### ISSUE TITLE
Improve rendering of variables view

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode-jupyter#10001]
## Environment data

-   VS Code version: 1.67.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.4.1011282140
-   Python Extension version (available under the Extensions sidebar): v2022.6.1
-   OS (Windows | Mac | Linux distro) and version: MacOS Big Sur
-   Python and/or Anaconda version: 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local 

## Expected behaviour

Variable view style is consistent with the rest of VSCode.

## Actual behaviour

It isn't and it has never been. 

<img width="709" alt="image" src="https://user-images.githubusercontent.com/2845433/168105166-6f1c97cf-35aa-4785-8f11-ec6294492f2b.png">

Look at the size of those headers. And the pitch black color. A slight decrease of font size and weight in the header would IMO improve the appearance.

**Comment by memeplex** [comment]
Indeed sometimes it seems like there is a slight zoom after the initial rendering:



https://user-images.githubusercontent.com/2845433/168107566-415bab83-8c0d-4723-9b4c-2ae1ca4b6ec7.mov

**Comment by IanMatthewHuff** [comment]
@memeplex Thanks for the report here. The variable viewer is implemented using a separate webview and (as you noted) does have some inconsistencies of look and feel with VS Code. We can keep this open as a suggestion for cleanup, though we may consider seeing if we can move from the webview to a native vscode control at some point instead of putting more cleanup work into the current view.

**Comment by memeplex** [comment]
Thanks @IanMatthewHuff. There's another related issue that would probably be addressed by moving to a native vscode control as you said, but perhaps I could file a different report for it:

<img width="87" alt="image" src="https://user-images.githubusercontent.com/2845433/168405420-1794e492-782a-4ce2-b4f0-683173345b3d.png">

It seems that the font is not monospaced so there's an alignment problem (look at the dots).

**Comment by memeplex** [comment]
@IanMatthewHuff upon further inspection, there is a notebook.outputFontFamily setting that notebook html output is ignoring (including the variables view as reported above), moreover there is notebook.markup.fontSize but no corresponding notebook.markup.fontFamily, which may be more appropriate for html output. This seems to me a problem in vscode general notebook support, not specific to the jupyter extension.

**Comment by roblourens** [comment]
This will become built-in to vscode, then it will match by default https://github.com/microsoft/vscode/issues/165445
