### ISSUE TITLE
The help pop up does not show up for method chains

### ISSUE THREAD

**Issue by joelostblom** [microsoft/vscode-jupyter#10004]
## Environment data

-   VS Code version: 1.67
-   Jupyter Extension version (available under the Extensions sidebar): v2022.4.1011282140
-   Python Extension version (available under the Extensions sidebar): v2022.6.0
-   OS (Windows | Mac | Linux distro) and version: PopOS 21.10
-   Python and/or Anaconda version: 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | local

## Expected behaviour

The help for the method would show up correclty

## Actual behaviour and step to reproduce

If I type the name of a top level object, the help bubble shows up fine:
![image](https://user-images.githubusercontent.com/4560057/168144471-e8f288ae-087b-4f1b-8ea1-d586b734255a.png)

If I chain a function to this object I get either just a single line in the help bubble, or the same message as for the parent object 
![image](https://user-images.githubusercontent.com/4560057/168144777-42716204-4c78-4c3d-97ad-4de94cb53c5b.png)

## Logs

The output pane is empty

**Comment by IanMatthewHuff** [comment]
Thanks for the report. Does the single line look like this?
![image](https://user-images.githubusercontent.com/812783/168147656-2300dea6-1c65-4c8d-b83b-258e89e0c56a.png)

I'm testing that against just a plain old .py file. When I do that I get the following:
![image](https://user-images.githubusercontent.com/812783/168147967-f35b66bf-1b68-4763-8ba1-cbe551723eb3.png)

I think the completion is correct (both are using the same Pylance extension to provide the help), but the wrapping seems a bit different in the Jupyter hosted case versus the .py file. Do you have a scenario for when you trigger seeing the parent DataFrame help? I've been playing around a bit and I always get one of the two completions seen above.

**Comment by joelostblom** [comment]
It happens to me occasionally using the same code you have there. I am not sure what is different. In general, I think it would be helpful to show the docstring for `.mean` instead of just the signature.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact taht the Jupyter extnsion does not offer completions (except for those from the kernel), I'm closing this issue.
I would suggest filing issues against the repo of the exnetion used to provide completions like pylance, or the like.
