### ISSUE TITLE
Remote kernel test is flakey

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10009]
Same test failed on two different runs:

![image](https://user-images.githubusercontent.com/19672699/168156725-ecf9aeef-fa81-45ba-bdf3-5fccf68f307d.png)

Here's an example:
https://github.com/microsoft/vscode-jupyter/runs/6412487044?check_suite_focus=true#step:38:38

**Comment by rchiodo** [comment]
Another instance:
https://github.com/microsoft/vscode-jupyter/runs/6412513755?check_suite_focus=true

**Comment by DonJayamanne** [comment]
Closing in favor or https://github.com/microsoft/vscode-jupyter/issues/10046
as there were a few PRs merged for that.
