### ISSUE TITLE
VS Code window hangs on notebook imports

### ISSUE THREAD

**Issue by somiandras** [microsoft/vscode-jupyter#10019]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

My Jupyter notebooks started to make the whole VS Code window hang, ie. it becomes totally unresponsive, and after a while VS Code offers to close/keep waiting/reload it. The sure way to replicate it for me is to start typing an import statement in a cell, like `from pandas.` and the UI will freeze by the time the autocomplete suggestions come up or when I keep on typing or if I try to select something from the pop-up list.

It all started yesterday (2022.05.12.). Newly created and my old (previously working) notebooks are all affected.

Visual Studio Code (1.67.1, undefined, desktop)
Jupyter Extension Version: 2022.4.1021342353.
Python Extension Version: 2022.6.2.

As the UI totally hangs I cannot copy text from the output panel, but nothing new appears after this (I checked other output panels, nothing changes right before/after the UI freezes):

<img width="950" alt="image" src="https://user-images.githubusercontent.com/12885402/168234706-57626319-63ba-48dd-aff8-08bd36e59130.png">

If you point me to some better ways I'll try and produce some more useful diagnostics.

### VS Code Version

 1.67.1 (Universal)

### Jupyter Extension Version

v2022.4.1021342353

### Coding Language and Runtime Version

Python 3.10.4

### Language Extension Version (if applicable)

2022.6.2.

### Running Jupyter locally or remotely?

Local

**Comment by kamfonas** [comment]
I had the exact same issue. I removed the PyLance extension per recommendation by @amunger and it seems to have fixed the problem. I cannot replicate the failure anymore.

**Comment by somiandras** [comment]
> this sounds like #9936. Can you try rolling back the Pylance extension to 2022.4.3 or earlier and check if it still reproduces?

This seems to have solved my issue, thanks. Closing this as it's clearly a duplication.
