### ISSUE TITLE
Notebooks open automatically

### ISSUE THREAD

**Issue by misha-antonenko** [microsoft/vscode-jupyter#10018]
Issue Type: <b>Bug</b>

The extension tries to contend with Jupyter I open in my browser by opening the same notebook and overwriting it, without any actions on my side whatsoever

Extension version: 2022.4.1021342353
VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:16.526Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.161-26.3

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id de7537ee-b7ff-4aa6-9ac1-40d3f0a20bb2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sdc-dev-container|
|OS|Linux x64 5.4.161-26.3|
|CPUs|Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (65 x 2095)|
|Memory (System)|156.41GB (11.25GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdc:30486549

```

</details>

**Comment by amunger** [comment]
Can you clarify what you are experiencing and provide steps to reproduce this issue?

**Comment by sadasant** [comment]
@misha-antonenko hello! Is my interpretation correct?

1. File “A” is open in the browser using Jupyter’s browser editor.
2. File “A” is also open on Visual Studio Code (or gets opened when Visual Studio Code is opened).
3. Visual Studio Code is overwriting file “A”, which does not reflect the status of “A” as it appears on the the Jupyter web editor.

Is that correct?
If so: Could it be that Visual Studio Code is set to automatically save the file? (check if it’s enabled by searching for “auto save” on the Visual Studio Code settings)

**Comment by amunger** [comment]
not enough info to investigate, so closing for now
