### ISSUE TITLE
Validating the remote uri can take too long

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10010]
Bring this up:

![image](https://user-images.githubusercontent.com/19672699/168158370-5a9a9d09-7dc1-4f1e-b7ab-9250accae645.png)

Hit enter.

For me it took 10 seconds before it went away. 

I think we need either a progress indicator or someway of checking the connection a lot faster.

**Comment by rebornix** [comment]
Starting with @DonJayamanne as it's about server connection.

**Comment by DonJayamanne** [comment]
Closing as the busy indicator has been added
