### ISSUE TITLE
Suggestion: Add cell code formatting functionality in Jupyter Notebook

### ISSUE THREAD

**Issue by iEuphoria** [microsoft/vscode-jupyter#1001]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by MaxGhenis** [comment]
Checking in as the https://github.com/microsoft/vscode-python/issues/10496 dependency is now closed

**Comment by IanMatthewHuff** [comment]
@MaxGhenis If you use the Jupyter Extension with VSCode-Insiders you should get the new notebook interface for .ipynb files by default. In that interface cell formatting should be supported. This new interface will eventually be rolling out to stable VS Code.

**Comment by asianboii-chen** [comment]
So has this feature been out yet? Thanks!
