### ISSUE TITLE
Enter key has no effect for jupyter instance specification if https is used instead of http

### ISSUE THREAD

**Issue by MovsisyanM** [microsoft/vscode-jupyter#10022]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I click the "Jupyter Server: local" button in the bottom right corner to specify the path to my already running jupyter instance, I write the path and hit enter, nothing happens. I should be able to connect and use an already running instance. 
When I enter a bogus path, it tells me that it didn't find the server specified (which is normal) 

### VS Code Version

Version: 1.67.1 (user setup) Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d Date: 2022-05-06T12:37:03.389Z Electron: 17.4.1 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Windows_NT x64 10.0.19044

### Jupyter Extension Version

2022.4.1021342353

### Jupyter logs

```shell
Visual Studio Code (1.67.1, undefined, desktop)
Jupyter Extension Version: 2022.4.1021342353.
Python Extension Version: 2022.6.2.
Workspace folder c:\Users\Mher.Movsisyan\Desktop\Projects\sandbox2
info 14:34:36.904: ZMQ install verified.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 14:34:39.665: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 14:34:40.558: Preferred Remote kernel for c:\Users\Mher.Movsisyan\Desktop\Projects\sandbox2\Hw11.ipynb is undefined
info 14:34:40.558: Find preferred kernel for c:\Users\Mher.Movsisyan\Desktop\Projects\sandbox2\Hw11.ipynb with metadata {"interpreter":{"hash":"ad2bdc8ecc057115af97d19610ffacc2b4e99fae6737bb82f5d7fb13d2f2c186"},"kernelspec":{"display_name":"Python 3.9.7 ('base')","language":"python","name":"python3"},"language_info":{"codemirror_mode":"r","file_extension":".r","mimetype":"text/x-r-source","name":"python","pygments_lexer":"r","version":"3.9.7"},"orig_nbformat":4} & preferred interpreter c:\Users\Mher.Movsisyan\AppData\Local\Programs\Python\Python310\python.exe
info 14:34:40.565: Preferred Remote kernel for c:\Users\Mher.Movsisyan\Desktop\Projects\sandbox2\Hw11.ipynb is undefined
info 14:34:40.565: Preferred kernel .jvsc74a57bd0ad2bdc8ecc057115af97d19610ffacc2b4e99fae6737bb82f5d7fb13d2f2c186.c:\ProgramData\Anaconda3\python.exe.c:\ProgramData\Anaconda3\python.exe.-m#ipykernel_launcher is exact match
info 14:34:40.566: PreferredConnection: .jvsc74a57bd0ad2bdc8ecc057115af97d19610ffacc2b4e99fae6737bb82f5d7fb13d2f2c186.c:\ProgramData\Anaconda3\python.exe.c:\ProgramData\Anaconda3\python.exe.-m#ipykernel_launcher found for NotebookDocument: c:\Users\Mher.Movsisyan\Desktop\Projects\sandbox2\Hw11.ipynb
info 14:34:40.566: TargetController found ID: .jvsc74a57bd0ad2bdc8ecc057115af97d19610ffacc2b4e99fae6737bb82f5d7fb13d2f2c186.c:\ProgramData\Anaconda3\python.exe.c:\ProgramData\Anaconda3\python.exe.-m#ipykernel_launcher for document c:\Users\Mher.Movsisyan\Desktop\Projects\sandbox2\Hw11.ipynb
info 14:34:40.969: Process Execution: > ~\AppData\Local\Programs\Python\Python310\python.exe -m pip list
> ~\AppData\Local\Programs\Python\Python310\python.exe -m pip list
info 14:34:41.774: Registering dummy command feature
info 14:34:46.457: Process Execution: > c:\ProgramData\Anaconda3\python.exe -m pip list
> c:\ProgramData\Anaconda3\python.exe -m pip list
info 14:34:50.414: Preferred Remote kernel for c:\Users\Mher.Movsisyan\Desktop\Projects\sandbox2\Hw11.ipynb is undefined
info 14:34:50.414: Find preferred kernel for c:\Users\Mher.Movsisyan\Desktop\Projects\sandbox2\Hw11.ipynb with metadata {"interpreter":{"hash":"ad2bdc8ecc057115af97d19610ffacc2b4e99fae6737bb82f5d7fb13d2f2c186"},"kernelspec":{"display_name":"Python 3.9.7 ('base')","language":"python","name":"python3"},"language_info":{"codemirror_mode":"r","file_extension":".r","mimetype":"text/x-r-source","name":"python","pygments_lexer":"r","version":"3.9.7"},"orig_nbformat":4} & preferred interpreter c:\Users\Mher.Movsisyan\AppData\Local\Programs\Python\Python310\python.exe
info 14:34:50.415: Preferred Remote kernel for c:\Users\Mher.Movsisyan\Desktop\Projects\sandbox2\Hw11.ipynb is undefined
info 14:34:50.415: Preferred kernel .jvsc74a57bd0ad2bdc8ecc057115af97d19610ffacc2b4e99fae6737bb82f5d7fb13d2f2c186.c:\ProgramData\Anaconda3\python.exe.c:\ProgramData\Anaconda3\python.exe.-m#ipykernel_launcher is exact match
info 14:35:12.734: Creating server with url : https://127.0.0.1:5858/
```

### Language Extension Version (if applicable)

v2022.6.2

### Running Jupyter locally or remotely?

Local

**Comment by MovsisyanM** [comment]
the 5858 port of my localhost is actually a tunneled port from a remote server (the server is the one running the jupyter notebook instance). I tunnel it myself and don't want vscode to tunnel to it.

**Comment by MovsisyanM** [comment]
Once i close the tunneled connection, then and only then vscode tells me that it couldnt connect
```
info 14:35:12.734: Creating server with url : https://127.0.0.1:5858/
warn 14:48:14.747: DataScience Error [r [Error]: 
	at new r (c:\Users\Mher.Movsisyan\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:999024)
	at Function.from (c:\Users\Mher.Movsisyan\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:999102)
	at _.setJupyterURIToRemote (c:\Users\Mher.Movsisyan\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:395433)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async _.selectRemoteURI (c:\Users\Mher.Movsisyan\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:397900)
	at async l.stepThrough (c:\Users\Mher.Movsisyan\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:924266)

FetchError: request to https://127.0.0.1:5858/api/kernels?1652438112796 failed, reason: read ECONNRESET
	at ClientRequest.<anonymous> (c:\Users\Mher.Movsisyan\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:4045126)
	at ClientRequest.emit (node:events:390:28)
	at TLSSocket.socketErrorListener (node:_http_client:447:9)
	at TLSSocket.emit (node:events:390:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)] {
  category: 'unknown',
  originalException: [FetchError: request to https://127.0.0.1:5858/api/kernels?1652438112796 failed, reason: read ECONNRESET
  	at ClientRequest.<anonymous> (c:\Users\Mher.Movsisyan\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:4045126)
  	at ClientRequest.emit (node:events:390:28)
  	at TLSSocket.socketErrorListener (node:_http_client:447:9)
  	at TLSSocket.emit (node:events:390:28)
  	at emitErrorNT (node:internal/streams/destroy:157:8)
  	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
  	at processTicksAndRejections (node:internal/process/task_queues:83:21)]
}
```

**Comment by amunger** [comment]
> hit enter, nothing happens

As in the quick pick menu doesn't even close? Or just that the "Jupyter Server: local" in the lower right doesn't change?

If you open the same endpoint in a browser on the same machine as VS code, does it load the web UI correctly?
Are there any logs from your Jupyter Server that show any connection?

**Comment by MovsisyanM** [comment]
The menu (the prompt at the top where I enter the path) doesn't close. The ui works fine and i can run things using my browser. I'll provide the jupyter server logs on monday.

**Comment by nbagiyan** [comment]
Same in VS Code: 

Version: 1.67.1 (Universal)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:16.526Z (1 wk ago)
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.3.0

Jupyter extensions v2022.4.1021342353
Python extensions v2022.6.2 

Tried to connect to existing remote jupyter. The quick pick menu doesn't even close after hitting enter

**Comment by MovsisyanM** [comment]
```
[I 09:12:48.053 NotebookApp] Serving notebooks from local directory: /home/mher
[I 09:12:48.053 NotebookApp] The Jupyter Notebook is running at:
[I 09:12:48.053 NotebookApp] http://localhost:8788/?token=ac282484941f902b7f715d15379f514a93bfa2e8d4f3d7c0
[I 09:12:48.053 NotebookApp]  or http://127.0.0.1:8788/?token=ac282484941f902b7f715d15379f514a93bfa2e8d4f3d7c0
[I 09:12:48.053 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 09:12:48.055 NotebookApp] No web browser found: could not locate runnable browser.
[C 09:12:48.055 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/mher/.local/share/jupyter/runtime/nbserver-596454-open.html
    Or copy and paste one of these URLs:
        http://localhost:8788/?token=ac282484941f902b7f715d15379f514a93bfa2e8d4f3d7c0
     or http://127.0.0.1:8788/?token=ac282484941f902b7f715d15379f514a93bfa2e8d4f3d7c0
[I 15:02:54.872 NotebookApp] Kernel started: 78a1a0e0-60a5-431f-95c2-b7221bbce6ca
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version
[I 15:04:54.901 NotebookApp] Saving file at /projects/REDACTED/WAAE_1m/WAAE_score_sandbox_113.ipynb
[I 15:06:54.914 NotebookApp] Saving file at /projects/REDACTED/WAAE_1m/WAAE_score_sandbox_113.ipynb
[I 15:08:54.917 NotebookApp] Saving file at /projects/REDACTED/WAAE_1m/WAAE_score_sandbox_113.ipynb
[I 15:10:46.098 NotebookApp] Saving file at /projects/REDACTED/WAAE_1m/WAAE_score_sandbox_113.ipynb
[I 15:12:26.187 NotebookApp] Starting buffering for 78a1a0e0-60a5-431f-95c2-b7221bbce6ca:83099bf8d7e441958ab9419fb0d2f53f

```

No extra lines are appended to this output file when I try to connect with vscode (unlike accessing it with my browser). I assume nothing gets sent over the network at all. The tunneled connection acts as if its blocking vscode.

**Comment by amunger** [comment]
@MovsisyanM (and anyone else hitting this) - Does your connection require a username and password? We might not be handling that case.

**Comment by MovsisyanM** [comment]
> @MovsisyanM (and anyone else hitting this) - Does your connection require a username and password? We might not be handling that case.

Yes

**Comment by amunger** [comment]
sounds like you're not using a password then, you don't really need one if you're using a token (I don't know if it's even possible to use both).

The "None" option just disconnects from any remote that you've previously selected.

**Comment by amunger** [comment]
A couple things you could try:
Switch to the pre-release version of the Jupyter extension and check if that changes anything. We've added some validation at that point, so you may see more info if something goes wrong.

Try using the web version at [vscode.dev](https://vscode.dev) and inspect the network traffic in developer tools. 
You should just be able to install the jupyter extension there and try the same command. You'll also need to add `--NotebookApp.allow_origin_pat=https://.*vscode-cdn\.net` to the jupyter server args (as specified in [the wiki](https://github.com/microsoft/vscode-jupyter/wiki/Connecting-to-a-remote-Jupyter-server-from-vscode.dev))

**Comment by amunger** [comment]
also, can you check if you have any special config settings and share those if possible? They should be in ~/.jupyter on the remote machine if you have anything

**Comment by MovsisyanM** [comment]
@amunger It started working! I used http instead of https :D. To make sure https was the problem I redid everything with https and it didn't work, so the problem was https. Thank you very much for your time.

**Comment by amunger** [comment]
Great to hear! I can repro the issue now with that info, so I'm going to leave this bug open since that experience is pretty confusing

**Comment by DonJayamanne** [comment]
@MovsisyanM Please could you replicate this issue with the latest version of VS Code and provide the verbose logs
See here for instructions to enable verbose logging.
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by MovsisyanM** [comment]
@DonJayamanne I can't attempt to reproduce this because I don't have the same equipment anymore

**Comment by DonJayamanne** [comment]
let's close this for now, please do ping when you run into this again
