### ISSUE TITLE
Support debugging of Interactive Window using the Jupyter debugger protocol

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#10037]
Basically implement debugging of IW using the same code used to enable debugging of notebooks.
* [x] https://github.com/microsoft/vscode-jupyter/issues/10037
* [ ] https://github.com/microsoft/vscode-jupyter/issues/10106
* [x] https://github.com/microsoft/vscode-jupyter/issues/10107

**Comment by roblourens** [comment]
I think this old issue was related to this task, maybe it's not relevant anymore: https://github.com/microsoft/vscode-jupyter/issues/7057

**Comment by DonJayamanne** [comment]
Closed #7057 with comments

**Comment by rchiodo** [comment]
This isn't actually working. There's a big problem that I see with the cell to file mapping. See this issue:
https://github.com/microsoft/vscode-jupyter/issues/10258

**Comment by DonJayamanne** [comment]
Curious, how are the tests passing for remote debugging?

**Comment by rchiodo** [comment]
I don't know. Didn't realize we had remote debugging tests. Or maybe they just test the simplest form.

**Comment by DonJayamanne** [comment]
Closing this issue as it has been completed.
