### ISSUE TITLE
'Restart' command doesn't auto-scroll to show up in the pane

### ISSUE THREAD

**Issue by david-cortes** [microsoft/vscode-jupyter#10031]
## Environment data

-   VS Code version: 1.67.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.4.1021342353
-   Python Extension version (available under the Extensions sidebar): v2022.6.2
-   OS (Windows | Mac | Linux distro) and version: linux (debian testing)
-   Python and/or Anaconda version: python 3.9.12, conda 4.11.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Steps to reproduce:
* Create an interactive jupyter window.
* Issue enough output to make the panel containing that window scrollable, and scroll to the end.
* Press the button "Restart" at the top of the interactive jupyter window.

## Expected behaviour

Should scroll down to the end, making the restart command visible in the outputs.

## Actual behaviour

Does not scroll, making it non-obvious from a quick visual perspective whether the button was clicked successfully and whether it worked or not.

![vscode_restart_doesnt_show](https://user-images.githubusercontent.com/11860098/168471286-ef14584b-116b-451d-bd9a-4a53a49f8d0b.gif)

**Comment by DonJayamanne** [comment]
Thanks, I can confirm this is a bug. 
I think the fix should be for us to scroll this cell (cell that contains the text indicating the status) into view

**Comment by greazer** [comment]
This is related to the other interactive window output scrolling issue we have in May.

**Comment by rchiodo** [comment]
This should be fixed by the auto scrolling added to VS code core.
