### ISSUE TITLE
Fill test hole for checking that dumpCell debugging files are deleted + re-enable debugging tests

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#10041]
Doing the work for https://github.com/microsoft/vscode-jupyter/issues/9973

I believe that we have a test hole for not checking to see if we delete the .py files we create during debugging. Also it looks like a number of the tests in debugger.vscode.test.ts are disabled or skipped. I'd like to add a test for temp file deletion and also revisit the skipped test as part of the work for #9973.

**Comment by roblourens** [comment]
I think it's just that those tests don't run in windows. I'd like to run this one on windows so I'll figure out what I need for that
