### ISSUE TITLE
Unable to select python kernel for my .ipynb jupyter notebook (in vs code 1.64.2)

### ISSUE THREAD

**Issue by Nihal-M** [microsoft/vscode-jupyter#10043]
Issue Type: <b>Bug</b>

I'm sometimes (seems random) unable to select my python kernel. The Select Kernel options shows an empty list and I don't see any of my anaconda environments there. I also tried setting the interpreter by providing the correct path to my conda env but that also doesn't seem to work.

Sometimes it does show up, but then on some days I face this problem. 

Please let me know if this is a bug and how to solve it?

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.13.0-40-generic
Restricted Mode: No
Remote OS version: Linux x64 4.18.0-193.28.1.el8_2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-1270 CPU @ 3.40GHz (16 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|62.53GB (47.68GB free)|
|Process Argv|--unity-launch --crash-reporter-id f2b6a001-1da9-4ce7-9f4c-850427bc4390|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: localhost_9996|
|OS|Linux x64 4.18.0-193.28.1.el8_2.x86_64|
|CPUs|AMD EPYC 7302 16-Core Processor (32 x 3290)|
|Memory (System)|251.75GB (28.49GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.80.0
js-debug-companion|ms-|1.0.17
gc-excelviewer|Gra|4.2.54
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by DonJayamanne** [comment]
This may have been fixed in the latest version.
Please could you update to the latest versions of VS Code, Jupyter & Python extensions.
If the problem persists, please feel free to re-open this issue or create a new one.

**Comment by Saurabhbaghel** [comment]
I am facing the similar problem cannot see the kernel. Even after giving in the complete path of the python it does not change the kernel. 
PS I have the latest vscode and extensions

![image](https://user-images.githubusercontent.com/93883934/211265936-cb020978-0b04-41d1-a431-4dd555828340.png)

**Comment by Vaunorage** [comment]
> I am facing the similar problem cannot see the kernel. Even after giving in the complete path of the python it does not change the kernel. PS I have the latest vscode and extensions
> 
> ![image](https://user-images.githubusercontent.com/93883934/211265936-cb020978-0b04-41d1-a431-4dd555828340.png)

Close the jupyter notebook file and open it again made it reapear for me

**Comment by NagiaKoushiou** [comment]
I also face the same problem!! deleted and downloaded everything again 
still not working 
<img width="1159" alt="Screenshot 2023-02-08 at 15 58 24" src="https://user-images.githubusercontent.com/93479116/217566248-a220daac-02d1-4bbc-b42c-4132cbeb6fab.png">

**Comment by dmelbs** [comment]
I am having the same problem!!! Please help!
<img width="686" alt="image" src="https://user-images.githubusercontent.com/91095587/217605724-def21f57-24da-4845-a876-fb295319baf7.png">

**Comment by dmelbs** [comment]
I have found a workaround... if you delete python and then delete visual studio code, upon reopening code if you try running code in a notebook it will recommend that you install needed dependencies. If you click to install and then try rerunning your code it should work. MUST DELETE EXTENSIONS BEFORE DELETING VSC!

**Comment by JackieMonster** [comment]
Yes， I also get the same problem. I just solve this problem by updating these extensions to the latest version.

-  Jupyter
- Python
- Pylance

**Comment by espoirMur** [comment]
Installing thoes extensions in both remote and local server seems to make things work.

> Yes， I also get the same problem. I just solve this problem by updating these extensions to the latest version.
> 
> * Jupyter
> * Python
> * Pylance

**Comment by vojtechkania** [comment]
> Yes， I also get the same problem. I just solve this problem by updating these extensions to the latest version.
> 
> * Jupyter
> * Python
> * Pylance

I have reinstalled all extensions and it worked just for the first time. When opened for the second time it has not worked. What should I do?

**Comment by vojtechkania** [comment]
> > Yes， I also get the same problem. I just solve this problem by updating these extensions to the latest version.
> > 
> > * Jupyter
> > * Python
> > * Pylance
> 
> I have reinstalled all extensions and it worked just for the first time. When opened for the second time it has not worked. What should I do?

I have found what the problem was. I had to mark some of my folders as confidential.

**Comment by Kovid141** [comment]
Go to Extension, Search Jupyter Notebook and click switch to prerelease version
![image](https://user-images.githubusercontent.com/29612547/224644413-db7f2568-50a5-4525-9ad1-1b81f0cb60bc.png)

**Comment by victorsanunes** [comment]
> Go to Extension, Search Jupyter Notebook and click switch to prerelease version ![image](https://user-images.githubusercontent.com/29612547/224644413-db7f2568-50a5-4525-9ad1-1b81f0cb60bc.png)

I had the same issue and this fixed it.

**Comment by MATLABmdl** [comment]
as victorsanunes said 
Go to Extension, Search Jupyter Notebook and click switch to prerelease version 
work for me and fix it

**Comment by drscotthawley** [comment]
I tried @Kovid141's solution of installing pre-release  but it says
"Can't install pre-release version of 'ms-toolsai.jupyter' extension because it is not compatible with the current version of Visual Studio Code (version 1.77.3)."

What can the rest of us do?   Please re-open this issue.

**Comment by cerealkella** [comment]
> I tried @Kovid141's solution of installing pre-release but it says "Can't install pre-release version of 'ms-toolsai.jupyter' extension because it is not compatible with the current version of Visual Studio Code (version 1.77.3)."
> 
> What can the rest of us do?

I'm facing this same issue on Manjaro, running version 1.77.1. I installed the Insiders Build using this command:
`yay -S visual-studio-code-insiders-bin`
Installed the python/jupyter extensions and it seems to be functioning as I would expect.
