### ISSUE TITLE
carriage return in interactrive window output?

### ISSUE THREAD

**Issue by ghylander** [microsoft/vscode-jupyter#10058]
Issue Type: <b>Bug</b>

There have been issues already regarding this, but I have found no definitive answer in them. All I found were closed with no comments, whteher it was fixed or won't be fixed.

Extension version: 2022.5.1001391015
VS Code version: Code - Insiders 1.68.0-insider (688c80245936b49b7ceca494d9edfe97cae06f8a, 2022-05-18T05:15:45.170Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.70GB (1.41GB free)|
|Process Argv|--crash-reporter-id 4285aea8-8024-49ba-97f2-9d60622a70f0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvspyt640:30438691
vscscmwlcmt:30465136
cppdebugcf:30475217
vsclangdc:30480125

```

</details>

**Comment by ghylander** [comment]
Purpose would be to have progress bars properly rendered (and not have a newline for every progress update, which could potentially be hundreds of newlines). In specific, I was trying to use the tqdm module, but I could see this happening with tensorflow and keras model.fit() loop, as it also creates an epoch progress bar
![image](https://user-images.githubusercontent.com/74593034/168975625-303d27d8-c530-4012-b8d9-de7a0cae2718.png)

**Comment by rchiodo** [comment]
Thanks for the issue. Do you have some code that repros the problem? 

I'd like to see if we're behaving different than jupyterlab in this case.

**Comment by ghylander** [comment]
hi, closing this since I upon doing some test I found out that the script I was trying to run had a 'no carriage return' print hidden that was causing the newline

fixed it and now it behaves as expected

sorry for the trouble
