### ISSUE TITLE
Exporting file as notebook drops comments on same line as cell delimiters

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-jupyter#10059]
Running

```sh
echo '# %% foo' > tmp.py
```

followed by opening it in VS Code and executing 'Jupyter: Export file as Notebook' from the command palette removes the comment.

![Screen Shot 2022-05-18 at 11 49 03](https://user-images.githubusercontent.com/30958850/169022302-e198e82a-60e3-4501-b0e1-c19fdb65a386.png)

Would be cool if it was placed at the start of a cell instead.

![Screen Shot 2022-05-18 at 11 51 27](https://user-images.githubusercontent.com/30958850/169023144-483422a1-b42e-4a95-ac29-2403723eb62a.png)

**Comment by rchiodo** [comment]
Thanks for the suggestion. I thought we used to do this, but maybe I'm remembering wrong. 

What would you want the comment to look like? 

This?
```
# %% foo
```
or this?
```
# foo
```

Cell delimiters feel a little weird in a notebook, but maybe it doesn't matter. 

Then there's also the problem of round tripping. If that comment is there, we'd have to detect or remove it when converting back to python.

**Comment by DonJayamanne** [comment]
Thanks for the suggestion, however this issue has not received enough upvotes since the time it was created.
Closing this issue for now.
