### ISSUE TITLE
Same display name for different venv kernels

### ISSUE THREAD

**Issue by abhimanyu-bitsgoa** [microsoft/vscode-jupyter#10064]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Hi!

We have a few venv setups in different folders for our project.
Now, the notebook Kerner picker used to display them with the corresponding path name. So it was clear to select the one we needed, as shown in the picture below:

![Inkeditems](https://user-images.githubusercontent.com/13154079/169297447-5bcdd9c1-7dce-4a61-a9fa-ce39bbb2a672.jpg)

But now, the entire path is no longer displayed, making our selection ambiguous, as shown below:

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/13154079/169297772-027b7871-2aae-44a0-8a24-d3841d570ff3.png)

Can you please tell if this is due to some recent change? 

Thanks.

### VS Code Version

1.67.2

### Jupyter Extension Version

v2022.4.1021342353

### Jupyter logs

```shell
N/A
```

### Coding Language and Runtime Version

Python 3.7.13

### Running Jupyter locally or remotely?

Local

**Comment by IanMatthewHuff** [comment]
@abhimanyu-bitsgoa Thanks for reporting. It's not intentional. We always want to give enough info to distinguish envs. From the looks of it this is specifically for poetry envs? Could you please save off the full contents of the Output -> Jupyter section in VS Code to a file and attach that to a comment here? Should give me more info that I would need to help debug this.

**Comment by lordmauve** [comment]
We see this for normal virtualenvs. It looks exactly the same but shows under a heading "Virtual Env" instead.

**Comment by lordmauve** [comment]
My "Output -> Jupyter" log:

```
Visual Studio Code (1.67.2, ssh-remote, desktop)
Jupyter Extension Version: 2022.4.1021342353.
Python Extension Version: 2022.6.3.
Multiple Workspace folders opened /home/mauve/gits/aie-0000/tml/core, /home/mauve/gits/aie-0000/tml/docs, /home/mauve/gits/aie-0000/tml/interactive, /home/mauve/gits/aie-0000/tml/offlineproduction, /home/mauve/gits/aie-0000/tml/serialization
info 11:20:28.855: ZMQ install verified.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 11:20:30.712: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 11:20:30.952: Process Execution: > ~/gits/aie-0000/tml/core/.venv/bin/python -m pip list
> ~/gits/aie-0000/tml/core/.venv/bin/python -m pip list
info 11:20:31.374: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 11:20:31.375: Find preferred kernel for Untitled-1.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"python"}} & preferred interpreter /home/mauve/gits/aie-0000/tml/core/.venv/bin/python
info 11:20:31.378: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 11:20:31.378: Preferred kernel .jvsc74a57bd01f60016f6f2423cf28ef47be1905c94d5a1cb5d2b4fd0540ecda31831506d1e9./home/mauve/gits/aie-0000/tml/core/.venv/python./home/mauve/gits/aie-0000/tml/core/.venv/python.-m#ipykernel_launcher is exact match
info 11:20:31.378: PreferredConnection: .jvsc74a57bd01f60016f6f2423cf28ef47be1905c94d5a1cb5d2b4fd0540ecda31831506d1e9./home/mauve/gits/aie-0000/tml/core/.venv/python./home/mauve/gits/aie-0000/tml/core/.venv/python.-m#ipykernel_launcher found for NotebookDocument: Untitled-1.ipynb
info 11:20:31.379: TargetController found ID: .jvsc74a57bd01f60016f6f2423cf28ef47be1905c94d5a1cb5d2b4fd0540ecda31831506d1e9./home/mauve/gits/aie-0000/tml/core/.venv/python./home/mauve/gits/aie-0000/tml/core/.venv/python.-m#ipykernel_launcher for document Untitled-1.ipynb
info 11:20:32.71: Registering dummy command feature
info 11:20:36.507: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 11:20:36.507: Find preferred kernel for Untitled-1.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"python"}} & preferred interpreter /home/mauve/gits/aie-0000/tml/core/.venv/bin/python
info 11:20:36.510: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 11:20:36.510: Preferred kernel .jvsc74a57bd01f60016f6f2423cf28ef47be1905c94d5a1cb5d2b4fd0540ecda31831506d1e9./home/mauve/gits/aie-0000/tml/core/.venv/python./home/mauve/gits/aie-0000/tml/core/.venv/python.-m#ipykernel_launcher is exact match
```

**Comment by DonJayamanne** [comment]
@abhimanyu-bitsgoa @lordmauve 

I believe this has been resolved in the latest pre-release version of the Jupyter extension.
Please install the lates vscode-insiders and pre-release versions of Jupyter and Python extensions to verify this.]

Closing this as fixed. If the issue still persists, please feel free to re-open the issue, or create a new issue or just ping here.
