### ISSUE TITLE
Remove Interactive Window's dependency on Python extension 

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#10085]
If you try to create an IW without the Python extension installed and haven't specified a remote connection, we will display a prompt saying that the Python extension is required.

That isn't really true since they could alternatively specify a remote jupyter connection, but they could also just specify a kernel to use, rather than requiring that they have an active interpreter.

We could probably re-use the same flow as the notebook and open the quickpick to choose a kernel and display the same error message if there isn't one to connect to.

**Comment by rchiodo** [comment]
We likely need to do this for the web case.
