### ISSUE TITLE
Log parsing extension

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10080]
Logs in CI are rather large and difficult to find things.

One idea to alleviate this would be to provide an extension that would:

- Create an outline provider which provides an outline based on all the tests in the log
- Not sure if that automatically creates folding regions or not, but if not the extension would automatically create folding regions in the log
- Extension would detect .log file extension and then parse to see if it's a CI log

**Comment by rebornix** [comment]
Since we are opening the logs in the editor, we can leverage the editor apis:

* Highlight the test result summary (how many fail and who fail), give them a red background, through decoration api
* Links to the test itself (which has call stacks) through link provider api
