### ISSUE TITLE
ActiveEditorContext needs to be replaced with a more general per editor context for some commands

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#10081]
In our package.json we are enabling / disabling the visibility of many editor toolbar commands based on context keys from ActiveEditorContext. However active editor context is not always the right thing when document are side by side. I believe we can get around this as in context keys we have access to the URI of the current document. If we have a general Editor Context service we can contribute URIs using the same general functions but add them to context key lists. Then we can us 'in' in the when context commands to check if documents should show or not show icons.

Example here:

R Notebooks Don't support variables (note that the R document is the active document):
![image](https://user-images.githubusercontent.com/812783/169591256-e5583fb3-08b6-4772-9ffd-5b9d96139b1c.png)

Now the python document is the active document. Click the overflow on the R document...variables are an options since clicking overflow doesn't make is the active document:
![image](https://user-images.githubusercontent.com/812783/169591392-e87ab26a-570f-4e34-866a-6afc393c6257.png)

**Comment by IanMatthewHuff** [comment]
I don't see this causing a ton of customer issues, but does feel like something we should clean up sooner rather than later.

**Comment by DonJayamanne** [comment]
Fixed
