### ISSUE TITLE
Using `require` to inject file contents into JS files causes issues with unit tests

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#10094]
We cannot write unit tests for some files if using code as follows:
```typescript
const addRunCellHook = require('../../pythonFiles/vscode_datascience_helpers/kernel/addRunCellHook.py');
```

* We might want to consider removing such webpack specific code from our code and use some other way to inject the file contents. 
* Or we need way another way to write unit tests for such files.
* Or we could have a simple provider that provides the contents of these files.
* We end up duplicating the files (its in the source code as well as vsix)

**Comment by rchiodo** [comment]
Not sure why this breaks anything? Does the require fail in a unit test?

**Comment by DonJayamanne** [comment]
> Does the require fail in a unit test?

Yes.
Can we not inject he IFileSystem to read the file contents using the Uri instead of using `require`.

**Comment by rchiodo** [comment]
Hmm, I think the file system could read it from the extension URI. I don't think these need to be embedded.

**Comment by DonJayamanne** [comment]
Yes agreed, 
was writing some tests for IKernelProvider and found bugs (bugs in the actual code), 
however the web scenario isn't covered by tests due to this issue
I would feel lot more comfortable knowing the web version too has some tests.

**Comment by rchiodo** [comment]
@sadasant's other fix in this area should be applicable.
