### ISSUE TITLE
Add tests for IW debugger using the Jupyter Protocol on the web

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#10107]
* [x] Test debugging local connections using the Jupyter protocol (done here [#10263](https://github.com/microsoft/vscode-jupyter/pull/10263))
* [x] Test debugging remote connections using the Jupyter protocol (done here [#10263](https://github.com/microsoft/vscode-jupyter/pull/10263))
* [ ] Test debugging remote connections using the Jupyter protocol on the web

Blocked on [Add tests for IW on web](https://github.com/microsoft/vscode-jupyter/issues/10296)

**Comment by rchiodo** [comment]
I assume this isn't actually done?

**Comment by connor4312** [comment]
@DonJayamanne this seems like a debt item--if not, are there verification steps for this?
