### ISSUE TITLE
Where is IntelliSense  in jupyter

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode-jupyter#10126]
I don't know whether it's the update of vscode or the update of jupyter extension. I cannot get auto-complete reminding as the following picture:

![image](https://user-images.githubusercontent.com/100815370/170159159-2eb12c26-6528-4bf3-aae4-f82ec49fb238.png)

This is also the case when I use "Ctrl + space". If I don't use it, it doesn't even have any prompt.

I have tried the recent version of jupyter, but it doesn't work.

Thank you for any help.

**Comment by czephyr** [comment]
@rchiodo Do you know anything about auto-imports from py-lance not working? 
https://stackoverflow.com/questions/72353286/how-can-i-get-pylance-auto-imports-on-jupyter-notebook-vscode/72385652#72385652

**Comment by rchiodo** [comment]
That depends. They should work. What does your entire notebook look like?
