### ISSUE TITLE
No indicator if the user does not answer to the request to use the CDN

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#10129]
The first time rendering a plot, let's say with the following code on a `ipynb` file:

```py
import numpy as np
from bqplot import pyplot as plt

# And creating some random data
size = 100
np.random.seed(0)
x_data = np.arange(size)
y_data = np.cumsum(np.random.randn(size)  * 100.0)
plt.figure(title='My First Plot')
plt.plot(x_data, y_data)
plt.show()
```

Users get asked whether they want to use CDN or not, via the `Datascience.useCDNforWidgets`.

If users do not answer this notification, eventually the timeout stops, the plot isn't rendered, and errors begin to appear in the developer console. Some of which are:

```
scriptManager.ts:126 Timeout waiting to get widget source for bqplot, ^0.5.34
VM32:1965          GET https://file+.vscode-resource.vscode-cdn.net/<path>/bqplot.js net::ERR_ABORTED 401
Could not instantiate widget
Error: Module bqplot, semver range ^0.5.34 is not registered as a widget module
```

There could be a better message telling users to decide whether to accept or reject using CDNs.

## Environment data

-   VS Code version: latest
-   Jupyter Extension version (available under the Extensions sidebar): main branch.
-   Python Extension version (available under the Extensions sidebar): latest.
-   OS (Windows | Mac | Linux distro) and version: OSX (but should be the same in any OS).
-   Python and/or Anaconda version: Python 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): NA
-   Jupyter server running: Remote (local server, used via token URL).

## Expected behavior

If the user does not interact with the notification request to use the CDN, there should be a better message of why their plots (and other features) won't work properly.

## Actual behaviour

Eventually the timeout ends and we begin getting errors in the console.

## Steps to reproduce:

1. Make sure to be in a clean environment where this notification hasn't been interacted with.2. 
  - Opening the developer tools at this point will show the problem more clearly.
2. Run some code in an `.ipynb` file to render a plot.
3. Wait for the notification to appear, asking to allow CDNs.
4. Do not interact with the notification for 30 seconds or so (until the errors begin appearing in the developer console).

**Comment by DonJayamanne** [comment]
This has been resolved, as the request for access to CDN is now a modal dialog.
