### ISSUE TITLE
Cached kernel is not cleared on reload after jupyter uri provider clears it

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#10133]
* Register a `IJupyterUriProvider` which implements `getHandles` and returns non empty handles arrary
* Connect to handle provided by this `IJupyterUriProvider`, execute cell
* Clear the handles in the `IJupyterUriProvider`
* Reload the window, the `IJupyterUriProvider` will now return empty array in `getHandles`
* The Jupyter extension still creates controller for the kernel used in last session, though the `IJupyterUriProvider` says now we don't have the server for it anymore

**Comment by DonJayamanne** [comment]
this should be fixed with the latest changes
