### ISSUE TITLE
linter should prevent *.vscode.web.test files from importing node modules

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#10150]
Our web test files can currently import node modules without any warning

**Comment by DonJayamanne** [comment]
@amunger 
I think this should be possible and shoudln't be a problem.
Would be good to know exactly what should be disabled or why (i'm assuming you ran into some problem).

E.g. tests should be able to import `sinon` or other node modules.

**Comment by amunger** [comment]
for example, `helpers.node`, or any of our node specific modules, can be imported from a web or common test. It mostly helps for trying to migrate node tests to the web as well when stripping out those dependencies.

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/microsoft/vscode-jupyter/issues/9891
