### ISSUE TITLE
Circular dependencies / Tangles between modules

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#10152]
As we introduced the top/primitive components via https://github.com/microsoft/vscode-jupyter/issues/8976 and moved the moduels/helpers to their logical folders, we had circular dependencies between the top components. Below is a simplified version of component dependnecies generated by Structure101

<img height=500 src="https://user-images.githubusercontent.com/876920/170587008-823b5235-b2bc-44f4-b127-53c28ad26d66.png" />

We want to gradually remove the dependencies in wrong directions, including

* No dependencies on `notebooks`/`iw`/`webview` in `platform`
* No dependencies on `iw` in notebooks
* Move feature code/helpers from `telemetry` to feature components. `notebooks`/`iw`/`webview` depends on `telemetry` but not the other way around
* ...

With above items tackled we could end up with an ideal architecture like below (we still need to revisit if it fits)

<img height=600 src="https://user-images.githubusercontent.com/876920/170587745-1eea3167-ad28-4945-aaed-57049ee26ca3.png" />

**Comment by rebornix** [comment]
While moving towards the ideal infrastructure, we might find our changes/PRs get really large even for fixing a single layer breaking relationship (e.g., remove `webviews` dependencies from `kernels`). To ensure us together contribute to the refactoring without stepping on each other's feet too often, we could take steps, from straightforward ones (`telemetry`, `api`), to layer protection through eslint rules and lastly a set of new top components.

## Separate feature and infra code

- [ ] Telemetry should only depend on `platform` component
  - [ ] Move `InterpreterPackageTracker` and `ImportTracker` out of `telemetry`
  - [ ] Move `sendKernelListTelemetry` and kernel types from `telemetry` to `kernels`
  - [ ] Move `splitMultilineString` to `platform` or helper (currently it's imported from `webviews`)
- [ ] API currently consists of core typings and API exposed to external extensions, these should be split into two components
  - [ ] Core typings in `platform`
  - [ ] Top component as `api`. No dependencies from `notebooks/kernel/webviews/iw` to `api`
- [ ] Logging
  - [ ] Move `GitHubIssueCodeLensProvider` and `GitHubIssueCommandListener` out of `platform/logging`
  - [ ] Move `LogReplayService` out of `intellisense` 

## Layer protections

- [ ] :runner: no dependents on `interactive-window` 
  - [x] `notebooks` does not depend on `iw` [vscode-jupyter#10153](https://github.com/microsoft/vscode-jupyter/pull/10153)
  - [ ] no `webview` dependencies (move webview related helpers into `platform`)
- [ ] `notebooks` depend on `kernels` only
  - [ ] Move Variables related functionalities (which read notebook*, kernels and webview types) out
  - [ ] Move ipywidgets message coordination code out of `kernel`
  - [ ] Move debugging/execution common helpers from `notebooks` to `kernel`
  - [ ] Register Intellisense provider in `intellisense`

## Extend top components

Currently components which depend on multiple primitive components (`kernels`/`notebooks`) are placed in multiple places (i.e., `platform/*`). We may want to move them out of the primitive components and group them together. These features/components include:

- [ ] Variable View
- [ ] Plot Viewer
- [ ] Ipywidgets
- [ ] Commands (Export, SaveSVG, etc)
- [ ] API
- [ ] Extension recommendation

**Comment by rebornix** [comment]
Discussed with @rchiodo offline about how we measure the success of the refactoring. The strategy we are talking here is clear (mostly adapting the eslint rules https://github.com/microsoft/vscode-jupyter/issues/9891 for layer protection and ensure we have minimal bundle size https://github.com/microsoft/vscode-jupyter/issues/10307), we would have better code structure and smaller bundle size (meaning faster download and activation) but at the same time we could use a few other metrics to validate how the refactoring goes. This is not scientific and we will explore what other potentials the refined architecture can give us in return.

- Clear component dependencies and architecture diagrams
  - Structure101 tangle analysis 
  - Dependency graph generated through https://github.com/microsoft/vscode-jupyter/tree/main/docs
- Bundling
  - Tree shaking unused third-party npm packages and also ensure desktop-only code are not being bundled into web https://github.com/microsoft/vscode-jupyter/issues/10307
  - Dead code removal through https://github.com/jrieken/ts-unused
- Code is easier to contribute to for new beginners
- PRs are relatively smaller and fewer layer breaking. It would take time to measure and compare but what we would love to see is fewer giant PRs touching multiple components (but we will still have quite some for new features)
- Ideas
  - We could cherry-pick layers and bundle them and test specifically against these layers. This can give us a sense of whether our components are decoupled properly and dependent components introduce unwanted side effects on base components

**Comment by rebornix** [comment]
Update of structure101 analysis

**_Before (release branch)_**

<img width="401" alt="image" src="https://user-images.githubusercontent.com/876920/174692214-d252d11a-f707-488b-9c33-4d1c738e9365.png">


**_Now (main, June 20)_**

<img width="456" alt="image" src="https://user-images.githubusercontent.com/876920/174692141-38f47bf8-c324-4f6c-9938-298618a61039.png">

**Comment by rebornix** [comment]
<img width="370" alt="image" src="https://user-images.githubusercontent.com/876920/175662553-7c1485cc-0e24-4be1-b112-4fdb98a6c578.png">

**Comment by DonJayamanne** [comment]
Does it matter how the internal code of the individual components reference each other? 
I didn't think they are not components in their own right, hence I do'nt think they are governed by the same rules.
E.g. does it matter if the languages & telemetry have references to controllers in nbotebooks & vice versa in the `notebooks` components?

**Comment by rebornix** [comment]
> Does it matter how the internal code of the individual components reference each other?

My short answer is not always. The tangles from structure101 can be used as indicators for how decoupled a component is and can be used as one approach to improve the code. There are good discussions in VS Code https://github.com/microsoft/vscode/issues/140874 about if/why/how of using structure101 to analyze and improve VS Code's code base.

> I didn't think they are not components in their own right, hence I do'nt think they are governed by the same rules.

I agree and I don't think we should enforce any layering concepts inside top components. 0 tangle is also not what we would try to archive. The goal IMHO should be better readability.

Based on my experience of the last two months, the tangles shown by structure101 (or a super-restrict eslint rule) helped find code that are placed in wrong folders/modules.

**Comment by DonJayamanne** [comment]
@rebornix please could you check if there's more work remaining here, if there is please could you document this so that we can resolve them and close this issue

**Comment by rebornix** [comment]
@DonJayamanne we can sit together and revisit this issue later this month.

**Comment by DonJayamanne** [comment]
Given that we're not doing anything actively in this space, lets close this for now.
