### ISSUE TITLE
Test jupyter kernel completions in web

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10166]
Testing the jupyter web extension providing completions when typing in a notebook.

Refs: #9977

- [x] anyOS @isidorn 
- [x] anyOS @rzhao271 

Complexity: 3

Authors: @rchiodo

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2310166%0A%0A&assignees=rchiodo)

---

### Requirements

- Install prerelease jupyter extension into http://insiders.vscode.dev
- Have a python environment that you can run jupyter from. (https://jupyter.org/install)
- install pandas into that environment as well
- Be familiar with jupyter notebooks

### Pre test steps

1. Go to a command prompt 
2. Activate the python environment with jupyter in it
3. Run jupyter with the following command line : `jupyter notebook --no-browser --NotebookApp.allow_origin=*`
4. Note the URL it generates for connecting
5. Start insiders.vscode.dev
6. Make sure Jupyter prerelease extension is installed
7. Bring up command palette
8. Pick 'Jupyter: Specify jupyter server for connections'
9. Pick 'Existing'
10. Enter the URL from step 4

### Test kernel completions

1. Open a new notebook
2. Pick the 'Python 3' kernel 
3. Add some code 
4. Run a cell
5. Create a new cell with 'import pandas as pd'
6. On the next line, type 'pd.'
7. Verify that you get completions for pandas
8. Try loading a CSV file in pandas (or create a dataframe with columns)
9. Verify that you can get 'column' completions. For example, if you create a dataframe named df, typing `df.` should list the columsn of the dataframe.

**Comment by rchiodo** [comment]
Your version of jupyter may not support that command line. Try running `python -m jupyter notebook --help` and see what it prints out. 

You do need the `allow_origin` setting or it won't work. I know they are moving that to a `--ServerApp.allow_origin` but that should print out a warning message? I get this:

[W 2022-05-31 09:22:57.678 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.

**Comment by isidorn** [comment]
Thanks for your reply. I just installed the jupyter version today, so I thought it is up to date. Here's what I get as output

![Screenshot 2022-05-31 at 19 06 13](https://user-images.githubusercontent.com/1926584/171232785-649761e5-b5b2-4ec0-8523-17106ab7e944.png)

**Comment by rzhao271** [comment]
LGTM. For the completions, I had to first run the cell, and then I got completions, but I was working in an untitled notebook.

For the environment, I set up a new venv environment, activated it, and then installed a bunch of libraries. On Windows, I ran the following commands in a new folder specifically for this issue:

```pwsh
python -m venv .venv
.\.venv\Scripts\activate
python -m pip install jupyterlab notebook voila pandas
```

**Comment by isidorn** [comment]
@rchiodo I just followed the steps @rzhao271 provided and I still get the same error. So here are the exact steps

```
python -m venv .venv
source .venv/Scripts/activate
python -m pip install jupyterlab notebook voila pandas
jupyter notebook --no-browser --NotebookApp.allow_origin=*
```

And I get the error from yesterday
"zsh: no matches found: --NotebookApp.allow_origin=*"

Let me try to swap with somebody for a test plan item...

**Comment by rchiodo** [comment]
Maybe your version of python is 2.7. It's no longer supported but is the default on Mac I think.

**Comment by isidorn** [comment]
When I do `python --version` in the terminal it says
`Python 3.8.9`
python -m also points to python version 3

**Comment by rchiodo** [comment]
What about this?
`python -m notebook --version`

**Comment by rchiodo** [comment]
Maybe `jupyter-notebook` is somewhere else on the path. What does `which jupyter-notebook` give you? For me it's in the environment I'm running.

**Comment by rchiodo** [comment]
Okay super weird. Wait, you're using .pyenv? That's not likely the matching/correct jupyter. Certainly not the same one you showed before.

**Comment by isidorn** [comment]
Yes, I started using .pyenv out of desperation because I could not get things to work.
Now that I have it, at least `jupyter notebook` command seems to work

**Comment by rchiodo** [comment]
We finally figured it out. For some reason on Isidor's machine, it needs this `jupyter notebook --no-browser --NotebookApp.allow_origin='*'`. Quotes around the * in the allow_origin.

**Comment by isidorn** [comment]
Thanks for all the help here, appreciate it.
I tested it and it works nicely.
