### ISSUE TITLE
Plot viewer: when deleting the rightmost image, no remaining image is focused

### ISSUE THREAD

**Issue by 2-5** [microsoft/vscode-jupyter#10169]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

If you have multiple images in the plot viewer and you delete the rightmost one (last one), no other remaining image is focused.

Steps:

1. open 4 images to the plot viewer
2. select the 3rd one
3. click the delete button repeatedly because you want to delete all of them
4. you'll notice after clicking delete 2 times that you'll be unfocused, despite there being 2 remaining images
5. you need to focus one image again to resume deleting them

Suggestion: When deleting the rightmost image, focus on the new rightmost one instead of leaving the image list without a focused image.

### VS Code Version

Version: 1.67.2 (user setup) Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5 Date: 2022-05-17T18:15:52.058Z Electron: 17.4.1 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Windows_NT x64 10.0.19044

### Jupyter Extension Version

v2022.4.1021342353

**Comment by amunger** [comment]
Thanks for the suggestion, that makes sense.

**Comment by DonJayamanne** [comment]
Thanks for reporting this issue, however given the fact that no one else has reported this and there have been no upvotes for over a year, I'm going to close this issue.
