### ISSUE TITLE
Typo in "Failure to start kernel due to failures in importing modules" wiki page

### ISSUE THREAD

**Issue by ExEr7um** [microsoft/vscode-jupyter#10171]
There are multiple typos in [Failure to start kernel due to failures in importing modules](https://github.com/microsoft/vscode-jupyter/wiki/Failure-to-start-kernel-due-to-failures-in-importing-modules) wiki page.

First one is in module name `pytprocess`, it should be `ptyprocess`.

Second one:

```diff
# if using a non-conda environment
- python -m pip install <xyz> -U --fore-reinstall
+ python -m pip install <xyz> -U --force-reinstall
# If using a conda environment
conda install --name <environment name> <xyz> --update-deps --force-reinstall
```

**Comment by DonJayamanne** [comment]
Thanks for filing this issue. 
I believe I've addressed the issues.  if there are more, please feel free to either re-open this or create a new issue.
