### ISSUE TITLE
Test Export in web

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#10183]
Refs: #9996

- [x] web @weinand 
- [x] web @joyceerhl  

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2310183%0A%0A&assignees=rebornix)

---

### Requirements

- Install prerelease jupyter extension into http://insiders.vscode.dev
- Have a python environment that you can run jupyter from. (https://jupyter.org/install)
- Be familiar with jupyter notebooks

### Set up

1. Go to a command prompt where you've installed jupyter into a python environment
2. Switch to a folder you're using for testing
3. Run jupyter with the following command `jupyter notebook --no-browser --NotebookApp.allow_origin=*`

### Test Steps

1. Open insiders.vscode.dev and create a new ipynb file
2. Open the file (which should open it in notebook editor)
3. Create a few cells
4. Connet to the jupyter server:
    1. Run the 'Jupyter: Specify jupyter server for connections' command, or use the link from the IW's info message
    2. Pick 'Existing'
    3. Paste the URL from the jupyter notebook server you started in step 3 of the setup
5. Run a few cells from the notebook file
6. Open command palette and then search for commands: `Jupyter: Export to HTML`, `Jupyter: Export to Python` and `Jupyter: Export to PDF`

Please test you can run those commands and have files saved into the workspace after the file successfully run. Note that exporting to PDF requires latex packages installed on your machine, it's fine it doesn't work but expect the error messages are intuitive.

**Comment by alexr00** [comment]
I'm probably just a jupyter noob, but I hit https://github.com/microsoft/vscode-jupyter/issues/10262 and couldn't finish testing.

**Comment by rchiodo** [comment]
@alexr00 my guess is your jupyter install is missing something.
