### ISSUE TITLE
Jupyter Variables view stays Loading forever

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-jupyter#10187]
Testing #10184

Everything in the test plan item works great until I run `Jupyter: Focus on Variables View`. The view stays this way:

![image](https://user-images.githubusercontent.com/22350/171170158-d21f8e2b-00a6-4900-b20b-ba3d3dda0af5.png)

As soon as I hit Play ▶️, debugging stops and the view completes:

![image](https://user-images.githubusercontent.com/22350/171170243-15fd55ab-1bb7-45af-9d76-b09d2dd9fd86.png)

**Comment by greazer** [comment]
This should be fixed with latest bits.

**Comment by joaomoreno** [comment]
@greazer Adding `bug` so someone verifies that.
