### ISSUE TITLE
cells aren't recognized

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-jupyter#10197]
Testing #10164

https://user-images.githubusercontent.com/29464607/171260954-0275ed23-0b96-4035-b333-1f5ea54c6d03.mov

**Comment by amunger** [comment]
try putting the code on the line after the `# %%` marker, otherwise it's just part of the comment. e.g.

```
# %%
print(1)

**Comment by meganrogge** [comment]
nothing is happening still when I run that

**Comment by meganrogge** [comment]
but I see this log:

```
info 14:44:10.180: Starting interactive window for resource '/Users/meganrogge/Repos/WorkspaceLaunchTaskDemo/test.py'
```

**Comment by rchiodo** [comment]
Something is weird in the GIF. There is NO colorization whatsoever on the python file. VS code ships with a tmlanguage file for python so it should colorize it? Is it possible to turn that off?
