### ISSUE TITLE
Connect to existing server quick pick loading bar goes forever if clipboard access is denies

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10192]
Testing #10170

Related to https://github.com/microsoft/vscode-jupyter/issues/10191, I pressed reject, get this notification and then can't seem to connect at all? Is there an exception to catch here in the exthost to continue on without clipboard access?

<img width="713" alt="Screen Shot 2022-05-31 at 10 19 25 am" src="https://user-images.githubusercontent.com/2193314/171234913-e51f01b2-e735-4449-9373-c8db1c894c6a.png">

**Comment by rchiodo** [comment]
In the desktop version we never hit this situation because clipboard permission wasn't necessary. Looks like we need to special case this situation. It certainly shouldn't fail if the user denies clipboard permission.
