### ISSUE TITLE
Suggestion: Query clipboard permissions when opening an existing server instead of always prompting

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10191]
Testing https://github.com/microsoft/vscode-jupyter/issues/10170

I find the setting up Jupyter experience kind of complicated. Have you considered doing a soft permissions query instead of a hard text read when connecting to avoid this prompt? Additionally, it would be better from a user's perspective imo to ask for the clipboard on ctrl/cmd+v, not when clicking some button.

<img width="891" alt="Screen Shot 2022-05-31 at 10 12 11 am" src="https://user-images.githubusercontent.com/2193314/171233681-12599ddc-9f97-4272-b757-44eb53cda5ad.png">

```
navigator.permissions.query({ name: 'clipboard-read' }).then(console.log)
```

**Comment by greazer** [comment]
nb-golden due to #10192

**Comment by connor4312** [comment]
This didn't work unless I added the setting referenced in https://github.com/microsoft/vscode-jupyter/issues/10363#issuecomment-1197392852, I assume that's implied?

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/2230985/181378594-90fdc6bb-c654-403b-9c30-c132494ece97.png">

**Comment by rchiodo** [comment]
Yeah sorry. I closed all of these bugs before we added the setting.
