### ISSUE TITLE
Should the user be able to give aliases to servers?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10195]
Testing https://github.com/microsoft/vscode-jupyter/issues/10170

I was expecting a pencil icon here that lets me give it a nice name. Not sure how useful this is in practice though.

<img width="608" alt="Screen Shot 2022-05-31 at 10 39 40 am" src="https://user-images.githubusercontent.com/2193314/171245893-3676a66b-49a2-4554-b1b2-87f545314ca9.png">

**Comment by IanMatthewHuff** [comment]
Added via the new two step process for adding a display anem
