### ISSUE TITLE
What does connecting to "None" server do?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10193]
Testing https://github.com/microsoft/vscode-jupyter/issues/10170

This item confuses me, I don't think it does anything so it shouldn't be there?

<img width="413" alt="Screen Shot 2022-05-31 at 10 25 23 am" src="https://user-images.githubusercontent.com/2193314/171235832-4a7bc130-233b-4e0a-a8db-05986ea28318.png">

**Comment by rchiodo** [comment]
It means you're not connected to any server. Not particularly useful for web as then you can't do anything, but for local it prevents remote kernels from showing up when you don't want them anymore.

**Comment by Tyriar** [comment]
Should that item be removed on web only since clicking it does nothing?

**Comment by rchiodo** [comment]
We're going to redesign this UI to make it so the user can have more than one remote server specified.

**Comment by DonJayamanne** [comment]
This should be fixed withthe new Kernel picker, marking as fixed as this UI no longer appears with the new kernel picker
