### ISSUE TITLE
Use an actual link in failure to connect quick pick

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10194]
Testing #10170

Repro:

1. Connect to server command
2. Select existing
3. Put in a bad url

<img width="553" alt="Screen Shot 2022-05-31 at 10 27 42 am" src="https://user-images.githubusercontent.com/2193314/171236209-81ef5c4a-8d4a-423b-be54-2b7813848d98.png">

If the VS Code API doesn't support markdown here, maybe it should?

**Comment by rchiodo** [comment]
VS code doesn't support markdown here. I believe I've already logged an issue for that.
