### ISSUE TITLE
Deprecate/Migrate Jupyter Power Tools extension

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#10196]

**Comment by greazer** [comment]
Also be sure to use the new Type **Deprecated** in package.json. May as well use this in your other extensions too.

**Comment by DonJayamanne** [comment]
Just need to update the package.json, did everything else last week.
<img width="682" alt="Screen Shot 2022-06-06 at 09 49 26" src="https://user-images.githubusercontent.com/1948812/172075655-96149a75-7b17-438f-a552-fe271ff91149.png">
