### ISSUE TITLE
Debugging a different cell with the same variables doesn't update the variables view

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode-jupyter#10199]
Testing #10184

Probably the same root cause as #10187 

1. Add 2 cells:

```py
# %%
a = 1234
b = 1
print(a)
c = a + b
print(c)

# %%
a = 3333
b = 3
print(a)
c = a - b
print(c)
```

2. Debug the first cell, see that a, b and c appear in the variables view once debugging is done
3. Debug the second cell, notice that a, b and c are not updated until after debugging is done

**Comment by greazer** [comment]
Most likely fixed in recent bits.
