### ISSUE TITLE
hovering over sort indicator shows column resize cursor

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-jupyter#10206]
Testing #10170

Hovering over the right half of the sort indicator ("triangle") shows the column resize cursor and when clicking there the column is actually resized.

![CleanShot 2022-06-01 at 09 54 55](https://user-images.githubusercontent.com/1898161/171355754-88974b65-281e-4966-ac34-c72260bc9a73.gif)

**Comment by sadasant** [comment]
Thank you @weinand! We'll follow up after our next triage!
