### ISSUE TITLE
Run by line does not work.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#10207]
## Environment data
Build of Visual Studio Code - Insiders: 1.68.0-insider(user setup)
Build of python-Pre-Release: v2022.7.11511005
Build of jupyter-Pre-Release: v2022.5.1001532360
Build of pylance: v2022.5.3
Build of jupyter Notebook Renderers: v1.0.8
Build of jupyter Keymap: v1.0.0
![image](https://user-images.githubusercontent.com/59192491/171344602-fac39d41-2131-4636-9636-ca62f76f444f.png)

## Steps to reproduce:
1. Opt into the custom editor experiment (not yet supported in native notebooks)
2. Open a new blank Jupyter notebook.
3. Add the following code to a cell:
```
def bar():
    for i in range(5):
         print(i)

def foo():
    bar()

foo()
print('Done')
```
4. Press F10 to step through the code in the cell line-by-line. 

## Expected behaviour
Verify that it first steps over function definitions for foo() and bar(), then steps into the function definitions after foo() is called, then steps back out when the loop in bar() finishes and prints 'Done'.

## Actual behaviour
No response when press F10

## Jupyter Log
![image](https://user-images.githubusercontent.com/59192491/171356984-f0ebb862-0d72-410d-8b31-b852ba5daf08.png)

**Comment by rchiodo** [comment]
This seems kind of important. Run by line isn't working.
