### ISSUE TITLE
Data viewer window launched from the variables view is empty

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode-jupyter#10200]
Testing #10184

1. Add a cell:
```py
# %%
a = dict()
b = [("a", "one"), ("b", "two"), ("c", "three")]
c = {k: v for (k, v) in b}
print(c)
```
2. Debug the cell
3. Open the variables view and notice that an icon appeared next to the variable name ("Show variable in data viewer")
4. Click on the icon for one of the variables, note that the Data Viewer window that opened is empty:

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/51720070/171287124-92754ade-103c-49c3-a5b0-9c61effcc0bc.png">

**Comment by greazer** [comment]
For web in May we're removing the button as this support is not ready for web yet.

**Comment by greazer** [comment]
@sadasant, looks like the complaint here is in the desktop versions, not web. But I've marked it as vscode-web anyway. Need to make sure this works in web and desktop for  June.

**Comment by olguzzar** [comment]
I experienced this same issue in desktop VS Code when opening a list's data viewer from the variable explorer. Video recording here: https://msit.microsoftstream.com/video/ae7b0840-98dc-bd6c-7484-f1ecfee3c9d9?st=590

Version: 1.69.0 (user setup)
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:36.503Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by sadasant** [comment]
Thank you, @olguzzar ! I'll follow up this month.

**Comment by DonJayamanne** [comment]
Unable to repor this issue.
@olguzzar @joyceerhl @linette-zyy are you still running into this issue?

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
