### ISSUE TITLE
Notebook export does not contain cell output

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-jupyter#10217]
Testing #10183

Running the notebook cells from https://github.com/microsoft/vscode-jupyter/issues/10165 results in this output:

<img width="1027" alt="CleanShot 2022-06-01 at 15 36 42@2x" src="https://user-images.githubusercontent.com/1898161/171417695-25e60334-955b-4159-9fe6-56feffa8726f.png">

However, when exporting this as html or pdf the cell output is missing:

![CleanShot 2022-06-01 at 15 38 37@2x](https://user-images.githubusercontent.com/1898161/171418150-e2100623-fe5f-445a-9b77-151b8ae9b6c6.png)

Here is the pdf file:

[Untitled-2.pdf](https://github.com/microsoft/vscode-jupyter/files/8814660/Untitled-2.pdf)

**Comment by DonJayamanne** [comment]
i don't think this is possible, unless we save widget state. 
we'd need you check how this works when exporting ipynb in jupyter itself, ie i believe this is working as expected.

**Comment by DonJayamanne** [comment]
Closing this issue as exporting this even in Jupyter notebooks produces the exact same behaviour
