### ISSUE TITLE
font size used in Variables View and Interactive Window too big

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-jupyter#10213]
Testing #10170

The font size used in Variables View and Interactive Window is too big:

![CleanShot 2022-06-01 at 13 01 58@2x](https://user-images.githubusercontent.com/1898161/171389897-eddf4088-0750-49a8-a732-6f05391c625c.png)

**Comment by sadasant** [comment]
Thank you, @weinand! We'll follow up after we circle through the open issues during our next triage.

**Comment by amunger** [comment]
duplicate of https://github.com/microsoft/vscode-jupyter/issues/8020
