### ISSUE TITLE
why is Jupyter REPL called "Interactive Window"?

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-jupyter#10214]
Testing #10170

The "Window" in the "Run Current File in Interactive Window" command sounds strange. 
Nowhere in VS Code do we call a "thing" that lives within a window, a "Window".
Consider to rename it Console or REPL...

**Comment by sadasant** [comment]
Thank you, @weinand! We'll follow up after we circle through the open issues during our next triage.

**Comment by greazer** [comment]
This is not something we're likely going to do since we have lots of documentation already.
