### ISSUE TITLE
Exported notebook files don't show up in VS Code explorer

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-jupyter#10218]
Testing #10183

Exported notebook files don't show up in the VS Code explorer. An explicit refresh is needed.

**Comment by rchiodo** [comment]
I still need a refresh?

I just exported to manualTest_exported.py. File explorer shows this:

![image](https://user-images.githubusercontent.com/19672699/171705817-f9298d4f-67a8-4a28-857f-10489b5e06ba.png)

However after switching back to the vscode.dev tab, the file shows up (no refresh other than losing focus)
