### ISSUE TITLE
Look into webview UI toolkit for the table implementation

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10219]
Testing #10170

We have a library that can be used which aims to provide a consistent experience with the rest of VS Code and it contains a table widget: https://code.visualstudio.com/blogs/2021/10/11/webview-ui-toolkit

I'm not sure of the current state but I believe it should meet accessibility requirements as well.

**Comment by sadasant** [comment]
Here’s the virtualization issue: https://github.com/microsoft/vscode-webview-ui-toolkit/issues/210

**Comment by greazer** [comment]
Yes, indeed on accessibility.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/165445
