### ISSUE TITLE
Sort arrow looks like it belongs to another column

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10220]
Testing #10170

Clicking on Name looks like it's sorting Type because of the styles used in the table

![Recording 2022-06-01 at 07 02 09](https://user-images.githubusercontent.com/2193314/171423199-950cd4a4-f109-4208-ad46-65753c29fc89.gif)

**Comment by sadasant** [comment]
Thank you! I believe this could be also solved if we follow through your feedback here #10219 , is that correct?

We'll follow up after our next triage!

**Comment by Tyriar** [comment]
Yep I imagine many of the issues I created will get fixed if you move to the webview toolkit, I'm not 100% sure the state of the package but at least then they'd be upstream issues we can action.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/165445
