### ISSUE TITLE
Should size in variables viewer be length?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10224]
Testing #10170

I'm not sure where else other than strings the size is used, but length seems more appropriate for Python as I think `len(string)` is the main function for getting the length?

<img width="513" alt="Screen Shot 2022-06-01 at 7 13 26 am" src="https://user-images.githubusercontent.com/2193314/171425565-17b71298-ade2-432d-8538-62e62de03083.png">

**Comment by rchiodo** [comment]
Size is overloaded to support by array length and multidimensional things like tables or 2/3d arrays.
