### ISSUE TITLE
Sorting a column shows "Loading variables" but they're already loaded

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10221]
Testing #10170

This causes a flicker which doesn't look good

![Recording 2022-06-01 at 07 04 00](https://user-images.githubusercontent.com/2193314/171423731-ce55aa78-888b-4538-b8f4-0a8d1a15cd95.gif)

**Comment by Tyriar** [comment]
This also happens when opening the webview, it would be better to only show loading variables after some reasonable time where a user may start to wonder why it's not working (500ms?). That way the flicker can be avoided

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/165445
