### ISSUE TITLE
Consider using a monospace font in the variable viewer

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10223]
Testing #10170

We typically use monospace fonts for things that represent code or their values

<img width="728" alt="Screen Shot 2022-06-01 at 7 09 10 am" src="https://user-images.githubusercontent.com/2193314/171424719-8d52eea2-21a0-45c5-95e3-2a2dc7bb6863.png">

See the debug viewlet for example:

<img width="203" alt="Screen Shot 2022-06-01 at 7 11 12 am" src="https://user-images.githubusercontent.com/2193314/171425092-c58b4422-624a-48a0-947b-c7360b984250.png">

<img width="411" alt="Screen Shot 2022-06-01 at 7 11 43 am" src="https://user-images.githubusercontent.com/2193314/171425196-660555fd-f698-4f0f-a81b-6ac03526b155.png">

**Comment by sadasant** [comment]
To solve this, we'd like to have a way to use the `debug.console.fontFamily` as a Less variable coming from VSCode core. More of the conversation can be seen in the back and forward on this PR: https://github.com/microsoft/vscode-jupyter/pull/10724

Suggestion (to future me): Open an issue on VSCode, or make a PR, exposing `debug.console.fontFamily` in the Less variables.

**Comment by Tyriar** [comment]
You should be able to read config on the ext host, pass the font family to your webview and inject a `<style>` element

**Comment by DonJayamanne** [comment]
@Tyriar the problems with that approach is, if users change themes or settings we need to detect that yet again and pas that to the WebView again. 
the suggestion is for vscode to inject those along with the other css variables.

**Comment by Tyriar** [comment]
Just refreshing on `window.onDidChangeActiveColorTheme` as well as config covers that case. I doubt we'll get font related css variables in webviews

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/165445
