### ISSUE TITLE
Prefer codicons over custom icons in webviews

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10226]
Testing #10170

We have a codicon for open external:
<img width="116" alt="Screen Shot 2022-06-01 at 7 17 03 am" src="https://user-images.githubusercontent.com/2193314/171426350-43e18724-283e-4a4d-91c1-06c79b53846b.png">

It's better to use this over a custom icon for consistency:

<img width="136" alt="Screen Shot 2022-06-01 at 7 17 46 am" src="https://user-images.githubusercontent.com/2193314/171426413-02c588c0-8d7a-487f-9a6d-d44b001fa179.png">

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/165445
