### ISSUE TITLE
Error messages are coming out empty

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10239]
Testing #10170

I don't know why this fails and it isn't giving me output.

![Recording 2022-06-01 at 07 41 09](https://user-images.githubusercontent.com/2193314/171431627-72458f1b-aee4-4506-8db5-37b5960b9b98.gif)

I have also seen in the past run something that should have given me an error but only showed up later (can't remember if it was a later run or after waiting x seconds)

**Comment by rchiodo** [comment]
I'm reproing with the same code:

```
class Complex:
    def __init__(self, realpart, imagpart):
        self.r = realpart
        self.i = imagpart

complex = Complex()
```
The error output is empty for some reason. Might be a failure parsing the trace?
