### ISSUE TITLE
Variable viewer: Button missing hover feedback

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10236]
Testing #10170

High contrast:

![Recording 2022-06-01 at 07 31 10 (1)](https://user-images.githubusercontent.com/2193314/171429417-5dc46212-4438-4ab3-bd56-155db7d26a25.gif)

It also should have feedback on regular themes.

**Comment by roblourens** [comment]
Will be fixed with a built-in variables viewer https://github.com/microsoft/vscode/issues/165445
