### ISSUE TITLE
Variable viewer: Class value info is not human friendly

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10238]
Testing #10170

After running this:

```py
class MyClass:
    """A simple example class"""
    i = 12345

    def f(self):
        return 'hello world'

x = MyClass()
```

<img width="719" alt="Screen Shot 2022-06-01 at 7 36 24 am" src="https://user-images.githubusercontent.com/2193314/171430511-645624f8-e3c6-4f03-be09-3f3b1f874696.png">

I was expecting something like `MyClass` or more useful `MyClass { var: ... }`

**Comment by rchiodo** [comment]
This is what python returns. The debugger shows the same thing.
