### ISSUE TITLE
Variable viewer: Text goes invisible when hovered in high contrast themes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10235]
Testing #10170
![Recording 2022-06-01 at 07 29 18 (1)](https://user-images.githubusercontent.com/2193314/171429039-25a04134-df7c-4cc5-9243-96b2fb6d7dea.gif)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/165445
