### ISSUE TITLE
Variable viewer: Show variable in data viewer button focus outline is cut off

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10231]
Testing #10170

<img width="73" alt="Screen Shot 2022-06-01 at 7 24 30 am" src="https://user-images.githubusercontent.com/2193314/171427856-61dcb496-68e7-421d-8cec-422b6d6912c1.png">

**Comment by sadasant** [comment]
This isn't a problem anymore. I can't reproduce it.
