### ISSUE TITLE
Variable viewer: Styling looks wrong in high contrast themes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10234]
Testing #10170

Notice:

- The border around the headers is thinner then the borders around the content
- The header top border is cut off

<img width="986" alt="Screen Shot 2022-06-01 at 7 27 39 am" src="https://user-images.githubusercontent.com/2193314/171428587-be46cc86-d9b7-4dec-8181-f42efc3880a0.png">

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/165445
