### ISSUE TITLE
Variable viewer: Can you retain the webview context when hidden?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10240]
Testing #10170

I know this is an option for custom editors, if it's available to webview panels that would save reloading the whole webview when re-focused (at the cost of keeping the context in memory):
![Recording 2022-06-01 at 07 44 13](https://user-images.githubusercontent.com/2193314/171432268-ad1cc256-3d83-491a-9de5-a2d37391356f.gif)

**Comment by Tyriar** [comment]
You could keep the context and trigger a refresh when the webview is shown instead of recreating it completely?

**Comment by Tyriar** [comment]
Yeah, it should load about as fast as the built-in panels then and feel more smooth/integrated.

**Comment by sadasant** [comment]
I like the idea of less flashing! We'll circle back after triage.

**Comment by Tyriar** [comment]
@rebornix related to that: https://github.com/microsoft/vscode-jupyter/issues/10221

**Comment by rchiodo** [comment]
> For refreshing, I also expect it does diffing and update incrementally instead of refreshing the whole page.

The react data grid we use should already be doing this. There is only flashing when we hide the window.

**Comment by rchiodo** [comment]
This was done on purpose to prevent execution from happening while the window is hidden. 
https://github.com/microsoft/vscode-jupyter/blob/e6f523d61c8eacba1beb996a05349d5cee8ac98e/src/webviews/extension-side/variablesView/variableViewActivationService.ts#L20

We could try detecting if the view is visible or not in the refresh though, and then set it to a pending refresh for when it becomes visible again.

**Comment by rchiodo** [comment]
Whoops wrong issue closed.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/165445
