### ISSUE TITLE
Variable viewer: Button in notebook is disabled

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10245]
Testing #10170

Not sure why this is disabled because I can open the viewer fine in the panel:

![image](https://user-images.githubusercontent.com/2193314/171436270-4534ee51-67a6-42cb-9e5b-dade5486d021.png)

**Comment by sadasant** [comment]
Closed in favor of: https://github.com/microsoft/vscode-jupyter/issues/10208
