### ISSUE TITLE
Variable viewer: Not screen reader accessible

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10243]
Testing #10170

Looks like no role/aria attributes that would indicate the header row is a row/header row:

<img width="421" alt="Screen Shot 2022-06-01 at 7 51 52 am" src="https://user-images.githubusercontent.com/2193314/171434076-df247e86-936a-478d-8dd5-3b5f344dbad4.png">

I also notice no `rowgroup` or `cell` roles https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/table_role

**Comment by minsa110** [comment]
Related: https://github.com/microsoft/vscode/issues/90408#issuecomment-1280068796
