### ISSUE TITLE
Interactive debugging does not work with ipykernel debugger

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10258]
Force ipykernel debugger on:
```json
  "jupyter.forceIPyKernelDebugger": true
```
Have code like so (part of one of our tests):
```
# %%
def foo(): 
   print(4)

# %%%
foo()
```

Set a breakpoint on the print(4)
Debug the second cell.

Continue when debugger comes up.

Expected result:
Stops on breakpoint (old debugger does)

Actual result:
Doesn't stop on breakpoint.

The cellToFile mapping that occurs in notebooks doesn't work for an interactive file. It needs more than cell URI to map as it has the same file for all dumped cells. This means breakpoints won't bind because they won't be rewritten to the mapped file.

**Comment by rchiodo** [comment]
This is breaking a number of tests that seem to force the usage of the new debugger. I'm disabling that for now.

**Comment by DonJayamanne** [comment]
> This is breaking a number of tests that seem to force the usage of the new debugger. I'm disabling that for now.

Wait, then how is it that the tests passed initially? Hmm, will look into this.

**Comment by DonJayamanne** [comment]
> It needs more than cell URI to map as it has the same file for all dumped cells. This means breakpoints won't bind because they won't be rewritten to the mapped file.

Agreed
