### ISSUE TITLE
Forbidden Error when using a new ipybn file created in vscode web 

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode-jupyter#10250]
Testing #10167

In Vscode Web i create a new file, --> Jupyter notebook, and it creates an untitled-1.ipynb file.

i add some code and works. but in the server side i keep getting this Forbidden Error.

![Screen Shot 2022-06-01 at 11 10 43 AM](https://user-images.githubusercontent.com/17892325/171473574-6695c842-5520-4869-a0f6-a993072d44ea.png)

**Comment by rchiodo** [comment]
That shouldn't matter. Something is calling the API without https.
