### ISSUE TITLE
Export command in Notebook Toolbar not enabled

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#10253]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/876920/171481144-345a363e-11bb-4824-a641-85a986e152ba.png">

Even when a remote server is connected and you can run Export command from command palette, the Export action in the notebook toolbar is still disabled.

**Comment by rchiodo** [comment]
/verified:

![image](https://user-images.githubusercontent.com/19672699/171696253-07743c04-d5e5-426f-aa9e-9c9c52c9ee77.png)
