### ISSUE TITLE
Interactive debugging only works on files in the root of the workspace

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10257]
Not a regression. Repros in stable.

1. Create a python file outside of the workspace
2. Add some cells
3. Debug a cell.

Expected result:
It enters debug mode and code lenses appear to support continue/stepinto

Actual result:
A copy of the file opens and the code lenses don't appear.

**Comment by DonJayamanne** [comment]
Given that no one else has reported this issue, closing this issue for now
