### ISSUE TITLE
Strange 'None' entry in the quickpick to configure a Jupyter server

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#10269]
Testing #10183

It's not really clear to me why there is an item for 'None' here, I'd expect to skip straight to the next step (pasting in the connection uri).

![image](https://user-images.githubusercontent.com/30305945/171695757-6fb1fc3e-81f0-4779-a711-84739bff9050.png)

**Comment by rchiodo** [comment]
Dupe of #https://github.com/microsoft/vscode-jupyter/issues/10193
