### ISSUE TITLE
Command to configure Jupyter server is unavailable after trusting a workspace and before reloading window

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#10268]
Testing #10183

1. Start in restricted mode
2. Create notebook
3. Trust current workspace
4. Run Specify Jupyter server command
5. :bug: command fails with:
![image](https://user-images.githubusercontent.com/30305945/171695509-a56a4ea0-4807-47d7-a2eb-ba87e33d2ac4.png)

Requires a window reload before the command works

**Comment by rchiodo** [comment]
I think we likely need to watch for workspace trust changed event?

https://github.com/microsoft/vscode/blob/14a7dfa47625f4e385bd17b8b8953e5a8b7faae9/src/vscode-dts/vscode.d.ts#L12165

**Comment by joyceerhl** [comment]
Are you conditionally registering the command only when the current workspace is trusted? Maybe instead we could unconditionally register the command but prompt for trust in the handler if it's needed?

**Comment by DonJayamanne** [comment]
Fixed with the new kernel picker UI.
