### ISSUE TITLE
Add telemetry for which language server is being used on Python notebooks

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-jupyter#10264]
Right now when we're trying to find usage or errors in notebooks telemetry for those using Pylance, we have to join queries on sessions. If we had telemetry to indicate which language server is being used on Python notebooks, this would make it faster/easier for us. 

cc @debonte

**Comment by rchiodo** [comment]
@luabud the language server right now is based on the 'python.languageServer' setting. Aren't you tracking this in the python extension? We don't have a separate setting.

**Comment by luabud** [comment]
We are tracking it, but we have to use "joins" on session ID to get this info and it's not always accurate (e.g. if Pylance failed to load and Jedi starts, it's not trivial to query for that). The queries often time out or run out of memory too.

**Comment by rchiodo** [comment]
Wouldn't the python extension then add a specific telemetry event for this? The language server for notebooks is never different than the language server for python files. Seems weird to add a telemetry event for notebooks.

**Comment by luabud** [comment]
That's a good point, if we were to log something it would probably make more sense to do it from the Python extension.
