### ISSUE TITLE
Unable to achieve interactive plot

### ISSUE THREAD

**Issue by p-i-** [microsoft/vscode-jupyter#10261]
## Environment data

-   VS Code version: 1.67.2 (current)
-   Jupyter Extension version (available under the Extensions sidebar): Jupyter v2022.4.1021342353
-   Python Extension version (available under the Extensions sidebar): Python v2022.6.3
-   OS (Windows | Mac | Linux distro) and version: macOS 12.4 (Monterey) (Current)
-   Python and/or Anaconda version: 3.10.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): `python -m venv .venv`
-   Jupyter server running: Local

## Expected behaviour

Running example from https://mplcursors.readthedocs.io/en/stable/ in a fresh .ipynb

Expecting to be able to click on the plot that is output, and for it to "interactively" respond to cursor location.

## Actual behaviour

It doesn't.

## Steps to reproduce:

Just  create a  fresh .ipynb and stick the first code example from the above link in a cell:

```
# https://mplcursors.readthedocs.io/en/stable/
import matplotlib.pyplot as plt
import numpy as np
import mplcursors

data = np.outer(range(10), range(1, 5))

fig, ax = plt.subplots()
lines = ax.plot(data)
ax.set_title("Click somewhere on a line.\nRight-click to deselect.\n"
             "Annotations can be dragged.")

mplcursors.cursor(lines)  # or just mplcursors.cursor()

plt.show()
```

Now this is likely an issue with backends. Prefixing `%matplotlib` outputs no plot, but instead:
> Using matplotlib backend: <object object at 0x112c49f20>

Please could we have instruction how to achieve interactive-plots, or an explanation of why we can't. If cannot, is it in the pipeline? What is blocking it?

I can't find any clear definitive documentation on backends, and how they apply in VSCode's Notebook editor.

I would love to be able to transition 100% from Jupyter Notebooks (operating out of web browser).

**Comment by jackthepanisher** [comment]
I think you will need `%matplotlib widget` to enable support for mpl widgets. This might require to install the `ipympl` package as well. I haven't looked much into the details and also haven't found much further information on the `mplcursors` site but JupyterLab seems to require the same to display the interactive cursors.

**Comment by rchiodo** [comment]
As @jackthepanisher said, you can use `%matplotlib widget` if you want an interactive plot. The default backend for plots is to just generate a PNG. (same as `%matplotlib inline`)

We have some limited capability for opening pngs in a separate viewer that you can zoom in on. 

![image](https://user-images.githubusercontent.com/19672699/171679354-f30bc4ce-f8fd-4a2e-9f77-1c53ed29dab4.png)

That opens a new window like so:

![image](https://user-images.githubusercontent.com/19672699/171679431-67fe70ba-1a3b-4c7e-94cf-25f2988cb456.png)

But of course the interactivity is not the same as you'd get with `%matplotlib widget` or `%matplotlib qt5`. 

For our list of supported backends, look here:
https://github.com/microsoft/vscode-jupyter/wiki/Using-%25matplotlib-widget-instead-of-%25matplotlib-notebook,tk,etc

**Comment by rchiodo** [comment]
This is what you should get with `%matplotlib widget`

![image](https://user-images.githubusercontent.com/19672699/171679906-92757ddf-ad05-4d22-abd1-8e599b4113df.png)

**Comment by p-i-** [comment]
Thanks for this.
The only issue now is that:
```
from matplotlib import pyplot as plt
plt.style.use('dark_background')
```

... with `widget` I now lose my beautiful dark-background plots.

So either I have dark plots and my eyeballs can relax, or I get interactive + eyestrain.

Is that a VSCode issue?  Is it fixable?

**Comment by p-i-** [comment]
`inline`:
<img width="849" alt="Screenshot 2022-06-05 at 01 51 03" src="https://user-images.githubusercontent.com/693495/172021637-9ccb4cb1-f1c3-4724-aab7-8d44c952e698.png">

`widget`:
<img width="853" alt="Screenshot 2022-06-05 at 01 51 33" src="https://user-images.githubusercontent.com/693495/172021647-3fc00ae0-1cdc-4d9f-ab7c-f166194a09b8.png">

**Comment by p-i-** [comment]
It seems that `%matplotlib widget` resets the theme.

If I do:
```
%matplotlib widget
plt.style.use('dark_background')

spectra12 = plot_spectrograms()
```
... now I get this:
<img width="833" alt="Screenshot 2022-06-05 at 01 56 30" src="https://user-images.githubusercontent.com/693495/172021852-8b52fedc-0b78-4269-b1aa-3a22b8970516.png">

Is there any way to recolor the white? A lot of my day is taken staring at these plots, so it would be wonderful if I can do it.

**Comment by rchiodo** [comment]
We don't control the colors for the matplotlib widget. That's entirely in matplotlib's code. I believe the docs for the ipympl backend (what it uses when you specify `%matplotlib widget`) are here:

https://matplotlib.org/ipympl/
