### ISSUE TITLE
First jupyter kernel web completion is slugish

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-jupyter#10276]
Testing #10166

Follow steps from testplan item.
Open some .ipynb file. Have the following cell

```
import pandas as pd
import numpy as np
import pylab as plt
pd.
# Set the global default size of matplotlib figures
plt.rc('figure', figsize=(10, 5))

# Size of matplotlib figures that contain subplots
fizsize_with_subplots = (10, 10)

# Size of matplotlib histogram bins
bin_size = 10
```

Notice on the fourth line I am triggering completions on `pd`. This first request takes 6+ seconds on my machine.
All subsequent intelli-sense triggers are good for `pd`.

**Comment by rchiodo** [comment]
I believe we run one completion at startup? Maybe we've since removed that code.
