### ISSUE TITLE
Remote jupyter server failures are not diagnosable

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10274]
Was helping somebody today and their default kernel spec was invalid. There's no way to tell from the Jupyter extension.

We need at least the console output from the jupyter server. I had tried adding this to jupyter a long time ago and they were hesitant. 

Maybe we could tell the user to look at the console output instead.

**Comment by DonJayamanne** [comment]
Closing this issue as there's nothing to be done here,
