### ISSUE TITLE
Should we prompt the user to save the current file before attempting to export?

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#10270]
Testing #10183

1. Create untitled ipynb, do not save
2. Run some cells
3. Choose Export to HTML
4. Not prompted to save the ipynb, exported file is blank

Could we prompt the user to save the ipynb before export?

**Comment by joyceerhl** [comment]
Also if I try to export an untitled file it actually brings up the local file dialog, which is a really odd experience, and then clicking Yes  on this dialog does nothing: 
![image](https://user-images.githubusercontent.com/30305945/171699308-e71a8f26-df44-4f07-aba9-03a46a1e5530.png)

**Comment by DonJayamanne** [comment]
Users havent complained about this issue and there haven't been any upvotes in this issue, hence closing this issue for now
