### ISSUE TITLE
RBL doesn't prompt for ipykernel setup anymore

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#10288]
Issue Type: <b>Bug</b>

* Connect to a Python intepreter which doesn't support Run By Line (old version of ipykernel)
* Run RBL
* VS Code stable: it prompts "ipykernel setup required for this feature"
* Insiders: nothing happens

Extension version: 2022.5.1001551026
VS Code version: Code - Insiders 1.68.0-insider (15253f1528573fc8f84e956b21af4bad57f38c07, 2022-06-02T05:16:07.238Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.63GB free)|
|Process Argv|--enable-proposed-api joyceerhl.vscode-pyolite --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api donjayamanne.kusto --crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DonJayamanne** [comment]
Works for me, though the message is very confusing
<img width="300" alt="Screen Shot 2022-06-03 at 10 57 58" src="https://user-images.githubusercontent.com/1948812/171765760-0450521f-2bba-401d-960b-66839ad0647b.png">

@rebornix please could you share your logs
