### ISSUE TITLE
Error links in notebooks cannot be clicked in web extension

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10287]
Open in insiders.vscode.dev
Create an exception in a cell
Try clicking on a link

Nothing happens.

**Comment by rchiodo** [comment]
Verification steps:

1. Open insiders.vscode.dev
2. Install latest prerelease jupyter extension
3. On your local machine (assuming you have jupyter installed), run this from a python environment with jupyter
```jupyter notebook --no-browser --NotebookApp.allow_origin=*```
4. That should generate a URL. Copy the URL
5. Go back to VS code and create a notebook
6. Run the 'Jupyter: Specify Jupyter server for connections' command
7. Pick 'Existing'
8. Paste the URL from your local jupyter server
9. In the notebook now enter a cell like so:
```
raise Exception('foo')
```
10. That should generate an error output
11. The error output should have clickable links
12. Clicking a link should put focus back into the cell

**Comment by rebornix** [comment]
It doesn't seem to show links 

<img width="507" alt="image" src="https://user-images.githubusercontent.com/876920/176795765-e9ea44c6-3230-415b-b9d6-63bf9de55cd4.png">

I'm testing against `v2022.6.1001831043` prerelease.

**Comment by rchiodo** [comment]
Sorry should have said you need to make sure you're using IPython 8.0 or higher.

**Comment by rchiodo** [comment]
IPython 7 won't parse the links at all.
