### ISSUE TITLE
Change prompt text that requires users to upgrade ipykernel to a newer version

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#10295]
If user has an old version of ipykernel, this is the message presented:
I have ipykernel 5 installed, and i still get asked to install ipykernel.

<img width="300" alt="Screen Shot 2022-06-03 at 10 57 58" src="https://user-images.githubusercontent.com/1948812/171766058-bc2164d4-2b31-49bb-8112-9983f9ead758.png">

**Comment by IanMatthewHuff** [comment]
I think this is more debugging than getting started since it's a debugging specific feature that needs the update.

**Comment by roblourens** [comment]
The latest telemetry on ipykernel versions shows <8% of users with ipykernel 5. At some point these issues just won't be that relevant.
