### ISSUE TITLE
Debug a cell test is flakey

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10294]
This test here:
Debug a cell from a python file:1 | Code lens with command jupyter.debugcell not found

Might have to wait for code lens in a waitForCondition loop.

It looks like the code lenses just haven't refreshed yet:

![image](https://user-images.githubusercontent.com/19672699/171760144-d8c5deb7-6194-4fb7-97da-6fe981c3aebd.png)

**Comment by amunger** [comment]
should be fixed by the added teardown to ensure previous debuggers have been stopped
