### ISSUE TITLE
Jupyter server with incorrect password validates too late

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#10300]
1. start an external juptyer server with a password
2. Specify server for connections in VS Code and use that server with the wrong password

Expected:
Error message that connection did not succeed

Actual:
The prompt goes away without any notification, but no connection was made.
Next time you try to connect to the server, no password prompt appears, but the connection fails because the (saved) password is wrong.

**Comment by amunger** [comment]
Stable has a warning prompt, but still saves the wrong password without letting you enter a new one, so not much of a regression

**Comment by IanMatthewHuff** [comment]
Note: Related to AML extension.

**Comment by IanMatthewHuff** [comment]
Validation notes:
Main scenario here is just that after inputting an incorrect Jupyter password the UI would not allow you a chance to re-connect with the correct password.

To note, we are currently running a UI experiment with remote server selection, so your experience might be a bit different if you are in the experiment or not. 

1. Not in the experiment, a failed password should drop you back to the URL specification page with a validation error and allow you to enter the URL and try a new password.
2. In the experiment, a failed password should pop up a modal dialog error. You can then restart the URL process to try a new password.

The fix here is just specific to having the ability to input a new password after a failed attempt. (Previously the failed password would cache), the connection would fail, but if you tried to reconnect it would not give you a chance to input a new correct password.
