### ISSUE TITLE
Data Viewer fails to start for Pytorch tensor in deep call stack

### ISSUE THREAD

**Issue by Saltsmart** [microsoft/vscode-jupyter#10317]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Steps:
1. Pause debugging at a breakpoint.
2. Select a function in the call stack (several layers before the current breakpoint).
3. Select a pytorch tensor **(especially as an item in a dict or tuple)** and open data viewer for it.

Expect to happen:
Data viewer window shows as normal.

What actually happened:
An error message pops up.

> Traceback (most recent call last): File "<string>", line 1, in <module> NameError: name '\<TENSOR\>' is not defined. View Jupyter [log](command:jupyter.viewOutput) for further details.

![image](https://user-images.githubusercontent.com/40828952/171990102-a2267122-56d8-4594-865b-74ba4c7c1e86.png)

Jupyter logs:
Please see below.

But the tensor is well defined and acts normally.

### VS Code Version

Version: 1.67.2 (system setup) Submit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5 Date: 2022-05-17T18:15:52.058Z Electron: 17.4.1 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Windows_NT x64 10.0.19043

### Jupyter Extension Version

v2022.4.1021342353

### Jupyter logs

```shell
info 15:52:48.619: Process Execution: > c:\ProgramData\Anaconda3\envs\d2l\python.exe -c "import pandas;print(pandas.__version__)"
> c:\ProgramData\Anaconda3\envs\d2l\python.exe -c "import pandas;print(pandas.__version__)"
error 15:52:49.252: Error: Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 's' is not defined

    at o.handleErrorResponse (vscode-file://vscode-app/d:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1038:45704)
    at vscode-file://vscode-app/d:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1038:45143
warn 15:52:49.252: DataScience Error Error: Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 's' is not defined

    at o.handleErrorResponse (vscode-file://vscode-app/d:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1038:45704)
    at vscode-file://vscode-app/d:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1038:45143
```

### Coding Language and Runtime Version

Python v3.8.12

### Language Extension Version (if applicable)

v2022.6.2

### Anaconda Version (if applicable)

2020.07

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
thanks for the bug, I was able to repro (though with a slightly different error message) simply by debugging through the [example here](https://visualstudiomagazine.com/articles/2020/06/09/working-with-pytorch.aspx#:~:text=PyTorch%20is%20a%20Python%20language%20code%20library%20that,or%20a%20GPU.%20PyTorch%20tensors%20are%20surprisingly%20complex.) and opening the data viewer for either of the tensor variables

```
error 14:34:52.984: Error: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 161, in _VSCODE_getDataFrameInfo
NameError: name '_VSCODE_convertToDataFrame' is not defined
```

**Comment by amunger** [comment]
this no longer repro's for me. Please provide a sample cell that reproduces the issue if you're still seeing this.
