### ISSUE TITLE
Scripts sources related to custom IPyWidgets not loaded

### ISSUE THREAD

**Issue by dentistfrankchen** [microsoft/vscode-jupyter#10319]
Recently i am trying to custom widget that contains javascript using ipywidget.However my project does not render the result as a jupyter notebook does. My widget cannot be displayed.

**Comment by dentistfrankchen** [comment]
[QuoteWidget.txt](https://github.com/microsoft/vscode-jupyter/files/8837768/QuoteWidget.txt)

This is the ipynb file, since i cannot upload it, i changed it to txt.

**Comment by dentistfrankchen** [comment]
![Settings - Visual Studio Code 6_4_2022 9_39_20 PM (2)](https://user-images.githubusercontent.com/56914624/172007172-de65cc2e-38fe-4850-aec0-92ad08cbefd6.png)
This picture is what i encountered. I added value to the key in settings.json, and i got this error.

**Comment by dentistfrankchen** [comment]
I am not sure whether this setting is the cause.

**Comment by dentistfrankchen** [comment]
Today I tried much more simple code:
%%html

<font size=6 color='blue'>Hello Jupyter</font>
<script>
document.write("Hello World!")
</script>

Also blank.
If you delete the <script>part, the display is ok.
Is there some problem with rendering javascript(or %%javascript)？

**Comment by dentistfrankchen** [comment]
Any relation with #6054?

**Comment by rchiodo** [comment]
VS code doesn't render your output in the same DOM as the rest of the notebook. Output is in its own iframe. The javascript you have there destroys the DOM of the iframe so that it has just 'hello world' in it, making the rendering logic for the rest of the output broken.

The DOM that jupyter has is not intended to be the same as the DOM we have in VS code. There's no way it would ever be, so you'll have to be careful what you do in your script code.

You might look at what standard widgets do (if you're working on a widget). Loading a script straight into an output is not really the recommended way to get a script to load. The script will fail to run the next time you execute the cell.

**Comment by dentistfrankchen** [comment]
@rchiodo Thanks for your reply.  I am new to using jupyter in vscode. Can you give me an example of correctly using %%javascript in jupyter-vscode?

**Comment by rchiodo** [comment]
%%javascript doesn't really work in VS code. We don't support all of the implicit properties that are available in a jupyter notebook. 

However you could follow the directions here if you want a python backend:
https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Custom.html

IPyWidgets do work in VS code.

**Comment by dentistfrankchen** [comment]
I read that documentation. However i think it requires me to write my project as a package? Can i do everything in a single ipynb?

**Comment by dentistfrankchen** [comment]
Today I ran the example provided by https://github.com/jupyter-widgets/widget-ts-cookiecutter. I wrapped the example(I did not add any code) in a package as instructed, and it worked in jupyter notebook in edge. However, for vscode it is still blank.

**Comment by DonJayamanne** [comment]
@dentistfrankchen thanks for providing the detailed explanation and code sample, I have come across a similar issue recently and have a fix for this, it is infact similar to other widget issues where we don't load the resources correctly.

**Comment by dentistfrankchen** [comment]
@DonJayamanne I appreciate your reply and thank you for your contribution for this project, which helps thousands of people who are doing data mining like me. I am still waiting to see the problem getting solved, since I need to wait for the next version of extension to release. Keep contact.

**Comment by DonJayamanne** [comment]
@dentistfrankchen 
This should work in tomorrows pre-release version of the Jupyter extension (you'll need VS Code insiders and then install the pre-release version of Jupyter extesnion).

Also, if you want to generate some HTML or run some JS I'd try the following:
```
%%html
<div id="myCustomEle">Hello</div>
<script type="application/javascript">
	document.getElementById("myCustomEle").innerHTML = "Hello World"
</script>
```

Even though the sample your provided might seem to work in Jupyter, that completely breaks the UI. Hence its not really a valid use case of such code. I'd change to as provided above.
```
<script> document.write("Hello World!") </script>
```

Another sample is to run two cells:
```
# First cell
%%html
<div id="myCustomEle">Hello</div>
```
```
# Second cell
%%javascript
document.getElementById("myCustomEle").innerHTML = "Hello World"
```

**Comment by DonJayamanne** [comment]
Closing this issue as fixed, as part of https://github.com/microsoft/vscode-jupyter/pull/10459
