### ISSUE TITLE
De-reference the constructor from the rendering of VariableExplorerButtonCellFormatter

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#10310]
The `VariableExplorerButtonCellFormatter` is currently tying the constructor of the `VariableExplorer` in: https://github.com/microsoft/vscode-jupyter/blob/main/src/webviews/webview-side/interactive-common/variableExplorer.tsx#L125

We should not take the reference from the constructor, for performance reasons.
(though I haven't tested this kind of performance in a while, but seems reasonable to move this state-referencing out of the constructor)

**Comment by DonJayamanne** [comment]
To my knowledge this kind of this only impacts perf in react only when dealing with components that get rendered 100s if not 1000s of times e.g. within a cell of a grid.
The variable explorer here is a top level component, hence i don't think this will introduce any perf issues, 

> e reference from the constructor, for performance reasons.(though I haven't tested this kind of performance in a while, 

personally i'd like to see the perf impact on this, as I don't think there is any

**Comment by sadasant** [comment]
@DonJayamanne You may be correct! I made this issue to keep the open question and come back to it later.

However, since our goal is to re-enable the data viewer on the web asap, this issue will be fixed soon when we remove the `isWeb` clause on that component. So, we can forget about this!

Thank you for taking the time to think it through though.

**Comment by DonJayamanne** [comment]
Should we then close this issue?

**Comment by sadasant** [comment]
Yup yup! Thanks!
