### ISSUE TITLE
Variables view should show that it is waiting for the running cell

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-jupyter#10321]
## Expected behaviour

When using the Variables view, clarify that when it needs to wait for the current cell to finish.

## Actual behaviour

For many minutes, I am starting at this unhelpful loading message. I assume the kernel can't be pinged until the cell is done running.

<img width="838" alt="image" src="https://user-images.githubusercontent.com/8599/172031070-0e438372-3802-43bb-a13a-da38fda1b763.png">

## Steps to reproduce:

While a long running cell runs, open the _Variables_ view the first time.

**Comment by amunger** [comment]
closing in favor of https://github.com/microsoft/vscode/issues/165445
