### ISSUE TITLE
Hitting Enter on `Jupyter: Specify Jupyter server for connections` doesn't do anything

### ISSUE THREAD

**Issue by julibeg** [microsoft/vscode-jupyter#10322]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Very similar to #4241. When I try to connect to a running jupyter server, pressing the `Enter` key does not do anything. This only occurs when the URI is correct. Otherwise, there is an error notification saying `Failed to connect to remote Jupyter notebook`. Also, after trying to press `Enter` with a correct URI, the "back" arrow in the UI doesn't work anymore either. I tried all the workarounds mentioned in #4241 and none of them worked for me. Previously, when looking at the logs, I saw that it said something about not being able to delete some password. However, when I reproduced the issue just now, the logs did not mention anything (for logs see below) and unfortunately I did not save the logs back then.

### VS Code Version

Version: 1.67.2 Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5 Date: 2022-05-17T18:23:40.286Z Electron: 17.4.1 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Linux x64 5.14.0-1038-oem

### Jupyter Extension Version

v2022.4.1021342353

### Jupyter logs

```shell
I restarted VSCode, ran `Jupyter Show Output`, reproduced the unwanted behavior, and then ran `Jupyter Show Output` again. It had not changed.

Visual Studio Code (1.67.2, ssh-remote, desktop)
Jupyter Extension Version: 2022.4.1021342353.
Python Extension Version: 2022.6.3.
Workspace folder /XXX
info 2:2:39.387: ZMQ install verified.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
> /XXX/miniconda3/envs/tf/bin/python -m pip list
```

### Coding Language and Runtime Version

Python v3.8.3

### Language Extension Version (if applicable)

v2022.6.3

### Anaconda Version (if applicable)

conda 4.11.0

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
Looks like you are using SSH remote to connect to some other machine.
Does the URL point to a Jupyter server running on the local machine or on the remote machine?

Please could you :
* enable `verbose` logging in your `user settings` as follows
* reload VS Code
* Replicate the issue
* & upload the contents of the `Jupyter Output` panel 

<img width="338" alt="Screen Shot 2022-06-06 at 08 48 30" src="https://user-images.githubusercontent.com/1948812/172073830-c9e4745a-a93a-4d46-b1f1-eea84818caba.png">

**Comment by DonJayamanne** [comment]
@julibeg We've found that in some cases if the target Url is HTTPS and if you enter `http://` then you'd run into the issue reported. If this is the case, please try entering `https`.

**Comment by julibeg** [comment]
Hi there and thanks for the quick reply! 

>  Does the URL point to a Jupyter server running on the local machine or on the remote machine?
The remote machine.

I reinstalled VSCode and the extensions in the meantime and now it works again. However, it has been working in the past as well and stopped at some point. As soon as I encounter the issue again, I will send the detailed logs and try entering `https`.

**Comment by DonJayamanne** [comment]
closing the issue for now
