### ISSUE TITLE
Run by line stop at the first line twice.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/vscode-jupyter#10347]
## Environment data

Build of Visual Studio Code - Insiders: 1.68.0-insider(user setup)
Build of python-Pre-Release: v2022.7.11541009
Build of jupyter-Pre-Release: v2022.6.1001562429
Build of pylance: v2022.6.0
Build of jupyter Notebook Renderers: v1.0.8
Build of jupyter Keymap: v1.0.0

## Steps to reproduce:

1. Open a new blank Jupyter notebook.
2. Add the following code to a cell:
```
def bar():
    for i in range(5):
        print(i)

def foo():
    bar()

foo()
print('Done')
```
3. Press F10 to step through the code in the cell line-by-line. 

## Expected behaviour

Verify that it first steps over function definitions for foo() and bar(), then steps into the function definitions after foo() is called, then steps back out when the loop in bar() finishes and prints 'Done'.

## Actual behaviour

Pressing F10 will stop at the line ```def bar():```, then pressing F10 again will stop at the line ```def bar():```.

![image](https://user-images.githubusercontent.com/82852072/172284942-43b5b56b-7656-4fb4-8e1b-2091383e0483.png)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
info 2:46:25.995: Executing silently Code (idle) = import ipykernel\nprint(ipykernel.__version__)
info 2:46:26.24: Executing silently Code (completed) = import ipykernel\nprint(ipykernel.__version__)
info 2:46:26.835: Executing silently Code (idle) = import debugpy\ndebugpy.debug_this_thread()
info 2:46:27.79: Executing silently Code (completed) = import debugpy\ndebugpy.debug_this_thread()
info 2:46:27.420: Execute Cell 0 Untitled-1.ipynb
```

</p>
</details>

**Comment by rchiodo** [comment]
This is a function of your version of IPython on the machine. You need to upgrade it to at least version `8.4.0`. 

See this issue here:
https://github.com/ipython/ipykernel/issues/841
