### ISSUE TITLE
Variable View doesn't use the full panel width by default

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#10351]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/876920/172491898-789f7193-180a-4811-b3cb-91ebcc20b0be.png">

The Variable View is not taking the full width of the panel, leaving a lot of spaces on the right, while text in cells are cut off.

**Comment by roblourens** [comment]
Variable viewer will become built-in https://github.com/microsoft/vscode/issues/165445
