### ISSUE TITLE
Drop fnv dependency for hash generation

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#10358]
`fnv-plus` was originally introduced for A/B testing via https://github.com/microsoft/vscode-jupyter/commit/db297c4a7833e1d5aab453541aa5b1751abd890b and it was set as the default hash algorithm and when we attempted to generate hash for file paths and use them as key for kernel mapping https://github.com/microsoft/vscode-jupyter/commit/409c62b27d3394cdebe1812a122263c0720eb7e0, we didn't pass in a hash algorithm so `fnv` was being picked by default.

As of today, we are only using `fnv` algorithm for creating `kernel <--> hash(file)` mapping for remote kernels. Using sha256 or fnv doesn't matter in this scenario and considering the size of the `fnv-plus` module, it would reduce the download and startup time for the Jupyter extension.

Proposals for dropping `fnv`:

1. Drop it directly since it's only used by remote kernels. We might want to check how many users are actually using remote kernels. For them the problem is they get an upgrade and they might not get the "suggested" kernel (we can give it a check).
2. Drop it for Web (as we just supported it very recently), and have a migration plan for Desktop.

**Comment by rchiodo** [comment]
I checked the telemetry using EXECUTE_CELL (which has a kernelconnectiontype field).

Here's the results:

![image](https://user-images.githubusercontent.com/19672699/172505873-6fa71e52-ee25-416b-ae93-f526910954b3.png)

Which means out of the 422 million cells run, 8 million were on remote kernels and 7 million were on already existing kernels. That 7 million would be affected by this change. So about 2% of cells run.

**Comment by DonJayamanne** [comment]
> Drop it directly since it's only used by remote kernels.

I prefer the migration

> and have a migration plan for Desktop.

Agreed

> Drop it for Web (as we just supported it very recently),

Agred.
