### ISSUE TITLE
Dataframe Intellisense: no auto complete after groupby 

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#10353]
Follow the steps in https://github.com/microsoft/vscode-jupyter-internal/issues/200 

> ## 6. Intellisense
> Type titanic_df.groupby(by='Sex').Age.mean()

I'm not getting auto complete anymore after typing `by`

**Comment by rchiodo** [comment]
What is this setting set to?

  "python.pylanceLspNotebooksEnabled": true,

**Comment by rchiodo** [comment]
Actually that setting has no effect for me. Can you show a gif? Or explain what you mean? I get autocomplete after the by myself:

![image](https://user-images.githubusercontent.com/19672699/172499912-3b26af48-0870-49a7-93e2-e16470348ef9.png)

But it doesn't include the 'Age' column. Jupyter isn't smart enough to parse this to produce the necessary completions, so I only get what pylance understands.

**Comment by rebornix** [comment]
@rchiodo we are seeing the same. Maybe the guidance for intellisense golden scenarios is not accurate enough. I don't get suggestion for "Sex" and also no suggestion for column names. If that's expected we could close this.

**Comment by rchiodo** [comment]
It's at least not supported at the moment. I don't now how we would because jupyter notebooks can't figure it out either:

![image](https://user-images.githubusercontent.com/19672699/172500461-2491b8c3-13dd-438a-a094-ec0250cf9350.png)

I think the golden scenario needs to be updated with the expected results.

**Comment by burkeholland** [comment]
Found in Golden Scenario. The intellisense doesn't know about the dataframe columns after calling `groupby`. If you specify one, the intellisense stops working completely. Interesting, though, is that if you specify that column using array syntax, the intellisense does keep working.

https://user-images.githubusercontent.com/686963/179260416-34fe38ed-8d43-4eeb-b0e5-f60ec490846d.mp4

**Comment by olguzzar** [comment]
Leaving a comment for awareness- experienced this while running through the golden scenario as well. Recording here: https://msit.microsoftstream.com/video/79a60840-98dc-a27a-e9b5-f1ed287bbe75?st=1000

**Comment by DonJayamanne** [comment]
Its been a while since this feature request was filed, and we haven't had an upvotes nor further comments on this issue (apart form internal team members)
Hence closing this issue for now
