### ISSUE TITLE
Remove the old localize function (in web)

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#10367]
Since `vscode-nls` does not yet support the `web` environment. If PR #10361 gets merged, eventually, when `vscode-nls` supports the `web` environment, we will have to remove the current `localize` function on favor of `vscode-nls`'s localize function.

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode/issues/148722

**Comment by DonJayamanne** [comment]
Closing this for now, will get addressed when its done upstream (no need of tracking issue for debt, as these things get communicated via standup and the like)
