### ISSUE TITLE
Remote kernels are not listed in kernel picker

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#10366]
Having similar issues recently on my Linux workstation:

1. Spin up a server within a Docker container; confirm a kernel has also been started
2. update "Specify Jupyter remote server for connections" within VS Code
3. go to "select kernel" but no remote kernel is listed

Clues:
 * My problem seems similar to https://github.com/microsoft/vscode-jupyter/issues/6653.
 * opening the localhost url for the server in a browser works fine (but i'd really like to work in VSC!)
 * following the same recipe above on my Macbook works, i.e. the remote kernel is available w/in VSC
 * i see the following logs from my jupyter server (in Docker):
``` 
[W 2022-06-08 12:46:40.543 LabApp] Could not determine jupyterlab build status without nodejs
[I 2022-06-08 12:46:45.853 ServerApp] Writing notebook-signing key to /home/app_user/.local/share/jupyter/notebook_secret
[W 2022-06-08 12:46:45.855 ServerApp] Notebook {my_notebook}.ipynb is not trusted
[I 2022-06-08 12:46:46.406 ServerApp] Kernel started: 36b69019-bb2d-45eb-80e4-798b8cc4426a
[I 2022-06-08 12:46:46.866 ServerApp] Starting buffering for 36b69019-bb2d-45eb-80e4-798b8cc4426a:1660cc72-10b0-445a-b13d-f21c5c9a6128
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 08bb58c7-34a1-4c21-9360-152e941aba63
...
```

_Originally posted by @JakeColor in https://github.com/microsoft/vscode-jupyter/issues/10363#issuecomment-1149884632_

**Comment by amunger** [comment]
@JakeColor - could you post the jupyter logs from the output pane (select Jupyter in the dropdown) after going through your repro steps? And also list the version info for vscode, jupyter extension and python extension?

**Comment by JakeColor** [comment]
@amunger sure!

Here are the logs from the Docker container: https://pastebin.com/ixiiNSZx

![image](https://user-images.githubusercontent.com/6565064/172941389-9ae831ef-94a5-41a9-a079-b9599cc6d04c.png)

Python version is 3.7.13

Also, I don't see jupyter logs in the "output pane;" am i looking in the right place?
![image](https://user-images.githubusercontent.com/6565064/172940825-779d078e-fe43-4fef-87c3-590ce0814182.png)

**Comment by amunger** [comment]
the logs are actually in the output tab, and select jupyter from the dropdown there

**Comment by JakeColor** [comment]
thanks for clarifying, here are the logs:  https://pastebin.com/zEMG0Q7L

please note my pastebin post expires in 30 days

**Comment by amunger** [comment]
From the logs it looks like is able to connect and I don't see any errors while discovering remote kernels.

Do you have `Python 3 (ipykernel)` listed at the top of the kernel picker? That one is likely the remote kernel if so, it might just be "suggested", which covers up the "Remote" annotation.

**Comment by amunger** [comment]
actually, I can get close to a repro for this issue if I do something that causes the server to stop responding to vscode connections, and I see some 403s in your juptyer server logs. 
We did some work around validating the server on connection this release - Could you try updating the extension and then reconnecting to the server: `jupyter: specify jupyter server for connections`.

**Comment by amunger** [comment]
It also looks like those logs were from a local-only session in vs code. So another set of logs when running that `jupyter: specify jupyter server for connections` command might help clear things up.

**Comment by amunger** [comment]
Good to hear! I'll close this for now but let us know if you see the issue again
