### ISSUE TITLE
Improve CI time

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#10399]
This issue captured ideas brought up in offline discussions with @rchiodo for improving the testing experience in the repo, including faster CI time and tighter feedback loop for changes (locally)

* Shared document/kernel for test suite when appropriate. We currently open and close document for every individual test, which will launch kernel for every single. The kernel startup contributes to main portion of our CI time. When document open/close and kernels state don't matter in a test suite, we could see how we can reuse the same document and kernel for faster testing.
* A `launch.json` option (with properly tuned envs) to test non-conda tests locally. Currently the tests on a reasonably powerful machine takes too long and some of us rely on the CI for the test results.

**Comment by rchiodo** [comment]
We could also work on improving
- Compile time
- Conda install time
- Not install .NET/Julia for python tests

**Comment by DonJayamanne** [comment]
Partial improvements made here https://github.com/microsoft/vscode-jupyter/pull/11867

**Comment by DonJayamanne** [comment]
Closing this as majority of the work has been done (faster compilation, faser tests, etc)
If we can improve more, I think it can be done as a regular debt task.
This used to take 45 minutes or longer back a year ago, now its around 15 minutes
