### ISSUE TITLE
Jump to the error line by clicking on the line vscode (python, interactive window)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#10409]
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/10390

<div type='discussions-op-text'>

<sup>Originally posted by **zhaoguangyuan123** June 10, 2022</sup>
Same as the question in the link:
https://github.com/microsoft/vscode/issues/117783

I want to jump to the error Line by clicking the line on the output of the interactive window, but I find it is dark and I am not able to click. 

Is this caused by extension error?
if so, how can i solve the issue?

<img width="687" alt="image" src="https://user-images.githubusercontent.com/48136187/172900349-bb186f39-b141-4906-8b49-aca4a4a5d361.png">

</div>

**Comment by DonJayamanne** [comment]
this should already work today. 
ill transfer this to the issue.
please could you provide the following information:
* version of python
* are you connected to a remote or local kernel?
* output from the `Jupyter` output panel (use the command `Jupyter : Sow Output`)

**Comment by rchiodo** [comment]
The version of 'ipython' is critical to see why this isn't working. If the version is less than 8.0, then it's not supported.

**Comment by zhaoguangyuan123** [comment]
Sorry for my late reply. Below is the information:

**version of python**
Python 3.8.5

are you connected to a remote or local kernel?
**local kernel on MAC** 
output from the Jupyter output panel (use the command Jupyter : Sow Output)

 **version of 'ipython'**
7.22

**Comment by zhaoguangyuan123** [comment]
> The version of 'ipython' is critical to see why this isn't working. If the version is less than 8.0, then it's not supported.

Thanks a lot, it works when I upgrade Ipython from 7.22 to 8.4.

Best 
Guangyuan
