### ISSUE TITLE
Continuous loading for Jupyter: Variables in VS Code Explorer tab

### ISSUE THREAD

**Issue by kenf1** [microsoft/vscode-jupyter#10413]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Jupyter: Variables in VS Code Explorer tab would continuously try to load variables when opening a folder, non-.ipynb or non-.py file. It would finally stop loading when I create a blank .ipynb or .py file and close it without saving changes.

### VS Code Version

1.68.0 (Universal)

### Jupyter Extension Version

v2022.5.1001601848

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
can repro, thanks for the bug

**Comment by rchiodo** [comment]
We may need an activation event for the pane.

**Comment by rchiodo** [comment]
Verification steps:

1. Install jupyter extension (prerelease)
2. Open a blank folder
3. Open the output tab
4. Click on the 'jupyter' header

This should cause the jupyter extension to load and the tab should change to say 'no variables'
