### ISSUE TITLE
CDN is not the 'default' option for widgets

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10439]
Looking on the CDN is secondary and is only done if there's a failure. 

We should probably always start with the CDN (because it usually packs all requirements into a single js file) and then fallback to the jupyter server.

**Comment by rchiodo** [comment]
Widget script sources should default to our two CDNs:

![image](https://user-images.githubusercontent.com/19672699/176748127-d5cd8a3b-f181-4a33-83d9-727bf9204fb4.png)

**Comment by rchiodo** [comment]
Oh wait. I had that already specified in my user settings.

**Comment by rchiodo** [comment]
I don't think this is working. I removed my CDN setting and cleared out the 'tmp' folder under the extension.

Then ran this code in the IW:

```
from ipyleaflet import (
    Map,
    Marker, MarkerCluster,
    TileLayer, ImageOverlay,
    Polyline, Polygon, Rectangle, Circle, CircleMarker,
    Popup,
    GeoJSON,
    DrawControl,
    basemaps
)
from ipyleaflet.leaflet import Heatmap
from ipywidgets import HTML
from random import uniform
import time
center = (52.204793, 360.121558)

m = Map(center=center, zoom=15)

marker = Marker(location=center, draggable=True)
m.add_layer(marker);

display(m)
```

The output I get is missing the jpg from the middle:

![image](https://user-images.githubusercontent.com/19672699/176749911-b6fbaa24-e645-4e14-bc6a-98b9c959dfe8.png)

If I turn the CDN on explicitly and repeat everything, I get the icon in the middle:

![image](https://user-images.githubusercontent.com/19672699/176750244-f3f05d23-a5c2-4028-a549-4e328c1060a6.png)

This sure makes it seem like the CDN is NOT the default.

**Comment by rchiodo** [comment]
For web without a CDN set, it still doesn't work. Seems like it should after the change you made yesterday.

**Comment by DonJayamanne** [comment]
I don't think we need to do anything here.
* If CDN is not enabled (first time), then user is infoemd about this.
    * If the user click `do not show again` we never warn them
    * If the user ignore, we warn them again til they do something
    * If the user clicks ok then CDN is enabled

Now if later the user changes the settings, i don't think we should warn them again.
That's basically the same as warnings the users again & again & again, unnecessarily.
I.e. the user was informed once, and the changes were made.
if subsequently the user changes this its on the user,
However if things do NOT work, then we do warn the user about this.

E.g. in the above screenshot (you should not run into the issue with image not being downloaded) as this will work with local & remove connections.

Again, if users change settings i don't think we should warn them about this (its possible the user wishes to do this on purpose, hence warning them is wrong).

**Comment by DonJayamanne** [comment]
I think we should fix this if:
* User removes the settings entirely from the settings.json file
However what if the user reverts the settings to the defaults, do we still ignore this scenario (is this the same as the user setting the value to an empty list?)

**Comment by rzhao271** [comment]
If the setting is removed entirely from the settings.json file, the setting value is reverted to the default. If the user sets the value to an empty list, that overrides whatever the default value is.

**Comment by DonJayamanne** [comment]
> User removes the settings entirely from the settings.json file
However what if the user reverts the settings to the defaults

This is an edge case and users haven't complained about this, hence closing this issue for now
