### ISSUE TITLE
Environment variables stored in kernel spec

### ISSUE THREAD

**Issue by willbowditch** [microsoft/vscode-jupyter#10449]
## Environment data

-   VS Code version: 1.68.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.5.1001601848
-   Python Extension version (available under the Extensions sidebar): v2022.8.0
-   OS (Windows | Mac | Linux distro) and version: Mac 12.4
-   Python and/or Anaconda version: v3.10.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): poetry
-   Jupyter server running: Local 

## Expected behaviour

Environment variables from the shell which starts `code .` should be available to the python interpreter

## Actual behaviour

Environment variables are being overridden to the values available when the kernel was created. A change to the value in the shell calling `code .` does not make it to the kernel. 

e.g. when running in an interactive notebook

```py
    import os
    {x: y for x,y in os.environ.items()}
``` 
doesn't contain the same variables from the parent shell. 

The variables appear to be coming from the kernel spec stored at: `~/.vscode/extensions/ms-toolsai.jupyter-2022.5.1001601848/temp/jupyter/kernels/python3104jvsc74a57bd0e4d8ccd8f336f6dcbbb8d3894e7b009042858cff9773302a24e306afcf1cd08b/kernel.json`

Editing the values/keys in this file changes the values available in ipython after relaunching:
```json
{
  ...,
  "env": {
    "VSCODE_CLI": "1",
    "SPACESHIP_VERSION": "3.16.7",
    "STARSHIP_SHELL": "zsh"
  }
}
```

I've not been able to find a setting to disable this persistence and, although I'm on a fresh install of vs-code, I don't think this was the default behaviour before. 

## Steps to reproduce:

1. Create a kernel via vs-code
2. Change an environment variable
3. Relaunch and the environment variable will not have changed inside the python instance

**Comment by rchiodo** [comment]
Thanks for the bug. This is actually the same root cause as this issue: 
https://github.com/microsoft/vscode-jupyter/issues/9774
