### ISSUE TITLE
Directly saved graphs from interactive window always match to the VSCode theme

### ISSUE THREAD

**Issue by Fred-Wu** [microsoft/vscode-jupyter#10448]
-   VS Code version: Version: 1.68.0
-   Jupyter Extension version: v2022.5.1001601848
-   Python Extension version: v2022.8.0
-   OS:  Mac  and version: Monterey 12.4
-   Python: 3.9.13
-   Jupyter server running: Local 

Saved graphics always match to the VSCode theme, even theme matching was disabled in the setting. 

Appears in the interactive window:

<img width="718" alt="image" src="https://user-images.githubusercontent.com/4111978/173629851-f3d4f5c0-813f-4aa9-93e2-abc219c46fa1.png">

Directly saved with the button

<img width="987" alt="image" src="https://user-images.githubusercontent.com/4111978/173630037-ba6771b1-a78d-4fd7-9583-32190f4f2fe3.png">

**Comment by rchiodo** [comment]
Thanks for the issue.

That's by design. The image doesn't have a black background, it has a transparent background.

**Comment by rchiodo** [comment]
While in the interactive window, if we notice the theme is dark but the plot is not, we add a white background behind it when displaying it. But the png editor wouldn't do such a thing.

**Comment by Fred-Wu** [comment]
However, the issue is `plotly`'s own png saving works OK.  Therefore, there must something similar can be done

<img width="904" alt="image" src="https://user-images.githubusercontent.com/4111978/173632038-a0eecc22-a3a4-4074-a7d1-b846a6f05ce5.png">

**Comment by rchiodo** [comment]
I don't believe we'd want to do that. The output png from matplotlib does not have a background on it. We don't want to attempt to 'fill' the background on a png already created.

**Comment by rchiodo** [comment]
For matplotlib, you can control this transparency yourself. Like so:

```
# %% Setup default params
import matplotlib.pyplot as plt
plt.rcParams['axes.facecolor'] = 'white'
plt.rcParams['figure.facecolor'] = 'green'

# %% Plot something
x = np.linspace(0, 20, 100)
fig = plt.plot(x, np.sin(x))
fig
```

The saved PNG in this case looks like so:

![image](https://user-images.githubusercontent.com/19672699/173636789-c2c085be-e347-43f6-9049-f169bb172c24.png)

**Comment by Fred-Wu** [comment]
Thanks. I was actually trying `plt.figure(facecolor='white')`, but apparent this is not working. 
Have to use `plt.rcParams['figure.facecolor']='white'`
