### ISSUE TITLE
Plot settings are not applied in the first run, but works in the subsequent runs. 

### ISSUE THREAD

**Issue by Fred-Wu** [microsoft/vscode-jupyter#10452]
VS Code version: Version: 1.68.0
    Jupyter Extension version: v2022.5.1001601848
    Python Extension version: v2022.8.0
    OS: Mac and version: Monterey 12.4
    Python: 3.9.13
    Jupyter server running: Local

First run:
Also the settings were not applied to the saved plot. 

<img width="719" alt="image" src="https://user-images.githubusercontent.com/4111978/173639889-2956a092-e62c-4e69-a48b-13b61436f500.png">

Second run:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/4111978/173639995-9b673baa-0af9-405e-8eaf-2d08e971c69b.png">

**Comment by rchiodo** [comment]
Thanks I can repro. Not sure what could possibly cause this problem. Tried in jupyter notebooks and it doesn't repro there.

Saving a figure is separate. You have to apply settings during the save.

**Comment by Fred-Wu** [comment]
Saving figure works too in the second run.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, however I can repro the exact same issue in both Jupyter Notebook and Jupyter Lab
Closing this issue as its not specific to VS Code.

@Fred-Wu please could you double check this in Jupyter lab/notebooks, from my end, I can easily repro the exact same behaviour out side vs code (i.e. in jupyter lab/notebook)
