### ISSUE TITLE
Cannot save Jupyter notebook file

### ISSUE THREAD

**Issue by theinthankhaing** [microsoft/vscode-jupyter#1046]
Issue Type: <b>Bug</b>

To save .ipynb file, crl + s command is used. However, the file is not saved. 

Extension version: 2020.5.78807
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (2.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ZER-0-NE** [comment]
I literally lost all of my work because of this. The autosave feature was on and now I see nothing got saved.

**Comment by claudiaregio** [comment]
@ZER-0-NE, did you try reopening the notebook? I had a user say they saved their notebook and realized stuff was missing. They reopened the notebook and all their changes were actually there. Wondering if this is the case for you too?

**Comment by ZER-0-NE** [comment]
I'm sorry, I've overwritten the changes so can't really say.
