### ISSUE TITLE
🐛 Restarting kernel doesn't clear number prefixes of the cells

### ISSUE THREAD

**Issue by SachinShekhar** [microsoft/vscode-jupyter#10481]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Restarting the kernel doesn't clear the number prefixes of the cells. It gets more confusing when I execute cells after kernel restart and the number prefixes of all other cells remain from the previous kernel session.

**How to replicate this bug**
1. Do some computations across several cells so that the number prefixes of the cells appear.
2. Restart kernel.
3. You can observe that number prefixes of the cells haven't been cleared.
4. Execute any one cell. Its number prefix will be updated, but other cells will retain their number prefixes from the previous kernel session.

(Both 3 & 4 are bugs)

### VS Code Version

Version: 1.68.0 (Universal) Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f Date: 2022-06-08T11:44:00.250Z Electron: 17.4.7 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Darwin x64 21.5.0

### Jupyter Extension Version

v2022.5.1001601848

### Running Jupyter locally or remotely?

Local

**Comment by IanMatthewHuff** [comment]
@SachinShekhar This behavior is consistent with the general behavior of Jupyter in the restart scenario. I don't believe that we would change this as that would make it work differently than `jupyter notebook` and `jupyter lab` does. Example below I've restarted a Jupyter kernel and re-executed the second cell. Cells 1 and 2 both have execution prefix 1.
<img width="774" alt="image" src="https://user-images.githubusercontent.com/812783/174328706-3b6ecedf-d9eb-42f6-9d95-290767255ba9.png">
