### ISSUE TITLE
issue about the extension name while saving new  jupyterbook file

### ISSUE THREAD

**Issue by nowading** [microsoft/vscode-jupyter#10498]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?
The file extension should not be json.
![new jupyterbook](https://user-images.githubusercontent.com/74819075/174429049-4dd8c761-bdcd-42cb-82c9-165fb7c85902.png)
![image](https://user-images.githubusercontent.com/74819075/174429549-75024c5b-d6af-463f-8574-f18f3e3c66a1.png)

### VS Code Version

Version: 1.66.2 Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977 Date: 2022-04-11T07:46:01.075Z Electron: 17.2.0 Chromium: 98.0.4758.109 Node.js: 16.13.0 V8: 9.8.177.11-electron.0 OS: Windows_NT x64 10.0.19041

### Jupyter Extension Version

v2022.3.1000901801

### Jupyter logs

```shell
Info 16:10:04: Raw session started and connected
启动内核 Python 3.7.8
Info 16:10:04: Finished connecting 7b68ad63-d0ba-4162-81f6-75f292f6270a
Info 16:10:04: Executing silently Code (idle) = import site\nsite.addsitedir(site.getusersitepackages())\n__vsc_ipynb_file__ = "Untitled-1.ipynb"\n%con
Info 16:10:04: Executing silently Code (completed) = import site\nsite.addsitedir(site.getusersitepackages())\n__vsc_ipynb_file__ = "Untitled-1.ipynb"\n%con
Info 16:10:04: Waiting for idle on (kernel): 2f73873b-d374-4f74-8c81-9c68508ac373 -> idle
Info 16:10:04: Finished waiting for idle on (kernel): 2f73873b-d374-4f74-8c81-9c68508ac373 -> idle
```

### Coding Language and Runtime Version

Python v3.7.8

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
I believe this issue was fixed recently in vscode core, can you try updating and check if the problem still exists?

**Comment by nowading** [comment]
> I believe this issue was fixed recently in vscode core, can you try updating and check if the problem still exists?

In version v1.68.1, the bug has been fixed and the problem has been solved. 
thanks.
