### ISSUE TITLE
Automatically disconnect local conda kernel and switch to dummy kernel.

### ISSUE THREAD

**Issue by fangning-ren** [microsoft/vscode-jupyter#10514]
## Environment data

-   VS Code version: 1.68.1
-   Jupyter Extension version (available under the Extensions sidebar): v2022.5.1001601848
-   Python Extension version (available under the Extensions sidebar): v2022.8.0
-   OS (Windows | Mac | Linux distro) and version: windows 10 education
-   Python and/or Anaconda version: 3.9.12/4.12.0
-   Type of virtual environment used: conda
-   Jupyter server running: Local 

## Expected behaviour

connect to my conda kernel and run every cells

## Actual behaviour

##Three possible behaviors
1. shows no kernel and do nothing
2. shows a kernel named "Python 3" with no python installed. Click run cell will norify me to install python
3. shows the correct kernel at the beginning. but it switch back to no kernel or the "Python 3" kernel in one seconds.
4. shows the correct kernel at the beginning. Could run a few commands. But soon switch to no kernel or the "Python 3" kernel.

## Steps to reproduce:
1. Create a new notebook
2. Open it with vscode.
3. create a new cell.
4. Select kernel to anything except "Python 3".
5. run the cell. The cell may be correctly executed.
6. Then the kernel is autometicly disconnected with no reason.

![1 ipynb - figures - Visual Studio Code 2022-06-20 18-16-18](https://user-images.githubusercontent.com/89762682/174684109-b4eea9d5-eced-41d3-afd6-a80a7fccc64e.gif)

**Comment by DonJayamanne** [comment]
Thanks for reporting this issue, i believe this has been resolve din our pre-reelase build.
Please could you:
* Install our pre-release build as follows:
* Go into the extensions tab & search for Jupyter, then click the button `Switch to Pre-Release Version`
See below
![Screen Shot 2022-06-24 at 12 22 21](https://user-images.githubusercontent.com/1948812/175449485-9acccf5e-f3b6-46b4-b0f8-410c650a8e06.png)


Please let me know how that goes

**Comment by amunger** [comment]
closing since it has been over a month since the info was requested
