### ISSUE TITLE
NameError: name '_VSCODE_getVariableInfo' is not defined

### ISSUE THREAD

**Issue by yc1999** [microsoft/vscode-jupyter#10516]
I was debugging...

When I chose "`view value in data viewer`" for a variable at a checkpoint for the first time, it worked fine as normal. 

Then  I clicked `F5`, and the programme **stopped at the same checkpoint**. 

But when I chose "`view value in data viewer`" for a variable again, it didn't work and the log was as follows

```shell
error 11:44:25.215: Error: Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name '_VSCODE_getVariableInfo' is not defined

    at o.handleErrorResponse (vscode-file://vscode-app/d:/vscode/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1041:45806)
    at vscode-file://vscode-app/d:/vscode/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1041:45245
warn 11:44:25.215: DataScience Error Error: Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name '_VSCODE_getVariableInfo' is not defined

    at o.handleErrorResponse (vscode-file://vscode-app/d:/vscode/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1041:45806)
    at vscode-file://vscode-app/d:/vscode/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1041:45245
```

**Comment by yc1999** [comment]
What's more, when my programme first stoped at the checkpoint, the `VARIABLES` are as follows:
![image](https://user-images.githubusercontent.com/37548571/174758284-7f318997-8dd4-4963-ae3c-812a1b66d872.png)
But when I clicked F5, and stopped at the checkpoint at scecond time, the `VARIABLES` are as follows:
![image](https://user-images.githubusercontent.com/37548571/174758555-b283b183-c6ad-4f32-90c4-551052595fad.png)

So, as you can see , a lot of `_VSCODE*` variables disappeared, it's so wired...

**Comment by rchiodo** [comment]
Thanks for the issue. My guess is that the second breakpoint was a different module and we're not loading the evaluation objects correctly.

Can you describe the two breakpoints more? Or provide repro source? Thanks.

**Comment by yc1999** [comment]
emmm, the first breakpoint and the second breakpoint is the same. I clicked `F5` to stop at the same checkpoint everytime.
![image](https://user-images.githubusercontent.com/37548571/174929980-f58bf9a8-b585-416b-9f8b-207fd211baf3.png)

**Comment by sanderdw** [comment]
I have the exact same problem.

**Comment by vincentvalton** [comment]
Same problem with either dataframe or tensors. Seems to have popped up during the last vscode update as it used to work fine before.

**Comment by vincentvalton** [comment]
In the meantime as a workaround: I can confirm that regressing to vscode 1.67.2 fixes the issue.

https://code.visualstudio.com/updates/v1_67

**Comment by yc1999** [comment]
> In the meantime as a workaround: I can confirm that regressing to vscode 1.67.2 fixes the issue.
> 
> https://code.visualstudio.com/updates/v1_67

oooooh, thank you. 
😂Forgive me, I have one more question: If I download version 1.67.2, and install it to replace version 1.68. Will my resources in 
 the version 1.68 disapper in the version 1.67.2 ? (such as extensions, preferences...)  @vincentvalton

**Comment by vincentvalton** [comment]
I have both versions installed, and all my preferences are there on both versions.

I had to downgrade the jupyter extension to an earlier version, but once that was done it all worked perfectly :+1: with the v1.67.2 (until the current version is updated and fixed)

**Comment by rchiodo** [comment]
My guess would be this change: 
https://github.com/microsoft/vscode-jupyter/commit/505dc65452fd8f61bb1148923922fcb8b7eea801

We used to load the script itself as a module. We don't do that because of needing to support web, but then since the code is only loaded once, we never reload for a new stack frame.

**Comment by rchiodo** [comment]
Test should be updated to make sure it causes more than one stack frame.
