### ISSUE TITLE
"Debug a cell from a python file" test is flaky

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#10521]
Error: FAILED TEST NAME: Interactive Window Debugging Debugging with VSCodePythonDebugger Debug a cell from a python file
Code lens with command jupyter.debugcell not found
Error: Code lens with command jupyter.debugcell not found
    at Timeout.<anonymous> (src/test/common.ts:56:20)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

Seems to fail every so often in CI runs. 
https://github.com/microsoft/vscode-jupyter/runs/6990014444?check_suite_focus=true

**Comment by amunger** [comment]
fixed in https://github.com/microsoft/vscode-jupyter/pull/10899
