### ISSUE TITLE
"SyntaxError: unexpected character after line continuation character" pops up

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#10531]
## Environment data

Build of Visual Studio Code - Insiders: 1.69.0-insider(user setup)
Build of python-Pre-Release: v2022.9.11681004
Build of jupyter-Pre-Release: v2022.6.1001741036
Build of pylance-Pre-Release: v2022.6.21
Build of jupyter Notebook Renderers: v1.0.8
Build of jupyter Keymap: v1.0.0

## Steps to reproduce:
1.Make sure Anaconda installed in local 
2.Open the file src/test/datascience/manualTestFiles/manualTestFile.py in VS Code 
3.At the top of the file it will list the things that you need installed in your Python environment 
4. On the first cell click Run Below 
5.Interactive Window should open, show connection information, and execute cells 
6.Check the "# %% Latex"

## Expected behaviour
Execute cells sucessfully without errors
![image](https://user-images.githubusercontent.com/59192491/174934681-2356a177-e79f-4fef-8c4a-98c39bacd658.png)

## Actual behaviour
![image](https://user-images.githubusercontent.com/59192491/174936047-8196a087-8dbd-4b31-b897-4d3dcae6d977.png)

![image](https://user-images.githubusercontent.com/59192491/174934790-b04bc4d4-cde9-4114-9d83-02f098013816.png)

## Sample code

```
# %% Latex 

%%latex 

\begin{align} 

\nabla \cdot \vec{\mathbf{E}} & = 4 \pi \rho \\ 

\nabla \times \vec{\mathbf{E}}\, +\, \frac1c\, \frac{\partial\vec{\mathbf{B}}}{\partial t} & = \vec{\mathbf{0}} \\ 

\nabla \cdot \vec{\mathbf{B}} & = 0 

\end{align} 
```

**Comment by rchiodo** [comment]
I wonder when this stopped working. Did we perhaps escape this before?

**Comment by rchiodo** [comment]
/verified

![image](https://user-images.githubusercontent.com/19672699/176744051-58b4aaa9-e1b2-495b-a132-72da030aec3f.png)
