### ISSUE TITLE
Extra `Cancel` button on restart kernel modal window

### ISSUE THREAD

**Issue by kilacoda** [microsoft/vscode-jupyter#10536]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

On restarting the kernel using the `Restart` button, I get a window that looks like this:

![image](https://user-images.githubusercontent.com/14952412/175110848-88e6950e-30a0-486a-8f5b-a3bc6fa91bfa.png)

Nothing too serious, but just kind of has an unnecessary button there.

### VS Code Version

Version: 1.69.0-insider (user setup) Commit: fbf1cf3832d43088e27837dbb68d24ab65a098c1 Date: 2022-06-17T05:16:33.731Z Electron: 18.3.3 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Windows_NT x64 10.0.19044

### Jupyter Extension Version

v2022.6.1001751046

### Coding Language and Runtime Version

Julia 1.7.2

### Language Extension Version (if applicable)

Julia - v1.6.24

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment]
Thanks for the issue. 

When we switched to modal, we should have remove the 'Cancel' button as we get one by default.

**Comment by kilacoda** [comment]
I'd be willing to fix it myself, seems like a one-liner but I don't know which file handles this stuff since I'm not at all familiar with this repo 😅

**Comment by rchiodo** [comment]
Code is here:
https://github.com/microsoft/vscode-jupyter/blob/de7254b63def4659b85f3ff9c32728536b65ede5/src/notebooks/notebookCommandListener.ts#L218

The 'No' option is actually the 'Cancel'.

**Comment by kilacoda** [comment]
Got it.

**Comment by kilacoda** [comment]
Should be fixed by #10539!
