### ISSUE TITLE
Data Viewer does not display Series data if index and column names are equal

### ISSUE THREAD

**Issue by andreas-wolf** [microsoft/vscode-jupyter#10533]
## Environment data

- VS Code version: 1.68.1
- Jupyter Extension version (available under the Extensions sidebar): v2022.5.1001601848
- Python Extension version (available under the Extensions sidebar): v2022.8.0
- OS (Windows | Mac | Linux distro) and version: Ubuntu 22.04
- Python and/or Anaconda version: Python 3.9.13 / 4.12.0
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Jupyter server running: Local

## Expected behaviour

Data view shows index and data column

## Actual behaviour

Data view only shows index column. 
I assume it creates a column for the data and that column is then overwritten with index values.
It may seem odd to name columns and indices with the same name, but this happens often automatically when grouping and then aggregating data frames.

## Steps to reproduce:
```
import pandas as pd
ser2 = pd.Series({1: 0, 2: 0, 3: 0})
ser2.name = 'A'
ser2.index.name = 'A'

1    0
2    0
3    0
dtype: int64
```
Displayed as

```
   A
0  1
1  2
2  3
```
Expected:
```
   Index A A
0  1       0
1  2       0
2  3       0
```

**Comment by rchiodo** [comment]
Thanks for the issue. I believe we'd have to special case when the index is the same as another column.

**Comment by andreas-wolf** [comment]
> I believe we'd have to special case when the index is the same as another column.
 Probably it would be better to just prefix the index colum name anyway to show that it is the index column i.e. if the index has the name A its column name would be Index A. Then there is no special case or inconsistency in the name shown. Furthermore it might be easier for Multiindexes.

**Comment by amunger** [comment]
closing as the jupyter data viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486
