### ISSUE TITLE
Default remote controller is always based on the first notebook

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10542]
See the code here:
https://github.com/microsoft/vscode-jupyter/blob/150d59679bbad582823386a7e851e286b035a81b/src/notebooks/controllers/notebookControllerManager.ts#L230

We don't use the URI to figure out the actual notebook so the metadata could be wrong.

**Comment by DonJayamanne** [comment]
This will be fixed with the new kernel picker
