### ISSUE TITLE
after saving a new notebook, the import of libraries gives an error

### ISSUE THREAD

**Issue by gab7001** [microsoft/vscode-jupyter#10553]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I started using copilot with vscode. I created a new notebook, and added few lines importing libraries like numpy, pandas, etc. The code works, but once I save the file the first time I get the error below. This happens with other libraries. I restarted the kernel without success. Any ideas? 

ModuleNotFoundError                       Traceback (most recent call last)
c:\Users\someuser\OneDrive\Documents\Jupyter Notebooks\xxxxx.ipynb Cell 1' in <cell line: 1>()
----> [1](vscode-notebook-cell:/c%3A/Users/germa/OneDrive/Documents/Jupyter%20Notebooks/Untitled-2.ipynb#ch0000000?line=0) import numpy as np

ModuleNotFoundError: No module named 'numpy'

### VS Code Version

Version: 1.68.1 (user setup) Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630 Date: 2022-06-14T12:48:58.283Z Electron: 17.4.7 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Windows_NT x64 10.0.22000

### Jupyter Extension Version

Name: Jupyter Id: ms-toolsai.jupyter Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more. Version: 2022.5.1001601848 Publisher: Microsoft VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

### Jupyter logs

```shell
[{
	"resource": "/C:/Users/someuser/OneDrive/Documents/Jupyter Notebooks/xxxxx.ipynb",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules",
			"path": "/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "diagnostic-severity-rules"
		}
	},
	"severity": 4,
	"message": "Import \"numpy\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 1,
	"startColumn": 8,
	"endLineNumber": 1,
	"endColumn": 13
}]
```

### Coding Language and Runtime Version

Python 3.10.5

### Running Jupyter locally or remotely?

Local

**Comment by IanMatthewHuff** [comment]
@gab7001 Thanks for reporting the issue. Can I ask a clarification question or two? I'm not sure that I fully understand the scenario. So you are executing cells in a python notebook, the cells run and execute fine, but in the errors window (and with squiggles on cells) you are seeing warnings that imports are missing? Could you do me a favor here, could you take a screenshot of the scenario as is? I'd like to see what it looks like from your end.

**Comment by IanMatthewHuff** [comment]
Ohh, and one more quick thing. That Jupyter log look a bit funny. Could you please copy out the full contents of the "Jupyter" tab of the output window? You can save that to a file and then attach it in a comment here. That would have the full debugging output that I could diagnose with.

**Comment by gab7001** [comment]
![image](https://user-images.githubusercontent.com/10581080/175429761-0a321b34-dffa-47c2-b046-2939f4615274.png)

**Comment by gab7001** [comment]
Here is another screenshot, Problems have to do with Pylance. Not sure what that is.

![image](https://user-images.githubusercontent.com/10581080/175431816-645dfde8-f787-4392-9472-2c1a032a48e1.png)

**Comment by gab7001** [comment]
Actually, I guess I have to install the libraries from the Terminal using pip. I did that and the problem is fixed. In any case, wondering if the system would present the solution in a more explicit way. It would be nice if there was a message saying something like "libraries need to be installed from the Terminal using pip ... bla bla" ... , particularly for newbies like myself.
