### ISSUE TITLE
cell runs forever and can't interrupt if remote server is unavailable

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#10568]
1. Connect to a remote jupyter server
2. Run a cell on a remote kernel
3. Kill the server
4. Run a cell on the same kernel

Result:
Cell stays in executing state indefinitely. Interrupt won't stop it.

**Comment by rzhao271** [comment]
This seems like a duplicate of https://github.com/microsoft/vscode-jupyter/issues/9828.
