### ISSUE TITLE
Debugging not available after installing ipykernel in jupyter notebook

### ISSUE THREAD

**Issue by thesyncopater** [microsoft/vscode-jupyter#10586]
## Environment data

-   VS Code version: 1.68.1
-   Jupyter Extension version (available under the Extensions sidebar): 2022.5.1001601848
-   Python Extension version (available under the Extensions sidebar): 2022.8.0
-   OS (Windows | Mac | Linux distro) and version: 19042.1766
-   Python and/or Anaconda version: 3.7.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A: N/A

## Expected behaviour

Debug cell results in line-by-line debugging with step into.

## Actual behaviour

VS code window directing me to "Ipykernel setup required for this feature".  I already installed ipykernel... 'pip install --user ipykernel'

## Steps to reproduce:
1. in a jupyter notebook: 
import numpy as np
g= np.arange(1,5) ,<--- set a breakpoint on this line

2. Click the down arrow and go to debug cell

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
Please could you ensure the `ipykernel` package is installed into the python environment installing it at the user level. Installing at the user level is known to cause a few issues. basically activate the environment in the terminal & remove the `--user` flag from the CLI.

Also, please could you run the following cell and let me know what you get in the output
```python
import ipykernel
print(ipykernel.__version__)
```

**Comment by thesyncopater** [comment]
I initially used “—user” because that’s what the help page says and also because the first time I tried it I got some permission issues. I tried it again without user and installed it.  I checked try e version and it looked like and older version so I updated it to 6.15.0. 

The debug works now. I guess this isn’t a bug. Thanks for your help. 

I do have the trouble of vs code stepping over lines when I want to step in. I’ve changed my launch.json “justmycode” to false but that doesn’t seem to have any effect.

**Comment by DonJayamanne** [comment]
>  trouble of vs code stepping over lines when I want to step in. I’ve changed my launch.json “justmycode” to false but that doesn’t

please could you file a separate issue for that 
thanks for getting back with the details, closing this issue as resolved
