### ISSUE TITLE
Interactive window debugging no longer works in insiders

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10592]
Open python file
Run cell
Debug a cell

- Never attaches.

Log looks like we never send breakpoints.

**Comment by DonJayamanne** [comment]
I tested this last week in VS Code Stable & latest pre-release version of Jupyter extension.
Basically only broken in VS Code insiders.

**Comment by rchiodo** [comment]
I have logs of it working and not:

Working:
[working.zip](https://github.com/microsoft/vscode-jupyter/files/8996001/working.zip)

Not:
[not.zip](https://github.com/microsoft/vscode-jupyter/files/8995999/not.zip)

**Comment by DonJayamanne** [comment]
> his a bunch of times this morning and I'm 100% on debugging success rate. Sounds like the two of you might have a better repro, but it has yet to fail for me.

@rchiodo @IanMatthewHuff it works for me. I tried this yesterday and wasn't able to repro this either.

**Comment by DonJayamanne** [comment]
I just test this once again, & I can debug local & remote kernels with that setting turned on, in both IW and Notebooks.

**Comment by rchiodo** [comment]
Must be a race condition then that only my machine is reproing. @amunger can you try? Don and Ian are using Mac I believe. I'm using Windows. Might be only reproing on windows.

**Comment by amunger** [comment]
I actually can't debug with or without that setting, so it's even worse for me
