### ISSUE TITLE
Adopt new cell context key pattern

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#10595]
Adopt https://github.com/microsoft/vscode/issues/146686 and https://github.com/microsoft/vscode/issues/147732#issuecomment-1144008503

**Comment by roblourens** [comment]
Blocked on https://github.com/microsoft/vscode/issues/154582 now

**Comment by DonJayamanne** [comment]
@roblourens can you provide some instructions on what needs to be tested here (i.e. how to verify this issue)

**Comment by roblourens** [comment]
Steps:

- Set `"notebook.cellToolbarVisibility": "hover"`
- Start RBL in cell A
- Hover cell B, it should not show the RBL buttons that cell A's toolbar has
