### ISSUE TITLE
Jupyter notebook: Slider widget doesn't come back after presentation change

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-jupyter#10608]
Testing #10434

- in a noteboook cell run
```
import ipywidgets as widgets
widgets.IntSlider()
```
a slider appears :heavy_check_mark: 
- right before the slide, from the `...` menu, run `Change Presentation` and change to `text/plain`. Text shows :heavy_check_mark: 
- Run `Change Presentation` again and change back to the IPyWidgets renderer. Space stays empty

**Comment by DonJayamanne** [comment]
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/4128
