### ISSUE TITLE
Notebook: Format Notebook  

### ISSUE THREAD

**Issue by AbdelrahmanHamdy1996** [microsoft/vscode-jupyter#1060]
Issue Type: <b>Feature Request</b>

Notebook: Format Notebook not working in "file.ipynb "
jupyter notebook cell 

notebook.format
{
  "key": "ctrl+shift+i",
  "command": "notebook.format",
  "when": "!editorTextFocus && activeEditor == 'workbench.editor.notebook'"
}

Extension version: 2020.5.78807
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.3.0-51-generic

**Comment by JanSawicki** [comment]
I checked the [backlog](https://github.com/microsoft/vscode/issues/91987) that @greazer mentioned and formatting is checked-out ☑️.

> Language Features @jrieken
> - [x] Go to definition
> - [x] Find all references
> - [x] Rename
> - [x] Code actions
> - [x] Formatting inside and across cells
> - [ ] 🏃 Outline

Does it mean that we should be able to format cells in Jupyter Notebooks in VS Code?
