### ISSUE TITLE
Debugger stops at the breakpoint twice 

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#10600]
```python
print(1)
print(2)
print(3)
```

* Add a breakpoint to the second line
* Start debugging in IW or notebook
* Debugger will stop at the desired breakpoint
* Hit continue (F5), and debugger will stop at the same place (same breakpoint) again.

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode-jupyter/issues/10586

**Comment by fabioz** [comment]
Note: this issue should be fixed in the `master` version in debugpy.

**Comment by roblourens** [comment]
I tried with debugpy 1.6.2 and .3 (without the new environment var) and can't repro this issue. Just trying to understand the state of things, does it not happen every time?
