### ISSUE TITLE
Local vs Remote doesn't make sense when in codespaces or remote ssh

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10601]
This general issue is exacerbated when using Codespaces. Specifically, if you are connected to a Codespace running Jupyter server, the VS Code UI is confusing for two reasons: 

1.  The kernel picker doesn't differentiate between kernels running locally versus in the codespace. 
2. The status bar denotes that the server is "local" when it is running in the codespace. While this is a different form of "remote" than what's reflected in the status bar, it's super confusing because conceptually the server is remote.
![Kernel Picking](https://user-images.githubusercontent.com/8644266/172917573-fb2fbca7-f679-4843-972e-927f5718a970.jpg)

_Originally posted by @binderjoe in https://github.com/microsoft/vscode-jupyter/issues/10363#issuecomment-1151453615_

**Comment by DonJayamanne** [comment]
Should we change the name of `Local` to `Code Spaces`, i.e. change the name o `Local` to the name of the remote environment (I believe we can get the name for this from the vscode env.name).

**Comment by DonJayamanne** [comment]
Suggestion:
* Display the name of the jupyter server (host name) in the status bar & quick pick

**Comment by DonJayamanne** [comment]
This should be fixed with the new kernel picker, hence closing this issue
