### ISSUE TITLE
Jupyter has a different intellisense result compare to python files

### ISSUE THREAD

**Issue by wasalive** [microsoft/vscode-jupyter#10603]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

![tqt](https://user-images.githubusercontent.com/96659037/176065748-57b5cff7-6ef0-4edc-a73f-f4dba2f3e0f1.png)
![ttt](https://user-images.githubusercontent.com/96659037/176065750-c59100a7-fd8d-4a4c-aa64-29b7ef25fccc.png)
As seen from the screenshot, I have pylance+python+jupyter extension installed. However, there seems to have many differences within the intellisense autocomplete result. Apparently in jupyter notebook part lack of many methods used in creation of python class. And it seems the autocompletion are designed for some jupyter works only but not python works. Is it possible to have a future feature that jupyter notebook can be using the same autocompletion as python files?

### VS Code Version

1.68.1

### Jupyter Extension Version

2022.5.100

### Coding Language and Runtime Version

Python 3.10.4

### Language Extension Version (if applicable)

2022.8.0

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment]
Not sure why this was closed, but I can answer why there is a discrepancy. 

Jupyter notebooks have completions from pylance and from the IPython kernel as well. IPython can provide more information but can also sometimes provide too much information.

There's a setting that can make IPython provide better information but it can slow down completions to the point where the kernel is stuck for periods of time.

![image](https://user-images.githubusercontent.com/19672699/176230689-a0c05180-f2c8-467f-89e2-d04c31fcb80a.png)
