### ISSUE TITLE
IPyWidgets result presentation is not themed

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-jupyter#10609]
Testing #10434

- create a cell
```
import ipywidgets as widgets
widgets.IntSlider()
```
- run the result
- use the color theme switecher to see how the notebook is rendererd in various themes.
  -> The result presentation is always shown with white background.

![image](https://user-images.githubusercontent.com/6461412/176192386-4789cbeb-297b-43cf-839c-d1c3554f6d30.png)

**Comment by DonJayamanne** [comment]
this is by design. Closing as this is a known issue and not something we plan on addressing.
