### ISSUE TITLE
Error highlight in Interactive window makes text unreadable in dark mode

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#10614]
the highlight for the undefined value in a NameError is too close to the text color:
![image](https://user-images.githubusercontent.com/2019016/176236542-a337a99d-edee-44a5-881e-ea32c373600c.png)

**Comment by amunger** [comment]
stable does not highlight anything, nor does a notebook

**Comment by rchiodo** [comment]
Yes this is the highlighting created by the kernel itself. We remove this highlighting. Perhaps it's changed again.

**Comment by DonJayamanne** [comment]
I cannot repro this at my end, @amunger are you using the same kernel in both stable & insiders?

**Comment by rchiodo** [comment]
Looks like an older version because the links for clicking on the line numbers aren't showing up.

**Comment by amunger** [comment]
Python               3.9.13
ipykernel            6.15.0

**Comment by amunger** [comment]
ipython              8.3.0

**Comment by amunger** [comment]
ah, this only repro's when executing from the input box (nowhere to link to)

**Comment by amunger** [comment]
and only in an interactive window that's not associated with a py file - created with command palette

**Comment by DonJayamanne** [comment]
@amunger Have you possibly switched the renderers, you might have to enure you select the `Jupyter` renderer instead of the built-in vscode renderer.

**Comment by amunger** [comment]
`InteractiveWindowTracebackFormatter.format()` does not get called when using a standalone IW. Still investigating why

**Comment by amunger** [comment]
or rather, that method returns early because there is no `IGeneratedCodeStore` for that notebook
