### ISSUE TITLE
If Python is missing server auto starter tries to run and pops up the "Needs Python Extension" modal

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#10615]
Testing #10590

For step 7 in the Install Python Extension command scenario, i.e. 

> Uninstall the Python extension to clear the kernel that was found (might need to reload the window here as we cache the controllers that we find). This time, instead of clicking the run button click on the command directly and run the command from the kernel picker menu.

Uninstalling the Python extension also uninstalls the Jupyter extension. This is because of the extension pack relationship--all extensions that are part of an extension pack are uninstalled when the extension pack itself is uninstalled.

Additionally, after uninstalling the Python extension I'm prompted to reload the window as mentioned in the TPI. After the reload, presumably because a notebook is open already, I get this: 
![image](https://user-images.githubusercontent.com/30305945/176243308-3e2ddf21-2639-4de4-acf7-cd0d9c55a153.png)

If we're already recommending the Python extension this strongly (having a kernel command to install the Python extension), could we also update this dialog in the screenshot above to include an Install button which will directly install the Python extension?

**Comment by IanMatthewHuff** [comment]
Hmm, actually was our interpreter package checking for telemetry causing this.

Validation steps.

Install Jupyter extension (install this first so you don't get the Python + Jupyter pack)
Install Python extension
Run a notebook with a kernel found by the python extension
Uninstall Python extension
Reload

Previous you'd get a prompt to install the Python Extension. Prompt should be gone now.
