### ISSUE TITLE
How to revert to a less "Jupiter-y" command in VSCode python interactive

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode-jupyter#10626]
I am extensively using Python on VSCode and the interactive mode. However VSCode keeps changing the interactive interface and it is getting difficult to get a consistent workflow.

What I liked about the "old" behaviour of VS code's Python interactive was command line that allowed multi-lines and history scrolling using the up/down arrows. I am personally not a big fan of the more "notebook" style of coding.

Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:52:13.188Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.2.0

There was a [solution](https://stackoverflow.com/questions/69091620/is-it-possible-to-revert-to-the-old-python-interactive-in-vs-code) in so, but now it has failed

**Comment by rchiodo** [comment]
Thanks for the issue.

Sorry but there is no way to go back to the old style. Your best bet is to log style change suggestions on VS code to change it. The jupyter extension doesn't actually provide the UI for this anymore. It is a core piece of VS code now.

**Comment by rchiodo** [comment]
Up/Down should still work in the input box though. It scrolls through the entries that have been typed in the input box. I don't recall if the old one also scrolled through the cells too or not.
