### ISSUE TITLE
Jupyter cell debugging does not step into all code

### ISSUE THREAD

**Issue by thoughtfulmoron** [microsoft/vscode-jupyter#10622]
Running the Debug Cell option does not step into all code despite the Jupyter: Debug Just my Code being deselected in settings

**Comment by DonJayamanne** [comment]
@rchiodo I believe this was by design, even in the old run by line this is what we used to do ( as well as the new nb run by line).

**Comment by rchiodo** [comment]
Run by line is different in my opinion. It doesn't really make sense without just my code.

But DebugCell you might want to step into IPython.

**Comment by DonJayamanne** [comment]
> But DebugCell you might want to step into IPython.

Agreed

**Comment by DonJayamanne** [comment]
Found it, this issue is a duplicate of https://github.com/microsoft/vscode-jupyter/issues/8146

**Comment by DonJayamanne** [comment]
Closing as a duplicate
