### ISSUE TITLE
building of wheel taking a long time

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-jupyter#10620]
Testing #10590

how long should this take? it's been several mins already

https://user-images.githubusercontent.com/29464607/176249079-6f6294e8-68ec-451c-9f03-b998ed790e55.mov

**Comment by IanMatthewHuff** [comment]
I'm closing this down as I don't believe there is anything that we can do on our side specific to the wheel building time. Our main goal here is to make users hit the ipykernel install message way less often, and we have other issues covering that.
