### ISSUE TITLE
Interactive window intellisense needs a middleware piece

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10630]
The input box in the IW is not really a standalone document. In order for pylance to not have to code logic for the IW, we should treat the IW input box just like another cell as far as pylance (or jedi) is concerned.

This would mean intercepting the notebook related messages for the IW cells and adding the IW input box into the list of cells it expects (and possibly remapping the URI so pylance treats it like a notebook cell).

This is a stopgap measure until the core can treat the IW as an entire notebook and has an api for dealing with the IW. At that point it would just treat the input box as another cell (at least that's the suggestion right now).

**Comment by rchiodo** [comment]
See this issue in pylance:
https://github.com/microsoft/pylance-release/issues/2894

The current solution was to understand IW cells in pylance. Seems like the wrong place for this knowledge to exist.

**Comment by debonte** [comment]
This is complete (see the 3 PRs linked above) and available for use if you have the latest release builds of Jupyter, Python, and Pylance.
