### ISSUE TITLE
Breakpoint in unrelated code causes issues with interactive debugging

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-jupyter#10635]
Testing https://github.com/microsoft/vscode-jupyter/issues/10258

1. Set a breakpoint as described in an issue
2. In any other random file in the workspace, set a breakpoint
3. Debug cell 2 as described
4. Notice the other breakpoint got moved into cell 

https://user-images.githubusercontent.com/2230985/176558633-df367096-3f6d-483c-841e-2bce920926ff.mp4

**Comment by rchiodo** [comment]
I can't seem to repro this. @connor4312 what extensions do you have installed?

**Comment by rchiodo** [comment]
I can't use 'forceIpykernelDebugger' at the moment as it doesn't work for me.

**Comment by roblourens** [comment]
I can't repro, and haven't heard anything else. This is an odd one, @connor4312 can you try again to verify it's gone? Please upgrade to the latest debugpy in your environment first because we had fixes from there.
