### ISSUE TITLE
Create a DebugEvaluator service

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#10639]
- From: https://github.com/microsoft/vscode-jupyter/issues/10638

This issue tracks the creation of a new service called `DebugEvaluator`. This service would allow any other piece of code to run Python on the debugger.

- This service will copy how the current DebugLocationTrackerFactory retrieves the frame ID.
- This service will replace all the current usages of the DebugLocationTrackerFactory in the same PR.

**Comment by DonJayamanne** [comment]
Closing this issue for now and leaving the main issue open
