### ISSUE TITLE
dataViewerDependencyService to derive the interpreter from the DebugEvaluator

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#10640]
- From: #10638
- After: #10639

Replace the usage of the `PythonEnvironment` (the interpreter) from the parameters of the `dataViewerDependencyService` methods and use the `DebugEvaluator` instead. Evaluate code to get the interpreter path then use the old interpreter code.

**Comment by DonJayamanne** [comment]
closing this for now and leaving the main issue open
