### ISSUE TITLE
Install Data Viewer dependencies using the DebuggerEvaluator

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#10641]
- From: #10638
- After: #10640

Enable installing `pandas` on the `DebuggerEvaluator` version of the `dataViewerDependencyService` by using the code underneath `%pip` and `%conda` in iPython. 

- Completely remove the usage of the interpreter from the dataViewerDependencyService.
- If pandas needs to be installed (either because it's not yet installed or because the version is inadequate), show a prompt message saying that You may need to restart the debugger after the installation is complete.

**Comment by DonJayamanne** [comment]
Closing this for now and leaving the main issue open,
Note: This falls in dependency installer
