### ISSUE TITLE
jupyter doesnt respect launch config

### ISSUE THREAD

**Issue by YoniChechik** [microsoft/vscode-jupyter#10646]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

ipynb and interactive don't respect launch config. this results in problem like env var setting. example:
```
  "launch": {
    "configurations": [
      {
        "name": "Python in workspace",
        "type": "python",
        "request": "launch",
        "program": "${file}",
        "cwd": "${fileDirname}",
        "console": "integratedTerminal",
        // I'm running the file from the file's dir path (for relative paths to work) so I have to add the workspace folder path to PYTHONPATH
        "env": {
          "PYTHONPATH": "${fileWorkspaceFolder}${pathSeparator}${env:PYTHONPATH}"
        }
      },
   ]
}
```
I know that we can do :
```
import os
import sys

sys.path.append(os.path.abspath(".."))
print(sys.path)
```

OR do

`Jupyter: Run Startup Commands` (which doesn't accept ${fileWorkspaceFolder})

as sugested in different issues but both are not really pythonic or scalable to multiple cases.

### VS Code Version

1.68.1

### Jupyter Extension Version

v2022.5.1001601848

### Coding Language and Runtime Version

python 3.9

### Language Extension Version (if applicable)

v2022.8.1

### Running Jupyter locally or remotely?

Local

**Comment by IanMatthewHuff** [comment]
@YoniChechik you are correct that we don't work with Python launch configs for this. Question, would you expect a separate notebook launch configuration? Or for a python notebook to respect general python launch configs when launching?

As a side note does using a .env file work in your scenario? That should be picked up and respected by Jupyter notebooks and the interactive window.
