### ISSUE TITLE
Kind ordering for kernels is 'english' specific

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10656]
See the code here:
https://github.com/rchiodo/vscode/blob/4cf4438fc001e0c925905af51577cfc1db72f42c/src/vs/workbench/contrib/notebook/browser/contrib/editorStatusBar/editorStatusBar.ts#L204

I copied this code on this pr as well:
https://github.com/microsoft/vscode-jupyter/pull/10602

Both should be made locale aware.

**Comment by DonJayamanne** [comment]
@brettcannon are the types of environments like `Virtual Env`, `Conda` localizable?
Are you planning on localizing these in Python extension.
Asking as things could look different and weird if they're localized in one and not the other.
I personally feel localizing this would make sense,

**Comment by brettcannon** [comment]
> are the types of environments like `Virtual Env`, `Conda` localizable?

"Virtual env" is possible, but "conda" is not as that's a product name.



> Are you planning on localizing these in Python extension.

No specific plans, but it's definitely a reasonable ask. I have opened https://github.com/microsoft/vscode-python/issues/20346 .

**Comment by DonJayamanne** [comment]
Haven't had enough upvotes on this issue, hence closing this issue for now
