### ISSUE TITLE
Consider adding a `More Info` button to the modal dialog prompt requiring users to install ipykernel 

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#10658]
Probably consider adding a `more info` button here.

![Screen Shot 2022-07-01 at 08 34 35](https://user-images.githubusercontent.com/1948812/176789783-77bdb0c3-56b5-48c5-86f7-b008c78319b2.png)

**Comment by IanMatthewHuff** [comment]
Validation.

Create a clean venv and select it as your notebook kernel. 
Run a cell to get the missing ipykernel message
See if More Info shows and that it links to the wiki.

**Comment by joyceerhl** [comment]
I do see the More Info button, but if I click it, the modal dialog reappears, not sure if that's expected?
