### ISSUE TITLE
Debugging an IW cell second time ends up displaying a seprate file

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#10657]
* Debug IW cell 
* Hit continue
* Execute text from IW input box
* Debug the same IW cell & now you get the weird window opening up (source maps don't work)

(same problem in stable).

![Screen Shot 2022-07-01 at 08 25 52](https://user-images.githubusercontent.com/1948812/176789026-2762a3fd-0db0-4079-831d-4e76f2af2c54.png)

**Comment by greazer** [comment]
Is this a regression?

**Comment by amunger** [comment]
@DonJayamanne can you check the repro again? I think it was fixed in #10651 (I can't repro it anymore)

**Comment by DonJayamanne** [comment]
verified as fixed
