### ISSUE TITLE
can't find any kernels because I'm in remote mode

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#10665]
Issue Type: <b>Bug</b>

1. connect to a jupyter server with an earlier version of the extension
2. kill that server
3. update vscode, now I'm in "remote" mode but without a server
4. start an interactive window, or open a notebook
5. can't find any python kernels - .NET interactive is selected in my case, and the IW is suggesting that I enter .NET code

Extension version: 2022.7.1001841019
VS Code version: Code - Insiders 1.69.0-insider (0b3574dcef8f35fec4ee4f83dc958c1f16ef6fce, 2022-07-01T05:17:04.343Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (16.39GB free)|
|Process Argv|--folder-uri file:///c%3A/src/vscode-jupyter --crash-reporter-id 1202dc88-403d-4ebc-8393-af3551a8bd5b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30496796
vsclangdf:30492506

```

</details>

**Comment by amunger** [comment]
selecting the kernel picker and selecting local kernels let's me select kernels, but the ipynb files that I opened during that time now persistently open with a .NET kernel

**Comment by rchiodo** [comment]
I thought we cached remote connections, but maybe I was too aggressive in removing them.

**Comment by greazer** [comment]
Not sure it's a regression. Just an assumption based on comments.

**Comment by amunger** [comment]
this has improved, where an option to connect to local kernels is shown, but an option to connect to another jupyter server should probably also be available

**Comment by DonJayamanne** [comment]
@amunger 
Closing this issue and creating a new one for the suggestion, as this is marked as a regression and leaving this open for more changes like suggestions would be confusing when tracking the progress of the regression and the original bug

**Comment by DonJayamanne** [comment]
One part of the issue was verified as fixed, and we ended up creating a new issue for the other part of the issue.
Hence marking this issue as verifed
