### ISSUE TITLE
There's no way to 'detach' from the current server anymore 

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10669]
Other than going through the kernel picker.

Should we put back the 'None' option on the server URI picker?

**Comment by greazer** [comment]
Perhaps we don't need to bother with this.

**Comment by YoraiLevi** [comment]
I am not sure if this is related. I found this when searching for a way to detach from my current jupyter notebook without closing it (working with remote ssh extension, it closes all user programs when it terminates)
I have a long running code in a jupyter notebook and it is rather annoying to keep vscode window open locally in order for it to finish computation.
It would be helpful if it was possible to attach and detach from the notebook

**Comment by DonJayamanne** [comment]
Such a feature is no longer necessary with the new kernel picker
