### ISSUE TITLE
Traceback does not render correctly from interactive window

### ISSUE THREAD

**Issue by Jacques-Peeters** [microsoft/vscode-jupyter#10663]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When running code into the interactive window from a .py file and a error is thrown, the traceback doesn't display correctly. 
When running the exact same code but within a .ipynb file, the traceback is correctly displayed. 

It makes debugging very difficult. See screenshot below. I tried to change Python version, extension, Ipython package, all without success. 

Note: I'm working from a [Remote - Containers. ](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers)

<img width="1258" alt="Screenshot 2022-07-01 at 10 47 06" src="https://user-images.githubusercontent.com/104154222/176860044-96fdd36e-4d05-44ba-8d6d-fee86dbf4aa6.png">
The exact same code, ran from .ipynb file on the left, .py file into the interactive window in the right. 

### VS Code Version

Version: 1.68.1 (Universal) Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630 Date: 2022-06-14T12:52:13.188Z (2 wks ago) Electron: 17.4.7 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Darwin arm64 21.5.0

### Jupyter Extension Version

v2022.5.1001601848

### Jupyter logs

```shell
info 8:32:56.373: Process Execution: > /usr/local/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2022.5.1001601848/pythonFiles/normalizeSelection.py
> /usr/local/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2022.5.1001601848/pythonFiles/normalizeSelection.py
info 8:32:56.428: Generated code for 2 = <ipython-input-2-2c32cc02cd77> with 295 lines
info 8:32:57.610: Cancel all remaining cells true || Error || undefined
info 8:32:57.610: Cancel pending cells
info 8:32:57.610: Cell 6 executed with state Error
```

### Language Extension Version (if applicable)

%% Python 3.8.13 (default, Jun 23 2022, 12:19:13)    Type 'copyright', 'credits' or 'license' for more information   IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.  

### Running Jupyter locally or remotely?

Remote

**Comment by amunger** [comment]
Can you try changing the error renderer to see if that helps?

![image](https://user-images.githubusercontent.com/2019016/176928576-394e001b-b6c3-4c6b-80fa-20abca976cc0.png)

**Comment by Jacques-Peeters** [comment]
Switching from `vscode.builtin-notebook-renderers` to `ms-toolsai.jupyter worked` 🎉 
![Screenshot 2022-07-04 at 14 35 38](https://user-images.githubusercontent.com/104154222/177156217-b432192b-9196-4326-bf91-9a107b959126.png)

Did I involuntary changed something? I see that nothing changed in my `settings.json` 

In other projects I don't see the same options (I think the same extensions are installed).

**Comment by DonJayamanne** [comment]
> Did I involuntary changed something? I see that nothing changed in my settings.json

Yes, at some point you may have changed this. Unfortunately it's not saved into your settings.
Changing the renderer can only be done by a user, and is only supported in notebooks that have more than one renderer.
If you don't see this in other projects, you probably don't have the same kind of output in a notebook or its not the same notebook.
