### ISSUE TITLE
Consider renaming "Connect to Your Own Jupyter Server"

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#10675]
Using the most recent Insiders bits from July 1st.

The kernel picker now shows an option: "Connect To Your Own Jupyter Server". This seems a bit odd to me. It might not be MY Jupyer server, just A Jupyter server. So consider something like "Use Kernel On Existing Jupyter Server", instead.

**Comment by rchiodo** [comment]
I think I'd rather wait for customer feedback. Or more than one opinion. We should discuss at standup.

**Comment by rchiodo** [comment]
Most of the other options say 'Connect' as the first word.

Maybe just 'Connect to a Remote Jupyter Server'?

**Comment by rchiodo** [comment]
Suggestions:
- Connect to External Jupyter Server 
- Connect to a Jupyter Server (+4)
- Connect to a Remote Jupyter Server
-
