### ISSUE TITLE
External application state - Refactor extension to be more in style of functional programming

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#10674]
_Context: I spoke about this idea with @rchiodo and @greazer . @greazer motivated me to make this issue, to at least ensure we would remember to have a conversation about it during standup._

Today, the `vscode-jupyter` extension is composed of a considerable amount of services that consist of statefull classes, each one tracking different behaviors of the extension. While some of the state stored in these classes is representative of user interactions, debugger behavior, network behavior and other interactions with external APIs, some of the state track features that are specific to the Jupiter Notebooks as a whole as well as the individual cells and outputs.

> Today:
> - Jupyter Notebooks have a specific API that is standard, independent of the `vscode-jupyter` extension.
> - `vscode-jupyter` has many services.
> - Service classes contain state that is sometimes tied to Jupyter Notebooks (whole or parts).
> - The state lives only in memory, independently of the Jupyter Notebook.

In functional programming, one way to keep the majority of the code stateless is to maintain the application state independent of the functions that use it, so that functions could receive and return a static version of the state. Stateless programming makes applications more predictable and easier to test. It might be interesting to move some of the service state out of the services into a centralized API (that is, both the cold-stored representation of the state and a centralized Jupyter-Notebook state manager in our extension).

> Potential future:
> - `vscode-jupyter` stores temporary state files (one per notebook).
> - The temporary state file has an API that either is a superset of the Jupyter Notebooks standard API, or that references / has pointers to sections of existing `.ipynb` files.
> - `vscode-jupyter` services could be stateless, or near stateless by interfacing with a centralized API that would deal with the update of the state file.

The new centralized state could contain many things, for example:

- The status of a debugging session.
- The status of the execution of a specific cell.
- Representations of the cell outputs (like output caches) that could not fit the existing `.ipynb` format.
- Custom IDs for any element within the standard structure of Jupyter Notebooks.

This would enable the Jupyter extension to grow in new directions, for example, the cold-stored state could be used for:

- Re-hydrating the state after re-opening VS Code.
- Re-hydrating the state after crashes.
- Crash reports.
- Resuming debugging in another device or in another version of VS Code.
- Better state control by allowing to lock certain sections of the state.
- Potential lazy loading of services and offloading of services.

Instead of a concrete proposal, this idea is a way for me to picture how the future would look. If some of this turns out to be representative of the future of our extension, we would begin to see issues or features related to this idea. Having a conversation about it will help us think in these terms. That is to say, please keep in mind the following considerations:

- **IT'S NOT URGENT:** This idea might not represent an imposing need today, but the `vscode-jupyter` project could, over time, face challenges that would be symptomatic of the necessity of the externalization of the service state.
- **COULD BE DONE INCREMENTALLY:** This idea could be implemented by parts. As soon as any service has the need to store its state in cold storage, the implementation of that solution could be thought to point towards a more universal service-state-manager for our extension.
- **MAY USE EXISTING CODE:** An external representation of the state of this application could both be done through a custom solution, or use existing tools that manage application state (as long as those tools satisfy the desired long-term features, which we would need to discuss).

During my conversations with @rchiodo and @greazer , both suggested existing software that reminded them of this idea:

- @rchiodo pointed to Redux https://redux.js.org
- @greazer pointed to IntelliTrace https://docs.microsoft.com/en-us/visualstudio/debugger/intellitrace?view=vs-2022

As always, any feedback appreciated 🙏

**Comment by DonJayamanne** [comment]
Closing as I don't think this will be necessary anymore.
