### ISSUE TITLE
Install Python shows up if in remote mode

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10670]
![image](https://user-images.githubusercontent.com/19672699/176972384-04141663-0a30-418b-bb6f-9b78cb8d6029.png)

This is the fault of my change and not testing after merging. I believe the logic for the 'Install Python' shows up if there are no local python kernels found. It should be changed to happen if no local interpreters found.

**Comment by IanMatthewHuff** [comment]
Related to "onlyOneTypeOfKernel" so closing.
