### ISSUE TITLE
failing connecting kernel for jupyter notebook

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode-jupyter#10681]
there is mu jupyter log

`error 11:28:17.852: Error in execution (get message for cell) c [Error]: Kernel Python 3.8.10 64-bit is not usable. Check the Jupyter output tab for more information. at _.createNewKernelSession (/home/ahmedsta/.vscode/extensions/ms-toolsai.jupyter-2022.6.1001631011/out/extension.node.js:2:492820) at _.connect (/home/ahmedsta/.vscode/extensions/ms-toolsai.jupyter-2022.6.1001631011/out/extension.node.js:2:491417) at u.startNew (/home/ahmedsta/.vscode/extensions/ms-toolsai.jupyter-2022.6.1001631011/out/extension.node.js:2:499802) at a (/home/ahmedsta/.vscode/extensions/ms-toolsai.jupyter-2022.6.1001631011/out/extension.node.js:2:440814) at w.createNotebookInstance (/home/ahmedsta/.vscode/extensions/ms-toolsai.jupyter-2022.6.1001631011/out/extension.node.js:2:440977) at w.createNotebook (/home/ahmedsta/.vscode/extensions/ms-toolsai.jupyter-2022.6.1001631011/out/extension.node.js:2:441982) { category: 'invalidkernel', kernelConnectionMetadata: { kind: 'startUsingPythonInterpreter', kernelSpec: { specFile: '/home/ahmedsta/.vscode/extensions/ms-toolsai.jupyter-2022.6.1001631011/temp/jupyter/kernels/python3810jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1/kernel.json', interpreterPath: '/bin/python3', isRegisteredByVSC: 'registeredByNewVersionOfExt', name: 'python3810jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1', argv: [Array], language: 'python', executable: 'python', display_name: 'Python 3.8.10 64-bit', metadata: [Object], env: {} }, interpreter: { id: '/bin/python3', sysPrefix: '/usr', envType: 'Global', envName: '', architecture: 3, sysVersion: '3.8.10 (default, Mar 15 2022, 12:22:08) \n[GCC 9.4.0]', version: [Object], displayName: 'Python 3.8.10 64-bit', detailedDisplayName: 'Python 3.8.10 64-bit', uri: [g] }, id: '.jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher' } }`

**Comment by DonJayamanne** [comment]
thanks for filling this issue okay could you.
* reload vscode
* try this again and provide all of the log output from the Jupyter output panel

**Comment by DonJayamanne** [comment]
@cpoptic 
looks like you are running into issues because the Python extension has failed to activate, see below logs
```message: "Activating extension 'ms-python.python' failed: command 'python.viewOutput' already exists."```
Please file an issue against the Python extension here https://github.com/microsoft/vscode-python to get this resolved.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
