### ISSUE TITLE
Change our "Install Python" command to use the Python contributed command

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#10696]

**Comment by IanMatthewHuff** [comment]
Validation.

Get a new VM that does not have python installed on it (Or remove it).
Install Jupyter + Python extension
Open a python notebook
In the kernel picker there should be an "Install Python" command at the bottom.
Run the command, instead of a popup it should open the python extension getting started page at the "Installing Python" section.

**Comment by andreamah** [comment]
I seem to still get the popup on prerelease jupyter: 
<img width="905" alt="image" src="https://user-images.githubusercontent.com/31675041/181637857-98ee9c56-e1fa-43e0-a223-b197ea6ee837.png">

**Comment by rchiodo** [comment]
This is actually expected behavior. It won't auto install for you, just bring you to where you install python from.
