### ISSUE TITLE
wrong kernel is selected for IW in web

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#10702]
repro steps
1. open insiders.code.dev, make sure you're not connected to a remote jupyter server
2. create an interactive window
3. conncect to a remote jupyter server

actual result:
The top item of the kernel picker is selected

expected
`Python 3` is selected, as is the case if you created another IW at this point

**Comment by DonJayamanne** [comment]
Woudln't this also apply to desktop with remote jupyter?

**Comment by amunger** [comment]
we don't open the IW without the python extension installed for desktop, but maybe if python wasn't on your machine

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/11967
