### ISSUE TITLE
Kernel issues with login shells on remote SSH

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#10707]
https://github.com/microsoft/vscode-jupyter/issues/9682#issuecomment-1167496842

On remote SSH vscode doesn't launch a remote login shell hence env variables are not as expected.
This works on local machines, hence users might expect the same behavior in remote as well.

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/microsoft/vscode-remote-release/issues/1671

**Comment by DonJayamanne** [comment]
Closing in favour of the upstream issue
