### ISSUE TITLE
Flaky intellisense test

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#10710]
![Screen Shot 2022-07-06 at 10 36 12](https://user-images.githubusercontent.com/1948812/177438635-ceed8030-ded0-4956-aea0-78043cb441fc.png)

**Comment by DonJayamanne** [comment]
This is definitely flaky, i've run into this a few times, no idea whats going on here.
Seems to be a problem with the language server itself.

**Comment by IanMatthewHuff** [comment]
Test is enabled and I've seen no failures for this recently, closing.
