### ISSUE TITLE
Notebook Getting Started Bug Tracking

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#10719]
Note: This is a temporary issue just for bug discussion / tracking. Should be closed after this iteration.

As of 7/7/2022 this is my current groupings of the Getting Started bugs.

Python Extension install / Jupyter Extension install
	•	[Don't show the "Notebooks might need to be restarted" prompt after Python Extension is installed (or at all?)](https://github.com/microsoft/vscode-jupyter/issues/10697)
	•	[Install kernels from the marketplace only lists Jupyter](https://github.com/microsoft/vscode-jupyter/issues/10377)
	•	[Extension dependency issues when building python dev containers](https://github.com/microsoft/vscode-jupyter/issues/6894)
	•	[Don't notify the user to reload after installing the extension](https://github.com/microsoft/vscode-jupyter/issues/6353)
	•	[Impossible to run any notebook without Python extension when RAW isn't supported](https://github.com/microsoft/vscode-jupyter/issues/5897)
Python / pip install
	•	[Change our "Install Python" command to use the Python contributed command](https://github.com/microsoft/vscode-jupyter/issues/10696) 
	•	[Install Python shows up if in remote mode](https://github.com/microsoft/vscode-jupyter/issues/10670) 
	•	[Selecting install from prompt when missing pip fails because pip is not available](https://github.com/microsoft/vscode-jupyter/issues/10400)
	•	[Zmq Not supported and requiring Python for Jupyter](https://github.com/microsoft/vscode-jupyter/issues/5141) (5897 dupe?)
IPyKernel Install
	•	[Consider adding a More Info button to the modal dialog prompt requiring users to install ipykernel ](https://github.com/microsoft/vscode-jupyter/issues/10658)
	•	[installing ipykernel looks successful after hitting permission denied](https://github.com/microsoft/vscode-jupyter/issues/10478) 
	•	[Change prompt text that requires users to upgrade ipykernel to a newer version](https://github.com/microsoft/vscode-jupyter/issues/10295)
	•	[Reword ipykernel installation message ](https://github.com/microsoft/vscode-jupyter/issues/9159)
	•	[Unclear why "Ipykernel setup required for this feature" is showing up for new setups and trying to run-by-line](https://github.com/microsoft/vscode-jupyter/issues/7761)
	•	[Identify kernels that have ipykernel installed to kernels picker.](https://github.com/microsoft/vscode-jupyter/issues/7230)
	•	[Version 2 of "I installed ipykernel 6, but I still can't use run-by-line"](https://github.com/microsoft/vscode-jupyter/issues/7128)
	•	[I installed ipykernel 6 to try run-by-line, but I don't want to have to restart the kernel.](https://github.com/microsoft/vscode-jupyter/issues/7127)
	•	[I misread the modal dialog about installing ipykernel 6. I thought it was telling me to install with pip.](https://github.com/microsoft/vscode-jupyter/issues/7125)
	•	[Option to change kernel sends me down a rabbit hole](https://github.com/microsoft/vscode-jupyter/issues/6892)
Performance
	•	[building of wheel taking a long time](https://github.com/microsoft/vscode-jupyter/issues/10620)
	•	[Mitigate slow kernel discovery (API adoption, placeholder kernels, measurements) ](https://github.com/microsoft/vscode-jupyter/issues/9628)
Initial Suggested Kernel
	•	[2.x python kernel suggested but no longer supported](https://github.com/microsoft/vscode-jupyter/issues/10619)
	•	[Automatically disconnect local conda kernel and switch to dummy kernel.](https://github.com/microsoft/vscode-jupyter/issues/10514) (Probably fixed)
	•	[Auto picked kernel after running 'Connect to Github' is .NET](https://github.com/microsoft/vscode-jupyter/issues/10591) (remote)
	•	[Allow a machine to configure the default Python interpreter version](https://github.com/microsoft/vscode-jupyter/issues/9997)
	•	[Preferred Python Notebook Kernel](https://github.com/microsoft/vscode-jupyter/issues/9615)
	•	[Losing selected kernel when installing python extension](https://github.com/microsoft/vscode-jupyter/issues/6891)
	•	[Jupyter notebooks not using Python in current path](https://github.com/microsoft/vscode-jupyter/issues/5998)
	•	[Show available kernels rather than languages in Create New Blank Notebook UI](https://github.com/microsoft/vscode-jupyter/issues/5155)
Notifications / Prompts
	•	[If Python is missing server auto starter tries to run and pops up the "Needs Python Extension" modal](https://github.com/microsoft/vscode-jupyter/issues/10615)
	•	[Wall of notifications](https://github.com/microsoft/vscode-jupyter/issues/6886)
	•	[Notification overload when installing ipykernel](https://github.com/microsoft/vscode-jupyter/issues/7907)
Remote
	•	[Remote jupyter server failures are not diagnosable](https://github.com/microsoft/vscode-jupyter/issues/10274)
	•	[ModuleNotFound errors on remote could indicate that files are not copied to the remote machine](https://github.com/microsoft/vscode-jupyter/issues/8644)
	•	[Consider treating Notebooks in remote repositories like they are in untrusted workspaces](https://github.com/microsoft/vscode-jupyter/issues/6949)
Jupyter Starting
	•	[Cannot resolve starting jupyter if active interpreter doesn't support jupyter](https://github.com/microsoft/vscode-jupyter/issues/9992)
	•	[Kernels using 32-bit Python environments installed via conda does not work](https://github.com/microsoft/vscode-jupyter/issues/9134)
	•	[Jupyter interpreter can be invalid and break things](https://github.com/microsoft/vscode-jupyter/issues/1110)
	•	[Ship our own Jupyter to eliminate configuration problems](https://github.com/microsoft/vscode-jupyter/issues/1131)
Environment setup / configuration
	•	[Investigate a method to create or suggest a virtual environment with ipykernel + needed packages for a given notebook](https://github.com/microsoft/vscode-jupyter/issues/9640)
	•	[Create a 'blessed' environment that has known modules installed](https://github.com/microsoft/vscode-jupyter/issues/9055)
	•	[Consider adding a blessed basic environment to install with the Jupyter extension](https://github.com/microsoft/vscode-jupyter/issues/7642)
Basic Initial Workflow (everything works, something very basic in work flow is confusing)
	•	[Set new notebook folder location](https://github.com/microsoft/vscode-jupyter/issues/5892)
Tutorials / Docs / Walkthroughs
	•	["Run by line" tutorial is hard to navigate](https://github.com/microsoft/vscode-jupyter/issues/8804)
	•	[Walkthrough text is not localized](https://github.com/microsoft/vscode-jupyter/issues/8801)
	•	['Select a kernel' walkthrough step button does nothing](https://github.com/microsoft/vscode-jupyter/issues/8800)
	•	[Jupyter Notebook Tutorial](https://github.com/microsoft/vscode-jupyter/issues/8029)
Aggregate / Grouping issues
	•	[Making it easy to get started with the Jupyter extension](https://github.com/microsoft/vscode-jupyter/issues/9336)
	•	[Proposal for proxy kernels](https://github.com/microsoft/vscode-jupyter/issues/9076) (as it's more of a broad work item)
	•	[Notebook getting started experience challenges/questions](https://github.com/microsoft/vscode-jupyter/issues/5936)
	•	[Improvements to getting started experience for DS](https://github.com/microsoft/vscode-jupyter/issues/1127)
Not "Getting Started" issues
	•	[If I open an ipynb and then select a kernel for it, opening a Python terminal should activate the same environment](https://github.com/microsoft/vscode-jupyter/issues/7478)

**Comment by karrtikr** [comment]
https://github.com/microsoft/vscode-jupyter/issues/10552 should probably be added here as well.

**Comment by IanMatthewHuff** [comment]
Closing meta issue.
