### ISSUE TITLE
People getting unwanted GitHub Actions Notifications

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#1073]
I'm keep getting this email notifications (4 emails so far):

![image](https://user-images.githubusercontent.com/33796896/98876257-e058df80-244b-11eb-83ee-1c9d35ffcc3c.png)

https://github.community/t/who-receives-notifications/17680

**Comment by IanMatthewHuff** [comment]
I believe this is resolved now by the action being turned off. Moving to validate.
