### ISSUE TITLE
Jupyter response slow after recent update

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#10736]
Issue Type: <b>Performance Issue</b>

When running code from `.py` files with <kbd>shift</kbd> + <kbd>enter</kbd>, 

1.  the interactive pane is very slow to first appear, in some cases over a minute;
1.  the `Jupyter: Interactive Window Mode` setting to `single` is ignored and a new Interactive pane is created for every block of code ran from a separate file;
1.  the code takes several whole seconds to copy over to the Interactive pane and begin executing, whereas it used to be nearly instant.

Extension version: 2022.6.1001902341
VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (2 x 2500)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.65GB free)|
|Process Argv|--crash-reporter-id 1e88d7ed-dfc2-42ed-b5d3-970568cb872e|
|Screen Reader|no|
|VM|0%|
</details>

<details>
<summary>Workspace Info</summary>

```
|  Window (CI_EMR_v_DSS.py - CLAE_code2 (Workspace) - Visual Studio Code)
|  Window (dataiku_dss-update.sh - dataiku_plugins (Workspace) - Visual Studio Code)
|    Folder (CLAE_git): 131 files
|      File types: py(43) sh(36) md(8) conf(7) properties(6) pyc(3) json(2)
|                  xlsx(2) gitignore(1) txt(1)
|      Conf files: settings.json(1)
|    Folder (MyNotes): 3169 files
|      File types: py(531) pp(212) ipynb(190) dat(163) sh(152) log(129)
|                  xml(84) md(70) json(66) rb(62)
|      Conf files: dockerfile(22) settings.json(5)
|    Folder (workspace): 9 files
|      File types: code-workspace(8)
|      Conf files:
|    Folder (_cluster): 90 files
|      File types: png(19) sh(12) jpg(12) json(9) css(5) py(3) crt(3) jar(3)
|                  pem(3) xml(1)
|      Conf files: settings.json(1)
|    Folder (plugins): 438 files
|      File types: json(111) py(64) wlock(22) txt(22) pyc(4) zip(3) md(3)
|                  pem(2) hyper(2) sh(1)
|      Conf files: settings.json(1) makefile(1)
|    Folder (MyNotes): 3169 files
|      File types: py(531) pp(212) ipynb(190) dat(163) sh(152) log(129)
|                  xml(84) md(70) json(66) rb(62)
|      Conf files: dockerfile(22) settings.json(5)
|    Folder (_cluster): 90 files
|      File types: png(19) sh(12) jpg(12) json(9) css(5) py(3) crt(3) jar(3)
|                  pem(3) xml(1)
|      Conf files: settings.json(1);
```
</details>

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549

```

</details>

**Comment by amunger** [comment]
that's odd, I'm not able to reproduce any of that behavior. Can you provide the Jupyter logs for us to investigate - you can run the command `Jupyter: Show Output` to get to them.

**Comment by amunger** [comment]
we still need the logs to be able to troubleshoot this - `Jupyter: Show Output`.
Please post logs here or a new issue if this is still occurring.
