### ISSUE TITLE
Test failing consistently (prompt to install ipykernel)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#10734]
Looking at the CI logs, this was fine this morning, even the last commit was green.
However most (if not all) PRs seems to be failing now for the same test.

![Screen Shot 2022-07-08 at 10 26 45](https://user-images.githubusercontent.com/1948812/177892723-2fbe1d60-9b38-4a59-8b66-51ff7b6acc2d.png)

**Comment by rchiodo** [comment]
Seems to still be failing even with the changes in VS code core.
