### ISSUE TITLE
Insiders build requires python

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1074]
Install just the jupyter extension
Open a notebook
You'll be told you have to install the python extension

![image](https://user-images.githubusercontent.com/19672699/98877778-1db27280-2436-11eb-9d67-1f48eb14d0e2.png)

First dialog is not expected. Second is.

First dialog is put up by something forcing interpreter search.

**Comment by DonJayamanne** [comment]
See here for similar suggestions no merging these two prompts https://github.com/microsoft/vscode-jupyter/issues/1092

**Comment by rchiodo** [comment]
Validated
