### ISSUE TITLE
Variable viewer is showing deleted variables

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#10740]
The Variable Viewer is showing information about variables that are no longer part of the notebooks.

## Environment data

-   VS Code version: Latest.
-   Jupyter Extension version (available under the Extensions sidebar): Latest.
-   Python Extension version (available under the Extensions sidebar): Latest.
-   OS (Windows | Mac | Linux distro) and version: All.
-   Python and/or Anaconda version: 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Jupyter server running: Local and Remote

## Expected behavior

Deleted variables should not appear in the variable viewer.

## Actual behaviour

Deleted variables are showing in the variable viewer.

<img width="538" alt="Screen Shot 2022-07-08 at 9 22 56 AM" src="https://user-images.githubusercontent.com/417016/178000995-1225447e-6071-4107-95b3-6016c67cc8cf.png">

## Steps to reproduce:

1. Make a new notebook with some variables.
2. Ensure it runs.
3. Open the variable viewer. Ensure you see the variables.
4. Delete some of the variables, then run again.
5. The deleted variables will be there.

**Comment by sadasant** [comment]
My guess is that this is because the kernel needs to be restarted. So, is this a feature, not a bug?

**Comment by DonJayamanne** [comment]
isn't this how a python works. not sure why we'd want to change how python works and not show the true state of the python process.

ie i don't think anything needs to be done here.

**Comment by sadasant** [comment]
Alright, understandable!
