### ISSUE TITLE
VS Code does not open exported HTML file when running a notebook via Azure ML setup

### ISSUE THREAD

**Issue by olguzzar** [microsoft/vscode-jupyter#10743]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Repro steps:

- Setup a notebook in Azure ML Studio
- In Azure ML Studio, click "Edit in VS Code"
- Once in VS Code, export the notebook as an HTML file
- Select the file save location in your azureuser folder
- Select "yes" when prompted "do you want to open the exported file?"

Expected behavior: VS Code opens the exported file

Actual behavior: VS Code doesn't seem to resolve the file location when stored in the Azure user folder, giving you this prompt:
![vscode remote](https://user-images.githubusercontent.com/95261576/178046395-fad21820-da41-448a-ada0-728cbc7a5a0b.jpg)

The HTML file gets added to the workspace, though, and you can open it from there

Full recording of the scenario is here: https://msit.microsoftstream.com/video/ae7b0840-98dc-bd6c-7484-f1ecfee3c9d9?st=1215

### VS Code Version

Version: 1.69.0 (user setup) Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9 Date: 2022-07-07T05:28:36.503Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Windows_NT x64 10.0.22000

### Jupyter Extension Version

v2022.6.1001902341

**Comment by rchiodo** [comment]
Not sure if this on the golden path. Azure ML would likely be required to reproduce this.
