### ISSUE TITLE
Restart & Interrupt kernel buttons are missing when using the Chinese Simplified Language Pack 中文没有重启内核

### ISSUE THREAD

**Issue by morning-start** [microsoft/vscode-jupyter#10752]
Issue Type: <b>Bug</b>

使用Chinese简体插件之后，notebook的restart就没了

Extension version: 2022.6.1001902341
VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.94GB (1.01GB free)|
|Process Argv|--crash-reporter-id cf0d668d-4329-46d7-829b-6dc58f8a1ba2 --crash-reporter-id cf0d668d-4329-46d7-829b-6dc58f8a1ba2|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549

```

</details>

**Comment by morning-start** [comment]
![image](https://user-images.githubusercontent.com/76601464/178138914-e600933c-0450-4165-8722-8814728a2e49.png)
![image](https://user-images.githubusercontent.com/76601464/178138930-a01060aa-9611-4308-b81f-2ab40c88bc67.png)
![image](https://user-images.githubusercontent.com/76601464/178138952-54958ba5-93bd-4063-82d2-9b26e9b970cf.png)

**Comment by DonJayamanne** [comment]
thanks for filling this issue
please could you upload a screenshot of the issue.

**Comment by kimbob13** [comment]
I have a same issue with him.
I guess it regards to CJK language pack since restart and interrupt button also disappears in Korean.
![en](https://user-images.githubusercontent.com/26755098/178180542-09e1d345-bcfb-425c-96a6-542712c43194.png)
![ko](https://user-images.githubusercontent.com/26755098/178180546-df3645c5-e9f3-48a1-a3d4-fee1ded24259.png)

**Comment by vrocker2048** [comment]
I also have the same issue. 
Since updating vscode and jupyter extension to the latest version, when I use the Chinese language pack, the restart and interrupt buttons on the global toolbar will disappear. 
When I uninstall the Chinese language pack, or downgrade vscode and jupyter extension, these problems will go away. Please check this problem, thanks!
<img width="831" alt="image" src="https://user-images.githubusercontent.com/24478928/178186048-eb1ad9f0-871e-4035-9e8f-dd1601cdadbd.png">

**Comment by enigmazack** [comment]
I met this problem since last auto update of vscode. Suffering for days, haven't realized that its a bug for language package.

**Comment by DonJayamanne** [comment]
I'm sorry you are running into this, we'll try to get this resolve asap.

**Comment by sadasant** [comment]
Hello @morning-start ! We just released a hotfix that re-enables those buttons that you reported missing. Please install `v2022.6.1101950301` and let us know how it goes! Thank you for using our extension. Your time and feedback are appreciated.

**Comment by morning-start** [comment]
@sadasant It is worked
![image](https://user-images.githubusercontent.com/76601464/178408913-d3afe71a-6da2-4b0e-b9f1-0136e89c826d.png)

**Comment by kimbob13** [comment]
It works in Korean, too. Thanks!

![ko_work](https://user-images.githubusercontent.com/26755098/178410443-9b4bafd7-fd3b-4f43-9f7c-df5fb87fb3cf.png)
