### ISSUE TITLE
Suggestions are doubled if pylanceHandlesNotebooks is true and Interactive is started

### ISSUE THREAD

**Issue by chmielcode** [microsoft/vscode-jupyter#10751]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Suggestions are doubled if pylanceHandlesNotebooks is true and Interactive is started. There are no duplicates before executing first cell in interactive window or when pylanceHandlesNotebooks is set to false.

### VS Code Version

Version: 1.69.0 (user setup) Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9 Date: 2022-07-07T05:28:36.503Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Windows_NT x64 10.0.19044

### Jupyter Extension Version

v2022.6.1001902341

### Coding Language and Runtime Version

Python v3.10.5

### Language Extension Version (if applicable)

Python v2022.10.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for reporting this issue, I can repro this at my end.

**Comment by amunger** [comment]
pylance issue: https://github.com/microsoft/pylance-release/issues/3027

**Comment by alkatar21** [comment]
Are there any information why the issue was closed?

**Comment by rchiodo** [comment]
Sorry. The pylance issue is tracking the problem. You could track it there.

**Comment by felixmaker** [comment]
I tried the prerelese version, it works well.
https://github.com/microsoft/vscode-jupyter/issues/11938#issuecomment-1306103766

**Comment by felixmaker** [comment]
Switch to the prerelease version. It works fine.
https://github.com/microsoft/vscode-jupyter/issues/11938#issuecomment-1306103766
