### ISSUE TITLE
Jupyter environment variables load only once ever per kernel.

### ISSUE THREAD

**Issue by tbenthompson** [microsoft/vscode-jupyter#10755]
### Applies To

- [x] Notebooks (.ipynb files)
- [x] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Once I run a notebook, the settings in the `.env` file become "stuck" across:
- restarting the kernel
- restarting VSCode entirely
- restarting my laptop entirely
- opening an entirely different notebook
- deleting and re-creating the conda environment with the same name

The only solution is to create a conda env/kernel with a new name at which point the `.env` file is reloaded. But, again, only once. 

It seems like there must be some kind of cache inside the extension?

Below, you can see two interactive windows that I loaded from two different kernels:
1. On the left, this is the output from a kernel that I loaded before changing the `.env` file. This output is incorrect. The output here is after a full restart of VSCode.
2. On the right, this is the output from a kernel that I loaded after changing the `.env` file. This output is correct.  

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/4241811/178165940-79551127-6e13-479e-a25f-894472e6012f.png">

### VS Code Version

Version: 1.69.0 (Universal) Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9 Date: 2022-07-07T05:28:41.511Z (3 days ago) Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Darwin arm64 21.5.0

### Jupyter Extension Version

v2022.6.1001902341

### Coding Language and Runtime Version

Python 3.10.5

### Language Extension Version (if applicable)

v2022.10.0

### Anaconda Version (if applicable)

4.13.0

**Comment by DonJayamanne** [comment]
Thanks for filing this extension, i'll have a look at this soon.
Please note, we've identified a few issues related to the environment variables being loaded in kernels & plan on addressing them for the next release
See here https://github.com/microsoft/vscode-jupyter/issues/10359

**Comment by tbenthompson** [comment]
Oh, haha, it's great to hear that there are known `.env` problems. I thought I was going crazy with this strange bug.

**Comment by DonJayamanne** [comment]
@tbenthompson Please could you :
* Try this again
* Provide all of the output from the `Jupyter` output panel (you can get to that using the command `Jupyter: Show Output`)

**Comment by tbenthompson** [comment]
Sure, here: https://gist.github.com/tbenthompson/63b3697b8be29d3ef18a5d24771b5441
Thanks!

**Comment by DonJayamanne** [comment]
Should be fixed with this PR https://github.com/microsoft/vscode-jupyter/pull/10843
Please could you install the latet pre-release version of the Jupyter extension and try this again (in vscode insiders) & let us know.
If it still persists, please feel free to reopen this issue, or I can do that.
