### ISSUE TITLE
VSC fails to connect to (any) python kernel.

### ISSUE THREAD

**Issue by thistlillo** [microsoft/vscode-jupyter#10757]
After the upgrade to the latest VSC version on Linux Ubuntu 20.04 I **cannot run any** jupyter notebook. When I run any cell, using any environment (that used to work till the previous version), VSC seems to fail connecting to the python kernel, a dialog shows up and says:
```
Connecting to kernel: base (Python 3.9.5): Activating Python Environment 'Python 3.9.5 ('base')'
```
It never disappears.

## Environment data

-   VS Code version:
```
Version: 1.69.0
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T08:29:47.439Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.13.0-52-generic
```

-   Jupyter Extension version (available under the Extensions sidebar):
```
v2022.6.1001902341
```
-   Python Extension version (available under the Extensions sidebar):
```
v2022.10.0
```
-   OS (Windows | Mac | Linux distro) and version:
```
Linux Ubuntu 20.04
```
-   Python and/or Anaconda version:
```
conda 4.11.0
```

-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...):
```
conda
```
-   Jupyter server running: Local | Remote | N/A
```
local
```

## Expected behaviour

Cell is run.

## Actual behaviour

Cell is never run, for every conda environment and kernel I can select, I read:
```
Connecting to kernel: base (Python 3.9.5): Activating Python Environment 'Python 3.9.5 ('base')'
```

## Steps to reproduce:
In my case it is enough to open any jupyter notebook, select any environemnt and run any cell.

**Comment by DonJayamanne** [comment]
thanks for filling this issue.
please could you upload all of the the output from the `Jupyrer` output panel.
user the command `Jupyter: Show Output` to get to that

**Comment by amitbha** [comment]
maybe because Jupyter extension is loaded before the Python extension is ready.
I reload the jupyter extension, it works

**Comment by thistlillo** [comment]
Actually, a mess came out. After some reload/restart/enable/disable/install ipykernel via vsc dialog,etc. conda (that had not been updated) detected a package conflict. It started trying to resolve it, but after a couple of hours "resolving conflict" I stopped and removed everything. I have yet to start the reinstallation.

**Comment by DonJayamanne** [comment]
@thistlillo Please let me know when you have something working or if you have the logs.

**Comment by thistlillo** [comment]
I think there is something wrong with my installation. I work on a remote machine using the Kubernetes extension and run jupyter notebooks remotely. Now, every once in a while, after I reconnect to the remote machine, jupyter notebooks do not run any more because VSC asks me to install kernels from the marketplace. With previous version I got this request only once after - may be - upgrading VSC, not it happens very often.

When this happens:
 - if I am using the release version of the Jupyter extension, I need to switch to the pre-release version;
 - when, after a while, this error occurs with the pre-release version, I need to switch to the release version.

**Comment by DonJayamanne** [comment]
@thistlillo I'm sorry you are running into this issue, I'd like to get you unblocked from this issue.
As mentioned earlier , please could you provide all of the output from the `Jupyter` output panel, without this its very difficult to diagnose the issue.
https://github.com/microsoft/vscode-jupyter/issues/10757#issuecomment-1180198093

**Comment by thistlillo** [comment]
Thank you. I switched back to the release version, but the problem did not occur. Next time I have this problem (that appears random to me), I will post here the panel output.

**Comment by thistlillo** [comment]
Ok, so now I have the same problem: VSC asks me to install kernels from the marketplace.
I am using Jupyter extension on a remote machine running within a Kubernetes cluster. May be - I will make a test tomorrow - this happens when I switch local machines. On my laptop I have the latest VSC, on my work PC the previous release. May be this is the reason of this mess.

**Comment by thistlillo** [comment]
Yes, I confirm. Each time I switch between my linux PC and windows laptop I need to switch, respectively, to the pre-release/release version of the Jupyter extension. However, on the notebook (latest VSC, release version of Jupyter ext) I get the error "Could not find renderer", that I am able to solve with a random sequence of operation on the extensions.

**Comment by DonJayamanne** [comment]
@thistlillo have you managed to get the logs as per the request here https://github.com/microsoft/vscode-jupyter/issues/10757#issuecomment-1193073360

**Comment by thistlillo** [comment]
When I had this problem the `output` panel stayed empty. Now I am always working on the same PC so I am not experience that issue. I will start working again on two PCs from September.

I am using the extension to run notebooks on a linux pod on a remote kubernetes pod. The installation is very fragile. For, this morning, I had a cell running that I was not able to interrupt. If I open a new notebook the page stays empty. The output panel is again empty.

**Comment by DonJayamanne** [comment]
> but the page stays empty: it is not even able to load the file. 

Looks like some perf issue.
* Are you connecting to the remote machine using remote SSH.
* Can you confirm you are running into these issues only on the remote machine, this way we can isolate the issue as being related to running VS Code on remote machines.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Comment by Liincc** [comment]
> maybe because Jupyter extension is loaded before the Python extension is ready. I reload the jupyter extension, it works
> 
> 1. disable jupyter extension
> 2. restart vscode
> 3. open the .ipynb file
> 4. enable jupyter extension
> 5. run all

This worked for me!

**Comment by chesselingfm** [comment]
Had the same issue. "pip install --upgrade --force-reinstall ipykernel" resolved the problem

**Comment by FasilGibdaw** [comment]
> > maybe because Jupyter extension is loaded before the Python extension is ready. I reload the jupyter extension, it works
> > 
> > 1. disable jupyter extension
> > 2. restart vscode
> > 3. open the .ipynb file
> > 4. enable jupyter extension
> > 5. run all
> 
> This worked for me!

I am running Jupyter server remotely and I have to do this disabling and enabling all the time to make it work.  
`Version: 1.78.0 (Universal)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:11:00.813Z (1 day ago)
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: Yes`

Is there any setup/trick I should consider to avoid this
