### ISSUE TITLE
support configurable start port instead of a magic number 9000

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#10765]
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/10761

<div type='discussions-op-text'>

<sup>Originally posted by **ladyrick** July 11, 2022</sup>
`KernelLauncher.computeStartPort` support different start port instead of a magic number `9000`:
https://github.dev/microsoft/vscode-jupyter/blob/be3667521cf217753b343c7483c128b34dd5d213/src/kernels/raw/launcher/kernelLauncher.node.ts#L99

In my case, I need port 9000-10000 to be reserved. These ports may be not used now but may be used in the future. Now jupyter uses 9000 as start port. It's very likely to occupy a port in 9000-10000 and later my other application would failed because of "port is already in use".</div>

**Comment by rchiodo** [comment]
Should be relatively simple to add a setting with it defaulting to 9000.

**Comment by RafalSkolasinski** [comment]
Is there any way to configure this currently? It often clashes with my other dev services I work on.

**Comment by DonJayamanne** [comment]
@RafalSkolasinski unfortunately no. If at all possible, please feel free to submit a PR.

**Comment by DonJayamanne** [comment]
This issue has been open for a while and there haven't been any PRs even though its been marked as `good first issue`

**Comment by CarlosDomingues** [comment]
Could this issue be reopened? I'd like to give it a try.
