### ISSUE TITLE
Reducing Spacing in Python Output in VS Code

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode-jupyter#10777]
The output of a pandas dataframe of 20 lines takes a full page because of very high spacing as depicted below: enter image description here

![image](https://user-images.githubusercontent.com/100815370/178390683-c7ff633e-121e-4e4c-a194-d55c876063c9.png)

Can this be changed in VS code settings or in some python settings?

**Comment by rchiodo** [comment]
Thanks for the issue. This doesn't repro for me:

![image](https://user-images.githubusercontent.com/19672699/178543593-c9004bc5-5313-49c6-879a-05a531af0d5a.png)

My guess is that you have something in your kernel that is interfering with printing. Something that's adding the extra output lines. 

What does this show?

```
display(df.head(20))
```

**Comment by amunger** [comment]
not enough info, closing for now
