### ISSUE TITLE
keyboard interrupt keymap

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10779]
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/10767

<div type='discussions-op-text'>

<sup>Originally posted by **Guseyn013** July 11, 2022</sup>
In jupyter notebook there is a keyboard shortcut to interrupt kernel by pressing "I" button twice in command mode. Adding that feature to the VS Code extension would be very useful.</div>

**Comment by IanMatthewHuff** [comment]
@rebornix This would be added in our keymapping file I assume and is Jupyter specific, so assigning myself.

**Comment by seeM** [comment]
There's a PR for this: https://github.com/microsoft/vscode-jupyter-keymap/pull/10

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
