### ISSUE TITLE
Support for Pyspark interactive

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1078]
Create an extensibility point similar to this:

```typescript

interface IKernelSpec {
    // Fields of a jupyter kernelspec.json
    // Maybe live id for an already running kernel?
}

interface IKernelProvider {
     getKernels(): Promise<IKernelSpec[]> // This is implicitly local. Maybe it needs something to say that?
}

interface IInteractiveWindow {
    executeCode(code: string, file: Uri | undefined = undefined, line: number = 0, silent: boolean = false);
    readonly kernel: IKernelSpec;
}

interface IPythonExtensionApi {
    registerKernelProvider(provider: IKernelProvider) : Disposable;
    openInteractiveWindow(kernelSpec: IKernelSpec, remoteUri?: string, bearerToken?: string): Promise<IInteractiveWindow>
}
```

This would be used to
- Let an extension register its own set of kernels (works around Pyspark having to set the Jupyter interpreter to get their kernels listed)
- Let an extension open an interactive window connected to a specific kernel and a specific remote URI (Pyspark needs this in order to run their code)
- Let an extension send code to this interactive window (This would likely be useful for other language extensions)
- Let an extension be able to tell what kernel is currently picked in an interactive window (Pyspark needs this to determine if an interactive window still has their kernel enabled)

**Comment by DonJayamanne** [comment]
Suggestions:
* We might want to expose an API so other languages can provide the cell ranges
* We might want to expose an API so other languages can provide the details of code blocks (e.g when hitting ctrl+enter, then where is the next line)
* commenting/converting code blocks to comments

Such an api is sufficient for https://github.com/microsoft/vscode-jupyter/issues/273
This allows us to have a:
* Unique command set for sending lines/codeblocks/cells to interactive window for all languages
* Converting cells to markdown & vice versa will work for all languages
* Majority of the commands will just work.
Else other languages will need to reimplement the same commands/features (lot more work) & it will no longer be consistent.

**Comment by greazer** [comment]
@zesluo, FYI, we recently fixed issue #411 to re-enable picking a kernel in the interactive window.

**Comment by zesluo** [comment]
Thank you! I will try it then

**Comment by zesluo** [comment]
![image](https://user-images.githubusercontent.com/46309533/100195935-0776dd00-2f33-11eb-9876-30d3f6fea62e.png)
we just found that we cannot have the place to change kernel even with previous version of ms-python. And we don't have any code changes. any ideas about it? Thanks in advance!

**Comment by DonJayamanne** [comment]
Please could you ensure you have the latest version of VSCode and both extensions.
If it didn't work, please could you provide the logs for the  `console` window (like likes an issue in VSCode, I know we had an issue and it was fixed).

> with previous version of ms-python

Please install latest version. A change in new version of VSCode broke the old version.

**Comment by zesluo** [comment]
Hello @DonJayamanne ,

Thanks for your reply! We notice some changes in the new view version.
1. it needs to install Jupyter extension and ms-python together at same time.
2. By using the command : 
![image](https://user-images.githubusercontent.com/46309533/100309556-22565980-2fe6-11eb-9ded-6885eefcf691.png), it can now get the interactive window. Thanks for this support!
The problem is: when we try to change the kernel, it cannot succeed. The logs are attached. Please feel free to let me know if more information is needed. Thanks!
[1126errorlogs.log](https://github.com/microsoft/vscode-jupyter/files/5600539/1126errorlogs.log)



![image](https://user-images.githubusercontent.com/46309533/100309394-be339580-2fe5-11eb-8e2d-90e6051edb49.png)
![image](https://user-images.githubusercontent.com/46309533/100309499-02269a80-2fe6-11eb-98a2-18b2b63d9eae.png)

**Comment by zesluo** [comment]
@DonJayamanne, @rchiodo , Feel free to let me know if more information is needed. Thanks^_^

**Comment by DonJayamanne** [comment]
> The problem is: when we try to change the kernel, it cannot succeed. The logs are attached. Please feel free to let me know if more information is needed. Thanks!


@zesluo please could you file a separate issue for the kernel not starting up.

**Comment by zesluo** [comment]
Sure! Here it is ,https://github.com/microsoft/vscode-jupyter/issues/4055. Thanks

**Comment by DavidKutu** [comment]
@zesluo feel free to reopen this or create a new issue if its not fixed.
