### ISSUE TITLE
Show matplotlib figures during debug in visual studio code (using ssh conection)

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode-jupyter#10792]
I am working with visual studio code (python) using ssh to access a remote server (where the code is located). I am able to write code, run and debug without any problem. However I am not able to generate matplotlib figures during debug in the same way as i can do it without the ssh connection.

I've tried to follow several suggestions from internet and other post here but none of them is fully working.

I've tried the option of " Jupiter> Debug current file in interactive window " but it does not work. I am not sure why, but the debug in the interactive window is not responding and i can not work during debug.

I've tried python debug and the only matplotlib backend that works is (matplotlib.use("WebAgg"). However for this backend it only works with one figure and the debug is block after the plot.

I have also tried to use X.Org (in my case xquartz over mac) but the figures are really slow and it is not useful.

Any idea on how to plot figures during debug in the same way as in local development?

Thanks!

**Comment by rchiodo** [comment]
Thanks for the issue. 

One way to do this is to do the 'Debug your current file in the interactive window'. 

There's a bunch of caveats though.

1) You need to have ipykernel installed into the python environment you're using. If you run that command it should have asked you to do so. 
2) It's likely easier to use if you put cell markers around pieces of code `# %%`. This would also allow you to prerun bits of your script before you need to debug the part that's causing problems. This is what it looks like when you do that:

![image](https://user-images.githubusercontent.com/19672699/178788777-35acc8ac-cec5-4df5-b1e4-c9d4eb45761f.png)

3) When debugging in the interactive window, your code in your script is running as an IPython cell. If you split it up, it might be multiple cells or it could be one large cell (for the whole file). 
4) As you step, the cell execution is moved forward one line at a time. However the execution is paused in between steps. This means anything you type in the interactive window won't be executed. Instead you have to run extra code in the 'debugger console'. Shown below:
![debugConsole](https://user-images.githubusercontent.com/19672699/178789774-02ba4485-f909-4bbe-bfa0-3db37c505742.gif)

5) This debugger console is where you can run normal matplotlib commands. 

For more information see this issue:
https://github.com/microsoft/vscode-jupyter/issues/1278
