### ISSUE TITLE
Support vega

### ISSUE THREAD

**Issue by PaleNeutron** [microsoft/vscode-jupyter#10812]
I mean this package https://github.com/vega/ipyvega/ which is used by `altair` to render plot in offline mode.

The code below won't show any thing in vscode but works well in notbook

```
from vega import Vega

Vega({
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "width": 400,
  "height": 200,
  "padding": 5,

  "data": [
    {
      "name": "table",
      "values": [
        {"category": "A", "amount": 28},
        {"category": "B", "amount": 55},
        {"category": "C", "amount": 43},
        {"category": "D", "amount": 91},
        {"category": "E", "amount": 81},
        {"category": "F", "amount": 53},
        {"category": "G", "amount": 19},
        {"category": "H", "amount": 87}
      ]
    }
  ],

  "signals": [
    {
      "name": "tooltip",
      "value": {},
      "on": [
        {"events": "rect:mouseover", "update": "datum"},
        {"events": "rect:mouseout",  "update": "{}"}
      ]
    }
  ],

  "scales": [
    {
      "name": "xscale",
      "type": "band",
      "domain": {"data": "table", "field": "category"},
      "range": "width",
      "padding": 0.05,
      "round": True
    },
    {
      "name": "yscale",
      "domain": {"data": "table", "field": "amount"},
      "nice": True,
      "range": "height"
    }
  ],

  "axes": [
    { "orient": "bottom", "scale": "xscale" },
    { "orient": "left", "scale": "yscale" }
  ],

  "marks": [
    {
      "type": "rect",
      "from": {"data":"table"},
      "encode": {
        "enter": {
          "x": {"scale": "xscale", "field": "category"},
          "width": {"scale": "xscale", "band": 1},
          "y": {"scale": "yscale", "field": "amount"},
          "y2": {"scale": "yscale", "value": 0}
        },
        "update": {
          "fill": {"value": "steelblue"}
        },
        "hover": {
          "fill": {"value": "red"}
        }
      }
    },
    {
      "type": "text",
      "encode": {
        "enter": {
          "align": {"value": "center"},
          "baseline": {"value": "bottom"},
          "fill": {"value": "#333"}
        },
        "update": {
          "x": {"scale": "xscale", "signal": "tooltip.category", "band": 0.5},
          "y": {"scale": "yscale", "signal": "tooltip.amount", "offset": -2},
          "text": {"signal": "tooltip.amount"},
          "fillOpacity": [
            {"test": "datum === tooltip", "value": 0},
            {"value": 1}
          ]
        }
      }
    }
  ]
})
```

**Comment by DonJayamanne** [comment]
We need to register the main entry point of widgets with requirejs.

**Comment by rchiodo** [comment]
We could register the scripts in the renderer so that they load one notebook open.

**Comment by DonJayamanne** [comment]
**Summary of the problems:**
* The widget scripts are registered only when we render ipywidgets (however vega is a regular js)
 Hence we need to register the scripts for all outputs
* The baseUrl is setup in the webview where ipywidgets are rendered, however regular js is rendered in a different webview. Either we have a custom renderer for regular js/html mimetypes, or we update core to render js in the same webview as other outputs.
* The first two will probably be sufficient for fixing the rendering of the widget after execution, however if the user opens a regular notebook then things will not work as the renderer will load first and the extension host will still be busy fetching the scripts. 
    * We need to either wait for the widget scripts to be loaded, 
    * or pre-load the widget scripts in some way (e.g. via some renderer extension list plotly is included in the renderer extensions, again the path will have to be accessible via `<require config baseUrl>/nbextensions/jupyter-vega`, meaning the renderers will have to have a way to register some scripts before loading its own scripts.

**Comment by DonJayamanne** [comment]
**Suggestion for updating the base url**
* We can add custom js code into the html/js outputs that update the `baseUrl` of requirejs in the webview
**TODO:**
* Check if requirejs is available in built in renderers
* This feels hackish, 
    * hence check if its possible to have these js/html loaded in the same webview as widgets
    * should we create a custom renderer for js/html outputs (discuss with Matt)
* Even if this is done, how will this work when re-loading the same notebook
Probably best discussed with Matt as this deals with webviews and loading of custom scripts, and the like.

**Comment by DonJayamanne** [comment]
There haven't been enough upvotes on this issue, hece we're closing this for now.
If this is requried, please feel free to re-open or create a new issue and upvote that
