### ISSUE TITLE
run current cell commands not working at all after updating to 2020.11.0

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#1081]
```
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
extension: 2020.11.0 (11 November 2020) v2020.11.358366026
```

I'm getting the following error when using my shortcut to run a current cell
```
command 'python.datascience.runcurrentcell' not found
```

I also tried to use right click menu
![image](https://user-images.githubusercontent.com/33796896/98881312-b0afd480-2457-11eb-8d20-994305f9d238.png)
It didn't work either

And there is no any run cell commands at all:
![image](https://user-images.githubusercontent.com/33796896/98881251-8fe77f00-2457-11eb-89ca-97676534331b.png)

I had to downgrade to `v2020.10.332292344`, version before that won't work either.

**Comment by StevenLi-DS** [comment]
@joyceerhl What is this `vscode-jupyter`? Anywhere I can see an explanation for it? How do I launch the interactive window now instead of a jupyter notebook UI.

**Comment by rchiodo** [comment]
All of the data science code in the python extension has moved to a new extension (which is still downloaded with the python extension).

You can read about it here:
https://devblogs.microsoft.com/python/introducing-the-jupyter-extension-for-vs-code/

Any shortcuts you had for 'python.datascience' commands should be changed to 'jupyter.' commands instead.

**Comment by rchiodo** [comment]
@StevenLi-DS you're showing the run current cell in the right click context menu. Are you saying it has no effect?

**Comment by greazer** [comment]
Dupe of #1089

**Comment by StevenLi-DS** [comment]
@greazer @rchiodo  could you please reopen this and I don't think it's a dup and I find that run current cell is actually not working at all but only run all cells under `2020.11.0 (11 November 2020)`

![demo](https://user-images.githubusercontent.com/33796896/99011671-a30f5300-251a-11eb-87c9-b30e9461abc3.gif)

**Comment by StevenLi-DS** [comment]
It might have something to do with `jupyter.enableCellCodeLens` I set it to `true` and then back to `false` and it's working.

**Comment by rchiodo** [comment]
Hmm weird. Something about the setting being off may have broken us.

**Comment by DonJayamanne** [comment]
@Mrfence97 @StevenLi-DS @daeh

I am unable to repro this at my end.
Please could you confirm the issue persists.

If it still repros in the latest version, then please could you try the following:
* Enable `debug` logging in the Jupyter extension
	* Go into settings `Jupyter->logging` & select `debug`
* Try to run a cell using the command palette
	* Please do not use the keyboard shortcuts
	* Please select the command from the command palette or right click & select `Run Current Cell`
* If you can replicate the issue
	* Copy the contents of the `Jupyter` output panel (`Jupyter: Show Output`)
	* Paste the contents into this issue.

**Comment by StevenLi-DS** [comment]
@DonJayamanne I have no issue with it anymore under `v2020.11.358541065` Thanks.
