### ISSUE TITLE
Run By Line behaves differently when cell starts with comments/empty lines

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-jupyter#10828]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When executing Run By Line on a cell, if the cell starts with code, the function behaves as expected. If the cell starts with a blank line or a comment, the "Run Next Line" button will stay on the first line the first time it is clicked instead of moving to the next line.

https://user-images.githubusercontent.com/686963/179250394-cb59a7cd-ecd3-4c06-bcec-9bd6d026d6c9.mp4

### VS Code Version

1.70.0-insider

### Jupyter Extension Version

v2022.7.1001981020

### Jupyter logs

https://gist.github.com/burkeholland/2fe372f24df124dc17490e5a8e0373c8

### Coding Language and Runtime Version

Python 3.9.13

### Language Extension Version (if applicable)

v2022.7.1001981020

### Anaconda Version (if applicable)

MinConda 4.13.0

**Comment by rchiodo** [comment]
I don't repro this issue. @burkeholland my guess is your version of IPython is the one with the bug that causes debug stepping not to work.

Can you run this cell and report the results:

```
import IPython
print(IPython.__version__)
import ipykernel
print(ipykernel.__version__)
```

**Comment by greazer** [comment]
We think that this has been fixed already.

**Comment by amunger** [comment]
@burkeholland - are you able to provide the package versions that Rich requested?

**Comment by amunger** [comment]
not enough info, closing for now
