### ISSUE TITLE
Kernels should be associated per notebook instead of being global.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10834]
If I pick connect to remote, then I get a list of remote kernels.

On the next notebook, I'm in remote mode. 

If I switch to local, then go back to the first notebook, it's also in local mode now. 

Seems like the 'local' vs 'remote' state should be per notebook, not global.

**Comment by greazer** [comment]
Right. Yeah, this isn't just about local vs remote. It gets really confusing and potentially data-destructive if the user tries to connect to more than one remote.

**Comment by amunger** [comment]
applies to experiment `"jupyter.showOnlyOneTypeOfKernel": true`

**Comment by IanMatthewHuff** [comment]
Closing as this is covered by the new picker experiment. Still needs to roll out fully, but will be covered by other work items.
