### ISSUE TITLE
Kernel architecture review and polish

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#10832]
This issue covers the architecture review and polish @DonJayamanne and I are working on. The main goals of this task are

* Finalize how the APIs from `src/kernels` are being used by the core system (`notebooks`, `interactive-window` etc) and 3rd party extensions. There will be restriction and clear separation between internal and external use of the kernel interfaces.
* Internal architecture review and polish of `src/kernels` component. The kernel component will stay minimal and limited responsibilities without worrying about business logics of how kernels are being used (i.e., how to read variables, how to install dependencies into the kernels, etc)

Here is a list of tasks we will tackle:

- [x] Strict IKernel with notebook document linked in core
  - https://github.com/microsoft/vscode-jupyter/pull/10817
  - Internal system always create `IKernel` with `NotebookDocument`, it's 1-to-1 mapping.
  - 3rd party can create kernels from `Uri` instead of `NotebookDocument`
- [x] Conditional notebook controller for cell execution https://github.com/microsoft/vscode-jupyter/pull/10884 
  - 3rd party can create kernels, which don't require a VS Code `NotebookController` to be created 
- [x] Remove explicit knowledge of [interactive window](https://github.com/microsoft/vscode-jupyter/blob/main/src/kernels/kernel.base.ts#L608) from `IKernel`
  - https://github.com/microsoft/vscode-jupyter/pull/10853
  - Both Interactive Window and Debugging feature require special initialization after jupyter session is started. `StartupCode` can be registered from IW and Debugging other than embedding the logic into `IKernel`
  - The fix would be similar to how we add `@multiInject(ITracebackFormatter)`
- [x] Debugging and Debug Variable can probably be moved out https://github.com/microsoft/vscode-jupyter/pull/10870
  - Debugging and debug variable provider are used by notebook and interactive window so they probably don't need to live in `kernels` at all.
- [x] 🏃 `KernelFinder` and `KernelProvider` https://github.com/microsoft/vscode-jupyter/issues/11153
- [x] Review misplaced internal components 
  - [x] ipywidgets https://github.com/microsoft/vscode-jupyter/pull/10903
  - [x] port
```[tasklist]

**Comment by rebornix** [comment]
A gist of our discussion of how the kernel detection and launching works currently

<img width="1604" alt="image" src="https://user-images.githubusercontent.com/876920/179894686-5f61b1a7-bb1d-42ba-bebe-f4fa874e3c34.png">

**Comment by rebornix** [comment]
We have polished and narrowed down the API we expose to the core and 3rd party extensions. The core currently only needs to use `IKernelFinder`, `IKernelProvider`, and `IKernel`. The core can always get a `IKernel` which is attached to a `NotebookDocument` and `NotebookController` while 3rd party extensions can request for _headless_ kernels but those kernels won't be visible to the core system.

In August, we would look into what we can do to improve `IKernelFinder` and see if we can make it transparent to other components or make it easier to use. Along with that we would have telemetry ready to give better insights into how each kernel type (raw, pyenv, remote) works in overall right now.

**Comment by DonJayamanne** [comment]
Here's my proposal (from my private project)
```typescript
export type KernelSpecConnectionInfo = BaseKernelConnectionInfo & {
    resolve: (resource: Uri | undefined) => Promise<KernelSpec>;
};
export type KernelFactoryConnectionInfo = BaseKernelConnectionInfo & {
    makeSettings(options?: Partial<ServerConnection.ISettings>): ServerConnection.ISettings;
}

export interface KernelRegistry {
    registerKernel(connection: KernelSpecConnectionInfo | KernelFactoryConnectionInfo): Disposable;
}
```

I don't think we need `onDidChangeKernelnfo`

**Comment by rebornix** [comment]
The only task left is simplying kernel finder, which is now tracked separately in https://github.com/microsoft/vscode-jupyter/issues/11153.

**Comment by DonJayamanne** [comment]
Closing this issue for now, as we have other issues to track this work
