### ISSUE TITLE
New Remote UI: Why after connecting to a remote Jupyter Server does the kernel picker say "Connect to *Another* Jupyter Server"?

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#10837]
<img width="235" alt="image" src="https://user-images.githubusercontent.com/11685408/179325115-525488b2-141e-4e55-aacd-cf8faff3152b.png">

I think the idea here was to try to let the user know that they're already connected to a remote server, and this will allow them to connect to a different one. But it's not clear.

To me, it sounds like I could actually connect to another server at the very same time I'm connected to the current one. Of course, this would be necessary if we fix #10834. 

But no matter what, I don't think it's confusing to just leave the command named simply. "Connect to Jupyter Server". This doesn't seem confusing.

**Comment by IanMatthewHuff** [comment]
Closed due to onlyOneTypeOfKernel
