### ISSUE TITLE
Spell checker support

### ISSUE THREAD

**Issue by wnhfyang** [microsoft/vscode-jupyter#1084]
Currently the Notebook Editor does not support spell checker extensions (I have tried "Code Spell Checker" and "SpellChecker", and I have also tried the Insider version of the extension). As a non-native speaker, a functional spell check is very useful for me. I hope that at least for the markdown cell words can be checked. Any solutions or suggestions are welcome. (It is a pity that editing inside a browser started by JupyterLab also does not support spell checking.)

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
This should work in the preview notebook editor, as this is standard (supporting vscode extensions) functionality of native notebooks.
Closing this issue as this is solved with the native notebook.
For more information on native notebooks, please see here https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/
