### ISSUE TITLE
interactive plot not working with vscode Jupyter

### ISSUE THREAD

**Issue by kemal-nl** [microsoft/vscode-jupyter#10849]
Plot is not shown when presentation type is _Jupyter IPyWidget renderer - application/vnd.jupyter.widget-view+json_

Switching to presentation type _image/png_ it does show up. Issue occurs intermittently. I tried in Jupyter Notebook (non-VSCode), that one renders properly.

I used:
`%matplotlib widget`

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
