### ISSUE TITLE
Creating a new conda environment does not make it appear until python is installed in it

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10859]
With stable bits:

- Create new conda environment without python `conda create -n newEnv`
- Start VS code
- Open a notebook
- Conda environment will not appear in the list of kernels

Then
- Open a python file
- Select this environment as the active interpreter
- Python extension installs python into it
- You can now pick it as a notebook controller

**Comment by DonJayamanne** [comment]
Duplicate of #11855
