### ISSUE TITLE
Timed out waiting to get a heartbeat from kernel process for the latest version and older versions of python extension in vs code

### ISSUE THREAD

**Issue by okvarsh** [microsoft/vscode-jupyter#1086]
According to your output you have a very old python extension installed. This extension should be updated to the latest too:

```ms-python.python-2020.8.108011```

_Originally posted by @rchiodo in https://github.com/microsoft/vscode-python/issues/14707#issuecomment-726220969_
![issue2](https://user-images.githubusercontent.com/57315334/98975570-458bfe00-253c-11eb-89c3-e00b9d48889f.png)
![issue3](https://user-images.githubusercontent.com/57315334/98975576-4755c180-253c-11eb-90b0-ebfe17483385.png)
![issue1](https://user-images.githubusercontent.com/57315334/98975579-47ee5800-253c-11eb-8fe6-80f4eefd1d67.png)

**Comment by okvarsh** [comment]
Yes my TEMP is set to this
TEMP=C:\\Users\\varsh\\AppData\\Local\\Temp;C:\\Program Files\\Tesseract-OCR
What should it be changed to?

> This looks like the root cause:
> 
> ```
> write to stderr: OSError: File 'C:\\Users\\varsh\\AppData\\Local\\Temp;C:\\Program Files\\Tesseract-OCR\\tmp-17668u1svxSNnArsM.json' does not exist in any of the search paths:
> ```
> 
> Is your TEMP variable set to something other than a single directory?
> 
> From that error it looks like this:
> 
> ```
> TEMP=C:\\Users\\varsh\\AppData\\Local\\Temp;C:\\Program Files\\Tesseract-OCR
> ```

**Comment by rchiodo** [comment]
It should just be this:

```
TEMP=C:\\Users\\varsh\\AppData\\Local\\Temp
```

**Comment by rchiodo** [comment]
Although you might want to find out what added the Tesseract-OCR to the end? It might not work after you change the TEMP variable.

**Comment by okvarsh** [comment]
Yes, I changed the Temp variable and reinstalled python extension. It works fine now!
