### ISSUE TITLE
Flaky test: Kernel.IKernelConnection Events

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#10860]
This test here: https://github.com/microsoft/vscode-jupyter/blob/703a363c70f0e943906447858a2f5472bec02b82/src/test/datascience/notebook/kernelEvents.vscode.common.test.ts#L118 failed unexpectedly in this PR: https://github.com/microsoft/vscode-jupyter/pull/10825

I couldn’t reproduce it locally. After re-running the CI builds on that PR, that test passed.

**Comment by DonJayamanne** [comment]
@sadasant looking at that PR, looks like there were other failures, Export and one particular Job didn't run to completion at all.
Couldn't find a kernelconnection events failure though.

**Comment by sadasant** [comment]
@DonJayamanne I'm sorry! The Kernel Events failure happened in the previous run. I tried to debug it, but locally it would just work, so I restarted the PR pipelines and the test passed

(though others failed that hadn't failed the previous time, as you noticed)

**Comment by sadasant** [comment]
Should we close the issue until we find a reproducible way to make this test fail?

**Comment by greazer** [comment]
Flaky, but not flaky enough to keep open right now.
