### ISSUE TITLE
[Plot Viewer] Implement export to PDF on the web

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#10866]
This issue is because, for the first PR of #10405 I'm going to avoid implementing the PDF exporting feature of the Plot Viewer, as it uses local write streams and this dependency `svg-to-pdfkit` which is loaded in real time with `require`, meaning that trying to solve it heads on might lead me to a number of issues that would delay the immediate benefits our customers could receive otherwise.

**Comment by DonJayamanne** [comment]
This has already been done
