### ISSUE TITLE
Trouble with using tensorboard extension with remote SSH (timeout)

### ISSUE THREAD

**Issue by dibbla** [microsoft/vscode-jupyter#10874]
Hi guys,

My VSCode encounterred a problem when using the tensorboard extension. 

## Situation
After press `Ctrl+Shift+P` and launch the tensorboard, VSC seems loading forever and reports a timeout of 60s. I'm using tensorboard extension together with the SSH remote (I'm developing on a server with SSH remote extension).

## Several Attempts
- First I changed the conda env, but in vain.
- I also tried to use ssh terminal with `tensorboard --logdir .`, and it reported that 'absl' is missing. However, I checked via `conda list` and I'm pretty sure I've installed absl-py.
- Just before things went wrong, the tensorboard extention worked fine. I changed a few lines in my `.bashrc` trying to modified the setting of CUDA. But I still cannnot get the extension work after changing the file back to origin.

## Info might be useful
I actually encountered this problem earlier this year in other conda env. I installed tensorboard extension according to the VSC pop up window(tiny tips in right-buttom). Then it worked. But I now can hardly remember what command VSC input to the terminal. Maybe redo the line may help?

## My Environment

Remote:
- Ubuntu 20.04
- tensorboard 2.9.1
- absl-py 1.1.0
- numpy 1.19.5

Thanks!

**Comment by rchiodo** [comment]
Thanks for the bug.

Your python output log should contain information about what tensorboard was doing. We [log](https://github.com/microsoft/vscode-python/blob/0974f9239c7e38e406a66a0b9f06e547604d4475/src/client/tensorBoard/tensorBoardSession.ts#L468) stdout and stderr from running the tensorboard module.

**Comment by dibbla** [comment]
> Thanks for the bug.
> 
> Your python output log should contain information about what tensorboard was doing. We [log](https://github.com/microsoft/vscode-python/blob/0974f9239c7e38e406a66a0b9f06e547604d4475/src/client/tensorBoard/tensorBoardSession.ts#L468) stdout and stderr from running the tensorboard module.

Sry not quite get your point. I'm running python code/launching tb session just by terminal command. The output log for running `tensorboard --logdir [my folder]` is:
```
Traceback (most recent call last):
  File "/home/dibbla/.local/bin/tensorboard", line 5, in <module>
    from tensorboard.main import run_main
  File "/home/dibbla/.local/lib/python3.8/site-packages/tensorboard/main.py", line 26, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'
```

And the error info given by VSC is:
*We failed to start a TensorBoard session due to the following error: Timed out after 60 seconds waiting for TensorBoard to launch.*

Maybe these info help?

**Comment by rchiodo** [comment]
Yes the module absl is missing. That's why it times out, it doesn't actually start.

**Comment by dibbla** [comment]
> Yes the module absl is missing (or at least it's not found in the sys path). That's why it times out, it doesn't actually start.

yes you're right. I redo `/bin/python3 /home/dibbla/.vscode-server/extensions/ms-python.python-2022.10.1/pythonFiles/shell_exec.py /bin/python3 -m pip install -U tensorboard /tmp/tmp-3690113vmd9xrwV8cpD.log` and follow the warning to add dir to PATH. It is now working again. 👍

**Comment by Jimimaku** [comment]
> Hi guys,
> 
> My VSCode encounterred a problem when using the tensorboard extension.
> 
> ## Situation
> After press `Ctrl+Shift+P` and launch the tensorboard, VSC seems loading forever and reports a timeout of 60s. I'm using tensorboard extension together with the SSH remote (I'm developing on a server with SSH remote extension).
> 
> ## Several Attempts
> * First I changed the conda env, but in vain.
> * I also tried to use ssh terminal with `tensorboard --logdir .`, and it reported that 'absl' is missing. However, I checked via `conda list` and I'm pretty sure I've installed absl-py.
> * Just before things went wrong, the tensorboard extention worked fine. I changed a few lines in my `.bashrc` trying to modified the setting of CUDA. But I still cannnot get the extension work after changing the file back to origin.
> 
> ## Info might be useful
> I actually encountered this problem earlier this year in other conda env. I installed tensorboard extension according to the VSC pop up window(tiny tips in right-buttom). Then it worked. But I now can hardly remember what command VSC input to the terminal. Maybe redo the line may help?
> 
> ## My Environment
> Remote:
> 
> * Ubuntu 20.04
> * tensorboard 2.9.1
> * absl-py 1.1.0
> * numpy 1.19.5
> 
> Thanks!
