### ISSUE TITLE
Localization problem of the toolbar button

### ISSUE THREAD

**Issue by ted1030** [microsoft/vscode-jupyter#10873]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

![image](https://user-images.githubusercontent.com/37107237/179928280-499a357f-f904-438b-b8a0-70425839325f.png)

The "Interrupt" button is not translated.

### VS Code Version

1.69.1

### Jupyter Extension Version

v2022.7.1001951036

### Language Extension Version (if applicable)

Python Extension v2022.11.12001005

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment]
Thanks for the bug. Not sure why interrupt isn't translated. Looks like the translation team just missed it for some reason.

**Comment by sadasant** [comment]
@ted1030 Thank you for reporting this! Fortunately we have fixed this. It will be included in the next release. Have a good day! And let us know if you have any other feedback 👍
