### ISSUE TITLE
Some python settings not migrated to jupyter extension correctly (Was: Glitches due to vscode-jupyter transition)

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-jupyter#1088]
It appears the [VS Code Jupyter](https://github.com/microsoft/vscode-jupyter) extension was recently auto-installed on my machine, presumably by the Python extension.

It seems to have done a decent job of porting my existing data science settings over to the new extension, e.g.

```diff
- "python.datascience.magicCommandsAsComments": true,
+ "jupyter.magicCommandsAsComments": true,
```

However, after the transition, the interactive window was no longer showing any code lenses. Took me a minute to figure out that's because the settings had been renamed and they now needed to be called

```diff
- "jupyter.codeLenses": "python.datascience.runcell, python.datascience.runallcellsabove, python.datascience.runcellandallbelow, python.datascience.debugcell",
+ "jupyter.codeLenses": "jupyter.runcell, jupyter.runallcellsabove, jupyter.runcellandallbelow, jupyter.debugcell",
```

Only the JSON key `"python.datascience.codeLenses"` had been automatically renamed, not the string itself. I think it's worth triggering another automatic rewrite of user settings that handles this change so others don't encounter the same issue and perhaps spend longer on figuring out why their code lenses disappeared.

Second, some of my custom keybindings stopped working as well. E.g. I had
```json
{
  "key": "ctrl+shift+enter",
  "command": "python.datascience.runallcells"
}
```

which now just triggers a warning

> command 'python.datascience.runallcells' not found

Perhaps those can be auto-migrated as well.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue & I'm sorry you had to migrate these settings manually.
Looks like we missed some settings when migrating the settings to the new extension.
