### ISSUE TITLE
`shift + enter` broken again ... and again

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#1089]
Issue Type: <b>Bug</b>

Every couple of VS Code updates, this keeps breaking.

https://github.com/microsoft/vscode-python/issues/6578

Yet again... pressing <kbd>shift</kbd> + <kbd>enter</kbd> after an update gives:
`command 'python.datascience.execSelectionInteractive' not found`
and does not run the selected code block in the Python Interactive Pane.

Extension version: 2020.11.358366026
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.61GB free)|
|Process Argv|--crash-reporter-id f652528b-5678-4b12-9ca0-3de6b1e1135f|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by clayms** [comment]
looks like it was replaced with `jupyter.execSelectionInteractive` 

are all of these changes to settings and commands documented somewhere?  A lot of other things have broken in the last update.

**Comment by DonJayamanne** [comment]
I'm sorry the migration (from Python to Jupyter extension) hasn't been very smooth for you.
With regards to the commands, all `python.datascience.xyz` commands have been renamed to `jupyter.xyz`.

With regards to documentation, we will look into this, currently our documentation sits in https://code.visualstudio.com/docs/python/jupyter-support

**Comment by StevenLi-DS** [comment]
@DonJayamanne Not smooth? Everything's broken on my end and I've spent hours to try to fix everything while getting nothing done. The doc you mentioned is about the notebook UI. How about the interactive window? It would really be great if you guys could give folks a heads-up.

**Comment by DonJayamanne** [comment]
>  there any plan to support vscode extensions in this new jupyter UI?

Yes, I can confirm that VS Code extensions are supported in the new Jupyter UI (if not please file an issue with VS Code).

**Comment by DonJayamanne** [comment]
@joyceerhl I believe your current PR already this issue.

**Comment by DonJayamanne** [comment]
Dup of #1088
