### ISSUE TITLE
Jupyter extension not compatible with VScode version 1.69.2

### ISSUE THREAD

**Issue by BCArg** [microsoft/vscode-jupyter#10909]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Jupyter extension (https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter) not compatible with latest VS code version (1.69.2). I tried to install the extension via the left-hand side panel on VS code as well as via vsix. None of them worked

Trying to install via the left-hand side bar on vs-code I get (on Log (Remote Server):

```
[2022-07-25 14:26:31.388] [remoteagent] [info] New EH opened, aborting shutdown
[2022-07-25 14:26:31.768] [remoteagent] [info] [127.0.0.1][c3f10e96][ManagementConnection] The reconnection short grace time of 5m has expired, so the connection will be disposed.
[2022-07-25 14:27:45.039] [remoteagent] [info] Getting Manifest... ms-toolsai.jupyter
[2022-07-25 14:27:45.093] [remoteagent] [error] Failed to install extension. ms-toolsai.jupyter
[2022-07-25 14:27:45.095] [remoteagent] [error] Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)
```

I then tried to download the vsix file (named `ms-toolsai.jupyter-2022.7.1002081042.vsix`) from [this link](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter), but when I try to install it via vsix I get:

![image](https://user-images.githubusercontent.com/20555037/180779356-060b0999-9549-4d15-9523-bd9a07ba0e0b.png)

The jupyter extension did not come bundled with the [python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python), which was also installed via vsix.

### VS Code Version

1.69.2

### Jupyter Extension Version

v2022.6.1201981810

### Jupyter logs

```shell
[2022-07-25 15:08:38.316] [remoteagent] [info] Getting Manifest... ms-toolsai.jupyter
[2022-07-25 15:08:38.370] [remoteagent] [error] Failed to install extension. ms-toolsai.jupyter
[2022-07-25 15:08:38.372] [remoteagent] [error] Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)
```

From `Log (Remote Server)` when attempting to install from within VScode

### Coding Language and Runtime Version

Python3 (from different conda environments)

### Language Extension Version (if applicable)

v2022.11.12061004 (installed via VSIX)

### Anaconda Version (if applicable)

conda 4.10.1

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
Here's the link to the extension that works with 1.69 version of VS Code.
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2022.6.1201981810/vspackage
If you'd like to find out how I got this version this is what i did:
* First get the link from the market place for latest vsix, which would be of the form https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2022.7.1002081042/vspackage
* Open VS Code stable
* Go into extensions and select Jupyter and copy the version number from there
* Update the link with the new version

Here's a screenshot of Jupyter extension with the version number
![Screen Shot 2022-07-26 at 07 14 19](https://user-images.githubusercontent.com/1948812/180875433-35f609c6-1f2b-4208-a5f8-3e4ed42858c8.png)

**Comment by BCArg** [comment]
thanks, it works now. But how can I know which jupyter extension version would be compatible with which VS code version, in this specific case, how can I know that jupyter extension `v2022.6.1201981810` is the one compatible with VS code `1.69`?

Now that I have `v2022.6.1201981810` installed (via VSIX, from the link you provided), I have the very same screenshot as you, though this was not the case before, that's why I got the error i.e. was trying to install a version not compatible with VScode 1.69

Thanks again
