### ISSUE TITLE
ctrl+x with cut of cell problem

### ISSUE THREAD

**Issue by Ldeeprenard** [microsoft/vscode-jupyter#10904]
Hi,

I've an issue with the cut & paste in a situation. 
I write code in a temporary cell, then i cut the text with ctrl+x, then i cut the cell with x, and then i lost the copy forever. ctrl+v didn't work, ctrl+z didn't restore the cuted cell. 

Same issue when i disable the jupyter keymap extension. 

## Environment data

-   VS Code version: 1.69.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.7.1001951036
-   Python Extension version (available under the Extensions sidebar): v2022.10.1
-   OS (Windows | Mac | Linux distro) and version: W10
-   Python and/or Anaconda version: 3.10.4 & 2.2.0
-   Type of virtual environment used : conda
-   Jupyter server running: Local

**Comment by amunger** [comment]
thanks for the report, the bug is actually in vscode: https://github.com/microsoft/vscode/issues/143123

**Comment by Ldeeprenard** [comment]
Thanks !
