### ISSUE TITLE
Automatically capture screenshots for ever test failure

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#10902]
We seem to be duplicating this everhwere.

**Comment by amunger** [comment]
It could probably go in the global test hooks

**Comment by DonJayamanne** [comment]
yes that's the plan, i think that's the only way to avoid the code duplication

**Comment by DonJayamanne** [comment]
Closing for now, i think  we should write more unit tests and most of the integration tests already capture screenshots, hence nothing to be gained from making this change
