### ISSUE TITLE
TestPlan: PlotViewer on the web

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#10919]
Testing the PlotViewer on the web.

Refs: https://github.com/microsoft/vscode-jupyter/issues/10405

- [x] web @tanhakabir

Complexity: 3

Authors: @sadasant

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2310881)

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2310919%0A%0A&assignees=sadasant)

---

### Requirements

- Install prerelease jupyter extension into http://insiders.vscode.dev
- Have a python environment that you can run jupyter from. (https://jupyter.org/install)
- Be familiar with jupyter notebooks
- (Good to have) Familiarity with https://matplotlib.org

### Set up

1. Go to a command prompt where you've installed jupyter into a python environment
2. Install `matplotlib`.
  - For Conda: https://anaconda.org/conda-forge/matplotlib
  - For pip: https://matplotlib.org/stable/users/installing/index.html
3. Switch to a folder you're using for testing
4. Run jupyter with the following command `jupyter notebook --no-browser --NotebookApp.allow_origin=*`

### Test steps

1. Open insiders.vscode.dev and create a new `.ipynb` file.
2. Connet to the jupyter server:
    1. Run the 'Jupyter: Specify jupyter server for connections' command.
    2. Pick 'Existing'.
    3. Paste the URL from the jupyter notebook server you started in step 3 of the setup.
3. In one of the Notebook cells, create a plot. You can use this code:

```py
import matplotlib.pyplot as plt
plt.plot([1,2], [1,2])
```

4. Run the cell in any way. For example: by clicking the ▶️ button at the left of the cell.
  1. It might ask which kernel to use. Pick the remote kernel.
5. Hover over the plot. You should see three buttons at the top-right of the plot.
  1. The first button from left to right should allow you to copy the plot, and paste it elsewhere.
  2. The second button should expand the plot in a separate tool (this is the Plot Viewer).
  3. The third issue should allow the plot to be saved.

https://user-images.githubusercontent.com/417016/180882962-4dce66bd-0521-4a3c-83b4-17ed32b91a2b.mov

### Known issues (may o may not happen to you)

- When saving the plot in the web: If you use the button that appears when you hover the plot, the file will be saved as `.ipynb`, however it will contain a python file (with the source code of the plot). In the desktop version however, you can download the `.png` version of the plot. #10921
- The plot viewer itself (the one that is accessed via the second hovered button) has a save button that fails to save the file in the web, citing that local folders are not supported #10922

**Comment by tanhakabir** [comment]
The basics seem to work well!
