### ISSUE TITLE
ipykernel with os.path issue.

### ISSUE THREAD

**Issue by dontworrywearetogether** [microsoft/vscode-jupyter#10929]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I'm try to get py file path, use code like this `os.path.dirname(sys.argv[0])`  
but the `sys.argv[0]` result is `.local/lib/python3.8/site-packages/ipykernel_launcher.py` 

how to fix it...
please let me know it.
thank a lot

### VS Code Version

os.path.dirname(sys.argv[0])

### Jupyter Extension Version

v2022.7.1001951036

### Coding Language and Runtime Version

python 3.8.10

**Comment by rchiodo** [comment]
Thanks for the issue.

sys.argv[0] is going to be the path that started the kernel, it has nothing to do with the cell you're running.

The `__file__` variable should point to the file that the cell was run from:

![image](https://user-images.githubusercontent.com/19672699/181062214-460236f2-12d7-4a0d-b77b-25004e04aaf9.png)
