### ISSUE TITLE
Web PlotViewer: "Export to different formats" failing with "Opening Local Folders is Unsupported"

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#10922]
Even though (I believe) "Export to different formats" (accessible after opening the plot in the separate plot viewer view) uses the same underlying code as "Save As", "Export to different formats" fails on the web with "Opening Local Folders is Unsupported".

**Comment by sadasant** [comment]
So far, I can't reproduce this neither using the `Extension (web)` debug approach nor using `vscode-test-web`. However, I'm testing this by copying the renderers code into the Jupyter extension code.

**Comment by sadasant** [comment]
@DonJayamanne reports that this isn't happening to him. We'll sync tomorrow.

**Comment by sadasant** [comment]
This bug does not reproduce in Chrome, but it does reproduce in the Brave Browser.

**Comment by DonJayamanne** [comment]
Closing for now as no one else has reported this and Brave browser isn't officially supported
https://code.visualstudio.com/docs/editor/vscode-web#_browser-support
