### ISSUE TITLE
Notify users of files that could have caused the kernel to crash

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#10923]
Refs: #7538

- [x] anyOS @rebornix
- [x] anyOS @karrtikr

Complexity: 3

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2310923%0A%0A&assignees=DonJayamanne)

---

### Requirements

- Install prerelease jupyter extension into VS Code Insiders (desktop)
- Have a python environment that you can run jupyter from. (https://jupyter.org/install)
- Be familiar with jupyter notebooks
- Use Python 3.6 or later (please ensure you aren't using Python 2, use `python --version` to check the version)
- Ensure the following setting is added to your settings.json file (this is a hidden setting only used for testing)
```jsonc
"jupyter.disableZMQSupport": true,
```

### Test Error message

1. Open a folder in VS Code
2. Add a file named `email.py` to the root directory of the workspace folder
3. Create an ipynb file in the root directory
4. Run a cell in the ipynb file with any code such as `print(1234)`
5. Wait for the kernel startup to fail (this can take around 30 seconds)

* [ ] Verify an error message is displayed indicating the fact that the presence of the file `email.py` may have caused the kernel to crash
* [ ] Delete the `email.py` file and verify the kernel now runs.

**Comment by rebornix** [comment]
It works great and the error message is intuitive. I only ran into a different exception on kernel restart.
