### ISSUE TITLE
web - IW debugging cannot find the file to debug

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#10920]
1. go to insider.code.dev
2. connect to a remote jupyter server
3. create a python file with a `# %%` cell and save it
4. click the debug cell code lens

actual:
the cell starts running, but instead of breaking in the file, a new editor opens with error message:
`Could not load source '<ipython-input-1-022d05bbd8a8>': source unavailable.`

**Comment by DonJayamanne** [comment]
Yes, I can repro that. looks like a regression.
Note: This works locally when connected to a remote Jupyter server, only fails in vscode.dev.
