### ISSUE TITLE
Better first install experience

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-jupyter#1092]
Tried installing the extension (without installing the Python extension) and was surprised to find that the extension can't run without the Python extension. It feels like the extension detail should have a big warning informing the users that a notebook language extension is required. Also, got this large stream of notifications:

![image](https://user-images.githubusercontent.com/35271042/98991116-3d05da00-24e0-11eb-87ec-6876747e0825.png)

It seems like the first two notifications should be consolidated. The last one should be asked at a later time (this is the first time i'm opening the extension).

**Comment by DonJayamanne** [comment]
The issue with the first two prompts has been identified & tracked here https://github.com/microsoft/vscode-jupyter/issues/1074

As for he second prompt, i agree we could defer that to later.

**Comment by greazer** [comment]
This is an issue that we just found ourselves. It's not intentional.

**Comment by rchiodo** [comment]
Validated
