### ISSUE TITLE
IPyKernel not installed into interpreter Python 3.8.6 64-bit

### ISSUE THREAD

**Issue by Gbhavesh007** [microsoft/vscode-jupyter#1093]
Issue Type: <b>Feature Request</b>

please help..

Extension version: 2020.8.109390
VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18362

**Comment by Liehu** [comment]
> @TomChan0508
> Instead of using `pip install ipyerkernel` pelase could you:
> 
> * Either activate the environment & then run `python -m pip install ipykernel`
> * Or run `<fully qualified path to python executable.exe> -m pip install ipykernel`
> 
> Using just plain `pip install` would not necesarily install into the same environment you have selected.

I have try ,but fail.
and I found the solution from https://github.com/microsoft/vscode-jupyter/issues/693#event-3986007931
reinstall pyzmq slove it

**Comment by sbwiecko** [comment]
> @sbwiecko @levalencia @Liehu
> 
> Please could you try the following:
> 
> * Open a terminal
> * Activate the environemtn
> * Run the command `python -m ipykernel --version`
> * Try manually running `python -m pip install ipykernel` if you are using conda, then please use `conda install ipykernel `

So that was a great indication, thanks a lot. I did that:
1 - `'C:\Program Files\Python38\python.exe' -m ipykernel --version`
`7.18.1`
2 - `'C:\Program Files\Python38\python.exe' -m pip uninstall ipykernel`
```
Found existing installation: ipykernel 5.3.4
Uninstalling ipykernel-5.3.4
```
3 - `'C:\Program Files\Python38\python.exe' -m pip list`
```
Package               Version
--------------------- ---------
ipykernel             5.3.0
```
4 - ???
5 - `'C:\Program Files\Python38\python.exe' -m pip uninstall ipykernel`
```
Found existing installation: ipykernel 5.3.0
Uninstalling ipykernel-5.3.0
```
6 -  `'C:\Program Files\Python38\python.exe' -m pip install ipykernel`
`Successfully installed ipykernel-5.3.4`
7 - Now it works again ;-)

**Comment by DrStarkXavier** [comment]
@TomChan0508 have you tried to install it using `pip3` instead of `pip` using the terminal:

`pip3 install ipykernel`

the output was:

```
Requirement already satisfied: ipykernel in c:\python\python39\lib\site-packages (5.3.4)
Requirement already satisfied: tornado>=4.2 in c:\python\python39\lib\site-packages (from ipykernel) (6.1)
Requirement already satisfied: traitlets>=4.1.0 in c:\python\python39\lib\site-packages (from ipykernel) (5.0.5)
Requirement already satisfied: jupyter-client in c:\python\python39\lib\site-packages (from ipykernel) (6.1.7)
Requirement already satisfied: ipython>=5.0.0 in c:\python\python39\lib\site-packages (from ipykernel) (7.19.0)
Requirement already satisfied: ipython-genutils in c:\python\python39\lib\site-packages (from traitlets>=4.1.0->ipykernel) (0.2.0)
Requirement already satisfied: pyzmq>=13 in c:\python\python39\lib\site-packages (from jupyter-client->ipykernel) (20.0.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\python\python39\lib\site-packages (from jupyter-client->ipykernel) (2.8.1)
Requirement already satisfied: jupyter-core>=4.6.0 in c:\python\python39\lib\site-packages (from jupyter-client->ipykernel) (4.7.0)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\doctor\appdata\roaming\python\python39\site-packages (from ipython>=5.0.0->ipykernel) (0.4.4)
Requirement already satisfied: setuptools>=18.5 in c:\python\python39\lib\site-packages (from ipython>=5.0.0->ipykernel) (49.2.1)
Requirement already satisfied: jedi>=0.10 in c:\python\python39\lib\site-packages (from ipython>=5.0.0->ipykernel) (0.17.2)
Requirement already satisfied: backcall in c:\python\python39\lib\site-packages (from ipython>=5.0.0->ipykernel) (0.2.0)
Requirement already satisfied: pygments in c:\python\python39\lib\site-packages (from ipython>=5.0.0->ipykernel) (2.7.2)
Requirement already satisfied: pickleshare in c:\python\python39\lib\site-packages (from ipython>=5.0.0->ipykernel) (0.7.5)
Requirement already satisfied: decorator in c:\python\python39\lib\site-packages (from ipython>=5.0.0->ipykernel) (4.4.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\python\python39\lib\site-packages (from ipython>=5.0.0->ipykernel) (3.0.8)
Requirement already satisfied: six>=1.5 in c:\users\doctor\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.1->jupyter-client->ipykernel) (1.15.0)
Requirement already satisfied: pywin32>=1.0; sys_platform == "win32" in c:\python\python39\lib\site-packages (from jupyter-core>=4.6.0->jupyter-client->ipykernel) (300)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\python\python39\lib\site-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel) (0.7.1)
Requirement already satisfied: wcwidth in c:\python\python39\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel) (0.2.5)  
```

**So, when I run it, it works**

![image](https://user-images.githubusercontent.com/72295771/99812092-b2ac1e80-2b4e-11eb-8f6e-dfdef725e376.png)

**Comment by DonJayamanne** [comment]
Thanks, looks like pyzmq was either corrupted for some users or ipykernel was not installed correctly.
Closing as this has been resolved.

**Comment by name-ohr** [comment]
i`d just installed ipykernal faild errore:

Traceback (most recent call last):
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\shell_exec.py", line 26, in <module>
    subprocess.check_call(shell_args, stdout=sys.stdout, stderr=sys.stderr)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:/Users/Administrator/AppData/Local/Programs/Python/Python37/python.exe', 'c:\\Users\\Administrator\\.vscode\\extensions\\ms-python.python-2020.12.424452561\\pythonFiles\\pyvsc-run-isolated.py', 'pip', 'install', '-U', 'ipykernel', '--user']' returned non-zero exit status 2.

**Comment by ArthurZ** [comment]
What solved my issue using an upgraded packaged in Anaconda is:
`conda uninstall pyzmq` then
`conda install pyzmq`

**Comment by charris-msft** [comment]
I hit the same issue and forced a reinstall of ipykernel and it fixed it:
From the Terminal window in VS Code:
`python -m pip install ipykernel --force`

**Comment by heapcog** [comment]
@charris-msft, I had the same issue and your suggestion worked...Thank you...

**Comment by neonbeast** [comment]
![d4](https://user-images.githubusercontent.com/66249437/108214479-3bd6ef80-7156-11eb-9705-ae5f04c4c080.PNG)

Guys ipykernel issue , i tried all things but not working!!

**Comment by jtLeo** [comment]
> I hit the same issue and forced a reinstall of ipykernel and it fixed it:
> From the Terminal window in VS Code:
> `python -m pip install ipykernel --force`

Thanks a lot, it works out for me!
Btw, I installed it directly under Command Prompt, and I noticed that I have to make sure that the installation was under the  Command Prompt WITH admin right!

**Comment by MikeKowalski43** [comment]
@charris-msft that worked for me. Thanks a lot!
