### ISSUE TITLE
Avoid polluting the user's shell history for automated actions

### ISSUE THREAD

**Issue by PeterJCLaw** [microsoft/vscode-jupyter#10935]
## Environment data

-   VS Code version: 1.69.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.6.1201981810
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04 LTS

## Expected behaviour

When collecting environment data, the extension should not pollute the user's shell history.

## Actual behaviour

I observed lines such as `printenv > /tmp/tmp-45935fdNhOTkd5hRYtxt` in my shell history which appear to have come from https://github.com/microsoft/vscode-jupyter/blob/545c0a7b00b073da4d73ed58bf6c49e0d31b7ee6/src/platform/terminals/helper.node.ts#L81-L93

I'm not sure if that command ending up in my shell history is expected or avoidable, though it is definitely surprising. My (and my colleagues) initial reaction to discovering this was to assume that we had picked up a vulnerability and started work to secure our systems against potential intrusion. Investigation (thankfully) suggests that this extension is a more likely source of the unexpected shell history.

It would be great if the extension could avoid polluting the user's shell history in this manner.

**Comment by rchiodo** [comment]
Thanks for the issue. 

We're using this at the moment to detect if jupyter is in the path or not. I wonder if `process.env` would be good enough?

**Comment by DonJayamanne** [comment]
Closed by PR https://github.com/microsoft/vscode-jupyter/pull/10986
