### ISSUE TITLE
disconnect SSH caused kernel being killed

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode-jupyter#10948]
After Using SSH Remote connection, disconnecting will kill the kernel.

How can I disconnect, then reconnect to a vscode dev container without killing the ipynb kernel within my workspace?

**Comment by rchiodo** [comment]
Thanks for the issue. 

The only way for a kernel to survive the VS code extension host dying (the process where our extension runs) is to use a jupyter server instead.

See this [issue](https://github.com/microsoft/vscode-jupyter/issues/1378#issuecomment-1004422673) for a discussion on using the 'remote' server to control your kernel lifetime.
