### ISSUE TITLE
Data Viewer: open the same variable from variable doesn't reuse Data Viewer

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#10942]
Testing #10915

* Click on the action "Show Variable in Data Viewer" from the variable view
* Data Viewer opened
* Click again
* It opens a new data viewer, instead of focusing on the Data Viewer again

**Comment by rchiodo** [comment]
I believe this is on purpose too. Has to do with auto refresh. You want the state of the dataframe before and after.

**Comment by sadasant** [comment]
Should we close this issue?

**Comment by rebornix** [comment]
> I believe this is on purpose too. Has to do with auto refresh

Now I see the intention, we allow users to open the value of the variable in a data viewer editor, and the value can change so each time we open a new data viewer to show the latest value on button click.

If this is what we offer, the command name is ambiguous **Show Variable in Data Viewer** is telling me that I will have the variable opened in a data viewer, and it's linked with the kernel state and Variable Viewer. **Show variable current value in Data Viewer** might reflect what it really does.
