### ISSUE TITLE
No auto refresh with Data Viewer

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#10943]
Testing #10915

* Open a variable in data viewer
* Update the variable value
* Variable View auto refreshes it value but Data Viewer doesn't

**Comment by rchiodo** [comment]
Data Viewer should have a refresh button? You may not want to auto refresh.

**Comment by rchiodo** [comment]
I mean I believe it already has one.

**Comment by DonJayamanne** [comment]
Agreed, i think this was deliberate

**Comment by sadasant** [comment]
Should we close this issue then?

**Comment by rebornix** [comment]
> You may not want to auto refresh

For a moment I was thinking why wouldn't I but then realized that users might want to have a lock'ed version of the variable viewed in the data viewer. 

With that said, when I open the variable from the variable to the data viewer, having auto refreshed turn on is my expectation. I would prefer by default auto refresh + a **lock** button.

**Comment by sadasant** [comment]
For this solution I'd like to discuss UI approaches. So, given my time constraints, I'll unassign this issue from me.

**Comment by DonJayamanne** [comment]
Closing this issue as there aren't any upvotes nor feedback from users for this issue.
