### ISSUE TITLE
Export to PDF does not work on Desktop

### ISSUE THREAD

**Issue by amytnguyen01** [microsoft/vscode-jupyter#10945]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Exporting to PDF does not work on desktop JupyterNB in VSCode. An error dialogue box pops up when this happens: 

![image](https://user-images.githubusercontent.com/59705411/181128490-2a333b0a-1862-4b21-b0ac-aefea8ca81e6.png)
![image](https://user-images.githubusercontent.com/59705411/181129315-04e4a6d7-24a3-440c-9f5c-c29d33aaf8c4.png)

### VS Code Version

Version: 1.69.2 (user setup) Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a Date: 2022-07-18T16:12:52.460Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Windows_NT x64 10.0.19044

### Jupyter Extension Version

Jupyter v2022.6.1201981810

**Comment by rchiodo** [comment]
Thanks for the issue.

The error in the output window explains what you have to do. You need to install `xelatex`. For more information look here:
https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex
