### ISSUE TITLE
Back button on Kernel Picker misses 'Connect to Another Jupyter Server' if starting remote.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10959]
Enable `jupyter.showOnlyOneTypeOfKernel`
Restart VS code
Pick a remote kernel
Bring up kernel picker
Select 'Connect to Local Kernels'
Go back

Expected:
It still says 'Connect to Another Jupyter Server'

Actual:
It only has the 'Connect to Local Kernels'

![image](https://user-images.githubusercontent.com/19672699/181308930-a18257c5-3017-4a7e-b084-d9f53b58c703.png)

**Comment by IanMatthewHuff** [comment]
Closed due to onlyOneTypeOfKernel
