### ISSUE TITLE
Native Notebooks - Insiders Survey

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#1095]
Logic for triggering survey: 

1. User is in VS Code Insiders and still opted into the Native Notebooks experiment
2. User runs > 99 cells 
OR
3. User opens > 5 notebooks 

Prompt: "Can you please take a minute to tell us about your notebooks experience in VS Code?" 
If user clicks x, prompt at next session. 
If user click yes, disable for 6 months. 
If user clicks no, disable for 3 months. 

*Please copy same trigger cadence for Data Science Stable Survey

**Comment by rchiodo** [comment]
I don't believe this is working? I cleared my global cache then tried opening 5 notebooks. Survey doesn't come up.

Looking at the code, I think this is likely the wrong 'notebook' provider:

https://github.com/microsoft/vscode-jupyter/blob/fee11a6d6e4aabf79b4a7fa99716b430882fded9/src/client/datascience/insidersNativeNotebookSurveyBanner.ts#L49

It should be using this notebook 'provider' instead:

https://github.com/microsoft/vscode-jupyter/blob/fee11a6d6e4aabf79b4a7fa99716b430882fded9/src/client/common/application/notebook.ts#L23

The first provider is for webview notebooks.

**Comment by rchiodo** [comment]
Validated.
