### ISSUE TITLE
Failed to install python extension

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-jupyter#10952]
Testing #10911

Followed the steps provided then clicked `install python extension` and saw an error message 
`Failed to install the python extension`
Logs

```
Visual Studio Code - Insiders (1.70.0-insider, undefined, desktop)
Jupyter Extension Version: 2022.7.1002101047.
Python Extension not installed.
Workspace folder /Users/meganrogge/Repos/vscode
info 8:29:16.522: ZMQ install verified.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 8:29:17.408: LSP Notebooks experiment is disabled -- not using Pylance
info 8:29:17.513: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 8:29:17.513: Find preferred kernel for Untitled-1.ipynb with metadata {"orig_nbformat":4} & preferred interpreter 
info 8:29:17.519: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 8:29:17.519: Find preferred kernel for Untitled-1.ipynb with metadata {"orig_nbformat":4} & preferred interpreter 
info 8:29:17.524: Preferred Remote kernel for Untitled-1.ipynb is undefined
error 8:30:31.690: Failed to install Python Extension via Kernel Picker command
warn 8:30:31.695: DataScience Error [Error: Failed to install the Python Extension.
	at _.installPythonExtensionViaKernelPicker (/Users/meganrogge/.vscode-insiders/extensions/ms-toolsai.jupyter-2022.7.1002101047/out/extension.node.js:2:2368540)
	at async a._executeContributedCommand (/Users/meganrogge/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:63914)]

```

**Comment by meganrogge** [comment]
I had already installed the python extension but it was disabled

**Comment by rchiodo** [comment]
@IanMatthewHuff is there something else we can collect from @meganrogge's machine that can tell us why the python extension failed to install?

**Comment by IanMatthewHuff** [comment]
This is a follow up from the previous work on the kernel picker commands. Basically the built in command that we use to install an extension can't handle the case where the extension is already installed, but disabled. And the extensions API can't tell you that an extension is installed but disabled (it doesn't show up in the .all list or anywhere else that I can see). This situation is what I added the timeout for since the installExtension command just hangs forever if the extension is installed but disabled.

I think the correct thing here would be for the core extension command to detect this situation and return that back as an error from the command and then for us to surface that.

**Comment by rebornix** [comment]
> I think the correct thing here would be for the core extension command to detect this situation and return that back as an error from the command and then for us to surface that

Since it's an explicit **Install** command and users' intention is to use the Python extension, maybe the core should activate it.

**Comment by IanMatthewHuff** [comment]
> > I think the correct thing here would be for the core extension command to detect this situation and return that back as an error from the command and then for us to surface that
> 
> Since it's an explicit **Install** command and users' intention is to use the Python extension, maybe the core should activate it.

Yeah, I was thinking that as a possibility as well. My worry was that "disable" is usually always an explicit user action to take, right? Undoing an explicit user action felt different to me versus just installing something missing. But I'm not sure on that. Just activating does seem easier.

**Comment by IanMatthewHuff** [comment]
Timeout was previously added for this scenario, so closing.
