### ISSUE TITLE
after window reload, still in local mode but no `Connect to Jupyter Server` option

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-jupyter#10958]
Testing #10911
![Screen Shot 2022-07-27 at 10 01 25 AM](https://user-images.githubusercontent.com/29464607/181306494-ae8b7193-c628-4290-a799-e1e9ca0d6f75.png)

**Comment by rchiodo** [comment]
That's not the first step? What steps did you take to get there?

**Comment by rchiodo** [comment]
That should be expected if you picked 'Connect to Local'

**Comment by meganrogge** [comment]
I did not pick connect to local - that option wasn't there. Here were my steps. 

Remote back

Bring up a notebook and a kernel picker again
You should be showing remote kernels
Pick Connect to Local
The list of local kernels should appear
Hit escape
Bring up kernel picker again
You should be showing remote kernels
Pick Connect to Local
The list of local kernels should appear
Hit back
You should be showing remote kernels
Remote to local

Bring up notebook and a kernel picker again
Pick Connect to Local
Pick a local
Bring up kernel picker
It should show only local
Restart

Restart VS code
Make sure still in local mode


I noticed that the kernel picker only showed local options but the status bar indicator said `Jupyter Server: remote`

**Comment by rchiodo** [comment]
So you did all of those steps, restarted VS code and clicked on the kernel picker? How did you bring up that quick pick you have in the screenshot?

**Comment by meganrogge** [comment]
the above screen shot is what happened when I opened the kernel picker and I expected it to have `Connect to Local` but I guess it didn't because those were already in the list?

not sure why the status bar entry said remote though, which is why I expected to see `Connect to local` as an option

**Comment by rchiodo** [comment]
Super weird. I'm not even sure how that's possible. The kernel picker doesn't bring up that dialog. The jupyter extension does. So clicking on the kernel picker should NEVER show that quick pick first. It's almost like it auto selected the 'connect to local' option.

And your status bar should say local too.

Thanks.

I'll try to repro.

**Comment by meganrogge** [comment]
I tried to reproduce and couldn't,  so maybe just a weird one time occurrence.

**Comment by rchiodo** [comment]
I can't seem to reproduce :(

**Comment by meganrogge** [comment]
fine to close this I think. only saw it one time
