### ISSUE TITLE
python 2 is selected and I'm shown a notification abt it no longer being supported

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-jupyter#10954]
Testing #10911

If python 2 is unsupported, not sure why it gets selected when I have others

![Screen Shot 2022-07-27 at 8 35 22 AM](https://user-images.githubusercontent.com/29464607/181288898-a4ec791c-ec32-431b-a81d-d0fdcbe43447.png)

**Comment by rchiodo** [comment]
We should probably disable python 2 kernels altogether? The suggestion logic in the core is also broken because it suggests the first kernel returned every time.

**Comment by IanMatthewHuff** [comment]
Closing as dupe of #11072
