### ISSUE TITLE
'Install Python' command is showing up in kernel picker even when python extension is installed

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10960]
![image](https://user-images.githubusercontent.com/19672699/181310222-928661f8-c54f-42c9-a2bd-a47200c5619d.png)

Not sure how, but all I did was reload the VS code window. It wasn't there before the reload.

After python finishes discovering all of the interpreters, it goes away.

**Comment by IanMatthewHuff** [comment]
Hmm, kinda functioning as expected, but not optimal. Our method for seeing if we need to install python has always been having the Python extension, but not detecting any Python interpreters. I think we keep that logic, but we could also add in something to wait until interpreters have initially loaded before we show it.
