### ISSUE TITLE
On Jupyter Notbooks add a keyboard shortcut to run current line/selection only 

### ISSUE THREAD

**Issue by gal064** [microsoft/vscode-jupyter#10974]
On Jupyter notebook add a keybind that allows you to only run current line. Google Colab has this feature and it's very useful:

https://user-images.githubusercontent.com/50427415/181645586-9583269b-0b05-4002-946a-740ad6b1fd22.mov

**Comment by amunger** [comment]
could be included in the scratch pad story

**Comment by amunger** [comment]
#4573

**Comment by amunger** [comment]
duplicate of https://github.com/microsoft/vscode-jupyter/issues/1471
