### ISSUE TITLE
Multiple `stream` text outputs in a cell is rendered weirdly

### ISSUE THREAD

**Issue by colinfang** [microsoft/vscode-jupyter#10982]
Jupyter version: 2022.6.1201981810
Jupyter notebook renderers: 1.0.9

If a cell has multiple outputs

```json
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1\n"
     ]
    },
    {
    "name": "stdout",
    "output_type": "stream",
    "text": [
        "2\n"
    ]
    },
    {
    "name": "stdout",
    "output_type": "stream",
    "text": [
        "3\n"
    ]
    },
    {
    "name": "stdout",
    "output_type": "stream",
    "text": [
        "4\n"
    ]
    }
   ],
```

the rendered output (ignore the code) looks like 
![image](https://user-images.githubusercontent.com/1499555/181904574-02d6d817-bf06-42b4-8a28-00ec84f35e95.png)

I noticed this when I was playing with IJulia kernel as it likes to emit mutiple outputs instead of collecting all outputs into one entry.

**Comment by colinfang** [comment]
https://github.com/JuliaLang/IJulia.jl/issues/1047  this is the related IJulia issue

**Comment by DonJayamanne** [comment]
I've tried this in the jupyter extension and this works as expected.
I can repro the exact same behaviour with the Julia extension in VS Code.
Looks like you are using the `Julia` extension, if you were to disable the `Julia` extension or select another kernel from the kernel picker (a `Julia` kernel contributed by the `Jupyter` extension), then this would work.

Please disable the `Julia` extension to verify the fix.
If the problem persists,please let us know and we'll gladly reopen this issue.

**Comment by colinfang** [comment]
I can reproduce this without Julia extension

The json of the `.ipynb` looks like

```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
        {
         "name": "stdout",
         "output_type": "stream",
         "text": [
          "1\n"
         ]
        },
        {
        "name": "stdout",
        "output_type": "stream",
        "text": [
            "2\n"
        ]
        },
        {
        "name": "stdout",
        "output_type": "stream",
        "text": [
            "3\n"
        ]
        },
        {
        "name": "stdout",
        "output_type": "stream",
        "text": [
            "4\n"
        ]
        }
   ],
   "source": [
    "print(1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10.5 ('.venv': poetry)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.5"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "512c91d955b25b534351ca4618113d6e22ddb840c99623bf00202fcd8908abb7"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

```

**Comment by colinfang** [comment]
Note Python would not automatically generate multiple outputs. This issue is on the renderer: it is unable to render properly if there are mutliple outputs in the raw json of `.ipynb`. I am not sure if that is legit `.ipynb` format though.
