### ISSUE TITLE
Display `Connect to another Jupyter server` in kernel picker

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#10991]
Comment from here https://github.com/microsoft/vscode-jupyter/issues/10665#issuecomment-1199819311
Originally filed by @amunger 

> where an option to connect to local kernels is shown, but an option to connect to another jupyter server should probably also be available

repro steps:

1. with `"jupyter.showOnlyOneTypeOfKernel": true`, connect to a jupyter server through vscode
2. exit vscode
3. kill that jupyter server
4. open vscode and start an interactive window, or open a notebook
5. Try to select a remote kernel

Actual:
you first need to get out of remote mode by selecting a local kernel, then you can connect to a remote server

**Comment by IanMatthewHuff** [comment]
Closing as showOnlyOneTypeOfKernel is removed.
