### ISSUE TITLE
IW error callstack links are off by one line with IPython7

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#11002]
execute these cells in the interactive window

```
# %%
def raiser():
  raise Exception("error")

# %%
raiser()
# exception raised
x = 1
```

Click on the some of the links in the resulting error callstack.
🐛 The cursor is placed one line off from where it should be

**Comment by amunger** [comment]
might just be an issue with IPython 7

**Comment by DonJayamanne** [comment]
From what I know we haven't added support for parsing of stack traces for `ipython7`
If you look at the code in `tracebackFormatter.ts` we have special code for `ipython8`, & nothing for `ipython7`
I also brought this up some time ago (when re-factoring this code)

**Comment by DonJayamanne** [comment]
Version 7 is over 2.5 years old, i think we can close this as wont fix.
