### ISSUE TITLE
error links in stack traces do not link to other cells correctly

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#11004]
Create two cells in a Jupyter notebook:

```
def raiser():
  raise Exception("error")
```

```
raiser()
# exception raised
x = 1
```

click on a link in the stacktrace from the first cell
:bug: the cursor will be placed in the second cell

the stacktraces also aren't numbering cells correctly:
![image](https://user-images.githubusercontent.com/2019016/182239696-4b54b1a5-babf-4a33-94cd-685d15442a3f.png)

**Comment by rchiodo** [comment]
Additionally (maybe a separate issue), links to python files don't show up:

![image](https://user-images.githubusercontent.com/19672699/182240959-b1413c19-4df6-4f77-884f-ff5d1f5e1e62.png)

**Comment by amunger** [comment]
repro's in old release, so not a regression

**Comment by amunger** [comment]
with the new IPykernel version, links aren't showing up at all (at least we're not showing the wrong ones anymore). Perhaps we can just add links if it's the current cell and not show links otherwise

**Comment by amunger** [comment]
duplicate of https://github.com/microsoft/vscode-jupyter/issues/11750
