### ISSUE TITLE
Run by line eventually stops working

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#11006]
Run by line over and over again on a cell.

Eventually VS code will hang.

I have this in the jupyter output:

```
Traceback (most recent call last):
  File "c:\Users\aku91\miniconda3\envs\debugPyLatest\lib\site-packages\ipykernel\kernelbase.py", line 328, in process_control
    await result
  File "c:\Users\aku91\miniconda3\envs\debugPyLatest\lib\site-packages\ipykernel\kernelbase.py", line 947, in debug_request
    reply_content = await reply_content
  File "c:\Users\aku91\miniconda3\envs\debugPyLatest\lib\site-packages\ipykernel\ipkernel.py", line 466, in do_debug_request
    return await self.debugger.process_request(msg)
  File "c:\Users\aku91\miniconda3\envs\debugPyLatest\lib\site-packages\ipykernel\debugger.py", line 657, in process_request
    self.stop()
  File "c:\Users\aku91\miniconda3\envs\debugPyLatest\lib\site-packages\ipykernel\debugger.py", line 400, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "c:\Users\aku91\miniconda3\envs\debugPyLatest\lib\site-packages\ipykernel\debugger.py", line 246, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq\backend\cython\socket.pyx", line 662, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory
```

**Comment by rchiodo** [comment]
After that point I can run a cell but I can no longer debug without restarting VS code. My guess is the state of the debugger in VS code thinks it's still debugging and it's sending a debug_stop request when it doesn't have to.

**Comment by amunger** [comment]
could also be causing flaky debug tests

**Comment by phgmacedo** [comment]
In https://github.com/microsoft/vscode-jupyter/issues/10596 I have another case where the Jupyter debugger breaks.

**Comment by amunger** [comment]
@rchiodo - can you provide the version info that you think might be relevant here (IPython, DebugPy)? I cannot get this to repro with what I have

**Comment by rchiodo** [comment]
I was using the latest of each. 

![image](https://user-images.githubusercontent.com/19672699/182471113-f9ab904b-7636-4d87-9ce7-4af1b4c63230.png)

I don't think it's a bug in debugpy though. I think we're not tracking state in the extension correctly.

**Comment by rchiodo** [comment]
After I hit the error state, restarting the kernel has no effect (which I think if debugpy was the problem, it would go away). I have to reload VS code for it to work again.

**Comment by rchiodo** [comment]
And it's not always the same error.

Like right now the UI thinks there's still one more line to run:

![image](https://user-images.githubusercontent.com/19672699/182472541-ff22d376-a44b-4cdb-831a-2b6baef9a860.png)

But the output from the cell shows the final line already ran:

![image](https://user-images.githubusercontent.com/19672699/182472605-c47d65aa-599b-47bc-8e8b-660729982c87.png)

And I can't step anymore.

**Comment by amunger** [comment]
I managed to hit that last described case after updating debugpy 1.6.0 to debugpy 1.6.2
I'm now also seeing that extra error in the cell output, https://github.com/microsoft/vscode-jupyter/issues/11036, which I see cropped in one of your screenshots.

**Comment by roblourens** [comment]
I haven't seen this particular case, or that error message, with all the latest versions (but am still working with debug stability in tests, and if there is a remaining issue, I'd expect to still turn it up there)
