### ISSUE TITLE
 jupyter's markdown doesn't work

### ISSUE THREAD

**Issue by lipengmao** [microsoft/vscode-jupyter#11015]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I can't use markdown. Once I open the markdown cell, the whole jupyter can't run. It says "go to", but it doesn't work. If the whole jupyter has only code, it can run, but once markdown is added, the whole jupyter cannot run. Why is this happening? I use multiple versions of jupyter like this.I am running jupyter on a remote server.

### VS Code Version

The latest version 

### Jupyter Extension Version

The latest version 

### Coding Language and Runtime Version

python 3.7 and more

### Language Extension Version (if applicable)

English

### Running Jupyter locally or remotely?

remote

**Comment by rchiodo** [comment]
Thanks for the issue. 

Can you share a screenshot and or an example notebook? 

Markdown is working fine when I try to repro:

![image](https://user-images.githubusercontent.com/19672699/182425190-72ee10ec-ecad-4a97-b66d-b6c56a0fa3f1.png)

**Comment by DonJayamanne** [comment]
@lipengmao  i think this wasn't working in yestedays insider vesion. Should be fixed today.

**Comment by DonJayamanne** [comment]
Closing for now, if this issue persists, please feel free to re-open this or create a new issue
