### ISSUE TITLE
Set `"PYDEVD_IPYTHON_COMPATIBLE_DEBUGGING" = "1"` in the environment prior to importing `debugpy`

### ISSUE THREAD

**Issue by fabioz** [microsoft/vscode-jupyter#11033]
There was a recent fix in `debugpy` to work properly with IPython and the fix requires that `"PYDEVD_IPYTHON_COMPATIBLE_DEBUGGING" = "1"` is set in the environment prior to importing `debugpy`.

See: https://github.com/microsoft/debugpy/issues/869#issuecomment-1132141003 for details on why a custom support was needed.

**Comment by DonJayamanne** [comment]
@fabioz 
From what I understand the suggestion is to set the env variable always for pydevd to work properly in IPython, is that correct.

**Comment by fabioz** [comment]
@DonJayamanne yes, when using IPython it should always be set (it'll do nothing in `debupy 1.6.2` and earlier but on newer versions it should fix the issues related to stepping in IPython).
