### ISSUE TITLE
Hope to support Jupyter runtime completion in Python interactive scripts

### ISSUE THREAD

**Issue by syqg88** [microsoft/vscode-jupyter#11035]
Python interactive is very powerful and easy to use in vscode.
The command palette in the python interactive window already supports Jupyter runtime completion, which can automatically complete the column names of the dataframe.

But I don't always write code in command palette. I usually write code in .py files using "#%%", however Jupyter runtime completion is not supported in the .py file editing window.
Hope to support Jupyter runtime completion in Python interactive scripts.
thank!

**Comment by DonJayamanne** [comment]
Thanks for the suggestion, i believe we already  have an issue traacking this feature, will find that and close this in favor of that.

**Comment by amunger** [comment]
closing for lack of votes. There are downsides to implementing this since the intellisense would no longer be accurate for the script on its own, i.e. restarting the kernel could make the parts of the code invalid.
