### ISSUE TITLE
File shadowing warning given on __init__.py file

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-jupyter#11040]
Type: <b>Bug</b>

I have an app where I have an __init__.py file  that contains only `__version__ = '0.1.0'`. But opening it in VS Code is giving me the file name shadowing warning from Jupyter:

![image](https://user-images.githubusercontent.com/45497113/182719088-dc465ae2-568f-4caa-94a1-c610711b1bf6.png)

I think the chances of someone creating a file called __init__.py for their file is really small (compared to e.g. random.py, math.py), so I think files that start with __ shouldn't have this warning triggered for them? 

 Extension version: 2022.8.1002161046
VS Code version: Code - Insiders 1.70.0-insider (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-03T05:53:23.899Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (1.32GB free)|
|Process Argv|--crash-reporter-id 664528d7-58ad-4032-9a86-c163f8ada97b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728

```

</details>

**Comment by ludwigbald** [comment]
This issue persists for me, using VSCodium 1.70.2 and the Jupyter extension v2022.8.1002170547
