### ISSUE TITLE
tab hints like in browser version

### ISSUE THREAD

**Issue by loftusa** [microsoft/vscode-jupyter#1106]
Apologies if this already exists.

I have a notebook open, and tab doesn't work the same way that it does in a browser jupyter lab environment. I'd like to be able to press tab when my cursor is at the end of an object, and have all of its attributes pop up, exactly as it is in the browser.

I looked through the settings and couldn't find a feature that did this.

**Comment by greazer** [comment]
Hey @loftusa, I had typed a rather large response to this issue, but apparently it got lost (maybe I forgot to press the right button). Anyway, I'm trying to figure out whether you are not happy with how VS Code normally supports autocomplete when typing code, or whether you're simply looking for the shortcut key to force autocomplete to come up on a line you've already typed. To do that, just press ```ctrl-space``` (or ```cmd-space``` on Mac).
