### ISSUE TITLE
Matplotlib widget represantation broken after update

### ISSUE THREAD

**Issue by dawnclaude** [microsoft/vscode-jupyter#11065]
After updating VS Code, the code that used to work and show interactive matplotlib plot with Jupyter IPyWidget does not work anymore.

Example cell:

```
import numpy as np
import matplotlib.pyplot as plt
%matplotlib widget

t = np.linspace(0,2*np.pi,100)
y = np.sin(t)
fig = plt.figure()
plt.plot(t,y)
```
This used to show the interactive widget plot, now it doesn't show anything when IPyWidget output representation is selected. Other representations like png work fine.

- VS Code Version: 1.70.0
- OS Version: Windows x64 10.0.18363

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, I've tested this at my end and things work as expected.
Please could you:
* Run the cell, and then 
* Capture all of the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to it) and upload that here
* Also open the developer tools using the command `Toggle Developer Tools`, 
    * Then go into the console window
    * If there are any errors in there, please capture those and send them as well (you might want to take a screenshot)

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
