### ISSUE TITLE
Unsupported kernel showing up

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#11072]
## Environment data

-   VS Code version: 1.70.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.7.1002181843
-   Python Extension version (available under the Extensions sidebar): v2022.12.0
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: Python 3.10.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Actual behaviour

A kernel from my WSL environment shows up on the kernel picker list, when I'm not connected to WSL from VS Code.
![image](https://user-images.githubusercontent.com/10833267/183532299-c8143557-4b80-49c0-ab33-41e0d655f46c.png)

When I pick that kernel, I get this error:
![image](https://user-images.githubusercontent.com/10833267/183532392-6c9c106a-ee31-465b-86de-5c4625c44ed3.png)

Which links here, which wasn't helpful: https://github.com/microsoft/vscode-jupyter/wiki/Using-unsupported-Python-Environments

**Comment by GlucoseHuang** [comment]
I also encountered this situation. I tried to exclude it with setting "jupyter.kernels.filter", but didn't work. (I work on Macbook Air 2020, M1)

**Comment by DonJayamanne** [comment]
based on internal discussions this could not be reproduced
