### ISSUE TITLE
hvplot not rendering

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#11071]
## Environment data

-   VS Code version: 1.70.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.7.1002181843
-   Python Extension version (available under the Extensions sidebar): v2022.12.0
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: Python 3.10.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Actual behavior

Plot created using `hvplot` doesn't render and only renders when used with `panel`
![image](https://user-images.githubusercontent.com/10833267/183532057-a1bbbf68-18a9-460a-8787-ec16449bb12e.png)

**Comment by DonJayamanne** [comment]
@minsa110 please could you share the notebook for this so I can test this at my end.

**Comment by DonJayamanne** [comment]
[panel.ipynb.zip](https://github.com/microsoft/vscode-jupyter/files/9297598/panel.ipynb.zip)

**Comment by DonJayamanne** [comment]
@minsa110 
I've tried the notebook you gave:
* I'm getting the plot for the code `holo_df.hvplot.scatter('bill_length_mm', 'bill_depth_mm')`
* However, when you run the exact same notebook in Jupyter Notebook, it doesn't work, i get the exact same output as you do. I.e. the plot is not rendered in Jupyter notebook either.

Please could you:
* Test running the above notebook in Jupyter notebook & Jupyter Lab (both seprately)
* Let me know which one works
* Provide the version of Jupyter Notebook & Jupyter Lab, use the command `jupyter --version` to get the version info.
* Try the same notebook in VS Code Insiders with the latest pre-release version of the extesnion

**Comment by minsa110** [comment]
It actually doesn't work on any of these...:

| Tool | Works? |
| --- | --- |
| VS Code | No<br>- VS Code version: 1.70.0<br>- Jupyter version: v2022.7.1002181843 |
| VS Code Insiders | No<br>- VS Code version: 1.71.0-insider<br>- Jupyter version: v2022.8.1002241042 |
| Jupyter classic | No<br>![image](https://user-images.githubusercontent.com/10833267/183924820-f9ca728d-e6a5-4ba2-9787-33e4b9604882.png) |
| Jupyter Lab | No<br>![image](https://user-images.githubusercontent.com/10833267/183929092-6143c18a-3c9f-4ec5-ae4d-224fbbde5ac0.png) |

**Jupyter versions**
IPython          : 8.4.0
ipykernel        : 6.9.1
ipywidgets       : 7.6.5
jupyter_client   : 7.2.2
jupyter_core     : 4.10.0
jupyter_server   : 1.18.1
jupyterlab       : 3.4.4
nbclient         : 0.5.13
nbconvert        : 6.4.4
nbformat         : 5.3.0
notebook         : 6.4.12
qtconsole        : not installed
traitlets        : 5.1.1

**Comment by DonJayamanne** [comment]
ha ha...

**Comment by minsa110** [comment]
Closing, since it doesn't work on other tools as welll
