### ISSUE TITLE
Counter in dataviewer

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#11082]
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/11081

<div type='discussions-op-text'>

<sup>Originally posted by **KrisvanderMast** August  9, 2022</sup>
When using the dataviewer in Jupyter notebook I can easily filter. That's great but I can't see how many records remain of the total when filtering. For example if I have 30.000 records displayed and filter on a column first name for Kris I'd love to see how many records have Kris in their first name column. 

This discussion started first out on Twitter: https://twitter.com/KrisvanderMast/status/1554898271172272133</div>

**Comment by DonJayamanne** [comment]
Closing this issue as there aren't enough upvotes to warrant this feature.
