### ISSUE TITLE
Jupyter interpreter can be invalid and break things

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1110]
See the discussion here:
https://github.com/microsoft/vscode-jupyter/issues/513

Sometimes the jupyter interpreter can go out of date. We should verify it's still valid somehow before using it.

**Comment by Mjboothaus** [comment]
Yes - I think I'm coming across this sort of issue within my Gitpod.io environment.

Basically I'm defining an environment completely via code (in this case .gitpod.yml - which in turn contains shell commands to install a conda environment which is then added as a Juypter kernel).

So I end up with a conda environment called say MY_ENV_NAME and I am installing this as a Jupyter kernel i.e.

`python -m ipykernel install --user --name=MY_ENV_NAME`

as part of the build script. So the kernel is installed to:

`/home/gitpod/.local/share/jupyter/kernels/MY_ENV_NAME`

However notebooks that I have been successfully using and running with this conda environment, when I re-launch the Gitpod environment it is opening the notebook, but it is failing to recognise the environment.

Interestingly, this was working beforehand but has just broken somewhere in the infrastructure i.e. either Gitpod or VS Code which makes it difficult to track down.

**Comment by rzhao271** [comment]
What are some verification steps for this issue?

**Comment by Mjboothaus** [comment]
As you can appreciate this issue was sometime ago now and while I can recall the behaviour I don't have a specific example at hand.

I suspect both VS code and get pod have changed significantly since then – and I have not been using it pod very much since then because of the issue at the time.

When I get a moment I might re-try using my gitpod environment from before
Cheers

**Comment by Mjboothaus** [comment]
https://github.com/DataBooth/db-hello-gitpod

I think the .Gitpod.yaml file in this repo was the example I was running at the time

**Comment by DonJayamanne** [comment]
No one has reported this for a while, hence marking as verifeid
