### ISSUE TITLE
Debugger architecture review

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#11108]
Review the organization of the debugger code. https://github.com/microsoft/vscode-jupyter/wiki/Source-Code-Organization

Could include https://github.com/microsoft/vscode-jupyter/issues/10638 and linked issues

Also see https://github.com/microsoft/vscode-jupyter/issues/7057

**Comment by DonJayamanne** [comment]
Closing this deb issue for now as stale.
