### ISSUE TITLE
Support loading notebooks Widget state

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#11117]
* When we open a notebook with saved widget state, ensure we render this

We had an issue for this, unable to find the old duplicate issue, we have this commented in the code though.

**Comment by DonJayamanne** [comment]
Technical challenges
**Where do we load source for 3 party widgets**
* Assume we save the widget state for matplotlib and now share this notebook with someone
* Upon opening the notebook, the widget framework will attempt to load the widget classes (JS modules) for the matplotlib module (as defined in the widget state)
* However such modules have not been loaded, hence widget state will not load
* Result = widget will not be displayed
This only works for built in widgets as the source is bundled with the ipywidgets module in jupyter extension.

**Comment by maximlt** [comment]
It looks like this is the issue you were looking for https://github.com/microsoft/vscode-jupyter/issues/4404.
