### ISSUE TITLE
Interactive Window kernel picker does not change when switching to remote mode

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#11111]
Type: <b>Bug</b>

1. turn on new remote experience: `"jupyter.showOnlyOneTypeOfKernel": true,`
2. create an interactive window
3. go to the kernel picker and connect to a jupyter server
4. Select a kernel
:bug: Selected kernel did not change

:bug: going from remote to local, a local kernel is shown in the kernel picker, but not necessarily the one selected, and running a cell will ask you to pick a kernel

Extension version: 2022.8.1002261021
VS Code version: Code - Insiders 1.71.0-insider (ef65ac1ba57f57f2a3961bfe94aa20481caca4c6, 2022-08-11T05:16:46.298Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (12.79GB free)|
|Process Argv|--crash-reporter-id 1202dc88-403d-4ebc-8393-af3551a8bd5b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252

```

</details>

**Comment by IanMatthewHuff** [comment]
Closing due to "onlyOneTypeOfKernel"
