### ISSUE TITLE
info 23:15:34.492: Execute Cell 0 c:\Users\SMART LAPTOPS\Desktop\latex doc\khan.ipynb info 23:15:35.851: Cancel all remaining cells true || Error || undefined info 23:15:35.852: Cancel pending cells info 23:15:35.852: Cell 0 executed with state Error

### ISSUE THREAD

**Issue by oriakhan** [microsoft/vscode-jupyter#11115]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
I'm closing this issue due to the lack of any information.
Please could you fill in the requested information and I'll be happy to re-open this issue, or please feel free to create a new issue with the missing information such as version, logs, etc.
