### ISSUE TITLE
DataFrame Explorer with interactive plots

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/vscode-jupyter#11123]
When working in the Jupyter interactive window I often want to explore my dataframes variable using the dataframe viewer.

![image](https://user-images.githubusercontent.com/42288570/184524361-9fb87da6-ce1f-4efa-8711-686360c9529b.png)

This has some power. But I would like more power including the ability to quickly explore plots via drag and drop similarly to the extension [Data Preview](https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-preview). It is based on the powerful, [Perspective](https://perspective.finos.org/) pivot table. The Data Preview extension only works on files. I would like some like that for exploring DataFrame variables.

![image](https://user-images.githubusercontent.com/42288570/184524401-26db8f0a-2310-4fb7-947c-bf4c7c2ed826.png)

(and yes I can do `.to_csv(...)` and open Data Preview on the file I've saved. But its just not the same user experience.

Part of my request is because I am responsible for our Data platform in a larger org. And a lot of new Pythonistas are entering. They can do a little bit of Python but might not be able to do all kinds of file and plotting commands fast. It would greatly help them if VS Code provided really strong tools for simple data exploration similarly to what they are used to in Excel.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, however given the fact that this has not received enough upvotes nor any comments since this was created, I'm going to close this.

**Comment by MarcSkovMadsen** [comment]
😢
