### ISSUE TITLE
Run by Line stops at the wrong line for a function call

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#11137]
test `Stops in same-cell function called from last line` is failing

Manual repro show there is a bug - the jump from the function call should go to line 2:
![RBL](https://user-images.githubusercontent.com/2019016/184920241-622c56fb-f001-4e67-8c7b-da0db1284c48.gif)

**Comment by DonJayamanne** [comment]
No more flaky tests, hence marked as verified
