### ISSUE TITLE
Wrong uninstallation method on linux systems

### ISSUE THREAD

**Issue by morfyum** [microsoft/vscode-jupyter#11130]
Infect the Linux home directory!
Impossible to remove with one click.
Annoying files stay on system.
Absolute malware/adware functionality!

After install python extension, Jupyter installed automatically as dependency.
This adware are show in app folder, and impossible to remove.

After remove 
  - this malware extension, 
  - or remove whole python extension, 
  - or remove VSCOD app, 
this malware stay on linux system home folder, and need to find and remove manually the files.

Absolute not user friendly!
I do not asked this tool, just installed automatically and impossible to remove as simple.

SYSTEM:
```
 - Fedora 36 Workstation latest 
 - Gnome 42 latest
 - Application: VSCodium
 - Installation method: flatpak
```

**Comment by DonJayamanne** [comment]
@morfyum 
Sorry for not getting back to you on this.
The Jupyter extesnion is an optional dependency of the Python extension, yes it is installed with the Python exension, however you can uninstall this anytime and as a result it will never get installed automatically again.

> This adware are show in app folder, and impossible to remove.

I'd like to undertand what you mean by impossible to remove. You should be able to just uninstall this `Jupyter` extension and that should be it.

> this malware stay on linux system home folder, 

Would help if you could provide more information on what folder is still in the home folder. Please could you share a screenshot of this.
Please note, I've tested this at my end and the extension folder gets deleted completely.

**Comment by morfyum** [comment]
Hello.

I cant replicate this issue. Maybe fixed? 

Previously after remove the jupyter.
The desktop icon stay on my system, maybe on `.local/share/applications/`, `.local/share/jupyter/` paths.

Currently directories are cleand.


Currently lot of file stay instide of flatpak app, this is not interested for me, because I doesnt see between my desktop apps.

`./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-2022.8*`


BTW all file under svcodium extension, stay on system. `Uninstall` button just remove the flag from vscodium? 
Files stay on system?

```
...
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/geojson.bundle.js.LICENSE.txt
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/vega.bundle.js.LICENSE.txt
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/renderers.js.map
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/renderers.js.LICENSE.txt
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/161.bundle.js.LICENSE.txt
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/geojson.bundle.js
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/dataresource.bundle.js
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/renderers.js
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/nteract_transforms.bundle.js.LICENSE.txt
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/plotly.bundle.js
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/modeldebug.bundle.js
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/nteract_transforms_vsdom.bundle.js
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/vega.bundle.js
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/plotly.bundle.js.LICENSE.txt
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/20.bundle.js
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/nteract_transforms.bundle.js
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/20.bundle.js.LICENSE.txt
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/161.bundle.js
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/591.bundle.js
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/extension_renderer
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/extension_renderer/index.js
./.var/app/com.vscodium.codium/data/codium/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/extension_renderer/index.js.map
...
```

**Comment by DonJayamanne** [comment]
> This is an uninstalled stage. App are closed, packages are stay on active system. but my primary issue is not this. I cant reproduce my real issue today.


Closing this issue as you cannot replicate this.
I would suggest you file an issue with VS Codium if this continues as this isn't a problem with VS Code.
Thanks for getting back to us with a confirmation.
