### ISSUE TITLE
Getting Pylance reportMissingImports when using Remote SSH with Jupyter Server: Remote

### ISSUE THREAD

**Issue by lgonzalezsa** [microsoft/vscode-jupyter#11157]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Working with Remote SSH to leverage remote filesystem access and having terminals connected to remote server. I am also interested to have a live kernel I can connect / disconnect as needed, expensive or long lasting code computation in my notebooks, then trying to have similar end user experience as I do have with Jupyter Lab web interface but certainly with the benefit if vscode.

Here the issue I am noticing, if I use local kernels no issues with Pylance, but the kernel is destroyed if I close vscode.
Now, using Jupyter Server: Remote connecting to localhost, allows me to keep live the kernel even if I disconnect, similar as closing the web browser when using Jupyter Lab.
However, Pylance complains with reportMissingImports
![image](https://user-images.githubusercontent.com/704686/185508228-04baab59-e1ec-4f1d-b669-842801de1248.png)

I am using the extensions correctly for my use case? Could I configure vscode or extension to properly let Pylance to work?

Thanks!

### VS Code Version

1.70.2

### Jupyter Extension Version

v2022.7.1102252217

### Jupyter logs

```shell
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:25.715Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.19.0-76051900-generic
```

### Coding Language and Runtime Version

Python 3.9.12

### Language Extension Version (if applicable)

v2022.12.1

### Anaconda Version (if applicable)

Conda 4.12.0

### Running Jupyter locally or remotely?

Remote

**Comment by IanMatthewHuff** [comment]
@lgonzalezsa I don't believe this is a configuration that you are missing. It's just a bit of a hole that we should (I believe) be able to patch up. Currently our pylance support doesn't work with remote connections. In the remote case we don't expect to have local access to the python environment in question which we need to work with Pylance. However in this case you just have the server started on localhost, so while it is "remote" we do actually have access to the Python environment that we could use for pylance. I think we do some special casing for "remote" running on the same machine in a few other places, so we might be able to do something like that here, but we are not currently doing that.

**Comment by Gorluxor** [comment]
Came to the same issue is there a possible workaround? Like is there a way to forward to vscode the jupyter lab's language server?
Another idea, if pylance needs local files, can some sort of remote-sync help?

**Comment by IanMatthewHuff** [comment]
Duping against #7889 for remote language server support.

**Comment by giahung24** [comment]
For anyone got into this issue and wonder why IanMatthewHuff closed it and pointed to a non-related issue. I think this is the right reference #13095
