### ISSUE TITLE
Add AAD auth token to the http header sent to jupyter server

### ISSUE THREAD

**Issue by zesluo** [microsoft/vscode-jupyter#1116]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description

Hello team! We are currenty trying to support 'Synapse Pyspark Interactive' in VSCODE extension. As the picture shown, it will include a base URL and a token. We want to add the synapse AAD token into it, so it can be sent to jupyter server. 
![image](https://user-images.githubusercontent.com/46309533/83884015-db925000-a776-11ea-821c-f56c2d80cf4a.png)

Previously, we used sparkMagic to do this. However,this time, the situation for Synapse is different as the livy for Synapse is not very standard. So we hope to add AAD token to the http header. Thanks a lot!

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by rchiodo** [comment]
I believe there was some question on timeout for the token? Maybe the example code doesn't include the addition of the expiration.

You should use these type definitions:

```typescript
export interface IJupyterServerUri {
    baseUrl: string;
    token: string;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    authorizationHeader: any; // JSON object for authorization header.
    expiration?: Date; // Date/time when header expires and should be refreshed.
    displayName: string;
}

export type JupyterServerUriHandle = string;

export interface IJupyterUriProvider {
    readonly id: string; // Should be a unique string (like a guid)
    getQuickPickEntryItems(): QuickPickItem[];
    handleQuickPick(item: QuickPickItem, backEnabled: boolean): Promise<JupyterServerUriHandle | 'back' | undefined>;
    getServerUri(handle: JupyterServerUriHandle): Promise<IJupyterServerUri>;
}
```

You implement the ```IJupyterUriProvider```.  The ```IJupyterServerUri``` you return from the ```getServerUri``` call should include an expiration date. When that date is up we'll reask for the new URI which should include the new auth headers.

**Comment by DavidKutu** [comment]
Hi @zesluo, does [this](https://github.com/microsoft/vscode-jupyter/issues/1116#issuecomment-764926131) solve the issue?

**Comment by DavidKutu** [comment]
@zesluo feel free to reopen this or create a new issue if its not fixed.
