### ISSUE TITLE
Deprecate `jupyter.generateSVGPlots`

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#11168]
This was added to have a high resolution SVG for plot viewer.
however we found that a number of users ran into issues as the generated notebook would end up being a few GB into of a mere few KB, hence the notebook was no longer usable (could not share the file and the like).

Note: The default value of `generateSVGPlots` used to be `true`, however now this is `false`.
I think this can now be removed all together, as its been almost 1 full year since we changed the default and we haven't had a single complaint about the plot viewer not using SVGs.

**Comment by amunger** [comment]
@agkphysics - the setting wasn't actually removed yet, the only thing changed here was adding a deprecation message. Can you create a new issue with repro steps that shows the issue?

**Comment by amunger** [comment]
and does something like `%config InlineBackend.figure_formats = ['svg']` fix it? (from this [SO post](https://stackoverflow.com/questions/36622237/jupyter-notebook-inline-plots-as-svg))

**Comment by agkphysics** [comment]
@amunger Okay I see now that it still works if you set `"jupyter.generateSVGPlots": true` in config. And your suggestion for `InlineBackend.figure_formats` also works, so this config variable doesn't seem to matter. Thanks.

**Comment by vvilhonen** [comment]
Why removing this? I don't mind the big size for having sharp figures and have been using the setting since I found it. Couldn't you just default to false for it? Setting up vscode on a new computer I had to google around to find the name of the setting as it's not visible anymore even though it's still working.

**Comment by amunger** [comment]
@vvilhonen - thanks for the input. We were just looking to cut unused features to reduce maintenance cost, but if it actually is being used, then we'll keep it around.
