### ISSUE TITLE
Dataframe display is not in monospaced font in interactive window

### ISSUE THREAD

**Issue by stevenlis** [microsoft/vscode-jupyter#11175]
## Environment data

Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:38:59.695Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.6.0

Jupyter extension: v2022.7.1102252217
Python extension: v2022.12.1

```
!jupyter --version
Selected Jupyter core packages...
IPython          : 8.4.0
ipykernel        : 6.9.1
ipywidgets       : 7.6.5
jupyter_client   : 7.2.2
jupyter_core     : 4.10.0
jupyter_server   : 1.18.1
jupyterlab       : 3.4.4
nbclient         : 0.5.13
nbconvert        : 6.4.4
nbformat         : 5.3.0
notebook         : 6.4.12
qtconsole        : 5.3.1
traitlets        : 5.1.1
```

## Expected behaviour

Dataframe display should be in monospaced font in html

According to this issue https://github.com/microsoft/vscode/issues/144417, this should be fixed.

## Actual behaviour

Dataframe display is not in monospaced font in html

![CleanShot 2022-08-22 at 21 10 28](https://user-images.githubusercontent.com/33796896/186046358-60b6bbf0-05e2-47c5-ab6e-366e62c7e014.png)
![CleanShot 2022-08-22 at 21 14 21](https://user-images.githubusercontent.com/33796896/186046758-9aae9a11-1bcf-4caf-bde2-40c9c865aa5e.png)

**Comment by IanMatthewHuff** [comment]
@DonJayamanne This isn't the data frame viewer, just output. Would that be your area? Or @rebornix?

**Comment by StevenLi-DS** [comment]
Could someone pls give me an update on this? Are you guys able to repro this issue, or am I missing something?

**Comment by StevenLi-DS** [comment]
@DonJayamanne Thank you for the explanation. But according to https://github.com/microsoft/vscode/issues/144417 , this is a bug. If this is an inherited, could you please transfer it to vscode?

**Comment by DonJayamanne** [comment]
No need to transfer just yet,

**Comment by stevenlis** [comment]
@DonJayamanne Hi, any update on this? It's been a year.

**Comment by DonJayamanne** [comment]
Hi, We prioritise issues based on upvotes and severity of the issues
Unfortunately we haven’t been able to prioritise this

**Comment by DonJayamanne** [comment]
Unfortunately this issue hasn't been upvoted by anyone else since the time this was created.
Closing this for now.
