### ISSUE TITLE
Extension activation failed [TypeError: s.notebooks.onDidChangeCellMetadata is not a function]

### ISSUE THREAD

**Issue by quaesitor-scientiam** [microsoft/vscode-jupyter#11174]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Open .ipynb and Jupyter extension automatically fails after upgrading VSCode

Visual Studio Code (1.70.2, undefined, desktop)
Jupyter Extension Version: 2022.2.1030672458.
Python Extension Version: 2022.4.1.
Info 19:03:21: ZMQ install verified.
Error 19:03:21: extension activation failed [TypeError: s.notebooks.onDidChangeCellMetadata is not a function

### VS Code Version

1.70.2

### Jupyter Extension Version

2022.2.1030672458

### Jupyter logs

```shell
Running the command results in 

Error dialog saying:  Command Jupyter: Show Output resulted in error
                      jupyter.viewOutput not found
```

### Coding Language and Runtime Version

Python 3.10.2

### Language Extension Version (if applicable)

2022.4.1

### Anaconda Version (if applicable)

n/a

### Running Jupyter locally or remotely?

Local

**Comment by quaesitor-scientiam** [comment]
Running on RHEL8 environment

**Comment by DonJayamanne** [comment]
Thanks for filing this issue

> Jupyter Extension Version: 2022.2.1030672458.

You seem to be having a very old version of the Jupyter exesnion.
Please update the jupyter extensison to the latest version and this problem should go away.
YOu might want to update your Python extension as well, as that too could cause other issues & failures.
