### ISSUE TITLE
Jupyter Scrolling during looping pyplot output

### ISSUE THREAD

**Issue by jtchilders** [microsoft/vscode-jupyter#11179]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I often use the strategy below in jupyter notebooks to see updating plots during a machine learning training or similar iterative algorithms. It involves using `pyplot` to plot data during the loop execution, while clearing the previous plot so that there is always only the latest result shown. However, if the loop is down the page (not at the top) and has content below it, the window scrolls up and down automatically. This can make it hard to center on the actual plots and watch them update. I don't see this behavior in a jupyter notebook server running on my macbook, so I presume this is VSCode specific.

The code is below, though to see the behavior, the loop needs to be in the middle of the page, so add some markdown blocks between the imports and the loop, and some markdown below the loop.

I recorded a Gif showing the behavior: [GIF of the problem](https://drive.google.com/file/d/1f-ZoLVnAmz9lHlLH13IH7Umy70l0VLok/view)

```python
import matplotlib.pyplot as plt
import numpy as np
import time
import IPython.display as ipydis


for step in range(10):

   x = np.arange(100)
   y1 = np.cos(x)
   y2 = np.sin(x)

   plt.close('all')
   fig,ax = plt.subplots(1,2,figsize=(18,6),dpi=80)
   ax[0].plot(x,y1,'-b')
   ax[1].plot(x,y2,'-r')
   plt.show()
   time.sleep(1)
   ipydis.clear_output(wait=True)
```

VS Code details:

1.70.2 (Universal)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z (1 wk ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0

### VS Code Version

1.70.2 

### Jupyter Extension Version

v2022.7.1102252217

### Coding Language and Runtime Version

Conda install of python 3.8.3

### Language Extension Version (if applicable)

v2022.12.1

### Anaconda Version (if applicable)

conda 4.13.0

### Running Jupyter locally or remotely?

Local

**Comment by IanMatthewHuff** [comment]
@DonJayamanne Might actually be a core rendering issue for @rebornix ?

**Comment by amunger** [comment]
it looks like this may have been fixed with the scrolling changes we've made, I'm not seeing that behavior. Let me know if that's no the case and we can re-open
