### ISSUE TITLE
`Specify local or remote Jupyter server for connections` broken

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#1118]
Issue Type: <b>Bug</b>

Communicating the migration instructions after factoring out Jupyter extension from the Python extension has been ham-handed.
among others: https://github.com/microsoft/vscode-jupyter/issues/1057

It is not at all clear that to get to the pop-up selection menu to input a new server in the <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd> menu, input `Jupyter: Specify local or remote Jupyter server for connections`.

If I select `Jupyter: Specify local or remote Jupyter server for connections`, even if its the same server it is already connected to, VS Code will force me to reload/restart VS Code.  If I don't restart and select `Jupyter: Specify local or remote Jupyter server for connections` again, I get a VS Code ERROR: 
> Command 'Jupyter: Specify local or remote Jupyter server for connections' resulted in an error (command 'jupyter.selectjupyteruri' not found)

Also, how can I delete urls from the list of recently used servers+tokens? It is keeping a list of all of the Jupyter servers that have long since been shut down.

Is it possible to specify the server in the `.code-workspace` settings like I used to before the Jupyter extension was factored out of the Python extension? It was much more convenient to simply specify "python.dataScience.jupyterServerURI": "http://100.100.100.001:8888/?token=*******************" in the settings.

Why was the `python.dataScience.jupyterServerURI` setting not ported over to the Jupyter extension as `jupyter.jupyterServerURI` along with most of the other `python.dataScience` settings?  

Extension version: 2020.11.358541065
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (1.95GB free)|
|Process Argv|--crash-reporter-id f652528b-5678-4b12-9ca0-3de6b1e1135f|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by clayms** [comment]
why can't I simply specify something similar to the following in my `.code-workspace` file ?

```
"settings":  {
    "jupyter.jupyterServerType": "remote"
    "jupyter.jupyteruri": "http://111.111.111.111:8888/?token=*************************************"
```

Where does the Jupyter extension save the remote jupyter server URI?

**Comment by clayms** [comment]
now I am getting 

> Unable to open 'Interactive - #1': Cannot read property 'createKey' of undefined.

and 

> Unable to write into workspace settings. Please open the workspace settings to correct errors/warnings in the file and try again.

**Comment by clayms** [comment]
well ... here is one ....

https://github.com/microsoft/vscode-jupyter/blob/68bee5c0117a9c7b7fd6f27ebc492e072d15daa8/package.nls.json#L109

**Comment by clayms** [comment]
How can I set `serverUriStorage.Uri` directly?

https://github.com/microsoft/vscode-jupyter/blob/68bee5c0117a9c7b7fd6f27ebc492e072d15daa8/src/client/activation/migrateDataScienceSettingsService.ts#L56-L58

**Comment by rchiodo** [comment]
Sorry but setting the server URI directly is not supported. You have to use the command. It's stored in encrypted storage as this value may contain a token to a Jupyter server that you wouldn't want to expose on your file system.

**Comment by rchiodo** [comment]
> python.dataScience.jupyterServerURI setting not ported over to the Jupyter extension as jupyter.jupyterServerURI

This should have happened automatically. It doesn't get ported to the same setting as it doesn't exist though. What should have happened is that it was encrypted and stored internally.

**Comment by rchiodo** [comment]
> Communicating the migration instructions after factoring out Jupyter extension from the Python extension has been ham-handed.

Was there something else you're having trouble with besides your remote setting?

**Comment by rchiodo** [comment]
We're also planning on revamping the remote support. Something more akin to this is coming:
https://github.com/microsoft/vscode-jupyter/issues/1366

**Comment by smackesey** [comment]
Agree that this is very confusing (change in behavior of `python.dataScience.jupyterServerURI`), I could not figure out why my environment suddenly changed. There is no explanation of changes due to migration (that I could find) in the docs. Also there is no explanation of what @rchiodo mentions above about the server URI being kept in encrypted storage. Is there any way to view this setting?

**Comment by rchiodo** [comment]
>  Is there any way to view this setting?

The only way to view the setting is to bring up the 'Specify local or remote Jupyter server for connections' picker. It will show the current value at the top:

![image](https://user-images.githubusercontent.com/19672699/99422069-f8998600-28b3-11eb-8993-9e49784c2125.png)

We should probably have a 'what's changed' in the release notes that describes what's changed.

I can do a brief summary here:

- All ```python.dataScience``` settings are now ```jupyter.``` settings except for one exception
- ```python.dataScience.jupyterServerURI``` has been removed. You can no longer set this in your settings.json. It's encrypted now. You have to use the command above.
- In the VS Code insiders version, we will default to using the new native notebook support. See 
https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/ and the blog post that came out with the new jupyter extension:
https://devblogs.microsoft.com/python/python-in-visual-studio-code-november-2020-release/

As far as I remember that should be the sum total of the differences. I'll add a bug to put this in our release notes (and or documentation)
