### ISSUE TITLE
Add support for automated testing of Jupyter Notebooks (ex nbval)

### ISSUE THREAD

**Issue by PhilMacKay** [microsoft/vscode-jupyter#1119]
Machine learning developers tend to do a lot of experimental work in Jupyter Notebooks, but it is very fastidious to share notebooks with colleagues and ensure the code is reliable and repeatable.

We would previously convert notebooks to scripts (using `Jupytext`) to allow static analysis tools to help catch problems in shared notebooks, but it's still complicated to make automated tests of these files because they execute the code as soon as they are imported.

I recently found the [`nbval`](https://github.com/computationalmodelling/nbval) extension that analyze `.ipynb` files and test each cell making sure it reproduces the saved output. Since we already have pytest all set up, it's very simple to add notebook testing! Building automated tests can become as simple as making a clean Jupyter Notebook, which would greatly help my team with a machine learning background adopt a good software development practice!
However, VSCode-Python doesn't display notebook tests in the test interface...

When `nbval` is installed (and that I have notebooks to test), I can run all tests and the notebook tests will be executed. I can see the results in the output log. However, they are not displayed in the Test interface because it seems that PyTest's results are not parsed correctly.

If you want to try the extension for yourself and see how it works with VSCode Python, you can clone the `nbval` repo and run its tests!

**Comment by DonJayamanne** [comment]
Thanks for the suggestion, however there haven't been any upvotes on this issue, hence closing this issue
