### ISSUE TITLE
Add support for parameters and/or tags assignment (papermill)

### ISSUE THREAD

**Issue by MSeal** [microsoft/vscode-jupyter#1121]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

Add ability to set metadata tags on a cell, like notebook classic supports in the gif below (but maybe with a better interface for it).

![enable_parameters](https://user-images.githubusercontent.com/1863892/68149173-408c7b80-fef2-11e9-8a81-5220c31d2913.gif)

## Description

Cell tags are used as a convention based pattern for converting notebooks in a few contexts. The [papermill](https://github.com/nteract/papermill) library uses the `parameters` and `injected-parameters` tags to manage user inputs to notebook executions. [NBConvert](https://github.com/jupyter/nbconvert) has notebook manipulation processors that filter or convert cells based on tags. Overall while it was originally used for metadata matching purposes, it's use for production execution paths has become a necessity with Jupyter today. Have a minimal way to manage the cell tags would go a long way for cross-tooling support.

**Comment by aeturrell** [comment]
+1. This would be really helpful when using with [JupyterBook](https://github.com/executablebooks/jupyter-book).

**Comment by kennysong** [comment]
+1. Is this being planned for VSCode Jupyter or the new native notebook integration?

**Comment by DavidKutu** [comment]
Once we are ready to roll out the new notebook for everyone, we'll come back to adding more features like this one.

**Comment by tsuga** [comment]
FYI, a workaround is mentioned in #1182
https://github.com/microsoft/vscode-jupyter/issues/1182#issuecomment-840762264

**Comment by saldroubi** [comment]
Please add this feature soon. The workaround, jupyter power tools, does not work with latest vs code insider.

**Comment by jonyzambrano01** [comment]
+1!

**Comment by mhorlacher** [comment]
Is this implemented yet? Would be very useful for [papermill](https://papermill.readthedocs.io/en/latest/usage-parameterize.html)!

**Comment by torext** [comment]
This seems like pure user interface work, so hoping this won't be pushed out for much longer.

**Comment by ADN8B** [comment]
+1 
It would be great if you could add cell tags in Vscode.

**Comment by tarunn90** [comment]
+1!

**Comment by PaleNeutron** [comment]
I need tags!

**Comment by JamesIgoe** [comment]
would be helpful, yes...

**Comment by rezan21** [comment]
Meanwhile, I've created a script which can automate adding certain tags, e.g. "parameters" for papermill, to a notebook. It requires an indicator comment. (by default, it looks for _the first occurrence_ of "default param".) You'd need to add the indicator as a comment to the cell you wish to add the tag to.

```python
import json


def add_tag_to_nb(nb_path: str, tag: str = "parameters", indicator: str = "default param"):
    # read notebook
    with open(nb_path) as file:
        nb = json.load(file)

    for i, cell in enumerate(nb["cells"]):
        cell_text = "".join(cell["source"])
        # find first cell with the indicator
        if indicator in cell_text:
            cell["metadata"]["tags"] = cell["metadata"].get("tags", [])  # existing tags
            if tag not in cell["metadata"]["tags"]:
                cell["metadata"]["tags"].append(tag)  # add tag
            break
    else:
        print(f"{indicator} not found in {nb_path}!")
        return None

    nb["cells"][i] = cell
    # save
    with open(nb_path, "w") as file:
        json.dump(nb, file)

```

**Comment by rebornix** [comment]
Hi all, thank you for the suggestion and all your feedbacks! We published a new extension **Jupyter Cell Tags** https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-cell-tags to the marketplace which you can play around with today. The extension will be available through Jupyter extension pack later.

With this extension, you should be able to mark a cell as papermill parameters, or insert a new random tag from the cell toolbar 

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/876920/191581198-3bd107b8-4003-40b9-b444-f0922cc7a553.png">

Once a tag is added to a cell, it will be rendered in the cell status bar so you can delete them with ease 

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/876920/191581533-4f4e5218-e49b-4bf4-8f58-cbbd2fa95be0.png">

You can add new cell tags through status bar item **+ Tag** as well 

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/876920/191581660-53e1b311-8a25-4aac-99ea-ff3b81c5248d.png">

---

Give it a try and feel free to share your thoughts on how it works and what else we can do to improve the tag editing experience.

**Comment by mertgoksel** [comment]
Cannot edit cell tags in R kernel. The editor doesnt open.
