### ISSUE TITLE
Support opening a notebook with a specific Kernel

### ISSUE THREAD

**Issue by jruales** [microsoft/vscode-jupyter#11220]
## Environment data

-   VS Code version: 1.71.0-insider (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2022.8.1002431052 (pre-release)
-   Python Extension version (available under the Extensions sidebar): v2022.13.12411009 (pre-release)
-   OS (Windows | Mac | Linux distro) and version: Windows 11 Enterprise
-   Python and/or Anaconda version: Anaconda with Python 3.8.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda env
-   Jupyter server running: Local / Conda

## Expected behaviour

When I create a new (untitled) notebook, I should be able to make it connect to a specific kernel.

## Actual behaviour
Currently, it's ignoring the `kernelspec`, `language_info`, and `vscode.interpreter.hash` info that I'm setting in the metadata, even though I'm verifying that these properties are actually in the ipynb when I save it.

## Steps to reproduce:

The following code should have connected to the specified kernel but the kernel information was not taken into consideration when choosing the default kernel of the notebook.
```ts
/**
 * Creates an untitled new Jupyter Notebook in VS Code with a single cell with the given contents and language.
 * @param cellContents The code that will go in the code cell of the produced notebook.
 * @param cellProgrammingLanguage The language to be used for syntax highlighting and intellisense in the generated notebook. For example "python". It needs to be a valid language name for Monaco.
 * @returns A promise to a vscode.NotebookDocument object
 */
async function exportToNotebook (
    cellContents: string,
    cellProgrammingLanguage: string = "python",
    showNotebook = true
): Promise<vscode.NotebookDocument> {
    const notebookData = new vscode.NotebookData([
        new vscode.NotebookCellData(vscode.NotebookCellKind.Code, cellContents, cellProgrammingLanguage)
    ]);
    notebookData.metadata = {
        custom: {
            metadata: {
                kernelspec: {
                    display_name: "Python 3.8.12 ('base')",
                    language: "python",
                    name: "python3"
                },
                language_info: {
                    codemirror_mode: {
                        name: "ipython",
                        version: 3
                    },
                    file_extension: ".py",
                    mimetype: "text/x-python",
                    name: "python",
                    nbconvert_exporter: "python",
                    pygments_lexer: "ipython3",
                    version: "3.8.12"
                },
                vscode: {
                    interpreter: {
                        hash: "ad2bdc8ecc057115af97d19610ffacc2b4e99fae6737bb82f5d7fb13d2f2c186"
                    }
                }
            }
        }
    };
    const doc = await vscode.workspace.openNotebookDocument("jupyter-notebook", notebookData);

    if (showNotebook) {
        await vscode.window.showNotebookDocument(doc, {
            viewColumn: vscode.ViewColumn.Beside
        });
    }
    return doc;
}

exportToNotebook("print('Hello, world!')")
```

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
info 20:6:1.171: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 20:6:1.177: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 20:6:1.177: Find preferred kernel for Untitled-1.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"python"}} & preferred interpreter c:\Users\REDACTED\AppData\Local\Microsoft\WindowsApps\python3.9.exe
info 20:6:1.178: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 20:6:1.178: Preferred kernel .jvsc74a57bd0111469083a2139fa0b94c1d63b9e9729a9ede9d6e4b098abbd86e93baea06861.c:\Users\REDACTED\AppData\Local\Microsoft\WindowsApps\python3.9.exe.c:\Users\REDACTED\AppData\Local\Microsoft\WindowsApps\python3.9.exe.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, [object Object], false, false)
info 20:6:1.178: PreferredConnection: .jvsc74a57bd0111469083a2139fa0b94c1d63b9e9729a9ede9d6e4b098abbd86e93baea06861.c:\Users\REDACTED\AppData\Local\Microsoft\WindowsApps\python3.9.exe.c:\Users\REDACTED\AppData\Local\Microsoft\WindowsApps\python3.9.exe.-m#ipykernel_launcher found for NotebookDocument: Untitled-1.ipynb
```

</p>
</details>

**Comment by jruales** [comment]
Just for more context, the scenario is the following:

We have an extension that is using a Jupyter extension API to provide us with a list of kernels. Our extension connects to one of them that the user chooses. Then at some point, the user has the ability to export their work as a Jupyter Notebook that is opened as an untitled notebook in a new editor, and we want to make sure that this notebook is connected to the same compute as the one our extension was connected to. This way, the user won't have to go through the kernel selection process twice.

**Comment by jruales** [comment]
@IanMatthewHuff is there any update on this? Is it something that could be addressed?

**Comment by DonJayamanne** [comment]
@jruales is this still an issue with the latest version of the pre-release version of the Jupyter extension.
Please install the latest vscode insiders and pre-releaes versions of the Juptyer and Python extensions.
let me know if the issue still exists

**Comment by jruales** [comment]
@DonJayamanne I'm still seeing the issue, even with the latest pre-release version of both the Jupyter and the Python extensions

**Comment by DonJayamanne** [comment]
>  I can set up a meeting if you would like to see what I'm doing

Yes please

**Comment by jruales** [comment]
@rebornix why was this item moved to Backlog? I thought it was targeted for February?

**Comment by DonJayamanne** [comment]
Closing in favour of https://github.com/microsoft/vscode-jupyter/issues/13251#issuecomment-1495190529
