### ISSUE TITLE
Export to HTML prompts for Python kernel, then fails

### ISSUE THREAD

**Issue by olguzzar** [microsoft/vscode-jupyter#11228]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

While running through the golden scenario, I attempted to export the notebook to an HTML file. 

Expected:
After clicking export to HTML, I am prompted to specify a file name. After entering one, the exported HTML file is then generated. 

Actual:
After clicking export to HTML, I was prompted to specify a file name. After entering one, I was then prompted to specify a Python kernel. After selecting my current kernel (the golden scenario conda env), I received the error "Running cells with python 3.7.13 ('golden_scenario_env') requires notebook package."
I then tried again, and was not prompted to select a Python kernel, and the HTML file was then correctly generated.

I don't believe I should have been prompted to select a Python kernel at all. Recording here: https://msit.microsoftstream.com/video/79a60840-98dc-a27a-e9b5-f1ed287bbe75?st=1212

### VS Code Version

Version: 1.70.2 (user setup) Commit: e4503b30fc78200f846c62cf8091b76ff5547662 Date: 2022-08-16T05:35:13.448Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Windows_NT x64 10.0.22000

### Jupyter Extension Version

v2022.7.1102252217

### Anaconda Version (if applicable)

conda 4.12.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
@olguzzar I am very sorry for missing this issue. looks like we came across this issue much later.
I guess you have managed to get this working.
I do apologize for the late reply.
If this still exists, plese do let us know. and we'll be happy to re-open this, or feel free to create a new issue
