### ISSUE TITLE
Running a Python Program in Visual Studio Code Using Jupyter Notebook Extension Consumes C Drive Storage

### ISSUE THREAD

**Issue by DanielSoenarto** [microsoft/vscode-jupyter#11222]
I have a 2 drives on my laptop (HDD and SSD). My SSD is around 128 Gb.

Currently I'm doing a Python project in signal processing using a library/module called WFDB. The dataset is pretty large (around 1.6 Gb).

I don't know why every time I run a code which looped all the signals and filter, stacking those into new variables, it consumes my C drive like crazy. When I closed it, the memory of the C drive doesn't come back. Does anybody know what's wrong with this and how to fix it?

**Comment by DonJayamanne** [comment]
Thanks for filing this issue,
I don't quite understand the problem.

> onsumes my C drive like crazy. When I closed it, the memory of the C drive doesn't come back. 

Is the problem that memory is being used or the C drive disc space is being used. 
They are two different things. Hence the question.

Also, please could you share a screenshot of the problem along with the following information:

* What version of Python and environment type are you using
* Output from the `Jupyter` output panel (go into the command palette and select `Jupyter: Show Outpu` and copy all of the output into this issue so we have more information)

**Comment by DanielSoenarto** [comment]
@DonJayamanne Hi, I have found the fix to the problem. I have cleanly deleted all files and folders related to VS Code. It seems that my memory is too small for storing all the variables in the program. Hence, it consumed my C drive storage because the arrays are bigger than my RAM. 

Sorry for the trouble, it's mainly because the dataset is too large.

**Comment by DonJayamanne** [comment]
thanks for getting back
