### ISSUE TITLE
not able to start jupyter notebook imported into python using wsl when running as the root user

### ISSUE THREAD

**Issue by matthewchung74** [microsoft/vscode-jupyter#1124]
## Environment data

- VS Code version: 1.38.1
- Extension version (available under the Extensions sidebar): Python 2019.9.34911
- OS and version: windows 10.0.17763
- Python version (& distribution if applicable, e.g. Anaconda): python 3.7.3 conda 4.7.12
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Relevant/affected Python packages and their versions: XXX
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): jedi, but happens both ways

## Actual behaviour

run cell for this 
```
#%%
import os
```
gives 
```
Executing code failed : Error: Jupyter server crashed. Unable to connect. Error code from jupyter: 1
```

## Steps to reproduce:
1. open wsl
2. launch conda environment
3. open vscode
4. create .py file with 
```
#%%
import os
```
5. run cell

see error message

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
cwd: /mnt/c/Users/matt/Documents/code/course-v3/nbs/dl-me
##########Linting Output - pylint##########
> ~/anaconda3/bin/python -m jupyter kernelspec list
> ~/anaconda3/bin/python -m jupyter kernelspec list
> ~/anaconda3/bin/python -m jupyter notebook --no-browser --notebook-dir=/tmp/fe814943-4e41-421f-b230-8b5c217dbebe --config=/tmp/fe814943-4e41-421f-b230-8b5c217dbebe/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> ~/anaconda3/bin/python -m jupyter kernelspec list
> ~/anaconda3/bin/python -m jupyter kernelspec list
> ~/anaconda3/bin/python -m jupyter notebook --no-browser --notebook-dir=/tmp/ccb8d822-bb60-48d3-9f12-937035982aa7 --config=/tmp/ccb8d822-bb60-48d3-9f12-937035982aa7/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
```
![console](https://user-images.githubusercontent.com/1685700/65547896-39c02100-decf-11e9-8e5b-fba663253e6d.png)

i wasn't able to find `Enable source map support for extension debugging` advice?
```

I'm able to get this working on my mac but would love it on my PC for the GPU.

**Comment by Qiuzhuang** [comment]
> instructions

this fixed issue with root remote connection to start jupyter via vscode.

**Comment by Qiuzhuang** [comment]
> i just generated a new log which is here. https://gist.github.com/foobar8675/87bd0d2f2047840ed500af0f3fbf6e9f and noticed one line that looked suspicious.
> 
> ```
> console.ts:137 [Extension Host] Info Python Extension: 2019-09-25 21:37:31: [C 22:37:31.404 NotebookApp] Running as root is not recommended. Use --allow-root to bypass.
> ```
> 
> so i ran this with the following output
> 
> ```
> (base) root@DESKTOP-LFEDEL2:/mnt/c/Users/matt/Documents/code/course-v3/nbs/dl-me# ~/anaconda3/bin/python -m jupyter notebook --no-browser --notebook-dir=/tmp/f0c16a0f-1292-46e5-af9a-b33f32c9b3ee --NotebookApp.iopub_data_rate_limit=10000000000.0
> [I 22:43:34.730 NotebookApp] JupyterLab extension loaded from /root/anaconda3/lib/python3.7/site-packages/jupyterlab
> [I 22:43:34.731 NotebookApp] JupyterLab application directory is /root/anaconda3/share/jupyter/lab
> [C 22:43:34.733 NotebookApp] Running as root is not recommended. Use --allow-root to bypass.
> ```
> 
> then ran this
> 
> ```
> (base) root@DESKTOP-LFEDEL2:/mnt/c/Users/matt/Documents/code/course-v3/nbs/dl-me# ~/anaconda3/bin/python -m jupyter notebook --no-browser --notebook-dir=/tmp/f0c16a0f-1292-46e5-af9a-b33f32c9b3ee --NotebookApp.iopub_data_rate_limit=10000000000.0 --allow-root
> [I 22:44:30.968 NotebookApp] JupyterLab extension loaded from /root/anaconda3/lib/python3.7/site-packages/jupyterlab
> [I 22:44:30.969 NotebookApp] JupyterLab application directory is /root/anaconda3/share/jupyter/lab
> [I 22:44:30.970 NotebookApp] Serving notebooks from local directory: /tmp/f0c16a0f-1292-46e5-af9a-b33f32c9b3ee
> [I 22:44:30.970 NotebookApp] The Jupyter Notebook is running at:
> [I 22:44:30.970 NotebookApp] http://127.0.0.1:8888/?token=2bde53de571d92fb6fc75075c91e7eb5c77713cf27dde706
> [I 22:44:30.971 NotebookApp]  or http://127.0.0.1:8888/?token=2bde53de571d92fb6fc75075c91e7eb5c77713cf27dde706
> [I 22:44:30.971 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [C 22:44:30.976 NotebookApp]
> 
>     To access the notebook, open this file in a browser:
>         file:///root/.local/share/jupyter/runtime/nbserver-1005-open.html
>     Or copy and paste one of these URLs:
>         http://127.0.0.1:8888/?token=2bde53de571d92fb6fc75075c91e7eb5c77713cf27dde706
>      or http://127.0.0.1:8888/?token=2bde53de571d92fb6fc75075c91e7eb5c77713cf27dde706
> ```
> 
> which seemed ok. so i tweaked my `jupyter_notebook_config.py` to the following https://gist.github.com/foobar8675/583a49ddb027cd9e4e7ee0d347111eaf and in vscode, turned off
> 
> ![snip](https://user-images.githubusercontent.com/1685700/65662162-59973800-dfe8-11e9-895b-cb73b682e829.png)
> 
> and it seemed to work!
> 
> Did I miss something in the instructions about not using a root user?

this fixed issue with root remote connection to start jupyter via vscode

**Comment by DonJayamanne** [comment]
@Qiuzhuang sorry for not getting back to you on this. wanted to check if this is still unresolved?

**Comment by Qiuzhuang** [comment]
Yes, this is working perfectly now. Thank you.
