### ISSUE TITLE
Flaky test: Run By Line: Run a second time after interrupt

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#11245]
1) VSCode Notebook - Run By Line
       Run a second time after interrupt:

      Error: Print during time loop is not working
      + expected - actual

      at Timeout.<anonymous> (src/test/common.ts:59:20)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

https://github.com/microsoft/vscode-jupyter/runs/8121269645?check_suite_focus=true

**Comment by roblourens** [comment]
Log seems to show that debugging broke, we are sending stepIn but never stopping. The DA only sends "continued" events.

**Comment by roblourens** [comment]
And https://github.com/microsoft/vscode-jupyter/runs/8109923123?check_suite_focus=true

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-jupyter/issues/7611 (for upstream debugpy issue)
