### ISSUE TITLE
kernel connection failures causing CI test failures for Windows

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#11273]
Perf and smoke tests are failing pretty often on Windows, sometimes one of the integration tests as well.
I got a local repro on my first attempt for the perf test but didn't happen again.

Screenshot shows that it's stuck on connecting to the kernel

![Can_restart_a_kernel_after_it_dies_c9385224a0_1-screenshot](https://user-images.githubusercontent.com/2019016/188234558-755c07e6-0dd4-46f5-a34b-acaa318bbf9d.png)

**Comment by roblourens** [comment]
Maybe this is the same thing?

https://github.com/microsoft/vscode-jupyter/runs/8259365822?check_suite_focus=true

**Comment by DonJayamanne** [comment]
> Screenshot shows that it's stuck on connecting to the kernel

When this happens can you share some logs, else its difficult to tell what's going on or what failed?
Do you see any errors in the consolel window that would indicate what went' wrong?

Please ensure you have `verbose` logging turned on

**Comment by amunger** [comment]
This only happened once locally, so I don't have a repro. CI jobs were failing pretty regularly so that's a good source of logs if it fails again there

**Comment by amunger** [comment]
here's a couple of recent smoke test failures in CI, not sure if it's the same cause because they don't have screenshots

https://github.com/microsoft/vscode-jupyter/actions/runs/3040335269/attempts/1
https://github.com/microsoft/vscode-jupyter/actions/runs/3019371579/jobs/4855271396

**Comment by amunger** [comment]
Looks like the same issue occurred here https://github.com/microsoft/vscode-jupyter/actions/runs/3058653938/jobs/4935110389

[TestLogs-raw-nonConda-3.10---windows-latest.zip](https://github.com/microsoft/vscode-jupyter/files/9578083/TestLogs-raw-nonConda-3.10---windows-latest.zip)

**Comment by DonJayamanne** [comment]
Should be fixed now
