### ISSUE TITLE
Don't show unclickable links in dialogs

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#11285]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/4674940/188328541-be478c6d-a878-46b8-94b5-b86ee7da4637.png">

We usually show "Learn more..." buttons instead.

**Comment by IanMatthewHuff** [comment]
Validation notes:

This is for a server error with the web extension. You need to be running web, and then you can just try to connect to a junk server name to test it.

The UI varies a bit based on if you are on the kernel picker experiment or not. I've fixed both scenarios.

With `jupyter.showOnlyOneTypeOfKernel` on, the modal dialog shown above will be replaced with a non-modal error dialog with different wording. With that value false you will get a general server connected error in the validation box, and a non-modal error that gives information specific to the web failure connection case.
