### ISSUE TITLE
`Jupyter: Run Cell` can be confused with `Notebook: Execute Cell` shortcut

### ISSUE THREAD

**Issue by kolibril13** [microsoft/vscode-jupyter#11283]
I wanted to redefine the Keybinding to run a single cell, and searched in Shortcuts for `Run Cell` which showed me `Jupyter: Run Cell` and `Jupyter: Run Current Cell`.
However, the command I needed in the end was `Notebook: Execute Cell`. 
This is a bit confusing and took me a bit of time to figure out.
To avoid this confusion for other users, is it possible to remove  `Run Cell` and `Jupyter: Run Current Cell` from the Shortcut commands? For me, these two latter commands did not have any effect when called.

## Environment data

-   VS Code version: 1.71.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.8.1002431955
-   Python Extension version (available under the Extensions sidebar): v2022.14.0
-   OS (Windows | Mac | Linux distro) and version: MacOS, latest
-   Python and/or Anaconda version: 3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Jupyter server running: Local

**Comment by amunger** [comment]
thanks for the issue. It looks like `jupyter: run cell` is used by the code lenses for python scripts in the Interactive Window, but doesn't have any effect when called directly so it should be removed from the keyboard shortcuts as you suggested

**Comment by amunger** [comment]
turns out we can't hide commands from the keyboard shortcuts menu, and the confusion between commands should be covered by https://github.com/microsoft/vscode-jupyter/issues/6626.
