### ISSUE TITLE
Vega plots rendered in VS Code are not aware of the themes

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#11292]
Whether we're using dark or light them, the plot is still a light styled plot.
In JLab it changes based on the theme.
Should we change this, what if user want the old light style plots even in dard vscode themes?

**Comment by DonJayamanne** [comment]
Fixed, this should now work.
### Note: vega supports light and dark themes, hence if you use light or dark themes, the vega output will change accrodingly.

**Testing instructions:**
* Install latest VS Code Insiders, Jupyter pre-release and Notebook renderers extension
* Install the following python packages
```pip install altair, vega, vega-datasets```
* Run a cell in a notebook with light theme
```python
import altair as alt
from vega_datasets import data

# Show an image where the interactive plot is not supported
alt.renderers.enable('mimetype')

source = data.cars()

alt.Chart(source).mark_boxplot().encode(
    x='Origin',
    y=alt.Y(alt.repeat('column'), type='quantitative'),
).repeat(column=['Horsepower', 'Weight_in_lbs'])
```
* Change the theme and run the previous cell again
* Run a cell in a notebook with light theme
```python
from IPython.display import display

display({
    "application/vnd.vegalite.v3+json": {
        "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
        "description": "A simple bar chart with embedded data.",
        "data": {
            "values": [
                {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
                {"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
                {"a": "G", "b": 19}, {"a": "H", "b": 87}, {"a": "I", "b": 52}
            ]
        },
        "mark": "bar",
        "encoding": {
            "x": {"field": "a", "type": "ordinal"},
            "y": {"field": "b", "type": "quantitative"}
        }
    }
}, raw=True)
```
* Change the theme and run the previous cell again

**Comment by joelostblom** [comment]
@DonJayamanne Is it possible to use a light theme for vegalite/altair when the dark theme is enabled in VS Code? This is a quite important use case since it allows you to see what the plot would look like for others outside the editor. It seems like setting it back to "default" does not work and it is still dark:

![image](https://user-images.githubusercontent.com/4560057/195917155-9076f719-c749-4d9c-ac55-116dc64ecc05.png)


Also see https://github.com/vega/vega-themes/issues/413

**Comment by DonJayamanne** [comment]
please could you file a separate feature request.

**Comment by joelostblom** [comment]
@DonJayamanne Follow up here https://github.com/microsoft/vscode-jupyter/issues/11670
