### ISSUE TITLE
Vega, Plotly & Altair renderers generate image outputs and add that to ipynb

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#11293]
* Execution creates a JS output
* IPynb now has JS output.
* Renderer generates an image output 
* Renderer then adds this image output to the list of outputs
* IPynb saved now has JS + image output.

Upon re-loading the notebook, Jupyter ends up loading the image.

**Pros:**
* This can be shared and image is loaded and displayed, even in github
* This is how jupyter (notebook/lab) works today

**Cons**
* If we changed to this behaviour, users loose out on the interactive nature of the plots.

**Note:**
Once https://github.com/microsoft/vscode-jupyter/issues/11218 is fixed, we don't need to do this, however this ensures the file can be opened on github or the like. 
Also this ensures we're consistent with Jupyter.

**Comment by DonJayamanne** [comment]
Plotly does the same thing
Hence useful for opening notebooks with plotly and falling back to the image.

**Comment by joelostblom** [comment]
Related to this is that in altair we rely on this to save an image for display on e.g. GitHub via `alt.renderers.enable('mimetype')`, and this is not working if the notebook is run in vs code instead of jupyterlab

**Comment by DonJayamanne** [comment]
Closing this issue as no one else has reported this.
