### ISSUE TITLE
"Initial Notebook Cell Execution Perf Test" flaky

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#11303]
Saw this test fail multiple times recently

https://github.com/microsoft/vscode-jupyter/runs/8213023011?check_suite_focus=true
https://github.com/microsoft/vscode-jupyter/runs/8165563331?check_suite_focus=true
https://github.com/microsoft/vscode-jupyter/runs/8166064024?check_suite_focus=true

**Comment by amunger** [comment]
pretty sure this has the same root issue as the smoke test, it's just timing out connecting to the kernel. Dupe of https://github.com/microsoft/vscode-jupyter/issues/11273
