### ISSUE TITLE
winapi module not found

### ISSUE THREAD

**Issue by NovarisOberion** [microsoft/vscode-jupyter#11310]
## Environment data

-   VS Code version: 1.70.1 (portable installation, local data/ folder)
-   Jupyter Extension version (available under the Extensions sidebar): v2022.8.1002431052
-   Python Extension version (available under the Extensions sidebar): v2022.14.0
-   OS (Windows | Mac | Linux distro) and version: Win7 & Win10
-   Python and/or Anaconda version: 3.7.0 & 3.9.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

VSCode starts and jupyter notebook cells are evaluated

## Actual behaviour

Extension hangs at "connecting to kernel: .... Activating...."
Error log in Jupyter output log: winapi module not found

## Steps to reproduce:

1. Have a local portable installation of VSCode
2. Start VSCode
3. Open a jupyter notebook
4. Try to connect to the local server and run a cell

## Logs

info 23:41:46.685: Process Execution: cwd: p:\vscode\Code\data\extensions\ms-toolsai.jupyter-2022.8.1002431052\pythonFiles\vscode_datascience_helpers
cwd: p:\vscode\Code\data\extensions\ms-toolsai.jupyter-2022.8.1002431052\pythonFiles\vscode_datascience_helpers
warn 23:41:46.836: Traceback (most recent call last):
  File "p:\vscode\Code\data\extensions\ms-toolsai.jupyter-2022.8.1002431052\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py", line 13, in <module>
    import winapi
ModuleNotFoundError: No module named 'winapi'

## Workaround

In order to avoid the error and have the extension work properly I had to append the local path to the sys.path before the import of winapi:

+ import sys
+ sys.path.append('')
import winapi

it seems when invoking the script using python the local folder is not automatically added to the search path. print(sys.path) did not contain ''.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
Out of curiosity what kind of a Python environment are you using?
`winapi` should exist in the Python envionrment and not necessarily in the workspace folder.
The above code thats runnign `kernel-interrupt_daemon` should not have to add the current working folder into `syspath`

**Please could you:**
* Send all of the output from `Jupyter` output panel
* What is the name of the worksapce folder and where is the Python environment with respect to the python environment.

**Comment by NovarisOberion** [comment]
I tried installing winapi using pip but even then it did not work. I then found that there is a copy of winapi inside the kernel-interrupt_daemon so I tried to find a way to include this one in the project

As for the environment, on this machine I am using some kind of a portable version, I unpacked it on a usb stick and use a script file to first set the paths and environment variables and then invoke vscode

**Comment by NovarisOberion** [comment]
Log file:
[jupyter.log](https://github.com/microsoft/vscode-jupyter/files/9501993/jupyter.log)
 
Python is located in a folder next to vscode, you can see it in the log: P:/vscode/codedata/binaries/python. Both python and the scripts subfolder are on the PATH environment variable

**Comment by NovarisOberion** [comment]
maybe to add: 
if I run "python -m pip install winapi" I get the following response:
Collecting winapi
  Using cached winapi-0.0.0-py3-none-any.whl (2.0 kB)
Installing collected packages: winapi
Successfully installed winapi-0.0.0

However, the sites-packages folder only contains a "winapi-0.0.0.dist-info" folder without any .py files in it. No winapi folder is created.
