### ISSUE TITLE
Ship our own Jupyter to eliminate configuration problems

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1131]
We've had tons of issues related to people not having jupyter configured correctly (examples):
https://github.com/microsoft/vscode-python/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22data+science%22+tornado
(as of this bug there were 18 issues just with tornado configuration).

We should ship our own jupyter to eliminate these issues. We can have the latest greatest all the time and use this to make sure we can install our own kernels.

**Comment by davidanthoff** [comment]
I think from our (Julia) point of view it would be great if this was somehow only triggered if a user is using Jupyter Notebooks with Python, i.e. if this was entirely skipped in a scenario where a user is installing the Jupyter extension to work with Julia Jupyter notebooks. We are converging on a _very_ nice integration in https://github.com/julia-vscode/julia-vscode/pull/980 that is completely zero-config, zero-install for the Julia scenario. If we could keep this Julia scenario in a state that nothing Python gets triggered or installed on a user system, that would be great.

**Comment by DonJayamanne** [comment]
Closing this issue for now, as we haven't got any plans for this yet.
