### ISSUE TITLE
Latex math rendering

### ISSUE THREAD

**Issue by kklot** [microsoft/vscode-jupyter#11316]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Latex expressions display OK in markdown file, but not in markdown cell of `.ipynb`.

### VS Code Version

Version: 1.71.0 Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c Date: 2022-09-01T07:25:38.437Z (6 days ago) Electron: 19.0.12 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Darwin x64 21.6.0 Sandboxed: No

### Jupyter Extension Version

v2022.9.1002511105

### Coding Language and Runtime Version

R

### Language Extension Version (if applicable)

4.0

### Running Jupyter locally or remotely?

Local

**Comment by IanMatthewHuff** [comment]
@kklot Thanks for filing. Could you please give an example of the behavior that you are seeing? Right now this issue doesn't really have enough information for us to push a fix. A snipped that works correctly in a markdown file and not in .ipynb would be the best help.

**Comment by kklot** [comment]
Thanks for the response, to reproduce:

1.  Create a markdown file, and type $a$, then open preview we can see 
![Screenshot 2022-09-07 at 18 20 10](https://user-images.githubusercontent.com/4459378/188929496-3bf2b153-2b65-4e78-abf9-9c7c3cf2eee7.png)
2. Create a notebook, make a markdown cell and type $a$, render it we see
![Screenshot 2022-09-07 at 18 22 09](https://user-images.githubusercontent.com/4459378/188929857-59af4d23-9747-48e9-aeaa-0c33d82c2f40.png)

**Comment by IanMatthewHuff** [comment]
@kklot Hmmm, this currently isn't the behavior that I repro. Currently when I'm editing the markdown cell it looks like this:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/812783/188931714-6fbc4f98-f0b5-44f4-ab53-4ff953bc96fc.png">
And when I commit the cell (exiting edit mode) it correctly formats it.
<img width="336" alt="image" src="https://user-images.githubusercontent.com/812783/188931834-dd7c7d8e-5b92-418f-a7ce-0ca9827364e6.png">

Trying to figure out what might be causing the rendering that you are seeing. Does this issue still repro if you only enable the Jupyter extension? Wondering if another installed extension might be interfering.

**Comment by kklot** [comment]
Ach! this has been annoying for weeks now. I reload with all extension disabled, quit, and load them all again and it works now!! I have tried to quit and restart VSCode several times before but did not think about reloading the extensions.

Thanks a lot @IanMatthewHuff
