### ISSUE TITLE
Flaky kernel listing test

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#11324]
162 passing (13m)
  121 pending
  1 failing

  1) DataScience - VSCode Notebook - (Remote Execution)
       Local and Remote kernels are not listed:
     AssertionError: Should have at least one remote kernelspec: expected false to be truthy
      at Context.<anonymous> (src/test/datascience/notebook/remoteNotebookEditor.vscode.test.ts:170:16)

https://github.com/microsoft/vscode-jupyter/runs/8236545562?check_suite_focus=true

**Comment by DonJayamanne** [comment]
Looks like this applies to the kernel UI changes (i.e. type of the kernel picker thats displayed), hence assigning to @IanMatthewHuff 
```await changeShowOnlyOneTypeOfKernel(true);```

**Comment by DonJayamanne** [comment]
fixed in latest main

**Comment by connor4312** [comment]
Marking as verified, please unverify if you've seen this again...
