### ISSUE TITLE
Python interactive window data Viewer bug

### ISSUE THREAD

**Issue by linyu0219** [microsoft/vscode-jupyter#1134]
When use the DataViewer to look the variables,
if the variable is a type of pandas.DataFrame and the columns has same column names , like all the columns name is 0, as [0,0,0,0]
the dataVierer will show the first 0 column in orther 0 columns.

**Comment by IanMatthewHuff** [comment]
Doing the old bug pass I still see this issue, moving to triage as it feels like a problem.

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1134
