### ISSUE TITLE
Don't focus last cell if I run a different cell

### ISSUE THREAD

**Issue by CoenraadS** [microsoft/vscode-jupyter#11347]
## Environment data

-   VS Code version: 1.71.0
-   Jupyter Extension version: 2022.8.1002431955
-   Python Extension version: v2022.14.0
-   OS version: Windows 10
-   Python version: 3.9.13
-   Type of virtual environment used: venv
-   Jupyter server running: **Local**

## Expected behaviour

When I click `Run Cell`, I do not expect editor to scroll. (Ctrl + Enter works fine!)

## Actual behaviour

Editor scrolls away

## Steps to reproduce:

1. I attached the file I see this behavior in
[example.py.txt](https://github.com/microsoft/vscode-jupyter/files/9539921/example.py.txt)

![Animation](https://user-images.githubusercontent.com/5593825/189477319-0ed423a2-d44a-445a-ac91-c00f0bc8daac.gif)

**Comment by amunger** [comment]
thanks for filing an issue. I agree that this scrolling doesn't really feel necessary

**Comment by amunger** [comment]
there is actually an existing setting to disable this: jupyter.enableAutoMoveToNextCell
