### ISSUE TITLE
Interactive window doesn't start kernel in Remote-WSL

### ISSUE THREAD

**Issue by step4** [microsoft/vscode-jupyter#11340]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When I try to start an interactive window, the editor splits but the window stays empty.
I use the Remote WSL extension to work on the projects in my subsystem.

I assumed maybe it has something to do with the experiments (A/B testing) like in #11003 but I can't disable them with remote wsl.

![image](https://user-images.githubusercontent.com/11348121/189354882-d2a2f0aa-6a11-4933-96cb-e1c30d535103.png)

also the extensions page says the extension is running on wsl:

![image](https://user-images.githubusercontent.com/11348121/189354287-0ad23071-d661-4492-bd22-fca4c6eec882.png)

Is there another way to troubleshoot this?

### VS Code Version

1.71.0 

### Jupyter Extension Version

2022.8.1002431955

### Jupyter logs

```shell
Visual Studio Code (1.71.0, wsl, desktop)
Jupyter Extension Version: 2022.8.1002431955.
Python Extension Version: 2022.14.0.
Multiple Workspace folders opened <redacted>
info 14:50:43.90: ZMQ install verified.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 14:50:43.995: LSP Notebooks experiment is enabled
info 14:50:44.764: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 14:50:45.190: Starting interactive window for resource '/home/c/warranty/extract_labels.py'
info 14:50:45.806: Process Execution: > ~/miniconda3/envs/w/bin/python -m pip list
> ~/miniconda3/envs/w/bin/python -m pip list
error 14:50:50.51: No remote controllers
info 14:50:50.281: Preferred Remote kernel for Interactive-1.interactive is undefined
error 14:50:50.282: No remote controllers
```

### Coding Language and Runtime Version

Python 3.8.13

### Language Extension Version (if applicable)

Python Extension Version: 2022.14.0

### Anaconda Version (if applicable)

conda 4.10.3

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
can you try to explicitly set the python interpreter before opening the Interactive window with the command `Python: Select Interpreter` (is there an interpreter available?). I've seen something similar when we just don't know which interpreter to use.

**Comment by step4** [comment]
Sure I did.
I could select all my conda env interpreters and also the system one.
But the problem is still there regardless which interpreter I choose.

**Comment by step4** [comment]
I reinstalled VS Code completely in my WSL by deleting the `.vscode-server` folder in my home folder.
After installing all extensions again it solved the problem.
