### ISSUE TITLE
ScenePic visualizations do not display in VS Code

### ISSUE THREAD

**Issue by matajoh** [microsoft/vscode-jupyter#11366]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I loaded [this Jupyter notebook](https://github.com/microsoft/scenepic/blob/main/python_examples/getting_started.ipynb) and ran the first cell. Nothing showed up. The same cell produces a ScenePic animation when viewed in Jupyter or JupyterLab.

### VS Code Version

Version: 1.71.0 (user setup) Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c Date: 2022-09-01T07:36:10.600Z Electron: 19.0.12 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10.0.22000 Sandboxed: No

### Jupyter Extension Version

 v2022.8.1002431955

### Jupyter logs

```shell
info 23:1:53.761: Execute Cell 0 c:\Source\scenepic\python_examples\getting_started.ipynb
info 23:1:54.184: Cell 0 executed with state Success
```

### Coding Language and Runtime Version

Python v3.9.13

### Language Extension Version (if applicable)

v2022.14.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Made some progress, however only one output gets rendered, others still fail.
Still WIP
Partially related to https://github.com/microsoft/vscode-jupyter/issues/11218

![image](https://user-images.githubusercontent.com/1948812/190541359-b01964f9-b0c8-47ec-bbb4-bf10d491bef9.png)
[scenpic1.zip](https://github.com/microsoft/vscode-jupyter/files/9580066/scenpic1.zip)

**Comment by DonJayamanne** [comment]
Made some more progress

![Screen Shot 2022-09-16 at 13 10 39](https://user-images.githubusercontent.com/1948812/190548756-3d6272b0-6339-46c0-b147-f0471e940ab1.png)

**Comment by DonJayamanne** [comment]
Blocked by https://github.com/microsoft/vscode-jupyter/issues/11218, https://github.com/microsoft/vscode/issues/160965

**Comment by matajoh** [comment]
Amazing progress @DonJayamanne! Thanks for looking into this. Anything I can do to help support this effort?

**Comment by DonJayamanne** [comment]
>  Anything I can do to help support this effort?

Not much, however once we get this working we'll need to look into the ordering issue.
I've reported this issue here with details https://github.com/microsoft/scenepic/issues/48

**Comment by matajoh** [comment]
I've fixed the rendering issue, and at least locally everything seems to be working fine. Thanks again for your help! Does it look good to you as well with the latest version (1.0.16)?

**Comment by DonJayamanne** [comment]
@matajoh please could you test this at your end, 
* Please install the latest insider version of VS Code
* Install the latest pre-release versions of the Jupyter and Python extensions

Optionally wait for the new versions to be relased some time this week.
