### ISSUE TITLE
Discovering Installed Python Location is incorrect on my Arm64 device

### ISSUE THREAD

**Issue by sudhagart** [microsoft/vscode-jupyter#11363]
Issue Type: <b>Bug</b>

Azure Data Studio \ Jupyter extension is detecting the existing installation of Python in the wrong location - causing notebook init to fail. Below is error snippet. 

Could not start session: Command failed: "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\python.exe" -c "import platform;print(platform.python_version())"
Access is denied.

Actual install location that should have been used is C:\Users\Sudht\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe

When running Azure Data Studio as user - the users path is the right one to use. 

Extension version: 2021.8.1046824664
Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, please could you share the logs for `Python` and `Jupyter` extensions.
Use the commands `Jupyter: Show Output` and `Python: Show Output` to get to the logs.

**Comment by sudhagart** [comment]
Python: Show Output - doesn't exist in Azure Data Studio. 

Jupyter: Show Output - snip below 

User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'NativeNotebookEditor'
Info 2022-09-13 10:09:49: ZMQ install verified.
Info 2022-09-13 10:09:53: No controller, hence notebook communications cannot be initialized for editor file:///c%3A/Users/Sudht/OneDrive%20-%20Microsoft/Notebooks/JuPyter/WCD%20Analysis/FileOverlapDesktop.ipynb

**Comment by DonJayamanne** [comment]
>  Python: Show Output - doesn't exist in Azure Data Studio.

Please verify you have the Python extension installed. If not, you'll need to install the Python extension.

**Comment by sudhagart** [comment]
This is for Azure Data Studio - There is no Python Extension available.

**Comment by DonJayamanne** [comment]
discovering python environments and corresponding python kernels is not guaranteed to work correctly unless python extension is installed 

any reason why python extension cannot need installed on azure data studio?

**Comment by sudhagart** [comment]
AFAIK - Azure data studio does not enable all extensions. Seems to have its own subset of extensions that are supported. This is native notebook support in Azure Data Studio. Not one brought in through the Jupyter notebook extension in VSCode.

**Comment by DonJayamanne** [comment]
Thanks for getting back, Unfortunately there's not much we can do at this end. For Jupyter to work well with Python, we ask users to install Python extension. If Azure Data Studio doesn't enable/allow installing Python extension, I'd file an issue against that.

Closing this issue for now, as Python extension is required for Jupyter to discover Python environments.
