### ISSUE TITLE
Data Viewer displays small floating-point numbers as 0

### ISSUE THREAD

**Issue by dilwong** [microsoft/vscode-jupyter#11373]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Create variable in a .ipynb notebook
```
a = np.zeros((10,10)) + 1e-11
```
and show `a` in the Data Viewer:

<img width="945" alt="wrong small number" src="https://user-images.githubusercontent.com/22341642/190286635-1311f88e-cd16-4ba1-97bd-843e78a39e8d.png">

It appears that numbers larger than or equal to `1e-10` are displayed correctly:
<img width="971" alt="correct small number" src="https://user-images.githubusercontent.com/22341642/190287037-cabdc708-43b3-4d0d-bb2c-263645155dee.png">
but numbers smaller than `5e-11` replaced with `0`. Numbers between `5e-11` and `1e-10` are rounded to `1e-10`.

Is this a bug or the intended behavior? I couldn't find any information on this.

### VS Code Version

1.71.1

### Jupyter Extension Version

v2022.8.1002431955

### Coding Language and Runtime Version

Python 3.9.12

### Language Extension Version (if applicable)

v2022.14.0

### Anaconda Version (if applicable)

conda 4.12.0

### Running Jupyter locally or remotely?

Local

**Comment by vertok** [comment]
plugin Excel Viewer in vscode has same behavior as described above.
https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer

**Comment by amunger** [comment]
closing as the jupyter data viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486
