### ISSUE TITLE
Show remote server display name in kernel picker groups

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11381]
When extensions register server uri provider to Jupyter with a display name, we are not showing the display name in the kernel picker, instead we show a generic `(Remote) Jupyter server`. We might want to put the display name there too.

![image](https://user-images.githubusercontent.com/876920/190475113-72d61d6c-60f3-4c6e-acb7-ec248189666b.png)

**Comment by DonJayamanne** [comment]
This was brought up in the past (& also mocked), however the feedback was that user would only ever have one remote server hence it wasn't useful to see the name.
Note, personally I think its use to see this, E.g AML compute have a name for their connections, and we support those display names in the `Remote Server Connection picker.`
