### ISSUE TITLE
telemetryGenerator always causes generated files to look modified

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#11382]
This causes an extra, unneeded step when trying to commit and push changes

(.venv3) PS C:\src\vscode-jupyter> git commit -m "skip flakey kernel listing test"
husky - prettier is installed

> jupyter@2022.9.100 generateTelemetry
> gulp generateTelemetryMd

[11:29:16] Using gulpfile C:\src\vscode-jupyter\gulpfile.js
[11:29:16] Starting '**generateTelemetryMd**'...
[11:29:33] Finished 'generateTelemetryMd' after 17 s
Checking formatting...
All matched files use Prettier code style!
[aamunger/flakyTest 33b2707bd] skip flakey kernel listing test
 1 file changed, 2 insertions(+), 1 deletion(-)

(.venv3) PS C:\src\vscode-jupyter> git status      
On branch aamunger/flakyTest
Your branch is ahead of 'origin/aamunger/flakyTest' by 1 commit.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        **modified:   TELEMETRY.csv
        modified:   TELEMETRY.md
        modified:   src/gdpr.ts**

no changes added to commit (use "git add" and/or "git commit -a")

**(.venv3) PS C:\src\vscode-jupyter> git add -u
warning: LF will be replaced by CRLF in TELEMETRY.csv.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in TELEMETRY.md.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/gdpr.ts.
The file will have its original line endings in your working directory**

(.venv3) PS C:\src\vscode-jupyter> git status
On branch aamunger/flakyTest
**nothing to commit, working tree clean**

**Comment by amunger** [comment]
I think this is only on Windows, so it might have to be me that fixes it

**Comment by DonJayamanne** [comment]
@amunger Please could you confirm you have `compiled` the code.
I.e. ensure you first run `npm run compile` before running the generator script.
The generator script uses the compiled JS code.

If that works then you'll need to run `npm run compile` and have that task persisted (use the new feature in VS Code to persist the tasks or optionally use `npm run compiled`.

**Comment by DonJayamanne** [comment]
> warning: LF will be replaced by CRLF in TELEMETRY.csv.

Looks like yo're running into a Git issue, looks like your git setup is replacing all of the LF with CRLF unnecessarily

**Comment by DonJayamanne** [comment]
@amunger I've tried this at my end on my Windows machine and I'm not running into any issues, looks like a git config issue at your end.

Here are my settings related to CRLF/LF
```
core.autocrlf=true
```

You might want to change that or look into yoru settings.
Unassigning myself as this is an enviornment issue, and not an issue with the code. (again works for me on my Windows machine)
