### ISSUE TITLE
How can I run Jupyter in vscode when I have to use Slurm to get GPU

### ISSUE THREAD

**Issue by aqlkzf** [microsoft/vscode-jupyter#11395]
I want to use jupyter in vscode when I connect to the Central Server, now it works fine when I didn't use Slurm to get my GPU resource to compute, but I really want to konw how can I use GPU via slurm in vscode-jupyter.

Much thanks in advance.

**Comment by amunger** [comment]
I'm not very familiar with slurm, but from [this walkthrough](https://nero-docs.stanford.edu/jupyter-slurm.html) it looks like it's just a way to set up a remote jupyter server. Where is it failing for you? Are you trying to connect directly to the remote jupyter server, or use vscode's ssh first and then connect?

Can you provide the logs `Jupyter: Show Output`

**Comment by aqlkzf** [comment]
Now I find a way to use vscode-jupyter under slurm, similar to this https://jejjohnson.github.io/research_journal/tutorials/jupyter_vscode/vscode_jupyter/ ,
I can use tmux to open jupyter and get the url, then use vscode-jupyter to open the existing service via this url.
But when I thoose 
![image](https://user-images.githubusercontent.com/67051837/190688024-8d8bf8b8-8402-41d5-a2f6-a2623cdbaa92.png)
there are only one choice,no the existing url choice what I see in some blogs on the Internet.
![image](https://user-images.githubusercontent.com/67051837/190688212-7307c4fa-738b-4676-84d6-1f699bd31fe4.png).
Can you kindly give me some advice on how to slove this problem?

**Comment by aqlkzf** [comment]
![image](https://user-images.githubusercontent.com/67051837/190688636-a0764bb6-65f0-4730-a42f-b1e1760ee91b.png)
I didn't have this choice.

**Comment by DonJayamanne** [comment]
@aqlkzf 
Based on the notes, all you have to do is copy the link of the jupyter server that you get in output of step 3 from here https://jejjohnson.github.io/research_journal/tutorials/jupyter_vscode/vscode_jupyter/ ,

Once you have the link of the jupyter server, then in the `Enter the URI of the running Jupyter Sever`, just paste that link and that should be all.
