### ISSUE TITLE
pipenv installs not importable in Jupyter Notebooks

### ISSUE THREAD

**Issue by Amondale** [microsoft/vscode-jupyter#11390]
## Environment data

-   VS Code version:  VSCodium 1.71.1 rel 22256
-   Jupyter Extension version (available under the Extensions sidebar): v1.0.9
-   Python Extension version (available under the Extensions sidebar): 2022.14.4
-   OS (Linux Mint) and version: Vanessa (21)
-   Python and/or Anaconda version: 3.10.4
-   Type of virtual environment used (pipenv): 
-   Jupyter server running: Local 

## Expected behaviour
inherits pipenv's installs

## Actual behaviour
ignoring pipenv (see screenshot)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]
![Screenshot from 2022-09-15 21-18-07](https://user-images.githubusercontent.com/8033475/190556144-d08368f8-2aad-4864-9a04-f2cd8fde46c8.png)

not a code issue, possibly a problem w/Jupyter vscode extension?

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by amunger** [comment]
seems to work fine for me - did you restart the kernel after installing the package?

Can you run this snippet from both the notebook and the terminal to make sure you're using the same environment:

```
import sys
print(sys.executable)
```
