### ISSUE TITLE
Snappy data viewer for large DFs

### ISSUE THREAD

**Issue by matthewgson** [microsoft/vscode-jupyter#1139]
This feature request is following from microsoft/vscode-python#5469

When I work with large pandas DFs, I relied on PyCharm's dataframe viewer. I liked it because it was very responsive and fast, though it wasn't without problem. With VSCode, however, it is nearly impossible to view large DFs, and many times it takes too much time to see it. 

My guess is that PyChram programmed the viewer to work dynamically - it does not throw all of the data into the viewer, but some parts of data that is visible to users. As the user scrolls to left/right and up/down it instantly loads data to the viewer. Sometimes it was a little bit buggy but was still okay to use. 

I hope vscode Data Viewer can handle large DFs like this.

**Comment by IanMatthewHuff** [comment]
Tagging this per #1151 which I'm going to close to mention that we could also support interrupt to let users bail when loading a large data frame.

**Comment by alandema** [comment]
This problem does not occur only with dataframes. Any type of large data has this behavior. Big numpy arrays, big lists, big dicts...

**Comment by Streep** [comment]
> We will likely just rely on external extensions like Data Wrangler for data viewer functionality going forward - closing

Is it possible to use an external extension like Data Wrangler in a debug session? So that it opens Data Wrangler's data viewer when choosing "View Value in Data Viewer"?
