### ISSUE TITLE
Data Viewer Bug: Pandas table does not display with datetime objects

### ISSUE THREAD

**Issue by NikTarasov** [microsoft/vscode-jupyter#1140]
Issue Type: <b>Bug</b>

When a column contains datetime object with timezone specified. For example if we have a table with a column with unix timestamps in ms, and we want to create a corresponding column with the local time:
`data["datetime"] = data["ts"].map(lambda x: pd.Timestamp(int(x), unit="ms", tzinfo=gettz("Europe/London")))`
It works if we don't provide `tzinfo` though.

Extension version: 2019.8.30787
VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.9.184-linuxkit

**Comment by grzesir** [comment]
has this problem come back? getting it now

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/11680
