### ISSUE TITLE
Run Selection/Line in interactive window shortcut does not work

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#11410]
Jupyter: v2022.8.1002431955Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:07:15.900Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

![CS-1OeFH58K](https://user-images.githubusercontent.com/33796896/191300417-5ef12378-3e92-49d0-aa80-b866b4650b42.png)

I tried the same key comb with my other files (in a non-jupyter env) and it works. For some reason, I have to click the action in the context menu after a selection. A shortcut wouldn't execute my selection. I believe I set it up to only work with .py file. I attached my keybindings.json. Am I missing something or maybe this is a bug.

[keybindings.json.zip](https://github.com/microsoft/vscode-jupyter/files/9609166/keybindings.json.zip)

**Comment by amunger** [comment]
Do you have this setting enabled?
"jupyter.sendSelectionToInteractiveWindow": true

**Comment by StevenLi-DS** [comment]
@amunger Thank you man... it works.

**Comment by amunger** [comment]
no problem - it would make more sense for us to enable that command if `send to terminal` and `send to IW` each have dedicated commands as was the case for you, but we're just disabling it entirely right now.
