### ISSUE TITLE
Add coloring to python data debug data viewer

### ISSUE THREAD

**Issue by RomiRand** [microsoft/vscode-jupyter#11415]
I'm having the same issue as someone else who posted it in the wrong repo: microsoft/vscode#143596. That user was pointed here but I think it was never opened, and it doesn't seem solved, so I'll do it now. Copying the issue text for reference:

I'd like the data viewer to color by value - like a heatmap.
I would also suggest to have the ability to view matrices as images rather than tables - this is particularly relevant when a matrix is large.

the core idea being that text is a super inefficient and ineffective way to visualize an array of numbers.

refer to matlab's data viewer which is very well done.

PyCharm also has great data visualization for debugging.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, however given the fact that this has not receieved enough upvotes/comments since this was created, I'm closing this for now.
