### ISSUE TITLE
Julia still needs support for Jupyter:Variables

### ISSUE THREAD

**Issue by micampbell** [microsoft/vscode-jupyter#11427]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

This is addressed in https://github.com/microsoft/vscode-jupyter/issues/7224 which says its duplicated in https://github.com/microsoft/vscode-jupyter/issues/6548
**but neither solves the problem**.
https://ibb.co/PFsr9bV
Note in the image that the Jupyter: Variables show that none are defined. The wonderful variable watch only works for .jl files. Not for .ipynb files. 

### VS Code Version

1.71.2

### Jupyter Extension Version

v2022.8.1002431955

### Coding Language and Runtime Version

Julia 1.8.1

### Running Jupyter locally or remotely?

Local

**Comment by roblourens** [comment]
Issues to watch
https://github.com/microsoft/vscode/issues/166296
https://github.com/microsoft/vscode/issues/165445
