### ISSUE TITLE
VS_Code Jupyternotebooks matplotlib WIDGETS background colour

### ISSUE THREAD

**Issue by chandradharkoneti** [microsoft/vscode-jupyter#11423]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

__LTDR:__ I want the fourth image to look like the second image.

When using VS_Code and jupyter notebooks, if I use matplotlib widgets, the colour of the __OUTPUT__ cell background is white.
This is very inconvenient. This issue is not present when using regular output(only when using widgets). 

What settings should I change in order to make it work the way I want?

Jupyter extension version: v2022.4.1021342353
Jupyter Notebook Renderers: v1.0.9

*__When not using widgets, no changes to plt.style__*
![NO_Widgets, White](https://user-images.githubusercontent.com/34944218/191466582-780d9026-ea9d-4c6a-8e28-8d8f1d327d02.PNG)

*__When not using widgets, but background set to black by calling__* ```plt.style.use("dark_background")```
![NO_Widgets_Black](https://user-images.githubusercontent.com/34944218/191466594-94f970f3-8ca9-451c-bbfc-f2d9dfca2199.PNG)

*__When using widgets by calling__*```%matplotlib widget``` *__and no changes to plt.style__*
![Widgets_White](https://user-images.githubusercontent.com/34944218/191466565-1f71376c-c098-489d-a234-235a8b040af6.PNG)

*__when using both,__* ```%matplotlib widget``` *__and__* ```plt.style.use("dark_background")```
![Widgets_Black](https://user-images.githubusercontent.com/34944218/191466547-c0946040-b1bb-48c8-a920-7c7d380353af.PNG)

### VS Code Version

Version: 1.67.2 (system setup) Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5 Date: 2022-05-17T18:15:52.058Z Electron: 17.4.1 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Windows_NT x64 10.0.18363

### Jupyter Extension Version

v2022.4.1021342353

### Jupyter logs

```shell
info 14:57:26.76: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing c:\Users\CK Dell\AppData\Roaming\jupyter\runtime\kernel-214043ZiO7UYgaFiG.json

info 14:57:26.206: Started kernel Python 3.9.5, (Raw session started and connected)
info 14:57:26.208: Finished connecting 88c1eb8d-fbca-480f-b6dc-891f1927d649
info 14:57:26.216: UpdateWorkingDirectoryAndPath in Kernel
info 14:57:26.217: Executing silently Code (idle) = import os\nimport sys\n%cd "c:\Users\CK Dell\Desktop\Temp\junk\___TEMP_____JUPYTER"\nif os.getcwd() not
info 14:57:26.246: Executing silently Code (completed) = import os\nimport sys\n%cd "c:\Users\CK Dell\Desktop\Temp\junk\___TEMP_____JUPYTER"\nif os.getcwd() not
info 14:57:26.246: Waiting for idle on (kernel): 1bc9c91f-f103-4e9a-aaf4-4c18d5cda41f -> idle
info 14:57:26.246: Finished waiting for idle on (kernel): 1bc9c91f-f103-4e9a-aaf4-4c18d5cda41f -> idle
info 14:57:28.640: Cell 0 executed with state Success
info 14:57:28.688: Cell 1 executed with state Success
info 14:57:28.757: Cell 2 executed with state Success
info 14:57:28.833: Cell 3 executed with state Success
info 14:57:28.903: [32mFetch Script for {"moduleName":"jupyter-matplotlib","moduleVersion":"^0.10.1"}
info 14:57:28.903: [32mFetch Script for jupyter-matplotlib
info 14:57:28.905: [32mSearching for Widget Script jupyter-matplotlib#^0.10.1 at path: c:\Users\CK Dell\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\tmp\scripts\b0d924f65dfa982626f637881b146744cbae637d0702699e5f5617031e5773e9\index.js
info 14:57:28.912: [32mWidget Script jupyter-matplotlib#^0.10.1 found at path: c:\Users\CK Dell\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\tmp\scripts\b0d924f65dfa982626f637881b146744cbae637d0702699e5f5617031e5773e9\index.js
info 14:57:28.914: [32mScript for jupyter-matplotlib, is https://file%2B.vscode-resource.vscode-cdn.net/c%3A/Users/CK%20Dell/.vscode/extensions/ms-toolsai.jupyter-2022.4.1021342353/tmp/scripts/b0d924f65dfa982626f637881b146744cbae637d0702699e5f5617031e5773e9/index.js from cdn
info 14:57:29.23: Cell 4 executed with state Success
info 14:58:46.545: Execute Cell 0 c:\Users\CK Dell\Desktop\Temp\junk\___TEMP_____JUPYTER\JUPYTER___SCRATCH.ipynb
info 14:58:46.545: Execute Cell 1 c:\Users\CK Dell\Desktop\Temp\junk\___TEMP_____JUPYTER\JUPYTER___SCRATCH.ipynb
info 14:58:46.545: Execute Cell 2 c:\Users\CK Dell\Desktop\Temp\junk\___TEMP_____JUPYTER\JUPYTER___SCRATCH.ipynb
info 14:58:46.545: Execute Cell 3 c:\Users\CK Dell\Desktop\Temp\junk\___TEMP_____JUPYTER\JUPYTER___SCRATCH.ipynb
info 14:58:46.546: Execute Cell 4 c:\Users\CK Dell\Desktop\Temp\junk\___TEMP_____JUPYTER\JUPYTER___SCRATCH.ipynb
info 14:58:46.610: Cell 0 executed with state Success
info 14:58:46.663: Cell 1 executed with state Success
info 14:58:46.813: Cell 2 executed with state Success
info 14:58:46.930: Cell 3 executed with state Success
info 14:58:47.120: Cell 4 executed with state Success
```

### Coding Language and Runtime Version

Python 3.9.5

### Language Extension Version (if applicable)

Python extension v2022.8.1, Pylance extension v2022.9.20

### Anaconda Version (if applicable)

N/A

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
closing in favour of https://github.com/microsoft/vscode-jupyter/issues/7161

**Comment by chandradharkoneti** [comment]
> closing in favour of #7161

@DonJayamanne : Please do not close the Issue without providing a solution.

I saw the issue you linked to #7161 , In that, in the image, there is an option .cell-output-ipywidget-background{}

Can you please at least tell me how to access that setting so that I can change it to black and see what happens.

![129631201-cbc4c754-1a42-4375-bd89-aaae810ed647](https://user-images.githubusercontent.com/34944218/191474714-546a89d4-22d8-41a3-8d04-1ff0d64c9164.png)

**Comment by chandradharkoneti** [comment]
**I have found the solution**
**For anyone interested:**

Make sure VS Code is closed(at least no jupyter related things should be running on it[ I personally closed it completely and reopened it for editing the below file]). 

Open file explorer, go to:

```C:\Users\<your_username_here>\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\webviews\webview-side\ipywidgetsRenderer```

Open the **ipywidgetsRenderer.js** file (using notepad++ or notepad or even VSCode(before letting any jupyter stuff run)) and 

wherever you see ```cell-output-ipywidget-background``` followed by ```background: white```, replace ```white``` with ```black```.

Now the problem is solved. Enjoy :)
