### ISSUE TITLE
connecting kernel is so many times issues

### ISSUE THREAD

**Issue by Ramyaa7780** [microsoft/vscode-jupyter#11421]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by IanMatthewHuff** [comment]
@Ramyaa7780 Can you please provide more information about your issue? To investigate more we'd need at a minimum:
1. The scenario for what you are trying to do
2. The logs from the "Jupyter" section of the output window (which would have the needed information to diagnose a connection issue)

**Comment by IanMatthewHuff** [comment]
Closing due to no info provided.
