### ISSUE TITLE
Check setting scopes

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#11422]
There are a bunch of settings that have `"scope": "machine"`, for example, the log level: https://github.com/microsoft/vscode-jupyter/blob/515ad59e73cb734ae2066c286ef964c6efd60b31/package.json#L1518-L1532

This means that if I configure these in my user settings, then open a Remote-SSH window, those settings won't apply. I don't think `"machine"` is right for that, I think that the log level is a user preference which should carry across between machines. `"window"` would be the right scope for that.

https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema:~:text=machine%20%2D%20Machine%20specific%20settings%20that%20can%20be%20set%20only%20in%20user%20settings%20or%20only%20in%20remote%20settings.%20For%20example%2C%20an%20installation%20path%20which%20shouldn%27t%20be%20shared%20across%20machines.

There are about 10 machine-scope settings, I'm not sure any of them should be machine-scoped.

**Comment by DonJayamanne** [comment]
> configure these in my user settings, then open a Remote-SSH window, those settings won't apply. I don't think "machine" i

i would have thought users would only change this when they need to diagnose a problem, on a specific env. not something they want to carry with them wherever they go.

**Comment by roblourens** [comment]
I guess I want to run with that always enabled, but I'm not typical. You're probably right I don't think that's something we need to decide for the user. And I don't think that's true for the other settings.

**Comment by roblourens** [comment]
I'm a little suspicious of a lot of the setting scopes. 

- I see the `machine` scope on a lot of settings that seem like they are essentially user preferences, and should be able to be set in user settings
- The `application` scope is used on a lot of settings that seem like they would work as `window` scope or even `resource` scope
- `resource` scope is used on some settings, and I don't know what differentiates those from the others

We should use the most permissive scope reasonable for each setting, so let's check the scopes for all settings

Please check over the scopes for settings in your area

- [ ] "jupyter.experiments.enabled"
- [ ] "jupyter.showVariableViewWhenDebugging"
- [ ] "jupyter.experiments.optInto"
- [ ] "jupyter.experiments.optOutFrom"
- [ ] "jupyter.widgetScriptSources"
- [ ] "jupyter.askForLargeDataFrames"
- [ ] "jupyter.askForKernelRestart"
- [ ] "jupyter.exportWithOutputEnabled"
- [ ] "jupyter.jupyterLaunchTimeout"
- [ ] "jupyter.jupyterLaunchRetries"
- [ ] "jupyter.jupyterCommandLineArguments"
- [ ] "jupyter.notebookFileRoot"
- [ ] "jupyter.useDefaultConfigForJupyter"
- [ ] "jupyter.jupyterInterruptTimeout"
- [ ] "jupyter.sendSelectionToInteractiveWindow"
- [ ] "jupyter.variableExplorerExclude"
- [ ] "jupyter.codeRegularExpression"
- [ ] "jupyter.defaultCellMarker"
- [ ] "jupyter.markdownRegularExpression"
- [ ] "jupyter.themeMatplotlibPlots"
- [ ] "jupyter.decorateCells"
- [ ] "jupyter.enableCellCodeLens"
- [ ] "jupyter.enableAutoMoveToNextCell"
- [ ] "jupyter.allowUnauthorizedRemoteConnection"
- [ ] "jupyter.codeLenses"
- [ ] "jupyter.debugCodeLenses"
- [ ] "jupyter.debugpyDistPath"
- [ ] "jupyter.stopOnFirstLineWhileDebugging"
- [ ] "jupyter.remoteDebuggerPort"
- [ ] "jupyter.disableJupyterAutoStart"
- [ ] "jupyter.stopOnError"
- [ ] "jupyter.addGotoCodeLenses"
- [ ] "jupyter.variableQueries"
- [ ] "jupyter.kernels.filter"
- [ ] "jupyter.kernels.trusted"
- [ ] "jupyter.interactiveWindowMode"
- [ ] "jupyter.pythonCellFolding"
- [ ] "jupyter.interactiveWindowViewColumn"
- [ ] "jupyter.magicCommandsAsComments"
- [ ] "jupyter.pythonExportMethod"
- [ ] "jupyter.runStartupCommands"
- [ ] "jupyter.debugJustMyCode"
- [ ] "jupyter.showOutlineButtonInNotebookToolbar"
- [ ] "jupyter.newCellOnRunLast"
- [ ] "jupyter.pythonCompletionTriggerCharacters"
- [ ] "jupyter.logKernelOutputSeparately"
- [ ] "jupyter.excludeUserSitePackages"
- [ ] "jupyter.enableExtendedKernelCompletions"

**Comment by DonJayamanne** [comment]
Closing this for now, as the only items remaining are related to export feature.
