### ISSUE TITLE
Remote Access not Working over SSH Tunnel

### ISSUE THREAD

**Issue by fny** [microsoft/vscode-jupyter#11438]
VS Code: 

> Version: 1.71.2
> Commit: 74b1f979648cc44d385a2286793c226e611f59e7
> Date: 2022-09-14T21:12:14.256Z
> Electron: 19.0.12
> Chromium: 102.0.5005.167
> Node.js: 16.14.2
> V8: 10.2.154.15-electron.0
> OS: Linux x64 5.15.0-46-generic
> Sandboxed: No

Python: 3.9
Jupyter ext: v2022.8.1002431955
Python ext: v2022.14.0
Operating systems:
> **TINY MACHINE: CLIENT**
> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04.5 LTS
> Release:	20.04
> Codename:	focal

> **BIG MACHINE: HOST**
> Distributor ID:	RedHatEnterpriseServer
> Description:	Red Hat Enterprise Linux Server release 7.9 (Maipo)
> Release:	7.9
> Codename:	Maipo

# Expected Behavior

I expect to be able to access big machine which has the jupyter notebook port forwarded via an SSH tunnel on the client.

# Current Behavior

VS Code continues to execute code on the client.

# More details

Tiny and Big run in a protected environment. They can only communicate via SSH. As such, my typical workflow involves starting a jupyter notebook  on Big--the machine with compute power--via `jupyter notebook --no-browser` and forwarding port 8888 from the Big onto Tiny. Using the provided URL, I can then access Big machine from tiny: 

> http://localhost:9999/?token={token}

Everything works as expected using this URL in my browser. However, when I attempt to use the Jupyter extension in VS Code, the code is still running locally. As a test I ran `import os; os.getcwd()` which showed  `/home/tinymachineuser`. 

Here is what showed up in the logs in VS Code.

```
info 22:58:21.421: Creating server with url : http://localhost:9999/
info 22:58:51.836: Execute Cell 0 /home/tinymachineuser/Untitled.ipynb
info 22:58:51.889: Cell 0 executed with state Success
```

I see nothing appear in the Jupyter notebook logs.

**Comment by amunger** [comment]
after you connect to the server with the `Jupyter: Specify Jupyter server for connections`, you also need to select a kernel from that server:
![image](https://user-images.githubusercontent.com/2019016/192033718-aaa6a5ba-0f61-4a89-82fd-32a57a038743.png)

Are you able to see the kernels from the remote server? The default from a Jupyter server is typically called `Python 3 (IPykernel)` as shown in that screenshot.

(also make sure you're not sharing tokens to active servers)

**Comment by fny** [comment]
I am not able to see the kernels from the remote server. All the
environments listed are local.

[image: image.png]

**Comment by fny** [comment]
You're right! This is not obvious behavior and isn't documented anywhere that I can tell:

https://code.visualstudio.com/docs/datascience/jupyter-notebooks#_connect-to-a-remote-jupyter-server
