### ISSUE TITLE
DataViewer should auto-refresh or provide a button to refresh it.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#1143]

**Comment by gcambray** [comment]
DataViewer in debugging cession is a great improvment
In this context, an auto-refresh check box on top of a refresh button would be ideal
Much needed feature!

**Comment by tsauliu** [comment]
need this feature too, with this, we analyst could replace excel by Pandas + Visual Studio Code

**Comment by IanMatthewHuff** [comment]
Validated. Checked with both a simple flat structure as well as with the slicing feature on to see if the slice was preserved.
