### ISSUE TITLE
Trying to use Gradio - One of the best ways to share a machine learning model

### ISSUE THREAD

**Issue by dfinke** [microsoft/vscode-jupyter#11432]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Trying to use https://www.gradio.app/getting_started/ in a notebook. This works in Google colab notebooks:

![image](https://user-images.githubusercontent.com/67258/191806580-7711b254-1aa0-485d-ace6-eb69208d87ed.png)

### VS Code Version

1.71.2

### Jupyter Extension Version

v2022.8.1002431955

### Jupyter logs

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-10d7309ba719> in <module>
      4     return "Hello " + name + "!"
      5 
----> 6 demo = gr.Interface(fn=greet, inputs="text", outputs="text")
      7 
      8 demo.launch()

c:\Python38\lib\site-packages\gradio\interface.py in __init__(self, fn, inputs, outputs, examples, cache_examples, examples_per_page, live, interpretation, num_shap, title, description, article, thumbnail, theme, css, allow_flagging, flagging_options, flagging_dir, flagging_callback, analytics_enabled, _api_mode, **kwargs)
    300 
    301         md = (
--> 302             MarkdownIt(
    303                 "js-default",
    304                 {

c:\Python38\lib\site-packages\markdown_it\main.py in __init__(self, config, renderer_cls)
     50         self.block = ParserBlock()
     51         self.core = ParserCore()
---> 52         self.renderer = renderer_cls(self)
     53 
     54         self.utils = utils

TypeError: 'dict' object is not callable
```

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
Basically its not a problem with VS Code, but something at your end, either with the python environment or the package itself. Again, as mentioned the failure is in the `gradio` pacakge code itself, not vs code.

Please try this same same code in Jupyter Lab/Jupyter Notebooks, and if it fails there you might want to file an issue with Gradio. If not, please do ping us and i'll be happy to help you resolve this issue.

Please note, this works perfectly well for me in VS Code, see below:
![Screen Shot 2022-09-26 at 09 08 22](https://user-images.githubusercontent.com/1948812/192169758-5cc3c6da-20b8-401f-88ca-4f6edaf986b2.png)

Closing this issue as this isn't a problem with vscode, but more of an environmental issue.

**Comment by dfinke** [comment]
Thank you for checking. Yes, ended up upgrading Python from 3.8, re-installed `gradio` and it worked

**Comment by DonJayamanne** [comment]
Glad you got it working and thanks for getting back,
