### ISSUE TITLE
The editor could not be opened due to an unexpected error: Cannot read properties of undefined

### ISSUE THREAD

**Issue by 3h4** [microsoft/vscode-jupyter#11435]
Type: <b>Bug</b>

I'm working remotely and very often loose connection to the jupyter server. The workflow if that happens need to improve a bit, there are too many popup alerts... Right now this happened to my notebook after I got disconnected and connected again.

<img width="618" alt="Screenshot 2022-09-23 at 00 02 37" src="https://user-images.githubusercontent.com/23310996/191859395-c0b229a3-4063-44a4-8944-9ab9b0055b27.png">

Extension version: 2022.9.1002511105
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:07:15.900Z)
OS version: Darwin arm64 20.6.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.18.0-348.12.2.el8_5.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|--crash-reporter-id 4cf64333-f132-4c56-a15d-29c771efde05|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ber|
|OS|Linux x64 4.18.0-348.12.2.el8_5.x86_64|
|CPUs|AMD EPYC 7502 32-Core Processor (128 x 2977)|
|Memory (System)|503.46GB (340.95GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
fc301958:30573243

```

</details>

**Comment by marinafridman** [comment]
Similar issue here. I'm working locally, and the error message is slightly different. Closing the file and re-opening resolves the problem.
![image](https://user-images.githubusercontent.com/36742782/192265010-15c3d65f-947d-40c3-a9bf-c55ea236e141.png)
Jupyter Extension version: v2022.8.1002431955
VS code version: Version: 1.71.2 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:05:37.721Z 
OS: MacOS Catalina 10.15.7

**Comment by 3h4** [comment]
It happens again..  I try to close the notebook and click on "Don't save" but the window simply doesn't close. I have to restart VScode in order to open again..






<img width="972" alt="Screenshot 2022-10-01 at 21 32 41" src="https://user-images.githubusercontent.com/23310996/193425458-a8bb921f-b780-4960-96e5-728f7925fdac.png">

**Comment by Jamesekmills** [comment]
> It happens again.. I try to close the notebook and click on "Don't save" but the window simply doesn't close. I have to restart VScode in order to open again..

I have the same issue. It happens fairly regularly after working in VS code for 1-2 hours. I haven't been able to identify any particular trigger

**Comment by OUTHIM** [comment]
Being troubled by this problem as well.

**Comment by yapanel** [comment]
Same here, I have seen this couple of times now, and it is interrupting my development cycle.

**Comment by davidteubes** [comment]
Same here. Working on Windows, hosting an Ubuntu server VM, using Samba.

**Comment by lodewijkvankeizerswaard** [comment]
I am having the same / a similar issue. Working on a SSH remote.
![image](https://user-images.githubusercontent.com/22987218/218734772-5cc0e662-adfa-4219-916e-6a6ac4070242.png)

It mostly consistently triggers when I run intensive code, that also generates a lot of output (tqdm progress bars). I'm having no trouble opening the same notebook through jupyter notebook (also remote). A checkpoint of the same notebook created through jupyter, re-enables me to open the file.

The python language server crashed at the same time, so this might be related to pylance (?) or the language server. I found the onDidChangeContent property on the [vscode documentation](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide), though I do not feel capable of debuging this further. It might also be related to [issue #165176](https://github.com/microsoft/vscode/issues/165176). Hope this helps

**Comment by jmsull** [comment]
Also having this problem

**Comment by HqChen2021** [comment]
Has anyone solved this problem?

**Comment by indrex** [comment]
Same issue in Feb'23 version of VSCode. I just can't use it for longer than 10-15 minutes. Need to reload window to continue working. 
![image](https://user-images.githubusercontent.com/38977850/223996621-94239451-9df3-4c8c-9450-2533a7a8829e.png)

**Comment by sanketkshah** [comment]
Also have this issue. I use the copilot plugin.

**Comment by indrex** [comment]
We need to notify the copilot team. Opened a discussion [here](https://github.com/orgs/community/discussions/49615)

**Comment by DeyoSwed** [comment]
I have the same issue here; to definitely copilot that trigger it for me wrote a message in the other thread.

**Comment by bregaldo** [comment]
Same problem here, I get this error every hour or so. Also have copilot, but no idea if this is related.

**Comment by tomascortes** [comment]
same problem, when i deactivate copilot and it stopped

**Comment by mschrader15** [comment]
Same problem here

**Comment by indrex** [comment]
Rolling back Jupyter and Copilot extensions resolve the issue. I've raised a ticket with GitHub regarding it and they are investigating.

**Comment by OnyxianSoul** [comment]
I dont have copilot,  and i also have this issue.

**Comment by krbnite** [comment]
I have this issue too; remote server, appears where my Jupyter notebooks should be. I use copilot.

**Comment by bl3e967** [comment]
I had this issue with the error message `the editor could not be opened due to an unexpected error: Cannot read properties of undefined (reading 'onDidChangeContent')`. Using vscode locally on MacOS. I don't use copilot. Reloading the window via `F1 > Developer: Reload Window` resolved the issue.

**Comment by rebornix** [comment]
Thank you all for your feedback and patience. This issue is now mitigated in latest VS Code Insiders and will be available in next Stable. 

What happens is Copilot (or any other extension) crashes the extension host and then the serializer for ipynb notebook is no longer available. Even if the extension host is restarted, we fail to re-associate the serializer extension with the notebook document in the workbench/ui. This should now be improved, work happened in https://github.com/microsoft/vscode/issues/179224
