### ISSUE TITLE
Python data viewer does not support grouped columns (custom indices), Multi-index , PeriodIndex

### ISSUE THREAD

**Issue by p5ydn0** [microsoft/vscode-jupyter#1144]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

When run below code:

```python
import numpy as np
import pandas as pd

# data is from kaggle Titanic Competition
data_train = pd.read_csv('data/train.csv')

g = data_train.groupby(['SibSp','Survived'])
df1 = pd.DataFrame(g.count()['PassengerId'])
df2 = pd.DataFrame(g.count()['Pclass'])
print(df)
```
**the python interactive variables** function can't achieve(display) the expected groupby effect.

the expected effect is like this(below is in Spyder):

![image](https://user-images.githubusercontent.com/25891214/78686391-8b893f80-7925-11ea-828d-c31dce3d1949.png)

but the VSCode variables effect is this:

![image](https://user-images.githubusercontent.com/25891214/78686491-ae1b5880-7925-11ea-8047-ceb24b63294d.png)

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local 
-   **Extension version:** 2020.3.71659
-   **VS Code version:** 1.43.2
-   **Setting python.jediEnabled:** true 
-   **Python and/or Anaconda version:** 3.7.3
-   **OS:**  Mac 
-   **Virtual environment:** conda 

## Developer Tools Console Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by aeryen** [comment]
bump this, the current data viewer seems have poor support for multi-index.

**Comment by amunger** [comment]
closing as the jupyter variable viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486
