### ISSUE TITLE
When you open VS Code from Azure ML two times it opens two different windows for the same notebook session

### ISSUE THREAD

**Issue by iemejia** [microsoft/vscode-jupyter#11440]
## Environment data

**VS Code Environment:**
Version: 1.72.0-insider
Commit: b9f7f85e90b4d51b38fcbf4232801ab04bd659cb
Date: 2022-09-23T08:15:07.186Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

**VS Code Extensions**
Jupyter Extension: v2022.9.1002681037 Pre-Release
Python Extension: v2022.15.12631011 Pre-Release
Azure Machine Learning - Remote: v0.19.2022092309 Pre-Release
Azure Data Lake Tools: v0.2.15

**Python Environment**
Conda: 4.13.0
Python: 3.9.13
Type of virtual environment: Conda + IPyKernel

## Expected behaviour

Open a single session on the notebook/instance

Maybe this is the expected behavior but I was expecting to only have one instance. It will be probably less error-prone for the user.

## Actual behaviour

Open two different sessions

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. From Azure ML open a ipython notebook and Click in open with visual studio code and wait til it is open
2. Come back to Azure ML and open it a second time.

**Comment by roblourens** [comment]
I think this is on azure ml, the site or the extension.

**Comment by iemejia** [comment]
@roblourens do you have an intuition if this could be solved if Azure ML generates the exact link? Would VS Code open a single workspace in that case?

**Comment by roblourens** [comment]
VS Code doesn't support opening two instances of the same workspace. I'm not sure what the flow is for going from the webpage to a vscode workspace - I think it could be opening a URI directly or invoking a command in the extension which generates a URI and opens it?

**Comment by iemejia** [comment]
Actually the URI that Azure ML uses to open VS Code is always generated equally since it includes the exact information of the notebook and Compute Instance, something like:

`vscode://ms-toolsai.vscode-ai/computeInstance/remote?computeId=/subscriptions/XXXXXXX-XXXX-XXXX-XXX-XXXXXXXXXX/resourceGroups/e2e-vscode-jupyter-rg/providers/Microsoft.MachineLearningServices/workspaces/e2e-vscode-jupyter-workspace/computes/e2ecomputeinstance2&sessionId=XXXXX&windowId=_blank&activeFileFolderPath=/Users/imejiauseche/data-science/Titanic.ipynb`

I just noticed that if I change the `windowId=_blank` for `windowId=_self` it works as I would expect, now I just need to find how to report this to the Azure ML team.

**Comment by DonJayamanne** [comment]
> now I just need to find how to report this to the Azure ML team.

i believe this is the place to file issues for azure ml extension
https://github.com/Microsoft/vscode-tools-for-ai

**Comment by iemejia** [comment]
Thanks @DonJayamanne. It seems the repo you sent me is for the VS Code Azure ML extension. We should probably contact someone in the [Azure ML team](http://ml.azure.com/) that manages the action when you click in the button that generates the link to open VS Code.

**Comment by DonJayamanne** [comment]
> contact someone in the Azure ML team that manages the action when you click in the 

to my knowledge it's the same team. besides to my knowledge it's still done via the same vscode extension, which is the aml extension.

**Comment by iemejia** [comment]
Actually I am not sure if it is the case. We need to change the destination link of the `Edit in VS Code` button to open a single instance of VS Code Azure ML is in this page.

![Screenshot 2022-09-30 at 05 27 47-button](https://user-images.githubusercontent.com/79476/193224232-2c0ca834-b36e-4d90-b163-132a5710f0c9.png)

Changing the target windowId of the link could be the way to guarantee that we don't open multiple instances of the notebook workspace (which is not supported as @roblourens mentions).
