### ISSUE TITLE
Jupyter Variables are not painted correctly when resizing the variable panel

### ISSUE THREAD

**Issue by iemejia** [microsoft/vscode-jupyter#11447]
## Environment data

**VS Code Environment:**
Version: 1.72.0-insider
Commit: b9f7f85e90b4d51b38fcbf4232801ab04bd659cb
Date: 2022-09-23T08:15:07.186Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

**VS Code Extensions**
Jupyter Extension: v2022.9.1002681037 Pre-Release
Python Extension: v2022.15.12631011 Pre-Release
Azure Machine Learning - Remote: v0.19.2022092309 Pre-Release
Azure Data Lake Tools: v0.2.15

**Python Environment**
Conda: 4.13.0
Python: 3.9.13
Type of virtual environment: Conda + IPyKernel

**.net Environment**
.net: 6.0.401

**Operating System**
macOS Monterrey 12.6
Macbook Air (M1, 2020)

## Expected behaviour

Jupyter variables to paint all the time and consistently when resizing the variables panel

## Actual behaviour

When moving/resizing the panel to see more details on the variables sometimes the variables dissapear, sometimes they are painted really slowly, sometimes they are not shown at all.

## Steps to reproduce:

1. Run a jupyter notebook that contains many variables
2. Open the Variables 'panel/view'
3. Resize it

![reportbug-azuremlremote4](https://user-images.githubusercontent.com/79476/192231232-18ae3c34-0a5e-4208-ae12-68d07ec06559.gif)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/165445
