### ISSUE TITLE
Jupyter Notebook Remove the compute instance name from the title bar

### ISSUE THREAD

**Issue by iemejia** [microsoft/vscode-jupyter#11452]
## Environment data

**VS Code Environment:**
Version: 1.72.0-insider
Commit: b9f7f85e90b4d51b38fcbf4232801ab04bd659cb
Date: 2022-09-23T08:15:07.186Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

**VS Code Extensions**
Jupyter Extension: v2022.9.1002681037 Pre-Release
Python Extension: v2022.15.12631011 Pre-Release
Azure Machine Learning - Remote: v0.19.2022092309 Pre-Release
Azure Data Lake Tools: v0.2.15

**Python Environment**
Conda: 4.13.0
Python: 3.9.13
Type of virtual environment: Conda + IPyKernel

**.net Environment**
.net: 6.0.401

**Operating System**
macOS Monterrey 12.6
Macbook Air (M1, 2020)

## Expected behaviour

The compute instance associated with the current notebook should be showed only once

## Actual behaviour

The information about the compute instance is repeated in the title bar and in the status bar. It is probably good to remove it from the title since the contrast of the lower bar is better.

## Steps to reproduce:

1. Create a notebook on Azure ML
2. Open the notebook with VS Code

![Screenshot 2022-09-26 at 12 14 26-clean](https://user-images.githubusercontent.com/79476/192252409-a453a236-4dfc-4994-91cd-0a5d6a66b11b.png)

**Comment by amunger** [comment]
that title bar area shows the workspace name, so I'm betting azure ML sets the workspace name to the compute instance

**Comment by roblourens** [comment]
The title bar shows the workspace name which must include the remote name - the workspace name shows up in many different contexts and the titlebar is often used to identify particular windows/workspaces. The statusbar item is there because a remote is a special context and we want to make it obvious that you are working inside this context. It feels redundant but has always worked this way for all remotes and I think it makes sense.

**Comment by roblourens** [comment]
I get that, it's also that both of these are customizable and hideable (actually you can hide it from the titlebar yourself if you prefer)
