### ISSUE TITLE
Error while trying to view a 3 dimensional numpy array

### ISSUE THREAD

**Issue by soares7vinicius** [microsoft/vscode-jupyter#1145]
## Steps to cause the bug to occur

1. Open Python Interactive's variables table
2. Click to view a 3D ndarray

## Actual behavior

Get the following error:
```
Error: Failure during variable extraction: --------------------------------------------------------------------------- ValueError Traceback (most recent call last) ~/Documents/file.py in <module> 51 _VSCODE_df = _VSCODE_pd.Series.to_frame(_VSCODE_evalResult) 52 elif _VSCODE_targetVariable["type"] == "ndarray": ---> 53 _VSCODE_df = _VSCODE_pd.DataFrame(_VSCODE_evalResult) 54 elif hasattr(_VSCODE_df, "toPandas"): 55 _VSCODE_df = _VSCODE_df.toPandas() ~/anaconda3/envs/tcc/lib/python3.7/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy) 462 mgr = init_dict({data.name: data}, index, columns, dtype=dtype) 463 else: --> 464 mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy) 465 466 # For data is list-like, or Iterable (will consume into list) ...
```

## Expected behavior

Show the variable data

### Jupyter and/or Python environment

-   **Jupyter server running:** Local
-   **Extension version:** 2020.5.86398
-   **VS Code version:** 1.45.1
-   **Setting python.jediEnabled:** true 
-   **Setting python.languageServer:** Jedi 
-   **Python and/or Anaconda version:** 3.7.7
-   **OS:** Linux Manjaro 19
-   **Virtual environment:** conda

**Comment by rajkundu** [comment]
+1, This would be an awesome addition to offer the same functionality as (if not better than) Spyder

**Comment by joyceerhl** [comment]
You can now inspect multidimensional tensors and ndarrays in the Jupyter extension's data viewer as of the April 2021 release: https://devblogs.microsoft.com/python/jupyter-in-visual-studio-code-april-2021-release/
