### ISSUE TITLE
Jupyter Notebook Opening an .html file in Azure ML should probably render the page instead of the text version

### ISSUE THREAD

**Issue by iemejia** [microsoft/vscode-jupyter#11455]
## Environment data

**VS Code Environment:**
Version: 1.72.0-insider
Commit: b9f7f85e90b4d51b38fcbf4232801ab04bd659cb
Date: 2022-09-23T08:15:07.186Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

**VS Code Extensions**
Jupyter Extension: v2022.9.1002681037 Pre-Release
Python Extension: v2022.15.12631011 Pre-Release
Azure Machine Learning - Remote: v0.19.2022092309 Pre-Release
Azure Data Lake Tools: v0.2.15

**Python Environment**
Conda: 4.13.0
Python: 3.9.13
Type of virtual environment: Conda + IPyKernel

**.net Environment**
.net: 6.0.401

**Operating System**
macOS Monterrey 12.6
Macbook Air (M1, 2020)

## Expected behaviour

When I open a .html on a notebook from Azure ML from VS Code I would expect to see the rendered webpage instead of the html code.

## Actual behaviour

If you open an html file inside of an Azure ML workspace it shows the raw html codes: `<html>...`

## Steps to reproduce:

1. Create a python notebook in Azure ML
2. Open the notebook with VS Code
3. Export the notebook to html
4. Open the html from the VS Code files view

![reportbug-azuremlremote20](https://user-images.githubusercontent.com/79476/192257938-4ed02403-60b4-4c7d-bb16-adede26c4b52.gif)

**Comment by amunger** [comment]
vscode is a code editor, so opening the html file within that application will provide an editor for the raw html. closing as out of scope

**Comment by roblourens** [comment]
https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server
