### ISSUE TITLE
Jupyter Notebook Name of exported python file should be similar to the notebook name

### ISSUE THREAD

**Issue by iemejia** [microsoft/vscode-jupyter#11453]
## Environment data

**VS Code Environment:**
Version: 1.72.0-insider
Commit: b9f7f85e90b4d51b38fcbf4232801ab04bd659cb
Date: 2022-09-23T08:15:07.186Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

**VS Code Extensions**
Jupyter Extension: v2022.9.1002681037 Pre-Release
Python Extension: v2022.15.12631011 Pre-Release
Azure Machine Learning - Remote: v0.19.2022092309 Pre-Release
Azure Data Lake Tools: v0.2.15

**Python Environment**
Conda: 4.13.0
Python: 3.9.13
Type of virtual environment: Conda + IPyKernel

**.net Environment**
.net: 6.0.401

**Operating System**
macOS Monterrey 12.6
Macbook Air (M1, 2020)

## Expected behaviour

When exporting as .py from a jupyter notebook the proposed name should be similar to the one of the notebook, for example for `Titanic.ipynb` I would expect the exported file to be `Titanic.py`

## Actual behaviour

When exporting as .py from a jupyter notebook the proposed name is a bit odd `%% [ markdown ]` maybe it would be more user friendly to propose a similar name to the one of the notebook.

Notice that for other formats like `.pdf` it proposes it with a similar name.

## Steps to reproduce:

1. Create a notebook
2. Export is as .py (python) file

Strange name proposed for python `%% [ markdown ].py`

![reportbug-azuremlremote14](https://user-images.githubusercontent.com/79476/192254114-a7cee56c-9696-4530-a456-1f89169e3ce0.gif)

Correct name proposed for pdf `Titanic.pdf`:

![reportbug-azuremlremote17](https://user-images.githubusercontent.com/79476/192254128-106ce007-9b6f-460b-9cdd-66c2af5c1683.gif)

**Comment by DonJayamanne** [comment]
Closing as already done.
