### ISSUE TITLE
Notebook asks to restart kernel after running all and scrolling up

### ISSUE THREAD

**Issue by iemejia** [microsoft/vscode-jupyter#11451]
## Environment data

**VS Code Environment:**
Version: 1.72.0-insider
Commit: b9f7f85e90b4d51b38fcbf4232801ab04bd659cb
Date: 2022-09-23T08:15:07.186Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

**VS Code Extensions**
Jupyter Extension: v2022.9.1002681037 Pre-Release
Python Extension: v2022.15.12631011 Pre-Release
Azure Machine Learning - Remote: v0.19.2022092309 Pre-Release
Azure Data Lake Tools: v0.2.15

**Python Environment**
Conda: 4.13.0
Python: 3.9.13
Type of virtual environment: Conda + IPyKernel

**.net Environment**
.net: 6.0.401

**Operating System**
macOS Monterrey 12.6
Macbook Air (M1, 2020)

## Expected behaviour

Scroll up without messages

## Actual behaviour

After doing Run All if I go to the bottom of the notebook and then scroll up rapidly it triggers a message asking me if I want to restart the kernel.

## Steps to reproduce:

1. Create a notebook with multiple cells
2. Run all the cells
3. Scroll to the bottom of the notebook
4. Scroll up

![reportbug-azuremlremote13](https://user-images.githubusercontent.com/79476/192250446-6dbc2031-d9ca-4e48-88dd-37028312ab2d.gif)

**Comment by DonJayamanne** [comment]
@iemejia 
> After doing Run All if I go to the bottom of the notebook and then scroll up rapidly it triggers a message asking me if I want to restart the kernel.

How are you scrolling, are you using the track pad, mouse or a keyboard shortcut.
I'm on a Mac M1 my self and am unable to repro this issue.

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by iemejia** [comment]
@DonJayamanne Hi, sorry for the delay. I was traveling last week.

I think I found what is going on. When you execute a long running notebook by clicking on the `Run All` button and you want to jump to the current executing cell you click multiple times the `Go To` button, but when the execution is finished the area where the 'Go To' button suddenly becomes the `Restart` button.

Curiously if you press the `Interrupt` button (the previously called `Run All`), the Go To button is still visible but disabled. I wonder if to avoid the confusion we should let the `Go To` button at all times to make it less error-prone.

**Comment by DonJayamanne** [comment]
@iemejia thanks for providing the details
Not sure if we can do anything here, but I'd defer to @roblourens 's expertise in this area.

**Comment by roblourens** [comment]
I don't understand- your gif doesn't show anything about clicking in the toolbar. But if that's the issue, yeah, we can't necessarily solve it by showing the Go To button all the time because other buttons like RunAll/Interrupt are showing/hiding anyway. I'd rather keep the current behavior and save the toolbar space in most cases.
