### ISSUE TITLE
Can't expand right-handed column in Data Viewer

### ISSUE THREAD

**Issue by dstanner** [microsoft/vscode-jupyter#1146]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description
Right now I cannot figure out an artful way to expand columns on the right-hand side of the Variable Explorer window. The column is too narrow to read anything. Dragging the column header boundaries around on other columns resizes the columns. But trying to drag the right-hand side of the column header to the right on the far-right column is fruitless. Dragging the left hand side to the left to expand that right column just shrinks the other columns, and does nothing to expand the right-hand column.

I've loaded a sample dataset and attached a screenshot here that shows my squished column. 

![Capture](https://user-images.githubusercontent.com/34904658/67049404-0302b280-f0eb-11e9-9f23-9e7bfb1054c8.JPG)

Is there some way to expand this that I"m missing? Double-clicking the column boundaries in the header (a la Excel) does nothing, and the dragging thing doesn't seem to work for me.

Pointers appreciated, or if there is no good way to do this, adding a way would be helpful.

**Comment by jtele2** [comment]
Did this ever get solved? Or is there an "expand all" feature?

**Comment by amunger** [comment]
closing as the jupyter data-viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486
