### ISSUE TITLE
Jupyter: Cell Tags view should have some welcome content

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-jupyter#11466]
This way it is just empty and I have no clue what value it could bring me as a user.

![Screenshot 2022-09-27 at 14 34 57](https://user-images.githubusercontent.com/1926584/192527780-b3471bd5-8b8a-4189-a70d-b065c298d71a.png)

**Comment by roblourens** [comment]
Seems like some "welcome content" would help, also I was wondering whether it's possible to only show this view once you open a notebook

**Comment by rebornix** [comment]
Fixed in cell tags extension.
