### ISSUE TITLE
Test: markdown image attachment improvement

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11463]
Refs https://github.com/microsoft/vscode-jupyter/issues/5321

- [x] anyOS @sandy081
- [x] anyOS @kieferrm

Authors: @rebornix 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2311463%0A%0A&assignees=rebornix)

---

We have been improving the image attachment support in Jupyter this month, to ensure that image attachment data can be added and cleaned up when the cell content updates. Please make sure you test:

* Initial setup
  * Install prerelease Jupyter extension in Insiders
  * Turn on two experiment settings `editor.experimental.pasteActions.enabled`, `ipynb.experimental.pasteImages.enabled`
  * Open an ipynb notebook
  * Take a screenshot, paste into a markdown cell
  * Ctrl+Enter to turn the markdown cell into preview
* Please test
  * The image is rendered properly
  * Double click the markdown cell to continue editing the cell, then  delete the attachment link from the markdown cell
    * Save the document. Then right click on the editor title bar, run Reopen Editor With ... to open in a text editor, please make sure the image attachment data is not in the file.
    * When you delete the attachment link in the cell, then undo, ctrl+enter to render the markdown cell again. Please make sure the image is rendered properly

**Comment by sandy081** [comment]
@rebornix 

These steps did not work for me - I do not see the image preview after pressing `ctrl+enter`

<img width="774" alt="image" src="https://user-images.githubusercontent.com/10746682/192572903-55e5fffa-c787-48e6-9a98-7b80577b958c.png">

May I know if I am missing something?

**Comment by sandy081** [comment]
@rebornix Even the preview mode is not showing the image

<img width="724" alt="image" src="https://user-images.githubusercontent.com/10746682/192594387-5a4ada5d-4c8c-4f48-b1b8-1f5a2a0390f4.png">

I am on Mac and I used the native screenshot (shift+ctrl+command+4) and pasted it in to the markdown cell.
