### ISSUE TITLE
Test: cell tag editing and slideshow support

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11462]
Refs https://github.com/microsoft/vscode-jupyter/issues/1121, https://github.com/microsoft/vscode-jupyter/issues/1121

- [x] anyOS @alexdima
- [x] anyOS @minsa110

Authors: @rebornix 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2311462%0A%0A&assignees=rebornix)

---

We added support cell tags and slideshow in ipynb file opened in notebook editor. A good demo of how the cell tag insertion/deletion and slideshow works is https://github.com/microsoft/vscode-jupyter/issues/1182#issuecomment-1254098790 , please test (after installing the prerelease of Jupyter extension in Insiders)

* You can add tags to a cell through cell toolbar commands
* You can delete tags from cell status bar
* You can jump to a cell metadata in an ipynb json file from a notebook editor through cell toolbar commands
* You can add slideshow types through cell toolbar commands
* etc ...

**Comment by alexdima** [comment]
Please see https://github.com/microsoft/vscode-jupyter/issues/11467 , none of the actions have any effect for me 🤷 .

**Comment by rebornix** [comment]
@alexdima thanks for the bug report, it's a very good one

* The cell context menu in notebook editor is using `UriComponents` as context, but the cell toolbar is using `NotebookCell`. Since we populate commands from cell toolbar to the cell context menu, those commands won't work in cell context menu. It's a bit too late to make this change, let's fix it in Oct https://github.com/microsoft/vscode/issues/162018 
* For now, let's workaround this by checking if the context is a `NotebookCell` or `UriComponents`.

To continue testing, we can use the cell toolbar (placed at the top right of a cell) or command palette to perform those actions.
