### ISSUE TITLE
Interactive Window (python) history only captures from input box, not from e.g, Run Selection in Interactive Window

### ISSUE THREAD

**Issue by paulmadejong** [microsoft/vscode-jupyter#11468]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When scrolling through history using the up and down arrows, only inputs that were inputted using the input box of the interactive window are shown. I would appreciate that code that was entered using "Run Selection/Line in Interactive Window" (or any other way of copying code from Editor into the Interactive Window) would also be part of the history. This was suggested in #8658 but the issue was closed. Is this a bug or intentional?

Also, the ability to alter run cell blocks as with Jupiter in a browser would be helpful. 

### VS Code Version

1.71.2 (Universal)

### Jupyter Extension Version

v2022.8.1002431955

### Jupyter logs

```shell
none
```

### Coding Language and Runtime Version

Python 3.10.6 and IPython 7.26.0

### Language Extension Version (if applicable)

v2022.14.0

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
I think it's actually covered by https://github.com/microsoft/vscode/issues/129081 (which was also closed) since it needs to be implemented in core.

**Comment by paulmadejong** [comment]
> I think it's actually covered by [microsoft/vscode#129081](https://github.com/microsoft/vscode/issues/129081) (which was also closed) since it needs to be implemented in core.

Yes that’s the exact same request. Didn’t find it myself so thanks for pointing me there. Hope they work on it in core to improve usability!
