### ISSUE TITLE
Test failure: Updating display data

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11486]
`DataScience - VSCode Notebook - (Execution) (slow) -> Updating display data` failed twice in last 7 days

2022-09-26 - TestLogs-local-nonConda-3.9-prerelease--ubuntu-latest
https://github.com/microsoft/vscode-jupyter/actions/runs/3131539772
2022-09-15 - TestLogs-raw-nonConda-3.10---windows-latest
https://github.com/microsoft/vscode-jupyter/actions/runs/3058653938

**Comment by DonJayamanne** [comment]
Should now be fixed
