### ISSUE TITLE
Perpetually "Loading Variables" in Jupyter:Variables tab

### ISSUE THREAD

**Issue by athalia-fastpay** [microsoft/vscode-jupyter#11495]
## Environment data

-   VS Code version: **1.71.2 (user setup)**
-   Jupyter Extension version (available under the Extensions sidebar): **v2022.8.1002431955**
-   Python Extension version (available under the Extensions sidebar): **v2022.14.0**
-   OS (Windows | Mac | Linux distro) and version: **Windows_NT x64 10.0.19044**
-   Python and/or Anaconda version: **3.9.13**
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): **virtualenv**
-   Jupyter server running: **Local**

## Expected behaviour

Variables should show in the tab so that it can be viewed in the Data Viewer

## Actual behaviour

Always shows "Loading Variables" but nothing loads.
I've tried to install a different version, the pre-release and installing the new version and reloading my VS Code but the same issue remains.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by athalia-fastpay** [comment]
I deleted the virtual environment and created a different virtualenv and now my variables and data viewer are back. Moving to close this.

**Comment by athalia-fastpay** [comment]
Right, I did have this issue with the variable explorer after installing autotime

**Comment by amunger** [comment]
ah, sounds like a duplicate then. Give that other issue a vote and hopefully we can get that fixed
