### ISSUE TITLE
Dataviewer needs export and copy

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1149]
It's nice to see the data in a grid, but what if somebody wants to do actual analysis on it. We need at least a copy. Export to csv would be nice too (or open in excel).

**Comment by Sutyke** [comment]
Any news when this feature will be available?

**Comment by rchiodo** [comment]
Sorry but this isn't planned at all. We do accept PRs though. Export to CSV from the dataviewer would likely be difficult to implement (we only have json data in the UI) , but copy shouldn't be to difficult

**Comment by Sutyke** [comment]
Thank for your quick reply, text copy of columns names and cell values
would bring the most benefits to users. it's easy to save file to excel
from the ide by code but users need to copy cell  or header values during
the data analysis.

**Comment by BGW1001** [comment]
Is there any update on this? It is extrodinary that  an interactive pane does not allow its self to copied or exported. Select all does not work. This is a massive fail. This is a much used feature in Spyder. It cant be that difficult.

**Comment by alexepperly** [comment]
> Is there any update on this? It is extrodinary that an interactive pane does not allow its self to copied or exported. Select all does not work. This is a massive fail. This is a much used feature in Spyder. It cant be that difficult.

100%.  This feature would be fantastic to have.  Please, VSCode team, hear our cries!

**Comment by azhagar-deepan** [comment]
@rchiodo @IanMatthewHuff @DonJayamanne 
Hi,
Please look at my code regarding this enhancement. Also give your suggestions.

````
import csv
def export_as_CSV(c,filename = 'filename.csv'): #This function can create the CSV
    with open(filename, 'w', newline='',encoding='utf-8') as csvfile: #get the filename from the user like "Save As" dialog box
        writer = csv.DictWriter(csvfile, fieldnames = c[0].keys())
        writer.writeheader()
        writer.writerows(c)

#For instance:
#We have a list of json or list of Dictionaries like
cars = [
{'No': 1, 'Company': 'Ferrari', 'Car Model': '488 GTB'},    #FIRST json or FIRST record of our CSV
{'No': 2, 'Company': 'Porsche', 'Car Model': '918 Spyder'}, #SECOND json or SECOND record of our CSV
{'No': 3, 'Company': 'Bugatti', 'Car Model': 'La Voiture Noire'}, #THIRD json or THIRD record of our CSV
{'No': 4, 'Company': 'BMW', 'Car Model': '\U0001f600'},
] #list of dictionaries

export_as_CSV(cars, "trip.csv") #CSV file will be created
````

Thank you

**Comment by GuillaumeMoscou** [comment]
> > Is there any update on this? It is extrodinary that an interactive pane does not allow its self to copied or exported. Select all does not work. This is a massive fail. This is a much used feature in Spyder. It cant be that difficult.
> 
> 100%. This feature would be fantastic to have. Please, VSCode team, hear our cries! @rchiodo Even just being able to copy successfully would be a great mprovement. You guys already do such a great job, so thank you for what you do. This would be just one more HUGELY helpful feature!

Yes Spyder for this is very great. you better control the content of variables. So adding it in VS would be a huge help because sometimes you do not have the possibility or you don't want to export in csv / excel through the code.

**Comment by ReeceLincoln** [comment]
Any progress on this? Would greatly appreciate this functionality!

**Comment by NikDE123** [comment]
Any update on this one? Its hard to analyse a Dataframe with large number of rows and columns.

**Comment by pandaxuning** [comment]
Please add this feature. For someone coming from Spyder, missing this feature is quite inconvenient.

**Comment by shezadt** [comment]
I would love to have this function too! :)

**Comment by OndrejW** [comment]
I would love to have this function too! :)

**Comment by statisco** [comment]
Is this open since 2019 and still no updates? That's sad... It would be great to have this function. :(

**Comment by sjhsbhqf** [comment]
Looking forward to the arrival of this feature

**Comment by kflow-stash** [comment]
This would be a very convenient feature - I agree that simple copy/paste functionality for basic objects (such as list, Series, DataFrame) should be easy to implement and very helpful for users

**Comment by mcxvio** [comment]
This would be great, thanks.

**Comment by amunger** [comment]
We will likely just rely on external extensions like Data Wrangler for this functionality

**Comment by amunger** [comment]
closing as our data-viewer was deprecated
