### ISSUE TITLE
reconsider adding an option to control the font size of tensorboard interface

### ISSUE THREAD

**Issue by Qm-jmz** [microsoft/vscode-jupyter#11497]
I‘ve known that this question had been discussed in #15560 and microsoft/vscode-python#17214. But I really beg your team to reconsider adding an option to control the font size of tensorboard interface.

My resolution is 1080P.

As shown in the figure below, the font size of tensorboard opened by browser looks clear and comfortable.
![image](https://user-images.githubusercontent.com/50917637/193212273-263a78df-afae-4926-bf30-a5e449bb7586.png)

But the font of tensorboard opened with VS Code is too small and fuzzy.
![image](https://user-images.githubusercontent.com/50917637/193213688-e521621a-284d-4bb1-8017-caa7e004baf0.png)

**Comment by DonJayamanne** [comment]
Thanks for filing this issue
However this issue has not enough upvotes since this was created, hence closing this
