### ISSUE TITLE
Confusing "Invalid URI specified" UX while connecting to server

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#11492]
Type: <b>Bug</b>

Found verifying #11285

1. Try connecting to a jupyter server
2. Type in some badly formed uri, such as `http:::/example.com`

**Bug**
There is no feedback in the input box. Nothing seems to happen

At the bottom of the screen an error notification with `Invalid URI specified` shows, but I missed this the first time I ran into this issue 

<img width="299" alt="Screen Shot 2022-09-29 at 11 40 42 AM" src="https://user-images.githubusercontent.com/12821956/193116240-09f5c824-13f8-409b-b4ea-96749e4f2b86.png">

Extension version: 2022.9.1002731204
VS Code version: Code - Insiders 1.72.0-insider (Universal) (2c801254ebf547baaee771b99aa76d202f999622, 2022-09-29T08:07:33.897Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52:30568093
vscccc:30564267
pyindex848:30577858

```

</details>

**Comment by DonJayamanne** [comment]
This should now be fixed in the latest kernel picker.
Enable the new kernel picker as follows in the user settings, reload and test again
```
"notebook.kernelPicker.type": "mru",
```
