### ISSUE TITLE
Turtle widget code fails to run the second time but succeeds the third time

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode-jupyter#11509]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

```
import turtle as ttl

ttl.shape('turtle')
ttl.speed(0)

# draw a line
ttl.forward(200)

ttl.mainloop()
print('done')
```

If you run it twice, it will report an error. The third time, it can run normally again. Unless you kill the kernel, an error will occur every time you run it repeatedly.

```
Terminator                                Traceback (most recent call last)
c:\newPython\test.ipynb Cell 2 in <cell line: 1>()
----> [1](vscode-notebook-cell:/c%3A/newPython/test.ipynb#W1sZmlsZQ%3D%3D?line=0) ttl.shape('turtle')
      [2](vscode-notebook-cell:/c%3A/newPython/test.ipynb#W1sZmlsZQ%3D%3D?line=1) ttl.speed(0)
      [4](vscode-notebook-cell:/c%3A/newPython/test.ipynb#W1sZmlsZQ%3D%3D?line=3) # draw a line

File <string>:5, in shape(name)

Terminator:
```

### VS Code Version

1.71.2

### Jupyter Extension Version

v2022.8.1002431955

### Jupyter logs

```shell
info 9:45:11.383: Execute Cell 0 c:\newPython\test.ipynb
info 9:45:11.423: Cell 0 executed with state Success
info 9:45:13.223: Execute Cell 1 c:\newPython\test.ipynb
info 9:45:14.751: Cell 1 executed with state Success
info 9:45:16.767: Execute Cell 1 c:\newPython\test.ipynb
info 9:45:16.923: Cancel all remaining cells true || Error || undefined
info 9:45:16.923: Cancel pending cells
info 9:45:16.924: Cell 1 executed with state Error
```

### Coding Language and Runtime Version

Python 3.10

### Language Extension Version (if applicable)

Python Pylance jupyter

**Comment by amunger** [comment]
It might just have some trouble with initialization and teardown of the external app. Looks like @DonJayamanne has done some previous work to get turtle working on https://github.com/microsoft/vscode-jupyter/issues/8241

**Comment by DonJayamanne** [comment]
@ydmykr 
Can you run the same code in Jupyter Notebook (outside VS Code) and let me know if you run into the same problem

**Comment by ydmykr** [comment]
![image](https://user-images.githubusercontent.com/100815370/194193206-a8b17924-b411-4897-a2df-67250122e0c1.png)

Unfortunately, I will still encounter the same problem.

**Comment by DonJayamanne** [comment]
Thanks for getting back to us, Looks like a problem with the package itself, or other.
Unfortunately I'm not an expert of the turtle widget, please react out to the maintainers of the turtle package for assistance.
Closing this issue as this isn't a problem with the Jupyter extension.
