### ISSUE TITLE
Bug in DataViewer filter for numbers

### ISSUE THREAD

**Issue by bitagoras** [microsoft/vscode-jupyter#1150]
## Environment data

- VS Code version: 1.39.1
- Extension version: 2019.10.41019 (8 October 2019)
- Python version: Anaconda for Python 3.7.3 64-bit

## Expected behaviour

Entering e.g. "3" in colum filter for integer numpy array should result in e.g. rows with `-3, -3, 3, 13, 23`.

## Actual behaviour

Displayed are the rows e. g. `-3, -3, 0, 0, 3, 13, 23`. This is a bug since zeros should be filtered. ~~With floating point arrays the filtering seem not to work at all when expecting string pattern matching. All rows are filtered for any digits.~~

## Screenshot

![filter](https://user-images.githubusercontent.com/10660123/66704616-d8e17700-ed1d-11e9-965c-0ce12c1bab61.png)

Another remark on the screenshot: It would be nice, if the sorting would be stable. For several identical lines the other lines should stay in the order of the last sorted column (here the last sorted column was the line index which is now disordered for equal elements in column 1)

**Comment by IanMatthewHuff** [comment]
I believe that the dataviewer changes from Vandy has resolved this issue.
