### ISSUE TITLE
Connection to kernel takes forever

### ISSUE THREAD

**Issue by podleyan** [microsoft/vscode-jupyter#11513]
## Environment data

-   VS Code version: 1.71.1
-   Jupyter Extension version (available under the Extensions sidebar): v2022.8.1002431955
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.8.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A and venv 
-   Jupyter server running: Local 

## Expected behaviour

Jupyter notebook should run the cell

## Actual behaviour

Message in the right corner: 
Connecting to kernel: Python 3.8.10: Activating Python Environment 'Python 3.9.12 ('base')'

Doesn't connect 

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1.  Run cell with code:  Print("")

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```

```

</p>
</details>

I've reinstalled ipykernel, but it doesn't help. 
Before it was working and nothing changed since then.

**Comment by Ronkiro** [comment]
I couldn't repro here.

> I've reinstalled ipykernel, but it doesn't help.

Do you have more than one Python's version in your computer? If so, in which one did you reinstall? Also, do you use some kind of tool to install python (Like pyenv)?

**Comment by podleyan** [comment]
Yes, I do have only one Python version. I've tried to use virtual environment (venv) with the same python as well. 
I've reinstalled ipykernel both with and without virtual env. I don't use any tool to install python. 

Thank you

**Comment by amunger** [comment]
Sorry you're hitting this issue.

Can you try reproducing the issue after a fresh reload and provide the logs from the command `Jupyter: Show Output`

**Comment by amunger** [comment]
we are actually seeing some test failures that seem to be caught in the same issue https://github.com/microsoft/vscode-jupyter/actions/runs/3177406135/jobs/5177808333

![Can_restart_a_kernel_after_it_dies_c9385224a0_1-screenshot](https://user-images.githubusercontent.com/2019016/193697158-ce5c468e-af88-4e15-8063-026070407ded.png)

**Comment by amunger** [comment]
Perhaps this error?

```
[34m9:12:05 PM.346[39m: [33m2022-10-03 21:12:05,207 UTC - ERROR - Error in line INITIALIZE_INTERRUPT:1[39m
[33mTraceback (most recent call last):[39m
[33m  File "d:\a\vscode-jupyter\vscode-jupyter\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py", line 335, in main[39m
[33m    print(f"INITIALIZE_INTERRUPT:{int(line.split(':')[1])}:{handle}")[39m
[33mOSError: [Errno 9] Bad file descriptor[39m
[33m [][39m
```

**Comment by xavArtley** [comment]
I hit the same issue on windows and with current jupyter extension version
The console output is:
```
Visual Studio Code (1.71.2, undefined, desktop)
Jupyter Extension Version: 2022.8.1002431955.
Python Extension Version: 2022.14.0.
Multiple Workspace folders opened c:\CIVA_RP\CIVA_SIE\src_python\pyciva, c:\CIVA_RP\CIVA_SIE\src_python\webapps, c:\CIVA_RP\CIVA_SIE\src_python\civa_utils, c:\CIVA_RP\CIVA_SIE\src_python\external_repo\pycoralie, c:\CIVA_RP\CIVA_SIE\src_python\external_repo\parallel_coordinates, c:\CIVA_RP\CIVA_SIE\Scripts_Ant, c:\Users\xa235208\Documents\Developments\mydevs
info 8:44:14.489: ZMQ install verified.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 8:44:14.779: LSP Notebooks experiment is enabled
info 8:44:14.805: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 8:44:15.972: Process Execution: > c:\CIVA_RP\CIVA_SIE\ProjetCIVA\ceaComponents\dev\python\python.exe -m pip list
> c:\CIVA_RP\CIVA_SIE\ProjetCIVA\ceaComponents\dev\python\python.exe -m pip list
info 8:44:16.33: Starting Jupyter Session id = 'startUsingPythonInterpreter:.jvsc74a57bd092eab6366f9b599e0febef1ea0e3b122efe43fec124f29c28fa76c06311d10d8.c:\CIVA_RP\CIVA_SIE\ProjetCIVA\ceaComponents\dev\python\python.exe.c:\CIVA_RP\CIVA_SIE\ProjetCIVA\ceaComponents\dev\python\python.exe.-m#ipykernel_launcher' (Python Path: , EnvType: System, EnvName: '', Version: 3.8.5) for 'c:\CIVA_RP\CIVA_SIE\src_python\webapps\xartests\test.ipynb' (disableUI=true)
info 8:44:16.34: Creating raw notebook for resource 'c:\CIVA_RP\CIVA_SIE\src_python\webapps\xartests\test.ipynb'
info 8:44:16.34: Computing working directory for resource 'c:\CIVA_RP\CIVA_SIE\src_python\webapps\xartests\test.ipynb'
info 8:44:16.93: Starting raw kernel 'Python 3.8.5' for interpreter c:\CIVA_RP\CIVA_SIE\ProjetCIVA\ceaComponents\dev\python\python.exe
info 8:44:16.136: Kernel launching with ports 9000,9002,9003,9004,9005. Start port is 9000
info 8:44:16.633: Process Execution: > c:\CIVA_RP\CIVA_SIE\ProjetCIVA\ceaComponents\dev\python\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> c:\CIVA_RP\CIVA_SIE\ProjetCIVA\ceaComponents\dev\python\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 8:44:18.52: ipykernel version 6.15.1 for c:\CIVA_RP\CIVA_SIE\ProjetCIVA\ceaComponents\dev\python\python.exe
info 8:44:18.52: ipykernel location c:\CIVA_RP\CIVA_SIE\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\ipykernel\__init__.py for c:\CIVA_RP\CIVA_SIE\ProjetCIVA\ceaComponents\dev\python\python.exe
info 8:44:19.231: Preferred Remote kernel for c:\CIVA_RP\CIVA_SIE\src_python\webapps\xartests\test.ipynb is undefined
info 8:44:19.231: Find preferred kernel for c:\CIVA_RP\CIVA_SIE\src_python\webapps\xartests\test.ipynb with metadata {"kernelspec":{"display_name":"Python 3.8.5 64-bit (system)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.5"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"92eab6366f9b599e0febef1ea0e3b122efe43fec124f29c28fa76c06311d10d8"}}} & preferred interpreter c:\CIVA_RP\CIVA_SIE\ProjetCIVA\ceaComponents\dev\python\python.exe
info 8:44:19.234: Preferred Remote kernel for c:\CIVA_RP\CIVA_SIE\src_python\webapps\xartests\test.ipynb is undefined
info 8:44:19.234: Preferred kernel .jvsc74a57bd092eab6366f9b599e0febef1ea0e3b122efe43fec124f29c28fa76c06311d10d8.c:\CIVA_RP\CIVA_SIE\ProjetCIVA\ceaComponents\dev\python\python.exe.c:\CIVA_RP\CIVA_SIE\ProjetCIVA\ceaComponents\dev\python\python.exe.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, [object Object], true, false)
info 8:44:19.237: PreferredConnection: .jvsc74a57bd092eab6366f9b599e0febef1ea0e3b122efe43fec124f29c28fa76c06311d10d8.c:\CIVA_RP\CIVA_SIE\ProjetCIVA\ceaComponents\dev\python\python.exe.c:\CIVA_RP\CIVA_SIE\ProjetCIVA\ceaComponents\dev\python\python.exe.-m#ipykernel_launcher found for NotebookDocument: c:\CIVA_RP\CIVA_SIE\src_python\webapps\xartests\test.ipynb
info 8:44:19.324: Process Execution: > ~\Miniconda3\envs\binder\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 10092
> ~\Miniconda3\envs\binder\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 10092
info 8:44:19.324: Process Execution: cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\pythonFiles\vscode_datascience_helpers
cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\pythonFiles\vscode_datascience_helpers
info 8:44:19.396: Preferred Remote kernel for c:\CIVA_RP\CIVA_SIE\src_python\webapps\xartests\test.ipynb is undefined
warn 8:44:19.397: Fatal Python error: init_sys_streams
warn 8:44:19.397: : can't initialize sys standard streams
Traceback (most recent call last):
  File "C:\CIVA_RP\CIVA_SIE\ProjetCIVA\ceaComponents\dev\python\lib\io.py", line 54, in <module>

warn 8:44:19.398: ImportError: cannot import name 'open_code' from 'io' (unknown location)
```
I don't have issue with version v2022.7.1002181843

**Comment by DonJayamanne** [comment]
@xavArtley Can you file a separate issue.
You are running into a different issue, basically things are failing as opposed to `kernel takes forever`.
When filing the issue, please provide the above logs as well as the logs from the version `2022.7.*`
I'd like to compare the two and see what's different.

**Comment by DonJayamanne** [comment]
[podleyan](https://github.com/podleyan)
Please could you replicate the issue and provide the logs (you seem to have forgotten to upload this in the issue)

**Comment by andreostrovsky** [comment]
> Perhaps this error?
> 
> ```
> �[34m9:12:05 PM.346�[39m: �[33m2022-10-03 21:12:05,207 UTC - ERROR - Error in line INITIALIZE_INTERRUPT:1�[39m
> �[33mTraceback (most recent call last):�[39m
> �[33m  File "d:\a\vscode-jupyter\vscode-jupyter\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py", line 335, in main�[39m
> �[33m    print(f"INITIALIZE_INTERRUPT:{int(line.split(':')[1])}:{handle}")�[39m
> �[33mOSError: [Errno 9] Bad file descriptor�[39m
> �[33m []�[39m
> ```

I get this same issue, and the above error, whenever there's a pending update. Closing vscode shows an "updating vs code" popup. After starting vscode again, all works normally.

**Comment by yuuuxt** [comment]
I was having the same issue, restarting vscode and reboot device didn't help. 

Downgrading from `2022.9.1202862440`(current latest) to `2022.9.1100000000` (2nd latest) then upgrade to `2022.9.1202862440` again, then the issue disappears.

**Comment by DonJayamanne** [comment]
Thsi should be fixed in the latest pre-release version of the Jupyter extension
Youl could either install the latest pre-release jupyter and python extensions in vscode insiders to verify this issue or test this in the latest stable version that will be released some time this week.

**Comment by kechan** [comment]
On a M2 Max Apple Silicon, just upgraded to Ventura 13.3 and VS Code Jupyter Notebook is toasted (apparently). 
I run the first cell and it is a waiting clock icon at the bottom forever. Need to reboot and try again. 
Probably will raise a new issue.
