### ISSUE TITLE
With remote server specified, local kernels aren't listed if the server is down

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#11528]
Type: <b>Bug</b>

This may be because I am in the remote experiment and also have 
`"jupyter.showOnlyOneTypeOfKernel": false`

1. Specify a jupyter server for remote kernels
2. Kill the server
3. reload vscode 
:bug: only one of my local kernels is listed
:bug: cannot debug a cell
:bug: cannot create an interactive window

Extension version: 2022.9.1002791060
VS Code version: Code - Insiders 1.72.0-insider (a12109a6ac8cdb070d94d63a5dc3a3a8f53bad8c, 2022-10-04T12:24:00.023Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (12.12GB free)|
|Process Argv|--crash-reporter-id 1202dc88-403d-4ebc-8393-af3551a8bd5b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pylantcb52:30568093
vsccc:30564266
pyindex848:30577858

```

</details>

**Comment by DonJayamanne** [comment]
I recall reporting this in the past. This is eithera regression or a duplicate.

**Comment by IanMatthewHuff** [comment]
@amunger Bit confused about the showOnlyOneTypeOfKernel mention about also being in the kernel experiment. When reproing do you see the Connect To A Remote Server and Connect to Local Kernel commands in the picker or not? Just trying to make sure that I'm looking at the right repro.

**Comment by amunger** [comment]
the experiment was disabled with the setting, I just wanted to bring up that I _was_ in the experiment in case that was causing issues. I was not seeing the "connect to local kernels" command, just a single one of my local kernels.

I just updated and attempted to capture a screenshot and this no longer repros for me: the cached remote kernel is still selected, and I am able to switch to a different kernel. I'll just close this for now since I'm pretty sure I was the only one that saw this.

**Comment by IanMatthewHuff** [comment]
Awesome, if you see it again just reactivate or file a new one. I was just worried about making sure that I knew if it was possibly an overall general issue versus relating to the experiment.

**Comment by amunger** [comment]
OK, it came back again. I'm in remote mode as shown in the status bar, and have to both specify jupyter server as "none" and reload vs code before the full list of local kernels are shown

![KernelLIsting](https://user-images.githubusercontent.com/2019016/194155972-ce0c90c1-3983-4351-b1a5-d1ecc20f6ac2.gif)

**Comment by DonJayamanne** [comment]
this should now be fixed
@amunger please could you confirm this

**Comment by connor4312** [comment]
Taking the "close" action as a verification. Otherwise please remove the tag.
