### ISSUE TITLE
Interrupt button in .ipynb is missing after updating to 1.72

### ISSUE THREAD

**Issue by gaminglifex** [microsoft/vscode-jupyter#11567]
## Environment data

-   VS Code version: 1.72
-   Jupyter Extension version (available under the Extensions sidebar): v2022.9.1002791758
-   Python Extension version (available under the Extensions sidebar): v2022.16.0
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: 3.10.5 / 2.1.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

![image](https://user-images.githubusercontent.com/72642816/194499774-ce189ae1-5808-417c-b574-00570b301222.png)

**Comment by rebornix** [comment]
We merged the interrupt button with the run all button, so when there is a long running cell and the run button will be swapped with interrupt.

**Comment by gaminglifex** [comment]
Thank you for your response. However, this a bit inconvenient when I am trying to execute functions using ipywidget.
![image](https://user-images.githubusercontent.com/72642816/196385035-33303f1f-8902-4437-aaf3-fe6bb71ce891.png)
As there is no loading indicator even the program is running, it would be great to have that interrupt button display like the one in previous version.
May I know is there any way for me to get the button back except installing previous version?
