### ISSUE TITLE
Gather icon to appear at all times 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#1156]
# Enhancement: Gather Extension

## Steps to cause the bug to occur
Install gather extension 

## Actual behavior
No icon appears on the cell toolbar

## Expected behavior

Icon should appear on the cell toolbar once the extension is installed. 
When user clicks on icon, throw error/popup explaining cells must be run for gather to function. 

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by DavidKutu** [comment]
Done
