### ISSUE TITLE
Expand insiders kernel picker options to show an MRU section and an active sessions section

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#11577]
Building on the work of #11576. 

Expand the kernel source options with options to see a MRU list of the X most recently used controllers.
Expand the kernel source options with options to see the currently active notebook sessions from all kernel sources.

Helpful to make sure the kernel picking UI design can expand in a way that encompasses picking on characteristics other than just kernel source.

**Comment by DonJayamanne** [comment]
fixed with the latest kernel picker
