### ISSUE TITLE
Clear outputs when cell is running or in queue

### ISSUE THREAD

**Issue by apcamargo** [microsoft/vscode-jupyter#11585]
In JupyterLab if you put a given cell that was previously executed in the run queue, the outputs will be cleared right after you click the run button (or press any of the the keyboard shortcuts).

In VSCode the behavior is different. The old outputs of a cell that is being re-executed will not disappear until the cell finishes executing and the new outputs are displayed.

Not really sure if this is a design decision, but I think JupyterLab's behavior is less confusing. If you are re-executing a notebook in VSCode (after changing the inputs or some parameters, for example) and don't realize that the cells are not finished, you could think that the outputs being shown are up-to-date.

Screen recordings of JupyterLab and VSCode showcasing the different behavior:

https://user-images.githubusercontent.com/22940964/194778952-ae6536b3-e3b9-4f98-bcee-6d8f695af348.mov

https://user-images.githubusercontent.com/22940964/194778954-d2ec7fe4-4965-4441-844c-6d0ca862b725.mov

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, I agree this can be confusing.
A related issue is here https://github.com/microsoft/vscode-jupyter/issues/7123

**Comment by hwaxxer** [comment]
Agree 100% with this. It's actually quite hard to tell what cells in VSCode are currently running. Because the output can be huge, especially for errors and not clearing them on run is a design mistake, imho.

**Comment by DonJayamanne** [comment]
Closing this issue for now, as this hasn't received sufficient upvotes from the time this was created.
