### ISSUE TITLE
Reuse of cell makes it move

### ISSUE THREAD

**Issue by gilles-zerah** [microsoft/vscode-jupyter#11583]
Type: <b>Bug</b>

- Scroll up to an already used cell
- Execute the cell
- The cell moves up

Extension version: 2022.8.1002431955
VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.87GB (5.51GB free)|
|Process Argv|--crash-reporter-id 7b818869-eba6-49ab-b905-febaae92ae5b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
vscccc:30566498
pyindex848cf:30577861
fc301958:30573243

```

</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, unfortunately I don't quite understand the problem.
Please could you take a screen recording using something like gifcap.dev or similar and upload it here so I can get a better understanding of the bug.

**Comment by gilles-zerah** [comment]
Hello, 
Thanks for your prompt reply.
To make things clearer (see also the movie):
When I execute  the first cell, it goes up and disappears, I do not even see the messsage and I have to scroll back to see it.
On the other hand, for the other cell (towards the end of the notebook), it stays in place, as expected.
![Recording 2022-10-10 at 09 30 23](https://user-images.githubusercontent.com/6022551/194818913-9a020214-50f8-48a7-9315-5b8d99c4c252.gif)

**Comment by DonJayamanne** [comment]
@gilles-zerah 
I'm very sorry for not getting back to you on this, this issue completely fell off my rather. I do apologize for that.
Are you still running into this issue?

**Comment by gilles-zerah** [comment]
Hello,

Yes, I do. When I reuse a cell a little bit upstream, it generally
"disappears" (that is goes up) when I run it. This is annoying.
Thanks,
Gilles

Le dim. 4 déc. 2022 à 20:53, Don Jayamanne ***@***.***> a
écrit :

**Comment by rebornix** [comment]
Let's track it in https://github.com/microsoft/vscode/issues/121723

**Comment by gilles-zerah** [comment]
Note that Ctrl+Enter does not move the cell, from my experience, but naturally keeps the focus on the current cell. 
I guess this is understandable since there is no change of focus contrary to Shift+Enter
