### ISSUE TITLE
"No Pip installer" when ancestor folder contains poetry

### ISSUE THREAD

**Issue by p-i-** [microsoft/vscode-jupyter#11596]
Type: <b>Bug</b>

In /foo `poetry init`
In /foo/bar create a .venv and x.ipynb
Open x.ipynb, select our .venv/bin/python
Execute a cell (e.g `1+1`) and VSCode dialog-prompts to install ipykernel

However, it's getting tangled with the /foo/poetry stuff.

The dialog-prompt says "Running cells with 'Python 3.10.0 ('.venv': poetry)' requires ipykernel package."

And clicking 'ok' gives "There is no Pip installer available in the selected environment (Source: Jupyter (Extension)" error.

So VSCode's not applying `pip install ipykernel` to the selected Python.

Extension version: 2022.9.1002791758
VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:21:58.256Z)
OS version: Darwin x64 21.5.0
Modes:
Sandboxed: No

**Comment by p-i-** [comment]
In case anyone has gotten stuck with this, as a workaround that we can `. .venv/bin/activate` and `pip install ipykernel`.

**Comment by DonJayamanne** [comment]
@p-i- 
I'm sorry for not getting back to you on this issue. Please could you confirm this is still and issue with the latest vsocde insiders and latest pre-release versions of the Jupyter and Python extensions.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Comment by david-waterworth** [comment]
This is still an issue for me with vscode 1.81.0 (July 2023 update).

I'm starting to migrate projects to poetry, and I cannot launch a notebook in a poetry project for the first time as the automatic jupyter installation fails.
