### ISSUE TITLE
how to close ssl connection at vscode config

### ISSUE THREAD

**Issue by lijianl** [microsoft/vscode-jupyter#11594]
`Connection failure. Verify the server is running and reachable. (Denied connection to insecure server.).`

how to close ssl, so that i can use http in vscode

**Comment by amunger** [comment]
I'm not quite clear on what you're asking.
Where is that error shown, and what action caused it? Are you trying to connect to a remote Jupyter server, or just connecting to a remote workspace with remote-ssh?

**Comment by chris-aeviator** [comment]
@amunger 
the issue is that vscode seems to sometimes disallow connections to http:// jupyter servers that are password protected. Sometimes there's the warning that asks to allow but sometimes it plainly errors directly.
