### ISSUE TITLE
Failures in `switchKernelWithRetry` must be handled inside the method for native notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1159]
Currently we handle some exceptions and others are thrown.
Due to changes in how kernel picker works, this is the place to handle the exceptions and notify user.

See following comments in `kernelProvider.ts` file (hook for VS Code events)
```typescript
                // TODO: We need to handle these exceptions in `siwthKernelWithRetry`.
                // We shouldn't handle them here, as we're already handling some errors in the `siwthKernelWithRetry` method.
                // Adding comment here, so we have context for the requirement.
                this.kernelSwitcher.switchKernelWithRetry(notebook, selectedKernelConnectionMetadata).catch(noop);
```

**Comment by greazer** [comment]
Not sure this has meaning anymore.

**Comment by IanMatthewHuff** [comment]
@DonJayamanne you closed but then added debt? Wasn't sure on the state of this when looking at things to verify. Pretty sure you already fixed the switch with retry code.

**Comment by rchiodo** [comment]
I believe this code was just removed entirely.
