### ISSUE TITLE
Sluggish interface ipynb

### ISSUE THREAD

**Issue by bdch1234** [microsoft/vscode-jupyter#11619]
The interface for ipynb-files feels sluggish on my laptop, but not my desktop. Is there anything I can turn off to get the same experience on the laptop? I am using an ARM-based laptop and remoting into a virtual computer. But it is definitely not a connection-problem, because browsing and using standard python-files shows no lag whatsoever, even with all Pylance-features etc.

**Comment by roblourens** [comment]
Are you remoting with Remote-SSH? We have some open issues about performance in that scenario and are working on it

**Comment by bdch1234** [comment]
Yes, I’m using the Remote-SSH extension to VSCode

**Comment by roblourens** [comment]
Ok thanks, we are working on this scenario
