### ISSUE TITLE
outline focus (highlight) should reflect position of current selected cell

### ISSUE THREAD

**Issue by yuuuxt** [microsoft/vscode-jupyter#11611]
a sample notebook:
```
# header 1
	cell 1
	cell 2
## header 1.1
	cell 3
	cell 4
# header 2
	cell 5
	cell 6
```
current behavior is:
1. click `header 1` in outline, `header 1` is highlighted, the editor goes to show `header 1`
2. scroll in notebook to select `cell 5` (`header 1` section is now invisible)
3. in outline view, `header 1` is still highlighted, but `header 2` is expected to be highlighted, as we are currently under section `header 2`

expected behavior is:
1. if only one cell is selected (or edited): the focus of outline should automatically select the corresponding header, e.g.
```
select cell 1 - highlight header1
select cell 3 - highlight header 1.1
select cell 6 - highlight header 2
```
4. if multiple cells are selected: (no highlight is fine)

**Comment by roblourens** [comment]
I see this when `notebook.outline.showCodeCells` is disabled, not sure if we are intending to find the parent and focus it or not

**Comment by jrieken** [comment]
@yuuuxt Do you have 'Follow Cursor' enabled?

<img width="471" alt="Screenshot 2022-10-12 at 09 07 19" src="https://user-images.githubusercontent.com/1794099/195273577-f06ef70b-44dd-4317-a5f2-180588a64255.png">

**Comment by yuuuxt** [comment]
No I didn't; 

Now I ticked it, but it doesn't have the expected behavior - the highlight item in outline doesn't follow my selection.

**Comment by yuuuxt** [comment]
How do you evaluate the priority of this feature?  Currently user cannot find what section they are currently are if they just scroll to browse - As I mentioned, "follow cursor" is very limited.

**Comment by yuuuxt** [comment]
Seems it's of low priority. Workarounds are (both need "follow cursor"): 
- turn `notebook - outline - show code cells` on, then every cell appears in outline. It looks cumbersome, but at least shows current cell position;
- quickly add a markdown cell and then delete (in edit mode: `amdd` / `bmdd`) to let the outline jump to the next header/markdown cell. It keeps outline cleaner, but notice that the selected header is the next header.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
