### ISSUE TITLE
Code loss/corruption when jupyter crashes.

### ISSUE THREAD

**Issue by JensvandeZande** [microsoft/vscode-jupyter#11613]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When I try to interrupt a cell execution, jypiter crashes. When it crashes all my code in the notebook is gone, like permanently gone. This happens with open unsaved notebooks, as well as saved notebooks.

In Untitled2.ipynb I tried to interrupt a cell execution. Jupyter crashes and results in code loss in Untitled2.ipynb but also in Untitled1.ipynb. This behaviour is also there when the notebooks are saved. The saved notebooks get somehow corrupted when jupyter crashes. 

In my opinion this is a major bug, I lost all my work 3 to 4 times now because of this.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/49940005/195044851-a4740434-a34e-4be5-bbb7-21264f34747b.png">

<img width="636" alt="image" src="https://user-images.githubusercontent.com/49940005/195045016-e63c4c51-85ea-4b46-a380-b234f3e24819.png">

### VS Code Version

1.71.0

### Jupyter Extension Version

v2022.8.1002431955

### Coding Language and Runtime Version

python 3.10.6

### Language Extension Version (if applicable)

python Extension v2022.14.0

### Running Jupyter locally or remotely?

N/A or Not sure

**Comment by roblourens** [comment]
Could you check for errors in dev tools (Help > Toggle Developer Tools) when this happens?

Also could you share the code that you are running that causes a crash when interrupted?
