### ISSUE TITLE
Cached variable values never update for hover in a notebook

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1162]
The kernelVariables class does not check the current execution count of a notebook when matching on hover. It needs to do so or it might use the wrong version of a variable.

To reproduce this problem:
1. Open notebook with a cell like so : ```x = 10```
1. Run the cell
1. Hover over cell
1. Add another variable to cell
1. Run cell again.

Second variable won't hover value because the cached value is the x = 10.

**Comment by DavidKutu** [comment]
this is fixed by using native notebooks
