### ISSUE TITLE
python import fails after recent upgrade

### ISSUE THREAD

**Issue by mgenet** [microsoft/vscode-jupyter#11639]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

We are using the FEniCS library, installed with `conda create -n fenicsproject -c conda-forge fenics`. Since the September upgrade, `import fenics` in a jupyter notebook cell opened with vscode fails with `Could not find DOLFIN pkg-config file. Please make sure appropriate paths are set.`, even though `python -c "import fenics"` still works in the vscode terminal, and the notebook imports fine when run with JupyterLab. Any idea what might be going on? Thanks!

### VS Code Version

1.72.1

### Jupyter Extension Version

1.0.9

**Comment by DonJayamanne** [comment]
@mgenet thanks for filing the issue, please could you provide the following information
* Version of Jupyter extension
The version you have listed does not seem to be correct, the latest version is `2022.9.120*`
* Output from the `Jupyter` output panel.
please could you upload the logs from the `Jupyter` output panel, you can get there output using the command `Jupyter: Show Output`. Please remember to copy and upload all of the output.
* What version of Python are you using 
* What type of Python environment are you using (is it conda? pipenv, etc)

**Comment by mgenet** [comment]
While trying to gather the additional info, I realized it started working again, even though I did not change anything… Sorry & Thanks!
