### ISSUE TITLE
Shorten extension activation time by not unnecessarily awaiting async tasks within ExtensionSingleActivationServices

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11640]
_Originally posted by @DonJayamanne in https://github.com/microsoft/vscode-jupyter/pull/11572#discussion_r990499647_

        this blocks the loading of the extension, can this be done in the background, 
        all of the activate methods run when extension loads and we wait for all of them to complete.
        i would suggest using the IExtensionSync.... interface

I didn't realize that there is an `IExtensionSyncActivationService` which doesn't block (`await` for long running tasks), and should be used whenever possible.

**Comment by amunger** [comment]
This sounds backwards - by definition synchronous will block. Are you implying that we should not be awaiting the asyncronous tasks within those activations? We should be careful with doing that since it's an easy way to introduce race conditions

**Comment by DonJayamanne** [comment]
> by definition synchronous will block. Are you implying that we should not be awaiting the asyncronous tasks within those activations? We should be careful with doing that since it's an easy way to introduce race conditions

Everything in node is single threaded, hence any code thats not async will alway be blocking (the only way to make something non-blocking is to break out of the current event loop like using `setTimeout` or the like).

If you want some startup code to run when extension loads, and if it has some async stuff, 
* If this code contains some async code and MUST be completed before all of the extension starts completely then use the `async` version of the interface
Async stuff could be like loading somethings from files or the like.
* If this code contains some async code and need not be completed before all of the extension starts completely then use the `non-async` (`IExtensionSyncActivationService`) version & do not await on the promises (this way the activation will not be avaiting on these promises).

Yes, the node event loop will eventually run the other promises and delay everything (that cannot be avoided ever, however we can minimize the time taken to load the extension by not waiting on those promises).

**Comment by rebornix** [comment]
> We should be careful with doing that since it's an easy way to introduce race conditions

IMHO we shouldn't take the assumption that an `ExtensionSingleActivationService` module will be created and **fully initialized** before other non `ExtensionSingleActivationService` modules. We might already take it for guaranteed, let's go through them in each one's area to ensure this doesn't happen.

**Comment by amunger** [comment]
Maybe a better title would be "Shorten extension activation time by not unnecessarily awaiting async tasks within `ExtensionSingleActivationService`s" ?
