### ISSUE TITLE
Change how context key `jupyter.controllersLoaded` is updated

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#11647]
@IanMatthewHuff 
As per discussion I think we can:
* Directly use the Python API to determine if python envs are available or not instead of checking the controllers.
* Remove the code to update `jupyter.controllersLoaded` from the `ControllerLoaded` class

**Comment by IanMatthewHuff** [comment]
Verification:

Check that "Install Python" command doesn't show up in the kernel picker if you have the python extension installed and have some python on your system
Check that "Install Python" command does show up in the kernel picker if you have the python extension installed and do not have any python environments on the system (VM for this easiest?)
