### ISSUE TITLE
Flaky Kernels Finder integration tests

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11654]
Kernels Finder tests are now flaky as we don't `await` for the kernel finders to finish scanning, so when we are ranking kernels, the kernels are not guaranteed to be ready https://github.com/microsoft/vscode-jupyter/blob/42c3299ba4b0fe9f6b2c6ce5c45ac6fe691a2695/src/test/datascience/kernel-launcher/kernelFinder.vscode.test.ts#L65.

We could potentially add internal api to wait for kernel finders to finish kernel discovery. However I see it as a good chance to move it to unit tests. Kernel ranking doesn't need to depend on real kernel finder to work.

**Comment by DonJayamanne** [comment]
i noticed the kernel finder integration as well, i will convert to unit test.

**Comment by DonJayamanne** [comment]
Fixed
