### ISSUE TITLE
Listcomps are blockers for running by line

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#1165]
Create the following cell and try to run by line:
```
print('hello')
myList = [x ** 2 for x in range(0, 100000)]
print('world')
```
Each line of the listcomp is treated like a line. Since there is no way to step out / run past you are stuck with the entire thing if you want to debug a later line.

**Comment by DavidKutu** [comment]
on the new run by line, you can either stop it and keep running normally, or interrupt the execution.
