### ISSUE TITLE
Plotly No renderer could be found for mimetype "application/vnd.plotly.v1+json"

### ISSUE THREAD

**Issue by ddobrinskiy** [microsoft/vscode-jupyter#11658]
## Environment data

-   VS Code version: 1.72.0
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:19:55.212Z (1 wk ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
-   Jupyter Extension version (available under the Extensions sidebar): v2022.9.1202862440
-   Python Extension version (available under the Extensions sidebar):  v2022.16.1
-   OS (Windows | Mac | Linux distro) and version: Mac 
-   Python and/or Anaconda version: `Python 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:07:06) [Clang 13.0.1 ] on darwin` 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

Plotly charts displayed in-line

## Actual behaviour

```python
import plotly.graph_objects as go
go.Figure(data=go.Bar(y=[2, 3, 1]))
```
this code leads to `No renderer could be found for mimetype "application/vnd.plotly.v1+json", but one might be available on the Marketplace.` error.

The workaround from [3936](https://github.com/microsoft/vscode-jupyter/issues/3936) just leads to empty output

```python
import plotly.io as pio
pio.renderers.default = 'iframe_connected'
```

Screen-capture: [link](https://drive.google.com/file/d/1QyDZ4Qy4bybWt3zSDCP0CunqvWLl1hd_/view?usp=sharing)

**Comment by ddobrinskiy** [comment]
Screencapture

![2022-10-14 15 05 24](https://user-images.githubusercontent.com/29500178/195832468-a1d8235f-7220-440a-a9ab-078bec87b8fc.gif)

**Comment by TheHotChilli** [comment]
I have the same Issue using px.imshow

- Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
- Jupyter Extension version (available under the Extensions sidebar): v2022.9.1202862440
- Python Extension version (available under the Extensions sidebar): v2022.16.1
- OS: Windows 10 Home (Version 21H2)
- Python: Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, please could you confirm you have installed the `Jupyter Notebook Rdnderers` extension & has been updated to the latest version.
This is responsible for rendering the above mime type.

**Comment by ddobrinskiy** [comment]
Installing [Jupyter Notebook Renderers](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter-renderers) solved the issue, many thanks @DonJayamanne !

**Comment by Liquidsilver2000** [comment]
> Installing [Jupyter Notebook Renderers](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter-renderers) solved the issue, many thanks @DonJayamanne !

This helped me as well ..simply click the link and it will open up the extension in VSCode and once you install the extension you will see your plot automatically update.

**Comment by Babarazizkhan** [comment]
thank you for this solution i can resolve the error...
