### ISSUE TITLE
Render api

### ISSUE THREAD

**Issue by PeterWone** [microsoft/vscode-jupyter#11656]
I maintain vsc-print, which adds print capabilities to VS Code.  One of your users logged an issue on my repo because he wanted to print a rendered Jupyter notebook.

To allow me to support you in a way that maintains consistency with your preview pane I need you to surface a rendering API that takes a string (the content of a notebook file) and returns HTML ready for display in a browser. If this depends on assets like stylesheets I also need a way to resolve an asset URI to a resource Buffer. For security reasons scripts can only be delivered embedded in the HTML.

If you support this you will implicitly support render to PDF because printing is via workstation browser. Chromium derivatives can support print to PDF directly and Windows supports print to PDF for any browser.

**Comment by amunger** [comment]
We do have an existing `Jupyter: Export to HTML` command that might be useful here, rather than having to re-build the entire rendered notebook yourself.

**Comment by PeterWone** [comment]
@amunger Thank you! I will examine the code handling `Jupyter: Export to HTML` -- this level of decoupling is highly desirable.

**Comment by amunger** [comment]
closing for now
