### ISSUE TITLE
Kernel Picker Experiment: Persist selection on document open

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#11665]
Right now when documents are open the kernel picker experiment starts in a state where nothing is selected. You need to start by picking a source and a controller. We should persist selection here.

1. We could persist the selection in some type of storage OR
2. If we see a selected kernel (due to vs code core's storage of the selection) we can select the kernel source associated with that controller

2 sounds better if possible.

**Comment by DonJayamanne** [comment]
fixed in current kernel pucker via mru
