### ISSUE TITLE
help() function causes kernel to crash

### ISSUE THREAD

**Issue by VincentGurgul** [microsoft/vscode-jupyter#11662]
Type: <b>Bug</b>

1. open jupyter notebook in vscode
2. type "help()" and execute the cell
3. a window to type in a keyword should appear (it does so in ipython and jupyter lab), instead the cell keeps executing forever and can't be interrupted, one must restart the kernel and loses all variables

Extension version: 2022.9.1202862440
VS Code version: Code 1.72.2 (Universal) (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:30.254Z)
OS version: Darwin x64 20.6.0
Modes:
Sandboxed: No

**Comment by amunger** [comment]
are you looking in the right place? The input box can be easy to miss since it can be pretty far removed from where you are focused in the editor:
<img width="524" alt="image" src="https://user-images.githubusercontent.com/2019016/195907729-f60a4bf0-6e1b-4f75-b8ae-7ab4a11a2888.png">

**Comment by VincentGurgul** [comment]
Ok, I did not expect it to be up there. I did indeed miss it, everything works as intended. Thank you very much for taking the time and clearing this up!
