### ISSUE TITLE
Misleading connection error message from 3rd party jupyter server

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11675]
When 3rd party jupyter server failed to connect, we often show **`https://remote` is not reachable**. The url in the error message is not useable as it's not telling users which server is unavailable.

<img width="808" alt="image" src="https://user-images.githubusercontent.com/876920/196068082-7d60f6a0-8c6e-4ef1-81ba-9920d8446479.png">

**Comment by IanMatthewHuff** [comment]
Was a touch hard to verify, but I just used the debugger to junk the url returned by the Azure ML extension and it looks like it's doing the right thing now:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/812783/198356240-e0a44bd7-bb85-4444-9dc5-0d43a353fea9.png">
