### ISSUE TITLE
Debugger event duplication when running by line

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#1168]
So far this seems mostly benign to me. But when looking at the debug console it seems that each time you run by line you get an extra instance of all associated debugger events. For example, the first time running a simple one line cell it looks like this:

![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/fc2d6f50-0f7a-40cc-9378-c396c30e10cf)

Now run by line that cell a second and a third time and it looks like this:
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/7c132c23-207d-4c9b-9373-1d74e525cd11)

Note three copies of all events. The number of copies is always the number of times you have run by line.

**Comment by DavidKutu** [comment]
doesn't happen on the new run by line.
