### ISSUE TITLE
Jupyter doesn't finish kernel detection before resolving api method addRemoteJupyterServer

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11681]
Neither `addRemoteJupyterServer` nor `getSuggestedController` will guarantee creating controllers for the kernels found in the kernel finders as now they are push model. 

This is breaking the workflow:

* Users click run cell
* Kernels not available, users pick a kernel source command from the kernel picker
* kernel source command calls the `addRemoteJupyterServer` api to register a remote server
* 🐛 Kernels are populated to VS Code and VS Code continues to run the cells

**Comment by amunger** [comment]
is there an easy way to verify this? Are you enabling an experiment to get `addRemoteJupyterServer` to run from the kernel picker? The only options I get are to install suggested extensions, and browse marketplace

**Comment by rebornix** [comment]
@jungaretti just verified this for us. I'll ask @jungaretti if he has access to adding a `verified` label for this issue.

**Comment by jungaretti** [comment]
Verified! Unfortunately, I don't have permission to add the label to this issue.
