### ISSUE TITLE
Kernel session not suggested even though it's matching the document and used in last session

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11688]
* Connect a locally launched jupyter server
* Create an untitled notebook
* Run a cell
* Reload the window
* The previous kernel session is picked/selected, but it's not the suggested kernel in the kernel list

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/876920/196326674-4a1a7f21-b6c5-4ae1-b5d7-92177619401a.png">

**Comment by DonJayamanne** [comment]
hmm, that's weird, we have a great for this.
possibly a race condition with the new code
I'll have a look tomorrow

**Comment by rebornix** [comment]
@DonJayamanne thanks, we can catch up on this tomorrow. From what I read, we didn't seem to suggest kernel sessions at all 

https://github.com/microsoft/vscode-jupyter/blob/948cfcc2178c817d8a0b548056464d562c37d731/src/notebooks/controllers/controllerDefaultService.ts#L98

https://github.com/microsoft/vscode-jupyter/blob/948cfcc2178c817d8a0b548056464d562c37d731/src/notebooks/controllers/controllerDefaultService.ts#L119

We are only calculating preferred controllers for `startUsingRemoteKernelSpec`, but never `connectToLiveRemoteKernel`.

**Comment by DonJayamanne** [comment]
this should be working now with the new quick pick
