### ISSUE TITLE
DF preview in variable explorer/data tip not aligned 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#1169]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Create any pandas data frame 
2. Open variable explorer
3. Hover over the data frame's value  
4. Hover over data frame's data tip in a cell 

Variable explorer: 
- Values are not aligned and spacing does not allow for easy interpretation
- Data frame preview does not include data types of columns 

Data Tip:
- Data frame preview does not include data types and is not easily understandable since rows appear are displayed as one continuous string

## Actual behavior
![DF Preview ](https://user-images.githubusercontent.com/19276747/83205419-5918e900-a103-11ea-86f9-21f6c6329929.gif)

## Expected behavior

Both previews of data frames should include data frame name, column names, data types per column, dimensions of the data frame, and a few* rows. 

*Number of rows/cols to be displayed TBD, preview could be capped depending on data frame size* 

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by DavidKutu** [comment]
this is fixed
