### ISSUE TITLE
Move off IControllerRegistration#onCreated

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11694]
We now introduced `onChanged` to support sending multiple controllers creation in one event and also support delete event, it can replace the existing `onCreated` event. https://github.com/microsoft/vscode-jupyter/pull/11685

We want to go through `onCreated` usage in each component to see if we can optimize with the batch event, instead of a simple `onCreated(handler)` to `onChange(e => e.added.foreach(controller => handler(controller)` replacement.

**Comment by DonJayamanne** [comment]
I've got a PR for this https://github.com/microsoft/vscode-jupyter/pull/11695
