### ISSUE TITLE
How to connect remote jupyter behind a socks5 proxy

### ISSUE THREAD

**Issue by fancyerii** [microsoft/vscode-jupyter#11708]
I want to use vscode with jupyter plugin to debug codes running in a remote server. But this server can only be accessed by ssh. I can use "ssh -D 12345 remote-server" to setup a socks5 proxy. Then I can open browser using this proxy to open ipynb file and write codes in cell and run it remotely.

But I want to use vscode with jupyter to debug the codes remotely.

**Comment by DonJayamanne** [comment]
Thanks for reaching out to us.
Have you considered installing VS Code on the remote machine and accessing that via SSH,
see here https://code.visualstudio.com/docs/remote/ssh-tutorial

**Comment by fancyerii** [comment]
> Thanks for reaching out to us. Have you considered installing VS Code on the remote machine and accessing that via SSH, see here https://code.visualstudio.com/docs/remote/ssh-tutorial

Thanks. But I have to ssh a jump server A and then ssh to server B through A. Could you tell me how can I do this?

**Comment by DonJayamanne** [comment]
@roblourens can you help here? thanks

**Comment by roblourens** [comment]
If you can set up your ssh config to connect in one shot using `ProxyJump` or `ProxyCommand` then Remote-SSH should work. If you don't want to use Remote-SSH

> Then I can open browser using this proxy to open ipynb file and write codes in cell and run it remotely.

That probably also works with the Jupyter extension.
