### ISSUE TITLE
Setting for turning datatips all the time on/off

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#1170]
We need a separate setting to allow users to toggle whether datatips-all-the-time once we enable run-by-line. It should be on by default.

**Comment by DavidKutu** [comment]
@roblourens, does VS Code have a way to turn off datatips? (hovering)

**Comment by roblourens** [comment]
Sorry, which hovers are you referring to?

**Comment by DavidKutu** [comment]
when you're debugging and you hover on a variable, it shows the content of the variable

**Comment by roblourens** [comment]
I think you want https://github.com/microsoft/vscode/issues/127676, which I can fix. I'm not sure you want a setting for it, because these hovers conflict with the language hovers, but you can hold alt to see the other hover
