### ISSUE TITLE
Support dispose/stop in JupyterUriProvider

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11718]
Currently `JupyterUriProvider` offers server uris but when users want to disconnect to the server, there isn't a way to do that, except clearing the endpoint cache in Jupyter extension. However if users reload the window, the server uri disconnected in previous session is then back.

Since the server uri info is provided by the provider extension, it can provide a `dispose` method in `IJupyterUriInfo` to allow a disconnect from the Jupyter extension side.

**Comment by DonJayamanne** [comment]
I don't think this is necessary, the provider could instead just dispose the handle and trigger a `onDidChangeHandles` event. that way the Jupyter extension will automatically clear our the corresponding uri (which has a 1-1 relationship)
