### ISSUE TITLE
Kernel crashes when executing code

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#11713]
Feedback on the marketplace from Javier Rojas:

> it crashes every time
> I ran many code lines and it crashes when I try to plot things or the process takes a lot

I assume those are kernel crashes.

**Comment by kieferrm** [comment]
@DonJayamanne can you pls add what concrete information we need from Matt to track down this issue

**Comment by DonJayamanne** [comment]
Hi Javier, I'm sorry you're running into this issue.
Please could you provide the following information:
* By `crashes every time`, do you mean VS Code crashes or the kernel crashes. Please could you provide a screenshot of this failure so I understand exactly what is failing.
* Please could you reload VS Code and attempt to repro the issue & then copy the output from the `Jupyter` output panels.
    * Please upload all of the contents of this output into this issue.
* Finally please could you provide the a sample notebook you are running (which causes the failure) along with the necessary packages that need to be installed
