### ISSUE TITLE
Support reconnect/create in JupyterUriProvider 

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11717]
Currently `JupyterUriProvider` supports providing a list of jupyter server uris to the Jupyter extension but when the endpoint is no longer alive, and Jupyter still holds a connection to the endpoint, there isn't a way to reestablish a new connection easily, other than

* Clear that connection
* Request the provider extension to create a new connection

It would be great that if we can reinitiate/create a live connection to replace the legacy one. The `JupyterUriProvider` can reuse the same handle and when Jupyter asks for `getServerUri(handle)`, it can then reinitiate a new connection and provide the new url/token to Jupyter to replace the old one.

**Comment by DonJayamanne** [comment]
@rebornix not sure i see the purpose for this.
I think we can get the exact same behaviour today by:
* Disposing that related url/handle
* Then user will have to select the server (for the new handle) and from the server select a new kernel

Why wouldn't that work, would the end workflow/ux be the same?

**Comment by DonJayamanne** [comment]
Lets close this issue for now, been open and we haven't run in to any issues here
