### ISSUE TITLE
Conda environment not detected

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#11710]
This is feedback on the marketplace from matt triano:

> I've been using conda and jupyter lab/notebooks for years. I've been using VSCode for a few weeks while developing and deploying infrastructure and I finally started using the infra I set up to do some data science work, but I couldn't get VSCode to show the conda env I made and registered as a kernel (using this pattern https://stackoverflow.com/questions/39604271/conda-environments-not-showing-up-in-jupyter-notebook, which I've used 1 to 4 times a month for the past 4 years). I restarted VSCode (having to reconnect 4 ssh sessions), but my kernel still wasn't showing up.

> My VSCode environment is pretty clean (I only have MSFT's official extensions for Remote SSHing, python, docker, and jupyter (and the official extensions packaged with those extensions). VSCode's port forwarding and Docker extension are very nice, and this might just be a temporary delay until VSCode sorts itself out, but if VS code wants to win me away from my prior workflow, it has to provide a superior workflow, and my kernels show up in jupyter as soon as I open a new notebook whereas I can't select my kernel in VSCode 30 minutes on.

**Comment by kieferrm** [comment]
@DonJayamanne can you pls add what concrete information we need from Matt to track down this issue

**Comment by DonJayamanne** [comment]
Hi Matt, I'm sorry you're running into this issue.
Please could you enable logging as follows and provide some logs that would help us determine why you aren't seeing the Conda Environment:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Open settings & go into `Python->Logging`
* Change the value to `debug`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` and `Python` output panels.

Please remember to provide the outputs from both `Jupyter` and `Python` outputs.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
