### ISSUE TITLE
Add side-by-side layout of input and output cells

### ISSUE THREAD

**Issue by ragdollfun** [microsoft/vscode-jupyter#11734]
Hello everyone !

Would it be possible to display output cells on the side of the corresponding input cells instead of below:

i.e. this
![image](https://user-images.githubusercontent.com/68953298/197157320-5dc01cdd-1730-4f2d-ac93-38cc75de6f11.png)
(example from Matlab's "live editor", notice the buttons on the top right that allow to switch between "output on right", "output inline" and "hide input")

instead of this
![image](https://user-images.githubusercontent.com/68953298/197157959-2edb67ae-cc70-4109-a0a9-dd3931348a72.png)
(look at all the wasted screen real estate on the right side)

Also, it seems like this is already a feature in JupyterLab:
https://github.com/jupyter/notebook/issues/1283#issuecomment-1275156078
https://github.com/jupyterlab/jupyterlab/pull/10648

**Comment by amunger** [comment]
This would be handled in the core. I think https://github.com/microsoft/vscode/issues/131206 covers this feature request
