### ISSUE TITLE
Investigate possible ability to slip threads to enable more dynamic line by line execution....

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#1173]
Running a cell like this line by line doesn't really accomplish what a user hopes it will.

```python
df.head(5)
df.head()
```
Stepping over the first line, the user expects to see 5 rows written to output. Stepping the second line shows the default set of lines.

Problem here is due to the asynchronous nature of some libraries. The call to df.head returns immediately, but is processed over time. 

Is there a way we can address this scenario? 

Note that this should not hold up the first release of run-by-line

**Comment by DavidKutu** [comment]
In the case of `.head()` It won't work, not even with normal debugging. This is an issue of how debugpy handles it.
