### ISSUE TITLE
Running cell in new notebook files results in prompt for URI

### ISSUE THREAD

**Issue by olguzzar** [microsoft/vscode-jupyter#11742]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. Create new notebook file
2. In the new file, type a simple python code cell
3. Run the cell
4. You are prompted to enter a remote Jupyter server URI for it to run
5. Esc out of that prompt and try running again, and the cell executes successfully without the URI prompt
6. This only happened with the first new notebook file I created - subsequent ones just successfully used my default local python kernel

Recording of repro is [here](https://microsoft-my.sharepoint.com/:v:/p/olguzzar/EVL-B7USGmFFsGjyDYKXPzEBwYqSEwrTCQLm0UxyDA0cZg?e=LZOfBg) starting at 1:10

### VS Code Version

Version: 1.72.2 (user setup) Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075 Date: 2022-10-12T22:15:18.074Z Electron: 19.0.17 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10.0.22621 Sandboxed: No

### Jupyter Extension Version

v2022.9.1202862440

**Comment by olguzzar** [comment]
https://user-images.githubusercontent.com/95261576/197532870-80cd7530-1f87-4eb9-8ada-40b594afc9ff.mp4

Here's the exact snippet of video where this is repro'd - having some issues with the permissions on the uploaded video above

**Comment by DonJayamanne** [comment]
I'm so sorry for not getting back to you.


please could you replicate this issue with the latest pre-release version of the Jupyter extension and send the `jupyter ` logs from the output panel band `Jupyter`

**Comment by olguzzar** [comment]
Hi @DonJayamanne, it seems I can no longer repro this issue in the pre-release or release version of the extension - it now correctly defaults to the Python kernel rather than the "Connect to a Jupyter Server" as it did in the video. I will make sure to update this issue with the logs if I'm able to repro again!

**Comment by DonJayamanne** [comment]
Will close this for now, thanks
If this comes back please feel free to ping here and I'll re-open this issue or create a new issue
