### ISSUE TITLE
Wide Matplotlib figure not proportionally rescaled when window is smaller than figure with retina resolution images. 

### ISSUE THREAD

**Issue by brendanjmeade** [microsoft/vscode-jupyter#11749]
## Environment data

-   VS Code version: 1.72.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.10.1102961034
-   Python Extension version (available under the Extensions sidebar): v2022.16.1
-   OS (Windows | Mac | Linux distro) and version: macOS 12.6
-   Python and/or Anaconda version: 3.10
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Expected behaviour

Wide matplotlib images should be proportionally scaled when retina resolution is used.  

## Actual behaviour

Wide matplotlib images are not proportionally scaled when retina resolution is used.  In vscode-jupyter notebooks, a matplotlib figure may have a width (specified by `figsize`) that makes it wider than the window.  These images are rescaled by vscode-jupyter to fit inside the visible window width.  This scaling is done proportionally for the case when non-retina images are used.  This looks great and I think this is the correct behavior.  However, if retina images are requested (using `%config InlineBackend.figure_format = "retina"`), then the images are only resized horizontally rather than horizontally and vertically as they are in the non-retina case.  This results in images that look squashed in the horizontal direction.  This is inconsistent with the non-retina behavior.  Proportional image scaling for retina and non-retina cases would be fantastic! 

## Steps to reproduce:

1. Figures proportionally resized with window.  If the horizontal scale of an image is greater than the window width, then both horizontal and vertical sizes are scaled proportionally.

```
import numpy as np
import matplotlib.pyplot as plt
plt.figure(figsize=(20, 3))
plt.plot(np.random.rand(100))
plt.show()
```

2. Figures are **not** proportionally resized with window size.  Vertical size stays the same, but horizontal size is squished.
```
%config InlineBackend.figure_format = "retina"
import numpy as np
import matplotlib.pyplot as plt
plt.figure(figsize=(20, 3))
plt.plot(np.random.rand(100))
plt.show()

## Summary figure

<img width="1195" alt="Screen Shot 2022-10-22 at 9 03 59 PM" src="https://user-images.githubusercontent.com/4225359/197368557-ea0fd101-b5b1-42b3-a847-33e49bf4b0d5.png">

**Comment by DonJayamanne** [comment]
I'm sorry for missing this issue and never getting back to you on this, will look into this today.

**Comment by DonJayamanne** [comment]
I can repro this issue at my end.
