### ISSUE TITLE
Navigate to file/line when clicking on traceback

### ISSUE THREAD

**Issue by RossBencina** [microsoft/vscode-jupyter#11750]
## Environment Data
VS Code version: 1.72.0
Unified Python Extension version: v2022.16.1
Jupyter Extension version: v2022.9.1202862440
Python Version: 3.10.7 64-bit
OS and version: Windows 10 10.0.19043

## Actual behavior

When running a cell in the VSCode IPython Notebook editor, if a traceback is printed, you can't click on an item in order to navigate to the matching file/line.

## Expected behavior
Should navigate when clicking on file/line entries in traceback.

## Steps to reproduce

1. Create a file `buggy.py` containing the following code:
```
 def trigger_bug():
        a = 1
        b = 2
        c = 0
        return (a+b)/c
```
2. Create a new notebook `runbug.ipynb`, enter the following code in a cell, and run the cell:
```
import buggy
buggy.trigger_bug()
```

3. A traceback is printed. Try to click (or ctrl-click) on a file/line indicator inside a traceback. Nothing happens.

## Related

This feature was previously added for clicking on tracebacks when running Python scripts in the terminal window. See: https://github.com/microsoft/vscode-python/issues/608

**Comment by amunger** [comment]
this was previously implemented but the changes in the latest ipykernel versions have broken the functionality and made it more difficult
