### ISSUE TITLE
Test adoption of the new Python Extension API

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#11755]
Testing adoption of the new Python Extension API for discovering Python Enviornmnents

Refs: #7583

- [x] MacOS @IanMatthewHuff 
- [x] anyOS @rebornix 
- [x] Windows @amunger 
- [ ] WSL @roblourens 

Complexity: 5

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2311755%0A%0A&assignees=DonJayamanne)

---

### Pre-Test
* Keep track of the kernels displayed in the kernel picker

### Requirements

- Install pre-release Jupyter extension
- Install pre-release Python extension
- Install VS Code Insiders

### Scenarios to test
* [ ] Verify the same kernels (kernel specs and Python environments) are still displayed in the kernle picker
* [ ] New Virtual environments are detected and displayed in the Kernel picker
    Note: You need to have already executed a cell in some notebook
    Then create a virtual environment within VS Code
    I.e. the goal is to test detection of new virtual envs after the extension has been used for a while
    * [ ] Verify you are prompted to install IPyKernel into this Python enviornment when running a Notebook cell against this kernel
    * [ ] Verify you are prompted to install IPyKernel into this Python enviornment when running an Interactive Window cell such a new Python Environment (either re-create a new env or uninstall IPyKernel)
    * [ ] Verify you are prompted to install Pandas data frame into this Python enviornment when using the Data Frame viewer 
    To test this, create a few variables, at least one with a list e.g. `a = [1,2,3]` and use the variable viewer to open the variable `a`
* [ ] New Conda environments are detected and displayed in the Kernle picker
    Note: You need to have already executed a cell in some notebook
    Then create a conda environment within VS Code
    I.e. the goal is to test detection of new virtual envs after the extension has been used for a while
    * [ ] Verify you are prompted to install IPyKernel into this Python enviornment when running a Notebook cell against this kernel
    * [ ] Verify you are prompted to install IPyKernel into this Python enviornment when running an Interactive Window cell such a new Python Environment (either re-create a new env or uninstall IPyKernel)
    * [ ] Verify you are prompted to install Pandas data frame into this Python enviornment when using the Data Frame viewer 
    To test this, create a few variables, at least one with a list e.g. `a = [1,2,3]` and use the variable viewer to open the variable `a`
* [ ] Re-load VS Code and verify you can pick a Kernel Spec before Python environments
    I'm hoping some machines are slow enough and we can see Kernel Specifications before Python environments in the kernel picker.
    In the past we regressed in this space and Jupyter extension waited for ALL python environnents to be loaded before displaying Kernel Specs on disc.
    We're verifyhing the fact that some kernels will appear before others
* [ ] Verify local kernel specs appera before Remote Kernel specs
    Connect to a local Jupyter server after having started a jupyter server using `jupyter notebook --no-browser --NotebookApp.allow_origin=*`
    In the past we regressed in this space and Jupyter extension waited for ALL python environnents to be loaded before displaying Kernel Specs on disc.
    We're verifyhing the fact that some kernels will appear before others
* [ ] Verify debugging works and uses the right Python environment

* [ ] Test other parts of the extension that you believe could be impacted by adopting the new Python Extension API

**Comment by rebornix** [comment]
@rebornix 's check list

* [ ] Verify the same kernels (kernel specs and Python environments) are still displayed in the kernle picker
* [ ] New Virtual environments are detected and displayed in the Kernel picker
    Note: You need to have already executed a cell in some notebook
    Then create a virtual environment within VS Code
    I.e. the goal is to test detection of new virtual envs after the extension has been used for a while
    * [ ] Verify you are prompted to install IPyKernel into this Python enviornment when running a Notebook cell against this kernel
    * [ ] Verify you are prompted to install IPyKernel into this Python enviornment when running an Interactive Window cell such a new Python Environment (either re-create a new env or uninstall IPyKernel)
    * [ ] Verify you are prompted to install Pandas data frame into this Python enviornment when using the Data Frame viewer 
    To test this, create a few variables, at least one with a list e.g. `a = [1,2,3]` and use the variable viewer to open the variable `a`
* [ ] New Conda environments are detected and displayed in the Kernle picker
    Note: You need to have already executed a cell in some notebook
    Then create a conda environment within VS Code
    I.e. the goal is to test detection of new virtual envs after the extension has been used for a while
    * [ ] Verify you are prompted to install IPyKernel into this Python enviornment when running a Notebook cell against this kernel
    * [ ] Verify you are prompted to install IPyKernel into this Python enviornment when running an Interactive Window cell such a new Python Environment (either re-create a new env or uninstall IPyKernel)
    * [ ] Verify you are prompted to install Pandas data frame into this Python enviornment when using the Data Frame viewer 
    To test this, create a few variables, at least one with a list e.g. `a = [1,2,3]` and use the variable viewer to open the variable `a`
* [ ] Re-load VS Code and verify you can pick a Kernel Spec before Python environments
    I'm hoping some machines are slow enough and we can see Kernel Specifications before Python environments in the kernel picker.
    In the past we regressed in this space and Jupyter extension waited for ALL python environnents to be loaded before displaying Kernel Specs on disc.
    We're verifyhing the fact that some kernels will appear before others
* [ ] Verify local kernel specs appera before Remote Kernel specs
    Connect to a local Jupyter server after having started a jupyter server using `jupyter notebook --no-browser --NotebookApp.allow_origin=*`
    In the past we regressed in this space and Jupyter extension waited for ALL python environnents to be loaded before displaying Kernel Specs on disc.
    We're verifyhing the fact that some kernels will appear before others
* [ ] Verify debugging works and uses the right Python environment

* [ ] Test other parts of the extension that you believe could be impacted by adopting the new Python Extension API
****

**Comment by amunger** [comment]
> Then create a conda environment within VS Code

How do I do this? I've only ever used the conda terminal to work directly with conda.

> Re-load VS Code and verify you can pick a Kernel Spec before Python environments

Python environments is not an event in time. Do you mean before all python environments are loaded in the kernel picker?

**Comment by IanMatthewHuff** [comment]
> Re-load VS Code and verify you can pick a Kernel Spec before Python environments
I'm hoping some machines are slow enough and we can see Kernel Specifications before Python environments in the kernel picker.

This exhibits on my machine pretty easily. I do see the Kernel Specs and can pick one before the Python Environments load.

**Comment by IanMatthewHuff** [comment]
@IanMatthewHuff 's Copy:
* [ ] Verify the same kernels (kernel specs and Python environments) are still displayed in the kernle picker
* [ ] New Virtual environments are detected and displayed in the Kernel picker
    Note: You need to have already executed a cell in some notebook
    Then create a virtual environment within VS Code
    I.e. the goal is to test detection of new virtual envs after the extension has been used for a while
    * [ ] Verify you are prompted to install IPyKernel into this Python enviornment when running a Notebook cell against this kernel
    * [ ] Verify you are prompted to install IPyKernel into this Python enviornment when running an Interactive Window cell such a new Python Environment (either re-create a new env or uninstall IPyKernel)
    * [ ] Verify you are prompted to install Pandas data frame into this Python enviornment when using the Data Frame viewer 
    To test this, create a few variables, at least one with a list e.g. `a = [1,2,3]` and use the variable viewer to open the variable `a`
* [ ] New Conda environments are detected and displayed in the Kernle picker
    Note: You need to have already executed a cell in some notebook
    Then create a conda environment within VS Code
    I.e. the goal is to test detection of new virtual envs after the extension has been used for a while
    * [ ] Verify you are prompted to install IPyKernel into this Python enviornment when running a Notebook cell against this kernel
    * [ ] Verify you are prompted to install IPyKernel into this Python enviornment when running an Interactive Window cell such a new Python Environment (either re-create a new env or uninstall IPyKernel)
    * [ ] Verify you are prompted to install Pandas data frame into this Python enviornment when using the Data Frame viewer 
    To test this, create a few variables, at least one with a list e.g. `a = [1,2,3]` and use the variable viewer to open the variable `a`
* [ ] Re-load VS Code and verify you can pick a Kernel Spec before Python environments
    I'm hoping some machines are slow enough and we can see Kernel Specifications before Python environments in the kernel picker.
    In the past we regressed in this space and Jupyter extension waited for ALL python environnents to be loaded before displaying Kernel Specs on disc.
    We're verifyhing the fact that some kernels will appear before others
* [ ] Verify local kernel specs appera before Remote Kernel specs
    Connect to a local Jupyter server after having started a jupyter server using `jupyter notebook --no-browser --NotebookApp.allow_origin=*`
    In the past we regressed in this space and Jupyter extension waited for ALL python environnents to be loaded before displaying Kernel Specs on disc.
    We're verifyhing the fact that some kernels will appear before others
* [ ] Verify debugging works and uses the right Python environment

* [ ] Test other parts of the extension that you believe could be impacted by adopting the new Python Extension API

**Comment by IanMatthewHuff** [comment]
> How do I do this? I've only ever used the conda terminal to work directly with conda.
 
Python did add a new Python Create Environment Command, I'm testing both that and creating one manually.

**Comment by amunger** [comment]
Here is my kernel loading experience, just two show up before all the rest are loaded at once

![KernelLoading](https://user-images.githubusercontent.com/2019016/197851426-854021d1-8893-4b74-a6cd-9641f53f4fee.gif)

**Comment by rebornix** [comment]
I couldn't get conda to work, similar to what @amunger was seeing. Other than this, it works great in overall, filed a couple of issues but they don't seem to be new.

**Comment by amunger** [comment]
> Verify local kernel specs appera before Remote Kernel specs

A few show up before the remotes are listed, but the remotes come in quite a bit before the bulk of the local ones show up.

**Comment by amunger** [comment]
also had the same feedback as @IanMatthewHuff mentioned at one point - the list is a lot bigger now, and it is difficult to find my typical kernel that I use since it's buried within all the kernels from other workspaces

**Comment by roblourens** [comment]
> Testing the jupyter web extension providing completions when typing in a notebook.

This isn't actually related right?

**Comment by DonJayamanne** [comment]
Oops, no, you're right

**Comment by roblourens** [comment]
I literally spent all afternoon and evening trying to get python installed in WSL. I finally have a working setup, was able to get started, will finish testing first thing tomorrow.

**Comment by roblourens** [comment]
Same question as Aaron about 
>  Re-load VS Code and verify you can pick a Kernel Spec before Python environments

https://github.com/microsoft/vscode-jupyter/issues/11755#issuecomment-1290868617

Does this just mean I should see environments loaded gradually, rather than none until they are all available? Or is this specifically about the ordering of particular types of environments, like are you looking for kernel specs that I registered to show up before global Python environmens?

**Comment by DonJayamanne** [comment]
> Does this just mean I should see environments loaded gradually, rather than none until they are all available? 

If you are lucky to have a slow machine, then yo'll see environments load gradually.
Its unlikely you'll have none, as the Python Extension API returns the active interpreter pretty quickly, hence you'll most likely see at least one python env in the list.

> Re-load VS Code and verify you can pick a Kernel Spec before Python environments

Sorry, I should have been more specific. I shoudl have stated that you can pick kernel specs before ALL python envrionmetns are loaded. I.e. over time you should see more & more python envs getting added to the list.
However kernel specs should be loaded very quickly in comparison.
