### ISSUE TITLE
Test: Kernel Picker "Kernel Source" experiment

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#11765]
Refs: https://github.com/microsoft/vscode-jupyter/issues/11576

- [x] anyOS @roblourens
- [x] anyOS @amunger

Authors: @IanMatthewHuff

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2311765%0A%0A&assignees=IanMatthewHuff)

---

@roblourens and @amunger. Felt like Don, Peng and I had seen this the most already so assigned the two of you to get new eyes on this.

To get the settings for this get the following in your settings:
`"jupyter.showOnlyOneTypeOfKernel": false,
    "jupyter.experimental.kernelPickerType": "Insiders",`

Note, this is all behind an experiment for now. Testing can be pretty broad here, but I've tried to list out some basic steps and a few known issues. Comments on the basic flow are better than testing every nook and cranny at this point.

Steps:

1. Start without any Jupyter servers attached.
2. Open up a notebook document
3. You should have a Select Kernel Source command (also if you had a previously selected kernel it should be available) in the kernel picker
4. 
<img width="780" alt="image" src="https://user-images.githubusercontent.com/812783/197646514-2534bbe8-0c84-4200-b75e-e6d004a16b99.png">

5. Picking that should list Local Kernels
6. After selecting "Local Kernels" you should see the normal kernel selection choices
7. Pick the Jupyter Server: Local item and add a remote server
8. 
<img width="231" alt="image" src="https://user-images.githubusercontent.com/812783/197646698-68319734-8ca4-4583-b657-3d72a97ca1fe.png">
9. When a server is added you should also get the option to name it, try giving a custom name
10. After server(s) are added, they should show up as options in the "Select Kernel Source" command
12. 
<img width="640" alt="image" src="https://user-images.githubusercontent.com/812783/197646808-86e46796-19b9-4e49-9b9b-13df2c610fe8.png">
13. When picking a remote kernel source you should only see kernels from that source as options
14. 
<img width="760" alt="image" src="https://user-images.githubusercontent.com/812783/197646871-537f52c6-b231-4e9d-a536-1d536a83fc48.png">
15. Open a second notebook file.
16. Connect it to a different kernel source
17. You should be able to select different sources for different open documents, and picking a different source in on should not kill other documents with other kernels sources (like the previous experiment used to do)
18. 
<img width="1832" alt="image" src="https://user-images.githubusercontent.com/812783/197647100-bbbdfe64-9a48-4c1c-8178-631e458f4ea1.png">
19. In above example one document is connected to Server B kernel source and the other is connected to Local kernel sources

**Comment by IanMatthewHuff** [comment]
Still an early experiment so there are some big known issues already:
[Kernel Picker Experiment: Consider integration of suggestions](https://github.com/microsoft/vscode-jupyter/issues/11666#top)
[Kernel Picker Experiment: Persist selection on document open](https://github.com/microsoft/vscode-jupyter/issues/11665#top)
[Kernel Picker Experiment: "Jupyter Server: Local / Remote" doesn't have meaning anymore](https://github.com/microsoft/vscode-jupyter/issues/11766#top)

**Comment by roblourens** [comment]
> Pick the Jupyter Server: Local item and add a remote server

Why is there no option to add a remote server behind the "Select Kernel Source" option?

**Comment by amunger** [comment]
There is still a big disconnect between conntecting to a jupyter server and then selecting the kernel. I would really expect those two steps to be tied together instead of having to then find the same server in the kernel picker.

**Comment by amunger** [comment]
There was some flakiness around re-selecting the same kernel when re-opening notebooks after having multiple open with different sources, but I'm struggling to get a consistent repro. I'm also confused about what is supposed to show up in the initial list along with 'select kernel source', most of the time it was _only_ the currently selected kernel, which seemed kind of strange.
