### ISSUE TITLE
Test: Restarting jupyter cell debug sessions

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#11769]
Refs: #7670

- [x] macOS @rebornix 
- [x] linux @karthiknadig
- [x] windows @brettcannon (Optional)
- [x] windows @karrtikr

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2311769%0A%0A&assignees=roblourens)

---

- Set `"jupyter.debugJustMyCode": false`
- Open a Jupyter notebook
- Add a breakpoint to a cell, and debug with the "Debug Cell" command
<img width="223" alt="image" src="https://user-images.githubusercontent.com/323878/197655029-aaaf3f96-f8d2-4804-93f6-170a910e3db6.png">
- Click the "restart" button in the debug toolbar- the debug session should restart and debug the same cell
- Try the same scenario in the interactive window- you should see a message that says "Restart is not supported in the interactive window"

**Comment by isidorn** [comment]
Blocked on https://github.com/microsoft/vscode-jupyter/issues/11776
Also how do I debug the interactive window?

**Comment by roblourens** [comment]
Have a .py file with the special comment like

```py
# %%
print(1)
print(2)
print(3)
print(4)
```

and click the "Debug Cell" codelens

<img width="199" alt="image" src="https://user-images.githubusercontent.com/323878/197837137-60437bd2-f226-4aa5-a5b4-e461eb3c5b79.png">

**Comment by brettcannon** [comment]
Everything but the notification about the interactive window not being supported worked.

https://github.com/microsoft/vscode-jupyter/issues/11798
