### ISSUE TITLE
Fix justMyCode=false for Interactive Window debugging with ipykernel debugging

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#11777]
https://github.com/microsoft/vscode-jupyter/issues/8146#issuecomment-1290324384

Need to avoid using `breakpoint()`. Use a DAP breakpoint or the suggested `stop_on_entry`

**Comment by vickkot** [comment]
Hi @roblourens,
 
Could you please tell if the issue with non-working breakpoint in the third-party libraries while debugging from jupyter notebook cell is going to be fixed after this issue is closed and merged?
Sorry for my poor english.
Thank you so much for all your work btw.

**Comment by roblourens** [comment]
That should work with the pre-release version of the extension when justMyCode is disabled

**Comment by vickkot** [comment]
> That should work with the pre-release version of the extension when justMyCode is disabled
It works! This is awesome, thank you

**Comment by dennischenfeng** [comment]
Using the pre-release version of the Jupyter extension also works for me too. Thanks!

**Comment by DonJayamanne** [comment]
We use `breakpoint` only when dealing with the old debugger, probably needs some cleaning up, closing for now.
