### ISSUE TITLE
Consider not showing venvs from other directories

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#11779]
Testing #11755

I think this work would actually fall on me on the Controller level (so I don't expect you to have to do this), but putting this item here for consideration since the new Python API did expose this. One thing that I always liked about using venvs is that they were restricted to just the folder path that I had open. Now I'm getting way too many non-relevant venvs from all over my system. 

<img width="633" alt="image" src="https://user-images.githubusercontent.com/812783/197839329-8d2f01e3-f742-45df-8ba5-99404f929e04.png">

I'm no python expert so I'm totally fine if folks disagree and we don't do this. It's just a downgrade for how I use Python + VS Code notebooks.

**Comment by DonJayamanne** [comment]
i like this feature

**Comment by DonJayamanne** [comment]
Looks like a bug in the Python Extension API

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode-python/issues/20068

**Comment by DonJayamanne** [comment]
Found that this is a change in the Python exension api and we need to filter the environments ourselves.

**Comment by roblourens** [comment]
> Found that this is a change in the Python exension api and we need to filter the environments ourselves.

Seems surprising that we would have to do it this way- isn't it expensive to collect venvs from all over the disk, just for us to ignore them?

**Comment by DonJayamanne** [comment]
> collect venvs from all over the disk, just for us to ignore them?

i think they're caching them, agreed, could probably be expensive (more disc IO , process validations etc..),, but that's what ive been asked to do , that's to filter them)l

@karrtikr @karthiknadig /cc

**Comment by karrtikr** [comment]
Yep they're cached from previous session, so it's not expensive. Although as I suggested [here ](https://github.com/microsoft/vscode-python/issues/20068#issuecomment-1291215166 ) what we can probably do is only return environments in the current VSCode context (only for the currently opened workspaces).

Feel free to reopen https://github.com/microsoft/vscode-python/issues/20068 in that case.

**Comment by DonJayamanne** [comment]
> current VSCode context (only for the currently opened workspaces).
> Feel free to reopen microsoft/vscode-python#20068 in that case.

@karrtikr . if you think this is what other users of the api need then fine. note this is definitely not something we do not need. please feel free to ignore or change the api accordingly. 
im assuming you've made this changes because you've felt other would need it, hence i can't tell you not to do this
