### ISSUE TITLE
Are there two setting buckets/categories for Jupyter?

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-jupyter#11773]
Testing #11768

* have jupyter installed
* open settings editor
* there is a nice "Jupyter" category and a wonky ".ipynb support" category. I believe they should be merged or the latter should have a proper label

<img width="552" alt="Screenshot 2022-10-25 at 15 11 18" src="https://user-images.githubusercontent.com/1794099/197782564-cf3cee15-3cec-4264-a151-a83c361d70ce.png">

**Comment by roblourens** [comment]
These are two separate extensions, .ipynb support is built-in

**Comment by jrieken** [comment]
> or the latter should have a proper label

**Comment by roblourens** [comment]
What is "proper"? It's the name of the extension

**Comment by roblourens** [comment]
Maybe you expect something with "Jupyter" in the name, but I think that will lead to confusion if people think "vscode has Jupyter support built-in" when it's just for the basics of reading notebook files. I think avoiding the word "Jupyter" was intentional

**Comment by jrieken** [comment]
How about proper capitalisation, like ".ipynb Support" or ".ipynb Viewer" or "Jupyter Viewer". 

I don't really share the concern about wrongly advertising "built-in Jupyter support" - the viewer is built-in and it is highly likely that folks will get in contact with it by clicking on a filename, not by browsing the settings UI. So, the "viewer" should make clear what it is (and I think it does a good job) but all related settings should be grouped together.

**Comment by roblourens** [comment]
Ah, capitalisation definitely.

The settings editor doesn't give us the ability to group settings from two different extensions:

<img width="626" alt="image" src="https://user-images.githubusercontent.com/323878/198334602-03e0e96e-db86-455b-a8ff-401ac78e15a9.png">

and I don't think we should make it work just for this, I can see why it would be useful but it's an unusual edge case. It does bug me that I can't find that setting by searching "Jupyter" but we could also patch that up with our natural language search service.

It's a little bit like Python's minor extensions which all have their own settings categories 
<img width="64" alt="image" src="https://user-images.githubusercontent.com/323878/198335782-ce6f9e6e-fbd6-451e-999f-e73d6f4b8679.png">

**Comment by rzhao271** [comment]
I'd also prefer that extensions don't hijack settings from one another
