### ISSUE TITLE
Revisit `jupyter.debugJustMyCode` settings name

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-jupyter#11772]
Testing #11768

The "debugJustMyCode" doesn't read nice. Looks like others use `debug.<main>.<topic>` like `debug.javascript.breakOnConditionalError` So maybe something like `debug.jupyter.XYZ`. Unsure about the XYZ, "just my code" reads to conversational. Maybe "skipImports" or "onlyCells" or something related to smart step?

<img width="561" alt="Screenshot 2022-10-25 at 15 06 18" src="https://user-images.githubusercontent.com/1794099/197781077-215b0474-168d-4317-aece-2f2374900309.png">

**Comment by roblourens** [comment]
"Just My Code" is a feature name that goes back to VS years ago. It's used in python but we tried to be more specific in js-debug. I don't want to reinvent the name of the feature but the description could use some work. And I'm actually not sure about the `debug.javascript` pattern, I think I like it better the other way around like these

<img width="208" alt="image" src="https://user-images.githubusercontent.com/323878/197832904-50787a11-fea8-4718-ac58-8bed026e6ea8.png">
