### ISSUE TITLE
Stepping into N times on the same statement

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-jupyter#11774]
Testing #11768

*  "jupyter.debugJustMyCode": true,
* use the snippet below
* press step into on line 5
* :bug: you need to press step into a couple of times before it resumes on the next line

```py
import ipywidgets as widgets

print(12)

a = widgets.IntSlider(description='a')
a

```

**Comment by roblourens** [comment]
Filed upstream https://github.com/microsoft/debugpy/issues/1104, not sure whether debugpy can do better or not

**Comment by roblourens** [comment]
Reopening since I'll do a workaround on our end.

**Comment by roblourens** [comment]
Real fix from debugpy is en route. Added a workaround on our end.
