### ISSUE TITLE
Selected and executed kernel is not suggested after window reload

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11788]
Testing #11755

* Create new venv
* Run cells against the new venv
* Install ipykernel as requested
* After the cell executes successfully, reload the window
* 🐛 the kernel is not suggested

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/876920/197847487-11e1df02-4ef1-4e87-8e0c-561006909130.png">

**Comment by DonJayamanne** [comment]
kernel suggestion is owned by @IanMatthewHuff

**Comment by DonJayamanne** [comment]
should be fixed with the new kernel picker ui.
@rebornix can you confirm this has been fixed
