### ISSUE TITLE
Should IPython and ipykernel code be skipped when justmycode is set to false?

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-jupyter#11785]
Testing #11768

This thought occurred to me when I was comparing the behaviour of justmycode == false for debugging notebooks vs debugging Python files. You can see that when debugging Python files with a function definition, stepping into the first breakpoint will act like a step over, and while in notebooks, it will take to IPython code:
![debugjustpycodenotebooks](https://user-images.githubusercontent.com/45497113/197846353-d0d00ca1-f581-422d-9391-905370f6f8ba.gif)

Maybe we should even consider changing the behaviour for how justMyCode works for Python files, or maybe this is all fine as is. Just figured it was worth bringing this up.

**Comment by roblourens** [comment]
It shouldn't step into ipykernel code- can you try upgrading debugpy and ipython to the latest? That should fix it

**Comment by luabud** [comment]
Yep, installing the latest ipython fixed it! Thanks 😊
