### ISSUE TITLE
Change kernel doesn't open kernel picker

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11786]
Testing #11755

When running against a kernel without ipykernel installed, an error prompt showed up and I picked "Change Kernel", the kernel picker didn't show up though, and only got an error message in the cell.

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/876920/197846717-acbcf1dc-62c6-485a-b378-df959dfb2f07.png">

**Comment by DonJayamanne** [comment]
@rebornix not sure why that didn't work for you, please could you test this once again,.
If this still fails, please could you provide the verbose logs.
