### ISSUE TITLE
Consider some UI notification when controllers are added / changed?

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#11784]
Testing #11755

Note: This might also be moved to my plate if we want to do something here.

Right now the kernels come in in chunks. But there is no indication of when more are added aside from popping the kernel picker. I notice it more in testing, but also in usage. Basically some time X after loading I'll have my selections available, but I never know the exact time, and have to pop open the kernel picker several times to see when they are loaded. Applies to both the type of kernels being loaded or detecting a new one.

**Comment by DonJayamanne** [comment]
@IanMatthewHuff since the ui aspect of kernels is you're area, im reassigning this to you

**Comment by DonJayamanne** [comment]
Reported internall
```
and I still see some odd behavior with kernel picking. Specifically, after a window reload the extension seems to pick an arbitrary kernel and no conda-based kernels are displayed. Then after 5-10 seconds it discovers the conda environments and then selects the kernel correctly. 
```

**Comment by DonJayamanne** [comment]
this is fixed with the new kernel picker
