### ISSUE TITLE
No prompt to install ipython/ipykernel and automatic installation fails

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11792]
Testing #11755

Tested on Codespace

* create a new conda env on codespace
* the new conda env is detected
* switch to the conda env from the kernel picker
* run a cell

There is no prompt to install ipykernel, however there is a notification for "installing ipykernel", at the end installation doesn't seem to happen I got an error in the cell

<img width="694" alt="image" src="https://user-images.githubusercontent.com/876920/197852333-d3f5c5c5-c264-4bb4-a80d-3c4c6c48c3b7.png">

**Comment by DonJayamanne** [comment]
Duplicate of #12279
