### ISSUE TITLE
VSCode Crashes when assigning list[many tuples] as a default function parameter (only when checking variables tab)

### ISSUE THREAD

**Issue by TheWCKD** [microsoft/vscode-jupyter#11799]
## Environment data

-   VS Code version: Version: 1.72.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.10.1103001107
-   Python Extension version (available under the Extensions sidebar): v2022.17.12981046
-   OS: Linux Mint 21 x64 5.15.0-52-generic (also happening on Windows)
-   Python and/or Anaconda version: Python 3.10.6
-   Type of virtual environment used: venv (also happening with miniconda)
-   Jupyter server running: Local

## Steps to reproduce:
```python
# run this block first
list_of_tuples = [("1","2","3", "4", "5") for i in range(350)]

# then this random function 
def test(argument = list_of_tuples):
    return 0
```
Open variables menu, vscode freezes, vscode cpu process stays at 12% constantly, nothing can be executed anymore. I think this is a major bug.

## Logs

<details>

<p>

```
info 22:10:56.524: Loading webview. View is notset
info 22:10:56.525: Loading web view...
info 22:10:56.526: Webview panel created.
info 22:10:56.761: Web view react rendered
```

</p>
</details>

**Comment by TheWCKD** [comment]
Also, after enabling verbose jupyter logs, and rerunning the steps to reproduce, this is the output (and then it freezes again):

```
debug 10:30:22.042: Cell 7 executed with state Success
debug 10:30:22.042: VSCodeNotebookController::handleExecution, Class name = x, completed in 35ms, has a falsy return value
debug 10:30:39.637: Executing silently Code (idle) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info
debug 10:30:39.668: Executing silently Code (completed) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info with 1 output(s)
```

**Comment by IanMatthewHuff** [comment]
I did a quick investigation here, no fix yet, but I do see the root cause.

Dropping a quick note here for investigation on our side:
https://github.com/microsoft/vscode-jupyter/blob/9307d256480265ad313cd8d7781a963cf627bfa5/src/kernels/variables/kernelVariables.ts#L345
We query the kernel using the inspect request to get the value for the variables that we list. When it tries to get the value for the test function it seems to return an unpacking of the entire tuple list. Then when we try to process that with the regexs it can't handle it.

<img width="3336" alt="image" src="https://user-images.githubusercontent.com/812783/198158638-df9b550a-b36b-4323-a902-590ce40cb636.png">

It's a bit of an upstream issue (at least I'd argue this isn't the best thing to return from inspect from the kernel) but we should be able to handle this better on our side.

**Comment by TheWCKD** [comment]
I understand, one thing I can add more is that the standalone Jupyter notebook web interface doesn't produce this bug, nor the Jupyter plug-in of PyCharm. 

Anyways, there should be a way of bypassing this, I don't need to see the function header into the variables, so I see no use in parsing it from the kernel in the first place. Thanks for investigating!

**Comment by IanMatthewHuff** [comment]
@TheWCKD At a minimum I see an easy bug here on our side in that by default we don't show the values for functions in our variables view (as you mentioned it's not super useful). But we start by calculating the values for everything defined before we hide some of them, such as functions. We can swap the order here pretty easily, this issue would still exist, but would be much less likely to show up as you would have to change our variable filters to hit it.

**Comment by DonJayamanne** [comment]
> It's a bit of an upstream issue (at least I'd argue this isn't the best thing to return from inspect from the kernel) but we should be able to handle this better on our side.

By upstream do you mean ipykernel? or Python extensoin code?

I would have thought its doing the right thing and not an upstream issue here. As we're asking for the kernel to inspect something and we are successfully getting the value back. However things hang when we attempt to run a regex on that large string.

**Comment by IanMatthewHuff** [comment]
@DonJayamanne Our extension should be able to handle this regardless. But I would say that inspect is supposed to return a reasonable inspection string for the user to look at. For list_of_tuples it returns a reasonable user viewable string, it knows not to unpack the entire list. However when list_of_tuples is a function default parameter it expands the entire thing out. Our responsibility to handle that, but it's a poor inspect string to return from ipykernel.

**Comment by roblourens** [comment]
Steps: edit `jupyter.variableExplorerExclude` to remove "function", then run this code

```py
list_of_tuples = [("1","2","3", "4", "5") for i in range(350)]
def test(argument = list_of_tuples):
    """ hello """
    return 0

test()
```

You should see `test` in the variables explorer with a value of `hello`
