### ISSUE TITLE
bad intellisense for conda kernels when using Interactive window 

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#11795]
Type: <b>Bug</b>

This has only repro'd for me with conda kernels

1. create a new file
2. run a simple cell in the IW

```
# %%
print(1)
```

4. edit the cell code to something else that should compile

:bug: error shown for code that isn't there

Extension version: 2022.10.1103001107
VS Code version: Code - Insiders 1.73.0-insider (bece5db81842e38bf85e8a08fb1f12b7f78d4384, 2022-10-24T05:31:12.081Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (14.35GB free)|
|Process Argv|--crash-reporter-id 1202dc88-403d-4ebc-8393-af3551a8bd5b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pylantcb52:30590116
pyind367:30587847
vsccc:30564266
pyindex848:30577858
nodejswelcome1:30587009
34cci188:30595212

```

</details>

**Comment by amunger** [comment]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/2019016/197859689-e97504a9-30d5-4212-990a-3968d9758a3e.png">

**Comment by DonJayamanne** [comment]
@amunger i think this shoudl be fixed with the latest bits of pylance, pytohn and juyter extensions.
Please could you verify this issue.
