### ISSUE TITLE
No prompt about debugging restart not working for the interactive window

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-jupyter#11798]
Testing #11769

This is what it looks like after I click the restart button in the debug toolbar:

![image](https://user-images.githubusercontent.com/54418/197862214-e925c4b9-510d-4495-aae6-5903330fc738.png)

**Comment by roblourens** [comment]
It looks like you have notifications disabled. This makes me realize that the error should maybe be a modal dialog instead.
