### ISSUE TITLE
Create data frame view editor only after packages are installed

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11790]
Testing #11755

When pandas is missing we will prompt to ask users to install missing packages. At the same time we opened the editor already, if users choose cancel we will then close the editor. Maybe we can open the editor only after users choose "Install"

<img width="1689" alt="image" src="https://user-images.githubusercontent.com/876920/197848081-dd76b611-7fad-4d2b-b0c7-9fe55c3fab1b.png">

**Comment by DonJayamanne** [comment]
data frame browser is managed by @IanMatthewHuff 
this is an existing behaviour

**Comment by DonJayamanne** [comment]
Closing this issue for now as this hasn't been reported by anyone.
I would consider this debt (polish), and I believe this will get fixed once we re-factor/chagne the df viewer.
