### ISSUE TITLE
Flow from adding a remote jupyter server to selecting a kernel in that server is not smooth

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#11797]
Testing #11765

Not sure whether this was a focus of this item, it's just something I noticed while working through it. To add a remote jupyter server, I have to 
- Click the status bar item, when I might expect to do it through the kernel picker
- Add my server
- Then go back to the status bar item to select a kernel from the server

I think I'd want to do all of this through the kernel picker.

**Comment by DonJayamanne** [comment]
Fixed with the new kernel picker
