### ISSUE TITLE
Odd step into/ step out of behavior using just my code

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#11791]
Testing #11768

1. With `"jupyter.debugJustMyCode": false`
2. With a python cell:

```py
def func():
    pass

func()
print("done")
```

2. Create a breakpoint on `func()`
3. Debug cell
4. Step into `func`
5. step out of it again
6. The debug cursor should be on `func()` again at this point
7. Now step into again

**Bug**
I end up in `interactiveshell.py` in the `run_code` method

I'd expect to continue to the next line instead

**Comment by mjbvz** [comment]
Repo is even easier actually:

1. With the cell:
```py
print('a')
print('b')
```
3. Break on the first print
4. Try stepping over

You end up in `interactiveshell.py`

**Comment by roblourens** [comment]
@mjbvz can you run this in the same environment? It's possible that I should have had people upgrade debugpy as part of the TPI: 

```py
import debugpy
print(debugpy.__version__)
```

**Comment by mjbvz** [comment]
@roblourens Sure, it's currently: `1.6.0`

**Comment by roblourens** [comment]
Should be fine with the latest
