### ISSUE TITLE
Debug cell: Saved notebook is marked as unsaved on clicking debug cell

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-jupyter#11803]
Testing #11769

![image](https://user-images.githubusercontent.com/3840081/197871353-7a2aba31-18e7-49b4-8337-334ec12c0636.png)

![image](https://user-images.githubusercontent.com/3840081/197869582-e2e8bdc6-8dff-42ff-b9c0-6031de61c344.png)

This might be expected, since output is changing and output is part of the document?

**Comment by roblourens** [comment]
> This might be expected, since output is changing and output is part of the document?

That's exactly right. Possibly other metadata too- selected kernel, or a timestamp.
