### ISSUE TITLE
Jupyter Notebook doesn't respect VS Code "editor.folding" setting

### ISSUE THREAD

**Issue by 2-5** [microsoft/vscode-jupyter#11802]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I have disabled code folding globally in VS Code with the `"editor.folding": false` setting in my `settings.json`.

But Jupyter Notebook doesn't respect this setting and shows the code folding arrows.

It seems a new `jupyter.pythonCellFolding` setting was added recently (https://github.com/microsoft/vscode-jupyter/pull/11737), but it doesn't seem to default to the `editor.folding` value. I think it should.

### VS Code Version

Version: 1.72.2 (user setup) Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075 Date: 2022-10-12T22:15:18.074Z Electron: 19.0.17 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10.0.19044 Sandboxed: No

### Jupyter Extension Version

v2022.9.1202862440

### Running Jupyter locally or remotely?

Local

**Comment by 2-5** [comment]
Tagging somewhat related https://github.com/microsoft/vscode-jupyter/issues/11703

**Comment by amunger** [comment]
> it doesn't seem to default to the editor.folding value. I think it should.

good call, thanks for pointing that out.

**Comment by amunger** [comment]
ah, I thought this was for .py files since you had tagged that other issue, but it's actually for folding regions in notebooks. 

note: The [notebook's folding controller](https://github.com/Microsoft/vscode/blob/main/src/vs/workbench/contrib/notebook/browser/controller/foldingController.ts#L26) is not using `editor.folding`

**Comment by 2-5** [comment]
Interesting line you linked to:

```typescript
export class FoldingController extends Disposable implements INotebookEditorContribution {
  static id: string = 'workbench.notebook.findController';
```

Is `workbench.notebook.findController` a typo? It says `findController` but it seems to me that `id` should be `workbench.notebook.foldController` to match the `FoldingController` class name.

**Comment by youurayy** [comment]
Folding in Jupyter notebooks in 1.72.2 seems to be pretty much broken.

**Comment by amunger** [comment]
@youurayy - can you create a new issue and explain what you're seeing? I'm not seeing any issues besides the one mentioned here.

**Comment by rebornix** [comment]
`workbench.notebook.findController` is an oversight but it should affect the functionalities. Also note that this folder controller is for folding markdown cells instead of folding inside cell editor. I'm sure what went wrong except the `jupyter.pythonCellFolding` related one.
