### ISSUE TITLE
Python extension fails to get actiavted conda envionment variables

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#11804]
Upstream issue https://github.com/microsoft/vscode-python/issues/20071

**Comment by rebornix** [comment]
Tried to verify this issue but there is a regression in Python environments detection

*v2022.17.13020517*

<img width="631" alt="image" src="https://user-images.githubusercontent.com/876920/198918655-d5f01817-7243-4ac5-9ebf-351ee62227f4.png">

*v2022.17.13011006*
<img width="605" alt="image" src="https://user-images.githubusercontent.com/876920/198918776-63bce5b0-708d-448d-91d2-25424049147c.png">

**Comment by karrtikr** [comment]
Being caused due to Jupyter: https://github.com/microsoft/vscode-jupyter/blob/d52654ed850fba4ff241b4aa2e9f62cb082b3f71/src/platform/api/pythonApi.ts#L85

`!` is being used where it shouldn't be. Should handle the `uri` is `undefined` case.

**Comment by DonJayamanne** [comment]
Fixed

**Comment by rzhao271** [comment]
In an Anaconda prompt, I wrote `conda env config vars set my_var=value2`
I then created another cell in a notebook in Insiders with `%conda env config vars list`, ran the notebook, and confirmed that the line `my_var = value2` was printed.
