### ISSUE TITLE
Widgets on remote server stop working after restart/kernel switch

### ISSUE THREAD

**Issue by zpincus** [microsoft/vscode-jupyter#11806]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

If you restart a remote jupyter kernel _after_ using the kernel picker, widgets no longer display.

Repro:
1. Create a simple test environment and run a jupyter server in it
```
conda create -n test python=3.10.6 ipywidgets=7.7.2 -c conda-forge
conda activate test
jupyter notebook
```
2. Create a new vscode window, and within that create a new jupyter notebook. Connect to the jupyter session you started in the terminal as a remote jupyter server.
3. In the first cell, paste:
```python
import ipywidgets
ipywidgets.IntSlider()
```
4. Run the cell and observe the slider appear. You can even restart the kernel and re-run and observe the slider work again.
5. Click the kernel picker widget in the upper right, and select the current kernel session (it should say "remote jupyter session" and specify "1 connection", i.e. like the lower entry in the picker here: <img width="616" alt="image" src="https://user-images.githubusercontent.com/174217/197899630-cd655956-6724-435f-8a74-5f02757fa56e.png">
6. Re-run the cell and observe that the slider still works. Then restart the kernel, re-run the cell (if everything worked the cell number should be `[1]` again), and observe that the slider does not appear.

This also happens when connecting to a new or different existing kernel as well, but the above has fewer repro steps.

I also observe similar, but harder-to-consistently-reproduce issues where in more complex notebooks (or something?) `IntSlider()` will continue to work, but matplotlib plots (and tqdm progress bars) no longer appear after some combination of restarts, kernel reconnections, and/or vscode reloads. In the above repro case, there is an output section where the slider should be, but it doesn't appear; i.e.: <img width="781" alt="image" src="https://user-images.githubusercontent.com/174217/197900082-ca32b697-a08a-46d8-98cd-375fbdf90b6f.png">
However, when matplotlib outputs stop working, there's not even an empty output section. I don't know if these are the same or related problems, but any suggestions as to how I might help isolate / reproduce this latter issue would be welcome -- it is frustrating to run some lengthy analysis only to discover that it's not possible to view the results of it in that session anymore. I was hoping to produce a repro of the above behavior here, but all I could get consistent was the above simple case.

### VS Code Version

Version: 1.72.2 (Universal) Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075 Date: 2022-10-12T22:16:30.254Z (1 wk ago) Electron: 19.0.17 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Darwin x64 20.6.0 Sandboxed: No

### Jupyter Extension Version

v2022.9.1202862440

### Jupyter logs

```shell
Visual Studio Code (1.72.2, undefined, desktop)
Jupyter Extension Version: 2022.9.1202862440.
Python Extension Version: 2022.16.1.
No workspace folder opened.
info 17:28:23.230: ZMQ install verified.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 17:28:23.479: LSP Notebooks experiment is enabled
info 17:28:23.791: Preferred Remote kernel for Untitled-1.ipynb is 4ee6eace-c462-43a1-8f91-17b49ad62581
info 17:28:23.791: Find preferred kernel for Untitled-1.ipynb with metadata {"orig_nbformat":4} & preferred interpreter 
info 17:28:23.818: Preferred Remote kernel for Untitled-1.ipynb is 4ee6eace-c462-43a1-8f91-17b49ad62581
info 17:28:23.818: Preferred kernel 4ee6eace-c462-43a1-8f91-17b49ad62581 is exact match or top match for non python kernels, (false, undefined, true, undefined)
info 17:28:23.819: PreferredConnection: 4ee6eace-c462-43a1-8f91-17b49ad62581 found for NotebookDocument: Untitled-1.ipynb
info 17:28:23.847: Preferred Remote kernel for Untitled-1.ipynb is 4ee6eace-c462-43a1-8f91-17b49ad62581
info 17:28:23.847: Switching remote kernel to 4ee6eace-c462-43a1-8f91-17b49ad62581 for untitled:Untitled-1.ipynb?jupyter-notebook
info 17:28:23.847: Using notebook.selectKernel to force remote kernel for untitled:Untitled-1.ipynb?jupyter-notebook to 4ee6eace-c462-43a1-8f91-17b49ad62581
info 17:28:24.054: Results of switching remote kernel: true
info 17:28:25.191: Got env vars ourselves faster /Users/zpincus/miniconda/envs/hxenv/bin/python with env var count 46 in 1341ms
info 17:28:25.196: Process Execution: > ~/miniconda/envs/hxenv/bin/python -m pip list
> ~/miniconda/envs/hxenv/bin/python -m pip list
info 17:28:26.710: Got env vars with python /Users/zpincus/miniconda/envs/hxenv/bin/python, with env var count 47 and custom env var count 0 in 2860ms
info 17:28:30.046: Creating server with url : http://localhost:8888/
info 17:28:30.074: Creating server with url : http://localhost:8888/
info 17:28:30.137: Checking for server existence.
info 17:28:30.137: Checking for server usability.
info 17:28:30.137: Starting notebook server.
info 17:28:30.138: Connecting to server
info 17:28:30.138: Connecting to process server
info 17:28:30.138: Connecting server kernel http://localhost:8888/
Connecting to Jupyter server at http://localhost:8888/
info 17:28:30.138: Creating server with url : http://localhost:8888/
info 17:28:30.140: Connection complete server
info 17:28:30.140: Server started.
info 17:28:30.140: Creating server with url : http://localhost:8888/
info 17:28:40.523: Dispose Kernel 'Untitled-1.ipynb' associated with 'Untitled-1.ipynb'
info 17:28:40.528: Starting Jupyter Session startUsingRemoteKernelSpec, d177cb038fded1cce5c655145a0089033fb2621f12aa5c1faff642247aa5e29c..python3./Users/zpincus/miniconda/envs/test/python./.-m#ipykernel_launcher (Python Path: /Users/zpincus/miniconda/envs/test, EnvType: Conda, EnvName: 'test', Version: 3.10.6) for 'Untitled-1.ipynb' (disableUI=false)
http://localhost:8888/: Kernel started: d2a5ff2d-6fbc-463f-bbad-79ff3f9119d5
error 17:28:41.002: Execing shell command, Class name = b, completed in 475ms, has a falsy return value, Arg 1: "~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/printEnvVariables.py", Arg 2: "" [Error: Command failed: conda activate test && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /Users/zpincus/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/printEnvVariables.py

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.



	at ChildProcess.exithandler (node:child_process:408:12)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)] {
  killed: false,
  code: 1,
  signal: null,
  cmd: "conda activate test && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /Users/zpincus/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/printEnvVariables.py"
}
info 17:28:41.767: Started session for kernel startUsingRemoteKernelSpec:d177cb038fded1cce5c655145a0089033fb2621f12aa5c1faff642247aa5e29c..python3./Users/zpincus/miniconda/envs/test/python./.-m#ipykernel_launcher
http://localhost:8888/: Creating new notebook 
info 17:28:42.257: Got env vars with python /Users/zpincus/miniconda/envs/test/bin/python, with env var count 45 and custom env var count 0 in 1737ms
info 17:28:42.261: Process Execution: > ~/miniconda/envs/test/bin/python -m pip list
> ~/miniconda/envs/test/bin/python -m pip list
info 17:28:42.537: Creating server with url : http://localhost:8888/
info 17:28:42.542: Updating preferred kernel for remote notebook d2a5ff2d-6fbc-463f-bbad-79ff3f9119d5
info 17:28:42.544: Creating server with url : http://localhost:8888/
info 17:28:46.390: Disposing kernel d177cb038fded1cce5c655145a0089033fb2621f12aa5c1faff642247aa5e29c..python3./Users/zpincus/miniconda/envs/test/python./.-m#ipykernel_launcher for notebook Untitled-1.ipynb due to selection of another kernel or closing of the notebook
info 17:28:46.390: Dispose Kernel 'Untitled-1.ipynb' associated with 'Untitled-1.ipynb'
info 17:28:48.397: Creating server with url : http://localhost:8888/
info 17:28:48.892: Starting Jupyter Session connectToLiveRemoteKernel, d2a5ff2d-6fbc-463f-bbad-79ff3f9119d5 for 'Untitled-1.ipynb' (disableUI=false)
info 17:28:49.005: Started session for kernel connectToLiveRemoteKernel:d2a5ff2d-6fbc-463f-bbad-79ff3f9119d5
http://localhost:8888/: Creating new notebook 
info 17:28:49.021: Creating server with url : http://localhost:8888/
info 17:28:50.737: Restart requested untitled:Untitled-1.ipynb?jupyter-notebook
info 17:28:50.737: Restart kernel execution
```

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
I'm sorry for not getting back, to you on this issue.
Please could try installing the latest pre-release version of the Jupyter extensioon and vscode insiders and let me know if this issue still persits. 
Optionally you can wait for the next stable release to test and confirm whether this stil eixsts.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Comment by zpincus** [comment]
Sorry, was waiting for the next stable release of everything to come out. The issue above is not fixed.

The repro is a bit more complex now as you have to explicitly choose "select another kernel..." from the kernel picker and navigate back to the remote jupyter server etc., instead of just re-selecting your current kernel. I guess that latter is correctly detected as a no-op. Alternately, selecting a different kernel and toggling back works fine.

I still don't have a better repro for the disappearance of e.g. tqdm widgets after some combination of window reloads and kernel reconnects (even without restarting the kernel), but the probability approaches 1 of widgets not working after once I've been connected to a kernel for a couple of days on a vscode-remote connection (which generally involves lots of window reloads on connection hiccups...) So any advice for providing you all with better debugging information about what's going on would be welcome.

**Comment by DonJayamanne** [comment]
@zpincus please install the latest pre-release version of Jupyter extension and let me know if you can replicate this.
* Please install latest VS Code Insiders
* Open the extensions page, search for Jupyter and click the button `Switch to Pre-Release Version`
* Similarly please install the latest `Pre-Release` version of the Python extension

<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">

**Comment by zpincus** [comment]
I can confirm that, using VS Code Insiders, with pre-release versions of Jupyter, Python, and Jupyer Notebook Renderers, I can still reproduce the above issue. Reconnecting to an existing remote kernel, and then restarting the kernel, causes widgets to no longer function.

**Comment by DonJayamanne** [comment]
Thanks, I can finally replicate this issue.

**Comment by DonJayamanne** [comment]
@zpincus I have managed to fix this, its been a long time for this issue to get resolved
The fix will in the next pre-release for VS Code insiders
(releaes will be in the next stable version, in around 4 weeks time)

**Comment by zpincus** [comment]
Thanks so much for your help and attention on this weirdo corner case! (and all the weirdo corner-cases I keep running across…)

**Comment by DonJayamanne** [comment]
> case! (and all the weirdo corner-cases I keep running across…)

they are all very useful and help improve  the overall product and use experience
