### ISSUE TITLE
Live Share stops after opening Python Interactive

### ISSUE THREAD

**Issue by eavanvalkenburg** [microsoft/vscode-jupyter#1180]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur
1. on machine 1 create live share with a Python script open
2. on machine 2 (@guendas)  accept live share and wait for join
3. on machine 1 click "run cell" to open Python Interactive and run code
4. machine 2 tries to do the same
5. on machine 1 the python extention says the other person in live share does not have the python extention installed and stops the live share.

## Actual behavior
Live share is stopped once the python interactive is opened

## Expected behavior
Live share works and allows both people to interact in the python interactive as well as python scripts

### Your Jupyter and/or Python environment
*Please provide as much info as you readily know*
- **Jupyter server running:**                       Local
- **Extension version:**                               2020.02.64397
- **VS Code version:**                                1.44.0-insider
- **Setting python.jediEnabled:**               false
- **Python and/or Anaconda version:**     3.7.6 (through Anaconda)
- **OS:**                                                     Windows 10
- **Virtual environment:**                          conda

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by IanMatthewHuff** [comment]
Closing as we don't own the liveshare scenarios anymore in the new notebook UI.
