### ISSUE TITLE
"Discovering Python Interpreters" is occasionally very slow after window reload. 

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#11800]
Testing #11755

I'm having a bit of trouble pinning down exactly when this happens, but I had assume that with caching this wouldn't be the case as much any more. Sometimes when I reload the window (no changes to python interpreters) the "Discovering Python Interpreters" step takes 30s or so. The whole wait time there I don't have access to any of the python controllers. 

Here is a semi-bad recording that I captured. Just a reload (nothing new added). 

https://user-images.githubusercontent.com/812783/197867350-4ef07bf0-642b-4147-bfce-8f3a55810da8.mov

**Comment by DonJayamanne** [comment]
@IanMatthewHuff please could you provide the debug logs

**Comment by IanMatthewHuff** [comment]
@DonJayamanne Looked to me like the time might be on the Python side, so I captured Jupyter and Python logs for one of these slow instances. 
[JupyterLog.txt](https://github.com/microsoft/vscode-jupyter/files/9864415/JupyterLog.txt)
[PythonLog.txt](https://github.com/microsoft/vscode-jupyter/files/9864416/PythonLog.txt)

**Comment by DonJayamanne** [comment]
@IanMatthewHuff you should see a progress indicator contributed by pytohn extension on the bottom left of the status bar (coudln't see it in the video).
Let me know if you see that is visible.

I'm adding some logging that would help us figure out where the delay is.
