### ISSUE TITLE
Can't change selected kernel in IW

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#11812]
Sometimes this works on the second try, but on the first it usually ignores my selection. I assume related to https://github.com/microsoft/vscode-jupyter/issues/11765

![Recording 2022-10-26 at 08 28 37](https://user-images.githubusercontent.com/323878/198069932-1f4f147e-af83-47ab-aa40-bd4481505f66.gif)

**Comment by DonJayamanne** [comment]
I think the selected kernel only lasts for the lifetime of the IW, when you close that, then we always use the active interpreter again for new executions.

**Comment by amunger** [comment]
experiment is no longer active, doesn't seem to repro in the new one
