### ISSUE TITLE
Jupyter Notebook: add access to cell metadata

### ISSUE THREAD

**Issue by chrisjsewell** [microsoft/vscode-jupyter#1182]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

As an extension to microsoft/vscode-jupyter#1121, to access the full notebook functionality, cell metadata should be accessible to view and modify in some manner.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by nathancarter** [comment]
Well...it *would* be epic...

**Comment by DonJayamanne** [comment]
In the mean time you can use the following extension https://marketplace.visualstudio.com/items?itemName=donjayamanne.jupyterpowertools
FYI - This only works in the VS Code insiders version (ability to edit tags, slider, ) 
Editint raw cells, metadtaa & notebook metadta is coming (in that extesnion)

**Comment by chrisjsewell** [comment]
Awesome thanks!

**Comment by psychemedia** [comment]
Cell tags (which are found in the distinguished `cell.metadata.tags` metadata element are also used to support rendering of notebooks via Jupyter Book eg to [hide particular content elements](https://jupyterbook.org/interactive/hiding.html#hide-cell-inputs).

How to add such tag metadata to notebooks is described [here](https://jupyterbook.org/content/metadata.html).

**Comment by tbenthompson** [comment]
Just a comment hoping that this gets prioritized at some point. At the moment, this blocks using VSCode for several common applications of notebooks (papermill, jupyter-book, and more). Thanks!

**Comment by jesusmariajurado** [comment]
+1
This would be very very usefull

**Comment by rafagsiqueira** [comment]
This might be obvious, but for those looking for a workaround on vscode: right click on the notebook -> Open With -> Built in text editor. Then edit the metadata tag directly in the Notebook JSON.

**Comment by amirbtb** [comment]
This could be useful to parameterize notebooks for [papermill](https://papermill.readthedocs.io/en/latest/) which is becoming a standard.

**Comment by luukalt** [comment]
+1
This would be very nice!

**Comment by cheginit** [comment]
Ability to add cell tags is necessary for `nbsphinx-gallery` that `sphinx` uses for generating documentation websites. Adding tags to notebooks by opening it as a json file can be difficult and at time not even possible since notebooks tend to be large files. So adding tags would be very helpful for this purpose.

**Comment by vitchyr** [comment]
+1 this would be great!

**Comment by mertgoksel** [comment]
This would help tremendously. +1

**Comment by rebornix** [comment]
Hi all, thank you for the feedbacks and your interest in cell tag and metadata editing support in VS Code. We have just published two extensions

* https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-cell-tags
* https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-slideshow

which will allow you to update cell tags and slide show inside the notebook editor

https://user-images.githubusercontent.com/876920/191586088-27fb3d9e-410b-4560-927d-5eeda4399e76.mov

Please give them a try and feedbacks welcome ;) 

If you are also interested in how it's implemented or you want to build an extension for a cell metadata that we don't support yet, you can find their source code in https://github.com/Microsoft/vscode-jupyter-slideshow and https://github.com/Microsoft/vscode-jupyter-cell-tags and tweak them to fit your need. We are interested in how you are using cell tags and metadata and figuring out how we can improve the experience to make you more productive. Thanks!

**Comment by psychemedia** [comment]
Re: possible applications of tags, I use them to provide custom styling for cells in JupyterLab etc.. https://github.com/innovationOUtside/jupyterlab_empinken_extension

Another use might be to customise cell rendering behaviour, a bit like IPython cell block magics. eg parse contents of a markdown cell tagged `mermaid-js` as:

````
```{mermaid}
ORIGINAL CELL CONTENT
```
````

**Comment by phense** [comment]
Well, it's not “perfect”, but the Cell Tag Extension does provide access to the Cell-Metadata from within VS Code.
Selecting “Edit Cell Tags (JSON)” opens the notebook in JSON format, and allows you to freely edit it (see '"metadata": {' ) on the right. 

![image](https://user-images.githubusercontent.com/1724296/222416577-3c980fb3-cdac-40fb-ba5d-029cb7694652.png)

Well, better than having to switch to jupyterlab just to edit some tags and cell metadata. 

Thanks, Microsoft!

Still, it would be nice to have a dedicated edit-window just for the notebook- and cell-metadata.
