### ISSUE TITLE
New Python virtual enviornments not listed in kernel picker

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#11822]
* Open a folder in vscode
* Create a new virtual environment outside vscode in a terminal in the same folder as above
* Verify the new env is displayed in the interpreter picker
* The new env will not appear in the kernel picker even after reloading VS Code

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode-python/issues/20104

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode-python/issues/20105

**Comment by rebornix** [comment]
Both are fixed now.
