### ISSUE TITLE
Do not reccommend the only controller as the preferred controller even if it doesn't match

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#11826]
Details described here https://github.com/microsoft/vscode/issues/164827

* Jupyter extension loads and detects kernel specs from disc and creates a controller for that (which happens to be typescript_
* Note: In the back ground Juyter extnesion is still busy finding other kernelspecs and Pytohn environments
* Jupyter extension has only one controller and sets that controller as the preferred controller.
* Jupyter then sees other controllers later, but doesn't find any matching controllers.

I think there are a few problems here:
* We should un-set the preffered controller once we get other controllers loaded

**Comment by rzhao271** [comment]
Hi Don, what are some verification steps for this issue?

**Comment by DonJayamanne** [comment]
Changed to debt, as this will go away with the new kernel picker.
this functionality has been removed
