### ISSUE TITLE
Python 2.7 has Python 3 display name in kernel picker

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#11830]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/30305945/198398250-a72f1024-fde5-45ec-a83d-55d9a36c738f.png">

**Comment by DonJayamanne** [comment]
@joyceerhl please could you enable verbose logging and upload the logs here.

**Comment by joyceerhl** [comment]
I shared the logs for this in Slack. Please let me know if you need anything else!

**Comment by DonJayamanne** [comment]
@joyceerhl Does this still repro with the latest pre-release bits of Jupyter extesnion.

**Comment by bhavyaus** [comment]
Was trying to verify this but Python27 does not even show up in the list for me:
<img width="670" alt="image" src="https://user-images.githubusercontent.com/25044782/214716155-1dc236d8-f23a-483b-963b-6cb703664368.png">

I have python27

**Comment by joyceerhl** [comment]
This has regressed: 
<img width="734" alt="image" src="https://user-images.githubusercontent.com/30305945/220980784-bbd95dee-003b-4170-9f85-fd7d7d556da1.png">

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/microsoft/vscode-jupyter/issues/12922
