### ISSUE TITLE
Some icons don't appear in the Insiders Notebook Editor until an untrusted notebook is trusted and then closed

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode-jupyter#1186]
OS: macOS Catalina 10.15.5
Version: 1.48.0-insider - commit: e7920dce7bfd0b707ebfc0a5379c6edd2233e475
Extension version: 2020.8.94012-dev

Steps to reproduce:
- Open an untrusted notebook, note that the only icons in the top-right corner are "Clear All Cells Outputs", "Split Editor Right" and ellipsis
- Mark the notebook as trusted, and then close it
- Reopen the notebook, observe that a few more icons appeared (export as, restart kernel and trust notebook)

![trust_icons](https://user-images.githubusercontent.com/51720070/87363860-ee8f0180-c526-11ea-9f8f-72b7fb6635a6.gif)

On a side note, I hovered over the icon because I was looking for "Trusted"/"Not trusted" wording and couldn't find it, but the icon's meaning was not immediately clear. The fact that it wasn't right next to the only other enabled notebook action (Clear All Cells Outputs) was also a bit confusing.

**Comment by DonJayamanne** [comment]
PM to determine the UX here.

**Comment by DonJayamanne** [comment]
@claudiaregio please could you advice the required UX?
Should we show the icons & disable them or just hide them (as done today)?

**Comment by DonJayamanne** [comment]
TODO:
* Ensure the icons are displayed when not trusted 
* & when they are trusted ensure they are enabled 
* One does not need to reload notebook to see some new icons (they should be displayed & enabled when trusting a nb)

**Comment by DonJayamanne** [comment]
Unable to replicate, moving to validate.

**Comment by joyceerhl** [comment]
Validated. After trusting:

![image](https://user-images.githubusercontent.com/30305945/105219051-da960f00-5b0a-11eb-95dd-ba13fc8927ef.png)

After reloading:

![image](https://user-images.githubusercontent.com/30305945/105219078-e08bf000-5b0a-11eb-9420-7a46a5669a6a.png)
