### ISSUE TITLE
Jupyter variables panel appears when using notebook without a Jupyter kernel attached

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#11870]
1. Open https://insiders.vscode.dev/github.com/bamurtaugh/python-tuples/blob/614d461702fe41eb06db69165df4774dea4e1b28/Tuples.ipynb
2. Select `Connect to a running Jupyter server` for kernel
3. :bug: in the output panel, Jupyter option appears, but there are no variables

IMO this panel should either be hidden if the notebook hasn't been executed yet, or should show a welcome action saying "the active notebook has not been executed, run a cell to see variables" with an action button to "run all"

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/30305945/199543205-92a6edd4-6586-4e66-a661-ad666d3e6cf7.png">

**Comment by amunger** [comment]
closing in favor of https://github.com/microsoft/vscode/issues/165445
