### ISSUE TITLE
jupyter notebook can not detect the default python version.

### ISSUE THREAD

**Issue by yanyu2015** [microsoft/vscode-jupyter#11891]
version:
![image](https://user-images.githubusercontent.com/11142054/199638706-6246b4a7-0893-493a-b0b3-1335bd3883cb.png)

After reinstal Anaconda, jupyter notebook can not detect the default python version.
I have configed as follows:
![image](https://user-images.githubusercontent.com/11142054/199638863-49c71a2f-acce-44ff-9c7f-cf0040e0b0f7.png)
![image](https://user-images.githubusercontent.com/11142054/199638896-6b0a3352-0e11-4913-a7a7-25c0bee388ca.png)
There is no the default python, why?

**Comment by DonJayamanne** [comment]
@yanyu2015 
I'm very sorry for missing this issue.
What do you mean by `default python`

**Comment by yanyu2015** [comment]
I mean that the python which is configured in the `Default Interpreter Path`

**Comment by DonJayamanne** [comment]
> python which is configured in the Default Interpreter Path

what version is that and whats the path to that deafult interpreter?
i.e. you can use `which python` in the terminal to find that and verify whether thats display int the list or not

**Comment by yanyu2015** [comment]
Please read the content I posted 29 days ago carefully, it may be helpful for you understand my problem. I have configured a python version in the 
`Default Interpreter Path`, but I cannot seleect it in a notebook.

**Comment by DonJayamanne** [comment]
oh sorry i missed that bit
please install the latest insider version of vscode and pre-release version of the jupyter extension and test that out. 
i believe this has been fixed in that version

please test that, as that's what will be released next week.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
