### ISSUE TITLE
Unclear kernel selection process in vscode.dev

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-jupyter#11896]
When I open a Jupyter notebook in vscode.dev (like https://vscode.dev/github/bamurtaugh/python-tuples) and run a cell, I'm prompted to select a kernel. When testing with users, it wasn't evident to them why they couldn't find or select a kernel - they expected it to work automatically or more closely to the desktop experience they're used to. Some more info (like link to docs, or special casing for web to provide different text) about kernel selection in web would be helpful.

Some users also either missed or ignored the prompt and continued clicking to run cells. It seems this quick pick should be more blocking, and potentially emit an error message if someone continues trying to run cells without a kernel.

cc @joyceerhl

**Comment by DonJayamanne** [comment]
@joyceerhl 
Do you think they clicked the kernel picker too quickly and the kernels weren't there.
Or did you/user see the kernels in the kernel picker after they clicked on the kernel picker once again

**Comment by bamurtaugh** [comment]
There weren't any kernels, since it was just a serverless vscode.dev instance:

![image](https://user-images.githubusercontent.com/25310137/199852492-851e45a5-fb27-43ff-bb48-e1f6d05b77b9.png)

They'd see the above, try to install Python and Jupyter extensions as recommended, and then become stumped when these extensions didn't give them a kernel / finish the setup process so that they could run cells.

**Comment by DonJayamanne** [comment]
Closing this as won't fix,
Its been a few years and no plans to iterate and change it at this stage
