### ISSUE TITLE
Can't copy cell output with preview notebook editor

### ISSUE THREAD

**Issue by MartinDix** [microsoft/vscode-jupyter#1190]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Open a python notebook with the preview notebook editor
2. Run a cell that creates output, e.g. print("abc")
3. Try to copy cell output with crtl+c

## Actual behavior
Get a message popup with
Cannot read property 'contains' of undefined

Using Copy from menu doesn't give an error but doesn't do anything.

## Expected behavior

Cell output is copied 

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.9.111407
-   **VS Code version:** 1.50.0-insider Commit: 73b33dcbc8204c23ae30b53ce129b32c6da98197
Date: 2020-09-24T09:42:09.149Z
-   **Setting python.jediEnabled:** true
-   **Setting python.languageServer:** Jedi
-   **Python and/or Anaconda version:** 3.8.5
-   **OS:** Windows
-   **Virtual environment:** conda

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by DonJayamanne** [comment]
Closing for now as upstream issues have been resolved. Please create a new issue if this issue persists.
