### ISSUE TITLE
VS Code - Empty Kernel Selection, 

### ISSUE THREAD

**Issue by tomanjepan** [microsoft/vscode-jupyter#11911]
## Environment data

-   VS Code version: 1.73.0 (user setup)
-   Jupyter Extension version: v2022.9.1202862440
-   Python Extension version: v2022.18.1
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Enterprise
-   Python version: 3.10.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | N/A : i honestly do not know

**## Expected behaviour**

After opening .ipynb file and running a code cell, I would expect to have list of Kernels to choose from.

**## Actual behaviour**

I have only option to install Python or Jupyter extension, which i tried to uninstall and install again, but nothing happened in this case.

![image](https://user-images.githubusercontent.com/41164803/200004455-9667c6dd-c88c-46ca-8324-fbc2be38cf18.png)

## Steps to reproduce:

I think the issue would be connected to virtual env which was deleted.
On this former virtualenv the Jupyter notebook worked as it should have.

After deleting the venv, the list of Kernels disappeared.

## Logs

Can be provided, I'm pretty new and dont know how any helpful logs can be generated.

<p>

**Comment by amunger** [comment]
It looks like the Jupyter extension either crashed or didn't finish activating. Does kernels eventually populate if you wait longer? Or was that screenshot taken after uninstalling the extension?

Can you run the command `Jupyter: Show Output` to see if there are any logs, and post them here if so?
If the extension crashed, there might be some logs in the developer tools that state why - `Developer: Toggle Developer Tools`

**Comment by amunger** [comment]
Do you see a Jupyter option in the dropdown for the output window? Those are the logs were after, but if the extension is crashing, they might not be there.
![image](https://user-images.githubusercontent.com/2019016/200022841-6e3f317c-ef7f-4b43-853f-22f08c55c4d2.png)

For the developer tools, the console tab has logs, but I'm not actually sure anything useful would be in there.

You could also try installing the pre-release version of the Jupyter extension, just find the "switch to pre-release" button on the extension page. There are quite a few changes in there around kernel discovery that aren't quite ready for stable, but they might work better for you anyway.

**Comment by tomanjepan** [comment]
You were right, the Jupyter option wasn't in the dropdown menu.

But it seems **your recommendation worked**. 
After switching to Pre-Release version, the list of Kernels is working again, as well as chosen Kernel itself.
Also the Jupyter option in Output appeared, I'm attaching results:
![image](https://user-images.githubusercontent.com/41164803/200026147-82268e7c-ba68-4b9a-80fd-0eba5ad1b61f.png)

Thanks again for your quick response, I've been smashing my head against the table for last 2 days because of this.

**Comment by amunger** [comment]
great to hear that worked for you. 

If you get a chance, it would still be great to see an error message about why it was failing to activate in case something else is broken that we don't know about. Try switching back to release, toggle developer tools, open the console tab and look for an error message specific to the Jupyter extension. There should be something about failing to activate.

![image](https://user-images.githubusercontent.com/2019016/200030168-e4f3f893-3d60-4f92-8a7e-19188ef37feb.png)
