### ISSUE TITLE
Remove/merge preferred controller, default controller, loader, registration, etc

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11914]
Currently we have both `controllerDefaultService` and `controllerPreferredService`, which have overlap but differ a bit at the same time.

**Comment by rebornix** [comment]
While we consolidate these two services, we should probably also simply how we create default/preferred controller, which currently is based on some heuristics, including:

* whether it's `localOnly`
* whether there is any kernel created (when there is an active python intepreter)
* whether we are connected to a remote (traditional flow)

**Comment by DonJayamanne** [comment]
* ControllerDefaultService -> Determines the 'default' kernel for a notebook. Default is what kernel should be used if there's no metadata in a notebook.
* ControllerPreferredService -> Computes and tracks the preferred kernel for a notebook. Preferred is determined from the metadata in the notebook. If no metadata is found, the default kernel is used.
* KernelRankingHelper.isExactMatch -> This seems to doe both of the above items as well!
* IW - We create the controller for active interrpeter always
* CibtrikkerKiader - we create active interpreter controller 
* notebookKernelSourceTracker - we show/hide controllers per notebook
* controllerPreferredService, vscodeNotebookController and notebookKernelSourceTracker
    * All three of these update the affinity of a controller with a notebook

**Comment by rebornix** [comment]
> ControllerDefaultService -> Determines the 'default' kernel for a notebook. Default is what kernel should be used if there's no metadata in a notebook.
> ControllerPreferredService -> Computes and tracks the preferred kernel for a notebook. Preferred is determined from the metadata in the notebook. If no metadata is found, the default kernel is used.

I wonder from user or VS Code API's perspective if these two services are the same, both promoting one controller over another. For Jupyter internal components, would these two services be private (not injectable)? Otherwise we would have confusion of which service to use.

**Comment by DonJayamanne** [comment]
Also found that the methdo `findPreferredKernelExactMatch` doesn't find the exact match, instead this finds a `close` match.

**Comment by DonJayamanne** [comment]
Next to do item, 
* [ ] KernelRankingHelper.isExactMatch -> This seems to doe both of the above items as well!

**Comment by DonJayamanne** [comment]
Most of the work is done, we'll need to wait for the new Kernel Picker to be stable, and once we delete the old code, then reviewing the existing code/structure would be simpler

**Comment by DonJayamanne** [comment]
Marking as closed
