### ISSUE TITLE
Current selected kernel not showing at the top of the kernel picker

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11912]
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/876920/192334929-7c5ece68-4b73-4efb-9204-d429e3674fcc.png">

I have to scroll the list to the very bottom and then I saw the selected venv kernel.

**Comment by DonJayamanne** [comment]
Should be fixed with teh new kernel picker
