### ISSUE TITLE
Duplicated intellisense in .ipynb files

### ISSUE THREAD

**Issue by alanyoungCN** [microsoft/vscode-jupyter#11938]
## Environment data

-   Language Server version: v2022.11.11
-   OS and version: MacOS
-   Jupyter Extension version: v2022.9.1202862440
-   Python Extension version: v2022.18.1
-   Python version: 3.9

## Code Snippet

```python
import numpy as np

foo = np.random.rand(5, 2, 4)

print(foo)
```

## Expected behaviour

Show only single intellisense/suggestion/information.

## Actual behaviour

Show intellisense/suggestion/information twice.
![image](https://user-images.githubusercontent.com/32586930/199951059-248a6daa-bf7a-464b-ae5a-9629acd330fd.png)
![image](https://user-images.githubusercontent.com/32586930/199951114-6b9f491a-bc47-4667-ad3f-38e68b5dc0d1.png)

## Repro Steps

1. Create a folder and create a new ipynb file.
2. Code and point to some tokens or package names.

## P.S.

There have been some discussions (https://github.com/microsoft/pylance-release/issues/3027) about this issue and according to @debonte, pylance will not support `python.pylanceLspNotebooksEnabled` option and remove old notebooks implementation (it seems the option has been removed but **the jupyter implementation remains old**), I still think this is an abnormal behavior. So how to fix this or use the new notebooks implementation?

**Comment by rchiodo** [comment]
My guess here is that this is actually in the python extension. That the python extension is saying to jupyter that it should use the concat language server.

However, I'm wondering if the jupyter extension ever needs to have a language server anymore? Can we just remove it? Or maybe just have it available when pylance isn't in use?

**Comment by rchiodo** [comment]
Oh this is fixed in the prerelese version. If you upgrade the Jupyter Extension to 

Name: Jupyter
Id: ms-toolsai.jupyter
Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.
Version: 2022.11.1003131031
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

The problem goes away.

**Comment by ZupoLlask** [comment]
> > Oh this is fixed in the prerelese version. If you upgrade the Jupyter Extension to
> > Name: Jupyter Id: ms-toolsai.jupyter
> > Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.
> > Version: 2022.11.1003131031
> > Publisher: Microsoft
> > VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
> > The problem goes away.
> 
> B.t.w. latest pre-release version (v2022.11.1003291043) will not start, but the exact version mentioned by @rchiodo works! And fixes the duplicate symbols issue.

I'm also having this problem with that same pre-release version!

**Comment by cameron-chen** [comment]
> @SjoerdV or @ZupoLlask - could you open a new issue with some further details if pre-release is still not working for you? Either with the logs from `Jupyter: show output` or any error messages in the developer tools: `Developer: toggle developer tools`

Hello @amunger , can you take a look? I open a new issue for the problem.

https://github.com/microsoft/vscode-jupyter/issues/12200#issue-1467746090

**Comment by wissambenhaddad** [comment]
Hello, experiencing the same problem on my Macbook pro m1 2020 ( Macos Ventura 13.0.1 )
is there any fix yet ?

**Comment by Slope86** [comment]
> Hello, experiencing the same problem on my Macbook pro m1 2020 ( Macos Ventura 13.0.1 ) is there any fix yet ?

Try upgrading your Jupyter Extension to pre-release version v2022.11.1003281132

**Comment by maxbane** [comment]
> > Hello, experiencing the same problem on my Macbook pro m1 2020 ( Macos Ventura 13.0.1 ) is there any fix yet ?
> 
> Try upgrading your Jupyter Extension to pre-release version v2022.11.1003281132

Just to make it as explicit as possible for anyone as daft as me: on the extension page inside vs code, you have to click "Switch to Pre-Release Version", then click the green down arrow next to "Uninstall", click "Install Another Version...", click on v2022.11.1003281132, then finally reload window. It took me forever to find "Install Another Version...".

**Comment by vbuxbaum** [comment]
Hi everyone! 

Changing to pre-release version also worked for me in version `v2022.11.1003301027` ✅

**Comment by GladioFeng** [comment]
I have the same problem

**Comment by debonte** [comment]
@GladioFeng, see https://github.com/microsoft/pylance-release/issues/3693#issuecomment-1331140153

**Comment by GladioFeng** [comment]
> @GladioFeng, see [microsoft/pylance-release#3693 (comment)](https://github.com/microsoft/pylance-release/issues/3693#issuecomment-1331140153)

thanks I have solved the problem by update jupyter extension to v2022.11.1003412109

**Comment by GladioFeng** [comment]
> @GladioFeng, see [microsoft/pylance-release#3693 (comment)](https://github.com/microsoft/pylance-release/issues/3693#issuecomment-1331140153)

thanks I have solved the problem by update jupyter extension to v2022.11.1003412109

**Comment by yibenhuang** [comment]
@debonte Hi, It seems that I am still encountering such a problem. When I have not started the kernel, I only see one suggestion. But after running the cell and entering the same command again, I will see repeated suggestions.

If I haven't run this cell yet, what I can see is:
<img width="653" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/62163340/b340a98b-fdbb-44ed-a698-ed1d161d5fb5">

After I ran the cell to import the module, repeated suggestions appeared.
<img width="658" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/62163340/b9797084-114c-4e47-b02d-08f3cc7d27c5">

Reported on: 
VSCode Version: 1.79.0
Jupyter: v2023.5.1001582324
Pylance: v2023.6.10
Python: v2023.10.0

**Comment by ZupoLlask** [comment]
@yibenhuang I'm also getting that same behavior...

**Comment by debonte** [comment]
@yibenhuang, @ZupoLlask, I believe you are hitting https://github.com/microsoft/vscode-jupyter/issues/13596. If you disagree, please open a new issue.
