### ISSUE TITLE
VSCode not finding kernel, that is found in jupyter kernelspec command

### ISSUE THREAD

**Issue by Quafadas** [microsoft/vscode-jupyter#11935]
## Environment data

-   VS Code version: 1.73.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.9.1202862440
-   Python Extension version (available under the Extensions sidebar): N/A
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: N/A
-   Type of virtual environment used: N/A
-   Jupyter server running: Local 

## Expected behaviour

The scala kernel to be found. I can find these entries in the logs, by setting to "verbose", 

debug 10:47:42.361: Loading kernelspec from c:\Users\partens\AppData\Roaming\jupyter\kernels\scala3Local\kernel.json for 
debug 10:47:42.361: Loading kernelspec from c:\ProgramData\jupyter\kernels\scala3\kernel.json 

But I can't see anything further, about why they are then "not found" or otherwise not appearing in the UI, ideally, it would be possible to trace that back, in the logs.

## Actual behaviour

![image](https://user-images.githubusercontent.com/24899792/200281008-3886245e-ec15-4dab-9abb-9a8a6f35ede6.png)

## Steps to reproduce:

I'm guessing this is environmental,  and hence hard to provide concrete steps for :-(... if I can provide more useful info, I'm happy to.  

## Logs

Struggling to upload the log, set to verbose, of Jupyter on startup ... but I'll find a way if it helps?

**Comment by DonJayamanne** [comment]
@Quafadas 
Thanks for filing this issue, I'm sorry yo'ure running into this issue.
I believe we've addressed this issue, please could you:
* Install VS Code insiders
* Install the pre-release version of the Python extension
* Install the pre-release version of the Jupyter extension

If the problem still persists in the pre-reelase version then please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by Quafadas** [comment]
@DonJayamanne 
Thanks for writing back. Although I wasn't able to download VS Code insiders (at work), but  I was able to switch to the pre-release of Python and Jupyter extensions... 

... and that now does find the kernels... 

Thanks for the fix ... I'll close this and excitedly await the next release :-).
