### ISSUE TITLE
Repeated existInFile blocking activation

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11948]
<img width="1567" alt="image" src="https://user-images.githubusercontent.com/876920/200631878-05464ad5-4123-44cf-a5de-e7fd72fead47.png">

It seems we are checking cache for every local kernel spec we found and each call is slow. We may want to listen to the onChange event instead of onCreate

https://github.com/microsoft/vscode-jupyter/blob/e6de0d3490be175081e94d7324c0b9f7406d4ea4/src/notebooks/controllers/connectionTracker.ts#L38

**Comment by rebornix** [comment]
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/876920/200637127-153c5389-afbf-4bef-bba4-f6beb01e69aa.png">

**Comment by DonJayamanne** [comment]
Dcone
