### ISSUE TITLE
Drawback with new kernel quick pick UI

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#11941]
Scenario:
* User has .net interactive or Julia extension installed
* User has jupyter extension installed
* User opens an existing notebook for the first time & hits the run button

Note: Jupyter has not seen this notebook before

1. VS Code sees kernsl from .net or julia extesnion
2. VS Code does not see a kernel from Juypter
3. VS Code will start execution of the cell against the .net or julia extension

Hence user will never be presented with the option of selecting a kernel.

@rebornix Is it possible to tweek VS Code to display the kernel picker if there are at least 2 items in the kernel quick pick. Where one item is a controller and the other is a command (or is this already how VS Code works).

**Comment by DonJayamanne** [comment]
**Solution:**
If user has never selected a kernel for this notebook before, then upon hitting `Run` user will be presented with the kernel picker.
(this way users can see new option for the Jupyter kernel picker `Select Kernel Source` & they can now chose something from the new ui)

**Comment by rebornix** [comment]
We will show progress when Jupyter is activating and Jupyter should start a progress during activation.

**Comment by mjbvz** [comment]
For verification, how do I get the kernel picker to show? When I create a new `.ipynb` file, it seems like my existing python interpreter is automatically selected

**Comment by rebornix** [comment]
@mjbvz thanks, @DonJayamanne already verified this offline so I'm going to add verified label to it.
