### ISSUE TITLE
Use nodejs fs.realPath instead of Pythons os.path.realpath

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1194]
Using node API is faster, much faster.
For every kernel spec we discover we end up spinning a Python process.
E.g. if we have 10 kernel specs, then we spin up 10 pythhon processes to run `os.path.realpath`
This takes time, running the corresponding nodejs code is simpler and faster.

```python
    const result = await pythonRunner.exec(
        ['-c', `import os;print(os.path.realpath("${expectedPath.replace(/\\/g, '\\\\')}"))`],
```

**Comment by rchiodo** [comment]
As part of the kernel refactor I'm going to do this. Makes writing the tests easier since I don't need to have python execution.
