### ISSUE TITLE
Change tests to account for lazy loading of controllers and Python environments

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#11957]
Change tests to account for lazy loading of controllers:
* IW, Debugger, Kernels, etc will need to account for the fact that Controllers are not always created   
With the new kernel picker UI, user will have to select a kernel from quick pick before they are presented with controllers.  
I.e. for the purpose of the tests, we might want to manually create controllers or chagne how the tests are executed.

* IW, Debugger, Kernels, etc, will need to account for the fact that Python enviornments are lazy loaded
E.g. here are hacy work arounds
```typescript

        let lastError: Error | undefined = undefined;
        const [activeInterpreter, interpreter1, interpreter2] = await waitForCondition(
            async () => {
                try {
                    return await Promise.all([
                        interpreterService.getActiveInterpreter(),
                        interpreterService.getInterpreterDetails(venvNoKernelPython),
                        interpreterService.getInterpreterDetails(venvKernelPython)
                    ]);
                } catch (ex) {
                    lastError = ex;
                }
            },
            defaultNotebookTestTimeout,
            () => `Failed to get interpreter information for 1,2 &/or 3, ${lastError?.toString()}`
        );

```

**Comment by amunger** [comment]
@DonJayamanne - Do you have some examples to help us with this task?

**Comment by DonJayamanne** [comment]
Today our tests that start kernels (debugger, IW) & a few others, rely on full end to end test
* I.e. we open a notebook/IW and wait for the controllers to get created
* Then we wait for the right controller to get selected
* Nect we wait for this controller to start

All of the above is slow and can be flaky if not done correctly (we have quite a lot of code to ensure things work correctly with local and remote kernels in our tests), by work, i mean ensure we select the right kernel.

Its simpler to instead:
* Write code that would create the kernel manually in the tests
* Test code against the kernel

The tests in `src/test/datascience/notebook/executionService.vscode.test.ts` were such tests and i've since moidified them, and now run in a matter of seconds and are lot more stable (less flaky).

Flakiness is a result of the test infrastructure (as there's no user here to select a kernel once they are all loaded in the quick pick). Hence the code we have ia very hacky (been updated time and time again to work around these timing issues)

Benefits of re-writing some of the tests:
* Faster tests
    * E.g. for IW i think we can have just one or tw tests that tests the whole thing end to end
    * The other tests can be written the same way as in `ececutionService.vscode.test.ts`
* Reduce likeliness of flaky tests
    * One could argue that flakiness is a sign of bugs in the code and i totally agree with that, and we should fix them.
    * However i/ve found recently that majority of the flakyness we have are a result of controllers not getting selected correctly, not getting created in time or getting disposed incorrectly or the like.

**Comment by roblourens** [comment]
It looks like this means executing code directly against the Jupyter kernel and not involving the vscode UI at all, right? But is it really possible to do that for debugging, since vscode's debug client is involved?

**Comment by DonJayamanne** [comment]
> But is it really possible to do that for debugging, since vscode's debug client is involved?

Aah yes, good point

**Comment by DonJayamanne** [comment]
Done, but the way we find the  controllers associated with the active python env on CI servers is very horrible.
Its legacy code that has been updated over & over to account for the changes, hence its got a lot of debt and makes it very difficult to manage.
However since its tests, i leave it for the ownsers of each area to simplify the code, or perhaps I can do that slowly over time as i update my own areas.
