### ISSUE TITLE
Don't update version in .ipynb files until an edit has been made

### ISSUE THREAD

**Issue by tbenthompson** [microsoft/vscode-jupyter#11964]
When I'm using a different Python version than the one used to create a Jupyter notebook, opening a Jupyter notebook results in the version in the .ipynb file changing. So, just from exploring a repository, I get lots of small diffs that show up in git.

```
-   "version": "3.10.5"
+   "version": "3.10.6"
```

It seems like this edit is not necessary until some kind of modification is made to the notebook. Essentially, I'm suggesting being lazy about this kind of change and ignoring it until something else about the notebook changes.

Thanks!!

**Comment by tbenthompson** [comment]
Here's another example
```
@ research/adagrid/lewis_ada.ipynb:560 @
 ],
 "metadata": {
  "kernelspec": {
-   "display_name": "Python 3.10.5 ('confirm')",
+   "display_name": "Python 3.9.6 64-bit",
   "language": "python",
   "name": "python3"
  },
@ research/adagrid/lewis_ada.ipynb:574 @
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
-   "version": "3.10.5"
+   "version": "3.9.6"
  },
  "vscode": {
   "interpreter": {
-    "hash": "b4c6ec5b2d6c7b38df115d547b82cd53ca25eea58d87299956d35a9dc79f19f1"
+    "hash": "31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"
   }
  }
 },
```

**Comment by rsatrioadi** [comment]
I very much second this.

**Comment by 2-5** [comment]
I encounter the same issue, with a twist. There are two version numbers in the metadata, but only one of them is updated, `language_info.version`, the version in `kernelspec.display_name` is not updated. The `venv` Python version is `3.10.8`.

```json
"metadata": {
 "kernelspec": {
  "display_name": "Python 3.10.4 ('.pyenv': venv)",
 },
 "language_info": {
  "version": "3.10.8"
 },
}
```

**Comment by DonJayamanne** [comment]
> opening a Jupyter notebook results in the version in the .ipynb file changing. So, just from exploring a repository, I get lots of small diffs that show up in git.

This should now be fixed in the latest version
The kernel is no longer automatically selected, hence notebook metadata is not updated.
The update takes place when users select a kernel (either manually or a side effect of executing a cell)
