### ISSUE TITLE
JSON rendering always expanded | `extended` metadata from IPython / Jupyter is ignored  

### ISSUE THREAD

**Issue by gsnidero** [microsoft/vscode-jupyter#11961]
## Environment data

-   VS Code version:
Version: 1.73.0 (Universal)
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:38:50.881Z (1 wk ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No
-   Jupyter Extension version (available under the Extensions sidebar): 
v2022.9.1202862440
-   Python Extension version (available under the Extensions sidebar):
v2022.18.1
-   OS (Windows | Mac | Linux distro) and version:
Apple M1 Pro | macOS Ventura Version 13.0 (22A380)
-   Python and/or Anaconda version:
python 3.10.5 installed with pyenv
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): 
virtualenv
-   Jupyter server running: 
Local

## Expected behaviour

In JupyterLab, when rendering a json output one can control if the data is `extended` or not

<img width="976" alt="image" src="https://user-images.githubusercontent.com/4365415/200827831-5e361d19-2add-42b8-9421-936e37efc1d7.png">

## Actual behaviour

In VSCode-jupyter, the `extended` metadata is not used

<img width="841" alt="image" src="https://user-images.githubusercontent.com/4365415/200827466-3f0ddd64-dd66-49c0-9b22-4bbff1937dd0.png">

## Steps to reproduce:
Run this on a notebook

```
from IPython.display import JSON

# first cell 
JSON({'a': [1, 2, 3, 4,], 'b': {'inner1': 'helloworld', 'inner2': 'foobar'}}, metadata={'expanded': True})

# second cell 
JSON({'a': [1, 2, 3, 4,], 'b': {'inner1': 'helloworld', 'inner2': 'foobar'}}, metadata={'expanded': False})
```

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
nfo 12:27:24.118: Restart requested file:///Users/giacomosnidero/repos/test-tech/Untitled-1.ipynb
info 12:27:24.118: Restart kernel execution
info 12:27:24.118: Restarting 7aa332df-9114-4368-87e8-7fc5ff4ea0d1
[I 12:27:24.122 NotebookApp] Creating new notebook in 
info 12:27:24.130: installMissingDependencies /Users/giacomosnidero/.pyenv/versions/3.10.5/envs/test-tech-3.10.5/bin/python, ui.disabled=false for resource '/Users/giacomosnidero/repos/test-tech/Untitled-1.ipynb'
info 12:27:24.130: Got env vars with python /Users/giacomosnidero/.pyenv/versions/3.10.5/envs/test-tech-3.10.5/bin/python, with env var count 54 and custom env var count 0 in 0ms
info 12:27:24.130: Got env vars ourselves faster /Users/giacomosnidero/.pyenv/versions/3.10.5/envs/test-tech-3.10.5/bin/python with env var count 54 in 0ms
info 12:27:24.131: Process Execution: > ~/.pyenv/versions/3.10.5/envs/test-tech-3.10.5/bin/python -c "import ipykernel"
> ~/.pyenv/versions/3.10.5/envs/test-tech-3.10.5/bin/python -c "import ipykernel"
info 12:27:24.236: Spec argv[0] updated from '/Users/giacomosnidero/.pyenv/versions/3.10.5/envs/test-tech-3.10.5/bin/python' to '/Users/giacomosnidero/.pyenv/versions/3.10.5/envs/test-tech-3.10.5/bin/python'
info 12:27:24.237: Got env vars with python /Users/giacomosnidero/.pyenv/versions/3.10.5/envs/test-tech-3.10.5/bin/python, with env var count 54 and custom env var count 0 in 1ms
info 12:27:24.237: Got env vars ourselves faster /Users/giacomosnidero/.pyenv/versions/3.10.5/envs/test-tech-3.10.5/bin/python with env var count 54 in 1ms
[I 12:27:24.258 NotebookApp] Kernel started: aa976560-51bb-4d4a-93f2-8b32de369622, name: python3105jvsc74a57bd075b429ef1bb511660894b825902db379d3782b7d15b9e72440ff49932a6e89de
[W 12:27:24.266 NotebookApp] delete /Untitled-1-jvsc-b6a81cb3-8cb6-4b78-8a5b-f38e49c1dd7ecdbf5b7e-0525-470b-9ca2-ec26e60a722c.ipynb
info 12:27:24.691: Got new session aa976560-51bb-4d4a-93f2-8b32de369622
info 12:27:24.691: Started new restart session
[I 12:27:24.694 NotebookApp] Kernel shutdown: 7aa332df-9114-4368-87e8-7fc5ff4ea0d1
info 12:27:24.779: Got env vars with python /Users/giacomosnidero/.pyenv/versions/3.10.5/envs/test-tech-3.10.5/bin/python, with env var count 54 and custom env var count 0 in 1ms
info 12:27:24.779: Got env vars ourselves faster /Users/giacomosnidero/.pyenv/versions/3.10.5/envs/test-tech-3.10.5/bin/python with env var count 54 in 1ms
info 12:27:24.779: Process Execution: > ~/.pyenv/versions/3.10.5/envs/test-tech-3.10.5/bin/python -c "import sys;print(sys.executable)"
> ~/.pyenv/versions/3.10.5/envs/test-tech-3.10.5/bin/python -c "import sys;print(sys.executable)"
info 12:27:24.780: UpdateWorkingDirectoryAndPath in Kernel

```

</p>
</details>

**Comment by vvilhonen** [comment]
This would be incredibly useful! I'm currently writing json to file and then using the vscode's internal json viewer to inspect unknown large json objects or using jq on command-line. Having functionality of the screenshot in the cell output when using `display_json` or `JSON` would make my whole year ❤️ 
<img width="557" alt="Screenshot 2022-12-20 at 14 15 04" src="https://user-images.githubusercontent.com/88401/208665119-a64a3bc0-2c0f-4872-831a-0bfa909ba488.png">

**Comment by DonJayamanne** [comment]
> tly writing json to file and then using the vscode's internal json viewer to inspe

@mjbvz I know this used to be possible ( I distinctly recall testing JSON and collapsing individual nodes), 

looks like we're no longer using the built-in editors to display the outputs, instead we use the mardown renderer to render different languages.
For instance if you look at the docs you can see selection of code and the like is possible (see screesnshots) https://code.visualstudio.com/api/extension-guides/notebook

@mjbvz Is this deliberate? if so, I think we might want to update the docs (I can file a separate issue for that) & perhaps leave the above request as a feature request

**Comment by mjbvz** [comment]
@rebornix Do you remember when this changed? I think it's been this way for a long time now since all output items should go through our output renders apis

**Comment by DonJayamanne** [comment]
@rebornix pinging, if this was removed, we might want to update the docs

**Comment by rebornix** [comment]
We don't have the "monaco-editor" renderer support since we moved all renderers out from core to extensions. 

> we might want to update the docs

Good call, we should update.

**Comment by shtratos** [comment]
are any workarounds or extensions for this?

**Comment by Welenkin** [comment]
Kind of workaound for now, install Monaco Editor renderer from extensions manager.

![image](https://github.com/microsoft/vscode-jupyter/assets/97966861/a3a552cb-9d78-47ae-9db2-8ac5493357a0)

run the code once, and select the 3 dots at the left of the output. select "change presentation"

![image](https://github.com/microsoft/vscode-jupyter/assets/97966861/6aed1d11-4ec1-4ab4-a451-9273c1a09bef)

Select monaco renderer. and its working as expected.

![image](https://github.com/microsoft/vscode-jupyter/assets/97966861/1821c689-1968-49aa-a081-5052a1c602c7)

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
