### ISSUE TITLE
Native Notebooks - Kernel Restart (Progress Indicator) Indicator

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#1197]
# Native Notebooks

## Current Behavior: 
When restarting the kernel the run all button and cell toolbar icons flash for cells that have outputs (for either selected or editor state). No cell toolbar icons appear to flash for cells that do not have outputs. 

![NNb Kernel Restart](https://user-images.githubusercontent.com/19276747/90815897-41a36380-e2e0-11ea-8f4c-396692b22e8e.gif)

## Expected Behavior: 
1. Disable green restart kernel button while in progress. 
2. Disable run all button while in progress.
3. Have blue bar scan across top of notebook canvas while in progress. 
4. Stop blue bar and resurface restart kernel and run buttons when done. 
5. No other icons flashing

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by DavidKutu** [comment]
I talked with VS code and extensions aren't supposed to have access to the blue bar. Will do this with a notification.

**Comment by DonJayamanne** [comment]
Validated
