### ISSUE TITLE
Restore Tensorboard Settings after Reconnect

### ISSUE THREAD

**Issue by ErlerPhilipp** [microsoft/vscode-jupyter#11981]
Type: <b>Feature Request</b>

# Behaviour
## Expected vs. Actual

I'm using Tensorboard in VS Code on a remote training machine. I need so set settings like refresh, pagination limit, smoothing etc.
When I reconnect, all these settings are gone and I have to set them again. Very annoying! For some reason, some of the selected runs stay selected sometimes.

Instead, Tensorboard in VS Code should remember all settings.

A solution could be:
- Store settings of Tensorboard like in the Browser (Cookies?)
- Allow custom CMD args for "Python: Launch Tensorboard" (not sure if Tensorboard has args for all settings)

## Steps to reproduce:

1. Connect VS Code to remote machine (SSH).
2. Open Tensorboard on remote machine (Python: Launch Tensorboard)
3. Change settings, e.g. via cogwheel menu
4. Reconnect VS Code (let local machine sleep or re-open VS Code)
5. Settings are gone

# Diagnostic data

-   Python 3.8.13, conda 4.13.0 (Remote machine)
-   VS Code Python v2022.19.13141010 (Remote machine)
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Experiment 'pythonSurveyNotification' is active
Experiment 'pythonPromptNewToolsExt' is active
LSP Notebooks experiment is enabled
LSP Notebooks interactive window support is enabled
> conda info --json
Python interpreter path: ~/miniconda3/envs/p2s_c11/bin/python
> conda run -n p2s_c11 --no-capture-output python ~/.vscode-server/extensions/ms-python.python-2022.19.13131010/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.19.13131010/pythonFiles/printEnvVariables.py
> ~/miniconda3/bin/python ~/.vscode-server/extensions/ms-python.python-2022.19.13131010/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.19.13131010/pythonFiles/interpreterInfo.py
> ~/miniconda3/envs/p2s_c11/bin/python ~/.vscode-server/extensions/ms-python.python-2022.19.13131010/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.19.13131010/pythonFiles/interpreterInfo.py
> ~/miniconda3/envs/poco/bin/python ~/.vscode-server/extensions/ms-python.python-2022.19.13131010/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.19.13131010/pythonFiles/interpreterInfo.py
> /bin/python3 ~/.vscode-server/extensions/ms-python.python-2022.19.13131010/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.19.13131010/pythonFiles/interpreterInfo.py
> /usr/bin/python3 ~/.vscode-server/extensions/ms-python.python-2022.19.13131010/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.19.13131010/pythonFiles/interpreterInfo.py
Starting Pylance language server.
> conda run -n p2s_c11 --no-capture-output python ~/.vscode-server/extensions/ms-python.python-2022.19.13131010/pythonFiles/get_output_via_markers.py -c "import tensorboard; print(tensorboard.__version__)"
> conda run -n p2s_c11 --no-capture-output python ~/.vscode-server/extensions/ms-python.python-2022.19.13131010/pythonFiles/get_output_via_markers.py -c "import torch_tb_profiler; print(torch_tb_profiler.__version__)"
> conda run -n p2s_c11 --no-capture-output python ~/.vscode-server/extensions/ms-python.python-2022.19.13131010/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.19.13131010/pythonFiles/tensorboard_launcher.py .
[ERROR 2022-10-10 9:35:19.121]: 
NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784


[ERROR 2022-10-10 9:35:19.184]: INFO:pytorch_profiler:Monitor runs begin
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

linting
• pylintArgs: "<placeholder>"

```

</p>
</details>

Extension version: 2022.18.2
VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-48-generic

**Comment by DonJayamanne** [comment]
@ErlerPhilipp 
Thanks for filing this feature request.
With the `Steps to reproduce` i don't see a step where and how you initialize the tensorboard settings.

Do you initialize these via Interactive Window or a Notebook or is this done via the Tensorboad GUI itself.

**Comment by ErlerPhilipp** [comment]
> @ErlerPhilipp Thanks for filing this feature request. With the `Steps to reproduce` i don't see a step where and how you initialize the tensorboard settings.
> 
> Do you initialize these via Interactive Window or a Notebook or is this done via the Tensorboad GUI itself.
I'm using the cogwheel menu in VS Code -> Tensorboard GUI. Not sure what you mean with Interactive Window and Notebook. I'm interacting with Tensorboard directly and manually.

Updated the issue text to clearify.
