### ISSUE TITLE
Wrong font in Jupyter output

### ISSUE THREAD

**Issue by thistlillo** [microsoft/vscode-jupyter#11999]
Despite what specified in the Settings `When set to empty, the Editor: Font Family is used.`:

![image](https://user-images.githubusercontent.com/6717655/201484511-b99f7eff-3308-4f64-b4b9-cdc5e9a1ebd4.png)

When the field `Notebook: Output font family` is left empty as in the screenshot above, the output of a Jupyter cell is rendered with the incorrect font:

![image](https://user-images.githubusercontent.com/6717655/201484588-1046c6e6-7595-4c2f-b093-fdff19708d99.png)

The field `Notebook: Output Font Family` needs to be filled. After providing a font family:
![image](https://user-images.githubusercontent.com/6717655/201487217-a725b8ec-29f4-4bef-8409-96a871cfed87.png)

## Update
Error messages  are unaffected by the setting. VSC keeps printing them with the default font even when a different one has been specified.

![image](https://user-images.githubusercontent.com/6717655/201487171-7057db4f-6481-4887-aa3b-a9f614356869.png)

The text displayed via `display(...)` command uses the correct font even when that field is left empty.

```
Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19043
Sandboxed: No
```
Jupyter: `v2022.9.1202862440`

**Comment by rebornix** [comment]
@amunger maybe you can help give this a check while updating the renderer options.

**Comment by amunger** [comment]
I'm not seeing what you're describing - changing the editor's font also changes the output font: 

![outputFonts](https://user-images.githubusercontent.com/2019016/202272946-00ad0301-67d4-46d7-a801-0418b988b8bb.gif)

Which font family are you trying to use?

**Comment by amunger** [comment]
closing with not enough info
