### ISSUE TITLE
notebook controller is disposed when Interactive window is opened quickly after vs code reload

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#11998]
repro steps: 

1. open a python script and add a `# %%` cell
2. reload vs code
3. run the cell before the `Discovering Python Interpreters` status item finishes
4. if that succeeds, wait until it finishes and run the cell again (otherwise the first cell fails with the below error)
:bug: `notebook controller is DISPOSED. 
View Jupyter [log](command:jupyter.viewOutput) for further details.`

**Comment by DonJayamanne** [comment]
@amunger I think this PR will address this issue https://github.com/microsoft/vscode-jupyter/pull/12009

**Comment by amunger** [comment]
can't repro anymore
