### ISSUE TITLE
Long DI planning

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#12008]
We have around 130+ injectable services/interfaces in Jupyter now and it seems the granularity of our code is high and inversify's planner can take hundreds of ms to prepare for instantiation, below is a js profile captured in debugging

<img width="739" alt="image" src="https://user-images.githubusercontent.com/876920/201571417-83d0545d-82b0-41b9-b141-08261b172ba3.png">

Sometimes it can be worse, here is a js profile of running release in Insiders

<img width="814" alt="image" src="https://user-images.githubusercontent.com/876920/201571819-c8173a0d-c2d6-4113-a8e4-70824b148cde.png">

We tend to make everything injectable, maybe we can revisit our modules and reduce some. With that said, I don't know if we are hitting some limit of inversify.

**Comment by rebornix** [comment]
cc @Tyriar .

`inversify` also contributes 150KB (along with reflect-metadata) to the bundle size though we are only using very few functionalities from it. Exploring writing a simple IOC module (or something similar to VS Code's one) is also an interesting option.

**Comment by DonJayamanne** [comment]
i don't think we should make everything injectable, this was at one point a requirement for testing and now of a ideological requirement.

however with sinon we can easily mock constructors / classes, hence injecting everything isn't necessary at all, we can just instantiate classes as we need them.

with that approach we should be able to get rid of most of the injectables.
ie i think objection is good, bit not an absolute necessity.

**Comment by DonJayamanne** [comment]
> seems the granularity of our code is high and inversify's

i think we r injecting even simple classes when we can just instantiate them.

**Comment by Tyriar** [comment]
> Exploring writing a simple IOC module (or something similar to VS Code's one) is also an interesting option.

xterm.js uses a stripped down version of VS Code's system and it's quite small:

- https://github.com/xtermjs/xterm.js/blob/a351f5758a5126308b90d60b604b528462f6f051/src/common/services/InstantiationService.ts
- https://github.com/xtermjs/xterm.js/blob/a351f5758a5126308b90d60b604b528462f6f051/src/common/services/Services.ts#L125-L153
- https://github.com/xtermjs/xterm.js/blob/a351f5758a5126308b90d60b604b528462f6f051/src/common/services/ServiceRegistry.ts
