### ISSUE TITLE
Native notebook editor --line numbers not show

### ISSUE THREAD

**Issue by ajasja** [microsoft/vscode-jupyter#1200]
Upstream issue https://github.com/microsoft/vscode/issues/106054

# Bug: Native notebook editor --line numbers not show

## Steps to cause the bug to occur

1. Open notebook in "open in preview Editor"
2. Copy some code 
3. Try to show lines either using the Esc + L or the context menu

## Actual behavior
Code lines are not show

![image](https://user-images.githubusercontent.com/19926/90928536-e6d73e00-e3ab-11ea-9681-f9335403f474.png)

## Expected behavior
Lines show at the edge of cell

### Your Jupyter and/or Python environment

-   **Jupyter server running:** Remote
-   **Extension version:** v2020.8.103604
-   **VS Code version:** 1.49.0-insider (user setup)
-   **Setting python.languageServer:** pylance
-   **Python and/or Anaconda version: 3.7.8
-   **OS:** Windows and Linux
-   **Virtual environment:** conda

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by DonJayamanne** [comment]
Moving to validate

**Comment by joyceerhl** [comment]
Validated. Line numbers can now be toggled in the native notebooks interface:

![image](https://user-images.githubusercontent.com/30305945/118430073-1475bd00-b688-11eb-800a-0d299391d645.png)
