### ISSUE TITLE
Confusing layering in extension-side/plotView

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#12016]
I see plotViewHandler.ts uses `Buffer` which is a node.js only type:

https://github.com/microsoft/vscode-jupyter/blob/47ec3908d23518e2cd4599149d7ba0806b0c2eee/src/webviews/extension-side/plotView/plotViewHandler.ts#L62

But it's imported from serviceRegistry.web.ts

https://github.com/microsoft/vscode-jupyter/blob/47ec3908d23518e2cd4599149d7ba0806b0c2eee/src/webviews/extension-side/serviceRegistry.web.ts#L29

Spotted this when working on https://github.com/microsoft/vscode-jupyter/pull/12017, fwiw working with `Buffer` over `ArrayBuffer` did slow me down a bit as I'm much more familiar with the latter.

**Comment by rebornix** [comment]
Since webview features have both webview side and extension host side, we currently have a code structure like 

```
src/webviews/
  - extension
    - feature 1
    - feature 2 
  - webview
    - feature 1
    - feature 2
```

Which give us this headache: where we put common/generic modules. I'm not a fan of introducing `src/webviews/common`, instead I would prefer we move to

```
- src/standalone
  - feature 1
    - common
    - webview
    - extension host
  - feature 2
    - webview
    - extension host
```

cc @DonJayamanne

**Comment by Tyriar** [comment]
Yeah having the closer to each other makes more sense to me. If that folder change does happen I suggest `webview` and `exthost`, that's what I landed on for my extensions as it's nice and concise.

Oh so you mean the absence of `.node.ts` doesn't necessarily mean it's not a node only file because the folder could determine it? The fact that `.node.ts` exists at all then can cause confusion.

**Comment by rebornix** [comment]
@Tyriar importing `node.ts` to `web.ts` feels wrong to me, it's breaking the layers. It's wrong also the other way around. We kind of have to have a `common` folder somewhere to fix this. I guess it's currently working fine as webpack helps us swap buffer https://github.com/microsoft/vscode-jupyter/blob/638795bcd9b45b010a4382efc4c844dd3e10a11d/build/webpack/webpack.extension.web.config.js#L140

**Comment by DonJayamanne** [comment]
Closing in favour of https://github.com/microsoft/vscode-jupyter/issues/14694
