### ISSUE TITLE
Avoid using innerHTML in error-renderer

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#12018]
innerHTML is unsafe here:

https://github.com/microsoft/vscode-jupyter/blob/47ec3908d23518e2cd4599149d7ba0806b0c2eee/src/webviews/webview-side/error-renderer/index.ts#L133

A bunch of escaping/sanitizing is done in here, that could be avoided by constructing the anchors via `document`:

https://github.com/microsoft/vscode-jupyter/blob/47ec3908d23518e2cd4599149d7ba0806b0c2eee/src/webviews/webview-side/error-renderer/index.ts#L237-L277

Part of #11996 as it would allow us to remove `lodash/escape`

**Comment by Tyriar** [comment]
This is a bigger task than I anticipated due to the ansi conversion as well, unassigning but it's still a code smell imo

**Comment by rebornix** [comment]
We probably shouldn't invest in this but merge its functionality with the builtin error renderer.

**Comment by Tyriar** [comment]
@rebornix to help me understand, what's the builtin error renderer?

**Comment by rebornix** [comment]
@Tyriar we have error renderer out of box https://github.com/microsoft/vscode/tree/main/extensions/notebook-renderers. The reason we still have this one is IW has special logic of link/file opening. We do want to merge these two.

**Comment by amunger** [comment]
preferred solution for merging https://github.com/microsoft/vscode-jupyter/issues/12285

**Comment by rebornix** [comment]
With https://github.com/microsoft/vscode-jupyter/issues/12285 we will remove the error renderer, let's track it there.
