### ISSUE TITLE
Flaky tests make contribution more difficult and are a project health concern

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#12014]
I just created 3 PRs and all of them failed with flakes. I suggest this project takes the approach of the VS Code repo where any flaky test is fixed immediately or disabled and looked at during debt week. This is especially important when CI blocks merging.

**Comment by DonJayamanne** [comment]
Closing as there are no more flaky tests
Almost all of the CI jobs are now mandatory beacuse there aren't any flaky test, making them mandatory enforces the need to fix the flaky test or skip them entirely (until they're fixed)
