### ISSUE TITLE
Listing local kernel specs when using a devcontainer

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#12024]
- Open a jupyter notebook in a local devcontainer
- The kernel picker lists a kernel from a local kernel spec, with a local path (`/Users/roblou/...`) that isn't actually accessible from the devcontainer
- If I pick it, it says that I need to install pip and ipykernel, which isn't true. If I click the option to install it for me, that doesn't work.

**Comment by DonJayamanne** [comment]
> The kernel picker lists a kernel from a local kernel spec, with a local path (/Users/roblou/...) that isn't actually accessible from the devcontainer

@roblourens not sure how this is possible.
Is this because of the cache moving across machines?

I thought the extension host is running on the remote machine (dev container), hence how is that able to access the files on your machine?

**Comment by roblourens** [comment]
The cache seems like a likely culprit, how is it stored?

> hence how is that able to access the files on your machine?

Right, it's not

**Comment by DonJayamanne** [comment]
We store the cache in the global state.

**Comment by DonJayamanne** [comment]
Will try and debug this.

**Comment by DonJayamanne** [comment]
Should now be fixced.
