### ISSUE TITLE
Consider removing setimmediate module

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#12032]
It's not clear why this exists, `setImmediate` is a legacy IE function, not standard across browsers and should therefore be avoided.

https://github.com/microsoft/vscode-jupyter/blob/638795bcd9b45b010a4382efc4c844dd3e10a11d/src/extension.web.ts#L14-L19

https://github.com/microsoft/vscode-jupyter/issues/10621 calls out regexp lookbehind, not setImmediate or RAF? I also can't see any usages of `requestAnimationFrame` or `setImmediate` in the codebase?

**Comment by Tyriar** [comment]
I see it was added by @DonJayamanne

**Comment by DonJayamanne** [comment]
@Tyriar 
I've added more comments of the exact place this is required

```
// Note: requestAnimationFrame is required in `@jupyterlab/services/lib/kernel/future.js` while ext host runs in webworker (running extension in web).
// & if `requestAnimationFrame` isn't available, then `setImmediate` is used as a fallback.
```

**Comment by DonJayamanne** [comment]
I.e. we do need `setImmediate` in webworkers on Safari, unless of course we change the code in the dependant node module.

**Comment by Tyriar** [comment]
I see https://github.com/jupyterlab/jupyterlab/blob/79013299873236a01590feaf1dde6bc6ba5fdc0f/packages/services/src/kernel/future.ts#L336-L347

Is this library only designed to work in node.js? Could we contribute a fallback to `setTimeout`? Could we just polyfill `setImmediate(cb)` to equal `setTimeout(cb)`?

**Comment by DonJayamanne** [comment]
> Could we just polyfill setImmediate(cb) to equal setTimeout(cb)?

Yes we could.

**Comment by rzhao271** [comment]
What are some verification steps for this issue?

**Comment by Tyriar** [comment]
@DonJayamanne could you please provide some steps for this?

**Comment by rzhao271** [comment]
I'll check the following:
- [ ] See where setImmediate is being used
- [ ] Test the extension on the web
