### ISSUE TITLE
No cell progress indicator when running cell against non-python kernel

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1203]
**Native Notebooks**
* Open existing notebook with C# cells
* Run a cell
Nothing happens for a while, and then all of a sudden it starts running a cell.

I've tripped into this a number of times and click the `run` button a number of times assuming it isn't running.

The problem is we are running, but its slow to start the kernel and theres no feedback about this.
Ideally i'd like to see the `spinner` against the cell or the cell `play` icon change to `stop` icon.

**NOTE: We shoudlnt' work on this just yet.**
Wait for https://github.com/microsoft/vscode/issues/103713
* This will control how and when a cell is marked as busy.

**Comment by DonJayamanne** [comment]
TODO: Investigate & get estimate

**Comment by DonJayamanne** [comment]
Working as expected, I can see a progress message on bottom right of VSC.

**Comment by IanMatthewHuff** [comment]
Validated. Looks good. Now I see the spinner icon while the kernel is loading (used Julia), then the cell progress timer when actually executing the cell.
