### ISSUE TITLE
Typing `help(...)` or `?fun` to open in a text editor

### ISSUE THREAD

**Issue by Fred-Wu** [microsoft/vscode-jupyter#12043]
In the interactive window, if the output exceeds the size limit, it provides the option to open the full output in a text editor. But for a shorter description, it does not offer such option. 

I was wondering whether it could be supported to open the text editor directly to show the help manual when typing `help()` or `?fun`.

**Comment by amunger** [comment]
Do you mean that it would skip placing the output in the notebook and just go straight to an editor, or that all outputs should include a link to open them in an editor, no matter how long they are?

**Comment by Fred-Wu** [comment]
> Do you mean that it would skip placing the output in the notebook and just go straight to an editor, or that all outputs should include a link to open them in an editor, no matter how long they are?

Ideally, go straight to open the contextual help to an editor.
