### ISSUE TITLE
Language of default cells in native notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1204]
Based on the current VSCode notebook design, the default language of cells is always the first item in the `NoteboookDocument.languages` property.
This property contains a list of langauges the notebook supports, we'll be adding csharp, javascript, fsharp, etc (languages of all kernels found on user machine).

However majority of the users might not want this, majority of the users would be creating Python notebooks.

* 1. Should we default all notebooks to be python?
	* This would work.
	* However, if a user has a `csharp` kernel, this is annoying
* 2. Should we instead leave the current behavior
	* Default cell language to the first item in the list of languages
	* Assumption here is, if user has multiple kernels installed, then they are working on other languages (hence its wrong to place `python` first)
* 3. Go with option 2
	* Default cell language of notebook to the language of the last used notebook.
	* This way, if user opens an existing notebook and it is julia, and next time they create a blank notebook, then the default cell is always `julia`
	* Similarly, if user opens an existing notebook with `rust`, then default language for all cells in this notebook is `rust`.

I think **option 3** might be the best way forward.

**Comment by DonJayamanne** [comment]
Code has been written but was disabled. We need to enable this as VSC issues have bee resolved.

**Comment by rchiodo** [comment]
Are you saying more work has to be done? It is not behaving as specified in option 3. 

I did this:

1. Create new blank notebook
2. Make it C#
3. Save it.
4. Cell changes back to python (seems bad)
5. Change back to C#
6. Change kernel to C#
7. Run a cell
8. Create new notebook
9. New notebook is also python.

**Comment by DonJayamanne** [comment]
Yikes, will move back to backlog, thanks

**Comment by DonJayamanne** [comment]
Seems like a regression in VS Code, https://github.com/microsoft/vscode/issues/114650

**Comment by kieferrm** [comment]
The upstream issue is closed.

**Comment by IanMatthewHuff** [comment]
Java notebook maintained language after save and reopen, and after that creating a new notebook was created with Java as default.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/32894391-51a2-4f57-82a0-9d8d93216dd1)
Validated.
