### ISSUE TITLE
Kernels listed selecting interpreter for notebook don't match normal Python interpreter selection (and don't contain my interpreter)

### ISSUE THREAD

**Issue by gjoseph92** [microsoft/vscode-jupyter#12054]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

* Created new Poetry environment `dask-pyspy-demo` and installed packages, _not_ including jupyterlab
* Refreshed window, ran "Python: Select Interpreter", picked `dask-pyspy-demo`:
![Screen Shot 2022-11-16 at 4 49 00 PM](https://user-images.githubusercontent.com/3309802/202319695-014d5e7d-a6fd-4748-8d8a-b63d6fe30bf0.png)
* Created a notebook, ran "Select notebook kernel".
![Screen Shot 2022-11-16 at 4 49 21 PM](https://user-images.githubusercontent.com/3309802/202319780-f28397c5-2893-4e44-9b85-578d015d18a3.png)

`dask-pyspy-demo` does not show up. I would expect it to show up.

* `poetry add --group dev jupyterlab`
* Refreshed window again
* Ran "Select notebook kernel", `dask-pyspy-demo` still doesn't show up.

One other thing: when restarting the window, notice how "Select Kernel" flashes a couple times to the interpreter I actually want (`dask-pyspy-demo-...`), then lands back on "Select Kernel":
https://user-images.githubusercontent.com/3309802/202320529-9f4360b5-c653-4054-9120-90ba855307de.mp4

### VS Code Version

Version: 1.73.1 Commit: 6261075646f055b99068d3688932416f2346dd3b Date: 2022-11-09T02:08:38.961Z (1 wk ago) Electron: 19.0.17 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Darwin x64 21.6.0 Sandboxed: No

### Jupyter Extension Version

v2022.9.1303220346

### Jupyter logs

```shell
Visual Studio Code (1.73.1, undefined, desktop)
Jupyter Extension Version: 2022.9.1303220346.
Python Extension Version: 2022.18.2.
Workspace folder /Users/gabe/dev/dask-pyspy-demo
info 16:53:05.763: ZMQ install verified.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 16:53:06.063: LSP Notebooks experiment is disabled -- not in treatment group
info 16:53:06.227: Got env vars ourselves faster /Users/gabe/Library/Caches/pypoetry/virtualenvs/dask-pyspy-demo-6EAlOZQU-py3.9/bin/python with env var count 44 in 137ms
info 16:53:06.229: Process Execution: > ~/Library/Caches/pypoetry/virtualenvs/dask-pyspy-demo-6EAlOZQU-py3.9/bin/python -m pip list
> ~/Library/Caches/pypoetry/virtualenvs/dask-pyspy-demo-6EAlOZQU-py3.9/bin/python -m pip list
info 16:53:06.517: Preferred Remote kernel for /Users/gabe/dev/dask-pyspy-demo/demo.ipynb is undefined
info 16:53:06.517: Find preferred kernel for /Users/gabe/dev/dask-pyspy-demo/demo.ipynb with metadata {"language_info":{"name":"python"},"orig_nbformat":4} & preferred interpreter /Users/gabe/Library/Caches/pypoetry/virtualenvs/dask-pyspy-demo-6EAlOZQU-py3.9/bin/python
info 16:53:06.540: Preferred Remote kernel for /Users/gabe/dev/dask-pyspy-demo/demo.ipynb is undefined
info 16:53:06.540: Preferred kernel .jvsc74a57bd02bc6906351481cef9ac83eabe42cb78287e09e65226f91bd31e6d8b565da21d2./Users/gabe/Library/Caches/pypoetry/virtualenvs/dask-pyspy-demo-6EAlOZQU-py3.9/python./Users/gabe/Library/Caches/pypoetry/virtualenvs/dask-pyspy-demo-6EAlOZQU-py3.9/python.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, [object Object], false, false)
info 16:53:06.541: PreferredConnection: .jvsc74a57bd02bc6906351481cef9ac83eabe42cb78287e09e65226f91bd31e6d8b565da21d2./Users/gabe/Library/Caches/pypoetry/virtualenvs/dask-pyspy-demo-6EAlOZQU-py3.9/python./Users/gabe/Library/Caches/pypoetry/virtualenvs/dask-pyspy-demo-6EAlOZQU-py3.9/python.-m#ipykernel_launcher found for NotebookDocument: /Users/gabe/dev/dask-pyspy-demo/demo.ipynb
info 16:53:06.574: Got env vars with python /Users/gabe/Library/Caches/pypoetry/virtualenvs/dask-pyspy-demo-6EAlOZQU-py3.9/bin/python, with env var count 44 and custom env var count 0 in 483ms
info 16:53:06.746: Preferred Remote kernel for /Users/gabe/dev/dask-pyspy-demo/demo.ipynb is undefined
info 16:53:06.773: Registering dummy command feature
```

### Coding Language and Runtime Version

Python 3.9.4

### Language Extension Version (if applicable)

v2022.18.2

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
@gjoseph92 

I'm sorry you're running into this and thanks for reporting this issue.
I believe we've addressed this issue in the latest main branch.

Please could you install the latest pre-release version of the Jupyter extension and test this out.
You'd need to isntall VS Code insiders and the pre-release version of Python extension as well.

If the issue still persists, then this is a bug and we'll look into this, however I need a verifiaction that this doesn't exist anymore in our latest pre-release version.

Thanks

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
