### ISSUE TITLE
Kernel in VSC blank native notebooks does not use the current working directory

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1205]
Create a blank notebook (do not save)
Create a py file next to it
Import py file from notebook

In old editor, you can run the cell with the import.
In the VSC editor you cannot.

# TODO: Fix only if this works as expected in old notebooks.

**Comment by DonJayamanne** [comment]
Works for me, moving to validate.

**Comment by rchiodo** [comment]
Works me too. Validated
