### ISSUE TITLE
Test failures, "active interpreter is undefined

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#12059]
https://github.com/microsoft/vscode-jupyter/actions/runs/3484390471/jobs/5828897131
https://github.com/microsoft/vscode-jupyter/actions/runs/3484390471/jobs/5828898159
https://github.com/microsoft/vscode-jupyter/actions/runs/3484409232/jobs/5828938914
```
  1) 3rd Party Kernel Service API @kernelCore
       "before each" hook for "List kernel specs":
     AssertionError: Active Interpreter is undefined.0
      at Context.<anonymous> (src/test/client/api.vscode.test.ts:57:20)
```

https://github.com/microsoft/vscode-jupyter/actions/runs/3484390471/jobs/5828898006
```
1) Kernel Execution @kernelCore
       "before all" hook for "Execute cell using VSCode Kernel @mandatory":

      Error: Kernel Connection pointing to active interpreter not found.0
      + expected - actual


      at Timeout.<anonymous> (d:\a\vscode-jupyter\vscode-jupyter\src\test\common.ts:65:20)
      at listOnTimeout (node:internal/timers:[55](https://github.com/microsoft/vscode-jupyter/actions/runs/3484390471/jobs/5828898006#step:44:56)9:17)
      at processTimers (node:internal/timers:502:7)
```

**Comment by DonJayamanne** [comment]
@karrtikr we r still running into issues with python extension API
looks like the timeout retry didn't work

**Comment by karrtikr** [comment]
https://github.com/microsoft/vscode-python/issues/20239#issuecomment-1318560711

I suspect `/Users/donjayamanne/crap/.venvWidgets/bin/python` does not exist.

**Comment by DonJayamanne** [comment]
> I suspect /Users/donjayamanne/crap/.venvWidgets/bin/python does not exist.

Most definitely doesn't, again apologies for this Kartik.

**Comment by DonJayamanne** [comment]
Should be fixed
