### ISSUE TITLE
Webpack and dev builds shouldn't go into the same folder

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#12069]
It seems that all build artifacts go into `./out`, this makes it difficult to know the exact output of production builds

**Comment by DonJayamanne** [comment]
> which means we never have importScripts available in a file that is definitely going to run in a worker (extension.web.ts) for example.

@Tyriar I'm not sure i understand this, please could you explain this
Its my understanding that once we bundle everything then the files would exist, and if a import script needs a file, then I would have though the logical step would be to first build the files that get imported before building the extension.web.ts file.

I.e. build the dependenvies first, which is easily solved by setting up the order of build in gulp (as thats whats used today)

**Comment by Tyriar** [comment]
@DonJayamanne when the file is run it will exist, but you want TS to know about the target to avoid making mistakes that could be caught at compile time, make intellisense more useful, prevent declaring hacky globals, etc.

**Comment by DonJayamanne** [comment]
> TS to know about the target to avoid making mistakes that could be caught at compile time, make intellisense more useful, prevent declaring hacky globals, etc.

@Tyriar 
Sure, but i cannot see where TS needs to know about the target,
can you give an example of the problem that can come up with the current approach (i.e. a sample issue that we can run into, as thats what you seem to be hinting at)

From what I can tell all of the TS code imports existing TS files and nothing from any build folders, hence TS already knows about the files and TS server can find everything it needs.

**Comment by Tyriar** [comment]
> Sure, but i cannot see where TS needs to know about the target,

There's the `importScripts` example I mentioned, if the target isn't set it means you're missing global symbols that definitely exist.

The main issue here was that multiple builds go into the same folder, so they can clobber each other which could lead to weird behavior in dev or published artifacts.

**Comment by DonJayamanne** [comment]
>  so they can clobber each other which could lead to weird behavior in dev or published artifacts.


I'm still not sure about this problem, sure running dev builds could clobber the production builds.
But I think we can address this by merely documenting the fact taht all output goes into the `out` folder and that should address taht.

> which means we never have importScripts available in a file that is definitely going to run in a worker (extension.web.ts) for example.
> if the target isn't set it means you're missing global symbols that definitely exist.

Isn't this an issue with tsconfig and not about the output folders?

Feels like we're mixing up two issues here.
Probably time to setup a meeting to discuss this issue. as I'm clearly unable to understand the issue in its entirety

**Comment by Tyriar** [comment]
Yes they're 2 closely related problems. I don't think a meeting is needed, the setup is just very fragile is the problem and it would be much simpler if the output artifacts pointed at separate folders. Just recommending best practices here, feel free to close if you're not planning on doing it.

**Comment by DonJayamanne** [comment]
@Tyriar do you have any recommendations for extension on how they can get around the limitation of the fact that the output path is statically defined in package.json?

Also, I think we should add (document) to our extension samples repo so others can benefit from this.
Personally I do not see an easy way around this, apart from updating the package.json file locally during release builds

**Comment by Tyriar** [comment]
VS Code and xterm.js both build to intermediate directories and then bundle to the main one. You could for example build to `out-x` or `out-y` which then bundle to `out` depending. I can't remember whether you had 2 webpack configs or just the prod one, but it would be a step in a good direction to introduce a dev one if you don't have one to bring the dev build closer to the prod build.

Luna Paint solves the problem similar to VS Code's prod builds where it copies all prod artifacts to a separate folder (sibling to the repo folder), including the package.json and then makes changes it.

**Comment by DonJayamanne** [comment]
I trued to do something similar a few years ago, and had a problem with debugging, as webpack compiles TS to JS and then bundles them. The JS debugger wasnt (back then) able to map from webpack bundle to JS maps and then from JS maps to the TS source. I even reached out to @connor4312  back then and learnt it was a limitation.

Time to re-visit that, I'm assuming that it may have since been addressed.
Thanks @Tyriar

**Comment by connor4312** [comment]
It sounds like you need the [source-map-loader](https://webpack.js.org/loaders/source-map-loader/) (though in some cases js-debug can now be able to follow intermediate maps automatically, depending on build configuration)

**Comment by DonJayamanne** [comment]
@Tyriar  FYI - I will be looking into this, I do want to get this fixed as I no agree its a good practice
However theres some debt in this extension that would need to be addressed before

**Comment by DonJayamanne** [comment]
Done
