### ISSUE TITLE
Exclude *.d.ts files from extension bundle

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#12077]
ms-toolsai.jupyter-2022.11.1003232212

Hi, I noticed that this extension appears to include a number of `vscode.d.ts` files in its bundle:

<img width="523" alt="Screenshot 2022-11-17 at 2 32 42 PM" src="https://user-images.githubusercontent.com/12821956/202574243-74619da7-b4bb-4091-a405-183d711cec06.png">

These files are not needed in the extension bundle and should be excluded to reduce download / install size

**Comment by DonJayamanne** [comment]
Thats weird, I could have sworn I removed these at some point from the bundle.
