### ISSUE TITLE
Avoid calling Python API on Web

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#12072]
> pythonExtension.exports.jupyter.registerHooks(); is reading Python exports actually.

this path should not hit in web. we cannot use pyth9n extension api in web

_Originally posted by @DonJayamanne in https://github.com/microsoft/vscode-jupyter/issues/12064#issuecomment-1319177068_

**Comment by DonJayamanne** [comment]
I cannot repro this anymore, looks like @rebornix fixed this.
Will have another look, weird because we have tests for this (web tests).

**Comment by rebornix** [comment]
@DonJayamanne the error is gone as I check if it's undefined or not. But `getNewAPI` is called on Web.

**Comment by DonJayamanne** [comment]
Fixed
