### ISSUE TITLE
slow kernel listing

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12070]
Testing #11755

There is also a progress indicator for a couple seconds but it goes away and retrieving the full list takes quite a while.

![KernelLoading](https://user-images.githubusercontent.com/2019016/202552360-64cf9fdb-012f-4771-bda9-56add4cce700.gif)

[jupyterlogs.txt](https://github.com/microsoft/vscode-jupyter/files/10035321/jupyterlogs.txt)

**Comment by DonJayamanne** [comment]
@amunger Please test with the latest bits, should be ok.
