### ISSUE TITLE
There are tmp and temp folder in the repo root, both are not gitignored

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#12088]
![image](https://user-images.githubusercontent.com/2193314/202677967-b0a529ed-6461-46fe-87be-12ec9925e19f.png)

The folders themselves are not gitignored:

![image](https://user-images.githubusercontent.com/2193314/202678060-e193a59b-1d5c-4e99-9160-ad0df9302c2a.png)

**Comment by DonJayamanne** [comment]
Not true, these are gitignored.
I have files in both of them are i do not see any of them showing up in my git changes.

**Comment by Tyriar** [comment]
Files within the folders are gitignored, not the folders themselves:

![image](https://user-images.githubusercontent.com/2193314/235468873-3b8b39b9-3dc6-4568-b348-c96c89069314.png)

https://github.com/microsoft/vscode-jupyter/blob/main/.gitignore#L34-L35

Changing those to `temp/` and `tmp/` should always grey out the folders in explorer as expected.
