### ISSUE TITLE
Run Selection in Interactive is slow

### ISSUE THREAD

**Issue by r3m0t** [microsoft/vscode-jupyter#12091]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: Win 10
-   Python and/or Anaconda version: 3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local(default)

## Expected behaviour

"Run Selection in Interactive" should work straight away

## Actual behaviour

There's a delay due to starting a Python subprocess to split the code into blocks.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Add `time.sleep(3)` to the `sitecustomize.py` or `site.py` to simulate a corporate Antivirus ;-)

## Logs

None

**Comment by r3m0t** [comment]
I've opened a PR but I'm not even clear why the normalize step is needed. Ideally it would be done with a persistent subprocess or in the kernel using a comm or silent execution to speed it up further. Or removed entirlye. As well, there's a lot of unused Python files that could be cleaned up.

**Comment by Fred-Wu** [comment]
I just wanted to report a similar issue. 

<img width="631" alt="Screenshot 2022-11-18 at 11 20 20 pm" src="https://user-images.githubusercontent.com/4111978/202703785-c44de2b4-07b8-4448-97a7-bbce64506b04.png">


It took about 6 times longer to run a numpy code in the interactive even though the actual underlying is much faster.

**Comment by r3m0t** [comment]
Hi @Fred-Wu , that's the behaviour of `timeit`. Because the second one is faster, it was run 100 times to get a more accurate average time measurement.

**Comment by Fred-Wu** [comment]
I just wanted to report a similar issue. 

<img width="631" alt="Screenshot 2022-11-18 at 11 20 20 pm" src="https://user-images.githubusercontent.com/4111978/202703785-c44de2b4-07b8-4448-97a7-bbce64506b04.png">


It took about 6 times longer to run a numpy code in the interactive even though the actual underlying is much faster. 

> Hi @Fred-Wu , that's the behaviour of `timeit`. Because the second one is faster, it was run 100 times to get a more accurate average time measurement.

Ah, thanks. I missed that part as I thought they should have the same settings.

**Comment by amunger** [comment]
> I've opened a PR but I'm not even clear why the normalize step is needed.

It looks like we do some code formatting for selections but skip that step when we just run a cell, likely to help with selecting bits of code indented within a code block.

this line also makes me think it's just a carry-over from what the python extension is doing, so it's worth taking another look if it's necessary:
`Python: Failed to normalize code for execution in terminal`
