### ISSUE TITLE
empty Interactive Window kernel picker with mru

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12097]
with "notebook.kernelPicker.type": "mru"

I'm connected to a remote jupyter server and have a kernel from that server selected. Trying to pick another kernel for the Interactive Window - selecting `select another kernel` shows an empty list. Reloading vs code does not help

## Logs

[jupyter logs.txt](https://github.com/microsoft/vscode-jupyter/files/10043706/kernelloadinglog.txt)

**Comment by amunger** [comment]
edited - I don't need to connect to a remote to repro

**Comment by rebornix** [comment]
Related https://github.com/microsoft/vscode/issues/166724 . 

@DonJayamanne is it intentional that we are not contributing sources for IW?

**Comment by DonJayamanne** [comment]
Fixed in https://github.com/microsoft/vscode-jupyter/pull/12108
