### ISSUE TITLE
New notebook interface doesn't work with VIM extension

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#1210]
Might be a vscode notebook problem and not ours. Or the VIM extension might need a change. But the ESC key is both the bound key for jupyter exiting to command mode and for VIM exiting to command mode. I was unable to use ESC to exit out of edit mode of a cell and into jupyter command mode. If I was in edit mode in VIM ESC would exit edit mode, but then hitting ESC again would not drop me into jupyter command mode, I was stuck in jupyter edit mode.

**Comment by greazer** [comment]
Change happening in VIM extension.

**Comment by kjohnsen** [comment]
Most Vim things are working for me for editing with the new notebook interface, but some things don't. For example, 'u' to undo. When I do that it always says I'm already at the oldest change.
