### ISSUE TITLE
Whole font awesome npm package bundled in vsix

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#12101]
We are probably using font awesome for the webview features, but we may not want to bundle the whole package into vsix, for example, its `less`/`scss` source files

<img width="754" alt="image" src="https://user-images.githubusercontent.com/876920/202779004-881c18a3-e1c9-4a93-8b7c-118281f11ffb.png">

The whole package is 1.4M.

**Comment by DonJayamanne** [comment]
Deferring this until we've merged the PR that refactors the whole build process 
https://github.com/microsoft/vscode-jupyter/pull/12129
