### ISSUE TITLE
Raw cells are not preserved in VSC Native Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1211]
See microsoft/vscode-python#7952
Open existing nb and save it, raw cells get converted into code.

Reason is the cell language `raw` is not supported by VSC as its not a language.
We cannot really add a raw language either as other extensions could have a language named `raw`.
Possibly look into `jupyter-raw-cell` or similar.
Also look at microsoft/vscode-python#7952 (different type of cell = custom)

Currently raw cells with language `raw` are treated as `plaintext`.

**Comment by greazer** [comment]
Pretty sure this has been fixed.
