### ISSUE TITLE
There should be a scroll bar when the jupyter output is too long

### ISSUE THREAD

**Issue by xxc-zsz** [microsoft/vscode-jupyter#12122]
This is the current style of jupyter output in vscode when it is too long.
![image](https://user-images.githubusercontent.com/108051416/202945057-e79cb1e9-8fa0-4cb9-8a84-74cfc649c008.png)
This is the style of jupyter.
![image](https://user-images.githubusercontent.com/108051416/202945107-b00d2291-1776-4c16-b50c-705d7489abea.png)
vscode should also have a scrollbar like jupyter, which would be handy.

**Comment by Brainor** [comment]
A great idea I think, especially when the error message is super long like this
![image](https://user-images.githubusercontent.com/5477995/204101113-2bd271c0-24ae-4d64-ba78-336500b5a360.png)
And if you want to see the whole error message, all you can do is click the `in a text editor` link, and it doesn't render at all like below.
![image](https://user-images.githubusercontent.com/5477995/204101175-85805430-fcb1-4dce-924a-385222b9b12c.png)
A scroll bar would definitely improve readability.

**Comment by amunger** [comment]
there is an experimental feature in pre-release to use a scrollable area for outputs that can be enabled with `"notebook.experimental.outputScrolling": true`. It does not yet work for errors but we are working on that as well
