### ISSUE TITLE
Azure Storage files can't be opened with new native notebook editor

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#1212]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. With latest VSC Insiders and daily build of Python extension, open an ipynb in an Azure Storage fileshare via the Azure Storage VSC extension

## Actual behavior

1. Only the raw json is shown

## Expected behavior

1. ipynb should be loaded in the native editor view

## Developer Tools Console Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by DonJayamanne** [comment]
Moving to backlog as we had to make this work for our partner teams, hence this would have to continue working in native notebooks as well.
FYI - ideally we wouldn't have to do much work here, as this is an upstream VS Code issue.

**Comment by stuartleeks** [comment]
Verified on Windows that the `ipynb` file is loaded in the notebook editor
