### ISSUE TITLE
Unable to connect to a remote server 

### ISSUE THREAD

**Issue by jerrylin96** [microsoft/vscode-jupyter#12124]
Type: <b>Bug</b>

I am unable to tunnel into jupyter notebooks on vscode. I have to open a separate browser window.

Extension version: 2022.9.1303220346
VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.18.0-193.28.1.el8_2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id e2493ef2-63f6-4853-8d76-bd91aaff010d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: bridges2.psc.edu|
|OS|Linux x64 4.18.0-193.28.1.el8_2.x86_64|
|CPUs|AMD EPYC 7742 64-Core Processor (256 x 3289)|
|Memory (System)|251.59GB (105.83GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by DonJayamanne** [comment]
@jerrylin96 
I'm sorry, but the issue does't make sense to me, possibly missing some information.
Are you using remote SSH or the like?
Can you provide more information to replicate this at my end, that would probably help me understand what you are doing when you say `tunnel into jupyter` and `open separate browser`

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Comment by jerrylin96** [comment]
When I enter command+shift+P, I don't see "Jupyter: Specify local or remote Jupyter server for connections" in the command palette. 

I tried following the instructions here:

https://stackoverflow.com/questions/72121390/how-to-use-jupyterlab-in-visual-studio-code#:~:text=Once%20connected%2C%20code%20cells%20run,Ctrl%2BShift%2BP)

But the "Jupyter Server: local button" does not show up in the global Status bar. Either that or I do not have such a global status bar.

The question in the stackoverflow link is essentially identical to mine, but the answer does not work for me. Apologies for the delay in the response, I got busy with some other stuff and forgot about wanting to get this fixed.

**Comment by DonJayamanne** [comment]
> Jupyter: Specify local or remote Jupyter server for connections" in the command palette.

this command has been removed
Is you Want to connect to a remote Jupyter kernel then please go into the kernel picker and select ‘Existing Jupyter Server’ and enter the url there
The kernel picker has changed and more information can be found here https://code.visualstudio.com/docs/datascience/jupyter-kernel-management

**Comment by jerrylin96** [comment]
For tunnel into jupyter I essentially mean this:

1.) When logged into the HPC I will access a compute node with something like this:
`interact -n 32 -p node-shared -t 1:00:00`

The HPC will give me the name of the node, let's say it's r177. 

2.) On another terminal on my desktop I will tunnel into HPC with a port number, say 8765:
`ssh -L localhost:8765:localhost:8765 username@hpc.university.edu`

3.) On this same terminal, I will tunnel into the compute node using that port number and the name of the node:
`ssh -L localhost:8765:localhost:8765 r177`

4.) Back on the original HPC window in VScode I will tunnel into the notebook
`conda activate myenvironment`
`jupyter lab --port=8765 --no-browser --ip=0.0.0.0`

However, I can only open this notebook on a browser. As previously mentioned, the instructions for getting this to work on VScode don't work for me.

**Comment by jerrylin96** [comment]
<img width="548" alt="Screenshot 2023-03-19 at 4 46 13 PM" src="https://user-images.githubusercontent.com/22736732/226217368-2ffda79b-fa4d-4f21-8936-922ff46a8da2.png">
I now run into this issue when trying to tunnel onto VScode.

**Comment by DonJayamanne** [comment]
> However, there is a new one that's similar.
If I try to log into a cloud service that uses Github's login API to access jupyter notebooks, VScode won't accept the username and password I give it even though it's the same as my Github login. Would you happen to know why?

Sorry no idea,

**Comment by DonJayamanne** [comment]
> If I try to log into a cloud service that uses Github's login API to access jupyter notebooks, VScode won't accept th

Please could you file a seperate issue for this.

**Comment by jerrylin96** [comment]
So this issue was resolved until the latest update. Here's a screenshot of what the error looks like now:

<img width="990" alt="Screenshot 2023-03-31 at 4 23 19 PM" src="https://user-images.githubusercontent.com/22736732/229249213-2b2fa3c4-56e0-4628-8154-343774ae6252.png">

The error message says the Jupyter Server already exists, but I am unable to find it and connect to it. If I try entering the URL manually it won't let me connect because the "server already exists". Everything was working normally before I updated.

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by jerrylin96** [comment]
<img width="830" alt="Screenshot 2023-04-03 at 2 28 53 PM" src="https://user-images.githubusercontent.com/22736732/229631627-62648477-4b3c-43ee-92e1-4db44e18d5ba.png">

<img width="939" alt="Screenshot 2023-04-03 at 2 30 56 PM" src="https://user-images.githubusercontent.com/22736732/229631991-42aebe9d-a0a0-48eb-87c3-4ce454a570f4.png">

[14:26:04.056] > ready: 0c1d5d02bb69
[14:26:04.128] > Linux 4.18.0-193.28.1.el8_2.x86_64 #1 SMP Thu Oct 22 00:20:22 UTC 2020
[14:26:04.129] Platform: linux
[14:26:04.191] > /usr/psc/shells/bash
[14:26:04.193] Shell: bash
[14:26:04.194] Creating bash subshell inside "bash"
[14:26:04.260] > bash version:  4.4.19(1)-release
[14:26:04.319] > bash version:  4.4.19(1)-release
[14:26:04.398] > 0c1d5d02bb69: running
[14:26:04.416] > Acquiring lock on /jet/home/jlin96/.vscode-server/bin/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/vscode-remote-lock.jlin96.7f329fe6c66b0f86ae1574c2911b681ad5a45d63
[14:26:04.420] > Found old VS Code install e8a3071ea4344d9d48ef8a4df2c097372b0c5161, attempting to clean up
[14:26:04.550] > Install still has running processes, not deleting: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
> Found existing installation at /jet/home/jlin96/.vscode-server/bin/7f329fe6c66b0f86ae1574c2911b681ad5a45d63...
> Checking /jet/home/jlin96/.vscode-server/.7f329fe6c66b0f86ae1574c2911b681ad5a45d63.log and /jet/home/jlin96/.vscode-server/.7f329fe6c66b0f86ae1574c2911b681ad5a45d63.pid for a running server
[14:26:04.551] > Looking for server with pid: 555073
[14:26:04.682] > Found running server...
[14:26:04.683] >  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
[14:26:04.691] > * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
>  
[14:26:04.727] > Checking server status on port 42671 with wget
[14:26:04.739] > 0c1d5d02bb69: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==42671==
> osReleaseId==centos==
> arch==x86_64==
> tmpDir==/run/user/83956==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==1aa11111-aaa1-111a-1111-a1aaa111111a==
> 0c1d5d02bb69: end
[14:26:04.740] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==42671==
osReleaseId==centos==
arch==x86_64==
tmpDir==/run/user/83956==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==1aa11111-aaa1-111a-1111-a1aaa111111a==

[14:26:04.742] Remote server is listening on 42671
[14:26:04.742] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":42671},"osReleaseId":"centos","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/83956","platform":"linux","connectionToken":"1aa11111-aaa1-111a-1111-a1aaa111111a"},"installUnpackCode":""}
[14:26:04.744] Persisting server connection details to /Users/jerrylin/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f6a6647f-7f329fe6c66b0f86ae1574c2911b681ad5a45d63-0.98.0/data.json
[14:26:04.751] Starting forwarding server. localPort 59627 -> socksPort 59624 -> remotePort 42671
[14:26:04.751] Forwarding server listening on 59627
[14:26:04.752] Waiting for ssh tunnel to be ready
[14:26:04.758] [Forwarding server 59627] Got connection 0
[14:26:04.762] Tunneled 42671 to local port 59627
[14:26:04.763] Resolved "ssh-remote+bridges2.psc.edu" to "127.0.0.1:59627"
[14:26:04.784] ------




[14:26:04.792] [Forwarding server 59627] Got connection 1
[14:26:04.936] [Forwarding server 59627] Got connection 2
[14:26:14.727] [Forwarding server 59627] Got connection 3

**Comment by DonJayamanne** [comment]
@jerrylin96 
> I'm not sure what you mean by Jupyter output panel, but I clicked the output tab in one of the screenshots and copied and pasted what I see. 

* Go into the command palette, 
* Select the command `Jupyter: Show Output`
* You can see the output towards the bottom, see below screenshot
* You can then select everything there and copy that
![Screenshot 2023-04-04 at 09 04 32](https://user-images.githubusercontent.com/1948812/229645343-57cd8f19-5f9a-4df7-915a-9cad8b927674.png)

> This issue is very reproducible. The annoying thing is that the server I want to connect to shows up after it has been closed, but not during.

I think loading the kernels is slow, and when you go back to add the url, its still busy loading the kernels and when you attempt to add it, you get an error message about it already existing there

I will look into that issue,

* Please could you confirm that eventually, after a few seconds or a minute, you can see the kernels in the kernel picker for the remote server?

* Also, please could you install the latest version of VS Code insiders and the pre-release version of Jupyter extension, it might be slightly improved, though not completely.

**Comment by jerrylin96** [comment]
Hello, sometimes the kernel shows up after a minute or two and sometimes it never shows up at all. This issue only started happening *after* i switched to hte latest verseion of VS Code and the Jupyter extension (although I am not sure if I am on pre-release or not).

**Comment by DonJayamanne** [comment]
The pre-relase only works on VS Code insiders.

> This issue only started happening after I switched to the latest version of VS Code.

Sorry to hear that, please could you let me know what version works for you then
I'm assuming this used to work for you in an older version of VS Code and older version of the Jupyter extesnion (unlikely it was 1.76 and the previous version of Jupyter, as the behaviour was the same in those previous versions too).
I.e. its likely you had an older version of VS Code and Jupyter extesnion, 

Either way, i believe i understand the issue, and will look into this
