### ISSUE TITLE
TELEMETRY.csv cannot be generated on a Windows machine

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#12130]
In https://github.com/microsoft/vscode-jupyter/pull/12107 I found that the line endings are not normalized, so generating and committing the telemetry.csv results in a confusing CI lint failure.

**Comment by DonJayamanne** [comment]
I think the plan was to remove this CSV file.

**Comment by DonJayamanne** [comment]
Closing this as we no longer generate these files
