### ISSUE TITLE
Trusting a notebook in the Insiders Notebook Editor displays a change indicator

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode-jupyter#1214]
OS: macOS Catalina 10.15.5
Version: 1.48.0-insider - commit: e7920dce7bfd0b707ebfc0a5379c6edd2233e475
Extension version: 2020.8.94012-dev

![trusted_save](https://user-images.githubusercontent.com/51720070/87363777-bd163600-c526-11ea-86c3-c0f4d1e08eb8.gif)

Closing the notebook without saving it also displays a "do you want to save your changes" modal like in microsoft/vscode-jupyter#899.

**Comment by DonJayamanne** [comment]
Closing as this has been fixed.
