### ISSUE TITLE
Installing ipykernel from dialog fails

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#12143]
1. Open a notebook
2. Create a Dev Container using the `Jupyter Data Science Notebooks` template
3. Command palette --> `Python: Create Environment`
4. Create the environment using `conda`
5. Try running your cell
6. 🩸 Asks you to install ipykernel (it would be nice if that command knew the context and installed it for me)
7. 🐛 Click "Install" but the install fails and I get the error message in the output (see below) with the same "requires ipykernel" error dialog:

![image](https://user-images.githubusercontent.com/10833267/203435591-49c2c2d2-2a16-4878-9690-ef9ecd0de7ee.png)

Version: 1.74.0-insider (user setup)
Commit: fef85ea792f6627c83024d1df726ca729d8c9cb3
Date: 2022-11-21T05:22:37.848Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by DonJayamanne** [comment]
@minsa110 
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
