### ISSUE TITLE
Support non-raw (start Jupyter Server) kernels for VSC Native Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1215]
Today it only supports raw kernels, not tested with Jupyter (ie. spin up jupyter and connect to it using the jupyter API)

**Comment by DonJayamanne** [comment]
Closing in favour of #254

**Comment by DonJayamanne** [comment]
Oops, closed the wrong issue here

**Comment by DonJayamanne** [comment]
Most of it has been supported, just added some tests

**Comment by rchiodo** [comment]
Validated. Used 
```json
"jupyter.disableZMQSupport": true
``` 
to test
