### ISSUE TITLE
Rendering latex in VSC Markdown cells (native notebooks)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1216]
VS code doesn't support rendering LaTeX yet in notebooks. See this issue in VS code:
https://github.com/microsoft/vscode/issues/108551

**Comment by jaymegordo** [comment]
+1 proper latex support would be great to have in the new native notebooks, any eta? (ps native notebooks is amazing, thanks so much!!)

**Comment by DonJayamanne** [comment]
VS Code is addressing this, however we're going to have to validate that it renders the equations correctly (go through some of the issues we had & confirm they work in VS Code).

**Comment by DonJayamanne** [comment]
How to validate:
* Go through all issues and look for issues related to latex/markdown rendering
* Ensure they work in VS Code
* If they work, file an issue in VS Code and update this issue and move this issue back to the `upstream` swimlane

**Comment by gusbemacbe** [comment]
In reference to @larissaford's issue https://github.com/microsoft/vscode/issues/118262

**Comment by joyceerhl** [comment]
Upstream issue https://github.com/microsoft/vscode/issues/119536

**Comment by rchiodo** [comment]
@joyceerhl do we need to do anything here? Not sure why this moved back to triage.

**Comment by mjbvz** [comment]
Closing as this was shipped on the VS Code side

Please open new issues against VS Code for any future bugs / feature requests related to math equation rendering in notebooks
