### ISSUE TITLE
Updating to pre-release v2022.11.1003301027 loses previously installed Jupyter kernel

### ISSUE THREAD

**Issue by jb261** [microsoft/vscode-jupyter#12166]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I have a project that contains .ipynb files. When I open the project the Jupyter kernel field in the upper right corner automatically populates with the virtual environment for this project. This is using Jupyter extension v2022.9.1303220346.

Issue: I updated to Jupyter extension pre-release v2022.11.1003301027, and exited and restarted VS Code. When I open the same project described above, the Jupyter kernel field in upper right corner reads "Select Kernel". When I click on that, the only two options are:
- Install suggested extensions [python + jupyter]
- Browse marketplace for kernel extensions

### VS Code Version

1.73.1

### Jupyter Extension Version

v2022.11.1003301027

### Jupyter logs

```shell
warn 17:34:34.384: No interpreter with path d:\Documents\coding\project_1\proj_env\Scripts\python.exe found in Python API
```

### Coding Language and Runtime Version

Python v 3.9.12

### Language Extension Version (if applicable)

python extension v2022.18.2

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, 
when using the pre-release version of the extension you need to use the insider version of vscode as well.
we made a mistake and didn't update the versioning to make this clear.

again, to fix this you'll need to install the latest VS Code Insiders to use the latest pre-release version of the Jupyter extension.
Once done, please let me know how this goes.
Closing this issue as I'm certain that will address the issue.
