### ISSUE TITLE
Navigation of Interactive Window with VIM keybindings

### ISSUE THREAD

**Issue by huyiqun** [microsoft/vscode-jupyter#1217]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description
What is an easy way to navigate the Interactive Window? I tried to look for information on this, but could not find any, not sure if such functionality already exists.

My typical work flow would be writing some code in the editor, and do "run selection" to invoke the Interactive Window. Sometimes when the output is too long, or when I need to go back to previous cells, I have to switch to the mouse or the arrow keys. Is there a way to achieve these using the VIM keybindings?

(The jupyter notebook allows to choose a certain keybinding, though sometimes it is also hard to use, but better than nothing I guess.)

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by IanMatthewHuff** [comment]
Validated
