### ISSUE TITLE
Feature Request: Run block and move down in Python text file without selecting block manually

### ISSUE THREAD

**Issue by kylebarron** [microsoft/vscode-jupyter#12176]
(I have tried to search through issues and have not found any relevant results)

Here's the behavior I'm used to in [Atom's Hydrogen](https://github.com/nteract/hydrogen) (with the added [hydrogen-python extension](https://github.com/nikitakit/hydrogen-python)). The only thing I'm pressing is <kbd>Shift</kbd> + <kbd>Enter</kbd>

https://user-images.githubusercontent.com/15164633/204105543-7e305ae8-0de6-4a67-8a67-41aa5caa9aac.mov

1. <kbd>Shift</kbd> + <kbd>Enter</kbd> first starts the jupyter kernel
2. Each call to <kbd>Shift</kbd> + <kbd>Enter</kbd>:
    1. **Infers** a "block" of code to run in Jupyter, including the current line plus any additional lines that are indented more than the current line
    2. Sends that block of code to Jupyter
    3. Moves cursor down past the block that was run + past any additional whitespace to the next line of Python code

#### Key points

- This is **not** in a notebook with cells, but rather a normal Python text file. 
- I don't have to select the block manually to determine what to run. 
- Moving the cursor down automatically means that I can use a series of _only_ <kbd>Shift</kbd> + <kbd>Enter</kbd> to run through as much of my file as I'd like
- This is Python-specific, and so maybe is out of scope for this extension? Is there a Python-specific Jupyter add on somewhere?

**Comment by amunger** [comment]
We currently have the Interactive Window for running sections of python files against a running kernel, and the "cells" are marked with `# %%`. You can set `"jupyter.sendSelectionToInteractiveWindow": true` to make shift+enter work that way.

One big difference with your video is that the output is sent to a separate editor rather than inline, and we don't currently attempt to find implicit code blocks.

Could you give that a try and let us know what you think?

**Comment by kylebarron** [comment]
> we don't currently attempt to find implicit code blocks.

That is what this feature request is for 🙂.

> and the "cells" are marked with `# %%`

This is the big difference between Atom + Hydrogen and vscode + Jupyter IMO. My point is I _don't want to have to use cells_. For me as a Python library author and not a data scientist wanting the notebook experience, Hydrogen provides an amazing, seamless development experience because it's so easy to interactively debug a normal Python script (while still getting rich data output by relying on IPython).

Inferring code blocks automatically is a big factor in Hydrogen's expressiveness, because I don't have to manually select each region of text every time I run <kbd>shift</kbd> + <kbd>enter</kbd>.

> You can set "jupyter.sendSelectionToInteractiveWindow": true to make shift+enter work that way

I do have this set.

**Comment by amunger** [comment]
alright, thanks for the feedback - I just wanted to make sure you knew about the functionality since it was related to what you were describing

**Comment by kylebarron** [comment]
I got frustrated enough that I just wrote [my own extension](https://github.com/kylebarron/vscode-jupyter-python) (I also figured you likely wouldn't accept/implement python-specific functionality in this repo). I.e. here's a screencast of it in vscode

https://user-images.githubusercontent.com/15164633/204452477-95deccd0-db05-40b1-8f82-07d09c858fdc.mov

The code for that extension is super hacky and not tested, but helps me keep my sanity and usual dev workflow now that Atom is mostly dead.

**Comment by andycraig** [comment]
@kylebarron Wow, this is fantastic! I started using it today. Thank you very much for making it!

You may want to share this at this similar issue: https://github.com/microsoft/vscode-jupyter/issues/1471. I had just started working on something similar but I will be very happily using yours instead!

**Comment by kylebarron** [comment]
> @kylebarron Wow, this is fantastic! I started using it today. Thank you very much for making it!

Welcome! With the caveat that it was a quick hack and I can't promise there are no bugs and that I'll spend a lot of time maintaining it going forward 😄 

> You may want to share this at this similar issue: #1471

Ah I assumed there _had_ to be an existing issue for this, but couldn't find one after a few minutes of searching.

**Comment by kylebarron** [comment]
I figure I'll close this in favor of #1471
