### ISSUE TITLE
Kernel issues (restart crashing, kernel won't connect)

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#12187]
From [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details):

> It keeps crashing : Kernell restart, kernell connecting but last for ever (hours). I can't figure out how to solve this issue no matter which python environment I am working with. Please reach out to me if you can help out!

**Comment by DonJayamanne** [comment]
I'm sorry you are running into this issue, 
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
