### ISSUE TITLE
The interactive window should look at the sheband to opens the script with the right python version

### ISSUE THREAD

**Issue by WiliTest** [microsoft/vscode-jupyter#12186]
Currently all scripts are launched using the default python version.

It would be great when using the context menu "run the file in the interactive window" to launch the script with the right python version when a shebang is use. 

Eg. a script containing the shebang `#!python3.9` should not be launch with the default python version (3.6 in my case) but 3.9.

**Comment by amunger** [comment]
closing since this hasn't generated enough interest to warrant adding the extra complexity
