### ISSUE TITLE
Broken Interactive window test ' Error stack traces have correct line hrefs with mix of cell sources'

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12189]
https://github.com/microsoft/vscode-jupyter/actions/runs/3565779955/jobs/5991373158
https://github.com/microsoft/vscode-jupyter/actions/runs/3568555079

**Comment by DonJayamanne** [comment]
@amunger looks like the tests are failing consistently, hence looks more like a break in the code., 
You might want to look into this sooner than later, hence assigned to nov and added the bug label
Please re-adjust as you see fit

**Comment by amunger** [comment]
same cause as https://github.com/microsoft/vscode-jupyter/issues/12190
