### ISSUE TITLE
make it easier to use: confusion about the role of the "restart" button 

### ISSUE THREAD

**Issue by WiliTest** [microsoft/vscode-jupyter#12185]
I launched my script using the context menu "run the file in the interactive window". It took me a while to understand that the "restart" button doesn't restart the debugging but only the "interactive window" (but the stop button stop the debug of the script...), and thus that I need to use the context menu "run the file in the interactive window" to restart the debugging. 

Thanks for this awesome extension!

**Comment by roblourens** [comment]
Any suggestions for what would make these buttons more clear?

"Restart" restarts the kernel. "stop" interrupts the kernel, and if it is debugging, that also means stopping debugging.

I'm a little confused since "Run the current file in the interactive window" does not do debugging, as I understand it.

**Comment by WiliTest** [comment]
Well, I'm even more confused. I realize that I'm confusing, "debug" with "run the script in the Jupiter" (which for instance output the errors, I thought it was the process of debugging, since I don't see in Jupiter a way to jump pause like the  debugger from the left does.
![image](https://user-images.githubusercontent.com/24194840/206186014-2a82d5c3-1389-41cb-9d0b-46be0ed96b45.png)

![image](https://user-images.githubusercontent.com/24194840/206185890-e9e7a58d-7898-4afe-a4f3-39e87fa529e2.png)

I guess this is the Jupiter debugging tool, right? 
![image](https://user-images.githubusercontent.com/24194840/206186294-ca20687e-0c0b-48a1-98f5-e41a2f0c3049.png)

I know it's not just about Jupiter, but I'm totally confuse about all these debugging tools, like the other one on the right: 
![Code_2022-12-07_14-04-45](https://user-images.githubusercontent.com/24194840/206187201-087a1d77-f9ab-4623-a99e-26ecb01962ac.png)

What's the difference between the one on the left, and with the right, and with Jupiter? (Which by the way display the variables with the debugger/terminal "1" on the left).

I know I'm not answering your question (I have no idea how you could make it clearer). I'm aware that my answer won't help. But I just wanted to let you know my confusion about the whole thing (the Jupiter buttons just add another level of complexity).

**Comment by roblourens** [comment]
I'm a little confused about your confusion 🙂 

In the last image the `1` starts debugging using a configuration from your launch.json. The `2` is contributed by an extension and debugs your open file, without having to write a json configuration.

Then in Jupyter, you can just run code without "debugging" it. You will notice "Run Cell" vs "Debug Cell" in a .py file with `# %% ` cell markers, for example

**Comment by WiliTest** [comment]
Thanks a lot for taking the time to explain this, I feel less confused now!

**Comment by roblourens** [comment]
Great, I will close this, but if you have any suggestions for how to make this less confusing, please let me know
