### ISSUE TITLE
Variable explorer for Notebooks (Interactive window)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1218]
What ever we do might impact interactive window as well.
This is the custom webview displayed with variable explorer

**Comment by IanMatthewHuff** [comment]
Hmm, I don't believe that this is currently planned. De-assigned and moving back to backlog.

**Comment by joyceerhl** [comment]
The native interactive window inherits the variable explorer for native notebooks.
