### ISSUE TITLE
Broken interactive window test 'Raising an exception from within a function has a stack trace'

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12190]
https://github.com/microsoft/vscode-jupyter/actions/runs/3565779955/jobs/5991373158
https://github.com/microsoft/vscode-jupyter/actions/runs/3568555079

**Comment by DonJayamanne** [comment]
@amunger looks like the tests are failing consistently, hence looks more like a break in the code., 
You might want to look into this sooner than later, hence assigned to nov and added the bug label
Please re-adjust as you see fit

**Comment by amunger** [comment]
I'll take a look, but it actually doesn't seem to have failed on main for a few weeks
![image](https://user-images.githubusercontent.com/2019016/204388943-1df0e683-de94-4c1f-b08c-4ae71b668eab.png)

**Comment by amunger** [comment]
never mind, looks like the latest ipykernel version breaks our regex again

**Comment by amunger** [comment]
verification steps:
create and save a python file
create a python environment and install ipykernel  6.18.1 (`pip install ipykernel==6.18.1)
run the file in the interactive window with something that will throw e.g. `print(x)`
ensure the stacktrace has links back to the errored line in the file
