### ISSUE TITLE
the same conda environment listed 3 times in kernel picker

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12207]
Testing #11963

after creating a conda env in the workspace and reloading vscode a few times, and **disabling** the mru kernel picker, I see the same environment listed multiple times:
![image](https://user-images.githubusercontent.com/2019016/204657538-115526a1-715b-4eae-b9a2-6050463fcca5.png)

[jupyterlogs.txt](https://github.com/microsoft/vscode-jupyter/files/10117674/jupyterlogs.txt)

**Comment by DonJayamanne** [comment]
@amunger i think its only dispalyed 2 times, not three. 
if you look at the screen shot, the second item is `2`.
Please confirm

**Comment by amunger** [comment]
1st, 3rd and 4th are the same, the third is just a relative path where the others are fully qualified

**Comment by DonJayamanne** [comment]
@amunger please could you:
* Replicate this again
* Create the conda env again and ensure you capture the logs
* When you get the duplicates as well i need the logs (if you happen to reload vscode)

The logs you have provided aren't sufficient as it doesnlt contain the logs from when you created the conda env.
I believe you may have reloaded vscode in between (ie reloaded after creating the env)

**Comment by amunger** [comment]
note - the MRU kernel picker was used to create the environment and does not show duplicates. Switching back to the old kernel picker will show the duplicates. (C:\SRC\TEST\6\.CONDA\PYTHON.EXE in this repro)
[environment creation jupyterlogs.txt](https://github.com/microsoft/vscode-jupyter/files/10125741/jupyterlogs.txt)
[kernel picker duplicates jupyterlogs2.txt](https://github.com/microsoft/vscode-jupyter/files/10125744/jupyterlogs2.txt)
[environment creation pythonLogs.txt](https://github.com/microsoft/vscode-jupyter/files/10125746/pythonLogs.txt)

**Comment by DonJayamanne** [comment]
> Switching back to the old kernel picker will show the duplicates. (C:\SRC\TEST\6.CONDA\PYTHON.EXE in this repro)
[environment creation jupyterlogs.txt](https://github.com/microsoft/vscode-jupyter/files/10125741/jupyterlogs.txt)


how did you create the conda env, did you do this manually via the CLI or via the python extension commands

**Comment by amunger** [comment]
> how did you create the conda env
with the MRU kernel picker: Select another kernel... -> Python Environments -> Create python environment -> conda

**Comment by DonJayamanne** [comment]
Found the problem, sometimes the Uri (path to the executable) is upper cased and in other cases its not upper cased.
Here are two different values returned by the Python extension for the same request

```
debug 09:31:08.170: Get Active Interpreter, Class name = x, completed in 56ms, has a truthy return value, Arg 1: "/c:/src/test/6", Return Value: {"id":"C:\\SRC\\TEST\\6\\.CONDA\\PYTHON.EXE","sysPrefix":"c:\\src\\test\\6\\.conda","envPath":{"$mid":1,"path":"/c:/src/test/6/.conda","scheme":"file"},"displayPath":{"$mid":1,"path":"/c:/src/test/6/.conda","scheme":"file"},"envName":"","uri":{"$mid":1,"fsPath":"c:\\src\\test\\6\\.conda\\python.exe","_sep":1,"path":"/c:/src/test/6/.conda/python.exe","scheme":"file"},"displayName":"","envType":"Conda","version":{"major":3,"minor":8,"patch":15,"raw":"3.8.15 (default, Nov 24 2022, 14:38:14) [MSC v.1916 64 bit (AMD64)]"}}


debug 09:30:57.943: Get Active Interpreter, Class name = x, completed in 39ms, has a truthy return value, Arg 1: undefined, Return Value: {"id":"C:\\SRC\\TEST\\6\\.CONDA\\PYTHON.EXE","sysPrefix":"c:\\src\\test\\6\\.conda","envPath":{"$mid":1,"path":"/c:/SRC/TEST/6/.CONDA","scheme":"file"},"displayPath":{"$mid":1,"path":"/c:/SRC/TEST/6/.CONDA","scheme":"file"},"envName":"","uri":{"$mid":1,"fsPath":"c:\\SRC\\TEST\\6\\.CONDA\\python.exe","_sep":1,"path":"/c:/SRC/TEST/6/.CONDA/python.exe","scheme":"file"},"displayName":"","envType":"Conda","version":{"major":3,"minor":8,"patch":15,"raw":"3.8.15 (default, Nov 24 2022, 14:38:14) [MSC v.1916 64 bit (AMD64)]"}}
```

**Comment by DonJayamanne** [comment]
@amunger this should be fixed in the latest pre-release version of Jupyter and Python extensxions.
Please re-open if the issue persists.
