### ISSUE TITLE
cell stuck in running for non-existent remote connection

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12203]
Testing #11963

enable mru kernel selection
create a jupyter server outside of vscode
connect to a kernel on the remote server and run a cell
kill the server and reload vscode
run a cell, this will open the kernel selection dialog
select the existing connection to the remote server

:bug: cell is in running state forever

**Comment by DonJayamanne** [comment]
this is a regression, we had this exact same issue reported in the past.

**Comment by amunger** [comment]
similar thing happens if you delete a venv within the workspace, I can still select the venv in the kernel picker and end up with a cell stuck in the running state

**Comment by DonJayamanne** [comment]
> the venv in the kernel picker and end up with a cell stuck in the running state



that's probably been around for a while.
though the other is a regression
