### ISSUE TITLE
bad error when trying to use a kernel from a dead server

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12204]
Testing #11963

create a jupyter server outside of vscode
use the mru kernel picker to connect to that server
kill the server, reload vscode
open the mru kernel picker, select another kernel, connect to a server, select the dead server, pick a kernel
run a cell

Expected: connection error
Actual:
```
Failed to start the Kernel. 
Kernel Python 3 (ipykernel) is not usable. Check the Jupyter output tab for more information. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
```

**Comment by DonJayamanne** [comment]
@amunger I'm trying what you have suggested but unable to replicate the issue.
Perhaps the following might need more clarification
> open the mru kernel picker, select another kernel, connect to a server, select the dead server, pick a kernel

Please confirm these are the steps
* Open the mru kernel picker
* Select `Select Another Kernel`
* Select `Existing Jupyter Server` => Is this correct
After the previous step, please could you share the screenshot of the issue.

Also, logs would be very useful here, please do share debug logs.

**Comment by amunger** [comment]
yes, those steps are correct.

[jupyterlogs.txt](https://github.com/microsoft/vscode-jupyter/files/10117415/jupyterlogs.txt)

![image](https://user-images.githubusercontent.com/2019016/204651300-8b12096e-8bc3-45ba-b01d-6ca135507128.png)

![deadServer](https://user-images.githubusercontent.com/2019016/204651472-5e30801b-f07c-4f5e-8e48-367e1823adcd.gif)
