### ISSUE TITLE
Notebook Editor: Toggle Line Command does nothing

### ISSUE THREAD

**Issue by rsebbe** [microsoft/vscode-jupyter#1220]
Issue Type: <b>Bug</b>

When editing python source of a native notebook (.ipynb) in the Notebook Editor (VSCode / Python extension),  the command 'Toggle Line Command' does not work. It is enabled, but does nothing when clicked. (it works fine with other file types)

Steps to reproduce:
- put the cursor one some source line
- click 'Toggle Line Comment' in Edit menu
- it does nothing. 

Extension version: 2020.1.56889-dev
VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:55:38.353Z)
OS version: Darwin x64 19.2.0
Remote OS version: Linux x64 4.15.0-62-generic

**Comment by DavidKutu** [comment]
This is now supported in the new Native Notebooks, to try them out please use VS Code Insiders.
More info here: https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/
