### ISSUE TITLE
No progress bar in kernel picker

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#12212]
Testing #11963

When the kernel picker button shows "Discovering Kernels", I'd assumed that the kernel quick pick would show a progress bar, but I don't see it.

**Comment by rebornix** [comment]
There is probably a delay of showing the progress but if it's long enough, you should be able to see progress bar running as shown in below video.

https://user-images.githubusercontent.com/876920/213328008-70e6732f-0ec5-47e3-be9b-d08cce88adfa.mov

Feel free to reopen issue if it's not what you are seeing.
