### ISSUE TITLE
Can't use the formatter in the ipynb cell 

### ISSUE THREAD

**Issue by AlafateABULIMITI** [microsoft/vscode-jupyter#1221]
I found that I can't use the formatter in the ipynb cell, like black and autopep8.

**Comment by EnriqueSolarte** [comment]
+1 Waiting for the feature

**Comment by gcsun** [comment]
+1

**Comment by phantomroom** [comment]
+1

**Comment by skorphil** [comment]
> This should be working in the VS code insiders version already. We use a newer VS code editor to host notebooks and that should support formatting of cells.

I'm using insiders version of notebooks editor. And it seems there is no autoformatting. Is there a way to turn it on?

**Comment by fishiu** [comment]
+1

**Comment by rchiodo** [comment]
Format cell is the way to format cells of a notebook. Format notebook will format every cell. There doesn't seem to be a way to set this on save that I can find. Format on save would be VS code's responsibility though.

**Comment by rchiodo** [comment]
I entered this issue for format on save:
https://github.com/microsoft/vscode/issues/120432

**Comment by hanmala123** [comment]
+1
It's a great feature

**Comment by like-a-freedom** [comment]
+1

**Comment by AlafateABULIMITI** [comment]
Hi all, I think we could close this, since it is possible to use formatter inside the cells now with the newest version of vscode, thank you for all the efforts you made!

**Comment by nickeubank** [comment]
@AlafateABULIMITI Would you mind pointing to how we can get this to work?

**Comment by timoklimmer** [comment]
@nickeubank It's Shift+Alt+F. You should also find it in the list of commands which you get when you press Ctrl+Shift+P. Note that you need a formatter installed. If none is installed yet, VS.Code will show a notification on the bottom left which asks you to install a formatter. (Personally, I am fairly happy with black.)

**Comment by nickeubank** [comment]
Thanks @timoklimmer ! BTW, is there any talk of implementing format-on-run (like [nb_black](https://github.com/dnanhkhoa/nb_black))? And if not, would vscode-jupyter be the place to propose that, or vscode? Still a little bit fuzzy on the lines between the two groups.

**Comment by timoklimmer** [comment]
@nickeubank I don't know if there is any nb_black related work or plans because I am not part of the team that develops the Jupyter extension. Have you checked the issues list already? @rchiodo fyi

**Comment by rchiodo** [comment]
Format on run could be implemented either in VS code core or the Jupyter Extension. Either one could be the place to enter the suggestion.
