### ISSUE TITLE
Showing local kernel specs in a remote window

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#12231]
Testing #11963

<img width="613" alt="image" src="https://user-images.githubusercontent.com/323878/204906268-eb44e8ec-4b8b-42cf-a3dc-1f9c9cd4aef0.png">

This is an SSH window, but the Julia path (and probably all of these?) are from my local machine. These are from us and not the Julia extension, right?

**Comment by DonJayamanne** [comment]
@roblourens what happens when you hit the refresh button?

> This is an SSH window, but the Julia path

is this SSH to your same machine? or ssh to some other remote machine?
if its the same machine, then its correct.

> These are from us and not the Julia extension, right?

yes

**Comment by roblourens** [comment]
Yes, SSH to a different machine.

Reload button- no change

**Comment by DonJayamanne** [comment]
> Yes, SSH to a different machine.

do you have these kernels on the other machine?
can you try refreshing and let me know what happens

**Comment by roblourens** [comment]
I said I clicked the reload button and nothing changed. Is that what you mean by "refreshing"?

No, the kernels are not on the other machine. Those are paths on my local mac, not the remote linux machine.

**Comment by DonJayamanne** [comment]
> I said I clicked the reload button and nothing changed. Is that what you mean by "refreshing"?

I mean clicking the refresh button on the quick pick (top right hand corner of screenshot)

**Comment by DonJayamanne** [comment]
Never mind, I think i know whats going on:
* VS Code mement is shared across machines
* We cache kernel specs for your local machine
* When you go to another machine, the same memento is provided by vscode (but probably by design, and I didn't think this would be the case)

can fix this later

**Comment by DonJayamanne** [comment]
Fixed,
