### ISSUE TITLE
"Create Environment" has no back button

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#12238]
Testing #11963

- Open the kernel picker
- "python environments"
- "Create Environment"
- There is no back button anymore

I think we are just calling a Python extension command here, so maybe we can pass in a command ID for its back button.

**Comment by DonJayamanne** [comment]
Identified and logged here https://github.com/microsoft/vscode-python/issues/20274

**Comment by DonJayamanne** [comment]
Fixed

**Comment by DonJayamanne** [comment]
this has been tested via a test plan, hence marking as verified
