### ISSUE TITLE
Refresh button not updating for deleted kernels

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#12232]
Testing #11963

If the kernel picker can update while it's open, is the refresh button still needed?

**Comment by DonJayamanne** [comment]
Yes, e.g if you delete/create a conda or virtual env outside vscode, then it might not necessarily appear here.
after all we rely on file monitoring and thats not guaranteed to work 100% of the time

At that point refresh is the only way to get things updated.

**Comment by roblourens** [comment]
When I delete a venv via the terminal, then click refresh, it's actually still there

**Comment by DonJayamanne** [comment]
> I close and reopen the kernel picker, then it appears

@roblourens didn't you mean `then it disappears`

**Comment by roblourens** [comment]
I guess so, I don't quite remember what I was seeing sorry
