### ISSUE TITLE
Pyolite is always the selected kernel for new notebooks

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#12236]
Testing #11963

- Install Pyolite
- Use some other kernels in your notebooks
- Run "Create new jupyter notebook"
- Pyolite is the autoselected kernel even though I've never actually used it

**Comment by DonJayamanne** [comment]
This is a regression.
In new notebooks Jupyter extension is no longer providing a preferred kernel.

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode-jupyter/commit/b2ebc8279e28aed76d7359ac39613c8c4c243b0e

**Comment by DonJayamanne** [comment]
to be verified

**Comment by roblourens** [comment]
We discussed this in the notebook sync. Verified as-is, but there is still some possible randomness here. I think the decision was for it to only autoselect kernels that are in the mru.
