### ISSUE TITLE
"Create Environment"- pressing esc shows the kernel picker again

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#12240]
Testing #11963

- Open kernel picker
- "Create Environment"
- Press escape

The kernel source picker is shown again. Pressing esc should hide the current picker and not show another one.

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode-python/issues/20274
Also mentioned here https://github.com/microsoft/vscode-jupyter/issues/11904

**Comment by roblourens** [comment]
I don't think this is related to the back button. esc cancels the whole flow, it doesn't go back

**Comment by DonJayamanne** [comment]
we don't know what happened?
the create environment quick pick is from python, so we don't know whether you hit escacpe or the environmetn was not created or user hit back button.

**Comment by DonJayamanne** [comment]
we need Python extension to tell us exactly what happened so we can make an informed decision on the workfow here

**Comment by DonJayamanne** [comment]
This had a test plan item and was verified

**Comment by DonJayamanne** [comment]
@rebornix this is not working again, I noticed this some time ago, but forgot to file an issue or look into this.
Can confirm there's definitely a bug here now as this flow is not right, i can never escape the kernel picker, it always goes back to the `Kernel Source Picker`

**Comment by DonJayamanne** [comment]
Fixed
