### ISSUE TITLE
Created environment does not appear in picker

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#12244]
Testing #11963

- Go through the "Create Environment" flow
- The venv was created, but not selected, and doesn't appear in the kernel picker

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/323878/204921066-a4c6c518-9b59-4aee-b513-41cbdb905aac.png">

It does appear in the python interpreter picker, though
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/323878/204921160-21a3200b-cd2c-43b1-8862-c6eccd79612f.png">

**Comment by DonJayamanne** [comment]
@roblourens please could you replicate this issue and provide the verbose logs from the Jupyter extension.

**Comment by roblourens** [comment]
Sorry, I should have grabbed the logs. I can't repro it right now
