### ISSUE TITLE
Controller gets disposed incorrectly (due to incorrect notification of removal of python env)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12250]
https://github.com/microsoft/vscode-python/issues/20292

**Comment by DonJayamanne** [comment]
Should now be fixed

**Comment by rzhao271** [comment]
@DonJayamanne what are some verification steps for this issue?

**Comment by DonJayamanne** [comment]
Verifying this manually is very difficult (almost impossible) as this is a flaky bug in Python extension.
The fact that users haven't reported this recently is an indication that this is now working as expected
