### ISSUE TITLE
Clarify `Working with Python` setup

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-jupyter#12258]
In the README.md section `Working with Python` there's this cryptic step:

> Since not working with Python, make sure to have a Jupyter kernelspec that corresponds to the language you would like to use installed on your machine.

What does this mean? Let's clarify this from the perspective of someone who doesn't even know what a kernelspec is.

**Comment by DonJayamanne** [comment]
we might want to include link to Jupyter docs instead
