### ISSUE TITLE
When vscode jupyter uses the rich package, the</>symbol appears on the left

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode-jupyter#12254]
Here is the example:

```
import logging
import os
import sys
from rich.logging import RichHandler
def set_logging():
    FORMAT = "Func/Mod:%(funcName)s  %(message)s"
    logging.basicConfig(level=logging.INFO, format=FORMAT, datefmt="[%X]", handlers=[RichHandler(markup=True, show_path=False)])
    if sys.platform.lower() == "win32": 
        os.system('color')
    log = logging.getLogger(__name__)
    #log = logging.getLogger("mylog")
    log.setLevel(logging.INFO)
    return log
if __name__=="__main__":
    log=set_logging()
    log.info("This is a test")
    log.info("This is a test")
    log.info("This is a test")
```

On vscode:

![image](https://user-images.githubusercontent.com/100815370/204958504-e52c2cae-0b61-48df-864d-a012c56ed5d8.png)

We can clearly see `</>` on the left side of the output box.

I tried the same codes on jupyter instead of vscode:

![image](https://user-images.githubusercontent.com/100815370/204958642-11ab708d-ed07-4c69-8133-83d9fb1ea17f.png)

I think this is a problem with the format judgment in vscode-jupyter. I hope it can be solved.

**Comment by roblourens** [comment]
This is a button that appears on each output. It lets you change the renderer type for that output

**Comment by FakeTrader** [comment]
Rendering as HTML displays redundant whitespace, in VSCode (ipython) and (PyCharm jupyter).

Also, the width is not dectected properly.

Result:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/9635792/212520277-f44c12b2-a62e-418f-9fd9-2952326a8938.png">

Expected:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/9635792/212520362-31eccbfb-8bdd-45f1-b937-ec34b92450fb.png">
