### ISSUE TITLE
Python Interactive window does not respect vscode editor keyboard shortcuts

### ISSUE THREAD

**Issue by vapoto** [microsoft/vscode-jupyter#1225]
Issue Type: <b>Bug</b>

In the Python Interactive window input box, globally defined keyboard shortcuts do not work. For example, redefining `cursorHome` or `selectNextSuggestion` in Keyboard Shortcuts does not change the shortcut in the Python Interactive window, even when removing the 'when' expression.

# Example:
## Steps to reproduce

1. Redefine `cursorHome` keybinding to `Ctrl+A`
2. Remove 'when' expression and conflicting shortcuts
3. Open Python file with cells
4. Open Python Interactive window
5. Type something in the Python Interactive window
6. Hit `Ctrl+A`

## Observed behaviour
All text is selected

## Expected behaviour
Cursor moves to beginning of line

# System information
Extension version: 2019.11.50794
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:40.719Z)
OS version: Linux x64 5.0.0-37-generic snap

**Comment by IanMatthewHuff** [comment]
Validated. Looks good for me now along with the VIM shortcuts.
