### ISSUE TITLE
Create sample extension that contributes remote jupyter servers (as a form of documentation)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12268]
We have the ability for extensions to contribute remote jupyter servers to the Jupyter extension
we shoudl create a sample and document how this can be done

This way if someone wishes to connect to Jupyter running on some special remote environment they can contribute this via the above API (just as Azure AML & others)

**Comment by pangav2001** [comment]
FYI, it seems like the [ms-ai-tools-test](https://github.com/microsoft/vscode-jupyter/tree/main/src/test/datascience/extensionapi/exampleextension/ms-ai-tools-test) example extension might be relevant to this. I came across it a couple of months ago when looking to add the functionality mentioned in #11518, but I no longer had a Kerberos environment to test it in, so I never got to it.

Hope this helps and, in any case, thanks for opening this issue, @DonJayamanne!

**Comment by DonJayamanne** [comment]
https://github.com/microsoft/vscode-extension-samples/pull/913
https://github.com/microsoft/vscode-jupyter-hub
