### ISSUE TITLE
Soimething wrong with jupyter notebook cell support for `input()` function

### ISSUE THREAD

**Issue by liganega** [microsoft/vscode-jupyter#12269]
When `input()` function is run with a string, that string should be shown in order to prompt the user to type in something. However, nothing shows up. 
And sometimes, but not always, even the results of `print()` function is displayed only afterwords.

Here is an example code:

```python
print("Please choose a number between 0 and 100.")
num = int(input("A number please: "))
print("The seletected number:", num)
```

- image captured while running:

![화면 캡처 2022-07-03 152051](https://user-images.githubusercontent.com/2748863/177027823-4d626f42-db46-4bda-97c0-142a904bca15.png)

The above image can be got after interruption of the cell running.

- image captures after

![화면 캡처 2022-07-03 152143](https://user-images.githubusercontent.com/2748863/177027837-3d3cc956-39d5-4069-ae65-517e97e86cb6.png)

**Comment by amunger** [comment]
There should be an input box at the top of the window (often missed since you may not be looking there)

![image](https://user-images.githubusercontent.com/2019016/205181962-8e609a70-c84a-4a3e-b491-3ebf9a16b81e.png)

**Comment by amunger** [comment]
closing since this issue is fairly old, please let us know if this isn't what you're seeing.
