### ISSUE TITLE
Reduce toolbar options when debugging

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-jupyter#12264]
I'm not a heavy data science user, but ran into this when verifying https://github.com/microsoft/vscode-jupyter/issues/11986

<img width="814" alt="image" src="https://user-images.githubusercontent.com/2230985/205136362-f3ff5dfb-29ef-49be-9792-36ad76f4e542.png">

This was the toolbar when having two columns and no sidebar open on my MacBook screen. In this case, I couldn't see the Variables button, and wouldn't have known it was there if I didn't see it.

Do users do things like adding new cells or clearing output while debugging? If not, should those options be hidden in debug mode to allow more space for debug actions?

**Comment by roblourens** [comment]
I don't think we should do anything different because the user is debugging. I think it's annoying how much space some of these buttons take up though. But @rebornix aren't the labels supposed to be disappearing when the toolbar is narrow? Or no?
