### ISSUE TITLE
Jupyter Split Cell and Select Multiple Cells command

### ISSUE THREAD

**Issue by Bill-Fujimoto** [microsoft/vscode-jupyter#1227]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description
1. The Jupyter split cell command (ctrl + shift + minus) does not work, it merely zooms out the display.  Would be great if this command were added.

2. The Jupyter select multiple cells (shift + down/up) as well as cell merge (shift + m) commands do not work.  Again, would be great if these were added.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by amm98d** [comment]
+1

**Comment by ThomasBourgeois** [comment]
+1

**Comment by mjbeyeler** [comment]
+1

**Comment by kid3night** [comment]
+1

**Comment by srikanthnadella** [comment]
+1

**Comment by fcarazo** [comment]
+1

**Comment by techcheese** [comment]
+1

**Comment by darioromero** [comment]
+1. Indeed, it's a very handy command needed in VS Code for the notebook.

**Comment by harshit-bajpai** [comment]
+1 Very handy and required for productivity.

**Comment by Gamebred94** [comment]
+1

**Comment by DonJayamanne** [comment]
* Split cell has been added
* Multi select has been added
* Merge cells has not been added.

**Comment by DonJayamanne** [comment]
@claudiaregio I know you have worked with Miguel on this, please could you ping him or check with VS Code about support for merging cells similar to VS Code.

**Comment by DonJayamanne** [comment]
Upstream https://github.com/microsoft/vscode/issues/119004

**Comment by adxrgh** [comment]
please

**Comment by autoscraper** [comment]
+1

**Comment by mattlim96** [comment]
+1

**Comment by claudiaregio** [comment]
Split cell and multiselect available in VS Code Insiders today.

**Comment by joyceerhl** [comment]
Validated. In VS Code Insiders split cell is available with the Ctrl+Shift+- shortcut:

![image](https://user-images.githubusercontent.com/30305945/118430270-9665e600-b688-11eb-9aeb-677edd80b811.png)

Multiselect is available using Shift+Up/Down Arrow https://code.visualstudio.com/updates/v1_55#_multiple-cell-selection

Merge cell is tracked here: https://github.com/microsoft/vscode/issues/119004
