### ISSUE TITLE
Outputs from cells suddenly only displaying text

### ISSUE THREAD

**Issue by juliazhang95** [microsoft/vscode-jupyter#12270]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.0
- OS Version: macOS 12.2.1

Steps to Reproduce:

Previously when doing df.head() or df.plot.line() I would see the output right away. Now all I get are descriptions of what the object type is.
![image](https://user-images.githubusercontent.com/11791012/156798814-c85787c2-7440-4122-8959-0a6808c1aa47.png)

This is what I see when I click on "Change presentation"
![image](https://user-images.githubusercontent.com/11791012/156798905-b6a9b9ca-94df-4249-a319-c94ffbe99ec7.png)

**Comment by amunger** [comment]
I'm not seeing this with the latest releases so I'll close for now since this issue is several months old. Could you comment or open another issue if this is still occurring?
