### ISSUE TITLE
Duplicated Suggestion

### ISSUE THREAD

**Issue by JiaranYa** [microsoft/vscode-jupyter#12280]
## Environment data

-   VS Code version: 1.73.1
-   Jupyter Extension version (available under the Extensions sidebar): v2022.9.1303220346
-   Python Extension version (available under the Extensions sidebar): v2022.18.2
-   PylanceExtension version : v2022.11.40
-   OS (Windows | Mac | Linux distro) and version: Win 10
-   Python and/or Anaconda version: 3.9.13
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local 

## Expected behaviour

-

## Actual behaviour

Pylance give suggestions/error reports/ hints ..  twice on the same issue.
this will be fixed after Jupyter extension disabled
same error reports in pylance: 
[#3674](https://github.com/microsoft/pylance-release/issues/3674)
[#3617](https://github.com/microsoft/pylance-release/issues/3617)
[#3693](https://github.com/microsoft/pylance-release/issues/3693)

(extra: update to pre-release version solve the problem, cause jupyter extension won't work properly,it cannot be loaded)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by amunger** [comment]
This is fixed in pre-release, though the latest pre-release doesn't work with vscode stable because of https://github.com/microsoft/vscode-jupyter/issues/12200. You can either install VSCode insiders or downgrade the Jupyter extension to v2022.11.1003281132 to work around this issue until it is resolved next week.

**Comment by JiaranYa** [comment]
Thank you
