### ISSUE TITLE
Copy / Paste of cells in new notebook editor links them

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#1228]
Pretty sure this is not intentional. When I copy a cell and then paste it, the two cells are then linked. They have the same execution count and typing in one also edits the other. So I can't copy a cell and then edit the copy with some changes. It's also causing some strange hover issues.

![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/3cb1b4e4-04da-47bf-8278-037c921106ea)

**Comment by DavidKutu** [comment]
I'm not able to repro this. I'll move it to validate and @IanMatthewHuff please check if you can repro it again. I think it might already be fixed.

**Comment by DonJayamanne** [comment]
Validated
