### ISSUE TITLE
How to develop extensions for vscode jupyter?

### ISSUE THREAD

**Issue by code1704** [microsoft/vscode-jupyter#12287]
We want to develop a new notebook metadata type for jupyter which will support drag-drop like input.

Does vscode jupyter support this?

**Comment by DonJayamanne** [comment]
thanks for existing interest in developing extensions.
>  new notebook metadata type

not sure what you mean by metadata type

> support drag-drop like input.

are you trying to support drag and drop into the text editor or something else. please could you describe some of the proposed functionality

**Comment by code1704** [comment]
Thanks for your reply.

We want to make the input editor more friendly.

1. visual visual builder (it will generate python code based on the dag and can be run as notebook cell)

<img width="588" alt="image" src="https://user-images.githubusercontent.com/110730540/205428769-443ec3a6-2544-41b8-a8f3-09bfc2157b87.png">

2. another example is colab
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/110730540/205428907-06c97ee7-b58c-4bdc-8ca5-cb077715404a.png">

**Comment by code1704** [comment]
Thanks for your reply.

We want to make the input editor more friendly.

1. visual visual builder (it will generate python code based on the dag and can be run as notebook cell)

<img width="588" alt="image" src="https://user-images.githubusercontent.com/110730540/205428769-443ec3a6-2544-41b8-a8f3-09bfc2157b87.png">

2. another example is colab
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/110730540/205428907-06c97ee7-b58c-4bdc-8ca5-cb077715404a.png">

**Comment by DonJayamanne** [comment]
> We just want to know which notebook API to use to render the cell input?

this will be interesting.
* You can create a Notebook Controller (`vscode.notebooks.createNotebookController`) that supports execution of cells.
* Then you can use `controller.createNotebookCellExecution` to create a `NotebookCellExecution` object that can be used to insert outputs into a notebook cell containing HTML output or the like
* 
*

**Comment by code1704** [comment]
> * Then you can use `controller.createNotebookCellExecution` to create a `NotebookCellExecution` object that can be used to insert outputs into a notebook cell containing HTML output or the like

Seems it will not work for this case. We need to render the input instead of output.

**Comment by DonJayamanne** [comment]
Yes thats correct, unfortunately its not possible to have a different view for inputs.
I think th eonly way to achieve a different view for inputs is to create a custom renderer for makdown

Please could you file an issue on the vscode repo with a feature request for a new API that would allow you to have a custom renderer/view for input cells?
