### ISSUE TITLE
Project names in kernel picker menu

### ISSUE THREAD

**Issue by kolibril13** [microsoft/vscode-jupyter#12292]
As `.venv` will be present in lots of local projects (e.g. because they were created with poetry), how about a list that would show the project in the kernel picker menu name as well e.g.:
* `.venv (/manim/.venv)`
* `.venv (/segmentation/.venv)`
* `.venv (/pytutorial/.venv)`

That way, it would become super easy to quickly test a notebook with kernels that come from other local projects.

**Comment by DonJayamanne** [comment]
@kolibril13 when you using the Python extension and use the command `Python: Select Interpreter` are the poetry environments listed in the way described above?
If not, then I'd suggest creating a similar feature request  there as well.

**Comment by kolibril13** [comment]
> When you using the Python extension and use the command Python: Select Interpreter are the poetry environments listed in the way described above?

No they don't. I've made https://github.com/microsoft/vscode-python/issues/20352 for that.

Also, I have some more feedback on the latest kernel picker menu here: https://github.com/microsoft/vscode/issues/168558
It's basically this issue (kernels from other projects), and two other issues ("Better kernel picking when creating first notebook" and "Local Python Environments not showing in parent folder") combined in one report.

**Comment by DonJayamanne** [comment]
Since the Jupyter extension uses the API provided by the Python extension, I'm going to close this issue.
As soon as the Python extension adds support for this we'll get this automatically

Hence closing in favour of the other (duplicate/upstream) issue
