### ISSUE TITLE
Create at least one debugger test that has a @mandatory tag added to the test name

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12305]
The `@mandatory` test tag is added to ensure that a PR can safely be merged knowing that mandatory features/tests pass.
It would be good to have at least one debugger test that has a `@mandatory` tag added to a test.

Currently PRs are blocked on ensuring all jobs containing the text `@mandatory` will always pass
With the way things stand, its possible for all debugger tests to pass an a PR get merged.

![Screenshot 2022-12-05 at 09 29 38](https://user-images.githubusercontent.com/1948812/205519427-03f34ae8-35bb-4d8e-aa6f-ee32e188f50d.png)

**Comment by roblourens** [comment]
Did this
