### ISSUE TITLE
Variable viewer for Native Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1230]

**Comment by joyceerhl** [comment]
Working on validating this. Is the expectation just 'works as before with native notebooks'?

One question I had: I noticed that we have this smaller tab within the Jupyter: Variables tab. Is there a reason we have this / can we remove this? I clicked on it to see what it would do and had to reload all of VSCode to get the variable panel back. If we are planning on keeping it around, I'd expect to be able to restore it with a command or on the next cell execute / notebook open.

![image](https://user-images.githubusercontent.com/30305945/104357358-ed349680-54c1-11eb-979f-cf73a0ba4073.png)

**Comment by matrix303** [comment]
Hi, i would appreciate it if it worked just as before.

I am running the latest beta build and cana not find the JUPYTER:VARIABLES tab, how can I access that?

**Comment by joyceerhl** [comment]
@matrix303 this isn't available yet. I believe it will become available in our next release. Thanks for your patience!

**Comment by IanMatthewHuff** [comment]
@joyceerhl I'm never fully sure how to validate these more meta work items. I was counting this as when the bulk of the work was done with a functioning variable view that was in. Then I was using individual work items to track follow up issues (tests, ui cleanup). Personally I care more about the validations for bugs / regressions where it's easy to see if something is fixed. If the variable view shows up and generally works I'd count this as done.

You are correct about the X button. That's part of the remaining UI cleanup. The variable view still thinks that it's part of the interactive window and that x I'm pretty sure is a leftover from that. Same thing with the height and width sizing. Hoping to do that after I get the tests up and running.

**Comment by joyceerhl** [comment]
Sweet, yeah it shows up and generally works 😊 marking this one as validated then.
