### ISSUE TITLE
Jupyter remotes not detected after adding a new remote server

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12318]

**Comment by roblourens** [comment]
Did this change since testing? I tested with remote servers

**Comment by DonJayamanne** [comment]
> Did this change since testing? I tested with remote servers

@rebornix can you describe the scenario when this didn't work for you.

**Comment by rebornix** [comment]
Since the update handler is never called, remote server will not work if providers are registered very late. For builtin remote server support, or extension which depends on Jupyter, they register remote server providers very early so they are identified by Jupyter.
