### ISSUE TITLE
Show the RAM and disk usage in the toolbar.

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12326]
I'd like to make another suggestion. A cool thing about Google Colab is that they show the RAM and disk usage in the toolbar. 

**Toolbar**

![usage-toolbar](https://user-images.githubusercontent.com/30958850/91634441-bbc69d00-e9f0-11ea-9cee-0adddae57272.png)

**Clicking on the toolbar opens this popup with more details**

![usage-popup](https://user-images.githubusercontent.com/30958850/91634443-bcf7ca00-e9f0-11ea-9cf8-5ff263beef0f.png)

Disk usage isn't that relevant when working locally but the RAM and CPU usage coming from the interactive window would be great to know.

![interactive-toolbar](https://user-images.githubusercontent.com/30958850/91634480-14963580-e9f1-11ea-89a6-76d7e8aacedb.png)

_Originally posted by @janosh in https://github.com/microsoft/vscode-jupyter/issues/1248#issuecomment-683269380_

**Comment by roblourens** [comment]
I actually think that a separate extension would be best for this. There appear to be a few extensions that provide local system usage stats in a generic way, in the window status bar or other places.
