### ISSUE TITLE
One of the notebook commands in the Command palette has percent signs around it

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-jupyter#12333]
The notebook open contextual help command seems to have a formatting issue.

![Screenshot of the command palette showing a notebook command with percent signs around it](https://user-images.githubusercontent.com/7199958/206056524-44bf3b61-87ba-4e45-82ed-2ee7e8ab78d3.png)

**Comment by DonJayamanne** [comment]
Thanks for filing this, please could you install the latest version and let me know how this goes.

**Comment by rzhao271** [comment]
LGTM
