### ISSUE TITLE
Mount the Remote File System and Remote terminal in VSCode for a remote Jupyter server

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-jupyter#1233]
Here's the branch that contains all my work. 
https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode?version=GBshsuman%2FremoteFSAndTerminal

Look into /src/azureml-remote folder

**Comment by DonJayamanne** [comment]
Closing in favor of the remote spec

**Comment by DonJayamanne** [comment]
Will be using the work from @shsuman
