### ISSUE TITLE
Debugging interactive window never starts for remote kernel

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12341]
I was connected to a remote kernel, set a breakpoint in a .py file and clicked the debug cell code lens.
The debugging toolbar appeared, but I don't think the code was submitted and the breakpoint was never hit.

![image](https://user-images.githubusercontent.com/2019016/206244582-a01dde02-b1f7-4e12-a10f-484b61f90d78.png)

[debuggingIWLogs.txt](https://github.com/microsoft/vscode-jupyter/files/10178329/debuggingIWLogs.txt)

Jupyter server logs from that time

```
[I 09:05:34.084 NotebookApp] Creating new notebook in
[I 09:05:34.250 NotebookApp] Kernel started: 99f96b8d-ec2a-4149-bd0a-e2fcd103e9c9, name: python3
[W 09:05:34.284 NotebookApp] delete /script1.py-jvsc-8a40bb87-9c8a-4bd4-9f2b-bd54a3a0178bba999467-a371-4bc6-bdcd-4a1bcfac3640.ipynb
```

**Comment by amunger** [comment]
I have not been able to resolve this after Reloading vs Code, trying a different script, killing and starting a new Jupyter server

**Comment by roblourens** [comment]
I think this will be fixed with https://github.com/microsoft/vscode-jupyter/issues/12407
