### ISSUE TITLE
Optional detail for remote kernels in kernel picker looks weird

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#12344]
<img width="737" alt="image" src="https://user-images.githubusercontent.com/876920/206268604-f71921f6-7c0d-424f-a482-0b9747eb1ac0.png">

It looks weird that we are showing detail for remote kernels but not others.

**Comment by DonJayamanne** [comment]
Agreed. the argument here was that when dealing with remote active kernels the last time it was active is crucial in picking a kernel.
However we could easily just remove this and see whether users complain.
I think this was based on an assumption that it was required

**Comment by rebornix** [comment]
We can probably change this
<img width="554" alt="image" src="https://user-images.githubusercontent.com/876920/213324842-54e7454d-5a61-4c4b-8dff-0eae74bb9ccc.png">

to

<img width="557" alt="image" src="https://user-images.githubusercontent.com/876920/213324777-0b41b4f8-c2df-4d9b-b0e4-24fc7bd8b855.png">

**Comment by DonJayamanne** [comment]
In controller do not display `detail` controllers within the Jupyter extension.

**Comment by andreamah** [comment]
Is there an easy way to get a remote kernel so that we can verify this?

**Comment by rebornix** [comment]
@andreamah if you have Docker installed you can use https://marketplace.visualstudio.com/items?itemName=rebornix.vscode-jupyter-docker-stack-connect

**Comment by rebornix** [comment]
I can actually verify this.
