### ISSUE TITLE
IJupyterServerUri detail ignored in kernel picker

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#12345]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/876920/206268999-db66b989-5ab6-435c-bbb3-7d621cadc928.png">

We now support display name for `IJupyterServerUri` contributed by extensions, but its name is ignored in the server list.

**Comment by DonJayamanne** [comment]
We are already doing this, 
```label: provider.displayName ?? provider.id,```
Probably done after the issue was created.
Closing to be verified.

@rebornix please could you verify this works as expected.
