### ISSUE TITLE
Language server duplicated

### ISSUE THREAD

**Issue by ywnien** [microsoft/vscode-jupyter#12340]
Type: <b>Bug</b>

1. Open both .py and .ipynb files in vscode
2. Write some codes and find two same objects in code prompt window
3. Also, check the dropdown menu of OUTPUT (Ctrl + Shift + U), there are "Python Language Server" and "Python 3.XX.X (<kernal name>)-languageserver"

Is there any way to manually shutdown the language server launched by Jupyter?

Extension version: 2022.9.1303220346
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.0-91-generic

**Comment by DonJayamanne** [comment]
@ywnien 
Please could you install VS Code insiders and the latest pre-release version of the Jupyter, Python and Pylance extensions and confirm this still repros.

**Comment by ywnien** [comment]
The problem is solved when I only changed to pre-release Jupyter (v2023.1.1003411034). Python, Pylance and VS Code are all stable version.
Weeks ago the pre-release Jupyter was unstable and keep crashing. Now it seems to be stable and seccessfully run on Windows10, WSL2 (ubuntu 20.04) and ssh remote server (ubuntu 20.04).

Thanks a lot!
