### ISSUE TITLE
Opening notebook changes it

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-jupyter#12352]
## Environment data

-   VS Code version: 1.74.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2023.1.1003411034 
-   Python Extension version (available under the Extensions sidebar): v2022.21.13411007 
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: 3.9.15
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): miniconda
-   Jupyter server running: Local

## Expected behaviour

Opening a notebook shouldn't change it.

## Actual behaviour

Opening a notebook changes it and the SCM view shows it has changed:

```patch
@joaomoreno ➜ /workspaces/aoc2022 (main ✗) $ git diff
diff --git a/7/7.ipynb b/7/7.ipynb
index ba81b36..79e2ae3 100644
--- a/7/7.ipynb
+++ b/7/7.ipynb
@@ -179,7 +179,7 @@
    "name": "python",
    "nbconvert_exporter": "python",
    "pygments_lexer": "ipython3",
-   "version": "3.9.15"
+   "version": "3.9.15 (main, Nov 24 2022, 14:31:59) \n[GCC 11.2.0]"
   },
   "orig_nbformat": 4,
   "vscode": {
```

**Comment by DonJayamanne** [comment]
Given the fact that vscode remembers the kernel last used, I think we can now stop storing interprter information and limit it to just version and kernelspec names.
