### ISSUE TITLE
Copied Images don't respect `jupyter.themeMatplotlibPlots`

### ISSUE THREAD

**Issue by thisiswhereitype** [microsoft/vscode-jupyter#12357]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When producing figures I have a this theme `"workbench.colorTheme": "Default Dark+"` which would make images/figures darker.
I set the following to allow the Notebook to use themes set in the Notebook.
`"jupyter.themeMatplotlibPlots": false`

The images appear as expected in notebook but when copying using the button and pasting into paint I have a Dark themed image.

### VS Code Version

Version: 1.73.1 (user setup) Commit: 6261075646f055b99068d3688932416f2346dd3b Date: 2022-11-09T04:27:29.066Z Electron: 19.0.17 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10.0.19042 Sandboxed: No

### Jupyter Extension Version

v2022.11.1003412109

### Running Jupyter locally or remotely?

Remote

**Comment by thisiswhereitype** [comment]
To be more specific I copied and pasted these images into paint.

When pasted into paint I get the transparent figure background turned black.

With this reproduced even on the light theme I also changed my Windows 10 theme to Light from Dark and after a `Developer: Reload Window ` and run reun of the Notebook found that I could produce a figure correct by exporting and saving but directly pasting a copied image into paint would turn transparent pixels black.

Aside from unexpected black pxiels the figure appears fine.

**Comment by DonJayamanne** [comment]
> When pasted into paint I get the transparent figure background turned black.

I believe this is expected, as the bacground is transparent.

Given the fact that no one has upvoted nor reported this issu over a year, I'm closing this issue for now.
