### ISSUE TITLE
kernel disappear with the last Jupyter extension update

### ISSUE THREAD

**Issue by FrancescoPaoloL** [microsoft/vscode-jupyter#12363]
Does this issue occur when all extensions are disabled?: No

Version: 1.74.0
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:47:18.476Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.4.0-135-generic snap
Sandboxed: No

Steps to Reproduce:

1.  Update Jupyter extension to the last version: 2022.11.1003412109 -- 1 day ago
2.  Run All, Clear Outputs of All Cells, Restart, Variables, Outline disappears; and No kernel select
3. Downgrade to 2022.9.1303220346 -- 3 wks ago
4. It works perfectly.

Please see the attached images.

![2022 11 1003412109_KO__1_day_ago](https://user-images.githubusercontent.com/47259713/206522592-b2406cdf-065d-4602-b4fb-ed30639064a9.png)
![2022 9 1303220346 _OK__3_wks_ago](https://user-images.githubusercontent.com/47259713/206522613-f229bb56-f096-40b4-b30f-3cec94a95ccb.png)

I am available for further info.

**Comment by DonJayamanne** [comment]
@FrancescoPaoloL 
Thanks for filing this issue, i'm sorry you are running into this problem
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by FrancescoPaoloL** [comment]
Hi @DonJayamanne!
As attached what you're requested.
Is seems a problem with  `GLIBCXX_3.4.22' library (not found!).
I’m sharing the file with you (with some info omitted).
Thanks for helping me.
[verboseLog.txt](https://github.com/microsoft/vscode-jupyter/files/10189507/verboseLog.txt)

**Comment by DonJayamanne** [comment]
Thank you for providing the information requested, that helped a lot.
Looks like you have an old version of the Python extension installed. Please install the latest version of the Python extension from teh marketplace. YOu have 2022.8.* and thats pretty old.

here is the info in the logs
```
Python Extension Version: 2022.8.1.

warn 22:05:35.763: Failed to get Python interpreter details from Python Extension API for /usr/bin/python3 [TypeError: Cannot read properties of undefined (reading 'known')
```

Closing this issue as this should get fixed one you install the latest version of the Python extension installed.

**Comment by DonJayamanne** [comment]
If after updating the extension you still run into issues, please do feel free to ping here or feel free to create a new issue.
