### ISSUE TITLE
MRU kernel picker stuck loading after clicking `select different kernel...`

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12366]
![image](https://user-images.githubusercontent.com/2019016/206588910-1132d3c7-6bc5-48c4-b212-d4028e9f83d1.png)

I went to a window that had been idle for a while but the jupyter extension had already been activated, clicked the kernel picker, Select Another Kernel, and it won't load any of the providers.

No new logs are coming while clicking the picker, but here is what there already was in the output 
[kernelPickerLogs.txt](https://github.com/microsoft/vscode-jupyter/files/10190601/kernelPickerLogs.txt)

**Comment by amunger** [comment]
oops, old version

**Comment by DonJayamanne** [comment]
Thats interesting, at least the kernel sources should show up. At this point VS Code is responsbile for displaying the kernel sources.

@amunger Can you still repro this issue?
Do you see any errors in the vscode developer tools console window.

**Comment by amunger** [comment]
no relevant errors from there either, this is from `v2022.9.1303220346`, a stable release that claims to be from 3 weeks ago. I didn't think we had a stable release from that time... nor would I expect the mru kernel picker to be available in an earlier stable release.
