### ISSUE TITLE
3rd party provided jupyter servers not visible unless it's stored in uristorage

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#12365]
* Start Jupyter in empty state
* 3rd party jupyter server uri provider `getHandles()` returns multiple results
* since no of the handle is ever stored in serverUriStorage, when going through the mru kernel picker -> select another kernel -> 3rd party kernel source, it doesn't list the handles at all

**Comment by rebornix** [comment]
Another challenge with this is how we present handles to users. Handles are meant to be unique but not necessarily human readable, however the display name for each handle is only known after we fetch server info, which usually means launching the remote jupyter server.

We might want to follow VS Code's provider API patterns, where the fetching of a model is split into two steps

* `provideT(): Promise<T>`
* `resolveT(): Promise<void>`

and extensions can fill in optional properties in `resolve`. Maybe we can follow the same. For example, in `getHandles`, instead of just returning handle ids, we can return richer data

```
getHandles?(): Promise<(JupyterServerUriHandle | { handle: JupyterServerUriHandle, displayName: string } )[]>;
```

**Comment by DonJayamanne** [comment]
@rebornix why can't we just 
* Iterate through all the handles
* Get the server info for each handle and then populate the servers from that result
* 
this way we wno't need any new changes to the API, only the kernle picker needs to be updated

**Comment by amunger** [comment]
not clear what the verification steps are - 
Do I need to add a "3rd party jupyter server uri provider"? How do I do that?

Does the Julia extension count, and am I just looking for the julia kernel to be listed? (if so, then this is verified)
