### ISSUE TITLE
Interactive Jupyter Kernal hangs when starting with in a dev container environment

### ISSUE THREAD

**Issue by seanturner026** [microsoft/vscode-jupyter#12377]
## Environment data

-   VS Code version: 1.74.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.11.1003412109
-   Python Extension version (available under the Extensions sidebar): v2022.20.0
-   OS (Windows | Mac | Linux distro) and version: Mac 13.0.1 (ARM / M1), container is Debian GNU/Linux 11 (bullseye)
-   Python and/or Anaconda version: 3.9.15
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): docker dev container
-   Jupyter server running: Local

## Expected behaviour

Starting up Jupyter Interactive Jupyter interactive kernal does not hang

## Actual behaviour

Starting up Jupyter Interactive causes the kernal to hang.

I see this in the devtools, I'm pretty sure this is the issue. See screenshot below.

notebookWebviewPreloads.js:3 Notebook preload 'https://vscode-remote%2Bdev-002dcontainer-002b2f55736572732f7365616e2f636f64652f6b6f626f6c642d6d6574616c732f6d616368696e652d70726f73706563746f72.vscode-resource.vscode-cdn.net/home/kobold/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/node_modules/%40vscode/jupyter-ipywidgets7/dist/ipywidgets.js' was expected to be a module but it does not export an 'activate' function

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

Sorry, where should I go about getting the logs? I looked in the directory referenced in the below screenshot, and there was nothing really there. I also looked in the dev container logs and didn't see much.

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

</p>

</details>

<img width="1697" alt="image" src="https://user-images.githubusercontent.com/30396892/206799309-93490203-9c54-4d76-b8ff-2030f2a8f1f9.png">

**Comment by amunger** [comment]
you can run the command `Jupyter: Show Output` to get the logs for the extension. Just paste that content here. 
Those errors in the developer console are not related.

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

please could you upload the logs from the `Jupyter` output panel, you can get there output using the command `Jupyter: Show Output`. Please remember to copy and upload all of the output.

**Comment by seanturner026** [comment]
Yep! Enabled verbose logging and reloaded VS code.

Here's the output from the `Jupyter` output panel.


Visual Studio Code (1.74.0, dev-container, desktop)
Jupyter Extension Version: 2022.11.1003412109.
Python Extension Version: 2022.20.0.
Workspace folder /home/blah-org/blah-repo
info 22:13:32.179: ZMQ install verified.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 22:13:32.516: LSP Notebooks experiment is enabled
info 22:13:32.569: Starting interactive window for resource '' with controller '.jvsc74a57bd0949777d72b0d2535278d3dc13498b2535136f6dfe0678499012e853ee9abcab1./usr/local/python./usr/local/python.-m#ipykernel_launcher (Interactive)'
info 22:13:32.722: Got empty env vars with python /usr/local/bin/python in 182ms
info 22:13:32.739: Process Execution: > /usr/local/bin/python -m pip list
> /usr/local/bin/python -m pip list
info 22:13:32.896: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0949777d72b0d2535278d3dc13498b2535136f6dfe0678499012e853ee9abcab1./usr/local/python./usr/local/python.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.9.15 (main, Nov 15 2022, 09:59:27) 
[GCC 10.2.1 20210110]) for 'Interactive-1.interactive' (disableUI=false)
info 22:13:32.897: Computing working directory for resource ''
info 22:13:32.915: Process Execution: > /usr/local/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /usr/local/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 22:13:32.978: Process Execution: > /usr/local/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"382dd11f-90be-4d70-a1f8-b92b24fd4116" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/blah-org/.local/share/jupyter/runtime/kernel-v2-7652eunUSazy5iOK.json
> /usr/local/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"382dd11f-90be-4d70-a1f8-b92b24fd4116" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/blah-org/.local/share/jupyter/runtime/kernel-v2-7652eunUSazy5iOK.json
info 22:13:32.979: Process Execution: cwd: ~/blah-repo
cwd: ~/blah-repo
info 22:13:33.070: Got empty env vars with python /usr/local/bin/python in 172ms
info 22:13:33.118: Got empty env vars with python /usr/local/bin/python in 165ms
info 22:13:33.118: Got empty env vars with python /usr/local/bin/python in 167ms
info 22:13:33.261: ipykernel version & path 6.3.1, /python/lib/python3.9/site-packages/ipykernel/__init__.py for /usr/local/bin/python
info 22:13:33.809: Kernel Output: To connect another client to this kernel, use: --existing kernel-v2-7652eunUSazy5iOK.json

warn 22:13:34.342: StdErr from Kernel Process [IPKernelApp] WARNING | Unknown error in handling startup files:

info 22:13:34.388: Started Kernel Python 3.9.15 (pid: 7971)
info 22:13:34.453: Process Execution: > /usr/local/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/printJupyterDataDir.py
> /usr/local/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/printJupyterDataDir.py
info 22:13:34.525: Got empty env vars with python /usr/local/bin/python in 90ms

**Comment by DonJayamanne** [comment]
thank you for providing the logs, please could you try the following:
```
/usr/local/bin/python -m pip install jupyter notebook
/usr/local/bin/python -m jupyter notebook
```
 
wait for Jupyter to start in a browser and try to run a cell in there.

**Comment by seanturner026** [comment]
Happy new year :) 

Modified the `jupyter notebook` command a bit. Also wasn't able to hit `localhost:8888/?token=1234567890` _probably_ because of a volume issue? Was able to hit localhost:8888 however and go from there by setting a password (which is the `302`s at the bottom of the comment).

```
$ docker run -it --rm -p 8888:8888 mp-notebook-upstream:latest bash
$ blah@ac7767afea6e:/home/jovyan$ /usr/local/bin/python -m pip install jupyter notebook
Defaulting to user installation because normal site-packages is not writeable
Collecting jupyter
  Downloading jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
Requirement already satisfied: notebook in /python/lib/python3.9/site-packages (6.4.3)
Requirement already satisfied: nbconvert in /python/lib/python3.9/site-packages (from jupyter) (6.5.0)
Requirement already satisfied: ipykernel in /python/lib/python3.9/site-packages (from jupyter) (6.3.1)
Collecting qtconsole
  Downloading qtconsole-5.4.0-py3-none-any.whl (121 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.0/121.0 kB 2.1 MB/s eta 0:00:00
Collecting jupyter-console
  Downloading jupyter_console-6.4.4-py3-none-any.whl (22 kB)
Requirement already satisfied: ipywidgets in /python/lib/python3.9/site-packages (from jupyter) (7.7.2)
Requirement already satisfied: jinja2 in /python/lib/python3.9/site-packages (from notebook) (3.1.2)
Requirement already satisfied: jupyter-core>=4.6.1 in /python/lib/python3.9/site-packages (from notebook) (4.11.1)
Requirement already satisfied: nbformat in /python/lib/python3.9/site-packages (from notebook) (5.4.0)
Requirement already satisfied: tornado>=6.1 in /python/lib/python3.9/site-packages (from notebook) (6.1)
Requirement already satisfied: terminado>=0.8.3 in /python/lib/python3.9/site-packages (from notebook) (0.12.1)
Requirement already satisfied: Send2Trash>=1.5.0 in /python/lib/python3.9/site-packages (from notebook) (1.8.0)
Requirement already satisfied: ipython-genutils in /python/lib/python3.9/site-packages (from notebook) (0.2.0)
Requirement already satisfied: prometheus-client in /python/lib/python3.9/site-packages (from notebook) (0.11.0)
Requirement already satisfied: pyzmq>=17 in /python/lib/python3.9/site-packages (from notebook) (23.2.1)
Requirement already satisfied: jupyter-client>=5.3.4 in /python/lib/python3.9/site-packages (from notebook) (7.3.4)
Requirement already satisfied: argon2-cffi in /python/lib/python3.9/site-packages (from notebook) (21.1.0)
Requirement already satisfied: traitlets>=4.2.1 in /python/lib/python3.9/site-packages (from notebook) (5.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /python/lib/python3.9/site-packages (from jupyter-client>=5.3.4->notebook) (2.8.2)
Requirement already satisfied: entrypoints in /python/lib/python3.9/site-packages (from jupyter-client>=5.3.4->notebook) (0.3)
Requirement already satisfied: nest-asyncio>=1.5.4 in /python/lib/python3.9/site-packages (from jupyter-client>=5.3.4->notebook) (1.5.5)
Requirement already satisfied: ptyprocess in /python/lib/python3.9/site-packages (from terminado>=0.8.3->notebook) (0.7.0)
Requirement already satisfied: cffi>=1.0.0 in /python/lib/python3.9/site-packages (from argon2-cffi->notebook) (1.14.6)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in /python/lib/python3.9/site-packages (from ipykernel->jupyter) (1.4.1)
Requirement already satisfied: matplotlib-inline<0.2.0,>=0.1.0 in /python/lib/python3.9/site-packages (from ipykernel->jupyter) (0.1.3)
Requirement already satisfied: ipython<8.0,>=7.23.1 in /python/lib/python3.9/site-packages (from ipykernel->jupyter) (7.27.0)
Requirement already satisfied: jupyterlab-widgets<3,>=1.0.0 in /python/lib/python3.9/site-packages (from ipywidgets->jupyter) (1.1.1)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /python/lib/python3.9/site-packages (from ipywidgets->jupyter) (3.6.1)
Requirement already satisfied: MarkupSafe>=2.0 in /python/lib/python3.9/site-packages (from jinja2->notebook) (2.0.1)
Requirement already satisfied: pygments in /python/lib/python3.9/site-packages (from jupyter-console->jupyter) (2.10.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /python/lib/python3.9/site-packages (from jupyter-console->jupyter) (3.0.20)
Requirement already satisfied: nbclient>=0.5.0 in /python/lib/python3.9/site-packages (from nbconvert->jupyter) (0.5.4)
Requirement already satisfied: defusedxml in /python/lib/python3.9/site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: beautifulsoup4 in /python/lib/python3.9/site-packages (from nbconvert->jupyter) (4.11.1)
Requirement already satisfied: bleach in /python/lib/python3.9/site-packages (from nbconvert->jupyter) (4.1.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /python/lib/python3.9/site-packages (from nbconvert->jupyter) (1.4.3)
Requirement already satisfied: tinycss2 in /python/lib/python3.9/site-packages (from nbconvert->jupyter) (1.1.1)
Requirement already satisfied: mistune<2,>=0.8.1 in /python/lib/python3.9/site-packages (from nbconvert->jupyter) (0.8.4)
Requirement already satisfied: packaging in /python/lib/python3.9/site-packages (from nbconvert->jupyter) (21.3)
Requirement already satisfied: jupyterlab-pygments in /python/lib/python3.9/site-packages (from nbconvert->jupyter) (0.2.2)
Requirement already satisfied: jsonschema>=2.6 in /python/lib/python3.9/site-packages (from nbformat->notebook) (3.2.0)
Requirement already satisfied: fastjsonschema in /python/lib/python3.9/site-packages (from nbformat->notebook) (2.15.3)
Collecting qtpy>=2.0.1
  Downloading QtPy-2.3.0-py3-none-any.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.6/83.6 kB 16.4 MB/s eta 0:00:00
Requirement already satisfied: pycparser in /python/lib/python3.9/site-packages (from cffi>=1.0.0->argon2-cffi->notebook) (2.20)
Requirement already satisfied: decorator in /python/lib/python3.9/site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (5.0.9)
Requirement already satisfied: pexpect>4.3 in /python/lib/python3.9/site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (4.8.0)
Requirement already satisfied: setuptools>=18.5 in /python/lib/python3.9/site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (65.5.0)
Requirement already satisfied: pickleshare in /python/lib/python3.9/site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (0.7.5)
Requirement already satisfied: backcall in /python/lib/python3.9/site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (0.2.0)
Requirement already satisfied: jedi>=0.16 in /python/lib/python3.9/site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (0.18.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /python/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat->notebook) (0.18.0)
Requirement already satisfied: six>=1.11.0 in /python/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat->notebook) (1.16.0)
Requirement already satisfied: attrs>=17.4.0 in /python/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat->notebook) (21.2.0)
Requirement already satisfied: wcwidth in /python/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->jupyter-console->jupyter) (0.2.5)
Requirement already satisfied: soupsieve>1.2 in /python/lib/python3.9/site-packages (from beautifulsoup4->nbconvert->jupyter) (2.3.2.post1)
Requirement already satisfied: webencodings in /python/lib/python3.9/site-packages (from bleach->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /python/lib/python3.9/site-packages (from packaging->nbconvert->jupyter) (3.0.9)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /python/lib/python3.9/site-packages (from jedi>=0.16->ipython<8.0,>=7.23.1->ipykernel->jupyter) (0.8.2)
Installing collected packages: qtpy, qtconsole, jupyter-console, jupyter
Successfully installed jupyter-1.0.0 jupyter-console-6.4.4 qtconsole-5.4.0 qtpy-2.3.0

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: python -m pip install --upgrade pip

$ blah@ac7767afea6e:/home/jovyan$ /usr/local/bin/python -m jupyter notebook -y --no-browser --ip=0.0.0.0 --ServerApp.token='blah' --ServerApp.password='blah' --notebook-dir=/home/jovyan
[I 16:50:29.821 NotebookApp] Writing notebook server cookie secret to /home/blah/.local/share/jupyter/runtime/notebook_cookie_secret
[I 16:50:30.952 NotebookApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2023-01-03 16:50:31.026 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-01-03 16:50:31.026 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-01-03 16:50:31.026 LabApp] 'answer_yes' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2023-01-03 16:50:31.026 LabApp] 'answer_yes' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2023-01-03 16:50:31.026 LabApp] 'answer_yes' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[I 2023-01-03 16:50:31.030 LabApp] JupyterLab extension loaded from /python/lib/python3.9/site-packages/jupyterlab
[I 2023-01-03 16:50:31.030 LabApp] JupyterLab application directory is /python/share/jupyter/lab
[I 16:50:31.066 NotebookApp] Registered JupyterLab Link Share extension at URL path /jupyterlab_link_share
[I 16:50:32.405 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 16:50:32.406 NotebookApp] Jupyter Notebook 6.4.3 is running at:
[I 16:50:32.406 NotebookApp] http://ac7767afea6e:8888/?token=1234567890
[I 16:50:32.406 NotebookApp]  or http://127.0.0.1:8888/?token=1234567890
[I 16:50:32.406 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:50:32.407 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///home/blah/.local/share/jupyter/runtime/nbserver-13-open.html
    Or copy and paste one of these URLs:
        http://ac7767afea6e:8888/?token=1234567890
     or http://127.0.0.1:8888/?token=1234567890
[I 16:50:38.306 NotebookApp] 302 GET / (172.17.0.1) 1.110000ms
# this is my going to localhost:8888 and setting a new password using the existing token.
[I 16:50:38.321 NotebookApp] 302 GET /tree? (172.17.0.1) 0.680000ms
[I 16:50:53.530 NotebookApp] Wrote hashed password to /home/blah/.jupyter/jupyter_notebook_config.json
[I 16:50:53.531 NotebookApp] 302 POST /login?next=%2Ftree%3F (172.17.0.1) 42.950000ms
/usr/local/lib/python3.9/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
```

In a second terminal:
```
$ docker ps
CONTAINER ID   IMAGE                         COMMAND                 CREATED         STATUS         PORTS                    NAMES
ac7767afea6e   mp-notebook-upstream:latest   "/entrypoint.sh bash"   4 minutes ago   Up 4 minutes   0.0.0.0:8888->8888/tcp   boring_elbakyan
```

**Comment by seanturner026** [comment]
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/30396892/210404841-e5307f5e-2968-40ac-b82c-77008642edb4.png">

**Comment by DonJayamanne** [comment]
Please could you send the docker file so I could try this at my end.
Also, please could you enable verbose logging, i don't think you have enabled verbose logging when you provided the logs. See below for instructions.

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by seanturner026** [comment]
I think we've figured this out on our end. Thank you very much for the help :)
