### ISSUE TITLE
Support for editing Plain text files (like Python,  MyST and R Markdown-based) as notebooks

### ISSUE THREAD

**Issue by teonbrooks** [microsoft/vscode-jupyter#1237]
Recently I've been using [jupyter-book](https://github.com/executablebooks/jupyter-book) as one of my primary notebook environments. It's built on top of MyST, which is a flavor of markdown that is compatible with reStructuredText, and they've built an extension for [syntax support](https://marketplace.visualstudio.com/items?itemName=ExecutableBookProject.myst-highlight).

I really love the integration VSCode has for executing `#%%` cells in python scripts with and general cells in Jupyter Notebooks. I am wondering if it would be of interest to support other cell paradigms like the ``` code chunk delimiter one in jupyter-book, which is also shared in RMarkdown. 
If it's a not feature that fits the roadmap, could you make a suggestion how I might be able to build off what is currently there and support it as an extension?

Thanks a bunch! I really love this product

**Comment by teonbrooks** [comment]
Hi, unfortunately I don't think I will have time to take this on myself but I think this would be a great improvement to notebook ergonomics in vscode.

**Comment by CaseyWeiner** [comment]
If this could happen at some point, that would be really awesome. One idea I had for HTML export is to expand it to prompt the user to pick either a static file or a jupyter book. For example if I choose jupyter book, it opens a GUI prompt to specify traits of the book and then creates the html pages. Could incorporate Github pages with this as well

**Comment by teonbrooks** [comment]
for visibility, it looks like the quarto vscode extension now supports its version of markdown, qmd (https://github.com/quarto-dev/quarto-cli/issues/149). I think a similar pattern could be used for the code execution part for other markdown files. looks like there's a related PR (https://github.com/microsoft/vscode-jupyter/pull/4876) to generalize the markdown within the standard vscode library

**Comment by arogozhnikov** [comment]
Moving suggestion from https://github.com/microsoft/vscode-jupyter/discussions/10174 as recommended by @DonJayamanne 

There are a number of already-existing formats that can convert from/to ipynb, implemented as context managers for jupyter. They augment loading/saving process with on-the-fly conversion between filetypes. 

While it could be of high value to implement the same for vs code, currently custom NotebookSerializers should provide conversion vscode <> custom format. This requires a lot of logic that is specific to vs code, and requires copying a good chunk of code and dependencies from vs code. (see https://github.com/microsoft/vscode-jupyter/discussions/10174)

Proposal below should simplify support for custom formats by reusing existing converters between ipynb and custom formats.

I suggest that *default* vscode NotebookSerializer for ipynb could be provided with a following triple:
```
1. filename extension (e.g. .Rmd, .ipynb.py and others)
2. callback to_ipynb(custom_format_bytes, filepath) -> ipynb_bytes
3. callback from_ipynb(ipynb_bytes, filepath) -> custom_format_bytes
```

For instance, when saving a file, extension will convert to ipynb, then use a corresponding conversion.

While `filepath` argument shouldn't be used in most conversions, it will be useful for extensions that grab additional files (like jupytext) or are configured at the repository level so they could have access to configuration files.

**Comment by parmentelat** [comment]
I'd like to +1 here

We have been using (jupytext-powered) text-based notebooks for quite some time now, 
because ipynb goes along with git so awkwardly

Using jupyter classic notebook mainly, so together with jupytext
And it would be tremendous help to be able to use vs-code instead

I've been trying to use [the vscode-jupytext extension](https://github.com/notebookPowerTools/vscode-jupytext) for a while,  but this clearly needs more work, so I ended up here following @DonJayamanne's post in that repo

How can we help ?

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1240
