### ISSUE TITLE
[BUG] Unknown warning

### ISSUE THREAD

**Issue by CoolPlayLin** [microsoft/vscode-jupyter#12383]
## Environment data

-   VS Code version: 1.74.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.11.1003412109
-   Python Extension version (available under the Extensions sidebar): v2022.20.0
-   OS (Windows | Mac | Linux distro) and version: Windows 11 22623.1028(22H2)
-   Python and/or Anaconda version: 3.11.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A: Local

## Actual behaviour

![image](https://user-images.githubusercontent.com/96709586/206885537-5bf5342f-03fc-43ce-adf6-ce0ac3db0cfa.png)

## Steps to reproduce:

When I delete the previous code block, the warning here says that the function is missing, but the code that defines the function is gone.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
@heejaechang any idea why this is happening. what kind of logs would you need to resolve this issue?

**Comment by CoolPlayLin** [comment]
I think I do not need the answer to the question.

**Comment by CoolPlayLin** [comment]
Thanks @DonJayamanne
