### ISSUE TITLE
Interactive Window settings are hard to identify

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12393]
All Jupyter extension settings are under the same group, but it's hard to tell what would apply to IW vs notebooks in general

**Comment by amunger** [comment]
verification steps:
1. open vscode without activating the jupyter extension (no .ipynb or .py editors visible)
2. open your settings JSON and add some deprecated settings (should have deprecation message)
```
"jupyter.interactiveWindowMode": "perFile",
"jupyter.newCellOnRunLast": false,
"jupyter.sendSelectionToInteractiveWindow": true,
"jupyter.enableAutoMoveToNextCell": false
```
3. activate the jupyter extension (open a .ipynb file)
4. check that the settings are eventually migrated

**Comment by rzhao271** [comment]
Doesn't work in a non-default profile. When I switch to a non-default profile and then run the "Open Current Profile Settings (JSON)" command, that opens a settings file that isn't the same as the JSON file used for the default profile.

**Comment by rzhao271** [comment]
And it's good now, at least on the default profile.
