### ISSUE TITLE
Issues with ipykernel debugging in the Interactive Window

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#12407]
There are some issues with ipykernel debugging (using `"jupyter.forceIPyKernelDebugger": true` or on a remote jupyter server) in the Interactive Window that need to be fixed as prereqs to https://github.com/microsoft/vscode-jupyter/issues/11777. I'll make this list more specific when I get back into it

- Mapping breakpoints to cells is not quite correct
- Setting a breakpoint in a cell after the debugged cell can hang the extension host
- Sometimes the line number translation goes to the wrong lines

**Comment by roblourens** [comment]
Since we have all these issues with mapping lines and cell paths, I was looking into using `setPydevdSourceMap`, as we used to do. It's not quite clear why we are doing the mapping in the extension, rather than using this feature to have debugpy do it. I tried to do this copying the way we used it previously but the maps are not taking effect, and I can confirm that by looking for the debugpy log lines that include `(after source mapping)` and `(after path translation)`.

@int19h - Should `setPydevdSourceMap` still work with the way we now talk to debugpy through ipykernel? Do you know of anything I'd need to do differently? My guess is that I'm sending the wrong thing for `runtimeSource.path` but I am copying the same pattern from our old code. If you would expect it to work then I'll try to add some more debug logs to debugpy to work out why they aren't applied.

**Comment by roblourens** [comment]
One thing I'm trying to understand is, what's the difference between using paths that look like `<ipython-input-1-09853089e9ea>` and the paths that I'm more familiar with, like `/var/folders/tx/p0ycbfpj37786p760wwdg6y80000gn/T/ipykernel_4963/3029800661.py`? @DonJayamanne do you know?

**Comment by roblourens** [comment]
I have this API working now, but I'm still not sure whether I will use it or keep the manual remapping in the extension code.

One more question @int19h, I would like to use `setPydevdSourceMap` to map between vscode notebook cell URIs and the runtime path (as well as using it for the interactive window which is a real single .py file). But since the cell is not a real file on disk, it fails this check

https://github.com/microsoft/debugpy/blob/main/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_api.py#L505-L508

I notice that if I just prepend a `<` to the cell URI, then debugpy will happily map correctly to my cell URI, I just have to clean up that character in responses. Would it be safe to rely on this behavior? Or would I be abusing the API?

**Comment by DonJayamanne** [comment]
> d is, what's the difference between using paths that look like <ipython-input-1-09853089e9ea> and the paths that I'm more familiar with, like

I wasn't involved in any of the debugger work, hence my knowledge is limited to what I've learnt from my own research.
I believe `ipython-input-1-09853089e9ea` are paths generated when using the old approach of the debugging (our old approach) and paths such as `ipykernel_4963/3029800661.py` are generated by ipykernel/ipython module that has support for debugging built into it (i.e. using built in debugger using Jupyter protocol).

**Comment by int19h** [comment]
Relying on `<` would be safe as it is a well-established convention for `__file__` in Python when it is not actually a filename - stuff like `<string>` or `<frozen ...>` coming from Python itself, or `<ipython...>` from Jupyter.

**Comment by roblourens** [comment]
Looked at the logs for notebook debugging, where we have a similar flow but no pydevd sourcemap, and noticed this

```
0.00s - File traced: /var/folders/tx/p0ycbfpj37786p760wwdg6y80000gn/T/ipykernel_65647/2595120235.py
0.00s - Added breakpoint:/private/var/folders/tx/p0ycbfpj37786p760wwdg6y80000gn/t/ipykernel_65647/2595120235.py - line:3 - func_name:None
```

This is the tmp directory on mac, which is symlinked from `/var/...` to `/private/var/...`. When you have a sourcemap, then set a breakpoint, debugpy doesn't try to resolve its symlinked path to a canonical path, but the breakpoint will only bind if it's on the resolved path. If I use the path with the resolved symlink in the sourcemap, then the sourcemap is not applied at all. 

Could work around it if we could have ipykernel (?) only use canonical paths, but I don't think we can have control over that.

**Comment by roblourens** [comment]
Don suggested that we can still control this path using `IPYKERNEL_CELL_NAME`, which would let us force the name to be the canonicalized tmp path, and could in theory work around this issue. I will attempt that for next month.
