### ISSUE TITLE
Calling `exit(0)` in a cell can crash the Jupyter kernel

### ISSUE THREAD

**Issue by eltechnic0** [microsoft/vscode-jupyter#12405]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I would like to have some cells stop execution dynamically (programmatically) based on some conditions. I came up with this idea of using `exit(0)` to do this. Sometimes it looks like it does the trick (maybe just the first time), but other times the cell is not interrupted and even worse, the kernel crashes after a few seconds. Also kernel restart and reconnection seems to go on forever.

I don't know if doing `exit(0)` is a valid mechanism to interrupt a cell being executed flawlessly, while letting the execution continue to subsequent cells. I couldn't find any alternative. Note that I would like to work in the Cell Script environment, so cell magic tricks are not viable (`%%script false --no-raise-error`).

1. Is this possible at all?
2. If not, could we have this feature?

To reproduce this, the easiest I found is this:

```py
#%%
# call `exit(0)` directly
exit(0)
print('exit(0) at top level')

#%%
# define `cell break` function
def cell_break():
    exit(0)

#%%
# call cell break function from a different cell
cell_break()
print('exit(0) in function')
```

### VS Code Version

Version: 1.74.0 (user setup) Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91 Date: 2022-12-05T16:38:16.075Z Electron: 19.1.8 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10.0.22621 Sandboxed: No

### Jupyter Extension Version

v2022.11.1003412109

### Coding Language and Runtime Version

Python 3.9.13+, IPython 8.5.0

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
thanks for filling this issue, unfortunately it's not possible to stop one cell and continue the next cell. all the code runs in a single process, hence you cannot stop execution in a process the way you have requested. unless u hanger misunderstood the question

you could instead just throw an exception then execution will halt completely.
calling `exit` will exit the process

alternatively you could check https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/runtools/readme.html whether this gives you what you need. if that's what your require please do file a separate issue with the details

sorry i wasn't and too provide a solution
