### ISSUE TITLE
disappearing buttons

### ISSUE THREAD

**Issue by gykovacs** [microsoft/vscode-jupyter#12402]
Type: <b>Bug</b>

1. Set up a typical Python data science workspace with jupyter ipykernel and the corresponding extensions.
2. Open a jupyter notebook in a tab, split the screen, and open some other text file (any file) on the right.
3. There are the usual buttons at the top of the jupyter notebook. As one clicks into the text file to the right, some jupyter buttons disappear, and one needs to click back into the jupyter pane to get back the buttons, and they come back slowely, one by one.

Extension version: 2022.9.1303220346
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.65GB (0.79GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/gykovacs/workspaces_clean/local_mcd --remote=wsl+Ubuntu-20.04 --crash-reporter-id 91d360e6-89b0-4fbc-a447-77185b89a52c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|Memory (System)|13.66GB (7.88GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|Memory (System)|13.66GB (7.88GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by gykovacs** [comment]
All I do is clicking between the left and right panes and the buttons at the top of the jupyter change.

![disappearing-buttons](https://user-images.githubusercontent.com/1881098/207595530-69a47d31-dd8a-4489-87b2-1200e52fd25c.gif)

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, please could you install the latest version of VS Code and the Jupyter extension and let us know whether this issue still repros for you

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
