### ISSUE TITLE
Jupyter Lab on SSH

### ISSUE THREAD

**Issue by bosoko** [microsoft/vscode-jupyter#12411]
Type: <b>Bug</b>

When running a Jupyter Lab instance on, say, AWS compute instance, I used to run a bash job and execute `python -m jupyter lab --no-browser ... ` command on it, which gave me a link to connect to, which I then copy-pasted into Specify Jupyter Server for Connections. 
In the latest update, the Specify Jupyter Server window has been changed, and is now caching the server information somehow, which causes the connection to fail unless I choose another server, remove the old one, restart VSCode and add it back. It's a lot of hassle.

Extension version: 2022.11.1003412109
VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.135-122.509.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HS with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.41GB (22.57GB free)|
|Process Argv|--crash-reporter-id cac6dc9e-4961-4a7d-83f1-28a40c171676|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Algotwo|
|OS|Linux x64 5.10.135-122.509.amzn2.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz (2 x 2499)|
|Memory (System)|7.66GB (5.98GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
3d0df643:30613357
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, I'm not entirely following you here when you say `and is now caching the server information somehow, which causes the connection to fail unless I choose another server`

Are you saying that it works the first time and when you re-load vscode it fails?

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
