### ISSUE TITLE
Option to Wrap Interactive Window Output

### ISSUE THREAD

**Issue by GitHunter0** [microsoft/vscode-jupyter#12414]
Hey folks, 

The Interactive Window is not wrapping the output, therefore the user has to frequently horizontal scroll to see the result, which is very painful...

As an example, see screenshot below:
![image](https://user-images.githubusercontent.com/26294221/208195118-0d70ce7a-bcd2-40c7-8d57-3f0f54ae4052.png)

Is it possible to configure the renderer to auto-wrap the output?

Thank you

PS: I have posted the issue in this [repo](https://github.com/microsoft/vscode-notebook-renderers/issues/140), but I think here is probably the right place.

**Comment by youurayy** [comment]
who is triaging this? (or should be)

there's already an option for it (previous versions were wrapping by default, introduction of the setting will change to no-wrap (which is a wrong way to introduce a new setting, by the way))

go to settings and search for "wrap":

![image](https://user-images.githubusercontent.com/588573/229291011-615658ac-a232-4b41-960f-c46b206273f0.png)

I needed to restart VSCode (the active window at least) for it to take effect.

/close

**Comment by GitHunter0** [comment]
@youurayy thank you, issue solved.
