### ISSUE TITLE
Breakpoints not hit when set in cells starting with by blank lines (and on other occasions)

### ISSUE THREAD

**Issue by kwikwag** [microsoft/vscode-jupyter#1242]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Create a Python file with cells, one cell - the first in the file - with function definition A, another cell with function definition B, and another cell which calls A and B. Have both A and B contain more than one line. 
2. Place breakpoints on more than one line in each function definition.
3. Perform any one of the following:

  - Add a space before the first cell in the file
  - Add code before the first cell in the file
  - Add a blank line to either of the cells with function definitions

4. Run Debug Cell on the cell with function calls.

e.g.

![issue-vscode-snippet-debug-cell-brakpoints-not-hit](https://user-images.githubusercontent.com/392199/90768065-dadd7480-e2f6-11ea-86d6-1ac509caba03.gif)

```python
import sys
# %%
def test():
    print(1)    
    print(2)

# %%
def test2():
    print(3)
    print(4)

# %%
test()
test2()
```

...and set breakpoints on all print() calls

## Actual behavior
Some or all of the breakpoints are not hit.

## Expected behavior
All breakpoints set should be hit on function calls.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.8.101144
-   **VS Code version:** 1.48.0 (system setup)
-   **Setting python.jediEnabled:** false
-   **Setting python.languageServer:** Microsoft
-   **Python and/or Anaconda version:** Python 3.7.4
-   **OS:** Windows | Mac | Linux (distro): Windows 10.0.19041 x64
-   **Virtual environment:** N/A (system Python)

## Python Output
I prefer not to.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by amunger** [comment]
this seems to be fixed and does not repro for me. Please re-open if you're still seeing this issue

**Comment by DonJayamanne** [comment]
yes i fixed this in the last iteration
