### ISSUE TITLE
Launching TensorBoard keeps on asking to install TensorBoard and PyTorch Profiler

### ISSUE THREAD

**Issue by dukecyto** [microsoft/vscode-jupyter#12420]
Type: <b>Bug</b>

In one of the AWS EC2 instances that I am Remote-SSHing into, I keep on getting the following dialog when launching :

```
TensorBoard >= 2.4.1 and the PyTorch Profiler TensorBoard plugin >= 0.2.0 are required. Would you like to install these packages?
```

Both dependencies are already installed in my conda environment.

When I hit "Yes" to the dialog, a shell opens to run `pip install -U torch-tb-profiler` but it just prints out "requirement already satisfied" for all depending packages. Nothing more happens.

When I hit "No" to the dialog, nothing more happens.

Let me note that I am struggling to reproduce this issue myself. On another EC2 instance, I get the same issue continually asking me to install tensorboard and torch-tb-profiler. However, on this instance, when I hit "No," I can go forward with selecting the folder to run the Tensorboard.

FYI, this is what I get when I directly run the command that the extension seems to be executing to check the torch-tb-profiler version:
```
$ conda run -n my-conda-env --no-capture-output python ~/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/get_output_via_markers.py -c "import torch_tb_profiler; print(torch_tb_profiler.__version__)"
>>>PYTHON-EXEC-OUTPUT
0.4.0
<<<PYTHON-EXEC-OUTPUT
```

Extension version: 2022.20.1
VS Code version: Code 1.74.2 (Universal) (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:26:09.430Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.13.0-1023-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|64.00GB (9.75GB free)|
|Process Argv|--crash-reporter-id b4ce0c20-914b-4f86-9588-9c2675a66ab0 --crash-reporter-id b4ce0c20-914b-4f86-9588-9c2675a66ab0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Session-e897163d-5244-487d-8d15-dc73df4ad687|
|OS|Linux x64 5.13.0-1023-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (48 x 2499)|
|Memory (System)|186.61GB (155.58GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723
vscup:30628656

```

</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, I'm sorry you are running into this.

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by dukecyto** [comment]
[Jupyter.log](https://github.com/microsoft/vscode-jupyter/files/10292043/Jupyter.log)
Looks like conda is not initialized in the shell invoked by the extension.

**Comment by DonJayamanne** [comment]
@dukecyto 
thanks for the logs and I'm sorry for not getting back to you any sooner.

Please could you install the latest VS Code insiders and the pre-release version of the Jupyter and Python extensions and test this out. Let me know if that still fails, and please do provide the logs for the same.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
