### ISSUE TITLE
"spawn /conda" does not use CONDA_PREFIX, resulting in ENOENT 

### ISSUE THREAD

**Issue by simopal6** [microsoft/vscode-jupyter#12430]
My installation:

```
Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:32:21.587Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No
```

I have a miniconda installation, which the Python extension (v2022.20.1) is able to see and use. However, when I try to run a Jupyter notebook, vscode prompts me to install the jupyter package, and then exits with the following error:

```
info 19:18:31.445: Process Execution: > /conda install -c conda-forge --name base jupyter -y
> /conda install -c conda-forge --name base jupyter -y
error 19:18:31.446: Error in execution Error: spawn /conda ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /conda',
  path: '/conda',
  spawnargs: [ 'install', '-c', 'conda-forge', '--name', 'base', 'jupyter', '-y' ]
}
```

To my understanding, it tries to run `/conda` (which of course doesn't exist). However, `$CONDA_PREFIX` exists in the terminal and is set to the correct path. If it were added before `/conda`, it would probably work.

So, how can I check why it's adding that leading slash and how to force it to use the correct prefix?

Thanks

**Comment by simopal6** [comment]
@karrtikr Thanks for your reply. I will try setting `python.condaPath`.

Anyway, I don't think it is a Jupyter-specific issue. The problem happened in this specific case because the Python extension tried to install Jupyter by running conda. It probably would have given the same error for any other package.

**Comment by karrtikr** [comment]
In that case please use the 'Python: Report Issue' command to open an issue on the Python extension, and make sure to include the logs.

**Comment by simopal6** [comment]
That's what I meant to do, but among all "Python: ..." commands in the palette, the "Report issue" one is missing.

**Comment by DonJayamanne** [comment]
@karrtikr We use the conda executable returned by Python extension, hence not sure what we're doing wrong here, I think this issue was prematurely moved to the Jupyter extension. Lets leave this here for now.

**Comment by DonJayamanne** [comment]
@simopal6 

Please could you install the latest pre-release version of the Jupyter extension.
& then please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by simopal6** [comment]
@DonJayamanne I actually already installed Jupyter from the command line. Is there any other operation I can perform that would elicit a call to conda from VSCode?

**Comment by DonJayamanne** [comment]
thanks, I'd like you to try out the pre-release version with vscode insiders, we fixed at least one issue with conda paths. is possible that fix will work for you too. 

if not please could you enable verbose logging and provide the logs as mentioned previously.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
