### ISSUE TITLE
Consider supporting python script cells (# %%) within script's if...main... block

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#1243]
Pulled from microsoft/vscode-python#11781 

It may be nice to make script cell blocks work within if __name__ == '__main__'. With Python scripts it's not ideal to have cells defined on the root because then it'll execute when imported. If you could define # %% cells within the if..main.. block then it would align close with best practices for Python

cc @Yura52, @earthastronaut

**Comment by earthastronaut** [comment]
@greazer I actually checked this out. This actually does work which is awesome!

```
# %%
def func(a=1):
   print("hello"*a)

if __name__ == "__main__":
    func()
    # %% 
    a = 3
    func(a)

    # %%
```
