### ISSUE TITLE
Nothing happen after clicking Jupyter: Specify Jupyter Server for Connections

### ISSUE THREAD

**Issue by HinnyTsang** [microsoft/vscode-jupyter#12441]
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Nothing happen after clicking `Jupyter: Specify Jupyter Server for Connections`. Vscode doesn't process anything after the command and nothing is shown in the jupyter lab server log.

#### Procedures to reproduce the problem

1. Click `Jupyter: Specify Jupyter Server for Connections` on the command palette.
2. Select `Existing`
3. Enter the URL of the local hosting Jupyter lab server, `http://localhost:8888/lab?token=<token>`
4. Enter the custom server name.
5. Restart vscode and choose the server added from `1`.
6. Nothing happing.

Version of Jupyter on remote server.
```
jupyter core     : 4.7.1
jupyter-notebook : 6.1.4
qtconsole        : 4.7.7
ipython          : 7.18.1
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 3.1.9
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.1.3
traitlets        : 5.0.5
```

### VS Code Version

1.74.1

### Jupyter Extension Version

v2022.11.1003412109

### Jupyter logs

```shell
[C 2022-12-23 10:44:29.621 ServerApp]

    To access the server, open this file in a browser:
        file:///C:/Users/hinnytsang/AppData/Roaming/jupyter/runtime/jpserver-4268-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/lab?token=cc596350b7793057c90a3a3f1beb1f2ede2f5cddd41578f0
     or http://127.0.0.1:8889/lab?token=cc596350b7793057c90a3a3f1beb1f2ede2f5cddd41578f0
D_Lib: debug printing for files [.*] and level [100] is turned on
D_Lib: debug printing for files [.*] and level [200] is turned on
D_Lib: debug printing for files [.*] and level [300] is turned on
4268:.../engine/vf_shex/vf_shex.cpp(91): INFO: DllCanUnloadNow returned S_OK.
[W 2022-12-23 10:44:34.611 LabApp] Could not determine jupyterlab build status without nodejs
```

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, & sorry you are running into it.

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.
