### ISSUE TITLE
Run 'MAIN' in Python Interactive Window

### ISSUE THREAD

**Issue by secj-eng** [microsoft/vscode-jupyter#1246]
# Feature: Interactive Window, Python Editor

## Description

In VSCode's Python extension, there is an option to right-click (or keyboard shortcut) in the editor and Run Current File in Python Interactive Window, which calls `python.datascience.runFileInteractive`. This works great, but it would nice to have an option to run a package's `main` file instead of just the file currently selected file in the editor.

While building a package/module and making changes in a non-main file, one currently needs to switch back to that main file editor tab before running it as described above.  It'd be nice to have a `python.datascience.run${Main}Interactive`, where you could specify `${Main}` along with a shortcut to execute it. Maybe a package specific variable? Thanks for the great work!  

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time.
