### ISSUE TITLE
ipynb Python cells always revert back to 2-space indentation

### ISSUE THREAD

**Issue by indirectlylit** [microsoft/vscode-jupyter#12465]
## Environment data

-   VS Code version:  `1.73.1`
-   Jupyter Extension version (available under the Extensions sidebar): `v2022.9.1303220346`
-   Python Extension version (available under the Extensions sidebar):`v2022.18.2`
-   OS (Windows | Mac | Linux distro) and version: `MacOS 13.1`
-   Python and/or Anaconda version: `Python 3.7.15`
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Docker image
-   Jupyter server running: Local

## Expected behaviour

Python cells should always use 4-space indentation once set

## Actual behaviour

Python cells revert to two-space indentation, requiring double-tabs and double-deletions to change indentation:

![2022-12-29 14 18 47](https://user-images.githubusercontent.com/2367265/210008347-48409590-9b21-4032-be6b-87cbf6784da2.gif)

The spacing reports 2 spaces:

![image](https://user-images.githubusercontent.com/2367265/210008411-6ff5a1f0-21a8-48f3-859f-ef5c4ddb21df.png)

I tried changing this value to 4 spaces, and also enabling auto-detection, but it always seems to be eventually reverted, and the setting does not seem to be shared across cells in any case.

This seems to follow `editor.tabSize` which I had set to 2 because that's what I use for most files. When switching to `4` the problem goes away.

I also tried adding ipynb to `.editorconfig` (with the editorconfig extension). However this did not work either:

```ini
[*]
charset = utf-8
indent_style = space
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.py,*.ipynb]
indent_size = 4
```

## Steps to reproduce:

set `editor.tabSize` to 2 and edit Python cells in ipynb notebook file

**Comment by rebornix** [comment]
We need to allow users to configure the tab/space size for notebook cells.

**Comment by roblourens** [comment]
Using 

```json
"[python]": {
        "editor.tabSize": 2,
}
```

in normal vscode settings works, right? Is this just an issue with the editorconfig extension? Do you have something else in mind @rebornix?

**Comment by indirectlylit** [comment]
thanks @roblourens – I wasn't aware that the python-specific tab size could be changed like that in the JSON settings file. This config achieves my goal of 2-space indentation by default and 4-space for Python:

```json
  "editor.tabSize": 2,
  "[python]": {
    "editor.tabSize": 4,
  },
```

Given that, barring further guidance from @rebornix or others, I think this issue can be closed. That said, a couple notes that might warrant follow-up:

1. I was not able to easily discover this setting. I tried searching the settings GUI for `python tabsize` expecting the setting to be exposed by one of the extensions and it wasn't. I assume there is documentation somewhere on JSON-only settings which I have not yet read? (e.g., is this `[language]: { settings }` pattern general to VSCode?)
2. It would be nice if editorconfig supported .ipynb notebook files, but I assume that's a separate issue
