### ISSUE TITLE
"Jupyter: Run Cells Above Current Cell" runs each cell 3 times

### ISSUE THREAD

**Issue by risaueno** [microsoft/vscode-jupyter#12471]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When I call "Jupyter: Run Cells Above Current Cell" (`jupyter.runallcellsabove.palette`) the interactive window shows each cell running 3 times, not just once as expected. 

This happens whether I use the keyboard shortcut or manually clicking from VSCode "show all commands" (see screenshots). This happens both locally and on a remote machine I connect to using Remote-SSH. 

![Screenshot 2022-12-30 at 17 57 09](https://user-images.githubusercontent.com/22602921/210099589-52f656e6-202f-4371-b7bd-e427b07b0059.png)
![Screenshot 2022-12-30 at 17 57 52](https://user-images.githubusercontent.com/22602921/210099588-81fa35d7-1b4e-4e9b-a6cb-e154096a5cb0.png)

### VS Code Version

Version: 1.74.2 (Universal)

### Jupyter Extension Version

v2022.11.1003412109

### Jupyter logs

```shell
info 17:59:26.818: ipykernel version & path 5.3.4, ~/opt/miniconda3/envs/bc/lib/python3.6/site-packages/ipykernel/__init__.py for /Users/risno/opt/miniconda3/envs/bc/bin/python
info 17:59:26.904: Got new session 0ce36080-36bf-4290-b0e2-d28c0e05a0f6
info 17:59:26.904: Started new restart session
info 17:59:26.904: Dispose Kernel process 13420.
info 17:59:26.940: UpdateWorkingDirectoryAndPath in Kernel
info 17:59:44.684: Generated code for 1 = <ipython-input-1-963935bb3827> with 4 lines
info 17:59:46.541: Generated code for 2 = <ipython-input-2-de19de053bc8> with 3 lines
info 17:59:46.693: Generated code for 3 = <ipython-input-3-de19de053bc8> with 3 lines
info 17:59:46.884: Generated code for 4 = <ipython-input-4-801d77656feb> with 3 lines
info 17:59:47.131: Generated code for 5 = <ipython-input-5-801d77656feb> with 3 lines
info 17:59:47.393: Generated code for 6 = <ipython-input-6-801d77656feb> with 3 lines
info 17:59:47.464: Generated code for 7 = <ipython-input-7-d2f06e104278> with 3 lines
info 17:59:47.545: Generated code for 8 = <ipython-input-8-d2f06e104278> with 3 lines
info 17:59:47.663: Generated code for 9 = <ipython-input-9-d2f06e104278> with 3 lines
```

### Coding Language and Runtime Version

Python v3.7.9

### Running Jupyter locally or remotely?

Remote

**Comment by amunger** [comment]
That is strange, but I'm not seeing this myself.

Have you seen any other run commands misbehaving like this?

**Comment by risaueno** [comment]
> Have you seen any other run commands misbehaving like this?
"Jupyter: Run All Cells" and "Jupyter: Run Current Cell and Below" seem to have the same behaviour. If it's just one line or one cell, it executes just once as expected. The problem seems to be when the command runs multiple cells at the same time.
