### ISSUE TITLE
Hide "Launch Tensorboard Session"

### ISSUE THREAD

**Issue by marcell-llerena** [microsoft/vscode-jupyter#12488]
Bug: 

VsCode version 1.74.2

Adding "python.experiments.optOutFrom": ["pythonTensorboardExperiment"] to user settings doesn't  hide "Launch Tensorboard session"

**Comment by DonJayamanne** [comment]
With the new tensoboard extension this will now be possible.

**Comment by DonJayamanne** [comment]
Closing this as you should be able to hide this by uninstalling the tensorboard extension.
