### ISSUE TITLE
Interactive Window improvements and issues

### ISSUE THREAD

**Issue by Yura52** [microsoft/vscode-jupyter#1248]
Hi! I tried to integrate notebooks-related functionality in my daily workflow. Not everything was smooth and I returned to JupyterLab in the end. However, the transition was very close to becoming successful, I really liked some features! I would like to share some feedback.

### High level impressions
I realized that "cells" within .py-files is the best form of a "Notebook" to me. Reasons:
- I get 100% of VSCode functionality (especially the editor)
- I have one and only one *interface* for code editing, regardless of what I am doing (writing C++ or drawing plots with Python in "Notebook")
- I can run ad hoc snippets in the interactive window without touching the original script
- I can seamlessly switch between running the script with the "python" command in the terminal and running it in the Interactive Mode without conversions from .py to .ipynb and vice versa
- I get clear diffs when VCS is involved
- everything else where .py is better at than .ipynb

In fact, all listed reasons can be compressed to one: "I strongly prefer .py files to .ipynb".

### Cells within .py
I mean the "# %%" thing that I praised above 😄 I had the following problems with it:
1. **Performance decreases over time**. I use VSCode to work on remote machine (not sure if it matters). After every (or so) kernel reloading the lag between my "shift+enter" and the VSCode's reaction (in the form of running the cell/selected code in the interactive window) becomes larger and larger up to 10 seconds (I needed to reload absolutely everything, VSCode included, in order to fix this). In other words, something was leaking, but I didn't understand, what exactly. Probably, the problem is there for Notebook Editor as well, but I spent less time with it, so I'm not sure.
2. No cells folding. I missed this feature from JupyterLab.
3. No shortcuts for operations within cells such as "go to the first line of cell", "select all the code within the cell" and so on.
4. No cell-level navigation. In JupyterLab, I can navigate between cells by exiting the editor mode (by pressing Esc) and using arrows. The functionality is not somewhat crucial, but some shortcut for traveling between cells would be nice to have.
5. No notebook-shortcuts (except for the "Shift+Enter"). Things like "Create a cell below" would make my life a bit easier.

In fact, only the first reason is a major blocker for me.

### Notebook editor
For now, I prefer JupyterLab for working with .ipynb, however, I spent some time with Notebook Editor and here are some things I would like to mention:
1. No "Go To Definition"
2. No multiple cursors across cells (I mean the "Cmd+D" thing).
3. No rulers
4. Color theme doesn't work properly (the dark theme I use ("1337") is automatically replaced with the native dark theme).
5. No brackets highlighting
6. No cells folding

1, 2, 3 and 5 seem to be caused by the same fact that the editor is different from the native VSCode editor.

### Common for both
1. I still don't understand how I can shutdown running kernels.
2. No shortcut for reloading the kernel (had to do that with the mouse 😄 ).

Software:
```
Visual Studio Code: 1.45.0
Python (VSCode extension): 2020.5.78807
python==3.7.7
jupyterlab==2.1.2
```

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by amunger** [comment]
looks like the majority of the requests here have been implemented except for @janosh's request for viewing RAM and disk usage, which we can make a separate issue
