### ISSUE TITLE
 response slowly，disconnect frequently

### ISSUE THREAD

**Issue by Chuan1937** [microsoft/vscode-jupyter#12486]
ADD ISSUE DESCRIPTION HERE

Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54
Embedder: codespaces

respond slowly today，and  disconnected  frequently。I think it's not due to my location,because it's fluent 2 days ago。today it absolutly disconnected。I can't open the files.

**Comment by roblourens** [comment]
Need more details- a screenshot might help

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
