### ISSUE TITLE
No IntelliSense in Jupyter Notebooks unless explicitly set python.languageServer to Jedi

### ISSUE THREAD

**Issue by skyeturriff** [microsoft/vscode-jupyter#12494]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

I have `python.languageServer` set to **Default**, without `pylance` installed, which it says should fallback to Jedi. I see the `Starting Jedi language server for default.` message in the Python output.

### Expected

IntelliSense support when working in Jupyter notebooks (code completion, quick info, etc.). On hover or when typing "." or Ctrl+space, code suggestions/documentation pop-ups, etc. should appear.

### Actual

No IntelliSense (barring that provided by the Jupyter kernel after code cells are run) unless I explicitly set `python.languageServer` to **Jedi**. On hover, or hitting Ctrl+space it reveals "No suggetions". After changing the setting to Jedi, I start to get code suggestions, documentation pop-ups, etc. inside `.ipynb` files again.

## Steps to reproduce:

`ms-python.python` v2022.18.2
`ms-python.vscode-pylance` not installed
`python.lanagugeServer` set to Default
`ms-toolsai.jupyter` v2022.9.1303220346
Using venv with python 3.9.12

1. Open empty project folder and activate venv
2. Execute command **Create: New Jupyter Notebook**; save
3. Use **Select Kernel** at top right of notebook to choose created venv
4. Being coding in code cell
5. Observe no code suggestions, doc pop-ups, etc. on hover or when hitting Ctrl+space, unless set language server explicitly to Jedi
![screencap](https://user-images.githubusercontent.com/14057112/206498753-4105d97e-62ad-44fa-9b27-66559e58b87b.gif)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.12
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Experiment 'pythonaacf' is active
Experiment 'pythonSurveyNotificationcf' is active
LSP Notebooks experiment is disabled -- not using Pylance
LSP Notebooks interactive window support is disabled -- not in LSP Notebooks experiment
> conda info --json
Python interpreter path: /usr/local/bin/python3
> ./venv/bin/python ~/.vscode/extensions/ms-python.python-2022.18.2/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.18.2/pythonFiles/interpreterInfo.py
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2022.18.2/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.18.2/pythonFiles/interpreterInfo.py
> /usr/local/bin/python3 ~/.vscode/extensions/ms-python.python-2022.18.2/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.18.2/pythonFiles/interpreterInfo.py
Starting Jedi language server for default.
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Jedi"

```

</p>
</details>

Extension version: 2022.18.2
VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (13.99GB free)|
|Process Argv|--crash-reporter-id c8a6657e-e7b2-438a-a4c5-cb11c85c922b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by EliCodesForFun** [comment]
Thanks for posting this. I couldn't get Intellisense to work for showing the parameters, specifically for Jupyter notebooks. I changed to Pylance and it works now.

**Comment by tmchartrand** [comment]
I'm having this issue too, was quite frustrating until I tracked it down! @karthiknadig the issue isn't with partial support from Jedi, the issue is with the 'default' language server setting, which as worded should behave identically to the 'jedi' setting if pylance is not installed, but is failing to fall back correctly. 

Oddly enough, I seem to also get jedi LSP results if the LSP is set to 'none', but not when set to 'default'!
