### ISSUE TITLE
More forceful interrupt?

### ISSUE THREAD

**Issue by austinmw** [microsoft/vscode-jupyter#12497]
Hi, I've noticed that the interrupt button often does not work, for example if I attempt to plot something large and then try to click interrupt, in many cases it will continue for several seconds and then display the plot.

I don't know the inner workings of this functionality so I assume it is working as intended, and maybe this question is naive, but is there any way to make the interrupt button more forceful?

**Comment by amunger** [comment]
This is likely something that would need to be implemented within the kernel, but I'll let @DonJayamanne comment.

**Comment by DonJayamanne** [comment]
@austinmw 
I'm assuming you are on a windows machine.
Interruping code on windows doesn't always work well, and interrupting code in Python + Jupyter is more complicated. As the python runtime that needs to monitor and handle the interrupt request could already be busy running some other code (hence interrupts might not always work).

Please could you provide more information when creating the issue (you skipped filling in the issue template). that helps us to better assist you, eg. i assume you are on windows - such info is captured in the issue template).

**Comment by austinmw** [comment]
@DonJayamanne Hi, I'm actually on a M1 MBP. I did fill out the template, but maybe I selected the wrong one (I selected feature request instead of bug, since my issue is something of a cross between question/feature request).

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by austinmw** [comment]
Thanks. I seem to be no longer able to reproduce the issue. Now when I click stop it stops immediately, so I'll close this for now.
