### ISSUE TITLE
enable "Toggle Cell Output Scrolling" like in native jupyter notebook

### ISSUE THREAD

**Issue by alexdauenhauer** [microsoft/vscode-jupyter#12496]
I think this is identical to https://github.com/microsoft/vscode-jupyter/issues/12122 but that one is closed and this feature does not exist to my knowledge. 

in Jupyter Notebook, you can toggle cell output scrolling so that large outputs still print, but you don't have to scroll for days to get to the next cell. Instead the output window has a scroll bar and you can scroll only the output. This would be a very nice feature to have since the current option is to have long outputs appear in a new editor window and this works for normal outputs, but is horrible for errors which get truncated and then you can't really read them in the new editor. 

![image](https://user-images.githubusercontent.com/11903445/211083192-efc4db45-04a0-4979-b4c9-a565ad5ee6ff.png)

**Comment by amunger** [comment]
tracking this in https://github.com/microsoft/vscode-jupyter/issues/4406

You can enable the experimental feature by adding `"notebook.experimental.outputScrolling": true` to your settings.json file

**Comment by alexdauenhauer** [comment]
@amunger when I add that setting it is grayed out signaling to me that it is not an option that exists. How do I enable it?

![image](https://user-images.githubusercontent.com/11903445/211095039-c2e5d46f-6ab8-4747-ae01-a12e7c60bdff.png)

**Comment by amunger** [comment]
it's expected to be grayed out since it's still experimental and undocumented. You'll need to reload vs code after adding the setting and then it will only affect cells where the content is long enough to need scrolling (instead of showing the `Output exceeds the size limit. Open the full output data in a text editor` message).

**Comment by alexdauenhauer** [comment]
ok great it is working now. Thank you for explaining to me how to work it

**Comment by miumer** [comment]
Is it possible to use a keyboard shortcut to focus on the scrollable output area and smooth scroll the output?

**Comment by amunger** [comment]
@miumer - please create a new issue for that feature request so it can be tracked independently

**Comment by Phlosioneer** [comment]
This confused me, so I'm including a comment here: The feature setting only applies a scroll bar to `print` based output (stdout and stderr). It doesn't add a scrollbar for last-line based output, like putting a large array on the last line.

**But** it removes the line length limit for both output types!!
