### ISSUE TITLE
If the cell runs for more than 60 seconds, an additional reminder will be given

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode-jupyter#12491]
In the process of using jupyter notebook, we can see the specific running time of the cell. 

I have an idea, if the running time of the cell is too long, such as more than 60 seconds, whether a reminder can pop up on the right side of the running time.

![image](https://user-images.githubusercontent.com/100815370/210688727-cae2b331-cba2-48db-aceb-f768de573ff4.png)

Is there a way to customize this function?
Thanks for any help.

**Comment by DonJayamanne** [comment]
Thanks for filing this feature request, given the fact that there haven't been any upvotes on this issue since it was open, I'm closing this.
