### ISSUE TITLE
Improve remote jupyter server CORS warning/error message prompt

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12507]
TODO:
* Provide ability for 3rd party Jupyter Server providers the ability to provide custom protocols for Web Sockets.

Other?

**Comment by DonJayamanne** [comment]
Improve UX in remote URL input for vscode.dev (able to copy url, etc)

**Comment by DonJayamanne** [comment]
The following UX needs to be improved
* The URL cannot be copied
* Error message with link is not where the validation error message is displayed (disconnected UX)
* Check with @TylerLeonhardt what can be done to add links (commands) to the validation error message

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/1948812/211681311-1aec8fd0-93d1-436e-8ddb-3aaceb3a145f.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/1948812/211681320-e3283bc2-6c06-4b84-a06b-d27d4213d94d.png)

**Comment by TylerLeonhardt** [comment]
> Check with @TylerLeonhardt what can be done to add links (commands) to the validation error message

That's tracked with https://github.com/microsoft/vscode/issues/82112

**Comment by DonJayamanne** [comment]
* [ ] Add ability to copy the URL if there is one in the error message
* [ ] Display a link for the URL in the error message
* [ ] Display a tooltip or the like for quick pick item `Install Python`
* [ ] Display a tooltip or the like for quick pick item that correspond to Conda environments without Python

**Comment by DonJayamanne** [comment]
Verification steps:
* Use VS Code insiders
* Go into kernle picker and select `Eixisting Jupyter Server`
* Attempt to add an invalid URL
* The error message should contain the URL and it should be a link that can be clicked.
