### ISSUE TITLE
Docs on browser notebook options

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#12518]
Docs on connecting to the following kernel options from the browser

**Comment by minsa110** [comment]
https://github.com/microsoft/vscode-docs/blob/somin/browser-nb-options/docs/datascience/jupyter-notebooks-browser.md

Not submitting PR yet since GH managed Juptyer server has a bug

**Comment by DonJayamanne** [comment]
Not sure we should mention Pyolity, it hasn't been updated for over a year, and has a lot of other limitations.
Either we update that and ensure its fully supported by us or mention it saying that there are some solutions that provide the aibility to run code in the browser or we Create an official implementation that is supported by us (I would have thought thats what we'd want to do if we want to document it(.

Else right now if we document this in our main docs and things don't work well it might not look too good to recommend an extension thats not updated/maintained and hasn't got the best support for kernels (variable viewer, plot viewer, data frame viedwer, debugging, widgets, etc).
