### ISSUE TITLE
Incorrect display of polars Dataframe in Variables view

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [microsoft/vscode-jupyter#12519]
## Environment data

-   VS Code version: 1.74.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.11.1003412109
-   Python Extension version (available under the Extensions sidebar): v2022.20.1
-   OS (Windows | Mac | Linux distro) and version: Windows 
-   Python and/or Anaconda version: 3.8.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda 
-   Jupyter server running: Local 

## Expected behaviour

The package polars (https://github.com/pola-rs/polars) is a very fast and solid python package seeing wider and wider adoption every day. When creating a polars DataFrame and clicking the "link" (see picture) I expect to be taken to a Data Viewer showing the columns and the underlying data.

![image](https://user-images.githubusercontent.com/44194839/211506298-3a6d9ee9-5279-4a51-bce1-9afd922a0e90.png)

I would expect it to be similar to the printed HTML in Jupyter:

![image](https://user-images.githubusercontent.com/44194839/211516086-346e4956-79b0-413b-980c-5ff33c8d1739.png)

## Actual behaviour

There are multiple problems:

- A index column is added even though Polars doesn't have index
- Columns are imported as rows
- Column names are not used
- I can't show list and struct types are not respected and just showed as object

![image](https://user-images.githubusercontent.com/44194839/211506949-00350270-1286-4b4f-a5f8-fd7d092de043.png)

## Steps to reproduce:

1. Install polars: `pip install polars` 
2. Create new notebook with the Jupyter extension
3. Create a polars DataFrame:
```pytohn
import polars as pl

df_pl = pl.DataFrame({
    "int_col": [1,2,3],
    "str_col": ["abc","def","ghi"],
    "list_col": [[1],[1,2],[1,2,3]],
    "struct_col" : [
        {"x":1, "y":2},
        {"x":3, "y":4},
        {"x":5, "y":6}]
    })
```
4.  Go to "JUPYTER: VARIABLES" and click link for data viewer

**Comment by shiosai** [comment]
Similar issue **without a notebook** when having an active debug session: In *Run and Debug* -> *VARIABLES* right-click on a DataFrame in the variables view and then `View Value in Data Viewer`

**Comment by datenzauberai** [comment]
This happens because VSCode does not check the fully qualified name and tries to handle the `polars.DataFrame` just like a `pandas.DataFrame`. A workaround is to alias the `to_pandas` method with `toPandas` on the `polars.DataFrame`. See https://stackoverflow.com/a/76432740/11064332

**Comment by datenzauberai** [comment]
@roblourens I added a PR that would fix this.

**Comment by datenzauberai** [comment]
A quick follow-up regarding the limitations of the fix. It only converts the data frame to Pandas before displaying (the same tactic used for Spark data frames) and therefore cannot work around limitations of Pandas functionality.

- An index column will still be displayed 😢
- Columns are no longer imported as rows ✅
- Column names are now displayed correctly ✅
- list types are displayed correctly ✅
- struct types are still displayed as object 😢

**Comment by MarcoGorelli** [comment]
@datenzauberai alternatively, for now, would something like
```python
        elif _VSCODE_builtins.hasattr(df, "to_pandas"):
            try:
                df = df.to_pandas(use_pyarrow_extension_array=True).iloc[start:end]
            except Exception:
                df = df.to_pandas().iloc[start:end]
```
work? That would preserve the struct type at least

**Comment by datenzauberai** [comment]
> ```python
> use_pyarrow_extension_array=True
> ```

Nope, that would still display as object in the data viewer ☹️
