### ISSUE TITLE
[Feature Request] add setting to adjust Markdown text font size

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#1251]
## Environment data

- VS Code version: 1.30.2
- Extension version: 2018.12.1
- OS and version: Windows 10

The font size for Markdown text in the Python Interactive tab is a bit too small to read. I wish there could be a setting to adjust the default font size for the text independently from code font size in the editor.

![image](https://user-images.githubusercontent.com/33796896/51360885-7a8fac80-1a9b-11e9-820f-f296be1459e8.png)

**Comment by StevenLi-DS** [comment]
Will this issue be addressed in the native notebook UI. The markdown texts are just way too small.

**Comment by DonJayamanne** [comment]
Thanks for filing this suggestion, I'm going to close this in favor of the upstream issue https://github.com/microsoft/vscode/issues/123149
As we're now using the VS Code native UI and output styles are controlleed in VS COde (specially markdown).
