### ISSUE TITLE
Connecting to kernel: Python 3.9.7... loading to infinity

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12529]
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/12526

<div type='discussions-op-text'>

<sup>Originally posted by **leskovecg** January 11, 2023</sup>
When I start Interactive window loading goes to infinity. How can I solve this issue? 

![napaka](https://user-images.githubusercontent.com/62363084/211669311-21b6d7d6-23c9-49fd-8eda-6c6a88ef19cd.png)
</div>

**Comment by DonJayamanne** [comment]
@leskovecg 
Sorry you are running into this issue, 
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by abhirajD** [comment]
@DonJayamanne 
I am running into the same issue.

Attaching the logs.

[debug.txt](https://github.com/microsoft/vscode-jupyter/files/10414689/debug.txt)

**Comment by leskovecg** [comment]
I solved the problem by myself. I just reinstalled jupyter extension. Hope it will work for others.

**Comment by DonJayamanne** [comment]
@abhirajD @leskovecg 
The logs uploaded are incomplete.
Please could you:
* Reload VC Code
* Close all files in VS Code
* Reload again
* Open one notebook and run one cell in that one notebook
* Wait for a few minutes
* Then copy all of the output from the `Jupyter` output window and upload that here.

**Comment by DonJayamanne** [comment]
@leskovecg @abhirajD 
Please could you install the latest pre-release version of the Jupyter extension and provide the same logs
We have fixed a few issues and also identified some issues with python packages (and have added additional logging to identify these).

Thanks for your patience and sorry that you are still running into this.

Open the extensions page, search for Jupyter and click the button `Switch to Pre-Release Version`  
Similarly please install the `Pre-Release` version of the Python extension.

<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
