### ISSUE TITLE
"Run all cells" ignores exceptions

### ISSUE THREAD

**Issue by logan-pugh** [microsoft/vscode-jupyter#1252]
I noticed there is a difference in behavior between running all cells in a notebook in Jupyter Lab/Notebook and VS Code: when an exception is raised in Jupyter Lab/Notebook, subsequent cells do not run. In VS Code, all cells run regardless of whether any exceptions were raised.

I am sure the former is the correct behavior so can this be considered a bug in the VS Code Python extension? I also see that VS Code itself is adding native notebook support so perhaps this will be addressed in that but I wanted to be sure this issue was recorded somewhere.

I've also verified the same behavior in the latest VS Code Insiders (1.47.0).

Thanks!

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
