### ISSUE TITLE
Cannot import modules from other folders, even if included in Workspace Folder

### ISSUE THREAD

**Issue by Laxzal** [microsoft/vscode-jupyter#12530]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I opened VSCode Jupyter Notebook and saved an ipynb file in the folder DMPNN.

This ipynb uses a kernel called `arc_env`

In the workspace called DMPNN, I added the three folders:
- ARC
- RMG-Py
- RMG-databse

I changed my workspace settings with this line:
`"jupyter.notebookFileRoot": "${workspaceFolder}"`

Now, when I try to run the following cell
```cell
from arc.rmgdb import *
```

I receive the error `ModuleNotFoundError: No module named 'arc'`

![image](https://user-images.githubusercontent.com/56573970/211778028-18853277-b060-4bc1-8da6-d39140db73d4.png)

### VS Code Version

1.74.2

### Jupyter Extension Version

v2022.11.1003412109

### Jupyter logs

```shell
info 12:12:23.374: Disposing kernel .jvsc74a57bd0a8e45e6ea0d065fb717d160fb5d287a0349dfeff0060689ffcf9b9b81111ffd2./home/calvin/mambaforge/envs/arc_env/python./home/calvin/mambaforge/envs/arc_env/python.-m#ipykernel_launcher for notebook /home/calvin/Code/DMPNN/generate_molecules.ipynb due to selection of another kernel or closing of the notebook
info 12:12:23.375: Dispose Kernel '/home/calvin/Code/DMPNN/generate_molecules.ipynb' associated with '/home/calvin/Code/DMPNN/generate_molecules.ipynb'
[I 12:12:23.387 NotebookApp] Kernel shutdown: 7f06dafb-5287-4495-9569-4c1452484046
info 12:12:28.004: Attempting to start a server because of preload conditions ...
info 12:12:28.506: Got env vars with python /home/calvin/mambaforge/envs/t3_env/bin/python, with env var count 112 and custom env var count 0 in 1ms
info 12:12:32.982: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0a8e45e6ea0d065fb717d160fb5d287a0349dfeff0060689ffcf9b9b81111ffd2./home/calvin/mambaforge/envs/arc_env/python./home/calvin/mambaforge/envs/arc_env/python.-m#ipykernel_launcher (Python Path: /home/calvin/mambaforge/envs/arc_env, EnvType: Conda, EnvName: 'arc_env', Version: 3.7.15 (default, Nov 24 2022, 21:12:53) 
[GCC 11.2.0]) for '/home/calvin/Code/DMPNN/generate_molecules.ipynb' (disableUI=false)
[I 12:12:32.984 NotebookApp] Creating new notebook in 
info 12:12:33.009: installMissingDependencies /home/calvin/mambaforge/envs/arc_env/bin/python, ui.disabled=false for resource '/home/calvin/Code/DMPNN/generate_molecules.ipynb'
info 12:12:33.010: Got env vars with python /home/calvin/mambaforge/envs/arc_env/bin/python, with env var count 112 and custom env var count 0 in 1ms
info 12:12:33.016: Process Execution: > ~/mambaforge/envs/arc_env/bin/python -c "import ipykernel"
> ~/mambaforge/envs/arc_env/bin/python -c "import ipykernel"
info 12:12:33.089: Spec argv[0] updated from '/home/calvin/mambaforge/envs/arc_env/bin/python' to '/home/calvin/mambaforge/envs/arc_env/bin/python'
info 12:12:33.090: Got env vars with python /home/calvin/mambaforge/envs/arc_env/bin/python, with env var count 112 and custom env var count 100 in 1ms
[I 12:12:33.109 NotebookApp] Kernel started: a917a3a0-805c-4a0b-9f02-a01bca983583, name: pythonjvsc74a57bd0a8e45e6ea0d065fb717d160fb5d287a0349dfeff0060689ffcf9b9b81111ffd2
[W 12:12:33.117 NotebookApp] delete /generate_molecules-jvsc-2bbc6612-6b68-491d-8aec-9c143b620a1bf7a505a7-f609-44bd-9b06-71d0a2c8244e.ipynb
info 12:12:33.450: Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd0a8e45e6ea0d065fb717d160fb5d287a0349dfeff0060689ffcf9b9b81111ffd2./home/calvin/mambaforge/envs/arc_env/python./home/calvin/mambaforge/envs/arc_env/python.-m#ipykernel_launcher
info 12:12:33.451: UpdateWorkingDirectoryAndPath in Kernel
info 12:12:33.767: Cancel all remaining cells true || Error || undefined
```

### Coding Language and Runtime Version

Python 3.7.15

### Language Extension Version (if applicable)

v2022.20.1

### Running Jupyter locally or remotely?

Local

**Comment by kfir4444** [comment]
I am having a similar issue

**Comment by DonJayamanne** [comment]
@Laxzal 
Since I dont have the code, please could you try the following at your end
* Create a python file named `/home/calvin/Code/DMPNN/generate_molecules.py` or similar and add the same code that you have in the notebook
* Open the terminal in VS Code
* Activate your environment in the terminal
* Run the python file `/home/calvin/Code/DMPNN/generate_molecules.py`

& let me know if this works, my guess is that this fails as well. Hence closing this as a duplciate of https://github.com/microsoft/vscode-jupyter/issues/12531

If this is not the case then please feel free to re-open this issue or ping me here and I'll re-open this issue.

**Comment by Laxzal** [comment]
Hey @DonJayamanne 

Following your instructions, I created the file and ran the code in VSCode terminal and was able to run it. 

![image](https://user-images.githubusercontent.com/56573970/212134766-cf62d01b-67b9-4800-b113-793ca6be94ab.png)

![image](https://user-images.githubusercontent.com/56573970/212134874-4646d32f-3143-4eee-9bf4-fd19effce7ef.png)

**Comment by DonJayamanne** [comment]
Thanks, will check this out.

**Comment by DonJayamanne** [comment]
@Laxzal 
Looking at your code I don't see the arc folders
Please could you share more information on the files and paths

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
