### ISSUE TITLE
Installing ipykernel requires admin on Windows

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1253]
Steps to repro:
1. Create venv
1. Switch to it
1. Switch on raw kernel support
1. Run interactive window
1. Follow install prompts
1. Expect kernel to start

Kernel actually fails with an import dll load failure when importing the win32api package.

This is because the installer for pywin32 needs admin rights.

**Comment by DonJayamanne** [comment]
This should already be fixed for the following scenario
`Using windows store version 3.7 or earlier.`

**Comment by DonJayamanne** [comment]
**Testing**
See the issue on top (contains steps for repro https://github.com/microsoft/vscode-jupyter/issues/1253#issue-742809117)
