### ISSUE TITLE
Interactive window stuck with Python 3.11.1

### ISSUE THREAD

**Issue by Ocsidot** [microsoft/vscode-jupyter#12539]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1- Create a new ipynb file
2 - Open it on VsCode
3 - UI is continuously running and I cannot create code nor markdown

I have activated the logging to verbose but nothing is displayed in the Jupyter console

### VS Code Version

1.74.3

### Jupyter Extension Version

v2022.11.1003412109

### Coding Language and Runtime Version

Python 3.11.1

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
Sorry about not getting around to this issue. Is this still occurring for you on the latest version of vs code? Can you provide a gif or screenshot to show the behavior you are seeing?

Closing for now since this issue is quite old, but let us know if you're still having problems with notebooks.
