### ISSUE TITLE
Unable to pass auth headers for WebSockets in vscode.web

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12534]
Create a custom jupyter server behind a custom authentication
The URL auth works by passing the auth headers, however the WebSockets do not authenticate appropriately.

Solution: Need the ability to pass protocols in the WebSocket ctor.

**Comment by rzhao271** [comment]
Hi @DonJayamanne, what are some steps to verify this issue?

**Comment by DonJayamanne** [comment]
Marking as verified, as a separate (internal) extension has been able to verify this works as expected.
