### ISSUE TITLE
Kernel selection prompt is stuck when mru kernel picker type is turned on

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#12536]
1. Navigate to vscode.dev (ensure Jupyter extension is NOT installed)
2. Open a remote repo
3. Add `"notebook.kernelPicker.type": "mru"` to settings.json
4. Open a notebook
5. Click "Select Kernel"
6. Stuck on this:
![image](https://user-images.githubusercontent.com/10833267/211936450-2d8d82cf-4e43-4294-ba68-c97c73735af5.png)

cc/ @rebornix

**Comment by DonJayamanne** [comment]
The mru setting is now stable, and given the fact that we haven't seen similar issues in the past I'm closing this as fixed.
