### ISSUE TITLE
Failed to change kernel: Kernel Python 3.10.9 is not usable.

### ISSUE THREAD

**Issue by johnfoneill** [microsoft/vscode-jupyter#12549]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I'm unable to connect to the Kernel.  As I try to execute a cell in a notebook, VS Code tries to connect 5 times to the Kernel and then fails.  I've ported code working on an older Macbook to a new Macbook Pro M1.  I'm having problems configuring the correct version Python in VS Code / Jupyter.  I've set the Kernel to use Python 3.10.9 but can see the 3.8 being used.

I've missed a configuration VS Code / Jupyter somewhere and cannot seem to find the issue from the errors.
[jupyter.log](https://github.com/microsoft/vscode-jupyter/files/10427922/jupyter.log)

I've run the notebook file from the command line `jupyter notebook` and it starts and runs well.

### VS Code Version

Version: 1.74.3 Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534 Date: 2023-01-09T17:05:47.808Z Electron: 19.1.8 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Darwin arm64 22.2.0 Sandboxed: Yes

### Jupyter Extension Version

v2022.11.1003412109

### Jupyter logs

```shell
Visual Studio Code (1.74.3, undefined, desktop)
Jupyter Extension Version: 2022.11.1003412109.
Python Extension Version: 2022.20.2.
```

### Coding Language and Runtime Version

Python 3.10.9

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment]
> I've run the notebook file from the command line jupyter notebook and it starts and runs well.

when you do this please could you run the following code in a Jupyter notebook and let me know what you get
```python
import sys
print(sys.executable)
print(sys.version)
```

>  I've set the Kernel to use Python 3.10.9 but can see the 3.8 being used.

Looks like `/usr/local/bin/python` is your Python 3.8 env and `/usr/local/bin/python3` is your Python 3.10.9 env.
Please could you confirm this.
Right now 3.8 is used to start Jupyter. 
Before we make further changes I'd like to get the output from Jupyter when you run it from the terminal.

**Comment by johnfoneill** [comment]
Hi Don - Thank you for you fast response.

> when you do this please could you run the following code in a Jupyter notebook and let me know what you get
> 
> ```
> import sys
> print(sys.executable)
> print(sys.version)
> ```

**I built a test notebook with the 3 lines above and got a similar response as I did from my original execution...  I've attached the response here**
[rerun-test.txt](https://github.com/microsoft/vscode-jupyter/files/10439336/rerun-test.txt)


> Looks like /usr/local/bin/python is your Python 3.8 env and /usr/local/bin/python3 is your Python 3.10.9 env.

Correct.

> Before we make further changes I'd like to get the output from Jupyter when you run it from the terminal.

I've attached the terminal response here.  
[terminal_output.txt](https://github.com/microsoft/vscode-jupyter/files/10439351/terminal_output.txt)

**Comment by DonJayamanne** [comment]
I think you misunderstood something

**Comment by johnfoneill** [comment]
I absolutely did mis-read your ask... and your explanation was very clear, sorry.

```
> import sys
> print(sys.executable)
> print(sys.version)
```
**Output**
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3
3.10.9 (v3.10.9:1dd9be6584, Dec  6 2022, 14:37:36) [Clang 13.0.0 (clang-1300.0.29.30)]

**Comment by johnfoneill** [comment]
@DonJayamanne Is there anything more you need?  Did I answer your question?

**Comment by DonJayamanne** [comment]
Hmm, looks like Python 3.8 env is unable to launch kernels, 
Please could you:
* Open VS Code
* Select the command `Jupyter: Select Interpreter to Start Jupyter Server` from the command palette
* From the quick pick, please select your `/bin/python3 (Python 3.10.9)` environment
* If prompted to install some Jupyter related dependencies then please do so
* After that is done, please re-load vscode
* Try running a cell once again

**Comment by johnfoneill** [comment]
Fixed.
