### ISSUE TITLE
Problem reconnecting to jupyter notebook

### ISSUE THREAD

**Issue by KBlansit** [microsoft/vscode-jupyter#12540]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Hard to reconnect jupyter notebook when the notebook is shut off (due to server disconnection etc). Possibly a problem in storing tokens or cookies.

### VS Code Version

Version: 1.74.3 (Universal)

### Jupyter Extension Version

v2022.11.1003412109

### Running Jupyter locally or remotely?

None

**Comment by KBlansit** [comment]
I get a problem when entering in my password (I have a jupyter config of a static password) and my notebook will give an error from VS code saying I cannot connect to notebook due to bad password, and my notebook will show forbidden.

![image](https://user-images.githubusercontent.com/6611182/212167771-abab44fc-28a4-45b8-8294-1489965e9c28.png)


However, when I disable and then reenable jupyter extension in the extension tab, it will then work flawlessly.

**Comment by DonJayamanne** [comment]
> Hard to reconnect jupyter notebook when the notebook is shut off (due to server disconnection etc). Possibly a problem in storing tokens or cookies.

> I get a problem when entering in my password (I have a jupyter config of a static password) and my notebook will give an error from VS code saying I cannot connect to notebook due to bad password, and my notebook will show forbidden.

These two seem to be separate issues. 
Please could you confirm they are separate issues and if so, please could you file them separately.
If they are the same, then the problem seems to be specific to having a Jupyter server that was started and has a static password, is that correct.

**Comment by KBlansit** [comment]
> If they are the same, then the problem seems to be specific to having a Jupyter server that was started and has a static password, is that correct.

Yes, this is correct. My specific set up uses a static password for my notebook server. I remember VS code asking me for a password (which I entered in correctly), but I would get the error (on the notebook side) in the top screen shot.

That said, I have not tested this specific workflow of a non-static password. Tomorrow I can probably try replicating it without a static password if it would help isolate the problem.

**Comment by DonJayamanne** [comment]
@KBlansit I believe this issue has been resolved, please could you install the laetst pre-relase version of Jupyter exteniosn into VS COde insiders and let me know how this goes?

**Comment by benjamin83a** [comment]
Hi, i am a newbie, i installed VS code today, as soon as i run a cell and it runs for more than a minute i get the message "reconnecting to the kernel tensorflow (Python 3.10.10)". I spent hours looking on the web how to solve this but I am completely lost, I am not familiar with all these installs of coding stuff..

**Comment by dokutoshi** [comment]
@benjamin83a install the pre-release version. This suggestion per @DonJayamanne solved my issue. 
> Hi, i am a newbie, i installed VS code today, as soon as i run a cell and it runs for more than a minute i get the message "reconnecting to the kernel tensorflow (Python 3.10.10)". I spent hours looking on the web how to solve this but I am completely lost, I am not familiar with all these installs of coding stuff..
