### ISSUE TITLE
Timeout waiting for kernel should have a better error message

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1254]
Whenever we fail to launch a kernel (whether raw or jupyter) we should make the kernel stderr (or jupyter stderr) more prevalent.

We consistently get bugs from customers about this sort of thing and if they could find the error in our output they might be able to fix the problem themselves.

**Comment by greazer** [comment]
Let's at least make the message more actionable for the user.

**Comment by joyceerhl** [comment]
Validated with a busted kernel: 

![image](https://user-images.githubusercontent.com/30305945/104361567-77cbc480-54c7-11eb-8d09-27aa87f7d7a6.png)
