### ISSUE TITLE
Code does not run on this platform but runs on other platform

### ISSUE THREAD

**Issue by harshagarwal2245** [microsoft/vscode-jupyter#12557]
Type: <b>Bug</b>

For python Getting np.memory.error() while trying to execute code in vs code but same code gets execute in jupyter notebook

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.25272
Modes:
Sandboxed: Yes

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

Please could you also verify you have selected the same Python environment in both Jupyter as well as Jupyter Notebook extension in VS Code.
* Optionally please could you run the following code in Jupyter notebook and let me know what you get
```python
import sys
print(sys.executable)
```

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
