### ISSUE TITLE
Environment Selection bar disappeared in Interactive Window

### ISSUE THREAD

**Issue by elvissey1984** [microsoft/vscode-jupyter#1255]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Open VS Code
2. Ctrl+Shift+P, Python Interactive Window

## Actual behavior
The bar that shows current kernel/environment flashes as interactive window launches, and then completely disappears.

## Expected behavior
In the Interactive Window, on top of control buttons, there used to be a bar that shows current kernel/environment, which you can click on and switch if needed.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local 
-   **Extension version:** 2020.9.111407
-   **VS Code version:** 1.49.2
-   **Setting python.jediEnabled:** true | false
-   **Setting python.languageServer:** Jedi | Microsoft | None
-   **Python and/or Anaconda version:** 3.6.10 64-bit
-   **OS:** Windows 10 1909
-   **Virtual environment:** virtualenv

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by greazer** [comment]
This has been fixed
