### ISSUE TITLE
Remove unwanted/unused entries from package.nls.json files

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12562]
With the use of the new localization engine code (VS Code API), we no longer need the duplicate entires in the package.nsl*.json files.
We should remove items that are no longer referenced within the package.json file or other place.

E.g.
`products.installingModule` is not used in package.json and not used anywhere in code either. Hence this can be removed.
`capabilities.untrustedWorkspace.description` is used in package.json for commands, hence cannot be removed

**Comment by nikodemas** [comment]
I can take it, please assign it to me :)
