### ISSUE TITLE
[BUG] Cannot render image files in markdown blocks

### ISSUE THREAD

**Issue by jnooree** [microsoft/vscode-jupyter#12568]
The current release of this extension has trouble rendering markdown blocks with image file(s).

Related versions:

- OS: macOS arm64 22.2.0
- VSCode v1.74.3
- Jupyter v2022.11.1003412109

**Comment by amunger** [comment]
I can repro - I'm seeing Error rendering output item using 'vscode.markdown-it-renderer' in the html of the preview

**Comment by amunger** [comment]
Currently putting together a new version of the Jupyter Notebook Renderers extension to get this fixed.

**Comment by roblourens** [comment]
If this is fixed, please make sure you give it a type and a milestone
