### ISSUE TITLE
kernel selection 

### ISSUE THREAD

**Issue by Jacques2101** [microsoft/vscode-jupyter#12585]
- VS Code Version:  1.74.3 (Universal)
- OS Version: MacOS 13.1 

This a new problem and I do not know why it happens. When I launch vscode I do not have kernel as usual (I use Jupyter notebook). I don't know what's happened ????
when I click on "select kernel" I have an empty data that appears in the menu

I cannot use vscode anymore !!!

Thx for your help

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by Jacques2101** [comment]
I don't know why but now it is working. I do nit know why...

**Comment by DonJayamanne** [comment]
thanks for getting back, lets just close this issue.
