### ISSUE TITLE
Data Viewer doesn't show unique values when dataframe has duplicate column names

### ISSUE THREAD

**Issue by jvanelteren** [microsoft/vscode-jupyter#12583]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I made a dataframe with multiple identical column names (not good practice of course, but I did it). When using the data viewer, it shows the values of the last identical column for all of the columns.

    import pandas as pd
    test = pd.DataFrame(([10,20,30, 40],), columns=['same','same', 'same', 'different'])

This displays as:

    0, 30, 30, 30, 40
Expected:

    0, 10, 20, 30, 40

Regular displaying the dataframe in the interactive notebook does work as expected, this is only the Data Viewer.

### VS Code Version

Version: 1.74.3 (system setup) Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534 Date: 2023-01-09T16:59:02.252Z Electron: 19.1.8 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10.0.19044 Sandboxed: No

### Jupyter Extension Version

v2022.11.1003412109

### Coding Language and Runtime Version

Python 3.11.0

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
closing as the jupyter data viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486
