### ISSUE TITLE
Feature request: allow widgetScriptSources other than jsdelivr.com and unpkg.com

### ISSUE THREAD

**Issue by danvk** [microsoft/vscode-jupyter#12598]
I have a custom set of Jupyter widgets that I've developed for my project. They work great in the Jupyter notebook web viewer.

When I try to display them in the VS Code Notebook viewer, however, I get this message:

<img width="568" alt="Screenshot 2023-01-20 at 3 54 44 PM" src="https://user-images.githubusercontent.com/98301/213809032-f730dead-47d2-422f-a848-ffbede2ebc8f.png">

and a blank output. I believe the issue is that my widget's `extension.js` file looks like this:

```js
const url = 'https://mywebsite.com/dist/public/my-widget.bundle.js';
const {head} = document;
const script = document.createElement('script');
script.type = 'text/javascript';
script.src = url;
head.appendChild(script);
```

(See [this question](https://stackoverflow.com/questions/62943410/can-an-ipywidget-source-its-javascript-from-a-url-rather-than-local-disk) for more on why I'm doing it this way, but the gist is that it makes it possible for my coworkers to use the widget without having to build it themselves.)

It makes a ton of sense from a security perspective that there's a narrow set of domains allowed. I'd like to add my own domain to this list. The [linked page][1] says that `jupyter.widgetScriptSources` "can be configured", but so far as I can tell it can only be shrunk to a _subset_ of `["jsdelivr.com", "unpkg.com"]`. You can't add arbitrary domains:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/98301/213811338-6882af36-0dfe-4a09-8df3-b78b28b759e1.png">

I'd like to be able to do this. If that's possible, great! If not, consider this a feature request.

If it's relevant, I'm using the Jupyter extension in a remote workspace via SSH.

Possibly related: #4246

[1]: https://github.com/microsoft/vscode-jupyter/wiki/IPyWidget-Support-in-VS-Code-Python

**Comment by DonJayamanne** [comment]
Thanks for the feature suggestion, I believe this would be possible 
However the widget script (*.js) file would have to be accessible via the following URL:
`http://mywebsite.com/{packageName}@{moduleVersion}/dist/index.js`

E.g. if the widget name is `email_widget` and version is `0.1.0`
then the URL would be as follows
`http://mywebsite.com/email_widget@0.1.0/dist/index.js`

**Comment by DonJayamanne** [comment]
Similar requests in the past include https://github.com/microsoft/vscode-jupyter/issues/5192

**Comment by DonJayamanne** [comment]
Closing this issue as out of scope, we haven't had enough upvotes on this issue

**Comment by hendrickmelo** [comment]
I see the out of scope marking. I'm curious to know where this issue would be considered to be in scope. How many up votes is enough to keep it open? This is a constant annoyance for us. Essentially prevents us to use any of our notebooks that rely on custom widgets.
