### ISSUE TITLE
Not seeing errors

### ISSUE THREAD

**Issue by austinmw** [microsoft/vscode-jupyter#12595]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

After updating my VS Insiders version I am no longer seeing notebook error tracebacks. I've disabled all extensions besides Jupyter and Python. I just see a circled X with no output.

Screenshot:
![image](https://user-images.githubusercontent.com/12224358/213756125-63e18a45-e42b-4899-a871-c9aea0d2e571.png)

### VS Code Version

Version: 1.75.0-insider (Universal) Commit: 9ccc2b3b30c122afe45bc6722bef0e3901fb2806

### Jupyter Extension Version

v2023.1.2000202160

### Jupyter logs

No text in output panel. 

### Coding Language and Runtime Version

Python v3.9.6

### Language Extension Version (if applicable)

Python v2023.1.10181031

### Running Jupyter locally or remotely?

Occurs when running either local or remote

**Comment by amunger** [comment]
looks like the Jupyter extension error renderer is no longer showing anything, you can click the "change presentation" button to switch over to vscode's built-in error renderer
<img width="352" alt="image" src="https://user-images.githubusercontent.com/2019016/213785787-eb835b72-83d8-44cc-bcfe-2ca23b703c72.png">


@rebornix - Did you already complete the work to merge the error renderers? Is it expected that Jupyter's is still in that list?

**Comment by thomasaarholt** [comment]
I can reproduce the error but not @amunger's suggested fix:

https://user-images.githubusercontent.com/2721423/213877921-f93bdc8a-d1a0-4898-ad85-685d36c15e69.mov

**Comment by amunger** [comment]
@thomasaarholt - you have both a regular output and an error output below it. The `</>` in your capture corresponds to the error output - try clicking that one to select the alternative error renderer.

**Comment by austinmw** [comment]
The alternative, non-default renderer (`application/vnd.code.notebook.error`) seems to work. Also I want to note that the button clicking placement for the `</>` symbol seems to be off in my IDE (it is very hard to click on)
