### ISSUE TITLE
Add contextual help into Jupyter extension

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#12597]
Add the following features from the [Jupyter PowerToys](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-powertoys&ssr=false#overview) extension as a part of the main Jupyter extension:
- ~Kernel management~
- Jupyter contextual help

**Comment by DonJayamanne** [comment]
> Jupyter contextual help

We need to be very careful adding this feature, possibly make this an opt in feature
See here for issues reported by at least 2 users https://github.com/microsoft/vscode-jupyter-powertoys/issues/40

**Comment by minsa110** [comment]
+1 on being careful adding these features, and making sure known bugs and issues are addressed before moving the feature over to the Jupyter extension. The feature seems beneficial to our user workflows, as evidenced by these issues and comments:
- https://github.com/microsoft/vscode-jupyter/issues/1307
- https://github.com/microsoft/vscode-jupyter-powertoys/issues/57
- ![image](https://user-images.githubusercontent.com/10833267/214081450-a588801b-edf2-40a6-814e-eaa9122b6ba4.png)

It's also one of the most beloved features mentioned for JuptyerLab in tutorials and customer conversations.

**Comment by DonJayamanne** [comment]
@minsa110 I'm closing this issue.
I think what would work is, to bring this feature request up for issue planning or the like with @rebornix and then we can add this into an iteration.
Closing this for now as this isn't part of any iteration

**Comment by DonJayamanne** [comment]
Using this issue https://github.com/microsoft/vscode-jupyter/issues/1378
to track the feature request for`Add kernel management `

**Comment by Fred-Wu** [comment]
Would it be easier to implement the contextual help by creating a new window after typing ?fun or help(fun) such as how vscode-R does? 

At the moment, it appears as an overview until one clicks on "open in a text editor" to see the full. This is how I use the help for most of the time now. 

<img width="907" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/4111978/88157391-902a-4fae-a435-e59c61232a0a">

Would be useful to automatically open it in the new editor window, and with some highlights.
