### ISSUE TITLE
Test DataScience with Python 3.9

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#1259]
RC is published so seems like a good time to kick the tires on this for us.

Via Steve:

> The release candidate of Python 3.9 is ready! This is the time to test your packages and fix anything so you can have wheels ready for your users on release. (While we can't guarantee nothing will break between now and 3.9.0 final, we can guarantee that you'll be happier that we fixed it rather than left it broken.)
>  
> 
> 
> You can download Windows and macOS installers from https://www.python.org/downloads/release/python-390rc1/ or at \\pytools\Python\CPython\v3.9.0rc1 (including some official but unreleased ARM64 packages and side-loadable MSIX packages for Windows).
>  
> On Ubuntu, use the deadsnakes PPA to install precompiled builds (soon).
>  
> (Discussion to the post in the General channel)

**Comment by greazer** [comment]
Pretty sure this is working by now
