### ISSUE TITLE
Tabs change automatically to running jupyter notebook or second interactive window

### ISSUE THREAD

**Issue by entron** [microsoft/vscode-jupyter#1260]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Open two jupyter notebooks nb1.ipynb and nb2.ipynb in tab1 and tab2 respectively.
2. Let nb1.ipynb run through all cells.
3. While nb1.ipynb is still running and updating the outputs of each cell choose the nb2.ipynb tab
4. When nb1.ipynb has new updated cell output VScode will change to the nb2.ipynb's tab automatically.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Remote
-   **Extension version:** 2020.8.101144
-   **VS Code version:** 1.48.0
-   **Setting python.jediEnabled:** true | false
-   **Setting python.languageServer:** Jedi | Microsoft | None
-   **Python and/or Anaconda version:** 3.8.3
-   **OS:** Darwin x64 16.7.0
-   **Virtual environment:** conda 

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by kennysong** [comment]
Yeah, this is disruptive when I run a long process in one notebook and switch to another to continue working.

It's also caused me to make edits in the wrong tab.

**Comment by greazer** [comment]
This won't be a problem in native VS Code notebooks. But it remains a problem for the interactive window.

**Comment by StevenLi-DS** [comment]
@greazer Could you guys please consider adding a toggle for this? 

This also happens for interactive windows tab as well. It's a bit annoying when you try to run something in the background while editing another file or use vscode as a image viewer.

**Comment by arthurflor23** [comment]
A toggle would be perfect :)

**Comment by joyceerhl** [comment]
The new native interactive window no longer does this.
