### ISSUE TITLE
Not correctly handling print flushes in the Interactive Window or Jupyter Notebook

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#1261]
Reported by a customer on StackOverflow here:
https://stackoverflow.com/questions/62612738/any-way-to-get-jupyter-in-vscode-to-flush-the-buffer

Looks like we are not handling the flush correctly. We append each character after the next. In Jupyter each new character replaces the previous one.

![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/3daa9a98-88e1-4328-9ac7-aa8958c31d54)

**Comment by greazer** [comment]
I believe this has been fixed by now.
