### ISSUE TITLE
Better guidance for default python environment on Ubuntu

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#12610]
On Ubuntu (tested on 20.04 and 22.04), when users open the kernel picker the very first time, users will get two options "Python environments..." and "Existing Jupyter Server..."

<img width="603" alt="image" src="https://user-images.githubusercontent.com/876920/214114161-c27ebe41-4b27-406b-ac5e-0150e44d33b7.png">

In "Python Environment..." quick pick, we commend the Python environment shipped with Ubuntu

<img width="592" alt="image" src="https://user-images.githubusercontent.com/876920/214114263-9e5ead39-5c80-40fd-a3bb-2d6a3e2435ac.png">

As it's recommended, users will likely to pick this environment. Then users try to run the cell, we will prompt to install `ipykernel`. However it will fail immediately as there is no `pip`.

<img width="506" alt="image" src="https://user-images.githubusercontent.com/876920/214114442-24468d05-20a1-4361-b15b-132ab6854137.png">

We might want to improve this by

* either avoid recommending this environment, showing some sort of warning that pip is missing
* or automatically install missing pip and then other packages (`ipykernel`)

**Comment by rebornix** [comment]
IIRC we used to have issues with default Python on macOS. If that's still true, we should probably not recommend it too. In both cases we might want to recommend users to use "Create Python Environment".

**Comment by DonJayamanne** [comment]
@rebornix can you open the Python Interpreter quick pick from the command `Python: Select Interpreter` and check what the recommended/selected interrpeter is in there. if its the same, then the problem lies with python extension and we can move this issue there.

**Comment by rebornix** [comment]
It shares the same root cause as https://github.com/microsoft/vscode-python/issues/20543 I guess.

**Comment by DonJayamanne** [comment]
Closing as out of scope,
