### ISSUE TITLE
On opening an existing notebook with widget fallback output to a different mimetype

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12611]
On opening an existing notebook with widget fallback output to a different mimetype if an ipywidget needs an active kernel connection
Refs: #8635

- [x] web @rebornix 
- [x] anyOS @amunger 
- [x] anyOS @roblourens  

Complexity: 5

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%238635%0A%0A&assignees=DonJayamanne)

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2312611%0A%0A&assignees=DonJayamanne)

---

### Requirements

- Install prerelease jupyter extension into VS Code (desktop or http://insiders.vscode.dev)
- Have a python environment that you can run jupyter from. (https://jupyter.org/install)
- Be familiar with jupyter notebooks
- Have ipywidgets installed into your python environment using the command `python -m pip install ipywidgets`
- Install matplot lib `pip install matplotlib ipympl`

### Setup
* Run a cell with the following code
```python
%matplotlib widget

from matplotlib import pyplot as plt

fig, ax = plt.subplots()
ax.plot([0,1,2], [2,3,4] ,"o-")
```
* Verify the widget is rendered and you can interact with the widget using the controls in the output (such as panning, zoom, etc)
* Close the notebook and re-open the notebook
* Verify you can still see a plot (this time its not interactive)
* Re-load VSCode and open the same notebook and you should still see the plot displayed (though its not interactive)
*

**Comment by roblourens** [comment]
Does this work by redirecting the interactive renderer to a primitive one? Because it says it's rendering the ipywidget when I guess it's actually rendering a png
<img width="404" alt="image" src="https://user-images.githubusercontent.com/323878/214358145-7bbdf870-417f-4352-89eb-4ffbc9c86dd8.png">

It works as described but it seems backwards that you would tell me you are using an interactive renderer when that is not the case

**Comment by roblourens** [comment]
Btw regarding the complexity on this, I feel that it would be complexity 5 for other team members, but for the manually assigned people, it is not difficult to verify :)
