### ISSUE TITLE
Interactive Window backed by SimpleNotebookEditorModel

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12613]
Refs: microsoft/vscode#163377

- [x] macOS @roblourens
- [x] linux @roblourens 
- [x] windows @joyceerhl

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2312613%0A%0A&assignees=amunger)

---

The notebook within the Interactive Window now uses the `SimpleNotebookEditorModel` which delegates content retrieval to the file system service and a new `filesystemProvider`.

### Requirements

- Jupyter and python extensions installed
- A python interpreter/virtual environment that IPython can be installed into
- Select a python interpreter to use with the Interactive Window with `Python: Select Interpreter`

### Testing
* Run/Debug some python code in the interactive window:
  * Open a python file and execute code into the Interactive Window, either through `# %%` cells or the `Run Current File in Interactive Window` command
  * Run the command `Create Interactive Window` and use the input box to execute code
* Run code that will throw an error from a saved python file and check that the callstack is correct
  * you may need to switch presentation to see the errors https://github.com/microsoft/vscode-jupyter/issues/12595
* Enable the setting interactiveWindow.restore and reload vscode to check if the Interactive Window is restored properly (the kernel will be reset, but it should still contain the previously executed cells)

**Comment by eleanorjboyd** [comment]
blocked by[ this bug](https://github.com/microsoft/vscode/issues/172273)

**Comment by connor4312** [comment]
I'm blocked by the same issue Eleanor hit

**Comment by eleanorjboyd** [comment]
@amunger, not sure about the practice here- please close the issue if that is correct move but I wasn't sure given Connor and I didn't get to actually test your feature change.

**Comment by roblourens** [comment]
Usually if testing wasn't actually completed, we'd say you can leave the box unchecked and the TPI open

**Comment by roblourens** [comment]
This worked for me, I tested it
