### ISSUE TITLE
Kernel selector spins after reloading VS Code with IW restore enabled

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#12629]
Testing #12613

It looks like this is because kernel detection is happening, which is a bit strange to see given I already had a kernel preselected
<img width="519" alt="image" src="https://user-images.githubusercontent.com/30305945/214396002-f3b23e8d-02be-4727-95aa-0bdc0e79b8d7.png">

**Comment by amunger** [comment]
There might be an issue for this already, but it's just a general behavior for kernel picker/discovery

**Comment by DonJayamanne** [comment]
@joyceerhl does the spinning stop? if not thats a bug.
Else its normal for the kernel detection to take place after reloading, basically we refersh the list of kernels everytime we re-load vscode even if you already have something pre-selected.

Again if the spinning does not stop, thats a bug, so please feel free to re-open this issue.
