### ISSUE TITLE
Jupyter Hub for bad certs can not detect bad cert situation

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1262]
With a bad root cert, this can happen:

![image](https://user-images.githubusercontent.com/19672699/86062253-23766100-ba1d-11ea-8283-ac52281e1999.png)

We can detect this case and ask the user if they want to allow it anyway. (We do this for other cert errors)

**Comment by DonJayamanne** [comment]
Users haven't run into this hence closing this issue
