### ISSUE TITLE
External links in cell output don't work

### ISSUE THREAD

**Issue by crazy4pi314** [microsoft/vscode-jupyter#12621]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Open a new notebook ([demo](https://gist.github.com/crazy4pi314/964280b54de1096fd9f04259b1552e61)), and execute the following print statement in a code cell:
`print("https://www.github.com")`

The cell output has the link, and is highlighted as if it was an active link. I would expect the link to be clickable if I hold the ctl (windows) key as I hover, but this does not work. It seems to be just differently colored text that has to be copied and pasted out of the cell output. This holds for both the notebook output and the interactive output if the cell is in a py file.

Also if you have the same link in a markdown cell it works fine.

### VS Code Version

Version: 1.74.3 (system setup) Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534 Date: 2023-01-09T16:59:02.252Z Electron: 19.1.8 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10.0.22621 Sandboxed: No

### Jupyter Extension Version

v2022.11.1003412109

### Jupyter logs

```shell
info 15:56:06.650: Restart kernel execution
info 15:56:06.650: Restart requested file:///c%3A/Users/skais/OneDrive/Desktop/link-bug.ipynb
info 15:56:06.651: Restarting af1863d8-e719-4bf7-abf0-d592f3a45a99
info 15:56:06.652: Got env vars with python c:\tools\Anaconda3\python.exe, with env var count 76 and custom env var count 0 in 1ms
info 15:56:06.658: Process Execution: > c:\tools\Anaconda3\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> c:\tools\Anaconda3\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 15:56:06.718: Got env vars with python c:\tools\Anaconda3\python.exe, with env var count 76 and custom env var count 0 in 2ms
info 15:56:06.719: Got env vars with python c:\tools\Anaconda3\python.exe, with env var count 76 and custom env var count 0 in 3ms
info 15:56:06.729: Process Execution: > c:\tools\Anaconda3\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"74475002-4dec-4eb8-bca9-083a85ac2d68" --shell=9007 --transport="tcp" --iopub=9009 --f=c:\Users\skais\AppData\Roaming\jupyter\runtime\kernel-v2-395800eAD5JjGRt05V.json
> c:\tools\Anaconda3\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"74475002-4dec-4eb8-bca9-083a85ac2d68" --shell=9007 --transport="tcp" --iopub=9009 --f=c:\Users\skais\AppData\Roaming\jupyter\runtime\kernel-v2-395800eAD5JjGRt05V.json
info 15:56:06.729: Process Execution: cwd: ~\OneDrive\Desktop
cwd: ~\OneDrive\Desktop
info 15:56:07.332: ipykernel version & path 5.1.4, ~\AppData\Roaming\Python\Python37\site-packages\ipykernel\__init__.py for c:\tools\Anaconda3\python.exe
info 15:56:07.515: Kernel Output: To connect another client to this kernel, use: --existing c:\Users\skais\AppData\Roaming\jupyter\runtime\kernel-v2-395800eAD5JjGRt05V.json

info 15:56:07.593: Got new session a7873a4c-4465-415d-a8fb-bed472ab95c1
info 15:56:07.593: Started new restart session
info 15:56:07.594: Dispose Kernel process 397624.
info 15:56:07.620: UpdateWorkingDirectoryAndPath in Kernel
```

### Running Jupyter locally or remotely?

Local

**Comment by roblourens** [comment]
You shouldn't have to hold a key- since this is html content you can just click the link. This works for me.

**Comment by crazy4pi314** [comment]
Yeah that is what I expected, but it originally didn't do anything if I just clicked without holding control. Revisiting this in the current version (see below) it seems to work in notebooks both in code cell outputs and markdown cells. I think some of the issue might have been the mime type of the cell output, and I'll re-open if I can find out what the mime type was for the cells that didn't work before.

```
Version: 1.77.2 (user setup)
Commit: e344f1f539a80912a0e9357cec841f36ce97a4e2
Date: 2023-04-06T10:08:05.978Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```
