### ISSUE TITLE
Show progress for kernel restart

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#12625]
When I restart the kernel, I am not sure where to look for its progress. I know I can go to the `Output` panel for detailed output, but I usually don't have that open because I have other tabs open like the Jupyter Variables or Terminal. It just would be nice to show a progress bar or something similar when I restart the kernel.

A few suggestions for consideration:
1. Animated indicator on the kernel indicator to something like ![image](https://static.wikia.nocookie.net/clubpenguin/images/9/94/LAB.gif/revision/latest/scale-to-width-down/20?cb=20150519024435) `Restarting <kernel>` 
2. Animated indicator on the `Restart` button like ![image](https://static.wikia.nocookie.net/clubpenguin/images/9/94/LAB.gif/revision/latest/scale-to-width-down/20?cb=20150519024435) `Restarting...`

**Comment by DonJayamanne** [comment]
This looks like a regression, we had progress indicators for kernel start and restarts,
