### ISSUE TITLE
python 2 is the only kernel detected and attempts to use python 3 have failed

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-jupyter#12626]
Testing #2508

in insider's with `"notebook.kernelPicker.type": "mru",`

here's what I see (note the terminal for my python 3 path) and settings file attempting to get this to work manually

![Screenshot 2023-01-24 at 9 32 42 AM](https://user-images.githubusercontent.com/29464607/214375847-92d3a213-b019-418b-8596-d5fbe51fa1c8.png)

**Comment by DonJayamanne** [comment]
Closing as stable version of extension was installed into insiders.
