### ISSUE TITLE
Interactive window prompts to save before closing

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#12638]
Testing #12613

Have an interactive window, run cells in it, then try to close. I get prompted to save unsaved changes (which is surprising in and of itself), but clicking save just dismisses the window instead of what I'd expect (open system file dialog with option to save the file). 

![image](https://user-images.githubusercontent.com/30305945/214440292-d9bbcf3b-cdaa-4066-9ba7-c3d753de2c43.png)

**Comment by amunger** [comment]
@joyceerhl - does this repro for you every time? I can't get it to happen. Do you see a dirty indicator on the tab?

**Comment by joyceerhl** [comment]
Yes I do see a dirty indicator. Honestly not entirely sure how I got into this state. Maybe related to the IW restoring following a window reload?

**Comment by joyceerhl** [comment]
Oh wait, I just reproed it. 
![image](https://user-images.githubusercontent.com/30305945/214443268-ca86bfdd-401f-46e4-95b2-29b6954aa086.png)


1. `Jupyter: Create Interactive Window`
2. Reload with restore enabled
3. :bug: a second editor appears, and that one is marked dirty and will trigger the save dialog when closed
