### ISSUE TITLE
Deleted venv still shows after refreshing kernel list

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12633]
Testing microsoft/vscode#172103

1. Create a venv in the workspace
2. run a cell with that venv kernel
3. reload vscode
4. delete the venv through file explorer (windows)
5. refresh the kernel picker
🐛 kernel is still listed

**Comment by DonJayamanne** [comment]
@amunger please could you test this again and provide the logs
* Also let me know what env was removed/created
* Please provide the two logs, before and after reloading, & after clicking on refreshing (you might want to clear the logs before you hi the refresh button)

**Comment by amunger** [comment]
no longer repro's, and seems to refresh itself without needing to manually click refresh
