### ISSUE TITLE
Add Markdown formatting for help commands in Jupyter extension

### ISSUE THREAD

**Issue by Falven** [microsoft/vscode-jupyter#12649]
Currently, when working in an .R file in VS Code with the R extension, help commands are opened in a nicely formatted Markdown window, making the whole help text legible in the format it was intended to be read in.

Currently, it truncates the output and prints strange symbols.

It would be great if this functionality could be brought over to the Jupyter extension as well, so that help commands in Jupyter notebooks can also be displayed in a readable format.

```R
require(ISLR)
?Smarket # Help command
```

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
