### ISSUE TITLE
Detected project namespace not in sync if notebook is not in root folder

### ISSUE THREAD

**Issue by ibestvina** [microsoft/vscode-jupyter#12646]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Changes to the names are not recognized for imported modules if the notebook, if the notebook is not located in the same folder as the imported module.

As an example, we have two files: `module.py` is in the root workspace dir and contains line `x = 'Hello'`, and`notebook.ipynb` contains a cell with `from module import x`.

If `x` is renamed to `y` in `module.py`, the line in the notebook is properly underlined as a detected "unknown import symbol" (even without running the notebook, but running the notebook in general is not important in this issue). Changing the line in the notebook to `from module import y` removes the error.

However, if the notebook is in a subfolder, this does not work, even when the Notebook root folder is set to `${workspaceFolder}`. To replicate:

1. Create the files as described above, putting the notebook in a subfolder and setting the Notebook root folder to the workspace folder.
2. Run the cell (this is important since the names seem to sync after the first run, but not later when the notebook is restarted):
<img width="966" alt="image" src="https://user-images.githubusercontent.com/10189206/214645830-cedebcde-a85d-4b53-862c-9878b1d658f0.png">
3. Change the name in the module. The name change is not recognized in the notebook, even after restart.
4. Changing the name in the notebook raises a warning, even though this cell works. The warning stays even after running the cell.
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/10189206/214646533-79753c20-466d-4058-b96c-670221665f85.png">
5. Reverting the name back to `x` in the notebook removes the warning, even though the cell does not work now. Even after trying to run this cell, the warning is not there:
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/10189206/214647032-1e142aa8-32b7-4d79-9962-652ee86405aa.png">

I am not sure if this is even a Jupyter extension problem - I don't know which component handles these warnings. Please advise if I should move this issue elsewhere.

### VS Code Version

1.74.3 (Universal)

### Jupyter Extension Version

v2022.11.1003412109

### Jupyter logs

```shell
[Nothing seems to happen in the output since nothing needs to run for this problem to arise.]
```

### Coding Language and Runtime Version

Python 3.10.9

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing thi s issue, unfortunately this is a feature request, the Python language server isn't aware of the changes that need to be made to the CWD based on the settings.

Out of curiosity why do you place notebooks in a sub directory and then expect imports to work. I mean whats the reason for this. is it to structure the code better, and have tests and the like in a separate directory.
Also, do you use any other tool other than vscode for running these notebooks, if you do then how do you run such notebooks and ensure the imports work there as well.

I'm trying to understand the uses cases for setting up a separate CWD for notebooks when they are executed.

**Comment by ibestvina** [comment]
Thanks for the info!

Re. the reasons why notebooks are in a separate folder, I usually do this to store testing/experimentation/showcasing notebooks used during the development of the main module. So, if developing module `my_module`, I would have the following structure:

```
root/
├─ my_module/
│  ├─ implementation.py
├─ lab/
│  ├─ showcase_some_feature.ipynb
│  ├─ new_idea.ipynb
```
Of course, this is done for private projects - in the public ones, I use normal package imports in the notebooks, but when privately developing something, it is cumbersome to have to build/install the package I'm developing constantly as I am changing it, to propagate the new features to the notebooks.

To make the imports work in these notebooks when using normal Jupyter, I simply append the root dir to my python path (`sys.path.append("..")`) at the start of each notebook. If I ever decide to publish a package, then I simply remove that line, and expect users to properly install the package to be able to import it.

In VSCode, I do not need that line, as I can change the notebook root folder in the settings by setting it to `${workspaceFolder}`.

I was wondering, since the namespace is detected correctly when the notebook first starts, is it possible to trigger this sync manually somehow? I do not mind running some command when I make changes to the implementation, but it is a bit inconvenient to have to restart VSC every time to get everything to sync.

**Comment by DonJayamanne** [comment]
Unfortunately this issue hasn't received any upvotes, hence closing this issue.
