### ISSUE TITLE
Notebook outline: disable symbol?

### ISSUE THREAD

**Issue by thangckt** [microsoft/vscode-jupyter#12644]
Dear developers,

Is there any way to hide the symbol "M !" in the heading of the Outline of jupyter notebook file? I think it will be better for visualization.

![](https://user-images.githubusercontent.com/46436648/211773997-178c7d13-3d4f-4772-8ff7-05be63560146.png)

**Comment by thangckt** [comment]
I make a simple .ipynb file, and it shows a weird outline

![image](https://user-images.githubusercontent.com/46436648/216683549-3f48441c-87b5-49ee-a995-032f3afa1001.png)

**Comment by DonJayamanne** [comment]
Closing this as out of scope, haven't had any upvotes nor have we have similar issues

**Comment by thangckt** [comment]
I found many people have face this issue #147007
