### ISSUE TITLE
I created 2 docker container jupyter kernels and only one showed up on reload

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-jupyter#12647]
Testing microsoft/vscode#172094

<img width="657" alt="image" src="https://user-images.githubusercontent.com/2644648/214418188-72993152-5684-48e8-98df-468f659a01c7.png">

I used @rebornix's https://marketplace.visualstudio.com/items?itemName=rebornix.vscode-jupyter-docker-stack-connect to create these containers.

Could it be because they have the same name `Python (ipynb)`?

**Comment by DonJayamanne** [comment]
@rebornix do we need  to do anything here?

**Comment by DonJayamanne** [comment]
This is a known issue, however given the fact that no one else has reported this issue with this 3rd party extension, I'm closing this as not planned for Jupyter ext.
