### ISSUE TITLE
How to install kernel in VS code

### ISSUE THREAD

**Issue by AftabHaider680** [microsoft/vscode-jupyter#12651]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
If you are working on Python , then you do not need to install a Python kernel all you need is
* Install Jupyter extension
* Install Python extension
* Install a Python runtime (preferably conda or the like)
* Go into the kernel picker and select a Python environment
* You will be prompted to install some dependencies, click ok
* You can now run code against these Python environments


If you are working on Non-Python code
* Install the kernel based on the documentation of the corresponding kernel you are interested in, see here for more information https://docs.jupyter.org/en/latest/install/kernels.html. See docs for installing Julia, R kernels
* Install the Jupyter extension
* Go into the kernle picker and select the corresponding kernel, such as Julia or R or other
* Run the code against this kernel

Hope this was helpful.
The latest version of VS Code insiders and pre-release version of teh Jupyter extension has an improved kernel picker with more links to documentation explaining the above.

**Comment by DonJayamanne** [comment]
@AftabHaider680 as a suggestion questions such as these are perfect candidates for the [Discussions](https://github.com/microsoft/vscode-jupyter/discussions) sections, as those would help others with similar questions as well.
