### ISSUE TITLE
Jupyter Notebook Don't save automatically even on autosave after delay enabled

### ISSUE THREAD

**Issue by goyal-aman** [microsoft/vscode-jupyter#1265]
Issue Type: <b>Bug</b>

Create a new jupyter notebook (using ctrl+shift+p and select create new jupyter notebook), startworking on it but new changes made on the notebook are not saved. Though I expect it to be saved. But If I close and reopen the notebook it works fine.

PS : I cannot be sure if its python extention issue of  Vscode.

Extension version: 2020.5.86806
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by momt99** [comment]
Also not working in 'onFocusChange' mode. Really annoying when you close vscode and you open it and see that your notebook is not saved automatically and a lot of work is gone.

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
