### ISSUE TITLE
After workspace has been trusted and Python API reigstered, then refresh list of interpreters

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12661]
List of interpreters needs to be refreshed after Python API has been registered so we get the latest interprtetersx

When testing https://github.com/microsoft/vscode-python/issues/20261 
we need to click the refresh button in the kernel picker to get the list of python envs displayed in the kernel picker after trusting a workspace folder, this should not be necessary.

**Comment by sbatten** [comment]
@DonJayamanne I am trying to verify this but based on the steps in the previous issue, it seems like I am supposed to select the venv before trusting the workspace but I cannot do anything before trusting the workspace. Maybe you can provide steps for this issues specifically.

**Comment by DonJayamanne** [comment]
@sbatten 
* Please install the latest pre-release (had to make some more changes at our end)
* Open an untrusted workspace
* Go into kernel picker and go into Python envs, that should be empty
* Trust the workspace
* Go bakc into kernel picker and then into Python Envs
* This should show up with a list or start loading (progress indicator should be visible)

**Comment by sbatten** [comment]
It was pretty instant so I didn't see the progress indicator, but I suppose it worked
