### ISSUE TITLE
Use @vscode/vsce instead of vsce

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12663]
* Ensure this is done in all related repos
* [x] Gather
* [x] Renderers
* [ ] Keymaps
* [x] Powertoys
* [x] Jupyter extension

**Comment by 2022H1030042G** [comment]
Hi, I would like to work on this issue, is it available?

**Comment by DonJayamanne** [comment]
Yes it is

**Comment by 2022H1030042G** [comment]
Could you give some more information about the issue, like what needs to be done and where exactly the changes are required? I am new to open source contribution, it'd be great to have some help. Thanks.

What I understood is that I have to replace "vsce" with"@vscode/vsce" in the above mentioned repositories. Some more insight would be helpful.

**Comment by DonJayamanne** [comment]
The npm package vsce needs to be replaced with @vscode/vsce

**Comment by 2022H1030042G** [comment]
Where is this package "vsce"?, I am unable to find it.

**Comment by TylerLeonhardt** [comment]
No assignee so I'm moving this out

**Comment by DonJayamanne** [comment]
Done
