### ISSUE TITLE
How to get the results of a cell or execSelectionInteractive in other extension?

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12690]
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/12672

<div type='discussions-op-text'>

<sup>Originally posted by **ShuguangSun** January 29, 2023</sup>
In case that we send a piece of code via jupyter.execSelectionInteractive, the code      is shown in the cell and result printed below. Is it possible to get the result via a command?</div>

**Comment by amunger** [comment]
It isn't currently, although may be able to change that command to return the resource URIs for the newly created cell.

You can use the [vscode API](https://code.visualstudio.com/api/references/vscode-api#workspace) to access the notebook and cells within the Interactive Window - `workspace.notebookDocuments`, though you'd have to find the uri of the notebook (e.g. interactive-1.interactive).

**Comment by amunger** [comment]
closing for lack of interest/votes.
