### ISSUE TITLE
Better handling of (error) output

### ISSUE THREAD

**Issue by skwde** [microsoft/vscode-jupyter#12699]
Currently we can only set `"notebook.output.textLineLimit"` to show more lines of the cell output.

This applies to both, errors and standard ouptut.

It is fairly inconvenient to look at the truncated error messages. Also opening them in a separate window is of no help because their is no formatting.

It would be good to have a second option next to `"notebook.output.textLineLimit"`, something like

```
"notebook.output.errorLineLimit"
```

which can also be set to `0` or `-1` to display the entire error trace.

**Comment by amunger** [comment]
scrollable outputs and the copy output command should help resolve this.
