### ISSUE TITLE
Identify flaky kernel failures

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12695]
https://github.com/microsoft/vscode-jupyter/actions/runs/4046696969/jobs/6961281827

[logs.txt](https://github.com/microsoft/vscode-jupyter/files/10539919/logs.txt)

**Comment by rebornix** [comment]
We are seeing kernel execution failures in most commits, but it happened randomly in one or two jobs for each commit.

https://github.com/microsoft/vscode-jupyter/actions/runs/4129835142/jobs/7135882416
https://github.com/microsoft/vscode-jupyter/actions/runs/4129835142/jobs/7135882954
https://github.com/microsoft/vscode-jupyter/actions/runs/4129778341/jobs/7135764945
https://github.com/microsoft/vscode-jupyter/actions/runs/4121601311/jobs/7117450687
https://github.com/microsoft/vscode-jupyter/actions/runs/4121601311/jobs/7117451229
https://github.com/microsoft/vscode-jupyter/actions/runs/4108679057/jobs/7089656295
https://github.com/microsoft/vscode-jupyter/actions/runs/4089263227/jobs/7051778639

**Comment by roblourens** [comment]
Were these fixed by https://github.com/microsoft/vscode-jupyter/pull/12838 or is that something else?

**Comment by DonJayamanne** [comment]
Something else
I will look into these during debt week

**Comment by DonJayamanne** [comment]
We no longer have flay tests
