### ISSUE TITLE
Bug: Notebook Editor, Interactive Window, Python Editor does not work with diff

### ISSUE THREAD

**Issue by harvastum** [microsoft/vscode-jupyter#1270]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Select two .ipynb files from explorer
2. Right click, select "Compare Selected" from context menu

## Actual behavior
Two diff panels open up for a split second, then close.
## Expected behavior
The diff panels show up and allow user to inspect files.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:**  N/A
-   **Extension version:** 2020.5.80290
-   **VS Code version:** 1.45.1
-   **Setting python.jediEnabled:** true 
-   **Setting python.languageServer:** Jedi | Microsoft | None
-   **Python and/or Anaconda version:** 3.6.1 (but it's irrelevant)
-   **OS:** Windows 10
-   **Virtual environment:** N/A 

## Developer Tools Console Output

None

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
