### ISSUE TITLE
How can I set CSS rule in vscode-jupyter?

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode-jupyter#12705]
As is known to all, the number of characters in a line is limited. 

I refer to [this issue](https://stackoverflow.com/questions/53482343/how-to-disable-line-wrapping-in-jupyter-notebook-output-cells/63476260#63476260) on so, it said I can modify the css rule, however, I don't understand how can I edit this file on vscode.

There has another answer, use magic command while it doesn't work on vscode-jupyter. This works on web jupyter well.

```
%%html
<style>
div.output_area pre {
    white-space: pre;
}
</style>
```

Is there any way to set the limitation of line characters or change the css file on vscode?

Thank you for any help.

**Comment by ydmykr** [comment]
Any help?

**Comment by amunger** [comment]
can you explain the limitation more, I'm not sure what character limit you are referring to within the vscode.

![image](https://user-images.githubusercontent.com/2019016/218160694-fc213ebb-4d33-454c-9680-1b401cc92e84.png)

**Comment by ulysse06** [comment]
I have a similar issue.
![image](https://user-images.githubusercontent.com/81274708/221257934-543f399b-0def-424d-81ae-4131fa5bc20d.png)

**Comment by amunger** [comment]
@ulysse06 - that should be addressed in the next release, and you can install insiders to see it today. The `notebook.output.wordWrap` setting has also been introduced to configure word wrapping in the output
