### ISSUE TITLE
Do not automatically trigger environment discovery at startup

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode-jupyter#12719]
Already brought it up with @DonJayamanne but opening this issue to track it.

I understand with the current design of kernel picker this is not possible. However, with the new design discovery can be triggered when the list is opened instead, so this can be avoided.

**Comment by karrtikr** [comment]
FYI we have been recommending folks to disable Jupyter extension for related issues: https://github.com/microsoft/vscode-python/issues/20446#issuecomment-1456369910

**Comment by karrtikr** [comment]
@DonJayamanne Any status on prioritizing this?

https://github.com/microsoft/vscode-python/issues/21010#issuecomment-1499742609

**Comment by thoth291** [comment]
Look at my comment here: https://github.com/microsoft/vscode-python/issues/21010#issuecomment-1544106651

**Comment by DonJayamanne** [comment]
Done

**Comment by DonJayamanne** [comment]
This shuold now be done, https://github.com/microsoft/vscode-jupyter/pull/15261
