### ISSUE TITLE
Making %edit magic work in jupyter extension.

### ISSUE THREAD

**Issue by alexbalandi** [microsoft/vscode-jupyter#12710]
What I actually want is what was suggested in closed issue : https://github.com/microsoft/vscode-jupyter/issues/1685 (because nobody expressed interest in it...)

As seen from discussion here : https://github.com/jupyter/jupyter_console/issues/113#issuecomment-362636515, there should be nothing strongly blocking this functionality.
 Also, right now, as I understand it, interactive IPython shell works quite fine with simply making correct config as described here : https://stackoverflow.com/questions/15681153/external-editor-for-ipython-notebook/27957184#27957184

I'm sorry no one was up for it back in 2020, @rchiodo  :sweat_smile:  It was only recently that I learned of this cell magic at all and it looks really lucrative for easing the hassle of putting finalized prototype into python modules.

If you direct me a bit in terms of what parts of codebase I should be looking at, I can take it upon myself to implement this - will be slow, but I'll get there :)

**Comment by DonJayamanne** [comment]
Thanks for suggesting this feature, however I'm closing this issue as this has not receieved any upvotes
