### ISSUE TITLE
Clarification about Jupyter extension and the issue is tracked here https://github.com/microsoft/vscode-jupyter/issues/9292

### ISSUE THREAD

**Issue by JDDug** [microsoft/vscode-jupyter#12718]
Hello 
I'm having the issues mentionned in the call
https://github.com/microsoft/vscode-jupyter/issues/9290

In the answers, I found a response with link to
"This is a bug in the Jupyter extension and the issue is tracked here https://github.com/microsoft/vscode-jupyter/issues/9292
It will probably be fixed in the next release.
"
But in the site
https://github.com/microsoft/vscode-jupyter/wiki/IPyWidget-Support-in-VS-Code-Python
It is not clear which config file need to be updated. 
Can you please help to clarify between the vscode, jupyter server, widget config files which need to be updated?
thanks
JD

**Comment by DonJayamanne** [comment]
I'm not entirely sure what problem you are having 
Would help if you provided more information on what is not working and provided the logs thats in the issue template.

> But in the site
https://github.com/microsoft/vscode-jupyter/wiki/IPyWidget-Support-in-VS-Code-Python
It is not clear which config file need to be updated.
Can you please help to clarify between the vscode, jupyter server, widget config files which need to be updated?
 
Instructions are as follows
* Open VS Code
* Use the command `Preferenced: Open Settings UI`
* Search for `Jupyter Widget`
* Add the two items `jsdelivr.com` and `unpgk.com` into the list (using the `Add Item` button)
![Screenshot 2023-02-03 at 06 41 08](https://user-images.githubusercontent.com/1948812/216433153-1782ab0a-cd89-4b26-8676-ae0e11200b3c.png)
