### ISSUE TITLE
Server / Kernel title bar appears to "vibrate" when you move a slider

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#1271]
Don't have an easy way to capture gifs right now. But create something like a widget slider and then drag it back and forth. The title bar changes between busy and idle. But the size of the text area is not locked, so the entire bar changes size. So it looks like it's vibrating. Not a big deal, but very visually distracting.

![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/12d92c90-bfe8-4a4a-a7c6-cb0a1db654b0)

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
