### ISSUE TITLE
Jupyter fails to start when using (globally installed) Python

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12729]
Jupyter can fail to start when using Home Brew Python
# Suggestion
* Please create a virtual environment
* If you have conda then create a conda environment
* Ensure Jupyter is installed into the above conda environment or virtual environment
* Go into the command palette and select the command `Jupyter: Select Interpreter to Start Jupyter Server`
* Select the virtual env or conda env created earlier
* Re-load VS Code

Things should work as expected.
If not, then 
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by lucahost** [comment]
This fix did solve the issue, verifying this.

**Comment by DonJayamanne** [comment]
@lucahost Thank you very much for confirming the fix.

**Comment by DonJayamanne** [comment]
This has been fixed in the latest pre-release version of the extension.
