### ISSUE TITLE
HTML export doesn't show plots

### ISSUE THREAD

**Issue by Michitronik** [microsoft/vscode-jupyter#12725]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

If I want to export a notebook as html. The result shows no plots, made with "plotly.express".
"matplotlib.pyplot" plots are shown.

### VS Code Version

1.75.0

### Jupyter Extension Version

v203.1.2000312134

### Jupyter logs

```shell
nothing in output
```

### Coding Language and Runtime Version

Python 3.9.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Sorry for never getting back to you on this issue, somehow this slipped through the cracks.
We have made a lot of improvements and fixes in this space and believe this may have been resolved.
Please ensure you update to the latest version of VS code and the extensions.
Closing as I believe it may have been resolved,
If not please ping here and I'll reopen this or feel free to create a new issue.
