### ISSUE TITLE
cannot start remote Jupyter notebooks over ssh after recent upgrade

### ISSUE THREAD

**Issue by FlorinAndrei** [microsoft/vscode-jupyter#12735]
## Environment data

-   VS Code version: 1.75.0
-   Jupyter Extension version (available under the Extensions sidebar): v2023.2.1000360234
-   Python Extension version (available under the Extensions sidebar): v2023.2.0
-   OS (Windows | Mac | Linux distro) and version: Windows 10 local, Ubuntu 22.04 remote
-   Python and/or Anaconda version: 3.10.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Remote

Running VSCode on my Win10 laptop. In VSCode, I connect via ssh to a Linux machine running Ubuntu 22.04, where I run all my Jupyter notebooks. Python, CUDA, and all the libraries are on the remote Linux machine.

## Expected behaviour

Open ssh to remote Linux machine.

Open folder.

Open Jupyter notebook.

Run the notebook.

It runs.

## Actual behaviour

When I try to run the notebook, I get a little box at the top saying: "select kernel for notebook.ipynb"

Syntax highlighting also seems wrong.

## Steps to reproduce:

It worked until today when I applied all the updates to my VSCode and its extensions.

I am now on the pre-release version of the Jupyter extension.

I've tried the latest release and it's broken.

I've tried the previous version of the Jupyter extension and it still doesn't work.

My setup is broken right now.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
@FlorinAndrei 
Please could you select a level from the list and try again
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by FlorinAndrei** [comment]
I've found the root cause.

All VSCode extensions got somehow uninstalled from vscode-server in the remote Linux host. No idea how that happened. I am the only user. I have not touched extensions in a long time - I only approve reloads for updates.

I've installed Jupyter-related extensions into the remote SSH machine in vscode-server and now everything works.

**Comment by DonJayamanne** [comment]
Thanks for getting back to us
Closing as resolved
