### ISSUE TITLE
Poor UX when the python show interactive window command fails

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#1273]
# Bug: Notebook Editor, Interactive Window, Editor cells

While investigating https://github.com/microsoft/vscode/issues/97992

## Steps to cause the bug to occur

1. Install python extension
1. Run the `Python: Show interactive window` command

## Actual behavior
Flash as the window appears for a split second. Then it closes and there is a error notification:

![Screen Shot 2020-06-02 at 2 55 05 PM](https://user-images.githubusercontent.com/12821956/83573838-0f544800-a4e1-11ea-9ff2-f7af595e7cfe.png)

I don't really know how I'm supposed to fix this error. Maybe install juypter? 

## Expected behavior
The window starts.

If it cannot start properly, I am shown documentation that explains why and how to fix it

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:**  N/A
-   **Extension version:** 2020.05.80290
-   **VS Code version:**  1.46.0-insider
-   **Setting python.jediEnabled:** false
-   **Setting python.languageServer:** Jedi | Microsoft | None
-   **Python and/or Anaconda version:** 3.7.3
-   **OS:**  Mac 
-   **Virtual environment:** NA

## Developer Tools Console Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by greazer** [comment]
I believe this has been addressed when we started supporting raw kernel
