### ISSUE TITLE
Light+ V2: Invisible text in Jupyter notebook Python exception traceback

### ISSUE THREAD

**Issue by 2-5** [microsoft/vscode-jupyter#12751]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.75.0
- OS Version: Windows 10

Steps to Reproduce:

1. Set theme to Light+ V2 Experimental
2. Create Jupyter Notebook
3. Raise an exception
4. Notice how some of the exception traceback is invisible (you can select it to see it)

Light+ V2 theme:

![2023-02-03_150845](https://user-images.githubusercontent.com/3753822/216611704-50e9c990-c6d5-4b31-aa94-eba00f286bd1.png)

Old Light+ theme:

![2023-02-03_150859](https://user-images.githubusercontent.com/3753822/216611729-80f5364b-0ae4-4a10-944c-b25ee8619faa.png)

**Comment by amunger** [comment]
thanks for confirming. We are working on dropping the jupyter extension's renderer in favor of using core's, so that should take care of this issue

**Comment by rebornix** [comment]
We now default to the core renderer.
