### ISSUE TITLE
Flash of interactive window if Jupyter is not installed

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#1275]
Issue Type: <b>Bug</b>

**Repro**
1. On a machine with python but without Jupyter
1. Open a python file
1. Use the `Run current file in interactive window`

**Bug**
The interactive window appears for half a second then closes itself! Then a notification appears telling me to install Jupyter

This flash of interactive window makes it look like the window has crashed. Instead:

- Just show the notification
- Or show the error in the interactive window itself

Extension version: 2020.4.67630-dev
VS Code version: Code - Insiders 1.44.0-insider (ef75c4bb445e5021065cf0012cfa2c66e55bfa16, 2020-03-11T09:09:04.033Z)
OS version: Darwin x64 19.3.0

**Comment by greazer** [comment]
I believe this has been addressed since we started supporting raw kernel
