### ISSUE TITLE
Unable to find widget 'catboost-widget' from configured widget sources

### ISSUE THREAD

**Issue by 2-5** [microsoft/vscode-jupyter#12763]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I'm getting a warning when using `catboost` in a VS Code Jupyter notebook:

![2023-02-07_160732_catboost_widget](https://user-images.githubusercontent.com/3753822/217335084-633580c2-fe8b-4169-8316-a2d1eb533f0c.png)

The `catboost` JupyterLab extension are installed in my `venv`:

```
.venv\share\jupyter\labextensions\catboost-widget\package.json
.venv\share\jupyter\nbextensions\catboost-widget
```

VS Code settings:

```json
"jupyter.widgetScriptSources": [
    "jsdelivr.com",
    "unpkg.com"
],
```

Reproduction code in new notebook:

```python
# pip install catboost

from catboost import CatBoostClassifier, Pool

train_data = [
    [1, 3],
    [0, 4],
    [1, 7],
]
train_labels = [
    1,
    0,
    1,
]

model = CatBoostClassifier(verbose=False)
model.fit(train_data, train_labels, plot=True)
```

### VS Code Version

Version: 1.75.0 (user setup) Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164 Date: 2023-02-01T15:23:45.584Z Electron: 19.1.9 Chromium: 102.0.5005.194 Node.js: 16.14.2 V8: 10.2.154.23-electron.0 OS: Windows_NT x64 10.0.19045 Sandboxed: No

### Jupyter Extension Version

v2023.1.2000312134

### Jupyter logs

```shell
info 20:41:22.099: Started Kernel .venv (Python 3.10.8) (pid: 14296)
info 20:41:23.976: [32mFetch Script for {"moduleName":"catboost-widget","moduleVersion":"^1.0.0","requestId":"catboost-widget:^1.0.0:1675795283970"}
info 20:41:23.977: [32mFetch Script for catboost-widget
info 20:41:23.977: [32mSearching for Widget Script catboost-widget#^1.0.0 using cdns jsdelivr.com unpkg.com
error 20:41:24.298: Widget Script catboost-widget#^1.0.0 was not found on on any cdn
info 20:41:24.318: Script source for Widget catboost-widget@^1.0.0 was found from source local
info 20:41:24.318: [32mScript for catboost-widget, is https://file%2B.vscode-resource.vscode-cdn.net/c%3A/Users/User/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/tmp/scripts/313e36f185df5f57693369e39dedb4f8c3b69548f0734e73f29324a5b883710a/jupyter/nbextensions/catboost-widget/index from local
info 20:41:24.318: [32mFetch Script for catboost-widget
info 20:41:24.319: Script source for Widget catboost-widget@^1.0.0 was found from source local
info 20:41:24.319: [32mScript for catboost-widget, is https://file%2B.vscode-resource.vscode-cdn.net/c%3A/Users/User/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/tmp/scripts/313e36f185df5f57693369e39dedb4f8c3b69548f0734e73f29324a5b883710a/jupyter/nbextensions/catboost-widget/index from local
```

### Coding Language and Runtime Version

Python 3.10.8

### Language Extension Version (if applicable)

v2023.2.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
@2-5 thanks for filing this issue.
This is merely a warning indicating the fact that the widhget might not work properly as the widget could not be found on the  CDN 
Yes, the widget might exist in the virtual environment, however for things to work properly VS Code relies on the CDN as those scripts work better outside a Jupyter environment such as VS Code. And if those are not on the CDN then they might not work well,
Hence this warning message is expected (even if the widget were to work)

**Comment by 2-5** [comment]
@DonJayamanne so how can this warning be fixed? Should this be reported to the `catboost` team?

**Comment by DonJayamanne** [comment]
Oh wait it is available on CDN, just not in a standard location.

**Comment by DonJayamanne** [comment]
Closing as an upstream issue https://github.com/catboost/catboost/pull/2148
Based on the docs the file shnould be in `dist/index.js` and not `src/index.min.js`
