### ISSUE TITLE
flaky kernel tests e.g. `Should be prompted to re-install ipykernel when restarting a kernel from which ipykernel was uninstalled`

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12766]
https://github.com/microsoft/vscode-jupyter/actions/runs/4112185414/jobs/7096807649
https://github.com/microsoft/vscode-jupyter/actions/runs/4113151862/jobs/7098935606

[TestLogs-local-python-3.10--ubuntu-latest-_kernelCore__kernelInstall_.zip](https://github.com/microsoft/vscode-jupyter/files/10679298/TestLogs-local-python-3.10--ubuntu-latest-_kernelCore__kernelInstall_.zip)

**Comment by amunger** [comment]
tests that rely on kernel startup in local and remote scenarios are currently the most common case of flakey tests
![image](https://user-images.githubusercontent.com/2019016/220741195-f4e5e494-9603-4eb8-bd74-bccc53c47393.png)

**Comment by DonJayamanne** [comment]
No longer flaky
