### ISSUE TITLE
Cells become invisible

### ISSUE THREAD

**Issue by davide-perrone** [microsoft/vscode-jupyter#12779]
## Environment data

-   VS Code version: 1.75.0
-   Jupyter Extension version (available under the Extensions sidebar): v2023.1.2010391206
-   Python Extension version (available under the Extensions sidebar): v2023.2.0
-   SSH to Fedora machine from Windows

![image](https://user-images.githubusercontent.com/64072057/217554695-d3e2cf1b-20b2-4344-a159-be50f1207b1a.png)

Cells become invisible and unclickable and only become available again after collapsing them.

**Comment by rebornix** [comment]
This is fixed now in latest Insiders and will be available in next Stable recovery build.

**Comment by Luca715** [comment]
When is the next stable recovery build and how can i get my hands on it?
