### ISSUE TITLE
Clear/Reset cell variables on cell rerun

### ISSUE THREAD

**Issue by nihalkenkre** [microsoft/vscode-jupyter#12776]
Please consider the below code

```
op_nodes : dict[int, Node] = {}

for node in node_list
        op_nodes[id(node)] = node

for id, node in binOps.items():
    process_node(value)
```

This code is interpreted correctly the first time the cell is run, but rerun the cell and we get the error

```
TypeError                                 Traceback (most recent call last)
Cell In[2], line ***

--> op_nodes[id(node)] = node
    for id, node in op_nodes.items():
        process_node(value)

TypeError: 'int' object is not callable
```

This happens because the variable `id` is already created in the first run of the cell. Resetting the kernel works since variables are cleared.

Clearing out the variables of the particular cell which is run would be useful.

Best regards,
Nihal Kenkre

**Comment by DonJayamanne** [comment]
thanks for filling this feature request

> is already created in the first run of the cell. Resetting the kernel works since variables are cleared.

this is the expected behaviour for clicking run button
Eg is possible one wants to run a cell again and again and it only generates a graph
Hence cheating all of the variables in the kernel would be wrong

as there are separate buttons to control the state of the kernel (restart), I don’t see this behaviour  changing,

Though there is a separate feature request to restart and run all, which could work for you

**Comment by nihalkenkre** [comment]
Hello.

Request you to go through the feature request text again.

I mention resetting the variables of the cell that is re-run.



> thanks for filling this feature request
> 
> > is already created in the first run of the cell. Resetting the kernel works since variables are cleared.

> 
> this is the expected behaviour for clicking run button Eg is possible one wants to run a cell again and again and it only generates a graph Hence cheating all of the variables in the kernel would be wrong
> 

Clearing out all the variables in the kernel was never the request. Clearing out the variables in the particular cell which is re-run is the request

> as there are separate buttons to control the state of the kernel (restart), I don’t see this behaviour changing, Also this is how Jupyter notebooks/lab also works
> 
> Though there is a separate feature request to restart and run all, which could work for you

Again, restarting the kernel is what needs to be done now, or else compromise on the variable names. Hence resetting the variables in the cell which is re-run is what this request is about.

Regards,
Nihal Kenkre

**Comment by DonJayamanne** [comment]
> Clearing out all the variables in the kernel was never the request. Clearing out the variables in the particular cell which is re-run is the request


In Python one could end up creating variables any number of ways, global and the like, and tryihng to fitgure out what Cell introduced the varialb is not possible. As you can have the first cell that has a background thread and the like.

Once again, this is also not how Jupyter Notebooks/Lab works.  Hence I do not see us introducing such a change as this extension makes use of the Jupyter kernels and tried to behave the same (identical with the use of the Jupyter protocol).
