### ISSUE TITLE
jupyter.magicCommandsAsComment not working

### ISSUE THREAD

**Issue by jrich100** [microsoft/vscode-jupyter#12780]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

- Set `"jupyter.magicCommandsAsComments": true`
- Run .ipynb notebook cell:
`#!%%time`
`x = 5`

no output associated with the `%%time` magic. This same cell works when the magic command is not commented out. Should also note that I am using a remote Jupyter Server.

### VS Code Version

v1.73.1

### Jupyter Extension Version

v2022.10.110

### Coding Language and Runtime Version

Python 3.9.16

### Language Extension Version (if applicable)

v2022.18.2

### Anaconda Version (if applicable)

N/A

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, however that setting only applies to code in python files (i.e. for interactive window)
Regular notebooks with cells require magic commands to be entered as regular magic commands, instead of commenting them.
