### ISSUE TITLE
Run Selection/Line in Interactive Window ignores decorator

### ISSUE THREAD

**Issue by JanPalasek** [microsoft/vscode-jupyter#12782]
Type: <b>Bug</b>

# Introduction

Running Selection/Line in Interactive Window ignores decorators.

# Minimum reproducible file

Python file `test.py`:

```python
#%%
def my_decorator(fn):
    return my_decorator

#%%
@my_decorator
def f(a, b):
    return a + b
```

# How to reproduce

Go over the "cells" and for each run `Run In Interactive Window > Run Selection/Line in Interactive Window`. In the second cell, the decorator will be ignored.

# Versions

- Python: v2023.2.0
- System: CentOS 7

Extension version: 2023.2.0
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.17763
Modes:
Sandboxed: No
Remote OS version: Linux x64 3.10.0-1160.21.1.el7.x86_64

**Comment by DonJayamanne** [comment]
@JanPalasek I'm so sorry for missing this issue
Passing this onto @amunger , hopefully he'll have an idea whats going on here.

**Comment by amunger** [comment]
should be fixed by https://github.com/microsoft/vscode-jupyter/pull/13044
