### ISSUE TITLE
SVG adjust width, fit to display width

### ISSUE THREAD

**Issue by LeanderK** [microsoft/vscode-jupyter#12793]
I am currently creating figures for a publication. Therefore I have to use a certain size for the width and height for matplotlib to faithfully render my figures and to match my font-settings. I want to view the image in jupyter as svg to accurately judge how it looks. The problem now is that sometimes the svg is wider than the width in my jupyter notebook. I would like to view it resized so that it fits to the width of my output instead of being scrollable.

**Comment by rebornix** [comment]
>  I would like to view it resized so that it fits to the width of my output instead of being scrollable.

cc @amunger

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
