### ISSUE TITLE
Jupyter command `jupyter-notebook` not found.

### ISSUE THREAD

**Issue by vladcrishan** [microsoft/vscode-jupyter#12798]
## Environment data

-   VS Code version: Version: 1.75.0
-   Jupyter Extension version (available under the Extensions sidebar): v2023.1.2010391206
-   Python Extension version (available under the Extensions sidebar): v2023.2.0
-   OS (Windows | Mac | Linux distro) and version: MacOs Ventura 13.0.1
-   Python and/or Anaconda version: Python 3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): NA
-   Jupyter server running: Local

## Expected behaviour

jupyter notebook working like it worked before

## Actual behaviour

not working...

## Steps to reproduce:

`shit+enter` on jupyter notebook cell and I get the following output in the logs

Running `python3 -m jupyterlab` in terminal works. I can use jupyter notebook in the browser.
I can't find the exact command vscode extension executes but I'm guessing it's `jupyter-notebook` so I've tried adding an alias for `jupyter-notebook` command. Still with no luck...

```
alias jupyter-notebook="python3 -m jupyterlab"
```

My guess... Either MacOs update or vscode-jupyter update.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
error 20:48:10.251: Error in execution (get message for cell) Er [Error]: Jupyter server crashed. Unable to connect. 
Error code from Jupyter: 1
usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json] [--debug]
                  [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

optional arguments:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands:

Jupyter command `jupyter-notebook` not found.

    at Sm.rejectStartPromise (/Users/vladcrisan/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:254981)
    at t._complete (/Users/vladcrisan/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:255541)
    at t.n (/Users/vladcrisan/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:700797)
    at t.__tryOrUnsub (/Users/vladcrisan/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:701037)
    at t.complete (/Users/vladcrisan/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:700930)
    at t._complete (/Users/vladcrisan/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:699446)
    at t.complete (/Users/vladcrisan/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:699145)
    at ChildProcess.<anonymous> (/Users/vladcrisan/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1800927)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:538:35)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  category: 'jupyterconnection',
  vslsStack: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {}
  ]
}
```

</p>
</details>

**Comment by DonJayamanne** [comment]
@nicosuave 
Please could you try the following:
* Create a virtual environment in some directory
* Activate that virtual environment in the terminal
* Install Jupyter into that virtual environment as follows `<python> -m pip install jupyter notebook`
* Where `<python>` would be the fully qualified path to that virtual environment python executable
* Open the folder containing the virtual environment (i.e. open the parent directory)
* Open the command palette and select the command `Jupyter: Select Interpreter to Start Jupyter Server` and select that virtual enviornment
* If prompted to isntall any dependencies, then please do so
* Re-Load VS COde and let me know how that goes
* 
oh yes, please install the latest 2023.1.201 version of the latest pre-release version

**Comment by DonJayamanne** [comment]
Closing this issue as that should fix it
@vladcrishan if that does not work, please could you reply here and I'd be happy to reopen this issue or please feel free to open it your self (else, please create a new issue)

Once again, sorry you are running into this issue and thanks for filing this issue.

**Comment by vladcrishan** [comment]
Hi @DonJayamanne. To tell you the truth, I don't know why creating a virtual environment and installing required dependencies fixed all my issues and even made it work for ts kernel, but it sure did.
Thank you so much and keep up the good work 👍 !

**Comment by DonJayamanne** [comment]
@vladcrishan I think the recent changes in the pre-release version of the Jupyter extension should make creation of a virtual env unnecessary. please do feel free to try that as well.
Either way, thanks for the confirmation of the fix
