### ISSUE TITLE
Infinitely connecting to kernel

### ISSUE THREAD

**Issue by meetjaydeep** [microsoft/vscode-jupyter#12792]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Extension is not connecting to Python kernel, its infinitely showing "Connecting to kernel: code (Python 3.10.9): Activating Python Environment 'code'"
In past it was working using miniconda environment. I manually deleted miniconda directory and reinstalled it at different location.
Now, extension stopped working.
[code-jupyter.log](https://github.com/microsoft/vscode-jupyter/files/10698428/code-jupyter.log)

### VS Code Version

[Window Title] Visual Studio Code  [Main Instruction] Visual Studio Code  [Content]  Version: 1.74.0 (user setup) Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91 Date: 2022-12-05T16:38:16.075Z (2 mos ago) Electron: 19.1.8 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10.0.19044 Sandboxed: No  [OK] [Copy]

### Jupyter Extension Version

v2022.11.1003412109

### Jupyter logs

```shell
log File attached
```

### Coding Language and Runtime Version

Python 3.10

### Language Extension Version (if applicable)

Python

### Anaconda Version (if applicable)

23.1.0

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment]
@meetjaydeep I'm so sorry for missing this sissue, please could you install the latest pre-release version of the Jupyter extension in vscode insiders and let me know if you are still running into this issue.
Once again, I do apologize for not getting back to you sooner on this issue.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
