### ISSUE TITLE
Error message not fully visible with autoscroll in Interactive window

### ISSUE THREAD

**Issue by corneliusroemer** [microsoft/vscode-jupyter#1279]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Fill the interactive window with output
2. Scroll all the way to the bottom, so that autoscroll works (when you execute new lines the window keeps scrolling down)
3. Execute a command that creates an error message, e.g. `print(')`

## Actual behavior
The bottom part of the error message is cut off, not visible. Autoscroll doesn't scroll far enough, see on the screenshot:
![image](https://user-images.githubusercontent.com/25161793/96377246-cdbcf480-1184-11eb-8fd3-b5b31a9a7bb6.png)

## Expected behavior
The window scrolls down automatically so that the entire error message is visible

![interactiveerror](https://user-images.githubusercontent.com/25161793/96377578-bd0d7e00-1186-11eb-8240-b096d0ec0f2d.gif)

### Your Jupyter and/or Python environment

-   **Jupyter server running:** Local
-   **Extension version:** 2020.9.114305
-   **VS Code version:** 1.50.1
-   **Setting python.jediEnabled:** false
-   **Setting python.languageServer:** Microsoft
-   **Python and/or Anaconda version:** 3.8.5 Conda
-   **OS:** Windows 18636.1082 Enterprise
-   **Virtual environment:** conda

**Comment by roblourens** [comment]
This is probably fixed with the new interactive window
