### ISSUE TITLE
Implement R and SQL code with Python in the same Jupyter Notebook

### ISSUE THREAD

**Issue by jan-casas** [microsoft/vscode-jupyter#12796]
1. Would it be possible to work with Python, R and SQL in the same jupyter notebook?
2. If there is more than 1 graph (in jupyter notebook) add an option to view all (similar to how R display the graphs), it's quite useful

**Comment by kenf1** [comment]
Yes, it's possible. Python and SQL can be used directly but you'll need a package like rpy2 to communicate between R and Python.

Click on bottom of code cell to change which language to use.

**Comment by jan-casas** [comment]
Yes, but not as smooth as Datalore, for example, and hopefully vscode would be close to doing it without import modules.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, however given the fact that there have been no upvotes on this issue nor any additional comments, I'm closing this issue.
