### ISSUE TITLE
Feature: Add option to enable Python Interctive window to always scroll to the bottom with new output

### ISSUE THREAD

**Issue by corneliusroemer** [microsoft/vscode-jupyter#1280]
## Description

I know that you've discussed this feature suggestion before in https://github.com/microsoft/vscode-python/issues/8955 but I wanted to give some additional information.

I understand the intention behind the Interactive windows behaving like a chat - however the current implementation does not work smoothly enough for it to be useful. Even if I just scroll a little up, the window stops scrolling.

What's worse, new cells seem to get hidden behind the input window as shown on the screenshot, this was produced with automatic scrolling:
![image](https://user-images.githubusercontent.com/25161793/96368568-ae0dd800-1154-11eb-8d6c-b210a8bab268.png)

Would it not be possible to add a simple lock icon to the Interactive window as in the VScode output screen, where you can turn autoscrolling on and off? This is currently the only reason why I need to switch to mouse in my workflow and it's annoying - I don't think I'm alone in this.

**Comment by roblourens** [comment]
I think this is fixed in the new interactive window based on native notebooks
