### ISSUE TITLE
Data Viewer can't filter multi-index

### ISSUE THREAD

**Issue by notuntoward** [microsoft/vscode-jupyter#12829]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Filtering by multi-index doesn't work on the Data Viewer.  The first screenshot shows how an example multi-index dataframe is displayed in a Jupyter notebook celI output. The screenshot shows what that dataframe looks like in the Data Viewer to display.  

If I type '0' into the Data Viewer index filter box, I do see all the rows that have a 0 in the first tuple of their index.  But if I type "0,4", the display doesn't narrow down to only entries with a tuple of (0,4); instead, the display is unchanged.  If I instead type (0,4), then no rows are displayed at all.

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/3851891/218543596-33d85c22-ae48-40b8-87f5-e50ee773d849.png">

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/3851891/218543302-a6f573fe-6792-4330-bdd8-7d9995f291e7.png">

### VS Code Version

Version: 1.75.1 (user setup) Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf Date: 2023-02-08T21:32:34.589Z Electron: 19.1.9 Chromium: 102.0.5005.194 Node.js: 16.14.2 V8: 10.2.154.23-electron.0 OS: Windows_NT x64 10.0.22621 Sandboxed: No

### Jupyter Extension Version

v2023.1.2010391206

### Coding Language and Runtime Version

Python v3.9.7

### Language Extension Version (if applicable)

Python v2023.2.0

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
closing for https://github.com/microsoft/vscode/issues/165445

**Comment by DonJayamanne** [comment]
@amunger isn’t the issue you mentioned about variable viewer
Ie once variable viewer is added then that issue gets closed and this will bug not get resolved

**Comment by amunger** [comment]
oops, I just looked at the first screenshot and thought it was about the variable viewer

**Comment by amunger** [comment]
closing as the jupyter data viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486
