### ISSUE TITLE
Split long output lines, like Jupyter Notebook does, to avoid diff football between vscode-jupyter and Jupyter

### ISSUE THREAD

**Issue by xl0** [microsoft/vscode-jupyter#12825]
When generating an SVG, Jupyter will convert it into multiple lines:
```
"data": {
    'image/svg+xml': '<?xml version="1.0" encoding="utf-8" standalone="no"?>\n<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"\n  "http://www.w3.org/Graphic...
```
becomes
```
"data": {
    "image/svg+xml": [
        "<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"no\"?>\n",
        "<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n",
        "  \"http://www.w3.org/Graphic...
```
The same is done for `text/plain` and `applicaiton/javascript` outputs.

According to https://github.com/jupyter/nbformat/blob/main/nbformat/v4/rwbase.py#L68 , this is done to generate easier-to-read diffs. 
Ironically, this leads to annoying diff football between Jupyter and jupyter-vscode, since the latter does not perform this conversion.

Unfortunately, there is no possibility to configure this behaviour on Jupyter's side. Would it be possible to implement the same behaviour in vscode-jupyter?

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, 
agreed this is not an ideal experience,
will look into this and get this addressed
