### ISSUE TITLE
Jupyter crashes on multiple notebooks

### ISSUE THREAD

**Issue by wrogner** [microsoft/vscode-jupyter#12821]
## Environment data

-   VS Code version: 1.75.1
-   Jupyter Extension version (available under the Extensions sidebar): 2023.1.2010391206
-   Python Extension version (available under the Extensions sidebar): 2023.2.0
-   OS (Windows | Mac | Linux distro) and version: macOS 13.2
-   Python and/or Anaconda version: 3.10.10 / 3.11.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

1. Launch new kernels quickly
2. Launch kernels reliably
3. operate kernels reliably

## Actual behaviour

1. First kernel takes some time to launch (20 - 80s)
2. Second ... kernel takes between 60 - 600s
3. Running two or more notebooks side by side regularly leads to kernel crashes in similar cells (happens when I correct similar sample notebooks from students)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create two notebooks that load SciPy stack and Tensorflow
2. Use demo files from Tensorflow suffices for this
3. Change some cells so that they may or may not run into errors (changing size of matrices)
4. Run both notebooks in parallel

--> The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.
Canceled future for execute_request message before replies were done

## Logs

info 23:36:28.360: Process Execution: > ~/Development/py/5 ml/venv/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/Development/py/5 ml/venv/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 23:36:28.465: Spec argv[0] updated from '/Users/wolf/Development/py/5 ml/venv/bin/python' to '/Users/wolf/Development/py/5 ml/venv/bin/python'
[I 23:36:28.494 NotebookApp] Kernel started: af3d7540-ba8a-44dd-bd91-beac20ddf330, name: pythonjvsc74a57bd0cebcd33edd316d35f2057a62d18ade2e0a98bec41e4276bf6b91559eff1be53f
[W 23:36:28.508 NotebookApp] delete /courses/FH_2022_AIE_MIWbb/MWI-BB-1-WS2022-AIbb-Exercise to text analysis in Python-1192439/Pappenheim Georg_1690973_assignsubmission_file_/Text_analysis_Abgabe/Text_analysis/text_analysis_basics-jvsc-f2843a6e-2f0e-4b61-9c9d-789042e5ddda0d074236-04f6-413d-9e0b-cae8a1c24ec4.ipynb
info 23:36:38.576: Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd0cebcd33edd316d35f2057a62d18ade2e0a98bec41e4276bf6b91559eff1be53f./Users/wolf/Development/py/5 ml/venv/python./Users/wolf/Development/py/5 ml/venv/python.-m#ipykernel_launcher
info 23:36:38.840: Process Execution: > ~/Development/py/5 ml/venv/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/printJupyterDataDir.py
> ~/Development/py/5 ml/venv/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/printJupyterDataDir.py
[I 23:37:07.482 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel af3d7540-ba8a-44dd-bd91-beac20ddf330 restarted
error 23:37:07.485: Error in waiting for cell to complete Error: Canceled future for execute_request message before replies were done
    at t.KernelShellFutureHandler.dispose (/Users/wolf/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:33213)
    at /Users/wolf/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:27432
    at Map.forEach (<anonymous>)
    at v._clearKernelState (/Users/wolf/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:27417)
    at /Users/wolf/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:29860
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
warn 23:37:07.485: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
info 23:37:07.486: Cancel all remaining cells true || Error || undefined
[I 23:37:07.485 NotebookApp] Starting buffering for af3d7540-ba8a-44dd-bd91-beac20ddf330:bf2016b5-d7b0-487a-8d0c-d1e8ad7d7d45
[I 23:37:07.490 NotebookApp] Restoring connection for af3d7540-ba8a-44dd-bd91-beac20ddf330:bf2016b5-d7b0-487a-8d0c-d1e8ad7d7d45
[I 23:37:07.992 NotebookApp] Replaying 1 buffered messages
warn 23:37:07.993: Unhandled message found: execute_reply

**Comment by DonJayamanne** [comment]
Thanks for filing this  issue, and sorry you are running into this.
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
