### ISSUE TITLE
Unable to use Jupyter in VSCode with PyEnv

### ISSUE THREAD

**Issue by luciolcv** [microsoft/vscode-jupyter#12820]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Hi there, after rebooting VScode, I'm not able to run any kind of notebook, as it throws the following error:

```
Failed to start the Kernel. 
Jupyter server crashed. Unable to connect. 
Error code from Jupyter: 127
pyenv: jupyter-notebook: command not found
```

The log says:
`Exception while attempting zmq : No native build was found for platform=darwin arch=arm64 runtime=electron abi=106 uv=1 armv=8 libc=glibc node=16.14.2 electron=19.1.9`

Also, I found something that might impact on such a problem:

> Visual Studio Code (1.75.1, undefined, desktop)
> Jupyter Extension Version: 2023.1.2010391206.
> Python Extension Version: 2023.2.0.
> Workspace folder /Users/lucio/Workspaces/Test
> warn 23:06:43.042: Exception while attempting zmq : No native build was found for platform=darwin arch=arm64 runtime=electron abi=106 uv=1 armv=8 libc=glibc node=16.14.2 electron=19.1.9
>     loaded from: /Users/lucio/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/node_modules/zeromq
> 
> User belongs to experiment group 'jupyterTestcf'
> User belongs to experiment group 'jupyterEnhancedDataViewer'

I'm using a Macbook Pro M1, and until today I was able of running my code without problems.

### VS Code Version

1.75.1

### Jupyter Extension Version

v2023.1.2010391206

### Coding Language and Runtime Version

Python 3.9.6

### Language Extension Version (if applicable)

v2023.2.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and I'm sorry you are running into this problem
Please could you try the following:
* Download and extract the following file
* From within VS Code use the command `Extensions: Install from VSIX`
* Select the above VSIX and install that
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

Please do send all of the logs.

**Comment by luciolcv** [comment]
By installing the insiders' version, I cannot reproduce the issue and everything works perfectly!

**Comment by DonJayamanne** [comment]
Thanks for getting back
Let’s close this issue as fixed
