### ISSUE TITLE
Links to open output panel does not work in error renderer

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12839]
@rebornix 
We have links that open the `Output Panel` and that does not work.
This is message is present in almost all outputs, and that does not work anymore.

I would suggest bringing back the old renderer for now, and next iteration I can create a new custom renderer for kernel failure error messages. At the end of the day kernel failure error messages are not standcard error messages, but custom messages with additional information and links (here is the suggested fix from Kai for kernel error messages https://github.com/microsoft/vscode-jupyter/issues/11531)

I.e. bring back the old renderer and when we have a custom mime type & a corresponding renderer for the kernel failures, we can then remove this old error renderer.

Else this is pretty bad, and we knmow for a fact that users use this a lot (based on the issues and the like we know users have been able to look at the logs and click on links to get kernels working)

![Screenshot 2023-02-14 at 17 18 24](https://user-images.githubusercontent.com/1948812/218655214-02f5c545-1e39-4fee-bff2-ab7cad7a5e04.png)

**Comment by DonJayamanne** [comment]
Btw, here is the code where you can see what type of links & actions are supproted (custom messages from renderer)
```typescript
        if (message.message === InteractiveWindowMessages.OpenLink) {
            const href = message.payload;
            if (href.startsWith('file')) {
                await this.openFile(href);
            } else if (href.startsWith('vscode-notebook-cell')) {
                await this.openCell(href);
            } else if (href.startsWith('https://command:') || href.startsWith('command:')) {
                const temp: string = href.startsWith('https://command:') ? href.split(':')[2] : href.split(':')[1];
                const params: string[] = temp.includes('/?') ? temp.split('/?')[1].split(',') : [];
                let command = temp.split('/?')[0];
                if (command.endsWith('/')) {
                    command = command.substring(0, command.length - 1);
                }
                if (linkCommandAllowList.includes(command)) {
                    await commands.executeCommand(command, params);
                }
            } else {
                this.applicationShell.openUrl(href);
            }
        }
 
```

As you can see `https://command` are custom commands and we have a white list `linkCommandAllowList`
So, 4 command will not work today.

Note: Commands in messages such as `Jupyter [log](command:jupyter.viewOutput) for further details.` are turned into links in the function `createOutputWithErrorMessageForDisplay`

I tried passing standard VS Code commands, but looks like that is not supported in the error renderer.

**Comment by rebornix** [comment]
@DonJayamanne commands are disabled for security reasons and it's now on top of an allow list. Is Open Output Panel the only command that we are using? If not do we have a list of commands that are being used by the Jupyter extension in error messages?

**Comment by DonJayamanne** [comment]
Yes here the allow list
linkCommandAllowList

**Comment by DonJayamanne** [comment]
Here are the commands
```
// The following list of commands represent those that can be executed
// in a markdown cell using the syntax: https://command:[my.vscode.command].
export const linkCommandAllowList = [
    'jupyter.latestExtension',
    'jupyter.viewOutput',
    'workbench.action.openSettings',
    'jupyter.enableLoadingWidgetScriptsFromThirdPartySource'
];
```

**Comment by rebornix** [comment]
Based on code search, the only command that's used in error outputs is `jupyter.viewOutput`. Now we added it to the allow list but we should also explore a generic command to open a specific channel. VS Code does have this command but it only takes channel id as argument, which is not accessible to us yet.
