### ISSUE TITLE
Insert code cell above (ESC, A) doesn't work if text in the cell is selected

### ISSUE THREAD

**Issue by zljubisic** [microsoft/vscode-jupyter#12844]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Let's say that I would like to copy code inside of the cell, create new cell above and paste it inside of the newly create cell.
I would like to do that in this way:
1. select the code
2. press ctrl+c
3. press esc (to enter command mode)
4. press 'a' (to insert code cell above)
5. press ctrl+v to paste the code

This almost works, but there is an annoyance:
1. select the code - ok
2. press ctrl+c - ok
3. press esc (to enter command mode) - command mode is not entered, selection is cleared
4. press 'a' (to insert code cell above) - pressing 'a' here will add 'a' to the code instead of applying "insert code cell above" in the notebook
...

So, if I have selected the text in the cell, and pressed ctrl+c to copy it, I have to press esc twice to enter command mode.
This is not consistent with the command mode.

Can you please ensure that when esc is pressed no matter what is happening, a command mode is entered so we can use 'a', 'b'...?

### VS Code Version

Version: 1.74.3 (system setup) Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534 Date: 2023-01-09T16:59:02.252Z Electron: 19.1.8 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10.0.19044 Sandboxed: No

### Jupyter Extension Version

v2022.11.1003412109

### Running Jupyter locally or remotely?

Local

**Comment by roblourens** [comment]
We can't do that by default- escape has meaning inside the editor and we have to respect that as well. You can customize this yourself by modifying the keybinding for `notebook.cell.quitEdit`. You can bind it to escape with an empty `when` clause so that it always takes effect, or add a different keybinding, or whatever you want.

**Comment by zljubisic** [comment]
If you consider for example vim editor, if you press esc no matter what you are doing you are in command mode.
What you have suggested is not consistend.
Sometimes you can press esc,a to create cell above, sometimes you have to press esc, esc, a.
If you try to see how jupyter notebooks are working it is as I have described.
