### ISSUE TITLE
provide option to use custom css files for notebook

### ISSUE THREAD

**Issue by yuuuxt** [microsoft/vscode-jupyter#12862]
My usage is to customize how rendered markdown cells look like. I assume the styling of jupyter notebook in vscode is not
of high priority, so why not just expose them to the users? :)

ref:
- jupyter notebook: `custom.css` can be loaded if put in `~/.jupyter/custom`
- SO question: https://stackoverflow.com/questions/66186394/configure-custom-css-for-jupyter-notebook-in-vscode
- hack to DIY: not possible now (iocave/customize-ui/issues/156)
	- maybe the `be5invis.vscode-custom-css` extension works, but it's still a hack, which also requires admin permission and is not straightforward.

**Comment by forivall** [comment]
the builtin markdown previewer does support custom css, for example: https://github.com/mjbvz/vscode-github-markdown-preview-style ; I dug through the code of https://github.com/mjbvz/vscode-markdown-checkboxes, and it injects styles, so you can just adapt that into your own plugin that allows for any custom css.

**Comment by psychemedia** [comment]
It would also be useful to be able to style cells based on cell tags. The tags can then be used to provide additional semantic structure to a notebook that is rendered through tag specific styling.

One solution might be to provide a mechanism to add class attributes based on cell tags, along with a way of defining style rules for those classes.

**Comment by yuuuxt** [comment]
For anyone interested: https://github.com/drcika/apc-extension is working.

**Comment by psychemedia** [comment]
In teaching, wefind the ability to style tags based on a class on a cell that mirrors a cell metadata tag very useful for helping guide students through notebooks by usomg cell background colour to identify cells that define student activities or act as calls to action, eg as per JupyterLab extension https://pypi.org/project/jupyterlab-empinken-extension/ .

This may also provide hooks for other added accessibility benefits
