### ISSUE TITLE
Hovering on variables once a jupyter session starts should reflect the value of the variable

### ISSUE THREAD

**Issue by notuntoward** [microsoft/vscode-jupyter#12866]
In VSCode, using the Jupyter extension, when I hover over a variable in a notebook cell, I'd like to see its value.  This like many other IDEs already do, in many languages e.g. Matlab.

I'm used to seeing this on other IDE's and it seems like I should see it here too.

**Comment by DonJayamanne** [comment]
Thank you for filing this feature suggestion, given this has not receieved an upvotes I'm closing this issue for now.
