### ISSUE TITLE
IndentationError: unexpected indent when trying to "Debug cell" on indented code

### ISSUE THREAD

**Issue by syagev** [microsoft/vscode-jupyter#1287]
# Bug: Notebook Editor, Interactive Window, Python Editor cells

## Steps to cause the bug to occur
1. In the editor, have this code:
```python
#%%
    a = 1

```
2. Run the "Debug cell" action on the above cell.

## Actual & Expected behavior
The result cell in the Python Interactive window:
```
breakpoint()
    a = 1

  File "", line 2
    a = 1
    ^
IndentationError: unexpected indent
```
Expected behavior is for this to work (despite the indentation of the code in the cell). Indeed, running the "Run Cell" action actually works well! This is extremely useful working with hybrid code/notebook files. So sometimes you have in a `code.py` file for instance:
```
def some_func():
    a = 1
    b = a + 1
    return b
```
and you want to work in the **inside** of the function interactively so you would make it:
```
#%%
def some_func():
#%%
    a = 1
    b = a + 1
#%%
    return b
```
That would make it possible to either call the code as the function or work on the contents interactively by evaluating/debugging the middle cell - extremely useful. I'm guessing this has to do with the `breakpoint()` statement added by the extension when "Debugging" cells.

### Your Jupyter and/or Python environment
- **Jupyter server running:**                       Local 
- **Extension version:**                               2019.10.44104
- **VS Code version:**                                1.40.0
- **Setting python.jediEnabled:**               true
- **Python and/or Anaconda version:**     3.5.4
- **OS:**                                                     Windows 
- **Virtual environment:**                          pipenv

Possibly related https://github.com/microsoft/vscode-python/issues/6680

**Comment by DonJayamanne** [comment]
Thank you for filing this bug, given taht we haven't had enough users report this bug and the fact taht its more of an edge case, I'm closing this for now as wont fix.
