### ISSUE TITLE
Make Interactive Windown Output Like the Visual Debugger Tab

### ISSUE THREAD

**Issue by AeneasZhu** [microsoft/vscode-jupyter#1288]
![image](https://user-images.githubusercontent.com/44701446/70106211-f1b33c80-167d-11ea-9746-de9b3324ad8d.png)

Will be doable if the output cell shown inside the pop-up tab like the visual debugger tab? Making interactive output inside pop-up tab like the visual debugger tab wouldn't be very difficult as it's been achieved by the visual debugger, is it? Another feature is that when the cursor move outside the cell the pop-up tab will disappear and show another cell's output where the cursor is.

I know vscode python team is currently working on improving the New Notebook, but it won't be compatible with 3rd-party extentions soon. Thus, I think what I suggest above is another better way  to improve the experience of data science coding of VsCode and much more doable than making Notebook compatible with 3rd-party extentions. 

Would that be possible?
@rchiodo

**Comment by amunger** [comment]
closing with low vote count
