### ISSUE TITLE
Hitting ESC in kernel picker step does not dismiss whole quick pick

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-jupyter#12887]
Testing #11904

1. Go into the kernel picker
2. Select Python Environments
3. Select the option to create a new Environment,
4. Select Venv
5. Press `esc` -> quick pick is not dismissed. I am just taken to the previous step

This might be expected behaviour of multi step quick pick (@TylerLeonhardt ?). But in the test plan item you mentioned that this is not expected, thus I am creating this issue just in case.

**Comment by DonJayamanne** [comment]
@isidorn sorry, I hadn't merged the changes at the time, did not realize that.
Please could you test this once again with the latest pre-release bits in vscode insiders.

**Comment by isidorn** [comment]
Thank you. I have tested it out and it works as expected. Thus closing.
