### ISSUE TITLE
No direct cell output when CDN disabled

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-jupyter#12893]
Testing #12874

On insiders.vscode.dev on Microsoft Edge
Jupyter extension version: v2023.2.1000531229
Python extension version: v2023.3.10481011
Using ipywidgets 7

1. Create a new notebook
2. Add the following cell
```py
# Sample1
from ipyleaflet import Map, Marker

center = (52.204793, 360.121558)

m = Map(center=center, zoom=15)

marker = Marker(location=center, draggable=True)
m.add_layer(marker);

display(m)
```
3. Configure `"jupyter.widgetScriptSources": []` in user settings. Reload.
4. Run the cell.
5. :bug: The output is blank. The status is a checkmark, but several seconds later, an error dialog pops up saying that I need to allow access to CDNs. I was expecting the status to be an X with a status message saying that a result couldn't be produced because access to CDNs wasn't allowed.

**Comment by DonJayamanne** [comment]
This should be fixed in the latest pre-release version of the Jupyter extension

**Comment by rzhao271** [comment]
Doesn't seem to be working with Jupyter extension version v2023.2.1000541047

The result is still blank, and there's a checkmark.
![Screenshot showing cell and checkmark](https://user-images.githubusercontent.com/7199958/220790013-0aa498d3-bea4-42c8-8e17-ca428d8a2749.png)

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.
Also, please could you check if there are any errors in the console window in `Developer Tools`

**Comment by rzhao271** [comment]
There's a few errors in the console window in devtools:
```
extension.web.bundle.js:11 
        
       Uncaught (in promise) Error: Python Extension API not exported
    at R.registerHooks (extension.web.bundle.js:11:336057)
    at R.init (extension.web.bundle.js:11:335409)
    at R.getNewApi (extension.web.bundle.js:11:335178)
    at M.getApi (extension.web.bundle.js:11:345442)
    at M.hookupOnDidChangeInterpreterEvent (extension.web.bundle.js:11:348376)
    at M.getInterpreters (extension.web.bundle.js:11:340971)
    at M.populateCachedListOfInterpreters (extension.web.bundle.js:11:345696)
    at M.buildListOfInterpretersForFirstTime (extension.web.bundle.js:11:347750)
    at M.hookupOnDidChangeInterpreterEvent (extension.web.bundle.js:11:348333)
    at M.get onDidChangeInterpreter [as onDidChangeInterpreter] (extension.web.bundle.js:11:340501)
```

There's also the following error, though I purposely have CDN disabled:
```
Error: Module jupyter-leaflet, semver range ^0.17 is not registered as a widget module
```

Logs:
[jupyter-output-view-output.txt](https://github.com/microsoft/vscode-jupyter/files/10827891/jupyter-output-view-output.txt)
[devtools-log.log](https://github.com/microsoft/vscode-jupyter/files/10827892/devtools-log.log)

**Comment by DonJayamanne** [comment]
Closing as not planned, not worth this as its only when users change between multiple options.
So far we have never run into this.

**Comment by DonJayamanne** [comment]
Going to re-open as this is will need to be fixed, else its just a pain when testing

**Comment by DonJayamanne** [comment]
Not worth the effort.
