### ISSUE TITLE
Error: WidgetManager already initialized

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-jupyter#12892]
Testing #12874

Jupyter extension version: v2023.2.1000531229
Python extension version: v2023.3.10481011
Using ipywidgets 7

1. Create a new notebook.
2. Add the following cell
```py
# Sample1
from ipyleaflet import Map, Marker

center = (52.204793, 360.121558)

m = Map(center=center, zoom=15)

marker = Marker(location=center, draggable=True)
m.add_layer(marker);

display(m)
```
3. Run the notebook.
4. Add the following cell
```py
# Sample2
import k3d
import numpy as np
from numpy import sin,cos,pi
from ipywidgets import interact, interactive, fixed
import ipywidgets as widgets
import time
import math

plot = k3d.plot()

plot.camera_auto_fit = False

T = 1.618033988749895
r = 4.77
zmin,zmax = -r,r
xmin,xmax = -r,r
ymin,ymax = -r,r
Nx,Ny,Nz = 77,77,77

x = np.linspace(xmin,xmax,Nx)
y = np.linspace(ymin,ymax,Ny)
z = np.linspace(zmin,zmax,Nz)
x,y,z = np.meshgrid(x,y,z,indexing='ij')
p = 2 - (cos(x + T*y) + cos(x - T*y) + cos(y + T*z) + cos(y - T*z) + cos(z - T*x) + cos(z + T*x))
iso = k3d.marching_cubes(p.astype(np.float32),xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax, zmin=zmin, zmax=zmax, level=0.0)
plot += iso

plot.display()
```
5. Run the entire notebook again.
6. Run the first cell again.
7. :bug: No rendered outputs.

Devtools errors:
I see a few `WebSocket is already in CLOSING or CLOSED state.` errors, but the more immediate errors are the `Error: WidgetManager already initialized` errors, which I see whenever I run the notebook again.

**Comment by rzhao271** [comment]
It's harder for me to repro the issue with ipywidgets 8, but I hit the issue again.
The failure to render upon a re-run seems to occur when the `WebSocket is already in CLOSING or CLOSED state.` error occurs.

**Comment by DonJayamanne** [comment]
> The failure to render upon a re-run seems to occur when the WebSocket is already in CLOSING or CLOSED state. error occurs.

this is a know issue with the Jupyter server itself, they have an upstream issue for this.
will see if tehre'a work around for this.

> WidgetManager already initialized

I should change this message to a warning or information (its actually not an error)
Having this as an error confuses users (like your self and could lead users down the wrong path)

**Comment by rzhao271** [comment]
Seems like the notebooks render fine after that change using ipywidget 8.

**Comment by DonJayamanne** [comment]
If that works, then lets close this issue as resolved.
If there are other issues or this is still unresolved please feel free to re-open this issue
