### ISSUE TITLE
await jupyterApi.getKernelService() returns object with status undefined

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#12899]
## Environment data

-   VS Code version: 1.76.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2023.2.1000541047
-   Python Extension version (available under the Extensions sidebar): v2023.3.10531009
-   OS (Windows | Mac | Linux distro) and version: macOS 13.2.1
-   Python and/or Anaconda version: Python 3.9.7, Anaconda 23.1.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

Calling to `jupyterApi.getKernelService()` should return an object with a status property.

## Actual behaviour

Calling to `jupyterApi.getKernelService()` returns an object with a property with value `undefined`.

---

Should there be a default value for this property? https://github.com/microsoft/vscode-jupyter/blob/a95a92f351441090428c6f77102f5131b2390185/src/kernels/kernelFinder.ts#L29

**Comment by DonJayamanne** [comment]
> Calling to jupyterApi.getKernelService() returns an object with a property with value undefined.

This happens when access to this API is not allowed.
Please provide the logs or please could you confirm the extension is allowed to access this API.

**Comment by DonJayamanne** [comment]
Filed a separate issue for the default value https://github.com/microsoft/vscode-jupyter/issues/12903

**Comment by DonJayamanne** [comment]
@sadasant does this cause any bugs today (within the jupyter extension) or is it just causing issues outside jupyter (e.g. you expect it to be a string value and it isn't hence causes issues at your end).

**Comment by sadasant** [comment]
@DonJayamanne it's on my end. I made a PR originally on my end assuming that undefined was equivalent to `idle`, but then I looked at the type and thought that undefined wasn't supposed to be a value anyway, so I made this issue 🙂
