### ISSUE TITLE
Restarting cell debugging unsupported notification

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-jupyter#1289]
I'd like to resurface [this suggestion](https://github.com/microsoft/vscode-python/issues/6624#issuecomment-514048685) by @DonJayamanne to notify users that restarting cell debug sessions is unsupported:

> Can I suggest we display an error indicating this feature isn't supported. This way we know it's not a bug, instead it is by design.

## Related

microsoft/vscode-python#6624

**Comment by roblourens** [comment]
This is fixed
