### ISSUE TITLE
widget will not load if CDNs were previously disabled

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12895]
Testing #12874

1. delete `"jupyter.widgetScriptSources"` setting if it exists
2. run the first complex example in the test plan
3. click yes on the prompt to enable download sources
:bug: empty display. run again - still empty

**Comment by DonJayamanne** [comment]
This is an edge case that we only run into when testing various options.
Given the fact that no one has reported this and we haven't had similar reports, I'm closing this
