### ISSUE TITLE
Errors rendering ipywidgets

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#12890]
Testing #12875

- Follow the steps to install ipywidgets 7.7.2 and run the "more complex" samples
- Sometimes they work, and sometimes I see a lot of errors and the output is not rendered

The log output is really long, here are examples

<img width="556" alt="image" src="https://user-images.githubusercontent.com/323878/220421486-ffee1381-e190-4eba-acda-0b4ac083370f.png">

<img width="555" alt="image" src="https://user-images.githubusercontent.com/323878/220421545-d2d72403-1532-49cc-ac6e-863e7e3660d7.png">

<img width="558" alt="image" src="https://user-images.githubusercontent.com/323878/220421617-b60b30e2-c802-4742-8016-82841548b7b6.png">

Wondering whether I have an incompatible version of these sub-dependencies installed?

**Comment by roblourens** [comment]
And for #12874, maybe this is related so I'll mention it here

- Run "sample 3"
```py
# Sample3
import numpy as np
from bqplot import pyplot as plt

# And creating some random data
size = 100
np.random.seed(0)
x_data = np.arange(size)
y_data = np.cumsum(np.random.randn(size)  * 100.0)
plt.figure(title='My First Plot')
plt.plot(x_data, y_data)
plt.show()
```

- It correctly renders the output
- Click `...` and "Change Presentation"
- Select the text option
- Switch back to the rich renderer
- It fails to render the rich output
<img width="490" alt="image" src="https://user-images.githubusercontent.com/323878/220423429-4267e3c5-0ec5-4175-8dd0-f6f415b023a7.png">

Here's the text

```
Error rendering output item using 'jupyter-ipywidget-renderer'
Widget is not attached.
```

This error is printed a few times

<img width="648" alt="image" src="https://user-images.githubusercontent.com/323878/220423576-7b8e9793-85ff-402d-9fe0-80e61741e30f.png">

**Comment by DonJayamanne** [comment]
> It correctly renders the output
Click ... and "Change Presentation"
Select the text option
Switch back to the rich renderer
It fails to render the rich output

Switching between text and then ipywidgets is not supported, you must be in ipywidget renderer always.
That is a known issue.

**Comment by DonJayamanne** [comment]
@roblourens 
Could you try the following
* Create a new python environment
* pip install `ipywidgets==7.7.2 ipykernel k3d`
* Now try rendering the widget by running a cell

**Comment by DonJayamanne** [comment]
@roblourens this should be fixed now, please re-test
