### ISSUE TITLE
Can't start ipykernel when launching vscode from WSL

### ISSUE THREAD

**Issue by revz79** [microsoft/vscode-jupyter#1290]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Start VS Code from WSL
2. Create a python virtual environment and select it as python interpreter
3. Activate the virtual environment and install ipykernel
4. Create and edit a .ipynb file
5. Execute it

## Actual behavior

Notification area shows this message

StdErr from ShellExec, your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
 for . /home/revz/devel/python/notebooks/catch4/env/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/pyvsc-run-isolated.py /home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/printEnvVariables.py
### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local 
-   **Extension version:** 2020.9.114305
-   **VS Code version:** 1.50.1 (user setup)
-   **Setting python.jediEnabled:** using pylance
-   **Setting python.languageServer:** Pylance
-   **Python and/or Anaconda version:** 3.8.5
-   **OS:**  Windows_NT x64 10.0.20236 - WSL2 Ubuntu 20.04
-   **Virtual environment:** venv 

## Python Output

Error 2020-10-19 13:01:19: Jupyter Kernel Spec not found for a local connection
Error 2020-10-19 13:01:20: getActivatedEnvironmentVariables [Error: StdErr from ShellExec, your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
 for . /home/revz/devel/python/notebooks/catch4/env/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/pyvsc-run-isolated.py /home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/printEnvVariables.py
	at E.getActivatedEnvironmentVariablesImpl (/home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/out/client/extension.js:56:799964)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
Error 2020-10-19 13:01:20: getActivatedEnvironmentVariables, Class name = E, completed in 235ms, has a falsy return value, Arg 1: <Uri:/home/revz/devel/python/notebooks/catch4/test.ipynb>, Arg 2: {"architecture":3,"path":"/home/revz/devel/python/notebooks/catch4/env/bin/python","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5-final","major":3,"minor":8,"patch":5,"prerelease":["final"],"build":[],"version":"3.8.5-final"},"sysPrefix":"/home/revz/devel/python/notebooks/catch4/env","fileHash":"a68d09f1a0ebabab404ab39bc948d0b28b61f6b8e6b44b7fff5f4a71ac9ef778fe34d590e084adfb6146fc43ca720e4fe30def837aab7e80ec22da55a3baeed2","envName":"env","type":"Venv","displayName":"Python 3.8.5 64-bit ('env')"}, Arg 3: true [Error: StdErr from ShellExec, your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
 for . /home/revz/devel/python/notebooks/catch4/env/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/pyvsc-run-isolated.py /home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/printEnvVariables.py
	at E.getActivatedEnvironmentVariablesImpl (/home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/out/client/extension.js:56:799964)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
Error 2020-10-19 13:01:20: Failed to create the daemon service, defaulting to activated environment [Error: StdErr from ShellExec, your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
 for . /home/revz/devel/python/notebooks/catch4/env/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/pyvsc-run-isolated.py /home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/printEnvVariables.py
	at E.getActivatedEnvironmentVariablesImpl (/home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/out/client/extension.js:56:799964)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
Error 2020-10-19 13:01:20: Failed to connect raw kernel session: Error: StdErr from ShellExec, your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
 for . /home/revz/devel/python/notebooks/catch4/env/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/pyvsc-run-isolated.py /home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/printEnvVariables.py
Error 2020-10-19 13:01:20: DataScience Error [Error: StdErr from ShellExec, your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
 for . /home/revz/devel/python/notebooks/catch4/env/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/pyvsc-run-isolated.py /home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/printEnvVariables.py
	at E.getActivatedEnvironmentVariablesImpl (/home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/out/client/extension.js:56:799964)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
Error 2020-10-19 13:01:20: getActivatedEnvironmentVariables [Error: StdErr from ShellExec, your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
 for . /home/revz/devel/python/notebooks/catch4/env/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/pyvsc-run-isolated.py /home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/printEnvVariables.py
	at E.getActivatedEnvironmentVariablesImpl (/home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/out/client/extension.js:56:799964)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
Error 2020-10-19 13:01:20: getActivatedEnvironmentVariables, Class name = E, completed in 282ms, has a falsy return value, Arg 1: <Uri:/home/revz/devel/python/notebooks/catch4/test.ipynb>, Arg 2: {"architecture":3,"path":"/home/revz/devel/python/notebooks/catch4/env/bin/python","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5-final","major":3,"minor":8,"patch":5,"prerelease":["final"],"build":[],"version":"3.8.5-final"},"sysPrefix":"/home/revz/devel/python/notebooks/catch4/env","fileHash":"a68d09f1a0ebabab404ab39bc948d0b28b61f6b8e6b44b7fff5f4a71ac9ef778fe34d590e084adfb6146fc43ca720e4fe30def837aab7e80ec22da55a3baeed2","envName":"env","type":"Venv","displayName":"Python 3.8.5 64-bit ('env')"}, Arg 3: true [Error: StdErr from ShellExec, your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
 for . /home/revz/devel/python/notebooks/catch4/env/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/pyvsc-run-isolated.py /home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/printEnvVariables.py
	at E.getActivatedEnvironmentVariablesImpl (/home/revz/.vscode-server/extensions/ms-python.python-2020.9.114305/out/client/extension.js:56:799964)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by rchiodo** [comment]
This isn't reproing for me anymore. Works fine if I:

1. Launch Code from a WSL prompt
1. Install a new venv
1. Run a cell in the interactive window (it will ask to install ipykernel and then the interactive window opens).

**Comment by DJN1** [comment]
I can confirm that this has resolved itself somehow.
Thanks!

**Comment by tarasivashchuk** [comment]
FYI this happens if you exit VS Code with an open instance of the integrated terminal. To fix:
1. close all your integrated terminals
2. exit vscode
3. restart wsl
4. open vscode
5. open your notebook before opening an integrated terminal
6. boom
