### ISSUE TITLE
Provide option to opt-out (or opt-in) to storing vscode metadata in ipynb

### ISSUE THREAD

**Issue by arthurzenika** [microsoft/vscode-jupyter#12914]
I came across this problem while running https://github.com/Yelp/detect-secrets  as a pre-commit https://pre-commit.com/ on the ipynb files I wanted to commit to git. 

![Screenshot from 2023-02-23 17-03-28](https://user-images.githubusercontent.com/445200/220962975-3edb4c6e-ac98-43b0-a28b-480aba9f1f4d.png)
 
When looking at those lines I find 

![Screenshot from 2023-02-23 16-58-00](https://user-images.githubusercontent.com/445200/220963065-2dcef7a6-63c2-4bc4-8912-74ea61f61732.png)

It would be nice to have an option to disable writing this metadata. (In python code I can add some context and comments to tell detect-secrets to ignore a line, but here in json I'm not sure there is a way to go around this).

**Comment by DonJayamanne** [comment]
@arthurzenika 
We are planning on removing this 
In vscode insiders you will not see this anymore.
In fact you can test this today in the stable version of VS Code
* Open settings
* Search for `Kernel picker`
* Change the value to `mru`
![Screenshot 2023-02-24 at 05 53 45](https://user-images.githubusercontent.com/1948812/221003215-a04a448b-762f-496a-9f3f-b42bbd769bb5.png)


Closing as fixed, as we need to ship the new kernel picker experience, probably next month.

**Comment by arthurzenika** [comment]
Good news, thanks for the info.
