### ISSUE TITLE
[jupyter] Possible delay in output for stdin redirect? Support for inline inputs?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [microsoft/vscode-jupyter#12927]
I tried out a workflow similar to the following in VSCode's (awesome!) notebook integration:
https://github.com/EricCousineau-TRI/repro/blob/88361109/drake_stuff/notebooks/vscode_input.ipynb

Some notes:
- There seems to be occasional input delay?
- ~Side request: Is it possible to inline the prompt, similar to how Jupyter Lab does it?~ Upvoted #11732 per below.

Attached is a video showing Jupyter Lab (3.5.2) and VSCode (1.75.1)

https://user-images.githubusercontent.com/26719449/221248717-089ad94f-63b4-4c11-a37d-924f6a813739.mp4

Sorry for coupling possible bug + feature, but maybe they're related? (e.g. new feature means easier to debug the delay?)

**Comment by DonJayamanne** [comment]
@EricCousineau-TRI thanks for filing this issue
I'm not sure i understand the issue

Is the delay in the time being displayed, time of 18s in VS Code?


On a side note, debugging using pdb in notebooks within vscode is not supported, isntead please use the regular debugger (next to the run button you can see a down arrow, if you click that you will have a `Debug cell` option)

![Screenshot 2023-02-27 at 14 32 56](https://user-images.githubusercontent.com/1948812/221466709-c9429863-bf9c-4f6d-a9cf-6b2e29e8fc64.png)

**Comment by DonJayamanne** [comment]
> Support for inline inputs

This is a separate issue see here https://github.com/microsoft/vscode-jupyter/issues/11732
Please upvote that issue

**Comment by EricCousineau-TRI** [comment]
>  Please upvote that issue

Done!

> On a side note, debugging using pdb in notebooks within vscode is not supported, isntead please use the regular debugger [...]

Ah, just tried this out, checking "Breakpoints > Raised Exceptions", which covers my intended use case!

FWIW, I was using `pdb` so I could add targeted debugging similar to:
https://github.com/gotcha/ipdb/blob/0.13.11/ipdb/__main__.py#L228-L241

> Is the delay in the time being displayed, time of 18s in VS Code and the fact that the spinner icon appears against the cell?

Not the spinner cell, but instead that it (inconsistently) took some time for output to appear.
In the video, the first portion shows Jupyter Lab, and there is no delay between providing an expression and getting its output.
The second portion shows VSCode, where there is *sometimes* no delay, but sometimes there is.

At 15s, I input `my_func(2)`, which outputs `3` immediately great!
At 20s, I input `my_func(3)`, but it doesn't immediately output. I have to input additional expressions, which eventually flush to the output.

Does this make sense?

**Comment by DonJayamanne** [comment]
Can you try without pdb and try again
I haven’t seen any delays
Also when you do try it please share the following logs

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
