### ISSUE TITLE
Native Notebook: printed text missing in HTML display

### ISSUE THREAD

**Issue by ajasja** [microsoft/vscode-jupyter#1292]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

Example code cell to run in Notebook Preview cell.
```python
import pandas as pd
from IPython.display import display
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
print("BEFORE STRING")
display(df)
print("AFTER STRING")
```

## Actual behavior
The `AFTER STRING` is missing from display

![image](https://user-images.githubusercontent.com/19926/95803626-70710100-0cb5-11eb-97d4-671368e05406.png)

In plain text things work as expected (maybe a new line should be there...)
![image](https://user-images.githubusercontent.com/19926/95803662-88488500-0cb5-11eb-9ace-f24f722886e6.png)

## Expected behavior
`AFTER STRING` should be visible.

### Your Jupyter and/or Python environment

-   **Jupyter server running:** Remote
-   **Extension version:** v2020.10.302853766-dev
-   **VS Code version:** 1.51-insiders
-   **Setting python.jediEnabled:** true | false
-   **Setting python.languageServer:** Jedi | Microsoft | None
-   **Python and/or Anaconda version:** 3.7
-   **OS:** Windows local, Linux remote
-   **Virtual environment:** conda 

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by greazer** [comment]
I am not reproing the main issue in the bits we recently shipped. I'm also not reproing @Trollgeir's behavior.  

![image](https://user-images.githubusercontent.com/11685408/99308278-989bd480-280c-11eb-9532-3f4bfd2233d7.png)
