### ISSUE TITLE
Failed to start the kernel. Kernel Python 3.11.0 is not usable

### ISSUE THREAD

**Issue by rishi18722** [microsoft/vscode-jupyter#12928]
## Environment data

-   VS Code version: 1.75.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.1.2010391206
-   Python Extension version (available under the Extensions sidebar): v2023.2.0
-   OS (Windows | Mac | Linux distro) and version: Mac Ventura 13.1
-   Python and/or Anaconda version: 3.11.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Just trying to run a cell with "import numpy". This error comes up

## Logs

Visual Studio Code (1.75.1, undefined, desktop)
Jupyter Extension Version: 2023.1.2010391206.
Python Extension Version: 2023.2.0.
Workspace folder /Users/reeshavchowdhury/Desktop/hello
warn 23:55:17.887: Exception while attempting zmq : No native build was found for platform=darwin arch=arm64 runtime=electron abi=106 uv=1 armv=8 libc=glibc node=16.14.2 electron=19.1.9
    loaded from: /Users/reeshavchowdhury/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/node_modules/zeromq

User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 23:55:17.966: LSP Notebooks experiment is enabled
info 23:55:18.324: Find preferred kernel for /Users/reeshavchowdhury/Desktop/hello/Untitled-1.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.11.0"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49"}}} & preferred interpreter /usr/local/bin/python3
info 23:55:18.325: Find preferred kernel for /Users/reeshavchowdhury/Desktop/hello/Untitled-1.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.11.0"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49"}}} & preferred interpreter /usr/local/bin/python3
info 23:55:18.355: Find preferred kernel for /Users/reeshavchowdhury/Desktop/hello/Untitled-1.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.11.0"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49"}}} & preferred interpreter /usr/local/bin/python3
info 23:55:18.355: Preferred kernel .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher is exact match or top match for non python kernels, (true, [object Object], true, false)
info 23:55:18.355: PreferredConnection: .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher found for NotebookDocument: /Users/reeshavchowdhury/Desktop/hello/Untitled-1.ipynb
info 23:55:18.359: Find preferred kernel for /Users/reeshavchowdhury/Desktop/hello/Untitled-1.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.11.0"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49"}}} & preferred interpreter /usr/local/bin/python3
info 23:55:18.548: Preferred kernel .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, [object Object], true, false)
info 23:55:18.548: PreferredConnection: .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher found for NotebookDocument: /Users/reeshavchowdhury/Desktop/hello/Untitled-1.ipynb
info 23:55:18.622: Process Execution: > /usr/local/bin/python3 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /usr/local/bin/python3 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 23:55:18.623: Process Execution: > /usr/local/bin/python3 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /usr/local/bin/python3 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 23:55:18.625: Process Execution: > /usr/local/bin/python3 -m pip list
> /usr/local/bin/python3 -m pip list
info 23:55:19.190: Process Execution: > /usr/local/bin/python3 -m jupyter kernelspec --version
> /usr/local/bin/python3 -m jupyter kernelspec --version
info 23:55:25.929: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.11.0 (v3.11.0:deaf509e8f, Oct 24 2022, 14:43:23) [Clang 13.0.0 (clang-1300.0.29.30)]) for '/Users/reeshavchowdhury/Desktop/hello/Untitled-1.ipynb' (disableUI=false)
info 23:55:25.930: Checking for server existence.
info 23:55:25.930: Connecting to server
info 23:55:25.930: Launching server
info 23:55:25.931: Starting Notebook
info 23:55:25.933: Generating custom default config at /var/folders/nj/m3trckyn7blcd0sjcc8jmr740000gn/T/7259f5d7-6e08-4745-9d08-def372d13891/jupyter_notebook_config.py
Starting Jupyter from /usr/local/bin/python3 with arguments --no-browser --notebook-dir="/Users/reeshavchowdhury/Desktop/hello" --config=/var/folders/nj/m3trckyn7blcd0sjcc8jmr740000gn/T/7259f5d7-6e08-4745-9d08-def372d13891/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
info 23:55:25.976: Process Execution: > /usr/local/bin/python3 -m jupyter notebook --no-browser --notebook-dir="/Users/reeshavchowdhury/Desktop/hello" --config=/var/folders/nj/m3trckyn7blcd0sjcc8jmr740000gn/T/7259f5d7-6e08-4745-9d08-def372d13891/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> /usr/local/bin/python3 -m jupyter notebook --no-browser --notebook-dir="/Users/reeshavchowdhury/Desktop/hello" --config=/var/folders/nj/m3trckyn7blcd0sjcc8jmr740000gn/T/7259f5d7-6e08-4745-9d08-def372d13891/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
/Users/reeshavchowdhury/opt/anaconda3/lib/python3.9/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/reeshavchowdhury/Desktop/hello' instead of '"/Users/reeshavchowdhury/Desktop/hello"' if you require traitlets >=5.
  warn(
[W 2023-02-24 23:55:30.614 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-24 23:55:30.614 LabApp] 'config_file' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2023-02-24 23:55:30.614 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-24 23:55:30.614 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-24 23:55:30.614 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2023-02-24 23:55:30.619 LabApp] JupyterLab extension loaded from /Users/reeshavchowdhury/opt/anaconda3/lib/python3.9/site-packages/jupyterlab
[I 2023-02-24 23:55:30.619 LabApp] JupyterLab application directory is /Users/reeshavchowdhury/opt/anaconda3/share/jupyter/lab
[I 23:55:30.623 NotebookApp] Serving notebooks from local directory: /Users/reeshavchowdhury/Desktop/hello
[I 23:55:30.623 NotebookApp] Jupyter Notebook 6.4.12 is running at:
[I 23:55:30.623 NotebookApp] http://localhost:8888/?token=eca1abc9adaf89529d4c9dc456bca2bc8a3cbe6407b559c1
[I 23:55:30.623 NotebookApp]  or http://127.0.0.1:8888/?token=eca1abc9adaf89529d4c9dc456bca2bc8a3cbe6407b559c1
[I 23:55:30.623 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
info 23:55:30.627: Process Execution: > /usr/local/bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/local/bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[C 23:55:30.626 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/reeshavchowdhury/Library/Jupyter/runtime/nbserver-82552-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=eca1abc9adaf89529d4c9dc456bca2bc8a3cbe6407b559c1
     or http://127.0.0.1:8888/?token=eca1abc9adaf89529d4c9dc456bca2bc8a3cbe6407b559c1
info 23:55:30.630: Process Execution: > /usr/local/bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/local/bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/vscode_datascience_helpers/getServerInfo.py
info 23:55:31.120: Connecting server kernel http://localhost:8888/
info 23:55:31.120: Creating server with url : http://localhost:8888/
info 23:55:31.123: Server started.
[I 23:55:31.287 NotebookApp] Creating new notebook in 
info 23:55:31.321: installMissingDependencies /usr/local/bin/python3, ui.disabled=false for resource '/Users/reeshavchowdhury/Desktop/hello/Untitled-1.ipynb'
info 23:55:31.325: Process Execution: > /usr/local/bin/python3 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /usr/local/bin/python3 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 23:55:31.418: Spec argv[0] updated from '/usr/local/bin/python3' to '/usr/local/bin/python3'
[I 23:55:31.486 NotebookApp] Kernel started: 5af0c4ca-c30d-4b58-92c4-3b93ec5f47fc, name: pythonjvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49
[W 23:55:31.499 NotebookApp] delete /Untitled-1-jvsc-9b044659-3432-44b3-b923-5416f949ebe52d3620f1-d5d7-4adf-aa8a-3035b1390571.ipynb
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/reeshavchowdhury/Library/Python/3.11/lib/python/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/Users/reeshavchowdhury/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelapp.py", line 51, in <module>
    from .ipkernel import IPythonKernel
  File "/Users/reeshavchowdhury/Library/Python/3.11/lib/python/site-packages/ipykernel/ipkernel.py", line 19, in <module>
    from .comm.comm import BaseComm
  File "/Users/reeshavchowdhury/Library/Python/3.11/lib/python/site-packages/ipykernel/comm/__init__.py", line 3, in <module>
    from .comm import Comm
  File "/Users/reeshavchowdhury/Library/Python/3.11/lib/python/site-packages/ipykernel/comm/comm.py", line 14, in <module>
    from ipykernel.kernelbase import Kernel
  File "/Users/reeshavchowdhury/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 35, in <module>
    import psutil
  File "/Users/reeshavchowdhury/Library/Python/3.11/lib/python/site-packages/psutil/__init__.py", line 123, in <module>
    from . import _psosx as _psplatform
  File "/Users/reeshavchowdhury/Library/Python/3.11/lib/python/site-packages/psutil/_psosx.py", line 13, in <module>
    from . import _psposix
  File "/Users/reeshavchowdhury/Library/Python/3.11/lib/python/site-packages/psutil/_psposix.py", line 28, in <module>
    from . import _psutil_osx
ImportError: dlopen(/Users/reeshavchowdhury/Library/Python/3.11/lib/python/site-packages/psutil/_psutil_osx.abi3.so, 0x0002): tried: '/Users/reeshavchowdhury/Library/Python/3.11/lib/python/site-packages/psutil/_psutil_osx.abi3.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/reeshavchowdhury/Library/Python/3.11/lib/python/site-packages/psutil/_psutil_osx.abi3.so' (no such file), '/Users/reeshavchowdhury/Library/Python/3.11/lib/python/site-packages/psutil/_psutil_osx.abi3.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by amunger** [comment]
There have been a few fixes that went in this month, can you try the latest pre-release of the jupyter extension and see if that resolves the issue.

There is also a [known issue](https://github.com/jupyter/notebook/issues/6721) in the latest version of jupyter that you might be hitting if this is a new environment. I think the workaround would just be to downgrade the jupyter package manually, but @DonJayamanne would know more.

**Comment by rishi18722** [comment]
> There have been a few fixes that went in this month, can you try the latest pre-release of the jupyter extension and see if that resolves the issue.
> 
> There is also a [known issue](https://github.com/jupyter/notebook/issues/6721) in the latest version of jupyter that you might be hitting if this is a new environment. I think the workaround would just be to downgrade the jupyter package manually, but @DonJayamanne would know more.

I tried the following steps, and it didn't work.

- downgrade the jupyter package
- switch to the pre release version of the jupyter extension.
Please help me out with it

**Comment by DonJayamanne** [comment]
Thanks for filing this make and sorry you are running into Tom’s

> '/Users/reeshavchowdhury/Library/Python/3.11/lib/python/site-packages/psutil/_psutil_osx.abi3.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

Looks like you have somehow installed done wrong package into your python env 
It’s likely you might have to uninstall this and some other packages

Before we do that please try the following
Open the extensions page, search for Jupyter and click the button `Switch to Pre-Release Version`  
Similarly please install the `Pre-Release` version of the Python extension.

<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">

then try again
If that does not work then
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by thatSAMazing** [comment]
Switching to the pre-release version worked for me. Is this a known bug Don? When should I switch back to the release version?

>

**Comment by rishi18722** [comment]
Well, I was stupid enough, and needed tot change the interpreter. The interpreter selected was python 3.11.0 and the one required to be chosen was Python 3.9.13. Once I changed the interpreter to 3.9.13, the jupyter notebook immediately started working.
thank you everyone for the replies

**Comment by thatSAMazing** [comment]
Ah great! That's not the issue on my end unfortunately. Am running the right interpreter, but for some reason the pre release version got it working again. Curious what the cause is and when I'll be able to go back to the proper release
