### ISSUE TITLE
5+ minute startup time when opening a ipynb

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12926]
[jupyterLogs.txt](https://github.com/microsoft/vscode-jupyter/files/10827183/jupyterLogs.txt)
[pythonLogs.txt](https://github.com/microsoft/vscode-jupyter/files/10827184/pythonLogs.txt)

This was right after updating insiders and anti-virus was running at the time to make things worse, but I feel like perf has taken a hit lately, and this startup was especially bad so probably worth looking into.

**Comment by amunger** [comment]
might be safe to say that my PC was just in a bad state, I had to reboot as _everything_ seemed to be running slow, but I'll leave this open if you want to take a look at the logs first.

**Comment by DonJayamanne** [comment]
> > c:\src\test\6\.venv\Scripts\python.exe -m pip list
debug 09:19:55.890: interpreterPackages getPackageInformation, Class name = Xd, completed in 95426ms, has a falsy return value, Arg 1: {"interpreter":{"id":"C:\\SRC\\TEST\\6\\.VENV\\SCRIPTS\\PYTHON.EXE","sysPrefix":"c:\\src\\test\\6\\.venv","envPath":{"$mid":1,"fsPath":"c:\\src\\test\\6\\.venv","_sep":1,"path":"/c:/src/test/6/.venv","scheme":"file"},"displayPath":{"$mid":1,"fsPath":"c:\\src\\test\\6\\.venv","_sep":1,"path":"/c:/src/test/6/.venv","scheme":"file"},"envName":".venv","uri":{"$mid":1,"fsPath":"c:\\src\\test\\6\\.venv\\Scripts\\python.exe","_sep":1,"external":"file:///c%3A/src/test/6/.venv/Scripts/python.exe","path":"/c:/src/test/6/.venv/Scripts/python.exe","scheme":"file"},"displayName":".venv","envType":"Venv","version":{"major":3,"minor":11,"patch":1,"raw":"3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]"}}}
debug 09:20:17.221: Python API env change detected, add => 'C:\USERS\AAMUNGER\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON310\PYTHON.EXE'
debug 09:20:24.519: Python API env change detected, remove => 'C:\USERS\AAMUNGER\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON310\PYTHON.EXE'
debug 09:22:49.857: Conda file returned by Python Extension is conda
debug 09:22:50.065: Python API env change detected, add => 'C:\PYTHON310\PYTHON.EXE'
debug 09:22:55.596: Python API env change detected, remove => 'C:\PYTHON310\PYTHON.EXE'
debug 09:22:57.156: Python API env change detected, update => 'C:\USERS\AAMUNGER\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON37\PYTHON.EXE'
debug 09:22:57.187: Python API env change detected, update => 'C:\USERS\AAMUNGER\ANACONDA3\PYTHON.EXE'
debug 09:22:57.711: Get Active Interpreter, Class name = zo (started execution), Arg 1: "/c:/src/test/6"

Looks like VS Code (node process) was doing absolutely nothing for over 2 minutes
Most likey your PC was just too busy with other stuff.

No indication of any delays within the extension itself, hence closing this issue
If this persists in general, then please do create another issue
