### ISSUE TITLE
Ctrl+1/2 doesn't focus into input box of Interactive Window

### ISSUE THREAD

**Issue by echasnovski** [microsoft/vscode-jupyter#1293]
# Bug: Notebook Editor, Interactive Window, Editor cells

This seems to be the same issue as in microsoft/vscode-python#7597 and microsoft/vscode-python#9693. Behavior was as expected couple of days ago. Probably, changed after recent update of vscode-python extension.

## Steps to cause the bug to occur

1. Manually focus cursor in input box of Interactive Window, which is in second editor group.
2. Change focus to another editor group with Ctrl+1.
3. Change back focus to Interactive Window with Ctrl+2.
4. Try to change focus again with Ctrl+1.

## Actual behavior
- Focus hasn't returned to input box.
- Most of the times second use of Ctrl+1 doesn't have any effect. Sometimes, when focus is changed "quickly", it returns to first editor group.

Actual behavior with gif:
![vscode-python_interactive-window-focus_1](https://user-images.githubusercontent.com/24854248/81958581-dbd77980-9616-11ea-9b3c-cf7c4686f07b.gif)

Test that it works with normal file instead of Interactive Window:
![vscode-python_interactive-window-focus_2](https://user-images.githubusercontent.com/24854248/81958746-13debc80-9617-11ea-88ad-6c96b98784c3.gif)

## Expected behavior
- Focus should return to input box after Ctrl+2.
- Combinations Ctrl+1 and Ctrl+2 can be used multiple times in a row.

### Your Jupyter and/or Python environment

-   **Jupyter server running:** Local
-   **Extension version:** 2020.5.78807
-   **VS Code version:** 1.45.0
-   **Setting python.jediEnabled:** true
-   **Python and/or Anaconda version:** Python 3.8.2, conda 4.8.3
-   **OS:** Linux (Ubuntu 18.04.4):
-   **Virtual environment:** conda

## Developer Tools Console Output
I am not really sure, what should go here, as output is rather verbose.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by rchiodo** [comment]
I think I have a repro for the cat coding sample. Not sure how the focus gets lost, but this should repro in cat coding:

1. Add this to the HTML in extension.ts:

```
				<textarea id="text-area" width="450" height="400">Test</textarea>
				<textarea id="text-area-2" width="450" height="400">Test 2</textarea>
```

2. Add this to the main.js
```
let lastFocusedTextArea = (oldState && oldState.lastFocusedTextArea);

...
// Update state
        vscode.setState({ count: currentCount, lastFocusedTextArea });


    window.addEventListener('focus', () => {
        if (document.activeElement) {
            if (document.activeElement.nodeName === 'TEXTAREA') {
                lastFocusedTextArea = document.activeElement.id;
            } else if (document.activeElement.nodeName === 'BODY' && lastFocusedTextArea) {
                const elem = document.getElementById(lastFocusedTextArea);
                elem?.focus();
            }
        }

    }, true);

```

Open cat coding and put in second group.
Switch back and forth with CTRL+1 and CTRL+2. If you hit CTRL+2 a bunch really quick, focus will switch out of the window. Not sure where it went.

**Comment by rchiodo** [comment]
Root cause of problem seems to be related to this:
https://github.com/microsoft/vscode/commit/88929c7a45ec3d1b0c570113cf222ff92a860f60

and this
https://github.com/microsoft/vscode/commit/870700e95c18eff7f0827595b521a9d10a243274

What's happening now is that the blur at the top of the first commit is happening async too. Sometimes it can happen after the focus delay.

**Comment by greazer** [comment]
This problem no longer seems to repro.

**Comment by ejolly** [comment]
@greazer This is still an issue for me on the latest version of VSCode and VSCode jupyter/python extensions. And it looks like this upstream issue is still open...https://github.com/microsoft/vscode/issues/97992

**Comment by echasnovski** [comment]
Yes, this is still an issue (to a certain extent). Not immediate (requires couple of back-and-force changes between file and interactive window), but it still happens sometimes.

<details>
<summary>Gif reproducing issue</summary>

![vscode-python_interactive-window-focus_3](https://user-images.githubusercontent.com/24854248/113336891-b12a0880-932f-11eb-8774-05d8f14010e7.gif)

</details>

<details>
<summary>Versions information</summary>

```
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:24.277Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 4.15.0-29-generic
```

</details>

**Comment by leoauri** [comment]
Indeed, I am also still experiencing the issue on mac.
<details>
<summary>Version</summary>

Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z (3 wks ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
</details>

**Comment by echaya** [comment]
The issue comes back with the latest updates:

Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by echaya** [comment]
I just came up with a very simply autohotkey script (Windows) as a temp fix and remap ctrl+1 ctrl+2 to ctrl+left, ctrl+right. Hope anyone could find it helpful

``` autohotkey
#IfWinActive ahk_exe Code.exe

^Left::
{
  send ^1
  return
}
^Right::
{
  send ^2
  Sleep 10
  WinGetPos,Y,Y,W,H,A
  W_new := round(W*0.95,0)
  H_new := round(H*0.5,0)
  click, %W_new%, %H_new%
  return
}
#IfWinActive
```

**Comment by melsophos** [comment]
I also have the problem.

**Comment by echaya** [comment]
not sure if this issue can be reopened, otherwise need to open a new issuer

**Comment by fredshu** [comment]
Version 1.56 messed it up again, so reverting to 1.55.

**Comment by magickcicada** [comment]
@fredshu having same issue on 1.56(.2), but not in 1.55.

**Comment by nikhbikh** [comment]
Filed a new issue to track the regression in 1.56
https://github.com/microsoft/vscode-jupyter/issues/5985
