### ISSUE TITLE
Highlight Selected Words in another cells

### ISSUE THREAD

**Issue by michaelmiscanuk** [microsoft/vscode-jupyter#12930]
When I select a word or click on word, same words are also highlighted - but this functionality doesn't seem to work when used with cells - only highlighting selected words in the same cell. Is it not working, or do I miss something? Thanks

![image](https://user-images.githubusercontent.com/37830487/221347505-dc945d27-b260-408c-841e-63a77b9695aa.png)

**Comment by rebornix** [comment]
Let's track it in https://github.com/microsoft/vscode/issues/184259
