### ISSUE TITLE
Show variable explorer by default and create command to view it.

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode-jupyter#1294]
The variable explorer is a highly popular feature, once discovered.

We should consider showing it by default in the notebook editor and interactive window.

1. on window open, the Variable Explorer is shown in minimum height - e.g. single line. with text "No variables defined"
2. The open/close state is preserved across vs code sessions.

**Comment by IanMatthewHuff** [comment]
Covered by the new native notebook variable viewer + command.
