### ISSUE TITLE
cannot select a kernel in jupyter notebooks 

### ISSUE THREAD

**Issue by sampath017** [microsoft/vscode-jupyter#12947]
Type: <b>Bug</b>

install jupyter notebooks extention and try to run a jupyter notebook.

Extension version: 2023.1.2010391206
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.83GB (1.96GB free)|
|Process Argv|. --crash-reporter-id 4c2ee939-0c1e-4d1b-839e-2e5d5b350c7f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30672705
pythonb192:30669360

```

</details>

**Comment by amunger** [comment]
What happens when you try to run the notebook? Does the kernel picker open? Are you able to select a kernel?

Can you paste the logs from the output panel after reproducing the issue? The `Jupyter: Show Output` command will open the logs.

**Comment by sampath017** [comment]
Yep, extension didn't start and the activation status in null. Here is the log file from the developer tools console. 
[vscode-app-1677641328284.log](https://github.com/microsoft/vscode-jupyter/files/10856854/vscode-app-1677641328284.log)

**Comment by amunger** [comment]
It looks like the localization file is corrupt somehow. Can you try to uninstall and reinstall the jupyter extension to see if that fixes it?
```
mainThreadExtensionService.ts:111 Activating extension 'ms-toolsai.jupyter' failed: Invalid or unexpected token.
$onExtensionActivationError @ mainThreadExtensionService.ts:111
log.ts:404   ERR [/c:/Users/sampa/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206]: Failed to parse /c:/Users/sampa/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/package.nls.json: Invalid symbol.
log.ts:404   ERR [/c:/Users/sampa/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206]: Failed to parse /c:/Users/sampa/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/package.nls.json: Value expected.
```

**Comment by sampath017** [comment]
reinstallation through vscode didn't work but deleting the extension in the .vscode dir and install through vscode works.
