### ISSUE TITLE
PYTHONPATH not respected in Jupyter

### ISSUE THREAD

**Issue by mousey92** [microsoft/vscode-jupyter#12948]
Type: <b>Bug</b>

1. Create a custom Python package in a custom location, e.g. %USERPROFILE/test_package, complete with __init__.py
2. Add %USERPROFILE% to user or system environment variables
3. Create new Jupyter notebook
4. Try to import test package (import test_package), leads to ModuleNotFoundError
5. Check PYTHONPATH (import os; print(os.environ["PYTHONPATH"])) to see %USERPROFILE% is not in there

I cannot duplicate this issue running normal .py files with the Code Runner extension.

Even though this bug only occurs in Jupyter notebooks, reverting the Python extension to the previous version fixes the issue. I uncovered this when updating VSCode to the latest version, which also updated the Python extension (but not the Jupyter extension).

This is also not the first time an update to VSCode resulted in this behaviour.

Extension version: 2023.2.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (4.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and sorry you are running into this
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by mousey92** [comment]
Side note: my Python environment is located in c:\Users\Matthijs.Kramer\Anaconda3\envs\work. The package I'm trying to import is located in c:\Users\Matthijs.Kramer\PycharmProjects\common

[full.log](https://github.com/microsoft/vscode-jupyter/files/10849933/full.log) full log from starting VSCode to running cell

**Comment by mousey92** [comment]
Just downloaded and installed the Insiders version of VSCode and copied over all my extensions and settings from my regular install. The issue doesn't occur there.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.15GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Matthijs.Kramer/PycharmProjects/METS-tickets --crash-reporter-id 87be5129-635e-4294-98a7-478f0034beea|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30659908
vscodeenable:30660116
pythonb192cf:30661257
pythonms35:30671666

```

</details>

**Comment by DonJayamanne** [comment]
Awesome, let’s close this issue
As the fixed from insiders will go into stable
Thanks for getting back
