### ISSUE TITLE
Can't run a cell with python interpreters on the Jupyter Datascience Notebooks container

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12965]
Testing microsoft/vscode#174728

I can't figure out how to run a notebook on a container that is specifically meant for running notebooks.

1. Go to the remote explorer, select containers
2. create a new container with the "Jupyter Datascience Notebooks" configuration
3. Wait for the creation to complete

creating a Conda environment fails with 
`CondaError: Unable to create prefix directory '/workspaces/jupyter-datascience-notebooks/.conda'.
Check that you have sufficient permissions.`

creating a venv fails with 
`Error: [Errno 13] Permission denied: '/workspaces/jupyter-datascience-notebooks/.venv'`

trying to use the global environments leads to the `There is no Pip installer available in the selected environment.` error when trying to install IPykernel.

**Comment by DonJayamanne** [comment]
@amunger which container did you use, I'd like to ensure i can replicate this at my end as well.

**Comment by amunger** [comment]
![image](https://user-images.githubusercontent.com/2019016/222010519-db0afc8e-853f-4f42-a6fb-8b2a3e665351.png)

**Comment by minsa110** [comment]
Ah--that one is actually deprecated. https://github.com/microsoft/vscode-dev-containers/tree/main/containers/jupyter-datascience-notebooks

It's on my March iteration plan to create a new one (based off of that one), that our team can support

**Comment by DonJayamanne** [comment]
Closing this issue as this is not due to an issue with teh Pyton extension but due to the usage of a deprecated container/
