### ISSUE TITLE
Kernel selector does not use the "detail" value on IJupyterUriProvider

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-jupyter#12979]
## Environment data

-   VS Code version: 1.76.0
-   Jupyter Extension version (available under the Extensions sidebar): v2023.2.1000592019
-   Python Extension version (available under the Extensions sidebar): v2023.4.0
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: N/A
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: N/A

## Expected behaviour
- Kernel selector uses the `detail` property of the contributed `IJupyterUriProvider`

## Actual behaviour
- Kernel selector only uses the `displayName`

## Steps to reproduce:

1. Install Azure ML extension (I will update the right version to use once it is pre-released)
2. Open a notebook
3. Click "Select kernel" and observer the "Azure ML Compute Instances" quick pick does not contain any detail
![image](https://user-images.githubusercontent.com/56176070/222367198-75a50ec0-6fcf-4399-a05f-af0c8d94abce.png)

## Logs
```Visual Studio Code - Insiders (1.76.0-insider, undefined, desktop)
Jupyter Extension Version: 2023.2.1000592019.
Python Extension Version: 2023.4.0.
Workspace folder c:\azureml\test_yaml
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 23:55:23.072: LSP Notebooks experiment is enabled
warn 23:55:57.941: Failed to get activated env vars with python c:\Users\sevillal\AppData\Local\Microsoft\WindowsApps\python3.8.exe in 618ms
info 23:55:58.051: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.8.exe -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
> ~\AppData\Local\Microsoft\WindowsApps\python3.8.exe -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
info 23:55:59.252: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.8.exe -m pip list
> ~\AppData\Local\Microsoft\WindowsApps\python3.8.exe -m pip list
```

**Comment by DonJayamanne** [comment]
@sevillal we have decided not to display any details to reduce the content in the dropdown
Could you share the contents of the details property

**Comment by sevillal** [comment]
@DonJayamanne detail = 'Power your Notebook with an Azure ML Compute Instance'

**Comment by DonJayamanne** [comment]
I think we can try to add the `(i)` icon next to azure ML compute instance that would open a link to some webpage
That way users can get a lot more information about AZ ML, 
Meaning, I don't think the detail in AzML is enough to bring it back, and the link would be more useful (users can get more information about that from a webpage than they could from a detail).

**Comment by sevillal** [comment]
@DonJayamanne is that (i) behavior something we can contribute from the IJupyterUriProvider  API?

**Comment by DonJayamanne** [comment]
Currently there is no API for this, we can look into providing an option for this.

**Comment by DonJayamanne** [comment]
Just an update, we're looking into adding this into the new API. and we'll be reviewing the API in the sync meeting this week.

**Comment by DonJayamanne** [comment]
@sevillal this is now possible with the new Jupyter API. closing as done

**Comment by DonJayamanne** [comment]
Marking as verified as this feature is now made possible via another API which has already been tested and verified.
