### ISSUE TITLE
Clickout from AzML Studio to vscode.dev or desktop should auto-select and connect the kernel that was being used in the Studio

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#12987]
Not only should it select the same kernel based on the metadata written to the ipynb file, it should also connect to the same instance of the kernel (if one had been started). Here's the scenario:

1. Open NotebookA.ipynb in AzML Studio.
2. Choose "Azure ML Python 3.10" (or whatever name of kernel that's available on the compute).
3. Run a cell in Studio.
4. Clickout to vscode.dev.

## Expected
VSCode.dev should open in a tab with the target notebook opened and the same kernel selected. In addition, the kernel that was instantiated in AzML Studio at step 3, above, should be chosen and connected to automatically.

Note: that this scenario works as expected with Jupyter Lab and it's a two-way synchronization. Chaning the kernel in Jupyter Lab changes it in Azure ML and vice versa.

## Actual
If the notebook has not been opened before OR the user changed the kernel NotebookA was using last time, the user is presented with "Select Kernel" at the top right and has to go through several steps to find the right kernel to connect to. Steps are...

- Select Kernel button
- "Select Another Kernel..." dropdown
- "Jupyter Kernel..." (assuming user knows to do this)
- Find and choose the matching kernel manually

If the user doesn't realize they can find the alternate kernel in the "Jupyter Kernel..." choice, then they'll likely go down the 
"Azure ML compute instances..." option, which is usable, but more burdensome.

### Note
If the user changes the kernel being used for a notebook AzML Studio, then they will be forced again to go down the "Select Kernel" experience.

**Comment by DonJayamanne** [comment]
This has been fixed, an API has been provided which would allow azml to pre-select a kernel in a notebook

**Comment by DonJayamanne** [comment]
@sevillal please verify this is the case

**Comment by sevillal** [comment]
Verified.
