### ISSUE TITLE
Using Pandas Styler leads to strange import error

### ISSUE THREAD

**Issue by mapio** [microsoft/vscode-jupyter#12981]
## Environment data

-   VS Code version: 1.76.0 92da9481c0904c6adfe372c12da3b7748d74bdcb x64
-   Jupyter Extension version (available under the Extensions sidebar): v2023.2.1000592019
-   Python Extension version (available under the Extensions sidebar): v2023.4.0
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 22.04
-   Python and/or Anaconda version: Python 3.10.6 (main, Nov 14 2022, 16:10:14)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): python3 -m venv
-   Jupyter server running: Local 

## Expected behaviour

No exception.

## Actual behaviour

Raises exception `ImportError: Pandas requires version '3.0.0' or newer of 'jinja2' (version '2.11.2' currently installed).`

## Steps to reproduce:

1. create a virtualenv with  `python -m venv ...`
2. open vscode and create a new notebook
3. select the vevn as Python environment, let vscode install the ipython kernel
4. paste `! pip install pandas jinja2` in a cell and execute it
5. paste `from pandas.io.formats.style import Styler` in another cell and execute it

The first command installs 

- pandas (1.5.3),
- jinja2 (3.1.2)

but the raised issue reports version `2.11.2`.

What is even more strange is that opening a terminal in vscode, running Python and issuing `from pandas.io.formats.style import Styler` works as expected and no error is rised!

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by mapio** [comment]
This is incredibly frustrating. I've updated the OS in the mean time, by comparing `pandas.show_version()` of the linked bugrep above, I observed the bug with:

```
commit : https://github.com/pandas-dev/pandas/commit/2e218d10984e9919f0296931d92ea851c6a6faf5
python : 3.10.6.final.0
python-bits : 64
OS : Linux
OS-release : 5.15.0-60-generic
Version : https://github.com/pandas-dev/pandas/issues/66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023
machine : x86_64
processor : x86_64
byteorder : little
LC_ALL : en_US.UTF-8
LANG : en_US.UTF-8
LOCALE : en_US.UTF-8
```

but now the same function reports 

```
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.10.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.19.0-35-generic
Version          : #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8
```

I'm perfectly aware that the OS has nothing to do with the bug, but still today I can't reproduce it.

Maybe the process of upgrading Ubuntu and rebooting the machine cleared some cached file, or something else coming in the way.

I'm closing the bug now. It looks like an Heisenbug, this irritates me and of course sorry for the time I've made you spend on this.
