### ISSUE TITLE
Select a default kernel for newly created notebooks

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-jupyter#12980]
The Azure ML Extension would like to default newly created notebooks to a specific known kernel running on the managed computes, selecting a kernel manually might be cumbersome and confusing for customers.

**Comment by nickmccurdy** [comment]
I'm trying to migrate all my Jupyter notebooks to VSCode, and having to select the same kernel every time is annoying. I'd prefer it use the recommended kernel by default. For OP's use case, a setting for this would probably help as well, so it can be overridden by extensions and workspaces.

**Comment by DonJayamanne** [comment]
The necessary API has been provided an @sevillal I believe you are now using this.

**Comment by sevillal** [comment]
@DonJayamanne I don't think the API will resolve this, we end up using the API just to set the kernel to the specific notebook the Azure ML Studio user is coming from.

The goal of this item is that when VS Code is remotely connected using Azure ML remote, then any newly created notebook should default to pre-select a specific kernel that we know will be always available in the Azure ML VMs.

**Comment by DonJayamanne** [comment]
Ah yes, that’s right

**Comment by DonJayamanne** [comment]
Closing this for now, as we believe AzML extension can achieve their requirements using the existing API.
If that doesn't work we can create a new issue
