### ISSUE TITLE
Auto run feature

### ISSUE THREAD

**Issue by wybert** [microsoft/vscode-jupyter#12998]
Hi, I would like to know if we could have an auto-run feature. 

1. It will run the markdown cell automatically as Google Colab dose
2. Optional run all the cell automatically

**Comment by DonJayamanne** [comment]
> It will run the markdown cell automatically as Google Colab dose

Thanks, please could you describe this feature. I'm not aware of this.

> Optional run all the cell automatically

Not sure what you mean by this, please could you provide more information about this and how this works.

**Comment by wybert** [comment]
For the first one, 
> It will run the markdown cell automatically as Google Colab dose

in Colab, when you finish editing markdown A, and you click the other code cell or markdown cell B (without using ESC), the markdown cell A will render automatically. It's more mouse/touchpad friendly. 

For the second one,
> Optional run all the cells automatically

The code cell can have the same behavior as the markdown cell such as when losing the focus it will execute automatically. And also if we go back to change some code cells, the code cells following that cell will also execute automatically.

**Comment by DonJayamanne** [comment]
> in Colab, when you finish editing markdown A, and you click the other code cell or markdown cell B (without using ESC), the markdown cell A will render automatically. It's more mouse/touchpad friendly.

@mjbvz /cc Didn't want to create a new issue just yet.

> The code cell can have the same behavior as the markdown cell such as when losing the focus it will execute automatically. And also if we go back to change some code cells, th

@roblourens I guess this is in your area.

**Comment by roblourens** [comment]
Sorry, I'm not a fan of an auto-run feature. Re-running a cell can be destructive, slow, etc, I don't think it should ever happen without a user action
