### ISSUE TITLE
Input passwork UI does not work

### ISSUE THREAD

**Issue by XiaoxiaoMa-MQ** [microsoft/vscode-jupyter#13000]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

After activating a remote server, I tried to connect to the server using the kernel. However, the input password UI or form just flashes out, remaining only 0.1s. As a result, the connection was refused.

**Comment by DonJayamanne** [comment]
As a work around, please change the following setting to `all`
* You could add the change into  your user settings as follows
    * Open your user settings 
    * Add the following
    ```json
    "notebook.kernelPicker.type": "all"
    ```
* Or just change it in the settings editor as follows
![Screenshot 2023-03-07 at 09 49 59](https://user-images.githubusercontent.com/1948812/223274078-345d7552-5f22-4fd1-9d0e-010a8e8087a9.png)

**Comment by DonJayamanne** [comment]
@XiaoxiaoMa-MQ Please could you confirm that you have to re-enter the password everytime you re-load vscode.

**Comment by DonJayamanne** [comment]
Steps to repro:
* Start jupyter server with a password as follows
    * `python -m jupyter notebook password ` (follow the prompts and configure a password)
    * Start jupyter using the cli `python -m jupyter notebook`
    * Copy the above URL
* Open a notebook and go into the kernle picker
* Select `Existing Jupyter Servers` and enter the url
* Verify you are prompted to enter the password and can run a cell against a kernel of the remote server
