### ISSUE TITLE
UndefinedVariable in interactive window

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#13018]
## Environment data

-   Language Server version: Pylance v2023.2.20
-   Jupyter extension: v2023.1.2010391206
-   OS and version: macos 13.2 (22D49)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.12
```
Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:01.965Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No
```
## Code Snippet

```python
XXX
```

## Repro Steps

<img width="617" alt="CS-P8BCwjC9@2x" src="https://user-images.githubusercontent.com/33796896/218203376-08a015b7-a03d-4e2b-ba55-48490be01900.png">

I have also tried with the pre-release of Jupyter extension
<img width="1430" alt="CS-TY4ywsJp@2x" src="https://user-images.githubusercontent.com/33796896/218204217-a397752a-7a13-474d-9a32-483634fc7e9a.png">

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

[log.txt](https://github.com/microsoft/pylance-release/files/10711427/log.txt)

```
XXX
```

https://github.com/microsoft/pylance-release/issues/3661

**Comment by StevenLi-DS** [comment]
Hi, @debonte. Thanks for the fix. I've seen many updates of Jupyter extension. Will this be included in the next update soon?

**Comment by StevenLi-DS** [comment]
@debonte I just realized that I've been using the prerelease builds for weeks. The problem still exists in v2023.3.1000830504 somehow.

**Comment by debonte** [comment]
I can't repro it with that version. Could you please set `"python.trace.server": "verbose"`, repro it, and provide the resulting "Python Language Server" log?

Note that this setting is hidden, so you'll need to set it directly in the `settings.json` rather than via the Settings UI.

**Comment by StevenLi-DS** [comment]
@debonte I couldn't find the settings, but I did set `"python.analysis.logLevel": "Trace"`

jupyterlab: `v2023.3.1000851011`
pylance: `v2023.3.30`

[vscode-log.log](https://github.com/microsoft/vscode-jupyter/files/11067769/vscode-log.log)

<img width="1644" alt="CS-OiilzI3J@2x" src="https://user-images.githubusercontent.com/33796896/227680413-55ad0b41-08cd-422f-90b6-0fa429bcda11.png">

**Comment by debonte** [comment]
> I couldn't find the settings...

Ctrl+Shift+P to open the command palette. Then search for "Preferences: Open User Settings (JSON)". Execute that command and it will open your user `settings.json`. Add "python.trace.server": "verbose" in there.

We need to enable this to be able to see the LSP message traffic.

**Comment by StevenLi-DS** [comment]
@debonte I think it's just hidden from the UI, but still in the json file... I see...

[vscode-log.txt](https://github.com/microsoft/vscode-jupyter/files/11069239/vscode-log.txt)
ee...

**Comment by debonte** [comment]
@StevenLi-DS, thanks for the log. I'm able to repro this now and will investigate.

**Comment by debonte** [comment]
@StevenLi-DS, the second issue is now fixed. Please give it a try in the next Jupyter prerelease build.

**Comment by StevenLi-DS** [comment]
@debonte Is there any chance there could be an official release to fix this annoying issue rather than waiting antoher month since the pre-release is having issue:
```
Can't install pre-release version of 'ms-toolsai.jupyter' extension because it is not compatible with the current version of Visual Studio Code (version 1.77.2).
```

**Comment by debonte** [comment]
@StevenLi-DS, I believe that the pre-release Jupyter builds [require](https://github.com/microsoft/vscode-jupyter/blob/main/package.json#L32) VS Code Insiders.
