### ISSUE TITLE
Connecting to remote jupyter server issues

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13015]
### Scenario: Setup a password protected jupyter server
1. non-https prompt at the bottom right
* Connect to the server via the kernel picker
* After entering the URI a prompt is displayed asking the user whether to allow connecting to non-https or not
This prompt is far from the URI input, right now the user is focused on the input box and could easily miss the prompt
Should this be modal or a button right next to the URI? Or should it be part of the quick pick itself.

2. non-https prompt upon re-loading vscode
* Re-load vscode
* Open a notebook
* A prompt will be displayed at the bottom right asking whether to allow non-http servers
Why is this there, user woudl not have any idea
There is no context indicating it is related to the jupyter server
However why prompt again, when the user had already accepted this for this server once before, the server is still the same

3. prompted to enter a password opening opening a notebook after reloading vsdoe
* Re-load vscode
* Open a notebook
* User is prompted to enter a password (no idea why or what this password is for)
User could end up entering their OS password or the like.
Password should be saved in encrypted storage instead of prompting everytime

4. poor error message in kernel picker
* Re-load vscode
* Open a notebook
* Click no for https or do not enter a password (when promtped)
* Go into the kernel picker, and now user does not know exactly why the kernels are not displayed

4. no way to recover from non-https or no password
* Re-load vscode
* Open a notebook
* Click no for https or do not enter a password (when promtped)
* Go into the kernel picker, and there is an error mesage for the kernels of the remote server
* How can the user recover from this, there are no messages/instructions for resolving this.
We need a button that says `Enable non-http reqyest` `Enter Password` or `Retry Connection`, that would then prompt the user for the missing information (go though the same process that we go though when entering the URI)

### We try to figure out whether its jupyter hub or not
I think it would be better to prompt the user to make the selection
I.e. have two options, 
* Enter Jupyter Server (Notebook/Lab)
* Enter Jupyter Hub Uri

Or have a separate entry in the jupyter servers for Jupyter Hub

**Comment by joyceerhl** [comment]
In vscode.dev when you select to connect to an existing Jupyter server, a dummy URL is prepopulated in the picker:

<img width="673" alt="image" src="https://user-images.githubusercontent.com/30305945/226468689-ab7c58d1-eedf-4a0f-86f4-03b646392358.png">

This is quite misleading to the user IMO, can we consider showing this text as a placeholder rather than populating the text?

**Comment by DonJayamanne** [comment]
@joyceerhl are you trying the latest stable or pre-reelase.
I'm surprised you are seeing this, as I thought this was fixed a while ago in the jupyter exetnsion.

**Comment by bamurtaugh** [comment]
@DonJayamanne this was in the latest insiders.vscode.dev (as of this Monday) during user testing. Users opened https://insiders.vscode.dev/github/bamurtaugh/python-tuples and installed the Python and Jupyter extensions from the extension recommendation. Is there a chance they got an old version of the extension, even though they were in the latest insiders.vscode.dev?

**Comment by DonJayamanne** [comment]
> even though they were in the latest insiders.vscode.dev?

most likely
As we have removed that code and I could not replicate it

**Comment by joyceerhl** [comment]
@DonJayamanne doesn't this code here prefill the input box with the dummy `defaultURI` still? 
https://github.com/microsoft/vscode-jupyter/blob/adfc442a2178eff34d9cdc5aa049acecfbc9e8a9/src/kernels/jupyter/connection/serverSelector.ts#L357-L370

**Comment by DonJayamanne** [comment]
Oh, i could have sworne we removed that, will remove that, https://github.com/microsoft/vscode-jupyter/issues/13144

**Comment by bamurtaugh** [comment]
After observing users go through this flow in vscode.dev, I have a couple feedback points - let me know if they should be separate issues or tracked in this one:

- Pasting anything for users in the server input field - they'll often assume it's correct, even if it's a bogus URL: https://github.com/microsoft/vscode-jupyter/issues/13285
- When users enter vanilla vscode.dev without any remote Jupyter server, they're very confused. They assume Jupyter has generated and will provide them a remote server. Can we explore how to make this process clearer, like potentially guiding users to "Continue Working On" in the case switching dev environments is a better choice for them?
![image](https://user-images.githubusercontent.com/25310137/230459765-598747a1-3a08-4dd8-b818-0f718df02d3c.png)

**Comment by DonJayamanne** [comment]
We have individual issues for each, and others have been resolved.
Closing this issue.

**Comment by andreamah** [comment]
Are there some verif steps for this?

**Comment by DonJayamanne** [comment]
No, 

> We have individual issues for each

marking as verified
