### ISSUE TITLE
Execution time for our notebooks is slower than Jupyter

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1301]
Based on feedback here:
https://towardsdatascience.com/ipython-notebook-support-is-finally-here-for-visual-studio-code-b578abe0361c

We should investigate this and see if there's something we can do about this.

**Comment by TeodoroCriscione** [comment]
Hello! Sorry, I am a newbie ...
My 'settings.json' file in my working directory is actually empty:

`{
    "jupyter.jupyterServerType": "local"
}`

Where I am supposed to find the command line `python.dataScience.runStartupCommands : %config IPCompleter.use_jedi = False`? The same .ipynb file launched through Visual Basic Code is 100 times slower than if it is launched with Jupyter Lab. How can I solve this problem?

**Comment by rchiodo** [comment]
> Where I am supposed to find the command line python.dataScience.runStartupCommands : %config IPCompleter.use_jedi = False?

That's actually the old value when this bug was first opened. We've since moved to a new extension. The new setting should look like so:

```json
    "jupyter.runStartupCommands": ["%config IPCompleter.use_jedi = false"]
```

That setting is a list of 'code' we run on starting a jupyter kernel. That particular command tells Jupyter to stop using jedi for auto completion (which is hanging the jupyter kernel).
