### ISSUE TITLE
Top level decorators still do not work with run selection

### ISSUE THREAD

**Issue by etrippler** [microsoft/vscode-jupyter#13027]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

```
from dataclasses import dataclass, field

@dataclass
class Person:
    name: str = field(default='John')

p = Person()
p2 = Person(name = 'Jane')

print(p)
print(p2)
```

Results in 

```
Person(name='John')
Person(name='Jane')
```

However, running 
```
from dataclasses import dataclass, field
```

and then in another code block: 

```
@dataclass
class Person:
    name: str = field(default='John')

p = Person()
p2 = Person(name = 'Jane')

print(p)
print(p2)
```

Results in 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Untitled-1 in line 5
      7     name: str = field(default='John')
      9 p = Person()
----> 10 p2 = Person(name = 'Jane')
      11 print(p)
      12 print(p2)

TypeError: Person() takes no arguments
```

This issue has been mentioned here: https://github.com/microsoft/vscode-python/issues/16229
And here: https://github.com/microsoft/vscode-python/issues/15058
And was supposedly fixed by: https://github.com/microsoft/vscode-python/pull/17916

But I am obviously still seeing this behavior :(

## Steps to reproduce:

1. See above for a minimal example. 

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.9
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
[No Output]
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```
Multiroot scenario, following user settings may not apply:

languageServer: "Pylance"

linting
• flake8Args: "<placeholder>"
• flake8Enabled: true
• flake8Path: "<placeholder>"

formatting
• provider: "black"
• blackPath: "<placeholder>"

```

</p>
</details>

Extension version: 2023.4.0
VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.27GB free)|
|Process Argv|--crash-reporter-id 6afa82ca-498d-4823-a856-4375fdf3e3f7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30677850
funwalk2cf:30676044

```

</details>

**Comment by amunger** [comment]
thanks for finding the fix, that made it easy to port. Should be fixed in https://github.com/microsoft/vscode-jupyter/pull/13044
