### ISSUE TITLE
clicking on code cell output doesn't select cell

### ISSUE THREAD

**Issue by yuuuxt** [microsoft/vscode-jupyter#13026]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

clicking the celoutput area doesn't select that cell

![temp](https://user-images.githubusercontent.com/3153534/223603702-dbe49dff-2ad2-4a73-a063-6cb25aff5cb8.gif)

which is not intuitive and is not consistent with jupyter notebook

![temp2](https://user-images.githubusercontent.com/3153534/223603722-b89d1be0-2682-4446-a12d-63febe74084d.gif)

I think there should not be a state of `not selecting any cell`; which is meaningless - users always want to interact with cell(s). No matter what happens or what is done, one (or multiple) cell should be selected.

This issue along with #12738 makes operation less fluent - you are not sure if your action will be executed.

### VS Code Version

1.76.0

### Jupyter Extension Version

v2023.2.1000592019

### Running Jupyter locally or remotely?

None

**Comment by amunger** [comment]
@yuuuxt - is this still occurring for you on the latest version? The closest I can get to a repro is the cell can be unfocused, but it is still selected, so not as bad as your gif shows

**Comment by yuuuxt** [comment]
yes it's still happening on 1.77 and v2023.3.1201040234. Besides, I'm not sure what you meant by "unfocused but still selected":
- if my operations are all on the notebook, there should be (at least) one cell selected. When Focusing on notebook (editor) and don't click anything outside, somehow having no cell selected doesn't make sense to me;
- The consequence is operations like pressing "B", "A" not working. some are still functional like arrow up & down, but inserting cells are frequent moves as well. (so this is strange to me- if it's unfocused & selected, what's the logic of some operations working while some not working, and how to memorize it? what's the purpose of such a state?)

**Comment by amunger** [comment]
ok, I wasn't seeing the same UI issues as shown in your gif, but there are a few commands that stop working in that case because they have `!notebookOutputFocused` in the when clause. It looks like the JupyterKeyMap extension is adding those conditions and I'm trying to see if they could just be removed.
Just to confirm tho - if you remove that condition in those specific keybindings, does that enable the commands correctly?

**Comment by yuuuxt** [comment]
yes removing `!notebookOutputFocused ` makes it working. I will check all related shortcuts to make it work for me.

**Comment by amunger** [comment]
verification steps:
1. open the attached notebook (change the file's extension to .ipynb)
[inputsInOuputs.txt](https://github.com/microsoft/vscode-jupyter/files/11518667/inputsInOuputs.txt)
2. click in the output area, outside of the text fields
3. use the raw hotkeys `a` `b` `j` `k` (insert cell above/below, list previous/next) and ensure they trigger the commands
4. click within the text area in the output, those same keys should just write text without running commands
