### ISSUE TITLE
Jupyter kernel run path incorrect

### ISSUE THREAD

**Issue by colinmarcus** [microsoft/vscode-jupyter#13028]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Just start a jupyter notebook in vscode and run the following:

import os
import inspect
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
print(currentdir)

For me this prints:
C:\Users\colin\AppData\Local\Temp\ipykernel_3160

Previously, this would print the directory where the .ipynb script is located. I noticed the new, broken behavior after updating my Jupyter version.

I have tried setting the "Jupyter: Notebook File Root" to "${fileDirname}" but this doesn't work.

Unfortunately, having the working directory set to "AppData\Local\Temp\" breaks all code using relative file locations... Very troublesome.

### VS Code Version

Version: 1.76.0 (user setup) Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb Date: 2023-03-01T10:22:44.506Z Electron: 19.1.11 Chromium: 102.0.5005.196 Node.js: 16.14.2 V8: 10.2.154.26-electron.0 OS: Windows_NT x64 10.0.19045 Sandboxed: Yes

### Jupyter Extension Version

v2023.2.1000592019

### Coding Language and Runtime Version

Python 3.9.16

### Language Extension Version (if applicable)

v2023.4.0

### Anaconda Version (if applicable)

2.3.2

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
THanks for filing this issue & sorry you are running into this issue
, not sure where `temp/ipykernel_3160` is coming from


Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by colinmarcus** [comment]
Ran same code as before, it printed:
C:\Users\colin\AppData\Local\Temp\ipykernel_20832

Here's the log

[JupyterLog.txt](https://github.com/microsoft/vscode-jupyter/files/10925279/JupyterLog.txt)

**Comment by DonJayamanne** [comment]
Closing this issue as this is how IPyKernel behaves
If you try the same code in jupyter notebook or jupyter lab, you will get the same random file name.

This path is not generated nor controlled by vscode, not sure how this worked for you in the past.
<img width="831" alt="Screenshot 2023-03-21 at 17 44 40" src="https://user-images.githubusercontent.com/1948812/226535148-526cb650-b686-44f2-84c0-be8a318ce76d.png">
