### ISSUE TITLE
Auto-save Python Jupyter notebook and restore from temporary autosave

### ISSUE THREAD

**Issue by thistlillo** [microsoft/vscode-jupyter#13038]
Sometimes, long-running or badly-written cells cause Visual Studio Code using this extension to freeze. In my case, when this happens, I cannot ask for "stop running the cell", VSC becomes unresponsive and is not even able to save the notebook before closing. In many occasions, when I forgot to save the notebook before running a cell on huge datasets, I have lost all the last edits.

For example, in the last case, VSC went from being unresponsive:

![image](https://user-images.githubusercontent.com/6717655/224010369-668e4996-656e-4d4a-9bc5-97264ffcecb4.png)
 👍 
to crashing due to an out-of-memory errror:

![image](https://user-images.githubusercontent.com/6717655/224010240-4153aad5-22bb-49d7-9b5e-29c736b066ce.png)

(in this case it was not enough to re-open because I was working remotely and VSC was no longer able to connect: I had to quit VSC and re-launch it).

These crashes are usually caused by programming errors, but sometimes they are caused by something else because the code runs fine as a simple Python script. These kind of errors occur more often when working remotely (via ssh), but local runs are affected as well (even if to a lesser degree). In all the cases, this type of errors occur when working with scikit and pandas (but I always use those two libraries).

I think it would be important to add an automatic saving of the current notebook, possibly in a temporary file, before the user executes a cell.

**Comment by DonJayamanne** [comment]
Sorry for never getting back to you on this issue, somehow this slipped through the cracks.
We have made a lot of improvements and fixes in this space and believe this may have been resolved.
Please ensure you update to the latest version of VS code and the extensions.
Closing as I believe it may have been resolved,
If not please ping here and I'll reopen this or feel free to create a new issue.
