### ISSUE TITLE
Linting within Jupyter ipython Notebooks

### ISSUE THREAD

**Issue by JackKelly** [microsoft/vscode-jupyter#13040]
Thanks so much for enabling Jupyter within VS Code - it's a really cool feature!

I was just wondering if there are still plans to enable Python linting (e.g. using `mypy` and/or `ruff`) within Jupyter Notebook cells?

## Related

* #1231 - mentions "Linting"
* #2075 - asks for autopep8 linting. The answer was "_we don't have plans on adding this functionality at this time. VS Code is planning on adding native notebook support. This kind of functionality will light up then._". My understanding is that VS Code now has native notebook support.

Many thanks,
Jack

**Comment by dokutoshi** [comment]
Any progress on this?

**Comment by MuminKhan** [comment]
Bump?

**Comment by rebornix** [comment]
The notebook support is now stable in VS Code and extensions can adopt this already and add linting support. IIRC Ruff already works.
