### ISSUE TITLE
Interactive UI slows to a halt over time

### ISSUE THREAD

**Issue by kdkavanagh** [microsoft/vscode-jupyter#1304]
Moving out of microsoft/vscode-python#6563 since it seems to be a bit unrelated.

Does the interactive window do any other regular updating of old cells and/or the current set of variables? Despite disabling the variable inspector entirely, I'm still seeing this same issue with a large number of large dataframes.

EDIT: Also see jupyter server spinning at 100%, during execution of simple commands (e.g dataframe.head()) that complete nearly instantly in a raw python terminal and also JupyterLab UI

Just tried connecting to a kernel that was loaded up with big variables (long/wide dataframes) outside of vscode using microsoft/vscode-python#7015 (i.e I have no working cells in the vscode interactive window) - Things are still super slow, like 10min+ for df.head(), and again still super fast in JupyterLab.

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed with new native support for editing notebooks. To opt into that experience see: https://github.com/microsoft/vscode-jupyter/wiki/Introducing-Native-Notebooks.
