### ISSUE TITLE
Undiscovered Python interpreters can no longer be added manually

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-jupyter#13054]
After last month's update to the Python interpreter selection panel, I can no longer enter a path to an interpreter for it to be selected. Since some of my virtual envs fail to be auto-discovered, there's now no way to select them.

This list is missing my `py310` venv at `~/.venv/py310/bin/python`.

![Screenshot 2023-03-10 at 10 57 11](https://user-images.githubusercontent.com/30958850/224402965-2818e810-0351-4d48-98cb-9277a1777c61.png)

Could you add back the "Add interpreter by path" functionality?

**Comment by amunger** [comment]
As a workaround, can you run `Python: Select Interpreter` to add it first, and does it then show up in the kernel picker? (I'm assuming your screenshot is from the kernel picker menu)

**Comment by janosh** [comment]
@amunger Thanks, that worked! It does show up now.

<img width="817" alt="Screenshot 2023-03-10 at 11 28 11" src="https://user-images.githubusercontent.com/30958850/224408992-0079785b-2b4e-4750-9848-e1542b47c49d.png">

**Comment by DonJayamanne** [comment]
Closing this as resolved

**Comment by janosh** [comment]
Using `Python: Select Interpreter` seems more like a workaround to me. I've been using the Jupyter for a long time and wasn't aware of this. So other users won't be either. I think it would be better to add the ability to force-discover interpreters by path right to the selection panel in my screenshots.

**Comment by matangover** [comment]
Please reopen @DonJayamanne @amunger this is not resolved

**Comment by matangover** [comment]
@amunger @DonJayamanne Please reopen. This is not resolved - still cannot manually add interpreter path in the kernel picker.
