### ISSUE TITLE
Jupyter becomes unresponsive on remote:WSL

### ISSUE THREAD

**Issue by nickolasclarke** [microsoft/vscode-jupyter#1305]
Issue Type: <b>Bug</b>

1. Connect to remote WSL host
2. open a notebook and run some code cells. 
3. create a new code cell and attempt to run additional cell.
4. Note that the code cell does not run. The "executing cell" or scrolling top bar does not appear. Changes to the notebook cannot be saved. 

Extension version: 2019.10.44104
VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.19018
Remote OS version: Linux x64 4.19.79-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: WLinux|
|OS|Linux x64 4.19.79-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2194)|
|Memory (System)|6.70GB (5.52GB free)|
|VM|0%|
</details>

**Comment by greazer** [comment]
Thanks for your feedback. This old issue should be addressed with new native support for editing notebooks. To opt into that experience see: https://github.com/microsoft/vscode-jupyter/wiki/Introducing-Native-Notebooks.

If not, please open a new bug. Thanks!
