### ISSUE TITLE
Convert from python file to jupyter notebook

### ISSUE THREAD

**Issue by tddschn** [microsoft/vscode-jupyter#13050]
I found this issue https://github.com/microsoft/vscode-jupyter/issues/4495 with the same question, but the solution posted doesn't work for me.

I didn't find `'Export Current Python File as Jupyter Notebook' or 'Export Current Python File and Output as Jupyter Notebook'`  
in the context menu on extension `v2023.2.1200692131`.

## Describe the feature you'd like. 

In Python, you can mark a part of the file to run in Jupyter with the marker `##%`, so I thought there would be a feature to convert from python file to jupyter notebook, but I don't think it exists so I opened this issue.

What I want is bascially the inverse of Jupyter extensions 'Export Jupyter to Python',  
putting lines between markers in python cells.  I don't need comments in the python file to be converted to markdown cells in jupyter.

**Comment by amunger** [comment]
the default code cell marker is `# %%` - try putting those in your file and then look for the command. They only show up for files with code cells

![image](https://user-images.githubusercontent.com/2019016/224224135-0d01a841-4219-4c96-9bc5-02b4c01d06f3.png)

**Comment by tddschn** [comment]
Thank you! I didn't include any markers so didn't see the options. It works now. :)
