### ISSUE TITLE
VSCode jupyter's interpreter selection doesn't work for code formatter

### ISSUE THREAD

**Issue by itdevwu** [microsoft/vscode-jupyter#13053]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

If you:
- use conda or some other virtual envs;
- use 3rd-party code formatting tools like `black`, etc.

AND:

- the formatting tool is installed in some other env but the `base` environment.

then VSCode notebook is not capable to call the formatter, even if you have already select the env with the formatter you want.

Currently, a solution is to open another `.py` file in the same VSCode window, and select Python interpreter you desire in it. After that, VSCode notebook will be able to find everything inside that env.

**Possible cause**: VSCode and VSCode jupyter are out of sync when selecting interpreter inside VSCode jupyter. VSCode and its plugins don't know which perticular env user has chosen in the VSCode jupyter interface.

### VS Code Version

1.75.1

### Jupyter Extension Version

v2023.1.2010391206

### Running Jupyter locally or remotely?

None

**Comment by amunger** [comment]
it sounds like we're using the active interpreter to format, rather than the notebook's selected kernel

**Comment by fjolne** [comment]
As another solution, you can provide the path to interpreter in `.vscode/settings.json` (in case you have nested multi-root workspace, it should be in parent folder):
```json
{
    "python.defaultInterpreterPath": "${workspaceFolder}/.venv",
}
```

**Comment by DonJayamanne** [comment]
For this to work, all of the extensions (linters/formatters) will need to use the selected interpreter from a ntoebook and this would require 
* an API from Jupyter extension and 
* other extensions would have to be updated to adopt this change.

The best solution is to go with https://github.com/microsoft/vscode-jupyter/issues/13053#issuecomment-1604620626

Given that not many have come across this, I'm closing this as out of scope.
