### ISSUE TITLE
Exception strings get evaluated as HTML, brackets do not get escaped

### ISSUE THREAD

**Issue by kwikwag** [microsoft/vscode-jupyter#13056]
## Environment data
-   VS Code version: 1.76.0 (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2023.2.1200692131
-   Python Extension version (available under the Extensions sidebar): v2023.4.1
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.22621
-   Python and/or Anaconda version: 3.9.15
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Expected behaviour

Exception message string should be displayed as given.

## Actual behaviour

The exception string gets interpreted as HTML, effectively hiding anything that lies inside angle brackets.

## Steps to reproduce:

Run the following command in cell-mode:

`raise Exception('<an error>')`

![exception-brackets](https://user-images.githubusercontent.com/392199/224470639-c773d1ad-bc2f-45a1-a64d-94a6b70b946e.gif)

**Comment by DonJayamanne** [comment]
Looks like a regression @rebornix @amunger /cc
