### ISSUE TITLE
Not respecting the selected virtualenv kernel

### ISSUE THREAD

**Issue by zakandrewking** [microsoft/vscode-jupyter#13055]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

If I select try to run a kernel from a virtualenv, VSCode instead falls back to the global installation (where jupyter-notebook is not installed).

I can recreate this from scratch using a new virtualenv with just `pip install jupyter notebook`.

In the virtualenv, I can run `jupyter-notebook`, and VSCode will happily connect to the kernel if I choose "Select another Kernel > Existing Jupyter Server".

### VS Code Version

 Version: 1.76.1 Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b Date: 2023-03-08T16:48:08.231Z (2 days ago) Electron: 19.1.11 Chromium: 102.0.5005.196 Node.js: 16.14.2 V8: 10.2.154.26-electron.0 OS: Darwin arm64 22.3.0 Sandboxed: Yes

### Jupyter Extension Version

v2023.2.1200692131

### Jupyter logs

```shell
https://gist.github.com/zakandrewking/9257c732336c48781745ba0078e683aa
```

### Coding Language and Runtime Version

Python 3.11.2

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
You may need to run the command `Jupyter: Select Interpreter to start Jupyter Server` if I understand the issue correctly, although I'm surprised that we don't use the selected kernel if jupyter server is available there.

The interpreter we use for starting jupyter server isn't necessarily the same as the interpreter used to run the kernel.

**Comment by zakandrewking** [comment]
That worked! thank you (might be nice to have this in the docs, if other people get the same behavior)
