### ISSUE TITLE
Output of cells is not being displayed

### ISSUE THREAD

**Issue by thistlillo** [microsoft/vscode-jupyter#13063]
I am using
```
Version: 1.76.1 (user setup)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:00.131Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```
with extensions

- Jupyter (Microsoft): `v2023.2.1200692131`
- Remote-SSH (Microsoft): `v0.98.0`

All "remote" notebooks, i.e. a Jupyter notebooks running on a server to which I am connected with ssh, DO NOT display the output of a cell that has been run.

I do not know where to look at for error messages: any help?

I notice an extreme lag when scrolling. Output is rendered as white space.

Just a screenshot of `print(hello)` printing nothing:
![image](https://user-images.githubusercontent.com/6717655/224780888-63c18ded-75a1-4669-a1a2-fa4425972281.png)

**Comment by amunger** [comment]
can you check which renderer it's trying to use - click the `...` menu next to where the output should be and select change presentation. Is the built-in renderer selected?

If that doesn't help, can you also check the actual json content of that notebook to see if there is an ouptut? Save the file, right click the editor tab and select 'reopen editor with...' and pick the text editor. It should have something like

```
"outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "hello\n"
     ]
    }
   ],
   "source": [
    "print('hello')"
   ]
```

**Comment by thistlillo** [comment]
Hello,
 if I click the three dots, nothing happens. Something breaks the notebook.

Looking at the json, here it is what I find:
```
{
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "hello\n"
     ]
    }
   ],
   "source": [
    "print(\"hello\")"
   ]
  }
```


May be this could be useful... The json ends with:
```
"metadata": {
  "kernelspec": {
   "display_name": "ai",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

As a remark I forgot to mention before... when this happens, the fans of my notebooks start spinning quite fast.

**Comment by amunger** [comment]
can you check in the developer tools for any errors? `Developer: Toggle Developer Tools`

**Comment by thistlillo** [comment]
Yes, there is an error, whose text, by the way, I cannot copy and past here so I need to write it:
```
[Extension host] (node:6496) DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead
```
Even if it seems a warning, it appears as an error (`ERR`) in the console.

However, my `ipynb` has been unusable: if I copy and past the code in a new notebook, nothing changes. It does not even show the output of MarkDown  cells any more. I am going to reinstall everything.

This notebook manages huge datasets: I think the tool is not suited for such memory-intensive operations. I always have problem with plenty of data and jupyter notebooks using pandas/scikit...

**Comment by thistlillo** [comment]
REINSTALLING VSC fixed the issues.

However, I have not exactly understood what happened here. I uninstalled VSC, downloaded the latest version and installed it.

The "fresh" VSC had "preinstalled" all of the extensions of the previous installation. This is strange.

**Comment by thistlillo** [comment]
As you may see in the code above, the outermost `for` contains a print(file).
After running the cell, if I clear its output (and the fans spin etc), the output of that print is not cleared.

After running once and clearing the output, if I run the same cell again NO OUTPUT is displayed at all (only the print(file) is shown because it has not been cleared).

**Comment by thistlillo** [comment]
SOLVED.

Turning `display(dataframe)` into `print(dataframe)` solved the issue.
