### ISSUE TITLE
vscode jupyter notebook loads dataset or model very slowly while it should be fast.

### ISSUE THREAD

**Issue by Practicing7** [microsoft/vscode-jupyter#13062]
## Environment data

-   VS Code version: 1.76.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.2.1200692131
-   Python Extension version (available under the Extensions sidebar): v2023.4.1
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 22.04
-   Python and/or Anaconda version: Anaconda version: conda 23.1.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | native Mac OS remote ubuntu 

## Expected behaviour

I expect to use the load_dataset or load model function as I do in terminal or in the web version of jupyter notebook, it should be fast.

## Actual behaviour

I wait almost 10 minutes, the cell is stil running on loading dataset, however this just should be done in five seconds.

## Steps to reproduce:

environment preparation: pip install datasets 
1. from datasets import load_dataset 
2. dataset = load_dataset("yelp_review_full")

it will just continuously running without giving any result or warning.
![image](https://user-images.githubusercontent.com/95281221/224734787-0bcb7e30-d1f0-4710-9145-d0252c240a2e.png)
but in the web
![image](https://user-images.githubusercontent.com/95281221/224735053-c4460399-5d6a-4382-9c4f-1929929814bb.png)
it loads smoothly without any problem.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by amunger** [comment]
looks like it worked for me in 1.5 minutes. Can you provide the logs from `Jupyter: show output`?
![image](https://user-images.githubusercontent.com/2019016/224746603-5a2e461b-62fb-4048-9c77-9977c4f67fdf.png)

**Comment by Practicing7** [comment]
where can I get the logs? thank you. And it occurs to me that I am in China, and this huggingface datasets is approached with proxy, do you think would that have some influence? Or how can I use proxy in jupyter in vscode.

**Comment by amunger** [comment]
if you have a jupyter server that access the data sets (that you are using in the web), you could try re-using that jupyter server within vs code. Just click the kernel picker -> 'select another kernel' -> 'Existing Jupyter Server', and enter the location of the running server. It would be in the output of the command used to start it, e.g. `jupyter notebook`

**Comment by Practicing7** [comment]
Thank you! I don't know what happened, but it all works out in vscode
