### ISSUE TITLE
Rendering image in cell with PIL.Image leads to irrecoverable "Reconnecting to the kernel..." 

### ISSUE THREAD

**Issue by kechan** [microsoft/vscode-jupyter#13073]
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I created a virtualenv and pip install latest ipykernel, jupyter, and Pillow (the minimum necessary to test displaying a jpeg using PIL.Image. The VSCode "select interpreter" and "select kernel", I made sure I picked the one from this virtualenv. 
But as soon as I ran it, it provoked "Reconnecting to the kernel...". I have attached the jupyter log, it seems to suffer some exceptions. From the same venv, I am able to run this without problem on good old plain jupyter notebook from browser. This leads me to think this is some sort of integration issue between the py kernel and vscode/jupyter.

Here's the reproducing sample code in the cell:

`
import sys
print(sys.executable)         # sanity check python location

import PIL.Image
print(PIL.__version__, PIL.__file__)   # sanity check PIL package location

from pathlib import Path
img_name = Path.home()/'tmp'/'testing.jpg'

PIL.Image.open(img_name)
`

I used a couple of print to sanity check python and kernel location. They seemed to be ok. 

Additional platform info:

* Apple M2 Max (96gb)
* MacOS Ventura 13.2.1 (22D68)

Note: I have tried to simplify all reproducing artifacts. But I saw the same happened to conda with python 3.10.* and most packages installed from conda-forge. In certain version, the image will get rendered in vscode/jupyter but will provoke the Reconnecting..., at other times, the image won't even render.

### VS Code Version

Visual Studio Code (1.76.1, undefined, desktop)

### Jupyter Extension Version

Jupyter Extension Version: 2023.2.1200692131.

### Jupyter logs

```shell
the log is too long for GitHub submission (will add more later)

debug 11:17:52.734: VSCodeNotebookController::handleExecution, Class name = Kv (started execution)
debug 11:17:52.735: Execute Cell 1 /Users/kechan/Downloads/test_PIL.ipynb
debug 11:17:52.735: start the kernel, options.disableUI=false for /Users/kechan/Downloads/test_PIL.ipynb
debug 11:17:52.736: Start Jupyter Session in kernel.ts with disableUI = false
debug 11:17:52.737: Start cell 1 execution @ 1678807072737
[E 11:17:52.833 NotebookApp] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/Users/kechan/Library/Python/3.9/lib/python/site-packages/tornado/iostream.py", line 702, in _handle_events
        self._handle_write()
      File "/Users/kechan/Library/Python/3.9/lib/python/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/Users/kechan/Library/Python/3.9/lib/python/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/kechan/Library/Python/3.9/lib/python/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/Users/kechan/Library/Python/3.9/lib/python/site-packages/tornado/iostream.py", line 702, in _handle_events
    self._handle_write()
  File "/Users/kechan/Library/Python/3.9/lib/python/site-packages/tornado/iostream.py", line 976, in _handle_write
    self._write_buffer.advance(num_bytes)
  File "/Users/kechan/Library/Python/3.9/lib/python/site-packages/tornado/iostream.py", line 182, in advance
    assert 0 < size <= self._size
AssertionError
[I 11:17:52.833 NotebookApp] Starting buffering for 26123d52-fbd5-4caa-b7ff-22654ac45a11:555cd649-ba88-48a7-8fee-56c62d6dd8f6
[I 11:17:52.839 NotebookApp] Restoring connection for 26123d52-fbd5-4caa-b7ff-22654ac45a11:555cd649-ba88-48a7-8fee-56c62d6dd8f6
[I 11:17:53.342 NotebookApp] Replaying 1 buffered messages
```

### Coding Language and Runtime Version

python 3.9.6

### Language Extension Version (if applicable)

python extension v2023.4.1 (from Microsoft)

### Running Jupyter locally or remotely?

Locally

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and sorry you are running into this.
Please could you try running the following in a terminal
```
 /usr/bin/python3 -m pip install 'jupyter_client<8' 'pyzmq<25' --force-reinstall
```

Once done, reload VS Code and test again.

> and now I am wondering why it is referencing

This is another interrpeter that the Jupyter extension is using to startup the Jupyter server.
You can change this Python environment by using the command `Jupyter: Select Interpreter to Start Jupyter Server`

**Comment by kechan** [comment]
@DonJayamanne Thanks for your prompt response.  

Should i do the “/usr/bin/python3 … “ command within the venv (i.e. activating and doing it under new shell).
Else, if this is an operation that can affect my machine globally, please kindly point out, and I will try to plan for an undo in case i need to revert.

**Comment by DonJayamanne** [comment]
please run without activating the terminal, and yes it will impact the global python enviornment
please remember to use the `--user` flag,
```
 /usr/bin/python3 -m pip install 'jupyter_client<8' 'pyzmq<25' --user --force-reinstall
```

**Comment by kechan** [comment]
@DonJayamanne Ok, I came back to doing this (after some distraction with GPT4...) 

I freeze > requirements just in case I need to go back, and I performed the exact command as you said. 
And my test case worked (both PIL and plt.imshow)! So I guess why it didn't work before was I had been doing the downgrading experiment within venv or conda env. 

The version after downgrade are:

jupyter_client           7.4.9
pyzmq                    24.0.1

I think I will start going back to conda env to continue setting up TF and PyTorch, and hope for no new issue. If downgrading is a workaround, is there a real bug to be fix to allow VSCode to use newer jupyter_client and pyzmq. Should I just close this bug for now?

**Comment by DonJayamanne** [comment]
@kechan 
>  is there a real bug to be fix to allow VSCode to use newer jupyter_client and 

Yes, in fact most of this should just go away with the latest pre-release. 
As of today, the latest pre-release version ships with a fix

All you need to do is, install the pre-release as per the below instructions, reload vscode and the open a notebook and provide the output from the `Jupyter` output panel. Just as you have provided in the begining of this issue. 
I am certain that will fix this issue.
Today the logs contain the following text towards the start, ` Exception while attempting zmq : No native build was found for platform=darwin arch=arm64`
With the new pre-release, you should not see that message anymore.

If after this, you still run into issues please do replicate the issue and provide the logs, 
so we can try to get a fix in for the next release (which will be in 2-3 weeks time).

**Instructions for installing the pre-release**
* Please install latest VS Code Insiders
* Open the extensions page, search for Jupyter and click the button `Switch to Pre-Release Version`
* Similarly please install the latest `Pre-Release` version of the Python extension

<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">

@kechan I am going to close this as you have confirmed that you have downgraded the packages
& I am confident these issues will  go away with the latest pre-release version

If you still run into issues, please feel free to re-open this issue,. or ping me and i will open it, if all else fails, please feel free to create a new issue and i will look into this.

**Comment by kechan** [comment]
@DonJayamanne Thanks so much for your help. I will try this in the next few days and report back, and if there's any issues (i.e. upgrading my global packages that were downgraded for this workaround).
