### ISSUE TITLE
Contextual help

### ISSUE THREAD

**Issue by amirhosseindavoody** [microsoft/vscode-jupyter#1307]
One of the great benefits of python notebook is the exploratory nature of it. I personally find the contextual help window in `jupyter lab` a very helpful feature that makes the exploratory data analysis very easy by providing a fluid guide for the many API's that one might have to try. I don't know how big of an ask this is, but it would be much appreciated to provide this in VScode notebook editor.

Below is a screen shot of what I am referring to in jupyter lab. The functionality is that by clicking on each function, the docstring for that function is show in the contextual help window.

![image](https://user-images.githubusercontent.com/8355965/66498073-541f0080-ea72-11e9-91ce-7d3ae9a2b9e5.png)

**Comment by cipri-tom** [comment]
Indeed, this is what keeps me productive in Jupyter. I don't have to memorize all the stuff.

When it gets implemented, please also enable a keyboard shortcut for it ! In Jupyter there are 3 shortcuts that display progressively more information:

 1. Shift + Tab
   - parameter hints
   - this is what VS Code currently displays when the caret is within `(...)`. 
![Screenshot 2020-12-02 at 13 08 32](https://user-images.githubusercontent.com/2991890/100870789-7e662580-349f-11eb-8f75-1d5b76d7e568.png)

   - In both editors, it is often too small to understand anything

 2. Shift + Tab + Tab [ + Tab] (2 or 3 times)
   - expanded parameter hints
   - It shows the hints, and the documentation, in a slightly taller pop-up. 
   - VS Code has this on hover, but size is kind of small
![Screenshot 2020-12-02 at 13 05 54](https://user-images.githubusercontent.com/2991890/100870567-20d1d900-349f-11eb-85c2-ac76e4b35857.png)
   - if Tab is pressed 3 times, the tooltip lingers for a few seconds while you type
   - video from their docs: https://youtu.be/TgqMK1SG7XI 

 3. Shift + 4 * Tab
   - contextual help
   - opens a panel at the bottom with nice to read documentation (formatted!)
   - in JupyterLab (not normal notebooks), this panel updates as you move around

---

An extension that kind of does this is Kite Copilot : https://www.kite.com/copilot/ … but it is an external app and I don't want to install the whole of Kite for this.

Another external app which provides similar functionality is Dash -- there is an extension which interfaces with VS Code, but you need to have Dash window next to VS Code window (to recreate the experience). I haven't tested if it woks in notebooks.

**Comment by loftusa** [comment]
+1 on this. I haven't been able to get shift+tab when I'm working with vscode jupyter to work the same way as it does in browser, and have tried a few things at this point. This feature is pretty much the only reason I still use the browser version.

**Comment by luiul** [comment]
+1

**Comment by kevingoh** [comment]
+1

**Comment by nyschoi** [comment]
++1

**Comment by GitHunter0** [comment]
Hey @rchiodo , I think this feature is a major productivity booster and time saver. 

**RStudio**, similarly has a separate window for that, "Help" pane. Just select a function and press `F1` and it will open the documentation. 

Advantages:
(1) You can define the size of "Help" pane. (Kite window size is too small and makes really hard to inspect some documents)
(2) Unlike Kite hover feature, it stays open while you work on your code, so that you can reference it in real time
(3) Unlike `help(function)` command, it already shows the documentation from the beginning, so there is no need to scroll up to the beginning of the output cell every time to see the documentation, which is really painful. 
(4) It keeps the history of help searches to go back at it

Thank you

**Comment by ausiddiqui** [comment]
I use VSCode for editing existing Python/SQL scripts but never the Jupyter notebook feature when starting new projects because of this feature. The boost to productivity and learning an API is huge especially with the context panel and the shift tab shortcut. Same issues as other reported with hover and how quickly it disappears, and having to switch between keyboard and mouse is not ideal.

This would be an amazing feature to add as another panel like the data viewer panel but one that you can position permanently on a part of the screen. Thanks for considering this!

**Comment by Cyberjoe** [comment]
+1 - pls add this functionality to VSCode. It would be a significant breakthrough. You also may want to look at Spyder. I love its always-on help.

**Comment by Cyberjoe** [comment]
I just discovered this new extension which addresses the issue very well: [https://marketplace.visualstudio.com/items?itemName=bierner.docs-view]

**Comment by allefeld** [comment]
@Cyberjoe, that a great find!

Unfortunately, it doesn't work within notebooks, but neither does the standard popup (at least not properly).

**Comment by GitHunter0** [comment]
> I just discovered this new extension which addresses the issue very well: [https://marketplace.visualstudio.com/items?itemName=bierner.docs-view]

Fantastic extension, it would be great to see it incorporated in VScode as the default. Thanks a lot for the suggestion

**Comment by GitHunter0** [comment]
I discovered this trick too using "Open Definition to the Side" command: https://www.youtube.com/watch?v=3p4pXhpPVf4

**Comment by claudiaregio** [comment]
+1 
![image](https://user-images.githubusercontent.com/19276747/127586759-0ae2e0f5-1410-4812-a7d2-aedef6438a99.png)

**Comment by GitHunter0** [comment]
When this feature comes up, I really hope it works for `.py` files in Interactive Window too. 
For that, do we have to open the same issue in `vscode-python`?

**Comment by rchiodo** [comment]
@GitHunter0 
> For that, do we have to open the same issue in vscode-python?

No this window would be created in the jupyter extension for the interactive window. The interactive window is talking to a notebook kernel in the background, and that's what would drive the contextual help. At least one way to do it. @mjbvz's [doc-view extension](https://marketplace.visualstudio.com/items?itemName=bierner.docs-view) works without a kernel though. It just uses the hover provider.

**Comment by LunarLanding** [comment]
This is half of my jupyter workflow; and to be clear, this means wiring up vscode to the interpreter state, instead of getting it from static analysis. I can't switch to vscode-jupyter without this.

**Comment by bonassifabio** [comment]
+1
This is definitely a huge VSCode shortcoming.

**Comment by loftusa** [comment]
I'd like to add yet another +1 on this, I've had the exact same experience as @dennischenfeng. It's literally the only thing that causes me to still use Jupyter Lab over VSCode. I'd immediately switch to VSCode exclusively if this feature existed.

**Comment by bonassifabio** [comment]
Unfortunately it's not just a matter of how information is displayed, but also how detailed is the doc shown to the user
![Schermata 2021-11-11 alle 16 59 04](https://user-images.githubusercontent.com/608693/141329363-47ef1131-9d6f-488f-a86d-a4868308acc4.png)
<img width="1277" alt="Schermata 2021-11-11 alle 16 59 53" src="https://user-images.githubusercontent.com/608693/141329367-a5e8d032-efad-4e38-8458-494c5a70b318.png">

**Comment by loftusa** [comment]
@rchiodo @greazer I honestly think this is the most important issue in VSCode right now.

**Comment by McClunatic** [comment]
I'm seeing requests for this from colleagues otherwise interested in moving to VS Code! +1 from me!

**Comment by thetruejacob** [comment]
Is this still not implemented yet? It would provide such a huge boost to productivity.

**Comment by Cyberjoe** [comment]
The newly introduced side panel provides an opportunity to display contextual help. 

1. Install the Docs View extension
2. [View] - [Appearance] - [Side Panel]
3. [View] - [Open View...] - [Documentation - Panel]
4. Drag and drop the Documentation tab from the panel to the side panel
5. Type a python command and the documentation shows up in the side panel.
6. Unfortunately, the documentation disappears as soon as you start typing more code. You can get around this issue by 'pinning' (see screenshot). 

There's still significant potential for improvement. VSCode Developers - please have a look at Spyder in terms of process/layout/formatting.

![Screenshot-VSCode](https://user-images.githubusercontent.com/17931971/152648364-658a495b-4798-40b9-8d4d-48980daa5e70.jpg)

**Comment by GitHunter0** [comment]
@Cyberjoe , the problem is that Docs View extension, like VScode, in many cases also does not find and display the complete documentation like JupyterLab does. Nonetheless, that was a very good tip.

**Comment by dennischenfeng** [comment]
I think some parts of this issue have been solved (which I'm happy about!), while others remain unsolved.

Examples that are resolved: 
Some np, pd, and path lib functions, that I linked to in my original post on this thread (2021/10/14). VS Code now properly shows comparable contextual help to JupyterLab
![image](https://user-images.githubusercontent.com/10649357/157310183-4fe1a1af-08bf-4078-a48b-78f54b8e0cfb.png)
![image](https://user-images.githubusercontent.com/10649357/157310516-7d027d48-90c0-4276-a4ba-e567d75e6ab9.png)
![image](https://user-images.githubusercontent.com/10649357/157310895-7f89db59-71c9-4001-bc5a-5ce664384425.png)


Examples not yet resolved:
I only tested some torch functions (not many other packages), and seems like for some reason their contextual help still hasn't been improved, whereas JupyterLab's contextual help is still better. 
![image](https://user-images.githubusercontent.com/10649357/157312606-33b44479-2404-46c1-8b06-45dee3df979c.png)
![image](https://user-images.githubusercontent.com/10649357/157312979-ed78baaa-a6a3-4f88-87e2-49a03fe7e9e4.png)


Idk why some packages show discrepancy between VS Code vs JupyterLab, whereas others don't. Nonetheless, I'm still glad that it's actually being worked on and there has been some improvement so far.

**Comment by GitHunter0** [comment]
@dennischenfeng , very glad to know it is improving. As others have claimed and I agree, this is the most important issue of VScode right now.

**Comment by thorwhalen** [comment]
+1

**Comment by pcava** [comment]
+1

**Comment by rchiodo** [comment]
I have some good news. We were able to create a power toys extension that partially implements this feature. I say partial because it's not the exact same behavior as jupyter where you hit F1 and it gives you more and more detail.

You can try it out [here](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-powertoys) with either the insiders version of VS code or wait for the next version of VS code stable to ship.

Contextual help window looks like so:
![contextualHelp](https://user-images.githubusercontent.com/19672699/166294338-1af929f8-c86d-4ac2-8595-26248fab1c7b.gif)

**Comment by rchiodo** [comment]
It should be noted it's a little rough. It's from a hackathon project I did last year to try and address this that we never put in the real product. So it might not work, and the UI looks a bit stale. But hopefully it gives the information asked for.

There's a setting to control the detail level of the output:

![image](https://user-images.githubusercontent.com/19672699/166294948-50c144aa-34dc-40a9-856b-324792120f6c.png)

**Comment by GitHunter0** [comment]
@rchiodo indeed a great news! Will this work in the Interactive Window too? (I only use Jupyter Notebooks if I really have to, the Interactive Window is a better and cleaner product in my opinion)

**Comment by rchiodo** [comment]
It kinda works in the interactive window. At least in cells already run. Doesn't work in the input box because VS code doesn't treat that the same.

**Comment by rchiodo** [comment]
Oh and you have to expand the cells after they run to get the help.
![image](https://user-images.githubusercontent.com/19672699/166309193-71b3a4b8-b00f-406d-b1ed-83b6ec10e19e.png)

In that picture I've run a cell where the last line is 'pd.array'. As I move the cursor around in that line, the contextual help changes.

**Comment by amirhosseindavoody** [comment]
> 

This is great! Thanks for working on this.

**Comment by loftusa** [comment]
> I have some good news. We were able to create a power toys extension that partially implements this feature. I say partial because it's not the exact same behavior as jupyter where you hit F1 and it gives you more and more detail.
> 
> You can try it out [here](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-powertoys) with either the insiders version of VS code or wait for the next version of VS code stable to ship.
> 
> Contextual help window looks like so: ![contextualHelp](https://user-images.githubusercontent.com/19672699/166294338-1af929f8-c86d-4ac2-8595-26248fab1c7b.gif)

This is such great news!! So happy to hear that this is being worked on, it remains probably the most important issue in vscode for me!

**Comment by Fred-Wu** [comment]
> It should be noted it's a little rough. It's from a hackathon project I did last year to try and address this that we never put in the real product. So it might not work, and the UI looks a bit stale. But hopefully it gives the information asked for.
> 
> There's a setting to control the detail level of the output:
> 
> ![image](https://user-images.githubusercontent.com/19672699/166294948-50c144aa-34dc-40a9-856b-324792120f6c.png)

This is great. Thanks for implementing this. It is very much needed. 

Just wondering, whether this could be brought to python script as well?

**Comment by Fred-Wu** [comment]
> @Fred-Wu this particular window is using the jupyter kernel's requestInspect message. That might be possible if the user was using the interactive window with a python file but otherwise there's no backing kernel.
> 
> However the [docs-view](https://marketplace.visualstudio.com/items?itemName=bierner.docs-view) extension mentioned elsewhere in this thread might be usable for you. It provides the pylance hover documentation in a separate window.

Thanks for the information.  I have tried docs-view extension. 

Just wondering why pylance hover doc behaves differently to jupyter kernel doc, in which pylance provides minimal and incomplete information compared to jupyter doc. 

For example, with your extension, or run with `?` I can see docstring for a bounded method
```
Code under cursor: twitter_samples.strings

Signature: twitter_samples.strings(fileids=None)
Docstring:
Returns only the text content of Tweets in the file(s)
:return: the given file(s) as a list of Tweets.
:rtype: list(str)
File:
Type: method
```

But in a normal script, it just shows 
```
strings: Any
```

Also when I point to the `JUPYTER: CONTEXTUAL HELP` window, and select `Cut`/`Copy`/`Paste`, it actually performs these functions in the notebook for the section of codes the cursor points to.  Is this an intended function or a bug here?

**Comment by rchiodo** [comment]
Pylance doesn't know the actual type of something because things can be unions or have no type specified. Only actually running something can the type always be figured out. That's why Jupyter shows more information.

For your second question, VS code doesn't seem to support copying from our panel. Not sure why. You could log a bug here:
https://github.com/microsoft/vscode-jupyter-powertoys/issues

**Comment by DonJayamanne** [comment]
I'm closing this issue as we have an extension that provides this functionality in the following extension
If the provided functionality doesn't work as expected please file an issue on the corresponding repo
Here is the link to the exctension https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-powertoys
& here's the link to the corresponding repo https://github.com/microsoft/vscode-jupyter-powertoys
