### ISSUE TITLE
Immediate window debugger off by a line

### ISSUE THREAD

**Issue by jabbera** [microsoft/vscode-jupyter#13074]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Opened Immediate Window.
Created demo.py with the below code and you can see the debugger is off by what appears to be a line. If I remove the breakpoint on the whitespace line it won't break at all:

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/301208/225076323-ec4fcb01-187b-48a3-be3a-4a0cbaa2f870.png">

```
import matplotlib.pyplot as plt
fig, ax = plt.subplots()

fruits = ['apple', 'blueberry', 'cherry', 'orange']
counts = [40, 100, 30, 55]
bar_labels = ['red', 'blue', '_red', 'orange']
bar_colors = ['tab:red', 'tab:blue', 'tab:red', 'tab:orange']

ax.bar(fruits, counts, label=bar_labels, color=bar_colors)

ax.set_ylabel('fruit supply')
ax.set_title('Fruit supply by kind and color')
ax.legend(title='Fruit color')

plt.show()

```

### VS Code Version

1.76.1

### Jupyter Extension Version

v2023.2.1200692131

### Coding Language and Runtime Version

python 3.10.9

### Language Extension Version (if applicable)

v2023.4.1

### Running Jupyter locally or remotely?

Local

**Comment by roblourens** [comment]
Sorry, what did you do to start debugging that .py file? I think that we assume it has a `# %%` comment

**Comment by jabbera** [comment]
I'm using shift enter with this setting:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/301208/228920384-1c080343-e5cd-439f-89cb-b488e53794af.png">

**Comment by roblourens** [comment]
Thanks, as a temp workaround you might try adding a cell comment to the top of the file

**Comment by jabbera** [comment]
> Thanks, as a temp workaround you might try adding a cell comment to the top of the file

Thanks! That works.

**Comment by DonJayamanne** [comment]
@jabbera Are you still able to repro this issue with the latest versions of VS code, Jupyter, Python and Python debugger extenssions?
