### ISSUE TITLE
Provide a better error message when kernel crashes while running a cell

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13087]
Currently we end up with the following error message in the cell `Canceled future for execute_request message before replies were done`

Originally filed here https://github.com/microsoft/vscode-jupyter/issues/13081

**Comment by ODAncona** [comment]
I've got the same issue trying to finetune an object detection model using the framework mmdetection.


To reproduce:

 2097  conda create --name openmmlab python=3.8 -y
 2098  conda activate openmmlab
 2099  pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
 2100  pip install -U openmim
 2101  pip install pexpect
 2102  pip install -U openmim
 2103  mim install mmcv-full
 2104  pip install mmdet
 2105  pip install future tensorboard

```python
from mmcv import Config
cfg = Config.fromfile('configs/faster_rcnn/faster_rcnn_r50_caffe_fpn_mstrain_1x_coco.py')

from mmdet.apis import set_random_seed

classes = ['disk']
# Modify dataset type and path
cfg.dataset_type = 'CocoDataset'
#cfg.data_root = 'data/patient_50'

cfg.data.train.type = 'CocoDataset'
cfg.data.train.img_prefix = 'data/disk_detector/train'
cfg.data.train.ann_file = 'data/disk_detector/train/train.json'
cfg.data.train.classes = classes

cfg.data.val.type = 'CocoDataset'
cfg.data.val.img_prefix = 'data/disk_detector/val'
cfg.data.val.ann_file = 'data/disk_detector/val/val.json'
cfg.data.val.classes = classes

cfg.data.test.type = 'CocoDataset'
cfg.data.test.img_prefix = 'data/disk_detector'
cfg.data.test.ann_file = 'data/disk_detector/test.json'
cfg.data.test.classes = classes


# modify num classes of the model in box head
cfg.model.roi_head.bbox_head.num_classes = 1
# If we need to finetune a model based on a pre-trained detector, we need to
# use load_from to set the path of checkpoints.
cfg.load_from = 'checkpoints/faster_rcnn_r50_caffe_fpn_mstrain_3x_coco_20210526_095054-1f77628b.pth'

# Set up working dir to save files and logs.
cfg.work_dir = './tutorial_exps'

# The original learning rate (LR) is set for 8-GPU training.
# We divide it by 8 since we only use one GPU.
cfg.optimizer.lr = 0.02 / 8
cfg.lr_config.warmup = None
cfg.log_config.interval = 10

# Change the evaluation metric since we use customized dataset.
#cfg.evaluation.metric = 'mAP'
#cfg.evaluation.metric = 'IoU'
# We can set the evaluation interval to reduce the evaluation times
cfg.evaluation.interval = 12
# We can set the checkpoint saving interval to reduce the storage cost
cfg.checkpoint_config.interval = 12

# Set seed thus the results are more reproducible
cfg.seed = 0
set_random_seed(0, deterministic=False)
cfg.device = 'cuda'
cfg.gpu_ids = range(1)

# We can also use tensorboard to log the training process
cfg.log_config.hooks = [
    dict(type='TextLoggerHook'),
    dict(type='TensorboardLoggerHook')]


# We can initialize the logger for training and have a look
# at the final config used for training
#print(f'Config:\n{cfg.pretty_text}')
print(cfg.evaluation)

from mmdet.datasets import build_dataset
from mmdet.models import build_detector
from mmdet.apis import train_detector
import mmcv
import os.path as osp

# Build dataset
datasets = [build_dataset(cfg.data.train)]

# Build the detector
model = build_detector(cfg.model)
# Add an attribute for visualization convenience
model.CLASSES = datasets[0].CLASSES

# Create work_dir
mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
train_detector(model, datasets, cfg, distributed=False, validate=True)
```

**Comment by DonJayamanne** [comment]
@ODAncona

looks like your kernel is crashing due to the code or dependencies installed
Please could you double check that, try to run the same notebook with Jupyter notebook and/or Jupyter lab in the exact  same environment to verify the crash

**Comment by NickCrews** [comment]
I'm experiencing this. I'd like to solve the underlying issue of why my kernel is crashing. Is there a way to debug the root cause of the kernel crash in the meantime until this issue is fixed? The logging isn't very thorough.

**Comment by DonJayamanne** [comment]
> rnel is crashing. Is there a way to debug the root cause of the kernel crash in the meantime until this issue is fixe

unfortunately most of the time there’s no additional information
I would try to strip the code down, try a cell at a time
Update/downgrade dependencies 
Kernel crashing, means the python process has crashed, and it’s almost impossible (sometimes) for vscode to figure out why it crashed
As mentioned it could be a number of things, some code in the notebook or package, etc
Another thing is to try the same code outside vscode in Jupyter lab/notebook on the same environment

**Comment by NickCrews** [comment]
Thanks for the info.

If I export the notebook to a .py file and run that through the interpreter, it does not crash.
If I run the notebook with jupyterlab, then it also crashes.

So I think it is something to do with ipykernel, not the actual python code, and not VScode. Does that seem like the right conclusion?

**Comment by DonJayamanne** [comment]
>  I think it is something to do with ipykernel, not the actual python code, and not VScode. Does that seem like the right conclusion?

Yes, though i would expect it to crash in VS Code as well if it crashes in Jupyter Lab.
Perhaps you are using two different python environments.
