### ISSUE TITLE
Jupiter lab: Write cell content to file using %%file magic gives error [Errno 21] Is a directory: '/'

### ISSUE THREAD

**Issue by nikolasborrel** [microsoft/vscode-jupyter#1309]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Open a workspace with Jupyter Lab notebook
2. Create a cell with the magic keyword '%%file my_file.txt' at the top and some text below

## Actual behavior
No file is written into the current directory and an error is thrown. NOTE: it works using Jupyter lab running locally in the browser.

Error in calling magic 'file' on cell:
    [Errno 21] Is a directory: '/'
    args: ['my_file.txt']
    kwargs: {'append': False}
Traceback (most recent call last):
  File "/Users/nikolasborrel/opt/anaconda3/lib/python3.7/site-packages/metakernel/magic.py", line 96, in call_magic
    func(*args, **kwargs)
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/metakernel/magics/file_magic.py", line 33, in cell_file
    os.makedirs(path)
  File "/Users/user/opt/anaconda3/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
IsADirectoryError: [Errno 21] Is a directory: '/'

## Expected behavior
Should write the file my_file.txt with the content of the cell

### Your Jupyter and/or Python environment

-   **Jupyter server running:** Local
-   **Extension version:** 2020.8.10939020YY.MM.#####-xxx
-   **VS Code version:** 1.49.0
-   **Setting python.jediEnabled:** ?
-   **Setting python.languageServer:** Jedi
-   **Python and/or Anaconda version:** conda 4.8.5
-   **OS:** Mac OS 10.15.6
-   **Virtual environment:** conda
-   **Python version:** 3.7.8

## Python Output

[debug.log](https://github.com/microsoft/vscode-python/files/5239352/debug.log)

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by DonJayamanne** [comment]
Closing this issue , as this now works as expected.
Please feel free to re-open this issue or re-create a new one and we'll be happy to look into this.
