### ISSUE TITLE
Testing the zeromq module in Jupyter Notebooks with Electron 22

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13093]
Testing the zeromq module in Jupyter Notebooks with Electron 22

Refs: #5206

- [ ] macOS @digitarald
- [x] linux @chrmarti
- [x] windows @joyceerhl

Complexity: 3

Authors: @DonJayamanne  @deepak1556 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%235206%0A%0A&assignees=DonJayamanne)

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2313093%0A%0A&assignees=DonJayamanne,,deepak1556)

---

### Requirements

- Refer to this extension to get the right VS Code bits https://github.com/microsoft/vscode/issues/177646
- Have a python environment installed
- Have Python extension installed (preferably latest pre-release)
- Have Jupyter pre-release extension installed
- On Windows, please ensure you have the C++ runtime files installed, see here https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
    - Without this installed the zeromq binary will fail to load. 

### Steps without Conda
* Open a notebook 
* Add a cell with the following python code
```python
print("Hello World")
```
* Click the Run button
* If prompted to install ipykernel, then install it
* Verify the cell ran successfully and output is displayed
* Very the  messages `Exception while attempting zmq : Error: No native build was found for platform` is displayed towayds the top of the `Jupyter` output panel 
* NOTE: If the above error message is present, then the test has failed

**Comment by digitarald** [comment]
All works for me, except I don't get the output error:

> Very the messages Exception while attempting zmq : Error: No native build was found for platform is displayed towayds the top of the Jupyter output panel

What I get:

```
info 17:58:42.985: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd07e1998ff7f8aa20ada591c520b972326324e5ea05489af9e422744c7c09f6dad./usr/local/bin/python3.10./usr/local/bin/python3.10.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.10.10 (main, Feb 13 2023, 03:30:25) [Clang 14.0.0 (clang-1400.0.29.202)]) for 'Untitled-1.ipynb' (disableUI=false)
warn 17:58:43.035: Failed to get activated env vars for /usr/local/bin/python3.10 in 49ms
info 17:58:43.037: Process Execution: > /usr/local/bin/python3.10 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /usr/local/bin/python3.10 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
warn 17:58:43.038: Failed to get activated env vars for /usr/local/bin/python3.10 in 39ms
warn 17:58:43.039: Failed to get activated env vars for /usr/local/bin/python3.10 in 39ms
info 17:58:43.041: Process Execution: > /usr/local/bin/python3.10 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9016 --control=9014 --hb=9013 --Session.signature_scheme="hmac-sha256" --Session.key=b"a5ff54e2-6eed-44dc-a57b-890f0fb1ffad" --shell=9015 --transport="tcp" --iopub=9017 --f=/Users/digitarald/Library/Jupyter/runtime/kernel-v2-16139zJD3UCAbuswR.json
> /usr/local/bin/python3.10 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9016 --control=9014 --hb=9013 --Session.signature_scheme="hmac-sha256" --Session.key=b"a5ff54e2-6eed-44dc-a57b-890f0fb1ffad" --shell=9015 --transport="tcp" --iopub=9017 --f=/Users/digitarald/Library/Jupyter/runtime/kernel-v2-16139zJD3UCAbuswR.json
info 17:58:43.041: Process Execution: cwd: /
cwd: /
info 17:58:43.277: ipykernel version & path 6.16.0, ~/Library/Python/3.10/lib/python/site-packages/ipykernel/__init__.py for /usr/local/bin/python3.10
info 17:58:43.870: Started Kernel Python 3.10.10 (pid: 17544)
```
