### ISSUE TITLE
Support Python language server for remote (localhost) Python kernels

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-jupyter#13095]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I have an Azure ML compute instance, that has a Jupyter server running on port 8888.

- Then I make a remote connection in VS Code (using the Azure ML extension)
- Once connected I open a notebook and click "Select Kernel"
- I select "Existing Jupyter Server...", then I enter http://localhost:8888 and select a kernel that I know contains the packages I need for my notebook
- I can run my notebook without any problems, but the cells show squiggly lines and complains about the packages not being found

![image](https://user-images.githubusercontent.com/56176070/225708161-1994a030-75e8-44bd-9703-672f4bdc9b9b.png)

### VS Code Version

1.76.2

### Jupyter Extension Version

v2023.2.1200692131

### Jupyter logs

```shell
Visual Studio Code (1.76.2, amlext, vscode.dev)
Jupyter Extension Version: 2023.2.1200692131.
Python Extension Version: 2023.4.1.
Workspace folder /home/azureuser/cloudfiles/code
User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'jupyterTestcf'
info 17:31:01.510: LSP Notebooks experiment is enabled
info 17:31:04.067: Checking for server existence.
info 17:31:04.069: Connecting to server
info 17:31:04.070: Connecting remote server kernel http://localhost:8888/
Connecting to Jupyter server at http://localhost:8888/
warn 17:31:04.185: Password for http://localhost:8888/ was invalid.
info 17:31:04.185: Creating server with url : http://localhost:8888/
info 17:31:04.215: Server started.
info 17:31:04.216: Creating server with url : http://localhost:8888/
info 17:31:04.216: Creating server with url : http://localhost:8888/
info 17:31:05.645: Process Execution: > /anaconda/bin/python -m pip list
> /anaconda/bin/python -m pip list
info 17:32:22.336: Creating server with url : https://<redacted>1.westus.instances.azureml.ms/
info 17:32:23.131: Checking for server existence.
info 17:32:23.131: Connecting to server
info 17:32:23.644: Connecting remote server kernel https://<redacted>1.westus.instances.azureml.ms/
Connecting to Jupyter server at https://<redacted>1.westus.instances.azureml.ms/
info 17:32:23.644: Creating server with url : https://<redacted>1.westus.instances.azureml.ms/
info 17:32:23.655: Server started.
info 17:32:23.655: Creating server with url : https://<redacted>1.westus.instances.azureml.ms/
info 17:33:00.445: Process Execution: > /anaconda/envs/azureml_py310_sdkv2/bin/python -m pip list
> /anaconda/envs/azureml_py310_sdkv2/bin/python -m pip list
info 17:34:01.787: Disposing kernel 49d8ce31a50332edd7661e7f202762785400bc84a95074b1928c0ffc55182d4d..python310-sdkv2./anaconda/envs/azureml_py310_sdkv2/python./.-m#ipykernel_launcher for notebook /home/azureuser/cloudfiles/code/Users/<redacted>/notebook-samples/test-pandas.ipynb due to selection of another kernel or closing of the notebook
info 17:34:01.787: Dispose Kernel '/home/azureuser/cloudfiles/code/Users/<redacted>/notebook-samples/test-pandas.ipynb' associated with '/home/azureuser/cloudfiles/code/Users/<redacted>/notebook-samples/test-pandas.ipynb'
info 17:34:03.789: Checking for server existence.
info 17:34:03.790: Connecting to server
info 17:34:03.790: Connecting remote server kernel http://localhost:8888/
Connecting to Jupyter server at http://localhost:8888/
info 17:34:03.790: Creating server with url : http://localhost:8888/
info 17:34:03.793: Server started.
info 17:34:03.793: Creating server with url : http://localhost:8888/
info 17:34:03.801: Checking for server existence.
info 17:34:03.802: Connecting to server
info 17:34:04.524: Connecting remote server kernel https://<redacted>1.westus.instances.azureml.ms/
Connecting to Jupyter server at https://<redacted>1.westus.instances.azureml.ms/
info 17:34:04.524: Creating server with url : https://<redacted>1.westus.instances.azureml.ms/
info 17:34:04.535: Server started.
info 17:34:04.536: Creating server with url : https://<redacted>1.westus.instances.azureml.ms/
info 17:41:35.822: Disposing kernel 49d8ce31a50332edd7661e7f202762785400bc84a95074b1928c0ffc55182d4d..python38-azureml-pt-tf./anaconda/envs/azureml_py38_PT_TF/python./.-m#ipykernel_launcher for notebook /home/azureuser/cloudfiles/code/Users/<redacted>/notebook-samples/test-pandas.ipynb due to selection of another kernel or closing of the notebook
info 17:41:35.822: Dispose Kernel '/home/azureuser/cloudfiles/code/Users/<redacted>/notebook-samples/test-pandas.ipynb' associated with '/home/azureuser/cloudfiles/code/Users/<redacted>/notebook-samples/test-pandas.ipynb'
info 17:41:37.823: Creating server with url : http://localhost:8888/
info 17:41:37.827: Creating server with url : https://<redacted>1.westus.instances.azureml.ms/
info 17:47:10.916: Starting Jupyter Session startUsingRemoteKernelSpec, 8c822c3bbf09d11ec798d8488a143916fae1424f8b4499cdcfa43f9d73b8be0c..python310-sdkv2./anaconda/envs/azureml_py310_sdkv2/python./.-m#ipykernel_launcher for '/home/azureuser/cloudfiles/code/Users/<redacted>/notebook-samples/test-pandas.ipynb' (disableUI=false)
http://localhost:8888/: Kernel started: 078a73bc-4856-4aac-b8ea-56f4eb41d6a2
info 17:47:18.357: Started session for kernel startUsingRemoteKernelSpec:8c822c3bbf09d11ec798d8488a143916fae1424f8b4499cdcfa43f9d73b8be0c..python310-sdkv2./anaconda/envs/azureml_py310_sdkv2/python./.-m#ipykernel_launcher
http://localhost:8888/: Creating new notebook 
info 17:47:18.455: Creating server with url : https://<redacted>1.westus.instances.azureml.ms/
info 17:47:18.455: Creating server with url : http://localhost:8888/
```

### Running Jupyter locally or remotely?

N/A or Not sure

**Comment by DonJayamanne** [comment]
# Proposed solution

When dealing with remote jupyter python  kernels we should not display any errors about pakcages not being found.

**Comment by DonJayamanne** [comment]
# Note
* Server is localhost
* Hence python env is locally available
* So we should be able to figure the python env and pass that over to python language server

**Comment by giahung24** [comment]
Hello, 
I really appreciate this feature update. 90% of time I work with the notebook and I dont' want to use local kernel started by the extension. So, I have my jupyterlab running on localhost and connect vscode to this jupyter server. But this current bug really annoying, it disables all intellisense features (code autocomplete, wrong python interpreter -> wrong go to definition,...) 
So to continue my works, I have to switch back to jupyterlab (real sad to quit Vscode).

Could you prioritize this issue for the next release please ?

**Comment by avneeshs1** [comment]
My original thought was whether having a setting that allowed allowed users to choose an interpreter to be passed for external (truly remote or not) kernels, would alleviate this issue. However, @DonJayamanne correctly pointed out that that only works if there is only one type of kernel is being used. I think a cleaner solution might have to involve having users specify the language server interpreter per external kernel. 

However, I do think the jupyter extension should return the python extension's interpreter as the default for remote kernels. That change does not seem any worse than what is happening now and it helps at least some of cases where people are spinning up external jupyter servers to maintain state between VSCode restarts/disconnects etc. Thoughts?

**Comment by avneeshs1** [comment]
Got it. Thanks for clarifying. So, let us not change any current defaults. 

Then, IMHO, until we have a pylance interpreter setting per remote kernel notebook, at least having one setting for all remote kernels (defaults to unset) is a positive, no? That way, nothing really breaks/changes for people but for a bunch of us who are using remote kernels primarily because on instability of VSCode spun up kernels, this extra setting does the trick. Eventually, when pylance kernels are available on a per notebook basis, this can setting can be subsumed. I don't really have any other ideas.

**Comment by DonJayamanne** [comment]
Closing this issue as there isn't enough incentive to make this happen.
If this is a blocker, please do create a new issue and we can look into this.

**Comment by rzhao271** [comment]
Hi @DonJayamanne, what are some verification steps for this issue?

**Comment by DonJayamanne** [comment]
Will get @sevillal to verify this.

**Comment by sevillal** [comment]
Verified.
