### ISSUE TITLE
Test zeromq module in Jupyter Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13092]
Testing the zeromq module in Jupyter Notebooks

Refs: #5206

- [x] linux @connor4312 (ubuntu or other, but not alpine) (64bit)
- [x] linux @rzhao271 (Alpine) (64bit)
- [x] linux @dbaeumer (ubuntu or other, Alpine is not yet supported) (arm64) (TIP: Someone with Apple Silicon can test this in a docker container)
- [x] macOS @eleanorjboyd (Apple Silicon, arm64)
- [x] macOS @paulacamargo25 (intel 64bit)
- [x] windows @rebornix (32bit)
- [x] windows @esonnino (64bit)

Complexity: 3

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%235206%0A%0A&assignees=DonJayamanne)

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2313092%0A%0A&assignees=DonJayamanne)

---

### Requirements

- Have a python environment installed
- Have Python extension installed (preferably latest pre-release)
- Have Jupyter pre-release extension installed
- On Windows, please ensure you have the C++ runtime files installed, see here https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
    - Without this installed the zeromq binary will fail to load. 

### Steps without Conda
* Open a notebook 
* Add a cell with the following python code
```python
print("Hello World")
```
* Click the Run button
* If prompted to install ipykernel, then install it
* Verify the cell ran successfully and output is displayed
* Very the  messages `Exception while attempting zmq : Error: No native build was found for platform` is not displayed towayds the top of the `Jupyter` output panel 
* NOTE: If the above error message is present, then the test has failed

**Comment by DonJayamanne** [comment]
Please note, I have udpated the test plan item to indicate the fact that the error message should NOT exisxt, i forgot the word `not`. apologies for that.
Hopefully everyone else testing this will not run into the same issue that @dbaeumer ran into.

**Comment by connor4312** [comment]
Works perfectly on Ubuntu 22.04 🙂

**Comment by paulacamargo25** [comment]
Works great on Mac.

**Comment by TylerLeonhardt** [comment]
@rebornix confirmed working via chat
