### ISSUE TITLE
IPython.display.update_display interface failed since the second call

### ISSUE THREAD

**Issue by zjl9959** [microsoft/vscode-jupyter#13105]
## Environment data

-   VS Code version: 1.76.2 ee2b180d582a7f601fa6ecfdad8d9fd269ab1884 x64
-   Jupyter Extension version: v2023.2.1000592019
-   Python Extension version: v2023.4.1
-   OS and version: Windows10 Pro 21H2
-   Python and/or Anaconda version: Python 3.9.16/conda 4.12.0
-   Type of virtual environment used: conda
-   Jupyter server running: Local
-  IPython version: 8.11.0

## Expected behaviour

![v2023 1 20010391206](https://user-images.githubusercontent.com/28183761/226115305-b37e4f9f-41bb-4f0b-8783-a8b3e481a8ab.gif)

## Actual behaviour

![v2023 2 1000592019](https://user-images.githubusercontent.com/28183761/226115310-f8a24b02-6353-440c-ae2b-f587234a5e80.gif)

## Steps to reproduce:

Run this code in a jupyter notebook:

```python
from IPython import display
import time

display.display(display.HTML('<h1>A</h1>'), display_id='1')
time.sleep(2)
display.update_display(display.HTML('<h1>B</h1>'), display_id='1')
time.sleep(2)
display.update_display(display.HTML('<h1>C</h1>'), display_id='1')
```

### However, Jupyter Extension version v2023.2.1000592019 gives the wrong behaviour.

Please take a look, thanks!

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by Yard1** [comment]
Hi @DonJayamanne, I seem to still run into this issue if the `update` call is made from a separate cell.

VS Code version: 1.77.3 704ed70d4fd1c6bd6342c436f1ede30d1cff4710 x64
Jupyter Extension version: v2023.3.1201040234

Cell 1:
```python
from IPython.display import display
from time import sleep

dis = display('1', display_id=True)
sleep(1)
dis.update('2')
```

Cell 2:
```python
dis.update('3')
sleep(1)
dis.update('4')
```

Expected output:
```
'4'
```

Actual output:
```
'3'
```

**Comment by Yard1** [comment]
Furthermore, if there are several `update` calls made one after another, the output breaks as well.
```python
from IPython.display import display

ref = display('1', display_id=True)
ref.update('2')
ref.update('3')
```

Expected output:
```
'3'
```

Actual output:
```
```
(empty)

**Comment by DonJayamanne** [comment]
> Furthermore, if there are several update calls made one after

I cannot replicate this issue, please could you update the sample code.
As there's no code used to display the `ref`

**Comment by Yard1** [comment]
Sorry, I may be misunderstanding, but there is `ref = display('1', display_id=True)` in the sample (which works as intended by itself).
