### ISSUE TITLE
 we cannot see what we entered in the " input() " 

### ISSUE THREAD

**Issue by eswar-abhi** [microsoft/vscode-jupyter#13116]
after using " input() "to get the user data 

we enter some data in the box that appears at the top of the frame

and after we can't able to what we entered init

"""
I think we can able to see what we enter data in  "input() pannel " at the output side

"""

![input](https://user-images.githubusercontent.com/74318146/226474724-a55a4d9d-e3a1-4c5b-9b94-c417ef02e39a.png)

![output](https://user-images.githubusercontent.com/74318146/226475193-bf754ba2-2d9c-4e74-9dba-38603f21cf79.png)

**Comment by xflcx1991** [comment]
![图片](https://user-images.githubusercontent.com/3775351/227719284-c9019932-22f4-4f23-b914-21884cf6777f.png)
Here it is.

**Comment by DonJayamanne** [comment]
Closing this issue as out of scope as this hasn't beeen upvoted since this was ctated
