### ISSUE TITLE
Still prompted to install additional packages

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-jupyter#13129]
Testing #13124

Following the steps, I still receive this dialog: 

<img width="566" alt="image" src="https://user-images.githubusercontent.com/6561887/226637605-6f2a82c7-71b4-4f99-b220-e757d2fc13db.png">

**Comment by DonJayamanne** [comment]
@sbatten 
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.


either you haven’t got the latest pre-release version of the Jupyter extension (in vsc insiders)  or there is some other weird bug, hence the request for the logs
Please do send all the logs when running in verbose log level
