### ISSUE TITLE
Support for not automatically wrapping when reading csv files

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode-jupyter#13125]
![image](https://user-images.githubusercontent.com/100815370/226527330-9dc6fcfa-0746-4eb7-acb0-e2051efc0b4d.png)

I have a csv file that I used `pandas` to read and run in terminal and jupyter, respectively. Obviously, it is not automatically wrapped in the terminal while jupyter did. 

I hope there are settings that can be customized for this. I tried the following but it didn't work:

```
  "notebook.editorOptionsCustomizations": {
    "notebook.lineNumbers": "on",
    "notebook.output.textLineLimit": 100,
  }
```

**Comment by amunger** [comment]
It looks like pandas itself has some options for this:

```
pd.set_option('display.width', 200)
print(df.head())
```

or, just don't use print to display the data:

```
df.head()
```

Does that fix the issue for you?

**Comment by ydmykr** [comment]
@amunger This works. Thank you a lot.
