### ISSUE TITLE
Select Conda Environments in a Jupyter Notebook Kernel that do not contain Python runtime

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13124]
Test selecting Conda Environments that do not contain Python

Refs: #11855

- [x] macOS @sbatten 
- [x] linux @aeschli 
- [x] windows @andreamah 

Complexity: 3

Authors: @DonJayamanne

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2311855%0A%0A&assignees=DonJayamanne)

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2313124%0A%0A&assignees=DonJayamanne)

---

### Requirements

- Have a Conda installed installed
- Have latest pre-release version of Python extension installed
- Have Jupyter pre-release extension installed

### Steps without Conda
* Open a terminal and create an empty conda environment using the following CLI
`conda create -y -n <EnvName>`
* Open a notebook 
* Go into the kernel picker and select `Python Environments`
* [ ] Verify the kernel by the name `<EnvName>` exists in the Kerne picker under a section `Conda Env Without Python`
* [ ] Verify the tooltip for this environment in the quick pick makes sense
* Select this `<EnvName>` kernel
    * Upon selection some dependencies will be automatically installed (the dependencies installed are `IPyKernel` and `Python Runtime`)
    * NOTE: this could take some time
* [ ] Verify you can now run a cell against this kernel (without any errors or prompt to install any packages)
* Go back to the kernel picker
* [ ] Verify the kernel `<EnvName>` now appears in a different section `Conda Env` and contains the Python environment information, such as Python version number

**Comment by aeschli** [comment]
Tested on fresh Ubuntu 20.04 VM with Anaconda, worked flawlessly!
