### ISSUE TITLE
Can't execute k3d widget notebook

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#13131]
Testing microsoft/vscode#177719

1. Open https://github.com/microsoft/vscode-jupyter/blob/main/src/test/datascience/widgets/notebooks/k3d_widgets.ipynb
2. Install k3d
3. Run first cell
4. :bug: Cell never completes, no errors in output or dev tools

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/30305945/226673797-f43b2a09-eb3a-433f-bf57-2e5539deb0da.png">

**Comment by DonJayamanne** [comment]
Works for me, please do share the verbose logs

**Comment by joyceerhl** [comment]
So I went and split out all the lines in that notebook, and it looks like this succeeds:

https://insiders.vscode.dev/github.com/microsoft/vscode-jupyter/blob/adfc442a2178eff34d9cdc5aa049acecfbc9e8a9/src/test/datascience/widgets/notebooks/k3d_widgets.ipynb#C4:L1-L9

But executing this line never returns

https://insiders.vscode.dev/github.com/microsoft/vscode-jupyter/blob/adfc442a2178eff34d9cdc5aa049acecfbc9e8a9/src/test/datascience/widgets/notebooks/k3d_widgets.ipynb#C4:L11

**Comment by DonJayamanne** [comment]
Thanks, but that doesn't help.
Please could you try https://github.com/microsoft/vscode-jupyter/issues/13131#issuecomment-1480149478

**Comment by joyceerhl** [comment]
Tried with Python 3.10 from the Windows store, also didn't work.
No errors in dev tools or Jupyter console.
This notebook runs in the selected Python environment as confirmed with `import sys; print(sys.executable)`

**Comment by joyceerhl** [comment]
Weirdly, if I run `python3 -m pip install jupyter notebook` from the CLI, I get a message saying that all packages are already installed, and if I rerun the k3d notebook, the cell still fails to complete. But if I run `import sys; !{sys.executable} -m pip install jupyter notebook` in a notebook cell, then the cell completes. So I think the k3d library and/or the ipywidgets library have not declared a dependency on the `notebook` submodule that is really required to execute that library. I don't think this is a Jupyter extension problem at all, probably something that needs fixing in k3d and/or ipywidgets.

**Comment by DonJayamanne** [comment]
> robably something that needs fixing in k3d and/or ipywidgets.

Great, thanks for digging into this, will close this issue.

FYI: Instead of using `python3 -m pip install`, you need to activate the python environment you are working on and then run 
* `python -m pip install` or 
Use this for virtual environments, conda envs and the like
* `<fully qualified path to Python> -m pip install`, use the latter when dealing with globally installed python environments like Python in windows store or the like.
