### ISSUE TITLE
Expose reference to Python file from Interactive Window cell

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode-jupyter#13130]
Currently, it is not possible to trace back from an Interactive Window to the original source Python file.

As discussed with @amunger there isn't always a 1:1 match from Interactive Window to Python files depending on the `jupyter.interactiveWindow.creationMode` setting, but it should technically be possible to link from a cell back to the Python file similar to what `jupyter.interactive.goToCode` is doing.

It would be great if we could expose this capability so that extensions could update the original source as the Interactive Window is read-only.

**Comment by jabbera** [comment]
Consider this an upvote so data wranger can support interactive windows! https://github.com/microsoft/vscode-data-wrangler/issues/18

**Comment by dreadedhamish** [comment]
I'd very much like Data Wrangler to be able to interact with the Interactive Window.

**Comment by DonJayamanne** [comment]
Closing this as out of scope of now,
@pwang347 we can discuss this offline if and when this is necessary.
Right now it feels like a nice to have.
