### ISSUE TITLE
Jupyter kernel not restarting

### ISSUE THREAD

**Issue by nicoloceneda** [microsoft/vscode-jupyter#13138]
-   VS Code version: 1.76.2
-   Jupyter Extension version: v2023.2.1200692131
-   Python Extension version: v2023.4.1
-   OS and version: Mac Ventura 13.1 (Apple M1 Max)
-   Python version: 3.10.5
-   Type of virtual environment used: conda virtual environment
-   Jupyter server running: Local 

## Expected behaviour

When pressing the button restart, the kernel should restart. 

## Actual behaviour

The kernel fails to restart (roughly 1 in 3 times) and the following pop up window keeps loading. 

<img width="383" alt="Screenshot 2023-03-22 at 02 58 54" src="https://user-images.githubusercontent.com/47401951/226790697-4f7800be-3475-4a9e-9ead-b285b7ee98ab.png">

I can solve the issue by closing the whole window (not just the script that generated the issue) e restarting everything from zero. 

## Steps to reproduce:

Restart the kernel enough times. Sooner or later it will generate the behavior.

**Comment by DonJayamanne** [comment]
thanks for filling this issue and sorry you are running into this issue
It looks like the kernel is crashing at your end 
i suspect you would run into this same issue with classic Jupyter notebooks outside vscode as well

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by nicoloceneda** [comment]
No I do not run into the same issue with the classic jupyter notebook. I turned on the logging and this is what I see:
<img width="1647" alt="Screenshot 2023-03-22 at 03 32 33" src="https://user-images.githubusercontent.com/47401951/226795271-abe59096-2cd3-4f4f-8ca3-5c77f26ecb91.png">

**Comment by DonJayamanne** [comment]
To get to the Jupyter panel please go into the command palette and use the command ‘Jupyter: Show Output’

**Comment by nicoloceneda** [comment]
Here is the output:

```
debug 14:48:07.996: Executing silently Code (completed) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info a with 1 output(s)
debug 14:48:07.997: Executing silently Code (completed) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info a with 1 output(s)
debug 14:48:07.998: Executing silently Code (completed) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info a with 1 output(s)
debug 14:48:08.000: Executing silently Code (completed) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info a with 1 output(s)
debug 14:48:08.000: Executing silently Code (completed) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info a with 1 output(s)
debug 14:48:08.182: shutdownSession 66956a70-5f5b-48a1-b4e1-63f899c762fc, .envml./Users/nicoloceneda/miniforge3/envs/envML/python./Users/nicoloceneda/miniforge3/envs/envML/python.-m#ipykernel_launcher - shutdown complete
debug 14:48:21.422: Interrupt kernel command handler for /Users/nicoloceneda/Dropbox/Bhamra-Ceneda/research/recovery rates/code/results_card_1.ipynb
```

The kernel gets stuck roughly 60% of the times I try to restart it.

**Comment by nicoloceneda** [comment]
Permanently stuck in this state:

![Screenshot 2023-03-29 at 14 50 57](https://user-images.githubusercontent.com/47401951/228559713-92972955-8a8b-4ed5-b192-6c65ebedfaf3.png)

**Comment by nicoloceneda** [comment]
I calculated: 7 out of 10 times that I have run all cells or restarted the kernel, the kernel has stopped working, requiring to close and re-open the application.

**Comment by DonJayamanne** [comment]
@nicoloceneda 

* Please could you copy ALL of the output and share that, without the logs its almost impossible to help here.
* Are you running into this with all environments? Can you try creating a new environment and see whether the issue replicates there too.
* Optionally, please could you try the following (downgrade some packages as described in the comments) https://github.com/microsoft/vscode-jupyter/issues/12775#issuecomment-1447175314

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
