### ISSUE TITLE
The contents of this.outputs are not saved

### ISSUE THREAD

**Issue by slundberg** [microsoft/vscode-jupyter#13135]
## Environment data

-   VS Code version:  1.76.2
-   Jupyter Extension version (available under the Extensions sidebar): v2023.2.1200692131
-   Python Extension version (available under the Extensions sidebar): v2023.4.1
-   OS (Windows | Mac | Linux distro) and version: Mac 13.2.1 (22D68)
-   Python and/or Anaconda version: 3.9.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

## Expected behaviour

When `_repr_javascript_` is called the `this` object in the local scope represents the output area of the cell. In standard Jupyter notebooks the Javascript can store data in that object so that when the notebook is saved the contents reflect what the user sees on the screen. I would expect this to also work in VSCode.

## Actual behaviour

In VSCode notebooks a `this` object is passed, and it does come with an `outputs` property, but changes to that property do not get respected during the notebook saving process.

## Steps to reproduce:

```
from IPython.display import Javascript
Javascript("""
window.local_this = this;
function f() {
var content = "CONTENT6";
element[0].innerText = content;
window.local_this.outputs[0]["data"]["text/plain"] = [content];
}
setTimeout(f, 0)
""")
```

In a standard Jupyter notebook this results in a meaningful plain text representation stored in the saved ipynb file. But in VSCode the output object that is provided seems to be disconnected from the saving infrastructure, so the plain text representation remains "<IPython.core.display.Javascript object>" and not "CONTENT6" like it should be.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.

Unfortunately updating the cell outputs from within the rendered JS code is not supported and is out of scope.
If you try this same code in Jupyter Lab you'll see that it doesn't work there either.

You could optionally use ipywidgets or the like to send a message back to the kernel to update the same ouput, have a look at `IPython.display` or similar concepts.

Closing this as out of scope

**Comment by DonJayamanne** [comment]
> m the client side I think, so I am not sure how to update it from the Python side. Right n

You can send messages from the front end to the back end via kernel messages, when using ipywidgets.
I would suggest looking into ipywidgets.
