### ISSUE TITLE
Native Notebooks - No "Edited Since Execution" Indicator

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#1313]
# Feature Enhancement

Currently there is no indicator that tells a user that a cell has been edited since last executed. 

Which of the following below did I run? 

![R](https://user-images.githubusercontent.com/19276747/91369732-60fb2e80-e7c1-11ea-8f63-9585565649d2.PNG)
![G](https://user-images.githubusercontent.com/19276747/91369743-65274c00-e7c1-11ea-811a-0e7cc6b38b70.PNG)
![B](https://user-images.githubusercontent.com/19276747/91369756-6d7f8700-e7c1-11ea-83ef-0af09aa65bd5.PNG)

### If cell has been run and since edited, change green check mark to one of the following. 
Pros + Cons to be discussed

![Screen Shot 2020-08-26 at 6 14 21 PM](https://user-images.githubusercontent.com/19276747/91372305-29dc4b80-e7c8-11ea-85a2-8ee18d57b057.png)

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by DonJayamanne** [comment]
Closing as we no longer have the executed indicator when opening eixsitng notebooks.

**Comment by claudiaregio** [comment]
This feature request was not for opening existing notebooks. I was actually thinking for a use case when working in the notebook, a way to know if the output that is paired with the input was in fact correct or if the input was changed since the last run (aka output may not longer match). 

JupyterLab ended up implementing it a few months ago: https://twitter.com/martinRenou/status/1404345440817057797

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, however given that this has only receieved only 3 upvotes in the 3 years since this was created, I'm closing this for now
