### ISSUE TITLE
Cannot add a remote jupyter server from vscode.dev (or even desktop) without a refresh/reload

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-jupyter#13146]
1. Have a plain vscode.dev profile. Create a new Jupyter Notebook, and try to execute it
2. See there's no kernel extension installed. Browse the marketplace, and choose to install the Jupyter extension
3. Select a kernel. Choose "Existing Jupyter Server" 

    <img width="631" alt="image" src="https://user-images.githubusercontent.com/2230985/227035999-be83105b-171a-4de1-9bc9-9a71555f8e38.png">
    
4. Paste in the URL, and hit enter

5. You're brought back to step 3 🐛 

6. Try to enter the server URL again, and you get an error 

    <img width="628" alt="image" src="https://user-images.githubusercontent.com/2230985/227036138-96d726be-06eb-4640-8cbb-caca2187d1af.png">
7. Refresh the page and pick a kernel again. Things work now 

    <img width="618" alt="image" src="https://user-images.githubusercontent.com/2230985/227036240-cdf473f8-bf2c-4179-af7a-3055c761c16c.png">

**Comment by DonJayamanne** [comment]
I think i know whats happening, when we're taking the user back to step 3, then we're busy refreshing the list of kernels
thats why we take the user back
Perhaps we should display an empty entry in there to let the user know that we're fetching them.

**Comment by astroboylrx** [comment]
When you say "Refresh the page", what exactly did you do?
I run into the same issue and cannot connect to a local server.

**Comment by DonJayamanne** [comment]
@astroboylrx 
Sorry you are running into this (similar) issue
Please could you describe what you are seeing,
optionally, please could you share the following logs

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by astroboylrx** [comment]
Do you mind first answering me how to "Refresh the page"?

I saw exactly as you picture showed:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/3999966/227430915-53fa73ed-2ad0-4d8c-bf08-1f5f85eaeb95.png">

I followed your instructions and attached the verbose log from starting VS Code to the time it shows "A Jupyter Server with this URL already exists" 
[jupyter.log](https://github.com/microsoft/vscode-jupyter/files/11058669/jupyter.log)

**Comment by DonJayamanne** [comment]
> Do you mind first answering me how to "Refresh the page"?

If you are using VS Code  in the browser, then just refresh the webpage like any other page
If you are using VS Code in the desktop, then please re-load VS Code, 

Thanks for the logs, will check this out.

**Comment by DonJayamanne** [comment]
This should now be fixed in the latest pre-release version
