### ISSUE TITLE
zmq fails to start and stuck on "Detecting Kernels" on fresh windows 10 VM

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#13147]
Found while verifying https://github.com/microsoft/vscode-jupyter/issues/11854, but that had a string of issues so making a new one.

1. create a new Windows 10 VM on azure
2. download vscode insiders and install pre-release jupyter and python
3. open a notebook
:bug: Detecting kernels is spinning forever

from the logs:
```
warn 22:17:38.570: Exception while attempting zmq : The specified module could not be found.
\\?\c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.3.1000830504\out\node_modules\zeromq\prebuilds\win32-x64\node.napi.glibc.node
```
that file does exist, so the `\\?\` prefix is probably messing with it.

## Logs

<details>

Visual Studio Code - Insiders (1.77.0-insider, undefined, desktop)
Jupyter Extension Version: 2023.3.1000830504.
Python Extension not installed.
No workspace folder opened.
warn 22:17:38.570: Exception while attempting zmq : The specified module could not be found.
\\?\c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.3.1000830504\out\node_modules\zeromq\prebuilds\win32-x64\node.napi.glibc.node
warn 22:17:38.570: Exception while attempting zmq (fallback) : The specified module could not be found.
\\?\c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.3.1000830504\out\node_modules\zeromqold\prebuilds\win32-x64\electron.napi.node
info 22:17:39.197: LSP Notebooks experiment is disabled -- not using Pylance
info 22:17:39.257: Process Execution: > jupyter notebook --version
> jupyter notebook --version
info 22:17:39.265: Process Execution: > jupyter lab --version
> jupyter lab --version
info 22:18:41.394: LSP Notebooks experiment is enabled
info 22:19:13.925: Attempting to start a server because of preload conditions ...
info 22:19:13.933: Checking for server existence.
error 22:19:13.991: Error starting server in serverPreload:  [im [Error]: Jupyter cannot be started. Error attempting to locate Jupyter: Select an Interpreter to start Jupyter
	at fg.startServer (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.3.1000830504\out\extension.node.js:17:209248)
	at async fg.createServer (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.3.1000830504\out\extension.node.js:17:208543)
	at async Hm.connect (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.3.1000830504\out\extension.node.js:17:186849)
	at async Cy.createServerIfNecessary (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.3.1000830504\out\extension.node.js:24:44489)] {
  category: 'jupyterinstall'
}

<p>

**Comment by amunger** [comment]
I'll just add this to the previous issue since it is blocking the rest of verification

**Comment by DonJayamanne** [comment]
> that file does exist, so the \\?\ prefix is probably messing with it.

This is a duplicate of https://github.com/microsoft/vscode-jupyter/issues/13091
This issue is not new but has been around for a very long time.
Though the kernels keep detecting is an interesrting issue, @rebornix can you check this, we have run into this in a few places and we still have an open issue for this that others too ran into
