### ISSUE TITLE
Failed to save ipynb when connected to remote server

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#13158]
From [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details):

> This extension was Good, but somehow my Vscode graded this to the latest version, and things went wrong. The extension repeatedly failed when I was connecting to a remote server. It kept saying, "Failed to save '***.ipynb': Unexpected type." And I tried restarting the software created a new ipynb file. But the error keeps happening about every hour. I only stick to this because I haven't found an alternative.

**Comment by HqChen2021** [comment]
Thanks for reaching out, but I didn't keep the log file and stopped using jupyternote book after that. As I see somewhere else, this problem seems related to the copilot extension. But I haven't verified it

**Comment by DonJayamanne** [comment]
Could be related to https://github.com/microsoft/vscode-jupyter/issues/11435
