### ISSUE TITLE
doesn't work with the latest releases

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#13157]
From [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details):

> This is terrible, doesn't work with the latest releases. Also, the version history doesn't show more than 5 older versions. So, I am unable to roll back to older working versions.

**Comment by DonJayamanne** [comment]
Unfortunately no additional information has been provided, hence closing this issue as there's nothing that can be done to address the reported issue.
