### ISSUE TITLE
random extra stuff gets saved into notebook document

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#13156]
From [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details):

> Awful user interface. Cannot get new kernels working easily, random extra stuff gets saved into cells, and changes cannot be cleared and reset somehow even after closing the window. just terrible. I will need to use a editor just to work with notebooks.

**Comment by DonJayamanne** [comment]
Unfortunately no additional information has been provided, hence closing this issue.
