### ISSUE TITLE
fastprogress progress bar not showing

### ISSUE THREAD

**Issue by bosmart** [microsoft/vscode-jupyter#13163]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Created a progress bar (minimal code example below), but it didn't appear. It also messes with plots created by a fastai callback. Here's the summary of my tests:

v2022.11.1003412109 - fastprogress working, ShowGraphCallback works too
v2023.1.2000312134 - fastprogress working, ShowGraphCallback doesn’t (plot disappears)
v2023.1.2010391206 - fastprogress working, ShowGraphCallback doesn’t (plot disappears)
v2023.2.1000592019 - fastprogress not working, ShowGraphCallback works again
v2023.2.1200692131 - fastprogress not working, ShowGraphCallback works again

I'm attaching a notebook with minimal example of progress bar and progress bar+graph callback:
[fastprogress_min.ipynb.zip](https://github.com/microsoft/vscode-jupyter/files/11060247/fastprogress_min.ipynb.zip)

Here's what it should look like (and does with v2022.11.1003412109):
![Screenshot 2023-03-24 at 09 14 09](https://user-images.githubusercontent.com/5089507/227476520-ff9ea64c-87c0-422f-8f05-48d96ea71f7b.jpg)

### VS Code Version

1.76.2

### Jupyter Extension Version

v2023.2.1200692131

### Running Jupyter locally or remotely?

Remote

**Comment by bosmart** [comment]
BTW, latest insider build v2023.3.1000830504 also not working.

**Comment by bosmart** [comment]
Yeah, but you don't have some of the functionality that made me move from Jupyter Lab to VSCode in the first place - a proper debugger that allows you to step into 3rd party modules 🤷‍♂️

**Comment by datenzauberai** [comment]
This old workaround from the [fast.ai-forum](https://forums.fast.ai/t/using-visual-studio-code-with-fastai-vscode-bug/77976) still works for me:

`# workaround for https://github.com/microsoft/vscode-jupyter/issues/13163
from IPython.display import clear_output, DisplayHandle
def update_patch(self, obj):
    clear_output(wait=True)
    self.display(obj)
DisplayHandle.update = update_patch`

**Comment by Maimonator** [comment]
> This old workaround from the [fast.ai-forum](https://forums.fast.ai/t/using-visual-studio-code-with-fastai-vscode-bug/77976) still works for me:
> 
> ```
> from IPython.display import clear_output, DisplayHandle
> def update_patch(self, obj):
>     clear_output(wait=True)
>     self.display(obj)
> DisplayHandle.update = update_patch
> ```

Yes this works like a charm thanks!

**Comment by juanitorduz** [comment]
I have been having this issue affecting PyMC 😞. It would be really nice to fix this one 🙏!

**Comment by gaoxianggithub** [comment]
> This old workaround from the [fast.ai-forum](https://forums.fast.ai/t/using-visual-studio-code-with-fastai-vscode-bug/77976) still works for me:
> 
> ```
> from IPython.display import clear_output, DisplayHandle
> def update_patch(self, obj):
>     clear_output(wait=True)
>     self.display(obj)
> DisplayHandle.update = update_patch
> ```

amazing!!! it did work
