### ISSUE TITLE
Improve first python installation for getting started with notebooks

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#13164]
copied mostly from https://github.com/microsoft/vscode-jupyter/issues/11854#issuecomment-1410867746 since some of the clunkiness still exists.

I'm testing on a Windows 10 VM where I only have VS Code Insiders and git installed.

I'm now correctly prompted with installing Python from the Windows store:

![image](https://user-images.githubusercontent.com/25310137/215847739-e9692e5f-9789-4f91-b2ad-fc4ddba532ea.png)
![image](https://user-images.githubusercontent.com/25310137/215847841-6d9f7e5f-3010-4cb8-bcca-6d4fd938b051.png)

But once the Python install completes and I try running the cell again, I'm told Python still isn't installed:
![image](https://user-images.githubusercontent.com/25310137/215848122-f88f4ac5-b56b-4b8a-ac65-c8b18287faf5.png)

I expected to need to reload VS Code, so I close the above prompt and reload. **Can we prompt users to reload here?**

After a VS Code reload, Python is detected, and I'm prompted I'm missing a different package:
![image](https://user-images.githubusercontent.com/25310137/215848554-e70dfad5-0c48-4a47-9ecf-996f602a92c9.png)

installing now works successfully and the cell is run

**Comment by DonJayamanne** [comment]
> xpected to need to reload VS Code, so I close the above prompt and reload. Can we prompt users to reload here?

Agreed

**Comment by DonJayamanne** [comment]
@amunger looks like you have tested this with an old version.
Please could you re-test this with the latest insider bits, we do have a message prompting the user to `reload vs code`
