### ISSUE TITLE
Update & Publish renderer extension and use it in Python extension for Native Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1317]
https://github.com/microsoft/vscode-notebook-renderers

- [ ] Review Extension information
	- name, id, description, license
	- readme
	- contribution doc
- [ ] We need to update the renderer API in renderer extension as we did here: 
https://github.com/microsoft/vscode-python/pull/13665/files
Changes related to the following need to be applied to renderer extension:
	* [index.tsx](https://github.com/microsoft/vscode-python/pull/13665/files#diff-e9d196ad86eab236c4a11ac079541dc7)https://github.com/microsoft/vscode-python/pull/13665/files#diff-e9d196ad86eab236c4a11ac079541dc7
	* [package.json](https://github.com/microsoft/vscode-python/pull/13665/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)https://github.com/microsoft/vscode-python/pull/13665/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

- [ ] After publishing extension, remove related renderer code from DS code (from Python extension)

**Comment by greazer** [comment]
Closed in favor of #1423 (epic)
