### ISSUE TITLE
Cannot connect to jupyterhub server using VS Code, but link works from the browser

### ISSUE THREAD

**Issue by groblercarla** [microsoft/vscode-jupyter#13189]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I would like to open a Jupyterhub notebook in VSCode. 

I followed the steps at https://blog.jupyter.org/connect-to-a-jupyterhub-from-visual-studio-code-ed7ed3a31bcb to create a token and URL. 

VSCode dialog box asks for "Enter the URL of the running Jupyter server". I enter
https://ZZZ:8000/user/YYY/?token=XXX
(where YYY is my username, and XXX is my token, and ZZZ is our domain). 

Initially, I got an error complaining about certificate. 
I followed the steps at: https://github.com/microsoft/vscode-jupyter/issues/8811 and set the "use proxy support for extensions" to "off" in my VSCode settings. 

After retrying (i.e. re-entering my token URL (https://ZZZ:8000/user/YYY/?token=XXX) into the VSCode dialog box, the error now states "Connection failure. Verify the server is running and reachable from a browser. (request to https://ZZZ:8000/hub/login?next= failed, reason: unable to verify the first certificate). When connecting to vscode.dev Jupyter servers must be started with specific options to connect. Click here for more information."
The link goes to: https://github.com/microsoft/vscode-jupyter/wiki/Connecting-to-a-remote-Jupyter-server-from-vscode.dev

The URL for the server does work from the browser (verified that it connects from Edge and Chrome incognito), so there must be something else not working like it should, and the page ( https://github.com/microsoft/vscode-jupyter/wiki/Connecting-to-a-remote-Jupyter-server-from-vscode.dev) indicates that I should log an issue. 

Please let me know if more information would be helpful. 

### VS Code Version

Version: 1.76.2 (user setup) Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884 Date: 2023-03-14T17:55:54.936Z Electron: 19.1.11 Chromium: 102.0.5005.196 Node.js: 16.14.2 V8: 10.2.154.26-electron.0 OS: Windows_NT x64 10.0.22621 Sandboxed: No

### Jupyter Extension Version

v2023.2.1200692131

### Jupyter logs

```shell
Visual Studio Code (1.76.2, ssh-remote, desktop)
Jupyter Extension Version: 2023.2.1200692131.
Python Extension Version: 2023.4.1.
Workspace folder /home/carlau/contrail_advection_pipeline
User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'jupyterTestcf'
info 22:24:38.447: LSP Notebooks experiment is enabled
info 22:24:39.370: Starting Jupyter Session startUsingLocalKernelSpec, .test_env_2_scipy./home/carlau/.conda/envs/test_env_2_scipy/python./home/carlau/.conda/envs/test_env_2_scipy/python.-m#ipykernel_launcher (Python Path: /home/carlau/.conda/envs/test_env_2_scipy, EnvType: Conda, EnvName: 'test_env_2_scipy', Version: 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]) for '/home/carlau/contrail_advection_pipeline/test.ipynb' (disableUI=true)
warn 22:24:39.497: Failed to get activated env vars with python /usr/bin/python3 in 805ms
info 22:24:39.520: Process Execution: > /usr/bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
> /usr/bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
info 22:24:39.583: Process Execution: > /usr/bin/python3 -m pip list
> /usr/bin/python3 -m pip list
info 22:24:41.239: Process Execution: > ~/.conda/envs/test_env_2_scipy/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9086 --control=9084 --hb=9083 --Session.signature_scheme="hmac-sha256" --Session.key=b"b4d358da-a825-4504-8a70-5347c0066d0b" --shell=9085 --transport="tcp" --iopub=9087 --f=/home/carlau/.local/share/jupyter/runtime/kernel-v2-10048182lQjurYkgnCy.json
> ~/.conda/envs/test_env_2_scipy/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9086 --control=9084 --hb=9083 --Session.signature_scheme="hmac-sha256" --Session.key=b"b4d358da-a825-4504-8a70-5347c0066d0b" --shell=9085 --transport="tcp" --iopub=9087 --f=/home/carlau/.local/share/jupyter/runtime/kernel-v2-10048182lQjurYkgnCy.json
info 22:24:41.239: Process Execution: cwd: ~/contrail_advection_pipeline
cwd: ~/contrail_advection_pipeline
info 22:24:41.326: Process Execution: > ~/.conda/envs/test_env_2_scipy/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~/.conda/envs/test_env_2_scipy/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 22:24:41.346: Process Execution: > ~/.conda/envs/test_env_2_scipy/bin/python -m pip list
> ~/.conda/envs/test_env_2_scipy/bin/python -m pip list
warn 22:24:41.614: StdErr from Kernel Process /home/carlau/.local/lib/python3.8/site-packages/jupyter_client/__init__.py:23: UserWarning: Could not import submodules
  warnings.warn("Could not import submodules")

info 22:24:41.615: ipykernel version & path 6.15.0, ~/.local/lib/python3.8/site-packages/ipykernel/__init__.py for /home/carlau/.conda/envs/test_env_2_scipy/bin/python
warn 22:24:41.615: Stderr output when getting ipykernel version & path /home/carlau/.local/lib/python3.8/site-packages/jupyter_client/__init__.py:23: UserWarning: Could not import submodules
  warnings.warn("Could not import submodules") for /home/carlau/.conda/envs/test_env_2_scipy/bin/python
info 22:24:42.456: Started Kernel [test_env_2_scipy]sklearn (Python 3.8.5) (pid: 1005848)
info 22:24:50.340: Creating server with url : https://hex.mit.edu:8000/user/carlau/
warn 22:24:50.424: Uri verification error [FetchError: request to https://hex.mit.edu:8000/user/carlau/api/kernels?1679970290352 failed, reason: unable to verify the first certificate
	at ClientRequest.<anonymous> (/home/carlau/.vscode-server/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:1101739)
	at ClientRequest.emit (node:events:526:28)
	at TLSSocket.socketErrorListener (node:_http_client:442:9)
	at TLSSocket.emit (node:events:526:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)]
error 22:24:50.429: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/home/carlau/.vscode-server/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:172349)
	at u.dispose (/home/carlau/.vscode-server/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:63778)
	at hg.dispose (/home/carlau/.vscode-server/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:17:269825)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 22:35:07.626: Uri verification error [h [FetchError]: request to https://hex.mit.edu:8000/hub/login?next= failed, reason: unable to verify the first certificate
	at ClientRequest.<anonymous> (/home/carlau/.vscode-server/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:1101739)
	at ClientRequest.emit (node:events:526:28)
	at TLSSocket.socketErrorListener (node:_http_client:442:9)
	at TLSSocket.emit (node:events:526:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)] {
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
This issue may be resolved in our latest version, please could you try this in the latest pre-release version
* Please install latest VS Code Insiders
* Open the extensions page, search for Jupyter and click the button `Switch to Pre-Release Version`
* Similarly please install the latest `Pre-Release` version of the Python extension

<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">

**Comment by groblercarla** [comment]
I downloaded the VS Code insiders (version info available below) and selected the pre-release jupyter (version v2023.3.1000851011) and python pre-release (v2023.5.10871005), restarted my computer and tried again. Still get the same error. 

<img width="447" alt="image" src="https://user-images.githubusercontent.com/64163669/228273265-d2fd433c-c54d-437d-92b3-cfa5032401d4.png">

VS Code insiders version info: 
Version: 1.77.0-insider (user setup)
Commit: b9226e1ccc11625bcb42b55efb795e07ee533bb0
Date: 2023-03-24T18:57:27.096Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by DonJayamanne** [comment]
Looks like the certificate used on the remote server isn't valid or not recognized.
Please try adding the following setting `jupyter.jupyter.allowUnauthorizedRemoteConnection: true` in your user settings file and try again.

Note: This is not advised, this is only recommended if you know full well what you are connecting to is a valid and secure server. This setting is there for users to by pass SSL certificate issues as seems to be the case you are running into.
Here is the error you are running into:
```
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```
Let me know if that works.

**Comment by groblercarla** [comment]
I've tried adding the setting - but not sure I'm doing it correctly - see image below. VSCode indicates "Unknown Configuration Setting" when I hover over the setting. What should I be doing differently?

<img width="416" alt="image" src="https://user-images.githubusercontent.com/64163669/228962647-dc464288-4aa7-41b0-a5f8-f6c5d909c38d.png">

**Comment by DonJayamanne** [comment]
Sorry, the setting should be `jupyter.allowUnauthorizedRemoteConnection: true`
Not `jupyter.jupyter`, line 9 is what you need with just one `jupyter`

**Comment by abhishekgrewal** [comment]
Facing same issue now, tried the suggested fixes already.

VS Code: V1.81.1
Jupyter: v2023.7.1002162226
