### ISSUE TITLE
can not select kernel in jupyter notebook when ssh to WSL

### ISSUE THREAD

**Issue by Shi-YuZhang** [microsoft/vscode-jupyter#13186]
版本: 1.77.0-insider (user setup)
提交: b9226e1ccc11625bcb42b55efb795e07ee533bb0
日期: 2023-03-24T18:57:27.096Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
沙盒化: Yes

Steps to Reproduce:

1.  SSH to WSL
2. open an .ipynb file
3. click the "select kernel"
4. can not display any option for long time
![image](https://user-images.githubusercontent.com/74309824/227898208-55f6a87f-03e8-4b82-9164-2efae8794843.png)

**Comment by DonJayamanne** [comment]
Sorry you are running into this issue, please could you share the following logs
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
