### ISSUE TITLE
`clear_output(wait=True)` does not work inside async call

### ISSUE THREAD

**Issue by slundberg** [microsoft/vscode-jupyter#13199]
## Environment data

-   VS Code version: 1.76.2
-   Jupyter Extension version (available under the Extensions sidebar): v2023.2.1200692131
-   Python Extension version (available under the Extensions sidebar): v2023.4.1
-   OS (Windows | Mac | Linux distro) and version: Mac 13.2.1 (22D68)
-   Python and/or Anaconda version: 3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

## Expected behaviour

`clear_output(wait=True)` clears the output even during an async call.

## Actual behaviour

`clear_output(wait=True)` does not clear the output.

## Steps to reproduce:

Run the following code in a cell, notice that the `clear_output(wait=True)` call does not have any effect (both print1 and print2 are displayed).

```python
import asyncio
from IPython.display import display_html, clear_output, display

display({"text/html": "<b>print1</b>"}, raw=True, clear=True, include=["text/html"])

def f():
    #clear_output(wait=False) # uncomment this and it works (but causes flickering)
    clear_output(wait=True)
    display({"text/html": "<b>print2</b>"}, raw=True, clear=True, include=["text/html"])
asyncio.get_event_loop().call_later(1, f)
```

Note that this does work as expected in a Jupyter notebook.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and sorry you ran into this.
Will fix this soon,
