### ISSUE TITLE
Show description of kernels on main list.

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode-jupyter#13195]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### kernel selcting:
![image](https://user-images.githubusercontent.com/26390254/228311031-d156adee-9844-4613-b28a-639b8c305cd0.png)

### kernel selcting -> python environments:
![image](https://user-images.githubusercontent.com/26390254/228310057-5ae1443b-f07e-49a1-8fd2-7dd4f717d933.png)

expexted to see python path in kernel selcting.

### VS Code Version

1.76

### Jupyter Extension Version

2023.2.1200692131

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment]
Thank you for filing this feature request, however given that we haven't received any upvotes on this since this was created I'm closing this for now.
