### ISSUE TITLE
Copy cell code and output together as plain text

### ISSUE THREAD

**Issue by stevenlis** [microsoft/vscode-jupyter#13207]
I often find that I have to copy code and output together to share with others, such as on SO or bug reporting.
It would be great if Jupyter extension could give me an option to copy the code in a cell as well as its output together, which would save me lots of time.

For example, this cell and output ....
<img width="444" alt="CS-D60eXSHE@2x" src="https://user-images.githubusercontent.com/33796896/228391509-f8e027c3-1e16-45f5-a0f3-b2a811215a53.png">

... could be formatted to plain text as this so that you could simply copy and paste to share with others.
```
>>> import pandas as pd

>>> df = pd.DataFrame(
>>>     {'a': [1, 2, 3], 'b': [4, 3, 2]}
>>> )
>>> df.describe().T

   count  mean  std  min  25%  50%  75%  max
a    3.0   2.0  1.0  1.0  1.5  2.0  2.5  3.0
b    3.0   3.0  1.0  2.0  2.5  3.0  3.5  4.0
```

Or even better: add "```python" automatically

**Comment by DonJayamanne** [comment]
Closing this issue as there haven't been enough upvotes on this.
