### ISSUE TITLE
Unnecessary prompt to trust HTTP for Jupyter server URIs provided by AML

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13220]
AML provides the URI
Even though its HTTP instead of HTTPS, this is provided by an extension, hence its upto the user to trust the extension.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/1948812/228938845-c0169f67-b8a9-4015-8161-77279e2297d1.png)

**Comment by amunger** [comment]
@DonJayamanne how do I get AML to provide a URI?
