### ISSUE TITLE
Add support for `File-> Revert File` feature in Custom Editor

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1323]
Currently this is't hook up.
Based on docs, we need to revert the Notebook to the originally saved state.

* Today we seem to be attempting to revert it to the last hot exit state
* We aren't modifying the existing model (we're loading a new model)

We'd need to modify the current model and re-send all the cells back up to the UI
Note sure how this impacts undo/redo.
Also not sure how widely this is used.

**Comment by greazer** [comment]
Thanks for your feedback. This issue will likely be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987.
