### ISSUE TITLE
Cell debugger needs "break at exception or warning"

### ISSUE THREAD

**Issue by notuntoward** [microsoft/vscode-jupyter#13246]
## Environment data

-   VS Code version: 1.76.2
-   Jupyter Extension version (available under the Extensions sidebar): Jupyter  v2023.2.1200692131 
-   Python Extension version (available under the Extensions sidebar): Python  v2023.4.1 
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | N/A

## The problem

Most debuggers have settings that will bring you to the line of code where a warning or exception was triggered.  Data science workflows would be greatly improved if VSCODE Jupyter also did this.

In the screenshot, I have just run "Debug Cell" from the left hand dropdown cell menu, and an error message tells me that line 25 of the cell has caused a type error.

But it's not obvious why this is a type error.  To see that, the debugger should have -- like it would have in other debuggers -- opened the source file where the type exception was raised, and put the cursor on the line that did the raise.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/3851891/229313356-3e1342de-5ac6-48a6-818e-8e3ad521d880.png">

**Comment by roblourens** [comment]
You can enable this with the options in the breakpoints view

<img width="299" alt="image" src="https://user-images.githubusercontent.com/323878/232938988-e95e29c4-ae52-4a5b-a550-64a6c53002fa.png">
