### ISSUE TITLE
Redo in in custom editor inserts cells in the reverse order

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1325]
* Add 4 cells with numbers 1,2,3,4 respectively.
* Execute cells (not sure this is required)
* Go to last cell and undo
* Yay it works (only one cell left)
* Redo and now we have cells in the reverse order 4,3,2,1

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
