### ISSUE TITLE
Provide API to open a notebook and preselect a specific kernel

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13251]

**Comment by DonJayamanne** [comment]
How to use the new API:
* Use the existing API `getKernelService().getKernelSpecifications()` to get a list of all kernel connections
    * Sometimes they might not be immediately available, hence handle the event `onDidChangeKernelSpecifications`
* Identify the kernel connection you are interested in, and get the `id` of that
* Identify the `Uri` of the notebook that needs to be opened with a specific kernel
* Use the new API method `openNotebook(uri: Uri, kernelId: string): Promise<NotebookDocument>` to open the notebook with the specific kernel. 
    * Where `Uri` and `kernelId` was identified earlier

How to test:
* This API is already used in an extension today, used in Jupyter PowerToys extension today
* Install Jupyter Power toys extension
* Go into Jupyter activity bar
* Expand the `Kernel Specifications/Active Jupyter Sessions` tree item
* Select an kernel under a lanaguage
* When hovering over you can see `Open Jupyter Notebook`, click one of them, and verify the notebook is opened with the specific kernel

**Comment by jruales** [comment]
@DonJayamanne we would like to use the new API to create a new notebook with a specific kernel, not to open an existing notebook

The current api has two signatures, one to open a URI and one to create a new notebook:
![image](https://user-images.githubusercontent.com/1588988/230004592-f82fbe0e-c6b3-41d5-a322-7a9f09c77067.png)

Does the second signature now have a third argument that allows creating a new notebook with a specified kernel?

**Comment by DonJayamanne** [comment]
You can use the second api (above) and then subsequently can the api in Jupyter extension passing in the Uri of the notebook document

**Comment by DonJayamanne** [comment]
Marking as verified by @jruales @sevillal
