### ISSUE TITLE
Notebook communication between JavaScript and Python

### ISSUE THREAD

**Issue by Conchylicultor** [microsoft/vscode-jupyter#13255]
With Colab/Jupyter, it is possible to have bidirectional communication between Python/Javascript, without installing a notebook extention:

* In Jupyter, it is possible to execute arbitrary Python code from JS:

  ```javascript
  IPython.notebook.kernel.execute('x = 2');
  ```

* In Colab, for security reason, it is forbidden. However, it is still possible to call explicitly registered Python functions with input/outputs serialised to `Json`.

  ```python
  import IPython.display
  from google.colab import output

  def my_func():
    print('called')

  output.register_callback('my_func', my_func)


  IPython.display.Javascript("""
  google.colab.kernel.invokeFunction('my_func', [], {});  // fn_name, args, kwargs
  """)
  ```

It is very convenient, and unlock powerful use-cases. For example:

* `pandas.DataFrame` in Colab can be viewed interactively (with filters, pages,...).
* [`ecolab.inspect(obj)`](https://github.com/google/etils/blob/main/etils/ecolab/README.md#inspect-any-python-objects) to interactivelly inspect arbitrary Python objects: https://www.youtube.com/watch?v=MFbb5wZlYvE

There's an duplicate issue which was closed (https://github.com/microsoft/vscode-jupyter/issues/6918), even though the original issue (https://github.com/microsoft/vscode-jupyter/issues/7551) hasn't been fixed.

* If this is possible, it would be great to have an example on how to do this.
* If not, it would be great if VSCode was exposing an API `VSCode.kernel.invokeFunction` similar to Colab.

**Comment by DonJayamanne** [comment]
Closing this issue, as the package https://github.com/manzt/anywidget
now makes it very easy for front end code to communicate with the kernels using ipywidgets.

Though jupyter ntoeb9ook exposes a way to communicate with the kernel, jupyter lab no longer supports this.
I believe using IPyWidgets is the right way (as thats what Jupyter lab also recomends)
