### ISSUE TITLE
Make use of VS Code custom editor support

### ISSUE THREAD

**Issue by wamartin-aml** [microsoft/vscode-jupyter#1326]
# Bug: Notebook Editor, Interactive Window, Python Editor cells

## Steps to cause the bug to occur
1. Open .ipynb file with this extension enabled.
2. Press ctrl + F to search the file.

## Actual & Expected behavior

Expected: search window pops up, able to type in strings to find them in the document
Actual: No search window

### Your Jupyter and/or Python environment
*Please provide as much info as you readily know*
- **Jupyter server running:**                       Local (I think? I didn't start anything, but there is a kernel running)
- **Extension version:**                               2019.10.41019-xxx
- **VS Code version:**                                1.38.1
- **Setting python.jediEnabled:**               true
- **Python and/or Anaconda version:**     3.6.7
- **OS:**                                                     Linux (Ubuntu through WSL):
- **Virtual environment:**                          conda

## Developer Tools Console Output

None

**Comment by greazer** [comment]
Experiment for a subset of customers has been activated. If all is looking good, we will raise the percentage and continue to monitor.

**Comment by pckhoi** [comment]
How is the progress of this so far? Just lost an entire morning worth of work because autosave doesn't work.

**Comment by rchiodo** [comment]
@pckhoi you can enable it yourself if you like. Put this in your user settings.json

```json
"jupyter.experiments.optInto": [
        "CustomEditor"
    ],
```

**Comment by pckhoi** [comment]
That doesn't seem to solve my issue which is that the notebook doesn't autosave when I Cmd+Tab to another application. Should I open a new issue?

**Comment by rchiodo** [comment]
@pckhoi is it just the focus switch that doesn't work or does autosave on a timer work?

**Comment by pckhoi** [comment]
Autosave after delay seems to work.

**Comment by rchiodo** [comment]
@pckhoi can you open a separate issue then? This issue is about custom editor support, the auto save stuff was independent of that.
