### ISSUE TITLE
Don't paste anything in Jupyter server input field

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-jupyter#13285]
Related to https://github.com/microsoft/vscode-jupyter/issues/13144

It's great Jupyter no longer pastes a bogus URL in the server input field. But I was surprised it automatically pastes anything that's on my clipboard, which in this case happened to be a GitHub issue:
![image](https://user-images.githubusercontent.com/25310137/230458894-e2aab32c-d091-4996-ae31-687276b3b697.png)

Could we instead leave the input blank, leaving it to users to paste in a URL?

**Comment by DonJayamanne** [comment]
We no longer automatically paste a URL from clipboard into the inputbox in vsocde.dev.
However in desktop, this behaviour still exists.
