### ISSUE TITLE
Use actual `python.envFile` configuration for env file

### ISSUE THREAD

**Issue by micimize** [microsoft/vscode-jupyter#13294]
#10876 doesn't seem to add actual support for the `python.envFile` configuration option, only the default `${workspaceFolder}/.env` 

https://github.com/microsoft/vscode-jupyter/blob/cdc9c72db3ea7f56185b14d873364f5b26f7ecd9/src/platform/common/variables/customEnvironmentVariablesProvider.node.ts#L162-L164

**Comment by DonJayamanne** [comment]
Thanks, however if you look here, we are using the Python exctension API to get the env file,
```typescript
    public async getCustomEnvironmentVariables(

....
        if (purpose === 'RunPythonCode' && this.extensionChecker.isPythonExtensionInstalled) {
            const api = await this.pythonApi.getNewApi();
... 
                return api.environments.getEnvironmentVariables(workspaceFolderUri);
            }
        }

// fallback or non-python
        const envFile = this.getEnvFile(workspaceFolderUri);
        this.createFileWatcher(envFile, workspaceFolderUri);


```

**Comment by DonJayamanne** [comment]
If you have a specific issue that can be replicated or applies to Python and its not working as excpected, then please file an issue with the details (versions of extensions, logs and the like requested in the issue template) and we'll look into that.
