### ISSUE TITLE
Scroll-bar in zen-mode

### ISSUE THREAD

**Issue by bdch1234** [microsoft/vscode-jupyter#13292]
Would it be possible to have the scroll-bar to the far right of the window when in zen-mode? It would simplify scrolling the notebook, especially now that it is possible to have outputs scrollable as well.

**Comment by isidorn** [comment]
Zen mode does not hide the scroll bar. What exactly do you mean? Can you provide a gif / image showing the problem?

**Comment by bdch1234** [comment]
The scroll-bar location is currently at the right edge of cells:

<img width="462" alt="Screenshot 2023-04-18 at 11 44 55" src="https://user-images.githubusercontent.com/46796385/232740011-8dccba58-beec-4d9d-9faf-a0c16190ec46.png">

This means that mouse must be over a cell to be able to use mouse wheel or pad to scroll. If the bar instead would be to the far right of the window, like it is for classic Jupyter:

![screen2](https://user-images.githubusercontent.com/46796385/232741990-68338e55-fe51-4ffa-8699-4a9a483e6a58.jpeg)

Then that would enable having mouse on the sides when scrolling. This would be especially useful now that outputs can be made scrollable, since having mouse on the sides means scrolling does not accidentally stop to scroll an output. In addition, the possible "scrolling-area" when over a large output is increased from the width of the notebook scrollbar to the width from cell edge to the screen edge.

**Comment by isidorn** [comment]
How is this related to zen mode?

**Comment by bdch1234** [comment]
We only have the empty area to the sides of the cells when in zen-mode. When in normal mode the cells extend to the edge of the window, making this irrelevant.

**Comment by isidorn** [comment]
Thanks. So this is a feature request that for Centered Mode the Native Notebook would support scrolling when also in the right of the centered area.

fyi @rebornix

**Comment by bdch1234** [comment]
Yes exactly, thanks @isidorn. But if possible, it would be good to enable for both sides, not just the right.
