### ISSUE TITLE
Internal links in Jupyter Notebook doesn't work

### ISSUE THREAD

**Issue by FreezeHands** [microsoft/vscode-jupyter#1330]
When i try to create an internal link in the jupyter notebook it doesn't work.
i used this code:
```
[reference](#reference)

some stuff
## Reference
```
In any way it doesn't link me to that part of the notebook

**Comment by AndrewLaganaro** [comment]
internal links still not working on VS code insiders.

**Comment by nickmayn** [comment]
Still an issue would love to see this fixed!

**Comment by Virajdatt** [comment]
Hoping to see this feature added soon :).

**Comment by Sinha123456** [comment]
Is anyone can help me for internal link in google colab notebook, I tried above options but didn't worked as well.

**Comment by Virajdatt** [comment]
> Is anyone can help me for internal link in google colab notebook, I tried above options but didn't worked as well.

One cell 
<a id="my-unique-id"> </id>

The cell where u want to use above just include

[link_to_other_cell](#my-unique-id)

**Comment by nickmayn** [comment]
@Sinha123456  nothing we can do at the moment currently. You can try to do your development in the Jupyter interface from the forwarded port potentially? The internal hyperlinks would work there. To access it just look at the port forwarding section in vs code find the number of the port and go to localhost:(the port number). Then give it the token which you can get from:

```
 jupyter notebook list
```

Hopefully this functionality gets added soon!

**Comment by Sinha123456** [comment]
Thanks for answering my question. Internal link is properly working in
jupyter notebook but not in the google colab, hopefully, we can get
internal link in google colab soon.
Thanks again!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jsdodge** [comment]
Does this bug also break file links, as described on [StackExchange](https://stackoverflow.com/questions/66792149/how-do-i-set-vs-code-to-follow-markdown-file-and-section-links-in-a-jupyter-note)? With the two Markdown cells below, only the web link works for me from VS Code.
```
# First Markdown Cell
* [Notebook](test-index.ipynb)
* [Markdown](test.md)
* [Text](test.txt)
* [Cell](#Second-Markdown-Cell)
* [Web](https://stackoverflow.com)
```
```
## Second Markdown Cell
```

**Comment by Sinha123456** [comment]
No, bug didn't break my file links. I used a reference link in my jupyter
notebook. Here is the code what I used in the markdown cell.
<ul>
<li><a href="intro">Introduction</li></a>
</ul>

and top of the heading
<a id="intro"></a>
## Introduction

[linktext](link) are good for external links I guess, I haven't tried that
one for internal links.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jsdodge** [comment]
Here is an updated version of the issue, including the HTML anchor mentioned by @Sinha123456 , which does not work as expected for me. The following three Markdown cells all work as expected with the standard Jupyter notebook server. In VS Code (1.54.3, Darwin x64 19.6.0), only the web link functions as expected and the "HTML anchor in HTML" is not even rendered as a link.

The performance is better in VS Code Insiders (1.55.0) with the Python extension (v2021.4.690665134-dev), but still not the same as the standard notebook server. The file links work, but the Markdown section anchor "HTML anchor" tries to open the nonexistent file `<HOME>/#intro` in another window, and the "HTML anchor in HTML" is not rendered on the screen at all, not even as plain text.

```
# First Markdown Cell
* [Notebook](test.ipynb)
* [Markdown](test.md)
* [Text](test.txt)
* [Cell](#Second-Markdown-Cell)
* [HTML anchor](#intro)
* [Web](https://stackoverflow.com)

<ul>
<li><a href="#intro">HTML anchor in HTML</a></li>
</ul>
```
```
## Second Markdown Cell
```
```
<a id="intro"></a>
## Introduction
```

VS Code:
<img width="333" alt="Screen Shot 2021-03-27 at 11 28 09 AM" src="https://user-images.githubusercontent.com/4602669/112730563-88e57880-8eef-11eb-8520-29251093c718.png">

VS Code Insiders:
<img width="565" alt="Screen Shot 2021-03-27 at 11 39 00 AM" src="https://user-images.githubusercontent.com/4602669/112730839-0958a900-8ef1-11eb-8973-4386407b9d0a.png">

**Comment by joyceerhl** [comment]
VS Code is tracking adding internal notebook links to the new native notebooks interface in this issue: https://github.com/microsoft/vscode/issues/103519

**Comment by martinlietz** [comment]
I stumbled over this now and saw that this almost is making his first birthday next month :-) 
Any idea/ETA when this is fixed?

**Comment by Sinha123456** [comment]
Hello Martin,
I do not have any idea about this. I hope you find some solution soon.

**Comment by joyceerhl** [comment]
This is now supported in https://github.com/microsoft/vscode/issues/103519
