### ISSUE TITLE
A much better cell output presentation

### ISSUE THREAD

**Issue by patchie** [microsoft/vscode-jupyter#13308]
There is several cell output presentations, and they all suck unfortunately. Some suck more than others.

1. There is some times where you have to use one over the other, but it will change the presentation globally, so you need to change back and forth. Why not just make one presentation that works in all situations?
2. When i am running a code that changes the output, i cannot scroll up in the output to read, i then have to wait...
3. You should be able to resize the output window if you need, without changing presentation.
4. It would be nice if you could show the output in another view/window
5. If you could view the last 5 outputs from a cell, that would also make a lot of sense. So you can go back and see the difference.
6. When you do .head() on a pandas dataframe, it should show the data as it does when you use "data viewer", but with a few more bare minimum excel features, like filtering on numbers between two given numbers for example.

**@all:** Please add comments with your suggestions and problems with the current cell output presentations.

**Comment by roblourens** [comment]
> There is some times where you have to use one over the other, but it will change the presentation globally, so you need to change back and forth. Why not just make one presentation that works in all situations?

Can you be more specific? I don't know what you're referring to

> When i am running a code that changes the output, i cannot scroll up in the output to read, i then have to wait...

Can you give an example? I'm not sure in which scenario this doesn't work.

> If you could view the last 5 outputs from a cell, that would also make a lot of sense. So you can go back and see the difference.

I disagree- I think the best thing to do here is to duplicate the cell, that way your code change is captured along with the changed output.

> When you do .head() on a pandas dataframe, it should show the data as it does when you use "data viewer", but with a few more bare minimum excel features, like filtering on numbers between two given numbers for example.

I think that the data viewer is for this scenario :) a custom output renderer could help here, but I don't think that we plan to provide that kind of functionality built-in.

Point 4 is here: https://github.com/microsoft/vscode-jupyter/issues/1120

> You should be able to resize the output window if you need, without changing presentation.

You want to resize the output independently of the notebook window, is that it?

**Comment by patchie** [comment]
1. Sometimes you need to change the presentation to view the output content in the best way. I dont have any good examples right now unfortunately. But in the future, i would imagine that you would never need to change presentation of the output.

2. A good example of this is when you're training a model, then it updates the progressbar/output text every 0.5 seconds or similar, and every time it will scroll down to the bottom. An example in below screenshot:
![image](https://user-images.githubusercontent.com/1792727/231567437-b6515ea2-ceeb-469b-bb10-88a8d09b45e7.png)
Either you should be able to scroll even though its updating, or you should have a button to expand the "output field", or be able to open output in a separate tab.

3. I just want to see the whole output at the same time. when i use presentation "VS Code Builtin Notebook Output Renderer", it makes a fixed box for the output. I want to be able to click a button at the top to "Expand(change height to 100% of output height)/collapse(default as it is now)". Button should maybe be at the top of the output, but maybe also on bottom if its expanded so you dont need to scroll all the way up to collapse it.

5. That is true if you change the code. But i didn't change the code, i changed the dataset which is a separate file. And those times it would make sense to see if the training was better in a earlier run. Now i have to store the output in a separate .txt file. I have now been running the same code 35 times in a row, and would be nice to go back and see which was performing better.

6. Google colab has a magic wand you can press when you have run .head() on a datatable, and it changes to what they refer to as "data table". You can now for example sort and filter on the data. see more info here: https://www.youtube.com/watch?v=YfLD9bBDdc8 
This would be a huge improvement.

Tell me if you need more info, happy to help.

**Comment by DonJayamanne** [comment]
> JupyterLab has an extension called qgrid that is similar.

As far as I know  you can use this same widget in vscode as well,

**Comment by patchie** [comment]
> As far as I know you can use this same widget in vscode as well,

How? cannot find any extensions called qgrid. Link to a tutorial or something?

**Comment by DonJayamanne** [comment]
> How? cannot find any extensions called qgrid. Link to a tutorial or something?

If you follow the instructions here, https://github.com/quantopian/qgrid
that should be sufficient
I just tested this and doesn't seem to work, looks like this is no longer maintained, we have had users of the Jupyter extension in VS Code use this in the past.

**Comment by marctorsoc** [comment]
FWIW, `conda install -c eshard qgrid` with ipywidgets 8.0.6, worked for me on VScode

**Comment by amunger** [comment]
on the dataviewer feature in point 6, you might like the DataWrangler extension - it does just that.

resizing outputs is covered in https://github.com/microsoft/vscode/issues/174917

for scrolling issues, you could try adjusting the `notebook.scrolling.revealNextCellOnExecute` setting.

Thanks for all the feedback, I'm going to close this issue down just to clean up, but feel free to open a new issue for specific pain points to be able to track them.
