### ISSUE TITLE
Error opening ipynb files on macOS 10.13.6

### ISSUE THREAD

**Issue by david-roper** [microsoft/vscode-jupyter#13312]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Open or create ipynb file
Attempt to select python interpreter
VScode becomes unable to open ipynb file after an interpreter is selected

### VS Code Version

1.77.2

### Jupyter Extension Version

v2023.2.1200692131

### Coding Language and Runtime Version

Python 3.9.9

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and sorry you are running into this.
Sorry, but please could you explain what you mean by `unable to open ipynb file`
* Perhaps a screenshot of the issue would help, 
* Does VS Code freeze, do you get any error messages

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
