### ISSUE TITLE
Inline TensorBoard in a Jupyter notebook need to add port manually

### ISSUE THREAD

**Issue by ahyang98** [microsoft/vscode-jupyter#13328]
hi
when i use tensorboard in vscode notebook， i have to add port manually，otherwise it will not be shown.
it is inconvenient
![image](https://user-images.githubusercontent.com/45085520/232000235-56da6011-9f7e-4cfc-bddb-97f2ae9153f7.png)

**Comment by amunger** [comment]
duplicate https://github.com/microsoft/vscode-jupyter/issues/13324
