### ISSUE TITLE
Enable users to define their own default path when saving plots with "save as" from the interactive shell.

### ISSUE THREAD

**Issue by bbantal** [microsoft/vscode-jupyter#13321]
When I generate a figure with `matplotlib` and try to save it using that little "Save As" icon, it opens up a finder window and the default path is my system's root directory "/". Every time I want to save a figure I have to click through my file system to arrive at the desired filepath (which would be Desktop). I'm on macOS. It would be great if I could specify my own default path or if it would at least remember the path I used last time.

Relevant SO post with a useful answer: https://stackoverflow.com/q/76000138/11411944

**Comment by starball5** [comment]
With [VS Code 1.80's new `files.dialog.defaultPath` setting](https://code.visualstudio.com/updates/v1_80#_default-file-dialog-location), is this now configurable on the user end of things?

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, as there aren't enough upvotes and `files.dialog.defaultpath` setting might be a suitable work around, hence closing this issue for now
