### ISSUE TITLE
Jupyter automatically runs markdown cells when you click to another program. This makes copying from another source more time consuming than necessary.

### ISSUE THREAD

**Issue by hannibal90** [microsoft/vscode-jupyter#1332]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Run Jupyter kernel in VS Code
2. Type a paragraph in a Markdown cell
3. Select a different program, copy some text, and come back to VS Code

## Actual behavior

The markdown cells run automatically, without being told to run.

## Expected behavior

All cells should only run when they are told to. This behaviour slows down coding and creates unnecessary extra steps. 

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Remote
-   **Extension version:** 2020.08.105045
-   **VS Code version: 1.48.2
-   **Setting python.jediEnabled:** true
-   **Setting python.languageServer:** PyLance
-   **Python and/or Anaconda version: 3.8
-   **OS:** Windows | Mac | Linux (distro): Ubuntu 20.04
-   **Virtual environment:** conda

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by joyceerhl** [comment]
Fixed in native notebooks.
