### ISSUE TITLE
Select kernel per code cell

### ISSUE THREAD

**Issue by l-johnston** [microsoft/vscode-jupyter#13325]
We would like to select the kernel on a per code cell basis rather than one kernel for the notebook.

**Comment by DonJayamanne** [comment]
@l-johnston 
Thanks for filing this issue, unfortunately thats not something we plan on adding 

Jupyter Notebook/Jupyter Lab do not support per cell kernels, and this extension tries to provide the same functionality that Jupyter Notebook/Lab provides.
You could instead try to look at using cell magics that allow you to run cells with different kernels.
