### ISSUE TITLE
VPN prevents any extensions to run

### ISSUE THREAD

**Issue by shefinvex** [microsoft/vscode-jupyter#13340]
Type: <b>Bug</b>

When I connect my vpn, the python interpreters are not shown in the interpreter list. the python extension seems like to crash.

Extension version: 2023.4.1
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by shefinvex** [comment]
Well I actually tested again today and it worked with no problem. But I'm doing some more tests to ensure that the problem is not comming up again. The VPN name is "VPN Unlimited" by "KeepSolid".
So I'd like to keep the issue open until I come up with the conclusion that the problem is vanished permanently.

**Comment by DonJayamanne** [comment]
Its been 2 weeks, lets close this, we can always re-open or create a new issue
