### ISSUE TITLE
Jupyter notebook extension corrupted

### ISSUE THREAD

**Issue by CoffeeCecil** [microsoft/vscode-jupyter#13344]
I uninstalled jupyter notebooks because it was not interacting with the kernel correctly.

Note - I have anaconda3 installed. That was the extension's fault. I can start jupyter in my browser and it worked just fine. It ran infinitely - or for more than 60 seconds which is close enough on a local machine, frankly.

Right. Smaller problem. Big problem. I uninstalled Jupyter. And reinstalled Jupyter to see if that would do much to help. And uh, now I can't create notebooks. At all. The setting doesn't exist anymore. It shows the underlying JSON of the notebook when opened. Reinstalling the extension does nothing.

Other symptoms of this issue: running an interactive window produces the following error:

"The editor could not be opened due to an unexpected error: UNKNOWN notebook type 'interactive'"

Logging shows nothing indicating an extension failure:

```
Visual Studio Code (1.77.3, undefined, desktop)
Jupyter Extension Version: 2023.3.1201040234.
Python Extension Version: 2023.6.1.
Workspace folder c:\Users\admin\AppData\Roaming\Factorio\mods\general-testing
User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'jupyterTest'
info 21:53:29.284: LSP Notebooks experiment is enabled
warn 21:53:30.108: Failed to get activated env vars for d:\tango\scoop\apps\python\current\python.exe in 578ms
info 21:53:30.121: Process Execution: > d:\tango\scoop\apps\python\current\python.exe -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
> d:\tango\scoop\apps\python\current\python.exe -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
info 21:53:30.230: Process Execution: > d:\tango\scoop\apps\python\current\python.exe -m pip list
> d:\tango\scoop\apps\python\current\python.exe -m pip list
info 21:53:37.749: Starting interactive window for resource '' with controller '.jvsc74a57bd010218cfcb948c60146421182469e243cbcb6fe2a6fbb9cd42c00c8e7c79225b6.d:\tango\scoop\apps\python\current\python.exe.d:\tango\scoop\apps\python\current\python.exe.-m#ipykernel_launcher (Interactive)'
info 21:58:56.705: Process Execution: > d:\tango\scoop\apps\anaconda3\current\python.exe -m pip list
> d:\tango\scoop\apps\anaconda3\current\python.exe -m pip list
info 21:59:06.967: Starting interactive window for resource '' with controller '.jvsc74a57bd0485f3aa15c5c44eac83971d5e45f5f47fc35f40cfcb344183b12d5cdb818d1b7.d:\tango\scoop\apps\anaconda3\current\python.exe.d:\tango\scoop\apps\anaconda3\current\python.exe.-m#ipykernel_launcher (Interactive)'
```

Attempted to uninstall and reinstall code. *This did not resolve the issue*.

**Comment by rebornix** [comment]
@CoffeeCecil may I ask what version of VS Code and Jupyter extension are you using? There are multiple issues mentioned in this issue, including notebook document can't be opened/created, and also "not interacting with the kernel correctly". We want to make sure that your set up is up to date and troubleshoot together.

**Comment by CoffeeCecil** [comment]
Figured it out, you just need to delete the user preferences cached in app-data as well as reinstall the program.
