### ISSUE TITLE
jupyter takes very long time to start kernel for remote with no public internet access

### ISSUE THREAD

**Issue by qianyizhang** [microsoft/vscode-jupyter#13350]
## Environment data

-   VS Code version: 1.77.3 
-   Jupyter Extension version (available under the Extensions sidebar): v2023.3.1201040234
-   Python Extension version (available under the Extensions sidebar): v2023.6.1
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.22621
-   Python and/or Anaconda version: 3.8.13
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote (with no public internet access)

## Expected behaviour

starts jupyter kernal instantly once connected to server

## Actual behaviour

the first time starting kernel (after connect to server) takes about 5-10min .
behavior very similar to that of https://github.com/microsoft/vscode-jupyter/issues/11856

## Steps to reproduce:

1. mannuly install vscode server (by downloading tar, scp to server and extract remotely)
2. connects to server via remote ssh
3. opens .ipynb

## Logs

<details>

<summary>
partial logs
</summary>

<p>

```
debug 20:18:44.972: End cell 2 execution @ undefined, startedd @ undefined, elapsed time = 0s
debug 20:18:44.973: VSCodeNotebookController:: handleExecutionn, Class name = db, completed in 258025ms, has a falsy returnvalue
debug 20:18:52.206: interpreterPackages getPackageInformation, Classname = Kd, completed in 270594ms, has a falsy return value, Arg 1: {"iinterpreter":{"id":"/root/miniconda3/envs/py38/bin/python", "sysPrefix":"/root/miniconda3/envs/py38","envPath": {"$mid":1,"fsPath":"/root/mini"Lconda3/envs/py38","path":"
root/miniconda3/envs/py38","scheme":"file"},"displayPath": {"Ssmid":1,"fsPath":"/root/miniconda3/envs/py38","path":"/root/miniconda3/envs/py38","scheme":"file"},"envName":"py38","displayName":"py38","envType": "Conda","isCondaEnvWithoutPython":faalse,"version":{"major":3,"minor":8,"patch":13,"raw":"3.8.13
(default, Mar 28 2022, 11:38:47) \n[GCC 7.5.0]"},"uri":{"$mid":1,"fsPath":"/root/miniconda3/envs/py38/bin/python",""externaal":"file:///root/miniconda3/envs/py38/bin/python","path":"/root/miniconda3/envs/py38/bin/python","scheme":"file"}}}
everything 20:18:52.207: Telemetry Event : DATASCIENCE.NOTEBOOOK_START Measures: undefined Props: {"resourceType":"notebook","resourceHash": "0021d26b8d26c8d23b1270eb07fbf97eb1b891c191cc30c2cda21db29a77898a","kernelSessionId":"da8c39675929ba2e7eeb3e8ab33ee3606a473311dae54fbfdd7b8dd59e3c93a7b",
"capturedEnvVars": true","userExecutedCell": true","disableUII":"false","kernelLanguage": "python", "kernelid":"d0d9a5057d8e769fc009e0400782c928697a4249d0008b66247acb367d410ba7", "kernelSpechash": "0029fe20e8466d1816efe0a9d80c727877a2d0e7bcea6fe186c2a48b870537cb","pythonEnvironmentType": "Conda",
"pythonEnvironmentPath":"8004ef2893cd8ba7bcbe56b84cb0d06ac01e074b775ed352f293a083b0ffbcee","pythonEnvironmentVersion":"3.83.13","kernelConnectionType":"startusingPythonInterpreter", "pythonEnvironmentPackages": "{\'10179407bb8db6eccacc6da9ca62c2blbbb03bceec4db91e8a021d473e26a5d6c\':\'6.16.0\'
\'89e1278be8b894a35e73eaa5c2afd0f745961fd702a4704b2d9c4f1e825F3671\':\'0.2.0\',\'9916a5fb8a8d51c14412e88aed988e4404cd55f7b96Sa71c51d539b3cc15ca1eb97\' :\'NOT INSTALLED\',\'897912f1d7a38112511452e440bf4c54ef8e57a665e40648e89207d6628a2fd8\':\'NOT INSTALLED\'
\'3ce399db4dc985069ce539ac0a6cb94e8dd3d49f36dd0b7477088e013589991251\':\'4.11.1\',\''''''''''''''''[4.11.11.1](http://4.11.11.1/)\'\'d927Ca7348e57348e57348e5rrdb0af3535e1070009a91978\';\'7.7.2\'''d3e7ab21472587eb5ec6e05d0463e93a0b01F604b20c3def0e395b82a268fde5\':\'7.2.3\'',
\'94e6eda30eae43351771fb7e325569f30a9795fd919105b9710e95fdc94e0d66\':\'5.7.0\'', \'b53bcr919f24746d72094b8b86c0325cr40723d3d63240705db51a27b2261bc96\':\'6.5.2\', \'d60b76184370a4ed8fd706458d5bbr85163ar824d90732dd0f2e0c0897cd1c68\':\'24.0.1\',
\'904075f7a02bc2bda9f4d0cb02f379d7f97c1c0470a4d646ddb5e2ff60e10793\':\'NOT INSTALLED\'\'83716a35515f728928d7ce0aaa73e3445679d939169124b88fec90b522c45179\':\'6.2\'',\''840eb2c1c4b044921f16d4affecb7e8d16837e3aaa81f0df570a65851411acb60\':\'5.5.0\'}","isInsiderExtension":"false",
"ispythonExtensioninstalled": true","rawKernelSupported": "true", "VSCoode.ABExp.Features": ","abexp.assignmentcontext":"","isamlcompute":"false"
everything 20:18:52.207: Telemetry Event : DS_INTERNAL.GET_AOCTIVATED_ENV_VARIABLES Measures: {"duration":1} Props: {"enviype": "Conda","source":"python","failed":"false","reason": emptyVariables","isInsiderExtension": false","isPythonExtensionlInstalled": "true","rawKernelSupported": "true","VSCode.ABExp.
Features":"","abexp.assignmentcontext":"","","isamlcompoute":"false"


```
![3b5aa81f-0c8f-4d4b-8afd-87800e4f77f6](https://user-images.githubusercontent.com/12500132/232936451-07c6e1d1-c5d4-4f6d-b5da-f34bb04a10ea.jpeg)
</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, however the steps to repro are very vague and not sufficient.
Are you connecting to a remote jupyter server, it does not look like you are
Also not sure what you mean by `with no public internet`, does having internet access make this fater? Asking because I'm not entirely sure why that was mentioned, possible it has some importance that I'm not seeing.

> very long time to start kernel 

Can you give me an idea of how long this is, 10  minutes, 5 minutes, 1 minute

> partial logs

Based on the logs, I do not see any delay.
Please could you enable logging as follows and share the full logs (instead of a screenshot, you can just copy all of the text and paste here)
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by qianyizhang** [comment]
because the company server updates firewall to restrict ANY internet access from outside of the company.
And the kernel starts up pretty fast before that.

This is another portion of log that shows unreasonable amount of loading time, perhaps this is due to ipywdigets request? 
![image](https://user-images.githubusercontent.com/12500132/232944455-241d294e-f369-4d14-813f-8eea9f7d354f.png)

**Comment by qianyizhang** [comment]
sorry, took me a while to finnaly get the log out of server
[jupyter.log](https://github.com/microsoft/vscode-jupyter/files/11267876/jupyter.log)

**Comment by DonJayamanne** [comment]
> Workspace not trusted

Looks like your workspace is not trusted, please could you ensure the workspace is trusted,
Then reload vscode and try running the cell once again.

> he first log intends to highlight the 2 falsy return along some args:

Hmm, i can see that delay, looks like the Python extension is slow here
based on this the Python extension is slowing a few things down`warn 09:39:30.372: Failed to get activated env vars for /bin/python3 in 132391ms`

**Please could you try the following**
* Please could you enable `debug` logging for the Python extension as well
* Please re-loading vscode andtry  running this same process again and let me know if there's any improvement
* Please share the logs for both Python and Jupyter

**Comment by qianyizhang** [comment]
thanks for the timely response.
However I didn't find the python logging debug option, other than
```
"python.analysis.logLevel": "Trace"
```
Also, after connected to server with vscode remote, I waited awhile for loading extensions (which indeed takes awhile).
Then I opened a notebook, it still takes about ~ 2min for connecting to the jupyter kernel.

so my questions are:
1. is there any way to accelerate the extension loading process
2. is there any way to accelerate the kernel connection process

below are the logs, hope it helps:
[extension_host.log](https://github.com/microsoft/vscode-jupyter/files/11269207/extension_host.log)
[extension_host_remote.log](https://github.com/microsoft/vscode-jupyter/files/11269220/extension_host_remote.log)
[jupyter2.log](https://github.com/microsoft/vscode-jupyter/files/11269224/jupyter2.log)
[python.log](https://github.com/microsoft/vscode-jupyter/files/11269225/python.log)

**Comment by DonJayamanne** [comment]
@qianyizhang 

Thanks for the logs, not sure where you see 2m to start a kernel.
Based on the logs its much quicker than that

```shell
info 12:46:42.565: ZMQ loaded via fallback mechanism.
...
debug 12:46:46.904: VSCodeNotebookController::handleExecution, Class name = db (started execution)
...
debug 12:47:07.553: Cell 1 executed with state Success
```

As you can see above:
* You have loaded vs code and the extension starts to load at `12:46:46` thats the very first log entry
* Note, even though the log entry exists, the extension is still busy loading (this does not mean it has completed)
* You run a cell 4 seconds later at `12:46:46`
* The output is displayed at `12:47:07`

So from start to finish, loading the extensxion to getting an output of the cell takes less than 30s

> based on this the Python extension is slowing a few things downwarn 09:39:30.372: Failed to get activated env vars for /bin/python3 in 132391ms

please note, these executions are all asynchronous and not necessarily part of the flow that slows down execution.

> Also, after connected to server with vscode remote, I waited awhile for loading extensions (which indeed takes awhile).
> Then I opened a notebook, it still takes about ~ 2min for connecting to the jupyter kernel.

Which step is slow, connecting to vscode remote and waiting for extensions to load?
Based on the logs, loading the jupyter extension and running the cell is <30s

**Comment by qianyizhang** [comment]
I agree, it seems loading extension is the main casue.
However, launching kernel still takes some time, any idea on acclerating this?

> debug 12:47:06.517: Launching kernel in kernelProcess.ts, Class name = th, completed in 23262ms, has a truthy return value, Arg 1: "/ssd/pkgs/uranus-detection", Arg 2: ""

Furthermore, do you have any idea on loading extension faster? I tried to disable any automatic update, doesn't seem to help much

**Comment by DonJayamanne** [comment]
> However, launching kernel still takes some time, any idea on acclerating this?

Right now this takes < 25s, and thats pretty fast considering this is a conda environment. Conda environments take a lot of time to activate. I wouldn't consider this slow, for instance if you tried to do the same thing outside vscode, open a terminal, activate conda, launch jupyter notebook and run a cell, all of that would take around the same amount of time.

> I agree, it seems loading extension is the main casue.

So now that we know Jupyter Extension is not whats slow lets focus on the delays in loading VS Code.

**Comment by DonJayamanne** [comment]
@roblourens perhaps you might some idea why things are a little slow in this remote scenario.

**Comment by qianyizhang** [comment]
> > However, launching kernel still takes some time, any idea on acclerating this?
> 
> Right now this takes < 25s, and thats pretty fast considering this is a conda environment. Conda environments take a lot of time to activate. I wouldn't consider this slow, for instance if you tried to do the same thing outside vscode, open a terminal, activate conda, launch jupyter notebook and run a cell, all of that would take around the same amount of time.
> 
> > I agree, it seems loading extension is the main casue.
> 
> So now that we know Jupyter Extension is not whats slow lets focus on the delays in loading VS Code.

I installed everything on SSD, and I have a pretty good server.
activate conda + starts jupyter notebook via cli takes ~5s.

**Comment by DonJayamanne** [comment]
Thanks,  Can we close this issue as fixed

**Comment by DonJayamanne** [comment]
Sure thing

**Comment by roblourens** [comment]
If you fixed the problem by installing everything on a faster disk, that's a good indication that the system was just slow to load code. You can get some more specific numbers by running the command "Startup Performance" and checking the extension activation timing numbers. I'm not aware of any general perf issue with remotes.
