### ISSUE TITLE
Kernel issues after March 2023 release

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#13362]
From [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details):

> I was working with this extension just fine, then after March 2023 it became intolerable the amount of times the kernel just won't work. Really dissapointed as this was a really good tool to work on vscode.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
