### ISSUE TITLE
text underneath an arrow caused 'math processing error'

### ISSUE THREAD

**Issue by linjzq** [microsoft/vscode-jupyter#1336]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1.
$$
\require{AMScd}
\begin{CD}
A @>>i> B
\end{CD}
$$

$$
\require{extpfeil}
\begin{array}{ccc}
a & \xrightarrow[i]{} & b
\end{array}
$$

## Actual behavior
[Math Processing Error]
[Math Processing Error]
## Expected behavior
Both above code snippets work fine when using browser based Jupyter Notebook, or plugging into an html file. They didn't work using VSCode with Python extension. I reported this bug (#101642) to VSCode. But they closed it and suggested me open a bug report with Python Extension team.

### Your Jupyter and/or Python environment
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134
ms-python.python v2020.6.91350. 
Python 3.7.3 
Conda version 4.6.11

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local | Remote | N/A
-   **Extension version:** 20YY.MM.#####-xxx
-   **VS Code version:** #.##
-   **Setting python.jediEnabled:** true | false
-   **Setting python.languageServer:** Jedi | Microsoft | None
-   **Python and/or Anaconda version:
-   **OS:** Windows | Mac | Linux (distro):
-   **Virtual environment:** conda | venv | virtualenv | N/A | ...

## Developer Tools Console Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by joyceerhl** [comment]
Math-in-markdown support is now provided by VS Code. Please file an issue if this isn't working as expected.
