### ISSUE TITLE
Confetti animation displays differently in Jupyter Lab and VS Code notebook

### ISSUE THREAD

**Issue by kolibril13** [microsoft/vscode-jupyter#13378]
# Summary
When I run a confetti animation, the confetti shows in front of the cell in Jupyter Lab, but behind the cell in VS Code.
Is it possible to implement the display layer order in VS Code the same as in Jupyter Lab? That would be amazing!
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/44469195/233767641-ff97467c-657b-44a4-8689-1d890885ec92.png">

## Steps to reproduce:

```
pip install ipyreact
```
```py
import ipyreact


class ConfettiWidget(ipyreact.ReactWidget):
    _esm = """
    import confetti from "canvas-confetti";
    import * as React from "react";

    export default function({value, on_value, debug}) {
        return <button onClick={() => confetti() && on_value(value + 1)}>
            {value || 0} times confetti
        </button>
    };"""
ConfettiWidget()
```

## Environment data

-   VS Code version: latest
-   Jupyter Extension version (available under the Extensions sidebar): latest
-   Python Extension version (available under the Extensions sidebar): 3.11
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | N/A

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filling this issue

Unfortunately this is out of scope as the output is displayed inside a different iframe for security reasons, as a result it’s never going to be possible to get the same effect you would in Jupyter
