### ISSUE TITLE
LaTeX code snippet in Markdown cell

### ISSUE THREAD

**Issue by allefeld** [microsoft/vscode-jupyter#1337]
I'm trying to include a LaTeX code snippet in a Markdown cell in a notebook, using a fenced code block:

While editing, it looks like this:
![image](https://user-images.githubusercontent.com/1738353/85456016-6c9a6100-b596-11ea-930a-3bf811eefb18.png)

Rendered it looks like this:
![image](https://user-images.githubusercontent.com/1738353/85456176-96538800-b596-11ea-8057-9df9b1924f06.png)

As you can see, the code is rendered as code, but also there are `$$`s inserted before and after the `document` environment.

I believe this is due to MathJax, which detects a possible math environment and marks it explicitly as such.

The same happens if I use an indented code block, or an explicit HTML `<code>` tag.

I propose that MathJax in the extension is configured to ignore code snippets, probably using the `skipHtmlTags` configuration option

**Comment by joyceerhl** [comment]
Math-in-markdown rendering is now provided by VS Code. Please file an issue at https://github.com/microsoft/vscode if something isn't working for you
