### ISSUE TITLE
Add kernel restart indication on the kernel selector

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#13376]
When I select `Restart`, my eyes gravitate towards the kernel selector but nothing happens there so it feels like the restart action was unresponsive. There's the toast notification on the bottom right but it feels very muted--and is even out of my peripheral vision on a big screen:

![image](https://user-images.githubusercontent.com/10833267/233677133-56f05a5b-4835-4f15-b123-8c7a29523b22.png)

It would be nice if there was an indicator on the kernel selector--maybe a spinner--when the kernel is restarting.

**Comment by DonJayamanne** [comment]
haven't had any upvotes, hence closing this
