### ISSUE TITLE
Multiple reliability issues

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#13389]
Reporting multiple reliability issues from [marketplace review](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details):

- "Run All" button only executes the first cell in the notebook
- Hotkeys are buggy and only seem to work some of the time.
- The "Restart" button no longer does anything

Happy to create new issues for each of these, but wanted to start the thread with the customer here so that they can provide environment data and additional info.

**Comment by DonJayamanne** [comment]
Its been a while since this issue was created and we do not have any issues reported in this space.
Closing as its most likely been resolved since then.
