### ISSUE TITLE
Testing the Platform Specific extensions in Jupyter Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13385]
Testing the Platform Specific extensions in Jupyter Notebooks

Refs: #13085

- [x] macOS @isidorn (intel)
- [x] macOS @aiday-mar (apple silicon)
- [x] linux @aeschli (alpine 64bit)
- [x] linux @rzhao271 (alpine arm64)
- [x] linux @lramos15 (x64 Ubuntu)
- [x] linux @jrieken (arm64 ubuntu)
- [x] windows @TylerLeonhardt (32bit)
- [x] windows @cwebster-99 64bit
- [x] Web @roblourens 

Complexity: 3

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2313385%0A%0A&assignees=DonJayamanne)

---

#### Desktop
- Have a python environment installed
- Have latest VSCode Insiders installed
- Have latest Jupyter pre-release extension installed
- Have latest Python pre-release extension installed

#### Web
- Have a python environment installed and setup with Jupyter on your desktop
- Go to a command prompt
- Activate the python environment with jupyter in it
- Run jupyter with the following command line : jupyter notebook --no-browser --NotebookApp.allow_origin=*
    Note the URL it generates for connecting
- Start insiders.vscode.dev
- Make sure Jupyter prerelease extension is installed
- Open a notebook and connect to the above Jupyter server via the Kernel Picker

### Steps for DeskTop
* Open a notebook (or create a new Jupyter notebook using the command `Create: New Jupyter Notebook`)
* Open the `Jupyter` output panel via the command `Jupyter: Show Output`
* Very the  messages `Exception while attempting zmq : Error: No native build was found for platform` is NOT displayed towards the top of the `Jupyter` output panel 
* NOTE: If the above error message is present, then the test has failed
* Attempt to run a Python cell with the code `print("Hello World")` and verify the output is displayed
    * Note: Installing dependencies could take a while on Windows.

### Steps for Web
* Open a notebook (or create a new Jupyter notebook using the command `Create: New Jupyter Notebook`)
* Open a notebook and connect to the above Jupyter server via the Kernel Picker
* Attempt to run a Python cell with the code `print("Hello World")` and verify the output is displayed
    * Note: Installing dependencies could take a while on Windows.

**Comment by rebornix** [comment]
The test plan item template only support limited platforms but for this TPI, we would love some sanity testing for all platforms. 


We would need to some sanity testing against all platforms VS Code support if not included in above platforms 

  - [ ] Web
  - [ ] Windows 32 bit
  - [ ] Windows 64 bit
  - [ ] Windows ARM64
  - [ ] macOS Intel
  - [ ] Apple Silicon
  - [ ] Linux
    - [ ] x64 deb
    - [ ] x64 rpm
    - [ ] ARM32
    - [ ] ARM64
    - [ ] x64 Alpine
    - [ ] ARM64 Alpine

**Comment by TylerLeonhardt** [comment]
Tested it works in ` x64 rpm`

**Comment by aeschli** [comment]
Tested on Alpine.
