### ISSUE TITLE
vscode python jedi client: couldn't create connection to server

### ISSUE THREAD

**Issue by zhimin-z** [microsoft/vscode-jupyter#13380]
## Environment data

-   VS Code version: 1.77.3 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2023.3.1201040234
-   Python Extension version (available under the Extensions sidebar): v2023.6.1
-   OS (Windows | Mac | Linux distro) and version: Linux
-   Python and/or Anaconda version: 3.7.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Remote

## Expected behaviour

When I set up the pyenv to Python 3.7.0 in GitPod or CodesSpaces in Github, it crashes again and again when pip installing any available package: `line 20: 15589 Segmentation fault "$PYENV_COMMAND_PATH" "$@"` The exact same problem could be found [here](https://stackoverflow.com/questions/72210026/vscode-python-jedi-client-couldnt-create-connection-to-server).

## Actual behaviour

It just works like before.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open any project in Gitpod or CodeSpace at GitHub. Type the following command: `pyenv install 3.7.0` `pyenv local 3.7.0`
2. Then try to pip install any package, and you will see the error.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

![image](https://user-images.githubusercontent.com/8592144/233803147-e54d1c37-48a3-42f0-8978-4325e45808b5.png)
![image](https://user-images.githubusercontent.com/8592144/233803151-947a7d0a-c52f-4787-b2ef-14d91c758bc2.png)

</p>
</details>

**Comment by DonJayamanne** [comment]
Sorry I never got back to you on this issue, totally missed this.
Are you still running into this issue?

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
