### ISSUE TITLE
Debug code lens for mixed Python code cells (markdown & code)

### ISSUE THREAD

**Issue by Girmii** [microsoft/vscode-jupyter#13388]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

VSCode supports mixed Python code cells; cells which have a markdown tag (# %% [markdown]), but contain Python code as well. See [#2285](https://github.com/microsoft/vscode-jupyter/issues/2285).
VSCode also disables the debug code lens for markdown cells (which mixed cells are considered to be). See [#3265](https://github.com/microsoft/vscode-jupyter/issues/3265).

This seems a bit contradictory, because it is possible to run code in a mixed (markdown) cell, but not possible to debug it.
![VSCode debug code lens](https://user-images.githubusercontent.com/2436792/234035021-d7021f9b-88bf-4b93-8718-ed8439eac50a.png)

It there anyway to detect mixed cells and re-add the 'debug' code lens?

### VS Code Version

1.77.3

### Jupyter Extension Version

v2023.3.1201040234

**Comment by amunger** [comment]
I don't think this is worth fixing since the workaround of adding another cell marker for the code is fairly simple.
