### ISSUE TITLE
Testing Show whether a remote kernel is busy when reconnecting after reload

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13386]
Testing Show whether a remote kernel is busy when reconnecting after reload

Refs: #13085

- [x] anyOS @joaomoreno
- [x] web @roblourens

Complexity: 3

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2313275%0A%0A&assignees=DonJayamanne)

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2313386%0A%0A&assignees=DonJayamanne)

---

#### Desktop
- Have a python environment installed
- Have latest VSCode Insiders installed
- Have latest Jupyter pre-release extension installed

#### Web
- Have a python environment installed and setup with Jupyter on your desktop
- Go to a command prompt
- Activate the python environment with jupyter in it
- Run jupyter with the following command line : jupyter notebook --no-browser --NotebookApp.allow_origin=*
    Note the URL it generates for connecting
- Start insiders.vscode.dev
- Make sure Jupyter prerelease extension is installed
- Open a notebook and connect to the above Jupyter server via the Kernel Picker

### Steps for DeskTop/Web
* Open a notebook (or create a new Jupyter notebook using the command `Create: New Jupyter Notebook`)
* Open a notebook and connect to the above Jupyter server via the Kernel Picker
* Attempt to run a Python cell with the code `print("Hello World")` and verify the output is displayed
* Save the notebook
* Run a cell with the following code
```python
import time
for i in range(200):
    time.sleep(1)
    print(i)
```
* Run the above cell, and verify you can see some of the output starting from 1, 2...
* Reload VS Code
* After reloading, the notebook will be opened and the same kernel will be selected
* A few seconds later you should see the toolbar with the icon `Interrupt` displayed on the top
* [ ] Verify the `Interrupt` icon is dispalyed in the toolbar
* [ ] Verify the `Run All` icon is NOT dispalyed in the toolbar
* [ ] Click on the `Interrupt`button and verify you can now run the previous `print("Hello World")` cell and it runs to completion
* Now run a cell with the following code
```python
import time
for i in range(30):
    time.sleep(1)
    print(i)
```
* Reload VS Code
* [ ] Verify the `Interrupt` icon is dispalyed in the toolbar
* Wait for 30s 
* [ ] Verify the `Interrupt` icon changes to `Run All`

![Screenshot 2023-04-24 at 15 39 44](https://user-images.githubusercontent.com/1948812/233908858-f6138988-407f-4bfa-9e1e-dadf670f7fb0.png)
![Screenshot 2023-04-24 at 15 39 36](https://user-images.githubusercontent.com/1948812/233908850-7322e538-4f96-457d-9ba1-ef044c099d66.png)

**Comment by joaomoreno** [comment]
@DonJayamanne Since this is about remote Jupyter kernel, the Desktop steps are missing instructions on how to start it up, only Web has them.

Also, those steps for Web are very loosely defined:

> - Activate the python environment with jupyter in it

How to do this? Luckily, GPT comes to the rescue:

> **How to activate a Python environment with Jupyter?**
> 
> Here are the steps to activate a Python environment with Jupyter:
> 1.	Open your terminal and navigate to the directory where you want to create your environment.
> 2.	Type the following command in your terminal to create a new Python environment. Replace `myenv` with your desired environment name.
> 
> ```conda create --name myenv python=3.8```
> 
> 3.	Activate the environment by typing the following command. Replace `myenv` with the name of your environment.
> 
> ```conda activate myenv```
> 
> 4.	Install the Jupyter package by typing the following command in your terminal:
> 
> ```conda install jupyter```
> 
> 5.	Start Jupyter notebook by typing the following command in your terminal:
> 
> ```jupyter notebook```
> 
> 6.	Your default web browser will open up and you can start working with Jupyter notebooks.
> 7.	When you are done working, you can deactivate the environment by typing the following command:
> 
> ```conda deactivate```
> 
> That's it! You have successfully activated a Python environment with Jupyter.

**Comment by joaomoreno** [comment]
While I've verified this works as suggested above in Desktop, it would've been nicer to also reset the progress state for the running cell, not just the entire notebook. I'm guessing that's coming down the road?

**Comment by roblourens** [comment]
@joaomoreno from what I understand, it's not possible to figure out which cell is running while the kernel is busy

@DonJayamanne After reconnecting, am I supposed to see the output streaming in again? Your steps don't mention that but I thought I remembered seeing that when you demoed this.

**Comment by DonJayamanne** [comment]
> After reconnecting, am I supposed to see the output streaming in again? 

no

> remembered seeing that when you demoed this.

not yet implemented
