### ISSUE TITLE
Build platform specific extension targeting web platform

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13383]
https://github.com/microsoft/vscode/issues/180525
Currently web ends up installing the universal VSIX, hence we do have a build that works on the web (however it is the universal vsix, large)

**Comment by andreamah** [comment]
@DonJayamanne are there some verif steps for this bug?

**Comment by DonJayamanne** [comment]
Just install the extension and verify you can use some feature of the Jupyter extension or commands
Previously the extension would not activate due to an upstream issue in vscode
