### ISSUE TITLE
Pressing `Run` modifies notebook even though nothing has changed

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-jupyter#13398]
Testing #13275

Possibly unrelated to the remote kernel testing, but definitely behavior I did not expect. When running a cell, I see the notebook document changes without actually seeing no difference in the output. It seems like the run count is being serialized:

<img width="496" alt="image" src="https://user-images.githubusercontent.com/22350/234267900-8f24537d-3c98-4e97-b1d7-473aee3e7c54.png">

Maybe this is purposeful and there since the beginning, but definitely surprised me just now.

**Comment by DonJayamanne** [comment]
Thanks,
This is the expected behaviour
