### ISSUE TITLE
'vh' CSS unit in vertical layout for IPyhton.display are incorrect

### ISSUE THREAD

**Issue by jmrouet** [microsoft/vscode-jupyter#13407]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Creating a widget or html component with IPuthon.display.HTML or ipywidgets, using the VH CSS unit results in oversized elements.

1VH is normally defined as 1% of the viewport height. however, in vscode the viewport is much taller than the display area (or tab).

Example of code to reproduce:
```python
from IPython.display import HTML

input_form = """
<div style="width:500px; height:50px; border:1px solid white;">Rect 500px, 50px</div>
<div style="width:95%; height:50px; border:1px solid blue;">Rect 95%, 50px</div>
<div style="width:95vw; height:50px; border:1px solid lightblue;">Rect 95vw, 50px</div>
<div style="width:50%; height:100%; border:1px solid green;">Rect 50%, 100%</div>
<div style="width:50%; height:1vh; border:1px solid green;">Rect 50%, 1vh</div>
"""

display(HTML(input_form))
```

![image](https://user-images.githubusercontent.com/36963549/234567585-caa6d470-24ff-4c6f-b407-639f7818c7bc.png)

the green box is supposed to be very small (1% of the viewport), but it is actually around 140px already

Inspecting the tab from the Developer Tools, I see that the iframe "Notebook webview content" is sized: ~1800x14000. 
Is it on purpose ? 
Rendering the same jupyter code in a browser behaves as expected.

Hope my description of the issue is clear ;-)

### VS Code Version

Version: 1.77.3 (user setup) Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710 Date: 2023-04-12T09:16:02.548Z Electron: 19.1.11 Chromium: 102.0.5005.196 Node.js: 16.14.2 V8: 10.2.154.26-electron.0 OS: Windows_NT x64 10.0.22621 Sandboxed: Yes

### Jupyter Extension Version

v2023.3.1201040234

### Jupyter logs

```shell
no specific output
```

### Coding Language and Runtime Version

python 3.9

### Running Jupyter locally or remotely?

Local

**Comment by eomeara** [comment]
Same problem. I have an ipyleaflet map with height=80vh. Works correctly in browser but goes on forever in vscode.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, however given the fact that not many have run into this issue and there haven't been any upvotes, I'm closing this issue for now.

**Comment by jmrouet** [comment]
Dear Jayamanne,

Closing the issue won't make the problem disappear!
I can understand this is low priority as only few people complained, but
the issue is real.

Can at least an expert give some clues on where to look at in the code. I
would then try to correct myself and create a Pull Request

Regards

Le mar. 12 déc. 2023, 22:45, Don Jayamanne ***@***.***> a
écrit :
