### ISSUE TITLE
Jupyter can't find nbconvert to export as html

### ISSUE THREAD

**Issue by jonathanlilly** [microsoft/vscode-jupyter#13404]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

This is the same problem as in the closed issue #4347

Jupyter command jupyter-nbconvert not found in VS Code on Win10

although in this case I'm on a Mac.  It seems that VSCode doesn't know where to look to find nbconvert, although I could use it from the command line.

After spending several hours with this same problem, I finally found a very simple solution. The solutions in issue #4347 did not work for me.  Perhaps there is another solution that involves setting PYTHONPATH, but it seems strange that the command line works while the call from within VSCode doesn't.  

In VSCode's settings.json file, there is a line that can be set to extra directories needed by Python. In my case that looks like this:

``` 
"python.analysis.extraPaths": ["/Users/lilly/micromamba/lib/python3.11"],
```

This important thing seems to be that that directory contains the directory `site-packages`.

It's relevant to mention that I am getting VSCode to find the Python distribution I want it to use with

```
"python.defaultInterpreterPath": "/Users/lilly/micromamba/bin/python",
```

I hope this helps anyone else struggling with the same problem.

Now, I am able to explore to html from within VSCode by choosing ...>Export>HTML from the toolbar.

### VS Code Version

1.77.3

### Jupyter Extension Version

v2023.3.1201040234

### Jupyter logs

```shell
> ~/micromamba/bin/python -m pip list
error 16:09:11.223: Failed to get activated conda env variables for /Users/lilly/micromamba/bin/python
                 in 9ms
error 16:09:11.224: Unable to determine site packages path for python /Users/lilly/micromamba/bin/python (Conda)
info 16:09:11.226: Process Execution: > ~/micromamba/bin/python -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/micromamba/bin/python -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
error 16:09:11.227: Failed to get activated conda env variables for /Users/lilly/micromamba/bin/python
                 in 14ms
error 16:09:11.227: Unable to determine site packages path for python /Users/lilly/micromamba/bin/python (Conda)
info 16:09:11.228: Process Execution: > ~/micromamba/bin/python -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/micromamba/bin/python -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
error 16:09:11.378: Failed to get activated conda env variables for /Users/lilly/micromamba/bin/python
                 in 2ms
error 16:09:11.379: Unable to determine site packages path for python /Users/lilly/micromamba/bin/python (Conda)
info 16:09:11.379: Process Execution: > ~/micromamba/bin/python -m jupyter kernelspec --version
> ~/micromamba/bin/python -m jupyter kernelspec --version
error 16:09:11.552: Failed to get activated conda env variables for /Users/lilly/micromamba/bin/python
                 in 3ms
error 16:09:11.553: Unable to determine site packages path for python /Users/lilly/micromamba/bin/python (Conda)
info 16:09:11.553: Process Execution: > ~/micromamba/bin/python -c "import nbconvert;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/micromamba/bin/python -c "import nbconvert;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
error 16:09:11.891: Failed to get activated conda env variables for /Users/lilly/micromamba/bin/python
                 in 4ms
error 16:09:11.891: Unable to determine site packages path for python /Users/lilly/micromamba/bin/python (Conda)
info 16:09:11.893: Process Execution: > ~/micromamba/bin/python -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/micromamba/bin/python -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
error 16:09:11.921: Failed to get activated conda env variables for /Users/lilly/micromamba/bin/python
                 in 5ms
error 16:09:11.921: Unable to determine site packages path for python /Users/lilly/micromamba/bin/python (Conda)
info 16:09:11.923: Process Execution: > ~/micromamba/bin/python -m jupyter nbconvert /var/folders/24/lt32gtnn37vdn9n0qyfrntsm0000gn/T/f017475d-427e-49f5-a70e-04ecfaf43a08/vortexmoments.ipynb --to html --output tmp-26449lVSOcRtheD3Y.html --output-dir /var/folders/24/lt32gtnn37vdn9n0qyfrntsm0000gn/T --debug
> ~/micromamba/bin/python -m jupyter nbconvert /var/folders/24/lt32gtnn37vdn9n0qyfrntsm0000gn/T/f017475d-427e-49f5-a70e-04ecfaf43a08/vortexmoments.ipynb --to html --output tmp-26449lVSOcRtheD3Y.html --output-dir /var/folders/24/lt32gtnn37vdn9n0qyfrntsm0000gn/T --debug
```

### Coding Language and Runtime Version

Python 3.11.3

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and sorry you are running into this,
Thanks for sharing the error logs, very useful and indicates that something is certainly not behaving correctly.

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by jonathanlilly** [comment]
Hi Don,

Thanks for getting back to me.  I reproduced the issue on another
computer.  Here is the log file:

error 14:13:45.291: Export failed Error: Jupyter nbconvert is not
installed
    at Yw.getExportInterpreter (/Users/lilly/.vscode/extensions/ms-
toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:279832)
    at Zw.executeCommand (/Users/lilly/.vscode/extensions/ms-
toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:281012)
    at aS.export (/Users/lilly/.vscode/extensions/ms-toolsai.jupyter-
2023.3.1201040234/out/extension.node.js:24:285277)
    at yS.exportToFormat (/Users/lilly/.vscode/extensions/ms-
toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:290305)
    at yS.performNbConvertExport (/Users/lilly/.vscode/extensions/ms-
toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:290074)
    at yS.performExport (/Users/lilly/.vscode/extensions/ms-
toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:289751)
    at yS.exportImpl (/Users/lilly/.vscode/extensions/ms-
toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:289379)
    at yS.export (/Users/lilly/.vscode/extensions/ms-toolsai.jupyter-
2023.3.1201040234/out/extension.node.js:24:289135)
    at b_.export (/Users/lilly/.vscode/extensions/ms-toolsai.jupyter-
2023.3.1201040234/out/extension.node.js:24:424037)
    at m.h (/Applications/Visual Studio
Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:125789)

After including the statements in my settings.json file as described in
my post, the html generator now works on this computer as well.

On prompt I noticed this time: I did not choose to allow
terminal.integrated.inheritEnv to be set to false.  Not sure if this is
relevant. 

Best wishes,
Jonathan

On April 25, 2023, Github Notifications ***@***.***>
wrote:
> Thanks for filing this issue and sorry you are running into this,
>  Thanks for sharing the error logs, very useful and indicates that
> something is certainly not behaving correctly.
>
> Please could you enable logging as follows:
>
>  *  Open settings & go into Jupyter->Logging
>  *  Change the value to verbose
>  *  Reload VS Code,
>  *  Attempt to repro the issue & then copy the output from the Jupyter
>     output panel.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/microsoft/vscode-jupyter/issues/13404#issuecomment-
1522634423>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABWKBAR62WBVWTZ6BKRGMHTXDB3HZANCNFSM6AAAAAAXLTO4RQ>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by DonJayamanne** [comment]
Thanks for getting back, 
Closing this as resolved.
