### ISSUE TITLE
VScode cannot read or use the 'PYTHONPATH' variable in the 'env' in kernel.json

### ISSUE THREAD

**Issue by lester1027** [microsoft/vscode-jupyter#13415]
## Environment data

-   VS Code version: 1.77.3
-   Jupyter Extension version (available under the Extensions sidebar): v2023.3.1201040234
-   Python Extension version (available under the Extensions sidebar): v2023.6.1
-   OS (Windows | Mac | Linux distro) and version: Windows 11 WSL 2
-   Python and/or Anaconda version: Python 3.10.5, Anaconda 4.12.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote |: local

## Expected behaviour

I added a kernel.json file under ~/.local/share/jupyter/kernels.

`{
    "argv": [
        "/home/lester/anaconda3/envs/mne/bin/python",
        "-m", "ipykernel",
        "-f", "{connection_file}"
    ],
    "display_name": "Python 3 - MNE",
    "language": "python3",
    "env": {
        "PYTHONPATH": "/mnt/c/Users/leste/OneDrive/Frutta/MindAmp/git/eeg_device"
    }
}
`
The Jupyter kernel should be able the append the path(s) in the PYTHONPATH automatically.

## Actual behaviour

Only the browser jupyter can do that. Vscode notebook fails in doing so. sys.path does not show the PYTHONPATH added

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, I will have a look at this.
For now, you can create a `.env` file in  your workspace folder and add `PYTHONPATH=...` into that and the kernel will use that.

**Comment by DonJayamanne** [comment]
@lester1027 
I have tested this and it works as expected.
Please let me know if this problem still persists.

**Comment by adrn** [comment]
I'm seeing the same issue as raised by @lester1027, specifically when starting a kernel through a remote tunnel.
