### ISSUE TITLE
Error: getaddrinfo ENOENT raw.githubusercontent.com

### ISSUE THREAD

**Issue by 18392152392** [microsoft/vscode-jupyter#13419]
## Environment data

-   VS Code version: 1.77
-   I have download the sourceCode of the jupyter, when I run npm install or yarn, it always wrong, I and My group members have tried 
two days, we are crazy, Can you help to fix? thanks very very very much!

![1682681275474](https://user-images.githubusercontent.com/52459655/235136549-fa499ba7-4bff-4f48-aee9-b272636b45d9.jpg)

**Comment by DonJayamanne** [comment]
Try the latest version of the source code, you shouldn’t come across this error

**Comment by DonJayamanne** [comment]
Should be fine in the latest source
Closing this as I believe this isn’t an issue anymore
Please feel free to reopen or ping here or create a new issue of this still exists
