### ISSUE TITLE
Allow (Fine-Grained) Port Configuration for Notebooks  

### ISSUE THREAD

**Issue by farhanhubble** [microsoft/vscode-jupyter#13416]
VSCode launches notebooks using `ipykernel_launcher` with a command like this:
```
/home/username/bin/python3.8 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9010 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"72dc9cca-e641-445a-9ceb-3ca5433dc8c0" --shell=9007 --transport="tcp" --iopub=9011 --f=/home/username/.local/share/jupyter/runtime/kernel-v2-3617206EN99MmVys9xf.json
```
There are four port numbers that get passed: **stdin**, **control**, **iopub** and **hb**(heartbeat). However there are no settings for Jupyter notebooks in VSCode to control the port assignment. The port assignment or the full command should be editable. 

- Setting "--control=9991" in `jupyter.jupyterCommandLineArguments`  does not work on VSCode `v1.77.3`
- Setting "--NotebookApp.port=9999" in `jupyter.jupyterCommandLineArguments`  does not work on VSCode `v1.77.3`

**Comment by DonJayamanne** [comment]
Thanks for filing this issue,
* Can I ask why you would like to control the ports used?
Currently its not possible to hardcode the ports, as the ports could be in use, e.g. if you run two kernels, then the ports you define in some setting will be used and the kernel will fail to start.

What we could do is try to start the ports from a pre-define port number, i.e. if you state 9050 as the starting port we could start generating ports from there, e.tg. 9050, 9051, 9052, 9053 and for the next notebook, use 9054, and so on. and when a kernel is shutdown we re-cycle the ports and start from 9050.

But before we go with that, I'd like to understand the need for this.

**Comment by farhanhubble** [comment]
Thanks @DonJayamanne 
My own use case is to keep certain ports clear for other applications that are finicky about ports. Since the Jupyter ecosystem has that ability it's frustrating to not have that control when using VSCode. Having the ability to set a starting port number should sufficient as long as the launcher can picks all four ports beyond the base number, as you suggested.  

Cheers!

**Comment by DonJayamanne** [comment]
Out of curiosity, what option do you use to configure the port for the python kernels
Is it via cli or config file, please could you provide the coding name or cli argument used

**Comment by farhanhubble** [comment]
I prefer to launch each kernel with its own options. So command line argument like `--control=9991` are my preferred way.

**Comment by DonJayamanne** [comment]
What I meant was, how do you configure the ports today in Jupyter notebook/lab?

**Comment by DonJayamanne** [comment]
Thank you for this feature request, however there haven't been enough upvotes on this issue, hence closing this for now.
