### ISSUE TITLE
Azure Machine Learning remote experience integration (Summary)

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-jupyter#13427]
# Desired experience
This is the desired experience when Azure ML users connect to remote targets and interact with notebooks.

## Kernel pre-selection
We are referring pre-selection to the selection in the kernel picker that VS Code sets by default when opening a notebooks without any manual user interaction.

User is connected to an Azure ML compute instance using VS Code and:

1. Creates a new notebook:  
  a. The kernel picker will pre-select the “Python 3.10 - SDK V2” from Jupyter server http://localhost:8888/  

2. Opens an existing notebook: 
  a. If previously a kernel was selected manually then honor it 
  b. Otherwise, if there is a kernel session from Jupyter server http://localhost:8888/ associated with that notebook, then pre-select it. 
  c. If none of the above, pre-select the “Python 3.10 - SDK V2” from Jupyter server http://localhost:8888/

## Kernel selection
This section defines the desired behavior when the user manually selects a kernel using the kernel picker.

1. User clicks the kernel picker
2. Kernel picker directly displays the kernels and kernel sessions from the Jupyter server http://localhost:8888/ . There is no step-by-step selection, no “Jupyter Kernel”, “Python environments” or “Existing Jupyter Server” options, no “compute instance selection” or other intermediary step.
![image](https://user-images.githubusercontent.com/56176070/235258182-4814e8e8-6206-448d-99e6-158d79ecb164.png)

## VS Code kernel creation
When user is connected to an Azure ML compute instance in VS Code and a new kernel session needs to be created, then the kernel session created on VS Code is a reusable session in JupyterLab and Azure ML and there is one session per notebook.

## Notebooks UI improvements
- There is a clear indication that the kernel is busy
- In case the kernel is busy and user runs a cell show cell status as queued instead of running

# Issues
The following issues are sorted by priority:

- [x] https://github.com/microsoft/vscode-jupyter/issues/13424
- [x] https://github.com/microsoft/vscode-jupyter/issues/13423
- [ ] https://github.com/microsoft/vscode-jupyter/issues/13095
- [x] https://github.com/microsoft/vscode-jupyter/issues/13426
- [x] https://github.com/microsoft/vscode-jupyter/issues/13259
- [x] https://github.com/microsoft/vscode-jupyter/issues/13318
- [x] https://github.com/microsoft/vscode-jupyter/issues/12980
- [x] https://github.com/microsoft/vscode-jupyter/issues/12979

**Comment by DonJayamanne** [comment]
> Opens an existing notebook:
a. If previously a kernel was selected manually then honor it
b. Otherwise, if there is a kernel session from Jupyter server http://localhost:8888/ associated with that notebook, then pre-select it.

this is always possible with the new api provided
Please can you only include the requests that is not possible today

**Comment by DonJayamanne** [comment]
> There is a clear indication that the kernel is busy


this is a already possible today

**Comment by DonJayamanne** [comment]
@sevillal 
Going to close this issue, as I do not see much value in keeping this open anymore.
Only one of the items are left open and since there hasn't been any conversations around any of these issues since they were created I'm closing this for now.

Going forward, lets just create issues for items taht are required to be addressed, i.e. items that are blockers.
