### ISSUE TITLE
For Azure ML remote compute instances pre-select the matching session in remote server (http://localhost:8888)

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-jupyter#13422]
User is connected to a compute instance using Azure ML remote and opens an existing notebook in VS Code:

1. If previously a kernel was selected manually then honor it 

2. Otherwise, if there is a kernel session from Jupyter server http://localhost:8888/ associated with that notebook, then pre-select it. 
3. If none of the above, pre-select the “Python 3.10 - SDK V2” from Jupyter server http://localhost:8888/

**Comment by DonJayamanne** [comment]
Please create a separate issue for the last cases, these are the different issues

The first two have been solved with the openNotebook api (only azml knows what was selected), hence closing this issue

**Comment by DonJayamanne** [comment]
Re-opening as my understanding was incorrect

**Comment by sevillal** [comment]
Closing this. We will try to workaround this from the Azure ML extension.
