### ISSUE TITLE
Show cell status as "Queued" if kernel is busy

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-jupyter#13426]
It might not be specific to Azure ML remote experience, but we it would be ideal to show the cell status as "Queued" if the kernel is busy. Currently it displays "running" although it is not running and it is just waiting for the other operations to finish, it also counts the waiting time as execution time.

**Comment by rzhao271** [comment]
Hi @DonJayamanne, what are some verification steps for this issue?

**Comment by sevillal** [comment]
Verified. 

1. Cell does not show as running (no spinning icon)
2. Running time is corrected
