### ISSUE TITLE
Add an indicator that the kernel is busy

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-jupyter#13425]
This might not be specific to the Azure ML remote experience but we are proposing to add and indicator that the kernel is busy.

This can help in scenarios where user runs some long code in Azure Notebooks, then continues working on VS Code, if connected to the same kernel session it would be useful to know the kernel is busy.

**Comment by DonJayamanne** [comment]
This has always been done in this iteration
This was conveyed to the azml team

**Comment by DonJayamanne** [comment]
Duplicate of the iteration plan item https://github.com/microsoft/vscode-jupyter/issues/13275

**Comment by DonJayamanne** [comment]
See here for UI behaviour https://github.com/microsoft/vscode-jupyter/issues/13386
