### ISSUE TITLE
output stream conflicts when warning directly from the `logging` packages logger

### ISSUE THREAD

**Issue by gitkoi** [microsoft/vscode-jupyter#13432]
Type: <b>Bug</b>

# %% ルートロガー

import logging

print("aaaa")
root_logger = logging.getLogger()

root_logger.handlers.clear()

print(len(root_logger.handlers))

root_logger.info("root logger info")

print(len(root_logger.handlers))
root_logger.warning("root logger warning")
print(len(root_logger.handlers))

logging.info("logging info")
print(len(root_logger.handlers))
logging.warning("logging warning")
print(len(root_logger.handlers))

---
上のコードをセルの実行で、printが出力されません。

---出力---
root logger warning
WARNING:root:logging warning

# root_logger.warning("root logger warning")
ここをコメントアウトするとPrint関数が出力されます。

---出力---
WARNING:root:logging warning
aaaa
0
0
0
1
1

Extension version: 2023.6.1
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3960X CPU @ 3.30GHz (12 x 3300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.92GB (4.29GB free)|
|Process Argv|--crash-reporter-id 94fcaca8-82d9-4eb5-a0e0-4afdf59e8db5|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743
pythonclientmvcf:30725893

```

</details>

**Comment by DonJayamanne** [comment]
Thank you for filing thi sissue, however there are no plans to resolve this.
As Interactiv Window and Jupyter notebooks share the same infrastrcutre of running Python code, thats using IPyKernel, and its not the same as running code in the terminal.
