### ISSUE TITLE
Put a button at the bottom of Jupyter cells which lets you open Data Viewer for the result

### ISSUE THREAD

**Issue by xareelee** [microsoft/vscode-jupyter#13430]
## Currently Problem

Jupyter automatically prints/renders the last value as the output, but it has limit.

![Screenshot 2023-05-01 at 16 33 57](https://user-images.githubusercontent.com/804308/235430717-a0065470-3474-44f0-937d-6cde6d2a806c.png)

To view the whole data frame, you need to create a variable to capture the value, open the "Variables" tool, find that variable, and click the button to view it in "Data Viewer":

![Screenshot 2023-05-01 at 16 34 38](https://user-images.githubusercontent.com/804308/235431002-46340df5-daac-4f60-927c-eb4c8bb44bbe.png)

and you'll finally see the data frame:

![Screenshot 2023-05-01 at 16 35 05](https://user-images.githubusercontent.com/804308/235431012-42128622-45ca-4495-9b74-ef7dd7bb2067.png)

## Feature request

Why not just put a button which lets you open Data Viewer for the result?

![Screenshot 2023-05-01 at 16 57 16](https://user-images.githubusercontent.com/804308/235431916-1e88cd5a-0fb5-4964-bacb-e9138258af3c.png)

Just let the Jupyter core captures the runtime objects for every cell, and you don't need to write the redundant code to view the whole data frame.

**Comment by amunger** [comment]
thanks for the suggestion, you might also be interested in trying out the [Data Wrangler extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.datawrangler) to provide this functionality for now

**Comment by amunger** [comment]
closing since we will likely just rely on the data wrangler extension taking care of dataframe viewing going forward.
