### ISSUE TITLE
Jupyter notebook multiline math equations render error

### ISSUE THREAD

**Issue by espylapiza** [microsoft/vscode-jupyter#1343]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1.

Paste the following code as markdown in a jupyter cell.

```markdown
$$\begin{aligned}
f(x)&=x+x\\
&=2x
\end{aligned}$$
```

## Actual behavior

![image](https://user-images.githubusercontent.com/39075622/81497062-a0733d00-92ee-11ea-8caa-9a7aef0cdd48.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/39075622/81497007-41152d00-92ee-11ea-87d5-d3089aa2b463.png)

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.4.76186
-   **VS Code version:** 1.45.0
-   **Setting python.jediEnabled:** true
-   **Python and/or Anaconda version:** Python 3.7.6, conda 4.8.3
-   **OS:** Windows | Mac | Linux (distro): Manjaro Linux
-   **Virtual environment:** conda

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by mjbvz** [comment]
This appears to render properly using native notebooks in VS Code 1.60:

<img width="605" alt="Screen Shot 2021-08-04 at 11 02 53 PM" src="https://user-images.githubusercontent.com/12821956/128299382-ec8a4de8-9cd8-4dde-8c8f-7455f4505824.png">
