### ISSUE TITLE
IW and notebooks on 3.11 swallow exception.add_note()

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-jupyter#13446]
[PEP 678](https://peps.python.org/pep-0678) added in 3.11 allows enriching exceptions with notes. This works in the REPL:

```py
>>> try:
...   raise TypeError('bad type')
... except Exception as e:
...   e.add_note('Add some information')
...   raise
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: bad type
Add some information
```

Entering the same in an IW or Jupyter notebook using a 3.11 kernel, I don't see the note:

```py
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Untitled-1.ipynb Cell 1 in 2
      1 try:
----> 2   raise TypeError('bad type')
      3 except Exception as e:
      4   e.add_note('Add some information')

TypeError: bad type
```

**Comment by DonJayamanne** [comment]
Thanks, I've tried this in Jupyter Lab/Notebook and it does not work there either.
I'm assuming the Python kernel needs to be updated to support this (if it hasn't already been done)

Closing as this isn't an issue wit[h the Jupyter extension (all we do is return the same error message returned by the backend kernel)

![Screenshot 2023-05-04 at 17 05 29](https://user-images.githubusercontent.com/1948812/236133843-71a48a9e-9dcd-410d-9a50-24541e5e2b7c.png)

**Comment by janosh** [comment]
By Python kernel, you mean https://github.com/ipython/ipykernel?

**Comment by DonJayamanne** [comment]
Yes

**Comment by janosh** [comment]
Doesn't look like it's been reported yet.
