### ISSUE TITLE
Unable to get Server Id required when connecting to a Kernel running on Remote Jupyter Server

### ISSUE THREAD

**Issue by rjra2611** [microsoft/vscode-jupyter#13458]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Hey, 

I'm trying to connect to a kernel on a remote Jupyter server for which I implemented the interface `IJupyterUriProvider` 

My aim is to use `notebook.selectKernel` command to select the kernel of the remote server.

The `notebook.selectKernel` command requires providing the `controllerId`.  Given we don't have access to the private `KernelService` API to fetch the `serverId` (require to create `controllerId`). 

E.g ControllerId: `﻿https://remote/?id=_builtin.jupyterServerUrlProvider&uriHandle={JupyterServerUriHandle}`

How can I go about it achieving it? 

```
vs.commands.executeCommand('notebook.selectKernel', {
    id: controllerId,
    extension: "ms-toolsai.jupyter"
});
```

What I tried to re-create the serverId:
- From my understanding, the serverId is a SHA-256 hash of the server URI
- The server URI requires the `JupyterServerUriHandle`
- The `JupyterServerUriHandle` is received as an argument of `getServerUri` method but that didn't happen

The `getServerUri` method (`getServerUri(handle: JupyterServerUriHandle): Promise<Models.IJupyterServerUri>`) from the implementation of `IJupyterUriProvider` didn't receive `handle` as argument

![image](https://user-images.githubusercontent.com/28739120/236338734-f1d8dcb6-77fc-47db-9227-dba9cd910c07.png)

### VS Code Version

Version: 1.77.3 (user setup) Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710 Date: 2023-04-12T09:16:02.548Z Electron: 19.1.11 Chromium: 102.0.5005.196 Node.js: 16.14.2 V8: 10.2.154.26-electron.0 OS: Windows_NT x64 10.0.19044 Sandboxed: No

### Jupyter Extension Version

v2023.3.1201040234

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment]
> My aim is to use notebook.selectKernel command to select the kernel of the remote server.

I would not recommend doing this, this is meant only for internal use, 

> ommand requires providing the controllerId. Given we don't have access to the private KernelService API to fetch the serverId (require to create controllerId).

Thats correct and we do not plan on making this available for other extensions as this could cause other issues.

I would not recommend forcefully changing the kernel, instead the user should do this, 
However you can use the following API to change the kernel of a notebook, see here https://github.com/microsoft/vscode-jupyter/issues/13251
