### ISSUE TITLE
Cannot restore cell output options after making it scrollable

### ISSUE THREAD

**Issue by david-cortes** [microsoft/vscode-jupyter#13454]
## Environment data

-   VS Code version: 1.78.0
-   Jupyter Extension version (available under the Extensions sidebar): v2023.4.1011241018
-   Python Extension version (available under the Extensions sidebar): v2023.8.0
-   OS (Windows | Mac | Linux distro) and version: linux (debian sid)
-   Python and/or Anaconda version: conda 23.1.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Steps to reproduce:

1. Create a jupyter interactive window.
2. Execute there some statement tha would produce a lot of simple-text print output, such as the following:
```python
for i in range(1000):
    print(i,i,i)
```
3. At the bottom of the produced output for that cell, click where it says "View as a scrollable element".
4. Try to switch the cell back to how it was before clicking the scrollable button above.

## Expected behaviour

Should have such an option in the right-click menu of the cell or in the left rectangle in blue that's shown when scrolling through the cell outputs.

## Actual behaviour

Not possible to turn it back to how it was before clicking to make it scrollable, and not possible to open the output in a simple text editor window from there.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by amunger** [comment]
you can use `notebook.cell.toggleOutputScrolling` to toggle it back

**Comment by notuntoward** [comment]
Yes, I would also greatly appreciate a button that would undo making a cell output a `scrollable element`

**Comment by notuntoward** [comment]
@amunger, thanks, that helps.  If anybody is wondering how to run `notebook.cell.toggleOutputScrolling` on Windows, it's mapped by default to `Ctrl+K Y`

**Comment by amunger** [comment]
closing as there hasn't been enough votes for this to be implemented
