### ISSUE TITLE
Using Tensorboard behind a reverse proxy

### ISSUE THREAD

**Issue by Ali-Flt** [microsoft/vscode-jupyter#13487]
As far as I've understood, the "Launch Tensorboard" command in vs code does nothing more than starting a Tensorboard session and simply opening "localhost:6006" in a new tab. Right?

I don't think you can call this an "integration". It only works fine in a local environment. 
This approach means that localhost:6006 of the code-server must be somehow forwarded to localhost:6006 of the client. Which can be worked around for a SSH remote connection but is not as straight forward for other scenarios. 

For instance my scenario: A Code-server inside a container in a server behind reverse proxy. Meaning the 8000 port of the container is exposed and redirected to https://mydomain and I use https://mydomain to connect to my Code-server. 
In this case localhost:6006 of the container is not forwarded to my machine's localhost:6006 so just opening localhost:6006 does me no good. 

I believe the correct way to do this "Tensorboard integration" would be to actually make the VS code session independent from Tensorboard's process. Meaning the code-server must read from localhost:6006 and send what it receives to the opened tab in the VS code GUI, removing the need for client to worry about port forwarding completely.

Also if you don't plan to do this "actual integration", I suggest at least adding more Tensorboard related configurations in the extension settings of VSCode. Such as an option to specify the url to open when Launch Tensorboard is called to override http://localhost:6006. This way I can at least expose localhost:6006 to another domain inside my reverse proxy and tell VS code to open that domain whenever I launch Tensorboard.

**Comment by DonJayamanne** [comment]
Thanks for this feature suggestion, however given the fact that this hasn't recieved any upvotes, I'm closihng this issue
