### ISSUE TITLE
Jupyter Notebooks not loading

### ISSUE THREAD

**Issue by kaptnfirlefanz** [microsoft/vscode-jupyter#13485]
## Environment data

-   VS Code version: 1.78.1 (VSCodium)
-   Jupyter Extension version (available under the Extensions sidebar): v2023.3.100
-   Python Extension version (available under the Extensions sidebar): v2023.8.0
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04.6 LTS
-   Python and/or Anaconda version: 3.8.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A

## Actual behaviour

.ipnyb are loding forever. This is true for all files in all workspaces. 

## Logs
[vscode-app-1683797658018.log](https://github.com/microsoft/vscode-jupyter/files/11450666/vscode-app-1683797658018.log)

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, and sorry you are running into this.

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
If this still fails, can you try to disable all extensions including Jupyter extension and see if the ipynb files load.
If that works, then try disabling all except the jupyter extension and test loading IPYNB file, 
Basically confirm that ipynb fails to load only when Jupyter extension is enabled.

**Comment by chadsr** [comment]
See https://github.com/VSCodium/vscodium/issues/1508

I'm having the same issue and it seems to be related to VSCodium build 1.78.1, not this extension.
