### ISSUE TITLE
Very opaque what's happening when you reconnect to a kernel

### ISSUE THREAD

**Issue by varunjain-github** [microsoft/vscode-jupyter#13483]

**Comment by DonJayamanne** [comment]
Thanks for filling this issues, please can you provide more information on what is expected here, ie what would solve this issue.

**Comment by DonJayamanne** [comment]
Thanks @Huntrr , closing this issue in favour of https://github.com/microsoft/vscode-jupyter/issues/13276
The above issue is something I'm currently working on.
