### ISSUE TITLE
Faulty remote kernel - v2023.4.1011241018 - Current

### ISSUE THREAD

**Issue by ndgayan** [microsoft/vscode-jupyter#13486]
VSCode - 1.78.1

I can not execute the cell using the Jupyter extension. Could you take a look at what changes are breaking? 
![image](https://github.com/microsoft/vscode-jupyter/assets/1891059/147c968a-ef9c-4e35-a475-308f3a684fb6)

Working fine after rolling back to the previous version of the extension.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue and sorry you are running into this issue, 
please could you share the information that is requested in the issue template

* Platform
* Steps to reproduce this error

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by ndgayan** [comment]
It seems the Jupyter extension is incorrectly registering the Python kernel as a C kernel. 

Platform
VSCode Remote Development [Remote server is Ubnutu 20.04 with SSH]

Steps to reproduce this error
    1. Install the recent version of Jupyter Extension [By default, it is installed on the remote Ubuntu server]
    2. Create a Jupyter NB. 
    3. Add a cell and write Python code.
    4. After running it, failed with the above message. 

After deleting the remote Jupyter extension (rebooting the server) and re-installing fixed the issues. Now Jupyter NB cell is running fine.

I can not produce errors anymore:

Below is the successful cell execution log.
        10:20:46.567 [debug] Start cell 2 execution @ 1683901246567
        10:20:46.617 [debug] End cell 2 execution @ 1683901246617, started @ 1683901246567, elapsed time = 0.05s
        10:20:46.618 [debug] Cell 2 executed with state Success
        10:20:46.618 [debug] VSCodeNotebookController::handleExecution, Class name = Dy, completed in 55ms, has a falsy return value
