### ISSUE TITLE
DS: Outline feature in jupyter notebook mode

### ISSUE THREAD

**Issue by jediyoda36** [microsoft/vscode-jupyter#1349]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Please support outline feature in jupyter notebook mode.**
Just like *Table of Contents* extension in Jupyter Notebook. [Table of Contents extension webpage](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html)

**Comment by DonJayamanne** [comment]
Closing in favor of #1348
