### ISSUE TITLE
Unable to install Jupyter extension within vscode

### ISSUE THREAD

**Issue by entgraceades** [microsoft/vscode-jupyter#13495]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I'm unable to successfully install the extensions onto my vscode version.

Initially when I try to install I get the error: Failed to install ms-toolsai.jupyter.
I've tried to download it manually using vsix however when I do the manually install after reloading I still am unable to access anything in the command palette. 

### VS Code Version

[Window Title] Visual Studio Code  [Main Instruction] Visual Studio Code  [Content]  Version 1.22.2 Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9 Date 2018-04-12T16:38:45.278Z Shell 1.7.12 Renderer 58.0.3029.110 Node 7.9.0 Architecture x64 

### Jupyter Extension Version

2023.5.1001341100

### Coding Language and Runtime Version

Python 3.10.9

### Anaconda Version (if applicable)

conda 23.3.1

### Running Jupyter locally or remotely?

N/A or Not sure

**Comment by amunger** [comment]
You'll need to update vscode to use the jupyter extension. Version 1.22.2 is very old.
Closing for now, let me know if that doesn't work
