### ISSUE TITLE
[FR] Manual kernel ID for connecting to an existing kernel session

### ISSUE THREAD

**Issue by NightMachinery** [microsoft/vscode-jupyter#13497]
I have started a Jupyter lab server:
```
jupyter lab --ip='0.0.0.0' --port='6035' --no-browser --notebook-dir=~/code
```

I then connect to this server using emacs-jupyter and create a kernel/session with the following connection file:
```
/home/x/.local/share/jupyter/runtime/kernel-c3a1494f-61c2-4c64-8c61-ac096278edae.json
```

I want to be able to connect to this session using VSCode. But the kernel chooser does not show this kernel. I want to manually give it the kernel ID.

Related:
- https://github.com/jupyterlab/jupyterlab/issues/14535

**Comment by DonJayamanne** [comment]
Thank you for the feature request, however this hasn't recieved any upvotes hence closing this issue.
