### ISSUE TITLE
Cannot render Julia's help document in VScode Jupyter Notebook

### ISSUE THREAD

**Issue by wybert** [microsoft/vscode-jupyter#13493]
I use VS Code Jupyter for Julia. `?sum` show below,

search: sum sum! summary cumsum cumsum! isnumeric VersionNumber issubnormal

ParseError: KaTeX parse error: No such environment: verbatim at position 7: \begin{̲v̲e̲r̲b̲a̲t̲i̲m̲}̲ sum(f, itr; [i…

Sum the results of calling function \texttt{f} on each element of \texttt{itr}.

The return type is \texttt{Int} for signed integers of less than system word size, and \texttt{UInt} for unsigned integers of less than system word size. For all other arguments, a common return type is found to which all arguments are promoted.

The value returned for empty \texttt{itr} can be specified by \texttt{init}. It must be the additive identity (i.e. zero) as it is unspecified whether \texttt{init} is used for non-empty collections.

ParseError: KaTeX parse error: No such environment: quote at position 7: \begin{̲q̲u̲o̲t̲e̲}̲ \textbf{compat…

\section{Examples}

ParseError: KaTeX parse error: No such environment: verbatim at position 7: \begin{̲v̲e̲r̲b̲a̲t̲i̲m̲}̲ julia> sum(abs…

Note the important difference between \texttt{sum(A)} and \texttt{reduce(+, A)} for arrays with small integer eltype:
ParseError: KaTeX parse error: No such environment: verbatim at position 7: \begin{̲v̲e̲r̲b̲a̲t̲i̲m̲}̲ julia> sum(Int…

In the former case, the integers are widened to system word size and therefore the result is 128. In the latter case, no such widening happens and integer overflow results in -128.

\rule{\textwidth}{1pt}

ParseError: KaTeX parse error: No such environment: verbatim at position 7: \begin{̲v̲e̲r̲b̲a̲t̲i̲m̲}̲ sum(itr; [init…

Returns the sum of all elements in a collection.
The return type is \texttt{Int} for signed integers of less than system word size, and \texttt{UInt} for unsigned integers of less than system word size. For all other arguments, a common return type is found to which all arguments are promoted.

The value returned for empty \texttt{itr} can be specified by \texttt{init}. It must be the additive identity (i.e. zero) as it is unspecified whether \texttt{init} is used for non-empty collections.

ParseError: KaTeX parse error: No such environment: quote at position 7: \begin{̲q̲u̲o̲t̲e̲}̲ \textbf{compat…

See also: \href{@ref}{\texttt{reduce}}, \href{@ref}{\texttt{mapreduce}}, \href{@ref}{\texttt{count}}, \href{@ref}{\texttt{union}}.

\section{Examples}\begin{verbatim} julia> sum(1:20) 210

julia> sum(1:20; init = 0.0) 210.0 \end{verbatim} \rule{\textwidth}{1pt}

ParseError: KaTeX parse error: No such environment: verbatim at position 7: \begin{̲v̲e̲r̲b̲a̲t̲i̲m̲}̲ sum(A::Abstrac…

Sum elements of an array over the given dimensions.
\section{Examples}\begin{verbatim} julia> A = [1 2; 3 4] 2×2 Matrix{Int64}: 1 2 3 4

julia> sum(A, dims=1) 1×2 Matrix{Int64}: 4 6

julia> sum(A, dims=2) 2×1 Matrix{Int64}: 3 7 \end{verbatim} \rule{\textwidth}{1pt}

ParseError: KaTeX parse error: No such environment: verbatim at position 7: \begin{̲v̲e̲r̲b̲a̲t̲i̲m̲}̲ sum(f, A::Abst…

Sum the results of calling function \texttt{f} on each element of an array over the given dimensions.
\section{Examples}\begin{verbatim} julia> A = [1 2; 3 4] 2×2 Matrix{Int64}: 1 2 3 4

julia> sum(abs2, A, dims=1) 1×2 Matrix{Int64}: 10 20

julia> sum(abs2, A, dims=2) 2×1 Matrix{Int64}: 5 25 \end{verbatim}

It's not rendered correctly.

**Comment by amunger** [comment]
I'm not able to get the `?` help command to run at all against a julia kernel - Are you just running `?sum` in a cell?
<img width="653" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/2019016/04b36ee0-a71d-45b8-9a27-bbbaf86da964">

**Comment by wybert** [comment]
@amunger. Yes, did you install Julia kernel? It's from my Jupyter support kernel, not Julia language Support kernels. 
![image](https://github.com/microsoft/vscode-jupyter/assets/5254627/fb98f24e-ffe0-44b0-bec4-fb3992d5f8b0)

From Julia language Support kernels in Julia 1.9.0. I have the same error as shown by you.

**Comment by wybert** [comment]
> @amunger. Yes, did you install Julia kernel? It's from my Jupyter support kernel, not Julia language Support kernels. ![image](https://user-images.githubusercontent.com/5254627/238078928-fb98f24e-ffe0-44b0-bec4-fb3992d5f8b0.png)
> 
> From Julia language Support kernels in Julia 1.9.0. I have the same error as shown by you.

![image](https://github.com/microsoft/vscode-jupyter/assets/5254627/6ce40185-6218-4fd7-8527-9b4ea7d39f40)

**Comment by xukai92** [comment]
i have the same issue with Julia 1.9.2

**Comment by amunger** [comment]
sorry, I'm still not able to run that `?sum` cell with the only kernel provided by the julia extension.
How are you installing the kernel, or can you just attach the resulting notebook to this issue? The raw json in the .ipynb should contain the output that is failing to render.

**Comment by xukai92** [comment]
i think can you do `@doc sum` as an alternative

**Comment by amunger** [comment]
got it, thanks.
One workaround is to switch the renderer to text/markdown:
<img width="682" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/2019016/6c98e80d-d893-4b7e-b057-f1cedf26c7e0">

**Comment by amunger** [comment]
the markdown renderer just has an issue with the section at top:

```
\begin{verbatim}
sum(f, itr; [init])
\end{verbatim}
```

**Comment by mjbvz** [comment]
See https://github.com/microsoft/vscode/issues/143801 and https://github.com/KaTeX/KaTeX/issues/1745
