### ISSUE TITLE
Plotly js backend is outdated with frontend

### ISSUE THREAD

**Issue by zhimin-z** [microsoft/vscode-jupyter#13491]
Type: <b>Bug</b>

I am a VSCode user and use plotly.py to plot figures, however, things become weird when I notice that the Javascript front and back end are different. Here is the original ticket for it: plotly/plotly.py#4181 and followup: https://github.com/microsoft/vscode/issues/181758

Extension version: 2023.8.0
VS Code version: Code 1.78.0 (Universal) (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:11:00.813Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No
Connection to 'ssh-remote+docjk-gpu-01' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 55f0327b-a019-48e1-a282-943c7eae9341|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+docjk-gpu-01' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30730053
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051

```

</details>

**Comment by DonJayamanne** [comment]
@zhimin-z are you still running into this.
I cannot repro this at my end.

**Comment by zhimin-z** [comment]
> @zhimin-z are you still running into this? I cannot repro this at my end.

It suddenly works on my side as well. I guess this is due to the update of the js backend:
![image](https://github.com/microsoft/vscode-jupyter/assets/8592144/78042051-ae3f-41a9-bd51-4b5d1727d523)
But I do not know what is broken there.
