### ISSUE TITLE
Shift tab to get documentation

### ISSUE THREAD

**Issue by jnandeepdevsarma** [microsoft/vscode-jupyter#13502]
Kindly implement the shift tab documentation shortcut to get documentation like original Jupiter notebook .

**Comment by amunger** [comment]
That feature is availalable in the [Jupyter power toys extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-powertoys) from this issue https://github.com/microsoft/vscode-jupyter/issues/1307

The language server also provides the Trigger Parameter Hints command, which might be what you're looking for - ctrl+shift+space by default.

**Comment by jnandeepdevsarma** [comment]
Thanks a lot for the information.
