### ISSUE TITLE
Notebook: Failed to start the Kernel on Insiders in a docker image

### ISSUE THREAD

**Issue by thomasaarholt** [microsoft/vscode-jupyter#13500]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual
Running any cell in a Notebook immediately triggers the following printed error:
<img width="1395" alt="image" src="https://github.com/microsoft/vscode-python/assets/2721423/8979388d-158c-4c74-a46a-c56943345700">

```
Failed to start the Kernel. 
Jupyter server crashed. Unable to connect. 
Error code from Jupyter: 1
/usr/local/lib/python3.10/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/fabrica/projects/dynamic-storage' instead of '"/fabrica/projects/dynamic-storage"' if you require traitlets >=5.
  warn(

[W 17:38:28.827 NotebookApp] Loading JupyterLab as a classic notebook (v6) extension.
[C 17:38:28.827 NotebookApp] You must use Jupyter Server v1 to load JupyterLab as notebook extension. You have v2.5.0 installed.
    You can fix this by executing:
        pip install -U "jupyter-server<2.0.0"
[C 17:38:28.827 NotebookApp] Running as root is not recommended. Use --allow-root to bypass. 
View Jupyter log for further details.
```
The full log when following "View Jupyter log for details" is:

```
17:41:33.476 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0949777d72b0d2535278d3dc13498b2535136f6dfe0678499012e853ee9abcab1./usr/local/python./usr/local/python.-m#ipykernel_launcher  (Python Path: /usr/local/bin/python, Unknown, 3.10.11) for 'Untitled-1.ipynb' (disableUI=false)
17:41:33.477 [info] Launching server
17:41:33.477 [info] Starting Notebook
17:41:33.479 [info] Generating custom default config at /tmp/1c0b63bf-05ca-4fd1-87b3-491687015ba3/jupyter_notebook_config.py
17:41:33.498 [info] Process Execution: /usr/local/bin/python -m jupyter notebook --no-browser --notebook-dir="/fabrica/projects/dynamic-storage" --config=/tmp/1c0b63bf-05ca-4fd1-87b3-491687015ba3/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
17:41:34.407 [error] Failed to start the Jupyter Server Error: Jupyter server crashed. Unable to connect. 
Error code from Jupyter: 1
/usr/local/lib/python3.10/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/fabrica/projects/dynamic-storage' instead of '"/fabrica/projects/dynamic-storage"' if you require traitlets >=5.
  warn(

[W 17:41:34.297 NotebookApp] Loading JupyterLab as a classic notebook (v6) extension.
[C 17:41:34.297 NotebookApp] You must use Jupyter Server v1 to load JupyterLab as notebook extension. You have v2.5.0 installed.
    You can fix this by executing:
        pip install -U "jupyter-server<2.0.0"

[C 17:41:34.297 NotebookApp] Running as <username> is not recommended. Use --allow-<username> to bypass.
    > at Jh.rejectStartPromise (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001341100-darwin-arm64/out/extension.node.js:17:124999)
    > interpreter = [object Object]
17:41:34.408 [warn] Error occurred while trying to start the kernel, options.disableUI=false Error: Jupyter server crashed. Unable to connect. 
Error code from Jupyter: 1
/usr/local/lib/python3.10/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/fabrica/projects/dynamic-storage' instead of '"/fabrica/projects/dynamic-storage"' if you require traitlets >=5.
  warn(
```

I believe the traitlets error is unrelated, but I cannot be 100% certain on this. 

## Steps to reproduce:

Install VSCode Insiders, install the Remote extension, and latest pre-release Python extension. Connect to a docker image running Python 3.10 in debian bullseye. (I realise this is ambigous. I can provide more details if desired).
Install the following requirements.txt python packages as `pip install -r requirements.txt`
[requirements.txt](https://github.com/microsoft/vscode-python/files/11472729/requirements.txt).

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.11
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

formatting
• provider: "black"
• blackArgs: "<placeholder>"

```

</p>
</details>

Extension version: 2023.9.11321009
VS Code version: Code - Insiders 1.79.0-insider (2575777b9d3cdb865d61f9f1dfaac1fea9e1bde6, 2023-05-12T05:24:44.544Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes
Remote OS version: Linux arm64 5.15.49-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|11, 10, 11|
|Memory (System)|32.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 4a8c06c2-0320-41c0-8941-8602c1cfce96|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container europe-docker.pkg.dev/nube-hub/docker/fabrica/dynamic-storage:4.0.14-thomas (dynamic-storage)|
|OS|Linux arm64 5.15.49-linuxkit|
|CPUs|unknown (6 x 0)|
|Memory (System)|15.61GB (11.87GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
vscrpc:30624061
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
azdwalk:30721579
pythonms35:30671666
cai9j608:30680470
57b77579:30687741
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showsbindicator:30724477
pythongtdpath:30726887

```

</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, 
I'm unable to repro this issue without the requirements.txt file
I just created a new virtual environment and installed via `python -m pip install jupyter jupyterlab notebook` and it worked.

I.e. the problem is with the versions of packages in your requirements.txt file.

**Comment by thomasaarholt** [comment]
Reason and fix found here: https://github.com/microsoft/vscode-jupyter/issues/13623
