### ISSUE TITLE
Arrow buttons stopped working

### ISSUE THREAD

**Issue by 3h4** [microsoft/vscode-jupyter#13514]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Arrow buttons stop working. After some development time, the arrow buttons stop working in a cell and I'm unable to navigate. Closing and opening the tab fixes the issue. This has happened several times.

### VS Code Version

Version: 1.78.1

### Jupyter Extension Version

v2023.4.1011241018

### Running Jupyter locally or remotely?

None

**Comment by Ar-Kareem** [comment]
Same thing constantly happens to me after updating to version 1.78.1

This makes notebooks almost unusable in vscode, which is sadly what I primarily work on.

For some reason the arrow keys work in some cells and permanently break in others.

Here's an example of the keyboard troubleshoot output for a broken cell where the arrow keys don't work
![image](https://github.com/microsoft/vscode-jupyter/assets/65195696/0b71c048-00b1-44e4-ba45-c962b711e417)

Here's an example of the keyboard troubleshoot output for a working cell
![image](https://github.com/microsoft/vscode-jupyter/assets/65195696/a8a99e97-8b9e-47aa-99c7-3ca66645bebe)

For some reason vscode thinks I'm in hover mode. I tried pressing ctrl+K then ctrl+I (even twice ctrl+I) like what some people suggested to exit hover mode but that didn't work. also tried ctrl+shift+P then `escape focus hover` but that didn't work either.

This is very frustrating.

**Comment by Ar-Kareem** [comment]
I finally found a fix!!!

Go to Keyboard Shortcuts (ctrl+shift+P then type `Preferences: Open Keyboard Shortcuts`)

Then search for `scroll hover` and unbind these four
![image](https://github.com/microsoft/vscode-jupyter/assets/65195696/e69cf32c-97b4-4989-a8dd-dc44be5c43e0)

and it fixed the issue for me!

I have no idea what hover mode is and at this point I'm just glad I don't have to care about it any longer.

**Comment by DonJayamanne** [comment]
I'm very sorry for missing this issue all these months.
Are you still running into these issues?

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
