### ISSUE TITLE
Unable to start Kernel 'base (Python 3.7.3)' due to connection timeout

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#13517]
From [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details):

> It does not work in vscode. Can't find solution. 'Unable to start Kernel 'base (Python 3.7.3)' due to connection timeout. '

Possibly related comment:

> To fix "kernel issue" you should install previous downgrade your python extension.

**Comment by yushaodong** [comment]
vscode: 1.78.2
![image](https://github.com/microsoft/vscode-jupyter/assets/34783871/7b6e174b-ec4b-45be-850d-13db02b1303c)

**Comment by yushaodong** [comment]
I found the solution. Using ipykernel will work. It is a local jupyter server.
