### ISSUE TITLE
Allow selecting Jupyter Server per Notebook or Interactive Window

### ISSUE THREAD

**Issue by syagev** [microsoft/vscode-jupyter#1352]
Would be useful for notebooks as well the interactive window to support being able to pick a server per notebook/interactive window session (like we allow picking kernels).

_Originally posted by @rchiodo in https://github.com/microsoft/vscode-python/issues/3104#issuecomment-655041391_

**Comment by IanMatthewHuff** [comment]
This is covered by the new insiders kernel picker work, but as that's just a prototype leaving the bug open until it rolls out.

**Comment by DonJayamanne** [comment]
This will be fixed with the new kernel picker
