### ISSUE TITLE
"Clear All Outputs" in Version Control Tab

### ISSUE THREAD

**Issue by kolibril13** [microsoft/vscode-jupyter#13524]
I often want to clear the notebook output before committing.
It would be amazing if there was a "Clear All Outputs" button in the version control diff viewer.
That way, one could still preview all the changes and see the new output, but it would also become possible to quickly remove the output in order to keep the git archive small. 
<img width="521" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/44469195/246b361d-ac10-4e80-9040-fd595ac5531d">

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, unfortunately there haven't been enough upvotes on this issue.
