### ISSUE TITLE
Jupyter Extension for VS Code does not show tables created by fastai learners

### ISSUE THREAD

**Issue by BellaCoola** [microsoft/vscode-jupyter#13528]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

[This Jupyter Notebook](https://github.com/fastai/fastbook/blob/master/01_intro.ipynb) is expected to show tables with epoch, train_loss, valid_loss, accuraccy, time etc. columns when `learn.fit_one_cycle()` and / or `learn.fine_tune()` is called, as seen [here](https://github.com/fastai/fastbook/blob/master/01_intro.ipynb):

![Screenshot from 2023-05-19 00-31-54](https://github.com/microsoft/vscode-jupyter/assets/31868524/299bc7f1-6032-4575-abfd-0a4ded1ba6c4)

However these tables are not shown when the same Jupyter Notebook is run in Jupyter Extension for VS Code:

![Screenshot from 2023-05-19 00-39-07](https://github.com/microsoft/vscode-jupyter/assets/31868524/46579bba-9c01-4d57-89f7-c661c663a2ef)

### VS Code Version

1.78.2

### Jupyter Extension Version

v2023.4.1011241018

### Coding Language and Runtime Version

Python 3.11.3

### Language Extension Version (if applicable)

v2023.8.0

### Running Jupyter locally or remotely?

Local

**Comment by gaoxianggithub** [comment]
me too
![image](https://gitee.com/shawn2gao/myimg/raw/master/2023-5-1913:50:30.png1684475429251.png)

**Comment by amunger** [comment]
can you provide a sample notebook to repro this scenario.

**Comment by amunger** [comment]
this seems to work when I open that notebook, unless the issue was from running the cell. In that case, could you post what the output of that cell is when it's not showing up? and if there is a plain text option if you select "change presentation" from the output menu?
