### ISSUE TITLE
Notebooks end up with `attachment` in cell attributes when it should not

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13522]
When I opened a notebook in vscode.dev and made a change, almost all cells had added "attachment" to the cell attributes. Not sure what was driving this.

**Comment by Yoyokrazy** [comment]
This is driven by the [notebookAttachmentCleaner](https://github.com/microsoft/vscode/blob/7f4221a9553c32f79a894da9a58cf5a2bbb69123/extensions/ipynb/src/notebookAttachmentCleaner.ts) most likely. It's what is responsible for upkeeping all of the base64 attachments stored behind the notebook. This was implemented last summer to support the attachment format the Jupyter uses to store images within the notebook. 

It should behave such that the cell attributes should only contain the attachment field after an image has been pasted in using that provider specifically (which is the default for jupyter iirc). Currently, the attachment field just isn't removed when there are no attachment style images within the cell, which causes cells to retain the field. 

I can look into tweaking that if we feel it's an issue. Is this causing any bigger issues or is it just an unexpected field to be seeing?

**Comment by DonJayamanne** [comment]
> Is this causing any bigger issues or is it just an unexpected field to be seeing?

The result would be users will end up seeing this in their SCM view every time when making a minor change to some other cell. i.e. this would result in unwanted changes to the notebook file and users have complained about that in the past.
Its not a breaking change, but one that will end up annoying users eventually.

**Comment by Yoyokrazy** [comment]
> All I did was edit a cell (just text, no images/pasting/etc)

@pamelafox thanks for the update! Yep, this will get taken care of next week. The intended behavior is that only cells with the images specifically stored as attachments will receive that field.

**Comment by amunger** [comment]
![Recording 2023-06-28 at 09 45 37](https://github.com/microsoft/vscode-jupyter/assets/2019016/6bc73903-a85a-4114-836d-d22a34ef3e0c)

**Comment by rebornix** [comment]
Verifier, please test with both `ipynb.pasteImagesAsAttachments.enabled` set to `true` and `false`.
