### ISSUE TITLE
Expose a hook to send a message as soon as a Kernel WebSocket is created

### ISSUE THREAD

**Issue by realDuang** [microsoft/vscode-jupyter#13532]
We are building an extension which using jupyter extension to connect remote kernel. Now we need to send some extra comm_msg to let server get more status to run extra task.
Could jupyter extension expose an API which can send some extra message actively after connecting to kernel?

Some further thoughts. We can expose a callback hook that fires every time a websocket message is returned. This allows the caller to actively send specific information through the received message.

Seems extension currently supports these capabilities. Could you consider exposing them?
```[tasklist]
### Tasks
```

**Comment by DonJayamanne** [comment]
API has been provided and confirmed to be working
