### ISSUE TITLE
Settings.json not updated when multiple workspaces open

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-jupyter#1353]
If multiple folders are open in an untitled workspace, selecting a new compute instance does not connect to that compute, instead it connects to the previously specified compute instance

**Comment by DavidKutu** [comment]
@shsuman, could you check if this still reproes on the newest version of the jupyter extension?

**Comment by DavidKutu** [comment]
Feel free to reopen this or create a new issue if its not fixed.
