### ISSUE TITLE
`Interactive Window: Always scroll on new cell` doesn't work with jupyter notebook cells started by `shift+enter`

### ISSUE THREAD

**Issue by wtdcode** [microsoft/vscode-jupyter#13536]
This is similar to #4475 and #11127. Looks like `Interactive Window: Always scroll on new cell` doesn't apply to cells started by `shift+enter`

## Environment data

- Vs Code version:

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 20.6.0
Sandboxed: Yes

-   Jupyter Extension version (available under the Extensions sidebar): v2023.4.1011241018
-   Python Extension version (available under the Extensions sidebar): v2023.8.0
-   Python and/or Anaconda version: 3.8.16
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Both pressing "running" button or using "control+enter" gives the expected behavior as shown:

![press](https://github.com/microsoft/vscode-jupyter/assets/30623163/cf5f6f9c-039e-47af-a277-3c5f42d831af)

## Actual behaviour

But pressing "shift+enter" gives the incorrect behavior:

![shiftenter](https://github.com/microsoft/vscode-jupyter/assets/30623163/8469154f-9dbd-411f-a42e-bce44576a1ed)

## Steps to reproduce:

- See above.

**Comment by amunger** [comment]
the notebook view is different than the interactive window, so that setting won't change anything for what you are attempting to do.

It sounds like you are looking for the configurability requested in [this issue](https://github.com/microsoft/vscode-jupyter/issues/12445)

Let me know if that's not the case

**Comment by wtdcode** [comment]
> the notebook view is different than the interactive window, so that setting won't change anything for what you are attempting to do.
> 
> It sounds like you are looking for the configurability requested in [this issue](https://github.com/microsoft/vscode-jupyter/issues/12445)
> 
> Let me know if that's not the case

I simply can't understand why `control+enter` works but `shift+enter` not while they are almost doing the same thing: running a cell.

**Comment by amunger** [comment]
They execute different commands - you could update your keyboard shortcuts to make only execute the command that you like though.

<img width="531" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/2019016/7c8e0816-702d-47af-aaa0-cd3afaaa1101">

**Comment by wtdcode** [comment]
> They execute different commands - you could update your keyboard shortcuts to make only execute the command that you like though.
> 
> <img alt="image" width="531" src="https://user-images.githubusercontent.com/2019016/239632188-7c8e0816-702d-47af-aaa0-cd3afaaa1101.png">

Oh, I got it. This perfectly solves my issue, thanks!

**Comment by BradNeuberg** [comment]
I'd like to vote to re-open this bug.

The default behavior of Jupyter Lab in the browser when Shift-Enter is pressed is to both execute the current cell and jump to the next cell, **without autoscrolling the window**

The fact that VS Code scrolls the window with this behavior means that the cell that just executed is constantly getting cut off, requiring manual scrolling up.

This behavior, execute then jump to next, is probably one of the most common things a data scientist does while working with a Jupyter Notebook.

Having to use Ctrl-Enter to execute just the current cell, then manually click to jump to the next cell, is maddening.

These kinds of UX quality of life things are very important for people in their code editors. I just made the jump to VS Code from Jupyter Lab in the browser and its driving me crazy.

My proposal: allow Shift-Enter to execute the current cell and select the next cell, __without__ also autoscrolling the VS Code window. This means Shift-Enter should respect "interactiveWindow.alwaysScrollOnNewCell".

Moving to Cntrl-Enter is not a suitable replacement.

**Comment by amunger** [comment]
The `interactiveWindow.alwaysScrollOnNewCell` setting is for the [interactive window](https://code.visualstudio.com/docs/python/jupyter-support-py) and does not effect notebooks. 
I agree that the current scroll on execute behavior is off, and that should get fixed as part of the other issue you commented on..

**Comment by vaniastankov** [comment]
I guess this one is still not fixed? It is not a big problem if the the cell execution result is comparatively small. However, whenever cell output is taking half or more of the screen, it becomes a real headache. Would love to see it fixed, but don't know if I can contribute in any useful way.
