### ISSUE TITLE
There is no way to wrap the text in the interactive window

### ISSUE THREAD

**Issue by pinkfrog9** [microsoft/vscode-jupyter#13539]
## Environment data

-   VS Code version: latest
-   Jupyter Extension version (available under the Extensions sidebar): v2023.4.1011241018
-   Python Extension version (available under the Extensions sidebar): v2023.8.0
-   OS (Windows | Mac | Linux distro) and version: latest
-   Python and/or Anaconda version: 3.10.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

Be able to wrap text in the interactive window

## Actual behaviour

Text are no way to be wrapped. For example, this image,
<img width="746" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/107285219/07f3e11b-3d07-4420-a986-98e9424b17d4">

Notice the horizontal scrollbar. I have to scroll it to see the remaining text.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by amunger** [comment]
the setting "notebook.output.wordWrap": true should do it

**Comment by pinkfrog9** [comment]
Thanks. It works.
