### ISSUE TITLE
Need to send comm_msg before jupyter connection done

### ISSUE THREAD

**Issue by realDuang** [microsoft/vscode-jupyter#13544]
We need to send some comm_msg to synchronize the additional connection information before connecting to jupyter server.

With the exposed capabilities of the existing jupyter extension, it seems that the connection handler will not be available until the connection is complete.

Is there a way to expose websocket handler earlier so that we can send comm_msg before excute_request type requests are sent?

I think there are some services that need to have the connection protocol set up before the first code execution. Is this feature request makes sense to you?

**Comment by DonJayamanne** [comment]
Closing this issue for now, had a discussion offline and believe this can be solved some other way.
