### ISSUE TITLE
Can the ports attributes provider use a selector?

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-jupyter#13553]
This extension registers a ports attributes provider so that ports that are listened on for the internal workings of the extension don't get picked up by automatic port forwarding when connected to a remote. ✅

Right now, the provider is registered with an empty selector, which means that VS Code will ask this extension for port attributes for each and every port that it automatically forwards. 

Is it feasible to use a selector when the ports attributes provider is registered here?

https://github.com/microsoft/vscode-jupyter/blob/cd19546c19ce54e61445f4b4090d111a248ecceb/src/kernels/portAttributeProvider.node.ts#L20-L21

I'm thinking about having an error if the selector is empty like this. The selector will result in a better experience for users as it will prevent extra trips to the extension host for ports that won't have attributes provided.

**Comment by DonJayamanne** [comment]
@alexr00 
The way this is works is
* We dynamically generate a few ports,
* The CLI is also dynamic
* Then we start a process based on the above CLI and port

Thus the suggestion i have is, 
* Just as we're about to start the new process, I can register port attributes provider using the above ports
* & when the above process dies, we can dispose the above provider.

I believe this will work, only difference from what we have today is that 
* we will end up dynamically registring/un-registring a few of these as kernels (process) are started and shutdown. Then again, I do not think thats an issue.

Please can you advice this approach works.

**Comment by alexr00** [comment]
@DonJayamanne I don't see a problem with that. If you find that it doesn't work then I will fix whatever bug that is uncovered.

**Comment by alexr00** [comment]
@DonJayamanne thanks for making this change! I will make the change in VS Code Insiders to start logging an error when an empty selector is passed. Then, next iteration I'll start throwing.

**Comment by DonJayamanne** [comment]
Apologies for not getting to this sooner
