### ISSUE TITLE
Add support for Highcharts for Python

### ISSUE THREAD

**Issue by romanb1337** [microsoft/vscode-jupyter#13556]
Hi!

Please, add support (or exception) for https://github.com/highcharts-for-python (at the moment Jupyter Notebook Renderers breaks Highcharts for Python)

**Comment by romanb1337** [comment]
@DonJayamanne Yes, sure https://raw.githubusercontent.com/highcharts-for-python/highcharts-for-python-demos/master/highcharts-core/column-and-bar-charts/basic-column.ipynb

**Comment by DonJayamanne** [comment]
Thank you for the sample, 
I've tested this in Jupyter Notebook as VS Code and they both fail with the exact same error message
Give that this does not work in Jupyter Notebook (I do not expect it to work in VS Code either), I'd suggest you file an issue in the Highcharts repo 

<img width="1098" alt="Screenshot 2023-05-25 at 15 50 58" src="https://github.com/microsoft/vscode-jupyter/assets/1948812/54a60173-6032-4d74-b408-aa0603f56a82">

**Comment by DonJayamanne** [comment]
Its already a known issue, see here https://github.com/highcharts-for-python/highcharts-core/issues/46
