### ISSUE TITLE
Dark Mode for AzureML widget is not supported well

### ISSUE THREAD

**Issue by AbeOmor** [microsoft/vscode-jupyter#1355]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Turn VSCode to Dark mode
2. Run a AzureML Juypter widget

## Actual behavior
![image](https://user-images.githubusercontent.com/9068012/91092651-336d8400-e60d-11ea-9a70-bbf58c287738.png)

## Expected behavior
Should be all dark

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local | Remote | N/A
-   **Extension version:** 20YY.MM.#####-xxx
-   **VS Code version:** #.##
-   **Setting python.jediEnabled:** true | false
-   **Setting python.languageServer:** Jedi | Microsoft | None
-   **Python and/or Anaconda version:** #.#.#
-   **OS:** Windows | Mac | Linux (distro):
-   **Virtual environment:** conda | venv | virtualenv | N/A | ...

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by DavidKutu** [comment]
This might be resolved with the new native notebook. @AbeOmor, please open a new issue if that's not the case.

**Comment by rchiodo** [comment]
@DavidKutu, Anoushka contacted me about this one. It's a bug in the Azure ML widget, not the extension.
