### ISSUE TITLE
Resume outputs from an a previously executing cell upload reloading VS Code

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13585]
Testing Show whether a remote kernel is busy when reconnecting after reload

Refs: #13276

- [x] anyOS @deepak1556
- [ ] web @bamurtaugh

Complexity: 3

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%231276%0A%0A&assignees=DonJayamanne)

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2313585%0A%0A&assignees=DonJayamanne)

---

#### Desktop
- Have a python environment installed
- Have latest VSCode Insiders installed
- Have latest Jupyter and Python pre-release extension installed

#### Web
- Have a python environment installed and setup with Jupyter on your desktop
- Run jupyter with the following command line 
  `python -m jupyter notebook --no-browser --NotebookApp.allow_origin='*'`  
  Note the URL it generates for connecting
  [See herefor more information on setting up Jupyter](https://github.com/microsoft/vscode-jupyter/wiki/Install-and-Setup-Jupyter-Notebook-Lab-for-Testing)  
- Start insiders.vscode.dev
- Make sure Jupyter prerelease extension is installed
- Open a notebook and connect to the above Jupyter server via the Kernel Picker

### Steps for DeskTop/Web
* Open a notebook (or create a new Jupyter notebook using the command `Create: New Jupyter Notebook`)
* Open a notebook and connect to the above Jupyter server via the Kernel Picker (`Select Another Source -> Existing Jupyter Server`)
* Attempt to run a Python cell with the code `print("Hello World")` and verify the output is displayed
* Save the notebook
* Run a cell with the following code
```python
import time
for i in range(200):
    time.sleep(1)
    print(i)
```
* Run the above cell, and verify you can see some of the output starting from 1, 2...
* Reload VS Code
* After reloading, the notebook will be opened and the same kernel will be selected
* A few seconds later you should see the toolbar with the icon `Interrupt` displayed on the top
* [ ] Verify the `Interrupt` icon is dispalyed in the toolbar
* [ ] Verify the `Run All` icon is NOT dispalyed in the toolbar
* [ ] Click on the `Interrupt`button and verify you can now run the previous `print("Hello World")` cell and it runs to completion
* Now create a cell with the following code
```python
import time
for i in range(300):
    time.sleep(1)
    print(i)
```
* Run the above cell , and verify you can see some of the output starting from 1, 2...
* Reload VS Code (or Exit VS Code completely & restart VS Code)
* After reloading, the notebook will be opened and the same kernel will be selected
* A few seconds later you should see the new output from the counter, e.g. 1.2....8,9,10,11....

**Comment by bamurtaugh** [comment]
`python -m jupyter notebook --no-browser --NotebookApp.allow_origin='*'` fails for me, so I adjusted it to `python -m notebook --no-browser --NotebookApp.allow_origin='*'` - @DonJayamanne let me know if that's alright/expected.

**Comment by bamurtaugh** [comment]
Thanks so much @DonJayamanne for taking the time to unblock my Jupyter setup (and @rebornix for your help earlier)! This is now working great and really cool to see.
