### ISSUE TITLE
HTML escaped dictionary cannot open in the data viewer

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1359]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Debug a file with this code

```python
import numpy as np
import pandas as pd
from pandas import Series
dict2 = {'a> <a href="bobs"/>':[1, 2, 3], '<b':[4, 5, 6]} 
df6 = pd.DataFrame.from_dict(dict2) 
print(df6) # Set breakpoint here
```
2. Attempt to view the df6 or dict2 in the data viewer 

## Actual behavior
Error parsing json

## Expected behavior
Viewer opens

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local | Remote | N/A
-   **Extension version:** 20YY.MM.#####-xxx
-   **VS Code version:** #.##
-   **Setting python.jediEnabled:** true | false
-   **Setting python.languageServer:** Jedi | Microsoft | None
-   **Python and/or Anaconda version:** #.#.#
-   **OS:** Windows | Mac | Linux (distro):
-   **Virtual environment:** conda | venv | virtualenv | N/A | ...

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by joyceerhl** [comment]
We should be able to close this. IIRC we used the `rawString` property on custom evaluate requests to ensure the debugger doesn't send us escaped strings.
