### ISSUE TITLE
What is a Jupyter Server for Testing?

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-jupyter#13599]
Testing #13585

When I choose "Select kernel," I see 2 options:
![image](https://github.com/microsoft/vscode-jupyter/assets/25310137/6ea86b91-8e52-4a77-9370-ede5d9255fd4)

I'm unsure what a Jupyter Server for Testing is, so I click the (i) to go to docs. I'm brought to https://code.visualstudio.com/docs/datascience/jupyter-kernel-management#_existing-jupyter-server. This section doesn't really answer my question. When I ctrl+f the whole doc, I also don't get any results.

cc @minsa110 for the docs aspect too

**Comment by DonJayamanne** [comment]
@bamurtaugh thats a bug I will remove that, it should only show up during testing.
