### ISSUE TITLE
Open With allows using the custom editor even when it's not supported.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1360]
Use the 'Open With' menu
These options show up:

![image](https://user-images.githubusercontent.com/19672699/94291985-32cc5400-ff11-11ea-9ab6-97f15a0760af.png)

If you pick the first one on insiders it will just fail.
If you pick the second one on stable it will just fail.

We either need a way to remove these or put up a warning or switch over to the one that works when that occurs.

**Comment by rchiodo** [comment]
I believe this is already fixed

**Comment by IanMatthewHuff** [comment]
Validated. At least it's validated with a warning for both scenarios now. Wonder if we lost some history on this? I seem to recall already validating this before.
