### ISSUE TITLE
Prompted to save changes after selecting a kernel

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-jupyter#13600]
Testing #13585

After I select a remote kernel, I'm prompted to save changes to my project:

![image](https://github.com/microsoft/vscode-jupyter/assets/25310137/a7bcabb1-9649-42d7-a218-6aa5807c0b75)

This wasn't expected - all I've changed is my Jupyter config, not any content in my files.

**Comment by DonJayamanne** [comment]
@bamurtaugh Please could you provide some instructions to replicate this issue.
At what point did you get prompted to save the notebook? Did you attempt to close the notebook or browser or other.
Or was is just as descrived, you select a kernel and then you get the prompt

**Comment by bamurtaugh** [comment]
@DonJayamanne it was just as described - I selected a kernel and then got the prompt.

**Comment by DonJayamanne** [comment]
I suspect its auto save kicking in then, please could you try disabling auto save, and try again.

**Comment by bamurtaugh** [comment]
I can't repro, so closing! Will reopen if I observe again. Maybe that notebook had some change from long ago that only got triggered when I happened to change kernels once or twice.
