### ISSUE TITLE
Stuck "Detecting Kernels" after reload, can't reconnect to kernel

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-jupyter#13602]
Testing #13585

Followed the steps from the TPI:

> Run a cell with the following code
> import time
> for i in range(200):
>     time.sleep(1)
>     print(i)
> Run the above cell, and verify you can see some of the output starting from 1, 2...
> Reload VS Code
> After reloading, the notebook will be opened and the same kernel will be selected

But after reloading, my notebook is stuck "Detecting Kernels:"

![image](https://github.com/microsoft/vscode-jupyter/assets/25310137/422d0adb-fa1a-499e-a3a6-d2e84fa80dea)

I verified in a browser that the Jupyter server is still running:
![image](https://github.com/microsoft/vscode-jupyter/assets/25310137/251aa9ca-0298-401b-93c6-14a97669f4f1)

**Comment by bamurtaugh** [comment]
If I go through kernel selection again, I can't connect to the remote kernel:

![image](https://github.com/microsoft/vscode-jupyter/assets/25310137/0103836c-3fe9-4083-9f90-76a8348f0072)

**Comment by bamurtaugh** [comment]
I was able to try to continue testing by creating an entirely new Codespace, launching jupyter within it, and adding that new codespace as a remote kernel.

But upon a reload, insiders.vscode.dev was still stuck trying to connect. I tried creating a 3rd new Codespace and repeating the connection process, and now I can't connect even to begin with:

![image](https://github.com/microsoft/vscode-jupyter/assets/25310137/06021971-42f8-4086-8434-c0e6c913d908)

cc @rebornix who helped me connect a remote Codespace kernel to begin with for awareness and in case I'm missing anything.

**Comment by DonJayamanne** [comment]
> upyter server from Codespaces changed to a private port. I made the port public again, but I still get the same error message "Unable to connect to the remote server."

This could be the problem, 
This isn't a valid use case, 
Will chat with @rebornix about this.

**Comment by DonJayamanne** [comment]
Closing as this has been resolved.
Using code spaces and re-mapping ports it not a valid user case.
