### ISSUE TITLE
"Unhandled error" when I try to run code

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-jupyter#13601]
Testing #13585

I tried to run "Hello World" in my Jupyter notebook connected to a remote kernel, and I received the following:

![image](https://github.com/microsoft/vscode-jupyter/assets/25310137/66cbc8f9-0d69-4ddc-b5ee-4ad53ae103f3)

The kernel seems valid when I "Select a different kernel:"
![image](https://github.com/microsoft/vscode-jupyter/assets/25310137/073961a2-4b07-4059-904a-77c986f68a24)

![image](https://github.com/microsoft/vscode-jupyter/assets/25310137/67694fb8-b3ed-4663-9979-21fbbfade884)

**Comment by bamurtaugh** [comment]
I can also verify the URL I'm using loads in the browser:

![image](https://github.com/microsoft/vscode-jupyter/assets/25310137/efb62645-4a52-4e63-a177-f2a83270c527)

**Comment by bamurtaugh** [comment]
@rebornix helped me a ton by helping me set up a Codespace as my environment, as I couldn't get my local one working and kept seeing this error if I tried a local kernel.

**Comment by bamurtaugh** [comment]
With my now working local Jupyter setup, I no longer see this error! But leaving open since the error message `Unhandled error` was vague.

**Comment by DonJayamanne** [comment]
@bamurtaugh I think the problem was because your Python environment was busted, if this problem still exists with the new Virtual Environment we created in the `temp` folder, please do re-open this, however I suspect this was due to the old python env.
