### ISSUE TITLE
Pressing up-arrow copies last command, but doesn't move caret to end of line

### ISSUE THREAD

**Issue by geajack** [microsoft/vscode-jupyter#13617]
## Environment data

-   VS Code version: 1.78.2
-   Jupyter Extension version (available under the Extensions sidebar): v2023.4.1011241018
-   Python Extension version (available under the Extensions sidebar): v2023.8.0
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 22.04
-   Python and/or Anaconda version: 3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: local

## Description

If I create an interactive window in VS Code by say using the "Create interactive window" command in the command palette, and within that interactive window I press the Up arrow to get my last used command, the command correctly appears in my input field, but the caret is at the *beginning* of the line and not the end. Because every other terminal-type app I've ever used automatically moves the caret to the end, if I want to add something to the command I instinctively just start typing, but end up just prepending garbage to the command.

**Comment by amunger** [comment]
yeah, a separate dedicated command might be the way to go here and would probably also take care of https://github.com/microsoft/vscode-jupyter/issues/11657

**Comment by amunger** [comment]
There haven't been enough votes or consensus for exactly how to do this, but you can actually just set this up yourself by editing the keybindings.json file and adding something like:

```
  {
    "key": "ctrl+shift+up",
    "command": "runCommands",
    "when": "isCompositeNotebook && !notebookEditorFocused && !suggestWidgetVisible",
    "args": {
        "commands": [
            "interactive.history.previous",
            "cursorBottom"
        ]
    }
  },
  {
    "key": "ctrl+shift+down",
    "command": "runCommands",
    "when": "isCompositeNotebook && !notebookEditorFocused && !suggestWidgetVisible",
    "args": {
        "commands": [
            "interactive.history.next",
            "cursorTop"
        ]
    }
  },
```

you may also want to remove default keybindings for `interactive.history.previous`/`next` by just deleting them in the keyboard shortcuts UI
