### ISSUE TITLE
2nd figure in the same cell in notebooks cut  after reloading file in VSCode Insiders

### ISSUE THREAD

**Issue by danieltomasz** [microsoft/vscode-jupyter#13618]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When I execute code that plot in the notebook everythink in fine (I use standard matplotlib backend)
I create new notebook
and place into cell
```
import matplotlib.pyplot as plt
import numpy as np

# Data for plotting
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, ax = plt.subplots()
ax.plot(t, s)

ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()

fig.savefig("test.png")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Data for plotting
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, ax = plt.subplots()
ax.plot(t, s)

ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()

fig.savefig("test.png")
plt.show()
```

This render first time 2 plots ok, but after moving to other file and back the seconnd figure in the output is cut out (as you see  in the screenshot, sometimes this happens only after reloading the VSCode window  and not moving between different files, but closing and opening the file is enough for this effect to occur)
![image](https://github.com/microsoft/vscode-jupyter/assets/7980381/636fe877-ae13-4f81-bc44-bcc884548c39)

Or even worse as it here
![image](https://github.com/microsoft/vscode-jupyter/assets/7980381/dfd04c07-cd31-44c4-87df-97f102d1bb23)

If only one figure is in the output, this is rendered ok
The stable Vscode doesnt have this problem

### VS Code Version

Version: 1.79.0-insider Commit: fa8eefda18bf099d82b58453f8fe5d3010196fa0 Date: 2023-05-31T03:10:55.044Z Electron: 22.5.4 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Darwin arm64 22.5.0

### Jupyter Extension Version

v2023.4.1011241018

### Coding Language and Runtime Version

Python 3.11

### Language Extension Version (if applicable)

standard

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
I'm very sorry for not getting back to you on this issue.
Are you still running into this issue, please do let me know as we'd like to get you unblocked.

**Comment by danieltomasz** [comment]
Hi, some time ago I switched back to stable, maybe in meantime the error was solved, I am closing this issue now
