### ISSUE TITLE
All the kernel is gone

### ISSUE THREAD

**Issue by jarrycf** [microsoft/vscode-jupyter#13621]
<img width="899" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/92665982/d8fe01eb-e930-4384-99a7-11a3c2c8c370">
when I selection cmd+shift+p and notebook.clearNotebookKernelsMRUCache All the kernel is gone. How do I recover

**Comment by rebornix** [comment]
@jarrycf sorry for reaching out late, can you try latest VS Code and try if you can reproduce?
