### ISSUE TITLE
Expose API for a custom variable viewer

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode-jupyter#13626]
Currently, it is possible to view data frame variable values in data viewer as follows:
![image](https://github.com/microsoft/vscode-jupyter/assets/8560030/21dcecba-8d34-406b-8432-d205c1b75d0f)

It would be great to support extensibility for us to launch in other viewers such as Data Wrangler as well.
See https://github.com/microsoft/vscode-data-wrangler/issues/49

**Comment by amunger** [comment]
This should now be possible with a core contribution https://github.com/microsoft/vscode-data-wrangler/issues/131. But we can re-visit if that doesn't work out for some reason.
