### ISSUE TITLE
Installation of Visual Studio broke the efficiency in Visual Code to auto select Python kernels for Jupyter Notebook 

### ISSUE THREAD

**Issue by Tirbo06** [microsoft/vscode-jupyter#13624]
## Environment data

-   VS Code version: 1.78.2 (user)
-   Jupyter Extension version (available under the Extensions sidebar): v2023.4.1011241018
-   Python Extension version (available under the Extensions sidebar): 3.10.6
-   OS (Windows | Mac | Linux distro) and version: Win 10
-   Jupyter server running: Local 

Dear team,

So as I need to run Tensorflow on my GPU i had to install _Nvidia CUDA Tools kit_ that "recommend" to have **Microsoft Visual STUDIO** installed. I execute and make a minimal installation with the Python component, then install _CUDA_, then install _CudaNN._

As soon as i relaunch my regular **Microsoft Visual CODE,** Jupyter notebook start to fetch for kernels (it wasn't doing it before), take a lot of time and don't respond when i try to add it via mouse click (click on "Detecting kernel", wait until it auto-finds a kernel, and finally i can click on it, wich is useless because the notebook just auto-selected it).

I am not sure if GPU computing via **TF** requires **Microsoft Visual STUDIO** and I am suspecting _Windows APPS_ to be faulty by adding its own python distributions as "_APPS_" and then confusing the kernel selection. 

I use regular Python distributions, installed  `C:\Python` and most of the time i do not use virtualenv.

## I have tried the following:
- Uninstalled Microsoft Visual STUDIO
- Uninstalled Microsoft Python APPs
- Set the path of the python interpreter in Settings.json in VSCode

Still did not resolved the issue. How can i fix this ? Thanks

### Expected behaviour
- Launch VSCode with a jupyter file already openned
- Directly run the jupyter file
Works like it used to and does not take time to find and select a kernel.

## Actual behaviour
- Launch VSCode with a jupyter file already openned
- Directly run the jupyter file
- Does not run jupyter file as it searchs for a kernel

## Steps to reproduce:
- Launch VSCode with a jupyter file already openned
- Directly run the jupyter file
- Close VSCode
- Install Visual Studio
- Launch VSCode with a jupyter file already openned
- See difference

**Comment by Tirbo06** [comment]
![image](https://github.com/microsoft/vscode-jupyter/assets/59821431/01464756-8235-4983-8714-926e1ebd2f54)

**Comment by DonJayamanne** [comment]
Do the list of python environments appear in the python interpreter picker?
Use the command ‘Python : Select Python Environment ‘ to get that list

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
