### ISSUE TITLE
Export uses the wrong interpreter to perform the export

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1363]
It defaults to using the 'jupyter interpreter' instead of using the user's interpreter. This makes it impossible for the user to diagnose errors as the errors don't match what their current interpreter might report.

See this issue:
microsoft/vscode-jupyter#710

**Comment by greazer** [comment]
Keeping this as must-fix since #710 is affecting many users. We closed that bug in the python repo prior to opening the jupyter repo.

**Comment by IanMatthewHuff** [comment]
@greazer Hang on a second. I think that I already fixed this. Did this maybe get moved over from a completed pipeline?

**Comment by IanMatthewHuff** [comment]
Yeah, this was fixed.

It was this PR here in python: https://github.com/microsoft/vscode-python/pull/14308
And this one in Jupyter: https://github.com/microsoft/vscode-jupyter/pull/181

**Comment by rchiodo** [comment]
This doesn't seem to be fixed?

Repro steps:

1) Open notebook
2) Switch kernel to new env
3) Install nbconvert in new env
4) Run export

It uses the selected interpreter instead?

Looking at the callstack, I'm not sure how it would ever get passed a candidate interpreter.

**Comment by IanMatthewHuff** [comment]
@rchiodo  are you using the command from the palette Jupyter: Export to HTML? Realized that I fixed this working with the ExportAs button, which does pass and use a candidate interpreter. Pretty sure that I didn't look at the palette commands. Will probably have to make an additional fix for them.

**Comment by rchiodo** [comment]
I used the export button at the top of a native notebook.

**Comment by joyceerhl** [comment]
Validated.
