### ISSUE TITLE
Testi kuvaaja

### ISSUE THREAD

**Issue by Tapu87** [microsoft/vscode-jupyter#13638]
import matplotlib.pyplot as plt

# Tiedot
kokonaismyynti = 103060.27
mainosmyynti = 69793.28
mainosbudjetti = 3304.79
budjetin_kasvu_prosentti = 20
mainostuotto_kerroin = 21.1

# Kuukaudet
kuukaudet = ['Tammikuu', 'Helmikuu', 'Maaliskuu', 'Huhtikuu', 'Toukokuu', 'Kesäkuu']

# Myynnin arvot
myynti = [kokonaismyynti] * len(kuukaudet)
mainosmyynti = [mainosmyynti * mainostuotto_kerroin] * len(kuukaudet)

# Budjetin kasvu
uusi_budjetti = mainosbudjetti * (1 + budjetin_kasvu_prosentti / 100)
budjetti_kasvu = uusi_budjetti - mainosbudjetti

# Kuvaaja
plt.plot(kuukaudet, myynti, 'b', label='Kokonaismyynti')
plt.plot(kuukaudet, mainosmyynti, 'r', label='Mainosmyynti')
plt.title('')
plt.xlabel('Kuukausi')
plt.ylabel('Myynti (€)')
plt.legend()

# Budjetin kasvun merkintä
plt.text(kuukaudet[-1], mainosmyynti[-1], f"Budjetin kasvu: {budjetti_kasvu:.2f} €")

plt.show()

**Comment by amunger** [comment]
is there a problem that you are seeing running this notebook in vs code?
