### ISSUE TITLE
Interactive window doesn't respect `editor.cursorBlinking` setting

### ISSUE THREAD

**Issue by kryptan** [microsoft/vscode-jupyter#13645]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Disable cursor blinking:

    "editor.cursorBlinking": "solid"

This setting is respected almost everywhere including Jupyter notebooks but not in the input box inside the interactive window. Cursor is still blinking there.

Not sure if this is VSCode or extension bug.

Related:
https://github.com/microsoft/vscode/issues/131941
https://github.com/microsoft/vscode/pull/168217
https://github.com/microsoft/vscode/issues/180429

### VS Code Version

Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

### Jupyter Extension Version

v2023.4.1011241018

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
seems to be fixed now
