### ISSUE TITLE
Plotly Graph having hyperlinks does not work in VS Code but works in Jupyter Notebook

### ISSUE THREAD

**Issue by hjain5164** [microsoft/vscode-jupyter#13659]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I have created a plotly graph having a title text. The title text contains <a> HTML element so that if someone clicks on the title, they will be redirected to a web page. The title text is not clickable, and nothing happens when I click on it in VS Code. But it seems to work in Jupyter Notebook. Below is the sample graph:

<img width="878" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/20479605/2cf8bf07-8a06-44a4-b10b-29b31c8463ee">

The text (i) highlighted with yellow color is a hyperlink, but it does not open up the browser window and redirect to this URL.

Below is the code which I used:

```
figure = go.Figure()
figure.add_trace(go.Scatter(x = result['Text Length'], y = result['Average Words Per Sentence'], mode='markers'))
figure.update_layout(title = {'text': 'Text Length<sup><a href =""https://plotly.com/chart-studio-help/adding-HTML-and-links-to-charts/#step-2-the-essentials>(i)</a></sup><br><sup>A small description</sup>', 'x': 0.5, 'xanchor': 'center'})
figure.update_layout( xaxis = dict(title = 'Text Length<a href =""https://plotly.com/chart-studio-help/adding-HTML-and-links-to-charts/#step-2-the-essentials>(i)</a>', automargin = True))
```

### VS Code Version

1.78.2

### Jupyter Extension Version

v2023.4.1011241018

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thank you for filing this issue and sorry you are running into this.
Please could you try this in Jupyter Lab and let me know whether it works

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
