### ISSUE TITLE
All kernels say 'ipython kernel' when starting

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1365]
Open a julia notebook
Start the kernel

It says 'Starting IPython kernel'

**Comment by DonJayamanne** [comment]
I believe this has already been done.
Moving to validate.

**Comment by IanMatthewHuff** [comment]
Validated. 
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/45cf8173-0795-46f1-ae0a-66c16f9bd365)
