### ISSUE TITLE
Missing option to convert Python script to Jupyter notebook.

### ISSUE THREAD

**Issue by xquyvu** [microsoft/vscode-jupyter#13665]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
Version: 1.78.2 (Universal)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z
```
- OS Version: `Darwin arm64 22.2.0`

Steps to Reproduce:

1. Open the command palette (Cmd + Shift + P)
2. Type 'Export'

![image](https://github.com/microsoft/vscode/assets/40758906/45e4c5b2-f828-4aa7-b02f-8abd7a8d38a6)

I'm just following the instruction [here](https://code.visualstudio.com/docs/python/jupyter-support-py#_export-a-jupyter-notebook). This option existed in previous versions of VSCode but it's now missing.

**Comment by DonJayamanne** [comment]
@xquyvu Thank you for filing this issue, looks like the Jupyter extension is either not installed or has failed to activate.
Please could you check your developer logs to see whether the extension has failed to activate
* Open the command palette and select the command `Toggle Developer Tools` 
* Check if there are any errors there.

**Comment by DonJayamanne** [comment]
Thank you
 Please could you open a python file and then  check the logs again

**Comment by xquyvu** [comment]
I've just tried again now:
![image](https://github.com/microsoft/vscode-jupyter/assets/40758906/1d304b99-3065-4c16-b911-43ca87146a10)


Oh and it seems I can convert notebooks to python scripts just fine.
![image](https://github.com/microsoft/vscode-jupyter/assets/40758906/64da7363-e020-4519-a92a-3f3dd4c9a1a5)

**Comment by DonJayamanne** [comment]
Thank you for getting back to us
Will close this issue as it’s resolved 
Please feel free to create a new issue if you run into other issues

**Comment by xquyvu** [comment]
Sorry it's not resolved. I can convert notebooks to python scripts, but not the other way around 😬
