### ISSUE TITLE
Allow configuration of cell debugger

### ISSUE THREAD

**Issue by matthiasgeihs** [microsoft/vscode-jupyter#13676]
In some cases (e.g., https://github.com/microsoft/debugpy/issues/1166#issuecomment-1374221154) it would be useful if we could configure the cell debugger. For example, in the case pointed out above, it would be nice if we could set `"subProcess": false` for preventing the debugger from crashing (as it currently does not support subprocess debugging).

**Comment by roblourens** [comment]
That issue will be fixed. Is that what this is about or is there anythign else you are asking to configure?

**Comment by matthiasgeihs** [comment]
Mainly about this issue, but I imagine there may be other cases where configuration of the cell debugger might be useful.

**Comment by roblourens** [comment]
I don't think I can tackle this without a concrete use case, I will get to the subprocess issue as soon as I'm able though
