### ISSUE TITLE
Interrupt button in interactive window gone in v2023.8.0

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode-jupyter#13673]
Type: <b>Bug</b>

In the Python interactive window, there used to be an "interrupt" button on the toolbar for interrupting the currently-running cell. as of v2023.8.0, this button is no longer available, making it difficult to work with Python code interactively without constantly restarting the kernel. Why was this button taken away, and can we have it back?

<img width="675" alt="Screenshot 2023-06-07 at 9 18 16 PM" src="https://github.com/microsoft/vscode-python/assets/81476/4d60ab4e-0173-4110-8cbb-7aed1981ac6f">

Extension version: 2023.8.0
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T15:00:40.428Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.4.0-1105-gcp
Remote OS version: Linux x64 4.15.0-1098-gcp

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|64.00GB (23.15GB free)|
|Process Argv|--crash-reporter-id 57711574-f0db-4702-a245-8b56bbeb7d3a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ProdCPU-10|
|OS|Linux x64 5.4.0-1105-gcp|
|CPUs|Intel(R) Xeon(R) CPU @ 2.60GHz (128 x 2600)|
|Memory (System)|503.87GB (484.56GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: A100|
|OS|Linux x64 4.15.0-1098-gcp|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (12 x 2200)|
|Memory (System)|83.58GB (79.69GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixhidewlkth:30730051
showsbindicator:30760979
pythongtdpathcf:30739705
pythonnosmt12:30757131

```

</details>

**Comment by silaskoemen** [comment]
Same issue for me. Whenever I run Python code in the interactive window, at first the Interrupt button exists but after a while it disappears and to interrupt something you have to restart the kernel, losing all variables created.

I thought it had something to do with whether you run code from the .py file with Shift+Enter vs pasting it into the Interactive Window, but that is not the case. Another thought was that you could only interrupt some kind of loop running, but the button also vanished while running loops.

Any help is appreciated

**Comment by rebornix** [comment]
@amunger I'm not sure if it's because we stopped contributing the interrupt button and depends on the core to handle it. Thinking about it again, IW might be different from notebook. In notebook we either show "Run" or "Interrupt" while in IW, we don't have a Run button (as it's a request from python file) but we might want to keep Interrupt there.

**Comment by amunger** [comment]
The expected behavior change was that the interrupt button only shows up when a cell is running, the same as notebooks since it's coming from core.

I can get this to repro this issue if I execute something in a window that isn't currently visible. After focusing on the IW again, the interrupt button no longer appears at all (or never goes away if I hide the window while a cell completes). Very strange that it would be disabled permanently, but that's likely where we need to look

**Comment by amunger** [comment]
as a workaround, you should be able to run the command `jupyter.interruptkernel`, although I think you need focus to be on the interactive window

**Comment by amunger** [comment]
verification:
open a python file and run a cell in the interactive window

```
# %%
import time
for i in range(10):
    time.sleep(1)
    print(i)
```

interrupt button should be visible while the code is running

hide the interactive window by opening another editor within the group, run the cell again without showing the IW.
interrupt button should still show while code is running when the IW is shown again, and hide when code completes.
