### ISSUE TITLE
Missing option to convert Python script to Jupyter notebook

### ISSUE THREAD

**Issue by xquyvu** [microsoft/vscode-jupyter#13674]
Re-raising this issue because it was incorrectly marked as resolved

https://github.com/microsoft/vscode-jupyter/issues/13665

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
Version: 1.78.2 (Universal)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z
```
- OS Version: `Darwin arm64 22.2.0`

Steps to Reproduce:

1. Open the command palette (Cmd + Shift + P)
2. Type 'Export'

![image](https://github.com/microsoft/vscode/assets/40758906/45e4c5b2-f828-4aa7-b02f-8abd7a8d38a6)

I'm just following the instruction [here](https://code.visualstudio.com/docs/python/jupyter-support-py#_export-a-jupyter-notebook). This option existed in previous versions of VSCode but it's now missing.

I can convert notebooks to python scripts, but not the other way around.

**Comment by xquyvu** [comment]
@rebornix Could you have a look when you've got a chance? Thanks!

**Comment by xquyvu** [comment]
Ok I've figured it out. The option is only open when you have `# %%` anywhere in the file which marks the beginning of a notebook cell.

![image](https://github.com/microsoft/vscode-jupyter/assets/40758906/37983417-52fb-4580-9981-bff06ae2f1b5)

However, in the previous versions of VSCode, that was not required.

**Comment by rebornix** [comment]
We haven't updated the context keys for more than a year, not sure how this gets regressed. With that said, I think we can relax the context key a bit.
