### ISSUE TITLE
Can't change remote Jupyter server without restarting VS Code

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#1367]
Issue Type: <b>Bug</b>

After one of the recent updates, I can no longer change the remote Jupyter server without restarting VS Code.  I used to be able to simply comment out the remote and local Jupyter  `python.dataScience.jupyterServerURI`s that I was not using and un-comment the one that I wanted to use and after closing the VS Code Python notebook pane everything would switch just fine.  Now after changing the `python.dataScience.jupyterServerURI` it is only recognized after I restart VS Code.

Is there a way to get back the old behavior?  It was much more convenient. 

```
	"settings":  {
		// local
		// "python.dataScience.jupyterServerURI":  "local"
		// Remote # 1
		// "python.dataScience.jupyterServerURI": "http://100.100.100.001:8888/?token=*******************"
		// Remote # 2
		"python.dataScience.jupyterServerURI": "http://100.100.100.002:8888/?token=*******************"
	 }
```

Extension version: 2020.9.114305
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.36GB free)|
|Process Argv|--crash-reporter-id f652528b-5678-4b12-9ca0-3de6b1e1135f|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by StarryFire** [comment]
This is a problem since I am trying to connect VSCode which is running inside a container...and in the same container my instance of jupyter server is also running and hence it never ends up connecting since the token changes on every restart.

**Comment by sanzgiri** [comment]
On the latest windows insider build (or stable build as of 11/12/2021) - when I try to connect to a remote jupyter server: I get a popup window that says "Please reload VS Code when changing the Jupyter Server connection." But after reloading (or not) the connection is never completed.

**Comment by DonJayamanne** [comment]
> after reloading (or not) the connection is never completed.

Please could you file a separate bug for this and I'll look into that

**Comment by DonJayamanne** [comment]
> problem since I am trying to connect VSCode which is running inside a container...and in the same

I'm sorry to hear just out of curiosity, why aren't you running directly for within vscode instead of starting a Jupyter server and then connection to it

**Comment by DonJayamanne** [comment]
Going to try and tackle this in debt, with some other debt work
