### ISSUE TITLE
Feature: Strip trailing lines from editor cells on export

### ISSUE THREAD

**Issue by 0az** [microsoft/vscode-jupyter#1369]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description

In the comment-based cell format, it's often useful to add extra empty lines for aesthetic or organizational purposes. However, empty lines at the end of code cells aren't useful when exported to `.ipynb` format, as notebook renderers often add cell borders, etc.

Example (`$file.py`):
```py
# %%
import numpy as np
import matplotlib.pyplot as plt
# The following empty line serves only to visually delimit the cells

# %%
def load_data(): ...
```

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by DonJayamanne** [comment]
Thanks for this feature suggestion, however there haven't been any upvotes on this feature request
Hence closing this issue for now
