### ISSUE TITLE
Ability to save R plots generated from interactive window

### ISSUE THREAD

**Issue by akzaidi** [microsoft/vscode-jupyter#1370]
# Bug: Notebook Editor, Interactive Window, Python Editor cells

This may not be on the roadmap since it's not really a Python development issue, but would definitely be a nice to have for polyglot users 😀 I use R and Python together in almost all of my projects, and find the [rmagic](https://ipython.org/ipython-doc/2/config/extensions/rmagic.html) extension in `rpy2` to be super useful when using both languages together. This also works great in the interactive window of VSCode 🎉, with the one caveat that images aren't accessible through the plot viewer. It would be great if R graphics also showed up in the plot viewer so users could retain images created in the interactive window and zoom/export them as for python plots.

## Steps to cause the bug to occur

1. Generate R plot using  rpy2.ipython extension:

```
%load_ext rpy2.ipython
import seaborn as sns
import matplotlib.pyplot as plt

iris = sns.load_dataset('iris')

# relevant R chunk below:

%%R -i iris -w 4 -h 3 --units in -r 200
library(ggplot2)
library(ggdark)
theme_set(dark_theme_minimal())
ggplot(iris, aes(x = sepal_length, y = sepal_width, color = species)) + 
geom_point() + facet_wrap(~species) + 
theme(legend.position = 'bottom')
```

## Actual & Expected behavior

Ability to hover over plot and open plot in plot viewer.

### Your Jupyter and/or Python environment

*Please provide as much info as you readily know*
- **Jupyter server running:**                       _Remote_
- **Extension version:**                               _2019.11.41015-dev_
- **VS Code version:**                                _1.40.0-insider_
- **Setting python.jediEnabled:**               _false_
- **Python and/or Anaconda version:**     _3.7.3_
- **OS:**                                                     _Mac_
- **Virtual environment:**                          _conda_

**Comment by IanMatthewHuff** [comment]
Closing as part of old issue cleanup as it hasn't gotten upvotes.
