### ISSUE TITLE
Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

### ISSUE THREAD

**Issue by SNdungi** [microsoft/vscode-jupyter#13727]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by amunger** [comment]
Where did you see this error? 
What were you doing when it appeared? 
Is it persistent, or did this only happen once?

**Comment by DonJayamanne** [comment]
@mjbvz /cc

**Comment by rdking** [comment]
I don't know about the OP, but I get this same error on version 1.80.1-1689183569 while trying to open a binary file with the Microsoft Hex Editor plugin. Happened with 1.80.0 as well, and it *is* persistent.

**Comment by amunger** [comment]
@rdking - can you open a separate issue against vscode for that. The jupyter extension shouldn't have anything to do with the hex editor.

**Comment by amunger** [comment]
closing as not enough info
