### ISSUE TITLE
"__file__" variable not available in IPython after kernel restart

### ISSUE THREAD

**Issue by alexbogun** [microsoft/vscode-jupyter#1373]
## Environment data

-   VS Code version: 1.50.1
-   Extension version (available under the Extensions sidebar): v2020.10.332292344
-   OS and version: Win 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8
-   Type of virtual environment used conda
-   Value of the `python.languageServer` setting: Jedi

## Expected behaviour

`__file__` variable is always defined in IPython

## Actual behaviour

`__file__` variable is available when IPython first starts, but is not available after kernel restart.

Reverting to version v2020.9.112786 fixes the problem

## Steps to reproduce:

1. open VSCode
2. create new Python script (.py)
3. type `print(__file__)`
4. Run Selection/Current line in Python Interactive
5. Restart Jupyter kernel
6. Run Selection/Current line in Python Interactive again
</details>

**Comment by IanMatthewHuff** [comment]
Validated.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/293ac1fe-76f9-436d-b063-aa70a69e8c97)

**Comment by alexbogun** [comment]
Unfortunately the issue is back again, could we please reopen this?

**Comment by rchiodo** [comment]
I'm reproing too.

**Comment by IanMatthewHuff** [comment]
@rchiodo I don't believe this was in the point fix. Yeah, I don't see it in the release branch. I think this is fixed, but just not live for customers yet.

**Comment by rchiodo** [comment]
Ah okay. Thanks. @alexbogun this will be fixed in our next stable release.

**Comment by IanMatthewHuff** [comment]
Validated via the previous validation. Will be in the next release as mentioned.
