### ISSUE TITLE
Interactive window ignores blank lines in .py file leading to mismatched row numbers in case of errors

### ISSUE THREAD

**Issue by davhin** [microsoft/vscode-jupyter#13733]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Apologies if I missed an existing issue, this seems very basic and on-the-nose so I expected it to exist already. Basically when I run a .py file in the interactive window and there is an error I noticed the row numbers not matching, a little exploration revealed that blank rows are counted in the editor but not in the interactive window, see screenshot. I would expect them to match.

![Screenshot 2023-06-20 at 11 01 39](https://github.com/microsoft/vscode-jupyter/assets/7582591/66076e68-2298-4647-9ee0-80815b989713)

### VS Code Version

Version: 1.79.2 (Universal) Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06 Date: 2023-06-14T08:58:52.392Z Electron: 22.5.7 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Darwin arm64 22.3.0

### Jupyter Extension Version

v2023.5.1001582324

### Jupyter logs

```shell
Visual Studio Code (1.79.2, undefined, desktop)
Jupyter Extension Version: 2023.5.1001582324.
Python Extension Version: 2023.10.1.
Platform: darwin (arm64).
Workspace folder ~/projects/backend, Home = /Users/davidhinrichs
11:10:41.713 [info] Start refreshing Interpreter Kernel Picker (1687252241713)
11:10:41.719 [info] Using Pylance
11:10:42.238 [info] Process Execution: ~/projects/backend/.venv/bin/python -m pip list
11:10:43.421 [info] End refreshing Interpreter Kernel Picker (1687252241713)
11:10:53.797 [info] Starting interactive window for resource '~/projects/backend/optimization/test.py' with controller '.jvsc74a57bd0887b3c2f00e9807f5ff1a75e73186f94a5fc28a681abeeda7d70a7a7f6f333d9.~/projects/backend/.venv/python.~/projects/backend/.venv/python.-m#ipykernel_launcher (Interactive)'
11:10:53.924 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0887b3c2f00e9807f5ff1a75e73186f94a5fc28a681abeeda7d70a7a7f6f333d9.~/projects/backend/.venv/python.~/projects/backend/.venv/python.-m#ipykernel_launcher  (Python Path: ~/projects/backend/.venv/bin/python, Poetry, .venv, 3.11.3) for '/Interactive-1.interactive' (disableUI=false)
11:10:53.930 [info] Process Execution: ~/projects/backend/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
11:10:53.933 [info] Process Execution: ~/projects/backend/.venv/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.5.1001582324-darwin-arm64/pythonFiles/normalizeSelection.py
11:10:53.938 [info] Process Execution: ~/projects/backend/.venv/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"51d818d0-7f6d-46b2-842c-ceed8e854df1" --shell=9002 --transport="tcp" --iopub=9004 --f=~/Library/Jupyter/runtime/kernel-v2-109703N2GbjutaTHR.json
    > cwd: ~/projects/backend/optimization
11:10:54.049 [info] ipykernel version & path 6.23.1, ~/projects/backend/.venv/lib/python3.11/site-packages/ipykernel/__init__.py for ~/projects/backend/.venv/bin/python
11:10:54.200 [warn] StdErr from Kernel Process 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
11:10:54.361 [info] Started Kernel .venv (Python 3.11.3) (pid: 11100)
11:10:54.361 [info] Started new session 3ae37b2e-6d52-4c7c-a3dd-eadba121406b
11:10:54.410 [info] Process Execution: ~/projects/backend/.venv/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.5.1001582324-darwin-arm64/pythonFiles/printJupyterDataDir.py
11:10:54.411 [info] Generated code for 1 = <ipython-input-1-d73862284fc1> with 4 lines
11:10:54.420 [info] Kernel acknowledged execution of cell 1 @ 1687252254415
11:10:54.513 [info] End cell 1 execution @ 1687252254512, started @ 1687252254415, elapsed time = 0.097s
11:10:54.514 [warn] Cancel all remaining cells due to cancellation or failure in execution
```

### Coding Language and Runtime Version

Python v.3.11.3

### Language Extension Version (if applicable)

Python v2023.10.1

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
possibly https://github.com/microsoft/vscode-jupyter/issues/11002, Are you using IPython 7?

**Comment by davhin** [comment]
Using IPython 8.14.0, I have included my poetry lock file. Also, if I include more blank lines the same effect happens. Basically it seems the Interactive Window strips all blank lines before running the code which means the row/line numbers are just off by that amount. thanks for looking into this!

[poetry.lock.txt](https://github.com/microsoft/vscode-jupyter/files/11815043/poetry.lock.txt)

**Comment by amunger** [comment]
oh, this is probably because we inconsistently normalize the code depending on how it was sent over (https://github.com/microsoft/vscode-jupyter/issues/13045). 
I can repro when selecting some code from a .py file and `shift+enter` to execute the selection

**Comment by davhin** [comment]
this is exactly how i am sending over the code, yes!

**Comment by amunger** [comment]
There is now a setting in insiders to skip the heavy normalization step: `"jupyter.interactiveWindow.textEditor.normalizeSelection": false`

It should still be able to execute selections in the same way, but will leave empty lines alone.

The old behavior is still default for now until I'm more certain that this won't break anyone's workflow.
