### ISSUE TITLE
Type() function does not display any output

### ISSUE THREAD

**Issue by lorigami-jfh** [microsoft/vscode-jupyter#13744]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

The Python extension does not display the output of the type() function when running it.

## Steps to reproduce:

a=1
type(a)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.4
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): MicrosoftStore
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

[Running] python -u "f:\Python\operations.py"

[Done] exited with code=0 in 0.387 seconds

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

testing
• pytestArgs: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: true

```

</p>
</details>

Extension version: 2023.10.1
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz (20 x 2295)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.92GB (117.41GB free)|
|Process Argv|--crash-reporter-id ba40cb0f-fc1f-41b2-8886-1ab37a16b444|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
pythongtdpath:30769146
dh2dc718:30763024

```

</details>

**Comment by DonJayamanne** [comment]
It kind of works for me, thought the presentation is not correct.
![Screenshot 2023-06-22 at 07 15 52](https://github.com/microsoft/vscode-jupyter/assets/1948812/fa818833-07c3-412e-8e94-9931728def38)

> Expected vs. Actual

@Krishnaa-tech Please could you share a screenshot of the output. 
I'd like to see what it looks like at your end.

**Comment by Krishnaa-tech** [comment]
![image](https://github.com/microsoft/vscode-jupyter/assets/101107027/80a9e704-02aa-45db-bf01-b57f3a265fb0)

I have implemented this in this way, and it's working.

**Comment by DonJayamanne** [comment]
> I have implemented this in this way, and it's working.

So can we close this issue? or is there something else thats' not working?
Please could you share a screenshot of what is not working.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
