### ISSUE TITLE
The code is not executed completely when pick 'Python: Run Current File In Python Interactive Window'.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#1374]
## Environment data
![image](https://user-images.githubusercontent.com/59192491/98228974-4816b280-1f94-11eb-8bc4-b6659ba67515.png)

## Expected behaviour
The kernel should be restarted and it should run the whole file again.

## Actual behaviour
The code is not executed completely.
![image](https://user-images.githubusercontent.com/59192491/98229397-cffcbc80-1f94-11eb-9b31-d8e08dd3ba3c.png)

## Steps to reproduce:
1. Open the file manualTestFile.py in VSCode
2. Select conda Interpreter as current environment
3. On the first cell click `Run Cell And All Below`
4. Close the Interactive Window then pick `Python: Show Python Interactive Window`
5. The kernel should be restarted and pick `Python: Run Current File In Python Interactive Window`

**Comment by greazer** [comment]
@linette-zyy, when I ran the file you provided in the latest stable build of the jupyter extension, all of the code is executing from what I can tell. When the run is complete, I have the output you provided above, as well as the variables you defined at the end. They appear correctly in the variable explorer.

Closing for now, please reopen if there's still a problem.
