### ISSUE TITLE
Jupyter notebook missing descriptions in intellisense recommendations.

### ISSUE THREAD

**Issue by kunalchaturvedi** [microsoft/vscode-jupyter#1375]
## Environment data

-   VS Code version: 1.50.1
-   Extension version (available under the Extensions sidebar): python extension v2020.10.332292344
-   OS and version: ubuntu 20.04 lts
 -   conda version : 4.8.3
 - conda-build version : 3.18.11
 - python version : 3.8.3.final.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda (set to base env)
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: python extension v2020.10.332292344
-   Value of the `python.languageServer` setting: Jedi
 -   Jupyter server running: Local

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

Descriptions shown for python files.
![Screenshot from 2020-10-30 20-47-52](https://user-images.githubusercontent.com/16863787/97723450-cf29dd80-1af1-11eb-8b7b-c96f8535f22f.png)

## Actual behaviour

No descriptions are shown for intellisense recommendations for jupyter notebooks. This is seen for all recommendations made by intellisense.

![Screenshot from 2020-10-30 20-53-14](https://user-images.githubusercontent.com/16863787/97723968-5d05c880-1af2-11eb-9474-d1fa64f9df76.png)

Switching to pylance language server has the same issue as above.
Switching to the microsoft language server causes intellisense to not work at all for jupyter notebook files.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
@DavidKutu I'm unable to repro this issue, please could you try this again & let me know if you can repro this. Thanks

**Comment by DonJayamanne** [comment]
@kunalchaturvedi I'm unable to repro this issue at my end.
IT works as expected, see below

![Screen Shot 2020-11-16 at 15 05 42](https://user-images.githubusercontent.com/1948812/99318900-73639200-281d-11eb-82b1-31d6c2aa3afe.png)

Please could you 
* Install the latest version of the Python, Jupyter & Pylance exetnsions
* Re-load VS Code
* Try once again
* If it doesn't work, please provide logs from your `Python` & `Jupyter` output panels 
* & screenshots

Thanks

**Comment by DonJayamanne** [comment]
Apologies, i have been looking at the wrong thing, please ignore my previous comment.

**Comment by perepelart** [comment]
I have got the same issue. I can not see any docstring while typing and even inside the brackets of functions. But if i do the same with files with .py extension everything works correctly.
Here is that i see while typing in the file .ipynb :
![VsCodeError](https://user-images.githubusercontent.com/64279180/99370082-47541980-28ce-11eb-868f-9eebf8f1e424.png)
Here is that i see moving inside the brackets : 
![VsCodeError2](https://user-images.githubusercontent.com/64279180/99371134-8fc00700-28cf-11eb-8507-253bfc40e4cb.png)

But in the files with .py extension everything works correctly, respectively : 
![NotErrorPy1](https://user-images.githubusercontent.com/64279180/99370653-03addf80-28cf-11eb-82c9-862df739323b.png)
![NotErrorPy2](https://user-images.githubusercontent.com/64279180/99370909-525b7980-28cf-11eb-9e78-fd07f9842947.png)

**Comment by DonJayamanne** [comment]
@perepelart @kunalchaturvedi 
Thanks for reporting this issue. I have confirmed that this is not supported.
Please consider using the Native Notebook (see here for more for).
To use the `new Native Notebook`, simply install `VS Code Insiders` and you'll get that new UI.

**Comment by perepelart** [comment]
@DonJayamanne Thank you but i could not make it work even in VS Code Insiders. I fully uninstalled VS Code (with folders in .config and .vscode on Ubuntu) and installed VS Code Insiders from https://code.visualstudio.com/insiders/ . I installed Python extension, Jupyter extension and add to "settings.json" line "jupyter.experiments.optOutFrom": ["NativeNotebookEditor"]. After it i did the  command "Jupyter: Create New Blank Jupyter Notebook" and opened created .ipynb file. But even after all of these things i could not see any docstring while typing and while moving cursor in the brackets of function. I thought that something got broken during process of installation and tried to reinstall it. I fully uninstalled VS Code Insiders with hidden folders and repeated all of described steps. But even after second try i do not get any changes. Now i still can not see any docstring and do not know that to do.

**Comment by DonJayamanne** [comment]
>  add to "settings.json" line "jupyter.experiments.optOutFrom": ["NativeNotebookEditor"]. 

Please remove that. You need to use the new ui

**Comment by perepelart** [comment]
@DonJayamanne Thank you for the answer. I did it. I even fully cleared "settings.json" and saved it as empty file. After it i could not see docstring but now i got error message after creation of file with .ipynb extension: "CustomEditor and NativeNotebook experiments cannot be turned on together". I googled around this error but could not find any information. After the program installation i didn't change any settings exclude installation of extensions which i described. Can you explain me what did I do wrong this time?

**Comment by perepelart** [comment]
@DonJayamanne I solve the error "CustomEditor and NativeNotebook experiments cannot be turned on together" by typing in the settings.json such lines:
"workbench.enableExperiments": false,
"window.enableExperimentalProxyLoginDialog": false,
"python.experiments.enabled": false,
"jupyter.experiments.enabled": false.
I did not turn on them and i guess they were turned on by default.
But docstrings do not work anyway.

**Comment by perepelart** [comment]
@DonJayamanne I installed extension "Pylance", typed in settings.json : "python.languageServer": "Pylance" and now i can see docstring! Thank you for the help. (It was all performed in latest version of VS Code Insiders).

**Comment by cyx772791512** [comment]
@perepelart I faced a same problem with you that the docstring in .ipynb is missing. And I tried your suggestion, changed the "languageServer" from "Microsoft" into "Pylance", then the docstring appeared. 
However, Pylance cannot analyze and autocomplete the cv2 module, could the next release of Jupyter fix this issue?
@DonJayamanne

**Comment by DonJayamanne** [comment]
@cyx772791512 Please ensure you are using the new Nativenotebook edtiro. You need to be using VS Code Insiders for this.
Please see `Working with Other Lanaguages` in https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter (this section provides instructions to getting the new experience).

**Comment by alsonyap** [comment]
So glad I found this issue being raised, thank you so much for the solution and work @DonJayamanne

Have a great year ahead to you and the team! 🎉

**Comment by DonJayamanne** [comment]
> ay I know if this feature (and new look of Jupyter notebook in VS Code) will eventually make it to the "main" VS Code application?

Yes it will

**Comment by mtsitzer** [comment]
On latest version of vscode-jupyter, and this is an issue for me:

Non notebook (docstring displays):
![image](https://user-images.githubusercontent.com/28517224/123038481-58559380-d3a5-11eb-8aba-55076385334b.png)

Notebook (nothing comes up):
![image](https://user-images.githubusercontent.com/28517224/123038507-64415580-d3a5-11eb-903c-bf8bccf46410.png)

**Comment by rchiodo** [comment]
This should be working now:

![image](https://user-images.githubusercontent.com/19672699/131420401-7a5c57b4-834c-479a-a141-00c5b0b48e4b.png)
