### ISSUE TITLE
Provisioning the remote JupyterHub server URL in a docker container

### ISSUE THREAD

**Issue by BouarfaMahi** [microsoft/vscode-jupyter#13759]
## Environment data
Code-server supports connecting to a remote Jupyter notebook server, and we can use that to connect to our JupyterHub with the URL https:///user//?token=.

The issue is that I need to refresh the code-server page to choose the Kernel to use. Is there any way to provision this URL in a Docker container or where is located  the Jupyter extension file system that registers this URL?

## Expected behaviour

Connecting code-server to a remote JupyterHub instance from a browser without refreshing the web page.

## Actual behaviour

need to refresh the browser.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

using code-server:
1. remove the remote jupyterHub url by clicking on the trash icon
2. copy past the remote url then apply enter.
3. click on the kernel select and no kernel appears.
4. refresh the browser and the kernels are present.

Furthermore, there is no issue when using Vscode desktop client instead of code-server

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filling this issue l issue and sorry you are running into this

what version of vscode and Jupyter extension are you using
You do not need to refresh the browser,
The delay is most likely in connection to the server and fetching the kernels, in fact just clicking the kernel picker in a few seconds should work

let me know if this works in the latest version or not (you haven’t provided the version information).  
If not please could you try vscode insiders and the latest pre-release version of the Jupyter extension

currently there’s no way to store the url and token in the file system, this is insecure as the token contains authentication information

**Comment by BouarfaMahi** [comment]
Thanks, after 4 minutes the remote connection remains inactive.

code-server version: 
**code-server: v4.12.0**
Code: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-13T18:36:32.554Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

i will try the 4.14 last version

Jupyter extension:   v2023.3.100 is the last supported  version (Open VSX Registry)
Not possible to activate the Pre-release version. v2023.4.1001091014

**Comment by BouarfaMahi** [comment]
After upgrading to the last 4.14 code-server version i can now activate the last jupyter extension pre-release version. 
The Kernels appears as soon as  i  click the kernel select.
Thanks Don for your valuable advice.
