### ISSUE TITLE
Test Exporting a Notebook in web

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13768]
Test Storing Remote Jupyter Servers with the new storage format

Refs: #13577

- [x] Web @rebornix 
- [x] Web @joyceerhl

Complexity: 3

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2313577%0A%0A&assignees=DonJayamanne)

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2313768%0A%0A&assignees=DonJayamanne)

---

### Requirements

- Have a python environments installed
- Familiarity launching Jupyter Notebooks Application outside VS Code

#### Steps
- Run jupyter with the following command line 
  `python -m jupyter notebook --no-browser --NotebookApp.allow_origin='*'`  
  Note the URL it generates for connecting
  [See herefor more information on setting up Jupyter](https://github.com/microsoft/vscode-jupyter/wiki/Install-and-Setup-Jupyter-Notebook-Lab-for-Testing)  
- Start insiders.vscode.dev
- Go into the kernel picker and add the above URL into the input for `Select Another -> Existing Jupyter Server`
- Open a Notebook and Select a Python kernel
- From the command palette select `Jupyter: Export to HTML`
- Verify the notebook is exported to a HTML file.

**Comment by alexr00** [comment]
> Start insiders.vscode.dev

I think there are missing steps after this: 
- Open a remote repository folder that has a Jupyter notebook in it
- Open the notebook file
