### ISSUE TITLE
Test Storing Remote Jupyter Servers with the new storage format

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13767]
Test Storing Remote Jupyter Servers with the new storage format

Refs: #11645

- [x] Web @joaomoreno
- [x] anyOS @amunger
- [x] anyOS @roblourens

Complexity: 3

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2311645%0A%0A&assignees=DonJayamanne)

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2313767%0A%0A&assignees=DonJayamanne)

---

### Requirements

- Have a python environments installed
- Familiarity launching Jupyter Notebooks Application outside VS Code

#### Steps
- Run jupyter with the following command line 
  `python -m jupyter notebook --no-browser --NotebookApp.allow_origin='*'`  
  Note the URL it generates for connecting
  [See herefor more information on setting up Jupyter](https://github.com/microsoft/vscode-jupyter/wiki/Install-and-Setup-Jupyter-Notebook-Lab-for-Testing)  
- Start insiders.vscode.dev
- Install the **Release** version of the Jupyter extension (`2023.5.110*`)
- Add the following to the user settings file
```jsonc
	"jupyter.experiments.enabled": true,
	"jupyter.experiments.optInto": [  ],
	"jupyter.experiments.optOutFrom": [ "NewRemoteUriStorage" ]
```
- Reload VS Code
- Create a notebook with `Create: New Jupyter Notebook`
- Connect to the above Jupyter server via the Kernel Picker
    - Open the kernel picker, select `Select Another Kernel -> Existing Jupyter Server` and enter the above URL
- Select a Python kernel and verify you can run a cell with the text `print("Hello World")`
- Reload VS Code and verify the same kernels are displayed in the Kernel Picker
- Opt into the experiment by adding the following to the user settings file
```jsonc
	"jupyter.experiments.enabled": true,
	"jupyter.experiments.optInto": [ "NewRemoteUriStorage" ],
	"jupyter.experiments.optOutFrom": [  ]
```
- Switch to the **Pre-Release** Jupyter extension
- Reload VS Code 
- Open a notebook and verify the same kernels are still displayed in the kernel picker
- Start a new Jupyter server and add this server as well into the Kernel Picker and verify the two remote Jupyter Servers are listed in the kernel picker (the one added earlier and the one added now)
- Opt out of the experiment as follows
```jsonc
	"jupyter.experiments.enabled": true,
	"jupyter.experiments.optInto": [  ],
	"jupyter.experiments.optOutFrom": [ "NewRemoteUriStorage" ]
```
- Reload VS Code and verify the 2 Remote Jupyter Servers are still visible in the kernel picker

**Comment by joaomoreno** [comment]
### Pre-requisites

1. Create a new folder
2. Open folder in VS Code, with Python extension installed
3. Run `Python: Create Environment...`, choose `venv` and your default Python installation
4. Open a new Terminal
5. Run `python -m pip install jupyter`

**Comment by joaomoreno** [comment]
FYI seeing a warning here:

"NewRemoteUriStorage"

**Comment by joaomoreno** [comment]
Added a step:

> - Create a notebook with `Create: New Jupyter Notebook`

**Comment by joaomoreno** [comment]
This doesn't work from Safari: https://github.com/microsoft/vscode-jupyter/issues/13779

**Comment by DonJayamanne** [comment]
@joaomoreno  shoes this work in another browser?

**Comment by roblourens** [comment]
Don please make sure you aren't copying the Create Issue link from some other TPI, because otherwise you will end up with 2 and a bunch of issues pointing at the wrong place
