### ISSUE TITLE
Request: Allow Data Wrangler to use Jupyter API in production

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode-jupyter#13774]
Hi! Looks like we're getting the message below on the latest pre-release version: v2023.6.1001652307
Could you please add us to the allow list?

<img width="561" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/8560030/e77365be-d5a7-4cc3-a086-0f52b6a5c606">

Thanks!

**Comment by DonJayamanne** [comment]
Closing as fixed (user setup issue)
