### ISSUE TITLE
Can't connect to remote Jupyter Server from vscode.dev on Safari

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-jupyter#13779]
Attempting to test #11645 on Safari results in the following error:

<img width="660" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/22350/a28e3b3d-00ca-4a87-9568-92498606848a">

**Comment by DonJayamanne** [comment]
Thanks, can replicate this in stable as well, looks like this has never worked, possible http is not allowed.

**Comment by DonJayamanne** [comment]
Closing this as out of scope. this seems to be an issue with the browser when connecting to localhost (regardless of http/https).
Connecting to remote ips works
