### ISSUE TITLE
Kernel picker flickers and shows "Outline" toolbar button briefly

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#13787]
Testing #13765

This might be a problem in core, for wizards we should hopefully be able to avoid this and keep the quick open consistently open, just change the content. Or is the existing jupyter server doing something async for some reason before showing it?

![Recording 2023-06-27 at 07 28 13 (1)](https://github.com/microsoft/vscode-jupyter/assets/2193314/3e73b7a0-0d0a-40ee-9c93-a30070d7c0ed)

**Comment by DonJayamanne** [comment]
Yes we do have some async stuff, we try to read the clipboard to populate the input box, 
The plan is to remove that, once we remove that, this will hopefully go away.

**Comment by DonJayamanne** [comment]
This is no longer an issue.
