### ISSUE TITLE
Installing ipykernel: Collecting package metadata (c

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#13788]
Testing #13765

When creating a conda environment via the kernel picker I see this:

![image](https://github.com/microsoft/vscode-jupyter/assets/2193314/07863e08-7896-48e5-bd18-64df34cfdc86)

What's the `(c` about? Is content being truncated?

**Comment by DonJayamanne** [comment]
Yes, this is just content being truncated, I think we can strip the last few chars and add `...` to make it more obvious
