### ISSUE TITLE
Command "Notebook: Select Notebook Kernel" does nothing

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-jupyter#13784]
Testing #13577

1. Open `insiders.vscode.dev`
2. Run the command "Notebook: Select Notebook Kernel"
3. Nothing appears to happen

**Comment by DonJayamanne** [comment]
Will get @amunger or @rebornix to validcate this, you need to open a ntoebook document

**Comment by DonJayamanne** [comment]
Agreed
