### ISSUE TITLE
Xeus-Cling kernel not appearing in VS Code's Jupyter Notebook kernel picker

### ISSUE THREAD

**Issue by mrinmoy2developer** [microsoft/vscode-jupyter#13783]
Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

Unable to connect to xeus-cling kernel in WSL2 Ubuntu from VS Code jupyter notebook even though it works fine when launched in browser.
Steps to Reproduce:

1.  I've VS Code Jupyter extension v2023.5.1101742258 installed
2.  I'm running Ubuntu 22.04.2 LTS on WSL2 on windows 11 Home ,OS Build 22621.1848
3.  I've installed xeus-cling and jupyter in a conda environment , "XeusCling" using miniconda 23.1.0 following the instructions at https://envyen.com/posts/2021-06-27-C-CPP-Jupyter-Notebook-Windows/
4. When I try to launch the jupyter server in --no-browser mode and open the url in the browser xeus-cling works fine and I'm able to connect to c++11,c++14 & c++17 as shown below:-
![image](https://github.com/microsoft/vscode/assets/35917115/4aeab26c-c204-4a1b-86b8-1d3e2efdfd13)
But when I open another '.pynb' file on windows in vs code the XeusCling env doesn't show up:
![image](https://github.com/microsoft/vscode/assets/35917115/51199d59-4d66-48b5-8d34-e7728a2fdc87)
![image](https://github.com/microsoft/vscode/assets/35917115/6eae51d6-0f0f-48dc-ad25-0f0c108fcbe9)

5. I tried using VS Code Insiders and got the same issue as shown below:-
![image](https://github.com/microsoft/vscode/assets/35917115/20dd3d3a-f5c0-451a-8c13-35c500f3a9c0)

**Comment by DonJayamanne** [comment]
Thank you for reporting this and sorry you are running into this.  
We are aware of this issue and will look into this

here’s an old(related) issue https://github.com/microsoft/vscode-jupyter/issues/5469

**Comment by mrinmoy2developer** [comment]
ok

**Comment by DonJayamanne** [comment]
Oops, sorry, the issue was related to xeus-python, not xeus-cling, they are two different issues.
Will look into this again.

**Comment by DonJayamanne** [comment]
Tested and this should work, the kernels are now displayed.
@mrinmoy2developer Let me know if this issue still persists.
