### ISSUE TITLE
Kernel picker icon spins forever

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-jupyter#13780]
1. Follow the microsoft/vscode#11645 test plan item with just the Jupyter extension installed, no others

🐛 The kernel picker will spin forever.

https://github.com/microsoft/vscode-jupyter/assets/22350/92cabef5-0437-42f6-beb8-f2f25b8688fc

**Comment by DonJayamanne** [comment]
@joaomoreno  please can you share the logs from the Jupyter output channel

**Comment by joaomoreno** [comment]
```
Visual Studio Code - Insiders (1.80.0-insider, undefined, vscode.dev)
Jupyter Extension Version: 2023.6.1001801100.
Python Extension not installed.
No workspace folder opened.
17:03:27.099 [info] User belongs to experiment group 'FastKernelPicker'
17:03:27.099 [info] User belongs to experiment group 'PasswordManager'
```

**Comment by NightMachinery** [comment]
https://github.com/microsoft/vscode/issues/186903

**Comment by DonJayamanne** [comment]
@rebornix the Jupyter extension isn't display the spinner (at least based on the logs),
looks like a core issue

**Comment by gitclimate** [comment]
I switched to using ssl in the jupyter config file and the spinner stopped

c.ServerApp.certfile = '/home/user/.jupyter/certificate.pem'
c.ServerApp.keyfile = '/home/user/.jupyter/key.pem'

**Comment by rebornix** [comment]
Let's merge it into https://github.com/microsoft/vscode/issues/186364
