### ISSUE TITLE
Not able to connect to Jupyter lab server started with password

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-jupyter#13781]
Testing #13766

<img width="660" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/10746682/4fceb206-5b9a-4097-8b83-007d28be4668">

**Comment by DonJayamanne** [comment]
@rebornix @amunger 
Please can you test this test plan item
I’m assuming the Jupyter server wasn’t started with the right cli agrs

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/13801
