### ISSUE TITLE
Unable to connect to Jupyter server with empty token

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-jupyter#13798]
Testing #13766

1. Run `python -m jupyter notebook --no-browser --NotebookApp.allow_origin='*' --NotebookApp.token=` in a terminal.
2. Try connecting to the localhost kernel and running a cell.
3. :bug: Get an error about _xsrf not being passed in.

Non-empty tokens work fine.

**Comment by DonJayamanne** [comment]
@rzhao271 are you connecting through the web or desktop

**Comment by DonJayamanne** [comment]
@rebornix @amunger Please can you test this at your end as well

**Comment by amunger** [comment]
did not repro for me

**Comment by rzhao271** [comment]
Unable to repro now. Closing
