### ISSUE TITLE
Kernel Management issues and improvements

### ISSUE THREAD

**Issue by harplife** [microsoft/vscode-jupyter#1379]
# Feature: Notebook Editor

## Description

1. Jupyter Notebook tree shows active kernels. It'd be nice if I could monitor active kernels on the workspace.
2. Notebook editor shows only option for Restart and interrupt kernel. I'm not sure if closing the notebook window actually quits the kernel - if not, it'd be nice to have options to either temporarily close the window or quit the kernel completely. Kernel management will probably make this feature obsolete though.

**Comment by JulesGM** [comment]
being able to kill a kernel without having to close the window would be very nice. A lot of the time, the `interrupt` button just doesn't actually kill the kernel even after minutes.

**Comment by oholimoli** [comment]
please implement this feature. I'm working on a cython extension and when I want to compile it I must kill the kernel, otherwise I get a permission error when compiling the new cython extension:

```
PermissionError: [Errno 13] Permission denied: './jupyter/ext.cp37-win_amd64.pyd' 
```

**Comment by jtkiley** [comment]
In https://github.com/microsoft/vscode-jupyter/issues/7189#issuecomment-901259010, @rchiodo said:  

> Thanks for the suggestion. Kernels should be killed when:
> - You close VS code
> - You close the notebook/interactive window that had the kernel selected.
> 
> Do you need another way to kill a kernel? Maybe while VS code is still open?

Unless I'm misreading, when I close a notebook (i.e. close its tab in the VS code window), its kernel should be killed. That's not the behavior I'm seeing. For example, right now, I have a notebook that has been closed for a couple of days, and it's still holding ~48GB of RAM. If I reopen it (i.e. name italicized in the tab as a preview), I still see the green checks and execution times suggesting that the kernel is still running (and verified in Activity Monitor).

Ideally, I'd like to be able to kill kernels much like I can in the Jupyterlab interface, whether that's by a panel (see #7598), visibility in the file browser with a right-click option (see Jupyterlab), or something else. I work on a lot of (research) projects with a mix of documents, `.py` files, notebooks, CSVs, and the like. So, I may have a project window open for weeks, even though any given notebook is only in use for a short amount of time (and, thus, shouldn't have a running kernel holding on to lots of RAM).

I'm pretty new to the Jupyter functionality in VS Code, but I like it a lot. This is probably my top usability issue so far.

**Comment by rchiodo** [comment]
@jtkiley the kernel should die on notebook close (unless you're using remote where kernels would be handled by the remote server). 

You might be hitting this bug though:
https://github.com/microsoft/vscode-jupyter/issues/5225

**Comment by jtkiley** [comment]
@rchiodo Thanks!

If I close the notebook's tab within the VS code window, it continues to live forever. But, if I close the interactive window (what #5225 appears to be having an issue with), it does appear to kill the kernel.

Am I right that both cases should kill the kernel, and not just the second?

FYI: Mac, Intel, 11.6.1, current stable VS code

**Comment by rchiodo** [comment]
Yes both cases should kill the process. Daemon failure may be happening on Mac M1 as well.

**Comment by jtkiley** [comment]
@rchiodo I'm on an Intel Mac in this case, but I went exploring a bit. 

If I create a test notebook, it kills on tab close like you'd expect. So, I went back to the big notebook I was working with, and I managed to cut until I have a small reproducible test case. It's pretty obscure, but it goes like this: If I run through a notebook and display a `%matplotlib inline` figure, close it (proper kernel kill), reopen it and run through to `df.head()` in pandas, and then close the tab, the kernel persists. Oddly enough, I need to run that `df.head()`; importing pandas and mocking up a data frame won't do it.

With that in mind:

1. This is probably a bug apart from this issue. I'll see if I can find it already reported (pointers appreciated).
2. The possibility for a strange bug like this is probably a good reason to expose kernel management controls.

**Comment by rchiodo** [comment]
The daemon failure I mentioned was likely timing related so it may be that the kernel has to be just slow enough to not respond to a request from the daemon in order for it to not die.

**Comment by DonJayamanne** [comment]
Closing this issue as the functionality requested in the original comment of this issue has been provided by the Jupyter Power Toys extension, see here https://github.com/microsoft/vscode-jupyter-powertoys#kernel-management-panel

**Comment by JulesGM** [comment]
@DonJayamanne I feel strongly like this should be a core Jupyter feature, and not in some extension.

**Comment by JulesGM** [comment]
having to close and restart kernels reliably is just a bread and butter thing that should be a core feature

**Comment by JulesGM** [comment]
@rchiodo please don't kill this

**Comment by chrisyeh96** [comment]
@DonJayamanne: I would love to have this feature moved into the main Jupyter VS Code extension as well. I didn't know about Jupyter PowerToys as an option until I came across this thread, and until now, I've been reluctantly relying on JupyterLab to manage my Jupyter kernels.

While the Jupyter VS Code [extension description on the VSCode marketplace](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter) currently references Jupyter PowerToys, it doesn't actually list what features PowerToys supports and simply says that PowerToys adds "experimental features." I personally would not have thought that kernel management would be considered an "experimental feature," so I didn't even think to look at PowerToys. Perhaps this is a personal issue, but I would love to see either:

a) directly adding the kernel management feature into the Jupyter extension, OR
b) enhancing the discoverability of the Jupyter PowerToys features.

**Comment by DonJayamanne** [comment]
> list what features PowerToys supports and simply says that PowerToys adds "experimental feat

Thank you for this suggestion, we're planning on moving some of this into the core jupyter extension, however this hasn't been prioritized. But that is the goal.
