### ISSUE TITLE
Kernel list did not persist after installing pre-release

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#13797]
Testing #13767

I had 3 remote servers listed in release jupyter, including one with an active kernel.
After installing pre-release and enabling the experiment, I only see one really old server

![image](https://github.com/microsoft/vscode-jupyter/assets/2019016/a19b32d1-66bd-43e3-a6ae-8ce2efdd0461)

**Comment by amunger** [comment]
[jupyterLogs.log](https://github.com/microsoft/vscode-jupyter/files/11887032/jupyterLogs.log)

**Comment by amunger** [comment]
The other way seems to work: adding a server with the `NewRemoteUriStorage` experiment active will show up when reloading without the experiment.

**Comment by DonJayamanne** [comment]
Please can you try this once again with the latest pre-release version and please ensure you opt into the experiment as follows 
```jsonc
	"jupyter.experiments.optInto": [
		"FastKernelPicker",
		"PasswordManager",
		"NewRemoteUriStorage"
	],
```

Similarly for opting out use 
```
	"jupyter.experiments.optOutFrom": [
		 "FastKernelPicker",
		 "PasswordManager",
		 "NewRemoteUriStorage"
	],
```

**Comment by DonJayamanne** [comment]
I have tried this at my end and works,

Can you try the following
* Open VS Code insiders with a new user data directory and extensions folder as follows
`code-insiders  --user-data-dir=~/temp/newFolder2 --extensions-dir=~/temp/newFolder1`
* Install the stable versions of Jupyter extension
* Enter the urls
* Reload VSCode and verify the urls have been persisted
* Opt into the experiments as follows
```json
{
    "jupyter.experiments.enabled": true,
    "jupyter.experiments.optInto": [
        "FastKernelPicker",
        "PasswordManager",
        "NewRemoteUriStorage"
    ],
    "jupyter.experiments.optOutFrom": [    ],
}
```
* Reload VS Code
* Install the latest pre-release version of the Jupyter extension
* Verify the Urls have been migrated and you see them

If this doesn't work, then please do share the logs.

**Comment by DonJayamanne** [comment]
Closing as this was verified as fixed by @amunger
