### ISSUE TITLE
Cannot connect to password protected Jupyter server when opting out of password manager experiment

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13802]
@amunger ran into this.

**Comment by amunger** [comment]
I hit the bad password error once after clicking 'don't show again' to the password warning toast, but closing and reopening the kernel picker got past that

**Comment by amunger** [comment]
now I can get stuck with a bad password error opted in to the experiment:

[jupyterLogs.log](https://github.com/microsoft/vscode-jupyter/files/11897382/jupyterLogs.log)

**Comment by DonJayamanne** [comment]
I'm unable to replicate this, looks like you had the same server before you added it, possible the server was already in the list and it was password protected and you hadn't entered the password (you get promtped to enter the password as soon as you load the extension).

My suggestion is to clear the urls , reload, wait for a few seconds and then add the Url.

**Comment by DonJayamanne** [comment]
This has been resolved.
