### ISSUE TITLE
Two instances of the same kernel after switching storage formats

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#13800]
Testing #13767

I switched the experiment settings, installed the pre-release extension, and now I see two copies of the kernel. Both of them work.

<img width="637" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/323878/7ad95826-b66e-4bba-9fc8-6de76bed1f28">

**Comment by DonJayamanne** [comment]
One is an active kernel an one is just the kernel spec
We probably need better names, but this is expected.
