### ISSUE TITLE
DS: Enable tensor/multi-dimensional array inspection experience

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#1381]
This is a rather nebulous feature at the moment, but the intent is to create something that can be used to inspect ml-related datatypes, such as tensors, multi-dimensional arrays, etc.

**Comment by joyceerhl** [comment]
You can now inspect multidimensional tensors and ndarrays as of the April 2021 release: https://devblogs.microsoft.com/python/jupyter-in-visual-studio-code-april-2021-release/
