### ISSUE TITLE
Unable to use matplotlib to draw plots in an external window

### ISSUE THREAD

**Issue by 130040167** [microsoft/vscode-jupyter#13812]
## Environment data

-   VS Code version: 1.80.0-insider 
-   Jupyter Extension version (available under the Extensions sidebar): v2023.6.1001811100
-   Python Extension version (available under the Extensions sidebar): v2023.10.1
-   OS (Windows | Mac | Linux distro) and version: Windows_NT ia32 10.0.22621
-   Python and/or Anaconda version: 3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote 

## Expected behaviour

When I use command like %matplotlib tk to open a pop-up window in the Jupyter extension of vscode, an error occurs:
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running.
But when using Jupyter and Matplotlib in the browser, everything works fine.

## Actual behaviour

an error occurs:
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 get_ipython().run_line_magic('matplotlib', 'tk')

File ~/anaconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2414, in InteractiveShell.run_line_magic(self, magic_name, line, _stack_depth)
   2412     kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2413 with self.builtin_trap:
-> 2414     result = fn(*args, **kwargs)
   2416 # The code below prevents the output from being displayed
   2417 # when using magics with decodator @output_can_be_silenced
   2418 # when the last Python token in the expression is a ';'.
   2419 if getattr(fn, magic.MAGIC_OUTPUT_CAN_BE_SILENCED, False):

File ~/anaconda3/lib/python3.10/site-packages/IPython/core/magics/pylab.py:99, in PylabMagics.matplotlib(self, line)
     97     print("Available matplotlib backends: %s" % backends_list)
     98 else:
---> 99     gui, backend = self.shell.enable_matplotlib(args.gui.lower() if isinstance(args.gui, str) else args.gui)
    100     self._show_matplotlib_backend(args.gui, backend)

File ~/anaconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3600, in InteractiveShell.enable_matplotlib(self, gui)
   3596         print('Warning: Cannot change to a different GUI toolkit: %s.'
   3597                 ' Using %s instead.' % (gui, self.pylab_gui_select))
   3598         gui, backend = pt.find_gui_and_backend(self.pylab_gui_select)
-> 3600 pt.activate_matplotlib(backend)
   3601 configure_inline_support(self, backend)
   3603 # Now we must activate the gui pylab wants to use, and fix %run to take
   3604 # plot updates into account

File ~/anaconda3/lib/python3.10/site-packages/IPython/core/pylabtools.py:360, in activate_matplotlib(backend)
    355 # Due to circular imports, pyplot may be only partially initialised
    356 # when this function runs.
    357 # So avoid needing matplotlib attribute-lookup to access pyplot.
    358 from matplotlib import pyplot as plt
--> 360 plt.switch_backend(backend)
    362 plt.show._needmain = False
    363 # We need to detect at runtime whether show() is called by the user.
    364 # For this, we wrap it into a decorator which adds a 'called' flag.

File ~/anaconda3/lib/python3.10/site-packages/matplotlib/pyplot.py:279, in switch_backend(newbackend)
    276     current_framework = cbook._get_running_interactive_framework()
    277     if (current_framework and required_framework
    278             and current_framework != required_framework):
--> 279         raise ImportError(
    280             "Cannot load backend {!r} which requires the {!r} interactive "
    281             "framework, as {!r} is currently running".format(
    282                 newbackend, required_framework, current_framework))
    284 # Load the new_figure_manager() and show() functions from the backend.
    285 
    286 # Classically, backends can directly export these functions.  This should
    287 # keep working for backcompat.
    288 new_figure_manager = getattr(backend_mod, "new_figure_manager", None)

ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. use %matplotlib tk in jupyter of vscode

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
> ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

Thanks for filing this issue and sorry you are running into this.
Based on the above errorx, this is an issue with the Python environment.
Either you haven't selected the right kernel (python environment) or the packages are not installed correctly into the Python environment.

I would suggest trying to check stackoverflow as this isn't and issue with the Jupyter extension and its very specific to a particular package (tk)
