### ISSUE TITLE
kernel picker does not complete on remote server

### ISSUE THREAD

**Issue by seldomworks** [microsoft/vscode-jupyter#13827]
## Environment data

-   VS Code version: 1.79.2
-   Jupyter Extension version (available under the Extensions sidebar): v2023.5.1101742258
-   Python Extension version (available under the Extensions sidebar): v2023.10.1
-   OS (Windows | Mac | Linux distro) and version:  Windows
-   Python and/or Anaconda version:  Python 3.11.4 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...):  N/A
-   Jupyter server running: Remote 

## Expected behaviour
Login and allow me to pick a kernel

## Actual behaviour
Kernel picker does not complete
![image](https://github.com/microsoft/vscode-jupyter/assets/4422448/928c5f3b-4e0f-4de5-b29d-e893dbd2eb2f)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Select Kernel 
2. Enter URL
3.  Skip option to change name
4. Kene picker will spin forever

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
07:13:32.725 [error] Failed to setup finder for Select Kernel Error: 'Failed to parse remote URI http://vl-<username>-gridsdca:8888
    at qr (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1101742258-win32-x64\out\extension.node.js:2:1694682)
    at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1101742258-win32-x64\out\extension.node.js:17:126648
    at async Promise.all (index 2)
    at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1101742258-win32-x64\out\extension.node.js:17:126492
07:17:57.669 [info] Loading webview. View is notset
07:17:57.670 [info] Loading web view...
07:17:57.671 [info] Webview panel created.
```

</p>
</details>

**Comment by eizanprime** [comment]
I have the same issue

**Comment by NightMachinery** [comment]
https://github.com/microsoft/vscode/issues/186903

**Comment by wross2** [comment]
Same issue. Only started recently.

**Comment by thegunslingers** [comment]
> Same issue. Only started recently.

Ditto

**Comment by wross2** [comment]
Temporary workaround that worked for me: install VS Code Insiders and download the prerelease version of the jupyter plugin. Worked like a charm. More info here: https://github.com/microsoft/vscode-jupyter/issues/13699

**Comment by seldomworks** [comment]
> Temporary workaround that worked for me: install VS Code Insiders and download the prerelease version of the jupyter plugin. Worked like a charm. More info here: [#13699 (comment)](https://github.com/microsoft/vscode-jupyter/issues/13699#issuecomment-1598099657)

Thanks @wross2! I was about to try this but vscode updated and this seems to be fixed in the below version as well.  I didn't need to switch to VS code insiders  and I believe I am still using the released version of the Jupyter plugin.

Version: 1.80.0 (user setup)
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T15:06:02.407Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

Jupyter version: v2023.6.1001861915

**Comment by DonJayamanne** [comment]
Closing this as fixed, if this issue persists in the latest version of Jupyter extension 2023.6 (released moments ago), then please feel free to file a new issue
