### ISSUE TITLE
Undeprecate `jupyter.generateSVGPlots` and make it opt-in

### ISSUE THREAD

**Issue by eduardobehr** [microsoft/vscode-jupyter#13835]
# Request

- Keep the setting `jupyter.generateSVGPlots` and re-enable its support on GUI
  - This removes hurdles to those who wish to use the feature
- Make it `false` by default to prevent it from causing issues mentioned by #11168
  - This way, it keeps working as always and won't cause issues unnoticed by users 

- Remove deprecation warning when editing `settings.json`

# Motivation

The feature `jupyter.generateSVGPlots` has been deprecated by #12330 due to #11168 suggestion. I understand that this might have caused issues for some users, who probably plotted too much data, which would be well compressed by PNG rasterization, but would create huge XMLs files for SVG description. 

However, I believe there's still a great value on allowing SVG plots to persist, which are:
- Vector images, which provide better details when zoomed in when a PDF output is generated.
- Better GIT diff compression support. If a single detail changes in a PNG image, GIT must store a whole copy of the new file, as it's intrinsically binary. But if we change the same detail with SVG, only a few lines might change, as seen below:

PNG diff:
![image](https://github.com/microsoft/vscode-jupyter/assets/66493967/fe4749de-be3c-40d2-8de3-90ab902d705b)

SVG diff:
![image](https://github.com/microsoft/vscode-jupyter/assets/66493967/6722c618-7d94-4869-80f7-7889f68dc651)

Ideally, only the changed graphics feature would be updated, but unfortunately, many `xlink:href` IDs also change randomly. Still, most lines are preserved between commits.
---

**Comment by DonJayamanne** [comment]
You can get the same behaviour today by adding the following into your settings file
```jsonc
	"jupyter.runStartupCommands": [
		"import matplotlib_inline.backend_inline",
		"_VSCode_matplotLib_FigureFormats = matplotlib_inline.backend_inline.InlineBackend.instance().figure_formats",
		"_VSCode_matplotLib_FigureFormats.add('svg')",
		"matplotlib_inline.backend_inline.set_matplotlib_formats(*_VSCode_matplotLib_FigureFormats)"
	]
```
