### ISSUE TITLE
detecting kernels taking a long time

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#13839]
## Environment data

-   VS Code version: 1.79.2
-   Jupyter Extension version (available under the Extensions sidebar): v2023.5.1001582324
-   Python Extension version (available under the Extensions sidebar): v2023.10.1
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Jupyter server running: Local

## Expected behaviour

For it to detect kernels faster, I wouldn't expect longer than 3s

## Actual behaviour

Took a long time for "Detecting Kernels" text + spinner to go away 

## Steps to reproduce:

1. Create new notebook 

## Logs

Visual Studio Code (1.79.2, undefined, desktop)
Jupyter Extension Version: 2023.5.1001582324.
Python Extension Version: 2023.10.1.
Platform: win32 (x64).
Workspace folder ~\Dev\learning-csharp, Home = c:\Users\clregio
User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'jupyterTestcf'
14:12:54.373 [info] Start refreshing Interpreter Kernel Picker (1688332374373)
14:12:54.537 [info] Using Pylance
14:13:09.605 [info] End refreshing Interpreter Kernel Picker (1688332374373)
14:13:09.608 [warn] No interpreter for Pylance for Notebook URI "Untitled-1.ipynb"
14:13:11.768 [info] Process Execution: ~\Miniconda3\python.exe -m pip list
14:15:26.396 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd09e16cb08e8a63beaf1411b072454043fa9e1a88bc28e134506f9483ccbd2e699.c:\Users\<username>\Miniconda3\python.exe.c:\Users\<username>\Miniconda3\python.exe.-m#ipykernel_launcher  (Python Path: ~\Miniconda3\python.exe, Conda, base, 3.9.5) for 'Untitled-1.ipynb' (disableUI=true)
14:15:29.394 [info] Process Execution: ~\Miniconda3\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
14:15:29.410 [info] Process Execution: ~\Miniconda3\python.exe c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 7352
    > cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\pythonFiles\vscode_datascience_helpers
14:15:29.735 [info] Process Execution: ~\Miniconda3\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"3332ff80-a8ac-41b6-ba77-da0fe9dca96c" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\<username>\AppData\Roaming\jupyter\runtime\kernel-v2-7352dzOX0oSmyghJ.json
    > cwd: ~\Dev\learning-csharp
14:15:30.172 [info] ipykernel version & path 6.4.1, ~\Miniconda3\lib\site-packages\ipykernel\__init__.py for ~\Miniconda3\python.exe
14:15:32.485 [info] Started Kernel base (Python 3.9.5) (pid: 10836)
14:15:32.485 [info] Started new session cd265c5e-ce39-4ea1-81c1-dfc6ac0b4662
14:15:32.613 [info] Process Execution: ~\Miniconda3\python.exe c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\pythonFiles\printJupyterDataDir.py

**Comment by NightMachinery** [comment]
https://github.com/microsoft/vscode/issues/186903

**Comment by DonJayamanne** [comment]
@rebornix based on the logs, it seems Jupyter has correctly cleared the refresh indicator.
