### ISSUE TITLE
[FR] Connect to existing Jupyter kernel using kernel ID

### ISSUE THREAD

**Issue by NightMachinery** [microsoft/vscode-jupyter#13849]
When using a remote server for development in Jupyter, I port-forward the Jupyter server to my local machine, e.g., `http://127.0.0.1:8132`. Then I'll connect VSCode to it using the "Existing Jupyter server" option.

But this feature has terrible UX for selecting an already existing kernel from a server. It sometimes shows existing kernels, sometimes doesn't, and the only distinguishing feature the showed kernels (sometimes) have is that the name of the notebook file that started them is shown in parentheses. 

It'd be much easier if VSCode simply provided an option to use a kernel ID when connecting to a server. This ID can be obtained from within the notebook itself:
```
! pip install git+https://github.com/NightMachinery/PyNight.git

from pynight.common_jupyter import kernel_current_id, clipboard_copy_jupyter
from ipykernel.connect import get_connection_file

clipboard_copy_jupyter(kernel_current_id())

print(kernel_current_id())
print(get_connection_file())
```

emacs does this and it works really well. I can reconnect to an existing kernel without any troubles. But with VSCode, I pretty much have to start a new kernel every time I take a break between development.

```[tasklist]
### Tasks
```

**Comment by DonJayamanne** [comment]
I'm struggling to understand the feature request, is this for connecting to existing remote Jupyter servers or just local kernels?
If users would like to connect to a remote server like youe example, then the Kernel Id alone and connection file isn't sufficient, as users could be connecting to a remote server, in fact a connection file might work (without exposing a lot of ports, and its not just plain http protocol either).  
So users must provide the Url and the token/password information as well.

Or are you after the ability to connect to just a local kernel (thats running on the same machine), in which case providing a connection file could work?

**Comment by DonJayamanne** [comment]
Thank you for the suggestion, I will try to have a look into this option.

**Comment by DonJayamanne** [comment]
> It sometimes shows existing kernels, sometimes doesn't, and the only distinguishing feature the showed kernels (sometimes) have is that the name of the notebook file that started them is shown in parentheses.

Thanks for the great feedback rather than building a whole new UX for this, I'd prefer to fix the existing issues we have.
That being said, I would still like to explore connecting to kernels using connection files (though honestly I was only look into this for local kernels and not remote, as remote requires setup of ssh or the exposing the ports and the like)

Please can you try the latest pre-releasee version of the Jupyter extension in VS Code insiders and let me know how that works.
Or please wait for the next release (some time this week) and you can let me know what works and what does not.


> It sometimes shows existing kernels, sometimes doesn't

Please can you share the logs from the Jupyter output panel, as that contains information about the issues you might be running into

**Comment by NightMachinery** [comment]
@DonJayamanne Thanks!

1. How do I install the pre-release version?
2. Even if the current kernel selections' bugs are ironed out, there would still be no way to distinguish between kernels started from the same file. Perhaps you can add their ID to the current UI as a subtitle or sth?

**Comment by DonJayamanne** [comment]
> How do I install the pre-release version?

* Please install latest VS Code Insiders
* Open the extensions page, search for Jupyter and click the button `Switch to Pre-Release Version`
* Similarly please install the latest `Pre-Release` version of the Python extension

<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">

Optionally, wait a few days and the new release will be out (hopefully tomorrow)

> Even if the current kernel selections' bugs are ironed out, there would still be no way to distinguish between kernels started from the same file. Perhaps you can add their ID to the current UI as a subtitle or sth?

What do you mean by `no way to distinguish between kernels started from the same file`
Please can you give and example

thanks

**Comment by NightMachinery** [comment]
@DonJayamanne I don't have the switch button:
<img width="848" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/36224762/1509bbe3-3812-4b7c-8c14-ed32736aa4e6">

I am already on VSCode Insiders and Python's pre-release version.

**Comment by DonJayamanne** [comment]
Ok, that is the latest version, please could you you now replicate the issue and can you let me know what works and what does not.

Please share steps to repro the issues and share the output from the Jupyter output panel (as the logs contain information about any errors you could be running into).
Also, please do share some screenshots of the issues.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
