### ISSUE TITLE
Cell display overlap on output. 

### ISSUE THREAD

**Issue by paul-ada** [microsoft/vscode-jupyter#13843]
## Environment data

-   VS Code version: `1.79.2`
-   Jupyter Extension version (available under the Extensions sidebar): `v2023.5.1101742258`
-   Python Extension version (available under the Extensions sidebar): `v2023.10.1`
-   OS (Windows | Mac | Linux distro) and version: `MacOS v13.3.1`
-   Python and/or Anaconda version: `3.10.10`
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): `pyenv`
-   Jupyter server running: Local | Remote | N/A : `Local`

## Display Bug:

**Images below.**

1. This bug tends to happen when I scroll down and a cell is not in display anymore, after I scroll back up, this clustering will make a cell that has been executed already extend so that it overalps and covers its output. I am not sure what could be causing this.

<img width="1189" alt="Capture d’écran 2023-07-04 à 09 35 11" src="https://github.com/microsoft/vscode-jupyter/assets/94653185/5b1f74c7-93a8-4b6b-8a9c-260e9fadbf4a">. 
    
2. Caused by the same behavior, a cell with multiple lines will shrink to one line and become scrollable, leaving a trailing white space before the output space. 

<img width="1170" alt="Capture d’écran 2023-07-04 à 09 51 28" src="https://github.com/microsoft/vscode-jupyter/assets/94653185/a385e0eb-8ace-4064-9889-db1b5f7b0412">

**Comment by rahatzamancse** [comment]
I am also facing this display error.

**Comment by ColinConwell** [comment]
+1 to try and bump this issue. (Latest updates on VSCode and Extensions):

OS: MacOS Sonoma (14.5)
Version: 1.91.1 (Universal)
Jupyter Extension: v2024.6.0
Python Extension: v2024.10.0
Occurs across multiple Conda environments with Python 3.10 / 3.11
Occur with both Local and Remote (Linux Ubuntu 22.04.3 LTS) Jupyter servers / kernels

Example display issue below (multi-line cell collapse).
<img width="1234" alt="Screenshot 2024-07-26 at 2 33 09 PM" src="https://github.com/user-attachments/assets/6067da12-a4ea-4481-8ec0-4a1189184d14">
