### ISSUE TITLE
Unable to see the effect of javascript code in notebook

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#13855]
## Environment data

-   VS Code version: 1.80.0-insider (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2023.6.1001861915
-   Python Extension version (available under the Extensions sidebar): v2023.13.11862047
-   OS (Windows | Mac | Linux distro) and version: Windows11 22H2
-   Python and/or Anaconda version: conda 23.5.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Issue

1. Modify a notebook (e.g., add a few cells) but don't save the notebook yet
2. Try to access the current notebook as the user sees it at runtime, i.e.,
   ```js
   %%js
   var notebook_json = JSON.stringify(Jupyter.notebook.toJSON());
   Jupyter.notebook.kernel.execute('_cell_data = ' + JSON.stringify(notebook_json));
   ```
   then:
   ```python
   import json
   json.loads(_cell_data)
   ```

In classic Jupyter notebook, I'm able to see the cell data as the output from above example:
![image](https://github.com/microsoft/vscode-jupyter/assets/10833267/df3a0a73-f689-413b-b2dc-a6a59f0a5a5d)

In VS Code, I get the following error (`NameError: name '_cell_data' is not defined`):
![image](https://github.com/microsoft/vscode-jupyter/assets/10833267/82bc6e84-b3ef-4103-9d92-261233e6c972)

**Comment by DonJayamanne** [comment]
@minsa110 accessing the kernel directly from JavaScript is not supported.
In fact if you try the same code in Jupyter Lab you'll see that this does not work there either.
Note: this is by design

**Comment by minsa110** [comment]
I see. How did we arrive at the decision to not support it when Jupyter classic supports it (and thus users may expect it)? Would it be significant work to add this support?

Adding folks who brought this up first: @ekzhu @matteo-brucato

**Comment by ekzhu** [comment]
Is there an alternative to obtain the user's view of the notebook in JSON format inside the shell? Say we want to generate a summary of a visualization that's only available in the frontend of the notebook, but the code is running in the shell as a magic command.

**Comment by DonJayamanne** [comment]
Also, Jupyter lab does not support this at all, 
Given this, I think that’sa good enough reason to not support it

> Would it be significant work to add this support?

yes it would , 

> Jupyter.notebook
I’m Jupyter notebook their api exposes the notebook model (as they application is purely web based)  . Allowing users of the api to make changes directly to the notebook

However in vscode the renderer has access to just the one output, that’s it

> How did we arrive at the decision to not support it when Jupyter classic supports it (an

Jupyter lab spent support this, too much work, and a few other reasons that I cannot recall
