### ISSUE TITLE
from ..parent_package import something don't work in jupyter notebook cell of vs code

### ISSUE THREAD

**Issue by workhours** [microsoft/vscode-jupyter#13851]
there is no way to launch python code in cell as run python -m

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, and sorry you are running into this.
However I do not understand the problem you are running into

Please can you provide step by step instructions used to replicate this issue,
E.gl. open a notebook file, add a cell and run the cell..
Also please can you add screenshots as that would help me get a better idea of the problem

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
