### ISSUE TITLE
When opened from WSL, ipynb notebook suddenly gets "stuck" - cells wont run, kernel won't restart.

### ISSUE THREAD

**Issue by LDZuckerman** [microsoft/vscode-jupyter#13876]
Does this issue occur when all extensions are disabled?: Hard to tell, since need Python and Jupyter extensions to attempt. 

- VS Code Version: 1.79.2, 695af097c7bd098fbf017ce3ac85e09bbc5dda06, x64
- OS Version: Windows 11 Pro, version 22H2

Steps to Reproduce:

1. Open Ubuntu WSL, move to desired directory, activate desired conda environment.
2. Open VSCode instance using `code  .`
3. Open .ipynb notebook, wait for connection to kernel.
4. Click "run cell" arrow icon next to any cell, which turns to square (which would typically indicate cell is running).
5. See "spinning arrow icon" at the top of the screen indicating that VSCode is attempting to run the first command in the cell (e.g. `/path/to/file.ipynb > [spinning arrow icon] [first command in cell]`. Noteably, there is no spinning arrow or time count at the bottom of the running cell, as occurs when the cell runs correctly. 
6. Wait 30+ minutes with no change.
7. Attempt to stop cell execution by clicking square icon next to cell.  Nothing happens. 
8. Wait 30+ minutes with no change.
9. Click the Restart icon to attempt to restart Kernel. See pop-up that says `Restarting Kernel`, but nothing else changes.
10. Wait 30+ minutes with no change.
11. Attempt to close VSCode window. See pop-up indicating that changes will not be saved, allow this.
12. Re-open VSCode window as described above.
13. Sometimes this fixes the issue and things run, but more and more frequently over the past week it does not.

Note: sometimes restarting my computer fixes the issue, but not allways. 
Also, sometimes this issue randomly occurs after I have been successfully editing and running cells in a notebook for a while.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue and sorry you are running into this problem
Please can you try to replicate this issue with a simple cell such as `print("Hello World")` and then share the logs from the `Jupyter Output` panel

You can get there output using the command `Jupyter: Show Output`. Please remember to copy and upload all of the output.

Please ensure to copy and paste all of the output from the output panel when you have managed to replicate this issue.

**Comment by LDZuckerman** [comment]
Sorry for the delayed response. I have been waiting for the issue to happen again, and I will be sure to reply again with the requested output when it does.

**Comment by LDZuckerman** [comment]
The issue has presented itself again. Here is what the output panel shows when I attempt to run a cell that simply contains `print("Hello World")`: 

Visual Studio Code (1.80.0, wsl, desktop)
Jupyter Extension Version: 2023.6.1101941928.
Python Extension Version: 2023.12.0.
Platform: linux (x64).
Workspace folder /mnt/c/Users/Lea/OneDrive/TransitClassification_2023, Home = /home/lzucker1
16:15:01.775 [info] User belongs to experiment group 'FastKernelPicker'
16:15:02.391 [info] Start refreshing Kernel Picker (1689372902391)
16:15:02.398 [info] Using Pylance
16:15:04.266 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0fda72531e0bae826dfddf080a925520916a773a79752674d1ec3256ac429f738.~/miniconda3/envs/general/python.~/miniconda3/envs/general/python.-m#ipykernel_launcher  (Python Path: ~/miniconda3/envs/general/bin/python, Conda, general, 3.10.4) for '/mnt/c/Users/Lea/OneDrive/TransitClassification_2023/test.ipynb' (disableUI=true)
16:15:04.510 [info] End refreshing Kernel Picker (1689372902391)
16:15:08.861 [info] Process Execution: ~/miniconda3/envs/general/bin/python -m pip list
16:15:08.997 [info] Process Execution: ~/miniconda3/envs/general/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
16:15:09.205 [info] Process Execution: ~/miniconda3/envs/general/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"09310a4c-9534-4a1a-abb6-d653da9bfa20" --shell=9002 --transport="tcp" --iopub=9004 --f=~/.local/share/jupyter/runtime/kernel-v2-60797pjM8mrstCf0.json
    > cwd: /mnt/c/Users/Lea/OneDrive/TransitClassification_2023
16:15:10.135 [info] ipykernel version & path 6.24.0, ~/miniconda3/envs/general/lib/python3.10/site-packages/ipykernel/__init__.py for ~/miniconda3/envs/general/bin/python
16:15:12.302 [warn] Didn't get response for requestKernelInfo after 3042ms.
16:15:12.304 [info] Started Kernel general (Python 3.10.4) (pid: 6162)
16:15:12.304 [info] Started new session 46b6cce5-48cd-4202-af06-2f0f6045605c
16:16:46.686 [info] Handle Execution of Cells 0 for /mnt/c/Users/Lea/OneDrive/TransitClassification_2023/test.ipynb

**Comment by DonJayamanne** [comment]
@LDZuckerman 
Please can you try the solution described here https://github.com/microsoft/vscode-jupyter/issues/14519#issuecomment-1778289425
Let me know if that works for you.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
