### ISSUE TITLE
Support for YAML/JSONC cells

### ISSUE THREAD

**Issue by fourpoints** [microsoft/vscode-jupyter#13884]
I see a lot of programming languages are supported when selecting language mode. (I believe this list is determined by [LanguagesSupportedByPythonkernel](https://github.com/microsoft/vscode-jupyter/blob/main/src/platform/common/constants.ts#L114)). It would also be nice to also have some configuration languages to be supported. This would be helpful when exporting notebooks to other formats, as it would give a way to insert metadata through the editor.

This feature is technically supported by using the `raw` cell type, but this is missing syntax highlighting.

This would be similar to how many Markdown documents support having a metadata header, but would let it be its own cell instead of being contained in a markdown cell.

```md
---
title: document title
---
# heading

lorem ipsum
```

Wish list: YAML, JSONC/JSON5, HCL, INI, TOML. (XML is already supported.)

(It would also be nice if these cells automatically received a `configuration` tag, but that can already easily be done manually.)

**Comment by DonJayamanne** [comment]
> Wish list: YAML, JSONC/JSON5, HCL, INI, TOML. (XML is already supported.)

Thanks for this feature suggestion.
Lets assume these languages were supported.
What would happen if one were to try and run a cell.

The languages supported today (in the link you mentioned), have corresponding magics.
E.g. html, xml, javascript, latext, etc can be executed using cell magics.

However if YAML, JSONC, etc were added what does this mean
Is it just for syntax highlighting alone?

**Comment by DonJayamanne** [comment]
Thanks for the feature suggestion, unfortunately there haven't been enough upvotes or interest in this feature.
Hence deciding to closing this issue.
