### ISSUE TITLE
Implement interactive window with VS code notebook API

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1388]
TODO
- [x] #6465
- [ ] #6462
- [x] #6421
- [ ] #6424
- [x] #6449
- [x] #6456
- [x] #6458
- [x] #4257
- [x] #6457
- [x] #6418

This epic is switching the interactive window to use the VS code notebook API instead of our custom webview.

Here's a brief list of the requirements (in mostly priority order):
1. Support input from an external source (like a python file)` (already supported)
1. Show all cell outputs in a big read only list (already supported)
1. *Support direct input from a text editor that doesn't move. (`vscode upstream`)*
1. *Support hiding/collapsing code in cells (`vscode upstream - possibly part of Jupyter Outline`)* -- supported with `notebook.cell.collapseCellInput` command
1. Support copying code out of cells with some gesture (`extension`)
1. Support a history of text entered in the pinned text editor (`extension`)
1. Support theming (already supported)
1. Support intellisense (extension)
1. Support all cell outputs that a notebook does (already supported)
1. *Support restarting/interrrupting kernel*
1. Support variables
1. *Scroll as new inputs come in (behave like chat window) (`vscode upstream`)* -- supported with notebook focus commands:

![image](https://user-images.githubusercontent.com/30305945/121930225-fcc93d00-ccf6-11eb-9673-b56cffea8286.png)

**Comment by greazer** [comment]
This is done, other than a couple bug stragglers.
