### ISSUE TITLE
Remove extra click for remote jupyter server connection

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#13892]
When users connect to their own jupyter server, a common workflow:

* Add first server
  * Open Kernel Picker
  * Select Another Kernel
  * Pick "Existing Jupyter Server"
  * Paste the url and connect
* Add second server
  * Open Kernel Picker
  * Select Another Kernel
  * Pick "Existing Jupyter Server"
  * Now we have two options in the quick pick, a server added above and an action to connect to a new server
  * 🐛  Users then paste the url into the input box directly, since the quick pick input is only used for "filter", users couldn't move forward

**Comment by rebornix** [comment]
We can use the quick pick api to show a "Connect to xyz" action when users paste the url and then connect directly, this though might require https://github.com/microsoft/vscode/issues/121205 to allow us show validations on the quick input's input box.

**Comment by TylerLeonhardt** [comment]
When they paste in a url can it have a single item that says:

```
Connect to ${quickpick.value}
```

And then when they hit enter, it shows an input box with the value prefilled and then you have access to the validation ux?

**Comment by DonJayamanne** [comment]
See previous proposal here https://github.com/microsoft/vscode-jupyter/issues/13023#issue-1614314914
