### ISSUE TITLE
kernel selector does not show full path of the environment

### ISSUE THREAD

**Issue by braindevices** [microsoft/vscode-jupyter#13909]
according to [document](https://code.visualstudio.com/docs/datascience/jupyter-kernel-management#_jupyter-kernels)
We should see the full path of the environments.
This is quite important in multi-root workspace. I have a workspace we A, B, C, D 4 different root dirs. Each of them have different venv.

For some reason the jupyter notebook always openned with `A/venv` no matter where the notebook file located (maybe this is already a bug).

Then I have to choose the venv each time I open one of the notebook located in B, C, D.

However, the selector does not show the full path but `./venv/bin/python` this is really annoying.
I do not know which one is which.

## Environment data

-   VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:59:55.818Z)
-   Jupyter Extension version (available under the Extensions sidebar): v2023.5.1101742258
-   Python Extension version (available under the Extensions sidebar): v2023.12.0
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 22.04
-   Python and/or Anaconda version: 3.10.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

show full path with `~/` ![example](https://code.visualstudio.com/assets/docs/datascience/jupyter-kernel-management/noterbook-kernel-picker.gif)

## Actual behaviour

![Screenshot1](https://github.com/microsoft/vscode-jupyter/assets/7507440/505c0c22-45b8-47e3-8271-16f1efd45f5e)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

</p>
</details>

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, you seem to be using an old vesion of VS Code and Jupyter extension
Please update to the latest version, that should fix it.
