### ISSUE TITLE
Release latest version on OpenVSX

### ISSUE THREAD

**Issue by jrich100** [microsoft/vscode-jupyter#13919]
Hi!

I noticed that the Jupyter extension is behind by several version on the OpenVSX marketplace: https://open-vsx.org/extension/ms-toolsai/jupyter

I believe it is the responsibility of the extension developers to publish here, is this something that you are doing? And could you please update this to the latest version?

Thank you!

**Comment by jrich100** [comment]
Could version 2023.6.100 also be added?

**Comment by isidorn** [comment]
Thanks for opening this issue. But we are currently not publishing to open-vsx. We do not have control of that publisher on the open-vsx side. I believe it is published by open-vsx themselves and I suggest to reach out to them for more details.
