### ISSUE TITLE
Variable visualization issue with Juyter notebook

### ISSUE THREAD

**Issue by lucamcwood** [microsoft/vscode-jupyter#13917]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Hello,
I have been using notebooks inside VSCode and I noticed that the variable explorer is inconsistent with "Show variable snapshot in data viewer". If you expand the variable (example Python list) then the elements are different from the plain variable explorer. I think the correc values are the ones in the simple variable explorer as they match with the print command. I have experienced this problem with datetime objects (i.e. an array of datetimes).

![2023-07-14 16_14_52-](https://github.com/microsoft/vscode-jupyter/assets/96908267/b9b7acac-b6e3-41e5-98c4-8ffa775ef234)
![2023-07-14 16_15_26-Window](https://github.com/microsoft/vscode-jupyter/assets/96908267/8764e9cf-2b7c-4c5d-ab7b-db2cb4e04ac6)

### VS Code Version

Version: 1.76.2 (system setup) Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884 Date: 2023-03-14T17:55:54.936Z Electron: 19.1.11 Chromium: 102.0.5005.196 Node.js: 16.14.2 V8: 10.2.154.26-electron.0 OS: Windows_NT x64 10.0.19045 Sandboxed: No

### Jupyter Extension Version

v2023.2.1200692131

### Coding Language and Runtime Version

Python v3.11.3

### Language Extension Version (if applicable)

v2023.4.1

### Anaconda Version (if applicable)

Not using anaconda

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
closing as the jupyter data viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486
