### ISSUE TITLE
Jupyter crashing unexpectedly

### ISSUE THREAD

**Issue by HydroRaptor** [microsoft/vscode-jupyter#13916]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

tried to run jupyter notebook cell, can't run.
stopped unexpectedly.

### VS Code Version

1.80.1

### Jupyter Extension Version

v2023.3.100

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
can you share the logs from the output panel - run `Jupyter: show output` to open them
