### ISSUE TITLE
custom .env file cannot be loaded once in workspace

### ISSUE THREAD

**Issue by kubow** [microsoft/vscode-jupyter#13921]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Vscode workspace automatically loads `.env` file found in the root. So this thing works seamlessly:

```python
from os import environ
print(f'The value of sample variable is ({environ.get(SAMPLE)})')
```
However, if I want to have custom env files loaded upon a run of the file:

```python
from dotenv import load_dotenv  # dotenv_values
from os import getenv  # environ
# load environmnet variables
load_dotenv('./../.env.test')  
print(f'{getenv("SAMPLE")} is the sample value')
```

It does not proceed when I trigger it using vscode's  jupyter extension.
The jupyter notebook shows that value without any problem thus I suspect the extension fails. 
Not sure where to collect any logs though.

Also : I am using ipywidgets in the notebook itself and these values are tripled in the vscode version (compared with default jupyter notebook).

Running on latest Mint Linux
`Linux jav-mint 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linu`

### VS Code Version

Version: 1.80.1 Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771 Date: 2023-07-12T17:22:25.257Z Electron: 22.3.14 ElectronBuildId: 21893604 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Linux x64 5.15.0-76-generic

### Jupyter Extension Version

v2023.6.1101941928

### Coding Language and Runtime Version

Python 3.10.6

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue & I'm sorry you are running into this, 

> However, if I want to have custom env files loaded upon a run of the file:

What do you mean by `run of the file`?
Are you using a notebook or are you trying to run a python file?

If you would like to use custom .env files, then all you need to do is go into the settings and change the path to your `env` file , see here



![Screenshot 2023-07-19 at 05 47 21](https://github.com/microsoft/vscode-jupyter/assets/1948812/71f3601d-fc55-4b7b-9447-dbf778a84078)

**Comment by kubow** [comment]
Hi and sorry for the confusion. Everything I am presenting here is meant to be run inside the jupyter notebook. So when I refer to the **file run** I mean first time when you open the notebook and attempt to run a code.

The problem here is I have some variables already stored in the main `.env` file (which vscode uses as part of workspace) but I would like to append another set of variables from another `.env.test` file. Then this combination (`load_dotenv/getenv`) works in the native jupyter notebook but not in the vscode extension.

Anyway there is a workaround to keep those env files as a separate dictionary:
```python
from dotenv import dotenv_values
temp = dotenv_values('./../../.env.test')
SAMPLE = temp["SAMPLE"]
```
