### ISSUE TITLE
Use kernel selected for Pylance in Jupyter Notebook files

### ISSUE THREAD

**Issue by kevinMEH** [microsoft/vscode-jupyter#13920]
Currently, the python.interpreter.infoVisibility setting, when set to "onPythonRelated" does not consider .ipynb files as Python related files.

This is undesirable, because the Python extension can be used inside VSCode rendered Jupyter Notebooks, but users may not be able to select the correct interpreter for the Python extension while inside the Jupyter Notebook, which may cause the extension to report nonexistent errors.

For example:
![image](https://github.com/microsoft/vscode-python/assets/71391217/93fac925-660c-4b61-9d67-327a0665a88e)

Here, we are in an environment where the "torch" import is available. The Jupyter Notebook interpreter is set to the correct environment, called "pytorch". However, because the regular Python Extension (and as a result Pylance) is set to another "base" environment, the extensions says that the import cannot be resolved.

![image](https://github.com/microsoft/vscode-python/assets/71391217/9b0f5365-c101-465f-aa3d-d819b7407e19)

What a user can do is to go into a "py" file and then select the interpreter below, but that's a weird thing to do. What's better is if the interpreter option on the status bar is to be available on "ipynb" files.

Fix: I would submit a pull request, but I do not want to sign the Microsoft CLA. Here's how I think the issue is fixed: (I've never developed an extension before so I don't know if this is correct.)

`src/client/common/constants.ts`
```ts
/* eslint-disable camelcase */
/* eslint-disable @typescript-eslint/no-namespace */
export const PYTHON_LANGUAGE = 'python';
// ++++
export const JUPYTER_NOTEBOOK_LANGUAGE = "jupyter";
// ++++
export const PYTHON_WARNINGS = 'PYTHONWARNINGS';

export const NotebookCellScheme = 'vscode-notebook-cell';
export const InteractiveInputScheme = 'vscode-interactive-input';
```

`package.json`
```json
        "languages": [
            {
                "aliases": [
                    "Jinja"
                ],
                "extensions": [
                    ".j2",
                    ".jinja2"
                ],
                "id": "jinja"
            },
// ++++
            {
                "aliases": [
                    "Jupyter"
                ],
                "extensions": [
                    ".ipynb"
                ],
                "id": "jupyter"
            },
// ++++
            {
                "aliases": [
                    "pip requirements",
                    "requirements.txt"
                ],
```

`src/client/interpreter/interpreterService.ts`
```ts
// ++++
import { Commands, PYTHON_LANGUAGE, JUPYTER_NOTEBOOK_LANGUAGE } from '../common/constants';
// ++++
// ...
            get hidden() {
                const visibility = this.configService.getSettings().interpreter.infoVisibility;
                if (visibility === 'never') {
                    return true;
                }
                if (visibility === 'always') {
                    return false;
                }
                const document = this.docManager.activeTextEditor?.document;
                if (document?.fileName.endsWith('settings.json')) {
                    return false;
                }
                // ++++
                return document?.languageId !== PYTHON_LANGUAGE && document?.languageId !== JUPYTER_NOTEBOOK_LANGUAGE;
                // ++++
            }
```

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

Please can you look for the string `jupyterPythonPathFunction: Giving Pylance` in the logs and paste that here
That lets us know the ptyhon environment passed into the Python language server

**Comment by kevinMEH** [comment]
I did the above. The Jupyter notebook interpreter is set to "pytorch", and the regular Python interpreter is set to "base" (just like in the image above).

In the output, there is no "jupyterPythonPathFunction: Giving Pylance" anywhere. In fact, there is no mention of "Pylance" at all in the output.

That being said, there is a mention of the "base" environment being used for getPackageInformation instead of the "pytorch" environment:

```
debug 20:27:11.815: interpreterPackages getPackageInformation, Class name = r (started execution), Arg 1: {"interpreter":{"id":"C:\\PROGRAMDATA\\MINICONDA3\\PYTHON.EXE","sysPrefix":"C:\\ProgramData\\miniconda3","envType":"Conda","envName":"base","envPath":{"$mid":1,"path":"/C:/ProgramData/miniconda3","scheme":"file"},"architecture":3,"sysVersion":"3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]","version":{"raw":"3.10.12","major":3,"minor":10,"patch":12,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.10.12 ('base')","detailedDisplayName":"Python 3.10.12 ('base': conda)","uri":{"$mid":1,"fsPath":"c:\\ProgramData\\miniconda3\\python.exe","_sep":1,"external":"file:///c%3A/ProgramData/miniconda3/python.exe","path":"/C:/ProgramData/miniconda3/python.exe","scheme":"file"}}}
debug 20:27:11.815: Create activated Env, Class name = _ (started execution), Arg 1: {"allowEnvironmentFetchExceptions":true,"interpreter":{"id":"C:\\PROGRAMDATA\\MINICONDA3\\PYTHON.EXE","sysPrefix":"C:\\ProgramData\\miniconda3","envType":"Conda","envName":"base","envPath":{"$mid":1,"path":"/C:/ProgramData/miniconda3","scheme":"file"},"architecture":3,"sysVersion":"3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]","version":{"raw":"3.10.12","major":3,"minor":10,"patch":12,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.10.12 ('base')","detailedDisplayName":"Python 3.10.12 ('base': conda)","uri":{"$mid":1,"fsPath":"c:\\ProgramData\\miniconda3\\python.exe","_sep":1,"external":"file:///c%3A/ProgramData/miniconda3/python.exe","path":"/C:/ProgramData/miniconda3/python.exe","scheme":"file"}}}
```

Strangely enough, there is also a getPackageInformation call using the "pytorch" environment:

```
debug 20:27:12.097: interpreterPackages getPackageInformation, Class name = r (started execution), Arg 1: {"interpreter":{"id":"C:\\USERS\\.CONDA\\ENVS\\PYTORCH\\PYTHON.EXE","sysPrefix":"C:\\Users\\.conda\\envs\\pytorch","envType":"Conda","envName":"pytorch","envPath":{"$mid":1,"fsPath":"c:\\Users\\.conda\\envs\\pytorch","_sep":1,"path":"/c:/Users/.conda/envs/pytorch","scheme":"file"},"architecture":3,"sysVersion":"3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 17:59:51) [MSC v.1935 64 bit (AMD64)]","version":{"raw":"3.11.4","major":3,"minor":11,"patch":4,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.11.4 ('pytorch')","detailedDisplayName":"Python 3.11.4 ('pytorch': conda)","uri":{"$mid":1,"fsPath":"c:\\Users\\.conda\\envs\\pytorch\\python.exe","_sep":1,"external":"file:///c%3A/Users/.conda/envs/pytorch/python.exe","path":"/c:/Users/.conda/envs/pytorch/python.exe","scheme":"file"}}}
debug 20:27:12.097: Create activated Env, Class name = _ (started execution), Arg 1: {"allowEnvironmentFetchExceptions":true,"interpreter":{"id":"C:\\USERS\\.CONDA\\ENVS\\PYTORCH\\PYTHON.EXE","sysPrefix":"C:\\Users\\.conda\\envs\\pytorch","envType":"Conda","envName":"pytorch","envPath":{"$mid":1,"fsPath":"c:\\Users\\.conda\\envs\\pytorch","_sep":1,"path":"/c:/Users/.conda/envs/pytorch","scheme":"file"},"architecture":3,"sysVersion":"3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 17:59:51) [MSC v.1935 64 bit (AMD64)]","version":{"raw":"3.11.4","major":3,"minor":11,"patch":4,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.11.4 ('pytorch')","detailedDisplayName":"Python 3.11.4 ('pytorch': conda)","uri":{"$mid":1,"fsPath":"c:\\Users\\.conda\\envs\\pytorch\\python.exe","_sep":1,"external":"file:///c%3A/Users/.conda/envs/pytorch/python.exe","path":"/c:/Users/.conda/envs/pytorch/python.exe","scheme":"file"}}}
```

There is no mention of any of my other environments in the log, except for in the "Full interpreter list for  is" part.

So it seems that for getting package information only, the extension is using the Python interpreter "base" instead of the Jupyter notebook interpreter "pytorch".

---

To reproduce this issue:
1. Make an environment, and install a unique package.
2. Open a Jupyter notebook, and select the new environment's interpreter.
3. Create a cell and import the unique package.
4. Go to a regular Python file, and select a different interpreter from an environment which does not have the package installed.
5. Go back to the Jupyter notebook, and you will see an error for the package import saying `Import "unique" could not be resolved Pylance`

**Comment by DonJayamanne** [comment]
Can you share the first few lines of the logs, I'l like to see the versions
Please could you also share the version of Pylance used.
I'm after the following lines, upto `using Pylance`
```
Visual Studio Code - Insiders (1.81.0-insider, undefined, desktop)
Jupyter Extension Version: 2023.4.1011241018.
Python Extension Version: 2023.12.0.
Platform: darwin (arm64).
Workspace folder ~/crap, Home = /Users/donjayamanne
09:56:43.164 [info] Attempting to start a server because of preload conditions ...
09:56:43.166 [debug] Get Custom Env Variables, Class name = bc (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
09:56:43.167 [info] Start refreshing Kernel Picker (1689724603167)
09:56:43.172 [info] Using Pylance
```

**Comment by kevinMEH** [comment]
Oops, seems like I'm using an older version of the Python extensions:

```
Visual Studio Code (1.73.1, undefined, desktop)
Jupyter Extension Version: 2022.9.1303220346.
Python Extension Version: 2022.18.2.
```

I deliberately use an older version of VSCode, and I didn't realize that the newer versions of the Python extension did not have support for older versions of VSCode.

I assume that the problem I described above is fixed for the newer versions of the Python extensions? Apologies for the confusion. Feel free to close the issue.

**Comment by DonJayamanne** [comment]
> I assume that the problem I described above is fixed for the newer versions of the Python extensions? Apologies for the confusion. Feel free to close the issue.

this is fixed in the latest versions
