### ISSUE TITLE
after open ipynb file "cmd+c" error when copy from BITO（GPT）

### ISSUE THREAD

**Issue by Kurt-Shiwz** [microsoft/vscode-jupyter#13939]
## Environment data

-   VS Code version: 1.80.1 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2023.6.1101941928
-   Python Extension version (available under the Extensions sidebar): v2023.12.0
-   OS (Windows | Mac | Linux distro) and version: macOS 13.4.1
-   Python and/or Anaconda version: 3.11.4
-   Jupyter server running: Local 

## behaviour

when open .ipynb and then open 'Bito' or some other chatGPT extension, copy chatGPT's answer, but copy a cell (which mouse focus on).
But when open other file(such as .py/.sh/.log) don't has this problem.

![image](https://github.com/microsoft/vscode-jupyter/assets/7554917/839f47b7-3707-4672-b470-c4588fad91f4)

**Comment by roblourens** [comment]
You can open an issue on the extension you're using
