### ISSUE TITLE
Support getting list of all symbols defined in a Jupyter notebook 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-jupyter#13930]
Currently "Go to Symbol in Editor" shows the list of markdown cells by default. There's a setting that allows code cells to be included too, but there isn't a way to get the list of all symbols from a notebook file.

This feature request came up as part of a conversation with a screen reader user, who constantly uses symbol navigation as part of their workflow. They often switch to Python files just for that functionality. 

It would be great if it would be possible to get the list of all symbols defined in a notebook file

**Comment by amunger** [comment]
related discussion about code/symbols in the outline view https://github.com/microsoft/vscode/issues/134055
