### ISSUE TITLE
Failed to start the Kernel.  0.00s - Debugger warning: It seems that frozen modules are being used, which may 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off 0.00s - to python to disable frozen modules. 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation. C:\Users\Faisal Shah\AppData\Roaming\Python\Python311\site-packages\traitlets\traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\Users\\Faisal Shah\\AppData\\Roaming\\jupyter\\runtime\\kernel-v2-9328mvuqLYLAUE61.json' instead of '"c:\\Users\\Faisal Shah\\AppData\\Roaming\\jupyter\\runtime\\kernel-v2-9328mvuqLYLAUE61.json"' if you require traitlets >=5.   warn( Bad address (C:\projects\libzmq\src\epoll.cpp:100).  View Jupyter [log](command:jupyter.viewOutput) for further details.

### ISSUE THREAD

**Issue by farooqiFaisal** [microsoft/vscode-jupyter#13949]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filling this issue
However since no information has been provided I'm closing this issue
Please feel free to create a new issue with the information requested in the issue template
