### ISSUE TITLE
Vim recenter cursor vertically (zz) doesn't work

### ISSUE THREAD

**Issue by kimichenn** [microsoft/vscode-jupyter#13955]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

## Steps to reproduce:

1. Make sure the [VSCode Vim extension](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) is installed
2. Open any `.ipynb` file.
3. Create a code cell and write some code in it.
4. In normal mode, press `zz`.

### Expected:
The screen should recenter vertically to where the cursor is.

### Actual:
`zz` has no response.

### VS Code Version

Version: 1.80.1 (user setup) Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771 Date: 2023-07-12T17:22:07.651Z Electron: 22.3.14 ElectronBuildId: 21893604 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Windows_NT x64 10.0.19045

### Jupyter Extension Version

v2023.6.1101941928

### Coding Language and Runtime Version

Python 3.10.11

### Language Extension Version (if applicable)

Python Extension v2023.12.0

### Anaconda Version (if applicable)

conda 4.12.0

### Running Jupyter locally or remotely?

Local
```[tasklist]
### Tasks
```

**Comment by DonJayamanne** [comment]
Sorry for never getting back to you on this issue, somehow this slipped through the cracks.
We have made a lot of improvements and fixes in this space and believe this may have been resolved.
Please ensure you update to the latest version of VS code and the extensions.
Closing as I believe it may have been resolved,
If not please ping here and I'll reopen this or feel free to create a new issue.
