### ISSUE TITLE
Unexpected behaviour of rendering multiple the same instances of ipywidgets.Output

### ISSUE THREAD

**Issue by dsonyy** [microsoft/vscode-jupyter#13950]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Vscode notebook has a problem with rendering correctly a cell with the following code:
```py
import ipywidgets
from IPython.display import display

out = ipywidgets.Output()

with out:
    print("test")
    
display(out)
display(out)
```

**Expected behaviour:**
The same as in Jupyter Notebooks and Jupyter Lab. Cell should render the same instance of a widget two times:
```
test
test
```

**Actual behaviour:**
The widget is rendered only once:
```
test
```
If we add `time.sleep` between two `display` calls:
```py
import ipywidgets
from IPython.display import display
import time

out = ipywidgets.Output()

with out:
    print("test")
    
display(out)
time.sleep(1)
display(out)
```
the behaviour  is correct - two widgets are rendered which is worrying.

### VS Code Version

1.80.1

### Jupyter Extension Version

v2023.6.1101941928

### Coding Language and Runtime Version

Python 3.9.7

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, I can replicate this at my end.
Will look into this.
