### ISSUE TITLE
Custom restart sequences

### ISSUE THREAD

**Issue by nicoborghi** [microsoft/vscode-jupyter#13962]
When working with long Jupyter notebooks, it can be tedious to restart the kernel, run the first cells, and then scroll back to the working cell. It would be helpful to have customizable restart sequences that allow users to specify the cells that should be executed after the kernel is restarted.

For example, a user might want to specify a restart sequence that includes the following steps:
1. Restart the notebook kernel
2. Run the first cell
3. Run the current cell

This would allow the user to restart the kernel and import the modules without having to scroll through the notebook.

**Comment by DonJayamanne** [comment]
Thanks for filing this feature request, given the fact that there haven't been any upvotes on this issue since it was open, I'm closing this.
