### ISSUE TITLE
rendered markdown cells are sometimes just empty space

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#13964]
I had instances of writing a markdown, pressing execute (which does not execute anything, just gets you out of editing) and then the cells looks empty, taking the same space but just a big box empty. If I edit again I see my original text, but this is defo a bug. Not a big deal though.

...might be due to an unstable internet connection (even though I never saw something like this in Jupyter after 5-6y, and I've been working with VScode for 6 months and saw it 5-6 times).

_Originally posted by @marctorsoc in https://github.com/microsoft/vscode-jupyter/issues/13338#issuecomment-1645393350_

**Comment by amunger** [comment]
@marctorsoc - could you provide a screenshot and the actions that led to this if you see it again?

**Comment by marctorsoc** [comment]
I'll post when I see it again, but unfortunately it's not something I know how to reproduce

**Comment by marcglobality** [comment]
To be honest, it's been a long time since I saw this, and at the time I did not have a very stable connection. So that might be it. If you want i can reopen if it happens again
