### ISSUE TITLE
Test: Continue On on Codespace

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#13974]
Refs: [#13577](https://github.com/microsoft/vscode-jupyter/issues/13895)

- [x] Web @DonJayamanne  
- [x] Web @eleanorjboyd 

Complexity: 2

Authors: @rebornix  

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2313974%0A%0A&assignees=rebornix)

---

#### Steps
- Open a github repository without dev containers preset
- Press . to open github.dev
- Install Jupyter extension
- Create a new notebook document
- Go to Kernel Picker -> Select Another Kernel -> Connect to Codespace
- Pick a sku
- Once the server is created, pick the ipykernel kernel, run a cell
- Once the cell executed succesfully, you should now see an option on the notebook toolbar "Continue On"

Now you should be able to navigate to the Codespace instance under the hood, with the changes you made in the workspace.

@DonJayamanne @eleanorjboyd this test requires knowledge of Jupyter so I manually assigned this test to you, thanks!

**Comment by eleanorjboyd** [comment]
What is the step `Once the cell executed succesfully, you should now see an option on the notebook toolbar "Continue On"`? Where do I find this toolbar? I am seeing it successfully in the terminal tab.

**Comment by eleanorjboyd** [comment]
@rebornix pointed out I was not on insiders. Here were the steps I took after changing to see the continue on in toolbar
Steps to do so:
1. in github.dev click on the "gear" icon
2. select switch to insiders
3. confirm you are on pre-release Jupyter extension 
4. reload window
5. execute cell in notebook (might require repicking the kernel, codespace should show up as a kernel option)
6. continue on will appear in the toolbar

**Comment by DonJayamanne** [comment]
I am unable to select a kernel, get the following errors
![Screenshot 2023-07-26 at 06 52 58](https://github.com/microsoft/vscode-jupyter/assets/1948812/5c776303-38e2-4ab0-891e-25682a05a822)
