### ISSUE TITLE
"detect kernel" present while building codespace

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode-jupyter#13978]
Testing #13974

This is a small item but I think having the spinner still saying "detecting kernel" after I have selected to build a new codespace is confusing (also because I see the notification in the bottom about the codespace getting set up / starting the server). I think that maybe the detecting kernel notification should change the wording or disappear during the codespace setup.
<img width="1700" alt="Screenshot 2023-07-25 at 9 05 52 AM" src="https://github.com/microsoft/vscode-jupyter/assets/26030610/00801ee9-dec4-4464-9de8-74ce665379b6">

**Comment by DonJayamanne** [comment]
Duplicate https://github.com/microsoft/vscode/issues/206007
