### ISSUE TITLE
Jupyter interactive output copy & pasting.

### ISSUE THREAD

**Issue by notrichardren** [microsoft/vscode-jupyter#13977]
When I have a large output, I can't CMD+A and CMD+C to copy it all. Instead, I have to drag my mouse across the output (often, not even capturing all of the output).

<img width="887" alt="Screenshot 2023-07-25 at 12 37 33 PM" src="https://github.com/microsoft/vscode-jupyter/assets/34405553/bad10781-6577-4fcf-b4b3-9b22e6b68599">

I'd like to be able to easily select an output block and CMD+A (select all, or some other shortcut to select all) and CMD+C (copy) to copy everything.

**Comment by amunger** [comment]
There is a copy output command available for all notebook outputs. Let us know if that doesn't work for you.
![image](https://github.com/microsoft/vscode-jupyter/assets/2019016/732b1ea4-2948-41f0-a123-11d967a24624)
