### ISSUE TITLE
Unable to choose Python env as kernel in Codespaces

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#13972]
## Environment data

-   VS Code version: 1.81.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2023.7.1002071100
-   Python Extension version (available under the Extensions sidebar): v2023.13.12051535
-   OS (Windows | Mac | Linux distro) and version: Windows, on Edge
-   Python and/or Anaconda version: Python 3.10.8 (default on Codespaces)

## Expected behaviour

- Opened default Codespaces (i.e., created Codespaces from repo from the browser)
- Installed Jupyter and Python extensions
- Verified that Python ext is activated and that there are Python envs
  ![image](https://github.com/microsoft/vscode-jupyter/assets/10833267/2b10f2d7-a029-4454-aad8-23da304b6a33)
- Opened ipynb -> kernel selector to select one of the Python env
- Expected to see `Python environments...` as an option

## Actual behaviour

Only see `Existing Jupyter server...` as an option:
![image](https://github.com/microsoft/vscode-jupyter/assets/10833267/fa3a703b-f375-415f-a40e-1391797868a4)

**Comment by minsa110** [comment]
Closing in favor of https://github.com/microsoft/vscode-jupyter/issues/13911

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode/issues/189280
