### ISSUE TITLE
Remove old API from Python extension

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13986]
@karrtikr /cc
I'll work on this in debt week.

**Comment by karrtikr** [comment]
Thanks, wasn't clear on whether APIs under `datascience` scope are meant to be private for Jupyter or not.

**Comment by DonJayamanne** [comment]
They are definitely private, hence they can be removed from your npm package (not useful for anyone else), I will remove the code from your repo after a review.

**Comment by eleanorjboyd** [comment]
does this need to be verified?

**Comment by DonJayamanne** [comment]
I do not think so, we just deleted dead code from the repo
