### ISSUE TITLE
Document Jupyter related types in `@vscode/python-extension` npm package

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode-jupyter#13982]
We now have [a npm package](https://github.com/microsoft/vscode-python/issues/20949#issuecomment-1639159916) which carries the Python extension api types.

See https://github.com/microsoft/vscode-python/issues/21690#issue-1820995425. If you would like these types to be present in the `@vscode/python-extension` API, these should likely be documented. Otherwise let us know and we'll remove these types from the package.

Types for package are defined here: https://github.com/microsoft/vscode-python/blob/main/src/client/api/types.ts

**Comment by DonJayamanne** [comment]
> If you would like these types to be present in the @vscode/python-extension API, these should 

I don't think there's a need to expose this api in the public npm as they are useful only to thr Jupyter extension. 

In a way it's private for Jupyter extension, and cannot be used by any other extension, if called by others then it's a noop. As the result of calling that API is that python extension will call back into Jupyter extension

**Comment by karrtikr** [comment]
Actually there're other types as well: https://github.com/microsoft/vscode-python/blob/8b9bca1fd5a684d454e0d97583642cb46553241e/src/client/api/types.ts#L128-L167, which seem to be Jupyter specific, which I think you would like to include in the package. I think these are specific for dataviewer: https://github.com/microsoft/vscode-python/blob/8b9bca1fd5a684d454e0d97583642cb46553241e/src/client/api/types.ts#L38-L49

**Comment by DonJayamanne** [comment]
No, we don't need those either.
I do not think we should publish anything that very specific & private for Jupyter extenssion.
Please feel free to remove them from the npm package
