### ISSUE TITLE
Kernel Runs cells indefinitely 

### ISSUE THREAD

**Issue by dustykeyboard1** [microsoft/vscode-jupyter#13998]
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The cells run on a loop forever. I constantly have to restart the kernel and lose all my data/variables. It happens repeatedly. I have restarted the kernel. Uninstalled and reinstalled the jupyter extension, restarted my mac, quit and re-opened VS code. No clue why this is happening. 

### VS Code Version

1.68.0

### Jupyter Extension Version

v2022.5.1001601848

### Jupyter logs
```
info 10:29:49.355: Cell 7 executed with state Success
info 10:29:49.407: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
info 10:29:49.426: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
info 10:29:49.452: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(batch_predictions))
info 10:29:49.467: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(batch_predictions))
info 10:29:50.33: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(scaled_data))
info 10:29:50.50: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(scaled_data))
[I 10:29:51.195 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
[I 10:29:51.197 NotebookApp] Starting buffering for dbba2645-934c-47c5-bc12-bed53c5c8575:b9467747-eecb-488e-851f-240b2f42c09d
[I 10:29:51.201 NotebookApp] Restoring connection for dbba2645-934c-47c5-bc12-bed53c5c8575:b9467747-eecb-488e-851f-240b2f42c09d
```

### Coding Language and Runtime Version

Python 3.11.4

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Sorry I never got back to you on this.

Please note, you seem to be using a very old version of VS Code and Jupyter extesnion
Plese update to the latest versions and if it still occurs, please do file a new issue and we'll look into it.
