### ISSUE TITLE
Incorporate Sanddance into data visualization workflows

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#140]
I guess this would be an epic, but here's stuff we talked about (that I can remember, feel free to add more)

- Integrate Tim's work
- Integrate directly into our data viewer
- Automate the discovery or usage of their ipywidget
- Generate python code from pieces of their UI

**Comment by IanMatthewHuff** [comment]
Closing in favor of #1135 which has more info.
