### ISSUE TITLE
Text in traceback gets incorrectly interpreted as HTML

### ISSUE THREAD

**Issue by camillol** [microsoft/vscode-jupyter#14002]
Type: <b>Bug</b>

1. Make an `.ipynb` notebook.
2. Put this in a code cell: `raise ValueError(f"Unknown type: {type(lambda x:x)}")`
3. Run it.

Expected result: should display this:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[21], line 1
----> 1 raise ValueError(f"Unknown type: {type(lambda x:x)}")

ValueError: Unknown type: <class 'function'>
```

See good screenshot in Jupyter notebook outside of VSCode:
<img width="729" alt="Screenshot 2023-07-28 at 12 51 40 PM" src="https://github.com/microsoft/vscode-jupyter/assets/196272/167adc87-12be-4a0c-8b8e-2ad654aa8ee8">

Actual result: displays this:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[179], line 1

----> 1 raise ValueError(f"Unknown type: {type(lambda x:x)}")

ValueError: Unknown type: 
```

See bad screenshot in VSCode:

<img width="616" alt="Screenshot 2023-07-28 at 12 52 44 PM" src="https://github.com/microsoft/vscode-jupyter/assets/196272/c59174f8-59cb-4cbc-9a72-dbb2cbc41b9a">

Note that the `<class 'function'>` part is missing, presumably because it gets interpreted as HTML. Or it gets haphazardly stripped, instead of getting properly escaped.

Extension version: 2023.6.1101941928
VS Code version: Code 1.80.2 (Universal) (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T21:05:41.366Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 774d68bb-c124-4b34-ac13-a08d9a3197de|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
vscrp:30673768
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
gsofa:30797621
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014:30797589

```

</details>

**Comment by amunger** [comment]
duplicate

**Comment by camillol** [comment]
Could you share the number of the duplicate issue so I can follow it?

**Comment by amunger** [comment]
https://github.com/microsoft/vscode/issues/177405

**Comment by camillol** [comment]
Thank you!
