### ISSUE TITLE
The extension is stuck and no output is given

### ISSUE THREAD

**Issue by Saltsmart** [microsoft/vscode-jupyter#14004]
Type: <b>Bug</b>

When I update Jupyter extension and VSCode, they give no output when I run a cell.

Extension version: 2023.7.1001901100
VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (10.27GB free)|
|Process Argv|--crash-reporter-id deaad0bf-2897-480e-b8cf-04d2a61dc2e3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014cf:30797590

```

</details>

**Comment by Saltsmart** [comment]
![problem-stuck](https://github.com/microsoft/vscode-jupyter/assets/40828952/0f8b8aea-6385-4020-a0c9-4bfa119af02c)

**Comment by Saltsmart** [comment]
When I switch to another version (v2023.6.1001861915), this still happens.

**Comment by DonJayamanne** [comment]
Thank for filing this issue and sorry you are running into this.
Please can you try the following:
* Create a new notebook
* Add just one cell to that notebook with the code `print("Hello World")`
* Reload VS Code
* Run that cell
* Finally please could you upload the logs from the `Jupyter` output panel, you can get there output using the command `Jupyter: Show Output`. Please remember to copy and upload all of the output.

**Comment by Fred-Wu** [comment]
I am just about to report the same on 

OS: macOS Ventura 13.5, M1
VS Code version: Code 1.80.2
Jupyter: v2023.6.1101941928


This happens to me while jupyter variables pane keeps "loading variables" from a file, which converts the file to a list and dict of 400,000.  

<img width="552" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/4111978/d58a83f6-6bf7-44dd-8311-56f1d80b142a">

<img width="409" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/4111978/9f34d780-8fd4-4fc1-936b-e4d155edfb7a">



But event after "VARIABLES" pane loading successfully,   it was still stuck when I just tried to show the first one. 

<img width="351" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/4111978/32bf9aab-ad54-4cb5-b909-3a08b5a769f2">

When I restarted Kernel, the output pane shows the following

```
[error] stat() failed for "vscode-notebook-cell:~/Documents/Studies/Coursera/Deep%20Learning/Sequence%20Models/Week%202/Operations_on_word_vectors_v2a.ipynb#W3sZmlsZQ%3D%3D" 
[Unavailable (FileSystemError): ENOPRO: No file system provider found for resource 'vscode-notebook-cell:~/Documents/Studies/Coursera/Deep%20Learning/Sequence%20Models/Week%202/Operations_on_word_vectors_v2a.ipynb#W3sZmlsZQ%3D%3D'
	at ii.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:27301)
	at Object.stat (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:24574)
	at async mu.exists (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:17:17828)
	at async l_.getWorkingDirectory (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:465224)
	at async l_.getCode (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:464690)
	at async Promise.all (index 1)
	at async eg.gatherInternalStartupCode (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:963)
	at async eg.initializeAfterStart (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:17:219511)
	at async eg.restart (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:17:213846)
	at async Jy.wrapKernelMethodImpl (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:198557)] {
  code: 'Unavailable'
```

Otherwise, running codes just show some boring messages

```
11:33:11.888 [info] Generated code for 1 = <ipython-input-1-1d7d0b7308ea> with 2 lines
11:33:11.912 [info] Kernel acknowledged execution of cell 6 @ 1690767191907
11:33:11.915 [info] End cell 6 execution @ 1690767191913, started @ 1690767191907, elapsed time = 0.006s
11:33:16.739 [info] Generated code for 2 = <ipython-input-2-e76c3f3a02a5> with 2 lines
11:33:16.759 [info] Kernel acknowledged execution of cell 7 @ 1690767196757
11:33:18.918 [info] End cell 7 execution @ 1690767198916, started @ 1690767196757, elapsed time = 2.159s
11:33:22.081 [info] Generated code for 3 = <ipython-input-3-4bde853e0d27> with 1 lines
11:33:22.098 [info] Kernel acknowledged execution of cell 8 @ 1690767202096
11:33:24.209 [info] End cell 8 execution @ 1690767204207, started @ 1690767202096, elapsed time = 2.111s
11:35:20.532 [info] Generated code for 4 = <ipython-input-4-1d7d0b7308ea> with 2 lines
```

**Comment by Saltsmart** [comment]
It may be related with the package `ctypes`. @DonJayamanne 
The conda env is totally broken (same as [this issue](https://github.com/conda/conda/issues/12531) 
I reinstalled Anaconda and it's now working properly.
It's recommended **not** to close this issue since @Fred-Wu or someone else has this problem.

**Comment by DonJayamanne** [comment]
@Fred-Wu Please can you file a seperate issue, as your issue is completely separate. its got to do with the variable viewer blocking execution (due to the size of the content, being returned for variables)

 As they are unrelated, I'm closing this.
Once again @Fred-Wu please do create a new issue

**Comment by DonJayamanne** [comment]
@Fred-Wu I created the issue here https://github.com/microsoft/vscode-jupyter/issues/14006
