### ISSUE TITLE
dataframe column completions don't work with latest jedi 0.19.0

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode-jupyter#14012]
First failing [commit](https://github.com/microsoft/vscode-jupyter/tree/a9f4179979fd4a57df14f8116e2ffa5bac97a368)

Logs:

```
  1) DataScience - VSCode Intellisense Notebook - (Code Completion via Jupyter) withJedi @lsp
       Dataframe column completions:

      Error: Unable to get completions for cell vscode-notebook-cell:/home/runner/work/vscode-jupyter/vscode-jupyter/temp/emptyPythonf61110b1-b736-4a2e-9a48-dc368a72ab10..ipynb#W4sZmlsZQ%3D%3D
      + expected - actual


      at Timeout.<anonymous> (src/test/common.ts:102:20)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
```

**Comment by amunger** [comment]
run failure link https://github.com/microsoft/vscode-jupyter/actions/runs/5716878516/job/15491670585#logs

**Comment by amunger** [comment]
repro steps

set config "jupyter.enableExtendedKernelCompletions": true
%pip install jedi==0.19.0
%pip install pandas
restart the kernel
run the cell
```
import pandas as pd
data = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
        'age': [25, 30, 35, 40],
        'city': ['New York', 'Paris', 'London', 'Tokyo']}
df = pd.DataFrame(data)
```
add a cell below, type `df.name.add` and trigger completions `ctrl+.`

:bug: no completions

**Comment by Justype** [comment]
Same issue. I am using code-server. So I can only use Jedi. The intellisense only works in the first chunk. If you add another chunk, the intellisense does not work.

**Comment by DonJayamanne** [comment]
Works now, closing as completed.
