### ISSUE TITLE
Pre-connect to the selected kernel before running the first command

### ISSUE THREAD

**Issue by sayol** [microsoft/vscode-jupyter#14063]
According to my experience, after selecting a kernel, Jupyter is not connected to the kernel until the first execution is perform. And in this case, we have to wait a plenty of time to get connected. We would like Jupyter to connect in advance to the a kernel after the kernel is selected.

**Comment by amunger** [comment]
It seems to auto-start for me, can you check if you have `"jupyter.disableJupyterAutoStart": false` (default)

**Comment by DonJayamanne** [comment]
> We would like Jupyter to connect in advance to the a kernel after the kernel is selected.

We alrteady do this today for local kernels, please can you confirm you do not have this setting `"jupyter.disableJupyterAutoStart": false`
Or are you connecting to a remote Kernel, with remote Jupyter kernels, we do not auto start (pre-warm) the kernels, as its possible users might not want to run some code.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
