### ISSUE TITLE
Copilot is not able to access context of other jupyter cells

### ISSUE THREAD

**Issue by cidersec** [microsoft/vscode-jupyter#14064]
## Environment data

-   VS Code version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
-   Jupyter Extension version (available under the Extensions sidebar): v2023.6.1101941928
-   Python Extension version (available under the Extensions sidebar): 2023.14.0
-   OS Mac: 13.5
-   Python and/or Anaconda version: 3.10.6
-   Type of virtual environment used conda: conda 4.13.0
-   Jupyter server running: Local

## Expected behaviour

Copilot uses context of other cells around it.

## Actual behaviour
Copilot gives generic suggestions within a cell.

Related to this https://github.com/orgs/community/discussions/62569
but I don't know the best repo for the bug.

## Steps to reproduce:

<img width="1169" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/108358451/3e6f1fa2-c0ec-4005-ada3-cf24ffdbf698">

1.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel 

(<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

Just seeing a bunch of lines like
```
07:26:33.476 [info] Kernel acknowledged execution of cell 6 @ 1691148393474
07:26:33.532 [info] End cell 6 execution @ 1691148393530, started @ 1691148393474, elapsed time = 0.056s
```

</p>
</details>

**Comment by rebornix** [comment]
Please file against the Copilot extension.
