### ISSUE TITLE
Incorrect cell execution time with remote jupyter kernel

### ISSUE THREAD

**Issue by stas-sl** [microsoft/vscode-jupyter#14072]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When I connect to an existing remote jupyter instance, cell execution time becomes incorrect. For some reason it starts from some offset like 13-14 seconds, and only after execution is finished it shows actual correct number. Restarting vscode, reopening the notebook, reconnecting to jupyter doesn't help. However with local jupyter there is no such issues.

https://github.com/microsoft/vscode-jupyter/assets/4602302/dcbf1a6f-b2d1-4037-9e15-e5848cad25f6

### VS Code Version

1.81.0

### Jupyter Extension Version

v2023.7.1002162226

### Coding Language and Runtime Version

Python 3.11.3

### Anaconda Version (if applicable)

anaconda3-2023.07-0

### Running Jupyter locally or remotely?

Remote

**Comment by skwde** [comment]
Same problem here. My offset is around 7930 min.

The problem also appears here <https://github.com/microsoft/vscode-jupyter/issues/12399>.

**Comment by stas-sl** [comment]
@skwde, thanks for linking previous issue. Somehow I haven't found it myself. After reading comments there I realized that it might be due to time difference with remote host. And actually I can confirm that this was the reason. I didn't have NTP enabled on remote host for some reason, so time was off by 14 seconds. After enabling it, the offset has gone. So it kind of solves the issue, although I don't know why not measure time either completely on client or on server, so it doesn't depend on time difference between client and server.
