### ISSUE TITLE
Remote connection between code-server and JupyterHub drops intermittently

### ISSUE THREAD

**Issue by BouarfaMahi** [microsoft/vscode-jupyter#14085]
I've been experiencing an issue where the remote connection between code-server and JupyterHub stops after a varying number of hours. The disconnection is inconsistent and does not happen after a specific time, making it hard to pinpoint the exact cause.

## Environment data

code-server version: 4.16.1
JupyterHub version: 3.0.0
Operating System: Ubuntu 22.04
Browser : Brave 1.56.20

## Expected behaviour

The connection between code-server and JupyterHub should remain stable and not disconnect on its own without any user intervention or specific trigger.

## Actual behaviour

The remote connection drops randomly after an uncertain number of hours.

## Steps to reproduce:

1- Setup code-server and connect it with JupyterHub/token.
2- Work on the environment for a few hours.
3- Observe the intermittent loss of connection between the two platforms.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filling this issue
What version of the Jupyter extension are you using?

Pleat can you share the logs from the Jupyter output panel as follows 
* You can get to the output panel using the command `Jupyter: Show Output`. Please remember to copy and upload all of the output.

**Comment by BouarfaMahi** [comment]
Jupyter extension: v2023.4.1001091014   Pre-Release

the Juputer: Show Output command gives an empty content.

**Comment by BouarfaMahi** [comment]
I am using the pre release version because of this issue

https://github.com/microsoft/vscode-jupyter/issues/13759

**Comment by DonJayamanne** [comment]
I would suggest you try to upgrade to the latest version of the jupyter extension.
Unfortunately the version you are using is too old and I cannot try to find if there's a bug in that version and not in the latest version.
If you are unable to install the latest version, then I'm sorry but I'm not sure I can do much there.

Please let me know if you are able to install the latest version.
I haven't tried code-server, but if that doesn't let you upgrade, then I would suggest installing VS Code or the like.

**Comment by BouarfaMahi** [comment]
Again the extension library for code-server is not the same as the one for VSCode. My open source project is using code-server and it is not possible to switch to VSCode.
