### ISSUE TITLE
Pop up informing the user that debugging won't work with a particular version

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-jupyter#14080]
Please see this issue: https://github.com/microsoft/vscode-jupyter/issues/12847

The initial suggestion was to upgrade ipykernel on Compute instances but Azure ML users tend to upgrade slower because they don't want to break the reproducibility of the combination of other python modules on the image so customers have run into this. 

It would be ideal if Jupyter extension can detect this case and let the users know that debugging doesn't work with that particular version of ipykernel

**Comment by DonJayamanne** [comment]
@shsuman I believe this is no longer applicable as the AzML machines have been upgraded, isn't that right?

Closing this issue for now, please feel free to re-open to ping me and I'll open this.
