### ISSUE TITLE
Can't list all remote kernels

### ISSUE THREAD

**Issue by jacktang** [microsoft/vscode-jupyter#14092]
![img_v2_f7d50862-1d66-4489-8f82-52046b883e8g](https://github.com/microsoft/vscode-jupyter/assets/44341/eb314256-92f9-4ae9-bbab-c3e2ca5c17d2)

I can't list all kernels at remote host. I clicked install python extension, and it kept installing...

## Environment data

-   VS Code version: 1.81.0
-   Jupyter Extension version (available under the Extensions sidebar): v2023.6.1101941928
-   Python Extension version (available under the Extensions sidebar): v2023.14.0
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04.4 LTS
-   Python and/or Anaconda version: Python 3.10.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running:  Remote

**Comment by DonJayamanne** [comment]
Sorry you are running into this.

Please can you try installing both the Jupyter and python extensions. 
Next please can you share the logs from vscode console window (use the command 'Toggle Develiper Tools' to open the console window)

**Comment by jacktang** [comment]
Hello @DonJayamanne , I reinstalled python and Jupyter extensions and it fixed 👍
