### ISSUE TITLE
Changes to environment variables in `python.envFile` not getting picked up

### ISSUE THREAD

**Issue by kartikgupta-db** [microsoft/vscode-jupyter#14105]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The extension is supposed to load environment variables from `python.envFile` setting (https://github.com/microsoft/vscode-jupyter/issues/9691). 

But the variables seems to be cached somewhere. It takes multiple restarts of the kernel and restart of the entire notebook to pickup the latest changes. 

## Steps to reproduce
1. Create a notebook
2. Add some code like 
```python
import os
print(os.environ["TEST_ENV_VAR"])
```
3. Create a `.env` file (in the location pointed by `python.envFile` variable. 
4. Add the TEST_ENV_VAR to the file. Run the cell (which starts the kernel). The variable is loaded correctly. 
5. Change (or remove) TEST_ENV_VAR. 
6. Restart the kernel  and run the cell -> the variable is still found (this error happens very frequently, but NOT everytime). 
7. Restart the notebook -> if you are lucky the variable is not found, otherwise the variable is still found. 

## Video

https://github.com/microsoft/vscode-jupyter/assets/88345179/b06a96d7-d496-4f54-a3cf-6c3f9f2c09b7

### VS Code Version

1.79.2

### Jupyter Extension Version

v2023.5.1101742258

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
You are using an old version of the Jupyter extension
Please could you update to the latest version of Jupyter and python extension and try to replicate this issue

**Comment by kartikgupta-db** [comment]
@DonJayamanne  I am able to reproduce this with `v2023.7.1002162226` now. Exactly the same issue. Requires multiple notebook/kernel restarts for the env to be refreshed. I suspect some kind of caching here?

**Comment by fjakobs** [comment]
@binderjoe can you take a look? We need this for the Dtabricks VS Code extension.

**Comment by DonJayamanne** [comment]
@karrtikr if we enable verblose logging in Python extension will the logs show that Python extension has detected changes to the .env file? or do we need add logging for that?

**Comment by karrtikr** [comment]
Changes aren't logged right now as historically this has been working fine, but logging can be added here: https://github.com/microsoft/vscode-python/blob/d17ebcec3a4f202ceb4715040343e97adbd103fe/src/client/common/variables/environmentVariablesProvider.ts#L187

**Comment by kartikgupta-db** [comment]
FWIW, the env file changes are being picked immediately, when the code is run using "Run Python File" or "Debug Python File" options.

**Comment by kartikgupta-db** [comment]
@DonJayamanne any ideas on the reason for the bug?

**Comment by DonJayamanne** [comment]
Sorry no idea
The env variables are provided by python extension, looks like the python extension isn’t detecting the changes to the files 

are you updating the env file outside of vscode or from within vscode

**Comment by kartikgupta-db** [comment]
The update happens from within vscode.  We are working on the databricks  vscode extension. 

The flow is
1. Changes are made to a .env file
2. These changes are copied to another envfile (which is what is being tracked by python extension via the `python.envFile` setting). 
3. The kernel is restarted but we still do not see the new changes.

Is there a way to force kernel restarts? I see that you have a kernel API where there is an env field. Maybe we can directly interface with that? Right now, we can't access that API.

**Comment by kartikgupta-db** [comment]
@DonJayamanne bump.

**Comment by DonJayamanne** [comment]
@karrtikr is this still an issue with the latest version of the Jupyter extension and VS Code.
Sorry for not getting back on this issue, I believe we did address this in a sperate PR.
Let me know how things go.

**Comment by kartikgupta-db** [comment]
@DonJayamanne this issue seems to persist. I am using `v2023.9.1102792234`. I am able to exactly replicate the original issue.

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

Please share all of the logs

**Comment by kartikgupta-db** [comment]
I have an already active kernel. 
When I make changes to the .env file it detects that changes are made

```
16:37:01.517 [debug] Begin sendTelemetryForPythonKernelExecutable
16:37:01.517 [debug] Executing silently Code (idle) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys
16:37:01.524 [debug] Executing silently Code (completed) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys with 1 output(s)
16:37:01.524 [debug] End sendTelemetryForPythonKernelExecutable
16:37:01.524 [debug] Started running kernel initialization for ~/dabs-ui/a.ipynb
16:37:01.524 [debug] Executing silently Code (idle) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy
16:37:01.528 [debug] Executing silently Code (completed) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy with 0 output(s)
16:37:01.528 [debug] Determined IPyWidgets Version as undefined and event fired
16:37:01.529 [debug] Executing silently Code (idle) = import os as _VSCODE_os\nimport sys as _VSCODE_sys\n%cd "/~/dabs-ui"\nif _VSCODE_os.g
16:37:01.540 [debug] Executing silently Code (completed) = import os as _VSCODE_os\nimport sys as _VSCODE_sys\n%cd "/~/dabs-ui"\nif _VSCODE_os.g with 1 output(s)
16:37:01.540 [debug] Requesting Kernel info
16:37:01.540 [debug] Got Kernel info
16:37:01.540 [debug] End running kernel initialization, now waiting for idle
16:37:01.540 [debug] Waiting for 60000ms idle on (kernel): dd9507ba-3533-4a55-9aea-1d3a015846f7 -> idle
16:37:01.540 [debug] Finished waiting for idle on (kernel): dd9507ba-3533-4a55-9aea-1d3a015846f7 -> idle
16:37:01.540 [debug] End running kernel initialization, session is idle
16:37:01.540 [debug] Registering commtarget jupyter.widget
16:37:02.172 [info] Handle Execution of Cells 0 for ~/dabs-ui/a.ipynb
16:37:02.173 [debug] start the kernel, options.disableUI=false for ~/dabs-ui/a.ipynb
16:37:02.173 [debug] Execution Request Sent to Kernel for cell 0
16:37:02.177 [debug] Start cell 0 execution @ 1697553422176 (clear output)
16:37:02.177 [info] Kernel acknowledged execution of cell 0 @ 1697553422176
16:37:02.179 [info] End cell 0 execution @ 1697553422179, started @ 1697553422176, elapsed time = 0.003s
16:37:02.180 [debug] Cell 0 executed with state Success
16:37:24.845 [debug] Python env vars changed ~/dabs-ui
16:37:24.845 [debug] Detected changes to env file ~/dabs-ui in PythonApi
16:37:26.592 [debug] Python env vars changed ~/dabs-ui
16:37:26.592 [debug] Detected changes to env file ~/dabs-ui in PythonApi
```

When I then try to run the cell, it does not pickup the latest env because the kernel is already running (this is expected). 

When I restart the kernel and try running the cell, I still do not get the updated values. 
```
16:40:11.772 [info] Restart requested ~/dabs-ui/a.ipynb
16:40:11.772 [debug] Cancel pending cells
16:40:11.772 [info] Dispose Kernel process 80638.
16:40:11.775 [debug] Kernel Launcher. launch, Class name = ty (started execution), Arg 1: "~/dabs-ui/.venv/python.~/dabs-ui/.venv/python.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "~/dabs-ui/a.ipynb", Arg 4: "~/dabs-ui", Arg 5: ""
16:40:11.776 [debug] Getting activated env variables, Class name = za (started execution), Arg 1: "~/dabs-ui/a.ipynb", Arg 2: "~/dabs-ui/.venv/bin/python", Arg 3: undefined
16:40:11.776 [debug] Getting activated env variables, Class name = za, completed in 0ms, has a truthy return value, Arg 1: "~/dabs-ui/a.ipynb", Arg 2: "~/dabs-ui/.venv/bin/python", Arg 3: undefined
16:40:11.777 [info] Process Execution: ~/dabs-ui/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
16:40:11.782 [debug] Launching kernel in kernelProcess.ts, Class name = Zv (started execution), Arg 1: "~/dabs-ui", Arg 2: ""
16:40:11.783 [debug] Kernel Env Variables for ~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-darwin-arm64/temp/jupyter/kernels/pythonjvsc74a57bd042660d2d69fc44730a42da1b7384258858c7d4f111cbf520a6feba19d0bda03d/kernel.json, PATH value is <REDACTED>
16:40:11.785 [info] Process Execution: ~/dabs-ui/.venv/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9009 --control=9007 --hb=9006 --Session.signature_scheme="hmac-sha256" --Session.key=b"22f4f5e9-828a-4527-a3ea-6641a4129a8d" --shell=9008 --transport="tcp" --iopub=9011 --f=~/Library/Jupyter/runtime/kernel-v2-75453aw74RvBn356H.json
    > cwd: ~/dabs-ui
16:40:11.785 [debug] Launching kernel in kernelProcess.ts, Class name = Zv, completed in 3ms, has a truthy return value, Arg 1: "~/dabs-ui", Arg 2: ""
16:40:11.821 [debug] Disposed Kernel process 80638.
16:40:11.823 [debug] KernelProcess Exited, Exit Code - undefined
16:40:11.958 [info] ipykernel version & path 6.25.2, ~/dabs-ui/.venv/lib/python3.10/site-packages/ipykernel/__init__.py for ~/dabs-ui/.venv/bin/python
16:40:12.175 [debug] KernelProcess output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-v2-75453aw74RvBn356H.json

16:40:12.176 [debug] Kernel Output: To connect another client to this kernel, use: --existing kernel-v2-75453aw74RvBn356H.json

16:40:12.195 [debug] Kernel Launcher. launch, Class name = ty, completed in 420ms, has a truthy return value, Arg 1: "~/dabs-ui/.venv/python.~/dabs-ui/.venv/python.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "~/dabs-ui/a.ipynb", Arg 4: "~/dabs-ui", Arg 5: ""
16:40:12.199 [debug] Waiting for Raw Session to be ready in postStartRawSession
16:40:12.199 [debug] Waiting for Raw session to be ready, currently connected
16:40:12.199 [debug] Raw session connected
16:40:12.199 [debug] Waiting for Raw session to be ready for 30s
16:40:12.199 [debug] Waited for Raw session to be ready & got connected
16:40:12.199 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
16:40:12.199 [debug] Kernel status before requesting kernel info and after ready is unknown
16:40:12.199 [debug] Sending request for kernelInfo
16:40:12.201 [debug] KernelProcess error: [IPKernelApp] WARNING | Unknown error in handling startup files:

16:40:12.201 [warn] StdErr from Kernel Process [IPKernelApp] WARNING | Unknown error in handling startup files:
16:40:12.411 [debug] Got response for requestKernelInfo
16:40:12.411 [debug] Successfully completed postStartRawSession
16:40:12.412 [info] Restarted dd9507ba-3533-4a55-9aea-1d3a015846f7
```

On restarting the file, it does a restart with similar logs. 

After waiting for ~1minute. And then restarting the kernel I get the following logs and the new value is loaded. 
```
16:45:03.341 [debug] Getting activated env variables, Class name = za (started execution), Arg 1: "~/dabs-ui/a.ipynb", Arg 2: "~/dabs-ui/.venv/bin/python", Arg 3: undefined
16:45:03.341 [debug] Get Custom Env Variables, Class name = Kl (started execution), Arg 1: "~/dabs-ui/a.ipynb", Arg 2: "RunPythonCode"
16:45:03.342 [debug] Get Custom Env Variables, Class name = Kl, completed in 1ms, has a truthy return value, Arg 1: "~/dabs-ui/a.ipynb", Arg 2: "RunPythonCode"
16:45:03.346 [debug] Launching kernel in kernelProcess.ts, Class name = Zv (started execution), Arg 1: "~/dabs-ui", Arg 2: ""
16:45:03.385 [debug] Disposed Kernel process 83995.
16:45:03.387 [debug] KernelProcess Exited, Exit Code - undefined
16:45:03.589 [debug] Got env vars with python ~/dabs-ui/.venv/bin/python, with env var count 51 in 248ms. 
    PATH value is <REDACTED> and 
    Path value is undefined
16:45:03.589 [debug] Prepend PATH with python bin for ~/dabs-ui/.venv/bin/python, 
    PATH value is <REDACTED>  and 
    Path value is undefined
16:45:03.589 [debug] Activated Env Variables for ~/dabs-ui/.venv/bin/python, 
    PATH value is <REDACTED>  and 
    Path value is undefined
```

**Comment by DonJayamanne** [comment]
Thank you very much for the logs, I believe I may have found the cause,
Please can you 
* Download this file
* Extract it
* Go into vscode and select the command `Extensions: Install from VSIX`
* Reload vscode when prompted to do so
* Try to replicate the issue (it shoudl work)
* If not, plese provide the logs again
[ms-toolsai-jupyter-insiders.vsix (3).zip](https://github.com/microsoft/vscode-jupyter/files/12956491/ms-toolsai-jupyter-insiders.vsix.3.zip)
