### ISSUE TITLE
Ask for Conda/Pip ipykernel install in notification rather than quickpick (if possible)

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#1410]
If a new conda environment is desired to run the interactive window and it doesn't have ipykernel installed, we first notify the user at the bottom right with "Do you want to install ipykernel?"

If the user clicks yes, they are then prompted with a quick pick at the top of VS Code whether it should be conda or pip to install.

This second level question is unnecessary and likely the source of discouragement for users. Instead, the notification should offer "Ipykernel is required to be installed to use the interactive window. Use Conda? Use Pip?". We don't need a cancel button. The user can click the x.

**Comment by greazer** [comment]
This seemed to have gotten lost. Putting back into New Issues

**Comment by greazer** [comment]
In the name of reducing prompting

**Comment by rchiodo** [comment]
This works totally different now. Closing
