### ISSUE TITLE
Data Viewer throws error "Python package 'pandas' is required for viewing data." even though pandas is installed

### ISSUE THREAD

**Issue by simonfisher** [microsoft/vscode-jupyter#1411]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Create New Blank Jupyter Notebook
2. Create basic array
3. Run Cell
4. In the Variables area, try open the array in the Data Viewer

Note: pandas is installed in the selected python environment (shown in screenshot below). See this Terminal output:

`simonfisher@Simons-MBP-2 ~ % pip --version pandas`
`pip 20.2.1 from /Users/simonfisher/.pyenv/versions/3.7.8/lib/python3.7/site-packages/pip (python 3.7)`

Note: I am using insider build of Code, and daily build of the python extension, to try and resolve this issue as I was having the same problem with the stable builds of both.

## Actual behavior

![image](https://user-images.githubusercontent.com/50608438/89597353-3f331980-d89d-11ea-889c-a545d8428220.png)

If I then click "Install" (just for the hell of it), it goes to the following screen with a new error pictured (ignore the different/new file shown, I did this step with a new test file):

![image](https://user-images.githubusercontent.com/50608438/89599314-8e2f7d80-d8a2-11ea-88e7-3c9379b1cf43.png)

## Expected behavior

The Data Viewer window showing the array...

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.8.99098-dev
-   **VS Code version:** 1.48.0-insider
-   **Setting python.jediEnabled:** true
-   **Setting python.languageServer:** Jedi
-   **Python and/or Anaconda version:** 3.7.8 64-bit (pyenv)
-   **OS:** Mac
-   **Virtual environment:** N/A

## Developer Tools Console Output

Python package 'pandas' is required for viewing data.
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
notify @ notificationService.ts:106
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:409
_invokeHandler @ rpcProtocol.ts:394
_receiveRequest @ rpcProtocol.ts:310
_receiveOneMessage @ rpcProtocol.ts:237
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:463
_receiveMessage @ ipc.net.ts:747
(anonymous) @ ipc.net.ts:602
fire @ event.ts:587
acceptChunk @ ipc.net.ts:240
(anonymous) @ ipc.net.ts:201
t @ ipc.net.ts:29
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166

Error: Python package 'pandas' is required for viewing data.
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
notify @ notificationService.ts:106
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:409
_invokeHandler @ rpcProtocol.ts:394
_receiveRequest @ rpcProtocol.ts:310
_receiveOneMessage @ rpcProtocol.ts:237
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:463
_receiveMessage @ ipc.net.ts:747
(anonymous) @ ipc.net.ts:602
fire @ event.ts:587
acceptChunk @ ipc.net.ts:240
(anonymous) @ ipc.net.ts:201
t @ ipc.net.ts:29
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by joyceerhl** [comment]
Hi @simonfisher very sorry for the delayed response on this issue. By any chance are you still seeing this issue?
