### ISSUE TITLE
No kernel while folder opened

### ISSUE THREAD

**Issue by Dominicus1165** [microsoft/vscode-jupyter#14129]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

## How to produce error

Start VSCode => Open or create any `*.pynb` => Select kernel => python environment =>kernel selection will work

Start VSCode => Open folder => Open or create any `*.ipynb` => Select kernel => python environment => no kernel detected

I can only click "install python"

`python --version`  does work\
`juypter kernelspec list` does work

This results in no available kernel => can't run code\
It also does not accept the path to python (pressing enter has no effect)

## Tried Repairs

- reinstall vscode and python
- update all versions to newest including python 3.11.4

### VS Code Version

1.81.1

### Jupyter Extension Version

v2023.7.1002162226

### Coding Language and Runtime Version

Python 3.11.4

### Language Extension Version (if applicable)

Python v2022.17.12861055

### Running Jupyter locally or remotely?

Local

**Comment by Dominicus1165** [comment]
Installed packages in VSCode are
- Jupyter
- Jupyter Notebook Renderers
- Jupyter Keymap
- Jupyter Slide Show
- Pylance
- Python
- IntelliCode

Installed python packages are (including dependencies)
- jupyter
- jupyterlab
- pip
- pandas
- numpy
- matplotlib
- requests

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and sorry you are running into this.

* Please could you let me know what folder you are opening? Are you opening the Python environment folder itself.
* Please could you enable logging as follows and then share the logs:
    * Open settings & go into `Jupyter->Logging`
    * Change the value to `verbose`
    * Reload VS Code,
    * Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
