### ISSUE TITLE
Minimal package requirements to run a jupyter notebook

### ISSUE THREAD

**Issue by skwde** [microsoft/vscode-jupyter#14130]
Lately I have been running into some issues with environments and jupyter notebooks where I am asked to install `ipykernel` into the environment even though it is already installed.

It is not clear to me what the minimum requirements actually are from the current sources of information:

- https://code.visualstudio.com/docs/datascience/jupyter-notebooks#_setting-up-your-environment mentions `jupyter`
- https://github.com/microsoft/vscode-jupyter/wiki/Jupyter-Kernels-and-the-Jupyter-Extension#python-environments mentions `ipython` and `ipykernel`
- https://github.com/microsoft/vscode-jupyter/wiki/Installing-Jupyter mentions `jupyter` *may* be required.

Note,
- `jupyter` requires `ipython` and `ipykernel`.
- `ipykernel` requires `ipython`.

So which one is it? What are the minimum requirements with versions?

**Comment by DonJayamanne** [comment]
You need to install the latest version of IPyKernel and all of the related dependencies.
Use `pip install ipykernel` or the like, as to what the related dependencies are depends on the `ipykernel` package itself.

> So which one is it? What are the minimum requirements with versions?

Closing this issue as this has been answered.
If there are other questions, please feel free to file a new issue or ask ehere.

**Comment by skwde** [comment]
@DonJayamanne thanks for the reply.

By latest available version I assume you mean latest version in the environment.

Can you  please also clarify the meaning of "`jupyter` *may* be required" as mentioned <https://github.com/microsoft/vscode-jupyter/wiki/Installing-Jupyter>. In which cases might `jupyter` be needed?

**Comment by DonJayamanne** [comment]
> ning of "jupyter may be required" as mentioned

This is when some of the native modules for zmq do not work on your platform. 
Its a little technical, but if you get promtped to install jupyter, thats the easiest way to tell that the native modules do not work on your platform.
