### ISSUE TITLE
IPyWidgets doesn't work with the default version of jupyter ipywidgets shipped with Ubuntu 18

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1414]
See this comment here:
https://github.com/microsoft/vscode-python/issues/3429#issuecomment-629558081

Looks like our internal implementation requires a newer version of ipywidgets on the machine.

**Comment by DonJayamanne** [comment]
# Solution

Display a warning about unsupported version of ipywidgets and recommend updating this.
Do this when ipywidgets is used.

**Comment by DonJayamanne** [comment]
Closing this for now, as we haven't had any users report any issues since
