### ISSUE TITLE
Exporting Jupyter to PDF -Plotly does not display

### ISSUE THREAD

**Issue by Seanthelast** [microsoft/vscode-jupyter#14153]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

In trying to export my notebook to a pdf, I cannot seem to get it to display the output of the graphs I made with plotly. I have found another solution on this website that applies to HTML and ideally should thus apply to PDF exports (here: https://github.com/microsoft/vscode-jupyter/issues/6999), but the suggested line of code that manipulates the plotly renderers does not seem to work; I get an error essentailly that says "DataFrame constructor not properly called!". I thus have no idea how else to manipulate the renederes and get the PDF to show the Plotly objects I have created 

### VS Code Version

Version: 1.81.1 (user setup) Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794 Date: 2023-08-09T22:22:42.175Z Electron: 22.3.18 ElectronBuildId: 22689846 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Windows_NT x64 10.0.19045

### Jupyter Extension Version

N/A

### Jupyter logs

```shell
Nothing to report here
```

### Coding Language and Runtime Version

Python 3.10.11

### Running Jupyter locally or remotely?

Local

**Comment by Seanthelast** [comment]
Is there any additional information I should add? I apologize if I have not added enough

**Comment by DonJayamanne** [comment]
I'm sorry for not getting back to you on this, please could you share a simple ipynb file with the output that you have tried to export to PDF.

> the suggested line of code that manipulates the plotly renderers does not seem to work; I get an error essentailly that says "DataFrame constructor not properly called!". I thus have no idea how else to manipulate the renederes and get the PDF to show the Plotly objects I have created

Where is this error message displayed? Is this dislayed by nbformat/nbconvert
Please could you share a screen sample or logs where this message is displayed along with the details of the message

**Comment by Seanthelast** [comment]
I'm not sure if I can share a simplified version of this file and this is the only file on hand that I have created using plotly, but I can show you some screenshots of the output and send you the pdf itself to show you what I am talking about.
The output in the file should consist of several plotly objects. For example, the first such output should be a graph such as this:
![image](https://github.com/microsoft/vscode-jupyter/assets/89895021/c9f357c4-eec0-40e9-b2d1-87130877f865)
When rednering to pdf, I appear to get no errors in rendering, but the pdf displays these outputs as compelltly blank:
[8.14.23.pdf](https://github.com/microsoft/vscode-jupyter/files/12578981/8.14.23.pdf)

The line of code I was referring to that  Itry to add that gave me an error was the following:
import plotly.express as px
import plotly.io as pio

pio.renderers.default = "notebook"

fig = px.line(...)
fig.show()

These lines of code however produce this error:
ValueError                                Traceback (most recent call last)
Cell In[5], line 8
      1 # # This ensures Plotly output works in multiple places:
      2 # # plotly_mimetype: VS Code notebook UI
      3 # # notebook: "Jupyter: Export to HTML" command in VS Code
      4 # # See https://plotly.com/python/renderers/#multiple-renderers
      6 pio.renderers.default = "notebook"
----> 8 fig = px.line(...)
      9 fig.show()
File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\plotly\express\_chart_types.py:264](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/seant/Documents/Snell%20Research/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/plotly/express/_chart_types.py:264), in line(data_frame, x, y, line_group, color, line_dash, symbol, hover_name, hover_data, custom_data, text, facet_row, facet_col, facet_col_wrap, facet_row_spacing, facet_col_spacing, error_x, error_x_minus, error_y, error_y_minus, animation_frame, animation_group, category_orders, labels, orientation, color_discrete_sequence, color_discrete_map, line_dash_sequence, line_dash_map, symbol_sequence, symbol_map, markers, log_x, log_y, range_x, range_y, line_shape, render_mode, title, template, width, height)
    216 def line(
    217     data_frame=None,
    218     x=None,
   (...)
    258     height=None,
    259 ) -> go.Figure:
    260     """
    261     In a 2D line plot, each row of `data_frame` is represented as vertex of
    262     a polyline mark in 2D space.
    263     """
--> 264     return make_figure(args=locals(), constructor=go.Scatter)

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\plotly\express\_core.py:2003](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/seant/Documents/Snell%20Research/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/plotly/express/_core.py:2003), in make_figure(args, constructor, trace_patch, layout_patch)
   2000 layout_patch = layout_patch or {}
   2001 apply_default_cascade(args)
-> 2003 args = build_dataframe(args, constructor)
   2004 if constructor in [go.Treemap, go.Sunburst, go.Icicle] and args["path"] is not None:
   2005     args = process_dataframe_hierarchy(args)

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\plotly\express\_core.py:1313](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/seant/Documents/Snell%20Research/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/plotly/express/_core.py:1313), in build_dataframe(args, constructor)
   1311         args["data_frame"] = args["data_frame"].to_pandas()
   1312     else:
-> 1313         args["data_frame"] = pd.DataFrame(args["data_frame"])
   1314 df_input = args["data_frame"]
1316 # now we handle special cases like wide-mode or x-xor-y specification
   1317 # by rearranging args to tee things up for process_args_into_dataframe to work

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\core\frame.py:781](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/seant/Documents/Snell%20Research/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/pandas/core/frame.py:781), in DataFrame.__init__(self, data, index, columns, dtype, copy)
    778 # For data is scalar
    779 else:
    780     if index is None or columns is None:
--> 781         raise ValueError("DataFrame constructor not properly called!")
    783     index = ensure_index(index)
    784     columns = ensure_index(columns)

ValueError: DataFrame constructor not properly called!

Not really sure where else to go with these lines of code, as I am pretty sure that it is something with the plotly objects themselves that is preventing them from showing on the pdf.

**Comment by Seanthelast** [comment]
Is this better?
13:10:03.414 [info] End cell 6 execution @ 1694718603413, started @ 1694718593254, elapsed time = 10.159s
13:10:03.414 [warn] Cancel all remaining cells due to cancellation or failure in execution
13:10:03.414 [debug] Cancel pending cells
13:10:03.414 [debug] Cell 6 executed with state Error
13:10:07.453 [info] Loading webview. View is notset
13:10:07.454 [info] Loading web view...
13:10:07.454 [info] Webview panel created.
13:10:08.821 [info] Web view react rendered
13:10:08.883 [debug] Executing silently Code (idle) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info
13:10:08.883 [debug] Executing silently Code (idle) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info
13:10:08.904 [debug] Executing silently Code (completed) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info with 1 output(s)
13:10:08.980 [debug] Executing silently Code (completed) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info with 1 output(s)

**Comment by DonJayamanne** [comment]
@sadasant 
Please can you replicate the issue and then share the logs
Based on the logs, I do not see any export takingplace.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
