### ISSUE TITLE
Keyboard navigation of plot viewer does not change focused element

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1415]
1. Open multiple plots
1. Tab into the list at the top
1. Use the arrow keys to move around. 

Expected:
Focused element changes

Actual:
Only selected element changes

![image.png](https://images.zenhubusercontent.com/5bda265b648e32720db70349/0c0ac3a2-1f9b-4657-9059-233ee0e4ec75)

**Comment by DonJayamanne** [comment]
Given this issue hasn't been upvoted nor reported by anyone else I'm closing this
