### ISSUE TITLE
The kernel picker did not update the loading icon after the check was complete

### ISSUE THREAD

**Issue by realDuang** [microsoft/vscode-jupyter#14158]
## Environment data

-   VS Code version:  1.82.0 - Insider
-   Jupyter Extension version (available under the Extensions sidebar): v2023.8.1002321100
-   Python Extension version (available under the Extensions sidebar): v2023.15.12302115
-   OS (Windows | Mac | Linux distro) and version: Chrome web
-   Python and/or Anaconda version: 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): 
-   Jupyter server running: Remote

## Expected behaviour

![image](https://github.com/microsoft/vscode-jupyter/assets/17807197/0c2aa6d3-9867-4358-be02-0bf305032d8a)

## Actual behaviour

![image](https://github.com/microsoft/vscode-jupyter/assets/17807197/80d4d2d4-4b3e-4814-a2c7-2bc5168adab8)

## Steps to reproduce:

I am trying to use jupyter vscode extension under insiders.vscode.dev.

When I open any notebook, it occasionally appears that the kernel selector shows a loading icon, but the actual detect function is completed.

Then I check the jupyter log and find that the kernel picker detection runs properly.

I haven't found the exact path of recurrence yet, but the problem is there. It seems that the detection is actually completed before the UI update time is caused.

![image](https://github.com/microsoft/vscode-jupyter/assets/17807197/673471fb-7dbe-48bb-8374-42e0b828d262)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Visual Studio Code - Insiders (1.82.0-insider, undefined, vscode.dev)
Jupyter Extension Version: 2023.8.1002321100.
Python Extension Version: 2023.15.12302115.
No workspace folder opened.
14:48:37.299 [info] User belongs to experiment group 'NewJupyterSession'
14:48:46.411 [error] Unable to determine the caller of the extension API for trace stack. Error: 
    at u.determineExtensionFromCallStack (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2023.8.1002321100/extension/out/extension.web.bundle.js#vscode-extension:11:310457)
    at g (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2023.8.1002321100/extension/out/extension.web.bundle.js#vscode-extension:26:113218)
    at Object.registerRemoteServerProvider (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2023.8.1002321100/extension/out/extension.web.bundle.js#vscode-extension:26:113817)
    at _i.eval (https://github.vscode-unpkg.net/GitHub/codespaces/1.14.15/node_modules/js-sha256/src/sha256.js:1:1)
    at Generator.next (<anonymous>)
    at fulfilled (https://github.vscode-unpkg.net/GitHub/codespaces/1.14.15/node_modules/js-sha256/src/sha256.js:1:1)
14:48:46.414 [error] Unable to determine the caller of the extension API for trace stack. Error: 
    at u.determineExtensionFromCallStack (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2023.8.1002321100/extension/out/extension.web.bundle.js#vscode-extension:11:310457)
    at eval (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2023.8.1002321100/extension/out/extension.web.bundle.js#vscode-extension:26:114020)
    at Object.registerRemoteServerProvider (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2023.8.1002321100/extension/out/extension.web.bundle.js#vscode-extension:26:114112)
    at _i.eval (https://github.vscode-unpkg.net/GitHub/codespaces/1.14.15/node_modules/js-sha256/src/sha256.js:1:1)
    at Generator.next (<anonymous>)
    at fulfilled (https://github.vscode-unpkg.net/GitHub/codespaces/1.14.15/node_modules/js-sha256/src/sha256.js:1:1)
14:48:51.963 [info] Start refreshing Kernel Picker (1692600531963)
14:48:52.860 [info] End refreshing Kernel Picker (1692600531963)
14:48:58.000 [info] Handle Execution of Cells 0 for /A8F6376E-193C-4729-B2E9-570B631961F5/b771c1ab-1696-4f34-aac1-fe4c1b81d925/bef3408a-8d26-413b-9c5d-956cbae04d1e/vscode-test.ipynb
14:48:58.002 [info] Starting Kernel startUsingRemoteKernelSpec, 725001538c52f828aa9114ee3c092d578790498546af01798de7d09dfaf960f6..synapse_pyspark./python3./.-m#synapsekernel.synapse_pyspark  for '/A8F6376E-193C-4729-B2E9-570B631961F5/b771c1ab-1696-4f34-aac1-fe4c1b81d925/bef3408a-8d26-413b-9c5d-956cbae04d1e/vscode-test.ipynb' (disableUI=false)
14:48:59.075 [info] https://a8f6376e193c4729b2e9570b631961f5.pbidedicated.windows.net/webapi/capacities/A8F6376E-193C-4729-B2E9-570B631961F5/workloads/Notebook/Data/Direct/api/workspaces/b771c1ab-1696-4f34-aac1-fe4c1b81d925/artifacts/bef3408a-8d26-413b-9c5d-956cbae04d1e/jupyterApi/versions/1: Kernel started: 5b11c4fe-1d74-43cc-8ae7-43c98934cca8
14:49:00.291 [info] Started session for kernel startUsingRemoteKernelSpec:725001538c52f828aa9114ee3c092d578790498546af01798de7d09dfaf960f6..synapse_pyspark./python3./.-m#synapsekernel.synapse_pyspark
14:49:13.400 [info] Start refreshing Kernel Picker (1692600553400)
14:49:13.933 [info] Kernel acknowledged execution of cell 0 @ 1692600552741
14:49:14.204 [info] End refreshing Kernel Picker (1692600531963)
14:49:14.205 [info] End refreshing Kernel Picker (1692600553400)
14:49:14.986 [info] End cell 0 execution @ 1692600553518, started @ 1692600552741, elapsed time = 0.777s
```

</p>
</details>

**Comment by amunger** [comment]
> but the actual detect function is completed.
What are you basing this off of? the "End refreshing Kernel picker" log?

How long does the loading icon show after the refresh completes? a few seconds?

**Comment by realDuang** [comment]
> > but the actual detect function is completed.
> > What are you basing this off of? the "End refreshing Kernel picker" log?
> 
> How long does the loading icon show after the refresh completes? a few seconds?

No, it's stuck at the loading state for a long time and never change it unless I restart vscode

**Comment by DonJayamanne** [comment]
Based on the logs Jupyter extension is done with the kernel refresh

**Comment by realDuang** [comment]
@rebornix This issue is still bothering us. if you have a moment please check back to see if there is any further progress, or information you would like me to provide.

**Comment by rebornix** [comment]
Let's merge it into https://github.com/microsoft/vscode/issues/186364, will tackle this soon.
