### ISSUE TITLE
conda Environment

### ISSUE THREAD

**Issue by lsao2000** [microsoft/vscode-jupyter#14166]
Type: <b>Feature Request</b>

i have a problem with activation of the conda environment in jupyter notebook 

VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by DonJayamanne** [comment]
@lsao2000 
Please can you provide more information (eg steps) that would help is replicate your issue


Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
