### ISSUE TITLE
Run Selection/Line in Interactive Window as Debug

### ISSUE THREAD

**Issue by etrippler** [microsoft/vscode-jupyter#14165]
## Goal

I'm trying to accomplish the following workflow:

* Working in a regular `.py` file (call it `main.py`) and sending Selections/Lines to the Interactive Window.
* Setting a breakpoint in `main.py` or in module code that it is calling.
* Sending a selection/line to the interactive window, but running it as a `Debug Cell`.
   * At this point, expected behavior would be the same as normal debugging. Halt at breakpoints, drop into debug console (not interactive window), etc. 

## Current State

This is *almost* possible in a few different ways. 

1. Closest: You can use the `# %%` cell syntax to get the "Debug Cell" option (Note: this still has a bug currently where it hits a breakpoint on `sys.excepthook = old_excepthook`, mentioned in: https://github.com/microsoft/vscode-jupyter/issues/9815. It would be great if this issue could be opened again and this bug looked at. I am running into an identical problem and for me turning on "Just My Code" is not practical)
<img width="341" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/123005132/247d3c28-5fbd-4f6e-b19f-5863fc161161">

2. You can open up a proper Jupyter notebook:
<img width="356" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/123005132/4716905b-8994-4a0d-aafe-ee9084ced071">

3. You can run the entire file 
<img width="367" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/123005132/795fdee9-53a6-4fce-b553-5ddb18dfb82f">

**However, there is no way to to "Run Selection/Line in Interactive Window as Debug". In theory this seems completely possible, if option 1 were to have it's bug fixed, and a command was added to do the same thing as "Debug Cell" without having to add the special `#%%` characters.**

Edit: I also just realized there are commands. "Jupyter: Debug Current Cell in Interactive Notebook" and "Jupyter: Debug Current File in Interactive Notebook". I'm just looking for "Jupyter: Debug Current Selection/Line in Interactive Notebook

## Environment data

-   VS Code version: 1.81.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.7.1002162226
-   Python Extension version (available under the Extensions sidebar): v2023.14.0
-   OS (Windows | Mac | Linux distro) and version: MacOS 13.5.1
-   Python and/or Anaconda version: 3.11
-   Type of virtual environment used: Conda
-   Jupyter server running: Local

**Comment by DonJayamanne** [comment]
Thank you for the feature suggestion, however given taht there haven't been any upvotes on this issue since this was created, I'm closing this for now.
