### ISSUE TITLE
Syntax highlighting stops working

### ISSUE THREAD

**Issue by umarbutler** [microsoft/vscode-jupyter#14174]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Syntax highlighting will very regularly 'break' requiring me to re-open my notebook for it to start working again. Sometimes, I will need to restart vscode to get highlighting back.

### VS Code Version

Version: 1.81.1 (user setup)

### Jupyter Extension Version

v2023.7.1002162226

### Coding Language and Runtime Version

Python 3.11.4

### Language Extension Version (if applicable)

v2023.14.0

### Running Jupyter locally or remotely?

Local

**Comment by aiden4977** [comment]
Me too. This could happened after deleting a notebook cell, by clicking "delete" on tools bar in the right-upper corner of a cell. Syntax highlighting was disabled. Code auto filling was disabled. Besides, I cannot jump into function definition with CTRL+left click.

![image](https://github.com/microsoft/vscode-jupyter/assets/72481939/398054b9-357a-49f8-9594-3950eedea18b)

**Comment by guyguyguy1234** [comment]
Same issue. Autocomplete disabled etc. The jupyter is essentially reduced to windows notepad. Needless to say this is an extreme issue that should be addressed asap.

**Comment by jonathanbisp** [comment]
The same here

**Comment by rebornix** [comment]
Can you please update to latest Pylance extension and see if you can reproduce?

**Comment by rd-andreas-lay** [comment]
Happens to me all the time as well.

**Comment by rebornix** [comment]
This issue should be fixed now with latest Pylance extension.
