### ISSUE TITLE
Programmatical notebook control within vscode-jupyter

### ISSUE THREAD

**Issue by ultmaster** [microsoft/vscode-jupyter#14178]
I'm building a tool (basically a coding helper) that generates code and helps debugging and etc. I've had a successful (yet hacky) implementation in nbclassic. I'm looking for ways to make it possible in jupyterlab and vscode.

I've been hunting for the following abilities:

1. Insert a cell with specific content below the currently selected cell and fill-in some content. This can be implemented in nbclassic with `display(Javascript("IPython.notebook.insert_cell_blow(...); ..."))`. But in vscode, Javascript is not displayed (https://stackoverflow.com/q/70768787), and `IPython` / `Jupyter` is not defined even with `%%js` (#4539).
2. Insert a cell below (like 1.) and run the inserted cell. In nbclassic, this can be done with `CodeCell.execute`, which is not possible here due to similar reasons as 1.
3. Get a JSON representation of last cell. This is helpful for a debuging feature that automatically fixes the last cell. This can be implemented in nbclassic by `IPython.notebook.get_cell` (the variables can be transpassed with the approach described in https://stackoverflow.com/q/58881349). Considering that this is even more advanced, I haven't tried yet.

Things I've tried:

1. Looking for possible variables I can use in `window.` of `%%js`. Currently some variables caught my attention `window.ipywidgetsKernel`, `vscIPYWidgets`, `_mgr`. However, after going through the documentation of ipywidgets, I didn't find it particularly useful to me.
2. Looking for other examples. I've noticed https://github.com/Microsoft/vscode-notebook-renderers which does a similar thing to manipulate the notebooks. However, it seems like a plug-in / middleware type of thing at the layer of vscode rendering and dealing with visual components (like DOM element). (although I think a jQuery solution might be acceptable as a last resort)
3. Going through the code of vscode-jupyter. I've noticed a NotebookEdit in vscode. Interacting with it might give me the ability to editing the notebook (after implementing a new vscode extension maybe). However, I'm not sure whether it possesses the ability to integrate with vscode-jupyter and send command to run some cell.

I'm acceptable to all hacky solutions as long as their effort is affordable to me. Any suggestions on what directions I should investigate into?

**Comment by rebornix** [comment]
@ultmaster in VS Code, outputs are rendered in separate webview, which has no access the notebook model. That's why in both notebook renderers and jupyter extension, it talks to the extension host and let its extension counter part to do the notebook edits (and also we can request cell execution from there). You might want to follow the same route.
