### ISSUE TITLE
unable to download required widget in VSCode

### ISSUE THREAD

**Issue by gincru** [microsoft/vscode-jupyter#14176]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filling this issue
However without any information it’s not possible to help you
Please could you fill in the required info and include steps to repro the issue

**Comment by gincru** [comment]
thanks for replying! the problem was eventually fixed - it had to do with
an antivirus software on my computer. it was my first time reporting an
issue and didn't realize that I needed to write more information. will do
next time!

-Gin
