### ISSUE TITLE
open two .ipynb files in two editor groups

### ISSUE THREAD

**Issue by lunbudao** [microsoft/vscode-jupyter#1418]
Issue Type: <b>Bug</b>

Sometimes when I open two .ipynb files (file1 and file2) in two editor groups, that is, file1 in group1, file2 in group2, the two files just flashing alternately, I think maybe they are fast switching, and I can't edit them. Also, I can't change to other files, such as .py files in both editor groups, it just switch back to .ipynb files quickly.

Extension version: 2020.9.114305
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.91GB (9.65GB free)|
|Process Argv|--crash-reporter-id 3ae9254d-1956-4b69-96df-e3e84714db34|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by greazer** [comment]
@lunbudao, please reopen if this is an issue that still occurs using VS Code Insiders build and the notebook support there,.
