### ISSUE TITLE
Not able to connect to a remote Jupyter kernal

### ISSUE THREAD

**Issue by TeZLa369** [microsoft/vscode-jupyter#14191]
Type: <b>Bug</b>

After starting the py kernel in the folder I am working on using the terminal, I pasted the URL in the VS Code to use that kernal, but it shows connection error.
But if I paste the same link the browser it works

Extension version: 2023.7.1002162226
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.23526
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.34GB (0.86GB free)|
|Process Argv|C:\\Users\\kunta\\Documents\\Languages_and_Developments\\Python\\Fellowship\\SIRTUIN6\\SIRTUIN6_NEW.ipynb --crash-reporter-id 2f401b75-80db-4ea0-99c4-15616fc605d5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by DonJayamanne** [comment]
Thanks for filling this issue
Please can you share the logs and details of the error message

Also please could you share the cli used to start Jupyter in the terminal

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Just out of curiosity, why do you start Jupyter locally and connect to it as though it was a remote server, that option was built primarily for connecting to remote servers,


locally You could instead just select the python env or the Jupyter kernel from the kernel picker, and that would be much simpler,
I’m only adding to understand what’s missing do that it can be improved

**Comment by TeZLa369** [comment]
Jupyter log:
11:56:51.162 [debug] Updating cache with Remote kernels
connectToLiveRemoteKernel:'43273fb6-448c-4770-9215-61d580ee4a03
(interpreter id = )', Added =
connectToLiveRemoteKernel:'43273fb6-448c-4770-9215-61d580ee4a03
(interpreter id = )', Updated = , Removed =
11:57:11.087 [warn] Password for http://localhost:8888/tree/ was invalid.
11:57:11.103 [debug] Disposing session manager
11:57:11.103 [debug] SessionManager - dispose contents manager
11:57:11.103 [debug] ShutdownSessionAndConnection - dispose session manager
11:57:11.104 [warn] Uri verification error [t [Error]: Invalid response: 404
Not Found
    at t.create
(c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.7.1002162226-win32-x64\out\extension.node.js:2:68150)
    at process.processTicksAndRejections
(node:internal/process/task_queues:96:5)
    at async t.listRunning
(c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.7.1002162226-win32-x64\out\extension.node.js:2:55954)
    at async gm.getRunningKernels
(c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.7.1002162226-win32-x64\out\extension.node.js:17:169061)
    at async Promise.all (index 0)
    at async ko.validateRemoteUriNew
(c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.7.1002162226-win32-x64\out\extension.node.js:2:1707330)
    at async r.value
(c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.7.1002162226-win32-x64\out\extension.node.js:24:570971)]
{
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error:
null },
    [Symbol(Response internals)]: {
      url: 'http://localhost:8888/tree/api/kernels?1693204031089',
      status: 404,
      statusText: 'Not Found',
      headers: [T [Headers]],
      counter: 0
    }
  },
  traceback: ''
}
11:57:11.115 [debug] Finished disposing jupyter session manager

**Comment by TeZLa369** [comment]
If I use the kernels that are available in the VS code then some of the
packages don't work and sometimes it shows to install ipykernel although
it's already installed.
So I just start the jupyter in the terminal using the "jupyter notebook"
command. After that I copy and paste the URL from the terminal to the VS
Code.
Earlier it used to work but after installing the latest version of the
jupyter, it has stopped working.
[image: image.png]

**Comment by zensayyy** [comment]
Hi, 

I have the same error. Logs below. Note it says invalid password warning. However, same token used as in browser. Jupyter Server version 2.7.2.

```
17:02:31.485 [warn] Password for [redacted]/tree was invalid.
17:02:31.557 [debug] Disposing session manager
17:02:31.557 [debug] SessionManager - dispose contents manager
17:02:31.557 [debug] ShutdownSessionAndConnection - dispose session manager
17:02:31.557 [warn] Uri verification error t [Error]: Invalid response: 404 Not Found
    at Function.create (~/.vscode/extensions/ms-toolsai.jupyter-2023.7.1002162226-darwin-arm64/out/extension.node.js:2:68150)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.t.listRunning (~/.vscode/extensions/ms-toolsai.jupyter-2023.7.1002162226-darwin-arm64/out/extension.node.js:2:55954)
    at gm.getRunningKernels (~/.vscode/extensions/ms-toolsai.jupyter-2023.7.1002162226-darwin-arm64/out/extension.node.js:17:169061)
    at async Promise.all (index 0)
    at ko.validateRemoteUriNew (~/.vscode/extensions/ms-toolsai.jupyter-2023.7.1002162226-darwin-arm64/out/extension.node.js:2:1707330)
    at r.value (~/.vscode/extensions/ms-toolsai.jupyter-2023.7.1002162226-darwin-arm64/out/extension.node.js:24:570971) {
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: '[redacted]/tree/api/kernels?1693234951490',
      status: 404,
      statusText: 'Not Found',
      headers: [T [Headers]],
      counter: 0
    }
  },
  traceback: ''
}
17:02:31.576 [debug] Finished disposing jupyter session manager
```

**Comment by briancleland** [comment]
@zensayyy Thanks for the fix. I have been having the same problem for the last few days. @DonJayamanne any word on progressing this?

**Comment by DonJayamanne** [comment]
This has been verified as fixed In the latest version of the Jupyter extension which will be released sometime this week,

**Comment by DonJayamanne** [comment]
The latest version has been released.
Please update VS Code and Jupyter extnsion.
Closing tihs issue.
If this still exists, please do ping here or feel free to create a new issue.
