### ISSUE TITLE
Should be clear to see which cells was run last

### ISSUE THREAD

**Issue by patchie** [microsoft/vscode-jupyter#14209]
It should be some indication telling you what was the last run cell, and maybe the last 5. Using fading color or something like that in the border around the cell or something.
Some times, you will run the same notebook several times, and it might take some time, and when you come back, you dont know where you stopped, since the cell run number from yesterday is similar to the one today. so where was the last cell i ran?

**Comment by DonJayamanne** [comment]
Thanks for filing this feature request, given the fact that there haven't been enough upvotes on this issue since it was open, I'm closing this.
