### ISSUE TITLE
Built in CPU/Memory/Cuda/GPU memory monitor

### ISSUE THREAD

**Issue by patchie** [microsoft/vscode-jupyter#14212]
Would be nice to have a resource monitor in the running cell to see how much resources the cell is utilizing.

**Comment by Reslan-Tinawi** [comment]
Hello :)

Any update on this? I'm looking for a way to at least monitor only memory usage.

**Comment by DonJayamanne** [comment]
We try to keep VS Code lean and we think the functionality you're asking for is great for a VS Code extension. Maybe you can already find one that suits you in the [VS Code Marketplace](https://aka.ms/vscodemarketplace). Just in case, in a few simple steps you can get started [writing your own extension](https://aka.ms/vscodewritingextensions). See also our [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Happy Coding!

**Comment by DonJayamanne** [comment]
Here's a sample that achieves this functionality https://github.com/DonJayamanne/vscode-python-kernel-resource-monitor
