### ISSUE TITLE
Entering the URL of the Jupyter server is too deep

### ISSUE THREAD

**Issue by kryptan** [microsoft/vscode-jupyter#14229]
I want to connect to the remote Jupyter server. I press the `Select Kernel` button:

![image](https://github.com/microsoft/vscode-jupyter/assets/11528855/e7f9c411-f5e4-4d7d-aba9-c4e3df865f88)

I'm presented with a text field that looks like a good place to enter the server URL but that doesn't work. Instead, I have to press `Select Another Kernel`.

![image](https://github.com/microsoft/vscode-jupyter/assets/11528855/44e13005-5438-4b7e-b795-6200f4969c60)

I'm presented with another text field that looks like a good place to enter the server URL but that also doesn't work. Instead, I have to press `Existing Jupyter Server`.

![image](https://github.com/microsoft/vscode-jupyter/assets/11528855/a2eb240f-69c6-45ae-9593-8846b56576ed)

I'm presented with yet another text field that looks like a good place to enter the server URL but that again doesn't work. Instead, I have to press `Enter the URL of the running Jupyter server`.

![image](https://github.com/microsoft/vscode-jupyter/assets/11528855/8512e046-08de-44ab-a039-a38b49eec58d)

Finally, I'm presented with a text field that will accept the URL.

![image](https://github.com/microsoft/vscode-jupyter/assets/11528855/808e4fdd-3b9e-4fd0-a912-5d3d1c39a7c3)

---

Overall, to get to the field that accepts the URL I had to skip another 3 text fields. I think it would be nice if any of these intermediate text fields would directly accept the URL.

**Comment by DonJayamanne** [comment]
@kryptan thanks for filing this issue,
we have removed the last step from the kernel picker, that should reduce the number of steps to 3 steps instead of 4.
Plese update to the latest version and let me know how that works.
