### ISSUE TITLE
Server entries look weird without connection info

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#14220]
Testing #14201

![Image](https://github.com/microsoft/vscode-jupyter/assets/876920/35c3f84e-dee5-4cb6-bb36-035b1da5cc78)

Without `detail` the servers look weird compared to the first one, I wonder if we can have some placeholder like "Never connected" or something similar to indicate that the entry is valid but it's not connected yet. Right now it feels like they are partially broken.

**Comment by DonJayamanne** [comment]
Fixed
