### ISSUE TITLE
Confusing UI, or possible bug, for setting non-python jupyter kernel

### ISSUE THREAD

**Issue by jlperla** [microsoft/vscode-jupyter#1422]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1.  Start a new vscode terminal, with (1) the python extension installed ; (2) conda installed with jupyter; and (3) a jupyter kernel for julia installed *inside* whatever the appropriate conda installation is.  i.e. completely standard setup, where you know the kernel works when running `jupyter lab` etc.
2. Open vscode and ensure that the python environment is correctly set to the one you have installed the non-python kernel in.  In my case, the base conda.
3. Create a blank jupyter notebook, it starts at the top saying "No Kerneel: Not Started" as it should
4. Click on that "No Kernel..." to select one

## Actual behavior

It looks like the UI allows you to choose the kernel, but it seems like it really just listing the conda environments?  You can't select Jupyter.

However, if you choose a python kernel  *and then* click on it again, it seems to load the list of kerenels within the conda environment and you can choose the Julia.

I believe that after you have created a `.ipynb` with the non-python kernel selected, it does open up correctly without the mulitple clicks.

## Expected behavior

I would expect to be able to choose the kernel for a non-python kernel installed within my activated conda environment.  Can you load the kernelspecs a little earlier in the UI?

Also, I haven't tested this, but does the current UI allow you to have a non-python kernel associated with multiple conda environments?  They would all point to the same julia executable, for example?  It seems like your UI envisions a conda-style setup where different environments have different directories for the kernels.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by greazer** [comment]
Unfortunately, this bug got lost somewhere in our issue universe till now. I'm going to close it now. @jlperla, feel free to reopen this one or enter a new one of there are further issues you're finding with our non-Python kernel support.
