### ISSUE TITLE
Markdown cells do not intelligently complement latex code in jupyter extensions

### ISSUE THREAD

**Issue by mainDevgithub** [microsoft/vscode-jupyter#14230]
I have installed the LaTex Workshop plugin with the LaTex plugin, and I have texlive installed on my computer with the environment variables set correctly. In VS Code, the .tex file is able to smart hint latex code completion, but not in the markdown cell of the .ipynb file. (Translation from DeepL)

**Comment by rebornix** [comment]
It seems that the LaText extension doesn't work well with the editor in notebook. Please file issue against them, thanks!
