### ISSUE TITLE
Entry for "Select language mode" does not show up

### ISSUE THREAD

**Issue by ShalokShalom** [microsoft/vscode-jupyter#14249]
Hi, lovely people :)

I discovered, after debugging the other remaining systems involved for half an hour, that Jupyter Notebooks seemingly leave no entry in the formidable "Select language mode" menu. 

Yes, I did install the extension, Julia itself, the IJulia package and even the Python kernel.

![Screenshot_20230903_143859](https://github.com/microsoft/vscode-jupyter/assets/6344099/9a65a291-458b-444f-9666-9072da483102)

How can I help you to debug this?

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
Jupyter Notebooks are not the same file format as plain text files, hence you cannot create an untitled text file.
Please use one of the following options to create Jupyter Notebooks
* Use one of the following commands from the command palette
    * `Create Jupyter Notebook`
    * `Create: New File` => `Jupyter Notebook`
* Optionally create a file named `<file name>.ipynb` in the explorer and then open that.

**Comment by ShalokShalom** [comment]
I opened up a feature request at VSCode. In case that gets implemented, this feature request here gets valid again. 

I would ask to open it, so we don't lose track, until this happens.
