### ISSUE TITLE
Mime types unexpected order of rendering

### ISSUE THREAD

**Issue by timeterror** [microsoft/vscode-jupyter#1424]
Recently I've run into the following, which seems related to how mime types are handled in VS Code (see microsoft/vscode-python#11880).

- Run the Python code below within either a _VS Code Python Interactive environment_ or a _Jupyter Notebook within VS Code_.
```python
# %% Test mimetype
from IPython.display import display

class MimeTest:
    def _repr_html_(self):
        return '<b>HTML</b>'
    def _repr_latex_(self):
        return '$\LaTeX$'
    def _repr_markdown_(self):
        return '**Markdown**'
    def _repr_plaintext_(self):
        return 'plaintext'
    def __repr__(self):
        return 'repr'
    def _repr_mimebundle_(self, include, exclude, **kwargs):
        data = {
            'text/html': self._repr_html_(),
            'text/latex': self._repr_latex_(),
            'text/markdown': self._repr_markdown_(),
            'text/plaintext': self._repr_plaintext_(),
        }
        if include:
            data = {k: v for (k, v) in data.items() if k in include}
        if exclude:
            data = {k: v for (k, v) in data.items() if k not in exclude}
        return data

display(MimeTest())
```

- On my machine, the `_repr_mimebundle_` is fully ignored and the preference for displaying is first `'text/markdown'`, then `'text/latex'`, and finally `'text/html'`.
- The expected result is that the following order would be applied microsoft/vscode-python#11880 or that of [IPython](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.formatters.html?highlight=mime#IPython.core.formatters.DisplayFormatter)
- In this case the expected output would be the `'text/html'` mime type, regardless if the `_repr_mimebundle_` is applied.

**Comment by taldcroft** [comment]
I'm running into the same issue, though at a simpler level. I have a class that implements the HTML and LaTeX reprs, so equivalent to:
```
class MimeTest:
    def _repr_html_(self):
        return 'HTML'
    def _repr_latex_(self):
        return 'LaTeX'
```
In VS Code Version: 1.55.2 + Jupyter v2021.5.745244803, entering `MimeTest()` in a Python cells results in LaTeX. Jupyter notebook, Jupyter lab, and VS code insiders notebook all give HTML, which is my expectation.

This behavior has changed. In particular I was doing testing for https://github.com/astropy/astropy/pull/11476 about 26 days ago and I was seeing the expected HTML output for a class with `_repr_html_` and `_repr_latex_` both defined.

**Comment by DonJayamanne** [comment]
This has been fixed.
