### ISSUE TITLE
Visual studio marketplace VSIX release numbers out of sync with github?

### ISSUE THREAD

**Issue by dsjoho** [microsoft/vscode-jupyter#14269]
## Environment data
Irrelevant

## Expected behaviour
It is expected to be able to download the latest stable release (2022.09.120) from
the following link https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2022.09.120/vspackage

I.e. I expect the latest stable release number on github.com to match the version number it was made available on the marketplace

## Actual behaviour

"Resource not found" - the version number that is presented as the latest stable release on github is not the same as what was used on the marketplace. I can thus not find the VSIX file and can't transfer it to my offline environment.

How can I now find the VSIX file for the latest stable release?

## Additional comments regarding vs code marketplace vsix download link
I expect to be able to download the VSIX of the latest stable release from https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
but they seem to list pre-releases instead of latest stable.
This seems to affect quite many users who download VSIX manually. See e.g. https://github.com/microsoft/vscode-jupyter/discussions/13593 and https://github.com/microsoft/vscode-jupyter/discussions/10489 to see that multiple people struggle with this.
If you have the possibility of influencing how the vs code marketplace releases work, please take this into consideration.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, unforatunately we do not support this.
As the part of the build number in the exetnsion is auto generated and not static.

> Additional comments regarding vs code marketplace vsix download link
I expect to be able to download the VSIX of the latest stable release from ...
but they seem to list pre-releases instead of latest stable.

I believe this is a known issue in the Marketplace itself.
@sandy081 are you aware of any Github issue on any repo (marketplace repor or the like that would address this issue)

**Comment by dsjoho** [comment]
Thank you for your prompt reply! And of course for your work in this great extension.

So to check that I understand the phrase "unfortunately we do not support this" properly; it's intentional/accepted that the github release number doesn't match the marketplace release number (since it includes the build number)? 
Is there any way to quickly see what build number that would be so that one can get the vsix in a simple way?

**Comment by DonJayamanne** [comment]
>  it's intentional/accepted that the github release number doesn't match the marketplace release number (since it includes the build number)?

I will create an issue for this on VS Code.
