### ISSUE TITLE
Customer when run the code on vscode (Desktop /Web) an input box would appear asking for a snowflake URL token but it no longer appears

### ISSUE THREAD

**Issue by nadeemrnd** [microsoft/vscode-jupyter#14262]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Customer when run the code on vscode (Desktop /Web) an input box would appear asking for a snowflake URL token but it no longer appears. This used to work fine and now its not working for any user and afffeceting workflow.
This works fine when same code is run on Azure ML notebook. Only issue when run from VScode.
The customer is working on an Azure ML Remote Compute instance

Even tried with new compute instance and facing same issue.

This issue has effected other members of our team as well.

Business impact: blocks us from doing any work, this is one of the pivotal parts to our authentication workflow

From Browser console logs: (For detail logs see the attachment
[No Input box appears to add the token when ran using VScode.docx](https://github.com/microsoft/vscode-tools-for-ai/files/12481204/No.Input.box.appears.to.add.the.token.when.ran.using.VScode.docx)
)

Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': (k,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list......R} could not be cloned.
at https://main.vscode-cdn.net/stable/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/workbench/workbench.web.main.js:591:47236
(anonymous) @ defaultWorkerFactory.ts:116
Promise.then (async)
postMessage @ defaultWorkerFactory.ts:116
sendMessage @ simpleWorker.ts:292
o @ simpleWorker.ts:254
(anonymous) @ simpleWorker.ts:132
sendMessage @ simpleWorker.ts:127
(anonymous) @ simpleWorker.ts:373
[No Input box appears to add the token when ran using VScode.docx](https://github.com/microsoft/vscode-jupyter/files/12527658/No.Input.box.appears.to.add.the.token.when.ran.using.VScode.docx)

![image](https://github.com/microsoft/vscode-jupyter/assets/124931914/d37552a4-9e44-4ab5-bd5e-556f90d0bc19)

### VS Code Version

Latest (Tried using new compute Instance from ML)

### Jupyter Extension Version

Latest (Tried using new compute Instance from ML)

### Jupyter logs

```shell
No error on Jupyter. Input option is not enable to enter the token
```

### Language Extension Version (if applicable)

NA

### Anaconda Version (if applicable)

NA

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing as this has been confirmed as fixed.
