### ISSUE TITLE
Disable auto-scroll

### ISSUE THREAD

**Issue by shane-nichols** [microsoft/vscode-jupyter#14265]
Autoscrolling is poorly implemented and usually jumps far past the target. The config option "Interactive Window: Always Scroll On New Cell" seems to have no effect. The behavior of Jupyter Lab is ideal (no auto scroll) and should be an option.

**Comment by NickCrews** [comment]
Per https://github.com/microsoft/vscode/pull/193126, in the newly released version you can now adjust `notebook.scrolling.revealNextCellOnExecute`!
