### ISSUE TITLE
Duplicated kernel names showed in the selection menu

### ISSUE THREAD

**Issue by guoz14** [microsoft/vscode-jupyter#14268]
What is the issue: 
I have duplicated environment listed when I clicked the environment/kernel selection button on the top right corner. However, I have only two environments and kernels listed when I click "Select Another Kernel". Could anyone please tell me what the reason could possibly be? They seems to be fixed already as I checked previous similar issues. 

What I did: 
I simply reinstalled the vs code.

Btw before Vscode usually directly activates the current kernel if I open cmd terminal in vscode but not anymore, Just curious on why but no biggy.

Thanks a lot!

![image](https://github.com/microsoft/vscode-jupyter/assets/47837118/abd6dc69-1efb-40a4-8b7a-7d2c61eb6704)
![image](https://github.com/microsoft/vscode-jupyter/assets/47837118/81dc9122-70c0-4e9b-9495-fc901d2b73f9)
![image](https://github.com/microsoft/vscode-jupyter/assets/47837118/31cfa9dd-1173-4b66-9b24-3a956e4828b7)

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and sorry you are running into this.

> Btw before Vscode usually directly activates the current kernel if I open cmd terminal in vscode but not anymore, Just curious on why but no biggy.

Not sure when this used to happen, however this isn't a supported scenario.


Thanks for sharing the screenshots.
It looks like these are valid entries.
You have two Python environmentm named `qlib` and `ml`, at the same time you also have 2 kernelspecs registered for these two environments.
The Jupyter Extension for VS Code supports kernels from multiple locations, either from Kernle Specs or just pure Python environments. Kernle Specs is required by the Juptyer Notebook/Jupyter Lab applications. Jupyter Extension does not require them, but supported for more advanced usages where users would like custom env variables or the like for kernelspecs.


The simplest way to get rid of the duplicates is to remove the kernelspec.
You can find where these two kernelspecs are located by one of the two following options
* Install the Jupyter Powertoys extension
    * See here https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-powertoys
    * Open the Jupyter Kernel Management panel on the side activity bar and select the kernel spec
    * From there you can find the location of the kernelspec file
    * Next, you can delete that entire kernelspec folder
* Or, run the command `jupyter kernelspecs list` in your terminal
    * This will list the above two kernelspecs with the paths to the folders for each of the krenlespec
    * You can then delete the kernlespecs you do not need
* Finally you can find more information about kernelspecs here https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs
