### ISSUE TITLE
Can't automaticly quit python language server after quitting VSCode on macOS

### ISSUE THREAD

**Issue by Saafo** [microsoft/vscode-jupyter#1427]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Open a ipynb file in VSCode
2. Close tab or VSCode after finish using it
3. You can find `Microsoft.Python.LanguageServer` still in the background, and can be seen in the `Activity Monitor.app`

## Actual behavior

When I finished using jupyter notebooks in vscode, I close the window, press `cmd+q` to quit VSCode. However, there is a process called `Microsoft.Python.LanguageServer` which can be seen in the `Activity Monitor.app`, and using my memory more than `1G`.

## Expected behavior

When close all of the jupyter notebooks tabs in vscode, the `Microsoft.Python.LanguageServer` in the background should be automaticly quit.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.5.80290
-   **VS Code version:** 1.45.1
-   **Setting python.jediEnabled:** false
-   **Setting python.languageServer:** Microsoft
-   **Python and/or Anaconda version:** Python 3.7.7 & conda 4.8.3
-   **OS:** Mac
-   **Virtual environment:** conda

## Developer Tools Console Output

No output available.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by greazer** [comment]
Year old bug, closing for now. @Saafo, please reopen if this problem still occurs when using notebooks in VS Code Insiders.
