### ISSUE TITLE
Jupyter notebook cell execution slow in vscode

### ISSUE THREAD

**Issue by jhancibo** [microsoft/vscode-jupyter#14283]
## Environment data

-   VS Code version: 1.81.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.7.1002162226
-   Python Extension version (available under the Extensions sidebar): v2023.14.0
-   OS (Windows | Mac | Linux distro) and version: MacOS 3.5.1 (22G90)
-   Python and/or Anaconda version: Python 3.10 conda 23.1.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local 

## Expected behaviour

When executing df.head() for a very small dataframe in pandas, the cell stops working and freezes, until for long time

## Actual behaviour

When executing df.head() for a very small dataframe in pandas, the cell execute immediately.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Run interactive window
2. The click icon and progress bar when run each cell not showing in execution. No "*" in the [] to indicate the program is running.
3. And the execution time is much longer than the past, even with the simple command "df.head()". It used to take 1 second, now it may take minutes.
4. While the execution time is extremely longer than the past, the selected python interpreter disappear under the right bottom corner of IDE when this problem happens, 
5. And also the Jupyter output section on the under of IDE takes extremely long time to load and refresh.
6. All behavior are absent in JupyterLab!
7. The June version of VScode does NOT have those bugs!

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by FlorinAndrei** [comment]
@jhancibo I see something similar, I wonder if it's the exact same issue like the one you have.

First, click the Jupyter extension icon on the extreme left. Make sure Contextual Help is visible. Then trigger the bug.

When I do it, I see the Code Under Cursor in the contextual help very slowly show / delete words, one character at a time. When that happens, cell execution is very slow.

Also, it is only triggered by CTRL-Enter for me. If I click the Execute Cell arrow instead, it's always fast.

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by jhancibo** [comment]
I did what you said but the output from the Jupyter output panel have nothing when it occurred. Any alternative? The problem still persists.

**Comment by DonJayamanne** [comment]
> I did what you said but the output from the Jupyter output panel have nothing when it occurred. Any alternative? The

Do you mean there was nothing at all, or there was no change?
There should be a lot of logging in there.

**Comment by jhancibo** [comment]
Please ignore this ticket, same issue as this ticket https://github.com/microsoft/vscode-jupyter/issues/14459#issuecomment-1776941962
