### ISSUE TITLE
Variable Explorer resizes off the screen

### ISSUE THREAD

**Issue by techwithtim** [microsoft/vscode-jupyter#1431]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Open the variable explorer from the Juypter Notebook interface
2. Drag the border down as far as possible

## Actual behavior
 Goes off the screen and cannot be resized back up

## Expected behavior
Stops at a max height

Notes:
@techwithtim Will fix this...

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local | Remote | N/A
-   **Extension version:** 20YY.MM.#####-xxx
-   **VS Code version:** #.##
-   **Setting python.jediEnabled:** true | false
-   **Setting python.languageServer:** Jedi | Microsoft | None
-   **Python and/or Anaconda version:** #.#.#
-   **OS:** Windows | Mac | Linux (distro):
-   **Virtual environment:** conda | venv | virtualenv | N/A | ...

## Developer Tools Console Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
