### ISSUE TITLE
Jupyter extension should detect the URLs of local running jupyter servers

### ISSUE THREAD

**Issue by iemejia** [microsoft/vscode-jupyter#14313]
Having to select a kernel is always an annoying extra step when running jupyter notebooks. We could avoid this hassle for the local case by detecting locally running jupyter servers and filling automatically the local server URL(s).

We can get the URLs from the CLI tool so I suppose there should be a programmatic way to find them.
```
$ jupyter notebook list
Currently running servers:
http://127.0.0.1:8888/?token=507df4752a97d486289240aaa9514fd1e4031660e0d31c21 :: /Users/ismael
```
This will be a way to simplify also the multiple steps mentioned in #14229

**Comment by DonJayamanne** [comment]
Thank you for filing this issue,
I'd like to understand why you start Jupyter Servers locally and then use VS Code to connect to that.
The feature in VS Code is provided to connect to remote servers, not local.

For local there's no need to start a jupyter server, instead you can just select a kernel spec or just select a Python environment.

**Comment by iemejia** [comment]
I see, I stumbled into this while running jupyter notebooks inside of codespaces. In that case you might need to install the jupyter notebook or it can be pre-installed/started as part of some Docker image. I think the most important reason to use a local server is isolation, with environments any extension can modify the environment. Jupyter server introduces an extra layer of isolation that can also be useful.

(you picked my curiosity, how can you define/select a kernel spec without jupyter, I thought you needed to register those via ipykernel with jupyter).

**Comment by DonJayamanne** [comment]
> (you picked my curiosity, how can you define/select a kernel spec without jupyter, I thought you needed to register those via ipykernel with jupyter).

Kernelspecs can be created/registered even without Jupyter. Jupyter is an application that supports launching the kernels.

> ought you needed to register those via ipykernel with jupyter).

If you select a Pyhon environment, then we prompt the user to install ipykernel if it is not already isntalled.

>  think the most important reason to use a local server is isolation, with environments any extension can modify the environment.

Agreed, then again, there are other benefits, 
I.e. users do not have to isntall Jupyter and other packages (thats a lot to install to get Jupyter working).
When dealing with other kernelspecs like R, Julia, etc, there's no need to install Jupyter/Python at all. thus making it even simpler to use kernels outside the context of Jupyter (which is the original design goal of kernels)

**Comment by DonJayamanne** [comment]
Closing this feature requested as out of scope, there's a sample in the VS Code samples directory if users woudl like to create such an extension
