### ISSUE TITLE
Keep "Restart" button visible if the notebook loses focus

### ISSUE THREAD

**Issue by allefeld** [microsoft/vscode-jupyter#14317]
When the notebook editor loses focus to a regular editor, the "Restart" button in the toolbar disappears:

![image](https://github.com/microsoft/vscode-jupyter/assets/1738353/0ff7e582-f0fb-4cb9-bac3-b34c0cdab2c2)

That is inconvenient because I often use another editor to edit a module (Python), and the notebook which imports this module needs to be restarted to import the new version.

The way it is is just a click more (click to focus the notebook then click on the "Restart" button), but in a longer development session that can still be a lot more clicks.

The behavior is also strange because the other notebook toolbar buttons remain visible, though they are just as applicable or inapplicable as the "Restart" button. Moreover, the button does not disappear if the focus in another notebook.

Please keep the "Restart" button visible even if the notebook loses focus.

**Comment by rebornix** [comment]
<img width="1904" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/876920/8e123a2e-9c1a-490e-9350-443216dd1e95">

The restart button does persist when the notebook editor loses focus, but it only shows up if the kernel is live.
