### ISSUE TITLE
Can't find kernels in latest version of VScode.

### ISSUE THREAD

**Issue by marquis08** [microsoft/vscode-jupyter#14322]
## Environment data

- VS Code version: Version: 1.81.1 (Universal)
- Jupyter Extension version (available under the Extensions sidebar): v2023.8.1002501831
- Python Extension version (available under the Extensions sidebar): v2023.4.0
- OS (Windows | Mac | Linux distro) and version: Ubuntu
- Python and/or Anaconda version: python 3.10.0, conda 23.3.1
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Jupyter server running: Remote

## Expected behaviour
Find kernels that already installed.

## Actual behaviour

As mentioned in #14259, after a while it works as expected.  
But today it the same as it was like keep finding kernels endlessly.

![image](https://github.com/microsoft/vscode-jupyter/assets/27425140/4f5f9c0b-78c4-4a97-a503-c666e33b023d)

**Comment by DonJayamanne** [comment]
Looks like the Jupyter extension hasnt been activated
Please can you used the command ‘Toggle Developer Tools’
Then have a look at the console window and see if there are any errors

of that fails then
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
> v2023.4.0

looks like you are not using the latest version of python extension either
Please update that to the latest version

If that fails then please feel free to file another issue
