### ISSUE TITLE
Variables are not rendered for intermediate cells when using Run All

### ISSUE THREAD

**Issue by iemejia** [microsoft/vscode-jupyter#14328]
## Environment data

-   VS Code version: 1.82.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.8.1002501831
-   Python Extension version (available under the Extensions sidebar): v2023.16.0
-   OS (Windows | Mac | Linux distro) and version: Mac (Darwin arm64 22.6.0)
-   Python and/or Anaconda version: 3.10 / 23.3.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local & Remote

## Expected behaviour

While running a notebook with multiple steps that takes long time to train a model in a cell. I expected ot be able to explore the variables of previous steps to check that everything is in order
![jupyter-variablesnotshowwhilerunning](https://github.com/microsoft/vscode-jupyter/assets/79476/ea737126-1300-4653-92d2-04f0f5a9256a)

## Actual behaviour

I have to wait until the full run of the notebook to be able to review the variables.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create a new notebook
2. Add a cell with a variable
```python
i = 1
```
3. Add a cell that sleeps
```python
import time
time.sleep(10)
```
4. Open Variables View
5. Press Run All, it will stay for a while in the second cell and you won't be able to see the values of the variable `i` declared in the first one.

**Comment by DonJayamanne** [comment]
Thanks for filling this issue
This is deliberate, getting variables values odd an expensive operation, 

displaying the variables information while executing cells used to be done in the past, 
However that proved very inefficient, and ended up slowing execution of the cells , this it was updated to only refresh the information after everything completed

Assume for instance there was a very complex set of variables, getting all of that information is slow and time consuming, fetching that information between each cell further delays execution of cells

Closing as not planned
@rebornix @minsa110 /cc

**Comment by iemejia** [comment]
Ah I see, a pity but I understand also the argument. Thanks!
