### ISSUE TITLE
Error: Cannot run cells, duplicate documents found

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-jupyter#1433]
## Environment data

- VS Code version: 1.37.1
- Extension version: latest insiders build
- OS and version: macOS 10.14.6
- Python version: 3.6.7 (miniconda)

## Expected behaviour

Executing cells in the Python interactive window should work even if a file is open in multiple tabs.

## Actual behaviour

I get the error message

> Cannot run cells, duplicate documents for my_notebook.py found.

## Steps to reproduce:

1. Open a Python file with code cells and uncommited changes.
2. Also open the file in working tree view (changes side by side).
3. Go back to the first tab and try to run any cell. It only works once all other tabs with that file have been closed.

**Comment by greazer** [comment]
I no longer repro this. Assuming it's been fixed.

**Comment by janosh** [comment]
Yep, no longer experiencing this either. Thanks for fixing!
