### ISSUE TITLE
Add Notebook template support

### ISSUE THREAD

**Issue by Tanvir786123** [microsoft/vscode-jupyter#14337]
It would be nice if this extension could support something like this [library](https://pypi.org/project/jupytemplate/), which essentially enables **all** notebooks to inherit a **customised** template to provide consistency, especially for large projects.

**Comment by Tanvir786123** [comment]
I should note that my current solution is to use this [extension](https://marketplace.visualstudio.com/items?itemName=bam.vscode-file-templates).

However, it isn't ideal because it's an **additional** extension, which is buggy. It would be nicer if this extension could mimic the `jupytemplate` instead.

**Comment by amunger** [comment]
closing as there hasn't been any additional votes to support implementing this
