### ISSUE TITLE
Python package 'pandas' version 0.20.0 (or above) is required for viewing data even though installed higher version of pandas

### ISSUE THREAD

**Issue by xu20160924** [microsoft/vscode-jupyter#14332]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When I right-click to View value in Data Viewer, it raises up warning that "Python package 'pandas' version 0.20.0 (or above) is required for viewing data", but I have already installed pandas with 1.2.5, if I choose to install, Data viewer will be ok, however, my project will not be startable. I have observed the chosen install that replaced 1.3.5 of pandas of 1.2.5 both are higher than 0.20.0. Hope anyone helps me, the Data viewer is really helpful.
<img width="372" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/22407827/85929bea-6263-4677-b725-74521ddfcde2">

### VS Code Version

1.70.0

### Jupyter Extension Version

v2022.8.1002431052

### Jupyter logs

```shell
info 21:31:28.728: Found debugAdapterPython on Debug Configuration to use
info 21:31:28.772: Process Execution: > ~/xxx/venv/bin/python -c "import pandas;print(pandas.__version__)"
> ~/xxx/venv/bin/python -c "import pandas;print(pandas.__version__)"
warn 21:31:29.270: Failed to get version of Pandas to use the Data Viewer. /home/work/xxx/venv/lib/python3.7/site-packages/pandas/compat/__init__.py:109: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

error 21:32:5.204: [Error: Python package 'pandas' version 0.20.0 (or above) is required for viewing data.
  at s.promptInstall (/home/work/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431052/out/extension.node.js:17:291013)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 21:32:5.204: DataScience Error [Error: Python package 'pandas' version 0.20.0 (or above) is required for viewing data.
  at s.promptInstall (/home/work/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431052/out/extension.node.js:17:291013)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)]
```

### Coding Language and Runtime Version

python 3.7.10

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
looks like we're failing when trying to get the version

```
Jupyter Extension: Failed to get version of Pandas to use the Data Viewer. 
c:\src\test\ws1\.venv\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\src\test\ws1\.venv\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
c:\src\test\ws1\.venv\lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
```

**Comment by amunger** [comment]
It looks like this can happen if you end up with multiple uninstalls of numpy, and maybe installing pandas 1.3.5 puts you in that situation.

I was able to get the data viewer to work with pandas 1.3.5 after uninstalling both versions of numpy (I just ran `pip uninstall numpy` twice) and then reinstalling it.

let me know if that doesn't work for you.

Closing as this seems like a python package manager issue.

**Comment by xu20160924** [comment]
I‘ve tried uninstalling and recreating the virtual environment and reinstalling dependencies, but all of this doesn't work for me, it still mentions me "Python package 'pandas' version 0.20.0 (or above) is required for viewing data." By the way,  what I expected was to work with 1.2.5 pandas, since my project looks incompatible with  1.3.5.
