### ISSUE TITLE
Cell execution time lost after reloading

### ISSUE THREAD

**Issue by marctorsoc** [microsoft/vscode-jupyter#14342]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When reloading the window, the notebook "forgets" about the **execution time**. Interestingly, does not "forget" about the **execution order**

![image](https://github.com/microsoft/vscode-jupyter/assets/22045779/057a1425-8ec6-4bee-80e1-78e8ad70b389)

This is what I'd like to see (the 0.0s. Obviously, in this case it's not useful, but in other cases might be worth knowing how long it took to run the last time)

![image](https://github.com/microsoft/vscode-jupyter/assets/22045779/1afdac47-fa69-4f58-9c31-dbac7a3ebffc)

This especially critical for a remote (but happens also locally), because every day I turn on and off the machine, so reload the window, and lose all this information.

### VS Code Version

Version: 1.82.2 (Universal) Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d Date: 2023-09-14T05:59:47.790Z Electron: 25.8.1 ElectronBuildId: 23779380 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Darwin x64 22.6.0

### Jupyter Extension Version

v2023.8.1002501831

### Jupyter logs

```shell
Lmk if you need this. Not sure is needed in this case
```

### Coding Language and Runtime Version

python 3.9

### Running Jupyter locally or remotely?

Local

**Comment by roblourens** [comment]
This is because execution order is part of the jupyter notebook format, but execution time isn't. We don't write extra metadata from vscode to your notebook file, so I think it isn't really practical for us to keep this data unfortunately.

**Comment by marctorsoc** [comment]
In some jupyter extensions the metadata is saved e.g. https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/execute_time

I see you changed from `bug` into `feature-request`. I can agree with this. Is there anything else I can do to surface this feature request?
