### ISSUE TITLE
jupyter notebook latex math equations render error 

### ISSUE THREAD

**Issue by lubianh93** [microsoft/vscode-jupyter#1434]
# environment
vscode 1.44.2
vscode-python-ext: 2020.4.76186
# recurrent
1. make a blank ipynb file
2. paste the following code as markdown into the first cell

> $$ \text{For } x \in \mathbb{R}^n \text{,     } sigmoid(x) = sigmoid\begin{pmatrix}
    x_1  \\
    x_2  \\
    ...  \\
    x_n  \\
\end{pmatrix} = \begin{pmatrix}
    \frac{1}{1+e^{-x_1}}  \\
    \frac{1}{1+e^{-x_2}}  \\
    ...  \\
    \frac{1}{1+e^{-x_n}}  \\
\end{pmatrix}\tag{1} $$ 

the result cannot be displayed properly. but the result is displayed correctly in the other **markdown**

I tried to delete all the carriage returns and it displayed correctly.
> $$ \text{For } x \in \mathbb{R}^n \text{,     } sigmoid(x) = sigmoid\begin{pmatrix}    x_1  \\    x_2  \\    ...  \\    x_n  \\\end{pmatrix} = \begin{pmatrix}    \frac{1}{1+e^{-x_1}}  \\    \frac{1}{1+e^{-x_2}}  \\    ...  \\    \frac{1}{1+e^{-x_n}}  \\\end{pmatrix}\tag{1} $$

**Comment by mjbvz** [comment]
This now appears to render properly using native notebooks with VS Code 1.60

<img width="814" alt="Screen Shot 2021-08-04 at 11 05 48 PM" src="https://user-images.githubusercontent.com/12821956/128299647-38854a11-dbeb-46b5-8437-cdea7d89a040.png">
