### ISSUE TITLE
Enter manually the path of the jupyter kernel

### ISSUE THREAD

**Issue by iXrst** [microsoft/vscode-jupyter#14344]
Being able to manually enter the path of the Jupyter (Select Python Environment) notebook kernel or to set it in the workspace settings.

   - In the graphical option to add the kernel (Select Python Environment) not all of them are displayed, one reason could be similar to the discussion in this issue [https://github.com/microsoft/vscode-jupyter/issues/9703](url) which is about the location where the 'venv' is stored.
   - Or being able to configure it in the workspace settings, as was discussed in this request [https://github.com/microsoft/vscode-jupyter/issues/9703](url)

**Comment by rebornix** [comment]
I wonder if it makes sense to have a `+ Jupyter Kernel` action, similar to the `+ Create Python Environment` action.

**Comment by DonJayamanne** [comment]
> [https://github.com/microsoft/vscode-jupyter/issues/9703](https://github.com/microsoft/vscode-jupyter/issues/url)

Such an issue does not exist.

> Being able to manually enter the path of the Jupyter (Select Python Environment) notebook kernel or to set it in the workspace settings.

I'm struggling to understand the issue.
Is the problem the fact taht some kernels  do not show up,
Or the fact that your jupyter servers do not show up.
Please could you try to share some screenshots or the like that would help us understand the problem.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
