### ISSUE TITLE
Give a option to disable the `Execute Cell` button beside the cell.

### ISSUE THREAD

**Issue by baiguoname** [microsoft/vscode-jupyter#14341]
Sometimes it would be annoying that the `Execute Cell` button keep showing up, and run the cell by a mistaken clicking on the button.
![image](https://github.com/microsoft/vscode-jupyter/assets/52092777/be17d8f1-6866-4042-9366-105f1b2f3f0a)
It would be very grateful if there is a option provided to disable the button showing up.

**Comment by baiguoname** [comment]
It seems to me that the code from https://github.com/microsoft/vscode-jupyter/blob/main/src/webviews/webview-side/react-common/image.tsx line 137 would be the place the button loaded.

**Comment by DonJayamanne** [comment]
Thanks for filing this feature request, given the fact that there haven't been any upvotes on this issue since it was open, I'm closing this.
