### ISSUE TITLE
Transient data in cells is causing jupyter to complain

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1435]
Got this when opening a saved notebook from us:

![image](https://user-images.githubusercontent.com/19672699/79253952-d846ac00-7e38-11ea-9a2a-58dc1cef45ee.png)

Need to remove transient fields when saving

**Comment by greazer** [comment]
Doesn't seem reproable. I tried again in latest insiders... Opened a notebook generated from a python script IW session.
