### ISSUE TITLE
JupyterHub with username/password

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#14367]
Refs: #13973

- [x] anyOS: @rebornix  
- [x] anyOS: @amunger 
- [x] web: @joyceerhl

Complexity: 5

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2314367%0A%0A&assignees=DonJayamanne)

---

# Pre-Requisites
* Install VS Code insiders
* Jupyter pre-relese extension
* JupyterHub extension

# Install and launch Jupyter Hub
https://jupyterhub.readthedocs.io/en/1.2.0/installation-guide-hard.html
1. Create a new folder
2. Create a file named `jupyterhub_config.py` and paste the below contents into that file
    1.  Custom config to make auth easier, else you need use your login creds, which I guess you don't want to use.
```python
# Configuration file for jupyterhub.

c = get_config()  #noqa
c.JupyterHub.authenticator_class = 'jupyterhub.auth.DummyAuthenticator'
c.DummyAuthenticator.password = "pwd" # Feel free to change the default password
c.Spawner.args = ['--NotebookApp.allow_origin=*']
from jupyterhub.spawner import SimpleLocalProcessSpawner
c.JupyterHub.spawner_class = SimpleLocalProcessSpawner
```
3. Create a virtual env in this folder using Python extension
4. Install Jupyterhub using the CLI `python -m pip install jupyterlab jupyterhub`
5.  Install the npm package `configurable-http-proxy` globally via the cli `npm i -g configurable-http-proxy`
6. Now start Jupyter Hub using the cli `jupyterhub` (ensuring the cwd in the terminal is the same folder in step 1 and your virtual env is in the same folder under `.venv`)
7. In the browser navigate to Jupyter Hub login page, genrally `http://localhost:8000`

# Note:
* There is no need to log into JupyterHub

# Steps to test
1. Go into VS Code, open a notebook
2. From the kernel picker select `Existing JupyterHub Server...`
3. Enter the Jupyter Hub Url `http://localhost:8000` (that shouldbe all)
4. [ ] Verify you are prompted for your user name and password (remember password is `pwd`)
Note: Remember to use the same user name (else it will not work, these are things to be ironed out later)  
6. [ ] Verify you now get a list of Kernels in the kernel picker
7. [ ] Verify you can select a kernel and run code against this kernel

**Comment by amunger** [comment]
>  Remember to use the same user name
The same as what? My windows username does not work

**Comment by DonJayamanne** [comment]
> Also tried adding c.DummyAuthenticator.username to the config without success

Looks like Jupyterhub doesn't work on windows, 
Please could you try swapping with one of the  Python ext engineers or please try WSL or linux
I recall Joyce too running into issues with windows.

**Comment by DonJayamanne** [comment]
@amunger perhaps you can try codespaces, see Joyces comment here https://github.com/microsoft/vscode-jupyter/issues/14202#issuecomment-1698369706

**Comment by rebornix** [comment]
I can get it working on macOS. The setting I use to launch jupyter hub is as below, so I was able to use user name `dummy` and password `pwd` to connect to the Hub.

```py
c.JupyterHub.authenticator_class = "dummy"
c.DummyAuthenticator.password = "pwd" # Feel free to change the default password
c.Spawner.args = ['--NotebookApp.allow_origin=*']
c.Spawner.default_url = '/lab'
from jupyterhub.spawner import SimpleLocalProcessSpawner
c.JupyterHub.spawner_class = SimpleLocalProcessSpawner
```

**Comment by amunger** [comment]
WSL did not work, but I was able to use the same technique as Joyce.
Pretty sure I needed to log in to the browser first to get the username/password to work though, it sounds like Joyce did as well.

**Comment by DonJayamanne** [comment]
> Pretty sure I needed to log in to the browser first to get the username/password to work though, it sounds like Joyce did as well.

Thanks for that comment @amunger , I found the reason why you'd have to do that, created an issue to try and address that at least in desktop (for vscode.dev there's nothing we can do about it)
https://github.com/microsoft/vscode-jupyter-hub/issues/29
