### ISSUE TITLE
Testing Jupyter Extension API

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#14368]
Refs: #13894

- [x] anyOS: @rebornix  
- [x] anyOS: @amunger 

Complexity: 5

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2314368%0A%0A&assignees=DonJayamanne)

---

# Steps
* Create a sample VS Code extension using `yo code` or by any other means
    * Or use this sample https://github.com/microsoft/vscode-extension-samples/pull/913
* Run `npm install @vscode/jupyter-extension` to install the typedef of the Jupyter Extension API

Things to try:
* [ ] Review the API and contribute a new item for the Kernel Picker 
* [ ] Verify it shows up in the kernel picker along with `Python Environments`, `Jupyter Kernels`, `Existing Jupyter Server`
* [ ] Contribute Jupyter Servers (with ids and lables) and verify they show up in the quick pick upon selecting the newly contributed item
* [ ] Verify the documentation in the API is clear enough.
* [ ] Trigger the `onDidChangeServers` event and verify the new Servers are displayed in the quick pick
* [ ] Create at least two commands and verify they are displayed in the quick pick
    * [ ] Verify selecting each command ends up calling the `handleCommand` with the right arguments.
* Create only one command and ensure there are no servers
    * [ ] Upon selecting your server from the kernel picker, verify the command is automatically selected.

@rebornix 
* [x] Verify you are able to select a valid Jupyter Kernel from the extension you build
* [x] Verify you are able to execute a cell from the kernel selected
* [x] Reload VS Code and verify the same kernel  is auto selected in the kernel picker
* [x] Go into the kernel picker and verify the server is now listed with a date/time for the last connection

**Comment by rebornix** [comment]
It's working as expected, great work! I have moved my Docker Connect extension to the new API and it's seamless. 👏 

The only challenge with my Docker Connect extension is mapping directory, I found a couple of issues with how it works (from my understanding the new mapping didn't get https://github.com/microsoft/vscode-jupyter/pull/12446/files#r1058626552 resolved unfortunately) but we can discuss later.

**Comment by amunger** [comment]
I'm not sure what should be in the value parameter here, isn't the value entered just my Server Provider that they selected? It seemed to be undefined when I tried using it.

```
    /**
     * Returns a list of commands to be displayed to the user.
     * @param value The value entered by the user in the quick pick.
     */
    provideCommands(value: string | undefined, token: CancellationToken): ProviderResult<JupyterServerCommand[]>;
```

**Comment by amunger** [comment]
It also wasn't totally clear to me where commands were going to show up (along with my provided servers, or after selecting one), but it was easy enough to add a dummy command to find out. Totally makes sense how it works once I got the hang of it.

**Comment by amunger** [comment]
pretty nice

![Recording 2023-09-26 at 13 13 30](https://github.com/microsoft/vscode-jupyter/assets/2019016/0287088f-faeb-46a5-854e-2fbc73dbb82b)
