### ISSUE TITLE
Azure ML widgets look off when rendering.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1436]
We show this:
![image](https://user-images.githubusercontent.com/19672699/78413883-5485f780-75ce-11ea-850e-734634ee2d20.png)

Jupyter Lab shows this:
![image](https://user-images.githubusercontent.com/19672699/78413980-cf4f1280-75ce-11ea-86c0-d80f9f0aaf8d.png)

Seems there are some slight differences.

**Comment by DonJayamanne** [comment]
Closing as this is no longer an issue.
