### ISSUE TITLE
Native Notebooks - Error loading preloads: Cannot read property 'src' of null

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode-jupyter#1437]
## Environment data

-   VS Code version: 1.51.0-insider
-   Extension version (available under the Extensions sidebar): v2020.11.311084263-dev
-   OS and version:  Darwin x64 19.6.0
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.6, conda
-   Type of virtual environment used : Conda
-   Relevant/affected Python packages and their versions: Altair=4.1.0
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: pylance

With the new Native Notebook and default "Jupyter Notebook Renderer", I'm getting some error's when trying to view plots as pngs, with both R/ggplot and Python/altair. 

- Altair: if I change the render from 'mimetype' (png) to html the chart outputs fine. 

- R/ggplot: the chart will display if I change to the builtin png renderer.

<img width="711" alt="Screen Shot 2020-10-31 at 08 24 40" src="https://user-images.githubusercontent.com/29611875/97783174-45aaf780-1b53-11eb-88a9-9df375724880.png">
<img width="690" alt="Screen Shot 2020-10-31 at 08 25 50" src="https://user-images.githubusercontent.com/29611875/97783176-4774bb00-1b53-11eb-8064-dde30cb05af8.png">

## Expected behaviour

Chart output png images are displayed.

## Actual behaviour

Error loading preloads: Cannot read property 'src' of null

## Steps to reproduce:
```
import altair as alt
import pandas as pd

# doesn't work with png
alt.renderers.enable('mimetype')

# does work with html
# alt.renderers.enable('html')

source = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]})

alt.Chart(source).mark_bar().encode(
    x='a',
    y='b')
```

## Logs
attached
[native notebook png output issue.txt](https://github.com/microsoft/vscode-python/files/5469349/native.notebook.png.output.issue.txt)

**Comment by DonJayamanne** [comment]
Been a few months since this was fixed hence closing this.
