### ISSUE TITLE
Paste in Jupyter Notebook makes a copy to the Terminal window

### ISSUE THREAD

**Issue by Locietta** [microsoft/vscode-jupyter#1438]
# Bug: Notebook Editor

## Steps to cause the bug to occur

1. click to focus the vscode built-in terminal window

2. focus back to notebook

3. copy & paste

## Actual behavior

paste to both notebook and terminal

## Expected behavior

paste to only notebook

### Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local 
-   **Extension version:** 2020.7.94776
-   **VS Code version:** 1.47.2
-   **Setting python.jediEnabled:** false
-   **Setting python.languageServer:** Microsoft
-   **Python and/or Anaconda version:** 3.8.3
-   **OS:** Windows 10
-   **Virtual environment:** conda

## Developer Tools Console Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by rchiodo** [comment]
This is fixed in upstream.
