### ISSUE TITLE
Add specific support for sagemath kernels

### ISSUE THREAD

**Issue by davidmartcresp** [microsoft/vscode-jupyter#14389]
I'm having trouble trying to get things smoothly between this extension and Sagemath. Sagemath is python but not quite, there is an extra layer to make symbolic mathematics more friendly. This extension detects the kernel and treat it like regular python which is fine because it works. However, not knowing  this distinction magic commands as "%display latex" the symbolic computations spits out a non humanly readable string that is key for symbolic computation. Also, by treating it like python my other extensions  detect a lot of syntax errors.

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to run a cell from a notebook with the sagemath kernel selected

I would have expected sagemath kernels to be treated as non-python kernels.
Please do share the logs

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
