### ISSUE TITLE
Automatic new line after typing

### ISSUE THREAD

**Issue by sirio3mil** [microsoft/vscode-jupyter#14380]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

In any cell I try to type anything and after each letter automatically create a new line

### VS Code Version

1.83.0-insider

### Jupyter Extension Version

v2023.9.1002711100

### Jupyter logs

```shell
there is no log, its typing problem
```

### Coding Language and Runtime Version

Python 3.10.10

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
@rebornix @Yoyokrazy could this have something to do with auto format?
