### ISSUE TITLE
Notebook Markdown/HTML `<a>` tag broken when nested

### ISSUE THREAD

**Issue by osterhoutan** [microsoft/vscode-jupyter#1441]
## Environment data

-   VS Code version: 1.51.0
-   Extension version: v2020.10.332292344
-   OS and version: Win10 1909
-   Python version: Python 3.8.3 (64bit) (w/ anaconda)
  -   Anaconda Version:  conda 4.8.5
-   Type of virtual environment used: conda
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: `"Pylance"`

## Constant Info
Due to issue/feature-request microsoft/vscode-jupyter#1335 I am having to use HTML tags in certain places in order to accomplish certain formatting that is normally possible in Jupiter notebook/lab & Google colab.  
In this case I am trying to make a web link clickable while being formatted inside of some `<font>` tags.
Since while URL's _**not**_ surrounded by HTML tags are clickable in markdown syntax by default 
  (_i.e._ without having to use the `[...](...)` markdown syntax)
  they are not clickable when surrounded by HTML tags.
Therefore I used an `<a>` tag to make it clickable, resulting in the code below:
```md
<!-- Some normal/plain markdown code here -->
<font size="4">
    The DTM for w#x where w is a substring of x. </br>
    <i>(See the definition of substring and subsequence at 
    <a href="https://en.wikipedia.org/wiki/Substring">https://en.wikipedia.org/wiki/Substring</a>)</i>
</font>
``` 

## Expected behavior
First of all I would prefer to be able to just do something like this:
```md
<!-- Some normal/plain markdown code here -->
<font size="4">
  The DTM for w#x where w is a substring of x. </br>
  _(See the definition of substring and subsequence at https://en.wikipedia.org/wiki/Substring )_
</font>
<!-- Some more normal/plain markdown code here -->
```
But regardless it should end up looking something like this:
> ![Expected behavior (mostly)](https://i.imgur.com/lrHMYRm.png)
> Except the font size should respect what is in the HTML `<font>` tags.

## Actual behavior
It does this weird thing:
> ![Actual Behavior](https://i.imgur.com/YEqZeAv.png?1)
> As you can see it somehow replaces the contents of the `<a>` tag with the corresponding markdown syntax, which is just plain strange.

## Steps to reproduce
Just nest an `<a>` tag inside some other html code,
 (I gave my code before in the Constant Info section above).

## Logs

<details>
<summary>N/A</summary>
</details>

**Comment by joyceerhl** [comment]
This is fixed in native notebooks: 
![image](https://user-images.githubusercontent.com/30305945/131575371-0b41c2fd-2c14-46b1-8d8e-3ca436eaff3c.png)
