### ISSUE TITLE
Unexpected error message "Python 3.9.0 64-bit required ipykernel to be installed" pops up when run cell with conda environment.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#1442]
## Environment data
![image](https://user-images.githubusercontent.com/59192491/98323573-0e41bc80-2025-11eb-867d-82c7d3d9b8a3.png)

## Expected behaviour
Interactive Window should open, show connection information, and execute cells.

## Actual behaviour
Unexpected error message "Python 3.9.0 64-bit required ipykernel to be installed" pops up.
![image](https://user-images.githubusercontent.com/59192491/98323827-c4a5a180-2025-11eb-9a86-8b98778e27f1.png)

## Steps to reproduce:
1. Make sure Anaconda installed in local
2. Open the file manualTestFile.py in VSCode
3. Select conda Interpreter as current environment
4. On the first cell click 'Run Cell And All Below'

**Comment by greazer** [comment]
@linette-zyy, can you setup a repro? We need to be able to look at a machine or get the logs from a machine that's exhibiting this behavior.

**Comment by linette-zyy** [comment]
I have installed the latest extensions, the issue is not repro.

**Comment by DonJayamanne** [comment]
@linette-zyy apologies for not getting back to you, please could you confirm you are still experiencing this issue.
