### ISSUE TITLE
Update @jupyterlab and @jupyter-widget npm packages to latest (with support for new WebSocket Protocol)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#14422]
There are some changes in the npm pakcages,
Some have been bumped to a new version, due to changes in protocol

Update to latest
* Update in ipywidgets package
* Update in jupyter extension
* Update in renderess
* Update in powertoys
* Update in jupyterhub

Required for https://github.com/microsoft/vscode-jupyter/issues/13565, IPyWidgets, changes in protocol messages, 

**Desktop: Start jupyter server**
* [x] Test connecting
* [x] Test execution
* [x] Test selecting an existing kernel and executing code
* [x] Test widgets with a new kernel
* [x] Test widgets with an existing kernel and executing code
* [x] Test complex widgets
* [x] Test linking widgets
* [x] Test ipysheets
* [x] Test k3d
* [x] Desktop: Reload VS Code and test against existig kernels as well 

**Web: Start jupyter server**
* [x] Test connecting
* [x] Test execution
* [x] Test selecting an existing kernel and executing code
* [x] Test widgets with a new kernel
* [x] Test widgets with an existing kernel and executing code
* [x] Test complex widgets
* [x] Test linking widgets
* [x] Test ipysheets
* [x] Test k3d
* [x] Web: Reload VS Code and test against existig kernels as well 

**Web: Start jupyter Hub server**
* [x] Test connecting
* [x] Test execution
* [x] Test selecting an existing kernel and executing code
* [x] Test widgets with a new kernel
* [x] Test widgets with an existing kernel and executing code
* [x] Test complex widgets
* [x] Test linking widgets
* [x] Test ipysheets
* [x] Test k3d
* [x] Web: Reload VS Code and test against existig kernels as well

**Comment by DonJayamanne** [comment]
Plan
* Release a pre-release version of the Jupyter Notebook Renderers extension (with latest npm packages)
    * [ ] Verify this works with the latest stable and insiders version of Jupyter extension 
    * [ ] Verify this works with the latest stable and insiders version of VS Code
* Release a pre-release version of Jupyter extension (with latest npm packages)
    * [ ] Verify user is prompted to install latest pre-release version of Renderers when using IPyWidgets
    * [ ] Verify regular execution works with latest pre-release version of Renderers
    * [ ] Verify regular execution works with latest stable version of Renderers
    * [ ] Verify widgets works with latest pre-release version of Renderers

**Comment by rebornix** [comment]
Today
| VS Code Version | Jupyter Version | Renderer Version | Testing |
|-----------------|-----------------|------------------|---------|
| 1.94                         | x (not applicable) | x (not applicable) |  |
| 1.95-Insiders          | 2024.09 Stable          | Stable | ✅  |
| 1.95-Insiders          | Prerelease w/ update          | Stable | ✅ |


Bump engine of the renderer extension and publish prerelease next week

| VS Code Version | Jupyter Version | Renderer Version | Testing |
|-----------------|-----------------|------------------|---------|
| 1.95-Insiders          | 2024.09 Stable          | Prerelease w/ update |   |
| 1.95-Insiders          | Prerelease w/ update          | Prerelease w/ update |  |
| 1.95-Insiders          | Prerelease w/o update          | Prerelease w/ update |  |

**Comment by DonJayamanne** [comment]
Closing as completed, all thats remaininmg is publishing the two extensions.
