### ISSUE TITLE
Unexpected results when hit 'a' and 'b' Keyboard Shortcuts.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#1443]
## Environment data
![image](https://user-images.githubusercontent.com/59192491/98368925-16c0e400-2073-11eb-8bac-1632b26ead56.png)

## Expected behaviour
Hit 'a', the selected cell moves up
Hit 'b', the selected cell moves down

## Actual behaviour
Hit 'a', created a new cell on the selected cell.
![image](https://user-images.githubusercontent.com/59192491/98369295-b2525480-2073-11eb-9f05-5fff7c6174ff.png)
Hit 'b', created a new cell under the selected cell.
![image](https://user-images.githubusercontent.com/59192491/98369406-ddd53f00-2073-11eb-938d-713499e6b3df.png)

## Steps to reproduce:
1. Run cell and export as Jupyter notebook named 'tester.ipynb' in interactive window.
2. Open tester.ipynb in editor
3. Hit `a` and verify the selected cell moves up
4. Hit `b` and verify the selected cell moves down

**Comment by greazer** [comment]
@linette-zyy, I'm not following. What you describe sound by-design. If you press a on a cell, a new cell is inserted above. If you press b a new cell is inserted below. This is correct behavior.
