### ISSUE TITLE
Add support for ipython question marker operator

### ISSUE THREAD

**Issue by ybc1991** [microsoft/vscode-jupyter#1445]
## Description
Ipython has a very useful `?` operator to explore the signature and definition of functions. It is supported in the jupyter notebook as well. For example, when we type and run `numpy.exp?` in the cell, a full doc will be popped from the bottom of the browser. However, when I did the same thing in vs-code environment, nothing would be shown. I believe this feature is useful for lots of programers.

**Comment by DonJayamanne** [comment]
Thanks for filing this feature requets, howver this has been marked for deprecation and hasn't received any new upvotes.
This feature is available in Juptyer Notbeooks via the payloads feature which has been marked for deprecation, see here https://jupyter-client.readthedocs.io/en/stable/messaging.html#payloads-deprecated

Also the current behaviour in VS Code lines up with that of Jupyter Labs.
