### ISSUE TITLE
Cannot connect to jupyter lab with special character like @ in the url

### ISSUE THREAD

**Issue by ypj0202** [microsoft/vscode-jupyter#14455]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The Jupyter Hub I am using uses user's email as username. 
The URL is like the following when vscode try to request a ist of kernel: `https://jupyter.example.com/user/user%40example.com/`
A vs code cannot retrieve the kernel as it translates the special character to `@` to `%40` result in 404 not found. 
When I  try to replace the `%40` back to `@` and try in my browser and it returns a list of URL:
```
[
    {
        "id": "8a195b2f-7d39-4bb0-a4ed-e5b65e269e4e",
        "name": "python3",
        "last_activity": "2023-10-06T09:56:09.408009Z",
        "execution_state": "idle",
        "connections": 2
    }
]
```
But in VSCode it does not work.

### VS Code Version

1.82.3

### Jupyter Extension Version

v2023.8.1002501831

### Jupyter logs

```shell
[error] UniversalRemoteKernelFinder: Failed to get kernels without cache t [Error]: Invalid response: 404 Not Found
    at Function.create (~\.vscode\extensions\ms-toolsai.jupyter-2023.8.1002501831-win32-x64\out\extension.node.js:2:68150)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.t.listRunning (~\.vscode\extensions\ms-toolsai.jupyter-2023.8.1002501831-win32-x64\out\extension.node.js:2:55954)
    at xm.getRunningKernels (~\.vscode\extensions\ms-toolsai.jupyter-2023.8.1002501831-win32-x64\out\extension.node.js:17:167615)
    at async Promise.all (index 0)
    at Mm.listKernelsFromConnection (~\.vscode\extensions\ms-toolsai.jupyter-2023.8.1002501831-win32-x64\out\extension.node.js:17:176326)
    at ~\.vscode\extensions\ms-toolsai.jupyter-2023.8.1002501831-win32-x64\out\extension.node.js:17:174573 {
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://jupyter.example.com/user/user%40example.com/api/kernels?1696586173731',
      status: 404,
      statusText: 'Not Found',
      headers: [I [Headers]],
      counter: 0
    }
  },
  traceback: ''
}
```

### Coding Language and Runtime Version

Python 3

### Running Jupyter locally or remotely?

Remote

**Comment by nikita-dev-null** [comment]
I have the same problem

**VS Code Version**: 1.83.0
**Jupyter Extension Version**: v2023.9.1002770152

**Comment by DonJayamanne** [comment]
@nikita-dev-null @ypj0202 
Sorry you are running into this issue and thanks for filing this.

I believe this VSIX shoudl fix it.
* Please download this file
* Extract the zip file
* Go into VS Code and select the command `Extensions: Install from VSIX`
* Select the extracted vsix
* Reload VS Code when prompted to do so, 
* Try again and this shoudl work

Let em know how that goes.

**Comment by nikita-dev-null** [comment]
@DonJayamanne 
In my case, it helped
Thank you very much!

**Comment by ypj0202** [comment]
This is indeed the fix. I will now close this issue.
