### ISSUE TITLE
Split Jupyter Cell

### ISSUE THREAD

**Issue by zdog234** [microsoft/vscode-jupyter#1446]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description

Hi! This is a mindblowing addition to vscode, and I'm amazed by how much functionality you've already implemented.

That being said, I can't find a way to "split" cells (usually `ctrl + shift + -`). Apologies if I missed an existing issue for this, or if it's already implemented and I just haven't found it.

Thanks!

**Comment by GitProfAn** [comment]
In favor to add this useful function.

**Comment by greazer** [comment]
Split cells has been implemented in VS Code native notebook support (including ctrl+shift+-). Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
