### ISSUE TITLE
Unable to plot using pythreejs and meshplot

### ISSUE THREAD

**Issue by Sentient07** [microsoft/vscode-jupyter#14461]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I am attempting to plot meshes using meshplot as shown here: https://skoch9.github.io/meshplot/tutorial/ and also I've been trying to use pythreejs. Both of them fail. I am unable to understand why they fail. Below is the output of the cell (for meshplot). Same happens for pythreejs as well. I'm using %matplotlib widget. For better context, my vscode runs on a remote server. 

<img width="1117" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/6195312/a6992bdc-c0a9-4a55-8919-1fd9e2c84fb1">

### VS Code Version

1.80.1

### Jupyter Extension Version

v2023.9.1102792234

### Jupyter logs

```shell
UserWarning: 64-bit data types not supported for WebGL data, casting to 32-bit.
  warnings.warn('64-bit data types not supported for WebGL '
```

### Running Jupyter locally or remotely?

Remote

**Comment by Sentient07** [comment]
P.S: I'm guessing that I'm not the first person to face/open this. Apologies if it's a duplicate as i didn't search exhaustively prior to opening this issue. Thanks!

**Comment by Sentient07** [comment]
Hello @DonJayamanne. Hope all is good at your end. Just checking if there could be a solution to this. Thanks!

**Comment by DonJayamanne** [comment]
Sorry I missed this, this works for me without any issues
Please can you update to the latest version of VS Code, you are using an older version. 
Also where is the warning about WebGL message logged? Is that in the Jupyter Ouput panel, VS Code console window, or Jupyter terminal? Please could you share a screen of the error along with teh UI where it is logged

![Screenshot 2023-10-17 at 13 36 58](https://github.com/microsoft/vscode-jupyter/assets/1948812/52fe5d19-cc64-4c27-ba65-6f3cbad9f55b)

**Comment by Sentient07** [comment]
@DonJayamanne Thanks for your response. I can confirm it works at my local end. However, when I'm working on a notebook that runs on a server, it doesn't work. What could be the reason? I can view meshes from other libraries such as trimesh but not ones that use py3js

**Comment by DonJayamanne** [comment]
> However, when I'm working on a notebook that runs on a server, it doesn't work. What could be the reason?

Please can you 
* Select the command `Toggle Developer Tools` 
* Go into the `console` window and see if there are any errors in there (when you run into this issue)

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
