### ISSUE TITLE
Cell timer shows 57 seconds when the processing starts

### ISSUE THREAD

**Issue by thistlillo** [microsoft/vscode-jupyter#14463]
Yesterday, my VSC got updated. As usual, I had to reinstall every extension related to python, including Jupyter.

Right after the update, the timer showing the running time of a cell starts showing 57 seconds. Before the update, it used to start from 0. 

What do I need to verify?

```
Version: 1.83.0 (user setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

I cannot show the version number of the extensions, because today I get "Error while fetching extensions, XHR failed".

As a useless and avoidable personal rant, VSC used to work fine and be pleasant to work with, it should have stayed "simple".

**Comment by DonJayamanne** [comment]
Thank you for filling this issue and sorry you are running into this

are you running the cells against a local kernel or a remote kernel?
Please can you share the logs from the Jupyter output panel when you start and finish running the cell

**Comment by DonJayamanne** [comment]
You can get to the logs using the command ‘Jupyter: Show Output’

**Comment by thistlillo** [comment]
I am sorry but I re-installed everything because I was in a hurry due to close deadlines.

**Comment by DonJayamanne** [comment]
> I am sorry but I re-installed everything because I was in a hurry due to close deadlines.

No need to apologise 
Does this mean you can no longer repro the issue?

**Comment by thistlillo** [comment]
After reinstallation everything is fine.

**Comment by DonJayamanne** [comment]
Let’s close this is issue for now
Thanks
