### ISSUE TITLE
Set jupyter.excludeUserSitePackages true by default

### ISSUE THREAD

**Issue by mdespriee** [microsoft/vscode-jupyter#14464]
This request concern the use of jupyter notebook in vscode.

I just lost hours trying to debug wrong python package loading, until I discovered that I needed to put this setting "jupyter.excludeUserSitePackages": true. I'm using the env variable PYTHONNOUSERSITE=1 everywhere, but since jupyter is started by vscode, it was not using this env variable.

I suggest to make this value the default, because the use of venv/conda envs is now the standard way of doing, and even more with the recent changes on ubuntu 23.04 where the user-site packages are completely managed by apt, and using venv became mandatory.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, and sorry you are running into this.

where are you setting `PYTHONNOUSERSITE=1`, is it setup in your bashprofile or bashrc or the like? If so which one.
Thanks

**Comment by mdespriee** [comment]
I'm mainly using conda environments.
PYTHONNOUSERSITE is set in zshrc. So, I guess that's the cause of my issue (I didn't start vscode from shell).

I still think setting this default will help.

**Comment by DonJayamanne** [comment]
Given that this feature request has been around for over a year and hasn't received an upvotes I'm closing this.
