### ISSUE TITLE
Allow to configure notebooks in AutoReload by default

### ISSUE THREAD

**Issue by FrsECM** [microsoft/vscode-jupyter#14478]
Often i use a notebook in order to test a library that i'm developping.
It's very convenient when we have to display something etc....

The problem is that everytime i need to remember the way to enable autoreload mode in notebook. And everytime i have to search on the internet and do the right copy/past in order to enable this behavior.

It would be great if in the UI it was possible to enable it for the whole notebook :
![image](https://github.com/microsoft/vscode/assets/26071804/1d6b27cf-d386-4f9a-bab0-bd79452ab122)

It's a quite simple but very interesting feature ! 

Thanks a lot !

**Comment by DonJayamanne** [comment]
Thanks for filing thi sissue, 
Are you referring to he `autoreload` magic command?

**Comment by FrsECM** [comment]
Yes exactly, it’s always two lines to add at the beggining of the cell but i have to search it everytime on the web.
Beeing able to set it up by default would improve debogging experience.

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Don Jayamanne ***@***.***>
Envoyé : Wednesday, November 1, 2023 4:49:09 AM
À : microsoft/vscode-jupyter ***@***.***>
Cc : François Ponchon ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/vscode-jupyter] Allow to configure notebooks in AutoReload by default (Issue #14478)


Thanks for filing thi sissue,
Are you referring to he autoreload magic command?

**Comment by DonJayamanne** [comment]
Please use this setting to add the necessary commands that will be sent to the kernel when it starts.
![Screenshot 2023-11-22 at 12 59 34](https://github.com/microsoft/vscode-jupyter/assets/1948812/870b4f0b-2430-48df-980e-908cfe461dbb)
