### ISSUE TITLE
shift+enter no longer runs a cell after pressing esc multiple times

### ISSUE THREAD

**Issue by PierXuY** [microsoft/vscode-jupyter#14474]
Thank you very much for such an excellent product! The overall experience with vscode jupyter is great.     
But at the same time, there are a few things that I think can improve the experience:   

- It is hoped that the same variables can be highlighted across cells.Currently, only the same variable in the same cell can be highlighted.
- When the `Ese` key is pressed to focus on the cell container, if the `Ese` key is pressed again or multiple times, the cell cannot be run using the shortcut keys `Ctrl + Enter` or `Shift + Enter`. This has some impact on the experience. Is it possible to automatically focus when using `Ctrl + Enter` or `Shift + Enter`, so that the current cell can execute normally and avoid inadvertent failure?

Looking forward to a more perfect experience, thank you!

**Comment by amunger** [comment]
The first point should be covered by https://github.com/microsoft/vscode/issues/184259

For the second, that sounds like a bug, but I'm not able to repro - after pressing escape multiple times, I can still run the cell with shift/ctrl+enter. Does the cell still appear focused? Are you on the latest version of vs code?

**Comment by amunger** [comment]
never mind, I can hit it now.

**Comment by PierXuY** [comment]
> never mind, I can hit it now.

Thanks for the reply. I'm using the latest version of vscode.      

After pressing escape multiple times,  the cell still appears focused, but when I press `shift/ctrl+enter`, the cell does not execute normally.  In addition, when I press `shift+enter`, the next cell will be focused but the previous cell is not executed.   

I wonder if other users have similar situations.
