### ISSUE TITLE
How to use my own keyboard shortcuts when coding with notebook?

### ISSUE THREAD

**Issue by honkerjha** [microsoft/vscode-jupyter#1447]
I set some user shortcuts in the VSCode,but when I coding with notebook I found the shortcuts did not work. How to user my own keyboard shortcuts when coding with notebook ?
And, I set '"editor.mouseWheelZoom": true' in 'setting.json',it also doesn't work. How should I do?

**Comment by 0liu** [comment]
Any progress on this? Without keybinding makes this project not much meaningful since people could do almost everything in a browser.

**Comment by rchiodo** [comment]
@0liu this is actually happening soon in the VS code insiders version. See these two items:

https://github.com/microsoft/vscode-jupyter/issues/4438
https://github.com/microsoft/vscode-jupyter/issues/4233

**Comment by rchiodo** [comment]
Closing in favor of https://github.com/microsoft/vscode-jupyter/issues/4376
