### ISSUE TITLE
Answer to #8322

### ISSUE THREAD

**Issue by pgA3D** [microsoft/vscode-jupyter#14494]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Tried something asked by [DonJayamanne](https://github.com/DonJayamanne) in https://github.com/microsoft/vscode-jupyter/issues/8322#issuecomment-1749833560

Issue is blocked so I can't reply. But here is my answer: it works on my side, thanks!
![image](https://github.com/microsoft/vscode-jupyter/assets/46679185/a6177d59-2662-4504-9eb0-03aa90e23341)

### VS Code Version

Version: 1.83.0 (user setup) Commit: e7e037083ff4455cf320e344325dacb480062c3c Date: 2023-10-03T16:12:16.321Z Electron: 25.8.4 ElectronBuildId: 24154031 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Windows_NT x64 10.0.19045

### Jupyter Extension Version

v2023.10.100

### Coding Language and Runtime Version

Python

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment]
> Issue is blocked so I can't reply. 

Sorry, didn't mean that, it got locked automatically.
Thanks for creating this issue and getting back.

> But here is my answer: it works on my side, thanks!

Thank you, thats great news.
Closing this issue
