### ISSUE TITLE
BUG: timeout when connecting to kernel on slow machine

### ISSUE THREAD

**Issue by NickCrews** [microsoft/vscode-jupyter#14515]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

My newish computer broke last week, using that worked fine. But, until my new machine arrives, I'm borrowing my dad's computer with a wimpy little i3. I believe this slowness is causing a timeout error. I'm not sure if you will be able to repro this without a slow computer, but here are my repro steps:

1. Reboot the machine
2. make a new .ipynb
3. run the first cell.
4. I get the message `Failed to connect raw kernel session: Error: Unable to start Kernel '.venv (Python 3.11.6)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.`  Full log output below.

5. Repeat step 3 as many times as I like and I get outcome 4 every time.
6. OK, so I read the logs, and in a new terminal I try `python -m ipykernel_launcher`. This takes like 10 seconds, but it succeeds. Now, if ctrl-c that process and go back to the notebook, now the kernel starts up fine! Perhaps there is some caching or something that happens, so on subsequent runs that command is fast enough to avoid the timeout. If I restart vscode, the notebook kernel continues to work. So it seems like it requires a machine reboot for the cache to get cleared.

I'm not sure how you can repro this. Perhaps go into the `ipykernel_launcher` script and monkeypatch in a `time.sleep(10)` to emulate a slow computer?

### VS Code Version

Version: 1.83.1 (Universal) Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc Date: 2023-10-10T23:46:55.789Z Electron: 25.8.4 ElectronBuildId: 24154031 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Darwin x64 23.0.0

### Jupyter Extension Version

v2023.9.1102792234

### Jupyter logs

```shell
09:18:23.233 [error] waitUntilUsed timed out Error: timeout
    at Timeout.<anonymous> (~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-darwin-x64/out/151.node.js:1:17194)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
09:18:23.234 [error] Disposing kernel process due to an error Error: Unable to start Kernel '.venv (Python 3.11.6)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0b727918fd311c44844600ae430f1976f0f8dc47d07c96db9dab81b44f2e17c1c.~/code/mismo/.venv/python.~/code/mismo/.venv/python.-m#ipykernel_launcher
    > Interpreter Id = ~/code/mismo/.venv/bin/python
    > at ~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-darwin-x64/out/extension.node.js:24:87612
09:18:23.234 [error] 
09:18:23.234 [info] Dispose Kernel process 2233.
09:18:23.260 [error] Kernel Launcher. launch, Class name = ty, completed in 6063ms, has a falsy return value, Arg 1: "~/code/mismo/.venv/python.~/code/mismo/.venv/python.-m#ipykernel_launcher", Arg 2: 6000, Arg 3: "~/code/mismo/docs/examples/patent_deduplication.ipynb", Arg 4: "~/code/mismo/docs/examples", Arg 5: "" Error: Unable to start Kernel '.venv (Python 3.11.6)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0b727918fd311c44844600ae430f1976f0f8dc47d07c96db9dab81b44f2e17c1c.~/code/mismo/.venv/python.~/code/mismo/.venv/python.-m#ipykernel_launcher
    > Interpreter Id = ~/code/mismo/.venv/bin/python
    > at ~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-darwin-x64/out/extension.node.js:24:87612
09:18:23.261 [error] Failed to connect raw kernel session: Error: Unable to start Kernel '.venv (Python 3.11.6)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
09:18:23.261 [error] Failed to connect raw kernel session: Error: Unable to start Kernel '.venv (Python 3.11.6)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
09:18:23.261 [warn] Error occurred while trying to start the kernel, options.disableUI=false Error: Unable to start Kernel '.venv (Python 3.11.6)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0b727918fd311c44844600ae430f1976f0f8dc47d07c96db9dab81b44f2e17c1c.~/code/mismo/.venv/python.~/code/mismo/.venv/python.-m#ipykernel_launcher
    > Interpreter Id = ~/code/mismo/.venv/bin/python
    > at ~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-darwin-x64/out/extension.node.js:24:87612
09:18:23.261 [warn] Kernel Error, context = start Error: Unable to start Kernel '.venv (Python 3.11.6)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0b727918fd311c44844600ae430f1976f0f8dc47d07c96db9dab81b44f2e17c1c.~/code/mismo/.venv/python.~/code/mismo/.venv/python.-m#ipykernel_launcher
    > Interpreter Id = ~/code/mismo/.venv/bin/python
    > at ~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-darwin-x64/out/extension.node.js:24:87612
09:18:23.265 [info] Process Execution: ~/code/mismo/.venv/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
09:18:23.491 [info] Dispose Kernel '~/code/mismo/docs/examples/patent_deduplication.ipynb' associated with '~/code/mismo/docs/examples/patent_deduplication.ipynb'
09:18:23.502 [error] Error in execution Error: Unable to start Kernel '.venv (Python 3.11.6)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0b727918fd311c44844600ae430f1976f0f8dc47d07c96db9dab81b44f2e17c1c.~/code/mismo/.venv/python.~/code/mismo/.venv/python.-m#ipykernel_launcher
    > Interpreter Id = ~/code/mismo/.venv/bin/python
    > at ~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-darwin-x64/out/extension.node.js:24:87612
09:18:23.502 [error] Error in execution (get message for cell) Error: Unable to start Kernel '.venv (Python 3.11.6)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0b727918fd311c44844600ae430f1976f0f8dc47d07c96db9dab81b44f2e17c1c.~/code/mismo/.venv/python.~/code/mismo/.venv/python.-m#ipykernel_launcher
    > Interpreter Id = ~/code/mismo/.venv/bin/python
    > at ~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-darwin-x64/out/extension.node.js:24:87612
09:18:23.542 [info] End cell 0 execution @ undefined, started @ undefined, elapsed time = 0s
```

### Coding Language and Runtime Version

python 3.11.6

### Anaconda Version (if applicable)

NA

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and sorry you are running into this
I have seen other users run into similar issues, and its caused by some other software blocking these ports,
Do you have some suck software on your mac?


Optionally, please can you launch Jupyter Lab/Notebook in your terminal, and let me know if that works.
`python -m jupyter notebook`
Once done, open a notebook in the notebook UI and try running a cell.

**Comment by DonJayamanne** [comment]
> This takes like 10 seconds, but it succeeds. Now, if ctrl-c that process and go back to the notebook, now the kernel starts up fine! Perhaps there is some caching or something that happens, so on subsequent runs that command is fast enough to avoid the timeout

Looks like an issue with the Python package itself, hence the reques+ to try and start Jupyter Notebook outside vscode in the terminal

**Comment by NickCrews** [comment]
Thanks for the help!

> Do you have some suck software on your mac?

The OS-installed stuff like `photoanalysisd` that I don't realy have control over, but it only takes 25% of a CPU at max (out of 4 cores). This might just run at startup of my machine, I could wait 30 minutes after boot and maybe that daemon will calmn down by then and I could retry if you think that's useful?

> python -m jupyter notebook

That works, it takes like 10 seconds. Then I can open the given URL in chrome and it works. If I paste that as an "existing server" in the vscode jupyter UI, then when I run the first cell, it takes like 15 seconds to actually connect, but it does successfully.

Let me know what else I can do.

**Comment by DonJayamanne** [comment]
@NickCrews 
I think i may have a solution for this.
Please can you try the solution posted here https://github.com/microsoft/vscode-jupyter/issues/14519#issuecomment-1778289425
Basically its a custom VSIX (custom build of the Jupyter extension with a potential fix)
Let me know how that goes
Lets continue the discussion in that issue https://github.com/microsoft/vscode-jupyter/issues/14519#issuecomment-1778289425
