### ISSUE TITLE
Jupyter - Customize output fonts & style

### ISSUE THREAD

**Issue by MiracleXYZ** [microsoft/vscode-jupyter#1451]
![image](https://user-images.githubusercontent.com/30370926/65386592-58f46c80-dd70-11e9-9743-e38c2349a8fa.png)

It would be pretty helpful if we could customize the font & style of cell output.
Especially in Chinese system - it's using SimSun which doesn't look good enough.

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/123149
