### ISSUE TITLE
enable a scroll bar to show long file path

### ISSUE THREAD

**Issue by Borease** [microsoft/vscode-jupyter#14521]
Hi, VS code jupyter team.

When I using the jupyter notebook in the vs code editor, the prompted auto-filled file path cannot be fully displayed if the file path is too long. Is it possible to add a scroll bar in the auto fill windows, so that we can scroll to see the full contents?

Below is the screenshot to illustrate what I mean. The black circle shows the long file path that is hidden. Is it possible to add a scroll bar at the bottom so that people can scroll and see the full path? Thank you!

![screenshot 2023-10-17 185155](https://github.com/microsoft/vscode-jupyter/assets/29754901/3895617b-07db-43b5-9db3-8fd2f17dfd6f)

**Comment by roblourens** [comment]
These suggestions might be coming from an extension, is that possible?
