### ISSUE TITLE
VSCode gets killed (15) when opening .ipynb file

### ISSUE THREAD

**Issue by gernophil** [microsoft/vscode-jupyter#14531]
## Environment data

-   VS Code version: 1.83.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.9.1102792234
-   Python Extension version (available under the Extensions sidebar): v2023.18.0
-   OS (Windows | Mac | Linux distro) and version: macOS 14.0
-   Python and/or Anaconda version: Python 3.8-3.11 (python.org); Conda 23.5.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): unrelated
-   Jupyter server running: N/A

## Expected behaviour

open .ipynb file in editor

## Actual behaviour

VSCode gets killed (15)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. create an .ipynb file and open it.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

Hey everyone, I am trying to make sense of this and also found some reports of killed (15) for VSCode, but none of them matches my issue. Starting from today, everytime I open a .ipynb file, VSCcode crashes within seconds. I am on Mac and completely removed the VSCode app and the folders `~/.vscode` and `~/Library/Application Support/Code` and reinstalled everything, but nothing changes this. It started today and there seem to have been update for both th Jupyter and the Python plugin. I tried to revert Jupyter (haven't reverted Python yet), but it didn't help. Could this still be related?

![Bildschirmfoto 2023-10-19 um 12 40 44](https://github.com/microsoft/vscode-jupyter/assets/19264855/96d132f0-5a71-41a3-9796-3da66b5e1687)

**Comment by jupitersh** [comment]
the same for me

**Comment by DonJayamanne** [comment]
@jupitersh are you connected to a remote server over SSH or the like?
Please can you also share the same information and try what I've suggested thanks

**Comment by jupitersh** [comment]
> @jupitersh are you connected to a remote server over SSH or the like? Please can you also share the same information and try what I've suggested thanks

Here is the screenshot when I connected to a remote server over SSH and opened a ipynb file:
<img width="1120" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/55310213/ada120b7-be17-49a0-b836-2668ed739a4d">


Here is the screenshot when I opened a ipynb file on my local computer:
<img width="362" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/55310213/c00e1f11-7315-4aea-bb59-a128579da8e2">
