### ISSUE TITLE
It would be nice to see a df.describe() in the data viewer

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1453]
df.describe() does this:

![image](https://user-images.githubusercontent.com/19672699/56448126-9c2e4900-62c1-11e9-85f6-7e98e71f09b3.png)

This would be super easy to add as extra rows into the data viewer.

**Comment by IanMatthewHuff** [comment]
@rchiodo This was old and didn't seem upvoted, so closing. Just ping if you want me to reactivate to keep it in the mix for a data viewer enhancement.
