### ISSUE TITLE
vscode (both stable and insiders version) in Ubuntu 20.04 crashes when opening jupyter notebooks

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/vscode-jupyter#14536]
## But if I disable the `jupyter` extensions and then re-luanch vscode then it does not crash

And for the jupyter` extensions - I have tried uninstalling-reinstall, And also tried both the "release" and "pre-released" versions. 

But facing the same issue as soon as I enable this extension.

===============

OS in my Machine - Ubuntu 20.04.6 LTS

Stable VsCode Version
Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:45:31.402Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-87-generic

--------

Version: 1.84.0-insider
Commit: c42f8961f9ba803175ccbb8260e8d70d561f8bee
Date: 2023-10-19T05:34:17.626Z
Electron: 25.9.1
ElectronBuildId: 24472542
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-87-generic

**Comment by DonJayamanne** [comment]
Sorry you are running into this issue.
Please revert pylance to version `2023.10.20` to get around this issue.
https://github.com/microsoft/vscode-jupyter/issues/14529
