### ISSUE TITLE
Test Tensorboard functionality in Python extension

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#14548]
Refs: #14472

- [x] anyOS @karrtikr 
- [x] anyOS @rebornix 
- [x] anyOS @luabud 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2314548%0A%0A&assignees=DonJayamanne)

---

# Test 1
* Install latest version of VS Code Insiders
* Install latest pre-release version of Python Extension 
* Install Python and setup a virtual environment in your workspace (required for installation of tensorboad)
* Open a Python file
* Select the command `Python: Launch Tensorboard`
* [ ] Verify you are prompted to install the Tensorboard extension
* Opon installing the tensorboard extension, verify selecting the command `Python: Launch Tensorboard` will now work
    * What does it mean by `will now work`?
    * You will be prompted to install tensorboard
    * Tensoboard UI will be launched (if tensorboard has already been installed)

# Test 2
* Install latest version of VS Code Insiders
* Install latest pre-release version of Python Extension 
* Install Python and setup a virtual environment in your workspace (required for installation of tensorboad)
* Open a Python file
* Write the following code in the file 
```python
import tensorboard
```
* [ ] Verify the code lense `Launch Tensorboard Session` is displayed
* Click this code lense
* [ ] Verify you are prompted to install the Tensorboard extension

**Comment by luabud** [comment]
You might need to set `"python.experiments.optInto": ["pythonRecommendTensorboardExt"],` to the User settings.json in case you're unlucky like me and fell in the 10% pre-release bucket that is in the control group

I got the notification as expected:
![image](https://github.com/microsoft/vscode-jupyter/assets/45497113/d03597b7-d04e-46a9-9253-9cdbd8de5d43)

However clicking on the install button didn't do anything (https://github.com/microsoft/vscode-jupyter/issues/14557)

once I manually installed it, I still saw a notification coming from the Python extension (I was expecting it to be coming from the Tensorboard extension, but looking at the logs this seems to be expected)
![image](https://github.com/microsoft/vscode-jupyter/assets/45497113/11366cb3-5139-4b45-818f-4ec4e4bf91f6)

![image](https://github.com/microsoft/vscode-jupyter/assets/45497113/fb83c055-9bd3-4a22-bb1d-4473ded9657b)

Tensorboard was launched as expected:
![image](https://github.com/microsoft/vscode-jupyter/assets/45497113/7faadd22-fe7d-45d2-9569-22de05a5db9b)


Code lenses also showed up successfully (and it prompted to install the extension when I didn't have the Tensorboard ext installed):
![image](https://github.com/microsoft/vscode-jupyter/assets/45497113/217ac9f4-de82-446e-9c25-96014ccb8f31)
