### ISSUE TITLE
VSCode Insiders crashes when I try to open a Jupyter notebook. (reason:'killed', code:'15')

### ISSUE THREAD

**Issue by shawn-weibyapps** [microsoft/vscode-jupyter#14540]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I typically open two windows simultaneously: one connected to the remote server project and the other for the local project. However, when I open Jupyter Notebook locally, both windows tend to crash and display the following error message. This issue occurs approximately 80% of the time, and while reopening is a workaround, but it is really annoying!
<img width="222" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/144085540/bec669ca-fa8a-4a20-8926-2709f492afad">

* About Vscode Insiders
```
Version: 1.84.0-insider (Universal)
Commit: c42f8961f9ba803175ccbb8260e8d70d561f8bee
Date: 2023-10-19T05:37:12.504Z
Electron: 25.9.1
ElectronBuildId: 24472542
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.5.0
```
* About My Laptop
```
2020 M1 13 inch MacBook Pro
mac OS: Ventura 13.4.1
```
### VS Code Version

1.84.0-insider (Universal)

### Jupyter Extension Version

 v2023.9.1102792234

### Coding Language and Runtime Version

Python v3.9.6

### Running Jupyter locally or remotely?

Local

**Comment by yermandy** [comment]
The same happens to me! When I open (click on) `.ipynb` file via SSH connection, the connection to the SSH server drops immediately

**Comment by Messjer** [comment]
This also happens to me. First I thought it was an ssh issue but even locally it happens.

**Comment by mayug** [comment]
I have the same issue. When I connect to the remote and open any .ipynb, it shows setting up kernels and then disconnects. This happens only on one server. On the other server, it still works fine.

**Comment by RealChenZhang** [comment]
This also happens to me.

**Comment by jabbera** [comment]
This is fixed with the most current release of pylance: https://github.com/microsoft/pylance-release/issues/4983
