### ISSUE TITLE
Display execution time on each cell

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1454]
Referenced in microsoft/vscode-python#5662 were two good ideas for adding execution time to each cell:

First idea  -
> The extension for Jupyter solves it like this: jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/execute_time/readme.html. A single line with a timestamp and the execution time in milliseconds below every executed cell.

> But I guess that would not look as pretty in vscode as it would clutter the window. Maybe the execution time could be displayed on hover: Either over the cell or over a designated area like a button? The execution time could also be displayed in the status bar at the very bottom. Or maybe the execution time is displayed after clicking a button, like you suggested? Or maybe there could be a button at the very top, that globally enables and disables the display of the execution time below each cell.

Second idea -
> How about adding a little info icon to every cell by default next to the "Remove cell" and "Go to code" buttons which on hover displays the cells execution time and when it started running. Something like this.

![image](https://user-images.githubusercontent.com/30958850/61993746-3b54a080-b068-11e9-8795-6eb4f075e49b.png)

**Comment by janosh** [comment]
Does this no longer being parked mean it's coming soon? Would be great!

**Comment by rchiodo** [comment]
Actually this is already available in the insiders build.

![image](https://user-images.githubusercontent.com/19672699/104354449-0afffc80-54be-11eb-99ef-8ef71b336363.png)

That's likely where it will be when we start using the VS code API in stable.

**Comment by janosh** [comment]
@rchiodo Cool! Does this apply also to the interactive window?

**Comment by rchiodo** [comment]
No, sorry not at the moment. Hopefully when/if we switch that to the new API too.

**Comment by janosh** [comment]
The new notebook API? Is there a tracking issue for that?

**Comment by rchiodo** [comment]
Yes there is:
https://github.com/microsoft/vscode-jupyter/issues/1388

**Comment by andreimargeloiu** [comment]
+1
