### ISSUE TITLE
Install tensorboard action is not doing anything

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-jupyter#14557]
Testing #14548

Triggering the Python: Launch Tensorboard command is showing the "install tensoboard extension" as expected. However, clicking on the install command seems to be failing silently:

 
![tensorboardnotinstalling](https://github.com/microsoft/vscode-jupyter/assets/45497113/0b508ed8-b2c8-4452-8905-ca2bc44ff9ef)

**Comment by luabud** [comment]
might be worth calling out that I'm in the control group, and had to opt into the experiment by setting 
```
 `"python.experiments.optInto": ["pythonRecommendTensorboardExt"],`
```

**Comment by luabud** [comment]
![image](https://github.com/microsoft/vscode-jupyter/assets/45497113/05fa7db9-e59a-4f7d-ad55-34231cd9cf46)

![image](https://github.com/microsoft/vscode-jupyter/assets/45497113/fec46e7c-17e7-49ba-a4a2-abd517234156)

**Comment by DonJayamanne** [comment]
I am 99% certain this is  because the release version of the extension has not been published
Will chat with team and check whether we should instead just publish the extension

**Comment by DonJayamanne** [comment]
@luabud Please can you try this once again.
Please ensure you uninstall the tensorboard extension

**Comment by luabud** [comment]
With the new update the Tensorboard extension is installed as expected! The woird thing is that now both commands are showing up:
![image](https://github.com/microsoft/vscode-jupyter/assets/45497113/39d450a3-95cc-4183-9e30-009bfe13a023)

Running the one from the Python extension fails:

![image](https://github.com/microsoft/vscode-jupyter/assets/45497113/63919897-9344-46bb-8b78-c14c2e1cc1c1)

After it's run, it seems to disappear and only the Tensorboard one shows up:
![image](https://github.com/microsoft/vscode-jupyter/assets/45497113/6dc9f70e-7d5f-435c-9b5a-37cfa8d1ba89)

**Comment by luabud** [comment]
I'll close this and mark as verified since the original issue has been fixed. Created https://github.com/microsoft/vscode-jupyter/issues/14586 to address the dupe commands.
