### ISSUE TITLE
Linux: create python environment from kernel picker does not install missing pip

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#14567]
## Environment data

-   VS Code version: 1.84.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): 2023.9.1102792234
-   Python Extension version (available under the Extensions sidebar): 2023.18.0
-   OS (Windows | Mac | Linux distro) and version: macOS

On a vanilla Ubuntu machine, when we run `Python: Create Environment` command, it can install missing `pip` package first and then install `requirements.txt`. However when we try to use the default Python environment to install missing ipykernel, or use the same command to create new Python Environment from the Kernel Picker, it doesn't install `pip` for us.

Starting the issue from our repo as I'm not sure if we are not passing in the right arguments to the command.

**Comment by DonJayamanne** [comment]
> Starting the issue from our repo as I'm not sure if we are not passing in the right arguments to the command.

Nope, this isn't us.

**Comment by DonJayamanne** [comment]
@rebornix where did you install pip from.
From what I recall @brettcannon mentioned that all Python distros except for Linux flavours do not have Pip.

**Comment by DonJayamanne** [comment]
Aren't you downloading python for mac from here 
https://www.python.org/downloads/macos/

**Comment by rebornix** [comment]
@DonJayamanne Linux distros' Python doesn't come with pip, but Create Environment command can handle that now, except when running from the Kernel Picker.

**Comment by DonJayamanne** [comment]
@karthiknadig @karrtikr 
Do we need to add any special arguments to ensure `pip` is installed when creating a new environment via the command

**Comment by rebornix** [comment]
I found this https://github.com/microsoft/vscode-python/issues/17975 in the meanwhile.

**Comment by DonJayamanne** [comment]
Transferred that to this repo, as package installation is done in this ext.

**Comment by karthiknadig** [comment]
In the logs for python you should see what it is trying to do. We do one of two things:
<img width="466" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/3840081/46adb4b3-d21d-4c2c-bbba-d3189b8a0421">

Note that this can fail if python itself isn't properly installed. Like missing distutils.

**Comment by brettcannon** [comment]
And this only happens in Debian-based Linux distros like Ubuntu when you get your Python from the distro itself or from the Deadsnakes PPA (e.g. pyenv doesn't have this problem).

**Comment by rebornix** [comment]
Thank you both for the details and now I understand the situation better: when users try to use the distro python interpreter to run code directly, it doesn't have pip and it might very likely require sudo to install pip. To improve this experience, one solution can be asking users if they want to use a venv other than only showing an error notification.

**Comment by DonJayamanne** [comment]
Sounds like this is something that needs to be addressed in Python extension itself, is that right @karthiknadig @brettcannon ?

**Comment by brettcannon** [comment]
> Sounds like this is something that needs to be addressed in Python extension itself, is that right @karthiknadig @brettcannon ?

It already is to the best of our abilities (to the point that I created https://pypi.org/project/microvenv/ for this specific issue). If you use the "Create Environment" command we bootstrap in pip on machines that are missing it. But unfortunately that can still fail if key things are still left out of the person's Python install on certain Python versions (i.e. distutils missing on Python <=3.9 versions due to pip expecting it for backwards-compatibility; I've [asked the them to clarify the error message](https://github.com/pypa/pip/issues/12253)). Unfortunately Debian-derived distros flat-out suck for Python development due to this and Debian won't change things (the Python steering council, which I'm on, asked the Debian tech leads to change how they package up Python and they politely said no).

**Comment by DonJayamanne** [comment]
Closing as an upsream issue, basically there's not much we can do in the Jupyter extension as this is already handled (to the best of their abilities) in Python extension.
