### ISSUE TITLE
Python commands to launch tensorboard is still showing up even when the Tensorboard extension is installed 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-jupyter#14586]
With the new update the Tensorboard extension is installed as expected! The weird thing is that now both commands are showing up:
![image](https://github.com/microsoft/vscode-jupyter/assets/45497113/39d450a3-95cc-4183-9e30-009bfe13a023)

Running the one from the Python extension fails:

![image](https://github.com/microsoft/vscode-jupyter/assets/45497113/63919897-9344-46bb-8b78-c14c2e1cc1c1)

After it's run, it seems to disappear and only the Tensorboard one shows up:
![image](https://github.com/microsoft/vscode-jupyter/assets/45497113/6dc9f70e-7d5f-435c-9b5a-37cfa8d1ba89)

_Originally posted by @luabud in https://github.com/microsoft/vscode-jupyter/issues/14557#issuecomment-1783252926_

**Comment by DonJayamanne** [comment]
Unfortunately not much we can do here, as both extensions contribute this.
Once Python extension removes this command this should not be an issue.
Closing as not planned
