### ISSUE TITLE
Variable explorer should update all at once

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1460]
There has been some feedback about the variable explorer being slow.

The variable explorer isn't really slow, it's just made to be async and interruptable. 

We could change this such that we compute all the variables the way we do now, but then don't refresh the screen (or put loading) until we have all of the data.

**Comment by IanMatthewHuff** [comment]
Doesn't seem worth keeping this old bug around for variable view perf unless it's getting votes / new customer complaints.
