### ISSUE TITLE
Select Multiple Cells and Copy/Paste

### ISSUE THREAD

**Issue by tobias-fyi** [microsoft/vscode-jupyter#1461]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description

One feature I've found myself wanting is the ability to select multiple cells to move or copy/paste them as a group (into the same notebook or into a different one).

As far as I can tell, this functionality has not been implemented in the native Code notebook editor. If it has been and I'm not seeing it, I apologize.

The native notebook editor is a gamechanger for me. Thank you so much for all of your hard work!

**Comment by madSec** [comment]
Hi, just started using VSCode notebooks instead of Jupyter notebooks and found it actually works pretty well except for this missing feature of copying/pasting/moving multiple or even single cells. Hopefully this feature will be added soon.

**Comment by s4ul0bk** [comment]
I'm trying migrate from jupyter to vscode, but some features on nbextensions doesn't existing, losing time to do the same operation. This multiple cells selection is an example of this missing feature.

**Comment by aaron-dunigan-atlee** [comment]
Until this feature is implemented, a workaround is to view the notebook as plain text (right click in explorer panel, Open With..., and select Text Editor).  Copy and paste the cell objects as desired, then close the text tab and re-open as notebook.  Not elegant but it works.

**Comment by ymentha14** [comment]
As a suggestion, this [extension](https://www.npmjs.com/package/@axlair/jupyterlab_vim) working on jupyter lab allows you to select many cells by holding down the shift key and playing with J and K keys following the vim convention: you can then cut/copy it at your ease.

This is one of the very few feature of this jlab extension that is not fully reproducible on vscode yet, would be awesome to see it coming on code!

**Comment by claudiaregio** [comment]
This feature is currently available in [VS Code Insiders](https://code.visualstudio.com/insiders/) today! Try it out and let us know your thoughts, this will be moving to VS Code Stable when ready :)
