### ISSUE TITLE
2 Python processes started per kernel when running a notebook

### ISSUE THREAD

**Issue by pongwoo** [microsoft/vscode-jupyter#1462]
Hi all,

I have set up a jupyter notebook with pySpark. When I connect to the jupyter server using VS Code Python interactive window, it spins up 2 applications. While it is simple to kill one of them, I wonder if there is a setting that I could change.

Thanks in advance.
Pong

**Comment by DonJayamanne** [comment]
Closing as we don't start restart kernels anymore.
