### ISSUE TITLE
When exporting a notebook to Python, the default filename of the script should mirror the notebook filename

### ISSUE THREAD

**Issue by pauloneves** [microsoft/vscode-jupyter#1463]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

We should be able to automatically export a converted python script while saving a Jupyter Notebook. It would finally save the problem of versioning notebook files. 

This feature would allow us to have the exported python script under version control and the notebook in .gitigore.

## Description

I believe the feature request above should be implemented in 3 steps:

When pressed, the icon "Convert and save to a python script" asks for a filename. The save dialog should automatically fill the filename based in the notebook name, just changing the extension from `.ipynb` to `.py`. 

The Convert and Save could be called as an extension method in VSCode. It should be able to save with the default name, without user interaction.

A configuration option should be created to automatically export the file when the notebook is saved.

**Comment by burkeholland** [comment]
Found in Golden Scenario. Current format is the first few lines of the Notebook which ends up being something like..

`# % % markdown`

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/11453
