### ISSUE TITLE
Notebooks still lacking cell ids

### ISSUE THREAD

**Issue by SuperMB** [microsoft/vscode-jupyter#14652]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

In Jupyter notebook in VS Code, creating a new cell does not create an "id" in the json for the cell. This was happening previously if I set the nbformat to 4 and nbformat_minor to 5. However, now, the "id" field is not being created for cells. Our extension relies heavily on the id of cells, so this is currently a show stopper for us. Since this was addressed previously, I am hoping it isn't a large fix. Similar issues/previous fix: https://github.com/microsoft/vscode/issues/134834
![Extension Development Host  TestCode ipynb - NeelShare (Workspace) - Visual Studio Code 11_1_2023 8_49_44 PM](https://github.com/microsoft/vscode-jupyter/assets/5454335/352c449f-5793-4f25-9b94-b936b62f18e1)

### VS Code Version

1.84

### Jupyter Extension Version

v2023.10.1003070148

### Jupyter logs

```shell
Visual Studio Code (1.84.0, undefined, desktop)
Jupyter Extension Version: 2023.10.1003070148.
Python Extension Version: 2023.20.0.
Platform: win32 (x64).
Multiple Workspace folders opened x:\Code\GitHub\ArcticFoxRepos\Tests\NeelShare\Automations, x:\Code\GitHub\ArcticFoxRepos\Tests\NeelShare\Code, x:\Code\GitHub\ArcticFoxRepos\Tests\NeelShare\Projects\Build
20:46:42.519 [info] Start refreshing Kernel Picker (1698896802519)
20:46:42.524 [info] Using Pylance
20:46:46.029 [info] End refreshing Kernel Picker (1698896802519)
20:46:47.756 [warn] Failed to get activated env vars for c:\Python310\python.exe in 3402ms
20:46:47.770 [info] Process Execution: c:\Python310\python.exe -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
20:46:47.877 [info] Process Execution: c:\Python310\python.exe -m pip list
20:46:48.837 [warn] No interpreter for Pylance for Notebook URI "x:\Code\GitHub\ArcticFoxRepos\Tests\NeelShare\Code\TestCode.ipynb"
20:48:10.714 [info] Start refreshing Interpreter Kernel Picker
20:48:10.714 [info] Start refreshing Kernel Picker (1698896890714)
20:48:12.281 [info] End refreshing Kernel Picker (1698896890714)
```

### Coding Language and Runtime Version

Python 3.10.5

### Language Extension Version (if applicable)

Python Extension: v2023.20.0

### Running Jupyter locally or remotely?

Local

**Comment by SuperMB** [comment]
Quick note, I had the issue on my desktop, my Surface was running fine. Surface VS Code updated to VS Code 1.84 and starting having the issue of not adding IDs to cells. I reverted VS Code to 1.83.1. Now, the jupyter notebook is adding cell IDs as expected. So, it seems like an issue with VS Code 1.84. Hope that is helpful!

**Comment by SuperMB** [comment]
@DonJayamanne Just trying to keep this on your radar. Every time us, or anyone using our software, launches VSCode, they have to reinstall 1.83.1 because 1.84.X still has this issue... Really causing a mess.

**Comment by DonJayamanne** [comment]
This should be fixed in the latest VS COde insiders version.
Please let me know if it works.
If it doesn't please feel free to re-open this issue or feel free to file a new one.
