### ISSUE TITLE
Support Raw Cell for jupyter notebook

### ISSUE THREAD

**Issue by wangys96** [microsoft/vscode-jupyter#1466]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description

Currently vscode-python supports only Code mode and Markdown mode for cells, while Raw cell is not allowed, and the Raw cells in other ipynb files are renderd as blank chunk.

**Comment by Dom4n** [comment]
+1 for this issue, raw cells are used by great number of devs
I use them to quickly disable some code (it will not run as the cell is just text now), markdown will render badly in that case.

**Comment by namanarora97** [comment]
The issue still exists. I spent a long time figuring out why some of the cells in my assignment that my professor gave me don't show up in VS code at all. Is there no plan for this to be fixed? I have to move away from VS Code just because of this :(

**Comment by NelisW** [comment]
thanks for the trouble with notebooks in VS Code.
I was really looking forward to editing Jupyter notebooks in my favourite editor!
But alas, no raw cells :-( 
so back to clunky jupyter editor.

**Comment by joyceerhl** [comment]
Apologies for the trouble. This issue is on our backlog. Our team is working hard to replatform the Jupyter extension onto VS Code's notebooks API, and we intend to address this issue afterwards.

**Comment by NelisW** [comment]
thanks!!!!!!

**Comment by renogomez** [comment]
When I execute raw cells the kernel gets blocked. Anyone having similar issues?

**Comment by rchiodo** [comment]
Executing raw cells should behave the same as Jupyter

**Comment by greazer** [comment]
This PR should alleviate at least some of the trouble with raw cells. https://github.com/microsoft/vscode-jupyter/pull/6958. It is available in VS Code Insiders v1.60+. I'm going to close this issue. Please open new, more specific issues related to raw cells. Thank you!!
