### ISSUE TITLE
Unable to use Debuger in VSC with AML remote extension

### ISSUE THREAD

**Issue by soferreira** [microsoft/vscode-jupyter#14662]
## Environment data

-   VS Code version: 1.84
-   Jupyter Extension version (available under the Extensions sidebar): v2023.10.1003070148
-   Python Extension version (available under the Extensions sidebar): v2023.20.0 
-   OS (Windows | Mac | Linux distro) and version: w11
-   Python and/or Anaconda version: python 3.10.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Remote 
-  Azure Machine Learning - Remote v0.36.0
-  Azure Machine Learning v0.38.0

## Expected behaviour

I am currently connected to my Azure ML compute instance in my VS Code. I am trying to debug my python script from VS Code.
Debugger should start and stop if there are breakpoints in the code.

## Actual behaviour

There is an error in the OUTPUT terminal and all breakpoints are ignored. Nonetheless, the code is executed.

Error message:

2023-11-02 14:48:36.187 [info] [Error - 2:48:36 PM] Request textDocument/codeAction failed.
2023-11-02 14:48:36.187 [info] Message: Request textDocument/codeAction failed with message: Debug Failure. Unable to find notebook URI for vscode-notebook-cell://XXXXXX/home/azureuser/cloudfiles/code/Users/soferreira/Untitled.ipynb#XXXXX
Code: -32603

## Steps to reproduce:

1. Connect VSC to Azure ML compute instance
1. Open one of the .ipynb file
1. Insert breakpoints
1. Click "Debug Cell"

Note: This issue applies to .ipynb files. Debuger is working fine with .py files

**Comment by soferreira** [comment]
@shsuman

**Comment by DonJayamanne** [comment]
@shawnzhu Please can you shed some light on this. Does debugging work in AzML (has it worked).
Trying to fiture out whether this is recent bug or it has never worked

@soferreira has the file untitled.ipynb been saved to disk

**Comment by shsuman** [comment]
@DonJayamanne There was a debugging problem with ipykernel v6.8.0 but that was fixed some time ago by Azure ML. https://github.com/microsoft/vscode-tools-for-ai/issues/1970

@DonJayamanne I tested the debugging and it is working with all the latest version of the extensions

**Comment by shsuman** [comment]
![image](https://github.com/microsoft/vscode-jupyter/assets/44413557/6b49bb40-9c95-470a-922d-d5e0c8b5787b)

**Comment by DonJayamanne** [comment]
6.8.0 is a very old version
