### ISSUE TITLE
Cannot debug with autotime, pykernel setup required for this feature

### ISSUE THREAD

**Issue by FatjonZOGAJ** [microsoft/vscode-jupyter#14664]
## Environment data

-   VS Code version: Version: 1.83.1 (Universal)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
-   Jupyter Extension version (available under the Extensions sidebar): v2023.10.1003070148
-   Python Extension version (available under the Extensions sidebar): v2023.20.0
-   OS (Windows | Mac | Linux distro) and version: OS: Darwin arm64 22.6.0
-   Python and/or Anaconda version: conda 23.9.0, python 3.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local (through VSCode Remote Development)

## Expected behaviour

Being able to debug

## Actual behaviour

Get an error with pykernel setup required for this feature even though I have it

## Steps to reproduce:

Appears randomly and then stays. Setup new conda environment, install all packages -> works for a while. Down the road, the jupyter notebook by default chooses another kernel at which point even selecting the new one doesn't work anymore.

I have tried and browsed everything online, getting very frustrated about this and based on what I've seen I'm not the only one. 

**I think I boiled it down to `%load_ext autotime`, commenting that out makes it work.** 

This also seems highly related, but didn't fix the issue https://stackoverflow.com/questions/75729130/vscode-debugger-warning-on-frozen-modules

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
```

</p>
</details>

**Comment by amunger** [comment]
related - https://github.com/microsoft/vscode-jupyter/issues/10933 autotime also breaks the variables view, so it makes sense that debugging would have issues as well

**Comment by amunger** [comment]
debugging works for me with auto time, I was able to break on the print(1) line below and continue to success.

```
%load_ext autotime

print(1)  
```
