### ISSUE TITLE
Explore enabling Non-Python kernel auto complete

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#14672]
We might already have issues open for this request but I couldn't find that yet.

Notes:
* [x] Feature will be behind an experiment
* [ ] Experiment will be rolled out to all insiders
* [x] We will need to ensure completion requests to the kernel complete quickly, so as to prevent slowing down the kernel 
* [ ] Python kernel completion cannot be disabled (it is on by default)
* [x] Python kernel completion does not support displaying documentation (resolveCompletionItem not implemeneted)
* [x] Kernel completions will be enabled by default
* [x] Configurable non-python kernel completion trigger characters
* [x] Setting to run off non-python kernel completions
* [ ] Merge Python and non-python kernel completions into the same settings (turn off and trigger characters)
This will need to be done after the experiment, once were comfortable enabling this new feature (non-python kernels) for all
* [ ] Leave experiment for at least 2 months.

**Comment by Philonoist** [comment]
Yes please! As a concrete example, I would like to use Rust jupyter kernel (https://github.com/evcxr/evcxr/blob/main/evcxr_jupyter/README.md)
with completions. (rust-analyzer lsp integration exists both in plain jupyter lab, and in vscode).
If I can help here, let me know.

**Comment by DonJayamanne** [comment]
> t not seeing any requests for it to the kernel.

@maxandersen What version of VS Code and Jupyter extension are you using?
This should be enabled by default in VS Code Insiders and the Pre-releaase version of the Jupyter extension (I think i mentioned that in a previous comment)

> how does one trigger it?

This gets triggered via the characters `. @ #` in Java.
You can customize these trigger characters via the setting `jupyter.completionTriggerCharacters`

**Comment by maxandersen** [comment]
I'm running latest vscode insiders (Version: 1.85.0-insider (Universal)
Commit: 055458feab40fc308fc6d70b185068138c8cf8eb
Date: 2023-11-27T05:36:15.984Z (1 day ago) and the pre-release of jupyter extension v2023.11.1003331000.

I'll try it out some more and see whats going on.

**Comment by DonJayamanne** [comment]
Please use the keys ctrl+space to force completions to show up
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by maxandersen** [comment]
@DonJayamanne got it working. not sure what made the difference. I did say yes to install python and java extension this time when starting up. 

can it be that the python extension matching runtime needs installing for completion to work ? it seems weird as i was executing code via the kernel without following those popup "recommendations/suggestions" on what to install.

**Comment by DonJayamanne** [comment]
This has been completed in the latest version of Jupyter extension.
See follow settings
![Screenshot 2024-04-03 at 07 54 35](https://github.com/microsoft/vscode-jupyter/assets/1948812/af72cb72-5839-4858-9dde-13ce126c3889)
