### ISSUE TITLE
'# MAGIC' comment for files coming from Databricks isn't included in Settings > Jupyter > Magic Commands As Comments

### ISSUE THREAD

**Issue by Mertzo-96** [microsoft/vscode-jupyter#14686]
In  **Settings > Jupyter > Magic Commands As Comments** we can see that uncomment shell assignment for line or cell only work for following types of comments: **#!, #!% #!%%**. As we can see this is not working with the files generated from Databricks which use **# MAGIC** instead of **#!**. Is there a workaround around this to make it work with magic commands coming from Databricks files, and can we have this as a extension of the setting. 

Thanks!

**Comment by DonJayamanne** [comment]
@Mertzo-96 thank you for filign this issue.
Please can you give an example of the magic command, I tried searching but couldn'-t find anything.
thanks

**Comment by Mertzo-96** [comment]
So when you create .py file in databricks all the magic commands get commented in this way:
**# MAGIC %run SOME_PATH_TO_FILE**
The problem is when you turn on this setting **Settings > Jupyter > Magic Commands As Comments** in VS Code, it starts reading comments magic lines correctly, without this setting ig gives error on the line:
**% run SOME_PATH_TO_FILE**
but if I do it as it says in the setting:
**#! %run SOME_PATH_TO_FILE**
then it works, my only problem with it is that it only reads these type of comments: **#!** as Commented Magic Command and **# MAGIC** coming from Databricks is ignored.

 Is this enough context?

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
