### ISSUE TITLE
[Feature Request] Contextual Help menu

### ISSUE THREAD

**Issue by RensDimmendaal** [microsoft/vscode-jupyter#1468]
In jupyter lab you can add a tab next to your editor which shows the function signature of the function you're currently writing / the one you clicked on latest. Pycharm has similar feature as well. I would love to be able to use it in vscode. 

Example:
![image](https://user-images.githubusercontent.com/9828683/62698384-4cdd6700-b9dd-11e9-94bb-47a7f50f0b82.png)

**Comment by IanMatthewHuff** [comment]
Dupe of #1307. Currently implemented in the Jupyter PowerToys extension.
