### ISSUE TITLE
Unable to find widget 'ipyevents' version '2.0.2' from configured widget sources ["jsdelivr.com","unpkg.com"]. Expected behavior may be affected. Click [here](https://aka.ms/PVSCIPyWidgets) for more information.

### ISSUE THREAD

**Issue by Aarathitomsb** [microsoft/vscode-jupyter#14682]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, 
Unfortunately this is an issue with the ipyevents package
The generate practice if for Widget authors to publish the JS packages in the CDN as well, however when this isn't done then widgets might not work as expected.
Please file an issue on the ipevents python repo.
