### ISSUE TITLE
Python Run Cell Fails - 'No Kernel Connected'

### ISSUE THREAD

**Issue by adxsoft** [microsoft/vscode-jupyter#14692]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.84.0
- OS Version: Mac 10.13.6

Steps to Reproduce:

1. See youtube video https://youtu.be/w2HLRYZNhAQ for demo of the problem
2.

**Comment by adxsoft** [comment]
Hi Don .. thanks for chasing this up.

Attached are results from re-running the cell as shown in the video

1. Console output  - 'vscode-app-1699489548877.log'
2. settings.json file 'settings original.json'

I added the line to the user settings you suggested
_"jupyter.disableZMQSupport": true_

This test produced the following error

**Missing field in JSON data: notebook.path. 
View Jupyter log for further details.**

Attached are

1. the Jupyter tab output - 'Jupyter output after jupyter.disableZMQSupport true added to user settings.log'
2. the changed settings.json

I'm not sure why but the jupyter.disableZMQSupport": true line is dimmed in the settings.json file which I thought meant it was not known to VSCode or any extension??

Note when I added the new line in the settings I quit and restarted VSCode to make sure the new settings were in effect

I've zipped up the files in the attachment 'testfiles re 14692.zip'
[testfiles re 14692.zip](https://github.com/microsoft/vscode-jupyter/files/13302772/testfiles.re.14692.zip)

Good Luck
Cheers

**Comment by DonJayamanne** [comment]
Just out of curiosity, are you able to upgrade the Mac OS  and try this?
I know thats a big change, however we're planning on deprecateing support for 10.13 in the next month or so.

> Missing field in JSON data: notebook.path.

Can you try installing Jupyter notebook into your Pytohn environment using the following command
`python -m pip install jupyter notebook` & try again.

**Comment by adxsoft** [comment]
Unfortunately can't easily upgrade as my network of old Macs cannot extend
beyond OSX version is 10.13.

Installed the Jupyter Notebook as per your instructions and still get No
Kernel connected when I run the cell.

Note I have VS Code 1.69.1, Jupyter Extension V2022.6.1201981810 and Python
extension V2022.16.1 on another Mac with 10.13 and running the cell works
perfectly as well as running a notebook.

Cheers

**Comment by DonJayamanne** [comment]
Thanks, totally understood

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by adxsoft** [comment]
Managed to get things *working* as follows

1. I Removed *all* extensions then reinstalled only Jupyter and Python
extensions.

2. Simplified the user settings JSON as follows
{
"workbench.colorTheme": "Default Dark Modern",
"window.zoomLevel": 1,
"jupyter.logging.level": "verbose",
"jupyter.disableZMQSupport": true
}

3. VSCode Jupyter extension loaded successfully and detected python 3.10.0
correctly

4. Run the code
# %%
a=1
b=2
print(a*b)

5. Resulted in Jupyter Windows which is the expected results
[image: Screen Shot 2023-11-09 at 8.15.34 pm.png]
[image: Screen Shot 2023-11-09 at 8.16.21 pm.png]

6. As a further test I removed the line

              "jupyter.disableZMQSupport": true

    and it still works!
------------------------------------------------------------------------------------------------------------------------------------------------
Not sure why the original issue arose, maybe my previous user settings JSON
(below) had a lot of irrelevant stuff from old extensions I had played with
and removed.

{
"python.pythonPath":
"/Library/Frameworks/Python.framework/Versions/3.10/bin/python3",
"python.formatting.provider": "autopep8",
"editor.formatOnSave": true,
"code-runner.executorMap": {
"python": "$pythonPath -u $fullFileName"
},
"code-runner.showExecutionMessage": false,
"code-runner.clearPreviousOutput": true,
"code-runner.saveAllFilesBeforeRun": true,
"zenMode.centerLayout": false,
"zenMode.fullScreen": false,
"zenMode.hideLineNumbers": false,
"editor.fontSize": 13,
"workbench.colorTheme": "Monokai Dimmed",
"liveServer.settings.donotShowInfoMsg": true,
"todohighlight.isEnable": true,
"todohighlight.defaultStyle": {
"backgroundColor": "#F00",
"color": ""
},
"todohighlight.keywords": [
{
"text": "IDEA:",
"color": "white",
"backgroundColor": "magenta",
"overviewRulerColor": "grey"
},
{
"text": "DEBUG:",
"color": "#ff0000",
"backgroundColor": "yellow",
"overviewRulerColor": "grey"
},
"REVIEW:",
{
"text": "DONE:",
"color": "#005500",
"backgroundColor": "green",
"overviewRulerColor": "grey"
},
{
"text": "NOTE:",
"color": "#ff0000",
"backgroundColor": "yellow",
"overviewRulerColor": "grey"
},
{
"text": "REVIEW:",
"color": "black",
"backgroundColor": "#999900",
"overviewRulerColor": "grey",
"isWholeLine": false
},
{
"text": "TODO:",
"color": "#800",
"border": "1px solid red",
"borderRadius": "2px", //NOTE: using borderRadius along with `border` or
you will see nothing change
"backgroundColor": "#AA9900"
//other styling properties goes here ...
}
],
"gitlens.advanced.messages": {
"suppressGitMissingWarning": true,
"suppressGitVersionWarning": true
},
"tabnine.experimentalAutoImports": true,
"debug.javascript.autoAttachFilter": "smart",
"explorer.confirmDelete": false,
"security.workspace.trust.untrustedFiles": "open",
"workbench.editorAssociations": {
"*.ipynb": "jupyter-notebook"
},
"python.defaultInterpreterPath":
"/Library/Frameworks/Python.framework/Versions/3.10/bin/python3",
"notebook.cellToolbarLocation": {
"default": "right",
"jupyter-notebook": "left"
},
"editor.inlineSuggest.enabled": true,
"github.copilot.enable": {
"*": true,
"yaml": false,
"plaintext": false,
"markdown": false,
"python": true,
"javascript": true,
"clojure": true,
"typescript": true
},
"python.linting.enabled": false,
"github-enterprise.uri": "
vscode://vscode.github-authentication/did-authenticate?windowid=1&code=efba1fb6ff2b0473fd3f&state=1cc2bc79-2587-4847-9e66-6462b19ddfa7
",
"explorer.confirmDragAndDrop": false,
"liveServer.settings.AdvanceCustomBrowserCmdLine": "",
"liveServer.settings.port": 8080,
"editor.accessibilitySupport": "off",
"[html]": {
"editor.defaultFormatter": "mblode.pretty-formatter"
},
"[clojure]": {
"editor.defaultFormatter": "pedrorgirardi.vscode-cljfmt"
},
"editor.snippetSuggestions": "top",
"liveServer.settings.root": "",
"liveServer.settings.CustomBrowser": "firefox",
"liveServer.settings.NoBrowser": true,
"editor.stickyScroll.enabled": true,
"timeline.pageOnScroll": true,
"workbench.localHistory.maxFileEntries": 500,
"[python]": {
"editor.formatOnType": true
},
"jupyter.interactiveWindow.creationMode": "perFile",
"update.mode": "manual",
"window.nativeFullScreen": false,
"git.openRepositoryInParentFolders": "never",
"window.zoomLevel": 1,
"workbench.editor.empty.hint": "hidden",
"jupyter.excludeUserSitePackages": true,
"jupyter.runStartupCommands": "",
"python.experiments.enabled": false,
"python.interpreter.infoVisibility": "always",
"python.languageServer": "Pylance"
}

Thanks for your prompt help
Cheers
