### ISSUE TITLE
Saving py files that have Jupyter cells would auto-generate ipynb files on-the-fly

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode-jupyter#1469]
Opening this to track this suggestion seperately. based on discussion in microsoft/vscode-python#3109 

"I second the suggestion by @JackCaster. I would even go one step further and have an option to do this conversion on-the-fly. So something like whenever I save a python file with jupyter markup a corresponding notebook is created. If it already exists, update only the cells that were modified since the last conversion and clear their output"

**Comment by amunger** [comment]
https://github.com/microsoft/vscode-jupyter/issues/1240 requests going the other direction. We'd might need both at once anyway
