### ISSUE TITLE
Add notebook filename to interrupt kernel time out popup

### ISSUE THREAD

**Issue by mdg-insens** [microsoft/vscode-jupyter#14690]
When working with various notebooks simultaneously, the popup signaling an interrupt kernel time out can appear and it is no obvious from which notebook it comes from.

Adding the concerned notebook on the popup file name could help.

**Comment by DonJayamanne** [comment]
Unfortunately its very difficult to replicate this issue, 
Easiest is to review the code or just test while debugging.

Note: The popup contains the name of the kernel and not the notebook
