### ISSUE TITLE
Allow copying an image result from Python Interactive window

### ISSUE THREAD

**Issue by andrewdelong** [microsoft/vscode-jupyter#1470]
## Environment data

- VS Code version: 1.30.2
- Extension version (available under the Extensions sidebar): 2018.12.1
- OS and version: Ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda Python 3.7.2
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda 
- Relevant/affected Python packages and their versions: None

## Expected behaviour

It'd be great if Python plots within the IDE could be copied to the clipboard. I'd expect right-click to show a menu with "Copy" as an option, for example.

Copying pasting quick plots into Slack/e-mail is super convenient for sharing intermediate results with colleagues.

## Actual behaviour

Copying code from Python Interactive works (including rich formatting), but copying images does not. Right-clicking on the image does not show a menu. Selecting the image as part of the surrounding code does not include the image.

Workaround: Take screenshot, paste into image editor, crop, copy-paste the crop, close image editor.

## Steps to reproduce:

1. Paste this into a .py script
```python
#%%
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 100)
plt.plot(x, np.sin(x))
```
2. Click "Run Cell" in the editor.
3. Try to copy the resulting plot to the clipboard.

**Comment by rstoddard24** [comment]
I also found I can drag and drop into google products (Gmail, Google Slides)

On Mac, a work around to get to Slack is drag and drop into Finder, a .png file is rendered, then drag and drop into Slack (or wherever)

**Comment by andreimargeloiu** [comment]
It's 2021, it would be good to be able to copy the figures from the interactive figure viewer...

**Comment by berkdemir** [comment]
Any development on this issue?

**Comment by rchiodo** [comment]
Sorry but this is not currently supported. There is no context menu for output in either the stable or insiders build nor any way to use the clipboard to copy output images. This should probably be an upstream bug in VS code.

The only thing that works (on windows) is you can drag images out of the view to windows explorer to create a download.png.

**Comment by rchiodo** [comment]
Moving back to triage to see if we can get VS code to support copy on output.

**Comment by berkdemir** [comment]
Any option such as right click menu or button after double click (currently
downloads as pdf) would be great. Spyder works great in this manner.

3 Şub 2021 Çar 20:19 tarihinde Rich Chiodo <notifications@github.com> şunu
yazdı:

**Comment by greazer** [comment]
Just wanna discuss with VS Code team about what could be done here.

**Comment by linzhlalala** [comment]
with today updating. Double click doesn't go edit panel.

**Comment by gaboceron10** [comment]
It is possible to save the file to local and then copy it. However copying it directly from the output would save us some time.

**Comment by CamilleHamon** [comment]
It would be very useful to get this feature. I ended using the Snipping Tool as a workaround, which is almost as fast as being able to CTRL+C in VS Code.

**Comment by ryblogs** [comment]
I'm on MacOS. I was always able to Copy / Paste image results from the Python interactive window by highlighting/selecting the graphic with the mouse and pressing CTRL+C. However, this functionality seems to have broken in the 1.60 update. I can click+drag the image result into some applications (e.g. an outlook email), but that doesn't work in some other applications (e.g. MS Teams).

**Comment by ceaza** [comment]
For charts, copy CTRL+C not working with 1.60 on windows.

**Comment by bpops** [comment]
I didn't want to create a new issue, but it appears some of the functionality discussed herein is further broken in the new vs code notebooks. Also, my main way of using plots before, dragging them out of vs code directly into powerpoint, no longer works. I must drag them into a windows explorer folder and then into powerpoint.

**Comment by amunger** [comment]
A copy to clipboard feature was added to the renderer in https://github.com/microsoft/vscode/issues/129880
