### ISSUE TITLE
Dark theme support for ipywidgets

### ISSUE THREAD

**Issue by kolibril13** [microsoft/vscode-jupyter#14714]
Ipywidgets don't look too pleasant in dark mode 
<img width="831" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/44469195/ae077a4d-cda2-4cd9-b630-3d20f9dbed8c">

Therefore I'd like to ask Is it possible to support theming for ipywidgets?

There was a discussion about this 3 years ago, where @DavidKutu mentioned that there is no theming support planed:
https://github.com/microsoft/vscode-jupyter/issues/1355

Maybe things have changed since then? Would be great to have that feature!
cc. @DonJayamanne

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/7161
