### ISSUE TITLE
Running multiple lines in interactive window not working

### ISSUE THREAD

**Issue by FDenker** [microsoft/vscode-jupyter#14721]
## Environment data

-   VS Code version: 1.84.2
-   Jupyter Extension version (available under the Extensions sidebar): v2023.10.1003070148
-   Python Extension version (available under the Extensions sidebar): v2023.20.0
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: python 3.11.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): anaconda
-   Jupyter server running: Local 

## Expected behaviour

Selecting multiple lines and then either pressing the shortcut or right clicking and selecting "Run Selection/Line in Interactive window" should run this selection in the interactive window. 
The shortcut works completely fine 

## Actual behaviour
However, nothing happens. 

Interestingly, if I hold the shortcut at some point it will run it (then multiple times). I know this sounds really strange but I have done a complete reinstall of windows and it is still happening.

Interestingly, the shortcut works completely fine if I just select one line

![python_issue](https://github.com/microsoft/vscode-jupyter/assets/29603173/5513d384-0285-43a1-a7e4-4c131eef75e4)

**Comment by amunger** [comment]
by "shortcut" do you mean the keyboard shortcut? (`shift+enter`)?

What do you have in your settings for `jupyter.interactiveWindow.textEditor.normalizeSelection`? Does the behavior change if you toggle that setting?

**Comment by FDenker** [comment]
Hi,
Thank you so much. I had it toggled on, but it works if I turn it off! That is amazing.

Should I close this issue or would you like to investigate why normalizing the selection causes the issue?

**Comment by amunger** [comment]
thanks for the update. We plan to eventually turn that setting off for everyone by default, so I think we can just close this.
