### ISSUE TITLE
Can not use micromamba env as a kernel

### ISSUE THREAD

**Issue by meicale** [microsoft/vscode-jupyter#14730]
the pluging find nothing to be used as a kernel

**Comment by DonJayamanne** [comment]
Thanks for filing this issue & sorry you are running into this.

Do you see the micromamba environment in the Python environment picker?
Use the command `Python: Select Interprerte` to see the list of Python environments

**Comment by meicale** [comment]
> Do you see the micromamba environment in the Python environment picker? Use the command `Python: Select Interprerte` to see the list of Python environments

Yes, it can be found and used. 
My solution to this problem is to use the preview version of this plugin.
