### ISSUE TITLE
Some LaTeX markdown tags do not render correctly

### ISSUE THREAD

**Issue by laduran** [microsoft/vscode-jupyter#14732]
## Environment Information

VS Code version Info:
Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

Jupyter Extension version: v2023.10.1100000000
Python Extension version:  v2023.20.0
OS (Windows | Mac | Linux distro) version: Windows 11 Pro v23H2
Python Version:  3.11.6

## Issue description

The following math markdown renders correctly when I am running in a proper Anaconda Jupyter environment:

$$y^{(i)}_{prediction} = \begin{cases} 1 & \mbox{if } a^{[2](i)} > 0.5 \\ 0 & \mbox{otherwise } \end{cases}\tag{5}$$

However, if I try to render this same above latex I get errors. 

The error being:
![image](https://github.com/microsoft/vscode-jupyter/assets/4511009/1fd397ec-646e-4f13-a5f3-c17ae61e8ab9)

I also corrected the errors so the proper rendering is shown above the error.
The tag causing the issue is the \mbox tag.

### Notes
There are likely other tags that are either not handled correctly or not supported.
I found this issue when importing Jupyter Notebooks from other sources and noticed that the Markdown didn't render correctly in VS.Code but was rendering correctly in other environments.

I am willing to help work on this bug/feature request but would need some guidance on where LaTeX support is in the code.

**Comment by amunger** [comment]
the issue is actually within the Katex library that vscode uses for latex markdown rendering https://github.com/KaTeX/KaTeX/issues/2050
