### ISSUE TITLE
@property decorator does not work in ipython notebooks 

### ISSUE THREAD

**Issue by Etrama** [microsoft/vscode-jupyter#14748]
I am trying to use @property decorators to define getters and setters in VS Code Ipython notebooks. They always error out with a type error. The same code when executed in a .py file runs successfully.

## Environment data

-   VS Code version: 1.84.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.10.1100000000
-   Python Extension version (available under the Extensions sidebar): v2023.21.13241008
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.22621
-   Python and/or Anaconda version: 3.11.5 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local (N/A probably)

## Expected behaviour

@property decorators can be used to define getters and subsequently @propety.setter decorators can be used to define setters. See example code.

## Actual behaviour

@property decorators lead to a TypeError. (TypeError: 'property' object is not callable)

## Steps to reproduce:

1. Try running the following python code in an ipython cell in vscode:
```
class Pokemon():
    def __init__(self):
        self._attack = 0

    @property
    def attack(self): # attack getter
        return self._attack
    
    @attack.setter
    def attack(self, value):
        self._attack = value
```

2. Try running the same code in a .py script. I am prvoding an example script below for ease of reproduction:
```
class Pokemon():
    def __init__(self):
        self._attack = 0

    @property
    def attack(self): # attack getter
        return self._attack
    
    @attack.setter
    def attack(self, value):
        self._attack = value
    
if __name__ == "__main__":
    pokemon = Pokemon()
    pokemon.attack = 50
    print(pokemon.attack)
```

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
{
	"name": "TypeError",
	"message": "'property' object is not callable",
	"stack": "---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
c:\\Users\\kaush\\Desktop\\python_projects_new\\oops-for-data-scientists\\oops-for-data-scientists.ipynb Cell 121 line 1
----> <a href='vscode-notebook-cell:/c%3A/Users/kaush/Desktop/python_projects_new/oops-for-data-scientists/oops-for-data-scientists.ipynb#Y316sZmlsZQ%3D%3D?line=0'>1</a> class Pokemon():
      <a href='vscode-notebook-cell:/c%3A/Users/kaush/Desktop/python_projects_new/oops-for-data-scientists/oops-for-data-scientists.ipynb#Y316sZmlsZQ%3D%3D?line=1'>2</a>     def __init__(self):
      <a href='vscode-notebook-cell:/c%3A/Users/kaush/Desktop/python_projects_new/oops-for-data-scientists/oops-for-data-scientists.ipynb#Y316sZmlsZQ%3D%3D?line=2'>3</a>         self._attack = 0

c:\\Users\\kaush\\Desktop\\python_projects_new\\oops-for-data-scientists\\oops-for-data-scientists.ipynb Cell 121 line 5
      <a href='vscode-notebook-cell:/c%3A/Users/kaush/Desktop/python_projects_new/oops-for-data-scientists/oops-for-data-scientists.ipynb#Y316sZmlsZQ%3D%3D?line=1'>2</a> def __init__(self):
      <a href='vscode-notebook-cell:/c%3A/Users/kaush/Desktop/python_projects_new/oops-for-data-scientists/oops-for-data-scientists.ipynb#Y316sZmlsZQ%3D%3D?line=2'>3</a>     self._attack = 0
----> <a href='vscode-notebook-cell:/c%3A/Users/kaush/Desktop/python_projects_new/oops-for-data-scientists/oops-for-data-scientists.ipynb#Y316sZmlsZQ%3D%3D?line=4'>5</a> @property
      <a href='vscode-notebook-cell:/c%3A/Users/kaush/Desktop/python_projects_new/oops-for-data-scientists/oops-for-data-scientists.ipynb#Y316sZmlsZQ%3D%3D?line=5'>6</a> def attack(self): # attack getter
      <a href='vscode-notebook-cell:/c%3A/Users/kaush/Desktop/python_projects_new/oops-for-data-scientists/oops-for-data-scientists.ipynb#Y316sZmlsZQ%3D%3D?line=6'>7</a>     return self._attack
      <a href='vscode-notebook-cell:/c%3A/Users/kaush/Desktop/python_projects_new/oops-for-data-scientists/oops-for-data-scientists.ipynb#Y316sZmlsZQ%3D%3D?line=8'>9</a> @attack.setter
     <a href='vscode-notebook-cell:/c%3A/Users/kaush/Desktop/python_projects_new/oops-for-data-scientists/oops-for-data-scientists.ipynb#Y316sZmlsZQ%3D%3D?line=9'>10</a> def attack(self, value):

TypeError: 'property' object is not callable"
}
```

</p>
</details>

Please let me know if you need any additional information.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, I have tested this at my end in a similar environment (mac, python 3.11) & it works without any issues.
Please could you verify you are using the same Python environment in both cases
I.e. run the following in in a cell
```
import sys
sys.executable
```
& verify the output is the same in both of the cases (i.e. vscode and Jupyter)

I suspect this is something at your end, as there's notihng in the Jupyter exetnsion that we do to handle such things.
Please try running the same notebook in a different folder or the same python environment (if its not the same)
![Screenshot 2023-11-21 at 18 01 46](https://github.com/microsoft/vscode-jupyter/assets/1948812/4b0ee053-7229-4d87-b9f6-9717d55da0ee)


If this still fails
Then please share the following
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by Etrama** [comment]
Thanks for your response!

I can confirm that both the .ipynb and .py are running the same python:
<img width="928" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/22076465/8cde3053-fffc-4121-a25c-a8093d65b64b">

<img width="678" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/22076465/c22e1148-76b5-408f-bbde-bd526f958999">

<hr>
Changed the logging level as requested:
<img width="443" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/22076465/af09cb25-29cc-4c35-9e5a-4974d4ab60ef">

Reproducing the issue:
Weirdly, I could not reproduce the issue. The error went away once I restarted VS Code. Thanks for your help, but this is a little curious.

I am closing the issue as we cannot reproduce the error.

If someone else has the @property decorator leading to a TypeError in an .ipynb, please restart your VS Code.
