### ISSUE TITLE
Can't save to remote workspace

### ISSUE THREAD

**Issue by svechinsky** [microsoft/vscode-jupyter#1474]
# Bug: Notebook Editor, Interactive Window, Python Editor cells
When specifying a remote Jupyter server I can successfully creat new notebooks via the command palate but I can't save them.
When I click on the save icon it just prompts saving the notebook on my local computer.
Also, it doesn't let me view other notebooks/files on the remote server.

## Steps to cause the bug to occur
1. Specify a remote URI
2. Create a new notebook via command palate
3. Try and save 

### Expected
Clicking save saves the notebook on the remote desktop
+
Being able to view other files on the remote workspace.
### Actual
Clicking save prompts for a local save and I can't view other files.

### Your Jupyter and/or Python environment
*Please provide as much info as you readily know*
- **Jupyter server running:**                       Remote
- **Extension version:**                               2019.10.41019
- **VS Code version:**                                1.39.1
- **Setting python.jediEnabled:**                false
- **Python and/or Anaconda version:**     3.7
- **OS:**                                                     Ubuntu
- **Virtual environment:**                          pipenv

**Comment by rchiodo** [comment]
This should be resolved. At least the remote-ssh case.

**Comment by rchiodo** [comment]
The other case is handled by this:
https://github.com/microsoft/vscode-jupyter/issues/1366
