### ISSUE TITLE
Shift+Enter doesn't route to Jupyter

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/vscode-jupyter#14753]
Type: <b>Bug</b>

I have both the Python and Jupyter extensions installed; however, when I hit <kbd>Shift</kbd>+<kbd>Enter</kbd>, I always end up getting my code run in a Python shell instead of my interactive window.

In other words, Python's "[Run Selection/Line in Python Terminal](https://github.com/microsoft/vscode-python/blob/main/package.json#L1188-L1192)" command is run instead of Jupyter's "[Run To Line in Interactive Window](https://github.com/microsoft/vscode-jupyter/blob/64e59437a71e7d91f61f9b6bb43b93547f1c9304/package.json#L127-L131)" command.

Extension version: 2023.20.0
VS Code version: Code - Insiders 1.85.0-insider (da5ab29656a9f0bef63602fbce10968a7f4db2b5, 2023-11-20T18:53:26.158Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.49GB free)|
|Process Argv|--log vscode.typescript-language-features:trace --crash-reporter-id b3069aa6-29c0-4a9a-9f21-122aa0ea5c48|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
showlangstatbar:30737417
pythonfmttext:30716741
9b8hh234:30694863
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
synctok:30869157
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30859870
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by DonJayamanne** [comment]
Sorry you are running into this issue.
Please can you check whether this setting is turned on, if not, please could you turn that on and try it again.
You might need to re-load VS Code.

![Screenshot 2023-11-22 at 08 16 41](https://github.com/microsoft/vscode-jupyter/assets/1948812/02e1859f-3771-4855-9e61-f371241f8663)

**Comment by DanielRosenwasser** [comment]
I didn't! It now works as expected, sorry about that.

For background, I saw this in my context menu:

![image](https://github.com/microsoft/vscode-jupyter/assets/972891/2dbe68b3-a42f-4029-8797-061416f28e51)

and since the <kbd>Shift</kbd>+<kbd>Enter</kbd> keybinding is explicitly called out, I assumed that something must be wrong.

Is it possible to not show the keybinding in the context menu unless Jupyter can really guarantee that behavior?

Also, the Jupyter experience is so much closer to what I want that you can also take this as a vote to switch the default of `"jupyter.interactiveWindow.textEditor.executeSelection"` to `true`. 😄

**Comment by amunger** [comment]
This will eventually always go to the native python REPL by default, which is the same editor widget. Using a jupyter kernel instead will still require that setting or having a `# %%` cell in the file
