### ISSUE TITLE
Native Experience - Right click on cell should have a context menu (copy/paste)

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#1475]

**Comment by hawktang** [comment]
Report same issue here

**Comment by axsk** [comment]
Still present in 1.53.2

**Comment by patryk-madej** [comment]
same issue, no context menu

**Comment by VinodPathak** [comment]
Any updates on this?

**Comment by August65** [comment]
Any updates ? still no right click menus in cell:
Version: 1.55.1 (user setup)
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T15:06:02.360Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by seadniksic** [comment]
Same issue still present for me

**Comment by adamszpilewicz** [comment]
Still have that issue.

**Comment by Erik262** [comment]
Yeah same here, not able to click with the right mouse button. Huge UX-Failure in my opinion.

**Comment by cvallenduuk** [comment]
I also have the same issue

**Comment by serivas** [comment]
Same issue here, very annoying

**Comment by fisicocarlos** [comment]
I also have the same issue. Very annoying

**Comment by Mr-Boshi** [comment]
Same issue

**Comment by topogibra** [comment]
Same issue as well

**Comment by Erik262** [comment]
If you guys use VS Code Insider, then this context menu works!

**Comment by kllsi** [comment]
I'm still having the same issue

**Comment by gaboceron10** [comment]
Upvoting, I'd also like this feature, so the notebook could work with extensions.

**Comment by gaboceron10** [comment]
> If you guys use VS Code Insider, then the right click context menu works!

@Erik262 Did it work for your? Did you get text edition like copy/paste? I'm using insiders and when I right click I get cell edition options. I'm using setting: "jupyter.experiments.optOutFrom": ["NativeNotebookEditor"],

**Comment by joyceerhl** [comment]
There's a right click context menu in the new preview native notebooks experience. It's available by default to everyone in VS Code Insiders and a fraction of VS Code Stable users. Please see https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code#enabling-the-new-experience for instructions on how to enable the new experience in VS Code Stable.

![recording (25)](https://user-images.githubusercontent.com/30305945/125894022-d4b04a26-cbcd-41c6-a422-5b6f9bceaa44.gif)

**Comment by Erik262** [comment]
> > If you guys use VS Code Insider, then the right click context menu works!
> 
> @Erik262 Did it work for your? Did you get text edition like copy/paste? I'm using insiders and when I right click I get cell edition options. I'm using setting: "jupyter.experiments.optOutFrom": ["NativeNotebookEditor"],

Yeah it works, just out of the box, didn't change anything.

**Comment by IanMatthewHuff** [comment]
Closed as resolved by the new editor UI.
