### ISSUE TITLE
AnyWidget should work without access to external network resources

### ISSUE THREAD

**Issue by billti** [microsoft/vscode-jupyter#14761]
I'm building out some custom IPyWidgets using AnyWidget. All the files needed are installed with the packages for both AnyWidget and my custom widgets (via pip), yet Visual Studio Code fails if there is no network connection with the below:

<img width="571" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/993909/2934e8a3-4ffc-480b-93cd-4b8eda8eadd2">

From looking at the network trace, it would appear it's using a CDN for a couple of basic files (seems to be require.js, and the AnyWidget index.js that is already in the pip package).

By contrast, when using the `jupyter lab` web browser interface, everything works great with no network connection, and I can see it is fetching everything from the jupyter server running on localhost:

<img width="840" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/993909/174d3aa6-4300-4745-8328-e0e71394db21">

The actual custom widget JS and CSS files that AnyWidget loads seem to load fine via a blob URI in VS Code without issue, so it does seem to be only the AnyWidget files themselves which are failing. 

It would be great is VS Code could support pip installs of AnyWidget - and custom widgets using it - without needing to hit external network resources.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.

Most liked already resoved by https://github.com/microsoft/vscode-jupyter/pull/14711
Please try installing the latest pre-release version of the Jupyter extension in VS Code insiders.

**Comment by billti** [comment]
Works great for local Python environment. Still fails if connected to a Jupyter server kernel. That's lower pri for me though, so not sure if you want to track this here or elsewhere.

**Comment by DonJayamanne** [comment]
This works for Remmote Jupyter Notebook servers, but not for Remote Jupyter lab servers.

**Comment by DonJayamanne** [comment]
Verified by author.
