### ISSUE TITLE
Export (Jupyter) notebook as HTML

### ISSUE THREAD

**Issue by johnstantongeddes** [microsoft/vscode-jupyter#1476]
I love being able to work with Jupyter Notebooks as .py files with an interactive Python session, similar to how Rmarkdown works in RStudio. The only thing I'm missing is the ability to *export the HTML*, without (explicitly) going through ipynb. I think this request would be a component of the larger [Support Jupyter Notebook Interactive Computing paradigm](https://github.com/microsoft/vscode/issues/34739) issue.

**Comment by DavidKutu** [comment]
Dupe of #1490
