### ISSUE TITLE
Unable to download widgets from remote Jupyter Lab servers

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#14762]
Today we are able to download widgets from remote jupyter notebook servers, but not from remote jupyter lab servers.
This is due to the changes in how the scripts are bundled for lab vs notebooks.

See here https://github.com/microsoft/vscode-jupyter/issues/14761

**Comment by DonJayamanne** [comment]
So far not reported by anyone, hence left as debt item.

**Comment by s1lvester** [comment]
Hi, 

i would like to raise my Hand concerning this issue :)

Alternatively I would suggest for vscode-jupyter to "honor" the settings for the remote vscode-server to always download on the client, not on the server.

How is this relevant?

If you work on an "airgapped" jupyterlab with vscode-remote-ssh you have no option do download widgets using: 

"jupyter.widgetScriptSources": ["jsdelivr.com", "unpkg.com"].

However vscode-server is perfectly able to use the vscode-client to download extensions/files/updates/whatever and push them through ssh to be installed on the vscode-server.

Thank you for your concideration.

Rgds
Markus

**Comment by DonJayamanne** [comment]
@s1lvester 

> However vscode-server is perfectly able to use the vscode-client to download extensions/files/updates/whatever and push them through ssh to be installed on the vscode-server.

The challenge is not being able to download files, but being able to download widget files from jupyter lab

**Comment by s1lvester** [comment]
Thanks for responding. I could also spin-out the issue with downloading files through ssh into a separate issue?

**Comment by DonJayamanne** [comment]
>  I could also spin-out the issue with downloading files through ssh into a separate issue?

I think you have misunderstood this issue,
What is the exact problem you are running into, please can you describe the issue and share the error message and the like.
