### ISSUE TITLE
Gradio doesn't render its UI when executed remotely

### ISSUE THREAD

**Issue by alexandrnikitin** [microsoft/vscode-jupyter#14777]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I'm trying to use Gradio with Jupyter VSCode extension connected to remote host. It doesn't render its UI in output cell. 
The same code works fine locally. See screenshot. I tried both latest stable and prerelease versions.

Note: it doesn't have `show_api=False` arg on the right screenshot but it doesn't affect it.

<img width="1715" alt="Screenshot 2023-11-24 at 6 00 53 PM" src="https://github.com/microsoft/vscode-jupyter/assets/1798438/1629304c-362b-468e-9b06-7cd38d560b2e">

The code:

```python
%pip install gradio

import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
demo.launch()
```

### VS Code Version

Version: 1.84.2 (Universal) Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e Date: 2023-11-09T10:52:33.687Z (2 wks ago) Electron: 25.9.2 ElectronBuildId: 24603566 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Darwin arm64 23.1.0

### Jupyter Extension Version

v2023.10.1100000000

### Jupyter logs

```shell
No errors, only messages like these:

02:04:19.882 [info] Handle Execution of Cells 19 for <deleted>
02:04:19.892 [info] Kernel acknowledged execution of cell 19 @ 1700877859892
02:04:20.025 [info] End cell 19 execution @ 1700877860024, started @ 1700877859892, elapsed time = 0.132s
```

### Coding Language and Runtime Version

Python 3.11.3

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
Have you tried share=true for public access (as per the output)?


Since it’s remote the server is running on the remote machine, 
Hence local host will not work from your machine

Closing as this isn’t an issue with vscode
I’m certain you will run into the same issue with Jupyter lab/notebook in the browser as well

if you think this is an issue with vscode please feel free to reopen or create another issue  with the new information
