### ISSUE TITLE
Having the interactive window on a different screen when running VS code interactively with python

### ISSUE THREAD

**Issue by nemar3** [microsoft/vscode-jupyter#14789]
Having the interactive window on a different screen when running VS code interactively with python:

having the code and the interactive window all in one screen is not ideal, I am always adjusting and readjusting the size of the windows depending if I want to see more code or more of the interactive output, having the possibility to split this into multiple screens would be great

this was already requested on stackoverflow:
https://stackoverflow.com/questions/66921894/opening-python-interactive-tab-in-different-window

**Comment by amunger** [comment]
This is just recently becoming possible with https://github.com/microsoft/vscode/issues/10121#issuecomment-1790316086.

It looks like the Interactive Window is not yet supported in a floating window, but you should be able to move the python file to a separate window in the next release. I'll keep an eye out for how to add support for the IW.

**Comment by nemar3** [comment]
thanks ! this is awesome, I installed vs code insiders, I have two monitors, I extended them, it's not possible to create a floating window for the interactive window, it is however  possible to create a floating window for the python code, so this gets me the result I was after: now I have these in two separate screens

**Comment by amunger** [comment]
I believe this fully works now.

**Comment by anthonykim1** [comment]
![Image](https://github.com/user-attachments/assets/e1b2fed0-5419-447b-bb25-b82d20a93c2a)
verified it is working as expected as I see IW on its own floating window when there are #%% symbol to denote to run in IW
