### ISSUE TITLE
[Feature Request] Add context menu for Python Interactive window

### ISSUE THREAD

**Issue by Coderx7** [microsoft/vscode-jupyter#1478]
Adding a context menu that hosts different operations allowed in the interactive window would be a great feature. for example restarting, interrupting a kernel, adding a new cell, removing a cell, expanding/collapsing and more importantly copying a cell content or portions of it, can be provided in a context menu. 
 
Currently, the only way we can copy an error or output from the python interactive window is by first making a selection and then pressing Ctrl+C. this is not desirable and an uncalled-for hassle. nearly always after making a selection, I uncontrollably go for a right click to select copy! and bang there is no context menu and I have to reselect what I selected before again! 

It would be much appreciated if you could add a context menu where we can select a word, line, or the whole output of a cell, and then copy it. 
being able to restart/interrupt a kernel, etc from a context menu is also desirable and greatly appreciated.

**Comment by joyceerhl** [comment]
Context menus are now supported in the Python interactive window.
