### ISSUE TITLE
Allow custom jupyter widget sources

### ISSUE THREAD

**Issue by divyansshhh** [microsoft/vscode-jupyter#14791]
I would like to use a custom cdn as the source for some widgets. Currently only jsdelivr and unpkg are supported. Can we add support for custom widget sources?

**Comment by DonJayamanne** [comment]
@divyansshhh Out of curiosity, why do you need this?
Why doln't the existing CDNs work?

**Comment by robertmartin8** [comment]
+1 this is necessary for corporate users

**Comment by DonJayamanne** [comment]
Closing as not planned, due to lack of upvotes

**Comment by mlucool** [comment]
Would you be willing to take a PR here?
