### ISSUE TITLE
New Notebook Editor Toolbar

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-jupyter#1479]
To discuss new toolbar designs. This also removes a lot of clutter from https://github.com/microsoft/vscode-python/issues/8116 by moving a lot of the cell actions to the toolbar

![image](https://user-images.githubusercontent.com/15910920/67519729-51b8cb00-f65c-11e9-8ec3-036983ae0d48.png)

**Comment by IanMatthewHuff** [comment]
Closed by new UI
