### ISSUE TITLE
Provide option for 'never ask again' for denying kernel access

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#14806]
Testing #14787

That pop-up would get really annoying if I didn't ever want to grant access to a particular extension that kept asking for it.

**Comment by DonJayamanne** [comment]
>  particular extension that kept asking for it.

Or disable/uninstall the extension?

I do not want to add too many buttons to a modal dialog box.
Lets discuss in sync meeting.

**Comment by DonJayamanne** [comment]
Fixed,
