### ISSUE TITLE
Error on Jupyter extension installation/startup

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#14800]
Testing #14788

<img width="484" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/876920/241c3428-6fb1-42ff-bd49-7867fb92a614">

In my dev container, I have Python and Pylance extension disabled and then I found I don't have Jupyter installed yet, so I went ahead, installed Jupyter and immediately got this error.

**Comment by DonJayamanne** [comment]
Do you have zmq disabled?

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/14799
