### ISSUE TITLE
Learn more dismisses the modal dialog 

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#14808]
Testing #14787

Not sure how to proceed once I click on Learn More as the modal dismisses and ended up in a weird state.

**Comment by DonJayamanne** [comment]
Perhaps we can discuss at notebook sync,
As this is a modal diaglog, I do not see any other way to add a learn more button.
Given the docs let users know they can manage the permissions i think it should be ok

**Comment by rebornix** [comment]
@DonJayamanne should "Learn more" be treated as no-op, so the next time if the same request comes, we show it again?

**Comment by DonJayamanne** [comment]
> e treated as no-op, so the next time if the same request comes, we show it again?

Aaah got it, yes, thats right it should.
