### ISSUE TITLE
Can not start Julia Kernel

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#14801]
Testing #14788

<img width="636" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/876920/9cd646c7-fedd-4c75-9438-979e85fcd9e0">

* Ensure Julia and Python extensions disabled
* Install Jupyter extension
* Now open a notebook which contains Julia cells
* The kernel is now set to Julia automatically somehow
* Now run Julia code, I got this error.

**Comment by DonJayamanne** [comment]
Closing as zmq was disabled. User setup issue.
