### ISSUE TITLE
Issue navigating notebook especially with hidden blocks

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#14804]
From [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details):

> the jupyter notebook extension is a**. its slow. sometimes I can't tell when blocks are missing if i deleted it accidentally. Sometimes, it also mixes a hidden md/code cell with other blocks and f***s up a lot of the data. this causes me to have trouble editing certain books because it jumps up to some ghost book that i can't even delete. I had to create another notebook all together in order to get rid of it. I also closed the prev notebook and it got rid of it, but if you have tons of data for processing stuff and you would neeed to rerun cells in order to get the variables back, its a massive waste of time.

**Comment by minsa110** [comment]
I'm guessing that the "hidden blocks" mentioned here are collapsed blocks. So I played around with notebook navigation with a bunch of collapsed blocks (both input/output and code/md), but didn't run into problem mentioned here. Could you provide more info so we can debug the issue?

**Comment by DonJayamanne** [comment]
> t jumps up to some ghost book that i can't even delet
>  also closed the prev notebook and it got rid of it,


Looks like screen cheese, closing and reopening notebooks generally fixes screen cheese

**Comment by DonJayamanne** [comment]
Unfortunately there hasn't been any additional information provided that can help address this issue.
Hence closing this issue.
If anyone run into this issue, please create a new issue with the details requested in the issue template.
