### ISSUE TITLE
Notebook Editor - linter support

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1482]
We should support linting and syntax errors in cells.

**Comment by nickeubank** [comment]
e.g. something like https://github.com/dnanhkhoa/nb_black for vscode?

**Comment by nickeubank** [comment]
I opened an issue to ask about ease of porting [here](https://github.com/dnanhkhoa/nb_black/issues/34).

**Comment by IanMatthewHuff** [comment]
Resolved by native notebook editor UI
