### ISSUE TITLE
Expect share jupyterlab kernel instance in runtime in new stable api

### ISSUE THREAD

**Issue by realDuang** [microsoft/vscode-jupyter#14831]
Currently we are using the newly provided stable API of jupyter extension to let our extension connect to the server of Fabric notebook. It allows the extension side to pass in a custom Websocket class, which indeed provides high flexibility for custom features, which is very great.

But at the same time, I also noticed that the new api will cancel most of the runtime hooks, which means that it will be more difficult for the extension to obtain the runtime jupyterlab packaged api through jupyter extension.

One solution I thought of was that I tried using KernelManager.connectTo() in the Websocket class after establishing the connection trying to share the same kernelConnection with the jupyter extension. But this doesn't work because the jupyter extension doesn't seem to have created its own Kernel Connection instance at this time. And if I create a new kernelConnection in the WebSocket class, it will not be reused by the jupyter extension.
![image](https://github.com/microsoft/vscode-jupyter/assets/17807197/91d89e63-9160-4569-ac60-ecff467b4f0f)

Of course, there may be a more appropriate solution here, such as providing a new hook to allow the extension to obtain the instance. I'd like to hear your concerns. Everything done here is to enable the extension side to use the api encapsulated by jupyterlab, thereby improving the ease of use of jupyter extension.

**Comment by DonJayamanne** [comment]
> also noticed that the new api will cancel most of the runtime hooks, wh

Can you give an example of what kind of other messages/runtime hooks are required/
I was under the impression that Synapse extension  needs to send one message after connection and that was it.
Why do you need hooks and the like?

**Comment by realDuang** [comment]
The best practice we hope should not be to only send a message manually, but to be able to call Jupyterlab's API to control the life cycle of the message. Such as constructing a comm_msg to automatically generate id and time, or constructing a control msg auto-increment sequence, or registering hook to wait for msg response.

This can be done by sharing jupyterlab's kernelConnection instance with us through the jupyter extension.

```ts
          const kernelManager = new KernelManager();
          const kernelConnection = await kernelManager.connectTo({ model: this.kernelModel! });
          this.connection = kernelConnection;
```
