### ISSUE TITLE
Interactive Variables View, possibility to search by name with a shortcut, similar to Spyder variable explorer

### ISSUE THREAD

**Issue by nemar3** [microsoft/vscode-jupyter#14842]
When running python code in VS Code on interactive mode, there's a Variables view, that has name, type ,size , value.
there can be many variables in this view, currently in order to locate the variable by name, I have to scroll up and down.
Spyder has a similar functionality :variable explorer, but in there I can search by name typing cntr+F.
Would be great to have something similar in VS Code

**Comment by amunger** [comment]
We are currently in the process of building out a variable view for kernels/notebooks in vscode core. With a tree view for the variables, we should be able to include search functionality.
https://github.com/microsoft/vscode/issues/165445
https://github.com/microsoft/vscode/issues/146748
