### ISSUE TITLE
Remote Jupyter Kernel session disposed and cannot be restarted

### ISSUE THREAD

**Issue by danguetta** [microsoft/vscode-jupyter#14851]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I am working with Jupyter notebooks in VS Code using a remote Jupyter server.

Periodically whenever I try to run a cell, I get the following message:
```Cannot execute code, session has been disposed. Please try restarting the Kernel.```

But the restart button at the top of the notebook is disabled:
<img width="114" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/3497361/99179a77-5d94-4469-991d-fea8447260a8">

In the same VS Code instance, if I open a new Jupyter notebook in a different tab and try to connect it to the remote kernel, it works just fine. But the original notebook seems "cursed" - it doesn't matter what I do (close it, re-open it, restart the remote kernel, clear the list of remote kernels and re-input it) VS Code things the kernel has been disposed and nothing will make it start a new one.

The only thing that seems to work is closign the VS Code window completely (but not force quitting VS-code) and re-opening it.

### VS Code Version

Version: 1.84.2 Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e Date: 2023-11-09T10:52:57.054Z (3 wks ago) Electron: 25.9.2 ElectronBuildId: 24603566 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Darwin arm64 23.1.0

### Jupyter Extension Version

v2023.10.1100000000

### Jupyter logs

```shell
Unfortunately I got to this box after closing the VS Code window and re-opening it, and it works now
```

### Coding Language and Runtime Version

Python v.311.6

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
> Periodically whenever I try to run a cell, I get the following message:
Cannot execute code, session has been disposed. Please try restarting the Kernel.

Please note, this is an indication of the fact that the kernel died.
This is most likely caused by some code in your notebook.
If you can only repro this in one notebook, then the problem is likely an issue with the code or some of the packages.
Based on past issues, we've found users tend to have some older versions of packages, or incompatible packages that causes the kernel process to crash/die.

Please do check if this is the case,

**Comment by danguetta** [comment]
Thanks @DonJayamanne . I'm aware that the problem is that my kernel has died. The bug is that when the kernel dies, VSCode seems unable to recreate it (the "restart" button is disabled, as shown in my initial post), and I have to close VS Code completely to fix it.

Unfortunately, it seems pretty difficult to make a Jupyter kernel die, so I can't reproduce it (if you know a sure-fire way to reproduce a kernel crash let me know!)

That said, I'll enable jupyter logging now, so the next time it happens I'll hopefully be able to post the trace here. You can put the ticket into a dormant state in the meantime.

Thanks!!

**Comment by DonJayamanne** [comment]
> The bug is that when the kernel dies, VSCode seems unable to recreate it (the "restart" button is disabled, as shown in my initial post),

Ok understood, apologies for misunderstanding the issue
Will check this out

**Comment by DonJayamanne** [comment]
>  restart the remote kernel, clear the list of remote kernels and re-input it) VS Code things the kernel has been disposed and nothing will make it start a new one.

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by danguetta** [comment]
@DonJayamanne : I've enabled verbose logging. I've tried to repro the issue but can't because it's hard to intentionally crash a kernel, but I'll keep trying and report back here with logs as soon as it does

**Comment by bsdz** [comment]
I know this issue is a closed and a fix is pending in next release. My kernels are served by Enterprise Gateway and it's configured to automatically cull kernels after a period of inactivity (12 or 24 hours). I found a temporary workaround that doesn't require restarting the IDE. Use the kernel picker to switch to a local python environment then switch back to your Jupyter kernel.
