### ISSUE TITLE
Option to not append results to Python Interactive

### ISSUE THREAD

**Issue by johnwoodill** [microsoft/vscode-jupyter#1485]
As part of my data science workflow I use the Python Interactive window as a REPL. That is, I run lines and then can interact with the Jupyter terminal to check data and figures. However, as the number of Jupyter cells grows the processing speed of each line declines. In some cases, when the number of cells exceeds 200 it takes a while to even process `1+1`. To overcome this I `restart the ipython kernel` and `remove all cells`. However, I lose my variables and have to rerun all the variables I was working with.

After some searching, it appears there was an option to disable appending results to the window, but it is not available now.

`"python.jupyter.appendResults": false,`

 It would be great to have this option available so the Python Interactive window acts more like a REPL than a notebook, at least until this issue is resolved [#727](https://github.com/microsoft/vscode-python/issues/727). These features are necessary for efficient data science workflows -- akine to Spyder and RStudio.

**Comment by rchiodo** [comment]
It's unlikely we'll get to this.
