### ISSUE TITLE
Unable to follow a traceback in the error message in Jupyter notebook

### ISSUE THREAD

**Issue by CatEek** [microsoft/vscode-jupyter#14868]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Links to the .py modules In the notebook's cell are clickable, but produce "Unable to open *.py" error
Happens on a remote machine accessible by ssh

```
File [/localscratch/mambaforge/envs/cmls/lib/python3.9/site-packages/pydantic/main.py:761](https://vscode-remote+ssh-002dremote-002bvdi.vscode-resource.vscode-cdn.net/localscratch/mambaforge/envs/cmls/lib/python3.9/site-packages/pydantic/main.py:761), in BaseModel.__getattr__(self, item)
    758     return super().__getattribute__(item)  # Raises AttributeError if appropriate
    759 else:
    760     # this is the current error
--> 761     raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')

AttributeError: 'Algorithm' object has no attribute 'model_parameters'```



### VS Code Version

1.79.2

### Jupyter Extension Version

v2023.6.1001652307


### Running Jupyter locally or remotely?

Remote

**Comment by CatEek** [comment]
<img width="253" alt="Screenshot 2023-12-06 at 11 14 57" src="https://github.com/microsoft/vscode-jupyter/assets/16350783/f91647c5-da97-47a0-9740-51d347b25b24">

This is the message, won't display in the main post for some reason

**Comment by amunger** [comment]
this should be fixed in the latest version of vs code.
