### ISSUE TITLE
Visual indicator of kernel connection status 

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#14862]
The kernel selector UI should indicate if the kernel is currently running/connected.

This would remove any need for injecting the status messages into the IW history, which can be awkward.
https://github.com/microsoft/vscode/issues/186389
https://github.com/microsoft/vscode/issues/186387
https://github.com/microsoft/vscode/issues/186489

Also would improve the notebook experience.

**Comment by DonJayamanne** [comment]
Given that no one has asked for this, I’m inclined to close this
We have this same experience in notebooks today and it hasn’t been an issue

**Comment by amunger** [comment]
I made this issue based off your comment here https://github.com/microsoft/vscode/issues/186389#issuecomment-1612204129

> We have a similar need for notebooks as well

Is that no longer true?

**Comment by DonJayamanne** [comment]
> Is that no longer true?

Good question, I have no idea what the scenarios were for Notebooks.
Its just that when I think about this now, i'm not keen on adding another item into the status bar, 
again, I cannot recall issues where users have asked for this (pity I didn't track when/if users did request this)

Perhaps this is a good item for discussions in notebook sync.

**Comment by DonJayamanne** [comment]
Been over a year and there hasn't been any feedback on the status of kernels for IW (after reloading VS Code)

See here https://github.com/microsoft/vscode/issues/186389#issuecomment-1612204129

> hence to avoid confusion, I wouldn’t auto reconnect just yet,
Do we even need to display a message about the fact that a kernel is not connected?

why not try without that message and see what users think?
