### ISSUE TITLE
set environment variables for kernels (particularly PYTHONPATH) relative to $workspaceFolder

### ISSUE THREAD

**Issue by zpincus** [microsoft/vscode-jupyter#14861]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I am not sure if this is a bug report or a feature request, and/or whether it counts as a dupe of several previous, but: it does not seem possible to set environment variables for Jupyter kernels relative to `$workspaceFolder`.

This is of particular relevance when a workspace represents a git repo with some python source code in a subdirectory (an extremely common scenario, yes?) that one would like to be importable from notebooks. The typical solution would be to set `PYTHONPATH` to include this directory. (Ideally, such a configuration could be checked into the repo itself via a `settings.json` or `code-workspace` file...)

This case is well handled for tools to be run via the integrated terminal with a `settings.json` entry; e.g.:
```
    "terminal.integrated.env.osx": {
        "PYTHONPATH": "${env:PYTHONPATH}:${workspaceFolder}/src",
    }
```

However, this setting does not appear to be used by the kernel launcher, nor does the jupyter extension seem to offer a similar setting.

I am aware of the support for `.env` files, but as far as I can tell it only makes sense to put absolute paths into them, which is not really useful or appropriate for something that would be checked into a shared repo. 

This issue can somewhat be worked around by setting `"jupyter.notebookFileRoot": "${workspaceFolder}"` and then appending relative paths to `sys.path` via `jupyter.runStartupCommands`. But that's a bit brittle and convoluted, and loses the benefit of running notebooks relative to their own path.

There are lots of bug reports and SO posts circling this issue but none seem to address the bug/issue/feature request head on -- specifically, why it's critical to be able to specify the PYTHONPATH (and similar environment variables) relative to the workspace, especially for configurations checked into e.g. git repos that wind up in different absolute paths on different machines. Here are a couple of the related issues:
https://github.com/microsoft/vscode-jupyter/issues/11534
https://github.com/microsoft/vscode-jupyter/issues/1467

https://stackoverflow.com/questions/58735256/set-pythonpath-for-local-jupyter-notebook-in-vs-code
https://stackoverflow.com/questions/53275420/how-can-i-set-enviroment-variables-for-data-science-mode-of-vscode

### VS Code Version

1.84.2

### Jupyter Extension Version

v2023.10.1100000000

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
> appropriate for something that would be checked into a shared repo.
> This issue can somewhat be worked around by setting 

Sounds like more of a feature request

> but as far as I can tell it only makes sense to put absolute paths into them,

You can add relative paths in there, 
Have you tried that.
You can also use `${workspaceFolder}` in your .env file.
Please try these two.

**Comment by zpincus** [comment]
> You can add relative paths in there,

Unless I misunderstand something, relative paths in the `.env` file would work, but only in the case that `jupyter.notebookFileRoot` is set to `${workspaceFolder}` and one never changes the cwd in any other fashion.

>You can also use ${workspaceFolder} in your .env file.

This does not seem to be the case?
`.env`:
```sh
FOO=bar
PYTHONPATH=before:${workspaceFolder}:after
```

Then in a local notebook cell:
```python
import os
print(os.environ['FOO'])
print(os.environ['PYTHONPATH'])
```
which produces:
```
bar
before::after
```

**Comment by DonJayamanne** [comment]
Oh yes thats not supported, i thought it was, sorry.
Only relative paths are supported.

**Comment by zpincus** [comment]
I guess this is a feature request then! Should I close this and open another issue as an explicit request for `${workspaceFolder}` support in `.env` files (or similar)?

Fully-resolved paths are obviously not a good solution for config files checked into a shared repo; likewise relative paths are at best brittle and at worst potentially dangerous...

**Comment by DonJayamanne** [comment]
> I guess this is a feature request then! Should I close this and open another issue as an explicit request for ${workspaceFolder} support in .env files (or similar)?

Yes, please however, please create an issue in the Python extension repo
as that extension si responsible for resolving the variables in .env files.
https://github.com/microsoft/vscode-python/issues/

Thanks
