### ISSUE TITLE
Ask users to upgrade their pytorch profiler plugin to support jump to source

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-jupyter#14878]
At the same time when we check to see if PyTorch devs have the profiler plugin installed, we need to also check the version # of the torch-tb-profiler package and prompt users who have the older version to "Upgrade to the latest version of the torch-tb-profiler to access profiler jump-to-source-code"

**Comment by karrtikr** [comment]
It's not clear who owns the data science label, hence moved to Jupyter.
