### ISSUE TITLE
Issue/PR Grooming - review, categorization, assignment

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#14872]
Please follow https://github.com/microsoft/vscode/issues/199906 for guidelines of issue review and categorization. 

# Tracking

## Issues assigned to you

- [x] @amunger 
- [x] @donjayamanne
- [ ] @rebornix 

## Issues assigned to feature areas but without owner

- [x] [`cell-magics`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Acell-magics)
- [x] [`data-viewer`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Adata-viewer)
- [x] [`output-renderer`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aoutput-renderer)
- [x] [`interactive-window`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Ainteractive-window)
- [x] [`interactive-window-debugging`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Ainteractive-window-debugging)
- [x] [`ipywidgets`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aipywidgets)
- [x] [`jupyter-output`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Ajupyter-output)
- [x] [`kernel-management`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Akernel-management)
- [x] [`language-any`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Alanguage-any)
- [x] [`mru`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Amru)
- [x] [`notebook-commands`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-commands)
- [x] [`notebook-context-keys`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-context-keys)
- [x] [`notebook-debugging`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-debugging)
- [x] [`notebook-execution`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-execution)
- [x] [`notebook-getting-started`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-getting-started)
- [x] [`notebook-import-export`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-import-export)
- [x] [`notebook-intellisense`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-intellisense)
- [x] [`notebook-kernel`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-kernel)
- [x] [`notebook-kernel-execution`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-kernel-execution)
- [x] [`notebook-kernel-picker`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-kernel-picker)
- [x] [`notebook-kernel-remote`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-kernel-remote)
- [x] [`notebook-kernel-startup`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-kernel-startup)
- [x] [`notebook-liveshare`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-liveshare)
- [x] [`notebook-markdown`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-markdown)
- [x] [`notebook-output`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-output)
- [x] [`notebook-remote`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-remote)
- [x] [`notebook-run-by-line`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-run-by-line)
- [x] [`notebook-serialization`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-serialization)
- [x] [`notebook-workflow`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Anotebook-workflow)
- [x] [`plot-viewer`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aplot-viewer)
- [x] [`telemetry`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Atelemetry)
- [x] [`tensorboard`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Atensorboard)
- [x] [`variable-explorer`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Avariable-explorer)
- [x] [`vscode-web`](https://github.com/microsoft/vscode-jupyter/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Avscode-web)

## Satellite Repositories

- [x] [vscode-jupyter-ipywidgets](https://github.com/microsoft/vscode-jupyter-ipywidgets)
- [ ] [vscode-jupyter-cell-tags](https://github.com/microsoft/vscode-jupyter-cell-tags)
- [ ] [vscode-jupyter-slideshow](https://github.com/microsoft/vscode-jupyter-slideshow)
- [x] [vscode-notebook-renderers](https://github.com/microsoft/vscode-notebook-renderers)
- [ ] [vscode-jupyter-keymap](https://github.com/microsoft/vscode-jupyter-keymap)
- [x] [vscode-zeromq](https://github.com/microsoft/vscode-zeromq)
- [x] [vscode-jupyter-powertoys](https://github.com/microsoft/vscode-jupyter-powertoys)

**Comment by DonJayamanne** [comment]
> Issues assigned to feature areas but without owner

Not sure how you determine whether they are owned or not, A little confused, lets dicuss tomorrow.
I own some of the areas, e.g. ipywidgets, kernel-management, etc.

**Comment by rebornix** [comment]
@DonJayamanne it's making sure that all issues have owners so they can get triaged. With that said, there might be labels that we don't have clears owners for, which we can discuss in our standup. 

I went through some of above labels and did assignments based on previous ownership assignments.

**Comment by DonJayamanne** [comment]
> I went through some of above labels and did assignments based on previous ownership assignments, and removed the checkboxes for the ones that have no owners yet.

where do we document the owners, and how does one know who owns a label

E.g. i woudll have assumed `ipywidgets` would be clear, as I own that
Guess we need a way to document the lables and the areas they correspond to.

**Comment by amunger** [comment]
closing since we would need a new list if we do something similar again this year
