### ISSUE TITLE
"go to next cell" command

### ISSUE THREAD

**Issue by rholland** [microsoft/vscode-jupyter#1488]
In Don's original plug in there were editor commands to go to the next or previous cell.  I do not see them now.  Could you please add them back.  They are very useful for navigation.

Thanks.

**Comment by greazer** [comment]
I presume this old issue related to the interactive window. Keystrokes to move between python script cells (# %%) are supported. By default Ctrl+Alt+[ and Ctrl+Alt+] navigate up and down a script by cell.
