### ISSUE TITLE
When copying a tab to a new vscode window, jupyter interactive session opens on the old vscode window

### ISSUE THREAD

**Issue by david-cortes** [microsoft/vscode-jupyter#14887]
## Environment data

-   VS Code version: 1.85.0
-   Jupyter Extension version (available under the Extensions sidebar): v2023.11.1003402403
-   Python Extension version (available under the Extensions sidebar): v2023.22.0
-   OS (Windows | Mac | Linux distro) and version: linux (debian 12)
-   Python and/or Anaconda version: 3.11 (conda)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Steps to reproduce:

1. Enable this setting:
![image](https://github.com/microsoft/vscode-jupyter/assets/11860098/a641a55f-637a-440c-8e54-5175f3408659)
2. Open a new vscode window.
3. In the new window, create a python file, write some command on it.
4. Click on the first code line of the file that was created above, and press shift+enter so that it will execute in a jupyter interactive window.
5. Right-click the tab of the file where this line was executed, and select 'Copy into New Window'.
6. In the new window that opens, click the same line as before and press shift+enter.

## Expected behaviour

Should open a new jupyter interactive window in the same vscode window from where the command is being triggered, which in this case is the new window that was created after step 5.

## Actual behaviour

Sends the python line to the jupyter interactive window that was running on the previous vscode window from where the file was copied.

Note that opening a new jupyter interactive window from the command palette also opens it in the old vscode window rather than the new one.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by amunger** [comment]
Interactive Window and notebook editors are not supported in floating windows at this point https://github.com/microsoft/vscode-jupyter/issues/14789
