### ISSUE TITLE
Too much space between one-line-cell

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode-jupyter#1489]
There seems to be too much blank space between cells that only have one line of code. We could move the cell menu up to be on the same line as the "run" button in these cases.
![image](https://user-images.githubusercontent.com/26419852/67111457-c9cd4f80-f189-11e9-8567-39a269554576.png)

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed with new native support for editing notebooks starting with v1.59 of VS Code. If this issue continues to occur in the latest build of VS Code, please reopen or enter a new issue.
