### ISSUE TITLE
Support for geopandas GeoDataFrames in DataViewer

### ISSUE THREAD

**Issue by seflue** [microsoft/vscode-jupyter#14891]
It would be great, if [GeoDataFrames](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.html) would be also supported by the DataViewer.

Converting GeoDataFrames into pandas DataFrames is quite simple:
```
pd_df = pd.DataFrame(gdf)
```
I already found [this comment](https://github.com/microsoft/vscode-python/issues/15527#issuecomment-825319834). So I took a look at the [mentioned approach](https://github.com/microsoft/vscode-jupyter/issues/5590#issuecomment-824473734) to solve this problem, cloned the repo and looked at the code.

And actually, this should already be supported by the following code, shouldn't it?
https://github.com/microsoft/vscode-jupyter/blob/90b109f85402071015d8437ba5a8904b968b7e03/pythonFiles/vscode_datascience_helpers/dataframes/vscodeDataFrame.py#L123-L132

Some help to find out, why it doesn't work and how to actually make it work, would be really appreciated.

**Comment by amunger** [comment]
We are likely going to start relying on external extensions such as [Data Wrangler](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.datawrangler) for providing dataframe viewer functionality. Have you tried that extension to see if it supports what you are looking for?

**Comment by amunger** [comment]
closing as the jupyter data viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486
