### ISSUE TITLE
Straightly convert jupyter format python code (using # %% cells) from/to HTML5

### ISSUE THREAD

**Issue by Xiantongc612** [microsoft/vscode-jupyter#1490]
**If the jupyter python script can be straight forward export as an HTML5, it's really convenient to show our codes to the others and build the documents.** However, current extension have not supported this feature. As the consequence we have to use Pandoc to do so. It makes my workflow not consistent as what I expect.

**Comment by amunger** [comment]
The interactive window can be exported as HTML, is that the expectation here, or is there a reason to want an HTML file that only has cell inputs without any of the results?

**Comment by Xiantongc612** [comment]
Hello, @amunger.
The story of this issue is like, as a developer, I want to export my file as a HTML file, so that it can be used as document.
Currently, the thing I do is like open the interactive environment, restart the kernel, and run all codes.
And sometimes I accidently run the code in a different (maybe trouble-making) order or some hidden variable are set in the interactive environment.
Thus, I wonder if it is possible to give us a button, which can run all codes and export the result as HTML files.

**Comment by amunger** [comment]
fyi - there is a command `Jupyter: run current file in interactive window` to run all code cells, then you could export the results of that command

**Comment by amunger** [comment]
I think the two step `Jupyter: run current file in interactive window` (clearing or closing the IW first) then Export As Html is the closest we are going to get here.
