### ISSUE TITLE
Unable to distinguish stack frames using proposed kernels API

### ISSUE THREAD

**Issue by kycutler** [microsoft/vscode-jupyter#14922]
In the proposed kernel `executeCode` API, tracebacks in error results are concatenated together into one string (despite the underlying messages from the kernel having them split up by stack frame). This makes it difficult / generally impossible to distinguish each stack frame when using the new API.

For example, executing the code:
```python
def div(a, b):
  return a / b
div(1, 0)
```

The Jupyter `error` message directly from the kernel gives:
```json
{
  "ename": "ZeroDivisionError",
  "evalue": "division by zero",
  "traceback": [
    "---------------------------------------------------------------------------",
    "ZeroDivisionError                         Traceback (most recent call last)",
    "Cell In[1], line 3\n      1 def div(a, b):\n      2   return a / b\n----> 3 div(1, 0)\n",
    "Cell In[1], line 2, in div(a, b)\n      1 def div(a, b):\n----> 2   return a / b\n",
    "ZeroDivisionError: division by zero"
  ]
}
```

Notice that each stack frame in the traceback is contained in its own string in the array. Also note that the stack frames themselves may contain multiple lines.

But executing the same code with the new API and parsing the data from the `application/vnd.code.notebook.error` output gives:
```json
{
  "name": "ZeroDivisionError",
  "message": "division by zero",
  "stack": "---------------------------------------------------------------------------\nZeroDivisionError                         Traceback (most recent call last)\nCell In[2], line 3\n      1 def div(a, b):\n      2   return a / b\n----> 3 div(1, 0)\n\nCell In[2], line 2, in div(a, b)\n      1 def div(a, b):\n----> 2   return a / b\n\nZeroDivisionError: division by zero"
}
```

Here the stack frames have all been joined together, and it is generally infeasible to split them back out. We need to be able to distinguish the stack frames so that we can exclude some frames before displaying to the user.

**Comment by DonJayamanne** [comment]
Please use the following approach
```typescript
let output: NotebookCellOutput
const oldTraceback = output.metadata.originalError.traceback
```

This is guaranteed to work, we store the original error as `originalError` in the metadata of the error output item.

**Comment by DonJayamanne** [comment]
@kycutler @pwang347

The API has changed
* kernel execution now returns an enumerable of `Outupts`, this as the individual output items as well as the metadata associated with the output
* In the case of errors, please use the metadata to access the originalError.tracback as follows
`output.metadata.originalError.traceback`, where `output` is the output returned by the execution method.
You can access the individual items in the output using the `items` property
