### ISSUE TITLE
simplify the UI of Notebook Editor

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#1493]
The new Notebook Editor is an amazing new data science feature in vscode for sure. I'd like to make some suggestions in terms of its user interface, however.

1. the buttons between the input and output cells is very disturbing
![Snipaste_104](https://user-images.githubusercontent.com/33796896/67168248-5a658480-f370-11e9-8b6a-649c2acfb2a9.png)
The gap between them also looks a little bit weird. I haven't seen any Jupyter user interface designs that put something between the inputs and outputs. Could you guys please consider moving them to the top?
![Snipaste_321](https://user-images.githubusercontent.com/33796896/67168265-a3b5d400-f370-11e9-8b1a-0e42c4bf8fe1.png)

2. I don't think it is necessary to break the vertical bar into two bars and add an indentation for the output cell. I think the background color of the cell already indicates one is cell and another one is the output area. The color change while editing a cell also seems unnecessary since you literally can see your cursor there. I suggest we align them like Jupyter Lab or add a shadow like Colab.
![image](https://user-images.githubusercontent.com/33796896/67168319-8a615780-f371-11e9-973a-81ef30d6527c.png)
![image](https://user-images.githubusercontent.com/33796896/67168331-a238db80-f371-11e9-89dd-b708becfe7f1.png)
![image](https://user-images.githubusercontent.com/33796896/67168922-21301300-f376-11e9-8118-6ac67543d597.png)
![image](https://user-images.githubusercontent.com/33796896/67168615-4c196780-f374-11e9-9fb5-733f42e5e8b9.png)

There are just way too many elements in the Editor.
![image](https://user-images.githubusercontent.com/33796896/67169067-07430000-f377-11e9-971e-c55dd6047ac8.png)

Please consider making it as simple as Jupyter Lab where all the buttons are on the top and nothing is around your code and output except the runtime order number.
![image](https://user-images.githubusercontent.com/33796896/67169141-8801fc00-f377-11e9-8724-8ecda6a60b18.png)

**Comment by claudiaregio** [comment]
Closing as new UI is coming with Native Notebooks
