### ISSUE TITLE
%matplotlib widget -- display(fig.canvas) is blank but not display(fig)

### ISSUE THREAD

**Issue by keriheuer** [microsoft/vscode-jupyter#14932]
## Environment data

-   VS Code version: 1.85.0
-   Jupyter Extension version: v2023.11.1003402403
-   Python Extension version: v2023.22.1
-   OS and version: macOS Sonoma 14.1
-   Python and/or Anaconda version: Python 3.11
-   Type of virtual environment used: conda
-   Jupyter server running: Local 

## Expected behaviour

In Google Colab using the `%matplotlib widget` I can use `display(fig.canvas)` with `ipywidgets` since `fig.canvas` is a Jupyter widget but not the parent `fig` object. The matplotlib figure will still appear with both `display(fig.canvas)` and `display(fig)` commands.

## Actual behaviour

Calling `display(fig.canvas)` in my Jupyter notebook in VSCode only shows the axes, ticks, and tick labels. None of the matplotlib artists plotted appear. In contrast, everything shows up when I call `display(fig)`.  `display(fig.canvas)` doesn't bring up any errors, but the plot shows up blank, even though clearly things were plotted to it as seen with the `display(fig)` command. How to fix this? I need the plot to show on `display(fig.canvas)` so I can use it in commands like `display(ipywidgets.HBox([fig.canvas, fig2.canvas]))`.

Attached are screenshots showing the difference between the 2 outputs:

`display(fig.canvas)` 
<img width="1404" alt="Screenshot 2023-12-19 at 12 33 42 PM" src="https://github.com/microsoft/vscode-jupyter/assets/54902150/fc522fca-08fc-45c6-a416-a3ae3af54385">

`display(fig)`
<img width="1362" alt="Screenshot 2023-12-19 at 12 33 53 PM" src="https://github.com/microsoft/vscode-jupyter/assets/54902150/e241d4c3-877f-416c-81fd-d85f157fce4f">

## Steps to reproduce:

Here's a minimal (simpler) example of my code to reproduce this:

```
import numpy as np
import matplotlib.pyplot as plt

%matplotlib widget
plt.ioff()

#variables
colors = plt.cm.cool(np.linspace(0, 1, 3))
delays = np.arange(0, 150, 50)
yticks = [7.5 + (2.5 * i) for i in range(3)]

# create figure
fig, ax = plt.subplots(layout='compressed', figsize=(8,5))
fig.canvas.toolbar_visible = False
fig.canvas.header_visible = False
fig.canvas.footer_visible = False
fig.canvas.resizable = False

# adjust fig layout
ax.margins(x=0.02, y=0.2)
ax.tick_params(which="both", axis="y", left=False, labelleft=True)
ax.tick_params(which="both", axis="x", top=True)

# set initial tick labels
ax.set_xlabel('Angle [rad]')
ax.set_yticks(yticks)
ax.set_yticklabels([r'Original ($x_1$)'] + [r'$x_%d = x_1 + %d\tau$' % (i+2, i+1) if i != 0 else r'$x_2 = x_1 + \tau$' for i in range2)])

# generate some fake data to plot
x = np.linspace(-np.pi, np.pi, 201)
sine = np.sin(x)

# plot first sine wave
ax.plot(x, sine+7.5, color="#dd1c77")
delay_labels = []

# add additional sine waves with an x-offset to plot
delay = np.pi
for i in range(3):
  i += 1
  y_offset = 2.5 * i
  x_offset = delay * i
  color = colors[i-1]
  line, = ax.plot(x+x_offset, sine+y_offset)

# this shows only a blank plot 
display(fig.canvas)

# this shows the full plot with the sine waves
display(fig)
```

**Comment by DonJayamanne** [comment]
I'm sorry you are running into this issue and thanks for filing this issue, 

However this works for me.

> In Google Colab using the %matplotlib widget I can use display(fig.canvas) with ipywidgets since fig.canvas is a

From my understanding Colab is running in the cloud and VS Code is running locally. thus you aren't testing the same things.
Its most likely there's something wrong in your local setup.
I'd suggest installing Jupyter Lab locally `python -m pip install jupyterlab`
Then running the same code against the exact same python environment and testing it.

Please let me know how this goes, given thsi works for me I'm failrly certain this is an issue at your end hence clsoing this.
However if you can get this working in JupyterLab and not vscode, please do ping here and I'd be happy to reopen this issue or feel free to file a new issue.
