### ISSUE TITLE
Ideas for DataScience cell promotion

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1494]
Feedback from a customer:

Scenario:
Code that starts off from Data Exploration ends up a mess because the code is a tool, not the goal.
When you switch to deploying to a pipeline, code producing a robust output is now the goal.

There is a difference in task. I believe I do the tasks one at a time, but not in a waterfall. I don’t stop “data Exploration” once I’m “cleaning up”. I go back and forth in loop. In one case I’m learning about the data. In the other I’m trying to ensure a transform on the data is correct and robust.

I think the switch in task is precisely analogous to coding + debugging vs refactoring + unit testing.

What I want: 
Tools to update cells into production code: ‘refactor’, ‘test’, but allowing me to immediately jumping back to Data Exploration. My UI ‘gesture’ of reseting the interpreter is my ‘Run a validation test against this’ from a clean state.

I want to take a single cell (or maybe a small set of cells), ensure it does the right processing step and will continue to do so, is reusable, and then move it out of the visible mainline ‘Exploration’ set of cells.  However there is an overlap of moving it out and still fixing issues with it.  I want to be free to fix issues with code I’ve mentally moved out of the “DataExploration” without necessarily doing a full reset.

The “autoreload” I want: 
I want the tool to understand For those cells in the process of becoming reusable interpret the literal contents at the time I run. (Because those cells are in still in flux.)

The things in autoreload that I don’t want: I don’t want to be reloading things that I am not changing.   I want the ‘blast radius’ small enough that I trust the tool to do what mean.

Some other ideas from the analgous to refactoring / unit testing:
•	Look at what the old ‘Data Dude’ skew for VS did long ago with snapshotting representative data to enable ‘unit testing’ a database.
o	I think a tool to generate a small literal dataset to unit test the processing step of a cell would be valuable.
•	See if my use of autoreload really can work .. and if so what causes Steve Steiner to give up on it as not worth it after at least 3 tries.
•	Make a high level ‘refactoring’ style commands of ‘Move cell to separate file’, ‘Create test for cell’.

**Comment by DonJayamanne** [comment]
Closing this as tyhere haven't been any upvotes or activity in this issue for over 2 years
