### ISSUE TITLE
Hovering on variables once a jupyter session starts should reflect the value of the variable.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1495]
Multiple users in a usability study attempted this.

**Comment by ldorigo** [comment]
+1,  this is a major productivity boost in IDEs that support it. Alternatively, displaying variable values inline (which vscode already does when debugging) could also be useful

**Comment by DonJayamanne** [comment]
Its been a while since this issue has been opened and we haven't received enough comments nor upvotes on this issue
Hence closing this issue for now
