### ISSUE TITLE
remote jupyter server list have the same server name "Existing Jupyter Server.." for all servers

### ISSUE THREAD

**Issue by TTTPOB** [microsoft/vscode-jupyter#14953]
## Environment data

-   VS Code version: 1.85.1
-   Jupyter Extension version (available under the Extensions sidebar): V2023.11.1003402403
-   Python Extension version (available under the Extensions sidebar): v2023.22.1
-   OS (Windows | Mac | Linux distro) and version: centos7
-   Python and/or Anaconda version: 3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: remote
## Expected behaviour

remote server list stores the name I typed in

## Actual behaviour

![image](https://github.com/microsoft/vscode-jupyter/assets/19909103/6679a3cb-82ad-4c0c-bff5-5839092178ad)

I have tried to clear remote server list and reconnect, issue remained. previously I have three different jupyter server, they all appear as "Existing jupyter server.." now

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. connect to a remote server with address, password and name
2. reload vscode window
3. select kernel for notebook, choose existing server to get server list
4. see the bug

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
see attached
```
[jupyter.log](https://github.com/microsoft/vscode-jupyter/files/13747664/jupyter.log)

</p>
</details>

**Comment by TTTPOB** [comment]
update: downgrade to `2023.10.100`, there is no such issue

**Comment by youurayy** [comment]
It's just unbelievable how bad the remote kernel Jupyter support still is in VSCode. I'm clicking the "Existing Jupyter Server..." and it does nothing.

**Comment by DonJayamanne** [comment]
Sorry you are running into this issue, I've identified the problem and will try to get a fix out soon.

**Comment by DonJayamanne** [comment]
@youurayy @TTTPOB 
Sorry you are running into this issue, we've identified the fix and its available in the latest pre-release version of the extension
However you need to install VS Code insiders for this.
Please let me know if it works there, (please note, the server name isn't displayed in the MRU yet, that will be fixed soon)
