### ISSUE TITLE
Feature request (FR): ability to print python interactive window content

### ISSUE THREAD

**Issue by dsanalytics** [microsoft/vscode-jupyter#1496]
Hi, 

It'd be great if we could print the entire python interactive window content with 3 options:
1) cell inputs hidden 
2) cell inputs shown collapsed 
3) cell inputs shown expanded
Great for generating ad-hoc reports for business and/or saving output for oneself while algo designing/prototyping.

Ideally, this extension would first implement hide input cells option, i.e. the 3rd one along with already existing 2 (collapse/expand input cells), so that printing option would simply just print what's already shown in the interactive window. Input cells are informative, but would look unprofessional in a report produced for business folks.

This feature would be one great enhancement! Thanks in advance.

Environment: 
Windows 7 SP1 64bit Home Premium
VSCode v1.33.0
Python 3

**Comment by amunger** [comment]
this would be better in a separate extension
