### ISSUE TITLE
Cell output height is not shrinked until cell execution completes

### ISSUE THREAD

**Issue by stas-sl** [microsoft/vscode-jupyter#14960]
## Environment data

-   VS Code version: Version: 1.85.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.11.1003402403
-   Python Extension version (available under the Extensions sidebar): v2023.22.1
-   OS (Windows | Mac | Linux distro) and version: Local: MacOS Ventura 13.4.1
-   Python and/or Anaconda version: Python 3.11.7, miniconda3-3.11-23.11.0-2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pyenv, miniconda
-   Jupyter server running: Local

## Expected behaviour

I would expect it to behave like Jupyter lab, so that when you run a cell, all previous output is cleared and output height is truncated:

https://github.com/microsoft/vscode-jupyter/assets/4602302/f5013645-52bd-4075-85c7-fd987755e5ff

## Actual behaviour

If there is a long running cell that has a lot of output, or if you interrupt it and there is large stack trace, then on subsequent cell reruns there remains quite large empty space until execution completes.

https://github.com/microsoft/vscode-jupyter/assets/4602302/cb50fd13-65aa-40e7-82fd-fdfc8d67b5b9

**Comment by amunger** [comment]
This was changed by design to reduce the amount of scrolling as cells are re-executed, especially for situations such as this: https://github.com/microsoft/vscode/issues/193835

**Comment by stas-sl** [comment]
Hmm, ok, I see that there is long history behind this issue, and there are a few related but different scrolling/anchoring artifacts. I admit, I haven't studied them all, and I don't know implementation details, probably for some issues this fix works well, but in this particular case it looks quite questionable to me. 

First, if you run a cell for the first time, its output will still grow, so you will still have that scrolling, which you should handle somehow. 
Second, even on second re-run, output might be longer, so again you still can't avoid scrolling.

In one of the issues (https://github.com/microsoft/vscode/issues/196465) you said:

> The whitespace is just holding the position for the output to re-appear and reduces the amount of jumpiness while re-executing cells.

You are probably assuming that the new output will be of the same size as previous one, but it's surely not guaranteed. For example you might run a cell and by mistake it produced huge output, so you quickly corrected your mistake and re-run the cell, but it could take long time to execute and you will be left with annoying whitespace all that time, until execution finishes.
