### ISSUE TITLE
Tolerance of ipython cell magics in source code cells

### ISSUE THREAD

**Issue by rben01** [microsoft/vscode-jupyter#1497]
## Environment data

- VS Code version: 1.27.1
- Extension version: 2018.8.0
- OS and version: macOS 10.14
- Python version: Anaconda Python 3.6
- Type of virtual environment used: conda
- Relevant/affected Python packages and their versions: N/A

## Actual behavior

When using a python file as a makeshift Jupyter notebook (with use of the VSCode Jupyter extension), valid ipython kernel code is flagged as invalid by the Python parser. For instance, cell magics, which begin with one or two percent signs, are flagged as syntax errors

## Expected  behavior

The parser should ignore valid ipython cell magic syntax; flagging these as problems just adds noise. A good solution might be to have the Python extension have its own internal Jupyter flag, which when enabled would understand that ipython cell magics are syntactically correct, but when disabled would treat the file as vanilla Python for the purpose of checking syntax.

## Steps to reproduce:
Write e.g., `%matplotlib inline` at the top of the file.

**Comment by DonJayamanne** [comment]
Moving back to new issues to triage.
We can contribute to pylance & jedi or just swallow these messages from the middle man.

**Comment by rben01** [comment]
I think this can be closed, as it looks like the python extension now supports this via comments that begin with `#!`, e.g., `#! %matplotlib inline`.

**Comment by rebornix** [comment]
I wonder if we should filter out these set of errors in the notebook language client middleware, @rchiodo do you think that's the right layer?

**Comment by rchiodo** [comment]
@rebornix, yes I think so. I believe we have another issue we're we recommended just that:

#6635

**Comment by rchiodo** [comment]
Sorry closed prematurely. This issue is I believe about magics in python files, not notebooks. Python files would not be handled by the middleware piece we have. Although maybe we'd do something similar.

**Comment by rchiodo** [comment]
Closing for now as the workaround described above should work. Otherwise we'd have to special case python files with cell markers.
