### ISSUE TITLE
Getting stuck when starting to debug a notebook cell

### ISSUE THREAD

**Issue by moesphere** [microsoft/vscode-jupyter#14979]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Debugging of a notebook cell is stuck forever when started.
This is related to [issue 13349](https://github.com/microsoft/vscode-jupyter/issues/13349).

MWE (debug random python function in cell):
```
slice()
```

### VS Code Version

Version: 1.85.1 Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2 Date: 2023-12-13T09:49:37.021Z Electron: 25.9.7 ElectronBuildId: 25551756 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Windows_NT x64 10.0.19044

### Jupyter Extension Version

v2023.11.1003402403

### Coding Language and Runtime Version

Python v3.10.12

### Language Extension Version (if applicable)

Pylance v2023.12.1

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
@moesphere sorry you are running into this issue.
Please can you share more information than `this is related toxxx`
* Please can you providce steps to repro the issue
* Please can you share the logs as follows

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by nataziel** [comment]
@DonJayamanne this is likely a duplicate of https://github.com/microsoft/vscode-jupyter/issues/14958

**Comment by moesphere** [comment]
Yes, it is a duplicate of [#14958](https://github.com/microsoft/vscode-jupyter/issues/14958).

I am experiencing the same as mentioned in the issue: If I switch to a different python version, it works.

I will comment in the original issue.
