### ISSUE TITLE
Can't use http proxy with interactive window

### ISSUE THREAD

**Issue by damienrj** [microsoft/vscode-jupyter#1498]
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

Steps to Reproduce:

1. Attach to container
2. Install Python Extension
3. Try to connect to service behind proxy (sent as environment variable)

I understand that 

> Local proxy settings are not reused inside the container, which can prevent extensions from working unless the appropriate proxy information is configured (for example global HTTP_PROXY or HTTPS_PROXY environment variables with the appropriate proxy information)

So I set the proxies in /etc/profile.d in the containers, and this works for ipython but not the interactive python.  Is there a way to configure the proxy for interactive python in a container?

**Comment by DonJayamanne** [comment]
@damienrj I'm sorry we didn't get to you on this issue for a while.
I'm certain you can now setup the env  variables in the `.env` file and this will work.
If it does not work, please feel freel to file an an issue or re-open this and we'll look into this.
Once again, i'm sorry we never got back to you on this.
