### ISSUE TITLE
When removing duplicated completion items, items with rich documentation end up getting removed as well.

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#14983]
Assume Kernel returns the completion item `aggregate` and on resolve we get additional documentation for this
& pylance returns `aggregate` and on resolve we do not get additional documentation for this

As `aggregate` is returned by `pyalcne` Jupyter will remove that item from the completions and user will only see one `aggregate`  (the one returned by Pylance).

This isn't ideal, as users now lose the documentation, and end up with a less richer completion item.

Example is 
```python
# Cell 1
import pandas as pd
data = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
        'age': [25, 30, 35, 40],
        'city': ['New York', 'Paris', 'London', 'Tokyo']}
df = pd.DataFrame(data)

# Cell 2 
# Completion for `aggregate` and `agg` returned by Jupyter kernel is better than that returned by Pylance
df.ag
```

<details>
  <summary>Here's what we get from Pylance</summary>
  
![Screenshot 2024-01-05 at 08 25 35](https://github.com/microsoft/vscode-jupyter/assets/1948812/dc7fe0ee-b90d-4e62-bbb4-4a836a00040e)

</details>

<details>
  <summary>& here's what we get from the Jupyter kernel</summary>
  
![Screenshot 2024-01-05 at 08 25 45](https://github.com/microsoft/vscode-jupyter/assets/1948812/610a6a2f-995d-4d18-b0a9-7be684d2654a)

</details>

@luabud /cc

**Comment by luabud** [comment]
Chatted with @bschnurr briefly about this. It seems we're failing to get the dosctrings from agg and aggregate specifically (Pylance was supposed to show the docs too in that case).

**Comment by luabud** [comment]
so Pylance fails to show docstrings in these cases because they're not in the source: 
![image](https://github.com/microsoft/vscode-jupyter/assets/45497113/5c523ee4-0a10-45f5-b34d-da12ca48c11e)

they're in `shared_docs`:
![image](https://github.com/microsoft/vscode-jupyter/assets/45497113/261d86d5-a7a2-4323-9ad0-f0004e745e0d)

I wonder if the de-dupe could be done by VS Code instead of the Jupyter extension? If there are multiple providers offering similar suggestions then VS Code could pick the "best"?

**Comment by DonJayamanne** [comment]
> I wonder if the de-dupe could be done by VS Code instead of the Jupyter extension? If there are multiple providers offering similar suggestions then VS Code could pick the "best"?

Not sure that would work, that would be a feature request
& unlikely, as the documetnation is provided lazily, i.e. VS Code will never know which item is better.

Question> Why can't pylance get the docs from the shared_docs.py file?

**Comment by luabud** [comment]
We can, it's just not something we currently support. We seem to be only failing to show docstrings for methods introduced in the latest versions of Pandas. We created an issue on the Pylance side to track this improvement.

**Comment by DonJayamanne** [comment]
Thanks, Do you have a link to that issue

**Comment by DonJayamanne** [comment]
Closing in favour of the upstream Pylance issue

**Comment by luabud** [comment]
https://github.com/microsoft/pylance-release/issues/5334
