### ISSUE TITLE
Go to Definition in Notebook Editor

### ISSUE THREAD

**Issue by mogwai** [microsoft/vscode-jupyter#1499]
# Feature: Notebook Editor

## Description

Would it be possible to use the python language server to create links to definitons of classes/methods in notebooks? This would make it a powerful environment.

**Comment by Xemnas0** [comment]
This would indeed be very useful. Thank you

**Comment by VigneshBaskar** [comment]
Any updates on this please?

**Comment by Bornatch** [comment]
Would be great!

**Comment by claudiaregio** [comment]
This is available today with Native Notebooks in VS Code Insiders!
Download to try it out today :)


![gotodef](https://user-images.githubusercontent.com/19276747/120092391-2cf1c880-c0c7-11eb-86fe-308bb7dc6048.gif)

**Comment by KeremTurgutlu** [comment]
> This is available today with Native Notebooks in VS Code Insiders!
> Download to try it out today :)
> 
> ![gotodef](https://user-images.githubusercontent.com/19276747/120092391-2cf1c880-c0c7-11eb-86fe-308bb7dc6048.gif)

I don't think this is the same feature requested. Jupyter already has `?` or `??` to display the signature and definition. What we want is to be able to `Go To Definition` similar to `.py` files :D

**Comment by vrnvorona** [comment]
I was shocked that is not default functionality. Makes code inspection literally impossible compared to regular python files or working from IntelliJ IDEs.

**Comment by joyceerhl** [comment]
@vmvorona We offer clicking to go to definitions of classes and functions (including library code) in the preview native notebooks editor that @claudiaregio described. We plan to roll out the new native notebooks editor as the default soon, but in the meantime, please feel free to try it out in VS Code Insiders.

**Comment by greazer** [comment]
Based on this issue thread, goto definition used to work in a notebook. It doesn't appear to in v1.59. So marking as regression for now.

**Comment by greazer** [comment]
After reading through and trying these scenarios with the latest builds of VS Code and Jupyter, I believe all of this works. If there's still something you think we're missing, please open a new bug with further details. 

Thank you for the feedback!

**Comment by VigneshBaskar** [comment]
I can confirm Go To Definition works in the latest build using F12. Thank you!
