### ISSUE TITLE
Environment variable used to set other environment variables in kernel.json was not substituted

### ISSUE THREAD

**Issue by lrtfm** [microsoft/vscode-jupyter#15007]
The jupyter doc says:

> __env__ (optional): A dictionary of environment variables to set for the kernel. These will be added to the current environment variables before the kernel is started. Existing environment variables can be referenced using ${<ENV_VAR>} and will be substituted with the corresponding value. Administrators should note that use of ${<ENV_VAR>} can expose sensitive variables and should use only in controlled circumstances.

When I set $PATH in the json file like this:
```
"PATH": "/my/path/to/some/bin:${PATH}"
```
the value of PATH will be 
```
'/my/path/to/some/bin:${PATH}'
```
where `${PATH}` is not substituted.

A complete example of the json file is like this:
```
cat kernel.json 
{
 "argv": [
  "/my/path/to/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "my-venv",
 "env": {
  "OMP_NUM_THREADS": "1",
  "PATH": "/my/path/to/some/bin:${PATH}"
 },
 "language": "python",
 "metadata": {
  "debugger": true
 }
}
```

## Environment data

-   VS Code version: November 2023 (version 1.85)
-   Jupyter Extension version (available under the Extensions sidebar): v2023.11.1100101639
-   Python Extension version (available under the Extensions sidebar): v2023.22.1
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: Python 3.11.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: N/A

## Expected behaviour

PATH in notebook is expected to be 
```
'/my/path/to/some/bin:/my/old/path/to/bins'
```

## Actual behaviour

PATH in notebook is be 
```
'/my/path/to/some/bin:${PATH}'
```
where `${PATH}` is not substituted.

**Comment by DonJayamanne** [comment]
Does this work in classic Jupyter?

**Comment by lrtfm** [comment]
> Does this work in classic Jupyter?

Yes, it works if I start a jupyter server and then connect the server from browser.

**Comment by DonJayamanne** [comment]
Thanks for the confirmation
<details>
  <summary>Internal Notes</summary>
  
See `KernelProvisionerBase.__apply_env_substitutions`

</details>

**Comment by connor4312** [comment]
Can you share steps for this? I tried adding the `env` section from the reporter in my kernel spec, but running

```
import os
print(os.environ['OMP_NUM_THREADS'])
```

doesn't shown anything

**Comment by DonJayamanne** [comment]
Steps
* Create a Python virtual env named `.venv` in you workspace folder using the Python extension commands
* Activate the above env and install IPyKernel into this env
* Run the following in the terminal after you have activated and installed ipykernel
```
python -m ipykernel install --sys-prefix --env PATH '${PATH}:/Users/donjayamanne/demo/sample' --name testing  
```

Replace `/Users/donjayamanne/demo/sample` some some valid path
And replace `:` with `;` if testing on windows.
* This will create a kernelspec named `testing` in your virtual env (in `.venv/shared/jupyter/kernels/testing/kernel.json`)
* Optionally create the file `.venv/shared/jupyter/kernels/testing/kernel.json` with the following contents 
```json
{
 "argv": [
  "/Users/donjayamanne/demo/.venv/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "testing",
 "language": "python",
 "metadata": {
  "debugger": true
 },
 "env": {
  "PATH": "${PATH}:/Users/donjayamanne/demo/sample"
 }
}
```
* Open a notebook, select the above Kernel (`Jupyter Kernels => testing`)
* Run a cell with the code 
```python
import os
os.environ["PATH"]
```
* Verify the path you provided is included
* Verify the path variable `${PATH}` has been replace with the value for `PATH` env variable (in the past this value woudl appear as is)
