### ISSUE TITLE
Denser notebook display

### ISSUE THREAD

**Issue by morags** [microsoft/vscode-jupyter#15013]
Notebooks displayed in VS Code take considerably more vertical space than those displayed in JupyterLab.

Compare JupyterLab:
![תמונה](https://github.com/microsoft/vscode-jupyter/assets/5771389/7ed556d8-0ed1-4b5e-849c-88c5dfff6825)

With VS Code:
![תמונה](https://github.com/microsoft/vscode-jupyter/assets/5771389/de286405-3522-40ea-800a-c8cb4f1afb9a)

It would be useful to have user-adjustable settings for padding, margins, row height, etc., so users can customize the display to be more or less dense.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
