### ISSUE TITLE
Notebook code cell wraps regardless of toggle word wrap setting

### ISSUE THREAD

**Issue by shahinrostami** [microsoft/vscode-jupyter#1501]
# Bug: Notebook Editor, Interactive Window, Python Editor cells

## Steps to cause the bug to occur
1. Edit a Jupyter Notebook through VSCode, and enter enough code into a cell such that you would expect one of two outcomes:
- The line wraps to the next
- The line overflows

## Actual & Expected behavior
Actual:
- A code cell wraps regardless of the setting below.
<img width="570" alt="Screenshot 2019-10-16 at 21 01 13" src="https://user-images.githubusercontent.com/15690380/66954551-8d4e0680-f058-11e9-93db-9da471507ac8.png">
<img width="1037" alt="Screenshot 2019-10-16 at 21 04 55" src="https://user-images.githubusercontent.com/15690380/66954612-a3f45d80-f058-11e9-8f2a-b27fa5d9df8f.png">

Expected:
- The View -> Toggle Word Wrap setting is used to determine whether the line wraps or overflows

### Your Jupyter and/or Python environment
*Please provide as much info as you readily know*
- **Jupyter server running:**                       Local
- **VS Code version:**                                1.40.0-Insider
-**Python plugin version:**                         2019.11.42782-dev
- **Python and/or Anaconda version:**     Anaconda 2019.7, Python 3.7.3 64-bit
- **OS:**                                                     Mac
- **Virtual environment:**                          conda

**Comment by thakkarparth007** [comment]
@rchiodo, the new notebook experience does allow line wrapping, but it has to be set individually for every cell rather than a global setting. It'd be good to have every a global setting for this.

**Comment by rchiodo** [comment]
> @rchiodo, the new notebook experience does allow line wrapping, but it has to be set individually for every cell rather than a global setting. It'd be good to have every a global setting for this.

This is unexpected. Can you show a screen shot? It works for me in the editor. Maybe you're referring to the output though.
![wordwrap](https://user-images.githubusercontent.com/19672699/107547627-823eb400-6b82-11eb-82d5-8a0283fc8c71.gif)

**Comment by thakkarparth007** [comment]
I see, you're using the global setting whereas I was using Alt+Z shortcut which works on a cell level basis. I'd been used to that shortcut in text editors and expected the same to continue in notebooks (with all cells).

![vscode-notebook-wrapping](https://user-images.githubusercontent.com/747423/107554901-8b6c6700-6bfc-11eb-8bfc-527f480bb40a.GIF)

(interestingly, Github doesn't let me upload files ending in .gif, but is okay with .GIF -- casing seems to matter. But that's for another repository I guess)

**Comment by GarretOConnell** [comment]
+1 for this feature. also being able to set fixed cell widths would be helpful for standardizing line lengths (e.g. to PEP8)

**Comment by mysticaltech** [comment]
Folks, just want to let you know that working with jupyter in vscode has now become "orgasmic". Just makes my life simpler! Whoever did this, just thank you.

**Comment by IanMatthewHuff** [comment]
New Editor UI has resolved this issue as it uses full VS Code editor instances.
