### ISSUE TITLE
Notification for Cell Execution

### ISSUE THREAD

**Issue by ahmadmustafaanis** [microsoft/vscode-jupyter#15039]
When a Cell is executed in Google Colab, it gives a notification for execution (Successfully or Failed).
![image](https://github.com/microsoft/vscode-jupyter/assets/47111429/1db44fbe-c4cc-4619-af2f-2d05f0eb2633)

Since VS Code is also based on Chrome, I believe it should be possible to add such a notification in VS Code Jupyter notebook for Cell Execution.

**Comment by DonJayamanne** [comment]
Thanks for filing this feature request, will look into this.

**Comment by ahmadmustafaanis** [comment]
Thank you, kindly let me know if I can also contribute in it.  My JS is not very good though, can we do it with `window.alert` or something similar?

**Comment by DonJayamanne** [comment]
Given the fact taht there haven't been any upvotes nor any other similar issues, I'm closing this issue as not planned.
