### ISSUE TITLE
Notebook Editor ignores remapped Esc key

### ISSUE THREAD

**Issue by sholderbach** [microsoft/vscode-jupyter#1503]
# Bug: Notebook Editor ignores the remapping of Esc onto caps lock under Ubuntu

## Steps to cause the bug to occur
1. Remap the `Caps Lock` key as an additional `Esc` via gnome-tweaks
2. Enable `"keyboard.dispatch": "keyCode"` to circumvent the problems with key remapping in the normal VS code editor
3. Try to exit the cell edit mode of the Notebook editor via the `Esc` on the remapped key

## Actual & Expected behavior
Escpected: The `"keyboard.dispatch": "keyCode"`setting is respected and the press of the remapped `Esc` results in leaving jupyter edit mode.

Result: only the original `Esc` leaves the jupyter edit mode of the cell, pressing the remapped `Esc` jupyter remains in edit mode. (`CAPS LOCK` is not activated!)

### Your Jupyter and/or Python environment
- **Jupyter server running:**                       Local
- **Extension version:**                               2019.10.41019
- **VS Code version:**                                1.39.2
- **Setting python.jediEnabled:**               true
- **Python and/or Anaconda version:**     3.7.1
- **OS:**                                                    Linux (distro): Ubuntu 18.04 LTS
- **Virtual environment:**                          conda

**Comment by IanMatthewHuff** [comment]
Resolved by new Editor UI
