### ISSUE TITLE
Setting default interpreter for new notebooks

### ISSUE THREAD

**Issue by thomasaarholt** [microsoft/vscode-jupyter#15032]
The "regular" VSCode Python extension lets you set the path of the python interpreter in following manner in a `.vscode/settings.json` file or in general user settings:
```json
{
    "python.defaultInterpreterPath": ".venv/bin/python"
}   
```
This means that by default, any python functionality will use that environment.

The Jupyter extension doesn't seem to respect this setting. 

If I create a new virtual environment (full repro below) with the above setting.json, new notebooks in VSCode ask me to select an interpreter when I run run a cell in the notebook:
<img width="1728" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/2721423/728062e2-923d-48b4-a913-bda95193b05c">

If I set the interpreter in one notebook, and then open another, I still need to select the interpreter on the first cell run, but with a slightly different menu. Here the venv is already suggested as the first option:
<img width="1728" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/2721423/8b6a11c6-de54-4520-a573-8b092c5fdb2c">

Is there a setting I can set so that this setting is already selected for a new notebook in a new environment, so that I do not have to select an interpreter at all?

### Full repro for testing this behaviour:
```bash
# create and cd into folder for the python project
mkdir jupyter-test
cd jupyter-test

# make a python virtual environment in a .venv folder
python  -m venv .venv

# create a file at `.vscode/settings.json` setting the python interpreter path
mkdir .vscode
echo '{"python.defaultInterpreterPath": ".venv/bin/python"}' > .vscode/settings.json

# open vscode, and make a new notebook
code .
Cmd + Shift + P 'Create: New Jupyter Notebook'
```

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, we are currently working on a solution for this item.
There are two solutions we have come up with
* Hide all of the unwanted python environments
    * First open a Jupyter notebook (we need the Jupyter extension to first get activated)
    * Go into you settings file (user settings to make the changes globally, or workspace for settings to apply to a worksapce)
    * Edit the setting `"jupyter.kernels.excludePythonEnvironmentsx": [<....>]`
    * Add paths to environments you wish to hide from the list (intellisense should kick in providing auto completions)
* Optionally, install an extension that changes the kernel of notebooks to point to the active Python env (the one setup using Python extension)
    * Install latest vs code insiders (unfortunately the extension only works in latest insiders version, will be in stable in the next release)
    * Install the latest pre-release version of the Jupyter extension (you must install pre-release version as that has a change to make this possible)
    * Finally install this extension https://marketplace.visualstudio.com/items?itemName=donjayamanne.vscode-default-python-kernel
    * More notes on the usage can be found on the readme of the extension

Please let me know how this goes

**Comment by DonJayamanne** [comment]
Closing as completed
