### ISSUE TITLE
Allow ms-vscode-dscopilot-agent the ability to call proposed apis. 

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#15044]
Currently I'm getting this popup: 
![image](https://github.com/microsoft/vscode-jupyter/assets/11685408/3f4862da-f589-44d9-b8d3-86f99ba283dd)

**Comment by DonJayamanne** [comment]
@greazer thanks, unfortunately our plan is to deprecate this API.
Please can you let us know what methods of the kernel you require, 
* Today we have a proposed API to execute code against a kernel

**Comment by greazer** [comment]
Here's what I know I'm interested in.
 
- const jupyterExtKernelService = await jupyterExtension?.exports.getKernelService();
- vscode.notebooks.onDidChangeNotebookCellExecutionState
- jupyter comms behavior

I use the 2nd item above to run extension initialization code that is required to live in the jupyter kernel. In general, I need to... 
- Execute code in the user's kernel. Just like Data Wrangler. In fact, my implementation of VSCJupyterKernelSession is basically the same as that one.
- Be able to run kernel initialization code BEFORE the user's first cell is run. Currently, a user is required to manually execute at least one cell before my extension can work. 
- Know when a notebook is activated/deactivated so that I can swap out internal context to provide notebook-appropriate responses from my extension. I don't think this is a jupyter extension thing though.

**Comment by DonJayamanne** [comment]
Closing in favour of https://github.com/microsoft/vscode-jupyter/issues/15124

> Execute code in the user's kernel. Just like Data Wrangler. In fact, my implementation of VSCJupyterKernelSession is

Fixed with the new kernel execution API.

> Know when a notebook is activated/deactivated so that I can swap out i

If you mean `opened/focused` by `activated/decactivated`, then you can use the onDidOpen, onDidChangeActiveNotebook... APIs provided by VS Code.

@greazer , plese can you create separate issues for each of the following, so we can track each individually.
> Be able to run kernel initialization code BEFORE the user's first cell is run. Currently, a user is required to manually execute at least one cell before my extension can work.
