### ISSUE TITLE
Native Editor - Right Click Context Menu To Create New Notebook

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-jupyter#1504]
Hard to get to the Native Jupyter view for the first time unless you know to create a file with the .ipynb extension or have an existing notebook file. 

Have a right click context menu item in the file window of VS Code that allows users to create a new Jupyter file through UI. 

Example:
![image](https://user-images.githubusercontent.com/15910920/65353855-f8fc9b00-dba2-11e9-8361-9f1b3d2adbd4.png)

Spec TBD

**Comment by IanMatthewHuff** [comment]
File creation is all handed as part of code vscode, so closing.
