### ISSUE TITLE
Failed to start the Kernel.  Jupyter notebook failed to launch. 

### ISSUE THREAD

**Issue by WiG96** [microsoft/vscode-jupyter#15054]
## Environment data

-   VS Code version: 1.85.1
-   Jupyter Extension version (available under the Extensions sidebar): 2023.11.1100101639
-   Python Extension version (available under the Extensions sidebar): 2023.22.1
-   Pylance Extension Version: 2023.12.1
-   OS (Windows | Mac | Linux distro) and version: linux (arm64)
-   Python and/or Anaconda version:  3.9.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | N/A: running local

## Logs:

`Visual Studio Code (1.85.1, undefined, desktop)
Jupyter Extension Version: 2023.11.1100101639.
Python Extension Version: 2023.22.1.
Pylance Extension Version: 2023.12.1.
Platform: linux (arm64).
Workspace folder /home/GLO, Home = /home/GLO

13:02:50.155 [warn] Exception while attempting zmq : /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-arm64/dist/node_modules/zeromq/prebuilds/linux-arm64/node.napi.glibc.node)
13:02:50.157 [warn] Exception while attempting zmq (fallback) : Cannot find module 'node-gyp-build'
Require stack:
- ~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-arm64/dist/node_modules/zeromqold/lib/native.js
- ~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-arm64/dist/node_modules/zeromqold/lib/index.js
- ~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-arm64/dist/extension.node.js
- ~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-arm64/dist/extension.node.proxy.js
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
- 
13:02:51.855 [info] Start refreshing Kernel Picker (1705924971855)
13:02:51.901 [info] Using Pylance
13:02:52.286 [info] Start refreshing Interpreter Kernel Picker
13:03:00.216 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher  (Python Path: /usr/bin/python3, Unknown, 3.9.2) for '~/Python-Projects/Data_Science_projects/Pandas_Tutorial/EDA.ipynb' (disableUI=true)
13:03:01.459 [warn] Failed to get activated env vars for /usr/bin/python3 in 1249ms
13:03:01.557 [info] Process Execution: /usr/bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
13:03:02.231 [info] Process Execution: ~/.venv/bin/python -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
13:03:02.311 [info] Process Execution: ~/.venv/bin/python -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
13:03:02.409 [info] Process Execution: ~/.venv/bin/python -m pip list
13:03:02.581 [info] Process Execution: ~/.venv/bin/python -m jupyter kernelspec --version
13:03:02.645 [info] Process Execution: /usr/bin/python3 -m pip list
13:03:04.294 [info] End refreshing Kernel Picker (1705924971855)
13:03:07.759 [info] Launching server
13:03:07.816 [info] Starting Notebook
13:03:07.930 [error] Failed to start the Jupyter Server Error: Jupyter notebook failed to launch. 
{0}
    > at new r (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-arm64/dist/extension.node.js:81:4511)
    > originalException = Error: EFAULT: bad address in system call argument, write
13:03:07.940 [warn] Error occurred while trying to start the kernel, options.disableUI=true Error: Jupyter notebook failed to launch. 
{0}
    > at new r (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-arm64/dist/extension.node.js:81:4511)
    > originalException = Error: EFAULT: bad address in system call argument, write
13:03:19.802 [info] Handle Execution of Cells 0 for ~/Python-Projects/Data_Science_projects/Pandas_Tutorial/EDA.ipynb
13:03:19.956 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher  (Python Path: /usr/bin/python3, Unknown, 3.9.2) for '~/Python-Projects/Data_Science_projects/Pandas_Tutorial/EDA.ipynb' (disableUI=false)
13:03:20.010 [info] Launching server
13:03:20.024 [info] Starting Notebook
13:03:20.086 [error] Failed to start the Jupyter Server Error: Jupyter notebook failed to launch. 
{0}
    > at new r (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-arm64/dist/extension.node.js:81:4511)
    > originalException = Error: EFAULT: bad address in system call argument, write
13:03:20.125 [warn] Error occurred while trying to start the kernel, options.disableUI=false Error: Jupyter notebook failed to launch. 
{0}
    > at new r (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-arm64/dist/extension.node.js:81:4511)
    > originalException = Error: EFAULT: bad address in system call argument, write
13:03:20.142 [warn] Kernel Error, context = start Error: Jupyter notebook failed to launch. 
{0}
    > at new r (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-arm64/dist/extension.node.js:81:4511)
    > originalException = Error: EFAULT: bad address in system call argument, write
13:03:20.293 [info] Process Execution: /usr/bin/python3 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
13:03:27.334 [info] Dispose Kernel '~/Python-Projects/Data_Science_projects/Pandas_Tutorial/EDA.ipynb' associated with '~/Python-Projects/Data_Science_projects/Pandas_Tutorial/EDA.ipynb'
13:03:27.371 [error] Error in execution Error: Jupyter notebook failed to launch. 
{0}
    > at new r (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-arm64/dist/extension.node.js:81:4511)
    > originalException = Error: EFAULT: bad address in system call argument, write
13:03:27.389 [error] Error in execution (get message for cell) Error: Jupyter notebook failed to launch. 
{0}
    > at new r (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-arm64/dist/extension.node.js:81:4511)
    > originalException = Error: EFAULT: bad address in system call argument, write
13:03:28.271 [info] End cell 0 execution after 0s, completed @ undefined, started @ undefined
`

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
I'm sorry you are running into this issue.
This shoudl be fixed in the latest pre-release version of the Jupyter extension
Please install VS Code insiders and the latest pre-release version of Jupyter extnsion.
Or please wait for the next stable version of VS Code (some time this week).

If this still does not work, please do let us know, either ping here or feel free to open a new issue.
