### ISSUE TITLE
Cut (Ctrl + X) deletes lines but pastes nothing

### ISSUE THREAD

**Issue by ZeyuSun** [microsoft/vscode-jupyter#15067]
I also met same the problem of #4185 and the data clipped are lost. Has this issue been resolved?

**Comment by DonJayamanne** [comment]
Sorry for never getting back to you on this issue, somehow this slipped through the cracks.
We have made a lot of improvements and fixes in this space and believe this may have been resolved.
Please ensure you update to the latest version of VS code and the extensions.
Closing as I believe it may have been resolved,
If not please ping here and I'll reopen this or feel free to create a new issue.
