### ISSUE TITLE
DataViewer: Unable to view when the values include certain data types

### ISSUE THREAD

**Issue by saravanabalagi** [microsoft/vscode-jupyter#15077]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

```
# %%
from pathlib import Path

# %%
a = [1,3,Path('.')]
b = [1,3,4]
```

Both `a` and `b` are lists. `b` opens in DataViewer, `a` fails with error notification.

<details>
<summary>Screenshots</summary>

When opening `a`:

<img width="171" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/8567893/689d83d7-37f9-4647-be77-953719043646">
<img width="458" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/8567893/0b270d73-bf63-4541-a9cf-7cea3d8bdabc">

When opening `b`:

<img width="171" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/8567893/e4b0a1f2-745a-4135-ad71-be12ee0b34fb">
</details>

Other info:
- Runs into the same error in both notebook and interactive py files
- Suspected that this was related to this [issue](https://github.com/microsoft/vscode-jupyter/issues/13913), and tried installing the VSIX given there, no changes. This also happens when pandas dataframe is opened, but since it happens for lists with `Path` vars, this could be something else.
- Also tried the pre-release version, no changes.
- Tried running it locally and on remote, no changes.

### VS Code Version

Version: 1.85.2 (Universal) Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681 Date: 2024-01-18T06:40:32.531Z Electron: 25.9.7 ElectronBuildId: 26354273 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Darwin arm64 23.2.0

### Jupyter Extension Version

v2023.11.1100101639

### Jupyter logs

```shell
18:07:32.853 [warn] DataScience Error Error: Failed to fetch variable info from the Jupyter Server.
    at Uy.extractJupyterResultText (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:265:76)
    at Uy.deserializeJupyterResult (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:265:158)
    at Uy.getDataFrameRows (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:264:34835)
    at Mu.getRows (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:351:60676)
    at ~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:351:48528
    at jf.wrapRequest (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:351:48804)
```

### Coding Language and Runtime Version

Python 3.8.16

### Language Extension Version (if applicable)

v2023.22.1

### Anaconda Version (if applicable)

23.1.0 (also tried it with 23.11.0)

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
closing as the jupyter data viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486
