### ISSUE TITLE
Stop, Restart, Interrupt Buttons Don't Work with Julia Kernel (v1.10)

### ISSUE THREAD

**Issue by nickbrady** [microsoft/vscode-jupyter#15071]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When running an IJulia Kernel (IJulia v1.24.2, Julia v1.10.0) the Stop, Restart, and Interrupt Buttons do not function properly. 

Run All Button does function properly.

### VS Code Version

1.85.2

### Jupyter Extension Version

2023.11.1100101639

### Coding Language and Runtime Version

vJulia 1.10.0

### Language Extension Version (if applicable)

Julia Language Support v1.66.2

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and sorry you are running into this.
Please could you enable verbose logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to this output panel).

**Comment by nickbrady** [comment]
Example to reproduce the issue.

```julia
# Start the timer
println("Starting the timer...")

# Sleep for 5 seconds
sleep(5)

# Indicate that the time has passed
println("5 seconds have passed.")
```

Nothing appears in the log file to indicate that the Interrupt, Restart, or Stop buttons were pressed.
If I execute the code and do nothing, the jupyter timer within the cell also counts to 5 seconds. 
If I press the Interrupt button once, the same result occurs.
If I press the Interrupt button several times (2 or 3), then the timer in the cell continues indefinitely (until I reload the window).

Thanks for the help.

[CantStopJuliaNotebook_log.txt](https://github.com/microsoft/vscode-jupyter/files/14088693/CantStopJuliaNotebook_log.txt)

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, I've tested this in Jupyter Lab as well (using the latest julia docker container and installing jupyter lab into that), and can replicate the same behaviour.
Looks like a problem with Julia kernel itself.

Looks like its still not resolved.
See duplicate issue https://github.com/microsoft/vscode-jupyter/issues/10328
