### ISSUE TITLE
Support specifying Python Interpreter via Path in kernel picker

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#15087]
https://github.com/microsoft/vscode-jupyter/issues/15086

We have had similar requests in the past.

**Comment by DonJayamanne** [comment]
# Problems
* Assume user enters a path to an interpreter and that kernel is selected
    * User now reloads VS Code, 
    * At this point we need to re-create the same controller, but to do this, we need to keep track of the fact that the user manually entered a path to an interpeter
    * Solution: Perhaps its best we not implement this feature, but allow users to filter existing kernels by entering the paths or the like.

**Comment by DonJayamanne** [comment]
Not planning on supporting this feature as this would require Jupyter exetnsion to now manage/track the Python environment entered into the input box by user, this is already done and managed by Python extension today..

**Comment by Mxbonn** [comment]
> Not planning on supporting this feature as this would require Jupyter exetnsion to now manage/track the Python environment entered into the input box by user, this is already done and managed by Python extension today...

The jupyter extension fails to find the python version I use on a workspace level for me.

**Comment by DonJayamanne** [comment]
Please file a separate issue
