### ISSUE TITLE
Remote jupyter server reporting missing imports

### ISSUE THREAD

**Issue by jnlaia** [microsoft/vscode-jupyter#15088]
This is related to https://github.com/microsoft/vscode-jupyter/issues/13095 that was closed as it was deemed not important. Reopening a new issue again, as per the suggestion of the admin in the closed issue.

For all my career as a machine learning practicioner, I always used jupyter running on remote machines. So that is a very common working scenario. In my current setting, I need to do port forwarding (via kubernetes) to expose the 8080 port of the jupyter server. VSCode sees the remote link at a localhost address (I don't know if that is relevant or not).

VSCode is unable to resolve the imports

> Import "lightgbm" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)

even if I have in the local folder of the notebook a `pyrightconfig.json` that points VSCode at a local virtual environment that has that package installed

![image](https://github.com/microsoft/vscode-jupyter/assets/6794079/ff5c6a73-e910-402d-a4a0-12e583487878)

Tagging @DonJayamanne as he was the one who closed the previous issue, with the hope that this ticket adds to the incentive to make this happen

**Comment by DonJayamanne** [comment]
@jnlaia Do you still see this issue with the latest version of Jupyter, Pylance and Python extensions?
We made a few changes in this area and I believe this may no longer be an issue.

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `trace`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).

**Comment by DonJayamanne** [comment]
Also can you confirm that the message is coming from pylance extension?
