### ISSUE TITLE
Unhandled kernel message from a widget, No such comm

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#15082]
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/15076

<div type='discussions-op-text'>

<sup>Originally posted by **jshudson** January 27, 2024</sup>
I'm having an issue with running widgets using display or interact.  The widgets display when running a cell, but interacting with them gives an error message:

No such comm: d34adf99764f44519f1a8e7f42e1773e

The jupyter output is as follows:

3:09:25.208 [debug] Cell 3 executed with state Success
13:09:25.254 [debug] Widget Message: WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:2.0.0
13:09:25.255 [debug] Version of IPyWidgets 8 determined after 0.001s
13:09:25.256 [debug] Widget Message: WidgetManager: Loading class SliderStyleModel:@jupyter-widgets/controls:2.0.0
13:09:25.270 [debug] Widget Message: WidgetManager: Loading class IntSliderModel:@jupyter-widgets/controls:2.0.0
13:09:25.272 [debug] Widget Message: Received display data message d34adf99764f44519f1a8e7f42e1773e
13:09:25.286 [debug] Widget Message: Waiting for model to be available before rendering it d34adf99764f44519f1a8e7f42e1773e
13:09:25.286 [debug] Widget Message: WidgetManager: Loading class IntSliderView:@jupyter-widgets/controls:2.0.0
13:09:25.288 [debug] Widget Message: WidgetManager: Loading class LayoutView:@jupyter-widgets/base:2.0.0
13:09:25.288 [debug] Widget Message: WidgetManager: Loading class StyleView:@jupyter-widgets/base:2.0.0
13:09:42.142 [debug] Start cell 3 execution @ undefined
13:09:42.143 [info] End cell 3 execution after 1706292565.207s, completed @ 1706292565207, started @ undefined
13:09:42.183 [info] Unhandled widget kernel message: stream [object Object]
Unhandled kernel message from a widget: stream : {"name":"stderr","text":"No such comm: d34adf99764f44519f1a8e7f42e1773e\n"}

Any suggestions?</div>

**Comment by jshudson** [comment]
vscode information:

Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Jupyter information (vscode extentions):
v2023.11.1100101639
Jupyter Cell Tags v0.1.8
Jupyter Keymap v1.1.2
Jupyter Notebook Renderers v1.0.17
Jupyter Slide Show v0.1.5

Python vscode extension: Python v2023.22.1

Python kernel: 3.11.7

Steps to reproduce error:

Create a new notebook with the following code cell:

```
from ipywidgets import IntSlider

slider = IntSlider(min = 1, max=10)
display(slider)
```

yields the following result.  Move the slider produces the error.
![image](https://github.com/microsoft/vscode-jupyter/assets/10821770/e50868ea-e4e0-41a5-93c0-4f594e5419d8)

**Comment by DonJayamanne** [comment]
@jshudson I've tried this at my end and am unable to repro this.
Please can you list the versions of the packages install in your Python envrionment?

I've tried with Python 3.11.7 and the following packages
```
ipykernel          6.29.0
ipywidgets         8.1.1
```
I.e. the latest version of IPyKernel and Ipywidgets.

**Comment by jshudson** [comment]
Hi @DonJayamanne,

It appears to be an issue only on my work laptop.  I can get it working on others with no issue, but I can't figure out where to look to figure out what is causing the difference.

Here are the packages:
Package              Version
-------------------- -----------
anyio                3.6.2
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.2.0
attrs                22.1.0
backcall             0.2.0
beautifulsoup4       4.11.1
bleach               5.0.1
blinker              1.6.3
cffi                 1.15.1
click                8.1.7
colorama             0.4.6
comm                 0.2.1
contourpy            1.0.6
cycler               0.11.0
debugpy              1.8.0
decorator            5.1.1
defusedxml           0.7.1
entrypoints          0.4
et-xmlfile           1.1.0
executing            1.2.0
fastjsonschema       2.16.2
Flask                3.0.0
fonttools            4.38.0
idna                 3.4
ipykernel            6.29.0
ipython              8.7.0
ipython-genutils     0.2.0
ipywidgets           8.1.1
itsdangerous         2.1.2
jedi                 0.18.2
Jinja2               3.1.2
joblib               1.3.2
jsonschema           4.17.1
jupyter_client       8.6.0
jupyter_core         5.7.1
kiwisolver           1.4.4
MarkupSafe           2.1.1
matplotlib           3.6.2
matplotlib-inline    0.1.6
mistune              2.0.4
molmass              2023.8.30
nest-asyncio         1.5.6
notebook_shim        0.2.2
numpy                1.23.5
openpyxl             3.1.2
packaging            21.3
pandas               2.1.0
pandocfilters        1.5.0
parso                0.8.3
pickleshare          0.7.5
Pillow               9.3.0
pip                  23.3.2
pip-autoremove       0.10.0
platformdirs         2.5.4
prometheus-client    0.15.0
prompt-toolkit       3.0.33
psutil               5.9.4
pure-eval            0.2.2
pycparser            2.21
Pygments             2.13.0
pyparsing            3.0.9
pyrsistent           0.19.2
python-dateutil      2.8.2
pytz                 2023.3
pywin32              305
pywinpty             2.0.9
pyzmq                24.0.1
QtPy                 2.3.0
scikit-learn         1.3.2
scipy                1.11.4
Send2Trash           1.8.0
six                  1.16.0
sniffio              1.3.0
soupsieve            2.3.2.post1
stack-data           0.6.2
terminado            0.17.0
threadpoolctl        3.2.0
tinycss2             1.2.1
tornado              6.2
traitlets            5.6.0
tzdata               2023.3
wcwidth              0.2.5
webencodings         0.5.1
websocket-client     1.4.2
Werkzeug             3.0.0
widgetsnbextension   4.0.9

**Comment by DonJayamanne** [comment]
> It appears to be an issue only on my work laptop. I can get it working on others with no issue

Please can you create a new virtual environment `python -m venv .venv` and install ipykernel and widgets into that using `python -m pip install ipykernel ipywidgets` and try again.
Possible some of the other pakcages are interfering .

**Comment by jshudson** [comment]
Unfortunately with my work laptop, I can't run from a virtual environment due to whitelist restrictions.  However, I was able to create one and get a list of which packages were installed by default.  I uninstalled all packages not found in that list and was able to get the widget working.  I then installed the remainder of the packages I needed for this project and it still seems to function correctly.  The following is a list of packages that have not been reinstalled which may be the culprit

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/JH0035/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/JH0035/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">


Package Name
--
anyio
argon2-cffi
argon2-cffi-bindings
attrs
beautifulsoup4
bleach
blinker
cffi
click
defusedxml
entrypoints
fastjsonschema
Flask
idna
ipython-genutils
itsdangerous
Jinja2
jsonschema
jupyter_client
jupyter_core
MarkupSafe
mistune
molmass
notebook_shim
pandocfilters
pip-autoremove
prometheus-client
pycparser
pyrsistent
pywinpty
QtPy
Send2Trash
sniffio
soupsieve
terminado
tinycss2
tornado
traitlets
tzdata
wcwidth
webencodings
websocket-client
Werkzeug
widgetsnbextension



</body>

</html>

**Comment by jshudson** [comment]
And I reinstalled all of the rest of the list, and everything still seems to be working.  Many of the packages are newer versions, so not sure which one it was.  For reference here is the new list:

Package                   Version
------------------------- ---------------
anyio                     4.2.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.2.0
attrs                     23.2.0
backcall                  0.2.0
beautifulsoup4            4.12.3
bleach                    6.1.0
blinker                   1.7.0
cffi                      1.16.0
click                     8.1.7
colorama                  0.4.6
comm                      0.2.1
contourpy                 1.2.0
cycler                    0.12.1
debugpy                   1.8.0
decorator                 5.1.1
defusedxml                0.7.1
entrypoints               0.4
et-xmlfile                1.1.0
executing                 1.2.0
fastjsonschema            2.19.1
Flask                     3.0.1
fonttools                 4.47.2
fqdn                      1.5.1
idna                      3.6
ipykernel                 6.29.0
ipython                   8.7.0
ipython-genutils          0.2.0
ipywidgets                8.1.1
isoduration               20.11.0
itsdangerous              2.1.2
jedi                      0.18.2
Jinja2                    3.1.3
joblib                    1.3.2
jsonpointer               2.4
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
jupyter_client            8.6.0
jupyter_core              5.7.1
jupyter-events            0.9.0
jupyter_server            2.12.5
jupyter_server_terminals  0.5.2
jupyterlab_pygments       0.3.0
jupyterlab-widgets        3.0.9
kiwisolver                1.4.5
MarkupSafe                2.1.4
matplotlib                3.8.2
matplotlib-inline         0.1.6
mistune                   3.0.2
molmass                   2023.8.30
nbclient                  0.9.0
nbconvert                 7.14.2
nbformat                  5.9.2
nest-asyncio              1.5.6
notebook_shim             0.2.3
numpy                     1.26.3
openpyxl                  3.1.2
overrides                 7.7.0
packaging                 21.3
pandas                    2.2.0
pandocfilters             1.5.1
parso                     0.8.3
pickleshare               0.7.5
pillow                    10.2.0
pip                       23.3.2
pip-autoremove            0.10.0
platformdirs              2.5.4
prometheus-client         0.19.0
prompt-toolkit            3.0.33
psutil                    5.9.4
pure-eval                 0.2.2
pycparser                 2.21
Pygments                  2.13.0
pyparsing                 3.1.1
pyrsistent                0.20.0
python-dateutil           2.8.2
python-json-logger        2.0.7
pytz                      2023.4
pywin32                   305
pywinpty                  2.0.12
PyYAML                    6.0.1
pyzmq                     24.0.1
QtPy                      2.4.1
referencing               0.33.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.17.1
scikit-learn              1.4.0
scipy                     1.12.0
Send2Trash                1.8.2
six                       1.16.0
sniffio                   1.3.0
soupsieve                 2.5
stack-data                0.6.2
terminado                 0.18.0
threadpoolctl             3.2.0
tinycss2                  1.2.1
tornado                   6.2
traitlets                 5.6.0
types-python-dateutil     2.8.19.20240106
tzdata                    2023.4
uri-template              1.3.0
wcwidth                   0.2.5
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.7.0
Werkzeug                  3.0.1
widgetsnbextension        4.0.9

**Comment by DonJayamanne** [comment]
> everything still seems to be working.

Thanks for getting back
Given that it is working, I'm closing this issue
