### ISSUE TITLE
Add a "Delete cell" option in the notebook cells' right-button menu

### ISSUE THREAD

**Issue by Adam-Antios** [microsoft/vscode-jupyter#15092]
There is no "Delete cell" option in either the code's or markdown's right-button menu's.

![Untitled](https://github.com/microsoft/vscode-jupyter/assets/17729838/6d39d7d9-c667-4138-b602-e01ed36ce583)

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
