### ISSUE TITLE
Top level await in notebook recognized incorrectly

### ISSUE THREAD

**Issue by jussiarpalahti** [microsoft/vscode-jupyter#1510]
Code behaves erroneously when encountering top level await in notebook cell. While top level await is incorrect Python syntax in regular use it is supported in Jupyter Notebook cells with IPython kernel. This includes Code's notebook environment. I don't see a workaround to this since every caller of async function needs to itself be async and so awaited upon. Moreover Code gives confusing error messages about top level await (see below).

I'd like to be able to use top level await as in Jupyter Notebook and Console while keeping code intelligence of Code. This doesn't stop notebook based coding, but it is confusing since false errors mask actual errors.

## Expected behaviour

await would work like it usually does inside async functions. Regular Python says "SyntaxError: 'await' outside function". This should be the correct response if parser can't recognize await differently being in notebook cell.

## Actual behaviour

VS Code flags top level await as "undefined variable". Async function's name following it is marked as "unexpected token". Function call's parentheses are shown as tuple. 

## Versions

Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:22:37.660Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

VS Code Python 2019.8.30787
  "python.jediEnabled": false

**Comment by p-i-** [comment]
This still isn't fixed.
Pylance goes crazy, and I have to keep closing the .ipynb and reopening it, because sometimes the entire cell gets error-hilighted.
Please fix!
It's a pylance issue.
And it's not an enhancement request. It's a serious IDE bug.

**Comment by rchiodo** [comment]
Need to look at adding ipython imports to all concat docs

**Comment by rchiodo** [comment]
Verification steps:

1. Open a notebook
2. Type ```await print()```

It should not have any diagnostics (well once the correct intellisense engine finally starts)
