### ISSUE TITLE
Report width of the Jupyter window for libraries like `rich` to use

### ISSUE THREAD

**Issue by ma-sadeghi** [microsoft/vscode-jupyter#15106]
Libraries like `rich` need to know the width of the enviornment in which they're running. It'd be great if you could somehow provide a way to inspect the width of the Jupyter window. (although it seems like it's related to VSCode in general maybe?)

**Comment by DonJayamanne** [comment]
Thank you for filing this feature request, as this hasn't received any upvotes I'm closing this issue as not planned.
