### ISSUE TITLE
recommended environment highlight confusing for select environment dropdown

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode-jupyter#15104]
1. create notebook
2. try to run notebook
3. no kernel
4. choose python env as kernel
5. in "select a python environment" dropdown, the recommended python is highlighted like your cursor is on it even though it is not

<img width="748" alt="image" src="https://github.com/microsoft/vscode-python/assets/26030610/eb06d4e0-7ccf-4f42-8d75-b5649273108c">

**Comment by DonJayamanne** [comment]
No longer repros, most likely fixed.

**Comment by DonJayamanne** [comment]
@eleanorjboyd Please can you help verify this issue.

**Comment by Yoyokrazy** [comment]
Could be theme related. Seems fine on my end now. cursor is on the entry with the lighter grey hover.

![Image](https://github.com/user-attachments/assets/1f8780ac-42dd-4e7a-850c-ff626f7b8083)
