### ISSUE TITLE
Auto Scroll in the Jupyter output

### ISSUE THREAD

**Issue by ldsands** [microsoft/vscode-jupyter#1511]
Sorry if this is something that I've missed but I would love to see an auto scroll feature for output in the jupyter python interactive window. For example when I have some code print out some output it will not scroll to the end of that output when it reaches the end of the designated area in the output window. Thank you for all of your work on this extension I have loved using it!

![image](https://user-images.githubusercontent.com/7889104/62094998-89be9680-b244-11e9-8c74-6393ac292502.png)

**Comment by GitHunter0** [comment]
> I still think this scrollbar should be auto scrolled as well.

I think that too.

**Comment by SnakeWayne** [comment]
After using vscode version of jupyter， I dont want to go back to the browser version, it so handy.But the scroll bar is not friendly，especially in the pdb senario.

**Comment by orionlee** [comment]
With current release version of Jupyter, the auto scroll does not seem to work (at least in interactive python case), even with the `maxOutputSize: -1`  workaround (the settings seems to have migrated to `jupyter.maxOutputSize`).

Here is a gif:
![vscode-jupyter-autoscroll](https://user-images.githubusercontent.com/250644/128908865-698bd698-4735-4df8-ab79-04b175b4edba.gif)

The relevant settings:
![image](https://user-images.githubusercontent.com/250644/128908343-f668eaa5-78f4-4557-9af7-591970b5328b.png)


Versions:
```
Jupyter extension: v2021.8.1054968649
Python extension:  v2021.8.1105858891
Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by rchiodo** [comment]
@orionlee Can you update to the latest version of VS code? The scrolling for this is actually now part of VS code itself, and not the jupyter extension.

**Comment by GitHunter0** [comment]
@rchiodo , I'm always updating and using the last version of VScode on Windows 10, however there is a problem that never seems to go away: the auto-scroll does not work whenever the code triggers an error message... Please, any thoughts on that?

**Comment by rchiodo** [comment]
Can you give an example?

I entered this code here:

```python
# %%
import os
[print(p) for p in os.environ['PATH'].split(';')]
print('')
raise Exception('Stuff happened')
```

I get this in the new interactive window (the one that VS code creates the UI for in version 1.59)

![image](https://user-images.githubusercontent.com/19672699/128912567-57bf8d75-9226-40f3-ad9a-15c4a9c8e13f.png)

**Comment by orionlee** [comment]
@rchiodo the auto scrolling to latest output works with VSCode 1.59.0

**Comment by GitHunter0** [comment]
> Can you give an example?
> 
> I entered this code here:
> 
> ```python
> # %%
> import os
> [print(p) for p in os.environ['PATH'].split(';')]
> print('')
> raise Exception('Stuff happened')
> ```
> 
> I get this in the new interactive window (the one that VS code creates the UI for in version 1.59)
> 
> ![image](https://user-images.githubusercontent.com/19672699/128912567-57bf8d75-9226-40f3-ad9a-15c4a9c8e13f.png)

Thank you @rchiodo , now that I updated to 1.59.0 I can't reproduce the issue, maybe it is resolved,
