### ISSUE TITLE
API to pre-select remote Jupyter kernels

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#15122]
* Synapse & AzML would like to automatically select a kernel associated with a notebook
Workflow
- Users open synapse/azml outside vscode and work on a notebook
- Next users continue in VS Code
- The notebook is opened, however the kernel is not auto selected.
- Current approach is to use a deprecated API

**Proposed solutions**
* Provide a way to select a kernel got a notebook given the server/kernel id
* This could be useful for users who wish to pre-select all notebooks with a given remote kernel as well (today we have an API to pre-select local Python kernels)

@realDuang @sevillal /cc

**Comment by DonJayamanne** [comment]
Closing this issue for now as I do not believe this is a blocker for any of the partner extensions

**Comment by andyscho** [comment]
> Closing this issue for now as I do not believe this is a blocker for any of the partner extensions

Can you say more about this? I am curious about if there are good ways to accomplish this now. Thanks!

**Comment by DonJayamanne** [comment]
Sure
* Basically there are only 2 upvotes on this issue (we require a minimum of 20 within 60days, and this issue has been open for far longer than that, https://github.com/microsoft/vscode/wiki/Issues-Triaging)
* Also we do not have any partner (internal MS extensions) that are blocked on this functionality, 

>  curious about if there are good ways to accomplish this now. Thanks!

Unfortunately no.
