### ISSUE TITLE
Explore supporting Comms messaging on code execution

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#15124]
**Current proposal**
* Ensure Comms API only works within the context of a pending request execution
    * I.e. 3rd party makes a request to execute code via the kernel API
    * & comms is valid only until this execution request has not resolved
    * Once execution completes, the comms API will not be available.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-jupyter/issues/14468
- [ ] https://github.com/microsoft/vscode-jupyter/issues/14776
```

**Comment by DonJayamanne** [comment]
@rebornix I am closing this issue as completed.
As we do not need this.

**Comment by rebornix** [comment]
Sounds reasonable to me.

**Comment by DonJayamanne** [comment]
Closing in favour of https://github.com/microsoft/vscode-jupyter/issues/15437
