### ISSUE TITLE
Open Interactive python console per file 

### ISSUE THREAD

**Issue by htjain** [microsoft/vscode-jupyter#1513]
I am migrating from PyDev to VSCode. 
Many times I have to work with multiple python files.
But not able to figure out how to run each file in its own Interactive python console (just like multiple Jupyter notebooks ) 

Can someone please guide me ?

**Comment by joyceerhl** [comment]
This is supported with the setting `"jupyter.interactiveWindowMode": "perFile"`. The interactive window will be started with the currently active Python interpreter.
