### ISSUE TITLE
Unable to connect to localhost notebook server in vscode.dev

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode-jupyter#15147]
## Environment data

-   VS Code version: 1.86.0 (vscode.dev)
-   Jupyter Extension version (available under the Extensions sidebar): v2024.1.2024012502
-   Python Extension version (available under the Extensions sidebar): v2024.0.1
-   OS (Windows | Mac | Linux distro) and version: Mac (Edge)
-   Python and/or Anaconda version: 3.11.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Can connect to localhost kernel running with command:
`python3 -m notebook --NotebookApp.allow_origin="*"`

Also went through the steps [here](https://github.com/microsoft/vscode-jupyter/wiki/Connecting-to-a-remote-Jupyter-server-from-vscode.dev).

## Actual behaviour

<img width="625" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/8560030/871ca209-da2a-4b51-b026-7b2a3f075f5c">

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Start a server on localhost: `python3 -m notebook --NotebookApp.allow_origin="*"`
2. Verify that the connection works in VS Code Stable (v1.86.0 with Jupyter extension version v2024.1.2024012502)
3. Verify that the same connection does not work in vscode.dev

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Visual Studio Code (1.86.0, undefined, vscode.dev)
Jupyter Extension Version: 2024.1.2024012502.
Python Extension Version: 2024.0.1.
Pylance Extension Version: 2023.12.1.
No workspace folder opened.
16:16:04.430 [error] Unable to determine the caller of the extension API for trace stack. Error: 
    at EI.determineExtensionFromCallStack (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2024.1.2024012502+web/extension/dist/extension.web.bundle.js#vscode-extension:107:51815)
    at Object.registerRemoteServerProvider (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2024.1.2024012502+web/extension/dist/extension.web.bundle.js#vscode-extension:107:29295)
    at bo.eval (https://github.vscode-unpkg.net/GitHub/codespaces/1.16.10/node_modules/moment/locale/af.js:3:1)
    at Generator.next (<anonymous>)
    at fulfilled (https://github.vscode-unpkg.net/GitHub/codespaces/1.16.10/node_modules/moment/locale/af.js:3:1)
16:16:04.430 [error] The API registerRemoteServerProvider has being deprecated and will be removed soon, please use createJupyterServerCollection (extension unknown).
16:16:16.188 [warn] Password for http://localhost:8888/ was invalid.
16:16:16.214 [debug] Disposing Jupyter Lab Helper
16:16:16.214 [debug] SessionManager - dispose contents manager
16:16:16.214 [debug] ShutdownSessionAndConnection - dispose session manager
16:16:16.214 [warn] Uri verification error Error: Forbidden
16:16:16.216 [debug] Finished disposing Jupyter Lab Helper
16:16:16.216 [error] Jupyter Lab Helper:getKernelSpecs failure:  Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.

```

</p>
</details>

**Comment by amunger** [comment]
I've never actually used the vanilla `notebook` package.

Are you able to use the jupyter package?
`python3 -m jupyter notebook --NotebookApp.allow_origin="*"`
or
`python3 -m jupyter lab--NotebookApp.allow_origin="*"`

**Comment by pwang347** [comment]
Hi @amunger! Looks like neither of those are working for me either

<img width="878" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/8560030/b343cd28-b857-41a1-be36-aa08b0948085">
<img width="993" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/8560030/aa2c34ca-72ed-4284-ac2f-d0cc7f9efb6f">

I get the same password incorrect screen, and it's working in local Jupyter
<img width="612" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/8560030/5a15fdfa-2da4-41fa-a6c6-dbd1d07b9b21">
<img width="402" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/8560030/9f50b925-5977-41b7-804a-8bd2e339781b">

**Comment by pwang347** [comment]
Adding some server logs which show first the inability to sign in from vscode.dev, followed by it working in local:


<details>

<summary>Logs
</summary>

<p>

```

<p>

```
[W 2024-02-08 11:21:13.116 ServerApp] 404 OPTIONS /hub/api (@::1) 64.08ms referer=None
[W 2024-02-08 11:21:13.128 ServerApp] 404 GET /hub/api (@::1) 1.46ms referer=None
[W 2024-02-08 11:21:13.134 ServerApp] 404 OPTIONS /tree? (@::1) 0.53ms referer=None
[W 2024-02-08 11:21:13.139 ServerApp] 404 GET /tree? (@::1) 0.61ms referer=None
[W 2024-02-08 11:21:13.771 ServerApp] 405 OPTIONS /login? (@::1) 1.54ms referer=None
[W 2024-02-08 11:21:13.795 ServerApp] 404 OPTIONS /tree (@::1) 1.60ms referer=None
[W 2024-02-08 11:21:13.803 ServerApp] 404 GET /tree (@::1) 6.70ms referer=None
[W 2024-02-08 11:21:13.820 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/Users/paulwang/Library/Python/3.11/lib/python/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwang/Library/Python/3.11/lib/python/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 753, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-08 11:21:13.836 ServerApp] 403 GET /api/kernels?1707420073811 (@::1) 15.48ms referer=None
[W 2024-02-08 11:21:13.837 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/Users/paulwang/Library/Python/3.11/lib/python/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwang/Library/Python/3.11/lib/python/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 753, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-08 11:21:13.838 ServerApp] 403 GET /api/kernelspecs?1707420073811 (@::1) 1.55ms referer=None
[W 2024-02-08 11:21:13.838 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/Users/paulwang/Library/Python/3.11/lib/python/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwang/Library/Python/3.11/lib/python/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 753, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-08 11:21:13.839 ServerApp] 403 GET /api/kernels?1707420073812 (@::1) 2.01ms referer=None
[W 2024-02-08 11:21:13.839 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/Users/paulwang/Library/Python/3.11/lib/python/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwang/Library/Python/3.11/lib/python/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 753, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-08 11:21:13.840 ServerApp] 403 GET /api/sessions?1707420073812 (@::1) 2.70ms referer=None
[W 2024-02-08 11:21:13.883 ServerApp] 404 OPTIONS /hub/api (@::1) 0.61ms referer=None
[W 2024-02-08 11:21:13.895 ServerApp] 404 GET /hub/api (@::1) 1.53ms referer=None
[W 2024-02-08 11:21:13.900 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/Users/paulwang/Library/Python/3.11/lib/python/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwang/Library/Python/3.11/lib/python/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 753, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-08 11:21:13.901 ServerApp] 403 GET /api/kernelspecs?1707420073844 (@::1) 1.87ms referer=None
[W 2024-02-08 11:21:13.909 ServerApp] 404 OPTIONS /tree? (@::1) 1.87ms referer=None
[W 2024-02-08 11:21:13.912 ServerApp] 404 GET /tree? (@::1) 1.21ms referer=None
[W 2024-02-08 11:21:16.241 ServerApp] 404 GET /api/terminals?_=1707419911787 (0bb86db298ff4b8dbb32960fb63d6847@::1) 2.33ms referer=http://localhost:8889/tree
[W 2024-02-08 11:21:40.087 ServerApp] 404 GET /api/terminals?_=1707419911790 (0bb86db298ff4b8dbb32960fb63d6847@::1) 3.69ms referer=http://localhost:8889/tree
[W 2024-02-08 11:22:14.775 ServerApp] 405 OPTIONS /login? (@::1) 2.70ms referer=None
[W 2024-02-08 11:22:14.801 ServerApp] 404 OPTIONS /tree (@::1) 2.77ms referer=None
[W 2024-02-08 11:22:14.808 ServerApp] 404 GET /tree (@::1) 0.67ms referer=None
[W 2024-02-08 11:22:17.254 ServerApp] 404 OPTIONS /hub/api (@::1) 1.51ms referer=None
[W 2024-02-08 11:22:17.257 ServerApp] 404 GET /hub/api (@::1) 1.52ms referer=None
[W 2024-02-08 11:22:17.263 ServerApp] 404 OPTIONS /tree? (@::1) 1.51ms referer=None
[W 2024-02-08 11:22:17.266 ServerApp] 404 GET /tree? (@::1) 1.64ms referer=None
[W 2024-02-08 11:22:17.948 ServerApp] 404 OPTIONS /hub/api (@::1) 1.20ms referer=None
[W 2024-02-08 11:22:17.950 ServerApp] 404 GET /hub/api (@::1) 0.79ms referer=None
[W 2024-02-08 11:22:17.954 ServerApp] 404 OPTIONS /tree? (@::1) 1.00ms referer=None
[W 2024-02-08 11:22:17.956 ServerApp] 404 GET /tree? (@::1) 1.22ms referer=None
^[[A^[[A


[W 2024-02-08 11:22:23.059 ServerApp] 404 OPTIONS /hub/api (@::1) 1.41ms referer=None
[W 2024-02-08 11:22:23.063 ServerApp] 404 GET /hub/api (@::1) 1.43ms referer=None
[W 2024-02-08 11:22:23.074 ServerApp] 404 OPTIONS /tree? (@::1) 3.08ms referer=None
[W 2024-02-08 11:22:23.087 ServerApp] 404 GET /tree? (@::1) 0.60ms referer=None
[W 2024-02-08 11:23:43.918 ServerApp] 404 GET /hub/api (@127.0.0.1) 9.76ms referer=None
[W 2024-02-08 11:23:43.928 ServerApp] 404 GET /tree? (@127.0.0.1) 1.72ms referer=None
[I 2024-02-08 11:23:49.024 ServerApp] User 408bae62db074664ad1ff5ea6c4aab59 logged in.
[I 2024-02-08 11:23:49.030 ServerApp] 302 POST /login? (408bae62db074664ad1ff5ea6c4aab59@127.0.0.1) 7.52ms
[W 2024-02-08 11:23:50.093 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.03ms referer=None
[W 2024-02-08 11:23:53.483 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.37ms referer=None
[I 2024-02-08 11:23:53.596 ServerApp] Kernel started: d5e1198f-bfaf-40cd-822e-6ffbf511b64b
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-02-08 11:23:58.829 ServerApp] Connecting to kernel d5e1198f-bfaf-40cd-822e-6ffbf511b64b.
[W 2024-02-08 11:23:59.657 ServerApp] 404 GET /nbextensions/mitosheet/extension.js (@127.0.0.1) 2.27ms referer=None

```

</p>
</details>

**Comment by pwang347** [comment]
Hi @DonJayamanne, I did not see any logs appearing in console after the failed auth attempt:
<img width="528" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/8560030/82a3051e-1256-4eff-9836-74bcb2533d6c">

**Comment by amunger** [comment]
oh, try pasting in the full url with the token so that it doesn't (shouldn't) prompt for a password.

`http://localhost:8888/?token=xxxxxxxxxxxxx`

When I only put in `http://localhost:8888` for the server location, it asks for a password, and the token only works as a password on desktop for some reason.

**Comment by pwang347** [comment]
> oh, try pasting in the full url with the token so that it doesn't (shouldn't) prompt for a password.
> 
> `http://localhost:8888/?token=xxxxxxxxxxxxx`
> 
> When I only put in `http://localhost:8888` for the server location, it asks for a password, and the token only works as a password on desktop for some reason.

This worked for me, thanks @amunger! Yeah, interesting that the behaviour is different here. I was so used to not including the token that it never occurred to me it should be part of the server URL.

**Comment by DonJayamanne** [comment]
Closing as fixed
