### ISSUE TITLE
Make traceback line numbers clickable to jump back to original source

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1514]
Quote from customer:

> In that case, feature suggestion: make the line numbers clickable when tracebacks are shown in the interactive window, for errors during "normal" execution. It seems like that would utilize the same source-map infrastructure as the debugger, but perhaps I'm misunderstanding what you mean by `hashed source that jupyter generates`. Thanks!

This is inline with what we had talked about making the errors searchable too.

**Comment by joyceerhl** [comment]
The Jupyter extension contributes an error renderer which provides clickable traceback line numbers. It's not working right now but will be fixed shortly. Closing in favor of https://github.com/microsoft/vscode-jupyter/issues/7267.
