### ISSUE TITLE
No warning/error for overwriting a std lib file

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#15155]
Only repros with latest packages, so create a new venv for the kernel
Create a file in the workspace called `random.py`
Create a notebook and run a cell.

the cell succeeds, which causes `Display error about overriding builtin modules (without Python daemon` to fail.

**Comment by DonJayamanne** [comment]
Problem is latest version of IPykernel prevents shadowing of builtin packages when starting a kernel
