### ISSUE TITLE
Implement disconnect Kernal feature

### ISSUE THREAD

**Issue by nilupulmanodya** [microsoft/vscode-jupyter#15162]
I discovered a discussion in https://github.com/microsoft/vscode-jupyter/issues/7189#issue-973476691 indicating that Jupyter kernels are automatically disconnected in VS Code under two specific circumstances:

- When VS Code is closed.
- When the notebook or interactive window that was using the kernel is closed.

There are scenarios where it might be necessary to disconnect a kernel from a notebook that is already open and either intended for future use or currently in use for output generation or code implementation review. This is especially relevant for notebooks that have already been executed and are no longer needed for further runs.

At present, this can only be achieved by the methods mentioned above. However, I believe creating a more straightforward and efficient way to disconnect the kernel without closing the notebook window would enhance usability. 

Implementing such a feature could also help mitigate issues related to GPU memory shortages, as it would free up resources without requiring the user to close their work environment.

**Comment by DonJayamanne** [comment]
Closing in favour of https://github.com/microsoft/vscode-jupyter/issues/1378
