### ISSUE TITLE
unable to "view value in data viewer" while debugging when hdf5 are involved

### ISSUE THREAD

**Issue by timebis** [microsoft/vscode-jupyter#15179]
Type: <b>Bug</b>

unable to "view value in data viewer" while debugging. When I click on it, nothing is oppened.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 5.10.0-27-amd64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 4578)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.02GB (26.32GB free)|
|Process Argv|log --trace --crash-reporter-id ae314da7-6d41-419c-a7b5-785ea246fad1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|14.7.0
copilot|Git|1.156.0
copilot-chat|Git|0.11.1
go|gol|0.40.3
vscode-h5web|h5w|0.0.11
markdown-converter|man|5.2.1
rainbow-csv|mec|3.11.0
git-graph|mhu|1.30.0
autopep8|ms-|2023.8.0
flake8|ms-|2023.10.0
python|ms-|2023.16.0
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.9.1002771829
jupyter-keymap|ms-|1.1.1
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.4
vscode-typescript-next|ms-|5.4.20240205
vscode-vba|ser|0.9.6
pdf|tom|1.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30951796
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928

```

</details>

**Comment by MrTrigger** [comment]
Any update? I'm having the same problem with hdf5 data

**Comment by amunger** [comment]
closing as the jupyter data viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486. Though if this still occurs with another data viewer like the one from Data Wrangler, you should open an issue with that extension
