### ISSUE TITLE
Jupyter UI is not cleaned in VScode-insder Version: 1.87.0-insider

### ISSUE THREAD

**Issue by bluehope** [microsoft/vscode-jupyter#15185]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

VScode version: ```Version: 1.87.0-insider (Universal)
Commit: b2598b92d18ea1132e9cd35df776c8c22a7f9730
Date: 2024-02-13T05:48:12.281Z (23 hrs ago)
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin x64 23.3.0```

Jupyter Extention version: `v2024.1.1`

---

With simple Python code with cell mode,

``` python
# %%
import numpy as np

print("hello world")
```
<img width="1051" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/1754257/81eef403-f2bd-49c0-a899-2abb8b6f2819">

1. Press `Clear All` : The result 'hello world' text box remains.
<img width="1061" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/1754257/f3f8769b-e30d-49ba-9ae0-e4779f97867b">

2. Press `Restart`: Text UI is corrupted. 
<img width="1055" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/1754257/364ad65f-4b3e-453b-964b-d61217273b3d">

3. Run 3 more times + `Clear All` + `Restart`: Text UI is corrupted, results text box remains.
<img width="1058" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/1754257/512e7f38-5b5a-47e8-aeb2-f144fc13be4e">

### VS Code Version

Version: 1.87.0-insider (Universal) Commit: b2598b92d18ea1132e9cd35df776c8c22a7f9730 Date: 2024-02-13T05:48:12.281Z (23 hrs ago) Electron: 27.3.2 ElectronBuildId: 26836302 Chromium: 118.0.5993.159 Node.js: 18.17.1 V8: 11.8.172.18-electron.0 OS: Darwin x64 23.3.0

### Jupyter Extension Version

v2024.1.1

### Coding Language and Runtime Version

Python 3.9

### Running Jupyter locally or remotely?

None

**Comment by rebornix** [comment]
This issue should be fixed now in latest Insiders. Thanks for the report!
