### ISSUE TITLE
Allow cells to be modified and rerun (automatically rerun dependent cells)

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode-jupyter#1518]
from survey:

The quick, obvious thing is to be able to make standalone and zoomable plots, without resorting to %matplotlib hacks. As a long term goal: rigth now, there is very little difference between running code in the interactive windows and executing line by line in the integrated terminal. To make a truly convenient Data Science environement, that is pleasant to use, an interactive window should: allow cells to be modified and rerun, and _automatically rerun all the cells whose variables depend on the cell that has been modified!!_ I know it's not the way Jupyter works, and this is just an extension that wraps it, but otherwise there is little reason to use it tbh

**Comment by greazer** [comment]
Already done or has a spec (Claudia's)
