### ISSUE TITLE
Allow user to decide which code lens show up

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1519]
Since we have so many commands, it would be nice to be able to pick the code lens that appear above a cell. 

Right now we have:
- Run Cell (and implicitly advance)
- Run Above
- Run Below

We might also want
- Debug Cell
- Run Cell (and don't advance)
- Export Cell
- Add new cell

Let's do this when we add debugging support.

**Comment by greazer** [comment]
mostly doable with "juypter.codeLenses" setting.
