### ISSUE TITLE
Provide way to edit the original Python code (file) associated with an Interactive Window cell

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode-jupyter#15196]
This is a reopen for https://github.com/microsoft/vscode-jupyter/issues/13130

Now that we are integrated for the Jupyter Data Viewer, we also need to support the Data Viewer in the interactive window. This means that we need a way to export code back to the original Python file. The current behaviour is that we can only export the code to a new notebook, which will not be executable.

Thanks!

CC @DonJayamanne

**Comment by jabbera** [comment]
I agree, the notebook format is so unfriendly to source control that we use the interactive window extensively so we can use the jupytext format. Another option here from my perspective would be to render jupytext python files in the notebook editor as opposed to pairing it to an interactive window. (Assuming this would make the wrangler just work) 

This (or something similar) is an open ask here: https://github.com/microsoft/vscode-jupyter/issues/1240

**Comment by DonJayamanne** [comment]
@yinghawl @jabbera 
You can use the DW functionality with Interactive window today.
This issue is about modifying the Python file from within the DW extension. Is that something you need?
I'd like to keep the comments in this issue related to the  topic, else discussing things like jupytext, etc tend to pollute this issue as they are not really related to this.

**Comment by jabbera** [comment]
@DonJayamanne Sorry, I don't want to derail the conversation, but It's never worked for me so I thought we were talking about data wrangler working period.

![image](https://github.com/microsoft/vscode-jupyter/assets/301208/2dba9158-64eb-4223-bf5d-acd8ec8d56fa)

**Comment by yinghawl** [comment]
Yup, I am encountering the same issue as @jabbera

**Comment by DonJayamanne** [comment]
@jabbera @yinghawl Please file a separate issue in the DW extension
This issue is not for discussion of enabling that feature
To my knowledge this issue does not block enabling that (this is more of an API issue).

**Comment by DonJayamanne** [comment]
Given that this issue has been open for a while and there hasn't been any follow up since then i'm closing this issue.
@pwang347 please feel free to create this issue again when you do plan on starting work on this, else lets close this as there's nothing blocking here for now.
