### ISSUE TITLE
Run Selection/Line in Python Terminal doesn't take into account code changes in the import files

### ISSUE THREAD

**Issue by nemar3** [microsoft/vscode-jupyter#15203]
## Environment data

-   VS Code version: 1.86.2
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): v2024.0.1
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: 3.11.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

I am doing Run Selection/Line in Python Terminal with shift+Enter
in my code I am doing an import from file A with class B
I make some code changes in class B
then I do run Selection/Line in Python Terminal with shift+Enter to re-import the class with the changes
the code changes in file A , class B should be taken into account

I have to exit() the python terminal and start it again for the changes to be taken into account

I have the File A and File B open at the same time. File B is open as a floating window

## Actual behaviour
I am doing Run Selection/Line in Python Terminal with shift+Enter
in my code I am doing an import from file A with class B
I make some code changes in class B
then I do run Selection/Line in Python Terminal with shift+Enter to re-import the class with the changes
the code changes in file A , class B are not taken into account
I have to exit() the terminal and start it again

## Steps to reproduce:
create 2 files, File A and File B
in File A create a 
class B
    def print_some_value():
          print ("123")
in File B
from A import B
b=B()
b.print_some_value()
execute these 3 lines of code with  Run Selection/Line in Python Terminal, shift+Enter

then make a change in File A:
class B
    def print_some_value():
          print ("456")
in File B
execute the same 3 lines of code as before with  Run Selection/Line in Python Terminal, shift+Enter
and even though the class was re-imported the old value is still being printed, should print "456"

I have the File A and File B open at the same time. File B is open as a floating window

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by amunger** [comment]
That's how python interpreters work, and not controlled by vs code.

**Comment by nemar3** [comment]
I don't think this is a python interpreter issue, it's a VS Code issue, this problem doesn't happen on Spyder

**Comment by amunger** [comment]
Spyder must be doing additional work since this is the behavior you will get with a raw python interpreter in the command line or a jupyter notebook. You can manually reload a module to get the latest changes though:

```
import importlib
importlib.reload(your_module)
```

**Comment by amunger** [comment]
also, are you using the Interactive Window (the editor that opens on the right with a kernel picker), or just the integrated terminal?

**Comment by nemar3** [comment]
In Spyder I am not using importlib and not doing any reloading, I am using the console that comes by default on the right lower side, I think it's called IPython Console

**Comment by amunger** [comment]
closing this for now as it hasn't had any other votes in support of implementation
