### ISSUE TITLE
Cmd+A in output

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode-jupyter#15209]
1. run code which generates error message
2. click cursor in the error message output
3. see the blue outline of the output (signaling your focus is in the box)
<img width="1237" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/26030610/a62ff421-bf6c-43ab-9c7c-4ab1b00345bc">
4. use `cmd a` to attempt to select all in output cell
5. 🐛 the highlight moves to every cell in the notebook? if I try to copy nothing happens
6. I noticed this also happens for non error outputs, so maybe its a design decision?
<img width="1233" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/26030610/c9208686-204b-458f-a974-7c82f54dde40">

came during work on this TPI: https://github.com/microsoft/vscode-copilot/issues/4217

**Comment by rebornix** [comment]
Can be part of https://github.com/microsoft/vscode/issues/204950

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/204023
