### ISSUE TITLE
API to link a DebugSession object to a notebook

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode-jupyter#15228]
There is currently an internal property `__notebookUri` on the Jupyter kernel's `vscode.DebugSession.Configuration` object which can be used to determine when a notebook starts/stops debugging.

Just opening an issue here to track the finalization / evolution of this API as per offline discussions. Thanks!

CC @rebornix

**Comment by DonJayamanne** [comment]
Please consider this issue as an official confirmation that this is the stable way to proceed with this.
I.e. officially supported for DW extension, and no plans to document nor support this for others.
