### ISSUE TITLE
Allow opening of a large string in the editor from the variable explorer

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#1522]
When you have a large data frame or series you can use the Data Explorer. But for a very large string we truncate it in the variable explorer, but you can't open it up to see the context. We should have an option to open up the text just in a plain old editor window to view longer strings.

**Comment by DonJayamanne** [comment]
@roblourens looks like a candidate for custom variable viewers (today we have special case for pandas data frames, dict and lists)

**Comment by amunger** [comment]
closing in favor of https://github.com/microsoft/vscode/issues/165445
