### ISSUE TITLE
confirm before notebook installs a package

### ISSUE THREAD

**Issue by rootsmusic** [microsoft/vscode-jupyter#15222]
When I run a .ipynb file that I didn't create, I probably won't catch install commands that aren't in the first cell.  If there's a `!pip` or `piplite.install` command, please confirm that user wants to proceed with the installation.  Since I'm running a conda environment, pip can still install duplicative packages except from the pypi channel.

**Comment by rootsmusic** [comment]
@DonJayamanne Would setting the workspace trust block a notebook from installing new packages?  Thanks.

**Comment by DonJayamanne** [comment]
> setting the workspace trust block a notebook from installing new packages? Thanks.

if you don’t trust the workspace, then you won’t be able to execute
