### ISSUE TITLE
Notebook console loop "Jupyter completion time"

### ISSUE THREAD

**Issue by Alextron0102** [microsoft/vscode-jupyter#15233]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Hi,
I get this problem when typing on a fresh new notebook created by "name".ipynb on the explorer menu, when typing on a new cell it starts spamming "[debug] Jupyter completion time:" on console and it doesn't stops.
It ramps up CPU usage and had already tryed everything to get rid of it (uninstalling vscode, python, ipykernel, extensions)  and nothing seems to fix it. 

Version: 1.86.2 (system setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621

### VS Code Version

1.86.2

### Jupyter Extension Version

v2024.1.1

### Jupyter logs

```shell
...
07:40:05.009 [debug] Jupyter completion time: 7
07:40:05.013 [debug] Jupyter completion time: 11
07:40:05.021 [debug] Jupyter completion time: 6
07:40:05.026 [debug] Jupyter completion time: 11
07:40:05.033 [debug] Jupyter completion time: 16
07:40:05.034 [debug] Jupyter completion time: 17
07:40:05.040 [debug] Jupyter completion time: 23
07:40:05.044 [debug] Jupyter completion time: 27
07:40:05.046 [debug] Jupyter completion time: 24
07:40:05.050 [debug] Jupyter completion time: 28
07:40:05.055 [debug] Jupyter completion time: 19
07:40:05.059 [debug] Jupyter completion time: 23
07:40:05.071 [debug] Jupyter completion time: 7
07:40:05.074 [debug] Jupyter completion time: 10
07:40:05.079 [debug] Jupyter completion time: 15
07:40:05.082 [debug] Jupyter completion time: 18
07:40:05.087 [debug] Jupyter completion time: 21
07:40:05.095 [debug] Jupyter completion time: 6
07:40:05.099 [debug] Jupyter completion time: 10
07:40:05.108 [debug] Jupyter completion time: 5
07:40:05.113 [debug] Jupyter completion time: 9
07:40:05.119 [debug] Jupyter completion time: 5
07:40:05.126 [debug] Jupyter completion time: 12
07:40:05.128 [debug] Jupyter completion time: 8
07:40:05.135 [debug] Jupyter completion time: 5
07:40:05.139 [debug] Jupyter completion time: 9
07:40:05.144 [debug] Jupyter completion time: 8
07:40:05.148 [debug] Jupyter completion time: 12
07:40:05.154 [debug] Jupyter completion time: 9
07:40:05.158 [debug] Jupyter completion time: 13
07:40:05.164 [debug] Jupyter completion time: 15
07:40:05.172 [debug] Jupyter completion time: 7
07:40:05.187 [debug] Jupyter completion time: 7
07:40:05.191 [debug] Jupyter completion time: 10
07:40:05.198 [debug] Jupyter completion time: 17
07:40:05.200 [debug] Jupyter completion time: 19
07:40:05.208 [debug] Jupyter completion time: 5
07:40:05.213 [debug] Jupyter completion time: 10
07:40:05.217 [debug] Jupyter completion time: 13
07:40:05.221 [debug] Jupyter completion time: 12
07:40:05.230 [debug] Jupyter completion time: 8
07:40:05.234 [debug] Jupyter completion time: 12
07:40:05.237 [debug] Jupyter completion time: 8
07:40:05.241 [debug] Jupyter completion time: 10
07:40:05.249 [debug] Jupyter completion time: 6
07:40:05.254 [debug] Jupyter completion time: 10
...
```

### Coding Language and Runtime Version

Python 3.11.8

### Language Extension Version (if applicable)

Python v2024.0.1

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Please could you
[ms-toolsai-jupyter-insiders.vsix.zip](https://github.com/microsoft/vscode-jupyter/files/14411234/ms-toolsai-jupyter-insiders.vsix.zip)

* Please install VS Code Insiders (not stable)
* Download the attached file
* Extract this file
* Open VS Code and select the command `Install from VSIX`
* Select the above extracted VSIX
* When prompted to reload VS Code, please do so
* Try to replicate the issue once again

**Comment by DonJayamanne** [comment]
Also, do you have the [Jupyter Powertoys extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-powertoys)  installed?

**Comment by Alextron0102** [comment]
> > Yes, i do.
> 
> Please can you try disabling that extension and re-installing your old version of Jupyter extesnion (i.e. install v2024.1.1) Then try again.
> 
> The Poweroys extension is known to cause a few issues, I will be looking into that this week.

I installed powertoys because of the problem, to maybe help debug and let me close the kernel that stucks on that loop. But the interesting thing come as follows:

By uninstalling the vsix extension on the vscode insiders and installing the release (v2024.1.1), the problem appears again:
![image](https://github.com/microsoft/vscode-jupyter/assets/51174118/a438cd64-d823-47cd-b1ca-7239416a5e2e)

By disabling the power toys extension on vscode (not insiders) and typing, the problem continues to appear:
![image](https://github.com/microsoft/vscode-jupyter/assets/51174118/e4216ef1-3a10-4d13-a164-b7711fe24c23)

Any additional info let me know, i'm happy to help ^^

**Comment by DonJayamanne** [comment]
[ms-toolsai-jupyter-insiders.vsix (1).zip](https://github.com/microsoft/vscode-jupyter/files/14413570/ms-toolsai-jupyter-insiders.vsix.1.zip)

Please can you install this VSIX in VSCode insiders and let me know if the problem still persists?
Thanks for your help.
I'm trying to figure out whether the fix will be in tomorrows release or next month/
The first VSIX i gave contains fixes that will go int the next month,
The above VSIX is what we will ship as the next official relese in the next few days.

**Comment by Alextron0102** [comment]
> [ms-toolsai-jupyter-insiders.vsix (1).zip](https://github.com/microsoft/vscode-jupyter/files/14413570/ms-toolsai-jupyter-insiders.vsix.1.zip)
> 
> Please can you install this VSIX in VSCode insiders and let me know if the problem still persists? Thanks for your help. I'm trying to figure out whether the fix will be in tomorrows release or next month/ The first VSIX i gave contains fixes that will go int the next month, The above VSIX is what we will ship as the next official relese in the next few days.

Seems stable for me
![image](https://github.com/microsoft/vscode-jupyter/assets/51174118/2afe1806-5a48-44ec-865a-0dac3ce9ad33)

**Comment by DonJayamanne** [comment]
Thanks, closing this issue for now,
The fix will be in the next release (some time this week)
Thanks for your help.
