### ISSUE TITLE
Persistent "Jupyter API" message with remote SSH (but not local)...

### ISSUE THREAD

**Issue by ColinConwell** [microsoft/vscode-jupyter#15255]
The following message appears incessantly when running Jupyter Notebooks in VSCode via RemoteSSH:

> Thank you for trying the Jupyter API. Please file an issue on our repo to allow the extension unknown to use this API in production. This would prevent us from breaking your extension when updating the API (as it is still a work in progress).

The notification cannot be silenced, even when turning off notifications from the Jupyter Extension.

The notebook seems to be running correctly, and there are seemingly no other issues. I realize the message is likely thrown by the use of an extension, but I have dozens of extensions and systemtically isolating the extension that is causing the notification should likely not be the expected resolution. At minimum, it would be nice to be able to silence this message, since everything else appears to be working correctly. (The absence of the message on the local machine also suggests that the error is potentially not with any particular extension).

## Environment data

-   VS Code version: 1.86.2 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2024.1.2024012502 (pre-release)
-   Python Extension version (available under the Extensions sidebar): v2024.0.1
-   OS (Windows | Mac | Linux distro) and version: MacOS 14.3.1 (23D60) [Local] | Ubuntu 20.22 [Remote]
-   Jupyter server running: Local | Remote

## Expected Behavior

Messaging should be the same for the local and remote machine. If the use of the remote is causing the issue, but the notebook is functioning, we should be able to silence the message, no?

**Comment by ColinConwell** [comment]
Note: After some testing, it appears this _may_ be related to the Data Wranglers Extension -- but not in VSCode-Insiders?

**Comment by DonJayamanne** [comment]
Thank for you filing this issue and sorry you are running into this.
Please could you share the following verbose logs to help us identify where this is coming from.
The logs should contain some trace level informatio that will help us, thanks

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by ColinConwell** [comment]
Logs are copied below. I can confirm that at least the final four calls of:
> [warn] Publisher  is allowed to access the Kernel API with a message.

occur only after activating the DataWrangler Extension, and cease to repeat again once I disable it.

For your convenience, I have removed simplified this by removing some of the logs that repeat over multiple kernel instances.

> Visual Studio Code (1.86.2, ssh-remote, desktop)
> Jupyter Extension Version: 2024.1.1.
> Python Extension Version: 2024.0.1.
> Pylance Extension Version: 2024.2.2.
> Platform: linux (x64).
> Multiple Workspace folders opened /storage/colinconwell/workspace/_scriptexe, /storage/colinconwell/workspace/advantage/encomplexe
> 23:34:53.658 [debug] Get Custom Env Variables, Class name = Tm (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
> 23:34:53.659 [info] Start refreshing Kernel Picker (1709094893659)
> 23:34:53.677 [info] Using Pylance
> 23:34:54.311 [debug] Preferred Remote kernel for /storage/<username>/workspace/advantage/deep_social/social_pipe.ipynb is undefined
**> 23:34:55.677 [warn] Publisher  is allowed to access the Kernel API with a message.**
> 23:34:55.685 [debug] API called from unknown
> 23:34:56.714 [debug] Get Custom Env Variables, Class name = Tm, completed in 3057ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
> 23:34:56.714 [debug] Jupyter Paths /kernels: 
> 23:34:56.715 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, /.local/share/jupyter/kernels
> 23:34:56.815 [debug] Search for KernelSpecs in Interpreter /usr/bin/python
> 23:34:56.815 [debug] Finding Global Python KernelSpecs
> 23:34:56.827 [debug] Search for KernelSpecs in Interpreter /bin/python
> 23:34:56.830 [debug] Search for KernelSpecs in Interpreter /storage/<username>/miniforge3/envs/synthese/bin/python
> 23:34:56.830 [debug] Search for KernelSpecs in Interpreter /storage/<username>/miniforge3/bin/python
> 23:34:56.832 [debug] Search for KernelSpecs in Interpreter /storage/<username>/miniforge3/envs/rserver/bin/python
> 23:34:56.833 [debug] Search for KernelSpecs in Interpreter /usr/bin/X11/python
> 23:34:56.834 [debug] Full interpreter list is length: 14, /usr/bin/python::Unknown:/usr/bin/python, /bin/python::Unknown:/bin/python, /usr/bin/python::Unknown:/usr/bin/python, 
> /storage/<username>/micromamba/envs/replicaMFT/bin/python:replicaMFT:Conda:/storage/<username>/micromamba/envs/replicaMFT/bin/python, /storage/<username>/miniforge3/envs/synthese/bin/python:synthese:Conda:/storage/<username>/miniforge3/envs/synthese/bin/python,
> /storage/<username>/miniforge3/envs/synthese/bin/python:synthese:Conda:/storage/<username>/miniforge3/envs/synthese/bin/python,
> 23:34:56.838 [debug] Getting activated env variables, Class name = mp (started execution), Arg 1: "/storage/<username>/workspace/_scriptexe", Arg 2: "/storage/<username>/miniforge3/envs/synthese/bin/python", Arg 3: undefined
> 23:34:56.838 [debug] Get Custom Env Variables, Class name = Tm (started execution), Arg 1: "/storage/<username>/workspace/_scriptexe", Arg 2: "RunPythonCode"
> 23:34:56.839 [debug] Get Custom Env Variables, Class name = Tm, completed in 1ms, has a truthy return value, Arg 1: "/storage/<username>/workspace/_scriptexe", Arg 2: "RunPythonCode"
> 23:34:56.986 [debug] Error in detecting whether url is isJupyterHub: FetchError: request to http://localhost:8950/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8950
> 23:34:57.009 [debug] Kernels for interpreter /usr/bin/python are .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher
> 23:34:57.011 [debug] Kernels for interpreter /bin/python are .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
> 23:34:57.012 [debug] Kernels for interpreter /storage/<username>/miniforge3/bin/python are .jvsc74a57bd054afd49dc1a55979cab352f47427df250df7754581bd13d45f3da62b69d26be0./storage/<username>/miniforge3/python./storage/<username>/miniforge3/python.-m#ipykernel_launcher
> 23:34:57.012 [debug] Kernels for interpreter /usr/bin/X11/python are .jvsc74a57bd02636b3513b3f1288d9e07636fd7ce7b783df2b7968b1a7153844bb9cd2aa11d5./usr/bin/X11/python./usr/bin/X11/python.-m#ipykernel_launcher
> 23:34:57.298 [debug] KernelProvider switched kernel to id = .jvsc74a57bd075f824c3b687079921b405435f95fff61212657e05ac5235ee8e1311f32ff6e5./storage/<username>/miniforge3/envs/synthese/python./storage/<username>/miniforge3/envs/synthese/python.-m#ipykernel_launcher
> 23:34:57.300 [debug] Initialize notebook communications for editor /storage/<username>/workspace/advantage/deep_social/social_pipe.ipynb
> 23:34:57.300 [debug] Resolving notebook UI Comms (resolve) for /storage/<username>/workspace/advantage/deep_social/social_pipe.ipynb
> 23:34:57.300 [debug] initialize CommonMessageCoordinator
> 23:34:57.321 [debug] Registering commtarget jupyter.widget
> 23:34:57.321 [debug] IPyWidgetMessageDispatcher.initialize
> 23:34:57.322 [debug] Attempting to determine version of IPyWidgets
> 23:34:57.322 [debug] Controller selection change completed
> 23:34:57.323 [debug] Waiting for IPyWidgets version
> 23:34:57.323 [debug] Waiting for IPyWidgets version promise
> 23:34:57.325 [error] Failed to validate Password info D [FetchError]: request to http://localhost:8950/tree? failed, reason: connect ECONNREFUSED 127.0.0.1:8950
>     at ClientRequest.<anonymous> (/storage/<username>/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/node-fetch.js:1:306417)
>     at ClientRequest.emit (node:events:514:28)
>     at Socket.socketErrorListener (node:_http_client:501:9)
>     at Socket.emit (node:events:514:28)
>     at emitErrorNT (node:internal/streams/destroy:151:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
>     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
>   type: 'system',
>   errno: 'ECONNREFUSED',
>   code: 'ECONNREFUSED'
> }
> 23:34:57.348 [debug] Loading kernelspec from /.local/share/jupyter/kernels/python3/kernel.json 
> 23:34:57.399 [error] Error fetching kernels from http://localhost:8950/ (Jupyter-App): FetchError: request to http://localhost:8950/api/kernels?1709094897334 failed, reason: connect ECONNREFUSED 127.0.0.1:8950
>     at ClientRequest.<anonymous> (/storage/<username>/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/node-fetch.js:1:306417)
>     at ClientRequest.emit (node:events:514:28)
>     at Socket.socketErrorListener (node:_http_client:501:9)
>     at Socket.emit (node:events:514:28)
>     at emitErrorNT (node:internal/streams/destroy:151:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
>     at processTicksAndRejections (node:internal/process/task_queues:82:21)
> 23:34:57.399 [debug] Disposing Jupyter Lab Helper
> 23:34:57.399 [debug] SessionManager - dispose contents manager
> 23:34:57.400 [debug] ShutdownSessionAndConnection - dispose session manager
> 23:34:57.403 [debug] Finished disposing Jupyter Lab Helper
> 23:34:57.403 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache FetchError: request to http://localhost:8950/api/kernels?1709094897334 failed, reason: connect ECONNREFUSED 127.0.0.1:8950
>     at ClientRequest.<anonymous> (/storage/<username>/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/node-fetch.js:1:306417)
>     at ClientRequest.emit (node:events:514:28)
>     at Socket.socketErrorListener (node:_http_client:501:9)
>     at Socket.emit (node:events:514:28)
>     at emitErrorNT (node:internal/streams/destroy:151:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
>     at processTicksAndRejections (node:internal/process/task_queues:82:21)
> 23:34:57.403 [debug] UniversalRemoteKernelFinder: Writing 0 remote kernel connection metadata to cache
> 23:34:57.403 [error] Jupyter Lab Helper:getKernelSpecs failure:  Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
>     at v.dispose (/storage/<username>/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:10935)
>     at ni.dispose (/storage/<username>/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:29299)
>     at r.dispose (/storage/<username>/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:139:4518)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Promise.all (index 0)
>     at VD.listKernelsFromConnection (/storage/<username>/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:20060)
>     at /storage/<username>/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:17485
> 23:34:57.709 [debug] Hiding default kernel spec 'Python 3 (ipykernel)', 'pythonjvsc74a57bd014ee1abc7e2a49a43d216538d94486bdf284c3c6a675e3d8548e1bc9b8d41b64', /storage/<username>/miniforge3/envs/jupyter/bin/python for interpreter /storage/<username>/miniforge3/envs/jupyter/bin/python and spec /storage/<username>/miniforge3/envs/jupyter/share/jupyter/kernels/python3/kernel.json
> 23:34:57.710 [debug] Kernels for interpreter /storage/<username>/miniforge3/envs/jupyter/bin/python are .jvsc74a57bd014ee1abc7e2a49a43d216538d94486bdf284c3c6a675e3d8548e1bc9b8d41b64./storage/<username>/miniforge3/envs/jupyter/python./storage/<username>/miniforge3/envs/jupyter/python.-m#ipykernel_launcher
> 23:34:58.129 [info] End refreshing Kernel Picker (1709094893659)
> 23:34:58.419 [debug] Conda file returned by Python Extension is conda
> 23:34:59.820 [debug] Got env vars with python /storage/<username>/miniforge3/envs/synthese/bin/python, with env var count 62 in 2982ms. 
>     PATH value is /storage/<username>/workspace/_scriptexe/.micromamba:/storage/<username>/.vscode-server/cli/servers/Stable-903b1e9d8990623e3d7da1df3d33db3e42d80eda/server/bin/remote-cli:/storage/<username>/miniforge3/envs/synthese/bin:/storage/<username>/miniforge3/condabin:/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/csail/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games and 
>     Path value is undefined
> 23:34:59.820 [debug] Prepend PATH with python bin for /storage/<username>/miniforge3/envs/synthese/bin/python
> 23:34:59.820 [debug] Activated Env Variables for /storage/<username>/miniforge3/envs/synthese/bin/python, 
>     PATH value is /storage/<username>/miniforge3/envs/synthese/bin:/storage/<username>/workspace/_scriptexe/.micromamba:/storage/<username>/.vscode-server/cli/servers/Stable-903b1e9d8990623e3d7da1df3d33db3e42d80eda/server/bin/remote-cli:/storage/<username>/miniforge3/envs/synthese/bin:/storage/<username>/miniforge3/condabin:/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/csail/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games and 
>     Path value is undefined
> 23:34:59.827 [debug] Getting activated env variables, Class name = mp, completed in 2989ms, has a truthy return value, Arg 1: "/storage/<username>/workspace/_scriptexe", Arg 2: "/storage/<username>/miniforge3/envs/synthese/bin/python", Arg 3: undefined
> 23:34:59.856 [info] Process Execution: /storage/<username>/miniforge3/envs/synthese/bin/python -m pip list
**> 23:35:12.581 [warn] Publisher  is allowed to access the Kernel API with a message.
> 23:35:14.873 [warn] Publisher  is allowed to access the Kernel API with a message.
> 23:35:16.931 [warn] Publisher  is allowed to access the Kernel API with a message.
> 23:35:18.095 [warn] Publisher  is allowed to access the Kernel API with a message.**

**Comment by ColinConwell** [comment]
Again, I am able to prevent all but the first instance of the message by disabling DataWrangler.

I think, depending on how you interpret this, that a viable action item would still be the ability to silence the error notification with an optional user setting.

Thanks for your rapid response!

**Comment by DonJayamanne** [comment]
@ColinConwell 
Please can you install the latest version of Jpuyter extension.
Let me know if you are still running into this.

**Comment by DonJayamanne** [comment]
Please could you
* Update to the latest version of VS Code 1.87
* Download the attached file
* Extract this file
* Open VS Code and select the command `Install from VSIX`
* Select the above extracted VSIX
* When prompted to reload VS Code, please do so
* Try to replicate the issue once again
* Then please provide the logs

The new logs should contain an entry `Unable to determine the caller of the extension API for trace stack`
Please share the logs with that line along with the lines after that
[ms-toolsai-jupyter-insiders.vsix (1).zip](https://github.com/microsoft/vscode-jupyter/files/14476814/ms-toolsai-jupyter-insiders.vsix.1.zip)

**Comment by ColinConwell** [comment]
This is the log output you requested, I think. I triggered this again with the DataWranglers extension.

> 00:48:49.034 [error] Unable to determine the caller of the extension API for trace stack. Error: 
>     at Pg.determineExtensionFromCallStack (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.0/dist/extension.node.js:203:3695)
>     at SI.getService (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.0/dist/extension.node.js:408:21206)
>     at O9 (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.0/dist/extension.node.js:198:24858)
>     at Object.getKernelService (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.0/dist/extension.node.js:198:26331)
>     at Fi.getKernelSession (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.datawrangler-0.29.0/out/extension.js:2:1985473)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at Ii.getCellStatusBarItemForCell (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.datawrangler-0.29.0/out/extension.js:2:1981744)
>     at h.$provideNotebookCellStatusBarItems (/storage/<username>/.vscode-insiders/cli/servers/Insiders-bb171489789c9a49e985a4a2c8694138d70d42c1/server/out/vs/workbench/api/node/extensionHostProcess.js:155:3705)

Note that this error does not occur locally, only on Remote SSH. Also note that this is with a VS-Code-Insiders installation I have (I cannot currently mess with my main VSCode stable setup). Let me know if that's an issue and I can potentially do this same operation on a Stable install sometime soon.

**Comment by ColinConwell** [comment]
It seems I can also trigger it just with Jupyter PowerToys:

> 01:00:15.561 [error] Unable to determine the caller of the extension API for trace stack. Error: 
	at Pg.determineExtensionFromCallStack (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.0/dist/extension.node.js:203:3695)
	at O9 (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.0/dist/extension.node.js:198:24761)
	at Object.getKernelService (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.0/dist/extension.node.js:198:26331)
	at activateFeature (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.vscode-jupyter-powertoys-0.1.0/out/main.js:335:56)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async activate (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.vscode-jupyter-powertoys-0.1.0/out/main.js:343:9)
	at async activate (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.vscode-jupyter-powertoys-0.1.0/out/main.js:13995:5)
	at async u.n (/storage/<username>/.vscode-insiders/cli/servers/Insiders-bb171489789c9a49e985a4a2c8694138d70d42c1/server/out/vs/workbench/api/node/extensionHostProcess.js:140:6255)
	at async u.m (/storage/<username>/.vscode-insiders/cli/servers/Insiders-bb171489789c9a49e985a4a2c8694138d70d42c1/server/out/vs/workbench/api/node/extensionHostProcess.js:140:6218)
	at async u.l (/storage/<username>/.vscode-insiders/cli/servers/Insiders-bb171489789c9a49e985a4a2c8694138d70d42c1/server/out/vs/workbench/api/node/extensionHostProcess.js:140:5675)
01:00:15.566 [error] Unable to determine the caller of the extension API for trace stack. Error: 
	at Pg.determineExtensionFromCallStack (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.0/dist/extension.node.js:203:3695)
	at SI.getService (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.0/dist/extension.node.js:408:21206)
	at O9 (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.0/dist/extension.node.js:198:24858)
	at Object.getKernelService (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.0/dist/extension.node.js:198:26331)
	at activateFeature (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.vscode-jupyter-powertoys-0.1.0/out/main.js:335:56)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async activate (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.vscode-jupyter-powertoys-0.1.0/out/main.js:343:9)
	at async activate (/storage/<username>/.vscode-insiders/extensions/ms-toolsai.vscode-jupyter-powertoys-0.1.0/out/main.js:13995:5)
	at async u.n (/storage/<username>/.vscode-insiders/cli/servers/Insiders-bb171489789c9a49e985a4a2c8694138d70d42c1/server/out/vs/workbench/api/node/extensionHostProcess.js:140:6255)
	at async u.m (/storage/<username>/.vscode-insiders/cli/servers/Insiders-bb171489789c9a49e985a4a2c8694138d70d42c1/server/out/vs/workbench/api/node/extensionHostProcess.js:140:6218)
	at async u.l (/storage/<username>/.vscode-insiders/cli/servers/Insiders-bb171489789c9a49e985a4a2c8694138d70d42c1/server/out/vs/workbench/api/node/extensionHostProcess.js:140:5675)

**Comment by DonJayamanne** [comment]
Thanks for the logs. Will try to get a fix

**Comment by DonJayamanne** [comment]
I'm going to share another VSIX, please can you try this again and share the logs
I should be able to get this resolved.

You might have logs with the following lines
* Regex failed to parse stack frame
* Parsed file name in stack
* Unable to parse file name in stack
* Unable to determine the caller of the extension API for trace stack
* Frames.
* Jupyter Extension Root.

Please share all of the above logs in the same order,
Once again, thanks for your patience and help.

Here's the new VSIX
[ms-toolsai-jupyter-insiders.vsix.zip](https://github.com/microsoft/vscode-jupyter/files/14477275/ms-toolsai-jupyter-insiders.vsix.zip)

**Comment by ColinConwell** [comment]
Attached are all logs (unabridged) with the new VSIX install in Insiders:

[jupyter_vsix_logs.txt](https://github.com/microsoft/vscode-jupyter/files/14486942/jupyter_vsix_logs.txt)

**Comment by DonJayamanne** [comment]
Please try this vsix, hopefully this will work.

[ms-toolsai-jupyter-insiders.vsix.zip](https://github.com/microsoft/vscode-jupyter/files/14493575/ms-toolsai-jupyter-insiders.vsix.zip)

**Comment by DonJayamanne** [comment]
**Steps to repro**
* Install data wrangler extension
* Open a Jupyter notebook
* Run a cell
Verify you do not see a prompt with the message similar to the following `Thank you for trying the Jupyter API. Please file an issue on our repo to allow the extension unknown to use this API in production. This would prevent us from breaking your extension when updating the API (as it is still a work in progress).`
