### ISSUE TITLE
Jupyter Notebook Freezes / Does not connect to renderer

### ISSUE THREAD

**Issue by jakubLangr** [microsoft/vscode-jupyter#15259]
## Environment data

-   VS Code version:
Version: 1.86.2
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:42:12.210Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0
-   Jupyter Extension version (available under the Extensions sidebar): Latest  / Pre-Realease / Previous (all tried)
-   Python Extension version (available under the Extensions sidebar): Latest / Pre-lease (all tried)
-   OS (Windows | Mac | Linux distro) and version: OS (14.3.0)
-   Python and/or Anaconda version: 3.10 / 3.12  (all tried)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

Jupyter Notebook works / not frozen

## Actual behaviour

Either Jupyter Ntb Freezes like this
![Screenshot 2024-02-28 at 13 18 39](https://github.com/microsoft/vscode-jupyter/assets/1884004/5c027a1b-98d6-4812-8a5a-27284630bf2b)

Or does not load at all (just background color, no cells)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

Upon reinstalling, the render works for ~1 second and then it refuses to update. Eg print('test1') -> prints test1 -> print('test2') -> cell runs but text remains test1 

print in a new cell print('test323') -> cell runs but no output shown

## Logs
When trying this (is this the right thing?)
![Screenshot 2024-02-28 at 13 23 05](https://github.com/microsoft/vscode-jupyter/assets/1884004/a0eddfe0-6801-4c24-bc9d-e2aa23384fe2)
I get this:
![Screenshot 2024-02-28 at 13 22 56](https://github.com/microsoft/vscode-jupyter/assets/1884004/e58ee784-d39a-49c8-b3cc-fa21f8585b7f)
<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
I'm very sorry this issue didn't get looked at, some how it slipped through the cracks and out bot didn't assign this to anyone.
Are you still running into this issue?
