### ISSUE TITLE
Make sure to use `resolveEnvironment` for the selected Python kernel to get version information

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode-jupyter#15254]
Opening based on https://github.com/microsoft/vscode-python/issues/22877#issuecomment-1966626259. It seems that currently if the details are available in `environments.known`, we use that, else we get it from `resolveEnvironment`.

Related: https://github.com/microsoft/vscode-jupyter/issues/15140

**Comment by DonJayamanne** [comment]
We are already doing this

**Comment by DonJayamanne** [comment]
@karrtikr Found that there could be a race condition here, will look at modifying the code to always call resolve when getting the version.

**Comment by DonJayamanne** [comment]
Done https://github.com/microsoft/vscode-jupyter/pull/15261
