### ISSUE TITLE
Asynchronous code is unreliable when using the Deno kernel

### ISSUE THREAD

**Issue by sorenlouv** [microsoft/vscode-jupyter#15277]
I am using the Deno kernel with the Jupyter Extension for vscode. I have noticed that asynchronous responses are not correctly displayed and I often have to execute the cell multiple times before seeing a response. This is especially problematic when calling mutating APIs where it is not possible to execute them more than once. 
Instead of seeing the response I either see a stale response (from a previous invocation) or `Promise { <pending> }`

**Reproduce**

1. Install Deno by following the descriptions [here](https://docs.deno.com/runtime/manual/tools/jupyter):

```
deno jupyter --unstable --install
```

2. Select Deno as Kernel

3. Execute the following notebook. After each execution try incrementing `/todos/1` to `/todos/2`, `/todos/3`, and see how the response does not always update reliably. 

```ts
fetch('https://jsonplaceholder.typicode.com/todos/1')
      .then(response => response.json())
      .then(json => console.log(json))     
```

<img width="1045" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/209966/8c96385e-ae07-4806-a67e-50285f828b0d">

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and sorry you are running into this.
Unfortunately this is an issue with the Deno kernel.

I can replicate the exact same behaviour in Jupyter Lab (i.e. outside VS Code)
Please file an issue against Deno kernel repo.
<img width="488" alt="Screenshot 2024-03-04 at 11 10 44" src="https://github.com/microsoft/vscode-jupyter/assets/1948812/e17a9791-bbfc-4e6e-8f5d-bbcf3e3d15d5">
