### ISSUE TITLE
Make cells (# %%) collapsible python files

### ISSUE THREAD

**Issue by oerpli** [microsoft/vscode-jupyter#1527]
## Environment data

- VS Code version: 1.33
- Extension version (available under the Extensions sidebar): Current
- OS and version: Win10 1703
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
- Relevant/affected Python packages and their versions: n/a
## Expected behaviour

In a document with multiple cells, collapsing some of them improves usability.

## Actual behaviour

It is not possible to collapse cells.

## Some Details

I think defining `#%%` as (collapsible region start) shouldn't be very hard (I can try to submit a PR in 1-2 weekends if you agree with the idea). 

Some implementation details should be evaluated though:

- Behavior of Shift+Enter in the cell above
- What to display if a region is collapsed (`#%% Comment ...` would be the default I think)
- Behavior of collapsed regions affected by `Run below|above`
- Visibility of `Run Cell | Run Above | Run Below`

**Comment by pythlang** [comment]
Temp comment bump for now as I've just stumbled across this while working and also desire this... I may be able to take a stab at this in a few weeks here with some guidance while I have some free time. 

Let me get back to this comment later.


![Screen Shot 2020-11-30 at 13 37 04](https://user-images.githubusercontent.com/23020467/100650405-e0912000-3311-11eb-9ace-f10e8449dbfc.png)

**Comment by retorquere** [comment]
> I believe the only way to do this would be with the outline support VS Code has already:
> https://code.visualstudio.com/api/references/vscode-api#FoldingRangeProvider
> 
> As far as I can tell, the start line remains visible, so you'd probably end up with something like:
> 
> #%%

Would `# %% # some comment` work?

**Comment by ruestefa** [comment]
> Would # %% # some comment work?

You can add comments directly after `# %%` even without an additional `#`.

**Comment by chenhao1umbc** [comment]
It has been more than 2 years, since the original post...

**Comment by Diogo-Rossi** [comment]
For anyone still waiting for this (like me), I found a way that worked for me. It is the simple setting bellow (in case it help someone):

Expand  the "Regular expression used to identify code cells" (in the settings) to also recognize the expression `#\\s*region`

`"jupyter.codeRegularExpression": "^(#\\s*%%|#\\s*\\<codecell\\>|#\\s*In\\[\\d*?\\]|#\\s*In\\[ \\]|#\\s*region)"` <- here

Now the cells also starts with `# region` and I can close the folding area  with `# endregion`, making the cells collapsible.

**Comment by PrateekArya** [comment]
Yes, it works! But I am using a modified version as follows so that I can also write comments on the top of my cells:

![image](https://user-images.githubusercontent.com/1255663/124281369-f0900d00-db49-11eb-8ceb-517e28ffedd8.png)

Here if u just want to copy it:
^(#\s*region\s*%%|#\s*\<codecell\>|#\s*In\[\d*?\]|#\s*In\[ \])

Now, I write the cell headers as:

![image](https://user-images.githubusercontent.com/1255663/124281549-1a493400-db4a-11eb-965e-122d0a2d5eed.png)

and the end of cell and starting of next cell as:

![image](https://user-images.githubusercontent.com/1255663/124281633-32b94e80-db4a-11eb-8559-8e0b144857fd.png)

**Comment by Diogo-Rossi** [comment]
@PrateekArya 

Nice! But just to make it clear: you regular expression requires that the cell starts with `# region %%`.

Basically, you have not added a new pattern but modified the regular `# %%` to `# region %%`.

That is ok. But if you find working with some file with previous pattern `%%` that won't be a cell anymore.

BTW, any of that patterns allow you to to write comments on the top of cells.

**Comment by PrateekArya** [comment]
Yes. I agree! :)

**Comment by vikassharma555** [comment]
@Diogo-Rossi Thanks your fix works...I am currently using VSCode Insider V.1.60. Accidently I was able to make the usual # %% collapsible. Write # %% + press enter + tab + # region. 
code looks like this ->
# %%
    #region
#endregion

# %% folding works...
![Folding_VSCode](https://user-images.githubusercontent.com/89971860/131817441-a6fc249b-cc2d-4f39-ad8c-13e1f4888350.png)

**Comment by Diogo-Rossi** [comment]
I found a better solution. Maybe you are interesting too.

1. Install [this extension](https://marketplace.visualstudio.com/items?itemName=zokugun.explicit-folding)
2. Config the setting `"editor.foldingStrategy"` to `"auto"` (i.e.: `"editor.foldingStrategy":"auto"`)
3. Add the following in the settings:
```
"explicitFolding.rules": {
    "python": [
        {
            "separatorRegex": <PUT HERE THE SAME REGEX USED IN THE SETTING "jupyter.codeRegularExpression">
            "foldEOF":true
        },
    ]
}
```
Now everything works.
* All the expressions in used in `"jupyter.codeRegularExpression"` define cells that are collapsible.
* There is no need of any additional line (i.e. `# endregion`) to close the collapsible regions.
* It now works exactly the same as the cells in spyder

**Comment by rebornix** [comment]
@Diogo-Rossi thanks for the solution, it works seamlessly. 

```
"explicitFolding.rules": {
        "python": [
            {
                "separatorRegex": "# %%",
                "foldEOF":true
            }
        ]
    }
```

We could probably register a similar folding range provider in Jupyter oob.

**Comment by otaolafranc** [comment]
Hello, 
doing what was mentionned above, added the possibility to fold using "# %%" but it removed the possibility to fold for functions (def) or (for). anyone that could give me a hand to solve this issue?

> I found a better solution. Maybe you are interesting too.
> 
> 1. Install [this extension](https://marketplace.visualstudio.com/items?itemName=zokugun.explicit-folding)
> 2. Config the setting `"editor.foldingStrategy"` to `"auto"` (i.e.: `"editor.foldingStrategy":"auto"`)
> 3. Add the following in the settings:
> 
> ```
> "explicitFolding.rules": {
>     "python": [
>         {
>             "separatorRegex": <PUT HERE THE SAME REGEX USED IN THE SETTING "jupyter.codeRegularExpression">
>             "foldEOF":true
>         },
>         {
>             "indentation": true,
>             "offSide": true
>         }
>     ]
> }
> ```
> 
> Now everything works.
> 
> * All the expressions used in `"jupyter.codeRegularExpression"` define cells that are collapsible. (including `#%%`)
> * There is no need of any additional line (i.e. `# endregion`) to close the collapsible regions.
> * It now works exactly the same as the cells in spyder

**Comment by Diogo-Rossi** [comment]
@otaolafranc 
It seems we don't need this suggestion anymore  to fold using `#%%`. It is now part of the extension.
