### ISSUE TITLE
There is an issue with rendering in WSL

### ISSUE THREAD

**Issue by dcdmm** [microsoft/vscode-jupyter#15288]
![image](https://github.com/microsoft/vscode-jupyter/assets/75072088/5691ab18-9f6e-4ee2-bc69-c5ff45a7be25)
![image](https://github.com/microsoft/vscode-jupyter/assets/75072088/a55de9cc-0486-468f-8dc4-d2f9b4e1aea6)
Code not rendered or rendering error

**Comment by dcdmm** [comment]
Also, it is not possible to enter the function internally, so it is necessary to close the notebook file and then open it to be effective

**Comment by darkopetrovic** [comment]
Got similar issues since the last update of vscode.

Original loaded cell:
![image](https://github.com/microsoft/vscode-jupyter/assets/1554288/5e04727f-02e5-4b32-8b07-2be62b482160)

Adding space between:

![image](https://github.com/microsoft/vscode-jupyter/assets/1554288/74afd6ab-7aa5-4cce-a0f8-ef6597f44e25)

Writing new code in the cell:

![image](https://github.com/microsoft/vscode-jupyter/assets/1554288/2ec6fc57-1769-4379-9668-82fc34274240)
![image](https://github.com/microsoft/vscode-jupyter/assets/1554288/8590378b-c174-4695-af6f-4f6aa3288ef7)

**Comment by Don-Felice** [comment]
Seeing similar issues also without using WSL since the last update (Jupyter: v2024.2.0).
Seems so far as if only notebooks which existed already before the update are affected.

**Comment by dcdmm** [comment]
> 自上次更新 vscode 以来遇到了类似的问题。
> 
> 原始加载单元： ![图像](https://private-user-images.githubusercontent.com/1554288/309755699-5e04727f-02e5-4b32-8b07-2be62b482160.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjgzMTYsIm5iZiI6MTcwOTYyODAxNiwicGF0aCI6Ii8xNTU0Mjg4LzMwOTc1NTY5OS01ZTA0NzI3Zi0wMmU1LTRiMzItOGIwNy0yYmU2MmI0ODIxNjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDg0MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDIzZGUxODgwZWJiMWRlYTBjNDcyMzQxMzBhYzliNmY2NGU4ZmQ0NzRlNzgzODlhZGMyNTc1N2RiNmE3YzU5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GLrxnU0mhuOBx4idSuV_NmzI-QbUfOX-EhCYATzRwyk)
> 
> 在以下内容之间添加空格：
> 
> ![图像](https://private-user-images.githubusercontent.com/1554288/309755769-74afd6ab-7aa5-4cce-a0f8-ef6597f44e25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjgzMTYsIm5iZiI6MTcwOTYyODAxNiwicGF0aCI6Ii8xNTU0Mjg4LzMwOTc1NTc2OS03NGFmZDZhYi03YWE1LTRjY2UtYTBmOC1lZjY1OTdmNDRlMjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDg0MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTczMzJmNGVmZjBhMTZlM2U3ZTY4ZGYxZTI0MzU4NTJlMTBmMGRjODJmOTRhZTcyNGE0NWU0MjdmYWYxNWFiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dOWzfyNAdkB4gPJBoni1nAOL4a8Vm1o2sZfZr-D2HNQ)
> 
> 在单元格中编写新代码：
> 
> ![图像](https://private-user-images.githubusercontent.com/1554288/309756202-2ec6fc57-1769-4379-9668-82fc34274240.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjgzMTYsIm5iZiI6MTcwOTYyODAxNiwicGF0aCI6Ii8xNTU0Mjg4LzMwOTc1NjIwMi0yZWM2ZmM1Ny0xNzY5LTQzNzktOTY2OC04MmZjMzQyNzQyNDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDg0MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzAwN2I2Njk5M2IwYWFlYjc2OWIyZjJiNzU4MGRlNDE2YjkzYmVhMzhlZTJjMTUxNThjMGFlYTg5NTZkNGVhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4TjaluG_xNVr89FxnAMMJEz1La7iXSUGOtZJu2yFsFM) ![图像](https://private-user-images.githubusercontent.com/1554288/309757184-8590378b-c174-4695-af6f-4f6aa3288ef7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjgzMTYsIm5iZiI6MTcwOTYyODAxNiwicGF0aCI6Ii8xNTU0Mjg4LzMwOTc1NzE4NC04NTkwMzc4Yi1jMTc0LTQ2OTUtYWY2Zi00ZjZhYTMyODhlZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDg0MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzIzY2U2NTMwZGRkYWJiOGVkZmVjNzdlMjk0NThiNDQwZDcyZjM1ODAzNGFlZTk2YjliZDFhN2E2ZTE5OTUyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t5iDWne7xFXSKaaojFDQS6bdUNbXHmlmVn7CgGSvn8U)
> 
> Jupyter 扩展版本：v2024.2.2024022602（预发布）
> 
> 快速解决方法：删除单元格并按 Ctrl+Z，或将单元格切换到 markdown (M)，然后返回代码 (Y)

Thank you, I'll try it

**Comment by dcdmm** [comment]
> 自上次更新 vscode 以来遇到了类似的问题。
> 
> 原始加载单元： ![图像](https://private-user-images.githubusercontent.com/1554288/309755699-5e04727f-02e5-4b32-8b07-2be62b482160.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mjg2OTcsIm5iZiI6MTcwOTYyODM5NywicGF0aCI6Ii8xNTU0Mjg4LzMwOTc1NTY5OS01ZTA0NzI3Zi0wMmU1LTRiMzItOGIwNy0yYmU2MmI0ODIxNjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDg0NjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTQ5MmQwODY1N2VjZmYxNzQ5YjRlYzNmNTFiZmU1NDc0ODYzOTdmMGNjZjg2NjQ5ZDIxZWQzMWJiM2U3Yzk3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IfpIbcoy7RyYwiMGCiDX7oXovQIG0ub7Lf5bcBS8zng)
> 
> 在以下内容之间添加空格：
> 
> ![图像](https://private-user-images.githubusercontent.com/1554288/309755769-74afd6ab-7aa5-4cce-a0f8-ef6597f44e25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mjg2OTcsIm5iZiI6MTcwOTYyODM5NywicGF0aCI6Ii8xNTU0Mjg4LzMwOTc1NTc2OS03NGFmZDZhYi03YWE1LTRjY2UtYTBmOC1lZjY1OTdmNDRlMjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDg0NjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWIwNTk5YmZhYjQxYjA4ZmUwODVjZWMwOGQzMTI5MDc0NDZlZjljYzNlNWZhODVhNWMzNDlmMzA3OTMxN2Y5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.opnEQyJvPEcqcQ3HYhh1snZmdWewfjV4lUtanJFa0FU)
> 
> 在单元格中编写新代码：
> 
> ![图像](https://private-user-images.githubusercontent.com/1554288/309756202-2ec6fc57-1769-4379-9668-82fc34274240.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mjg2OTcsIm5iZiI6MTcwOTYyODM5NywicGF0aCI6Ii8xNTU0Mjg4LzMwOTc1NjIwMi0yZWM2ZmM1Ny0xNzY5LTQzNzktOTY2OC04MmZjMzQyNzQyNDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDg0NjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGJkNzE3NjE1OWQ5N2E0MjE0NzIxMGI5YTlkNGJiYTRmYmRkZDhjNTQ5ZTYwYmYyMzZhZTllNDdkNDEzM2QyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5VwoESYloQpFjNtkKEy-yhwWHmqnVaY055Gm0bu7ZWo) ![图像](https://private-user-images.githubusercontent.com/1554288/309757184-8590378b-c174-4695-af6f-4f6aa3288ef7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mjg2OTcsIm5iZiI6MTcwOTYyODM5NywicGF0aCI6Ii8xNTU0Mjg4LzMwOTc1NzE4NC04NTkwMzc4Yi1jMTc0LTQ2OTUtYWY2Zi00ZjZhYTMyODhlZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDg0NjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQxNjFjOTQwZGQ3YWZlNmNkNDAzNjM1OGMyMjY2MDA2NzRmNTUzZTQ0MTkxMzQ3YjUyYjhkYjZmYmZhODMxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RuJRbuzYNBHVA2KpP6U22cAWjGGWpPnhC2iFdTNfKcY)
> 
> Jupyter 扩展版本：v2024.2.2024022602（预发布）
> 
> 快速解决方法：删除单元格并按 Ctrl+Z，或将单元格切换到 markdown (M)，然后返回代码 (Y)

It still doesn’t work in my notebook. I have to close the file again and reopen it.

**Comment by dreamwayjgs** [comment]
Same issue in remote container (docker). 
I cannot see any logs but Python Language Server says repeatedly: "Received change text document command for closed file."
I did not have this issue in the last month. I got this one after update in this Monday.

**Comment by rick-van-bijnen** [comment]
I have the same issue, with garbled syntax highlighting for jupyter notebooks in vscode. It seems to be similar to this one from 2 years ago:

https://www.reddit.com/r/vscode/comments/rh5irl/syntax_highlighting_is_completely_broken_outside/

Note that deleting the settings.json file seemed to fix it back then for that person, but that's not something I want to (or should) do.

**Comment by debonte** [comment]
This is a bug in VS Code: https://github.com/microsoft/vscode/issues/206487

It's already fixed in VS Code Insiders and assuming the fix behaves well in insiders, [could ship VS Code stable as soon as tomorrow](https://github.com/microsoft/vscode/issues/206487#issuecomment-1979832053).

Alternatively, you can work around this issue by downgrading to the VS Code 1.86.2.
