### ISSUE TITLE
hover in code editor of  function show brief explain might be a good idea. 

### ISSUE THREAD

**Issue by q2333gh** [microsoft/vscode-jupyter#15282]
This is jupyter notebook hover look like :
![image](https://github.com/microsoft/vscode-jupyter/assets/32679742/75191426-eb61-4624-a001-b16e1d76dd91)

This is normal  .py file hover function explain look like :
![image](https://github.com/microsoft/vscode-jupyter/assets/32679742/eaf494e5-cc9d-4bfa-8708-a3f6a53e0dd1)

**Comment by DonJayamanne** [comment]
@q2333gh are you still experienceing this same issue?
Have you tried installing the Pylance extension?

**Comment by q2333gh** [comment]
fixed by install the vscode extension : `Pylance`
