### ISSUE TITLE
Improved data science debugging tools

### ISSUE THREAD

**Issue by jamesstidard** [microsoft/vscode-jupyter#1529]
Hi,

I've moved from using PyCharm as my daily driver to VSCode and there is one quite prominent feature that I miss. PyCharm has visualisations for libraries like `pandas`.

![data_view](https://user-images.githubusercontent.com/1797906/55576812-0d8acb00-570a-11e9-8d04-26ebf4d5b450.png)

This is extremely useful for debugging these kinda multi-dimensional and often large structures. It would be great to see some kind of tool like this in VSCode.

Additionally, library's like `numpy`, `pandas`, and `xarray`, provide pretty multi-line __repl__ and __str__ representations. However, these are also not very usable in VSCode at the moment.

For example when in debug mode and using the Debug Console, newlines are printed as a literal "\n". This makes the __repr__ output (that might have been a nice stop-gap solution to the feature suggested above) also not a particularly great alternative.

### Debug Console Print
<img width="433" alt="Screenshot 2019-04-04 at 6 56 23 pm" src="https://user-images.githubusercontent.com/1797906/55577469-91918280-570b-11e9-8f79-5edce0589499.png">

### IPython
<img width="448" alt="Screenshot 2019-04-04 at 6 57 43 pm" src="https://user-images.githubusercontent.com/1797906/55577540-b8e84f80-570b-11e9-987b-ac45bee5432f.png">

Would also be happy to hear about maybe any plugins that could help address this or how other's use VSCode Debugger + Python Data Science libs.

Thanks.

**Comment by DavidKutu** [comment]
Dupe of #1283
