### ISSUE TITLE
The extension should notify the user to install Python and the Python extension when attempting to export a notebook if they are not installed

### ISSUE THREAD

**Issue by xiaoxi-david** [microsoft/vscode-jupyter#15309]
Currently, the extension requires Python and the Python extension to export a Jupyter notebook. But, if you lack either, the drop-down menu asking for a Python environment is blank and VSCode gives you no information about what to do.

I would like the extension to notify the user to install Python and the Python extension when trying to export a notebook if they are not installed.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
