### ISSUE TITLE
Standalone workflow from VSCode 

### ISSUE THREAD

**Issue by Dyl777** [microsoft/vscode-jupyter#15311]
I know there is already an option to run this in the browser. What am effectively asking is there a version that is just like Juypter notebook local that it does not have any connection to VSCode. The UI features are kinda nice and I was wondering if there was some work on this kind of thing specifically. I am just asking because of wanting to contribute to the UI features of this and I would like to but it's difficult to sieve through the Microsoft stuff and I want to have a place to merge it back to , obviously I wouldn't be able to merge it back here as it lacks the VSCode interoperability. Was wondering if something like that was being worked on

**Comment by amunger** [comment]
The notebook UI in VS Code is based off of the [Jupyter project](https://jupyter.org/). So if you're looking for the tool without the additions from Microsoft, that would be the place to go.

**Comment by Dyl777** [comment]
So why does the VSCode Juypter UI support KateX (or uses it by default) however the Juypter notebook doesn't use it. Even installing Juypter themes on Anaconda doesn't give the font formatting, cell box UI, text highlighting VScode offers.

**Comment by Dyl777** [comment]
Am not referring to the Microsoft stuff. I really like the way they customized the theme and style. Am referring to the VSCode am asking if the theme and styling is available standalone or there is something like that

**Comment by amunger** [comment]
No, sorry, the UI is very tightly coupled to vscode.

**Comment by Dyl777** [comment]
Why so??So this UI can't run on a browser.
