### ISSUE TITLE
Hanging when trying to choose/change Kernel

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#15314]
From [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details):

> Good idea, but execution is lacking. Hanging a lot when trying to choose/change Kernel, when re-opening VSCode, you have to create a new Jupyter server kernel for some reason, it won't connect to the same one running locally that it used literally a second ago. Paths and modules are not always resolved, you have to cycle through different kernels which is time consuming until you find the one that will start resolving paths, but will still not recognize all modules you have installed.

**Comment by DonJayamanne** [comment]
Its been a few months and no information has been provided to help resolve this issue.
Closing for now, if this problem persists, please feel free to create a new issue with the steps to repro and versions of the VS Code and Jupyter extension
