### ISSUE TITLE
Don't steal focus from HTML input elements

### ISSUE THREAD

**Issue by joelostblom** [microsoft/vscode-jupyter#15324]
In [an example like this one](https://altair-viz.github.io/gallery/multiple_interactions.html), selecting a value from the dropdown once, sets focus on the dropdown. Subsequent presses of up/down arrow keys toggles the selected values and immediately updates the chart (the same behavior occurs in JupyterLab). In VS Code, pressing the down/up arrows instead goes to the next cell, which makes it inconvenient to quickly toggle through multiple dropdown options

**Comment by ManonMarchand** [comment]
Might be related to this? 

In an anywidget like this one: 

```python
import anywidget
import traitlets


class TxtWidget(anywidget.AnyWidget):
    _esm = """
    function render({ model, el }) {
      let placeholder = model.get("value");
      let input = document.createElement('INPUT');
      input.setAttribute("placeholder", placeholder)
      input.setAttribute("type", "text");
      el.appendChild(input);

      input.addEventListener("keydown", (event) => {
        event.stopPropagation();
      })
    }
    export default { render };
    """
    value = traitlets.Unicode("edit me").tag(sync=True)

test = TxtWidget()
test
```

If I don't add the listener to call stopPropagation, pressing `suppr` while editing the text in the input, the entire cell is deleted.

This does not happen in a Jupyter editor.

**Comment by joelostblom** [comment]
I noticed that this seems to be a bigger issues than just widgets. Even actions like zooming in a chart with the scroll wheel is not working for me currently in VS Code notebooks, e.g. the spec here https://altair-viz.github.io/gallery/interactive_scatter_plot.html. The chart works as expected both in the web browser and in JupyterrLab, but in VS Code, the notebook is scrolled instead of the chart being zoomed.


https://github.com/microsoft/vscode-jupyter/assets/4560057/118f06ba-2902-4e91-8c82-4782e8495542




```
Version: 1.88.0-insider
Commit: 61187a0b6547df5911a0ee259f7afda46bac7ec3
Date: 2024-03-04T05:46:08.286Z
Electron: 28.2.2
ElectronBuildId: 26836304
Chromium: 120.0.6099.276
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.0-76060800daily20240311-generic
```

**Comment by amunger** [comment]
@joelostblom - I wasn't able to repro the zoom issue for that plot widget example, the mouse wheel zooms the widget as expected, even in the stable release. But I created a separate issue to track it.

**Comment by joelostblom** [comment]
Thanks for the quick fix here @amunger ! I just tried out the zoom example again (in the insiders preview) and I can't repro either so I will close that issue for now and report if it occurs again.

**Comment by amunger** [comment]
verification steps:

1. create a jupyter notebook and run the code with a python kernel

```
%%HTML
<input type="text">
<br />
<textArea rows="4" ></textArea>
<br />
<select>
    <option>1</option>
    <option>2</option>
    <option>3</option>
</select>
```

2. interact with the output elements (arrow keys, enter, delete) and ensure that the focus stays within the elements as you would expect
