### ISSUE TITLE
Add options for how script cells are differentiated. "Change color or draw a highlight behind the currently active cell"

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#1532]
## Environment data

- VS Code version: 2019.4.11881

I think  `python.dataScience.decorateCells` is a very useful feature but I wish there could be more options for it such as changing its color, alpha, and thickness.

Maybe also the option to add some delay? 
![vs_code](https://user-images.githubusercontent.com/33796896/56624448-e471a200-6606-11e9-8e83-101fd117e8e3.gif)

**Comment by joyceerhl** [comment]
We added support for theming the script cell decorations with the following color token customizations:
```
    "workbench.colorCustomizations": {
        "interactive.activeCodeBorder": "#ff0000",
        "interactive.inactiveCodeBorder": "#ff0000"
    },
```
