### ISSUE TITLE
Allow copy of charts from the output cell area

### ISSUE THREAD

**Issue by joelostblom** [microsoft/vscode-jupyter#15322]
In jupyterlab I can copy a chart by shift + right-clicking the chart image, which brings up the browser menu. In VS Code, it shift + right click does nothing. Some charting libraries seems to render a save button in VS Code, so I guess there is some logic to detect whether the output is an image. However, other libraries produce both and image and and interactive chart, and it seems like the VS logic fail for those. 

E.g. the matplotlib code from [this example ](https://matplotlib.org/stable/gallery/lines_bars_and_markers/bar_colors.html#sphx-glr-gallery-lines-bars-and-markers-bar-colors-py) seem to work fine as three small button show up to the right when I hover the image (copy, open in new tab, save to disk). However [this altair example](https://altair-viz.github.io/gallery/simple_bar_chart.html)  does not show any buttons when hovered over and there seems to be no way for me to copy the image other than taking a screenshot. In jupyterlab (and directly in the browser), I can shift + right click and copy the altair chart as well.

Maybe related to https://github.com/microsoft/vscode-jupyter/issues/13453 and https://github.com/microsoft/vscode/pull/190768

```
Version: 1.88.0-insider
Commit: 61187a0b6547df5911a0ee259f7afda46bac7ec3
Date: 2024-03-04T05:46:08.286Z
Electron: 28.2.2
ElectronBuildId: 26836304
Chromium: 120.0.6099.276
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.6.10-76060610-generic
```

**Comment by amunger** [comment]
Looks like there is a `canvas` element that we could copy in the altair example:

![image](https://github.com/microsoft/vscode-jupyter/assets/2019016/92b5c2ff-24f9-4e11-b19a-2c92ac83a55a)

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
