### ISSUE TITLE
Add a feature to print the output of a cell

### ISSUE THREAD

**Issue by geajack** [microsoft/vscode-jupyter#15333]
If I write a cell that outputs a string like 'my_string`, the output looks something like:

```
'Hello\nworld!'
```

then I go "ugh, woops" and re-type a new cell:

```
print(my_string)
```

to get the expected output:

```
Hello
world!
```

I would like it if how the string is displayed became a property of the UI and not of my code. In other words, I'd like to be able to click on the three dots next to a cell output, or maybe right-click on the output directly, and tick a box that says "print strings" or something - not sure what a good name for this would be.

Ideally I'd also like to be able to set an option to do this by default, and maybe even some kind of button or shortcut to do this very quickly, like a special button just for this next to the cell output, or like shift-clicking on the output or something.

**Comment by DonJayamanne** [comment]
Thanks for the suggestion, however I'm closing this as those is something the kernel needs to support.
Given that there are numerous kernels from different languages, trying to implement this feature is vscode (conferring output to print representation) is not going to be possible
