### ISSUE TITLE
Setting python.dataScience.runMagicCommands only accepts string and is unclear as to what it allows

### ISSUE THREAD

**Issue by RichardPflaum** [microsoft/vscode-jupyter#1533]
## Environment data

- VS Code version: 1.38.0
- Extension version (available under the Extensions sidebar): 2019.9.34911
- OS and version: Windows 10 Professional v1903
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda, Python=3.6.9
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Relevant/affected Python packages and their versions: 
   jupyter_client            5.3.1                      py_0
   jupyter_core              4.5.0                      py_0
   jupyterlab                1.0.2            py36hf63ae98_0
   jupyterlab_server         1.0.0                      py_1
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977):  Language server

## Expected behaviour

The setting python.dataScience.runMagicCommands accepts a list and passes each string contained in the list as a %magic command to the jupyter server. I'd like to use the setting "runMagicCommands" to make the Jupyter server always reload external modules automatically and also have the external qt Plot-window for matplotlib plots. Basically I'd expect the setting to work as if I'd type the commands manually into the interactive window:
```
%reload_ext autoreload
%autoreload 2
%matplotlib qt
```

## Actual behaviour

Error message when adding list,
```
 {
	"resource": "/c:/Users/<username>/AppData/Roaming/Code/User/settings.json",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 4,
	"message": "Incorrect type. Expected \"string\".",
	"startLineNumber": 53,
	"startColumn": 44,
	"endLineNumber": 56,
	"endColumn": 6
}
```

## Steps to reproduce:
Use following settings.json:
```
{
    "python.dataScience.runMagicCommands": [
        "reload_ext autoreload",
        "autoreload 2",
        "matplotlib qt"
    ]
}
```

## Further comments
I was also not able to find any documentation of the runMagicCommands setting.

**Comment by DonJayamanne** [comment]
Closing this as the setting has been removed in favor of runStartupCommands
