### ISSUE TITLE
Variables in variable viewer do not change when restarting the kernel

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#15344]
Found the root cause to be `onDidChangeVariables` not being implemented.
I think we should update this when new cells are run to ensure the variable view is refreshed.

* Restart kernels (based on status change)
    * Update variables
* Kernel dies/crashes (based on status change)
    * Update variables
* Execution completes
    * Update variables = Perhaps
    * I say perhaps, as this could have perf implications

**Comment by amunger** [comment]
Add setting `"notebook.experimental.variablesView": true`
Create a notebook and run some cells to get some variables
check the debug sidebar to see the variables
restart/crash the kernel and ensure the variables are cleared.

a kernel can be crashed with 

```
import IPython
app = IPython.Application.instance()
app.kernel.do_shutdown(True)
```
