### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by vfltv** [microsoft/vscode-jupyter#15342]
Type: <b>Bug</b>

Don't know the details, but via Extension Bisect, extension appears to spike CPU usage by ~15% at idle (ie without any operations being performed) and CPU temps spike from ~50-55c (typical idle temps) to 70-85c (medium load) with corresponding fan speed increase. 

Extension version: 2024.2.0
VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:36.258Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 6900HS with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|39.23GB (9.21GB free)|
|Process Argv|--crash-reporter-id 831297cc-0cc6-4f7f-8ae9-2bc431c4fd17|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470
666c4381:30973075

```

</details>

**Comment by vfltv** [comment]
Appears related to https://github.com/microsoft/pylance-release/issues/4022

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, does this issue go away when you disable the Pylance extension?

**Comment by vfltv** [comment]
No longer able to replicate after restart with both Jupyter v2024.2.0 and Pylance enabled.
