### ISSUE TITLE
slow kernel startup to run first cell

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#15353]
I was just counting seconds in my head, but it took around 15-20 seconds to run the cell after selecting it.

[slowFirstCell.log](https://github.com/microsoft/vscode-jupyter/files/14579066/slowFirstCell.log)

**Comment by DonJayamanne** [comment]
Cannot access the file

<img width="393" alt="Screenshot 2024-03-13 at 08 56 10" src="https://github.com/microsoft/vscode-jupyter/assets/1948812/06e3a0cc-bd9c-4dd4-862f-4ad05b0fca8f">

**Comment by DonJayamanne** [comment]
Found there was a 10s delay due to a timeout waiting for connection
```
14:43:21.383 [warn] Waited 10016ms for kernel to start Error: timeout
    at Timeout.p (~\.vscode-insiders\extensions\ms-toolsai.jupyter-2024.3.2024031201-win32-x64\dist\extension.node.js:55:1754)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
```

**Comment by DonJayamanne** [comment]
Will be fixed as part of https://github.com/microsoft/vscode-jupyter/issues/15493
