### ISSUE TITLE
VSCode slow and crashes - Python and Jupyter Notebooks

### ISSUE THREAD

**Issue by ale-dg** [microsoft/vscode-jupyter#15351]
Type: <b>Performance Issue</b>

Hi, 

When working with large Python Notebook files and restart the kernel, it takes way too long to do so and most often than not it crashes. When opening VSCode again, all the workspaces/folders are closed and have to open them again. 

Also regarding Python + Jupyter, doing some quick benchmarking between VSCode and JupyterLab (or Notebook), VSCode feels like a snail. It takes forever to run, i.e. generating the same graph in VSCode takes sometimes 66s and in Jupyter takes 30s, half the time hence making us work double the time (if you take that in perspective). 

When I began using VSCode for Jupyter it was a breeze because it was almost as fast as Jupyter, but it has been decreasing in performance over time, especially with the latest release. I know you work hard to keep it updated and for integrating new features, but with the latest release everything just went mental and it has become almost impossible to use it.

Thanks

Best

VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:22:39.156Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
black-formatter|ms-|2024.0.1
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.3
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

(1 theme extensions excluded)

</details>

**Comment by DonJayamanne** [comment]
@kburchfiel @paul-rogers 
If you too are running into this, please can you disable all extensions except, Jupyter and Python and verify you are still running into this. If yes, please create a new issue.

@ale-dg thanks for identifying the fact that it was the Pylance extension

**Comment by ale-dg** [comment]
HI @DonJayamanne,

No problem. Glad I could help. I am having a nice talk with the Pylance team here https://github.com/microsoft/pylance-release/issues/5614, though I had to downgrade a lot of versions of all the tools (VSCode, Jupyter, Pylance) to be able to work smoothly. So, if I may suggest something, I wouldn't discard a memory leak in the Jupyter extension as sometimes it also utilises a lot of threads when running.

Thanks for your help.

Best

**Comment by DonJayamanne** [comment]
>  discard a memory leak in the Jupyter extension as sometimes it also utilises a lot of threads

Jupyter extension doesn't start any threads.
Perhaps the perf issues are from Python process spawned for the kernel, the Python processes start threads/sub processes.

**Comment by kburchfiel** [comment]
Hi @DonJayamanne, thank you for your response! I continued to experience performance issues after disabling Pylance and all other extensions (except for Juptyer and Python), unfortunately. I've also noticed some other odd UI issues; the 'Go To' button is no longer working and the scroll bar sometimes disappears. (I've actually noticed this same 'Go To' disappearance within Jupyter Lab; however, my notebook tends to run much more quickly on Jupyter Lab, so I think there's still something within Code that's causing the sluggish behavior). 

I saw that there's an update to Code available, so I'll see if that resolves these issues; if not, I'll submit a new bug per your request.

I really do love working in Code and am looking forward to getting these issues resolved!

**Comment by ale-dg** [comment]
Hi @DonJayamanne,

Just for the record, I had forgotten this issue, which seems related to the Jupyter extension as well. Another lad also posted the logs there and is experiencing issues: https://github.com/microsoft/vscode-jupyter/issues/14459#issuecomment-1986677050 (and, according to him, he does not have Pylance installed).

Best

**Comment by ale-dg** [comment]
Let me repro with the upgraded version as I have downgraded a lot of versions for working further on my project...

**Comment by ale-dg** [comment]
@DonJayamanne I have finished without markdown... as I was fixing some issues, it stopped until an error, but went smoothly. Now I am running the one with markdown and the main difference has been that it took longer to start-up and the number of cells are increasing (and the computer went a bit hot).

As per your request, I'll share the log files in the other comment. 

Best

**Comment by DonJayamanne** [comment]
@ale-dg In summary, having markdown cells slows execution, is that right?

**Comment by ale-dg** [comment]
Yes, but consider I did not use Pylance. Would you like me to test with it? I just activated it and opened the log trace for python and just for indexing it finishes its memory.

2024-03-13 17:51:01.092 [info] [Info  - 17:51:01] (4192) Heap stats: total_heap_size=1220MB, used_heap_size=1156MB, total_physical_size=1218MB, total_available_size=2900MB, heap_size_limit=4096MB

2024-03-13 17:51:01.108 [info] [Warn  - 17:51:01] (4192) Workspace indexing has hit its upper limit: 2000 files

**Comment by DonJayamanne** [comment]
Great, lets create a new issue as you seem to be running into issues with Pylance,
I'd like to ensure we isolate the problems and resolve them one by one,
there could be number of issues that contribute to this poor user ex and I'd like to get them all resolved, hence the focus on creating separate issues (to resolve them individually)
