### ISSUE TITLE
Python code is not highlighted!

### ISSUE THREAD

**Issue by piwawa** [microsoft/vscode-jupyter#15350]
## Environment data

-   VS Code version: 1.87.1 (user setup)
-   Commit: 1e790d77f81672c49be070e04474901747115651
-   Date: 2024-03-06T00:21:36.258Z
-   Electron: 27.3.2
-   ElectronBuildId: 26836302
-   Chromium: 118.0.5993.159
-   Node.js: 18.17.1
-   V8: 11.8.172.18-electron.0
-   OS: Windows_NT x64 10.0.19045

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): v2024.2.0
-   Python Extension version (available under the Extensions sidebar): v2024.2.1 
-   OS (Windows | Mac | Linux distro) and version: Windows 
-   Python and/or Anaconda version: Python 3.10.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda 
-   Jupyter server running: Remote

## Expected behaviour

On my own PC, most of modules can be highlighted normally:

![image](https://github.com/microsoft/vscode-jupyter/assets/46926496/edb5aa9b-8eb8-46a2-90fa-ede6b84d3f1a)

## Actual behaviour

When I use ssh to connect my remote Manjaro server, ALL modules cannot be highlighted, just look like this:

![image](https://github.com/microsoft/vscode-jupyter/assets/46926496/2a2094ee-9010-4fac-b3e3-448736a7f628)

It looks TERRIBLE! No matter I reinstall plugins or change env, it still cannot be highlighted!

**Comment by DonJayamanne** [comment]
Please can you install the latest versions of the extension and let me know if you are still running into this issue?

**Comment by piwawa** [comment]
> Please can you install the latest versions of the extension and let me know if you are still running into this issue?

Sometimes it's normal and sometimes it can't be highlighted. In most cases, it will be highlighted automatically after a few minutes.
