### ISSUE TITLE
Enhanced IntelliSense for Notebooks Executed with %run

### ISSUE THREAD

**Issue by DavidHJong** [microsoft/vscode-jupyter#15354]
## Problem:

In VS Code's Jupyter Notebook environment, variables and functions defined within a notebook executed using the `%run` magic command are not recognized by VS Code's IntelliSense features. This leads to linting errors, a lack of hover-over information, and hampers code comprehension across notebooks.

## Proposed Feature:

Enhance the VS Code Jupyter extension to intelligently track variables and functions introduced by notebooks executed with `%run`. This could involve:

- **Static Analysis:** Parsing the called notebook for:
  - Import statements
  - Global variable definitions
  - Function definitions
- **Heuristic Analysis (optional):** If full static analysis isn't feasible, incorporate heuristics to infer potential definitions. Examples:
  - Identifying variables saved to files
  - Detecting return values from functions
- **Integration:** Collaborate with the Python extension/Pylance to provide this extracted namespace information, enabling accurate hover-over definitions and linting.

## Benefits:

- **Seamless Navigation:** Explore code across related notebooks without constant context switching.
- **Improved Understanding:** Reduce the need to manually inspect the called notebook to track variables and functions.
- **Enhanced Productivity:** Spend more time coding and less time hunting down definitions in complex notebook-based projects.

## Example:

**Main Notebook**

```python
%run "helper_notebook.ipynb"

# feature_query should be recognized here with type hints and hover information 
result = feature_query(data) 
```

**helper_notebook.ipynb**

```Python
def feature_query(input_data):
    # ... code logic
    return processed_data
```

**Acknowledgement**:  I understand the dynamic nature of Jupyter Notebooks might introduce limitations for perfectly accurate analysis. However, even partial and intelligent tracking would offer a significant improvement to the development experience.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, however I am closing this issue as out of scope.
This required a lot of work that needs support from multiple extensions for Kernels and Language servers, 
Given the fact that Language servers already have no knowledge of the context of the kernel, this presents yet another challenge.

**Comment by DavidHJong** [comment]
Thank you for the feedback on my previous feature request. After some feedback, I’ve got a new, simpler idea to navigate between notebooks in VS Code. What if we could just click on variables or functions to jump to their definitions in other notebooks?

**Here’s the idea:**

1. Clickable Links: When using %run, allow us to create clickable links for functions and variables that take us to their definitions in the executed notebook.
2. Direct Navigation: Clicking these links opens the notebook where the item is defined, right at the definition point.
3. Search as a Backup: If direct navigation isn’t possible, a quick search within the target notebook could help.

**Benefits:**

Simplifies moving between related notebooks.
Helps keep track of where things are defined.
Could significantly improve workflow with minimal complexity.

**Thoughts?** Could this be doable, and would it help you too?
