### ISSUE TITLE
data viewer freezes when viewing dataframe with enum content

### ISSUE THREAD

**Issue by adrinia** [microsoft/vscode-jupyter#15362]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Running this file with breakpoint at "pass". 
```
from enum import Enum
class Cars(Enum):
    Volvo = 1
    BMW = 2
    Suzuki = 3

data = {'namn': [Cars.Volvo]}
df = pd.DataFrame(data)

pass
```
Right-clicking on "df" in "run and debug"-tab and choosing "data viewer" yields an empty table with an error message.

### VS Code Version

1.87.2

### Jupyter Extension Version

v2024.2.0

### Jupyter logs

```shell
15:31:10.100 [warn] DataScience Error [SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at db.getDataFrameRows (~\.vscode\extensions\ms-toolsai.jupyter-2024.2.0-win32-x64\dist\extension.node.js:341:135411)
	at async Mu.getRows (~\.vscode\extensions\ms-toolsai.jupyter-2024.2.0-win32-x64\dist\extension.node.js:430:55497)
	at async ~\.vscode\extensions\ms-toolsai.jupyter-2024.2.0-win32-x64\dist\extension.node.js:430:43520
	at async Vf.wrapRequest (~\.vscode\extensions\ms-toolsai.jupyter-2024.2.0-win32-x64\dist\extension.node.js:430:43796)]
```

### Coding Language and Runtime Version

Python 3.12

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
closing as the jupyter data viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486
