### ISSUE TITLE
General discussion about support for other languages than just Python

### ISSUE THREAD

**Issue by clouds56** [microsoft/vscode-jupyter#1536]
Is it possible to make jupyter support other language like julia and R?
Or at least provide some interface for other extension to integrate.

**Comment by jlperla** [comment]
@rchiodo   I had a chance to try out the variable listing to replace the current `whos` (which looks like it was deprecated in Julia in 0.6).

It could be that the first part of the answer is:
```julia
"query": "String.(Base.names(Main))",
```

Note that following:
```julia
julia> a = 5
5

julia> b = "test"
"test"

julia> String.(Base.names(Main))
7-element Array{String,1}:
 "Base"
 "Core"
 "InteractiveUtils"
 "Main"
 "a"
 "ans"
 "b"
```

But I tried to put the following in my `settings.json` and it didn't seem to help?
```json
    "jupyter.variableQueries": [
        {
            "language": "julia",
            "query": "String.(Base.names(Main))",
            "parseExpr": "'(\\w+)'"
        }
    ]   
```
So something else is missing.  I also am not sure I understand how things would parse after it has the names.  It looks to me like https://github.com/microsoft/vscode-jupyter/blob/69a2fb578b5b1cd1ae836934885b24e87cbd2e39/src/client/datascience/jupyter/kernelVariables.ts#L423-L493 would need to be language specific as well, unless I am missing something?  But I don't know typescript, so hard for me to know what is going on.

**Comment by rchiodo** [comment]
Thanks @jlperla, I'll try the same thing with a julia kernel and debug bits of our stuff. Might be the parseExpr is not working.

The spot you linked to in the kernelVariables.ts is where we parse the results of a jupyter 'inspect' request (this request is what we use: https://jupyter-client.readthedocs.io/en/stable/messaging.html#introspection). We had hoped that other kernels would return data in the same format as ipython, but that's probaly not happening.

I'll debug it from our side and see what's happening.

**Comment by davidanthoff** [comment]
I think
```julia
"[" * join(map(i->"'$i'", String.(Base.names(Main))), ", ") * "]" |> println
```
would return the list in a format that is similar to the Python version, so using that as the query might just work?

**Comment by jlperla** [comment]
Thanks @rchiodo .  I suspect @davidanthoff  has the best approach for that string, and then the parsing shouldn't be different.

For the inspection, that makes sense.  I am not sure how to call it manually to see what it is returning, but I think this is the IJulia code: https://github.com/JuliaLang/IJulia.jl/blob/9b10fa9b879574bbf720f5285029e07758e50a5e/src/handlers.jl#L229-L248

**Comment by rchiodo** [comment]
I used this as the query:

```json
{
            "language": "julia",
            "query": "String.(Base.names(Main))",
            "parseExpr": " \"(\\w+)\""
        }
```

Which does give us the list of variables. 

However after that, the inspect request fails with this message from the julia kernel:

![image](https://user-images.githubusercontent.com/19672699/104352220-40efb180-54bb-11eb-9f83-490ff5c6eea2.png)

**Comment by jlperla** [comment]
Thanks @rchiodo   Try the suggestion from @davidanthoff . There aren't enough adjectives in the world to describe how much more knowledgeable and competent he is on these things than me.

**Comment by rchiodo** [comment]
It's not the query that is failing. I can get the list. It's the inspect request. 

For example, with this code here:

```julia
a = 5
```

The regex I was using returns me:

"Base",
"Core"
"Main",
"a"

All 3 of those give the same inspect result. 

Trying with @davidanthoff's query and regex gives the same result. 

Should an inspect request for "a" throw a bounds error? Do you have a way for me to try the same inspect request in a cell (IPython does this if you prefix code with a ?, like ```?x``` will inspect ```x```)

**Comment by jlperla** [comment]
I see.  I am not sure if it is relevant, but these guys told me the following:
```julia
julia> a = 5
5

julia> varinfo(Main, r"a")
  name                    size summary
  –––––––––––––––– ––––––––––– –––––––
  Base                         Module
  InteractiveUtils 198.160 KiB Module
  Main                         Module
  a                    8 bytes Int64
  ans                  8 bytes Int64

julia> varinfo(Main, r"^a$")
  name    size summary
  –––– ––––––– –––––––
  a    8 bytes Int64
``
So if `varinfo` is used behind the hood, maybe you need to put pass in the `^` and `$` around the string?

**Comment by rchiodo** [comment]
That gives the same bounds error on the inspect request. Inspecting "^a$" instead of "a" gives the same problem.

**Comment by davidanthoff** [comment]
Is the inspect request just sending some Julia code to eval in the kernel? What exactly is being sent? Or is there a special inspect Jupyter message?

**Comment by jlperla** [comment]
Wait, that may not be it.  See  that https://github.com/JuliaLang/IJulia.jl/blob/9b10fa9b879574bbf720f5285029e07758e50a5e/src/handlers.jl#L192  is called from the inspector implementaiton: https://github.com/JuliaLang/IJulia.jl/blob/9b10fa9b879574bbf720f5285029e07758e50a5e/src/handlers.jl#L236

Note that
```julia
julia> a = 5
5

julia> using IJulia

julia> IJulia.docdict("a")
Dict{String,Union{String, JSON.Writer.JSONText}} with 3 entries:
  "text/plain"    => "  No documentation found.\n\n  \e[36ma\e[39m is of type \e[36mInt64\e[39m.\n\n\e[1m  Summary\e[22…
  "text/markdown" => "No documentation found.\n\n`a` is of type `Int64`.\n\n# Summary\n\n```\nprimitive type Int64 <: S…
  "text/latex"    => "No documentation found.\n\n\\texttt{a} is of type \\texttt{Int64}.\n\n\\section{Summary}\n\\begin…
```

Is that the text that would be parsed by the https://github.com/microsoft/vscode-jupyter/blob/69a2fb578b5b1cd1ae836934885b24e87cbd2e39/src/client/datascience/jupyter/kernelVariables.ts#L438-L443

But I think we are now in the guts where @stevengj might be able to point some of this stuff out.

**Comment by rchiodo** [comment]
Yes this text here:

```
e[36ma\e[39m is of type \e[36mInt64\e[39m.\n\n\e[1m  Summary\e[
```

is the type of response we're expecting.

**Comment by rchiodo** [comment]
> Is the inspect request just sending some Julia code to eval in the kernel? What exactly is being sent? Or is there a special inspect Jupyter message?

The inspect request is a special jupyter kernel message. 

The docs for it are here:
https://jupyter-client.readthedocs.io/en/stable/messaging.html#introspection

We send the inspect_request with the 'code' value set to the name of the variable.

**Comment by davidanthoff** [comment]
What are you sending as the `cursor_pos` in the inspect message? The stack trace from your screenshot to me looks like a string indexing error inside `get_token` at https://github.com/JuliaLang/IJulia.jl/blob/9b10fa9b879574bbf720f5285029e07758e50a5e/src/handlers.jl#L195 from your screenshot.

Is there any chance you could let me know the line number of the stack trace item that I marked with a red error from your screenshot?

![image](https://user-images.githubusercontent.com/1036561/104376187-80c59180-54d9-11eb-9391-5780435a7817.png)

Namely the line number of the stack trace in `get_token`.

**Comment by rchiodo** [comment]
We set cursor_pos to zero.

Trace for the get_token is at line 217:

" [4] get_token(::String, ::Int64) at C:\Users\Rich\.julia\packages\IJulia\IDNmS\src\handlers.jl:217"

**Comment by rchiodo** [comment]
Closing this as other languages are supported in the new UI (with other extensions supporting their own kernels and language servers)
