### ISSUE TITLE
kernel does not show immediately after metadata changed

### ISSUE THREAD

**Issue by zesluo** [microsoft/vscode-jupyter#1538]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur
After I inserted the kernelspec to the config file of ipynb, I have to close vscode and restart it again. Then I can see the kernel I want.
I think that it may because the notebook cache the data. And only by closing and reopening vscode can it be able to read the updated kernelspec and go effect.
By the way, I also did some workaround such as 1.close t5.ipynb window and reopen it again 2.restart kernel.3.restart my computer. Unfortunately, none of them can work for me>_<. Would you mind help us again on it? Thanks a lot!
![image](https://user-images.githubusercontent.com/46309533/74495543-1136d300-4f13-11ea-8bfc-c41859b083d7.png)
![image](https://user-images.githubusercontent.com/46309533/74495557-198f0e00-4f13-11ea-949e-43098c986cca.png)

### Your Jupyter and/or Python environment
Version: 1.42.0 (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

## Developer Tools Console Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by greazer** [comment]
We need to review how we're working for the pyspark scenario, so moving to July

**Comment by DavidKutu** [comment]
@zesluo, this might be fixed in the new native notebooks, could you please confirm?

**Comment by DavidKutu** [comment]
@zesluo feel free to reopen this or create a new issue if its not fixed.
