### ISSUE TITLE
Test: Exploratory test for Data Veiwer

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#15419]
- [x] anyOS: @rebornix 
- [x] anyOS: @amunger 
- [x] anyOS: @DonJayamanne 

Complexity: 3

Authors: @rebornix 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2315419%0A%0A&assignees=rebornix)

---

**Setup**
* Install pre-release of Jupyter Extension
* Install pre-release of Data Wrangler Extension

We are deprecating the builtin Data Viewer, let's do some exploratory testing and see if there is anything obvious that we miss.

**Comment by amunger** [comment]
Still no support while debugging, attempting to open the dataviewer will just get stuck loading the editor.

**Comment by amunger** [comment]
The slice control:

The jupyter data viewer's slice control lets you view a 2-dimensional slice of a n-dimensional array 
run the cell:

```
import tensorflow as tf

rank_3_tensor = tf.constant(
    [
        [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]],
        [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]],
        [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]],
    ]
)
```

For example, the second element of each position's inner array with
![image](https://github.com/microsoft/vscode-jupyter/assets/2019016/cb8bfa6d-829f-4e15-9df2-5eb999e55548)

example taken from [here](https://www.tensorflow.org/guide/tensor), which has a good visual.

### notes

- This is my first time using this tool, but I think that's the main capability
- I don't see anything similar in DW, but I definitely could have missed it
- This control is used for the types: `ndarray`, `Tensor`, `EagerTensor`, `DataArray`
- No idea what kind of usage it has

**Comment by amunger** [comment]
found the usage for the slice tool: 2038 distinct VSCodeMachineIds

**Comment by amunger** [comment]
of the types supported in the jupyter data viewer:

```
'DataFrame',    'list',    'dict',    'ndarray',    'Series',    'Tensor',    'EagerTensor',    'DataArray'
```

it looks like the only missing type is a torch tensor:

```
import torch
mytensor = torch.tensor([1, 2, 3])
```

**Comment by rebornix** [comment]
I'm not seeing "Open in Data Viewer" action in the builtin Variable View, but it works fine in the old one. 

<img width="360" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/876920/a4f9ee79-988d-4d8f-9023-30e8425ad093">

**Comment by rebornix** [comment]
A couple of issues found with the vsix with debugging support:

* The builtin variable view has no action contribution for open the data frame in data viewer
* We didn't hook up the data viewer contribution point for the debug variables view
* Lastly, when opening the data viewer from the legacy variable view, the DW data viewer is always in the loading state.
