### ISSUE TITLE
Drop custom keyword from metadata in diff view

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#15413]
Refs: https://github.com/microsoft/vscode/issues/205637

- [x] anyOS: @rebornix 
- [x] anyOS: @amunger 
- [x] anyOS: @Yoyokrazy 

Complexity: 2

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2315413%0A%0A&assignees=DonJayamanne)

---

**Setup**
* Install pre-release of Jupyter Extension
* Open a worksapce folder
* Add the following setting into user settings `"jupyter.experimental.dropCustomMetadata": true,`
* Reload VS Code

**Steps**
* Create a notebook file
* Add a cell and save it
* Go into time time view and verify the property `custom` is no longer visible under the `metadata` section of the cell
* Add a few more cells
* Add an attachment to a MD cell and verify the properti `attachment` is displayed along with`metadata ` under the metadata section of the notebook cell in diff view

Test again with the above setting set to `false` or removed
* This time verify the word `custom` exists in the diff view for cells.

**Comment by amunger** [comment]
Flipping the setting means opening any previously saved notebook is updated. 
I imagine that will be quite disruptive for people with version controlled notebooks if we're planning on rolling this out in an automated fashion.

**Comment by DonJayamanne** [comment]
> imagine that will be quite disruptive for people with version controlled notebooks if we're planning on rolling this out in an

`custom` will not show up in SCM, 
hence this issue does not apply.
