### ISSUE TITLE
Export Interactive Window

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#15412]
Refs: #15380

- [x] anyOS: @rebornix 
- [x] anyOS: @amunger 

Complexity: 2

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2315412%0A%0A&assignees=DonJayamanne)

---

**Setup**
* Install pre-release of Jupyter Extension

**Steps**
* Create an IW window
* Verify you can export the IW to an notebook

**Comment by rebornix** [comment]
I wonder if this can be a verification item other than a TPI

**Comment by DonJayamanne** [comment]
> I wonder if this can be a verification item other than a TPI

Cannot, as not everyone will have Python installed, and will require some domain knowledge to install Python and create IW (by running Python code).

In all honestly this is a complexity of 1, but didn't want to leave that as 1.
