### ISSUE TITLE
Output truncated with no way to view all output in the notebook itself

### ISSUE THREAD

**Issue by zhanwenchen** [microsoft/vscode-jupyter#15420]
## Environment data

-   VS Code version: 1.87.2
-   Jupyter Extension version (available under the Extensions sidebar): v2024.2.0
-   Python Extension version (available under the Extensions sidebar): v2024.2.1
-   OS (Windows | Mac | Linux distro) and version: Mac Sonoma 14.3.1 (23D60)
-   Python and/or Anaconda version: Python 3.12.1 and conda 24.1.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behavior

Scrolling past settings (200 lines)

## Actual behaviour

<img width="1093" alt="Screenshot 2024-03-24 at 1 06 15 PM" src="https://github.com/microsoft/vscode-jupyter/assets/5029736/ebb8b8fd-14ae-4ed1-8495-752147e5edc2">
<img width="1865" alt="Screenshot 2024-03-24 at 1 06 21 PM" src="https://github.com/microsoft/vscode-jupyter/assets/5029736/30a373f6-88ee-4d3f-b430-5ebb652a8dad">

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX


```

</p>
</details>

**Comment by DonJayamanne** [comment]
Please can you try the latest vscode insiders
This has been fixed in insiders.
If you can still repro the issue please let us know and we'll reopen this issue
