### ISSUE TITLE
pressing ctrl+A in an input or textarea within the output will select all output

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#15428]
Testing #15414

1. Run a cell with the code

```
from IPython.display import HTML
HTML('<input type="text" name="name" value="value\nvalue\nvalue"></br><textarea name="name">value\nvalue\nvalue</textarea><div>hello</div>')
```

2. click in one of the inputs and press ctrl+a
:bug: all output is selected

slight regression, didn't behave all that well before either (all cells were selected as a side effect)

The context key `notebookOutputInputFocused` could be used to avoid this on the new command, but then it would just delegate back to selecting all cells again.

**Comment by amunger** [comment]
similar to https://github.com/microsoft/vscode-jupyter/issues/15324

We could possibly swallow all text editor commands when `notebookOutputInputFocused` is true with a higher priority command. Probably don't want to do that in endgame week tho

**Comment by DonJayamanne** [comment]
Already using that when clause today, `when: ContextKeyExpr.and(NOTEBOOK_EDITOR_FOCUSED, ContextKeyExpr.not(InputFocusedContextKey), NOTEBOOK_OUTPUT_FOCUSED),`

Must be some other bug,

**Comment by DonJayamanne** [comment]
Oops, was using the wrong context.

**Comment by DonJayamanne** [comment]
Fixed, should be ready on tomorrow's insiders

**Comment by ZupoLlask** [comment]
Hi guys!

I have the setup you'll find below and now I'm unable to select all the code in the code cell I'm focusing pressing ctrl+A.
Do you think it is related with this issue/PR?

Thanks.


Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

Name: Jupyter
Id: ms-toolsai.jupyter
Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.
Version: 2024.3.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
