### ISSUE TITLE
Autoreload other python files if they've been imported 

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1542]
User scenario:

User has two files, foo.py and bar.py.

They are working in foo.py and they run this cell
```
from bar import my_func
my_func()
```
Then they go to bar.py and modify my_func().

They run a cell like so:
``` python
#%%
my_func()
```
It would be nice if my_func automatically picked up the changes from bar without having to redo the import. 

The autoreload magic does this already.
https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html

**Comment by DonJayamanne** [comment]
I'm closing this issue as this has been around for 4 years and little progress made here with no external PRs
also there are other wayts to acomplish this via autoreload magics in jupyter.
as this isn't the default behaviour in Jupyter i'm reluctant to implement this in the extension.
hence closing this issue.
