### ISSUE TITLE
add a toggle to disable max output size limit to command palette

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#1543]
Sometimes I need to run some stats models that generate large results so that I have to scroll to see the whole outputs. Currently, I need to manually set `max output size` to `-1` and then change it back later. It would be easier if there is a command to allow me toggle between my customized max output size limit and infinity.

**Comment by greazer** [comment]
Closing as dupe of https://github.com/microsoft/vscode-jupyter/issues/7096.
