### ISSUE TITLE
Cannot use variable viewer to view details of a dictionary or a list

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#15433]
Testing #15419

Open workspace
Add python file with the following code
```python
x = 1234
# %%
mydictionary = {'a': 1, 'b': 2}
```
* Run above cells
* Open variable `mydictionary` in variable viewer and nothing happens

This works in stable VS Code

**Comment by DonJayamanne** [comment]
Similarly does not work for lists either

**Comment by amunger** [comment]
which variable viewer are you opening?
nothing happens, as in the viewer is blank? 
is this because of https://github.com/microsoft/vscode-jupyter/issues/15432?

![image](https://github.com/microsoft/vscode-jupyter/assets/2019016/bde5ba79-95b9-4f0f-b775-902325ec177e)

**Comment by DonJayamanne** [comment]
Weird, can no longer repro this.
