### ISSUE TITLE
Print in python notebooks

### ISSUE THREAD

**Issue by Davood-M** [microsoft/vscode-jupyter#1545]
Issue Type: <b>Bug</b>

For printing on the same line, in jupyter lab we can simply use the following:
print('...................', end='\r', flush=True)

in vscode, this kind of printing does not work (I put it in a loop to see the progress of training for example). I would appreciate it if you could address this.

Thank you

Extension version: 2020.1.58038
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (8.10GB free)|
|Process Argv|C:\Users\statlab\Desktop\Gender Privacy\SAN|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by greazer** [comment]
I believe this works now in notebooks and the interactive window.
