### ISSUE TITLE
Colour notebook cell background by tag

### ISSUE THREAD

**Issue by psychemedia** [microsoft/vscode-jupyter#15489]
In classic Jupyter notebooks and JupyterLab, we use an extension to colour cell backgrounds for specific user tags (customisable tags and colours from a preference setting).

<img width="765" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/82988/8f6a38cc-3537-4a56-9aab-d2ece99454dc">

In VS Code:

- is there any way of colouring notebook cell backgrounds independently?
- is there any way of influencing cell rendering based on cell metadata?

How practical would it be to create a "colour cell background by cell metadata tag" in VS Code?

**Comment by psychemedia** [comment]
Hmm.. looking at [`vscode-markdown-mermaid`](https://github.com/mjbvz/vscode-markdown-mermaid/), is there a workaround of interruptung the renderer somehow? So if the renderer is passed a cell, can we look at the cell tags metadata, and then wrap all the content in a div classed by the tag(s)? And have a css style file somewhere that can style against that class/classes?

**Comment by DonJayamanne** [comment]
Thank you for the feature request, given this hasn't receieved any upvotes since this was createdk I'm closing this issue.

**Comment by psychemedia** [comment]
@DonJayamanne do you know of any way of propagating a cell tag to a css class attribute?

**Comment by DonJayamanne** [comment]
Unfortunately there isn’t one that I’m aware of
