### ISSUE TITLE
Can I use a container (not-docker) for my python kernel?

### ISSUE THREAD

**Issue by kaare-mikkelsen** [microsoft/vscode-jupyter#15487]
I am working remotely on a server where I am not allowed to make a python installation, but instead have to rely on a python installation inside a singularity container.
That means I can access a python kernel by typing:

singularity exec containerFile.sif -B mountOptions python 

Is there any way to make this a valid kernel, for use with, for instance, an interactive session in VS code?

**Comment by DonJayamanne** [comment]
If you are able to get this working in classic Jupyter Notebook/Jupyter Lab (even if it were on another machine), then I do no see why this isn't possible (i.e. as long as it is regisrered as a kernel in kernels folder).
Else its not a feature that is currently supported, and I do not see us supporting this in the future either, as we try to stick to the Jupyter protocol.

**Alternative**
* can install Jupyter inside the container
* Then run Jupyter inside the container, not sure what the CLI is, 
* Once Jupyter application is running inside that container, you can connect to that via Jupyter extension as though it was a remote Jupyter application (using the url)

Hopefully that helps.
Closing as not planned.
