### ISSUE TITLE
Fix semantic versioning

### ISSUE THREAD

**Issue by sfo** [microsoft/vscode-jupyter#15488]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The current versioning scheme leads to the effect that pre-releases are considered more recent than the stable release, even if the latter is the most recent version (see my other issue here: https://github.com/microsoft/vscode/issues/209522).
This is due to the (ab)use of the patch-level identifier to denote pre-release versions.

Rather, pre-release versions should be denoted by [appending to the upcoming release version separated by a `-`](https://github.com/semver/semver/blob/master/semver.md). So instead of `v2024.3.2024032701`, the current pre-release version should be `v2024.3.0-2024032701` to allow proper handling of different release branches.

### VS Code Version

Version: 1.88.0-insider Commit: d994aede3529f4d1af9eeaeb234d32fd936243e7 Date: 2024-03-29T22:23:13.365Z Electron: 28.2.8 ElectronBuildId: 27744544 Chromium: 120.0.6099.291 Node.js: 18.18.2 V8: 12.0.267.19-electron.0 OS: Linux x64 6.7.10-100.fc38.x86_64 snap

### Jupyter Extension Version

v2024.3.0

### Running Jupyter locally or remotely?

None

**Comment by sfo** [comment]
Thanks for clarification. However, I cannot follow this argumentation:
> [...] VS Code is able to detect and properly handle the versions. I.e. VS Code know which version is pre-relese and which one is stable.
> [...]
> This is not true, VS Code will not treat pre-relese as a more recent version than stable. [...]

In the other issue, @sandy081 [confirmed](https://github.com/microsoft/vscode/issues/209522#issuecomment-2036569612) that VS Code considers version numbers only to determine the most recent version.

The following screenshot confirms this behavior, as it shows a list perfectly sorted by version number. It also shows that both (pre-release, and release) versions are provided in the pre-release branch of the extension, so no manual switch to release branch should be required:
![vscode_versions](https://github.com/microsoft/vscode-jupyter/assets/571497/3ca1884d-6a9c-4763-9d8b-2782f959b0a4)

Additionally, the following screenshot shows that VS Code suggests to install the older pre-release version instead of the more recent, stable version, which implies that VS Code is not using other indicators than pure version number to determine the most recent one:
![image](https://github.com/microsoft/vscode-jupyter/assets/571497/ca44f3bd-a6c5-4713-9d8a-ea5187e96714)

So I have to conclude that contrary to your argumentation, either VS Code is not able to distinguish pre-release and stable version by other means than version number, or this plugin somehow prevents VS Code from doing so (maybe a metadata issue then?).

**Comment by sbatten** [comment]
@sfo If a user opts to "Install Pre-release", they will be offered all builds of the extension including "Stable" releases. At the time of release of a stable build, this is essentially the same build that has already been available in the pre-release channel, and therefore, there is no benefit to switching to it.
