### ISSUE TITLE
Stop cell execution crashes the kernel.

### ISSUE THREAD

**Issue by alex180500** [microsoft/vscode-jupyter#15498]
After the latest update (vscode 1.88.0) clicking the square button to stop a cell execution (for example while doing a long for loop) now crashes the whole kernel.

## Steps to reproduce:

```py
import time
for _ in range(1_000_000):
    time.sleep(1)
```

After running just use the "stop cell execution" button.

## Logs

```
13:19:17.910 [info] Handle Execution of Cells 1 for ~\My Drive\Dottorato\PhD Code\Various\issues\issue_vscode.ipynb
13:19:19.237 [info] Interrupt kernel execution
13:19:19.237 [info] Interrupt requested ~\My Drive\Dottorato\PhD Code\Various\issues\issue_vscode.ipynb
13:19:19.237 [info] Interrupt kernel execution
13:19:19.237 [info] Interrupting kernel: python3122jvsc74a57bd05a18e1050da49b3ab4bc844da5b120df8344e2e5fe34e720fa658460e31bb145
13:19:19.237 [info] Interrupting kernel via SIGINT
13:19:19.251 [error] Disposing session as kernel process died ExitCode: 1, Reason: 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

13:19:19.256 [info] Interrupt requested & sent for ~\My Drive\Dottorato\PhD Code\Various\issues\issue_vscode.ipynb in notebookEditor.
13:19:19.287 [info] Cell 1 completed in -1712315957.917s (start: 1712315957917, end: undefined)
```

**Comment by alex180500** [comment]
Strangely this problem seems to come randomly, reopening vscode has fixed it temporarily.

**Comment by DonJayamanne** [comment]
Thank you for filling this issue and sorry you are running into this

I don't think this is an issue with the latest version of vscode, as we haven't made any changes in this space.
Then again I could be wrong

Please let me know if you keep running into this.
Please try regular jupyter lab as well and see if this repros.

Also please do fill in the issues template
We request information to be able to help users.
Please have a look at the issue templates and provide that information.

**Comment by alex180500** [comment]
I'm getting an hard time trying to reproduce the bug sadly. I will update whenever I'm able to. Maybe it's better to close this for now.
