### ISSUE TITLE
Command to "Run cells in section" for current cell's section in notebook.

### ISSUE THREAD

**Issue by asford** [microsoft/vscode-jupyter#15501]
_Searched for "Run cells in section"_

The new ["Run cells in section" feature](https://code.visualstudio.com/updates/v1_88#_run-cells-in-section) is fantastic for organizing notebooks,
particularly where you may have a section of "heavy IO" before a block of EDA or interactive analysis.

We often have notebooks with two sections:
1. A "data load" block that loads data from a backend warehouse, potentially running some expensive post-processing.
2. A "analysis" block, where we reshape the data, define some helper functions and run some lighter post-processing or tidy the dataset.

The "run in section" feature is great inside an analysis block, because we can easily rerun the lightweight helper definitions and generate EDA plots *without* triggering the heavier IO section of the notebook. Wow! Much rapid feedback. Much workflow ease. Nice.

However, unlike the (also great) "Run Precedent Cells" feature, there doesn't appear to be a way to trigger this from the command palette (and therefor keyboard shortcut) for the selected cell or section.

It would be good to add a editor command "Execute Section Cells"...

...selectable by the standard command palette
...targetable by keyboard shortcuts
...(ideally) in the extended run dropdown

...that detects the section of the currently selected cell or cells
...then runs the entire section (or sections) in the needful way (as if I clicked this on the section header in outline)

Examples of where in the UI I would expect this to show up...
![image](https://github.com/microsoft/vscode-jupyter/assets/282792/6d41a7c3-f3ca-412b-839e-438d21ce4031)
![image](https://github.com/microsoft/vscode-jupyter/assets/282792/b26a7479-5872-4e8a-8ec0-a81629e7ecf6)

I noted, in the keyboard shortcuts section, `notebook.section.runCells`, however this doesn't appear to have an effect when bound to a key.

**Comment by asford** [comment]
I've cross-filed into https://github.com/microsoft/vscode/issues/209653 where this might be appropriate?

**Comment by amunger** [comment]
closing in favor of the issue in vscode
