### ISSUE TITLE
Disposing session as kernel process died ExitCode: 3228369022, Reason:

### ISSUE THREAD

**Issue by seakafuka** [microsoft/vscode-jupyter#15510]
The issue about kernel crashes took me a whole afternoon to resolve. It occurred when running cells containing plot-related functions.
It wasn't until I downloaded the mkl package that the problem was fixed. I hope this solution can assist others facing the same issue. Additionally, I sincerely request an explanation of the principle behind this solution.

**Comment by DonJayamanne** [comment]
> wasn't until I downloaded the mkl package that the problem was fixed. 

Closing this as  this is due to third party packages.
As is reported
Ie the kernel crashed due to the lack of or incorrectly/not installed extensions
