### ISSUE TITLE
Make Code Executed with `Run Selection/Line in Interactive Window` Accessible with Up Arrow

### ISSUE THREAD

**Issue by colinbrust** [microsoft/vscode-jupyter#15534]
When using the interactive shell, you can either directly enter code into the interactive terminal, or select code in a script and run it in the interactive shell with the `Run Selection/Line in Interactive Window`  option. However, if you press the up arrow in the interactive terminal, it only registers code that was typed and executed from the interactive terminal. It would be very helpful if pressing the up arrow pulled up code that was executed using the `Run Selection/Line in Interactive Window` option.

**Comment by amunger** [comment]
closing for lack of supporting votes.

similar request: https://github.com/microsoft/vscode/issues/129081
note you can also use `%run file.py` from the input box, which will be added to the history
