### ISSUE TITLE
Server-side execution

### ISSUE THREAD

**Issue by 3f6a** [microsoft/vscode-jupyter#15543]
As https://github.com/jupyterlab/jupyter-collaboration/pull/279 has been merged, could something similar apply to vscode Jupyter notebooks?

The use case here is that one should be able to disconnect from a remote, connect again, and not miss any output.

**Comment by b10902118** [comment]
Any progress so far? I would like to implement this functionality. I am first time to this project, just digged into APIs. Hope to learn  TODOs and insights from you guys.

**Comment by DonJayamanne** [comment]
Its been a few months and there haven't been enough upvotes to warrant this feature. hence closing this.
> The use case here is that one should be able to disconnect from a remote, connect again, and not miss any output.
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/3998

**Comment by DonJayamanne** [comment]
You have two parts in this issues, one is a solution referenced an upstream PR and then also mentioned the problem

The problem is a duplicate
The upstream pr is not something we can implement as the architectures are completely different, vscode don’t use Jupyter servers
