### ISSUE TITLE
"paste code into file" without creating a new cell

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#1554]
Please consider adding a toggle for "paste code into file" without creating a new cell and sometimes users may just wanna insert the code somewhere in the existing code.

**Comment by greazer** [comment]
The latest behavior here is to just support a copy-to-clipboard button in the interactive window. This still includes the initial # %%. However, you can also just click into the IW cell and press Ctrl+A to select all, then Ctrl+C to copy just the text.
