### ISSUE TITLE
Text Color Remains Black and Unreadable Across All Dark Themes in Jupyter (WSL2-Ubuntu)

### ISSUE THREAD

**Issue by akikuno** [microsoft/vscode-jupyter#15542]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

In my Jupyter environment (WSL2-Ubuntu), even when I switch to the Dark theme, the text color remains black, making it barely unreadable. This happens with all Dark themes. I have not done anything to override the settings in vscode specifically for text color.

I apologize if this issue has already been discussed, but I would appreciate any guidance on how to address this problem.

# Dark theme
![image](https://github.com/microsoft/vscode-jupyter/assets/15861316/2dcbe4f1-432a-43d4-a775-1c378260263b)

# Light theme

![image](https://github.com/microsoft/vscode-jupyter/assets/15861316/089ce501-89ce-4fd9-9d7e-ff865a9dff0b)

### VS Code Version

1.88.1 e170252f762678dec6ca2cc69aba1570769a5d39 x64

### Jupyter Extension Version

v2024.3.1

### Language Extension Version (if applicable)

Python Extension

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Are you referring to the text color just in the extensions page or any thing else?
You should see the exact same issue with other extensions as well, not just Jupyter.

If not, please share screenshots.

**Comment by akikuno** [comment]
Oh, sorry for the confusion. It turns out the text color is black in extensions other than Jupyter as well, so it seems the issue isn't specific to Jupyter. Since I rarely use VScode for anything other than Jupyter, I hadn't noticed this before. Thank you so much for your guidance!
