### ISSUE TITLE
connecting a remote Jupyter server os.getcwd() can’t work properly 

### ISSUE THREAD

**Issue by aiyolo** [microsoft/vscode-jupyter#1555]
When vocode connecting a remote jupyter server, os.getcwd() will not print current directory 

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by minwhoo** [comment]
As per @IanMatthewHuff 's suggestion, I've found using the configuration below in `settings.json` working and helpful for now. I still would like a more explicit option to set the working directory in the settings though.

```
{
    ...,
    "jupyter.runStartupCommands": [
        "%cd ${workspaceFolder}"
    ]
}
```

**Comment by IanMatthewHuff** [comment]
Closing as the startup commands work as a workaround for this.
