### ISSUE TITLE
Pylance reportUndefinedVariable when using Jupyter startup script

### ISSUE THREAD

**Issue by slnc** [microsoft/vscode-jupyter#15560]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Pylance incorrectly warns about undefined variables when they're defined indirectly via `%run` statements or through `/home/$USER/.ipython/profile_default/startup/preamble.py` files.

The only sane workaround I've found is to disable the `reportUndefinedVariable` which, sadly, also disables the valuable true positive cases.

**How to reproduce:**

1. Create an .ipython startup script:
```sh
mkdir -p /home/$USER/.ipython/profile_default/startup/
echo "import pandas as pd" >> /home/$USER/.ipython/profile_default/startup/preamble.py
```
2. Restart VSCode/Jupyter kernel.
3. In a blank notebook, create a cell with:

```python
pd.DataFrame([])
```

**Expected:**
Pylance doesn't give any errors because the cell works.

**Actual:**
<img width="565" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/69429/2e0e1101-aefc-4bb3-897c-1cdccd416728">

If Pylance can't dynamically check for this (a reason I've read in past issues reporting this same bug), would it be possible to make Pylance ignore certain user-defined undefined variables ("pd", "np", etc) and only for certain (`.ipynb`) file patterns through a user defined dict? 

```json
    "python.analysis.diagnosticSeverityOverrides": {
        "reportUndefinedVariableForFilePatterns": {
           "**/*.ipynb": ["pd", "np"]
        }
    },
```

It's a bit of a hack, but that would solve all the instances I've found of this problem ([1](https://stackoverflow.com/questions/72270548/how-to-ignore-pylance-type-checking-on-notebooks/78342862#78342862) [2](https://github.com/microsoft/pylance-release/issues/2135) [3](https://github.com/microsoft/vscode-jupyter/issues/6987)).

### VS Code Version

1.88.1

### Jupyter Extension Version

v2024.4.1.

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thank you for filing this feature request, however given this issue has not received sufficient upvotes, I'm closing this issue
