### ISSUE TITLE
Allow user to pick from local jupyter session

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1556]
When connecting to an existing jupyter session, user needs to enter the URL of the jupyter server.
We could instead pre-populate a list with the active jupyter servers.

We already have code to get the list of servers (it includes the token information as well).

**Comment by ivirshup** [comment]
I'd really like this. It's kind of a pain to find the token for a server if that's needed, but vscode should have the rights to figure out tokens on it's own (from `jupyter notebook list --json`).

**Comment by DonJayamanne** [comment]
// @ts-ignore blah
import {Event} from 'vscode'


type Id = string;
type EnvironmentType = 'conda' | 'global';

type Environment = {
    id: Id;
    name: string;
    type: EnvironmentType;

    executablePath?: string;
    version?: string;
    sysPrefix?: string;
}

interface Environmentsx {
    onDidChangeEnvironment: Event<{id: Id, change: 'added' | 'removed' | 'updated'}>;
    onDidChangeProgress: Event<{state: 'started' | 'completed'}>;
    getEvironments() : Id[];
    getEnvironmentDetailsSync(id): Environment;
    getEnvronmentDetails(id): Promise<Environment>;
    getRefresPromise() : Promise<void> | undefined;
    refresh(): Promise<void>;
}


// What do we need from the UI
// * Ability to refresh
// * Get notified when items are added, updated, removed
// * Get information about an envs
// * Get current list of envs
// * Get all envs

interface Environments {
    // Object ref for an Id will always be the same in the lifetime of VS Code session.
    onDidChangeEnvironment: Event<{
        env: Environment;
        change: 'added' | 'updated' | 'removed';
    }>;
    environments : Environment[];
    resolveEnvironment(env: Environment): Promise<SomeFormOf<Environment>>;
    resolveEnvironment(id: Id): Promise<SomeFormOf<Environment>>;







    onDidChangeProgress: Event<{state: 'started' | 'completed'}>;
    getRefresPromise() : Promise<void> | undefined;
    refresh(): Promise<void>;
}



// Api user
const environmentsListNow = environments.environments;

// After 10 minutes
environmentsListNow[0] !== environments.environments[0];

// Type
return userMapping.get('id') as SomeFormOf<Environment>


const internalMapping = new Map<Id, Environment>();
const userMapping = new Map<Id, UserClass>();

class UserClass implements Environment {
    get name() {
        return this.internal.name;
    }
    get sysPrefix(): string | undefined {
        return this.internal.sysPrefix;
    }

    constructor(readonly internal: Environment) {

    }
}

**Comment by DonJayamanne** [comment]
Closing as users can already add jupyter servers manually
