### ISSUE TITLE
Intellisense Docs dont follow code when you scroll in Notebook Editor

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-jupyter#1557]
If you bring up the intellisense docs and scroll in the notebook editor, the doc popup stays static in the page rather than following the notebook

![image](https://user-images.githubusercontent.com/15910920/68996363-bc20ed80-084d-11ea-87e3-3165d67acbde.png)

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
