### ISSUE TITLE
scrolling over a zoomable widget scrolls the notebook, instead of zooming

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#15575]
I noticed that this seems to be a bigger issues than just widgets. Even actions like zooming in a chart with the scroll wheel is not working for me currently in VS Code notebooks, e.g. the spec here https://altair-viz.github.io/gallery/interactive_scatter_plot.html. The chart works as expected both in the web browser and in JupyterrLab, but in VS Code, the notebook is scrolled instead of the chart being zoomed.

https://github.com/microsoft/vscode-jupyter/assets/4560057/118f06ba-2902-4e91-8c82-4782e8495542

```
Version: 1.88.0-insider
Commit: 61187a0b6547df5911a0ee259f7afda46bac7ec3
Date: 2024-03-04T05:46:08.286Z
Electron: 28.2.2
ElectronBuildId: 26836304
Chromium: 120.0.6099.276
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.0-76060800daily20240311-generic
```

_Originally posted by @joelostblom in https://github.com/microsoft/vscode-jupyter/issues/15324#issuecomment-2032462254_

**Comment by joelostblom** [comment]
I just tried out the zoom example again (in the insiders preview) and I can't repro either so feel free to close this issue for now and I'll report if it occurs again.
