### ISSUE TITLE
Problem opening the same notebook multiple times/tab

### ISSUE THREAD

**Issue by mmiakashs** [microsoft/vscode-jupyter#1558]
# Bug: Notebook Editor Opening Problem

## Steps to cause the bug to occur
1. Open a notebook
2. Open the same notebook in another tab

## Actual behavior
Both the same notebooks expected to open in a notebook view. 

## Expected behavior
The first notebook open in the notebook view, however when open the same notebook in the second/third times/tab, it opened in the JSON view. 

### Your Jupyter and/or Python environment
*Please provide as much info as you readily know*
- **Jupyter server running:**                       Local
- **VS Code version:**                                1.41
- **Anaconda version:**     4.7.12
- **OS:**                                                     Linux (ubuntu):
- **Virtual environment:**                          conda

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed with new native support for editing notebooks starting with v1.59 of VS Code. If this issue continues to occur in the latest build of VS Code, please reopen or enter a new issue.
