### ISSUE TITLE
Jupyter Panel Stuck on loading variables....

### ISSUE THREAD

**Issue by guocity** [microsoft/vscode-jupyter#15594]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.89.0-insider
- OS Version: Darwin arm64 23.5.0

Steps to Reproduce:

This week, VSCode have bug not showing variable in Jupyter Panel after few cell run. It will stuck on loading variables....

**Comment by rebornix** [comment]
@amunger do we make changes to variable fetching recently?

**Comment by amunger** [comment]
no changes were made to the Jupyter variable view
@guocity can you set `"jupyter.logging.level": "verbose"`, repro the issue and then post the content of the jupyter logs here. The command `Jupyter: Show Output' should get you there

You can also try using the built-in variables view, which works for python kernels with `"notebook.experimental.variablesView": true`. It should show up in the debug side-bar.

**Comment by guocity** [comment]
sure, i have moved to stable build, and if i encounter the issue, i will paste the log here
