### ISSUE TITLE
Let me opt out of your surveys permanently 

### ISSUE THREAD

**Issue by petar-andrejic** [microsoft/vscode-jupyter#15592]
I don't want to do your surveys. I don't want popups distracting me on a regular basis asking me to do your surveys. As far as I can tell the extension has no settings for permanently disabling these popups.

**Comment by DonJayamanne** [comment]
Thank you for filing this feature request, however this hasn't receieved sufficient upvotes and hasn't receieved any PRs either, hence closing this for now.
