### ISSUE TITLE
Syncronization problem of editing notebook

### ISSUE THREAD

**Issue by moghadas76** [microsoft/vscode-jupyter#15591]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I run two processes of Vsocde. I opened a notebook at the same time. When I edited one of them, the other one did not get updated.

Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:34:12.840Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-28-generic snap

### VS Code Version

1.88.1

### Jupyter Extension Version

v2024.3.1

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment]
Thank you for filing this issue.
This should work, provided you have auto save enabled, 

else changes from one instance of VS Code are not synced with the other (as they are separate processes).
In this case its by design.
