### ISSUE TITLE
[Feature Request] jupyter-style autocomplete in the editor (provide column names for dataframes for instance)

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#1561]
1. When typing in the main editor, there are no completions for column names but there are completions when using the input windows in interactive windows:

![vs](https://user-images.githubusercontent.com/33796896/58809549-29b3c700-85ea-11e9-840d-a40d88d740fe.gif)

2. The method completions (e.g., `.dropna()`) in the interactive windows only show up for `DataFrame` not `Series`. Meanwhile, the editor does not seem to have completions for those common methods at all.

![vs1](https://user-images.githubusercontent.com/33796896/58810056-210fc080-85eb-11e9-89d3-8351af929a02.gif)
```
Version: 1.34.0 (user setup)
Python Extension: 2019.5.17517
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

**Comment by Sutyke** [comment]
Is there any update on dataframe column name auto complete bug?

**Comment by rchiodo** [comment]
Interactive auto complete works for me. It might be you have to wait for a bit.

![image](https://user-images.githubusercontent.com/19672699/105068230-8bca7580-5a35-11eb-984b-ec28c43efed9.png)

In that picture, there's a 'Miles_per_gallon' column on the dataframe.

**Comment by eved1018** [comment]
Im still a little confused if this can be implemented into the editor as well ( unrelated to jupyer) as a standard python thing.

**Comment by rchiodo** [comment]
@eved1018 this requires jupyter to work in the editor. It needs a runtime reference to the dataframe because the column names aren't available without the data being loaded. 

So no this would not be available in normal python editing unless you were using the interactive window and the file you're looking at was participating in the interactive session (well once we fix this bug).

**Comment by eved1018** [comment]
Amazing thank you!

**Comment by rchiodo** [comment]
Closing for lack of up votes. We will eventually support pylance understanding kernels. At that point I think this would just work (well if we told pylance about the kernel used for the interactive window).
