### ISSUE TITLE
Kernel detection spinner is confusing and mostly unnecessary after one is found.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#15614]
After VS Code starts or loads a new workspace and loads a notebook, a search is kicked off for kernels. This can take several seconds or even more than a minute or two.

When this occurs, a little spinner appears next to "Detecting Kernels". Once an appropriate kernel is found, it's displayed for notebook, but the graphical spinner keeps spinning. This now confusingly indicates that the found kernel is busy executing. This is not true.

This isn't an awful thing, but it sure seems like a user very likely does not care that more kernels are being detected once the one they're looking for shows up. So the suggestion here is to make the spinner disappear. If the user clicks on the kernel picker while detection is happening, then some other notification can be shown.

Here's a gif.

![WhatsExecutingExactly](https://github.com/microsoft/vscode-jupyter/assets/11685408/d82337e3-dff3-4185-9688-e8b4452188cf)

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given this hasn't received any upvotes I'm closing this issue.
