### ISSUE TITLE
Jupyter extension doesn't need to notify user of extension running code in their kernel nearly as often as it does.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#15613]
![WhyNotificationNotBusy](https://github.com/microsoft/vscode-jupyter/assets/11685408/8089849d-3e4c-40e7-a3bf-946e4501278f)

When my extension calls `executeCodeInKernel`, the jupyter extension always notifies me. While I understand the thought behind this, it seems like overkill and can make for a bad experience if an extension consistently executes code in the kernel.

Seems like a one-time notification the first time this occurs after a kernel has been started would be sufficient. This is enough to tell the user that an extension is indeed running code in their kernel. 

In addition, just making use of a kernel busy state indicator for additional extension executions, would be called for as well. The user could hover over this indicator and be given the reason that their kernel is busy. 

The stop button on the notebook is appropriate for user-invoked cell executions, but isn't appropriate for a "system-invoked" execution.

**Comment by DonJayamanne** [comment]
This is required to ensure users are aware of the fact that the kernel is busy running some other code even though the user might not be aware of this.
Else users could end up complaining about the fact that Notebook/Kernel execution is very slow, only to find out that some other extension is busy running some code in the kernel.

Today we give a grace period of 500ms, if after 500ms the 3rd party code has not yet completed, we display a progress message.
I'll change the timeout from 500ms to 1s.

**Comment by DonJayamanne** [comment]
> In addition, just making use of a kernel busy state indicator for additional extension executions, would be called for as well.

Unfortunately this isn't supported yet in VS Code API, and no plans for this just yet.

**Comment by DonJayamanne** [comment]
> The stop button on the notebook is appropriate for user-invoked cell executions, but isn't appropriate for a "system-invoked" execution.

Not following what you mean by `system-invoked execution`
Are you suggesting that the execution from a co-pilot extension is deemed as `system-invoked`, i would have thought this is an extension instead of `system` as its not part of VS Code.

**Comment by DonJayamanne** [comment]
> Seems like a one-time notification the first time this occurs after a kernel has been started would be sufficient. This is

Agreed, will display once per session.

> In addition, just making use of a kernel busy state indicator for additional extension executions, would be called for as well.

Yes
