### ISSUE TITLE
For a folder/workspace, create a configuration for Jupyter: Default Kernel

### ISSUE THREAD

**Issue by joepalm4** [microsoft/vscode-jupyter#15637]
When .ipynb files are created or opened, you need to select the kernel each time. Once the kernel has been selected for a file, it remains the kernel used for that file, regardless if it's closed and reopened. I'm wondering if this is possible to set a default kernel for all .ipynb files that are opened in the future. A default kernel for all jupyter notebook files for a given folder/workspace.

**Comment by DonJayamanne** [comment]
Please use this extension https://marketplace.visualstudio.com/items?itemName=donjayamanne.vscode-default-python-kernel
