### ISSUE TITLE
Detach interactive window from file and rename

### ISSUE THREAD

**Issue by robfrworld** [microsoft/vscode-jupyter#15631]
VSCode Jupyter extension enables a productive mode of working with a python script and an attached interactive window. This way, one can run (parts of) the script in the interactive window and then work "hands on" with the results. This is especially handy for R&D work.

However, sometimes one would like to go back and forth inspecting multiple results, e.g. for different parameter sets. This works reasonably well for computations with a short run time. However, for computations with a long runtime it is inconvenient or prohibitive that a new run will erase the results of the previous run in the interactive window.

For this use case it would thus be great to be able to:

- detach the interactive window from the python file, such that the "run in interative window" commands are no longer sent to this window
- be able to rename the interactive window, e.g. to "Configuration A1"
- automatically create a new interactive window when the user selects a "run in interactive window" command

To implement this, two new right-click menu entries could be added to the interactive window tab: "Detach interactive window from file" and "Rename interactive window"

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
