### ISSUE TITLE
No effect after setting the "jupyter.notebookFileRoot": "${fileDirname}". Always default to the ${workspaceFolder}.

### ISSUE THREAD

**Issue by ndgayan** [microsoft/vscode-jupyter#15649]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The file root is always the workspace folder in 2024.4.0. No effect after setting to "jupyter.notebookFileRoot": "${fileDirname}". However, the 2024.3.1 version is working fine.

### VS Code Version

Version: 1.89.0

### Jupyter Extension Version

2024.4.0

### Coding Language and Runtime Version

Python 3.10

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and sorry you are running into this.

> The file root is always the workspace folder in 2024.4.0. No effect after setting to "jupyter.notebookFileRoot": "${fileDirname}". However, the 2024.3.1 version is working fine.


Given this works in the latest version of the Jupyter extension, I would suggest updating to the latest version.
We do not back port fixes to older versions.

**Comment by ndgayan** [comment]
Sorry. I think you misunderstood. The issue is in the current version of the extension. The issue. is no effect after setting the "jupyter.notebookFileRoot": "${fileDirname}". it is always default to the [${workspaceFolder}. I can't set it to the ${fileDirname}.

However order version of the extension working fine.

**Comment by DonJayamanne** [comment]
> Sorry. I think you misunderstood my question.

Oh sorry,  I have indeed, thanks

**Comment by DonJayamanne** [comment]
Please can you share the folder structure?
* Have you got a workspace folder opened?
* What is your workspace folder path & what is your path to the Python file?

I've tried this with the latest version of Jupyter extension and VS Code and this works as expected.

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by ndgayan** [comment]
Sorry about the late reply,

Using remote SSH:

Below is the process to activate Python environment.

Workspace folder settings.json set to
  _"python.pipenvPath": "/opt/python/venvs/my_env",
  "python.defaultInterpreterPath": "/opt/python/venvs/my_env/bin/python3",
  **"jupyter.notebookFileRoot": "${fileDirname}"**_

Assume the notebook is in two Test folders deep from the workspace folder root.

**From the old version of the extension. [v2024.3.1]**

```python
import os
os.getcwd()
# /<Path to Workspace Folder>/Test/Test
```

**From the old version of the extension. [v2024.4.0]**

```python
import os
os.getcwd()
# /<Path to Workspace Folder>
```

You can clearly see the "jupyter.notebookFileRoot": "${fileDirname}" not reading or using the newer version of the extension. Could you use Git to compare the code changes related to this issue?

I'll work on getting Jupyter logs from both versions of the extensions and get permission to post here.

**Comment by DonJayamanne** [comment]
Thank you for the logs, sorry I missed this.
Will try to repro this, unfortunately I couldn't repro this locally.
Will try with SSH.

**Comment by bankotibi** [comment]
I'm also facing the same issue with the remote-ssh extension.
The host machine is windows 10 and the server is linux (rhel7).

**Comment by Null404bad** [comment]
> Thank you for the logs, sorry I missed this. Will try to repro this, unfortunately I couldn't repro this locally. Will try with SSH.

I'm facing the similar issue. Downgrading jupyter notebook extension doesn't work for me. I'm wondering if it's caused by OS since Visual Studio Code Server no longer support old linux distribution recently. And I upload my jupyter log here:

https://gist.github.com/Null404bad/a7c675c46149fa60e0c15fda5a83944f

Hope you can tell me how to fix this. I'm really suffering from this issue because I have to use the absolute filepath every time. Thanks a lot.

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).
