### ISSUE TITLE
Cannot connect to a remote Jupyter server from vscode.dev

### ISSUE THREAD

**Issue by nsklei** [microsoft/vscode-jupyter#15668]
## Environment data

-   VS Code version: 1.89.0 on vscode.dev
-   Jupyter Extension version (available under the Extensions sidebar): v2024.4.0
-   Python Extension version (available under the Extensions sidebar): v2024.6.0
-   OS (Windows | Mac | Linux distro) and version: Win 11 v10.0.22621 Build 22621
-   Jupyter server running: Remote

## Expected behaviour

I run a jupyter notebook instance on my azure vm.
When opening the url http://xx.xx.xxx.xxx:yyyy/tree?token=abc12345 in my browser jupyter works.
When opening the same url in VS Code Desktop App, I can connect to the kernel and run a script on it.

## Actual behaviour

When trying to connect the kernel using the same url in vscode.dev I get the following error:

![image](https://github.com/microsoft/vscode-jupyter/assets/94993442/e0e8be1d-0375-4c36-9023-b924370c0d18)

I followed the steps described [here](https://github.com/microsoft/vscode-jupyter/wiki/Connecting-to-a-remote-Jupyter-server-from-vscode.dev), but it didn't solve the problem.

**Comment by DonJayamanne** [comment]
@nsklei Are you still running into this issue?

**Comment by nsklei** [comment]
Yes, I still have the problem. I start the jupyter server using

`jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.allow_origin='*`'

**Comment by nsklei** [comment]
Okay I fixed the issue. Problem was that my browser somehow blocked the http connection in the background.
I created a certificate using letsencrypt and started the jupyter server again using the following command:

`jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --certfile=/home/azureuser/fullchain.pem --keyfile=/home/azureuser/privkey.pem --NotebookApp.allow_origin='*'`
