### ISSUE TITLE
Install modules from the missing module error

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#1566]
I was running a new notebook and didn't have seaborn in my current env. I get the Missing module warning when I execute the cell. From that warning (or from a popup) I'd like for vscode to install that module for me. 

Possible: We already look at imports when we open, match up against current env list and offer to install missing modules?

**Comment by AndrewTrapani** [comment]
Did this never get any traction?

Or is this a duplicate issue?

Today in VSCode 1.51.1, with Python 2020.11.37..., and PyLance 2020.12.0, it auto imported something from my current project, but it did not import a system module "os", even though PyLance it warns about "os" not being defined.

This feature saves a lot of time and headaches.

**Comment by FelixKahane** [comment]
Is there any news on this issue?

**Comment by rchiodo** [comment]
I think we could do something simple to start with here. On a ModuleNotFound error add a link to create a cell to resolve the problem. 

That would insert a cell with code like so:

```
%pip install modulename
```
or 
```
%conda install modulename
```

The user would then have to explicitly run the cell themselves, but it at least shows them what they have to do (and uses the %pip instead of !pip)

**Comment by kapilkd13** [comment]
Any updates on it.

**Comment by rchiodo** [comment]
You can look at our iteration plan to see if we plan to do something in the next month or so. It's always pinned to the top of our issues
https://github.com/microsoft/vscode-jupyter/issues

Or look at the milestone on the issue itself.

This issue is not a high priority at the moment though.

**Comment by yonbav** [comment]
Im also suffering from this issue, probably will switch to pycharm because of that :(

**Comment by dev-ro** [comment]
any updates on this highly convenient feature request for efficient coding?

**Comment by WerVa** [comment]
![image](https://user-images.githubusercontent.com/3823792/203528286-5242b67d-7199-4d60-bec6-546e3f95883b.png)
Hi this function will be great! Please add it

**Comment by mpr1255** [comment]
How does this not exist yet??

**Comment by rjalexa** [comment]
Cannot understand why this is considered low priority. Manually adding imports that are flagged as missing by pylint is a real waste of time. Pycharm users ridicule us for having to do it manually. I do love VSCode and recommend it all the time but this is so disappointing. Cmon guys! :)

**Comment by TheLime1** [comment]
is this true ? 
![image](https://user-images.githubusercontent.com/47940043/234326965-e71b1828-0a4e-4f56-a601-4dc750b838bd.png)

**Comment by f2008700** [comment]
Eagerly waiting for this basic feature. Please don't make us go back to Pycharm.

**Comment by TheLime1** [comment]
i found this [extension](https://marketplace.visualstudio.com/items?itemName=PeterSteiner.pip-installer&ssr=false#qna) as a copium
_the issue is from 2019 man_

**Comment by johnkennyuk** [comment]
> i found this [extension](https://marketplace.visualstudio.com/items?itemName=PeterSteiner.pip-installer&ssr=false#qna) as a copium _the issue is from 2019 man_

FYI after installing the extension myself I found that It hasnt been updated for a long time as I had to recreate extension.js code modifications as per https://marketplace.visualstudio.com/items?itemName=PeterSteiner.pip-installer&ssr=false#qna  John Cutburth posts (in my case the first post was sufficient) in order to add a wait to the activate function install missing to use this import installer with VENV's

**Comment by johnkennyuk** [comment]
> i found this [extension](https://marketplace.visualstudio.com/items?itemName=PeterSteiner.pip-installer&ssr=false#qna) as a copium _the issue is from 2019 man_

FYI after installing the extension myself I found that It hasnt been updated for a long time as I had to recreate extension.js code modifications as per https://marketplace.visualstudio.com/items?itemName=PeterSteiner.pip-installer&ssr=false#qna  John Cutburth posts (in my case the first post was sufficient) inorder to add a wait to the activate function install missing to use this import installer with VENV's

**Comment by DonJayamanne** [comment]
We try to keep VS Code lean and we think the functionality you're asking for is great for a VS Code extension. Maybe you can already find one that suits you in the [VS Code Marketplace](https://aka.ms/vscodemarketplace). Just in case, in a few simple steps you can get started [writing your own extension](https://aka.ms/vscodewritingextensions). See also our [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Happy Coding!
