### ISSUE TITLE
Jupyter not compatible with VS code version 1.87.2 

### ISSUE THREAD

**Issue by monafurukawa** [microsoft/vscode-jupyter#15676]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I cannot find the version of jupyter and python extension compatible with VS code version 1.87.2 
Does anyone know how to find which versions are compatible? Also the only the latest versions are available on the market place. I would like to download as .vsix 

### VS Code Version

1.87.2

### Jupyter Extension Version

N/A

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment]
Unfortunately you need to install the extension via the marketplace instead of downloading it.
