### ISSUE TITLE
Extension gets very slow after a few hours of use

### ISSUE THREAD

**Issue by trouve-antoine** [microsoft/vscode-jupyter#15670]
Type: <b>Bug</b>

Since about two weeks the Jupyter extension often shows as unresponsive in the list of Running Extension. After launch, it starts to get slower after a few hours, to a point where running a cell with only 1+1 may take minutes.
The same notebooks work perfectly fine when I run Jupyter standalone and use in my browser.

Extension version: 2024.4.0
VS Code version: Code 1.89.0 (Universal) (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:10:10.196Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (1.61GB free)|
|Process Argv|hafh-analytics --crash-reporter-id a522f206-f325-475e-92e4-aaa55a98363f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by JasonGross** [comment]
Not sure if I'm having the same problem or a different one, but for me the log seems to indicate that it's the kernel (the node process running the vscode server on the remote machine) that is taking all the time:
```
02:46:47.500 [info] Generated code for 35 = <ipython-input-35-2073cdd569a5> with 273 lines
02:46:48.250 [debug] Cell Index:3 sent to kernel
02:46:49.050 [debug] Start cell 3 execution @ 1716000409049 (clear output)
02:46:49.050 [debug] Kernel acknowledged execution of cell 3 @ 1716000409049
```
(here there is only about a second of lag, I'll post again when it gets back up to many seconds)

**Comment by JasonGross** [comment]
This one is somewhat longer:
```
02:52:44.007 [info] Handle Execution of Cells 0 for /Interactive-1.interactive
02:52:44.008 [debug] Cell Index:0 sent to kernel
02:52:46.567 [debug] Interpreter for Pylance for Notebook URI "/Interactive-1.interactive" is ~/guarantees-based-mechanistic-interpretability/.venv/bin/python
02:52:47.776 [debug] Start cell 0 execution @ 1716000767776 (clear output)
02:52:47.776 [debug] Kernel acknowledged execution of cell 0 @ 1716000767776
```

**Comment by DonJayamanne** [comment]
@JasonGross 
Are you implying that the kernel gets slow after some time?
If this is the case, I'm not sure there's anything we can do about that.
However if you believe VS Code is contributing to this, please can you disable all extensions, including Pylance, 
leave the following enabled and test
* Jupyter, Python and Notebook Renderers
Try disabling the following setting to see if that makes a difference.



![Image](https://github.com/microsoft/vscode-jupyter/assets/1948812/11f844e2-71b6-47ba-a575-447728cd04ef)

**Comment by SterlingYM** [comment]
Can this be related to https://github.com/microsoft/vscode/issues/211154 (which branched off from https://github.com/microsoft/vscode-jupyter/issues/14459)?

**Comment by DonJayamanne** [comment]
Its been over a month since the information was requested, hence closing this issue

If however anyone is still running into similar issues, please feel free to create a new issue instead fo commenting here, that way we start fresh.
