### ISSUE TITLE
Jupyter stopped working

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#15685]
From marketplace review https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details

> ... Every other release breaks, and it's a mystery hunt how to find a combination of VSCode and Jupyter extension actually works. Please, for the love of all that is good, stop putting out releases that break the extension. Is there any internal review process? How do these broken versions keep getting pushed out?

**Comment by DonJayamanne** [comment]
Unfortunately this issue has been open for a while and no new information has been provided, hence closing this issue.
