### ISSUE TITLE
Adding a command and shortcut for jupyter.changeCellToRaw

### ISSUE THREAD

**Issue by maximecharriere** [microsoft/vscode-jupyter#15683]
In Jupyter Notebook, when selecting a cell, you can press `esc + r` to transforme the cell from Python to Raw. This is particularly useful for disabling a cell, so that it doesn't execute when you choose "Execute all" or "Execute above cells".
See this question for more info: https://stackoverflow.com/questions/34192290/ipython-notebook-elegant-way-of-turning-off-part-of-cells  

In VSCode, `jupyter.changeCellToCode` (`esc+c`) and `jupyter.changeCellToMarkdown` (`esc+m`) are already present, but not `jupyter.changeCellToRaw` (`esc+r`).  

**Would it be possible to add this command and corresponding shortcut?  
If I propose a PR, will it be accepted?**

**Comment by amunger** [comment]
Doesn't changing to markdown accomplish this same thing?

**Comment by maximecharriere** [comment]
Technically, yes, but it's not the most convenient.  
In the following screenshot you have 3 times the same cell, but as a Python, Raw, and Markdown format.  

- The first cell is executed if I `maj+enter`, `Execute all` or `Execute above cells`, which I don't want.
- The second still has a "code" style, but the cell is deactivated and will not execute the Python code. 
- In the third one, the code will also not run, but it has a markdown style, resulting in a messy notebook. The comments in code will be interpreted has H1 header, everything will be on one line, and we will not see the difference between a real Markdown cell and a deactivated code cell.

![image](https://github.com/microsoft/vscode-jupyter/assets/51918753/961c70b3-a827-445d-b4e9-87d41261b4ea)

**Comment by amunger** [comment]
I think [this cell commenting feature](https://github.com/microsoft/vscode/issues/142437) should cover this scenario - you can now comment the full cell content with the standard `toggle comment` command.
