### ISSUE TITLE
Deno: Hints only pop up in the same cell. Variables are shown as unrecognized otherwise.

### ISSUE THREAD

**Issue by planetoryd** [microsoft/vscode-jupyter#15682]
## Environment data

-   VS Code version: 1.88.1 0d01a72525276e5e3771fe5851b9c83de0de1e2b
-   Jupyter Extension version (available under the Extensions sidebar): v2024.4.2024040801
- deno 1.43.2 (with a trivial patch to make it not error)

Linux

![image](https://github.com/microsoft/vscode-jupyter/assets/68096727/2ecfbcba-9c54-48c5-a065-98de95b364e6)

![image](https://github.com/microsoft/vscode-jupyter/assets/68096727/7d736373-f342-4f29-90f5-06d382614c2e)

![image](https://github.com/microsoft/vscode-jupyter/assets/68096727/312457ef-9ab4-4c21-a126-a887462cb747)

The first cell has been run. Hints only work in the same cell.

**Comment by planetoryd** [comment]
![image](https://github.com/microsoft/vscode-jupyter/assets/68096727/b9556fc6-90fe-463f-a138-b945f534a8df)

![image](https://github.com/microsoft/vscode-jupyter/assets/68096727/1a6849b5-2cfb-438f-b7a2-98132059324c)

**Comment by planetoryd** [comment]
I cleared the output.

And I tried to type in the second cell  

![image](https://github.com/microsoft/vscode-jupyter/assets/68096727/8e30f141-bee6-4989-af09-add9ffd4e363)

so this is what it logs when the problem happens

**Comment by dsherret** [comment]
This is a vscode_deno bug. See: https://github.com/denoland/vscode_deno/issues/932

**Comment by DonJayamanne** [comment]
Closing in favour of upstream issue https://github.com/denoland/vscode_deno/issues/932
