### ISSUE TITLE
Consider adding settings to turn off cell toolbars - "Change to Markdown" button distracting 

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode-jupyter#1569]
## Description
I find the button to "Change to Markdown" distracting , especially under dark theme. The "M" is quite different from other icons and makes me think of actually code. I would like to disable this (or toolbar altogether) and only use keyboard shortcut for this. 

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by wdscxsj** [comment]
> I totally agree with @xgdgsc, In dark mode, I often confuse the cell toolbar with the cell itself. I think they take too much space. The ability to turn off the cell toolbar would be great.

The cell toolbar is intrusive indeed. Takes too much vertical space. Please please add an option to disable it.

**Comment by bilderbuchi** [comment]
Afaict this is already fixed - the Python/Markdown label on a cell's lower right (what I think the OP means) can be removed with the Notebook layout setting "Show Cell Status Bar" -> hidden. There is also a "Compact View" setting, but I don't know what exactly that changes.

**Comment by rchiodo** [comment]
The new notebook layout has completely changed this. There's no longer a toolbar button to switch to markdown. Instead you switch the language in the lower right.
