### ISSUE TITLE
debug dataframe Data Viewer 

### ISSUE THREAD

**Issue by PavukEdya** [microsoft/vscode-jupyter#15705]
all values in my pandas dataframe are objects, i made this because i need save some information for each cell
for cell i use 

```
@dataclasses.dataclass
class DataFrameCellWithCoord:
    value: Any
    row: int
    column: int
    column_letter: str

    def __str__(self):
        return str(self.value)

    def __repr__(self):
        return self.__str__()
```
when i use in debug 'View Value in Data Viewer' i see
![изображение_2024-05-23_112731459](https://github.com/microsoft/vscode-jupyter/assets/115864498/f0eb9928-1a3f-42bb-b404-e76dce6a49e6)
How can I make the DF display use a text representation of objects?

**Comment by amunger** [comment]
closing as the jupyter data viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486
