### ISSUE TITLE
Suggestions to for jupyter notebook

### ISSUE THREAD

**Issue by pypiuser** [microsoft/vscode-jupyter#1570]
# Suggestion: Notebook Editor, Interactive Window, Editor cells

## Suggestions for improvements ->
-> Can we have similar (colab) hover toolbar. In providing such an option, we can use this Jupyter notebook for presentations with little or no interface elements.
-> Please provide a theme to hide toolbar and new line.
This lets us fit more content. Very useful in the presentations. 
-> Scroll the '>' green play icon as the textbox scrolls. We have to move up every time to exec a cell. Colab has a floating button.
-> Please document cell shortcuts. Colab has tooltips on toolbar icons. This helps beginners  learn shortcuts. 
-> Slow to start. Opening a new Jupyter Notebook is slow.
-> Support dragging cells
-> Support find & replace
-> Support a context driven menu for cells 
-> Support export to HTML and PDF documents
-> Rich text markup editing.

### Your Jupyter and/or Python environment
*Please provide as much info as you readily know*
- **Jupyter server running:**                      Local
- **Extension version:**                              Latest
- **VS Code version:**                                Now
- **Setting python.jediEnabled:**              ?
- **Python and/or Anaconda version:**    3.8
- **OS:**                                                      Linux
- **Virtual environment:**                          Anaconda

## Developer Tools Console Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by IanMatthewHuff** [comment]
Closing as the notebook UI is now owned by the code vscode notebook interface.
