### ISSUE TITLE
Shortcut to display function/method docstring

### ISSUE THREAD

**Issue by arthurmloureiro** [microsoft/vscode-jupyter#15709]
Normal jupyter notebooks will display the function docstring with `alt/option + tab`. Can this please be implemented in this extension?

The "mouse hovering" idea is awful and only works 1 out of 20 times. I cannot even see numpy docstrings...

**Comment by DonJayamanne** [comment]
Thank you for the feature request, closing this as there haven't been sufficient upvotes on this feature request.
