### ISSUE TITLE
textbase tqdm bar does not display correctly

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode-jupyter#15701]
Here's the codes:

```
from time import sleep
from tqdm import tqdm

for i in tqdm(range(100)):
    for j in tqdm(range(10), leave=False):
        sleep(0.1)
```

When running in the terminal, it shows correctly. It returns two progress bars, one for the` i `and one for the` j` in the loop.

However, when running in the jupyter notebook or Interactive Window, only the outermost `i` loop is displayed, and the progress bar of the` j` loop contained therein is not displayed.

**Comment by ydmykr** [comment]
Related on StackOverflow: https://stackoverflow.com/questions/78507717/nested-tqdm-loading-bars-not-working-in-vscode-interactive-window

**Comment by DonJayamanne** [comment]
Looks like something broke in tqdm, as this doesn't work properly in Jupyter lab either (though different issues).


![Image](https://github.com/user-attachments/assets/b3e19b7a-393a-4962-ae5a-5fdd40f15651)

**Comment by DonJayamanne** [comment]
@ydmykr 
As a work around, try using `from tqdm.notebook import tqdm` instead of `from tqdm import tqdm`

**Comment by DonJayamanne** [comment]
# WORK AROUND

import `tqdm.notebook` instead of `tqdm`
I.e. 
```python
from time import sleep
from tqdm.notebook import tqdm

for i in tqdm(range(100)):
    for j in tqdm(range(10), leave=False):
        sleep(0.1)
````

**Comment by Jorritboer** [comment]
Thank you for looking into this (minor) issue. 
The workaround doesn't seem to work for me either however.

https://github.com/user-attachments/assets/e2a8d49b-924d-4fc6-91ee-2748683e4b9c

**Comment by b-a0** [comment]
The workaround works for me in VS Code on Windows:

![tqdm](https://github.com/user-attachments/assets/737ef7be-1653-430a-9092-8497f6292c95)

Version info:

vs code:
```
Version: 1.92.0 (system setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.20348
```

conda environment:
```
- python=3.9.19
- ipython=7.33.0
- tqdm=4.66.5
```

**Comment by cceyda** [comment]
tqdm has been really unreliable on vscode notebooks lately, it stops working suddenly, like it will render on previous cell and will stop working at next cell 🤷 not sure if issue with ipywidgets,tqdm or vscode

**Comment by DonJayamanne** [comment]
> For today the issue seems happen while using remote kernels only and I can't get rich progress bar to render either, so not a tqdm issue this time

Sorry you are running into this and thank you for sharing this information.
If you are using the widgets, then please can you file a new issue, as this issue focuses on non-widgtets (text based)
Please do share the information required to repro this.

**Comment by DonJayamanne** [comment]
Given the fact that tqdm text doesn't work in Jupyter lab as well, its not specific to VS Code.
Also the widget version of tqdm works as expected.
Hence closing this issue as there's nothing that needs to be resolved in VS Code
