### ISSUE TITLE
Cannot retrieve remote Kernels from JupyterHub when username contains ',' character

### ISSUE THREAD

**Issue by jkornblum** [microsoft/vscode-jupyter#15715]
## Environment data

-   VS Code version: 1.89.1
-   Jupyter Extension version (available under the Extensions sidebar): v2024.4.0
-   Python Extension version (available under the Extensions sidebar): v2024.6.0
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: 3.11 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda (on server)
-   Jupyter server running: Remote

## Expected behaviour

Can connect to remote JupyterHub Kernel using UI prompts (supply host, username, password, token) and successfully using Kernel. 

## Actual behaviour

It authenticates to server but fails to retrieve Kernels, it gives message on UI "Unable to connect to remote server"
It does not list any remote kernels.

## Steps to reproduce:

Provide a username with a comma character ',' in it
For example username `kornblum, joshua`

## Logs

While I'm not familiar with this library other than being a user I did some digging and understand the problem.
I'm not sure best place to resolve it but hoping for some feedback.

The username is not being URL encoded "correctly", i.e. the comma is not URL encoded to `%2C` so it passes this
URL request `https://jhub.eap.tceh.net/user/kornblum,%20joshua/api/kernels` instead of `https://jhub.eap.tceh.net/user/kornblum%2C%20joshua/api/kernels`. It happens regardless if I pass the following to the UI

- `https://jhub.eap.tceh.net/user/kornblum%2C%20joshua/` (this one I would expect to work)
- `https://jhub.eap.tceh.net/user/kornblum, joshua/` (I understand why this is not working)

Somewhere along the way this `kornblum%2C%20joshua` is being changed to `kornblum,%20joshua` which is causing the problem. I can't identify where. This was working in older versions of this extension.

Here are some relevant links to JupyterLab repo

https://github.com/microsoft/vscode-jupyter/blob/235f3885e4ed280945f315ead12a0c64cd18d2b1/src/kernels/jupyter/finder/remoteKernelFinder.ts#L327

https://github.com/jupyterlab/jupyterlab/blob/144a5e84a3af41caa31d206e4aaef5fd9ff1e330/packages/services/src/kernel/restapi.ts#L69

https://github.com/jupyterlab/jupyterlab/blob/144a5e84a3af41caa31d206e4aaef5fd9ff1e330/packages/services/src/serverconnection.ts#L332

I can reproduce/fix the issue with this little script
``` javascript
let bad_url1 = "https://jhub.eap.tceh.net/user/kornblum, joshua/api/kernels"
let bad_url2 = "https://jhub.eap.tceh.net/user/kornblum,%20joshua/api/kernels"
let good_url = "https://jhub.eap.tceh.net/user/kornblum%2C%20joshua/api/kernels";

fetch(bad_url1, { headers: {'Authorization': 'token 7fsdfsdfd'} })
  .then(resp => {
	return resp.text();
  })
  .then(data => {
	console.log(data)
  })
;
// shows error page

fetch(bad_url2, { headers: {'Authorization': 'token dfsdsfs'} })
  .then(resp => {
	return resp.text();
  })
  .then(data => {
	console.log(data)
  })
;
// shows error page

fetch(good_url, { headers: {'Authorization': 'token sdfasfa'} })
  .then(resp => {
	return resp.text();
  })
  .then(data => {
	console.log(data)
  })
;
// returns list of kernels
```

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
15:59:09.989 [error] Jupyter Lab Helper:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at v.dispose (/Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.4.0-darwin-x64/dist/node_modules/@jupyterlab/services.js:11:10935)
	at ni.dispose (/Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.4.0-darwin-x64/dist/node_modules/@jupyterlab/services.js:11:29299)
	at r.dispose (/Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.4.0-darwin-x64/dist/extension.node.js:191:14050)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)
	at async __.listKernelsFromConnection (/Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.4.0-darwin-x64/dist/extension.node.js:296:20211)
	at async /Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.4.0-darwin-x64/dist/extension.node.js:296:17636]
15:59:09.989 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache [r [Error]: Invalid response: 404 Not Found
	at r.create (/Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.4.0-darwin-x64/dist/node_modules/@jupyterlab/services.js:11:1067)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Object.Rl [as listRunning] (/Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.4.0-darwin-x64/dist/node_modules/@jupyterlab/services.js:11:4507)
	at async r.getRunningKernels (/Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.4.0-darwin-x64/dist/extension.node.js:191:14446)
	at async Promise.all (index 0)
	at async __.listKernelsFromConnection (/Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.4.0-darwin-x64/dist/extension.node.js:296:19348)
	at async /Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.4.0-darwin-x64/dist/extension.node.js:296:17636] {
  response: p [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://jhub.eap.tceh.net/user/kornblum,%20joshua/api/kernels?1716584349653',
      status: 404,
      statusText: 'Not Found',
      headers: [p [Headers]],
      counter: 0
    }
  },
  traceback: ''
}
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Sorry for not getting back to you on this.
What version of Jupyter Hub extension do you have installed?
Please let me know if you are still running into this issue.
