### ISSUE TITLE
Workspace-level `jupyter.runStartupCommands`

### ISSUE THREAD

**Issue by mthiboust** [microsoft/vscode-jupyter#15713]
Currently, the `jupyter.runStartupCommands` setting can only be set in the user settings file. It would be useful if it could also be defined in the workspace settings file.

Use case: sharing this setting with collaborators through a `.vscode/settings.json` in a git repository.

**Comment by DonJayamanne** [comment]
Thank you for this feature request, however there haven't been sufficient upvotes on this feature request, hence closing this
