### ISSUE TITLE
View Databricks Notebooks as Jupyter Notebooks/Custom Notebook file format.

### ISSUE THREAD

**Issue by MarthinusBosman** [microsoft/vscode-jupyter#15717]
I've honestly been looking into developing a custom notebook that supports databricks .py files, but realized that while it's easy to make it render like a notebook, it doesn't come with the functionality to actually run it in the same kernel used in this jupyter extension.

It would likely be simpler to just add support for databricks files within this extension, just adding read logic whenever the correct first line is detected.

That said, this repo is massive and I can't make heads or tails of it yet.

But this would be a great feature imo.

**Comment by DonJayamanne** [comment]
Thankyou for this feature request, however there aren't enough upvotes on this issue, hence closing this.
