### ISSUE TITLE
deno kernel bug

### ISSUE THREAD

**Issue by YicanPeng** [microsoft/vscode-jupyter#15737]
## Environment data
-   VS Code version:1.89.1 (system setup)
-   Jupyter Extension version: 2024.4.0
-   Python Extension version: 2024.6
-   OS: Windows_NT x64 10.0.19044
-   Anaconda version: conda 24.5.0
-   Deno version: 1.44.0
-   Type of virtual environment used :NA
-   Jupyter server running: Local

## Expected behaviour

I use deno as the jupyter extension's kernel, and write JavaScript in .ipynb file. The kernel works well when it runs single-line code like `console.log(1)`. But if it runs a loop code like `for (let i=0;i<5;i++){console.log(i);}`, the vscode outputs only the last number instead of the whole loop results. In the original     jupyter lab, the browser will output all as expected.

### wrong output in vscode
![3f6079d224bcda915bc2e8e8215561cb](https://github.com/microsoft/vscode-jupyter/assets/51412272/f13f5b29-43cd-48fa-8a62-6fc3d7ab098f)
### right output in a Edge browser tab of jupyterlab
![image](https://github.com/microsoft/vscode-jupyter/assets/51412272/4ad75de7-3715-486d-b742-2189219951f8)

**Comment by DonJayamanne** [comment]
Caused by upstream issue https://github.com/denoland/deno/issues/24737
