### ISSUE TITLE
If XDG_DATA_HOME is configured without JUPYTER_DATA_DIR, the app doesn't appear to find kernels

### ISSUE THREAD

**Issue by randallb** [microsoft/vscode-jupyter#15735]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When XDG_DATA_HOME is configured (seemingly without JUPYTER_DATA_DIR) on unix, the plugin fails to properly detect kernels.

https://github.com/microsoft/vscode-jupyter/blob/f41cffb91a1853a639ae7b29f50072126cb0e459/src/kernels/raw/finder/jupyterPaths.node.ts#L32

https://github.com/bolt-foundry/vscode-jupyter/blob/main/build/installDenoKernel.ts#L10

https://github.com/microsoft/vscode-jupyter/blob/f41cffb91a1853a639ae7b29f50072126cb0e459/src/kernels/raw/finder/jupyterPaths.node.unit.test.ts#L251-L260

I think those are the related callsites / tests. I didn't feel familiar enough to try a PR, but am happy to do so.

### VS Code Version

1.89

### Jupyter Extension Version

v2024.4.0

### Coding Language and Runtime Version

deno

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and sorry you are running into this & sorry you are running into this.
Lets first try to get to the bottom of the issue, based on your description some kernels aren't getting detected.
However the code you have highlighted doesn't seem to be causing any issues.

Please could you
* Download the attached file
* Extract this file
* Open VS Code Insiders (if you haven't got that, please could you install VS Code insiders) and select the command `Install from VSIX`
* Select the above extracted VSIX
* When prompted to reload VS Code, please do so
* Try to replicate the issue once again


[ms-toolsai-jupyter-insiders.vsix (3).zip](https://github.com/user-attachments/files/16397343/ms-toolsai-jupyter-insiders.vsix.3.zip)

**Comment by DonJayamanne** [comment]
Closing this issue as the information requested was not provided
