### ISSUE TITLE
Open running remote Jupyter notebooks

### ISSUE THREAD

**Issue by mmrnustik** [microsoft/vscode-jupyter#1573]
VSCode should allow to open and connect to notebooks on Jupyter server visible on `/tree?` page.

**Comment by Minxiangliu** [comment]
@rchiodo 
Hi, I am trying to use vscode for remote jupyter. 
I have started the jupyter server on linux.
![image](https://user-images.githubusercontent.com/30144428/118605396-d512b200-b7e8-11eb-92aa-81c4ac9ad319.png)

but when I copy the URL in vscode(Windows), there is no response
![image](https://user-images.githubusercontent.com/30144428/118605731-29b62d00-b7e9-11eb-8a3b-9da3b855e46c.png)

However, the web can be accessed normally
![image](https://user-images.githubusercontent.com/30144428/118606049-86b1e300-b7e9-11eb-8970-5a5e0e86394a.png)

What am i missing?

**Comment by rchiodo** [comment]
@Minxiangliu your issue is a dupe of this: https://github.com/microsoft/vscode/issues/110528

VS code is not allowing the enter key to work.

**Comment by IanMatthewHuff** [comment]
I believe that this initial bug here (showing running sessions on a remote server) has been resolved, so closing this issue. I think that #1366 solves the other issues mentioned.
