### ISSUE TITLE
Causes black to crash

### ISSUE THREAD

**Issue by elmdecoste** [microsoft/vscode-jupyter#15738]
Type: <b>Bug</b>

The Jupyter extension is causing the black extension to crash

Extension version: 2024.4.0
VS Code version: Cursor 0.34.0 (838bc2665badb9638e37757a74e5586cfea89e50, 2024-05-27T00:09:09.301Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|8, 6, 6|
|Memory (System)|32.00GB (1.01GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DonJayamanne** [comment]
Thank you for filing this issue,
Given that you are not using the standard version of VS Code I'm closing this issue.
I do not believe the stable (nor insiders) version of VS Code runs into such issues with Jupyter extension, it seems to be related to the custom build of Cursor that seems to be causing this issue.

Similar issues https://github.com/microsoft/vscode-jupyter/issues/15721
