### ISSUE TITLE
Moving cells around should recenter the notebook on that cell

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-jupyter#1575]
When you move a cell up or down, the screen doesnt recenter around the cell that you are moving, so if you have to move the cell multiple spots, you need to keep moving your mouse/scrolling in the notebook

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed with new native support for editing notebooks starting with v1.59 of VS Code. If this issue continues to occur in the latest build of VS Code, please reopen or enter a new issue.
