### ISSUE TITLE
variables assigned to via the %%bigquery magic wrongly show red underline

### ISSUE THREAD

**Issue by myyc** [microsoft/vscode-jupyter#15751]
## Environment data

-   VS Code version: 1.90.0
-   Jupyter Extension version (available under the Extensions sidebar): v2024.5.0
-   Python Extension version (available under the Extensions sidebar): v2024.8.0
-   OS (Windows | Mac | Linux distro) and version: Arch Linux
-   Python and/or Anaconda version: 3.12.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: N/A

## Expected/Actual behaviour

to reproduce this:

```
%%bigquery bqtest
select 1
```

see screenshots below. worth pointing out that not only does the variable exist "in general", vscode also shows it in the variable inventory (second screenshot).

![Screenshot from 2024-06-08 11-32-23](https://github.com/microsoft/vscode-jupyter/assets/5025392/fd27054b-af49-443e-9c9f-03bd1b704718)
![image](https://github.com/microsoft/vscode-jupyter/assets/5025392/1beb3413-1c87-4be2-a49b-c01ce650226b)

## Logs

No relevant output as it's a frontend issue.

**Comment by DonJayamanne** [comment]
Thank you for filing this feature request, closing this issue as there haven't been sufficient upvotes on this.

**Comment by myyc** [comment]
it's not a feature request, it's a bug

**Comment by DonJayamanne** [comment]
Do you have the pylance extension installed
The red underline works be provided by that extension (or similar) and not Jupyter extension

Easy way to determine is to disable pylance if you have that installed

**Comment by myyc** [comment]
i have the pylance extension installed, and you're right, it's a pylance error: `"bqtest" is not definedPylance`; whose fault it is then, is it pylance not getting the variable via the magic, or is it vscode-jupyter not passing it correctly? or maybe it's an issue in the magic itself?

**Comment by DonJayamanne** [comment]
Jupyter extension isn’t responsible for passing any additional information to pylance in this case, 
This feature needs to be supported by pylance itself,

Please can you create an issue against the pylance extension as this is beyond the scope of the Jupyter extension
I’m sorry I wasn’t able to provide this information sooner
