### ISSUE TITLE
Issue #9264 not solved but locked by the bot

### ISSUE THREAD

**Issue by GitHunter0** [microsoft/vscode-jupyter#15750]
Hey folks, I just replicated the issue #9264 with the latest version of VScode `1.90.0` and Jupyter `2024.5.0` for Windows. Can you please reopen it?

**Comment by DonJayamanne** [comment]
@GitHunter0 Are you still running into this issue?

**Comment by DonJayamanne** [comment]
Done, reopened https://github.com/microsoft/vscode-jupyter/issues/9264
