### ISSUE TITLE
"Jupyter kernel..." item is missing when selecting a kernel for a notebook

### ISSUE THREAD

**Issue by ibobak** [microsoft/vscode-jupyter#15769]
Type: <b>Bug</b>

I have anaconda installled, and I have multiple environments in my anaconda.
On my host Linux machine I see this set of elements when selecting a kernel for my notebook:

![image](https://github.com/microsoft/vscode-jupyter/assets/8807043/4b60a873-ffb0-4398-9d84-99ed631cdc9b)

I've also made a clean VM with the same OS (Ubuntu 22.04), with the same anaconda,  installed the same version of VS Code.  And in my VM I see this:

![image](https://github.com/microsoft/vscode-jupyter/assets/8807043/3954f5a0-6ba0-4bc6-b1e2-63ab01cb43d9)

There also exist some environments, they are made the same way (conda create --name  env_name).   But unfortunately, VS code doesn't see them.

Note: if I run separately  "jupyter notebook" or "jupyter lab", the notebook/lab  WILL see those kernels, and this means the specifications (kernel.json) are fine.

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:02:43.666Z)
OS version: Linux x64 6.4.6-060406-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2696 v4 @ 2.20GHz (88 x 1477)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 5|
|Memory (System)|251.76GB (216.11GB free)|
|Process Argv|--crash-reporter-id 27d42247-63fb-4d9e-9cb0-87d9974843dc|
|Screen Reader|no|
|VM|50%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
2f103344:31071589

```

</details>

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).

**Comment by ibobak** [comment]
Did you mean "trace"?  I don't see "verbose" in the list.

Here is the log:
```
Visual Studio Code (1.90.2, undefined, desktop)
Jupyter Extension Version: 2024.5.0.
Python Extension Version: 2024.10.0.
Pylance Extension Version: 2024.7.1.
Platform: linux (x64).
Workspace folder ~/Projects2/ml_general, Home = /home/ihor
01:06:54.330 [debug] Start refreshing Kernel Picker (1721858814330)
01:06:55.890 [debug] API called from ms-toolsai.vscode-jupyter-powertoys
01:06:55.897 [trace] Search for KernelSpecs in Interpreter /bin/python3
01:06:55.898 [trace] Search for KernelSpecs in Interpreter /usr/bin/python3
01:06:55.898 [trace] Search for KernelSpecs in Interpreter /opt/anaconda3/bin/python
01:06:55.898 [trace] Search for KernelSpecs in Interpreter /opt/anaconda3/envs/generic/bin/python
01:06:55.900 [debug] Get Custom Env Variables, Class name = Bm, completed in 1570ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
01:06:55.900 [debug] Jupyter Paths /kernels: 
01:06:55.900 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
01:06:56.970 [debug] KernelProvider switched kernel to id = .jvsc74a57bd08de3d3f3f8a288c9565bea1d307549b7b00ae8ffed7e5b61917d20ed003331ae./opt/anaconda3/envs/generic/python./opt/anaconda3/envs/generic/python.-m#ipykernel_launcher
01:06:56.971 [debug] Controller selection change completed
01:06:56.982 [debug] Get Custom Env Variables, Class name = Bm, completed in 1ms, has a truthy return value, Arg 1: "~/Projects2/ml_general", Arg 2: "RunPythonCode"
01:06:57.117 [trace] Hiding default KernelSpec /opt/anaconda3/bin/python for interpreter /opt/anaconda3/bin/python (KernelSpec file /opt/anaconda3/share/jupyter/kernels/python3/kernel.json)
01:06:57.118 [trace] Hiding default KernelSpec /opt/anaconda3/envs/generic/bin/python for interpreter /opt/anaconda3/envs/generic/bin/python (KernelSpec file /opt/anaconda3/envs/generic/share/jupyter/kernels/python3/kernel.json)
01:06:57.118 [debug] End refreshing Kernel Picker (1721858814330)
01:06:58.248 [trace] Conda file is conda
01:06:58.749 [debug] Interpreter for Pylance for Notebook URI "~/Projects2/ml_general/eda/generic/catboost1.ipynb" is /opt/anaconda3/envs/generic/bin/python
01:06:59.375 [debug] Got env vars from Python Ext in 2394ms for /opt/anaconda3/envs/generic/bin/python, with env var count 80.
01:06:59.376 [trace] Prepend PATH with python bin for /opt/anaconda3/envs/generic/bin/python
01:06:59.376 [debug] Getting activated env variables, Class name = Pp, completed in 2395ms, has a truthy return value, Arg 1: "~/Projects2/ml_general", Arg 2: "/opt/anaconda3/envs/generic/bin/python", Arg 3: undefined
01:06:59.383 [info] Process Execution: /opt/anaconda3/envs/generic/bin/python -m pip list
01:07:01.639 [trace] Registering commtarget jupyter.widget
01:07:01.640 [debug] Start refreshing Interpreter Kernel Picker
01:07:01.640 [debug] Start refreshing Kernel Picker (1721858821640)
01:07:01.948 [trace] Python API env change detected, update => '/bin/python3'
01:07:01.952 [trace] Python API env change detected, update => '/opt/anaconda3/bin/python'
01:07:01.955 [trace] Search for KernelSpecs in Interpreter /opt/anaconda3/bin/python
01:07:01.956 [trace] Python API env change detected, update => '/opt/anaconda3/envs/generic/bin/python'
01:07:01.957 [trace] Python API env change detected, update => '/usr/bin/python3'
01:07:01.962 [debug] Refreshed Environments
01:07:01.962 [trace] Hiding default KernelSpec /opt/anaconda3/bin/python for interpreter /opt/anaconda3/bin/python (KernelSpec file /opt/anaconda3/share/jupyter/kernels/python3/kernel.json)
01:07:02.964 [debug] End refreshing Kernel Picker (1721858821640)

```

**Comment by DonJayamanne** [comment]
Yes, `trace`, sorry about that.

**Comment by DonJayamanne** [comment]
> Note: if I run separately "jupyter notebook" or "jupyter lab", the notebook/lab WILL see those kernels, and this means the specifications (kernel.json) are fine.

* Do you know where these kernel specs are, if you do, please can you share the full path to the location of these kernelspecs
* In a terminal, please can you run the command `python -m jupyter kernelspec list` and share the output (this will dump the list of kernels)
