### ISSUE TITLE
python extension output hyperlinks

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#1576]
Issue Type: <b>Feature Request</b>

Directed here by @rchiodo from this [StackOverflow post](https://stackoverflow.com/questions/54367355/ability-to-follow-hyperlinks-displayed-in-vs-code-python-extension-interactive-p/54931643#54931643)

To reiterate: 

The code below correctly displays the hyperlinks to the Jupyter Server running remotely or locally.  However, even though the mouse cursor changes from an arrow-cursor to the hand cursor, I cannot follow the link by either clicking on it or `ctrl`+clicking on it.

What do I need to do to be able to follow hyperlinks displayed in the VS Code Python extension's Interactive Python pane?

```python
from IPython.display import display, Markdown
from subprocess import Popen, PIPE
import pandas as pd

process = Popen(['powershell', 'jupyter notebook list'], stdout=PIPE, stderr=PIPE)
stdout, stderr = process.communicate()

jupy = stdout.decode('utf-8')\
        .replace('Currently running servers:\r\n', '')\
        .strip()\
        .split('\r\n')

jupy = [item.split(' :: ')[0] for item in jupy]
# jupy = ['<a href="{}">{}</a>'.format(item, item) for item in jupy]

for link in jupy:
    display(Markdown('[{}]'.format(link)))
```

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

**Comment by amunger** [comment]
this works now
