### ISSUE TITLE
!pip uninstall in jupyer has issues

### ISSUE THREAD

**Issue by Lord225** [microsoft/vscode-jupyter#15760]
Type: <b>Bug</b>

When you run for example:
```
!pip uninstall UMAP
!pip install umap-learn
```
it will stall on uninstall and ask for `Y` but when you cancel the execution it will go on with next command. Jupyter will detect it as he is not able to stop process and incoceccly display information amout not being able to interupt kernel.

Extension version: 2024.5.0
VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

**Comment by DonJayamanne** [comment]
Please pass the `-y` flag into the `pip` command as follows
`!pip uninstall UMAP -y`

**Comment by Lord225** [comment]
Yes, that solution works, but it is important to note that Jupyter recognizing `!pip uninstall UMAP` as a kernel crash is still a bug that should be addressed.

**Comment by Lord225** [comment]
![image](https://github.com/microsoft/vscode-jupyter/assets/49908210/516de7d7-6e08-4af4-b27d-63a1b73b2793)

**Comment by DonJayamanne** [comment]
Unfortunately this issue beyond the control of the jupyter extension.
This is actually a problem with ipykernel and jupyter lab/notebook.

Ie you will think into this exact same problem outside vscode
