### ISSUE TITLE
Filtering of variables in "Jupyter" window is needed

### ISSUE THREAD

**Issue by ibobak** [microsoft/vscode-jupyter#15774]
It would be good to have something like a filter for variables:  if there are a lot of them, it is hard to scroll.  It would be good to type in a part of name and quickly get the filtered list:

![image](https://github.com/microsoft/vscode-jupyter/assets/8807043/d5ec7c28-5e1e-4f82-8096-de98a6639710)

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
