### ISSUE TITLE
Memory leak with jupyter notebook and vs code tunnel

### ISSUE THREAD

**Issue by AlessandroGrassi1998** [microsoft/vscode-jupyter#15775]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I am using a [remote tunnel](https://code.visualstudio.com/docs/remote/tunnels) to connect to a linux machine where a jupyter hub server is running. I noticed that very often memory is not deallocated even after restarting the kernel, this especially applies with GPU memory. I am using the GPU to run pytorch code, using the CUDA api. The only way to clear the memory is to restart the machine. 
Is there a solution to this? Or is this a known issue?

Thanks for your help, I remain available to provide further information if needed

### VS Code Version

1.90.1

### Jupyter Extension Version

v2024.5.0

### Coding Language and Runtime Version

Python 3.10.14

### Language Extension Version (if applicable)

Python extension v2024.8.1

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
I'm sorry for never getting back to you on this issue.
Are you still  running into this problem?

Is it possible that the kernels are still running in the background?
Also, please can you share some of the lgos from the Jupyter extension.
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).
