### ISSUE TITLE
jupyter notebook convert from python file does not process "# %%" well

### ISSUE THREAD

**Issue by nscavalier** [microsoft/vscode-jupyter#15778]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90.1
- OS Version: Windows 10

Steps to Reproduce:

1. I export the jupyter notebook to a python file, the cell is separated with '# %%'
2. I convert the python file back to notebook, these '# %%' still preserved in each cells.
3. I try to use the replace (ctrl-H) to replace the '# %%\n' (with regex on), I can not find all the matches in each cell. It looks like I can only find the recent cells in my sight.

**Comment by amunger** [comment]
verification: 
1. open a notebook and select a kernel (just to avoid a separate activation issue)
2. open a saved python file with some `# %%` code cells 

e.g.

```
#%%
import requests
def download(url, filename):
    """ utility function to download a file """
    response = requests.get(url, stream=True)
    with open(filename, "wb") as handle:
        for data in response.iter_content():
            handle.write(data)

#%% 
# """
# # a
# b
# """

#%% [markdown]
'''
# a
b
'''
```

4. run `Jupyter: Export Current Python File as Jupyter Notebook`
5. verify the cell content is correct and doesn't contain the `# %%` markers
