### ISSUE TITLE
Variables viewer is not able to show contents of `polars` `DataFrame`

### ISSUE THREAD

**Issue by bzm3r** [microsoft/vscode-jupyter#15773]
This is a follow-up issue on: 
* https://github.com/pola-rs/polars/issues/6152
* https://github.com/microsoft/vscode-jupyter/issues/12519

#12519 was resolved, so its not clear to me why this issue is occurring now. It may be entirely unrelated.
 
## Environment data

-   VS Code version: 
```
Version: 1.90.1
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:02:43.666Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
```

-   Jupyter Extension version (available under the Extensions sidebar): XXX
```
Name: Jupyter
Id: ms-toolsai.jupyter
Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.
Version: 2024.5.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
```

-   Python Extension version (available under the Extensions sidebar): XXX
```
Name: Python
Id: ms-python.python
Description: Python language support with extension access points for IntelliSense (Pylance), Debugging (Python Debugger), linting, formatting, refactoring, unit tests, and more.
Version: 2024.8.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python
```
-   OS (Windows | Mac | Linux distro) and version: XXX
```
OS: Linux x64 5.15.0-112-generic
```
-   Python and/or Anaconda version: Python 3.11.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

Variables are displayed.

## Actual behaviour

![image](https://github.com/microsoft/vscode-jupyter/assets/4350451/0e42e039-b933-4162-80ba-864d09b7eb7e)

## Steps to reproduce:

Copy and paste the following code within either a Jupyter Notebook or Interactive Window:

```py
import polars as pl

x = pl.DataFrame({"alpha": [1, 2, 3, 4], "beta": ["c", "u", "d", "m"]})
```

2. Click on the Variables viewer, and then attempt to view the variable `x`.

## Logs

```
14:33:25.277 [info] Process Execution: ~/miniforge3/envs/jjpred/bin/python -c "import pandas;print(pandas.__version__);print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d")"
14:33:25.995 [error] [Error: Failed to fetch variable info from the Jupyter Server.
	at VI.extractJupyterResultText (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.5.0-linux-x64/dist/extension.node.js:435:82)
	at VI.deserializeJupyterResult (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.5.0-linux-x64/dist/extension.node.js:435:164)
	at VI.getDataFrameInfo (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.5.0-linux-x64/dist/extension.node.js:434:39717)
	at async Wu.ensureInitialized (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.5.0-linux-x64/dist/extension.node.js:435:30068)
	at async Wu.getDataFrameInfo (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.5.0-linux-x64/dist/extension.node.js:435:28893)
	at async Xf.prepDataFrameInfo (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.5.0-linux-x64/dist/extension.node.js:435:14293)
	at async Xf.showData (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.5.0-linux-x64/dist/extension.node.js:435:12418)]
```

**Comment by amunger** [comment]
The jupyter data viewer is [being deprecated](https://github.com/microsoft/vscode-jupyter/issues/15486), but you can try the [Data Wrangler extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.datawrangler), which already has support for polars dataframes.
