### ISSUE TITLE
Jupyter Notebook kernel restarts automatically

### ISSUE THREAD

**Issue by rakeshku93** [microsoft/vscode-jupyter#15772]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Jupyter Notebook kernel restarts in VS Code every time I run a cell, it is quite frustrating.

### VS Code Version

VSCodeUserSetup-x64-1.90.1

### Jupyter Extension Version

v2024.5.0

### Coding Language and Runtime Version

Python 3.10

### Running Jupyter locally or remotely?

Local

**Comment by rakeshku93** [comment]
Hi @DonJayamanne  Kindly let me know if you need any details. Thanks for looking into this issue.

**Comment by DonJayamanne** [comment]
@rakeshku93 I'm sorry I missed this issue, are you still running into this issue.

**Comment by rakeshku93** [comment]
Yes

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.
