### ISSUE TITLE
Can't use GPU

### ISSUE THREAD

**Issue by uvezero** [microsoft/vscode-jupyter#15780]
## Environment data

Version: 1.90.1
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:02:43.666Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.5.0-35-generic

## Expected behaviour
import torch
(no problem)

## Actual behaviour
 I am using:
NVIDIA-SMI 550.90.07 Driver Version: 550.90.07 CUDA Version: 12.4

Cuda compilation tools, release 12.5, V12.5.40

and cudnn for cuda 12.
The problem is that when I run code in the terminal it appears to be able to use the GPU.
'''
x = torch.tensor([1.0, 2.0, 3.0], device='cuda')

Tensor operation result on GPU: tensor([5., 7., 9.], device='cuda:0')

'''
But when I try to import torch in VScode in a notebook I get this:
'''

Running cells with 'test_env (Python 3.12.1)' requires the ipykernel package.
Run the following command to install 'ipykernel' into the Python environment.
Command: '/home/juan/test_env/bin/activate -m pip install ipykernel -U --force-reinstall'

'''
I tried to run this in terminal:
" pip install ipykernel -U --force-reinstall " but it didn't work it just stop me from being able to use the GPU in the terminal as well.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, and I'm sorry for the delay in getting back to you on this issue.
Are you still running into this problem?
