### ISSUE TITLE
Code blocks always sending minimized makes it difficult to check what sent.

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode-jupyter#15799]
Testing microsoft/vscode-python#23676

```python
my_dict = {
    'key1': 'value1',
    'key2': 'value2',
    'key3': 'value3',
    'key4': 'value4'
}

class MyClass:
    def my_function(self):
        print("Hello, world!")
        print("bye, world!")

# Create an instance of MyClass
my_instance = MyClass()

# Call the my_function method
my_instance.my_function()
```

I placed my cursor on the end of every single line in the file, and hit shift+enter for each. Here is what the smart repl showed by default.
![image](https://github.com/microsoft/vscode-python/assets/12552271/46e62602-c0b6-461c-b41a-f4900c075ac9)

It's fairly difficult to figure out if the correct line sent to the repl if the blocks always appear minimized.

**Comment by amunger** [comment]
The idea was that the code is the same as what was in the source file, but it is more obvious with `# %%` sections for what is being sent to the IW.

Not collapsing a single line cell would make sense, but a single expression could be arbitrarily large, and there is already a setting for this: `"interactiveWindow.collapseCellInputCode": "fromEditor"`.

**Comment by amunger** [comment]
I'm just going to leave this as a setting to keep things consistent unless we get more push from users about this
