### ISSUE TITLE
HTML entity names (without semicolon) replaced by corresponding character when printed

### ISSUE THREAD

**Issue by rben01** [microsoft/vscode-jupyter#1579]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur
1. Open the ipython interactive window
2. In that window, run the command `print(repr("&amp &lt &gt"))`

## Actual behavior
`'& < >'` is printed. Below is a screenshot of the VS Code ipython interactive window.
<img width="252" alt="Screen Shot 2020-01-24 at 10 11 17 PM" src="https://user-images.githubusercontent.com/766670/73115729-0f6f8600-3ef8-11ea-8f88-d88958c553ac.png">

## Expected behavior
`'&amp &lt &gt'` is printed. Below is a screenshot of ipython in Mac's Terminal.app.
<img width="303" alt="Screen Shot 2020-01-24 at 10 11 30 PM" src="https://user-images.githubusercontent.com/766670/73115723-054d8780-3ef8-11ea-8fbb-d8bde092670a.png">

## Other notes
This is unique to `print`; merely returning the string, or `display`ing it, does not cause this issue. Below is a screenshot of the VS Code ipython interactive window.
<img width="307" alt="image" src="https://user-images.githubusercontent.com/766670/73115767-8c9afb00-3ef8-11ea-8cff-060e223941e5.png">

### Your Jupyter and/or Python environment
*Please provide as much info as you readily know*
- **Jupyter server running:**                       Local
- **Extension version:**                               2020.1.58038
- **VS Code version:**                                1.41.1
- **Setting python.jediEnabled:**               false
- **Python and/or Anaconda version:**     Python 3.7.6, conda
- **OS:**                                                     Mac
- **Virtual environment:**                          venv

## Developer Tools Console Output

```
[Extension Host] Info Python Extension: 2020-01-24 22:19:54: Submitting code for 31f3df12-57a3-40a1-820f-6be5e1f218d0
console.ts:137 [Extension Host] Info Python Extension: 2020-01-24 22:19:54: Waiting for jupyter server and web panel ...
console.ts:137 [Extension Host] Info Python Extension: 2020-01-24 22:19:54: Loading web panel. Panel is set
console.ts:137 [Extension Host] Info Python Extension: 2020-01-24 22:19:54: Wait for sys info for 31f3df12-57a3-40a1-820f-6be5e1f218d0 0
console.ts:137 [Extension Host] Info Python Extension: 2020-01-24 22:19:54: Finished execution for b9d76321-cd30-4fe4-9af0-a60948f48132
console.ts:137 [Extension Host] Notification handler 'textDocument/publishDiagnostics' failed with message: Cannot read property 'connected' of undefined
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:581
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:581
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
```

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by greazer** [comment]
I no longer repro this in the interactive window. The expected output is shown. 
![image](https://user-images.githubusercontent.com/11685408/120933544-7c2f8e80-c6af-11eb-8157-ee28c3f256ef.png)
