### ISSUE TITLE
Cell randomly losing focus, view jumping (reopening #12863)

### ISSUE THREAD

**Issue by thobitz** [microsoft/vscode-jupyter#15797]
## Environment data

-   VS Code version: 1.88.1
-   Jupyter Extension version (available under the Extensions sidebar): v2024.3.1
-   Python Extension version (available under the Extensions sidebar): v2024.4.1
- Pylance Extension: v2024.6.1
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Python 3.9.13
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: N/A

## Expected behaviour

Uninterrupted editing of Notebooks

## Actual behaviour

Whenever an autosave occurs or whenever the notebook is saved with Ctrl-S, the current cell loses focus and the notebook scrolls to a  random place. This makes VSC more or less unusable. 

During the save, the "Problems" box is updated. The location to which the notebook scrolls often (but not always) seems to be related to the position of the errors displayed in the Problems box.

The issue has been described comprehensively in bug report 12863, but was auto-closed without resolution.

Unfortunately I cannot access Github or upload any files from my work laptop where the issue occurs. I cannot reproduce the issue on my personal laptop, despite running the same versions of VSC, Jupyter, Python and Pylance. 

## Steps to reproduce:

See above. The issue has been described comprehensively in 12863.

**Comment by ricardorodl** [comment]
Following. Same issue here.

**Comment by amunger** [comment]
closing in favor of https://github.com/microsoft/vscode-jupyter/issues/12863 since that has videos that show the issue

**Comment by DavidMorton** [comment]
@amunger Though this is closed, #12863 is marked as resolved, and so I can't comment. I just want to chime in and say that this has started happening to me this year. At first, it was only on VSCode in the cloud, when launching from AML, so I switched to using VSCode with the remote extension, and that worked for a while. Now it's happening again. Do you know of any workaround currently? It's driving me nuts and really breaking the flow

**Comment by thobitz** [comment]
Currently my workaround is to disable Autosave. Which obviously isn’t a solution – but at least I can use Jupyter NBs for demos and tests now and then.

**Comment by amunger** [comment]
oh, sorry, didn't realize the conversation was still locked, I've unlocked https://github.com/microsoft/vscode-jupyter/issues/12863
