### ISSUE TITLE
Where is the side bar of jupyter

### ISSUE THREAD

**Issue by codegzx** [microsoft/vscode-jupyter#15802]
## Environment data

-   VS Code version: 1.90.2
-   Jupyter Extension version (available under the Extensions sidebar): v2024.5.0
-   Python Extension version (available under the Extensions sidebar): v2024.8.1
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: py3.11.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local 

## 
I can‘’t find sidebar of jupyter and can't find a config for it.

![image](https://github.com/microsoft/vscode-jupyter/assets/62829855/cc7b79f5-778c-430a-a938-0e1927a802d2)

**Comment by DonJayamanne** [comment]
You need to install the Jupyter Powertoys extension.
https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-powertoys

**Comment by codegzx** [comment]
> You need to install the Jupyter Powertoys extension. https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-powertoys
@DonJayamanne Thanks a lot! It works
