### ISSUE TITLE
Notebook editor: project tree explorer

### ISSUE THREAD

**Issue by andreamoro** [microsoft/vscode-jupyter#1580]
## Description
Pretty much like it happens in other languages, it would be lovely to have access to a project tree explorer to navigate through functions within the code in an easy way.

Other feature that could complete this
- Variable declaration and type (always used to navigate to)

This could perhaps mitigate the absence of the [search functionality](https://github.com/microsoft/vscode-python/issues/7903).

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time.
