### ISSUE TITLE
Talk to jupyter kernel of over unix socket 

### ISSUE THREAD

**Issue by murarisumit** [microsoft/vscode-jupyter#15812]
Have to connect to jupyter notebook from vscode that has unix-socket exposed.

Have multiple notebook running, mapping ports is difficult; can have socket with different names.

**Comment by DonJayamanne** [comment]
> Have multiple notebook running, mapping ports is difficult; can have socket with different names.

Not sure what you mean by mapping ports is difficult
Can you share more information about what you mean by `mapping`, as far as I know users do not need to know anything about these ports.
As for using unix sockets, I personally do not see us supporting this as we've not had such requests in the past and feels like a very edge case requirement.

**Comment by murarisumit** [comment]
Thanks for responding @DonJayamanne, yes understandable might be edge case requirement. 

So for me structure is, want to create multiple notebooks in one repo & have separate dependencies in their own folder. Have docker-compose in each folder to start the jupyter kernel for those dependencies. Entire thing is running on local machine.

```
- root
  - folder1
    -> notebook1.ipynb
    -> notebook2.ipynb
    -> requirements.txt
    -> docker-compose.yaml(new port which isn't conflict, to tell VSCode how to connect to it)
    -> Dockerfile

  - folder2
    -> notebook1.ipynb
    -> notebook2.ipynb
    -> requirements.txt
    -> docker-compose.yaml(new port which isn't conflict with folder1, to tell VSCode how to connect to it)
    -> Dockerfile
```
Right now have docker-compose in each folder(with multiple notebooks & with requirements.txt) & whenever I'm creating new folder have to create find which port aren't already used & then create connection so there is no conflict(because there are multiple notebooks, & some are running in parallel).

Solution: 
If unix socket is supported, can have unix-socket based on folder-names & do docker-compose up & connect with vscode connection based on socket path.

---

Understandable with bandwidth restriction, if you can guide can make changes for this.
