### ISSUE TITLE
Dev process: npm i (or npm ci) freezes / takes too long

### ISSUE THREAD

**Issue by xl0** [microsoft/vscode-jupyter#15813]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I want to hack a bit. Following https://github.com/microsoft/vscode-jupyter/blob/main/CONTRIBUTING.md I ran
`npm ci`
and it hangs after a while, not showing any progress for over 15 minutes, and not showing up in top.
I see that in CI you use ` npm ci --ignore-scripts --prefer-offline --no-audit`

In my limited experience with node, I've never faced this issue, so not sure if it should be fixed, or the docs should be updated.

(I installed recommended node version through mamba, and then installed the recommended npm version)

### VS Code Version

recent

### Jupyter Extension Version

master

### Running Jupyter locally or remotely?

Local

**Comment by xl0** [comment]
I also had to run
`npm run postinstall`
To actually get a working environment. But at least it worked. Is this a bug, or just lack of documentation?

**Comment by DonJayamanne** [comment]
Sorry for never getting back to you. Are you still running into this issue.
We used to have similar issues, however that was related to an npm package that has since been removed.

**Comment by xl0** [comment]
```
$ npm i
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated @types/del@4.0.0: This is a stub types definition. del provides its own type definitions, so you do not need this installed.
npm WARN deprecated postinstall-build@5.0.3: postinstall-build's behavior is now built into npm! You should migrate off of postinstall-build and use the new `prepare` lifecycle script with npm 5.0.0 or greater.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated lolex@6.0.0: lolex has been renamed to @sinonjs/fake-timers. No API changes made. Please use the new package instead
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated vscode-debugprotocol@1.51.0: This package has been renamed to @vscode/debugprotocol, please update to the new name
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated codecov@3.8.3: https://about.codecov.io/blog/codecov-uploader-deprecation-plan/
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
(##################) ⠙ reify:date-fns: timing reifyNode:node_modules/rxjs Completed in 7281ms
```
(just hangs here, no CPU activity)

**Comment by DonJayamanne** [comment]
thats so weird, I'm assuming you are using the asme version of node.js `18.15.0`?

**Comment by xl0** [comment]
My bad, I had 18, but 18.20 because.
15 is broken in mamba. I downgraded to .17 which is the lowest that can be installed, and now it works!
