### ISSUE TITLE
When you have a long data frame and plot in one cell, horizontal scrolling should only appear for data frame

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-jupyter#1581]
Feedback from PyData NYC:

If you have a cell that prints out a dataframe that is wider than the screen (causing horizontal scroll bar), and also prints out a matplotlib plot (that fits inside the window), horizontal scrolling will scroll the entire output rather than just the dataframe. JupyterLab has a scroll bar that only scrolls the dataframe.

VS Code:
![image](https://user-images.githubusercontent.com/15910920/68408265-0e2d8900-0153-11ea-9497-81f0e7884be7.png)

JupyterLab:
![image](https://user-images.githubusercontent.com/15910920/68408330-28676700-0153-11ea-8842-ad58cd61b227.png)

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
