### ISSUE TITLE
Markdown cell fails to embed image from Drive

### ISSUE THREAD

**Issue by dtrizna** [microsoft/vscode-jupyter#15819]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Markdown has ability to insert files from remote location. It generally works fine in VSCode, but does not with `drive.google.com` links for some reason, e.g.:

```
<img src="https://drive.google.com/uc?id=1NJ2ivw31VV94LeYSPayvmvsZ-BZlPa7i" width="600">
```
nor 
```
<img src="https://drive.usercontent.google.com/download?id=1NJ2ivw31VV94LeYSPayvmvsZ-BZlPa7i&authuser=0" width="600">
```

![image](https://github.com/microsoft/vscode-jupyter/assets/15322061/c47869a1-413d-4b5d-82dd-877b9bb7b2fc)

It works both in Collab and in Github's notebook parser. This is the method people suggest to embed images when working in Collab. To keep availability of material in both platforms (Collab and VSCode), solving this bug is paramount.

### VS Code Version

Version: 1.90.2 (user setup) Commit: 5437499feb04f7a586f677b155b039bc2b3669eb Date: 2024-06-18T22:34:26.404Z Electron: 29.4.0 ElectronBuildId: 9728852 Chromium: 122.0.6261.156 Node.js: 20.9.0 V8: 12.2.281.27-electron.0 OS: Windows_NT x64 10.0.22631

### Jupyter Extension Version

v2024.5.0

### Running Jupyter locally or remotely?

None

**Comment by dtrizna** [comment]
Hey! Is there any chance to get an update on that?

**Comment by DonJayamanne** [comment]
Sorry for never getting back to you on this issue, somehow this slipped through the cracks.
Please can you try to replicate this issue and open the dev tools (use the command `Toggle Developer Tools`) and share the error messages found in the console window.
