### ISSUE TITLE
Python Version Display Issue

### ISSUE THREAD

**Issue by KGZaker** [microsoft/vscode-jupyter#15829]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Hello,

My system environment is macOS 14.5, using the Jupyter plugin version v2024.6.0, and Miniforge Conda version 24.5.0. I have discovered an issue where the Python version number is not displayed correctly when using the “Python: Select Interpreter” command (see the attached screenshot, where both “macbio” and “macbio_x86” should be Python 3.12.4, but they are shown as Python 3.1.X).
<img width="723" alt="Code 2024-07-07 10 24 21" src="https://github.com/microsoft/vscode-jupyter/assets/41966490/8612807c-ca4a-4d46-8ece-991361e6f19c">

Interestingly, when I create an `.ipynb` file using the “Create: New Jupyter Notebook” feature and select the kernel with the incorrectly displayed Python version, 
<img width="711" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/41966490/7c56ca8c-8aff-439e-9053-48049020ec76">

a popup (as shown in the screenshot) appears.
<img width="536" alt="Code 2024-07-07 10 26 18" src="https://github.com/microsoft/vscode-jupyter/assets/41966490/5c5c1f68-16d3-470a-a3b9-272ca45d8c59">

However, if I ignore this popup, the kernel still works correctly. Therefore, it seems that the issue might only be related to the retrieval of the Python version information, as the Python functionality still works correctly.

### VS Code Version

1.91.0

### Jupyter Extension Version

v2024.6.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
> However, if I ignore this popup, the kernel still works correctly. Therefore, it seems that the issue might only be related to the retrieval of the Python version information, as the Python functionality still works correctly.

Yes that is correct.

# SOLUTION (WORK AROUND)

As a work around, please ignore this warning message.

**Comment by jgwill** [comment]
An option to ignore this warning would be fantastic :)

**Comment by rubensa** [comment]
Switching to pre-release version of Python extension should fix the issue.  See: https://github.com/microsoft/vscode-python/issues/23649

**Comment by DonJayamanne** [comment]
Closing in favour of the Python extension issue
