### ISSUE TITLE
Passing headers. VScode to Colab Enterprise/JupyterLab with authentication + CORS

### ISSUE THREAD

**Issue by gogasca** [microsoft/vscode-jupyter#15821]
Currently I want to connect VScode with JupyterLab extension to Google Cloud Colab Enterprise or AI Notebooks or any JupyterLab service that requies authentication.
I'm currently using JupyterLab Gateway as a way to overwrite headers (Authentication + CORS - Origin). Is there a way to overwrite HTTP headers in current Extension? If not what is the any good pointers for me to add support for this.

Background:

- https://github.com/jupyter-server/jupyter_server/issues/1439
- https://medium.com/@gogasca_/how-to-connect-from-vscode-to-vertex-notebooks-directly-8c078d538b0b

Wanted behavior:
 Ability to pass custom HTTP header for HTTP(s) and Websockets. Example:

```
headers = {"Origin": PROXY_URL, "Authentication": AUTH_TOKEN}
```

- Some headers like Authentication can be regenerated every X seconds. (Using an external command `gcloud`) 
- 
I would like to see how can I add this to Extension properties. Any pointer will be appreciated

**Comment by gogasca** [comment]
@DonJayamanne any pointers are appreciated. I would be happy to propose a PR. Thanks

**Comment by DonJayamanne** [comment]
@gogasca Thanks for filing this issue.
At this stage we have no plans on supporting such a feature request.
However you can create your own extension that passes the necessary headers and the like.
Please have a look at the Jupyter Hub extension that we've created.

This is a simple extension that takes care of auth and the like (with custom headers).

https://github.com/microsoft/vscode-jupyter-hub

Feel free to reach out for additional details with regards to this extension or the like
