### ISSUE TITLE
Cell with line magic in it doesn't map correctly

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#1582]
#%%
testing = 'hello'
%whos
testing = 'world'

Brings up the temp file. Not the source file.

![DebugMagic.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/a2221ec7-a68b-4057-bd19-566f918ec9b2)

**Comment by roblourens** [comment]
Seems to work now
