### ISSUE TITLE
import jupyter should use currently open file ipynb

### ISSUE THREAD

**Issue by breathe** [microsoft/vscode-jupyter#1583]
Issue Type: <b>Feature Request</b>

1. Open a .ipynb file
2. Dismiss the 'Import Jupyter' (I tend to disable this kind of popup permanently as I often find the notifications somewhat annoying -- particularly when they offer actions which don't 'stay in sync' with other changes in the app interaction contexts)
3. Try to import the file via cmd-shift-p and invoking the 'import jupyter notebook' command
4. See a file-chooser dialogue ... -- but I'm already in the ipynb file I want to import!

It would be nice if there was a command for converting the currently open ipynb file that could be activated/discovered via a cmd-shift-p search ...

Extension version: 2018.12.1
VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.38GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rchiodo** [comment]
I'm not sure this applies anymore. Closing as not relevant.
