### ISSUE TITLE
Repeated notification: Restart Visual Studio Code to apply the latest updates

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#15830]
From marketplace https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details

> ... It always tells me to "Restart Visual Studio Code to apply the latest updates." The booting takes 30 secs which is kinds irritating, then the time VS Code restarts, 20 secs after it, I get the same response to restart ...

**Comment by rebornix** [comment]
It would be great if we have the VS Code version installed on user's machine to troubleshoot.

**Comment by DonJayamanne** [comment]
Its been a while this issue has been opened, and unfortunately we haven't had any new information provided.
Hence closing this issue.
