### ISSUE TITLE
Cannot use "Drop Into Editor" in jupyter notebook

### ISSUE THREAD

**Issue by ProcedureOriented** [microsoft/vscode-jupyter#15839]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Nothing happens when I drag a file from side bar into an open jupyter notebook editor with holding 'shift' key. It used to show a dashed cursor and place the relative path after dropping the file. 
But now it is not showing and working. I can just see the dashed cursor blink once when holding shift key, then disappear.
<img width="526" alt="Screen Shot 2024-07-10 at 15 37 42" src="https://github.com/microsoft/vscode-jupyter/assets/10933927/0249dc59-c5fc-4a53-a6ce-41d2b3375742">

I guess it may have a conflict with VS Code's new feature "Editor › Drop Into Editor: Show Drop Selector"? not sure.

Btw it always not works in interactive window, it will help if "Drop Into Editor" can be used in interactive window.

### VS Code Version

Version: 1.91.0 Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286 Date: 2024-07-01T18:53:23.353Z Electron: 29.4.0 ElectronBuildId: 9728852 Chromium: 122.0.6261.156 Node.js: 20.9.0 V8: 12.2.281.27-electron.0 OS: Darwin arm64 21.6.0

### Jupyter Extension Version

v2024.6.0

### Coding Language and Runtime Version

Python 3.12.4

### Language Extension Version (if applicable)

Python Extension v2024.10.0

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
Can you update and try again? this works for me in 1.92 and 1.92 insiders.
