### ISSUE TITLE
Unable to create interactive window, existing notebooks are shown as json files

### ISSUE THREAD

**Issue by abhisheksoni27** [microsoft/vscode-jupyter#15843]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I am currently not able to see interactive play elements on my run.py file.

My .ipynb files open as JSON.

I have Python as well as Jupyter extensions installed which are distributed by Microsoft.

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/11e0819d-9253-4e9b-942f-2980d52ce246">

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/48a098de-b55b-4375-a3ac-afafbb1bb6a1">

### VS Code Version

Version: 1.91.1 Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729 Date: 2024-07-09T22:07:46.768Z (2 days ago) Electron: 29.4.0 ElectronBuildId: 9728852 Chromium: 122.0.6261.156 Node.js: 20.9.0 V8: 12.2.281.27-electron.0 OS: Darwin arm64 23.5.0

### Jupyter Extension Version

v2024.6.0

### Jupyter logs

```shell
Visual Studio Code (1.91.1, undefined, desktop)
Jupyter Extension Version: 2024.6.0.
Python Extension Version: 2024.10.0.
Pylance Extension Version: 2024.7.1.
Platform: darwin (arm64).
Workspace folder ~/github/trading/algotrading, Home = /Users/abhisheksoni
14:18:14.169 [warn] No interpreter with path ~/github/trading/algotrading/.venv/bin/python3 found in Python API, will convert Uri path to string as Id ~/github/trading/algotrading/.venv/bin/python3
14:18:14.170 [info] Starting interactive window for resource '' with controller '.jvsc74a57bd070e568023ce40db8e86ad6511b69d121cd7702522e8997b095adf0103a97d48a./Users/~/github/trading/algotrading/.venv/python./Users/~/github/trading/algotrading/.venv/python.-m#ipykernel_launcher (Interactive)'
14:18:14.218 [warn] The following kernels use interpreters that are no longer valid or not recognized by Python extension, Kernels startUsingPythonInterpreter:'id=.jvsc74a57bd070e568023ce40db8e86ad6511b69d121cd7702522e8997b095adf0103a97d48a./Users/~/github/trading/algotrading/.venv/python./Users/~/github/trading/algotrading/.venv/python.-m#ipykernel_launcher'(interpreterId='~/github/trading/algotrading/.venv/bin/python') and valid interpreter ids include /Users/~/.pyenv/versions/3.10.4/bin/python, /Users/~/github/trading/algotrading/.venv/bin/python3, /usr/bin/python3
```

### Running Jupyter locally or remotely?

Local

**Comment by abhisheksoni27** [comment]
Any update on this @rebornix?

**Comment by abhisheksoni27** [comment]
Anyone, any updates? :)

**Comment by luabud** [comment]
Hi @abhisheksoni27, I'm not sure this is actually the problem, but given there's an error message related to the Python environment you're trying to use, maybe you can try creating a new virtual environment? It may be helpful to run the "Python: Create Environment" command and then select "venv". Then make sure to select this new environment by running the "Python: Select Interpreter" command before you open the interactive window.

**Comment by amunger** [comment]
It sounds like the `.ipynb support` built in extension isn't activating, you could search the extensions sidebar for `@builtin .ipynb` to confirm.

Can you open the dev tools after trying to open a notebook and check the console for any errors from activating that extension? (command `Developer: Open Developer tools`)
