### ISSUE TITLE
Add font zoom feature in Notebook.

### ISSUE THREAD

**Issue by whimian** [microsoft/vscode-jupyter#1584]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description

In vscode, 
the shortcut `Crtl + scroll` zooms font, 
but we cannot do font zoom within the notebook editor.

This request is the same as microsoft/vscode-python#8346 .
I resubmit this request because the old request microsoft/vscode-python#8346 is locked, and cannot be reopened.

The shortcut `Crtl + Shift + +` will zoom the window, not the font.

@rchiodo @jmew @DonJayamanne

**Comment by IanMatthewHuff** [comment]
Resolved by new notebook UI.
