### ISSUE TITLE
Retina plots should not render larger than non-retina plots

### ISSUE THREAD

**Issue by timmolendijk** [microsoft/vscode-jupyter#15845]
I ran into https://github.com/microsoft/vscode-jupyter/issues/3606, which was diagnosed as a wrapping issue.

But the actual issue reported there is that plots rendered with `figure_format = "retina"` should not render larger than the default `figure_format` plots to begin with. This is unresolved as of today and something that is a real problem because it means that I cannot have high-res plots without also having blown-up plots.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue.
When filing issues, please can you fill in the issue template that helps us help you.
E.g. version of VS Code, Jupyter extension, python version and steps to reproduce this issue.

I have tried the following and I see no difference,
Hence, please share a very sample code to replicate this issue (along with the details of vscode, jupyter, python version).

![Image](https://github.com/user-attachments/assets/cb51f001-90e0-45a8-bd75-8ab0d43d1e43)

**Comment by timmolendijk** [comment]
I’m sorry for being sloppy in my reporting.

## Environment

VS code:
```
Version: 1.91.1 (Universal)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:07:54.982Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

Jupyter extension: v2024.6.0 running local server

Python extension: v2024.10.0 running venv

OS: macOS 14.5



## Expected behaviour

Screenshot as included in @DonJayamanne’s previous message.

## Actual behaviour

<img width="889" alt="Screenshot 2024-07-22 at 02 12 53" src="https://github.com/user-attachments/assets/4ba96aba-f03a-45ed-9643-ec477c8b9909">
<img width="897" alt="Screenshot 2024-07-22 at 02 13 13" src="https://github.com/user-attachments/assets/bc5c03e7-406b-4ba9-9414-ee7f8e0b5138">

**Comment by timmolendijk** [comment]
Are you sure that your plots remain equally sized even when making the notebook wider @DonJayamanne?

**Comment by DonJayamanne** [comment]
Yes, confirmed. (i.e. the plot sizes are still the same even if i were to resize the notebook editor or even vs code)

**Comment by DonJayamanne** [comment]
Please can you share your notebook, here's mine

[matplotlib_retina_issue15845.ipynb.zip](https://github.com/user-attachments/files/16449458/matplotlib_retina_issue15845.ipynb.zip)

**Comment by DonJayamanne** [comment]
I figured this out, I can now replicate this at my end.
My notebook presentation ws not set to use the one from Notebook Renderers extension, instead it was using the built-in version.

**Comment by DonJayamanne** [comment]
Closing as that should resolve the issue, let me know if it doesn't

**Comment by timmolendijk** [comment]
Installing the Notebook Renderer extension resolves the practical problem, thanks.

Although I do wonder how installing another extension is to be considered a proper fix to this issue? I mean, shouldn’t the `vscode-jupyter` extension be capable of supporting retina in and of itself?

**Comment by DonJayamanne** [comment]
The renderer extension gets installed automatically when you install Jupyter extension
You may have uninstalled it at some point

**Comment by timmolendijk** [comment]
Hmm. Okay. Not sure how or when that may have happened. But alright.
