### ISSUE TITLE
timestamp index in data viewer

### ISSUE THREAD

**Issue by wj-c** [microsoft/vscode-jupyter#1585]
In data viewer, when the index is Timestamp it always shows hour, minute and second. However, often times, we use timestamps of lower frequency (like Day) and it's not necessary to show 0 hour, 0 minute and 0 second.

Would it be possible not to show redundant part (hour, minute and second) when using low-frequency timestamps as index?
<img width="263" alt="批注 2019-09-22 220539" src="https://user-images.githubusercontent.com/35519780/65389168-99121a00-dd85-11e9-8d98-5cc460d0acd1.png">

**Comment by IanMatthewHuff** [comment]
Closing down as part of an old bug cleanup push as it has not been upvoted.
