### ISSUE TITLE
Test: builtin data viewer removal

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#15865]
Re #15864

- [x] anyOS: @DonJayamanne 

Complexity: 2

Authors: @rebornix 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2315865%0A%0A&assignees=rebornix)

---

**Setup**
* Install pre-release of Jupyter Extension

We removed the entry point for the builtin data viewer, but still kept all the code for it (which we plan to remove later in debt week). The open in data viewer button still shows up in the current webview based Variable View. Please help test if it works as expected, including but not limited to

- When click on the button, we present a modal dialog to suggest installing data viewer extensions. It should direct you to the extension search view
- Once Data Wrangler is installed, the button works as expected
- Same works fine in debugging

**Comment by DonJayamanne** [comment]
Too easy, work as expexted
