### ISSUE TITLE
Switching kernels using raw kernel doesn't actually switch

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1587]
1. Create two ipykernel ready enviroments
1. Open a notebook with the first
1. Save the notebook
1. Change to the second
1. Execute
1. Verify second env is being used (I used sys.executable)
1. Close notebook
1. Reopen
1. Execute

Second environment is not being used to run the notebook.

**Comment by greazer** [comment]
Please reopen if this is still a problem with the latest native notebook support
