### ISSUE TITLE
Data Wrangler extension - dataframe viewer not opening within VSCode

### ISSUE THREAD

**Issue by clementlefevre** [microsoft/vscode-jupyter#15877]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Hello,

Coming from https://github.com/microsoft/vscode-data-wrangler/issues/49#issuecomment-2237213617 :

When using VSCode with the python debugger (no notebook) :
- __when the Data Wrangler extension is enabled__ :  when right-clicking on a dataframe variable, neither the legacy Viewer nor the new Data Wrangler triggers the opening of a new Vscode tab with the dataframe content.
- __when the Data Wrangler extension is disabled__ :    when right-clicking on a dataframe variable, the legacy data viewer opens correctly.

The thing is the legacy data viewer is supposed to be deprecated by the next version of VSCode (v1.92).

How to reproduce :

- in a python file  in vscode :
```python
import pandas as pd
df = pd.read_csv(https://gist.githubusercontent.com/netj/8836201/raw/iris.csv")
df
```
- set a breakpoint at the last line.
- run the script via the VSCode python debugger.
- in the variable panel : _right-click on the df variable_->  "View Data in Data Viewer" : works if Data Wrangler is disabled, otherwise nothing happens.

```
----------------------------------------------------------------
VSCode
Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621
----------------------------------------------------------------
Data Wrangler v1.4.2
----------------------------------------------------------------
Jupyter v2024.6.0
```

### VS Code Version

1.91.1

### Jupyter Extension Version

2024.6.0

### Jupyter logs

```shell
Visual Studio Code (1.91.1, undefined, desktop)
Jupyter Extension Version: 2024.6.0.
Python Extension Version: 2024.10.0.
Pylance Extension Version: 2024.7.1.
Platform: win32 (x64).
```

### Language Extension Version (if applicable)

python microsoft extension v2024.10.0

### Running Jupyter locally or remotely?

Local

**Comment by Err1000** [comment]
_when the Data Wrangler extension is disabled : when right-clicking on a dataframe variable, the legacy data viewer opens correctly._

I've had the same issue until i tried a rollback of the Data Wrangler as well as the Jupyter Extension.

The following setup fixed it for me, and I now see the Data Wrangler instead of the legacy Data Viewer:

Jupyter Extension: Version v2024.5.0
Data Wrangler: Version 1.4.1

**Comment by clementlefevre** [comment]
Thanky you Alex, 
could you just please detail how you did proceed for the **rollback** of the 2 extensions Data Wrangler & Jupyter ? 
A - Just uninstall & reinstall both
B - Or revert to Data Wrangler: Version 1.4.1 & Jupyter Extension: Version v2024.5.0 as you just mentioned ? 

Thanks a lot in advance, CL.

**Comment by clementlefevre** [comment]
@Err1000,  you are a Star !
 
@amunger : any chance we get it cleared by the next release ?

Thanks and have a nice day.

**Comment by rebornix** [comment]
@clementlefevre can you please try the latest Insiders 1.92 and Jupyter prerelease, I just tested this and it's working as expected. Thanks in advance!

**Comment by Oli-Ross** [comment]
Still seeing this, both on the newest version and the ones @Err1000 suggested.

**Comment by amunger** [comment]
With the latest jupyter extension pre-release, can you attempt to open the Data viewer, and post the logs here from the output window (command: `Jupyter: Show Output`)

**Comment by amunger** [comment]
this was likely fixed, but please post the logs from `Jupyter: Show Output` if not.
