### ISSUE TITLE
Editing a large notebook file can result in lots of constant IO happening (bad for power and battery)

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1588]
Ian has partially addressed by doing a more manual debounce (https://github.com/microsoft/vscode-python/pull/12064), but we'll still write the entire file every time.

The only solution I see is to not write the entire file every time, but instead compute where changes have occurred and only write the changes to disk (especially since it writes on every update).

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
