### ISSUE TITLE
Filter variables in the Python code instead of filtering them in TS land

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#15881]
Today we fetch all variables from kernel and then filter then in TS.
The payload returned is very large in some cases, when debugging some code, I found that the code returned over 100 variables, and I could only see 12 variables in the UI.
The Json returned by Python code (kernel) too was very large.

If we filter on the Python side, we should be able to improve the perf as well.

Feel free to close this (as its not causing any issues)

**Comment by amunger** [comment]
I'm not seeing this behavior, and the only filtering I can find is in python.
Can you see if you have more variables than displayed if you run `%who_ls`?
all I have from running the following cell is ['a']

```
a = 1
%who_ls
```

**Comment by DonJayamanne** [comment]
Seems they are different code paths, I'm fairly certain I was referring to this code (can't recall)
I recall seeing some very large JSON being sent back.
If you have a look at the default values, we're hiding a lot of stuff `module;function;builtin_function_or_method;ABCMeta;type;ModelMetaclass`

```typescript
        const exclusionList = this.configService.getSettings(kernel.resourceUri).variableExplorerExclude
            ? this.configService.getSettings().variableExplorerExclude?.split(';')
            : [];
```

Looks like thats not read in the new variable provider, 
Guess not many are using that setting, hopefully we can remove that, just way too many of these settings.

I think we can close this issue as the old variable view is dead, and so is the code associated with that.

**Comment by amunger** [comment]
ah, I thought this was for the new variable view/provider. Sounds good
