### ISSUE TITLE
Constant reconnection to kernel connecting to local docker container kernel

### ISSUE THREAD

**Issue by vvuk** [microsoft/vscode-jupyter#15885]
Every 10-20s I'm getting a "Reconnecting to the kernel Python3 (ipykernel)" notification, and I'm unsure what's happening. This is different than #12775 -- I'm running notebook 7.2.1 for one, and for two it doesn't seem to be harmful; the kernel is still running, it's just the connection that drops.  Connection is to jupyterlab running inside docker, with a port forarded to localhost:10000.

## Environment data

-   VS Code version: 1.91.1 (just updated, happened in earlier as well)
-   Jupyter Extension version (available under the Extensions sidebar): v2024.6.0
-   Python Extension version (available under the Extensions sidebar): v2024.10.0
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: 3.11.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): docker; `quay.io/jupyter/pytorch-notebook:cuda12-latest` container
-   Jupyter server running: Remote

## Expected behaviour

.. no notification

## Actual behaviour

`Reconnecting to the kernel Python3 (ipykernel)` pops up every 15-20s.

## Steps to reproduce:

Unclear how to get into this state, but it's persistent. Happens upon restart of VS Code; happens if I shut down the kernel and even the container and restart it.

## Logs

I've turned on Jupyter logging set to `trace`. There's nothing in the logs --

```
...
21:40:06.862 [trace] Start cell 6 execution @ 1722055206862 (clear output)
21:40:06.862 [debug] Kernel acknowledged execution of cell 6 @ 1722055206862
21:40:06.866 [trace] Cell 6 completed in 0.004s (start: 1722055206862, end: 1722055206866)
21:40:06.867 [trace] Cell 6 executed successfully
```

is the last entry, when I last executed a cell. The message has been happening continuously since notebook load. The server logs are a stream of:

```
pytorch-notebook  | [I 2024-07-27 04:43:27.786 ServerApp] Restoring connection for 063f2b81-82e1-4182-8e5e-336e77a62d4f:4439969d-deab-449b-abe8-e85d1673f836

pytorch-notebook  | [I 2024-07-27 04:43:38.908 ServerApp] Starting buffering for 063f2b81-82e1-4182-8e5e-336e77a62d4f:4439969d-deab-449b-abe8-e85d1673f836
pytorch-notebook  | [I 2024-07-27 04:43:38.926 ServerApp] Connecting to kernel 063f2b81-82e1-4182-8e5e-336e77a62d4f.
pytorch-notebook  | [I 2024-07-27 04:43:38.926 ServerApp] Restoring connection for 063f2b81-82e1-4182-8e5e-336e77a62d4f:4439969d-deab-449b-abe8-e85d1673f836

pytorch-notebook  | [I 2024-07-27 04:43:50.046 ServerApp] Starting buffering for 063f2b81-82e1-4182-8e5e-336e77a62d4f:4439969d-deab-449b-abe8-e85d1673f836
pytorch-notebook  | [I 2024-07-27 04:43:50.066 ServerApp] Connecting to kernel 063f2b81-82e1-4182-8e5e-336e77a62d4f.
pytorch-notebook  | [I 2024-07-27 04:43:50.066 ServerApp] Restoring connection for 063f2b81-82e1-4182-8e5e-336e77a62d4f:4439969d-deab-449b-abe8-e85d1673f836
```

(extra spaces added by me) It looks like the connection is just being dropped?

**Comment by DonJayamanne** [comment]
Thank you for filing this issue and sorry you are running into this.
Based on the logs, the issue doesn't seem to be realted to VS Code itself.
It seems the websocket connection is dropping over time.
Please can you share the logs from `VS Code` developer tools (use the command `Toggle Developer Tools` and open the console window)

There might be some logs in there as well,
Optionally, please can you have a look at the `network` tab in the developer tools and see if there's something there that might give a clue to whats going on.
