### ISSUE TITLE
navigate through cells in interactive window 

### ISSUE THREAD

**Issue by ggrrll** [microsoft/vscode-jupyter#15884]
As far as I can see , there is no way at the moment to navigate through cells in interactive window -- at the moment, one has to do it by hand , clicking on 'delete' button of every cells

That would a very nice feature  to have, to clean up the interactive window, before exporting , without having to re run the notebook , pretty much like it happens already in a jupyter notebook -- arrows 🔽  / 🔼   + delete

(also, sometimes , we wanna maybe just show few cells / sections of the interactive script )

thanks

**Comment by amunger** [comment]
you can set a shortcut for `interactive.history.focus` to do this, though I should probably also just add a default keybinding.

**Comment by ggrrll** [comment]
nice! thanks a lot

**Comment by ggrrll** [comment]
(I figure out that I can delete outputs of previous cells with cmd+backspace )
