### ISSUE TITLE
Discrepancy in handling `set_next_input` payload.

### ISSUE THREAD

**Issue by xl0** [microsoft/vscode-jupyter#15886]
Test code:
```py
display("Hello, world!")

payload = dict(
    source="set_next_input",
    text="Hello there",
    replace=True,
    clear_output=False
)

get_ipython().payload_manager.write_payload(payload)
```

In Jupyter notebook and nbclassic, the outputs of the cell are cleared unless `clear_output=False` .
Code from nbclassic:
```js
        this.events.on('set_next_input.Notebook', function (event, data) {
            if (data.replace) {
                data.cell.set_text(data.text);
                if (data.clear_output !== false) {
                  // default (undefined) is true to preserve prior behavior
                  data.cell.clear_output();
                }
```

In vscode-jupyter, the outputs are not cleared. This is definitely low-impact, but would be nice to fix the discrepancy in behaviour.

**Comment by xl0** [comment]
Another thing I've noticed, when I repeatedly issue set_next_input for the next input, I only see it updated after the cell finishes executing.

![Peek 2024-07-28 03-30](https://github.com/user-attachments/assets/cc917d10-0b10-4eba-8bb1-49df7fc96a11)

 In Jupyter nbclassic, it updates live:
![Peek 2024-07-28 04-26](https://github.com/user-attachments/assets/94c89213-5201-4905-bc45-929662f3ca4b)

Would be great to get live updates in Jupyter Vscode.

**Comment by DonJayamanne** [comment]
Thank you for filling this issue
Does this issue exist in Jupyter lab as well?

**Comment by xl0** [comment]
Oh you are right, Lab has the same issue. I assumed that it would behave the same way as notebook 7, but alas, there is more inconsistency.

```py
display("Hello, world!")

payload = dict(
    source="set_next_input",
    text="print('Hello, world!')",
    replace=True,
    clear_output=True
)

get_ipython().payload_manager.write_payload(payload)
```

Vscode:
![image](https://github.com/user-attachments/assets/1e5f5e8c-5992-4e77-8977-81725941f13b)

Jupyter Notebook (7):
![image](https://github.com/user-attachments/assets/057fc30d-4827-45e3-819a-c4678b682270)

Jupyter Lab:
![image](https://github.com/user-attachments/assets/ade5d907-06f4-468e-97db-2657912f6677)

Jupyter nbclassic:
![image](https://github.com/user-attachments/assets/dcf2253b-0ec4-4a73-92e6-852bffcef2d6)

I'll raise this with Lab, see if they would like to fix it.

**Comment by xl0** [comment]
You are right, Lab has the same issue.  I'll raise it with them, and see if they would like to fix it, or keep it this way.

**Comment by DonJayamanne** [comment]
Closing this issue as this is how it behaves in Jupyter lab as well.
Given the fact that Jupyter lab is the latest implementation of Jupyter, I'm closing this issue as it behaves as expected.
If Jupyter lab changes to resolve this, then we can re-visit and fix this in VS Code, until then closing this.
