### ISSUE TITLE
Jupyter Notebook Kernel crash during asyncio execution - error message displays in previous cell ouput

### ISSUE THREAD

**Issue by rk-exxec** [microsoft/vscode-jupyter#15893]
Does this issue occur when all extensions are disabled?: No, Jupyter and Python need to be enabled for the code to run. But I did a bisect and cant identify an extension that would be responsible. The crash only occurs occasionally.

- VS Code Version: 1.91.1
- OS Version: Win 10 - 10.0.19045 Build 19045

![grafik](https://github.com/user-attachments/assets/dfb5b295-6d4b-48c8-a9ff-ccaaa3ba2f3a)

The second cell causes a kernel crash in the "fit" cell while executing asyncio futures.
The crash message shows in the previous cell "init" output, but only when "Execute all" is used. 

Steps to Reproduce:

1. Run two cells in a row with "Execute all"
2. the second cell causes a kernel crash
3. observe error message in first cell output

I wasn't able to create a minimal reproducible example, because the crash only happens in my specific case and not every time.
Here is the code for the crashing cell:

```py
def background(f):
    def wrapped(*args, **kwargs):
        return asyncio.get_event_loop().run_in_executor(None, f, *args, **kwargs)
    return wrapped

@background
def async_fun(file):
    try:
        # something that causes a kernel crash
    except Exception as e:
            print(str(e), traceback.format_exc())
            print(file)

futures = list()

sem = asyncio.Semaphore(4)
for file in sources:
    async with sem:
        futures.append(async_fun(file))

res = await asyncio.gather(*futures)
```

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
I'm unable to replicate this issue.
Here's the code I'm using to run in the second cell with async io and kernel crash.
I'll send a custom VSIX that will contain some additional logging, hopefully that will help.

```python
import asyncio


sources = ['']

def background(f):
    def wrapped(*args, **kwargs):
        return asyncio.get_event_loop().run_in_executor(None, f, *args, **kwargs)
    return wrapped

@background
def async_fun(file):
    try:
        # something that causes a kernel crash
        import IPython
        app = IPython.Application.instance()
        app.kernel.do_shutdown(True)
    except Exception as e:
        print(str(e), traceback.format_exc())
        print(file)

futures = list()

sem = asyncio.Semaphore(4)
for file in sources:
    async with sem:
        futures.append(async_fun(file))

res = await asyncio.gather(*futures)
```

**Comment by DonJayamanne** [comment]
@rk-exxec are you still running into this issue?

**Comment by DonJayamanne** [comment]
Are you still running into this issue?

**Comment by rk-exxec** [comment]
Hey, I'll try to see if my code still fails this way! I'll get back to you.

**Comment by rk-exxec** [comment]
I managed to reproduce it consistently with this code. 
Since my previous code used a lot of memory, I tried filling it and then crashed the kernel with your example.  

When executing this together with a second cell ("Run All" or "Execute Cell and Below"), the crash is displayed on the second cell.
If executed individually the crash shows correctly on the first cell.

```py
import asyncio
import traceback
import numpy as np
from time import sleep

sources = ['']

def background(f):
    def wrapped(*args, **kwargs):
        return asyncio.get_event_loop().run_in_executor(None, f, *args, **kwargs)
    return wrapped
big_arr_arr = []

@background
def async_fun(i):
    try:
        print(i)
        # fill memory
        big_arr = np.zeros(2147483648, dtype=np.uint8) # alloc 2 gb
        big_arr[-1] = 1
        print(big_arr.shape)
        big_arr_arr.append(big_arr)
    except Exception as e:
        print(str(e), traceback.format_exc())
        # when memory is full, crash kernel
        import IPython
        app = IPython.Application.instance()
        app.kernel.do_shutdown(True)
    finally:
        print(i, 'done')

futures = list()

sem = asyncio.Semaphore(8)
for i in range(20):
    async with sem:
        futures.append(async_fun(i))

res = await asyncio.gather(*futures)
``` 

```py
print("Hello World!")
```

**Comment by DonJayamanne** [comment]
> current cell or a previous cell. ", did that change or did I not notice this?

Than you for getting back

Possibly changed after this issue was reported
Given this is a technically challenging issue to resolve (identify exact cell that caused the crash), I’m closing your issue as won’t fix

**Comment by DonJayamanne** [comment]
Short I cannot do better, ie resolve it and provide better error message
