### ISSUE TITLE
Live share support with VS Code Custom editor

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1590]
I believe this has been turned off today.
Leaving in new issues to get this proritized.

@rchiodo Or is this meant to be done as part of the syncing multiple editors?

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
