### ISSUE TITLE
Feature Request: More easily handle changing the working directory

### ISSUE THREAD

**Issue by jnolis** [microsoft/vscode-jupyter#15904]
Often times when running notebooks the ideal working directory isn't the base folder. For instance, if you have VSCode open the folder of a repository, it may be the case that all of the code is in the `src` folder, and you want that as the notebook current directory.

_There does not seem to be a straightforward way to specify where the working directory is when launching a new Jupyter Interactive Window._

I think this would be fixed by having an option *"Create Interactive Window From Working Directory"* and then let the user specify the working directory

<img width="719" alt="Screenshot 2024-07-31 at 11 42 16 AM" src="https://github.com/user-attachments/assets/e6e1478e-52cd-4129-a3b1-ace57850f87f">

I think this is a valid feature to add because all of the current solutions have their own issues:

1. Within an existing window you can create a cell `%cd /path/to/working/dir%, but then you need to create that cell each time you open a new window
2. If you are working with a python script in the working directory you can add `# %%` as a line in the file and when you click "run cell" it will open the interactive window in the right working directory. But then you are polluting your code
3. You can hard code the working directory in the settings, but this doesn't seem easy to get to nor is it workspace specific

This feature would be helpful for my team (and probably others?) Thank you!!

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
