### ISSUE TITLE
 Can't paste into jupyter widget text cell (continued)

### ISSUE THREAD

**Issue by SimonHeybrock** [microsoft/vscode-jupyter#15908]
Opening this instead of the closed  #15154.

I have the same issue.

- Using latest vscode on Mac using the remote extension.
  - It *works* on my Linux (Ubuntu) machine (also using remote extension).
- Tried `ipywidgets` 8 as well as downgrading to 7, with no effect.

To answer the last question in the thread:

              ok, that's exactly what I see in the logs as well. 

Feels like a long shot, but can you open the developer tools and watch for any errors in the console when you try to paste into either of those fields: `Developer: Toggle Developer Tools`

_Originally posted by @amunger in https://github.com/microsoft/vscode-jupyter/issues/15154#issuecomment-1934607795_

I am not seeing any warnings or errors in the console when trying to paste. It works fine in the `HTML` widget:
```python
from IPython.display import HTML
HTML('<input type="text" placeholder="Enter your name" /><')
```

There is a warning when *creating* the widget (edit: but this seems unrelated --- if I create the widget differently the warning disappears, but pasting still does not work):

```python
Extension Host] warn 14:58:31.356: Jupyter Extension: Unable to find a cell that owns the model 2bf20d706afa42e6a725686c8326a9d7
```
<img width="905" alt="image" src="https://github.com/user-attachments/assets/1461d0c8-826d-4469-9b14-c836e8676784">

**Comment by amunger** [comment]
tracking through https://github.com/microsoft/vscode-jupyter/issues/15787
