### ISSUE TITLE
Support Python 2.7 notebook kernels

### ISSUE THREAD

**Issue by lixin6135** [microsoft/vscode-jupyter#1592]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur
1. It said below after I updated to the newest vscode.

'Failed to connect to Jupyter notebook. 
http://localhost:8888/
Error: Kernel {0} is not usable. Check the Jupyter output tab for more information.'

![Peek 2020-03-30 11-03](https://user-images.githubusercontent.com/7124000/77928244-2b840080-7276-11ea-9f29-ab5d48e6da3e.gif)

### Your Jupyter and/or Python environment
I am using version 1.43 under Ubuntu 18.04. anaconda version is version 1.7.2

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by rchiodo** [comment]
Closing as we have no plans to support 2.7
