### ISSUE TITLE
(Feature Request) Line Numbers - All Cells

### ISSUE THREAD

**Issue by umdstu** [microsoft/vscode-jupyter#1593]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description
Allow line numbers to be toggled in ALL cells. Current behavior only allows a single (selected) cell to have line numbers be toggled via `L`.

Thanks

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by ecorro** [comment]
It looks like in Vs Code insiders, the option to toggle line numbers on/off does not work. Could you consider this feature for this product?

**Comment by rchiodo** [comment]
For insiders it isn't actually the jupyter extension that would be responsible for the line numbers. Instead VS code has to implement it. See these two requests:

#microsoft/vscode#106054
#microsoft/vscode#114294

**Comment by Rubix982** [comment]
Any updates on this?

**Comment by rchiodo** [comment]
@Rubix982 you should check the VS code issues. We're unlikely to implement this in the older UI.

**Comment by greazer** [comment]
Being tracked in issue #1659
