### ISSUE TITLE
The pop-up docs is not escaped correctly

### ISSUE THREAD

**Issue by GF-Huang** [microsoft/vscode-jupyter#15939]
## Environment data

-   VS Code version: 
```
版本: 1.92.1 (user setup)
提交: eaa41d57266683296de7d118f574d0c2652e1fc4
日期: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```
-   Jupyter Extension version (available under the Extensions sidebar): `v2024.7.0`
-   Python Extension version (available under the Extensions sidebar): `v2024.12.3`
-   OS (Windows | Mac | Linux distro) and version: `Windows 11 23H2 x64 10.0.22631`
-   Python and/or Anaconda version: `3.11.9 miniconda`
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): `miniconda`
-   Jupyter server running: `Local`

## Expected behaviour
Don't show `&nbsp;`.

## Actual behaviour
![image](https://github.com/user-attachments/assets/7b4ee2a5-1013-40e0-ae49-119ac2891466)

**Comment by DonJayamanne** [comment]
I'm sorry I missed this issue,
I'm unable to repro this in the latest versions of the Jupyter and Pylance extension.
Please can you update to the latest versions and try again.
If this problem still persists, please ping here and I'll re-open this or feel free to create a new issue.
