### ISSUE TITLE
Cannot cancel search procedure

### ISSUE THREAD

**Issue by senicram** [microsoft/vscode-jupyter#15933]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Searching in all files in project stucked. I cannot cancel it.

Reproduce:
1. Ctrl+Shift+F
2. Search not existing word in all projects
3. Searching will stuck and cannot cancel it.
4. Jupyter notebook is grey
5. The only solution, restart Visual Studo Code

### VS Code Version

1.92.0

### Jupyter Extension Version

2024.7.0

### Running Jupyter locally or remotely?

Local

**Comment by andreamah** [comment]
Do you have `search.experimental.closedNotebookRichContentResults` enabled?

If you do the following, what do you get?

1. Run `Developer: Set Log Level`  in the command palette and set `Trace`.
2. Do a search using your above steps.
3. In the bottom panel, check logs in the `Extension Host` channel in the `Outputs` tab.

**Comment by andreamah** [comment]
You just need to open the command palette and select the 'Run Developer: Set Log Level' item.

See https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette on opening the command palette.
