### ISSUE TITLE
Jupyter Notebook Server crashed or cannot connect

### ISSUE THREAD

**Issue by sharoncxu** [microsoft/vscode-jupyter#1594]
## Environment data

- VS Code version: 1.42.1
- Extension version (available under the Extensions sidebar): Python 2020.2.64397
- OS and version: Windows 10 Build 18362.207
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.4
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

## Expected behaviour

Running like a regular cell

## Actual behaviour
![image](https://user-images.githubusercontent.com/17832870/75119868-d17b9400-5654-11ea-8bca-ef40ff4c5e68.png)
![image](https://user-images.githubusercontent.com/17832870/75119876-e0fadd00-5654-11ea-9c54-38832483e576.png)

**Comment by greazer** [comment]
Closing due to age. Many things have changed and been fixed since this bug was entered.
