### ISSUE TITLE
NOT GETTING KERNEL

### ISSUE THREAD

**Issue by Vijaykrishna-vk** [microsoft/vscode-jupyter#15951]
Type: <b>Feature Request</b>

UNABLE TO FIND THE KERNEL SOURCE FOR NOTEBOOK FILES

Extension version: 2024.7.0
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by DonJayamanne** [comment]
Please can you share more information
What do you mean by ‘not getting kernel’
Can you share steps to repro this issue and any  errors from the logs from the ‘Jupyter’ output panel
