### ISSUE TITLE
Variable rename takes way too long in Jupyter notebooks

### ISSUE THREAD

**Issue by umarbutler** [microsoft/vscode-jupyter#15957]
It takes way too long to rename a variable in a Jupyter notebook despite the fact that, AFAIK, it is not even possible to reference variables defined in Jupyter notebooks from other scripts.

**Comment by DonJayamanne** [comment]
Sorry you are running into this, please can you fill in the issue template so we can help you with this issue.
Also are you using Pylance extension?
