### ISSUE TITLE
Crashing Jupyter kernel

### ISSUE THREAD

**Issue by ancepsinfans** [microsoft/vscode-jupyter#15955]
Type: <b>Bug</b>

Running my Jupyter notebook, and no matter what kind of code is running, within 5 minutes, the kernel crashes and needs to be restarted.

Extension version: 2024.7.0
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|8, 7, 7|
|Memory (System)|16.00GB (7.02GB free)|
|Process Argv|--crash-reporter-id 3920b3b0-6fce-4f3c-a37c-27e692fe28a5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-c:31111717
fje88620:31121564

```

</details>

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `trace`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).

Crashing kennels is always an issue with the python environment and not the Jupyter extension, basically Jupyter extension just sends code for execution to Jupyter kernels , and Jupyter extension doesn’t do anything beyond that

Please can you install Jupyter lab and try this outside vscode please share the terminal logs when running in terminal, when the kernel crashes there will be some information as to why it crashed

Or create a new python environment using conda (or the like)
From what we’ve seen crashes are a result of incorrectly installed packages

Try running just ‘print(1234)’ for over 5 minutes, if that crashes it’s not Jupiter extension, again try reinstalling installing python
