### ISSUE TITLE
Notebook change events are not firing when changing a kernel

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#15965]
Does this issue occur when all extensions are disabled?: No, requires the Jupyter extension

- VS Code Version: Latest insiders
- OS Version: Windows 11

Steps to Reproduce:

1. Git clone https://github.com/rchiodo/test-notebook-change (example extension)
2. Build the extension
3. Git clone https://github.com/bokeh/tutorial
4. Setup a python environment with bokeh in it
5. Install the Jupyter extension and the Python extension
6. Launch the extension from step 1
7. Open the bokeh tutorial folder
8. Open one of the notebooks
10. Select a kernel and pick one that uses the bokeh environment
11. Notice the change output in the extension debug console
12. Open another notebook
13. Clear console output for debugging extension
14. Pick that kernel selected in the last notebook

Expected result:
Kernel change notification happens

Actual result:
No changes detected.

This seems to be causing this issue here:
https://github.com/microsoft/pylance-release/issues/5172

**Comment by karthiknadig** [comment]
This should be possible with the new API I am working on. This will have an API that can pass any Uri and get a python for it. We can discuss if that can fit here.

**Comment by rchiodo** [comment]
I disagree about putting this in the python extension (tracking kernel changes). Other extensions likely need to know when a kernel changes, regardless of whether or not the kernel is in a jupyter notebook, or in a different kind of notebook. Additionally, the python extension would only track changes to 'python' kernels. What if the user switches to a C# kernel? (and the C# kernel has the same issue with multiple kernels not causing a did change event).

The root cause of the problem is that onDidChangeNotebookDocument event doesn't fire unless the underlying text model changes. But jupyter notebooks are backed by more than one model - the file on disk, and the current kernel stored somewhere else (I assume in memento storage). I think the correct fix here is to fire the event when either changes.

**Comment by rchiodo** [comment]
I think we can make this a lot better with the fix I just proposed. `display_name` is saved in the ipynb file, so theoretically changing it should cause a kernel change event. 

```text
"metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
```

**Comment by DonJayamanne** [comment]
Closing as this PR was merged https://github.com/microsoft/vscode-jupyter/pull/15967
Will create a separate issue for a simpler API to get this information via Python Api
