### ISSUE TITLE
Unable to view DataFrame in VS Code

### ISSUE THREAD

**Issue by mekanavsharma** [microsoft/vscode-jupyter#15969]
## Environment data

-   VS Code version: 1.92.2 (user Setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2024.7.0
-   Python Extension version (available under the Extensions sidebar): 3.12.3
-   OS (Windows | Mac | Linux distro) and version: Windows 
-   Pandas version: 2.2.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | Local (On VS Code)

## Expected behaviour

Showed be able to view dataframe in new pop-up

## Actual behaviour

When attempting to view a DataFrame in Visual Studio Code using the Data Wrangler extension, I encounter the following error:
"Could not retrieve variable autos from the Jupyter extension. Please file an issue on the Data Wrangler GitHub repository."

FYI : 1 month ago I used to get popup.  But then I don't what changes were made and I am not getting this pop.

## Steps to reproduce:
I first reported this issue with Data Wrangler , after our discussion they suggested that the issue is at your end. Here is the link for our discussion.

https://github.com/microsoft/vscode-data-wrangler/issues/270

If you want further information from my end, do let me know.

**Comment by amunger** [comment]
relevant error 
![image](https://github.com/user-attachments/assets/601eb034-339a-4f39-ae12-2a4d06217f75)

looks like a permission issue between DW <-> Jupyter

**Comment by DonJayamanne** [comment]
Solution
* Select the command `Jupyter: Manage Access to Jupyter kernels` from the command palette
* From the quick pick that appears, select the `Data Wrangler` extension

> FYI : 1 month ago I used to get popup. But then I don't what changes were made and I am not getting this pop.

Yes, that was a prompt asking to allow the Data Wrangler extension to allow using this API.

If the above solution doesn't work, please feel feel to file a new issue or ping here
