### ISSUE TITLE
Notebook jittery when editing a large cell

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-jupyter#1596]
![bug](https://user-images.githubusercontent.com/15910920/84430854-4ff64480-abf8-11ea-90cb-16eff2a9fa07.gif)

note im not scrolling at all when i enter the cell, its auto scrolling

Edit: ok looks less jittery in the gif due to the low fps... but its very noticeable in real time

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
