### ISSUE TITLE
Onboard onto the latest zeromq-prebuilt changes

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-jupyter#15970]
After https://github.com/microsoft/vscode-zeromq/issues/30 is completed, I would like the Jupyter extension to ship with only the latest `@vscode/zeromq` if possible in order for the extension to become compliant with internal Microsoft policies.

**Comment by DonJayamanne** [comment]
@rzhao271 Looks like the build outputs have changed.
In the past we used to get `node.napi.glibc.node`, now the build generates `zeromq.glibc.node`
Have a look at the contents in the artifacts of the zip files in the last two relases.
The latest release ....16.11 is built from your changes, and the previous ...16.10 is the old stable build.

**Comment by rzhao271** [comment]
I confirm that we renamed some of the output files while bumping to 16.11, ref PR [microsoft/zeromq-prebuilt#32](https://github.com/microsoft/zeromq-prebuilt/pull/32/files#diff-de673cd1b2aebbfb0fdca507f33b2c47b01626b2c093e6467690b651531dc647R50).

Adding Deepak to this issue.

**Comment by DonJayamanne** [comment]
> Do we want to keep the new file names (such as zeromq.glibc.node) or revert them (so they return to node.napi.glibc.node)?

Please revert, as 3rd party packages (that we use) rely on the older names.
Else it required changes upstream to packages like https://www.npmjs.com/package/@aminya/node-gyp-build & https://github.com/zeromq/zeromq.js/

Basically this name is imposed by the packages we depend on,

**Comment by DonJayamanne** [comment]
@rzhao271 thanks for identifying the problem, didn't realize it was a change made a while ago.

**Comment by deepak1556** [comment]
The change comes from the `prebuildify` version that upstream uses which ends up deciding the final name of the binaries, specifically https://github.com/prebuild/prebuildify/commit/7b6dcbd0860a82db8804079ba55663affd9ae555

We can preserve the older names by having a rename task in our CI.

**Comment by DonJayamanne** [comment]
Got it, thanks for the details @deepak1556 
Will make these changes during debt week.

**Comment by rzhao271** [comment]
@DonJayamanne I published `@vscode/zeromq@0.2.3`, which preserves the older names. Could you try onboarding again?

**Comment by DonJayamanne** [comment]
Changes have been merged
