### ISSUE TITLE
Interactive Window in a Separate Window Does Not Include Text Box

### ISSUE THREAD

**Issue by aleewen** [microsoft/vscode-jupyter#15985]
When the Interactive Window is in the main VS Code window, it shows the text box at the bottom to be able to write and run things:
![Screenshot from 2024-09-02 10-10-51](https://github.com/user-attachments/assets/85677d09-c225-422c-9c46-6c584168a8ec)

However, if the Interactive Window is moved into a separate window (i.e. Right Click -> Move into New Window) then the text box at the bottom disappears:
![Screenshot from 2024-09-02 10-10-24](https://github.com/user-attachments/assets/3070be20-3c0b-4cd5-bea6-c2b6498c524f)

It would be ideal to be able to run and test code in the Interactive Window on a separate screen.

**Comment by amunger** [comment]
It looks like the Interactive window editor isn't loading correctly, this works fine on my machine.
Can you open dev tools (`Developer: Toggle Developer Tools`) and check the console output for any errors that could be related.

**Comment by aleewen** [comment]
Hi, sorry I didn't see the notification and forgot to check here.
This is the console output. It doesn't look like there are any errors here.
I'm also on Ubuntu.

![Image](https://github.com/user-attachments/assets/52d07d93-e76d-4141-8ccf-e6e0ef72eb9f)
