### ISSUE TITLE
Incorrect line numbers in Python interactive window while showing the error(s) 

### ISSUE THREAD

**Issue by hyderkh** [microsoft/vscode-jupyter#1598]
Issue Type: <b>Bug</b>

The code line # and the traceback line numbers for ValueError do not match in Python interactive window.

Step to reproduce:
1. Execute below script
2. Check the ValueError in python interactive window
3. In code number_of_frames = int(sys.argv[1]) is at line#34, but in interactive window shows error at line#30

## Start of script
""" RollDieDynamic.py """
"""Dynamically graphing frequencies of die rolls."""

import matplotlib.pyplot as plt
from matplotlib import animation
import numpy as np
import seaborn as sns
import random
import sys

def update(frame_number, rolls, faces, frequencies):
    """Configures bar plot contents for each animation frame."""
    """ roll die and update frequencies """
    for i in range(rolls):
        frequencies[random.randrange(1,7) -1 ] += 1
    
    """ reconfigure plot for updated die frequencies """
    plt.cla() # clear old contents of figure
    axes = sns.barplot(x=faces, y=frequencies, palette='bright')
    axes.set_title(f'Die Frequncies for {sum(frequencies):,} Rolls')
    axes.set(xlabel='Die Value', ylabel='Frequency')
    axes.set_ylim(top=max(frequencies) * 1.10)

    """ display frequncy & percentage ablive each patch (bar) """
    for bar, frequency in zip(axes.patches, frequencies):
        text_x = bar.get_x() + bar.get_width() / 2
        text_y = bar.get_height()
        text = f'{frequency:,}\n{frequency/sum(frequencies):.3%}'
        axes.text(text_x, text_y, text, ha='center', va='bottom')
    

"""read command line arguments for the number of frames and rolls per frame"""
number_of_frames = int(sys.argv[1])
rolls_per_frame = int(sys.argv[2])

sns.set_style('whitegrid')
figure = plt.figure('Rolling a Six-sided Die')
values = list(range(1,7))
frequencies = [0] * 6

""" configure and start the animation that calls function update """
die_animation = animation.FuncAnimation(
    figure, update, repeat = False, frames=number_of_frames, intervals=33,
    fargs=(rolls_per_frame, values, frequencies))

plt.show() # display window

## End of Script

Extension version: 2020.5.80290
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

<img width="1107" alt="Screen Shot 2020-06-02 at 8 55 09 PM" src="https://user-images.githubusercontent.com/65697702/83584520-62e08900-a515-11ea-8603-c85fce7e40c2.png">

**Comment by greazer** [comment]
Looks like this is working in the latest bits. 
![image](https://user-images.githubusercontent.com/11685408/120931877-4d61ea00-c6a8-11eb-9f44-26a5c57fca73.png)
