### ISSUE TITLE
notebook becomes unresponsive, the kernel dies, and unable to save

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#16003]
Originally from Louis M on marketplace

> So many times the notebook becomes unresponsive, the kernel dies without any reason, the notebook won't save on disk and so many other pains. Using vanilla jupyter in browser is so much more reliable...

**Comment by DonJayamanne** [comment]
Please provide the information required to replicate this issue
Or please provide a minimal notebook with the code that causes this issue along with the version of Python and OS used.
