### ISSUE TITLE
 When I connect to the remote server using VSCode, in the ipynb files, I am unable to select a kernel as it does not show up.

### ISSUE THREAD

**Issue by hlshen-coder** [microsoft/vscode-jupyter#16005]
## Environment data

-   VS Code version: 1.85.2
-   Jupyter Extension version (available under the Extensions sidebar):v2024.8.2024081201
-   Python Extension version (available under the Extensions sidebar): v2024.14.0
-   OS (Windows | Mac | Linux distro) and version: ubuntu18.04
-   Python and/or Anaconda version: 3.7.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda 
-   Jupyter server running: Local | Remote | Remote

## Actual behaviour

the kernel selection for Jupyter Notebook keeps getting stuck.

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `trace`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).

**Comment by DonJayamanne** [comment]
Closing as information was required wasn't provided.
If this is still an issue. please provide the above logs and ping here or feel free to create a new issue
