### ISSUE TITLE
interactiveWindow.executeWithShiftEnter not work

### ISSUE THREAD

**Issue by TuRan-sino** [microsoft/vscode-jupyter#16020]
## Environment data

-   VS Code version: 1.93.0
-   Jupyter Extension version (available under the Extensions sidebar): v2024.8.0
-   Python Extension version (available under the Extensions sidebar): v2024.14.0
-   OS (Windows | Mac | Linux distro) and version: windows 11
-   Python and/or Anaconda version: python 3.11
-   Type of virtual environment used conda
-   Jupyter server running: Remote

## Expected behaviour

Enable `interactiveWindow.executeWithShiftEnter = true`, so that I can type `shift+enter` in interactive window to run python code

## Actual behaviour
But, after I enable `interactiveWindow.executeWithShiftEnter = true`, type `shift+enter` will take no effect, event if `enter` and `ctrl+enter`

**Comment by amunger** [comment]
duplicate https://github.com/microsoft/vscode-jupyter/issues/16010
