### ISSUE TITLE
Cannot use %load loading python files in Jupyter Notebook editor

### ISSUE THREAD

**Issue by yoctta** [microsoft/vscode-jupyter#1602]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1.  
![ezgif-1-eae9022a5800](https://user-images.githubusercontent.com/17178935/82904904-b42ccd80-9f95-11ea-8cf5-399d4b0df0f9.gif)

## Actual behavior

running [%load sample.py]  in a cell could failed to load python file.
The content in the cell didn't change and on bugs are reported.

## Expected behavior

It can run well in browsers , lines of sample.py will be appended in the cell. 

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:**  Remote 
-   **Extension version:** 2020.5.80290
-   **VS Code version:** 1.45
-   **Setting python.jediEnabled:** true 
-   **Python and/or Anaconda version:** 3.6.7
-   **OS:** Windows | Mac | Linux (distro): Ubuntu Server 16.04
-   **Virtual environment:** conda

## Developer Tools Console Output

Extension Host] Info Python Extension: 2020-05-26 20:39:04: Finished waiting for idle on (kernel): cf5ac630-6175-4c22-9cfb-e3679088198d -> idle
console.ts:137 [Extension Host] Info Python Extension: 2020-05-26 20:39:18: Executing cell NotebookImport#2
console.ts:137 [Extension Host] Info Python Extension: 2020-05-26 20:39:18: Submitting code for a99c91cd-361c-4c77-a74f-cf9b6d1b3e9d
console.ts:137 [Extension Host] Info Python Extension: 2020-05-26 20:39:18: Kernel switching to busy
console.ts:137 [Extension Host] Info Python Extension: 2020-05-26 20:39:18: Kernel switching to idle
console.ts:137 [Extension Host] Info Python Extension: 2020-05-26 20:39:18: Finished execution for NotebookImport#2
console.ts:137 [Extension Host] Info Python Extension: 2020-05-26 20:39:18: Finished executing cell NotebookImport#2

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by IanMatthewHuff** [comment]
Fixed for VSCode-Insiders native notebooks only as part of set_next_input work in #4566

**Comment by rchiodo** [comment]
Is this behind an experiment? Doesn't work for me with old webview. Trying native now.

**Comment by rchiodo** [comment]
Oh I believe you mentioned it was native only. Validated.
