### ISSUE TITLE
Feature Request: UI to Edit Notebook metadata 

### ISSUE THREAD

**Issue by winnieXY** [microsoft/vscode-jupyter#16036]
Please add a feature so that I can easily modify the notebook metadata and add additional information therre for parsers.

I use this feature currently (via spyder and spyder-notebook) but it would be super useful if it would be possible to edit the notebook metadata via vscode. Currently the only option (which i found) using vscode is to open the notebook as json and edit the metadata there.

**Comment by DonJayamanne** [comment]
Thank you for filing this feature request, however given the fact taht there haven't been sufficient upvotes on this issue, I'm closing this as not planned.

**Comment by psychemedia** [comment]
I would also find this useful, eg when using `.ipynb` documents as source documents in a `quarto` publication process, where having YAML frontmatter in the first cell of a notebook clutters the notebook content.
