### ISSUE TITLE
Blank plots with plotly 5.24

### ISSUE THREAD

**Issue by DavidP2Z** [microsoft/vscode-jupyter#16037]
Type: <b>Bug</b>

Plotly 5.24 introduced a new series of traces and plotly.express figures for tiled maps. The trace names are scattermap, linemap etc, and the corresponding plotly.express figures are scatter_map, line_map etc. All of these produce blank figures when using the default "vscode" renderer. Switching to a different renderer eg "notebook" produces the correct result.  

Here's an example code snippet:

```
import plotly.express as px

df = px.data.carshare()
fig = px.scatter_map(df, lat="centroid_lat", lon="centroid_lon",     color="peak_hour", size="car_hours",
                  color_continuous_scale=px.colors.cyclical.IceFire, size_max=15)
fig.show()
```
This produces a blank figure and no error messages.

Changing the renderer fixes the problem.

```
fig.show(renderer="notebook")
```

A map with markers should now be displayed.

Extension version: 1.0.19
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Darwin x64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DonJayamanne** [comment]
Closing as a duplicate, verified that updating the renderer package fixes this issue.
