### ISSUE TITLE
Clicking "Run All" runs cell out of order

### ISSUE THREAD

**Issue by lewj85** [microsoft/vscode-jupyter#16033]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Clicking "Run All" at the top runs cell out of order. Same issue as #2316 which was closed without a solution.

I tried debugging this by adding cells via the "+Code" button at the top, vs via hovering at the bottom of a cell and clicking "+Code (Add Code Cell)", vs via "Shift+Enter" at the last cell to auto-create the next cell. No method was consistent or fixed this out-of-order cell execution bug.

Another interesting anomaly: when I tried deleting the problem cell/cells (the ones running out of order), it completely changed the order of the remaining cells, causing cells that originally ran in order to no longer run in order. Quite confusing and inconvenient. As with #2316 I had no issues running cells in order if I highlighted the top cell and quickly clicked "Shift+Enter+Enter+Enter...etc".

Some cells have large outputs and clicking "Clear All Outputs" fixed the issue one time, but it was not a consistent fix.

Sometimes I click "Shift+Enter+Enter+Enter..." and later switch to clicking "Run All", this sometimes triggers the issue but not always.

### VS Code Version

1.92.2

### Jupyter Extension Version

v2024.8.1

### Jupyter logs

```shell
I don't see a Jupyter Output panel anywhere, nor a Jupyter Show Output option.
```

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `trace`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).
