### ISSUE TITLE
Inconsistent font rendering in Markdown cells

### ISSUE THREAD

**Issue by dimitry-ishenko** [microsoft/vscode-jupyter#1604]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Reset all font settings to defaults.

2. Create new Notebook.

3. Enter the following text and observe it rendered in "monospace" font:

<img src="https://user-images.githubusercontent.com/2858291/81459858-d8a04180-916f-11ea-8bf7-1c3f376b83de.png" width="50%" />

4. Change editor font in the settings to your favorite mono-spaced font, eg:
`"editor.fontFamily": "'Courier'"`

5. The text inside code block does not change:
<img src="https://user-images.githubusercontent.com/2858291/81460149-79433100-9171-11ea-86e8-39e70f5c5604.png" width="50%" />

## Actual behavior

Text inside code block does not respect `editor.fontFamily` setting and is rendered in "monospace" font, whereas the rest of the text does change.

## Expected behavior

All text rendered with the new font.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** N/A
-   **Extension version:** v2020.4.76186
-   **VS Code version:** 1.45 and 1.46
-   **Setting python.jediEnabled:** false
-   **Python and/or Anaconda version:** python 3.8.2 (no anacondas here)
-   **OS:** Ubuntu 20.04 LTS
-   **Virtual environment:** N/A

## Developer Tools Console Output

:shrug: 

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by joyceerhl** [comment]
VS Code core renders markdown cells now so this issue should be resolved. Please open an issue at https://github.com/microsoft/vscode if this isn't working for you.
