### ISSUE TITLE
`%%Javascript IPython.notebook.save_notebook()` executing successfully but notebook is not saved

### ISSUE THREAD

**Issue by ar-siddiqui** [microsoft/vscode-jupyter#16044]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Running following cell, I expect the notebook to save

```%%javascript
IPython.notebook.save_notebook()
```

The cell is executing without error but notebook is not saved.

### VS Code Version

1.92.2

### Jupyter Extension Version

v2024.7.0

### Coding Language and Runtime Version

Python 3.12

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thank you for coming this issue
Unfortunately we do not support access to the ipnb notebook via the python code in this manner
