### ISSUE TITLE
Setting jupyter server URI via the "Python: Specify local or remote jupyter server connections" command ignores folder-level setting

### ISSUE THREAD

**Issue by syagev** [microsoft/vscode-jupyter#1605]
## Environment data

-   VS Code version: 1.44.2
-   Extension version (available under the Extensions sidebar): 2020.4.76186
-   OS and version: Win 10 18363
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv

## Expected behavior

After changing the jupyter server URI to "local" via the "Python: Specify local or remote jupyter server connections" command, reloading the window, and opening the "Interactive Window" - it should open with a local kernel **or** warn me that a different URI is specified in the folder's settings and that it will be the one actually in effect.

## Actual behavior

VSCode attempts to connect to the server specified in the **folder** settings (which remains unmodified).

## Steps to reproduce:

1. Create a workspace with more than one project
2. Set a remote jupyter server URI in the `settings.json` file of the folder to some remote server.
3. Use the "Python: Specify local or remote jupyter server connections" command and select "local"
4. Reload the window
5. The remote URI is in effect instead of local and the user is confused about why that's happening

**Comment by amunger** [comment]
Closing since this seems to behave as expected now, unless the new experiment is turned on, and I created https://github.com/microsoft/vscode-jupyter/issues/11111 for that scenario

**Comment by amunger** [comment]
and for the multi-root issue: https://github.com/microsoft/vscode-jupyter/issues/5185
