### ISSUE TITLE
Ability to detect kernel API permission errors

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode-jupyter#16074]
Hi there,

Currently the access errors are being localized, e.g., https://github.com/microsoft/vscode-jupyter/blob/main/src/standalone/api/kernels/kernel.ts#L287. This means that we don't have a reliable way to detect when issues with kernel execution are due to permission errors like this to display a more appropriate message.

It would be great if we could have a reliable method to detect this. Thanks!

Related: https://github.com/microsoft/vscode-data-wrangler/issues/270

**Comment by DonJayamanne** [comment]
# Solution
If the `name` property of the error is `vscode.jupyter.apiAccessRevoked` then this means the access to the API has been revoked.
