### ISSUE TITLE
Document version mismatch error when saving any modified notebook

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-jupyter#16076]
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. Disable auto-save
2. Create a new notebook
3. Add a cell
4. Save the notebook
5. :bug: Document version mismatch

### VS Code Version

1.94.0-insider

### Jupyter Extension Version

2024.9.2024092401

### Coding Language and Runtime Version

N/A

### Running Jupyter locally or remotely?

Local

**Comment by rebornix** [comment]
This should be fixed in next Insiders.

**Comment by amunger** [comment]
seems fixed now
