### ISSUE TITLE
Toggle text output as markdown

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#16080]
It would be nice to be able to toggle output as markdown preview - especially when I'm exploring nlp model outputs. The model outputs in markdown (but it comes back as plaintext), but it's really hard to read it so I have to copy it to a new md cell. Can we detect a way to render as markdown?

Current:
![image](https://github.com/user-attachments/assets/12c09710-40cc-4a80-b5e5-587ca5511333)

**Comment by amunger** [comment]
could you just use the `IPython.display` package?
![image](https://github.com/user-attachments/assets/c02a2fbe-6e4b-4e8e-a0b9-2e55d5b64e1e)

**Comment by amunger** [comment]
I think we just need to leave this to the kernel - if we get the mime type of text/markdown, we can use the markdown renderer
