### ISSUE TITLE
Jupyter debug problem with vscode

### ISSUE THREAD

**Issue by pomergranate** [microsoft/vscode-jupyter#16093]
## Environment data

-   VS Code version:  1.93.1
-   Jupyter Extension version (available under the Extensions sidebar):  v2024.8.1
-   Python Extension version (available under the Extensions sidebar):  v2024.14.1
-   OS (Windows | Mac | Linux distro) and version: Windows 11 22H2
-   Python version: python 3.9.19 
-   Anaconda version:  conda 24.7.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Stop , when confronted with the breakpoint. 

## Actual behaviour

The program can not trigger a breakpoint, or to be exact can not run at all. 

## Steps to reproduce:

1. Create a test.ipynb file in the vscode
2. Write some codes in the cell as follows
```python
print('1')
print('2')
print('3')
print('4')
print('5')
print('6')
```
3. Set a breakpoint
4. Start ' Debug Cell ' and see it freezes. 

![bug](https://github.com/user-attachments/assets/62aaca03-6566-4d8d-bd29-772b90c86aef)

## Logs

<details>

<summary>
None
</summary>

<p>
</p>

</details>

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `trace`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).

**Comment by pomergranate** [comment]
@DonJayamanne Thank you for your responses. Here are the logs. 
[jupyter.log](https://github.com/user-attachments/files/17226815/jupyter.log)

**Comment by pomergranate** [comment]
@DonJayamanne 
I have searched for help on the internet for some time, and found one with a similar problem aroused by the 'typing' installation. However, the problem still remains even though I uninstalled it.

**Comment by DonJayamanne** [comment]
@pomergranate 
Thank you for filing this issue, looks like you had and old version of the Jupyter extension.
1. Please can you ensure you update your version Of Jupyter, Python and VS Code and test this again.
2. Also, please can you create a new conda environment and see if you still run into this issue.
3. Finally, can you confirm you are able to 
    * Run a cell without debugging
    * Debug regular python file in VS Code using the Python extension.
