### ISSUE TITLE
Clear cell output doesn't always work

### ISSUE THREAD

**Issue by JuanVargas** [microsoft/vscode-jupyter#16095]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

OS = Ubuntu 22.04.5 LTS
Julia = 1.10.5
VSC = 1.93.1

I like Julia and would like it to succeed, but I am very frustrated by bugs and issues that come along constantly when using Julia 
from an ipynb notebook under VSC.   The issue I am reporting here as new was supposed to have been fixed (issue 5446 is marked as closed) but the reality is that the issue has not been fixed.  Not sure if this is a VSC or a Julia problem.

Put it simply:  When I run a cell in Julia that is supposed to produce output via println(args), the output is shown immediately below the cell, but only the firs time the cell is run. If I select the  ...  button to "clear the cell output" , the output is cleared, and if I run the cell again,  the ... button is not shown, only the green check mark.  And once that happens, everytime I run the cell, the output is not shown. 

If I clear all the outputs and run again, the output is NOT shown 
![Screenshot from 2024-10-03 12-20-29](https://github.com/user-attachments/assets/1f053e76-e144-46ae-91a1-363d5699219c)

### VS Code Version

1.93.1

### Jupyter Extension Version

v2024.8.1

### Coding Language and Runtime Version

Julia 10.1.5

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `trace`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).
