### ISSUE TITLE
complex-valued numpy array displays as "[object object]" in data viewer

### ISSUE THREAD

**Issue by eseabean** [microsoft/vscode-jupyter#1610]
Issue Type: <b>Bug</b>

Create a jupyter notebook
import numpy as np
Create a complex-valued numpy ndarray like 
A = np.ones(2) + 1j * ones(2)
Show A in the data viewer
It seems data viewer  is loading, but the result never comes out

Extension version: 2020.4.74986
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (6.55GB free)|
|Process Argv|-psn_0_4240395|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IanMatthewHuff** [comment]
Dupe against #11680

**Comment by saidinesh75** [comment]
Has this issue been resolved? If yes, please let me know to solve it. I'm still facing the issue 

<img width="1555" alt="image" src="https://user-images.githubusercontent.com/32860784/216751525-b8537c57-1ec0-464d-86f7-a937a7fe356f.png">
