### ISSUE TITLE
Ability to add RAW text

### ISSUE THREAD

**Issue by vpankaj97** [microsoft/vscode-jupyter#1611]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description

Jupyter Notebook has a nifty feature where, instead of marking a cell as Code or Markdown, we can also mark it as RAW,  which is helpful many times.
 
One simple use case is, I tried to create a flow chart of sorts to visualize a flow of data.
This can't be done by commenting on a code cell AND using a markdown just squishes everything up.

It would be appreciated if RAW cells could also be supported.

On a side note, Spaces between the cells which are marked as Markdowns are way off, tend to be distanced quite a lot.

If I open then same .ipynb fike in nbviewer or jupyter notebook on chrome, the distance between the cells is way less.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by DonJayamanne** [comment]
This feature is supported today, you can create a cell and change the language to `raw`

**Comment by richardjharris** [comment]
Working on 1.67.2 / v2022.4.1021342353

You need to create a Code-type cell and then click 'Python' (or whatever) in the bottom-right corner of the cell. Or open command palette and find 'Notebook: Change Cell Language'.

**Comment by Grisly00** [comment]
Thanks for the reply, you are right. I was confused, since you can change to markdown via the 3-dot menu on top of a cell, but to change to raw you simply change the language. Should have read more carefully!

**Comment by joshjob42** [comment]
Is this a feature controlled on the kernel side or the VS Code Jupyter extension side? On the latest VS Code and extension, I can change cells to raw when using the Python 3 kernel, but not when using the latest Julia extension version and any current Julia version (either the current release or the release-candidate). The only options available with a Julia kernel are Markdown and Julia.

**Comment by rchiodo** [comment]
It's a function of the 'languages' that a kernel says it supports. We give back 'raw' here:

https://github.com/microsoft/vscode-jupyter/blob/2adefe9614c3e95234573ddfdbff4689b09e5859/src/notebooks/controllers/vscodeNotebookController.ts#L187

Here's our list:

https://github.com/microsoft/vscode-jupyter/blob/2adefe9614c3e95234573ddfdbff4689b09e5859/src/platform/common/constants.ts#L132

So the Julia extension has to support 'raw' in their list of languages for the Julia kernel.
