### ISSUE TITLE
Can't save file

### ISSUE THREAD

**Issue by AyomideA-S** [microsoft/vscode-jupyter#16121]
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I created a Jupyter notebook file (ipynb), and then I try writing code into the cells but then it just keeps saying this:
> Saving 'test.ipynb': Writing into file...

I then get this error message afterwards:
> Failed to save 'test.ipynb': Canceled

Then the extension restarts with this error message:
> The extension host terminated unexpectedly. Restarting...

### VS Code Version

1.94.2

### Jupyter Extension Version

2024.10.2024100401

### Jupyter logs

Visual Studio Code (1.94.2, undefined, desktop)
Jupyter Extension Version: 2024.10.2024100401.
Python Extension Version: 2024.16.1.
Pylance Extension Version: 2024.10.1.
Platform: win32 (x64).
Temp Storage folder ~\AppData\Roaming\Code\User\globalStorage\ms-toolsai.jupyter\version-2024.10.2024100401
Workspace folder ~\Desktop\Tech\Crypt, Home = c:\Users\...
00:33:55.136 [info] Starting Kernel (Python Path: ~\AppData\Local\Programs\Python\Python312\python.exe, Unknown, 3.12.6) for '~\Desktop\Tech\Crypt\test.ipynb' (disableUI=true)
00:34:00.560 [warn] Failed to get activated env vars for ~\AppData\Local\Programs\Python\Python312\python.exe in 5425ms
00:34:00.564 [warn] Failed to get activated env vars for ~\AppData\Local\Programs\Python\Python312\python.exe in 3910ms
00:34:00.618 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
00:34:00.820 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -m pip list
00:34:00.844 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
00:34:00.881 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.10.2024100401-win32-x64\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 18316
    > cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2024.10.2024100401-win32-x64\pythonFiles\vscode_datascience_helpers
00:34:02.347 [info] Process Execution: ~\AppData\Local\Programs\Python\Python312\python.exe -m ipykernel_launcher --f=c:\Users\~\AppData\Roaming\jupyter\runtime\kernel-v3e5eab095098d4880f9fb0005cdf42ee01710d102.json
    > cwd: ~\Desktop\Tech\Crypt

### Coding Language and Runtime Version

Python v3.12.6

### Language Extension Version (if applicable)

Python v2024.16.1

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
I'm not sure what's going on here. 
Is this on an SSH connection or just local?
Can you collect the "notebook" and "window" logs from the output panel as well?

**Comment by AyomideA-S** [comment]
It's a local connection...
Never mind, thanks for the help. I just disabled all extensions and figured that it's another extension that's causing the issue.

Again, I'm so sorry for taking your time.
Regards.
