### ISSUE TITLE
Jupyter Notebooks don't display attachments images

### ISSUE THREAD

**Issue by HAHAYAYAYA** [microsoft/vscode-jupyter#16128]
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Using the notebook in VS Code, all the images are broken.

Using the standard Jupyter notebook UI in the web browser renders all images.

### VS Code Version

Version: 1.94.2 (user setup) Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427 Date: 2024-10-09T16:08:44.566Z Electron: 30.5.1 ElectronBuildId: 10262041 Chromium: 124.0.6367.243 Node.js: 20.16.0 V8: 12.4.254.20-electron.0 OS: Windows_NT x64 10.0.22631

### Jupyter Extension Version

v2024.9.1

### Running Jupyter locally or remotely?

Local

**Comment by HAHAYAYAYA** [comment]
![Image](https://github.com/user-attachments/assets/623cf2aa-98dd-4ec5-b8e9-5130916c09b2)
![Image](https://github.com/user-attachments/assets/a09c20db-7c39-4e55-8394-1cb97851c75b)

**Comment by amunger** [comment]
How is the attachment being added?
If you view the file as text, do you see that .png name listed as an attachment? from the yellow line, it looks like it doesn't exist.
Can you share a notebook file that has this issue
