### ISSUE TITLE
Choosing kernel in interactive window doesn't make sense

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1612]
* Open python file
* Run some code in interactive window
* Get an error that moduel isn't installed
* Change kernel to pick a valid python install (conda environment)
* Run, all ok
* Close interactive window and run code again
* Back to square one.

Do users use this?
What's the point, shouldn't we disable this or change the current interpreter instead as the kernel isn't persisted.

**Comment by joyceerhl** [comment]
The active interpreter drives the interactive window kernel selection by design.
