### ISSUE TITLE
Cycling between code and raw cell modes is broken

### ISSUE THREAD

**Issue by sakshamsharma** [microsoft/vscode-jupyter#16122]
https://github.com/microsoft/vscode-jupyter/issues/1466
I went through this and a bunch of other rather old threads on raw cells, but cannot find any existing mention of this particular use-case.

It is addressed in all those tickets that raw cells are immensely useful, and they've been the single reason why I haven't been able to switch to vscode based jupyter notebooks despite trying every few months. At this moment I can do the following:
- Convert cells to raw using Cmd+Shift+P and "Change Cell Language".
- Map the above to a keyboard shortcut "R" which opens a pop-up which I then use to convert the cell to raw (probably need to add a good "when" condition for this too, this doesn't work well otherwise).

This is a start, but it still does not replicate the common workflow I (and from my discussions, many of my friends) follow.

This a four part request, some of which are bugs and others are feature requests:
- Could we support a keyboard shortcut to support switching language to "raw" similar to how there's one for switching to code or markdown? Jupyter uses "r" for this.
- Switching to raw using the drop-down does not instantly make it raw and make its output disappear. It just stays here until I press Shift+Enter to execute it. I suppose one could consider this a design choice but I'd like to add my two cents that the common case for making a cell raw is that you want it out of your way for the time being. I infact use raw cells half the time to just clear the output in a way.
- There's no indicator telling us it is a raw cell. I suppose some people might have a language-print on the lower right hand corner but that seems clunky and verbose at best. Jupyter does it well by removing the "[  ]" indicator from raw cells entirely. I think it's simple and effective.
- (bug) Raw cells can be converted to markdown with "m" shortcut, but not to code with "y" shortcut. I suppose one could adjust the "y" shortcut's "when" condition to resolve this (I haven't tried this) but I guess it should be fixed by default anyway.

Thanks, and happy to share any more information if required.

## Environment data
-   VS Code version: 1.94.2
-   Jupyter Extension version 2024.9.1
-   Python Extension version v2024.16.1
-   OS (Windows | Mac | Linux distro) and version: VSCode on Mac, SSH to linux.
-   Type of virtual environment used: Remote python kernel
-   Jupyter server running: Remote

**Comment by DonJayamanne** [comment]
@sakshamsharma Thank you for filing this issue.
In the future, please can you create separate issues so we can deal with them individually. else its difficult to manage a number of problems/feature requests in the same issue.

**Comment by DonJayamanne** [comment]
Closing this issue as I've created separate issues for each of the items. (items 1 & 4 are the same)
