### ISSUE TITLE
Change Default Scroll Behavior to Do Not Scroll

### ISSUE THREAD

**Issue by wmthor** [microsoft/vscode-jupyter#16130]
![Image](https://github.com/user-attachments/assets/5ea38a8f-d54f-4784-bcd6-6ce1901d6fcd)

## Description:
This PR proposes changing the default scroll behavior in the extension to match the independent code and output scrolling behavior to None/Do Not Scroll as from these scroll options [PR #193126](https://github.com/microsoft/vscode/pull/193126). This change will enhance usability, especially for users managing large outputs or errors.

### Improved Navigation and Debugging:
Large outputs or error messages often make it difficult to verify code execution quickly. Independent scrolling allows users to review outputs while keeping code in view, improving the debugging process and navigation.

### Better Usability for Large Text and Errors:
For users with larger text settings or long error messages, independent scrolling reduces the need for excessive navigation, making it easier to focus on both code and output.

### Familiar UX:
The independent scroll behavior **aligns with the Jupyter notebook default**, that has been widely tested . Keeping code and output scrollable separately reduces friction and creates consistency for users familiar with Jupyter’s default environment.

## Proposal:
After reviewing these improvements, [we](https://github.com/microsoft/vscode-jupyter/issues/13536#issuecomment-1561996110) propose setting the default scroll behavior to "None/Do not scroll." This removes the need for scrolling, keeping outputs fully visible without extra interaction. It smooths the transition for users familiar with Jupyter and is the likely the optimal choice for most users.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
