### ISSUE TITLE
shift/ctrl + enter adds new non-interactive cells with no cursor

### ISSUE THREAD

**Issue by AusafMo** [microsoft/vscode-jupyter#16136]
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

![Image](https://github.com/user-attachments/assets/ad25fa15-f164-4741-acd8-36d473c1ae2b)

Running the shell adds new cell but without the cursor, The new cells (happens multiple times in a row) completely non-interactive.
After restarting kernel or spamming shift+enter for a couple times, the cursor appears again.

### VS Code Version

1.94.2 (Universal)

### Jupyter Extension Version

v2024.9.1

### Coding Language and Runtime Version

python 3.12.7

### Language Extension Version (if applicable)

v2024.16.1

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
Is this happening consistently? Is there specific code in the cell that causes this to happen?
Are other cells behaving normally while this is happening?

**Comment by AusafMo** [comment]
> Is this happening consistently?

Yes, it is happening consistently, even on my colleagues machines, both of ours being macs if that helps.


> Is there specific code in the cell that causes this to happen?

I don't think its code specific, at least,  I didn't seem to recognise any patterns.


> Are other cells behaving normally while this is happening?

Yes, the existing cells behave normally, i.e., they do show cursors while the new one(s) don't.

**Comment by amunger** [comment]
Does it still occur in a new profile? run `Profiles: Create a Temporary Profile` and just install the jupyter extension

**Comment by AusafMo** [comment]
> Does it still occur in a new profile? run `Profiles: Create a Temporary Profile` and just install the jupyter extension

Yes, hard to reproduce consistently, but happens in new profile too.

**Comment by amunger** [comment]
Could you run `Developer: Toggle Developer tools` and check the console for any relevant errors?
Does this ever happen if you add a cell a different way, like with the toolbar or the `notebook.cell.insertCodeCellBelow` command?
If possible, could you also include a gif of the behavior?
