### ISSUE TITLE
Ability to run cells in section

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#16134]
Currently, there's the ability to run cells in the section using the Outline, but it would be convenient to also have that ability when I right click directly on the notebook cell.

**Comment by DonJayamanne** [comment]
@minsa110 which context menu are you referring to?
Menu you you click out side the cell text editor or inside the cell text editor?
See below
![Image](https://github.com/user-attachments/assets/1340ad21-6939-49ae-b0da-3dbeca797972)
![Image](https://github.com/user-attachments/assets/e5f3df8a-3f21-4a83-8bf2-91d69bffe7a2)
