### ISSUE TITLE
Copy cell output command not working correctly

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#16149]
> @amunger  Thanks for your reply.
> you mean this?
> ![Image](https://github.com/user-attachments/assets/4a5eb832-671b-4783-b4f4-861ce4a25d3c)
> 
> it is not working, for me
>  

 _Originally posted by @Shahin-rmz in [#15948](https://github.com/microsoft/vscode-jupyter/issues/15948#issuecomment-2438804883)_

**Comment by amunger** [comment]
@Shahin-rmz - yes, that command should work. Can you try without that when clause? You could try something like this for the when clause instead:
`notebookEditorFocused && !inputFocus`

The interactive window history is a notebook, so that should work.

If it's still not working you can use `toggle keyboard shortcuts troubleshooting` to make sure that the command is actually being invoked.

**Comment by Shahin-rmz** [comment]
> The interactive window history is a notebook, so that should work.

Thanks for the solution. It works like a charm. 🥇 

Just a quick idea, it would be awesome if we could select and copy a chunk of output to be able to search it on the internet or whatever. 
Something like Vim `Visual mode` but in interactive window.
 
I am hardcore Vim user, and for my new work position I am using VS code and actually like it. 
But some small details (like what above said) is missing. 
Thanks, best

**Comment by Shahin-rmz** [comment]
![Image](https://github.com/user-attachments/assets/bde16b51-1dc3-4e94-81cf-2af2f3441b3d)
here is an example of it. in this case I just selected the error text.

`NameError: name 'pri' is not defined`

**Comment by amunger** [comment]
thanks for the feedback - I agree the notebook output sections are not very keyboard friendly at this point. 

One workaround would be to use the accessibility view when focused on the output (alt+f2), but I just realized that it's not yet enabled for the IW, https://github.com/microsoft/vscode/issues/232421. It should be soon though.
