### ISSUE TITLE
Interactive window doesn't start if docker-based jupyter is running on port 8888.

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-jupyter#1615]
# Bug: Notebook Editor, Interactive Window, Editor cells

Hello there, we have been experiencing problems with Jupyter on VSCode. We usually work with a local jupyter notebook in docker mapped to local port of Windows 8888. We then somehow realized that when you start a notebook through VSCode, a jupyter server is started on the same port. 
## Steps to cause the bug to occur

1. Deploy a Jupyter Docker container
`docker run -p 8888:8888 jupyter/scipy-notebook
`
2. Everything is fine. You have your Docker-based Jupyter!
3. Open a .ipynb through VSCode
4. VSCode should start a local Jupyter server based on the interpreter on VSCode on 127.0.0.1:8888 blocking access to the Docker one
## Actual behavior
According to @rchiodo on microsoft/vscode-python#8698, the port should be rolled to next port. But in this image you can see that we have two pids on 8888 (and different hostnames).
![image](https://user-images.githubusercontent.com/32867099/80521044-a54cfe00-898a-11ea-8e25-dd2b6797b743.png)

## Expected behavior
The port should be rolled to next port. Feedback on UI could be great! I think that in order to roll on next port for the VSCode Jupyter Server, ports listening on 0.0.0.0 should be also taken into account.

### Your Jupyter and/or Python environment
Jupyter on Python 3.7.5
_Please provide as much info as you readily know_

-   **Jupyter server running:** Local 
-   **Extension version:** 2020.4.76186
-   **VS Code version:** 1.44
-   **Python and/or Anaconda version:** 3.7.5
-   **OS:** Windows 
-   **Virtual environment:** N/A 

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by amunger** [comment]
This seems to be working correctly now after trying the original repro steps on my Windows machine. Let us know if you're still having issues

```
[I 13:26:44.506 NotebookApp] The port 8888 is already in use, trying another port.
[I 13:26:44.508 NotebookApp] Serving notebooks from local directory: c:\\src\\test\\2
[I 13:26:44.508 NotebookApp] Jupyter Notebook 6.4.10 is running at:
[I 13:26:44.508 NotebookApp] http://localhost:8889/?token=007fa36090440627b5674347705969c703320309f3d30350
```
