### ISSUE TITLE
No focus when entering a Jupyter Notebook tab

### ISSUE THREAD

**Issue by LucaMarconato** [microsoft/vscode-jupyter#1616]
# Bug: Notebook Editor, Interactive Window, Editor cells
## Steps to cause the bug to occur

1. Open a tab with a .ipynb file with some cells (Python extension must be installed)
2.  move a bit around: pressing `j` you select the next cell
3. now move the focus away from the tab and put it back in to the notebook tab, for instance press twice ```CMD+` ``` in macOS to show and hide the terminal. 
4. now you would expect to be able to interact with the notebook with the keyboard, for instance pressing `k` you would expect to select the cell above, but nothing happens
5. to restore the focus you have to click with the mouse in one cell

## Actual behavior
Once going away from a .ipynb tab and going back in the focus is lost and you have to use click with the mouse to restore the focus

## Expected behavior
Focus should be on the notebook, as what it happens with any source code tab.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local | Remote | N/A
-   **Extension version:** 2020.4.74986
-   **VS Code version:** March 2020 (version 1.44)
-   **Setting python.jediEnabled:** false
-   **Python and/or Anaconda version:** Python 3.7.6
-   **OS:** Mac 10.15.3
-   **Virtual environment:** conda

## Developer Tools Console Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by susamuru7** [comment]
If you use to Windows 10 you should try this ⊞ Win + Tab then you could use to → the key to Enter.

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
