### ISSUE TITLE
Duplicated completion items

### ISSUE THREAD

**Issue by heejaechang** [microsoft/vscode-jupyter#16173]
### Applies To

- [x] Notebooks (.ipynb files)
- [x] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?
![Image](https://github.com/user-attachments/assets/f52f0e56-bee9-4922-9584-96044666d71c)

repro steps

1. create a cell
2. type `import os`
4. run the cell
5. create a cell after the first cell
6. type `os.` <= completion here

repro for both `notebook` and `interactive window`

### VS Code Version

1.94.2

### Jupyter Extension Version

v2024.10.2024100401

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment]
@heejaechang I do not see any duplicates in the screenshot

**Comment by GF-Huang** [comment]
@rchiodo Is it fixed in `v2024.11.2`?

**Comment by rchiodo** [comment]
The fix for this wouldn't be in Pylance. It would be in the jupyter extension.

**Comment by GF-Huang** [comment]
I had tried the `Jupyter v2024.11.2024102401 (pre-release)`, issue still.

**Comment by rchiodo** [comment]
I'm using 2024.11.2024111901 and it doesn't seem to repro for me:

![Image](https://github.com/user-attachments/assets/8569c189-5d65-46e2-ac5d-f090fdc5fe8b)

**Comment by GF-Huang** [comment]
@rchiodo I found it depends on Python version, I can reproduce on `3.10.12`, could you try it?

**Comment by rchiodo** [comment]
You might be on VS code stable. I'm using VS code insiders. Jupyter may have updated their required VS code version so the latest only works on insiders.

I can repro with Python 3.10 too:

![Image](https://github.com/user-attachments/assets/5793984a-5267-4c6b-8c76-a77e74fa152d)


@DonJayamanne you may need something different based on the results returned from ipykernel. Older versions must have had different completions.

**Comment by DonJayamanne** [comment]
Steps to repro
* Install Python 3.10
* Install pylance
* Install the latest version of ipykernel
* Run a cell containing the text `import os`
* In the next cell type the text `os.path.abs` at this point we should get completions for `abspath` and there should be just one item, instead of two.

**Comment by DonJayamanne** [comment]
@rchiodo Found that the label `* abspath` is what was causing the issue, I.e. the prefix `*`
Hopefully the new fix should work.

**Comment by eleanorjboyd** [comment]
tried this- it worked correctly if I did it in 2 different cells, it doesn't work if its in the same cell as the import. Seems like the direct issue from the verification steps but wasn't sure if the other scenario was supposed to work

<img width="913" alt="Image" src="https://github.com/user-attachments/assets/6ead8ef8-d22a-404b-bede-3f721d1fe1db" />
<img width="915" alt="Image" src="https://github.com/user-attachments/assets/1032ff84-c2cf-4cad-b7e7-998dcb06a6a2" />

**Comment by eleanorjboyd** [comment]
nvm installed pykernel and I no longer see the duplicate. Thanks
