### ISSUE TITLE
Persist user input in `ipdb` prompt in notebooks

### ISSUE THREAD

**Issue by dafriedman97** [microsoft/vscode-jupyter#16183]
A common workflow for me is to import my own modules into a notebook and insert `import ipdb; ipdb.set_trace()` into those modules when I need to debug.

In Jupyterlab notebooks, that pulls up a window like this. Note that my input (`print(x)`) is shown before the output.

![Image](https://github.com/user-attachments/assets/522f3d3f-55de-481e-8939-6fe1dbb3e011)

Here's how the same looks in the Vscode version. Note that I've run `print(x)`, but once I execute that, my input disappears. Would it be possible to persist that input?

![Image](https://github.com/user-attachments/assets/07df6fc1-e728-4f88-8967-099798c0ee10)

**Comment by DonJayamanne** [comment]
Thank you for filing this issue.
Have you looked at debugging, instead of using `ipdb` https://code.visualstudio.com/docs/datascience/jupyter-notebooks#_debug-a-jupyter-notebook

**Comment by dafriedman97** [comment]
Thanks @DonJayamanne, I'll give that a shot.

**Comment by DonJayamanne** [comment]
Closing this issue as there are no plans to support ipdb, instead we woudl recommend users to use the rich and fully integrated debugger.
