### ISSUE TITLE
Treat Raw String Literals in Markdown Cells as Markdown

### ISSUE THREAD

**Issue by 0az** [microsoft/vscode-jupyter#1618]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description

Right now, it's possible to create markdown cells for the Interactive Window with Python multi-line string literals. However, this only works with standard multi-line string literals: raw string literals are treated as code.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

(While I'm here, is there an issue to follow for execution latency? I'm getting high (5s-20s) latency between Run Cell command issued and VSCode response. Sometimes the cell cursor will advance, sometimes it doesn't.)

**Comment by rebornix** [comment]
Not Interactive Window specific so removing IW label/assigness.

**Comment by rebornix** [comment]
It is IW related (writing markdown cell in python file)

**Comment by amunger** [comment]
Closing since there hasn't been much interest/votes for implementing this
