### ISSUE TITLE
Impossible to tell whether cell output has been collapsed

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1619]
Theres no way to tell whether a cell output has been collapsed or not, or if cell execution is just not working.

I.e. if you collapse output of a cell, there's no indicator to tell whether cell output has been collapsed.
Feels wrong, I spent a few minutes trying to debug this simple thing.

![Screen Shot 2020-03-17 at 12 38 58](https://user-images.githubusercontent.com/1948812/76895225-d47d3500-684c-11ea-8fe4-b75aa73f7e39.png)
![Screen Shot 2020-03-17 at 12 39 07](https://user-images.githubusercontent.com/1948812/76895226-d5ae6200-684c-11ea-8dfa-43c624f5c9d9.png)
![Screen Shot 2020-03-17 at 12 39 12](https://user-images.githubusercontent.com/1948812/76895228-d5ae6200-684c-11ea-92ba-bfdaf45ccbd4.png)
![Screen Shot 2020-03-17 at 12 39 21](https://user-images.githubusercontent.com/1948812/76895229-d5ae6200-684c-11ea-92b0-d3e5861d3043.png)

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
