### ISSUE TITLE
Ability to change / have an additional "Green Play" button to "Run Python File in Python Interactive".

### ISSUE THREAD

**Issue by andradefraga** [microsoft/vscode-jupyter#1620]
I would argue that only very seasoned developers can write reams of code without needing to validate their logic as they sketch out their functions / classes. Experienced developers at some point will want to ensure that their code is behaving as expected and will seek some kind of a confirmation. For this reason, I would prefer to reassign the green play button for running my modules in the Python Interactive Terminal (PIT) or for the VSCode Python team create an additional "green play like button" (maybe the fast forward button to show that you are getting more than play - in that the other existing PIT variables are also accessible). 

At the moment, I am aware that I can use the # %% directive to create code blocks that can then be run in the PIT with the mouse. Also, if I am part way through developing a function or a class, I can select multiple lines and using Shift + Enter, send the block for evaluation in the PIT. 

Users can define their own key-bindings - and I have indeed created my own CTRL + P CTRL + I to run the module in PIT, but it can get annoying if I am currently operating the mouse to then have to switch to the keyboard and perform the 3 key operations. Given I am new to VSCode, I do not want to override the native F5 key binding.

The big advantage of this way of developing is that I can make use of variables in the PIT and seek the immediate feedback to more easily arrive at the desired behaviour. I also believe this will help people moving over from Data Science platforms, such as Python using with Spyder, RStudio and MATLAB or new coders who will instinctively want to code this way.

I appreciate that some of these tasks can be achieved using break points or TDD, but I tend to use docstrings with the doctest.testmod directive - which again lends itself well to working in the PIT. Given the behaviour of many data science type IDE's, I can imagine this would be a useful feature and will help with your adoption in Data Science or with new developers.

Many thanks.

**Comment by rebornix** [comment]
Let's track this in https://github.com/microsoft/vscode-jupyter/issues/7683
