### ISSUE TITLE
Unable to choose python env

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#16202]
Originally from Timothée CLOUP on marketplace

> Cannot choose your python env. I have the same issue since since years.

**Comment by DonJayamanne** [comment]
Please can you share more information about the Python env you cannot select?
Its possible the Python env is not detected by the Python extension or the like.
Please share the following information
* Version of VS Code, Jupyter and Python extensions
* Is the Python env displayed in the quick pick used to select a Python environment when using the command `Python: Select Interpreter`
*
