### ISSUE TITLE
Kernel detection by jupyter not working with ms-python extension

### ISSUE THREAD

**Issue by Xharos** [microsoft/vscode-jupyter#16208]
## Environment data

-   VS Code version: 1.93.1
-   Jupyter Extension version : v2024.8.1
-   Python Extension version : v2024.18.0
-   OS and version: Linux 6.6.54-2-MANJARO
-   Python version: 3.12.6
-   Type of virtual environment used : venv
-   Jupyter server running: Local

## Expected behaviour

Select the python kernel from the jupyter select kernel button.

## Actual behaviour

I got an empty list :
![Image](https://github.com/user-attachments/assets/2f3cf376-7b1d-484b-9f65-d1c0f6f964a7)

## Steps to reproduce:

- Install ms-python from the marketplace
- Install jupyter from the marketplace
- Create a new project with a new .ipynb file
- ctrl+shift+p -> Python: Select interpreter -> Create virtual environment -> venv -> python 3.12.6 in /bin/python
- Inside the venv, pip install jupyter ipykernel
- Run command jupyter notebook

I am now able to open the ipynb file created earlier inside my browser and select the venv to run it :
![Image](https://github.com/user-attachments/assets/ac518b2e-38a5-4446-abea-db9a7e23cd30)

But i cannot select the venv in vs-code. It shows an empty list when clicking select kernel (see Actual behaviour).

Bug found, if from this step i disable/uninstall ms-python and restart vs-code, the venv kernel appears automatically :
![Image](https://github.com/user-attachments/assets/8ba9173b-dce0-4080-9301-8d16d02757f3)
I'm able to launch the cell inside vs-code without any error. But I want the ms-python extension for the code documentation. 

What can i do to have both extensions running without any bug ?
I've already look the tutorial on ms-python README file, section run with jupyter notebook. But it's not working for me.

Thanks in advance

**Comment by DonJayamanne** [comment]
Thank you for filling this issue, former I’m failing to infants the problem

> Bug found, if from this step i disable/uninstall ms-python and restart vs-code, the venv kernel appears automatically 👍🏾 

From what I gather this works now
Or does it still not work?

Also please update your version of vscode, Jupyter and python extensions (you do not have the latest versions installed)

**Comment by Xharos** [comment]
Thanks for this quick response.

It is indeed working (i can execute code in notebook inside vs-code) when ms-python is not installed.
But i would like it to be working with ms-python (to support documentation, completion, etc)

I doesn't know that i am not up to date.
I've performed a system upgrade (through pacman) because i have installed vs-code from manjaro package manager.
Same for the extensions (installed from the extensions tab) that seems up-to-date.

It seems in fact that pacman -S code is not the latest version (as shown in this community package https://aur.archlinux.org/packages/visual-studio-code-bin). I will try to install it to see if i can get newest version of the extensions.

**Comment by DonJayamanne** [comment]
> VS Code version: 1.93.1

You mentioned you have 1.93

> It seems in fact that pacman -S code is not the latest version (as shown in this community package https://aur.archlinux.org/packages/visual-studio-code-bin). 

The above link shows that 1.95 is the latest version

> Jupyter Extension version : v2024.8.1

The latest version is 2024.10.0

**Comment by Xharos** [comment]
I will try to install vs code from another source then. I cannot upgrade higher than 1.93.1 with the current package that i'm using.

I will try the aur package and see if i'm able to get more recent extension version.

**Comment by DonJayamanne** [comment]
Let me know how that goes
