### ISSUE TITLE
PIXI environments not "conda activated"

### ISSUE THREAD

**Issue by petrushy** [microsoft/vscode-jupyter#16228]
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

pixi can be used to set up environments, which are then used by vscode jupyter. 

It seems like these environments are seen like normal virtual-python environment and the specific conda-activation that is done for conda environments is not performed. It seems like vscode does not identify the pixi environments as conda environments.

### VS Code Version

1.95.3

### Jupyter Extension Version

v2024.11.2024102401 (pre-release)

### Jupyter logs

```shell

```

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Do these pixi environments work in regular python extension?

**Comment by petrushy** [comment]
Not sure i understand, the environment work and gets activated if ran from the console with pixi run juputer labVscode finds the env and uses that python binary but seems not to activate the conda activate scripts. On 18 Nov 2024, at 11:52, Don Jayamanne ***@***.***> wrote:﻿
Do these pixi environments work in regular python extension?

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `trace`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).
