### ISSUE TITLE
Native REPL output with unicode characters 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-jupyter#16222]
Type: <b>Bug</b>

# Behaviour

When printing strings with unicode characters, the Native REPL is not properly displaying them

## Steps to reproduce:

1. Run this in the Native REPL:
`x = "Oi tudo bem com você?"`
2. Then `print(x)`
Notice that it outputs `Oi tudo bem com vocÃª?`

# Diagnostic data

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

Extension version: 2024.18.1
VS Code version: Code - Insiders 1.96.0-insider (4a98be2738be4ad8647feb52d1e6845e06515dea, 2024-11-08T09:56:49.748Z)
OS version: Windows_NT x64 10.0.26100
Modes:

-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.7
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Default

<details>
<summary>User Settings</summary>
<p>

```

languageServer: "Pylance"

experiments
• optInto: ["All"]

```
</p>
</details>

<details>
<summary>Installed Extensions</summary>

|Extension Name|Extension Id|Version|
|---|---|---|
|.NET Install Tool|ms-dotnettools.vscode-dotnet-runtime|2.2.2|
|Catppuccin for VSCode|Catppuccin.catppuccin-vsc|3.15.2|
|Catppuccin Icons for VSCode|Catppuccin.catppuccin-vsc-icons|1.17.0|
|GitHub Copilot|GitHub.copilot|1.245.0|
|GitHub Copilot Chat|GitHub.copilot-chat|0.23.2024110806|
|JavaScript Debugger|ms-vscode.js-debug|1.95.2|
|JavaScript Debugger Companion Extension|ms-vscode.js-debug-companion|1.1.3|
|Jupyter|ms-toolsai.jupyter|2024.11.2024110701|
|Jupyter Cell Tags|ms-toolsai.vscode-jupyter-cell-tags|0.1.9|
|Jupyter Keymap|ms-toolsai.jupyter-keymap|1.1.2|
|Jupyter Notebook Renderers|ms-toolsai.jupyter-renderers|1.0.2024102901|
|Jupyter Slide Show|ms-toolsai.vscode-jupyter-slideshow|0.1.6|
|Prettier - Code formatter|esbenp.prettier-vscode|11.0.0|
|Pylance|ms-python.vscode-pylance|2024.11.100|
|Python|ms-python.python|2024.18.1|
|Python Debugger|ms-python.debugpy|2024.13.2024103001|
|Python Environment Manager|ms-python.vscode-python-envs|0.0.0|
|Ruff|charliermarsh.ruff|2024.54.0|
|Table Visualizer for JavaScript Profiles|ms-vscode.vscode-js-profile-table|1.0.10|
</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (12.48GB free)|
|Process Argv|--log trace --log ms-python.autopep8=debug|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aa:30263845
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
01bff139:31013167
dvdeprecation:31040973
dwnewjupyter:31046869
impr_priority:31057980
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
i21gd607:31141543
iacca1:31150324
notype1:31143044
dwcopilot:31158714
h409b430:31177054
390bf810:31176401

```

</details>

**Comment by amunger** [comment]
It actually displays the correct character in the interactive window, so it may be something in the message passing between the python extension and the running interpreter.
