### ISSUE TITLE
Jupyter notebooks after a while become very slow

### ISSUE THREAD

**Issue by drkg4b** [microsoft/vscode-jupyter#1622]
Bug: Execution of code in Jupyter mode (when using '#%%' to start a cell) after a while becomes painfully slow and laggy and require vscode restart to get back to normal speed. 

## Steps to cause the bug to occur

1. Just use the editor for a while

## Actual behavior

After running for a random amount of time, execution of commands is heavily lagged and require complete restart of the vscode editor

## Expected behavior

Smooth operation of the editor without lag or slower than necessary execution of commands.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local 
-   **Extension version:** 2020.3.71659
-   **VS Code version:** 1.43.2
-   **Setting python.jediEnabled:** false
-   **Python version:** 3.7.4
-   **OS:** Windows 10
-   **Virtual environment:** N/A/ sometimes venv.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by robertodawid** [comment]
Hi, I am running a basic example of plotnine in jupyter notebook in VSC. The code runs perfectly in jupyter-browser, however, VSC is slow and generates very very large file of 112MB.
The example is from
 https://datacarpentry.org/python-ecology-lesson/07-visualization-ggplot-python/index.html
What is happening?

**Comment by IanMatthewHuff** [comment]
@robertodawid This is a known issue. With our plot viewer support we create both png and svg versions of plot outputs, and the svg plot outputs of plotnine in particular can be very dense and large. The best way to avoid this right now would be to turn off the VS Code setting Juypter: Enable Plot Viewer. The clear the outputs from the notebook that you are working with. This should bring the file back to a more reasonable size.

**Comment by waterchinap** [comment]
May be I can add some more info for this issue:
ipynb format,
I use pandas and read a file about 1M rows(about 4 m in size) into a df, 
```
df.describe()
# this will take very long time, about 10 seconds..
```
it works fine in jupyter lab web app

**Comment by ShadyAbuKalam** [comment]
Loading a large UTF-8 text file (~160 MB), makes the next operations very slow (seems to block), even if it's as simple as function dentition.  
But it works great inside the web app.

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363
Python: 3.7.9

**Comment by deborahtrez** [comment]
![image](https://user-images.githubusercontent.com/28389950/125475507-276dda93-8957-48c9-97a3-9c631c1c8792.png)

I just installed Jupyter Notebook for VSCode on Mac 2020 M1, and tried to run this simple print command but it is running forever!! 
If I try to interrupt it, it will show "Interrupting Kernel" endlessly, but it will not end. It will remain like that forever. 

![image](https://user-images.githubusercontent.com/28389950/125475803-a6be2dab-837f-435f-b604-2e9df33888d1.png)

**Comment by salmanea** [comment]
I had the same problem. In the settings, I specifically assigned a 'local' server for Jupyter. It solved the problem. It used to be on 'default'.

**Comment by DonJayamanne** [comment]
@ShadyAbuKalam @salmanea Please could you install VS Code insiders and give this a test now.
We've made a lot of changes that would significantly improve the perf across the board (loading & execution).
Do let us know how this goes. 
FYI - you'll need vscode insiders, as the changes have been shipped yet (once you install vscode insiders, please ensure you have the latest jupyter extension installed as well)

**Comment by salmanea** [comment]
Just tested the insider version.
Seems like that Jupyter extension works much faster and lighter.
The variables are also shown much faster. The stable build struggles to update the variable list. Much slower than for example if you use Spyder IDE. So I think great job guys 👍

A quick side question: why are the variables are now shown down with the terminal and other stuff instead of the top of the interactive window? I think it's a much better idea to have them on the top.

**Comment by DonJayamanne** [comment]
> y are the variables are now shown down with the terminal and other stuff instead of the top of the

This is great feedback, please could you file a separate bug to discuss this.
This was done as part of the overall UI changes to the notebook. 

> hink it's a much better idea to have them on the top.

Agreed, but lets discuss this separately in a separate issue.

& thanks a lot for testing this & providing your feedback.

**Comment by DonJayamanne** [comment]
Closing this issue based on the comments from @salmanea

If anyone is still experiencing perf issues, please file a new issue or please feel free to re-open this issu.e
FYI - The latest version with the perf fixes will be made availabel today.
