### ISSUE TITLE
Intellisense doesn't recognize TextCalendar formatyear function

### ISSUE THREAD

**Issue by wyatt-wong** [microsoft/vscode-jupyter#16237]
### Applies To

- [ ] Notebooks (.ipynb files)
- [x] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The Intellisense was unable to detect the TextCalendar formatyear function

![Image](https://github.com/user-attachments/assets/54742ca0-fc2d-4fde-a4d0-e0e379e30040)

### VS Code Version

1.95.3

### Jupyter Extension Version

v2024.10.0

### Jupyter logs

```shell

```

### Coding Language and Runtime Version

Python v3.13.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
@wyatt-wong This works for me as expected.
Please can you confirm you have install the Pylance extensiokn, as thats what provides better completions.
![Image](https://github.com/user-attachments/assets/13bd2eda-9762-4e06-bc37-2d892d655a86)

**Comment by wyatt-wong** [comment]
> [@wyatt-wong](https://github.com/wyatt-wong) This works for me as expected. Please can you confirm you have install the Pylance extensiokn, as thats what provides better completions. ![Image](https://github.com/user-attachments/assets/13bd2eda-9762-4e06-bc37-2d892d655a86)

OK. I found that I uninstall Pylance extension. After re-install it, I found Intellisense was able to show the parameter list for formatyear function.
