### ISSUE TITLE
Multiple "pip install" commands in a single Jupyter cell occassionally failed when executing the second and subsequent "pip install" commands

### ISSUE THREAD

**Issue by wyatt-wong** [microsoft/vscode-jupyter#16239]
### Applies To

- [x] Notebooks (.ipynb files)
- [x] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Occasionally when multiple "pip install" commands were put into a single Jupyter notebook cell, ONLY the first "pip install" command can be successfully executed.

Subsequent "pip install" commands will failed to execute with error messages.

### VS Code Version

1.95.3

### Jupyter Extension Version

v2040.10.0

### Jupyter logs

```shell

```

### Coding Language and Runtime Version

Python v3.13.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Closing as this isn't something thats controlled by the Jupyter extsnion.
This is something thats handled by the Python kernel itself.
I.e. its an issue with IPyKernel package that handles these `shell` comments.
