### ISSUE TITLE
Make kernel and selection UI consistent

### ISSUE THREAD

**Issue by afeld** [microsoft/vscode-jupyter#16248]
I checked if there is an issue already; couldn't find one.

I teach [an introductory course on Python and data analysis](https://computing-in-context.afeld.me/). We recently went through how to work with [Python files](https://computing-in-context.afeld.me/lecture_23.html#create-python-file) and [notebooks](https://computing-in-context.afeld.me/lecture_23.html#create-notebook) in VSCode, and one of the steps is selecting the interpreter/kernel (respectively). It occurred to me that it's strange that they're in different places in the UI. Screenshots below.

I know they are _technically_ different things, but they are conceptually very similar, certainly for people working in Python (files and notebooks) exclusively.

**My proposal:** Move the kernel selection to the [Status Bar](https://code.visualstudio.com/docs/getstarted/userinterface#_basic-layout), same placement as the interpreter selection.

Thanks!

**Interpreter**

![Image](https://github.com/user-attachments/assets/0f62720c-463b-480c-876d-252da4d49f50)

**Kernel**

![Image](https://github.com/user-attachments/assets/d7ea9770-c08f-49e5-b0a6-c03faf9b58c3)

**Comment by vishalkrish-12** [comment]
@afeld I've experiencing this already, when it comes to kernel selection by using from "Python Environments" option the expected behavior is that it should list out the "Global Envs" and "Virtual envs or Conda envs".

What actually happens randomly the "Virtual envs or Conda envs" not showing up in the list so that I am not able to select the kernel, but previously it's working.

**Comment by afeld** [comment]
@vishalkrish-12 That seems like a bug; I suggest looking through [other open issues](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue%20state%3Aopen%20conda%20kernel%20label%3Abug) and potentially opening a new one. The scope of this feature request is specific to the placement of the `Select Kernel` button.

**Comment by DonJayamanne** [comment]
@vishalkrish-12 please file a separate issue for the problems you are experiencing, they aren't related to this issue.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, unfortunately the two are separate items and used extensively today by a large number of users to configure separately for multiple reasons. Changing this will be very challenging, and given the fact that we've had this UX for a while now, we have no plans on changing this any time.

Closing as out of scope.
