### ISSUE TITLE
Interactive Plotly Visuals Not Displaying in Jupyter Notebook (pyo.iplot Keeps Running)

### ISSUE THREAD

**Issue by JayDS22** [microsoft/vscode-jupyter#16247]
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

## Description

I'm trying to create an interactive Plotly visualization in a Jupyter Notebook. However, when I run the code below, the last cell keeps running indefinitely without producing any output or errors. 

## Code Snippet

```PYTHON
import numpy as np
import pandas as pd
%matplotlib inline
%matplotlib widget

import plotly.offline as pyo
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.graph_objects as go

# Initialize Plotly
pyo.init_notebook_mode(connected=True)

# Sample Plotly Scatter Plot
fig = go.Figure(data=go.Scatter(x=[1, 2, 3], y=[4, 5, 6]))
pyo.iplot(fig)
```

## Environment
Python Version: 3.9
Jupyter Notebook/Lab Version: Jupyter Notebook 6.4.5
Plotly Version: 5.17.0
Browser: Google Chrome 118.0.x

### VS Code Version

1.93.1

### Jupyter Extension Version

v2024.8.1

### Jupyter logs

```shell
The notebook cell runs indefinitely without displaying the plot or throwing any errors.
```

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, you seem to be using an old version of VS Code.
Please can you install the latest version of VS Code, Jupyter extension and the Notebook Renderers extensions.
I'm certain that should fix this issue.
