### ISSUE TITLE
Jupyter Server: Not Started No Kernel

### ISSUE THREAD

**Issue by DorotheaM** [microsoft/vscode-jupyter#1627]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

I've been trying to use jupyter notebook in vscode. I installed the python extension then clicked Python: Select Interpreter to start jupyter server and then I tried to create a notebook.

## Actual behavior
![Σχόλιο 2020-04-14 005945](https://user-images.githubusercontent.com/58270364/79167073-4a929e80-7def-11ea-9cb1-6f3febe100c3.png)

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local | Remote | N/A
-   **Extension version:** 2020.3.71659
-   **VS Code version:** 1.44.0
-   **Setting python.jediEnabled:** true | false
-   **Python and/or Anaconda version:** 3.8.0
-   **OS:** Windows_NT x64 10.0.18362
-   **Virtual environment:** conda | venv | virtualenv | N/A | ...

## Developer Tools Console Output

[-1586816413609.log](https://github.com/microsoft/vscode-python/files/4472163/-1586816413609.log)

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by greazer** [comment]
Not enough information to solve, closing.
