### ISSUE TITLE
Request: display video in jupyter notebook during processing

### ISSUE THREAD

**Issue by sebastianherreramonterrosa** [microsoft/vscode-jupyter#16271]
#### Description
When applying frame-by-frame processing to a video, I usually rely on `cv2.imshow` to visualize the output. However, this approach requires an external window and isn't well-suited for Jupyter Notebooks, especially in environments like Visual Studio Code. It would be fantastic if we could visualize the frame-by-frame video processing directly as the output of a cell in a Jupyter Notebook.

#### Current Workflow
The standard code to achieve this outside a notebook is:

```python
import cv2

video_path = "./my_video.mp4"
cap = cv2.VideoCapture(video_path)

while cap.isOpened():
    success, frame = cap.read()

    if success:
        frame = process_my_frame(frame)  # Apply custom frame processing

        cv2.imshow("frame", frame)  # Display the frame
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()
```

**Comment by DonJayamanne** [comment]
Thank you for filing this feature request.
Unfortunately the Jupyter extension doesn't provide such functionality, it merely provides the renderers for outputs generated by the kernel.
I.e. if you want to view the frame output in VS Code, then you need to use a python package that can generate the necessary output that can be displayed in Notebooks. Generally most (if not all) outputs generated in notebooks can be displayed in VS Code.

In this case, I belieeve you need to find a package that can generate the output.
Optionally, find a way to convert the frame into a format that is already supported.
E.g. convert the frame into a png image format, and then display that png image.

Here are a few samples
https://gist.github.com/mstfldmr/45d6e47bb661800b982c39d30215bc88
https://medium.com/@souquet.leo/display-an-image-opencv-image-in-jupyter-computer-vision-toolbox-37a1150ec198

Closing this issue as it is beyond the scope of this extension.
