### ISSUE TITLE
Include code sent from editor in Interactive Window text entry box history

### ISSUE THREAD

**Issue by andycraig** [microsoft/vscode-jupyter#1628]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description

When using the up/down arrow keys in the Interactive Window text entry box to go through the history of code that was previously sent, only code sent _from the text entry box_ is included. Code that was sent from the editor window is not included in the history.

This video illustrates what mean. '1' and '2' were sent from the text entry box and '99999999' was sent from the editor. After sending all three numbers, pressing up/down makes only '1' and '2' appear.

![history](https://user-images.githubusercontent.com/23294156/74835981-d1804900-5361-11ea-90a0-c6f4d1a56552.gif)

Perhaps this was an intentional design decision, in which case it's probably fine as-is. But if not it would be nice to have code sent from the editor appear in the history as well.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by joyceerhl** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/129081
