### ISSUE TITLE
separate run and stop buttons

### ISSUE THREAD

**Issue by yonashub** [microsoft/vscode-jupyter#16282]
Currently, the Jupyter Notebook integration in Visual Studio Code uses a single button to toggle between running a cell/kernel and stopping it. This design can lead to unintentional behavior.

When a long-running operation is interrupted by clicking the button, the button's state changes to "Run" immediately while its icon is still "stop". If the user clicks again without realizing the kernel has stopped, the operation reruns. This causes unexpected side effects.

**Request**

To improve usability and prevent accidental reruns, separate "Run" and "Stop" buttons for Jupyter Notebooks in VS Code. This separation will prevent accidental reruns due to the overloaded button behavior.

**Proposed Solution**

Consider displaying two distinct buttons:
Run: Triggers kernel execution.
Stop: Interrupts the current kernel execution.

**Reproduction Steps**
Open a Jupyter Notebook in VS Code.
Run a long-running cell.
Click the button to stop the kernel.
Quickly click the button again.
**Expected Behavior**
The kernel should remain stopped.
**Actual Behavior**
The kernel reruns.

**Comment by DonJayamanne** [comment]
> the button's state changes to "Run" immediately while its icon is still "stop". If the user clicks again without realizing the kernel has stopped, the operation reruns. This causes unexpected side effects.

Please can you share a video of this, based on the code we change the icon only when the state has changed. Not otherwise.
