### ISSUE TITLE
Jupyter notebook cell code folding and output view expanding request

### ISSUE THREAD

**Issue by matthewgson** [microsoft/vscode-jupyter#1629]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description

 This feature request is similar to microsoft/vscode-python#10503. I hope vscode jupyter notebook may allow the code cell to be folded as in .py code editor in VScode, and fold the output panel as in Jupyterlab (this is done when a user clicks left margin of the cell). It would be great if it adds an option to show code line number within the cell, but maybe it is not crucial.
<img width="826" alt="image" src="https://user-images.githubusercontent.com/46496637/77232559-14f3f000-6b78-11ea-9b9c-7f5290afa92c.png">

On the other hand, output panel is forced to be viewed through scrolling if it is too big. I hoping that there's an option (possibly by right-click) to expand the output so that users can view the whole output handy.

<img width="1610" alt="image" src="https://user-images.githubusercontent.com/46496637/77232977-baa85e80-6b7a-11ea-9e34-52b9e755a407.png">

Also a minor fix:
Please replace file icon on the tab to Jupyter icon. 
(Edit : I'm currently using vscode-icons package from vscode teams. The icon disappears when it renders .ipynb)
<img width="549" alt="image" src="https://user-images.githubusercontent.com/46496637/77232820-a9ab1d80-6b79-11ea-8dfe-6029ae7b024a.png">

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by peter-ch** [comment]
That page says nothing about code folding. How do I use it?

**Comment by IanMatthewHuff** [comment]
@peter-ch in the new notebook interface there are commands and keybindings to collapse both the input and output sections of any cells. Is that what you are looking for? Example of a collapsed code section (with expand icon) shown below.
![image](https://user-images.githubusercontent.com/812783/102515236-58658700-4042-11eb-85c7-93a6e2462bb9.png)

**Comment by peter-ch** [comment]
I'm looking for the functionality to collapse code blocks. I can see on this page that it is present https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/ 
but when I open a notebook I don't see those little buttons to collapse anything, they're just not there. Is there an option to turn this on? Do I use the "old" notebook interface for some reason and how do I turn the new on? Thanks.

**Comment by IanMatthewHuff** [comment]
@peter-ch If you are using VS Code - Insiders you should get the now notebook interface by default. In that interface I don't believe that there are actually buttons to do the collapse. There is instead a keybinding and a vscode command to collapse them. The button to expand back out only shows up after collapsing them.

**Comment by peter-ch** [comment]
Yes, thanks, I just realized I wasn't using the insiders build. It works.

**Comment by Bakerbakura** [comment]
Is there any info on when the new notebook interface will be pushed to the main VS Code build?

**Comment by jiajia20** [comment]
This is amazing! Thanks for making JupyterNotebook cell and their input/output Collapseable.

**Comment by pbower** [comment]
Hi, when is this being added to VS Code?

**Comment by pbower** [comment]
This is awesome. When is it being added to the main build? The shortcut Ctrl-K Ctrl-C doesn't seem to work however.

**Comment by pbower** [comment]
This is awesome. When is it being added to the main build? The shortcut Ctrl-K Ctrl-C doesn't seem to work however. 
Also, it would be great if there were a 'expand/collapse all cells' option up the top to keep things neat and tidy.

**Comment by pbower** [comment]
This is awesome. When is it being added to the main build? 
It would be great if there were a 'expand/collapse all cells' option up the top to keep things neat and tidy.

**Comment by DavidKutu** [comment]
We're working hard on that right now!

Unfortunately we don't have an exact date. I'll add that we are keeping up with this [API](https://github.com/microsoft/vscode/issues/93265). When that releases on stable, we'll follow suit as soon as possible.

**Comment by IanMatthewHuff** [comment]
Closed as the new Notebook UI is fully released now.
