### ISSUE TITLE
Support filtering variables in the variable explorer based on JMC

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1630]
Some imports generate a ton of variables (like types defined etc) that we don't filter by default.

We could use the 'file' value we get from Jupyter to filter out types that aren't in the workspace. These would be non user code.

See this bug for a reason why:
microsoft/vscode-python#10301

**Comment by amunger** [comment]
I'm assuming this is complete since I haven't noticed non-JMC variables. Let me know if that's not the case with an example
