### ISSUE TITLE
Errors on the 'Connecting to a remote...' wiki page

### ISSUE THREAD

**Issue by gy-mate** [microsoft/vscode-jupyter#16339]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1.
The title should include `github.dev`.

2.
`python -m jupyter --generate-config` or `jupyter --generate-config`
_is correctly_
`python -m jupyter notebook --generate-config` or `jupyter notebook --generate-config`

3.
The _"If Jupyter Server is running on your local machine, your browser might prevent access to this locally running Jupyter application from public websites such as"_ sentence is missing its ending.

### VS Code Version

N/A

### Jupyter Extension Version

N/A

### Jupyter logs

```shell

```

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Fixed

**Comment by gy-mate** [comment]
@DonJayamanne Thank you! :)

As far as I can see, issue no. 3 hasn't been fixed yet:

> The _"If Jupyter Server is running on your local machine, your browser might prevent access to this locally running Jupyter application from public websites such as"_ sentence is missing its ending.
