### ISSUE TITLE
Add support for sandance data explorer

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1633]
https://sanddance.js.org/

To my knowledge its a Gui that's used to explore data.. Do something visually what one would do programatically using pandas and/or similar.

We have an extension in VS Code for this, built in react. https://marketplace.visualstudio.com/items?itemName=msrvida.vscode-sanddance

Probably reach out and integrate as a data explorer, or attempt to integrate ourselve (PR, etc)

![sandance](https://user-images.githubusercontent.com/1948812/75702021-95a28900-5c69-11ea-9b8c-897a861fd6a9.gif)

**Comment by IanMatthewHuff** [comment]
Closing in favor of #1135 as there is more info and Tim's work in that issue.
