### ISSUE TITLE
Support for pixi environments using pixi-kernel

### ISSUE THREAD

**Issue by seembha** [microsoft/vscode-jupyter#16335]
I have found Pixi quite useful to manage my Python project workflow. I have a global environment where I install common utilities like JupyterLab which I then use, with the help of pixi-kernel (https://github.com/renan-r-santos/pixi-kernel), to manage my notebooks in pixi project environments. This obviates the need to have JupyterLab in every environment. Pixi environments are now supported by VSCode's Python extension and was hoping Jupyter extension would follow suit.

Here's my setup
### Global environment
```
PS C:\Users\seembha\Projects\Python\test\src\test> pixi global list
Global environments as specified in 'C:\Users\seembha\.pixi\manifests\pixi-global.toml'
└── python
    ├─ dependencies: python 3.13.1, jupyterlab 4.3.4, pixi-kernel 0.5.3
    └─ exposes: jlpm, python, pydoc, jupyter-labhub, jupyter-labextension, jupyter-lab, idle, pythonw
```
### Project environment
```
PS C:\Users\seembha\Projects\Python\test\src\test> pixi info
System
------------
      Pixi version: 0.39.0
          Platform: win-64
  Virtual packages: __win=0=0
                  : __archspec=1=x86_64_v4
         Cache dir: C:\Users\seembha\AppData\Local\rattler\cache
      Auth storage: C:\Users\seembha\.rattler\credentials.json
  Config locations: No config files found

Global
------------
           Bin dir: C:\Users\seembha\.pixi\bin
   Environment dir: C:\Users\seembha\.pixi\envs
      Manifest dir: C:\Users\seembha\.pixi\manifests\pixi-global.toml

Project
------------
              Name: test
           Version: 0.1.0
     Manifest file: C:\Users\seembha\Projects\Python\test\pyproject.toml
      Last updated: 23-12-2024 00:09:30

Environments
------------
       Environment: default
          Features: default
          Channels: conda-forge
  Dependency count: 2
      Dependencies: python, ipykernel
 PyPI Dependencies: test
  Target platforms: win-64
```
When I run JupyterLab in the project folder, pixi-kernel gives me a list of 3 kernels to pick
-  `Python 3 (ipykernel)` : global environment
-  `Python (Pixi)` : project environment
-  `R (Pixi)` : project environment

Selecting `Python (Pixi)` when opening a notebook in the pixi project folder (`C:\Users\seembha\Projects\Python\test\src\test\Untitled.ipynb`) picks the appropriate project (default) environment
```
import sys
print(sys.executable)
C:\Users\seembha\Projects\Python\test\.pixi\envs\default\python.EXE
```

When I open the above notebook in VSCode (v1.96.2) with Jupyter extension (v2024.11.0) I get a list of only 2 kernels as shown in the screenshot below and the choice for the project environment is missing.
![Image](https://github.com/user-attachments/assets/b2d1e9df-88d1-4011-8c8d-62dbedfed1ce)

I can, however, go to `Python Environments...` and pick the correct project environment. But, I'm not sure if that's the correct/expected behavior.

**Comment by DonJayamanne** [comment]
> in the screenshot below and the choice for the project environment is missing.

Instead of picking the option 'Jupyter kernel', go back and select three 'Python Environment' from the list
