### ISSUE TITLE
Kernel restart and clear cells commands via keyboard shorcuts don't work from editor

### ISSUE THREAD

**Issue by patrick984** [microsoft/vscode-jupyter#1636]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Configure key-bindings for restartkernel and removeallcells.

```
  {
    "key": "ctrl+'",
    "command": "python.datascience.restartkernel",
    "when": "editorTextFocus && python.datascience.featureenabled && python.datascience.hascodecells"
  },
  {
    "key": "ctrl+alt+'",
    "command": "python.datascience.removeallcells",
    "when": "editorTextFocus && python.datascience.featureenabled && python.datascience.hascodecells"
  },
```

2. Start using an Interactive Session (.py file with #%% cells).

3. Try to restart kernel or clear cells using configured keyboard shortcuts.

## Actual behavior

Nothing happens.

## Expected behavior

Interactive kernel is restarted or output cells cleared as per command.

## Notes

This worked properly using the previous version of the Python extension (before support for multiple interactive windows was added). I am using Interactive Window Mode: perFile. However I also tested with it set to single and multiple and neither worked.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.08.103604
-   **VS Code version:** 1.48.1
-   **Setting python.languageServer:** Pylance
-   **Python version:** 3.8.1
-   **OS:** Windows & macOS
-   **Virtual environment:** WinPython & venv (macOS)

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by juliuscrn** [comment]
Would be nice to have these back. Having to click that restart icon every time you need to clear the environment gets tiresome. I tried using the shortcut with Interactive window mode single, perfile, default - none of them works.

**Comment by joyceerhl** [comment]
Closing in favor of https://github.com/microsoft/vscode-jupyter/issues/6996. Restart Kernel has been fixed to work from the editor, but Clear All still needs to be fixed.
