### ISSUE TITLE
Investigate LiveShare tests (many are disabled + raw kernel conversion)

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#1637]
Currently many of the liveshare test look like they are being skipped. I would presume due to issues with them. I saw some problems when looking at converting them to use raw kernel, so filing this issue to consider if we want to get the liveshare tests fixed up in general and converted to use raw kernel in particular.

**Comment by greazer** [comment]
LiveShare support is being revamped.
