### ISSUE TITLE
Setup font color in [markdown] cell will make math render disappear

### ISSUE THREAD

**Issue by Fred-Wu** [microsoft/vscode-jupyter#1640]
## Steps to cause the bug to occur

```
# %%[markdown]
# This is $\beta$

#%%[markdown]
# <font color='blue'>
# This is $\beta$
```
![pythoncell](https://user-images.githubusercontent.com/4111978/88059441-31e11400-cba8-11ea-97d2-6620956ec166.png)

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local 
-   **Extension version:** 2020.7.94776
-   **VS Code version:** 1.47.2
-   **Setting python.jediEnabled:** true 
-   **Setting python.languageServer:** Jedi 
-   **Python and/or Anaconda version:** 3.7.7
-   **OS:** Ubuntu 20.04
-   **Virtual environment:** conda

**Comment by joyceerhl** [comment]
Fixed in native interactive window 
![image](https://user-images.githubusercontent.com/30305945/131549550-a26c8333-2074-4a38-9653-ce32c71718c4.png)
