### ISSUE TITLE
Notebook files larger than usual due to saving SVG's for plotviewer

### ISSUE THREAD

**Issue by Viynne** [microsoft/vscode-jupyter#1646]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Working with Notebook on Visual Studio Code

## Actual behavior
Asides from the fact that my VSCode has began to slow down drastically, predictions are really slow.
My notebook file of 696KB gets as large as 53mb when I re-run it on my VSCode. This makes loading it up take longer. How can I resolve this?

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.8.101144
-   **VS Code version:** 1.48.0
-   **Setting python.jediEnabled:** false
-   **Setting python.languageServer:** Jedi | Microsoft | None
-   **Python and/or Anaconda version:** 4.8.3
-   **OS:** Windows 
-   **Virtual environment:** N/A 

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by ChandlerTayek** [comment]
I ran into the same issue and I tried setting that flag in VSCode's version 1.53.2 and it says it is an unknown configuration setting. Does anyone have a work around or is this flag supposed to work in the most up-to-date version of VSCode?

**Comment by rchiodo** [comment]
The new setting is 

```
"jupyter.enablePlotViewer": "false"
```

We used to have our code in the python extension when this bug was originally created.

**Comment by ChandlerTayek** [comment]
The setting:
`"jupyter.enablePlotViewer": false` 
 worked like a charm for me. Just for context, the issue I was running into was not having GitHub render my notebook created from VSCode because of the massive file size multiple SVG plots were creating. That setting reduced my file size by about 80%. Thank you so much for the quick response @rchiodo.

**Comment by taldcroft** [comment]
The fix works great, but I would never have guessed that this option is going to bloat my (plot-heavy) notebooks by a factor of 30 in size. If the option were called `storePlotsAsSVG` that would have caught my attention. Or maybe it should default to false, I have not found the plot viewer to be all that useful and as mentioned it can break viewing on GitHub.

**Comment by IanMatthewHuff** [comment]
Now we just generate PNGs by default and show PNGs in the plot viewer. You need to opt into the SVGs explicitly.
