### ISSUE TITLE
Error loading pyodps/progress:1.5.0. Internet connection required for loading 3rd party widgets. Error loading pyodps/progress:. Internet connection required for loading 3rd party widgets.

### ISSUE THREAD

**Issue by wellcasa** [microsoft/vscode-jupyter#1648]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local | Remote | N/A
-   **Extension version:** 20YY.MM.#####-xxx
-   **VS Code version:** #.##
-   **Setting python.jediEnabled:** true | false
-   **Setting python.languageServer:** Jedi | Microsoft | None
-   **Python and/or Anaconda version:** #.#.#
-   **OS:** Windows | Mac | Linux (distro):
-   **Virtual environment:** conda | venv | virtualenv | N/A | ...

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by DonJayamanne** [comment]
This hasn't been reported, since.
Hence closing this issue.
If this issue persists, please create a new issue or please re-open this issue.
