### ISSUE TITLE
Start Page links are red

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode-jupyter#1649]
## Environment data

VS Code Version: 1.48.0 (stable)
Python extension version: v2020.8.103604
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T08:03:27.059Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

When I install the python extension, the links on the Start Page appear in red and I am using the default dark theme. (the links are still working)

![recording (5)](https://user-images.githubusercontent.com/9721254/90933672-f49dbb00-e3cd-11ea-91be-11667ea70ce6.gif)

**Comment by greazer** [comment]
Start page will be going through some major updates in the near future.
