### ISSUE TITLE
Vim editing (or other editor setting) doesn't work in interactive window input

### ISSUE THREAD

**Issue by pmercatoris** [microsoft/vscode-jupyter#1650]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

Hello, I am a data scientist wanting to switch from Emacs to VSCode, but am held up by one missing feature. I need the modal editing provided by the Vim extension. However, the Python Repl behaves totally different from other editing buffers, as it does not accept the Vim extension (and i suppose other editing extension either). 

Problems like this can occur: the original behaviour of CTRL-V is disabled to allow the Vim behaviour (blockwise visual mode) and am unable to paste code in the interactive window with the keyboard. The `p` from Vim is not recognised, and the `CTRL-V` is disabled, I only can right click and paste. Same thing happens with Copy, Cut and others.

Moreover, may I suggest to allow the Repl to be a buffer as it allows easier navigation of the history using he keyboard and would allow other editing  settings to be taken into account. That is the way it works in Emacs, and am really  missing that feature.  Often i would just stay in the Repl and copy parts of  previously ran commands all without touching the mouse.

**Comment by 205g0** [comment]
Would it be possible to let existing extensions be active in your notebooks? I use for example the Neo Vim extension powered by a full nvim instance which is close to the real experience.

**Comment by retorquere** [comment]
Any news on this? I keep getting stray characters in my notebooks 😜 .

**Comment by retorquere** [comment]
That's what I indeed what I was looking for. Alright, appreciate the quick answer. I'll have to look at jupytext then.

**Comment by joyceerhl** [comment]
This is now supported in the new native interactive window implementation: https://code.visualstudio.com/updates/v1_58#_jupyter-interactive-window
