### ISSUE TITLE
Ability to open .py files directly in the Notebook Editor

### ISSUE THREAD

**Issue by syagev** [microsoft/vscode-jupyter#1651]
# Feature: Notebook Editor

## Description
Allow opening a `.py` file, optionally with percent annotations, directly in the notebook editor. This allows a notebook like experience for percent files, instead of the only option available currently which is running the cells in the interactive window. This is also preferable to converting the the file `.ipynb` before hand.

Naturally, cell outputs would be either discarded or exported to an `.ipynb` explicitly. 

This would mimic the behavior of the Jupyter Notebook web interface when opening `.py` files.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time.
