### ISSUE TITLE
Support customizing Just My Code settings for interactive window

### ISSUE THREAD

**Issue by Coderx7** [microsoft/vscode-jupyter#1656]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description
It would be great, not to encounter the `interactiveshell.py` when debugging. 
I uncheck **Debug just my code** so that I can step into the libraries I use. However, `interactiveshell.py` is a nuisance here which I really dont need to see or work with. 
If `interactiveshell.py` is of any importance, we can add a separate checkmark for it in the settings that lets the user explicitly enable it (i.e. when debugging, the first code that he/she sees is interactiveshell.py!).   
In my humble opinion, 99.99% of the times, no one intends on checking on `interactiveshell.py` when they start debugging their code. 
It would be great to have this out of the way. 
Thank you all very much in advance 

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by joyceerhl** [comment]
This should be fixed with https://github.com/microsoft/debugpy/issues/664
