### ISSUE TITLE
interactive window not opening in other conda environment

### ISSUE THREAD

**Issue by sachin02986** [microsoft/vscode-jupyter#1657]
Some how I am unable to open python interactive window in other conda environment. This works perfectly fine in base environment, but gives me the below error in other environment. - 
'Timed out waiting to get a heartbeat from kernel process'

Not sure if a known issue or if I am missing anything in the configuration.
By the way I am able to run script in other environment in terminal but not in interactive window.

**Comment by greazer** [comment]
Stale bug.
