### ISSUE TITLE
text of error messages is not HTML-encoded

### ISSUE THREAD

**Issue by allefeld** [microsoft/vscode-jupyter#1662]
# Bug: Notebook Editor, Interactive Window, Editor cells

The text of error messages, i.e. messages attached to raised `Exception` and `Error` objects, is not HTML-encoded, potentially disrupting display.

## Steps to cause the bug to occur

Raise an exception or error whose message contains `<` followed by a character in a notebook cell.

Examples:

```
raise TypeError("array(['1', '2.0', 'a'], dtype='<U32'")
raise TypeError("a<b")
raise TypeError("a<10")
raise TypeError("This is <i>very</i> important!")
```

## Actual behavior

In the first and second case, the error message is truncated in display. In the fourth case, the word 'very' is shown in italics.

![image](https://user-images.githubusercontent.com/1738353/86500113-d1b83880-bd86-11ea-99d1-2ed16273148b.png)

This last case might be seen to be useful, but the truncating of error messages in other cases is too high a price. Python error messages are not intended to be interpreted as HTML code.

## Expected behavior

The error messages should appear verbatim, without interpretation as HTML.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.6.91350
-   **VS Code version:** 1.46.1
-   **OS:** Linux Debian
-   **Virtual environment:** conda

## Developer Tools Console Output

No relevant output.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
