### ISSUE TITLE
Cell output generated without calling `print` is truncated without a warning

### ISSUE THREAD

**Issue by hbsmith** [microsoft/vscode-jupyter#1664]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

For example:
```
big_dict = {}
for i in range(1000):
    big_dict[i] = list(range(10))
```

If I run a cell with `print(big_dict)`, it outputs:

```
Output was trimmed for performance reasons.
To see the full output set the setting "python.dataScience.textOutputLimit" to 0.
...
4, 5, 6, 7, 8, 9], 460: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 461: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 462: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 463: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 464: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 465: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 466: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 467: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 468: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 469: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 470: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 
```

While if there's implicit output when running the cell (no print call, just `big_dict`), it outputs:
```
6, 7, 8, 9],
 474: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 475: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
```

## Actual behavior

Implicitly outputting from a cell is truncated without warning. 

## Expected behavior

I would expect a warning message just like I get from using `print()`

-   **Jupyter server running:** Remote
-   **Extension version:** 20YY.MM.#####-xxx
-   **VS Code version:** 1.47.2
-   **Setting python.jediEnabled:** don't see this setting
-   **Setting python.languageServer:** Jedi
-   **Python and/or Anaconda version:** 3.7.6
-   **OS:** Mac
-   **Virtual environment:** N/A

Related to : microsoft/vscode-python#9401

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
