### ISSUE TITLE
How to integrate custom SVG into plot viewer?

### ISSUE THREAD

**Issue by allefeld** [microsoft/vscode-jupyter#1665]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description

I'm not sure whether this is just a question, or a feature request.

I have Python code that generates custom plots in SVG format and displays them in the notebook output cell (`_repr_svg_` / `IPython.display`). I would like to display these SVGs in such a way that they can be "expanded", i.e. there is the "Expand image" icon on hover, and when clicked the SVG is shown in the plot viewer ("Plots" tab).

As a question: The vscode-python documentation mentions that this feature works with matplotlib and Altair. Is there something I can do make it work with my plots, I assume via a JavaScript API?

As a feature: I propose that every SVG output cell can be "expanded".

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by IanMatthewHuff** [comment]
I'm going to close this enhancement request as it has not been upvoted for consideration.
