### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by ASCII35** [microsoft/vscode-jupyter#1667]
Issue Type: <b>Bug</b>

Extension host terminated unexpectedly. When I run jupyter notebook code both on  local  and remote server, this bug happened many times irregularly.

Extension version: 2020.7.96456
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (18.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by MJimitater** [comment]
Any updates on this? Im facing the same problem

**Comment by ASCII35** [comment]
> Any updates on this? Im facing the same problem

No. Still have this problem..

**Comment by MJimitater** [comment]
@ASCII35 Im also still facing the problem.. but I was able to run my code in "insiders" version of vscode (1.52.0-insiders) and the problem hasn't occured since.. just fyi

**Comment by ASCII35** [comment]
> @ASCII35 Im also still facing the problem.. but I was able to run my code in "insiders" version of vscode (1.52.0-insiders) and the problem hasn't occured since.. just fyi

Thanks!!!

**Comment by Dart120** [comment]
<img width="538" alt="image" src="https://user-images.githubusercontent.com/47606100/117583809-26dc7d80-b101-11eb-911c-28e4d12e24f7.png">
<img width="536" alt="image" src="https://user-images.githubusercontent.com/47606100/117583825-41aef200-b101-11eb-95c7-57cfac8a52fe.png">


I've just had this issue. I was running a particulally long data wrangling and ml script in notebook mode. Here is the output from devtools.

**Comment by greazer** [comment]
@Dart120, thanks for the info, but it doesn't provide enough detail as to what may have happened. Please open a new issue with any repro steps you might have. Be sure to include the version of VS Code you're using and whether this was a notebook or python script you were running.
