### ISSUE TITLE
Remote jupter server stuck at "Starting Jupyter Server"

### ISSUE THREAD

**Issue by sahilseth** [microsoft/vscode-jupyter#1668]
# Bug: issue with using a remote jupyter server

## Steps to cause the bug to occur

1. create a blank jupyter template
2. set a remote jupyter server
3. running the first cell asks for a password
4. it gets stuck at "Starting Jupyter Server"

## Actual behavior

console window shows the following:

```
[Extension Host] Info Python Extension: 2020-06-20 09:52:40: Executing cell NotebookImport#0
console.ts:137 [Extension Host] Info Python Extension: 2020-06-20 09:52:40: Waiting for jupyter server and web panel ...
console.ts:137 [Extension Host] Info Python Extension: 2020-06-20 09:52:40: Checking for server existence.
console.ts:137 [Extension Host] Info Python Extension: 2020-06-20 09:52:40: Checking for server usability.
console.ts:137 [Extension Host] Info Python Extension: 2020-06-20 09:52:40: Starting notebook server.
console.ts:137 [Extension Host] Info Python Extension: 2020-06-20 09:52:40: Connecting to history server
console.ts:137 [Extension Host] Info Python Extension: 2020-06-20 09:52:40: Creating jupyter server: ac9982aa-0508-4c6c-8786-bfa9b6ea1d50
```

## Expected behavior
4. it gets stuck at "Starting Jupyter Server"

![image](https://user-images.githubusercontent.com/684975/85204764-55304f00-b2dc-11ea-8ba0-a75f5ee69756.png)

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Remote 
-   **Extension version:** v2020.6.89148
-   **VS Code version:** 1.46.1
-   **Setting python.jediEnabled:** true | false
-   **Setting python.languageServer:** Jedi | Microsoft | None
-   **Python and/or Anaconda version:** 3.7.4 (local), 3.7.1 (remote)
-   **OS:** Mac (local) | Linux (Ubuntu 18.04), remote
-   **Virtual environment:** conda (remote)

## Developer Tools Console Output

```
[Extension Host] Info Python Extension: 2020-06-20 09:52:40: Executing cell NotebookImport#0
console.ts:137 [Extension Host] Info Python Extension: 2020-06-20 09:52:40: Waiting for jupyter server and web panel ...
console.ts:137 [Extension Host] Info Python Extension: 2020-06-20 09:52:40: Checking for server existence.
console.ts:137 [Extension Host] Info Python Extension: 2020-06-20 09:52:40: Checking for server usability.
console.ts:137 [Extension Host] Info Python Extension: 2020-06-20 09:52:40: Starting notebook server.
console.ts:137 [Extension Host] Info Python Extension: 2020-06-20 09:52:40: Connecting to history server
console.ts:137 [Extension Host] Info Python Extension: 2020-06-20 09:52:40: Creating jupyter server: ac9982aa-0508-4c6c-8786-bfa9b6ea1d50
```

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

Please let me know if I missed mentioning any details.

**Comment by greazer** [comment]
Issues labeled with "Info needed" are closed if we do not receive more information from the issue author in 2 weeks. If you are the issue author and you still are running into this problem, please reactivate with additional information.
