### ISSUE TITLE
Expansion of cell output windows

### ISSUE THREAD

**Issue by bpops** [microsoft/vscode-jupyter#1673]
It would be fantastic if the notebook editor could provide expanded output cells, such that scrolling the individual cell windows would not be required. This is currently an option in Jupyter notebooks by double-clicking the side of the window to toggle expanded/compact.

Could be an toggle feature similar to that, a setting to apply to all, etc.

**Comment by m-beau** [comment]
> * Python › Data Science

I cannot find this setting anywhere. Do I need to literally write down "python.DataScience.EnableScrollingForCellOutputs": false in the settings json file?

Thanks!

**Comment by m-beau** [comment]
Amazing cheers!

**Comment by greazer** [comment]
Closing as additional considerations for this issue are covered by other bugs such as #7096 and microsoft/vscode#131574
