### ISSUE TITLE
Cell output flashes when using fastprogress package (was: cell output erased after execution/model training is complete.)

### ISSUE THREAD

**Issue by agigao** [microsoft/vscode-jupyter#1674]
# Bug: Notebook Editor, Interactive Window, Editor cells
Hi guys,

I'd love to use VSCode for my Data Science endeavours but this break the workflow:

Progress bar generated report gets erased after it's finished, not very convenient when training models:
![Peek 2020-07-24 15-03](https://user-images.githubusercontent.com/22436648/88385156-e18fcf00-cdbe-11ea-9714-783c436ca0a3.gif)
Steps to Reproduce:

1. pip install fastprogress
2. open a new notebook in VSCode and run the snippet
```python
from fastprogress.fastprogress import master_bar, progress_bar
from time import sleep
mb = master_bar(range(10))
for i in mb:
    for j in progress_bar(range(100), parent=mb):
        sleep(0.01)
        mb.child.comment = f'second bar stat'
    mb.main_bar.comment = f'first bar stat'
    mb.write(f'Finished loop {i}.')
    #mb.update_graph(graphs, x_bounds, y_bounds)
```

**Finished Loop 0, 1, 2...**
![Peek 2020-07-24 14-47](https://user-images.githubusercontent.com/22436648/88384580-be185480-cdbd-11ea-8714-e723e53a1a5e.gif)

Does this issue occur when all extensions are disabled?: Yes

- VSCode Version:

```
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:15.161Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic
```

- OS Version:
```
Operating System: Linux Mint 20
Kernel: Linux 5.4.0-42-generic
Architecture: x86-64
```
- Python
```
Version 3.8.2
Anaconda? - Nope
```

Cheers,
Giga

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by claforte** [comment]
FYI,  I tried to work-around the issue using:
```
import fastprogress
fastprogress.fastprogress.master_bar, fastprogress.fastprogress.progress_bar = \
    fastprogress.fastprogress.force_console_behavior()
fastprogress.fastprogress.workaround_empty_console_output()
```
... but unfortunately that doesn't help. It would fantastic if this could be fixed... this is the #1 issue preventing me from switching from "Jupyter notebook" to vscode's.

**Comment by DonJayamanne** [comment]
@claforte 
This issue has been resolved in Native notebooks
Please have a look at native notebooks (a better UI for editing of Notebooks):
* Please install VS Code insiders & you'll get it automatically
* Please understand some of the features might not yet be available (variable viewer, run by line, etc)
* See here for more information https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/

**Comment by claforte** [comment]
I just tried it in native notebooks today, and while the output disappears, at least this time I see the resulting dataframe/report, so it's more usable:
![image](https://user-images.githubusercontent.com/5090329/106356061-a53baf00-62ca-11eb-8741-926d7abdf4fc.png)

**Comment by DonJayamanne** [comment]
So, if i'm not mistaken this (Native Notebooks UX) is more inline with what Juptyer does (see Jupyter output here https://github.com/microsoft/vscode-jupyter/issues/1674#issuecomment-663836730)

**Comment by claforte** [comment]
Yes, at this point, the only remaining issue is that the Native Notebooks UX keeps resizing/flashing while the fastprogress is shown. But it's just annoying, not a showstopper. Thank you!

**Comment by DonJayamanne** [comment]
@claforte I'm going to close this issue as it now works as expected.

>  remaining issue is that the Native Notebooks UX keeps resizing/flashing while the fast

I'll file a seprate issue for this.
