### ISSUE TITLE
command W close both plot viewer and the notebook together

### ISSUE THREAD

**Issue by wli64** [microsoft/vscode-jupyter#1676]
## Actual behavior
when double click to open a plot in the plot viewer, after hit command W, both the plot viewer and the jupyter notebook close.

## Expected behavior
command W should only close the one windows which is active now, should not close both the plot viewer and the main notebook window.

![1](https://user-images.githubusercontent.com/57596964/82372548-715e7900-9a1c-11ea-98be-cfe8daaa5562.gif)

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local 
-   **Extension version:** 2020.5.80290
-   **VS Code version:** 1.45.1
-   **Setting python.jediEnabled:** true
-   **Python and/or Anaconda version:** 3.7.6
-   **OS:**  Mac 
-   **Virtual environment:**  N/A | ...

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by IanMatthewHuff** [comment]
I don't repro this any more with the new notebook UI.
