### ISSUE TITLE
Jupyter notebook cannot save changes from Notebook Editor

### ISSUE THREAD

**Issue by zatkins2** [microsoft/vscode-jupyter#1677]
# Bug: Notebook Editor, Interactive Window, Editor cells

Unfortunately this Issue appears in ~50% of sessions, but of course this is frequent enough to prevent use of Notebook development in VS Code (with the Notebook Editor) on my machine.

## Steps to cause the bug to occur

1. Open a pre-existing Jupyter notebook (any .ipynb file; as indicated open within WSL. I am running Ubuntu-18.04).
2. Make arbitrary changes to your file.  After a short period (immediately to a few minutes), the Notebook Editor will not be able to save -- both ctrl + S and the save button do not clear the "dirty editor" asterisk next to filename.
3. Does not depend on whether cells have been executed since changes made in file (unlike in other issues which noted that executing a cell recovers ability to save the file).

Interestingly, the problem seems to correlate with the Notebook Editor mistakenly opening multiple windows of the same file in step 1, if opening directly from the VS Code Explorer. In ~50% of VS Code sessions, I observe this behavior (multiple Notebook Editor windows even though I opened the file "once"). If this happens, my inability to save occurs ~100% of the time...

In this case:
1. Open a pre-existing Jupyter notebook (any .ipynb file; as indicated open within WSL. I am running Ubuntu-18.04).
2. Close any redundant Editor windows opened by VS Code.
3. Make arbitrary changes to your file.  **_Immediately_**, the Notebook Editor will not be able to save -- both ctrl + S and the save button do not clear the "dirty editor" asterisk next to filename.
4. Does not depend on whether cells have been executed since changes made in file (unlike in other issues which noted that executing a cell recovers ability to save the file).

Example:
* Multiple Editors opened from one file in Explorer
![image](https://user-images.githubusercontent.com/46325652/85213338-1e355a00-b32b-11ea-9955-48847f7c5191.png)
* Changes made to file, "dirty editor" asterisk does not respond to save attempts. Changes **_not_** written to disk
![image](https://user-images.githubusercontent.com/46325652/85213380-94d25780-b32b-11ea-83f5-f734ab1c2dac.png)

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Remote (WSL)
-   **Extension version:** 2020.6.89148
-   **VS Code version:**  Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
-   **Python and/or Anaconda version:** 3.8.2 / conda 4.8.3
-   **OS:** Windows_NT x64 10.0.18363
 -  **Remote OS version:** WSL1, Ubuntu-18.04, Linux x64 4.4.0-18362-Microsoft
-   **Virtual environment:** miniconda 

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
gitlens|eam|10.2.2
python|ms-|2020.6.89148

## Developer Tools Console Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by willuvbb** [comment]
Hello, I started to have this issue too and lost an hour of work. Has there been any progress made as to the root cause/any sort of fix?

**Comment by rchiodo** [comment]
Sorry there is no fix for the save button not working anymore (we haven't been able to repro locally). However, we are moving away from our custom implementation (which will change how we save).

You can try the new implementation by either:
- Using VS code insiders (which uses VS code's notebook editor instead of ours)
or
- Setting this in your USER (not workspace) settings.json:
```json
    "jupyter.experiments.optInto": [
        "CustomEditor"
    ],
```
That setting makes VS code track the document and whether or not it's dirty.

**Comment by willuvbb** [comment]
Hi @rchiodo, thank you so much for the quick response! I will try the CustomEditor setting that you suggested.
