### ISSUE TITLE
Jupyter notebook Export as Python Script FAILED

### ISSUE THREAD

**Issue by beto-Sibileau** [microsoft/vscode-jupyter#1681]
# Bug: VS code, Jupyter Notebooks, Export as Python

## Steps to cause the bug to occur

1.

## Actual behavior

The export as Python file doesn't work from the Export as button (error: Jupyter command `jupyter-nbconvert` not found). However, if I run the `nbconvert` from command line (`Python: Create Terminal`) it does work.

## Expected behavior

Jupyter Notebook exported as a py file. How to configure such that it works from the export as button?

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.9.114305
-   **VS Code version:** 1.50.1
-   **Python and/or Anaconda version:** 3.8.5
-   **OS:** Windows
-   **Virtual environment:** Dev Container: Python3

## Python Output

> /usr/local/bin/python ~/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/pyvsc-run-isolated.py jupyter nbconvert --version
Error 2020-10-29 10:43:38: Export failed [r [Error]: Traceback (most recent call last):
[...]
  File "/root/.local/lib/python3.8/site-packages/jupyter_core/command.py", line 133, in _jupyter_abspath
    raise Exception(
Exception: Jupyter command `jupyter-nbconvert` not found.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by Remodor** [comment]
I have exactly the same problem!

**Comment by Steffanou** [comment]
Same issue.
I closed all files in VSCODe, restarted VSCode, opened only the .ipynb to convert, run a cell.
then tried to convert to .py
It worked after this sequence, not sure which elment is needed.

**Comment by kostastsiolis** [comment]
Same issue as initially described.
The solution of installing jupyter-nbconvert to version 5.6.1 (as described in https://github.com/microsoft/vscode-jupyter/issues/611) works for me!!

**Comment by DonJayamanne** [comment]
@beto-Sibileau are you still experiencing this issue?

@kostastsiolis @Steffanou thanks for the feedback.

**Comment by GitHunter0** [comment]
I'm receiving the same error `Exception: Jupyter command `jupyter-nbconvert` not found.` when using the "Export As" button of the interactive window with the output of my python script (.py). 

I also tried to install `nbconvert 5.6.1` but the annoying error persists...

**Comment by GitHunter0** [comment]
> 
> 
> I'm receiving the same error `Exception: Jupyter command jupyter-nbconvert not found.` when using the "Export As" button of the interactive window with the output of my python script (.py).
> 
> I also tried to install `nbconvert 5.6.1` but the annoying error persists...

I exported as .ipynb first, which automatically installed some missing packages ('notebook' package being one of them) and now it is working.

**Comment by DonJayamanne** [comment]
@GitHunter0 
Thanks for the feedback, will look into what's different there.

**Comment by DonJayamanne** [comment]
@beto-Sibileau 
I just realized that you are on windows & are using a Docker Container. Is that correct.
Is it possible for you to share the docker image/file so we can try this at our end.

Thanks

**Comment by beto-Sibileau** [comment]
Hi @DonJayamanne , thanks for following up! Please find attached the docker file and `devcontainer.json` file I'm using, together with requirements. BTW, I have tried in the latter, both `nbconvert` and  `nbconvert==5.6.1` with the same error outcome:
~~~
Exception: Jupyter command `jupyter-nbconvert` not found
~~~
[devcontainer.zip](https://github.com/microsoft/vscode-jupyter/files/5772042/devcontainer.zip)

**Comment by DonJayamanne** [comment]
Thanks, I can now replicate this issue.

**Comment by DonJayamanne** [comment]
Looks like a bug in nbconvert, now i recall we had a number of issues with nbconvert in the past.
Please update to the latest version of nbconvert (6.0.7) & it will work.
I just ran `pip install nbconvert -U` and that worked. YOu might want to remove teh version number from the requirements.txt file for nbconvert (interestingly that's the only package that's pinned to a specific version).

Thanks again for providing the information.
Closing as updating the package fixes it.

**Comment by SonOfTheHighest** [comment]
Hi @DonJayamanne, after I updated nbconvert I now get the following error message as I am trying to convert a notebook to a pdf file: 

> nbconvert failed: article.tplx

Could you help me out?

**Comment by DonJayamanne** [comment]
@SonOfTheHighest this issue has been closed, please could you create a new issue with the details.
