### ISSUE TITLE
Undo (Ctrl + Z) hangs the kernel

### ISSUE THREAD

**Issue by vpankaj97** [microsoft/vscode-jupyter#1682]
Issue Type: <b>Bug</b>

1. Write any piece of code in a cell.
2. Try to UNDO.

Expected Result: 

Undo works just fine.

Actual Result:

Goes into an endless loop.

> Can't be stopped
> Kernel restart button doesn't work

I have to manually reopen the file (effectively restart the kernel)

---

As a visual representation, in the screenshot below, I have tried to perform undo action.

![image](https://user-images.githubusercontent.com/49087486/95831206-62bf8800-0d56-11eb-8aa2-f2eaeb8e93db.png)
 Note. It's been 5 mins now!

-- Using the **Preview Notebook Editor**
Extension version: 2020.10.302853766-dev
VS Code version: Code - Insiders 1.51.0-insider (605bc4ec1eaf8dc1acd89a0c3c5743926ed0dc09, 2020-10-12T10:52:10.028Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

**Comment by Bewinxed** [comment]
I can reproduce this on the latest insider vscode, ctrl+z makes the kernel run forever and i have to restart vscode.

Local vscode, local jupyter session, clean install.

**Comment by Jaimeolivares** [comment]
I can also confirm that ctrl+z does this instead of undoing anything in the cell.

Version: 1.52.0-insider (user setup)
Commit: 6f933020e8dd4ea046eae2bcfc59a18edf2bc517
Date: 2020-12-08T15:37:23.937Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by DonJayamanne** [comment]
This is an upstream issue and its being trakced here https://github.com/microsoft/vscode/issues/106362

**Comment by joyceerhl** [comment]
Validated that Ctrl + Z no longer hangs the kernel. However we are now unsetting the execution time for the kernel. I don't think we should be doing that and IIRC the extension controls this. Going to log a new issue for that.

![undo](https://user-images.githubusercontent.com/30305945/106095843-5682ef00-60e9-11eb-9336-e704e02b814d.gif)
