### ISSUE TITLE
Unable to load a compatible version of the widget 'catboost_module'. Expected behavior may be affected.

### ISSUE THREAD

**Issue by javiqm12** [microsoft/vscode-jupyter#1684]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. !pip install jupyter ipywidgets catboost
2. !jupyter nbextension enable --py widgetsnbextension
3. run:
```
from catboost.datasets import amazon
from catboost import CatBoostClassifier
(train_df, test_df) = amazon()
y = train_df.ACTION
X = train_df.drop('ACTION', axis=1)
cat_features = list(range(0, X.shape[1]))
model = CatBoostClassifier(iterations=100)
model.fit(X, y, cat_features=cat_features, verbose=10, plot=True)
```

## Actual behavior
Presents a pop up window in the lower right hand side with error
"Unable to load a compatible version of the widget 'catboost_module'. Expected behavior may be affected."
and buttons Ok, Do not show again, Report issue

## Expected behavior
Show a plot of logloss as progress training iterations

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.8.109390
-   **VS Code version:** 1.48.2
-   **Setting python.jediEnabled:** not defined
-   **Setting python.languageServer:** Jedi
-   **Python and/or Anaconda version:** Python 3.8.5
-   **OS:** Linux (distro): Manjaro xfce
-   **Virtual environment:** venv

## Python Output

After setting python.logging.level=debug, restarting vs code and running the above code, there is no Python output tab.

**Comment by DonJayamanne** [comment]
This should now work as expected, moving to June to get validated.
