### ISSUE TITLE
An error message "The host doesn't allow runing.." always pops up even though enable all permissions.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#1687]
## Environment data
![image](https://user-images.githubusercontent.com/59192491/93182229-07f13b80-f76c-11ea-8f28-161b1957c37b.png)

## Steps to reproduce
1. Install the LiveShare VSCode Extension (VS Live Share Extension Pack)
2. Open manualTestFile.py in VSCode
3. Run the first cell in the file
4. Switch to the `Live Share` tab in VS Code and start a session
5. Open another window of VSCode
6. Connect the second instance of VSCode as a Guest to the first Live Share session
7. Enable all permissions in Host
5. Click "Run cell" in Guest

## Expected behaviour
Interactive Window should open, show connection information, and execute cells.

## Actual behaviour
An error message pops up.
![image](https://user-images.githubusercontent.com/59192491/93182786-b0070480-f76c-11ea-80b2-a1f1727951ce.png)

Note: When we select a cell in manualtestfile.py and right-click to click the 'Run Current Cell, it can be executed without error message.
![image](https://user-images.githubusercontent.com/59192491/93183075-1db33080-f76d-11ea-9535-618010194c07.png)

**Comment by IanMatthewHuff** [comment]
Closing LiveShare related issues.
