### ISSUE TITLE
Be able to provide string argument to python.datascience.execSelectionInteractive for extensibility.

### ISSUE THREAD

**Issue by andycraig** [microsoft/vscode-jupyter#1689]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

`python.datascience.execSelectionInteractive` executes the current selection in the Interactive Window. How about a command that accepts a string argument and executes that in the Interactive Window? Other extensions could then call this to provide more complicated versions of `python.datascience.execSelectionInteractive`, such as executing and advancing to the next line (#13495) or auto-detecting and executing whole code blocks (#4978).

It's straightforward to send specified text to Python or IPython running in the terminal, but as far as I know there's currently no way to send specified text to the Interactive Window. (Apologies if I've missed an existing command that allows this.)

Thank you.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by andycraig** [comment]
Would you be interested in an external contributor PR for this?

In line with the title, I would add a string argument to `python.datascience.execSelectionInteractive`. If the argument is provided, it would send that string to the Interactive Window. If no argument is provided, it would follow the current behaviour: send the selection (or line, if there is no selection) to the Interactive Window.

**Comment by DavidKutu** [comment]
@andycraig we always welcome contributions!

**Comment by andycraig** [comment]
@DavidKutu Great! I will have a try at it.

**Comment by andycraig** [comment]
Feature added in #5053.
