### ISSUE TITLE
Local file not found error - Native notebooks

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#1690]
originally created by @jilljac in https://github.com/microsoft/vscode/issues/106141

- VSCode Version: 1.49.0-insider
- OS Version: Mac OS Catalina 10.15.6 (19G2021)

Steps to Reproduce:

1. Load pandas dataframe from local file
2. Sometimes when loading, file not found. Requires kernel restart to fix

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by greazer** [comment]
Is this still happening? Seems like we may have fixed it but Claudia was trying to re-repro it?
