### ISSUE TITLE
Blank View with Long Jupyter Notebook

### ISSUE THREAD

**Issue by rezkies** [microsoft/vscode-jupyter#1692]
I have an ipynb file with more than 6000 line code when open in notepad. Every time I open it with vscode, it just displays a blank page. If I make code little short to just 1100 line, it opens without problems.

![image](https://user-images.githubusercontent.com/17778028/91521040-fe20a900-e920-11ea-9b6e-cf0cc9cf3d05.png)

**Comment by greazer** [comment]
@rezkies, sorry for our slow response. While this notebook still seems to have trouble loading in the latest stable build of VS Code for some reason, in VS Code Insiders it does load. Insiders has rearchitected how notebooks are loaded and processed and will be released into the stable build as soon as we can. So for now I'm going to close this bug.
