### ISSUE TITLE
Code lens for python plugin in vscode disappears

### ISSUE THREAD

**Issue by martocode** [microsoft/vscode-jupyter#1694]
### Actual behavior
![image](https://user-images.githubusercontent.com/60155740/96027281-dc07c980-0e81-11eb-941d-a7b2d67b9362.png)

Run Cell | Run Above | Debug Cell Code Lens suddenly disappeared.

### Expected behavior
![image2](https://i.stack.imgur.com/G3jKu.png)

### Same problems
https://www.reddit.com/r/vscode/comments/dcdjlu/python_test_code_lens_doesnt_appear_above/
https://github.com/Microsoft/vscode-python/issues/1906
### What i've tried

```
{
    "editor.codeLens": true,
    "python.dataScience.codeLenses": "python.datascience.runcell,  python.datascience.runallcellsabove, python.datascience.debugcell",
    "python.dataScience.enableCellCodeLens": true,
    "python.dataScience.codeRegularExpression": "^(#\\s*%%|#\\s*\\<codecell\\>|#\\s*In\\[\\d*?\\]|#\\s*In\\[ \\])",
    "python.dataScience.askForKernelRestart": false,
    "python.dataScience.magicCommandsAsComments": true 
}
```
- Delete plugin folder
- Complete uninstall 
- Reinstall

**Comment by greazer** [comment]
Old bug, closing.
