### ISSUE TITLE
Jupyter server started by vscode is totally internal and can't access from external

### ISSUE THREAD

**Issue by NewUserHa** [microsoft/vscode-jupyter#1695]
related: https://github.com/microsoft/vscode-python/issues/9252

issues:
* cmd: `jupyter notebook list` will not list the started notebook server by vscode.
* log(extension host) will not log the url of notebook like the related issues do.
* output window Jupyter is useless at all except display `Started kernel Python 3.8.1 64-bit` all time.

solutions:
1. the `jupyter notebook list` should output the url of the notebook.
2. the output window jupyter should display the url of the notebook.

**Comment by DonJayamanne** [comment]
Closing this issue as we haven't had enough upvotes to this issue
