### ISSUE TITLE
"Debug Cell" has unpredictable behavior

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode-jupyter#1696]
Issue Type: <b>Bug</b>

When editing a normal python file that has notebook-like cells (using the special comments #%%), clicking on "debug cell" seems to have several possible effects, which are hard to understand/predict. One of three things happened when pressing that button today:

1.  An interactive window appears, similar to when "run cell" is pressed. Simultaneously, a read-only copy of the whole file being debugged is opened, on which it is possible to set breakpoints  and step through the code (but not to edit the code).

2.  An interactive window appears, similar to when "run cell" is pressed. Simultaneously, a copy of the current cell is opened, without syntax highlighting and without the possibility to set breakpoints (but the current line is highlighted when stepping through the code with the debugger UI).

3. A popup prompting me to install debugpy appears. If I click on install, it results in an error (something like "you will need to install debugpy for debugging cells". The popup is still there despite installing debugpy (and this 3rd behavior happened *after* the previous two! so I'm really confused)

If different types of behavior are intended, then it would be good to explicitly state what triggers which behavior. If not, then please fix it ;-) 

Note that I am using the insiders edition, so it is possible that my version got updated through the day, causing the different behaviors I've observed. If so, let me know and I am happy to do more testing.

Extension version: 2020.9.111407
VS Code version: Code - Insiders 1.50.0-insider (ddc98c3f620ab1d2ecad5942ebf4736060403d67, 2020-09-25T05:35:02.163Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.15.0-112-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.30GB free)|
|Process Argv|--crash-reporter-id d0092040-d4fc-4c5d-89c1-5c594ed4fde4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: xxxx|
|OS|Linux x64 4.15.0-112-generic|
|CPUs|AMD EPYC 7281 16-Core Processor (12 x 2100)|
|Memory (System)|58.98GB (0.46GB free)|
|VM|0%|
</details>

**Comment by greazer** [comment]
@ldorigo, sorry for the long lack of response, but what you're seeing for #2 is not expected behavior (i.e. it's a bug). We've seen this in other situations and have fixed them. So by now you may or may not still be seeing strange behavior.

Note that the debugpy package is required to be installed in your current environment when trying to debug a script cell. We have had bugs where we attempt to install that package, but we wind up installing it to the wrong environment. Thus you'd continually see the prompt to reinstall. 

I'm going to close this for now. Please reopen if you're still experiencing problems.
