### ISSUE TITLE
Lots of orphaned progress notifications after interactive window fails to open

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#1698]
Issue Type: <b>Bug</b>

**Repro**
Same initial steps as microsoft/vscode-python#14509:

1. Install python extension
1. Run something in the python terminal
1. Now open python interactive window using `run in interactive window`
1. See alert about installing `ipykernel`
1. Click button to install

The install should never complete. Now:

1. Click the cancel buttons on the install notifications.
1. See some error notifications
1. The interactive window closes
1. Click on VS Code's notifications

**Bug**
There are still progress tasks running:

<img width="1924" alt="Screen Shot 2020-10-24 at 12 11 11 PM" src="https://user-images.githubusercontent.com/12821956/97091668-4fcc7380-15f2-11eb-8854-fd5f4f82b9f0.png">

Specifically `Connecting to IPython kernel: Fetching Kernels` and `Executing Cell`. I don't seem to be able to cancel or dismiss either of these

Extension version: 2020.9.114305
VS Code version: Code - Insiders 1.51.0-insider (7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9, 2020-10-23T07:32:22.213Z)
OS version: Darwin x64 19.6.0

**Comment by DonJayamanne** [comment]
Should not be an issue anymore, we've refactored this code.
Moving to validate.
