### ISSUE TITLE
Change cell toolbar button order

### ISSUE THREAD

**Issue by jakekara** [microsoft/vscode-jupyter#1704]
Apologies if this is a dupe. New to this project.

I think the switchCellType button on the Jupyter Notebook interface should be the first button (before runCell). This button persists for both Markdown and Code cells, so putting it first would prevent it from "moving" when you click it. Maybe this was a deliberate design decision, but it feels a little broken to me.

Here's what I'm suggesting:

1. The Markdown cell wouldn't look any different.

<img width="286" alt="Screen Shot 2020-09-10 at 7 26 33 PM" src="https://user-images.githubusercontent.com/10201883/92823688-9300b900-f39b-11ea-9c3c-7a695927b0a9.png">

2. The Code cell would look like this:

<img width="299" alt="Screen Shot 2020-09-10 at 7 26 28 PM" src="https://user-images.githubusercontent.com/10201883/92823690-93994f80-f39b-11ea-8410-df0541e392bd.png">

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed with new native support for editing notebooks starting with v1.59 of VS Code. If this issue continues to occur in the latest build of VS Code, please reopen or enter a new issue.
