### ISSUE TITLE
Cell print output loses whitespace when rendering after time delay

### ISSUE THREAD

**Issue by dperlman** [microsoft/vscode-jupyter#1705]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Paste the following code into a fresh new Jupyter notebook and run it:
```python
y="hello, "
print(y, end='')
print('endingtest')
print(y, end='')
time.sleep(1)
print('endingtest')
```

## Actual behavior
```
hello, endingtest
hello,endingtest
```
<img width="330" alt="Screen Shot 2020-08-27 at 3 02 56 PM" src="https://user-images.githubusercontent.com/8398233/91500063-8d718200-e877-11ea-840b-734bda0f0f1c.png">

The second pair of print statements produces different output than the first, even though the only difference is a short delay between them. 

## Expected behavior
```
hello, endingtest
hello, endingtest
```

The short delay should not affect the output.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.8.103604
-   **VS Code version:** 1.48.2
-   **Setting python.jediEnabled:**  false
-   **Setting python.languageServer:** Microsoft
-   **Python and/or Anaconda version:** 3.8.2
-   **OS:** Mac
-   **Virtual environment:** conda 

Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

## Python Output

I do not think this is relevant to this problem but if the problem does not reproduce I am happy to provide.

**Comment by greazer** [comment]
This works in the latest VS Code insiders build.
