### ISSUE TITLE
Progess bars not updating properly in Python Interactive Window on macOS

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode-jupyter#1708]
## Steps to cause the bug to occur

1. Create a model that fits using a progress bar to monitor progress, such as Tensorflow.
2. Run model in interactive window with progress bar enabled.

## Actual behavior

The progress bar does not update properly, printing a new line with every update, rather than using the existing line. Here is a screen shot:

<img width="957" alt="Screen Shot 2020-09-15 at 12 46 20 PM" src="https://user-images.githubusercontent.com/81476/93245931-a2905100-f751-11ea-8cfe-bc11f9a8e524.png">

## Expected behavior

A progress bar that updates in the same line.

### Your Jupyter and/or Python environment

-   **Jupyter server running:** Local
-   **Extension version:** 2020.8.108011 
-   **VS Code version:** 1.49.0
-   **Setting python.jediEnabled:** false
-   **Setting python.languageServer:** Pylance
-   **Python and/or Anaconda version:** Python 3.8.5, Anaconda 3
-   **OS:** macOS Catalina
-   **Virtual environment:** conda 

## Python Output

See screen shot above.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by greazer** [comment]
Closing due to age. Please reopen if this problem still occurs in the latest build of VS Code Insiders
