### ISSUE TITLE
Update Display Data disappears when display and display.update are in the same cell

### ISSUE THREAD

**Issue by hsm** [microsoft/vscode-jupyter#1710]
# Bug: Notebook Editor, Interactive Window, Editor cells

This bug seems to be related to https://github.com/microsoft/vscode-python/pull/10874 . Note that the consequence of this bug is that VSCode cannot be used effectively with the current version of the FastAI library.

## Steps to cause the bug to occur

```
# %%
from time import sleep

from IPython.display import Markdown

# %%
dh = display(display_id=True)

# %%
dh.update(Markdown('`Display Update Fun 1`'))
sleep(3)
dh.update(Markdown('`This update remains`'))
# %%
dh = display(Markdown('`Display Update Fun 2`'), display_id=True)
dh.update(Markdown('`This update is supposed to remain`'))
sleep(3)
```

## Actual behavior

```
Direct kernel connection
Python version:
3.7.3 (default, Apr 24 2020, 18:51:23) \n[Clang 11.0.3 (clang-1103.0.32.62)]
[1] from time import sleep...
[2] dh = display(display_id=True)
`This update remains`
[3] dh.update(Markdown('`Display Update Fun 1`'))...
[4] dh = display(Markdown('`Display Update Fun 2`'), display_id=True)...
`Display Update Fun 2`
```
## Expected behavior

```
Direct kernel connection
Python version:
3.7.3 (default, Apr 24 2020, 18:51:23) \n[Clang 11.0.3 (clang-1103.0.32.62)]
[1] from time import sleep...
[2] dh = display(display_id=True)
`This update remains`
[3] dh.update(Markdown('`Display Update Fun 1`'))...
[4] dh = display(Markdown('`Display Update Fun 2`'), display_id=True)...
`This update is supposed to remain`
```
### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.8.105369
-   **VS Code version:**  1.48.2
-   **Setting python.jediEnabled:** false
-   **Setting python.languageServer:** PyLance
-   **Python and/or Anaconda version:** 3.7.3
-   **OS:** Mac
-   **Virtual environment:** venv

## Python Output

There was no output.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by avylove** [comment]
The workaround wasn't working for me, but the new version did. There was some hanging with new interface at times, but this particular issue looks like it's resolved there.

**Comment by avylove** [comment]
I'm confused to why this was closed, particularly with no comment. While it seemed to work in the insiders version, that doesn't look like it's made it to general release yet. Please leave open until issue is deployed in a general release.
