### ISSUE TITLE
Notebook Editor: julia starts with wrong cwd on remote host

### ISSUE THREAD

**Issue by pfarndt** [microsoft/vscode-jupyter#1712]
# Bug: Notebook Editor: julia starts with wrong cwd on remote host

## Steps to cause the bug to occur

Opening a (Julia) .ipynb on a remote host (via Remote-SSH) starts a (remote) julia kernel as expected. The kernel process gets a `--project=@.`, which is good and tells julia to search for an environment defining `Project.toml` in the `cwd`. 

However, the actual working directory of the julia kernel is set to my home directory on the remote host and not the directory of the ipynb. This way the kernel starts up with the wrong julia environment, which is very inconvenient (i.e. useless) and inconsistent to the behavior in jupyter lab.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** N/A
-   **Extension version:** 2020.8.109390 (15 September 2020)
-   **VS Code version:** 1.49.0

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by rchiodo** [comment]
The julia extension for VS code should be handling running Julia kernels now.
