### ISSUE TITLE
Error: Module fileupload, semver range is not registered as a widget module

### ISSUE THREAD

**Issue by purskills** [microsoft/vscode-jupyter#1713]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local | Remote | N/A
-   **Extension version:** 20YY.MM.#####-xxx
-   **VS Code version:** #.##
-   **Setting python.jediEnabled:** true | false
-   **Setting python.languageServer:** Jedi | Microsoft | None
-   **Python and/or Anaconda version:** #.#.#
-   **OS:** Windows | Mac | Linux (distro):
-   **Virtual environment:** conda | venv | virtualenv | N/A | ...

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by max-endeavour** [comment]
Have the same issue, just installed fileupload on Linux 18.04 following the exact procedure from [here](https://github.com/peteut/ipython-file-upload/blob/master/README.rst) and got the error in VSCode.
Let me know if there is any information that could help you debug this.

Cheers

**Comment by IanMatthewHuff** [comment]
@max-endeavour Thanks for commenting. I think that we would want the exact version of fileupload that you installed, and then do the following:

1. In VS Code settings set Jupyter: Logging Level to 'debug'
2. Re-run the scenario that creates the error
3. Pull everything in the VS Code output tab under the 'Jupyter' dropdown. That's all our advanced debug output. If you save that in a file an attach it to a comment here that would be helpful for our investigation.
