### ISSUE TITLE
Jupyter Hub with base_url set cannot be connected to.

### ISSUE THREAD

**Issue by tariktourougui** [microsoft/vscode-jupyter#1716]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. set the `c.JupyterHub.base_url = '/jupyter/'` in `jupyterhub_config.py`
2. set `"python.dataScience.jupyterServerURI": "http://localhost:8000/jupyter/"` in `settings.json`
3. try to logging with login/password authentication
## Actual behavior
Unable to connect as the jupyter server is unable to handle the authentication request
```
08:55:07.032 - error: [ConfigProxy] 404 POST /hub/login?next=
[I 2020-09-10 08:55:07.058 JupyterHub log:174] 200 GET /jupyter/hub/error/404?url=%2Fhub%2Flogin%3Fnext%3D (@127.0.0.1) 22.10ms
08:55:07.067 - error: [ConfigProxy] 404 POST /hub/api/authorizations/token
[I 2020-09-10 08:55:07.070 JupyterHub log:174] 200 GET /jupyter/hub/error/404?url=%2Fhub%2Fapi%2Fauthorizations%2Ftoken (@127.0.0.1) 1.49ms
```

## Expected behavior
connect and access to the remote kernels

### Your Jupyter and/or Python environment
Running JupyterHub version 1.1.0 with python3.6
_Please provide as much info as you readily know_

-   **Jupyter server running:** | Remote |
-   **Extension version:** v2020.8.108011
-   **VS Code version:** 1.48.2
-   **Setting python.jediEnabled:**  false
-   **Setting python.languageServer:**  None
-   **Python and/or Anaconda version:** None
-   **OS:** Windows 
-   **Virtual environment:** | N/A | 

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by DonJayamanne** [comment]
Note: We can check the response headers to determine if the server is running jupyter Jub `z-Jupyterhub-Version`
Such headers are commonly used to inspect the remote web server/application/environment hosting the websites. Very rarely 
 hidden/remoted, e.g. Banking websites.

**Comment by DonJayamanne** [comment]
Its been almost 2 years since this was filed and we've only have one upvote on this issue.
