### ISSUE TITLE
Changes to .env need a restart of vscode to become active in the Interactive Window

### ISSUE THREAD

**Issue by ARF1** [microsoft/vscode-jupyter#1722]
# Bug: Interactive Window

## Steps to cause the bug to occur
1. Add an entry to `.env`: e.g. `PYTHONPATH=../libraries/my_library;${PYTHONPATH}`
2. Launch the interactive window
3. Run `import sys; sys.path`.
4. Close interactive window (or not, as you wish)
5. Change the entry to `.env`: e.g. `PYTHONPATH=../libraries/my_library_FOO;${PYTHONPATH}`
6. Launch the interactive window
7. Run `import sys; sys.path`.

## Actual behavior
Entry from `.env` stays on `my_library` even after it was changed in `.env` to `my_library_FOO`.

## Expected behavior
Make changed `.env` entries available in Interactive Window. (Or alternatively show a pop-up after `.env` was modified with the option to restart the server for the Interactive Window.

### Your Jupyter and/or Python environment
*Please provide as much info as you readily know*
- **Jupyter server running:**                       Local
- **Extension version:**                               2020.1.58038
- **VS Code version:**                                1.41.1
- **Setting python.jediEnabled:**               false
- **Python and/or Anaconda version:**     3.8.1
- **OS:**                                                     Windows
- **Virtual environment:**                          conda

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by tbenthompson** [comment]
I just wanted to note that changes to my `.env` are not active in a notebook *even after a VSCode restart*. It seems like the only way to update environment variables set this way is to completely re-create my conda environment. Perhaps there's some kind of caching going on? This is quite surprising so maybe I'm doing something wrong.

**Comment by DonJayamanne** [comment]
This should be fixed with https://github.com/microsoft/vscode-jupyter/pull/10843
Please install the latest pre-release version of the Jupyter extension into VS Code insiders and tet this tout.
If this problem still prerists, please feel free to reopen this issue or ping us and we'll do the same
