### ISSUE TITLE
ipynb not opening when resolving merge conflicts 

### ISSUE THREAD

**Issue by MaxwellWibert** [microsoft/vscode-jupyter#1734]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Attempt to merge between two divergent branches with merge conflicts in an ipynb file from terminal.
2. Try to resolve these conflicts in code by opening that file in vscode

## Actual behavior
Nothing but a blank screen will render on trying to open the ipynb file. 
## Expected behavior
Ideally show in rendered cell format. Alternatively, at least show merge conflicts in raw ipynb form

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local 
-   **VS Code version:** 1.44.2

-   **Python and/or Anaconda version:** python 3.
-   **OS:**  Mac 
-   **Virtual environment:** conda 

## Developer Tools Console Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by dav-ell** [comment]
Why was this closed? This is still an issue for me. I can't resolve ipynb merge conflicts in VSCode currently, as they produce an error and don't open, whether the Python extension is enabled or not.

**Comment by rchiodo** [comment]
This was closed because we never repro'd it. Your issue may be this one:
https://github.com/microsoft/vscode-jupyter/issues/633.

**Comment by tbrodbeck** [comment]
I can +1 the request to reopen this issue. Currently it is not possible to open a notebook for me at all (nothing happens) when there is a merge conflict in it. It would be great to see the Javascript Code then to perform a merge

**Comment by tbrodbeck** [comment]
I can +1 the request to reopen this issue. Currently it is not possible to open a notebook for me at all (nothing happens) when there is a merge conflict in it. It would be great to see the Javascript Code then to perform a merge

**Comment by rchiodo** [comment]
@tbrodbeck your issue should be #633. The merge conflict headers is preventing the notebook editor from opening. However #633 is really about how the notebook editor shouldn't be opening at all.

You might try using VS code insiders instead. It has built in diffing support for notebooks so it shouldn't have a problem with the merge conflict headers.

**Comment by tbrodbeck** [comment]
Ok thanks for the elaboration!
