### ISSUE TITLE
Unsaved Notebook data is lost on exit

### ISSUE THREAD

**Issue by dimitry-ishenko** [microsoft/vscode-jupyter#1746]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Launch VSCode.
2. Create new blank Notebook (Ctrl+Shift+P then enter Python: Create Blank New Jupyter Notebook)
3. Modify the notebook (eg, enter `print("Hello abyss!")` in the cell and press Ctrl+Enter)
4. Close VSCode.
5. Re-launch VSCode.
6. Witness your work gone into the abyss.
7. Optional: Smash computer screen with heavy object.

## Actual behavior

VSCode blissfully discards any unsaved changes.

## Expected behavior

Either (a) an "Are you sure?"-type confirmation dialog is shown on exit; or (b) the file is restored, when VSCode is relaunched, which is what's done with other file types.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** N/A
-   **Extension version:** v2020.4.76186
-   **VS Code version:** 1.45
-   **Setting python.jediEnabled:** false
-   **Python and/or Anaconda version:** python 3.8.2 (no Anaconda)
-   **OS:** Ubuntu 20.04 LTS
-   **Virtual environment:** N/A

## Developer Tools Console Output

Nah... that ain't me

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by msveshnikov** [comment]
Just for everyone information - I was able to find my unsaved notebook with 2 days of work in "C:\Users\user\Local Settings\Temp\"
