### ISSUE TITLE
Jupyter: Create GitHub Issue enhancements

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#176]
Either make it 1. a webview or 2. a quickpick / input box series

Also, fix some bugs:
- [ ] Submit GitHub Issue command should never be visible
- [ ] Currently autopopulated # of jupyter notebooks is wrong, this actually counts the number of active kernel connections
- [ ] Use VS code API instead of our custom markdown

**Comment by DavidKutu** [comment]
Joyce already added something similar to this.
Also, closing in favor of #7035
