### ISSUE TITLE
[ipynb][Solarized Light] Markdown text color while editing

### ISSUE THREAD

**Issue by dataludus** [microsoft/vscode-jupyter#1766]
Issue Type: <b>Feature Request</b>

In a *python Notebook*, when I use *Solarized Light Color theme* and edit a Markdown cell, the text color is the same when I select the text or not, i.e. there is no selection highlighting. I think is only a color issue in the theme and should be changed.

This is a screenshot while editing the markdown cell (a few words in the paragraph are selected):
![Screenshot_20200511_121721](https://user-images.githubusercontent.com/16387977/81578522-4a9ba500-9381-11ea-91ee-7d5caf285043.png)

This is with another color theme:
![Screenshot_20200511_121908](https://user-images.githubusercontent.com/16387977/81578714-90586d80-9381-11ea-9096-1f773124e4e6.png)

Extension version: 2020.4.76186
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 5.6.10-3-MANJARO

**Comment by Episkiliski** [comment]
Hi,

this issue is still happening. Anybody has the same problem?

Thanks!
