### ISSUE TITLE
unstable jumping behaviors of interactive window

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#1781]
Since the interactive window is able to scroll past the end, it has been acting very unstable:

1. If I have a DataFrame preview and half of that preview is covered, sometimes the other half would jump up and show on the screen if I click anywhere on the DataFrame.

2. If I click somewhere in a DataFrame above, sometimes the interactive window will jump to the last cell output in the bottom. 

3. Mentioned in https://github.com/microsoft/vscode-python/issues/11349 interactive window won't jump to the latest output if I'm looking something way up in the interactive window outputs. I have to scroll down every single time to see it. I was told this is by design but I'm not quite sure if this makes much sense. If I run a new cell, that means wanna see its output. I think a more reasonable thing is to add a toggle for this or add an interactive window anchor icon on the top to control that.

**Comment by StevenLi-DS** [comment]
@rchiodo This happens again and the cells in interactive windows jump around again, but I haven't found a pattern to reproduce it at this moment. Have you observed it under `v2020.12.414227025`

**Comment by rchiodo** [comment]
The repro I have is to output something that renders itself using javascript. Like a LaTex equation. The scroll happens before the render sometimes and then it ends up in the wrong spot.

**Comment by StevenLi-DS** [comment]
@rchiodo Here's what I'm experiencing now: https://github.com/microsoft/vscode-jupyter/issues/4276#issuecomment-755637209
