### ISSUE TITLE
Port PRs/Code from Python to Jupyter for Joyce

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#180]
Data viewer/PyTorch
- [x] https://github.com/microsoft/vscode-python/pull/14244
- [ ] https://github.com/microsoft/vscode-python/pull/14269

Github actions updates
- [x] https://github.com/microsoft/vscode-python/pull/14263
- [x] https://github.com/microsoft/vscode-python/pull/14286

Bug fixes
- [x] https://github.com/microsoft/vscode-python/pull/14332
- [x] https://github.com/microsoft/vscode-python/pull/14336

and future PRs

**Code:**
* [x] GitHub Action used to assign github issues & related files 
* [x] GitHub Action used to run VS Code tests (in VSC insiders & stable) - created by Don
* [x] GitHub Action used to run Functional tests - the one created by Rich
* [x] Don to get list of PRs/commits related to native notebooks

**Comment by DavidKutu** [comment]
Validated, looks like everything is moved to jupyter
