### ISSUE TITLE
Create New Blank Jupyter Notebook' resulted in an error (command 'python.datascience.createnewnotebook' not found)

### ISSUE THREAD

**Issue by ogola89** [microsoft/vscode-jupyter#1803]
Issue Type: <b>Bug</b>

The problem is created when two things happen:
1.) Run 'Create New Blank Jupyter Notebook' from command Pallette

2.) Open *.ipynb jupyter notebook.

It worked once, but hasn't worked again. I don't know how to identify what is going on. I have disabled other Jupyter-like extensions.

Extension version: 2020.4.74986
VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (0.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by andvsilva** [comment]
Hi, 

I have this problem on Linux deepin 4.15.0-30deepin-generic #31 SMP Fri Nov 30 04:29:02 UTC 2018 x86_64 GNU/Linux

I am using the anaconda Command line client (version 1.7.2)

Error:
Command '.NET Interactive: Create new blank notebook' resulted in an error (command 'dotnet-interactive.newNotebook' not found)

Installed  'dotnet-interactive.newNotebook' extension, But this does not fix the problem.

Someone knows how to fix this issue? 

Thanks in advance.
![DeepinScreenshot_select-area_20201130145600](https://user-images.githubusercontent.com/66761171/100646814-4e8f1480-331d-11eb-86f8-5d2cf07dbe2a.png)

**Comment by DonJayamanne** [comment]
@andvsilva 

> Command '.NET Interactive: Create new blank notebook' resulted in an error (command 'dotnet-interactive.newNotebook' not found)

This  isn't a command contributed by the Jupyter extesnion.
Please report this issue against the `.NET Interactive Notebooks` extension repo https://github.com/dotnet/interactive.
