### ISSUE TITLE
Matplotlib inlinebackend = Retina doesnt work

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-jupyter#1892]
https://ryanwingate.com/visualization/matplotlib/inline-backend-on-retina-displays/

It should render matplotlib plots at a high resolution but keep it the same size, but in VS Code it makes all the plots bigger.

**Comment by raiskila** [comment]
Not sure if this is the correct issue given it was transferred, but I'll post here anyway.

Is there currently a solution for getting pixel-perfect 2x plots in the VSCode Jupyter extension on 2x displays?
