### ISSUE TITLE
Add support for Rise slideshows in VSCode

### ISSUE THREAD

**Issue by aaronsmith1234** [microsoft/vscode-jupyter#1956]
# Feature: Notebook Editor, Interactive Window, Python Editor cells
## Description
[Rise slideshows](https://rise.readthedocs.io/en/stable/) are really cool ways to show off and share a notebook with others. Native support for them in Vscode would be really cool! They're the only reason I still see a need to use Jupyters interface.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by hugocool** [comment]
There is a vscode plugin called [vscode-reveal](https://marketplace.visualstudio.com/items?itemName=evilz.vscode-reveal), this plugin however only works on markdown files.
In the vscode insiders edition it (vscode-reveal) also recognises the markdown in jupyter notebooks, however this is very buggy and nowhere near the quality of [RISE](https://github.com/damianavila/RISE).
If this buggy behaviour is fixed such that vscode-reveal has the same capabilities of RISE, it allows one to make presentations from jupyter notebooks and preview them inside of vscode. It does not have to be built into vscode.
