### ISSUE TITLE
qgrid widget is not able to load in vscode, but is able to in notebooks

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#1974]
Loads with the same kernel in jupyter notebook and shows the grid:
![image](https://user-images.githubusercontent.com/812783/79620891-5ff51a80-80c6-11ea-8954-8ddd6eb117eb.png)

[qgridvscode.log](https://github.com/microsoft/vscode-python/files/4495629/qgridvscode.log)
[qgridwegview.log](https://github.com/microsoft/vscode-python/files/4495630/qgridwegview.log)

I have the env still so ask and I can give a pip list.

**Comment by WinstonDodson** [comment]
Just to add that this same issue exists in the VS Code - Insider native notebooks as well.
