### ISSUE TITLE
debug cell function does not work

### ISSUE THREAD

**Issue by rustedwizard** [microsoft/vscode-jupyter#2043]
Issue Type: <b>Bug</b>

I create a simple .py file use #%% created a code cell. 
Run cell works perfectly, but when click debug cell nothing happens and status bar shows executing cell.

Extension version: 2020.3.71659
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (18.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by tshemeng** [comment]
Another Situation: vscode path contains CJK character.
