### ISSUE TITLE
Closing interactive window does not kill running script

### ISSUE THREAD

**Issue by mattbierner** [microsoft/vscode-jupyter#2185]
Issue Type: <b>Bug</b>

**Repro**
1. Create a file:

```py
import time

i = 0

while True:
    time.sleep(1)
    print(i)
    with open('x', 'w') as f:
        f.write(str(i))
        i += 1
```

1. Use the `Run current file interactive window` command
1. Then close the interactive window

**Bug**
Script is still running (check `x`)

I can't find any way to kill the script. 

Also, now if I use `Run current file interactive window`, the window just has a loading indicator forever

Extension version: 2020.2.64397
VS Code version: Code - Insiders 1.44.0-insider (b0791e5236f462fbb785e9a00319705607cefb9d, 2020-03-10T11:17:54.705Z)
OS version: Darwin x64 19.3.0

**Comment by seyeeet** [comment]
Well im on version 1.55.2 and still have this issue.
