### ISSUE TITLE
With no python extension, an invalid kernel will just timeout instead of showing an error

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#219]
Create a kernelspec.json that is invalid (or edit your only one). Something like the path to python is invalid.

Start without python extension and attempt to use that kernel. 

Expected:
Immediately gives an error stating invalid python

Actual:
Timeout waiting for heartbeat.

We don't handle the ENOENT when spawning the kernel process.

**Comment by greazer** [comment]
@rchiodo, reactivate if this is still an issue in native notebooks.
