### ISSUE TITLE
CDN download unit tests seem to randomly fail on Azure

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#227]
Originally filed here
https://github.com/microsoft/vscode-python/issues/11442

The following test has been disabled https://github.com/DonJayamanne/vscode-jupyter/blob/7d068b75af518ef1772f4ac33ae512286026fea0/src/test/datascience/ipywidgets/cdnWidgetScriptSourceProvider.unit.test.ts#L51

**Comment by rchiodo** [comment]
I guess we don't need these. Haven't had any bugs with this in forever. Just closing this issue.
