### ISSUE TITLE
"Disable Jupyter Auto Start" setting does not work

### ISSUE THREAD

**Issue by rholland** [microsoft/vscode-jupyter#2292]
Unchecking the settings box does not lead to Jupyter auto starting.  Jupyter does not start running until I run a cell whether the box is checked or not.

Win 10
latest python extension
latest vscode update
Anaconda 3.7

**Comment by Marines1775** [comment]
Maybe this isn't the proper place for a comment,  but why would you combine Python and Jupyter together?   Speaking for myself, although I've seen allot of other posts asking how to disable Jupyter.  VSC is Microsofts product and the Python extension is there's also but combining the two doesn't make sense.   Anaconda is probably the dominant platform / installation for Jupyter Notebook
