### ISSUE TITLE
New version tries to pip install kernelspec

### ISSUE THREAD

**Issue by Louis-DR** [microsoft/vscode-jupyter#2308]
vscode version : 1.42.0
vscode-python version : 2020.2.62710
python version : 3.7.3 64-bits
os : windows 10
no venv, no anaconda

I just updated VScode and the python extension. When trying to run a Jupyter notebook or a Jupyter cell, it tries to start a Jupyter server but fails and gives an error notification asking to install more dependencies. When pressing the "Install" button, it tries to pip install kernelspec.

```
"C:/Program Files/Python37/python.exe" c:/Users/loudur01/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/shell_exec.py "C:/Program Files/Python37/python.exe" -m pip install -U kernelspec --user C:/Users/loudur01/AppData/Local/Temp/tmp-14796WOIAB7kweneN.log
Executing command in shell >> C:/Program Files/Python37/python.exe -m pip install -U kernelspec --user
Collecting kernelspec
 Could not find a version that satisfies the requirement kernelspec (from versions: )
No matching distribution found for kernelspec
You are using pip version 19.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "c:/Users/loudur01/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/shell_exec.py", line 26, in <module>
    subprocess.check_call(shell_args, stdout=sys.stdout, stderr=sys.stderr)
  File "C:\Program Files\Python37\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
```
I tried uninstalling and reinstalling jupyter, rebooting the computer, running as admin.

Edit : rolling back to 2020.1.58038 and it works again

**Comment by Quantium** [comment]
Same issue here. 

I just selected an environment in the VSCode footer to fix it.

![pic 2020-11-26 at 9 27 15](https://user-images.githubusercontent.com/2090436/100368785-a2ba9180-2fc9-11eb-9f70-6abfaa0e6543.png)
