### ISSUE TITLE
Kernel from a notebook is not used when starting up

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#235]
Dont install the python extension
Open a notebook that is pointing to a custom kernel
Run the notebook

The first kernel on the machine is used instead of the one in the notebook.

**Comment by IanMatthewHuff** [comment]
Validated. I remember having this issue before. Both my julia and java notebooks correctly used the right kernels, when before they used to pull some random kernel that happened to be first in the list. Python extension not installed.
