### ISSUE TITLE
Notebooks are sometimes corrupted (made unloadable in Jupyter or Jupyter Lab)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#2487]
We might need to create a notebook builder to ensure we never corrupt the notebook file. 
This would be responsible for editing/creating notebook JSON (e.g. create a new cell that returns the JSON or inserts a new cell into the specific spot, edits a cell by appending the output...).

By corrupt i mean, our code creates/modifes an ipynb file such that:
* It cannot be opened or displayed correctly in jupyter notebooks or jupyter labs.
* It doesn't display displays correctly in jupyter notebooks or jupyter labs.

We seem to do this every once in a while (incorrectly formatted html/markdown, or the like).
Issues I've seen:
* execution count not stored correctly in ipynb
* latex not formatted/escaped correctly
* multiline strings not formatted correctly
* html strings not escapted/formatted correctly
* error information (output) not stored correctly.
* Other issues with other attributes missing

See https://nbformat.readthedocs.io/en/latest/api.html#nbformat.validate

**Suggestions:**
* We could run nbformat.validate in the background and see if we break the notebook at the user end (capture as telemetry and see how bad it is)
    * We could always try to ship our own copy of nbformat (little benefit)
* Create our own validator in nodejs (so we can run this everytime, however, the problem still remains - when do we run this? If on user machines, its too late with the only benefit of telemetry)
* Ensure the type definitions are used appropriately and JSON is validated accordingly, instead of casting to `any` and the re-casting to hide compiler warnings.
* Personally I think we need a notebook builder/writer that'll encapsulate the logic of creating/editing cells (something to wrap up a model as described here https://github.com/microsoft/vscode-python/issues/9255#issue-541253579)
    * This will ensure we create cells in one place with the right structure.
    * E.g. when we need to create a markdown cell, the attributes have been initialized correctly (i.e. create JSON)
    * Similarly when updating cells. This way the logic is in one place.
    * Right now editing is done in different parts of the code, which I don't think is correct (specially if there's a schema that needs to be adhered to).
* Others

@rchiodo @IanMatthewHuff @DavidKutu Thoughts

**Comment by JamesDConley** [comment]
I'm still having issues with this. I had a weird import error on pandas (referenced DLL and numpy), previously I was able to fix it by exiting the notebook and reloading it.  When I exited out of it I accepted the prompt to save changes, and then I could no longer open the file.  After I deleted the JSON for the first cell that contained the import and error I was able to open it again.

**Comment by IanMatthewHuff** [comment]
@JamesDConley Thanks for helping to report this issue. Could you please open up a new issues here in the vscode-jupyter repo with your info? This older issue was for a specific corruption cause, so I don't want to reactive the old bug for a new and probably different issue. A new issue will help us look into this.
