### ISSUE TITLE
Implement full Jedi LS

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#249]
This is required to get a middleware piece for notebooks to run. The work here is actually in the python extension though.

**Comment by greazer** [comment]
LS for native notebooks rollout is tied to Pylance. Per the above comment the decision is to worry about Jedi after general native notebook release.

**Comment by rchiodo** [comment]
Actually the new Jedi LSP should just make this work. The notebook intellisense is not tied to pylance, but rather an LSP based language server.
