### ISSUE TITLE
Implement ipywidget support to same level as webview notebooks

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#251]

**Comment by rchiodo** [comment]
Make sure you have the latest insiders when validating

**Comment by IanMatthewHuff** [comment]
Validated.

This worked for me across the range of stuff that I was testing with (basic widgets, py3js, qgrid, bqplot).

I did notice one fairly important issue that I logged with #4095. But that seems like a follow up issue / bug fix. The basic widget functionality all seems validated.

**Comment by Kingwl** [comment]
Cool. Thanks!
