### ISSUE TITLE
Error: Activating Python 3.6.5 64-bit ('base': conda) to run Jupyter failed with Error: spawn cmd ENOENT.

### ISSUE THREAD

**Issue by MuSamiNaf** [microsoft/vscode-jupyter#2510]
# Bug: Error: Activating Python 3.6.5 64-bit ('base': conda) to run Jupyter failed with Error: spawn cmd ENOENT.

## Steps to cause the bug to occur
1. Open or Create a new IPYNB file.
2. Run Cell

## Actual behavior
Error: Activating Python 3.6.5 64-bit ('base': conda) to run Jupyter failed with Error: spawn cmd ENOENT.

GIF:
<img src="https://s5.gifyu.com/images/errorc578506b4f45dcd6.gif" alt="errorc578506b4f45dcd6.gif" border="0" />

## Expected behavior
The cell to run and display a correct output.

### Your Jupyter and/or Python environment
*Please provide as much info as you readily know*
- **Jupyter server running:**                       Local
- **Extension version:**                               2020.1.55524-dev
- **VS Code version:**                                1.41.1
- **Setting python.jediEnabled:**               false
- **Python and/or Anaconda version:**     3.6.5
- **OS:**                                                     Windows 10
- **Virtual environment:**                          conda

## Developer Tools Console Output
https://pastebin.com/rQf1DzRX

## VSCode Settings

```json
{
    "python.pythonPath": "C:\\Users\\AtOmiC.ADMINRG-7UQ6VS4\\Anaconda3\\python.exe",
	"terminal.integrated.env.windows": {
	"PATH": ""},
}
```

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by bakharia** [comment]
Can you please let me know where exactly did you add that?
I ran the same tests and got the same output. Did you add %SystemRoot%/system32 to environments variable or in settings.json or both?
