### ISSUE TITLE
Implement plot viewer

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#252]

**Comment by DonJayamanne** [comment]
Discussed with PMs, not required for GA, will ask users to use matplot lib widget instead.

**Comment by sztal** [comment]
Hi, do you already know when plot viewer may be available in VS Code insiders builds?

**Comment by DonJayamanne** [comment]
@sztal 
For now is it possible for you to use [ipympl](https://github.com/matplotlib/ipympl)?
* pip install ipympl`
* Then add the following cell magic
* The output plot will allow you to zoom in/out, pan across, save as png, etc

Does this work for you?

**Comment by sztal** [comment]
Sure, it works! Thanks a lot. And just one more question by the way, is there a way to save plot from the `ipympl` widget as SVG (or PDF) file? I see that default behavior is to render a PNG.

**Comment by DonJayamanne** [comment]
Thanks for confirming that ipympl meets you needs
For saving to other formats, please see here https://github.com/matplotlib/ipympl/issues/14

**Comment by claudiaregio** [comment]
Let's try this: 
1. Render a button within the cell output area that will "Open in Plot Viewer"
The plot viewer will come with a toolbar that just has "Save As". Will function the same as "Save As" below, will not come with zoom in/out. 

2. Render a second button within the cell output area that will say "Save As"
The second button will open the user's file directory and they can save image with their preferred name and either pdf or the original format of the image.
