### ISSUE TITLE
Ensure all rendering libraries that worked with webviews, work with native notebooks (Plotly wasn't working for me)

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#256]

**Comment by rchiodo** [comment]
What else would this be besides plotly? Vega? Altair?

**Comment by rchiodo** [comment]
This is not working for anything but plotly. Vega and Altair fail to run.

**Comment by DonJayamanne** [comment]
Latex cells with magics, as follows:
```
%%latex
$sin(x)/x$
```

> This is not working for anything but plotly. Vega and Altair fail to run.

Works for Altair for me.
What's wrong with Vega and Altair? Please could you provide code sample and errors.

**Comment by rchiodo** [comment]
This doesn't work if you run it in native, works fine in old webview.
```python
# Cell 1
import altair as alt
import pandas as pd

# Cell 2
df = pd.read_json('cars.json')

alt.Chart(df).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
)
```

Attaching cars.json
[cars.zip](https://github.com/microsoft/vscode-jupyter/files/5811425/cars.zip)

**Comment by rchiodo** [comment]
Note: It works if you just open a notebook. Doesn't work if you run it. Same results for vega and altair.

I got a bunch of notebooks from here:
https://github.com/vega/ipyvega/tree/master/notebooks

**Comment by rchiodo** [comment]
Sorry altair does work. I had the wrong bits. Vega doesn't.
