### ISSUE TITLE
DS: Support jupyter keyboard shortcuts for cell manipulation, et al. 

### ISSUE THREAD

**Issue by Econ808** [microsoft/vscode-jupyter#2598]
## Description

It would be nice to be able to have shortcuts for copy (keybinding: C), cut (keybinding: X) and paste (keybinding: V) of notebook cells when "outside" a cell, similar to the functionality of the original Jupyter notebook project.

Also I really miss the ability to split and merge cells with a simple keybinding.

**Comment by lseongjoo** [comment]
> Thanks for the suggestion. We haven't currently implemented cut/copy/paste/split or merge, but when we'll do we'll make sure to add the default keybindings.

Thank you! We love vscode and jupyter inside.

**Comment by claforte** [comment]
This still doesn't work, at least on this non-insider release... are we still supposed to use vscode insiders? It's been >6 months...

**Comment by rchiodo** [comment]
Yes the insiders build is still where you can use keybindings for normal jupyter commands. We're about to ship a release that has even more of them enabled in insiders.

Not sure if you're asking this or not, but the keybindings won't be updated in the stable version (well until it switches to the new editor too). We're not backporting the keybindings to the older editor.

**Comment by rchiodo** [comment]
If you want to try out the new keybindings before we ship, you can install one of our latest internal vsixs. Like the one in the artifact list here:
https://github.com/microsoft/vscode-jupyter/suites/1927710168/artifacts/38000699

**Comment by claforte** [comment]
Thanks, I confirm it works in insiders. I'm trying the insiders-weekly, hopefully it's stable enough for everyday use...
