### ISSUE TITLE
Jupyter doesn't work with conda virtual environment except "base" virtual environment

### ISSUE THREAD

**Issue by elixirtrip** [microsoft/vscode-jupyter#2616]
# Bug: Notebook Editor, Interactive Window, Editor cells

Cant run jupyter notebook cell in a newly created virtual environment using conda. But it's working fine when using default virtual conda environment "base".

## Steps to cause the bug to occur
1. Create a new environment with `conda create -n my_environment python=3.6`
2. Activate a new environment `conda activate my_environment` ore by selecting it in vscode
3. Try to use jupyter notebook

## Actual behavior

![actual_begaviar_sell](https://user-images.githubusercontent.com/54764772/69989225-76e60680-1543-11ea-86e7-d2f89eff2dad.gif)

![actual_behavior_conda_env](https://user-images.githubusercontent.com/54764772/69989503-05f31e80-1544-11ea-805a-c5fa0d51c334.gif)

## Expected behavior

![axpected_behavior_jupyter](https://user-images.githubusercontent.com/54764772/69918460-86e1e580-1472-11ea-8c40-7bba56ea1e7b.gif)

### Jupyter and/or Python environment
- **Jupyter server running:**                        Local
- **Extension version:**                                2019.11.5
- **VS Code version:**                                  1.40.2
- **Python and/or Anaconda version:**     3.6.9/4.7.12
- **OS:**                                                          Mac
- **Virtual environment:**                             conda

## Developer Tools Console Output

`Error: Activating Python 3.6.9 64-bit ('machine_learning_with_real_world_projects': conda) to run Jupyter failed with Error: Command failed: . activate penv && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /Users/***/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/printEnvVariables.py
Could not find conda environment: penv
You can list all discoverable environments with 'conda info --envs'.`

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by ayushnoori** [comment]
It appears I am having the same issue. I am using a Jupyter notebook with Python code cells in VS Code. After creating a new environment, I select the appropriate Python interpreter via the VS Code GUI. I have registered the virtual environment with Jupyter using `python -m ipykernel install --user --name=myenv` and my virtual environment has the `jupyter` library installed.

I am able to use `conda activate myenv` in the terminal (Command Prompt) and run code directly in the terminal perfectly fine. Unfortunately, when attempting to run the same code in the code cell, I am unable to activate `myenv`; instead, I see that `base` is activated when I run `!conda info --envs` and `!where python`.

Has a fix been implemented for this issue? Would appreciate any suggestions. Thank you!

**Comment by DonJayamanne** [comment]
@ayushnoori Please could you file a new issue.
