### ISSUE TITLE
No docstrings in Jupyter Notebooks

### ISSUE THREAD

**Issue by jqluisneumann** [microsoft/vscode-jupyter#2652]
I am also encountered the same (similar issue). On a python file, I get the full docstrings:
image
![image](https://user-images.githubusercontent.com/40681405/69292119-612a3480-0c59-11ea-8b99-d22ce1f874bb.png)

But in a jupyter notebook, I don't get the docstrings:
image
![image](https://user-images.githubusercontent.com/40681405/69292131-67b8ac00-0c59-11ea-8419-ad403480760e.png)

## Steps to cause the bug to occur
1. Start VSCode, create a python file. Import numpy, docstring behave as expected.
2. Open existing ipynb file, do original imports (numpy, matplotlib, pandas). Intelissense partially work, no docstrings.

### Your Jupyter and/or Python environment
- **Jupyter server running:**                       Local 
- **Extension version:**                               2019.11.49689
- **VS Code version:**                                1.40.1
- **Setting python.jediEnabled:**               true
- **Python and/or Anaconda version:**     3.7
- **OS:**                                                     Windows
- **Virtual environment:**                          conda

## Developer Tools Console Output
In my console, I see no errors, other than:
[Embedded Page] Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/Microsoft/monaco-editor#faq
webviewElement.ts:241
[Embedded Page] Failed to construct 'Worker': Script at 'vscode-resource://file///c%3A/Users/USERNAME/.vscode/extensions/ms-python.python-2019.11.49689/out/datascience-ui/native-editor/editor.worker.js' cannot be accessed from origin 'null'.

**Comment by abdulfatir** [comment]
I'm facing this issue too. Has this been fixed?

**Comment by rchiodo** [comment]
It's been fixed in our internal builds. The next release will have the fix or you can install in internal build. An example is here:
https://github.com/microsoft/vscode-jupyter/suites/1955423675/artifacts/38740672
