### ISSUE TITLE
Update links to point to Jupyter Repo

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#269]
* Update https://aka.ms/pyaiinstall to point to `https://github.com/microsoft/vscode-jupyter/wiki/Troubleshooting-Jupyter-issues-in-the-Python-Interactive-Window-or-Notebook-Editor`

* Update https://aka.ms/PVSCIPyWidgets

**Comment by DonJayamanne** [comment]
Links might take a while to get updated

**Comment by joyceerhl** [comment]
Validated
