### ISSUE TITLE
Intellisense not working in Jupyter notebook

### ISSUE THREAD

**Issue by prasiyer** [microsoft/vscode-jupyter#2706]
# Bug: Notebook Editor, Interactive Window, Python Editor cells
Issue: Intellisense not working in jupyter notebook
Setup:
    VSCode Version: 1.4
    Using VSCode from Windows 10 to connect to remote Linux VM
    Linux VM details: 4.15.0-1050-azure microsoft/vscode-python#55-Ubuntu SMP
    Python version in vm - 3.5.6
   Env: Conda
Python extension version - 2019.10.44104
Setting python.jediEnabled:**               false
Jupyter server: remote

Issue:

    Intellisense is not working with Jupyter notebook, however intellisense is working with python files (.py)
    I am able to run cells in jupyter notebook

**Comment by rBatist4** [comment]
Unfortunately I have exactly the same problem as @jqluisneumann, I installed everything from 0 to see if it solved, I just added the extension Jupyter, Pylance, Python and Visual Studio IntelliCode, but it ends up being the same.

**Comment by IanMatthewHuff** [comment]
@rBatist4 Could you please open up a new issue here in the vscode-jupyter repo regarding your issue? This particular bug has been closed as of 2019. That way we can help track your issue individually and help resolve it.

**Comment by CSAapps** [comment]
I have this same issue. Any solutions ?

**Comment by rchiodo** [comment]
@CSAapps can you open a new issue? This issue was long ago resolved. We'd need a lot more information to diagnose why intellisense may not be working for you.

**Comment by CSAapps** [comment]
> @CSAapps can you open a new issue? This issue was long ago resolved. We'd need a lot more information to diagnose why intellisense may not be working for you.



> @CSAapps can you open a new issue? This issue was long ago resolved. We'd need a lot more information to diagnose why intellisense may not be working for you.

Yes sure I will open a new issue. Could you please mention what are the information you need. Then I open a new issue with that information. 

Thank you
