### ISSUE TITLE
line numbers within cells in jupyter notebook

### ISSUE THREAD

**Issue by ajshedivy** [microsoft/vscode-jupyter#2766]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description
Is there a way to simply add line numbers in cells when working with jupyter notebooks in vscode? This feature can be toggled on in jupyter notebook and jupyter lab, and would be useful when writing longer cells. 

![image](https://user-images.githubusercontent.com/50843283/68075581-a7395a00-fd77-11e9-8088-9a38c9fe1db0.png)

**Comment by Juanca0312** [comment]
Muchas thanks amigo! Ahora como lo hago para todo mi notebook, Muchas thanks de antemano. :)

**Comment by DavidKutu** [comment]
Hola @Juanca0312, por ahora no hay opción de hacerlo para todo el notebook por que cada cell es un editor separado. No planeamos agregar forma para hacerlo para todo, por que pronto vamos a sacar una nueva interfaz para notebooks. La puedes probar en insiders (https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/) (de la extensión de jupyter, no de python). Está mucho mejor, por ejemplo, carga mucho más rápido.

Creo que por ahora esa nueva interfaz no tiene forma para ver los numeros de linea, pero se lo puedes pedir a vscode, depende de ellos. (https://github.com/microsoft/vscode)
