### ISSUE TITLE
Add telemetry to capture when users are connecting to remote servers on Azure VMs

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-jupyter#280]
Want to size the market of users connecting to remote Jupyter servers running on Azure VMs without SSH.

Think looking for "azure" in the URL name is a good enough proxy. Open to suggestions for better classification (e.g. metadata that the Jupyter server exposes with information about the host it's running on).

Simply tagging existing events is sufficient to answer the question. We don't need to store hostname or connection information.

**Comment by DavidKutu** [comment]
validated
