### ISSUE TITLE
Gather Extension

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#29]
* Rename extension id to the new DS Extension
* API is no longer under `exports.datascience`..., its under `exports`.

**Comment by rchiodo** [comment]
@DavidKutu This isn't working for me? At least the one in the marketplace.

**Comment by DavidKutu** [comment]
what happens? does it not activate? is the button not showing up?

**Comment by rchiodo** [comment]
Activation crashes. `Gather threw an exception during activate`

**Comment by rchiodo** [comment]
Oh no wait, now it's working. WTF. Let me try a different version (was using insiders)

**Comment by rchiodo** [comment]
Works now. I do need to reload but it gathers just fine.
