### ISSUE TITLE
LaTeX equations not showing when character '$' is abscent in .ipynb files

### ISSUE THREAD

**Issue by Mathufnn** [microsoft/vscode-jupyter#2901]
In regular Jupyter Notebooks, one can include a LaTeX-style equation without surrounding the equation with '$' in a markdown cell.

But when I try to do the same in VS Code with the Python extension, the equation won't render.
For example, in regular Jupyter Notebook: 

```
\begin{align*}
(a+b)^2 = a^2+2ab+b^2
\end{align*}
```

Renders 

![equation](https://latex.codecogs.com/gif.latex?%24%5Cbegin%7Balign*%7D%20%28a&plus;b%29%5E2%20%3D%20a%5E2&plus;2ab&plus;b%5E2%20%5Cend%7Balign*%7D%24)

But in VS Code, the equation will only render when the code is surrounded with '$', like this:
```
$\begin{align*}
(a+b)^2 = a^2+2ab+b^2
\end{align*}$
```

Is it possible to include the same funcionality for .ipynb files as in Jupyter Notebooks? It breaks many of my codes with LaTeX equations, and adding '$' to all of them is infeasible.

Edit:
Python VS Code extension version: 2019.10.41019
VS Code version: 1.39.1

**Comment by lon91ong** [comment]
Like [this ipynb file](https://github.com/LetsCodePhysics/ModernPhysics/blob/master/Assignment%2002%20Relativistic%20Dynamics.ipynb)
```
$$ \begin{eqnarray}
\frac{dx}{dt} &=& v, \text{ and} \\\
\frac{dv}{dt} &=& a,
\end{eqnarray} $$
```
multi lines equation doesn't work, my version of VS Code is:
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```
