### ISSUE TITLE
Add support for multidimensional data in data viewer

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#298]
- Modify vscodeGetDataFrameRows to convert extra dimensions to strings
- Truncate long values UI side
- When user clicks into a cell, display the full flattened element

**Comment by joyceerhl** [comment]
To validate this one please open manualTestFile.py and verify that you can open `myTensor` in the data viewer via the following aveneues:
1. Variable view
2. Debugging cell in interactive window
2. Debug current Python file --> debug variables panel --> View Variable in Data Viewer

**Comment by rchiodo** [comment]
Validated
