### ISSUE TITLE
Local images cannot be inserted in jupyter notebook.

### ISSUE THREAD

**Issue by Arial333** [microsoft/vscode-jupyter#2988]
In the markdown part, online images can be inserted well, but the local images cannot be recognized.

**Comment by AndrewLaganaro** [comment]
Hi, I'm using VS Code Insiders and the Python "dev" extension for insiders, and I'm having this same problem. Local images (on the same folder and folders above etc) doesn't render on python notebooks at all.
I tried to copy the suggested solution into settings.json "python.dataScience.useWebViewServer: true" or :false, but my vscode says this command isn't associated with anything.

So, what do I do? Thanks!

**Comment by IanMatthewHuff** [comment]
@AndrewLaganaro On insiders we've moving over to a new UI provided by the VSCode notebook interface. Could you please open up a new issue for this? This old issue was just for our old webview UI and we won't reactivate it.
