### ISSUE TITLE
Support NaN, inf, -inf in data viewer

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#299]
- Today the pandas DataFrame `to_json` doesn't support serializing NaN, inf, -inf. `json.dumps` does support NaN, inf, -inf, but can't be used on DataFrames:
![image](https://user-images.githubusercontent.com/30305945/97235234-b0e57a00-179f-11eb-973d-a2c70619dd64.png)
- Possible solution: preprocess NaN/inf/-inf in vscodeGetDataFrameRows with `df.replace(np.inf, ...)` before calling `df.to_json()`
- Need to map values over to JavaScript equivalents in order for the dataviewer column sort to work

**Comment by IanMatthewHuff** [comment]
Validated. Looks good to me. Added the values to a few lists and checked sorting as well.
