### ISSUE TITLE
Tensor tooltips

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#302]
To implement this, modify this code here:
https://github.com/microsoft/vscode-jupyter/blob/f29073ed195d134827f581251a53c481d88584ef/src/client/datascience/editor-integration/hoverProvider.ts#L111-L118

@greazer mentioned wanting to make the tooltips we display configurable for users. One way to do this is retrieve more custom properties in `IJupyterVariable`, then create a setting (sorry PMs), then display those properties in our tooltips if available for each type. Something like

```
"jupyter.variableTooltipFields": {
    "Tensor": [ "dtype", "shape", "device" ],
    "DataFrame": [ "somePropertyOfInterest" ]
}
```

Then we can read this setting in the hoverProvider.ts and filter out the properties that the user has opted into when constructing the `vscode.Hover` contents for types that are explicitly configured in settings.

Not a requirement yet, we can just hardcode these for the MVP, but just an idea, and this mechanism would work for any other custom variable tooltips we want to support.

**Comment by rchiodo** [comment]
So I think you're suggesting:
- A configurable setting based on type? that uses a regex to parse the value for a tooltip?
- We implement this parsing in the code mentioned above?

**Comment by joyceerhl** [comment]
To validate, you'll need to opt into the experiment:

> "jupyter.experiments.optInto": [ "jupyterEnhancedTensorTooltips" ]

Then run an interactive Python file cell containing this code in the interactive window, place your cursor above the variable name, and verify that a tooltip appears containing shape, dtype and device info:
```python
import torch
foo = torch.tensor([[0, 1, 2], [3, 4, 5]])
```

**Comment by IanMatthewHuff** [comment]
Validated. At least I'm pretty sure this is what we are looking for. I can also try adding a new property.

![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/861656c2-60cc-47ef-a434-9ba0e79e38e4)
