### ISSUE TITLE
Make tensors viewable in data viewer

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#304]
- Add tensors to the list of types that are supported in the dataviewer
- Update vscodeGetDataFrameRows to massage tensors into the right format (currently all the other supported types get converted to pandas dataframes)

**Comment by joyceerhl** [comment]
To validate this:

Run the following code in the IW or a notebook:

```python
# PyTorch Tensors
import torch 
i = torch.LongTensor([[2, 4]])
v = torch.FloatTensor([[1, 3], [5, 7]])
w = torch.sparse.FloatTensor(i, v)  # sparse tensor

# TensorFlow EagerTensors
import tensorflow as tf
a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
```

Verify that you can open all these tensors in the data viewer and that their shapes show up correctly in the variable explorer.

**Comment by rchiodo** [comment]
I can't get this code to run. It just hangs when I run it.

**Comment by joyceerhl** [comment]
You might have better luck splitting them into two cells (one for torch and one for tensorflow). Importing each module takes a really long time.

**Comment by rchiodo** [comment]
They already are. The first cell has been running for 5 minutes.

**Comment by joyceerhl** [comment]
Posting for posterity: if you're on Linux or Windows you need to check pytorch.org for the specific install command (do not just run `pip install torch`).

**Comment by rchiodo** [comment]
Validated.
