### ISSUE TITLE
Slice data in data viewer

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#305]
- Show Slice Data panel for >1D tensors and ndarrays
- Select first dimension by default
- Show shape of tensor and currently-selected axis
- Axis dropdown
- Index dropdown
- Refetch dataframe rows on axis/index selection change

**Comment by joyceerhl** [comment]
Messaging is implemented, blocked on design of actual UI controls for slicing.

**Comment by IanMatthewHuff** [comment]
There is probably a lot to fully test here. But I pulled up a 3x3 and tried to test all the basics. All looked good to me.

1. Slicing using the expression worked as expected
2. Slicing using Axis / Index boxes also worked as expected
3. Axis / Index and the slice expression correctly updated based on the other changing
4. When slice expression could not be reflected in Axis / Index it was disabled
5. Could stop slicing data then re-enable and it saved the slice that I had.

Validated.
