### ISSUE TITLE
Inline tensorboard in notebook cells

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#307]
Blocked on upstream https://github.com/electron/electron/issues/26369

**Comment by rchiodo** [comment]
@joyceerhl how do I validate this? Do you have some sample code?

**Comment by joyceerhl** [comment]
After installing the tf-nightly-cpu build (or monkeypatching a stable tensorboard package install by removing the `frame-ancestors *` directive in the backend.py file under tensorboard in your site-packages directory), you would do 

```python
%load_ext tensorboard
```

in one cell, then 

```python
tensorboard --logdir logs/fit # if this isn't a real directory or doesn't contain any files, that's fine
```

Then verify that the tensorboard website shows up inline like so:

![image](https://user-images.githubusercontent.com/30305945/100941465-84173780-34ae-11eb-8853-a5e3b6b2b2bc.png)

**Comment by rchiodo** [comment]
Validated

**Comment by rchiodo** [comment]
Actually doesn't show up in the cell. I get a blank window.

**Comment by joyceerhl** [comment]
Yuck. If you rerun does it show up then?

**Comment by rchiodo** [comment]
You mean rerun the cell?

This is what the DOM has in it:

```
<iframe id="tensorboard-frame-ca08763762bcb52d" width="100%" height="800" frameborder="0" src="vscode-webview://0f723281-f562-4b34-b949-7dd77fa27a56/">
      </iframe>
```

Didn't you do some translation on the src for the tensorboard? Maybe that isn't happening?

**Comment by joyceerhl** [comment]
Ah wait do you have dev Jupyter VSIX installed as well? Sorry the translation happens in the Jupyter extension, forgot to mention you should also install a VSIX off main. The fix for that went in on Monday.

**Comment by joyceerhl** [comment]
That fix rewrites `window.location` in the tensorboard iframe code to `http://localhost` for the src. If that didn't fix things I need to try something else.

I asked about rerunning because the TensorBoard team recently fixed an issue where on Windows only on the first run it would timeout waiting for tensorboard to start (in browser-based Jupyter as well), so you had to run twice to get the output inline.

**Comment by rchiodo** [comment]
It works fine in stable, it's just insiders that I'm getting the frame rewrite problem.

**Comment by rchiodo** [comment]
Where did you do the rewrite? Was it jupyterNotebook.ts/cellOutput.tsx? That would explain why it would only work on stable.

**Comment by rchiodo** [comment]
No wait, never mind. I wasn't using the latest in the insiders bits. Works there too.
