### ISSUE TITLE
Host Tensorboard UI in a webview

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#308]

**Comment by rchiodo** [comment]
I presume we have to wait for Tensorboard to update their bits on pypi? I get the frame-source error when doing this from scratch.

**Comment by joyceerhl** [comment]
You can also uninstall your existing copies of tensorboard/tensorflow, then install their nightly build, which contains the CSP changes: https://pypi.org/project/tf-nightly-cpu/

**Comment by rchiodo** [comment]
Validated
