### ISSUE TITLE
Add Launch Tensorboard command

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#309]
- Detect if tensorboard is already installed
- If not installed reuse existing module installer to install tensorboard
- Once tensorboard is installed, display input box asking user to input log directory
- Open tensorboard in webview (requires #308)

**Comment by rchiodo** [comment]
Seems like this should be in the python repo? We didn't add this to the jupyter code, right?

**Comment by joyceerhl** [comment]
Yeah sorry this is all implemented in the Python repo. There's an issue tracking this on the Python extension side as well for news entry purposes only.

**Comment by rchiodo** [comment]
Validated
