### ISSUE TITLE
Detect `%load_ext tensorboard` inline usage

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#312]
To validate:
- Opt into 'nativeTensorBoard' experiment in the Python extension
- Create a native Jupyter notebook
- Type %load_ext tensorboard or %tensorboard --logdir logs/fit <-- this is how to launch tensorboard inline in a notebook using the tensorboard nbextension
- Codelenses should appear above these lines

**Comment by rchiodo** [comment]
Validated
