### ISSUE TITLE
Detect tensorboard commands in terminal

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#313]
Send telemetry when we find an integrated terminal running tensorboard

**Comment by joyceerhl** [comment]
We can use `vscode.window.onDidWriteTerminalData`

**Comment by joyceerhl** [comment]
This is now https://github.com/microsoft/vscode-python/pull/15125

**Comment by rchiodo** [comment]
Did you submit this in python already?

**Comment by joyceerhl** [comment]
Yes but this is just about sending telemetry when we find an integrated terminal running tensorboard now.

**Comment by IanMatthewHuff** [comment]
@joyceerhl I was looking to verify this bug. I installed tensorboard locally but when I started it up either from my Mac terminal or from VS Code terminal my terminal name changed to Python3.7 not tensorboard. Anything specific I need to do here?
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/cceeb313-c992-4e71-b888-26f314a3da8b)

**Comment by joyceerhl** [comment]
Sounds like the current mechanism won't work for tensorboard installed into conda environments. I'll implement the process tree polling idea next.

**Comment by rchiodo** [comment]
@joyceerhl should we move this out of validate or is there another issue for the conda problem?

**Comment by joyceerhl** [comment]
Ugh I thought I moved it back to backlog. Should be fixed now.
