### ISSUE TITLE
Detect tfevents files in the user's workspace and auto-set log directory

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#314]

**Comment by rchiodo** [comment]
@joyceerhl what's a tfevent file? Can you explain the steps necessary to try this out? Thanks.

**Comment by joyceerhl** [comment]
Ah yes thanks for asking. tfevent files are logfiles containing metadata from a tensorflow run. Those files are read by the tensorboard webapp, and tensorboard needs to be told which directory to recursively search for tfevent files. So you would do the following to try this:

1. Install a Python extension VSIX off the latest vscode-python main bits
1. Opt into the "nativeTensorBoard" Python extension experiment 
1. Install the tensorboard package (to validate this particular item you don't need the nightly build)
1. Create a Python file and add the following code to a file. e.g. call it foo.py
```python
# Starter TensorBoard script from 
# https://www.tensorflow.org/tensorboard/get_started#using_tensorboard_with_keras_modelfit

import tensorflow as tf
import datetime

mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

def create_model():
  return tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
  ])

model = create_model()
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir='./', histogram_freq=1)

model.fit(x=x_train, 
          y=y_train, 
          epochs=5, 
          validation_data=(x_test, y_test), 
          callbacks=[tensorboard_callback])
```
1. Run the code with `python foo.py`. This will generate a log directory containing tfevent files with the relevant metadata
1. You should see a prompt in the bottom right asking if you want to launch a native TensorBoard session

**Comment by rchiodo** [comment]
I think this is working? The prompt actually came up twice and it let me start two tensorboard windows

**Comment by joyceerhl** [comment]
Yeah multiple sessions are fine https://github.com/microsoft/vscode-python/pull/14751#discussion_r530061535

It's weird that you saw the prompt twice though, the prompt is a singleton and is not supposed to show itself again if we're already waiting for the user to respond to the first prompt.
