### ISSUE TITLE
`shift + enter` broken again (x2)

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#3167]
Issue Type: <b>Bug</b>

reference:
microsoft/vscode-python#3397
microsoft/vscode-python#5621
https://github.com/microsoft/vscode-python/issues/6578

Same keyboard shortcut settings as before (shown below). However, since the most recent update, `shift + enter` does not run the single line when that the cursor is currently on and when there is nothing selected.  It does nothing.  I have tried deleting my custom keyboard shortcuts for `shift + enter` and relying on the defaults, but the behavior is the same.

Should also note that the problem persists whether or not code lens is on or off: https://github.com/microsoft/vscode-python/issues/6578#issuecomment-511515912 .
"Send Selection To Interactive Window" is also set: https://github.com/microsoft/vscode-python/issues/6578#issuecomment-514253279 .

Everything else still works: 
1.  runs only **selected** code in Interactive Pane with or without 'cells' (`#%%` markers) present in file.
1.  runs 'cell' cursor is currently in and advances when there are 'cells' in file and nothing is selected.

Is there something additional that I need to add to the set of keyboard shortcuts json below?

```
{
        "key": "shift+enter",
        "command": "-python.execSelectionInTerminal",
        "when": "editorTextFocus && !findInputFocussed && !python.datascience.ownsSelection && !replaceInputFocussed && editorLangId == 'python'"
    },
    {
        "key": "shift+enter",
        "command": "python.datascience.execSelectionInteractive",
        "when": "editorTextFocus && !python.datascience.hascodecells && !findInputFocussed && !python.datascience.ownsSelection && !replaceInputFocussed && editorLangId == 'python'"
    },
    {
        "key": "shift+enter",
        "command": "python.datascience.execSelectionInteractive",
        "when": "editorTextFocus && python.datascience.hascodecells && !findInputFocussed && !python.datascience.ownsSelection && !replaceInputFocussed && editorLangId == 'python'"
    },
    {
        "key": "shift+enter",
        "command": "python.datascience.execSelectionInteractive",
        "when": "editorTextFocus && python.datascience.featureenabled && python.datascience.ownsSelection && !findInputFocussed && !replaceInputFocussed && editorLangId == 'python'"
    },
    {
        "key": "shift+enter",
        "command": "python.datascience.runcurrentcelladvance",
        "when": "editorTextFocus && python.datascience.featureenabled && python.datascience.hascodecells && !editorHasSelection"
    }
```

Extension version: 2019.8.30787
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by zabi-kamran** [comment]
change the keyboard shortcut for the `python.datascience.runFileInteractive` to any other key combination and the shift+enter will work just fine.
