### ISSUE TITLE
Install torch-tb-profiler package

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#318]
Install torch-tb-profiler package for users whose active workspace contains a torch import. Install failure should not block starting a TensorBoard session.

**Comment by nfx** [comment]
@joyceerhl @greazer this profiler? https://github.com/pandas-profiling/pandas-profiling

**Comment by nfx** [comment]
this does not display correctly in the daily build:

```python
from pandas_profiling import ProfileReport
ProfileReport(df, explorative=True).to_widgets()
```

**Comment by joyceerhl** [comment]
Sorry, this issue refers to https://pypi.org/project/torch-tb-profiler/. Would you mind opening a separate GitHub issue describing the incorrect behavior that you're seeing with the pandas profiler? Thanks!

**Comment by IanMatthewHuff** [comment]
Reassigning me and Joyce just for validation tracking (Joyce = work, Ian = validate).

**Comment by joyceerhl** [comment]
@IanMatthewHuff fyi you'll need to opt into the `PythonPyTorchProfiler` experiment in the Python extension as well to see this 😅

**Comment by IanMatthewHuff** [comment]
Code lens shows:
![image](https://user-images.githubusercontent.com/812783/112395264-4b000e80-8cbb-11eb-8954-be8b4dd8ee0a.png)

+Profiler prompt:
![image](https://user-images.githubusercontent.com/812783/112395298-5a7f5780-8cbb-11eb-9133-75c7b95c6a81.png)

And installation worked. Validated.
