### ISSUE TITLE
Some magic commands not working in Python Interactive window

### ISSUE THREAD

**Issue by Gorbagzog** [microsoft/vscode-jupyter#3187]
# Environment data

VS Code version: 1.36.1
Extension version (available under the Extensions sidebar): 2019.8.29288
OS and version: MAC 10.14.4
Python version: 3.7.1

# Expected behavior

Inside the Python interactive window, I want to use magic commands like %magic or the question mark like foo?

# Actual behavior

Some magic commands are working (like %history or %pylab), but other do not work, like %magic or %pinfo which is equivalent to the question mark foo?

I understand this might be related to this closed issues: microsoft/vscode-python#4170 microsoft/vscode-python#5565
However the behaviour of some magic functions are not the same inside the Python interactive window compared to an ipython terminal. 

I do not know if this issue is from my side, or if it is by design in the Python interactive window, or if it will be solved in a future release.

**Comment by Alonoparag** [comment]
%lsmagic doesn't work for me, using 1.51.4 OSS version on Manjaro Gnome 20
