### ISSUE TITLE
Python interactive window drops fps when creating many plots - SVG rendering is slow

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-jupyter#3279]
Not sure how hard it is to do anything about this but I noticed that if the Python interactive window contains lots of plots already (above maybe 30), adding new ones brings the frame rate down quite significantly. Above around 60 plots, it's at less than 1 fps and makes _all_ of VS Code become unresponsive. Once the plots are done, VS Code (including the interactive window) returns to normal.

![python-interactive-many-plots-low-fps](https://user-images.githubusercontent.com/30958850/60990055-6e482600-a33f-11e9-9d6a-6194fe800371.gif)

Here's some example code to reproduce the issue.

```py
#%%
import matplotlib.pyplot as plt
import numpy as np

for i in range(100):
    plt.plot()
    N = 50
    x = np.random.rand(N)
    y = np.random.rand(N)
    colors = np.random.rand(N)
    area = (30 * np.random.rand(N)) ** 2  # 0 to 15 point radii
    plt.title(f"plot #{i + 1}")
    plt.scatter(x, y, s=area, c=colors, alpha=0.5)
    plt.show()
```

**Comment by ParteekSJ** [comment]
> Possible solution - Generate PNGs along with the SVG, but only display the PNG in the history window. When the plot viewer opens, use the SVG.

How do I do that?

**Comment by janosh** [comment]
@ParteekSJ ￼nothing you have to do. This is something the Jupyter extension now does internally.￼

**Comment by ParteekSJ** [comment]
> @ParteekSJ ￼nothing you have to do. This is something the Jupyter extension now does internally.￼

Thank you.
