### ISSUE TITLE
Provide new interactive window experience for editing notebooks directly

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#3335]
Reusing the interactive window, when opening an ipynb file, just load it into an interactive window, but with these differences:

- Cells are editable
- There's a convert button
- Cells are reorderable (P2)

**Comment by drcege** [comment]
> Maybe next release, or the one after that. It's the next big thing we're working on.
> 
> Here's a gif of what I currently have. Comments welcome
> 
> ![native](https://user-images.githubusercontent.com/19672699/62637692-df540c80-b8f0-11e9-9bf7-62a23ded32b2.gif)


@rchiodo Hi, how can we remove the horizontal frames with "run and markdown button" in the latest version, as described in this [question](https://stackoverflow.com/questions/63637755/hide-lines-with-run-and-markdown-button-on-ipynb-on-vscode)?

![](https://i.stack.imgur.com/vNvct.png)

It takes up a lot of space but is useless most of the time. I just want an interface like the one in your GIF (native jupyter-like experience).

**Comment by rchiodo** [comment]
> @rchiodo Hi, how can we remove the horizontal frames with "run and markdown button" in the latest version, as described in this question?

> It takes up a lot of space but is useless most of the time. I just want an interface like the one in your GIF (native jupyter-like experience).

That GIF is one of our early versions. We didn't ship it that way.

There is no way to turn off the toolbar. However there is another way to open notebooks that we're working on. See this here:
https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/
