### ISSUE TITLE
Jupyter notebook does not go away when closing down vscode

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#3369]
Run  a cell
Close VS code
Jupyter notebook should go away

**Comment by atulkakrana** [comment]
I have the same issue working on remote server. I didn't test on local machine.

**Comment by rchiodo** [comment]
@atulkakrana are you using a remote connection to a jupyter server, or are you doing remote SSH? Meaning did you specify your server here:

![image](https://user-images.githubusercontent.com/19672699/100648602-03154000-32f6-11eb-9dfc-bb6c594034e5.png)

or did you connect this way?

![image](https://user-images.githubusercontent.com/19672699/100648710-29d37680-32f6-11eb-849a-264b28751834.png)
