### ISSUE TITLE
When saving jupyterServerURI setting, duplicate entry is created in settings file

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#343]
![image](https://user-images.githubusercontent.com/812783/97598734-7f012d00-19c4-11eb-915c-086471b33bcc.png)

**Comment by IanMatthewHuff** [comment]
@joyceerhl @rchiodo Do we still have a validation needed here? At least when I opened the initial issue and Joyce's repro above it was by moving from our extension back to the old python extension after migrating once. And the jupyterServerURI isn't even stored there anymore.

Feels like the rest of this was already covered by our bug bash that was testing settings migration.

**Comment by rchiodo** [comment]
I don't think we bug bashed the final settings change, but maybe that's another bug. This specific issue seems to be validated in my opinion though.

**Comment by IanMatthewHuff** [comment]
Validating via our migration testing.
