### ISSUE TITLE
Is there a way to have a full REPL or console for vs code Python?

### ISSUE THREAD

**Issue by colstat** [microsoft/vscode-jupyter#3469]
I find it extremely frustrating using terminal as a REPL. There is no console. It's not a real IDE. I hope to see something like Matlab or R have done.

The following is extremely inconvenient:
1. you can't highlight in terminal
2. shortcut like shift+left arrow which is used to highlight produces characters ;2D (see picture)
3. breaking from a loop using Ctrl+C sometimes exits Python, you have to invoke all over again.
4. The big fat cursor is ugly.

Essentially,
The Python extension just invokes Python from terminal. I mean, if I wanted the terminal experience, I'd do it with VIM. The whole point of VS Code Python is to step away from that.

I'm running:
- VS Code version: 1.33.1
- Extension version: 2019.3.6558
- OS and version: OS X
- Python version: 3.6.7

![terminal](https://user-images.githubusercontent.com/14314760/56231725-2de15080-604d-11e9-99b9-f9132c60f94c.png)

**Comment by butterkaffee** [comment]
> I think you're misunderstanding my intent.
> 
> We have this:
> ![image](https://user-images.githubusercontent.com/19672699/56243408-5e29ee80-604f-11e9-9d8a-8225cedcfdf0.png)
> 
> I'm suggesting this UI will meet your needs.
> 
> If this doesn't meet your needs, are you willing to go into more depth on what you want?

How can I get to that setup? It looks like what I would need if I can run code fragments in my .py file with a shortcut (like shift+enter in terminal). So far I followed the links you provided and got to this stage 
![image](https://user-images.githubusercontent.com/10497301/104426631-7b705180-5582-11eb-8450-1ba1b31ff728.png)

I don't know how to run code on the left with a shortcut in the interactive window though.

**Comment by rchiodo** [comment]
@butterkaffee you can do a couple of things to get code in a python file to run in the interactive window.

1. Add the ```# %%``` comment above a group of code you want to mark as a cell. Hit the 'Run Cell' link that appears after that.
![image](https://user-images.githubusercontent.com/19672699/104485477-647c3000-557f-11eb-95e4-860d376dfe19.png)

Actually that seems to be the only one working at the moment. There's supposed to be a command to run the current selection in the interactive window. Thanks for asking as you helped us find a bug.
