### ISSUE TITLE
No way to stop asking about 'debug' setting for logging

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#348]
When this warning comes up:

```
You have enabled debug logging for the Jupyter extension, which will continue to write logs to disk. Would you like to turn debug logging off?
```

It would be nice to have a 'dont ask me again' setting. I want it to be on.

**Comment by IanMatthewHuff** [comment]
Validated. Verified the setting, picked don't ask again and I wasn't.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/7cb2738b-2aba-4a0a-b634-b3a233be0e5e)
