### ISSUE TITLE
Enhanced support for plots in the Python Interactive window

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode-jupyter#3528]
1. A standalone plot view - similar to R Studio
2. The ability to pop out the plot for resizing
3. Export the plot to image or pdf. 
4. Copy the plot to clipboard.

**Comment by bibinvargheset** [comment]
How to set to open in new windows as this issue is closed?

**Comment by rchiodo** [comment]
@bibinvargheset this is not currently supported. It was closed because we didn't plan to implement it.

**Comment by rchiodo** [comment]
However, plots open in a plot viewer at the moment. You can click on the icon over top of an image:

![image](https://user-images.githubusercontent.com/19672699/99284924-b4db4980-27eb-11eb-9221-d4f5a36f46f7.png)

This will open the plot in a separate window. It's not exactly what Rong describes above, but it's a least a separate window.

**Comment by nayefahmad** [comment]
Just want to say I think this would be a very useful feature for interactive data exploration. Can someone explain why it was decided not to implement it?

**Comment by rchiodo** [comment]
Time to implement is the only reason we didn't fully implement what Rong suggested above. What part are you wanting that isn't there?

**Comment by nayefahmad** [comment]
Thanks for replying. I am mainly referring to the standalone plot view (similar to RStudio)

**Comment by DjinnTonic** [comment]
Yeah this is in fact super important, and I believe that most data scientists who are used to RStudio or spyder would appreciate this feature. I am considering switching from spyder to VS Code but without this feature I won't.
It seems like typing %matplotlib auto into the console activates the Qt5Agg backend which could solve the problem.

**Comment by lars-at-styx** [comment]
@rchiodo I'm not sure if perhaps I'm doing something wrong, in my case the part I want that doesn't seem to be working is rotation of 3D plots. I can however prefix my code with `%matplotlib auto` as a workaround, this for some reason creates a new matplotlib screen separate from vscode in which it does work.

**Comment by adrianschlatter** [comment]
@rchiodo For me, the essential part that is missing is the interactivity: When exploring data, I want to modify a plot that is already there. Typical use case: I create a plot from a script, I run the script, look at the plot, find something that I want to improve/add/change/remove, improve the plot in the console until I am happy, then copy the working code back into my script.

`%matplotlib auto`

is a simple workaround. Would be nice to have a setting to do this automatically in the background.

**Comment by rchiodo** [comment]
Have you tried using ```%matplotlib widget``` instead? You have to change your plots a bit, but they will render inline:

![image](https://user-images.githubusercontent.com/19672699/108891154-3ac51880-75c3-11eb-9c7c-a16af108023e.png)

It doesn't seem to have rotation, but there might be options I don't know about.

**Comment by adrianschlatter** [comment]
I have not tried that because it seems unattractive to have the plots inline. Having the plots scroll away more and more when I add code hinders interactivity. When I say "interactive" I am not referring only to the zoom and pan features but mainly to the ability to type code to modify the plot.
