### ISSUE TITLE
Review kernel search & startup environment variables (support for non-python kernels with Conda environments)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#365]
**Issues when starting non-python kernels**
### Starting Java kernel registered in a conda environment (like BeakerX) will never work as the paths are incorrect. We need to activate conda environment and use those env vars...
See other comments.

**Context:**
https://github.com/microsoft/vscode-jupyter/issues/361
https://github.com/microsoft/vscode-jupyter/pull/362

@IanMatthewHuff 

This doesn't seem right as there is a specific search order for jupyter kernel specs. You can have the same name without Conda involved at all. And if you didn't have conda active you wouldn't want a conda path to be searched at all.

https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs
https://github.com/jupyter/jupyter_client/blob/540c996396ad60c312016fecc48200b5452ef1f2/jupyter_client/kernelspec.py

I think we'd want the following:
1. If conda wasn't active you'd use the Jupyter search priority order.
2. If conda was active (only if python extension is installed) you'd want to prioritize the active conda env (and no other ones) then the jupyter ones in priority order.

I get that's a bigger change, but that seems right to me. Could file it as a work item for after parity release?

@DonJayamanne 

> This doesn't seem right as there is a specific search order for jupyter kernel specs. You can have the same name without Conda involved at all. And if you didn't have conda active you wouldn't want a conda path to be searched at all.

Agreed. This PR ensures that if we have duplicates we at least get that working.
Would you agree this PR is sufficient or does this break anything. 

> I think we'd want the following:
> If conda wasn't active you'd use the Jupyter search priority order.

Also, we need to run the kernels with the conda environment variables.
E.g. when running a JavaKernel installed by a conda environment, then we'd need to activate the conda environment to run the Java kernel. (as java executable & the like is in Conda environment) & all of these paths are setup when activating the conda environment.

**Comment by IanMatthewHuff** [comment]
Validated via our testing on this.
