### ISSUE TITLE
Smoke test failure

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#372]
![image](https://user-images.githubusercontent.com/30305945/97898399-ad487a80-1cec-11eb-8ccf-b435a6de2c52.png)

Details: https://github.com/microsoft/vscode-jupyter/runs/1343321593?check_suite_focus=true

**Comment by DonJayamanne** [comment]
The attached logs are not related to the failure.

**Comment by rchiodo** [comment]
@joyceerhl are you investigating this? The latest failures look related to the random bytes stuff. If you're not actively investigating, I'm happy to look at it.

**Comment by joyceerhl** [comment]
Sorry just saw this @rchiodo. I've been investigating the smoke tests for the last 2-3 days (among other things) but wouldn't mind extra eyes on these.

The random bytes smoke test is failing on Windows, and I can repro the failure locally. But I'm pretty sure it's only a smoke test setup issue because the actual VSIX itself works fine. For some reason node can't load the ffi-bindings.node module (complains about it not being a valid win32 application). My latest theory I'm pursuing is that the smoke tests are running with the wrong node.exe.

There are also macos smoke test failures. Random bytes test passes there but the other two tests (running cells in notebook and IW) fail. There are errors about the interpreter not having ipykernel installed which seems weird because ipykernel is deliberately installed as part of the smoke test requirements.

**Comment by rchiodo** [comment]
I'll look at the mac test failures.

**Comment by joyceerhl** [comment]
Validated.
