### ISSUE TITLE
Remove RBL experiment code

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#373]
Per @claudiaregio, having rolled RBL out to 100% of customers, we can now remove code that checks for the experiment's enablement.

https://github.com/microsoft/vscode-jupyter/blob/c41c6e2af68ce4e8860cdd25da2a77c9e1c33c79/src/client/datascience/interactive-common/interactiveBase.ts#L194

https://github.com/microsoft/vscode-jupyter/blob/c41c6e2af68ce4e8860cdd25da2a77c9e1c33c79/src/client/datascience/jupyter/jupyterVariables.ts#L76-L79

https://github.com/microsoft/vscode-jupyter/blob/c41c6e2af68ce4e8860cdd25da2a77c9e1c33c79/src/client/datascience/editor-integration/hoverProvider.ts#L33

**Comment by DavidKutu** [comment]
validated
