### ISSUE TITLE
DS: Enable Jupyter widgets (aka ipywidgets)

### ISSUE THREAD

**Issue by Babakjfard** [microsoft/vscode-jupyter#3767]
I use BeakerX widget in Jupyter a lot to explore my pandas data frames. It will be great if this feature can be added to vscode (and in general the support for Jupyter Widgets in vscode)

**Comment by LeeRippon** [comment]
> Got it working. For anyone else struggling, this works in VSCode:
> 
> ```
> import plotly.graph_objects as go
> import numpy as np
> from ipywidgets import interact
> 
> fig = go.FigureWidget()
> fig.add_scatter()
> 
> xs=np.linspace(0, 6, 100)
> 
> @interact(a=(1.0, 4.0, 0.01), b=(0, 10.0, 0.01), color=['red', 'green', 'blue'])
> def update(a=3.6, b=4.3, color='blue'):
>     with fig.batch_update():
>         scatt = fig.data[0]
>         scatt.x=xs
>         scatt.y=np.sin(a*xs-b)
>         scatt.line.color=color
> 
> fig
> ```
> 
> ![image](https://user-images.githubusercontent.com/64961256/81355642-7533f680-9112-11ea-8e1e-64d421550b1d.png)

Does plot viewer work with it? I have my interactive plots working in my VScode Jupyter notebook but for some reason it won't let me open it into a separate screen (i.e., plot viewer). Thanks!

**Comment by rchiodo** [comment]
Sorry but widget based plots are not connected to our external viewer.

**Comment by JonesKenzie** [comment]
Hello, I can't use the widgets.  I'm on a Windows 10, using Python 3.8.5 64-bits with the 2020.6.91350 Python Extension.  
![image](https://user-images.githubusercontent.com/38723964/113400535-3e0daa00-93a2-11eb-887e-943ff57d72cf.png)

```
argon2-cffi==20.1.0
async-generator==1.10
attrs==20.3.0
backcall==0.2.0
bleach==3.3.0
cffi==1.14.5
colorama==0.4.4
cycler==0.10.0
decorator==5.0.0
defusedxml==0.7.1
entrypoints==0.3
ipykernel==5.5.3
ipython==7.22.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==2.11.3
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
kiwisolver==1.3.1
MarkupSafe==1.1.1
matplotlib==3.4.1
mistune==0.8.4
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.3.0
numpy==1.20.2
packaging==20.9
pandas==1.2.3
pandocfilters==1.4.3
parso==0.8.2
pickleshare==0.7.5
Pillow==8.2.0
prometheus-client==0.9.0
prompt-toolkit==3.0.18
pycparser==2.20
Pygments==2.8.1
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2021.1
pywin32==300
pywinpty==0.5.7
pyzmq==22.0.3
scipy==1.6.2
seaborn==0.11.1
Send2Trash==1.5.0
six==1.15.0
terminado==0.9.4
testpath==0.4.4
tornado==6.1
traitlets==5.0.5
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
```

```
jupyter core     : 4.7.1
jupyter-notebook : 6.3.0
qtconsole        : not installed
ipython          : 7.22.0
ipykernel        : 5.5.3
jupyter client   : 6.1.12
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
```

**Comment by rchiodo** [comment]
@JonesKenzie  can you enter a new issue? We'll need more logging to determine what the problem is.
