### ISSUE TITLE
Multiprocessing requires a restart in order for the interactive window to work

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#378]
Run this code in interactive window:

```
# %%
import multiprocessing
```

Run this code. It will hang
```
def newmethod292():
    pool = multiprocessing.Pool()
    results = pool.map(my_function, [1,2,3,4,5,6])
    pool.close()
    pool.join()
    print(results)

newmethod292()
```

Restart the kernel and do the same. It will now work.

Double check we're setting the ```__file__``` value correctly. This was supposed to work already.

**Comment by greazer** [comment]
No upvotes. Closing
