### ISSUE TITLE
Request to expose command to collapse/expand all cell inputs in interactive window

### ISSUE THREAD

**Issue by rholland** [microsoft/vscode-jupyter#3799]
I really like that you provided the collapse functionality, currently as clickable button.  I would like to associate it with a shortcut key but I cannot find the associated command.  Could you please provide one.  

Also please consider changing the behavior of the *collapse all cell inputs*.  If you can do it I think it makes more sense in terms of work flow to have new cells respect the setting.  Currently any new cells that are added turn off the setting and show the input.

I am on Windows 10 with the latest VS Code and Python extension updates and running Python 3.7.

Thanks again for the very nice extension.

**Comment by juliuscrn** [comment]
Is there a way to keep cells expanded by default?

**Comment by rchiodo** [comment]
> Is there a way to keep cells expanded by default?
@juliuscrn , yes there is. See his bug here:
https://github.com/microsoft/vscode-jupyter/issues/3598
