### ISSUE TITLE
Update readme, icon, background, description for renderer extension

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#386]
We need to update the:
* Readme
* `description` in package.json (this is displayed in marketplace as description immediately under extension name on the main page)
* Icon
* Official name of extension

https://github.com/microsoft/vscode-notebook-renderers

**Comment by rchiodo** [comment]
Not sure how to validate this. I don't see the notebook renderer in the marketplace? I do see the icon in the source though.
