### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by vicnoo** [microsoft/vscode-jupyter#3913]
- Issue Type: `Performance`
- Extension Name: `jupyter`
- Extension Version: `2020.11.358541065`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Padawan\AppData\Local\Temp\ms-toolsai.jupyter-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Jrex-web** [comment]
Se recarga la CPU y se bloquea.

**Comment by greazer** [comment]
@vicnoo, please attach the file you mention above. Thank you!
