### ISSUE TITLE
Render markdown with an appropriate font

### ISSUE THREAD

**Issue by aaznadi** [microsoft/vscode-jupyter#3917]
Would be nice to have the markdown rendered with a non-monospace font. This would definitely make the notebooks more readable as we work on them.

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
