### ISSUE TITLE
Kernels in /usr/share/jupyter or /usr/local/share/jupyter are not found

### ISSUE THREAD

**Issue by rapgenic** [microsoft/vscode-jupyter#3918]
## Environment data

-   VS Code version: 1.52.0-insider
-   Extension version (available under the Extensions sidebar): commit 49ff2c6d0cd5b83f9be0bc5c52c8c44dbc66c022
-   OS (Windows | Mac | Linux distro) and version: Arch Linux
-   Python version: 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): none
-   Jupyter server running: Local

## Expected behaviour

Find kernels located in 
* `/usr/share/jupyter/kernels`
* `/usr/local/share/jupyter/kernels`
## Actual behaviour

Those kernels are not found

## Possible reason
I think the bug is located in the following lines:

https://github.com/microsoft/vscode-jupyter/blob/49ff2c6d0cd5b83f9be0bc5c52c8c44dbc66c022/src/client/datascience/kernel-launcher/kernelFinder.ts#L324-L328

Where i think the `/` (root) part is missing. I tried substituting those lines with the following and it seemed to actually work now:

```typescript
        paths.push(
            path.join('/', 'usr', 'share', 'jupyter', 'kernels'),
            path.join('/', 'usr', 'local', 'share', 'jupyter', 'kernels'),
            path.join(this.pathUtils.home, secondPart)
        );
```

**Comment by rapgenic** [comment]
Well probably this does not apply to `/usr/share/jupyter/kernels` because that folder seems to be already found by the `getInterpreterPaths` function, and in that case the `/` root is present

**Comment by rchiodo** [comment]
Thanks for the bug. The fix does seem appropriate. Feel free to submit a PR or we should get to this soon.
