### ISSUE TITLE
Python language keywords are not highlighted in Jupyter notebooks over WSL

### ISSUE THREAD

**Issue by jeanmonet** [microsoft/vscode-jupyter#3919]
## Environment data

-   VS Code version: 1.51.1
-   Jupyter Extension version: v2020.11.358541065
-   Remote - WSL extension: 0.51.3
-   OS (Windows) and version: 10 with WSL1 running Ubuntu 20.04 LTS
-   Python and/or Anaconda version: Python 3.8.6
-   Type of virtual environment used (conda): conda 4.9.2
-   Jupyter server running: N/A

## Expected behaviour

Python language keywords should be highlighted like in .py files.

## Actual behaviour

Python language keywords are not highlighted/colored in a .ipynb notebook opened in VSC via WSL (with interpreter set to the relevant Python interpreter in the conda environment (over remote WSL1).

## Steps to reproduce:

Open  .ipynb notebook in VSC via WSL - Remote.
Can't figure out why this is happening?

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
