### ISSUE TITLE
Palette command "Open in Notebook Editor" not functional

### ISSUE THREAD

**Issue by pe224** [microsoft/vscode-jupyter#3920]
## Environment data

-   VS Code version: 1.51.1
-   Extension version (available under the Extensions sidebar): v2020.11.358366026
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.358541065
-   OS (Windows | Mac | Linux distro) and version: Win 10
-   Python and/or Anaconda version: 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Steps to reproduce:

1. Create `test.ipynb` with content
```json
{
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.6-final"
  },
  "orig_nbformat": 2,
  "kernelspec": {
   "name": "python3",
   "display_name": "Python 3.8.6 64-bit",
   "metadata": {
    "interpreter": {
     "hash": "dc33fc19570b4b278fa70787b867f471bafaa41b19b180fd264f469f8e7754ae"
    }
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2,
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "a = 1"
   ]
  }
 ]
}
```

and set `"jupyter.useNotebookEditor": false,` in settings

2. Right-click on `test.ipynb` in the File Explorer sidebar and choosing `Open in Notebook editor` will open it correctly in the notebook editor

3. Double-click on `test.ipynb` in the File Explorer sidebar opens it as JSON (as expected due to settings). But now, running the command `Jupyter: Open in Notebook Editor` from the command palette does nothing.

Expectation: it re-opens the JSON-format `test.ipynb` in the Notebook editor

**Comment by rchiodo** [comment]
Thanks for the bug. I believe exposing this to the palette was not intended. It would never have worked. That command is supposed to only be on the menu.

We should either remove it from the palette or fix it.

**Comment by rchiodo** [comment]
The bug is here:
https://github.com/microsoft/vscode-jupyter/blob/922deb2d4793e4d6b0a6883e0d45b861434f0046/src/client/datascience/interactive-ipynb/nativeEditorCommandListener.ts#L118

On a palette command (as opposed to the menu command), the file URI is always undefined. This code could be fixed with another if statement that checks for an empty URI and then uses the active document instead.

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on addressing this issue in the near future.
