### ISSUE TITLE
working with docker

### ISSUE THREAD

**Issue by chakib-belgaid** [microsoft/vscode-jupyter#3921]
Issue Type: <b>Bug</b>

can't conenct to a notebook run inside a container 

Extension version: 2020.11.358541065
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:14:40.758Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 4.19.0-12-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.72GB free)|
|Process Argv|--crash-reporter-id a56bd84e-33a8-4277-b466-d275f97d3e85|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: frontend-lille|
|OS|Linux x64 4.19.0-12-amd64|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (4 x 2200)|
|Memory (System)|7.82GB (0.26GB free)|
|VM|100%|
</details>

**Comment by greazer** [comment]
Thanks for the feedback!

Please set this setting: ```"python.logging.level": "debug"```
Then restart VS code, reproduce your problem, and copy the output of the 'Python' output tab into this issue.
