### ISSUE TITLE
No module named 'tensorflow'

### ISSUE THREAD

**Issue by christina-0725** [microsoft/vscode-jupyter#3922]
Issue Type: <b>Bug</b>

# <VScode> Jupyter extension - No module named 'tensorflow'
I used Anaconda to create a virtual environment with module tensorflow.
![Image of virtual environment](https://github.com/christina-0725/Helloworld/blob/main/3.PNG)

I can import tensorflow in Juypter notebook which was installed in Anaconda. 
![Image of Jupyter notebook](https://github.com/christina-0725/Helloworld/blob/main/2.PNG)

I can also import tensorflow in VScode Python extension.
![Image of VScode Python extension](https://github.com/christina-0725/Helloworld/blob/main/4.PNG)

 But in VScode Jupyter extension, when I input "import tensorflow as tf", the ModuleNotFoundError will occur.
![Image of Vscode Jupyter extension](https://github.com/christina-0725/Helloworld/blob/main/1.PNG)

This problem also happened on my mac. I don't know why this happens. I hope someone can help me solve this question. Thanks!

Extension version: 2020.11.358541065
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (2.97GB free)|
|Process Argv|C:\Users\kh\Desktop\VScode\服装图像训练.ipynb --crash-reporter-id 6a652439-042b-4523-8c8c-eea565986121|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by christina-0725** [comment]
This time I launch VScode from Anaconda and I successfully run the program under "tensorflow" virtual enviroment.
But it also reminds me as follow:

```TypeScript
"StdErr from ShellExec, Did not find path entry C:\ProgramData\Anaconda3\bin for C:/ProgramData/Anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\kh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py c:/Users/kh/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/printEnvVariables.py"
```

**Comment by greazer** [comment]
@christina-0725, thanks for the feedback. Can you open a new issue in the vscode-python repo for the second issue you're mentioning?

**Comment by christina-0725** [comment]
> @christina-0725, thanks for the feedback. Can you open a new issue in the vscode-python repo for the second issue you're mentioning?

I have tried to run the proin the VScode python repo, the code is as follow:
```Python
import tensorflow as tf
from tensorflow import keras
# Helper libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(tf.__version__)
```
This time the Python debug console remind me as follow:

```TypeScrpit
PS C:\Users\kh\Desktop\VScode>  & 'C:\Users\kh\.conda\envs\tensorflow\python.exe' 'c:\Users\kh\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\lib\python\debugpy\launcher' '57994' '--' 'c:\Users\kh\Desktop\VScode\hhh.py'
2020-11-20 13:32:33.934779: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-11-20 13:32:33.939820: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2.3.1
PS C:\Users\kh\Desktop\VScode> conda activate tensorflow
```
Thanks for your concern!
