### ISSUE TITLE
Capture telemetry of kernel when switching kernel in native notebook

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#3933]
Requested by @claudiaregio  & in Native Notebooks we aren't doing this (when we should)

**Comment by rchiodo** [comment]
I don't see this in the code? Did you just submit this?

**Comment by rchiodo** [comment]
Oh you did just submit this. I'll try validating again.

**Comment by rchiodo** [comment]
Validated.
