### ISSUE TITLE
Jupyter is not opening

### ISSUE THREAD

**Issue by Manju2012** [microsoft/vscode-jupyter#3941]
Issue Type: <b>Bug</b>

I've jupyter installed on my system. But i'm not able to open it

Extension version: 2020.11.358541065
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (4.49GB free)|
|Process Argv|--crash-reporter-id 94c7c2c1-d4eb-4a91-875a-886cd31e395f|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rchiodo** [comment]
Thanks for the bug.

Can you do the following:

1. Go to settings and change this value debug:

![image](https://user-images.githubusercontent.com/19672699/99423070-0996c700-28b5-11eb-8444-3c2e54ace535.png)

2. Restart VS code
3. Reproduce your error
4. Copy the contents of the Jupyter output tab to this bug (either in plain text or as a file you upload)

Thanks

**Comment by Manju2012** [comment]
Now i'm able to open it but can't run it. please see the screenshot of error
![image](https://user-images.githubusercontent.com/56887373/99494043-56060380-2996-11eb-9398-45e7d31f1d07.png)

**Comment by rchiodo** [comment]
For some reason our install is failing. You can do this manually instead.

1. Open an anaconda prompt
1. Switch to the environment you want to use (looks like base from the error message)
1. Type 'conda install ipykernel'
1. Restart VS code

It should pick up ipykernel then.

If not then we need the output I asked for above.

**Comment by Manju2012** [comment]
I followed your instructions as above and it is updated successfully. but when i open jupyter notebook in cmd it is showing below error

![image](https://user-images.githubusercontent.com/56887373/99629004-4e5d6200-2a5d-11eb-91b2-0e7bb6b85630.png)



and also i'm getting IPYkernel not installed error and if I click on install then i'm getting error as could not install. as shown below
![image](https://user-images.githubusercontent.com/56887373/99629265-b9a73400-2a5d-11eb-8721-5f2624cacaee.png)

**Comment by rchiodo** [comment]
THat sounds like this issue here:
https://github.com/jupyter/notebook/issues/3435

**Comment by Manju2012** [comment]
I tried that and now i can run jupyter in browser.  but when I start jupyter in VS code i'm getting error as beow
![image](https://user-images.githubusercontent.com/56887373/99769689-b4fd8100-2b2c-11eb-85cb-6f7f73c10fb8.png)

**Comment by rchiodo** [comment]
That sounds like a path problem. You may have to start VS code from the same environment you're running jupyter from, or follow the directions here:
https://github.com/jupyter/notebook/issues/4980

**Comment by Manju2012** [comment]
> 
> 
> That sounds like a path problem. You may have to start VS code from the same environment you're running jupyter from, or follow the directions here:
> [jupyter/notebook#4980](https://github.com/jupyter/notebook/issues/4980)

tried this too. but still not resolved my issue
