### ISSUE TITLE
Release notes failed to specify how jupyterServerURI changed.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#3942]
It was confusing to people how to set their jupyter server URI after we eliminated this setting. We should have done something like:
- Talk about it in the blog
- Talk about in the release notes
- Have documentation on the transition

**Comment by rchiodo** [comment]
Other migration settings were also not explained. We had a bug in our migration that caused some settings to fail and keybindings no longer worked.

**Comment by greazer** [comment]
We should document things like this on an FAQ and point people to it. That and the jupyter troubleshooting doc. Perhaps put in wiki?

**Comment by IanMatthewHuff** [comment]
Validating based on the existence of FAQ / Wiki, which I believe is the work item for this.

https://github.com/microsoft/vscode-jupyter/wiki

**Comment by rchiodo** [comment]
But it's not on the wiki?

**Comment by IanMatthewHuff** [comment]
@rchiodo I thought the point was the have a communication channel for the next time that we had a change like this. @greazer What's the work that we need to validate here?

**Comment by greazer** [comment]
Yes, at this point, I don't understand the need to document this particular problem (jupyterServerURI changed). I created a section for current or common issues, but I thought any conversation about issues we've had with the transition from Python to a separate extension is getting kinda old.

**Comment by rchiodo** [comment]
Yeah maybe the wiki is not the place to log all of the answers for different bugs. Maybe just general categories of issues (like being on stable and not having some editor feature work)
