### ISSUE TITLE
Hide the green `tick` when loading existing notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#3943]
@claudiaregio requested
When opening an existing notebook, the green `tick` or error icon in cell statusbar should not be displayed.
The green tick or error icon should only be displayed during run time.
**Else user makes the assumption the cell ran right now, instead of this being some old state**

**Comment by IanMatthewHuff** [comment]
Validated. Green tick is now only when I execute after opening.
