### ISSUE TITLE
IPython debugger cannot quit in python interactive mode

### ISSUE THREAD

**Issue by TZTsai** [microsoft/vscode-jupyter#3946]
Issue Type: <b>Bug</b>

1. Open an ipynb file
2. Use IPython debugger: `from IPython.core.debugger import set_trace`
3. Add a breakpoint in the code by inserting `set_trace()`
4. Run the cell and an ipdb panel jumps out
5. Try to close it by pressing `Ecs` but it fails

Extension version: 2020.11.358366026
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (4.42GB free)|
|Process Argv|--crash-reporter-id bbf2684e-202b-49a4-8628-45ff35f0cc52|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rchiodo** [comment]
Sorry but this isn't supported. If you want to debug ipython you can use the interactive window debugger:
https://code.visualstudio.com/docs/python/jupyter-support-py#_debug-a-jupyter-notebook
