### ISSUE TITLE
Create Jupyter Notebook from Start Page

### ISSUE THREAD

**Issue by savannahostrowski** [microsoft/vscode-jupyter#3948]
## Environment data

-   VS Code version: 1.51
-   Extension version (available under the Extensions sidebar): 2020.11.358366026
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

I should be able to click the create Jupyter notebook button and successfully create a notebook.

## Actual behaviour

Create notebook link yields error.
![image](https://user-images.githubusercontent.com/8949415/99300721-cd565e80-2801-11eb-9605-dd90a5463bc1.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open VSCode
2. Click button on start page!

**Comment by rchiodo** [comment]
Hmm, looks like our empty notebook is invalid. I'm guessing this is insiders? It at least doesn't support opening an empty ipynb file.

**Comment by savannahostrowski** [comment]
Hm, I wasn't on VSCode or Python/Jupyter insiders.

**Comment by rchiodo** [comment]
Hmm. Can you include your settings.json? That command works for me on stable. Maybe there's something in your settings that causing extra code to run.

**Comment by savannahostrowski** [comment]
```
{
    "files.autoSave": "afterDelay",
    "python.analysis.completeFunctionParens": true,
    "window.zoomLevel": 1,
    "editor.snippetSuggestions": "none",
    "workbench.colorTheme": "Material Theme Palenight High Contrast",
    "python.languageServer": "Pylance"
}
```

**Comment by greazer** [comment]
@savannahostrowski, can you still repro this? We're not.
