### ISSUE TITLE
'python.datascience.execSelectionInteractive' not found

### ISSUE THREAD

**Issue by crunkilton** [microsoft/vscode-jupyter#3949]
Issue Type: <b>Bug</b>

I have a keybinding to execute the current selection in a python interactive window. It recently stopped working, and it seems like 'python.datascience.execSelectionInteractive' no longer appears to exist.

To reproduce:
Add this to keybindings.json:
{
    "key": "cmd+enter",
    "command": "python.datascience.execSelectionInteractive"
  }

Expected results: cmd+enter executes the current selection in an interactive window

Actual results:
command 'python.datascience.execSelectionInteractive' not found

I also do not see any settings anymore when I search "data science" in settings, which may be related. 

Extension version: 2020.11.358366026
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 6|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 6cc1787e-c794-4061-b789-b89d2432cd77|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by xquyvu** [comment]
Same issue here.

**Comment by rchiodo** [comment]
Sorry this is a result of our porting settings during the switch to the Jupyter Extension. See this issue:
#1089
