### ISSUE TITLE
bqplot seems to not load anymore

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#3955]
![image](https://user-images.githubusercontent.com/19672699/99467709-d45d9980-28f3-11eb-940e-a54c32757368.png)

We may have to load an older version?

**Comment by rchiodo** [comment]
Seems to be there on jsdelivr
https://cdn.jsdelivr.net/npm/bqplot@0.5.19

Unpkg has it too, just a different spot
https://unpkg.com/bqplot@0.5.19

**Comment by rchiodo** [comment]
Yeah the 'npm' value is now requires on jsdelivr for some reason.

**Comment by rchiodo** [comment]
Seems like it should load just fine. Weird that it's just bqplot.

**Comment by joyceerhl** [comment]
The error is `Internet connection required for loading 3rd party widgets`. I ran the test 3x locally and the test only failed once. It's not a CDN issue as the packages are there. So AFAICT those errors are just a result of a flaky network connection.

**Comment by joyceerhl** [comment]
We already have retry logic in the test (retries for 10s then stops trying). If the internet connection is actually transiently down I'm not sure what we can do here. Maybe increase the allowed timeout?

**Comment by rchiodo** [comment]
> Maybe increase the allowed timeout?

Sounds like a good first step.
