### ISSUE TITLE
Forever spinning icon

### ISSUE THREAD

**Issue by ctokun** [microsoft/vscode-jupyter#3957]
## Environment data

-   VS Code version: 1.52.0-insider
-   Extension version (available under the Extensions sidebar): v2020.11.367453362
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.358541065
-   OS (Windows | Mac | Linux distro) and version: Mac 10.15.7
-   Python and/or Anaconda version: Python 3.7.8 Honda 4.9.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

The spinning wheel icon will turn into a checkmark when the cell is done executing. Super distracting -- even an option to disable the checkmark icon altogether would be extremely helpful.

## Actual behaviour

![gif](https://user-images.githubusercontent.com/47460327/99470883-bf3c3700-2902-11eb-8e7f-4c56a36ba948.gif)

The spinning wheel continues to spin until the file is closed, regardless of whether the cell is done executing or has failed. This doesn't happen 100% of the time -- it seems random as far as I can tell. 

## Steps to reproduce:
1. Create new notebook
2. Enter code into cell
3. Run cell

**Comment by rchiodo** [comment]
Thanks for the bug. We haven't seen this internally so it might be hard to fix without a repro.

**Comment by greazer** [comment]
@ctokun, if you can find a repro, please reopen this bug. Thanks!
