### ISSUE TITLE
results after find and replace are not displayed by the notebook editor 

### ISSUE THREAD

**Issue by paulromer149** [microsoft/vscode-jupyter#3960]
## Environment data

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
-   VS Code version: 1.51.1
-   Extension version (available under the Extensions sidebar): v2020.11.367453362
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.358541065
-   OS (Windows | Mac | Linux distro) and version: Mac 10.15.7
-   Python and/or Anaconda version: 3.8.5 64-bit (anaconda)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

After using the search and replace tool from the sidebar on the left, I expect to see the changed text in the editor. 

## Actual behaviour

The the changes do not show up in the display of the notebook. However, if I save the file and reopen it, the changes are visible. Also, parts of the json for the notebook file can be changed inadvertently. 

## Steps to reproduce:

Create a notebook with some markdown text and some code that uses the letter "w". 

Do a global find and replace on the letter "w" using the tool on the bar on the left. Change all occurrences to  "q". 

The display for the search tool will no longer display any instances of "w" that match the find. But the display of the notebook in the editor will still show the "w" character. 

Then try to find the letter "q". It will now show up in all the places where the "w" was before and in the word "markdown" which is part of the json for the notebook. 

If you save the file then reopen it, any markdown cells will now be broken. But in the cells with code or comments, the "w" character will now be gone and the "q" character will be there in its place. 

## Logs

</summary>

<p>

The first image shows the display before clicking to replace all instances of "w" with "q". Note that find has found the work markdown from the json for the notebook: 
<img width="1384" alt="Screen Shot 2020-11-18 at 1 22 42 AM" src="https://user-images.githubusercontent.com/33130966/99494971-e6652980-293f-11eb-9fe6-d54d7fb991d0.png">

The second image shows the display after clicking to replace all instances of "w" with "q". The find tool no longer finds an instances, yet the display still shows them: 
<img width="1406" alt="Screen Shot 2020-11-18 at 1 23 00 AM" src="https://user-images.githubusercontent.com/33130966/99495149-35ab5a00-2940-11eb-9cab-92412a35ebb6.png">

The final image shows the effect of saving the file, closing it, and reopening. The "q" shows up where the "w" character was. And the markdown is broken:
<img width="824" alt="Screen Shot 2020-11-18 at 1 23 31 AM" src="https://user-images.githubusercontent.com/33130966/99495472-b5d1bf80-2940-11eb-9928-4e1f7255dad1.png">

</p>
</details>

**Comment by rchiodo** [comment]
Sorry but this isn't supported. VS code does not know that our editor is for a text document. If you want to perform search and replace in notebook files, you'll need to use the insiders version of VS code where we've switched to using a new editor that VS code does understand.

You can read about it here:
https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/
