### ISSUE TITLE
Jupyter toolbar

### ISSUE THREAD

**Issue by nguyen14ck** [microsoft/vscode-jupyter#3963]
Jupyter has a toolbar (Run, Save, Export, Show Variable Table). However, it disappears in the recent version of VSCode Insider. Please bring back that toolbar and the button to display variable table. Thanks.

**Comment by rchiodo** [comment]
Most of those functions are available in the insiders. They've just moved to the 'toolbar' location for editors now:

![image](https://user-images.githubusercontent.com/19672699/99575188-24d50580-298d-11eb-8029-17af817c22d6.png)


The variable table isn't currently supported however. That's being worked on here:
https://github.com/microsoft/vscode-jupyter/issues/250

**Comment by nguyen14ck** [comment]
Thanks
