### ISSUE TITLE
"python.dataScience" settings now removed an unable to send selection to interactive window

### ISSUE THREAD

**Issue by lukehuxham** [microsoft/vscode-jupyter#3974]
## Environment data

-   VS Code version: 1.51.1
-   Extension version (available under the Extensions sidebar): v2020.11.367453362
-   OS and version: Windows 10 Enterprise 1803
-   Python version (& distribution if applicable, e.g. Anaconda): conda 4.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda env
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: "python.languageServer": "Pylance",

## Expected behaviour

Up until this latest change I was able to select either line or selection and send to interactive window.

## Actual behaviour

This option no longer exists in any context menu or setting

This may be by design, apologies if that is the case but have been through the changelogs for Python extension and VS code and cannot see any mention of these changes.

Thanks.

**Comment by greazer** [comment]
Please reopen if this is not resolved in the next official release.
