### ISSUE TITLE
Code coverage needs to be measured

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#3975]
We have an OKR of 50% coverage for tests.

None of our functional or vscode.test.ts files measure coverage.

**Comment by DonJayamanne** [comment]
I tried to work on this, but never managed to get time to finish it off, see here https://github.com/microsoft/vscode-python/pull/12738

**Comment by DonJayamanne** [comment]
Related issue https://github.com/microsoft/vscode-jupyter/issues/1679

**Comment by joyceerhl** [comment]
Validated
