### ISSUE TITLE
When using native notebooks, if kernel selector is shown, interpreter selector should be hidden

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#3979]
![image](https://user-images.githubusercontent.com/30305945/99731205-69869c80-2a72-11eb-9bb9-357c4dd83e39.png)

**Comment by DonJayamanne** [comment]
TODO:
* Restore old code in python extension
* When a notebook with a (viewtype in jupyter) is displayed, then hide interprter

**Comment by greazer** [comment]
Looks like this should be in validate.

**Comment by DonJayamanne** [comment]
Validated in development version of Python extension.
