### ISSUE TITLE
Native Notebooks - "Getting Started" Kernel Behavior

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#398]
When a user is working with a new empty notebook (any number of cells but all empty) and changes the kernel to a different language, have language picker for empty cell match that of the kernel.

**Comment by IanMatthewHuff** [comment]
@DonJayamanne Looks like there is a bug here when validating. 

Two empty python cells, kernel set to python:
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/3af5944d-f649-4c75-8082-97fd58f369eb)

Change kernel to java kernel:
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/15bd6943-0e30-4501-a9b7-2a1f6bece928)

I'd expect two empty java cells. Instead I have two empty java cells and one empty python cell.

**Comment by DonJayamanne** [comment]
Thats odd, I can see that as well.

**Comment by IanMatthewHuff** [comment]
Maybe a vscode side issue with committing the change? Wasn't sure, so pulled it back to look at.

**Comment by DonJayamanne** [comment]
Looks like a VS Code issue.
If there is one cell, then it works, if we have 2 ceels we end up with 1 extra.
If there are 3 cells, then we end up with another extra 2 cells..

**Comment by claudiaregio** [comment]
Does any extra work need to be done to enable the .NET team's experience to work here? Their .NET interactive kernel supports multiple languages, and comes with a default language. In their user's case they would need to have the cell language change to the default language of the kernel.

**Comment by DonJayamanne** [comment]
> enable the .NET team's experience to work here

I don't think so, of things don't work i would expect then to file an issue

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode/issues/111534

**Comment by joyceerhl** [comment]
Validated with Bash kernel: 
![image](https://user-images.githubusercontent.com/30305945/101232344-131a8000-3666-11eb-96dc-ec3896d9b0cd.png)
