### ISSUE TITLE
LaTeX rendering does not work

### ISSUE THREAD

**Issue by hellmrf** [microsoft/vscode-jupyter#3986]
## Environment data

-   VS Code version: 1.52.0-insider (latest, upgraded just now)
-   Jupyter Extension version: v2020.11.372831992 (latest)
-   OS and version: Ubuntu 20.04
-   Python and/or Anaconda version: conda 4.9.0, jupyter core 4.6.1, ipython 7.12.0, Python 3.8 and Julia 1.5.2
-   Type of virtual environment used: any
-   Jupyter server running: Local

## Expected behaviour
LaTeX being rendered, as it does in Jupyter Notebook, Jupyter Lab, Google Colab and any other NBViewer.

**Python:**
![image](https://user-images.githubusercontent.com/25724069/99762136-9371aa80-2ad6-11eb-83d6-3a7eb4d540ed.png)
**Julia:**
![image](https://user-images.githubusercontent.com/25724069/99762154-9bc9e580-2ad6-11eb-8d62-93b912d6fe6d.png)

## Actual behaviour

Markdown cells outputs raw LaTeX, code cells output says "No renderer could be found for MIME type: text/latex":

(The same code above, but in VSCode):
**Python:**
![image](https://user-images.githubusercontent.com/25724069/99762265-d92e7300-2ad6-11eb-9aab-fd9050610d4b.png)
**Julia:**
![image](https://user-images.githubusercontent.com/25724069/99762333-0713b780-2ad7-11eb-9ca1-f9ab819c0ca4.png)

## Steps to reproduce:

1. Install Jupyter with any Kernel;
2. Install VS Code Insiders;
3. Install Jupyter Extension;
4. Create and open a new notebook (or open an existing, whatever);
5. Select any kernel you want;
6. Try writing the fanciest equation with LaTeX math;
7. Cry.

**Comment by CaesarOG** [comment]
Yes, with Code-Insiders, even single dollar-sign Latex between $ $ , does not work in the new version notebooks markdown using the Jupyter extension.

**Comment by DonJayamanne** [comment]
Closing as a dup of https://github.com/microsoft/vscode-jupyter/issues/1216
