### ISSUE TITLE
Matplotlib callbacks not working on VSCode Jupyter Extension

### ISSUE THREAD

**Issue by dcordb** [microsoft/vscode-jupyter#3987]
```python
%matplotlib
import matplotlib.pyplot as plt

def onPick(event):
    print('here')
    print(event)

fig, ax = plt.subplots()

ax.scatter([5], [5], s=1000, picker=True)
fig.canvas.mpl_connect('pick_event', onPick)
plt.show()
```
The above code plots a single point on (5, 5) and adds an event handler to it, so that when the point is clicked it can print info about the clicked point.

If one run this and click the button it should enter on `onPick` function. In a Jupyter Notebook it works fine, while in VSCode Jupyter Extension doesn't.

## Environment data

-   VS Code version: 1.51.1
-   Extension version (available under the Extensions sidebar): v2020.11.371526539
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.358541065
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 19.10
-   Python and/or Anaconda version: Python 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pyenv
-   Jupyter server running: Local

## Expected behaviour

It should print the event when the point is clicked.

![jupyter-ok](https://user-images.githubusercontent.com/49773291/99762438-82b93880-2ac6-11eb-8b9c-381c781bce93.png)

## Actual behaviour

It doesn't print anything besides the backend selection.

![jupyter-wa](https://user-images.githubusercontent.com/49773291/99762449-89e04680-2ac6-11eb-8a8d-513169919214.png)

## Steps to reproduce:

1. Paste this code on a Jupyter cell of VSCode extension.
2. Run it.
3. Click on the point (with left or right click, it doesn't matter).

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Started kernel Python 3
> ~/.pyenv/versions/3.8.5/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/.pyenv/versions/3.8.5/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
```

</p>
</details>

**Comment by dcordb** [comment]
By the way, if on `onPick` function we add an artist to the axes instance it adds it and shows it. Only the standard output isn't shown.

```python
import matplotlib.pyplot as plt

def onPick(event):
    print('here')
    print(event)
    ax.text(5, 5, 'Test Text!')
    plt.draw()

fig, ax = plt.subplots()

ax.scatter([5], [5], s=1000, picker=True)
fig.canvas.mpl_connect('pick_event', onPick)
plt.show()
```

In the above code I added a text to current axes instance, if you click on the point you will see it, so onPick is called.

**Comment by DonJayamanne** [comment]
I'm sorry for the delay in getting back to you on this issue.
Will be looking into this righ tnow.

**Comment by DonJayamanne** [comment]
I can confirm this doen't work at our end.
Looks like we need to handle some custom messages.

**Comment by DonJayamanne** [comment]
From what I can tell this is now working in VS Code.
Please feel free to re-open this issue or file an new issue.
I believe this was fixed last month as part of the other IPYWidget issues  https://github.com/Microsoft/vscode-jupyter/issues/9503
