### ISSUE TITLE
Native Notebooks - Duplicate Kernel Options 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#399]
Getting interpreter duplicates in the kernel options

Interpreter Options: 
![image](https://user-images.githubusercontent.com/19276747/98176857-3824a300-1eae-11eb-9caf-f04de4107b84.png)

Kernel Options:
![image](https://user-images.githubusercontent.com/19276747/98179743-4fff2580-1eb4-11eb-8a27-f62efd51406d.png)

**Comment by rchiodo** [comment]
I'd argue that this is not must fix. It still works and it's only an inconvenience.

**Comment by greazer** [comment]
Agreed.

**Comment by DonJayamanne** [comment]
Related to #4023

**Comment by DonJayamanne** [comment]
Fixed
