### ISSUE TITLE
Cells with hyperlink tag (<a>) and apostrophe (') are not rendered correctly

### ISSUE THREAD

**Issue by dimitry-ishenko** [microsoft/vscode-jupyter#3990]
Issue Type: <b>Bug</b>

Please see example:

![Peek 2020-11-20 12-02](https://user-images.githubusercontent.com/2858291/99828084-7a91e500-2b28-11eb-8a3d-59bc6170e42d.gif)

Extension version: 2020.11.372831992
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.4.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 2082)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.23GB (5.16GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id afa44bcd-1274-4e79-83bd-74c25be547ee|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by claudiaregio** [comment]
Thanks @dimitry-ishenko , I am able to reproduce this. Will go over this at our triage meeting

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adjusting this functionality at this time. We are moving toward a new implementation for notebooks in VS Code. That will address this problem. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
