### ISSUE TITLE
Don't default to exporting HTML and PDF files to the root (/) directory of the user's machine

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-jupyter#3991]
Currently when you export to PDF or HTML, the location of the exported file is the root of the user's machine (e.g. /filename.pdf)

Users working on remote hosts (e.g. Azure ML compute, Azure VM) are sometimes unable to write to the root of their host. They have to manually change the export path to a directory that they can write to.

Ideally the exported path defaults to either the root of the user's workspace, current working directory, or the directory in which their Notebook is in.

**Comment by DonJayamanne** [comment]
Bug - as this breaks simple HTML in AML (the export doesn't work with default directory & it needs to be changed to workspace) - could be permissions or the like.
Either way, not the best default experience

**Comment by greazer** [comment]
This more seriously affects remote scenarios.

**Comment by IanMatthewHuff** [comment]
Validated. Didn't default to Mac home directory anymore and tested from Native Notebooks, old webviews, and custom editors.
