### ISSUE TITLE
Kernel Switch Problem

### ISSUE THREAD

**Issue by dariush-bahrami** [microsoft/vscode-jupyter#3995]
## Environment data

-   VS Code version: 1.51.1
-   Python Extension version: v2020.11.371526539
-   Jupyter Extension version: v2020.11.372831992
-   OS: Windows 10 64bit
-   Python version: 3.8.3, 3.7.9
-   Type of virtual environment used : conda
-   Jupyter server running: Local

## Expected behaviour

I created blank jupyter notebook in conda environment which has tensorflow2 installed on that; then switched kernel to base conda env and restarted jupyter kernel. i expected  an error after importing tensorflow in a cell because now i am in a different environment that doesn't have tensorflow package in it.

## Actual behaviour

The cell containing "import tensorflow" executed without any error

## Steps to reproduce:
![jupyter_kernel_change_bug](https://user-images.githubusercontent.com/43555207/99848813-b4e29d00-2b8f-11eb-83b9-74e04571e897.gif)

**Comment by rchiodo** [comment]
Can you do an 
```
import sys;
print(sys.executable)
```
to make sure the kernel is the one you selected?

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, please could you provide the following:
* Ensure you have debug logging enabled
	* Go into settings and select `Jupyter->Logging`.
	* Select `debug`
	* Please restart VS Code
* Open a notebook
* Change the kernel to the Conda environment.
* Run a new cell with the following:
    * Ensure you have selected the new conda environment.
```python
import sys
print(sys.executable)
```
* Confirm the correct conda environment has been used.

If not, please provide the contents from the `Jupyter` output panel.

**Comment by dariush-bahrami** [comment]
> Thanks for filing this issue, please could you provide the following:
> 
> * Ensure you have debug logging enabled
>   
>   * Go into settings and select `Jupyter->Logging`.
>   * Select `debug`
>   * Please restart VS Code
> * Open a notebook
> * Change the kernel to the Conda environment.
> * Run a new cell with the following:
>   
>   * Ensure you have selected the new conda environment.
> 
> ```python
> import sys
> print(sys.executable)
> ```
> 
> * Confirm the correct conda environment has been used.
> 
> If not, please provide the contents from the `Jupyter` output panel.

![jupyter_kernel_change_bug_logging](https://user-images.githubusercontent.com/43555207/99858400-bbc6db00-2ba2-11eb-84c0-ce7178cc9d8c.gif)
[jupyter_debug_log.txt](https://github.com/microsoft/vscode-jupyter/files/5576522/jupyter_debug_log.txt)
I the kernel switch only works for two kernels which i linked to jupyterlab before (base and tf). the problem is jupyter extention list a lot of kernels (some of them even appear several times) which can not be selected and  in order to using them some extra manual effort should be done to link them to the jupyterlab. sorry about my english

**Comment by DonJayamanne** [comment]
Closing as a dup of #4011
