### ISSUE TITLE
Hover to add cell is unreliable

### ISSUE THREAD

**Issue by robotdad** [microsoft/vscode-jupyter#3997]
## Environment data

Current insiders build of VSCode and the Jupyter extension.

## Expected behaviour

Some way to add a new cell that is consistently on the screen to click or a keyboard combo.

## Actual behaviour

You have to hover the mouse precisely over the cell border to get an interface that surfaces buttons to add a cell. No keyboard shortcut information is shown so I don't know what combo to use to avoid this interface.

**Comment by robotdad** [comment]
Ok, if I hover over the interface that appears when I hover over the other interface than there is a B option shown for adding code cells. Would be nice to have an option to add markdown cells as well.

**Comment by robotdad** [comment]
Adding a new code cell using B defaults to plaintext which is not what I want. Python would be a better default. Last used would work as long as it wasn't plain text. I don't want to create markdown or plaintext cells followed by more of the same. I want to write my docs in a text cell, then add a new code cell, repeat.

**Comment by claudiaregio** [comment]
Thanks for the feedback Marc! I have forwarded your issue to VS Code. 

There is a known bug that when you add a code cell after a markdown cell, the addition defaults to a plain text cell. Both teams are working on resolving this, you can track updates here. 
https://github.com/microsoft/vscode/issues/108464

If you go into File -> Preferences -> Keyboard Shortcuts and look for the commands below, you can add your own custom shortcut to by clicking the + to the left. 
![image](https://user-images.githubusercontent.com/19276747/99859186-2eed3480-2b44-11eb-80b3-6b71b589b4ca.png)
