### ISSUE TITLE
"jupyter.sendSelectionToInteractiveWindow": false sends code to Interactive Window

### ISSUE THREAD

**Issue by andycraig** [microsoft/vscode-jupyter#3999]
Issue Type: <b>Bug</b>

It seems like the setting `jupyter.sendSelectionToInteractiveWindow` has no effect when running the command `Jupyter: Run Selection/Line in Interactive Window`. The code is always sent to the Interactive Window, even if the setting is set to `false`.

Code can still be sent to the Python terminal with the command `Python: Run Selection/Line in Python Terminal`. Perhaps the setting `jupyter.sendSelectionToInteractiveWindow` shouldn't exist anymore?

**To reproduce**

1. In the Settings UI, disable `Jupyter: Send Selection to Interactive Window` (i.e., no checkmark)
1. Create a file 'temp.py' with the following content:
    ```py
    x = 1
    ```
1. Run command `Jupyter: Run Selection/Line in Interactive Window`

**Expected:** `x = 1` is run in the terminal.

**Actual:** An Interactive Window is launched and `x = 1` is run there.

<details>
<summary>settings.json</summary>

Here is my entire `settings.json` file. Following the steps above doesn't put `"jupyter.sendSelectionToInteractiveWindow"` in `settings.json`, so to double check I've explicitly set `"jupyter.sendSelectionToInteractiveWindow": false`.

```json
{
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter-notebook",
            "filenamePattern": "*.ipynb"
        }
    ],
    "python.insidersChannel": "daily",
    "jupyter.insidersChannel": "off",
    "jupyter.sendSelectionToInteractiveWindow": false
}
```
</details>

Extension version: 2020.11.372831992
VS Code version: Code - Insiders 1.52.0-insider (caf01baa45b9816e2e1d8a2de22b40cf89459c03, 2020-11-20T07:26:12.345Z)
OS version: Linux x64 4.15.0-123-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2802)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.70GB (0.61GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 3b2efe2b-53ac-4b07-b763-4b6c235e501a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2prompt:30219162
vstry244:30226747
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by joyceerhl** [comment]
> The code is always sent to the Interactive Window, even if the setting is set to false.

This sounds like a bug. Code should only be sent to the interactive window if that setting is `true`, as that setting controls the `jupyter.ownsSelection` context key. We use `jupyter.ownsSelection` everywhere else that we contribute this command, except for where we include it in the command palette. I think the fix here would be to add `&& jupyter.ownsSelection` to the when clause below: https://github.com/microsoft/vscode-jupyter/blob/9d35e91126a2c3e0dca31598e141ea575c1d96e9/package.json#L1169-L1171

**Comment by joyceerhl** [comment]
On second thought I'm not sure there's actually a bug here. The setting is useful for controlling the enablement of keybindings, but even if we updated the when clause for 'Run Selection/Line In Interactive Window', this would just result in the command not appearing in the command palette at all when `jupyter.sendSelectionToInteractiveWindow` is set to true. If the user is explicitly running the 'Run Selection/Line In Interactive Window' command, it seems reasonable to allow that, and I wouldn't expect a command called 'Run ... In Interactive Window' to start sending code to the integrated terminal based on a setting. I.e. I don't think this issue needs a bug fix.

**Comment by andycraig** [comment]
Hi @joyceerhl, thank you for considering. I had thought changing `Jupyter: Send Selection to Interactive Window` was intended to change the effect of  `Jupyter: Run Selection/Line in Interactive Window`, but it sounds like its effect is to change the value of `jupyter.ownsSelection`. (I think I had got confused because I rebound one of the <kbd>Shift+Enter</kbd> commands without rebinding the other one, so it seemed like changing the setting wasn't changing anything.)

I agree that it's not a bug after all. I will close. Thanks again!
