### ISSUE TITLE
Frozen Input Interactive Window

### ISSUE THREAD

**Issue by sjnarmstrong** [microsoft/vscode-jupyter#4001]
## Environment data

-   VS Code version: 1.51.1
-   Extension version (available under the Extensions sidebar): v2020.11.371526539
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.372831992
-   OS (Windows | Mac | Linux distro) and version: Pop!_OS 20.10
-   Python and/or Anaconda version: Python 3.6.10 conda 4.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

When I type values into the interactive window i want it to let me type.

## Actual behaviour

Occasionally when i type values into the window it freezes up and doesn't let me type. This only happens occasionally and it is usually just after I copy code or when I am running another script in the terminal. I sometimes find that spamming ctrl+c&ctrl+v on the interactive window lets me type again.

## Steps to reproduce:

1. Open an interactive window
2. Copy contents from code.
3. Attempt to paste the values into the edit box of the interactive window.

## Logs
N/A

**Comment by joyceerhl** [comment]
Hey @sjnarmstrong, sorry for the trouble here. This is a known issue that we're tracking in https://github.com/microsoft/vscode-jupyter/issues/1293. We're actively investigating that issue so I'll be closing this as a duplicate. Thanks for filing an issue and again sorry for the trouble caused.
