### ISSUE TITLE
Data Viewer fails to show anything but simple lists and dicts

### ISSUE THREAD

**Issue by AltfunsMA** [microsoft/vscode-jupyter#4003]
## Environment data

-   VS Code version: 1.51.1
-   Python Extension version: v2020.11.371526539
-   Jupyter Extension version: v2020.11.372831992
-   OS: Windows 10 but SSH'd to Ubuntu 16.04.
-   Python and/or Anaconda version: 3.8.2
-   Type of virtual environment used: venv
-   Jupyter server running: Local (on Linux machine)

## Expected behaviour

1. Variables whose contents are visible under 'value' in the variable explorer should be available in the Data Viewer. 

2. If part of the data is too large to be displayed in full, it should be truncated.

3. If object has an informative string visible under 'Value', this should be displayable 

## Actual behaviour

1. Anything beyond a simple list or dict gets stuck loading A list of several thousand short strings loads instantaneously; but anything containing a Tensor object will not display no matter how small.

2. A pandas Dataframe (755 x 9) containing some relatively long strings also gets stuck loading indefinitely.

3. I can hover over or resize the Value column, e.g. a BERT model specification see most of the description; but there's no way of clicking on it to see it in full even though the string is clearly visible.

## Steps to reproduce:

1. Create complex list containing objects from any package or a large dataframe in interactive window.
2. Attempt to inspect the object by double clicking on the variable explorer.

**Comment by joyceerhl** [comment]
Hi @AltfunsMA, thanks for your feedback! We plan to add Tensor support to the data viewer in https://github.com/microsoft/vscode-jupyter/issues/304. 

I'd like to understand your use case better for 2) and 3). What would your ideal truncation behavior be like, and are you saying that you would like to be able to view strings in the data viewer as well?

**Comment by AltfunsMA** [comment]
Hi @joyceerhl , 

On 2, I most often use Rstudio and the tidyverse, so I'm used to storing texts and their metadata in dataframes. A feature like what happens with the `View()` function in Rstudio would be what I'd have in mind. 

No need to see the very last word of each text string; but it's good to know if the first couple of sentences match the metadata. It's a quick sanity check that whatever pre-processing I'm doing is proceeding as expected. Just truncating each cell of the dataframe at 1000 chars or so would do. As it stands, any large dataframe cannot be inspected at all. Of course, if you could manage it so that you could progressively dig deeper into objects and expose different parts as needed (while loading the overall structure); that would be good, but that may be a lot of effort for little usage.

On 3, I'm not au fait with the details, but it seems objects like BERT models expose a "docstring" that describes their behaviour and/or specification. In this case, the string is really short, not more than a couple of sentences and it contains important information. Being able to see the full specification would be great.

Hope this helps!

In general, I find Rstudio's variable explorer is far better suited to data science tasks, where you want to see at a glance

**Comment by greazer** [comment]
Tensors will be supported. There are a couple of other issues with Data Viewing we should consider.

**Comment by joyceerhl** [comment]
@AltfunsMA You should now be able to inspect tensors in the Jupyter extension's data viewer as of the April 2021 release: https://devblogs.microsoft.com/python/jupyter-in-visual-studio-code-april-2021-release/

**Comment by greazer** [comment]
We should at least do some work to let the user know what happened.

**Comment by IanMatthewHuff** [comment]
Closing as we have other issues relating to general complex types and this one was specific for Tensors.
