### ISSUE TITLE
Address notebookUsageTracker perf issues

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#4004]
From https://github.com/microsoft/vscode-python/pull/14752/files#r527840360 

> We already have code that looks for ipynb files or the like (notebookUsageTracker).
& this causes vscode to hang (CPU issues & i think memory issues).
Scenario is:
User has a few virtual envs in their local workspace
Or they open a network drive
Our code scans through all all folders (nested) & this is a lot of IO.
Suggestion.
Search only 2 levels of folders
Take the users search.exclude setting from settings.json into account when perfoming searches (if vs code is ignoring searching through directories, then we too should ignore this).

More context: 
https://github.com/microsoft/vscode-python/issues/11173
https://github.com/microsoft/vscode-python/issues/12467

Fix would be to apply `search.exclude` when calling `workspace.findFiles`. By default it only applies `find.exclude`. Note that `search.exclude` settings can contain sibling patterns as their values instead of booleans, which `findFiles` does not support: https://github.com/microsoft/vscode/issues/48674#issuecomment-384835796 

In this case since `findFiles` doesn't support sibling patterns I would vote to combine any globpatterns whose value is not `false` in `search.exclude` and pass that as a comma-separated globpattern to `findFiles`.

**Comment by sc420** [comment]
Facing the same problem, my workspace is a network drive, I noticed rg.exe spawning every time when I opened a .py file.
The only workaround for me now is to open the subdirectory as project root to reduce the search space and don't open any .py files on the network drive.

**Comment by greazer** [comment]
I believe this has been addressed. Please reopen if I'm incorrect.
