### ISSUE TITLE
Old code executing even after I changed it

### ISSUE THREAD

**Issue by Ascii-abhishek** [microsoft/vscode-jupyter#4005]
Issue Type: <b>Bug</b>

executing a cell sometimes keep on executing old written code in same cell
like: if i wrote a wrong code and executed it. it will show error but then i fixed the code and execute it again, but it will show same error output (python error output shows old code )

**cell current code:**
```py
import ast
ast.literal_eval(data.iloc[0, 'test'])
```
**error out:**
```terminal
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-81-be7943709176> in <module>
      1 import ast
----> 2 ast.literal_eval(ata['test'].tolist())[0]

NameError: name 'ata' is not defined
```

Extension version: 2020.11.372831992
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: disabled_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.90GB free)|
|Process Argv|--crash-reporter-id 2b5b20a5-b66b-41ae-8480-0fa215d2973d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joyceerhl** [comment]
@ascii-abhishek thanks for reporting an issue and sorry for the trouble here. We've had reports of this issue in the past but have been unable to consistently reproduce it. Does this bug reliably appear for you?

**Comment by saguerraty** [comment]
Hi there, 
If you reload the kernel it might work (does so for me at least). though it would be ideal for it to be sufficient to import the module again for the changes to take effect. For Data science it is far from ideal to have to restart the kernel to be able to fix issues with modules :)

(I'm using a virtual env on anaconda using v2020.12.424452561 of the extension and ipython 7.16.1)

**Comment by Ascii-abhishek** [comment]
@joyceerhl 
I'm not a frequent user of jupyter (new to this and mostly hobby work). Since the bug encounter, I shifted my remaining dev to browser-based. Since you are already aware of it, and there may be other open issues for this, I think it would be best to close this one. (created as I couldn't find a similar case). Thanks for your quick response.

@saguerraty  
thanks for the tip. I'll sure to try it next time I encounter the problem.
