### ISSUE TITLE
Jupyter will not change environments when using conda

### ISSUE THREAD

**Issue by jackbrucesimpson** [microsoft/vscode-jupyter#4011]
## Environment data

-   VS Code version: 1.5.1
-   Jupyter Extension version (available under the Extensions sidebar): 2020.11.372831992
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.8 and 4.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): coda
-   Jupyter server running: Local

## Expected behaviour

When I click the Python version in the top right a drop down appears that allows me to select my Jupyter environment. When I make this selection, it should change the environment the notebook is being run in.

## Actual behaviour

The environment does not change - selecting the environment does nothing.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Click Python version in top right
2. Select environment from dropdown that appears
3. In the bottom right a pop-up will momentarily appear stating that it is switching environments
4. However once it disappears after a fraction of a second, the environment has not changed.

**Comment by joyceerhl** [comment]
Hey @jackbrucesimpson, sorry about the trouble here. Could you please provide detailed logs by doing the following:
1. In your settings.json, add "jupyter.logging.level": "debug"
2. Reload VS Code
3. Repeat your steps above
4. Open the "Jupyter" output tab and copy and paste the logs from there 

That will help us figure out what's going on here.

Also, I see you're using conda--are you switching from one conda environment to another?

**Comment by jackbrucesimpson** [comment]
Thanks so much for the help! Yes, I am switching from one conda environment to the other. This is what I get - I'm not sure why it thinks dependencies are missing - in the past I was able to switch between environments with Jupyter without a problem.

Info 2020-11-25 00:22:09: Found matching interpreter based on metadata, for the kernel python3, Python 3
Info 2020-11-25 00:22:09: installMissingDependencies C:\Users\jack.simpson\.conda\envs\conda-env\python.exe
Info 2020-11-25 00:22:09: > ~\.conda\envs\conda-env\python.exe c:\Users\jack.simpson\.vscode\extensions\ms-toolsai.jupyter-2020.11.372831992\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> ~\.conda\envs\conda-env\python.exe c:\Users\jack.simpson\.vscode\extensions\ms-toolsai.jupyter-2020.11.372831992\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
Info 2020-11-25 00:22:10: Install Missing Dependencies, Class name = f, completed in 489ms, has a falsy return value, Return Value: 0
Info 2020-11-25 00:22:10: Initial setup for file:///c%3A/Users/jack.simpson/OneDrive%20-%20aemc.gov.au/Analytics/ACT_Renewable_Tariffs/201119_lmp.ipynb starting ...
Info 2020-11-25 00:22:10: Initialize config for plots for file:///c%3A/Users/jack.simpson/OneDrive%20-%20aemc.gov.au/Analytics/ACT_Renewable_Tariffs/201119_lmp.ipynb
Info 2020-11-25 00:22:10: Kernel switching to busy
Info 2020-11-25 00:22:10: Kernel switching to idle
Info 2020-11-25 00:22:10: Initial setup complete for file:///c%3A/Users/jack.simpson/OneDrive%20-%20aemc.gov.au/Analytics/ACT_Renewable_Tariffs/201119_lmp.ipynb

**Comment by jackbrucesimpson** [comment]
Do you happen to know what might be going wrong? I've also noticed that the auto-save of Jupyter notebooks has also stopped working as well when it worked perfectly in the past.

**Comment by joyceerhl** [comment]
Ah it doesn't think there are missing dependencies, that's just a log message we print as we're checking that the selected interpreter has all the required dependencies installed.

If you run the following code in a cell before and after switching kernels, what do you get? Would like to know if it's a UI issue or if the kernel is legitimately not being switched.

**Comment by jackbrucesimpson** [comment]
Thanks so much for looking into this - it definitely does not change kernels - I noticed this was a problem because I have GeoPandas installed in one of my conda environments which has worked perfectly in the past or if I explicitly run Jupyter in the browser from that conda environment. However, it will give me a ModuleNotFoundError when I try to run it in Jupyter in VS Code now.

**Comment by jackbrucesimpson** [comment]
I've also noticed despite having auto-save functionality enabled so that it saves every 20 seconds by default (which has worked in the past) the Jupyter notebooks have become rather tempramental and will sometimes refuse to autosave for long periods of time.

**Comment by joyceerhl** [comment]
Ah, you're the third person to mention autosave not working. Thanks for bringing that up. Can you reliably trigger the failure to autosave by any chance?

**Comment by jackbrucesimpson** [comment]
Sadly it doesn't seem to be something I can consistently replicate - it sometimes saves automatically and sometimes it just stops and I notice the file is marked as having not saved in a while.

By the way, I just wanted to say thanks for all the great work you've been doing with Jupyter in VS Code - I shifted over a few months ago and aside from these issues its been fantastic :)

**Comment by ayushnoori** [comment]
Quick note to mention that I have occasionally noticed that Jupyter is able to run the virtual environment when I create a completely new Python notebook; however, as soon as I save the notebook, the bug returns. Not sure if this behavior is consistent.

**Comment by IanMatthewHuff** [comment]
@jackbrucesimpson Could you try something out for your scenario? Could you try installing VS Code - Insiders and the insiders version of the Python extension (which automatically installs the Jupyter extension as well) along with that, and then trying the same kernel switch? There have been a couple of similar issue recently relating to conda environment activation (which is what is happening under the covers when switching kernels) that might be cleared up with the most recent insiders builds.

https://github.com/microsoft/vscode-python/issues/14812

**Comment by neeveermoree** [comment]
I have the same bug. Changing conda environment at bottom left corner or python interpreter at top right corner does not changing the contents of sys.exeutable. Creating a new notebook and working in it makes the job done only for this particular notebooks. However others still refuse to work with selected conda env or python interpreter. If you reopen VS Code it stops working as well as the others.

**Comment by johncai117** [comment]
Hi, I have the same bug too. It works fine when changing to Python interpreters created by venv, but not those created by conda. I can see those conda Python interpreters but clicking on them does nothing (also doesn't change the contents of sys.executable).

**Comment by IanMatthewHuff** [comment]
@neeveermoree and @johncai117 Did either of you try the vs-code insiders / python extension insiders combo that I mentioned in my previous post? We believe that there is a possible issue in the stable versions that might be causing this. Knowing if you see the same issues on insiders would help us to narrow down our investigation. VS Code - Insiders has a very clean install and uninstall and keeps separate context from stable VS Code, so it's quick and safe to install it to check out.

VS Code Insiders: https://code.visualstudio.com/insiders/
Python Insiders: https://github.com/microsoft/vscode-python/blob/main/CONTRIBUTING.md#development-build

If anyone is still seeing the issue on insiders you can do the following.

Set the vscode setting Jupyter->Logging->Level to "debug." Then repro the issue of changing the kernel via the kernel selector in the notebook. After that open the Jupyter section of the Output window in VS Code. Copy out everything there, save it in a file, and post that file attached to a comment here. I can look into those logs.

**Comment by jackbrucesimpson** [comment]
Thanks @IanMatthewHuff - I'd try out the Insiders version if my work gave me install permissions on my machine, but maybe some of the others can test it out.

**Comment by jackbrucesimpson** [comment]
Just had the Python extension update with the December release - it doesn't look like this has fixed it.

**Comment by IanMatthewHuff** [comment]
For the folks in this thread, one thing to try here (as we've had a few reports of conda environment issues here and in other issues) would be the following:

- Open a Command Prompt or Terminal (not an anaconda prompt)
- Run the conda activation command. On Windows (will change based on installation) would be something like: `C:\Users\[UserName]\Anaconda3\Scripts\activate`
- Then after the base activation explicitly activate the environment you are targetting like `conda activate myEnv`

What we are looking for here is anything in the output that looks like an error even if it's benign and you can still activate and use the environment. Recently on windows we've been seeing lots of issues like this:
https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#the-system-cannot-find-the-path-specified-on-windows
These errors sometimes don't block the environment activation, but if we see anything in stderr during our kernel startup (also on kernel switch) we are going to fail out and not use the environment. Might be the cause of some of these issues.

**Comment by jackbrucesimpson** [comment]
Hi Ian, I don't think I'm triggering anything when I run it.

![image](https://user-images.githubusercontent.com/6303549/102561454-828d7680-4120-11eb-8a05-f9a7d4bc551d.png)

**Comment by constructor-s** [comment]
> 
> 
> @neeveermoree and @johncai117 Did either of you try the vs-code insiders / python extension insiders combo that I mentioned in my previous post? We believe that there is a possible issue in the stable versions that might be causing this. Knowing if you see the same issues on insiders would help us to narrow down our investigation. VS Code - Insiders has a very clean install and uninstall and keeps separate context from stable VS Code, so it's quick and safe to install it to check out.
> 
> VS Code Insiders: https://code.visualstudio.com/insiders/
> Python Insiders: https://github.com/microsoft/vscode-python/blob/main/CONTRIBUTING.md#development-build
> 
> If anyone is still seeing the issue on insiders you can do the following.
> 
> Set the vscode setting Jupyter->Logging->Level to "debug." Then repro the issue of changing the kernel via the kernel selector in the notebook. After that open the Jupyter section of the Output window in VS Code. Copy out everything there, save it in a file, and post that file attached to a comment here. I can look into those logs.

So I was experiencing the same/similar issue with regular non-insider versions. Tried the insider version for both VS Code [1] and Python extension (it asked me if I want to install the insider version of it, and I pressed yes weekly) [2]. 

There is now a new interface for Jupyter notebooks (looks modern but need getting used to it...) Now as far as I can tell there are three places for switching interpreters:
1. Bottom left next to the "x" and "!" - this is some sort of global Python setting for regular scripts?
2. If I bring up the command palette and search for Jupyter, there is an option for "Select Interpreter to Start Jyputer Server"
3. If I open an `.ipynb` file now there is no old toolbar on the top but on the bottom right there is another place where Python version is displayed. 

So I wasn't getting switching kernels to work until: I set 1 and 2 above to my base Anaconda environment and started to switch on the third option at the bottom right. I have a long list of environments but here are the interesting ones that pop up when I press on the bottom right:
1. Base Anaconda `Python 3 mstoolsai.jupyter PATH\TO\Anaconda3\python.exe`
2. My own environment called vf `Python 3 mstoolsai.jupyter PATH/TO/Anaconda3/envs/vf\python.exe` Note the backslashes instead of forward slashes except for the final `\python.exe`
3. `Python 3.7.4 64-bit (conda) mstoolsai.jupyter PATH\TO\Anaconda3\python.exe`
4. `Python 3.7.4 64-bit ('vf': conda) mstoolsai.jupyter PATH\TO\Anaconda3\envs\vf\python.exe` Note they are all forward slashes

So as far as I can tell by printing out `sys.executable`, I can properly switch to both 3 and 4 but if I choose to either 1 and 2 it always go to 1 - the base conda. 

I have no idea how VC Code extensions work but here is my guess from the debug log:

When I switch to 3 the log shows
```
Info 2020-12-26 11:19:21: Getting preferred kernel for file:///c%3A/Users/USERNAME/SOME/PATH/test.ipynb
Info 2020-12-26 11:19:21: Searching for kernel based on {"name":"python37464bitbasecondabf7a8476334344fb8cd256dd1fa80879","display_name":"Python 3.7.4 64-bit ('base': conda)"} for c:\Users\USERNAME\SOME\PATH\test.ipynb
```

The `"name"` seems to be a unique ID. 

However, when I switch to 2
```
Info 2020-12-26 11:38:36: Getting preferred kernel for file:///c%3A/Users/USERNAME/SOME/PATH/test.ipynb
Info 2020-12-26 11:38:36: Searching for kernel based on {"name":"python3","display_name":"Python 3"} for c:\Users\USERNAME\SOME\PATH\test.ipynb
```
It seems to me that it is trying to find a kernel with name "python3", but both 1 and 2 are called "python3", so it just decided to start interpreter 1. 


[1] VS Code ```Version: 1.53.0-insider (system setup)
Commit: 4a875e23d20b64504a818834f3fa4c40adb8d480
Date: 2020-12-21T12:33:38.481Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.18363```
[2] Python ```ms-python.python v2021.1.442908725-dev``` Jupyter ```ms-toolsai.jupyter v2020.12.414227025```
* For completeness I also installed Sublime Extension and Pylance when it popped up. I also went into the Python extension settings and modified one thing - I told it where `conda.exe` is but I am not sure if it mattered since I think it was able to find all of my interpreters automatically.

**Comment by munich-ml** [comment]
@IanMatthewHuff 

> For the folks in this thread, one thing to try here (as we've had a few reports of conda environment issues here and in other issues) would be the following:
> - Open a Command Prompt or Terminal (not an anaconda prompt)
> - Run the conda activation command. 
> - On Windows (will change based on installation) would be something like: C:\Users\[UserName]\Anaconda3\Scripts\activate
Then after the base activation explicitly activate the environment you are targetting like conda activate myEnv
> What we are looking for here is anything in the output that looks like an error even if it's benign and you can still activate and use the environment. Recently on windows we've been seeing lots of issues like this:
https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#the-system-cannot-find-the-path-specified-on-windows
These errors sometimes don't block the environment activation, but if we see anything in stderr during our kernel startup (also on kernel switch) we are going to fail out and not use the environment. Might be the cause of some of these issues.

Hi Ian,
I'm seeing all the symptoms you described on my machine:

1. `Jupyter select a kernel` doesn't affect kernel that is actually used. It's (almost) always the base kernel. 
-- However, sometimes my env_kernel is used, but a havn't found a way to consitantly reproduce that.
-- I tried your experiment: When executing `conda activate my_env` from cmd and lauch VSCode after that, it uses my_env. In that case, however, I cant' switch back to base. 
2. I'm also having issues with the Windows PATH. 
-- I had to add `C:\ProgramData\Anaconda3` manually to PATH and still it wouldn't find `python`.
-- Part of that was solved by [disabling App execution aliases](https://superuser.com/questions/1437590/typing-python-on-windows-10-version-1903-command-prompt-opens-microsoft-stor)
3. One more thing I wonder is why VSCode lists 4 kernels although there are just 2:
![image](https://user-images.githubusercontent.com/53127691/103477159-1d8e7d80-4dbc-11eb-9365-15a869646e71.png)

This inconsistant behaviour drives me crazy, thus I would be really thankful for any help. I'm willing to conduct experiments on my machine, too!

**Comment by DonJayamanne** [comment]
@munich-ml thanks for reaching out. I'm sorry about this issue.
Please could you try the following:

1. Add conda executable to the settings
* Locate the fully qualified path of the  `conda.exe` executable.
* Update your settings.json to point to that
```json
"python.condaPath": "<fully qualified path to conda executable> ... c:\\userName\\conda.exe",
```
* Try again.

2. If previous step doesn't work then test with logging & provide the logs
* Please could you enable logging in Jupyter extension as follows:
	* Open settings & go into `Jupyter->Logging`
	* Change the value to `debug`
	* Reload VS Code,
* Please could you enable logging in Python extension as follows:
	* Open settings & go into `python->Logging`
	* Change the value to `debug`
	* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.
* Attempt to repro the issue & then copy the output from the `Python` output panel.

We have had a number of issues in the past related to activation of environments. I suspect this is related to that.


Thanks

**Comment by munich-ml** [comment]
@DonJayamanne 
1. Adding conda.exe
I added `"python.condaPath": "C:\\ProgramData\\Anaconda3\\Scripts\\conda.exe"` to my settings, but that didn't help. 

2. Logging
I added the `debug` log levels. Here are the outputs:
- [jupyter_log.txt](https://github.com/microsoft/vscode-jupyter/files/5768901/jupyter_log.txt)
- [python_log.txt](https://github.com/microsoft/vscode-jupyter/files/5768902/python_log.txt)

Thanks for your help!

**Comment by DonJayamanne** [comment]
@munich-ml Thanks for the logs
* Please could you open your command prompt (not powershell) and run the following and let me know what you get (Please send a screenshot of the output)
`C:/ProgramData/Anaconda3/Scripts/activate && conda activate plotly_env && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\holge\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py c:/Users/holge/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/printEnvVariables.py`

**Comment by munich-ml** [comment]
@DonJayamanne 

- My conda version:
![image](https://user-images.githubusercontent.com/53127691/103774554-102bfa00-502d-11eb-98fd-61fb74f14eac.png)

- Screenshot on script execution
![image](https://user-images.githubusercontent.com/53127691/103774801-7153cd80-502d-11eb-9217-d031d206e33f.png)

- Screenshot on script execution after `conda activate plotly_env`
![image](https://user-images.githubusercontent.com/53127691/103775293-24bcc200-502e-11eb-9084-87005e386af0.png)

In comparison those screenshots look identical. I executed those scripts a couple times and sometimes I did see differences in `CONDA_PREFIX_1` and `CONDA_SHLVL`. However, those differences weren't clearly reproducible.
![image](https://user-images.githubusercontent.com/53127691/103779190-ac58ff80-5033-11eb-889b-a1be23013989.png)

**Comment by DonJayamanne** [comment]
@munich-ml Thanks for the details.
I can see that somethign isn't working, however still unable to put my finger on it.
I'll probably have to create a custom version of the extension with some additional logging & possible fixes (if i identify anything).

Sorry for the trouble. Will get back to you soon.

**Comment by jackbrucesimpson** [comment]
Latest version of Jupyter seems to have fixed the problem!

**Comment by jackbrucesimpson** [comment]
Nope, looks like the latest version of Python has broken it again, or it was a freak event with the notebook on Friday where it worked briefly. Back to being unable to change anaconda kernals.

**Comment by ayushnoori** [comment]
@jackbrucesimpson was just about to comment here as well - this seemed to work for me too until today. I am working on both a local machine and a remote server using the Remote - SSH extension. At present, it appears that switching anaconda environments works locally, but not on my remote machine (perhaps due to version).

**Comment by jackbrucesimpson** [comment]
I've just been working locally and unfortunately switching environments does not work for me at all :(

**Comment by grg2rsr** [comment]
Are there any news on this? I am also affected by this and it pretty much renders vscode unusable to me at the moment.

**Comment by jackbrucesimpson** [comment]
Yeah same here, I went back to using them in the browser - it's a shame because I preferred using notebooks in VS Code.

**Comment by JVedant** [comment]
Faced the same issue and I just downgraded the version to v2020.12.414227025 and it works fine, seems like the latest versions are still crashing the kernel.

![VSCode Jupyter extension version](https://user-images.githubusercontent.com/39456727/109009524-a34fea80-76d4-11eb-9106-0e54834daebb.png)

**Comment by DonJayamanne** [comment]
@grg2rsr @jackbrucesimpson @JVedant 

I'm sorry to hear about these issues.
Please could you re-install the latest version of the Jupyter extension & provide the following information

1. Are you using Conda, if so what version
2. Please provide information about what environment you are using (so I can match up the environments against what is in the logs)
2. Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `debug`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by jackbrucesimpson** [comment]
Just tried out VS Code again this morning and after the Jupyter extension updated it's working again!

**Comment by munich-ml** [comment]
The latest Jupyter extension (v2021.3.619093157) works for me, too.

Thanks to all contributors!

**Comment by chetanchawla** [comment]
This error occurs for me on the latest Jupyter extension (v2021.3.619093157), so I have switched to v2020.12.414227025 and it seems to solve the problem.
