### ISSUE TITLE
Separate settings for Jupyter notebooks and Interactive windows

### ISSUE THREAD

**Issue by AltfunsMA** [microsoft/vscode-jupyter#4012]
The main reason I'm using VS code at the moment is because of the ability to have interactive windows with output alongside normal python files. This is the closest I can get to my Rstudio setup when coding in python.

I'd like to be able to set up different working directories for Interactive windows (workspace) and Jupyter notebooks (file directory). This conforms to the usual expectations for the .py and .ipynb (e.g. when opening other people's notebooks contributed to a remote machine) while facilitating debugging with the normal tools in VS code.  thanks to improvements in issue [#3605](https://github.com/microsoft/vscode-jupyter/issues/3605), you can select one or the other but it'd be best if they were separate.

**Comment by DonJayamanne** [comment]
**Internal note:**
Work done here https://github.com/microsoft/vscode-jupyter/issues/254 will resolve this - for Native Notebooks.
As the CWD is not derived from settings, instead it will be set to where the ipynb file is (as we are using the remote file system).
Agan, only works for native Notebooks.

**Comment by DonJayamanne** [comment]
Its been a year and there haven't been too many upvotes on this issue, hence I'm going to close this for now.
@rebornix @amunger Please feel free to re-open this if you feel this is necessary.
