### ISSUE TITLE
Create Native Notebook test with random executions

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4020]
**Goal:**
* Ensure we do not end up in an undesired/wrong state.

E.g. we have come across a number of instances when running cells, leaves the spinner going on endlessly even after execution has completed.
This was later identified as a result parallel edits of the cells & solved with the use of `chainWithPendingUpdates`.

However recently users have reported this exact same issue again & so has @claudiaregio:
Suggestion from VS Code is to:
* Write test with a simple notebook with multiple tests
* Run cells randomly

**Ensure the results are as expected**

**Comment by DonJayamanne** [comment]
Related to #4022

**Comment by IanMatthewHuff** [comment]
@DonJayamanne Is there a specific validation needed here? The related PRs that I recall were just adding in more logging, not specifically a new test.

**Comment by DonJayamanne** [comment]
Yup, we decided to not add any new tests, but just add more logging.

**Comment by IanMatthewHuff** [comment]
Validated with new logging.
