### ISSUE TITLE
Python.DataScience keyboard shortcuts disappeared

### ISSUE THREAD

**Issue by StefanBloemheuvel** [microsoft/vscode-jupyter#4024]
## Environment data

-   VS Code version: 1.51.1
-   Extension version (available under the Extensions sidebar): 2020.11.371526539
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.372831992
-   OS (Windows | Mac | Linux distro) and version: Mac Pro, mac Catalina 10.15.7
-   Python and/or Anaconda version: 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda virtual environment
-   Jupyter server running: Local

## Expected behaviour

The full set of data science shortcuts should be visible. However, they disappeared a few days ago.

## Actual behaviour

Only the keyboard shortcuts gotoNextCell, gotoPrevCell, notebookedit and restartkernel are available when I searh for python.data in the keyboard shortcuts. Which actually are the only 4 keyboard shortcuts that i manually changed. How can i retrieve the full list of keyboard shortcuts for data science again?

**Comment by DonJayamanne** [comment]
All keyboard shortcuts have been migrated to `jupyter.`
We have moved the data science functionally from the option extension into a separate extension named `Jupyter`.

**Comment by DonJayamanne** [comment]
Closing for now as I believe that addresses your question. 

I'm sorry three new extension didn't automatically migrate your keyboard shortcuts. We plan on fixing that in the next release , hopefully find time today.
