### ISSUE TITLE
VSCode Jupyter is incompatible with Miniforge ARM conda

### ISSUE THREAD

**Issue by leh08** [microsoft/vscode-jupyter#4028]
Hi Team,

- VSCode Version: 1.51.1
- OS Version: MacOS 11.0.1

I would like to report **Jupyter** in VSCode is **incompatible** with `conda` from `miniforce` community supporting native ARM
I get this error when **starting** `Python Interactive Window` Or `Create a New Jupyter Notebook`

Could our team help to solve this bug? Thanks.

https://github.com/conda-forge/miniforge
[osx-arm64 (Apple Silicon)](https://github.com/conda-forge/miniforge)

![uP8Fr1](https://user-images.githubusercontent.com/37028078/100303263-fd231480-3000-11eb-94a0-a6389458cc7e.png)

But I can still start **Jupyter lab** or **notebook** as a **standalone server** outside VSCode.

Kind regards
Giang

**Comment by DavidKutu** [comment]
Thanks for reporting the issue @leh08.

We'll gladly help in any way we can. To start, please set the setting `jupyter.logging.level` to `debug` in vscode, repro de issue, and share everything from the output panel. That'll help a lot in finding the issue.

**Comment by leh08** [comment]
Hi Team,

It works now with python 3.9.1 installed

Kind Regards
Giang

**Comment by oresttokovenko** [comment]
Mine still doesn't work.
