### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Zuhayer-Bin-Javed** [microsoft/vscode-jupyter#4029]
- Issue Type: `Performance`
- Extension Name: `jupyter`
- Extension Version: `2020.11.372831992`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\zuhay\AppData\Local\Temp\ms-toolsai.jupyter-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by greazer** [comment]
@Zuhayer-Bin-Javed, we need the file noted to be able to investigate this problem. 

`c:\Users\zuhay\AppData\Local\Temp\ms-toolsai.jupyter-unresponsive.cpuprofile.txt
`
