### ISSUE TITLE
Markdown in notebooks includes extra line between last two items in a bulleted list

### ISSUE THREAD

**Issue by ijyliu** [microsoft/vscode-jupyter#4030]
## Environment data

-   VS Code version: 1.51.1
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.372831992
-   Python Extension version (available under the Extensions sidebar): v2020.11.371526539
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Home build 19041.630
-   Python and/or Anaconda version: 3.7.9 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Markdown list items should have the same spacing between them when rendered.

## Actual behaviour

There is an extra line (extra spacing) between the second to last and last item in the list.

## Steps to reproduce:

1. Open a jupyter notebook in VSCode

2. Copy-paste the following in a Markdown cell:

```
In this homework we will cover:  
 - loading large data using streaming/chunks, learn about json
 - working with dates in pandas
 - analyzing randomly assigned treatment
 - constructing a comparable control group
 - analyzing at the level of randomization
 
some useful links:
 - [tutorial on dates in pandas](https://pbpython.com/pandas-grouper-agg.html)
 - [pandas documentation on reshaping](https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html)
 - [yelp data documentation](https://www.yelp.com/dataset/documentation/main)

We start with a simple list of imports, as well as defining the path to the file we will be using. Please update the paths to point to the correct location on your computer.
```

Note that there is an extra blank line in the rendered block between "constructing a comparable control group" and "analyzing at the level of randomization." But such a line does not appear between the link "pandas documentation on reshaping" and "yelp data documentation."

Markdown code:
![vscode mdown unrendered](https://user-images.githubusercontent.com/67396209/100371993-a0aaff80-2fd6-11eb-8c62-b5e0586d3927.gif)

Rendered:
![vscode mdown formatting](https://user-images.githubusercontent.com/67396209/100372032-aaccfe00-2fd6-11eb-9adf-5cccf8a402ea.gif)

The same bug also appears to occur for numbered lists. Try copy pasting the following (unfortunately I can't add any more screenshots):

```
 1. create a function that will take a dataframe containing the columns `post` and `treat` and returns the OLS estimate of `post` on `treat` together with the estimate of the variance of that estimate (Remember that in this simple case $\hat{\beta} = cov(y,x)/var(x)$ and that the variance is $\sigma^2_\epsilon/(n \cdot var(x))$. Return the results as a new dataframe with one row and 2 columns.
 2. apply your function to your data from question 4 within each `year` (you can do that using `pd.Grouper(freq='Y',key='date')` within a `groupby` and use the `apply` method.
 3. use your grouped results to plot the mean together with their 95% asymptotic conf interval
 4. comment on the results, in particular on date before the start of the experiment.
```

Thanks for creating this great open-source tool!

**Comment by claudiaregio** [comment]
Hi @ijyliu I am able to repro at this time. Will discuss this during our triage meeting.

**Comment by greazer** [comment]
@ijyliu, Thanks for the feedback, however, we're not going to address this right now. We are transitioning to a different notebook UI, provided by VS Code itself. That effort will handle this situation. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
