### ISSUE TITLE
How to change font and font size of comment and cell execution results under vscode jupyter ?

### ISSUE THREAD

**Issue by kailotus** [microsoft/vscode-jupyter#4031]
Hello, how can I set the font and font size of comment and cell execution results in the Jupyter environment of VS Code? As shown in the screenshot, thank you very much~

![vscode_jupyter](https://user-images.githubusercontent.com/7297066/100401448-73bd2200-3094-11eb-98dc-f255da9c1c11.png)

**Comment by claudiaregio** [comment]
Hi @kailotus, you can zoom in and increase font size by Ctrl/Cmd and +

**Comment by kailotus** [comment]
Hi, **@claudiaregio**, thanks a lot. But I mean for the font and font size of comment and cell execution results can set separately.

**Comment by claudiaregio** [comment]
I see, will discuss this at our next triage meeting!

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.

**Comment by kailotus** [comment]
Hi, **@greazer** , Thank you for your kind help and suggestions.

**Comment by jamilraichouni** [comment]
Hi!

This issue has been closed but I cannot find anything that describes how I can change the font family and/ or size for the code cell execution output!?

Can someone point me to an according setting, please?

Thank you,
Jamil

**Comment by claudiaregio** [comment]
Hi @jamilraichouni, 

This issue is now being tracked here: 
https://github.com/microsoft/vscode/issues/119214

I have copied over your comment but feel free to add any more information you find to be important!
