### ISSUE TITLE
a small bug while executing cell in jupyter notebook

### ISSUE THREAD

**Issue by zy452608532** [microsoft/vscode-jupyter#4032]
when executing a cell in a jupyter notebook, if one undo (Ctrl + Z) after the execution, the cell would keep running forever and can not stop. One can not execute the cell unless the jupyter notebook is shut down and reopened, but other cells can run well. 
BTW, it runs on vs-code-insider.

**Comment by claudiaregio** [comment]
Hi @zy452608532, I am able to reproduce at this time. Will discuss corrected behavior during our triage. 

What would your expected behavior be in this scenario? What were you trying to achieve when you pressed undo after executing a cell?

**Comment by Bewinxed** [comment]
Hello, I’m having the same issue, after executing the cell, sometimes as it runs I’m trying to edit or undo an edit that I have done, if the code stops on an error and I press CTRL+z, the same issue happens and I have to restart vscode.

**Comment by greazer** [comment]
The fix for this bug is being tracked here: https://github.com/microsoft/vscode/issues/106362. Closing in this repo.
