### ISSUE TITLE
Escape unconditionally remove all cursors, selection and focuses cell

### ISSUE THREAD

**Issue by larsch** [microsoft/vscode-jupyter#4033]
## Environment data

-   VS Code version: 1.51.1
-   Jupyter Extension version: v2020.11.372831992
-   Python Extension version: v2020.11.371526539
-   OS: Windows 10 2004
-   Python and/or Anaconda version: 3.8

## Expected behaviour

When pressing Escape while multiple cursors or selection are active, I expect it to return to a single cursor. This is the normal behavior in VSCode.

Rebinding notebook.cell.quitEdit or changing it's 'when' criteria should be possible

## Actual behaviour

When pressing ESC while multiple cursors or selection are active, all cursors are lost and the cell is focused. Up/down/home/end moves between cells instead of moving the cursor).

Removing Escape keybinding (notebook.cell.quitEdit) from shortcuts has no effect.

## Steps to reproduce:

Create Jupyter notebook. Create 1 or more cells. Edit code in cell, Activate multiple cursors either by Ctrl+D og Ctrl+Alt+Ctrl+Arrow keys. Press Escape to return to single-cursor mode or remove selection.

Removing the Escape keyboard shortcut has no effect. Escape still stop editing and selects the cell.

```
    {
        "key": "escape",
        "command": "-notebook.cell.quitEdit",
        "when": "inputFocus && notebookEditorFocused && !editorHasSelection && !editorHoverVisible"
    }
```

**Comment by claudiaregio** [comment]
Hi @larsch, I am unable to repro this issue at this time. Could you provide a gif showing us what you are seeing? If you need a tool ScreenToGif works pretty well (https://www.screentogif.com/)

Could you also provide us with the VS Code version you are using?

**Comment by larsch** [comment]
@claudiaregio Updated issue with Code version. Here's demo:

![JupyterEscapeDemo](https://user-images.githubusercontent.com/15712/100580777-dc034200-32e6-11eb-9201-2771a2118ee1.gif)

**Comment by claudiaregio** [comment]
Thanks for the additional info. (This is only reproduced in stable, not insiders)

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
