### ISSUE TITLE
Never stops asking for feedback

### ISSUE THREAD

**Issue by larsch** [microsoft/vscode-jupyter#4034]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version: v2020.11.372831992
-   Python Extension version: v2020.11.371526539
-   OS: Windows 10 2004
-   Python and/or Anaconda version: 3.8

## Expected behaviour

Doesn't ask me to tell how the Python Data Science feature are working me. Preferably not at all, but at least at most once.

## Actual behaviour

Asks me to tell how the Python Data Science features are working for me every time I open a notebook and sometimes when I evaluate a cell.

## Steps to reproduce:

Open Jupyter Notebook.

I have clicked both 'Take survey' and 'No thanks' so many times, but it keeps popping up.

**Comment by dpelaez10** [comment]
Having the same issue ... already took the survey thinking that'd suppress the notification but it pops up every time I evaluate a cell.

**Comment by Jawsingale** [comment]
So frustrating....

**Comment by abixel** [comment]
Same problem. The pop-up occurs every time I run a Jupyter notebook cell. Taking the survey, saying 'no thanks', and even re-installing the extension have not solved the problem.

**Comment by claudiaregio** [comment]
@larsch @dpelaez10 @Jawsingale @abixel There was a bug in our survey deployment, fix coming soon!

**Comment by mchitre** [comment]
Its almost unusable for me -- almost every cell eval causes the popup!

OS: macOS Catalina

**Comment by joyceerhl** [comment]
This should be fixed in the latest version of the Jupyter extension (version 2020.11.392013122). Please give that a try and let us know if it works for you, and we're very sorry for the trouble caused.

**Comment by DonJayamanne** [comment]
Closing as the issue has been resolve
