### ISSUE TITLE
Cut (Shift+Del or Ctrl+X) occasionally deletes twice

### ISSUE THREAD

**Issue by larsch** [microsoft/vscode-jupyter#4035]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version: v2020.11.372831992
-   Python Extension version: v2020.11.371526539
-   OS: Windows 10 2004
-   Python and/or Anaconda version: 3.8

## Expected behaviour

Cut (Shift+Delete, or Ctrl+X) should delete only selection and/or currently selected line.

## Actual behaviour

Cut (Shift+Delete, Ctrl+X) occasionally deletes twice.

## Steps to reproduce:

A: In notebook cell, make a selection, press Shift+Del. 50% of the time selection is deleted correctly. 50% of the time, the entire line is deleted too.

B; In notebook cell, with no selection, press Shift+Del. 50% of the time the current line is correctly deleted. 50% of the time, two lines are deleted.

**Comment by claudiaregio** [comment]
@larsch I am able to reproduce this at this time (in stable and insiders). Will discuss this at triage meeting.

**Comment by greazer** [comment]
Looks like a dupe of VS Code bug: https://github.com/microsoft/vscode/issues/101946. We should investigate and open a new bug if necessary.

**Comment by rchiodo** [comment]
Going to work on making a repro case

**Comment by rchiodo** [comment]
Potential fix for this is here:
https://github.com/microsoft/vscode-jupyter/compare/rchiodo/double_delete

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
