### ISSUE TITLE
Unable to select interpreter to start Jupyter server

### ISSUE THREAD

**Issue by leonarduschen** [microsoft/vscode-jupyter#4036]
## Environment data

-   VS Code version: 1.51.1
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.372831992
-   Python Extension version (available under the Extensions sidebar): v2020.11.371526539
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.8.5 32-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

Works just fine

## Actual behaviour

Select interpreter does nothing and Jupyter keeps prompting ipykernel to be install to my other interpreter 3.8.3 64-bit (conda) - which is my conda base environment. I have also tried creating new venv and conda environments and got the same results.

Also, it keeps asking for feedback for some reason, perhaps it is related to https://github.com/microsoft/vscode-jupyter/issues/4034

## Steps to reproduce:

- Open VSCode
- Run `python -m venv venv`
- Click yes when prompted to select the new virtual environment for the current working directory
- Create new `.ipynb` file and open it

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by claudiaregio** [comment]
Hi @leonarduschen, does this happen constantly? Have you tried restarting VS Code? Also, could you provide a gif showing us what you are seeing? If you need a tool ScreenToGif works pretty well (https://www.screentogif.com/)

**Comment by leonarduschen** [comment]
> Have you tried restarting VS Code?

Yes and tried using multiple Python versions in `conda` environment too - but Jupyter keeps using my base `conda` interpreter 3.8.3 64-bit (conda) for some reason. Perhaps this is related to https://github.com/microsoft/vscode-jupyter/issues/4037.

That said, I ended up deleting Python (e.g. interpreter, conda, etc), installed Python 3.9.0 64-bit and it works fine now. Feel free to close the issue.

**Comment by claudiaregio** [comment]
Ok great, thanks for the update!
