### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Alexfm101** [microsoft/vscode-jupyter#4040]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2020.11.372831992`
- OS Version: `Linux x64 5.4.0-53-generic`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by claudiaregio** [comment]
@Alexfm101 Can you please provide some more information on the bug you are experiencing?
