### ISSUE TITLE
Python Interactive Window: Keyboard Shortcut to Scroll

### ISSUE THREAD

**Issue by raunakk** [microsoft/vscode-jupyter#4043]
I use editor (.py) files and Interactive Window side-by-side. (screenshot attached). 

There are times when I would like to look at previous cell execution output. For this, I press Cmd+2 to shift focus to the interactive window. The focus shifts to the input code box. There is not keyboard shortcut (that I can find) which allows me to shift focus to the scroll bar and use Up/Down arrows scroll up and down in the interactive window to view previous cells. I end up switching to mouse for this which is time consuming. Would be great if keyboard shortcuts for this can be supported. 
<img width="609" alt="Screenshot 2020-11-30 at 1 01 56 PM" src="https://user-images.githubusercontent.com/44130937/100580803-9d807e00-330c-11eb-9d63-b6fe92b6cdc2.png">
<img width="555" alt="Screenshot 2020-11-30 at 1 02 18 PM" src="https://user-images.githubusercontent.com/44130937/100580806-9fe2d800-330c-11eb-9e92-bd5ff3c270b8.png">

**Comment by claudiaregio** [comment]
Thanks @raunakk, will discuss at our next triage meeting!

**Comment by joyceerhl** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/130724
