### ISSUE TITLE
Control panel disappeared in insider version

### ISSUE THREAD

**Issue by xsoheilalizadeh** [microsoft/vscode-jupyter#4045]
I used to have a stable version of jypyter and I had a control panel to see variables and other execution features but it looks like all of them disappeared in the insider version.

![image](https://user-images.githubusercontent.com/22220356/100602070-a9723d00-3318-11eb-9ff3-f48051a5cd3a.png)

**Comment by claudiaregio** [comment]
Hi @xsoheilalizadeh, the toolbar in insiders is actually located in the top right. 

![image](https://user-images.githubusercontent.com/19276747/100636207-5089b100-32e6-11eb-9e99-7328a176081d.png)

**Comment by xsoheilalizadeh** [comment]
Thanks @claudiaregio, but it hasn't all the features like the variables table.

**Comment by claudiaregio** [comment]
We are still working on feature parity with the new Native Notebook experience, variable explorer coming back soon :)

**Comment by jtisbell4** [comment]
Any update on when the variable explorer will be coming back to Insiders? I still do not see it.

**Comment by claudiaregio** [comment]
It is being worked on right now, hoping to ship in the next two releases!
