### ISSUE TITLE
Lock closed issues

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4046]
Lock after 7 days of closing an issue.
This way users create new issues & do not comment on old closed issues.
Python extension does this.

Else we need to monitor closed issues for user comments as well.

**Comment by greazer** [comment]
I was going to make this happen, but I'm not seeing how the python extension does this. I can't even find any locked conversations at all. What am I missing?

**Comment by DonJayamanne** [comment]
This is the bot used https://github.com/apps/lock
Core extension has `.github/lock.yml` file in repo (we too should have this file).
I think so we'd need to do is setup the bot for the repo

**Comment by joyceerhl** [comment]
We already have the `.github/lock.yml`, so I gave the bot access to this repo. 
![image](https://user-images.githubusercontent.com/30305945/102256755-9f2b7380-3ec0-11eb-9307-96ab38709dd7.png)

**Comment by IanMatthewHuff** [comment]
@joyceerhl anything else we need to do here? Looking to validate, but I'm not seeing issues getting locked. 
https://github.com/microsoft/vscode-jupyter/issues/4205
https://github.com/microsoft/vscode-jupyter/issues/4203

**Comment by joyceerhl** [comment]
Yeah this isn't done. The approach I took (adding the bot to our repo and configuring lock.yml) apparently doesn't work, I think @greazer said he had another tack in mind and wanted to work on this.

**Comment by greazer** [comment]
Unassigned myself. Who am I kidding? I don't really have the time to solve this myself. I believe I had found a Github action that can be used to do this, rather than a Github bot.

**Comment by DavidKutu** [comment]
Right now the action is running every hour. You can see the locked issues [here](https://github.com/microsoft/vscode-jupyter/runs/2514151678?check_suite_focus=true).
When its caught up, I'll change it to run once a day.

**Comment by joyceerhl** [comment]
Validated, issues are getting locked.
