### ISSUE TITLE
Interactive pane input is broken

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#4048]
Issue Type: <b>Bug</b>

Interactive pane input is broken.  Most of the time I cannot input anything into the console input at the bottom of the Interactive Pane.  If I "Remove all cells", sometimes it will fix itself and sometimes it won't.  Running code in the Interactive Pane by selecting the code and pressing <kbd>shift</kbd>+<kbd>enter</kbd> still works, and if I do that, sometimes the console input will start working again and sometimes it won't.  

Most of the time it does not work.

Extension version: 2020.11.372831992
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.99GB free)|
|Process Argv|--crash-reporter-id f652528b-5678-4b12-9ca0-3de6b1e1135f|
|Screen Reader|yes|
|VM|0%|
</details>

**Comment by IanMatthewHuff** [comment]
@clayms Thanks for filing this issue. We've had some issues recently with the input box that we are working to resolve. We did just have a point release on the 30th that looks like you (by your version number) don't have yet. Can you try out the most recent version of the extension? We did have one input box fix in that release. @rchiodo  is looking into another now as well.

**Comment by greazer** [comment]
Hey @clayms, I'm going to close this out. If it still repro's after installing the latest extension, please reopen.
