### ISSUE TITLE
Force reload after extension is installed

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#405]

**Comment by IanMatthewHuff** [comment]
Now reload is not required (you just see an info message that changes might now show without a new notebook / interactive window session) and we see the change and message even if you install python not via our prompt.

**Comment by joyceerhl** [comment]
Validated: 
![image](https://user-images.githubusercontent.com/30305945/99998252-3b0b0900-2d73-11eb-9e90-db952fd122ee.png)
