### ISSUE TITLE
Jupyter and .NET interactive extension side by side

### ISSUE THREAD

**Issue by LadyNaggaga** [microsoft/vscode-jupyter#4050]
Documenting the current Jupyter and .NET interactive extension side by side experience for our teams. I have also opened a duplicate issue on [dotnet/interactive](https://github.com/dotnet/interactive/issues/917) as we partner on an experience. 
## Environment data
Installed 
- .NET Core 3.1 and 5.0 
- .NET Interactive extension
- VS Code Insiders  

Not installed 
- Python 
- Jupyter 

### **Scenario**: User has .NET Interactive extension and has installed the Jupyter Extension
Profile:  A .NET user who is using .NET interactive for their notebooks.  They typically would use .NET Interactive as their entry into Data Science, or has prototype tool, Dev Ops, IoT for full details please check out the .NET Interactive plan [here](https://github.com/dotnet/interactive/issues/392). 
### Out of box experience (OOB)
- Installed the Jupyter extension 
- Created a Jupyter:Create New Blank Jupyter Notebook (ctrl + shift + P)
- This happens 
![image](https://user-images.githubusercontent.com/2546640/99831743-8e8c1580-2b2d-11eb-90af-f46ac249410d.png)
- Default language is python - suggestion/ question: If Python is not installed default to the kernel on available or ask user to select language?
![image](https://user-images.githubusercontent.com/2546640/99832968-5dace000-2b2f-11eb-842e-c8a62501afa7.png)
- I selected C# Interactive using the language picker and hit run. 
- Prompted to select notebook - kernel to run this notebook. 
**Note**:  From a user perspective they could be left unsure what to do at this point. 

![image](https://user-images.githubusercontent.com/2546640/99833430-f80d2380-2b2f-11eb-9059-91879508c4c3.png)

**Note**: There is C# kernel and .NET Interactive C# kernel in the kernel provider list. This could confuse our customers. 

### Tried workaround 

- Install the dotnet interactive global tool

` dotnet tool install -g --add-source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" Microsoft.dotnet-interactive`

- This works temporarily 

### Issues 
-  .NET IntelliSense is gone in this experience. 
-  Polyglot notebooks doesn't seem to work either
- If you close then open VS Code Insiders then try creating or open a C# .ipynb file the OOB experience happens again. 

**Additional Notes**
- If you open and run a notebook in .NET Interactive then open a new notebook in the Jupyter extension the cell will run. 

Thank you

**Comment by DonJayamanne** [comment]
@LadyNaggaga 
* Please could you check your `console` window & provide the output from there (`Help->Toggle Develoepr Tools-> console window`). There might be some errors there.

> Note: There is C# kernel and .NET Interactive C# kernel in the kernel provider list. This could confuse our customers.

Please could you provide a screenshot of this.
Is `C# Kernel` a Jupyter Kernel. If this is, this will be displayed as its a Jupyter kernel & we do not hide any kernels today. 
@rchiodo @IanMatthewHuff /cc

**Comment by DonJayamanne** [comment]
> If you close then open VS Code Insiders then try creating or open a C# .ipynb file the OOB experience happens again.

@rchiodo @IanMatthewHuff @DavidKutu @joyceerhl are you able to repro this.
Please try with a empty folder. 
I can't repro at my end.

**Comment by LadyNaggaga** [comment]
> @LadyNaggaga
> 
> * Please could you check your `console` window & provide the output from there (`Help->Toggle Develoepr Tools-> console window`). There might be some errors there.
![image](https://user-images.githubusercontent.com/2546640/100678079-5e692180-333a-11eb-9e8d-0fa7af963c69.png)

> 
> > Note: There is C# kernel and .NET Interactive C# kernel in the kernel provider list. This could confuse our customers.
> 
> Please could you provide a screenshot of this.
![image](https://user-images.githubusercontent.com/2546640/100678391-041c9080-333b-11eb-9fec-ddc4f7b89976.png)
Other than .NET Interactive languages none of the other language options exist on my machine. Is there a way for us to hide them?
> Is `C# Kernel` a Jupyter Kernel. If this is, this will be displayed as its a Jupyter kernel & we do not hide any kernels today.
On the machine I did this one there is no C# Kernel through installed.  
The above documents the user experience when our customers have already installed and used .NET Interactive extension(which [Standard I/O](https://github.com/dotnet/interactive/blob/main/docs/kernels-overview.md) then installs Jupyter extension. 
> @rchiodo @IanMatthewHuff /cc

**Comment by DonJayamanne** [comment]
@LadyNaggaga 

> Other than .NET Interactive languages none of the other language options exist on my machine. Is there a way for us to hide them?

1. I'm assuming this is because you provide a richer experience for C# with the .net interactive extension? Correct?
2. I guess we could always hide some kernels, if the .net interactive extension is installed.
However this means anyone installing other .NET kernels developed by others would also get hidden. & I don't think this is the right approach.

Is there a way to identify kernels that are registered by the .nEt interactive extension?
Could you add some metadata into the kernel json file so we can determine based on that.
This way we could hide just those kernels (kernel that were created explicitly by the .net interactive extension

**Comment by colombod** [comment]
@DonJayamanne 

> Is there a way to identify kernels that are registered by the .nEt interactive extension?
Could you add some metadata into the kernel json file so we can determine based on that.
This way we could hide just those kernels (kernel that were created explicitly by the .net interactive extension

That discovery should be performed via some api that probably have to sit with the viscose extensibility api. I am under the impression that notebook content providers should have a mean to discover kernels via the kernelProviders and talk to them (probably including language services requests) via the kernelProvider api surface. Then each VScode extension that registers kernelProviders will be accountable for establishing connections to the actually kernel runtime (iPythong / .NET Interactive, and anything else).

**Comment by jonsequitur** [comment]
The languages in Maria's screenshot are the languages VS Code has language providers registered for, and most don't have corresponding kernels. `C#` and `C# (.NET Interactive)` are different languages in a number of important ways, and the `C#` variant isn't supported by .NET Interactive, so it shouldn't be present in the list.

> Is there a way to identify kernels that are registered by the .nEt interactive extension?

There's ideally only a single .NET Interactive kernel process which speaks multiple languages. When it's spun up, it has a default language but the others are always available within the same process. 

For the purposes of Jupyter, we register based on the default language, but again they're all polyglot-enabled:

![image](https://user-images.githubusercontent.com/547415/100688563-82773380-3337-11eb-91ed-51cec38cb622.png)

It's worth noting that starting a separate kernel process per language within the same notebook interferes with a number of scenarios related to variable sharing and extension loading.

> Could you add some metadata into the kernel json file so we can determine based on that.

Ideally the kernel discovery mechanism shouldn't depend on kernelspec.json, but should come directly from .NET Interactive Notebooks extension. We've had some discussion about how to support this in the VS Code notebook APIs.

/cc @brettfo

**Comment by claudiaregio** [comment]
Another detail worth adding: 
For the sharing scenario, if you try to open up a .NET interactive notebook downloaded or sent to you, the kernel and the language are not correctly set.

**Comment by DonJayamanne** [comment]
Closing this issue as we no longer own the notebook, its contributed by VS COde (as a built in extension)
