### ISSUE TITLE
cannot change kernel successfully with ms-python 2020.11.371526539

### ISSUE THREAD

**Issue by zesluo** [microsoft/vscode-jupyter#4055]
Hello @DonJayamanne , @rchiodo Thanks for your support on interactive window! We found a bug as below. 
## Environment data

Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

## Expected behaviour

can change kernel successfully
## Actual behaviour

By using the command :
![image](https://user-images.githubusercontent.com/46309533/100695772-ee57ab80-33cc-11eb-82ba-d49cc176c387.png)

when we try to change the kernel, it cannot succeed. The logs are attached. Please feel free to let me know if more information is needed. This breaks our function to run 'Pyspark interactive'  Thanks a lot!
![image](https://user-images.githubusercontent.com/46309533/100695808-029ba880-33cd-11eb-8549-6afe808a70fd.png)
![image](https://user-images.githubusercontent.com/46309533/100695824-07f8f300-33cd-11eb-921f-6d90ff4f5384.png)
[1126errorlogs.log](https://github.com/microsoft/vscode-jupyter/files/5620212/1126errorlogs.log)

\

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by IanMatthewHuff** [comment]
Hey @zesluo it doesn't look like you have the full logs here. To get the full logs you should set Jupyter->Logging->Level to "debug" and then pull what is in the "Jupyter" tab of the output window. 

Also I'm a bit unsure about your scenario here. Is the issue with kernel changing or with the "Run selection / line in interactive window?"

**Comment by zesluo** [comment]
Hello @IanMatthewHuff , thanks for your reply! here it is. ^_^

![image](https://user-images.githubusercontent.com/46309533/100827570-ff212380-3497-11eb-9e91-31b9108327ce.png)
![image](https://user-images.githubusercontent.com/46309533/100827631-27a91d80-3498-11eb-9a3f-f69390d61bc0.png)
[output logs in jupyter.docx](https://github.com/microsoft/vscode-jupyter/files/5626929/output.logs.in.jupyter.docx)
the issue  is with kernel changing

**Comment by IanMatthewHuff** [comment]
@zesluo this error is the error that we show when a kernel fails to launch. Looking at the log it looks like Runtime errors are coming from the sparkmagic package, which is failing to import numpy.

This is the relevant chunk of the logging:
![image](https://user-images.githubusercontent.com/812783/100948774-7c12c400-34bd-11eb-9fa7-6e1c99439152.png)

Looks like sparkmagic is attempting to import numpy and there is a RuntimeError with the version of numpy that you are trying to use. Not sure what exact version you have, but I see a number of recent issues regarding this error on Windows like so:

https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an
https://stackoverflow.com/questions/64778222/how-to-fix-runtimeerror-the-current-numpy-installation-fails-to-pass-a-sanity

Looks to me like an error with sparkmagic and the environment (specifically numpy) that you are trying to run it in.

**Comment by greazer** [comment]
We believe that this is a result of a bad environment. The version of numpy needs to be downgraded as it's not compatible with Python 3.9.

**Comment by zesluo** [comment]
Thanks for the suggestion! @IanMatthewHuff , @greazer , I 've already fixed the problem.

**Comment by DonJayamanne** [comment]
Thanks for getting back with a confirmation.
