### ISSUE TITLE
Cells recovered with the "z" shortcut are not saved

### ISSUE THREAD

**Issue by alanhett** [microsoft/vscode-jupyter#4058]
## Environment data

-   VS Code version: 1.51.1
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.392013122
-   Python Extension version (available under the Extensions sidebar): v2020.11.371526539
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

When I delete a cell, then bring it back using the "z" shortcut key, it should save this change and keep the recovered cell.

## Actual behaviour

When I delete a cell, then bring it back using the "z" shortcut key, then if I save the file and close and reopen it, the cell is permanently lost. It doesn't save the recovered cell.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create a new jupyter notebook and create a couple of cells, enter some arbitrary code
2. Delete a cell using the trash can icon at the right side of the cell
3. Recover the cell by pressing the "z" key (while no cells are selected)
4. Save the notebook and close it
5. Reopen the notebook, the cell is missing

**Comment by IanMatthewHuff** [comment]
@alanhett Thanks for the report on this. I just gave it a try and I repro the same issue. When the cell comes back with 'z' the cell reappears, but the file doesn't correctly get marked as dirty and the change is not saved if you close. We'll triage this issue.

**Comment by alanhett** [comment]
Thanks @IanMatthewHuff , by the way I also attempted to make the file "dirty"  by making some arbitrary changes w/in the cell and w/in other cells (like between steps 3 and 4 above), and it still would lose the cell.

**Comment by IanMatthewHuff** [comment]
@alanhett Yeah it's reflecting that chance visually, but not in the backing data. We'll have to clean this up.

**Comment by IanMatthewHuff** [comment]
Validated. Removed the cell and did an undo command. After that, the cell was back, file was not dirty and the cell was still there after opening and closing.
