### ISSUE TITLE
never ending loading

### ISSUE THREAD

**Issue by aragong** [microsoft/vscode-jupyter#4059]
Issue Type: <b>Bug</b>

Jupiter extension never ends loading process. If I update to the newest version the problem persists and also 
imports of my local modules fail.

Thank you in advance

Extension version: 2020.11.372831992
VS Code version: Code - Insiders 1.50.0-insider (0c50e1db17168a738235bd7e5c02b9f05ea5df59, 2020-09-30T06:53:41.824Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3411)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.98GB (9.80GB free)|
|Process Argv|--crash-reporter-id dcc88fd9-fed3-4050-a9e9-4928cc13bd3d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IanMatthewHuff** [comment]
@aragong you have an older version of VS Code insiders listed. I believe that might have issues with some of the newer features that we are introducing. Do you still repro the issues with the most recent version of Code - Insiders?

**Comment by aragong** [comment]
thank you @IanMatthewHuff , I am trying to update VSCode but the server kicks out this error: 
![image](https://user-images.githubusercontent.com/48764870/100840309-fae40e80-3475-11eb-91c7-5b82ec4e81b0.png)


If I update python extension and Jupyter extension to the newest version, the conda selector disapeared (I already launch an issue on this).

Any way to avoid that server error?

**Comment by aragong** [comment]
Solve! everything is running properly! The update of VSCode was the problem! 

Thank you!

**Comment by IanMatthewHuff** [comment]
@aragong Glad to hear it!
