### ISSUE TITLE
Custom widget in Jupyter Notebook is not working on vscode insider.

### ISSUE THREAD

**Issue by Kingwl** [microsoft/vscode-jupyter#4062]
### **Transfer from https://github.com/microsoft/vscode/issues/111404**

Even though I think it might be a problem with vscode.
Please feel free to PM me on teams if anything I can help.

## Environment data

-   VS Code version: 1.52.0-insider (user setup)
-   Extension version (available under the Extensions sidebar): v2020.11.371526539 
-   OS and version: Windows_NT x64 10.0.19042
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: doesn't matter
-   Relevant/affected Python-related VS Code extensions and their versions: 1.52.0-insider
-   Value of the `python.languageServer` setting: doesn't matter

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

Custom widget should work on vscode insider

## Actual behaviour

It's not work

## Steps to reproduce:

notebook: 
```json
{"cells":[{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["%%javascript\r\n","\r\n","define('email_widget', [\"@jupyter-widgets/base\"], function(widgets) {\r\n","\r\n","    var EmailView = widgets.DOMWidgetView.extend({\r\n","\r\n","        // Render the view.\r\n","        render: function() {\r\n","            this.email_input = document.createElement('input');\r\n","            this.email_input.type = 'email';\r\n","            this.email_input.value = 'example@example.com';\r\n","            this.email_input.disabled = true;\r\n","\r\n","            this.el.appendChild(this.email_input);\r\n","        },\r\n","    });\r\n","\r\n","    return {\r\n","        EmailView: EmailView\r\n","    };\r\n","});"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["from traitlets import Unicode, Bool, validate, TraitError\r\n","from ipywidgets import DOMWidget, register\r\n","\r\n","\r\n","@register\r\n","class Email(DOMWidget):\r\n","    _view_name = Unicode('EmailView').tag(sync=True)\r\n","    _view_module = Unicode('email_widget').tag(sync=True)\r\n","    _view_module_version = Unicode('0.0.1').tag(sync=True)"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["from IPython.display import display\r\n","\r\n","email = Email()\r\n","display(email)"]}],"metadata":{"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.6"},"orig_nbformat":2},"nbformat":4,"nbformat_minor":2}
```

1.  Save above json into an .ipynb
2.  Open saved file
3.  Run all cells (install ipywidgets if you need)

Above samples copies from https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Custom.html.
And work on below version of vscode：

```
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

And all plugins has the same version:
```
jupyter: v2020.11.372831992 
python: v2020.11.371526539 
```

Expected output is what shows in the vscode:
![image](https://user-images.githubusercontent.com/6831019/100428742-4d68a800-30cf-11eb-927d-8abf5a07ee39.png)

And actually output is:
![image](https://user-images.githubusercontent.com/6831019/100428702-4346a980-30cf-11eb-8112-2ba7e86da97c.png)

Thanks.

## Logs

None

**Comment by IanMatthewHuff** [comment]
@Kingwl This is indeed an issue. But it's a known one. In VS Code - Insiders we are rolling out our new notebook interface, based on VS Code's native notebook support. Currently custom widgets are not supported in it yet.

I'm going to close this issue as we already have this tracking that addition:
https://github.com/microsoft/vscode-jupyter/issues/251

Currently this is on track for the next release.

**Comment by Kingwl** [comment]
Well. To be clear. Does only insider has the native notebook? 
We have an product who using custom widget based on webview notebook. And I want to make sure it always works well.

**Comment by IanMatthewHuff** [comment]
Notebooks are in both stable and insiders, but right now insiders is using the new notebook interface detailed here:
https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/

If you want a working custom widget you should just use vscode stable at this point. But widget support is coming very soon to the insiders version of notebooks.

**Comment by Kingwl** [comment]
Thanks for the response.
