### ISSUE TITLE
Latest version of extension does not allow you to Run Selection in Interactive Window

### ISSUE THREAD

**Issue by sc0h0** [microsoft/vscode-jupyter#4063]
As the title says, the feature of running selected code in Interactive Window no longer exists. 

The latest version has Shift+Enter run the selected code in Python terminal which is completely different.

Can you please put this feature back in?

Below shows an older version which has the feature.

![image](https://user-images.githubusercontent.com/10361350/100704064-ed3c7380-33f8-11eb-9160-7998e9ca1473.png)

**Comment by joyceerhl** [comment]
Hey @sc0h0, if you set `"jupyter.sendSelectionToInteractiveWindow": true` in your settings.json, does the problem persist?

**Comment by sc0h0** [comment]
Hi @joyceerhl  yes that worked thanks! Might be best set to default for next version?

**Comment by joyceerhl** [comment]
That would break users who want shift+enter to run code in the Python terminal. However this suggests that our mechanism for resolving shift+enter is broken. Usually when a user runs shift+enter, the Python extension prompts the user to decide whether they want shift+enter to go to the terminal or integrated window. Did you get a prompt of that sort and select a preference by any chance @sc0h0?

**Comment by sc0h0** [comment]
I didn't get a prompt. I would seem that when I installed the latest version (2020.11.371526539) that it set shift+enter to only correspond to "run in terminal".
