### ISSUE TITLE
Export as Python Script is available for Non-python languages

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#407]
If you run the command it will create a .py file with the code from the other language (Julia C#) inside python comment blocks.

**Comment by DonJayamanne** [comment]
Hmm, not sure removing the command was the right thing.
I think it would have been better to export to `Script`, nbconvert supports this out of he box & we can just convert any notebook to any script.

**Comment by DavidKutu** [comment]
here's a separate issue to support other languages
https://github.com/microsoft/vscode-jupyter/issues/4054

**Comment by IanMatthewHuff** [comment]
@DavidKutu doesn't look like this is fully fixed. It removes it from the quick pick, but the command palette command Jupyter: Export to Python Script is still available and still will export Julia / Java to a python file with python comment block sections. Moving back to backlog.

**Comment by DonJayamanne** [comment]
Validated
