### ISSUE TITLE
Ability to change default "shift-enter" to "enter" when running code in Interactive Window

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/vscode-jupyter#4073]
Most REPL terminals (CPython, IPython, Bash, cmd . . . ) uses the ***ENTER*** key to run commands.

It would be good to have the ability to change the default behavior of ***shift-enter*** and ***enter*** key to match this common behavior in the Python Interactive window.

I know this window is not a common terminal, but the similarity can improve usability to some users used to normal terminals.

The Default is: ***enter*** initiates a new line in the cell and ***shift-enter*** run code.

The feature request is:
To have the ability (in ***Preference settings***) to choose changing the behavior to: ***enter*** run code and ***shift-enter*** initiates a new line in the cell.

**Comment by rchiodo** [comment]
Thanks for the suggestion. We'll consider it at our next weekly triage.

**Comment by andycraig** [comment]
I would really like this feature too. I'm always hitting <kbd>Enter</kbd> accidentally because that's what I use in other REPLs. I asked for a similar feature here (first I asked for full customisation of the shortcut, then in a comment said that just <kbd>Enter</kbd> would be fine): https://github.com/microsoft/vscode-jupyter/issues/1239

**Comment by andycraig** [comment]
It was also requested here https://github.com/microsoft/vscode-jupyter/issues/3328. There was a request there to make the shortcut to run code from the editor configurable as well, and since that's already the case the issue was closed.

**Comment by andycraig** [comment]
Would you be interested in an external PR for this?

**Comment by rchiodo** [comment]
Sure but not sure how to surface it to the user. The easiest to implement would likely be a setting. 

But VS code has keybindings for commands instead. 

So I think the better way would be to change the interactive window to send a command when the user hits a key combination. 

The problem there is handling the keyboard before the actual textArea gets the keystroke. 

Making the ideal solution more difficult. I'm not sure we'd accept a PR for the quick and dirty solution :(

**Comment by andycraig** [comment]
Hi @rchiodo, thank you for your reply. Here's my understanding of the requirements:

1. Add capability for calling commands via keybindings when in Interactive Window text area
2. Add 'In Interactive Window text area' option for use in `when` clause for keybindings
3. Create command for 'execute code in Interactive Window text area', bound to <kbd>Shift-Enter</kbd> by default
4. Create command for 'new line in Interactive Window text area', bound to <kbd>Enter</kbd> by default
5. Modify Interactive Window text area hint text to show current keybinding for executing code
6. Tests as appropriate (1-4?) 

I will have a look at the codebase to get a feel for what modifications would be required. If I don't post back it's safe to assume that I decided not to proceed. (I was very much thinking about the quick-and-dirty solution with a setting 😄)

Thank you again, and thanks as always for your work on the Jupyter/Python extensions.

**Comment by rchiodo** [comment]
@andycraig that sounds like a good plan. That seems like a good way to solve this.

**Comment by andycraig** [comment]
Linking another issue about keyboard shortcut support in Interactive Window: https://github.com/microsoft/vscode-jupyter/issues/1225

**Comment by joyceerhl** [comment]
You can now configure the shortcut to execute code in the [preview interactive window](https://code.visualstudio.com/updates/v1_58#_jupyter-interactive-window), which features improved VS Code workbench integration and is currently the default in VS Code Insiders. Please let us know if it works for you and give us any feedback you have about the new experience 😊 If you find any bugs or have concerns, please file a new issue at https://github.com/microsoft/vscode-jupyter/issues so we can fix it. Thank you! 

![image](https://user-images.githubusercontent.com/30305945/126432144-ea8d98d8-a39f-45d5-8ed0-e95f66e1f8b3.png)

**Comment by Diogo-Rossi** [comment]
@joyceerhl Thankyou! it is working.
I'm also looking forward to the default VS Code release. Great job!
