### ISSUE TITLE
import local module problem

### ISSUE THREAD

**Issue by aragong** [microsoft/vscode-jupyter#4076]
Issue Type: <b>Bug</b>

Hi there,

I am having this problem after the update of the extension. I am loading a module "workspace.py" in the folder "code", this import works fine in the terminal but fails in the interactive window... I do not know why.
I add a image of the code and the folder structure:
![image](https://user-images.githubusercontent.com/48764870/100842325-f79e5200-3478-11eb-9c6a-4501199f67cd.png)

Extension version: 2020.11.392013122
VS Code version: Code - Insiders 1.52.0-insider (bf21395291146c014220eb70b54fdfc0a15956b5, 2020-12-01T09:19:32.000Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3411)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.98GB (6.98GB free)|
|Process Argv|--crash-reporter-id dcc88fd9-fed3-4050-a9e9-4928cc13bd3d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2prompt:30219162
vstry244:30226747
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by rchiodo** [comment]
Thanks for the bug. I believe this is because the default directory for the interactive window is the same as the file. It's set with this option here:

![image](https://user-images.githubusercontent.com/19672699/100914805-63d48200-3488-11eb-85e7-ccd5b894568f.png)

You should be able to change this to `${workspaceRoot}` and it will change the current directory for the kernel to the root of your workspace.

**Comment by aragong** [comment]
> Thanks for the bug. I believe this is because the default directory for the interactive window is the same as the file. It's set with this option here:
> 
> ![image](https://user-images.githubusercontent.com/19672699/100914805-63d48200-3488-11eb-85e7-ccd5b894568f.png)
> 
> You should be able to change this to `${workspaceRoot}` and it will change the current directory for the kernel to the root of your workspace.

Thank you @rchiodo, I prefered to refactor filename and classname. As you suggest the confict has been resolved! Again thank you! It is good to know that is better to avoid this word!
