### ISSUE TITLE
Test Reports Save their results and only publish on failure

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#4080]
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/fecca43d-1f52-4dce-b685-17bb1148f135)

Scenario (example shown in picture above):

PR runs and there is a failure in Notebook Test Report.
Re-run the PR checks
All notebook tests pass
Notebook Test Report still shows up as a failure, I believe as it still has the result from previous and only publishes on failure.

**Comment by rchiodo** [comment]
These don't work anymore (well because of permissions).
