### ISSUE TITLE
Test Failure: DataScience - VSCode Notebook - (Trust): Test notebook with output

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-jupyter#4081]
Prompted to trust an untrusted notebook and trusted:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-jupyter/vscode-jupyter/out/test/datascience/notebook/notebookTrust.vscode.test.js)

**Comment by DonJayamanne** [comment]
Dup of https://github.com/microsoft/vscode-jupyter/issues/393
