### ISSUE TITLE
Pressing the "Open Changes" button raises error

### ISSUE THREAD

**Issue by hkennyv** [microsoft/vscode-jupyter#4086]
## Environment data

About:

```
Version: 1.52.0-insider
Commit: bf21395291146c014220eb70b54fdfc0a15956b5
Date: 2020-12-01T09:20:33.868Z (1 day ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0
```

-   VS Code version: 1.52.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.392013122
-   Python Extension version (available under the Extensions sidebar): v2020.11.371526539
-   OS (Windows | Mac | Linux distro) and version: Mac OS 10.14.6 (hackintosh)
-   Python and/or Anaconda version: Python 3.8.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Pressing the "Open Changes" button in new native notebook toolbar (in the top right) should open the Version control tab with a notebook diff

## Actual behaviour

Pressing the "Open Change" button in the new native notebook toolbar does not open the version control tab and shows an error notification in the bottom right:

```
Unable to open 'Untitled-1.ipynb (Working Tree)': e.load is not a function.
```

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. create new directory "nbtest" and `git init` inside
2. Press command+shift+p and select "Create new blank jupyter notebook"
3. Add code to a cell then press command+s to save the notebook in the "nbtest" (current) directory
4. Press the "Open Change" button in the notebook toolbar

upon following these steps, the error notification should pop up

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'NativeNotebookEditor'
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
Error 2020-12-02 12:05:51: Attempted to SaveAs with a model that is not NativeEditorNotebookModel

```

</p>
</details>

**Comment by rchiodo** [comment]
This would actually be on VS code to fix. Not sure why I can't transfer an issue, but can you reopen this there:
https://github.com/microsoft/vscode/issues

**Comment by hkennyv** [comment]
thanks @rchiodo, looks to be a duplicate of microsoft/vscode#111599 and should have been fixed!
