### ISSUE TITLE
Improve notification UX for trusting notebooks 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#4088]
Currently when using notebooks that user VS Code's notebook api, you get prompted every time you open a `.ipynb` file:

<img width="976" alt="Screen Shot 2020-12-02 at 1 34 28 PM" src="https://user-images.githubusercontent.com/12821956/100934096-1addf700-34a3-11eb-8fac-bcaf4ab65e3e.png">

I understand why we cannot run notebook code automatically, but showing the prompt as soon as you open a file feels aggressive. A few thoughts:

- Could the warning be shown somewhere else instead of a notification?

- Could we defer showing the error until there is content that we know will not be rendered or until the user performs an operation, such as trying to execute a cell?

/cc @rebornix

**Comment by rchiodo** [comment]
To answer your questions:

> - Could the warning be shown somewhere else instead of a notification? 

We'd need some other place to put this in the VS code notebook UI. The only place we can stick things is in the toolbar and the output. Kai has mentioned you guys might add the ability for us to have docked panes in the window (we want this to show variables). Might be able to put an untrusted banner at the top then.

> - Could we defer showing the error until there is content that we know will not be rendered or until the user performs an operation, such as trying to execute a cell? 

Any output is considered a security risk. So without an output banner at the top, the user won't know why their old output isn't showing up.

**Comment by greazer** [comment]
We're not going to make any changes to how we manage trusted notebooks. We're waiting for VS Code to implement trusted workspaces. At that point, this is moot.
