### ISSUE TITLE
Unclear why execute cell commands are not available if you dismiss the trust notification

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#4089]
Issue Type: <b>Bug</b>

**Repro** 
1. Make sure you are using VS Code's notebook api
1. Open a new `.ipynb` file
1. See a notificaiton about trusting the notebook
1. Dismiss the notification 
1. Now look to see if you can execute cells
 
**Bug**
I accidentally dismissed the notification and then was confused as to why the execute cell commands/buttons were missing.
 
Could we instead show these buttons but either:

- Show them as disabled with a hover message explaining why they are disabled?
- Allow them to be clicked but show the user UI about trusting the notebook?

Extension version: 2020.11.392013122
VS Code version: Code - Insiders 1.52.0-insider (f4187f22026ff6537f2ca8132ad3209fceb5071f, 2020-12-02T13:18:35.551Z)
OS version: Darwin x64 20.1.0

<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2prompt:30219162
vstry914:30230485
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139

```

</details>

/cc @rebornix

**Comment by rchiodo** [comment]
Thanks for the suggestion. /cc @claudiaregio

**Comment by greazer** [comment]
We're not going to make changes to the trusted notebooks. Waiting for VS Code's trusted workspaces.
