### ISSUE TITLE
Widget Icons for play controls are all broken in native notebooks

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#4095]
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/cf9d9dbc-22ee-4efd-85ae-fcae579d4729)

They all show up as boxes. Same controls are used for stuff like animation in py3js.

**Comment by rchiodo** [comment]
This is font awesome. It needs to be included into the list of stuff we load into the output webview.

**Comment by DonJayamanne** [comment]
Preload the font-awesome stuff.

**Comment by joyceerhl** [comment]
Validated. 
![image](https://user-images.githubusercontent.com/30305945/106095161-22f39500-60e8-11eb-9ad7-aff39a46ae68.png)
