### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by vtzast** [microsoft/vscode-jupyter#4099]
- Issue Type: `Performance`
- Extension Name: `jupyter`
- Extension Version: `2020.11.392013122`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\vtzast\AppData\Local\Temp\ms-toolsai.jupyter-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DonJayamanne** [comment]
Thanks for replying this issue, unfortunately you tried to upload the file.
