### ISSUE TITLE
git diff (aka open changes) has to be issued twice to work (.ipynb)

### ISSUE THREAD

**Issue by giammi56** [microsoft/vscode-jupyter#4101]
## Environment data

Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
ipython 7.19.0 py38hc5df569_0 conda-forge
ipython_genutils 0.2.0 py_1 conda-forge
Type of virtual environment used: conda
Jupyter server running: Local

## Expected behaviour

Display directly the index of the differences

## Actual behaviour

the first issue goes empty, one has to click twice on "Open Changes" to display the changes. Two tabs are open: one is empty (sometimes continuously loading), the other correctly displays the changes

## Steps to reproduce:

1. stage a change
2. right click, open changes
3. right click, open changes (second time)

## Logs

NOTE: I have this packet install  to strip the jupyter outputs
https://github.com/kynan/nbstripout (latest version)

**Comment by DonJayamanne** [comment]
Hmm, I'm unable to repro this issue at my end.

> the first issue goes empty

Please could you provide a screenshot so i have a better idea what this means.

**Comment by giammi56** [comment]
![image](https://user-images.githubusercontent.com/11757284/101086714-8e6e2a00-35b1-11eb-97d3-0b81234b0580.png)

Sorry, I cant' find how to copy the text: second screenshot :)

![image](https://user-images.githubusercontent.com/11757284/101087149-1c4a1500-35b2-11eb-81ae-2d02aa2b441a.png)

**Comment by DonJayamanne** [comment]
Thanks for the screenshot.
Will look into this further.

**Comment by DonJayamanne** [comment]
Thanks for the screenshot.
Will look into this further.

In the mean time, if this is a serious issue that affects your workflow, please consider using the new Native Notebook editor (use VS Code Insiders).
That has better support for diffing (its being worked on, but significantly better).

* Please install VS Code insiders & you'll get it automatically
* Please understand some of the features might not yet be available (variable viewer, run by line, etc)
* See here for more information https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/

**Comment by giammi56** [comment]
well, diff now is not working any more..

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
