### ISSUE TITLE
cannot open .ipynb at the first click

### ISSUE THREAD

**Issue by giammi56** [microsoft/vscode-jupyter#4102]
## Environment data

Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
ipython 7.19.0 py38hc5df569_0 conda-forge
ipython_genutils 0.2.0 py_1 conda-forge
Type of virtual environment used: conda
Jupyter server running: Local
## Expected behaviour

open a .ipynb file

## Actual behaviour

1. upond opening a file it prompts "Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed or enabled."
2. after clicking "Reopen file with VS Code standard text editor" it works

## Steps to reproduce:

1. open a file

**Comment by DonJayamanne** [comment]
Thanks for reporting this issue. I believe we have resolved this in our current dev environment.
The fix will be in the next release.
