### ISSUE TITLE
File and execution lock with continual execution on widget file

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#4104]
Ran into this while testing with native notebooks. Will try to get the repro nailed down, but wanted to get it logged first. I did a run all on a file with widgets. One cell got stuck in an endless execution. When in this state I both couldn't interrupt or close down the file. But I could move around VS Code tabs and do other actions.

![FullVSLockOnWidgetFail.gif](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/2e18a59a-1b6c-408c-8327-252e9cfa8ba0)

**Comment by greazer** [comment]
Not enough info to reproduce.
