### ISSUE TITLE
Error notification: CustomEditor and NativeNotebook experiments cannot be turned on together

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-jupyter#4105]
Testing codespaces scenario https://github.com/microsoft/vssaas-planning/issues/1593
- open a codespace with a Python file
- among other notification dialogs (see microsoft/vscode-python#14833) I get 

![image](https://user-images.githubusercontent.com/6461412/100997910-268cf480-355b-11eb-8674-8fa82a3cc237.png)

Unclear to me as user what has caused this and what I need to do differently.

**Comment by DonJayamanne** [comment]
I think i know what's going on here.
* In insiders NativeNotebook is always on in experiment.
* Now assume user happens to fall into the CustomEditor experiment in VS Code Insiders.
At this point, user is in both experiment groups.

Solution
* Modify the `inExperiment` method to check if `experiment argument == CustomEditor` & if user already belongs to native notebook experiment, in such a case, just return `false`

**Comment by PaoloTCS** [comment]
I have the identical message.  Latest insiders edition of VSC.

**Comment by joyceerhl** [comment]
Validated. I can't simulate control tower opting me into custom editor, but if I manually opt into native notebooks and custom editor experiments in VSCode Insiders, creating a new blank Jupyter notebook still opens into the native notebooks UI and I don't get a prompt. 

@PaoloTCS we have a fix in for this. If the fix works as expected, it will be available in our next release, which will hopefully be in about 2 weeks' time. Thanks for letting us know 😊
