### ISSUE TITLE
Native Notebooks are creating a new kernel on any execution after moving to a different document

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#4109]
Pretty bad issue right now, especially as I don't think that the old kernel is getting shutdown. It will do this again and again for me when moving to another document. 

![NewKernel.gif](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/0adba581-9d05-44ca-a668-bd621f8874f6)

Have one suspicion that I'm looking into right now.

**Comment by greazer** [comment]
Not able to repro this on shipping extension. May be a regression that was recently caused (but thankfully not shipped)

**Comment by DonJayamanne** [comment]
I tried, & cannot repro this issue.

**Comment by DavidKutu** [comment]
I'm also unable to repro this.

**Comment by IanMatthewHuff** [comment]
@DavidKutu @DonJayamanne I'll take over investigation on this.

**Comment by IanMatthewHuff** [comment]
Did some more work to pin down at least one repro. Scenario is as follows. Python extension required for this scenario.

1. Create a new jupyter notebook
2. Run this notebook with a selected installed kernelspec, not just an interpreter (we need 'startUsingKernelSpec' as our connection type)
3. Change the active interpreter
4. Do something to retrigger vscode kernel provider fetching swap to a different document and back
5. Execute a cell again (it will reconnect to a new kernel instance)

**Comment by rchiodo** [comment]
Validated. Does not create a new kernel after following the steps above.
