### ISSUE TITLE
Telemetry needs to be better documented

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4121]
The telemetry constants in this file here:
```src\client\datascience\constants.ts```

could be better documented. This way a 3rd party or our own PMs can understand what causes a telemetry event to fire. 

At the very least we should enforce documentation on new events.

**Comment by DonJayamanne** [comment]
Something we wanted to do, but never did happen.
I agree we should enforce it or add a simpler linter to check this.

**Comment by DavidKutu** [comment]
Dupe of #4960
