### ISSUE TITLE
Use the new VSC API to trust output 

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4122]
See here https://github.com/microsoft/vscode/issues/108946#event-3895074324 & https://github.com/microsoft/vscode/issues/109104

We must change the existing code to use the new VSC API, as current approach is very hacky
(when we trust a notebook, we perform an edit and prevent VSCode from seeing it as a dirty change & force it to reload the notebook).
**Hopefully with the new VSC API - all we need to do is just update a single property**

**Comment by DonJayamanne** [comment]
Block due to https://github.com/microsoft/vscode/issues/114936

**Comment by kieferrm** [comment]
The upstream issues is closed.

**Comment by DonJayamanne** [comment]
Closing this as we've done what needs to be done, and we'll update the changes when there are new changes to propopsed API and workspace trust.
