### ISSUE TITLE
Opening a Jupyter Notebook doesn't trigger loading of Python and Jupyter Extension

### ISSUE THREAD

**Issue by sarthak7gupta** [microsoft/vscode-jupyter#4125]
Steps to reproduce-
1. Open a VS Code window.
2. Opening a .ipynb file doesn't trigger the Python and Jupyter extensions to load, it shows raw JSON.
3. Opening a .py file, however, loads the extensions and then the Jupyter Notepad renders.

P.S.- I'm not sure if I explained the issue properly, or if it's an issue at all. I couldn't find a related post elsewhere. Also, i hope this is the correct repository to be posting the issue to.

Extension version: 2020.11.392013122
VS Code version: Code 1.51.1
OS version: Linux x64 5.4.0-56-generic snap

**Comment by joyceerhl** [comment]
Hey @sarthak7gupta this is definitely a problem. This sounds like VSCode isn't activating us when they should. Has this been a problem before or did it manifest with an upgrade?

**Comment by sarthak7gupta** [comment]
I've been facing this problem for quite a while now on the Stable VS Code. The latest VS Code Insiders, with the redesigned Jupyter UI, however does not seem to have this issue

**Comment by greazer** [comment]
@sarthak7gupta, can you try opting into the custom editor experiment? We're likely to turn this feature on for all users in the near term. 

```    
"jupyter.experiments.optInto": [
        "CustomEditor"
    ],
```
