### ISSUE TITLE
Jupyter notebook restart changes cwd

### ISSUE THREAD

**Issue by jdnewmil** [microsoft/vscode-jupyter#4126]
To reproduce:

1) use terminal/CMD to change directory to a working directory.
2) enter "code ."
3) open an ipynb file
4) execute a cell
4) enter "import os; os.getcwd()" in the interactive window, note that it indicates the working directory
5) restart the kernel
6) enter "import os; os.getcwd()" in the interactive window, and it will report the directory in which VSCode is installed rather than the working directory.

VSCode 1.51.1 (Windows 10)
Python extension version 2020.11.371526539

**Comment by joyceerhl** [comment]
Thanks for logging a bug @jdnewmil. Would you expect the kernel cwd to be the same before and after requesting a restart?

To fix this we'd want to also run this code after a kernel restart:
https://github.com/microsoft/vscode-jupyter/blob/a3d35d46cb3b487d21243964069bc929ec590e1b/src/client/datascience/jupyter/jupyterNotebook.ts#L949

where `directory` is the result of `os.getcwd()` at the time of the restart request.

**Comment by jdnewmil** [comment]
> Would you expect the kernel cwd to be the same before and after requesting a restart?

I think that would have the least element of surprise. Alternatively, use one of the root or workspace directories configured in the VSCode UI, which would create a mechanism for controlling the cwd of the kernel (change configured directory, restart kernel). As it is, before the restart my data files are straightforward to access with relative paths, but afterward I need absolute paths.

**Comment by greazer** [comment]
I'm no longer reproing this. At least on vscode insiders.
