### ISSUE TITLE
(CTRL + Enter) run code shortcut in Native View is actually (Shift + Enter)

### ISSUE THREAD

**Issue by Bewinxed** [microsoft/vscode-jupyter#4131]
## Environment data

-   VS Code version: 1.52.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.399280825
-   Python Extension version (available under the Extensions sidebar): v2020.12.394869726-dev
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: 3.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda but no venv
-   Jupyter server running: Local

Version: 1.52.0-insider (user setup)
Commit: 92192baf760315ac47fb2caaf3ce6d0778962352
Date: 2020-12-03T05:43:59.635Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

## Expected behavior

Code in the cell is executed

## Actual behavior

A new line is entered instead.

## Steps to reproduce:

1 - Select any cell.

2 - It is prompt that you can CTRL+Enter to run code.
![image](https://user-images.githubusercontent.com/9145989/101208759-b332d200-3683-11eb-8c55-6233dd0af6c4.png)

3 - Click CTRL+Enter
4 - It inserts a new line instead.

**Comment by claudiaregio** [comment]
Hi @Bewinxed,

Could you please go to File -> Preferences -> Keyboard shortcuts -> Type "Ctrl + Enter" and paste a photo of the commands you are seeing? 

![image](https://user-images.githubusercontent.com/19276747/101262061-a26c7580-36f0-11eb-9425-c94f3abae549.png)

**Comment by Bewinxed** [comment]
Hello, Find it below, I see lots of commands however none of these I have
set up myself, it's a clean install.

[image: image.png]

**Comment by Bewinxed** [comment]
For some reason the image didn't go through email, here it is:

![image](https://user-images.githubusercontent.com/9145989/101287306-89eb8080-3800-11eb-9fe9-30fde872d74a.png)

**Comment by claudiaregio** [comment]
Thanks @Bewinxed. 

@greazer I have the most recent stable version of all extensions and I am seeing Ctrl + Alt + Enter to run instead of the Ctrl + Enter the customer is seeing (must be due to different python extension versions). Either way it looks like the extension shortcut is not overriding the notebook shortcuts? 

![image](https://user-images.githubusercontent.com/19276747/101289325-9647ed00-37b0-11eb-8a0c-d428e7ac2b00.png)

**Comment by Bewinxed** [comment]
By the way, actually, most shortcuts don't work, for example, clear output ALT+Z does nothing.

CTRL+Z sometimes works but other times sends the kernel into an infinite run, pressing CTRL+Z again stops this but have to go to edit=> undo so CTRL+Z works again.

Just checked again and the shortcut prompt for running the cell is fine now?

![image](https://user-images.githubusercontent.com/9145989/101289607-9676d580-380e-11eb-8b3b-dc5d91986a96.png)

Python v2020.12.394869726-dev
Jupyter v2020.11.399280825
Version: 1.52.0-insider (user setup)
Commit: 5e350b1b79675cecdff224eb00f7bf62ae8789fc
Date: 2020-12-04T10:15:27.849Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by joyceerhl** [comment]
>  the extension shortcut is not overriding the notebook shortcuts?

@claudiaregio that text is set by VSCode. We don't have control over that tooltip.

>  the shortcut prompt for running the cell is fine now?

@Bewinxed this was recently fixed by VSCode, sorry about the confusion: https://github.com/microsoft/vscode/commit/b617b725a06169c39dcae398ee7c21d44bebe6b2

**Comment by joyceerhl** [comment]
@claudiaregio do you know if the intent for the Alt+Delete shortcut to clear notebook cell outputs is meant to be operational 
1. when the cell is only selected but not focused, or
1. when the cell is both selected and focused?

**Comment by claudiaregio** [comment]
@joyceerhl My assumption is that it should work for both cell selected state and cell editor but will confirm with Peng

**Comment by greazer** [comment]
Closing per discussion above.
