### ISSUE TITLE
No cell output for bokeh server apps but static plots are fine

### ISSUE THREAD

**Issue by bsaintmichel** [microsoft/vscode-jupyter#4132]
## Environment data

-   VS Code version: 1.51.1
-   Jupyter Extension version: 2020.11.399280825
-   Python Extension version: 2020.11.371526539
-   OS and version: Windows 10 64-bit
-   Python version: Python 3.8.6 64-bit _(not conda)_
-   Type of virtual environment used: N/A
-   Jupyter server running: Local

## Expected behaviour

I would like to make animated plots in Bokeh through Bokeh server apps. _Producing static figures works in my environment_. I expected animated plots through Bokeh server apps to be working too.

## Actual behaviour

[The demo code of bokeh regarding notebook server apps](https://github.com/bokeh/bokeh/blob/branch-2.3/examples/howto/server_embed/notebook_embed.ipynb) produces no output in VSCode _but_ works perfectly fine in Jupyter Lab & Jupyter Notebook. I had the same issue with my computer at work (Linux 18.04 x64 LTS with Python 3.6.X).

My issue seems related to [this one](https://github.com/microsoft/vscode-jupyter/issues/417) but I am not savvy enough to confirm it is the same problem. If it is I would be happy to get more information on how to set up the mime-types used for rendering.

## Steps to reproduce:
0. (Install Python, VSCode, Jupyter Extension, IPykernel, and Bokeh directly from VSCode or using `pip`)

1. Run the (working) static plot in VSCode

```python
import numpy as np
from bokeh.plotting import figure
from bokeh.io import show, output_notebook

output_notebook()

x = np.linspace(0,4*np.pi, 100)
y = np.sin(x)
plot = figure(width=400, height=400)
plot.line(x,y)
show(plot)
```

2. Run the (no output) bokeh server app in VSCode

```python

from bokeh.layouts import column
from bokeh.models import ColumnDataSource, Slider
from bokeh.plotting import figure
from bokeh.io import show, output_notebook
from bokeh.sampledata.sea_surface_temperature import sea_surface_temperature

output_notebook()

def bkapp(doc):

    print('OHOHO')

    df = sea_surface_temperature.copy()
    source = ColumnDataSource(data=df)

    plot = figure(x_axis_type='datetime', y_range=(0, 25),
                  y_axis_label='Temperature (Celsius)',
                  title="Sea Surface Temperature at 43.18, -70.43")
    plot.line('time', 'temperature', source=source)

    def callback(attr, old, new):
        if new == 0:
            data = df
        else:
            data = df.rolling('{0}D'.format(new)).mean()
        source.data = ColumnDataSource.from_df(data)

    slider = Slider(start=0, end=30, value=0, step=1, title="Smoothing by N Days")
    slider.on_change('value', callback)

    doc.add_root(column(slider, plot))

    print(doc)

show(bkapp)
```

3. Launch `jupyter lab` and run code from 2. Somehow it works !?!?

## Python package versions just in case

alembic             1.4.3     
argon2-cffi         20.1.0    
astroid             2.4.2     
async-generator     1.10      
atomicwrites        1.4.0     
attrs               20.3.0    
backcall            0.2.0     
bleach              3.2.1     
bokeh               2.2.3     
certifi             2020.11.8 
certipy             0.1.3     
cffi                1.14.4    
chardet             3.0.4     
colorama            0.4.4     
cryptography        3.2.1     
cycler              0.10.0    
Cython              0.29.21   
decorator           4.4.2
defusedxml          0.6.0
entrypoints         0.3
gitdb               4.0.5
GitPython           3.1.11
idna                2.10
imageio             2.9.0
iniconfig           1.1.1
ipykernel           5.3.4
ipython             7.19.0
ipython-genutils    0.2.0
ipywidgets          7.5.1
isort               5.6.4
jedi                0.17.2
Jinja2              2.11.2
JPype1              1.2.0
json5               0.9.5
jsonschema          3.2.0
jupyter-client      6.1.7
jupyter-core        4.7.0
jupyter-telemetry   0.1.0
jupyterlab          2.2.9
jupyterlab-pygments 0.1.2
jupyterlab-server   1.2.0
kiwisolver          1.3.1
lazy-object-proxy   1.4.3
Mako                1.1.3
MarkupSafe          1.1.1
matplotlib          3.3.3
mccabe              0.6.1
mistune             0.8.4
natsort             7.1.0
nbclient            0.5.1
nbconvert           6.0.7
nbformat            5.0.8
nbserverproxy       0.8.8
nest-asyncio        1.4.3
networkx            2.5
notebook            6.1.5
numpy               1.19.4
oauthlib            3.1.0
OpenPIV             0.23.1
packaging           20.7
pandas              1.1.4
pandocfilters       1.4.3
parso               0.7.1
pickleshare         0.7.5
Pillow              8.0.1
PIMS                0.5
pip                 20.3.1
pluggy              0.13.1
prometheus-client   0.9.0
prompt-toolkit      3.0.8
psutil              5.7.3
py                  1.9.0
pycparser           2.20
Pygments            2.7.2
pylint              2.6.0
pyOpenSSL           20.0.0
pyparsing           2.4.7
pyrsistent          0.17.3
pytest              6.1.2
python-dateutil     2.8.1
python-editor       1.0.4
python-json-logger  2.0.1
pytz                2020.4
PyWavelets          1.1.1
pywin32             300
pywinpty            0.5.7
PyYAML              5.3.1
pyzmq               20.0.0
requests            2.25.0
ruamel.yaml         0.16.12
ruamel.yaml.clib    0.2.2
scikit-image        0.17.2
scipy               1.5.4
Send2Trash          1.5.0
setuptools          49.2.1
six                 1.15.0
slicerator          1.0.0
smmap               3.0.4
SQLAlchemy          1.3.20
terminado           0.9.1
testpath            0.4.4
tifffile            2020.11.26
toml                0.10.2
tornado             6.1
tqdm                4.54.0
trackpy             0.4.2
traitlets           5.0.5
typing-extensions   3.7.4.3
urllib3             1.26.2
wcwidth             0.2.5
webencodings        0.5.1
widgetsnbextension  3.5.1
wrapt               1.12.1

### Jupyter

Info 2020-12-04 20:55:03: Executing cell NotebookImport#0
Info 2020-12-04 20:55:03: Submitting code for 59f53695-ab6a-4751-b749-899c057bfbfd
Info 2020-12-04 20:55:03: Kernel switching to busy
Info 2020-12-04 20:55:03: Kernel switching to idle
Info 2020-12-04 20:55:03: Finished execution for NotebookImport#0
Info 2020-12-04 20:55:03: Finished executing cell NotebookImport#0

**Comment by rchiodo** [comment]
When I try the same I get this:

```
ERROR:bokeh.server.views.ws:Refusing websocket connection from Origin 'vscode-webview://8676e056-ff6e-461f-b0b9-4b600c50665f';                       use --allow-websocket-origin=8676e056-ff6e-461f-b0b9-4b600c50665f or set BOKEH_ALLOW_WS_ORIGIN=8676e056-ff6e-461f-b0b9-4b600c50665f to permit this; currently we allow origins {'localhost:8888'}
WARNING:tornado.access:403 GET /ws?platform=electron (::1) 1.00ms
```

I believe this is a problem for bokeh to handle. They will only load in a browser.

**Comment by rchiodo** [comment]
Although we could potentially special case bokeh and modify their JS to use a proxy instead. Not sure if we'd do that or not.

**Comment by bsaintmichel** [comment]
Ah ! I did not see that error, that would have obviously been helpful. I hesitated between a post here and in the bokeh community.


Thanks for the help, I'll mention the issue to them.
