### ISSUE TITLE
Carriage Return Added to Magic Command's Argument

### ISSUE THREAD

**Issue by bisen2** [microsoft/vscode-jupyter#4133]
## Environment data

-   VS Code version: 1.52.0-insider
-   Jupyter Extension version: 2020.12.360105876-dev
-   Python Extension version: 2020.12.401222302-dev
-   OS and version: Windows 10 Enterprise Version 2004
-   Python and/or Anaconda version: conda 4.9.2, python 3.8.3
-   Type of virtual environment used: NA
-   Jupyter server running: Local

## Additional environment data
-   VS Code also has the .NET Interactive Notebooks Extension installed
    - .NET Interactive Notebooks is Version 1.0.160204
-   This behavior is not reproducible in a browser-based Jupyter notebook running the same kernel

## Expected behaviour

When loading an IPython extension with another line in the cell, the `%load_ext <ext_name>` command should work the same as if it were the only line in the cell: load the extension and not throw an error.

## Actual behaviour

`%load_ext <ext_name>` works as expected if it is the only line in the cell, but raises a `ModuleNotFoundError` if there is another line. This appears to be happening because IPython is reading `%load_ext <ext_name>\r` and is searching for an extension called `<ext_name>\r`, which does not exist.

## Steps to reproduce:

1. Install a the `ipython-sql` extension (any extension will do, this is just an example).
2. Open a new blank Jupyter notebook in VSCode.
3. Enter `%load_ext sql` with an additional line after it in a cell.
4. Run the cell.

## Note
I am not sure if this is the proper place to report this. My assumption would have been that IPython would already strip trailing whitespace before searching for a package name, but the fact that this issue is not consistent in the browser based Jupyter notebook led me to post it here. If this would be a better fit for [the IPython repo](https://github.com/ipython/ipython) I can repost this issue there. Looking at [this comment in the IPython repo](https://github.com/ipython/ipython/issues/5640#issuecomment-40640366), it is implied that IPython already strips trailing whitespace from line magics, so I am unsure why that is not happening in this case.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel
</summary>

```
> ~\Anaconda3\python.exe c:\Users\BIsenhart\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.360105876-dev\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> ~\Anaconda3\python.exe c:\Users\BIsenhart\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.360105876-dev\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
Started kernel Python 3
> ~\Anaconda3\python.exe c:\Users\BIsenhart\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.360105876-dev\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~\Anaconda3\python.exe c:\Users\BIsenhart\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.360105876-dev\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
```
</details>

<details>

<summary>IPython Error Message</summary>

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-478f3b08bc39> in <module>
----> 1 get_ipython().run_line_magic('load_ext', 'sql\r')
~\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2324                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2325             with self.builtin_trap:
-> 2326                 result = fn(*args, **kwargs)
   2327             return result
   2328 
<decorator-gen-65> in load_ext(self, module_str)
~\Anaconda3\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):
~\Anaconda3\lib\site-packages\IPython\core\magics\extension.py in load_ext(self, module_str)
     31         if not module_str:
     32             raise UsageError('Missing module name.')
---> 33         res = self.shell.extension_manager.load_extension(module_str)
     34 
     35         if res == 'already loaded':
~\Anaconda3\lib\site-packages\IPython\core\extensions.py in load_extension(self, module_str)
     78             if module_str not in sys.modules:
     79                 with prepended_to_syspath(self.ipython_extension_dir):
---> 80                     mod = import_module(module_str)
     81                     if mod.__file__.startswith(self.ipython_extension_dir):
     82                         print(("Loading extensions from {dir} is deprecated. "
~\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 
~\Anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)
~\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)
~\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)
ModuleNotFoundError: No module named 'sql\r'
```
</details>

**Comment by claudiaregio** [comment]
Thanks @bisen2, will have someone review next week

**Comment by joyceerhl** [comment]
Unfortunately I can't repro this. @bisen2 what version of ipython do you have installed?

**Comment by bisen2** [comment]
My IPython version is 7.16.1

**Comment by greazer** [comment]
@bisen2, please reopen if this problem still occurs using the new notebook experience in VS Code Insiders
