### ISSUE TITLE
Native Notebooks - Cells running out of order

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#4136]
## Expected behavior

Cells to run in order 

## Actual behavior

Cells run out of order

## Steps to reproduce:

1. Open notebook
2. Run 3 cells to connect to kernel
3. Cells run out of order
(Once connected to kernel, the issue does not exist, only happens when running to connect to kernel) 

![Cells out of order](https://user-images.githubusercontent.com/19276747/101262460-c9787680-36f3-11eb-8f2f-26945768b53a.gif)

**Comment by DonJayamanne** [comment]
Validated
