### ISSUE TITLE
The error message output hasn't font

### ISSUE THREAD

**Issue by xsoheilalizadeh** [microsoft/vscode-jupyter#4138]
Issue Type: <b>Bug</b>

The error message in the output box hasn't any font to represent a better appearance.

![image](https://user-images.githubusercontent.com/22220356/101290141-b3fb6d80-3815-11eb-9482-fe0f7caf35ac.png)

Extension version: 2020.11.399280825
VS Code version: Code - Insiders 1.52.0-insider (5e350b1b79675cecdff224eb00f7bf62ae8789fc, 2020-12-04T10:15:27.849Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.89GB free)|
|Process Argv|--crash-reporter-id b20e30ad-198c-4114-b96c-608fbcb79ecb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2promptcf:30219163
vstry244:30230484
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by joyceerhl** [comment]
Thanks for the feedback @xsoheilalizadeh. Are you referring to the 
> NameError: name 'a' is not defined

message? What font would you like to see instead?

**Comment by xsoheilalizadeh** [comment]
The whole output message not only the main error message (only the error messages haven't font), in the stable version of Jupyter you could see that it has a font. I don't know what font would be appropriate in this case but it was better in the stable version.

![image](https://user-images.githubusercontent.com/22220356/101317740-564a3e00-3874-11eb-90b2-c5786e9d29b5.png)


@joyceerhl

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on changing this functionality at this time.
