### ISSUE TITLE
Gather: Use notebookIdentity instead of notebook.identity when handling external commands

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-jupyter#414]

**Comment by rchiodo** [comment]
Not sure this is working? I tried this on an untitled notebook and I get this error (after running cells)

```
Please run cells before gathering
```

**Comment by DavidKutu** [comment]
That's expected. Before nothing showed up.

**Comment by rchiodo** [comment]
Maybe that's a separate bug. Works on a notebook with a file.

**Comment by rchiodo** [comment]
> It does work if you run the cell, right?

Not in an untitled notebook.

**Comment by DavidKutu** [comment]
I couldn't repro that, what did you do? I did:

1. Create new blank NB
1. press gather
`Please run cells before gathering` comes out
1. write whatever code on the first cell
1. run the cell
1. press gather
`works as expexted`

**Comment by rchiodo** [comment]
I opened a notebook that was already untitled (reloaded VS code) and ran the first cell. Tried to gather and got the error.

**Comment by DavidKutu** [comment]
Weird, I can't repro in that case either.

**Comment by rchiodo** [comment]
Now the gather button isn't showing up on reload.

**Comment by rchiodo** [comment]
Reloaded again and gather button shows up again. Something is fishy.
