### ISSUE TITLE
How to use my own custom "dark" toolbar icons?

### ISSUE THREAD

**Issue by mkanet** [microsoft/vscode-jupyter#4141]
My apologies if this is not the correct place to ask this kind of question.  If it is not, please feel free to close this issue.  I also asked the [same question](https://stackoverflow.com/questions/65176506/how-to-use-my-own-custom-dark-toolbar-icons) on StackOverflow below.  Hopefully, someone would be kind enough to help me out:

https://stackoverflow.com/questions/65176506/how-to-use-my-own-custom-dark-toolbar-icons

## Environment data

-   VS Code version: 1.51.1 (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): 2020.11399280825
-   Python Extension version (available under the Extensions sidebar): 2020.11.371526539
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Version 2004 (64bit)
-   Python and/or Anaconda version: Python 3.7.4 (64bit)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Jupyter server running: Local | Remote | N/A: Local

I would like to use my own custom 'dark' toolbar icons in Jupyter when in Interactive mode.  If I change the stock .svg icons under:
      

    \.vscode\extensions\ms-toolsai.jupyter-2020.11.399280825\dark\*

..I still see the original "dark" icons after restarting VSCode and Jupyter again. It appears the icons get cached on first use. I'm hoping someone would please be kind enough to show me to force Jupyter to reload its icons without reinstalling the extension again... or, any other way to be able to use my icons. My icons are almost identical in size to the original icons, except they are different colors.

In a related note... I noticed that if I make any modifications to

    \.vscode\extensions\ms-toolsai.jupyter-2020.11.399280825\out\client\extensions.js

These changes don't affect the Jupyter extension after restarting VSCode. I'm guessing it might be the same reason why my custom icons are also ignored. I'm not even sure why these source files are there if they're not being used after the extension is installed.

Ideally, I'd like to make these kinds of enhancements via my own extension. I would be grateful if someone could show me how to make these kinds of changes with my own extension. However, I would be happy with a quick hack in the meantime.

Thanks again for all your effort in making such a great Extension!

**Comment by joyceerhl** [comment]
Unfortunately all the svgs under out/resources/dark/* either are unused or pertain only to our new native notebooks UI, and not to the interactive window.

The svgs for the interactive window are loaded inline and not read from disk, so I don't think what you're trying to do is possible:

https://github.com/microsoft/vscode-jupyter/blob/a3d35d46cb3b487d21243964069bc929ec590e1b/src/datascience-ui/react-common/image.tsx#L10-L215

To do what you're trying to accomplish, you would need to fork this repo and switch the svgs under this directory https://github.com/microsoft/vscode-jupyter/tree/main/src/datascience-ui/react-common/images, then build the extension from source yourself. I hope that helps 😊

**Comment by mkanet** [comment]
Thank you for the quick reply back.  Are there any instructions to build it; or, will it work as-is by just extracting the files from the zip to my extensions directory (and use it instead of the one that I installed via VSCode)?  I'm just looking for the quickest way to get it working.

**Comment by joyceerhl** [comment]
I'm not sure what you mean by 'extracting the files from the zip to my extensions directory'. I believe you'd need to build the whole extension from source after changing the svgs. Here are instructions to build it: https://github.com/microsoft/vscode-jupyter/blob/main/CONTRIBUTING.md#local-build 

You will also need to install the development dependencies listed here https://github.com/microsoft/vscode-jupyter/blob/main/CONTRIBUTING.md#prerequisites

**Comment by mkanet** [comment]
Hi @joyceerhl.  Thank you so much for your help.  I was actually hoping to make a very small change/hack to override pre-built webpack resource with a custom one. 

Do you know how I can modify the currently installed extension so it will use my modified file:
`file:///D:/image.tsx`

instead of...
`webpack:///./src/datascience-ui/react-common/image.tsx`

I tried changing **commons.initial.bundle.js.map** to point to my modified file, however, that didn't make any difference.

I'm open to any tips/suggestions that might help me do this without having to setup a development PC environment just to change a few icons.  I even tried overriding these resources via CSS mod using VSCode Developer Tools.. however, Developer Tools doesn't have access to these resources either.

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on solving this type of customization.

**Comment by mkanet** [comment]
No worries.  I was able to make the toolbar icons more visible by changing the base theme color from "VS-Dark" to "VS"
