### ISSUE TITLE
Extension jupyter causes high cpu load

### ISSUE THREAD

**Issue by oligu** [microsoft/vscode-jupyter#4144]
[ms-toolsai.jupyter-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-jupyter/files/5654130/ms-toolsai.jupyter-unresponsive.cpuprofile.txt)

- Issue Type: `Performance`
- Extension Name: `jupyter`
- Extension Version: `2020.11.399280825`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\OLIVER~1.GUB\AppData\Local\Temp\ms-toolsai.jupyter-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by joyceerhl** [comment]
Hi @oligu please attach the following file in a comment so we can assist you:

c:\Users\OLIVER~1.GUB\AppData\Local\Temp\ms-toolsai.jupyter-unresponsive.cpuprofile.txt

**Comment by oligu** [comment]
Hi @joyceerhl, you can find the requested file in the link at the top of my original post.

**Comment by joyceerhl** [comment]
So sorry I missed that. After loading the cpuprofile into the profiler it seems that `t.guid` is the bottleneck. Looking at out/client/extension.js, I see `t.guid` in the context of what appears to be inversify library code. We're on version 4.13.0, which is deprecated, and inversify actually deprecated their use of GUIDs 2 years ago with version 5.0.1. Perhaps we should bump our inversify version? /cc @DonJayamanne @rchiodo @IanMatthewHuff @DavidKutu

**Comment by DonJayamanne** [comment]
I agree, let's update

**Comment by joyceerhl** [comment]
@DonJayamanne will do that today

**Comment by joyceerhl** [comment]
Do we have a way to verify that such changes are not degrading performance?

**Comment by DonJayamanne** [comment]
> Do we have a way to verify that such changes are not degrading performance?

No.

**Comment by ydennisy** [comment]
I am seeing this same issue, with a high CPU load, unresponsive warning in the console and then the webview becoming indisposed :(

**Comment by kjohnsen** [comment]
I'm getting a constant considerable CPU usage from `electron_node bundle.js` whenever a notebook is open and idle:
![image](https://user-images.githubusercontent.com/19983357/106001814-6a453b80-607e-11eb-91a7-0a6971ccc654.png)

When I manually kill the offending process, I am able to use the notebook as normal without any apparent loss of function.

**Comment by ydennisy** [comment]
@joyceerhl is there any update here?

**Comment by joyceerhl** [comment]
Hi @ydennisy, thanks for checking in. Our December release included a dependency upgrade which should reduce the impact of `t.guid` on performance. If you are still encountering high CPU load, please open a new GitHub issue with the CPU profile the way that @oligu did, as it's possible the performance issue you are observing is caused by something else.
