### ISSUE TITLE
Native Notebooks + Custom Editor Error? 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#4146]
Got the following customer error from survey. 

"CustomEditor and NativeNotebook experiments cannot be opened together" - this is the error i get everytime i try to open an .ipynb file.  I undestand bugs happen, but when they do, a detailed explanation of what went wrong should be available (most of us vscode users are devs ourselves, when something breaks, we like to know why, so we might address the issue)." 

Can someone clarify what logic would trigger this error to a user? Would like to update the error to be more clear + potentially provide location to resolution instructions.

**Comment by DonJayamanne** [comment]
We believe we have resolved this issue in the recent point release.
Hence closing this issue.
If this comes up again we can re-visit it.
