### ISSUE TITLE
IPyVolume test is timing out

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4152]
![image](https://user-images.githubusercontent.com/19672699/101418966-d6d46300-38a3-11eb-93b5-24699f5b9257.png)

Disabling test for now. Hit this on two separate PRs. Looks to be different than render_execution failures.

**Comment by greazer** [comment]
Re-enable the test. We think it's fixed.

**Comment by rchiodo** [comment]
Should be fixed by Don's PR: https://github.com/microsoft/vscode-jupyter/pull/4306
