### ISSUE TITLE
Failing to prompt to install ipykernel when starting kernel with conda env

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#4153]
1. Install miniconda
2. Create a new env without anything installed in it
3. Create a new blank native notebook
4. Try to run any code cell
5. We simply timeout waiting for a heartbeat without ever asking the user to install data science dependencies
6. If you try to run a code cell again you get an uninformative 'Canceled' error prompt

For the old webview notebooks I do get the prompt when first creating a notebook (maybe because we're prewarming kernels there and can't do that for native notebooks), but if I use the kernel selector to switch to an env that doesn't have ipykernel installed and then try to run code, I get the same timeout problem.

**Comment by DonJayamanne** [comment]
Validate if this has been fixed

**Comment by rchiodo** [comment]
This has not been fixed. I still repro it.

**Comment by rchiodo** [comment]
@DonJayamanne I'm guessing your latest kernel change should fix this? Or did you already submit it?

**Comment by DonJayamanne** [comment]
When I get a prompt to install IPykernel I clicked no & I get two messages, one error & one warning.
Ideally I should get just one message, not multiple:

See below screen

![Screen Shot 2021-01-22 at 15.19.35.png](https://images.zenhubusercontent.com/59df9ec4b0222d5de47b6b0f/32527bb6-e126-4a66-8ccc-aecdbe6f114b)shot

**Comment by DonJayamanne** [comment]
Wait , let me test if this was the original behaviro.
