### ISSUE TITLE
LD_LIBRARY_PATH is not respected

### ISSUE THREAD

**Issue by hzfmer** [microsoft/vscode-jupyter#4156]
## Environment data

-   VS Code version: 1.51.1
-   Jupyter Extension version (available under the Extensions sidebar): !ldd /ccs/home/hzfmer/file_back/programs/andes/anaconda3/lib/python3.8/site-packages/osgeo/_gdal.cpython-38-x86_64-linux-gnu.so | grep libnsl

-   Python Extension version (available under the Extensions sidebar): !ldd /ccs/home/hzfmer/file_back/programs/andes/anaconda3/lib/python3.8/site-packages/osgeo/_gdal.cpython-38-x86_64-linux-gnu.so | grep libnsl

-   OS (Windows | Mac | Linux distro) and version: Linux-Red Hat 7.6
-   Python and/or Anaconda version: 3.8.3-Anaconda
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

## Expected behaviour
I was trying to import a package "gdal" from "osgeo", which is successful if I ran it in the system or VSCode terminal, while in vscode-jupyter it was unable to find the dynamic library "libnsl.so.1".  It's strange that `ldd` in the terminal finds it, but Jupyter doesn't.

I have added the location of this library to `LD_LIBRARY_PATH`, and Jupyter seems to read the variable, but somehow doesn't respect it.

## Actual behaviour

![image](https://user-images.githubusercontent.com/28425640/101457384-51c06c80-38ea-11eb-9213-83dbef942f76.png)

## Steps to reproduce:
This might be not very likely to reproduce, since I am working on an HPC cluster.
I would expect some setting/configuration as a workaround.

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by IanMatthewHuff** [comment]
@hzfmer Sorry about the issue here. 

Are you able to load this notebook in normal jupyter (just starting `jupyter notebook` from the command line) and have it work outside of VS Code? I wasn't sure from your example how you were setting that LD_LIBRARY_PATH for jupyter. But in general I would think that you'd have to specify it in the kernel.json file to actually get it picked up in the Jupyter (not terminal scenario). Is that how you are specifying it for the notebook?

Example would be the second reply on this thread here:
https://stackoverflow.com/questions/37890898/how-to-set-env-variable-in-jupyter-notebook

**Comment by hzfmer** [comment]
@IanMatthewHuff 
Thanks.  I can run this notebook directly, and this module can be imported if I use **Chrome** to remotely loading the notebook. So Web and VSCode perform differently.

My `LD_LIBRARY_PATH` was set in my **~/.bashrc**, and as you can see `os.environ['LD_LIBRARY_PATH']` does include this path.

I tried to add 
> "env": {"LD_LIBRARY_PATH":"~/.local/lib"} 

to _~/file_back/programs/andes/anaconda3/share/jupyter/kernels/python3/kernel.json_, which doesn't work either.

I don't understand why the same command gives different results if running in Jupyter?
```
!ldd ~/file_back/programs/andes/anaconda3/lib/python3.8/site-packages/osgeo/_gdal.cpython-38-x86_64-linux-gnu.so | grep libnsl

# libnsl.so.1 => not found
```
While in Vscode integrated terminal:
```
ldd ~/file_back/programs/andes/anaconda3/lib/python3.8/site-packages/osgeo/_gdal.cpython-38-x86_64-linux-gnu.so | grep libnsl

# libnsl.so.1 => ~/.local/lib/libnsl.so.1 (0x00007f8ea120b000)
```

**Comment by IanMatthewHuff** [comment]
Ok, so a few more questions here. Sorry about this, but without a local repro to look at it's a bit trickier to drill down on this.

1. You mentioned that you are running against a remote jupyter server in your initial issue post. Does this mean that you are connecting to a remote machine using the "Jupyter: Specify local or remote server for connection" setting in vs code? Or is VS Code actually running on the machine that is executing the notebook?
2. Can you tell me more about the conda environment that you are using to run this? 
3. If you print your current working directory, is it the same in the vscode terminal versus in the jupyter notebook?

The thought here is that your context for executing in Jupyter is not the same as executing the terminal. This is expected to some degree, you might have a different working directory, environment, interpreter and other things that would cause one to fail and the other to succeed. Just trying to narrow down what the difference is given my questions above. 

Given what I've seen online we do need to make sure that LD_LIBRARY_PATH is set before Jupyter / IPython is started up.
https://github.com/jupyter/notebook/issues/1290

**Comment by hzfmer** [comment]
@IanMatthewHuff  
Please check below:
> using the "Jupyter: Specify local or remote server for connection" setting in vs code? Or is VS Code actually running on the machine that is executing the notebook?

I used "remote-ssh"  to connect to the server first, and then open the jupyter file. So VS Code is running on the remote server.

> about the conda environment that you are using to run this
I recently reinstalled the Anaconda on the server, which is migrating to a new system. 
```
>> lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RedHatEnterprise
Description:	Red Hat Enterprise Linux release 8.1 (Ootpa)
Release:	8.1
Codename:	Ootpa

>> conda --version
conda 4.9.2
>> python -c "import sys; print(sys.version)"
3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00) 
[GCC 7.5.0]

##  gdal is installed using conda:
>> conda install -c conda-forge gdal
>> conda list gdal
packages in environment at ~/file_back/programs/andes/anaconda3:

Name                    Version                   Build  Channel
gdal                      3.0.4            py38h172510d_4    conda-forge
libgdal                   3.0.4                h9e6407a_4    conda-forge
```


My environment is a bit unusual that my default SHELL is **/bin/zsh**, but for some reasons I have to switch to using **/bin/bash** on the server. Yet Jupyter is started with **zsh**, which probably messed things up. Web remote Jupyter connection executes my RemoteCommand `bash -l`, which doesn't have this problem; while **Remote-SSH** doesn't respect **RemoteCommand** in the ssh configuration

**It might be worth trying to force Jupyter to start with bash, which I don't know how.**

I am sorry I cannot set up a local environment for you to reproduce it, but I would like to explain more information to you, if it will help.

Thank you so much!

**Comment by hzfmer** [comment]
For any one reads this in similar situation, Jupyter via Remote-SSH uses the default SHELL, and even if you specify a different SHELL through `RemoteCommand` in ssh config, it's not respected. Please read the comment above to change your environment variable is needed, or change the default shell instead.

**Comment by IanMatthewHuff** [comment]
Thanks for looping back with the solution in case any one else hits this.
