### ISSUE TITLE
Variable explorer: no variables defined

### ISSUE THREAD

**Issue by Inspired1601** [microsoft/vscode-jupyter#4159]
Issue Type: <b>Bug</b>

Variable explorer always shows "No variable defined", no matter how many cells did I run or how many variables did I create in every cell. 
Yesterday variable explorer worked correctly, but today it shows only "No variable defined".
I tried to create new Jupyter Notebook, to restart VS Code, to reboot my PC - nothing changed.

Extension version: 2020.11.399280825
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.94GB (4.83GB free)|
|Process Argv|--crash-reporter-id b0a3d91a-b073-470a-8715-c873fe3c9feb|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Inspired1601** [comment]
UPD: variable explorer breaks down after I create dictionary in any cell. 
Steps to reproduce:
1. Open Variable explorer
2. Write "x = 'hello'" in a cell.
3. Run this cell: variable 'x' appears in Variable explorer.
4. Then create another cell and write "di = {'0': 1}. Run this cell.
5. Now Variable explorer freezes and even if you modify you 'x' variable, nothing changes.

**Comment by Inspired1601** [comment]
[http://joxi.ru/82Q94KOs9q87k2] (screenshot)

**Comment by IanMatthewHuff** [comment]
@Inspired1601 Currently looking into this. I don't repro this with the current bits from main that I have:
![image](https://user-images.githubusercontent.com/812783/101546104-275bc700-395d-11eb-9d25-97c5113397a4.png)

However when I pull our currently released public version of the extension I do see the issue here. Looks like this might be cleaned up in our upcoming release. Let me do one more quick check to verify.

**Comment by IanMatthewHuff** [comment]
@Inspired1601 Yes, this is fixed in our upcoming release bits. Sorry about the issue.
