### ISSUE TITLE
Test running conda python kernel

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4162]
We need to ensure we do not regress, hence add tests

**Comment by rchiodo** [comment]
Probably want this in multiple tests.

- VS code tests
- Functional tests

**Comment by rchiodo** [comment]
Maybe have switching kernels as part of the tests. Not sure it's necessary though. Conda kernels instead of straight python kernels is probably a good enough test (or maybe run some of the tests with regular kernel and some with conda)

**Comment by DonJayamanne** [comment]
We have support for conda kernels on CI today.
The raeson the python specific tests were disabled is because the python extension was not able to detect & actiavte the conda environments on CI.

**Comment by IanMatthewHuff** [comment]
Validate. Conda test existing and running.
