### ISSUE TITLE
Test switching conda kernels on CI

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4163]
To ensure we do not regress

**Comment by rchiodo** [comment]
Adding a native test to verify kernel switching

**Comment by rchiodo** [comment]
Already have one for interactive window.

**Comment by IanMatthewHuff** [comment]
@rchiodo Does this test exist? In the PR it looks like it was disabled on vscode upstream. Not seeing it in the code currently.

**Comment by rchiodo** [comment]
Sorry I removed it on a recent submission.

It was in here:
https://github.com/microsoft/vscode-jupyter/commit/233454316f3dbed6d336a4bfb5e81a6c8f541f48#diff-407846ad077861133760b3073c6dffee75297a69f158c447eb3e9a39fb9ee22f

**Comment by rchiodo** [comment]
You should be able to add that back once Peng's change goes through.

**Comment by IanMatthewHuff** [comment]
Sounds good. I'll just move to upstream for now.

**Comment by joyceerhl** [comment]
Validated: https://github.com/microsoft/vscode-jupyter/runs/1780254622?check_suite_focus=true#step:29:8917
