### ISSUE TITLE
ANSI/VT100 escape sequences aren't rendered properly

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-jupyter#4174]
## Environment data

-   VS Code version: 1.52-insiders
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.399280825
-   Python Extension version (available under the Extensions sidebar): N/A
-   OS (Windows | Mac | Linux distro) and version: Win10
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

"Done!" should be green.

## Actual behaviour

![image](https://user-images.githubusercontent.com/2644648/101556665-3dbf4e00-3970-11eb-92e7-8aa2ccb648ca.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Install .NET Interactive kernels
2. Open this notebook:

```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": "\r\n<div>\r\n    <div id='dotnet-interactive-this-cell-88188.fd528a8447a84b009c2f638f12c99c47' style='display: none'>\r\n        The below script needs to be able to find the current output cell; this is an easy method to get it.\r\n    </div>\r\n    <script type='text/javascript'>\r\n// ensure `require` is available globally\r\nif (typeof require !== typeof Function || typeof require.config !== typeof Function) {\r\n    let require_script = document.createElement('script');\r\n    require_script.setAttribute('src', 'https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js');\r\n    require_script.setAttribute('type', 'text/javascript');\r\n    require_script.onload = function () {\r\n        loadDotnetInteractiveApi();\r\n    };\r\n\r\n    document.getElementsByTagName('head')[0].appendChild(require_script);\r\n}\r\nelse {\r\n    loadDotnetInteractiveApi();\r\n}\r\n\r\nasync function probeAddresses(probingAddresses) {\r\n    function timeout(ms, promise) {\r\n        return new Promise(function (resolve, reject) {\r\n            setTimeout(function () {\r\n                reject(new Error('timeout'))\r\n            }, ms)\r\n            promise.then(resolve, reject)\r\n        })\r\n    }\r\n\r\n    if (Array.isArray(probingAddresses)) {\r\n        for (let i = 0; i < probingAddresses.length; i++) {\r\n\r\n            let rootUrl = probingAddresses[i];\r\n\r\n            if (!rootUrl.endsWith('/')) {\r\n                rootUrl = `${rootUrl}/`;\r\n            }\r\n\r\n            try {\r\n                let response = await timeout(1000, fetch(`${rootUrl}discovery`, {\r\n                    method: 'POST',\r\n                    cache: 'no-cache',\r\n                    mode: 'cors',\r\n                    timeout: 1000,\r\n                    headers: {\r\n                        'Content-Type': 'text/plain'\r\n                    },\r\n                    body: probingAddresses[i]\r\n                }));\r\n\r\n                if (response.status == 200) {\r\n                    return rootUrl;\r\n                }\r\n            }\r\n            catch (e) { }\r\n        }\r\n    }\r\n}\r\n\r\nfunction loadDotnetInteractiveApi() {\r\n    probeAddresses([\"http://100.112.236.39:1002/\", \"http://127.0.0.1:1002/\"])\r\n        .then((root) => {\r\n            // use probing to find host url and api resources\r\n            // load interactive helpers and language services\r\n            let dotnet_require = require.config({\r\n                context: '88188.fd528a8447a84b009c2f638f12c99c47',\r\n                paths: {\r\n                    'dotnet-interactive': `${root}resources`\r\n                }\r\n            }) || require;\r\n            if (!window.dotnet_require) {\r\n                window.dotnet_require = dotnet_require;\r\n            }\r\n        \r\n            dotnet_require([\r\n                    'dotnet-interactive/dotnet-interactive'\r\n                ],\r\n                function (dotnet) {\r\n                    dotnet.init(window);\r\n                },\r\n                function (error) {\r\n                    console.log(error);\r\n                }\r\n            );\r\n        })\r\n        .catch(error => {console.log(error);});\r\n    }\r\n    </script>\r\n</div>"
     },
     "metadata": {
      "transient": {
       "display_id": "4a1ae2b7-2ff4-42da-9d7b-5727c36de68e"
      }
     },
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[92masdf\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "Write-Host \"asdf\" -ForegroundColor Green"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".NET (PowerShell)",
   "name": ".net-powershell"
  },
  "language_info": {
   "file_extension": ".ps1",
   "mimetype": "text/x-powershell",
   "name": "PowerShell",
   "pygments_lexer": "powershell",
   "version": "7.0"
  },
  "orig_nbformat": 2
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by IanMatthewHuff** [comment]
@TylerLeonhardt Thanks for reporting this. I'll check into this. Any chance you could just attach the ipynb to a comment here? Formatting is a bit off in the post above.

**Comment by TylerLeonhardt** [comment]
there you go!
[notebook.zip](https://github.com/microsoft/vscode-jupyter/files/5662913/notebook.zip)

**Comment by DonJayamanne** [comment]
I believe this is an issue with the VSCode API, they don't seem to support terminal escape characters.
Also raised here https://github.com/microsoft/vscode/issues/107424
Today we handle some of them manually, might be something to bring up with VSC.

**Comment by IanMatthewHuff** [comment]
Yeah, I confirm the same issue. As @DonJayamanne mentioned it's likely going to be an upstream issue for this fix, but I needed an excuse to set up the .net interactive kernel on this machine anyways, so I checked it out. 

![image](https://user-images.githubusercontent.com/812783/101663464-938f0700-39ff-11eb-8b16-dd6584ef9c35.png)

**Comment by TylerLeonhardt** [comment]
@IanMatthewHuff @DonJayamanne here's the discussion about this in vscode:
https://github.com/microsoft/vscode/issues/98202

Looks like you need to leverage the new `CellOutputKind`.

**Comment by DonJayamanne** [comment]
Aaah yes that's right. I thought we do use rich output type, might need to have another look into this issue.

**Comment by DonJayamanne** [comment]
Yes we are doing the right thing here, looks like an issue in VS Code.
We're creating a Rich output with mimetype `text/plain`

**Comment by DonJayamanne** [comment]
Looks like the fix for this https://github.com/microsoft/vscode/issues/98202 has stopped working.

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/112178
