### ISSUE TITLE
Rewrite pr.yml, insiders.yml, and release.yml to reuse javascript code instead of duping code

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4175]
Following the directions here:

https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action#writing-the-action-code

You can create a 'local' action as long as the js can find all of its dependencies. We should be able to install other 'actions' as npm modules and reference them from a js script.

**Comment by rchiodo** [comment]
Going to do this first before refactoring other tests as it will make it a lot easier to write new actions.

**Comment by joyceerhl** [comment]
I think you went with moving everything into one yml and not reusing JS code like the title of this issue says. Validating based on that (please reopen if I'm mistaken). Nice work on this 😊
