### ISSUE TITLE
Interactive Window should honor color tokens provided by native notebook editor

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#4176]
As it currently stands colors used by the interactive window (either script or IW proper) are based on color tokens available prior to native notebooks. Native notebooks has a set of color tokens that would be more appropriate to use. 

We could wait until we re-code the IW to use the native notebook API, but in the meantime could we just do a simple replacement of color tokens? 

Here's some examples:
![image](https://user-images.githubusercontent.com/11685408/101834007-9b79a480-3aee-11eb-8b7b-2c7ab39b567f.png)

**Comment by rchiodo** [comment]
Do you have an example? Color tokens we use are pulled from the theme on disk. Not sure what color tokens you're saying don't match. Interactive window should match tokens in a python file.
