### ISSUE TITLE
OpenCV not importing in notebook

### ISSUE THREAD

**Issue by borisneal** [microsoft/vscode-jupyter#4180]
Issue Type: <b>Bug</b>

1. Build OpenCV 4.4.0 (Windows 10) with Python
2. Create a notebook with "import cv2" command

Error: DLL load failed while importing cv2. The specified module could not be found.

This works fine when running jupyter notebook from the Anaconda prompt.

Extension version: 2020.11.399280825
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (33.03GB free)|
|Process Argv|--crash-reporter-id 14e1089a-d031-4d6d-9983-10220fd5065e|
|Screen Reader|no|
|VM|40%|
</details>

**Comment by rchiodo** [comment]
Thanks for the bug. 

Can you do the following?

- Set this setting: `"jupyter.logging.level":"debug"` in your settings.json
- Repro the problem
- Upload the contents of the 'Jupyter' output tab

My suspicion is that we're not setting the path correctly or the kernel you're using isn't the one you wanted.

**Comment by borisneal** [comment]
It's probably the path, which is now manifesting in a different place in the notebook (the import issue is magically fixed). How do I find the extension logging output? I don't see a "Jupyter" tab. Do I need a dev edition of VSCode?

**Comment by rchiodo** [comment]
> Do I need a dev edition of VSCode?

No it should be here:

![image](https://user-images.githubusercontent.com/19672699/101687692-b6311800-3a1f-11eb-9a45-136b3eef313c.png)

**Comment by borisneal** [comment]
The issue no longer reros. 😄 Let's close for now.
