### ISSUE TITLE
Jupyter notebook is not launching   - spawn cmd ENOENT

### ISSUE THREAD

**Issue by narendraprasath** [microsoft/vscode-jupyter#4181]
Issue Type: <b>Bug</b>

Installed VS code VSCodeUserSetup-x64-1.51.1 version on Windows 10.
I have installed python extension then it is showing an below error:
**spawn cmd ENOENT**

Not able to use jupyter notebook

Extension version: 2020.11.399280825
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (9.41GB free)|
|Process Argv|--crash-reporter-id 33294b11-f111-4df8-8709-d1f82008f86b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rchiodo** [comment]
Thanks for the bug.

Can you do the following?

- Set `"jupyter.logging.level":"debug"` in your settings.json
- Repro your problem
- Upload the contents of the 'Jupyter' output tab 

Thanks

**Comment by narendraprasath** [comment]
Thanks for your response.

I installed VS code on user privilege and I faced this issue. Now, I tried installed VS code on admin user and the issue has fixed.

I don't the real cause of the issue. But this worked for the mentioned issue.
