### ISSUE TITLE
restart jupyter kernel only works through clicking restart button in interactive window

### ISSUE THREAD

**Issue by StefanBloemheuvel** [microsoft/vscode-jupyter#4182]
## Environment data

VS Code version: 1.51.1
Extension version (available under the Extensions sidebar): 2020.11.371526539
Jupyter Extension version (available under the Extensions sidebar): v2020.11.399280825
OS (Windows | Mac | Linux distro) and version: Mac Pro, mac Catalina 10.15.7
Python and/or Anaconda version: 3.7
Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda virtual environment
Jupyter server running: Local

## Wrong behaviour

The jupyter restart kernel keyboard shortcut does not work, even when triggering it with the command pallete. It does work when i click the restart icon in the interactive window. How could i trigger the restart kernel again with a keyboard shortcut? I already resetted all my keyboard shortcuts so that could not be the issue.

**Comment by rchiodo** [comment]
Thanks for the bug.

Restarting the kernel in the interactive window requires the window has focus.

**Comment by StefanBloemheuvel** [comment]
Hi @rchiodo 

Thanks for you reply, but i actually mean the keyboard shortcut when coding in the .py file, like in a jupyter cell with #%%. Also, every time when i restart the kernel it asks as an option: yes, and don't ask again. But when i click the yes don't ask again it just keep asking me that question when I restart the kernel later on, it does not remember my choice.

**Comment by rchiodo** [comment]
> But when i click the yes don't ask again it just keep asking me that question when I restart the kernel later on, it does not remember my choice.

That should have unchecked this setting here:

![image](https://user-images.githubusercontent.com/19672699/101675296-7ada1d80-3a0e-11eb-9814-0d291aedebb9.png)

If it didn't you should be able to uncheck it yourself.

Keyboard shortcut while a python file has focus does make sense. We should change the code to make that possible too.

**Comment by StefanBloemheuvel** [comment]
> That should have unchecked this setting here

Where could i find that setting?

> Keyboard shortcut while a python file has focus does make sense. We should change the code to make that possible too.

Thanks for considering it, it was a functionality that I used a lot when it was possible with the keyboard shortcuts originally falling under the datascience name instead of the jupyter name.

**Comment by rchiodo** [comment]
> Where could i find that setting?

Command Palette: Open Settings UI and type 'kernel restart' should find it.

**Comment by StefanBloemheuvel** [comment]
>Command Palette: Open Settings UI and type 'kernel restart' should find it.

Thanks i found it, however, I get the error that i am not able to write into users settings. my user settings are:

```
{
    "terminal.integrated.inheritEnv": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "window.zoomLevel": 0,
    "editor.minimap.enabled": false,
    "python.showStartPage": false,
    "python.languageServer": "Microsoft",
    "workbench.colorTheme": "Cobalt2",
    "editor.fontSize": 15,
    "python.autoComplete.extraPaths": [
        '/Users/name/anaconda3/envs'
    ],
    "jupyter.sendSelectionToInteractiveWindow": true
}
```

**Comment by rchiodo** [comment]
> I get the error that i am not able to write into users settings.

Not sure why you can't write to that file, but that's the reason why the message keeps popping up.

**Comment by StefanBloemheuvel** [comment]
I will look online to find a solution, thanks for your help!

**Comment by joyceerhl** [comment]
Closing in favor of https://github.com/microsoft/vscode-jupyter/issues/6996
