### ISSUE TITLE
Variables in seperate window

### ISSUE THREAD

**Issue by ShlomiRex** [microsoft/vscode-jupyter#4183]
![image](https://user-images.githubusercontent.com/17744127/101632854-5022a180-39db-11eb-8fe6-6dbcde7d0954.png)

If I could only move the variables to vscode window, so I can look at it vertically instead of horizontally it could improve the experience.

**Comment by rchiodo** [comment]
Thanks for the suggestion. We'll discuss in our weekly triage.

**Comment by greazer** [comment]
@ShlomiRex, we will be addressing this as part of our switch to native notebook support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987.
