### ISSUE TITLE
Dash board to track activation times of extension

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4187]
Ensure this doesn't get worse over time for users.
Else we wait for users to complain & by then its possible the start time has degraded by 10 fold (i.e. we need to know how bad things get)

**Comment by joyceerhl** [comment]
Added a page for this here https://msit.powerbi.com/groups/bf1a0bdc-23b0-4199-a210-563a5f3b92df/reports/d5d2e008-9f12-4909-92c0-8afb922f9717/ReportSection86034010521e3e143907 It looks like our activation times actually went down in the latest version of the extension.
