### ISSUE TITLE
Use code cove yml file to configure reports for PRs

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4188]
We can configure code cov to generate reports in a PR so we can see how the updated code effects the coverage.
* Whether it reduces or increases coverage
* Looks at the coverage for the new/modified code

I.e. add something like the following
![Screen Shot 2020-12-09 at 10 33 17](https://user-images.githubusercontent.com/1948812/101671959-15842d80-3a0a-11eb-88b9-5b437aeae99a.png)

The current report in the PRs doesn't really mean anything, we have two of them, one with 80% & the other report with 75% (if anything this seems confusing).

**Suggestion**
* Deprecate current github action reports
* Use code cov reports in PRs
* Ensure subsequent updates to PR, results in a single report (override previous report in PR with the new output)

https://docs.codecov.io/docs/pull-request-comments

**Comment by DonJayamanne** [comment]
![Uploading Screen Shot 2020-12-09 at 10.33.17.png…]()

**Comment by rchiodo** [comment]
I believe the root cause of the problem for this is that our dynamic nyc instrumentation happens on the js files and codecov needs the files to match the source repository (.ts files).

Looking to see if instrumentation can use a sourcemap or not.

**Comment by DonJayamanne** [comment]
More reason to move to jest...

**Comment by rchiodo** [comment]
I haven't found something in jest that allows us to instrument outside of running? So that wouldn't work for the vscode tests as far as I can tell. Meaning to use jest, we have to run our tests with it.

**Comment by DonJayamanne** [comment]
Aaah yes, thats true

**Comment by DonJayamanne** [comment]
Either way, still dislike our current clunky approach, not that i have any alternatives.

**Comment by DonJayamanne** [comment]
Nope, I'm wrong, it is possible I'm doing this today see here https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/test/extension/testRunner.ts
& it supports coverage as well for tests that run in VS Code.
Jest rocks

**Comment by joyceerhl** [comment]
Validated https://github.com/microsoft/vscode-jupyter/pull/4342#issuecomment-758270915
