### ISSUE TITLE
Review release process

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4190]
* Do we want to create releases in GitHub
	* label/tag commit & include the change log & the like into github release
	* We have the code but not enabled.
* Do we want to automate uploading VSIX to marketplace?
	* We have the code, but not enabled.
	* Review process & document this if we're going with this.
* Other changes?
	* Thoughts/suggestions for changes

**Comment by greazer** [comment]
Let's just meet to discuss.
