### ISSUE TITLE
Ensure we can start kernels even when we have kernels with the same name

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4191]
This needs to be done as we have reverted thi s change in the release and change is in main

**Comment by DonJayamanne** [comment]
* Ensure duplicates are not displayed in kernel picker
* If we have an interpreter XYZ and we have a python kernel inside that, then we should only display the interpreter or the kernel (not both) as both are identical
	* use command `python -m ipykernel install --sys-prefix --name duplicate
	* Now edit the kernelspec.json to give it some custom variables in the json.
* After we add env in the kernelspec.json then confirm we have both kernels

**Comment by rchiodo** [comment]
I still have dupes in the kernel picker:

![image](https://user-images.githubusercontent.com/19672699/105779817-0149b080-5f24-11eb-843c-6c951ea3d922.png)

However they're not dupes? I can select them and they will show the correct sys paths. So I think this is working as designed.

Validated.
