### ISSUE TITLE
Kernel is restarted when reconnecting to a remote Jupyter server

### ISSUE THREAD

**Issue by diricxbart** [microsoft/vscode-jupyter#4199]
## Environment data

-   VS Code version: 1.51.1
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.411183155
-   Python Extension version (available under the Extensions sidebar): v2020.11.371526539
-   OS (Windows | Mac | Linux distro) and version: Debian
-   Python and/or Anaconda version: 3.6.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Remote

## Expected behaviour

When a notebook is connected to a remote Jupyter server, a long-running cell is executed and if VSCode is closed and we re-open the notebook, then I would expect that the notebook has kept running. This is also the behavior in vanilla Jupyter notebooks, if you refresh/restart your browser and open the same url, then you can just keep working, the kernel continued its job... I would also expect that the cell output has updated, since the kernel kept running.

## Actual behaviour

The kernel has restarted and we see the last saved state of the notebook.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Have VSCode connected to a remote running Docker container via the "Remote - Containers" plugin (v0.148.1)
2. Inside VSCode open a terminal and launch a new screen session (when 'screen' is not installed in the Docker container, you'll first need to install it)
3. Press 'Enter' to skip the screen intro page
4. Now launch a Jupyter server, which will result in a URL with token to allow connecting to this Jupyter server (e.g. http://127.0.0.1:8888/?token=1e34e199...). Copy this to the clipboard.
5. Detach from the screen session by going to screen command mode (CTRL + A) and hitting 'd'
6. Open the VSCode command pallette (CTRL + SHIFT + P) and select "Jupyter: Specify local or remote Jupyter server for connections"
7. Select 'Existing'
8. Now enter the URL in the presented field (note that for me CTRL+V didn't work for pasting here (another bug?), but right-click > Paste did work), press 'Enter' to confirm
9. Next a pop-up will show-up to reload, click the 'Reload' button. After VSCode has reloaded, we see that the Jupyter notebook is now using the remote Jupyter server.
10. Enter the following in a Jupyter notebook cell as a means of test:
```
import time
for i in range(1000):
    print(i)
    time.sleep(10)
```
11. Run the cell, you should see an incrementing number being printed every 10 seconds.
12 Exit VSCode. Note that the Jupyter server remains running and the kernel should (could) have been kept alive
13. Start VSCode and connect to the remote running docker container
--> I was hoping that the cell would have resumed executions, but this was not the case.

**Comment by DonJayamanne** [comment]
> was hoping that the cell would have resumed executions, but this was not the case.
> would also expect that the cell output has updated, since the kernel kept running.

Thanks for replying this issue.
Unfortunately this isn't something sweet sorry today. To my knowledge this isn't supported in Jupyter notebooks nor labs.

**Comment by DonJayamanne** [comment]
> Note that the Jupyter server remains running and the kernel should (could) have been kept alive

Note, the kernel is still kept alive and we do not kill this.
Is you reconnect after some time (after execution had completed), you can connect to that instance and state is available.

Eg run a cell with the code `x = 1234`. After you close and reconnect, you can still see the value of the variable `x`.

If you are asking for the state of the print statements to be recovered (out generated while the notebook was closed, then add mentioned earlier that's not supported).

We are tracking such issues against this issue here https://github.com/microsoft/vscode-jupyter/issues/300

**Comment by DonJayamanne** [comment]
If there are  other issues then please do let me know as I'm closing this on favor of https://github.com/microsoft/vscode-jupyter/issues/300.
Happy to reopen this issue to address other problems.
