### ISSUE TITLE
User snippets in interactive window input

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-jupyter#4200]
Hope I didn't overlook any duplicates.

Would be cool if the interactive window input suggested user snippet completions.

```json
{
  "import numpy": {
    "prefix": "inp",
    "body": [
      "import numpy as np"
    ],
    "description": "import numpy"
  }
}
```

## Expected Behavior

Typing `inp`, I'd expect the first suggestion to be `import numpy`. In a Python file it is. In the IW input, I get other stuff.

![no-completions](https://user-images.githubusercontent.com/30958850/101808467-a6e0c600-3b16-11eb-8690-c9c98461d228.png)

**Comment by DonJayamanne** [comment]
Thanks for the suggestion we'll discuss this.

**Comment by maciejkos** [comment]
@DonJayamanne Could you please share what is the single source of truth as to what vscode-jupyter supports? 

For example, I am trying to understand:
- if there is no support for snippets at all or just for third-party snippets? There exists `C:\Users\Christine\AppData\Roaming\Code\User\snippets\jupyter.json`, but editing it doesn't seem to make any difference.
- if any extensions are supported?
- if highlighting of matching brackets is implemented? It was implemented in the past #2430, but I can't get it to work on my machine. I would be happy to file an issue if I knew whether the developers know about it or not.

**Comment by DonJayamanne** [comment]
@maciejkos Currently snippets are not supported in the interactive window input.
This is because that input is not a real VS Code text editor, hence most of the VS Code functionality is not supported in that input box.

**Comment by maciejkos** [comment]
Thanks, @DonJayamanne. Are all of the supported features listed in the [Working with Jupyter Notebooks in Visual Studio Code doc](https://code.visualstudio.com/docs/python/jupyter-support)?

**Comment by DonJayamanne** [comment]
Unfortunately, no

**Comment by janosh** [comment]
@DonJayamanne Is #1231 the issue that tracks refactoring the interactive window to use VS Code internals?

**Comment by DonJayamanne** [comment]
> at tracks refactoring the interactive window to use VS Code internals?

Its the issue that tracks using VS Code Internals for notebooks (i.e. use the new VS Code Notebook UI instead of our webview based UI).

**Comment by joyceerhl** [comment]
This is resolved in the [preview interactive window](https://code.visualstudio.com/updates/v1_58#_jupyter-interactive-window), which features improved VS Code workbench integration and is currently the default in VS Code Insiders. Please let us know if it works for you and give us any feedback you have about the new experience 😊 If you find any bugs or have concerns, please file a new issue at https://github.com/microsoft/vscode-jupyter/issues so we can fix it. Thank you! 

![recording (3)](https://user-images.githubusercontent.com/30305945/126431824-f78b16dd-3dca-4826-a172-dd7d1f7e1420.gif)
