### ISSUE TITLE
I can't save the files

### ISSUE THREAD

**Issue by andreeaman** [microsoft/vscode-jupyter#4202]
Issue Type: <b>Bug</b>

all files appear with * and I can't save them
would you please help me out with this problem
Great thanks
Andreea

Extension version: 2020.12.411183155
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (6.65GB free)|
|Process Argv|--crash-reporter-id a8a9447a-6e21-4021-9fb5-8da8e57891fd|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DonJayamanne** [comment]
Thanks for reporting this issue.
Please could you me a bit more specific about what you mean by `all files`.
Are you using `Python files` or notebooks or other?
If they are standard files such as Python or the like, then please report this issue in the VS Code repo. If its an issue with Notebooks, then we'll look into that.

A screenshot would help here.

**Comment by greazer** [comment]
@andreeaman, can you try opting into the Custom Editor experiment? This will likely be the default for all users in the near future.

Add this to your user settings. 
```
    "jupyter.experiments.optInto": [
        "CustomEditor"
    ],
```
