### ISSUE TITLE
Gather: External buttons not appearing when using 'Create New Blank Jupyter Notebook' command

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-jupyter#4206]
Steps:
1. Open a folder in VS code (don't open files, the python, jupyter and gather extensions should not activate)
1. Use the 'Create New Blank Jupyter Notebook' command
1. (If you open a python file, the button appears)

Actual Result:
The external buttons don't appear

Expected Result:
External buttons appear

This doesn't happen if the extensions were already activated.

**Comment by joyceerhl** [comment]
Validated 
![image](https://user-images.githubusercontent.com/30305945/104352280-5369eb00-54bb-11eb-8d35-93a465c37b0d.png)
