### ISSUE TITLE
Image bug when outputting to interactive window

### ISSUE THREAD

**Issue by cjh9** [microsoft/vscode-jupyter#4223]
## Environment data

-   VS Code version: 1.51.1
-   Extension version (available under the Extensions sidebar): v2020.11.371526539
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda):  3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A

Run this to create a black square and output it into the interactive window:

```
import numpy as np
import PIL

i = 255*np.zeros([500,500])
i = i.astype(np.uint8)
im = PIL.Image.fromarray(i)
im
```

Problem:
1. It will not be the actual size 500x500 pixels large, but smaller. 
2. There is a white line in the bottom that is there on all pictures. See screenshot:

I tried to do the same in a jupyter notebook in the browser, and it outputs the correct size, with no line at the bottom.
![Screenshot from 2020-12-12 23-18-30](https://user-images.githubusercontent.com/18718330/101996192-75abf580-3cd0-11eb-81ea-deebc866fa70.png)

**Comment by DavidKutu** [comment]
Thanks for the issue @cjh9. 
I can also repro your issue with both the interactive window and the webview notebook. It doesn't happen on the native notebook, which means this is an issue on how we handle the outputs in the webviews.

(You can try the native notebooks if you use our extension in VS Code insiders.)

Quick note:
I did a small change to your imports to get the code to run.
```
import numpy as np
from PIL import Image

i = 255*np.zeros([500,500])
i = i.astype(np.uint8)
im = Image.fromarray(i)
im
```

**Comment by greazer** [comment]
@cjh9, thanks for logging this issue! As David mentioned, we are moving to a new implementation of notebooks in VS Code. This new experience is currently active if you use VS Code Insiders. Therefore, we will not be addressing this problem in the current implementation.
