### ISSUE TITLE
Unstable notebook behaviour after output trimmed

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode-jupyter#4225]
I'm training an ML model in a ipynb. After a while the output is truncated, i.e.

> Output was trimmed for performance reasons.
> To see the full output set the setting "jupyter.textOutputLimit" to 0.
 
After this point vscode opened a second copy of the same notebook, and won't allow me to save either of them (it looks like it crashed, tried to recover the document and is now sitting with both the current and previous copies open at the same time).

The actual server is still running the training job in the background, I can see the progress via my mlflow tracking server. It looks like the front end lost connection with the jupyter backend. 

![image](https://user-images.githubusercontent.com/5028974/102065915-4242a580-3e4d-11eb-9175-f8d38c9d5cf5.png)

Also, there are continuous errors in the Jupyter output console, not sure they're related though.

> > ~/.pyenv/versions/pre-training/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> Error 2020-12-14 20:34:23: Jupyter Kernel Spec not found for a local connection
> > ~/.pyenv/versions/pre-training/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> Started kernel Python 3.9.1 64-bit ('pre-training')
> > ~/.pyenv/versions/pre-training/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> > ~/.pyenv/versions/pre-training/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> Error 2020-12-14 20:34:24: [TypeError: Cannot read property 'themes' of undefined
> 	at y.findTokenColors (/home/david/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:762290)
> 	at processTicksAndRejections (internal/process/task_queues.js:94:5)
> 	at async y.applyThemeData (/home/david/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:763801)
> 	at async f.handleMonacoThemeRequest (/home/david/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:531328)]
> Error 2020-12-14 20:34:24: [TypeError: Cannot read property 'themes' of undefined
> 	at y.findTokenColors (/home/david/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:762290)
> 	at processTicksAndRejections (internal/process/task_queues.js:94:5)
> 	at async y.applyThemeData (/home/david/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:763801)
> 	at async f.handleCssRequest (/home/david/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:530965)]
>

**Comment by DavidKutu** [comment]
Thanks for the issue @david-waterworth.
Could you share the notebook that causes the issue? If not, maybe a sample notebook that does? I'm not able to reproduce it by just printing big outputs.

And another question, does the issue reproduce if you set the setting "jupyter.textOutputLimit" to 0?
