### ISSUE TITLE
Plotly no renderer error in Jupyter notebook

### ISSUE THREAD

**Issue by coobas** [microsoft/vscode-jupyter#4227]
Issue Type: <b>Bug</b>

Hi, I have this issue with Plotly inside Jupyter notebooks. Any plotly image output yields `No renderer could be found for MIME type: application/vnd.plotly.v1+json`. E.g., in a new Jupyter notebook, this cell runs into this problem:
```python
import plotly.graph_objects as go
go.Figure(data=go.Bar(y=[2, 3, 1]))
```
(Btw, plotly works fine in interactive windows)

Extension version: 2020.12.414227025
VS Code version: Code - Insiders 1.53.0-insider (96b426ef1da0f0a51ce9ef1931cd1fd2322547e4, 2020-12-14T05:49:45.285Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.86GB free)|
|Process Argv|. --crash-reporter-id fb99fee3-070d-490a-bbeb-7313929b8cf0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30208930
wsl2promptcf:30219163
vstry914:30230485
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139
core-portspanelcf:30233468

```

</details>

**Comment by DavidKutu** [comment]
Thank you for the issue @coobas.

Unfortunately I wasn't able to repro your issue, the graph renders for me on both stable and insiders.
Could you try and see if the issue also happens to you on stable?
Could you please check if you have a 'Notebook Renderers' extension installed?

Thanks in advance.

**Comment by coobas** [comment]
Thanks David for your prompt reply. In stable, Plotly works fine in noteboks.

In insiders, I have the new notebook GUI, could that be the reason?
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/4492625/102197281-3690c680-3ec1-11eb-8a03-856a5d83ed7d.png">

Btw, I don't see Notebook Renderers (https://github.com/microsoft/vscode-notebook-renderers) as a separate extension, seems to be part of [Jupyter extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter). Isn't it?

**Comment by DavidKutu** [comment]
I just found that we are already following this issue here: https://github.com/microsoft/vscode-jupyter/issues/3936

The new native notebooks are just a preview, there is still some stuff we need to iron out before releasing on stable. So in the mean time please use stable if possible.

I'll close this issue as a duplicate, please follow the other issue for a resolution. And feel free to ping me if you have any other question.

**Comment by coobas** [comment]
Thank you! I will follow #3393 ;)
