### ISSUE TITLE
The code cannot be executed in the manually created Jupyter Notebook.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#4232]
## Environment data
![image](https://user-images.githubusercontent.com/59192491/102188702-994d8680-3ef0-11eb-99d9-590a52ca06b2.png)

## Steps to reproduce:
1. Open a folder
2. Click "New file" to create a new file named test.ipynb
3. Add print('bar') to that cell
4. Enter “Ctrl+Alt+Enter”

## Expected behaviour
The code is executed without any error.

## Actual behaviour
The code cannot be executed.
![image](https://user-images.githubusercontent.com/59192491/102191218-12021200-3ef4-11eb-9d5e-5a162d2f95b8.png)

If I use Ctrl+Shift+P to create an blank Jupyter Notebook
![image](https://user-images.githubusercontent.com/59192491/102191060-dc5d2900-3ef3-11eb-855a-d7f468514197.png)
The code can be executed.
![image](https://user-images.githubusercontent.com/59192491/102191178-044c8c80-3ef4-11eb-8328-4a2cfd2e40ff.png)

**Comment by IanMatthewHuff** [comment]
@linette-zyy Thanks for filing this. In a way this is expected, when you create a new file in vscode it has the .ipynb extension, but that would not actually be a valid ipynb as it would be missing the format and metadata needed. But at the same time, this is something that we might expect customers to do, so we should see if there is a way for us to support this experience better.

**Comment by greazer** [comment]
This should be working now.
