### ISSUE TITLE
Determine how to ship Jupyter Keybindings for Native Notebooks

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#4233]
## Environment data
![image](https://user-images.githubusercontent.com/59192491/102198116-f94a2a00-3efc-11eb-91fb-092eb373c0d6.png)

## Steps to reproduce

1. Run cell and export as Jupyter notebook named 'tester.ipynb' in interactive window.
2. Open tester.ipynb in editor
3. Hit o on a code cell with output and verify that outputs disappear.
4. Hit z and verify a deleted cell reappears
5. Hit l on a code cell and verify line numbers appear

## Expected behaviour
Hit o on a code cell with output and verify that outputs disappear.
Hit z and verify a deleted cell reappears
Hit l on a code cell and verify line numbers appear

## Actual behaviour
Hit o on a code cell with output and that outputs did not disappear.
Hit z and a deleted cell did not reappear
Hit l with no line numbers appear
![image](https://user-images.githubusercontent.com/59192491/102198382-475f2d80-3efd-11eb-9f76-ddbc19a7467c.png)

**Comment by linette-zyy** [comment]
This issue is not reproduce on stable build.

**Comment by IanMatthewHuff** [comment]
Thanks. Some of these might just be differences with the new notebook UI on insiders. Will look into it.

**Comment by DonJayamanne** [comment]
# Suggestion from VS Code https://github.com/microsoft/vscode/issues/106679

**Comment by DonJayamanne** [comment]
## Solution as proposed by VS Code

**Option 1 (preferred by VS Code): Create a new extension to ship keybindings**
* New extension will be dependency of Jupyter extension
* Category should not contain `keymap` (see previous comment in VS Code repo for details)
* All key bindings should go into this
* This way, if users don't want default Jupyter key bindings, they can disable this new extension & (optionally install another extension if someone creates it).
* Also easy for users to discover & disable this key bindings (if they don't want jupyter key bindings)
**TODO:** Validate whether we can have a dependency on an extension and have that extension disabled and continue using th main extension (e.g. user disables keymap extension & continues to use Jupyter).
We can easily validate this today by disabling Jupyter exension & validating whetehr Python extension works.
If it works, then we can go with this approach, **else we need to notify VS Code** 

**Option 2: Add all key bindings in the Juypyter extension with when clause to disable it**
* In the when clause make a reference to a config setting (we alraedy do this today()
* If that setting is set, then such key bindings will not be enabled.
* This allows users to disable jupyter style keybindings.
* Not VSCodes preferred option (as key bindings are generally separate extensions).

**Comment by DonJayamanne** [comment]
We decided to go with option 2.

**Comment by DonJayamanne** [comment]
Shortcuts to be added are in #4376

**Comment by DonJayamanne** [comment]
Closing this issue as we have a solution.
