### ISSUE TITLE
Nested outputs are frozen in place in change handlers

### ISSUE THREAD

**Issue by Ivorforce** [microsoft/vscode-jupyter#4234]
Issue Type: <b>Bug</b>

Create a Jupyter Notebook with the following code:

```python
import ipywidgets.widgets as iwidgets
from IPython.display import display, clear_output
import random

output = iwidgets.Output()
display(output)

def render(*args):
    r = random.random()

    with output:
        clear_output()
        print(r, "Outside")

        out = iwidgets.Output()
        with out:
            print(r, "Inside")
        display(out)

render()

button = iwidgets.Button(description="Redraw")
button.on_click(render)
display(button)
```

Notice how upon first draw, all sub-outputs will freeze the output in place.
![ezgif-6-642c8427758b](https://user-images.githubusercontent.com/2308167/102211745-5aa9d300-3ed4-11eb-962b-124a3db73e35.gif)

Also notice how this isn't reproducible in native jupyterlab:
![ezgif-6-5ecf2b2e7491](https://user-images.githubusercontent.com/2308167/102211941-abb9c700-3ed4-11eb-9b05-9bc2aa85a813.gif)

It is notable that this boils down to not being able to remove or add new `Output` objects to the outer `Output` object during the button `on_change` calls. The Output that is continuing to be displayed is, in fact, the old one, and the newly created one is ignored.

Finally, this issue is _only_ applicable to Output objects. Any other widget (I've tested) works fine.

Extension version: 2020.12.414227025
VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 20.1.0
Remote OS version: Linux x64 4.15.0-122-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 6, 9|
|Memory (System)|16.00GB (0.51GB free)|
|Process Argv|--crash-reporter-id cbbc61b5-28c9-4771-9425-0768a82e57a6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ablalab|
|OS|Linux x64 4.15.0-122-generic|
|CPUs|Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (36 x 1726)|
|Memory (System)|376.59GB (36.77GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
vstry244cf:30236574
pythonvsdeb440:30233463
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30236630
vsjup459cf:30229594

```

</details>

**Comment by IanMatthewHuff** [comment]
@Ivorforce Thanks for the clear repro on this. I confirm the same thing that you are seeing. We'll look into it (note: lots of the team is out of the holidays so response might be a bit slower)

**Comment by DonJayamanne** [comment]
Fixed with https://github.com/microsoft/vscode-jupyter/pull/10502
