### ISSUE TITLE
"Extension Host Terminated Unexpectedly"

### ISSUE THREAD

**Issue by bazeroni** [microsoft/vscode-jupyter#4235]
Issue Type: <b>Bug</b>

### Expected
1. start vscode
2. open folder
3. python initializes extensions
4. choose conda as interpreter
### Actual
1. start vscode
2. open folder
3. "python extension loading"
4. "Extension Host Terminated Unexpectedly"
### Extensions
- Anaconda Extension Pack
- Atom One Dark Theme
- Jupyter
- Python
- YAML
### Versions
- vscode (user) 1.52.0 November
- conda 2020.11
- python 3.8.5
### Note
I ran the new 'Help: Start Extension Bisect' feature and the process nailed down Jupyter to be the culprit.

Extension version: 2020.12.414227025
VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (24.38GB free)|
|Process Argv|--crash-reporter-id 5af5876d-9748-495a-b06a-ff7794e6e934|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30233463
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30236630
vsjup459cf:30229594

```

</details>

**Comment by IanMatthewHuff** [comment]
@bazeroni Not fully sure if this is caused by the Jupyter Extension or the Python Extension as the two of those interoperate with each other. Can you turn jupyter.logging.level to 'debug' in the vscode settings and then repro the issue? Can see what's in the "jupyter" tab of the output window to see if anything is going on in the logging.

**Comment by bazeroni** [comment]
@IanMatthewHuff sorry I realized that the guys over at [vscode-python](https://github.com/microsoft/vscode-python/issues/14977) found out that it indeed had to do with the main python extension and it has since been patched as of this morning. Let me know if you still would like logs.

**Comment by IanMatthewHuff** [comment]
@bazeroni Nope it's all good, no logs needed. Python and Jupyter extension teams are related teams here at Microsoft, so if they are on it, then it's not an issue for Jupyter here.

**Comment by bazeroni** [comment]
@IanMatthewHuff Ok cool, thank you!
