### ISSUE TITLE
Notebook is NOT saved

### ISSUE THREAD

**Issue by momt99** [microsoft/vscode-jupyter#4238]
It's been the fifth or sixth time that everything is saved, autosave is on with an interval of 10 seconds, no sign or caution about the unsaved notebook, and I close vscode. The next time I open it, none of them are saved and lots of works and codes are LOST.

## Environment data

-   VS Code version: 1.51.1
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.372831992
-   Python Extension version (available under the Extensions sidebar): v2020.11.371526539
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

**Comment by IanMatthewHuff** [comment]
@momt99 Very sorry about this issue. In the past I know that we had a few issues with autosave, but I believed that those had been all ironed out. What exact auto save settings do you have? Also, might be good to pull the newest version of the extension to make sure that you are up to date with the latest fixes.

**Comment by momt99** [comment]
At first, my autosave preference was on focus change, which didn't work with jupyter notebooks, then I changed it to after delay with a delay of `10000`.
Yeah, I updated it the day after and I hope that the bug is fixed.
Also, I want to ask to add support to keep the unsaved changes in vscode temporary storage like other unsaved files, so these kinds of problems will not happen if the notebook is not saved.

**Comment by IanMatthewHuff** [comment]
@momt99 If you are interested let me point you at this:
https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/

The basics is that previously VS Code didn't have any support for a notebook like UI. So our extension had to add this UI by making a custom UI with a webview, which is basically just a webpage that VS Code lets you host internally. This worked, but it was a lot of effort to make that webpage look and feel like a part of VS Code and there were many issues still with things like theming, autosaving and respecting editor settings. 

VS Code is now adding a Notebook UI to VS Code which we are moving over to using. It's actually the default now in VS Code - Insiders with our extension. In this implementation VS Code itself is handling the saving, so it should resolve any autosave issues that are happening. There are still a few features missing in this new implementation, so it's not fully rolled out to stable yet, but it's our plan moving forward.

**Comment by momt99** [comment]
Thanks for the information.
Hope to see the new notebook UI soon. Looks interesting.
