### ISSUE TITLE
Conda Activation Issue (w/keras package?) 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#4248]
## Steps to Reproduce
1. Install keras on env using following command in anaconda terminal: conda install -c conda-forge keras
2. Restart VS Code 
3. Try working in a notebook with that env. 

## Actual Behavior
VS Code completely breaks, errors thrown, cannot use notebook at all 

Uninstalling the keras package from the env and restarting VS Code fixed the issue

![image](https://user-images.githubusercontent.com/19276747/102521698-1b9d8e00-404a-11eb-8613-d052d2d346f7.png)

[Conda Activation Error Logs2.txt](https://github.com/microsoft/vscode-jupyter/files/5711094/Conda.Activation.Error.Logs2.txt)
[Conda Activation Error Logs.txt](https://github.com/microsoft/vscode-jupyter/files/5711095/Conda.Activation.Error.Logs.txt)

**Comment by IanMatthewHuff** [comment]
A bit more info here from Claudia and I debugging. 

Some packages can change the base activation of conda particularly the PATH variable (all the issues that we've seen for this are on windows). This can cause errors on startup like so:
https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#the-system-cannot-find-the-path-specified-on-windows

When we try to start up a kernel we watch stderr. When C:/Users/clregio/Anaconda3/Scripts/activate is run the 'System cannot find the path specified' errors show up in stderr and we exit out on any errors in stderr. The funky thing is that some of these errors seem to be benign and you can still then activate your environment and run after seeing them. But we exit out before that and you can't use any conda environments as it's the base activate having issues.

**Comment by rchiodo** [comment]
Validated. I can install keras and still have it work.
