### ISSUE TITLE
Version miss match

### ISSUE THREAD

**Issue by apurvTri123** [microsoft/vscode-jupyter#4249]
Install python 3.8
Install Python extension by Microsoft for VS Code
Install Python 3.6

The Jupyter extension still gives an error for 3.8 ipynb files even after changing the source interpreter

**Comment by IanMatthewHuff** [comment]
Hey @apurvTri123 can you give a bit more info about your scenario? I can't quite tell what you are doing here. Do you mean that with a notebook file selecting the 3.8 python as your kernel causes an error? Notebook files can select their own interpreter to use and it might not reflect the selection of the Python interpreter in the bottom left.

**Comment by greazer** [comment]
Issues labeled with "Info needed" are closed if we do not receive more information from the issue author in 2 weeks. If you are the issue author and you still are running into this problem, please reactivate with additional information.
