### ISSUE TITLE
Cannot connect to local server, silent failure

### ISSUE THREAD

**Issue by ivirshup** [microsoft/vscode-jupyter#4252]
## Environment data

-   VS Code version: 1.53.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: macOS 10.15.7 
-   Python and/or Anaconda version: 3.8.6 (but also there are conda envs)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): At the moment, N/A
-   Jupyter server running: Local | N/A

## Expected behaviour

* Shift-Command-P > Select local or remote jupyter server
* Put in url
* Restart vscode after prompt
* Run notebooks through that server

## Actual behaviour

No execution, no errors. I can get notebook execution if I have vscode start a server. I thought it might be like #3916, but I'm just not getting any output or anything.

Kernels are being picked up correctly, but I'm not sure if that's cached. Notebook server is definitely running:

```sh
$ jupyter notebook list        
Currently running servers:
http://localhost:8888/?token=577f9fb28942695a39fb6a0a1d814d5b5d447634a266517f :: /Users/isaac
```

Plus I've got a notebook open in safari. I don't see any notifications in the notebook log about vscode.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

* Shift-Command-P > Select local or remote jupyter server
* Put in url
* Restart vscode after prompt
* Run notebooks through that server

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'NativeNotebookEditor'
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
Error 2020-12-18 19:44:58: SessionManager cannot enumerate kernelspecs. Returning default.
```

</p>
</details>

**Comment by claudiaregio** [comment]
@ivirshup do you have a workspace open? Could be related to #4037

**Comment by ivirshup** [comment]
Yes, I have tried this with workspaces open. It does ask me to restart vscode after changing the url, so I suppose there would be some time in this process during which a workspace isn't open.

**Comment by IanMatthewHuff** [comment]
@ivirshup Given that last line in the jupyter log it looks like it did pick up a remote URL, but failed to enumerate the kernel specs on the server. If you have access to the environment used to start up that server can you try running `jupyter kernelspec list` and see if you get kernels listed without any errors? That might be the step that's failing here, and I have seen issues before with machines that can't list the kernelspecs correctly.

**Comment by greazer** [comment]
Issues labeled with "Info needed" are closed if we do not receive more information from the issue author in 2 weeks. If you are the issue author and you still are running into this problem, please reactivate with additional information.
