### ISSUE TITLE
"python.dataScience" is being used in a wiki page

### ISSUE THREAD

**Issue by marckassay** [microsoft/vscode-jupyter#4253]
I believe `"python.dataScience"` setting is deprecated. This wiki [page](https://github.com/microsoft/vscode-jupyter/wiki/IPyWidget-Support-in-VS-Code-Python) references it.

**Comment by joyceerhl** [comment]
Great catch, thank you! Should be fixed now :)

**Comment by IanMatthewHuff** [comment]
Validated (unpkg was also spelled incorrectly, so fixed that as well). Thanks for the catch on this.
