### ISSUE TITLE
Native notebooks: Whitespace at start of output suppressed

### ISSUE THREAD

**Issue by gvanrossum** [microsoft/vscode-jupyter#4254]
## Environment data

```
Version: 1.53.0-insider (system setup)
Commit: c927a8015b9e26bd454d6e293bb0384aa1975d06
Date: 2020-12-18T05:27:48.567Z
Electron: 11.0.5
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.19042
```
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.416706931
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): None
-   Jupyter server running: (No idea)

## Expected behavior

```
print("  ho")
print("  ho")
print("  ho")
```
Expected output:
```
  ho
  ho
  ho
```
## Actual behavior

The spaces at the start of the first line are not rendered:
```
ho
  ho
  ho
```

## Steps to reproduce:

![image](https://user-images.githubusercontent.com/2894642/102701371-3834f400-420b-11eb-820b-89f60c89d5cf.png)

**Comment by joyceerhl** [comment]
Hi @gvanrossum thanks for reporting a bug! I can repro this behavior:

![image](https://user-images.githubusercontent.com/30305945/102704155-81497000-422c-11eb-9911-114e0bec88d5.png)

The leading whitespace is being stripped when processing the output that comes back from the kernel here:

https://github.com/microsoft/vscode-jupyter/blob/6c215b106c5612b6c33299a69e43f1376aef12d9/src/client/datascience/notebook/helpers/helpers.ts#L595

I'm not sure why we were trimming whitespace before (@DonJayamanne might know), but the fix would be to change that line to:

```ts
 ['text/plain']: concatMultilineString(output.text) 
```

With that change:
![image](https://user-images.githubusercontent.com/30305945/102704139-58c17600-422c-11eb-8cf5-63d650a30c97.png)

**Comment by IanMatthewHuff** [comment]
@joyceerhl If I recall correctly we had this issue with the old notebooks and fixed it. I remember customers having issues with output formatting of tables due to this. Think we might have fixed it in old notebooks, but not in the native notebooks code that branched out, downsides of us still having implementation separation with old / native notebooks.

**Comment by IanMatthewHuff** [comment]
Validated.
![image](https://user-images.githubusercontent.com/812783/104359301-56b5a480-54c4-11eb-89d9-746e814b810d.png)
