### ISSUE TITLE
unable to connect to julia kernel in ssh remote

### ISSUE THREAD

**Issue by woodwm** [microsoft/vscode-jupyter#4255]
## Environment data

-   VS Code version: 1.52.1
-   Jupyter Extension version (available under the Extensions sidebar): 2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): 2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04
-   Python and/or Anaconda version: Miniconda with python 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Jupyter server running: Local | Remote | N/A: Local

## Expected behaviour

run julia code in jupyter notebook using ssh remote

Julia version: 1.5.3

I already installed `IJulia` in the remote ubuntu 20.04 connected via `Remote - SSH` and installed the julia kernel by runing `notebook()` in julia which downloaded `miniconda` and installed all necessary python packages including `jupyter`.

It can connect to the julia kernel in my local windows machine, but failed in the remote ubuntu machine.

## Actual behaviour

"Timed out waiting to get a heartbeat from kernel process"

**Comment by joyceerhl** [comment]
Hi @woodwm, could I ask for some more info from you? Would you mind turning on debug logging in your VSCode settings on your remote ubuntu machine and providing us with detailed error logs? You can do this by opening the command palette and typing 

![image](https://user-images.githubusercontent.com/30305945/102704370-675d5c80-422f-11eb-87fb-af9c05dc69fd.png)

then add the following setting to your settings.json

![image](https://user-images.githubusercontent.com/30305945/102704360-51e83280-422f-11eb-975f-98ff4ac51ca0.png)

and repeat your bug repro steps above. Then copy and paste the contents of the Jupyter output panel at the bottom of VSCode (pictured below).

![image](https://user-images.githubusercontent.com/30305945/102704379-8825b200-422f-11eb-8443-efd9f45c88c6.png)

Many thanks!

**Comment by woodwm** [comment]
Hi, I find it is because of my mistake. I was running a jupyter notebook cloned from github. It has project environment defined by `Project.toml` and `Manifest.toml`. I missed some packages and cause trouble to lauch `IJulia.jl` successfully. There are two ways: either run `Pkg.instantiate` to install all the packages in the project or temporarily remove the project.toml file and vs code will be able to connect to the julia kernel.
