### ISSUE TITLE
jupyter.alwaysScrollOnNewCell doesn't work on user input loop

### ISSUE THREAD

**Issue by AidanVIII** [microsoft/vscode-jupyter#4257]
## Environment data

-   VS Code version: 1.52.0 (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.18363
-   Python and/or Anaconda version: 3.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Editor scrolls to the last printed statement after input.

## Actual behaviour

Editor didn't scroll.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. ~~Set `"editor.scrollBeyondLastLine": "true"`~~
Set `"jupyter.alwaysScrollOnNewCell": "true"` 
2. Run a python file asking for input in the python interactive window:

```python
def inputLoop():
    for i in range(30):
        print('line')
    userInput = input("Input: ")
    inputLoop()

inputLoop()
```

Unsure where this should get tracked, opened [/vscode/issues/113189](https://github.com/microsoft/vscode/issues/113189)

**Comment by joyceerhl** [comment]
Hi @AidanVIII, the interactive window does not read the `editor.scrollBeyondLastLine` setting. Provided that you reload VSCode after you add `"jupyter.alwaysScrollOnNewCell": true`, the interactive window does appear to scroll for me. Would you mind providing a screenshot or GIF of the behavior you're seeing please? Thank you!

**Comment by AidanVIII** [comment]
My bad, `editor.scrollBeyondLastLine` was unrelated, edited the OP to match.
The problem happens when I enter an input as an answer to the `userInput = input("Input: ")` line & hit [ Enter ]:

1. Just ran the interactive window from contextual menu:

![1](https://user-images.githubusercontent.com/20214995/102746059-c620f400-435d-11eb-94e4-f78fd95b722e.png)

2. Entering input:

![2](https://user-images.githubusercontent.com/20214995/102746093-d2a54c80-435d-11eb-8d7c-02ed880a1c18.png)

3. After I hit [ Enter ], the scrollbar thumb updates in size, but scroll doesn't happen:

![3](https://user-images.githubusercontent.com/20214995/102746210-139d6100-435e-11eb-972e-fbc013578e15.png)

**Comment by IanMatthewHuff** [comment]
@AidanVIII I just took a look and I repro this as well. Not fully sure what is going on here yet, but looks like the focus being on the input box might be causing something that prevents our scroll code from working. We'll look into this (note: Lots of the team is out over the holidays here so probably no progress for a little while).

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed with new native support for editing notebooks starting with v1.59 of VS Code. If this issue continues to occur in the latest build of VS Code, please reopen or enter a new issue.
