### ISSUE TITLE
fail in applying a color theme to notebook in ssh remote

### ISSUE THREAD

**Issue by woodwm** [microsoft/vscode-jupyter#4259]
## Environment data

-   VS Code version: 1.52.1
-   Jupyter Extension version (available under the Extensions sidebar): 2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): 2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04
-   Python and/or Anaconda version: Miniconda with python 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Jupyter server running: Local | Remote | N/A: Local

## Expected behaviour

run jupyter in my local windows computer

![image](https://user-images.githubusercontent.com/13971199/102785938-6b13ef00-43a7-11eb-85e0-fa797651baca.png)

## Actual behaviour

run jupyter in the remote ubuntu using ssh remote

![image](https://user-images.githubusercontent.com/13971199/102786007-85e66380-43a7-11eb-8fcb-ac3f1fb726e1.png)

Both use "Kimbie Dark" theme. This also happens when apply other dark themes. The color of words is not right.

**Comment by claudiaregio** [comment]
hi @woodwm, does this happen with all themes?

**Comment by woodwm** [comment]
Hi, yes. Typical problems are the color and style (italic) of words and the background color in the notebook.

**Comment by IanMatthewHuff** [comment]
@woodwm This is currently a consequence of our notebook UI being implemented as a webview. It is looking for the theme files on the remote machine when they are only installed on the local machine.

We're not going to fix this in our current UI implementation as we are moving over to a new UI supported by VS Code. 

https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/

You can check out this new UI by using VS Code - Insiders with the Jupyter extension, though some features are not fully supported as it's in Preview. I'm going to close this issue as we won't be fixing it for the old UI and the new UI should clear it up.
