### ISSUE TITLE
Native Notebooks - Remove Duplicate Command

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#426]
VS Code surfacing "Notebook: Select Notebook Kernel" command
We are surfacing "Jupyter: Select a Kernel" command

Unless there is a use case for having both that I am not seeing, hide our select a kernel command. 
![image](https://user-images.githubusercontent.com/19276747/98604282-3c7b0280-2298-11eb-9994-5aa28ce1a4d2.png)

**Comment by rchiodo** [comment]
Validated
