### ISSUE TITLE
Native notebook is not loading. Just preview is working

### ISSUE THREAD

**Issue by giammi56** [microsoft/vscode-jupyter#4263]
Version: 1.53.0-insider
Commit: 4a875e23d20b64504a818834f3fa4c40adb8d480
Date: 2020-12-21T12:39:40.504Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Linux x64 5.4.0-58-generic
Jupyter Extension  v2020.12.414227025
Python Extension v2021.1.436783525-dev
Type of virtual environment used: virtualenv anaconda3
Jupyter server running: Local

## Expected behaviour
open a file in Jupyter Notebook

## Actual behaviour
it loads forever
files can be opened just with the preview version

## Steps to reproduce:

![Peek 2020-12-22 17-52](https://user-images.githubusercontent.com/11757284/102913165-adf4c600-447e-11eb-93f0-d60324c92f12.gif)

NOTES: the issue is present since at least a month. I haven´t reported since now, but it became important for me to have the native notebook.

**Comment by claudiaregio** [comment]
HI @giammi56, this functionality is currently not available. Please continue using the "preview" version or just click on notebooks normally in the file explorer

**Comment by giammi56** [comment]
@claudiaregio thank you. what do you mean with "on notebooks normally in the file explorer" ?

**Comment by claudiaregio** [comment]
If you have the file explorer open and click on a notebook it should automatically open a notebook, no right click necessary. 
The default in VS Code insiders is now Native Notebooks! Let me know if that doesn't work for you

![File Explorer Open](https://user-images.githubusercontent.com/19276747/102920242-3f444800-443f-11eb-82ad-b3a611f1c230.gif)
