### ISSUE TITLE
Unexpected token and undefined variables problems and warnings

### ISSUE THREAD

**Issue by roma-glushko** [microsoft/vscode-jupyter#4265]
## Environment data

-   VS Code version: 1.53.0-insider(4a875e23d20b64504a818834f3fa4c40adb8d480)
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.429416775-dev
-   OS (Windows | Mac | Linux distro) and version: MacOS Catalina 10.15.5 (19F101)
-   Python and/or Anaconda version: 3.9.1 64bit
-   Type of virtual environment used: venv (poetry env use python3)
-   Jupyter server running: Local

## Expected behaviour

I expect list of problems and warnings reflect the actual code issues in notebook cells and when I click on particular problem it lands me to the correct place that should be changed.

## Actual behaviour

I'm getting a lot of errors and warnings like this:

<img width="1497" alt="Screenshot 2020-12-22 at 22 00 16" src="https://user-images.githubusercontent.com/9402690/102928324-2b313280-44a1-11eb-8b7c-2f405d29fc48.png">

All of the notices don't seem to be relevant. They lead to wrong cells and it's quite hard to understand what triggers these errors and warnings:

![2020-12-22_22-02-42 (1)-min](https://user-images.githubusercontent.com/9402690/102930066-6f720200-44a4-11eb-96db-69e603e21899.gif)

In the same time, I can actually execute notebook without any errors.

## Steps to reproduce:

1. Notebook shown in the gif can be found here: https://github.com/roma-glushko/kaggle-wine-quality
2. Open project in VC and wait until it indexed
3. Try to run cells of the notebook 

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
> ~/Projects/kaggle/kaggle-wine-quality/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/Projects/kaggle/kaggle-wine-quality/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Started kernel Python 3
> ~/Projects/kaggle/kaggle-wine-quality/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2020-12-22 12:20:16: Jupyter Kernel Spec not found for a local connection
> ~/Projects/kaggle/kaggle-wine-quality/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Started kernel Python 3.9.1 64-bit ('.venv')
> ~/Projects/kaggle/kaggle-wine-quality/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/Projects/kaggle/kaggle-wine-quality/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/Projects/kaggle/kaggle-wine-quality/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/Projects/kaggle/kaggle-wine-quality/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/Projects/kaggle/kaggle-wine-quality/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
```

</p>
</details>

**Comment by claudiaregio** [comment]
Hi @roma-glushko, are you using Pylance? 

If you hit Command + Shift + P and select "Preferences: Open Settings (JSON)" what is the value of your setting "python.languageServer": "________"

**Comment by claudiaregio** [comment]
I cloned the repo and did not get any of the surfaced errors with Pylance.

**Comment by roma-glushko** [comment]
@claudiaregio indeed, pylance was missed in my insider version of VC:

<img width="933" alt="Screenshot 2020-12-23 at 10 16 49" src="https://user-images.githubusercontent.com/9402690/102975335-919d6b80-4508-11eb-84ef-b93b9525f447.png">

Thank you for the help 🙌

**Comment by roma-glushko** [comment]
Actually after installing Pylance (version v2020.12.2), the issue is back to stay after some time 😌 Here is my current JSON config:

```json
{
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter-notebook",
            "filenamePattern": "*.ipynb"
        }
    ],
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.insidersChannel": "weekly",
    "python.languageServer": "Pylance",
    "workbench.colorTheme": "Default Light+",
    "editor.fontSize": 16,
    "files.autoSave": "afterDelay",
    "jupyter.askForKernelRestart": false
}
```

I had a section where Lasso model where initied and evaluated. I removed those cells but errors are still referring to those removed cells. In addition, errors keep irrelevantly pointing various cells that doesn't seem to have issues:

![2020-12-23_17-05-23 (1)](https://user-images.githubusercontent.com/9402690/103010858-a5b18f00-4541-11eb-87f7-3c71c082d0ea.gif)

**Comment by IanMatthewHuff** [comment]
@roma-glushko I'm trying this myself, and I'm also not reproing the issue. I do get one pylance error on the %%time magic command, but that is currently expected as magic commands are not valid python. There are also a few warnings on possibly unbound variables, which I believe are legit warnings, though I've not dug in more on them. 
![image](https://user-images.githubusercontent.com/812783/103030180-16d84e80-4510-11eb-9727-2a5e28b4cddc.png)

I have a couple of things to try here.

- I don't believe this is the issue, but try commenting out that %%time command. For language server support with a notebook it basically creates a single python file from the cells. Having that invalid python in the notebook might be messing with the language server
- From a notebook there is a VS Code command palette command Jupyter: Export to Python Script. That command should convert your notebook to a script file. Can you try that and see if you get the same errors (with commenting out %%time) in the .py file? Would help isolate if this is a Language Server issue or a notebook issue

Thanks.

**Comment by roma-glushko** [comment]
Hey @IanMatthewHuff thank you for replay 🙏 

I actually helped to remove `%%time` directive from the cell:

<img width="1791" alt="Screenshot 2020-12-23 at 21 37 13" src="https://user-images.githubusercontent.com/9402690/103031771-259e2000-4567-11eb-8f6c-6fb65c09257e.png">

All errors are gone and only warnings are left. Interesting if I return `%%time` back, then I could not reproduce these errors again 😌  The same goes for exported python file. It doesn't have any error even when I add `%%time` back in place.

**Comment by IanMatthewHuff** [comment]
@roma-glushko Glad that it helped!
