### ISSUE TITLE
Jupyter Server address bar is too large

### ISSUE THREAD

**Issue by Ivorforce** [microsoft/vscode-jupyter#4268]
Here's a very basic problem I have with VSCode Jupyter right now: With large addresses, the address bar is far too large.

If I am in full screen with file browser hidden it's ok:

<img width="1439" alt="Bildschirmfoto 2020-12-24 um 11 30 11" src="https://user-images.githubusercontent.com/2308167/103082877-646dbd80-45db-11eb-8e76-79e6ba348d2a.png">

But once it is there with a reasonable size it's far too large:
<img width="1440" alt="Bildschirmfoto 2020-12-24 um 11 30 54" src="https://user-images.githubusercontent.com/2308167/103082901-7d766e80-45db-11eb-8f55-7d7fb1457bf0.png">

I can't see the python state anymore, and the buttons start a second row.

If possible, I'd like the address bar to collapse down to a minimum size first (max layout priority). A simpler solution might be giving it a reasonable max width — if I'm that interested in the current server (I'm not), i can always hover over the address or click it.

**Comment by joyceerhl** [comment]
Thanks for the suggestion @Ivorforce! Most of our team is on vacation now, so we'll discuss this proposal at our next team triage.

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
