### ISSUE TITLE
add "Connect to Colab/Deepnote"

### ISSUE THREAD

**Issue by llxlr** [microsoft/vscode-jupyter#4269]
So  we can use Colab or Deepnote more conveniently

**Comment by joyceerhl** [comment]
Thanks for the suggestion @llxlr! Most of our team is on vacation now, so we'll discuss this proposal at our next team triage.

**Comment by DonJayamanne** [comment]
Closing in favour of https://github.com/microsoft/vscode-jupyter/issues/12268
