### ISSUE TITLE
Cell results won't match what is shown in the editor

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-jupyter#427]
1. Have autosave enabled
1. Create a new notebook
1. Paste this code:
```
from time import sleep
dict2 = {'a> <a href="bobs"/>':[1, 2, 3], '<b':[4, 5, 6]}
df6 = pd.DataFrame.from_dict(dict2)
print(df6)
```

1. Edit the cell
1. Run the cell

Result:
result won't match the contents

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
