### ISSUE TITLE
Cannot import so module

### ISSUE THREAD

**Issue by muser840** [microsoft/vscode-jupyter#4270]
Cannot import compiled SO module `fmodule` in the notebook. In the old VS-CODE Jupyter notebook extension it works just fine, therefore I think it is an issue with this new jupyter extension.

```
import sys
sys.path.append('.')
import fmodule
```

<summary>
ModuleNotFoundError: No module named 'fmodule'
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-bb0155c26dc3> in <module>
----> 1 import fmodule
ModuleNotFoundError: No module named 'fmodule'
</summary>

**Comment by joyceerhl** [comment]
Hey @muser840 sorry for the trouble here. Just to clarify are you saying that you encountered this problem after upgrading to a newer version of the Jupyter extension? If so, which version did this work on, and which version did this stop working on? Thanks!

**Comment by muser840** [comment]
> Hey @muser840 sorry for the trouble here. Just to clarify are you saying that you encountered this problem after upgrading to a newer version of the Jupyter extension? If so, which version did this work on, and which version did this stop working on? Thanks!

Sorry if I wasn't clear... It's a bit different what I was trying to say. I have in parallel VS Code with Python extension that can open Jupyter notebooks (v2020.12.424452561) and VS Code Insiders with vscode-jupyter (v2020.12.414227025). 

I placed shared object module `fmodule.cpython-38-x86_64-linux-gnu.so` into the folder, then open vscode/vscode-insiders in the same folder. With old vscode Python extension it imports just fine, while with vscode-jupyter under VS Code Insiders it can't find module. Therefore I conclude that something is wrong with "vscode-jupyter" extension.

**Comment by AlexanderZeilmann** [comment]
I think I have the same problem. Here is a minimal example to reproduce it:

1. Create a new folder and two files inside of it ```SomeModule.py``` and ```notebook.ipynb```.
2. ```SomeModule.py``` contains only the line ```test = 42```.
3. ```notebook.ipynb``` contains three cells:
    1. ```import numpy```
    2. ```from SomeModule import test```
    3. ```test * test```

Opening the notebook with Jupyter and executing the cells works without any problems:
```numpy``` is imported as well as ```test``` and we can multiply ```test``` to itself.

However, if we open the notebook in ```vscode-jupyter``` (which is connected to the same Jupyter Server):
1. ```numpy``` is imported without any problems.
2. Executing the second cell raises the error
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-2f8b85fb3bb7> in <module>
----> 1 from SomeModule import test

ModuleNotFoundError: No module named 'SomeModule'
```

I suspect this is only a minor oversight from my side (do I have to put something special in a ```__init__.py``` file?),
however, I am wondering why  ```Jupyter``` and ```vscode-jupyter``` behave differently.

**Comment by rchiodo** [comment]
@AlexanderZeilmann I'm not reproing your issue? Can you try upgrading to our latest bits. It was likely a problem with the current working directory for the kernel when started. We did fix an issue related to this in the last release.

If it still repros can you verify:
- You're not using a remote jupyter URI (you're letting us start the kernel)
- What does pwd show? It should show the current directory of the notebook.

@muser840 can you try again as well?

**Comment by muser840** [comment]
> @muser840 can you try again as well?

Now seems all is okay. Thanks!

**Comment by AlexanderZeilmann** [comment]
@rchiodo I can sadly still reproduce the issue.
I am on version v2021.2.576440691 of the extension which should be the current version.

> You're not using a remote jupyter URI (you're letting us start the kernel)

I am using a jupyter URI for some server on which jupyter is running.
Letting ```vscode-jupyter``` start the kernel on localhost is only working very rarely, but I think this is a different problem.
Because of the higher computing power of the server, I want to use the jupyter installed on the server

> What does pwd show? It should show the current directory of the notebook.

It prints the location of my home directory on the server. This is not where the files are located.
My files are stored locally on my laptop.
I can change the directory to some other location on the server, however, I don't know how to change it to my local machine.

I'm not even sure if the way I am trying to use this extension (local files, remote jupyter) is the intended way.

-----

I just tried something different:
When I connect to the server using the [remote ssh extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) and then open a jupyter notebook using ```vscode-jupyter```, everything is working.

**Comment by rchiodo** [comment]
> It prints the location of my home directory on the server. This is not where the files are located.
My files are stored locally on my laptop.
I can change the directory to some other location on the server, however, I don't know how to change it to my local machine.

If you're using remote, it cannot load any of the local files. We do not copy files to the remote server nor do we control the working directory of the remote server.

Your best bet (as you found) is to use Remote SSH instead. That will then run the server and the files on the remote machine. Of course you then have to put your files on the remote machine.

**Comment by AlexanderZeilmann** [comment]
> If you're using remote, it cannot load any of the local files. We do not copy files to the remote server nor do we control the working directory of the remote server.

Ahh, I understand, thank you for the clarification 😃 
I don't know, why I assumed that I can use local files and remote kernel 🙈
