### ISSUE TITLE
Python interactive stuck on start

### ISSUE THREAD

**Issue by sigbjorngrini** [microsoft/vscode-jupyter#4271]
## Environment data

-   VS Code version: Insiders build 1.51 daily and weekly channel
-   Extension version (available under the Extensions sidebar): Python v2020.11.311084263-dev
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

## Expected behaviour

Shift-Enter starts Python interactive and runs code

## Actual behaviour

Shift-Enter starts Python interactive and gets stuck on Executing cell

## Steps to reproduce:

1. Make a .py file
2. Shift-Enter on the first line to start Python interactive

It does not happen for stable VS Code.

**Comment by fredshu** [comment]
@joyceerhl , many thanks for your nice reply. While searching on how to enable Jupyter logging, I noticed that my Python extension was old and the new VSCode started working nicely after updating all extensions. Thanks again!
