### ISSUE TITLE
Add spell checking support to notebook cells

### ISSUE THREAD

**Issue by roma-glushko** [microsoft/vscode-jupyter#4275]
It's always nice to have spell checking whenever you write code comments or markup text.

At this point, it's possible to miss typos in the cells as they are not highlighted for a writer:

![2020-12-31_10-46-56 (1)](https://user-images.githubusercontent.com/9402690/103402389-aa83cd80-4b55-11eb-8466-322f7761fe04.gif)

**Comment by joyceerhl** [comment]
Thanks for the suggestion @roma-glushko! We'll discuss this at our next team meeting.

**Comment by DonJayamanne** [comment]
This is something VS Code would have to support. I would have expected existing spell checker extensions to work as the new notebook as its a first class editor.

**Comment by greazer** [comment]
This should already be working in VS Code. Let's discuss with them.

**Comment by DonJayamanne** [comment]
The Spell Check extension doesn't support Notebook API (it doesn't detect opening of notebook documents).
Probably need to submit a PR when the API is stable, until then leaving this open as this is a widely used extension.

**Comment by DonJayamanne** [comment]
Closing this issue, as there's nothing we need to do in Jupyter extenion for this.
If it still doesn't work, please file an issue on VS Code for this.
