### ISSUE TITLE
switching tabs causes interactive window jump around

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#4276]
```
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
Jupyter: v2020.12.414227025
```

This happens when 
- have two vscode windows opened
- have two tabs in one of the window
- switch from one tab to another
- click a output in the interactive window

![demo](https://user-images.githubusercontent.com/33796896/103432130-a9c85700-4ba8-11eb-8c57-162e20422414.gif)

**Comment by joyceerhl** [comment]
Unfortunately I can't reproduce this locally with two files in group 1 and the IW in group 2 (with dataframes containing dummy data). My version info:
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
Jupyter extension: v2020.12.414227

@StevenLi-DS, would you mind providing the exact ipynb you used in the GIF above so I can make sure it's not something specific to the code you ran?

**Comment by StevenLi-DS** [comment]
@joyceerhl Sorry for the late reply. I observed this issue in multiple files, so I don't think it is file-related. As you can see, there are only two lines of code, and then I just ran `df.head()` a couple of times so I can have a long results.

**Comment by StevenLi-DS** [comment]
I'm still experiencing this issue, and it happens when you use Interactive window and markdown preview at the same time.  If you have your editor on `.md` on one side while the interactive window on another side. Sometime, click or selecting text in the interactive window will make the cells jump around.
