### ISSUE TITLE
Automatic tab switching whilst running .ipynb file 

### ISSUE THREAD

**Issue by hannibal90** [microsoft/vscode-jupyter#4278]
## Environment data

-   VS Code version: 1.52.1
-   Python Extension version (available under the Extensions sidebar): v2020.12.424452561
-   OS: Linux Ubuntu 20.04
-   Python and/or Anaconda version: 3.8
-   Jupyter server running: Remote

## Behaviour

When running all the cells in a long .ipynb file, if I switch to edit a file in another VS Code tab, every time a cell gets completed I automatically get switched from my new tab back to the running .ipynb tab.

**Comment by joyceerhl** [comment]
Hi @hannibal90, we intentionally added this, but it sounds like this is not desirable for you. Would you prefer a way to turn off the tab switching behavior?

**Comment by hannibal90** [comment]
Hi, yes a way to disable this would be great.  I have lost count of the number of times I have overwritten code as a result of this auto tab switching. Thanks

**Comment by greazer** [comment]
Dupe of #1425

**Comment by greazer** [comment]
Also a dupe of #1260
