### ISSUE TITLE
The insider version has the markdown cell not respecting the breakline

### ISSUE THREAD

**Issue by andreamoro** [microsoft/vscode-jupyter#4280]
## Environment data

-   VS Code version: Insider
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   OS (Windows | Mac | Linux distro) and version: Mac OS X
-   Python and/or Anaconda version: Python 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): none
-   Jupyter server running: Local | Remote | local

## Expected behaviour

A <br> should render the text on the cell with the breakline as it happen in the non-insider version.

## Actual behaviour

The text ignores the breakline and is merged with the previous line creating a huge clutter.

## Steps to reproduce:

![image](https://user-images.githubusercontent.com/5256583/103485528-441dda00-4df7-11eb-9ab6-af97cec52fc9.png)
![image](https://user-images.githubusercontent.com/5256583/103485534-4a13bb00-4df7-11eb-89f6-cc363614f309.png)

**Comment by joyceerhl** [comment]
Thanks for reporting a bug @andreamoro. This is likely related to https://github.com/microsoft/vscode/issues/113351.
