### ISSUE TITLE
Notebook imports start failing after saving Notebook

### ISSUE THREAD

**Issue by myFree** [microsoft/vscode-jupyter#4281]
Issue Type: <b>Bug</b>

I am working in a Conda environment
I have selected the correct conda environment using `Python: Select Interpreter`
My settings.json has

```"python.pythonPath": "/home/bgracey/anaconda3/envs/fastai/bin/python",```

I can run my notebook successfully before I save it; however; as after the first time I click `save notebook` the notebook then starts failing on

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-a48780125025> in <module>
----> 1 import fastbook
```

If I export the notebook to a python script; I can run it directly in the terminal successfully as well. 

Please let me know if I can provide any additional information to help triage this scenario.

The notebook in question is: https://gist.github.com/myFree/0668cf700b4b173a632ab27743e0f959

Extension version: 2020.12.414227025
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.4.0-58-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 3248)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.47GB (0.35GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 5c134b14-d74a-47ed-bf9e-6446f7022df9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by joyceerhl** [comment]
Hey @myFree, what is the result of running the following code in a cell, both before and after saving the notebook?

```python
import sys
print(sys.executable)
```

**Comment by myFree** [comment]
Hi; the issue is not reoccurring today; and notebooks are continuing to run after being saved!

I'll run the suggested command if it re-occurs to try gather more info on the root cause; but for now will mark as closed.

Thank you for the prompt response and suggestion.
