### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by vishalverma116** [microsoft/vscode-jupyter#4282]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2020.12.414227025`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 1014,
		"activateCallTime": 66,
		"activateResolvedTime": 21941,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-toolsai.jupyter",
				"_lower": "ms-toolsai.jupyter"
			},
			"activationEvent": "onLanguage:python"
		}
	},
	"runtimeErrors": []
}
```

**Comment by joyceerhl** [comment]
Hi @vishalverma116, could you please open an issue with the bug report template fully filled out? https://github.com/microsoft/vscode-jupyter/issues/new?labels=bug&template=1_bug_report.md Without further information we cannot resolve your issue. Thank you!

**Comment by vishalverma116** [comment]
hi @joyceerhl , 
i apologies for being late. I reinstall the vscode now it gives this output.

Language server is set to Microsoft.
Acquiring model 'intellisense-members-lstm' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Downloading model.
Starting download of https://cdsmprodstg.blob.core.windows.net/models-prod-output/Output_15708AE89896CA5DF1690433B7A8D93D28B7_215F8B4FAB1F4663ABD624559FD205B9?sv=2018-03-28&sr=b&sig=DhkEP3943NnZqQtBK8JQb7Ljz4HNO29SIObke0X1lU8%3D&se=2021-01-10T15%3A23%3A17Z&sp=r
Download complete.
Error while activating Python: {}

**Comment by greazer** [comment]
@vishalverma116, please reopen if you are still having problems.
