### ISSUE TITLE
layout defect: in jupyter jnotebook view, local server name needs truncation

### ISSUE THREAD

**Issue by mwartell** [microsoft/vscode-jupyter#4287]
Issue Type: <b>Bug</b>

I connected to an existing jupyter server with a long URI like
http://localhost:8889/?token=a10e87772729f45acfb33c15e8fe5581878a29e93da65239

This blew the button/Trusted/Jupyter Server: header line from a proper one line to three lines high. All to show me the complete token which is uninformative. 

This is a layout issue only. Everything works fine, and widening the editor to "too wide" clears the extra blank space.

Extension version: 2020.12.424452561
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-58-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.52GB (4.26GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 414f5e79-d368-48a5-8ef6-0f1e13928101|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspyt653:30237719
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440cf:30237828
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30236629
pythonvspyt600cf:30239449
vsjup459cf:30237188

```

</details>

**Comment by DonJayamanne** [comment]
Duplicate https://github.com/microsoft/vscode-jupyter/issues/4268#issuecomment-751824615
