### ISSUE TITLE
Data Viewer of Interactive Viewer will not open numpy complex ndarrays

### ISSUE THREAD

**Issue by nheinsdorf** [microsoft/vscode-jupyter#4288]
## Environment data

-   VS Code version: 1.52.1
-   Extension version (available under the Extensions sidebar): Python 2020.12.2
-   OS and version: openSUSE Leap 15.2
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): None
-   Relevant/affected Python packages and their versions: numpy 1.17.3
-   Relevant/affected Python-related VS Code extensions and their versions: Python Extension 2020.12.2
-   Value of the `python.languageServer` setting: Pylance 

## Expected behaviour

In the variable explorer I double click on a complex ndarray and it opens in the data viewer. 

## Actual behaviour

I double click on the variable, and the data viewer window opens. A blue bar suggests that it's loading but it keeps loading and never shows the data (the array has a small size of just 20 rows times 20 columns of complex numbers). 

## Steps to reproduce:

1. in the interactive window run the following code:
```
 import numpy as np
from numpy.random import rand
arr = rand(20, 20) + 1j*rand(20, 20)
```
double click on arr inside the window's variable explorer.

**Comment by DonJayamanne** [comment]
Thanks for reporting this issue, I can replicate this at my end:
This is what I get for those interested:
![Screen Shot 2021-01-04 at 12 23 01](https://user-images.githubusercontent.com/1948812/103576209-a4f4f300-4e87-11eb-9211-5f1c8a289f3c.png)

**Comment by DonJayamanne** [comment]
We would need to check the type of the data & format it accordingly.

Not sure if we're already doing this for each an every element in the array, could have some perf issues if we were to check and format each and every element in such a way, if we're already doing this, then I guess there isn't a perf issue.

**Comment by joyceerhl** [comment]
@nheinsdorf, I'm able to open the data viewer but I get the same result as Don's screenshot above. You seem to be encountering a different problem. When you see 

> A blue bar suggests that it's loading but it keeps loading and never shows the data

Are there any error messages in the Jupyter output panel at the bottom of VSCode? Could you please turn on debug logging by setting `jupyter.logging.level: 'debug'` in your settings.json, repeat your repro steps, and provide the contents of the output panel?

![image](https://user-images.githubusercontent.com/30305945/103582989-c3f98200-4e93-11eb-8133-eae2f90543ea.png)

**Comment by nheinsdorf** [comment]
@joyceerhl I added jupyter.logging.level: 'debug' to my settings.json. But I don't see any output in the interactive window when doing anything with Jupyter. I see that you have a Jupyter instance in the terminal at the bottom of the screen, but in the dropdown menue I can only select bash. How do I get the debugging output?

**Comment by rchiodo** [comment]
This should be fixed now.

**Comment by nheinsdorf** [comment]
Great!

**Comment by int19h** [comment]
It looks like this has regressed - see https://github.com/microsoft/debugpy/issues/1213

**Comment by amunger** [comment]
We've deprecated the Jupyter data viewer and the Data Wrangler extension seems to be able to handle this in their viewer - closing
