### ISSUE TITLE
Code Completion in adjacent cells is slow/non existent

### ISSUE THREAD

**Issue by corman44** [microsoft/vscode-jupyter#4290]
Issue Type: <b>Bug</b>

Create Jupyter notebook, import requests, Shift+Enter to run and create new Cell, type "r = req" and press Ctrl+Space to attempt code completion. No Suggestions are available

Extension version: 2020.12.414227025
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-58-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz (4 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.72GB (1.83GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id a5791e2f-e43f-45ab-84a7-8e7a11f52bda|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440cf:30237828
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629
vsjup459cf:30237188

```

</details>

**Comment by joyceerhl** [comment]
Hi @corman44! Which Python language server are you currently using? You can check this value in your settings.json:
```
  "python.languageServer"
```

**Comment by corman44** [comment]
Hi @joyceerhl Jedi is defined. Is this the default for VS Code on Ubuntu 20.04? I have not edited this setting
`"python.languageServer": "Jedi"`

**Comment by joyceerhl** [comment]
That is the default, but if you switch it to Pylance and install the recommended Pylance extension, does code completion improve?

**Comment by HaleTom** [comment]
I have the same issue with `"python.languageServer": "Pylance"`.

See more generic issue:  Pylance / Language server support #4307

**Comment by HaleTom** [comment]
Previous art: https://stackoverflow.com/questions/65561436/pylance-not-working-in-vscode-jupyter-notebooks

**Comment by corman44** [comment]
Hi @joyceerhl, code completion seems to be working after switching to Pylance. Thank you for the support!
