### ISSUE TITLE
Build zmq binaries for the new Mac ARM Processor

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4293]
Slowly Mac ARM processor will be the default on most macs.
Today zmq binaries are avaialble for Mac ARM.

We should consider build them or alternatives (upgrade or the like.
Else we're going to end up using Jupyter all over again for most macs.
This isn't an issue, but we decided to go with zmq do to a number of benefits.

Last build of this package was over a year ago https://github.com/zeromq/zeromq.js

**Comment by joyceerhl** [comment]
Closing in favor of https://github.com/microsoft/vscode-jupyter/issues/5206
