### ISSUE TITLE
Remove `info-needed` label when someone replies to an issue

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4294]
Goal - easily identify issues that need to be actioned (via a simple query).
Issues that fall into this category must be looked at, query = assigned to someone, in parking lot or new issues, & no label of info-need & label = bug

This way issues that have been commented on a no longer flaged as info-needed and not forgotten.
If an issue has a label of info-needed for more than ? months, surely we can close that issue.
We cannot close issues just because its stale, its possible we didn't get back to the user or dodn't prioritize the issue.

**Comment by rchiodo** [comment]
Not sure we need this. We handle info-needed manually now. Not sure we need to automate it?
