### ISSUE TITLE
cant create jupyter notebook

### ISSUE THREAD

**Issue by tingmwu** [microsoft/vscode-jupyter#4295]
Issue Type: <b>Bug</b>

when I use ctrl+shift+p create a jupyter notebook, it shows "Create New Blank Jupyter Notebook' resulted in an error (command 'jupyter.createnewnotebook' not found)". 

Extension version: 2020.12.414227025
VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19041

**Comment by IanMatthewHuff** [comment]
@tingmwu Looks like you are on an older version of VS Code there. Could you please update VS Code to the newest version and see if you are still having the issue?

**Comment by tingmwu** [comment]
As you suggested, I updated the VS code and all the plug-ins, and still showed “Command 'Jupyter: Create New Blank Jupyter Notebook' resulted in an error (command 'jupyter.createnewnotebook' not found)”. The reinstallation is still like this. my jupyter worked well without VS Code.



At 2021-01-06 01:21:05, "Ian Huff" <notifications@github.com> wrote:

@tingmwu Looks like you are on an older version of VS Code there. Could you please update VS Code to the newest version and see if you are still having the issue?

**Comment by IanMatthewHuff** [comment]
@tingmwu Looks like we had an activation ordering issue here. The PR in progress above #4313 should resolve this issue and be in shortly.

**Comment by rchiodo** [comment]
Validated. THis should be fixed in our next release.
