### ISSUE TITLE
Generate perf report on every submission

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4297]
Hopefully the PR build task can run the perf test and submit it.

**Comment by rchiodo** [comment]
Going to try this in two steps:
- Add a perf test yml file that just updates a txt file with a number in it and see that a submit to main updates it
- Add an actual perf test that generates a json file with perf numbers. This will submit on every PR completion assuming I was able to get the first step to work.

**Comment by greazer** [comment]
Closing as dupe of #8585
