### ISSUE TITLE
Error squiggle in cell when not expected (native notebooks) because of missing line breaks

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4300]
![image](https://user-images.githubusercontent.com/19672699/103709133-c547af00-4f66-11eb-9661-f291c0c7b38f.png)

I believe this is caused by there not being spaces between cells in the concatenated document. Probably should stick on on the end of every cell.

**Comment by rchiodo** [comment]
This is going to be done in the Python Extension.

**Comment by rchiodo** [comment]
For validation, you'll need the latest insiders python extension

**Comment by DonJayamanne** [comment]
Validated
