### ISSUE TITLE
Pylance / Language server full support

### ISSUE THREAD

**Issue by HaleTom** [microsoft/vscode-jupyter#4307]
## Environment data

-   VS Code version: Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.80-2-MANJARO
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: Linux svelte 5.4.80-2-MANJARO #1 SMP PREEMPT Sat Nov 28 09:58:18 UTC 2020 x86_64 GNU/Linux
-   Python and/or Anaconda version: 3.9.1, conda, conda 4.8.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour
Language server functions are available

Eg, pressing F2 to rename a variable, I get the rename variable popup

## Actual behaviour

Pylance works for `.py` files:

![.py with pylance](https://i.imgur.com/Zf4u8h4.png)

But doesn't work with Jupyter `.ipynb` notebooks:

![.ipynb with pylance](https://i.imgur.com/1MeTjuK.png)

I tried saving the `.ipynb` - same issue.

## Steps to reproduce:

1. See images above.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'jupyterTest'
Error 2021-01-06 09:44:36: Jupyter Kernel Spec not found for a local connection
> /bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.local/share/miniconda3/envs/rl/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> ~/.local/share/miniconda3/envs/rl/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> ~/.local/share/miniconda3/envs/rl/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/.local/share/miniconda3/envs/rl/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> ~/.local/share/miniconda3/envs/rl/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/.local/share/miniconda3/envs/rl/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/.local/share/miniconda3/envs/rl/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
Started kernel Python 3.9.1 64-bit ('rl': conda)
> ~/.local/share/miniconda3/envs/rl/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/.local/share/miniconda3/envs/rl/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
```

</p>
</details>

**Comment by HaleTom** [comment]
Previous art: https://stackoverflow.com/questions/65561436/pylance-not-working-in-vscode-jupyter-notebooks

**Comment by rchiodo** [comment]
Thanks for the bug.

We do have partial intellisense in notebooks, but rename support is not currently supported. It works slightly better if you use VS code insiders (this will force notebooks to open with a beta notebook editor that has better intellisense), but this still doesn't support rename yet.

**Comment by jackedai** [comment]
Can confirm that with VS Code insiders, Python Daily insiders channel, and Pylance that this problem has disappeared and everything is working exactly as I expect. Really well done makes for the best Jupyter experience yet, the only thing missing is 'Rename Symbol' not a huge deal in Jupyter though.

**Comment by jackedai** [comment]
This is working great on the daily Python preview channel with Jupyter, Pylance and Python 3.9.1.

The only problem is that it doesn't recognize when I'm putting in a object just for Jupyter to print its __repr__, and won't recognize the line break. Easy enough to put line breaks in but might frustrate some people, here is an example:
![image](https://user-images.githubusercontent.com/61746202/104118126-8d26de80-5361-11eb-8e86-1b20d9b24660.png)

**Comment by rchiodo** [comment]
Thanks. Line breaks are actually already being tracked by this issue here:
https://github.com/microsoft/vscode-jupyter/issues/4300

**Comment by fromm1990** [comment]
I would love a full pylance experience within notebooks as well. I have a significant increase of code mistakes in notebooks compared to plain python files with pylance. It will definitely help my productivity when working within notebooks.

**Comment by haeraeus** [comment]
This code actually works :(
![image](https://user-images.githubusercontent.com/27274713/119356246-81034400-bca6-11eb-9f02-96980402e16a.png)

**Comment by altosaar** [comment]
+1 pylance does not work for jupyter notebooks, and would be nice to have.

**Comment by rchiodo** [comment]
This should be working now but the 16 upvotes it received on Jul 19th makes me think it isn't working for some people.

**Comment by altosaar** [comment]
Still not working unfortunately!

**Comment by TTTPOB** [comment]
I found that pylance is working when I choose to launch jupyter server in "local" (which is the default option), but not "remote"
but I need to run notebooks remotely because this allows me to manually manage the kernels

**Comment by TTTPOB** [comment]
I found that if I start a remote server manually, connect a notebook from vscode to it, pylance wont be enabled,
but if i let vscode start a local jupyter server instead, pylance will be working as normal

**Comment by markub3327** [comment]
I don't know why my Pylance give me a lots of errors, but the cell and whole notebook I can run without any issue (no errors). Here is list of founded errors: 
  * Unindent not expected
  * Unexpected indentation
  * Expected expression
  * "(" was not closed
  * and so on ...
 

Thanks.

**Comment by rchiodo** [comment]
@markub3327 I opened a new issue for you (#8678). We need some more information to help you.

**Comment by DonJayamanne** [comment]
Closing this as fixed
