### ISSUE TITLE
[UX] Show error globally when it happens somewhere in a notebook during execution

### ISSUE THREAD

**Issue by roma-glushko** [microsoft/vscode-jupyter#4311]
Currently, when execute a notebook and the error occurs, the only way to find a place when error occurred is by manually browsing through the whole notebook.  

Furthermore if your error is in a middle of notebook and you happen to be review the end of it,  it may be confusing to recognise that notebook execution ended up with an error that you need to take a look at.

In addition, we rarely spend time waiting till notebook execution is finished and usually switching to some another stuff while it's executing (like another notebook in the same project). Also, we rarely have a notebooks with a few cells and even simple data analysis or modeling leads to tens of cells if not more. In that cases, the importance of this UX issue grows. 

I propose to introduce a way to globally notify users that error occurs in the notebook, so it would be transparent where to look at in order to see execution status. 

It would great to quickly navigate to a cell with errors. So it would be much quicker to deal with errors.

**Comment by rchiodo** [comment]
Thanks for the suggestion.

I think the most obvious place would be in the 'Problems' pane where syntax errors show up.

**Comment by roma-glushko** [comment]
@rchiodo yeah, had the same thought. Also, some toaster notification would not hurt in addition to the error in the Problems section.

**Comment by DonJayamanne** [comment]
Fixed in the latest version of VS Code, see here https://code.visualstudio.com/updates/v1_70#_go-to-most-recently-failed-cell
