### ISSUE TITLE
Outline view for native notebooks does not show any code

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4315]
Seems to be working just fine now for markdown

![image](https://user-images.githubusercontent.com/19672699/103819103-a278d180-501e-11eb-8175-3347229ad892.png)

However I believe we need to implement a symbol provider for the entire notebook. It may or may not require changes to the pylance concatenation work we did.

**Comment by DonJayamanne** [comment]
> However I believe we need to implement a symbol provider for the entire notebook. It may or may not require changes to the pylance concatenation work we did.

Should it show symbols in the code?
If it did, then its not a TOC (which is what Jupyter users require).
I think VSC team did discuss this to great lenghts, whehter it should or not support code symbols in there as well.

Something for PMs & QP & then discussion with VSC?

**Comment by rchiodo** [comment]
If you look at @jrieken's example, their github issues notebook is showing code:
https://github.com/microsoft/vscode/issues/98173

**Comment by jrieken** [comment]
> However I believe we need to implement a symbol provider for the entire notebook.

No, there is no participation possible. Today, all notebooks get the same outline/toc which is markdown cells (by header) and code cells (always show the first non empty line). We could support document symbol outlines for code cells which would require a normal document symbol provider but that has low/no priority at the moment.

**Comment by rchiodo** [comment]
Sorry I didn't realize the first line of code is there. The icon is very similar to the markdown one.

**Comment by rchiodo** [comment]
Maybe that should be a separate issue? The code also seems to be out of order. I'll enter a bug
