### ISSUE TITLE
Solarized Light colour theme does not show highlighted text in code cells

### ISSUE THREAD

**Issue by kopeckyf** [microsoft/vscode-jupyter#4323]
## Environment data

-   VS Code version: 1.52.1
-   Jupyter Extension version (available under the Extensions sidebar): 2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): 2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: Windows, checked and confirmed on Fedora 33
-   Python and/or Anaconda version: 3.19
-   Type of virtual environment used: N/A
-   Jupyter server running: Local

## Expected behaviour

In code cells in Solarized Light, when text is selected it should have a different colour than the background.

## Actual behaviour

In code cells in Solarized Light, selected text has the same colour as the background.

## Steps to reproduce:

Trivial. Example screenshot:
 
![grafik](https://user-images.githubusercontent.com/10461729/103947547-8701e980-5138-11eb-943e-67765cc4631b.png)

"plt" is selected, but you can't see it.

## Logs

N/A

## Comment
I would have created a PR instead of a bug report, but I'm too inexperienced with Visual Studio Code themes to find the colour settings and change them, sorry :(

**Comment by DonJayamanne** [comment]
Thanks for reporting this issue, we'll look into this.

> I would have created a PR instead of a bug report, but I'm too inexperienced with Visual Studio Code themes to find the colour

Thanks for even considering this option.

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Feel free to try the new experience in VS Code Insiders. The new experience is the default.
