### ISSUE TITLE
Native Notebooks - Jupyter Server Selector

### ISSUE THREAD

**Issue by ayim** [microsoft/vscode-jupyter#4328]
The Jupyter Server entry point that used to be located here: 
![image](https://user-images.githubusercontent.com/10951869/103951208-1dabb780-50f3-11eb-997e-6a39646dc06a.png)

Will be moved to the global status bar in Native Notebooks since the original entry point is no longer available.
![image](https://user-images.githubusercontent.com/10951869/103958685-79ca0800-5102-11eb-8e9a-784bfc7e73c8.png)

All functionality should remain the same - this will help achieve experience parity in native notebooks.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue with the suggestions, I'm closing this in favor of #254
The functionality & UI elements will be addressed in that issue.
