### ISSUE TITLE
The Jupyter notebook in VSCode has no "IntelliSense" document content.

### ISSUE THREAD

**Issue by Jill-Cheng** [microsoft/vscode-jupyter#4329]
Now, the function of Jupyter notebook in VSCode is provided by the extension "Jupyter", which uses the "IntelliSense" provided by the extension "Jupyter". But its "IntelliSense" has no document content.

1.
before:

![image](https://user-images.githubusercontent.com/61971386/103986357-8e230900-51c5-11eb-9568-84bf6f5b8f52.png)

now:

![image](https://user-images.githubusercontent.com/61971386/103986440-af83f500-51c5-11eb-841f-e14947f82d89.png)

2. 
before:

![image](https://user-images.githubusercontent.com/61971386/103986574-f7a31780-51c5-11eb-8081-a3530c154338.png)

now:

![image](https://user-images.githubusercontent.com/61971386/103986658-1acdc700-51c6-11eb-8863-10c3a47a8037.png)

**Comment by claudiaregio** [comment]
Closing as dupe of #4218
