### ISSUE TITLE
Pandas df.head() very slow to respond

### ISSUE THREAD

**Issue by noppGithub** [microsoft/vscode-jupyter#4331]
## Environment data

-   VS Code version: 1.52.1(user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Home
-   Python and/or Anaconda version: Python 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | N/A: Local

## Expected behaviour

Respond within less than a second(just like Jupyter browser)

## Actual behaviour

Waited for 5 mins before the result appear

## Steps to reproduce:
1. Install VS Code
2. Download the extensions above
3. Create a file with .ipynb
4. Click on the file
5. Press "Trust" button
6. Load the data into dataframe(~100k rows, 5 columns)
7. Type df.head()

**Comment by claudiaregio** [comment]
@noppGithub Could you please provide the dataset or notebook you are trying to work with?

**Comment by noppGithub** [comment]
@claudiaregio After factory reset my Windows, the issue is gone.
Using VSCODE is even faster than the traditional `jupyter` server.

**Comment by claudiaregio** [comment]
@noppGithub glad to hear that! Closing as issue is no longer occuring
