### ISSUE TITLE
VSCode invokes `provideKernels` every time we change tabs between notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4332]
Upstream issue https://github.com/microsoft/vscode/issues/114048
This was partially fixed here https://github.com/microsoft/vscode-jupyter/pull/4192

However the kernel has already been changed in the notebook editor & that causes other issues.
the root cause is with VS Code & we cannot tell what the previously selected kernel was/is.

**Comment by rchiodo** [comment]
This still occurs. provideKernels is called on every tab switch.

**Comment by greazer** [comment]
What is the user-facing result of this problem?

**Comment by DonJayamanne** [comment]
> What is the user-facing result of this problem?

The active kernel could change behind the scenes.
We need to validate this.
Ian reported this issue:
* Open a notebook, slect kernel A
* Open another notebook select Kernel b
* Tab between the two & the first notebook will end up with some other kernel (**even when user didn not change this_**

**I thought VS Code fixed this, we need to validate this.
I think VSCode calling the funciton is OK, provided the kernel does not change just because of tabbing in/out.**

**Comment by rchiodo** [comment]
Validated.

**Comment by DonJayamanne** [comment]
https://github.com/microsoft/vscode/issues/116504

**Comment by DonJayamanne** [comment]
This will be resolved with VS Codes changes to how kernels are provided.

**Comment by DonJayamanne** [comment]
Closing this issue as VS Code is planning on re-wamping the kernel provider API.
