### ISSUE TITLE
Ensure we use the new Trusted notebook icon

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4338]
TODO: Don find the icons

**Comment by DavidKutu** [comment]
use blocked site and encryption

**Comment by DonJayamanne** [comment]
Validated. However moving back to backlog so that we move the icon to the far right.
This way its a non-introsive icon, right now this is in beween the move cells & maginify icons.
I.e. adding an icon that does nothing in between that do, seem weird, might as well move this to the far right.

@claudiaregio /cc

**Comment by claudiaregio** [comment]
@DonJayamanne Please make sure it is moved all the way to the right

**Comment by rchiodo** [comment]
Validated
