### ISSUE TITLE
Refactor INotebook to be simpler

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#434]
# Work Item

Split JupyterNotebook into separate classes
- Execution wrapper (for everything - generic)
- Kernel changing
- Kernel initialization
- Kernel creation
- Connection
- Kernel mapped to file URI

Determine if Live share is used or not

# Original Complaint:

from here (http://pyretro.westus.azurecontainer.io:4000/#3b9f321e-9838-486e-a661-a5e96c46189f)

CellExecution and JupyterNotebook should be combined into a more generic algorithm (this is really jupyter exceution)
jupyterNotebook.ts should probably be renamed? That's where we handle IO pub messages, and I always have to dig around for that file when trying to debug kernel messages
Break INotebook into smaller components (componetise):
* Separate class to communicate with kernel
* Separate class to get active kernel & status of kernel & the like
* Separate class to execute & manage execution state
* Separate class to manage starting kernels
JupyterNotebook should be split into multiple parts. Exposing the kernel, exposing the session, and execution. Exposing the kernel by itself would make the execution part easy to do alone
Our initial "mega-classes" like INotebook Session are too big and expose too much.
Break large classes into smaller components.
Composition over inheritance & composition over god classes.
Having one class that does everything makes it difficult to extend & re-purpose

**Comment by IanMatthewHuff** [comment]
Superseded by more recent #6950 and internal #191
