### ISSUE TITLE
Variable Inspector Pane not Available under New Notebook Experience

### ISSUE THREAD

**Issue by davidski** [microsoft/vscode-jupyter#4348]
I can't find any references in the blog posts discussing the new notebook editing experience that suggests that variable 
inspection is not supported under the new notebook experience. The insider Jupyter extension has preferences for the 
variable pane so I'm assuming/hoping this a bug and not just user error. :smile:

## Environment data

-   VS Code version: 1.53.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.478960791-dev
-   OS (Windows | Mac | Linux distro) and version: MacOS Big Sur
-   Python and/or Anaconda version: python3.9.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): NA
-   Jupyter server running: Local

## Expected behavior

- Icon(s) for displaying the variable inspector

## Actual behavior

There is no icon for displaying the variable inspector window, nor is any command for activating that pane available in the command palette.

<img width="1369" alt="Screen Shot 2021-01-11 at 7 57 03 PM" src="https://user-images.githubusercontent.com/2313762/104267833-4f03ea80-5447-11eb-8733-8422ea05840b.png">

## Steps to reproduce:

1. Create a blank Jupyter notebook
2. Add basic code such as 
```
import numpy as np
from numpy.random import rand
arr = rand(20, 20)
```
3. Execute the cell.
4. Confirm that no icons are displayed for the variable inspector.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'NativeNotebookEditor'
Error 2021-01-11 19:31:10: Jupyter Kernel Spec not found for a local connection
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2021-01-11 19:31:23: Jupyter Kernel Spec not found for a local connection
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Started kernel Python 3.9.1 64-bit
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2021-01-11 19:33:07: Jupyter Kernel Spec not found for a local connection
Error 2021-01-11 19:33:44: Jupyter Kernel Spec not found for a local connection
Error 2021-01-11 19:34:01: Jupyter Kernel Spec not found for a local connection
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Started kernel Python 3.9.1 64-bit
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
```

</p>
</details>

**Comment by IanMatthewHuff** [comment]
Hey @davidski it's just a missing feature, I'm actually currently adding this as we speak :). The new UI is provided by VS Code, and doesn't have the UI affordances to add the variable explorer into the document itself. The new one that I'm adding looks just like the variable explorer in the old UI, only it's docked into a separate panel in VS code. This is just one of the few missing things that we wanted to get done before rolling the new UI out of insiders and into stable.

**Comment by IanMatthewHuff** [comment]
Closing this issue as we already have work item bugs tracking the new variable explorer.

**Comment by davidski** [comment]
@IanMatthewHuff Are the work items for the variable explorer (and other missing features from the old interface) publicly accessible? I'd like to keep eyes on those. It's painful going back to the old interface at this point. 😉

**Comment by IanMatthewHuff** [comment]
@davidski They are public, but on the downside we use a different program which is not public to help track what stage they are in (in progress, in review, completed) so they might not be quite as informative as they could be:
https://github.com/microsoft/vscode-jupyter/issues/1230 (here is the variable explorer one for instance)
Parity with the old views is our team's main focus now, so the plan is for in the next couple of releases to start rolling it out more. Can't commit to a specific date though.
