### ISSUE TITLE
Recursive debugging in Jupyter Console (interactive window)

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-jupyter#4352]
For 1: Yes, I am talking about the Jupyter integration launched via command "Jupyter: Create interactive window". 

![Screenshot_20210112_160258](https://user-images.githubusercontent.com/20026777/104332286-4ddac800-54f0-11eb-8be7-0d6757ac5a04.png)

With respect to issue 2, staying always inside the jupyter console would greatly fit to recursive debugging, enabling the following workflow: 

- Stopping at some initial breakpoint
- investigate stack trace, create some plots
- modify the current stack by calling additional functions, eventually stop in between at some overlaped breakpoint
- create some other plot
- continue to breakpoint 1
- continue ... 
- ...

But even without recursive debugging, it would be nice to have the fully-fledged jupyter console available, when stopping at some breakpoint. What is the purpose of the current implementation, i.e. post-poning commands?

For 2: Ok, thanks for the hint (I thought I had searched the issues before, sorry!).

_Originally posted by @darim1 in https://github.com/microsoft/debugpy/issues/525#issuecomment-758680695_

**Comment by IanMatthewHuff** [comment]
@darim1 I'm not fully sure if we can support this in the interactive console debugger, but I can file this as an enhancement to investigate.

**Comment by darim1** [comment]
OK, thanks!

I'd like to provide a simple example:

1. Please create this file:
''
def fun(): import pdb; pdb.set_trace() print('fun') def rec_fun(): import pdb; pdb.set_trace() print('fun') a = 1 import pdb; pdb.set_trace() b = 2
''
2. Then step through these commands inside ipython:

''
import my_module # This will stop at the breakpoint and allow user further user input in the console, e.g. `print(a)` # press c to completely load the module my_module.fun() # This will stop the debugger at the breakpoint inside function fun import my_module # this will load the module for the debugger instance debug my_module.rec_fun() # this will launch a nested debugger instance # Press c+enter: The nested instance will stop at breakpoint inside rec_fun() # Press c+enter: The debugger will move to the previous breakpoint # Press c+enter: The debugger will leave and go back to normal REPL mode.
''



Am 13. Januar 2021 00:51:46 MEZ schrieb Ian Huff <notifications@github.com>:
>@darim1 I'm not fully sure if we can support this in the interactive console debugger, but I can file this as an enhancement to investigate.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/microsoft/vscode-jupyter/issues/4352#issuecomment-759110617
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by darim1** [comment]
One additional remark:

In my opinion it's not necessary to explicitly specify the "debug" command in order to enter recursive mode, but rather let eventually all commands silently enter recursive mode, whenever there is a breakpoint  involved.

What do you think?


Am 13. Januar 2021 01:56:56 MEZ schrieb Daniel Rimmelspacher <danervt@hotmail.com>:
>OK, thanks!
>
>I'd like to provide a simple example:
>
>1. Please create this file:
>''
>def fun(): import pdb; pdb.set_trace() print('fun') def rec_fun(): import pdb; pdb.set_trace() print('fun') a = 1 import pdb; pdb.set_trace() b = 2
>''
>2. Then step through these commands inside ipython:
>
>''
>import my_module # This will stop at the breakpoint and allow user further user input in the console, e.g. `print(a)` # press c to completely load the module my_module.fun() # This will stop the debugger at the breakpoint inside function fun import my_module # this will load the module for the debugger instance debug my_module.rec_fun() # this will launch a nested debugger instance # Press c+enter: The nested instance will stop at breakpoint inside rec_fun() # Press c+enter: The debugger will move to the previous breakpoint # Press c+enter: The debugger will leave and go back to normal REPL mode.
>''
>
>
>
>Am 13. Januar 2021 00:51:46 MEZ schrieb Ian Huff <notifications@github.com>:
>>@darim1 I'm not fully sure if we can support this in the interactive console debugger, but I can file this as an enhancement to investigate.
>>
>>-- 
>>You are receiving this because you were mentioned.
>>Reply to this email directly or view it on GitHub:
>>https://github.com/microsoft/vscode-jupyter/issues/4352#issuecomment-759110617
>-- 
>Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by darim1** [comment]
OK, thanks!

I'd like to provide a simple example:

1. Please create this file "my_module.py":

```python
def fun():
   import pdb; pdb.set_trace()
   print('fun')
        def rec_fun():
            import pdb; pdb.set_trace()
            print('fun')
            a = 1

import pdb; pdb.set_trace()
b = 2
``` 

2. Then step through these commands inside ipython:

```python
import my_module # This will stop at the breakpoint and allow user further user input in the console, e.g. `print(a)`
# press c to completely load the module
my_module.fun() # This will stop the debugger at the breakpoint inside function fun
import my_module # this will load the module for the debugger instance
debug my_module.rec_fun() # this will launch a nested debugger instance
# Press c+enter: The nested instance will stop at breakpoint inside rec_fun()
# Press c+enter: The debugger will move to the previous breakpoint
# Press c+enter: The debugger will leave and go back to normal REPL mode.
```

One additional remark:

In my opinion it's not necessary to explicitly specify the "debug" command in order to enter recursive mode, but rather let eventually all commands silently enter recursive mode, whenever there is a breakpoint  involved.

What do you think?

**Comment by IanMatthewHuff** [comment]
@darim1 Appreciate the additional info. Not sure where this would fall in our priority queue, but it does seem like an interesting scenario to support for debugging.

**Comment by amunger** [comment]
this does not look specific to IW

**Comment by roblourens** [comment]
I'm pretty sure this is essentially the same as https://github.com/microsoft/vscode-jupyter/issues/1278#issuecomment-1216966234 (although some language is different and that one predates the native interactive window) but I understand what you're asking for.
