### ISSUE TITLE
Add .vscode tests for variable view to ensure we don't break functionality.

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#4355]
Need to make sure we have some tests here, note that we have functional tests for the old variable viewer which do much of the testing around specific variable types. That will all be the same. What we need here is variable view + native notebook + vscode specific stuff.

1 - Open a notebook, execute, verify variables
2 - 1 + execute a second cell, verify updated variables
3 - 1 + open a second editor, execute a cell, verify variables are from second editor
4 - 3 + switch back to first editor, verify variables are from first editor

**Comment by IanMatthewHuff** [comment]
I'd like to reopen this. We have the single sniff test in, but I had at least one more that I wanted to add. Already had it in progress.

**Comment by DavidKutu** [comment]
Validated, tests are in
