### ISSUE TITLE
UI Cleanup for the VariableView

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#4356]
UI cleanup needed to get the VariableView working well for release

1 - Remove the 'x' that lets you close the view, I believe this is a leftover from being hosted in the IW / old webview
2 - Size correctly to fill the webview area, right now it's not filling and it's still looking for height updates from the splitter

Optional
1 - Add the name of the active document on top
2 - Add a button into the editor window to open up the view

**Comment by IanMatthewHuff** [comment]
Adding, color syntax highlighting doesn't look correct in the view right now.

**Comment by claudiaregio** [comment]
For 1/27: 
P0: Remove 'X', Icon in notebook toolbar 
P1: name of active document on top, color syntax highlighting

**Comment by IanMatthewHuff** [comment]
@claudiaregio Sounds good. X removal and sizing went in on Friday. Will add icon next.

**Comment by IanMatthewHuff** [comment]
@claudiaregio Open view button just went in. At this point I might resolve this work item and create new items for syntax color and adding the name of the active document, just to make tracking easier.

**Comment by IanMatthewHuff** [comment]
For Validation. This bug is removing the x close button + sizing to fill. Will open new bugs for the other issues.

**Comment by rchiodo** [comment]
Validated
