### ISSUE TITLE
Options to disable notebook editor and notebook diff not working

### ISSUE THREAD

**Issue by jamesmyatt** [microsoft/vscode-jupyter#4357]
## Environment data

-   VS Code version: 1.52.1
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Python 3.8.6 | packaged by conda-forge | (default, Dec 26 2020, 04:30:06) [MSC v.1916 64 bit (AMD64)]
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

With the following options in my settings.json, I expect to open ipynb files as regular json files and to get a regular json file diff in the git tab using "Open changes".

```json
{
    ...
    "jupyter.useNotebookEditor": false,
    "notebook.diff.enablePreview": false,
    ...
}
```

I also get the same behaviour when `notebook.diff.enablePreview` is unset

## Actual behaviour

Always opens the file using the notebook editor, even for "Open changes".

## Steps to reproduce:

1. Set options as above
2. Open ipynb file: observe notebook editor
3. "Open changes" in git tab: observer notebook editor

## Logs

N/A

Looks like it's related to https://github.com/microsoft/vscode-jupyter/issues/633, which I previously worked around by disabling the notebook editor.

**Comment by IanMatthewHuff** [comment]
@jamesmyatt I just took a look at the previous fix (that was a fix that I personally validated). Between now and then we moved over to a new CustomEditor interface for opening .ipynb files. I repro what you see now so I believe that we have regressed this with that CustomEditor change. I'll mark it as such.

**Comment by jamesmyatt** [comment]
Thanks @IanMatthewHuff

**Comment by IanMatthewHuff** [comment]
@jamesmyatt I'm going to leave this open for now. But I'm not sure this is something that we'll actually be resolving, at least not directly. Currently our UI in VS Code stable is provided by a webview that we create, we did a lot of work to make this look and feel like core VS Code editors as we could, but it has its issues. However VS Code is now rolling out native VS Code support for notebook like documents and we are moving our UI over to that. If you install VS Code - Insiders you can see what this new interface looks like. I believe that in that new world VS Code (not our team) would own the diffing experience and the ability to view raw json.

**Comment by jamesmyatt** [comment]
@IanMatthewHuff , this was fixed again at some point and was working until  v2021.2.603412351. Then in v2021.3.619093157 it has been unfixed again. Everything else is up-to-date. Can we have the fix back please?

**Comment by IanMatthewHuff** [comment]
@jamesmyatt I'm going to resolve this particular issue against #633  as they should both cover the same topic. I believe this is regressed and we'll pull that bug back to triage to discuss fixing.
