### ISSUE TITLE
Remove custom editor support if in native notebook experiment

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4360]
CustomEditor and NativeNotebook cannot be enabled at the same time.

**Comment by DonJayamanne** [comment]
@rchiodo what's required here?

**Comment by rchiodo** [comment]
The settings.json editor settings will mess up the native notebooks if custom editor is turned on. VS code will use our custom editor instead of native notebooks (at least I believe it will). This is what happens if you use 'open with' and pick custom editor in insiders.

**Comment by DonJayamanne** [comment]
Looking at the code today, it should work as expected. Moving to validate.
Basically if user is not in custom editor, we remove the settings from their settings.json file.

**Comment by rchiodo** [comment]
Sorry there still needs to be changes done here. You can't enable the native notebook experiment in stable. It only works in insiders. So this can't even be validated.

**Comment by DonJayamanne** [comment]
Created issue for this #4488

**Comment by DonJayamanne** [comment]
Moving back to validate.

**Comment by DavidKutu** [comment]
validated
