### ISSUE TITLE
Add telemetry around experiments that a user is in

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4362]
This should include optInto and optOutFrom settings.

**Comment by joyceerhl** [comment]
It looks like we already have this: 
https://github.com/microsoft/vscode-jupyter/blob/8abe251c8edb394f951d1417b96eed32f0670ee2/src/client/common/experiments/service.ts#L98-L114

**Comment by rchiodo** [comment]
Validated. The telemetry shows up.
