### ISSUE TITLE
Name for Interactive #1

### ISSUE THREAD

**Issue by Victsz** [microsoft/vscode-jupyter#4365]
It would be clear if I can name the tab 
![image](https://user-images.githubusercontent.com/8154646/104426150-86e06e80-55bc-11eb-9b60-20b5bd454cad.png)

**Comment by rchiodo** [comment]
Thanks for the suggestion. 

If you use a ```# %%``` comment to start the interactive window, it will name it automatically like so:

![image](https://user-images.githubusercontent.com/19672699/104488064-b8d4df00-5582-11eb-9900-ec9b0695cd37.png)

If that doesn't work, how would you like to name it? 

I can think of two ways that would be possible:

1) A command that allows you to rename it. It brings up a quick pick like so:
![image](https://user-images.githubusercontent.com/19672699/104488325-0cdfc380-5583-11eb-8e29-82a1a31c3948.png)

2) A default name for all interactive windows you set in the settings.json

````json
"jupyter.interactiveWindow.prefix": "Interactive "
```

**Comment by Victsz** [comment]
Option 1 would be nice

Yes, I`m using # %% in a  named file, but it starts as Interactive #1. 
Is it because I enable multiple interactive window?
![image](https://user-images.githubusercontent.com/8154646/104538123-3d446200-5656-11eb-975d-64e28068d3b7.png)

**Comment by rchiodo** [comment]
Yes sorry didn't remember that 'perFile' is required for it to name the interactive window with the file name.

**Comment by amunger** [comment]
closing for lack of votes
