### ISSUE TITLE
Run selection in interactive window is no longer available 

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4368]
We used to have this on the context menu and as a command within a python file. It's no longer available.

This comment here pointed that out.
https://github.com/microsoft/vscode-jupyter/issues/3469#issuecomment-759293352

**Comment by rchiodo** [comment]
Not sure why this is in validate? It doesn't work for me.

**Comment by DavidKutu** [comment]
The command does appear on the command palette, and for it to appear on the editor context we need to check the setting "jupyter.sendSelectionToInteractiveWindow": true.

The ownsSelection editor context depends completely on this setting. Maybe we should remove it? Or have the setting only control the keybinding.

**Comment by rchiodo** [comment]
Validated.
