### ISSUE TITLE
Ctrl + F does not show the number of occurrences of the text that I am searching

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/vscode-jupyter#4373]
When using Jupyter notebook with Vs Code, Edit -> Find, or pressing Ctrl + F, it does not show the number of occurrences of the text that I am searching.

![image](https://user-images.githubusercontent.com/12703975/104494851-068e2d80-55fd-11eb-8ac9-855caa947b93.png)

**Comment by rchiodo** [comment]
Sorry but this isn't (and can't be) supported for the notebooks in the stable release of VS code.

However the VS code insiders version uses a new notebook editor. This does support CTRL+F finding all of the entries.

![image](https://user-images.githubusercontent.com/19672699/104496650-17538a80-558e-11eb-8018-df6153e25201.png)
