### ISSUE TITLE
Native Notebooks - Essential Jupyter Shortcuts to be supported

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#4376]
### Shortcuts for any mode
* [x] Shift + Enter: run the current cell, select below
* [x] Ctrl + Enter: run selected cells
* [x] Alt + Enter: run the current cell, insert below
* [x] Ctrl + S: save

### Shortcuts for selected mode
* [x] A: insert cell above
* [x] B: insert cell below
* [x] X: cut selected cells
* [x] C: copy selected cells
* [x] V: paste cells below
* [ ] Shift + V: paste cells above
* [x] D, D (press the key twice): delete selected cells
* [x] Z: undo cell deletion
* [x] S: Save
* [x] Y: change the cell type to Code
* [x] M: change the cell type to Markdown

### Shortcuts for edit mode
* [x] Esc: take you into select mode
* [x] Tab: code completion or indent
* [x] Ctrl + Z: undo
* [ ] Ctrl + Shift + Z or Ctrl + Y: redo
* [x] Ctrl + Home: go to cell start
* [x] Ctrl + End: go to cell end
* [x] Ctrl + Left: go one word left
* [x] Ctrl + Right: go one word right
* [x] Down: move cursor down
* [x] Up: move cursor up

**Comment by DonJayamanne** [comment]
Use `Option 2` as outlined here https://github.com/microsoft/vscode-jupyter/issues/4233

**Comment by claudiaregio** [comment]
@DonJayamanne thanks sorry thought I removed that one. Yes some of these I checked are already supported but wanted to make sure we had a full list to compare against.

**Comment by DonJayamanne** [comment]
> es some of these I checked are already supported but wanted to make sure we had a full list to compare against.

Thats fine, we can check that, this way the issue is a concise list of what needs to be available (easy for testing).

**Comment by greazer** [comment]
See #4233 for information as to how the keybindings should be included in the extension.

**Comment by DonJayamanne** [comment]
See #4233 for solution.

**Comment by DonJayamanne** [comment]
The following have not been added
* Shift + V: paste cells above (blocked on VS Code)
* Ctrl + Y: redo (not added as we support `Ctrl + Shift + Z`

**Comment by rchiodo** [comment]
Doesn't seem to be working at the moment.

**Comment by rchiodo** [comment]
Validated.
