### ISSUE TITLE
Ctrl+Enter not running current cell in VS code insiders version - instead inserting empty line below

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/vscode-jupyter#4377]
Sorry if this issue can't be supported for notebooks in **VS code insiders version**

Ctrl + Enter is just inserting line below, not executing current selected cell.

I have tried to include below in keybindings.json but its just not working.

```
{
    "key": "ctrl+enter",
    "command": "jupyter.runcurrentcell",
    "when": "editorTextFocus && jupyter.hascodecells && !editorHasSelection && !notebookEditorFocused"
  }
```
---

## VS-Code Version Details

Version: 1.53.0-insider
Commit: e17aea136d32fdb06d9b32184b04ccd36bb51e9c
Date: 2021-01-12T08:22:28.134Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Linux x64 5.8.0-36-generic

**Comment by rchiodo** [comment]
The keybinding would actually be this I believe:
```json
    {
        "key": "ctrl+enter",
        "command": "notebook.cell.execute",
        "when": "notebookCellListFocused"
    },
    {
        "key": "ctrl+alt+enter",
        "command": "-notebook.cell.execute",
        "when": "notebookCellListFocused"
    }
```

```jupyter.runcurrentcell``` is for the old notebook editor. VS code has their own commands for executing cells in the new editor (not controlled by the jupyter extension).

**Comment by rohan-paul** [comment]
Thanks so much, that works beautifully.
