### ISSUE TITLE
R kernal not working

### ISSUE THREAD

**Issue by okanji** [microsoft/vscode-jupyter#4388]
Issue Type: <b>Bug</b>

## Cannot select R kernal in VS code jupyter notebook

**Note: This does not happen in vs code insider, it works fine in insider so perhaps this bug has already been addressed in beta**

### Steps to Re produce
- Create new jupyter notebook in vs code
- In the top right of the editor, select the R kernal (default is python). You need to have installed R and the R kernal on your machine

![image](https://user-images.githubusercontent.com/30703259/104569867-165e3f80-5606-11eb-8226-47976edcccaa.png)

- The selection will not be recognized, nothing will change and the Kernel will remain 'Python'
- After saving the notebook, closing it and re opening the following appears:

![image](https://user-images.githubusercontent.com/30703259/104570001-3ee63980-5606-11eb-9c79-a2d8281882a2.png)

Extension version: 2020.12.414227025
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 9959db57-a060-434f-929b-dbac9810bf45|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt617:30244266
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
vstry244cf:30244300
pythonvsdeb440:30242242
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629

```

</details>

**Comment by DonJayamanne** [comment]
Thanks for reporting this issue. Unfortunately support for other language kernels in Notebooks is limited to the Native Editor available in VS Code Insiders. 
For now you'll need to use VS Code insiders. Please note thought, the plan is to eventually support the Native Notebook editor it in VS Code stable (not just Insiders).
