### ISSUE TITLE
Intellisense not working in different cells

### ISSUE THREAD

**Issue by LilHang** [microsoft/vscode-jupyter#4389]
## Environment data

-   VS Code version: 1.53.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: win10 20h2
-   Python and/or Anaconda version: anaconda custom
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | Local

## Expected behaviour

1. create new jupyter notebook in vscode
2. write code in cell no.1, eg: "temp = 1" or import a library
3. shift + enter，run cell no.1
4. in cell no.2，type”te....“or"numpy.", intellisense, autocompletion shows up

## Actual behaviour

in cell no.1 intellisense works fine, but in cell no.2 and cells below, it failed.
in .py file, intellisense works totally fine .

language server is set to Pylance, also post: https://github.com/microsoft/pylance-release/issues/829

**Comment by DonJayamanne** [comment]
@LilHang I'm so sorry for not getting back to you on this.
I have tested this at my end and works as expected, possible this is a duplicate of #4300
* Please could you try this once again with a new line in the second cell (before the code)
As follows:
```python
# empty line
te
```

**Comment by LilHang** [comment]
@DonJayamanne Thanks，it works when i left a blank line before the code(either in the cell above or the current cell) , maybe this is a duplicate of #4300, I'm going to close this issue.
