### ISSUE TITLE
Auto start doesn't work for native notebooks

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4411]
Makes startup take all that much longer.

**Comment by rchiodo** [comment]
This is actually not working correctly. It puts up errors on auto start. The old code would ignore errors.

**Comment by rchiodo** [comment]
Meaning if you have an error starting a kernel, it shouldn't just show up randomly. It should only show if you click run a cell.

**Comment by DonJayamanne** [comment]
> puts up errors on auto start. The old code would ignore errors.

Can you let me know what you did to get errors? Is it an invalid kernel or what?

**Comment by rchiodo** [comment]
I have a kernel without ipykernel installed. Well just an interpreter. It's set a the default for a notebook. On opening the notebook an error pops up.

**Comment by rchiodo** [comment]
This still isn't working? I believe I merged your latest changes. I still get the error to come up without clicking on anything.

**Comment by DonJayamanne** [comment]
Unable to replicate, please could you re-test.

**Comment by rchiodo** [comment]
I believe I fixed it with the subsequent submission. We should probably have somebody else validate.

**Comment by IanMatthewHuff** [comment]
@DonJayamanne @rchiodo This didn't validate for me. When I start up VS Code with a native notebook I see the message that it's looking to start a server due to preload conditions. But I don't see an actual server start. When I execute the first cell, I actually see the message for the server starting hit:
[I 10:31:22.120 NotebookApp] The Jupyter Notebook is running at:
[I 10:31:22.121 NotebookApp] http://localhost:8888/?token=5578ca9da346e3451deb88eefcb727316bbef761f33788ce

**Comment by rchiodo** [comment]
@IanMatthewHuff  does it work for raw?

**Comment by DonJayamanne** [comment]
Validated and seems to work for me:
* Raw
    * Open a notebook and kernel will get selected by VS Code
    * A kernel is auto started
    * Test: Wait for a few seconds, then run a cell it should run immediately
* Jupyter (non-Raw)
    * Open a notebook and kernel will get selected by VS Code
    * Jupyter server is auto started auto started
    * Test: Wait for a few seconds, then run a cell it should not start jupyter, but Kernel will get started (this cannot be avoided, unless we start Jupyter server with the exact same default kernel).
    * We should not have to start the server, but use existing server

I managed to validate both while debugging, i.e. confirming at a lower level that it works as expected.

**Comment by joyceerhl** [comment]
Validated
