### ISSUE TITLE
Cannot use interactive window as it shows (Python 3.8.7 64-bit requires ipykernel to be installed)

### ISSUE THREAD

**Issue by RajatM24** [microsoft/vscode-jupyter#4417]
## Environment data

-   VS Code version: 1.52.1
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: Windows 7 ultimate
-   Python and/or Anaconda version: 3.8.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Dont know what this is or how to find it i am very new to all of this
-   Jupyter server running: it says default vscode runs it on your localhost

## Expected behaviour
i think it is expected to run flawlessly open interactive windows and run the code 

## Actual behaviour
whenever i try to open the interactive window in vscode with and without code
it asks ( Python 3.8.7 64-bit requires ipykernel to be installed )
with an option to install,
when clicked install it runs the script which gives a long list starting with requirements fulfilled 
## Steps to reproduce:
1. Well with above python version and os with latest vscode
2. just right click and click on run current file in interactive windows 
3. thats when the error occurs
## Logs
the below is from vscode developer console
![Capture](https://user-images.githubusercontent.com/77397073/104811639-f5266a80-5822-11eb-92b4-76529dc38b50.PNG)
![Capture1](https://user-images.githubusercontent.com/77397073/104811641-f8b9f180-5822-11eb-8c76-8cdc5fc6b2bc.PNG)
![Capture2](https://user-images.githubusercontent.com/77397073/104811642-fa83b500-5822-11eb-8ba7-dee646c2b18b.PNG)
and this is from view->output 
set output to jupyter

User belongs to experiment group 'pythonJoinMailingListVar2'
User belongs to experiment group 'jupyterTestcf'
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
> ~\AppData\Local\Programs\Python\Python38\python.exe -c "import os;print(os.path.realpath("C:\\Users\\ABC\\AppData\\Roaming\\jupyter\\kernels"))"
> ~\AppData\Local\Programs\Python\Python38\python.exe -c "import os;print(os.path.realpath("C:\\Users\\ABC\\AppData\\Roaming\\jupyter\\kernels"))"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
Error 2021-01-16 17:46:55: Find kernel spec, Class name = I, completed in 9132ms, has a falsy return value, Arg 1: <Uri:Untitled-1>, Arg 2: undefined, Arg 3: undefined, Arg 4: undefined, Return Value: undefined [Error: IPyKernel not installed into interpreter Python 3.8.7 64-bit:C:\Users\ABC\AppData\Local\Programs\Python\Python38\python.exe
	at I.installDependenciesIntoInterpreter (c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:1:209187)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:1:207872)]
Error 2021-01-16 17:46:55: Exception attempting to start notebook:  [Error: IPyKernel not installed into interpreter Python 3.8.7 64-bit:C:\Users\ABC\AppData\Local\Programs\Python\Python38\python.exe
	at I.installDependenciesIntoInterpreter (c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:1:209187)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:1:207872)]
Error 2021-01-16 17:46:55: DataScience Error [Error: IPyKernel not installed into interpreter Python 3.8.7 64-bit:C:\Users\ABC\AppData\Local\Programs\Python\Python38\python.exe
	at I.installDependenciesIntoInterpreter (c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:1:209187)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:1:207872)]
Error 2021-01-16 17:46:55: DataScience Error [Error: IPyKernel not installed into interpreter Python 3.8.7 64-bit:C:\Users\ABC\AppData\Local\Programs\Python\Python38\python.exe
	at I.installDependenciesIntoInterpreter (c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:1:209187)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:1:207872)]
Error 2021-01-16 17:46:55: Failed to initialize ipywidgetHandler [Error: IPyKernel not installed into interpreter Python 3.8.7 64-bit:C:\Users\ABC\AppData\Local\Programs\Python\Python38\python.exe
	at I.installDependenciesIntoInterpreter (c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:1:209187)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:1:207872)]
Error 2021-01-16 17:46:55: DataScience Error [Error: IPyKernel not installed into interpreter Python 3.8.7 64-bit:C:\Users\ABC\AppData\Local\Programs\Python\Python38\python.exe
	at I.installDependenciesIntoInterpreter (c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:1:209187)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:1:207872)]
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"

**Comment by RajatM24** [comment]
And sorry if this is too much i just new to all this stuff

**Comment by joyceerhl** [comment]
Hi @RajatM24 this is the perfect amount of detail, thank you! It seems like our ipykernel install detection isn't working for you. If you explicitly run this: `~\AppData\Local\Programs\Python\Python38\python.exe -m pip install ipykernel`, can you start the interactive window? Can you also run `pip show ipykernel` and paste the output here?

**Comment by RajatM24** [comment]
Sorry in I leave in India so it is 11 here I will send tomorrow

**Comment by RajatM24** [comment]
well the `~\AppData\Local\Programs\Python\Python38\python.exe -m pip install ipykernel` command says `Requirement already satisfied: ipykernel in c:\users\abc\appdata\local\programs\
python\python38\lib\site-packages (5.4.3)
Requirement already satisfied: tornado>=4.2 in c:\users\abc\appdata\roaming\pyth
on\python38\site-packages (from ipykernel) (6.1)
Requirement already satisfied: ipython>=5.0.0 in c:\users\abc\appdata\roaming\py
thon\python38\site-packages (from ipykernel) (7.19.0)
Requirement already satisfied: traitlets>=4.1.0 in c:\users\abc\appdata\roaming\
python\python38\site-packages (from ipykernel) (5.0.5)
Requirement already satisfied: jupyter-client in c:\users\abc\appdata\roaming\py
thon\python38\site-packages (from ipykernel) (6.1.11)
Requirement already satisfied: backcall in c:\users\abc\appdata\roaming\python\p
ython38\site-packages (from ipython>=5.0.0->ipykernel) (0.2.0)
Requirement already satisfied: setuptools>=18.5 in c:\users\abc\appdata\local\pr
ograms\python\python38\lib\site-packages (from ipython>=5.0.0->ipykernel) (49.2.
1)
Requirement already satisfied: colorama in c:\users\abc\appdata\local\programs\p
ython\python38\lib\site-packages (from ipython>=5.0.0->ipykernel) (0.4.4)
Requirement already satisfied: jedi>=0.10 in c:\users\abc\appdata\roaming\python
\python38\site-packages (from ipython>=5.0.0->ipykernel) (0.18.0)
Requirement already satisfied: pickleshare in c:\users\abc\appdata\roaming\pytho
n\python38\site-packages (from ipython>=5.0.0->ipykernel) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c
:\users\abc\appdata\roaming\python\python38\site-packages (from ipython>=5.0.0->
ipykernel) (3.0.10)
Requirement already satisfied: decorator in c:\users\abc\appdata\roaming\python\
python38\site-packages (from ipython>=5.0.0->ipykernel) (4.4.2)
Requirement already satisfied: pygments in c:\users\abc\appdata\roaming\python\p
ython38\site-packages (from ipython>=5.0.0->ipykernel) (2.7.4)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\abc\appdata\roami
ng\python\python38\site-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel) (0
.8.1)
Requirement already satisfied: wcwidth in c:\users\abc\appdata\roaming\python\py
thon38\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython
>=5.0.0->ipykernel) (0.2.5)
Requirement already satisfied: ipython-genutils in c:\users\abc\appdata\roaming\
python\python38\site-packages (from traitlets>=4.1.0->ipykernel) (0.2.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\abc\appdata\loca
l\programs\python\python38\lib\site-packages (from jupyter-client->ipykernel) (2
.8.1)
Requirement already satisfied: pyzmq>=13 in c:\users\abc\appdata\local\programs\
python\python38\lib\site-packages (from jupyter-client->ipykernel) (21.0.1)
Requirement already satisfied: jupyter-core>=4.6.0 in c:\users\abc\appdata\roami
ng\python\python38\site-packages (from jupyter-client->ipykernel) (4.7.0)
Requirement already satisfied: pywin32>=1.0 in c:\users\abc\appdata\local\progra
ms\python\python38\lib\site-packages (from jupyter-core>=4.6.0->jupyter-client->
ipykernel) (300)
Requirement already satisfied: six>=1.5 in c:\users\abc\appdata\local\programs\p
ython\python38\lib\site-packages (from python-dateutil>=2.1->jupyter-client->ipy
kernel) (1.15.0)`
and `pip show ipykernel` says
Name: ipykernel
Version: 5.4.3
Summary: IPython Kernel for Jupyter
Home-page: https://ipython.org
Author: IPython Development Team
Author-email: ipython-dev@scipy.org
License: BSD
Location: c:\users\abc\appdata\local\programs\python\python38\lib\site-packages
Requires: ipython, tornado, traitlets, jupyter-client
Required-by:

**Comment by joyceerhl** [comment]
Thanks. This part of the log seems suspicious, it looks like we managed to drop a backslash in the filepath to our isolate script somehow:
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\ABC.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"


What do you get if you run these two commands:

1. > C:\Users\ABC\AppData\Local\Programs\Python\Python38\python.exe c:\Users\ABC.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
2. > C:\AppData\Local\Programs\Python\Python38\python.exe c:\Users\ABC\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"

Thank you for your patience!

**Comment by RajatM24** [comment]
Well when trying first command i get 
`can't open file
c:\Users\ABC.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles
\pyvsc-run-isolated.py': [Errno 2] No such file or directory`
when running second i get
`The system cannot find the path specified.`

**Comment by RajatM24** [comment]
well there is no support and i have gone to other platform so i am closing this

**Comment by cpoptic** [comment]
Yep this ipykernel issue is ridiculous (there are multiple issues on Github) and without any resolution.
