### ISSUE TITLE
Delete, Copy or Paste multiple cells

### ISSUE THREAD

**Issue by noppGithub** [microsoft/vscode-jupyter#4422]
In Jupyter notebook, you can select multiple cells and then you can choose to Delete, Copy or Paste those selected cells.
It would be great if this feature available in VSCODE.

**Comment by joyceerhl** [comment]
Thanks for the feedback @noppGithub. This requires https://github.com/microsoft/vscode/issues/114156. We would likely also address this alongside https://github.com/microsoft/vscode-jupyter/issues/1227.

**Comment by noppGithub** [comment]
> Thanks for the feedback @noppGithub. This requires [microsoft/vscode#114156](https://github.com/microsoft/vscode/issues/114156). We would likely also address this alongside #1227.

Thank you so much
