### ISSUE TITLE
Jupyter notebook incorrect indentation with argument specified on first line of function/class

### ISSUE THREAD

**Issue by dstanner** [microsoft/vscode-jupyter#4425]
## Environment data

-   VS Code version: 1.52.1
-   Extension version (available under the Extensions sidebar): v2020.12.424452561
-   OS and version: Windows Server 2019 Datacenter v1809
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7 (miniconda)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: VS Code Python Jupyter notebook
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

Indentation within function/class argument list aligns with opening paren after an argument has been specified on the first line.

![image](https://user-images.githubusercontent.com/34904658/105099119-014b3b80-5a60-11eb-9b0b-ef71c33cd6dd.png)

## Actual behaviour

Indentation goes to left margin.

![image](https://user-images.githubusercontent.com/34904658/105099173-16c06580-5a60-11eb-841b-c01dfbdf8b29.png)

Note that standard Python code editor (not notebook) behaves as expected:

![image](https://user-images.githubusercontent.com/34904658/105099416-80d90a80-5a60-11eb-8aee-968471a6dd53.png)

Also, within notebook cells the indentation behavior without an argument on the first line also behaves as expected:

![image](https://user-images.githubusercontent.com/34904658/105099641-db726680-5a60-11eb-810c-f2438019596a.png)

## Steps to reproduce:

See example images above

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
User belongs to experiment group 'AlwaysDisplayTestExplorer - control'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonJoinMailingListVar3'
User belongs to experiment group 'pythonSendEntireLineToREPLcf'
User belongs to experiment group 'pythonNotDisplayLinterPrompt'
> conda --version
> pyenv root
> python3.7 c:\Users\otterpie\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 c:\Users\otterpie\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 c:\Users\otterpie\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 c:\Users\otterpie\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\otterpie\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.7 c:\Users\otterpie\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.6 c:\Users\otterpie\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3 c:\Users\otterpie\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -2 c:\Users\otterpie\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Miniconda\envs\cseai_page\python.exe c:\Users\otterpie\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Starting Pylance language server.
Python interpreter path: C:\Miniconda\envs\cseai_page\python.exe
> conda info --json
> conda info --json
> conda info --json
> conda info --json
> conda env list
> conda info --json
> conda info --json
> conda env list

```

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the issue. This will be addressed when we switch to using the new VS code API (which you can preview by installing the VS code insiders build).
