### ISSUE TITLE
connects to wrong kernel when connected to remote Jupyter server

### ISSUE THREAD

**Issue by phrenesis3000** [microsoft/vscode-jupyter#4427]
When connected to jupyterlab (on localhost:8888) with multiple kernel, the cell does not get executed by specified kernel (selecting Jupyter from right pulldown in cell and selecting kernel from bottom right pulldown).
Image shows when I selected the kernel named "julia" (sorry for confusing name. it is a python kernel).

<img width="1136" alt="Screen Shot 2021-01-21 at 1 14 19" src="https://user-images.githubusercontent.com/77741396/105206171-69497100-5b89-11eb-986e-0d583603e2d6.png">

## Environment data

-   VS Code version:
Version: 1.53.0-insider
Commit: 4d0d36c6ab154d841263c8d223a4bd1b9af07a23
Date: 2021-01-20T09:14:00.924Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.2.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.1.0-dev (commit: 27cfffe12b414ecc25715d5edd7ac89edead09bc)
-   Python Extension version (available under the Extensions sidebar): v2021.2.497453231-dev
-   OS (Windows | Mac | Linux distro) and version: Mac (macOS 11.1 (20C69))
-   Python and/or Anaconda version:

```
$ conda info
     active environment : base
    active env location : /Users/user/miniconda3
            shell level : 1
       user config file : /Users/user/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/user/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/user/miniconda3/pkgs
                          /Users/user/.conda/pkgs
       envs directories : /Users/user/miniconda3/envs
                          /Users/user/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.5 Darwin/20.2.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Remote

## Expected behaviour

evaluated cell:
```
import sys
print(sys.executable)
```
cell output:
```
/Users/user/projects/julia/.venv/bin/python
```

## Actual behaviour

cell output:
```
/Users/user/miniconda3/bin/python
```

## Logs

[jupyter_lab.log](https://github.com/microsoft/vscode-jupyter/files/5843841/jupyter_lab.log) (log from jupyter lab --debug)
[vscode.log](https://github.com/microsoft/vscode-jupyter/files/5843843/vscode.log) (log from Output(Jupyter) with jupyter.logging.level: info set)

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

</details>

**Comment by rchiodo** [comment]
Thanks for the bug. Can you tell me what this is set to?

```json
"jupyter.jupyterServerType": ""
```

It's odd that you'd be getting jupyter lab output when using VS insiders version. It doesn't currently support connecting to a remote host. It might be you have a hybrid of things happening (an unsupported scenario at the moment).

**Comment by phrenesis3000** [comment]
It is set to remote in User's setting and Workspace's setting.
```
"jupyter.jupyterServerType": "remote"
```

**Comment by rchiodo** [comment]
Sorry that's not supported at the moment. If you want to connect to your own jupyter server, you have to use the VS code stable version.

**Comment by phrenesis3000** [comment]
I understand.
Thank you for letting me know.
