### ISSUE TITLE
hover doen not work in jupyter notebook when use pylance server

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/vscode-jupyter#4432]
## Environment data
version: 1.52.1 (user setup)
commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

##issue screen
![image](https://user-images.githubusercontent.com/33288114/102730114-667f1480-436e-11eb-83fa-69eaa222f495.png)

**Comment by rchiodo** [comment]
This is actually a dupe of #4218. Should be fixed in the next release.
