### ISSUE TITLE
User prompted to select a kernel when running a cell immediately after opening a notebook even if one is set in metadata

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4440]
This is a known issue and has been around for a while.
The problem is VS Code is not waiting to get the list of kernels from extension, and when user runs a cell, VS Code doesn't have the kernel list, hence displays the kernel Picker UI.

**How to repro**
* Open a notebook
* Run a cell immediately
* You'll get a prompt to select a kernel

Upstream https://github.com/microsoft/vscode/issues/108950

**Comment by joyceerhl** [comment]
Validated. Opened an existing notebook and immediately ran a cell, and I wasn't asked to select a kernel.
