### ISSUE TITLE
Add command to support for Paste cell above current cell

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4441]
Blocked by upstream https://github.com/microsoft/vscode/issues/114720

Hacky work around posted here https://github.com/microsoft/vscode/issues/114720#issuecomment-764826535
Will wait for feedback from VSC.

**Comment by DonJayamanne** [comment]
Not sure this is a blocker for Feb, but @claudiaregio added this list as a blocker (but these are new features, hence not sure about priority of this particular issue).

**Comment by rebornix** [comment]
FYI https://github.com/microsoft/vscode/issues/114720#issuecomment-790291099, we already have this command.

**Comment by IanMatthewHuff** [comment]
Validated. Command is there and works like a charm:
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/7a41de7f-b8a1-421a-b797-d806ec0cab0e)
