### ISSUE TITLE
Creating new notebook via VS Code UI should allow a default language to be set (currently always Plain Text)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4443]
* Create a new file with ipynb extension (not using our command)
* Add a cell
* Language of cell is `Plain Text`
https://github.com/microsoft/vscode/issues/114724

@claudiaregio /cc

**Comment by greazer** [comment]
A diary study user has already complained about this.

**Comment by greazer** [comment]
We can add a new cell based on last language used via our extension. (i.e. does not have to be solved by VS Code)

**Comment by rchiodo** [comment]
Validated.
