### ISSUE TITLE
RandomBytes test is falling over on windows

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4444]
Get this error consistently:

1) "after each" hook: closeActiveWindows for "Random bytes generation"

Exit code from Tests is 1
Killing VSC
Exiting with test failures
  1 passing (49s)
  1 failing
  1) Smoke Tests
       "after each" hook: closeActiveWindows for "Random bytes generation":
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (d:\a\vscode-jupyter\vscode-jupyter\out\test\smoke\datascience.smoke.test.js)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

**Comment by rchiodo** [comment]
Should be passing now. Same reason as run cells below test failure.

**Comment by IanMatthewHuff** [comment]
Random bytes test in smoke tests looks to be in and passing on all platforms in most recent main action runs. Validated.
