### ISSUE TITLE
Run cells below test seems to randomly fail

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4445]
Times out on after hook:

Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-jupyter/vscode-jupyter/out/test/datascience/notebook/notebookEditor.vscode.test.js)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by IanMatthewHuff** [comment]
Validated in most recent green main run. Run cells below test is in and passing.
https://github.com/microsoft/vscode-jupyter/runs/1779246981?check_suite_focus=true
