### ISSUE TITLE
Users opting into Experiments locally should also belong to same experiment when using VS Code remote

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4450]
Assume user opts into experiment A
Now spins up VS Code locally, they get features from Experiment A
Next, if the same user connects to WSL or remote SSH, they should get the same features from Expeirment A when on remote VS Code.

E.g. if they have Native Notebooks locally, they msut get the same experience in WSL, etc.
`scope` of `Application` might be whats required in package.json for the experiment setting.
Today the setting `"jupyter.experiments.optInto"` has its scope set to `machine`

**Comment by rchiodo** [comment]
Validated using WSL
