### ISSUE TITLE
Jupyter-notebook background-color not correct when connected via SSH

### ISSUE THREAD

**Issue by ctr26** [microsoft/vscode-jupyter#4457]
## Environment data

-   VS Code version: 1.53.0-insider
-   Extension version (available under the Extensions sidebar): v2021.1.502429796
-   OS and version: Macos
-   Python version (& distribution if applicable, e.g. Anaconda): 3,7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions:
-   Relevant/affected Python-related VS Code extensions and their versions:
-   Value of the `python.languageServer` setting:

## Expected behaviour

Vscode theme should be respected when using jupyter in python.

## Actual behaviour

SSH into a server, then use either ipynbs or ipython interactive cells which causes the VScode theme to be ignored.

## Steps to reproduce:

/\

**Comment by rchiodo** [comment]
Sorry but only the default themes are supported in a remote situation. 

If you use VS code insider's, this problem shouldn't happen though.

**Comment by ctr26** [comment]
I'm using vscode insiders

**Comment by rchiodo** [comment]
Can you share a screenshot?

**Comment by rchiodo** [comment]
The interactive window will still have this problem. Sorry should have mentioned VS code insiders only fixes it for notebooks.
