### ISSUE TITLE
Jupyter Variables tab is not named Jupyter Variables until you click on it

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4458]
It was confusing to me what it was for.

![image.png](https://images.zenhubusercontent.com/5bda265b648e32720db70349/a24699cd-51ca-4def-9e69-44ebd99e9973)

**Comment by DavidKutu** [comment]
I can't get a repro of this.

**Comment by joyceerhl** [comment]
Validated, although FYI @DavidKutu I'm still seeing the leading colon :( 
![image](https://user-images.githubusercontent.com/30305945/110262607-0f4e1080-7f69-11eb-9074-572617ba2b41.png)
