### ISSUE TITLE
Data viewer should clearly indicate when data is filtered

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#4462]
Originally from https://github.com/microsoft/vscode-jupyter/issues/1286#issuecomment-765306346:

> One thing on filtering pandas dataframes:
I can click on Filter Rows button and enter a condition in any of the white boxes that appear below the column names. The dataframe gets filtered in real time. But when I click again on teh Filter Rows button, the dataframe stays filtered. I'd expect that once the filters are masked, they are not applied. One could get confused unless he shows the filters.
My suggestion is that the filters gets applied only when the conditions are visible or, alternatively, add some indication that the dataframe is filtered even when the conditions are hidden.

**Comment by joyceerhl** [comment]
We added a clear filter button in https://github.com/microsoft/vscode-jupyter/pull/4805. Not sure if that addresses the ask here.

**Comment by IanMatthewHuff** [comment]
With the "clear filters" button and having to explicitly pick "hide filters" this feels resolved to me unless customers complain.
