### ISSUE TITLE
Finish dependency installation work

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4466]
Two steps

- Move to jupyter notebooks on kernel startup
- Remove from kernelSelector
- Move/remove `KernelExecution.validateKernel`  (this too is dependency validation & the like)
	- Some of it might be required as we validate the remote kernels (could be refactored)	
	- this might not be required as well, or perhaps is. But we check here as well for IPyKernel and other stuff.
	- This follows the same code path we have with KernelSelector (when using webview we validate), with notebooks we perform the same validation by calling the same method `useSelectedKernel`.
	- I attempted to remove this, but CI failled for non-raw. Meaning this block of code seems to be useful only in non-raw scenarios. I added  the code back.
	- The tests failing was usage of a kernel that didn't have ipykernel isntalled in it.
	- Meaning we are validating the dependencies fir non-raws in different code paths, we always assumed this was the case, this is a confirmation.

**Comment by greazer** [comment]
Reopen if there's still interesting stuff here. I can't tell.
