### ISSUE TITLE
Sample notebook from start page looks wrong on native notebook

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#4468]
Might just be vscode rendering differences, but might have to change the notebook or something as this looks rather lame, and it's a new user experience.

![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/d8699307-a7f6-4a1a-9e79-eddf63dd14d5)

**Comment by DavidKutu** [comment]
This is what it looks like:
![newStartPage](https://user-images.githubusercontent.com/20347396/106641814-7b89be80-653c-11eb-8362-c550b41196ca.gif)

**Comment by DonJayamanne** [comment]
Validated
