### ISSUE TITLE
MathJax does not render properly in Jupyter Notebook with Sagemath kernel.

### ISSUE THREAD

**Issue by SashaIr** [microsoft/vscode-jupyter#447]
I'm running a Jupyter Notebook with a SageMath kernel. By default, I use `%display latex` to have LaTeX-style outputs from my computations, which is rendered by MathJax.

When I use the notebook in a browser window, everything works fine. But when I use it in VSCode, then it does not render automatically: when I run a cell, I see no output, and I need to manually select any other LaTeX-style output (I can get some by executing any `%%latex` cell), manually select any math renderer, and then all the other outputs that were not showing before magically appear. I need to do this every time I run a cell. Is there any solution?

## Environment data

-   VS Code version: 1.51
-   Extension version: v2020.10.332292344
-   OS and version: Windows 10 Education
-   Python version: Python 3.7 in Sagemath 9.1

## Expected behaviour

Render math automatically after running a cell.

## Actual behaviour

Math is not rendered unless the renderer is manually reloaded.

## Steps to reproduce:

1. [Install a SageMath kernel](https://ask.sagemath.org/question/43240/sagemath-and-vscode/).
2. Open a new Jupyter Notebook.
3. Run `%display latex`.
4. Run `1+1`.

![image](https://user-images.githubusercontent.com/17984906/98585631-ddcd7d00-22c7-11eb-87fc-fe981d400518.png)

To render the math, run any `%%latex` cell.

![image](https://user-images.githubusercontent.com/17984906/98585691-f342a700-22c7-11eb-97c0-b3b5d9ac90a5.png)

**Comment by SashaIr** [comment]
Hi, I wanted to ask if there is any update about this issue. Thank you!

**Comment by SashaIr** [comment]
Hi, is there any progress about this bug?

**Comment by DonJayamanne** [comment]
Apologies for the delay in getting back to you.
This has been fixed, please feel free to install the latest VS Code Insiders version & test this out.
Closing as this has been fixed
The changes will be in the next release of VS Code & Jupyter (which is slated for next week).
