### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by toprakfirat** [microsoft/vscode-jupyter#4472]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2020.12.414227025`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.52.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 465,
		"activateCallTime": 14,
		"activateResolvedTime": 1464,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-toolsai.jupyter",
				"_lower": "ms-toolsai.jupyter"
			},
			"activationEvent": "onLanguage:python"
		}
	},
	"runtimeErrors": []
}
```

**Comment by claudiaregio** [comment]
Hi @toprakfirat 
Could you please provide some additional details on the issue you are experiencing? 
Helpful information includes steps to reproduce, expected behavior vs. actual behavior, pictures or screen recordings when applicable. (https://www.screentogif.com)
