### ISSUE TITLE
Scroll to a sensible position when collapsing long outputs (new jupyter extension of VSCode insiders)

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode-jupyter#4473]
Not sure whether to classify this as a bug, as it's more a UX issue than a real bug.

Currently, when collapsing a very long cell output (by doing right-click and then "collapse cell output"), it appears that the notebook retains the previous scroll coordinates.

This is an issue with long outputs, especially if they span more than the total screen height. In those cases, after collapsing the cell I often end up with a view of cells that are much further down in the notebook, forcing me to scroll up and waste time trying to find back where I was. 

It would probably make more sense to automatically scroll so that the cell whose output was collapsed is visible?

**Comment by claudiaregio** [comment]
Thanks @ldorigo, closing as this issue has been transferred. 
You can track updates here: https://github.com/microsoft/vscode/issues/114866
