### ISSUE TITLE
Native Notebooks - Variable explorer doesn't reset with kernel restart

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#4474]
### Steps to reproduce: 
1. Open notebook
2. Run cells
3. Open variable explorer
4. Restart kernel 

### Expected behavior
Variable explorer should be empty 

### Actual behavior 
Variables from last run remain 

I have to restart the kernel, clear all outputs, close and reopen the notebook

**Comment by rchiodo** [comment]
Dupe of #4492
