### ISSUE TITLE
Add option to disable automatic scrolling to next cell.

### ISSUE THREAD

**Issue by nasosev** [microsoft/vscode-jupyter#4475]
There is already an option "Always Scroll On New Cell** whose behavior is described:

_Automatically scroll the interactive window to show the output of the last statement executed. **If false, the interactive window will only automatically scroll if the bottom of the prior cell is visible.**_

But it should be possible to completely disable automatic scrolling (as is the default behaviour of Jupyter Lab). It is annoying when debugging as any error messages are automatically scrolled passed.

Lang: F#

Thanks

**Comment by DavidKutu** [comment]
Thanks for the request @nasosev. We'll discuss it in an upcoming meeting.

**Comment by Knifa** [comment]
Really looking out for this one too --- the scrolling doesn't seem to ever hit the right target for me as is.

**Comment by ravikumargrk** [comment]
I really need this

**Comment by rebornix** [comment]
This can now be disabled via `interactiveWindow.alwaysScrollOnNewCell`

**Comment by amunger** [comment]
that setting seems to not be working for me currently, created a separate issue: https://github.com/microsoft/vscode-jupyter/issues/11127
