### ISSUE TITLE
key binding of Markdown enter on macOS should command + enter instead of ctrl + enter

### ISSUE THREAD

**Issue by kgtkr** [microsoft/vscode-jupyter#4476]
![image](https://user-images.githubusercontent.com/17868838/105665477-84660900-5f1a-11eb-8dc5-73270162a734.png)

**Comment by DavidKutu** [comment]
Thanks for the request @kgtkr! We'll discuss it in an upcoming meeting.

**Comment by joyceerhl** [comment]
Closing as VS Code doesn't show that keybinding hint anymore.
