### ISSUE TITLE
The problem of math formula rendering in markdown block.

### ISSUE THREAD

**Issue by Fenyutanchan** [microsoft/vscode-jupyter#4478]
Now, I have found that the formula in $$ cannot be rendered correctly, such as
<img width="460" alt="image" src="https://user-images.githubusercontent.com/32387646/105710071-9020f200-5f51-11eb-90d1-91a02d51a1bb.png">.

Version of the Jupyter extension: v2020.12.414227025
VS Code Version: 1.53.0-insider
platform: Mac OS Big Sur 11.1

**Comment by DavidKutu** [comment]
Thank you for reporting this @Fenyutanchan. We are already following this issue here: #1216, and we'll roll it out as soon as its ready.

I'll be closing this as a dupe, but to get your math formulas working you could use stable VS code and use our webview implementation of notebooks.
