### ISSUE TITLE
Jupyter: Select a Kernel command missing in Python Interactive context

### ISSUE THREAD

**Issue by mparq** [microsoft/vscode-jupyter#4479]
Created out of discussion from #3724

## Environment data
-   VS Code version: 1.52.1
-   Jupyter Extension version (available under the Extensions sidebar): 2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): 2021.1.502429796
-   OS (Windows | Mac | Linux distro) and version: Mac 10.15.7 (Catalina)
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote (via local Docker)

## Expected behaviour

In Python interactive window, I should be able to select a kernel via Jupyter: Select a Kernel command.

## Actual behaviour

Command Palette does not show Jupyter: Select a Kernel in Python interactive context

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open up a `.py` file after connecting a remote notebook server to Jupyter extension and run cell. Python interactive window opens
2. Notice that command palette willl not contain Jupyter: Select a Kernel command. However, top right of interactive window will show UI for selecting different kernel on remote notebook server.
3. Export `.py` file to `.ipynb` and open in new window. Notice that command palette for notebook context does have Jupyter: Select a Kernel as an available command.

**Comment by DavidKutu** [comment]
Thanks for filing @mparq. I can confirm there is no command (even if not using remote). I'll bring it up in our next meeting.

**Comment by fohria** [comment]
I have the same issue for .ipynb files, with the additional bug that if I select kernel through the drop down list, nothing happens. It stays on the kernel in the conda environment I'm running the jupyter server from. 

If I select "Jupyter: Select kernel" from the command palette, after a few seconds I get a notification about an error:

<img width="393" alt="Screenshot 2021-02-18 at 18 13 51" src="https://user-images.githubusercontent.com/8695061/108394503-acd8de80-720c-11eb-8436-c38c06662290.png">

Running a line from a .py file to interactive window, opens a random kernel among the available conda environments available on the remote machine.

**Comment by DavidKutu** [comment]
Hi @fohria, could you please open a new issue? This seems to be something else going wrong.

**Comment by IanMatthewHuff** [comment]
Validated.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/dabf52cc-6831-47e7-a08c-6dac41499138)
