### ISSUE TITLE
Hover Documentation Pop up box never appears in notebook file

### ISSUE THREAD

**Issue by janice5tian** [microsoft/vscode-jupyter#448]
## Environment data

-   VS Code version: 1.51.0
-   Extension version (available under the Extensions sidebar): V2020.10.332292344
-   OS and version: win10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5 Anaconda
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: Jupyter
-   Relevant/affected Python-related VS Code extensions and their versions: v2020.10.332292344
-   Value of the `python.languageServer` setting: Jedi

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour
While in a jupyter notebook,
On hover, showing document window in HTML formatting (with headers, etc)

Like on a regular .py file:
![image](https://user-images.githubusercontent.com/39750141/98499652-2299db00-2218-11eb-9044-c7c67b2a908b.png)

## Actual behaviour

value of modules? shows up on hover
![image](https://user-images.githubusercontent.com/39750141/98499591-f8e0b400-2217-11eb-9973-12b060432d23.png)

## Steps to reproduce:

You can see the two example files, with minimal content in screenshots above.

## Logs

No output as it's the editing interface.

**Comment by greazer** [comment]
@janice5tian please reactivate if pylance doesn't work for you.

**Comment by janice5tian** [comment]
thank you! didn't know this was a language server problem. Issue has been resolved by installing the Pylance VSCode extension 👍
