### ISSUE TITLE
Reimplement insiders build for jupyter extension

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4480]
Not sure how we do this but have had a least one customer request for this.

**Comment by DonJayamanne** [comment]
**Solution:**
* Implement solution proposed by VSCode
* Update `engine` in `package.json` in the insiders VSIX to point to the latest VS Code insiders version
* Push this vsix to marketplace (before the official release)

**Comment by rchiodo** [comment]
Shouldn't we close this after it's automated?

**Comment by DonJayamanne** [comment]
Yes, agreed
