### ISSUE TITLE
Display line numbers in cell

### ISSUE THREAD

**Issue by ecorro** [microsoft/vscode-jupyter#4483]
I opened this request at the VS Code Insiders GitHub but the admins told me that enabling line numbers in each cell is up to the extension's developer. So I hope this is the right place to request this. At the moment, even if you select "on" at the "Editor: Line Numbers" dropdown, you get nothing in Jupyter notebooks. Thank you.

**Comment by DavidKutu** [comment]
Thank you for filing @ecorro. We are currently following this issue here: #1200. I'll close this as a dupe and we'll get it up as soon as its ready.
