### ISSUE TITLE
Variable explorer doesn't update list of hidden variables when docked vertically.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#4485]
VS Code Insiders with Jupyter extension from main.

1. Open or create a new notebook (native notebook)
2. Add this code to a cell but don't execute yet.
```python
import time
t0 = time.perf_counter()
t1 = time.perf_counter()
t2 = time.perf_counter()
t3 = time.perf_counter()
t4 = time.perf_counter()
t5 = time.perf_counter()
t6 = time.perf_counter()
t7 = time.perf_counter()
t8 = time.perf_counter()
```
3. Open the variable viewer -> Jupyter: Open Jupyter Variable View
4. Drag and dock the viewer to the left panel.
5. Size the Variable Viewer as short as possible.
6. Execute the above cell
7. Drag the bottom of the Variable View down to reveal all the tx variable. You'll only see the first 4. The rest will say "Loading..."

**Comment by joyceerhl** [comment]
Is there supposed to be an icon? It's not showing for me, I spent a couple minutes hunting for it after docking it to the left panel.

Apart from that, seems to work now.

**Comment by IanMatthewHuff** [comment]
Nope, no icon. Mostly because I've always been working with it in the bottom view panel where it doesn't really need one. I'll file a new issue and loop with Claudia about getting one.
