### ISSUE TITLE
Use existing ipykernel instead of installing in every python environment

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#449]
With zmq work, we won't need clients to do anything, just pick interpreter, done.
We should be able to do this for todays approach as well.
~Or just install in user home directory using `--user`, this way it will be available to all interpreters and we won't have to do anything, if we find it great, else we just install no difference.~
* Also check how spyder handles this.

**Comment by greazer** [comment]
Probably not doing this. If we do, we'll have good reason and won't really need this bug to track it.
