### ISSUE TITLE
Handle kernel restarts correctly with the variableview

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#4492]
Correctly handle kernel restarts with the variable view

**Comment by joyceerhl** [comment]
This is kind of weird. If I open the data viewer from the variable view, switch back to the notebook, and request a cell restart, the variable view fails to clear even after the restart:

![restart](https://user-images.githubusercontent.com/30305945/106097587-6b14b680-60ec-11eb-85c3-abf2b8ee0b7e.gif)

Works fine as long as you don't open the data viewer though.

**Comment by IanMatthewHuff** [comment]
@joyceerhl Good catch. I'll pull this back to in progress and investigate.

**Comment by DonJayamanne** [comment]
Validated
