### ISSUE TITLE
In Julia notebook, the exponential symbol is not interpreted properly

### ISSUE THREAD

**Issue by AronT-TLV** [microsoft/vscode-jupyter#4493]
## Environment data

-   VS Code version: 1.53.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): 2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): 2021.2.510221908-dev
-   Pylance Extension version 2021.1.2
-   OS (Windows | Mac | Linux distro) and version: OS X 11.1
-   Python and/or Anaconda version: 3.7.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

2^2 should be 4

## Actual behaviour

2^2 is 0

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Put the above code in a Jupyter cell and run
2. If you put 2**2 you get the correct result
3. If you put 2^2 in a Julia terminal (RePL) you get the correct result

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DavidKutu** [comment]
Thanks for filing @AronT-TLV. I'm able to get the expected result on my Julia notebook:
![image](https://user-images.githubusercontent.com/20347396/105780354-1b37c300-5f25-11eb-9be4-2d6829cb54a8.png)

I should also add, that running `2**2` gives me a syntax error.

What Julia kernel are you using?

**Comment by AronT-TLV** [comment]
After I got your response, I began to think maybe I'm not understanding this completely. To test, I opened up an interactive notebook. I had to choose the kernel I was using and then I noticed on the bottom it lists it:

![Screen Shot 2021-01-26 at 17 59 31](https://user-images.githubusercontent.com/22121571/105870270-c5384d80-6000-11eb-98c4-6fc9cc0fcf9c.png)

When I went back to the original notebook, you can see it says it's a Julia cell, and thats what confused me. And you see I get 0. But the problem is that it is actually running Python:

![Screen Shot 2021-01-26 at 18 05 37](https://user-images.githubusercontent.com/22121571/105870907-6f17da00-6001-11eb-81b7-92cad64908f8.png)

When i switched the kernel to Julia it worked. So this isn't really a bug, just a confusing UX. 

My apologies for imposing on your time.

Thanks for a great product!

**Comment by DavidKutu** [comment]
Glad it worked!
