### ISSUE TITLE
Jupyter and Notebook are prefixed in front of similar commands

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4494]
![image](https://user-images.githubusercontent.com/19672699/105768204-e588df00-5f10-11eb-8a59-db230ed08361.png)

I believe we should:

a) Have a consistent prefix - I'd suggest ```Notebook```
b) Not have two commands that do the same thing 

  Example:
     Execute Cell & Run Current Cell

**Comment by greazer** [comment]
We just need to be careful not to change interactive window commands.

**Comment by greazer** [comment]
Also fix #4545 as part of this.

**Comment by IanMatthewHuff** [comment]
Validated. Everything notebook now:
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/ca9dd236-4bc3-4d6c-be44-4b63319dd5c7)
