### ISSUE TITLE
Create outline based on cells

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#4496]
The outline under explorer just lists all the variables. I believe it would be more helpful if a long file could be outlined based on 
cells.

For example, if you have a file:
```python
# %% -----------------
# load data

# %% -----------------
# clean data
``` 
The outline could be:
load data
clean data

**Comment by DavidKutu** [comment]
Thanks for the suggestion @StevenLi-DS. I'll bring it up in our next meeting.

**Comment by GitHunter0** [comment]
@StevenLi-DS , @jadiator,  let's campaign here microsoft/vscode-python#17218

**Comment by DonJayamanne** [comment]
Upstream issue in Python extension https://github.com/microsoft/vscode-python/issues/17218

**Comment by amunger** [comment]
closing in favor of the python issue
