### ISSUE TITLE
Can't save a Python notebook with caps on

### ISSUE THREAD

**Issue by Drarig29** [microsoft/vscode-jupyter#4502]
## Environment data

-   VS Code version: 1.52.1
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.502429796
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: Python 3.8.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Can save a Python notebook when the caps lock is on.

## Actual behaviour

Can't save a Python notebook when the caps lock is on.

## Steps to reproduce:

1. Create a new blank Jupyter Notebook
2. Write anything just to be able to save
3. Enable the caps lock with your keyboard
4. Try to save with Ctrl+S, or save as with Ctrl+Shift+S (same result via the menu)

## Logs

No log at all is added when I try to save. Nothing is triggered.

## Note

- I can save the changes when closing the tab, thanks to the prompt about unsaved changes.
- My VS Code isn't broken. Saving works with other types of file. Only notebooks encounter this bug.

**Comment by DavidKutu** [comment]
Thanks for filing @Drarig29. I was able to repro this behavior on the webview notebook. We'll discuss this in an upcoming meeting. In the meantime, this issue is not present on the new native notebooks, You can try it out if you use VS Code Insiders. (https://code.visualstudio.com/insiders/)

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Feel free to try the new experience in VS Code Insiders. The new experience is the default.
