### ISSUE TITLE
Plotly does not resize when editor resizes

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4506]
Issue Type: <b>Bug</b>

Originally reported in 

* Open two editor groups side by side
* Create a plotly output
* Close the other editor group
* Editors are resized but the ploty output is not. Check that the webview is resized properly

Extension version: 2021.1.499599561-dev
VS Code version: Code - Insiders 1.53.0-insider (51d19635946a76d2f9007f9e4f4db1c26a0ebfae, 2021-01-25T19:37:36.530Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (12.22GB free)|
|Process Argv|--crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2prompt:30219162
vstry914:30244316
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt875:30247033
core-portspanel:30233467
coreuntitledfile:30249963

```

</details>

**Comment by IanMatthewHuff** [comment]
@rebornix Thanks for filing this Peng. Just to check are you using the old renderers extension? Did didn't think that plotly was currently working with the current bits. @DonJayamanne Is plotly expected to render currently? I'm getting an error loading preloads message right now.

**Comment by DonJayamanne** [comment]
@IanMatthewHuff 
sorry i missed this question

> 'm getting an error loading preloads message right now.

Yes it should.

**Comment by DonJayamanne** [comment]
Been 2 years an no one has reported this issue and we've had just one upvote on this, hence closing this
