### ISSUE TITLE
When executing a second native notebook, Execution notification is sometimes messed up

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#4507]
Open two native notebook files side by side (not sure if SxS is needed, but it seems to help)
1. Execute file 1
2. Execute file 2

Since it's a bit hard to describe here is a picture of the state.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/570ea7fd-fa73-4215-9648-78d7319cf98c)

The cell appears to execute, but the execution count is not updated, and the green check never shows up. I noticed as the variable view was not updating (as an new execution order doesn't seem to be sent). This situation occurs about...15-20% of the time that I do the given scenario. Seems like this might be experiment blocker? So tagging GA for now.

**Comment by greazer** [comment]
Closing for verification
