### ISSUE TITLE
Notebook icon problems

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-jupyter#4508]
From @tyriar on https://github.com/microsoft/vscode/issues/115094#issue-794406334

- Export as and open jupyter variable view looks really bad on standard dpi
- Not enough contrast on the green icons, we shouldn't be using color at all yet blue, green and red are used

![image](https://user-images.githubusercontent.com/2193314/105877963-65688500-5fb5-11eb-80f3-1ea2761d099e.png)

- Run cell and below and run cells above do not show up initially, you need to focus another cell to get it to show up

![image](https://user-images.githubusercontent.com/2193314/105878217-a3fe3f80-5fb5-11eb-8235-34e08a4edb7f.png)

- Trusted is red initially and then it turns green when opening - this should be green from the beginning to reduce visual noise

**Comment by IanMatthewHuff** [comment]
@misolori Agreed. Both of those icons are brought over from the old view and don't match up well.

**Comment by greazer** [comment]
I believe all this is moot at this point.
