### ISSUE TITLE
Don't ask for a survey when you're already hammering users with notifications

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#4509]
I just installed jupyter recently, the amount of notifications I'm getting hit with by both python and jupyter is intense. Asking to fill out a survey after that isn't very tasteful:

![image](https://user-images.githubusercontent.com/2193314/105883593-e3c82580-5fbb-11eb-80d4-8e25828e9330.png)

cc @devinvalenciano

Related: https://github.com/microsoft/vscode/issues/115108

**Comment by IanMatthewHuff** [comment]
@Tyriar Thanks for filing, and yes, totally agree. With the split of the Jupyter and Python extensions you can now get notifications from Python, Jupyter, and Pylance language server I believe.

**Comment by greazer** [comment]
This survey only appears after you have opened a notebook 5 times or ran 100 cells. So this scenario shouldn't be common.

**Comment by devinvalenciano** [comment]
Any data to support what proportion of users are experiencing this?

**Comment by Tyriar** [comment]
Ping @greazer
