### ISSUE TITLE
Issues with cell execution

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4514]
* Run all cells
* Try to interrupt multiple cells
* Run more cells while others are running

When trying the above, you can see that things dont work as expected
Initially reported by Jim (hopefully I have identified the cause & can fix)

**Comment by DonJayamanne** [comment]
Tests to add:
* Run cell with ipykernel not installed
	* Steps:
		* Should get prompt to install ipykernel, click cancel
		* Run cell again, should get prmopt to install ipyknerke again
	* Same as previous, but run whole document
	* Same as previous, but run one cell, then whole document
	* Same as previous, but run whole document then one cell
* Run cell 1 & cell 2
	* Cell 2 should have errors in code
	* Run a validate the status of cells
	* Run the cells again, again cell 2 should fail
	* Run the first cell, confirm it ran again
	* Run cell 3 & confirm it runs without errors
	* This is to ensure we don't cache failures...
	* Found plenty of scenarios where cells wouldn't run again
* Run cell 1, 2, 3, 4 individuall
	* Ensure they run in order
* Run cell 3, 1, 4, 2 individually (random order)
	* Ensure they run in order (randomize the order of the cells executed & confirm execution count generated matches the order of submission for execution)
* Run cell 1
	* Run cell 2
	* Confirm both cells have a busy icon
* Run notebook	
	* Add and run new cell
	* Confirm all cells including the new one has a busy icon
* Run a notebook
	* Ensure second cell has errors
	* Confirm 1 is a success & 2 has errors & rest do not run
	* Verify status of all cells (found while testing some cells end up with busy icon even though they finish)
	* I think we have a test for this (update to test status of all cells).	
* Run a notebook
	* Ensure second cell is a long running cell
	* Interrupt execution
	* Confirm 1 is a success & 2 has completed (interrupted or passed successfully) & rest do not run
	* Second cell could be error state if interrupted or success if interrupt failed & it got restated
	* Verify status of all cells (found while testing some cells end up with busy icon even though they finish)

**Comment by rchiodo** [comment]
Seems to be working as expected? I can run all cells and interrupt. I can interrupt more than once, and interrupting stops all queued executions.
