### ISSUE TITLE
Jupyter resolves wrong notebook data for git resource

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4520]
## Environment data

-   VS Code version: VS Code Insiders
-   Jupyter Extension version (available under the Extensions sidebar): 2021.1.499599561-dev
-   Python Extension version (available under the Extensions sidebar): N/A
-   OS (Windows | Mac | Linux distro) and version: Mac Big Sur
-   Python and/or Anaconda version: 2.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: LOCAL

Originally reported in https://github.com/microsoft/vscode/issues/115042 by @jrieken 

Testing https://github.com/microsoft/vscode/issues/114969

* added the plotly.txt-based notebook, file as untracked
* open diff editor, everything is new
* commit the file
* close editors
* reopen notebook, delete a cell
* open diff
* :bug: diff shows old/stale information

<img width="1338" alt="Screenshot 2021-01-26 at 14 38 17" src="https://user-images.githubusercontent.com/1794099/105852148-5fd66380-5fe4-11eb-916c-c98d285de308.png">

Jupyter doesn't resolve the right notebook data for 

```
Uri {scheme: "git", authority: "", path: "/c:/Users/rebor/code/vscode-notebook-testdata/bugreports/plotly.txt.ipynb", query: "{"path":"c:\\Users\\rebor\\code\\vscode-notebook-testdata\\bugreports\\plotly.txt.ipynb","ref":"~"}", fragment: "", …}authority: ""fragment: ""path: "/c:/Users/rebor/code/vscode-notebook-testdata/bugreports/plotly.txt.ipynb"query: "{"path":"c:\\Users\\rebor\\code\\vscode-notebook-testdata\\bugreports\\plotly.txt.ipynb","ref":"~"}"scheme: "git"_formatted: "git:/c%3A/Users/rebor/code/vscode-notebook-testdata/bugreports/plotly.txt.ipynb?%7B%22path%22%3A%22c%3A%5C%5CUsers%5C%5Crebor%5C%5Ccode%5C%5Cvscode-notebook-testdata%5C%5Cbugreports%5C%5Cplotly.txt.ipynb%22%2C%22ref%22%3A%22~%22%7D"_fsPath: nullfsPath: (...)__proto__: URI
```

**Comment by rchiodo** [comment]
@rebornix do you have any more information? I'm not sure what your expecting the jupyter extension to do? Is there a problem in reading the plotly output? Or is there a problem in reading the ipynb contents itself?

**Comment by rebornix** [comment]
@rchiodo I expect the notebook content provider to provide the right `notebookdata` but now it's giving me out of date cell data.

**Comment by rchiodo** [comment]
@rebornix I'm not reproing but maybe I'm not doing the same thing as you.

1. Created a notebook with plotly in it
2. Run a plot
3. Checked in changes
4. Deleted plot
5. Opened diff

I get this:

![image](https://user-images.githubusercontent.com/19672699/106210205-3996fc00-617b-11eb-994c-82f198e84052.png)

Looks correct to me. 

Can you be more explicit in what parts are not matching?

**Comment by rchiodo** [comment]
Blech. I had a situation where it looks like I repro'd it but reloading VS code and I can't get a problem to occur. It looked like the contents of the file were from an older revision? Is that what you were seeing?

**Comment by rchiodo** [comment]
Okay I think I was able to repro but I don't think this is our problem. 

These steps repro

1) Write notebook with some cells in it
1) Commit
1) Delete notebook
1) Commit
1) Add notebook with one cell
1) Commit
1) Write notebook with some cells in it that are different than step one.
1) Open diff

Diff should show difference between step 5 and 7 but actually shows diff between 1 and 7.

Looking in the debugger it looks like VS code never actually calls us with the git-resource. Not sure how it gets the model for the old notebook.
