### ISSUE TITLE
Markdown table poorly displayed

### ISSUE THREAD

**Issue by orion160** [microsoft/vscode-jupyter#4524]
When using jupyter notebooks in vscode, the tables in markdown are displayed in a ugly way, in which even with a few rows and columns, it  is intelligible.

There is no proper formating for the table, there are not hints for separate different rows, and there are not lines that separate the content.

Example

![image](https://user-images.githubusercontent.com/61389980/106028017-725ea480-6099-11eb-9915-e34e5fd83442.png)

**Comment by rchiodo** [comment]
Thanks for the bug. Do you have the LaTeX code that generates that table? I'd like to see what Jupyter outputs.

This likely won't be fixed until this item is resolved:

https://github.com/microsoft/vscode-jupyter/issues/1216

**Comment by orion160** [comment]
This is what jupyter notebook displays
![image](https://user-images.githubusercontent.com/61389980/106071495-6ba15300-60d4-11eb-933d-02bb9e2ae0c2.png)

The difference is in the spacing and visual hints, like the bars, and the color hint in each row.

**Comment by rchiodo** [comment]
Can you share the LaTeX that generates the output?

Might be a problem with which output we're picking. That looks like jupyter is picking 'text/html' instead of 'text/latex'.

**Comment by orion160** [comment]
![image](https://user-images.githubusercontent.com/61389980/106071758-e8ccc800-60d4-11eb-93c0-8b238b79420f.png)

**Comment by orion160** [comment]
I dont see any correspondence with the issue #1216 

without using latex, jupyter native notebooks are layed out in  a poor format.

vscode notebook
![image](https://user-images.githubusercontent.com/61389980/106072040-71e3ff00-60d5-11eb-83b1-4d76d828b2c0.png)


jupyer notebook

![image](https://user-images.githubusercontent.com/61389980/106072238-d1daa580-60d5-11eb-9597-8fd7f2c7411c.png)

**Comment by orion160** [comment]
Overall native jupyter notebooks is a big enhancement, no more to say lets wait to it to leave the insiders channel
