### ISSUE TITLE
Extension host terminated uexpectedly when using ipywidgets.Fileupload

### ISSUE THREAD

**Issue by beralves** [microsoft/vscode-jupyter#4525]
## Environment data

-   VS Code version: 1.52.1
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.502429796
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

ipywidgets.Fileupload should work on vscode while running the notebook. Fileupload works if I launch "jupyter notebook" in the command and run my notebook there. It would be helpful to run it inside vscode, to avoid context switching and use debug features.

## Actual behaviour

ipywidgets.Fileupload crashes extension host on vscode while running the notebook. I get the message "Extension host terminated uexpectedly."

## Steps to reproduce:

1. Create a notebook and include an ipywidgets.Fileupload. Run the cell, it displays fine. Click "upload", select the file you would like to upload. When you click "OK" to close the file browser dialog you get the error message.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the bug. We haven't tried using FileUpload before, but we'll see if we can repro with it.

**Comment by rchiodo** [comment]
Yep crashes the host for me too. Just do this:

```python
widgets.FileUpload(accept='', multiple = False)
```

Then click on the Upload button and pick a text file. Extension host will die

**Comment by rchiodo** [comment]
Looks to me like a message buffer being to big. Callstack for crash is here:
```
postToSocket (d:\Source\vscode-jupyter\src\client\datascience\raw-kernel\rawSocket.ts:230)
(anonymous function) (d:\Source\vscode-jupyter\src\client\datascience\raw-kernel\rawSocket.ts:222)
VM_Unknown (undefined:97)
[ Promise.then ]
sendMessage (d:\Source\vscode-jupyter\src\client\datascience\raw-kernel\rawSocket.ts:221)
sendToRealKernel (d:\Source\vscode-jupyter\src\client\datascience\raw-kernel\rawSocket.ts:104)
sendPendingMessages (d:\Source\vscode-jupyter\src\client\datascience\ipywidgets\ipyWidgetMessageDispatcher.ts:354)
sendRawPayloadToKernelSocket (d:\Source\vscode-jupyter\src\client\datascience\ipywidgets\ipyWidgetMessageDispatcher.ts:142)
receiveMessage (d:\Source\vscode-jupyter\src\client\datascience\ipywidgets\ipyWidgetMessageDispatcher.ts:109)
receiveMessage (d:\Source\vscode-jupyter\src\client\datascience\ipywidgets\ipyWidgetMessageDispatcherFactory.ts:42)
onMessage (d:\Source\vscode-jupyter\src\client\datascience\ipywidgets\commonMessageCoordinator.ts:106)
(anonymous function) (d:\Source\vscode-jupyter\src\client\datascience\ipywidgets\notebookIPyWidgetCoordinator.ts:88)
fire (event.ts:623)
onDidReceiveMessage (extHostNotebook.ts:44)
$onDidReceiveMessage (extHostNotebook.ts:612)
_doInvokeHandler (rpcProtocol.ts:409)
_invokeHandler (rpcProtocol.ts:394)
_receiveRequest (rpcProtocol.ts:310)
_receiveOneMessage (rpcProtocol.ts:246)
(anonymous function) (rpcProtocol.ts:105)
```

**Comment by rchiodo** [comment]
The ZMQ library is crashing trying to send the data to client.

**Comment by beralves** [comment]
Hi, any plans for this issue? I'm happy to test if needed.

**Comment by rchiodo** [comment]
There are no plans to fix this at the moment. We generally wait for more feedback before prioritizing. 

A workaround might be to start your own jupyter server and set it as the 'remote' URI to connect to. That should use a different communication mechanism to send the data to the kernel then. I haven't tried it though.
