### ISSUE TITLE
Native notebook shortcut commands are applying in edit more, or at least 's' is

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#4527]
Create a new cell. Type 'ssssss' into the cell. With each s typed you can see the File menu activating quickly and the file saving. More noticeable in an untitled notebook as it pops up the save as dialog. 
![SaveButton.gif](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/a68cfe28-2c52-40e4-b3f2-1332128f1a43)

**Comment by rchiodo** [comment]
Does this still repro for you? I think we moved it to validate to see if anybody else could repro? Doesn't repro for me.

**Comment by IanMatthewHuff** [comment]
I do still repro it. How about I'll assign myself and see again today if I can lock down a solid reason why it's happening.

**Comment by DavidKutu** [comment]
Also can't repro

**Comment by DonJayamanne** [comment]
Validated.
