### ISSUE TITLE
Copying with CMD+C in cell output sometimes copies cell contents

### ISSUE THREAD

**Issue by pbotros** [microsoft/vscode-jupyter#4528]
## Environment data

Version: 1.53.0-insider
Commit: 1a9dd758530782ee4bb09a15bdc484f3dcb9b5a3
Date: 2021-01-26T05:12:23.287Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
-   Python and/or Anaconda version: 3.7
-   Jupyter server running: Local 

## Expected behaviour

Highlighting any part of a Jupyter cell's output then pressing Cmd+C should copy the highlighted text.

## Actual behaviour

Highlighting a part of a Jupyter cell's output and then pressing Cmd+C _sometimes_ copies the cell's code contents. This happens pretty often for me in larger more complicated notebooks. Notably, it seems that clicking Edit > Copy copies the right thing.

## Steps to reproduce:

1. Create a new jupyter notebook.
2. Make a Python code cell and put in:
```
print('This is output')
print('This is output')
```
3. In the output, select immediately after the "is" on the first line to the second "is" on the second line, inclusive. See GIF.
4. Press Cmd+C.
5. Open any other text editor, and Cmd+V. The cell contents with `print(...)` are instead copied.

See attached GIF for repro illustration. Note in the GIF where manually clicking Edit > Copy works properly as does Cmd+C when copying another part of the output, but the GIF includes two other instances of using Cmd+C that do not work properly and instead copy the code.

![copying](https://user-images.githubusercontent.com/773285/106060561-113ecd00-60a9-11eb-90bf-e6b488a74c73.gif)

</details>

**Comment by rchiodo** [comment]
Thanks for the issue. I believe this issue would actually be handled by VS code as they're controlling the copy.

**Comment by rchiodo** [comment]
Issue moved to [microsoft/vscode #115278](https://github.com/microsoft/vscode/issues/115278) via [**ZenHub**](https://www.zenhub.com/)
