### ISSUE TITLE
Notebooks - Timer Issues

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4532]
Originally reported in https://github.com/microsoft/vscode/issues/114232

Steps to Reproduce:

1. Open notebook
2. Run some cells 
3. Re-run cells
4. Watch timers

Issues: 
1. Sometimes timer for multiple cells runs at the same time - I would expect the timer for one to start only after the previous has completed
2. After running cells once, the timer starts at random strange values. If I continued running the cells the timer for the second cell would start at 10 seconds or 80 seconds or 100 seconds etc - I would expect the timer to start from zero again each time
![Timer Off](https://user-images.githubusercontent.com/19276747/104382540-1dd8f800-54e3-11eb-8ca9-95ec7f9cb1dd.gif)

**Comment by DonJayamanne** [comment]
Fixed, to be validated.

**Comment by rchiodo** [comment]
Validated
