### ISSUE TITLE
Ctrl+Z affects cell timer state

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#4535]
Originally from https://github.com/microsoft/vscode-jupyter/issues/1682

Validated that Ctrl + Z no longer hangs the kernel. However we are now unsetting the execution time for the cell. I don't think we should be doing that and IIRC the extension controls this. See GIF below where I run a cell, then press Ctrl+Z a bunch of times:

![undo](https://user-images.githubusercontent.com/30305945/106095843-5682ef00-60e9-11eb-9336-e704e02b814d.gif)

**Comment by DonJayamanne** [comment]
Valdiated
