### ISSUE TITLE
Math rendering in Markdown cell not working at all

### ISSUE THREAD

**Issue by kjohnsen** [microsoft/vscode-jupyter#4537]
A very simple problem. I start a notebook, put inline or display math in a cell, and "execute" with ctrl+alt+enter. The raw code is displayed instead of rendered math.

$ f(x) = 42$
$$ e^x $$

## Environment data

-   VS Code version: 1.53.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): 2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.18363
-   Python and/or Anaconda version: 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

To see rendered math in the notebook editor after executing markdown cell.

## Actual behaviour

I see un-rendered math.

## Logs

Nothing.

**Comment by rchiodo** [comment]
Sorry but LaTeX is not currently supported in the insiders version. See this bug for more information:
#1216
