### ISSUE TITLE
Variable view needs an icon

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#4538]
Doesn't currently have one. This is fine if it's in the panel, but docked in the explorer it looks wrong. @claudiaregio do we have something that we can use here? I can loop with Jill if needed.

**Comment by IanMatthewHuff** [comment]
There also might be a bigger discussion here about having a general Jupyter sidebar, and if variables should just be docked there by default. We can chat at triage.

**Comment by rchiodo** [comment]
Woot! Looks great:

![image](https://user-images.githubusercontent.com/19672699/107837093-2cba0100-6d54-11eb-9e61-4911cb39b76f.png)
