### ISSUE TITLE
Viewing data from a conda kernel when non conda is the active interpreter does not work

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4540]
1. Create (or install) python venv
1. Set this as your python interpreter (open a python file if you have to)
1. Create conda env
1. Open notebook
1. Set its kernel to the conda env
1. Add something that you can view with the data viewer
1. Try to view it
1. It will ask to install pandas
1. Pandas install will fail

**Comment by rchiodo** [comment]
You can work around the problem if you set the active interpreter to the conda environment.

**Comment by DonJayamanne** [comment]
IPyKernel install into conda doesn't work.

**Comment by DonJayamanne** [comment]
Found the problem is due to a bug upstream in Python extension - https://github.com/microsoft/vscode-python/pull/15286

**Comment by DonJayamanne** [comment]
Install latest dev version of Python extension.

**Comment by rchiodo** [comment]
Validated.
