### ISSUE TITLE
Variables tab does not update when running a new cell if it's not visible

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4541]
1. Run some cells in a notebook with variables
2. Open variable viewer
3. Switch to another output (hide variable viewer)
4. Add new cell with new variable
5. Switch back to variable viewer

Expected result:
Variable shows up

Actual result:
Variable is not there. Variable list seems to have previous execution list.

**Comment by IanMatthewHuff** [comment]
Hmm, maybe this is the same as you were seeing, but this is actually a bit odder than I thought. I checked the messages coming in, and they are getting fetched with the correct execution order, and coming back with the correct variables. 

To get them to show up, I don't actually even have to execute anything more, just moving my mouse over the control makes them show up. Not quite what I expected.

**Comment by DonJayamanne** [comment]
Validated
