### ISSUE TITLE
Variables tab gets in the way of using the terminal

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4544]
If I need to look at a terminal an a variable value at the same time, I can't.

Usage example: I open an ipython console to connect to my notebook in order to play around with data. I'm trying to executing something that requires one of the variables. I need to see both at the same time.

Dragging the variables to say the file panel is weird. It'd be nice if there was a 'jupyter' tab.

**Comment by amunger** [comment]
this is supported now
