### ISSUE TITLE
Ensure that all Azure ML compute users are opted into native notebooks

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#4550]

**Comment by rchiodo** [comment]
How do we validate this? Do we need to remote into an azure compute instance?

**Comment by rchiodo** [comment]
@SiddhanthUnnithan do you have directions on how to use the remote support?

**Comment by DonJayamanne** [comment]
> How do we validate this? Do we need to remote into an azure compute instance?

Yes, sorry i missed this.
Setup AML Compute.
Open in VS Code stable, upload the VSIX to the AML Compute & install that VSIX using the command palette & reload VS Code.

**Comment by rchiodo** [comment]
I'm hitting this, but it seems like it at least loads the native editor

```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found
```

And for some reason jupyter notebook doesn't work.
