### ISSUE TITLE
Notebook toolbar doesn't appear when first opening a notebook

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4552]
Not sure who's fault this is:
![image](https://user-images.githubusercontent.com/19672699/106213565-d6f52e80-6181-11eb-82b3-0785ef4927fe.png)

**Comment by kevball2** [comment]
I am also seeing this issue,
Jupyter build: v2020.12.414227025 (Insiders Channel: Daily)
Python: v2021.1.502429796
Pylance: v2021.2.0   
Insiders Build: 1.53.0
OS: 10.0.21301

**Comment by rchiodo** [comment]
The workaround is to give a cell focus.

**Comment by kevball2** [comment]
Even with a cell in focus, the notebook toolbar does not appear for me or maybe I do not know what I should be seeing. From the recent VScode days preview of the insiders build it looks like the toolbar that should be there never activates 

![image](https://user-images.githubusercontent.com/22545150/106930937-b6762880-66db-11eb-8e03-53d2eacb53d6.png)

**Comment by astrowonk** [comment]
> Even with a cell in focus, the notebook toolbar does not appear for me or maybe I do not know what I should be seeing. From the recent VScode days preview of the insiders build it looks like the toolbar that should be there never activates
> 
> ![image](https://user-images.githubusercontent.com/22545150/106930937-b6762880-66db-11eb-8e03-53d2eacb53d6.png)

Same for me. I never see the toolbar regardless of what I do with a cell.

**Comment by rchiodo** [comment]
The toolbar is at the upper right. On VS code insiders that's the limit of what is available. It should have:

- Run all
- Clear all Cell outputs
- Export 
- Restart kernel

**Comment by rchiodo** [comment]
In my screenshot it only has the run all and clear all outputs.

**Comment by astrowonk** [comment]
> The toolbar is at the upper right. On VS code insiders that's the limit of what is available. It should have:
> 
> * Run all
> * Clear all Cell outputs
> * Export
> * Restart kernel

Wait, what happened to the data viewer, variable inspector, and the gather feature [all demoed last week on Youtube](https://www.youtube.com/watch?v=g5EykzAsCC0) on the VS code channel?

**Comment by rchiodo** [comment]
> @rchiodo Wait, what happened to the data / dataframe viewer, variable inspector, and the gather feature all demoed last week on Youtube on the VS code channel?

Sorry but the bits that @claudiaregio was using haven't shipped yet.

**Comment by astrowonk** [comment]
> > @rchiodo Wait, what happened to the data / dataframe viewer, variable inspector, and the gather feature all demoed last week on Youtube on the VS code channel?
> 
> Sorry but the bits that @claudiaregio was using haven't shipped yet.
> 
> That's our next release which should be coming up in the couple of weeks.

Ah-ha! Ok, sorry for the confusion. Insiders isn't as Insider-y as I thought.

**Comment by DonJayamanne** [comment]
Upstream https://github.com/microsoft/vscode/issues/118996

**Comment by joyceerhl** [comment]
Upstream issue has been closed. Can we close this?

**Comment by DonJayamanne** [comment]
> Upstream issue has been closed. Can we close this?

once validated, yes

**Comment by DonJayamanne** [comment]
Closing as validated.
