### ISSUE TITLE
Variables don't need to list type aliases

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4553]
![image](https://user-images.githubusercontent.com/19672699/106213871-7c100700-6182-11eb-8ebd-7b2a2d456360.png)

The code to generate these 'variables' is this:

```python
from typing import List

Vector = List[float]

height_weight_age = [70,  # inches,
                     170, # pounds,
                     40 ] # years

grades = [95,   # exam1
          80,   # exam2
          75,   # exam3
          62 ]  # exam4
```
At least I wouldn't expect Vector or List to be variables.

**Comment by DonJayamanne** [comment]
Closing this issue as we haven't had any upvotes on this.
