### ISSUE TITLE
Preferred kernel spec not used when running a notebook

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4556]
* Use Jupyter (raw kernels disabled)
* Ensure notebook has metadata pointing to a kernel spec named 'xyz'
* Ensure a kernel spec named 'xyz' has been registered as a kernel
* Open this notebook in webview notebooks
	* UI displays the kernel spec `xyz` as the kernel on the top right hand corner
	* Run the cell `import sys; sys.executable`
	* The preferred kernel is NOT selecetd, it just uses the default interpreter as the kernel
* Open this notebook in native notebooks
 	* UI displays the kernel spec `xyz` as the kernel on the bttom right hand corner
	* Run the cell `import sys; sys.executable`
	* The preferred kernel is NOT selecetd, it just uses the default interpreter as the kernel

Seems to be broken, i can't see how this would have worked.

**Comment by DonJayamanne** [comment]
This is a bug introduced as part of passing kernel connection metadata

**Comment by rchiodo** [comment]
This is still reproing in the old webview.

**Comment by rchiodo** [comment]
Native notebooks do not repro.

**Comment by rchiodo** [comment]
Looks like customer reported this too:
#4682

**Comment by IanMatthewHuff** [comment]
Looking at validating this now. Currently I'm seeing some issues, trying to tell if it's new issues or not a full fix here.

**Comment by IanMatthewHuff** [comment]
Ok, the issue that I'm seeing is something different. I can validate this issue.

Validated.
