### ISSUE TITLE
Does Jupyter notebook in VS Code insiders have "Variable explorer and data viewer" function.

### ISSUE THREAD

**Issue by Jill-Cheng** [microsoft/vscode-jupyter#4560]
In VS Code we can use the "Variable explorer and data viewer" function, and the Jupyter notebook in VS Code insiders has better "IntelliSense" and other functions.

Is there a "Variable explorer and data viewer" function in Jupyter notebook in VS Code insiders.
For example: 

![image](https://user-images.githubusercontent.com/61971386/106243659-b7730a00-6244-11eb-88c9-b5eca40b9d2e.png)

Thanks a lot!

**Comment by claudiaregio** [comment]
Hi @Jill-Cheng , this is on the way! Planning to have this in Feb
