### ISSUE TITLE
Create a new experiment for the custom editor

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4561]
Ensure it doesn't conflict with Native Notebooks, see discussion (Jim) here https://teams.microsoft.com/l/message/19:9b163ad1e1ed4c49938d9692be1ce751@thread.skype/1611862176803?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=6182cd1a-acf2-40e6-8b08-07bd25990df8&parentMessageId=1611784871932&teamName=Python%20for%20VS%20Code&channelName=Data%20Science&createdTime=1611862176803

**Comment by greazer** [comment]
We're not going to bother with Custom Editor. Native Notebooks is too close.
