### ISSUE TITLE
VariableView goes away if you switch off of an active notebook context

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#4562]
Right now the VariableView is keyed to having an active notebook context. And it's keyed to being unavailable without one. This leads to some UI annoyance with it. Take the following scenario.

Open a notebook A
Execute it
Open the variable panel
Open the data viewer (or move to a native notebook that has not been executed yet)
Move back to notebook A in the editor

The variable view is still available and has the right info. But since we moved to a context that hid it, it's not open by default when you move back to the document.

I think there is an easy fix here. Instead of enablement of the view when there is an active notebook running, it should just be enabled when there is a native notebook editor (with or without an active notebook / kernel) open at all in the editor.

**Comment by DavidKutu** [comment]
Its extra annoying if you open settings.

**Comment by joyceerhl** [comment]
Validated. Opened a blank notebook, created some variables, opened the data viewer and verified that the variable view stayed open, opened another blank notebook, created some variables, verified that variable view updated to match the active notebook, switched back to the first blank notebook, verified that variable view updated, and verified that the variable view only went away after closing all notebooks.

**Comment by joyceerhl** [comment]
FYI @DavidKutu I'm still seeing the leading colon :( 

![image](https://user-images.githubusercontent.com/30305945/110262477-ae263d00-7f68-11eb-8834-3ec50306e83b.png)
