### ISSUE TITLE
Implement h (help) command

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-jupyter#4565]
Accessibility for new users, this should bring up all the keyboard shortcuts (a, b, dd) for notebooks.

**Comment by claudiaregio** [comment]
Thanks @DavidKutu , will discuss at our team's next triage meeting!

**Comment by DonJayamanne** [comment]
Isn't the existing keyboard shortcuts command sufficient. 
Either way if we were to implement our own help command then I vote we just bring up the VS Code keyboard shortcuts (or the like) 

![Screen Shot 2021-01-29 at 09 59 45](https://user-images.githubusercontent.com/1948812/106310762-ea9fa400-6218-11eb-9884-5e23e2136f40.png)

**Comment by DonJayamanne** [comment]
Closing as duplicate of https://github.com/microsoft/vscode-jupyter/issues/1307
