### ISSUE TITLE
IPython.get_ipython().set_next_input does not work

### ISSUE THREAD

**Issue by arradha** [microsoft/vscode-jupyter#4566]
The ` IPython.core.interactiveshell.InteractiveShell.set_next_input` function does not work. Without this function, it is impossible to implement magic commands that alter the contents of the current or the next cell.

## Environment data

-   VS Code version: 1.52.1
-   Jupyter Extension version: v2020.12.414227025
-   Python Extension version: v2021.1.502429796
-   OS and version: Windows 10
-   Python and/or Anaconda version: Python 3.6
-   Type of virtual environment used: N/A
-   Jupyter server running: Local

## Expected behaviour

On running 
```
import IPython
IPython.get_ipython().set_next_input("print('This goes in the next cell')")
```
The expected behaviour is that a new cell is created below the current one with the contents `print('This goes in the next cell')`. 

## Actual behaviour

No cell new is created and call to `set_next_input` fails silently.

## Steps to reproduce:

1. Create a new notebook
2. Enter the above fragment in the first cell and run the cell.

**Comment by claudiaregio** [comment]
HI @arradha, able to repro this issue. Will discuss at next triage meeting

**Comment by IanMatthewHuff** [comment]
This is an internal ask that I have some context on. Will discuss on Monday.

**Comment by IanMatthewHuff** [comment]
https://jupyter-client.readthedocs.io/en/stable/messaging.html#payloads-deprecated

https://github.com/jupyter/notebook/blob/083df1bf5eb0513fde4451e7ffc11e0a36db9bc7/notebook/static/notebook/js/codecell.js#L392

Looks like supporting this will also support the %load magic. And maybe others. Look for the message and then use the VSCode API to either edit or add cells.

**Comment by rchiodo** [comment]
Validated.
