### ISSUE TITLE
Variables are not sortable.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4585]
I know we never implemented this, but being able to click on the 'Name' column seems kinda crucial.

**Comment by IanMatthewHuff** [comment]
Agree :(. I do think that after this is rolling out to stable I want to take a good long look at what the AZNB team did with their variable view. Might be better to sync up with them as opposed to sinking more time into this.

**Comment by IanMatthewHuff** [comment]
Fixed by Vandy
