### ISSUE TITLE
Support language features for other languages when using cell magics

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4588]
I would like to run bash scripts in a cell.
I use cell magics for this.
I would like the langauge of the cell to be automatically set to `bash`

Similarly when using %html, %%svg, etc...
%%script julia
%%html
%%kql

Provides intellisense, syntax highlighting & the like (ie. use VS Code features to improving cell editing experience for non-python & non-markdown cells)

Additionally we should make sure all of the languages supported by magics. This includes things like:
- Q# #10772

**Comment by greazer** [comment]
Related to https://github.com/microsoft/vscode/issues/140147.

**Comment by ahmed2m** [comment]
I hope you're planning for sql too, it's so annoying as of the current state, yesterday I changed every cell. When I opened the same notebook today all the types are reset to Python!

**Comment by Photonico** [comment]
I expect this feature will be realized soon. :)
Could you tell me any progress?

**Comment by rchiodo** [comment]
Sorry this isn't on our radar at the moment.

**Comment by Photonico** [comment]
> Sorry this isn't on our radar at the moment.

Hi,

Do you have a plan to fix this problem?

For example, I use both Python and Julia in one Jupyter notebook. I found that clicking the lower right button of the cell can demonstrate the menu which controls the syntax highlighting. I guess that If Julia option would be added to the menu, the problem gets solved.

![pic](https://raw.githubusercontent.com/Photonico/Problems/master/2022/Screenshot_20220316_062224.png)

However, I prefer this feature to be a native of Jupyter extension.

**Comment by Photonico** [comment]
> This issue is about autodetecting cell magics that change the language. The plan is to make the language change automatically as you type a cell magic. It's not a high priority at the moment but will likely be addressed eventually.
> 
> What you're describing is more of a polyglot kernel. The jupyter extension has no plans for a polyglot kernel. However .NET interactive does. A polyglot kernel would likely support ALL languages in that dropdown. @DonJayamanne also mentioned another polyglot kernel in your [discussion ](https://github.com/microsoft/vscode-jupyter/discussions/9364) of this topic.
> 
> The IPython kernel supports only a subset of languages based on known cell magics that can change the language from python to something else. It seems julia is possible in that list though with the julia.magic extension: https://stackoverflow.com/questions/24091373/best-way-to-run-julia-code-in-an-ipython-notebook-or-python-code-in-an-ijulia-n. So when we implement this feature, we should add julia to the list.

Julia language should be added to the menu. However, I still need to change the cell language every time I open the notebook. 
It is better that the call can identify the language of the cell automatically according to the statement: `%%script julia`.

**Comment by RafalSkolasinski** [comment]
One more use case that seems not mentioned, 

If there would be for example
```
%%writefile myfile.yaml
some: field
other: field
```
it'd be nice if it could be detected that this is yaml syntax.

**Comment by nicocanali** [comment]
> This issue is about autodetecting cell magics that change the language

Instead of autodetecting, which might be tricky, would it be possible to allow a custom mapping? For example, I have a Kusto syntax highlighting extension that would be great to autoswitch when `%%kql` appears in a cell. Similarly, there may be non-standard names (like `%%bigquery`) that would nicely map to SQL, but might be tricky to do it automatically...so letting the user map it through a setting could work...? WDYT?

**Comment by DonJayamanne** [comment]
Created an upstream issue https://github.com/microsoft/pylance-release/issues/4969 
That would be a better solution, as pylance natively supports notebooks

**Comment by DonJayamanne** [comment]
Closing in favour of upstream issue https://github.com/microsoft/pylance-release/issues/4969
