### ISSUE TITLE
Display errors against the actual code (squiggles, etc) instead of just displaying the error as cell output (Native Notebook)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4589]
Run a cell with errors, & i get the details of the error in the output.

I would like a deeper integration with VS Code so that I see the error  in the cell itself.
Else it still feels like i'm using a terminal, running code in a terminal, looking at the output & then translating that output error & looking at my editor to find that faultly code.

I'm using VS Code for because i like its editor features, but this still feels very much like compiling code in a terminal.

**Comment by rchiodo** [comment]
We do some of this in the interactive window with our links. 

Does normal python do this for debugging? I guess the callstack window provides the location.

**Comment by DonJayamanne** [comment]
@IanMatthewHuff i think this falls under execution and errors, not intellisense, let me know if thats ok

**Comment by DonJayamanne** [comment]
Closing as out of scope, not requested by anyone and no upvotes
