### ISSUE TITLE
Jupyter interactive plots are very slow / laggy when opened in separate tab (e.g seaborn pairplot)

### ISSUE THREAD

**Issue by sws144** [microsoft/vscode-jupyter#459]
https://github.com/microsoft/vscode/issues/101238#issue-646955985

**Comment by NargesChinichian** [comment]
Same here. Mac, Big Sur

**Comment by mcpeixoto** [comment]
Same here, Ubuntu 20.04 LTS

**Comment by IanMatthewHuff** [comment]
Defaulting to PNG should help resolve this, so closing.
