### ISSUE TITLE
Allow me to ignore variables in the variables list

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4590]
Use case: I have a bunch of 'helper' variables in my variables list. It takes too long to find the stuff I want.

Alternatively a filter might work.

**Comment by IanMatthewHuff** [comment]
We have a Variable Explorer Exclude list, but I'd think we're looking at something in the actual control here.

**Comment by IanMatthewHuff** [comment]
Dupe against #1525 (add ignore in that one)
