### ISSUE TITLE
.env file is ignored in a notebook and the interactive window

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4593]
Created a .env file like so:

```
MYGOOFVAR=GOOF
```

Ran some code like so:
```python
print(os.getenv("MYGOOFVAR"))
```

MYGOOFVAR is not printed out.

**Comment by greazer** [comment]
This may be a regression. Joyce, please check to see if it repro's on Windows.

**Comment by joyceerhl** [comment]
Repros on Windows for me.

**Comment by DonJayamanne** [comment]
Cannot repro when debugging, brilliant..

**Comment by greazer** [comment]
Based on other bugs we have on .env file use that indicate that the file is indeed being read and processed, this clearly must be a regression.

**Comment by greazer** [comment]
Not getting upvotes or duplicate complaints. Therefore, it's either NOT a regression or even if it is, it doesn't affect many people. Moving to July for now.

**Comment by chart-magnum** [comment]
I have this issue as described in https://github.com/microsoft/vscode-jupyter/issues/7926

**Comment by DonJayamanne** [comment]
Fixed as part of https://github.com/microsoft/vscode-jupyter/pull/9018
Closing to get this tested

**Comment by joyceerhl** [comment]
Verified:

![image](https://user-images.githubusercontent.com/30305945/155784947-2f16815f-928c-4206-aea2-10683c292c00.png)

**Comment by giswqs** [comment]
I  just ran into the same problem. When should be `.env` file be saved to?

**Comment by giswqs** [comment]
Nevermind. I figured it out. The `.env` file needs to be put in the root directory. https://github.com/microsoft/vscode-jupyter/issues/10928
