### ISSUE TITLE
Hide command `Select  Interpreter to start Jupyter Server` if Raw kernels work

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4594]
Do we need this if raw kernels work?
Is this used for exports & the like?

If not, then we should hide this, had a user trying to use this to switch kernels.

**Comment by IanMatthewHuff** [comment]
It is used for nbconvert at a minimum. Maybe a rename? We talked a bunch about installing a single version of nbconvert, ipykernel, ect... on disk to use at one point. That seems like it would be the full fix here. But it's a pretty big work item.
