### ISSUE TITLE
Create and show intro native notebook

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#4600]

**Comment by DonJayamanne** [comment]
**Question:** Is this for just those that fall into the experiment & have RUN a cell in a Notebooks before?

I don't think we should consider users who just opened a notebook & never ran a cell.
Python users who get the Notebook start page could fall into this category (extension opened start page for them, & they never ran a cell).

Please could you confirm @claudiaregio

**Comment by claudiaregio** [comment]
Yes correct, this should be surfaced to people who have run a cell before and should only be displayed once.

**Comment by rchiodo** [comment]
What would be the validate steps for this? Should it just open if I've already run a notebook? 

Is this only for the stable version?

**Comment by rchiodo** [comment]
This doesn't seem to be working. Unless I'm misunderstanding the conditions for it to start.

**Comment by rchiodo** [comment]
Validated.
