### ISSUE TITLE
set remote Jupyter server URL when opening VS Code from CLI

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#4601]
When opening VS Code from the command line, how would I set the remote Jupyter server URL at the same time?

I did not see any option here: https://code.visualstudio.com/docs/editor/command-line 

Extension version: 2020.12.414227025
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.69GB free)|
|Process Argv|--crash-reporter-id f652528b-5678-4b12-9ca0-3de6b1e1135f|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by IanMatthewHuff** [comment]
Hey @clayms just making sure that I understand the scenario here. You're looking to start up vscode from the command line, but you'd like to vary the specified remote Jupyter server each time you start it? Right now, the URL is stored in a secret cache which we set via the command, so I don't believe there is a way to do this currently, it's not just a loose setting that you could edit before startup. 

I believe that right now you would have to run the command and then reload. We're currently looking at our options moving forward for improving our remote support, we know the restart and the single global setting is not optimal.

**Comment by clayms** [comment]
@IanMatthewHuff you got it.  That is exactly what I want to do.  Looks like I will have to wait.
Thanks.

**Comment by IanMatthewHuff** [comment]
@clayms If you don't mind I'll reactivate this. Just to check in our triage meeting in case anyone on the team knows a way around this.

**Comment by clayms** [comment]
No problem.

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time. We may revisit in the future if we get more feedback along these lines.
