### ISSUE TITLE
Add a button to the prompt `Select an interpreter to start Jupyter`

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4607]
Bug - as the user was confused & didn't know what to do.

Today when ZMQ fails, we display a message `Select an Intepreter to Start Jupyter`.
We should probably add a button to this prompt, so users can click on the button and address the issue.
Else user could assume that they need to just selecet a plain python interpreter (which is confusing to users - this has been proven to be confusing).

**Comment by DonJayamanne** [comment]
With the refactoring of how we handle errors, I don't think this will happen anymore.
Moving to validate.

**Comment by IanMatthewHuff** [comment]
Validated. I blew away my interpreter and disabled ZMQ and wasn't seeing this issue.
