### ISSUE TITLE
Notebook trust warning is an error

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4614]
Originally reported: https://github.com/microsoft/vscode/issues/115070

Error = something unexpected/bad happened

![image](https://user-images.githubusercontent.com/2193314/105873236-1f5cf280-5fb0-11eb-8184-8f0030f05e61.png)

**Comment by rchiodo** [comment]
I believe this is what we want. Untrusted notebooks should be an exceptional case.  Triage to review.

**Comment by greazer** [comment]
Using a warning will cause the notification to disappear after 30 seconds. This is not acceptable for this message.
