### ISSUE TITLE
Would you like to install Python extension doesn't state why a user would want to

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4615]
Originally reported: https://github.com/microsoft/vscode/issues/115074

Consider rephrasing to something like this:

> Would you like to install the Python extension to enhance the editing experience?

![image](https://user-images.githubusercontent.com/2193314/105873588-7ebb0280-5fb0-11eb-99a3-c7f5dd468e14.png)

**Comment by greazer** [comment]
We need to more strongly insist that the Python extension gets installed. Otherwise there is functionality that will just not work.

**Comment by DonJayamanne** [comment]
I don't think the current message is strong enough. Its still a question for the user for enhanced editing experience. When in fact its required for proper functioning of notebooks.

E.g. interrupt will not work without Python extension, etc. Similar there could be a lot of other issues.
I think we should change the message from a question to a recommendation. Right now we're just letting the user know `hey it will give you better editing experience, yes or no`
When it should be `Please install this to get Python notebooks working properly`.

Moving back to backlog.

**Comment by claudiaregio** [comment]
"Installation of the Python Extension is strongly recommended when working with Python notebooks. For the most seamless experience, would you like to install now?" 

Keep all same options (yes, no, do not show again)

**Comment by DonJayamanne** [comment]
Validated
