### ISSUE TITLE
Plot context menu doesn't show click feedback for Save as SVG/PNG only

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4616]
Originally reported https://github.com/microsoft/vscode/issues/115076

![recording (33)](https://user-images.githubusercontent.com/2193314/105874240-38b26e80-5fb1-11eb-8769-261554c5411b.gif)

**Comment by rchiodo** [comment]
This would be an issue for altair. They provide the javascript that creates that UI.
