### ISSUE TITLE
Only save as SVG works in plot context menu

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4617]
Originally reported https://github.com/microsoft/vscode/issues/115077

All other items do nothing:

![recording (33)](https://user-images.githubusercontent.com/2193314/105874334-4ec02f00-5fb1-11eb-95e7-3b2a370002a1.gif)

**Comment by greazer** [comment]
We're going to wait for an external customer to enter this to consider addressing it. Thanks!
