### ISSUE TITLE
Python KeyboardInterrupt was unexpected

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4621]
Originally reported by @Tyriar : https://github.com/microsoft/vscode/issues/115085

This might just be how it works, but it's a bit weird that it says KeyboardInterrupt here instead of what I expect actually happened (infinite loop detection?). I didn't touched the keyboard to cause it to happen.

![image](https://user-images.githubusercontent.com/2193314/105876898-3dc4ed00-5fb4-11eb-9bec-6f6cef032f22.png)

**Comment by rchiodo** [comment]
This is how stop works in a jupyter cell. It sends an interrupt to jupyter. It's the same as hitting CTRL+C in the command line.
