### ISSUE TITLE
Errors are repeated in notebook status bar

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4622]
Originally reported https://github.com/microsoft/vscode/issues/115100

This seems like redundant noise:

![image](https://user-images.githubusercontent.com/2193314/105879995-ae213d80-5fb7-11eb-80a2-872265926fec.png)

![image](https://user-images.githubusercontent.com/2193314/105880009-b37e8800-5fb7-11eb-9593-489aaa42972c.png)

**Comment by greazer** [comment]
If the cell is not trivial or contains an exception, this is not redundant, but useful.
