### ISSUE TITLE
New notebook markdown renderer can't display <code> tags

### ISSUE THREAD

**Issue by JorickvdHoeven** [microsoft/vscode-jupyter#4627]
Issue Type: <b>Bug</b>

The new notebook markdown renderer skips text wrapped in code tags. An example is: 

`
'<h4 id="create_data_model" class="doc_header"><code>create_data_model</code><a href="__main__.py#L2" class="source_link" style="float:right">[source]</a></h4>\n\n> <code>create_data_model</code>(**`file_name`**:`str`=*`None`*, **`location`**:`Path`=*`None`*)\n\nCreates an SQLite database with the appropriate tables for use in \nmanaging the data intake process.\n\nThis will not destroy a pre-existing database file.\n\nParameters\n----------\nfile_name : str, optional\n    Name of the database file defaults to \'intake_db\'\n    \nlocation : Path, optional\n    Location where to save the db file, by default current working directory'
`

which starts rendering as of: "(**`file_name`**:`"

<img width="660" alt="Screen Shot 2021-02-02 at 9 18 35 PM" src="https://user-images.githubusercontent.com/1242401/106688510-3e551900-659c-11eb-8e75-26112256f516.png">

It should show:

<img width="749" alt="Screen Shot 2021-02-02 at 9 20 35 PM" src="https://user-images.githubusercontent.com/1242401/106688659-8411e180-659c-11eb-8b64-9fbc9bad263c.png">

Extension version: 2021.1.502429796
VS Code version: Code - Insiders 1.53.0-insider (8d779a4fadaadec06b44b8875a1d3c4adba8e380, 2021-02-02T16:34:06.213Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (1.61GB free)|
|Process Argv|--crash-reporter-id 2333cb5f-f1d8-41ca-aca6-c0148ccfa9c5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2promptcf:30219163
vstry914:30244316
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt600cf:30251589
core-portspanel:30233467
coreuntitledfile:30249963

```

</details>

**Comment by rchiodo** [comment]
Sorry but in the insiders version only basic markdown is currently supported. See this issue for more information (and when we might get more things supported):
https://github.com/microsoft/vscode/issues/106701
