### ISSUE TITLE
Outsized toolbar when running Python scripts in a smaller window

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode-jupyter#4628]
When a VSCode window is resized to be smaller, all of the toolbar items are retained at the expense of crowding out actual Python output, which seems like a mistake.  In particular, the screen real estate allocated to relatively unimportant information like the current Python kernel label seems far too large.

<img width="483" alt="Screen Shot 2021-02-03 at 9 51 30 AM" src="https://user-images.githubusercontent.com/81476/106772388-93794500-6605-11eb-9c06-eedae0990304.png">

Is it possible to hide these altogether, or at least make them smaller?

**Comment by rchiodo** [comment]
Sorry about the toolbar being too big. There's no way to change it at the moment. We'll consider it in a future revision though.

**Comment by greazer** [comment]
Yes, we will consider in a future version as there are plans to somewhat redesign part of the interactive window.

**Comment by fonnesbeck** [comment]
Thanks, that would be great if there was a rethink of this. As you can see, its not difficult to cause the toolbar to take up most of the available space:

<img width="726" alt="Screen Shot 2021-02-25 at 5 26 40 PM" src="https://user-images.githubusercontent.com/81476/109232933-a6a7ac80-778e-11eb-8b99-ffa7802fd044.png">

**Comment by relishyeah** [comment]
Hey there, this constitutes a serious accessibility problem for low vision users such as myself. I generally use the extension full screened to better read the text, but I am limited by what I can have on my screen besides the toolbar.

Some potential suggestions that would improve my experience, in order of significance

1. Allow the user to fully hide the toolbar from the settings, similar to `"jupyter.mainToolbar.visible": false`
2. Stop the little icons on the left side of the toolbar from  line wrapping
3. Allow the toolbar to be resized with the mouse

Thank you for your time

![image](https://user-images.githubusercontent.com/25086688/111234166-5a4cd100-85c4-11eb-9f24-5f59b046d9b2.png)

**Comment by rchiodo** [comment]
@relishyeah The notebook UI is actually being redesigned. You might want to try the [insiders ](https://code.visualstudio.com/insiders/) version of VS Code. It does not have this same problem.

The interactive window does still have this problem though.
