### ISSUE TITLE
Z command messes up entire python jupyter notebook

### ISSUE THREAD

**Issue by lucasthim** [microsoft/vscode-jupyter#4629]
This jupyter notebook functionality still sucks after 2 years. I just lost all my progress made for 3h because the freaking "Z" messed up my entire notebook. Seriously, you guys are better off without this functionaliy. This is not the first time this happens. Should I really be making backup files every five minutes?

**Comment by rchiodo** [comment]
Sorry to hear that Z messed up everything. 

Can you give us any more detail? What happened to the notebook?

**Comment by bblank70** [comment]
I have had a similar experience. Quite a few cells were converted to
markdown potentially and some cells re-arranged in order. Also, I'm not
sure if it's related but it may happen in tandem with a saving error
phenomenon. Despite ctrl+s to save vscode prompts to save.

I'll try and reproduce late this evening.

**Comment by lucasthim** [comment]
Hi, sorry for the delay.

The same events that happens to @bblank70 also happens to me. 

As far as I noticed, VS Code "gets lost" whenever I press "Z" more than once.  If I press Z only once, it reverses the last action and nothing wrong happens. However, if I press Z twice or more in a row, it messes up my entire notebook (code cells turn into commentary cells and vice-versa, code cells vanish, code blocks vanish, etc) and these actions cannot be undone.

Also, the Ctrl+S problem has happened to me quite a few times, but I'm not sure if it is indeed related.

Can someone else please confirm this behavior? I really love VS Code, but this bug is really a pain...

Thanks.

**Comment by lucasthim** [comment]
Still facing issues here. Yesterday I used the Z command to revert a couple cells right before I saved my file. 

I just realized that I literally lost all my progress made yesterday.

Does anyone have a work around for this faulty behaviour?

Thanks.

**Comment by rchiodo** [comment]
The recommendation is to use the insiders version of VS code instead. It's where our UI is moving to and has the most active development on it. 

If you use the insiders version of VS code, your UI will look a bit different but VS code will then handle CTRL+Z and Z commands and be aware of the undo stack. This should be more robust.
https://code.visualstudio.com/insiders/

We're slowly rolling this out for the stable version of VS code too.

**Comment by rchiodo** [comment]
This is the new UI:

![image](https://user-images.githubusercontent.com/19672699/109688656-61da9780-7b39-11eb-9664-33efd08a2cd0.png)
