### ISSUE TITLE
Order of Icons in Native Notebook toolbar is odd

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4632]
![Screen Shot 2021-02-03 at 13 07 20](https://user-images.githubusercontent.com/1948812/106809742-e44a6700-6620-11eb-8304-cea0f0d733fc.png)

**What is the expected order of icons**
1. Run All (added by vs code, when running all, this changes to `Stop`)
![Screen Shot 2021-02-03 at 13 13 28](https://user-images.githubusercontent.com/1948812/106810397-b9acde00-6621-11eb-9d84-97c1d5007977.png)

2. Clear output (added by VS Code)
![Screen Shot 2021-02-03 at 13 13 31](https://user-images.githubusercontent.com/1948812/106810396-b9144780-6621-11eb-8dd7-bae9b61e5c00.png)

3. Interrupt Kernel (added by us)
	Enabled only when cells are running (kernel is busy)
![Screen Shot 2021-02-03 at 13 13 33](https://user-images.githubusercontent.com/1948812/106810393-b9144780-6621-11eb-96d2-cb7fac315ea0.png)
4. Open Changes (added by VS Code - no idea why this is after our icon?)
![Screen Shot 2021-02-03 at 13 13 36](https://user-images.githubusercontent.com/1948812/106810391-b9144780-6621-11eb-85b8-d3ae7e2b4eaf.png)
5. Restart Kernel
	Enabled only when cells are running (kernel is busy)
![Screen Shot 2021-02-03 at 13 13 39](https://user-images.githubusercontent.com/1948812/106810390-b9144780-6621-11eb-9975-993844e5392d.png)
6. Run Cell Above
	Enabled only when any cell other than 1st is selected
![Screen Shot 2021-02-03 at 13 13 42](https://user-images.githubusercontent.com/1948812/106810389-b87bb100-6621-11eb-96f6-5581f256c5d5.png)
7. Run cell & below
![Screen Shot 2021-02-03 at 13 13 44](https://user-images.githubusercontent.com/1948812/106810388-b87bb100-6621-11eb-89d0-1d7ea099e381.png)
8. Variable viewer
![Screen Shot 2021-02-03 at 13 13 47](https://user-images.githubusercontent.com/1948812/106810387-b87bb100-6621-11eb-98a8-8897a95fd72c.png)
9. Export Notebook
![Screen Shot 2021-02-03 at 13 13 50](https://user-images.githubusercontent.com/1948812/106810386-b7e31a80-6621-11eb-9a63-d3dbe617cd7c.png)
10. Trust Icon (Red when not trusted, & green when trusted)
![Screen Shot 2021-02-03 at 13 13 53](https://user-images.githubusercontent.com/1948812/106810385-b7e31a80-6621-11eb-9149-3d4a3e82938b.png)
11. Specify Local or remote (used to toggle between local or remote jupyter connections)
![Screen Shot 2021-02-03 at 13 13 56](https://user-images.githubusercontent.com/1948812/106810383-b7e31a80-6621-11eb-9d01-47106abbaf25.png)

12. Last (split editor) Added by VS Code
![Screen Shot 2021-02-03 at 13 13 59](https://user-images.githubusercontent.com/1948812/106810381-b74a8400-6621-11eb-91d4-68169bc64710.png)

**Comment by DonJayamanne** [comment]
Not sure where Run Above, Run Below should be? Should the be placed before or after interrupt and restart?
Feels like they should be next to run all. & clear output, interrupt & restart should be placed together.
Followed by Variable viewer as thats the next logical icon to be used.
Lastly are export, trust, select local/remote..

**Comment by joyceerhl** [comment]
@claudiaregio had me file this related bug on vscode: https://github.com/microsoft/vscode/issues/114927

**Comment by greazer** [comment]
Unless we have good reason to change it (one reason may be VS Code limitations), it should remain the same as webview had it:
![image](https://user-images.githubusercontent.com/11685408/106811977-f2e64d80-6623-11eb-8280-3408c8c39f0d.png)

If we cannot mimic what we had due to VS Code limitations we can file a bug on them.

**Comment by DonJayamanne** [comment]
Until the VSC issue is resolved, this is the best we can do today.
Moving issue to blocked upstream.

![Screen Shot 2021-02-03 at 13 36 08](https://user-images.githubusercontent.com/1948812/106812785-fa5a2680-6624-11eb-996e-1788addcdf83.png)

**Comment by DonJayamanne** [comment]
Waiting on VS Code to provide detail on guidelines for these buttons (lots of changes happening in this space, toolbar, editor/title/run support in notebooks, etc)

**Comment by joyceerhl** [comment]
Validating as I believe our current toolbar is what we expect:

![image](https://user-images.githubusercontent.com/30305945/118430189-61f22a00-b688-11eb-9afc-b722aaa3b566.png)
