### ISSUE TITLE
Copying a trusted notebook does not make it trusted.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4633]
Using VS code's file explorer if I copy and paste a notebook, the new notebook cannot be run without trusting it. 

Seems unexpected. At least somebody would be not expecting it.

**Comment by joyceerhl** [comment]
Can't seem to find the dupe, but I know we discussed this at some point...

**Comment by DonJayamanne** [comment]
> but I know we discussed this at some point..

Agreed, I recall bringing this up.

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
