### ISSUE TITLE
Suggestion: Data viewer for dataframes should always show head somehow

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4634]
I find myself having to print head over and over (I don't remember column names)

Instead of littering my notebook with head calls, it would be nice if I could just pin the head somewhere (dataframe viewer is close but too large). 

What I really want is variable viewer to have a way to just keep the head pinned. Or maybe a way to drag a cell out and pin it by itself in the jupyter tab.

**Comment by joyceerhl** [comment]
We just had a customer ask for this exact feature (instead of loading the whole data set into the data viewer)

**Comment by DonJayamanne** [comment]
Closing this issue as this feature request hasn't had any upvotes or comments for over a year
