### ISSUE TITLE
My current python environment is missing as an option in the kernel selector

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#4638]
I have a notebook that I've run in this workspace that has the correct kernel in it:
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/38c28abc-a39e-4e01-a707-62286df5b561)

Exported my interactive window output to a new notebook file, it's located in the exact same folder as the other one:
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/a1bf3a7e-f857-42bd-97a1-7fae7672f575)

In the kernel picker is not a .covidEnv option at all (the list is long, but trust me, it's not on there), and I can't use the current interpreter that I set up for my workspace.

**Comment by IanMatthewHuff** [comment]
Note, here is the kernel picker list for the other file, which does have the .covidEnv
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/95082b8f-9fff-49a1-a049-5747f77f0e1f)

**Comment by rchiodo** [comment]
Ian are you validating this? I don't repro this (although it can be hard to find the matching kernel). For me it was just called Python 3 but had the same path as the conda environment.

**Comment by IanMatthewHuff** [comment]
I know this is bad practice but maybe I should just validate? Might even be specific to a way that we used to register interpreters. As best as I can tell it would require an old interpreter that we registered that didn't have an interpreter path.

**Comment by IanMatthewHuff** [comment]
My change should apply the "hide all old registered interpreters" in native scenarios correctly. So if you have an old registered interpreter then you don't have that interpreter on your system any more that should also test it. Or I can just close as I'm the only person with this specific repro.

**Comment by rchiodo** [comment]
This is not working for me. Might be the kernel finder changes that broke it though.

I made one of my kernel.json files point to something that didn't exist. It still shows up in the list.

**Comment by IanMatthewHuff** [comment]
Validated.
