### ISSUE TITLE
Tensorflow import Error

### ISSUE THREAD

**Issue by MayaSakaguchi617** [microsoft/vscode-jupyter#4645]
Issue Type: <b>Bug</b>

Tensorflow is already installed.

>>>import tensorflow as tf

>>>run the next cell
Error: Direct kernel connection broken

Extension version: 2020.12.414227025
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 6d5cec51-b17c-464e-9bbd-a5aad282620e|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rchiodo** [comment]
Thanks for the bug. This sounds like importing tensorflow caused the kernel to crash. 

Are you using pytorch? That might be the issue if you don't install it according to pytorch's directions? 
https://pytorch.org/get-started/locally/

Not really an expert on tensorflow or pytorch though.

**Comment by DonJayamanne** [comment]
@MayaSakaguchi617 
In addition to what @rchiodo has suggested, Please could you also enable logging & provide the output when you get the above error (please try this first before re-installing pytorch).

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `debug`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

@rchiodo would be good to see what errors are returned by kernel, this way when it happens in the future we can proactively ask user from extension to re-install pytorch with some instructions (ie. prevent user from having to report an issue - i.e. provide a way for them to resolve it at their end then and there...).

**Comment by MayaSakaguchi617** [comment]
I really appreciate your advice.

Since I couldn't find Jupiter->Logging, 
I tried to debug by following below.
https://code.visualstudio.com/docs/python/jupyter-support

---Result---
CODE
[ ]:import tensorflow as tf
[ ]:print('hello')

OUTPUT
(base) % source /Users/{username}/opt/anaconda3/bin/activate
(base) % conda activate base
(base) % /Users/{username}/opt/anaconda3/bin/python "{filename}.py"
zsh: illegal hardware instruction  /Users/{username}/opt/anaconda3/bin/python 
(base) %

**Comment by DonJayamanne** [comment]
> Since I couldn't find Jupiter->Logging,

Open your settings from the command palette & select `Preferences: Open Settings UI`
![Screen Shot 2021-02-04 at 11 22 00](https://user-images.githubusercontent.com/1948812/106944333-4e274700-66db-11eb-9227-559b6d5b6a1a.png)

The reload VS Code after changing it to `debug`.
Run your cell & wait for the error `Direct Kernel connection broken`.
Go into your output panel `Jupyter` and copy the output & paste it here.
See here 
![Screen Shot 2021-02-04 at 11 23 49](https://user-images.githubusercontent.com/1948812/106944483-7b73f500-66db-11eb-898f-e1f9eb047f7a.png)

**Comment by rchiodo** [comment]
Your python example indicates that tensorflow crashes without using VS code. 

Sounds like a tensorflow bug. I believe this is the sort of thing that happens if you don't install pytorch using the directions (I had something similar happen to me). Or it could be that tensorflow isn't supported on your chip yet either. 

See this issue here:
https://github.com/tensorflow/tensorflow/issues/44999

**Comment by MayaSakaguchi617** [comment]
@DonJayamanne Thanks for kind instruction.

I've just run the first line: import tensorflow as tf
The output was a little long, so I will attach a text file.

[Log_1.txt](https://github.com/microsoft/vscode-jupyter/files/5928096/Log_1.txt)

**Comment by greazer** [comment]
Please reopen this bug (or file in the tensorflow repo) if the above advice doesn't resolve your issue. Thanks!
