### ISSUE TITLE
Data Explorer and Variable View do not show up

### ISSUE THREAD

**Issue by tkanngiesser** [microsoft/vscode-jupyter#4656]
Data Explorer and Variable View do not show up (as for example shown in [Notebooks in VS Code Are Getting Revamped!](https://www.youtube.com/watch?v=g5EykzAsCC0).

## Environment data

-   VS Code version: Version: 1.53.0-insider (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): 2021.2.531887795-dev
-   OS (Windows | Mac | Linux distro) and version: macOS Big Sur  V.11.1 (20C69)
-   Python and/or Anaconda version:2020.11
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | Local

## Expected behaviour

Data Explorer and Variable View should be visible as introduced in the video.

## Actual behaviour

The menu does not include the option to show Data Explorer and Variable View.

## Steps to reproduce:

1. Create new blank Jupyter Notebook.

**Comment by DonJayamanne** [comment]
@tkanngiesser thanks for filing this issue, however we have not yet released this functionality.
You can however try this feature by installing the latest development build of the extension from here https://github.com/microsoft/vscode-jupyter/suites/1970894193/artifacts/39165018

Closing for now, 
Please feel free to re-open this issue or file a new issue with more information on what you have tried.
