### ISSUE TITLE
Failed to connect to remote notebook

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#4657]
Issue Type: <b>Bug</b>

1. ssh into a remote computer
2. start a jupyter lab instance `jupyter lab --ip=100.100.100.100`
3. get the jupyter server url: e.g. `http://100.100.100.100:8890/lab?token=*********************************`
4. this url opens up jupyter labs without issue in a browser
5. in VS Code press <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>
6. select `Jupyter: Specify local or remote Jupyter server for connections`
7. select `Existing  Specify the URI of an existing server`
8. reload VS Code when prompted
9. Once VS Code reloads, run python code in the interactive pane

I get:

```
Failed to connect to remote Jupyter notebook. 
Check that the Jupyter Server URI setting has a valid running server specified. http://100.100.100.100:8890/lab 
Error: Kernel Python 3 is not usable. 
Check the Jupyter output tab for more information.
```

Yet the exact same server URI works just fine in a browser.  

What is the problem?

It seems like every couple of updates, this breaks.

In the terminal running the Jupyter server, I see the following every time I try and get VS Code to connect:

```
[W 2021-02-04 19:55:36.482 LabApp] 405 POST /lab/api/contents/?1612468535735 (100.200.20.10) 1.49ms referer=None
[W 2021-02-04 19:55:37.165 LabApp] 405 POST /lab/api/contents/?1612468536417 (100.200.20.10) 4.18ms referer=None
```

Extension version: 2020.12.414227025
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.51GB free)|
|Process Argv|--crash-reporter-id f652528b-5678-4b12-9ca0-3de6b1e1135f|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.

> It seems like every couple of updates, this breaks.

I'm sorry about this, 
Please could you confirm this exact same scenario used to work previously.

I have personally never tried spinning Jupyter Lab & connecting to that, I'll test this at my end.
Generally we've tried `jupyter notebook -ip...` I'll check if we do support that & if we've regressed in that area.

**Comment by clayms** [comment]
Yes, confirming this is the approach I have always used for the past approx. two years.

**Comment by DonJayamanne** [comment]
Thanks, I've tested this at my end and it seems to work as expected.
Please could you try installing our latest development build of the VSIX and let us know if this makes any difference  https://github.com/microsoft/vscode-jupyter/suites/1970511305/artifacts/39153932

Also, please could you try the following (if the above doesn't work):
* Change the IP to something else & try again
* Remove the IP completely & try again
* If none of these work, can you try to install an older version of the extension & let us know if it works.
	* Do you know when this stopped working? Were you using this last week or last month?
	* If you haven't got this information, please try to install the October release of the Python extesnion (to do this, you'll first need to uninstall the existing Jupyter & Python extensions in that order & then install the October version of Python extension)
	* Trying to figure out when we regressed for you.

**Comment by clayms** [comment]
earlier today it worked just fine.

It still did not work after I:
1. tried `notebook` instead of `lab`
2. Tried all your suggestions above 
2. restarted my computer

However, it did start working again after I refreshed my group and security policies.  

Not sure why Jupyter labs or notebook worked in the browser just fine, but would not work in VS Code.

Anyway, this issue can be closed now.
