### ISSUE TITLE
Native Notebook insiders banner should have a do not show again option

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#4658]
Per VSCode guidance all notifications should show have this option.

**Comment by rchiodo** [comment]
Not sure what banner this is? When does it come up?

**Comment by IanMatthewHuff** [comment]
Native Notebook Insiders. It only has options to disable for 6 or 3 months. 
https://github.com/microsoft/vscode-jupyter/blob/bd71f9607edc974855a9790110d3d12500f14a76/src/client/datascience/insidersNativeNotebookSurveyBanner.ts#L99

**Comment by rchiodo** [comment]
I think we can close this one? As you're working on the opposite?
