### ISSUE TITLE
ipyfilechooser + ipython_blocking blocks forever

### ISSUE THREAD

**Issue by bryceschober** [microsoft/vscode-jupyter#4660]
## Environment data

-   VS Code version:
    ```
    Version: 1.53.0 (user setup)
    Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
    Date: 2021-02-03T20:36:38.611Z
    Electron: 11.2.1
    Chrome: 87.0.4280.141
    Node.js: 12.18.3
    V8: 8.7.220.31-electron.0
    OS: Windows_NT x64 10.0.19041
    ```
-   Jupyter Extension version: v2020.12.414227025
-   Python Extension version: v2021.1.502429796
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: 3.8.5
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Expected behaviour

1. Open Jupyter mybinder from https://github.com/bryceschober/ipyfilechooser_blocking_example
2. Choose restart and run all cells
3. Expect execution of later cells to block until a file is selected in the ipyfilechooser widget and the "Select" button is clicked.

## Actual behaviour

blocking execution forever

## Steps to reproduce:

1. Check out github project
2. `conda create -f environment.yml -n just-testing`
3. Open `blocking_file_chooser_example.ipynb` in VS Code 
4. Run all cells
5. Blocks forever, including after selecting file in widget

## Logs

I cleared the logs before running, and got nothing in the output except the execution line

**Comment by rchiodo** [comment]
Thanks for the bug. I believe this is the same issue as this one (or same root cause anyway). 

https://github.com/microsoft/vscode-jupyter/issues/4525
