### ISSUE TITLE
Installing the python extension should use the 'extension.open' command instead of opening the URL

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4664]
See @jakebailey 's PR here:
https://github.com/microsoft/vscode-python/pull/15321

**Comment by rchiodo** [comment]
Seems it doesn't work :(

**Comment by IanMatthewHuff** [comment]
Does this need to be tested on codespaces? I gave it a try locally and it worked popping up the same page as before. Did find one new issue that I filed separate: #4724.

**Comment by rchiodo** [comment]
Yeah it would be nice to test on codespaces. @joyceerhl can you try it out?

**Comment by rchiodo** [comment]
To validate:
1) Install just jupyter extension
2) Export from the interactive window.

**Comment by joyceerhl** [comment]
Webviews seem to all be busted in Codespaces right now, but if I install the Jupyter extension, create a blank native notebook and hit 'yes' on the prompt which recommends installing the Python extension, the install page correctly shows up in my Codespace.
