### ISSUE TITLE
Add "reveal in side bar" when right clicking a notebook tab

### ISSUE THREAD

**Issue by koenlek** [microsoft/vscode-jupyter#4666]
If you right click on a file tab in VS code, you normally get a "Reveal in side bar" button:
![image](https://user-images.githubusercontent.com/6514289/106971229-56937800-6703-11eb-85a4-2b22d8b49528.png)

But for a notebook tab, you don't get that:
![image](https://user-images.githubusercontent.com/6514289/106971263-657a2a80-6703-11eb-88d3-1e400decd620.png)

Similarly, the option to sync the side bar with the active file ("Reveal active file in side bar") doesn't work for notebook tabs.

It would be great if we could add these functions, as if the notebook tab is a normal file tab. I often rely on this feature to quickly browse to related files.

**Comment by DavidKutu** [comment]
Thanks for the suggestion @koenlek. Will do, in fact, we have that option already in VS Code insiders. 
You can go ahead and try it out. https://code.visualstudio.com/insiders/

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987.
