### ISSUE TITLE
Jupyter restart notification asks again in another notification afterwards

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4669]
Originally reported https://github.com/microsoft/vscode/issues/115140

Repro:

1. Run infinite loop cell
2. Try to stop it
3. Wait for timeout notification
4. Press restart

![recording (49)](https://user-images.githubusercontent.com/2193314/105897147-aa4be600-5fcc-11eb-8ea5-1f1d763317ca.gif)

**Comment by rchiodo** [comment]
I believe this only happens if you click the stop button more than once? Although we should fix that too.

**Comment by DonJayamanne** [comment]
Someone on windows will need to validate this.

**Comment by rchiodo** [comment]
This kinda works? I'll log a new issue.

If you hit the interrupt button once we only ask for the interrupt restart (instead of the follow up dialog).

If I hit the interrupt button more than once, no dialog appears.
