### ISSUE TITLE
Display gather button only when necessary

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4678]
We can hide the gather button & display it only when a cell has been run, instead of always displaying it.

VSCode provides contexts for this, we should use that the context variable is `notebookCellRunState`

<img width="296" alt="Screen Shot 2021-02-05 at 12 41 28" src="https://user-images.githubusercontent.com/1948812/107087010-a92a6e00-67af-11eb-8a19-49f02be50a6c.png">

**Comment by claudiaregio** [comment]
I specifically requested the functionality that the button be displayed even without cells being run. It should appear in the cell toolbar but if the user tries to click before running, a tooltip explains to them they must run cells before they can use the feature.
