### ISSUE TITLE
Gather extension is crash with the latest dev version of Jupyter

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4679]
* Opt your self into native notebooks
* Open VS Code
* Open a Notebook immediately

<img width="570" alt="Screen Shot 2021-02-05 at 12 45 20" src="https://user-images.githubusercontent.com/1948812/107087271-13431300-67b0-11eb-8b98-61f6e18195a0.png">

**Comment by DavidKutu** [comment]
I reproed once, but after updating VS Code I can't get it to repro again.

**Comment by greazer** [comment]
I don't repro either.
