### ISSUE TITLE
Deleted Notebooks remain open in the editor

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode-jupyter#4683]
## Environment data

-   VS Code version: 1.52.1
-   Extension version (available under the Extensions sidebar): v2021.1.502429796
-   OS and version: Ubuntu 20.04

## Expected behaviour

Consistency when deleting files. When you delete any file in the explorer, the file is removed from the editor window.

## Actual behaviour

If you delete an ipynb file in the explorer, the notebook remains open. This makes it really easy to accidentally edit the deleted file (or even run a cell) which results in it being recreated.

## Steps to reproduce:

1. Open a notebook
2. Delete the file in explorer

**Comment by rchiodo** [comment]
Thanks for the bug. 

This should be addressed when we switch over to VS code's new notebook API. Please track this issue for when we switch:
#1231.

You can try it yourself if you use VS code [insiders](https://code.visualstudio.com/insiders/).

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987.
