### ISSUE TITLE
DataFrame viewer keeps opening on top of the notebook

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4689]
1. Run notebook that creates a data frame
2. Write some code using the data frame
3. Realize I want to view data frame and open it
4. Move it to the side
5. Repeat

Step 4 should only be necessary once. Why do I have to keep moving the viewer?

**Comment by joyceerhl** [comment]
Basically, remember the last editor group, or pick a better editor group, for the data viewer?

**Comment by rchiodo** [comment]
Remember I think.

**Comment by joyceerhl** [comment]
Implemented in #4805, moving to validate

**Comment by IanMatthewHuff** [comment]
Validated. Looks good to me. Did the following:
1. opened data viewer
2. dragged to column 2
3. closed data viewer
4. reopened with a new dataframe
5. it was opened in column 2 as expected.
