### ISSUE TITLE
Renaming notebook filename generates new file instead of transforming the current one

### ISSUE THREAD

**Issue by vmussa** [microsoft/vscode-jupyter#4692]
## Environment data

-   VS Code version: 1.53.0
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.4142
-   Python Extension version (available under the Extensions sidebar): v2021.1.5024
-   OS (Windows | Mac | Linux distro) and version: Windows 10, Build 19041
-   Python and/or Anaconda version: Python 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

After opening an existing notebook and then renaming it while it is still open in VS Code, the filename should be updated to the newly specified name.

## Actual behaviour

Instead, the open notebook seems to keep the original name and a copy of it is created with the newly specified name, duplicating the notebook.

## Steps to reproduce:

1. Create a new notebook inside VS Code and save it.
2. Then, rename it and click it.
3. A new tab will open with a new buffer of a new notebook with the newly specified name.

![record](https://user-images.githubusercontent.com/4412998/107129353-add04e80-68a3-11eb-8bac-4a21492f1840.gif)

**Comment by DavidKutu** [comment]
Thank you for reporting this @vmussa.

I'll add some notes to this issue:

- When using the webview notebooks, I can repro the issue with any existing notebook, or my creating a new one with the command.
- When using native notebooks (insiders), I can only repro when creating a new notebook with the command. It works as expected with existing notebooks.

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987.
