### ISSUE TITLE
Native Notebooks - Notebook to display on open for experiment

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#4694]
Notebook to be displayed to those in Native Notebooks open first opening. Notebook only to be displayed once. 
[Welcome to Native Notebooks!.zip](https://github.com/microsoft/vscode-jupyter/files/5938002/Welcome.to.Native.Notebooks.zip)

**Comment by DonJayamanne** [comment]
For #4600

**Comment by rchiodo** [comment]
Validated.
