### ISSUE TITLE
Jupyter notebook extremely slow

### ISSUE THREAD

**Issue by wesley-cheek** [microsoft/vscode-jupyter#4695]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2020.12.414227025`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 212,
		"activateCallTime": 5,
		"activateResolvedTime": 919,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-toolsai.jupyter",
				"_lower": "ms-toolsai.jupyter"
			},
			"activationEvent": "onLanguage:python"
		}
	},
	"runtimeErrors": []
}
```

**Comment by DavidKutu** [comment]
Hi @wesley-cheek, sorry to hear your notebooks are slow. Could you tell me what is slow? Is the notebook not loading when you try to open it? Or is it slow when running cells? 

Also, are you using VS code stable? If you are, please try VS code insiders, we have a new faster implementation notebooks that you can try in the mean time.
