### ISSUE TITLE
An error pops up after setting jupyter server URI via the "Jupyter: Specify local or remote jupyter server connections".

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#4697]
## Environment data
![image](https://user-images.githubusercontent.com/59192491/107189242-04649680-6a24-11eb-99e1-5d9e61fcec90.png)

## Expected behaviour
The jupyter server is changed to the special server. 

## Actual behaviour
An error pops up.
![image](https://user-images.githubusercontent.com/59192491/107188755-2c072f00-6a23-11eb-9179-60015b769b25.png)

## Steps to reproduce:

1. Open Anaconda prompt window to  run command 'jupyter notebook' to start up a local Jupyter server
2. In the command window that launched Jupyter look for the server / token name like so: http://127.0.0.1:8888/?token=a44c9f092df568d6272c59f116455cea9e4fb4aaf0c77768
3. You can also start up Jupyter from VSC:
         a. Press Ctrl+Shift+P to run the command 'Jupyter: Specify local or remote jupyter server connections'
         b. Type in the URL to connect to a running jupyter server
4. Input the server / token name here

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DavidKutu** [comment]
Sorry to hear you're having trouble @linette-zyy. Could you check the developer Console and share the errors that come up?
(`Help -> Toggle Developer Tools`)

**Comment by linette-zyy** [comment]
@DavidKutu Please refer below screenshots for details.
![image](https://user-images.githubusercontent.com/59192491/107303281-be5a1200-6ab9-11eb-86d7-28db1884dd55.png)

![image](https://user-images.githubusercontent.com/59192491/107303305-c914a700-6ab9-11eb-8cc4-1b51010383fb.png)

**Comment by DavidKutu** [comment]
Thanks for your reply @linette-zyy. The screenshots you show me are from VS code itself, what I can gather is that the version of the extension you're using is somehow broken. 

I also noticed you're using a development version (probably from our daily or weekly insiders). Does the issue keep happening if you go back to a different version? Say `2020.12.414227025`

(You might also want to make sure you have this setting `"jupyter.insidersChannel": "off"`)

Let me know if that works.

**Comment by greazer** [comment]
@linette-zyy, please retry with the latest build of VS Code stable and our latest build of the extension here: https://pvsc.blob.core.windows.net/extension-builds-jupyter/ms-toolsai-jupyter-release.vsix
