### ISSUE TITLE
Wrong conda environment being used in vscode notebook

### ISSUE THREAD

**Issue by LucasStromberg** [microsoft/vscode-jupyter#4699]
I have installed an environment via Anaconda Navigator, for TensorFlow development with GPU (CUDA, cuDNN).

When running "import tensorflow as tf" in python everything works as usual in cmd, vscode .py-files, native web-based jupyter notebook but NOT in vscode jupyter notebook. I have set my python interpreter with ctrl+shift+P to my desired environment and I can as stated above confirm that everything works in normal .py files in vscode (and also in the vscode terminal), but not in notebook.

- - - - -
Windows 10
python: 3.8.5
cudatoolkit: 10.1.243
cudnn: 7.6.5
jupyter_client: 6.1.7
jupyter_core: 4.7.1
jupyterlab_pygments: 0.1.2
tensorflow: 2.3.0
- - - - -

Error output:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-da6830fd618f> in <module>
      1 import sys
      2 sys.executable
----> 3 import tensorflow as tf
      4 
      5 #tf.config.list_physical_devices('GPU')

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     39 import sys as _sys
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     43 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     44 
     45 # Bring in subpackages.
---> 46 from tensorflow.python import data
     47 from tensorflow.python import distribute
     48 from tensorflow.python import keras

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\data\__init__.py in <module>
     23 
     24 # pylint: disable=unused-import
---> 25 from tensorflow.python.data import experimental
     26 from tensorflow.python.data.ops.dataset_ops import AUTOTUNE
     27 from tensorflow.python.data.ops.dataset_ops import Dataset

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\data\experimental\__init__.py in <module>
     95 
     96 # pylint: disable=unused-import
---> 97 from tensorflow.python.data.experimental import service
     98 from tensorflow.python.data.experimental.ops.batching import dense_to_ragged_batch
     99 from tensorflow.python.data.experimental.ops.batching import dense_to_sparse_batch

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\data\experimental\service\__init__.py in <module>
    138 from __future__ import print_function
    139 
--> 140 from tensorflow.python.data.experimental.ops.data_service_ops import distribute
    141 from tensorflow.python.data.experimental.ops.data_service_ops import from_dataset_id
    142 from tensorflow.python.data.experimental.ops.data_service_ops import register_dataset

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py in <module>
     23 
     24 from tensorflow.python import tf2
---> 25 from tensorflow.python.data.experimental.ops import compression_ops
     26 from tensorflow.python.data.experimental.ops.distribute_options import AutoShardPolicy
     27 from tensorflow.python.data.experimental.ops.distribute_options import ExternalStatePolicy

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py in <module>
     18 from __future__ import print_function
     19 
---> 20 from tensorflow.python.data.util import structure
     21 from tensorflow.python.ops import gen_experimental_dataset_ops as ged_ops
     22 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\data\util\structure.py in <module>
     31 from tensorflow.python.framework import tensor_spec
     32 from tensorflow.python.framework import type_spec
---> 33 from tensorflow.python.ops import tensor_array_ops
     34 from tensorflow.python.ops.ragged import ragged_tensor
     35 from tensorflow.python.platform import tf_logging as logging

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py in <module>
     40 from tensorflow.python.ops import gen_control_flow_ops
     41 from tensorflow.python.ops import gen_data_flow_ops
---> 42 from tensorflow.python.ops import list_ops
     43 from tensorflow.python.ops import math_ops
     44 from tensorflow.python.platform import tf_logging as logging

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\list_ops.py in <module>
     23 
     24 from tensorflow.core.framework import types_pb2
---> 25 from tensorflow.python.framework import cpp_shape_inference_pb2
     26 from tensorflow.python.framework import dtypes
     27 from tensorflow.python.framework import ops

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\cpp_shape_inference_pb2.py in <module>
    188 _CPPSHAPEINFERENCERESULT_HANDLESHAPEANDTYPE.fields_by_name['shape'].message_type = tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2._TENSORSHAPEPROTO
    189 _CPPSHAPEINFERENCERESULT_HANDLESHAPEANDTYPE.fields_by_name['dtype'].enum_type = tensorflow_dot_core_dot_framework_dot_types__pb2._DATATYPE
--> 190 _CPPSHAPEINFERENCERESULT_HANDLESHAPEANDTYPE.fields_by_name['specialized_type'].enum_type = tensorflow_dot_core_dot_framework_dot_types__pb2._SPECIALIZEDTYPE
    191 _CPPSHAPEINFERENCERESULT_HANDLESHAPEANDTYPE.containing_type = _CPPSHAPEINFERENCERESULT
    192 _CPPSHAPEINFERENCERESULT_HANDLEDATA.fields_by_name['shape_and_type'].message_type = _CPPSHAPEINFERENCERESULT_HANDLESHAPEANDTYPE

AttributeError: module 'tensorflow.core.framework.types_pb2' has no attribute '_SPECIALIZEDTYPE'

**Comment by DavidKutu** [comment]
Sorry to hear you're having issues @LucasStromberg.

I managed to get your code to work on our native notebooks:
![image](https://user-images.githubusercontent.com/20347396/107300751-f7997000-6a2e-11eb-94b9-aa8bac7cce83.png)

Please help me by answering a couple of questions:

1. What version of the Jupyter extension are you using?
2. Are you using VS code stable or Insiders?
3. Could you open the dev tools (`Help -> Toggle Developer Tools`) and see if there is an error on the Console, if so, please share it.

From my searches, it looks like tensorflow is a tricky install, maybe it works in the interactive window and not in notebooks because the kernel was different?

Anyway, please let me know.

**Comment by LucasStromberg** [comment]
Hi.

1. v2020.12.414227025
2. Stable
3. Doesn't seem to be any errors in the console.

I tried creating a new environment with:
`conda install -c anaconda cudatoolkit=10.1`
`conda install -c anaconda cudnn=7.6`
`pip install tensorflow-gpu==2.3.0`

Again, importing tensorflow in cmd works fine, as well as doing it in a .py file in vscode. Notebook still doesn't work, but now I get another output error (below).

I tried installing numpy 1.19.3 as in the link, but this doesn't work since tensorflow 2.3.0 requires numpy 1.16.0.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-da6830fd618f> in <module>
      1 import sys
      2 sys.executable
----> 3 import tensorflow as tf
      4 
      5 #tf.config.list_physical_devices('GPU')

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     39 import sys as _sys
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     43 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     39 from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
     40 
---> 41 from tensorflow.python.eager import context
     42 
     43 # pylint: enable=wildcard-import

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\context.py in <module>
     27 
     28 from absl import logging
---> 29 import numpy as np
     30 import six
     31 

C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py in <module>
    303 
    304     if sys.platform == "win32" and sys.maxsize > 2**32:
--> 305         _win_os_check()
    306 
    307     del _win_os_check

C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py in _win_os_check()
    300                    "See this issue for more information: "
    301                    "https://tinyurl.com/y3dm3h86")
--> 302             raise RuntimeError(msg.format(__file__)) from None
    303 
    304     if sys.platform == "win32" and sys.maxsize > 2**32:

RuntimeError: The current Numpy installation ('C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
