### ISSUE TITLE
Need a check for insiders version of VS code when enabling insiders version of Jupyter Extension

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4700]
In order to support on going changes like this:
https://github.com/microsoft/vscode/issues/93265#issuecomment-775295266

We need to update at the same time as VS code does.

**Comment by joyceerhl** [comment]
Not sure how to validate this, did we turn insiders back on?

**Comment by rchiodo** [comment]
No we haven't. Seems like we're not going to either. we're just going to use the trick that Peng discussed.

**Comment by rchiodo** [comment]
I think we can just close this.
