### ISSUE TITLE
Resizing right most column of variable view when in side panel doesn't work

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4705]
![image](https://user-images.githubusercontent.com/19672699/107268559-2860b180-69fd-11eb-8a19-030994b38ac5.png)

Try dragging the right side size of the 'value' column. Once the mouse goes outside of the panel it stops responding.

**Comment by greazer** [comment]
Address as parity only if resizing the rightmost column worked in webview.

**Comment by DavidKutu** [comment]
I can't repro this. If I try to drag it past the panel width, I keep controlling it until I click somewhere inside the panel to set it there.
Also, how do you put the variables there? Is that a setting?

**Comment by rchiodo** [comment]
>  I keep controlling it until I click somewhere inside the panel to set it there.

That's exactly the problem. I can only set the width to the current width of the panel. There's no way for me to resize the value column past the edge of the window.

> Also, how do you put the variables there? Is that a setting?

Not sure what you're asking. I just created variables with a lot of data. Like this:

```python
mystr = "A really long string that won't fit in the variables value column"
```

**Comment by DavidKutu** [comment]
How do you put it on the side bar instead of the panel?
![image](https://user-images.githubusercontent.com/20347396/108411134-1fca6100-71dd-11eb-852c-c8613cd06b4e.png)

**Comment by rchiodo** [comment]
You drag the tab header over to a side panel. 

The problem repros with it at the bottom too, it's just not as much of a pain

**Comment by IanMatthewHuff** [comment]
Keeping around most of the variable explorer feedback, but this one seemed really minor if it wasn't being reported by customers. So closing, but please reactivate if you disagree.
