### ISSUE TITLE
pd.set_option 'display.max_rows' to anything greater than default no longer works

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#4707]
Issue Type: <b>Bug</b>

pd.set_option 'display.max_rows' to anything greater than default no longer works when outputting to the Interactive Pane.

This worked just a few days ago.  Where has this setting been moved to?

e.g.
```
pd.set_option('display.max_rows', 50)
```

Then sending a pandas DataFrame with more than 50 rows to output in the Interactive Pane, will only display the first 5 rows, then `...` , and then the last 5 rows.

However, the following does still work:
```
pd.set_option('display.max_rows', 5)
```

Reproduceable: 
```
pd.set_option('display.max_rows', 50)

df = pd.DataFrame({
    "col1": ["x"] * 500
})

df
```
![image](https://user-images.githubusercontent.com/12793783/107280414-56a6b700-6a26-11eb-8113-ab61c171aad8.png)

```

pd.set_option('display.max_rows', 5)

df = pd.DataFrame({
    "col1": ["x"] * 500
})

df
```
![image](https://user-images.githubusercontent.com/12793783/107280531-763ddf80-6a26-11eb-8275-357b81207571.png)

Extension version: 2020.12.414227025
VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.60GB free)|
|Process Argv|--crash-reporter-id f652528b-5678-4b12-9ca0-3de6b1e1135f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by DavidKutu** [comment]
Thank you for reporting the issue @clayms. 

To display all the rows, set `max_rows` greater than the number of rows in the `DataFrame.`

In your example:
```
import pandas as pd
pd.set_option('display.max_rows', 501)

df = pd.DataFrame({
    "col1": ["x"] * 500
})

df
```

Gives this result:
![image](https://user-images.githubusercontent.com/20347396/107296887-1a278b00-6a27-11eb-90c7-12f8695dcc18.png)

Let me know if it works for you.

**Comment by clayms** [comment]
My actual dataframe has over 20,000 rows, so setting the `max_rows` to `20_001` is not feasible.  

What I actually need to set it the `min_rows` to anything larger than the default of `10`.  


```
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.min_rows', 50)

df = pd.DataFrame({
    "col1": ["x"] * 20_000
})

df
```


![image](https://user-images.githubusercontent.com/12793783/107310917-6260a080-6a5b-11eb-87e0-c083e554922a.png)
