### ISSUE TITLE
Kernels disappear after doing remote

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4708]
Set to remote jupyter
Create new blank notebook
Select kernel
Big list should show up
Run cell
Select kernel

This shows up instead of full list
![image](https://user-images.githubusercontent.com/19672699/107289009-3b817a80-6a19-11eb-8ae1-c7e5d95168cb.png)

**Comment by DonJayamanne** [comment]
I too can replicate this issue.

**Comment by rchiodo** [comment]
Validated.
