### ISSUE TITLE
Error opening in stable after coming out of native experiment

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4711]
![image](https://user-images.githubusercontent.com/19672699/107289990-af705280-6a1a-11eb-9ae9-667ab0413f82.png)

Unable to open 'manualTest_3.ipynb': Using the Jupyter notebook editor requires the stable version of VS code and the CustomEditor experiment to be enabled.

Likely caused by this:
```
"workbench.editorAssociations": [
    {
      "viewType": "jupyter.notebook.ipynb",
      "filenamePattern": "*.ipynb"
    }
  ],

**Comment by greazer** [comment]
Re opening the notebook should resolve the problem.
