### ISSUE TITLE
ALT+ENTER and CTRL+ENTER not working in native notebooks

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4713]
ALT+ENTER doesn't seem to leave focus in the same cell
CTRL+ENTER doesn't run anything (just adds a new line)

**Comment by IanMatthewHuff** [comment]
I just checked it out. For me on Mac they all seem to do the right thing:
shift + enter: execute and move next
ctrl + enter: execute and stay in place
alt + enter: execute and insert a new cell

**Comment by DonJayamanne** [comment]
Valdiated
