### ISSUE TITLE
Hide all but 3 of our icons in the native notebook

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4730]
For both stable and insiders hide all but 3.

The 3 are to be determined.

Others can be forced into the overflow menu.

**Comment by claudiaregio** [comment]
Top 3 to be used: 
1. Restart kernel
2. Variable Explorer
3. Export As 
When kernel is in busy state, turn the restart kernel notebook toolbar icon into the STOP EXECUTION RED SQUARE ICON. When kernel is in idle state, turn back into the kernel restart icon.

**Comment by rchiodo** [comment]
Not sure yet about the the icon/command changing.

This might work:

```
                {
                    "command": "jupyter.notebookeditor.restartkernel",
                    "title": "%jupyter.command.jupyter.restartkernel.title%",
                    "group": "navigation@3",
                    "when": "notebookViewType == 'jupyter-notebook' && !jupyter.isbusy"
                },
                {
                    "command": "jupyter.notebookeditor.interruptkernel",
                    "title": "%jupyter.command.jupyter.interruptkernel.title%",
                    "group": "navigation@3",
                    "when": "notebookViewType == 'jupyter-notebook' && jupyter.isbusy"
                },
```

I'd have to code it up to find out.

**Comment by IanMatthewHuff** [comment]
Validated.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/ae0c3c76-c89f-49a6-87f0-15b0044e5f0c)
Restart, Variable, Export As
