### ISSUE TITLE
It is not clear that a kernel is running. It should be.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#4731]
Whether you run all the cells in a notebook, or "this cell and down" or just run a single cell, it is extremely difficult to tell that a kernel is running. The only indication comes through scrolling through the notebook looking for timers in the cell status bars or if you happen to see that the "interrupt kernel" toolbar icon is no longer grayed out. Since it's gray to begin with, the difference is really subtle.

Ideas: 
- Disable the run xxx commands when a kernel is running.
- Make the interrupt kernel button red so that it's more noticeable.
- Provide some hint on the VS Code status bar
- Provide a widget in a location similar to what Jupyter Lab and Classic uses (a green "busy" circle)

Any or all of the above.

**Comment by IanMatthewHuff** [comment]
@greazer I believe that the "goto running cell" button that has the spinner icon handles this pretty well. Closing, but reactivate if you disagree :).
