### ISSUE TITLE
Support syntax highlighting for OSS build (Arch linux)

### ISSUE THREAD

**Issue by coxackie** [microsoft/vscode-jupyter#4733]
First of all, let me mention my appreciation for the work you are doing with this extension.

 I do understand that you may only be supporting the microsoft build of vscode. But, I want to point out that syntax highlighting does not seem to work for notebooks (apart from python). Below is how an notebook rinning the R kernel looks like in the `code - oss` build of arch linux:
![Screenshot from 2021-02-10 10-31-59](https://user-images.githubusercontent.com/22049642/107498632-f762b700-6b8b-11eb-9de8-8b3a1db648f5.png)
As you can see, there is no highlighting at all. Here the equivalent with `vscode`:
![Screenshot from 2021-02-10 10-33-32](https://user-images.githubusercontent.com/22049642/107498676-03e70f80-6b8c-11eb-8306-4fe010b09c14.png)
(These both are in the 1.53.1 build, but the problem appeared in every previous build.)
It appears that the `extensions` folder of the `code - oss` build may not be parsed correctly for syntax highlighting? I can give you any info you need in case you can help with this issue.

**Comment by rchiodo** [comment]
Thanks for the bug. Yes we don't really support the OSS build. It looks like you're running an older version of it though. The newer version should have notebooks that use the new VS code notebook editor. Something that looks like so:

![image](https://user-images.githubusercontent.com/19672699/107555283-d601cb00-6b8b-11eb-9883-fb08335e5642.png)

**Comment by coxackie** [comment]
@rchiodo I understand you do not support these builds, but just a quick question: I am actually using 1.53.1 of code, and latest jupyter notebook extension. I was under the impression you can only get the native notebooks in insiders versions. Can one also enable them in the "stable" version? I could not find a way to do so...

**Comment by rchiodo** [comment]
> Can one also enable them in the "stable" version? I could not find a way to do so...

No sorry not at the moment.

**Comment by coxackie** [comment]
@rchiodo ok, many thanks. I really hope native notebooks get pushed soon to stable. I cannot find any roadmap on this.
