### ISSUE TITLE
Can't work in WSL2

### ISSUE THREAD

**Issue by xsro** [microsoft/vscode-jupyter#4734]
## Environment data

-   VS Code version: 1.53.1
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.502429796
-   OS (Windows | Mac | Linux distro) and version:  Microsoft Windows 10 家庭中文版OS 版本:          10.0.19041 暂缺 Build 19041
-   Python and/or Anaconda version: conda 4.9.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

display a notebook webview

## Actual behaviour

the webview is blank with nothing rendered. 

Maybe it is because the VSCode can't get webview's resources is in WSL

```
vscode-webview-resource://c5d9b98d-9328-406e-9447-c9f63711dfb8/file///home/xsro/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/datascience-ui/notebook/require.js
```
![image](https://user-images.githubusercontent.com/64292434/107499684-3a467e00-6bd0-11eb-895f-6aa3ebfa686b.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1.  in WSL, open a jupyter notebook

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

webview console

```
Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
ipywidgets.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
monaco.bundle.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
commons.initial.bundle.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
nativeEditor.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
font-awesome.min.css:1 
```

</p>
</details>

**Comment by rchiodo** [comment]
I believe this is this error here:
https://github.com/microsoft/vscode/issues/105536
