### ISSUE TITLE
[New notebook experience] False positives in diffs of outputs of cells

### ISSUE THREAD

**Issue by thakkarparth007** [microsoft/vscode-jupyter#4736]
## Environment data

-   VS Code version: 1.54.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.2.518958983-dev
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Python 3.6.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local (in a remote SSH session)

## Expected behaviour

When viewing diffs of a notebook, when the outputs are the same, the diff viewer should not show that output has changed.

## Actual behaviour

Even when output of the notebook versions is the same, the diff viewer shows that output has changed. That is technically true because the outputId attribute in the output json has changed, but fundamentally the output is the same.

![image](https://user-images.githubusercontent.com/747423/107532855-5522ed80-6be4-11eb-86fc-f960f1f1b2ec.png)

![image](https://user-images.githubusercontent.com/747423/107532898-5fdd8280-6be4-11eb-9405-939d564b91fa.png)

While it might be useful to see that the notebook cell has been executed, I guess it should be an option to let the user see what they want out of the diff viewer - whether the cell has been executed (even if it gave the same result), or whether the actual output is different.

Without this, viewing diffs of tables/large outputs is difficult.

**Comment by claudiaregio** [comment]
Hi @thakkarparth007, thanks for the feedback. I have transferred this over to vs code. You can find updates here: https://github.com/microsoft/vscode/issues/116350
