### ISSUE TITLE
Update VSCode Notebooks API

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4737]
All the changes are here (last 4 commits, starting from WIP):
https://github.com/rebornix/vscode-jupyter/commits/rebornix/fixVSCAPI

These changes must be applied to master after we have created a release branch.

* [x] Import from vscode & not from `..../vscode-proposed`
* [x] Update Python extension notebook API
* [x] Update renderers extension

**Comment by IanMatthewHuff** [comment]
Not sure if there is a specific validation on this. But resolving due to notebooks now working in insiders and the API update PRs.
