### ISSUE TITLE
Feature Request: Keyboard shortcut - jump cursor to code entry cell

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode-jupyter#475]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description
Feature request to add a keybinding option to jump cursor to the code entry cell in the Python Interactive window, from anywhere in vs code.

While moving around vs code I find myself constantly needing to move back to the mouse to and then mouse to the code entry cell. Would be a very nice feature to have, thanks!

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by jaymegordo** [comment]
Commnenting to see if I can bump this issue back on the radar, would still be very nice to have!! Hopefully it's not too complex to implement.

**Comment by rchiodo** [comment]
Theoretically CTRL+1/CTRL+2 should do this already. There's been some issues with focus tracking though.

**Comment by jaymegordo** [comment]
@rchiodo yeah that sorta works, but doesn't seem to all the time, and also only swaps between editors in the same panel. Eg if I have split panels I still have to jump over from the other side first.

I'd love it if there was a dedicated shortcut which did:
1. Bring python interactive window to focus/activate (from anywhere in vs code)
2. Place cursor in the code entry cell

Again not super critical, but I would definitely use it a ton.

**Comment by Keeptg** [comment]
It will be great if this suggestion can be supported. I rememberd there is a time CTRL+2 (if the cursor in the code entry cell previousely) or CTRL+2+2 (if the cursor not in the code entry cell previousely) work well. But CTRL+2+2 doesn't work for a while. Today, I update the newest vscode (1.56.0), both of the CTRL+2 and CTRL+22 is invalid to move the cursor to the code entry cell.
Hope it will be support again in the future!

**Comment by VictorSuarezL** [comment]
In fact, in MacOS you can press CMD+M to switch the cursor between script and terminal. I would also definitely use it a ton!!

**Comment by Keeptg** [comment]
> 
> 
> In fact, in MacOS you can press CMD+M to switch the cursor between script and terminal. I would also definitely use it a ton!!
@VictorSuarezL Sure! In Ubuntu, we can also press ctrl+` to switch the cursor between script and terminal.

**Comment by jaymegordo** [comment]
@rchiodo gonna keep pinging you on this one 😉

Now that Native Interactive is live, (especially now that the code entry line is even smaller) would be amazing to have a dedicated shortcut like `jupyter.interactive.focusCodeEntry` or similar which does:
1. Bring focus to interactive window if not focused
2. Move cursor to end of code entry cell

This would make my workflow SO much faster rather than constantly having to mouse back and click into the code entry cell.

<img width="815" alt="image" src="https://user-images.githubusercontent.com/29611875/124645647-88db0a00-de48-11eb-80a7-975e830ccad5.png">

**Comment by rchiodo** [comment]
@jaymegordo given that the interactive window is switching to being part of VS code core, it might make sense to make this request in vscode instead. 

However CTRL+1/CTRL+2 should be doing what you wanted. It's supposed to switch focus to the entry point at the bottom. It's just broken at the moment:
https://github.com/microsoft/vscode/issues/124788

**Comment by jaymegordo** [comment]
@rchiodo thanks for letting me know, I'll open this issue there to see if there's some interest.
