### ISSUE TITLE
Running a cell from the cell run button does not select or highlight the cell if not previously selected.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#4756]
1. Open a notebook
2. Run a cell using the cell run button on the left of the cell.

No highlighting of the cell or the next cell occurs, making it very difficult to know if it was run or not. 

When a cell is run via the toolbar, it should basically be the same operation is shift-enter. The current cell should run and the next one should be selected.

For example:
![image.png](https://images.zenhubusercontent.com/5bda244bb6c4f1227d4a2d8e/039be093-c0c1-4a87-92ba-dd846434a177)

Should result in:
![image.png](https://images.zenhubusercontent.com/5bda244bb6c4f1227d4a2d8e/6a85390f-b6be-4eb4-acaf-9b9a494ebc64)

Instead of: 
![image.png](https://images.zenhubusercontent.com/5bda244bb6c4f1227d4a2d8e/5852f26b-2b9c-4394-a7a1-d152c0eab6e7)

**Comment by DonJayamanne** [comment]
Personally don't like that option. CLicking on the `Button` should keep me there.
Azure Notebooks does the same thing today, it does not advance to the next cell.

**Comment by greazer** [comment]
This isn't necessarily about advancing to the next cell. You can run a cell without it being the actively selected cell, but that cell does not become active. This seems odd and wrong. If Jupyter Lab does the same thing, then well.. so be it.

**Comment by DonJayamanne** [comment]
Assigning to Rob due to the fact that Rob has worked a lot in this space, @roblourens please feel free to un-assign if incorrect.

**Comment by roblourens** [comment]
This has since been fixed
