### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by xman0142** [microsoft/vscode-jupyter#4763]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2020.12.414227025`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.53.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 88,
		"activateCallTime": 5,
		"activateResolvedTime": 644,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-toolsai.jupyter",
				"_lower": "ms-toolsai.jupyter"
			},
			"activationEvent": "onLanguage:jupyter"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Unable to start session for kernel Python 3. Select another kernel to launch with."
		}
	]
}
```

**Comment by DonJayamanne** [comment]
@xman0142 thanks for filing this issue.
To better assist you with this please could you provide the following information:

## Environment data

-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `debug`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
