### ISSUE TITLE
Clicking on a markdown item in Outline tab should scroll the item clicked to the top of the editor, not the middle. 

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#4777]
It may make sense for code navigation via the Outline view to scroll the selected code to the middle of the editor window. But in notebooks, a markdown cell is likely the beginning of a new cell. The contents of the last cell aren't likely to be immediately relevant.

**Comment by greazer** [comment]
Tracked in VS Code's repo here: https://github.com/microsoft/vscode/issues/116514

**Comment by joyceerhl** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/116514
