### ISSUE TITLE
Saving when prompted with "Do you want to save?" doesn't save changes correctly. (was: Cannot reopen ipynb after closing without saving changes)

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode-jupyter#4779]
## Environment data

-   VS Code version: 1.53.1
-   Extension version (available under the Extensions sidebar): 2021.1.502429796
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pyenv-virtualenv

## Expected behaviour

Closing an unsaved ipynb should not prevent it from being reopened

## Actual behaviour

If I close an ipynb which has unsaved changes it prompts to save changes. Then the file is closed, and from that point on it wont re-open. When I restart vscode the notebook is open with the unsaved changes - it acts like it was never actually closed but hidden. 

(I've separately reported that closing an unsaved notebook and accepting save changes doesn't actually work - you must save using Ctrl-S)

## Steps to reproduce:

1. Open an ipynb file and make a change
2. Close without saving
3. Accept "Save" from the "Do you want to save changes dialogue"
4. Attempt to reopen the file in the same vscode session - the file won't open
5. Exit and restart vscode - the file will reopen with previous changes unsaved

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and sorry for the delay in replying to this issue.
Let me look into this ASAP.

**Comment by rchiodo** [comment]
Validated I think? Not sure I did the repro correctly.

Open webview notebook
Edit file
Close file
Click Save 
Reopen, contents should be same.
