### ISSUE TITLE
Unable to create new notebook on fresh install

### ISSUE THREAD

**Issue by cwallace** [microsoft/vscode-jupyter#4780]
Issue Type: <b>Bug</b>

I am using a fresh Macbook Air M1 with Python 3.9.1 installed. After installing notebook and jupyter I receive an error attempting to run a cell in a new notebook.

Extension version: 2020.12.414227025
VS Code version: Code - Insiders 1.54.0-insider (6ac9a3ecb3698e82bf901f11bbb5940f6bc3c197, 2021-02-12T05:14:39.860Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.37GB free)|
|Process Argv|--crash-reporter-id 8f742068-df45-4987-975d-94b99b3da916|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
vstes627:30244334
pythonvspyt600cf:30251589
core-portspanelcf:30233468
coreuntitledfile:30249963

```

</details>

[Here is the output of jupyter.](https://pastebin.com/n9Dh52ap)

**Comment by greazer** [comment]
Likely fixed by a change made for another problem. Should be fixed in our main branch. Let's validate and release next month

**Comment by DonJayamanne** [comment]
Moving to fixed, as i cannot repro this.

**Comment by DonJayamanne** [comment]
@cwallace
Please install the latest extension (published today) & test against the latest VS Code insiders.
This should be working, if not please feel

**Comment by cwallace** [comment]
> @cwallace
> Please install the latest extension (published today) & test against the latest VS Code insiders.
> This should be working, if not please ping us back.

Yes the latest release resolve it. Thank you so much!
