### ISSUE TITLE
VS Code Insiders: Unable to open '....ipynb': Cannot read property '...' of undefined.

### ISSUE THREAD

**Issue by jjcfrank** [microsoft/vscode-jupyter#4782]
## Environment data

-   VS Code version: VS Code Insiders Version 1.5.4.0-insiders
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.502429796
-   OS (Windows | Mac | Linux distro) and version: macOS BigSur 11.2
-   Python and/or Anaconda version: Homebrew Python 3.9.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

Open a jupyter notebook

## Actual behaviour

Any .ipynb opened will cause VS Code Insiders to say: Unable to open '....ipynb': Cannot read property '...' of undefined.

NOTE: The second set of inverted commas has been 'Rich' or 'Error'

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Download VS Code Insiders
2. Install Python & jupyter notebook extension
3. Pip3 install ipykernel and ipython
4. Open VS Code Insiders and select a folder
5. Open a jupyter notebook within the selected folder
6. Any .ipynb opened will cause VS Code Insiders to say: Unable to open '....ipynb': Cannot read property '...' of undefined.
6.1 The second set of inverted commas has been 'Rich' or 'Error'

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by RahulARanger** [comment]
![not_opening](https://user-images.githubusercontent.com/57987728/107767897-ae615d00-6d5b-11eb-96f2-1d86864033ca.gif)

It started after the recent update.

**Comment by jjcfrank** [comment]
> ![not_opening](https://user-images.githubusercontent.com/57987728/107767897-ae615d00-6d5b-11eb-96f2-1d86864033ca.gif)
> 
> It started after the recent update.

That's the one.

**Comment by deepan-py** [comment]
same problem here `Unable to open '*.ipynb': Cannot read property 'Rich' of undefined.`

**Comment by kevball2** [comment]
Also seeing the same issue

**Comment by eduardopaul** [comment]
I'm having the same issue here.

**Comment by nathanlesage** [comment]
Can confirm. Some more info after fiddling around:

Calling `jupyter notebook` from the command line works just fine (but I had to reinstall the jupyter/notebook packages after the most recent Big Sur update, which happened to occur on the same day as said update), the notebooks open and the kernel works. So it's definitely an issue with the extension. (I'm on an M1 MacBook)

**Comment by pbotros** [comment]
Same issue too. Is there anyway to downgrade VS Code Insiders Edition, or do we have to go back to non-Insiders edition?

**Comment by nathanlesage** [comment]
> Same issue too. Is there anyway to downgrade VS Code Insiders Edition, or do we have to go back to non-Insiders edition?

Back to non-insider is easy: Just download the stable one and use it. Downgrading insiders, I would be interested myself as well

**Comment by rchiodo** [comment]
Unfortunately VS code is in the process of updating their notebook APIs. As they change them we'll be randomly broken until we can catch up. 

We're working on a process for making our extension update automatically every night as well (on insiders only) so we should be closer to keeping up with VS code changes.

**Comment by rchiodo** [comment]
Actually we can keep this open until we think we can catch up.

**Comment by saserbest** [comment]
Is there any quick solution we can apply while fix is on the way?

**Comment by rchiodo** [comment]
Actually closing in favor of #4796 

Sorry but there is no workaround. You have to go back to stable. The API we use to communicate with VS code is just not there in insiders anymore.

**Comment by rchiodo** [comment]
Sorry there is a workaround, install the older build of insiders. That should work as it will use the older API.

**Comment by rchiodo** [comment]
See directions here on how to get an older build:
https://github.com/microsoft/vscode/issues/46089#issuecomment-374246974

**Comment by hopezh** [comment]
same issue here, on both vscode and vscode insider, on M1 Mac Mini. Have to use Anaconda to open jupyter notebook for the time being.

**Comment by nathanlesage** [comment]
@rchiodo Thank you for providing the instructions and additional links!

**Comment by gitony0101** [comment]
same error so we do not need to update the insider too often right?

**Comment by jjcfrank** [comment]
> See directions here on how to get an older build:
> [microsoft/vscode#46089 (comment)](https://github.com/microsoft/vscode/issues/46089#issuecomment-374246974)

Looks good. But cannot get an older version compatible with M1.

**Comment by gulshan17** [comment]
> > See directions here on how to get an older build:
> > [microsoft/vscode#46089 (comment)](https://github.com/microsoft/vscode/issues/46089#issuecomment-374246974)
> 
> Looks good. But cannot get an older version compatible with M1.

https://vscode-update.azurewebsites.net/1.53.0-insider/darwin-arm64/insider Use this for M1 and then switch off the updates.

**Comment by rohan-paul** [comment]
Even insider version **1.53.0** not opening .ipynb file in Linux.

I got the .deb file for **1.53.0** by pasting the below URL directly in Browser

`vscode-update.azurewebsites.net/1.53.0-insider/linux-deb-x64/insider`

Uninstalled the previous insider version (54) and installed this one from the .deb file 

Below are version details.

![image](https://user-images.githubusercontent.com/12703975/107969422-c3492500-6fd5-11eb-90d1-d8a2b63bb10c.png)

But NOT opening any .ipynb file.

**Comment by rohan-paul** [comment]
For Linux, got the .deb file for **1.53.0** from here.

[vscode-update.azurewebsites.net/1.53.0-insider/linux-deb-x64/insider](https://vscode-update.azurewebsites.net/1.53.0-insider/linux-deb-x64/insider)

**Comment by gitony0101** [comment]
> > > See directions here on how to get an older build:
> > > [microsoft/vscode#46089 (comment)](https://github.com/microsoft/vscode/issues/46089#issuecomment-374246974)
> > 
> > 
> > Looks good. But cannot get an older version compatible with M1.
> 
> https://vscode-update.azurewebsites.net/1.53.0-insider/darwin-arm64/insider Use this for M1 and then switch off the updates.

I rolled back to this version while it still showed:" Cannot read property 'Markdown' of undefined。"

**Comment by AndrewLaganaro** [comment]
Returned to 1.53.0 version on windows 10, also rolled back the jupyter extension which has also previously been updated and eveything got to work back again. Also turned off Vscode auto update and python auto update too for a while.

**Comment by rchiodo** [comment]
This issue has been replaced by #4796. Please comment there if you're having problems.
