### ISSUE TITLE
Cant import class from another file in the same folder

### ISSUE THREAD

**Issue by ayperos23** [microsoft/vscode-jupyter#4783]
Issue Type: <b>Bug</b>

I cannot import a class from a py file which is in a same folder as mine ipynb. However, with classical Jupyter Notebook in the browser it works (same code and the ipynb is in the same folder as the one opened in VS Code). 
Please fix that

Extension version: 2020.12.414227025
VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:35:15.302Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id c5fb0557-e69b-4c02-9dbe-1d8d8643c669|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600cf:30251589

```

</details>

**Comment by claudiaregio** [comment]
Hi @ayperos23, I am not able to reproduce at this time. 
Could you please provide some additional details on the issue you are experiencing? 
Helpful information includes the logs, errors, pictures or screen recordings when applicable. (https://www.screentogif.com)
