### ISSUE TITLE
Use Stable API to manage secrets

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4784]
Required for https://github.com/microsoft/vscode-jupyter/issues/4737
(Remote Authentication service & use SecretsStorage in stable API)
Lot has changed in authentication service in VSC API (not used)

**Comment by IanMatthewHuff** [comment]
Not sure if this is an exact user validation to check here. But validating based on functionality working + usage of ExtensionContext.secrets.
