### ISSUE TITLE
Cannot correctly run a notebook document after you have moved panes

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#4786]
I believe there are may ways to repro this, but here is the specific repro that I was using.

1. Start VS Code with no documents open
2. Open Document A, run a cell
3. Open Document B
4. Drag Document B side by side with Document A
5. Try to run a cell in Document B

Cell will spin forever and never start.

**Comment by DavidKutu** [comment]
Validated
