### ISSUE TITLE
VS Code Insiders cannot open notebooks

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4796]
# Notebooks broken in insiders

Since this version:

![image](https://user-images.githubusercontent.com/19672699/107831658-6a625e00-6d43-11eb-8da3-c677a7b9693e.png)

VS code insiders is making breaking changes to the proposed API the jupyter extension uses to open notebooks. Until we can get a new build out, we recommend going back to stable. 

This issue will track our progress on making a new build just for insiders.

You can also go back to an older build of insiders if you want to continue using it. See directions here on how to do that:
microsoft/vscode#46089 (comment)

**Comment by peterschmidt85** [comment]
I have the same issue.

**Comment by ShuhuaGao** [comment]
Same issue https://github.com/microsoft/vscode-jupyter/issues/4806

**Comment by ShuhuaGao** [comment]
After the latest update of VS Code Insiders, the error message becomes "Unable to open 'IL_BC.ipynb': Cannot read property 'Markdown' of undefined.". 

Version: 1.54.0-insider (user setup)
Commit: a699ffaee62010c4634d301da2bbdb7646b8d1da
Date: 2021-02-15T05:17:48.792Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by furkantektas** [comment]
Same issue here:
`Unable to open 'XXX.ipynb': Cannot read property 'Code' of undefined.`

```
Version: 1.54.0-insider
Commit: a699ffaee62010c4634d301da2bbdb7646b8d1da
Date: 2021-02-15T05:15:52.209Z (5 hrs ago)
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

Jupyter versions (conda):

jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_core              4.7.1            py37hf985489_0    conda-forge
jupyter_server            1.3.0            py37hf985489_0    conda-forge
jupyterlab                3.0.7              pyhd8ed1ab_0    conda-forge
jupyterlab_code_formatter 1.4.4              pyhd8ed1ab_0    conda-forge
jupyterlab_execute_time   2.0.1              pyhd8ed1ab_1    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.2.0              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
```

**Comment by ShuhuaGao** [comment]
> You can also go back to an older build of insiders

The previous Insider version 1.53.0 works, which can be downloaded from https://vscode-update.azurewebsites.net/1.53.0-insider/win32-x64/insider  (for Windows).

In settings, search "update: Mode" and set it to "manual" to disallow automatic update. Different versions of VS code can co-exist but you need to start the specific version by double-clicking _Code - Insiders.exe_ in the specific folder.

**Comment by codekitchen** [comment]
For Apple Silicon Macs, the link you want is https://vscode-update.azurewebsites.net/1.53.0-insider/darwin-arm64/insider (it took me a few minutes to figure that out, so maybe that'll help others)

**Comment by rohan-paul** [comment]
For Linux (Ubuntu 20.04), got the .deb file for **1.53.0** from here.

[vscode-update.azurewebsites.net/1.53.0-insider/linux-deb-x64/insider](https://vscode-update.azurewebsites.net/1.53.0-insider/linux-deb-x64/insider)

**Comment by ayim** [comment]
Same issue here

![image](https://user-images.githubusercontent.com/10951869/108113588-8e2be980-704c-11eb-9bbc-5d5044560c44.png)

**Comment by frenkcleven** [comment]
For completeness: [1.53.0 Insider build for Intel Macs](https://vscode-update.azurewebsites.net/1.53.0-insider/darwin/insider).

**Comment by taisbak** [comment]
You need to add -user to the download url if vscode is installed using user set-up, e.g.:
[https://vscode-update.azurewebsites.net/1.53.0-insider/win32-x64-user/insider](url)

**Comment by DonJayamanne** [comment]
Just an update, we are looking into this, and aware of the issues.
The Insiders Notebook API has changed significantly and are in the process of updating the code accordingly.

**Comment by rednag** [comment]
> Same issue here:
> `Unable to open 'XXX.ipynb': Cannot read property 'Code' of undefined.`
> 
> ```
> Version: 1.54.0-insider
> Commit: a699ffaee62010c4634d301da2bbdb7646b8d1da
> Date: 2021-02-15T05:15:52.209Z (5 hrs ago)
> Electron: 11.2.3
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Darwin x64 20.3.0
> 
> Jupyter versions (conda):
> 
> jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
> jupyter_core              4.7.1            py37hf985489_0    conda-forge
> jupyter_server            1.3.0            py37hf985489_0    conda-forge
> jupyterlab                3.0.7              pyhd8ed1ab_0    conda-forge
> jupyterlab_code_formatter 1.4.4              pyhd8ed1ab_0    conda-forge
> jupyterlab_execute_time   2.0.1              pyhd8ed1ab_1    conda-forge
> jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
> jupyterlab_server         2.2.0              pyhd8ed1ab_0    conda-forge
> jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
> ```

Same issue - for now I'm working with the normal VSCode where notebooks are running.

**Comment by Sayam753** [comment]
I also need to set 
```json
    "update.mode": "none"
```
in settings.json to disable the upgrade from 1.53 to 1.54 insiders version.

**Comment by astrowonk** [comment]
Since Insiders is the only way to use try  the new Notebook editor (as far as I know) can you please just enable some opt-in preference to the new editor in stable/release VS Code 1.53? Or via a nightly build of the extension (like Remote has).

Every time I try the new notebook editor I'm thwarted by some incompatibility with Insiders. It'd be nice to just use it independently of needing VS Code insiders, if that's possible.

**Comment by DonJayamanne** [comment]
Just an update to everyone trying to use the Jupyter extension in Insiders.
We're working on this & have managed to fix most of the issues, unfortunately we're unable to publish the extension due to an upstream issue https://github.com/microsoft/vscode/issues/116888 

In the mean time anyone interested, can download the following VSIX & use this: https://github.com/microsoft/vscode/issues/116888

**Comment by jaymegordo** [comment]
@DonJayamanne Thanks a lot! Jupyter native notebooks is again working for me on 1.54.0 insiders.

**Comment by DonJayamanne** [comment]
A new extension has been published to the marketplace with the fixes.
Please ensure you update to the latest version of VS Code insiders & the latest version of the Python extension `2021.3.xxxx`

**Comment by DonJayamanne** [comment]
Moving to validate

**Comment by rchiodo** [comment]
For me I had to update the juypter extension and reload VS code for this to work with VS code insiders.

**Comment by rchiodo** [comment]
Nope sorry still not working. See this issue:
https://github.com/microsoft/vscode/issues/117445

It works partially now. If you use the 'Open With' editor you can open a notebook in insiders again:

![image](https://user-images.githubusercontent.com/19672699/108889938-cccc2180-75c1-11eb-9e90-ea47732911a1.png)

**Comment by frenkcleven** [comment]
> Nope sorry still not working. See this issue:
> [microsoft/vscode#117445](https://github.com/microsoft/vscode/issues/117445)
> 
> It works partially now. If you use the 'Open With' editor you can open a notebook in insiders again:
> 
> ![image](https://user-images.githubusercontent.com/19672699/108889938-cccc2180-75c1-11eb-9e90-ea47732911a1.png)

Same for me. But at least this is usable for now. Thanks!

**Comment by AndrewLaganaro** [comment]
Returned to 1.53.0 version on windows 10, also rolled back the jupyter extension which has also previously been updated and eveything got to work back again. Also turned off Vscode auto update and python auto update too for a while.

**Comment by gusbemacbe** [comment]
After updating the Python extension and reinstaling the @DonJayamanne's VSIX extension, the Jupyter notebooks work here now, but I receive two errors from Python extension:

![imagem](https://user-images.githubusercontent.com/2257024/108922237-830d2680-7615-11eb-9d01-2244440603a7.png)

**Comment by rchiodo** [comment]
Sorry but we forgot to mention you also need the insiders version of the python extension. It has similar problems with the API.

You can do this automatically with this setting here:

![image](https://user-images.githubusercontent.com/19672699/108922363-d9fe0600-75eb-11eb-82f7-c06c432ad155.png)

**Comment by gusbemacbe** [comment]
> Sorry but you also need the insiders version of the python extension. It has similar problems with the API.
> 
> You can do this automatically with this setting here:
> 
> ![image](https://user-images.githubusercontent.com/19672699/108922363-d9fe0600-75eb-11eb-82f7-c06c432ad155.png)

It worked now, thank you!

Too bad that VSCode Insiders with Jupyter Notebook (even if I always trusted the notebooks) does not support Jupyter Notebook's Python Markdown extension.

**Comment by rchiodo** [comment]
> Too bad that VSCode Insiders with Jupyter Notebook (even if I always trusted the notebooks) does not support Jupyter Notebook's Python Markdown extension.

@gusbemacbe Do you want to log a suggestion for this?

**Comment by gusbemacbe** [comment]
> > Too bad that VSCode Insiders with Jupyter Notebook (even if I always trusted the notebooks) does not support Jupyter Notebook's Python Markdown extension.
> 
> @gusbemacbe Do you want to log a suggestion for this?

Yes, I refer to the https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/python-markdown/readme.html.

**Comment by virtu** [comment]
After upgrading, notebooks are no longer detected but displayed as plain text in VSCode insiders. Any suggestions?

**Comment by jeanga** [comment]
Right click & "open with" did the job for me.

**Comment by virtu** [comment]
> Right click & "open with" did the job for me.

Thanks! Should be fixed, though, so the regular approach works again.

**Comment by eduardopaul** [comment]
Working like a charm! Thanks all for the amazing extension. Do you have any idea when this new notebook interface should be released in VSCode's regular version?

**Comment by taisbak** [comment]
> Working like a charm! Thanks all for the amazing extension. Do you have any idea when this new notebook interface should be released in VSCode's regular version?

Yes it does! Thank you.

**Comment by marcbernot** [comment]
Thanks notebooks work in 1.54. Is the live sharing of notebooks supposed to work? I never managed to get it working. Tips would be appreciated

**Comment by rchiodo** [comment]
> Thanks notebooks work in 1.54. Is the live sharing of notebooks supposed to work? I never managed to get it working. Tips would be appreciated

Live share of notebooks is a work in progress. You can track that here I believe:
https://github.com/MicrosoftDocs/live-share/issues/3301
https://docs.microsoft.com/en-us/visualstudio/liveshare/reference/notebooks

**Comment by rchiodo** [comment]
I'm closing this bug as the latest VS code insiders and the latest Jupyter extension and latest python insiders extension all seem to be working.

Going forward we hope to be able to ship the jupyter extension more often to deal with breaking issues from VS code on a much quicker cadence.

Thanks for your patience.

**Comment by rchiodo** [comment]
> Do you have any idea when this new notebook interface should be released in VSCode's regular version?

@eduardopaul this is actively being pursued. We're working on testing it with a few customers first to see how the new version compares to the old one. Right now your best bet for using the new interface is to use the insiders version.

**Comment by gusbemacbe** [comment]
@rchiodo, and Jupyter Notebook's Python Markdown extension?

**Comment by rchiodo** [comment]
@gusbemacbe I suggest you log a new issue for the markdown extension. Until that happens we won't be able to tell how many other people want it. Meaning right now it's not planned at all.
