### ISSUE TITLE
Unable to open 'file_name.ipynb': Cannot read property 'Rich' of undefined.

### ISSUE THREAD

**Issue by SamuelManechez** [microsoft/vscode-jupyter#4806]
Issue Type: <b>Bug</b>

I want to open jupyter notebook on vscode insider but since the last update I have this issue : Unable to open 'file_name.ipynb': Cannot read property 'Rich' of undefined.

This file doesn't work on the standard vscode.

I hope you will patch this quickly.

Thanks !

Extension version: 2020.12.414227025
VS Code version: Code - Insiders 1.54.0-insider (6ac9a3ecb3698e82bf901f11bbb5940f6bc3c197, 2021-02-12T05:14:15.897Z)
OS version: Linux x64 5.4.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|30.97GB (28.41GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 187279dd-b699-4c1d-94e3-4eb1f04f2c19|
|Screen Reader|no|
|VM|67%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt600cf:30251589
core-portspanel:30233467
coreuntitledfile:30249963
openwsldoc:30257222

```

</details>

**Comment by deepan-py** [comment]
Same error

**Comment by claudiaregio** [comment]
This should have been fixed with our last Jupyter insider release. Please make sure to reload and have the latest Jupyter Insider's extension.

**Comment by ShuhuaGao** [comment]
Same error. Cannot open the existing .ipynb notebooks since the last update.

VS Code Insiders
- Version: 1.54.0-insider (user setup)
- Commit: 6ac9a3ecb3698e82bf901f11bbb5940f6bc3c197
- Date: 2021-02-12T05:13:16.111Z

Jupyter: v2020.12.414227025

**Comment by deepan-py** [comment]
Unable to open 'intro_.ipynb': Cannot read property 'Markdown' of undefined.

**Comment by claudiaregio** [comment]
Hi @SamuelManechez and @deepan-py , please see #4796 for more details

**Comment by jmsquare** [comment]
Same error
