### ISSUE TITLE
Data Viewer throws error "Python package 'pandas' is required for viewing data." even though pandas is installed

### ISSUE THREAD

**Issue by NaokiTakahashiRad** [microsoft/vscode-jupyter#4808]
## Environment data
-   VS Code version: 1.53.0
-   Jupyter Extension version: v2020.12.414227025
-   Python Extension version: v2021.1.502429796
-   OS version: Mac OS10.15.17 (Catalia)
-   Python version: 3.66
-   Type of virtual environment used: pyenv, venv, pip install
-   Jupyter server running: Local 
-   Pandas version: 1.1.5

## Expected behaviour
Interactive session running .py file or ipynb file. 
Data (dataframe, list etc) are created.  
Open Variable Explorer and click on Data Viewer icon.  
Data Viewer opens and shows data.  

## Actual behaviour
Note, this is similar to issue  #1411.
When the Data Viewer icon is clicked, it throws error "Python package 'pandas' is required for viewing data." in a pop-up window. 
Note pandas is installed in environment and used to create the data.  
When "install" is clicked in the pop-up window, the terminal window shows:  
Executing command in shell >> /Users/username/venv/venvname/bin/python /Users/username/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py pip install -U pandas
Requirement already satisfied: pandas in /Users/username/venv/venvname/lib/python3.6/site-packages (1.1.5)  

Then, the Data Viewer opens and shows data as expected.  

This happens each time Data Viewer is clicked (even in the same session).

**Comment by joyceerhl** [comment]
Hi @NaokiTakahashiRad, thanks for reporting a bug. I cannot repro this with macOS 10.14.6, VS Code 1.53.0, Python 3.6.6 via pyenv with venv, local kernel, Jupyter extension v2020.12.414227025. Is the kernel that the notebook was started with the same as `/Users/username/venv/venvname/bin/python`? And would you mind providing debug logs from the Jupyter output panel? You can turn on debug logging by setting 'jupyter.logging.level' to 'debug' in your settings.json, reloading VS Code, repeating repro steps and looking for the Jupyter option in the dropdown under the Output tab in the terminal pane. Thanks and sorry for the bother!

**Comment by NaokiTakahashiRad** [comment]
Thank you. 

Regarding the kernel, it is Python 3.6.6 64-bit, but not sure which (~/.pyenv/shims/python, ~/venv/venvname/bin/python, ~/.pyenv/versions/3.6.6/bin/python) one was selected. ~venv/venvname... was darkened when clicked on jupyter kernel panel. I manually chose ~venv/venvmane.. and it is reproducible.

The Debug log is attached.

[Info 2021-02-15 22:24:48: Python Daemon .log](https://github.com/microsoft/vscode-jupyter/files/5986078/Info.2021-02-15.22.24.48.Python.Daemon.log)

**Comment by NaokiTakahashiRad** [comment]
I was able to fix the issue by doing the following:
brew install xz  (install lzma)
pyenv uninstall 3.6.6, then pyenv install 3.6.6

Thank you!
