### ISSUE TITLE
(Feature request) Line and Col ticker in the status bar

### ISSUE THREAD

**Issue by kjczarne** [microsoft/vscode-jupyter#4810]
Hi, first of all thanks for making this amazing tool!

I was wondering why the Line/Column ticker (Editor Selection) that normally appears in VSCode status bar isn't appearing in the Notebooks. I used this extensively in Jupyter Lab before I switched to VSCode Jupyter and it's super-useful to have when working with F# code. Could that be added to display line and column where the cursor is currently at within a given cell or is it not currently possible?

**Comment by joyceerhl** [comment]
Thanks for the feedback @kjczarne. Line numbers aren't yet supported in VS Code notebooks, and this is being tracked as #106054.  Out of curiosity would you expect the line number displayed to be relative to the current cell or the entire notebook?

**Comment by kjczarne** [comment]
Great to hear that this is under consideration! From my point of view the most useful would be displaying this sort of information on a per-cell basis. When F# kernel fails to run some statement it prints an error message that points to the line and column that caused a problem and in Jupyter Lab it's then fairly easy to navigate to said statement. But of course perspectives on the issue might differ. :)

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed with new native support for editing notebooks starting with v1.59 of VS Code.
