### ISSUE TITLE
Markdown not highlighted 

### ISSUE THREAD

**Issue by Sid281216** [microsoft/vscode-jupyter#4812]
## Environment data

-   VS Code version:  1.53.2
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.502429796
-   OS (Windows | Mac | Linux distro) and version: windows 10
-   Python and/or Anaconda version: python 3.9.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pip
-   Jupyter server running: Local 

## Expected behaviour

highlighted markdown

Hi, just started using vscode instead of jupyterlab, I really appreciate your work !!
I have an issue then, like you can see on the screenshot, markdown characters written in latex are not highlighted with a proper color. I also have Latexwrokshop extension installed and texlive
Hope you can help !
## Actual behaviour

![Sans titre](https://user-images.githubusercontent.com/75738466/107879137-67987200-6ed7-11eb-9d97-3cf5be7d079b.png)

**Comment by joyceerhl** [comment]
Thanks for the feedback @Sid281216. We have an existing issue tracking this request and will be closing this in favor of that: https://github.com/microsoft/vscode-jupyter/issues/1547
