### ISSUE TITLE
Pipenv is not used for Jupyter notebooks, as well as root project path

### ISSUE THREAD

**Issue by nfx** [microsoft/vscode-jupyter#4815]
Issue Type: <b>Bug</b>

1. create or open any Pipenv-based workspace (or project... i don't know the terminology)
2. create a Jupyter notebbok (*.ipynb), or use existing one.
3. run something that requires installed libraries in the pipenv
4. see exception that library is not installed.

also, assuming i'm in `notebooks` folder, i had to insert this snipped to `sys.path`. as long as VSCode is launching the notebook, it should prepend not only current directory to sys.path, but also the project root, which holds main python module path though jupyter hooks.

```
import os
sys.path.append(os.path.abspath('..'))
```

Extension version: 2021.1.502429796
VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T16:01:04.046Z)
OS version: Darwin x64 19.6.0

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by joyceerhl** [comment]
HI @nfx, if I'm understanding this issue description correctly, you are expecting that:

1. When in a folder containing a pipenv virtualenv, we should autoselect the Python interpreter associated with the current pipenv as the notebook kernel
2. We should always prepend the parent directory to sys.path

For the second request, you can configure this today by adding the following to your VS Code user settings.json:
```
    "jupyter.runStartupCommands": [ "import os", "import sys", "sys.path.append(os.path.abspath('..'))" ]
```

This will cause us to run that code at kernel startup for your notebooks.

**Comment by greazer** [comment]
Let's track this against the work happening in the Python extension.

**Comment by joyceerhl** [comment]
Assuming I understood the first ask correctly, @karrtikr, does the Python extension support autoselecting pipenv environments as the active Python interpreter?

**Comment by karrtikr** [comment]
No. We did support it earlier, but due to security reasons we cannot run pipenv without user consent, hence the support was removed.

**Comment by joyceerhl** [comment]
Thanks @karrtikr that's great context to have. In that case I believe @nfx would need to manually select a pipenv Python environment as the active Python interpreter.

**Comment by nfx** [comment]
@karrtikr which were the security reasons, btw? I've specified pipenv's interpreter as default interpreter for the project and logically expect it to be picked up as default for all new kernel processes.

@joyceerhl `jupyter.runStartupCommands` is a good "workaround" indeed, thank you. but in the long term it may increase the usability and adoption of extension :)

**Comment by karrtikr** [comment]
>  I've specified pipenv's interpreter as default interpreter for the project 

This doesn't seem to come under autoselection process then. Autoselection is done when no default interpreter is selected. cc @joyceerhl . So security reasons are not relevant here anyways.

**Comment by joyceerhl** [comment]
Sorry for the delayed response here. @nfx if this issue still persists--are you saying that the pipenv interpreter *is* being selected by the Python extension as the active interpreter, but that our Jupyter notebooks are using a different interpreter by default?

**Comment by nfx** [comment]
@joyceerhl it's still not using the pipenv classpath, nope

**Comment by rchiodo** [comment]
This should have been addressed with our path fixes (if the appropriate kernel is run).
https://github.com/microsoft/vscode-jupyter/pull/6518
