### ISSUE TITLE
Add support for "Jupyter: Always Trust Notebooks" setting in Workspace scope

### ISSUE THREAD

**Issue by crsqq** [microsoft/vscode-jupyter#4817]
I think it would be nice to have the ability to trust all notebook within the current workspace without having to trust all notebook generally.

Primarily this would remove the friction of having to manually hit that [Trust] button that pops up for every notebook we open in the editor simply because we're rightly paranoid about enabling the setting at the global User scope and leaving ourselves open to the security vulnerabilities (namely markdown links).

It just makes sense to enable this setting on a per-workspace basis to modulate this trust.

Currently:

<img width="539" alt="98960975-0bd2dd00-24d3-11eb-9216-83675b67bf1d" src="https://user-images.githubusercontent.com/4514040/107893219-35643000-6f2a-11eb-9ba2-03812f54d235.png">

<img width="537" alt="98961218-548a9600-24d3-11eb-891f-f34c0dfc100c" src="https://user-images.githubusercontent.com/4514040/107893218-34cb9980-6f2a-11eb-850d-62703f3e6d5c.png">

**Comment by joyceerhl** [comment]
Thanks for the feedback @crsqq, we'll discuss this as a team at our weekly triage meeting.

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed overall by VS Code's support for trusted workspaces.
