### ISSUE TITLE
vscode insider - in markdown cell inside jupyter notebook  - html not rendering properly

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/vscode-jupyter#4818]
For example in a markdown cell in a Jupyter NB, if I have the below HTML table, its not rendering at all.

```
<table>
    <tr><td>Plane(SVM().fit(D1, C=0.001))</td><td>Plane(SVM().fit(D1, C=1))</td><td>Plane(SVM().fit(D1, C=100))</td></tr>   
</table>
```

And below are my versions.

![image](https://user-images.githubusercontent.com/12703975/107982414-044b3480-6fea-11eb-8fcb-1499421b5929.png)

**Comment by joyceerhl** [comment]
Hi @rohan-paul unfortunately this is due to VS Code itself not supporting plaintext HTML in markdown cells: https://github.com/microsoft/vscode/issues/107192. Will check on what the status of that work is.

**Comment by DonJayamanne** [comment]
@joyceerhl do we have an update on this? Should we check with Peng

**Comment by joyceerhl** [comment]
Renders fine in Insiders now I think?

![image](https://user-images.githubusercontent.com/30305945/119531661-00415800-bd39-11eb-821b-75d3150cb37d.png)

**Comment by joyceerhl** [comment]
Fixed in native notebooks.
