### ISSUE TITLE
Tests are failing due to missing dependency

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4824]
3317 Error 2021-02-16 17:27:33: DataScience Error Error: No matching bindings found for serviceIdentifier: Symbol(IJupyterExtensionBanner)
 Symbol(IJupyterExtensionBanner) - named: DSSurveyBanner

**Comment by joyceerhl** [comment]
@DonJayamanne should be resolved now, please LMK if otherwise
