### ISSUE TITLE
ZMQ Error address in use consistent in Functional Test Group 2

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4829]
![image](https://user-images.githubusercontent.com/19672699/108112699-507a9100-704b-11eb-98e4-5d5f53a717b5.png)

**Comment by rchiodo** [comment]
Chaining doesn't seem to have fixed it. We're already chaining the port promises.

**Comment by greazer** [comment]
Old. Assuming it's been resolved.
