### ISSUE TITLE
Running Default Kernelspecs installed on the system does not save the interpreter used

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#4831]
I have an anaconda environment on my system. It's called functionalTestEnv. It has a kernelspec installed locally to that conda env (not in the global jupyter location). I believe that this is the default kernelspec that jupyter creates (this is an env that I often run Jupyter directly from). The argv points at the interpreter of this conda env, but the display name is just "Python 3." This can be created just by running jupyter notebook from a conda env.

![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/001239d6-6fc4-4197-9c15-d21ad4f3af12)
	
If I select that option and run it's used correctly to run my notebook using the python from that kernelspec file. You can see the sys.executable above.
	
If I save the notebook and open it again, and run it instead of using that same environment it uses the action python interpreter for the folder that I have open.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/ceb1536e-f891-4b40-8e20-afebe3df908c)

**Comment by IanMatthewHuff** [comment]
This is the metadata saved in the file after we run. Nothing to distinguish the interpreter.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/506a96ef-907f-44d7-a3a6-412e83cfd60e)

This is the kernelspec with the interpreter in the argv.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/82a5d989-d990-4649-ae0e-b89cb44fba94)

Situation is a bit odd, as we are surfacing "default" kernelspecs for any pythons that the python extension can find. These are only unique by argv and we don't save that information when we run them.

**Comment by EtienneTetreault** [comment]
I have the same problem here. I also found similar thread on StackOverflow.
https://stackoverflow.com/questions/66285231/visual-studio-code-interactive-window-changing-the-environment-does-not-work.

This all seems pretty recent for everyone (i've just started using Interactive Windows / Jupyter in VsCode, so i have no comparison as to how it worked before).

**Comment by EtienneTetreault** [comment]
Update : *Disclaimer, no screenshot, lots of command... There was a lot of troubleshoot, I didn't think of recording my commands.

In terminal ```jupyter kernelspec list``` list the kernel available to Jupyter. On my console, i was able to see the infamous Python3 on path _user/.local/share/jupyter/kernels/python3_... With the command ```jupyter kernelspec remove python3``` i delete it but another kernel python3 was found on path _user/.local/lib/python3.8/site-packages/ipykernel/resources_. Seems like this path would not be use by VSCode...

After that, when running VSCode Interactive Windows on a python script from my conda environment, the kernel I created for this environment with ```python -m ipykernel install --user --name condaEnvName --display-name "displayEnvName (conda)"``` was automatically selected. Cool.

But, while playing with various python environment in VSCode, I somehow manage to re-create the default Python3 Kernel in _user/.local/share/jupyter/kernels/python3_. It would somehow gain priority on my others kernel so I just delete it again and started to be cautious...

**Comment by DonJayamanne** [comment]
> The argv points at the interpreter of this conda env, but the display name is just "Python 3." This can be created just by running jupyter notebook from a conda env.


@IanMatthewHuff 
Looks like conda environment detection is failing in the core extension.
The Python extnsion is what tells us whehter an interpreter is Conda or other (in this case its missing that info, which leads me to believe core extension is failing here)

**Comment by grg2rsr** [comment]
Current workaround for me is downgrading the jupyter extension to `v2020.12.414227025`
(Ubuntu 20.04)
