### ISSUE TITLE
Interactive Python file commands are missing from command palette

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#4833]
Run Below/Run Cell commands are missing from command palette

**Comment by rchiodo** [comment]
I don't repro this?

![image](https://user-images.githubusercontent.com/19672699/108129979-b8d56c80-7063-11eb-9fac-8ae71d8bba47.png)

**Comment by rchiodo** [comment]
Opening a notebook causes this problem.

**Comment by greazer** [comment]
Shouldn't block tomorrow's release. If trivial, let's fix.

**Comment by joyceerhl** [comment]
FWIW we recently changed context key visibility in palette with https://github.com/microsoft/vscode-jupyter/pull/4769/

**Comment by joyceerhl** [comment]
Looked at our source, `jupyter.havenativecells` is set in response to messages from the interactive window. Once you run cells in the IW, the commands reappear.

**Comment by rchiodo** [comment]
This was caused by our latest bits but the fix is going to affect other things. I think we can put this in the point release.

**Comment by DonJayamanne** [comment]
Validated
