### ISSUE TITLE
Remove redundant code

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4835]
Check 
```
        // On CI we don't need to use keytar for testing (else it hangs).
        if (IS_REMOTE_NATIVE_TEST && this.extensionContext.extensionMode !== ExtensionMode.Production) {
            return this.testingState.get(`${service}#${key}`);
        }

````

**Comment by IanMatthewHuff** [comment]
@DonJayamanne Validation here? The code above seems to exist in encryptedStorage.ts.

**Comment by DonJayamanne** [comment]
Oops, sorry

**Comment by IanMatthewHuff** [comment]
Does it need to be removed? Wasn't 100% sure on this issue here. Presume this was code from before when vscode owned secrets?

**Comment by IanMatthewHuff** [comment]
Closing.

**Comment by IanMatthewHuff** [comment]
Sorry didn't mean to close. Back to parking lot I believe?

**Comment by DonJayamanne** [comment]
THis is still required, else tests crash on CI

**Comment by DonJayamanne** [comment]
This code still seems to be there.

**Comment by DonJayamanne** [comment]
looks like we cannot use keytar on CI, hence closing this issue
