### ISSUE TITLE
Cannot open resource with notebook editor 

### ISSUE THREAD

**Issue by TarjinderSingh** [microsoft/vscode-jupyter#4845]
I cannot open Jupyter Notebooks from the explorer window at the moment. I get the following error. However, if I right-click and "Open in Notebook Editor", the Jupyter notebook opens well. Is there a reason or setting for this?

```
Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed or enabled.
```

**Comment by rchiodo** [comment]
Thanks for the bug. The problem should go away if you try a second time. 

Can you check if you have this entry in your settings.json?

```
  "workbench.editorAssociations": [
    {
      "viewType": "jupyter.notebook",
      "filenamePattern": "*.ipynb"
    }
  ],
```

That should only be enabled in the insiders version of VS code. If you're using the stable version of VS code you shouldn't have that value there.

**Comment by TarjinderSingh** [comment]
I do have that entry in my settings.json. I have two Macs that are synced on the same vscode settings, and one is using the insiders version and one is using the stable version. The stable version one is showing this error. Do you think the shared settings between the two is causing the issue?

**Comment by rchiodo** [comment]
> Do you think the shared settings between the two is causing the issue?

Maybe? I thought insiders and stable wouldn't share the same settings but if they did it would cause the problem.

**Comment by TarjinderSingh** [comment]
OK, I commented out that block and it works on my Stable version but not the Insiders one. The insiders one is showing "Cannot read property 'Code' of Undefined".

So I am guessing that my settings are synced between the two and that block is breaking.

**Comment by rchiodo** [comment]
> The insiders one is showing "Cannot read property 'Code' of Undefined".

This is actually this bug here: #4796. Insiders is not currently working for opening notebooks. VS code made some breaking API changes that we haven't caught up to yet.

**Comment by TarjinderSingh** [comment]
OK, so I don't know why:
```
"workbench.editorAssociations": [
    {
      "viewType": "jupyter.notebook",
      "filenamePattern": "*.ipynb"
    }
  ],
 ```
is appearing in my stable build. But I am changing this locally for now in my stable build and I will wait for the Insiders fix soon.

**Comment by greazer** [comment]
If a user has the editorAssociations setting, then opt them into the native notebook editor experiment.

**Comment by DonJayamanne** [comment]
Validated, did use settings sync but must updated the settings manually
