### ISSUE TITLE
computer crashes when opening and running second interactive pane on different file

### ISSUE THREAD

**Issue by rholland** [microsoft/vscode-jupyter#4846]
## Environment data

-   VS Code version: jan 2021
-   OS and version: windows 10
-   Python version : 3.8

## Expected behaviour
open file run cells in interactive pane
open second file and run cells in interactive pane

## Actual behaviour
on running cells in second file while first pane is still open 
second pane opens but then computer crashes with blue screen

**Comment by rchiodo** [comment]
Thanks for the bug. Very strange that our window could cause a blue screen. What code were you running?

**Comment by greazer** [comment]
A blue screen would be an indication of a bug in a driver or other component that we have no control over.

**Comment by rholland** [comment]
Maybe a driver was the cause but I'm not sure.  I was running the Wise System Monitor and the blue screen reported that was the cause. So I uninstalled it and rebooted.  But it happened again with a different cause (more generic - forgot the label).  So I rebooted again and tried opening a blank notebook.  That was stable.  I then tried opening more notebooks from files.  I opened 6 and they were all stable.  You can close this if you want and I will reopen an issue if I see it again.
