### ISSUE TITLE
Can't run jupyter notebooks in vscode, Command failed: C:/Users/, Windows 10, Anaconda Distributor

### ISSUE THREAD

**Issue by KikeSenpai** [microsoft/vscode-jupyter#4850]
I had solved this problem in issue #4266, but now I am getting a very similar error again, at least the output log looks very similar.

## Environment data

-   VS Code version: 1.53.2 (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.464332847-dev
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: 3.7.9 with conda 4.9.2
-   Type of virtual environment used: conda (base)
-   Jupyter server running: Local

## Expected behaviour

To properly run cells in jupyter notebooks.

## Actual behaviour

When I open a jupyter notebook or try to run a cell in one I get the following error:

`
[Error: Command failed: C:/Users/eaperez/AppData/Local/Continuum/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\eaperez\.vscode\extensions\ms-python.python-2021.1.464332847-dev\pythonFiles\pyvsc-run-isolated.py c:/Users/eaperez/.vscode/extensions/ms-python.python-2021.1.464332847-dev/pythonFiles/printEnvVariables.py

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: "C:/Users/eaperez/AppData/Local/Continuum/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\eaperez\\.vscode\\extensions\\ms-python.python-2021.1.464332847-dev\\pythonFiles\\pyvsc-run-isolated.py c:/Users/eaperez/.vscode/extensions/ms-python.python-2021.1.464332847-dev/pythonFiles/printEnvVariables.py"
`

I allready tried using the lastest extension update, but I got the same error.

**Comment by rchiodo** [comment]
Did you go back to an older python extension? It looks like @DonJayamanne suggested you use an insiders build in #4266 but your output doesn't indicate an insiders build. You might try using a newer build.

https://pvsc.blob.core.windows.net/extension-builds-jupyter-public/ms-python-insiders.vsix

Although your error looks to me like conda is dying. 

Does this work from the a command prompt?

```
C:/Users/eaperez/AppData/Local/Continuum/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\eaperez.vscode\extensions\ms-python.python-2021.1.464332847-dev\pythonFiles\pyvsc-run-isolated.py c:/Users/eaperez/.vscode/extensions/ms-python.python-2021.1.464332847-dev/pythonFiles/printEnvVariables.py
```

**Comment by KikeSenpai** [comment]
I am using the extension insiders build you can see it in the extension directory (ms-python.python-2021.1.464332847-dev), although vscode is not insiders version,

Hello what do you mean by "conda is dying"

I  tried to run this from the command prompt and I got error

`C:/Users/eaperez/AppData/Local/Continuum/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\eaperez.vscode\extensions\ms-python.python-2021.1.464332847-dev\pythonFiles\pyvsc-run-isolated.py c:/Users/eaperez/.vscode/extensions/ms-python.python-2021.1.464332847-dev/pythonFiles/printEnvVariables.py`

But then I fixed the \ for / and add a / between eaperez.vscode so it looks like eaperez/.vscode, this is what I ran

`C:/Users/eaperez/AppData/Local/Continuum/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:/Users/eaperez/.vscode/extensions/ms-python.python-2021.1.464332847-dev/pythonFiles/pyvsc-run-isolated.py c:/Users/eaperez/.vscode/extensions/ms-python.python-2021.1.464332847-dev/pythonFiles/printEnvVariables.py`

This ran successfully, this is output

`'e8b39361-0157-4923-80e1-22d70d46dee6'
{"ALLUSERSPROFILE": "C:\\ProgramData", "APPDATA": "C:\\Users\\eaperez\\AppData\\Roaming", "ASL.LOG": "Destination=file", "COMMONPROGRAMFILES": "C:\\Program Files\\Common Files", "COMMONPROGRAMFILES(X86)": "C:\\Program Files (x86)\\Common Files", "COMMONPROGRAMW6432": "C:\\Program Files\\Common Files", "COMPUTERNAME": "MBOICSC36", "COMSPEC": "C:\\WINDOWS\\system32\\cmd.exe", "CONDA_BAT": "C:\\Users\\eaperez\\AppData\\Local\\Continuum\\anaconda3\\condabin\\conda.bat", "CONDA_DEFAULT_ENV": "base", "CONDA_EXE": "C:\\Users\\eaperez\\AppData\\Local\\Continuum\\anaconda3\\condabin\\..\\Scripts\\conda.exe", "CONDA_PREFIX": "C:\\Users\\eaperez\\AppData\\Local\\Continuum\\anaconda3", "CONDA_PROMPT_MODIFIER": "(base) ", "CONDA_PYTHON_EXE": "C:\\Users\\eaperez\\AppData\\Local\\Continuum\\anaconda3\\python.exe", "CONDA_SHLVL": "1", "DRIVERDATA": "C:\\Windows\\System32\\Drivers\\DriverData", "HOMEDRIVE": "C:", "HOMEPATH": "\\Users\\eaperez", "LOCALAPPDATA": "C:\\Users\\eaperez\\AppData\\Local", "LOGONSERVER": "\\\\MBDOMAIN01", "NUMBER_OF_PROCESSORS": "2", "ONEDRIVE": "C:\\Users\\eaperez\\OneDrive", "ONEDRIVECONSUMER": "C:\\Users\\eaperez\\OneDrive", "OS": "Windows_NT", "PATH": "C:\\Users\\eaperez\\AppData\\Local\\Continuum\\anaconda3;C:\\Users\\eaperez\\AppData\\Local\\Continuum\\anaconda3\\Library\\mingw-w64\\bin;C:\\Users\\eaperez\\AppData\\Local\\Continuum\\anaconda3\\Library\\usr\\bin;C:\\Users\\eaperez\\AppData\\Local\\Continuum\\anaconda3\\Library\\bin;C:\\Users\\eaperez\\AppData\\Local\\Continuum\\anaconda3\\Scripts;C:\\Users\\eaperez\\AppData\\Local\\Continuum\\anaconda3\\bin;C:\\Users\\eaperez\\AppData\\Local\\Continuum\\anaconda3\\condabin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files\\OpenVPN\\bin;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files (x86)\\IBM\\Client Access\\Emulator;C:\\Program Files (x86)\\IBM\\Client Access\\Shared;C:\\Program Files (x86)\\IBM\\Client Access;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn;C:\\Program Files (x86)\\Calibre2;C:\\Users\\eaperez\\AppData\\Local\\Microsoft\\WindowsApps;.;C:\\Users\\eaperez\\AppData\\Local\\Programs\\Microsoft VS Code\\bin", "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "PROCESSOR_ARCHITECTURE": "AMD64", "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 61 Stepping 4, GenuineIntel", "PROCESSOR_LEVEL": "6", "PROCESSOR_REVISION": "3d04", "PROGRAMDATA": "C:\\ProgramData", "PROGRAMFILES": "C:\\Program Files", "PROGRAMFILES(X86)": "C:\\Program Files (x86)", "PROGRAMW6432": "C:\\Program Files", "PROMPT": "(base) $P$G", "PSMODULEPATH": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules", "PUBLIC": "C:\\Users\\Public", "SESSIONNAME": "Console", "SYSTEMDRIVE": "C:", "SYSTEMROOT": "C:\\WINDOWS", "TEMP": "C:\\Users\\eaperez\\AppData\\Local\\Temp", "TMP": "C:\\Users\\eaperez\\AppData\\Local\\Temp", "USERDNSDOMAIN": "MAYOREO.BIZ", "USERDOMAIN": "MAYOREO", "USERDOMAIN_ROAMINGPROFILE": "MAYOREO", "USERNAME": "eaperez", "USERPROFILE": "C:\\Users\\eaperez", "WINDIR": "C:\\WINDOWS"}`

**Comment by rchiodo** [comment]
This sounds like it might be the problem. 

```
add a / between eaperez.vscode so it looks like eaperez/.vscode
```

It might just be our output is incorrect, but if that backslash is not appearing in the actual command, that would explain the error.

Can you try a newer build? It's at the same location. The one you have is a month old.

**Comment by KikeSenpai** [comment]
I ran it using v2021.2.576481509 and it fixed the issue, thanks.
