### ISSUE TITLE
set_next_input marks cell as executed (and updates the execution count)

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4857]
![image](https://user-images.githubusercontent.com/19672699/108282777-0a026080-7137-11eb-953d-0ab6b1070dbc.png)

**Comment by DonJayamanne** [comment]
Closing, doesn't repro anymore. Moving to validate

**Comment by IanMatthewHuff** [comment]
Verified.
![image](https://user-images.githubusercontent.com/812783/151460374-163c6576-dc34-4290-a84f-bb593292d3e9.png)
