### ISSUE TITLE
Notebook welcome page override notebook editor

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4858]
Issue Type: <b>Bug</b>

* Install Jupyter on 1.53.2
* Open a `ipynb` file
* File is opened, in a few seconds, it's overriden by the welcome page, which is also a notebook editor

Since I already open the notebook editor, maybe we don't need to show the welcome page anymore. This can be done by checking `window.activeNotebookEditor`.

Extension version: 2021.1.499599561-dev
VS Code version: Code - Insiders 1.54.0-insider (3f0d8a14759cddea93f0dbddc12a4ef1e5586e86, 2021-02-17T07:39:48.715Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.93GB free)|
|Process Argv|--crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanel:30257802
coreuntitledfile:30249963
wslfolderdoccf:30257852

```

</details>

**Comment by greazer** [comment]
The intention here is to override the notebook the user opened once with the welcome notebook. If that's what you're saying, then this is by design. However, if the Welcome notebook is popping up more than once, please let use know and reopen.
