### ISSUE TITLE
Enhancement to "create new blank jupyter notebook" command

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#4859]
1. `"Jupyter: Create new blank Jupyter notebook"` command to be changed to `"Notebook: Create new blank notebook"`
2. If only the Jupyter extension is installed, the command works as is today. 
3. If other extensions are installed on user's machine that build on top of the Jupyter extension, invoking the `"Notebook: Create new blank notebook"` should bring up the quick pick with the extension names as options. 

Ex. 
User has both Jupyter extension and .NET extension
User invokes `"Notebook: Create new blank notebook"` command
Quick pick opens up with "Jupyter" and ".NET Interactive" as options

**Comment by DonJayamanne** [comment]
**Proposed API:**
* `registerNewNotebookContent(options: {defaultCellLangauge})`
Based on the call stack we know what extension called this.
This information will be used to populate the dropdown list displayed when user clicks `Create new blank notebook`
* `Jupyter` (our extension Id)
* < Extension name based on the call stack> (similar to what we do with AML today)

* `createBlankNotebook(options: {defaultCellLangauge}): NotebookDocument`
.NET team will register their own command `Create Blank .NET Interactive Notebook`
When user selects that command, the .NET extension will invoke this new API.
Or should we just get them to invoke the command `jupyter.createnewnotebook` and pass in an options object `{defaultCellLangauge}`.
The problem with the command is that it doesn't feel like a proper API thats surfaced for use by others.

@rchiodo @IanMatthewHuff @DavidKutu @joyceerhl /cc

**Comment by DonJayamanne** [comment]
@brettfo /cc

**Comment by IanMatthewHuff** [comment]
Hmmm, are you saying that the dropdown list is populated by the names of the extensions? That doesn't quite seem right. The extension name might not be relevant to what the user is looking for. Also that doesn't open up the possibility for an extension to contribute more items to the list. 

I would think that it might be nice to have the extension name in the details tag and then extension can contribute a display name for the type of notebook that they were creating. Might even get rid of "blank" in the command prompt as we could also create different types of notebook skeletons.

Command name -> Notebook: Create new notebook

Dropdown:

- New Python notebook
  - Jupyter
- Matplotlib Sample notebook
  - Jupyter
- New C# notebook
  - .NET Interactive
- New F# notebook
  - .NET Interactive

**Comment by DonJayamanne** [comment]
Awesome idea, however that feels like something we should do as a separate spec (i.e. an extension on top of this work, & based on feedback - would users like such a thing, do they use the new commands, etc) - i.e. separate spec.

Or should we just go with the snippets (I recall @claudiaregio working on something similar - saving cells as snippets, that could be related & make this unnecessary).
I.e. why not do the same for python files, create sample python file for Matplotlib or tensort boards - I think the reason we don't want that is because snippets is the solution for regular files.

@claudiaregio /cc

**Comment by claudiaregio** [comment]
> Hmmm, are you saying that the dropdown list is populated by the names of the extensions? That doesn't quite seem right. The extension name might not be relevant to what the user is looking for. Also that doesn't open up the possibility for an extension to contribute more items to the list.
> 
> I would think that it might be nice to have the extension name in the details tag and then extension can contribute a display name for the type of notebook that they were creating. Might even get rid of "blank" in the command prompt as we could also create different types of notebook skeletons.
> 
> Command name -> Notebook: Create new notebook
> 
> Dropdown:
> 
> * New Python notebook
>   
>   * Jupyter
> * Matplotlib Sample notebook
>   
>   * Jupyter
> * New C# notebook
>   
>   * .NET Interactive
> * New F# notebook
>   
>   * .NET Interactive

I find this flow too complicated for creating blank notebooks. Too many languages, too many "types" of notebooks, too many combinations of languages and "types of notebooks". 
As Don mentioned, Notebook Templates should provide the solution implied here. Extensions will be able to contribute out of the box templates there

**Comment by IanMatthewHuff** [comment]
Sure that's fair to not want to complicate things. I guess I still would disagree with the dropdown having the name of the extension. I don't believe that would mean anything to the user. Having at least a display name surfaced by the extension seems clutch.

**Comment by DonJayamanne** [comment]
Here's the proposed UI:
1. First select the command from the command palette
![Screen Shot 2021-02-19 at 13 01 21](https://user-images.githubusercontent.com/1948812/108561244-bddc2b00-72b2-11eb-8a27-0c592eb58b9f.png)

2. New options
![Screen Shot 2021-02-19 at 13 01 27](https://user-images.githubusercontent.com/1948812/108561245-bf0d5800-72b2-11eb-8f7d-16b7eb8b5c02.png)

**Comment by IanMatthewHuff** [comment]
@DonJayamanne I had a comment above that I'd still like to push for a bit, though I'm willing to be voted down of course. Having a display name would be an improvement. ms-toolsas.jupyter and ms-dotnettools.dotnet-interactive-vscode are not meaningful to customers. I'd rather have extensions contribute a display name than show the Extension display name below that as the detail.

**Comment by DonJayamanne** [comment]
> I'd rather have extensions contribute a display name than show the Extension display name below

Sure, I'll add support for that in the API.

**Comment by claudiaregio** [comment]
Quick note, the command should have "Jupyter" removed from the name 

--> Just "create new blank notebook"

**Comment by DonJayamanne** [comment]
# How to validate
Install the `TypeScript Notebook` extension from marketplace (`extension id = `typescript-notebook`).
This uses the new API to register an option in the dropdown list.

**Comment by rchiodo** [comment]
Validated.
