### ISSUE TITLE
Kernels not destroyed when a Native Editor is closed

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4864]
This might be an issue on user machines as kernels do not get disposed & we don't have enough time to dispose these things when vsc shuts down.
I believe this is a regression, we recently removed some code that killed kernels when a notebook is closed (we might want to check when notebook documents are closed & kill the corresponding kernel).

**Comment by IanMatthewHuff** [comment]
Hmm, disposeResourceRelatedToNotebookEditor is getting called on close. Have to look what else is going on here.

**Comment by IanMatthewHuff** [comment]
@DonJayamanne Exactly what were you seeing left over? Currently when a native notebook is shut down (after running a cell so that it has a notebook) I'm seeing the dispose methods of both the JupyterNotebookBase and BaseJupyterSession are hit. Is there just a process left over?

**Comment by DonJayamanne** [comment]
When i close a notebook, I can re-open it and run a cell again & the execution counter increase instead of starting from 1, meaning its using an existing kernel (which should have been killed off when we closed the editor).
Thats basically how I came across the issue (it seemed way too fast to run a cell, then realized it was using an alraedy running kernel).

**Comment by IanMatthewHuff** [comment]
@DonJayamanne It's no repro currently for me. I get a Notebook and a Session shutdown when I close the document. Then if I re-open I get a new connection message and a fresh execution count.
![image](https://user-images.githubusercontent.com/812783/108436705-c7a55600-7200-11eb-8945-3ea6baec8157.png)

**Comment by DonJayamanne** [comment]
Ok, let me try it again. FYI - I was using insiders yesterday/today when i ran into this issue.

**Comment by DonJayamanne** [comment]
Yes, can still repro in main branch + vscode insiders.

**Comment by IanMatthewHuff** [comment]
Per convo on teams it doesn't repro on release + stable, so not related to the shipped dispose change. I'll pick back up as soon as insiders + main is up and running.

**Comment by IanMatthewHuff** [comment]
I did see this when testing the newest bits. But didn't get a chance to look into it. Deassigning as I'll be oof.

**Comment by DonJayamanne** [comment]
Unable to repro, moving to valdiate.
Please test in latest insiders & main.

**Comment by rchiodo** [comment]
What are we looking for here? Closing VS code always kills all sub processes for me on Windows.

**Comment by DonJayamanne** [comment]
> sing VS code always kills all sub processes for me on Windows.

That's great.

A simple test is:
* Open a notebook
* Run a cell
* Close the notebook
* Open it again, run the same cell & execution count should start from `1`, previously it would start from `2`

**Comment by rchiodo** [comment]
On main with release branch I can still repro. Was this only fixed in main?

**Comment by IanMatthewHuff** [comment]
Something else must be going on here to cause this state. When filed, Don was seeing it when he was fixing insiders I believe. I checked at that point and could not repro in either Release + Stable, or Main + Insiders. Then when validating Don's release fix VSIX I was seeing the issue repro. And now it seems that Rich is seeing it in Main + Release, which hasn't changed, or have more fixes gone in there since I've been out?

Per our Teams thread Rich could also not see it in Release bits on 2/18.

**Comment by DonJayamanne** [comment]
> On main with release branch I can still repro. Was this only fixed in main?

I couldn't see this in main. Weird.
Will try again today.

**Comment by rchiodo** [comment]
Sorry I said that wrong. I meant on stable with the point release branch.

**Comment by DonJayamanne** [comment]
Oh shoot yes, we have different flavours of the API, will check that.

**Comment by DonJayamanne** [comment]
Found that this is because the API in stable VS Code doesn't trigger the `onDidCloseNotebookDocument` event (a regression, that has since been fixed in insiders).
Moving to validate, as we cannot really fix this in stable & VSC will be releasing a new version some time next week (or after, can't remember).

**Comment by DonJayamanne** [comment]
@rchiodo Please could you validate in insiders.

**Comment by rchiodo** [comment]
Yep works in insiders with latest jupyter insiders from marketplace.

**Comment by IanMatthewHuff** [comment]
Nice, that makes sense given when and where we were seeing the issue.
