### ISSUE TITLE
Export as notebook disappears from command palette after opening a notebook

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4869]
This command here
![image](https://user-images.githubusercontent.com/19672699/108426475-a9375e80-71f0-11eb-8703-392f7cb77f52.png)

**Comment by rchiodo** [comment]
To repro:
- Open python file with cells
- See export command
- Open native notebook
- Go back to python file

Export command will be missing from command palette

**Comment by DavidKutu** [comment]
I can't repro

**Comment by DonJayamanne** [comment]
I too cannot replicate this issue, @rchiodo please feel free to re-open if you can replicate.
I tested in insiders.

**Comment by rchiodo** [comment]
This repros for me every time on stable.

**Comment by joyceerhl** [comment]
Validated in VS Code insiders. I can't open native notebooks in VS Code stable, I get this:
![image](https://user-images.githubusercontent.com/30305945/108920313-4e837580-75e9-11eb-9b36-3e2c9a7b2fd9.png)

**Comment by rchiodo** [comment]
> Validated in VS Code insiders. I can't open native notebooks in VS Code stable, I get this:
> ![image](https://user-images.githubusercontent.com/30305945/108920313-4e837580-75e9-11eb-9b36-3e2c9a7b2fd9.png)

You have to use the release branch to validate in stable still.
