### ISSUE TITLE
Review the new VSC Table API

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4875]
https://github.com/microsoft/vscode/issues/99997
We might want to have a look at this API and how we can use it.
& provide necessary feedback so we can use it for things like variable viewer or the like.

**Comment by IanMatthewHuff** [comment]
Based on our sync meeting update and the creation and our spec list on this issue here:
https://github.com/microsoft/vscode/issues/118115

I'm going to resolve this issue as I believe the review part of this is done.
