### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mavaddat** [microsoft/vscode-jupyter#4890]
- Issue Type: `Performance`
- Extension Name: `jupyter`
- Extension Version: `2021.2.576440691`
- VS Code version: Code - Insiders 1.54.0-insider (a699ffaee62010c4634d301da2bbdb7646b8d1da, 2021-02-15T05:17:48.792Z)
- OS version: Windows_NT x64 10.0.21313

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz (4 x 2990)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.66GB free)|
|Process Argv|--crash-reporter-id 5fbb05cc-8424-46f5-a920-45fc0475991e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
core-portspanel:30257802
pythontb:30258533
wslfolderdoccf:30257852

```

</details>

[ms-toolsai.jupyter-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-jupyter/files/6016470/ms-toolsai.jupyter-unresponsive.cpuprofile.txt)

**Comment by DavidKutu** [comment]
Thanks for letting un know @mavaddat. Your profiler tells me that there's a problem with inversify, specifically on the function _createSubRequests on planner.js. I tried recording a profile when activating the extension and got a normal execution. 

What did you do in the extension that you recorded?
Also, did it stop the extension from working?

**Comment by mavaddat** [comment]
> Thanks for letting un know @mavaddat. Your profiler tells me that there's a problem with inversify, specifically on the function _createSubRequests on planner.js. I tried recording a profile when activating the extension and got a normal execution.
> 
> What did you do in the extension that you recorded?

Jupyter and Pyhton were locking up my VS Code when opening a Python file. I stopped the Jupyter extension along with Python and Pylance. After that, Python seemed to be responsive.

> Also, did it stop the extension from working?

Yes, it stopped the Python extension from working. I force stopped the Python, Pylance, Jupyter  set of extensions. There seems to be some kind of problem for me with the native Python extension. Only when I disable the Python extension does the Python Language Server actually work.

**Comment by DavidKutu** [comment]
I see, lets try something. Please disable the Python and Pylance extensions, and leave the Jupyter extension as normal. Try opening a python file and let me know if the issue happens the same.

**Comment by greazer** [comment]
@mavaddat, this is tricky to diagnose without having a repro. Could you try disabling or temporarily uninstalling any other extension you're using and just have Jupyter? Does it repro then?

**Comment by mavaddat** [comment]
> @mavaddat, this is tricky to diagnose without having a repro. Could you try disabling or temporarily uninstalling any other extension you're using and just have Jupyter? Does it repro then? 

Yes, I will give it a shot and get back to you. Does it help if I provide you my system or environment variables? I've set Python to Python310.

**Comment by greazer** [comment]
Closing for now. @mavaddat, if you have been able to gather the info requested, please reopen. System and environment variables are probably not related, but if you provide them, it wouldn't hurt.
