### ISSUE TITLE
Show jupyter icon in editor tab

### ISSUE THREAD

**Issue by PKief** [microsoft/vscode-jupyter#4896]
I looked and have not found an Issue on this yet, which is why I opened a new one.

I am the developer of the Material Icon Theme and there have already been [some requests](https://github.com/PKief/vscode-material-icon-theme/issues/285) why the tabs for the *.ipynb files cannot display the Jupyter file icon. 

![image](https://user-images.githubusercontent.com/12248527/108620109-079b5180-742a-11eb-930a-79cab1882bc1.png)

Right now, it simply shows the default icon - which is shown for all icons that are not known to the icon extension. But in fact, the extension already has a jupyter file icon which is shown for files in the file explorer:

![image](https://user-images.githubusercontent.com/12248527/108620132-36192c80-742a-11eb-8296-03835b9328ca.png)

Do you see any possibility to make it possible for icon extensions in general, to display the jupyter icon also in the tab?

**Comment by DavidKutu** [comment]
Thanks for the suggestion @PKief. Our new Notebook Experience will have a new icon that looks like a notebook. You can try it out right now in VS Code insiders. https://code.visualstudio.com/insiders/

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987.
