### ISSUE TITLE
Include menu-based setting for Pandas display.max_rows

### ISSUE THREAD

**Issue by nfx** [microsoft/vscode-jupyter#4898]
Issue Type: <b>Bug</b>

By default, pandas in Jupyter notebooks displays 50 rows, though as a data scientist, i want to quickly increase the display limit with a click of a button to 100, 500, 1000, 10000.

Extension version: 2021.2.582707922
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by claudiaregio** [comment]
Hi @nfx, Have you used our data viewer feature before? 
Step 5 of our data science tutorial shows how you can view the data: https://code.visualstudio.com/docs/python/data-science-tutorial#_prepare-the-data

**Comment by nfx** [comment]
@claudiaregio i’ve seen the variable view but I haven’t seen yet the drill-down button. Will check it out today and tell :) 

from UX perspective, variables of a notebook should be displayed in a left-hand side of an editor, like in debug mode, not in the top of notebook to require frequent scrolling  :)

**Comment by nfx** [comment]
@claudiaregio that's way better than pd.max_rows! i'd still suggest to put it into left-hand pane, so it's more clear/visible. i'll make another issue for that one.
