### ISSUE TITLE
Create test for .NET extension to verify interaction

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4903]
Test should do the following:

- Create a new notebook

- Open a pre-existing .ipynb with unknown/missing kernelspec
   - by double-clicking a file in File Explorer
   - by opening the file from the VS Code file browser

- Open a pre-existing .ipynb with Python kernelspec
   - by double-clicking a file in File Explorer
   - by opening the file from the VS Code file browser

- Open a pre-existing .ipynb with .NET Interactive kernelspec
    - by double-clicking a file in File Explorer
    - by opening the file from the VS Code file browser

- Reopen without saving

- Round trip with
   - JupyterLab
   - Jupyter Notebook

With or without kernelspec files present

**Comment by joyceerhl** [comment]
Test should also verify #5156.

**Comment by joyceerhl** [comment]
I think this is blocked: https://github.com/microsoft/vscode-jupyter/issues/5406

**Comment by DonJayamanne** [comment]
Moving to triage again.
