### ISSUE TITLE
Option to fit dataframe/table output to column widths

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode-jupyter#4908]
It would be nice if the new jupyter native notebooks either compressed the dataframe column display width by default, or had an option to do so.

When tables have few/narrow columns the display would look better similar to the `rendered html` image below:

jupyter native notebook:
<img width="1434" alt="df_wide" src="https://user-images.githubusercontent.com/29611875/108785677-c2107e80-7526-11eb-9812-488e7105826a.png">

rendered html:
<img width="730" alt="df_fitted" src="https://user-images.githubusercontent.com/29611875/108785681-c341ab80-7526-11eb-9ac6-682de83a789f.png">

I've tried with the `pandas.display` settings like `max_colwidth` but those don't seem to have an effect on the display output.

**Comment by DavidKutu** [comment]
Thanks for the suggestion @jaymegordo. I'll bring it up in our next meeting.

**Comment by DonJayamanne** [comment]
@DavidKutu please move this upto VS Code as they own the rendering of tables (via HTML)
