### ISSUE TITLE
Update release plan to remove `-dev` `-rc` from the versions

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4912]

**Comment by jaymegordo** [comment]
@DonJayamanne will this apply to the jupyter extension only, or python as well?

Eg if we're on the daily insiders release for both python and jupyter, can we expect to no longer see the "-dev" suffix?

**Comment by greazer** [comment]
No there is no more suffix. To tell it'll just be based on the version number itself.
