### ISSUE TITLE
Native Notebooks - Cannot open notebook in insiders

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#4918]
## Environment data

-   VS Code version: 1.54.0 - insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.3.593162453
-   Python Extension version (available under the Extensions sidebar): v2021.3.579822299-dev
-   OS and version: Windows 19042.804
-   Python and/or Anaconda version: 3.7.6
-   Type of virtual environment used: conda
-   Jupyter server running: Local 

### What works 
*If I use the command "Create new jupyter notebook"
*If I right click on a notebook in file explorer and choose "Open with notebook editor" 
*If I right click on a notebook in file explorer and choose "Open with...", "Jupyter Notebooks (preview)" 

### What doesn't work
*If I click on a notebook in file explorer -> opens as JSON
*If I right click on a notebook in file explorer and choose "Open with...", "Jupyter" -> it hangs forever never works

**Comment by DonJayamanne** [comment]
Doesn't work for me either.

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode/issues/117445

**Comment by junrenshi** [comment]
As of today, Jupiter is still not working.  Develop tools report "extension 'ms-toolsai.jupyter' failed: Cannot read property 'viewType' of undefined.".

Python and Jupyter are all in the "daily" update channel.  Jupyter version v2021.3.600686576, Python version v2021.2.582707922.  Vscode-insider version informations are as follows:

Version: 1.54.0-insider
Commit: e590188f17162393f50feec19263398e6fe02d13
Date: 2021-02-26T20:39:49.367Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0

**Comment by DonJayamanne** [comment]
@junrenshi This should be fixed.
Please update to the latest insider version of VS Code.

**Comment by IanMatthewHuff** [comment]
Validated. Looks good in both scenarios to me.

**Comment by IanMatthewHuff** [comment]
Whoops, @DonJayamanne sorry was validating at the same time that you closed. Accidentally reopened it. Will close.
