### ISSUE TITLE
Log ICommandManager.executeCommand telemetry

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4926]
Seems VS code doesn't track our usage of this API so we need to add this ourselves.

**Comment by greazer** [comment]
Would be good to be able to tell why each call to this function occurs (to understand if the user explicitly did an action to call this or not).

**Comment by IanMatthewHuff** [comment]
Validated.
nfo Jupyter Extension: 2021-03-26 14:12:49: Telemetry Event : DS_INTERNAL.COMMAND_EXECUTED Measures: undefined Props: {"command":"jupyter.clearSavedJupyterUris","installSource":"marketPlace","VSCode.ABExp.Features":"invitationLink;installRecovery;livesharecontinuousaacf;reusableLinks;RemoveKernelToolbarInInteractiveWindowcf;pythonJediLSP;portForwardingServiceEnabled-development;portForwardingServiceEnabled-staging;portForwardingServiceEnabled-production;pythonDiscoveryModule;pythonFindInterpreter;presentWelcomePageByDefault","abexp.assignmentcontext":"vsliv695:30137379;vsins829:30139715;vsliv368cf:30146710;vsreu685:30147344;python383cf:30185419;pythonvspyt602:30280718;vspor879:30202332;vspor708:30202333;vspor363:30204092;pythonvsnew554:30265444;pythonvspyt943:30277000;vspre833:30267464;","isamlcompute":"false","isInsiderExtension":"true","ds_notebookeditor":"native","localOrRemoteConnection":"local","isPythonExtensionInstalled":"true","rawKernelSupported":"true"}
