### ISSUE TITLE
Interrupting more than once prevents VS code from asking for a restart

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4930]
Run some code like so:
```python
import time
time.sleep(100)
```
Interrupt the sleep more than once. 
On windows this will hang. After 15 seconds or so it SHOULD ask to restart the kernel. It doesn't if you click interrupt more than once.

**Comment by DonJayamanne** [comment]
Unable to replicate this issue. Moving to validate.
It works just fine for me.

**Comment by joyceerhl** [comment]
Validated, I get the prompt on windows after interrupting twice 
![image](https://user-images.githubusercontent.com/30305945/112359412-77e9fc80-8c8e-11eb-8232-8992e5225a69.png)
