### ISSUE TITLE
Not update package version on previous files

### ISSUE THREAD

**Issue by zhangx306** [microsoft/vscode-jupyter#4936]
<img width="1048" alt="Capture" src="https://user-images.githubusercontent.com/31398786/108965606-f2910f00-7631-11eb-9488-722295cd33ec.PNG">
Issue Type: <b>Bug</b>

-created a script 
-updated one package that the script was using succesfully through conda
-re-run the script, still the same version
-open a new .ipynb file and copy paste the code, package updated in the new script but not the previous one

Extension version: 2021.2.576440691
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.66GB (25.20GB free)|
|Process Argv|--crash-reporter-id 3651da78-aff5-4851-ae7d-6125f1ed13e5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue but it looks to me like this is expected. 

You're using two different kernels. If you look in your upper right corner of your notebook the V2 notebook is using a different kernel
![image](https://user-images.githubusercontent.com/19672699/109038959-22b3ce80-7681-11eb-8f8d-59a7de441046.png)

At least it seems that way and that would explain the discrepancy.
