### ISSUE TITLE
No docstrings in Jupyter Notebooks

### ISSUE THREAD

**Issue by hart-mk** [microsoft/vscode-jupyter#4942]
This issue was previously raised here, however it was closed without a resolution:

https://github.com/microsoft/vscode-jupyter/issues/2652

I am having exactly the same issue as was articulated in this previous bug report. I'm wondering if any progress has been made on this front.

Version:
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

VS Code version: 1.53.0 (user setup)
Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
Python Extension version (available under the Extensions sidebar): v2021.1.502429796
OS (Windows | Mac | Linux distro) and version: Windows 10 Home 20H2
Python and/or Anaconda version: Python 3, Anaconda 3.9.2
Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
Jupyter server running: Local

**Comment by rchiodo** [comment]
Thanks for the bug. It looks like this was only fixed in the insiders version of VS code. For the stable version (which you have) this bug still exists.

**Comment by rchiodo** [comment]
I repro'd this in stable using numpy:

![image](https://user-images.githubusercontent.com/19672699/109063853-85679300-769e-11eb-907c-dd68096f700e.png)

whereas in insiders it shows this:

![image](https://user-images.githubusercontent.com/19672699/109063971-aaf49c80-769e-11eb-8d49-87dfc3bdbb3e.png)

**Comment by hart-mk** [comment]
ok, thanks, I'll install the insiders version

**Comment by hart-mk** [comment]
@rchiodo I just installed the insiders version, doesn't seem to have fixed it. Any suggestions?

**Comment by rchiodo** [comment]
Did you install VS code insiders? 

You also need:
- Latest jupyter extension in insiders
- Latest Python insiders channel extension
- Latest Pylance with pylance as your language server

**Comment by hart-mk** [comment]
Yes, i installed VS code insiders as well as all the other suggestions. I am not even getting autocompletions unfortunately. I'm also seeing two errors in the bottom right corner:

```

Couldn't start client Python Tools

Cannot read property '0' of undefined

```

Could this be related? This is new, and is only happening with VS code insiders edition - not with the stable edition.

**Comment by rchiodo** [comment]
That means you don't have the 'insiders' version of the python extension. You need to set this:

![image](https://user-images.githubusercontent.com/19672699/109216559-87e2ef00-7769-11eb-9fe7-de610f2e8ac4.png)

**Comment by hart-mk** [comment]
Hmmm... I did actually set that originally and I'm still getting the errors... Any other info I can give you? Much appreciated.

**Comment by rchiodo** [comment]
You might need to reload VS code. That error comes specifically from the older python extension failing. 

My version is this:

![image](https://user-images.githubusercontent.com/19672699/109220633-093c8080-776e-11eb-854f-5ead87c89e41.png)

If yours is older, that would explain the problem.

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987.
