### ISSUE TITLE
[Suggestion] Add for Jupyter Notebook's Python Markdown

### ISSUE THREAD

**Issue by gusbemacbe** [microsoft/vscode-jupyter#4946]
Hello,

I refer to the [article here](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/python-markdown/readme.html) about Python Markdown. 

With this extension enabled on Jupyter Notebook, it allows to render the variable on a Markdown cell from a Python cell. Only Jupyter Notebook supports it, but VSCode Insiders does not support even if I always trust the notebook. You can compare two GIFs:

![1](https://user-images.githubusercontent.com/2257024/109070519-5f0f1b00-76d1-11eb-99b4-169e5a9745bf.gif)
![2](https://user-images.githubusercontent.com/2257024/109070705-97aef480-76d1-11eb-91da-274068090f41.gif)

**Comment by gusbemacbe** [comment]
@rchiodo, done.

**Comment by rchiodo** [comment]
Thanks for the suggestion. We'll leave this open to see how many people up vote it.

**Comment by bruno-salmito** [comment]
Greate.

**Comment by sfabriciop** [comment]
Cool

**Comment by DonJayamanne** [comment]
Unfortunately this hasn't been priotized yet.
We work on issues based on upvotes, have longest upvote this

**Comment by emso-exe** [comment]
👍

**Comment by SYNiMAK** [comment]
👍

**Comment by DonJayamanne** [comment]
Note for internal use:
* This is current made possible in Jupyter Notebooks via a custom extension, 
* This isn't a feature thats natively supported.

Possibly a candidate for powertoys extension.

**Comment by SYNiMAK** [comment]
Super keen to see this in VS code, which ever way.

**Comment by gusbemacbe** [comment]
> Possibly a candidate for powertoys extension.

@DonJayamanne, it is exclusive of Windows 10 and 11. :-/

**Comment by DonJayamanne** [comment]
im referring to the following extension, currently under development https://github.com/microsoft/vscode-jupyter-powertoys

**Comment by piggjf** [comment]
Upvoting via comment.  If there's an actual button to click, please share its location.  

Coming from R where I could `r var.name` stochastically generated variables to Jupyter has been a bit of an adjustment.  My writing style is suffering and reminds me of the work that I produced back in third grade.

**Comment by ManuelWIAS** [comment]
Is this working now ?

**Comment by drorata** [comment]
Seems like it doesn't. I guess the need is still there.

**Comment by BengtDahlgrenGeo** [comment]
It would be a great feature for industries constantly creating reports that are very similar. We switched to Jupyter Notebook because of the lack of this feature.

**Comment by t-fourcade-isp** [comment]
I fully agree with the previous comments. In my company it is this missing feature that hold us back from switching to vscode notebook (we keep working with jupyterlab even if we all agree that vscode is overall better).

**Comment by gaardhus** [comment]
It seems that Quarto has this (somewhat) figured out in their next release: https://github.com/quarto-dev/quarto-cli/pull/6190

**Comment by DonJayamanne** [comment]
Quarto isn't displaying markdow the same way Jupyter does, they are pre-evaluating the cells and then rednering them, in Jupyter its completely diferent, i.e. if you update the variable then the markdown has to be updated, where as in quarto the mardown cell is generated after the variable has been initialized and its actual code thats executed.

**Comment by DonJayamanne** [comment]
Does anyone here use Jupyter Lab, 
if so what is the extension in Jupter Lab that makes this possible?
Thanks

**Comment by gaardhus** [comment]
I havn't been able to find a solution that works in Jupyter Lab either, only the following for Jupyter Notebooks https://stackoverflow.com/a/52874352/9811508

**Comment by t-fourcade-isp** [comment]
There is two solutions, one for jupyter notebook and one for jupyterlab:
- for Jupyter Notebooks, the solution is the one stated by @gaardhus [(https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/python-markdown),](url)
- for JupyterLab, the solution is the imarkdown extension ([https://pypi.org/project/jupyterlab-imarkdown/](url))

I tested both and they work well in their own environments.

**Comment by decimad** [comment]
I cannot understand why this common-sense must-have feature needs some determined thumbs-up count since 3 years to be considered for being taken out of the backlog while the extension supports so many nonsense features that nobody will hardly require anytime... I'm forced to copy and paste latex stuff from python output into markdown cells since the beginning and will now switch to jupyterlab because of this.

**Comment by rebornix** [comment]
With the stable API of Jupyter extension, we can build a markdown renderer plugin for VS Code to support this feature. It doesn't need to be part of this extension IMHO considering it doesn't need any private/internal API. I can share an extension example for this, or maybe just publish one directly to the marketplace.

**Comment by DonJayamanne** [comment]
@rebornix I thought we never wanted to do this. I did prototype this at one point, but it was decided we would want to do something in Jupyter itself
Back then i was waiting for the stable VS Code API see comments here https://github.com/microsoft/vscode-jupyter/issues/4946#issuecomment-1084044004

**Comment by DonJayamanne** [comment]
We try to keep VS Code lean and we think the functionality you're asking for is great for a VS Code extension. Maybe you can already find one that suits you in the [VS Code Marketplace](https://aka.ms/vscodemarketplace). Just in case, in a few simple steps you can get started [writing your own extension](https://aka.ms/vscodewritingextensions). See also our [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Happy Coding!
