### ISSUE TITLE
Create dedicated Output Channel for Jupyter Server & each Kernel

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4954]
NOte: Also requestd by users (see here https://github.com/microsoft/vscode-jupyter/issues/3915)

We only ever start a single Jupyter server (non-raw).
Would be good to send the output from Jupyter server to this (along with output panels).
I would still want to see the Jupyter output in regular output panel, as this wa users send just one output panel.

But for debugging:
* Having the Juptyer server go into a dedicated output panel helps (else i have to go through the logs & split & join, etc...)
* Similarly send output from each kernel into its own dedicated output panel

We could easily do this via hidden configuration flag (or just when in debugging mode or the like).
**Would help development/debugging a lot**

**Comment by rchiodo** [comment]
I'm doing these in order from oldest to newest and thought I'd do this one.

Tenative plan
- Create output channel for the jupyter server. 
- Create output channel for each kernel (when raw). This option doesn't really work when not using raw
- Put both behind a setting
