### ISSUE TITLE
Add Jupyter Insider Build Telemetry 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#4959]
Add telemetry that tells us whether a specific build of the Juptyer extension is an insiders build or stable build. 
# Proposed solution
* Check the value of the vscode.engines version & if it has `-insider`

**Comment by gramster** [comment]
Use use -dev on version like core Python extension

**Comment by DonJayamanne** [comment]
@gramster unfortunately the marketplace rejects such versions. We tried to upload such a VSIX and it failed.
![Screen Shot 2021-02-22 at 16 52 06](https://user-images.githubusercontent.com/1948812/109330073-24f86300-7810-11eb-8b9b-793d3a814b86.png)

**Comment by DonJayamanne** [comment]
Depends on completing the Github Actions to publish insider build

**Comment by IanMatthewHuff** [comment]
Validated. Validated this by seeing and checking the shared property value in the telemetry presentation that I did for Jim / Claudia.
