### ISSUE TITLE
Unwanted message asking to install Python when I am not using python

### ISSUE THREAD

**Issue by KwokQPhan** [microsoft/vscode-jupyter#4965]
## Environment data

-   VS Code version: 1.54-Insider
-   Jupyter Extension version (available under the Extensions sidebar): Marketplace
-   Python Extension version (available under the Extensions sidebar): No
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: No
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): No
-   Jupyter server running: No

## Expected behaviour

No message to install Python.
Is this Python extension or Jupyter?

## Actual behaviour

When I create new Notebook I am asked to install Python, why?
Install Julia Extension
I am asked to install Python?
All in my company gets same message, in SSH worse, always asked to install python.

Why not ask when I try to run a Python notebook instead, I do not have Python install, why ask

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, 
I believe I know what is going on here. We should be able to address this fairly easily.

**Comment by joyceerhl** [comment]
Validated. Without the Python extension and an updated build of the Jupyter extension, if I open a blank notebook I do not get a prompt to install the Python extension.
