### ISSUE TITLE
Error loading pyodps/progress:1.5.0. Internet connection required for loading 3rd party widgets. Error loading pyodps/progress:. Internet connection required for loading 3rd party widgets.

### ISSUE THREAD

**Issue by JinhuaSu** [microsoft/vscode-jupyter#4971]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by joyceerhl** [comment]
Hi @JinhuaSu, sorry for the delayed response. Could you please fill out the bug template above? It helps us understand how to reproduce the issue and what code to run. Thanks!

**Comment by greazer** [comment]
@JinhuaSu, unfortunately, this behavior is expected as pyodps is not available on the download site we use to get widget source. We will ask pyodps to publish their source.

**Comment by DonJayamanne** [comment]
Filed issue upstream
