### ISSUE TITLE
Go to definition does not work for Pandas and other libraries

### ISSUE THREAD

**Issue by nfx** [microsoft/vscode-jupyter#4972]
Issue Type: <b>Bug</b>

`Go To Definition` does not work for Pandas and any other source type. For example, in this very simple code snippet, i try to CMD+click on a DataFrame symbol and as a seasoned engineer, i expect to go directly to sources of DataFrame class definition, because i have no time to google for documentation nor i generally trust it, because it's either not that extensive or out of date. And sources have more things to show.

```python
import pandas as pd
pd.DataFrame([{'foo': 1, 'bar': 2}])
```

navigation does not work also for any module in the `sys.path`:

```py
import os,sys
# (i have all my exploratory notebooks in `notebooks` folder and my other code in packages up the level)
sys.path.append(os.path.abspath('..'))
```

this does not work for symbols defined in the same notebook as well:

e.g. `def foo(): print(1)` in one cell, and `foo()` in the other cell doesn't get me jumping the way i'd expect from an IDE.

Extension version: 2021.3.600686576
VS Code version: Code - Insiders 1.54.0-insider (Universal) (e590188f17162393f50feec19263398e6fe02d13, 2021-02-26T20:39:12.763Z)
OS version: Darwin x64 19.6.0

<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvspyt639:30264824
pythontb:30258533

```

</details>

**Comment by nfx** [comment]
Must be part of https://github.com/microsoft/vscode/issues/91987

**Comment by joyceerhl** [comment]
Thanks, I do repro this behavior. Same behavior in the December release, so we didn't regress this.

Some observations:
- We do implement `provideDefinitions` in the `notebookConcatMiddleware` in the Python extension
- However ctrl+click does nothing in a notebook
- Invoking the Go to Definition command from the command palette with a symbol selected results in the following error message:
![image](https://user-images.githubusercontent.com/30305945/109399791-ba235680-78f9-11eb-946b-b446ce17959a.png)

- Additionally, when invoking the Go to Definition command, the Jupyter extension's log shows this message:
         `Info 2021-02-27 12:43:03: provideCodeActions not currently supported for notebooks`

**Comment by nfx** [comment]
@joyceerhl my other bug about this was closed with statement it’s working in daily build, but it’s not working, as we see here 😜 I have “all” AB experiments enabled so feel free to add experimental code for more feedback :)

also, it would be great if you can tell me how to get relevant logs for my countless bug reports to make your work easier 😊

**Comment by joyceerhl** [comment]
Appreciate you taking the time to help us improve our product 😊 To get full logs, add the following setting to your user settings.json:
>"jupyter.logging.level": "debug"

Then reload VSCode for the new setting to take effect, and you'll be able to find debug logs in the Jupyter output tab:
![image](https://user-images.githubusercontent.com/30305945/109401262-8b5dae00-7902-11eb-8b4e-638a31e7de16.png)

**Comment by nfx** [comment]
@joyceerhl where settings.json is located on macOS? Is it project level or user level?

**Comment by joyceerhl** [comment]
@nfx that would be user level. You can find it by running Cmd+Shift+P to bring up the command palette, then typing in 'Open Settings (JSON)' and selecting the top option.

**Comment by IanMatthewHuff** [comment]
I poked at this a bit on current VS Code - Insiders. I do see an initial failure the first time that I do Go To Definition or use F12. But then after that initial failure it seem to work correctly for me, but only for a basic intra file example (def foo in one call, foo() in another). Not getting any success on the example of pandas dataframe while it works just fine in .py. Looking more now.

**Comment by nfx** [comment]
@IanMatthewHuff i think pandas example doesn't work because symbols, it's not defined in the workspace, but it is a dependency. And indexing/debugging non-workspace symbols is disabled by default, as far as i understood. i think we really need a popup window asking to enable this. Anyway, my expectation from IDE is to look for symbol in every submodule defined in `sys.path`.

**Comment by IanMatthewHuff** [comment]
@nfx. While digging in on this I found a straight up bug here. Basically outgoing links (goto def and whatnot) from inside a notebook file to anything outside a notebook file were not working. I have a fix in progress and should hit the insiders build of the Python extension soonish. Just follow this issue and you should see when it gets closed.

**Comment by IanMatthewHuff** [comment]
Note for team validation. This was resolved in the Python extension.

**Comment by joyceerhl** [comment]
Validated against latest main for Python + Jupyter extension.

**Comment by nfx** [comment]
yes! it works! thanks!

**Comment by IanMatthewHuff** [comment]
@nfx Awesome. Thanks for the confirmation.
