### ISSUE TITLE
Interactive windows should change current working directory to be that of file containing the running cell

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-jupyter#4977]
Given the following two Python files in different directories `dir1` and `dir2`, if I first run `a.py` in an interactive window and then `b.py` in the same window, `b.py` throws an error `dir1/bar.csv` can't be found. This is because having run `a.py` first, the working directory was permanently set to `dir1`.

```py
# dir1/a.py

# %%
import pandas as pd

pd.read_csv('foo.csv')  # found at dir1/foo.csv
```

```py
# dir2/b.py

# %%
import pandas as pd

pd.read_csv('bar.csv')  # found at dir2/bar.csv
```

I think it makes sense to update the current working directory to be that of the file containing the cell that's currently running. In case this is considered a breaking change, perhaps this behavior could be activated by a setting?

**Comment by joyceerhl** [comment]
Thanks for the suggestion @janosh :) Will discuss with our team during our weekly triage meeting.

**Comment by greazer** [comment]
@janosh, thanks for the feedback. We don't have immediate plans on fixing this, but if you'd like to take a stab at submitting a PR for it, we'd be happy consider it.

Also we believe you can workaround this problem by setting "Interactive Window Mode" setting to perFile.

**Comment by andycraig** [comment]
If this feature is added, I'd like to request that it be added as an optional setting. (I often work with code where the current working directory is not the same as the file's location.)

**Comment by janosh** [comment]
@greazer Thanks for the advice! I'll give `"jupyter.interactiveWindowMode": "perFile"` a try. I do occasionally want to run code from different files in the same interactive window (just with different working directories) but it sounds like `perFile` is my preferred behavior most of the time. 🙇
