### ISSUE TITLE
cannot choose kernels

### ISSUE THREAD

**Issue by FuZhiyu** [microsoft/vscode-jupyter#4991]
Issue Type: <b>Bug</b>

No matter which kernel I'm choosing, when I tried to run a cell it always tries to activate Python 3.8.2, and failed to activate the conda environment for some reason (this part may be due to the special set up on my server, but always activating Python even I'm specifying a Julia kernel seems like a bug).

See below for the log output:

```

Error 2021-03-01 23:45:45: failed to create INotebook in kernel [Error: Activating Python 3.8.2 64-bit ('base': conda) to run Jupyter failed with Error: Command failed: . activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/zhiyufu/.vscode-server-insiders/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py /home/zhiyufu/.vscode-server-insiders/extensions/ms-python.python-2021.2.582707922/pythonFiles/printEnvVariables.py

CondaEnvironmentNotFoundError: Could not find environment: base .
You can list all discoverable environments with `conda info --envs`.

.
	at S.checkUsable (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:379738)
	at async S.startServer (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:378279)
	at async S.createServer (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:377668)
	at async c.getNotebook (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:502773)
	at async m.getOrCreateNotebook (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:374795)
	at async /home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:695974]
Error 2021-03-01 23:45:45: DataScience Error [Error: Activating Python 3.8.2 64-bit ('base': conda) to run Jupyter failed with Error: Command failed: . activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/zhiyufu/.vscode-server-insiders/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py /home/zhiyufu/.vscode-server-insiders/extensions/ms-python.python-2021.2.582707922/pythonFiles/printEnvVariables.py

CondaEnvironmentNotFoundError: Could not find environment: base .
You can list all discoverable environments with `conda info --envs`.

.
	at S.checkUsable (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:379738)
	at async S.startServer (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:378279)
	at async S.createServer (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:377668)
	at async c.getNotebook (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:502773)
	at async m.getOrCreateNotebook (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:374795)
	at async /home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:695974]
Error 2021-03-01 23:45:45: failed to start INotebook in kernel [Error: Activating Python 3.8.2 64-bit ('base': conda) to run Jupyter failed with Error: Command failed: . activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/zhiyufu/.vscode-server-insiders/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py /home/zhiyufu/.vscode-server-insiders/extensions/ms-python.python-2021.2.582707922/pythonFiles/printEnvVariables.py

CondaEnvironmentNotFoundError: Could not find environment: base .
You can list all discoverable environments with `conda info --envs`.

.
	at S.checkUsable (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:379738)
	at async S.startServer (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:378279)
	at async S.createServer (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:377668)
	at async c.getNotebook (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:502773)
	at async m.getOrCreateNotebook (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:374795)
	at async /home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:695974]
Error 2021-03-01 23:45:45: Failed to execute cells in CellExecutionQueue [Error: Activating Python 3.8.2 64-bit ('base': conda) to run Jupyter failed with Error: Command failed: . activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/zhiyufu/.vscode-server-insiders/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py /home/zhiyufu/.vscode-server-insiders/extensions/ms-python.python-2021.2.582707922/pythonFiles/printEnvVariables.py

CondaEnvironmentNotFoundError: Could not find environment: base .
You can list all discoverable environments with `conda info --envs`.

.
	at S.checkUsable (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:379738)
	at async S.startServer (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:378279)
	at async S.createServer (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:377668)
	at async c.getNotebook (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:502773)
	at async m.getOrCreateNotebook (/home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:374795)
	at async /home/zhiyufu/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.3.600686576/out/client/extension.js:49:695974]
```

Extension version: 2021.3.600686576
VS Code version: Code - Insiders 1.54.0-insider (e7989863202eac0ec4e66ca82733d968bca7527a, 2021-03-01T21:13:40.027Z)
OS version: Darwin x64 20.3.0
Remote OS version: Linux x64 3.10.0-1160.6.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 8759ecb8-1bc8-4b31-8247-a1013e757f64|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: athensx.uchicago.edu|
|OS|Linux x64 3.10.0-1160.6.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E7-8891 v2 @ 3.20GHz (80 x 2575)|
|Memory (System)|2015.58GB (348.97GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30253241
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533

```

</details>

**Comment by IanMatthewHuff** [comment]
@FuZhiyu . Thanks for reporting this. Would you please do one thing to help us look into this? It would actually be really helpful from our end to see the full logging output, not just the conda activation errors above. So if you make sure that you set Jupyter: Logging->Level to 'debug' and then re run the scenario. If you do that please copy out the full content of the Jupyter tab in the output window (you can save it to a file and just drag that file to a comment here so you don't have to copy and paste it all in). That will help give the fuller picture of what is going on here.

And also to confirm, this is happening with a connection to a remote linux server, correct? Do you see issue with kernel choosing locally as well? Or just when connecting to the server? You mentioned a special setup on your server, so also any info there could be helpful. Thanks much.

**Comment by FuZhiyu** [comment]
I would love to provide more information, but after I added the line `"jupyter.logging.level": "debug"` to my setting, reload, and redo the steps, the output is the same. Did I miss something obvious? I'm using native notebook.

And yes this happens on a Linux server. There is no issue on my local computer.

About the setup of the server, what I meant is the conda environment is pretty messed up here. The `base` env is not in the path, so the command `source activate base` will fail anyways. I don't want to waste your time debugging my conda setup, but if I understand correctly, if I'm specifying a Julia kernel, conda should not be activated anyways, right?

![image](https://user-images.githubusercontent.com/11523699/109754484-b9b0e700-7ba9-11eb-9db9-d4b00f21bd66.png)

**Comment by IanMatthewHuff** [comment]
Hmmm, I would be expecting there to be quite a bit more output in the "Jupyter" tab of the output window. Not sure what is going on with that. Before the "failed to create notebook in IKernel" there isn't anything more?

> I don't want to waste your time debugging my conda setup, but if I understand correctly, if I'm specifying a Julia kernel, conda should not be activated anyways, right?

You are correct that this should be the case. But there are a lot of code paths though our code, it's possible that something is trying to do a conda activation incorrectly. I'm not 100% sure that this is the same issue but I've seen at least two other recent issues that look like they might be similar to what you are seeing.

#4952 and #4855 . 

On your linux server is conda installed? I'm trying to tell here if it's incorrectly picking up a conda install on your host machine and trying to activate it on the server, or if it's just failing to activate a conda that is present on the server. Also to clarify, in your image posted above it says "Jupyter Server: local" does that mean that you are connected to that server via the VS Code remote extension? There is a difference between that and the support that we provide for connecting directly to an already running live jupyter server. Just making sure that I have the scenario right.

**Comment by masaki9** [comment]
I am also seeing this issue in 1.54.0 (Universal) and 1.54.0-insider (Universal) on my M1 Mac running macOS 11.2.2. I cannot switch to another kernel in the Jupyter interactive window. FYI, I have Python Extension v2021.2.582707922 and Jupyter Extension v2021.3.619093157 installed.

In 1.54.0 (Universal), whenever I attempt to switch to another kernel, I end up starting the following and fail to start the selected kernel.
Started 'Python 3' kernel
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 

In 1.54.0-insider (Universal), whenever I attempt to switch to another kernel, I end up starting the following and fail to start the selected kernel.
Started 'Python 3' kernel
Python 3.9.1 | packaged by conda-forge | (default, Jan 10 2021, 02:51:11) 

Selecting another kernel appears to always start the 'default' one.

By the way, I wonder if this issue is related to https://github.com/microsoft/vscode/issues/116951 .

**Comment by FuZhiyu** [comment]
@masaki9 sorry I was busy with other things last week and forgot to update, but I can confirm this bug is fixed. Thanks so much for the amazing productivity!
