### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by NicolaVanoli** [microsoft/vscode-jupyter#4993]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.2.576440691`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.53.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by IanMatthewHuff** [comment]
@NicolaVanoli If you hit this issue again, can you please copy out the data from your clipboard? That would have the callstack of the code that would help us to investigate this.
