### ISSUE TITLE
Exporting a notebook from the interactive window is not trusted.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4994]
Run interactive window
Save notebook
Open in editor

You have to trust before you can continue.

**Comment by SiddhanthUnnithan** [comment]
Is this still an issue? I wasn't able to repro this. You can't create an interactive window in an untrusted workspace and for all trusted workspaces, there is no concept of Notebook-level trust anymore.

**Comment by rchiodo** [comment]
No not an issue anymore
