### ISSUE TITLE
getActiveInterpreter can take a long time. 

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5004]
We should cache this value.
Or ask the python team why this isn't cached.

**Comment by rchiodo** [comment]
If we cache, we should update when they get their new value.

**Comment by IanMatthewHuff** [comment]
Not sure if we have a clear customer validation here, but I see the code changes for this. Validating.

**Comment by rchiodo** [comment]
Sorry should have added validation steps.

The delay was apparent when opening new notebooks. The kernel picker would take 5 seconds to even appear. All of this time was spent searching for the active interpreter on my own machine.

**Comment by IanMatthewHuff** [comment]
Yeah, I do see it being a bit snappier than before. I don't have exact numbers, but seems to be an improvement.
