### ISSUE TITLE
VS Code based tests should test with real jupyter as well as raw

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5010]
Seems like we can just run all the same tests over again with jupyter instead of raw (or some subset of them)

**Comment by DonJayamanne** [comment]
I'm picking this as I'm alraedy doing this, the issue i'm currently working on is to do with swithcing kernels in native notebooks when using Jupyter (that doesn't work).

**Comment by DonJayamanne** [comment]
**Native Notebook Test Matrix**

| Test        | No_Py_Ext        | Stable        | Insiders      | Raw   | Jupyter  | Remote  |Conda  |
| ------------- | ------------- | ------------- |------------- |------------- |-------------| -----|----------|
| Pick & Run Julia |       |       | Yes  | Yes || ||
| Pick & Run C# *   |       |       | Yes  | Yes || ||
| Pick & Run Java *   |       |       | Yes  | Yes || |Yes|
| Kernel Execution        |       |       |Yes  | Yes | Yes|Yes ||
| Kernel Interrupt        |       |       |Yes  | Yes | Yes| ||
| Kernel Restart        |       |       |       Yes  | Yes | Yes| Yes ||
| Kernel Selection (swith, register ipykernel, register kernel)        |       |       |       Yes  | Yes | WIP| ||
| Kernel Remember        |       |       |       Yes  | Yes | Yes| Yes||
| Prompt & Install IPykernel        |       |       |       Yes  | Yes | | ||
| Pick Right Kernel when open nb        |       |       |       Yes  | Yes | Yes| Yes||

**Comment by DonJayamanne** [comment]
Test to be added:
* Jupyter with conda
	* Switching kernels
	* Switching from non-conda to conda kernel & vice versa

**Comment by DonJayamanne** [comment]
Ideally we'd like run our test in all of the following permutations:
* Local + Remote
* Jupyter + Raw
* Conda + Non Conda
* Stable + Insiders 
	* Stable in release branch 
	* Insiders in Main (at least until Notebook API is stable)
	* When Notebook API is table, we might want to stable for Main branch as well.

**Comment by rchiodo** [comment]
I think to do so we need to refactor how those things are picked. I'm having trouble trying to run things locally (seems like we use env variables to control a number of different variables). 

Perhaps we can have a brainstorm about test design?

**Comment by DonJayamanne** [comment]
Agreed, that's why i started this, the YML is messy.
Ideally i'd like to have the following:
* OS matrix (windows, linux, mac) we have this today
* Python Matrix (conda, non conda)
* Server Matrix (local-raw, local-jupyter, remote)


This way we can run our tests in a different environment without having to add tonnes of env variables & duplicate stuff...
I.e. if we want, we can add another matrix, with and without python extension.

But this means we end up with a lot of new jobs for each matrix, and we might want to ensure we don't have too many either..

**Comment by DonJayamanne** [comment]
Closing as fixed.
