### ISSUE TITLE
Jupyter (Insider) Output Cell Scrollbar not working/showing

### ISSUE THREAD

**Issue by Tomiha** [microsoft/vscode-jupyter#5027]
## Environment data

-   VS Code version: 1.54.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): 2021.3.619093157
-   Python Extension version (available under the Extensions sidebar): 2021.2.582707922
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Pro (10.0.19041)
-   Python and/or Anaconda version: Python 3.7.6 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local 

## Expected behaviour
Having a vertical scrollbar in the Notebook Output Cells when contents exceed a certain value.
Related Jupyter settings are set:
 - Jupyter: Enable Scrolling For Cell Outputs (TRUE)
 - Jupyter: Max Output Size (100, Default was 200)

## Actual behaviour
Jupyter settings related to output cell scrolling seem to be ignored.
No scrollbar is added to a long output cell (must use the main scrollbar to scroll all the way down to the next input cell).

## Steps to reproduce:
INPUT:
for i in range(0.1000):
  print(i)

OUTPUT:
Values from 0 to 1000 printed to output, but without scrollbar in the output cell.
Results in an output that is over 4 pages long.
(Scrollbar visible in GIF is the main document scrollbar, what I want is an individual Output Cell scrollbar)

![vscode_jupyter_scollbug](https://user-images.githubusercontent.com/2349894/109940205-1b6c7080-7cd2-11eb-8ceb-49e3307f72cc.gif)

**Comment by DonJayamanne** [comment]
> Jupyter settings related to output cell scrolling seem to be ignored.

Thanks for filing this issue. Unfortunately the new Notebook in Insiders does't respect all of the settings. We'll try to get this functionality in.

**Comment by DonJayamanne** [comment]
Issue moved to [microsoft/vscode #118117](https://github.com/microsoft/vscode/issues/118117) via [**ZenHub**](https://www.zenhub.com/)

**Comment by DonJayamanne** [comment]
Issue has been transferred upstream, keeping this open for tracking purposes https://github.com/microsoft/vscode/issues/118117

**Comment by greazer** [comment]
This has been fixed
