### ISSUE TITLE
Document ipynb non ouvert

### ISSUE THREAD

**Issue by Sid281216** [microsoft/vscode-jupyter#5028]
Issue Type: <b>Bug</b>

Bonjoour,  j'ai un fichier ipynb qui s'ouvre trés bien sur jupyterlab mais sur vscode il ne s'ouvre pas. ça l'ouvre en mode "code source"

Added with google translate:

```Bonjoour, I have an ipynb file which opens very well on jupyterlab but on vscode it does not open. it opens it in "source code" mode```

Extension version: 2021.2.603412351
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: 
![Sans titre](https://user-images.githubusercontent.com/75738466/110003285-83dd4100-7d16-11eb-9dfd-b4c20e038945.png)
enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.94GB (1.55GB free)|
|Process Argv|--crash-reporter-id 3e28bd5e-0980-4f01-8657-d86f0b3a25cf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes516:30244333
pythonvspyt875:30259475
pythontbcf:30265426
vspre833:30267464

```

</details>

**Comment by DonJayamanne** [comment]
@Sid281216 I'm sorry for not getting back to you all this time, i totally missed this issue.
Please could you provide a screenshot of the issue or share the ipynb file that opens in jupyter lab and not in VS Code.
Thanks.
FI - You seem to be using an old version of VS Code, please could you update to the latest version of VS Code, and it might work.

**Comment by Sid281216** [comment]
Seems like the update resolve the issue !
Thanks for your time


-------- Message d'origine --------
De : Don Jayamanne ***@***.***>
Date : 12/03/2021 21:03 (GMT+01:00)
À : microsoft/vscode-jupyter ***@***.***>
Cc : Sid281216 ***@***.***>, Mention ***@***.***>
Objet : Re: [microsoft/vscode-jupyter] Document ipynb non ouvert (#5028)


@Sid281216<https://github.com/Sid281216> I'm sorry for not getting back to you all this time, i totally missed this issue.
Please could you provide a screenshot of the issue or share the ipynb file that opens in jupyter lab and not in VS Code.
Thanks.
FI - You seem to be using an old version of VS Code, please could you update to the latest version of VS Code, and it might work.

**Comment by DonJayamanne** [comment]
Thanks for getting back
