### ISSUE TITLE
Remote kernels we create for interactive window keep stacking up

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5030]
Seems like these should be shutdown when closing the interactive window.

Otherwise they stick around until we kill the server. This causes a problem when restarting a bunch of times.

**Comment by IanMatthewHuff** [comment]
Validated.

Started up against a server, not ZMQ. Then executed and checked the server log after closing the interactive window. Kernel and restart kernel both cleaned up.

![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/0eb5fefa-d32a-4316-b3be-eb0cba5605d0)
