### ISSUE TITLE
Insiders notebook output issue: matplotlib/seaborn plots extremely slow, debugger iterating over findfont

### ISSUE THREAD

**Issue by eudegbe** [microsoft/vscode-jupyter#5033]
Issue Type: <b>Bug</b>

Whenever I try to run notebook cells that output plots, runtimes are extemely slow. It takes ~3 minutes to output a simple scatter plot :(

In the Insiders version, the debugger is printing hundreds of "findfont" lines

Extension version: 2021.3.619093157
VS Code version: Code - Insiders 1.54.0-insider (42e27fe5cdc58539dad9867970326a297eb8cacf, 2021-03-02T19:09:10.315Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 3.10.0-1062.el7.x86_64

<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
vscoresta800cf:30265948
vspre833:30267464

```

</details>

**Comment by eudegbe** [comment]
Getting hundreds of lines like these

DEBUG: findfont: score(<Font 'Open Sans' (OpenSans-Light.ttf) normal normal light normal>) = 10.24
DEBUG: findfont: score(<Font 'Caladea' (Caladea-Italic.ttf) italic normal 400 normal>) = 11.05
DEBUG: findfont: score(<Font 'URW Gothic' (URWGothic-Book.otf) normal normal book normal>) = 10.05
DEBUG: findfont: score(<Font 'C059' (C059-Bold.otf) normal normal bold normal>) = 10.335
DEBUG: findfont: score(<Font 'Padauk' (Padauk.ttf) normal normal 400 normal>) = 10.05
DEBUG: findfont: score(<Font 'Nimbus Sans Narrow' (NimbusSansNarrow-BoldOblique.otf) oblique normal bold condensed>) = 11.535
DEBUG: findfont: score(<Font 'Liberation Sans' (LiberationSans-BoldItalic.ttf) italic normal bold normal>) = 5.335
DEBUG: findfont: score(<Font 'PakType Naskh Basic' (PakTypeNaskhBasic.ttf) normal normal 400 normal>) = 10.05
DEBUG: findfont: score(<Font 'DejaVu Sans' (DejaVuSansCondensed-Bold.ttf) normal normal bold condensed>) = 2.535
DEBUG: findfont: score(<Font 'URW Gothic' (URWGothic-DemiOblique.otf) oblique normal demi normal>) = 11.24
DEBUG: findfont: score(<Font 'Frank Ruehl CLM' (FrankRuehlCLM-Bold.ttf) normal normal bold normal>) = 10.335
DEBUG: findfont: score(<Font 'FreeMono' (FreeMonoBold.ttf) normal normal bold normal>) = 10.335
DEBUG: findfont: score(<Font 'Madan2' (madan.ttf) normal normal 400 normal>) = 10.05
DEBUG: findfont: score(<Font 'DejaVu Sans' (DejaVuSansCondensed-BoldOblique.ttf) oblique normal bold condensed>) = 3.535
DEBUG: findfont: score(<Font 'FreeMono' (FreeMonoOblique.ttf) oblique normal 400 normal>) = 11.05
DEBUG: findfont: score(<Font 'Liberation Mono' (LiberationMono-Italic.ttf) italic normal 400 normal>) = 11.05
DEBUG: findfont: score(<Font 'Open Sans' (OpenSans-SemiboldItalic.ttf) italic normal semibold normal>) = 11.24
DEBUG: findfont: score(<Font 'Liberation Serif' (LiberationSerif-Italic.ttf) italic normal 400 normal>) = 11.05
DEBUG: findfont: score(<Font 'Open Sans' (OpenSans-Semibold.ttf) normal normal semibold normal>) = 10.24
DEBUG: findfont: score(<Font 'Frank Ruehl CLM' (FrankRuehlCLM-BoldOblique.ttf) oblique normal bold normal>) = 11.335
DEBUG: findfont: score(<Font 'Open Sans' (OpenSans-Italic.ttf) italic normal 400 normal>) = 11.05
DEBUG: findfont: score(<Font 'NanumGothic' (NanumGothic.ttf) normal normal 400 normal>) = 10.05
DEBUG: findfont: score(<Font 'PT Sans Narrow' (PTN77F.ttf) normal normal bold condensed>) = 10.535
DEBUG: findfont: score(<Font 'URW Bookman' (URWBookman-Demi.otf) normal normal book normal>) = 10.05
DEBUG: findfont: score(<Font 'STIX' (STIX-Regular.otf) normal normal regular normal>) = 10.05
DEBUG: findfont: score(<Font 'C059' (C059-Italic.otf) italic normal 400 normal>) = 11.05
DEBUG: findfont: score(<Font 'STIX' (STIX-BoldItalic.otf) italic normal bold normal>) = 11.335
DEBUG: findfont: score(<Font 'Nimbus Roman' (NimbusRoman-Regular.otf) normal normal roman normal>) = 10.145
DEBUG: findfont: score(<Font 'Liberation Sans' (LiberationSans-Bold.ttf) normal normal bold normal>) = 4.335
DEBUG: findfont: score(<Font 'FreeMono' (FreeMonoBoldOblique.ttf) oblique normal bold normal>) = 11.335

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
* Please could you enable logging as follows:
	* Open settings & go into `Jupyter->Logging`
	* Change the value to `debug`
	* Reload VS Code,
* Please update to the latest VS Code Insiders (1.55.0-Insiders)
* Ensure you update to the latest Jupyter extesnion (2021.4.xxx)
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.
* Please could you also provide a Notebook that produces the plogs
Thanks

**Comment by DonJayamanne** [comment]
Finally can you confirm that the ipynb file is very large (ie originally its a few KB, and then once you run and save the notebook its a few MB or more).
