### ISSUE TITLE
My custom shortcut key is invalid because of the now python plugin

### ISSUE THREAD

**Issue by ryantian2000** [microsoft/vscode-jupyter#504]
## Environment data

-   VS Code version: 1.50.1 (system set up)
-   Extension version (available under the Extensions sidebar): v2020.9.114305
-   OS and version: Win7 x64 6.1.7601 & Win10 Pro 2004
-   Python version (& distribution if applicable, e.g. Anaconda): PYthon 3.8.3 64 bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: N/A

## Expected behaviour

I hope that in the global situation, _**Ctrl+;**_ key combination is available, but it is not available now, it is intercepted by default shortcut keys of python plugin

## Actual behaviour

In the global scope, **_Ctrl+;_** shortcut keys is invalid

## Steps to reproduce:

I have used VS CODE for many years, and I have also defined a unified key combination to edit C/C++, Java, Python, C#, etc., 
Such as using the combination key **_Ctrl+;_** replaces the END button, This is shown in the keybinding.json file：
`   
 {
        "key": "ctrl+;",
        "command": "cursorEnd",
        "when": "textInputFocus"
    },
    {
        "key": "end",
        "command": "-cursorEnd",
        "when": "textInputFocus"
    },
`

but recently, I updated the Python plugin and found ctrl + ; is invalid. The reason is that the default shortcut key of the new version of python plug-in will intercept **_Ctrl+;_** it makes this button invalid. 
I tried to delete the default shortcut key, but it still doesn't work. 
Even if I delete the default shortcut key of the python plug-in, it is still displayed in the keybindings.json file and will intercept **_Ctrl+;_**， like this：

`
    {
        "key": "ctrl+; c",
        "command": "-python.datascience.changeCellToCode",
        "when": "editorTextFocus && python.datascience.featureenabled && python.datascience.hascodecells && !notebookEditorFocused"
    },
    {
        "key": "ctrl+; m",
        "command": "-python.datascience.changeCellToMarkdown",
        "when": "editorTextFocus && python.datascience.featureenabled && python.datascience.hascodecells && !notebookEditorFocused"
    },
    {
        "key": "ctrl+; x",
        "command": "-python.datascience.deleteCells",
        "when": "editorTextFocus && python.datascience.featureenabled && python.datascience.hascodecells && !notebookEditorFocused"
    },
    {
        "key": "ctrl+; a",
        "command": "-python.datascience.insertCellAbove",
        "when": "editorTextFocus && python.datascience.featureenabled && python.datascience.hascodecells && !notebookEditorFocused"
    },
    {
        "key": "ctrl+; b",
        "command": "-python.datascience.insertCellBelow",
        "when": "editorTextFocus && python.datascience.featureenabled && python.datascience.hascodecells && !notebookEditorFocused"
    },
    {
        "key": "ctrl+; s",
        "command": "-python.datascience.insertCellBelowPosition",
        "when": "editorTextFocus && python.datascience.featureenabled && python.datascience.hascodecells && !notebookEditorFocused"
    },
    {
        "key": "ctrl+; d",
        "command": "-python.datascience.moveCellsDown",
        "when": "editorTextFocus && python.datascience.featureenabled && python.datascience.hascodecells && !notebookEditorFocused"
    },
    {
        "key": "ctrl+; u",
        "command": "-python.datascience.moveCellsUp",
        "when": "editorTextFocus && python.datascience.featureenabled && python.datascience.hascodecells && !notebookEditorFocused"
    },
`

 I think the python plug-in custom default The shortcut key of is not a good idea, 
it will make the shortcut key is also invalid when I editing java, c# code, this is a global scope, will have a great impact

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by jaymegordo** [comment]
@joyceerhl Are there docs somewhere describing the new 'when expression' options? For example I'm specifically looking to add a keybinding only when 'interactiveWindowHasFocus' or something like that, but don't see any conditions specifically related to the interactive window in the defaults.
