### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by WHITESHADOW076** [microsoft/vscode-jupyter#5044]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.2.576440691`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rchiodo** [comment]
Sorry but this doesn't give us anything to go on. Please reopen if you have more information.
