### ISSUE TITLE
Run Cell Above & Run Cell Below do not work

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5048]
They have been disabled, possibly due to VSC API changes.
Blocked upstream https://github.com/microsoft/vscode/issues/118569

**Comment by DonJayamanne** [comment]
Issue has been fixed in VS Code.

**Comment by DonJayamanne** [comment]
We just need to enable the tests probably tomorrow (after insiders has been updated)

**Comment by IanMatthewHuff** [comment]
Validated. They were in and out for a bit due to VS Code side changes. But they are in now and work with a basic tests.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/3b9d009d-c16a-4596-9fd0-ce98708b3d9d)
