### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Tipphead** [microsoft/vscode-jupyter#5050]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.3.619093157`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rchiodo** [comment]
Sorry but this doesn't give us anything to go on. Please reopen if you have more information.

**Comment by Tipphead** [comment]
Solved with anaconda and vs code reinstall.  I couldn’t open jupyter notebook interactive window.  I thought I had posted more detail my apologies.
