### ISSUE TITLE
Python data science module completely gone

### ISSUE THREAD

**Issue by Fred-Wu** [microsoft/vscode-jupyter#5052]
All options regarding data science are complete missing. Nothing behaves the same as before. 
Old options are now inactive in the settings. If trying to type "python.dataScience......", nothing comes up now. 

This makes
1. Shift + Enter in python script no long sends code to interactive window, only to terminal. 
2. Jupyter notebook is no more
3. all other features gone completely. 

## Environment data

-   VS Code version: 1.54.1
-   Jupyter Extension version (available under the Extensions sidebar): 2021.3.619093157
-   Python Extension version (available under the Extensions sidebar): 2021.2.625869727
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04
-   Python and/or Anaconda version: 3.8.8 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

**Comment by joyceerhl** [comment]
@Fred-Wu sorry for the confusion. The data science functionality was refactored out of the Python extension into a standalone Jupyter extension late last year. All old settings should have been automatically renamed for you from 'python.dataScience.xyz' to 'jupyter.xyz' as part of this migration. All of the old functionality is still available but under the Jupyter extension:

![image](https://user-images.githubusercontent.com/30305945/110196451-71880380-7df9-11eb-9525-a9fb6ec51540.png)

**Comment by Fred-Wu** [comment]
@joyceerhl I have Jupyter extension installed as well.  But the json entries in the settings were not renamed automatically. I will rename them manually and to see how it works.  

Also, with Jupyter installed, the existing Jupyter notebooks are not automatically opened in the notebook format. This was working like one week ago.

**Comment by joyceerhl** [comment]
@Fred-Wu sorry to hear that. What format are your Jupyter notebooks opened in? If you open the Jupyter output tab in the terminal panel, can you paste the output in a comment? It's this:

![image](https://user-images.githubusercontent.com/30305945/110197112-20c6d980-7dfe-11eb-87d7-8993100dfb8d.png)

**Comment by Fred-Wu** [comment]
@joyceerhl Don't worry about it. I have made a few changes in the settings, so it works again. Thank you.
