### ISSUE TITLE
Auto open ipynb file in jupyter does not work after update vscode

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/vscode-jupyter#5054]
## Environment data
version: 1.54.1 (user setup)
commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

## Expected behaviour

Auto open ipynb file in jupyter

## Actual behaviour
![image](https://user-images.githubusercontent.com/33288114/110197710-60d29e80-7e88-11eb-972a-961c6391abbd.png)
Auto open ipynb file does not work .
![image](https://user-images.githubusercontent.com/33288114/110197752-a727fd80-7e88-11eb-9833-4678a76bd021.png)

**Comment by CatNofishing** [comment]
Yea, I see the option to open with the preview notebook editor, but how  to auto open ipynb file in notebook.  I remember that the previous version did not have this option

**Comment by joyceerhl** [comment]
Sorry but the Use Notebook Editor setting no longer applies and should be deprecated. Could you please uncheck that setting and try again?

**Comment by CatNofishing** [comment]
I've tried. Even if I cancel it, it won't open automatically in the notebook

**Comment by PauliusSasnauskas** [comment]
> Yea, I see the option to open with the preview notebook editor, but how to auto open ipynb file in notebook. I remember that the previous version did not have this option

Did you try changing the default jupyter editor and restarting your VSCode? There may be some bugs with that (https://i.imgur.com/1UerY0o.png)

**Comment by CatNofishing** [comment]
@joyceerhl @PauliusSasnauskas Thank you for your reply. I don't know what caused this problem. Maybe it was a plug-in conflict. I reinstalled vscode and then it worked normally
