### ISSUE TITLE
Separate Jupyter from Python Extension

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-jupyter#5056]
Jupyter should be its own separate install.  Just because Python's installed should not mean that Jupyter is an automatic install.   If you're going to leave it like that why have the disable / uninstall option and heck that doesn't work unless you uninstall Python.

**Comment by claudiaregio** [comment]
Hi @Marines1775, 
The Jupyter extension powers the interactive window experience and data viewer for the Python extension, which are both very useful features to those using Python, even if they are not using notebooks. The code for the Jupyter extension used to reside within the Python extension. It was extracted to provide support for other languages, so the only change for Python users is they see a separation as an extra extension in the extensions list. Nothing extra was actually installed. 

See more details here: https://github.com/microsoft/vscode-jupyter/wiki/FAQ---(Frequently-Asked-Questions)

**Comment by Marines1775** [comment]
Claudia

Before you added Jupyter to the Python extension the interactive window worked great.  To me and others  <https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details> its causing crashes and allot of people are asking for the option to remove / NOT install it at all.   Just how does it power the interactive window experience?  

If the cod for the Jupyter extension used to reside within the Python extension,  but then it was extracted to provide support for other languages?  Then why can’t it be optional for installation ?   It seems appears I’m not the only asking this question if you read the comments on the rating and review <https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details>.  

I think it’s safe to say that others in the VSC Python community would appreciate separating Python & Jupyter and not forcing users to go along with what you think maybe the best choice.  

Thank you

**Comment by claudiaregio** [comment]
Hi @Marines1775, 

At this time we do not have plans to separate Jupyter from the Python extension. We may consider it in the future but it's not in our near-term plans. The dependency was created to ensure that our current Python users had very little change, everything just worked. 

If you are having issues with the interactive window it would be great if you could file another issue to help us understand what's going on so we can get it fixed for you :)

**Comment by Marines1775** [comment]
There'll be changes this year.

**Comment by phgmacedo** [comment]
There wasn't even a dupe on my [issue](https://github.com/microsoft/vscode-jupyter/issues/5387). 

It seems they're trying really hard not to get any feedback on this.

**Comment by Marines1775** [comment]
I'll say this,  based on others at MS that I've been in touch with there's going to be changes coming down the road.  
VSC is OK ,  IMHO it's far from being "GREAT" but they do listen and if it's doable they'll do it.   Some people from MS just don't communicate properly.   There software and they can do as they want.   Theres allot of other packages out there that MS is playing catch up too.   Have a great weekend and happy coding.

**Comment by phgmacedo** [comment]
@Marines1775 I made a [PR that alleviates this issue](https://github.com/microsoft/vscode-jupyter/pull/5400).

**Comment by greazer** [comment]
Jupyter is now a separate extension that is uninstallable after installing Python.
