### ISSUE TITLE
Notebook file size too large

### ISSUE THREAD

**Issue by oscardog** [microsoft/vscode-jupyter#5059]
## Environment data

-   VS Code version: Version: 1.54.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.3.619093157
-   Python Extension version (available under the Extensions sidebar): v2021.2.625869727
-   OS (Windows | Mac | Linux distro) and version: MacOS 11.2.1 (intel i9, 32GB ram)
-   Python and/or Anaconda version: 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

Saving ipynb in jupyter lab produces files 20x smaller than in VSCode - notebook has several charts including pairplots

## Actual behaviour

Huge notebook file size- upon reopening VSCode displays JSON and doesnt show in notebook view

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
We have address this issue in the latest Insider build.

* Please install the latest VS Code Insiders (1.55.0-insider)
* Please install the latest Jupyter extesnion (2021.4.xxx)
* Try it there & it should be fine.

In the old webview implementation of the notebooks we'd generate SVG versions of the plots & end up saving that into the notebook. We no longer do that.

FYI - If you are using plots (matplot lib), you might want to try using [ipympl](https://github.com/matplotlib/ipympl), as this produces a widget with rich interactive controls for your plots).
