### ISSUE TITLE
'%cd' always defaults to 'C:\Users\<user>' instead of the working directory

### ISSUE THREAD

**Issue by secure-mail-documentation-project** [microsoft/vscode-jupyter#5060]
Issue Type: <b>Bug</b>

The Jupyter extension fails to set the working directory when starting.

To reproduce:
- On Windows 10
- vscode project base in `C:\Users\My User\Documents\vscode_test_project`
- python file `test.py` in above directory that is empty except for the line `# %%` opened in editor
- Click on "Run Cell"
- Jupyter opens
- in jupyter notebook execute `%cd`

Expected result:
```
C:\Users\My User\Documents\vscode_test_project
```

Actual result:
```
C:\Users\My User
```

The result is the same no matter what I set in `python.dataScience.notebookFileRoot`. Above report assumes the default value of a clean install.

Extension version: 2021.2.603412351
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.18GB free)|
|Process Argv|C:\\Users\\My User\\Documents\\vscode_test_project --crash-reporter-id 52935532-1f43-4f4e-bbec-b6ee4da772c6|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DavidKutu** [comment]
Thanks for the issue @secure-mail-documentation-project. 

I can repro this on on my workspace, with notebooks and the interactive window. `%cd` always seems to default to `C:\Users\<user>` instead of the working directory.

**Comment by DonJayamanne** [comment]
Closing this issue as this hasn't been brought up by others.
