### ISSUE TITLE
Incorrect PYTHONPATH variable with .env file with relative paths

### ISSUE THREAD

**Issue by secure-mail-documentation-project** [microsoft/vscode-jupyter#5061]
Issue Type: <b>Bug</b>

The jupyter extension sets the PYTHONPATH variable incorrectly when a `.env` file contains relative path definitions.

To reproduce:
- On Windows 10
- vscode project base in `C:\Users\My User\Documents\vscode_test_project`
- `.env` file in above direcory with the content `PYTHONPATH=./some-library`
- python file `subdir\test.py` in above directory that is empty except for the line `# %%` opened in editor
- Click on "Run Cell"
- Jupyter opens
- in jupyter notebook execute `import sys; sys.path`

Expected result:
```
['c:\\Users\\My User\\.vscode\\extensions\\ms-toolsai.jupyter-2021.2.603412351\\pythonFiles\\.does-not-exist',
 'C:\\Users\\My User\\Documents\\vscode_test_project\\some-library',
 'c:\\Users\\My User\\.vscode\\extensions\\ms-toolsai.jupyter-2021.2.603412351\\pythonFiles',
 'c:\\Users\\My User\\.vscode\\extensions\\ms-toolsai.jupyter-2021.2.603412351\\pythonFiles\\lib\\python',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\python39.zip',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\DLLs',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env',
 '',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib\\site-packages',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib\\site-packages\\win32',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib\\site-packages\\win32\\lib',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib\\site-packages\\Pythonwin',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\My User\\.ipython']
```

Actual result:
```
['c:\\Users\\My User\\.vscode\\extensions\\ms-toolsai.jupyter-2021.2.603412351\\pythonFiles\\.does-not-exist',
 'C:\\Program Files\\Microsoft VS Code\\some-library',
 'c:\\Users\\My User\\.vscode\\extensions\\ms-toolsai.jupyter-2021.2.603412351\\pythonFiles',
 'c:\\Users\\My User\\.vscode\\extensions\\ms-toolsai.jupyter-2021.2.603412351\\pythonFiles\\lib\\python',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\python39.zip',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\DLLs',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env',
 '',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib\\site-packages',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib\\site-packages\\win32',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib\\site-packages\\win32\\lib',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib\\site-packages\\Pythonwin',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\My User\\.ipython']
```

Note the invalid value of the second line containing the path for `some-library`. This should always be relative to the location of the location of the `.env` file.

Also of concern to me seems to be the first line that seems to contain part of an error message with `.does-not-exist`.

Extension version: 2021.2.603412351
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.18GB free)|
|Process Argv|C:\\Users\\My User\\Documents\\vscode_test_project --crash-reporter-id 52935532-1f43-4f4e-bbec-b6ee4da772c6|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by secure-mail-documentation-project** [comment]
On observation that might help with debugging this issue.

Playing with the `.env` file I discovered that the problem can be partially fixed by setting a `worspaceFolder` environment variable in the `.env` file manually. That fixes the first line containing the remnant of an error message, the second line is however still expanded relative to the python file used to start the notebook rather than relative to the `.env` file.


Content of `.env`:
```
workspaceFolder=C:\Users\My User\Documents\vscode_test_project
PYTHONPATH=./some-library
```


Output of `import sys; sys.path`:
```
['c:\\Users\\My User\\Documents\\vscode_test_project',
 'c:\\Users\\My User\\Documents\\vscode_test_project\\subdir',
 'c:\\Users\\My User\\Documents\\vscode_test_project\\subdir\\some-library',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\python39.zip',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\DLLs',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env',
 '',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib\\site-packages',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib\\site-packages\\win32',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib\\site-packages\\win32\\lib',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib\\site-packages\\Pythonwin',
 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\My User\\.ipython']
```

**Comment by IanMatthewHuff** [comment]
I'm looking at this right now (though I am on Mac and not windows) and I don't see the same issue that you are seeing:
![image](https://user-images.githubusercontent.com/812783/110402115-a8475f00-802f-11eb-8c51-d1afcd97e030.png)
Let me poke around a bit more here quick.

**Comment by IanMatthewHuff** [comment]
Do I have your file layout correct? I also tried this with the subdir and that is also working.

vscode_test_project (.env file in here)
vscode_test_project/subdir (python file with cell marker here)

**Comment by secure-mail-documentation-project** [comment]
@IanMatthewHuff Thanks for looking into this. Yes your directory structure is correct. See my attached screenshots.

You seem to be using linux for reproducing this. I think this might be a windows-specific problem. My second post indicates that there are problems with variable substitution on windows. I.e. why else would adding a `workspaceFolder` environment variable affect the paths.

Please let me know if there is anything I can do to help you debug this.

**Alternative 1: simple `.env` file**
![image](https://user-images.githubusercontent.com/78811865/110449148-35d38f00-80c2-11eb-8094-61597d13490b.png)

![image](https://user-images.githubusercontent.com/78811865/110448734-be9dfb00-80c1-11eb-86eb-52af8821249f.png)

**Alternative 1: `.env` file with `workspaceFolder` environment variable**
![image](https://user-images.githubusercontent.com/78811865/110449494-8945dd00-80c2-11eb-829b-b4a420dbd1e2.png)
![image](https://user-images.githubusercontent.com/78811865/110449690-be522f80-80c2-11eb-8192-6b555fdbd9cc.png)

**Comment by secure-mail-documentation-project** [comment]
Another thought: could part of the issue be that my project path contains a space?

**Comment by secure-mail-documentation-project** [comment]
> Another thought: could part of the issue be that my project path contains a space?

Just realized I can test this myself of course. I move the `vscode_test_project` directory to the root of an external harddrive. This got rid of the space in the project path. - No improvement at all from what I can see.

![image](https://user-images.githubusercontent.com/78811865/110452388-69fc7f00-80c5-11eb-8636-db081ef711cf.png)

**Comment by IanMatthewHuff** [comment]
@secure-mail-documentation-project Sorry about this being hard to work through, without having the issue on my box it's a bit hard to debug. 

This isn't a full fix but as a possible workaround, we have a setting to specifically run python commands at the start of any notebook or interactive window session. If you have python code to manually add something into sys.path you could put it in here and that should run that code for any interactive sessions that you start. The setting is Jupyter: Run Startup Commands. 

Currently I'm looking at all the info on configuring .env files here:
https://code.visualstudio.com/docs/python/environments#_environment-variable-definitions-file

One thing to try. With just the PYTHONPATH specified instead of printing out sys.path could you instead import os and print os.environ? I'd like to see what the PYTHONPATH looks like there before it gets added to the sys.path.

**Comment by secure-mail-documentation-project** [comment]
> @secure-mail-documentation-project Sorry about this being hard to work through, without having the issue on my box it's a bit hard to debug.
> 
> One thing to try. With just the PYTHONPATH specified instead of printing out sys.path could you instead import os and print os.environ? I'd like to see what the PYTHONPATH looks like there before it gets added to the sys.path.

No problem. I have some self-interest that this get's fixed. I am happy to help debug it.

Output of  `import os; os.environ`:

```
environ{'ALLUSERSPROFILE': 'C:\\ProgramData',
        'APPDATA': 'C:\\Users\\My User\\AppData\\Roaming',
        'APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL': 'true',
        'CHROME_CRASHPAD_PIPE_NAME': '\\\\.\\pipe\\crashpad_16488_COLSEMPABNJOSNJN',
        'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
        'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
        'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
        'COMPUTERNAME': 'MYCOMPUTER',
        'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
        'CONDA_DEFAULT_ENV': 'vscode_test_env',
        'CONDA_EXE': 'C:\\ProgramData\\Miniconda3\\Scripts\\conda.exe',
        'CONDA_PREFIX': 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env',
        'CONDA_PREFIX_1': 'C:\\ProgramData\\Miniconda3',
        'CONDA_PROMPT_MODIFIER': '(vscode_test_env) ',
        'CONDA_PYTHON_EXE': 'C:\\ProgramData\\Miniconda3\\python.exe',
        'CONDA_SHLVL': '2',
        'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
        'ELECTRON_RUN_AS_NODE': '1',
        'HOMEDRIVE': 'C:',
        'HOMEPATH': '\\Users\\My User',
        'LOCALAPPDATA': 'C:\\Users\\My User\\AppData\\Local',
        'LOGONSERVER': '\\\\MYCOMPUTER',
        'NUMBER_OF_PROCESSORS': '4',
        'ONEDRIVE': 'C:\\Users\\My User\\OneDrive',
        'ORIGINAL_XDG_CURRENT_DESKTOP': 'undefined',
        'OS': 'Windows_NT',
        'PATH': 'C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env;C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\Library\\mingw-w64\\bin;C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\Library\\usr\\bin;C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\Library\\bin;C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\Scripts;C:\\ProgramData\\Miniconda3\\envs\\vscode_test_env\\bin;C:\\ProgramData\\Miniconda3\\condabin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files (x86)\\Common Files\\Acronis\\VirtualFile;C:\\Program Files (x86)\\Common Files\\Acronis\\VirtualFile64;C:\\Program Files (x86)\\Common Files\\Acronis\\FileProtector;C:\\Program Files (x86)\\Common Files\\Acronis\\FileProtector64;C:\\Program Files (x86)\\Common Files\\Acronis\\SnapAPI;C:\\Program Files\\Intel\\WiFi\\bin;C:\\Program Files\\Common Files\\Intel\\WirelessCommon;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\nodejs;C:\\Users\\My User\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\My User\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\My User\\AppData\\Local\\Programs\\Git\\cmd;C:\\Users\\My User\\AppData\\Roaming\\npm',
        'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
        'PROCESSOR_ARCHITECTURE': 'AMD64',
        'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 61 Stepping 4, GenuineIntel',
        'PROCESSOR_LEVEL': '6',
        'PROCESSOR_REVISION': '3d04',
        'PROGRAMDATA': 'C:\\ProgramData',
        'PROGRAMFILES': 'C:\\Program Files',
        'PROGRAMFILES(X86)': 'C:\\Program Files (x86)',
        'PROGRAMW6432': 'C:\\Program Files',
        'PROMPT': '(vscode_test_env) $P$G',
        'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
        'PUBLIC': 'C:\\Users\\Public',
        'PYTHONIOENCODING': 'utf-8',
        'PYTHONPATH': '.\\some-library;c:\\Users\\My User\\.vscode\\extensions\\ms-toolsai.jupyter-2021.2.603412351\\pythonFiles;c:\\Users\\My User\\.vscode\\extensions\\ms-toolsai.jupyter-2021.2.603412351\\pythonFiles\\lib\\python',
        'PYTHONUNBUFFERED': '1',
        'PYTHONWARNINGS': 'ignore',
        'SESSIONNAME': 'Console',
        'SYSTEMDRIVE': 'C:',
        'SYSTEMROOT': 'C:\\WINDOWS',
        'TEMP': 'C:\\Users\\My User\\AppData\\Local\\Temp',
        'TMP': 'C:\\Users\\My User\\AppData\\Local\\Temp',
        'USERDOMAIN': 'MYCOMPUTER',
        'USERDOMAIN_ROAMINGPROFILE': 'MYCOMPUTER',
        'USERNAME': 'My User',
        'USERPROFILE': 'C:\\Users\\My User',
        'VS140COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\',
        'VS2019INSTALLDIR': 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools',
        'VSCODE_AMD_ENTRYPOINT': 'vs/workbench/services/extensions/node/extensionHostProcess',
        'VSCODE_CWD': 'C:\\WINDOWS\\system32',
        'VSCODE_HANDLES_UNCAUGHT_ERRORS': 'true',
        'VSCODE_IPC_HOOK': '\\\\.\\pipe\\9baa9e15493b51ce2f3ae2619e4b305b-1.53.2-main-sock',
        'VSCODE_IPC_HOOK_EXTHOST': '\\\\.\\pipe\\vscode-ipc-ec9e04af-1898-4512-8e39-7df5223d50c4-sock',
        'VSCODE_LOG_NATIVE': 'false',
        'VSCODE_LOG_STACK': 'false',
        'VSCODE_NLS_CONFIG': '{"locale":"en-gb","availableLanguages":{},"_languagePackSupport":true}',
        'VSCODE_NODE_CACHED_DATA_DIR': 'C:\\Users\\My User\\AppData\\Roaming\\Code\\CachedData\\622cb03f7e070a9670c94bae1a45d78d7181fbd4',
        'VSCODE_PID': '16488',
        'VSCODE_PIPE_LOGGING': 'true',
        'VSCODE_VERBOSE_LOGGING': 'true',
        'VTUNE_PROFILER_2020_DIR': 'C:\\Program Files (x86)\\IntelSWTools\\VTune Profiler 2020\\',
        'WINDIR': 'C:\\WINDOWS',
        'JPY_INTERRUPT_EVENT': '584',
        'IPY_INTERRUPT_EVENT': '584',
        'JPY_PARENT_PID': '504',
        'TERM': 'xterm-color',
        'CLICOLOR': '1',
        'PAGER': 'cat',
        'GIT_PAGER': 'cat',
        'MPLBACKEND': 'module://ipykernel.pylab.backend_inline'}
```

The `.env`-file used for the above output was:
```
PYTHONPATH=./some-library
```

**Comment by secure-mail-documentation-project** [comment]
@greazer I just saw, that you added 'info-needed'. Could you please explain what you need to proceed? As far as I am aware, I have provided all info requested by @IanMatthewHuff. Did I misunderstand something? I am more than happy to help debugging this.

**Comment by huweiATgithub** [comment]
In my case, the .env file doesn't load at all for a .env file as simple as,
```
TEST_VAR=123456
```
then check with,
```
import os
print(os.getenv("TEST_VAR"))
```

**Comment by DonJayamanne** [comment]
I've managed to identify the cause of the issue, when using non-conda issues we dont use the env variables at all.
