### ISSUE TITLE
Jupyter Variables disappear after clicking and other data viewer bugs

### ISSUE THREAD

**Issue by nfx** [microsoft/vscode-jupyter#5062]
Issue Type: <b>Bug</b>

Upon clicking on variable exlorer in jupyter, a window in a lower editor pane appears and asks me to pick a variable. I pick a variable and Data Viewer opens up. And Jupyter Variables window disappears. Keeping the terminal pane open, even though it was not open. This is distracting me.

Data viewer does not refresh when dataframe refreshes, nor does have a button to do so.

It would be more intuitive behavior if cmd+click (or ctrl+click for non-mac users) would lead to data viewer instead of this additional flow.

Extension version: 2021.3.600686576
VS Code version: Code - Insiders 1.54.0-insider (Universal) (e590188f17162393f50feec19263398e6fe02d13, 2021-02-26T20:39:12.763Z)
OS version: Darwin x64 19.6.0

<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvspyt639:30264824
pythontb:30258533

```

</details>

**Comment by joyceerhl** [comment]
@nfx we've added a button to refresh the data viewer and we have also addressed the issue with the Jupyter variable window disappearing--the variable window will now remain open as long as there is a notebook open in the editor. 

The refresh button should already be in your build, but the data viewer must be active and focused for the button to appear. The Jupyter variable window fix will become available in our upcoming March release.

https://github.com/microsoft/vscode-jupyter/issues/4562
https://github.com/microsoft/vscode-jupyter/pull/5006

https://github.com/microsoft/vscode-jupyter/issues/1143
https://github.com/microsoft/vscode-jupyter/pull/4951

**Comment by nfx** [comment]
@joyceerhl i'm fine with early builds :) though they have pytest behavior broken and are a bit slow ...

**Comment by joyceerhl** [comment]
@nfx are you not seeing the refresh button / does it not work in v2021.3.600686576? This is what it's supposed to look like: 

![image](https://user-images.githubusercontent.com/30305945/110426862-a8f5ea80-805b-11eb-99c5-3bb36dd9e71b.png)

It'll only appear when you have set focus to the data viewer window.

**Comment by greazer** [comment]
I believe this can be closed. @nfx, please reopen if there's something remaining.
