### ISSUE TITLE
Open a notebook already on localhost without caching

### ISSUE THREAD

**Issue by Divide-By-0** [microsoft/vscode-jupyter#5067]
Is it possible to connect directly to a running localhost address for notebooks, and ensure that none of the data is cached? This might be two completely different features.

For a specific reason why, I'd like to be able to edit remote Jupiter notebooks tunnel through SSH on the local machine and vs code, but also make sure that none of the data is leaked to cache files on the local computer.

**Comment by joyceerhl** [comment]
Hey @Divide-By-0, not sure what 'ensure that none of the data is cached' refers to. Does this command in the command palette get you what you want re: connecting directly to a running localhost address for notebooks?

![image](https://user-images.githubusercontent.com/30305945/110259033-71534980-7f5a-11eb-83e6-da3cd9c1fd9b.png)

![image](https://user-images.githubusercontent.com/30305945/110259035-731d0d00-7f5a-11eb-8019-82303ae70e0b.png)

**Comment by joyceerhl** [comment]
Closing as this issue has been inactive for >1 month. Please feel free to comment/reopen if you'd like to follow up. Thanks for reporting a bug!
