### ISSUE TITLE
Native notebooks does not ask for permission to download from the CDN

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5074]
Reset all of your VS code settings
Run a notebook with a 3rd party widget in it
3rd party widget will not display

Run same code in interactive window
It will ask if you want to download from 3rd party site
Then widget will work

**Comment by IanMatthewHuff** [comment]
Validated:
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/56097be4-4330-44bd-973b-58cbb64ab22b)

After prompt widget is downloaded / shown.
