### ISSUE TITLE
Native notebooks widget priority is lower than text/plain

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5075]
Make sure widgets work in the interactive window
Run a notebook with a widget
Try to display it.

Text/plain will text precedence.

![image](https://user-images.githubusercontent.com/19672699/110401092-c744f180-802d-11eb-9f47-caf97ccf2aef.png)

**Comment by DonJayamanne** [comment]
I believe this is an error in VS Code.
They made changes last week, and its possible they haven't fixed this issue yet.

**Comment by rchiodo** [comment]
Sorry I should have tried updating to the latest. It works in the latest bits.
