### ISSUE TITLE
Notebook saved with this tool is not portable

### ISSUE THREAD

**Issue by mluseredu** [microsoft/vscode-jupyter#5077]
## Environment data

-   VS Code version: 1.54.1
-   Jupyter Extension version (available under the Extensions sidebar): 2021.3.619093157
-   Python Extension version (available under the Extensions sidebar): 2021.2.633441544
-   OS (Windows | Mac | Linux distro) and version: Tried on Windows also 3 different Linux distros
-   Python and/or Anaconda version: Official Python 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Size of Notebook generated is similar to https://jupyter.org/ with 12Kb

## Actual behaviour

Notebook generated by this tool is ranges from 1874MB to 2857MB
Notebooks cannot be shared by all our students. Thankfully we are still in a review stage.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by IanMatthewHuff** [comment]
@mluseredu Sorry that you are having an issue with file size here. In general file sizes should be very similar between VS Code and jupyter for saved output. Currently your issue doesn't have enough information for us to really investigate. Having a code sample or sample ipynb that shows a notebook file which is way larger when created with VS Code would be what we would need to help investigate this well.

Without a code example or repro I'm just guessing here, but I do have one possible suggestion. With some visualizations they create very, very dense SVG graphics. And our tool (unlike jupyter) automatically generates both pngs and svgs for plots. So one example that I do know of where we have larger file sizes is in cases with dense SVG plots. To rule this out you could try changing the setting Jupyter: Enable Plot Viewers to false. This will prevent SVG plots from being created and might help with file size.
![image](https://user-images.githubusercontent.com/812783/110514454-281b0b00-80bc-11eb-8c1c-dab31a9c9a62.png)
Just uncheck that box in the settings. Clear your output and then re-run the notebook.

**Comment by greazer** [comment]
Issues labeled with "Info needed" are closed if we do not receive more information from the issue author in 2 weeks. If you are the issue author and you still are running into this problem, please reactivate with additional information.
