### ISSUE TITLE
Pylance works with notebook on local server, but not with notebook on remote server

### ISSUE THREAD

**Issue by FaridRodriguez** [microsoft/vscode-jupyter#5088]
I'm using Visual Studio Code Remote - SSH (0.65.1)  extension  to connect to a remote server and work with ipython notebooks. Language server (Pylance) works fine for .ipynb files on the local server.  However, for .ipynb files on the remote server Pylance is not having any visual effect.

I have Python (2021.2.633441544), Pylance (2021.3.0)  and Jupyter (2021.3.619093157) extensions in both my local and remote server, same versions in both.

## Environment data - local server

-   VS Code version: 1.54.1
-   Jupyter Extension version: 2021.3.619093157
-   Python Extension version: 2021.2.633441544
-   Language Server version: 2021.3.0
-   OS and version: Windows 10 Pro 10.0.18362
-   Python version: 3.8.5
-   Type of virtual environment used: virtualenv 20.0.31
-   Jupyter server running: Local

## Environment data - remote server

-   Jupyter Extension version: 2021.3.619093157
-   Python Extension version: 2021.2.633441544
-   Language Server version: 2021.3.0
-   OS and version: Ubuntu 20.04 LTS
-   Python version: 3.8.5
-   Type of virtual environment used: virtualenv 20.0.31
-   Jupyter server running: Remote

## Expected behaviour

Pylance-like intellisense (and theme with input code in boxes that separates it from output) for .ipynb files on remote server, just as it works on a local server.

## Actual behaviour

No Pylance-like intellisense (and theme with input code in boxes) for .ipynb files on remote server.

## Additional information

Pylance functionalities working on the local server notebook:
![working_on_local](https://user-images.githubusercontent.com/25602348/110516796-0cbdf900-80d8-11eb-9eee-bb10a3e5a704.PNG)

Pylance functionalities not working on the remote server notebook:
![image](https://user-images.githubusercontent.com/25602348/110536143-1f8ff800-80ef-11eb-8b18-7b5e37b4113f.png)

As shown here this issue affects readability:
![image](https://user-images.githubusercontent.com/25602348/110540446-8237c280-80f4-11eb-9158-140bce6cca61.png)

**Comment by IanMatthewHuff** [comment]
@FaridRodriguez Sorry could you please clarify an aspect of this for me? In the picture that you mention pylance working it seems to be missing much of the info that I would expect to see. While in the not working picture it appears to have the full info. For example this is what I see with pylance on a normal .py file locally.
![image](https://user-images.githubusercontent.com/812783/110554333-709fec00-80ef-11eb-88bb-9974d3e87d69.png)

**Comment by IanMatthewHuff** [comment]
Yes, thanks for the explanation, it's more clear now. I believe the issues that you are running into are mostly centered around how themes work with our remote support and the implementation of our old UI.

Can I ask you to check something out for me? Currently we are working on moving from an old webview based UI over to a new notebook UI that VS Code core is providing. This new notebook interface is available as the default in vscode insiders, which you can install safely next to stable vs code.
https://code.visualstudio.com/insiders/
Could you please try out your scenario in vscode - insiders? This new UI is what we are looking to move everyone to, so we're unlikely to fix a theming issue on the old UI at this point.

**Comment by FaridRodriguez** [comment]
Yes, Pylance enhancements are working just perfect even in the remote server!
![image](https://user-images.githubusercontent.com/25602348/110987236-ccab8000-833c-11eb-8ec5-0c50f7ed7c81.png)
I think this new UI is a great improvement, very simple and effective. I'll be looking forward to it's release.

**Comment by IanMatthewHuff** [comment]
Awesome glad you like it. In the old UI vscode didn't support notebook style documents so we had to implement everything by hand in a webview (which was basically just a blank webpage that an extension could open in an editor window). In the new UI vscode core provides the basic notebook UI so everything feels and looks much more consistent with core vscode editors. 

I'm going to actually close this issue now as we are not looking to make fixes in the old UI unless there are major braking issue. You can use the new UI in insiders for now (note that insiders does have minor issues from time to time as it's getting daily builds) and in stable when it fully rolls out.
