### ISSUE TITLE
Don't use throw new errors when original error was throw by us (we lose original error information)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5089]
We have 3 places where we rethrow the original error, but as a new error with additional information.
We had 2 places in the extension where this caused issues, basically:
* We are throwing exception of type A
* Then we handle this and rethrow this as a new error type B (but retain some of the original error information)
* Further up, we check if the error is type A, and do something
* However the error is no longer of type A, its a new error.

Again, this was fixed recently in a PR, but we still have at least 3 areas that still do this.
Solutions:
* Ensure we do not throw new errors if we had thrown the original error

E.g. instead of 
```throw new WrappedError(localize.DataScience.jupyterNotebookFailure().format(err), err);```
We change this to
```typescript
if (err instanceof BaseError){
	throw err;
} else 
	throw new WrappedError(localize.DataScience.jupyterNotebookFailure().format(err), err);
}
```

This can be converted into a single liner as follows:
```typescript
	throw WrappedError.from(err);
```
Where `WrappedError.from` can do the necessary checking.

**Comment by IanMatthewHuff** [comment]
Validated.
