### ISSUE TITLE
Native Notebooks - .ipynb does not respect auto save on focus change

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode-jupyter#5096]
## Environment data

Version: 1.55.0-insider
Commit: 5d80c30e5b6ce8b2f5336ed55ad043490b0b818f
Date: 2021-03-08T05:24:34.127Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

jupyter: v2021.4.637168989
python: v2021.3.636328865-dev

## Expected behaviour

- .ipynb file is saved whenever cursor select somewhere out of the notebook window frame.

## Actual behaviour

- .ipynb is NOT saved, must manually save file with cmd+s.

**Comment by jaymegordo** [comment]
No issues with .py files ever, and can't test on 1.55.0 currently, had to jump back to 1.53.0 to deal with the ENOTDIR error that @DonJayamanne is working on right now. Once that fix is built I should be able to go back to 55 and confirm that.

In general though I would definitely expect the .ipynb to save whenever I focus out of the window (eg I don't want to ever have the chance of losing saved work), so that seems like you can at least repro what I was seeing.

**Comment by IanMatthewHuff** [comment]
@jaymegordo Yeah, at a minimum I repro some inconsistent behavior regarding this. I believe that we might need to transfer to vscode core to get this fixed. If so, I'll link the issue.

**Comment by DonJayamanne** [comment]
@IanMatthewHuff Please could you file an issue with VS Code with the details, seems like you managed to repro this at your end.

**Comment by IanMatthewHuff** [comment]
https://github.com/microsoft/vscode/issues/119026 @DonJayamanne

**Comment by rchiodo** [comment]
Should be addressed already.
