### ISSUE TITLE
The button “Open in Browser” is missing.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#5099]
## Environment data

-   VS Code version: 1.55.0-insider (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): 2021.4.625511240
-   Python Extension version (available under the Extensions sidebar): 2021.4.637492490-dev

## Steps to reproduce:
1. Make sure Anaconda installed in local
2. Open the file manualTestFile.py in VSCode
3. Select conda Interpreter as current environment
4. On the first cell click `Run Cell And All Below`
5. Interactive Window should open, show connection information, and execute cells
6. The first thing in the window should have a line like this: `Jupyter Server URI: http://localhost:[port number]/?token=[token value]`
7. Check to make sure that no outputs have errors
8. Verify that graphs and progress bars are shown
9. Click the `Export as Jupyter Notebook` button in the Interactive Window
10. Choose a file location and save the generated .ipynb file
11. When the prompt comes up in the lower right choose to open the file in the browser

## Expected behaviour
The file should open in the web browser and contain the output from the Interactive Window

## Actual behaviour
The button “Open in Browser” is missing.
![image](https://user-images.githubusercontent.com/59192491/110565893-2fa8e580-818a-11eb-8144-3f9fe5d9a7d5.png)

**Comment by rchiodo** [comment]
Test plan needs to be updated. Open in Browser was removed as an option.

**Comment by DonJayamanne** [comment]
Dup of #4836
