### ISSUE TITLE
Large number of kernels are running for a single notebook

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#5100]
Issue Type: <b>Bug</b>

I was editing a TypeScrip notebook, adding cells, moving things around, running cells. I ended up with 25 running kernels.

![image](https://user-images.githubusercontent.com/4674940/110566110-63d9c300-8104-11eb-81f7-d4e1099a2c3c.png)

Extension version: 2021.4.625511240
VS Code version: Code - Insiders 1.55.0-insider (Universal) (5d80c30e5b6ce8b2f5336ed55ad043490b0b818f, 2021-03-08T05:24:34.127Z)
OS version: Darwin arm64 20.3.0
Remote OS version: Linux x64 5.4.0-1031-azure
Remote OS version: Linux x64 5.4.0-1036-azure
Remote OS version: Linux x64 5.4.0-1031-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv|--enable-proposed-api lszomoru.lszomoru-proposed-api-sample --crash-reporter-id ef10dfea-3602-4c74-ba1a-109ce7da7825|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.4.0-1031-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (5.93GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1036-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (8 x 2693)|
|Memory (System)|15.64GB (7.88GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.4.0-1031-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (5.93GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
openwslfolder:30268768
vscoresta800:30265947
vspre833:30267464

```

</details>

**Comment by rchiodo** [comment]
Thanks for the bug.

Do they go away after shutdown? This might happen if you opened a bunch of notebooks and didn't close VS code.

It should also be noted you're listing ports there. Each kernel running opens 5 ports. Each notebook being open runs two kernels. So just having two notebooks open would be 10 ports visible.

**Comment by rchiodo** [comment]
I believe we recently changed disposing of kernels though? @IanMatthewHuff , @DonJayamanne could this be related to the dispose on editor close?

**Comment by DonJayamanne** [comment]
Let me check and get back.

**Comment by DonJayamanne** [comment]
> So just having two notebooks open would be 20 ports visible.

Agreed.

> d this be related to the dispose on editor close?

Can confirm that the kernels do get disposed when we close the notebooks.

**Comment by kieferrm** [comment]
I worked with only one notebook. I might have reopened it once or twice.

**Comment by greazer** [comment]
Let's see what's happening here.

**Comment by greazer** [comment]
@kieferrm, can you still repro this? Don has not been able to on Mac.
