### ISSUE TITLE
:Jupyter Variables pane... why ":"?

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-jupyter#5102]
Is there a reason there is a ":" in the Jupyter Variables pane name?

![image](https://user-images.githubusercontent.com/1487073/110570389-a6060300-810a-11eb-8c15-6d0ea17cb695.png)

Why isn't it just `JUPYTER VARIABLES`?  Would match the rest of VS Code...

**Comment by rchiodo** [comment]
Thanks. 

Looks like we didn't enter a bug here after discovering this same thing:
https://github.com/microsoft/vscode-jupyter/issues/4458

**Comment by IanMatthewHuff** [comment]
@chrisdias Yeah, from day one we had it as Jupyter : Variables where Jupyter was the view container name and Variables was the webview view name. We didn't love having the ":" in there so we tried not naming the view container and just naming the view Jupyter Variables. Oddly enough this worked for many members of the team but at least one of them (and you as well) was seeing the leading ":". Might be more issues associated with not having the view container named, so we're just going to revert it back.

**Comment by joyceerhl** [comment]
Validated. In main bits it's back to what it used to be.
![image](https://user-images.githubusercontent.com/30305945/112048713-ef435300-8b0b-11eb-883c-cf36e0b0727e.png)
