### ISSUE TITLE
Guest cannot execute cells even though enable "Allow Guest Execute Cells".

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#5105]
## Environment data
![image](https://user-images.githubusercontent.com/59192491/110598689-fe95d880-81bc-11eb-9c42-55bc253a2e45.png)

## Steps to reproduce:
1. Install the LiveShare VSCode Extension (VS Live Share Extension Pack)
2. Open manualTestFile.py in VSCode
3. Run the first cell in the file
4. Switch to the `Live Share` tab in VS Code and start a session
5. Move your cursor to a line, but don't select anything. Shift-enter should send that line to the Interactive Window
6. Verify that Jupyter server instance should appear in the live share tab
7. Open another window of VSCode
8. Connect the second instance of VSCode as a Guest to the first Live Share session
9. After the workspace opens, open the manualTestFile.py on the Guest instance
10. Open VS Code settings, change "Liveshare>languages:Allow Guest Command Control" to true
11. Change "Liveshare>languages:Allow Guest Execute Cells" to true
12. On Guest intance, click "Run cell"
![image](https://user-images.githubusercontent.com/59192491/110598922-4ae11880-81bd-11eb-9fce-ce14edc538b3.png)

## Expected behaviour
The file can be executed.

## Actual behaviour
"Run cell" is gray and cannot be clicked.
![image](https://user-images.githubusercontent.com/59192491/110596431-41a27c80-81ba-11eb-9b8d-b20071adb141.png)

**Comment by IanMatthewHuff** [comment]
Closing LiveShare related issues.
