### ISSUE TITLE
"autoreload" module not found using magic % command

### ISSUE THREAD

**Issue by candrewlee14** [microsoft/vscode-jupyter#5106]
## Environment data

-   VS Code Insiders version: 1.53.2
-   Jupyter Extension version (available under the Extensions sidebar): 2021.2.603412351
-   Python Extension version (available under the Extensions sidebar): 2021.2.633441544
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.6.12
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Expected behaviour

Load extension autoreload when running `%load_ext autoreload`.

## Actual behaviour

```
ModuleNotFoundError: No module named 'autoreload\r'
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-60c900c3607f> in <module>
      1 get_ipython().run_line_magic('matplotlib', 'inline\r')
      2 get_ipython().run_line_magic('matplotlib', 'notebook\r')
----> 3 get_ipython().run_line_magic('load_ext', 'autoreload\r')
      4 get_ipython().run_line_magic('autoreload', '2\r')
```

## Steps to reproduce:

Open a notebook file in VSCode Insiders, put the following at the top of a cell in a notebook file and run.
```
%matplotlib inline
%matplotlib notebook
%load_ext autoreload
%autoreload 2
```
Opening it in VSCode Insiders with those settings above and the new notebooks view, I get the error.
On VSCode (not Insiders), this works for me and I get no errors on that same cell.

--- 

Let me know if you need anything more, or if this is the wrong repo to file this issue on.
Thanks!

**Comment by rchiodo** [comment]
Thanks for the bug. 

Is this the same notebook with the same python environment (kernel) in both versions of VS?

Your issue sounds similar to this one:
https://stackoverflow.com/questions/47577596/modulenotfounderror-no-module-named-autoreload

What happens if you just do an ```import autoreload```?

I'd also be curious in the version that's working, what you get if you print the autoreload file.

```python
import autoreload
print(autoreload.__file__)
```

For me that file is here:

```d:\Source\Testing_5\testenv\lib\site-packages\IPython\extensions\autoreload.py```

**Comment by candrewlee14** [comment]
Yeah, same notebook with the same environment.

I did take a look at that error you linked before I filed this bug, and I had deleted any trailing whitespace.
That didn't resolve the issue for me.

This is what is printed for the autoreload file:

Non-working VS Insiders:
`c:\users\candr\miniconda3\envs\proj3\lib\site-packages\IPython\extensions\autoreload.py`

Working VS:
`C:\Users\candr\miniconda3\envs\proj3\lib\site-packages\IPython\extensions\autoreload.py`

**Comment by rchiodo** [comment]
Are you saying you can ```import autoreload``` but ```%load_ext autoreload``` fails?

**Comment by candrewlee14** [comment]
Yep, I just commented out the original `%load_ext autoreload` line, added the `import autoreload` line, and there was no error.

**Comment by rchiodo** [comment]
I'm wondering if there's an extra character being added in by our own stuff that's causing this problem.

**Comment by rchiodo** [comment]
Can you try the python insiders version and updating to our latest jupyter version?

Mine look like this:

![image](https://user-images.githubusercontent.com/19672699/110706982-807e0580-81ad-11eb-8fa8-f0e1dc34cea4.png)

![image](https://user-images.githubusercontent.com/19672699/110707000-8673e680-81ad-11eb-9a28-71c796f7fe32.png)

Insiders python version can be set here:
![image](https://user-images.githubusercontent.com/19672699/110707056-9b507a00-81ad-11eb-9d49-e83465d3b5fa.png)

**Comment by candrewlee14** [comment]
![image](https://user-images.githubusercontent.com/32912555/110707368-6b59a480-81b6-11eb-8ee1-f9ab7032027f.png)

Reloaded and ran again. Same error...

**Comment by rchiodo** [comment]
Your insiders version is also out of date. At least it might be if it still matches what your original entry described. This is the latest:

Version: 1.55.0-insider (user setup)
Commit: 5d80c30e5b6ce8b2f5336ed55ad043490b0b818f
Date: 2021-03-08T05:13:14.184Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by rchiodo** [comment]
Do you have other extensions installed? They might be interfering with the text. 

Additionally can you try this with the interactive window? 
https://code.visualstudio.com/docs/python/jupyter-support-py#_python-interactive-window

That doesn't load any extensions so it should be just the text you type in.

**Comment by joyceerhl** [comment]
Closing as this issue has been inactive for >1 month. Please feel free to comment/reopen if you'd like to follow up. Thanks for reporting a bug!
