### ISSUE TITLE
Autocomplete within strings does not work in notebooks

### ISSUE THREAD

**Issue by GarretOConnell** [microsoft/vscode-jupyter#5119]
## Environment data

-   VS Code version: 1.54.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.3.619093157
-   Python Extension version (available under the Extensions sidebar): v2021.2.636928669
-   OS (Windows | Mac | Linux distro) and version: macOS Catalina 10.15.17
-   Python and/or Anaconda version: 3.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | Remote

## Expected behaviour

When typing a path or a pandas column name in string, tab should trigger autocomplete options.

## Actual behaviour

Tab inserts a tab space.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open jupyter notebook with Python kernel in VScode
2. import pandas and create dataframe  "df" with column called "user
3. type "df['u']" with prompt after u and press tab.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
@GarretOConnell  Sorry for not getting back to you on this issue.
I think you are using the WebView based Notebooks. We're currently working on a better implementation of Notebooks.
Please could you install VS Code Insiders & try this out (you'll see the new notebook in there).
I believe this should work in there.

FYI - The notebook in VSCode Insiders is a first class citizen in VS Code and supports most if not all of the VSCode Editor functionality.

**Comment by GarretOConnell** [comment]
@DonJayamanne thanks very much, Insiders working with Intellisense for paths, and [this fix](https://stackoverflow.com/questions/60203867/how-to-show-docstring-or-function-signature-in-vs-code-for-a-jupyter-notebook) worked for docstrings - perhaps should be standard setting.
