### ISSUE TITLE
Jupyter Graffiti isn't working

### ISSUE THREAD

**Issue by darshan6** [microsoft/vscode-jupyter#5121]
Issue Type: <b>Bug</b>

Hello, I've been trying to work on Udacity jupyter files, but the jupyter graffiti extension is not working in vscode, it works fine when I launch it through jupyter-notebook in Anaconda. here is the link for Jupyter graffiti repo https://github.com/willkessler/jupytergraffiti 

Extension version: 2021.3.619093157
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.8.0-43-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz (4 x 1176)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 1|
|Memory (System)|7.62GB (0.22GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 68187822-f2a7-4374-9a8e-46d516cca282|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vspre833:30267464

```

</details>

**Comment by DonJayamanne** [comment]
Thanks for filling this issue. Unfortunately we don't support such Jupyter extensions that update the vscode ui. (The Jupyter extension you are referring to is build specifically for Jupyter).

Please consider using a vscode extension for screenshots of the like, please check the vscode marketplace for similar extensions.
