### ISSUE TITLE
Extra data on hover is missing in old webview

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5124]
I have pylance and I'm using an ipynb file. This is what i see when i try to get the docstrings from a function inside a modelu.
The first one is from VS Code Insiders which works pretty fine.
![Captura de pantalla (22)](https://user-images.githubusercontent.com/55694226/110837592-b7354800-82a1-11eb-9d52-2889c5a7c251.png)
![Captura de pantalla (23)](https://user-images.githubusercontent.com/55694226/110837596-b7cdde80-82a1-11eb-8b96-118b42d2f9b4.png)

_Originally posted by @arribass in https://github.com/microsoft/vscode-jupyter/issues/4218#issuecomment-796958313_

**Comment by rchiodo** [comment]
I can repro too. Webview is not showing the extra data anymore. Likely another API change.

**Comment by joyceerhl** [comment]
Hmm I'm seeing this with Pylance installed and set as `python.languageServer` in the custom editor:

![image](https://user-images.githubusercontent.com/30305945/113433644-76a68700-9394-11eb-923d-ee9d574cc118.png)

Is this expected behavior @rchiodo?

**Comment by rchiodo** [comment]
No that's the bug. David's merge should have fixed it.

**Comment by DavidKutu** [comment]
You need to click the 'i' to get the documentation.

**Comment by joyceerhl** [comment]
Thanks @DavidKutu, closing as validated: 
![image](https://user-images.githubusercontent.com/30305945/113632079-58a08700-961f-11eb-9b61-4af6de634bc5.png)
