### ISSUE TITLE
Provide an API for Jupyter to not provide preferred kernels when there are other 3rd party VS Code Kernels

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5126]
Assume we have .NET Interactive extension is installed:
* Today we do not provide preferred kernels for .NET languages based on metadata in kernelspec.

Some extensions do not install the kernel specs:
* Other language extensions would like to provide VS Code kernels
* How can we (Jupyter extension)  not provide a preferred kernel for such languages when users have these extensions installed that could potentially have their own kernels.

**Suggestions:**
* Get some API from VS Code
* Expose an API in jupyter that allows extensions to hide our Jupyter kernels based on some condition

**Comment by davidanthoff** [comment]
This would be exceptionally helpful from the Julia extension's point of view!

**Comment by davidanthoff** [comment]
Actually, could this behavior just be triggered by [this](https://github.com/julia-vscode/julia-vscode/blob/334a1334189f1dfe28d77c14b879b4ac59cc0e5b/src/notebook/jupyterExtension.ts#L17)?

This should probably be based on language, right? Essentially a way for the Julia extension to tell the Jupyter extension to not provide any kernels for the Julia language, right?

**Comment by rchiodo** [comment]
@DonJayamanne, @davidanthoff do we still need this? I believe we don't set a preferred kernel unless the notebook is using a python kernel. Julia provides it's own kernels (notebook controllers) and VS code remembers the last setting anyway. 

Is there still a need for us to stop specifying 'preferred' on kernels that the jupyter extension returns?

**Comment by davidanthoff** [comment]
I'm not sure :) I think at some point @DonJayamanne mentioned that the plan was that the Jupyter extension would not surface Julia kernels at all once we enable notebook support in the Julia extension by default? But I'm not sure whether that is still the plan. I'm also not sure whether it really is a good idea, at the end of the day I can imagine that someone for one reason or another would want to use the Jupyter kernel rather than the Julia notebook controller, and then the only way to do that would presumably be to disable the Julia extension, or something like that? 

But, at the moment the general UI experience for kernel selection is a bit confusing, I think. Here is how it looks on my system right now, for example:

![image](https://user-images.githubusercontent.com/1036561/131581113-de2e115c-63cb-4c95-83d1-40bf9ab85d9e.png)

**Comment by rchiodo** [comment]
@davidanthoff I believe if the julia kernels provide the metadata like the .NET kernels do, then that list would only show the ones provided by the julia extension. And yes if a user wants to run the jupyter julia kernel, they'd have to disable the julia extension (we check for this metadata when exposing kernels)

Metadata looks like so (I think):

```json
metadata: {
  vscode: {
    extension_id: "julialang.language-julia"
  }
}
```

Is there a use case for having both at the same time? Feels like it would be confusing to the user to have to pick.

**Comment by rchiodo** [comment]
@davidanthoff was that solution good enough?

**Comment by DonJayamanne** [comment]
Not sure Julia extension has control over the kernels (they don't register the kernels).
Lets discuss in triage.

**Comment by rchiodo** [comment]
Do we still need this functionality? There's better sorting in the kernel picker now. With the julia extension installed (and having a julia jupyter kernel) I get this now:

![image](https://user-images.githubusercontent.com/19672699/150407855-6bb99c24-3f30-4d86-af9b-a39efaf8ae71.png)

**Comment by DonJayamanne** [comment]
I agree, we should just close this.

**Comment by greazer** [comment]
Yes, removing special casing for 3rd party kernels (including .NET) is a good idea here.

**Comment by rchiodo** [comment]
Should be done now

Verification steps:

- Install [.NET kernel in jupyter](https://github.com/dotnet/interactive/blob/main/docs/NotebookswithJupyter.md)
- Install [.NET interactive](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode)

Open a notebook.

You should have two kernels (at least) for .NET.
