### ISSUE TITLE
Autocomplete in subsequent cells is not working 

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5129]
Using native notebooks in insiders have two cells like so:
1)
```
import numpy as np
```
2)
```
np.
```
Auto complete does not work correctly in the second one (it seems to only use jupyter)

![image](https://user-images.githubusercontent.com/19672699/110847139-67369100-8261-11eb-99dc-723b6456e5da.png)

**Comment by DonJayamanne** [comment]
Unable to repro, @rchiodo are you able to repro this issue?
Moving to validate, hopefully someone else can confirm this is working.

**Comment by IanMatthewHuff** [comment]
Validated for me at least.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/17100776-8daa-4c19-826e-91909e63eb1e)
