### ISSUE TITLE
VS Code not finding conda python interpreter & failing to open ipynb file

### ISSUE THREAD

**Issue by Tony-Boksic** [microsoft/vscode-jupyter#513]
# Bug: VS Code not finding conda python interpreter & failing to open ipynb file

## Steps to cause the bug to occur

1. Open ipynb file in a jupyter notebook in VS Code. The corrupted ipynb file is attached below.

## Actual behavior

The ipynb file fails to open and returns the following error message:

Command failed: C:/Users/Tony/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\Tony.vscode\extensions\ms-python.python-2020.9.112786\pythonFiles\pyvsc-run-isolated.py c:/Users/Tony/.vscode/extensions/ms-python.python-2020.9.112786/pythonFiles/printEnvVariables.py

Source: Python(Extension)

VS Code fails to find the conda python interpreter and the kernel is not found. 

From the Developer Tools Console Output below, it looks like the corrupted file is pointing to the MYSQL Workbench python interpreter.

## Expected behavior

I can no longer open the attached ipynb file in a VS-Code jupyter notebook. I have a problem with this one particular file as my other files open without a problem. I think that the problem comes from an error in the metadata as the metadata in this file looks very different to the metadata structure of the other files that successfully open.

This file used to open without any glitch in the past but now when I try to open the file, I see the above error.

I have pasted below the metadata information from a ipynb that opens successfully. The corrupted file used to open just like all my other files but recently it has produced this bug and I'm wondering how I can alter the metadata of the corrupted file in order to successfully open the file in a VS Code jupyter notebook.

### Jupyter and/or Python environment

-   **Jupyter server running:** Local 
-   **Extension version:** 2020.9.114305
-   **VS Code version:** 1.50.1
-   **Setting python.jediEnabled:** false
-   **Setting python.languageServer:** Microsoft
-   **Python and/or Anaconda version:**  Python 3.8.3 64-bit ('base': conda)
-   **OS:** Windows
-   **Virtual environment:** conda 

**##Developer Tools Console Output**

notificationsAlerts.ts:40 

Command failed: C:/Users/Tony/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\Tony\.vscode\extensions\ms-python.python-2020.9.114305\pythonFiles\pyvsc-run-isolated.py c:/Users/Tony/.vscode/extensions/ms-python.python-2020.9.114305/pythonFiles/printEnvVariables.py
onDidChangeNotification @ notificationsAlerts.ts:25

DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Tony/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/semver-umd.js.map: 

DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Tony/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/tas-client-umd.js.map: 

DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Tony/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/main.js.map: 

**Corrupted IPYNB file**
[Corrupted_file.txt](https://github.com/microsoft/vscode-python/files/5415500/Corrupted_file.txt)

**Metadata of IPYNB file that opens successfully in VS Code**

 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.8.3 64-bit ('base': conda)",
   "language": "python",
   "name": "python_defaultSpec_1597947257101"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3-final"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

**Comment by Tony-Boksic** [comment]
Hi Rich,

Thanks for getting back. I've got just the one Kernel available:

C:\Users\Tony\anaconda3\share\jupyter\kernels\python3

As I have deleted the metadata from the ipynb file, it doesn't seem like the notebook is pointing to any specific kernel.  

Do I need to specify the above kernel in the JSON file?

**Comment by rchiodo** [comment]
Sorry I may have misunderstood. I thought it wasn't working with the metadata in the notebook? Or is the metadata not in the notebook?

If it's the latter, you may have a problem with the 'jupyter interpreter' being set to a non existent interpreter. You can verify this by picking the 'Select interpreter to start jupyter server'. 

If that fixes it, I should reopen this bug and change it to be about us using a non existent interpreter.

**Comment by Tony-Boksic** [comment]
@rchiodo 

Hi Rich,

Thanks for taking the time to help. That has fixed it. You're correct that the jupyter interpreter was incorrectly set.

I understand that it is confusing so I'll recap what has happened.

- I originally had a corrupted ipynb file that no longer opened in VS Code as it was pointing to a non-existant python interpreter.
- You provided a solution that involved deleting the metadata from this same ipynb file in order to open the file in VS Code.
- This solution worked for a while. Once the metadata was deleted, the ipynb file opened successfully.
- However, that same ipynb file stopped working and no longer opened. It is the same ipynb file with the metadata removed.
- When I tried to open the file, it produced this error:

Command failed: C:/Users/Tony/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\Tony.vscode\extensions\ms-python.python-2020.9.114305\pythonFiles\pyvsc-run-isolated.py c:/Users/Tony/.vscode/extensions/ms-python.python-2020.9.114305/pythonFiles/printEnvVariables.py

As Rich indicated, by selecting the correct jupyter interpreter, this resolved the issue.

cheers, Tony

**Comment by rchiodo** [comment]
Thanks Tony.

I think I'm going to open another issue that makes sure we verify the jupyter intepreter before attempting to use it.
