### ISSUE TITLE
Jupyter notebooks deleting cells when saved

### ISSUE THREAD

**Issue by aparente-nurix** [microsoft/vscode-jupyter#5134]
Issue Type: <b>Bug</b>

This has happened 3 times now. I've either clicked save from the menu or used the keyboard shortcut to save a jupyter notebook and it reverts back to an older state of the file somehow. I opened a new notebook and replicated the issue. This is connected to a linux machine (from windows) through remote SSH. It happens transiently but frequently!

Extension version: 2021.3.619093157
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 3.10.0-1062.18.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (1.67GB free)|
|Process Argv|--crash-reporter-id e07a59f2-521a-4ce2-a228-0a2c780d3879|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: aparente-t7820|
|OS|Linux x64 3.10.0-1062.18.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz (48 x 1200)|
|Memory (System)|125.35GB (51.06GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by aparente-nurix** [comment]
It looks like I can recover it when closing the current open window and going to the file in the github tab to reopen it, but not from the explorer tab. It's not consistent either, in that i reopened it once successfully but then it went back to the reverted version again.

**Comment by greazer** [comment]
@aparente-nurix, can you give us a screenshot of your notebook? Just the cell UI we don't need your python code specifically.

**Comment by greazer** [comment]
cc: @microsoft/datascience-vsc-team-reviewers

**Comment by aparente-nurix** [comment]
![image](https://user-images.githubusercontent.com/53059220/111695110-f3abfb00-87ef-11eb-974d-9b1abce31c81.png)
Thanks for responding @greazer. Hopefully this can get resolved soon, the new notebook features in VScode insiders are really nice!

**Comment by rchiodo** [comment]
This sounds like a VS code issue (they control saving). 

See this issue here:
https://github.com/microsoft/vscode/issues/118592

**Comment by DonJayamanne** [comment]
Closing this issue in favor of the upstream VS Code issue.
