### ISSUE TITLE
Cannot import pyarrow

### ISSUE THREAD

**Issue by Kerybas** [microsoft/vscode-jupyter#5139]
## Environment data

-   VS Code version: 1.54.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.3.619093157
-   Python Extension version (available under the Extensions sidebar): v2021.2.636928669
-   OS (Windows | Mac | Linux distro) and version: Win10
-   Python and/or Anaconda version: 3.7.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | N/A: Local
-  pyarrow, from conda:  pyarrow 3.0.0 py37h633fffd_7_cpu

## Expected behaviour

I should be able to import pyarrow in a Notebook.

## Actual behaviour

import pyarrow: `ImportError: DLL load failed: The specified module could not be found.`

it works in a terminal, both from python and ipython.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

import pyarrow

**Comment by Kerybas** [comment]
A new install of pyarrow via another channel solved this strange issue.

**Comment by claudiaregio** [comment]
@Kerybas Closing as this issue seems resolved with a new install of pyarrow.
