### ISSUE TITLE
Candidates for Point release

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5147]
* Ignore failures when loading extension (ensure Python doesn't fail to load)
* Fixes for ENOTDIR (getActivatedEnv variables argument change) - unblocks users
* Activating Python extension unnecessarily (https://github.com/microsoft/vscode-jupyter/issues/5193)
	* Perf issues related to activation (https://github.com/microsoft/vscode-jupyter/issues/5004)
* Cannot read property 'then' of `undefined` https://github.com/microsoft/vscode-jupyter/issues/4976

**Comment by joyceerhl** [comment]
I'd like to include https://github.com/microsoft/vscode-jupyter/pull/5103, data viewer looks terrible in default light theme otherwise.

**Comment by joyceerhl** [comment]
We should also include https://github.com/microsoft/vscode-jupyter/issues/5057 in a point release for stable VS Code. This PR fixes a bad regression introduced in https://github.com/microsoft/vscode-jupyter/pull/4951 that causes duplicate data to be fetched into the data viewer.

**Comment by DonJayamanne** [comment]
Lets just ship next week.
