### ISSUE TITLE
Native Notebooks - Julia notebook not recognized? 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5148]
## Steps to reproduce:
1. Create new notebook
2. Switch kernel to julia 
3. Add some cells and save 
4. Send to someone else to open OR close vs code and reopen notebook

## Expected behaviour

Notebook opens with cell language as Julia

## Actual behaviour

Notebooks opens up with cell language as Python

**Comment by DonJayamanne** [comment]
@claudiaregio 
You'll need to run a cell, and then the cell information is saved in the notebook.
Lert me know what you think.

Note: Please install latest VS Code Insiders **(todays build)** to test this out (not stable).

**Comment by no-trick-pony** [comment]
> 
> 
> @claudiaregio
> You'll need to run a cell, and then the cell information is saved in the notebook.
> Lert me know what you think.
> 
> Note: Please install latest VS Code Insiders **(todays build)** to test this out (not stable).

At least for me this was not what's happening when using a notebook created with the current version of VS Code and Jupyter plugin and then opened with the Insiders version of both, see https://github.com/microsoft/vscode-jupyter/issues/5237#issuecomment-804561372

**Comment by DonJayamanne** [comment]
@claudiaregio this should be fixed in the latest Insider Build.

**Comment by IanMatthewHuff** [comment]
Validated. Scenario looks good for me now.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/8120245c-9c0e-4d24-a640-6aa0fb00f0f7)
