### ISSUE TITLE
Support for vega and vega-lite MIME types

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode-jupyter#5149]
[This](https://gist.github.com/davidanthoff/2283338575e7584a0d91fb1cc18fde9d) is a Jupyter notebook that has cell output that uses the `application/vnd.vegalite.v4+json` MIME type (and I manually removed the PNG and SVG versions of the same output that normally get included).

This kind of file shows the plot successfully both in Jupyter Lab and nteract, because both of those clients natively support the vega and vega-lite MIME types.

From my chat with @DonJayamanne I got the impression that this extension here would also support these MIME types out of the box? At the moment that doesn't seem to work because the plot is not displayed when I open this file in the Jupyter extension in VS Code.

**Comment by DonJayamanne** [comment]
Thanks @davidanthoff I'll look into this.

**Comment by IanMatthewHuff** [comment]
Example provided looks good with the new transforms update:
![image](https://user-images.githubusercontent.com/812783/112534308-21e98780-8d68-11eb-889a-4e054b0ff7de.png)

**Comment by joyceerhl** [comment]
Validated with the ipynb that David provided in this issue description and the latest VSIX build off main:
![image](https://user-images.githubusercontent.com/30305945/113642144-0322a500-9634-11eb-95e4-615b046b5c17.png)

**Comment by davidanthoff** [comment]
Great, thanks!
