### ISSUE TITLE
Suggestion: Kernel Doctor - notebook for diagnosing kernel problems

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5150]
@kieferrm  had this suggestion (it's been used before by other teams).

When a kernel startup fails, open up something (maybe a notebook) that the user can use to diagnose the problem themselves. 

Examples might include:
- Run the exact python command we just ran that failed (so the user can see the explicit output)
- Run commands that generate the pip list and allow it to be sent to us
- Run commands that pip uninstall/install stuff (if we know this might fix the problem, like with the zmq.constants failure)

Basically a self help wizard.

**Comment by rebornix** [comment]
> maybe a notebook

I love this idea a lot. It can open a special jupyter notebook with a diagnostic kernel and users can read the guidances (markdown cells) and run code cells with troubleshooting scripts.

**Comment by DonJayamanne** [comment]
Closing this as I don't think this is required anymore, if we do need such a thing then we can re-visit the requirements
