### ISSUE TITLE
Perf investigation: Investigate what makes inversify take so long

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5153]
We haven't actually figured out why (sometimes) creating the DI container takes so long.

Why does the jupyter extension take seconds to activate when it should be immediate.

Potential solutions:
- Change how we call inversify
- Fix inversify
- Stop using DI all together

**Comment by DonJayamanne** [comment]
> Stop using DI all together

👍🏾 (we can just new-up the classes we need). We can mock/stub using sinon as required for unit tests.

**Comment by rchiodo** [comment]
Stop using DI seems like a lot of work. We'd have to:
- Turn singletons into static objects
- New up everything everywhere else
- Rewrite a lot of our unit tests.

VS code has services too. I wonder how they do it?

**Comment by DonJayamanne** [comment]
Is this an issue, 

> We haven't actually figured out why (sometimes) creating the DI container takes so long.

Can we get some telemetry to see how slow/fast this is.
I.e. do we even need to do anything here?
I know at times somethigns have been slow, but its possible its just a specific machine or some other side effect of some other package or the like.

**Comment by rchiodo** [comment]
Yeah not sure. Need some telemetry I guess (and/or a profile of startup). On my machine the current startup time is 500ms. Seems fine.

Maybe we turn this item into telemetry for startup and add stuff like:
- Container init
- Extension activation
- IExtensionSingleActivationService timing

**Comment by rchiodo** [comment]
Turns out we already have this telemetry. It's under the event EXTENSION.LOAD event. Sent here:
https://github.com/microsoft/vscode-jupyter/blob/22866fa676ab480dbd18c24d09398bd9c24a2746/src/client/startupTelemetry.ts#L52

**Comment by rchiodo** [comment]
I did some preliminary investigation. The vast majority of people are under 5 seconds, and then even more under 10. But there's a non insignificant portion that take longer than 10 seconds to startup:

![image](https://user-images.githubusercontent.com/19672699/156620039-37522a7d-e3ea-4eb5-924e-be0975fa32f4.png)

**Comment by rchiodo** [comment]
Moving back to triage to see if we want to investigate more.

**Comment by rchiodo** [comment]
This makes me less concerned (crunching by percentiles)

![image](https://user-images.githubusercontent.com/19672699/156622256-0b319af0-3967-48fa-bb36-f5bd8f9e5ed6.png)
