### ISSUE TITLE
Show available kernels rather than languages in `Create New Blank Notebook` UI

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode-jupyter#5155]
@DonJayamanne helped us "register" the Julia extension with the Jupyter extension so that we show up in the new notebook UI, which is great!

Currently the UI looks like this:

![image](https://user-images.githubusercontent.com/1036561/111014150-43557700-8357-11eb-83c7-2be3bdd0b6fa.png)

Is that essentially showing a list of extensions? It doesn't look like a list of kernels or languages?

I think ideally the UI that would show up would show a list of _kernels_, right? Because one can always infer the correct language if a user has made a kernel choice. That would also correspond to how this is handled in Jupyter Lab:

![image](https://user-images.githubusercontent.com/1036561/111014245-ad6e1c00-8357-11eb-9811-a04f124c9470.png)

and nteract:

![image](https://user-images.githubusercontent.com/1036561/111014224-99c2b580-8357-11eb-8dfa-21fa3044d1a3.png)

**Comment by claudiaregio** [comment]
@DonJayamanne Last we discussed this you mentioned generating the full list of kernels available could take ~10s. 
Would we cut down on the generation time of the list of kernels if it is selected after a user picks the extension? 
Create new nb -> ext -> kernel list available to user + supported by extension

**Comment by davidanthoff** [comment]
Are there specific kernel types where it would take so long to generate the concrete list of kernels? I think on the Julia side of things we could probably return that list very fast, I would imagine that we would create the list of kernels we can provide at startup of our extension, so that if the Jupyter extension then queried for that list we could return it more or less instantanious.

But I imagine that for example when it comes to the remote server scenario, it might get slow? Maybe a UI design could be that the first top level list shows all the kernels that can be listed quickly (local kernelspecs and kernels provided by other extensions), and then there is a final entry "Remote kernels..." that would then open another sub list, and would be slower?

I do think it would be nice if we had a UI story here that mimics the other Jupyter clients and is not too deeply nested to generate a new notebook. I just seems quite cumbersome for a user to go through new nb->extension->kernel selection, just to create a new notebook, when the same operation is really quite direct in both Jupyter Lab and nteract...

**Comment by claudiaregio** [comment]
@davidanthoff I'll wait for Don to respond regarding the technical questions but I agree. The original plan was to surface the available kernels but given the amount of time it would take to generate that full list, users may think something was broken. The next best thing was to surface the extension (which for now seemed like a good temporary solution since the extension name matched the language - .NET, Julia and seemed intuitive enough for users. Very doubtful they read the full description of the drop down menu option, once they see the name they recognize they click that option)

**Comment by DonJayamanne** [comment]
Enumerating kernels can be very slow (specially when we look for python interpreters).
Also in the case of remote, we get kernels from a remote API call.
Hence displaying the list of kernels in the `Create Blank Notebook` might not be the best option.

At least not until we can guarantee it will be fast (very fast), at least under 2-3s. any longer, then the user would dismiss the propmt all together and move onto another approach.

**Comment by DonJayamanne** [comment]
@claudiaregio I'd suggest we park this issue for now (I know you have another start page that you're workign on as well). its an unnecessary risk (blocking UI that could result in a poor/slow UX).

**Comment by claudiaregio** [comment]
@DonJayamanne agreed

**Comment by DonJayamanne** [comment]
Closing this issue as this command has since been removed.
