### ISSUE TITLE
Markdown cells not rendering LaTeX in latest update

### ISSUE THREAD

**Issue by AvyayIrde** [microsoft/vscode-jupyter#5158]
Issue Type: <b>Bug</b>

Extension version: 2021.3.619093157
VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.19042

<b>Actual Behaviour:</b>

![image](https://user-images.githubusercontent.com/45104854/111030450-4f5d3980-8428-11eb-9cd1-0c497dcbf36a.png)

<b>Expected behaviour:</b>
Older build:
Extension version: 2021.2.576440691
VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.19042

![image](https://user-images.githubusercontent.com/45104854/111030555-f7730280-8428-11eb-8faa-d55343f4555f.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800HS with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.42GB (7.40GB free)|
|Process Argv|--crash-reporter-id 6bdba1e9-9fc1-4296-a856-a1e30b6f8dac|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vspre833cf:30267465
vsfjg287:30275553

```

</details>

**Comment by claudiaregio** [comment]
Hi @AvyayIrde, could you please try adding the following to your JSON settings and let me know if the issue persists? 
"notebook.experimental.useMarkdownRenderer": true,

**Comment by AvyayIrde** [comment]
it fixed few of the lines,
![image](https://user-images.githubusercontent.com/45104854/111061288-8b47db80-84c8-11eb-9d2f-e6b2e7968169.png)
 the whole block before rendering:
![image](https://user-images.githubusercontent.com/45104854/111061318-b4686c00-84c8-11eb-9e2c-2bc3414774f3.png)

**Comment by claudiaregio** [comment]
Hi @AvyayIrde, based on the screenshots I am a bit confused. The first screenshots and info provided indicate the issue was with VSC Stable and the second screenshots are from VSC Insiders. Could you clarify which build you are seeing issues with?

**Comment by hui2000ji** [comment]
Same issue here.
![image](https://user-images.githubusercontent.com/32122441/111257701-9761a380-8656-11eb-8488-a6c742e645b0.png)

**Visual Studio**
Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Jupyter**
Version: v2021.3.619093157

**Comment by hui2000ji** [comment]
Downgrading the Jupyter extension to v2020.12.414227025 and open my ipython notebook in "Notebook Editor" (rather than "Preview Notebook Editor") works (successfully displays latex).

**Comment by AvyayIrde** [comment]
> Hi @AvyayIrde, based on the screenshots I am a bit confused. The first screenshots and info provided indicate the issue was with VSC Stable and the second screenshots are from VSC Insiders. Could you clarify which build you are seeing issues with?

 I'm facing issues in build 2021.3.619093157 which I believe is the latest stable version.
 
 In the latter screenshot, I downgraded the extension to build 2021.2.576440691 which solved the issue.
 
This is what happened when I added "notebook.experimental.useMarkdownRenderer": true, to my JSON settings which partially fixed the issue:
![](https://user-images.githubusercontent.com/45104854/111061288-8b47db80-84c8-11eb-9d2f-e6b2e7968169.png)
`

**Comment by claudiaregio** [comment]
@AvyayIrde and @hui2000ji, thanks for the additional info. Based on the extra info provided, you have been placed into the Native Notebooks experience in VS Code. Rendering latex is not yet supported fully for native notebooks, but will be soon. 

If this is currently a complete blocker for you, you can opt out of the experiment by following these instructions: 

- Open the command palette (Windows: Ctrl + Shift + P, iOS: Command + Shift + P) and select "Preferences: Open Settings (JSON)"

- Add the following code to your JSON settings: "jupyter.experiments.optOutFrom": ["NativeNotebookEditor"]
