### ISSUE TITLE
Please update the variable explorer like Spyder... I'm waiting

### ISSUE THREAD

**Issue by Ikhwansong** [microsoft/vscode-jupyter#5160]
I have searched, is there any extension or feature to alternate the default variable explorer built in vscode.

But there were nothing. In terms of a brief test or to checking the variables produced by running a main code, the spyder's variable explorer is very convenient.

why is there not yet like that?

**Comment by claudiaregio** [comment]
Hi @Ikhwansong, are you having trouble finding the variable explorer? 

If you are working with VS Code Stable, the icon circled below will open the variable explorer. 

![image](https://user-images.githubusercontent.com/19276747/111039411-cc65c000-83e2-11eb-861b-3f8f7ee54b78.png)

If you are working with VS Code Insiders or are have native notebooks in stable, the toolbar is located in the top right. The icon circled below will open the variable explorer. 

![image](https://user-images.githubusercontent.com/19276747/111039566-98d76580-83e3-11eb-9449-779f53c025a2.png)

For more support for VSC Stable: https://code.visualstudio.com/docs/python/jupyter-support
For more support for VSC Insiders: https://github.com/microsoft/vscode-jupyter/wiki/Introducing-Native-Notebooks

**Comment by Ikhwansong** [comment]
Is this only available at the jupyter notebook environment?

**Comment by Ikhwansong** [comment]
Oh sorry. Here is the repository for the vscode jupyter.
