### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Varnei** [microsoft/vscode-jupyter#5162]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.2.603412351`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by claudiaregio** [comment]
Hi @Varnei 
Could you please provide some additional details on the issue you are experiencing? 
Helpful information includes steps to reproduce, expected behavior vs. actual behavior, pictures or screen recordings when applicable. (https://www.screentogif.com)
