### ISSUE TITLE
How to remove the previous kernal?

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/vscode-jupyter#5163]
I just want to keep one kernal, how to do it, i have deleted pycharm kernal.
![image](https://user-images.githubusercontent.com/33288114/111073067-359b1f80-8518-11eb-8f82-4f96494210bd.png)

**Comment by claudiaregio** [comment]
Hi @CatNofishing, Have you tried reloading the window? To do so open the command palette by pressing Ctrl + Shift + P (Cmd + Shift + P on Mac) and type "reload". Then select "Developer: Reload Window". When I did this it removed the kernel I deleted from the list providing in VS Code. 

![image](https://user-images.githubusercontent.com/19276747/111079993-a3fcc500-84b9-11eb-8f81-1582d8334803.png)

**Comment by CatNofishing** [comment]
@claudiaregio Thanks  your reply, i tried reloading the window, but it does  not work.😂

**Comment by claudiaregio** [comment]
@CatNofishing Even restarted VS Code? What steps did you take to delete the kernel? 
If you run the command "jupyter kernelspec list" in a terminal/command prompt, is the kernel you deleted still in that list? 


![image](https://user-images.githubusercontent.com/19276747/111090521-3c606d00-84ed-11eb-9f98-c17eb7458f89.png)

**Comment by CatNofishing** [comment]
@claudiaregio I run the command "jupyter kernelspec list" in a terminal ,i find that  kernel  still in that list,so i deletd the kernel then it works well. Thanks your reply.😁😁😁

**Comment by claudiaregio** [comment]
Great!! Glad to hear it wasn't a bug, the kernel was just hiding :)
