### ISSUE TITLE
Use 3rd party package to process ANSI codes

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5166]
Today we manually handle 3 different ansi codes in stream output (\r, backspace, uparrow).
Using a 3rd party package will improve the code and ensure it works across native/interactive & future proof it.
FYI - with the native notebooks even with VS Code handling these characters, we're going to have to handle these, when saving we're going to have to save the processed/stripped string.
Else we could end up with a large string, when only one line is to be displayed.

**Comment by joyceerhl** [comment]
Another candidate is xterm.js, I parked a PR I was working on to allow xterm.js to run in node environments without hacks

**Comment by DonJayamanne** [comment]
Not necessary, closing for now until we run into more issues
