### ISSUE TITLE
Goto cell command

### ISSUE THREAD

**Issue by pokey** [microsoft/vscode-jupyter#5168]
It would be great to have a "Goto Cell" command that does what the "Goto [xx]" codelens does for the cell where the cursor is currently positioned.

I have a feeling that the [`createExecutionLens`](https://github.com/microsoft/vscode-jupyter/blob/b368ea9326c13d6497e0f070d89d810d4ff86416/src/client/datascience/editor-integration/codeLensFactory.ts#L456) function could be used for this purpose without too much change

**Comment by pokey** [comment]
Poked around a bit more and seems like it would be even easier to just do something like [`getCurrentCellLens`](https://github.com/microsoft/vscode-jupyter/blob/b368ea9326c13d6497e0f070d89d810d4ff86416/src/client/datascience/editor-integration/codewatcher.ts#L1078) but looking for a command of `Commands.ScrollToCell` instead of `Commands.RunCell`.  WDYT?  Happy to file a PR on this one; looks like a pretty quick fix

**Comment by joyceerhl** [comment]
Thanks for the suggestion @pokey, and we're always happy to take PRs!

**Comment by pokey** [comment]
Cool! Will take a swing. Any thoughts on exact command name?

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
