### ISSUE TITLE
Export as Jupyter Notebook option saves files in wrong location

### ISSUE THREAD

**Issue by forsakenquantum** [microsoft/vscode-jupyter#5171]
When I choose the "Export as Jupyter Notebook" icon in VS Code, it brings up a standard Windows file picker window. I choose the directory and file name that I want and say OK. However, the file doesn't show up in that location; instead, it shows up in `C:\Users\Username\AppData\Local\Programs\Microsoft VS Code\c:\path\chosen\for\output\notebook.ipynb`.

**Comment by joyceerhl** [comment]
@forsakenquantum I just tried this but cannot reproduce the problem. Please could you fill our our bug template? At a minimum it would really help to have your VS Code version, Jupyter extension version, and operating system info. If you can provide detailed logs that would also be helpful.

**Comment by forsakenquantum** [comment]
@joyceerhl sure; can you point me to the bug template? I tried finding one but I couldn't. Also, are there instructions somewhere that I can follow about capturing logs?

In the mean time, here are the specs I'm working with:

VS Code info:
```
Version: 1.54.2 (user setup)
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:19.848Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

Jupyter extension: `ms-toolsai.jupyter 2021.3.619093157`

Device info:
```
Processor	Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz   2.11 GHz
Installed RAM	16.0 GB
Device ID	3EDE34B0-EF44-431E-9142-5753ECA0FFC0
Product ID	00330-62964-96164-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points
```

Windows info:
```
Edition	Windows 10 Pro
Version	20H2
Installed on	‎11/‎14/‎2020
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0
```

**Comment by joyceerhl** [comment]
The bug template is https://github.com/microsoft/vscode-jupyter/issues/new?assignees=&labels=bug&template=1_bug_report.md. An extra question:

Are you exporting from the interactive window? If so did you create the interactive window in association with a Python file, and where is that Python file located?

You can get debug logs by going to your settings and setting `jupyter.logging.level` to 'debug', reloading VS Code, repeating the repro steps, and then pasting the output of the Jupyter output tab:
![image](https://user-images.githubusercontent.com/30305945/111670178-c9007900-87d4-11eb-836e-372c380cae08.png)
