### ISSUE TITLE
`Failed to connect to Jupyter notebook` Kernel Python 3 is not usable.

### ISSUE THREAD

**Issue by phisanti** [microsoft/vscode-jupyter#5175]
## Summary

I am currently using paperspace, an AWS cloud computing provider. They allow simple access to EC2 terminals in AW2 with GPU acceleration. I created a docker image based on code-server and then I installed the python/jupyter extension. However, each time I try to launch a notebook I get an error related to the port's availability. I have already tried the apply the solutions proposed in issues #494, #4937, #5814 and #4866, but unfortunately, the error persisted. Although it could be the case I wasn't able to understand the solution or applied to my case, I thought my issue was a genuine error because I don't even get a token, just `...`.

Thank you in advance for the help.

## Environment data

-   VS Code version: v1.53.2
-   Jupyter Extension version (available under the Extensions sidebar): v2020.10.332292344
-   Python Extension version (available under the Extensions sidebar): v2020.10.332292344
-   OS (Windows | Mac | **Linux** distro) and version: Ubuntu 20.04.2 LTS
-   Python and/or Anaconda version: conda 4.9.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Tried all, base VE, and outside conda.
-   Jupyter server running: Local | **Remote** | N/A: Remote

## Expected behaviour

Run jupyter notebook.
## Actual behaviour

Prompt with the message:
```
Failed to connect to Jupyter notebook. http://127.0.0.1:8889/ Error: Kernel Python 3 is not usable. Check the Jupyter output tab for more information.
```
If I try to run the notebook from the terminal:

```
root@nfmkayr8:/notebooks# jupyter notebook --allow-root
[I 14:56:06.292 NotebookApp] The port 8888 is already in use, trying another port.
[I 14:56:06.296 NotebookApp] Serving notebooks from local directory: /notebooks
[I 14:56:06.296 NotebookApp] Jupyter Notebook 6.2.0 is running at:
[I 14:56:06.296 NotebookApp] http://localhost:8889/?token=...
[I 14:56:06.296 NotebookApp]  or http://127.0.0.1:8889/?token=...
[I 14:56:06.297 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 14:56:06.302 NotebookApp] No web browser found: could not locate runnable browser.

```

## Steps to reproduce:

We use code-server

1. Create an EC2 machine with Ubuntu and VScode-server. This can be done via paperspace -> image -> VScodeserver or following [this ](https://medium.com/@annantguptaneema/increase-productivity-with-vscode-server-2b5027e086ce)tutorial to set it in EC2 directly.
2. Run the machine and install python extension v2020.10.332292344
3. Reload
4. From the command palette, create a blank Jupyter notebook
5. Install the required libraries
6. Run a cell with `print("Hello World")` OR run command `jupyter notebook --allow-root`

## Logs

Here, I have not been able to activate the debug mode to see the "full output" so I posted the brief terminal output in the "actual behaviour" section.

**Comment by phisanti** [comment]
Hi @rchiodo, I know it might sound ridiculous, but unfortunately, the infrastructure where I have to run the system does not allow yet to update to a later version. That is the latest we can use until they do a general update. Regarding the debug option, I could not find it in my extension settings, so I tried the following approach:

```
 /notebooks# jupyter notebook --log-level='DEBUG' --allow-root
```
 And this is the print report in the terminal:
```
[D 17:45:02.537 NotebookApp] Searching ['/notebooks', '/root/.jupyter', '/home/coder/miniconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 17:45:02.537 NotebookApp] Looking for jupyter_config in /etc/jupyter
[D 17:45:02.538 NotebookApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 17:45:02.538 NotebookApp] Looking for jupyter_config in /home/coder/miniconda3/etc/jupyter
[D 17:45:02.538 NotebookApp] Looking for jupyter_config in /root/.jupyter
[D 17:45:02.538 NotebookApp] Looking for jupyter_config in /notebooks
[D 17:45:02.540 NotebookApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 17:45:02.540 NotebookApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 17:45:02.540 NotebookApp] Looking for jupyter_notebook_config in /home/coder/miniconda3/etc/jupyter
[D 17:45:02.540 NotebookApp] Looking for jupyter_notebook_config in /root/.jupyter
[D 17:45:02.541 NotebookApp] Looking for jupyter_notebook_config in /notebooks
[D 17:45:02.548 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
        /etc/jupyter/jupyter_notebook_config.json
[D 17:45:02.549 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
        /usr/local/etc/jupyter/jupyter_notebook_config.json
[D 17:45:02.549 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
        /home/coder/miniconda3/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
        /home/coder/miniconda3/etc/jupyter/jupyter_notebook_config.json
[D 17:45:02.551 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
        /root/.jupyter/jupyter_notebook_config.json
[I 17:45:03.028 NotebookApp] The port 8888 is already in use, trying another port.
[I 17:45:03.029 NotebookApp] The port 8889 is already in use, trying another port.
[W 2021-03-17 17:45:03.377 LabApp] 'allow_root' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-03-17 17:45:03.377 LabApp] 'allow_root' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2021-03-17 17:45:03.391 LabApp] JupyterLab extension loaded from /home/coder/miniconda3/lib/python3.8/site-packages/jupyterlab
[I 2021-03-17 17:45:03.392 LabApp] JupyterLab application directory is /home/coder/miniconda3/share/jupyter/lab
[I 17:45:03.399 NotebookApp] Serving notebooks from local directory: /notebooks
[I 17:45:03.399 NotebookApp] Jupyter Notebook 6.2.0 is running at:
[I 17:45:03.400 NotebookApp] http://localhost:8890/?token=...
[I 17:45:03.400 NotebookApp]  or http://127.0.0.1:8890/?token=...
[I 17:45:03.400 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 17:45:03.407 NotebookApp] No web browser found: could not locate runnable browser.
```

Do you think is there any other way to start the debug mode in my current python version?

**Comment by rchiodo** [comment]
Oh actually you're using VS code server. That's not VS code. We don't actually support that product at the moment. You'd be better off logging an issue there. Or perhaps trying to use [remote SSH instead](https://code.visualstudio.com/docs/remote/ssh)

I'm not even sure how to get our extension log from VS code server.
