### ISSUE TITLE
Survey request while opening a github issues notebook

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#5181]
Issue Type: <b>Bug</b>

1) Open a github issues notebook (which is not a Jupyter notebook)
->

![image](https://user-images.githubusercontent.com/4674940/111392432-cdf9e700-8673-11eb-8c20-fc54eb4d6ff7.png)

Extension version: 2021.4.641214696
VS Code version: Code - Insiders 1.55.0-insider (Universal) (892a1083cb2b9b3987ff7edc85376b5d9764433d, 2021-03-16T05:11:50.271Z)
OS version: Darwin arm64 20.3.0
Remote OS version: Linux x64 5.4.0-1031-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv|--enable-proposed-api lszomoru.lszomoru-proposed-api-sample --crash-reporter-id ef10dfea-3602-4c74-ba1a-109ce7da7825|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.4.0-1031-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (5.94GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
vscoresta800:30265947
vspre833:30267464
vsdfh931:30275552

```

</details>

**Comment by DonJayamanne** [comment]
TODO:
* [ ] Ensure we check all such messages/hooks to check if the notebook is a Jupyter notebook

**Comment by IanMatthewHuff** [comment]
Validated. Reset my settings and opened non-jupyter notebooks. Didn't see the survey.
