### ISSUE TITLE
Update CI pipeline to upload Insider builds every night (midnight or 1 am)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5182]
Only if Notebook tests are green
We need to ensure flaky tests do not block these uploads.

TODO: We need to find out how long VS Code insider builds take (right now I'm assuming it takes < 2 hours, and will be ready by 1am)

**Comment by IanMatthewHuff** [comment]
Validated. Scheduled build is running and releasing.
https://github.com/microsoft/vscode-jupyter/runs/2200966253?check_suite_focus=true
