### ISSUE TITLE
Can't edit multiple lines in a cell 

### ISSUE THREAD

**Issue by ChristosBouronikos** [microsoft/vscode-jupyter#5184]
## Environment data

-   VS Code version: 1.54.3
-   Jupyter Extension version (available under the Extensions sidebar): v2021.3.619093157
-   Python Extension version (available under the Extensions sidebar): v2021.3.658691958
-   OS (Windows | Mac | Linux distro) and version: Windows 10 - 10.0.19042
-   Python and/or Anaconda version: 3.8.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

When inside a cell, holding the "Alt" button and clicking in multiple places with the mouse, it should show multiple cursors and allow editing in multiple places.

## Actual behaviour

When inside the cell, if you hold the "Alt" button and click in multiple places to enable multiple cursors, when you *lift* the "Alt" button, the multiple cursors disappear and the cell will take the focus, instead of the inside of the cell where you were trying to edit.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Click inside a cell where you want to write text.
2. Press the "Alt" button and hold it pressed
3. While holding "Alt", click in multiple places where you want to edit with multiple cursors.
4. Release the "Alt" button.
5. Multiple cursors disappear and the focus turns to the outside of the cell.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the bug.

This should be addressed when we switch over to VS code's new notebook API. Please track this issue for when we switch:
#1231.

You can try it yourself if you use VS code [insiders](https://code.visualstudio.com/insiders/).

**Comment by ChristosBouronikos** [comment]
Thanks so much for the information.
Do you know where I can find more info about the new notebook API?

**Comment by rchiodo** [comment]
@claudiaregio's blog about it is a good starting point:
https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/

You can also read about the API here if you're interested in using it yourself (or contributing)
https://code.visualstudio.com/api/extension-guides/notebook

**Comment by ChristosBouronikos** [comment]
Thank you for being so nice and informative 😊.
