### ISSUE TITLE
Updates to Notebook API

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5191]
* Checking if a notebook has been closed using window.onDidCloseNotebookDocument instead of edito.onDidDispose
* Stdout & stderr streams have been added (we can stop using the text stream)

**Comment by IanMatthewHuff** [comment]
@DonJayamanne Made the onDidDispose change. Is there info about the stderr / stdout streams? Not seeing anything on the API announce page or in the proposed.d.ts
