### ISSUE TITLE
Extensibility: Support more than the two CDNs we have for ipywidget download

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5192]
Other teams (and companies probably) don't host their ipywidget script source on the CDNs we use.

We could make this more flexible by:

- Allow it to be specified in settings (this would replace our custom algorithm we have now for each CDN)
```json
{
   "cdns": [
      "unpkg.com" : "http://unpkg.com/^{moduleName}@{moduleVersion}/dist/index"
      "jsdelivr.com" : "http://jsdelivr.com/{moduleName}@{moduleVersion}/dist/index.js"
      "ml.azure.com" : "http://ml.azure.com/dist/location/^{moduleName}/index.js"
   ]
}
```

or 

- Making it in a json file on our github page (so we can add remove cdns (and people can submit PRs to add them).

or some other method to allow CDNs to be added.

**Comment by DonJayamanne** [comment]
Closing this as this was primarily requested because an internal team was having trouble getting ipywidgets working.
I.e. it was merely a work around.
