### ISSUE TITLE
Inconsistent separated theme in interactive window.

### ISSUE THREAD

**Issue by maxwellzh** [microsoft/vscode-jupyter#5196]
## Environment data

-   VS Code version: `1.54.3`
-   Jupyter Extension version (available under the Extensions sidebar): `v2021.3.619093157`
-   Python Extension version (available under the Extensions sidebar): `v2021.3.658691958`
-   OS (Windows | Mac | Linux distro) and version: `Local Mac and Remote Ubuntu 18.04`
-   Python and/or Anaconda version: `python 3.8.8 and conda 4.9.2`
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): `conda`
-   Jupyter server running: `Remote`

## Expected behaviour

I'd like to set jupyter interactive windows with separated theme (Light) to my vscode dark theme with the setting:`Jupyter: Ignore Vscode Theme` enabled.
<img width="773" alt="截屏2021-03-18 上午11 18 12" src="https://user-images.githubusercontent.com/32546978/111569363-724b6d00-87dd-11eb-9e4e-3b103e0671bd.png">

This is what it looks as I manually switch vscode to light theme and disable that option.
<img width="333" alt="截屏2021-03-18 上午11 19 11" src="https://user-images.githubusercontent.com/32546978/111569566-dd953f00-87dd-11eb-8346-5e414dcec846.png">

## Actual behaviour

As enabling that option and set vscode theme to dark, the background color and highlight of code syntax in interactive windows do switch to Light theme, but others like the icons in the top and toolbars above code box are still the color in dark theme.
<img width="330" alt="截屏2021-03-18 上午11 18 34" src="https://user-images.githubusercontent.com/32546978/111569774-54323c80-87de-11eb-986d-87d5724e8a9e.png">

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Set vscode theme to dark theme.
2. Enable that option in Setting.
3. Reload vscode window.
4. Open the notebook.

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987.
