### ISSUE TITLE
Word wrap not working

### ISSUE THREAD

**Issue by ChineseOuchie** [microsoft/vscode-jupyter#5197]
## Environment data

-   VS Code version: 1.54.3
-   Jupyter Extension version: 2021.3.619093157
-   Python Extension version: 2021.3.6568691958
-   OS (Windows | Mac | Linux distro) and version: Windows 10 pro
-   Python and/or Anaconda version: Python 3.8.6
-   Type of virtual environment used: N/A
-   Jupyter server running: Local

## Expected behaviour

Words will not wrap and you will see a horizontal scroll bar.

## Actual behaviour

Words are wrapping even when word wrap option is OFF

## Steps to reproduce:
1. Turn off wordwrap
2. Change windows size

![](https://i.imgur.com/q7X7eCk.gif)

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
