### ISSUE TITLE
Bug Report: Jupyter Data Viewer Filter will generate duplicated data in the viewer

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5200]
@znzhao commented on [Thu Mar 18 2021](https://github.com/microsoft/vscode/issues/119271)

When there are many columns and many rows in the data (for example in the sample data I have more than 50 columns and more than 5000 rows), using the filter in the data viewer will display a wrong line of duplicated data.
Screenshot:
When using the filter (looking up for ID = 1):
![image](https://user-images.githubusercontent.com/46983185/111668911-44b5f200-87e4-11eb-9555-7e3f2a4624fc.png)
 Actually, the data in line 1852 is:
![image](https://user-images.githubusercontent.com/46983185/111669127-76c75400-87e4-11eb-93eb-c66fd8dbc31f.png)

The bug can be replicated by the following file:
[testbug.zip](https://github.com/microsoft/vscode/files/6166045/testbug.zip)

The Python extension version that I use: v2021.3.658691958
VS code Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by joyceerhl** [comment]
Thanks for reporting a bug @znzhao I can reproduce the issue with the sample you provided. Will investigate.

**Comment by joyceerhl** [comment]
Strangely I cannot reproduce this in main bits. Going to need to poke at this more.

**Comment by znzhao** [comment]
> Strangely I cannot reproduce this in main bits. Going to need to poke at this more.

I think it is related to the sample size (and the column size). If the sample size is small, this issue will be gone.

With my computer, it looks like a dataframe with size (5000*50) will generate this issue. The real data that I worked with has a much larger size.

**Comment by znzhao** [comment]
On my computer, a sample size of (1000*5) will have no problem. I am not majored in computer science, so I am not sure I can report the bug in more detail, but just in case, I can list some info about my computer:
Core:
Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz   2.50 GHz
RAM: 8GB

**Comment by joyceerhl** [comment]
@znzhao sorry, to be more specific, I could reproduce the issue with the dataset you provided in Stable VS Code with Jupyter extension v2021.3.619093157. But I couldn't reproduce it with the *exact same dataset* and a debug extension running with the latest bits from our main branch. Appreciate your patience while I debug this :)

**Comment by znzhao** [comment]
I see. Thank you for the updating!

**Comment by joyceerhl** [comment]
@znzhao, I believe this has been fixed in v2021.4.641214696--however this version of the extension is only compatible with VS Code Insiders. If you would like to try out the fixed version, you can install VS Code Insiders here: https://code.visualstudio.com/insiders/ 

![image](https://user-images.githubusercontent.com/30305945/111686439-4ed8f000-87e6-11eb-8c2e-e03fa7391561.png)
