### ISSUE TITLE
Native Notebooks - Double kernel options shows

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5205]
VSC Insiders Version: 1.55.0
Jupyter: v2021.4.641214696
Python: v2021.4.665330847-dev

![image](https://user-images.githubusercontent.com/19276747/111680028-04a04080-87df-11eb-91db-ed50541175c4.png)

**Comment by greazer** [comment]
Showing extra kernels is annoying, but doesn't technically block usage. Therefore, moving to June release.

**Comment by DonJayamanne** [comment]
I believe this has been resolved.

**Comment by IanMatthewHuff** [comment]
I don't have the specific validation here. But closing to clear up our queue. @claudiaregio please reactivate if you are still seeing it.
