### ISSUE TITLE
Zeromq for Mac M1  & other linux distros 

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5206]
Zeromq is used to communicate with kernels. If zeromq didn't work on an os, then we rely on users installing jupyter, which will install python and zeromq will get built on the os.
Mac m1 is an os for which we don't have a prebuilt binary.

* I can confirm building zeromq works on Mac M1, & this works in a Mac

**TODO:**
* Ship this as an experiment (for controlled roll out)
* Consider contributing upstream
* Sign & Build dependencies (build pipeline)
* Should we sign & build dependencies for all OS & linux distros (even though we already have pre-built packages via npm)
* How to detect what's a Mac M1
	* We could optionally load currrenly shipped zeromq and then if that fails, try our build.
	* Would require some changes to the zeromq package code or we'll need to update the files during runtime.

**Comment by daler6** [comment]
Just so I am clear, does this mean that this issue is still being addressed and I will need the Python extension to run Jupyter notebooks on a Mac M1 machine until it is solved?

**Comment by DonJayamanne** [comment]
>  and I will need the Python extension to run Jupyter notebooks on a Mac M1 machine until it is solved?

Unfortunately yes, please consider installing the Julia extension, which supports jupyter notebooks without zeromq.

**Comment by daler6** [comment]
I did install the Julia extension - version 1.3.30 (tried both regular and insider). As I mentioned in my original bug report, I can run Jupyter notebooks using Julia code, but on the Mac M1, I also have to install the Python extension to get this to work. On the MacBook Pro with an Intel chip, I do not have to install the Python extension. So, perhaps the issue is in the Julia extension and how it works with the M1 chip?

**Comment by DonJayamanne** [comment]
> n. So, perhaps the issue is in the Julia extension and how it works with the M1 chip?

Please file an issue with Julia extenssion if notebooks do not work in Mac m1.

**Comment by daler6** [comment]
Will do. In fact this is where I originally filed this issue.

**Comment by xiajunwen1007** [comment]
Any progress here? There is a similar issue caused by this [#4](https://github.com/njpipeorgan/wolfram-language-notebook/issues/4)

**Comment by theelderbeever** [comment]
Is there an interim solution for users on this front? My .env files won't reload in jupyter and this problematic.

**Comment by DonJayamanne** [comment]
> Is there an interim solution for users on this front?

I'm sorry, however there's no work around for now. Related comments here https://github.com/microsoft/vscode-jupyter/issues/9774#issuecomment-1110329606

**Comment by DonJayamanne** [comment]
Summary of discussion with @deepak1556 

# Build
- Build on the CI pipeline (with Mac OS <version> SDK), we provide the target arch (e.g. arm64) - via a cross compilation
- We cross compile as there's no arm64 machine on CI
- Ensure zeromq has the build targets for arm64 (seems to work for Don on his M1, hence things should work as expected)
- Create separate pipeline for building on Mac arm
- Here's an sample pipeline https://github.com/microsoft/vscode/blob/4c72dedb4ad283a569f83a7389468c3ae2c642c3/build/azure-pipelines/darwin/product-build-darwin.yml#L98-L116

# Signing
- [ ] Check with Steven/Isidor about signing contents in the vsix (are they signed today)

# OS
- On website
- Platform all 3 arcs (32, 64, arm64)
- No support for linux 32
- Check link provided for supported - (https://code.visualstudio.com/docs/supporting/requirements#_platforms)
    - These are the minimum versions supported
    - We might want to consider building for these as well.

# Mac Universal?
- This is the future (no arch specific builds)
- Highly recommended (core ships universal for binaries)
- We might want to build a universal binary for Mac (then we ship just a single binary)
- Build x64 and arm64, then use mac toolchain to create universal binary (lipo)
	- https://github.com/microsoft/vscode/blob/4c72dedb4ad283a569f83a7389468c3ae2c642c3/build/azure-pipelines/darwin/product-build-darwin-universal.yml
- [ ] We might want to add a universal tag into extension package.json so it shows up in marketplace
