### ISSUE TITLE
I think that pyvsc-run-isolated.py has a bug (Python 3.x.x 64-bit requires ipykernel to be installed.)

### ISSUE THREAD

**Issue by adp-study** [microsoft/vscode-jupyter#5212]
## Environment data

-   VS Code version: 1.54.3
-   Jupyter Extension version (available under the Extensions sidebar): 2021.3.619093157
-   Python Extension version (available under the Extensions sidebar): 3.8.8 64bit
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.8.8 (it is not anaconda)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Jupyter will execute python code normally.

## Actual behaviour

When I execute python code with jupyter(Ctrl+Enter), vscode says `python requires ipykernel to be installed`.

If I comment code with in `pyvsc-run-isolated.py` as bellow or python38.zip that extract to site-packages path than Jupyter works perfectly.

```
#sys.path[0] = os.path.join(os.path.dirname(__file__), ".does-not-exist")
```

sys.path has package path to search(in my case sys.path[0] has `d:\\python3\\python38.zip`) but `pyvsc-run-isolated.py` removes it.

Sorry for my pure English.

---
my bad. I didn't know about sys.path[0] behavior.
Only windows build(from www.python.org) works differently.
For more robust code, why don't you check sys.path[0]'s ext. Thank you very much. I love vs-code and jupyter.

## Steps to reproduce:

install python-3.8.8-embed version from python.org(and jupyter package has installed too) then the problem is occurred.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
 d:\python3\python.exe c:\Users\RyuShin\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
Error 2021-03-19 14:25:16: Find kernel spec, Class name = O, completed in 5335ms, has a falsy return value, Arg 1: <Uri:z:\Projects\CAPTCHA\ttest.py>, Arg 2: undefined, Arg 3: undefined, Arg 4: undefined, Return Value: undefined [a [Error]: IPyKernel not installed into interpreter Python 3.8.8 64-bit:d:\python3\python.exe
	at O.installDependenciesIntoInterpreter (c:\Users\RyuShin\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:1:301391)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async O.getKernelForLocalRawConnection (c:\Users\RyuShin\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:1:299935)] {
  category: 'noipykernel',
  reason: 1
}
```

</p>
</details>

**Comment by RyuSh1n** [comment]
my bad. I didn't know about sys.path[0] behavior.
Only windows build(from www.python.org) works differently.
For more robust code, why don't you check sys.path[0]'s ext. Thank you very much. I love vs-code and jupyter.

**Comment by DonJayamanne** [comment]
Thanks for the feedback, I'll look into this ASAP,

**Comment by RyuSh1n** [comment]
I heard from bug.python.org. Isolated mode is probably enabled, i.e. `sys.flags.isolated == 1`. It's enabled by default for the embedded distribution [1], or if a "._pth" file exists beside and with the same base name as the executable or DLL (e.g.  "python._pth" or "python38._pth") [2].

By default, in embedded distribution, jupyter extension does not work properly.

**Comment by IanMatthewHuff** [comment]
I believe that this is fixed with the change from Don above. You can try this out now by downloading vscode insiders (which works SxS with stable) or wait until our next monthly release. Just ping back here if you are still seeing issues.
