### ISSUE TITLE
vscode  separate  interactive window to  another window.

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/vscode-jupyter#5216]
I have two monitors. I want to move the interactive window to another screen. How can I do that?

**Comment by claudiaregio** [comment]
Hi @CatNofishing, VS Code does not support pop-out windows at this time. 
Updates for this feature can be found here: https://github.com/microsoft/vscode/issues/10121

**Comment by DonJayamanne** [comment]
Closing this as its an upstream issue.
