### ISSUE TITLE
[Proposed API deprecation] NotebookContentProvider#resolveNotebook

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-jupyter#5217]
From the proposed API, we will remove the `NotebookContentProvider#resolveNotebook`-function. To establish a communication channel between renderers and extensions use `NotebookKernelProvider#resolveKernel`

**Comment by IanMatthewHuff** [comment]
Our only usage for this is for widget tests that are currently disabled. Will make the change and look at re-enabling those tests.
