### ISSUE TITLE
Jupyter extension

### ISSUE THREAD

**Issue by Luismunguiasalas** [microsoft/vscode-jupyter#5219]
Issue Type: <b>Bug</b>

Simply try to open a jupyter notebook

2021.3.658691958/pythonFiles/printEnvVariables.py bash: /Library/Frameworks/Python.framework/Versions/2.7/bin/python: Bad CPU type in executable

Extension version: 2021.3.619093157
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.1.0

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
pythonvspyt943cf:30277002
vscoresta800cf:30276762
vspre833cf:30267465
vsdfh931:30275552
vshan820:30276952

```

</details>

**Comment by claudiaregio** [comment]
Hi @Luismunguiasalas 
Could you please provide some additional details on the issue you are experiencing? 
Helpful information includes pictures or screen recordings when applicable. (https://www.screentogif.com)

**Comment by greazer** [comment]
@Luismunguiasalas, support for Python 2.7 is being deprecated. Please install a newer version of Python.
