### ISSUE TITLE
Jupyter Notebook Not Recognizing SKLEARN package install

### ISSUE THREAD

**Issue by drewipson** [microsoft/vscode-jupyter#5223]
## Environment data

-   VS Code version: 1.54.3
-   Jupyter Extension version (available under the Extensions sidebar): v2021.3.619093157
-   Python Extension version (available under the Extensions sidebar): 
-   OS (Windows | Mac | Linux distro) and version: MacOS Big Sur 11.2.3
-   Python and/or Anaconda version: Python 3.9.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour
After running a `python3 -m pip install sklearn` and the package installs and then running a `python3 -m pip freeze >> requirements.txt` command, I expect to be able to start up my notebook and import the sklearn library. Specifically, importing the classification_report from the sklearn.metrics module using this command in the first cell of the my notebook: `from sklearn.metrics import classification_report`.

## Actual behaviour

Upon running the 'from sklearn.metrics import classification_report` I receive the following error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-bc0c60130838> in <module>
      2 import numpy as np
      3 from textblob import TextBlob
----> 4 from sklearn.metrics import classification_report

ModuleNotFoundError: No module named 'sklearn'
```

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. `python3 -m venv env`
2. `python3 -m pip install sklearn`
3. Open jupyter notebook in VS Code.
4. First cell: `from sklearn.metrics import classification_report`

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
> /usr/local/bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/local/bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/local/bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/local/bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
```

</p>
</details>

**Comment by claudiaregio** [comment]
Hi @drewipson, if you pull the list of packages on the environment you are trying to use, does scikit-learn show up in that list? If not try pip install scikit-learn in your virtual environment instead. Does this code work if you try to run in in a Jupyter notebook in the browser? I am unable to reproduce this behavior at this time.

**Comment by drewipson** [comment]
@claudiaregio 

Yes, I was able to 'pip freeze' my libraries and it is there. I was also able to inspect the virtual environment library folder and it is there. I started a Jupypter notebook up in the browser and the library was able to import.

**Comment by claudiaregio** [comment]
@drewipson would you mind posting a pic of the notebook canvas with the error you are getting?

**Comment by drewipson** [comment]
https://user-images.githubusercontent.com/24757991/112086193-65b67400-8b51-11eb-8e67-b338c824b1d0.mov

@claudiaregio Here is a screen recording of the issue. I was able to fix the issue by running the notebook in a jupyter server. Once I did that, the next time I reopened it in VSCode the jupyter notebook worked inside VS Code.

**Comment by DonJayamanne** [comment]
@drewipson 
Please could you try the following:
* Create a new cell and type the following & execute it
```python
import sys
sys.executable
```
* Type the following in your terminal
```python -c "import sys;print(sys.executable)"```


Confirm both values are the same, if not, please ensure you activate the environment in the terminal or select the appropriate Intepreter from the kernel picker on the top right.


> python3 -m venv env
> python3 -m pip install sklearn

Based on your comments, this will not work correctly.
If you want to install sklearn into the virituanl environment `env`, then you'll first need to actiavte it as follows:
`source env/activate`, once done, use `python -m pip install...` instead of `python3`.

Please see here for usages of virtual environment for more information (activation & pip install) https://docs.python.org/3/tutorial/venv.html
