### ISSUE TITLE
"python.terminal.activateEnvironment": True will cause jupyter no kernel to select

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/vscode-jupyter#5224]
If you set "python.terminal.activateEnvironment": True,the jupyetr can not find a kernel to start cell

**Comment by DavidKutu** [comment]
Thanks for the issue @CatNofishing. I'm sorry you're having issues.

- How are you trying to start the cell? Is that the Interactive Window or is it a notebook?
- Does an error notification come up? If so, could you share it?
- Could you set this setting: `"jupyter.logging.level": "debug"` and then repro the issue, and share the Jupyter Output?

Please let me know to take a deeper look.

**Comment by CatNofishing** [comment]
Thanks your reply，i solve it after i resert vscode😄
