### ISSUE TITLE
Include VSIX file in each GitHub Release

### ISSUE THREAD

**Issue by gsmachado** [microsoft/vscode-jupyter#5226]
As in most of `microsoft/vscode-*` GitHub repos, it is a good practice to include the respective .vsix file in it. For example, [microsoft/vscode-python](https://github.com/microsoft/vscode-python/releases) does exactly that. 

Why? Because it saves (tons of) time if someone wants to install an old version of the extension and test something. Also, due to backward compatibility with VSCode, installing an old version of the extension is desired sometimes.

This is something that maybe requires 2-3 hours of "doing time", and there's the potential of many people benefiting from it.

**Comment by DonJayamanne** [comment]
Thanks for filling this issue, however today you can already install older versions from within vscode, you can see the older versions of the extension list there.

**Comment by DonJayamanne** [comment]
See here https://stackoverflow.com/a/66134500

**Comment by gsmachado** [comment]
Hello @DonJayamanne 

Thanks for the answer.

However, I would like to install vscode-jupyter programmatically. I'm using the following URL to download the .vsix:

`https://ms-toolsai.gallery.vsassets.io/_apis/public/gallery/publisher/ms-toolsai/extension/jupyter/<VERSION>/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage`

Where `<VERSION>` is the version found in:

![image](https://user-images.githubusercontent.com/2124276/111924991-419e5880-8aa7-11eb-8a05-6a7ce96b419f.png)

However, I can't see the version https://github.com/microsoft/vscode-jupyter/releases/tag/2021.02 in the list at the marketplace.

My question to you, is: how can I find older versions of the extension uploaded to the marketplace? That I can use in the URL I specified above?

**Comment by DonJayamanne** [comment]
Hmm, good point, we should probably better line up the version numbers published asking with the tags. 

Right now the versions published in the market place are the real versions and the version numbers.

I will look into this.

**Comment by gsmachado** [comment]
Great, thanks!

In the meanwhile, it would be great if you could tell me what's the corresponding version to [2021.02](https://github.com/microsoft/vscode-jupyter/releases/tag/2021.02) in the marketplace -- because I can't figure it out. 😞 

This would save me the time to do a Dockerfile, compile/build [in this commit](https://github.com/microsoft/vscode-jupyter/tree/e7ce3f234849973b2fb5e6c482b9158b02b0a00a), and get the .vsix file on my own. 😅 😅 😅

**Comment by DonJayamanne** [comment]
It's this one 
2021.3.600686576 | 26/02/2021 | Download

**Comment by DonJayamanne** [comment]
Closing in favor of the following:
* Fixes already made https://github.com/microsoft/vscode-jupyter/pull/5231
* https://github.com/microsoft/vscode-jupyter/issues/5274
* https://github.com/microsoft/vscode-jupyter/issues/5238
