### ISSUE TITLE
Native Notebooks - Create New Blank Jupyter Notebook

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5227]
VS Code Version: 1.55.0 - insider and 1.54.3 
Jupyter Ext: v2021.3.619093157
Python Ext: v2021.3.658691958
OS: Windows 

**Important Note: The following is not happening on my personal Mac with the exact same configurations as above** 

Create new blank Jupyter notebook command no longer showing dropdown list of potential extensions to create notebook from. 

Previous Behavior: 
Create New Blank Jupyter Notebook -> Options: Jupyter, TypeScript, .NET Interactive

Current Behavior: 
Create New Blank Jupyter Notebook just creates a notebook (appears to be creating a notebook given the last notebook configurations)

**Comment by greazer** [comment]
Extensions need to be activated before they appear in this list. This is the crux of the problem and it's probably something we should install.

**Comment by DavidKutu** [comment]
Couldn't repro on 1.56.0-insider but can on 1.55.2
this should be fixed on the May release.
