### ISSUE TITLE
Shortcut to Data Viewer

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5229]
Today if users want to open up a dataframe in the data viewer they have to open the variable explorer first, then click the icon to open in data viewer. 

Would be great if a user could hover over the dataframe, right click and select "Open in Data Viewer"

**Comment by matangover** [comment]
The following requests seem related/duplicate, consider merging the upvotes: #1448, #8668

**Comment by DonJayamanne** [comment]
Thank you for this feature suggestion, however given the fact taht we have only receieved 5 upvotes over the past 2.5 years, and this isn't enough to warrant this new feature, hence closing this issue for now
