### ISSUE TITLE
Implement Checkpoints for Notebooks

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#5232]
We have had several requests for the need for saving checkpoints like Jupyter Classic and Lab does.

**Comment by xgdgsc** [comment]
This would be very useful before https://github.com/microsoft/vscode/issues/98063 is addressed.  A colleage of mine recently lost his work in jupyter notebook when disk is full.

**Comment by xgdgsc** [comment]
Is this fixed?
