### ISSUE TITLE
Syntax Highlighting for Julia in VS Code not working at all and broken in VS Code Insider

### ISSUE THREAD

**Issue by no-trick-pony** [microsoft/vscode-jupyter#5237]
I reported this issue first on Julia discourse here: https://discourse.julialang.org/t/running-julia-jupyter-notebooks-inside-vscode/47421/13?u=manuel_bergmann
I am copying this over here:

I am currently on the stable version 1.53.2 of VSCode with Julia 1.5.3 and I have the exact same issues with it as described previously in the thread: Code runs, but no syntax highlighting and also only old UI.
Installed versions:

- VSCode (stable) 1.53.2
- Julia (on the system): 1.5.3
- Julia VS extension: 1.1.32
- Jupyter VS extension: v2021.2.603412351
- Platform: Windows 10
- Running: Locally
- Python: 3.8.4

![image](https://user-images.githubusercontent.com/13365292/112044074-aa3e1180-8b49-11eb-9037-173a7b3b0486.png)

Again, with the current VS Code Insider version this works. Kinda. The syntax highlighting in many cases seems broken, especially string interpolations.

- VSCode (insider) 1.55.0
- Julia (on the system): 1.5.3
- Julia VS extension: 1.1.37
- Jupyter VS extension: v2021.4.641214696
- Platform: Windows 10
- Running: Locally
- Python: 3.8.4

![image](https://user-images.githubusercontent.com/13365292/112044193-cd68c100-8b49-11eb-98f1-e11ad35f792a.png)

Note the `2pi` marked red as well as the syntax highlighting for the string interpolation being broken.
All those things work in regular .jl files in VS Code however:

![image](https://user-images.githubusercontent.com/13365292/112044284-ecffe980-8b49-11eb-90db-f44f2ad68bde.png)

Out of interest I tried the string interpolation in nteract as well and here it was completely broken too (but in a different way):

![image](https://user-images.githubusercontent.com/13365292/112044308-f4bf8e00-8b49-11eb-836f-3ef3a8305fff.png)

Am I missing something?

**Comment by DavidKutu** [comment]
Thanks for the issue @no-trick-pony. We haven't specifically supported other kernels in the stable version of notebooks (although its possible to use it). That support is for the new native notebook you're using in insiders.

Unfortunately, I couldn't repro your issue with the same version of VS code insiders and the Jupyter extension:
![image](https://user-images.githubusercontent.com/20347396/112076876-7efef680-8b38-11eb-8055-6317a2376699.png)

As far as I know, that highlighting is expected. I do have a few questions for you:

- Does this happen in other languages?
- Could you test your Julia notebook with the Julia extension disabled?

Please let me know what happens.

**Comment by no-trick-pony** [comment]
Thanks a lot for your help - I found out what the issue was: For some reason, the syntax highlighting in Insiders defaulted to Python even though the Julia kernel was used and run for the whole notebook. I honestly didn't even know this is configurable. Is there a setting to change this permanently? Thanks a lot for your help! :)

Regarding the current VS Code version, I was able to find this: https://github.com/julia-vscode/julia-vscode/issues/1620#issue-683938901 which suggests the issue is known and has to be manually fixed. Since this answers all my questions/is dealing with issues already reported I close this ticket.

Thanks again for your help and your efforts! :)

**Comment by jlperla** [comment]
@rchiodo FYI

**Comment by no-trick-pony** [comment]
Adendum: I closed and saved the notebook after I set the syntax to Julia for every cell and after reopening it, every cell was set to Python again. This can be reproduced on my machine for this notebook and happens every time and I have to set "Julia" as the language on every single cell on its own.
I think I found the issue: A notebook created with current stable VS Code will integrate the following metadata, regardless of what kernel was used:

```
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": 3
  },
  "orig_nbformat": 2,
  "kernelspec": {
   "name": "julia-1.5",
   "display_name": "Julia 1.5.3",
   "language": "julia"
  }
 },
```

Opening this file in VS-Code Insiders with the Jupyter extension seems to interpret this. Saving it there does not seem to overwrite it, so regardless of what kernel or per-cell language setting you use, it will still display everything as Python the next time you open the notebook. (Sidenote: Selecting a kernel seems to have vanished into the menu and is not an overlay anymore, or I am just blind). The per-cell language highlighting does not seem to be persisted at all.
I am not really experienced with Jupyter notebooks besides using them here and there, so I can't give much input on this, other than you should probably take another look at it (if there is a "this notebook should be language X setting I haven't found it yet ^^"), otherwise opening "old" (or others') notebooks with the new VSCode/Jupyter might get painful for anything else then Python.
Thanks again for your help

**Comment by rchiodo** [comment]
> I closed and saved the notebook after I set the syntax to Julia for every cell and after reopening it, every cell was set to Python again

This is actually a known issue. This bug here: https://github.com/microsoft/vscode-jupyter/issues/5148

**Comment by rchiodo** [comment]
I'm going to enter a new issue for this part:

 A notebook created with current stable VS Code will integrate the following metadata, regardless of what kernel was used:

```
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": 3
  },
  "orig_nbformat": 2,
  "kernelspec": {
   "name": "julia-1.5",
   "display_name": "Julia 1.5.3",
   "language": "julia"
  }
 },
```
I want to make sure our insiders version is not doing the same thing.
