### ISSUE TITLE
无法加载 'qgrid' 控件的兼容版本，请考虑降级到 1.1.1 版本。 Error: Module qgrid, semver range ^1.1.3 is not registered as a widget module

### ISSUE THREAD

**Issue by LastSun** [microsoft/vscode-jupyter#5243]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by IanMatthewHuff** [comment]
@LastSun . For ipywidgets the source for them must be downloaded from an external CDN. The qgrid widget has not put newer versions of their source up on those CDNs so you usually need to downgrade to version 1.1.1 to actually use with vscode notebooks. That is what that error message is telling you. Downgrading to 1.1.1 version of qgrid should unblock you with this.

**Comment by LastSun** [comment]
> @LastSun . For ipywidgets the source for them must be downloaded from an external CDN. The qgrid widget has not put newer versions of their source up on those CDNs so you usually need to downgrade to version 1.1.1 to actually use with vscode notebooks. That is what that error message is telling you. Downgrading to 1.1.1 version of qgrid should unblock you with this.

Got it! Thanks~~~
And I still want to confirm with you that the version 1.1.1 you mentioned IS the version of Jupyterlab extention qgrid2, NOT the pip/conda package version. Is my understanding correct?

**Comment by IanMatthewHuff** [comment]
I believe that these two installation paths (Jupyterlab and pip/conda package version) lead to the same base extension code for qgrid getting installed:
https://github.com/quantopian/qgrid#installation

There should still be an entry in conda or pip list for just plain old qgrid in the environment that you are using. And if that version is 1.2, 1.3, 1.3.1 or anything greater then the source for it are not up on CDN and we can't us it via VS Code.

**Comment by LastSun** [comment]
> I believe that these two installation paths (Jupyterlab and pip/conda package version) lead to the same base extension code for qgrid getting installed:
> https://github.com/quantopian/qgrid#installation
> 
> There should still be an entry in conda or pip list for just plain old qgrid in the environment that you are using. And if that version is 1.2, 1.3, 1.3.1 or anything greater then the source for it are not up on CDN and we can't us it via VS Code.

Clear👌Thanks again
