### ISSUE TITLE
Metadata in stable branch is always 'python' related

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5246]
From customer feedback on #5237

Adendum: I closed and saved the notebook after I set the syntax to Julia for every cell and after reopening it, every cell was set to Python again. This can be reproduced on my machine for this notebook and happens every time and I have to set "Julia" as the language on every single cell on its own.
I think I found the issue: A notebook created with current stable VS Code will integrate the following metadata, regardless of what kernel was used:

```
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": 3
  },
  "orig_nbformat": 2,
  "kernelspec": {
   "name": "julia-1.5",
   "display_name": "Julia 1.5.3",
   "language": "julia"
  }
 },
```

Opening this file in VS-Code Insiders with the Jupyter extension seems to interpret this. Saving it there does not seem to overwrite it, so regardless of what kernel or per-cell language setting you use, it will still display everything as Python the next time you open the notebook. (Sidenote: Selecting a kernel seems to have vanished into the menu and is not an overlay anymore, or I am just blind). The per-cell language highlighting does not seem to be persisted at all.
I am not really experienced with Jupyter notebooks besides using them here and there, so I can't give much input on this, other than you should probably take another look at it (if there is a "this notebook should be language X setting I haven't found it yet ^^"), otherwise opening "old" (or others') notebooks with the new VSCode/Jupyter might get painful for anything else other than Python.
Thanks again for your help

_Originally posted by @no-trick-pony in https://github.com/microsoft/vscode-jupyter/issues/5237#issuecomment-804561372_

**Comment by rchiodo** [comment]
Want to make sure this isn't still happening with native notebooks.

**Comment by DonJayamanne** [comment]
I believe this has been resolved, if you select a Julia kernel, this should work.

**Comment by IanMatthewHuff** [comment]
Validated. We had another bug similar to this Julia kernel and cell language = 'Julia' now both save correctly in the ipynb.
