### ISSUE TITLE
Migrate IPyWidget tests to the way Ian wrote tests for WebView Variables (IPYWidget tests for Notebooks)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5250]
Get rid of puppeteer and other stuff.
Use a single way, and test real bits with real editor.

This will make the tests easier to maintain going forward.
Right now, the tests are flaky as well.

**Comment by joyceerhl** [comment]
Can we / do we want to be able to simulate interaction with the DOM? My understanding was that the puppeteer test infra lets us do that, but maybe that's not a problem.

**Comment by DonJayamanne** [comment]
We can send messages to the WebView, and let that interact with the DOM.

**Comment by DonJayamanne** [comment]
Closing this as done
