### ISSUE TITLE
Data viewer does not display non-numeric index column values in DataFrames

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5253]
_Originally posted by @mbijjur in https://github.com/microsoft/vscode-jupyter/issues/4886#issuecomment-799949059_

> Hi @mbijjur can you share a code sample and the version of the Jupyter extension that you have? Or is it the same version with either build of VS Code?

It is the same Jupyter extension version. You can try with any simple pandas df example.
column names does not appear when transposed.

![image](https://user-images.githubusercontent.com/31503873/111262164-c4f42000-8649-11eb-857d-b245c67a5b82.png)

**Comment by IanMatthewHuff** [comment]
Validated. Looks good now.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/34748f74-eab3-4096-bc4b-41faee3516e3)
