### ISSUE TITLE
Too much whitespace between text

### ISSUE THREAD

**Issue by Sti2nd** [microsoft/vscode-jupyter#5257]
## Environment data

-   VS Code version: 1.54.3
-   Jupyter Extension version: v2021.3.619093157
-   Python Extension version: v2021.3.658691958
-   OS and version: Windows 10, Build 19041
-   Python version: Python 3.9.1
-   Type of virtual environment: venv
-   Jupyter server running: Local

## Expected behaviour

I would expect the header text to be closer to the content it belongs to; the content below. This is how we are used to seeing it in Jupyter lab.

![image](https://user-images.githubusercontent.com/6373430/112213116-0c684680-8c1e-11eb-888a-503d963b915b.png)

Notice how the rendered header is closer to the paragraph text below than the cell above.

## Actual behaviour

And this is how the same notebook looks in VS Code:

![image](https://user-images.githubusercontent.com/6373430/112212815-ba272580-8c1d-11eb-9bd7-af49f21e393d.png)

In VS Code, the rendered text cells have an extra line above which contains the "Change to code" and "Delete cell" button when the cell is hovered on. This adds some extra whitespace.

The problem is that there is so much whitespace that the header is closer to the cell above than the content it belongs to below; the paragraph. This can be confusing. The same huge whitespace exists between all rendered text.

**Comment by IanMatthewHuff** [comment]
@Sti2nd Currently we are in the process of moving over to a new notebook UI provided by visual studio. Could you try downloading vs code insiders (it can install safely SxS with vscode stable) and opening the notebook there? This is the how the new UI will look and we won't be going back to fix issues like this with the old views.

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
