### ISSUE TITLE
BqPlot, K3d widgetes do not work in Native Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5258]
Broken in stable Notebooks as well,
this is a regression.
Works in WebView.

**Comment by IanMatthewHuff** [comment]
@DonJayamanne Like...as of today? I was up to date with main as of this morning and k3d is working with the bits that I have:
![image](https://user-images.githubusercontent.com/812783/112217499-ede35a80-8bdf-11eb-9ec9-0e6283621648.png)

**Comment by DonJayamanne** [comment]
Funny, it doesn't work for me in Insiders, but works in stable webview.
Let me check again

**Comment by DonJayamanne** [comment]
@IanMatthewHuff  Try this
## First Cell
```python
import k3d
import numpy as np
from numpy import sin,cos,pi
from ipywidgets import interact, interactive, fixed
import ipywidgets as widgets
import time
import math

plot = k3d.plot()

plot.camera_auto_fit = False

T = 1.618033988749895
r = 4.77
zmin,zmax = -r,r
xmin,xmax = -r,r
ymin,ymax = -r,r
Nx,Ny,Nz = 77,77,77

x = np.linspace(xmin,xmax,Nx)
y = np.linspace(ymin,ymax,Ny)
z = np.linspace(zmin,zmax,Nz)
x,y,z = np.meshgrid(x,y,z,indexing='ij')
p = 2 - (cos(x + T*y) + cos(x - T*y) + cos(y + T*z) + cos(y - T*z) + cos(z - T*x) + cos(z + T*x))
iso = k3d.marching_cubes(p.astype(np.float32),xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax, zmin=zmin, zmax=zmax, level=0.0)
plot += iso

plot.display()
```

## Second cell

```python
@interact(x=widgets.FloatSlider(value=0,min=-3,max=4,step=0.01))
def g(x):
    iso.level=x
    
@interact(rad=widgets.FloatSlider(value=0,min=0,max=2*math.pi,step=0.01))
def g(rad):
    plot.camera = [3*r*sin(rad),3*r*cos(rad),0,
                   0,0,0,
                   0,0,1]
```
This is what I use for testing K3d, a more

**Comment by DonJayamanne** [comment]
That definitely works in WebView notebooks & I know this used to work.

**Comment by IanMatthewHuff** [comment]
![image](https://user-images.githubusercontent.com/812783/112218382-deb0dc80-8be0-11eb-94cf-8f0ba7a0d065.png)

Widget sliders in cell 2 seem to move stuff around.

**Comment by DonJayamanne** [comment]
Ok, closing this issue, must be environmental.
Thanks a lot for confirmation.
