### ISSUE TITLE
The 'Trust' notification should not be shown as error but a warning

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-jupyter#5263]
When I open a notebook I get informed that a notebook can execute harmful code. This is good. However, this notification should not be shown as an error. Since the user hasn't done anything wrong and the system is running as expected, it is misleading to the user to show this notification as an error, therefore this notification should be shown as a warning. 

![image](https://user-images.githubusercontent.com/172399/112289862-f34bae00-8c8e-11eb-8351-740720659348.png)

**Comment by rchiodo** [comment]
This was actually done on purpose because warnings/notifications go away. We did not want this error to disappear because the notebook is unusable when untrusted.

**Comment by rchiodo** [comment]
See this other dupe that was closed for that reason:
https://github.com/microsoft/vscode-jupyter/issues/4614

**Comment by egamma** [comment]
@rchiodo thanks for the additional background. Since you mention:

>...because the notebook is unusable when untrusted.

Then wouldn't it be more appropriate to show this as a modal dialog to force a decision from the user? I mean:
```typescript
vscode.window.showWarningMessage(`Ask for Trust...`, { modal: true });
```

//CC @misolori would this be something to provide guidance in the UI guidelines?

**Comment by rchiodo** [comment]
Reopening for triage to consider.

**Comment by misolori** [comment]
I can update our guideline to cover this. It sounds like this is not using the appropriate category level since it wants to keep the notification visible for a warning toast (which is an anti-pattern).

**Comment by rchiodo** [comment]
I don't think we want it to be modal as that would prevent all other operations. We just want a permanent message to appear.

**Comment by misolori** [comment]
I also imagine that once [trusted workspaces](https://github.com/microsoft/vscode/issues/106488) moves to stable that this notification might go away?

**Comment by greazer** [comment]
Since we're moving to trusted workspaces in the near future, we'll wait for that.
