### ISSUE TITLE
Support variables pane for R (was: Code highlight for R kernel)

### ISSUE THREAD

**Issue by phisanti** [microsoft/vscode-jupyter#5264]
So I am currently using the latest version of Jupyter (`v2021.2.0`) on my laptop. I find it very cool that I can also use R kernels, even with IntelliSense! yet I might be missing something because I would like to see the variables that I have created and if possible code highlight. Here is a screenshot.
![image](https://user-images.githubusercontent.com/33370667/112333058-2ce1e080-8cb2-11eb-916c-93664d344354.png)

**Comment by rchiodo** [comment]
Thanks for the suggestion. 

We'd likely need help from the R community to get code highlighting and the variable explorer to work. 

The variable explorer uses a setting to determine how to query the R kernel for the value of a variable. Specifically this one:

```json
 [
                            {
                                "language": "python",
                                "query": "_rwho_ls = %who_ls\\nprint(_rwho_ls)",
                                "parseExpr": "'(\\w+)'"
                            },
                            {
                                "language": "julia",
                                "query": "whos",
                                "parseExpr": "'(\\w+)'"
                            }
                        ]
```

If you added a setting for R, you might be able to figure out how get the kernel to return variable information. On top of that the R kernel has to support the jupyter '[introspection](https://jupyter-client.readthedocs.io/en/stable/messaging.html#introspection)' message. 

Syntax highlighting is more about VS code supporting R as a default language. In the VS code insiders build, I believe R highlighting should already work.

**Comment by greazer** [comment]
Thanks for your feedback. The code colorization issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.

We're keeping this open to track the ability for R to display variables.

**Comment by morning-start** [comment]
R kernel supports the jupyter '[introspection](https://jupyter-client.readthedocs.io/en/stable/messaging.html#introspection)' message. [#710](https://github.com/IRkernel/IRkernel/issues/710)

But what I set could use the variableQueries.

```
    {
      "language": "R",
      "query": "as.list(.GlobalEnv)",
      "parseExpr": "'(\\w+)'"
    }
```

```
    {
      "language": "R",
      "query": "_rwho_ls = %who_ls\\nprint(_rwho_ls)",
      "parseExpr": "'(\\w+)'"
    }
```

all of these can't work

**Comment by greazer** [comment]
Iteration-candidate because it was on Discussions.

**Comment by DonJayamanne** [comment]
Its been a while and there haven't been enough upvotes on this issue, 
Hence closing this, if still required please feel free to ping here and we'll re-open this issue
