### ISSUE TITLE
Widget tests fails on CI

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#5265]
This test was added here, but was never run on CI (the entire suite was skipped at the time)
https://github.com/microsoft/vscode-jupyter/pull/4345/files

I tried to turn on the widget loading VS Code test with a recent proposed API change, but this one still failed on CI. Going to keep this one off for now to investigate later. Seems go to still have the other two turned on.

**Comment by DavidKutu** [comment]
From Don, these also fail:

1. DataScience IPyWidgets (With Direct Kernel)
Widget renders after closing and re-opening notebook:
Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)
at listOnTimeout (internal/timers.js:531:17)
at processTimers (internal/timers.js:475:7)

1. DataScience IPyWidgets (With Direct Kernel)
"after each" hook for "Render beakerx (plot)":
Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)
at listOnTimeout (internal/timers.js:531:17)
at processTimers (internal/timers.js:475:7)

**Comment by DonJayamanne** [comment]
Closing for now, as these are the old tests.
