### ISSUE TITLE
Saving plots to local filesystem results in NoPermissions error

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode-jupyter#5269]
When I generate an image in a Python session on a remote connection, I typically want to save these images locally. However, I am now getting a NoPermissions error when I do so:

```
Error exporting image: NoPermissions (FileSystemError): Unable to write file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a224e5959415753227d/Users/cfonnesbeck/Downloads/no_clusters.png' (NoPermissions (FileSystemError): Error: EACCES: permission denied, mkdir '/Users')
```

This is being saved in a subdirectory of my personal account, so there should be no permissions error. I have tried other subdirs, but with similar effect.

- VSCode Version: 1.54.3
- OS Version: macOS 11.3
- Jupyter Extension version: 2021.3.0 
-  Python Extension version: 2021.3.1
-  Python and/or Anaconda version: 3.8
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Jupyter server running: Remote

Steps to Reproduce:

1. Generate image in Python
2. Open image in plots tab
3. Select save icon
4. Select local filesystem from file browser
5. Save to local folder (e.g. Downloads or Desktop)

**Comment by rchiodo** [comment]
Thanks for the bug. Can you try turning this setting on, reproing the bug, and giving us the output of the 'Jupyter' tab?

```json
"jupyter.logging.level":"debug"
```

I think there's something wrong with the file save dialog (which would be a VS code issue) but the trace output should tell us where we failed when creating the file.

**Comment by tueda** [comment]
I was wondering if this issue may be related to what I'm experiencing...

I'm using the Jupyter extension with "Remote-SSH". I tried to save an image via "Plots" tab ("Export different formats" button) to the Desktop folder of the local Windows machine, and it seems that "Save plot image" silently failed, or at least I don't see any file. If I save the plot into a remote directory, it gives an empty PDF file. I don't see any error message in both cases, though `"jupyter.logging.level": "debug"` seems to be the default setting.

Environment:

- OS version: Windows 10.0.19042 (x64)
- VSCode version: 1.55.1
- Jupyter Extension version: v2021.5.745244803
- Python Extension version: v2021.3.680753044
- Remote Extension version: v0.65.1

and

- Remote OS version: CentOS 7 (x86_64)
- Remote Python version: 3.9.2

**Comment by rchiodo** [comment]
@tueda can you post the contents of your 'Jupyter' output tab?

![image](https://user-images.githubusercontent.com/19672699/114744553-aa719d00-9d02-11eb-9dfe-a10cc9495a2d.png)

**Comment by tueda** [comment]
@rchiodo Thank you, I found the "Jupyter" tab. The log is: https://gist.github.com/tueda/baa3c1c770d93ea8ee01aeb1bf3b974c, for which I created a new blank Jupyter notebook and ran
```python
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 1)
y = x ** 2

plt.plot(x, y);
```
and then tried to save the plot from "Plots" tab opened by "Expand image".

Excerpt for saving the plot into a local directory:
```
Info 2021-04-15 10:51:31: exporting plot...
Info 2021-04-15 10:51:37: Attempting pdf write...
Info 2021-04-15 10:51:38: Writing pdf to c:/Users/tueda/Desktop/20210415.pdf
Info 2021-04-15 10:51:38: Finishing pdf to c:/Users/tueda/Desktop/20210415.pdf
```
But I don't see `20210415.pdf` in the Desktop folder.

For saving the plot into a remote directory:
```
Info 2021-04-15 10:52:11: exporting plot...
Info 2021-04-15 10:52:21: Attempting pdf write...
Info 2021-04-15 10:52:21: Writing pdf to /home/tueda/tmp/20210415/test1.pdf
Info 2021-04-15 10:52:21: Finishing pdf to /home/tueda/tmp/20210415/test1.pdf
```
But `test1.pdf` in the remote directory is empty (zero size).

I'm not sure if the glib error in the log is relevant:
```
Error 2021-04-15 10:50:49: Exception while attempting zmq : [Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/tueda/.vscode-server/extensions/ms-toolsai.jupyter-2021.5.745244803/out/client/node_modules/zeromq/prebuilds/linux-x64/node.napi.glibc.node)
```

**Comment by rchiodo** [comment]
Hmm. We use this code here to write the PDF

```typescript
                        const SVGtoPDF = require('svg-to-pdfkit');
                        const deferred = createDeferred<void>();
                        // eslint-disable-next-line @typescript-eslint/no-require-imports
                        const pdfkit = require('pdfkit/js/pdfkit.standalone') as typeof import('pdfkit');
                        const doc = new pdfkit();
                        const ws = this.fs.createLocalWriteStream(file.fsPath);
                        traceInfo(`Writing pdf to ${file.fsPath}`);
                        ws.on('finish', () => deferred.resolve);
                        // See docs or demo from source https://cdn.statically.io/gh/alafr/SVG-to-PDFKit/master/examples/demo.htm
                        // How to resize to fit (fit within the height & width of page).
                        SVGtoPDF(doc, payload.svg, 0, 0, { preserveAspectRatio: 'xMinYMin meet' });
                        doc.pipe(ws);
                        doc.end();
                        traceInfo(`Finishing pdf to ${file.fsPath}`);
                        await deferred.promise;
                        traceInfo(`Completed pdf to ${file.fsPath}`);
```
The last promise is never finishing. Something in the npm module ```pdfkit``` is failing.  I believe we might be hitting this issue here: 
https://github.com/foliojs/pdfkit/issues/1138

We might need to implement the workaround explained in that issue.

**Comment by DonJayamanne** [comment]
@fonnesbeck 
Are you still running into this issue?

**Comment by fonnesbeck** [comment]
Not recently! Go ahead and close the issue, thanks.

**Comment by DonJayamanne** [comment]
Thank you very much for getting back.
