### ISSUE TITLE
Notebook won't render

### ISSUE THREAD

**Issue by Bebotron** [microsoft/vscode-jupyter#5281]
## Environment data

-   VS Code version: 1.54.3
-   Jupyter Extension version (available under the Extensions sidebar): 2021.3.619093157
-   Python Extension version (available under the Extensions sidebar): 2021.3.680753044
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 18.04.5 LTS
-   Python and/or Anaconda version: Python 3.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A: Local

## Expected behaviour

I expect to see the notebook the way it's supposed to be. (Example from google images)
![image](https://user-images.githubusercontent.com/24438203/112396275-b09ccc80-8cb4-11eb-90aa-d3090dfdc8bd.png)

## Actual behaviour

The notebook does not render, it just shows the raw code
![ipynbraw](https://user-images.githubusercontent.com/24438203/112395221-d628d680-8cb2-11eb-88b5-709648c4ea8c.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Simply opening a `.ipynb` file

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

No output

<p>

</p>
</details>

**Comment by DonJayamanne** [comment]
I'm sorry you're running into this issue.
* Please could you install the latest version of Jupyter extension (released earlier today)
* Enable logging as follows:
	* Open settings & go into `Jupyter->Logging`
	* Change the value to `debug`
	* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

Thanks

**Comment by Bebotron** [comment]
I uninstalled and reinstalled python, so it's hopefully now the most updated version. I still get the problem, here is a screenshot including the output
![image](https://user-images.githubusercontent.com/24438203/112405123-87853780-8cc6-11eb-9127-ba3172b00186.png)

Here is the output in case it's easier this way
```
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'pythonDiscoveryModulecf'
Info 2021-03-24 17:26:02: ZMQ install verified.
Info 2021-03-24 17:26:02: id is ea69b027-b01f-4233-a3a6-a109c4ef0119
Error 2021-03-24 17:26:02: Error setting up custom editors:  Error: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.
    at w.reject (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2013:16717)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2013:20787
    at async w.doWriteConfiguration (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2013:13896)
Info 2021-03-24 17:26:02: Found existing keyfile at /home/bebotron/.config/Code/User/globalStorage/ms-toolsai.jupyter/nbsecret
Info 2021-03-24 17:26:04: Process Execution: > /usr/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py pip list
> /usr/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py pip list
Info 2021-03-24 17:26:04: Process Execution: > /usr/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py pip list
> /usr/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py pip list
Info 2021-03-24 17:26:04: Process Execution: > /usr/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import pip"
> /usr/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import pip"
Info 2021-03-24 17:26:04: Process Execution: > /usr/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import pip"
> /usr/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import pip"
Info 2021-03-24 17:26:04: Process Execution: > ~/anaconda3/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> ~/anaconda3/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
Info 2021-03-24 17:26:04: Process Execution: > ~/anaconda3/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> ~/anaconda3/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
Info 2021-03-24 17:26:04: Process Execution: > ~/anaconda3/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> ~/anaconda3/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version

```

**Comment by OHHH-YEHH** [comment]
@Bebotron Have you installed the Jupyter package in the Python environment ( 3.8.7 64 bit )? 
If no,  install with `pip install jupyter`.
Or select the interpreter by clicking on the left bottom corner ( Python 3.8.7 64 bit ) and choose the environment for which the Jupyter package is available. If anaconda distribution is available, choose that python interpreter.

**Comment by Bebotron** [comment]
@OHHH-YEHH Ok this must be where the problem is coming from. I have jupyter installed with Anaconda3 using Python 3.8.3 (I don't recall ever installing Python 3.8.7, maybe it was done with an update?). I switched the interpreter to `~/anaconda3/bin/python/` where I know I have jupyter in, but it still won't render.

**Comment by DonJayamanne** [comment]
@Bebotron, @OHHH-YEHH
I'm sorry you've come across this issue.
Please could you open your user `settings.json` file.
Look for an entry for the setting `workbench.editorAssociations`, please let me know what it is.

Next, please update as follows:
```json
	"workbench.editorAssociations": [
		{
			"viewType": "jupyter.notebook.ipynb",
			"filenamePattern": "*.ipynb"
		}
	],
```

This should get you unblocked.

**Comment by Bebotron** [comment]
@DonJayamanne Great that seems to have fixed it, thanks so much! Closing now.

**Comment by DonJayamanne** [comment]
> please let me know what it is.

Do you know what was in there?

**Comment by Bebotron** [comment]
Oh sorry I missed that, it was empty in the default .json
