### ISSUE TITLE
Opening a notebook in a codespace

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#5283]
1) open a `ipynb` file in a codespace
->
![image](https://user-images.githubusercontent.com/4674940/112401557-09c22b80-8cc8-11eb-9668-53263b1f1029.png)

Issues:
1) ~python extension activation shows the welcome page stealing the focus from the notebook that I opened~ //cc @brettcannon 
2) ~I get immediately asked for a survey~
3) the kernel port gets forwarded (this is a missing API adoption, @alexr00 has the details)

**Comment by DonJayamanne** [comment]
@alexr00, some of the ports opened here don't need to be forwarded, please let us know how we can hide such ports. Thanks

**Comment by DonJayamanne** [comment]
The popup should not appear the first time in code space, this should only appear if user opens 5 notebooks or executes 100 times/cells (in total).

**TODO**: Test & confirm this popup, we've got a few similar issues (possible its not working as expected)

**Comment by kieferrm** [comment]
This is the link for the port forwarding issue: https://github.com/microsoft/vscode-remote-release/issues/4727

**Comment by DonJayamanne** [comment]
I'll get this into our next request (tomorrow)
https://github.com/microsoft/vscode/issues/115616

**Comment by alexr00** [comment]
@DonJayamanne please do comment in https://github.com/microsoft/vscode/issues/115616 if you have any questions or feedback on the API! I was going to wait another week for the API to become a bit more stable before asking if microsoft/vscode-jupyter to try it out, so please be aware that it may change **without warning**. If you make a PR for adopting the API, I'd love to be @ mentioned or included on the review so I can understand how extensions use the API!

**Comment by DonJayamanne** [comment]
@alexr00 I'm assuming I'd need to use `PortAutoForwardAction.ignore` to ensure these ports are not forwarded, please could you confirm this? Thanks

**Comment by DonJayamanne** [comment]
As this is CodeSpaces with Insiders, I'm not going to rush this for the Release,

**Comment by alexr00** [comment]
@DonJayamanne Yes, for ports that the extension knows about and are internal to the working of the extension, use `PortAutoForwardAction.ignore`. For ports that the extension doesn't know about, simple exclude them from your returned array of attributes. If there are any ports that the extension knows about but are external to the working of the extension, i.e. user facing, you can return `PortAutoForwardAction.notify` if you want to make sure that the user is notified, or you can simply leave them out of your returned array and let the user's settings handle whether they get notified.

**Comment by greazer** [comment]
The port notification we should suppress. However, the survey notification shouldn't show at all. No survey notifications should show on codespace.

**Comment by alexr00** [comment]
@DonJayamanne I see that you have adopted the port attribute API 👏 Do you have any feedback on the API? Was it easy to understand how to use it?

**Comment by IanMatthewHuff** [comment]
Validated. 
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/b58b628d-96d4-435f-b3e5-8c04c6aeda48)
