### ISSUE TITLE
Unformatted text in jupyter.variableQueries setting 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#5289]
Issue Type: <b>Bug</b>

**Repro**
1. Open settings
1. Search `jupyter.variableQueries`

**Bug**
<img width="336" alt="Screen Shot 2021-03-24 at 6 19 52 PM" src="https://user-images.githubusercontent.com/12821956/112404502-b652dc00-8ccd-11eb-815c-fdf010ae339b.png">

Extension version: 2021.4.678042391
VS Code version: Code - Insiders 1.55.0-insider (8437d38d364ba93b53c1e659c20b1c86f710ec28, 2021-03-24T08:10:36.007Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.63GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IanMatthewHuff** [comment]
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/227dedd6-5fee-4ce0-b66d-82f867a9bf04)
Validated.
