### ISSUE TITLE
Synapse: Default kernel name is not provide and preventing synapse from working

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5290]
The kernelconnection we pass on remote should not default to an empty name. This can prevent the server from starting a kernel as not all server realize an empty name is the default kernel.

**Comment by rchiodo** [comment]
We should be able to enumerate the remote kernel specs to get the 'default' one.

**Comment by IanMatthewHuff** [comment]
@joyceerhl Any particular validation here? If it worked for synapse I'm fine to just validate on that, and I can see the code change.

**Comment by IanMatthewHuff** [comment]
Validated. Just reopen if there is still an issue.
