### ISSUE TITLE
Prompted to fill out survey when opening notebooks first time in CodeSpaces

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5295]
Originally reported here https://github.com/microsoft/vscode-jupyter/issues/5283

1) open a `ipynb` file in a codespace
->
![image](https://user-images.githubusercontent.com/4674940/112401557-09c22b80-8cc8-11eb-9668-53263b1f1029.png)

Issues:
2) I get immediately asked for a survey

**Comment by joyceerhl** [comment]
Validated. Opened a notebook a bunch of times in a new GitHub Codespace and verified the survey prompt never showed up.
