### ISSUE TITLE
Clearer UI indicators for native notebooks cell edit mode

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5306]
Was just in a QP where a customer who is accustomed to Jupyter notebooks keyboard shortcuts was trying to use the `b` keyboard shortcut to insert a cell below the current cell and didn't realize that he had the cell in edit mode. Once he pressed the esc key to select the cell, the `b` shortcut worked, but I needed to point it out for him to notice the difference.

**Comment by greazer** [comment]
This has bee tweaked quite a bit already.
