### ISSUE TITLE
Support != filter expression in data viewer columns

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5313]
Had a customer ask for this in a QP

**Comment by greazer** [comment]
Is it possibly <>?

**Comment by joyceerhl** [comment]
Customer was trying to do != fwiw 🤷‍♀️

**Comment by greazer** [comment]
Doesn't look like this is supported right now.

**Comment by greazer** [comment]
!= should be supported (at least for Python)

**Comment by DonJayamanne** [comment]
Closing this issue as there haven't been any upvotes on this feature request
