### ISSUE TITLE
Notebook Variable Viewer not displaying

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5316]
* Create notebook
* Run cell `a = 1`
* Open variable viewer & you can see `a`
* Run cell `a = 2`
* Run cell `a = 3`
* Open variable viewer & you can still see only `a`

Close variable viewer & open again, doesn't work, tab to terminal/output & back to variables, still not working.

**Comment by joyceerhl** [comment]
I see this too.

**Comment by IanMatthewHuff** [comment]
Yeah, looks like the API change to detect when cells have executed might be the culprit. Seems to happen along with the bug where the file thinks that it's still running after running and finishing a cell.

**Comment by joyceerhl** [comment]
Validated. Variable viewer updates after each cell execution completes.
