### ISSUE TITLE
Kernels with invalid Python executables get displayed & auto selected by kernel picker

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5318]
A specific environment on my machine cannot install ipykernel.

Log looks like this:

```
Info 2021-03-25 14:32:35: Process Execution: > d:\Source\Testing_3\newEnv5\Scripts\python.exe c:\Users\aku91\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.4.687458533\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> d:\Source\Testing_3\newEnv5\Scripts\python.exe c:\Users\aku91\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.4.687458533\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
Error 2021-03-25 14:32:36: Install Missing Dependencies, Class name = v, completed in 1612ms, has a falsy return value, Return Value: undefined [a [Error]: IPyKernel not installed into interpreter Python 3.8.5  ('newEnv5': venv):d:\Source\Testing_3\newEnv5\Scripts\python.exe
	at v.installMissingDependencies (c:\Users\aku91\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.4.687458533\out\client\extension.js:49:560241)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)] {
  category: 'noipykernel',
  reason: 2
}
```

Looks like it's not even asking.

**Comment by DonJayamanne** [comment]
1. What do you get when you run the following in the terminal?


```d:\Source\Testing_3\newEnv5\Scripts\python.exe c:\Users\aku91\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.4.687458533\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"```

1. What do you get when you run the following in the terminal (without isolated stuff)?


```d:\Source\Testing_3\newEnv5\Scripts\python.exe -c "import ipykernel"```

2. Can you enable logging of Python extension to see what was logged there?

This could explain why users run into issues with IPyKernel.
Someone is running into this exact same issue in core extension as well, see here https://github.com/microsoft/vscode-python/issues/10743#issuecomment-808269445

**Comment by DonJayamanne** [comment]
Adding high priority (desire to get this fixed in next release), and will leave in new issues to triage.

**Comment by rchiodo** [comment]
This is the environment that is pointing to a non existent python. If I activate this environment and run python, it shows that python doesn't even exist:

```
D:\Source\Testing_3>newenv5\Scripts\activate

(newEnv5) D:\Source\Testing_3>python
No Python at 'C:\Users\Rich\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe'

(newEnv5) D:\Source\Testing_3>
```

**Comment by rchiodo** [comment]
The python.exe is a symlink

**Comment by DonJayamanne** [comment]
Oh ok, python doesn't exist, ok got it.

**Comment by DonJayamanne** [comment]
> The python.exe is a some sort of redirecting exe. It's not even a symlink.

## Suggestions
* When get get list of interpreters from Python, we can check if the information is cached or not
* If cached, we get call getInterpreterDetails to get the details, if we get a response we know its valid
*
