### ISSUE TITLE
Support pasting of images from clipboard in markdown cells of Notebooks

### ISSUE THREAD

**Issue by rndxx** [microsoft/vscode-jupyter#5321]
**when i want to insert local image into a cell nothing happens :(**

Extension version: 2021.5.685944597
VS Code version: Code - Insiders 1.55.0-insider (6ebe2a14f3722bc2582ecd8108d0a71dfdd46036, 2021-03-25T16:25:06.257Z)
OS version: Windows_NT x64 10.0.19042

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, please could you provide some steps on what you have tried and what you mean by inserting local image? I.e. steps for us to be able to repro this issue.

**Comment by randomuserrr** [comment]
I took a screenshot and want to insert an image via ctrl + v.  this works in jypiter notebook but doesn't work in vscode

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode/issues/123021

**Comment by TheGeeKing** [comment]
For anyone searching a solution:

- a small extension: https://marketplace.visualstudio.com/items?itemName=mushan.vscode-paste-image
- a more advanced extension: https://marketplace.visualstudio.com/items?itemName=telesoho.vscode-markdown-paste-image

They can both save images locally and include them in Markdown with `Ctrl + Alt + V`.

**Comment by rebornix** [comment]
This is a good feature request for the markdown features in VS Code: Paste -> Upload/Paste image file and then insert link in markdown.

**Comment by rebornix** [comment]
> in jupyter images area not uploaded, its encoded and stored in the notebook metadata.
i would expect something similar in vscode, to be consistent

we at least need to support it when the document already has images embedded. Though it's arguable if we want to support dragging images into the document and embed into the document as it might make the document really large.

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode/issues/121256
