### ISSUE TITLE
Calls to `getInterpreterDetails` might not be getting cached just like `getActiveInterpreter`

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5331]
* Double check with Core team if this gets cached, if not this would be another bottle neck in our code
* If not cached, we can cache this just as we cache the `getActiveInterpreter` in `pythonApi.ts`

**Comment by DavidKutu** [comment]
It is cached here:
https://github.com/microsoft/vscode-python/blob/54fb57655a1b1076cb2968b904535b8231c13d3a/src/client/interpreter/interpreterService.ts#L228

**Comment by DonJayamanne** [comment]
Closing this issue as its has been validated in code (Python extension).
