### ISSUE TITLE
Improved Python syntax highlighting in Markdown cells

### ISSUE THREAD

**Issue by jsdodge** [microsoft/vscode-jupyter#5339]
A Jupyter notebook with the following Markdown cell shows Python syntax highlighting with a notebook server but not in VS Code. Is it possible to change this?

    # Test syntax highlighting
    
    ```python
    a = 1
    def addone(x):
        return x + 1
    mylist = [1, 'a', 2.718, True, addone(a)]
    ```

VS Code:
<img width="371" alt="Screen Shot 2021-03-26 at 12 38 39 PM" src="https://user-images.githubusercontent.com/4602669/112684388-35602580-8e30-11eb-96c6-87f7605ecd2c.png">

Jupyter notebook server:
<img width="404" alt="Screen Shot 2021-03-26 at 12 39 40 PM" src="https://user-images.githubusercontent.com/4602669/112684509-62143d00-8e30-11eb-8e57-f96d5467bfea.png">

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, currently we support this with Native Notebooks (See here for more information https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/).

To try to new notebook Editor, please install VS Code Insiders, we're working on getting that to be the default editor for ipynb files.

Here's what it looks like 
![Screen Shot 2021-03-26 at 14 34 37](https://user-images.githubusercontent.com/1948812/112695008-95f75e80-8e40-11eb-9b48-103d88a32082.png)
