### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by palak53** [microsoft/vscode-jupyter#5343]
- Issue Type: `Performance`
- Extension Name: `jupyter`
- Extension Version: `2021.3.684299474`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.54.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\palme\AppData\Local\Temp\ms-toolsai.jupyter-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by joyceerhl** [comment]
Hi @palak53, please upload the requested file located at this filepath so we can take a look, thanks!  c:\Users\palme\AppData\Local\Temp\ms-toolsai.jupyter-unresponsive.cpuprofile.txt
