### ISSUE TITLE
data viewer python interactive index not showing correctly

### ISSUE THREAD

**Issue by nemar3** [microsoft/vscode-jupyter#5348]
## Environment data

Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

-   Jupyter Extension version (available under the Extensions sidebar): 
    2021.3.684299474

-   Python Extension version (available under the Extensions sidebar):  2021.3.680753044
-   OS (Windows | Mac | Linux distro) and version: windows 10
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

when displaying a pandas dataframe in the data viewer the index of the dataframe is displayed

## Actual behaviour

the index is not displayed instead a row count is shown

![image](https://user-images.githubusercontent.com/65395704/112889943-93ae3200-90d6-11eb-8ee7-bb6a1dcd340d.png)

## Steps to reproduce:

df=pd.DataFrame([1,2,3,4])
df.index=["a,b,c,d".split(",")]

the expected behaviour is to have the index of "a","b","c","d" shown in data viewer instead of 0,1,2,3

**Comment by joyceerhl** [comment]
Thanks for the bug. This doesn't seem to ever have worked correctly in our data viewer, e.g. v2020.11.399280825: 
![image](https://user-images.githubusercontent.com/30305945/112896996-ee726a00-9093-11eb-8fa7-d2c92a315948.png)

And I repro the bug with our latest main bits too.
