### ISSUE TITLE
Text on plots are not visible

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5353]
![Screen Shot 2021-03-29 at 15 57 17](https://user-images.githubusercontent.com/1948812/112910132-99405380-90a7-11eb-9c9c-962b20253ff0.png)

**Comment by IanMatthewHuff** [comment]
Validated. Looks good now.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/166870da-bd3f-4a85-b97d-9dd2a34e0ae1)
