### ISSUE TITLE
Variable Explorer - Update Icon

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5355]
Update Variable Explorer icon to "variable-group" 

![image](https://user-images.githubusercontent.com/19276747/112914380-b2013700-90b0-11eb-81ac-160a668be954.png)

**Comment by greazer** [comment]
We should make the interactive window match.

**Comment by IanMatthewHuff** [comment]
Validated. New icon is visible in all locations. Plus you were totally right that we can use codicons in the old webviews, not sure why I was thinking that we couldn't.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/a8465866-e51d-4be8-a871-dccdf76e8341)
