### ISSUE TITLE
Cannot scroll automatically when reaches "maxOutputSize" in output

### ISSUE THREAD

**Issue by XinyueZ** [microsoft/vscode-jupyter#5358]
I am not sure whether this has been reported or not.

My experience is that the output cell cannot be scrolled ahead when the `maxOutputSize` has been reached. I must scroll manually and keep scrolling like this.

Or I miss options which I shall set to let it do automatically, don't I?

**Comment by IanMatthewHuff** [comment]
@XinyueZ thanks for reporting this. A couple of quick questions here. 

1. Could you please give us the info regarding the version of VS Code that you are on and the version of the Jupyter extension that you are using?
2. What are your settings for Jupyter->Always Scroll On New Cell and Jupyter->Enable Scrolling For Cell Outputs? Those settings might change output scrolling.
