### ISSUE TITLE
ERR command '{1}' not found when clicking on error message info

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-jupyter#5360]
## Environment data

-   VS Code version: Insiders

```
Version: 1.55.0-insider (user setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T12:48:52.547Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041
```
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX

![image](https://user-images.githubusercontent.com/1487073/113046333-cd258280-9154-11eb-902c-6289157ff186.png)

-   OS (Windows | Mac | Linux distro) and version: Windows with WSL (Ubuntu 20.04)
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

Trying to run a Python/Jupyter notebook cell and the kernel failed to start (issue https://github.com/microsoft/vscode-jupyter/issues/5361).  Got this message and clicked on `log` and nothign happens. 

![image](https://user-images.githubusercontent.com/1487073/113046094-7a4bcb00-9154-11eb-9168-a9a2fd2a32b4.png)

from the dev tools console:

![image](https://user-images.githubusercontent.com/1487073/113046183-994a5d00-9154-11eb-9c79-bd3e35170c13.png)

**Comment by IanMatthewHuff** [comment]
Thanks for the report. I'm not sure on the kernel timeout from #5361 yet, but I believe that I can see the code issue here already. We'll get it fixed.

**Comment by joyceerhl** [comment]
Validated. Message appears as follows, and clicking the hyperlink sets focus to the Jupyter output panel: 

![image](https://user-images.githubusercontent.com/30305945/113643394-17b46c80-9637-11eb-87f9-e07677569f34.png)
