### ISSUE TITLE
Install ipykernel is coming up during auto start. It shouldn't.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5368]
Turn off native notebook
Create notebook with kernel that requires ipykernel to be installed
Reload VS code
Open notebook
As you open the notebook the 'You need to install ipykernel' comes up.

**Comment by joyceerhl** [comment]
Validated. In custom editor when I first open a notebook connected to a kernel that does not have ipykernel installed, I don't get prompted to install ipykernel. I only get prompted when I run a cell. (Tested with new blank notebook and with opening an existing notebook.)

One thing that is sort of odd is that the kernel status is reported as Busy, and the kernel name isn't displayed.

![image](https://user-images.githubusercontent.com/30305945/114088747-3189c580-986a-11eb-973c-50207ceccd3b.png)
