### ISSUE TITLE
Cell separator `# %%` with comments after indentation does not render cell

### ISSUE THREAD

**Issue by EdwardCuiPeacock** [microsoft/vscode-jupyter#5370]
## Environment data

-   VS Code version: 1.54.3
-   Extension version (available under the Extensions sidebar): v2021.3.680753044
-   OS and version: MacOS 10.14.6
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.5 with Anaconda
-   Value of the `python.languageServer` setting: PyLance

## Expected behaviour

Using `# %%` to create cells under a function should also render the cell when it is followed by additional comments.

## Actual behaviour

When adding additional comments followed by the cell separator, the cell is not rendered.

## Steps to reproduce

```python
# Cell separator

# %%

# %% Has cell

def test_func():
    # %% 
    print("This has cell")

    # %% This has no cell
    print("This has no cell")
```

Screen shot below:
<img width="882" alt="Screen Shot 2021-03-31 at 3 05 55 PM" src="https://user-images.githubusercontent.com/80276234/113198674-329c7080-9234-11eb-91e9-a6cd64fbe9fb.png">

**Comment by rchiodo** [comment]
Thanks for the bug. Yes it seems comments on cell delimiters is not supported inside of functions.

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time.
