### ISSUE TITLE
Data viewer title should be less verbose and include variable shape if any

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5374]
Feedback from Jill: 'Data Viewer' is included in every data viewer's title, which takes up a lot of space. See if we can shorten the title and include more info like the shape of the variable. Also see if we can associate an icon with the viewType so the tab doesn't just show the default text editor seti icon.

**Comment by DonJayamanne** [comment]
Closing this issue as there haven't been enough upvotes on this feature request since it was created
