### ISSUE TITLE
How can we identify and track reasons for known Kernel issues caused by Python extension

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5376]
https://github.com/microsoft/vscode-python/issues/15823
How can we track such issues,
I.e. look at all failures and determine how many users fall into this category?
Just look for users who are using Conda Kernels & install fails?

Goal - avoid unnecessary triaging/debugging at our end when such kernel issues are caused by Python extension.

**Comment by rchiodo** [comment]
We could have a notebook in our repo that tracks these things. The notebook might have
- Kusto queries to show the issue
- Code to show the issue (if we wanted customers to use it)

**Comment by DonJayamanne** [comment]
> Code to show the issue (if we wanted customers to use it)

Not following you here. Please could you elaborate.

**Comment by rchiodo** [comment]
> Code to show the issue (if we wanted customers to use it)

Suppose the error is pyzmq constants one. How do you show the exact issue to a user? You try starting ipykernel. So the notebook might have a cell that launches a kernel.

Then the next cells after that might be markdown saying something like:

```
If you see zmq.constants not found, run this cell below
```

Where the cell below would then have the pip install pyzmq stuff in it.


The general idea is a notebook with a workflow that can let a user self diagnose their issue.

**Comment by DonJayamanne** [comment]
Oh sorry, my issue was not how we address/fix issues.
We know now that there are issues in core extension related to environment discovery & the like.
When users report issues and we try to determine how many users are running inot kernel issues, how do we tie some of those issues back to Python extension issues.

I.e. how do we prevent ourselves from barking up the wrong tree, when the issue is completely caused by core extesnion?

Agian, I'm not looking for solutions to get users unblocked, but would like to ensure we have a way to map core extension issues to kernel issues, this way we don't end up spending hours/days on trying to find a solution when the bug is solely caused by Python extesnion.
