### ISSUE TITLE
Text is not copy from output pandas dataframe

### ISSUE THREAD

**Issue by randomQQQ** [microsoft/vscode-jupyter#5384]
## Environment data

-   VS Code version: insiders 1.56
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.702919634
-   Python Extension version (available under the Extensions sidebar): v2021.4.690665134-dev
-   OS (Windows | Mac | Linux distro) and version: Windows 10

Text is not copy from output pandas dataframe

**Comment by joyceerhl** [comment]
Likely related: https://github.com/microsoft/vscode/issues/120370

**Comment by DonJayamanne** [comment]
Dup of https://github.com/microsoft/vscode/issues/115278

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode/issues/121115
