### ISSUE TITLE
Unwanted context menu options from invasive jupyter extension that I did not install

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/vscode-jupyter#5387]
## Environment data

-   VS Code version: 
-   Jupyter Extension version (available under the Extensions sidebar): 
-   Python Extension version (available under the Extensions sidebar): 
-   OS (Windows | Mac | Linux distro) and version: 
-   Python and/or Anaconda version: 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

I did not install the jupyter extension. I have never wanted to have "jupyter" support in my editor. This crap comes bundled with the Python extension. 

When I right click in a python file, I see the following options in my context menu: 

![image](https://user-images.githubusercontent.com/2473545/113361745-01e73480-9323-11eb-9a6c-448ba420f9b0.png)

I do not want these options. In fact, I have never asked to have "jupyter" installed. 

## Actual behaviour

The python extension comes bundled with malware, that introduces unwanted commands in my context menu, and other places. 

## Steps to reproduce:

1. Install the python extension
2. DO NOT install the jupyter extension, it will be installed anyway without user consent. 
3. Open a python file.
4. Right click inside the editor

**Comment by claudiaregio** [comment]
Hi @phgmacedo, the Jupyter extension powers the interactive window experience and the Data Viewer for the Python extension which are both very useful features for those using Python, even if they aren't using notebooks. The code for the Jupyter extension used to reside within the Python extension. It was extracted to provide support for other languages, so the only change for Python users is they see the separation as an extra extension in their extension list. Nothing "extra" was actually installed. 

While we may see fit to separate them in the future, this is not in our immediate roadmap at this time. 

For more details please read the FAQ: https://github.com/microsoft/vscode-jupyter/wiki/FAQ---(Frequently-Asked-Questions)

**Comment by phgmacedo** [comment]
@claudiaregio I'll repeat the same thing I replied when @brettcannon closed my issue in the python extension repo: 

Your reply does not address my issue. Was it closed out of spite because you didn't like the issue title, or is there a technical limitation that prevents the issue from being addressed, or is it that the context menu thing behaves as intended?

Can there even be a discussion about the design of the extension features?

**Comment by claudiaregio** [comment]
Issues here are not closed based on tone or title, they are closed based on whether it is a work item the team will address soon or would like to keep open to see if others will upvote it. While the team has already registered this feedback from a small number of people, it is not something we will address at this time. As mentioned above, it may happen in the future. The team has had thorough discussions regarding this as I'm sure you can imagine. 

Some additional information that might help make this more clear -- Before the split, those context menu items were there. After the split, those context menu items are now _technically_ contributed by Jupyter extension. Either way, the context menu items would have been there. It is a feature that we offer to all our Python users.

**Comment by phgmacedo** [comment]
> or would like to keep open to see if others will upvote it

So it is implied that `the team` would not like to see if others will upvote this issue? 

> While the team has already registered this feedback from a small number of people

Is this issue a dupe then?

> Before the split, those context menu items were there. After the split, those context menu items are now technically contributed by Jupyter extension. Either way, the context menu items would have been there. It is a feature that we offer to all our Python users.

So, if people didn't complain then, that means they can't complain now?

**Comment by claudiaregio** [comment]
It is not that the team does not want to see the issue upvoted, it's that we have already registered this feedback and it has been considered. It is not something we can address at this very moment in time, therefore closed.

**Comment by phgmacedo** [comment]
@claudiaregio 
> It is not something we can address at this very moment in time, therefore closed

Is there a specific technical limitation? Has any issue been opened in the vscode repo?

**Comment by claudiaregio** [comment]
It is not necessarily a technical limitation, but we are in the process of making other major code changes and migrations and steps must be taken in a coherent manner. There are also other logistical things that must be completed first in order for decoupling to take place. Evolution takes time :)

**Comment by phgmacedo** [comment]
I am not complaining about the `decoupling`. I'm specifically talking about the context menu entries. 

Judging by the Jupiter extension (at this moment) 2.5  stars rating, and the comments, you already have plenty of feedback about the decoupling, which is not the subject of this issue.

**Comment by claudiaregio** [comment]
As mentioned above, the interactive window is an experience we offer all our Python users. Just like any other VS Code menu item, users do not have to use or click on any options/features made available to them if they do not wish to use them.
