### ISSUE TITLE
Notebook running julia kernel doesn't render new cells

### ISSUE THREAD

**Issue by Bebotron** [microsoft/vscode-jupyter#5396]
## Environment data

-   VS Code version: 1.54.3
-   Jupyter Extension version (available under the Extensions sidebar): v2021.3.684299474
-   Python Extension version (available under the Extensions sidebar): v2021.3.680753044
-   Julia Extension version: v1.1.38
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 18.04.5 LTS
-   Python and/or Anaconda version: 3.8.3 (Julia 1.5.1)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A: Local

## Expected behaviour

When running the bottom-most cell in a notebook running a python kernel, a new cell is created. I can also create a new cell by pressing "b", like in the gif below
![cells_in_python](https://user-images.githubusercontent.com/24438203/113459323-9b652380-93c1-11eb-8f86-e85a54aa9f2a.gif)

## Actual behaviour

When running a julia kernel, running the bottom-most cell and pressing "b" give me an error and I can't see the new cells created. Note that the cell ran properly, I just can't create new ones.
![cells_in_julia](https://user-images.githubusercontent.com/24438203/113459534-4fff4500-93c2-11eb-9eec-0cbdbfc0ad9d.gif)

When I close the file and reopen, the cells I tried to create are now visible and runnable. But I still cannot create new ones.
![cells_in_julia2](https://user-images.githubusercontent.com/24438203/113459929-7d98be00-93c3-11eb-8525-cffa696624f5.gif)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Running a cell in a notebook running a julia kernel

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

Sorry output log is kinda long...
```
[jupyter.log](https://github.com/microsoft/vscode-jupyter/files/6251532/jupyter.log)

```

</p>
</details>

**Comment by claudiaregio** [comment]
Hi @Bebotron, I am able to reproduce. Pressing b or using the + icon to add a cell leads to more instances of the error.

**Comment by claudiaregio** [comment]
@Bebotron We actually recommend that other languages use the VS Code Insiders build to use Native Notebooks. 
I do not reproduce this issue on VS Code Insiders. If it is urgent for you to get unblocked I recommend using VS Code Insiders found here: 

VS Code Version. 1.56.0 
Python Version: v2021.3.680753044
Jupyter Ext Version: v2021.5.702919634

**Comment by Bebotron** [comment]
Any ideas on when this would be fixed for the release build? I've had previous issues with insiders build.

**Comment by rchiodo** [comment]
@Bebotron we're in the middle of testing the new experience with the stable version of VS code. Should be a matter of months.

However, the insiders build should be more stable than it has been in the last couple of months. We are better sync'd with VS code on API changes that were breaking us almost nightly. VS code insiders and an accompanying jupyter extension should ship each night now.
