### ISSUE TITLE
Remove data slicing experiment feature gate

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5399]
This will ensure users who have disabled experiments will still benefit from the feature.

**Comment by IanMatthewHuff** [comment]
Removed myself from optIn experiments. Slicing features all still there.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/09fb3696-38f8-443f-bd5a-9fbf2ea901d1)
