### ISSUE TITLE
Jupyter of VS Code cannot be exported as a python file.

### ISSUE THREAD

**Issue by Jill-Cheng** [microsoft/vscode-jupyter#5403]
## Environment data

-   VS Code version: 1.55.0 (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): 2021.5.702919634
-   Python Extension version (available under the Extensions sidebar): 2021.3.680753044
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.19041
-   Python and/or Anaconda version: Python3.8.3 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local 

## Expected behaviour

Export Jupyter as a python file in VS Code.

![image](https://user-images.githubusercontent.com/61971386/113540320-7ca99b80-9612-11eb-9d26-6b4308d8ee9e.png)

## Actual behaviour

Unable to export Jupyter as a python file in VS Code.

![image](https://user-images.githubusercontent.com/61971386/113539721-05bfd300-9611-11eb-9742-c9597a42a10e.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open VS Code and wait for all extensions to be loaded;
2. Open/create the Jupyter file, the code can be run (print("111"));
3. Click the export icon above Jupyter, there are only HTML and PDF options, but no the python option.

Related Links: [Export as python scripts is no longer available in VS code version 1.55](https://stackoverflow.com/questions/66925243/export-as-python-scripts-is-no-longer-available-in-vs-code-version-1-55)

**Comment by rchiodo** [comment]
Thanks for the bug. This is a regression.

**Comment by IanMatthewHuff** [comment]
Validated. I see the option now. But we should check in the point release branch as well to make sure it works on stable.

**Comment by Jill-Cheng** [comment]
@IanMatthewHuff  -Does it require the use of the specified version of the 'Python' extension or 'Jupyter' extension? There is still no "python" option in Jupyter in my VS Code.

**Comment by rchiodo** [comment]
@Jill-Cheng we close items when the bug has been fixed in our 'main' branch. You can build it yourself or use the insiders version of VS code which should get our nightly builds (which get published daily)
