### ISSUE TITLE
Native Notebooks - ipywidgets 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5404]
## Environment data

-   VS Code version: 1.55.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.702919634
-   Python Extension version (available under the Extensions sidebar): v2021.4.690665134-dev
-   OS and version: Windows 10
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Expected behaviour

Font color used to be white

## Actual behaviour
Strange red font for theme? Dark (Visual Studio) 

![image](https://user-images.githubusercontent.com/19276747/113593947-e5315200-95eb-11eb-9d76-d939cf31db60.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Run ipywidget with any text output

**Comment by DonJayamanne** [comment]
Dup of https://github.com/microsoft/vscode/issues/120577, https://github.com/microsoft/vscode-jupyter/issues/5299
