### ISSUE TITLE
Can't create new .NET interactive notebook

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5406]
1. Run the .NET Interactive: Create new blank notebook command
2. Notebook created has a Python kernel selected

**Comment by DonJayamanne** [comment]
How are you creating a new notebook?
You will need to use the command `Create .NET Notebook` or there should be a dropdown to create a .NET notebook

**Comment by joyceerhl** [comment]
Yes, that's exactly what I did. This is a known issue https://github.com/dotnet/interactive/issues/1189

**Comment by joyceerhl** [comment]
![dotnet](https://user-images.githubusercontent.com/30305945/113619430-cfcd1f80-960d-11eb-85c4-91bd88c07f9f.gif)

**Comment by DonJayamanne** [comment]
Should be fixed now
