### ISSUE TITLE
Jupyter: new "kernelspec" tag produces "jupyter_client.kernelspec.NoSuchKernel" with "jupyter nbconvert"

### ISSUE THREAD

**Issue by mihkelvaher** [microsoft/vscode-jupyter#5413]
## Environment data

-   VS Code version:  1.55.0
-   Jupyter Extension version: ms-toolsai.jupyter v2021.5.702919634
-   Python Extension version: ms-python.python v2021.3.680753044
-   OS and version: MacOSX Catalina 10.15.7
-   Python: 3.8.8; Anaconda: 4.3.27
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Expected behaviour
1) Save mynb.ipynb in VS Code
2) Convert notebook into html via terminal in the same env using
`jupyter nbconvert --to html mynb.ipynb --no-input --execute`

## Actual behaviour
Conversion produces error
`jupyter_client.kernelspec.NoSuchKernel: No such kernel named python388jvsc74a57bd040b90fc7ac2e82be620538bbf156a62f078051c1c11595b3240bdeeddbe7576e`

## Steps to reproduce:
1. mynb.ipynb:
```
{
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  },
  "orig_nbformat": 2,
  "kernelspec": {
   "name": "python388jvsc74a57bd040b90fc7ac2e82be620538bbf156a62f078051c1c11595b3240bdeeddbe7576e",
   "display_name": "Python 3.8.8 64-bit ('my_env38': conda)"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2,
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"test\")"
   ]
  }
 ]
}
```
2) `jupyter nbconvert --to html mynb.ipynb --no-input --execute`

<details>
The problem appeared after updating both VS Code and conda, though older notebooks can be converted without any problems in the same env.

The issue can be manually fixed if the "kernelspec" tag is removed:
```
,
  "kernelspec": {
   "name": "python388jvsc74a57bd040b90fc7ac2e82be620538bbf156a62f078051c1c11595b3240bdeeddbe7576e",
   "display_name": "Python 3.8.8 64-bit ('my_env38': conda)"
  }
 },
```

I'm using `jupyter nbconvert` because I have not found any ways to hide/remove cells with the built in exporter (the `--no-input` flag).
</details>

**Comment by IanMatthewHuff** [comment]
@mihkelvaher I tried this out by specifically setting the kernelspec to a bad name, and I do get the same error. However I'm note sure if the fix is something that we can handle easily from our side. The kernelspec tag here (if you are running from VS Code) is pointing at a legitimate conda kernel. However there seem to be issues with nbconvert picking up conda kernels for execute:

https://github.com/jupyter/nbconvert/issues/515
https://github.com/Anaconda-Platform/nb_conda_kernels/issues/77

The kernelspec tag looks valid to me, so the issue is with nbconvert picking up the kernelspec specified in the metadata. Which isn't something that we could resolve in VS Code. Seems like manually specifying a kernelspec for the conversion might help? 

https://nbconvert.readthedocs.io/en/latest/execute_api.html#execution-arguments-traitlets

**Comment by mihkelvaher** [comment]
Thanks!
Specifying the kernel did the trick.
`jupyter nbconvert --ExecutePreprocessor.kernel_name=python`...
Didn't think of turning to nbconvert since the issue came just after updating VS Code...

What would be _really_ nice, would be some code collapsing/hiding options in the output html, removing the need to use of nbconvert.
Checking out the Insiders version, there is an option to do these things in the editor but the collapsing does not persist into html outputs.

**Comment by rchiodo** [comment]
Do we need to do this same kernel name argument for our export?

**Comment by mihkelvaher** [comment]
A minor detail:
The browser jupyter notebook also "_Could not find a kernel matching..._" when opening a notebook saved in VS Code.
I've used `conda install nb_conda` to enable choosing kernels from conda and the correct kernel appears in the list below "_Could not find a kernel matching..._"

**Comment by DonJayamanne** [comment]
> Do we need to do this same kernel name argument for our export?

I'd say yes.

**Comment by DonJayamanne** [comment]
@mihkelvaher 
I believe this has been resolved, we no longer store the generated name in the ipynb file.
Please feel free to re-open this issue if the issue persists or please do create a new one and we'll look into it.
