### ISSUE TITLE
Docstring do not appear when editing cell

### ISSUE THREAD

**Issue by Syndorik** [microsoft/vscode-jupyter#5415]
## Environment data

-   VS Code Insiders: 1.56.0-insider 550035808407c15252e581e8abe1b820b9d311ee x64
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.718745073
-   Python Extension version (available under the Extensions sidebar): 2021.3.680753044
-   OS (Windows | Mac | Linux distro) and version: Windows10
-   Python and/or Anaconda version: 3.9.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote 

## Actual behaviour
Docstring do not appear when editing a cell. However inside the import cell, docstring appears.

For instance if I have two cells like:

```
import networkx as nx
```
and
```
nx.Graph()
```
Docstring won't appear

However if I have:
```
import networkx as nx
nx.Graph()
```

Then it appears

**Comment by IanMatthewHuff** [comment]
@Syndorik Sorry can I ask for a bit of a clarification here. By DocString do you mean the function hover like so?
![image](https://user-images.githubusercontent.com/812783/113758399-acb37600-96c8-11eb-98bf-6fb8f7945027.png)
If so I'm not currently reproing this issue.

However language features (like DocStrings) do rely not just on the Jupyter extension, but on the Python extension and the currently selected language server. Your Python extension does look like it's possibly a bit out of date could you try updating that and reproing? Also, what language server do you have selected in the Python extension?

**Comment by Syndorik** [comment]
@IanMatthewHuff Of course. I'm indeed speaking of the function hover, getting everything from the documentation. When the function that I'm calling is inside the same import, I can access the documentation as expected
![image](https://user-images.githubusercontent.com/28219244/113770891-0183da80-9723-11eb-808c-f6edd7f99ada.png)

However when it's not inside the same cell:
![image](https://user-images.githubusercontent.com/28219244/113770987-20826c80-9723-11eb-81be-8fce6bb03d46.png)

I actually tried this setup in two different computers with two installs. I also tried with a remote jupyter server and a local one. Whatever I do I keep having this issue.

I'm currently using the 2021.3.680753044 extension for python, that's the last release I can download. And I'm using Jedi as language server. I tried Pylance, but it did not work either

**Comment by canersnli** [comment]
I got same even worse issue. 

Pylance autocomplete doesn't work. It works like jupyter autocomplete.
![2021-04-08_01h02_07](https://user-images.githubusercontent.com/70806315/113940724-96133900-9806-11eb-8f25-f552d9d3ca76.png)


Even if I import library and run in the the same cell , still nor at the end of typing pop-up documentation neither hover pop-up documentation works.
![2021-04-08_01h02_31](https://user-images.githubusercontent.com/70806315/113940884-dffc1f00-9806-11eb-9f7a-fbc5d95d147a.png)
![2021-04-08_01h03_01](https://user-images.githubusercontent.com/70806315/113941085-2cdff580-9807-11eb-9297-d9da9852e47d.png)


- VS Code Insiders: 1.56.0-insider (user setup) Commit: bb90ba3d5a5f8d114045b045f3bbe1ebc404f54a
- Jupyter Extension version : v2021.6.723987413
- Python Extension version : v2021.4.690665134-dev
- OS (Windows | Mac | Linux distro) and version: Windows10
- Python and/or Anaconda version: 3.7.10
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Jupyter server running: local
- Microsoft Language Server: Pylance v2021.3.4

I had opened #4218 topic 4 months ago, unfortunately it still has not been solved. Now I got stuck in older VSCode version 1.51 which has some strange bugs either.

**Comment by IanMatthewHuff** [comment]
@Syndorik and @canersnli I see that you are both on insiders. Did this issue just hit? VS Code insiders just had a breaking change (yesterday I believe) that change requires an update to the insiders version of the python extension which is currently in progress here: https://github.com/microsoft/vscode-python/pull/15884#pullrequestreview-630709379

I'm guessing that this is not @Syndorik 's issue as they are seeing some hover documentation, just not when the import is in a different cell.

**Comment by rchiodo** [comment]
@Syndorik can you switch to the insiders version for python?

![image](https://user-images.githubusercontent.com/19672699/114090150-e7a1df00-986b-11eb-832e-3a11d48408ff.png)

It's a setting you have to change. Once it downloads and you reload VS code this issue should go away.

**Comment by canersnli** [comment]
Woow, everything works like a charm now, thx @rchiodo  I am switching from VS Code to insiders now, hope future updates don't create same issue again.

**Comment by Syndorik** [comment]
Updating my version of code-insiders did it for me too! That's awesome, thanks!

**Comment by rchiodo** [comment]
Thanks for checking :)

**Comment by floriandonhauser** [comment]
Unfortunately it seems like I am having the same issue.
I am running Python 3.8.8 with anaconda.

Only ctrl+shift+space shows the documentation in .ipynb files and not hover. In normal .py files documentation on hover works.
Version: 1.56.0-insider (user setup)
Commit: 7ce1499d9541ba2acf66cd30a9054bd7818a8f80
Date: 2021-04-22T05:13:14.711Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
Python v2021.4.765268190
Jupyter v2021.6.770905982
Python insider channel set to daily (Is there a way to see if it actually downloaded it?)

For normal VS Code the problem is even bigger, not even ctrl+shift+space works for .ipynb. Documentation works normally for .py as well.
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
Python v2021.4.765268190
Jupyter v2021.5.745244803

Any ideas?

**Comment by rchiodo** [comment]
@floriandonhauser does autocomplete work? Do you see any red squiggles anywhere? There are some problems with inserting new cells messing up intellisense. 

Additionally the interpreter set for the workspace (and not the kernel) is used to determine the set of packages that the language server understands. This might be the cause of the problem too.

On top of that, Pylance seems to work better than Jedi. Are you using Jedi or Pylance?

**Comment by floriandonhauser** [comment]
@rchiodo 
> On top of that, Pylance seems to work better than Jedi. Are you using Jedi or Pylance?

Installing Pylance fixed it for me, thank you a lot!
Before with Jedi, I think autocomplete was behaving like normal jupyter notebook (pretty bad recommendations imo).
The workspace was not the problem.
