### ISSUE TITLE
Updates to `cells` property in Notebook aPI

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5417]
Please note the following BREAKING change: NotebookDocument#cells has been removed in favour of getCells(range?), cellCount, and cellAt(index).

https://github.com/microsoft/vscode/issues/93265#issuecomment-813989752

**Comment by IanMatthewHuff** [comment]
Also adding the notebook property to TextDocument usage. It's in the same API change that I picked up from updating proposed API.
