### ISSUE TITLE
Running the contributed command: 'jupyter.selectjupyteruri' failed

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#5419]
Issue Type: <b>Bug</b>
Recent update completely broke Jupyter.

Selecting <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd> then `Jupyter: Specify local or remote Jupyter server for connections` gives the following error:
```
Command 'Jupyter: Specify local or remote Jupyter server for connections' resulted in an error (Running the contributed command: 'jupyter.selectjupyteruri' failed.)
```

![image](https://user-images.githubusercontent.com/12793783/113743280-80502780-96d1-11eb-860d-4ea4941066dc.png)

Trying to run python code with <kbd>Shift</kbd>+<kbd>Enter</kbd> gives the following three errors simultaneously:

1. `Unable to open 'Interactive - microsoft/vscode-python#1': Webview overlay is disposed.`
2. `e.toLowerCase is not a function`
3.  `e.toLowerCase is not a function`

![image](https://user-images.githubusercontent.com/12793783/113743662-ea68cc80-96d1-11eb-9c11-729dca1a940c.png)

Extension version: 2021.3.680753044
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.38GB free)|
|Process Argv|--crash-reporter-id f652528b-5678-4b12-9ca0-3de6b1e1135f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
openwsldoc:30282072
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820cf:30276953
pythondataviewer:30285071

```

</details>

**Comment by IanMatthewHuff** [comment]
@clayms Apologies on this. We store the jupyter server URI in the vscode secret store, and anyone on Windows is getting hit by this VS Code issue here:
https://github.com/microsoft/vscode/issues/120558
We're updating our code to clear out any secrets that hit this decryption failed message. That's basically what you did when you deleted the setting. After the secret is regenerated on 1.55 it should work from then on out.

**Comment by joyceerhl** [comment]
Seems to be working now. At least if I run the 'Specify local or remote Jupyter server for connections' command from the command palette I get the usual quickpick:

![image](https://user-images.githubusercontent.com/30305945/113913618-65dd8300-9791-11eb-9ead-1ff82297265c.png)

@DavidKutu @IanMatthewHuff  was there anything else to do as far as validation?

**Comment by IanMatthewHuff** [comment]
@joyceerhl were you reproing the issue before? I think the only way to repro this was if you had created a secret pre 1.55 on windows, then updated to 1.55 on windows and tried to access the same secret. I'm Mac so I've never actually seen the issue myself.

**Comment by joyceerhl** [comment]
Ah I wasn't reproing the issue before. I'll leave this for someone else to validate then.

**Comment by IanMatthewHuff** [comment]
@rchiodo I think you are our only other windows option. Were you seeing this? If you don't have it, then it's probably fine to just close. Code change is very simple and David did have the repro for fixing.

**Comment by rchiodo** [comment]
I'm not seeing that on insiders or stable. Specifying remote works fine and the quick pick always appears.

**Comment by clayms** [comment]
@rchiodo 

> @joyceerhl were you reproing the issue before? I think the only way to repro this was if you had created a secret pre 1.55 on windows, then updated to 1.55 on windows and tried to access the same secret. I'm Mac so I've never actually seen the issue myself.

**Comment by rchiodo** [comment]
Sorry that means in order to repro this I need to uninstall VS code, install 1.54, connect to remote, upgrade back to 1.55 and make sure to use the new bits in main in 1.55.

Is there a way to just corrupt the VS secret store?

**Comment by joyceerhl** [comment]
Validated. I did the following:

1. Install VS Code 1.54 and the March release (2021.3.x) of the Jupyter extension on the marketplace
2. Run `Specify local or remote Jupyter server for connections' to pick AML compute remote jupyter server
3. Open a blank notebook with the remote connection
4. Upgrade to VS Code 1.55.1 with the same 2021.3.x release of the Jupyter extension
5. Run 'Specify local or remote Jupyter server for connections' and verify the error message comes up:
![image](https://user-images.githubusercontent.com/30305945/114248705-34111b80-994d-11eb-8f27-c7579442dd07.png)
6. Install the Jupyter vsix from this morning's bug bash
7. Run 'Specify local or remote Jupyter server for connections' and verify the quickpick comes up with no error message 🎉

@clayms we're planning to make this fix available in a point release early next week so I'm going to go ahead and close this issue. Please keep an eye out for that release, which should resolve this issue. Thanks for bringing this to our attention!
