### ISSUE TITLE
Notebook trust when all cells are markdown (sanitize markdown)

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#5421]
Issue Type: <b>Bug</b>

I created a new notebook off https://github.com/joyceerhl/notebooks/blob/main/markdown.ipynb. All cells are markdown. Why am I prompted for notebook trust?

![image](https://user-images.githubusercontent.com/4674940/113758809-33685300-96c9-11eb-9e50-71adc994c1ea.png)

Extension version: 2021.6.718745073
VS Code version: Code - Insiders 1.56.0-insider (Universal) (550035808407c15252e581e8abe1b820b9d311ee, 2021-04-02T05:13:17.592Z)
OS version: Darwin arm64 20.3.0
Remote OS version: Linux x64 5.4.0-1031-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--enable-proposed-api lszomoru.lszomoru-proposed-api-sample --enable-proposed-api donjayamanne.kusto --crash-reporter-id ef10dfea-3602-4c74-ba1a-109ce7da7825|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.4.0-1031-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (1.79GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
openwslfolder:30278404
vscoresta800:30283263
vspre833:30267464
pythonptprofiler:30281269
vscnewfiletext:30280636
vshan820:30276952
pythondataviewer:30285072

```

</details>

**Comment by rchiodo** [comment]
Because markdown can have embedded javascript in it. I believe one of our attack vectors was actually markdown.

**Comment by kieferrm** [comment]
Makes sense, in this case we should consider sanitizing the markdown. I just opened another notebook that has a couple of code cells and for each of them one markdown cell with a header. It's hard to swallow that even for looking at it I'm getting prompted.

**Comment by greazer** [comment]
Should be solved by workspace trust
