### ISSUE TITLE
Widgets not rendering after reloading vscode

### ISSUE THREAD

**Issue by Syndorik** [microsoft/vscode-jupyter#5424]
## Environment data

- VS Code Insiders: 1.56.0-insider 550035808407c15252e581e8abe1b820b9d311ee x64
- Jupyter Extension version (available under the Extensions sidebar): 2021.6.718745073
- Python Extension version (available under the Extensions sidebar): 2021.3.680753044
- OS (Windows | Mac | Linux distro) and version: Windows10
- Python and/or Anaconda version: 3.9.2
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Jupyter server running: Remote
- IpyWidgets==7.6.3

## Behavior
When I'm initializing the jupyter server, connecting the notebook for the first time and runing the following cell 

```
from tqdm.notebook import tqdm
[k for k in tqdm(range(10))]
```
![image](https://user-images.githubusercontent.com/28219244/113777554-8a067900-972b-11eb-89b5-50fde4770cb9.png)

The ipywidget is displaying correctly. However, if I exit the notebook and comeback or if I reload the notebook, the Ipywidget does not render anymore.
![image](https://user-images.githubusercontent.com/28219244/113777455-65120600-972b-11eb-890d-94fcd8b1b7b3.png)

When I toggle the developper tools, on reload I have the following warning
![image](https://user-images.githubusercontent.com/28219244/113778164-5e37c300-972c-11eb-9393-aafedc7671df.png)

**Comment by rchiodo** [comment]
This is a side effect of us closing kernels when closing notebooks. Jupyter has the same problem but at least tells you why:

![image](https://user-images.githubusercontent.com/19672699/113903880-4db43680-9786-11eb-8b72-4c90646cc620.png)

**Comment by Syndorik** [comment]
Ok thanks for the information,
But, when I rerun the cell with a new runing kernel, the widget is  still not rendering. In jupyter I think the ipywidgets is rerendering if you rerun the cell with a new kernel after shuting down the other. 
In vscode if I close a notebook/reload it and then rerun the cell it doesn't work.

**Comment by rchiodo** [comment]
I'm reproing that too. Very weird. Although closing and reopening the notebook makes it work for me. 

My guess is that reloading a kernel does not remove the preload scripts that the first kernel added. This interferes with ipywidgets working.

**Comment by Syndorik** [comment]
I tested, and I need to kill all runing kernel (via the rest API) and then reload the window. If I do that, the IpyWidgets works again. Just closing the notebook an reopening it doesn't work for me

**Comment by rchiodo** [comment]
If VS code provides a way to detect this we should use it, or we need to set some global state to detect this ourselves.

**Comment by DonJayamanne** [comment]
In general IPyWidgets will not be re-loaded whether we re-load or close/re-open a notebook, unless we have https://github.com/microsoft/vscode-jupyter/issues/4404

**Comment by joyceerhl** [comment]
Validated (I think). In Insiders now if I execute a notebook with ipyvolume widgets, then reload, the widget doesn't initially show, but I can reexecute the cell and see the widget appear in the cell output.
