### ISSUE TITLE
Output Pandas truncated

### ISSUE THREAD

**Issue by Salokin42** [microsoft/vscode-jupyter#5429]
Issue Type: <b>Bug</b>

Hello,

the output in the Jupyter Interaction Windwo on the right is truncated. I try to output pandas dfs, and I don't see the whole output. I set the text output limit in the config to 0 and use the respective pandas commands (pd.set_option('display.max_columns', 1000)
pd.set_option('display.max_rows', 1000))

Best Regards,
Nikolas Lauer

Extension version: 2021.5.702919634
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.18363

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
wslfolderdoc:30282074
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue. Do you have an example cell that repros the problem?

I'm wondering why you'd want to look through thousands of rows in the text editor. Perhaps the dataviewer would work better?
https://code.visualstudio.com/docs/python/jupyter-support#_variable-explorer-and-data-viewer

**Comment by greazer** [comment]
Issues labeled with "Info needed" are closed if we do not receive more information from the issue author in 2 weeks. If you are the issue author and you still are running into this problem, please reactivate with additional information.
