### ISSUE TITLE
jupyter version 2021.5.7029 cannot work with synapse kernel

### ISSUE THREAD

**Issue by zesluo** [microsoft/vscode-jupyter#5431]
running below command with jupyter version 2021.5.7029
![image](https://user-images.githubusercontent.com/46309533/113853121-e15e2500-97cf-11eb-8d92-71fb6a855b2f.png)
generate error like this: 
![image](https://user-images.githubusercontent.com/46309533/113853183-f3d85e80-97cf-11eb-91c5-25088d55efa7.png)
![image](https://user-images.githubusercontent.com/46309533/113853252-0783c500-97d0-11eb-9802-c9701fbbac6c.png)

but if I change to this, everything works fine:
![image](https://user-images.githubusercontent.com/46309533/113853317-1c605880-97d0-11eb-9346-57d4ccae9639.png)

Background knowledge: use folder \jupyter_nb_ext to have a synapse kernel. recently we deprecate adal and use msal instead('AuthenticationContext' is only used in adal). We have already fixed it. But find that these two different jupyter extension version have different outcomes.

## Environment data

Version: 1.55.0 (user setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:55.261Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment]
That the old version works doesn't make any sense. This is code inside of the kernel. Which is running on the remote machine? I don't see how anything we do would make a difference here. 

Zeshi, I think we'd have to debug this. Or we need more information from the synapse kernel.

Is this still the situation where the synapse kernel is remote?
