### ISSUE TITLE
Markdown cells in edit mode get closed when switching to another application

### ISSUE THREAD

**Issue by david-cortes** [microsoft/vscode-jupyter#5434]
**Steps to reproduce:**
* Open a jupyter notebook with markdown cells.
* Double click some markdown cell to edit, and move the focus to somewhere inside it.
* Press Alt+Tab to switch to a different application.
* Return to vscode with Alt+Tab.

**Expected behavior:** should leave the markdown cell open in edit mode, as it was before switching to a different application.

**Actual behavior:** the markdown cell is closed (is not in edit mode) when switching back to vscode.

**Setup:** vscode 1.55.0, jupyter extension 2021.5.702919634, running on debian linux.

**Comment by rchiodo** [comment]
Thanks for the issue. 

This should be addressed when we switch over to VS code's new notebook API. Please track this issue for when we switch:
#1231.

You can try it yourself if you use VS code [insiders](https://code.visualstudio.com/insiders/).
