### ISSUE TITLE
Markdown cell rendering incorrectly when there are separation bars

### ISSUE THREAD

**Issue by david-cortes** [microsoft/vscode-jupyter#5435]
This notebook here renders incorrectly in vscode:
https://github.com/david-cortes/contextualbandits/blob/master/example/online_contextual_bandits.ipynb
https://nbviewer.jupyter.org/github/david-cortes/contextualbandits/blob/master/example/online_contextual_bandits.ipynb

In particular, the markdown cell at the beginning renders incorrectly: the message before the "sections: part is truncated, and shows again and again later after every separation bar.

**Setup:** vscode 1.55.0, jupyter extension 2021.5.702919634, running on debian linux.

**Comment by rchiodo** [comment]
Thanks for the issue. Likely a markdown renderer difference between what we ship and Jupyter uses.

**Comment by rchiodo** [comment]
If you try VS code [insiders](https://code.visualstudio.com/insiders/), this should be working

**Comment by rchiodo** [comment]
Well mostly working, there's still this bug here:
https://github.com/microsoft/vscode/issues/103519

**Comment by joyceerhl** [comment]
Fixed in native notebooks.
