### ISSUE TITLE
Native notebooks - can run cells even when untrusted

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5436]
Open notebook in jupyter classic
Open in insiders. It should say untrusted. Close trust notification without accepting yes.

I can still run a cell.

**Comment by rchiodo** [comment]
If run is clicked we shouldn't run but instead put up the error message.

**Comment by IanMatthewHuff** [comment]
Validated. I'm blocked from execution after closing the trust prompt.
