### ISSUE TITLE
Native notebooks - Trust icon is just a big red blob

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5437]
![image](https://user-images.githubusercontent.com/19672699/113915651-e1403400-9793-11eb-81e8-351a85239b50.png)

**Comment by joyceerhl** [comment]
Validated. Looks good now 
![image](https://user-images.githubusercontent.com/30305945/114244899-34f17f80-9944-11eb-9906-ee81ca48319c.png)
