### ISSUE TITLE
Native Notebooks - Run all above/below cell toolbar 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5438]
Run all above/below icons showing up in the middle of the toolbar. 
Can we move them to the very left so they are closest to the run? (For both left and right aligned cell toolbar) 

![image](https://user-images.githubusercontent.com/19276747/113915950-409e4400-9794-11eb-8bf7-62bded893ce5.png)

**Comment by joyceerhl** [comment]
Validated: 
![image](https://user-images.githubusercontent.com/30305945/114904418-b32ea580-9dcc-11eb-90f8-d2dba9e8c309.png)
