### ISSUE TITLE
Undo on a per cell basis does not work

### ISSUE THREAD

**Issue by Syndorik** [microsoft/vscode-jupyter#5441]
## Environment data

-   VS Code version: code-insiders 1.56.0-insider bb90ba3d5a5f8d114045b045f3bbe1ebc404f54a x64
- Jupyter Extension version (available under the Extensions sidebar): 2021.6.718745073
- Python Extension version (available under the Extensions sidebar): 2021.3.680753044
- OS (Windows | Mac | Linux distro) and version: Windows10
- Python and/or Anaconda version: 3.9.2
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Jupyter server running: Remote

# Actual Behavior
I assigned `jupyter.notebookeditor.undocells` and `jupyter.undocells` shortcuts. However, when I press the key combination, nothing happens. The only undo action that works is the one acting on notebook level

**Comment by claudiaregio** [comment]
Hi @Syndorik, will double check tomorrow but I believe the commands `jupyter.notebookeditor.undocells` and `jupyter.undocells ` could be for our interactive window... could you provide a screenshot or the code you wrote in order to set these shortcuts in case they are not?

**Comment by Syndorik** [comment]
Hi @claudiaregio, I've set the shortcut the following way :
![image](https://user-images.githubusercontent.com/28219244/113991504-ce406900-9852-11eb-8268-5e5742cdd928.png)
I think this is indeed for the interactive window, which is described there I guess https://code.visualstudio.com/docs/python/jupyter-support-py 

Is there any shortcut for an undo that works inside a cell only? Like the ctrl-Z in jupyter notebook that undo what was done inside a cell. Thanks!

**Comment by claudiaregio** [comment]
Is the shortcut Ctrl + Z not working for you in notebooks? 

Could you open the command palette and select "Developer: Toggle Screencast Mode" and then record a gif of what happens when you try to use Ctrl + Z within a cell after making some changes? 
(https://www.screentogif.com)

**Comment by Syndorik** [comment]
The ctrl + Z is working, but it undo what was done in the chronological order. The gif might help you understand what I mean bt that:
![Peek 2021-04-09 00-06](https://user-images.githubusercontent.com/28219244/114102607-e2727d80-98c7-11eb-9209-8ad085ecf9e0.gif)

I don't know if it's a bug or if it does not exist, but in jupyter notebook and colab notebooks, there are two types of undo, one that acts over the whole notebook (undoing cell deletion etc) and one that undo text inside a cell just like a normal text editor.

**Comment by claudiaregio** [comment]
@Syndorik I see what you mean now! Thanks so much for providing that video. Will look into this more soon

**Comment by Alaboudi1** [comment]
I also struggle with the ctrl + Z behavior. In many cases, it does not work or go through previous changes in random order.  Please look into this issue.

**Comment by claudiaregio** [comment]
@Syndorik and @Alaboudi1 I have filed an issue upstream in vs code, if you'd like to support ctrl + z changes please comment here: https://github.com/microsoft/vscode/issues/121056

**Comment by greazer** [comment]
This works as expected in recent insider releases
