### ISSUE TITLE
Notifications after installing an extension.

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#5447]
This is what I got right after installing the Jupyter extension on a SSH remote and opening the first notebook:

![image](https://user-images.githubusercontent.com/4674940/113956764-e2448600-97d2-11eb-9813-58a04cee5aff.png)

**Comment by claudiaregio** [comment]
@kieferrm Have you opened notebooks up before on that remote machine? 
The first prompt should show up if if you open at least 5 notebooks or if you run a minimum of 100 cells. 
What could be happening here is we are somehow keeping the count for the local machine and not separating for the remote scenario...

**Comment by greazer** [comment]
Changes to address this being tracked by #5261
