### ISSUE TITLE
How is the variable explorer in jupyter notebook implemented?

### ISSUE THREAD

**Issue by lensherrggg** [microsoft/vscode-jupyter#5448]
Hi, I'm currently developing an app that has some relations with Jupyter. I'm wondering how your team implemented the variable explorer in Jupyter interactive window and how to get the value of variable in user namespace in Jupyter? Besides, is it possible to edit on the variable explorer and change the value of variables like in Spyder?

I hope I could receive your reply soon. Many thanks.

**Comment by rchiodo** [comment]
You can view the logic here. This is where we make the calls to jupyter to compute the variable values and list.
https://github.com/microsoft/vscode-jupyter/blob/main/src/client/datascience/data-viewing/jupyterVariableDataProvider.ts
