### ISSUE TITLE
python interpreter not recognizing in VS Code Jupyter notebook via conda environment

### ISSUE THREAD

**Issue by cpoptic** [microsoft/vscode-jupyter#5453]
> Version: 1.55.0 (user setup)
> Commit: c185983a683d14c396952dd432459097bc7f757f
> Date: 2021-03-30T16:01:55.261Z
> Electron: 11.3.0
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Windows_NT x64 10.0.21292

It appears VS Code does not add one of the paths for Python interpreters in the Conda environment for some strange reason.

Running `python --version` from CMD prompt (with Conda env activated) shows `Python 3.6.12 :: Anaconda, Inc.`

But running `python --version` from within a Jupyter notebook in VS Code shows `Python 3.8.3`

So I suspect there's an issue with the VS Code not correctly mapping the Python path from the conda environment to the Jupyter notebook?

Here's the output of `where python` in my CMD prompt (within the Conda virtual env of course):

    (my_conda_env) D:\projects>where python
    C:\ProgramData\Anaconda3\envs\my_env\python.exe
    C:\Python38\python.exe
    C:\Users\username\AppData\Local\Microsoft\WindowsApps\python.exe

But here's the output of `where python` when called within VS Code Jupyter notebook (also with the Conda environment activated):

    C:\Python38\python.exe
    C:\Users\username\AppData\Local\Microsoft\WindowsApps\python.exe

Why does Visual Studio Code not correctly locate the 1st python path?

**Comment by rchiodo** [comment]
@cpoptic can you grab a screenshot of both your python interpreter list (bottom left when opening a python file) 

Looks like this for me:

![image](https://user-images.githubusercontent.com/19672699/114094902-b4624e80-9871-11eb-80ff-9d42b976ccce.png)


And a screenshot of the kernel list from your notebook? They should be pretty close. Mine looks like this:

![image](https://user-images.githubusercontent.com/19672699/114094982-c8a64b80-9871-11eb-8ce7-8d5e4d416fdd.png)

**Comment by cpoptic** [comment]
Certainly @rchiodo:
Screenshot of the Python interpreters (I have many versions of Python installed, this):

![image](https://user-images.githubusercontent.com/7234261/114183182-6735b980-9911-11eb-9fd6-0e949bb02378.png)

And the list of notebook kernels (again, I have multiple environments installed so need to scroll down to see all of them; these are just the first being displayed for you).

![image](https://user-images.githubusercontent.com/7234261/114183733-fc38b280-9911-11eb-9b1a-71448823f128.png)

**Comment by rchiodo** [comment]
Which kernel did you pick for the notebook?

**Comment by cpoptic** [comment]
This was on VS Code Insiders so that may have affected this issue.  
But a simple restart of VS Code, selecting the desired Conda environment (lower left corner of the IDE), and selecting the correspondingly named Jupyter kernel (upper right corner of the IDE) resolved this.

Closing as I believe this is resolved.  Much appreciated for the help.
