### ISSUE TITLE
Failures finding python interpreters should not cause kernelspec lookup to die

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5454]
https://github.com/microsoft/vscode-python/issues/15856#issuecomment-816007199

If the python extension fails to return interpreters it messes up our kernel search. We should make this more robust such that an individual interpreter failing to get details doesn't bring down everything else.

**Comment by rchiodo** [comment]
I think the fix for this would be in getInterpreterDetails during listKernelSpecs in the localKernelFinder.ts

**Comment by greazer** [comment]
Handled by #5486
