### ISSUE TITLE
Kernel name initially not displayed and status is initially busy

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5459]
From https://github.com/microsoft/vscode-jupyter/issues/5368:

In custom editor running in the extension host with latest main bits, when I first open a notebook connected to a kernel that does not have ipykernel installed, the kernel displays as busy and no name is shown. I would expect it to say 'Not Started' (because the kernel isn't running). If we've picked a kernel for the notebook we should also show the kernel's name.

**Comment by DonJayamanne** [comment]
Isn't this a regression, i don't recall seeing `busy` when opening a notebook.
Yes this block users, hence in a way we could say its not a regression (then again, i don't think thats how we'd classify regressions)

**Comment by joyceerhl** [comment]
This is a regression. I think this cropped up as a result of the disableUI change for autostarted kernels.

**Comment by DonJayamanne** [comment]
> disableUI change for autostarted kernels.

Weird, we didn't change anything for auto start in WebViews.

**Comment by DonJayamanne** [comment]
Closing this issue as we no longer have custom editors.
