### ISSUE TITLE
.NET interactive notebook metadata language is set to Python

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5460]
When a .NET interactive kernel is picked for a new blank notebook, the language in the metadata is set to Python. So after closing and reopening a notebook with the .NET kernel selected (even after running cells), the Jupyter extension picks a Python kernel and flips all the cell language identifiers to Python.

**Comment by rchiodo** [comment]
Something weird is happening here.

**Comment by joyceerhl** [comment]
Validated. If I create a Jupyter notebook using our create new blank Jupyter notebook command, pick the .NET interactive kernel, run some code, save it, close and reopen it, .NET interactive is correctly picked as the kernel and the cell language identifiers stay as C# (Interactive):

![image](https://user-images.githubusercontent.com/30305945/116745532-15340100-a9b0-11eb-8536-a1c2c3c5c087.png)
