### ISSUE TITLE
Update release branch of Python extension to handle new or old API

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#5463]
We updated the Python extension in main to handle the new NotebookDocument .cells API. However it's going to ship out with a VSCode that doesn't support that yet. We need to either revert the code as the old deprecated API is still supported (but this might break when VS Code updates? Can check if current main proposed API is what VSCode will ship) or change the code to handle either case. If not language service features in Stable will not work in notebooks.

**Comment by joyceerhl** [comment]
(Belatedly) validated.
