### ISSUE TITLE
Open with from file explorer + drag and dropping .ipynb files in VSC Insiders opens JSON 

### ISSUE THREAD

**Issue by jruales** [microsoft/vscode-jupyter#5465]
Issue Type: <b>Bug</b>

I noticed that when I open an .ipynb file that has a space in the filename, the notebook doesn't open with the notebook experience, but with the normal file experience. It seems like there's an issue with the regex used to determine if a notebook should be opened with the notebook experience? Note that this is in VS Code Insiders.

Extension version: 2021.3.680753044
VS Code version: Code - Insiders 1.56.0-insider (5904b7b686e9274631893d560fdbc55a5567f878, 2021-04-08T17:51:28.503Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (45.33GB free)|
|Process Argv|--crash-reporter-id e22d7c10-2f28-4cf7-a9c4-c5f030d067e5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt875:30259475
vspre833cf:30267465
vshan820cf:30276953
vscus158cf:30286554

```

</details>

**Comment by claudiaregio** [comment]
@jruales, I am unable to repro at this time. Would you be able to record a video of what you are seeing?  (https://www.screentogif.com)

**Comment by jruales** [comment]
@claudiaregio Hmm you're right, I think I confused the cause of why it wasn't loading with the Jupyter Notebook experience sometimes.

What I notice now is that:
* When I right-click -> open with Code Insiders
  * It shows the notebook experience if VS Code Insiders was *already open* before I did right-click -> open with Code Insiders
  * It shows the raw JSON file experience if VS Code Insiders was *closed* before I did right-click -> open with Code Insiders
* When I drag the ipynb into VS Code Insiders
  * It always shows the raw file experience

A separate issues is that I've noticed is that the raw file experience doesn't even show JSON syntax highlighting.

**Comment by claudiaregio** [comment]
@jruales, thanks for the clarification. I am now able to reproduce all of the behaviors listed above. I'm going to go ahead and move this to the vs code repo. 

On your second comment about the JSON Syntax highlighting I noticed the following. When the JSON is displayed, it is automatically being detected as Jupyter. 

![image](https://user-images.githubusercontent.com/19276747/114286844-45265f00-9a17-11eb-84fc-8d7b73f6276e.png)

If you click on that Jupyter button, you should see the following menu pop up. 

![image](https://user-images.githubusercontent.com/19276747/114286862-62f3c400-9a17-11eb-9cd1-13a660d91898.png)

Go ahead and click the second option -- "Configure File Association for '.ipynb'" and then type "JSON" and select it. 

![image](https://user-images.githubusercontent.com/19276747/114286898-97678000-9a17-11eb-8c76-afec53cd7bdd.png)

If you happen to work with raw JSON files and want to see the syntax highlighting, following the above steps should allow you to see it again. This did not interfere with opening notebooks in general in any way.

**Comment by claudiaregio** [comment]
Issue for opening now being tracked here: https://github.com/microsoft/vscode/issues/121029

**Comment by jruales** [comment]
In that case, should I close the current issue?

**Comment by claudiaregio** [comment]
@jruales If you're all set on the other issue, we can close it :)
