### ISSUE TITLE
Data Viewer autorefresh

### ISSUE THREAD

**Issue by Kugeleis** [microsoft/vscode-jupyter#5467]
The Data Viewer is great but should allow automatic refresh of the actual data content.
currently: Data Viewer shows data at the time of opening this tab
request: Allow data Viewer Tab reload the current data - this should be toggled by user since large data sets should not auto-reload by default

**Comment by joyceerhl** [comment]
Thanks for the feedback @Kugeleis. I'd like to understand your use case for auto refresh better. Are you using the data viewer with Jupyter notebooks, debugging Python files or debugging #%%-formatted Python code cells in the interactive window? What workflows are auto refresh useful in for you?

In the meantime you may find the refresh button useful:

![image](https://user-images.githubusercontent.com/30305945/114148644-d807b200-98ce-11eb-9070-b4983a559047.png)

**Comment by Kugeleis** [comment]
Thanks for the fast reaction @joyceerhl. I installed just not the latest jupyter extension and found this refresh button & ctrl+R. I guess this solves 90% of my request. Autorefresh would be just some creme on top.
To answer your question: I use the data viewer with notebook.
