### ISSUE TITLE
Current interpreter cannot be changed and used for the interactive window

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5470]
Open workspace
Open py file with cells
Set interpreter
Run interactive window (it should use interpreter)
Change interpreter
Run interactive window

Kernel does not start with new interpreter. You have to reload to get it to work.

**Comment by DavidKutu** [comment]
IDK exactly what we want to happen, but if I leave the Interactive window open and change the interpreter, the interactive window stays with the same kernel. 

If I change the interpreter, close the interactive window, and run a cell again, the new Interactive Window is created with the selected interpreter.

**Comment by joyceerhl** [comment]
> If I change the interpreter, close the interactive window, and run a cell again, the new Interactive Window is created with the selected interpreter.

This is the desired behavior.
