### ISSUE TITLE
Native Notebooks: Exporting a notebook from interactive window does not maintain the background color

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5472]
It looks like this:

![image](https://user-images.githubusercontent.com/19672699/114215501-86851480-991a-11eb-9bb2-06a9d9b4f36e.png)

The reason seems to be the order of the output renderers cause it's picking the SVG one:

![image](https://user-images.githubusercontent.com/19672699/114215569-9866b780-991a-11eb-9447-4a727401964b.png)

**Comment by joyceerhl** [comment]
I think we'd need some way to specify a preferred renderer for a given output?

**Comment by joyceerhl** [comment]
PNG is preferred to SVG now, so this exact situation shouldn't be a problem anymore.
