### ISSUE TITLE
Add "Run Below" option to all cells in interactive mode

### ISSUE THREAD

**Issue by benlindsay** [microsoft/vscode-jupyter#5476]
I'm starting to use the interactive mode instead of pure jupyter lately and really liking it! One thing that I'd like to see is the ability to run all the cells above OR below a certain point. Right now, only the first cell lets you "Run Below".

![image](https://user-images.githubusercontent.com/9361152/114224656-f608fd00-9936-11eb-9b72-7c25f91b5c18.png)

I'd love to see something like

`Run Cell | Run Above | Run Below | Debug Cell`

for every cell except the top or bottom cells.

**Comment by claudiaregio** [comment]
Hi @benlindsay, thanks for your suggestion! Will discuss at the next triage meeting :)

**Comment by greazer** [comment]
@benlindsay, Thanks for the feedback. There's a setting to turn this on. 

See Jupyter: Code Lenses. 

Thanks!
