### ISSUE TITLE
Enable test for interactive window starting with active interpreter

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5478]
This requires changes to the Python API. For example if we want to test that the interactive window picks up the current active interpreter if it's changed without needing to reload VS Code, we need to add the ability to invoke the Python extension's python.setInterpreter command from the Jupyter extension (i.e. make the command handler accept an optional URI or PythonEnvironment).

**Comment by rchiodo** [comment]
Started on this here:
https://github.com/microsoft/vscode-jupyter/tree/rchiodo/interactive_test

Might need a command in VS code to focus an interactive window.
