### ISSUE TITLE
Increase icon size + improve ability to recognize icons in Jupyter extension

### ISSUE THREAD

**Issue by sayanfaraz** [microsoft/vscode-jupyter#5479]
Icons are currently very small and hard to discern what they represent because of their size and possibly because of the number of elements (lines, shapes, etc) in the icon. That means that a user might frequently have to hover over an icon to understand what it does. Attached are some screenshots of the icons I noticed. I'm wondering if it would be possible to increase the size of the icon / use thinner lines for the icons / simplify them for improved UX.

![image](https://user-images.githubusercontent.com/5562153/114254173-d47e3480-997b-11eb-801a-145d80cad054.png)

**Comment by joyceerhl** [comment]
Thanks for the feedback. We're changing several icons already, for example the variable explorer will be changed to 
![image](https://user-images.githubusercontent.com/30305945/114257095-89135880-9972-11eb-84f3-b7af3fdeeafb.png) and in the new native notebooks interface, clear cell outputs will be changed to 
![image](https://user-images.githubusercontent.com/30305945/114257201-ffb05600-9972-11eb-8daf-b81023f2dfd9.png)

We'll pass that feedback along regarding the export to Python script icon.

I'm wondering if the size of the icons we use should follow the `editor.fontSize` setting. That would let users configure how large the icons are, but it would potentially cause size mismatches with the rest of VS Code, which doesn't seem to use that setting for icons.

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
