### ISSUE TITLE
table of contents tab 

### ISSUE THREAD

**Issue by MohamedAliRashad** [microsoft/vscode-jupyter#5482]
Something as simple as this, to navigate through the notebook more efficiently.

![Screenshot from 2021-04-12 00-25-25](https://user-images.githubusercontent.com/26205298/114323479-b0f6ed80-9b25-11eb-8182-9e64bc48242c.png)

**Comment by claudiaregio** [comment]
Hi @MohamedAliRashad, we already have support for Table of Contents in VS Code Insiders. If you'd like you can give it a try by downloading it here: https://code.visualstudio.com/insiders/

Once you have it and download the Python extension, you'll want to make sure you have the file explorer open and click outline (sometimes it's hiding out at the bottom)
![image](https://user-images.githubusercontent.com/19276747/114331119-29df5080-9af8-11eb-8aef-4690871b7ff8.png)

**Comment by MohamedAliRashad** [comment]
Cool, I will wait for it to be added to the normal version of VS Code.
Thanks
