### ISSUE TITLE
Pressing escape twice  and  A or B adds cell to the top of the notebook

### ISSUE THREAD

**Issue by vivek-s** [microsoft/vscode-jupyter#5483]
Current behavior:
Press escape once from edit mode to leave edit mode but current cell is selected. 
Press escape second time and the whole document is selected. 
Press a or b -> adds a cell at the top of the note book.

Issue: 
I find this behavior annoying because I inadvertently press escape twice (especially with a theme where the highlight is not very pronounced) and press a/b to add a cell on top of the notebook instead of before/after the cell as I intended

Proposed behavior:
Keep the current cell selected even with multiple escape keys

**Comment by joyceerhl** [comment]
This should be solved in VS Code itself: https://github.com/microsoft/vscode/issues/121129

**Comment by IanMatthewHuff** [comment]
Resolved via https://github.com/microsoft/vscode/issues/121129
