### ISSUE TITLE
Gracefully handle exceptions in parsing in python version

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5486]
https://github.com/microsoft/vscode-python/issues/15926

We should contribute to Python extension if they are ready.

**Comment by joyceerhl** [comment]
No need to contribute to Python extension I think. Karthik has assigned microsoft/vscode-python#15926 to himself.

**Comment by DonJayamanne** [comment]
Yup, I had a chat with karthik about this and he's going to fix it upstream because they've been running into other issues in this space.

**Comment by IanMatthewHuff** [comment]
Validated. I had a specific issue with this on my Mac that's resolved now.
