### ISSUE TITLE
Python kept telling to reload

### ISSUE THREAD

**Issue by vjou** [microsoft/vscode-jupyter#5488]
Issue Type: <b>Bug</b>

My issue was fixed by downgrading Jupiter from 2021.5.xxx to 2021.3.684299474. This report is only asking fix to prevent the same issue in future.

I am using VSCode with remote login on a Linux machine from Windows 10 PC. Jupyter extension on the remote Linux somehow got the version 2021.5.xxx and VSCode on the local Windows PC had Jupytar 2021.3.684299474. Before I downgraded Jupyter, VSCode on the Linux machine kept telling to reload for Jupyter upgrade, probably, for Jupyter on the local Windows PC. On Windows, I could not find any upgrade of Jupyter for 2021.5.xxx. So, I downgraded Jupyter on the Linux machine, then, the issue was gone.

Actually, at the same time, a very similar issue happened with Hex Editor. Its version was 1.5.x on the Linux machine and 1.4.0 on the local Windows PC. This was also fixed by downgrading Hex Editor on the Linux machine. 

Extension version: 2021.3.684299474
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 3.10.0-957.21.3.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (22.64GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/yhojo/OneDrive%20-%20mdanderson.org/_TEMP/ms_exchange_server_access --crash-reporter-id 7935b450-09cd-4de2-8420-7aa95ff3842a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: x1prpprotons1_hplusqa|
|OS|Linux x64 3.10.0-957.21.3.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8268 CPU @ 2.90GHz (96 x 2900)|
|Memory (System)|187.19GB (43.83GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
openwslfolder:30282073
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by joyceerhl** [comment]
Thanks for filing a bug. It sounds like the VS Code install on your Linux machine was newer than the VS Code install on your local Windows machine. This would cause newer versions of the Jupyter extension to be available on the remote and not locally. Is it possible that you opted out of automatic upgrades to VS Code in your Windows machine's VS Code settings? 

Additionally, how was VS Code asking you to reload? Was there a popup asking you to reload, or was this just the message in the Extensions sidebar?

**Comment by vjou** [comment]
Thank you for your comment and you were right. I forgot that I had set Update: Mode to manual by myself. And, a popup showed up when I remote-logged in the Linux machine. After I updated VSCode to the latest version, all of the troubled extensions (Jupyter and Hex Editor on both of remote and local) were updated by themselves. All the issues including the popup are gone, thanks to your comment.

Now, I'd like to ask a couple of questions about VSCode update. I have never installed VSCode on the remote Linux machine. Actually, before updating VSCode, both of VSCodes (remote and local) showed the exactly same version information on Help --> About, as well as after VSCode update. It does not look like that I was looking at the version of remote VSCode. If another VSCode is running on the remote, I would like to ask to tell me how I can see the version of the remote VSCode and how I can change the update setting of the remote VSCode?

**Comment by joyceerhl** [comment]
From the info you provided I will assume that you are using the Remote-SSH extension in my explanation. When you use Remote-SSH to connect to your Linux machine for the first time, VS Code installs a copy of [VS Code Server](https://code.visualstudio.com/docs/remote/ssh#_what-are-the-connectivity-requirements-for-the-vs-code-server-when-it-is-running-on-a-remote-machine-vm) on your Linux machine. This is how you're able to interact with your remote filesystem while running the VS Code client on your local Windows machine.

![image](https://user-images.githubusercontent.com/30305945/114650570-541b4480-9c97-11eb-9dd7-282413b4b676.png)

More info: https://code.visualstudio.com/api/advanced-topics/remote-extensions

My guess is that the Remote-SSH extension does not enforce that the remote machine's copy of VS Code Server and the local machine's copies of VS Code are the same version, which seems like a bug. I do not work on the Remote-SSH extension, so you may have more luck getting an authoritative answer about how to check the version of the VS Code Server if you open an issue at https://github.com/microsoft/vscode-remote-release/issues/new?assignees=&labels=&template=bug_report.md

You can change the update setting on your remote machine by running the command 'Preferences: Open Remote Settings' in your VS Code command palette. This will open the settings that are specific to the remote machine.

Additionally you should be able to prevent this problem in future if you opt into [VS Code settings sync](https://code.visualstudio.com/docs/editor/settings-sync), which is supposed to ensure that the settings between your local and remote setup are synchronized. That is, if you opted out of VS Code updates locally, the remote should be automatically opted out of updates as well.

**Comment by vjou** [comment]
Thank you for your comprehensive explanation. I will try to dig around a little more according to your suggestions by myself.
