### ISSUE TITLE
Selected Kernel does not point to the right interpreter

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5489]
Originally reported by @muser840 
https://github.com/microsoft/vscode-jupyter/issues/5214#issuecomment-817510157

Just to confirm that Jupyter uses the wrong python, which is confirmed by
``` python
import sys
print(sys.executable)
! which python
```

For me the output of the above prints:
```
/usr/bin/python3
/home/user/venv/bin/python
```

It should be the same! These is some mess with switching between python versions by the extension. Somehow switching to old and already deleted environments make it work. That makes extension totally unusable...

The problem is present on versions:
v2021.5.702919634
v2021.6.732501275

update: sometimes it randomly starts to work...

**Comment by DonJayamanne** [comment]
@muser840

Please could you provide the following information:
-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by bardal** [comment]
I think I see the same issue:

Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 6.1.7601
Jupyter Extension : v2021.5.745244803
Python 3.8.6 64-bit
Environment: venv

With venv selected - Jupyter Notebook output:
import sys
print(sys.version)
print(sys.executable)
3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
C:\Program Files\Python38\python.exe

Command line - same venv activated:
(reporting-env) D:\projects\utils>python
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.executable)
D:\projects\reporting-env\Scripts\python.exe

**Comment by DonJayamanne** [comment]
@bardal Thanks for the feedback:
* Are you using notebooks or interactive window?
* Please could you re-load VS Code, run the same code in a cell and prvide the following:
	* Cell Output
	* Output from the `Jupyter` output panel (you might have to copy th eoutput to a text file & upload that text file)
	* What kernel did you pick (i.e. what were you expecting to see)
	* Screenshots 
		* 	With the cell output 
		* With the kernel displayed in the bottom right


I'm sorry you're running into this and would appreciate the replying with the above info, I'd like to unblock you and others running into this.

**Comment by bardal** [comment]
I am loading a .ipynb in Visual Studio Code - not sure if that means notebooks or interactive window!

Jupyter Cell:
import sys
print(sys.version)
print(sys.executable)

3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] 
C:\Program Files\Python38\python.exe

I selected reporting_env as the kernel

Screenshot and Jupyter output panel screenshot:

![jupyter screenshot](https://user-images.githubusercontent.com/5731730/115953595-57f36600-a4e4-11eb-9594-1032effc92e6.png)

[jupyter_log.txt](https://github.com/microsoft/vscode-jupyter/files/6369287/jupyter_log.txt)

**Comment by DonJayamanne** [comment]
Thanks for the information,
Is `reporting_env` a conda environment?

**Comment by bardal** [comment]
reporting_env is a standard Python venv (not conda).

**Comment by DonJayamanne** [comment]
@bardal Thanks for the information
Please could you do me yet another favor:
* Please install VS Code  Insiders
* Install the Jupyter extension
* Open the same notebook and try this agaon
* Once again, please provide the logs & the screenshot.

FYI - In VS Code Insiders, you'll get the new Notebook UI & I believe this has been resolved there (See here for more information https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/).

Thanks again for your help.

**Comment by DonJayamanne** [comment]
Thanks for providing the information.

**Comment by bardal** [comment]
Unfortunately this is on a work PC so I won't be able to install VS Code
Insiders.

**Comment by DavidKutu** [comment]
Still reproes
![image](https://user-images.githubusercontent.com/20347396/120561881-39716c00-c3ba-11eb-893a-142ea01d30a5.png)

**Comment by IanMatthewHuff** [comment]
Validated. Lots of different ways to set up environments, but works with my venv.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/7cfbbda9-2278-449b-a1c3-d25c179a484c)
