### ISSUE TITLE
Interpreter information stored in kernelspec not used when starting Kernels

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5495]
* Select kernel pointing to virtual env
* Run kenrel & it points to something else

I've been using this notebook & kernel for months.
Kernel has been around for almost a year.
For some reason now its not getting picked

**Comment by DonJayamanne** [comment]
Assigning to myself to identify the cause.

**Comment by dgerzhoy** [comment]
I've found this same thing happening to me. It defaults to an environment that doesn't have IPython installed, and fails, even though I have the correct environment selected (and run) in the workspace.

If this tidbit helps: I am able to go into htop and kill all the processes related to vscode, and then when I restart vscode, it works again.

(I am running the notebook on linux, through vscode remote from a windows laptop)

**Comment by DonJayamanne** [comment]
@dgerzhoy Please could you install the latest VS Code Insiders, then yo'ull automatically get a version of the Jupyter extesnion with the latest build bits. If you cannot repro it there then it means it has been fixed, else you're experiencing a whole new issue, which means its time to (please) create a seprate issue.

**Comment by rchiodo** [comment]
Seems to be validated.
