### ISSUE TITLE
Commands `runallcellsabove` and `runcellandallbelow` don't use the selected kernel.

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode-jupyter#5497]
## Environment data

[Window Title]
Visual Studio Code - Insiders

[Main Instruction]
Visual Studio Code - Insiders

[Content]

Version: 1.56.0-insider (user setup)
Commit: 01466cf692c3e54f0eeb82ef0539a42391f185de
Date: 2021-04-12T05:17:32.143Z (14 hrs ago)
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

[OK] [Copy]

Jupyter extension version v2021.6.740555125

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Install the .NET Interactive extension.
2. Create a new notebook and select the .NET Interactive kernel.
3. Add two `C# (.NET Interactive)` cells with the contents `Console.WriteLine(1);` and `Console.WriteLine(2);`.
4. In the first cell, click the "Run cell and below" button.

EXPECTED:
The bottom cell should be executed with the .NET Interactive kernel.

ACTUAL:
The Python kernel is invoked and it appropriately fails because it was passed C# syntax.  Note that executing each individual cell directly works as expected.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Info 2021-04-12 13:19:27: Cell Index:0, state:1, exec: undefined. User queued cell for execution
Info 2021-04-12 13:19:27: Cell Index:1, state:1, exec: undefined. User queued cell for execution
Info 2021-04-12 13:19:27: Cell Index:0, state:1, exec: undefined. Update cell state as it was enqueued
Info 2021-04-12 13:19:27: Cell Index:0, state:1, exec: undefined. Ready to execute
Info 2021-04-12 13:19:27: Cell Index:1, state:1, exec: undefined. Ready to execute
Info 2021-04-12 13:19:27: Cell Index:0, state:1, exec: undefined. Before Execute individual cell
Info 2021-04-12 13:19:27: Cell Index:0, state:1, exec: undefined. Start execution
Info 2021-04-12 13:19:27: Cell Index:0, state:3, exec: undefined. Send code for execution
Info 2021-04-12 13:19:27: Cell Index:0, state:3, exec: undefined. Wait for jupyter execution
Info 2021-04-12 13:19:27: Cell Index:1, state:2, exec: undefined. Update cell state as it was enqueued
Info 2021-04-12 13:19:27: Cell Index:0, state:3, exec: undefined. Kernel switching to busy
Info 2021-04-12 13:19:27: Notebook Session status untitled:Untitled-1.ipynb # Busy
Info 2021-04-12 13:19:27: Cell Index:0, state:3, exec: undefined. Update output
Info 2021-04-12 13:19:27: Cell Index:0, state:3, exec: 3. Kernel switching to idle
Info 2021-04-12 13:19:27: Cell Index:0, state:3, exec: 3. Jupyter execution completed
Info 2021-04-12 13:19:27: Cell Index:0, state:3, exec: 3. Completed successfully
Info 2021-04-12 13:19:27: Notebook Session status untitled:Untitled-1.ipynb # Idle
Info 2021-04-12 13:19:27: Cell Index:0, state:3, exec: 3. Update cell state 4 and message 'NameError: name 'Console' is not defined'
Info 2021-04-12 13:19:27: Cell Index:0, state:3, exec: 3. Completed successfully & resolving
Info 2021-04-12 13:19:27: Cell Index:0, state:3, exec: 3. After Execute individual cell 4
Info 2021-04-12 13:19:27: Cancel all remaining cells true || 4
Info 2021-04-12 13:19:27: Cancel pending cells
Info 2021-04-12 13:19:27: Cell Index:1, state:2, exec: undefined. Execution cancelled
Info 2021-04-12 13:19:27: Cell Index:0, state:3, exec: 3. Executed successfully in executeCell
Info 2021-04-12 13:19:27: Cell Index:1, state:2, exec: undefined. Completed due to cancellation
Info 2021-04-12 13:19:27: Cell Index:1, state:2, exec: undefined. Update cell status as idle and message as empty
Info 2021-04-12 13:19:27: Cell Index:0, state:3, exec: 3. Execution disposed
Info 2021-04-12 13:19:27: Cell Index:1, state:2, exec: undefined. Cell cancelled & resolving
Info 2021-04-12 13:19:27: Cell Index:1, state:2, exec: undefined. Execution disposed
Info 2021-04-12 13:19:28: Trusting notebook...
```

</p>
</details>

**Comment by joyceerhl** [comment]
The root cause is that `onDidChangeActiveNotebookKernel` does not fire when we switch to a .NET Interactive kernel (I suspect this may be true for all 3rd party kernels). So our kernelProvider thinks the .NET Interactive notebook is still connected to the original Python kernel, and this call here returns the Python kernel instead of the selected 3rd party one:
https://github.com/microsoft/vscode-jupyter/blob/827750c6798fccb558a6bbaf5897d3525b2117ab/src/client/datascience/jupyter/kernels/kernelProvider.ts#L47-L49

**Comment by joyceerhl** [comment]
This is resolved now that VS Code has implemented run above/below in core.
