### ISSUE TITLE
Jupyter notebook not connecting to kernel

### ISSUE THREAD

**Issue by manishrw** [microsoft/vscode-jupyter#550]
Issue Type: <b>Bug</b>

Unable to start session for kernel Python 3.8.5 64-bit ('rait_env': conda). Select another kernel to launch with.

This is the error I get while connecting to jupyter notebook. It was working before this VS code version / this python extension version.

Extension version: 2020.8.106424
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Honghe** [comment]
> I've started experiencing experiencing a similar issue in the last few days. Bumping up the logging verbosity revealed the following error details for me:
> 
> ```
> {"jsonrpc": "2.0", "method": "output", "params": {"source": "stderr", "out": "ValueError: Invalid Signature: b'c4c679719d5545f008ddb84d858dd45780c7d50f6570ee9a7ef2ce57494ae904'\n"}}
> Error 2020-09-06 23:22:52: Kernel died [r [Error]: [IPKernelApp] ERROR | Invalid Message
> 
> 	at t._next ~/.vscode/extensions/ms-python.python-2020.8.106424/out/client/extension.js:54:782299)
> 	
> ...snip... 
> 
> Info 2020-09-06 23:22:52: Python Daemon (pid: 20538): write to stderr:   File "~/.local/share/virtualenvs/staying-up-to-date-explorable-wnFYf23f/lib/python3.7/site-packages/jupyter_client/session.py", line 927, in deserialize
> 
> Info 2020-09-06 23:22:52: Python Daemon (pid: 20538): write to stderr:     raise ValueError("Invalid Signature: %r" % signature)
> 
> Info 2020-09-06 23:22:52: Python Daemon (pid: 20538): write to stderr: ValueError: Invalid Signature: 
> ```
> 
> Trawling though my `Pipfile.lock` I noticed that `traitlets` had been upgraded from `4.3.3` to `5.0.3`. (`traitlets` seems to be a dependency of `jupyter-core`)
> 
> Reverting to `traitlets==4.3.3` resolved the problem for me

Where to view the logs?
