### ISSUE TITLE
Add better logging for modules installed/not installed

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5502]
@DonJayamanne commented on [Mon Apr 12 2021](https://github.com/microsoft/vscode-python/issues/15933)

When installing ipykernel we've found that plenty of users do not install ipykernel.
I believe this is because pip/conda doesn't exist on the user machines.

Suggestion is to add better logging to track this (part of the Jupyter extension OKR to improve kernel startup).

**Requirements:**
* When a package is not installed log why it was not installed, today we don't know whether its because pip is missing or installation actually failed.

**Comment by DonJayamanne** [comment]
Upstream issue with better logging/telemetry https://github.com/microsoft/vscode-python/issues/15933

**Comment by joyceerhl** [comment]
Literally just ran into this in Codespaces. Tried to open an interactive window, Jupyter extension prompted me to install ipykernel, install failed because I needed to run these commands first:

```
sudo apt-get update
sudo apt install python3-pip
```

**Comment by DonJayamanne** [comment]
@joyceerhl this might help https://github.com/microsoft/vscode-python/issues/15937

**Comment by DonJayamanne** [comment]
Changes have been added to Python extension

**Comment by IanMatthewHuff** [comment]
Validated. I can see the new message on #6194.
