### ISSUE TITLE
"find in selection" for notebook

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [microsoft/vscode-jupyter#5508]
Issue Type: <b>Feature Request</b>

Hope to use "find in selection" function in notebooks.

Extension version: 2021.5.743038836-dev
VS Code version: Code - Insiders 1.56.0-insider (48387dfc3d691558404cff1ea2582e3862a40080, 2021-04-13T05:15:44.407Z)
OS version: Linux x64 5.11.0-13-generic

**Comment by IanMatthewHuff** [comment]
I do repro this as well. However with the new Native Notebook UI this search / find UI is controlled by core VS Code, not the Jupyter extension. I'm going to transfer this issue to their repo.

**Comment by IanMatthewHuff** [comment]
Issue moved to [microsoft/vscode #121218](https://github.com/microsoft/vscode/issues/121218) via [**ZenHub**](https://www.zenhub.com/)
