### ISSUE TITLE
Better telemetry when interpreter doesn't match the kernel

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5509]
We track this today, but we don't know if:
* User ran a cell
* Whether its notebook or interactive or native or custom, etc...

Basically we don't have a lot of information we have with other events.
Using the existing infrastructure for this.

**Comment by IanMatthewHuff** [comment]
I don't have a specific repro for this, but validating on the implementation of the telemetry event.
