### ISSUE TITLE
Latex not rendering in markdown cells

### ISSUE THREAD

**Issue by AndyPietr** [microsoft/vscode-jupyter#5513]
Brilliant update, finally it look very nice, But even simplest latex equations don't appear

**Comment by joyceerhl** [comment]
@AndyPietr We're working on better LaTeX support for our new native notebooks interface, which I am assuming you are currently using in stable VS Code. Please try adding the following experimental setting to your user settings.json to opt into initial LaTeX support:

>   "notebook.experimental.useMarkdownRenderer": true,

Please also let us know if there are any specific equations that don't work after you have that setting enabled.

**Comment by AndyPietr** [comment]
Worked just fine, thanks @joyceerhl
