### ISSUE TITLE
Native notebook puts a squiggle on all the text of a cell for errors

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#5514]
![image](https://user-images.githubusercontent.com/812783/114618841-b015a700-9c5e-11eb-8eab-b2251b6e66a8.png)

The red squiggle takes up all the text above the error in the line. Reproed with different language servers for me.

**Comment by rchiodo** [comment]
Maybe the newline is missing in the text sent to pylance?

**Comment by greazer** [comment]
I think this has been resolved.
