### ISSUE TITLE
Restore the 'Ensure prompt is displayed when ipykernel module is not found' test

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5517]
https://github.com/microsoft/vscode-jupyter/pull/5511/files#r612852141
Not sure why it was skipped.
Any idea @IanMatthewHuff

**Comment by IanMatthewHuff** [comment]
Comment added on the PR comment.

**Comment by DonJayamanne** [comment]
Not required, as we don;t display prompts for installing ipykenel in remote, no way to know
