### ISSUE TITLE
Cannot uninstall 'Jupyter' extension. 'Python' extension depends on this.

### ISSUE THREAD

**Issue by lazarillo** [microsoft/vscode-jupyter#5520]
## Environment data

-   VS Code version: 1.55.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.745244803
-   Python Extension version (available under the Extensions sidebar): v2021.3.680753044
-   OS (Windows | Mac | Linux distro) and version: Mac 11.2.3
-   Python and/or Anaconda version: 3.9.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

Can uninstall Jupyter without having to uninstall other extensions... notably the `Python` extension, which I still very much want.

## Actual behaviour

When attempting to uninstall, I got the error message in the title and repeated below:

```Cannot uninstall 'Jupyter' extension. 'Python' extension depends on this.```

## Steps to reproduce:

1. Install the Python extension on VS Code
2. Install the Jupyter extension
3. Attempt to uninstall the Jupyter extension

(I confess, I am not sure if this is all that is required.  I have been using VS Code with both installed for over a year.  But Jupyter started causing problems with the IDE, so I wanted to uninstall it.)

## Logs

I have no log for the attempt to uninstall... there is no log, just the dialog box.  However, below is a log for the Python extension hanging, for reasons which I think are due to the Jupyter extension not loading properly.

Regardless, I would still like to be able to remove the Jupyter extension without removing the Python extension.  It seems that *Jupyter should rely upon Python*, not vice-versa.

File: `ms-python.python-unresponsive.cpuprofile.txt`

```
{
    "nodes": [
        {
            "id": 1,
            "callFrame": {
                "functionName": "(root)",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                2
            ]
        },
        {
            "id": 2,
            "callFrame": {
                "functionName": "processTicksAndRejections",
                "scriptId": "22",
                "url": "internal/process/task_queues.js",
                "lineNumber": 68,
                "columnNumber": 34
            },
            "hitCount": 0,
            "children": [
                3
            ]
        },
        {
            "id": 3,
            "callFrame": {
                "functionName": "runMicrotasks",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                4
            ]
        },
        {
            "id": 4,
            "callFrame": {
                "functionName": "iterEnvs",
                "scriptId": "463",
                "url": "file:///Users/mikewilliamson/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js",
                "lineNumber": 8,
                "columnNumber": 362633
            },
            "hitCount": 0,
            "children": [
                5
            ]
        },
        {
            "id": 5,
            "callFrame": {
                "functionName": "doIterEnvs",
                "scriptId": "463",
                "url": "file:///Users/mikewilliamson/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js",
                "lineNumber": 60,
                "columnNumber": 757453
            },
            "hitCount": 0,
            "children": [
                6
            ]
        },
        {
            "id": 6,
            "callFrame": {
                "functionName": "iterFromCache",
                "scriptId": "463",
                "url": "file:///Users/mikewilliamson/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js",
                "lineNumber": 60,
                "columnNumber": 758456
            },
            "hitCount": 0,
            "children": [
                7
            ]
        },
        {
            "id": 7,
            "callFrame": {
                "functionName": "t.getQueryFilter",
                "scriptId": "463",
                "url": "file:///Users/mikewilliamson/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js",
                "lineNumber": 8,
                "columnNumber": 241000
            },
            "hitCount": 0,
            "children": [
                8
            ]
        },
        {
            "id": 8,
            "callFrame": {
                "functionName": "",
                "scriptId": "463",
                "url": "file:///Users/mikewilliamson/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js",
                "lineNumber": 8,
                "columnNumber": 241199
            },
            "hitCount": 0,
            "children": [
                9
            ]
        },
        {
            "id": 9,
            "callFrame": {
                "functionName": "",
                "scriptId": "463",
                "url": "file:///Users/mikewilliamson/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js",
                "lineNumber": 8,
                "columnNumber": 241322
            },
            "hitCount": 37875,
            "positionTicks": [
                {
                    "line": 9,
                    "ticks": 37875
                }
            ]
        }
    ],
    "startTime": 21959870208,
    "endTime": 21965152805,
    "samples": [
        9,
        9,
        9,
```
.
.
.
```
        144,
        134,
        76
    ]
}
```

(The file is 75_890 lines long; all the missing lines just have some arbitrary sample number.)

**Comment by rchiodo** [comment]
Thanks for the suggestion. This is actually on purpose as the Python extension relies on code in the Jupyter extension for some of its functionality.

Do you have any more information on the problems the Jupyter extension caused?

**Comment by Alexey-Kamenev** [comment]
I'm also having all sorts of issues with Jupyter extension, from being too slow to issues with keyboard navigation, diffs not working and so on.
The only way to disable Jupyter extension that I've found so far is to install Python extension version just before Jupyter functionality was refactored into a separate extension.
Click "Install Another Version..." in Python extension and choose `2020.10.332292344` version.
After installation, you should be able to uninstall Jupyter extension just fine.
It's also a good idea to disable Jupyter in settings, something like:
```
    "python.dataScience.disableJupyterAutoStart": true,
    "python.dataScience.useNotebookEditor": false
```
This worked well for me even at the cost of not having the latest version of Python extension.

It would be great if Python/Jupyter extensions authors consider reversing the dependency so the Python extension won't depend on the Jupyter one anymore.

**Comment by lazarillo** [comment]
Hi @rchiodo , sorry, I had not noticed your original response.  What sort of information do you need from me?  What would be helpful?

Unfortunately, I cannot easily separate how Jupyter is slowing things down, except to say that VS Code used to run quite a bit faster before this update.  I cannot even say that Jupyter is to blame.  But it is still nice to be able to separate the installs.

I suspect that >50% of the Python users are not Jupyter users.  I am a data scientist, and as such, I use Jupyter quite a bit.  But I am now on a long term task using no data science or ad hoc analysis work.  Therefore, I wanted to remove Jupyter.  I have to imagine there are many people like myself.  I generally try to minimize cruft and avoid anything I do not need, to keep my machine running fast and with more memory available.

**Comment by rchiodo** [comment]
If you suspect the jupyter extension is slowing down something inside of VS code you can capture a trace of what's slow using the 'Running Extensions' window in VS code:

It looks like this:

![image](https://user-images.githubusercontent.com/19672699/117037715-a4485e00-acbb-11eb-89e6-f4b40eb7dfa2.png)

If you click on the little black circle, it will capture a perf trace. 

After that's done it should like this (well for the Jupyter Extension)

![image](https://user-images.githubusercontent.com/19672699/117037813-c3df8680-acbb-11eb-8897-436bdbcd8a0b.png)

If the Jupyter extension has a lot of CPU time listed there, you can then click the save button

![image](https://user-images.githubusercontent.com/19672699/117037909-e2458200-acbb-11eb-9832-f52a21eb7c77.png)

And upload the CPU profile to this issue. 

Something might be running but it shouldn't be if your just doing python work. We do activate and listen for python files (so we can add these code lenses)
![image](https://user-images.githubusercontent.com/19672699/117038064-0f923000-acbc-11eb-8abe-696a85d02359.png)

That could be slowing down the opening of a python file.

Other than that, there should be very minimal overhead.

**Comment by lazarillo** [comment]
Thanks, @rchiodo !  I guess I cannot really do this until I see it acting very slowly.  I will try to capture this and post it when I have the opportunity.  Hopefully it won't take too long.

I really appreciate your detailed explanation for how to pull the perf data.  :-)

**Comment by drproteus** [comment]
> This is actually on purpose as the Python extension relies on code in the Jupyter extension for some of its functionality.

Is there room for an alternative implementation, even if not entirely DRY (in which case, fork/opt-in/etc.)? Not to fix what ain't broke, but it feels like a _particularly_ inverted dependency.

**Comment by rchiodo** [comment]
It's actually circular the moment. The jupyter extension depends upon the python extension when starting python based kernels. The python extension depends upon the jupyter extension for some of it's data viewing features. 

We're unlikely to change this dependency because it's not really worth the effort (making a 3rd npm module or extension for the dataviewing part). The python extension is however in the process of removing the hard dependency. It should become optional in the near future.

**Comment by greazer** [comment]
Jupyter is now uninstallable after installing Python.
