### ISSUE TITLE
Native Notebooks: Why does cell status bar say "Ctrl+Alt+Enter" to run cell...

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#5522]
For Jupyter notebooks, it should not say this.

**Comment by joyceerhl** [comment]
This is upstream, we don't contribute this tip.

**Comment by claudiaregio** [comment]
I believe I mentioned this to Peng in another issue, if it could be written in such a way where it could display something different based on the extension shortcut let me see if I can find it..

**Comment by claudiaregio** [comment]
I can't seem to find the comment on the PR where I requested it be dynamic but I filed an issue for it in the vs code repo: https://github.com/microsoft/vscode/issues/121558

**Comment by claudiaregio** [comment]
This appears to be fixed in insiders! 

![image](https://user-images.githubusercontent.com/19276747/115272419-3add2280-a0f3-11eb-84df-f93d76d4ca2b.png)
