### ISSUE TITLE
IPyWidgets do not display in split views of Native Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5523]
* Open notebook A
* Run a cell with widgets
* Split notebook
* Run cell again, no widgets displayed in the second split view.

I'm certain this used to work, either way its an easy fix.

**Comment by joyceerhl** [comment]
Validated. Note initially the output isn't visible in the second notebook; I have to actually rerun it there for the widgets to show.
![image](https://user-images.githubusercontent.com/30305945/118432023-6fa9ae80-b68c-11eb-8afa-2ca677d62fe5.png)

**Comment by DonJayamanne** [comment]
Can be fixed for IPyWidgets 8 (by requesting the widget state, latest version of IPyWidgets 7 might also have the same protocol message to fix this)
