### ISSUE TITLE
Kernel Froze and lost all work

### ISSUE THREAD

**Issue by JacobRColp** [microsoft/vscode-jupyter#5526]
My kernal froze and upon restart - I had lost all work. I had saved the workbook a few times, but it seems to have erased when I reopened.

**Comment by claudiaregio** [comment]
@JacobRColp Sorry to hear you lost some work! Could you fill out the issue template regarding machine information to help us try to troubleshoot? If you run into this issue again it's really helpful to have the logs. 



## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A



## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by greazer** [comment]
Issues labeled with "Info needed" are closed if we do not receive more information from the issue author in 2 weeks. If you are the issue author and you still are running into this problem, please reactivate with additional information.
