### ISSUE TITLE
Revert to a  simpler FileSystem API provider

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5531]
Looks like core team is making changes to FS code that we inherited.
A lot of changes have been made since we forked.
I think we should just go back to what it was earlier (that's basically what's been happening over time & with the recent changes in core extension as well).

**Comment by rchiodo** [comment]
Not sure we need to do anything here? Are you suggesting we skip using node to do any file reading and just use the vs code file system?

Looking at the current python implementation, it's almost identical to our own. Closing for now.
