### ISSUE TITLE
Jupyter Notebook UI wont update to the new UI

### ISSUE THREAD

**Issue by TheTrice** [microsoft/vscode-jupyter#5534]
The UI for my notebook is still old, I even tried to uninstall extension and even VSCode itself and still same old UI:

## Environment data

-   VS Code version: 1.55.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.745244803
-   Python Extension version (available under the Extensions sidebar): v2021.3.680753044
-   OS (Windows | Mac | Linux distro) and version: Windows 10 , Mac OS BigSur 11.2.3 and Ubuntu 20.04
-   Python and/or Anaconda version: 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

![image](https://user-images.githubusercontent.com/75177440/115060164-d732d980-9ee7-11eb-861d-d060d4735ae2.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/75177440/115060054-ae124900-9ee7-11eb-95db-e3a5f7856fa5.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. 

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by claudiaregio** [comment]
Hi @TheTrice, currently the new Native Notebooks UI is only available in VS Code Insiders by default. Those who are seeing the new UI in the stable version are currently in an experiment. If you would like to try out our new Native Notebook experience, please download it here: https://code.visualstudio.com/insiders/
