### ISSUE TITLE
Too many flake tests failing

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#5535]
Almost every single run for the last week or so has failing tests in it.

Kernel starting
Notebook restarting with same kernel
Interrupt 

Seem to be three of the main culprits. Marking as high priority as we can't PR and release confidently in this state.

**Comment by DonJayamanne** [comment]
Hmm, are these flaky or always failing.
These didn't seem to fall last week or earlier.

**Comment by IanMatthewHuff** [comment]
Not sure how far back they started failing (is there a way to see test history? Used to be able to see that in AzDO) but all of these tests were failing at least once in the two runs before the breaking changes.

https://github.com/microsoft/vscode-jupyter/runs/2356143894?check_suite_focus=true
https://github.com/microsoft/vscode-jupyter/runs/2351318190?check_suite_focus=true

I actually don't mind driving this after the kernel push stuff, but it's not good. I just took a look and the last fully green 'Build and Test' run that I see (excluding runs in or targeting the release branch) was eight days ago. Over a week since the last all green PR run.

https://github.com/microsoft/vscode-jupyter/actions/runs/731108365

**Comment by DonJayamanne** [comment]
Oh no not implying that the recent changes broke the tests.
Agreed, we should get them green, end this is how we'll send up back to where we were until early this year, constantly having flaky tests

**Comment by IanMatthewHuff** [comment]
Ohh, I'm not worried about what change caused it (looking now my change might have caused a different new failure). Just mentioning that I'm unsure of when things started to flake, and expressing that I want to get it cleaned up so that we are pushing green. Red gets momentum, something starts to fail, we push anyways, we see the previous failure and push over it again. I do it plenty myself. Gotta get strict with myself.

**Comment by IanMatthewHuff** [comment]
We are still cleaning up a few tests, but I believe the above listed ones are all green. Validated.
