### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by mpr119** [microsoft/vscode-jupyter#5538]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.5.702919634`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.55.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by claudiaregio** [comment]
Hi @mpr119 Could you please provide some additional details on the issue you are experiencing? 
Helpful information includes steps to reproduce, expected behavior vs. actual behavior, pictures or screen recordings when applicable. (https://www.screentogif.com)
