### ISSUE TITLE
The tensorboad feature doesn't work -- just displays an empty white pane.

### ISSUE THREAD

**Issue by tsbertalan** [microsoft/vscode-jupyter#5540]
Issue Type: <b>Bug</b>

Install the Python, Pylance, and Jupyter plugins locally and in a SSH remote. Execute the "launch tensorboard" command+shift+p action. Observe a new empty-white tab.

Extension version: 2021.5.745244803
VS Code version: Code 1.55.2 (Universal) (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.4.0-70-generic
Remote OS version: Linux x64 4.15.0-139-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 6, 4|
|Memory (System)|4.00GB (0.26GB free)|
|Process Argv|-psn_0_12926035 --crash-reporter-id 973e9aaf-42b4-452a-bfdc-42299fec4a48|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ygk.vpn.tomsb.net|
|OS|Linux x64 5.4.0-70-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-1660 v4 @ 3.20GHz (16 x 1197)|
|Memory (System)|62.55GB (18.56GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sigurd.vpn.tomsb.net|
|OS|Linux x64 4.15.0-139-generic|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 1749)|
|Memory (System)|31.17GB (0.48GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
openwsldoc:30282072
vspre833:30267464
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by joyceerhl** [comment]
@tsbertalan If you manually configure a port forward for the port that TensorBoard is running on (usually it's 6006), does the feature now work? If so, you're likely encountering https://github.com/microsoft/vscode-python/issues/15807. Hopefully that unblocks you for now while we work on a fix. Apologies for the trouble!

**Comment by joyceerhl** [comment]
I believe I have a fix for this in https://github.com/microsoft/vscode-python/pull/16005 and am closing this issue in favor of https://github.com/microsoft/vscode-python/issues/15807. @tsbertalan Would you mind trying a preview build out and letting me know whether it works for you please? Here's the link to download the Python extension VSIX: https://github.com/microsoft/vscode-python/suites/2544957777/artifacts/55288471  Thanks so much for your patience!
