### ISSUE TITLE
Native Notebooks - Duplicate Error Information

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5541]
Every time I get an error I see the error both in the output and the cell status bar. Personally don't find it necessary to have this information duplicated. 

Can we keep the red x in the cell status bar (in case output is collapsed) but remove the duplication of the text? Not to mention when the text is really long it just disappears off the cell status bar and becomes somewhat unhelpful since you can't scroll to process it all anyway. 

![image](https://user-images.githubusercontent.com/19276747/115125385-989b2e80-9f7c-11eb-91af-5a9e99432c53.png)

**Comment by DonJayamanne** [comment]
This is what was originally requested by the PMs (discussion on teams).
Happy to change again

**Comment by joyceerhl** [comment]
Validated 
![image](https://user-images.githubusercontent.com/30305945/116750117-d6557980-a9b6-11eb-8b1a-52cdfe2ccecb.png)
