### ISSUE TITLE
Kernel picker shows Interpreter instead of selected kernel (as shown in the toolbar)

### ISSUE THREAD

**Issue by umeshk-unnik** [microsoft/vscode-jupyter#5543]
## Environment data

-   VS Code version: 1.55.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.745244803
-   Python Extension version (available under the Extensions sidebar): v2021.3.680753044
-   OS (Windows | Mac | Linux distro) and version: Windows 10 20H2
-   Python and/or Anaconda version: Python 3.6.8 (64 bit)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): NA
-   Jupyter server running: Local | Remote | N/A NA

## Expected behaviour

The top right hand section should show 3.6.8 (64 bit)

## Actual behaviour

The top right hand section shows 3.7.4 (32 bit)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open a ipynb and let it load. The section shows 3.7.4 (32 bit)

we require Python versions older than 3.7 and of 64 bit to run Deep Learning and OpenCV libraries. But after a recent update, I’ve found that the selected kernel is shown as 3.7.4 (32 bit) in the upper right corner. However when an attempt is made to change the kernel by selecting it, it shows that the current one is 3.6.8 (64 bit) “as it should be”. Seems like it is showing the topmost option out of all available kernels.

![Microsoft_Bug_VSCode_kernel](https://user-images.githubusercontent.com/70807385/115160260-021e5880-a0b5-11eb-809b-7d9aff47589a.jpg)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DavidKutu** [comment]
Thanks for the issue @umeshk-unnik. I'm not able to repro, but does this happen to you with only that notebook? Or does it happen constantly?

**Comment by umeshk-unnik** [comment]
> Thanks for the issue @umeshk-unnik. I'm not able to repro, but does this happen to you with only that notebook? Or does it happen constantly?

Hi David, The issue persists, also it is the case in every notebook. Would also like to add that this started happening after 2 events a few weeks back:
1. I installed 'black' Python Code formatter plugin.
2. There was a VSCode update in the near vicinity. 

So one or both of the above might be causing the issue. I tried a pip uninstall on 'black', it keeps the kernel busy and that's bout it. This could have been in the early days of April though not sure of the exact day.

Well that's that. Stay Awesome

**Comment by DavidKutu** [comment]
Thanks @umeshk-unnik. I've got one more thing to ask of you to look for a solution. Please set this setting:
`"jupyter.logging.level": "debug"`
Then repro your issue again, and finally share the content on the output panel (In the `Jupyter` dropdown).

**Comment by umeshk-unnik** [comment]
The screen grabs are attached below after applying the suggested settings.  Seems like it is showing 3.7.4 32 bit instead of 3.6.8 64 bit because of the values set in the associated kernel.json. 
![kerneljsonmoddate](https://user-images.githubusercontent.com/70807385/115908256-8f7ff500-a487-11eb-85ce-e8f916cbfd79.jpg)
![KernelNameSpecFile](https://user-images.githubusercontent.com/70807385/115908267-93ac1280-a487-11eb-9d06-9433ae6ff52c.jpg)
![Python_Kernel_json_issue](https://user-images.githubusercontent.com/70807385/115908386-bb02df80-a487-11eb-8cd5-497498e77f9a.jpg)

**Comment by DavidKutu** [comment]
Its possible that the display name on the kernel is wrong, it is on a folder called `python36`.
Is that kernel using the same `Python 3.6.8 64-bit` that is your interpreter at the bottom right?

**Comment by DavidKutu** [comment]
Here's a suggestion @umeshk-unnik. Please try moving that `python374...` kernel to another folder so that the extension doesn't find it. Then open vscode and on your notebook try selecting your desired kernel on the top right.

Let me know if that fixes it. If it does, maybe we misnamed the `python374...` kernel.

**Comment by umeshk-unnik** [comment]
> Its possible that the display name on the kernel is wrong, it is on a folder called `python36`.
> Is that kernel using the same `Python 3.6.8 64-bit` that is your interpreter at the bottom right?

Yes, the same folder holds the libraries for the `Python 3.6.8 64-bit` kernel and it is the one selected (as I have specified it as the default kernel for the entire workspace). It is also the one that runs. It is just that the kernel.json settings like display name, name and specFile are erroneously set by the process that sets them and that's what needs to be apparently rectified.

**Comment by umeshk-unnik** [comment]
> Here's a suggestion @umeshk-unnik. Please try moving that `python374...` kernel to another folder so that the extension doesn't find it. Then open vscode and on your notebook try selecting your desired kernel on the top right.
> 
> Let me know if that fixes it. If it does, maybe we misnamed the `python374...` kernel.

Well, I renamed the display name and it reflects in the ipynb. However as you suggested, when I remove the entire folder containing the kernel.json file (viz. python374.....), all faults seem to be rectified. The notebook runs perfectly like the good ol' times (with the correct indications). 

The files in the Roaming folder seem to be an issue. They mess up the kernel display as well as the options loaded in the kernel selection dropdown as far as I saw. Attaching screen grabs for your reference.... 

![FolderRemovalFromRoaming](https://user-images.githubusercontent.com/70807385/115960928-c0b4ff80-a531-11eb-8e82-d9e3111174aa.jpg)
![VoodooInNotebook](https://user-images.githubusercontent.com/70807385/115960932-c4e11d00-a531-11eb-91c9-94a1cd0dab6c.jpg)
![VoodooInKernelJSON](https://user-images.githubusercontent.com/70807385/115960935-c6aae080-a531-11eb-8eee-05afbbff4d63.jpg)

**Comment by DavidKutu** [comment]
I'm glad we found the issue. 
Not so long ago we used to register interpreters as kernels. But recently we stopped and changed the way we find kernels and interpreters to fix stuff like this. I think this kernel was created by us with the wrong info back then. 

I'll close the issue, but feel free to reopen it happens again.

**Comment by umeshk-unnik** [comment]
> I'm glad we found the issue.
> Not so long ago we used to register interpreters as kernels. But recently we stopped and changed the way we find kernels and interpreters to fix stuff like this. I think this kernel was created by us with the wrong info back then.
> 
> I'll close the issue, but feel free to reopen it happens again.

Sure thing. Was a pleasure providing cover fire. Thanks for the prompt response and effective suggestions. Stay Safe.
