### ISSUE TITLE
Native Notebooks - Trusted Icon

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5546]
Version: 1.56.0-insider (user setup)
Commit: 8aff878db2542eea2dfb571c8bb485118bbb3113
Date: 2021-04-19T05:15:35.845Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

Jupyter Extension: v2021.6.755784270

## Steps to Reproduce: 
1. Open notebook you created
2. Not Trusted icon appears in top right
3. Try to click icon to trust

## Expected Behavior
1. Not Trusted Icon should not be showing up on a notebook I created
2. When I click the trust icon it should bring up the popup to allow me to trust. 

## Actual Behavior:
1. Not Trusted icon shows up on a notebook I created
2. Clicking icon does nothing

I accidentally clicked the split editor button once and doing that and closing the second one produced somehow fixies the issue... 

![Trusted Broken](https://user-images.githubusercontent.com/19276747/115260907-06b03480-a0e8-11eb-9d7a-c5ced610a50a.gif)

**Comment by DavidKutu** [comment]
I can't get this to repro. Do you have some more specific steps?

**Comment by claudiaregio** [comment]
No it shows up randomly :( I can't figure out how or when it is triggered

**Comment by DavidKutu** [comment]
validated, we don't even use it anymore
