### ISSUE TITLE
Native Notebooks - Randomly not finding packages

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5549]
Sometimes my notebook randomly breaks and says that I am missing a package even though I have run this notebook running this kernel hundreds of times. 

This exact same notebook with the same kernel works fine on stable webview

![image](https://user-images.githubusercontent.com/19276747/115258159-97394580-a0e5-11eb-93b3-f7179409560c.png)

**Comment by DonJayamanne** [comment]
@claudiaregio 
Please could you provide the logs from `Jupyter` output panel.
Pease could you let us know what interpreter/kernel has the packages.

**Comment by greazer** [comment]
We think this is being addressed with another issue. But if you run into it again, collect the logs and give to Don

**Comment by claudiaregio** [comment]
When I have kernel # 1 _Python 3.7.6 64 bit ('base':conda)_ selected and try to run the first cell, it tells me that pandas+profiling is missing. 

When I have kernel # 2 _Python 3.7.10 64 bit ('base':conda)_ selected and try to run the first cell, it succeeds. 

![image](https://user-images.githubusercontent.com/19276747/116927520-a0133680-ac10-11eb-936c-27469c8c1f72.png)

When I select "Python: Select Python Interpreter" these are the options I get. 

![image](https://user-images.githubusercontent.com/19276747/116927594-b7eaba80-ac10-11eb-8f31-88a603408efc.png)

Both environments are named base and I wouldn't know which one to pick. When I check for the list of conda environments, these are the only 2 I have. When I run "conda list" on the base environment, it does show pandas_profiling is in this environment. 

![image](https://user-images.githubusercontent.com/19276747/116927974-452e0f00-ac11-11eb-8ec3-ec68b6f0f676.png)

[Packages not found logs.txt](https://github.com/microsoft/vscode-jupyter/files/6417431/Packages.not.found.logs.txt)

**Comment by DonJayamanne** [comment]
I too can replicate this issue 
![Screen Shot 2021-05-03 at 14 23 26](https://user-images.githubusercontent.com/1948812/116935587-65fb6200-ac1b-11eb-8643-52e194c1c72e.png)
