### ISSUE TITLE
Creating Jupyter notebook. Permission denied: Kernel is not usable. Fresh installation

### ISSUE THREAD

**Issue by alecstein** [microsoft/vscode-jupyter#5550]
## Environment data

-   VS Code version: 1.55.2
-   Extension version (available under the Extensions sidebar): v2020.10.332292344
-   OS and version: MacOS 10.14.6
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pipenv
-   Relevant/affected Python packages and their versions: jupyter, ipykernel
-   Relevant/affected Python-related VS Code extensions and their versions: none
-   Value of the `python.languageServer` setting: Jedi

## Expected behaviour

Python interactive mode and jupyter notebooks open with an active kernel.

## Actual behaviour

I see `Kernel: Not Started` and get the error message:

```
Failed to connect to Jupyter notebook. http://localhost:8888/ 
Error: Kernel Python 3.9.2 64-bit ('projecteuler.net-KImt1lMC') is not usable. 
Check the Jupyter output tab for more information.
```

## Steps to reproduce:

1. Open up a fresh VS Code installation (with all dotfiles and application data removed) installed from homebrew (brew install vscodium)
2.  Install the python package
3. Create a virtualenv using pipenv 
4. Install ipykernel and jupyter
5. Try to open python interactive mode or a jupyter notebook to get the error

## Logs

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>**View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python**</code>)
</summary>

```
Starting Jupyter from ~/.local/share/virtualenvs/projecteuler.net-KImt1lMC/bin/python with command line --no-browser --notebook-dir="/" --config=/var/folders/41/1b0n07qj0j719p7hp0m7sxjm0000gn/T/6f7421fe-36ff-4851-a134-02c9cbc5ff06/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
[I 18:59:59.203 NotebookApp] Serving notebooks from local directory: /
[I 18:59:59.203 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 18:59:59.203 NotebookApp] http://localhost:8888/?token=12c05128abe81e7836f5c61a284b506250e23acb306f35e9
[I 18:59:59.203 NotebookApp]  or http://127.0.0.1:8888/?token=12c05128abe81e7836f5c61a284b506250e23acb306f35e9
[I 18:59:59.204 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 18:59:59.230 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/dirac/Library/Jupyter/runtime/nbserver-74376-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=12c05128abe81e7836f5c61a284b506250e23acb306f35e9
     or http://127.0.0.1:8888/?token=12c05128abe81e7836f5c61a284b506250e23acb306f35e9
[I 19:00:00.118 NotebookApp] Creating new notebook in /
[W 19:00:00.153 NotebookApp] 403 POST /api/contents/?1618531200002 (127.0.0.1): Permission denied: Untitled.ipynb
[W 19:00:00.153 NotebookApp] Permission denied: Untitled.ipynb
[W 19:00:00.154 NotebookApp] 403 POST /api/contents/?1618531200002 (127.0.0.1) 40.340000ms referer=None
[I 19:00:00.210 NotebookApp] Creating new notebook in /
[W 19:00:00.226 NotebookApp] 403 POST /api/contents/?1618531200155 (127.0.0.1): Permission denied: Untitled.ipynb
[W 19:00:00.226 NotebookApp] Permission denied: Untitled.ipynb
[W 19:00:00.228 NotebookApp] 403 POST /api/contents/?1618531200155 (127.0.0.1) 18.220000ms referer=None
```

## Hunch

This used to work, until a week or two ago. I don't know what I changed, if anything.

I believe the problem might be caused by Jupyter trying to open a notebook in my root directory "/". Jupyter works from the command line just fine, and opens notebooks with 

`Serving notebooks from local directory: /Users/dirac/projecteuler.net`.

while running from VS Code gives:

`[I 19:00:00.118 NotebookApp] Creating new notebook in /`

I also noticed that the jupyter command runs: `--notebook-dir="/"`. I don't know if this can be changed with `Notebook File Root`, but mine is currently set to  `${fileDirname}`.

**Comment by greazer** [comment]
Please reopen if this is not resolved in the next official release.
