### ISSUE TITLE
Data Viewer doesn't show Index with Multi-Index dataframe

### ISSUE THREAD

**Issue by akald** [microsoft/vscode-jupyter#5551]
When using the latest version of Visual Studio Code, 1.55.2,  and Python 3.8.8, the dataframe viewer doesn't show the index if the dataframe is a MultiIndex. In the example below, I have both the fruit_name and date as the index.

![multi-index bug](https://user-images.githubusercontent.com/59920376/115142440-a95daa00-a039-11eb-9b67-f9520fae285d.jpg)

**Comment by DavidKutu** [comment]
Thanks for the issue @akald. We'll discuss it in our next triage meeting.

**Comment by akald** [comment]
No problem. I'm attaching a photo of the problem when I run
`import pandas as pd
import numpy as np

mux = pd.MultiIndex.from_arrays([
    list('aaaabbbbbccddddd'),
    list('tuvwtuvwtuvwtuvw')
], names=['one', 'two'])

df = pd.DataFrame({'col': np.arange(len(mux))}, mux)`

![image](https://user-images.githubusercontent.com/59920376/115435435-baf1ae00-a201-11eb-8181-7456e717437e.png)

**Comment by DavidKutu** [comment]
Thanks

**Comment by DonJayamanne** [comment]
Tried this now, the layout is not perfect ,. however we do display the values
Hence closing this issue for now as completed

![Screenshot 2022-12-08 at 11 17 18](https://user-images.githubusercontent.com/1948812/206325330-5c4ef249-24e7-4356-9bc6-953f967beef7.png)
