### ISSUE TITLE
Shift+Enter not running the code cell

### ISSUE THREAD

**Issue by cassieview** [microsoft/vscode-jupyter#5554]
## Environment data

VS Code version:
Version: 1.56.0-insider (user setup)
Commit: 8aff878db2542eea2dfb571c8bb485118bbb3113
Date: 2021-04-19T05:15:35.845Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0

-   Jupyter Extension version: v2021.6.755784270
-   Python Extension version: v2021.5.756443519-dev
-   OS: Windows_NT x64 10.0.19042
-   Python and/or Anaconda version: '3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) \n[GCC 7.3.0]'
-   Type of virtual environment used: conda
-   Jupyter server running: Issue is for both Local and Remote

## Expected behaviour

When you hit "Shift+Enter" it will execute the cell

## Actual behaviour

When you hit "Shift+Enter" it does a line return

## Logs

{
  "key": "shift+enter",
  "command": "notebook.cell.executeAndSelectBelow",
  "when": "notebookCellListFocused && notebookCellType == 'markdown' || notebookCellListFocused && notebookCellExecutionState == 'failed' || notebookCellExecutionState == 'idle' || notebookCellExecutionState == 'succeeded' && notebookKernelCount > 0"
}

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DavidKutu** [comment]
Hi @cassieview, could you check your key bindings? Maybe something else is using shift+enter

**Comment by claudiaregio** [comment]
@DavidKutu @cassieview had another extension that was contributing Shift + Enter as "Insert Line Below". Can't see which extension was the source. Is there something we can do to make sure others don't run into this issue in the future?

**Comment by claudiaregio** [comment]
Maybe we could file a feature request in VS Code repo to expose which extension is contributing each shortcut so that somewhere in our documentation we can have users check they don't have other extensions contributing similar shortcuts?

**Comment by DavidKutu** [comment]
There probably won't be a way to reserve key bindings for an extension. Our best bet would be to ask VS Code to make the extension that provides it visible on the `Keyboard Shortcuts` page.

**Comment by DavidKutu** [comment]
@claudiaregio 
https://github.com/microsoft/vscode/issues/121673
