### ISSUE TITLE
Can the "data viewer" in VS Code filter data with multiple conditions?

### ISSUE THREAD

**Issue by Jill-Cheng** [microsoft/vscode-jupyter#5560]
Can the "data viewer" in VS Code filter data with multiple conditions?
For example: "_>100_" is effective, and "_<200_" is effective. Is it possible to filter the data of "**100-200**"?

actual:

![image](https://user-images.githubusercontent.com/61971386/115327479-9c6bc280-a1c1-11eb-8b88-9b67e85d98e2.png)

The code I used:

```
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")
print(tips.head())

sns.scatterplot(x = tips['total_bill'], y= tips['tip'])

plt.show()
```

Related links:[ vscode-python - Can I use the data viewer's filters to apply 'greater-than' and 'less-than' filters simultaneously?](https://stackoverflow.com/questions/67130391/vscode-python-can-i-use-the-data-viewers-filters-to-apply-greater-than-and)

Thanks a lot!

**Comment by yinshiyi** [comment]
Data Viewer in VScode to view, sort, and filter the rows of data.
I can use > and <, which is great
I am wonderng if there is a way use something ```contain: string``` similar to ```.str.contains('search_string')```

**Comment by amunger** [comment]
closing as the jupyter variable viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486
