### ISSUE TITLE
Version 2021.6.755784270 does not install on latest VSC release 1.55.1

### ISSUE THREAD

**Issue by rjl9** [microsoft/vscode-jupyter#5561]
Version 2021.6.755784270 does not install on latest VSC release 1.55.1. Currently version 2021.6.755784270 is pushed "https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter" as the latest stable release. This renders other extension like Pylance unusable for VSC installations that are offline (without access to preview versions). The latest working version for the stable release of VSC 1.55.1 is 2021.5.745244803. Why is 2021.6.755784270 pushed as the latest supported version when it breaks on the latest stable version of VSC? I would have expected 2021.5.745244803 to have been the latest on "https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter" and the 2021.6.755784270 (which requires a non-stable insider VSC) to remain in a dev channel until ready for stable/production release of VSC to match it.

**Comment by hancockjt** [comment]
And how do we obtain the .vsix (compiled) version that works on the released VS Code 2021.5.745244803? I tried downloading the source. Build attempt came up with 9500+ build errors. The devcontainer workspace in the source didn't help.

This latest "release" has rendered the python extension dead and useless on my offline (closed network) VS Code instances.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.

> Why is 2021.6.755784270 pushed as the latest supported version when it breaks on the latest stable version of VSC? I would have expected 2021.5.745244803 to have been the latest on

This vsix targets 1.56.0-insiders. Hence VS Code should not download this. This is a feature supported by VS Code where one can publish multiple VSIX each targeting different VS Code versions.

I am cetain this is a problem with VS Code, possibly another variation of https://github.com/microsoft/vscode/issues/119073

To be better able to assist you ( @hancockjt, @rjl9) , please could you provide the following information:

* OS
* Environment - Remote Containers/SSH/WSL?
* How are you installing this?
	* Are you in VS Code and just downloading Python from the VSCode maretplace?
	* Or are you downloading Python extension manually and then attempting to install it in VS Code?

**Comment by DonJayamanne** [comment]
> s the latest stable release. This renders other extension like Pylance unusable for VSC installations that are offline (without access to preview versions)

Ok, i think i understand the issue now.
I believe you are going into the marketplace and downloading this from the browser.
I believe this is an issue for VS Code to address, they need to provide some information about the VS Code engine the extension is associated with.

**Comment by DonJayamanne** [comment]
Issue moved to [microsoft/vscode #121757](https://github.com/microsoft/vscode/issues/121757) via [**ZenHub**](https://www.zenhub.com/)

**Comment by hancockjt** [comment]
> I believe you are going into the marketplace and downloading this from the browser.

That's correct. The vscode instance I'm installing to has no Internet connection, thus I must download plugins explicitly.
