### ISSUE TITLE
Dataframe Viewer doesn't show formatted date

### ISSUE THREAD

**Issue by akald** [microsoft/vscode-jupyter#5566]
When using the latest version of Visual Studio Code, 1.55.2, and Python 3.8.8, the dataframe viewer doesn't format date columns correctly.

![image](https://user-images.githubusercontent.com/59920376/115436278-b679c500-a202-11eb-97ad-2d02500f3f44.png)

```
import pandas as pd
df = pd.DataFrame({'Date': {0: '1983-11-10 00:00:00', 1: '10/11/1983'}})
df['Date'] = pd.to_datetime(df.Date, dayfirst=True)

**Comment by IanMatthewHuff** [comment]
@akald I'm seeing the same results that you are, just to confirm, you're looking to see just '1983-11-10' in the dataviewer, not the additional time string?

**Comment by akald** [comment]
Thanks, so the dataframe viewer should show the date the same way the interactive window does on the left. It shouldn't have all the zeros. Many thanks.

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1138
