### ISSUE TITLE
Feature Usability and Discoverability in vscode/Jupyter Notebooks: Menu Items

### ISSUE THREAD

**Issue by cassieview** [microsoft/vscode-jupyter#5571]
## Environment data

Version: 1.56.0-insider (user setup)
Commit: b4816cfd1f4161a3bb272354d181a9947760ee26
Date: 2021-04-20T07:23:51.425Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

## Expected behaviour

A consistent menu navigation in classic Jupiter notebooks to notebooks in vscode, or an option to use a classic jupyter navigation menu.

## Actual behaviour

The Jupyter nav menu is hard to find and the icons are not ubiquitous making it difficult to know what the menu item is without hovering over it.  This obfuscates the additional and useful tooling that running notebooks in vs code provides. It can cause users to go back to classic notebooks because their natural dev flow is fragmented.  The tooling in the vscode notebooks is amazing but it will not fully get adopted from the community if you have to drastically change your dev flow to use it. 

Current vscode menu:
![image](https://user-images.githubusercontent.com/46505951/115447891-9f28e080-a1de-11eb-997b-56c63ae80f4e.png)

Current jupyter classic menu:
![image](https://user-images.githubusercontent.com/46505951/115447972-bc5daf00-a1de-11eb-9e0c-8a7283767564.png)

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

</p>
</details>

**Comment by IanMatthewHuff** [comment]
@cassieview  Thanks much for the feedback here. Currently the new notebook UI (toolbar locations in particular) is controlled by the core VS Code team and not specifically by the Jupyter extension. I think that we might need to move this issue or open up a new issue in vscode to discuss this. @claudiaregio how would you like to handle discussing this feedback with VS Code?

**Comment by greazer** [comment]
This is being tracked in vscode: https://github.com/microsoft/vscode/issues/121766

**Comment by cassieview** [comment]
I think we can close this one since its being tracked in vscode. Thanks! :)
