### ISSUE TITLE
Native Notebooks - Reduce languages displayed based on what kernel supports

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5580]
VS Code has finally enabled kernel supported language 🎉
https://github.com/microsoft/vscode/issues/116314

Let's reduce the number of languages that are displayed to a user once they click on the language picker based on what the kernel supports.

Issue will be updated after meeting with Don to create shortlist. 
This will also support the .NET team's requested experience.

**Comment by DonJayamanne** [comment]
> This will also support the .NET team's requested experience.

No this won't.
.net team will have to make their own changes in their kernel. Ie they own the kernel, hence the languages as well.

**Comment by claudiaregio** [comment]
Sorry, I meant the API would support it. The .NET team would do the work to expose those languages which in turn would be found by that API. Is that understanding correct?

**Comment by claudiaregio** [comment]
@DonJayamanne We were going to do this for us as well, only populate python, markdown, plain text + any magics python supports, am i not remembering correctly?

**Comment by DonJayamanne** [comment]
Yes, you are correect, but wanted to ensure anyone looking at this issue that we're not blocking .NET

**Comment by rchiodo** [comment]
Tested with .NET interactive. Languages correctly switched back and forth
