### ISSUE TITLE
Publish the VSIX files in the release

### ISSUE THREAD

**Issue by oli-arborum** [microsoft/vscode-jupyter#5582]
Currently, it is impossible to retrieve old releases of this extension.
Reason: Neither the VSIX files are published in the releases (like in the Python Extension on https://github.com/microsoft/vscode-python/releases) nor the complete version string (e.g. "2021.6.755784270" for the latest release) is made available (also like it is done in the Python Extension) in order to be able to fetch the VSIX via the URL https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/$VERSION/vspackage

Reason for request: There exist environments where a) a certain fixed version of VSCode is enforced or required and b) no direct internet connection from VSCode (to download extensions) is possible. If the used VSCode version is incompatible with the latest extension release, it is required to load a compatible (old) one manually.

If you see any chance where/how to get the Jupyter Extension version 2020.12 please give me an update on that.

**Comment by rchiodo** [comment]
This is actually supported within VS code itself. You click on the little gear icon next to the extension and pick ```Install Another Version...```

This will bring up a quick pick that lets you select an older version

![image](https://user-images.githubusercontent.com/19672699/115588679-d69d9880-a283-11eb-9577-cbac6ca83714.png)

**Comment by rchiodo** [comment]
That list (as of right now) has every version in it.

**Comment by oli-arborum** [comment]
Thanks for the screen shot of the list. It helped me to download the desired version.

However, note that I am using VSCode in an environment with no internet connection at all so that I am forced to download the VSIX files manually and transfer them to that environment to install them offline. Thus, the "Install another version..." entry is disabled in my VSCode.
To conclude, I really would apreciate it if you put the VSIX files in the releases (as other extensions like Python, C/C++, ... do). That would make our coding lifes easier.

**Comment by stanmartin1** [comment]
> That list (as of right now) has every version in it.

Unfortunately, no, this is not the case.   I have the same problem as the original poster oli-arborum.   His system, like mine, is not directly connected to the Internet.   The most recent versions of the extension (the only ones available with downloadable .vsix files) will not install in my version of VSCode, which cannot be changed for compatibility reasons.   So there is no extension installed from which to get a dropdown with previous versions.  Even if there was an extension installed, it could not load other versions since it cannot access the Internet.
Many other extension projects archive the .vsix files along with the source code; Jupyter is an exception.  But, at present, Jupyter is required to make Python extension work.  So both are DOA.

**Comment by oli-arborum** [comment]
We have exactly the same issues in our environment: We use an older version of VSCode for compatibilty reasons in an offline environment and need to install the Jupyter extension because the Python extension requires it since version 2020.11.

@stanmartin1 To download an arbitrary version of the Jupyter extension use the following URL:
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/${VERSION}/vspackage
and replace `${VERSION}` with the desired version string from @rchiodo's screen shot.

**Comment by stanmartin1** [comment]
> We have exactly the same issues in our environment: We use an older version of VSCode for compatibilty reasons in an offline environment and need to install the Jupyter extension because the Python extension requires it since version 2020.11.
> 
> @stanmartin1 To download an arbitrary version of the Jupyter extension use the following URL:
> [https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/${VERSION}/vspackage](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/$%7BVERSION%7D/vspackage)
> and replace `${VERSION}` with the desired version string from @rchiodo's screen shot.

Thank you! this got me running.

**Comment by oli-arborum** [comment]
> Thank you! this got me running.

You're welcome! =)

**Comment by stanmartin1** [comment]
BTW, while hacking the URL is a cool workaround, it would still be best if the dev team could just include the .vsix file under the list of released artifacts, alongside the source.

**Comment by oli-arborum** [comment]
> BTW, while hacking the URL is a cool workaround, it would still be best if the dev team could just include the .vsix file under the list of released artifacts, alongside the source.

Yes, I second that proposal.
Especially when there is no way to get the exact version string that needs to be inserted in the URL.

**Comment by rchiodo** [comment]
We'll be discussing this in triage. There's a reason why it's not there at the moment. Mostly to do with licensing. I believe the license says the VSIX has to be acquired from the marketplace but I'm not a lawyer so not sure what the ramifications of sticking it in github releases is.

If we can't put it on the github page, we'll log a bug with the marketplace team to make all versions available. We already have an [issue ](https://github.com/microsoft/vsmarketplace/issues/43) against them to make it obvious which VS code the items in the marketplace work against.

**Comment by oli-arborum** [comment]
@rchiodo Just FYI - I looked into the **six "most trending" extensions on the marketplace** and their related GitHub release pages:
- **vscode-python**: publishes the VSIX files in GitHub releases (see https://github.com/microsoft/vscode-python/releases)
- **vscode-cpp**: publishes the VSIX files in GitHub releases (see https://github.com/microsoft/vscode-cpptools/releases)
- **vscode-eslint**: publishes the VSIX files in GitHub releases (see https://github.com/microsoft/vscode-eslint/releases)
- **prettier-vscode**: publishes the VSIX files in GitHub releases (see https://github.com/prettier/prettier-vscode/releases)
- **vscode-live-server**: publishes the VSIX files in GitHub releases (see https://github.com/ritwickdey/vscode-live-server/releases)
- **vscode-jupyter**: ***does not*** publish the VSIX files in GitHub releases (see https://github.com/microsoft/vscode-jupyter/releases)

Do you notice anything? ;-)

**Comment by lanzrein** [comment]
Hello, 
Is there any update on this issue ? 


I tried the method mentionned here : 

> We have exactly the same issues in our environment: We use an older version of VSCode for compatibilty reasons in an offline environment and need to install the Jupyter extension because the Python extension requires it since version 2020.11.
> 
> @stanmartin1 To download an arbitrary version of the Jupyter extension use the following URL: [https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/${VERSION}/vspackage](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/$%7BVERSION%7D/vspackage) and replace `${VERSION}` with the desired version string from @rchiodo's screen shot.


But doing the command 
```
curl https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2022.1.130/vspackage
```

Got me an error message : `Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).`

Anyone found a way around this error ?

**Comment by DonJayamanne** [comment]
Closing this issue, as we already have a way to get the release on the marketplace and some of the other partner teams too do not publish VSIX in the github release just as we do not

>  error message : Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.

If this is still an issue please file an issue on VS Code
