### ISSUE TITLE
Include line hyperlinks for every part of traceback

### ISSUE THREAD

**Issue by ortk95** [microsoft/vscode-jupyter#5584]
When an exception is raised, the traceback provides nicely hyperlinked line numbers which allow the user to quickly navigate to the source of the error. However, these hyperlinks are only present for the top level file in the traceback, so do not allow easy navigation to where an exception is raised from an imported module:

![image](https://user-images.githubusercontent.com/26504228/115557973-268f5600-a2aa-11eb-9cad-85023fce7958.png)

It would therefore be useful if the line number hyperlinks were present for every part of the traceback to make tracking down the sources of errors easier. The VS Code terminal automatically turns each of the traceback paths into an appropriate link, so this would help to bring the Jupyter interactive window into line with the terminal's behaviour:

![image](https://user-images.githubusercontent.com/26504228/115559690-d2857100-a2ab-11eb-95f4-f0e373896c72.png)

**Comment by rchiodo** [comment]
Thanks for the suggestion. Seems easy enough to implement if the file is on the same file system.

**Comment by amunger** [comment]
I believe @rchiodo implemented this a few months ago - seems to be working for me.
