### ISSUE TITLE
Fix tests after kernel push update.

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#5585]
Tests were broken to unblock kernel push.

**Comment by joyceerhl** [comment]
@IanMatthewHuff were you already working on this? If not I can take this on.

**Comment by IanMatthewHuff** [comment]
@joyceerhl please grab it if you have cycles. I did one cleanup pass here, but it's still pretty bad. https://github.com/microsoft/vscode-jupyter/pull/5589

**Comment by joyceerhl** [comment]
I think we can close this as a dupe of #5535, it's the same set of tests that are failing (apart from ipywidgets, which are legitimately broken).
