### ISSUE TITLE
Fix widgets after kernel push changes

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#5586]
Widgets were broken by the kernel push changes. Need to update to use NotebookController as opposed to the old NotebookCommunications. Also remove the NotebookCommunications class that we added to proposedAPI to not break our build.

**Comment by joyceerhl** [comment]
Validated. Our test notebooks for beakerx, ipyvolume, bqplot, k3d look good with the release VSIX.
