### ISSUE TITLE
Incorrectly warned about lack of internet connection for widgets

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5587]
I've managed to replicate this a number of times.
I think we should change the way we check if user has access to the internet.
A simple ping to some known site (even google.com that responds quickly) would be better than what we have.

<img width="580" alt="Screen Shot 2021-04-21 at 08 40 05" src="https://user-images.githubusercontent.com/1948812/115581970-5b38e880-a27d-11eb-8cbb-fccc87e9ed0a.png">

**Comment by greazer** [comment]
If I remember the discussion, the current mechanism that determines whether there's an internet connection, literally does a ping to a known site. So not sure how to fix this any better and we're getting no thumbs up, so closing.
