### ISSUE TITLE
How to support all languagse in a Kernel

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5588]
With the notebook controller we need to define the langauges supported by a Notebook Kernel:
```
        /**
         * An array of language identifiers that are supported by this
         * controller.
         */
        supportedLanguages: string[];
```

In classic jupyter (not VS Code extesnion), we could have a kernel such as SOS, .NET Kernel, etc that support other langauges as well.
At this point the metadata only tells us that the langauage is `sos` or `Csharp`.
But these kernels could internally support other languages (meta kernels).

& in such cases, users might want to get the syntax highlighting for these other languages.
E.g. .NET kernel supports F#. But since the kernel spec says that Csharp is supported, now users cannto create a cell and change it to F# so that they can get the necessary syntax highlighthing.

Is it possible to leave `supportedLanguages` blank so that it supports all langauges (as it was previously).

Else this has the potential to break other kernels out there.

Another scenario is:
* With python kernel you can have cell magics.
* Users can install other python packages that support execution of SQL or the like from within the python kernel.
* At this point users would create a python cell and add the magic `%%sql` as the fist line.
* The rest of the code in that cell would be SQL, now users would want syntax highlighitng for SQL (but they cann't as the cell language is limited to Python).
Similarly there are other magics, kusto, sql, html, svg, javascript, perl, bash, & others that support cells with those languages & gets executed by the python kernel.

@jrieken @rebornix /cc

**Comment by jrieken** [comment]
> Is it possible to leave supportedLanguages blank so that it supports all langauges (as it was previously).

Yes - that's what I have pushed today

**Comment by DonJayamanne** [comment]
Thanks, closing this issue
