### ISSUE TITLE
Adding additional objects to Data Viewer; e.g. xarray arrays?

### ISSUE THREAD

**Issue by max-sixty** [microsoft/vscode-jupyter#5590]
Currently Data Viewer works with a few objects — pandas' DataFrames, numpy arrays, TF & PyTorch tensors. It's v impressive! Would it be possible to add more types of objects?

It would be great to get xarray in there too (disclaimer: I'm a core dev). A couple of approaches:
1. Look for objects with `__array__` methods and call that to return a numpy array. This extension doesn't need to know anything about the array for this to work, but we only get numpy functionality.
2. Add actual xarray support, including the ability to select labels, as well as indices

Here's an example of `np.asarray` & `__array__` working:

```python
In [6]: import xarray as xr

In [11]: da = xr.DataArray(np.random.rand(2,3,4), dims=list('abc'), coords=dict(a=['x','y'], b=['m','n','o']))

In [12]: da
Out[12]:
<xarray.DataArray (a: 2, b: 3, c: 4)>
array([[[0.91948492, 0.20846841, 0.6842219 , 0.16919421],
        [0.34729456, 0.59948279, 0.63013757, 0.82908032],
        [0.18657731, 0.24992941, 0.87905069, 0.93960824]],

       [[0.12899889, 0.30758554, 0.7182392 , 0.76364721],
        [0.68879206, 0.81600394, 0.10102972, 0.13856853],
        [0.43866809, 0.60140471, 0.47634698, 0.37118161]]])
Coordinates:
  * a        (a) <U1 'x' 'y'
  * b        (b) <U1 'm' 'n' 'o'
Dimensions without coordinates: c

In [13]: np.asarray(da)
Out[13]:
array([[[0.91948492, 0.20846841, 0.6842219 , 0.16919421],
        [0.34729456, 0.59948279, 0.63013757, 0.82908032],
        [0.18657731, 0.24992941, 0.87905069, 0.93960824]],

       [[0.12899889, 0.30758554, 0.7182392 , 0.76364721],
        [0.68879206, 0.81600394, 0.10102972, 0.13856853],
        [0.43866809, 0.60140471, 0.47634698, 0.37118161]]])

In [14]: da.__array__()   # same as above
Out[14]:
array([[[0.91948492, 0.20846841, 0.6842219 , 0.16919421],
        [0.34729456, 0.59948279, 0.63013757, 0.82908032],
        [0.18657731, 0.24992941, 0.87905069, 0.93960824]],

       [[0.12899889, 0.30758554, 0.7182392 , 0.76364721],
        [0.68879206, 0.81600394, 0.10102972, 0.13856853],
        [0.43866809, 0.60140471, 0.47634698, 0.37118161]]])
```

**Comment by joyceerhl** [comment]
> Would it be possible to add more types of objects?

Yes, and we welcome PRs 😊

> Add actual xarray support, including the ability to select labels, as well as indices

I might be misreading this, is the proposal to add custom UI for manipulating xarray objects?

> Look for objects with __array__ methods and call that to return a numpy array.

FWIW, if you wanted to pursue approach #1, here are the changes to make:

In this function: https://github.com/microsoft/vscode-jupyter/blob/70a6e7ba3836fde042c83f769912b6370efd659e/pythonFiles/vscode_datascience_helpers/dataframes/vscodeDataFrame.py#L91-L107 add a case for xarray DataArrays:
```python
    elif hasattr(df, "__array__") and hasattr(vartype, "__name__") and vartype.__name__ == "DataArray":
        df = _VSCODE_convertNumpyArrayToDataFrame(df.__array__(), start, end)
```
(Depending on how `__array__` is implemented it may be better to evaluate `df[start:end].__array__()` instead)

And add 'DataArray' to the following three lists of supported types:
1. https://github.com/microsoft/vscode-jupyter/blob/70a6e7ba3836fde042c83f769912b6370efd659e/src/client/datascience/jupyter/debuggerVariables.ts#L24-L32
2. https://github.com/microsoft/vscode-jupyter/blob/70a6e7ba3836fde042c83f769912b6370efd659e/src/client/datascience/jupyter/kernelVariables.ts#L39-L47
3. https://github.com/microsoft/vscode-jupyter/blob/70a6e7ba3836fde042c83f769912b6370efd659e/src/datascience-ui/data-explorer/mainPanel.tsx#L40

This should suffice to get support for viewing xarrays in the data viewer, including [slicing](https://devblogs.microsoft.com/python/jupyter-in-visual-studio-code-april-2021-release/#data-slicing) xarrays.

**Comment by vandyliu** [comment]
Solved by https://github.com/microsoft/vscode-jupyter/pull/6027
