### ISSUE TITLE
Highlight corresponding brackets

### ISSUE THREAD

**Issue by claireseceh** [microsoft/vscode-jupyter#5594]
Is possible to add a highlight of corresponding brackets ?

**Comment by greazer** [comment]
Thanks for your feedback. What window are you referring to? Interactive Window or a Python Notebook? Note that if it's a notebook, then the issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.

If it's interactive window, we don't support this yet.
