### ISSUE TITLE
jupyter notebooks stopped working Mar 2021

### ISSUE THREAD

**Issue by compfy-dot-com** [microsoft/vscode-jupyter#5597]
Issue Type: <b>Bug</b>

With the release Mar 2021 , the Jupyter notebooks stopped working. They cannot import modules installed in a virtual Python environment (venv).
```
     2 from pathlib import Path
      3 import numpy as np
----> 4 from PIL import Image
      5 from IPython.display import display
      6 
ModuleNotFoundError: No module named 'PIL'
```

Extension version: 2021.4.765268190
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>

**Comment by bardal** [comment]
Think this is because of #5489. What interpreter is your notebook picking up?

**Comment by DonJayamanne** [comment]
@compfy-dot-com Thanks for filing this issue.
Please could you provide some more information:
* OS
* Python Version
* Version of Jupyter extsnion
* Are you using Notebooks or Interactive Window
* Please provide the logs from your `Jupyter` output panel

**Comment by compfy-dot-com** [comment]
Yes, the Jupyter notebook is using the wrong Python interpreter, not the one currently selected in VSCode. The one selected in VS code is from a venv, but the notebook is using the default one.

**Comment by DonJayamanne** [comment]
@compfy-dot-com thanks again, however you have talked to provide the information I requested.
 I need that to get you unblocked. We have fixed a few issues in this area and next week we'll be releasing a new version. I'd like to ensure that fixes the issues you (and others) are running into.

Alternatively you can install vscode insiders, you'll be able to tests our latest development build there.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
