### ISSUE TITLE
Add tests for editing notebook metadata

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5601]
https://github.com/microsoft/vscode-jupyter/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed

**Comment by rchiodo** [comment]
@DonJayamanne do you have any more information? Editiing metadata outside of VS code? So like kernel changes? Or cell metadata too? 

Is the test to ensure metadata is there after opening and saving in VS code?

**Comment by DonJayamanne** [comment]
> So like kernel changes

Yes, 
Basically test:
* Select a kernel
* Ensure nb metadata contains the necessary information (interpreter hash, etc)
Close the notebook and verify changes in the ipynb file.

> Is the test to ensure metadata is there after opening and saving in VS code?

Yes
