### ISSUE TITLE
Native Notebooks - Run by Line

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5607]
#### Backlog
- [x] #7057
- [ ] #7611
- [x] #6917
- [x] #7127
- [ ] #7128
- [x] #7779

#### October Milestone
- [x] #7638
- [ ] #6898
- [ ] #7740
- [ ] #7563
- [ ] #7584
- [ ] #7690
- [x] #7696
- [ ] #7764
- [ ] #7733
- [ ] #7715
- [ ] #7718
- [ ] #7761
- [ ] #7751
- [x] #7750
- [ ] #7746
- [x] #7735
- [ ] #7734

#### Closed
<details>

- [x] #6904
- [x] #7494
- [x] #7630
- [x] #7633
- [x] #7576
- [x] #7218
- [x] #7586
- [x] #7631
- [x] #7467
- [x] #6243
- [x] #7530
- [x] #7323
- [x] #7332
- [x] #7346
- [x] #7365
- [x] #1166
- [x] #6214
- [x] #1170
- [x] #7339
- [x] #6215 
- [x] #6207
- [x] #6211
- [x] #6376
- [x] #6209
- [x] #6208
- [x] #6210
- [x] #6391
- [x] #6467
- [x] #6866
- [x] #6910
- [x] #6858
- [x] #6701
- [x] #6859
- [x] #6867
- [x] #6880
- [x] #7056
- [x] #6868
- [x] #7700
- [x] #6905
- [x] #6377
- [x] #6857
- [x] #6378
- [x] #6212
- [x] #6860
- [x] #7124
- [x] #7133
- [x] #7180
- [x] #6856
- [x] #6411
- [x] #6405
- [x] #6468
- [x] #7037
- [x] #7251
- [x] #7200
- [x] #7246
</details>

**Comment by DavidKutu** [comment]
# Steps to try debugging on notebooks

1. Build this [branch](https://github.com/microsoft/vscode-jupyter/tree/david/debuging)
2. Create a venv (`python -m venv [directory]`)
3. Install ipykernel 6 on your venv (`pip install ipykernel --pre`)
4. Open an notebook and select your venv on the kernel picker
5. Click this button on the toolbar
![image](https://user-images.githubusercontent.com/20347396/123297700-ab763600-d4cc-11eb-9ce6-a3cf870711f2.png)

You'll be able to set and hit breakpoints when running cells.

**Comment by ahmednrana** [comment]
> # Steps to try debugging on notebooks
> 1. Build this [branch](https://github.com/microsoft/vscode-jupyter/tree/david/debuging) on insiders
> 2. Create a venv (`python -m venv [directory]`)
> 3. Install ipykernel 6 on your venv (`pip install ipykernel --pre`)
> 4. Open an notebook and select your venv on the kernel picker
> 5. Click this button on the toolbar
>    ![image](https://user-images.githubusercontent.com/20347396/123297700-ab763600-d4cc-11eb-9ce6-a3cf870711f2.png)
> 
> You'll be able to set and hit breakpoints when running cells.

This branch is returning 404

**Comment by DavidKutu** [comment]
So sorry @ahmednrana! This is in main now, I'll update the instructions.
