### ISSUE TITLE
IntelliSense not working for Jupyter notebooks

### ISSUE THREAD

**Issue by manujchandra** [microsoft/vscode-jupyter#5609]
## Environment data

-   Version: 1.55.2
-   Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
-   Date: 2021-04-13T09:37:02.931Z
-   Electron: 11.3.0
-   Chrome: 87.0.4280.141
-   Node.js: 12.18.3
-   V8: 8.7.220.31-electron.0
-   OS: Linux x64 5.11.0-7612-generic
-   Jupyter Extension version (available under the Extensions sidebar): Version: 2021.5.745244803
-   Python Extension version (available under the Extensions sidebar): 2021.4.765268190
-   OS (Windows | Mac | Linux distro) and version: PopOS 20.04
-   Python and/or Anaconda version: 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Jupyter server running: Local

## Expected behaviour

When I hover over a token some information should get displayed. When I type autocomplete should work. Pressing ctrl+space inside a function should show function docs.

## Actual behaviour

Hovering over tokens and writing code does not produce any code assist. Tab autocomplete does not work. (It is as if I am writing code in a notepad)

(Code complete is working in .py files though)

Pressing ctrl+space inside a function shows files in the explorer instead of function parameters.

![Screenshot from 2021-04-23 11-27-05](https://user-images.githubusercontent.com/15191493/115825565-3a13fb80-a427-11eb-953b-c29a143a3ff0.png)

**Comment by joyceerhl** [comment]
Hi @manujchandra thanks for reporting a bug, this sounds like a regression. What's the value of the `"python.languageServer"` setting in your user settings.json?

**Comment by manujchandra** [comment]
Greetings @joyceerhl ,

python.languageServer was not set to anything in my settings to json. After setting it to "Pylance" and installing the Pylance extension it seems to be working fine.

Thanks for your support.
