### ISSUE TITLE
Jupyter (iPython) data viewer: scrollbar not working

### ISSUE THREAD

**Issue by Ov-ille** [microsoft/vscode-jupyter#5610]
## Environment data

-   VS Code version: 1.55.2
-   Jupyter Extension version (available under the Extensions sidebar): 2021.5.745244803
-   Python Extension version (available under the Extensions sidebar): 2021.4.765268190
-   OS (Windows | Mac | Linux distro) and version: Windows 10 (x64)
-   Python and/or Anaconda version: Python 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): with or without venv
-   Jupyter server running: N/A

## Expected behaviour

Scrolling up and down in the Python interactive data viewer using the scrollbar on the right side

## Actual behaviour

Scrollbar in Python interactive data viewer can't be used because it is too narrow (when hovering over scrollbar the mouse action immediately changes to increasing/decreasing the windows size)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. start interactive python session
2. open stored variable in data viewer (e.g. dataframe etc)
3. try to scroll down using the scrollbar on the right
![image](https://user-images.githubusercontent.com/81677045/115833858-cff25b00-a414-11eb-856b-10b5cfec8b0f.png)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by claudiaregio** [comment]
Hi @Ov-ille, I am able to reproduce this. Especially if you have a larger dataset, the table goes all the way to the end of the screen and the scroll is very small and hard to use. 

![image](https://user-images.githubusercontent.com/19276747/115899939-3f1b7f80-a414-11eb-95d1-8cb3ff85a436.png)

**Comment by Ov-ille** [comment]
I'm fairly new to this. It looks to me like the issue was solved, right? Do I have to wait for a new release now or can I adapt something in my VSCode to have this adjustment immediately?

**Comment by joyceerhl** [comment]
Yes, we should have an update out next week, or you can download a VSIX with the fix here: https://github.com/microsoft/vscode-jupyter/suites/2568953009/artifacts/55988512

**Comment by IanMatthewHuff** [comment]
Validated. Looks good.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/eccef82c-a44e-4c57-b147-d8f6cfe74de6)
