### ISSUE TITLE
interpreter name in kernelspec gets jumbed to `python3<hash #>`

### ISSUE THREAD

**Issue by juhuebner** [microsoft/vscode-jupyter#5612]
possibly related to #5597 #5489 

In the kernelspec section of the jupyter notebook the name of the kernel obtains an unusable name like 
`"name": "python388jvsc74a57bd0073360510c73ce0952195aa6ddd8e522a1bf8b6c3e24c76c079f2f34ecbdf310"`
s.b.

This makes it unusable in other jupyter applications. Interestingly within vscode the notebook runs fine.

## Environment data

-   VS Code version: 1.55.2
-   Jupyter Extension version
  - good: v2021.3.684299474
  - bad: v2021.4.702810522
-   Python Extension version v2021.4.765268190
-   Windows 10
-   Python 3.8.8 and Anaconda version: 2020.11/ updated
-   conda
-   Jupyter server running: Local

## Expected behaviour

Excerpt from the notebook with version v2021.3.684299474
```
{
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  },
  "orig_nbformat": 2,
  "kernelspec": {
   "name": "python3",
   "display_name": "Python 3.8.8 64-bit (conda)",
   "metadata": {
    "interpreter": {
     "hash": "073360510c73ce0952195aa6ddd8e522a1bf8b6c3e24c76c079f2f34ecbdf310"
    }
   }
  }
 },
```

## Actual behaviour

Excerpt from the notebook with version v2021.4.702810522
```
{
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  },
  "orig_nbformat": 2,
  "kernelspec": {
   "name": "python388jvsc74a57bd0073360510c73ce0952195aa6ddd8e522a1bf8b6c3e24c76c079f2f34ecbdf310",
   "display_name": "Python 3.8.8 64-bit (conda)"
  }
 },
```

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

* Install at max (available higher version up-to now show the same behaviour) the Jupyter extension v2021.4.702810522
* Create a new notebook via `ctrl+P` + `Jupiter: Create new notebook`
* After saving have look at the raw content

* Some part of the long hash coincides with the `fileHash` located in the file `kernelSpecPaths.json`
* The mixed name is also changed in working notebook created with jupyter notebook if opened and saved in vscode.

**Comment by DonJayamanne** [comment]
Thanks for filling this issue. I'll discuss this with the team.

**Comment by DonJayamanne** [comment]
@juhuebner 
We've decided to not store this kernel name.

**Comment by rchiodo** [comment]
Validated.
