### ISSUE TITLE
Not using workspace interpreter as the default interpreter

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5613]
Open a workspace, set interpreter to X
Open a notebook, and it will use Y (where Y is the global default)
We should be using `X` 
this is a regression (should work similar to interactive window - always use workspace interpreter as the default when creating new notebooks).

**Comment by DavidKutu** [comment]
In my case its either using the one from the metadata or not selecting anything and I have to select a kernel.
That seems good to me, but IDK if its what we want.

**Comment by IanMatthewHuff** [comment]
Validated.

debugEnv2 as python interpreter. Create new blank notebook. debugEnv2 is preferred kernel:
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/709fc2aa-686e-4dcf-9794-7f45bc316c8a)
