### ISSUE TITLE
Cell Languages Missing: Only Plaintext

### ISSUE THREAD

**Issue by davzaman** [microsoft/vscode-jupyter#5616]
Issue Type: <b>Bug</b>

Create new blank notebook using vscode command. Set the proper kernel for the notebook. Create a basic cell, it shows as python. Upon trying to execute it nothing happens. Clicking new code cell creates a Plain Text cell. When trying to change the Cell Language my only options are "Markdown" and "Plain Text".

I have a notebook in a different folder on my machine that I'm using VS Code Insider's jupyter extension and that one is working fine. I am not sure what is wrong with this.

Extension version: 2021.6.777186939
VS Code version: Code - Insiders 1.56.0-insider (Universal) (23a2409675bc1bde94f3532bc7c5826a6e99e4b6, 2021-04-21T05:59:06.814Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 5.0.0-37-generic
Remote OS version: Linux x64 5.0.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.57GB free)|
|Process Argv|--crash-reporter-id e36ddcb5-d3f9-4b36-9f9b-a02f63800663|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: lambda2.cs.ucla.edu|
|OS|Linux x64 5.0.0-37-generic|
|CPUs|Intel(R) Core(TM) i9-9960X CPU @ 3.10GHz (32 x 1200)|
|Memory (System)|125.58GB (54.49GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: lambda2.cs.ucla.edu|
|OS|Linux x64 5.0.0-37-generic|
|CPUs|Intel(R) Core(TM) i9-9960X CPU @ 3.10GHz (32 x 1200)|
|Memory (System)|125.58GB (54.49GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
vstes627:30244334
pythonvspyt875:30259475
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30267464
pythonptprofiler:30281269
vscnewfiletextcf:30288478
vshan820:30276952
pythondataviewer:30285072
vscus158:30286553
vscgsv2:30286872

```

</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue
This is due to the fact that you have an older version of VS Code Insiders.
Please could you update to the latest version of VS Code Insiders.
Please feel free to re-open thi sissue or create a new issue of this persists.
