### ISSUE TITLE
Remove use of INotebookModel when using NativeNotebooks (serializer)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5622]
With the new Content provider code in VS Code we will not be provided the Uri when asked by VS Code to translate the bytes into a Notebook document.
https://github.com/microsoft/vscode/issues/121974#issuecomment-826668767

This is a good thing, we can remove the use of these old wrappers else these will never go away and we'll keep using these wrappers & extending them.

We have a few places where INotebookModel is used:
* Trust (that's going to be handled by VSC Code, hence this won't be required for trust)
* Export (we can get the details of the document from the VS Code document)
* Context variables (we can use VS Code document instead)

**Note:** 
**This is not a breaking change in VSC**, but the old content provider will not be maintained either. Hence we'll need to move to the new one (e.g. to get around a few bugs that users have reported, when opening ipynb as json, etc).

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode/issues/121974#issuecomment-836763770

**Comment by IanMatthewHuff** [comment]
Validated. Also validated by the test plan.
