### ISSUE TITLE
Cells not showing

### ISSUE THREAD

**Issue by whippingdot** [microsoft/vscode-jupyter#5624]
## Environment data

-   VS Code version: 1.56.0-insider(user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.777186939
-   Python Extension version (available under the Extensions sidebar): v2021.4.765268190
-   OS (Windows | Mac | Linux distro) and version: Windows, 20H2
-   Python and/or Anaconda version: Python 3.8.5 64-bit (conda), 2020.11
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): I think Conda
-   Jupyter server running: Local

## Expected behavior

All the cells to load in

## Actual behavior

The first three cells don't load in but the rest do. By this I mean when I scroll to the top the first cell I see is the fourth cell. If I try scrolling further, I can't and I see that the scroll bar is at its max too. Also if I press the run all button the first three cells also run (i know this because I take inputs and the input dialogue still occurs).

## Steps to reproduce:

I think this might only be a problem with the current notebook I am using, so I don't know how you would replicate this. For now maybe:

1. Create 22 cells with the last two markdown and the rest python.

2. Try reloading the notebook a couple times and see if the first few don't load.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

There is a lot so I don't know what to paste here...
```
XXX
```

</p>
</details>

**Comment by joyceerhl** [comment]
@whippingdot This sounds bad if it's hitting lots of users. Can you share the notebook by any chance? Or post a GIF/screenshot? I can't reproduce it though--I created 22 cells with the last 2 markdown and the rest Python like you said, and reloaded 5x but the cells are definitely showing for me.

As for the logs, if you could paste all of them under the Jupyter output panel that would be helpful. Thanks in advance!

**Comment by whippingdot** [comment]
One thing to note - this is only happening on one computer. I don't really use that computer so it isn't a major problem, but I am pretty sure it isn't a problem with everyone. On the other computers it works. Also I can't seem to share the notebook, so I will just share a video:

https://user-images.githubusercontent.com/64354499/115984300-fa364b00-a5c3-11eb-85bf-5343cfeea69e.mp4

**Comment by greazer** [comment]
Please reopen if there is still a problem here.
