### ISSUE TITLE
Variable explorer in interactive window debug session does not show locals

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5626]
The root cause of this is that when there is a local and global scope, e.g. we're stopped on a breakpoint inside a function in a Python module, two variables requests are sent from the client to the debug adapter. However it looks like our debug adapter tracker code assumes only one variables request is ever sent, and we overwrite `this.lastKnownVariables` for each response we process:

https://github.com/microsoft/vscode-jupyter/blob/6cab79c9eddab3b52a3536064f8b323e55128371/src/client/datascience/jupyter/debuggerVariables.ts#L344-L346

In the case where there is only a global scope, two variables requests are still sent (you can see this by setting a breakpoint in onDidSendMessage in debugLocationTracker.ts), but their contents are identical, which is why the variable explorer still shows the right variables. But when we're stopped in a function and the local scope variables response is processed before the global scope variables response,  this results in the variable explorer failing to show local variables. E.g. in the screenshot below, the variable explorer only shows the globally declared `a` and `b`, when it should also be showing the local `df` (which is shown in the locals window on the left):

![image](https://user-images.githubusercontent.com/30305945/115976405-a9224a80-a522-11eb-803c-957790cc9e57.png)

Instead I think we should combine the `allowedVariables` with the existing `this.lastKnownVariables`. We must also clear `this.lastKnownVariables` to avoid showing variables that have gone out of scope in the variable explorer, e.g. we can clear on a continue event (since we'll recompute the lastKnownVariables the next time we receive variables responses from the debug adapter).

**Comment by joyceerhl** [comment]
https://github.com/microsoft/vscode-jupyter/commit/86a198e37ce57be17ed8454975381701005dca3e partially fixes this. If a globally scoped variable is shadowed by a local variable, should we show both (in which case we would need to indicate which scope each variable belongs to) or show the local by default?

**Comment by amunger** [comment]
Just went through a repro for this with the modern variable explorer - it looks like we now _only_ show the variables in the local scope, and globals don't appear at all.
![image](https://user-images.githubusercontent.com/2019016/161644051-e585b1f7-f40b-417c-8c9e-8bed5c688005.png)

**Comment by roblourens** [comment]
Rather than risk showing duplicate variables where it's not clear what scope the variable is in (since the explorer doesn't have this concept), I'll leave it as-is, ensure that we have a story for this in the new variable explorer, and close in favor of https://github.com/microsoft/vscode/issues/165445
