### ISSUE TITLE
Opening data viewer from 2+ scopes in a debug session fails with NameError: name '_VSCODE_VariableImport' is not defined 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5627]
This impacts all three debugging scenarios we currently support:

1) In Run By Line with v2021.6.780948196:

![rbl](https://user-images.githubusercontent.com/30305945/115977229-d8d55080-a52a-11eb-9056-d96bf4706d12.gif)

2) In interactive window debugging, you currently can't open the local variables from the variable explorer in the data viewer due to https://github.com/microsoft/vscode-jupyter/issues/5626. It looks like we used to disable the variable explorer when debugging in the interactive window, though we don't anymore and I don't remember why: https://github.com/microsoft/vscode-python/blob/c08ef0be557ed697ef96bfe12b3820d7e4ac2e8e/package.nls.json#L456. But the same problem likely applies for opening variables from the variable explorer, and does apply when using the View Value in Data Viewer context menu option in the variables window:

![iw_debugging](https://user-images.githubusercontent.com/30305945/115977285-67e26880-a52b-11eb-8858-5025eeeb4aef.gif)

3) In Python file debugging:

![twobreakpoints](https://user-images.githubusercontent.com/30305945/115941902-554d2e00-a45c-11eb-90c7-2ccb5f846edd.gif)

I don't think this is a regression, it looks like we have always evaluated the imports once per debug session in the topmost frame. https://github.com/microsoft/vscode-jupyter/blob/2ac130e64993790bb8500e3227c0808487149213/src/client/datascience/jupyter/debuggerVariables.ts#L211-L241

**Comment by IanMatthewHuff** [comment]
Validated. I used #3 python file as the validation. From what I see of the fix that should suffice. But if you want I can test the other two as well.
