### ISSUE TITLE
No scrollbar generated for large outputs

### ISSUE THREAD

**Issue by tobiasharren** [microsoft/vscode-jupyter#5629]
## Environment data

-   VS Code version: 1.56.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): 
-   Python Extension version (available under the Extensions sidebar): v2021.6.780948196
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04.2 LTS
-   Python and/or Anaconda version: Python 3.8.3, conda 4.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour
When running a code cell which generates large output (either text, or a series of plots), the ouput cells size should be limited and a scrollbar within the output cell should appear.

(Jupyter: Enable Scrolling For Cell Outputs 
is active,
Jupyter: Max Output Size
is 50 (was 200 previously, but lowering it did not help)

## Actual behaviour
The entire output is shown as one large chunk without scrollbar.

## Steps to reproduce:
create a new file
save a .ipynb file

insert into the first code cell:
`for i in range(50):
    print("test"`
insert into a second cell:
`from matplotlib import pyplot as plt 
for i in range(5):
    plt.figure()
    plt.plot(range(10), range(10))
    plt.show()`

run the notebook. (larger numbers lead to the same problem, so it is not just that the threshold is not reached

**Comment by joyceerhl** [comment]
@tobiasharren are you using the new native notebooks interface, i.e. it looks like the following?

![image](https://user-images.githubusercontent.com/30305945/116117078-b3eaf580-a670-11eb-83c5-b4470bd3d50b.png)

There doesn't seem to be a way to configure this in VS Code settings:

![image](https://user-images.githubusercontent.com/30305945/116117246-dc72ef80-a670-11eb-89a4-32bede78f688.png)

Note for engineering triage: we should file this as an upstream issue on VS Code.

**Comment by tobiasharren** [comment]
@joyceerhl thank you for your reply!
Yes that is exactly, what it looks like!

Is it then possible to not apply the native notebooks interface, while this does not work yet?
When right clicking and choosing "Open With" for .ipynb files, I get three choices (as seen in the picture):
![vs](https://user-images.githubusercontent.com/49845179/116118719-e5d67900-a6bd-11eb-8fd5-e815f64513a9.png)
the first second one opens the notebook interface as before.
the third goes into an infinite loading progress for my notebook.

**Comment by joyceerhl** [comment]
Yes, you can opt out as follows:

1. Open the command palette (Ctrl+Shift+P on Windows, Cmd+Shift+P on Mac)
2. Type 'Preferences: Open Settings (JSON)' and select the first option to open your user settings.json file Command palette
3. Add the following line to your user settings.json file:
```
"jupyter.experiments.optOutFrom": ["NativeNotebookEditor"],
```
4. If the following entry is present in your user settings.json file, __delete__ it:
```
"workbench.editorAssociations": [
  {
    "viewType": "jupyter-notebook",
    "filenamePattern": "*.ipynb"
  }
]
```
5. Reload Visual Studio Code for the new settings to take effect. You should be opted back into the old Jupyter notebook interface.

**Comment by joyceerhl** [comment]
Closing this issue as we are already tracking this issue in https://github.com/microsoft/vscode-jupyter/issues/4406. @tobiasharren please feel free to file a new issue if you run into any other issues.
