### ISSUE TITLE
Widgets do not get downloaded in CodeSpaces

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5633]

**Comment by rchiodo** [comment]
Waiting for codespaces/vscode to resolve CORS issue.

**Comment by joyceerhl** [comment]
We should check if abovementioned CORS issue has been fixed.

**Comment by IanMatthewHuff** [comment]
Looks good. Got the third party warning and it worked:
![image](https://user-images.githubusercontent.com/812783/135511615-dae86731-ac7e-48ef-9092-30143b4b4001.png)
