### ISSUE TITLE
Output dragged to last run cell.

### ISSUE THREAD

**Issue by grudloff** [microsoft/vscode-jupyter#5641]
## Environment data

-   VS Code version: 1.56.0-insider
-   Jupyter Extension version: v2021.6.780948196
-   Python Extension version: v2021.5.756443519-dev
-   OS:  Windows_NT x64 10.0.19041
-   Python and/or Anaconda version: Python 3.8.8 & conda 4.9.2
-   Type of virtual environment used: conda
-   Jupyter server running: Local

The output from cells gets dragged down to the last run cell. So for example, if I run cell 1 and then 2 before 1 finishes, the output of both goes to the output of 2. If I do the same with multiple cells, the same happens, all is dragged to the last cell.

Don't know if it is related but this issue arises in the same environment as issue #5636.

**Comment by IanMatthewHuff** [comment]
@grudloff I believe that this issue is going to be fixed by the same fix as #5636. So I'm going to close this issue for now. When the fix for #5636 hits if you still see this issue then comment here and I can reactivate.
