### ISSUE TITLE
Ctrl + Z should undo the cell changes first (Or should not undo the outputs)

### ISSUE THREAD

**Issue by Kingwl** [microsoft/vscode-jupyter#5643]
## Environment data

-   VS Code version: 1.55.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.745244803
-   Python Extension version (available under the Extensions sidebar): v2021.4.765268190
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version:  N/A
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

`Ctrl + Z` should undo changes in the cell if cell has been focused.  And I'm also not sure should `Ctrl+Z` can undo the outputs? (IMO: Not)

## Actual behaviour

Outputs will be undone rather than the cell.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Prepare a simple notebook:
![image](https://user-images.githubusercontent.com/6831019/116205770-a6b53000-a770-11eb-9d61-17612998f135.png)

2. Run the cell and type something in the cell before cell runs done:
![image](https://user-images.githubusercontent.com/6831019/116205966-dd8b4600-a770-11eb-9adf-05f371b09a33.png)

3. Click the cell to make sure the cell has been focused:
![image](https://user-images.githubusercontent.com/6831019/116206104-0c092100-a771-11eb-82fe-5c657db83766.png)

4. `Ctrl + Z`, Outputs disappeared.
![image](https://user-images.githubusercontent.com/6831019/116206139-15928900-a771-11eb-84ed-e505c3132796.png)

5. `Ctrl + Z`, Code undo.
![image](https://user-images.githubusercontent.com/6831019/116206310-3c50bf80-a771-11eb-9673-ecd9c5134fc9.png)

## Logs

Not important

**Comment by IanMatthewHuff** [comment]
@Kingwl Thanks for filing this. Could you take a look at these same scenarios in vscode-insiders? In vscode-insiders we are rolling out a new UI, this one based on the VS Code provided notebook API. I don't believe that we would fix the old UI at this point, but it would be good to know if you are seeing the same issue in the new UI as well.

**Comment by Kingwl** [comment]
VSCode Insider works fine. 

BTW: Are there any workaround about this?

**Comment by IanMatthewHuff** [comment]
I don't believe there is a current workaround on this. We can discuss at our triage meeting (Thursday) about what we'd expect Ctrl-Z to do in this situation. If we have agreement from our team on this change I could help point you are the code area for making this fix. Our focus is really heavily on the new UI currently, so we'd be unlikely to fix it ourselves.

**Comment by rchiodo** [comment]
It's unlikely we'll fix this but if @Kingwl you'd like to submit a PR, we're willing to point you to where to look.

**Comment by Kingwl** [comment]
>we're willing to point you to where to look. 

Aye. My pleasure.

**Comment by IanMatthewHuff** [comment]
Sorry forgot to drop a pointer here. So the old webviews use React / Redux for UI and state management. The code here is the reducers for undo and redo operations.
https://github.com/microsoft/vscode-jupyter/blob/9c234e1aeb8ee4f6e65a3b2a763d28ebc94a2ad6/src/datascience-ui/history-react/redux/reducers/execution.ts#L21
If you check where items are being added or removed from those undo / redo stacks you should be able to see if some state change that should not be undoable is getting added to the undo stack.

**Comment by Kingwl** [comment]
Thanks! And I'm not sure does the output can be undo？Would you mind give me some suggestion too？

**Comment by Kingwl** [comment]
Oh. BTW. We have a custom widget based on the webview notebook. And I saw the https://code.visualstudio.com/updates/v1_56#_native-notebooks.

I'm a little worry about the compatible about them (Actually there's already not compatible sometimes ago).
Would you mind share me the plan or roadmap to ship the native notebook? 
It's very helpful to planning (and prioritizing) the compatible test or adaptation work.
Thanks!

**Comment by Kingwl** [comment]
Sorry for pushing. Up.

**Comment by joyceerhl** [comment]
@Kingwl Let's sync offline--I'll set up time with you to chat.

**Comment by Kingwl** [comment]
Thanks to the team!
