### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.enumerations'

### ISSUE THREAD

**Issue by zohimchandani** [microsoft/vscode-jupyter#5649]
## Environment data

-   VS Code version: 1.55.2
-   Extension version (available under the Extensions sidebar):
-   OS and version: Win10
-   Python version (& distribution if applicable, e.g. Anaconda):  v2021.4.765268190
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: XXX

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

When I try run `classifier_test` which should import a package from another file, the import is not recognised and hence the module is not imported. 

## Actual behaviour

Module should be imported and no error should be given

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

![image](https://user-images.githubusercontent.com/60148725/116247417-bd548a80-a762-11eb-8da5-472fabc91734.png)

**Comment by IanMatthewHuff** [comment]
@zohimchandani It looks like you are trying to import a local module into your notebook. To get those picked up you might have to adjust the sys.path of the python interpreter that you are running. This doc here would have an example of this, can you check out adjusting your path like this?
https://mg.readthedocs.io/importing-local-python-modules-from-jupyter-notebooks/sys-path-in-notebook/path-notebook.html

**Comment by greazer** [comment]
Issues labeled with "Info needed" are closed if we do not receive more information from the issue author in 2 weeks. If you are the issue author and you still are running into this problem, please reactivate with additional information.
