### ISSUE TITLE
FindMatchingInterpreter matching on interpreter path

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#5650]
Noticed this in a semi-related PR here.

https://github.com/microsoft/vscode-jupyter/pull/5644#pullrequestreview-646103184

In FindMatchingInterpreter it's matching based on the path of the interpreter. I believe this might be an issue as "Interpreters" here is actually PythonEnvironments, and for Conda I believe you can have multiple environments with the same interpreter path if you don't specify the python version when creating the env.

**Comment by rchiodo** [comment]
We need to rethink how we uniquely identify PythonEnvironments.

**Comment by greazer** [comment]
We should add telemetry to see how many users fall into this category. Not necessary for June though.

**Comment by IanMatthewHuff** [comment]
Repro for this.

Create a conda env. Then you can create named conda kernelspec like this:
(dupe1) Ians-MacBook-Pro:~ ianhuff$ python -m ipykernel install --user --name dupeEnvUno --display-name "Dupe Env Uno"
Installed kernelspec dupeEnvUno in /Users/ianhuff/Library/Jupyter/kernels/dupeenvuno
(dupe1) Ians-MacBook-Pro:~ ianhuff$ python -m ipykernel install --user --name dupeEnvDos --display-name "Dupe Env Dos"
Installed kernelspec dupeEnvDos in /Users/ianhuff/Library/Jupyter/kernels/dupeenvdos

These will all get startUsingPythonInterpreter kernelConnectionMetadata and they will all have the same path. Find preferredKernel in helpers.ts matches only on path in a couple of places. If using old webview you run with "Dupe Env Uno" and save the file. The next time you open it you might get your kernel switched to the main conda env (dupe1) or "Dupe Env Dos" it's all ordering dependent.

The interactive window part usually works since the current interpreter is first in the list, so it usually gets matched before the other ones, but that is ordering dependent to some degree as well.

**Comment by rchiodo** [comment]
These are just completely skipped now. Seems wrong to me? Kernelspec might have a custom env.

**Comment by rchiodo** [comment]
This works fine if the custom kernelspecs are any different than the default kernelspec.
