### ISSUE TITLE
Native Notebooks - User should be prompted to install matching extension when opening a notebook based on embedded kernel info

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5651]
If a user opens up a notebook (in any way) and the correct kernel is not installed, there should be a clear way to inform the user and prompt to have them install the correct extension.

**Comment by DonJayamanne** [comment]
> there should be a clear way to inform the user and prompt to have them install the correct kernel.

Why do we need such a thing?
Today wth all of our python users we don't do this. I feel we'll end up spamming the uses with popups now.

**Comment by rchiodo** [comment]
The goal is to install the .NET interactive extension if somebody opens a .NET notebook. Or the julia extension if somebody opens a notebook with a Julia kernel (or the python extension if somebody opens a notebook with a python kernel)

**Comment by DonJayamanne** [comment]
> inform the user and prompt to have them install the correct kernel.

This should then read install correct `extension`

**Comment by claudiaregio** [comment]
@DonJayamanne fixed

**Comment by joyceerhl** [comment]
![image](https://user-images.githubusercontent.com/30305945/116749385-b4a7c280-a9b5-11eb-82a8-e94ed89fa8c0.png)

Sorry to do this @DonJayamanne but '.NET Interactive NotebooksPreview' should be '.NET Interactive Notebooks Preview' in
https://github.com/microsoft/vscode-jupyter/pull/5690/files#diff-840246f578e39f866bd9595486e1b8f423f378a35f7fdcf5c68e3e908f71b048R129

**Comment by DonJayamanne** [comment]
Damn it, i copied it from the interweb...
Oh well. good pick

**Comment by joyceerhl** [comment]
Validated: 

![image](https://user-images.githubusercontent.com/30305945/118435530-ff069000-b693-11eb-8244-e5d38a42f9e7.png)
