### ISSUE TITLE
Native Notebooks - Jupyter Start Page

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5652]
Explore Jupyter start page that includes creating new notebooks with UI gesture such as JupyterLab and educational links or content to help explore new languages.

**Comment by greazer** [comment]
Probably not required for May

**Comment by DonJayamanne** [comment]
**I'd suggest a start page that uses the VS Code infrastructure (with our own content)**
https://github.com/microsoft/vscode-jupyter/issues/5154

**Comment by claudiaregio** [comment]
@DonJayamanne not a dupe, will have different content and different actions displayed so we can leave it for now
