### ISSUE TITLE
Fix 'local' and 'remote' notebook tests

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#5660]
This PR here:
https://github.com/microsoft/vscode-jupyter/pull/5635

Got the 'raw' 'notebook' tests for conda and nonConda down to just two failure. But there are issues still with the initial kernel selection in the 'local' and 'remote' cases. Need to look more into that, but they are working

**Comment by IanMatthewHuff** [comment]
validation note, there are individual failures, but the main 15+ suites failing issues in 'remote' and 'local' are resolved.

**Comment by DonJayamanne** [comment]
Valdiated
