### ISSUE TITLE
Enhancement: Add support for R

### ISSUE THREAD

**Issue by Lovely-Qianyun** [microsoft/vscode-jupyter#5664]
Jupyter notebook is a brilliant interactive computing notebook environment for many languages.  At present, the kernel of jupyter notebook can provide support for R.  
It couldn't be better if support like linting, auto-completion and formatting for R can be added in this extension!  
![image](https://user-images.githubusercontent.com/76724881/116344589-15e65f00-a819-11eb-8581-6c1f7cde3d24.png)

**Comment by rchiodo** [comment]
Thanks for the suggestion. 

We'd love to support R as well as Python, Julia, and others, but generally the jupyter extension isn't going to provide language specific features. Instead we expect other extensions to do that work. This one might be a good place to log a suggestion to support notebooks:

https://github.com/MikhailArkhipov/vscode-r
