### ISSUE TITLE
Cells Reloaded Out of Order

### ISSUE THREAD

**Issue by davzaman** [microsoft/vscode-jupyter#5667]
Issue Type: <b>Bug</b>

Reloaded window which had a jupyter notebook open and all my cells are out of order.

Extension version: 2021.6.792062886
VS Code version: Code - Insiders 1.56.0-insider (Universal) (7ce1499d9541ba2acf66cd30a9054bd7818a8f80, 2021-04-22T05:12:09.510Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 5.0.0-37-generic
Fetching remote diagnostics for 'SSH: lambda2.cs.ucla.edu' failed: Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (2.53GB free)|
|Process Argv|-psn_0_110619 --crash-reporter-id e36ddcb5-d3f9-4b36-9f9b-a02f63800663|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: lambda2.cs.ucla.edu|
|OS|Linux x64 5.0.0-37-generic|
|CPUs|Intel(R) Core(TM) i9-9960X CPU @ 3.10GHz (32 x 1200)|
|Memory (System)|125.58GB (56.46GB free)|
|VM|0%|

Fetching remote diagnostics for 'SSH: lambda2.cs.ucla.edu' failed: Canceled
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
vstes627:30244334
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30286553
vscgsv2:30286872

```

</details>

**Comment by rchiodo** [comment]
Thanks for the bug. I believe this would be something that VS code would handle (given that you're using insiders).

**Comment by davzaman** [comment]
This is the first time it happened but it was not a UI bug. I opened up the notebook separately in Jupyter Lab and my cells were in the same (incorrect) order showing on VS Code. I can try to reproduce the problem and get back to you with a toy notebook.

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed with new native support for editing notebooks. To opt into that experience see: https://github.com/microsoft/vscode-jupyter/wiki/Introducing-Native-Notebooks.
