### ISSUE TITLE
"Kernel died with exit code 1" when trying to run code on interactive window 

### ISSUE THREAD

**Issue by malikdoole** [microsoft/vscode-jupyter#5689]
Hi,
I used to be able to run my python file using the interactive window. However, all of a sudden, I keep getting the following error "Kernel died with exit code 1" when I try to run my current file on the interactive window. How do I fix this issue?
Thanks.

Environment data

-   VS Code version: 1.55.2
-   Jupyter Extension version: 2021.5.1
-   Python Extension version: 2021.4.0
-   OS: Windows 10
-   Python and/or Anaconda version: 3.7.6 64-bit
-   Type of virtual environment used: conda
-   Jupyter server running: Local 

## Expected behaviour
Runs current file in the interactive window
## Actual behaviour
Kernel died with exit code 1. Traceback (most recent call last): File "C:\Users\username\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "C:\Users\username\Anaconda3\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\username\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module> from ipykernel import kernelapp as app File "C:\Users\username\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module> from .connect import * File "C:\Users\username\Anaconda3\lib\site-packages\ipykernel\connect.py", line 18, in <module> import jupyter_client File "C:\Users\username\Anaconda3\lib\site-packages\jupyter_client\__init__.py", line 4, in <module> from .connect import * File "C:\Users\username\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 24, in <module> import zmq File "C:\Users\username\Anaconda3\lib\site-packages\zmq\__init__.py", line 4...

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
Looks like zmq package is no longer working as expected. Possible you updated this or some other package or the python environment accidentally that caused this issue.

Please could you try to re-install ipykernel as follows:
```conda install ipykernel --update-deps```
if that doesn't work then try
```conda install ipykernel --update-deps --force-reinstall```

**Comment by malikdoole** [comment]
Thanks! Your solution worked.

**Comment by malikdoole** [comment]
@DonJayamanne - the second option worked.
