### ISSUE TITLE
What do we do if user opens a rust notebook and rust kernel does not exist

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5699]
Assume user opens a rust notebook and they do not have rust kernel installed.
* We do not provide a preferred kernel to VS Code
* VS Code will display the first available kernel
* Its possible Python will be the first kernel

**Solutions**
* Leave as is
* Add a dummy kernel with the name `rust` and set this as preferred
	* When they try to run, we display a message indicating the fact that such a kernel doesn't exist
	* Drawbacks - wat if someone tomorrow creates an extension that supports `rust`
* If user tries to run a cell against a `Python` kernel we warn the user about this
* Add another priority to preferred kernels in VS Code:
	* Default
	* FallBack - If theres no preferred, then use the one that has a `fallback`
		* This should only be applicable if there are no prefferred items.
	* Preferred

**Comment by rchiodo** [comment]
If no preferred kernel, VS code should show some way for the user to pick.

**Comment by rchiodo** [comment]
I don't think anybody has complained about this? I think this would be handled by the UI in VS code for finding more kernel providers that @misolori  is/was working on.
