### ISSUE TITLE
azureml_widgets not working in vs code 

### ISSUE THREAD

**Issue by ansaxena1** [microsoft/vscode-jupyter#5704]
## Environment data

-   VS Code version: 1.55.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.745244803
-   Python Extension version (available under the Extensions sidebar): v2021.4.765268190
-   OS (Windows | Mac | Linux distro) and version: Windows 20H2
-   Python and/or Anaconda version: 3.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A: remote

## Expected behaviour

Widget should be displayed.

## Actual behaviour

Error output: "Error: Module azureml_widgets, semver range ^1.0.0 is not registered as a widget module."

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

Run notebook included in bug: https://github.com/microsoft/vscode-jupyter/issues/5496

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
@ansaxena1 Please can you use a simpler sample in the future, its easier to use the following:
```python
from azureml.core import Workspace, Experiment, ScriptRunConfig
from azureml.widgets import RunDetails

ws = Workspace.from_config()
experiment = Experiment(workspace=ws, name='day1-experiment-hello')

config = ScriptRunConfig(source_directory='./code/hello', script='hello.py', compute_target='TestComputeForDon')

run = experiment.submit(config)
RunDetails(run).show()
```

**Comment by DonJayamanne** [comment]
Works for me
![Screen Shot 2021-04-29 at 15 37 44](https://user-images.githubusercontent.com/1948812/116626856-e0b53c00-a900-11eb-80d2-71d83e19c758.png)

@ansaxena1 
Please could you try this again & then share the logs

**Comment by ansaxena1** [comment]
This seems to be working now.
