### ISSUE TITLE
Test Native Notebooks with widgets in Remote Container (SSH/DevContainer or CodeSpaces)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5709]
Test in a remote.

**Comment by joyceerhl** [comment]
Widgets don't work in any of these scenarios. We need either an automated test or a manual test plan entry.

**Comment by rchiodo** [comment]
Now that we have a web extension, probably easiest to add an ipywidget test for web.

**Comment by rchiodo** [comment]
Although ipywidgets don't work in web yet (haven't figured out download story yet).

**Comment by DonJayamanne** [comment]
> (haven't figured out download story yet).

Any reason we cannot create a folder in the same temp directory using the VS Code API (`Uri.joinPath(context.extensionUri, 'temp')`). I thought it would work. But haven't tried that

**Comment by rchiodo** [comment]
Theoretically that should work. Haven't tried it yet.

**Comment by DonJayamanne** [comment]
This should be fixed now,

**Comment by DonJayamanne** [comment]
TODO: Validate widgets in CodeSpaces
