### ISSUE TITLE
Kernel Interrupt: pending cells are always timing out

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-jupyter#5713]
According to this comment:
https://github.com/microsoft/vscode-jupyter/blob/main/src/client/datascience/jupyter/kernels/kernelExecution.ts#L191

Its not up to us, so we ask the user to restart the kernel.

**Comment by DonJayamanne** [comment]
This comment merely means that if interrupt fails, the user will need to restart the kernel (which is what we do today), hence not sure what you're trying to say here.

**Comment by DavidKutu** [comment]
I'm not sure if its up to us, this issue is to figure that out.
If there's nothing to do, the tests should remain skipped or check that the restart message appears.

**Comment by DavidKutu** [comment]
This is still flakey
https://github.com/microsoft/vscode-jupyter/runs/2479902588?check_suite_focus=true

(That contains the #5717 fix and reenabled the tests)

**Comment by DonJayamanne** [comment]
I'll look into this, thanks.

**Comment by DonJayamanne** [comment]
Based on the logs the interrupt request was not sent out.

**Comment by DonJayamanne** [comment]
This is no longer an issue, hence closing this.
