### ISSUE TITLE
If user opts out of NativeNotebookEditor experiment, workbench.editorAssociations is not updated

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5719]
This means setting jupyter.experiments.optOutFrom isn't sufficient, because the editorAssociation is still there, so we force the user back into the experiment. If the user has opted out of NativeNotebookEditor experiment we should also remove our editorAssociation for the 'jupyter-notebook' viewType:

```
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter-notebook",
            "filenamePattern": "*.ipynb"
        }
    ],
```

Otherwise functionally it's going to look to users like they can't opt out at all.

**Comment by joyceerhl** [comment]
If the user sets the NativeNotebookExperiment in their optOut settings we should remove this setting.

**Comment by greazer** [comment]
I have been able to optout after opting in manually to native notebooks and again see our old custom editor implementation. I still have workbench.editorAssociations in my settings.
