### ISSUE TITLE
Don't change the notebook metadata if the user only opens or trusts a notebook

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-jupyter#5721]
We're changing the metadata in the notebook too soon.

To test that, modify [this test](https://github.com/microsoft/vscode-jupyter/blob/e507d6e7111141d4312ec7cfbdfb217818ba6b4e/src/test/datascience/notebook/contentProvider.vscode.test.ts#L198) to compare the full JSON instead of just the cells.

**Comment by joyceerhl** [comment]
We should validate this now.

**Comment by DavidKutu** [comment]
not validated,
to test this the `Verify generation of NotebookJson` test should open a notebook, trust it, and then assert that the contents have not changed.

**Comment by greazer** [comment]
I think @rebornix fix for notebooks being dirty on open will address this? Just closing for validation in August.
