### ISSUE TITLE
Cannot prevent unwanted workbench.editorAssociations from being added automatically

### ISSUE THREAD

**Issue by Lewington-pitsos** [microsoft/vscode-jupyter#5724]
## Environment data

-   VS Code version: 1.55.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.745244803
-   Python Extension version (available under the Extensions sidebar): v2021.4.765268190
-   OS (Windows | Mac | Linux distro) and version: Ubunut 18.04
-   Python and/or Anaconda version: Python 3.6.9, no anaconda
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): root python

## Expected behaviour

my `.vscode/settings.json` doesn't get anything added to it automatically, and I can open `.ipynb` files as regular JSON

## Actual behavior

my `.vscode/settings.json` gets a `workbench.editorAssociations` that I do not want added to it on reload, and there seems to be no way stop this. As a consiquence by default my `.ipynb` files always open in jupyter unless I manually edit my `.vscode/settings.json` every reload.

## Steps to reproduce:

1. install vscode
2. install the main Python extension
3. make a `.ipynb` file
4. edit `.vscode/settings.json` so it looks like:

```
{
    "python.dataScience.useNotebookEditor": false,
    "jupyter.useNotebookEditor": false   
}
```
5. reload vscode

Suddenly NOW `.vscode/settings.json` looks like

```
{
    "python.dataScience.useNotebookEditor": false,
    "jupyter.useNotebookEditor": false,
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter.notebook.ipynb",
            "filenamePattern": "*.ipynb"
        }
    ]   
}
```

**Comment by Lewington-pitsos** [comment]
Arguably this is a feature request, or even just asking for advice (something that should have just been posted on stackoverflow), but many sources, including recent comments on this repository, seem to claim that setting one of 

```
"python.dataScience.useNotebookEditor": false,
"jupyter.useNotebookEditor": false,
```

Should allow me to view `.ipynb` files as JSON, and this does not seem to be the case. If there is a correct way to achieve this it is not documented anywhere I have checked.

**Comment by joyceerhl** [comment]
The "jupyter.useNotebookEditor" setting was recently deprecated. Are you able to open as JSON by following these steps?
https://stackoverflow.com/questions/66941324/vs-code-jupyter-extension-source-view/66961774#66961774

**Comment by joyceerhl** [comment]
If you want your ipynb files to __always__ open as JSON, you can click the gear icon on the right of the 'Text Editor' option:

![image](https://user-images.githubusercontent.com/30305945/116797264-be562680-aa98-11eb-955b-27f9676a702b.png)

**Comment by Lewington-pitsos** [comment]
This definitely solved my issue. When I have a little more time I will make a documentation PR about this.
