### ISSUE TITLE
Shift+Enter does not run all selected cells

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#5739]
Issue Type: <b>Bug</b>

* Select two cells by shift+arrow down
* Shift+enter

It only runs the second cell

Extension version: 2021.6.806304047
VS Code version: Code - Insiders 1.56.0-insider (Universal) (4e185d8986339717e593be19bc75288905ffbb51, 2021-04-30T23:19:25.345Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.14GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonvspyt551cf:30291413
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30296409
vscgsv2:30286872
vscorehovct:30295782

```

</details>

**Comment by IanMatthewHuff** [comment]
@rebornix the controller is getting called directly from VS Code with only one cell to execute in this scenario. Pretty sure that would be on the VS Code side needing to pass in all the cells to execute handler, right?

![image](https://user-images.githubusercontent.com/812783/117084968-6c620a80-acfd-11eb-89df-ceea88b8ccb9.png)

**Comment by joyceerhl** [comment]
This may be caused by https://github.com/microsoft/vscode/issues/123024. The Jupyter extension doesn't customize the Shift+Enter shortcut.

**Comment by rebornix** [comment]
This is working fine now in latest VS Code Insiders.
