### ISSUE TITLE
Custom Editor only work for the first time

### ISSUE THREAD

**Issue by KirisameMarisaa** [microsoft/vscode-jupyter#5740]
## Environment data

-   VS Code version: 1.55.2 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.745244803
-   Python Extension version (available under the Extensions sidebar): v2021.4.765268190
-   OS (Windows | Mac | Linux distro) and version: macOS 10.15.6
-   Python and/or Anaconda version: Python 3.7.2 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

The custom editor should work whenever I open VSCode, and native editor will never appear

## Actual behaviour

Custom Editor only work when:
1. After done a clean install of VSCode, but will no longer work after restarting VSCode
2. Start VSCode after Delete `~/Library/Application Support/Code/User/globalStorage`

If I don't delete the 'globalStorage' directory:
1. Opening `.ipynb`  file with the Custom editor will lead to blank screen and infinite progress bar, with no outputs in `OPTPUT` debug console.
2. The default jupyter editor setting in `Settings.json` will be forced to change from `jupyter.notebook.ipynb` to `jupyter-notebook`
3. Only Native Editor work.
 

## Steps to reproduce:

1. Do a clean install of the latest stable version of VSCode
2. Install Python and Jupyter extension
3. open any Jupyter Notebook, it can be opened flawlessly.
4. restart VSCode and try to open any Jupyter Notebook in Custom Editor, this time the Custom Editor will no longer work

## Logs

None

**Comment by IanMatthewHuff** [comment]
@KirisameMarisaa Can you try adding the following to your settings file? 
    "jupyter.experiments.optOutFrom": ["NativeNotebookEditor"],
Might need to reload / clear the editor association after that.

**Comment by KirisameMarisaa** [comment]
Works flawlessly this time, thank you for offering the solution.
