### ISSUE TITLE
Failed to find a kernelspec to use for ipykernel launch

### ISSUE THREAD

**Issue by borjaureta** [microsoft/vscode-jupyter#5741]
Issue Type: <b>Bug</b>

I can't run any of the code I have on an ipynb file because it doesn't activate the kernel. I always get message "failed to find a kernelspec to use for ipykernel launch"

Extension version: 2021.4.765268190
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.38GB (6.25GB free)|
|Process Argv|--crash-reporter-id 7f654836-9f15-46ef-962c-bcd6ef80db7b|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553

```

</details>

lipboard because it was too large to send. Please paste.

**Comment by IanMatthewHuff** [comment]
@borjaureta Can you please set Jupyter.Logging.Level setting to "debug" and re-run your launch scenario? After rerunning you could copy out the contents of the Output->Jupyter window. That should have our detailed diagnostic information so that we can look into this.

**Comment by greazer** [comment]
Issues labeled with "Info needed" are closed if we do not receive more information from the issue author in 2 weeks. If you are the issue author and you still are running into this problem, please reactivate with additional information.
