### ISSUE TITLE
wrong kernel choice

### ISSUE THREAD

**Issue by StephaneKazmierczak** [microsoft/vscode-jupyter#5743]
Issue Type: <b>Bug</b>

jupyter extension doesn't find the local kernel while working on a notebook (local wsl conda env). Instead it give me kernel options that are on a remote machine ... 
I am currently getting similar bug while using stable or insider build of vscode and have experienced similar problem on and off for the last couple of months and versions.  
Is there a way to simply set the kernel using a path in the settings ? 

Extension version: 2021.5.745244803
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.65GB free)|
|Process Argv|--crash-reporter-id 5f564a54-8aac-4d61-a68a-1a5ee14df08a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|Memory (System)|12.36GB (10.43GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vscnewfiletext:30294816
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30294353

```

</details>

**Comment by StephaneKazmierczak** [comment]
somehow it eventually found the good kernel after restarting vscode many times, and activated it correctly after another couple of restart.

**Comment by IanMatthewHuff** [comment]
@StephaneKazmierczak sorry about this issue here. If you see the issue again, you can set jupyter.logging.level to "debug" in setting. Then in the Output->Jupyter window you can copy out the contents there and paste them in a comment here. That has our detailed diagnostic info that we could use to debug this.

**Comment by StephaneKazmierczak** [comment]
Thanks @IanMatthewHuff, I will do that if I get the issue again !

**Comment by greazer** [comment]
@StephaneKazmierczak, please reopen if this happens again.
