### ISSUE TITLE
link shortcuts from editor to interactive window

### ISSUE THREAD

**Issue by sbland** [microsoft/vscode-jupyter#5744]
There doesn't seem to be a way to link shortcuts such as `Jupyter: Restart Jupyter Kernal` for use when focused on the editor. Is this possible to implement?

**Comment by IanMatthewHuff** [comment]
@sbland Do you mean just to have that command work when focus is in the code editor as opposed to directly in the interactive window? Yes, I do repro the same thing as you. We do have the ability to have multiple interactive windows open at one time, so in that case we might not know which interactive window to restart (the same file can send code to different interactive windows). But in the case that there is just one we should be able to support this.

**Comment by sbland** [comment]
@IanMatthewHuff Yes exactly. Currently the shortcut `ctrl + Enter` links to a specific interactive window. It has the keybinding **when** set as `editorTextFocus && jupyter.hascodecells && !editorHasSelection && !jupyter.havenativecells && !notebookEditorFocused`. If I try copying this when to the command `Jupyter: Restart Jupyter Kernal` it has no effect.

**Comment by amunger** [comment]
the `jupyter: restart kernel` should be working when focus is on the relevant .py file. Let us know if you are still having issues with this.
