### ISSUE TITLE
Interactive content jumps because of dynamic toolbar resizing

### ISSUE THREAD

**Issue by daeh** [microsoft/vscode-jupyter#5749]
## Environment data

-   VS Code version: 1.55.2
-   Extension version: v2021.4.76526819
-   OS and version: MacOS 11.3.1
-   Python version: Anaconda 3.8.8
-   Type of virtual environment used: conda
-   Value of the `python.languageServer` setting: Pylance

## Actual behaviour

The toolbar in the interactive window spastically adds/removes a row causing the content to jump. Seems related to mouse movement in the other pane but I'm not sure what specifically triggers it.

https://user-images.githubusercontent.com/12652166/117053648-3580fa00-ace7-11eb-8748-e149319bff9d.mov

![output](https://user-images.githubusercontent.com/12652166/117055202-e76cf600-ace8-11eb-8421-82be9b3c2721.gif)

## Steps to reproduce:

Have interactive pane open, move mouse over code in an adjacent pane.

Thanks for the help!

**Comment by joyceerhl** [comment]
This is because hovering over a variable name causes us to run code in the interactive window's Jupyter kernel to display tooltips containing information about that variable. This causes the kernel status text to change and the entire toolbar to resize. We should probably allow kernel status text to wrap onto the next line so it's visible in narrow viewports.

**Comment by IanMatthewHuff** [comment]
Yeah, it's an awkward visual effect. It's super visible as well with things like dragging a widget slider as it continually goes Busy => Idle on the kernel status.

**Comment by joyceerhl** [comment]
@daeh This is resolved in the [preview interactive window](https://code.visualstudio.com/updates/v1_58#_jupyter-interactive-window), which features improved VS Code workbench integration and is currently the default in VS Code Insiders. Please let us know if it works for you and give us any feedback you have about the new experience 😊 If you find any bugs or have concerns, please file a new issue at https://github.com/microsoft/vscode-jupyter/issues so we can fix it. Thank you!
