### ISSUE TITLE
Refresh Data Viewer command should only appear in palette when a data viewer is active

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5752]
Right now it's always visible (oversight on my part). Also the capitalization is inconsistent with other command palette command names.

**Comment by IanMatthewHuff** [comment]
Validated:
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/ad7175cb-5fa1-4389-a821-14fb1980dfe2)
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/63096fac-4fb7-4bb0-b17d-a3d6668a76eb)
