### ISSUE TITLE
Can't execute cell and no Python option for cell type

### ISSUE THREAD

**Issue by sahitono** [microsoft/vscode-jupyter#5763]
Issue Type: <b>Bug</b>

1. Install the latest daily insider python and jupyter.
2. create new blank jupyter
3. select python as interpreter
4. cell can't be run with shift+enter or ctrl+enter. play button beside cell is not working too.
5. there is no option to change the cell type into python

Extension version: 2021.6.811652604
VS Code version: Code - Insiders 1.56.0-insider (8aff878db2542eea2dfb571c8bb485118bbb3113, 2021-04-19T05:15:35.845Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.43GB free)|
|Process Argv|--crash-reporter-id e5d8f13e-4e34-437c-b385-a6434494ec11|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30296409
vscgsv2:30286872
vscorehov:30295781

```

</details>

**Comment by joyceerhl** [comment]
Hi @sahitono would you mind updating to this VS Code Insiders build and trying again please? 

Version: 1.56.0-insider (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T21:56:48.403Z

**Comment by sahitono** [comment]
@joyceerhl updated and it is resolved. thank you! i'll close it.
