### ISSUE TITLE
Plots rendererd/generated in VS Code are not visible in Jupyter (ipynb portability issue)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5765]
* Open a notebook, generate a plotly plot
* Save & open in jupyter
* Plots do not appear

We need to split the line breaks as we do with source code when saving in ipynb files.

**Comment by rchiodo** [comment]
I don't think the line breaks are a problem anymore but it looks like the plotly output has to be marked as trusted before it will open. This seems okay to me.
