### ISSUE TITLE
Run Above/Below running the wrong cells

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5766]
* Create a notebook with 2 cells
* Select the first cell
* CLick the toolbar icon `run below` for the second cell and it will run the first cell
This is because VS Code sends the first cell as an argument to the click event of the toolbar of the second cell.

https://github.com/microsoft/vscode/issues/123002
https://github.com/microsoft/vscode/issues/123024

**Comment by DonJayamanne** [comment]
Solution - Use VS Code Command to run a cell instead of using controller.

**Comment by joyceerhl** [comment]
Validated. In Insiders following the original repro steps we now run the second cell.
