### ISSUE TITLE
Support other package managers besides pip/conda

### ISSUE THREAD

**Issue by xareelee** [microsoft/vscode-jupyter#5773]
I'm using PEP582 featured Python package manager (e.g. PyFlow or PDM) which installs local packages in `{project_path}/__pypackages__` folder.

The problem is that I did not find a way to set Jupyter Server to find ipykernel in `{project_path}/__pypackages__`. VSCode asks me to install ipykernel by `pip`, but I've already install it locally in `{project_path}/__pypackages__`.

I need a way to [run a Jupyter Cell (ctrl + enter) in my python code with `#%%`](https://code.visualstudio.com/docs/python/jupyter-support-py#_jupyter-code-cells) which would find the **ipykernel** in **`{project_path}/__pypackages__`**.

1. How do I config Jupyter Server properly to find ipykernel in `{project_path}/__pypackages__`?
2. How do I config `{project_path}/__pypackages__` for Python package search paths?

**Comment by rchiodo** [comment]
Thanks for the bug.

You might be able to work around this by setting the PYTHONPATH environment variable to search for packages in that ```__pypackages__``` folder you mentioned. I believe it would have to be set globally for the python we're launching to pick it up.

**Comment by xareelee** [comment]
@rchiodo 

VSCode did not launch the Jupyter Server with my local ipykernel installed in `{project_path}/__pypackages__`, even I [set `PYTHONPATH`](https://binx.io/blog/2020/03/05/setting-python-source-folders-vscode/).

settings.json:

```json
{
  "terminal.integrated.env.osx": {
    "PYTHONPATH": "${env:PYTHONPATH}:${workspaceFolder}/__pypackages__/3.7/lib",
  },
  "terminal.integrated.env.linux": {
    "PYTHONPATH": "${env:PYTHONPATH}:${workspaceFolder}/__pypackages__/3.7/lib",
  },
  "terminal.integrated.env.windows": {
    "PYTHONPATH": "${env:PYTHONPATH};${workspaceFolder}/__pypackages__/3.7/lib",
  },
  "python.envFile": "${workspaceFolder}/.env",
  "python.pythonPath": "/Users/xaree/.pyenv/versions/3.7.10/bin/python"
}
```

.env

```
PYTHONPATH=${PYTHONPATH}:./__pypackages__/3.7/lib
```

**Comment by rchiodo** [comment]
Hmm, '.env' files may not work. It depends upon your OS and how/when we're starting the kernel. 

What I should have said was set a global environment variable so that PYTHONPATH includes the ```full``` path to your packages folder.

**Comment by rchiodo** [comment]
Internally we should be doing this to determine if ipykernel needs installing:

```<your python path> -c "import ipykernel"```

If you can get that to work in a normal command prompt, that should let us find it too.

**Comment by xareelee** [comment]
@rchiodo 

Is there any way to print out current `PYTHONPATH` in VSCode? How could I set `PYTHONPATH` globally for VSCode to find ipykernel? I have no idea to find and set `PYTHONPATH` to launch Jupyter server correctly.

I found that VSCode launched by command line in shell are by GUI launcher are using different env. Is that true?

**Comment by rchiodo** [comment]
> Is there any way to print out current PYTHONPATH in VSCode? 

Print out the environment variable in a terminal. This depends upon your OS, but for windows it's just ```echo %PYTHONPATH%```

> How could I set PYTHONPATH globally for VSCode to find ipykernel?

Look up how to set global environment variables for your OS.

> I found that VSCode launched by command line in shell are by GUI launcher are using different env. Is that true?

Not sure what you mean by GUI launcher. You mean the shortcut that VS code installs? That will use your system environment. 

VS Code launched from a command line shell will use the environment of the command line.

**Comment by xareelee** [comment]
@rchiodo 

So, there is no way to configure how to find ipykernel to launch a Jupyter Server in VSCode, right? If true, could this be a feature request?

**Comment by rchiodo** [comment]
> configure how to find ipykernel to launch a Jupyter Server

This actually isn't something we always do. We start ipykernel by finding the ipykernel module but we're not running Jupyter most of the time (right now only M1 macs need to use Jupyter). So this setting wouldn't really make sense.

The problem you're having is specific to using a different package manager. So the request would be more like support other package managers besides pip and conda. 

The reason it works when you run from the command line is the environment is setup correctly to find the packages you installed with the other package manager.  VS code will inherit the environment from the command line shell. In fact this is the recommended way to get VS code to find packages when using conda too.

If you run this code it should list your ```__pypackages__``` in your sys path:

```python
import sys
print(sys.path)
```

That sys.path should be different if you run the same code from the gui launched VS code.

**Comment by xareelee** [comment]
> The problem you're having is specific to using a different package manager. So the request would be more like support other package managers besides pip and conda.

Yes, If only trying to solve my specific problem.

For abstract thinking in problem solving, I think the problem is: how to eliminate different behavior when launching a VSCode workspace with different ways (make it consistent).

I think there are many ways to solve this abstract question:

- specify additional module search paths for loading ipykernel in `settings.json`. (which currently is not available in [general settings](https://code.visualstudio.com/docs/python/settings-reference#_general-settings))
- make `PYTHONPATH` support finding `ipykernel` before launching. (which currently is not working in [`settings.json`](https://stackoverflow.com/a/58585415/1282160))
- give a way to setup environment for VSCode regardless how to launch it. (which currently is not working in [`.env`](https://code.visualstudio.com/docs/python/environments#_use-of-the-pythonpath-variable))

> That sys.path should be different if you run the same code from the gui launched VS code.

I found that setting `$PYTHONPATH` in VSCode doesn't help launch python code by **Command Palettes**:

- `Run code`
- `Python: Run Python File in Terminal`
- `Jupyter: Run Current Cell`

the `sys.path` will not contain my local packages (`__pypackages__/3.7/lib`).

I have no idea that is a bug or not. I need a way to load my local modules in Jupyter, including finding local ipykernel when launching.


> The reason it works when you run from the command line is the environment is setup correctly to find the packages you installed with the other package manager. VS code will inherit the environment from the command line shell. In fact this is the recommended way to get VS code to find packages when using conda too.

Thanks for your info, I finally know what is going on here.

**Comment by alexkyllo** [comment]
I recently gave PDM and PEP582 a try, and I get why launching it with `code .` from a shell in the project directory with `PYTHONPATH` set appropriately would work. 

Is there any such workaround when Remote SSH is involved, though? Is it possible to get the remote VS Code Server to launch from a specific shell environment?

**Comment by rchiodo** [comment]
> Is it possible to get the remote VS Code Server to launch from a specific shell environment?

Not that I know of. I'll try asking some people who would know.

**Comment by DonJayamanne** [comment]
Unfortunately there haven't been enough upvotes on this feature request, hence closing this issue
