### ISSUE TITLE
Unable to view image attachments in Markdown cells

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5774]
In Classic Jupyter one can insert images into markdown cells. The images are stored as base64 encoded metadata in the corresponding notebook cell.

The value in the markdown is as follows:
```![Screen%20Shot%202021-05-04%20at%2016.23.48.png](attachment:Screen%20Shot%202021-05-04%20at%2016.23.48.png)```

Note the `attachment:Screen%` above

We don't display these images today.
The menu option is `Edit->Insert Image` (applies to markdown cells).

This way images are stored in the notebook (self contained, just like output).

**Comment by DonJayamanne** [comment]
Upstream https://github.com/microsoft/vscode/issues/123021, https://github.com/microsoft/vscode/issues/119961

**Comment by amunger** [comment]
implemented in previous release https://github.com/microsoft/vscode/pull/155777
