### ISSUE TITLE
Independent font setting for notebook output

### ISSUE THREAD

**Issue by chungmoklee** [microsoft/vscode-jupyter#5784]
As far as know, there is no separate setting for notebook output font setting now. 
(Correct me if I am mistaken about this)
I often want to reduce the font size and line space in the notebook output so that condensed information can be displayed.

Thanks in advance!

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, I don't think we have plans on supporting this at our end.
With the new Native Notebooks VS Code owns the output and the font settings.
Transferring issue to VS Code.

**Comment by DonJayamanne** [comment]
Issue moved to [microsoft/vscode #123149](https://github.com/microsoft/vscode/issues/123149) via [**ZenHub**](https://www.zenhub.com/)
