### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by min0002** [microsoft/vscode-jupyter#5785]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.5.745244803`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
python extension is loading for ever...tried deleting VSC and also tried delete python and reinstall it

**Comment by DonJayamanne** [comment]
Thanks for filling this issue, unfortunately you have gained to paste the relevant information 
Please could you provide the missing information.
Closing for now, please feel free to reopen the issues with the missing information or feel free to create a new issue
