### ISSUE TITLE
Cannot execute Jupyter notebooks after VS-Code Insiders Update 

### ISSUE THREAD

**Issue by giuseppefilitto** [microsoft/vscode-jupyter#5788]
## Environment data

-   VS Code version: 1.57.0-insider    Commit: fe23c2041f848d6c2f6bd27875112a37bcc82f84
-   Jupyter Extension version: v2021.6.812916528
-   Python Extension version : v2021.4.765268190
-   OS (Windows | Mac | Linux distro) and version: MacOS 11.3 (Apple Silicon M1)
-   Python and/or Anaconda version: 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda (Miniforge3) 4.10.1
-   Jupyter server running: Local 

## Expected behaviour

Execution of a cell/notebook

## Actual behaviour

no execution 

## Steps to reproduce:

open a notebook
try to execute a cell

## Logs

Nothing happens in attempting to execute the cell

<img width="1139" alt="Schermata 2021-05-06 alle 11 19 43" src="https://user-images.githubusercontent.com/61703705/117274029-f7a5e200-ae5c-11eb-92e1-710b051a15bb.png">

**Comment by DonJayamanne** [comment]
I believe this has been resolved, please feel free to re-open or create a new issue if this issue persists.
