### ISSUE TITLE
Unable to open existing and new Jupyter Notebooks

### ISSUE THREAD

**Issue by mschiaff** [microsoft/vscode-jupyter#5794]
Issue Type: <b>Bug</b>

Since the last VSC update, every time I open an existing, or new, Jupyter Notebook, it's opened as plain text and not as a notebook. Hence, I can't execute any cell, because they don't even exist. It's just plain text. The only workaround I've found is to open the notebook from de "File" menu of VSC, but by doble-clicking the file it's not possible.

Here is an example of how it looks like:

![image](https://user-images.githubusercontent.com/26752943/117337191-1317e980-ae6b-11eb-902b-23af897714c2.png)

Extension version: 2021.6.811652604
VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1697)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.23GB (7.94GB free)|
|Process Argv|...--crash-reporter-id 8c952483-d3e9-4993-8564-614587d07ef1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30294353

```

</details>

**Comment by DonJayamanne** [comment]
@mschiaff Thanks for filing this issue and I'm sorry you're running into this.
Please could you provide the following information:
* Logs from the `Jupyter` output panel
* Check if there are any errors in the `Debug Console` log, opened using `Toggle Developer Tools`, possible the extension has failed to activate.

**Comment by greazer** [comment]
@mschiaff, in addition to providing the information that Don asked for above could you also check to see whether you have 
```json
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter-notebook",
            "filenamePattern": "*.ipynb"
        }
    ],
```
in your settings.json file (Preferences: Open Settings (JSON))? You should.

You should also NOT have anything that looks like:
```json
"files.associations": {
      "*.ipynb": <anything>
}
```
If either of the above statements is false, then this could explain the problem your seeing. How you got into this state is unknown, but given the significant changes we've been making to support VS Code's native notebook API, it's possible these settings could have gotten mis-set.

**Comment by XiaoTianJianJun** [comment]
I meet the same problem, hope it can be resolved soon. The current insiders version of vscode is no problem

**Comment by giuseppefilitto** [comment]
same problem here:

### Info

```
VS Code version: 1.57.0-insider
Commit: 6bee0f2f3fea9df1ad45344f09b2a139c93b384f
Date: 2021-05-07T08:14:45.808Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin arm64 20.4.0
Jupyter Extension version: v2021.6.812916528
Python Extension version : v2021.4.765268190
OS (Windows | Mac | Linux distro) and version: MacOS 11.3.1 (Apple Silicon M1)
Python and/or Anaconda version: 3.8.6
Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda (Miniforge3) 4.10.1
```
### Console log

```
electron/js2c/renderer_init.js:61 The vm module of Node.js is deprecated in the renderer process and will be removed.
t._load @ electron/js2c/renderer_init.js:61
console.ts:137 [Extension Host] (node:1755) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code - Insiders Helper (Renderer) --trace-deprecation ...` to show where the warning was created) (at writeOut (internal/process/warning.js:43:3))
S @ console.ts:137 
```
### Additional info

<img width="1163" alt="Schermata 2021-05-07 alle 14 38 12" src="https://user-images.githubusercontent.com/61703705/117450686-dbc83c00-af41-11eb-99e1-6f21eacf8a4a.png">
<img width="765" alt="Schermata 2021-05-07 alle 14 40 58" src="https://user-images.githubusercontent.com/61703705/117451018-3feb0000-af42-11eb-85f9-8fac7dd2c6ca.png">
<img width="1162" alt="Schermata 2021-05-07 alle 14 53 21" src="https://user-images.githubusercontent.com/61703705/117452371-fa2f3700-af43-11eb-8aab-98b9ed497980.png">

**Comment by DonJayamanne** [comment]
@mschiaff 
* Please confirm your version of VS Code & extension version where this is not working
Sorry to ask for this information again, it seems that it works in stable & not in insiders (at least for some).

**Comment by mschiaff** [comment]
@DonJayamanne I don't if I'm wrong, but I couldn't find any jupyter log because it doesen't even initiate. Regarding the debug console, here's what I found:

![image](https://user-images.githubusercontent.com/26752943/117485021-e1b82000-af35-11eb-86a8-38ff8dfb78d8.png)

@greazer I also checked the settings, and already have that config in the JSON file:

![image](https://user-images.githubusercontent.com/26752943/117485165-0d3b0a80-af36-11eb-9362-e24cc3ff90b9.png)

**Comment by mschiaff** [comment]
@greazer I'm sorry. The viewType was similar, but not exactly what you showed. I changed it, closed VSC and now it works. It also gave me the Welcome to a new experience and the notebook looks totally different. Thanks you all for the help!

![image](https://user-images.githubusercontent.com/26752943/117485820-dadddd00-af36-11eb-8aa0-b79ff8652d0d.png)

**Comment by DonJayamanne** [comment]
Closing this in favour of https://github.com/microsoft/vscode-jupyter/issues/5804
FYI - this is a bug in vscode https://github.com/microsoft/vscode/issues/123307
