### ISSUE TITLE
Do we need ability for users to join mailing list

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#58]
This is some new functionality added by Core team for Python extension.
Could be useful for us as well. Not sure.

**If not required,** 
* Then delete [src/client/application/misc/joinMailingListPrompt.ts](https://github.com/microsoft/vscode-jupyter/blob/d061ed898fba6dbd4b07e0612c131e8c12747db6/src/client/application/misc/joinMailingListPrompt.ts)

**If required**
* Use same mailing list of Python extension or different?

**Comment by claudiaregio** [comment]
I have found another solution for this, we can remove the mailing list for jupyter extension

**Comment by rchiodo** [comment]
Validated
