### ISSUE TITLE
Support both old and new `workbench.editorAssociations` setting formats

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5806]
Old layout will not get IntelliSense in settings.json anymore. It's now an object instead of an array. However we can't assume that we are loaded in a version of VS Code with the right setting format, so we should support both.

**Comment by kkukshtel** [comment]
Just peeking in here as a fellow extension author - what's the new workbench.editorAssociations format? My extension also broke on 1.56 and I can't find any documentation on why the following no longer works:

```
{
    "workbench.editorAssociations": [
    {
        "viewType": "depot.data",
        "filenamePattern": "*.cmod"
    }]
}
```

**Comment by joyceerhl** [comment]
@kkukshtel The new format is:

```
    "workbench.editorAssociations": {
        "*.cmod": "depot.data"
    }
```

i.e. the filenamePattern is the key and the viewType is the value.

That being said, the workbench.editorAssociations setting change should only be in VS Code 1.57.0-insider. VS Code stable should still be able to work with the old format. VS Code Insider is also supposed to be able to understand the old format and the new format--the settings.json IntelliSense will just flag the old setting as an error, but it's totally benign for now. I've also been told that tomorrow's VS Code Insider build will start automatically migrating users to the new format.

**Comment by kkukshtel** [comment]
Gotcha, thank you! And yeah I changed the setting in 1.56 and it seemed to break the editor association settings even more so tha change definitely didn't accidentally sneak into the release.

I'm trying to track down the causes of this https://github.com/microsoft/vscode/issues/123617 and thought it may have been related to what you posted here but seems like not.

**Comment by DavidKutu** [comment]
validated
