### ISSUE TITLE
No horizonal scrolling

### ISSUE THREAD

**Issue by randomQQQ** [microsoft/vscode-jupyter#5816]
## Environment data
Issue Type: <b>Bug</b>

No scrolling in pandas dataframe output

Extension version: 2021.6.819764235
VS Code version: Code - Insiders 1.57.0-insider (a19565da7dfc739fa26e36aae96113e19fe3806f, 2021-05-07T17:19:03.737Z)
OS version: Windows_NT x64 10.0.19042

## Actual behaviour
![image](https://user-images.githubusercontent.com/63656568/117564831-ab55de80-b0b6-11eb-9fab-9c7bdd414dc0.png)

## Expected behaviour
![image](https://user-images.githubusercontent.com/63656568/117564897-1dc6be80-b0b7-11eb-809c-8f650d3660fa.png)

**Comment by greazer** [comment]
Issue moved to [microsoft/vscode #123816](https://github.com/microsoft/vscode/issues/123816) via [**ZenHub**](https://www.zenhub.com/)
