### ISSUE TITLE
Check the stdout from nbconvert instead of its return value, sometimes it has an error, but the file was created

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#5818]
Currently, the editor and interactive window interface only support "export current python file and output as jupyter notebook". I need to reload it in a jupyter env to convert it to a pdf or html... which is a bit tedious. Please consider adding a feature so that users can directly export their outputs in a readable format like pdf if they need to share with others.

**Comment by rchiodo** [comment]
Maybe you missed it but this is supported:

![image](https://user-images.githubusercontent.com/19672699/117704751-0f90a500-b180-11eb-9232-b24feb539bac.png)

It looks kinda weird. 

Oh, it looks like the command palette isn't supporting it for some reason.

**Comment by StevenLi-DS** [comment]
@rchiodo I just tried and was able to export a PDF in jupyter lab but not via vscode. I do have a tex distribution MikTex installed.
[output.txt](https://github.com/microsoft/vscode-jupyter/files/6462100/output.txt)

**Comment by rchiodo** [comment]
Looks like it succeeds for us but nbconvert gives back an error message so we assume it failed. We might need to check the stdout from nbconvert instead of its return value.

**Comment by StevenLi-DS** [comment]
But I don't actually see any PDF saved on my disk.

**Comment by rchiodo** [comment]
It wrote it here:
```
C:\Users\liqia\AppData\Local\Temp\tmp-160241Cfgorf5DDED.pdf.pdf
```

But because of the failure, our cleanup of that temp folder deleted it.

**Comment by greazer** [comment]
@StevenLi-DS, if you're on Windows or Mac a workaround might be to export to HTML, then use your browser to save (or print) to PDF. Otherwise, we'll take a look.

**Comment by DavidKutu** [comment]
It does appear on the command palette now:
![image](https://user-images.githubusercontent.com/20347396/120867685-4a031d00-c547-11eb-85e7-42911f156df5.png)

What's left to do is what Rich mentions [here](https://github.com/microsoft/vscode-jupyter/issues/5818#issuecomment-839191535)

**Comment by DonJayamanne** [comment]
Thanks for this feature suggestion, however there haven't been any upvotes on this issue since it was created
Hence closing this issue for now
