### ISSUE TITLE
Timed out waiting to get a heartbeat from kernel process

### ISSUE THREAD

**Issue by Lukmon892** [microsoft/vscode-jupyter#582]
Hello All,

I am having issues with my jupyter notebook on my vscode. I am using python 3.8.3 on windows 10. Also, I installed Microsoft python extension on my vscode.

Kindly find the attached copy of the errors that I am getting on the vscode
![2020-09-26](https://user-images.githubusercontent.com/71932151/94342612-28c55680-ffe0-11ea-8fd8-974dc0b58506.png)
. And help me out with the necessary steps to take to resolve this issue. 

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by Nikhil1O1** [comment]
Timed out waiting to get a heartbeat from kernel process
I get the same error.
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.19.0-11-amd64```

**Comment by rchiodo** [comment]
@Nikhil1O1 unfortunately 'Timed out waiting to get a heartbeat from a kernel process' is just a generic error. It can happen for any number of reasons.

Can you set this value:
```json
"jupyter.logging.level": "debug"
```
Repro your problem, open the 'Jupyter' output tab, and then upload the contents of the output tab to a new issue? It's likely not related to this issue (as this was about spaces in the path which should have been fixed).

**Comment by darkl** [comment]
@rchiodo I am having the same problem with WSL2 and SageMath. I suspect it has to do with a space in my user directory.

> User belongs to experiment group 'NativeNotebookEditor'
> > /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> > /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> > /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> > /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> > /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> > /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> > /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> > /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> > /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> > /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> > /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> > /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> > /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> > /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> > /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> > /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> > /usr/bin/sage --python -m sage.repl.ipython_kernel -f /tmp/tmp-506nDwiRrRqUcl.json
> cwd: /mnt/c/Users/Elad Zelingher/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-0.51.3
> Error 2020-11-12 15:04:20: Disposing session as kernel process died ExitCode: 1, Reason: undefined
> Error 2020-11-12 15:04:20: Failed to connect raw kernel session: Error: Canceled
> Error 2020-11-12 15:04:20: failed to create INotebook in kernel [Error: Canceled
> 	at t.KernelShellFutureHandler.dispose (/home/elad/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:32:482004)
> 	at /home/elad/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:47:787217
> 	at Map.forEach (<anonymous>)
> 	at g._clearState (/home/elad/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:47:787160)
> 	at g.dispose (/home/elad/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:47:780908)
> 	at /home/elad/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:32:264323
> 	at Object.t.swallowExceptions (/home/elad/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:1:132214)
> 	at l.dispose (/home/elad/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:32:264285)
> 	at t.RawSession.dispose (/home/elad/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:49:187286)
> 	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
> Error 2020-11-12 15:04:20: DataScience Error [Error: Canceled
> 	at t.KernelShellFutureHandler.dispose (/home/elad/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:32:482004)
> 	at /home/elad/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:47:787217
> 	at Map.forEach (<anonymous>)
> 	at g._clearState (/home/elad/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:47:787160)
> 	at g.dispose (/home/elad/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:47:780908)
> 	at /home/elad/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:32:264323
> 	at Object.t.swallowExceptions (/home/elad/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:1:132214)
> 	at l.dispose (/home/elad/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:32:264285)
> 	at t.RawSession.dispose (/home/elad/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension.js:49:187286)
> 	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
> 

> Version: 1.52.0-insider (user setup)
> Commit: 050a123750e4ef4009930d0da1ff7a1a6441d4f3
> Date: 2020-11-12T05:43:04.852Z
> Electron: 9.3.3
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Windows_NT x64 10.0.19042

**Comment by rchiodo** [comment]
@darkl can you do the same thing I suggested for @Nikhil1O1? Turn on full logging and log a separate bug. THis looks like the problem, but we should have more output than that:

```
Error 2020-11-12 15:04:20: Disposing session as kernel process died ExitCode: 1, Reason: undefined
```

**Comment by darkl** [comment]
@rchiodo I did turn on `"jupyter.logging.level": "debug"`, I think:
![image](https://user-images.githubusercontent.com/1126390/98996898-a0543400-2501-11eb-85ed-1306725c338a.png)

**Comment by iyoushe1703** [comment]
> @rchiodo I did turn on `"jupyter.logging.level": "debug"`, I think:
> ![image](https://user-images.githubusercontent.com/1126390/98996898-a0543400-2501-11eb-85ed-1306725c338a.png)

Where can I find this file?

**Comment by Nikhil1O1** [comment]
> @rchiodo I did turn on `"jupyter.logging.level": "debug"`, I think:
> ![image](https://user-images.githubusercontent.com/1126390/98996898-a0543400-2501-11eb-85ed-1306725c338a.png)

How to turn this on??+
Shall I run this in a cell or terminal??

**Comment by darkl** [comment]
Use Ctrl+Shift+P and write `JSON` there. Choose Preferences: Open Settings (JSON).

Elad

**Comment by Nikhil1O1** [comment]
> Use Ctrl+Shift+P and write `JSON` there. Choose Preferences: Open Settings (JSON).
> 
> Elad

Okay, I added "jupyter.logging.level": "debug" in the json, but where will the output be returned?
I mean when I get the kernel heartbeat error, How can I access the log?

**Comment by darkl** [comment]
I think go to Output (CTRL+SHIFT+U) and then select Jupyter.
![image](https://user-images.githubusercontent.com/1126390/99682173-f585cd80-2a4c-11eb-944a-4ffec6273d8e.png)

@rchiodo can you confirm I understood your instructions correctly?
Elad

**Comment by Nikhil1O1** [comment]
> @Nikhil1O1 unfortunately 'Timed out waiting to get a heartbeat from a kernel process' is just a generic error. It can happen for any number of reasons.
> 
> Can you set this value:
> 
> ```json
> "jupyter.logging.level": "debug"
> ```
> 
> Repro your problem, open the 'Jupyter' output tab, and then upload the contents of the output tab to a new issue? It's likely not related to this issue (as this was about spaces in the path which should have been fixed).

#3973

I tried to explain my issue in the given link

**Comment by bubaleh1337** [comment]
I'd just updated my vs code and it helped me.

**Comment by amFarrouk** [comment]
same issue in linux (kali linux 2021) (i guess it's conflict in which kernel to use python2 or python3
