### ISSUE TITLE
"Run All Cells Above" icon gone and shortcut not working

### ISSUE THREAD

**Issue by MattWolf74** [microsoft/vscode-jupyter#5823]
-   VS Code version: 1.56.0
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.811652604
-   Python Extension version (available under the Extensions sidebar): 2021.5.829140558
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Pro 10.0.19042 Build 19042
-   Python and/or Anaconda version: 3.8.7 64 bit
-   Type of virtual environment used : N/A
-   Jupyter server running:  Local

Issue: 
The "Run All Above Cells" Icon is gone and the shortcut NOT working anymore. It was there along with the other Jupyter icons on the top right in VS Code. Neither does the shortcut work. What is going on? Have the shortcuts changed and why is there no mention in the change-logs of a change to this important feature? 

Can someone please help to make running all the above cells work again? It's hugely important for my  code writing as its very cumbersome to have to manually execute every cell above a location

**Comment by MattWolf74** [comment]
Thanks, will work with the insider in the meantime. Any idea when the next stable release can be expected? Thanks

> Sorry for the inconvenience @MattWolf74. We had to remove them because they had an issue.
> 
> They are back now on the cell toolbar in insiders, please use that in the mean time. They will be back on stable on our next release.

**Comment by DavidKutu** [comment]
My apologies, we should've put it on the change log.

Our next release should be on the first week of June. But I'll see if I can push this to a point release sooner.

**Comment by DavidKutu** [comment]
I checked, and unfortunately, the buttons are not in stable because of an issue with VS Code (the fix is live on Insiders).
We'll have the buttons back on the cell toolbar on the next release of VS Code and the extension.
Please use insiders in the mean time.

Sorry for the trouble.

**Comment by joyceerhl** [comment]
In the latest Jupyter extension Insiders build the run all cells above/below buttons are available in the cell toolbar and the command palette command has been reinstated:

![image](https://user-images.githubusercontent.com/30305945/118433100-18f1a400-b68f-11eb-9057-2f3d45cd0916.png)

As David mentioned, we will ship this fix when VS Code 1.57 stable releases, which should be at the start of June. Apologies again for the inconvenience.

**Comment by MattWolf74** [comment]
That is great, thanks for the update.
