### ISSUE TITLE
Unable to save SVG in Jupyter Cells Output 

### ISSUE THREAD

**Issue by shriaviator** [microsoft/vscode-jupyter#5827]
## Environment data

-   VS Code version: 1.56.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.811652604
-   Python Extension version (available under the Extensions sidebar): v2021.5.829140558
-   OS (Windows | Mac | Linux distro) and version: Pop_Os 20.04 LTS
-   Python and/or Anaconda version: 3.8.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | local

## Expected behaviour

- Click save to SVG : File saves to svg

## Actual behaviour

Nothing Happens 

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

```
import altair as alt
import pandas as pd

source = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]
})

alt.Chart(source).mark_bar().encode(
    x='a',
    y='b'
)
```
- Vscode / jupyter : Save as PNG works as expected and saves output 
- Jupyter-Lab : save as svg works as expected 

![jupyter](https://user-images.githubusercontent.com/32628818/117761648-5b595200-b245-11eb-8910-7e4d25320d75.png)
## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Nil Logs 
```

</p>
</details>

**Comment by IanMatthewHuff** [comment]
@shriaviator Thanks for the report here, I tested it out, and I see the same issue as you do. 

Just to note here. In vscode-insiders we are rolling out a new UI based on VS Code's new Native Notebook support. I just went and checked in it and this scenario does work there and I can save a SVG. 

![image](https://user-images.githubusercontent.com/812783/117897762-51047b80-b278-11eb-9335-59949997c43d.png)

We may be unlikely to fix this in the old UI as this new UI will be replacing it in upcoming releases.

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
