### ISSUE TITLE
Extension doesnt create cells when a new notebook is created

### ISSUE THREAD

**Issue by Sriram1023** [microsoft/vscode-jupyter#5832]
Steps to reproduce:
Method 1: 
1. Open VSCode
2. Create a new file in the current directory
3. Save the file as <some_name>.ipynb
Expected result: VSCode should recogonize the extension and open a jupyter notebook style editor
Actual result: It opens a plain text editor

Method 2:
1. In Any folder Right Click -> New -> text document
2. Edit the name of the text doc and also the extension to .ipynb
3 Open the File in VSCode
Expected result: VSCode should recogonize the extension and open jupyter style editor
Actual Result: It opens a plain text editor

**Comment by DonJayamanne** [comment]
I'm sorry you ran into this issue. There is a bug in VS Code Insiders, and we have craeted a new release that gets around this issue.
