### ISSUE TITLE
Native Notebooks - Selecting base env from kernel picker does not activate

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5833]
## Environment data

-   VS Code version: 1.56.0 (but opted into native notebook)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.811652604
-   Python Extension version (available under the Extensions sidebar): v2021.5.829140558
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open VS Code + notebook
2. Select anaconda base env from kernel picker 
3. Does not activate - keep getting error that package is not found although it shows up in the base env package list

Issue is solved by opening an anaconda prompt in the base environment and starting up vs code from there (code . )

**Comment by DonJayamanne** [comment]
Based on the feedback from @claudiaregio this is blocked on VS Code https://github.com/microsoft/vscode-jupyter/issues/5872

**Comment by DonJayamanne** [comment]
@claudiaregio does this now work for you?

**Comment by claudiaregio** [comment]
This is working for me in insiders now!!!

**Comment by claudiaregio** [comment]
Reopening as this is not working in stable post new release (1.57.0)

**Comment by rchiodo** [comment]
This should be fixed I believe.
