### ISSUE TITLE
Native Notebooks - Variable Explorer not generating any variables

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5836]
## Environment data

-   VS Code version: 1.57.0 - insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.832239655
-   Python Extension version (available under the Extensions sidebar): v2021.5.829140558
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local 

## Expected behaviour

Variable Explorer to generate values

## Actual behaviour

No Variables 

![image](https://user-images.githubusercontent.com/19276747/117869295-7a5ce180-b24f-11eb-811e-cbf522ea8e5c.png)

## Steps to reproduce:

1. Open nb in insiders 
2. Run all cells
3. Open Variable Explorer

**Comment by joyceerhl** [comment]
This is possibly a focus tracking issue or a variable fetch speed issue (Claudia has lots of variables in her active kernel and that causes the Loading... message for every variable after the first 5).

**Comment by 1vecera** [comment]
I have fairly simple code with a few small Dataframes and have the same issue.

**Comment by claudiaregio** [comment]
@1vecera Have you updated to the latest version of VS Code and the jupyter extension? I am now only seeing this when running all cells for the first time

**Comment by IanMatthewHuff** [comment]
@claudiaregio Are you still seeing this? Didn't believe this was an issue still. I'm closing, but just reopen if you still see it.
