### ISSUE TITLE
Native Notebooks - Run all not working

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5838]
## Environment data

-   VS Code version: 1.57.0 -insiders
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.832593372
-   Python Extension version (available under the Extensions sidebar): v2021.5.829140558

## Expected behaviour

Run all to work

## Actual behaviour

Run all does not work

**Comment by joyceerhl** [comment]
This is because the point fix is now the latest insiders build. We're going to publish another insiders build off the main branch, which should fix this.
