### ISSUE TITLE
Jupyter extension should wait until a document is opened to fetch kernels in remote scenarios

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5846]
* Fetching kernels is slow
* Kernels are required for Interactive & Notebooks

Hence makes sense to fetch kernels as soon as extension activates
This way kernels are available (already being fetched) as soon as a notebook is opened

Things to consider:
* Local vs remote
* Delays displaying kernels (hence run button) when opening a notebook
	* The longer it takes to fetch these, the longer the `Run` button is hidden
* If usinvg remote connection 
	* 	& user opens a Python file, what will happen? will user get error about kernels?

**Comment by DonJayamanne** [comment]
@IanMatthewHuff /cc

I think what we do today is good (correct thing), but lets see if there are any drawbacks (or things that need to be fine tuned or other)

**Comment by IanMatthewHuff** [comment]
Yeah, it would be good to talk over. Having been working on fixing up tests the main cause of test breakage was the change from loading kernels at document open time to activation time. Feels right at activation time to me, but I do feel some oddness, especially for stuff like remote scenarios.

**Comment by rchiodo** [comment]
Validated
