### ISSUE TITLE
Unable to run cells when opening existing notebooks (even after running it before a reload)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5858]
1. Install Jupyter extension
2. Open a notebook, select Kernel A
3. Run a cell & confirm execution order changes to 1
4. Next Select kernel B
3. Run a cell & confirm execution order changes to 1
6. Close this notebook
6. Reload VS Code.
7. Open the same notebook.
8. Confirm Kernel B is selected on the bottom
9. Run a cell, it looks like (progress UI displayed) the cell ran.
10. But there are errors in the error log indicating that it could not.

Upstream https://github.com/microsoft/vscode/issues/123700

Users running into this https://github.com/microsoft/vscode-jupyter/issues/4941#issuecomment-839948482
@joyceerhl /cc

**Comment by joyceerhl** [comment]
Isn't this the same as https://github.com/microsoft/vscode-jupyter/issues/5848?

**Comment by DonJayamanne** [comment]
Duplicate of #5848,
