### ISSUE TITLE
I can create a new jupyter notebook just fine, but opening existing one results in "Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed or enabled."

### ISSUE THREAD

**Issue by Santosh-Gupta** [microsoft/vscode-jupyter#586]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Connect to a remote server. 
2. Create a jupyter notebook. Write some cells. Save. Log out of remote server. 
3. Reconnect to remote server, right click on jupyter notebook file -> open with -> Jupyter Notebook. 

## Actual behavior

Result _**usually**_ is

>Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed or enabled.

Occasionally it opens correctly, but most of the time, it does not. 

However, if I create new .ipynb file, Jupyter starts up correctly. If I then try to open the file with Jupyter, I still get the same error. 

This error does not seem to be reproduced with I am working locally; usually on a remote server. I am using the remote-ssh extension to log into the remote server. 

## Expected behavior

saved Jupyter notebook files should be able to open correctly, since new notebooks work correctly. 

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

Python 3.6.9 64-bit. 

up-to-date Jupyter, installed today.

-   **Jupyter server running:** Local | Remote |  Remote
-   **Extension version:** 20YY.MM.#####-xxx | 
-   **VS Code version:** #.## | July 2020 (version 1.48)
-   **Setting python.jediEnabled:** true | false
-   **Setting python.languageServer:** Jedi | Microsoft | None
-   **Python and/or Anaconda version:** #.#.# | Python 3.6.9 64-bit.
-   **OS:** Windows | Mac | Linux (distro): Locally, Mac, Server uses Ubuntu Linux
-   **Virtual environment:** conda | venv | virtualenv | N/A | ... N/A

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by SantoshGuptaML** [comment]
I recently started getting this error again

> Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed or enabled.

Version: 1.55.0-insider

**Comment by SantoshGuptaML** [comment]
It is fixed, though I am not sure what was the cause of the fix. I upgraded jupyterlab, and also reopened the notebook. I didn't see this comment so I didn't think of isolating that method.
