### ISSUE TITLE
shift+enter should bypass markdown cell in Native Notebook

### ISSUE THREAD

**Issue by grapland0** [microsoft/vscode-jupyter#5866]
When press shift+enter on markdown cell, it should do no-op and skip to the next cell. 

In this way, user can press shift+enter multiple times to execute a series of continuous cells in notebook without manually skip the markdown cells in between with other shortcut keys or mouse.

The current webview vscode jupyter notebook supports this, but the native notebook does not.

**Comment by hanmala123** [comment]
+1

**Comment by joyceerhl** [comment]
This has been fixed in VS Code Insiders' repository and should become available early next week in the daily updates: https://github.com/microsoft/vscode/issues/123819

**Comment by grapland0** [comment]
Confirmed. Thank you!
