### ISSUE TITLE
VS-Code Insiders - Not opening jupyter notebook in Ubuntu 20.04 after latest update of Insider version

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/vscode-jupyter#5867]
After double-clicking on an .ipynb file its opening in a text format.

My VS-Code version details

```
Version: 1.57.0-insider
Commit: 659175fa39b994fc39381b0af2874c85efeb2a01
Date: 2021-05-13T05:12:59.200Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.8.0-53-generic
```

Have tried uninstalling-and-reinstalling Python and vscode-jupyter extensions, didn't help.

After enabling Developer-Tool getting these details when double-clicking on an .ipynb file.

```
ERR command 'npm.packageManager' not found: Error: command 'npm.packageManager' not found
    at u._tryExecuteCommand (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1752:3364)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1752:3245
```

**Comment by jcunwin** [comment]
I had a similar problem when upgrading the VSCode version.
Disabling the Pylance extension seems to have fixed the problem. I can now display and run my Julia language Jupyter notebook.

Version: 1.57.0-insider
Commit: 659175fa39b994fc39381b0af2874c85efeb2a01
Date: 2021-05-13T05:12:59.200Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.4.0-73-generic

**Comment by hanmala123** [comment]
I have this problem too after update vscode.
Even if right click tab and reopen editor with jupyter notebook, the editor can't be loaded.

**Comment by zx1621** [comment]
I have this problem too after update vscode.
So I reinstall python and jupyter extension and relaunch vscode, and it works.
You can try it in this way.

**Comment by IanMatthewHuff** [comment]
For the folks in this thread, could you please check to see if there is an updated version of the Jupyter extension installed? There was a change from vscode last night as to how we register as a notebook provider. If you don't have the most recent version of the Jupyter extension the symptom would be seeing .ipynb files opening as raw JSON and not as the notebook editor.

**Comment by DonJayamanne** [comment]
Closing this issue, under the assumption that its resolved.
If this issue still exists, please do get back to us or please feel free to file a new issue
