### ISSUE TITLE
Losslessly Compress Images for Smaller Extension Size

### ISSUE THREAD

**Issue by chrisyeh96** [microsoft/vscode-jupyter#5868]
This extension includes several image files which are included in the final distribution to end-users:

icon.png
resources/InstallJupyter.png
resources/PythonSelector.png

All of these images can be losslessly compressed by a significant amount, saving nearly 20KB in space. I have a forthcoming pull request which will do exactly that.

Would it be possible to use an automatic bot such as [ImgBot](https://github.com/marketplace/imgbot) to automatically losslessly compress future image assets for this repo?

**Comment by DonJayamanne** [comment]
Thanks for the PR , does the saving of 20kb make much of a dent. In another issue you mentioned that the  extension use 70mb once extracted. 

hence saving 20kb would have reduced the overall disc space space by just 0.027%, did this make any  improvident for your disc space in terms of perf or the like? Not sure how that makes any improvement.

**Comment by IanMatthewHuff** [comment]
Validated.
