### ISSUE TITLE
No variables in explorer for interactive window

### ISSUE THREAD

**Issue by shih-chi-47** [microsoft/vscode-jupyter#587]
# Steps to cause the bug to occur

1. Running a python script in an interactive window.
```
import numpy as np
import scipy.io as sio
import matplotlib.pyplot as plt

# %%
a = np.array(range(10))
```

2. Press "show variables active in jupyter kernel"

## Actual behavior
Nothing shows up in variables column. Consel in the developer tool shows things include
> Failure during variable extraction:
> NameError: name '_VSCODE_VariableImport' is not defined

## Expected behavior
Variable `a` shows in the variables column with value.

![variable_explorer](https://user-images.githubusercontent.com/31977167/93907493-63bb4780-fccb-11ea-8eda-b93c4309c4ad.gif)

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local 
-   **Extension version:** 20YY.8.109390
-   **VS Code version:** 1.49.0
-   **Setting python.languageServer:** Jedi
-   **Python and/or Anaconda version:** 3.8.5 Anaconda
-   **OS:** Windows 10
-   **Virtual environment:** conda

**Comment by IFFranciscoME** [comment]
Is there progress on this ?. I'm experiencing similar behavior. I'm using a virtual environment created with virtualenv and the code runs correctly, and if I type the variable name in the "Type code here and press shift-enter to run" it does run, but do not shows any of the variables using the option "Show variables active in jupyter kernel"
