### ISSUE TITLE
Reduce Extension Size / Minify?

### ISSUE THREAD

**Issue by chrisyeh96** [microsoft/vscode-jupyter#5870]
## Environment data

-   VS Code version: 1.56.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.832593372
-   Python Extension version (available under the Extensions sidebar): v2021.5.829140558
-   OS (Windows | Mac | Linux distro) and version: Windows 10 20H2
-   Python and/or Anaconda version: 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: N/A

## Description

Currently this extension takes up ~70 MB of hard disk space when installed, which is a lot of space. Is there any way to reduce the size of this extension? Some ideas include:

1. **"Minify" JSON/JS/Python files for releases.** A spot check of JSON files included in the released versions of this extension shows that the majority still maintain 4 spaces of indentation. Reducing this to 1 space (or even better, completely removing spaces/newlines) could save a significant amount of space.
2. **Losslessly compress image assets.** Several image assets currently are not losslessly compressed. See #5868 for example. Adding a bot that automatically losslessly compresses image assets could easily fix this issue.
3. **Avoid including unnecessary files in packaged extension.** I'm no expert in how these extensions are actually packaged, but it seems like there are some files that don't need to be included in the final distribution, for example, the `pythonFiles/.vscode` folder.

**Comment by DonJayamanne** [comment]
Thanks for filling this issue. We'll look into this.

**Comment by chrisyeh96** [comment]
> When we eventually switch over to Native Notebooks (https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/) we'll be able to delete a lot of the webview related dependencies,hence reduce file size.

Neat.

Also, I just did some basic grepping - it seems like just removing unnecessary spaces from the various .json, .js, .ts, and .py files can save ~2.5MB in the final distribution. Actually "minifying" all of the JS files (there are currently 55MB of .js files) would save much more.

**Comment by DonJayamanne** [comment]
Thanks for the suggestions,
Just out of curiosity, does this saving in disck space make much of a difference?
E.g. when installing Python packages (they can use upto 100s MB or even more, specially with conda packages), hence anyone working on Jupyter already ends up installing large pacakges today. 
In my experience, these are optimized for distribution.

Once again, thanks for the suggestions & investigation. But curious if you are running into any disck space issues or perf issues due to the size of this extesnion

**Comment by chrisyeh96** [comment]
I'm mostly just surprised that the extension itself takes ~70MB, when VS Code itself is ~250MB. On my laptop with only ~100GB of usable SSD space, these are non-trivial sizes.

**Comment by greazer** [comment]
Also see #4551

**Comment by DonJayamanne** [comment]
Closing this issue as we have removed a lot of the dependencies (file size should be much smaller in th next version), and once we ship the renderer extension as a seprate extension that would remove more items from the extesnion.
