### ISSUE TITLE
Plotly doesn't work with ipywidgets's Output

### ISSUE THREAD

**Issue by fekad** [microsoft/vscode-jupyter#5871]
The `plotly` figures don't show when I try to use the `widgets.Output` context in jupyter notebook

## Environment data

-   VS Code version: 1.57.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.838387092
-   Python Extension version (available under the Extensions sidebar): XXXv2021.6.834355108-dev
-   OS (Windows | Mac | Linux distro) and version: Darwin x64 19.6.0
-   Python and/or Anaconda version: Pyhton 3.8.5
-   Type of virtual environment used: conda
-   Jupyter server running: Local 

## Expected behaviour

The `ipywidgets.Output` should behave a placeholder so the same figure should show up.

```python
import plotly.express as px

print("Hello world!")
fig = px.scatter(x=[0,1,2,3,4],y=[2,4,7,2,7])
fig.show()
```

![Screenshot 2021-05-13 at 17 10 04](https://user-images.githubusercontent.com/6748541/118145606-103e6b00-b40e-11eb-8887-ff2ef2864d7a.png)

## Actual behaviour

```python 
import ipywidgets as widgets
import plotly.express as px

out = widgets.Output()
display(out)
with out:
    print("Hello world!")
    fig = px.scatter(x=[0,1,2,3,4],y=[2,4,7,2,7])
    fig.show()
```
![Screenshot 2021-05-13 at 17 08 50](https://user-images.githubusercontent.com/6748541/118145432-e4bb8080-b40d-11eb-8129-ac4f7e543537.png)

The figure is missing. First I just thought the size of the output field is small it was not the case:
```python
out = widgets.Output(layout=widgets.Layout(width='600px', height='200px'))
```
The same code works perfectly with `jupyter notebook`.

## Steps to reproduce:

Related/similar issues:
- https://github.com/colabtools/issues/1458

**Comment by DonJayamanne** [comment]
Can repro, we need to fix the bug at our end.

**Comment by DonJayamanne** [comment]
this should be fixed, fixed as part of  https://github.com/microsoft/vscode-jupyter/pull/10327
