### ISSUE TITLE
Blank notebooks not using active interpreter

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5874]

**Comment by DavidKutu** [comment]
Blank notebooks don't use the active interpreter, rather they ask me to select a kernel. 
I think that behavior is ok, but I'm putting this back just to be sure.

**Comment by DonJayamanne** [comment]
> I'm putting this back just to be sure.

The first kernel in the list should be the active interpret

**Comment by DavidKutu** [comment]
validated
