### ISSUE TITLE
Execution stopped if package file is modified.

### ISSUE THREAD

**Issue by grudloff** [microsoft/vscode-jupyter#5877]
While a notebook is being run, if a file is opened from the same directory or the tab is switched to an already open tab of a file in the same directory the execution appears to be halted. In reality, the last run cell is still running as normal and if it is run again, it will be run again and with extra outputs accordingly. The same behavior appears when switching tabs on the terminal panel. 
If a cell is run and this happens, and before it finishes, another cell is run, the output will be displayed in that cell when the previous one finishes.

## Environment data

-   VS Code version: 1.57.0-insider (user setup)
-   Jupyter Extension version: v2021.6.838387092
-   Python Extension version: v2021.6.829598502-dev
-   OS: Windows_NT x64 10.0.19041
-   Python version: python 3.8.8
-   Type of virtual environment used : conda 4.10.1
-   Jupyter server running: Local

**Comment by grudloff** [comment]
It may be related to #5641 as the behavior is very similar, in that it is a display issue of the cells being run and the output placement.

**Comment by DonJayamanne** [comment]
Hmm, I'm unable to repro this at my end.
Though I can see that the interrupt button  is missing.
![running](https://user-images.githubusercontent.com/1948812/118199067-1e3cbd80-b407-11eb-855b-25f55222dd68.gif)

**Comment by DonJayamanne** [comment]
I'm assuming the issues are related, lets leave this open, & I'll file an issue upstream against VS Code.

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode/issues/123830

**Comment by grudloff** [comment]
> Hmm, I'm unable to repro this at my end.
> Though I can see that the interrupt button is missing.
> ![running](https://user-images.githubusercontent.com/1948812/118199067-1e3cbd80-b407-11eb-855b-25f55222dd68.gif)

I am experiencing almost the same issue. If you take a closer look the execution time is missing as well as the top sliding blue bar. Though in my case I also have the rotating arrows missing.

> I'm assuming the issues are related, lets leave this open, & I'll file an issue upstream against VS Code.
> 
> @grudloff I'm sorry about this issue, it seems to be an upstream (VS Code) bug.

No problem. Thanks a lot for the help!
