### ISSUE TITLE
Update CTI test plan concerning info about Jupyter server URI being missing in interactive window.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#5888]
## Environment data
![image](https://user-images.githubusercontent.com/59192491/118249728-45af8b00-b4d8-11eb-8d13-ba9acf268f88.png)

## Steps to reproduce:
1. Make sure Anaconda installed in local
2. Open the file src/test/datascience/manualTestFiles/manualTestFile.py in VSCode
3. At the top of the file it will list the things that you need installed in your Python environment
4. On the first cell click Run Below
5. Interactive Window should open, show connection information, and execute cells
6. Observer the interactive window

## Expected behaviour
The first thing in the window should have a line like this: Jupyter Server URI: http://localhost:[port number]/?token=[token value]

## Actual behaviour
The info about Jupyter server URI is missing.
![image](https://user-images.githubusercontent.com/59192491/118250484-1fd6b600-b4d9-11eb-9453-ea05e6e05f90.png)

**Comment by rchiodo** [comment]
This is by design. We probably need to update the test plan

**Comment by rchiodo** [comment]
Updated test plan here:
https://github.com/microsoft/vscode-jupyter/commit/f65676d52174a0e679c4b681338570bb5e036eb3

URI is no longer displayed.
