### ISSUE TITLE
Saving invalid kernelspec

### ISSUE THREAD

**Issue by nathancarter** [microsoft/vscode-jupyter#5889]
I'm simply re-raising issue #2423.  I do not know why it was closed, nor why the conversation there was locked; no solution to the problem is given in that issue.

This is relevant for me because I'm using VSCode to edit Jupyter notebooks, then using [Jupyter Book](https://jupyterbook.org/intro.html) to compile those notebooks into a book.  Since that uses `nbconvert`, the same problem arises.

But much more generally, the problem is rather serious, in that VSCode is setting kernelspecs that it seems only VSCode will ever be able to understand.  It's taking Jupyter notebooks that are usable by a huge variety of tools and secretly converting them to only being usable within VSCode (!?).  If it needs to set the kernelspec to a secret giant hash that works only within VSCode, fine, go ahead and do that in memory, but why save that data to the filesystem?  Obviously VSCode can recreate such hashes any time it opens the file, so it doesn't have any actual need to change the kernelspec on disk, and doing so only destroys compatibility with every other notebook-related tool.

My current workflow is literally opening the `.ipynb` files in vim and manually fixing the metadata after I save it with VSCode, or alternatively opening up my SCM app and reverting those few lines manually after every save (!).

**Comment by DonJayamanne** [comment]
@nathancarter Sorry about this issue and thanks for filing it again and bringing it to our attention.
I believe we resolved this recently.
Please could you install VS Code insiders (we have an insider build of the extension that gets pushed daily for those using VS Code Insiders).

Please let us know if its resolved in the current version.

**Comment by DonJayamanne** [comment]
This was fixed here https://github.com/microsoft/vscode-jupyter/pull/5732
& I believe we have an existing issue here https://github.com/microsoft/vscode-jupyter/issues/5612
Once you've replied back, i'll close this in favor of the existing (open issue) #5612.

Once again, sorry for closing the other issue and we would like to address this, and its being tracked in #5612

**Comment by nathancarter** [comment]
Ah, I see, I'm not on insiders at the moment.  I can wait for it to propagate into the main build.  Thank you for the very fast reply!

**Comment by nathancarter** [comment]
And yes--I agree that your comments on #5612 are just what I was hoping for. :)

**Comment by DonJayamanne** [comment]
Thanks for the confirmation, closing in favor of #5612
