### ISSUE TITLE
Improve UX for getting started

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode-jupyter#5891]
In a recent UX study looking at the native notebook experience in Insiders with data scientists who were not familiar with VS Code, many participants struggled to get started.

Three out of seven participants started by creating a new file. This didn't provide them with an easy path to learning that they needed to install the Jupyter extension.

After installing the Jupyter extension, some participants looked for a New Notebook command in the main menu or in the Explorer viewlet. Nobody searched the command palette. Nobody read the extension details page.

Other participants tried to open an existing notebook. They were prompted to install the Jupyter extension but that was not sufficient to get everything working since they did not have Python installed.

Then once they tried to select a virtual environment that they had setup, they were prompted to install ipykernel. But they did not notice the prompt.

Overall there were many more steps required, most of which were hard to discover.

It would be worth exploring how we can remove all these points of friction. It would be worth storyboarding this experience, capturing the friction points and then thinking about possible improvements to the overall flow.

**Comment by claudiaregio** [comment]
Thanks for the summary @stevencl, already working on this one.

**Comment by claudiaregio** [comment]
Related Issues: 
https://github.com/microsoft/vscode-jupyter/issues/5798
https://github.com/microsoft/vscode-jupyter/issues/5897
