### ISSUE TITLE
Set language for all code cells in a notebook

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode-jupyter#5893]
In a recent UX study, participants (data scientists with little familiarity with VS Code) sometimes ended up with a notebook where the code cells were set to plaintext. Once they realised that they could click on the language label in the bottom right of the cell and saw the language quick pick selector, they wanted to be able to set the language for all code cells in the notebook, not just the one they clicked on.

**Comment by claudiaregio** [comment]
@stevencl If a user switches to language A, all cells added after that should be set to language A. Is that not what was happening to users? If so sounds like a bug

**Comment by rchiodo** [comment]
Could we add a command to change the language of all cells?

**Comment by stevencl** [comment]
Sorry for the delay in replying @claudiaregio. What was happening was that the user saw multiple cells were marked as plaintext. They clicked on the indicator on the cell, saw the quick pick with the list of languages, chose Python, and saw that cell was now changed from plaintext to Python. But the remaining cells were still marked as plaintext. They wanted an easy way to turn all the plaintext cells into Python cells. Having such a command as @rchiodo suggests would be good. I guess the question then is how best to expose that command? For example, clicking on the language label on a cell could show two context menu commands - "Change language for this cell", "Change language for all plaintext cells in this notebook". Clicking on each would show the language list in quick pick. 

Another alternative would be that the quick pick that shows the list of languages has a drop down/checkbox at the top "Change language for all [current language] cells". I don't know if this is possible?

Another option would be to expose the command in the command palette but I don't think anybody would find that in their first 30 minutes of using notebooks in VS Code.

**Comment by DonJayamanne** [comment]
I don't think this will be necessary anymore.
Users shouldn't end up in a situation where the language is set to plain text, also changing the kernel will update the cell language of all cells.

Eg if you had some other kernel selected and cell languages were  c# or plain text, changing to kernel to putting will update all cells to python.

**Comment by IanMatthewHuff** [comment]
Validated. I've not seen the plaintext issue. Also took a C# language cells + C# kernel and moved it to a python kernel. All cells were converted to python.
