### ISSUE TITLE
Prompt to change the language from plaintext when user executes plaintext code cell

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode-jupyter#5894]
In a recent UX study, participants (data scientists with little familiarity with VS Code) sometimes ended up with code cells that were set to plaintext. They did not notice the language indicator on the cell and repeatedly tried to write python code in the cell, then try to execute the code.

Would it be possible to detect that the user is repeatedly trying to execute a cell that is set to plaintext and then prompt the user to choose a language? This was a frustrating experience for participants who had never used notebooks in VS Code before.

**Comment by DonJayamanne** [comment]
@claudiaregio sound familiar. I'll try to find the issue where we discuss this exact same issue.

@stevencl would you be able to share the recording via Teams.
We'd like to understand what the user did.
Are they using Native NOtebooks or the webview based notebooks?
Did they pick a kernel, is one auto selected?

**Comment by DonJayamanne** [comment]
I think one problem we had here is:
* Should the user pick a kernel first
* Or select the langauge first?
* Or would they start writing code first in a few cells & then try to run...

Other scenarios include:
* Opening an existting notebook (& language is set to Python)
* THey then change the langauge in the cells to `R` or other 
* Then they start running a cell, now get errors
Problem, they didn't change the kernel.


In Jupyter, users first need to select a kernel when opening a notebook.

@claudiaregio I'm begining to think that user having to select a Kernel when running a cell would be a good thing, at that point they'd know that they want to use `R` kernel isntead of an autoselected `Pytohn (or other)` kernel.

**Comment by claudiaregio** [comment]
@DonJayamanne This was similar to what we saw with an old bug - if you had a markdown cell and pressed +code you would end up with a plain text cell. Yes, I agree the user should be picking a kernel first, we originally wanted to go this route but the amount of time it took to return the list of kernels was a bit long from the customer perspective. Do we believe there is anyway for us to speed up finding the kernels to surface? 

@stevencl Can you please provide access to the entire recordings with the Jupyter team? I believe users were ending up with a plain text cell as a bug and we should also be fixing the bug.

**Comment by DonJayamanne** [comment]
I think we can do something here, agreed need to see the videos.

**Comment by claudiaregio** [comment]
@DonJayamanne Why was kernel issue label added to this one?

**Comment by IanMatthewHuff** [comment]
Validated. I believe this was solved by the code that switches cell languages based on the kernel selected.
