### ISSUE TITLE
Cancel previous kernel connection when switching to another kernel

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#5896]
## Environment data

-   VS Code version: 1.57 Insiders
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.841665333
-   Python Extension version (available under the Extensions sidebar): N/A
-   OS (Windows | Mac | Linux distro) and version: macOS Big Sur
-   Python and/or Anaconda version: N/A
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

* Make sure you don't have Python installed
* Select a kernel which requires Python ext
* Run cells
* A notification asks me to install Python, cancel this notification
* Switch to another kernel
* Cell exection should be canceled now

## Actual behaviour

* Cell execution is in pending state
* Notification of connecting to previous kernel is not dismissed (I can't abort it from the notification either)
<img width="469" alt="image" src="https://user-images.githubusercontent.com/876920/118301248-b6828300-b497-11eb-9e6b-8bf5d5eccd77.png">

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by greazer** [comment]
Interesting, but not necessary to fix for June.

**Comment by DonJayamanne** [comment]
I'd move this out of July milestone as well, i think we have bigger bugs to fix.
Its more of a code health item.
