### ISSUE TITLE
Impossible to run any notebook without Python extension when RAW isn't supported

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5897]
* Disable Python extension
* Reload VS Code
* Run python notebook (with zmq disabled)
* Run a cell
* I get an error message, I click no & nothing happens .
* Wait 2 minutes, nothing happens
* Enable Python extnsion, that's all I do
* Things start to work now

Looks like code was blocked until python extension was enabled.

I think we should turn this into a modal dialog.
**Users cannot run Jupyter without Python extension**

**Comment by rchiodo** [comment]
Similar to the nbconvert problem.

**Comment by DonJayamanne** [comment]
This should be fxed
