### ISSUE TITLE
Native Notebook: running notebook blocks variable list refresh

### ISSUE THREAD

**Issue by grapland0** [microsoft/vscode-jupyter#5902]
When switch focus from one idle notebook to a running notebook, the variable viewer doesn't refresh to list the variables from that running notebook.

```
Name: Jupyter
Id: ms-toolsai.jupyter
Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.
Version: 2021.6.841665333
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
```
```
Version: 1.57.0-insider (user setup)
Commit: 40d5e6796fbc32d67dd0009e5b0027003803fd7e
Date: 2021-05-14T20:13:58.234Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by joyceerhl** [comment]
Hi @grapland0, do you mean the variable explorer never ever updates to show the variables from the running notebook, i.e. even after the running notebook completes execution it's still showing variables from the other, idle notebook? Or do you mean that while the running notebook is executing code, the variable explorer doesn't update to show variables that are defined during execution?

FWIW, this is what I'm seeing--when switching from an idle notebook to a running notebook, the variable explorer always shows the variables in the active notebook. 

![recording](https://user-images.githubusercontent.com/30305945/118375150-abe9eb80-b574-11eb-86cc-0389874b7f4e.gif)

If you could provide a screen recording using something like gifcap.dev that would really help make sure I'm not misunderstanding this issue. Thank you so much!

**Comment by grapland0** [comment]
Thank you for the help! I mean, when a notebook is executing code, its variable explorer doesn't show the variable newly created after its last focusing and refresh.

From the screen record below, it is expected that both A and B are showed at the end of the video. 
![recording](https://user-images.githubusercontent.com/11003371/118403944-b44e2f00-b625-11eb-8b1f-84de0a5a70a6.gif)

**Comment by grapland0** [comment]
From the screen cap I also find another issue... When the focus is on the notebook at right side, the variable explorer can be updated by notebook on the left.

**Comment by joyceerhl** [comment]
Thanks for providing the screen recording, really helped to clarify the issue.

If notebook A is executing, and I switch focus from notebook A to notebook B, then back to notebook A while execution has not completed, then 
1. the variable explorer continues to show notebook B variables even when focus is set to notebook A. At minimum we should show 'No variables' or the last known list of variables (may be stale but still better than showing variables from a different notebook)
2. when notebook A finishes executing, the variable explorer does not update to show the new variables. You have to run another cell in notebook A for the variable explorer to update.

**Comment by joyceerhl** [comment]
>  When the focus is on the notebook at right side, the variable explorer can be updated by notebook on the left.

I didn't see this in the screen cap, could you please clarify? 😅

**Comment by grapland0** [comment]
> Thanks for providing the screen recording, really helped to clarify the issue.
> 
> If notebook A is executing, and I switch focus from notebook A to notebook B, then back to notebook A while execution has not completed, then
> 
> 1. the variable explorer continues to show notebook B variables even when focus is set to notebook A. At minimum we should show 'No variables' or the last known list of variables (may be stale but still better than showing variables from a different notebook)

Last known list of variables is perfect. It would be better if there is a label indicating whether it is up to date.

> 2. when notebook A finishes executing, the variable explorer does not update to show the new variables. You have to run another cell in notebook A for the variable explorer to update. We should be refreshing the list of variables after execution completes.

Yes please!

**Comment by grapland0** [comment]
> > When the focus is on the notebook at right side, the variable explorer can be updated by notebook on the left.
> 
> I didn't see this in the screen cap, could you please clarify? 😅

Attached. It is expect that the variable shows variable C at the end of the video. 

![rec2](https://user-images.githubusercontent.com/11003371/118451148-cbcefb80-b6a9-11eb-8fcb-4f32c79a3951.gif)

**Comment by rchiodo** [comment]
Maybe we switch to using the DAP to get variables? IPyKernel supports it now...

**Comment by amunger** [comment]
looks like this has been fixed
