### ISSUE TITLE
Native Notebooks - trying to escape %debug breaks notebook

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5903]
## Steps to reproduce: 

Using this as an example in the first cell: 

![image](https://user-images.githubusercontent.com/19276747/118385312-b59a4000-b5c2-11eb-9a3e-50f54f5bc6be.png)

1. Put %debug in the second cell and run it
2. Enter variable "first" in drop down -> 5 should show up in the output of second cell 
3. Try to quit by either escape or by stopping the cell execution at the cell level 

## Actual Behavior: 
1. If you try to press escape, every time you press escape the value 5 shows up in the output again + drop down glitches
2. If you try to stop the execution at the cell level, an infinite loop starts to put 5s in the output. Gets completely stuck and you cannot stop it, have to shut down vsc completely 

## Expected Behavior: 
For both options to terminate debugging

**Comment by roblourens** [comment]
Seems fine, works for me
