### ISSUE TITLE
No heading Collapse, No table of content 

### ISSUE THREAD

**Issue by ZedTDean** [microsoft/vscode-jupyter#5905]
Issue Type: <b>Feature Request</b>

No heading Collapse, No table of content 

Those are becoming essential in jupyter Notebook and jupyterLab and Google Colab, and they should be in Visual studio 

Extension version: 2021.6.832593372
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

**Comment by claudiaregio** [comment]
Hi @ZedTDean, both these will be included in VS Code Stable when we migrate to Native Notebooks. If you would like to try it out today, please download and use VS Code Insiders: https://code.visualstudio.com/insiders/
