### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by sayid-alt** [microsoft/vscode-jupyter#5906]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.6.832593372`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by joyceerhl** [comment]
@sayid-alt, please fill out our [bug template](https://github.com/microsoft/vscode-jupyter/issues/new?assignees=&labels=bug&template=1_bug_report.md) so we can assist you. Thanks!
