### ISSUE TITLE
Enable  Export PDF /HTML in .NET Interactive 

### ISSUE THREAD

**Issue by LadyNaggaga** [microsoft/vscode-jupyter#5913]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.745244803
-   .NET Interactive Extension version: v1.0.2228010

[Reference issue ](https://github.com/dotnet/interactive/issues/1334)

## Expected behaviour
- User clicks on export to PDF or html they get an output 

## Actual behaviour

- User clicks on export to PDF or html the notebook 
     - the Exporting to PDF is left hanging 
![EXPORT](https://user-images.githubusercontent.com/2546640/118552719-4b51de80-b72d-11eb-97d7-70465b53e24f.gif)

**Comment by joyceerhl** [comment]
Our export functionality has a runtime dependency on Python interpreter and the `nbconvert` Python package. Exporting to PDF has an additional runtime dependency on `xelatex`. s@LadyNaggaga is the request is to enable the export functionality without requiring users to install Python and `nbconvert`?

**Comment by claudiaregio** [comment]
IIRC @rchiodo, you said this should just work correct?

**Comment by rchiodo** [comment]
Yes. But it requires python and nbconvert to be installed. It should prompt to install however.

**Comment by LadyNaggaga** [comment]
Ok, I see. To leverage these features the user would need to have Python and `nbconvert` installed. 
Thought, should be consider hiding this from .NET customers? Or are there any other workarounds your team has in mind for scenarios like .NET Interactive?

**Comment by claudiaregio** [comment]
@LadyNaggaga Is exporting to HTML/PDF not something that .NET customers want to be able to do?

**Comment by claudiaregio** [comment]
I had a quick chat with @rchiodo, he said that installing Python and nbconvert would not change what a user sees. For example, if a user has a .NET notebook open they have the .NET interactive kernel in the bottom right and the .NET compatible languages in their code cells, installing Python and nbconvert will not change any of those in their notebook. We would look into the global interpreter that would have nbconvert and could use that to convert to HTML/PDF.

**Comment by jonsequitur** [comment]
What's the desired experience for people who don't have Python and nbconvert installed? 

* Should the button be visible for discoverability of the feature?
* Should people who don't want the feature have a way to hide the button?
* Assuming it's always visible, what's the process when someone clicks it without having the dependencies present? 
  * Is it an automated install or do we provide install instructions? 
  * How large is the install? 
  * What's the uninstall story?

**Comment by rchiodo** [comment]
We think it should be enabled. 

To answer your questions:

Should the button be visible for discoverability of the feature?

> Should people who don't want the feature have a way to hide the button?

We think everybody should have a consistent experience.

> Assuming it's always visible, what's the process when someone clicks it without having the dependencies present?

We'll ask them to install the dependencies.


> Is it an automated install or do we provide install instructions?

Should be automated.


> How large is the install?

Depends upon what they have to install. 


> What's the uninstall story?

Uninstall python

**Comment by greazer** [comment]
Closing because .NET no longer requires Jupyter to open IPYNB files.
