### ISSUE TITLE
Data Viewer in Geopandas 

### ISSUE THREAD

**Issue by abashishvili** [microsoft/vscode-jupyter#5920]
Hello Everyone, 

I am working in Vscode using  Jupyter notebook in the native notebook editor. 

When I import geopandas dataframe I am not able to open the data viewer. While the data viewer works perfectly for pandas dataframe. I searched for possible solutions but seems there are none. So I thought it would be awesome if you add this update for the next releases. 

Best

**Comment by IanMatthewHuff** [comment]
@abashishvili I repro this as well. I'm going to take a quick look at the code here, might be something that we can basically support already.

**Comment by tyler-c2s** [comment]
This would be awesome! Currently you have to convert to a pandas dataframe to view. One potential flag would be how the geometry column is handled, I have had DataFrames with geometry not load with `Failed to create the Data Viewer. Check the Jupyter tab of the Output window for more info.` Perhaps due to the size of the geometry?

Example where this failure happens:
```python
import geopandas as gpd
import pandas as pd

world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
world_pandas = pd.DataFrame(world)
```

Dropping the geometry allows to view as expected:
```python
import geopandas as gpd
import pandas as pd

world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
world_pandas = pd.DataFrame(world.drop(columns='geometry'))
```

**Comment by abashishvili** [comment]
Useful hint indeed. I just tried and worked perfectly. The extension would be still valuable though.

**Comment by IanMatthewHuff** [comment]
@abashishvili @tyler-c2s When I took a look at this quick (sorry I dropped the investigation to close out on a few higher priority issues) I ran into the same issue with the geometry column. I was able to support the type, but it blows up with the data in that column. In our data converter we have the ability to drop columns. Pretty sure that I can support things just fine doing what @tyler-c2s  was doing inside our data viewer code. Questions, from what I see of it there isn't any reason why someone would want to directly look at this geometry data in column form. But would it be confusing to a user (I'm not a Data Scientist / Geopandas) user to not see the column there?

**Comment by tyler-c2s** [comment]
I can see how it could be confusing to not see the column represented when de-bugging a GeoDataFrame, is there any precedent to displaying a "hidden" column to indicate it exists but is not shown?

Overall I agree the geometry itself isn't too useful to view in the table, and is more useful to view through something like [hvplot](https://hvplot.holoviz.org/user_guide/Geographic_Data.html)
