### ISSUE TITLE
IPyLeaflet doesn't work in native notebooks

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5922]
Output from VS code native:

![image](https://user-images.githubusercontent.com/19672699/118726209-db535f00-b7e5-11eb-9ae6-2ae31c5a0ded.png)

Output from same environment with jupyter:

![image](https://user-images.githubusercontent.com/19672699/118726253-eb6b3e80-b7e5-11eb-8127-464cf6b2f732.png)

No errors in the developer tools console. Not sure why it's not working.

**Comment by rchiodo** [comment]
Works fine in the interactive window

![image](https://user-images.githubusercontent.com/19672699/118726396-1ce40a00-b7e6-11eb-819d-b69b051f9de5.png)

**Comment by rchiodo** [comment]
My guess is we're dropping some of the messages.

**Comment by joyceerhl** [comment]
Works for me today:

![image](https://user-images.githubusercontent.com/30305945/119562536-49a29f00-bd5b-11eb-9026-42c88ce2903e.png)


@rchiodo is it still broken for you?

**Comment by rchiodo** [comment]
Nope working for me now.
