### ISSUE TITLE
Change language of cells if not recognized

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5924]
Assume user opens a notebook:
* User opens a Python notebook
* Somehow user accidentally switches to .NET interactive kernel & hits run (now .net extension will change cells to .NET language)
* User realizes the wrong kernel was selected
* Now user changes to Python kernel
* User hits run, nothing happens

Problem:
* Nothing happens when clicking run
	* Is this something that needs to be addresed in VSCode Core 
* Cell language is `.NET` when Python notebooks don't support this.
 	* Should python kernel change language of cells from unsupported language to Python?

@rebornix /cc

**Comment by DonJayamanne** [comment]
Flagging as kernel issue, as the user is blocked from running a notebook at this stage.
This is similar to what user ran into in diary study, the cell language is incorrect and they cannot run a cell.

Very easy to run into when user has .NET extension & Python notebooks.

**Comment by rchiodo** [comment]
Pending spec from @claudiaregio

**Comment by IanMatthewHuff** [comment]
Validated. When selecting a new controller cell languages are changed to what is supported by that controller.
