### ISSUE TITLE
Jupyter extension just won't work

### ISSUE THREAD

**Issue by jiewangjs** [microsoft/vscode-jupyter#5928]
![image](https://user-images.githubusercontent.com/11204422/118807218-978e5180-b8da-11eb-863f-48a863af7f1f.png)
fresh install, jupyter notebook just won't work. cell cannot be executed.

**Comment by rchiodo** [comment]
Thanks for the bug.
@jiewangjs can you include the output of the 'jupyter' tab:

![image](https://user-images.githubusercontent.com/19672699/118865747-22009200-b896-11eb-941d-2137c7e52cb5.png)

It may be that you need to update your VS code and your Jupyter Extension. When using VS code insiders things are breaking every day.

**Comment by jiewangjs** [comment]
> Thanks for the bug.
> @jiewangjs can you include the output of the 'jupyter' tab:
> 
> ![image](https://user-images.githubusercontent.com/19672699/118865747-22009200-b896-11eb-941d-2137c7e52cb5.png)
> 
> It may be that you need to update your VS code and your Jupyter Extension. When using VS code insiders things are breaking every day.

problem solved. after endless trials, some package get installed, ~ipytext something like that.
