### ISSUE TITLE
Remove execution isolation script

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5931]
With trusted notebooks coming up, we should be able to remove this.
Python team is remove code at their end

https://github.com/microsoft/vscode-python/pull/16274

**Comment by rchiodo** [comment]
https://github.com/microsoft/vscode-jupyter/blob/main/pythonFiles/pyvsc-run-isolated.py

**Comment by DonJayamanne** [comment]
This should be fine before post ga, we know this causes issues, and had been known to cause a number of issues in python extension as well.
Removing this will fix potential bugs users are drinking into today, ie remove stuff we don't need.

**Comment by DonJayamanne** [comment]
Part of workspace trust work. Once a workspace is trusted, we don't need this.

**Comment by DonJayamanne** [comment]
Validated
