### ISSUE TITLE
Notebook cells will not run ==> Error: cannot delete password (source: jupyter (extension))

### ISSUE THREAD

**Issue by indyrambler** [microsoft/vscode-jupyter#5934]
## Environment data

-   VS Code version: 1.56.2
-   Jupyter Extension version: v2021.6.832593372
-   Python Extension version: v2021.5.842923320
-   OS: Linux (Opensuse Tumbleweed)
-   Python and/or Anaconda version: 3.8.10
-   Type of virtual environment used: venv
-   Jupyter server running: Local

## Expected behaviour

Expect basic cell to run through with no vscode errors. I have been attempting mainly with a cell that only has imports.

## Actual behaviour

When I click to run any cell the only response is an error popup on vscode that reads: cannot delete password (source: jupyter (extension))
![image](https://user-images.githubusercontent.com/47614226/118872944-c1318380-b8ae-11eb-9d90-2d416dd2cef8.png)

The output of the cell is shown here:
![image](https://user-images.githubusercontent.com/47614226/118873233-1bcadf80-b8af-11eb-839e-ab7fce31e0d1.png)

## Steps to reproduce:

1. Open any .ipynb file in vscode (jupyter environment loads successfully and correctly as far as I can see)
2. Click the run button on the first cell (jupyter seems to recognize the venv kernel even though vscode says it's not started)
3. Error pops up immediately in the bottom right corner of vscode window

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)

Info 2021-05-19 21:31:52: Executing cell NotebookImport#3
Info 2021-05-19 21:31:52: Waiting for jupyter server and web panel ...
Error 2021-05-19 21:31:52: Exception attempting to start notebook:  Error: Cannot delete password
    at E.$deletePassword (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1763:64048)
Info 2021-05-19 21:31:52: Exception executing cell NotebookImport#3:  Error: Cannot delete password
    at E.$deletePassword (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1763:64048)
Info 2021-05-19 21:31:52: Finished executing cell NotebookImport#3
Error 2021-05-19 21:31:52: DataScience Error Error: Cannot delete password
    at E.$deletePassword (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1763:64048)
Info 2021-05-19 21:31:54: Trusting notebook...
</summary>

<p>

```
xxx
```

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the bug. 

It looks like your encrypted storage is corrupted and our attempts to cleanup after it are failing. You might be able workaround this by deleting your user settings (although this will reset all of your settings if you do)

On windows those settings are stored here:

```C:\Users\<user name>\AppData\Roaming\Code\User\globalStorage```

If you stop VS code and delete the files and directories under that location, the problem should go away.

This was likely caused by this fix here:
https://github.com/microsoft/vscode-jupyter/commit/54bc65d32fc2d767879d525a8c3fe452541a8205

**Comment by indyrambler** [comment]
Thanks for the feedback. This workaround does not appear to have worked.

The settings you referred to on my OS (openSUSE Tumbleweed) are apparently at this location:
<code>/home/<username>/.config/Code/User/globalStorage</code>

I delete all of the contents of that directory after vscode is closed. New contents appear when I open vscode again. The jupyter notebook cell reacts the same (with an error).

Could this be related to admin rights somehow? Any other ideas?

**Comment by rchiodo** [comment]
This should only go down this path if you had been using a remote jupyter server before. You could try deleting your workspace and user settings.json (well really just the settings prefixed with 'jupyter')

**Comment by indyrambler** [comment]
Perfect! Thanks for the tip.

Switched the jupyter.jupyterServerType value to "local" in the the workspace and the user settings and now the cells run as expected.

This is strange because I have not used a remote server yet just FYI.

**Comment by rchiodo** [comment]
Do you have another machine? There is a sync settings option that might have moved it over. That might even be the cause of the problem as the expected URI isn't in the storage.

Or possibly if your workspace settings came down from another user submitting them to source control.

**Comment by indyrambler** [comment]
I used to use a Windows machine but I haven't used sync settings since I switched over. I only enabled the sync settings as an attempted fix to this problem actually. Thought it would be useful in the future as well though.

I'm not worried about it at this point but if you need more info on this bug I'll provide it. Just happy to know it's being checked out and I can still work.

**Comment by IanMatthewHuff** [comment]
I don't have the specific validation on this (requires windows + corrupted storate), but resolved based on no incoming customer issues since then.
