### ISSUE TITLE
Notebook getting started experience challenges/questions

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5936]
**Scenario 1**
* User creats a new notebook using `Create Blank Notebook`
* The notebook will default to `Python` (for new users)
* User will get a prompt to install Python extension (bottom right prompt)
* Is this good? What if the user wanted to get strated with TypeScript or Julia?

**Scenario 2**
* User creats a new notebook by creating a new file in VSC explorer `new.ipynb`
* The notebook will default to `plaintext` (for new users)
* Ther'es a slight difference between this scneario and previous.
* Why is it `plaintext`, should it be `python`
* However now user will get prompted to isntall Python, if the user was planning on working on TypeScript.

**Scenario 3**
* User has anaconda installed (but no jupyter kernels, in global path)
* User has Jupyter extension installed
* User opens a notebook (they get the dummy `Python 3` placeholder kenrel)
* User hits the run button, they get prpompted to install Python extension
* User installs it
* Now what?
* Ok, user hits run button again, but gets the exact same message
* Also the kernel picker doesn't display the new kernels.

**Problems**
* Annoying Prompts
	* Getting prompted to install Python when user intents on creating TS notebook
	* Getting prompted to install Python when user is just planning on opening a notebook to read (not exefcute)
* Solution is to Reload VS Code
	* Even after installing Python extensions, the run button doesn't work (need to reload vs code)
	* Even after installing Python extension, the list of kernels hasn't changed (need to reload vs code)

**Suggestion**
* Recommend installing Python only when the user hits the `run` button
	* Not sure, if 99% of the users are python, should we change this?
	* But if we don't, then we're always assuming it will be pyhton & ignoring the others.
	* Popups are a tough one (using popups are easy, finding an alternative is difficult).
* Fetch the list of the kernels once the Python extension has been activated `IPythonApiProvider.onDidActivatePythonExtension`
* When Python extension is installed and user attempts to run a cell
	* The dummy kernel should wait for kernel search to complete
	* After this, this dummy kernel should be upgraded to the preferred kernel (same solution we use here https://github.com/microsoft/vscode-jupyter/issues/5861)
	* I.e. if user has 10 pytho kernels, this placeholder will end up being upgraded to one of the 10 (it must be the preferred item).
	* Next after all of this, the run continues and starts the kernel.
	* NOTE: Disposing this kernel controller will not work, as its already associated with the document (user ran a cell)
	* Problem with this solution, next time user loads VSCode and opens this notebook, the placeholder kernel no longer exists, hecne when user attempts to run a cell, they'll get prompted once again to select a kernel **(no ideal)**
	* NOTE: The kernel that was used in both cases must be the same, we need to upgrade the placeholder to the preferred kernel.

@claudiaregio /cc

**Comment by DonJayamanne** [comment]
Working on this with @claudiaregio right now.

**Comment by rchiodo** [comment]
> Problem with this solution, next time user loads VSCode and opens this notebook, the placeholder kernel no longer exists, hecne when user attempts to run a cell, they'll get prompted once again to select a kernel (no ideal)

Isn't the selected kernel remembered by VS code on the next open?

**Comment by rchiodo** [comment]
Spec should cover other scenarios.
