### ISSUE TITLE
Accepting autocomplete suggestions in a notebook duplicates already typed text

### ISSUE THREAD

**Issue by irfanka** [microsoft/vscode-jupyter#5944]
## Environment data
- OS: XUbuntu 20.04, Linux x64 5.8.0-53-generic
- VS Code: 1.56.2 (and also previous versions)
- Commit: 054a9295330880ed74ceaedda236253b4f39a335
- Date: 2021-05-12T16:45:26.313Z
- Electron: 12.0.4
- Chrome: 89.0.4389.114
- Node.js: 14.16.0
- V8: 8.9.255.24-electron.0

## Expected behavior

Selecting autocomplete suggestions (e.g. hitting Tab) should add only the missing chars of the suggested expression

## Actual behavior

(Sometimes) manually-typed characters are duplicated, and the completion is appended after that

![autocomplete_bug](https://user-images.githubusercontent.com/5460254/119050089-aac81c80-b9c1-11eb-81a9-44e8b878f5d8.gif)

## Steps to reproduce

Unknown; the issue ocurrs sporradically and with no apparent reason. I've had this start happening in the exact same cell where it worked as expected mere seconds before that (and without the cell even losing focus).

P.S. this never happens in regular files; only in notebooks.

**Comment by rchiodo** [comment]
Dupe #5956
