### ISSUE TITLE
Update to new renderer API (notebook renderers) 

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#5951]
https://github.com/microsoft/vscode/issues/93265#issuecomment-844237859

Was already working on this but adding an issue now. Code change was easy, but sadly using the new ES6 import (which is good in general) requires that we move to webpack 5. So far I have a working implementation, though I was seeing an issue with plotly that I'll have to look into more.

**Comment by DavidKutu** [comment]
validated
