### ISSUE TITLE
Update to new renderers API (Jupyter)

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#5952]
https://github.com/microsoft/vscode/issues/93265#issuecomment-844237859

Jupyter version of the new renderers update. Issue here is that I'm a bit more worried about webpack 4 -> 5 update here. Just more going on with our webpack in Jupyter. Will tackle this after renderer API is updated.

**Comment by DonJayamanne** [comment]
Nothing to valdiate, moving as closed
