### ISSUE TITLE
Adopt `notebook/toolbar` contribution point for native notebooks

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5954]
Just had a chat with @rebornix about this. With Sunday night's Insiders build, extensions will be able to contribute items to `notebook/toolbar`, with the following groups:
* `navigation/edit`
* `navigation/execute` <-- This will house restart kernel and interrupt kernel
* `navigation` <-- This will house other actions like open variable view and export
* `status` <-- This appears on the right of the notebook toolbar and currently houses only the kernel picker. In future we can consider moving the local/remote status item up here, but for now we should not contribute to this group

We will be able to specify a `shortTitle` for each command that appears in the notebook toolbar. When present, this `shortTitle` attribute will be displayed next to the command's associated codicon in the toolbar, so as not to take up too much horizontal space with a lengthier title. VS Code will then pick either `shortTitle` or the existing `title` to display depending on context.

**Comment by claudiaregio** [comment]
Wahoooo ok entry points to move into the notebook toolbar: 

1. Short Title: Restart , Title: Restart Kernel - Navigation/Execute
2. Short Title: Interrupt, Title: Interrupt Kernel - Navigation/Execute
3. Short Title: Variables, Title: Open Variable View - Navigation 
4. Short Title: Export, Title: Export As - Navigation

**Comment by joyceerhl** [comment]
PR has been merged, should go out in tonight's Jupyter extension insiders build.

**Comment by IanMatthewHuff** [comment]
Validated. 
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/ec33ec79-4e71-482e-ab60-24f74e723574)
