### ISSUE TITLE
Tweak variable view fit and finish

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#5955]
1. Hide the 'Variables' title as we already have the view container title
2. Drop colors for variable contents
3. Change fonts used in column headers and table rows
4. Rework border styling on column headers
5. Rename 'Jupyter: Open Jupyter Variable View' to 'Jupyter: Open Variable View'

See https://github.com/microsoft/vscode/issues/118115 for Figma mockups of the intended look

/cc @claudiaregio based on feedback from @rebornix

**Comment by claudiaregio** [comment]
All of these changes sound good to me, they follow the VS Code theming much closer. Thanks @rebornix for the feedback! 

Let's go ahead and do this for webview as well since it's an easy fix.

**Comment by joyceerhl** [comment]
![image](https://user-images.githubusercontent.com/30305945/119212781-7317ae00-ba6f-11eb-85bb-e0d311fa3da7.png)

![image](https://user-images.githubusercontent.com/30305945/119212804-9b071180-ba6f-11eb-916b-edd8f894101c.png)

**Comment by IanMatthewHuff** [comment]
Validated. Looks good now.
