### ISSUE TITLE
Method completions inserting double values when selected

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-jupyter#5956]
I'm currently working in a native notebook editor on my local VS Code.

I have my Python language server set to "None" (not using Pylance or Jedi), and am seeing the following for completions:

![image](https://user-images.githubusercontent.com/6413608/119205055-fde6b180-ba4b-11eb-9462-a7703129c66a.png)

When choosing the completion I see the following:

![image](https://user-images.githubusercontent.com/6413608/119205071-0d65fa80-ba4c-11eb-9a86-134ef51016e5.png)

Instead of just inserting "get_image_details" the Notebook editor inserts "env.get_image_details". I'd expect only the method from the completion to be inserted when selected.

**Comment by claudiaregio** [comment]
Have to discuss if this is worth fixing since this is why we recommend language servers

**Comment by rchiodo** [comment]
Somehow the text edits from Jupyter aren't working in latest VS code. 

I'm guessing this doesn't repro in the interactive window.

**Comment by greazer** [comment]
It does not repro in the IW. However, it seems likely that people who set the LS to none is a small number. Therefore, moving out of upcoming milestone.

**Comment by jiewangjs** [comment]
Any feedback on the problem ?

**Comment by rchiodo** [comment]
> It does not repro in the IW. However, it seems likely that people who set the LS to none is a small number. Therefore, moving out of upcoming milestone.

This repros with pylance. It doesnt' require ls set to none.

**Comment by jiewangjs** [comment]
@rchiodo Yep, I figured it out. Disabled pylance, and problem solved.

**Comment by roblourens** [comment]
Was anything changed here? What needs verification?

**Comment by SiddhanthUnnithan** [comment]
@DonJayamanne just want to confirm that with the changes you merged @jiewangjs will no longer need to disable Pylance to avoid seeing double values?

**Comment by claudiaregio** [comment]
@SiddhanthUnnithan I believe the completions were actually coming from Jupyter, we merge both Pylance and Jupyter returned ones. This wasn't a Pylance issue so @jiewangjs shouldn't need to disable Pylance for Don's fixes to be seen
