### ISSUE TITLE
Native Notebooks - Drop down options for "Create new notebook" command gone

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5957]
## Environment data

-   VS Code version: 1.57.0 - insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.863311888

## Steps to reproduce: 
1. Use Jupyter Create new notebook command

## Expected behavior: 

*Rolling back to v2021.6.849191191 solves the issue and shows the picture below*

![image](https://user-images.githubusercontent.com/19276747/119205926-954d0400-ba4e-11eb-97a5-b77478a4e3ed.png)

## Actual behaviour

Just creates new notebook, no drop down options with .NET languages comes down

**Comment by DonJayamanne** [comment]
Works for me
![Screen Shot 2021-05-24 at 08 53 57](https://user-images.githubusercontent.com/1948812/119373749-9ad46500-bc6d-11eb-9f57-119a7085a40a.png)

**Comment by DonJayamanne** [comment]
Please could you try updating to latest insiders & Jupyter extension.

**Comment by claudiaregio** [comment]
I updated to the latest version (v2021.6.870847776) and it is fixed
