### ISSUE TITLE
Native Notebooks - Add Plot Viewer 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5960]
Have gotten continuous feedback for experiment and requests to bring back plot viewer in native notebooks. 

To discuss: Can we add a button using our own output renderers or does it require that we request an API for a button that is tied to an output?

**Comment by rchiodo** [comment]
Can we make SVG data transient? Perhaps there's some way to tag our 'special' SVG so that we can distinguish between customer made SVG versus ours.

**Comment by rchiodo** [comment]
Another idea would be to ask the user when clicking on the plotviewer whether or not to generate SVGs.

**Comment by DonJayamanne** [comment]
Do users need a plot viewer that allows them to zoom in/out.
WHy not just open the image in a tab, I'm think they just need the ability to save the plot and open on the side so they can see something before and after.
Would be a simple enough to add for Native Notebooks and wait to see the feedback.

**Comment by claudiaregio** [comment]
I have seen both schools of feedback - some asking to bring back plot viewer explicitly by name, and some to have the ability to save outputs. If we can make the SVG data transient such that people can just interact with it while working with the notebook, but not having it save to the notebook, that would give the ability for people to have both. zoom in/zoom out and save as, without making the notebook size increase drastically

**Comment by peguerosdc** [comment]
Just found this! I commented on a very big thread asking fot the Plot Viewer back https://github.com/microsoft/vscode-jupyter/issues/6315#issuecomment-870986194 .

Thanks for bringing the "save" feature back! At least for my use-case, that is everything I need except that right now the only option available is to save the PNG image, but I would like to save the SVGs as well (I remember there was an option to save the PDF too, but that I don't need). Hope it can be considered!
