### ISSUE TITLE
Kernel died with exit code 1073741845. 

### ISSUE THREAD

**Issue by futurehome** [microsoft/vscode-jupyter#5963]
Hi, 

When I tried to launch interactive window in vscode, it failed with the error below. Could you please help to identify what's wrong with it?

thanks,
alex
 
Issue Type: <b>Bug</b>

Kernel died with exit code 1073741845. C:\Users\Alex.wang\.virtualenvs\vtree-_4DfoHDc\lib\site-packages\traitlets\traitlets.py:2196: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use 'hmac-sha256' instead of '"hmac-sha256"' – or use CUnicode.
  warn(
C:\Users\Alex.wang\.virtualenvs\vtree-_4DfoHDc\lib\site-packages\traitlets\traitlets.py:2151: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '5995421f-97b9-4627-9c28-0b10e2db4c56' instead of 'b"5995421f-97b9-4627-9c28-0b10e2db4c56"'.
  warn(
Bad address (C:\projects\libzmq\src\epoll.cpp:100)

Extension version: 2021.6.832593372
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (0.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30301612
vscorehov:30302759
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by DavidKutu** [comment]
Hi @futurehome. Sorry to hear you're having issues. Could you check which version of traitlets you have in your virtual env?
Run `pip list` to find out and please let me know.

**Comment by futurehome** [comment]
The version of traitlets is 5.0.5.

The code is just some simple test code.

**Comment by DavidKutu** [comment]
Got it, could you please reproduce the issue and share the logs in the panel under `Output -> Jupyter`?
Please make sure your `jupyter.logging.level` setting is set to debug.

**Comment by DonJayamanne** [comment]
@futurehome Please could you try the following:
`python -m pip install ipykernel --upgrade --force-reinstall`
Ensure you do this in the Python environment  you are using (u might want to activate it or the like).

**Comment by futurehome** [comment]
The command failed as below, but I can install other package successfully.
![image](https://user-images.githubusercontent.com/6230304/119795512-20287580-bf0b-11eb-8f53-34b7d29a17d7.png)

> @futurehome Please could you try the following:
> `python -m pip install ipykernel --upgrade --force-reinstall`
> Ensure you do this in the Python environment you are using (u might want to activate it or the like).

**Comment by futurehome** [comment]
The log file is attached.

[jupyter.log](https://github.com/microsoft/vscode-jupyter/files/6552510/jupyter.log)



> Got it, could you please reproduce the issue and share the logs in the panel under `Output -> Jupyter`?
> Please make sure your `jupyter.logging.level` setting is set to debug.

**Comment by HarshulGaba** [comment]
I had the same issue in conda environment i tried reinstalling and updating but nothing worked

**Comment by Kevin-Luyu** [comment]
> The command failed as below, but I can install other package successfully.
> ![image](https://user-images.githubusercontent.com/6230304/119795512-20287580-bf0b-11eb-8f53-34b7d29a17d7.png)
> 
> > @futurehome Please could you try the following:
> > `python -m pip install ipykernel --upgrade --force-reinstall`
> > Ensure you do this in the Python environment you are using (u might want to activate it or the like).

Hi,

I had exactly the same issue with you and have made some further attempts, which reveals a possible internal conflict of packages in ipykernel.  

The permission issue in your picture can be possibly resolved by using `python -m pip install ipykernel --upgrade --force-reinstall --user` instead (adding the `user` to the end). NB: I was prompted to add the `--user` at a VS Code version of 1.58.2. So maybe you can consider updating your VS Code first. 

When executing the prompt, I got the error message that says some packages are too new. However, I found that upgrading the ipykernel automatically installs the "too new" jedi==0.18.0 and parso==0.8.2, even when I have just lowered their version to 0.17.2 and 0.7.0, which then creates the dependency conflict. At this stage, I have no idea how to proceed and hope someone else can help with this problem. The error massage of dependency conflict is pasted below. 

pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 4.2.5 requires jedi==0.17.2, but you have jedi 0.18.0 which is incompatible.
spyder 4.2.5 requires parso==0.7.0, but you have parso 0.8.2 which is incompatible.
python-language-server 0.36.2 requires jedi<0.18.0,>=0.17.2, but you have jedi 0.18.0 which is incompatible.

I would be happy to provide further information and hope the issue can be resolved soon.

**Comment by futurehome** [comment]
This issue still exists in 1.59.0 and the latest version of Jupyter extension.

**Comment by futurehome** [comment]
I solved this issue by reinstall Pyzmq==19.0.2.

**Comment by Kevin-Luyu** [comment]
> I solved this issue by reinstall Pyzmq==19.0.2.

I resolved my issue using your method as well, though in my case I was still prompted that the dependency conflict of parso and jedi exist. Hope this entire issue can be better handled in later releases.

**Comment by ranningw** [comment]
> I solved this issue by reinstall Pyzmq==19.0.2.

how to do that? I have the same problem as you posted.

**Comment by stephentesta** [comment]
I'm using a conda environment and I solved this issue by downgrading python to version 3.8.

**Comment by Gavin-jy** [comment]
> I solved this issue by reinstall Pyzmq==19.0.2.

I did the same thing and My problem has been eventually solved! Thanks a lot!

**Comment by DonJayamanne** [comment]
Fixed as part of https://github.com/microsoft/vscode-jupyter/issues/8354

**Comment by DonJayamanne** [comment]
**Testing**
* Run a cell using raw kernels
* Get the Pid of the process `os.getpid()` & kill that process from outside VS Code
* Confirm you get a message when the kernel has died.

**Comment by IanMatthewHuff** [comment]
Verified. Looks good.
