### ISSUE TITLE
Endless widget loading in Insiders

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#5965]
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/92168a1a-77d2-4105-b868-87f19615ff75)

I'm currently seeing this in insiders bits. I'd assumed that this was due to my renderer API changes that hit monday (build ending with 7776) but I just rolled back to version ending with 888, which should still be supported and which doesn't have my renderer changes, and it exhibited the same issue.

**Comment by ryanbrownnetworking777** [comment]
I'm having something similar where my code cells are endlessly running.

**Comment by IanMatthewHuff** [comment]
@ryanbrownnetworking777 Do you have a code sample that repros this? That (along with the version of VS Code / Jupyter extension that you have) and I could help look into this.

**Comment by greazer** [comment]
Issues labeled with "Info needed" are closed if we do not receive more information from the issue author in 2 weeks. If you are the issue author and you still are running into this problem, please reactivate with additional information.
