### ISSUE TITLE
Add the cell edit functions like split, merge, cut, move,etc.

### ISSUE THREAD

**Issue by AndyZZt** [microsoft/vscode-jupyter#5966]
![image](https://user-images.githubusercontent.com/29043558/119359781-8aa79e80-bcdc-11eb-91ba-627254fe3a77.png)
Since those functions of Jupeter Notebook bring great convenience to users, it will be satisfying to see those usful functions implemented on your plugin.

**Comment by claudiaregio** [comment]
Hi @AndyZZt, these features are supported in VS Code Insiders and will be resolved when we migrate to Native Notebooks for Stable. To try out today, download here: https://code.visualstudio.com/insiders/
