### ISSUE TITLE
Plotly bundle having issues after the new Renderer API change

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#5967]
Plotly graph is not displaying correctly after change to new notebook renderer API.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/8b66664c-da2f-4ee2-a19e-eaa0b26a7942)

`import plotly.graph_objects as go
fig = go.Figure(data=go.Bar(y=[2, 3, 1, 5]))
fig.show(`

**Comment by IanMatthewHuff** [comment]
https://github.com/plotly/plotly.js/issues/3518

**Comment by CalebEverett** [comment]
I think this may be the same issue, so adding here.

plotly stopped showing figures in code-insiders a couple of days ago

Issue Type: <b>Bug</b>

To replicate, start a new notebook in vscode-insiders and then try to run this cell
```python
fig = px.line(x=[0 ,1], y=[1, 2])
fig.show()
```

I've tried all of the different renderer types and the best is that a blank box displays in the cell where the chart should display. In most cases nothing happens. If no renderer is specified, a code symbol is available when clicked that provides an option to select the mimetype, with options for "application/vnd.plotly.v1+json" and "text/html", but neither results in the chart begin rendered.

If I toggle the developer tools, I get the following errors in the console:

```javascript
request {element: div#20596943-2608-4fc8-a5b1-6e3b1f2612fe.output, mime: "application/vnd.plotly.v1+json", value: {…}, metadata: {…}, bytes: ƒ, …}

Rendering mimeType application/vnd.plotly.v1+json {data: {…}, metadata: {…}, execution_count: null, output_type: "display_data"}

renderers.js:2 TypeError: this.Plotly.newPlot is not a function
    at componentDidMount (plotly.bundle.js:2)
    at zl (renderers.js:2)
    at Il (renderers.js:2)
    at renderers.js:2
    at Object.t.unstable_runWithPriority (renderers.js:2)
    at _i (renderers.js:2)
    at Si (renderers.js:2)
    at ki (renderers.js:2)
    at vi (renderers.js:2)
    at Hl (renderers.js:2)
```

Thanks for any help.

Just a couple of days ago this was working really nicely, with the figures displaying at 100% width and rendering the same way when the notebook was exported. The figures display in the regular version of vscode, but don't display at 100% width.

VS Code version: Code - Insiders 1.57.0-insider (286b643ecd231f66f3f2e67e1456f3c601838b46, 2021-05-25T05:24:28.413Z)
OS version: Windows_NT x64 10.0.19043
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (11.75GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/caleb/projects/traffic --remote=wsl+Ubuntu --crash-reporter-id f7543aed-88e3-49ba-bc08-aa9439d824e1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|24.85GB (15.68GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.179.0
remote-ssh|ms-|0.65.6
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.2
vscode-remote-extensionpack|ms-|0.21.0
git-graph|mhu|1.30.0
python|ms-|2021.6.864643163-dev
vscode-pylance|ms-|2021.5.4-pre.1
jupyter|ms-|2021.6.870847776
code-spell-checker|str|1.10.2


</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30303025
vscgsv2:30305091
vscorehov:30301224
3f5j7703:30294757
vscod805:30301674

```

</details>

**Comment by IanMatthewHuff** [comment]
@CalebEverett Per my PR here tomorrow's build of Jupyter on VSCode - insiders should have a fix for this.

https://github.com/microsoft/vscode-notebook-renderers/pull/51

**Comment by CalebEverett** [comment]
Awesome - looking forward to getting back to the awesome experience you guys are delivering  - thanks!

**Comment by greazer** [comment]
Running with the latest insiders, it appears that all is working well... Specifically the repro @CalebEverett, had above works.

**Comment by nicolaskruchten** [comment]
In principle, Plotly.js 2.0 (released today!) should be better-behaved with respect to ES6 imports :)

**Comment by IanMatthewHuff** [comment]
> In principle, Plotly.js 2.0 (released today!) should be better-behaved with respect to ES6 imports :)

@nicolaskruchten Awesome. Thanks for the heads up. I've filed #6182 to investigate / update.
