### ISSUE TITLE
Jupyter cannot detect ipykernel with pypy3.7

### ISSUE THREAD

**Issue by inumanag** [microsoft/vscode-jupyter#5969]
## Environment data

-   VS Code version: 1.56.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.832593372
-   Python Extension version (available under the Extensions sidebar): v2021.5.842923320
-   OS (Windows | Mac | Linux distro) and version: macOS Big Sur and Catalina
-   Python and/or Anaconda version: pypy 7.3.4 (Python v3.7.10)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A / pyenv
-   Jupyter server running: both Local and Remote

## Expected behaviour

Jupyter should start an interactive session.

## Actual behaviour

It does not, and asks for 'Python 3.7.10 64-bit ('pypy-venv': venv) requires ipykernel to be installed", despite it being installed.

## Solution?

The bug seems to be related to `pyvsc-run-isolated.py`: replacing `sys.path[:] = (p for p in sys.path if p != "" and normalize(p) != cwd)` (line 20) with `sys.path[:] = [p for p in sys.path if p != "" and normalize(p) != cwd]` solves the problem. Seems that pypy does not handle generators as Python does.

## Steps to reproduce:

1. install pypy3.7
2. Try to run a local kernel on a py file with `#%%` cells.

**Comment by DavidKutu** [comment]
Hi @inumanag. Thanks for the solution! Let me get pypy on my machine and I'll test it

**Comment by DavidKutu** [comment]
I'm running into some zmq errors when running pypy (even without the extension).

Does the change on `pyvsc-run-isolated.py` fix the issue to you @inumanag?

**Comment by inumanag** [comment]
Yes, that change pretty much solves all the problems, and the pypy kernel works as expected afterwards.

**Comment by DavidKutu** [comment]
Thanks for your input, I'll make the change

**Comment by joyceerhl** [comment]
We're actually already planning to remove the isolate script: https://github.com/microsoft/vscode-jupyter/issues/5931

**Comment by DavidKutu** [comment]
That's post GA, might as well have this change to unblock users with pypy in the mean time.

**Comment by IanMatthewHuff** [comment]
Validated. I'm having some issues with the zmq wheel build to install ipykernel, but it seem to be handling the detection ok, so it should be working for any setup that has that installed correctly.

@inumanag Is this resolved for you in current Jupyter insiders builds? Just comment here if you are still seeing the issue.

**Comment by inumanag** [comment]
Thanks for looking into this! I unfortunately won't be able to check the insider build anytime soon, but will report the issue again if the issue still persists after the next update.
