### ISSUE TITLE
Can't open Jupyter first time

### ISSUE THREAD

**Issue by akald** [microsoft/vscode-jupyter#5975]
On Windows 10, and the latest version of VS code:

If VScode is not opened and I try to open an .ipynb from file explorer, VSCode will open the file and then load the Python extension.

Since the Python extension has loaded after loading the .ipynb file, VSCode won't display the Jupyter file in the correct way, but as a sort of textfile. 

If VScode is already open, and I open a jupyter file, it works. But I don't always have VScode open.

**Comment by claudiaregio** [comment]
Seems like dupe of https://github.com/microsoft/vscode/issues/124527?

**Comment by akald** [comment]
Yes its the same bug as that one. I close
