### ISSUE TITLE
Native Notebooks - Shift + Enter to render markdown 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5976]
I almost reopened https://github.com/microsoft/vscode/issues/123819 but realized based on the description it was working correctly. When the markdown content is already rendered, shift+enter will skip to the next cell. However, when in edit mode, shift+enter does not render the markdown cell and move to the next. 

In Jupyter, if the markdown cell is in edit mode and user presses shift+enter it renders the markdown cell. Could shift+enter be updated to also render markdown cells when in edit mode?

**Comment by claudiaregio** [comment]
Ok that sounds good! We can do that :)

**Comment by IanMatthewHuff** [comment]
Validated. Shift-enter in markdown edit mode now renders the markdown and moves to the next cell.
