### ISSUE TITLE
Convert base64 string to bytes when adding images to output

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5978]
It looks like VS Code doesn't render the images anymore.
I think this is because the mime types are expecting bytes for images instead of a base64 encoded string.

Currently we have our own renderers, however when using VS Code renderers they don't work.
I think we should convert to bytes, then everything works (we convert bytes back to base64 string) and handle it in our renderers.

Will check with @rebornix

**Comment by rchiodo** [comment]
Is this still busted?

**Comment by DonJayamanne** [comment]
Its fixed
