### ISSUE TITLE
opening matplotlib plots in a separate 'plots' window.

### ISSUE THREAD

**Issue by Siddhant-Reddy-Bose** [microsoft/vscode-jupyter#5981]
Previous vs code notebook allowed us to simply click a button on a matplotlib plot to have it be copied in a separate 'plots' window/tab. This allowed tallying the plots across multiple runs side by side and making minor changed easily before saving to file.
I can't find this feature anymore! please put this incredible feature back

**Comment by joyceerhl** [comment]
We are planning to add this back: https://github.com/microsoft/vscode-jupyter/issues/5960

**Comment by DonJayamanne** [comment]
Dup of $5960
