### ISSUE TITLE
widget_jsmol is not loading jsmol

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [microsoft/vscode-jupyter#5988]
Hello
I am using widget_jsmol , I am trying to displat jsmol in vscode
Yet, it just display a white box but doesn't load the structure

I am not getting any error 

Do you have any ideas of how to solve this?

best, 

Andres

**Comment by DonJayamanne** [comment]
Hi everyone, I'm sorry about this isue, we've identifeied the cause, we'll be pushing a fix within the next 30 minutes or so.

**Comment by DonJayamanne** [comment]
@AndresOrtegaGuerrero Please could you install the latest Jupyter extension from the marketplace and try this again. I believe you are using VS Code Insiders (we just published a new version with a fix)

**Comment by AndresOrtegaGuerrero** [comment]
@DonJayamanne  Thank you for your help, I tried to install the latest version, yet 
If I check for the new version it doesn't appear. I went to the marketplace link and also it doesn't let me get the new version.

**Comment by rchiodo** [comment]
It sounds like you're using the stable version (not insiders then). Let me try to repro.

**Comment by rchiodo** [comment]
The jsmol widget doesn't seem to have published it's current JS to npm. 

We look for this widget: JmolView:widget_jsmol:^2.0.0

And only this version seems available: 
@osscar/widget_jsmol@0.1.0


You might have seen this popup:

![image](https://user-images.githubusercontent.com/19672699/119898235-6d4e1c80-bef6-11eb-9149-b98c85b8258e.png)

However it does seem to work okay in the insiders build of VS code. You might try it there:

![image](https://user-images.githubusercontent.com/19672699/119898210-61faf100-bef6-11eb-9b77-88b17bcd2acf.png)
