### ISSUE TITLE
Append error config in VSCode setting.json make VSCode not working. Message: (this.configurationService.getValue(...) || []).filter is not a function

### ISSUE THREAD

**Issue by andy3520** [microsoft/vscode-jupyter#5993]
## Environment data

-   VS Code version: 1.56.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.832593372
-   Python Extension version (available under the Extensions sidebar): v2021.5.842923320
-   OS (Windows | Mac | Linux distro) and version: macOS Bug surr 11.3.1
-   Jupyter server running: Local

## Expected behaviour
Vscode working normally

## Actual behaviour
When ever you click to a file/an extension or what ever you wanna open in VSCode it will show an error
```
(this.configurationService.getValue(...) || []).filter is not a function
```

And you cannot open them.
As I check the extension add to `setting.json` and make the file error with message `Incorrect type. Expect "array"`
The setting:
```
"workbench.editorAssociations": {
    "*.ipynb": "jupyter-notebook"
  },
```
Remove this config will make VSCode working normal again.
## Steps to reproduce:
Install Python extension package

1. Screenshoot
![image](https://user-images.githubusercontent.com/38342390/119690064-8feb2180-be73-11eb-83cd-92ef9e182b71.png)
![image](https://user-images.githubusercontent.com/38342390/119690120-9b3e4d00-be73-11eb-81ad-89ad88c5bae6.png)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Python interpreter path: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Starting Jedi Python language engine.
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda --version
Error 2021-05-26 22:49:49: Diagnostic Code: MacInterpreterSelectedAndHaveOtherInterpretersDiagnostic, Message: You have selected the macOS system install of Python, which is not recommended for use with the Python extension. Some functionality will be limited, please select a different interpreter.
Diagnostic Code: MacInterpreterSelectedAndHaveOtherInterpretersDiagnostic, Message: You have selected the macOS system install of Python, which is not recommended for use with the Python extension. Some functionality will be limited, please select a different interpreter.
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"

```

</p>
</details>

**Comment by joyceerhl** [comment]
Do you have a third party settings sync extension installed by any chance? If so we recommend the built-in settings sync functionality instead: https://code.visualstudio.com/docs/editor/settings-sync.

For context, the format you are seeing above (object format) is a new format that works only in VS Code Insiders. The format that is supported in 1.56 stable is the old array format which will be deprecated in the upcoming release. You should not be seeing this setting unless you have explicitly synchronized your settings or copied and pasted your settings files from Insiders to Stable.

**Comment by andy3520** [comment]
Hi, @joyceerhl I'm only using the built-in setting sync of VSCode, no 3rd party at all.
And yes I use both of the VSCode versions and I don't copy the setting json. I make it isolated sync with each other.
But thanks for the setting.

**Comment by andy3520** [comment]
Yes, I just move to a new laptop and reinstall all the tool.

**Comment by joyceerhl** [comment]
Thanks for the info, I will investigate. Sorry for the trouble and thanks for filing a bug!

**Comment by andy3520** [comment]
Np, thanks again for the fix.

**Comment by joyceerhl** [comment]
Do you have VS Code Insiders installed on either your old or new machine?

**Comment by andy3520** [comment]
Nope, I just remove all of it after got the bug, right now I'm only have the stable one.

**Comment by joyceerhl** [comment]
Did you have Insiders before? I'm wondering if the built-in settings sync is synchronizing settings between Insiders and Stable.

**Comment by joyceerhl** [comment]
I'm not able to reproduce this if I enable settings sync, uninstall VS Code and delete settings locally, then reinstall VS Code and resync settings. The only way I see this possibly happening is if you enabled the built-in settings sync across VS Code Stable and Insiders, which is not recommended due to issues like this (setting formats changing between stable releases). 

@andy3520 if you can reliably reproduce this problem or if you recall the specific sequence of actions you took to induce this bug, please share them so we can determine if this is a bug or a simple misconfiguration.

**Comment by andy3520** [comment]
I'll try another day if this happens as the sync false or my mistaken config. Close this for now, sorry for late reply @joyceerhl  got busy w/ stuffs.
