### ISSUE TITLE
Can't stop loading :Extension issue

### ISSUE THREAD

**Issue by KushagraSahu20012000** [microsoft/vscode-jupyter#6009]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.6.832593372`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rchiodo** [comment]
Thanks for the bug.

Do you have any more information? Is the jupyter extension just not loading?

Can you goto Help | Toggle Developer Tools and copy the console output here?

**Comment by greazer** [comment]
Please reopen when more info can be provided.
