### ISSUE TITLE
VSIX install fails on Visual Studio Code Stable

### ISSUE THREAD

**Issue by pilarArr** [microsoft/vscode-jupyter#6011]
## Environment data

-   VS Code version: 1.56.2
-   Jupyter Extension version (available under the Extensions sidebar): all vsix available versions on marketplace
-   Python Extension version (available under the Extensions sidebar): 2021.5.842923320
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: N/A
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: N/A
- No internet connection

## Expected behaviour

That vsix file installs the current version for the extension on Visual Studio Code Stable

## Actual behaviour

Error anouncing that the extension is not compatible with Visual Studio Code 1.56.2

## Steps to reproduce:

1. Get vscode installer for stable version and vsix installers for extensions Python and Jupyter
2. Turn off internet
2. Install Visual Studio Code Stable
3. Install vsix for python extension
3. Install vsix for jupyter extension

## Logs

```
[2021-05-27 10:38:17.235] [renderer1] [error] Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.56.2'.: Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.56.2'.
    at file:.../Visual Studio Code/VSCode-win32-x64-1.56.2/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:211002
```

I suspect that the problem resides on the `package.json` file used to compile the vsix file. The engine declared was the insiders one, like it is now in the main branch.

Edit: typo

**Comment by rchiodo** [comment]
This is because of this issue here:
https://github.com/microsoft/vsmarketplace/issues/43

In order to install Jupyter you can install it from within VS code or use the hacky workaround described here:
https://github.com/microsoft/vscode-jupyter/issues/5582#issuecomment-824235026

**Comment by rchiodo** [comment]
This issue will be solved once the marketplace bug is resolved. Please track and/or upvote that issue.
