### ISSUE TITLE
Native Notebooks - Remove old toolbar location icons 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#6019]
When Jupyter is able to activate the left global notebook toolbar for all, let's make sure to remove duplicate icons in the top right old toolbar. 

![image](https://user-images.githubusercontent.com/19276747/119930492-63e3a500-bf34-11eb-8a1d-65755a9cc87c.png)

**Comment by claudiaregio** [comment]
Since the default is now the global toolbar, can we make sure to remove these when "notebook.globalToolbar": true and display them when "notebook.globalToolbar": false ?

**Comment by DavidKutu** [comment]
![image](https://user-images.githubusercontent.com/20347396/121613690-e890f180-ca11-11eb-8c05-6420fb89b39b.png)

validated
