### ISSUE TITLE
Can't load python interpretor

### ISSUE THREAD

**Issue by shug1565** [microsoft/vscode-jupyter#6021]
Issue Type: <b>Bug</b>

Hi, just installed the latest jupyter extension, which fixed the plotly not showing problem, but I can't load my python interpretor now. If I press shift+enter, it just puts a new line in the code instead of running the cell. I tried to manually select a different interpretor, but it didn't work either.

Could you please help? Many thanks.

Extension version: 2021.6.885080120
VS Code version: Code - Insiders 1.57.0-insider (1082913dd012e21cc5f35a06f15c480ca447f67f, 2021-05-27T06:55:24.593Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz (24 x 2007)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (17.79GB free)|
|Process Argv|--crash-reporter-id 717eb2b4-1f36-481a-a450-8f77d9e8959c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30286553
pythonvsuse255:30303025
vscgsv2:30305091
vscorehov:30301224
vscod805:30301674

```

</details>

**Comment by joyceerhl** [comment]
@shug1565 Hi, sorry for the trouble. 

Are you trying to use shift+enter inside an ipynb file, or inside a Python file with #%% cell delimiters?

Additionally, could you please provide logs from the Jupyter extension's output panel? You can find them here:

![image](https://user-images.githubusercontent.com/30305945/120002521-c61ac500-bf89-11eb-95c7-b9c8eecd8f6f.png)

**Comment by shug1565** [comment]
Thanks for the follow up! It’s working now after I updated the vscode insider when a new version was available.
