### ISSUE TITLE
Take very long time (~ 1-2 minutes) to start the jupyter extension

### ISSUE THREAD

**Issue by quantumsnowball** [microsoft/vscode-jupyter#6022]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.6.832593372`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 143,
		"activateCallTime": 3,
		"activateResolvedTime": 943,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-toolsai.jupyter",
				"_lower": "ms-toolsai.jupyter"
			},
			"activationEvent": "onLanguage:python"
		}
	},
	"runtimeErrors": []
}
```

**Comment by joyceerhl** [comment]
Hi @quantumsnowball, please fill out our bug template so we can assist you: https://github.com/microsoft/vscode-jupyter/issues/new?assignees=&labels=bug&template=1_bug_report.md Thank you!
