### ISSUE TITLE
Option to hide toolbars above cells / move them to the left of the cells instead of on top

### ISSUE THREAD

**Issue by sofroniewn** [microsoft/vscode-jupyter#6024]
Hello, I'd like the option to hide the toolbars above individual cells. My apologies if this is already provided, I've spent quite a lot of time searching the settings and documentation and couldn't find it (though I have seem screenshots where the toolbar isn't there).

To be clear the toolbar I am referring too is the line with the green triangle, icon, and the M in the screenshot below which you can see appearing about 7 times. 

![image](https://user-images.githubusercontent.com/6531703/120014132-8908ff80-bf96-11eb-8540-10b6d231c67e.png)

I'd much prefer those icons if necessary to appear on the left side of the code cell. The screenshots on this page https://code.visualstudio.com/docs/python/jupyter-support-py make it look like that used to be the case, see 

![image](https://user-images.githubusercontent.com/6531703/120014479-f61c9500-bf96-11eb-9a79-2c725e7281c1.png)

But the screenshots here https://code.visualstudio.com/docs/python/jupyter-support all have the new style which I also seem to have 

![image](https://user-images.githubusercontent.com/6531703/120014593-1d736200-bf97-11eb-87ff-8eb43d5a5285.png)

The reason I prefer to have the icons on the left is that I never click on them, they take up a lot of vertical space so i see less code at any given time, and I'm constantly clicking on them selecting the cell when I want to click into the typing space to start typing.

Note this feature request follows my question here https://stackoverflow.com/questions/67728767/customize-style-of-jupyter-notebooks-in-visual-studio-code

Thanks and apologies if I just missed this in the settings!!

**Comment by sofroniewn** [comment]
Wow, thanks for the prompt reply! I've given this a try and now see 

![image](https://user-images.githubusercontent.com/6531703/120017676-02a2ec80-bf9b-11eb-82a0-21f0829cd51a.png)

which is definitely preferable for me. I probably say my ideal look would be with the first notebook style just with those buttons on the left, but that is purely aesthetic and not functional. I can work with this. Thanks!

**Comment by sofroniewn** [comment]
I guess I was quick to close, i can leave that up to you if this is something you want to support or not, feel free to close though if this issue is no longer useful to you!

**Comment by claudiaregio** [comment]
@sofroniewn Just for our validation purposes, when you first installed Insiders, was the toolbar on the right like in your screenshot?

**Comment by sofroniewn** [comment]
> @sofroniewn Just for our validation purposes, when you first installed Insiders, was the toolbar on the right like in your screenshot?

It believe it was but now I'm not sure, it could have been on the other side (I guess the left, but I don't think it was on top). The "notebook.cellToolbarLocation" setting was pre-populated with something, but I actually ended up deleting it as doing so moved that little box with the trashcan to the top left (where it is in the screenshot) over from the top right of the cell, where i found it blocking some of my text. Right now that setting is empty.

I'm not sure if it's helpful or desired, but I'd be happy to provide additional design feedback on the layouts or test other settings / customization - for example I don't love having the execution time in seconds below every cell as the vast majority of the time I am not interested in that and so it adds visual clutter. I know that you can't please everyone though, and some people might find it useful, so feel free to ignore

**Comment by joyceerhl** [comment]
> The "notebook.cellToolbarLocation" setting was pre-populated with something

@claudiaregio sounds like our cell toolbar automigrate was working then. (For context the Jupyter extension defaults the cell toolbar to the left)

>  for example I don't love having the execution time in seconds below every cell as the vast majority of the time I am not interested in that and so it adds visual clutter.

You can disable that using this setting:

```
    "notebook.showCellStatusBar": false,
```

**Comment by joyceerhl** [comment]
> I'd be happy to provide additional design feedback on the layouts or test other settings / customization

We are always interested in feedback, please feel free to open issues or comment here!

**Comment by sofroniewn** [comment]
>  "notebook.showCellStatusBar": false,

Nice, I like that!

> We are always interested in feedback, please feel free to open issues or comment here!

Thanks! You've been very helpful today, I've been able to make quite some progress customizing things to how I like them!!

**Comment by claudiaregio** [comment]
@sofroniewn If you want to try other settings click the ... in the notebook toolbar and select "Configure Notebook Editor Layout Settings". 
![image](https://user-images.githubusercontent.com/19276747/120090184-56095d80-c0b5-11eb-8079-e9e9b4594925.png)

There you can customize a bunch of other settings that were just added
![image](https://user-images.githubusercontent.com/19276747/120090206-8fda6400-c0b5-11eb-905c-eb13a5c21e47.png)
