### ISSUE TITLE
Remove run above and below buttons from cell toolbar

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#6025]
These are now implemented in VS Code core:

![image](https://user-images.githubusercontent.com/30305945/120284617-48003c00-c271-11eb-9d7f-8278aea44872.png)

**Comment by claudiaregio** [comment]
Summary of discussion: Leave the VS Code drop down actions, change our run all above/below icons to use their commands, add telemetry that shows usage of both of those icons.

**Comment by IanMatthewHuff** [comment]
I'd say validated, but it's actually that these are now not provided by VS Code and we put our back in. But I validated that as well.

**Comment by joyceerhl** [comment]
Actually, we ended up removing ours. At least for the 1.57 stable release, the default layout settings disable the consolidated run button, so VS Code's run above/below buttons end up in the cell toolbar.

**Comment by IanMatthewHuff** [comment]
Should have paid more attention to the adding and removing. I thought the cell toolbar ones were back to us.
