### ISSUE TITLE
Unable to open .ipynb with Insider's Build

### ISSUE THREAD

**Issue by abergerSRS** [microsoft/vscode-jupyter#6030]
Issue Type: <b>Bug</b>

I have a Jupyter Notebook (head_cal.ipynb) that successfully opens in the stable release of VSCode. However, when I try to open it the Insider's Build, I receive the error: 

> Unable to open 'head_cal.ipynb': INVALID mime type, must not be empty or falsy: <Figure size 576x576 with 1 Axes>.

This "INVALID mime type" error just started when I updated Insider's to the latest update.

VS Code version: Code - Insiders 1.57.0-insider (1082913dd012e21cc5f35a06f15c480ca447f67f, 2021-05-27T06:55:24.593Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (7.24GB free)|
|Process Argv|--crash-reporter-id 600f255c-13b3-4856-9d32-64dba66e24c6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.6.864643163-dev
vscode-pylance|ms-|2021.5.5-pre.1
jupyter|ms-|2021.6.881596855

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30291487
pythontb:30258533
vsc_aacf:30263846
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30303025
vscgsv2:30305091
vscorehov:30301224
vscod805:30301674

```

</details>

**Comment by abergerSRS** [comment]
No, the issue persists even with Jupyter v2021.6.885080120

Version: 1.57.0-insider (user setup)
Commit: 541a5d4fa70ab3095f23b28b88914e1f6a8f65c4
Date: 2021-05-28T09:50:57.063Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by joyceerhl** [comment]
It looks like you're on the latest VS Code insiders, but just to be sure, do you have a 'Restart to Update' in your help menu?

![image](https://user-images.githubusercontent.com/30305945/120044813-6b05c400-bfc3-11eb-8a6c-1436a6f00256.png)


Additionally is there any chance you can share the ipynb file (you can zip it up as a zip archive and attach it in a comment on this issue) so we can reproduce the issue and debug it locally?

**Comment by zx1621** [comment]
I have the same issue.
You can try to clear all outputs in the jupyter notebook.
It works for me.

**Comment by claudiaregio** [comment]
@zx1621 did you update to the latest version of VS Code, Python and the Jupyter extensions? I received confirmation from other customers running into this issue that it is resolved for them.

**Comment by zx1621** [comment]
@claudiaregio Sure. I updated vscode-insider and these extensions, but it didn't work. So I cleared all outputs in the jupyter notebook and it workes.

**Comment by claudiaregio** [comment]
@zx1621 Oh okay, glad to hear you're unblocked :)

**Comment by abergerSRS** [comment]
Clearing outputs worked for me. Thank you @zx1621
