### ISSUE TITLE
VSCode Insiders, Jupyter notebook not loading in remote, extension does not seem to be loading 

### ISSUE THREAD

**Issue by Santosh-Gupta** [microsoft/vscode-jupyter#6032]
Whenever I try to open a jupyter notebook in remote using VSCode insiders I get this message 

>"Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed or enabled."

and an option to "Reopen file with VS Code standard text editor"

Jupyter, Python, and Pylance are installed. 

I do Not get this error in regular VSCode, this only happens in Insiders 

## Environment data

-   VS Code version: Version: 1.57.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.885080120

-   Python Extension version (available under the Extensions sidebar): v2021.5.842923320
-   OS (Windows | Mac | Linux distro) and version: local, mac os 11.2 (20D64), remote, linux ubuntu 20.04
-   Python and/or Anaconda version: Python 3.6.9 64-bit.
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: N/A

## Expected behaviour

Should open 

## Actual behaviour

Does not open 

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

Connect to a remote server.

right click on jupyter notebook file -> open with -> Jupyter Notebook.

From looking at this issue

https://github.com/microsoft/vscode-jupyter/issues/586

It seems that the extension is not loading.

**Comment by joyceerhl** [comment]
@Santosh-Gupta please could you provide the contents of the Jupyter output panel in the terminal panel? 

![image](https://user-images.githubusercontent.com/30305945/120031424-a2697600-bfad-11eb-9b85-ae0df5f12d40.png)

**Comment by Santosh-Gupta** [comment]
I figured out the issue. I noticed that there was a box on the bottom left that said 'Restricted mode'. I clicked on it and selected 'trust'. Now it's working again. 

Sorry for the inconvenience.
