### ISSUE TITLE
Add option for creating interactive console connected to the notebook kernel

### ISSUE THREAD

**Issue by sztal** [microsoft/vscode-jupyter#6033]
It would be a killer feature to have the functionality (which is already available in Jupyter Lab) to create interactive Python consoles connected to specific notebook kernels. The main usecase is to be able to work interactively based on the state of a notebook without having to tinker with the notebook itself.

I am speaking of this feature (from Jupyter lab)

_You can connect a code console to a notebook kernel to have a log of computations done in the kernel, in the order in which they were done. The attached code console also provides a place to interactively inspect kernel state without changing the notebook. Right-click on a notebook and select “New Console for Notebook”:_

(from [the official documentation](https://jupyterlab.readthedocs.io/en/stable/user/notebook.html))

EDIT.
This may be related to #1278 , but I think the two requests are slightly different (in this case setting a breakpoint should not be needed).

**Comment by joyceerhl** [comment]
Thanks for the suggestion. Does https://github.com/microsoft/vscode-jupyter/issues/4573 cover your use case?

**Comment by sztal** [comment]
Hmm, I must say I am nost sure. I am not familiar with the idea of "scratchpad" notebooks, but I think that the feature described there is more complicated than what I am suggesting. Here the idea is not to have a parallel "scratchpad" notebook (which would keep track of code in cells/chunks etc.) but just to have an ability to launch an IPython shell (within VS Code) which is binded to the kernel of a specific notebook (so all objects defined in the notebook are accessible there etc.).

My hunch is that it could be realized by spawning a Python Interactive window connected to a specific kernel, but if for some reason it may be only implemented via some notebook-like interface then I think the scratchpad would do too (although it still seems to me a bit of an overkill in regard to my particular usecase).

But whatever you decide to do about it thanks for the great work! You made data analysis with Python really great :)

**Comment by greazer** [comment]
Thanks for the feedback. I think #4573 at least comes close to what you're looking for. Once we start moving more seriously along that path, we will end up with something that can work for your scenario.
