### ISSUE TITLE
Ship require.js with our renderers & kernel pre-loads

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#6034]
https://github.com/microsoft/vscode/pull/124864
Today we ship require.js with our preloads for CodeSpaces, we need to ship it always and also include it into our renderers

**Comment by IanMatthewHuff** [comment]
Picking this up. From the linked PR I should be able to test by removing the if statement from vscode core and making sure that things still work.

**Comment by IanMatthewHuff** [comment]
Getting into this now. It's a bit odd, I commented out the ipynb workaround in vscode core before making changes. My assumption was that something would have broken at that point using our current bits, but all the basics seem to be working fine.

**Comment by DavidKutu** [comment]
validated requirejs is preloaded
