### ISSUE TITLE
Support OAuth login for JupyterHub

### ISSUE THREAD

**Issue by TomAugspurger** [microsoft/vscode-jupyter#6035]
vscode-jupyter currently supports JupyterHub managed single-user notebook servers by including a token in the connection string or through a [username / password flow](https://github.com/microsoft/vscode-jupyter/blob/b1f70d0fc436c9bade9941406b2590b4034cf2bf/src/client/datascience/jupyter/jupyterPasswordConnect.ts#L18).

Many hubs are deployed with OAuth, often using the [jupyterhub-oauthenticator](https://jupyterhub.readthedocs.io/en/stable/reference/authenticators.html#the-oauthenticator) project. Would it be possible to support an oauth2 flow to authenticate with JupyterHub, in addition to token and username/password?

(https://github.com/microsoft/vscode-jupyter/issues/5430 mentions oauth, but that's related to the output of a widget rather than authenticating with a Hub).

Thanks!

**Comment by claudiaregio** [comment]
Thanks for the request! Will discuss it at our next triage :)

**Comment by DonJayamanne** [comment]
Closing in favour of https://github.com/microsoft/vscode-jupyter/issues/12268
