### ISSUE TITLE
Select kernel options missing when after running a jupyter notebook cell in VScode Insiders

### ISSUE THREAD

**Issue by ChandlerTayek** [microsoft/vscode-jupyter#6036]
When creating a fresh `.ipynb` file and trying to run `print('hello world')` I get prompted to select from an empty list of kernels. 
![image](https://user-images.githubusercontent.com/6510301/120048989-85449f80-bfcd-11eb-87f4-fd954a39c83c.png)

Here is a list of my current available kernels on my machine: 
![image](https://user-images.githubusercontent.com/6510301/120049145-f08e7180-bfcd-11eb-8aa6-f322839a99e4.png)

I have tried reinstalling the python and jupyter notebook extension for VScode with no luck.

Edit: I'm running 1.57.0-insider on Windows 10 Home

**Comment by claudiaregio** [comment]
Hi @ChandlerTayek! Do you have the Python extension installed?

**Comment by claudiaregio** [comment]
@ChandlerTayek Could you please provide the extension versions that you are using for Jupyter and Python?

**Comment by ChandlerTayek** [comment]
@claudiaregio Yes
Jupyter: 2021.6.885080120
Python: 2021.5.842923320

**Comment by joyceerhl** [comment]
Additionally do you have a pending VS Code Insiders update? The latest is 541a5d4fa70ab3095f23b28b88914e1f6a8f65c4 and you'll need to restart VS Code after installing the update.

Finally can you please share the Jupyter output logs? You can find them here: 
![image](https://user-images.githubusercontent.com/30305945/120050065-e7eb6a80-bfd0-11eb-8da4-5c1491178c13.png)

**Comment by ChandlerTayek** [comment]
I just installed the update that got pushed to me 30 or so mins ago. I think this is the correct info on my VScode insiders version: 
![image](https://user-images.githubusercontent.com/6510301/120050223-7d86fa00-bfd1-11eb-8254-c6ebdbcf6951.png)

Jupyter output log for opening up a jupyter-notebook.
```Info 2021-05-28 16:25:12: Checking if notebook is trusted
Info 2021-05-28 16:25:12: Check if Notebook is Trusted, Class name = p, completed in 2ms, has a truthy return value, Return Value: true
Info 2021-05-28 16:25:12: notebook communications already initialized for editor file:///c%3A/Users/chand/tools/geo1-tools/flight1-code/delivery/dev_this.ipynb
Info 2021-05-28 16:25:12: Attempting to start a server because of preload conditions ...
Info 2021-05-28 16:25:12: findPreferredKernel score for Python3, Python 3.7.9 64-bit ('vir-env': conda) is 14
Info 2021-05-28 16:25:12: findPreferredKernel score for Python 3.7.9 64-bit ('vir-env': conda) is 24
Info 2021-05-28 16:25:12: findPreferredKernel score for Python3, Python 3.7.6 64-bit ('base': conda) is 4
Info 2021-05-28 16:25:12: findPreferredKernel score for Python 3.7.6 64-bit ('base': conda) is 4
Info 2021-05-28 16:25:12: findPreferredKernel score for Python3, Python 3.9.4 64-bit ('lidar': conda) is 4
Info 2021-05-28 16:25:12: findPreferredKernel score for Python 3.9.4 64-bit ('lidar': conda) is 4
Info 2021-05-28 16:25:12: findPreferredKernel score for Python3, Python 3.7.10 64-bit ('contractor-port': conda) is 4
Info 2021-05-28 16:25:12: findPreferredKernel score for Python 3.7.10 64-bit ('contractor-port': conda) is 4
Info 2021-05-28 16:25:12: findPreferredKernel score for Python3, Python 3.6.13 64-bit ('ocv4': conda) is 4
Info 2021-05-28 16:25:12: findPreferredKernel score for Python 3.6.13 64-bit ('ocv4': conda) is 4
Info 2021-05-28 16:25:12: findPreferredKernel score for Python3, Python 3.7.10 64-bit ('test-env': conda) is 4
Info 2021-05-28 16:25:12: findPreferredKernel score for Python 3.7.10 64-bit ('test-env': conda) is 4
Info 2021-05-28 16:25:12: findPreferredKernel score for Python3, Python 3.9.5 64-bit ('pygsheets-test': conda) is 4
Info 2021-05-28 16:25:12: findPreferredKernel score for Python 3.9.5 64-bit ('pygsheets-test': conda) is 4
Info 2021-05-28 16:25:12: findPreferredKernel score for speclanguage=python, Python (myenv) is -1
Info 2021-05-28 16:25:12: findPreferredKernel score for Python3, Python (myenv) is 2
Info 2021-05-28 16:25:12: findPreferredKernel score for Python (myenv) is 2
Info 2021-05-28 16:25:12: findPreferredKernel score for Python3, Python 3.7.6 64-bit ('chand-dqTe9_GW': pipenv) is 4
Info 2021-05-28 16:25:12: findPreferredKernel score for Python 3.7.6 64-bit ('chand-dqTe9_GW': pipenv) is 4
Info 2021-05-28 16:25:12: findPreferredKernel score for Python3, Python 3.9.4 64-bit ('copy-env': conda) is 4
Info 2021-05-28 16:25:12: findPreferredKernel score for Python 3.9.4 64-bit ('copy-env': conda) is 4
Info 2021-05-28 16:25:12: findKernel found Python 3.7.9 64-bit ('vir-env': conda)
Info 2021-05-28 16:25:12: Find kernel spec, Class name = D, completed in 2ms, has a truthy return value, Arg 1: <Uri:c:\Users\chand\tools\geo1-tools\flight1-code\delivery\dev_this.ipynb>, Arg 2: {"language_info":{"name":"python","nbconvert_exporter":"python"},"orig_nbformat":2}, Arg 3: {"_isCancelled":false,"_emitter":null}, Return Value: {"kind":"startUsingPythonInterpreter","kernelSpec":{"specFile":"C:\\ProgramData\\Anaconda3\\envs\\vir-env\\share\\jupyter\\kernels\\python3\\kernel.json","interpreterPath":"C:\\ProgramData\\Anaconda3\\envs\\vir-env\\python.exe","name":"python379jvsc74a57bd084d1faca0b8febb3ce0e8fa2205a38ff9901ab305c8446c2a4a216587d99d938","argv":["C:/ProgramData/Anaconda3/envs/vir-env\\python.exe","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"C:/ProgramData/Anaconda3/envs/vir-env\\python.exe","display_name":"Python 3.7.9 64-bit ('vir-env': conda)"},"interpreter":{"sysPrefix":"C:\\ProgramData\\Anaconda3\\envs\\vir-env","envType":"Conda","envName":"vir-env","envPath":"C:\\ProgramData\\Anaconda3\\envs\\vir-env","path":"C:\\ProgramData\\Anaconda3\\envs\\vir-env\\python.exe","architecture":3,"sysVersion":"3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]","version":{"raw":"3.7.9","major":3,"minor":7,"patch":9,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.7.9 64-bit ('vir-env': conda)"},"id":".jvsc74a57bd084d1faca0b8febb3ce0e8fa2205a38ff9901ab305c8446c2a4a216587d99d938.C:\\ProgramData\\Anaconda3\\envs\\vir-env\\python.exe.C:\\ProgramData\\Anaconda3\\envs\\vir-env\\python.exe"}
Info 2021-05-28 16:25:12: PreferredConnection: .jvsc74a57bd084d1faca0b8febb3ce0e8fa2205a38ff9901ab305c8446c2a4a216587d99d938.C:\ProgramData\Anaconda3\envs\vir-env\python.exe.C:\ProgramData\Anaconda3\envs\vir-env\python.exe found for NotebookDocument: file:///c%3A/Users/chand/tools/geo1-tools/flight1-code/delivery/dev_this.ipynb
```

**Comment by joyceerhl** [comment]
There is a VS Code Insiders update from 13 hours ago. I believe you'll need that one as there were breaking changes to the VS Code notebooks API that our extension uses. Sorry for the trouble. If you have a pending update this option in your help menu should read "Restart to Update":

![image](https://user-images.githubusercontent.com/30305945/120050364-056d0400-bfd2-11eb-87d5-1890df60143f.png)

**Comment by claudiaregio** [comment]
I am not able to reproduce with the same extension versions and the latest version of vs code. 
@ChandlerTayek can you check one more time for VS code updates? I have the latest commit Joyce mentioned and it's not happening for me. Your commit ends in 269 instead of the 5c4

Version: 1.57.0-insider (user setup)
Commit: 541a5d4fa70ab3095f23b28b88914e1f6a8f65c4
Date: 2021-05-28T09:50:57.063Z

**Comment by ChandlerTayek** [comment]
Update: So after installing the new VScode insiders build I was prompted in the bottom left to restart. I clicked and VScode Insiders restarted and reloaded my windows. To fix my problem I had to go into the Help menu and click on the option `Restart and Apply Update` in the menu located next to this option. I wasn't able to grab a screenshot at the time because I didn't think it would help. 
![image](https://user-images.githubusercontent.com/6510301/120050371-0d2ca880-bfd2-11eb-9b3b-75ca8fed7af8.png)

**Comment by ChandlerTayek** [comment]
@claudiaregio @joyceerhl  Amazing That we posted the same thing at the same time. Thanks for being friendly and helpful! Love the product and I try every bit to not use something else when it is working as expected.

**Comment by joyceerhl** [comment]
Thanks for filing a bug and we appreciate your understanding as we work to improve the extension--we're always grateful for feedback and support from users like you 😊

**Comment by ChandlerTayek** [comment]
Yeah in terms of products that I use for my job for Machine Learning some of the features on VScode are the best in the industry in terms of development eidtors. Keep up the great work.

**Comment by claudiaregio** [comment]
Thanks @ChandlerTayek! Don't hesitate to reach out for any other feedback or feature requests!
