### ISSUE TITLE
Shift + Enter Shortcut should execute cell or render markdown even if in edit mode

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#6037]
There is still an influx of customer feedback where the Shift + Enter shortcut key is not behaving as expecting in our notebooks. 
I believe this is due to the fact that core contributes multiple shift + enters, and their notebook one is being trumped by the other condition. Let's contribute Shift + Enter as well so it overrides and we make sure it works for our users. 

**Edit: Let's make sure this applies to Ctrl + Enter as well

**Comment by joyceerhl** [comment]
Markdown cells aren't rendered for ctrl+enter when in edit mode either.

**Comment by claudiaregio** [comment]
Let's make sure that behavior persists for ctrl + enter too

**Comment by IanMatthewHuff** [comment]
Validated. Shift+Enter / Ctrl+Enter work in edit and command mode. I can look at the Ctrl+Enter => control mode when it merges.
