### ISSUE TITLE
Native Notebooks - Kernel and languages not respected on save 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#6038]
### Steps to Reproduce
1. Have Python, Jupyter, .NET extensions installed and Julia kernel
2. Create new notebook - pick whatever kernel/language you want
3. Save notebook 
4. Repeat these steps multiple times with different kernels/languages

### Expected Behavior
For the kernel and languages of the cells to be preserved on save

### Actual Behavior
Appears to have a bit of a flash (reload?) and kernel is sometimes "cleared" (you see Select Kernel), or kernel has switched to something else randomly and the language for all the code cells are changed as well. I tried this multiple times, sometimes Julia went to .NET, sometimes Julia went to Python etc. 

Since now we have behavior that has the language of all code cells change when the kernel changes, I'm thinking that it's really the kernel that is not being persisted here...?

**Comment by rchiodo** [comment]
@claudiaregio closing this for now. Please reopen if it repros for you again.
