### ISSUE TITLE
Failure to install the extensions from a file in an offline environment

### ISSUE THREAD

**Issue by brainoom** [microsoft/vscode-jupyter#6039]
The recent versions of this extension cannot be installed in an offline environment. 

That is because during install the extensions tries to access some remote urls (on vscodeexperments.azureedge.net, dc.services.visualstudio.com, maybe others) and fail to install if these domains are unreachable.

Notes:

- Maybe an offline version is needed (like in vscode-cpptools)?
- Possibly related: #5582 (If this issue won't be fixed, fixing #5582 wont help the issue opener use case)

## Environment data

-   VS Code version: 1.56.2
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.870847776
-   Python Extension version (available under the Extensions sidebar): 2021.5.842923320
-   OS (Windows | Mac | Linux distro) and version: Windows and Linux
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used: N/A
-   Jupyter server running: N/A
-  System has no direct internet connection or with very limited internet accesss
 
## Expected behaviour

The extension should be installable.

# Actual behaviour

Recent version(s) of the extension cannot be installed in an environment as described above. 

## Steps to reproduce:

1. Download of the extension visx file from the [extension page](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter)
2. Turn off your wifi (airplane mode etc.).
3. Try to install the extension from the downloaded visx
4. An error is shown stating that the extension is not compatible

## Logs

In the Log (Window) panel:
```
... [renderer5] [error] Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.56.2'.: Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.56.2'.
    at file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:211002
.... [renderer5] [error] net::ERR_INTERNET_DISCONNECTED: Error: net::ERR_INTERNET_DISCONNECTED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:109:7029)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```

</p>
</details>

**Comment by joyceerhl** [comment]
The reason the latest VSIXes from the Marketplace page aren't working is because we publish VS Code Insiders-compatible builds to the Marketplace feed as well, so they show up on top. You can download the latest stable-compatible Jupyter extension build from https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2021.6.832593372/vspackage while we work on a more comprehensive solution.

**Comment by 0wk** [comment]
Here's another problem.
Although I install the extension on the link you provided, it still cannot be used directly as it will occur an Error "Extension activation failed". After I looked at the developer tools, I found that it needs the privilege of using proposed api. 
Only if I add an extra code `"enable-proposed-api": ["ms-toolsai.jupyter"]` in the "argv.json" can I solve the problem and use it. Maybe there's still some problem with the extension need to be fixed.

**Comment by joyceerhl** [comment]
@0wk What version of VS Code are you running? The Jupyter extension shouldn't require further proposed API enablement in 1.56.2, which is the latest version of VS Code stable.

**Comment by 0wk** [comment]
@joyceerhl Yep, 1.56.2, shown as below:

> 1.56.2
054a9295330880ed74ceaedda236253b4f39a335
x64

**Comment by joyceerhl** [comment]
@0wk  Sorry for the delayed response. Are you able to install the VSIX using this UI:

![image](https://user-images.githubusercontent.com/30305945/120724436-ab17eb80-c488-11eb-8e66-afba1ac9d568.png)

**Comment by timswiley** [comment]
> The reason the latest VSIXes from the Marketplace page aren't working is because we publish VS Code Insiders-compatible builds to the Marketplace feed as well, so they show up on top. You can download the latest stable-compatible Jupyter extension build from https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2021.6.832593372/vspackage while we work on a more comprehensive solution.

** Thank you this worked for me.
