### ISSUE TITLE
Jupyter Notebook Behavior Differences in VS Code vs VS Code Insiders

### ISSUE THREAD

**Issue by amitktripathi** [microsoft/vscode-jupyter#6045]
I recently gave VS Code Insiders a try and its impressive. The main reason I was trying Insider edition because I could not use Python extensions in Jupyter Notebook in VS Code. Interestingly I can do those in Jupyter Notebook in VS Code Insiders edition. However, I am finding the Markdown cells in VS Code insiders behaving strangely.

Few issues in VS Code Insiders while using Jupyter Notebook:
1. The rendered fonts are very small and I am not sure what way to control/change them (In VSCode, the font followed 'Font Family'
2. The markdown does not execute without manually pressing ctrl+alt+enter . In VS Code, this occurred as soon as the markdown cell was unselected
3. While I see that there are more than just python and markdown cell options now, however switching between these two is not happening as smoothly (using escape and then M or Y does not produce intended results of switching between markdown and python)
4. While not the biggest issue, the delete cell button is very close to other buttons in cell menu. I liked the layout in VS Code where delete cell button was separate and minimized accidental deletion of cell.

<img src="https://user-images.githubusercontent.com/83621642/120305083-fc3fa800-c2ed-11eb-92a6-f58a14a10ee4.png" width=500px />
Using VS Code 1.56.2
<img src="https://user-images.githubusercontent.com/83621642/120305088-fe096b80-c2ed-11eb-8785-60dc9931f8ad.png" width=500px />
Using VS Code Insiders 1.57

VS Code - 1.56.2
VS Code Insiders - 1.57
Windows 10

(If this report has incorrect format, I apologize. First time posting issue/feedback on git)

**Comment by IanMatthewHuff** [comment]
@amitktripathi Currently VSCode-insiders contains our new UI that we will be slowly rolling out into stable over the next releases. Thanks for providing the feedback on it. I believe that we already have an issue covering the markdown not executing, but not on the other issues. We can look into these changes.

**Comment by IanMatthewHuff** [comment]
Just for a clarification or two. For Rendered fonts you mean fonts in the notebook output, correct? Font family (and all other editor setting should still control the input code cells).

**Comment by amitktripathi** [comment]
> 
> 
> Just for a clarification or two. For Rendered fonts you mean fonts in the notebook output, correct? Font family (and all other editor setting should still control the input code cells).

@IanMatthewHuff That is correct. The font used in the markdown cell during editing is the one specified by `Font Family`. However, after the cell execution or `stop editing`, the font utilized are too small (my preference). I am not aware of any setting to modify fonts (family and size). Actually, it may be just my preference (or may be others too), can the the font styles in markdown be specified in separate setting than that from `Font Family`

Also, thank you for looking into other issues.

**Comment by chandresh** [comment]
I found some other issues using Jupytor notebook using VS Code Insiders: https://github.com/microsoft/vscode-jupyter/issues/6094

**Comment by greazer** [comment]
M & Y shortcut is covered by #4438

**Comment by joyceerhl** [comment]
M & Y work for me today. They are actually contributed by VS Code. 
![image](https://user-images.githubusercontent.com/30305945/121235553-dbc1a180-c849-11eb-9f7d-022d27f913f1.png)

![image](https://user-images.githubusercontent.com/30305945/121235596-e3814600-c849-11eb-8e9f-57705f3c5b3f.png)

**Comment by berdakh** [comment]
> > Just for a clarification or two. For Rendered fonts you mean fonts in the notebook output, correct? Font family (and all other editor setting should still control the input code cells).
> 
> @IanMatthewHuff That is correct. The font used in the markdown cell during editing is the one specified by `Font Family`. However, after the cell execution or `stop editing`, the font utilized are too small (my preference). I am not aware of any setting to modify fonts (family and size). Actually, it may be just my preference (or may be others too), can the the font styles in markdown be specified in separate setting than that from `Font Family`
> 
> Also, thank you for looking into other issues.

The rendered font size is too small for me as well.  I hope we could increase the size.

**Comment by mtsitzer** [comment]
Also hoping for a setting to be able to change the output/rendered size. 

Input size:
![image](https://user-images.githubusercontent.com/28517224/121940180-a4983800-cd02-11eb-9582-553d5b95eff7.png)

Output/Rendered size:
![image](https://user-images.githubusercontent.com/28517224/121940201-ad890980-cd02-11eb-848c-2d87012db57c.png)

The output/rendered size is considerably smaller than the input text and is definitely a dissatisfier for me.

**Comment by IanMatthewHuff** [comment]
I just filed an issue upstream on VS Code for the markdown text size rendering. I don't believe that there is a current setting for this.
https://github.com/microsoft/vscode/issues/126294

**Comment by mtsitzer** [comment]
Something else I noticed: the rendering of error messages when running code cells is also noticeably harder to read than it used to be.

Interactive Python:
![image](https://user-images.githubusercontent.com/28517224/122485510-f8698200-cf8b-11eb-9648-dbf99acedbc4.png)

Notebook:
![image](https://user-images.githubusercontent.com/28517224/122485532-06b79e00-cf8c-11eb-9526-0d7a571a05e7.png)

Is there currently a way to make this a bit easier on the eyes?

**Comment by IanMatthewHuff** [comment]
@mtsitzer That's a good suggestion, would you mind filing that as a new issue? The feedback here is great, but when multiple issues get into one thread it can be a bit hard to track the resolution on our side.

**Comment by greazer** [comment]
Reading through, it appears that all of the issues noted have been addressed or reference another open issue. So, closing this one. If there was something missed, please open a new issue. Thank you!
