### ISSUE TITLE
Jupyter notebook starts with wrong kernel

### ISSUE THREAD

**Issue by dataroo** [microsoft/vscode-jupyter#6048]
Issue Type: <b>Bug</b>

Steps to Reproduce:

Install Jupyter extension
Open a notebook
Select a kernel from dropdown list
Execute some cells
Close notebook
Open notebook again

Expected results: 

Now the prechosen kernel should be the one I selected before

Actual result:

The first kernel from the dropdown list is selected. 

Looking into the Output view yields this message: 'Info 2021-06-01 17:09:02: Preferred kernel for file:///<filename>.ipynb is undefined'

How can I set the preferred kernel?

Extension version: 2021.6.832593372
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (5.41GB free)|
|Process Argv|--crash-reporter-id dc9a5b02-0795-4e68-825d-bc197ce5209a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by IanMatthewHuff** [comment]
@dataroo Sorry that there is an issue happening here, it should be saving the kernel and finding it again. Could you please do something for me? Could you set the setting Jupyter->Logging->Level to 'debug' then try to repro this same scenario? After reproing please copy out all the contents of Output: Jupyter (you can paste it into a file then attach a file to a comment on this thread). Something seems fishy here, but without the full output logs it's very hard to tell.

**Comment by dataroo** [comment]
Hi @IanMatthewHuff, thanks for your help!

I have attached the Jupyter logs. (I am not sure about the logging level, there was no option in the settings for the Jupyter extension to choose the logging level so I just left it the way it was).

I hope this is helpful enough :)
[20210602_jupyter_logs.txt](https://github.com/microsoft/vscode-jupyter/files/6582557/20210602_jupyter_logs.txt)

**Comment by IanMatthewHuff** [comment]
Thanks for adding the logging here. I've pull out what I think is the relevant bit here for investigation:
```
Info 2021-06-02 08:43:36: Creating raw notebook for file:///c%3A/Users/RelitzAn/Projects/ShortCut/CNN_objective_quality/notebooks/04-tw522re-azure-tracking.ipynb
Info 2021-06-02 08:43:36: Getting preferred kernel for file:///c%3A/Users/RelitzAn/Projects/ShortCut/CNN_objective_quality/notebooks/04-tw522re-azure-tracking.ipynb
Info 2021-06-02 08:43:36: findPreferredKernel score for Python 3.8.8 64-bit is 1
Info 2021-06-02 08:43:36: findPreferredKernel score for cnn_objective_quality is 1
Info 2021-06-02 08:43:36: findPreferredKernel score for ml_workshop_env is 1
Info 2021-06-02 08:43:36: findPreferredKernel score for venv is 1
Info 2021-06-02 08:43:36: findPreferredKernel score for venv2 is 1
Info 2021-06-02 08:43:36: findPreferredKernel score for Python 3.9.1 64-bit is 1
Info 2021-06-02 08:43:36: findPreferredKernel score for Python 3.7.9 64-bit is 1
Info 2021-06-02 08:43:36: Find kernel spec, Class name = x, completed in 2ms, has a truthy return value, Arg 1: <Uri:c:\Users\RelitzAn\Projects\ShortCut\CNN_objective_quality\notebooks\04-tw522re-azure-tracking.ipynb>, Arg 2: {"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.9"},"metadata":{"interpreter":{"hash":"d113fbe31c5352b2c9092912dc745b34fe3ad3bf338faf722bcf7352127e5928"}},"kernelspec":{"name":"cnn_objective_quality","display_name":"Python 3.7.9  ('.venv': venv)"}}, Arg 3: undefined, Return Value: {"kind":"startUsingPythonInterpreter","kernelSpec":{"specFile":"C:\\Users\\RelitzAn\\AppData\\Local\\Programs\\Python\\Python38\\share\\jupyter\\kernels\\python3\\kernel.json","interpreterPath":"C:\\Users\\RelitzAn\\AppData\\Local\\Programs\\Python\\Python38\\python.exe","name":"python388jvsc74a57bd0577043878e05f58794b761fb45a75d6ed977ac4ad6c94f259dae337e94262800","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"python","display_name":"Python 3.8.8 64-bit"},"interpreter":{"sysPrefix":"C:\\Users\\RelitzAn\\AppData\\Local\\Programs\\Python\\Python38","envType":"Unknown","envName":"","envPath":"","path":"C:\\Users\\RelitzAn\\AppData\\Local\\Programs\\Python\\Python38\\python.exe","architecture":3,"sysVersion":"3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]","version":{"raw":"3.8.8","major":3,"minor":8,"patch":8,"build":[],"prerelease":["final","0"]},"companyDisplayName":"PythonCore","displayName":"Python 3.8.8 64-bit"},"id":".python388jvsc74a57bd0577043878e05f58794b761fb45a75d6ed977ac4ad6c94f259dae337e94262800.python.C:\\Users\\RelitzAn\\AppData\\Local\\Programs\\Python\\Python38\\python.exe.Python 3.8.8 64-bit"}
```

Looks to me like you are working with 'cnn_objective_quality" kernelspec, but it's instead starting with base Python 3.8.8. Is that correct?

**Comment by dataroo** [comment]
Hi Ian, 

that is correct, I want to work with the 'cnn_objective_quality" kernelspec, but the notebooks always start with base Python.

The path to the kernelspec is ' C:\ProgramData\jupyter\kernels\cnn_objective_quality'. I have attached the content of the kernel.json file to this message.


Thanks for your help!

[kernel.txt](https://github.com/microsoft/vscode-jupyter/files/6675292/kernel.txt)

**Comment by IanMatthewHuff** [comment]
@dataroo Sorry for the slow reply here. Could you test something out? We just did some work recently to clean up our kernel finding code and it's live in our insiders extension. If you install VS Code - Insiders (it can be installed safely side by side stable VS Code) then you will get our new UI and our new kernel finding code. 

Going over your log it looks similar to some issues that we fixed there.

**Comment by dataroo** [comment]
@IanMatthewHuff thanks! You are right - it works in the Visual Studio Code Insiders version!

Do you know, when the code from the insiders extension will be included in the "standard" VS Code?

Thank you!

**Comment by IanMatthewHuff** [comment]
@dataroo it's actually rolling out to some (relatively large) percent of stable users right now. Should be rollout out to all in the next couple of months.

**Comment by DavidKutu** [comment]
@dataroo, you can use the new notebook interface in stable by following these steps: https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code

Please file another issue if it reproes on the new interface.
