### ISSUE TITLE
Javascript outputs should be limited to being run on opening a notebook based on a setting (regardless of workspace trust)

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6049]
This isn't a requirement, but I think it would make me more comfortable with the idea of workspace trust. 

Any notebook that a user opens won't allow any javascript in it until the notebook has had at least one cell run in it. We'd have to bring back the concept of a trusted notebook, but the user would never see the trust icon or the trust message. Instead trust would be decided at the workspace level, but an extra level of security would make sure to not run javascript until the user explicitly executes a cell.

We could add a setting to disable this behavior.

**Comment by SiddhanthUnnithan** [comment]
@rchiodo I'm looking at Notebook behaviour in trusted workspaces right now and want to make sure I understand this issue.

Are you saying that regardless of workspace trust we won't allow any JS output until the user has explicitly ran a cell? I'm curious what it means to "allow" any JS output. How do we detect JS output from regular output?

Also what do you mean when you say that trust will be decided at the workspace level? I'm assuming that the Notebook being in a trusted workspace doesn't influence whether we will allow the JS output.

**Comment by rchiodo** [comment]
> Are you saying that regardless of workspace trust we won't allow any JS output until the user has explicitly ran a cell?

Yes that's what I'm saying.

> I'm curious what it means to "allow" any JS output. How do we detect JS output from regular output?

JS output is in <script> tags inside html output.

All other output is either custom mimetype (not allowed as it runs JS), or images which are allowed.

> Also what do you mean when you say that trust will be decided at the workspace level? I'm assuming that the Notebook being in a trusted workspace doesn't influence whether we will allow the JS output.

Trust will be decided on per workspace, but I think (and that's what this item is about) that isn't good enough. I wouldn't expect code to run just by opening a file even if I trusted it.
