### ISSUE TITLE
Tensorflow - training output is not rendered properly

### ISSUE THREAD

**Issue by kuelumbus** [microsoft/vscode-jupyter#6050]
## Environment data
Version: 1.57.0-insider
Commit: 1e446dfadf588ec28b3fdba7ac083bfa1d45df3c
Date: 2021-06-01T05:13:45.931Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-73-generic snap

-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.892431424
-   Python Extension version (available under the Extensions sidebar): v2021.5.842923320
-   OS (Windows | Mac | Linux distro) and version: Linux
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...):poetry
-   Jupyter server running: Remote 

## Actual behaviour

![tf](https://user-images.githubusercontent.com/44866753/120358180-39973c00-c2d4-11eb-83a5-f919b3c8f5c3.gif)

## Steps to reproduce:
```python
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer='adam',
              loss=loss_fn,tf
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=10)
```

**Comment by IanMatthewHuff** [comment]
@kuelumbus Thanks for the report and the clear repro. I see slightly different behavior on insiders, but the output is also garbled and incorrect. Looks like the stream output is not getting handled correctly. We do have one open issue on output ordering that is incoming today, so I'll take a look tomorrow to see if that resolves this. I also looked at our old UI (using the interactive window) and that output looks correct so this is an error just with the new notebook UI.
![image](https://user-images.githubusercontent.com/812783/120567646-1d27fc00-c3c7-11eb-8c9e-d352d73b0c65.png)

**Comment by greazer** [comment]
Move to July if it still repros

**Comment by IanMatthewHuff** [comment]
@kuelumbus We had a bug dealing with output ordering that hit us for a few days. I tried with the build today and it looks good, just comment back here if you are still seeing it look off.

![image](https://user-images.githubusercontent.com/812783/120716959-9ed96180-c47b-11eb-850f-fe4fe23a188e.png)
