### ISSUE TITLE
Widgets no longer works as sys.prefix is empty

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#6052]
non-cdn approach always fails

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode-python/issues/16355

**Comment by DonJayamanne** [comment]
I believe the fix is super simple

**Comment by IanMatthewHuff** [comment]
Validated. Not 100% sure on the validation needed here, but I deleted my CDN download and then ran a few complex widgets, looked good.
