### ISSUE TITLE
`element` variable not defined when rendering IPyWidgets

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#6054]
* Vega, vpython, vegalite, ipyaladin, etc
	* Requires `element` variable
	* [x] Requires `nbextension/....` modules (tracked & possibly fixed here https://github.com/microsoft/vscode-jupyter/issues/10434)

**Solutions**
	* [ ] We must have our custom `application/javascript` renderer which adds the element variable in context
	* [ ] Register `nbextension/....` modules when kernel starts & loads (tracked & possibly fixed here https://github.com/microsoft/vscode-jupyter/issues/10434)

There could be plenty of widgets that rely on these, hence don't work.

**Comment by rchiodo** [comment]
Are you going to load widgets from the python nb_extensions folder?

**Comment by DonJayamanne** [comment]
we already do that today, the proposal is to list more files from there

**Comment by rchiodo** [comment]
nbextensions folder has to be added to require.js so that if a widget depends upon other files, they can be found.

**Comment by dentistfrankchen** [comment]
I believe now a lot of error behavior might be caused by the internal mechanism vscode uses to handle javascript.

**Comment by DonJayamanne** [comment]
This should now be fixed in the latest release.
