### ISSUE TITLE
Unable to open 'test.ipynb': i.NotebookCellMetadata is not a constructor.

### ISSUE THREAD

**Issue by acook-geo** [microsoft/vscode-jupyter#6062]
## Environment data

-   VS Code version: 1.57.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.892431424
-   Python Extension version (available under the Extensions sidebar): 2021.6.864643163-dev
-   OS (Windows | Mac | Linux distro) and version: Win10 20H2
-   Python and/or Anaconda version: python 3.8.5; conda 4.10.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Open an ipynb file

## Actual behaviour

Recieve error msg: `Unable to open 'test.ipynb': i.NotebookCellMetadata is not a constructor.`

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open ipynb file...

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by Qiuzhuang** [comment]
updating to this version and run into this issue either

**Comment by Zer0112** [comment]
same issue for me on every ipynb (vscode insider 1.57,jupyer v2021.6.892431424, python v2021.6.894226714-dev)

**Comment by rohan-paul** [comment]
No .ipynb file opening in Ubuntu 20.04 either for VSCode-Insider.


```
Version: 1.57.0-insider
Commit: 217f1a2f60a197807de78af362ecb832100fda96
Date: 2021-06-02T05:13:37.201Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-53-generic

```

Here's the full error from Toggling Developer Tool.

```
workbench.desktop.main.js:sourcemap:741 Unable to open '2_June_Local_Full_Dataset_Final_Run.ipynb': i.NotebookCellMetadata is not a constructor.
onDidChangeNotification @ workbench.desktop.main.js:sourcemap:741
workbench.desktop.main.js:sourcemap:627   ERR TypeError: i.NotebookCellMetadata is not a constructor
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.892431424/out/client/extension.js:16
    at S (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.892431424/out/client/extension.js:16)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.892431424/out/client/extension.js:16
    at Array.map (<anonymous>)
    at Object.t.notebookModelToVSCNotebookData (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.892431424/out/client/extension.js:16)
    at l.getNotebookData (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.892431424/out/client/extension.js:16)
    at m.openNotebook (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.892431424/out/client/extension.js:90)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at u.$openNotebook (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84)
```

**Comment by Zer0112** [comment]
jupyter v2021.6.898847129 seems to fix the issue for me

**Comment by acook-geo** [comment]
yes, just got the update

Thanks
