### ISSUE TITLE
Markdown boxes cause "Invariant Violation: Minified React error #137"

### ISSUE THREAD

**Issue by Quentin-Ludet** [microsoft/vscode-jupyter#6064]
Issue Type: <b>Bug</b>

When placing the following line in a markdown cell, the editor shows a "Invariant Violation: Minified React error #137" and prevents the cell from being edited:

```
test </br> </br>
```

[bugged_markdown.zip](https://github.com/microsoft/vscode-jupyter/files/6583901/bugged_markdown.zip)

After changing the box to markdown, the file is essentially bricked because the editor will not allow you to change it back to code.

![image](https://user-images.githubusercontent.com/42892221/120467969-ffe03700-c3a0-11eb-94c0-84c45694aaf8.png)

Extension version: 2021.6.832593372
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.65GB free)|
|Process Argv|--crash-reporter-id 499dbb84-ee8c-4dbf-9f10-aabc22943e2a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue. You might try switching to the [insiders ](https://code.visualstudio.com/insiders/) build of VS code. This is using a different way to render markdown and doesn't have this bug.

**Comment by greazer** [comment]
This will be fixed once we turn on Native VS Code notebook support.
