### ISSUE TITLE
Should not start in untrusted `Attempting to start a server because of preload conditions`

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#6077]

**Comment by IanMatthewHuff** [comment]
Validated. Turned on preload in a new workspace. Tried with both ZMQ on and ZMQ off. No preload when opening a notebook:
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/294d79c3-9cc4-4b14-afb6-29a88dcea128)
