### ISSUE TITLE
Interactive Window variable window doesn't work right when debugging a cell.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#6081]
- Open a python file with cell markers 
- Run a couple with some variables.
- Open the IW variables pane
- Debug into a cell with variables that have been initialized
- Hover over one of the variables.

**Actual**
The variables pane in the IW will change to reflect just the hovered variable.

**Expected**
The variables pane in the IW either doesn't change at all. It should show the known variables in the cell OR (easier solution) restore the code that pointed users to look at the VS Code debugger variables window instead.

This repro's in latest Insiders as well as Stable 1.56.2, indicating this started happening at least a couple releases ago. It is a regression.

**Comment by joyceerhl** [comment]
I think the right fix here is to disable the variable explorer when debugging. This is what we used to do.

**Comment by IanMatthewHuff** [comment]
Validated. IW looks fine (I'm hovering in this case):
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/a5c1c256-3b6c-4f24-8573-08f8a0f96004)
Nice work @vandyliu
