### ISSUE TITLE
Active interpreter is being cached too long

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6087]
Set active interpreter to something that requires ipykernel
Reload VS code
Open py file with cells
Run cell
Ipykernel install should come up. Cancel
Set active interpreter to something that doesn't require ipykernel
Run cell

Expected:
Cell run

Actual:
Ipykernel install is coming up.

Seems like the cache for active interpreter is not being cleared.

**Comment by DonJayamanne** [comment]
This works for me on a Mac.

**Comment by rchiodo** [comment]
Not sure if this is working or not. Needs to be verified.

**Comment by roblourens** [comment]
Seems very flaky. I have two venv's, "nokernel" and "yeskernel", only "yeskernel" has ipykernel installed

Sometimes I see
- Select "nokernel"
- Run a cell
- Ipykernel install prompt comes up, pick "Select kernel"
- Pick "yeskernel"
- The kernel does not actually change, the picker still says "nokernel"
- Try to run a cell again
- Nothing happens

Also saw it switch to yeskernel, but "run cell" does nothing

**Comment by DonJayamanne** [comment]
@rchiodo is this still an issue?
