### ISSUE TITLE
Copy paste not working between cell and outside

### ISSUE THREAD

**Issue by jounghoolee** [microsoft/vscode-jupyter#6093]
## Environment data

-   VS Code version: vscode-insider
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.898847129
-   Python Extension version (available under the Extensions sidebar): 2021.5.842923320
-   OS (Windows | Mac | Linux distro) and version: Linux ubuntu 18.04
-   Python and/or Anaconda version: 3.6.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running:  Local, but with ssh remote

## Expected behaviour

Copy and paste should work between jupyter notebook and outside world.

## Actual behaviour

Copy and paste only works inside jupyter notebook. I cannot paste anything copied outside, include search bar. I wondors it is only my issue.

<p>

```
XXX
```

</p>
</details>

**Comment by claudiaregio** [comment]
Hi @jounghoolee, could you please provide a bit more information on the issue you are running into? Maybe a screen recording would be helpful here, or a few more detailed steps on what you are doing that isn't working as expected for you? 

I tried just copying text from a cell and pasting into a browser searched and it worked fine but I may not be fully understanding the issue here.

**Comment by jounghoolee** [comment]
Really thanks for quick response! I thought it is common problem of vscode-insider for linux + newest jupyter notebook + ssh remote extension, because I just upgraded today....!
If copy paste works fine to/from jupyter cell and ctrl+f console in your case, I will update the issue as soon as I figure out the reason..!

**Comment by rchiodo** [comment]
@jounghoolee can you provide some more information on what you're trying to copy? A screenshot/gif would really help.

Thanks.

**Comment by jounghoolee** [comment]
I am so sorry to say this, but I fail to reproduce an issue, because today Jupyter notebook extension fail to excute like below.. I guess it is after the extension update.. 
![스크린샷, 2021-06-04 17-48-32](https://user-images.githubusercontent.com/7993455/120774499-4e3a3500-c55d-11eb-8ad7-776156803c43.png)

This is current state of my extension..
![스크린샷, 2021-06-04 17-48-51](https://user-images.githubusercontent.com/7993455/120774527-54c8ac80-c55d-11eb-98d4-2ddea1aa5dba.png)

I give up, and planning go back to stable version of vscode.. So sorry that I could not provide further useful information.

**Comment by claudiaregio** [comment]
@jounghoolee Have you updated to the latest version of VS Code and Jupyter? We had a breaking change yesterday and I am unable to reproduce the error you are seeing with the latest version of all.

**Comment by greazer** [comment]
@jounghoolee Please reopen if you are still having similar issues you'd like us to investigate.
