### ISSUE TITLE
Bokeh mimetype isn't working for me in native notebooks

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#6097]
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/7f53a7ec-7456-46bc-9474-7d3d55e6d451)

This looks to be a recent regression, this output is in my usual test file. Possibly when the UIntArray data change came in?

**Comment by DonJayamanne** [comment]
FYI - We never supported vnd.bokehjs_load.v0+json.

**Comment by IanMatthewHuff** [comment]
Hmmm, it's not on the list, but I'm sure that I've seen this working with native. I'll look at stable + native.

**Comment by IanMatthewHuff** [comment]
Validated. Looks good now that it defaults to javascript.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/9c981ef6-7e14-4aaa-b80b-9891879539c5)
