### ISSUE TITLE
Execution information not showing up after cells are run

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#6099]
Timing + green check missing

**Comment by DonJayamanne** [comment]
> Timing + green check missing

Is the cell status bar hidden?

**Comment by IanMatthewHuff** [comment]
@DonJayamanne a new change from last night seems to have defaulted it to hidden for me.
https://github.com/microsoft/vscode/issues/125403

**Comment by DonJayamanne** [comment]
Then this isn't a breaking change, its merely a UI change.

**Comment by IanMatthewHuff** [comment]
@DonJayamanne Yup, I didn't say that it was breaking. However the default doesn't seem right to me. Given the PR from Rob it seems like I've been opted into colab settings (where hidden is default) without explicitly selecting that.

**Comment by IanMatthewHuff** [comment]
@DonJayamanne did you see this change as well? Wondering if it's settings specific?

**Comment by DonJayamanne** [comment]
I've always turn this off (around 2-3 weeks ago), 
```json
"notebook.showCellStatusBar": false,
```

**Comment by IanMatthewHuff** [comment]
@DonJayamanne Yeah that's the setting that changed last night, it's not a boolean anymore. https://github.com/microsoft/vscode/commit/99665d0b4ac734861475eedeecb391bca4e4750d

**Comment by greazer** [comment]
timing and green check is visible for me with latest insiders and jupyter bits.
