### ISSUE TITLE
Extension activation fails on Linux

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode-jupyter#6105]
## Environment data

-   VS Code version: 1.56.2
-   Jupyter Extension version: 2021.6.832593372
-   Python Extension version (available under the Extensions sidebar): 2021.5.842923320
-   OS (Windows | Mac | Linux distro) and version: linux
-   Python and/or Anaconda version: 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: either

## Expected behaviour

Clicking on a Python file should open the file in VSCode

## Actual behaviour

File fails to open; instead I get an "Extension activation failed" message related to the Jupyter extension:

![image](https://user-images.githubusercontent.com/81476/120681805-60cf4400-c461-11eb-972e-1e64579acdd7.png)

## Logs

![image](https://user-images.githubusercontent.com/81476/120682081-a8ee6680-c461-11eb-9a23-5804f97f5509.png)

**Comment by fonnesbeck** [comment]
I just replicated this issue on a Mac as well, so not restricted to Linux.

**Comment by joyceerhl** [comment]
What's the value of the `workbench.editorAssociations` setting in your settings.json file?

If you set it to the following, this issue should go away:

```
"workbench.editorAssociations": [
   {
        "viewType": "jupyter-notebook",
        "filenamePattern": "*.ipynb"
   }
]
```

**Comment by fonnesbeck** [comment]
Yeah, this appears to be associated with contamination of my settings with insider build settings. Removing that fixed the issue.
