### ISSUE TITLE
Go to definition broken in insiders for Python notebooks

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#6108]

**Comment by joyceerhl** [comment]
To validate, ensure you are on the latest Python extension (will be published tonight) in VS Code Insiders, and ensure go to def works in a Jupyter notebook with Python code. Remember to select a Python interpreter first so that the language server works.

**Comment by IanMatthewHuff** [comment]
Validated.

Tested Goto within file:
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/18d7f9d6-6c63-43b0-9f4e-13404929503b)

Tested Goto jumping to library code:
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/a8c3b881-3ca5-4fa7-9524-9ba173aecf07)
