### ISSUE TITLE
Exporting jupyter notebook to python script does not work on macOS

### ISSUE THREAD

**Issue by woodwm** [microsoft/vscode-jupyter#611]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. click the "Export as" button when a jupyter notebook is opened, and select "Python Script"

## Actual behavior

an empty python script

## Expected behavior

a converted python script

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.8.108011
-   **VS Code version:** 1.49.0
-   **Setting python.jediEnabled:** false
-   **Setting python.languageServer:** Microsoft
-   **Python and/or Anaconda version:** 3.8.5
-   **OS:** Mac
-   **Virtual environment:** conda

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by kostastsiolis** [comment]
I can confirm that nbconvert 5.6.1 works for me as well!!
