### ISSUE TITLE
Remove work around for VS Codes Notebook Start Page

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#6113]
* Ensure `createNewNotebook` returns a NotebookDocument 
	* This way we don't need to rely on `window.activeNotbeookEditor`
*

**Comment by DonJayamanne** [comment]
Not sure why this was closed, this is required. 
Else at just have a hacky solution in our code going forward.

**Comment by joyceerhl** [comment]
Sorry, I suggested we close it because VS Code has disabled their start page.
