### ISSUE TITLE
VS Code can't open .ipynb files

### ISSUE THREAD

**Issue by HenriqueAJNB** [microsoft/vscode-jupyter#612]
## Environment data

-   VS Code version: 1.49.0
-   Extension version (available under the Extensions sidebar): v2020.8.108011
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda python 3.8.3
-   Type of virtual environment used: using conda environment
-   Value of the `python.languageServer` setting: "Pylance"
-   ipython version: 7.16.1
-   jedi version: 0.17.1
-   ipykernel version: 5.3.2

## Expected behaviour

VS Code could open `.ipynb` normally. It's opening normally in Jupiter Notebook

## Actual behaviour

VS Code keeps loading all the time and won't open the `.ipynb` file.

## Steps to reproduce:

1. Open VS Code
2. Open any `.ipynb` file.

![gif_vscode](https://user-images.githubusercontent.com/54143210/92985189-bce2da00-f486-11ea-8b3c-fcc1d2ec3a34.gif)

**Comment by biplavc** [comment]
Getting the following message 

`Unable to open 'scratch.ipynb (Working Tree)': Using the Jupyter notebook editor requires the stable version of VS code and the CustomEditor experiment to be enabled..****`

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-54-generic snap

Ubuntu 18.04

The above-mentioned approaches didn't work for me.

**Comment by teddybee** [comment]
Same issue here with 1.51.1
Windows 10 2020H2

**Comment by KiteRunner2** [comment]
Same issue, was working fine until I updated to 1.51.1...

**Comment by QPeiran** [comment]
https://github.com/microsoft/vscode-jupyter/issues/486
Update both vscode and python extention worked for me

**Comment by biplavc** [comment]
> #486
> Update both vscode and python extention worked for me

@QPeiran  can you provide your version details ?

**Comment by QPeiran** [comment]
> > #486
> > Update both vscode and python extention worked for me
> 
> @QPeiran can you provide your version details ?

VSCode version: 1.51.0
Python Extention:  v2020.10.332292344

**Comment by biplavc** [comment]
> > > #486
> > > Update both vscode and python extention worked for me
> > 
> > 
> > @QPeiran can you provide your version details ?
> 
> VSCode version: 1.51.0
> Python Extention: v2020.10.332292344

Issue persists in my case, windows OS is giving a different error message
```
StdErr from ShellExec, Did not find path entry D:\Anaconda\bin
Did not find path entry D:\Anaconda\bin
 for D:/Anaconda/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user_name\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py c:/Users/user_name/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/printEnvVariables.py
```

Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Both anaconda and vs code are added to system variables.

**Comment by QPeiran** [comment]
> > > > #486
> > > > Update both vscode and python extention worked for me
> > > 
> > > 
> > > @QPeiran can you provide your version details ?
> > 
> > 
> > VSCode version: 1.51.0
> > Python Extention: v2020.10.332292344
> 
> Issue persists in my case, windows OS is giving a different error message
> 
> ```
> StdErr from ShellExec, Did not find path entry D:\Anaconda\bin
> Did not find path entry D:\Anaconda\bin
>  for D:/Anaconda/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user_name\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py c:/Users/user_name/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/printEnvVariables.py
> ```
> 
> Version: 1.51.1 (system setup)
> Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
> Date: 2020-11-10T23:34:32.027Z
> Electron: 9.3.3
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Windows_NT x64 10.0.19041
> 
> Both anaconda and vs code are added to system variables.

@biplavc I didn't use ananconda -- pipenv instead
