### ISSUE TITLE
No execution time

### ISSUE THREAD

**Issue by grudloff** [microsoft/vscode-jupyter#6125]
## Environment data

-   VS Code version: 1.57.0
-   Jupyter Extension version : v2021.6.902307158
-   Python Extension version : v2021.6.897246044-dev
-   OS  and version: Windows_NT x64 10.0.19041
-   Python and Anaconda version: 3.8.10 and 4.10.1
-   Type of virtual environment used : conda
-   Jupyter server running: Local

## Expected behaviour

Execution time shown during execution and after execution at the end of run cells.

## Actual behaviour

No execution time shown during execution or after execution at the end of run cells.

**Comment by joyceerhl** [comment]
This may be related to https://github.com/microsoft/vscode/issues/125403

If you go into your settings.json file and add the following setting, does that fix things?

>     "notebook.showCellStatusBar": "visible",

**Comment by grudloff** [comment]
Thanks, @joyceerhl! That was just it.
