### ISSUE TITLE
ipynb files don't open in Notebook Editor on double-click

### ISSUE THREAD

**Issue by bazzilic** [microsoft/vscode-jupyter#6128]
## Environment data

-   VS Code version: **1.56.2**
-   Jupyter Extension version (available under the Extensions sidebar): **v2021.6.832593372**
-   Python Extension version (available under the Extensions sidebar): **v2021.5.842923320**
-   OS and version: **Windows 10 x64 Version 21H1 (OS Build 19043.985)**
-   Python and/or Anaconda version: **Python 3.9.5 x64**
-   Type of virtual environment used: **N/A**
-   Jupyter server running: **Local**

## Expected behaviour

When double-clicking an *.ipynb file, it should open in the Notebook Editor.

## Actual behaviour

It opens as JSON:

![not-working](https://user-images.githubusercontent.com/1805832/120754990-f8a35f80-c53f-11eb-8255-ff95b9a45449.gif)

Also, if I use _Jupyter: Open in Notebook Editor_ command in command palette, nothing happens. However, if I choose _View: Reopen Editor With..._ and choose Notebook Editor, it will work. I tried the `"jupyter.useNotebookEditor": true` config option but it did nothing and also apparently it is obsolete:

![image](https://user-images.githubusercontent.com/1805832/120760753-11634380-c547-11eb-89d6-e97c566d9fba.png)

If I open a folder in VS Code and open a file from there, it opens fine:

![working-2](https://user-images.githubusercontent.com/1805832/120759529-acf3b480-c545-11eb-86c7-314804d721e8.gif)

If I drag and drop the file in an open VS Code, it opens fine too:

![working-1](https://user-images.githubusercontent.com/1805832/120759574-b8df7680-c545-11eb-97b4-e2743eadb50b.gif)

## Steps to reproduce:

1. Take this ipynb file: [lagrangian.zip](https://github.com/microsoft/vscode-jupyter/files/6596385/lagrangian.zip)
2. Right click the ipynb file and select _Open With... > VS Code_
3. Observe it opening as a json file instead of in the Notebook Editor

**Comment by AlexJPF** [comment]
Same thing is happening to me except I can't open it either of the two ways you can.

**Comment by DonJayamanne** [comment]
@bazzilic @AlexJPF We're updating the Notebook UI.
Please could you install VS Code insiders and let us know if this has been resolved.

**Comment by bazzilic** [comment]
It seems to work now with the latest updates (Jupyter extension v2021.6.999662501)
