### ISSUE TITLE
Jupyter layout should hide the cell toolbar since neither Jupyter Lab nor Jupyter Classic has one.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#6129]
See the title.

**Comment by joyceerhl** [comment]
I believe we plan to display Run By Line and other run actions in the cell toolbar.

**Comment by claudiaregio** [comment]
Correct, while Jupyter doesn't have the cell toolbar, the webview implementation our users have today and it is where we surface other actions Jupyter does not have support for. Run by line, Gather, Smart Select, etc.

**Comment by DonJayamanne** [comment]
Closing for now, this is an established UI in webview.
Users can hide this today in Native Notebooks if they don't want it.
