### ISSUE TITLE
Typing errors of Jupyter notebook still show after closing notebook

### ISSUE THREAD

**Issue by lijunkang12** [microsoft/vscode-jupyter#6130]
## Environment data

-   Language Server version: 2021.6.0
-   OS and version: macOS 11.4
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.5

## Expected behaviour

Typing errors of a Jupyter notebook should disappear when the notebook is closed.

## Actual behaviour

Error messages still persist.

## Screenshot
- Before closing the notebook
![Screenshot 2021-06-04 at 12 26 48](https://user-images.githubusercontent.com/17224946/120788025-47e19400-c530-11eb-9969-f2c7a57ede4b.png)

- After closing the notebook
![Screenshot 2021-06-04 at 12 28 32](https://user-images.githubusercontent.com/17224946/120788120-63e53580-c530-11eb-93bb-9410140dfe94.png)

**Comment by DonJayamanne** [comment]
@lijunkang12 Please could you install the latest versio of VS Code & the jupyter + Python exteniosn & confirm this is still an issue.

**Comment by lijunkang12** [comment]
@DonJayamanne I can confirm that this problem persists. Version info follows:
VS Code: 1.58.0
Python: 2021.6.0
Jupyter: 2021.8.0

**Comment by DonJayamanne** [comment]
Please could you update Python to the latest dev version of the Python extension.
* Go into your command palette, and select `Python: Switch to Insiders Daily Channel`
* A new version will get installed & u'll be prompted to reload vscode

I believe this has been resolved in our development version of the Python extenssion.

**Comment by lijunkang12** [comment]
Cool, this indeed has been resolved in the insiders daily build. Thanks.
