### ISSUE TITLE
VSCODE Jupyter notebook interface is different.

### ISSUE THREAD

**Issue by redelectricyw** [microsoft/vscode-jupyter#6131]
## Environment data

-   VS Code version: 1.56.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.832593372
-   Python Extension version (available under the Extensions sidebar): v2021.5.842923320
-   OS (Windows | Mac | Linux distro) and version: Windows 10 x64 
-   Python and/or Anaconda version: Python 3.9.5 x64
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | Local

## Expected behaviour

XXX

## Actual behaviour

I am a beginner in python. I was trying to install Jupyter Notebook in VScode, but my interface was different from others.
[](url)

![other](https://user-images.githubusercontent.com/82155052/120829773-bf4b0e00-c598-11eb-95bd-5861771f5787.png)

but, my interface is

![my error](https://user-images.githubusercontent.com/82155052/120829873-dc7fdc80-c598-11eb-9f7f-c8b8309068ba.png)

My screen is weird, right? How can I solve this?

</details>

**Comment by claudiaregio** [comment]
Hi @redelectricyw! You have been placed into the Native Notebooks experiment! We are working on upgrading our notebook experience which is why you are seeing a different version :) 

Give it a try and let us know your thoughts!

**Comment by redelectricyw** [comment]
Ah, so this is not the wrong screen. If so, is there any way to change it to the above screen?

**Comment by redelectricyw** [comment]
> Hi @redelectricyw! You have been placed into the Native Notebooks experiment! We are working on upgrading our notebook experience which is why you are seeing a different version :)
> 
> Give it a try and let us know your thoughts!

Ah, so this is not the wrong screen. If so, is there any way to change it to the above screen?

**Comment by claudiaregio** [comment]
Could you help me understand why you'd like to return to the screen above?

**Comment by redelectricyw** [comment]
> Could you help me understand why you'd like to return to the screen above?

Dear sir.

I want it to look like this screen.
![Uploading 120829773-bf4b0e00-c598-11eb-95bd-5861771f5787.png…]()

**Comment by claudiaregio** [comment]
You spelled miss wrong ;) 

We have a new update that will be coming early next week that will look much more similar to the version you pasted above. The view you have requested will eventually be retired and will no longer exist. We would love to try to get customers used to the new notebook. Would you be willing to wait to see how the updated view works for you?

**Comment by redelectricyw** [comment]
> You spelled miss wrong ;)
> 
> We have a new update that will be coming early next week that will look much more similar to the version you pasted above. The view you have requested will eventually be retired and will no longer exist. We would love to try to get customers used to the new notebook. Would you be willing to wait to see how the updated view works for you?

Please understand that English is often misspelled because you live in a non-English speaking country. :)

As you said, the latest version of VSCODE is much cleaner and better. In particular, I found that the Table of Contents (TOC) support is also available. I love it! Thank you Sir.

**Comment by DonJayamanne** [comment]
Thanks for getting back to us. closing this issue as @redelectricyw seems to be happy with the new UI.
Please feel free to re-open or create a new issue if that's not the case.
