### ISSUE TITLE
Jupyter Interactive Window rendered markdown is misaligned

### ISSUE THREAD

**Issue by hkennyv** [microsoft/vscode-jupyter#6134]
## Environment data

-   VS Code version: 1.57.0-insider (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.905800020
-   Python Extension version (available under the Extensions sidebar): v2021.5.842923320
-   OS (Windows | Mac | Linux distro) and version: Mac OS 11.4 (20F71)
-   Python and/or Anaconda version: Python 3.9.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Jupyter server running: **Local** | Remote | N/A

```
Version: 1.57.0-insider (Universal)
Commit: fe1eafc80c07608de52a2f9c99fee103dea77f5e
Date: 2021-06-04T12:19:25.391Z (6 hrs ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin arm64 20.5.0
```

## Expected behaviour

Given the following markdown, we expect it to render as follows (github markdown flavor):

```markdown
# H1

Some text...

* list item 1
* list item 2
* list item 3

## H2
### H3
```

---
# H1

Some text...

* list item 1
* list item 2
* list item 3

### H3
---

## Actual behaviour

In the Jupyter interactive window, the markdown renders incorrectly (or misaligned). If you run the cell in the code snippet below in an interactive window, it will render as shown in the image below. The `H2` and `H3` elements are misaligned with what seems to be due to the list.

```python
# %% [markdown]
# # H1
# 
# Some text...
# 
# * list item 1
# * list item 2
# * list item 3
# 
# ## H2
# ### H3
```

![image](https://user-images.githubusercontent.com/29909203/120853220-27b1d500-c530-11eb-9260-68072fa2a285.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Run the snippet above in a Jupyter interactive window
2. The rendered markdown will have the `H2` and `H3` misaligned.

**note:** a temporary solution is to simply add another empty line after the end of the list. the interactive window will render it properly after doing this. however, it still seems like an issue that is worth being fixed. sorry if i'm being pedantic!

Also, I couldn't find the rendered HTML in the devtools elements to verify which part is being rendered incorrectly, it seems to just be an iframe (i could be wrong)?

## Logs

N/A

**Comment by claudiaregio** [comment]
@hkennyv I am able to reproduce this behavior, will review at our next triage meeting

**Comment by joyceerhl** [comment]
This is resolved in the [preview interactive window](https://code.visualstudio.com/updates/v1_58#_jupyter-interactive-window), which features improved VS Code workbench integration and is currently the default in VS Code Insiders. Please let us know if it works for you and give us any feedback you have about the new experience 😊 If you find any bugs or have concerns, please file a new issue at https://github.com/microsoft/vscode-jupyter/issues so we can fix it. Thank you! 

![image](https://user-images.githubusercontent.com/30305945/126430948-c3391c2d-9c73-4eb8-aa72-c3c9e3637a61.png)
