### ISSUE TITLE
Not Showing Documentation

### ISSUE THREAD

**Issue by bidyut18** [microsoft/vscode-jupyter#6144]
Issue Type: <b>Bug</b>

I have been using Jupyter extension with It's server but the jupyter block does not show the documentation of the object under the mousehover.

Extension version: 2021.6.832593372
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

**Comment by DavidKutu** [comment]
Thanks for the issue @bidyut18. 
- What language server do you have selected in settings? The setting is `python.languageServer`
- Could you share the module that is not showing documentation? (eg is it `pandas.DataFrame`, `numpy.random`?)

**Comment by bidyut18** [comment]
I changed my Language server to Pylance and now it's working better than the default Language server. The auto-completion is also improved a lot . I guess the  problem was in langauge  sever.
