### ISSUE TITLE
Bad long jupyter server url display

### ISSUE THREAD

**Issue by yopparai** [microsoft/vscode-jupyter#6145]
Issue Type: <b>Bug</b>

I have long jupyter server url (373 symbols) and it displays bad.
- In jupyter mode
![image](https://user-images.githubusercontent.com/55656303/120908009-1e7b5200-c66f-11eb-8889-d860933e0223.png)
- In interactive mode
![image](https://user-images.githubusercontent.com/55656303/120915628-691bbf00-c6ad-11eb-9adb-053f6bbf7e62.png)

Steps to reproduce:
1. Create `tmp.ipynb` (for jupyter mode) or `tmp.py` (for interactive mode) file inside any folder
2. Open command palette (`Ctrl+Shift+P`)
3. Select `Jupyter: Specify local or remote Jupyter server for connections` and select `Existing`
4. Write some long (> 300 symbols) existing jupyter server url
    1. For receiving long url you can generate config `jupyter notebook --generate-config`
    2. Write `c.NotebookApp.base_url = '/<some-long-url>/'` inside `jupyter_notebook_config.py`
    3. And run jupyter notebook server locally using `jupyter notebook` command
5. Run some code

Extension version: 2021.6.832593372
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (7.35GB free)|
|Process Argv|--crash-reporter-id 9129c348-3933-4ed3-87e3-6fdcee8bf225|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics (12 x 2994)|
|Memory (System)|11.99GB (10.57GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
pythonvsuse255:30311220
vscgsv2ct:30307505
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by DavidKutu** [comment]
Thanks for the issue, we'll probably crop it and show it on hover.

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed with new native support for editing notebooks starting with v1.59 of VS Code. If this issue continues to occur in the latest build of VS Code, please reopen or enter a new issue.
