### ISSUE TITLE
Lose of focus while switching windows using Alt+Tab

### ISSUE THREAD

**Issue by bajajvatsal** [microsoft/vscode-jupyter#6148]
## Environment data

-   VS Code version: 1.56.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.832593372
-   Python Extension version (available under the Extensions sidebar): v2021.5.842923320
-   OS and version: Windows Version 10.0.19043
-   Python version: 3.9.1
-   Type of virtual environment used : venv
-   Jupyter server running: Local

## Expected behaviour

The cursor and the notebook focus should remain same while switching windows back and forth.

## Actual behaviour

The focus changes to the file navigation bar at the top on VS Code window, and it looks like only alt key is pressed and focus remains at the navigation bar instead of the notebook.

**Comment by SailorMax** [comment]
possible same reason in problem described here: https://github.com/microsoft/vscode/issues/123081

**Comment by DavidKutu** [comment]
Thanks for the issue @SailorMax. Does this happen consistently to you? I'm trying it and normally the focus is preserved on the right cell, but if I do it enough times the issue does repro.

In either case, this is an issue with VS Code.

If you'd like a solution now, VS Code insiders defaults to our new native notebooks. The issue doesn't happen there.

**Comment by DavidKutu** [comment]
@SailorMax, [this issue](https://github.com/microsoft/vscode/issues/124788) in VS Code includes this. Please follow that.
