### ISSUE TITLE
Add option to Find and Replace with "Ctrl+F"

### ISSUE THREAD

**Issue by fschaffner** [microsoft/vscode-jupyter#6161]
I would like to suggest adding an option to quickly Find & Replace code in Jupyter Notebooks when using the shortcut Ctrl+F, just like the behavior when using Ctrl+F in Markdown (.md) files in VSCode and also in RStudio.

**Comment by DavidKutu** [comment]
Thanks for the suggestion @fschaffner. This will be supported on our new Native Notebooks. You can try it right now with [VS Code Insiders](https://code.visualstudio.com/insiders/).

Let me know if that works for you.

**Comment by DavidKutu** [comment]
Hi @fschaffner, it looks like using insiders works for you. I'm closing this for now, but you can reopen it otherwise.
