### ISSUE TITLE
Can't out images in python notebooks (error loading preloads)

### ISSUE THREAD

**Issue by aparente-nurix** [microsoft/vscode-jupyter#6167]
We have written the needed data into y
Issue Type: <b>Bug</b>

Getting this error when trying to plot graphs in matplotlib/pandas. 

Error loading preloads:
ue.renderCell is not a function

Extension version: 2021.6.904006657-dev
VS Code version: Code - Insiders 1.57.0-insider (a62df5d6c53e844bfdc50694f943c3f34b6ff50e, 2021-06-03T17:38:02.890Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 3.10.0-1160.24.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (2.08GB free)|
|Process Argv|--crash-reporter-id 3ab5d30a-e57d-4c95-ad43-4ab531c2c975|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: aparente-t7820|
|OS|Linux x64 3.10.0-1160.24.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz (48 x 1200)|
|Memory (System)|125.35GB (116.16GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonvspyt551cf:30291413
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30286553
pythonvsuse255:30303025
vscgsv2:30305091
vscorehov:30301224
vscod805cf:30301675
vscextlangct:30310089
vsccppwtct:30312693

```

</details>

our clipboard because it was too large to send. Please paste.

**Comment by DonJayamanne** [comment]
Looks like you are using the wrong version of VS Code Insiders and the Jupyter extension.
Please install the latest VS Code Insiders & the corresponding Jupyter extension from the marketplace.
