### ISSUE TITLE
IPython HTML links should not use WebView external URL

### ISSUE THREAD

**Issue by kwikwag** [microsoft/vscode-jupyter#6168]
Issue Type: <b>Bug</b>

When displaying an HTML link in IPython, the interactive window produces a link pointing to `https://<uuid>.vscode-webview-test.com/vscode-resource/file///<path-to-project>/<url>`. The expected behavior is to point to `<url>`.

Code sample:

```python
# %%
from IPython.core.display import display, HTML

# %%
url = 'http://httpbin.org/ip'
text = 'Show my IP'
display(HTML(f'<a href="{url}">{text}</a>'))
```

Extension version: 2021.5.842923320
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

Screen capture:

![ipython-display-html-external-link](https://user-images.githubusercontent.com/392199/120916549-e7c72b00-c6b2-11eb-9c48-479af0de3f31.gif)

**Comment by DavidKutu** [comment]
Thanks for the issue @kwikwag. This will be fixed on the release of VS Code 1.57, and that's coming either tomorrow or Wednesday!
