### ISSUE TITLE
Support Save As for any image output (Plot Viewer mitigation)

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#6183]
The second button will open the user's file directory and they can save image with their preferred name and either pdf or the original format of the image.

**Comment by rchiodo** [comment]
Not sure how to get this to work. Not working.

**Comment by IanMatthewHuff** [comment]
I see this in renderer code when I build it, but not on installed jupyter. I think we just need to push a new build to blob storage. I'll do that.

**Comment by IanMatthewHuff** [comment]
Renderer updated 6/30

**Comment by joyceerhl** [comment]
Validated 
![image](https://user-images.githubusercontent.com/30305945/124824270-007f6680-df27-11eb-9e22-122b860b1d74.png)
