### ISSUE TITLE
How can I remove the toolbar?

### ISSUE THREAD

**Issue by randomQQQ** [microsoft/vscode-jupyter#6190]
![image](https://user-images.githubusercontent.com/63656568/121095976-f9ffb100-c7f9-11eb-963b-42a5fb01bc22.png)

**Comment by joyceerhl** [comment]
You can disable it by adding the following to your user settings.json file:

```
    "notebook.globalToolbar": false,
```

**Comment by randomQQQ** [comment]
thx )
