### ISSUE TITLE
.NET Interactive cell output is marked as `unknown`.

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode-jupyter#6192]
## Environment data

-   VS Code version: 1.57.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): latest
-   Python Extension version (available under the Extensions sidebar): N/A
-   OS (Windows | Mac | Linux distro) and version: Win 10 latest
-   Python and/or Anaconda version: N/A
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: N/A

## Steps to reproduce:

1. Install the [.NET Interactive extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode).
2. Run the command: ".NET Interactive : Create new blank notebook".
3. Select "Create as '.ipynb'"
4. Select "C#".
5. Execute the code `1+1` in the cell and wait for the result `2` to be displayed.
6. Save the notebook to disk.
7. Open the .ipynb in notepad.

Expected:

The cell's output type is specified as `"unknown"` where according to [the spec](https://nbformat.readthedocs.io/en/latest/format_description.html#code-cell-outputs) the type should be one of `stream`, `display_data`, `execute_result`, or `error`.

**Comment by DonJayamanne** [comment]
Thanks @brettfo based on the teams conversation i'll be doing the following:
* stdout & stderror will go with stream
* Error output items will go into error
* Rest will go into display_data

**Comment by IanMatthewHuff** [comment]
Validated. Looks like a display_data type.

![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/d8c9277a-f3f6-4a37-9ecd-ad0423388acc)
