### ISSUE TITLE
Unable to switch python environment

### ISSUE THREAD

**Issue by Nayak11** [microsoft/vscode-jupyter#6194]
When i try to switch python environment, it is asking me to install ipykernel. When trying to install ipykernel it is throwing below error.

![image](https://user-images.githubusercontent.com/36310654/121098919-bbdba080-c7ab-11eb-8dc2-04fc4238de40.png)

**Comment by IanMatthewHuff** [comment]
Actually if you could also change the setting Python->Logging->Level also to debug and collect the log from the "python" tab of the output window (the previous logging is in the Jupyter tab) that might also be helpful to tell us more about the issue with that conda version.

**Comment by DavidKutu** [comment]
@Nayak11, this issue should be solved on our new notebook interface, you can try it out by following these steps: https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code

Please open another issue if the bug persists on the new interface.
