### ISSUE TITLE
Spike on using DAP for ipython

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6207]
Have to figure out how we talk to ipython directly instead of just using debugpy to inject a debugger.

Can we do this through the Jupyter REST api? (meaning remote)
Can we do this in raw kernel or is jupyter required?

https://github.com/microsoft/vscode-simple-jupyter-notebook

**Comment by IanMatthewHuff** [comment]
Validated per iteration test plan.
