### ISSUE TITLE
Add decorators to current line for run by line

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6210]
Should be able to:
- Add line color
- Add glyph in the margin (need icon? hopefully can use codicons)

See: 
https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions

**Comment by DavidKutu** [comment]
I think this is done
![image](https://user-images.githubusercontent.com/20347396/126008980-fd7e4a79-6549-407b-840f-7ce7b9c6eac6.png)

**Comment by rchiodo** [comment]
I assume Rob is handling the IP indicator? We used to hack that in before, but since VS code knows about the debugging it will show the ip indicator? 

Actually if that's the case, maybe you didn't need to do anything here? Cause VS code would be putting the decorator too.

**Comment by DavidKutu** [comment]
what's the IP indicator?

**Comment by rchiodo** [comment]
The little arrow that shows what line you're currently running. 

IP stands for ```instruction pointer```. In C++ land it's called that and there's a register on the CPU that usually stores the address of the IP called ```rip```

https://en.wikipedia.org/wiki/Program_counter
