### ISSUE TITLE
Ask VS code for disabling language picker

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6211]
This isn't supported at the moment. Need VS code changes.

Time estimate is how long it would take to add it to VS code. Basically change their 'when' clause for select language.

**Comment by claudiaregio** [comment]
Is this to have a setting to hide the language picker along the right side of the notebook?

**Comment by rchiodo** [comment]
> Is this to have a setting to hide the language picker along the right side of the notebook?

Yeah. Part of the spec for Run by Line asked for the ability to prevent changing the language while debugging.

**Comment by DonJayamanne** [comment]
So this isn't a must fix. It's a nice to have.
I mean why would a user change the cell language, won't we have the same problem with users changing language of the python file (when debugging interactive window), that too is possible today, but we don't try to disable that!

Ie, why are we trying to do this. Is it fear that users can do this which could screw debugging experience? 

I don't think this is a good ask.

**Comment by claudiaregio** [comment]
If it helps get RBL in faster, we can table this

**Comment by DavidKutu** [comment]
Do we want this for other stuff besides run by line?

I was talking with Rob and we concluded that there's no point in doing this. We followed Don's example.
