### ISSUE TITLE
Hitting ctrl-z in ipynb notebook can cause corruption.

### ISSUE THREAD

**Issue by hellige** [microsoft/vscode-jupyter#6220]
Issue Type: <b>Bug</b>

Hard to say. I made a number of edits in an .ipynb notebook in the vscode notebook editor. Hitting ctrl-z a few times ended up corrupting a markdown cell, making incorrect apparently random edits into the middle of the text.

I've seen this a few times, but can't reliably reproduce it.

Extension version: 2021.5.842923320
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.4.99-12983-g8b7876ab9f5e

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 1607)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|14.21GB (14.17GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 9b09e0bc-2d95-4e4f-8096-e5ceebf3dfa0|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt943cf:30300583
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by rchiodo** [comment]
Thanks for the bug. 

This should be addressed when we switch over to VS code's new notebook API. Please track this issue for when we switch:
#1231.

You can try it yourself if you use VS code [insiders](https://code.visualstudio.com/insiders/).

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed with new native support for editing notebooks starting with v1.59 of VS Code.
