### ISSUE TITLE
How to change graph size

### ISSUE THREAD

**Issue by molly-w** [microsoft/vscode-jupyter#6223]
How to customize graph size to make it bigger?

![image](https://user-images.githubusercontent.com/63043224/121287714-aa61d800-c914-11eb-958a-22fe041107a6.png)

I noticed the graph is much bigger in VS Code Insider:
![image](https://user-images.githubusercontent.com/63043224/121287903-0b89ab80-c915-11eb-8c9f-c0cc5a48a0c3.png)

Is it also achievable in VS Code by some settings or in next release?

**Comment by rchiodo** [comment]
Thanks for the suggestion.

Unfortunately there is no way to change the graph size at the moment. I believe the insiders making it larger is actually a bug:
https://github.com/microsoft/vscode/issues/125299

The CSS provided by plotly should be what's used in the graph. Plotly would decide if the graph takes up the full width or not. In the stable version, the plotly CSS is being applied.

**Comment by molly-w** [comment]
@rchiodo. Thanks for your reply.

**Comment by jackthepanisher** [comment]
Just set the size using Plotly itself. There are multiple ways to do it but the simplest for your example would be:
```Python
import plotly.graph_objects as go
fig = go.Figure(
    data=[go.Bar(y=[2, 1, 3])],
    layout_title_text="A Figure Displayed with fig.show()",
    layout_width=1200,
    layout_height=600
)
fig.show()
```
This works in stable (old notebook editor) and insiders (preview notebook editor). The only difference to the insiders version seems to be that the default width is set to the current width of the cell. This is not dynamic, i.e. it will not re-size when changing the cell size after the output has been rendered.

**Comment by greazer** [comment]
Looks like this is resolved. Closing.
