### ISSUE TITLE
Native Notebooks - Integration w/ Pylance

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#6240]
Still getting user feedback that Pylance as the language server is throwing incorrect errors, lighting up diagnostic errors too much. 

We should do some investigation as to why this is still happening

**Comment by DonJayamanne** [comment]
Possibly a duplicate of (or result of) https://github.com/microsoft/vscode-jupyter/issues/4718

**Comment by DonJayamanne** [comment]
Closing as a dup
