### ISSUE TITLE
Have visual code detect already running jupyter servers

### ISSUE THREAD

**Issue by ghylander** [microsoft/vscode-jupyter#6246]
when working with jupyter notebooks there is a feature to select what server to use. This is a very nice option, but it could be better.

Default behaviour is to start a new server, and there is an option to conenct to a local or remote jupyter server. Both options are super ok, but there could be a behaviour that tries to find a localhost jupyter server before creating a new server

**Comment by DonJayamanne** [comment]
Duplicate of #1556
