### ISSUE TITLE
The matplotlib drawing will have too much white space, which looks very unsightly

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/vscode-jupyter#6257]
## Environment data

version: 1.57.0-insider (user setup)
commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
date: 2021-06-09T11:49:36.076Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.18363
## Expected behaviour
Clear the extra white space of the picture

## Actual behaviour

![image](https://user-images.githubusercontent.com/33288114/121645533-e2108180-cac6-11eb-84d3-54a1ccb6dce2.png)

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on changing this functionality at this time.
