### ISSUE TITLE
Jupyter offline install into Ubuntu Linux fails

### ISSUE THREAD

**Issue by bitperza** [microsoft/vscode-jupyter#6258]
## Environment data

-   VS Code version: 1.56.2
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.999230701
-   Python Extension version (available under the Extensions sidebar): 2021.5.842923320
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 18.04.5. LTS
-   Python and/or Anaconda version: Python 3.6.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): NA
-   Jupyter server running: Local | Remote | N/A: NA

## Expected behaviour

Install succeeds

## Actual behaviour

Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code 1.56.2

## Steps to reproduce:

The workstation is offline. I brought Jupyter as .vsix file on memory stick. Then tried installing .vsix as usual in EXTENSIONS panel.

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by claudiaregio** [comment]
Hi @bitperza, are you able to update to the latest version of VS Code per chance? I believe this is a mismatch between the version of vs code and the extension version you are attempting to install.

**Comment by bitperza** [comment]
Hi @claudiaregio It did actually fix the problem! Sometimes the easiest solution really works :)
