### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by anantvatta** [microsoft/vscode-jupyter#6269]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.6.832593372`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.57.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 4237,
		"activateCallTime": 225,
		"activateResolvedTime": 268,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-toolsai.jupyter",
				"_lower": "ms-toolsai.jupyter"
			},
			"activationEvent": "onLanguage:python"
		}
	},
	"runtimeErrors": []
}
```

**Comment by joyceerhl** [comment]
@anantvatta Please fill out our bug template in full so we can assist you: https://github.com/microsoft/vscode-jupyter/issues/new?assignees=&labels=bug&template=1_bug_report.md

**Comment by greazer** [comment]
Issues labeled with "Info needed" are closed if we do not receive more information from the issue author in 2 weeks. If you are the issue author and you still are running into this problem, please reactivate with additional information.
