### ISSUE TITLE
Unresponsive cells after viewing variable in data viewer

### ISSUE THREAD

**Issue by pyr-kaboosh** [microsoft/vscode-jupyter#6271]
Issue Type: <b>Bug</b>

-run cells
-select: show variable 
-go back to the the tab with the .ipynb code 
-click on a different cell
-now there is two cursors blinking in two different cells taking no keyboard input
![Blinking](https://user-images.githubusercontent.com/80962489/121806978-6fcca800-cc52-11eb-9f57-60d2124dbf39.png)
-to type again i have to select another tab and go back to this one
-then i can finally type i again

Not a huge issue but quite annoying.

Extension version: 2021.6.832593372
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.10.41-1-MANJARO

<details>
Also running github theme, latex workshop, live share, python, pylance extensions
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor (12 x 3692)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.59GB (8.90GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 1ef437d3-6074-4443-91e4-2c5484053672|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by joyceerhl** [comment]
@pyr-kaboosh I can't replicate the behavior you describe (though I'm on Windows)--does this happen every time for you? Are there any additional steps you have to take in order for this to occur? (It might be simpler to provide a screen recording using software like gifcap.dev)

**Comment by greazer** [comment]
@pyr-kaboosh, We believe that this has been fixed in the latest versions of notebooks in VS Code. These are available by installing VS Code Insiders. Can you check to see if that works for you? If so, this will be addressed in an upcoming release.

**Comment by pyr-kaboosh** [comment]
It seems difficult to replicate and doesn't always happen. There must be some other reason as well that triggers it. IF it happens again I'll make sure to document it better. But apparently it has been fixed.
