### ISSUE TITLE
Start jupyter from a wrong python interpreter

### ISSUE THREAD

**Issue by shelfofclub** [microsoft/vscode-jupyter#628]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1.Open any .ipynb file.

## Actual behavior
I have a virtual environment "learnpytorch". Both the system-wide python environment (/usr/bin/python) and the "learnpytorch" virtualenv have jupyter notebook installed. I used to work in "learnpytorch". Now, I work in the system-wide python environment. But I found that when I open an ipynb file, jupyter is started from "learnpytorch". 
## Expected behavior
Jupyter is started from the interpreter selected for the current workspace.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.8.105369
-   **VS Code version:** 1.48.2
-   **Setting python.languageServer:** Jedi
-   **Python and/or Anaconda version:** 3.8.5
-   **OS:** Linux (Manjaro):
-   **Virtual environment:** virtualenv

## Python Output

[python_output.txt](https://github.com/microsoft/vscode-python/files/5157053/python_output.txt)

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by tzaffi** [comment]
This is a real issue. Please re-open and address.

**Comment by rchiodo** [comment]
@tzaffi can you open another bug? This original issue was identified as by design. We'd need more information from you on what might be happening and your exact repro steps.
