### ISSUE TITLE
Jupyter Notebooks Started Using 8 Spaces for Indentation for No Reason

### ISSUE THREAD

**Issue by tddschn** [microsoft/vscode-jupyter#6285]
Originally posted at https://github.com/microsoft/vscode-python/discussions/16467

## Environment data

-   VS Code version: 1.57.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.999230701
-   Python Extension version (available under the Extensions sidebar): v2021.5.926500501
-   OS (Windows | Mac | Linux distro) and version: macOS Big Sur 11.4
-   Python and/or Anaconda version: python 3.9.4 from conda-forge
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: local

## Expected behaviour

Auto indent with 4 spaces in notebooks.

## Actual behaviour

Jupyter notebooks started ssing 8 spaces for indentation for no reason.

## Steps to reproduce:

Can't reproduce it. But I can't fix it either, so I opened an issue here. :)
<img src=https://user-images.githubusercontent.com/45612704/121769977-28ceac00-cb99-11eb-9831-23de01200eb2.png width=500>
(The auto indentation is 8 spaces as shown above)  
</br>
</br>

## Logs

<details>

<summary>Output for <code>Jupyter</code>

<code>Jupyter</code>)
</summary>

<p>

```
Info 2021-06-15 17:47:27: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-06-15 17:47:27: [32mPosting message to Notebook UI 
Info 2021-06-15 17:47:27: Notebook Session status file://somepath/test.ipynb # Busy
Info 2021-06-15 17:47:27: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-06-15 17:47:27: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-06-15 17:47:27: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-06-15 17:47:27: [32mPosting message to Notebook UI 
Info 2021-06-15 17:47:27: Notebook Session status file:///somepath/test.ipynb # Idle
Info 2021-06-15 17:47:27: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-06-15 17:47:27: [32mPosting message to Notebook UI 
Info 2021-06-15 17:47:27: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-06-15 17:47:27: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-06-15 17:47:27: [32mWidget Coordinator received IPyWidgets_msg_received
```

</p>
</details>

**Comment by IanMatthewHuff** [comment]
@tddschn There is a new UI being rolled out for Jupyter notebooks which it looks like you have here. In this new UI each cell is just a VS Code editor instance. So this indentation should just be handled by the Editor: Tab Size setting or by any python specific language specific indentation settings that you have. Does changing that setting help your scenario at all?

**Comment by tddschn** [comment]
Thank you @IanMatthewHuff ! I went through the settings.json and found that `editor.tabSize` is set to 8 (but I don't think I set that), changing it to 4 fixed the indentation in notebooks!

It's weird that this setting doesn't seem to affect `.py` files opened in VS Code at all.
