### ISSUE TITLE
Jupyter stopped working after upgrade

### ISSUE THREAD

**Issue by kalofolias** [microsoft/vscode-jupyter#6292]
Issue Type: <b>Bug</b>

I am using notebooks inside WSL (windows insiders beta version). 

Jupyter broke after the latest VS code upgrade. It is loading forever now and I get a message "Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information."

Extension version: 2021.6.832593372
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.21390
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (20.49GB free)|
|Process Argv|--file-uri file:///g%3A/My%20Drive/AIRICA/Data%20Science/Notebooks/Vassilis/airlab.code-workspace --crash-reporter-id b73fa47d-8d75-46dc-8ad1-56cff0b15e2b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.51GB (13.97GB free)|
|VM|0%|
</details>

**Comment by IanMatthewHuff** [comment]
@kalofolias Looks like you have an older version of the Jupyter extension. Could you please update that? There were breaking changes with the most recent vscode update so older versions of the Jupyter extension will not work with it.
