### ISSUE TITLE
Request for debug version of VS Code to test widget

### ISSUE THREAD

**Issue by ansaxena1** [microsoft/vscode-jupyter#6294]
Could you provide a debug version of vs code that can pull from a custom location for the widget source, to help with debugging our custom widget for VS Code dark theme issues. 

Note to team:
* This is a request from AML team

**Comment by rchiodo** [comment]
We could improve the logging so that the hash of where the directory is going to be is logged. This would make it possible to predict where to put your index.js

**Comment by ansaxena1** [comment]
What do you mean by where the directory is going to be? Is this going to be a local path?

**Comment by IanMatthewHuff** [comment]
@ansaxena1 I'm going to take a look at this quick (though it might be early next week) but we think that we can just log where we are looking for the widget sources locally. Then you can just drop your widget bits there to test them without a debug version of vs code.

**Comment by ansaxena1** [comment]
Following up - has there been any progress with this?

**Comment by IanMatthewHuff** [comment]
@ansaxena1 Sorry again about the delay. I'm adding in a bit of tracing to our extension to surface the path that we are loading local files from. 

https://github.com/microsoft/vscode-jupyter/pull/7085

When this PR is in then in tomorrow's vscode-insiders build of our extension this new logging should show up. This will point to the exact location on disk that we are looking for the name / version combo of the widget. If you drop the widget files at that path you should be able to test out a new version locally.

**Comment by greazer** [comment]
@ansaxena1, has this issue been resolved? If not, please reopen with additional details.
