### ISSUE TITLE
Pointing to a non running remote server makes kernel picker and run cell disappear

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6297]
Set jupyter to remote
Run a cell
Stop VS code
Kill remote server

Open VS code
Cell is missing run button:

![image](https://user-images.githubusercontent.com/19672699/122118852-6459b800-cddd-11eb-9035-51e2fd31d13b.png)

And there's no kernel selector.

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/8474
