### ISSUE TITLE
Create meta context keys for notebook keybinding enablement

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#6299]
The when clauses for notebook editor keybindings are getting too long to easily parse. Per @IanMatthewHuff we should create our own meta context keys so we can express the conditions as follows:

```
"when": "jupyterNotebookCellEditorSelected || jupyterCellListCodeSelected"
```

**Comment by DonJayamanne** [comment]
Not sure how we can do that.
As you toggle between notebooks, we'll need to update our context keys and that's async.
i.e the context keys will change only after a few seconds, hence the commands/icons will unnecessarily appear & then disappear or viceversa.
I dont think we can create wrappers around vscode context keys.

**Comment by IanMatthewHuff** [comment]
Chatted about this at standup and currently not an easy way to do this, and no current issues with this, so closing.
