### ISSUE TITLE
Save File Button of New Jupiter User Interface 

### ISSUE THREAD

**Issue by rickypang0219** [microsoft/vscode-jupyter#6308]
## Environment data

-   VS Code version: 1.57.0 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.999406279
-   Python Extension version (available under the Extensions sidebar): Pylance v2021.6.1
-   OS (Windows | Mac | Linux distro) and version: MacOS 11.4
-   Python and/or Anaconda version: Python3.9.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | : Local 

## Expected behaviour
Similar to previous user interface, there is a floppy disk icon for saving ipynb file 
## Actual behaviour
I can't find the save-file button icon in the new UI

 I have upgraded my Jupyter extension to the latest version and it suddenly changes to the new user-interface. In previous UI,  there is a floppy disk icon for saving ipynb file. However, I cannot find such icon and the corresponding save-file button in the new user-interface. May I ask where is the save-file button in the new UI? 

Old UI: 
![120829773-bf4b0e00-c598-11eb-95bd-5861771f5787](https://user-images.githubusercontent.com/60353958/122255939-3077b300-cf01-11eb-9678-d2d3737dc213.png)

New UI: 
<img width="1138" alt="Screenshot 2021-06-17 at 00 06 44" src="https://user-images.githubusercontent.com/60353958/122256000-3c637500-cf01-11eb-9ebd-15a64bce6f1b.png">

**Comment by rchiodo** [comment]
Thanks for the bug. The new UI does not have a save file button on the toolbar. Instead you have to use a keyboard shortcut or the 'File | Save' menu.
