### ISSUE TITLE
Make it easier for customers to depart experiment

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#6309]
https://stackoverflow.com/questions/67983403/debugging-of-jupyter-notebooks-in-vscode

This is just an insiders user, but as we roll out native notebooks heavier we might get more requests for this in the near future. Might be worth a stopgap setting / command to help users depart the experiment?

**Comment by rchiodo** [comment]
We could add a command to do this.

**Comment by rchiodo** [comment]
Toggle menu?

**Comment by rchiodo** [comment]
Command pops up survey?

**Comment by rchiodo** [comment]
Survey might instead open an issue.

**Comment by rchiodo** [comment]
![image](https://user-images.githubusercontent.com/19672699/122470512-ff37cb00-cf72-11eb-9dbe-0ea352835604.png)
