### ISSUE TITLE
Julia kernel not visible

### ISSUE THREAD

**Issue by davide-f** [microsoft/vscode-jupyter#6314]
I am using the extension jupyter to run the code.
I recently updated and installed Julia 1.6.1 and removed Julia 1.6.0. Accordingly I updated the file .json in VSCode and the REPL works fine.
However, Julia in Jupyter does not work: I cannot set the bin location of the new 1.6.1; the interface is stuck at the old location 1.6.0.
![image](https://user-images.githubusercontent.com/67809479/122302422-5ea9c280-cf02-11eb-8fae-3b29e2ba552c.png)

## Environment data

-   VS Code version: 1.58.0-insiders
-   Jupyter Extension version (available under the Extensions sidebar): v2021.7.942275039
-   Python Extension version (available under the Extensions sidebar): v2021.5.926500501
-   OS (Windows | Mac | Linux distro) and version: Windows 10 19042.1052
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | local

**Comment by rchiodo** [comment]
Thanks for the bug.

If you go to a command prompt and run 'jupyter kernelspec list' does it list your 1.61 kernel or the 1.60 kernel? 

We find the kernels from the locations that jupyter writes them. It may also be our cache is not updating, although restarting VS code should fix that.

**Comment by rchiodo** [comment]
Sorry there was no info provided. Closing the issue.
