### ISSUE TITLE
Plot Viewer no longer an option with latest update

### ISSUE THREAD

**Issue by Eandreas1857** [microsoft/vscode-jupyter#6315]
Issue Type: <b>Bug</b>

The ability to use plot viewer on plots in jupyter notebook is not an option anymore. I have tried hovering over the plot as well an double clicking and drag-and-droping the plot but the plot viewer just isn't there anymore.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.895Z)
OS version: Linux x64 4.15.0-144-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|31.27GB (21.73GB free)|
|Process Argv|--force-user-env --unity-launch --crash-reporter-id 8549cb84-3041-4f25-a346-0734e581d59b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999406279
hexeditor|ms-|1.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
vscorehov:30309549
vscod805:30301674

```

</details>

**Comment by claudiaregio** [comment]
Hi @Eandreas1857, you have been updated to the new Native Notebooks interface :) What were you hoping to do with the Plot Viewer?

**Comment by Eandreas1857** [comment]
Hello @claudiaregio, the plot viewer is extremely useful when I have multiple plots within a notebook and want to be able to click between a few in another tab in VS quickly. Further, most of my plots are quite large and are difficult to look at in the notebook output, the plot viewer made it easy to open a plot and zoom in on particular parts of the plot. Honestly, this feature was my favorite part of using jupyter notebook in VScode rather than in a browser!

**Comment by claudiaregio** [comment]
Glad to hear you enjoy the plot viewer :) Do you do anything with the plots after looking at them? What plotting libraries are you using? Have you tried the matplotlib widget?

**Comment by Eandreas1857** [comment]
Currently, I only need to view the plots, not interact with them. I am only using matplotlib and have not used the widget. I only need the capability to be able to open the plots as was available with the plot viewer.

**Comment by DonJayamanne** [comment]
> Currently, I only need to view the plots, not interact with them. I am only using matplotlib and have not used the widget. I only need the capability to be able to open the plots as was available with the plot viewer.

Do you need to open the plots on the side so you can save them or
is the purpose to:
* Be able to view is on the side, then re-run the cell & compare the difference between the two plots?
* Or is it so that you can save the plot (image) to disc?
* Or other?

Basically I'm trying to understand the why you are opening the image on the side. Thanks
FYI - in our insiders version we've added support to be able to save plots (without having to open them - please install VS Code Insiders and try this out).

**Comment by Eandreas1857** [comment]
I would like to be able to view plots on the side, then re-run the cell and compare the difference between the two plots, as well as compare with other plots scattered throughout the notebook. Also, the capability of zooming plots in and out is nice when my plots are large. I currently don't really care about saving them, though I will install the VScode insiders.

**Comment by claudiaregio** [comment]
+1 
![image](https://user-images.githubusercontent.com/19276747/122619820-2f9c6980-d046-11eb-9772-699cbf03065c.png)

**Comment by claudiaregio** [comment]
+1 
![image](https://user-images.githubusercontent.com/19276747/122651237-5b722a80-d0ec-11eb-9190-90cd98f39a35.png)

**Comment by peguerosdc** [comment]
I am having the same issue with my vscode instance:

Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-59-generic snap

[Plot Viewer](https://code.visualstudio.com/docs/datascience/jupyter-notebooks#_plot-viewer) was a very useful feature. Why was it moved to insiders if it already was on the main version?

**Comment by sebgorgon** [comment]
Same here, would really appreciate Plot Viewer back.

**Comment by claudiaregio** [comment]
+1 
![image](https://user-images.githubusercontent.com/19276747/124205971-3c35ae80-da97-11eb-9cbe-e13a1dc5915a.png)

**Comment by claudiaregio** [comment]
+1 
![image](https://user-images.githubusercontent.com/19276747/124205989-4657ad00-da97-11eb-99bb-fd5bb257daae.png)

**Comment by claudiaregio** [comment]
+1 
![image](https://user-images.githubusercontent.com/19276747/124206025-57082300-da97-11eb-8b05-76a2759200c0.png)

**Comment by claudiaregio** [comment]
+1 
![image](https://user-images.githubusercontent.com/19276747/124206060-65563f00-da97-11eb-9cb6-0be38b5ffcda.png)

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/124206081-71420100-da97-11eb-86ab-04668ee58b04.png)

**Comment by claudiaregio** [comment]
+1 
![image](https://user-images.githubusercontent.com/19276747/124208630-c92f3680-da9c-11eb-8765-4c2400054a64.png)

**Comment by claudiaregio** [comment]
+1
![image](https://user-images.githubusercontent.com/19276747/124331137-ab68dc80-db43-11eb-8426-476d7c7694df.png)

**Comment by claudiaregio** [comment]
+1
![image](https://user-images.githubusercontent.com/19276747/124331203-c50a2400-db43-11eb-8cfb-bd206a2cc66d.png)

**Comment by claudiaregio** [comment]
+1
![image](https://user-images.githubusercontent.com/19276747/124331241-d3584000-db43-11eb-968c-21a541d89f99.png)
