### ISSUE TITLE
no option "Open in preview Notebook Editor"

### ISSUE THREAD

**Issue by NeoFantom** [microsoft/vscode-jupyter#6317]
## Environment data

Version: 1.58.0-insider (system setup)
Commit: a81fff00c9dab105800118fcf8b044cd84620419
Date: 2021-06-17T05:17:34.858Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041

I use vscode insider. I wait for and make sure the python and jupyter extensions to be ready. When I right-click a jupyter notebook (.ipynb) file, it doesn't show the option "Open in preview Notebook Editor". What might I be doing wrong?

**Comment by DonJayamanne** [comment]
Thang for filling this issue.
Looks like your are using vscode insiders. In insiders the default is the preview editor, hence the menu is not applicable.
Opening ipynb will default to the new editor.
If this doesn't work as expected please feel free to reopen this issue or file a new bug
