### ISSUE TITLE
Support Jupyter Lab Widgets

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#6320]
As Jupyter lab gets more popular we'll end up with widgets in jupyter lab & not notebooks,
Also user might install jlab widget instead of the notebook version.

**Comment by rchiodo** [comment]
Do we have telemetry on how many widgets are downloaded from the CDN versus loading from the nbextensions folder?

**Comment by DonJayamanne** [comment]
closing for now, i don't think we need this

**Comment by DonJayamanne** [comment]
This will be required for Jupyter Notebook 7

**Comment by DonJayamanne** [comment]
not required
