### ISSUE TITLE
still jupyter.selectjupyteruri failed

### ISSUE THREAD

**Issue by amacfie** [microsoft/vscode-jupyter#6329]
Same as https://github.com/microsoft/vscode-jupyter/issues/4330.
I thought it would be fixed in the version I'm running.

## Environment data

-   VS Code version: 1.56.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.832593372
-   Python Extension version (available under the Extensions sidebar): v2021.5.926500501
-   OS (Windows | Mac | Linux distro) and version: NixOS
-   Python and/or Anaconda version: 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Remote

## Expected behaviour

Same as https://github.com/microsoft/vscode-jupyter/issues/4330:
I get the UI box to choose local vs. past remote vs new remote jupyter server.

## Actual behaviour

Same as https://github.com/microsoft/vscode-jupyter/issues/4330:
Error message

## Steps to reproduce:

Same as https://github.com/microsoft/vscode-jupyter/issues/4330:
Execute Jupyter: Specify local or remote Jupyter server

**Comment by rchiodo** [comment]
Thanks for the bug. Can you include the error message text and the output from the 'Help | Toggle Developer Tools' console?

**Comment by amacfie** [comment]
@rchiodo Thanks. The error message and the output in developer tools are the same:
```
workbench.desktop.main.js:735 Command 'Jupyter: Specify local or remote Jupyter server for connections' resulted in an error (Running the contributed command: 'jupyter.selectjupyteruri' failed.)
```

**Comment by rchiodo** [comment]
Is there a callstack for that error? My guess is that you had remote specified and the remote is no longer available and we're crashing trying to talk to it.

You might be able to workaround this error my cleaning your user cache. On windows it's here:

C:\Users\aku91\AppData\Roaming\Code\User\globalStorage

Clearing that directory resets all of your global settings that aren't specified in a settings.json. Stuff like passwords and other secret things (in our case the remote uri)

**Comment by amacfie** [comment]
@rchiodo I don't see a callstack. I get the same error when I run `$ code --user-data-dir /tmp/empty_dir`, is that the test you had in mind?

**Comment by rchiodo** [comment]
Yes that should have had the same effect. TIL about ```--user-data-dir```. 

With no callstack, we'll have to wait till somebody can repro locally. You might try updating to the latest bits in the meantime (although this code hasn't changed in months, so I doubt that will do anything).

Do other jupyter commands work? Like say "Jupyter Create New Blank Notebook"

**Comment by amacfie** [comment]
Yeah I am able to do Jupyter Create New Blank Notebook and have a working local notebook.

I'll mention this on the off chance it's related: I'm not running the gnome keychain service so for example if I log in to settings sync I get an error about that and although I can log in, I'm logged out again when I restart VS Code.

**Comment by greazer** [comment]
@amacfie, please reopen if you're continuing to have issues using v1.59.
