### ISSUE TITLE
Git diff for ipynb files is being replaced by the notebook editor

### ISSUE THREAD

**Issue by wpbrown** [microsoft/vscode-jupyter#633]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Click python notebook file with changes in the Git pane. 

## Actual behavior

Diff window shows briefly and then notebook editor replaces the tab.

## Expected behavior

Diff editor should remain open. Notebook editor should not start in a git diff view.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:**  Remote 
-   **Extension version:**  2020.8.103604
-   **VS Code version:** 1.48.0
-   **OS:** Linux 

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by jamesmyatt** [comment]
Which version of the extension was this working in?

**Comment by greazer** [comment]
We believe this is a problem that should be solved on the VS Code side, because a custom editor should not be used for git diff.

**Comment by joyceerhl** [comment]
Filed upstream https://github.com/microsoft/vscode/issues/118764

**Comment by IanMatthewHuff** [comment]
Trying to validate this. Doesn't seem right here?
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/d6dc70d4-8a30-4ca6-9fd0-cf1f57734442)
I was testing in stable with CustomEditor.

**Comment by IanMatthewHuff** [comment]
Yeah, I believe this is a small improvement in that you can at least see the two editor SxS to look for differences, but it's not really a real diff view. We're also in an odd state where both notebooks are executable, even when not backed by a writable file. So you can execute on the old git file and get odd errors when you try to save.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/99c506bc-282d-4221-8b61-1f1ecdc8ba20)
Pulling back to backlog.

**Comment by chenfeibo** [comment]
It is working for me now. I had the same issue before. It was fixed when I installed the insider version, but after that it also worked in the stable version. My understanding is during installing the insider version, it fixed the config. You can try using the following config in the user settings.

```
    "notebook.kernelProviderAssociations": [
        {
            "viewType": "jupyter-notebook",
            "kernelProvider": "ms-toolsai.jupyter"
        }
    ]
```
With that, it can show two different modes of diff. First pic shows the new native feature, where you can even ignore metadata and/or output. Click it again, it'll show the traditional text based diff (second pic).

![pic2](https://user-images.githubusercontent.com/58605949/114316981-c84cc100-9aba-11eb-85c1-d1e7a390bb61.png)
![pic1](https://user-images.githubusercontent.com/58605949/114316985-caaf1b00-9aba-11eb-852d-a191a522fc8c.png)

**Comment by joyceerhl** [comment]
This is still showing the rich editors in the diff view. Moving back to backlog. I believe Matt put in a fix upstream that was supposed to resolve this, but maybe we still need to do something on our end.

**Comment by joyceerhl** [comment]
According to https://github.com/microsoft/vscode/issues/118764#issuecomment-799836958, for custom editors if we want the raw json to show up in the diff view we would need to implement a raw text custom editor provider and reroute git diff file opens to that provider. Like Ian said earlier, whether we fix this depends on the rollout timeline for the new preview native notebooks.

**Comment by oparaskos** [comment]
Is there a work-around for this;
So far I've tried all the workarounds i can find on the net:
 * adding `"jupyter.useNotebookEditor": false,` to settings; it greys out and doesnt recognise the setting
 * adding `"jupyter.experiments.optOutFrom": [ "NativeNotebookEditor", ],` doesnt help
 * adding `"files.associations": { "*.ipynb": "text" },` no help
 * adding `"notebook.diff.enablePreview": false,` no help
 * disabling the plugin (apparently it is required by the python plugin, thus needs me to disable python too which is   depended upon by other plugins i use)
 * can't `set language mode` as no text editor is active

**Comment by scrambldchannel** [comment]
I hacked around it by pinning to an earlier version. 

I think I followed this from @jamesmyatt

> This was working in v2021.2.603412351, but broken again in v2021.3.619093157

This might be a workaround if you don't need anything bleeding edge

**Comment by Ortega-Dan** [comment]
> Is there a work-around for this;
> So far I've tried all the workarounds i can find on the net:
> 
> * adding `"jupyter.useNotebookEditor": false,` to settings; it greys out and doesnt recognise the setting
> * adding `"jupyter.experiments.optOutFrom": [ "NativeNotebookEditor", ],` doesnt help
> * adding `"files.associations": { "*.ipynb": "text" },` no help
> * adding `"notebook.diff.enablePreview": false,` no help
> * disabling the plugin (apparently it is required by the python plugin, thus needs me to disable python too which is   depended upon by other plugins i use)
> * can't `set language mode` as no text editor is active

You are right, 
there seems to be no solution to this

**Comment by Ortega-Dan** [comment]
When pasting this in the settings.json it just grays out and doesn't work.
`    "notebook.kernelProviderAssociations": [
        {
            "viewType": "jupyter-notebook",
            "kernelProvider": "ms-toolsai.jupyter"
        }
    ]`
    
    
![image](https://user-images.githubusercontent.com/24926168/118155147-8676a980-b3dd-11eb-94c9-22c290300e43.png)

Is this an issue ?, or the setting must go inside a different object than the root of the settins json object ?

**Comment by chenfeibo** [comment]
> When pasting this in the settings.json (as in the last response from @chenfeibo) it just grays out and doesn't work.
> ![image](https://user-images.githubusercontent.com/24926168/118155444-e0776f00-b3dd-11eb-98b3-654c9f0182d7.png)
> 
> ![image](https://user-images.githubusercontent.com/24926168/118155147-8676a980-b3dd-11eb-94c9-22c290300e43.png)
> 
> Is this an issue ?, or the setting must go inside a different object than the root of the settins json object ?

Just re-checked mine, these lines are greyed as well. It could be some latest updates invalidated them. Then I don't know what operation helped, maybe the installation of a inside build.

**Comment by benlindsay** [comment]
> I hacked around it by pinning to an earlier version.
> I think I followed this from @jamesmyatt
> >   This was working in v2021.2.603412351, but broken again in v2021.3.619093157
>
> This might be a workaround if you don't need anything bleeding edge

Confirmed @jamesmyatt and @scrambldchannel's posts. I resorted to pinning Jupyter back to that version as well.

**Comment by Ortega-Dan** [comment]
Thanks. Then it seems like a confirmed issue on the current extension version.

**Comment by Ortega-Dan** [comment]
And in that case documenting here the temporal workaround can be very helpful. 
I don't see any v2021.2.603412351 in the releases. 
Am I looking at the right place ?
Or
Do you guys know if the following is the working version ?
![image](https://user-images.githubusercontent.com/24926168/119210628-dc4cf080-ba72-11eb-92e7-4cf828b26b80.png)

**Comment by benlindsay** [comment]
@Ortega-Dan I don't know how the releases on github translate to the versions available in the VSCode app itself, but if you go to your extensions panel in VSCode, go to your Jupyter extension, click the gear, click "Install another version", should see "2021.2.603412351" as one of the options you can roll back to.

![image](https://user-images.githubusercontent.com/9361152/119510767-675e0d00-bd37-11eb-861c-e23b8dadb642.png)

![image](https://user-images.githubusercontent.com/9361152/119510839-7775ec80-bd37-11eb-858a-abdab9046e9e.png)

**Comment by Ortega-Dan** [comment]
Thank you so much for the great help. !!

It looks like it is working now on the latest version with stable vscode.

Here: 
![working](https://user-images.githubusercontent.com/24926168/124176901-2adbaa80-da75-11eb-8894-6eefc869c669.png)

**Comment by scrambldchannel** [comment]
Cool, working for me too - thanks for sorting this out team :+1:

**Comment by benlindsay** [comment]
Just to make sure I haven't messed up my settings too much, this is still just available on Insiders, not VSCode proper, right? That's how it's looking on my machine at least

**Comment by joyceerhl** [comment]
@benlindsay It's available in everyone in Insiders and a fraction of users in Stable. If you're in VS Code stable you can also opt into the new native notebooks UI: https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code#enabling-the-new-experience

**Comment by benlindsay** [comment]
@joyceerhl Neat, thanks for the info! I did that and got the new stuff in VSCode stable now. Git diffing looks great! The kernel stuff was acting really weird but that's a battle for another day :)

**Comment by oparaskos** [comment]
@joyceerhl Thank you so much; that new git diffing workflow is so much better 👏💯

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed with new native support for editing notebooks starting with v1.59 of VS Code. If this issue continues to occur in the latest build of VS Code, please reopen or enter a new issue.
