### ISSUE TITLE
Jupyter Notebook Not Loading in VS Code

### ISSUE THREAD

**Issue by AnandaSP** [microsoft/vscode-jupyter#6330]
I usually keep notebooks open on VS Code. When VS Code gets opened, notebooks will get reloaded. But, since yesterday all existing notebooks not getting loaded, i.e. seeing blank screen. But, I can create new notebooks. This happens only for .ipynb, all .py files are getting reloaded.

**Comment by claudiaregio** [comment]
Hi @AnandaSP, could you please provide the extension versions of Jupyter and Python you are working with as well as the VS Code version? Could you also provide us your settings JSON content?

**Comment by AnandaSP** [comment]
VS Code Version: 1.57.1
Jupyter Extension Version: 2021.6.999406279
Python Extension Version: 2021.6.944021595

JSON Settings:
![image](https://user-images.githubusercontent.com/60298675/122634396-ab0c2280-d0fb-11eb-894f-c68bb774c403.png)

Let me know if anything else.

**Comment by claudiaregio** [comment]
@AnandaSP, could you please provide the raw JSON setting content? 

Ctrl + Shift + P -> Preferences: Open Settings (JSON)

**Comment by AnandaSP** [comment]
Sure. Here you go:

{
    "python.pythonPath": "C:\\Users\\AnandaPal\\AppData\\Local\\Programs\\Python\\Python39\\python.exe",
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
    },
    "window.zoomLevel": -1,
    "jupyter.jupyterServerType": "local",
    "notebook.cellToolbarLocation": {
        "default": "right",
        "jupyter-notebook": "left"
    }
}

**Comment by claudiaregio** [comment]
@AnandaSP Just double checking here, closing and reopening the file did not work?

**Comment by AnandaSP** [comment]
Closing is not working for those notebooks that are already opened. Some notebooks weren't saved, now can't save those too. I can reopen notebooks though.

**Comment by rchiodo** [comment]
@AnandaSP  can you upload the output from the 'Jupyter' output panel and the Developer Tools panel (Help | Toggle Developer Tools, and View | Output)

Thanks.

**Comment by AnandaSP** [comment]
https://github.com/microsoft/vscode-jupyter/issues/6330#issuecomment-865163094  Actually, in my case notebook is loading and loading. I can re-open, but which ones are already opened, I'm unable to close.

**Comment by jackthepanisher** [comment]
@AnandaSP it might be the case that there was a switch to the new notebook editor but your opened notebooks were using the old editor. In that case, the already opend notebooks will not display correctly.

To verify this, right-click on the tab of one of the affected notebooks and choose "Reopen Editor With..." and check which of the options is marked "active" and which is marked "default".

If it displays as:
- Jupyter Notebook (preview) Default
- Jupyter Notebook (custom) Active

..you can simply change to the new editor by clicking on "Jupyter Notebook (preview)".
In case you want to switch back to the old notebook editor, disable A/B tests in the Jupyter extension setting and restart VS Code.

**Comment by greazer** [comment]
This problem has been resolved in Stable v1.59 and Insiders.
