### ISSUE TITLE
Plotly 'notebook' renderer creates only blank output using preview notebook editor

### ISSUE THREAD

**Issue by jackthepanisher** [microsoft/vscode-jupyter#6334]
## Environment data

-   VS Code version: 1.58.0-insider 
-   Jupyter Extension version (available under the Extensions sidebar): v2021.7.949309867
-   Python Extension version (available under the Extensions sidebar): v2021.7.922878407-dev
-   OS (Windows | Mac | Linux distro) and version: Windows 10 21H1 (19043.1052)
-   Python and/or Anaconda version: Python 3.9.0 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Can use Plotly renderer types 'notebook' or 'notebook_connected' when using the preview notebook editor.

## Actual behaviour

Only an empty cell output is shown but the cell output is resized to what appears to be the possible dimensions of the Plotly graph.

Interestingly, generating a Plotly graph using 'notebook' renderer with the preview notebook editor, saving and then re-opening the .ipynb file with the old notebook editor will show the graph without re-generating the cell output. So it seems that this is an issue with the cell display itself but not with the generation of the cell output content.

<details>
<summary>More details</summary>

<p>
Currently, the default 'vscode' (aka 'plotly_mimetype') doesn't seem to support Plotly animations (see #4364). When using the old notebook editor "Jupyter Notebook (custom)" it is possible to use 'notebook' or 'notebook_connected' as the Plotly renderer which then also supports Plotly animations in VS Code. With the new notebook editor (Jupyter Notebook (preview)" only 'vscode' seems to work as inline renderer type but this renderer option still does not support Plotly animations or other interactive features in VS Code. This applies to insider version (1.58.0-insider) as well as the stable version (1.57.1).

Note 1: Other non-inline renderers like 'browser' are working as expected and would be a possible work-around to some extent. But of course it would not present the same experience as an inline renderer.

Note 2: In older versions (1.55.2 stable) the 'iframe' and 'iframe_connected' renderers were working with the old notebook editor as well but are not working anylonger (at least since 1.56.2 stable).

</p>
</details>

## Steps to reproduce:

```Python
import plotly.express as px
df = px.data.gapminder()
fig = px.scatter(df, x="gdpPercap", y="lifeExp", animation_frame="year", animation_group="country",
           size="pop", color="continent", hover_name="country",
           log_x=True, size_max=55, range_x=[100,100000], range_y=[25,90])
fig.show(renderer='notebook')
```

## Logs

<details>

<summary>Console output</summary>

<p>

```
VM369:4 UI PostOffice Received IPyWidgets_mirror_execute
VM369:4 UI PostOffice Received IPyWidgets_msg
VM369:4 UI PostOffice Received IPyWidgets_msg
VM369:4 UI PostOffice Received IPyWidgets_msg
VM369:4 UI PostOffice Received IPyWidgets_msg
VM369:4 UI PostOffice Received IPyWidgets_msg
VM369:4 UI PostOffice Received IPyWidgets_msg
VM384:5 Uncaught TypeError: require.undef is not a function
    at <anonymous>:5:17
    at S (notebookWebviewPreloads.js:3)
    at notebookWebviewPreloads.js:3
(anonymous) @ VM384:5
S @ notebookWebviewPreloads.js:3
(anonymous) @ notebookWebviewPreloads.js:3
async function (async)
(anonymous) @ notebookWebviewPreloads.js:3
$.outputs.set.queue @ notebookWebviewPreloads.js:3
enqueue @ notebookWebviewPreloads.js:3
(anonymous) @ notebookWebviewPreloads.js:3
postMessage (async)
(anonymous) @ main.js:833
(anonymous) @ host.js:27
```

</p>
</details>

**Comment by rchiodo** [comment]
Please see this issue here on using something other than the default renderer for plotly:
https://github.com/microsoft/vscode-jupyter/issues/4364

**Comment by jackthepanisher** [comment]
@rchiodo this issue is specifically about the differences between the old custom notebook editor and the new preview notebook editor. It is not really clear what the expected behavior should be. Is it supposed that 'vscode' is the only supported renderer type when using Plotly with VS Code? Why does the 'notebook' renderer work with the old notebook editor and not with the new notebook editor. Coming from the stable version of VS Code and the Python / Jupyter plugins (which uses the old notebook editor) this seem like a regression when switching to the new notebook editor.

**Comment by rchiodo** [comment]
> Why does the 'notebook' renderer work with the old notebook editor and not with the new notebook editor. Coming from the stable version of VS Code and the Python / Jupyter plugins (which uses the old notebook editor) this seem like a regression when switching to the new notebook editor.

I don't know for sure, but my guess is that plotly has code in it to detect some of the things we had in the DOM for our old editor. If it's not working with the new notebook editor with a renderer type of 'notebook', then I'd guess they need to update whatever they were doing before to work with the new editor. AFAIK, it's never worked with anything other than 'vscode'.

Looking at the console output, it looks like a renderer type of 'notebook' assumes it can use require.js (which is not there in the VS code case).

![image](https://user-images.githubusercontent.com/19672699/122998886-70f08a00-d362-11eb-9126-9a4d9f548e62.png)

**Comment by rchiodo** [comment]
This PR might make it work again:

https://github.com/microsoft/vscode-jupyter/pull/6318

**Comment by jackthepanisher** [comment]
Looks promising. I tried to compare both cell outputs for new vs. old notebook editor but apart from some styling change and positional movements there was no real difference in the generated output. So it looks like the old notebook editor does support the require function somehow (?). I don't have enough insight but I would assume that's independent from Plotly.

**Comment by IanMatthewHuff** [comment]
@rchiodo and @jackthepanisher Does this look like the expected output? This is running with my PR change.
![image](https://user-images.githubusercontent.com/812783/123006680-e7928500-d36c-11eb-9398-e7f59da6b372.png)

**Comment by rchiodo** [comment]
@IanMatthewHuff Yep that's it. Thanks.

The notebook renderer also makes it possible for the animations to run. At least it does for me.

**Comment by rchiodo** [comment]
@jackthepanisher our next insiders build should have this fix in it. Probably in the next day or two.

**Comment by jackthepanisher** [comment]
That's good news. Thanks for the quick response and fix.

**Comment by jackthepanisher** [comment]
@rchiodo and @IanMatthewHuff I have applied the changes to my 1.57.1 production setup of VS Code with Jupyter extension v2021.6.999 and it works like a charm.

**Comment by jackthepanisher** [comment]
It seems like there is an issue with opening a notebook containing cell output in 'notebook' renderer mode. The output stays blank and only shows up again when re-running the cell. Do you guys want me add logs here or create a new issue?

**Comment by rchiodo** [comment]
> It seems like there is an issue with opening a notebook containing cell output in 'notebook' renderer mode. The output stays blank and only shows up again when re-running the cell. Do you guys want me add logs here or create a new issue?

Please create a new issue. I'm guessing it requires our kernel to run something first as 'require.js' is loaded as part of our kernel loading.
