### ISSUE TITLE
Lost text focus after "Ctrl-Enter" is pressed on jupyter notebook

### ISSUE THREAD

**Issue by ws1088** [microsoft/vscode-jupyter#6337]
## Environment data

-   VS Code version: 1.57
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.999406279
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows 10, Mac, and Linux
-   Python and/or Anaconda version: 3.7.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Jupyter server running: Local and Remote 

## Expected behaviour

Should be like previous versions (before 1.57.0), when pressing "Ctrl-Enter" to run a cell, the text focus should remain in that some cell's text area, getting ready for users to add/change code and rerun.

## Actual behaviour

Focus is lost

## Steps to reproduce:

1. open a jupyter notebook
2. type `print(1)`
3. press "Ctrl-Enter" to run the cell

**Comment by joyceerhl** [comment]
@ws1088 The previous behavior where text remains in the editor after ctrl+enter was actually a bug, as reported by another user: https://github.com/microsoft/vscode-jupyter/issues/6198 We fixed this by contributing ctrl+enter tied to a custom command, `jupyter.notebookeditor.keybind.executeCell`.

You can go back to the old ctrl+enter behavior by opening the keyboard shortcuts configuration page:
![image](https://user-images.githubusercontent.com/30305945/122710893-13e7bd80-d216-11eb-9a76-366b0096f465.png)

And changing the keybinding for the following command to anything else:
![image](https://user-images.githubusercontent.com/30305945/122710837-f87cb280-d215-11eb-98da-6f2db2f9ee56.png)

**Comment by ws1088** [comment]
thanks. it's interesting how different use cases consider something as a bug or not. personally i like ctrl-enter to remains in the cell focus because most of the time i would write some code and test it out. maybe 5% of the time when i press ctrl-enter i would want to loose focus.
