### ISSUE TITLE
Latest version for engine "^1.57.0"

### ISSUE THREAD

**Issue by indyspike** [microsoft/vscode-jupyter#6338]
The current version history on the marketplace lists 2021.7.xxx versions. The marketplace changelog lists 2021.6.xxx

The oldest version visible lists "1.58.0-insider" as its engine version in the manifest. I'm trying to download a version for 1.57.1 for offline installation.

I have also mentioned having the ability to select code engine version in microsoft/vsmarketplace#43 so those of us needing offline installation can get the right versions.

**Comment by DavidKutu** [comment]
Sorry for the trouble @indyspike. You can download our latest stable version (for 1.57) here:
https://github.com/microsoft/vscode-jupyter/suites/3003065461/artifacts/67928509

I'll also push your issue on the vscode repo to have the option in the marketplace.

**Comment by indyspike** [comment]
Thanks for that. Seems like a few issues with /enhancements needed in the marketplace. For some (like this) the mechanism must be there in the background, it just needs an element to enable access to that feature from the marketplace. (Out of scope for this repo, just musing along with my thanks).
