### ISSUE TITLE
Gray screen

### ISSUE THREAD

**Issue by svh02** [microsoft/vscode-jupyter#6339]
## Environment data

-   VS Code version: 1.57.1
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.999406279
-   Python Extension version (available under the Extensions sidebar): 2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: W10
-   Python and/or Anaconda version: 3.8.8 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): CONDA
-   Jupyter server running: Local | Remote | N/A: Local

## Expected behaviour

Showing notebook while running

## Actual behaviour

I was training an RL model usign stable lines 3 with pytorch cuda versión. suddently during training the screen turned gray. I cannot even see the taskbar for saving the model or stoping the kernel.
It says the cell is still running, but I do not know for shure. I think it is since the GPU's fans are still working hard.

![image](https://user-images.githubusercontent.com/70783371/122803195-e6d5f200-d28b-11eb-8dcc-f0a9dc95f601.png)

 

## Steps to reproduce:

Not sure, I have trained the same model before without issues

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
Output is empty
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DavidKutu** [comment]
Sorry for the trouble @svh02. 

Could you upload the output from the `Jupyter` output panel and the Developer Tools panel? (Help | Toggle Developer Tools, and View | Output)

Thanks.

**Comment by svh02** [comment]
Hi David, 
I restarted de app and is now working fine. So I wont be able to upload the output.
Thanks for the answer. I will keep working and hopefully it won't cause any more trouble

**Comment by DavidKutu** [comment]
Good to know that its working!
Feel free to reopen this issue if it happens again.
