### ISSUE TITLE
Can't open terminal on Linux remote server from Windows, and got the error that I can't open jupyter notebook.

### ISSUE THREAD

**Issue by sherry975** [microsoft/vscode-jupyter#6343]
The VSCode is installed on Windows and I use it to connect to a remote server. It worked perfectly until last week. First, the terminal of the remote Linux server on VSCode didn't respond. Then, today I updated the VSCode, the terminal still didn't work and it came even worse that I can't open the Jupyter notebook and it said there was something wrong with the Jupyter and Python extension.
 
I tried to open the jupyter notebook, but it raised an error.  Then I tried to create a new jupyter notebook, it says:  "Command 'Jupyter: Create New Blank Notebook' resulted in an error (command 'jupyter.createnewnotebook' not found)"

## Environment data

-   VS Code version: 1.57.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.2.603412351
-   Python Extension version (available under the Extensions sidebar): v2021.2.633441544
-   OS (Windows | Mac | Linux distro) and version: VS code on windows to ssh remote Linux server
-   Python and/or Anaconda version: 3.8 / 4.9.2 (both on Linux)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local ->Remote

**Comment by claudiaregio** [comment]
Hi @sherry975 Can you please update to the latest versions of the Jupyter extension and the Python extension and let us know if the problem is still persisting for you?
