### ISSUE TITLE
Disable Jupyter kernel shut down after exit vscode in remote development 

### ISSUE THREAD

**Issue by hawktang** [microsoft/vscode-jupyter#6350]
## Environment data

-   VS Code version: 1.57.1
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.999 (16 June 2021)
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Mac 11.4 remote Ubuntu 20.4
-   Python and/or Anaconda version: 3.9.5 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): remote mini 4.8.3
-   Jupyter server running: Local | Remote | remote

## Expected behaviour

In remote development, after exit vs code, the kernel should persist. And after reopen vs code and reconnect to remote server, kernel should untouched and work can contiue. 

## Actual behaviour

After exit vs code or network lost, the reconnection will restart the kernel and all work would gone.

I tried to use manually setup jupter server instead of autostart jupyter server, the kernel still got restarted.

![image](https://user-images.githubusercontent.com/2004071/122891516-2a595a80-d377-11eb-90ec-8f97abe8fe04.png)

## Steps to reproduce:

As above.

**Comment by IanMatthewHuff** [comment]
@hawktang For your remote scenario do you mean a remote vscode extension? Or are you using the "Specify local or remote Jupyter server for connections" command option in VS Code? If you are using the second option with a manually started up Jupyter server those kernels should be persisted. I just tried this myself and I see the kernels being preserved on VS Code shut down:
![image](https://user-images.githubusercontent.com/812783/123018832-26800500-d384-11eb-9f93-0c392810bab6.png)
(note there are kernels shut down in the above picture, but they are the restart kernels. The main ones are still active.
And when restarting vscode the existing session was available in the session list:
![image](https://user-images.githubusercontent.com/812783/123018945-5f1fde80-d384-11eb-9e1a-8fa32c9fde4d.png)

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
