### ISSUE TITLE
Resolve DataFrame horizontal scrollbar issue on Jupyter side

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#6354]
Per the issue here: https://github.com/microsoft/vscode/issues/123816

Jupyter extension will look at providing the styles to size dataframe table output. Will also look at if this needs to be released in a point fix.

**Comment by rebornix** [comment]
<img width="539" alt="image" src="https://user-images.githubusercontent.com/876920/123042550-d9b02480-d3ab-11eb-9b65-fbc24878d926.png">

With `width: 100%` removed on table, it's actually an easy fix in the core https://github.com/microsoft/vscode/commit/d111d967b72748bbd125d3392eeebc52718a7c07

**Comment by CWen001** [comment]
@rebornix Sorry to have a question here. What color theme is used in this screencast? I have tried a few light color themes and the pandas output is not that pleasing. Yours looks great.
