### ISSUE TITLE
Disable notebook tab focusing upon cell completion

### ISSUE THREAD

**Issue by rxhh** [microsoft/vscode-jupyter#6356]
Issue:
A very common use case is to run an entire Jupyter notebook and switch tabs to work on something else while waiting. VSCode currently refocuses the notebook tab upon each cell completing. This is very workflow disruptive and often leads to user errors, such as accidentally deleting a cell via hotkeys when the cell comes into focus.

Feature:
Setting to disable cell focusing on cell run completion.

**Comment by IanMatthewHuff** [comment]
@rxhh If you have a chance could you take a peek at the UI in VS Code - Insiders? (it's a clean SxS install next to VS Code stable). That's the new UI that we are rolling out to all users in the nearish future. Doesn't have this same issue that is hitting you.

At this point we are unlikely to fix it in the current implementation as we believe the new UI should solve this best when it's fully rolled out.

**Comment by rxhh** [comment]
I just tried the new UI and can confirm that the issue is not present. Thank you!
