### ISSUE TITLE
Native Notebooks - List kernels as new notebook options

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#6359]
Changes were recently made to the extension such that we can now return kernels on disc quickly. 
After a new notebook is created via the command palette, let's go ahead and make the drop down list in the quick pick be the kernels available as opposed to the extension options.

**Comment by greazer** [comment]
Need some thought about a spec on this.

**Comment by rchiodo** [comment]
@claudiaregio Is this still something we need to do?

**Comment by DonJayamanne** [comment]
I don't think anything needs to be done here anymore, closing this.
@claudiaregio if you still feel something is required, please feel free to reopen this with a comment or please create a new issue

**Comment by claudiaregio** [comment]
I would still recommend this given it's the flow that Jupyter has and research in the past showed users not realizing a kernel had been selected but I think it's best if @minsa110 evaluates this as she is focused on the getting started flow.
