### ISSUE TITLE
jupyter extension without picture in interactive pattern

### ISSUE THREAD

**Issue by zpliu1126** [microsoft/vscode-jupyter#6373]
## Environment data

-   coder-server version: 3.10.2
-   ms-toolsai.jupyter:  v2021.6.832593372
-  ms-python.python: v2021.5.926500501
-   OS and version: centos7
-   Python version (& distribution if applicable, e.g. Anaconda): python3.6.5

It do'nt show me the picture in interactive jupyter.

![image](https://user-images.githubusercontent.com/39325949/123212513-7cc18500-d4f7-11eb-95c6-556742b6569d.png)

**Comment by DonJayamanne** [comment]
Thanks for filling this issue. Unfortunately code-server isn't supported, never not really sure what's going on here. I believe it's a problem with code server (disgusting contents in the iframe inside the notebook).
