### ISSUE TITLE
Implement %pdb support in notebooks

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6374]
Assuming we have debugging working can %pdb also work? Not sure what this does at the moment, but user's have been asking for this.

**Comment by evanphilipsmith** [comment]
The `%pdb` magic command automatically calls the interactive debugger when an exception is raised. 

Source: https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-pdb

**Comment by dynamicwebpaige** [comment]
The `%pdb` magic command is [often used with Jupyter and ipython notebooks](https://stackoverflow.com/questions/16867347/step-by-step-debugging-with-ipython/43413318#43413318) as a recommended best practice; and there are [several related questions on StackOverflow](https://stackoverflow.com/search?q=%22%25pdb%22+visual-studio-code), about pdb + VS Code. The Python debugger is [bundled with Python core](https://docs.python.org/3/library/pdb.html) - it definitely makes sense to support this.

* [How to use pdb(Python debugger) in vscode IDE's debugger?](https://stackoverflow.com/questions/65677725/how-to-use-pdbpython-debugger-in-vscode-ides-debugger)
* [Using the Python debugger with VS Code](https://stackoverflow.com/questions/54615398/using-the-python-debugger-with-vs-code)
* [Set breakpoint in imported python module in vs code](https://stackoverflow.com/questions/57373359/set-breakpoint-in-imported-python-module-in-vs-code)
* [Break on error/exception with python remote development in Visual Studio Code (vscode)](https://stackoverflow.com/questions/60288231/break-on-error-exception-with-python-remote-development-in-visual-studio-code-v)
* etc.

**Comment by roblourens** [comment]
This is actually supported, via quick input

**Comment by rchiodo** [comment]
> This is actually supported, via quick input

Do you have more details? %pdb is supposed to trap exceptions and show them in the debugger. At least I think that's how it works.

**Comment by roblourens** [comment]
When an exception occurs, I see a quick input show up which lets me enter pdb commands. In Jupyter lab, an input box appears below the cell for pdb commands. So it seems to work as well as Jupyter lab. I don't expect it to integrate with the vscode debugger or anything like that.

**Comment by micimize** [comment]
It seems unlikely to me that dropping into the full vscode from `%pdb` makes sense or is feasible – it would be confusing for `%pdb` not to invoke/work like `pdb`.

However, it might make sense to open a new issue to discuss/investigate a "drop into vscode debugger from running notebook" feature more thoroughly if that doesn't currently exist (or maybe better document how to set it up if it does).

**Comment by roblourens** [comment]
Can you explain more about what you're looking for? Debugging notebooks does exist with the "Debug cell" command

**Comment by micimize** [comment]
Ahh, ok – no that is perfect. For some reason it wasn't clear to me that [Debug Cell](https://code.visualstudio.com/docs/datascience/jupyter-notebooks#_debug-cell) used the existing notebook kernel.
