### ISSUE TITLE
Jupyter Notebook Theme not Colored Properly in WSL

### ISSUE THREAD

**Issue by BirkhoffG** [microsoft/vscode-jupyter#6380]
## Environment data

-   VS Code version: 1.57.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.999662501
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows WSL 2 (Ubuntu)
-   Python and/or Anaconda version: v3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

## Expected behaviour

The jupyter notebook should color the code according to user's chosen theme.

## Actual behaviour

The jupyter notebook does not color in the WSL environment.

## Steps to reproduce:

1. Choose a theme (in my case, I choose `azemoh.one-monokai`).
2. lanch WSL 2 (Ubuntu) and type `code .`.
3. I open a random notebook and the notebook does not seem to color the code properly (as you can see the left window in the image below).
4. I then copy this notebook to Windows file system and open vscode in Windows environment.
5. Without any changes on vscode's setting, I find jupyter notebook colored the code properly when openning from Windows enviornment (without WSL remote connection). 

![img](https://user-images.githubusercontent.com/26811230/123385859-97affa00-d5c8-11eb-9158-81dca01af0a4.png)
(Left: open through WSL 2, Ubuntu version; Right: open through Windows)

## Notes

I have seens issues #4899,  #646 reporting the similar bugs, and the developers claim to fix them in both issues. However, I still encounter this problem and this bug does not seem to be fixed.

**Comment by claudiaregio** [comment]
Closing as this will be fixed when we migrate completely over to Native Notebooks
