### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by teymour-aldridge** [microsoft/vscode-jupyter#6381]
- Issue Type: `Performance`
- Extension Name: `jupyter`
- Extension Version: `2021.6.999662501`
- OS Version: `Darwin x64 19.6.0`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/04/v7v7s5n97lx_fkl5y_ywb8s00000gn/T/ms-toolsai.jupyter-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by IanMatthewHuff** [comment]
If you attach the file we can reopen this issue. But we can't look into this without the file.
