### ISSUE TITLE
Kernel is not reloading updated anaconda environment 

### ISSUE THREAD

**Issue by aadhavanshines** [microsoft/vscode-jupyter#6392]
Issue Type: <b>Bug</b>

https://github.com/aadhavanshines/Queries/issues/1#issue-931598415

Please follow below steps to reproduce:

- Install anaconda in pc

- Install Jupyter extension in visual studio code

- Select Python 3.8 enviroment

- Open .pynb and select 3.8 python intrepreter

Issue when kernel selected it shows previous installed environment such as 3.9 but i need 3.8 enviroment which is recently updated
but it's not listing in kernel drop down
Please help to refresh kernels in VS code

Expected Results  kernel must reload existing anaconda env
Actual : Kernel listing previous uninstalled env

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (0.42GB free)|
|Process Argv|--crash-reporter-id a69d097c-d6e5-4f03-ba2f-c0acdb9bd42c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
vscode-ai|ms-|0.6.23
vscode-ai-remote|ms-|0.3.0
azure-account|ms-|0.9.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30329803
binariesv615:30325510

```

</details>

**Comment by claudiaregio** [comment]
@aadhavanshines Could you please provide the Jupyter and Python extension versions you are working with? Could you provide a screenshot of where you are clicking when you are trying to change the kernel and a screenshot of the drop down list produced?

**Comment by aadhavanshines** [comment]
@claudiaregio
Please find version details
![image](https://user-images.githubusercontent.com/86610936/123736427-b3fcb100-d8be-11eb-8293-0264a10d7948.png)

Please find kernel details, it's showing 3.9.5 64 bit ('myenv':conda) which i replaced with 3.8.8 64 bit ('myenv':conda),it's not reloading with current installed environments

![image](https://user-images.githubusercontent.com/86610936/123736598-05a53b80-d8bf-11eb-9b2c-cbd7c81bba96.png)

**Comment by IanMatthewHuff** [comment]
@aadhavanshines Does this issue persist after a Reload of the window? We get available environments from the python extension, which has some degree of caching. Sometimes it takes a reload to clear the cache.

If the issue persists after the reload. Could you change the setting Jupyter->Logging->Level to 'debug' and then after a reload and reproing the issue (run all the way until the incorrect change kernel dialog) save out everything in the Jupyter section of the output window. You can save that output in a file and attach that to a comment here, that has the info we would need to debug this.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
