### ISSUE TITLE
VS Code Fails to Save

### ISSUE THREAD

**Issue by eric-mc2** [microsoft/vscode-jupyter#6394]
Issue Type: <b>Bug</b>

This happens often when editing a Jupyter notebook. 

Steps:
1. Open and edit an .ipynb file with the Jupyter extension enabled.
2. Save the file.
3. Open the integrated source control panel, make some commits, view a diff, close the diff view. (I think the interaction with the diff view causes the problem).
4. Continue editing the .ipynb.
5. Ctrl+S or File->Save As.

Observed:
Current changes in the editor are not written to disk. Save-As writes the file's previously saved state to disk. No error is shown. 

Related:
This doesn't duplicate microsoft/vscode#114588 which is specific to untitled files. Might duplicate microsoft/vscode#126561.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
mdmath|goe|2.7.4
latex-workshop|Jam|8.19.2
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
vscodeintellicode|Vis|1.2.14
</details>

**Comment by claudiaregio** [comment]
Hi @eric-mc2, could you please provide the Jupyter output content when the issue occurs? 
Do you know if you are working with the Native Notebook interface? If you are unsure pasting a screenshot of your notebook would help us determine that.

**Comment by eric-mc2** [comment]
Hi @claudiaregio, 
I can consistently reproduce the issue. It seems to be triggered by editing the working version while the diff is open. I'm not sure which interface I'm using. The screenshot has more detailed steps.
<img width="1438" alt="vscode_bug_2" src="https://user-images.githubusercontent.com/53244793/123856676-fc2fc980-d8e6-11eb-828f-41f35fb3cf6b.png">

[jupyter-output.txt](https://github.com/microsoft/vscode-jupyter/files/6735924/jupyter-output.txt)

**Comment by claudiaregio** [comment]
@eric-mc2 This should be fixed when we migrate to the native notebook interface completely. Does it work if you click the save button in the notebook toolbar or if you close the diff and try to save?

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed with new native support for editing notebooks. To opt into that experience see: https://github.com/microsoft/vscode-jupyter/wiki/Introducing-Native-Notebooks.
