### ISSUE TITLE
Execute cells FAILED on Kubernetes pod

### ISSUE THREAD

**Issue by seyuboglu** [microsoft/vscode-jupyter#6398]
Issue Type: <b>Bug</b>

When running a cell in an **existing notebook** (_i.e._ one that is saved somewhere) on a Kubernetes pod, the cell does not execute. The following is logged to Remote Extension Host:
```
[2021-06-29 04:51:14.316] [exthost] [error] NotebookController[1] execute cells FAILED {}
```
Furthermore, the output in developer tools shows:
```
Error: duplicate execution for vscode-notebook-cell://k8s-container...
```
I can provide the full output if that would be helpful. 

Note: In a fresh, unsaved notebook created using `Jupyter: Create new blank notebook`, the cells execute without problem. The problem only manifests once the notebook is saved. 

Steps to reproduce:
1. Open VSCode on a Kubernetes pod
2. Create a blank notebook
3. Save the notebook to disk somewhere
4. Attempt to run the first cell

Extension version: 2021.6.999662501
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.89+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 3253bfa9-f4f2-4dc6-9afe-91a2465ce2f7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|pod-sabri in pod-sabri (gcr.io/hai-gcp-fine-grained/default)|
|OS|Linux x64 5.4.89+|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (8 x 2199)|
|Memory (System)|29.40GB (12.80GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
vscextlangct:30322307
binariesv615:30325510

```

</details>

**Comment by ad12** [comment]
I'm having this issue too

**Comment by IanMatthewHuff** [comment]
@seyuboglu Could you actually pull the logs from the Jupyter tab of the VS Code output window? That as well as the rest of the output from the developer tools would be helpful. Odd that it's not having an issue until after it's saved.

**Comment by seyuboglu** [comment]
Here are the logs: 
[jupyter_output_logs.txt](https://github.com/microsoft/vscode-jupyter/files/6737518/jupyter_output_logs.txt)
[dev_tools_log.txt](https://github.com/microsoft/vscode-jupyter/files/6737528/dev_tools_log.txt)


Other things to note:
I have the following in my workspace settings:
```
"jupyter.jupyterCommandLineArguments": [
			"--no-browser",
			"--allow-root",
			"--config=/home/sabri/.jupyter/jupyter_notebook_config.py",
		],
```
and I updated my Jupyter config via
```
jupyter notebook --generate-config

echo "c = get_config()
c.NotebookApp.ip = '*'
c.NotebookApp.open_browser = False
c.NotebookApp.port = 8004" >> /home/sabri/.jupyter/jupyter_notebook_config.py
```

**Comment by IanMatthewHuff** [comment]
Thanks for the logging. It does look to me like it's failing to find an open port at the port specified (rolling from 8004 to 8011):
> http://pod-sabri-t4-4:8011/

I don't believe that's the issue though. It looks to me like this is the relevant error:
```
Info 2021-06-30 02:06:22: Cell Index:0, state:undefined, exec: 17. Ready to execute
Info 2021-06-30 02:06:22: Cell Index:0, state:undefined, exec: 17. Before Execute individual cell
Info 2021-06-30 02:06:22: Cell Index:0, state:undefined, exec: 17. Start execution
Info 2021-06-30 02:06:22: Cell Index:0, state:undefined, exec: 17. After Execute individual cell undefined
Error 2021-06-30 02:06:22: Failed to execute cells in CellExecutionQueue Error: Can't apply edits to unknown notebook model: vscode-remote://k8s-container%2Bcontext%3Dgke_hai-gcp-fine-grained_us-west1-a_cluster-1%2Bpodname%3Dpod-sabri-t4-4%2Bnamespace%3Ddefault%2Bname%3Dpod-sabri%2Bimage%3Dgcr.io%252fhai-gcp-fine-grained%252fdefault/home/sabri/code/domino/scratch/sabri/Untitled.ipynb
    at xr.$applyEdits (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2524:13873)
    at r._doInvokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1832:11905)
    at r._invokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1832:11597)
    at r._receiveRequest (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1832:10259)
    at r._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1832:9062)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1832:7166
    at n.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at a.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:16288)
    at i._receiveMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:21546)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:18432
    at n.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at u.acceptChunk (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:13649)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:12997
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:634:139050
    at n.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at FileReader._fileReader.onload (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:634:137667)
Info 2021-06-30 02:06:22: Cancel pending cells
Info 2021-06-30 02:06:22: Install Missing Dependencies, Class name = w, completed in 450ms, has a falsy return value, Return Value: undefined
```

**Comment by IanMatthewHuff** [comment]
Looks very similar to this issue:
https://github.com/microsoft/vscode/issues/119891

That URI looks a touch odd to me for the file:
`vscode-remote://k8s-container%2Bcontext%3Dgke_hai-gcp-fine-grained_us-west1-a_cluster-1%2Bpodname%3Dpod-sabri-t4-4%2Bnamespace%3Ddefault%2Bname%3Dpod-sabri%2Bimage%3Dgcr.io%252fhai-gcp-fine-grained%252fdefault/home/sabri/code/domino/scratch/sabri/Untitled.ipynb`

@roblourens Looks like you had some context on the linked issue. Anything look off on this URI here?

**Comment by roblourens** [comment]
There's another issue with that sort of URI https://github.com/microsoft/vscode-remote-release/issues/5250. It's possible that the weird URI format could cause an issue like this too. Sounds like it will be fixed in the Containers extension

**Comment by IanMatthewHuff** [comment]
Looks like this has been fixed with the most recent VS Code + Containers Extension release. Please ping here if you are still seeing it with everything updated.
