### ISSUE TITLE
Custom Editor：Hit "Z" cannot reappear a deleted cell.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/vscode-jupyter#6399]
## Environment data
![image](https://user-images.githubusercontent.com/82852072/123764309-3e610700-d8f7-11eb-8fbd-3affd8f230ea.png)

## Expected behaviour

Hit Z and verify a deleted cell reappears.

## Actual behaviour

Nothing appears after hitting "Z".

**Comment by IanMatthewHuff** [comment]
@ttSpace Quick question. I'm surprised that you have that UI on a VS Code insiders install. Did you explicitly opt out from the new Native Notebook UI? That should be the default in insiders.

**Comment by ttSpace** [comment]
@IanMatthewHuff I follow https://stackoverflow.com/questions/67142271/visual-studio-jupyter-notebook/67145446#67145446 to enable Custom Editor in VS Code Insiders.

**Comment by IanMatthewHuff** [comment]
@ttSpace Understood. I'm going to close this issue now as it relates only to the old UI. We're going to be rolling out the new UI to all customers in the very near future. So fixed to the old UI will only be for totally broken functionality. Sorry about that.
