### ISSUE TITLE
Input runs as a popup, not as print

### ISSUE THREAD

**Issue by s-e1** [microsoft/vscode-jupyter#6400]
I just updated the extension. 
When I ask for an input, it appears on the top of the screen, and not under the cell like a standard print statement, like before.

**Comment by claudiaregio** [comment]
Hi @s-e1, Could you please provide some additional details on the issue you are experiencing? 
Helpful information includes steps to reproduce, expected behavior vs. actual behavior, pictures or screen recordings when applicable. (https://www.screentogif.com) It would be also helpful to have the VS Code version, Jupyter extension version and Python extension version.

**Comment by rchiodo** [comment]
The input at the top has been there for a very long time, not sure we ever supported input inline in a cell. 

Here's the submission that made that work:
https://github.com/microsoft/vscode-jupyter/commit/ab4d796d4defe5c02ea57b63af29703c9d82ed3f

**Comment by s-e1** [comment]
> 
> 
> Hi @s-e1, Could you please provide some additional details on the issue you are experiencing?
> Helpful information includes steps to reproduce, expected behavior vs. actual behavior, pictures or screen recordings when applicable. (https://www.screentogif.com) It would be also helpful to have the VS Code version, Jupyter extension version and Python extension version.

@claudiaregio 
vsc version1.57.1
python version 2021.6.944021595
jupyter version 2021.6.999662501
I expected the request for "enter an integer" to be printed under the cell, not on the top of the screen, as it did until now.
Current screenshot [at top]:
![Screenshot (91)](https://user-images.githubusercontent.com/49290335/123868137-f7dfcc80-d937-11eb-858a-cf4ffa6fe79a.png)
Previous screenshot [below cell]:
![Screenshot (92)](https://user-images.githubusercontent.com/49290335/123868153-fc0bea00-d937-11eb-95d9-e43871644208.png)

**Comment by rchiodo** [comment]
Not sure how the input was asked for before then. Can you show the box for the input in the old version? What extensions did you have installed before? Somebody else might have been handling that input as our extension has always asked for it from the top.

**Comment by s-e1** [comment]
> 
> 
> Not sure how the input was asked for before then. Can you show the box for the input in the old version? What extensions did you have installed before? Somebody else might have been handling that input as our extension has always asked for it from the top.

@rchiodo 
I had the same extensions as now, but without the latest update. I have used it many times and it always showed under the cell.
![Screenshot (94)](https://user-images.githubusercontent.com/49290335/123873857-d97dcf00-d93f-11eb-84f3-489f7a748391.png)

**Comment by rchiodo** [comment]
Do you have a screeenshot of the input box in the old version? It might give me some clue as to where it came from.

I went back 4 months and this is what we show:

![image](https://user-images.githubusercontent.com/19672699/123875004-cfcb7b80-d8ed-11eb-8ccf-90612ad38c4f.png)

**Comment by rchiodo** [comment]
What other extensions do you have?

**Comment by s-e1** [comment]
I don't have other screenshots. What I have is from the previous time it was run, if it's run again it shows the input on top.
The only other python extension I have is pylance 2021.6.3

**Comment by rchiodo** [comment]
If it was from another extension, it wouldn't be a python extension. What other extensions do you have other than the python extensions?

**Comment by s-e1** [comment]
angular language service, css formatter, live server, php intelephense

**Comment by greazer** [comment]
Sorry, @s-e1, even if there was a scenario in the past when inputs were appearing below the cell, they no longer do and we do not have plans on changing it.
