### ISSUE TITLE
Double-clicking notebook behavior felt unusual

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-jupyter#6401]
Testing https://github.com/microsoft/vscode/issues/127361

Notebooks open properly and I'm getting output:

![image](https://user-images.githubusercontent.com/25310137/123827521-8a8b5780-d8b5-11eb-814b-b73e44b7ed73.png)

One interesting experience I noticed was that when opening a notebook from my file system, if I click on it once from the Explorer, the notebook opens (although in the temporary/italic tab state):

![image](https://user-images.githubusercontent.com/25310137/123827709-b7d80580-d8b5-11eb-9acb-10998c5a50df.png)

And when I clicked on it twice from the Explorer, it opened two versions of the notebook (one with the code & markdown rendered, one with the raw source showing, and the latter is in focus):

![image](https://user-images.githubusercontent.com/25310137/123827871-d8a05b00-d8b5-11eb-86db-1585ea9e30dc.png)

Perhaps other users expect this, but I was expecting to just get the first screenshot in non-italics (i.e. Background.ipynb with the code and markdown cells rendered in focus and the tab now not in italics). Is there a reason double-clicking opens up the "source" of the notebook in the forefront when I feel like it opens up the current file more permanently in other scenarios? 

Also apologies if I'm using incorrect notebook terminology to distinguish here! Please also feel free to close if this has already been discussed/tested/decided at length, just wanted to open an issue for something that felt unusual to me.

**Comment by bamurtaugh** [comment]
cc @DonJayamanne since you are the author of the testing issue and I don't believe I have the ability to edit assignees in this repo.

**Comment by IanMatthewHuff** [comment]
@bamurtaugh Thanks for filing. That's an odd issue, good catch. That is not intended, so I'm not sure what is happening there yet, but I also reproed the same thing (took a try or two on the timing).

![image](https://user-images.githubusercontent.com/812783/123886548-8fc3c300-d904-11eb-8916-25740f98c1f8.png)

**Comment by joyceerhl** [comment]
I believe Logan has fixed this in VS Code earlier today (editor service bug IIRC). The fix should go out in tonight's Insiders so feel free to reopen if it's not fixed tomorrow.
