### ISSUE TITLE
Support spawning notebook servers for JupyterHub

### ISSUE THREAD

**Issue by TomAugspurger** [microsoft/vscode-jupyter#6402]
This is a bit similar to https://github.com/microsoft/vscode-jupyter/issues/1668, but I couldn't tell if that was a bug report or a feature request.

The goal of this feature request is to make it easier to work with a remote Jupyter Kernel that's managed by JupyterHub. Currently, users need to

1. create an API token through JupyterHub (first time only, see https://github.com/microsoft/vscode-jupyter/issues/6035 for an alternative)
2. Log into the Hub and start a notebook server
3. Connect to the started notebook server from VS Code

To eliminate the need for step 2, I wonder if VS Code could start the notebook server for the user? JupyterHub's REST API supports [spawning user servers](https://jupyterhub.readthedocs.io/en/stable/_static/rest-api/index.html#path--users--name--server). Would it be possible for VS Code to make a POST request to that endpoint, using the user's token, to spawn a notebook server if it isn't already running?

```console
$ curl -X POST -H "Authorization: token <user-token>" https://<hub-url>/hub/api/users/<username>/server  
```

There are some complications around things like feedback as the server is starting and profiles, but I think just having the basics of starting up a notebook server for the user would be fantastic. Thanks!

**Comment by IanMatthewHuff** [comment]
@TomAugspurger Thanks for the feedback. Seems like something that we'd want to support.

**Comment by choldgraf** [comment]
Just a note from me that I think this would be awesome. ✨

**Comment by DonJayamanne** [comment]
Closing this issue as there haven't been enough upvotes on this, and we believe this is possible with the API we have today (i.e. someone can contribute an extension that would make this possible)
 
Could also be closed in favour of https://github.com/microsoft/vscode-jupyter/issues/12268
