### ISSUE TITLE
Interactive Window - picks the wrong kernel

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6407]
Testing microsoft/vscode#127378

Open python file
Select interpreter
Run cell

Expected:
Cell runs with selected kernel

Actual:
![image](https://user-images.githubusercontent.com/19672699/123847522-879b6180-d8cb-11eb-8314-5615b91abaa3.png)

My active interpreter is actually this one:
![image](https://user-images.githubusercontent.com/19672699/123847560-93872380-d8cb-11eb-9588-96f2617f8bae.png)

**Comment by joyceerhl** [comment]
Debugged this with Rich offline. This was because Rich had `disableZMQ` in settings.json, and same behavior observed for native notebooks as well. After removing that setting everything worked fine.

**Comment by rchiodo** [comment]
This is really a dupe of #6409
