### ISSUE TITLE
[Endgame testing] Breakpoints can't be set before debugging

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-jupyter#6408]
Testing microsoft/vscode#127362

## Expected behaviour

I can set breakpoints before debugging 

## Actual behaviour

I have to start debugging in order to set breakpoints

**Comment by roblourens** [comment]
I'd like to be able to set breakpoints outside of a debug session, but the breakpoint margin takes a lot of space. Should look into this in July and see if we can make it look good

**Comment by roblourens** [comment]
Fixed this last month
