### ISSUE TITLE
Cannot select any kernel to run

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6409]
No matter what kernel I pick from my dropdown of kernels, I'm always getting this message:

![image](https://user-images.githubusercontent.com/19672699/123850479-ef06e080-d8ce-11eb-9a14-976bfcd2e585.png)

I have raw kernel turned off.

With raw kernel turned on, it picks the correct kernel.

**Comment by IanMatthewHuff** [comment]
Validated. Turned off kernel and launched from the IW with a few different envs.

**Comment by IanMatthewHuff** [comment]
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/0709edf2-547b-41e0-ab74-7e973098e301)
