### ISSUE TITLE
[Endgame testing] Changing kernel disables debugging

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-jupyter#6411]
Testing https://github.com/microsoft/vscode/issues/127362

## Expected behaviour

I debug in the venv kernel, switch to a diff't kernel, debugging is disabled. I switch back to the venv kernel and debug again.

## Actual behaviour

I debug in the venv kernel, switch to a diff't kernel, debugging is still enabled, but doesn't do anything. I switch back to the venv kernel and can no longer debug.

![recording (11)](https://user-images.githubusercontent.com/29464607/123854246-52930d00-d8d3-11eb-87b8-9aa23d2ee87b.gif)

**Comment by DavidKutu** [comment]
TODO: Check the context keys when changing kernels

**Comment by DavidKutu** [comment]
fixed alongside #7056.

If you don't have the requirements, a modal will ask you to update.
