### ISSUE TITLE
[Endgame testing] stopping at a temp file, debugging the call to a function defined in a diff't cell fails

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-jupyter#6413]
Testing https://github.com/microsoft/vscode/issues/127362
![recording (13)](https://user-images.githubusercontent.com/29464607/123857088-c256c700-d8d6-11eb-8019-99cb174f6e5b.gif)

**Comment by DavidKutu** [comment]
TODO: not all cells were dumped when appropriate. We should never show the temp files.

**Comment by DavidKutu** [comment]
this is fixed
