### ISSUE TITLE
Python controllers aren't registered fast enough

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6419]
Testing microsoft/vscode#127378

Opened IW with a python kernel
Reloaded window

Got this as my active kernel in the IW that was opened:
![image](https://user-images.githubusercontent.com/19672699/123848010-0ee8d500-d8cc-11eb-8a02-c93ac69cc502.png)

After a minute or so it switched to the correct kernel
![image](https://user-images.githubusercontent.com/19672699/123847911-f2e53380-d8cb-11eb-8f9a-c3afa69c7867.png)

**Comment by joyceerhl** [comment]
@rchiodo is that Julia kernel contributed by the Julia extension or by us? Are there any others in the list? I'm wondering if this is because we're rerunning our kernel discovery to reregister controllers, so the correct controller is initially unavailable.

**Comment by rchiodo** [comment]
It's a real kernel, so the julia kernel is contributed by us. And yes I suspect the julia kernel comes back first and the python one will come later. Don's work to have a placeholder kernel should solve this.

**Comment by joyceerhl** [comment]
This problem might also be alleviated by https://github.com/microsoft/vscode-jupyter/pull/6422
