### ISSUE TITLE
Support persistent raw kernel sessions

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6420]
Testing microsoft/vscode#127378

Create IW from a code lens
Reload VS code

IW has two sys infos in it after it starts up

![image](https://user-images.githubusercontent.com/19672699/123851384-f7abe680-d8cf-11eb-9065-dc0176c2680d.png)

**Comment by rebornix** [comment]
This is currently not supported and we might want to reconsider since we can restore history in IW now.

**Comment by amunger** [comment]
duplicate of #3998
