### ISSUE TITLE
Interactive window on reload will not associate with the same python file

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6421]
Testing microsoft/vscode#127378

Open interactive window using a code lens
Reload VS code
IW will reopen
Run a cell from the same file
A new IW will open. 

Expected: The same IW is used.

**Comment by joyceerhl** [comment]
Closing in favor of #6460 as we have disabled hot exit for the native interactive window so this specific bug won't hit any users
