### ISSUE TITLE
Interactive Window - switching kernels doesn't put up the switch kernel message until run a cell

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6424]
Testing microsoft/vscode#127378

Old IW would switch kernels and immediately tell you about it. The new one doesn't. 

I used that notification to tell when it was finished. And that it was okay to start running stuff.

**Comment by joyceerhl** [comment]
This is fixed. When you switch a kernel you now immediately get a progress notif and a placeholder sys info cell: 
![image](https://user-images.githubusercontent.com/30305945/131717068-e79adf88-af0e-44e4-a99e-a8fe8ae3f5f3.png)
