### ISSUE TITLE
"Running cells with {0} requires ipykernel" message has wrong interpreter `displayName`

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6425]
Testing microsoft/vscode#127378

This doesn't happen on a native notebook, but if I switch to this kernel:

![image](https://user-images.githubusercontent.com/19672699/123862389-254b5c80-d8dd-11eb-90c7-91cbc7a6187e.png)

I get an error saying it needs ipykernel. And the error is pointing to the wrong kernel. This doesn't happen with a notebook.

**Comment by joyceerhl** [comment]
Looks like the `displayName` might be incomplete for the busted interpreter https://github.com/microsoft/vscode-jupyter/blob/28739ba1128061328d1582d898a97c08abc9704e/src/client/datascience/jupyter/interpreter/jupyterInterpreterSubCommandExecutionService.ts#L94 https://github.com/microsoft/vscode-jupyter/blob/afddee11c14a4bfdb0bb0c338a1e40efcdd4dd5b/src/client/datascience/jupyter/interpreter/jupyterInterpreterDependencyService.ts#L139

**Comment by DonJayamanne** [comment]
Should be fixed now, closing for verification
