### ISSUE TITLE
Jupyter failed to create new cells  in a third part kernel notebook

### ISSUE THREAD

**Issue by zqni** [microsoft/vscode-jupyter#6427]
**Environment** 
> 
- OS: Linux x64 5.8.0-53-generic
- Python extension version: v2021.6.944021595
- Python version : 3.8
- Julia version:1.6.0

**Issues** 
> 
When trying to create new cells in a Julia kernel notebook, I met with the following alarm which said

`TypeError: Cannot read property 'charAt' of undefined at  in t `

Everything works fine in a python kernel notebook and Julia notebook indeed works without adding new cells.

**Comment by joyceerhl** [comment]
This PR https://github.com/microsoft/vscode-jupyter/pull/6291 should have fixed this problem for the upcoming stable release of the Jupyter extension (will be published sometime next week).

In the meantime, you can try out VS Code Insiders, which uses the preview native notebooks UI by default. That UI doesn't have this problem.
