### ISSUE TITLE
Native Notebooks - stronger contrast for cell border

### ISSUE THREAD

**Issue by kennysong** [microsoft/vscode-jupyter#6429]
The native notebooks feature is great. It's much faster to load and I love being able to use Vim keybindings.

One UX problem is that the border around each cell is so low-contrast that I can barely see it. Here's what it looks like:

<img width="1087" alt="asdf" src="https://user-images.githubusercontent.com/2199875/123899002-555c3380-d9a1-11eb-989b-f6df49305b1f.png">

Being able to clearly see the cells would be very helpful (it is a notebook, not a text file). There might be a color option I don't know about.

**Comment by joyceerhl** [comment]
You can customize `notebook.cellBorderColor` and many other tokens in your user settings.json like so:

![image](https://user-images.githubusercontent.com/30305945/123904566-88f97800-d925-11eb-8da5-53c2d8bdc100.png)

**Comment by kennysong** [comment]
Ah wonderful, this is exactly what I needed. I needed to change `notebook.outputContainerBackgroundColor` as well since it seems to copy `notebook.cellBorderColor` if not set.
