### ISSUE TITLE
Native Notebooks - output cell font size and color

### ISSUE THREAD

**Issue by kennysong** [microsoft/vscode-jupyter#6430]
The output cell in the native notebooks is a larger font size than the input cells. Is there a way to make them both the same size?

Also, some output is in a red font color. Why does this happen?

<img width="564" alt="asdf" src="https://user-images.githubusercontent.com/2199875/123901915-dcf87100-d9a6-11eb-8d75-05ce4216abca.png">
(the red output is produced by the [Papermill](https://github.com/nteract/papermill) library)

**Comment by joyceerhl** [comment]
The font size issue is tracked here https://github.com/microsoft/vscode/issues/123149 Please upvote that issue as VS Code uses upvotes to prioritize work.

Without knowledge of papermill I would hazard a guess that that is stderr output. Is the coloring undesirable for you?

**Comment by kennysong** [comment]
Thanks, I've upvoted and will track the other font size issue.

You're right about papermill, I manually checked and it's logging everything to stderr. Seems like a bug in their library. Not a VSCode bug.
