### ISSUE TITLE
Line Magic Linting

### ISSUE THREAD

**Issue by tanghyd** [microsoft/vscode-jupyter#6431]
Issue Type: <b>Bug</b>

When using Jupyer linemagic in an .ipynb notebook cell in VSCode there is a visual linting bug:

%load_ext autoreload
%autoreload 2
%matplotlib inline

appears to have a linting error with red lines under each %, with the hover text: "Expected expression Pylance".

This linting red line also shows up under %%timeit for an arbitrary code cell, but ONLY for the first %, not the second nor the whole term "%%timeit".

All of these magic commands appear to work correctly, it is just a weird linting interaction. I am not certain of the details behind linting so this may not be the most appropriate place to report this "bug"; but VSCode previously asked me for interactive Jupyter notebook feedback so I figured this may be relevant.

Extension version: 2021.6.999662501
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-74-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.59GB free)|
|Process Argv|--crash-reporter-id 6f39a52d-4364-4c01-bf77-267708478eb0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Dawn|
|OS|Linux x64 5.4.0-74-generic|
|CPUs|AMD Ryzen Threadripper 2920X 12-Core Processor (24 x 1712)|
|Memory (System)|62.67GB (31.51GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30329804
binariesv615:30325510
vsccppwtct:30329789

```

</details>

**Comment by rchiodo** [comment]
This should be handled if we fix this bug here:
https://github.com/microsoft/vscode-jupyter/issues/1497

**Comment by rchiodo** [comment]
Additionally pylance has an issue to handle this as well:
https://github.com/microsoft/pylance-release/issues/894
