### ISSUE TITLE
Many squiggles in Notebook

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-jupyter#6432]
Testing https://github.com/microsoft/vscode/issues/127362

* set up jupyter in a dev container:
  * create a new folder
  * (install remote dev container extension)
  * run `Remote Containers: Add Development Container Configuration Files...`
  * pick `Show All Definitions...` at the bottom
  * pick `Jupyter Data Science Notebooks`
  * reopen the folder in container
* find a sample notebook e.g. https://raw.githubusercontent.com/jrjohansson/scientific-python-lectures/master/Lecture-4-Matplotlib.ipynb
* open it and observe many squiggles even though the cells execute without errors (which indicates that there should be no errors):

![image](https://user-images.githubusercontent.com/5047891/123927996-b712a280-d98d-11eb-99d3-1d4096a940af.png)
 
![image](https://user-images.githubusercontent.com/5047891/123928060-c98cdc00-d98d-11eb-87d0-726412ecf181.png)

**Comment by rchiodo** [comment]
The first squiggle is this error here:
https://github.com/microsoft/pylance-release/issues/894

The second squiggle is likely this problem here:
https://github.com/microsoft/vscode-jupyter/issues/6333

**Comment by jakebailey** [comment]
I'm not sure why this is being closed in favor of the pylance issue if we are going to fix this by hiding diagnostics during the LS <-> Notebook translation (which would be here or vscode-python, I think). Should that issue be transferred, or has the plan changed?

**Comment by rchiodo** [comment]
Yeah I think the other issue should be transfered.
