### ISSUE TITLE
new vscode notebook plot pic‘s width is stretched

### ISSUE THREAD

**Issue by JJplane** [microsoft/vscode-jupyter#6437]
## Environment data

-   VS Code version:1.57.1
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.999662501
-   OS : Mac
-   Type of virtual environment used (conda )
-   Jupyter server running: Remote

## Actual behaviour
![image](https://user-images.githubusercontent.com/28783826/123933710-3374a800-d9c5-11eb-9291-454ec8994236.png)

**Comment by rchiodo** [comment]
This should be handled by this bug here:
https://github.com/microsoft/vscode/issues/125299

Which will be shipping in the next release of VS code.
