### ISSUE TITLE
Live share: The Guest Interactive window is no response when executed the cell.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#6438]
## Environment data
![image](https://user-images.githubusercontent.com/59192491/123933345-e0025a00-d9c4-11eb-9ec3-35b7bc3d35c8.png)

## Expected behaviour
Output should show up on Guest Interactive Window.

## Actual behaviour
The Guest Interactive window is no response.
![image](https://user-images.githubusercontent.com/59192491/123933962-6d45ae80-d9c5-11eb-9074-61eb0fdc2139.png)

After executed the cell in Guest, the output show up in the Host Interactive Window
![image](https://user-images.githubusercontent.com/59192491/123934406-d4636300-d9c5-11eb-8a9d-a5299529837c.png)

## Steps to reproduce:
1. Install Live Share VSCode Extension
2. Open manualTestFile.py in VSCode
3. Run the first cell in the file
4. Switch to the `Live Share` tab in VS Code and start a session
	Verify server start
		a. Jupyter server instance should appear in the live share tab
5. Open another window of VSCode
6. Connect the second instance of VSCode as a Guest to the first Live Share session
7. After the workspace opens, open the manualTestFile.py on the Guest instance
8. On the Guest instance run a cell from the file

**Comment by greazer** [comment]
We are reimplementing the interactive window using the native notebooks API. It's available in the latest Jupyter extension starting tomorrow. Please test this new experience with LiveShare, and add info to this bug.

**Comment by greazer** [comment]
@linette-zyy, please reopen if this still occurs on the newest, native notebook based interactive window.
