### ISSUE TITLE
[Endgame testing] Stepping into a built-in python function also leads to a random temp file being opened

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-jupyter#6442]
Testing https://github.com/microsoft/vscode/issues/127362
1. Debug a jupyter notebook
2. Attempt to step into something like a for loop
3. 🐛 A tmp file such as `Could not load source '/tmp/ipykernel_152730/2944423233.py': source unavailable.` is opened

**Comment by roblourens** [comment]
Can you paste the code?

**Comment by lramos15** [comment]
Yeah sure, here's my super advanced power function
```
def power(number, power):
    total = 1
    for _ in range(power):
        total = total * number
    return total
```

If you execute a step in on the `    for _ in range(power):` line you will get a random temp file opened

**Comment by DavidKutu** [comment]
TODO: maybe we don't allow stepping in on python code?

**Comment by roblourens** [comment]
If I debug this code as a normal python file and step in on that line, it doesn't step in to `range`.

**Comment by rchiodo** [comment]
JustMyCode should handle this. You guys have to set this during the attach if you want it to work the same.

**Comment by DavidKutu** [comment]
this is fixed
