### ISSUE TITLE
[Endgame testing] Debugging doesn't feel "native"

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-jupyter#6443]
Testing https://github.com/microsoft/vscode/issues/127362

When debugging a jupyter notebook it feels very different than debugging within VS Code. Debugging normally starts execution of the program and breakpoints are always present. This means that if you click debug it hits your first breakpoint, if you have no breakpoints it would just run all the cells. I also get confused about how to stop debugging because normally there is the red square which allows you to stop program execution but here the debug toolbar only offers a disconnect. I'm wondering how much this is limited by the way jupyter works as I find it strange and very confusing. It's especially weird when you're done debugging and everything is still connected. I didn't expect clicking run all to cause me to start debugging again.

**Comment by DavidKutu** [comment]
This definitely makes more sense in run by line.

@roblourens also had an idea for full debugging. We always have a session running in the background, and the only thing a user needs to do to debug is place a breakpoint and run the cell. That'll probably feel more natural.

**Comment by roblourens** [comment]
Improved this, we now show the breakpoint margin all the time and have a "debug cell" command that operates on a single cell. It's an ongoing discussion though.
