### ISSUE TITLE
[Endgame testing] Debug console doesn't provide intellisense

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-jupyter#6444]
Testing https://github.com/microsoft/vscode/issues/127362
1. Start debugging
2. Write a native function into a cell such as `pow`, you'll see intellisense
3. Open debug console and type `pow` or a variable you have defined
4. 🐛 No intellisense.

**Comment by roblourens** [comment]
Maybe based on `evaluate` request?

**Comment by roblourens** [comment]
Seems to work fine now.
