### ISSUE TITLE
New cell is getting inserted automatically when I run an existing cell

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-jupyter#6445]
Testing https://github.com/microsoft/vscode/issues/127378

![Kapture 2021-06-30 at 17 10 33](https://user-images.githubusercontent.com/10746682/123986078-489e0680-d9c6-11eb-85cd-7fd5950d1ca1.gif)

**Comment by rchiodo** [comment]
This is actually by design. Jupyter itself works this way.
