### ISSUE TITLE
Cannot open resource with notebook editor type 'jupyter-notebook'

### ISSUE THREAD

**Issue by Vinaychalluru** [microsoft/vscode-jupyter#6447]
Issue Type: <b>Bug</b>

Unable to view ```.ipynb``` files using Jupyter Notebook Extension

VS Code version: Code - Insiders 1.58.0-insider (57930758db9e2c83f59b9ee1851400bd16192d32, 2021-06-30T05:14:00.370Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

![image](https://user-images.githubusercontent.com/5652928/123994394-f7ecd480-d9ea-11eb-8e72-a32fbb47c6d8.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.01GB free)|
|Process Argv|--crash-reporter-id 6b18d399-0190-4f91-b62c-4f9fe378082a|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
gitlens|eam|11.5.1
gc-excelviewer|Gra|3.0.42
beautify|Hoo|1.5.0
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.14.0
mssql|ms-|1.10.1
python|ms-|2021.7.981196274-dev
vscode-pylance|ms-|2021.6.4-pre.1
jupyter|ms-|2021.7.985709665
vscodeintellicode|Vis|1.2.14

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805:30301674
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwt:30312692

```

</details>

**Comment by rchiodo** [comment]
@Vinaychalluru can you show the contents of your settings.json? It should have this value in it:

```json
  "workbench.editorAssociations": {
    "*.ipynb": "jupyter-notebook"
  },
```

If it doesn't, can you add that and reload VS code?

**Comment by Vinaychalluru** [comment]
I have both Insiders and Stable versions installed and Settings Synced up

I am unable to open Notebook using the Insiders version even after adding the above configuration and restarting VS Code.

Below is my settings.json from insiders:

> {
    "python.pythonPath": "C:\\Users\\vinay.c\\Anaconda3\\envs\\myenv\\python.exe",
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
      }, 
}

Below is my settings.json from stable:

> {
    "workbench.sideBar.location": "right",
    "editor.minimap.enabled": false,
    "terminal.integrated.rendererType": "dom",
    "python.pythonPath": "C:\\Program Files (x86)\\Python\\Python38\\python.exe",
    "terminal.integrated.fontSize": 16,
    "debug.console.fontSize": 16,
    "markdown.preview.fontSize": 16,
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "diffEditor.renderSideBySide": false,
    "mssql.resultsFontSize": 16,
    "mssql.connections": [
        {
            "server": "{{put-server-name-here}}",
            "database": "{{put-database-name-here}}",
            "user": "{{put-username-here}}",
            "password": ""
        }
    ],
    "workbench.editor.highlightModifiedTabs": true,
    "editor.fontSize": 16,
    "jupyter.sendSelectionToInteractiveWindow": false,
    "python.languageServer": "Pylance",
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
    },
    "jupyter.askForKernelRestart": false,
    "python.defaultInterpreterPath": "C:\\Program Files (x86)\\Python\\Python38\\python.exe",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "editor.renderIndentGuides": false,
    "workbench.colorCustomizations": {
        "editor.lineHighlightBackground": "#1073cf2d",
        "editor.lineHighlightBorder": "#9fced11f"
    },
    "editor.wordWrap": "off",
    "diffEditor.wordWrap": "off",
    "python.insidersChannel": "daily",
    "workbench.colorTheme": "Community Material Theme Ocean High Contrast",
    "notebook.lineNumbers": "on",
    "notebook.cellToolbarLocation": {
        "default": "right",
        "jupyter-notebook": "left"
    }
}

**Comment by joyceerhl** [comment]
@Vinaychalluru If you run Developer: Toggle Developer Tools from the command palette, do you see any errors in the log?

**Comment by Vinaychalluru** [comment]
@joyceerhl Yes, Attached the snapshot

![image](https://user-images.githubusercontent.com/5652928/124090018-13e78900-da72-11eb-8379-89b8118cba94.png)

**Comment by Vinaychalluru** [comment]
To check further, I have now reinstalled Code - Insiders. Everything worked as expected until an automatic update caused the errors above again.

**Version details after reinstalling:**
>Version: 1.58.0-insider (user setup)
**Commit: 49e1f9919880c1c96004f9b6ad91bcee7a94a1bd
Date: 2021-06-25T05:14:20.119Z**
Electron: 12.0.12
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041

**Version details after the automatic update:**
> Version: 1.58.0-insider (user setup)
**Commit: 57930758db9e2c83f59b9ee1851400bd16192d32
Date: 2021-06-30T05:14:00.370Z**
Electron: 12.0.12
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by joyceerhl** [comment]
You're running into https://github.com/microsoft/vscode/issues/127626, which prevents all extensions (including the Jupyter extension) from loading. This should've been fixed in the latest VS Code Insiders. If the issue recurs please file an issue on https://github.com/microsoft/vscode, you can also try a workaround: delete C:/Users/<your username>/AppData/Roaming/Code - Insiders/User/workspaceStorage which contains stray lockfiles
