### ISSUE TITLE
Setting 'jupyter.ignoreVsCodeTheme' is not being applied anymore.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6448]
We got this review feedback on the extension page:

```
Rating: 1/5
"jupyter.ignoreVscodeTheme": true is no longer working with the lastest VSCode.
I can't use native Jupyter theme with vscode.
```

Talked to @rebornix about it. We might be able to generate a custom set of color customizations when ignoreVSCodeTheme is true and then mark the setting as deprecated:

```json
"workbench.colorCustomizations": {            
            "notebook.focusedEditorBorder": "#f30a",
            "notebook.focusedRowBorder": "#ff0",
            "notebook.focusedCellBorder": "#f30a",
            "notebook.cellEditorBackground": "#F4F6F8",
            "notebook.cellToolbarSeparator": "#eee",
            "notebook.outputContainerBackgroundColor": "#F4F6F8"
}
```

**Comment by greazer** [comment]
This may be a bigger problem than we think. I think the bottom line here is that customers are requesting that they can see the notebook in a completely different theme than the editor. They may be using renderers that work best on a light background, but they want their source editor to be dark theme.

**Comment by jaymody** [comment]
I have the same issue, setting `"jupyter.ignoreVscodeTheme": true` seems to do nothing. Also, `"jupyter.colorizeInputBox": false` doesn't seem to work either.

**Comment by DonJayamanne** [comment]
Dup of https://github.com/microsoft/vscode-jupyter/issues/7264
