### ISSUE TITLE
Seeing squiggles in input editor

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-jupyter#6449]
Testing https://github.com/microsoft/vscode/issues/127378

![image](https://user-images.githubusercontent.com/10746682/124005565-86f0f100-d9d9-11eb-8f4f-5bf1b91a7d96.png)

**Comment by rchiodo** [comment]
Dupe of https://github.com/microsoft/vscode-jupyter/issues/6432

**Comment by rchiodo** [comment]
Sorry not a dupe. This is in the interactive window.

**Comment by rebornix** [comment]
This should be fixed now in Python extension.
