### ISSUE TITLE
Not seeing suggestions when I imported numpy module

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-jupyter#6450]
Testing https://github.com/microsoft/vscode/issues/127378

Validating following step:

> You should have Python IntelliSense for the input editor provided by Pylance, including module completions e.g. import numpy as np --> np. should bring up all numpy module methods

![image](https://user-images.githubusercontent.com/10746682/124005667-a38d2900-d9d9-11eb-9c2f-a004f4ecd004.png)

**Comment by joyceerhl** [comment]
@sandy081 What version of the Python extension do you have? It should be v2021.7.981196274-dev

**Comment by joyceerhl** [comment]
Additionally do you have the numpy module installed into your Python environment? If you don't, the lack of suggestions is expected, instead you can try 

```
import sys
sys.
```

**Comment by sandy081** [comment]
I have python `v2021.7.981196274-dev` installed. 

> Additionally do you have the numpy module installed into your Python environment?

I have not installed the module - I have to say I am new to Python so I did not know about it.

`sys.` worked.

Please feel free to close if it is a set up issue.

**Comment by joyceerhl** [comment]
Got it, my mistake for not asking you to install `numpy` in the setup instructions 😅 Closing as this is just an environment setup problem and not an issue with intellisense support for the interactive window.
