### ISSUE TITLE
Restart kernel should be a modal dialog

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-jupyter#6456]
Testing https://github.com/microsoft/vscode/issues/127378

Restart kernel shall be a modal dialog because user has to take an action to continue...

![image](https://user-images.githubusercontent.com/10746682/124008394-a9d0d480-d9dc-11eb-8c1d-2b748885af19.png)

**Comment by joyceerhl** [comment]
We should discuss potentially moving the restart kernel command into VS Code core, as this is common to many kernels.

**Comment by DonJayamanne** [comment]
here's the upstream issue with that feature request https://github.com/microsoft/vscode/issues/118783

**Comment by joyceerhl** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/118783
