### ISSUE TITLE
Nothing happens when I click on collapse all

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-jupyter#6457]
Testing https://github.com/microsoft/vscode/issues/127378

Here is my interactive window and clicking on collapse all action does not do anything

![image](https://user-images.githubusercontent.com/10746682/124008844-295ea380-d9dd-11eb-9ebc-5e5a6a94bc7b.png)

May be I do not have any collapsible cells here? If so, what is the way to have such cells.

**Comment by IanMatthewHuff** [comment]
Validated.
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/75ec2569-fda6-4e6d-b78a-d1cd3b270f88)
