### ISSUE TITLE
Not seeing any suggestions in input editor

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-jupyter#6458]
Testing https://github.com/microsoft/vscode/issues/127378

![image](https://user-images.githubusercontent.com/10746682/124009019-6165e680-d9dd-11eb-9452-0c16a66d7223.png)

**Comment by joyceerhl** [comment]
@sandy081 I'm a bit confused, you also filed https://github.com/microsoft/vscode-jupyter/issues/6450 which shows you were getting intellisense at some point. Did suggestions stop working after a while?

**Comment by sandy081** [comment]
Yeah, it stopped working all of a sudden

**Comment by rebornix** [comment]
They were already fixed in latest Python Insiders.
