### ISSUE TITLE
Interactive Window - No sys info at the top when kernel doesn't launch

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6462]
Testing microsoft/vscode#127378

If my kernel doesn't start (because I either picked a kernel without ipykernel installed or it's not working) I don't get sysinfo before cells:

![image](https://user-images.githubusercontent.com/19672699/123850032-596b5100-d8ce-11eb-86fd-869988286ab0.png)

**Comment by greazer** [comment]
Would be best to give an indication to the user that the kernel actually didn't start.
