### ISSUE TITLE
Support error link clicking in interactive window

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6465]
Testing microsoft/vscode#127378

Create an error like so:

![image](https://user-images.githubusercontent.com/19672699/123853697-9df8eb80-d8d2-11eb-86d2-1538ff6714b7.png)

The old IW would allow a user to click on the line number to jump to where the exception was thrown.

**Comment by greazer** [comment]
The case being made for this for IW and not necessarily native notebooks is because the user may be working with a large python file that tends to have a lot more code that a notebook.
