### ISSUE TITLE
Native Interactive - Delay when running a cell and opening the IW for the first time.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#6466]
Latest VS Code Insiders (end-game version)
Latest Jupyter extension

- Open VS Code 
- Open a Python script with cells
- Click on Run Cell, or press shift-enter on the cell

*Actual*
Nothing seems to happen for a few seconds. Finally the IW shows up and works.

*Expected*
The IW should be shown right away, and as initialization/kernel startup happens eventually gets populated.

**Comment by joyceerhl** [comment]
If you opt back into webview interactive, then reload, then repeat the same steps, what do you get?

The delay you're seeing is likely the fact that if controllers weren't already loaded, we wait to load and register all controllers with VS Code first, then look for the controller which matches the active interpreter. Though I would think that we'd have the same problem with the webview interactive window--needing to discover all kernels first.

**Comment by greazer** [comment]
With the webview, as soon as I run the first cell, I immediately see a blank IW window created. This would be acceptable. The native IW doesn't show anything at all for a few seconds, making me likely to try running the same cell again (which I have done).

**Comment by joyceerhl** [comment]
Here's what I see for native vs webview interactive window. Can you share what you're seeing (and also maybe Jupyter output logs?)

Native:
![recording (15)](https://user-images.githubusercontent.com/30305945/124086480-f1b82180-da05-11eb-9412-4bdeb78b87ad.gif)

Webview:
![recording (16)](https://user-images.githubusercontent.com/30305945/124086484-f250b800-da05-11eb-85ec-72de9fa9d3c2.gif)

**Comment by DonJayamanne** [comment]
Isn't this an `iw-golden` scenario

**Comment by IanMatthewHuff** [comment]
I'm not seeing a repro here, and neither is @greazer (per convo) so closing.
