### ISSUE TITLE
Native Interactive - Collapsing cells differs from Webview

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#6474]
If you execute a script code cell with the Webview based Interactive Window, the cell input and output will appear in the IW. However, only the first line of the source code will be shown. The user can expand the cell to see the entire source executed for that cell.

![image](https://user-images.githubusercontent.com/11685408/124083382-a51f1700-da02-11eb-8c7d-904e06f930fc.png)

The native interactive window shows full cell source by default. Then when you collapse all cells you basically see none of the source for collapsed cells that have no output. 

I believe the behavior we created for the webview was specifically requested by customers. So we should be careful in changing the behavior. I realize the native interactive window doesn't support this model yet... unless we just want to make use of monaco's ability to collapse source *within* each cell and leave the chrome around the cell visible.

**Comment by joyceerhl** [comment]
This isn't an intentional behavior change, we haven't gotten around to implementing custom code folding for the interactive window yet.

**Comment by joyceerhl** [comment]
I think we'd use https://code.visualstudio.com/api/references/vscode-api#FoldingRangeProvider

**Comment by joyceerhl** [comment]
Related: https://github.com/microsoft/vscode/issues/119776#issuecomment-873483243

**Comment by jaymegordo** [comment]
+1 would definitely like to have the option to run cells from a `.py` file show only the cell output in the native interactive window, similar to webview.

**Comment by rebornix** [comment]
Let's track this in https://github.com/microsoft/vscode/issues/119776 .
