### ISSUE TITLE
Native Interactive - Shouldn't have to give focus to cell to delete it from IW

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#6475]
The webview IW allowed users to delete a cell without having to give any focus to it. The native IW requires the cell has focus first. This can be an annoyance if you're using the IW workflow to build an ipynb that you plan on exporting when you're done.

**Comment by joyceerhl** [comment]
I think this is in reference to the fact that the cell toolbar is only rendered for the currently focused notebook cell. /cc @rebornix

**Comment by joyceerhl** [comment]
To do this, VS Code needs to give us a way to render the cell toolbar for every cell just for interactive window-embedded notebook documents

**Comment by rebornix** [comment]
This behaves the same as the notebook editor, open for ideas how do we handle this in iw, i.e., if it should behave differently than the notebook.

**Comment by IanMatthewHuff** [comment]
Verified. Previous cells can be deleted now.
