### ISSUE TITLE
Native Interactive - Prepend cell marker (#%%) to copied code when Copy Code button is clicked.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#6477]
The idea behind adding the ability to copy a code cell that exists in the interactive window is that it can be used to take a particular piece of code that was being iterated on directly in the IW and paste it into the script the customer is building. Therefore, it's not unreasonable to assume the user will want to just "Copy Code" and paste the copied cell code *as a marked cell* in the script. Having to manually add the marker can be an annoyance. 

If we did this, then the "Copy Code" button should perhaps be called "Copy Cell". Note that if the user does not want the cell marker they can always do a selection (including ctrl-a to select all) within the Monaco editor and use Ctrl+c or Cmd+c. It's also easier to delete a line with an unwanted cell marker than it is to add one. 

Note that the webview based IW did not support this feature and it also did not readily support selecting lines of code from the code section of each cell. I believe *I* was the requestor for this functionality, so you could say I'm just a little biased with regard to how I think it should work. :D

**Comment by joyceerhl** [comment]
Would you expect to see #%% on cells created from the interactive window input editor in addition to cells run from a Python file? FWIW I agree with @IanMatthewHuff I wouldn't want to see #%% at all. Could be a setting based on user feedback
