### ISSUE TITLE
Test issue: Outputs with support for ansic code ``:1 | Incorrect number of output: expected 2 to equal 1

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6485]
Recent PR failure:
[logs_11014.zip](https://github.com/microsoft/vscode-jupyter/files/6749454/logs_11014.zip)

**Comment by greazer** [comment]
@rchiodo, does this reflect a bug in the product?

**Comment by rchiodo** [comment]
Yes it should, just can repro locally yet. The test is indicating the number of outputs is incorrect.

**Comment by rchiodo** [comment]
So we're getting different outputs on Linux than on Windows/Mac (it works for Ian locally too). Might be timing related, might be linux only issue.

**Comment by DonJayamanne** [comment]
Should be fixed now.
