### ISSUE TITLE
Remove webview notebook editor code

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#6488]
(WIP)

- [x] Delete `interactiveWindow.ts`, `interactiveWindowProvider.ts`, `interactiveWindowCommandListener.ts`, `interactiveBase.ts`

**Comment by joyceerhl** [comment]
Discussion with @rebornix @rchiodo @DonJayamanne 

This iteration (Stage 0)
* Remove Live Share layers

Stage 1
Remove the UI 
Remove the INotebookEditorProvider
Remove INotebook (TBD? Native notebooks codepath also depends on INotebook)

Stage 2
Remove the ICell interface
* Rewrite export 
* Remove INotebookExecutionLogger preExecute and postExecute in favor of nativePostExecute (take NotebookCell instead of ICell)
How do we refactor execution so that things can be shared
What are we going to do for other languages 
Jupyter ext/Python ext --> npm module

Split out npm modules for
* Kernel discovery (trivial, look on disk? Need Python to discover certain kernels)
* Open sockets and start kernels
* Translating Jupyter outputs to VS Code outputs


--- Interactive window discussion ---

We need to be able to execute code silently against the underlying kernel so we cannot use pure VS Code APIs to execute code in the interactive window
* CWD
* __file__

Interactive window debug cell
* INotebookExecutionLoggers provide cell hashes and increment execution count, must preserve loggers for native interactive window port

**Comment by DonJayamanne** [comment]
Closing as this work has been completed
