### ISSUE TITLE
Native Interactive (and WebView) - Run several cells at one to start an interactive session, some cells don't run and are out of order

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#6494]
I believe this is a dupe, but I'm not sure if that dupe was readily reproable. This one seems to be.
- Open a Python script file with several cells that are distinguishable from each other, ala
```
# %%
print('1')
# %%
print('2')
# %%
print('3')
# %%
print('4')
```
- Run each line of code quickly via Shift+Enter
- Wait until processing is done.

Result
Some cells not run and definitely out of order. See...
![image.png](https://images.zenhubusercontent.com/5bda244bb6c4f1227d4a2d8e/d2e7b492-5d6c-4a48-b092-4679d64f602b)
-

**Comment by joyceerhl** [comment]
I was able to fix the problem where some cells don't run, however the out of order problem is easily reproducible even with webview interactive window:

![image](https://user-images.githubusercontent.com/30305945/125558649-2f518d02-3921-4147-a196-a17c59302edc.png)
