### ISSUE TITLE
Test Issue: Create new notebook seems to fail on some of the tests

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6498]
Create empty notebook using command & our editor is created:1 | Running the contributed command: 'jupyter.createnewnotebook' failed.
Create empty notebook and we have active editor:1 | NO notebook document for 'untitled:Untitled-1.ipynb?jupyter-notebook'
Create empty notebook will fire necessary events:1 | NO notebook document for 'untitled:Untitled-1.ipynb?jupyter-notebook'
Opening a non-notebooks will fire necessary events:1 | NO notebook document for 'untitled:Untitled-1.ipynb?jupyter-notebook'
Closing a notebook will fire necessary events and clear state:1 | NO notebook document for 'untitled:Untitled-1.ipynb?jupyter-notebook'
Closing nb should close our notebook editors as related resources:1 | Running the contributed command: 'jupyter.createnewnotebook' failed.
Active notebook points to the currently active editor:1 | NO notebook document for 'untitled:Untitled-1.ipynb?jupyter-notebook'
Create two blank notebooks:1 | NO notebook document for 'untitled:Untitled-1.ipynb?jupyter-notebook'
Active Notebook Editor event gets fired when opening multiple notebooks:1 | NO notebook document for 'untitled:Untitled-1.ipynb?jupyter-notebook'

[logs_11048.zip](https://github.com/microsoft/vscode-jupyter/files/6749653/logs_11048.zip)

**Comment by IanMatthewHuff** [comment]
We have some test debt, but I don't believe this is an issue anymore.
