### ISSUE TITLE
Plot viewer showscolor banding and performs slowly with large matplotlib pcolormesh

### ISSUE THREAD

**Issue by tcdejong** [microsoft/vscode-jupyter#6499]
Does this issue occur when all extensions are disabled?: **Yes**

# Issue Type: <b>Bug</b>

The VS Code plot viewer struggles with large matplotlib pcolormesh plots. The viewer introduces visual artifacts in the form of grey color banding, and becomes incredibly slow and unresponsive. These issues only occur in VS Code's plot viewer. They do not occur in the interactive terminal or Matplotlib's own viewer (when the MVP below is ran in a regular terminal).

# Steps to repoduce

1. Run the following MVP in the Python Interactive Window:

```py
import matplotlib.pyplot as plt
from random import randint

# generate placeholder data
x_len = 500
y_len = 75
data = [[randint(0,y+1) for _ in range(x_len)] for y in range(y_len)]

fig = plt.figure(figsize=(10,6))
ax = fig.add_subplot(111)
plt.pcolormesh(data, cmap="magma")
plt.show()
```

2. The plot shows correctly in the Interactive Window. 
3. Double click the plot in the plot viewer and wait for it to load (this can take several minutes). 
4. Notice the vertical color banding on the plot in the plot viewer. 

The `cmap` kwarg does not affect the color banding, but this one shows it the clearest. 

Finally, here's a screenshot comparing the plot viewer and interactive terminal. Notice the vertical, grey banding in the plot viewer. 

![afbeelding](https://user-images.githubusercontent.com/21024386/123930571-2db09f80-d990-11eb-9099-9e46026cb0e0.png)

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.58GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/redacted/Documents/Repositories/modality-reader|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.4
plantuml|jeb|2.15.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
vsliveshare|ms-|1.0.4498
material-theme|zhu|3.10.14

</details>

**Comment by greazer** [comment]
@sbatten, this behavior is due to the fact that the plot viewer makes use of a generated SVG (scalable vector graphics) file instead of a simple PNG or JPG to support better visualization fidelity in the plot viewer. The resulting SVG file from this plot is much larger than that of what is displayed in the IW file. 

That being said, this functionality has caused numerous complaints concerning ipynb file sizes that contain such images. We will address this problem with the in the near future.
