### ISSUE TITLE
 VSCode 1.57.1 Plot Viewer option missing

### ISSUE THREAD

**Issue by flyforward2016** [microsoft/vscode-jupyter#6502]
The plot viewer function of Jupyternotebook in VSCode 1.57.1 is missing. I cannot open the plot in a new tab, zoom-in / out and save it.

**Comment by IanMatthewHuff** [comment]
Duplicate of #6315 

@flyforward2016 The plot viewer is an element that has not yet been added to the new Native Notebook experience that we are rolling out. The issue that I linked above is the best issue to track for us resolving this issue.
