### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Nehanshu6192** [microsoft/vscode-jupyter#6509]
- Issue Type: `Performance`
- Extension Name: `jupyter`
- Extension Version: `2021.6.999662501`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`[ms-toolsai.jupyter-unresponsive.cpuprofile.txt]
[ms-toolsai.jupyter-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-jupyter/files/6752110/ms-toolsai.jupyter-unresponsive.cpuprofile.txt)
(https://github.com/microsoft/vscode-jupyter/files/6752108/ms-toolsai.jupyter-unresponsive.cpuprofile.txt)`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by claudiaregio** [comment]
@Nehanshu6192 Could you please provide the required information/logs so we can assist?
