### ISSUE TITLE
Native interactive window - interrupt doesn't seem to work (at least on Windows)

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6513]
Run this code:

```
import time
while (True):
    time.sleep(.1)
    print('*')
```

Hit the interrupt button. No interrupt.

Same code in a native notebook works (and throws the expected KeyboardException)

**Comment by joyceerhl** [comment]
Strange, interrupt seems to work for me 

![image](https://user-images.githubusercontent.com/30305945/124312067-95e3ba80-db23-11eb-8fee-e66d5b05632e.png)

Do you have the logs?

**Comment by rchiodo** [comment]
[no_interrupt.log](https://github.com/microsoft/vscode-jupyter/files/6756302/no_interrupt.log)

**Comment by rchiodo** [comment]
I had to do a restart at the end to get it to actually stop spewing output, so that's why there's a restart in there

**Comment by greazer** [comment]
Please add more logging so we can figure out what's happening.

**Comment by greazer** [comment]
After discussion, we determined this is more a problem with handling interrupt on Windows. If you change the delay to 1 sec vs .1 and it works, then this is the problem and there's not much we can do.
