### ISSUE TITLE
Native Notebooks - Diagnostics remain after resolving missing imports

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#6521]
## Environment data

-   VS Code version: 1.58.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.993044620
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   Pylance Extension version: v2021.6.4-pre.1
-   OS (Windows | Mac | Linux distro) and version: Windows

## Steps to reproduce: 
1. Try to import package that is missing from environment - get diagnostics from Pylance
2. Run cell and get error
3. Resolve environment but installing package 
4. Run cell again. Error is gone but the diagnostics from Pylance remain 

## Expected behavior
Diagnostics to be removed on run 

## Actual behavior
Diagnostics remain 

![resolved imports not removed](https://user-images.githubusercontent.com/19276747/124343650-fa356700-db81-11eb-9c80-6b6c63c3d9b1.gif)

**Comment by joyceerhl** [comment]
Does your active Python interpreter in the Python extension match your kernel? If not, this is expected behavior.
