### ISSUE TITLE
Hide Execution Time

### ISSUE THREAD

**Issue by shubsaini09** [microsoft/vscode-jupyter#6522]
Hi All, 

I am trying to find the option for hiding or disabling the execution time but unable to get the option. I tried searching on google but no luck. Can someone please help me with this issue?

![image](https://user-images.githubusercontent.com/12813253/124363385-89ad4980-dc58-11eb-9343-8fc744f4806f.png)

Thanks

**Comment by joyceerhl** [comment]
You can hide the whole status bar with the following setting in your user settings.json:


```
    "notebook.showCellStatusBar": "hidden",

```

**Comment by shubsaini09** [comment]
@joyceerhl it worked. Thanks for the help. Can you also share the documentation for such settings?

**Comment by joyceerhl** [comment]
Here's the list of all notebook layout settings: https://code.visualstudio.com/updates/v1_57#_notebook-layout-customization
