### ISSUE TITLE
VSC Jupyter reports python 3.7.3 Interpreter even though pointing to 3.8.8 exe

### ISSUE THREAD

**Issue by TickboxPhil** [microsoft/vscode-jupyter#6526]
Issue Type: <b>Bug</b>

Visual Studio Code reports python 3.7.3 in Jupyter .ipynb notebook although Anaconda Environment base (root) is latest Python 3.8.8.

[![enter image description here][1]][1]

However, Settings -> Default Interpreter Path definitely points to C:\ProgramData\Anaconda3 (it was installed for all users) whose Python.exe is indeed 3.8.8150. And code verifies it does seem to be the 3.8.8:

    import sys
    print (sys.version)
    
    3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)] 

Fortunately, I believe it must be 3.8 as it uses non-3.7 ":=" Assignment Expressions https://docs.python.org/3/whatsnew/3.8.html 

    a = np.arange(11)
    if (n := len(a)) > 10:
        print(f"List is too long ({n} elements, expected <= 10)")

I've uninstalled, rebooted and installed latest Anaconda 2021.05 and Visual Studio Code 1.57.1 (because VSC disappeared from the Anaconda tiles), still same issue. On another Windows 10 PC, VSC shows 3.8.8 no prob, although Default Interpreter Path to Anaconda3\Python.exe is slightly different via C:\users folder (as installed for own user only).

Is this just an annoying VSC misreporting bug or something more nefarious and I'm missing something?

  [1]: https://i.stack.imgur.com/QNAtq.png

Extension version: 2021.6.999662501
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by DavidKutu** [comment]
Thanks for the issue @TickboxPhil.

Could you please repro your issue, and then run this cell on the same notebook:
```
import sys
sys.version
```

Does it display the expected version? Or the one in the kernel picker?

**Comment by TickboxPhil** [comment]
Thanks for response David - I did run that code before as noted and it reported correct version 3.8.8. However, I think it also has the effect of flushing out the old kernal version, as the top right kernal picker got updated. Same on another workspace set of files. Sometimes, even a later incorrect 3.8.10 is reported (note contradiction bottom and top info) until that sys.version code is run (although sometimes just a delay until running anything):

![Visual Stusdio Code 3 8 10 oddity](https://user-images.githubusercontent.com/16966543/124730070-eafb4400-df08-11eb-837b-fdf481bbddd2.PNG)

But ultimately, the correct kernal *is* loaded, it's just a reporting thing and eventually even that gets flushed out (especially when using that code). May confuse some to begin with so worth keeping an eye on, but AOK for now, happy to close unless others still have problem. Many thanks!

**Comment by DavidKutu** [comment]
Lets leave this open for now, I'll discuss it with the team on an upcoming meeting.

One last thing, could you opt in to our new notebook interface and check if you can repro the issue?
To opt in, follow these steps: https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code

Please let me know if that helps.

**Comment by TickboxPhil** [comment]
Thanks David, good luck with team and dev. 

Have installed the Insiders on both machines - works great so far (love the timer on code block run) and doesn't repro the issue, although that cleared on normal VSC anyway as noted. 

Won't use it on urgent project until they release updated working Markup Theme Kit (currently 0.1.4) as difficult to distinguish Jupyter code and output - and https://github.com/microsoft/vscode-themes/issues already has enough on their list!

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed with new native support for editing notebooks. To opt into that experience see: https://github.com/microsoft/vscode-jupyter/wiki/Introducing-Native-Notebooks.
