### ISSUE TITLE
"native notebooks" release timeline?

### ISSUE THREAD

**Issue by nickeubank** [microsoft/vscode-jupyter#6531]
Hey all! 

I'm a data science instructor, and recently stumbled across the massive improvements in jupyter notebooks that one can find on the insider channel. Is there a timeline for release of that improved interface? I'm organizing and writing course materials for this fall, and am trying to figure out whether I should just go ahead and write my materials for the current interface (non-insider), or write them for the version on insider knowing that my students will have access to it on the main channel by the time classes start (not comfortable putting brand new data science students on insider...).

Thanks!

**Comment by DavidKutu** [comment]
Thanks for your comment @nickeubank!

The new interface is available in stable! To use it please follow these steps: https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code

We don't have a hard release date, but getting feature parity and releasing it as the default experience in stable is our number 1 priority. We're working hard to make that happen.

Let me know if this works for you.

**Comment by nickeubank** [comment]
WOOHOO! That's perfect, thanks so much @DavidKutu
