### ISSUE TITLE
veiwing numpy complex data with Data Viewer

### ISSUE THREAD

**Issue by kopalx** [microsoft/vscode-jupyter#6536]
Data Viewer does not display numpy complex data

**Comment by IanMatthewHuff** [comment]
@kopalx Could you provide an example notebook that illustrates this? Not fully sure what type of complex data you are referring to here.

**Comment by kopalx** [comment]
Hi,
I mean complex number. For instance, invoke following code and view it with the data viewer:

import numpy as np
aaa = np.array([1+j,1-j])

BR,
Alex

**Comment by greazer** [comment]
Dupe of #1610
