### ISSUE TITLE
Native Interactive - Clear All doesn't clear cells

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode-jupyter#6541]
## Environment data
-   VS Code version: 1.58.0-insider
-   Jupyter Extension version: v2021.8.1003809038
-   Python Extension version: v2021.7.992362372-dev
-   OS (Windows | Mac | Linux distro) and version: OSX 11.4
-   Python and/or Anaconda version: 3.9.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): poetry env
-   Jupyter server running: Local | Remote | local

## Expected behaviour
`jupyter.interactive.clearAllCells` deletes all cells in the current native jupyter interactive window

## Actual behaviour

Nothing happens, wether run with keyboard shortcut or from command palette

## Steps to reproduce:

1. `cmd + shift + p` > "clear all..."
2. press enter
3. cells not cleared

<img width="2204" alt="image" src="https://user-images.githubusercontent.com/29611875/124644457-26353e80-de47-11eb-8453-24cfbc1d0c71.png">

PS Native interactive looking 👌🏻👌🏻👌🏻 - excited to see how it progresses!

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by joyceerhl** [comment]
Oops, that'll be because the current implementation assumes the command is being invoked with context from the `interactive/toolbar` menu. Should be a straightforward fix.

**Comment by jaymegordo** [comment]
@joyceerhl thanks for the fix, working as expected now.

Side question... is there an explicit when-context for when the interactive window has focus similar to `editorTextFocus`? 

`jupyter.ownsSelection` doesn't seem to work. Something like `jupyter.interactive.hasFocus`?

Is there anywhere that all the when-contexts are documented? Thanks!

**Comment by jaymegordo** [comment]
I also played around with these editor contexts:
[https://github.com/microsoft/vscode-jupyter/blob/d06d8d8b0c2e8d7db45fcb6dc4434cdb313e6271/src/client/datascience/constants.ts#L190](https://github.com/microsoft/vscode-jupyter/blob/d06d8d8b0c2e8d7db45fcb6dc4434cdb313e6271/src/client/datascience/constants.ts#L190)

But not sure if they can be used for keyboard shortcuts... didn't seem to work anyways.

**Comment by joyceerhl** [comment]
You might try `notebookType == interactive`?

**Comment by joyceerhl** [comment]
There's no documentation for Jupyter when clauses at the moment--any Jupyter when clauses currently in use will appear in our package.json but there's no description for what they mean. It sounds like having extension-level documentation for these might be helpful to you?

**Comment by jaymegordo** [comment]
@joyceerhl yes jupyter-specific documentation on the when clauses would probably help, thank you!

**Comment by IanMatthewHuff** [comment]
Validated + opened https://github.com/microsoft/vscode/issues/128166 this as you have to have selection in specific areas for it to work.
