### ISSUE TITLE
Add a .vscode test for running a non-Python kernel (R, Java, beakerx) installed into a Conda env

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#6544]
We have a test in nonPythonKernels.vscode.test.ts that opens a Java notebook. But we don't seem to have one that runs it. Important test for testing a non-Python language kernel that is installed into a Conda python env.

**Comment by greazer** [comment]
We need this

**Comment by rchiodo** [comment]
So we have a .NET and a Julia test that runs every submission. Do we really need a java test too? Setting up a java kernel is a bit of work. (This one looks like the easiest: https://github.com/Kotlin/kotlin-jupyter)

**Comment by greazer** [comment]
Java may not be the best choice. But maybe R?

**Comment by DonJayamanne** [comment]
We have tests for running Julia notebooks
* Ensure we select the julia kernel when opening a julia notebook
* Ensure we can run a julia notebook
