### ISSUE TITLE
Per-cell line numbers cause issues with other extensions

### ISSUE THREAD

**Issue by circumspect** [microsoft/vscode-jupyter#6556]
## Environment data

-   VS Code version: 1.57.1
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.999662501
-   Python Extension version (available under the Extensions sidebar): 2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows 10 build 19042
-   Python and/or Anaconda version: Python 3.9.1, conda 4.10.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

When using the Error Lens extension ([found here](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens)), error messages from the Problems pane are shown inline on the line where the error occurs.

## Actual behaviour

The error messages are displayed on every open cell at the corresponding line:
![image](https://user-images.githubusercontent.com/40770208/124676638-6e3b7c00-deae-11eb-8014-a919ffd81c36.png)

A similar error occurs with the [markdownlint extension](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) flagging every cell that doesn't start with a title line as incorrect, e.g.,
![image](https://user-images.githubusercontent.com/40770208/124677425-f8381480-deaf-11eb-893a-fe8d4c9c1842.png)
when the user probably wants some markdown cells to denote subsections.

Opening the Problems pane and clicking on a listed problem highlights the correct cell and line, but it seems that extensions are unable to distinguish between cells.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Install the Error Lens extension
2. Create multiple cells, and give each a couple blank lines
3. Introduce a syntax error in one of the cells

**Comment by joyceerhl** [comment]
If I'm understanding the Error Lens extension correctly, it merely amplifies diagnostics being reported for notebooks. We recently fixed a problem in the Python extension's language server support for notebooks which caused diagnostics to be reported for markdown cells. If you opt into the Python Daily Insiders channel (Cmd+Shift+P > Python: Switch to Daily Insiders Channel, wait for the insiders build to finish downloading and installing, and reload when prompted), does the problem persist?

**Comment by joyceerhl** [comment]
FWIW the markdown lint extension is behaving correctly for me:

![image](https://user-images.githubusercontent.com/30305945/124845604-ec019500-df4b-11eb-825c-56a76aea460b.png)

**Comment by joyceerhl** [comment]
Actually the Error Lens extension is also behaving correctly for me:

![image](https://user-images.githubusercontent.com/30305945/124845680-12bfcb80-df4c-11eb-8056-2f33fb6b3cea.png)


I'm using the following extension versions in VS Code Insiders. 

![image](https://user-images.githubusercontent.com/30305945/124845760-3420b780-df4c-11eb-8d79-31021955a4b2.png)

@circumspect any chance you can switch to Insiders and try again? I can't seem to repro the behavior you're describing 😕

**Comment by circumspect** [comment]
Hi,
Thanks for taking a look! I was still running into the issue on stable VS Code even with the Insiders build of the Python extension, so I downloaded the latest portable version of VS Code Insiders. However, the issue persists there as well (I've attached my test notebook [here](https://github.com/microsoft/vscode-jupyter/files/6781204/test.zip)).
![image](https://user-images.githubusercontent.com/40770208/124856497-23972e00-df9a-11eb-9ca9-367e787d5cd5.png)



These are the extensions on VS Code Insiders:
![image](https://user-images.githubusercontent.com/40770208/124856728-930d1d80-df9a-11eb-828f-6c9f47d7aa6e.png)

**Comment by circumspect** [comment]
While the duplicated message doesn't always appear, if I type anything into the final cell, it reappears in the first python cell.

**Comment by joyceerhl** [comment]
Thanks for the info. Looks like we're merging language server results for all cells 🤔 we have some outstanding issues with language server support for notebooks. This may be related to https://github.com/microsoft/vscode-jupyter/issues/5932

**Comment by rchiodo** [comment]
@DonJayamanne did you file the upstream bug?

**Comment by DonJayamanne** [comment]
Done https://github.com/microsoft/pylance-release/issues/2118
