### ISSUE TITLE
Interactive window debug cell doesn't work on Devcontainer/Codespaces with >= ipykernel 6.0.0

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#6560]
1. Create a Codespace from https://github.com/kieferrm/vscode-remote-python
2. Open script.py 
3. Click on Debug Cell codelens 
4. 🐛 immediately throws an exception inside IPython source code

v2021.6.999662501 of Jupyter extension, ipykernel 6.0.1, ipython 7.25.0

**Comment by rebornix** [comment]
It stops at 

```
                # Reset our crash handler in place
                sys.excepthook = old_excepthook
```
