### ISSUE TITLE
Sometimes, cells take time to execute simple tasks

### ISSUE THREAD

**Issue by Syndorik** [microsoft/vscode-jupyter#6562]
## Environment data

-   VS Code version: 1.58.0-insider 4c952751a88154ff4c375b1ca78293ab53a5792a
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1007436305
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: Python 3.9.5 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...):  conda
-   Jupyter server running: Remote

## Expected behaviour
Since last Monday, there is a high latency on my notebooks. When I run a cell sometimes it takes a lot of times to execute. I'm working on a remote server, therefore I first thought it was latency between me and my server, but when I ping the server, latency seems to be normal.

I've seen this error on the logs when cells takes time to execute

```

[2021-07-07 11:00:17.985] [exthost] [error] [ms-python.python] provider FAILED
[2021-07-07 11:00:17.985] [exthost] [error] Canceled: Canceled
	at E.makeCancelError (/home/ubuntu/.vscode-server-insiders/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:9:184136)
	at E.handleFailedRequest (/home/ubuntu/.vscode-server-insiders/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:9:183987)
	at /home/ubuntu/.vscode-server-insiders/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:9:143141
	at async M.provideCompletionItems (/home/ubuntu/.vscode-server-insiders/bin/4c952751a88154ff4c375b1ca78293ab53a5792a/out/vs/server/remoteExtensionHostProcess.js:84:183488)
```
I'm not sure if this is related, but I also have this logs on my runing jupyter server

```

[W 11:05:49.929 NotebookApp] Forbidden
[W 11:05:49.930 NotebookApp] 403 GET /api/sessions?1625655949927 (127.0.0.1) 0.690000ms referer=None
```

**Comment by joyceerhl** [comment]
@Syndorik Thanks for filing a bug! Appreciate your patience with the following questions:

1. Is there anything in the dev tools log if you do Ctrl+Shift+P > Toggle Developer Tools?
2. If you downgrade the Jupyter extension to the version published before last Monday, does the issue persist? --> could be a recent regression in Jupyter extension insiders builds
3. If you switch to VS Code stable, does the issue persist? --> could be a recent regression in VS Code Insiders builds
4. Is there anything special about the code you are running? i.e. would it be possible to share a project that we can possibly execute to reproduce the problem?
5. If you run the same notebook locally (i.e. not connected to a remote server) do you observe the same latency? --> could be something to do with our remote server support

**Comment by Syndorik** [comment]
So I have tried 2 it doesn't help. However it seems that the stable version is working great on remote!

When I run the notebook locally (via WSL), it also seems to work.

When I toggle developer tools I have the following 
![image](https://user-images.githubusercontent.com/28219244/124931341-68ef4600-e002-11eb-8120-eb0f9269d504.png)
The UI PostOffice Received IPyWidgets_msg message seems to appear periodically too. 

I am sorry I can't share a my work project, though the problem appears even on new notebooks

**Comment by greazer** [comment]
Thanks @Syndorik, we're having trouble reproing. Can you be at least a bit more specific about what's in your cells? Is it simple print() statement that can take long time for example? How many cells? Can you do a screen recording of it happening while viewing non-sensitive code? Thanks!

**Comment by Syndorik** [comment]
Yes a simple notebook with a print statement had an execution delay when I was runing it.
But as for today it seems that the bug "disappeared". I don't know what was causing it, but right now it seems to run without delay.
