### ISSUE TITLE
Make Jupyter -> Send Selection to Interactive Window, true by default (iff Python stops auto-installing the Jupyter extension).

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#6565]
This prompt is used to configure whether shift+enter sends selections in Python files to the terminal or interactive window. Looks like it's been removed entirely (no references in either Python or Jupyter extension).

**Comment by joyceerhl** [comment]
This hurts new interactive window users the most because shift+enter will go to the terminal instead of the interactive window

**Comment by greazer** [comment]
This functionality was removed when the Jupyter functionality was moved out of the Python extension and into it's own. This was the commit id: 8f50e87f45943fe486cfbb1c61bbe9d5719ece91. 

Rather than re-add the prompt, we can consider making the jupyter -> Send Selection to Interactive Window true by default, if and when the Python extension removes installing Jupyter by default.

**Comment by rchiodo** [comment]
Blocked on https://github.com/microsoft/vscode-python/issues/18073

**Comment by luabud** [comment]
is the idea here that if users clicked "shift+enter" we'd prompt them to install the Jupyter extension?

**Comment by rchiodo** [comment]
No actually when/if the python extension removes the jupyter extension as an optional dependency, we're going to switch this setting to true:

```
"jupyter.sendSelectionToInteractiveWindow": false
```

**Comment by luabud** [comment]
got it, thanks for the clarification!

**Comment by rebornix** [comment]
It seems we didn't switch `jupyter.sendSelectionToInteractiveWindow` to `true` yet and we might want to reconsider.

**Comment by amunger** [comment]
We shouldn't override that functionality as long as Python still depends on this extension: https://github.com/microsoft/vscode-python/issues/18073

**Comment by amunger** [comment]
I think the current functionality is good - if the file has a # %% cell in it, it will be sent to the IW, we can add a launch configuration as well to make run in IW more discoverable
