### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Jainanish7** [microsoft/vscode-jupyter#6566]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.6.999662501`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.57.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by joyceerhl** [comment]
@Jainanish7 Please fill out our bug template so that we can assist you: https://github.com/microsoft/vscode-jupyter/issues/new?assignees=&labels=bug&template=1_bug_report.md
