### ISSUE TITLE
Debug state and breakpoint gutter get out of sync

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#6570]
I don't have concrete reproducible steps yet but from time to time I end up in an inconsistent UI state. The breakpoint gutter is visible although there is no running debug session. Then I can either see the break points or debug....

![image](https://user-images.githubusercontent.com/4674940/124820811-cd3ad880-df22-11eb-8194-9e1c6e7be97c.png)

**Comment by roblourens** [comment]
Can't happen anymore, the breakpoint gutter is always visible
