### ISSUE TITLE
Plot problem

### ISSUE THREAD

**Issue by Photonico** [microsoft/vscode-jupyter#6580]
Hi,

![](https://raw.githubusercontent.com/Photonico/Problems/master/2021/Screenshot_20210708_125547.png)

As the picture shows:
The DPI of my plot is very low. How can I improve it?
And, I do not want to show this huge extra white space. How to do that?

Thanks

**Comment by greazer** [comment]
@Photonico, With regard to updating the DPI for the graph, that's something you need to do with matplotlib plot parameters.

**Comment by Photonico** [comment]
> @Photonico, With regard to updating the DPI for the graph, that's something you need to do with matplotlib plot parameters.

I use `plt.figure(dpi=192)`, it works.
But the major question is how to cut the white space?

**Comment by nondominetur** [comment]
> > @Photonico, With regard to updating the DPI for the graph, that's something you need to do with matplotlib plot parameters.
> 
> I use `plt.figure(dpi=192)`, it works.
> But the major question is how to cut the white space?

Hi,

Setting the figure facecolor with a color like this:
`plt.gcf().set_facecolor('w')`
or like this:
`plt.rcParams['figure.facecolor'] = 'g'`

This didn't worked for me: `plt.figure(dpi=192)`

**Comment by DonJayamanne** [comment]
Here's my output
First cell has a very low DPI, second cell with same code, but much higher DPI.
FYI -  Please ensure you have changed the mime type from svg+xml to PNG (click on the `...` on the left of the image & change the mime tyep)
![Screen Shot 2021-07-23 at 14 03 40](https://user-images.githubusercontent.com/1948812/126841387-15ff8131-5362-4ac3-86f3-27d096827405.png)

**Comment by Photonico** [comment]
> > > @Photonico, With regard to updating the DPI for the graph, that's something you need to do with matplotlib plot parameters.
> > 
> > 
> > I use `plt.figure(dpi=192)`, it works.
> > But the major question is how to cut the white space?
> 
> Hi,
> 
> Setting the figure facecolor with a color like this:
> `plt.gcf().set_facecolor('w')`
> or like this:
> `plt.rcParams['figure.facecolor'] = 'g'`
> 
> This didn't worked for me: `plt.figure(dpi=192)`

It works, thanks!
