### ISSUE TITLE
Deleting a code cell or converting it to markdown causes diagnostics in other cells to be (permanently?) cleared

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#6581]
Python extension v2021.7.992362372-dev

I can reliably reproduce this problem:

![recording (18)](https://user-images.githubusercontent.com/30305945/124858746-7d303600-df63-11eb-9b93-4e3bb7b1b314.gif)

The existing cell whose diagnostics were cleared doesn't get its diagnostics back even after subsequently modifying its contents or adding new cells. 

Diagnostics are also incorrectly reported thereafter if I add a new cell (and the incorrect diagnostics go away if I delete cell 2):
![image](https://user-images.githubusercontent.com/30305945/124866854-e9b23180-df71-11eb-8304-24e534822317.png)

This may also be related to https://github.com/microsoft/vscode-jupyter/issues/6458

**Comment by joyceerhl** [comment]
I cannot reproduce this in v2021.6.944021595 so this is a regression fyi @rebornix

**Comment by joyceerhl** [comment]
Interestingly deleting cells in the interactive window doesn't cause intellisense to break.

**Comment by joyceerhl** [comment]
![image](https://user-images.githubusercontent.com/30305945/124867771-8fb26b80-df73-11eb-8924-b4794ecef7fe.png)

The diagnostic range coming in here is transparently forwarded to `vscode.NotebookConcatTextDocument.locationAt`, so the location that comes back corresponds to cell 1, and this causes diagnostics for cell 2 to be reported in cell 1:

![image](https://user-images.githubusercontent.com/30305945/124867944-df913280-df73-11eb-8bb6-88ff3f91b02d.png)

**Comment by greazer** [comment]
Looks like this has been fixed. I can't repro either problem that Joyce mentions.
