### ISSUE TITLE
Trying to enable Native Notebook Editor - says 'Value is not accepted. Valid values: "CustomEditor".'

### ISSUE THREAD

**Issue by umernalla** [microsoft/vscode-jupyter#6584]
## Environment data

-   VS Code version: 1.57.1
-   Jupyter Extension version : v2021.6.999662501
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Pro 20H2
-   Python and/or Anaconda version: 3.7.8 64  bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Should be able to add the following to settings.JSON
"workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
    },
    "jupyter.experiments.optInto": [
         "\_\_NativeNotebookEditor\_\_"
    ],

## Actual behaviour

\_\_NativeNotebookEditor\_\_ is not accepted, error:
Value is not accepted. Valid values: "CustomEditor".(1)

## Steps to reproduce:

1. opens Settings.json,
2. Paste in above workbench.editorAssociations and jupyter.experiments.optInto

## Logs

N/A

<p>

```
XXX
```

</p>
</details>

**Comment by greazer** [comment]
@umernalla, This is expected. It will be resolved when we ship Native Notebooks in stable.
