### ISSUE TITLE
Command/button to auto-fit column sizes in the data viewer

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode-jupyter#6585]
It would be handy to have a command or button to automatically fit all column sizes to their contents, to allow comfortably previewing dataframes' contents without having to manually resize all columns.

**Comment by DonJayamanne** [comment]
Thanks for the suggestion, we'll be looking into this when we review our UI for the data viewer.

**Comment by IanMatthewHuff** [comment]
Dupe of #7885
