### ISSUE TITLE
jupyter.enableNativeInteractiveWindow not found

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#6593]
The toggle in the Update note of the VS code June 2021 (version 1.58) and the extension v2021.8.1007436305.
But I couldn't find it. Am I missing something?

https://code.visualstudio.com/updates/v1_58#_jupyter-interactive-window

![image](https://user-images.githubusercontent.com/33796896/124985636-a060f100-e008-11eb-9cf6-749b61a4005b.png)

**Comment by StevenLi-DS** [comment]
@DonJayamanne  Is there any reason why this setting can not be used in workspace settings?

**Comment by joyceerhl** [comment]
@StevenLi-DS We defined it as a user setting:

https://github.com/microsoft/vscode-jupyter/blob/d06d8d8b0c2e8d7db45fcb6dc4434cdb313e6271/package.json#L1490-L1495

**Comment by StevenLi-DS** [comment]
@joyceerhl  Thanks. I just wanna try it out without affecting my global setting, so this is why I didn't find it. lol..
