### ISSUE TITLE
toggle for cell guidelines

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#6606]
Please consider to add a toggle for the cell guideline. I could be very messy sometimes

![Snipaste_100](https://user-images.githubusercontent.com/33796896/125137848-7fb59b80-e0db-11eb-8ff3-9bb6dc73d7ee.png)

**Comment by claudiaregio** [comment]
@StevenLi-DS Thanks for the suggestion, will discuss at our next triage meeting

**Comment by joyceerhl** [comment]
@StevenLi-DS Just to clarify, are you asking for a way to disable the interactive cell decorations (the horizontal blue lines that appear to delimit the start and end of a #%% cell)?

**Comment by StevenLi-DS** [comment]
@joyceerhl No, the decoration already have a toggle. I'm asking for those grey lines.

**Comment by joyceerhl** [comment]
Oh I see. Just to make sure I'm not misunderstanding--you want to have only the blue horizontal lines for the active cell, but not the grey horizontal lines for the other inactive cells?

If that's what you're asking for, we would implement that by conditionally calling `setDecorations` for `this.cellSeparatorType` based on the setting on line 129 here:

https://github.com/microsoft/vscode-jupyter/blob/a536d1fb32a344295af17381689f7e3560a85fc5/src/client/datascience/editor-integration/decorator.ts#L127-L129

**Comment by StevenLi-DS** [comment]
@greazer Indeed. But I wonder if there is a way to define the color of the blue lines as well. What if someone happens to use a blue theme.

**Comment by joyceerhl** [comment]
The color of the blue lines uses VS Code theme tokens, so as long as your theme defines this token, it will work. By changing these colors in your workbench.colorCustomizations setting you can also customize the decoration colors:

https://github.com/microsoft/vscode-jupyter/blob/a536d1fb32a344295af17381689f7e3560a85fc5/src/client/datascience/editor-integration/decorator.ts#L81-L98
