### ISSUE TITLE
Native Notebooks - Deleting cell migrates Pylance issues

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#6608]
## Environment data

-   VS Code version: 1.58.0
-   Jupyter Extension version: v2021.8.1013163132
-   Python Extension version: v2021.6.944021595
-   Pylance Extension version: v2021.7.2

![pylance delete](https://user-images.githubusercontent.com/19276747/125150882-e648b280-e0f7-11eb-9e1a-385ffc57c216.gif)

**Comment by joyceerhl** [comment]
This may be resolved by some of the fixes that @DonJayamanne and @rebornix have added to the Python extension. When the Python extension ships next we should try this again.

**Comment by claudiaregio** [comment]
-   VS Code version: 1.58.2
-   Jupyter Extension version: v2021.8.1054968649
-   Python Extension version: v2021.7.1060902895
-   Pylance Extension version: v2021.7.5

Putting back in new issues as this has not been fixed with the new Python extension release. The diagnostics now move downward instead of upward. 

![pylance delete2](https://user-images.githubusercontent.com/19276747/126888563-614eac38-15fa-407e-8dbc-08cacf7f6425.gif)

**Comment by rchiodo** [comment]
This requires new python bits to verify
