### ISSUE TITLE
Jupyter Notebook experience in VSCode.

### ISSUE THREAD

**Issue by tiger-revaapriyan** [microsoft/vscode-jupyter#6617]
I can't replicate the experience with jupyter-notebook on VSCode in different machines. I have 2 Windows machines a windows server and my pc (both uses Remote Linux for development; I use a Remote Linux machine in Server for development and WSL2 on pc).

The versions of VSCode, Python & Jupyter extensions are the same in both the machines. The jupyter-notebook in the server provides a better experience (as shown in extension details, mainly it supports vim), which I cannot get on my pc.

About VSCode.

```
Version: 1.58.0 (user setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```
Jupyter Extension: `v2021.8.1013163132`
Python Extension: `v2021.6.944021595`

Snap of a *.ipynb* file in Server (which supports VIM & that I want to replicate)

![Jupyter notebook in Machine A][1]

Snap of the same in my pc (which don't support vim).

![Jupyter notebook in my pc][3]

  [1]: https://i.stack.imgur.com/r249J.png
  [3]: https://i.stack.imgur.com/vfL5S.png

I could not figure out what I am missing.

**Comment by weidenka** [comment]
Same here. Only on the insider build of vscode I see the new interface.

**Comment by joyceerhl** [comment]
The new interface is currently available to all VS Code Insiders users and a fraction of VS Code Stable users. To opt into the new interface via your settings.json file, please see instructions here: https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code#enabling-the-new-experience

**Comment by tiger-revaapriyan** [comment]
Thanks! Happy Developing!
