### ISSUE TITLE
jupyter output rendering error

### ISSUE THREAD

**Issue by wkdguswo16** [microsoft/vscode-jupyter#6619]
Issue Type: <b>Bug</b>

The new jupyter-extension has a problem with rendering text output. It didn't apply by editor.font-family. I tried many things but still doesn't work.
![image](https://user-images.githubusercontent.com/45989093/125160311-33d82480-e1b7-11eb-953e-c506858e03e2.png)
I'm using D2Coding ligature font and the output font may be monospace.

Extension version: 2021.8.1013163132
VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (5.30GB free)|
|Process Argv|--crash-reporter-id e85599f9-a4d9-4759-9b35-d64197672f57|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by joyceerhl** [comment]
This is likely blocked on VS Code https://github.com/microsoft/vscode/issues/123149 Please upvote that issue to indicate your support for it. Thanks!
