### ISSUE TITLE
Variables Pane for Python Console

### ISSUE THREAD

**Issue by cbailiss** [microsoft/vscode-jupyter#6621]
I am attempting to use the REPL approach to develop Python, as essentially described here:
https://code.visualstudio.com/docs/python/editing#_run-selectionline-in-terminal-repl
i.e. highlighting subsets of lines, SHIFT+ENTER to execute in the Python Console in the Terminal pane.
This is iterative, writing code, executing, repeat.  Variable values accumulate as work progresses.
Seeing variable values change whilst editing the code is instant feedback and very productive.
At present, there is no way to easily see variable values in the UI when working this way in VS Code.

PyCharm offers a very nice simple, compact and fast variable explorer as part of its Python Console
![image](https://user-images.githubusercontent.com/11745789/125165287-49852400-e18e-11eb-921e-5393428907b6.png)
This pane also understands core Python data types well.

In VS Code, I am aware of the functionality of using the `# %%` however this clutters code with comments and the UI is too much like Jupyter - i.e. another vertical pane, another console pane instead of existing Python Console, another input window, plus it renders the output like Jupyter rather than just focussing on variable values.  SHIFT+ENTER still executes to the Console window.  All-in-all, a jarring and cluttered experience.
Really, I want a variables explorer that is simpler, cleaner, faster and that is more aligned to working with the Python Console than Jupyter use cases.  Without that, I am finding it difficult and frustrating to work with VS Code.  
As an aside, I come from a background of almost 20 years working with C# (where I expect a compile-run-debug experience) and 5 years working with R.  Modern Python development feels like to should support clean, simple, efficient REPL.  R-Studio enables REPL with variable inspection for R (inc. when editing *.R files) in a really clean efficient way that VS Code doesn't seem to for *.py files.

I am aware this request is similar to https://github.com/microsoft/vscode-jupyter/issues/3469 - hopefully I have explained my use reasoning above to avoid a repeat of the frustration present in that issue:

If this isn't the correct repo/MS Team for this request (e.g. does another team own the Python Console?), please let me know.

**Comment by joyceerhl** [comment]
In other words, you would like to be able to inspect variables while working in the Python REPL provided by https://github.com/microsoft/vscode-python.

We are exploring potentially moving the Jupyter extension's variable explorer to be a built-in feature in VS Code that extensions can populate; this sounds like a good use case for such an API. The Python extension would then populate the variable explorer with variable info for its REPL.

Alternatively the Jupyter extension could reimplement a pared-down version of the interactive window that looks more like a REPL--would that meet your needs?

**Comment by cbailiss** [comment]
Thank you for the reply.  Yes, you summarised it perfectly in your first sentence.  I took far more words to say the same thing! - in the hope of providing context/explanation.

In terms of the two options, the first sounds better.  I assume it could be visible/docked next to the interactive terminal pane as in PyCharm since that feels most intuitive.  I can well imagine other extensions/languages in VS Code would benefit and users arriving from other tools/ecosystems (e.g. R-Studio) into using VS Code would expect a variables pane.

The second option sounds like it would still be Jupyter under the surface (albeit less visual clutter), which sounds like a compromise. I'd rather this work with plain simple Python Console as opposed to Jupyter.

**Comment by joyceerhl** [comment]
> I'd rather this work with plain simple Python Console as opposed to Jupyter.

Is this because you would rather not have to install Jupyter kernels and kernel dependencies like `ipykernel`? I ask because if the first is the preference, then this feature request would probably be for the Python extension as well as VS Code itself. The second option is more within the Jupyter extension's wheelhouse, since the mechanism that the variable explorer is currently populated with depends on querying a live Jupyter kernel for variable values.

**Comment by amunger** [comment]
thanks for the suggestion, unfortunately this has not generated enough interest for us to prioritize
