### ISSUE TITLE
Should the interactive window always skip the CellMarker line

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#6623]
When `collapse all cell inputs` is enabled, the first line under the CellMarker (# %%) shows in the interactive window to help you easily identify a particular cell, but once you put something after it. The CellMarker line will show instead. This makes each cell hard to identify if you happen to use the CellMarker line as a separator

![Snipaste_754](https://user-images.githubusercontent.com/33796896/125173359-e777ef00-e18c-11eb-9f8d-3ae44a028d11.png)

I hope you guys could pls consider adding a toggle to always skip the CellMarker line or maybe even to let users select how many lines of code they wanna see when  `collapse all cell inputs` is enabled:
![Snipaste_727](https://user-images.githubusercontent.com/33796896/125173360-e8a91c00-e18c-11eb-9268-926c01d7d4ad.png)

**Comment by joyceerhl** [comment]
@StevenLi-DS we are working on porting the interactive window to use built-in VS Code UI. We have an outstanding issue tracking allowing showing the first code line when collapsing cell input in the new built-in UI https://github.com/microsoft/vscode/issues/119776#issuecomment-873483243 but we already skip the cell marker line in this implementation:

![image](https://user-images.githubusercontent.com/30305945/125175170-2141f900-e17f-11eb-8f67-68d132f11968.png)

**Comment by StevenLi-DS** [comment]
@joyceerhl Thanks for the info and this is shocking to me since I'm not a fan of this UI at all (so far). So the jupyter extension will eventually use this UI???

**Comment by joyceerhl** [comment]
For context, the goal of porting the interactive window to use built-in UI is so that VS Code themes, keybindings, snippets etc. will work in the interactive window.

The UI is still a work in progress and we would love to hear how we can make this UI work better for you. We are already aware of several problems, e.g. 
* Input box to be larger https://github.com/microsoft/vscode/issues/126415#issuecomment-875721427
* Toolbar to show only icons https://github.com/microsoft/vscode/issues/125551
* Interactive cell code to be collapsed https://github.com/microsoft/vscode/issues/119776#issuecomment-873483243

**Comment by StevenLi-DS** [comment]
@joyceerhl Thank you. I tried it yesterday, and it seems like lots of basic feature is still missing currently the current UI used in the extension, and I'll try it out from time to time along its development.

**Comment by joyceerhl** [comment]
If you spot any missing features, they are most likely unintentionally omitted and we will be implementing them this month. Please file bug reports on this repo so we can ensure they are added back: https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+is%3Aopen+label%3Ainteractive-window

Additionally, if there are any aspects of the UI that you don't enjoy, please let us know as well. We really want to ensure that the interactive window becomes even more enjoyable to use for our existing users after this transition is complete, and your early feedback helps us identify and resolve issues. Thank you so much 😊
