### ISSUE TITLE
VSCode Insiders - IPYNB to PDF export failed

### ISSUE THREAD

**Issue by RazvanCretu** [microsoft/vscode-jupyter#6624]
## Environment data

-   VS Code version: 1.59.0-Insiders
-   Jupyter Extension version (available under the Extensions sidebar): 2021.8.1013163132
-   Python Extension version (available under the Extensions sidebar): 2021.6.944021595
-   OS and version: Winows 10
-   Python and/or Anaconda version: Python from Anaconda 3.8.10 
-   Type of virtual environment used: N/A
-   Jupyter server running: Local 

## Expected behaviour

I'm expecting this to work everytime I click on the export button on the toolbar. It works in normal VSCode.

## Actual behaviour

Right when I open a notebook and try to export it right away it works.. but nothing happens if I run a cell and then I try to export it again. 

I tried to export it from the command pallette and I got the following error here:

![image](https://user-images.githubusercontent.com/38960348/125182505-310d1c00-e217-11eb-866b-47f5f164cf25.png)

## Steps to reproduce:

1. Create a `.ipynb` file 
2. Write a simple `print("Hello world!")` code
3. Try to export to pdf

**Comment by joyceerhl** [comment]
@RazvanCretu Would you mind providing the contents of the Jupyter output panel, please? That usually contains logs which might help us identify the problem.

**Comment by RazvanCretu** [comment]
Hi @joyceerhl 

Here it is:
![image](https://user-images.githubusercontent.com/38960348/125202949-bf68b880-e27e-11eb-8647-1451a3d5d34b.png)

Thanks for letting me know, I'm still discovering the VSCode and didn't knew where to look for outputs..
