### ISSUE TITLE
IntelliSense does not work in new "Native Built-in Interactive Window"

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/vscode-jupyter#6629]
## Environment data

-   VS Code version: 1.58.0
-   Jupyter Extension version (available under the Extensions sidebar): 2021.8.1013163132
-   Python Extension version (available under the Extensions sidebar): 2021.6.944021595
-   OS and version: Windows_NT x64 10.0.19041
-   Python and/or Anaconda version: Python 3.8.8 | Anaconda 2021.05
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Expected behaviour

IntelliSense should work in the new interactive window like it does with the old interactive window, show below:

![gif3](https://user-images.githubusercontent.com/57204023/125210809-685fe500-e278-11eb-8be2-c0c9748d6fa4.gif)

## Actual behaviour

IntelliSense dow not work in the new interactive window, show below:

![gif4](https://user-images.githubusercontent.com/57204023/125210814-71e94d00-e278-11eb-8df8-f4e18094ad83.gif)

## Steps to reproduce:

1. Configure `"jupyter.enableNativeInteractiveWindow": true`
2. Reload window in VS Code to apply the setting.
3. Run some piece of code in the interactive window with object definitions, import packages, etc.
4. Try to access objects atributes or packages functions in the interactive window with "`.`"

**Comment by joyceerhl** [comment]
@Diogo-Rossi IntelliSense for the built-in interactive window is available in the Python extension's Insiders Daily builds. If you run the 'Python: Switch to Insiders Daily Channel' command from the command palette, that should download a version of the extension with preliminary IntelliSense. Please let us know if that works for you 😊

**Comment by Diogo-Rossi** [comment]
@joyceerhl Yes, that worked!
So, for now the "Default Channel" does not have it yet, am I right?

**Comment by joyceerhl** [comment]
That's right. The Python extension will be releasing a stable build with IntelliSense for the interactive window sometime next week.
