### ISSUE TITLE
Decorate VS Code Interactive Window with additional meta data (e.g. proces ID)

### ISSUE THREAD

**Issue by aviolov** [microsoft/vscode-jupyter#6638]
I often debug a python interactive session that calls external C#, C++ or CUDA code by attaching an external debugger to the python process. I always type `os.getpid()` to get the process to attach-to, but in trying to save a few keystrokes, I wonder if there is a way to decorate the interactive window in VS Code with the pid?

To make this more generic - adding arbitrary meta-data that can be queried in the user's startup.py file to the interactive window might be useful. 

Copied from: https://stackoverflow.com/questions/68260744/decorate-vscode-jupyter-interactive-window-with-python-process-id?noredirect=1#comment120691117_68260744

Thanks

**Comment by joyceerhl** [comment]
Thanks for the suggestion, this is interesting. Could be something we add to the sysinfo cell that we include on startup.

**Comment by thomasfrederikhoeck** [comment]
Another idea (if possible) would be to integrate it directly into the launch such that it uses the process ID of the kernel running the  nodebook. It could look something like the following. This would make it extremely easy to debug as it would only require to hit F5 :-) :
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false,
        },
        {
            "name": "Python: Attach using Process Id",
            "type": "python",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "justMyCode": false
          }
        {
            "name": "Python: Attach to Jupyter Notebook",
            "type": "python",
            "request": "attach",
            "processId": "${jupyter:currentprocessid}",
            "justMyCode": false
          }
    ]
}

```

**Comment by thomasfrederikhoeck** [comment]
From the VS Code docs it would seem it would be possible to add it to the Jupyter extension in the same way as the NodeJS: https://code.visualstudio.com/docs/editor/variables-reference#_command-variables

**Comment by amunger** [comment]
closing as this issue hasn't generated enough interest to justify the investment
