### ISSUE TITLE
View dataframe via Data Viewer, filter based on column with boolean dtype doesn't work

### ISSUE THREAD

**Issue by heidler** [microsoft/vscode-jupyter#6639]
## Environment data

-   VS Code version: 1.58.0
-   Jupyter Extension version: v2021.8.1013163132
-   Python Extension version: v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows (19043.1083)
-   Python and/or Anaconda version: Python 3.8.5 (64-bit)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): WSL2
-   Jupyter server running: Local

## Expected behaviour

Filtering with boolean values (true/false). When filter via "true" or "1", I should get only true values. With "false" or "0", should be false values.

## Actual behaviour

With false everything works, with true it does not how it supposed to be.

## Steps to reproduce:

![image](https://user-images.githubusercontent.com/8638578/125339033-38384500-e351-11eb-885d-bc30fbee7460.png)
![image](https://user-images.githubusercontent.com/8638578/125339075-41291680-e351-11eb-92d2-5ec58a77b4aa.png)

**Comment by joyceerhl** [comment]
We don't seem to be handling the ColumnType.Bool case. @heidler did this ever work for you?

**Comment by heidler** [comment]
> We don't seem to be handling the ColumnType.Bool case. @heidler did this ever work for you?

For me, it never worked, so as you said, it's not bug, but enhancement! :)

I think the filter should work on every ColumnType. That would be awesome.

**Comment by joyceerhl** [comment]
@heidler If you don't mind I'd like to keep this feature request open :)

**Comment by heidler** [comment]
Ah, sure! I'm Github newbie, I thought I should closed it. :) Thanks @joyceerhl

**Comment by DonJayamanne** [comment]
Tested this at my end and this seem to work now.
Hence closing this.
