### ISSUE TITLE
Scrolling and saving notebooks can be slow or laggy

### ISSUE THREAD

**Issue by bkaplowitz** [microsoft/vscode-jupyter#6645]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.8.1013163132`
- OS Version: `Darwin x64 20.5.0`
- VS Code version: `1.58.0`

Hi for some reason, Jupyter keeps seeming to hang and lags when scrolling on occasion or saving. This doesn't happen outside ipynb files.
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 211,
		"activateCallTime": 4,
		"activateResolvedTime": 521,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-toolsai.jupyter",
				"_lower": "ms-toolsai.jupyter"
			},
			"activationEvent": "onLanguage:python"
		}
	},
	"runtimeErrors": []
}
```

**Comment by claudiaregio** [comment]
Hi @bkaplowitz, are you working with native notebooks? (Providing a screenshot of your notebook interface will tell us)

**Comment by bkaplowitz** [comment]
I believe it is the non-native notebook. 
<img width="1299" alt="Screen Shot 2021-07-13 at 12 47 06 PM" src="https://user-images.githubusercontent.com/8681308/125492810-645f699e-7440-4e7d-8753-852f3beddf07.png">

**Comment by claudiaregio** [comment]
@bkaplowitz this actually is native notebooks 🎉 
Improving scroll is actually being tracked here: https://github.com/microsoft/vscode/issues/126880. 
If you have any information or notebooks that you are able to share where we can reproduce the lag while scrolling could you please provide them in the issue mentioned? 

When you say "lags when ... saving", do you mean it takes a long time to save?

**Comment by bkaplowitz** [comment]
The entire notebook unfortunately freezes on occasion in response to a save
or click and I become unable to click anything inside the cells or move the
notebook at all.

**Comment by bkaplowitz** [comment]
After about 5 to 10 seconds it unfreezes and I can move everything again.

**Comment by joyceerhl** [comment]
@bkaplowitz How many cells are there in your notebook? Could you share the ipynb file (zip it up and attach it to a comment)?

**Comment by greazer** [comment]
Issues labeled with "Info needed" are closed if we do not receive more information from the issue author in 2 weeks. If you are the issue author and you still are running into this problem, please reactivate with the additional information requested.
