### ISSUE TITLE
interactive window and jupyter notebook not starting

### ISSUE THREAD

**Issue by timpiperseek** [microsoft/vscode-jupyter#6646]
Hello, I seem to be having an issue with getting interactive windows and jupyter notebooks to work.

VS code is telling me to open the Developer: toggle developer tools and inside there it says.

extension activation failed Error: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

If you could assist it would be appreciated.

## Environment data

-   VS Code version: 1.58
-   Jupyter Extension version v2021.8.1013163132
-   Python Extension version : v2021.6.944021595
-   OS: Running WSL (Ubuntu 18.04) on Windows 10
-   Python and/or Anaconda version: 3.7.5
-   Type of virtual environment used N/A
-   Jupyter server running: Local 

## Expected behaviour

opens interactive window and runs code
and 
opens jupyter notebooks and runs code

## Actual behaviour

interactive window opens but code is never run. It just sits there loading.
and
jupyter notebook only opens in raw text format.

let me know if I can provide anything else

**Comment by joyceerhl** [comment]
> Error: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

That message suggests that your user settings file has invalid content. If you open your user settings.json, do you see any squiggles flagging errors in the contents, and if you fix them does the extension start working?

**Comment by timpiperseek** [comment]
yes, there was an issue there.  It all seems to be working now. thankyou
