### ISSUE TITLE
Lines executed from the editor are not added to the command history

### ISSUE THREAD

**Issue by Iqigai** [microsoft/vscode-jupyter#6647]
## Environment data

-   VS Code version: 1.58 v2021.8.101
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Pro - Version 21H1 build 19043.1083
-   Python version: 3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour
When executing code from the editor, it is not added to the history of the jupyter interactive console

## Actual behaviour
All the code execute in the Interactive Window should be sequentially added to the history, regardless of it the origin, may it be from the editor or typed directly in the interactive window. 

## Steps to reproduce:
0- Open any python file or create a new one with a simple line of code such as:
print('Hello World')
1- Position the cursor on this line of code in the text editor. Right click and select execute "Run Selection/Line in interactive window"
2- Position the cursor in the interactive window input line. Use the up arrows to recall the line that was just executed
3- The "print('Hello World')" line should appear in the prompt

## Logs
N.A 
``

</p>
</details>

**Comment by andycraig** [comment]
I would like this feature too. I created a similar issue: https://github.com/microsoft/vscode-jupyter/issues/1628

**Comment by Iqigai** [comment]
Closing it since it is a duplicate of [https://github.com/microsoft/vscode-jupyter/issues/1628](url)
