### ISSUE TITLE
Lost all changes made in my notebook

### ISSUE THREAD

**Issue by mastats** [microsoft/vscode-jupyter#6649]
## Environment data

-   VS Code version: 1.57.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.999662501
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Changes are saved in my jupyter notebook. 

## Actual behaviour

Changes are not saved.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. I saved the changes I made to the notebook
2. I closed the file and opened the source control panel to stage my changes. But the panel said that there were no changes. I could only see a staged changed of the same file that I did 2 days ago but no the changes I made to the file since then.
3. I proceed to open the file and all my changes were gone

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by mastats** [comment]
Hi
Is there a way I can recover the changes I made? I need to submit this project tomorrow :( :(

Thanks in advance.

**Comment by DonJayamanne** [comment]
Apologies for the delay in getting back to you .
We have shipped a new UI for the Notebook. Please could you take a screenshot of the notebook and upload it.

**Comment by greazer** [comment]
Issues labeled with "Info needed" are closed if we do not receive more information from the issue author in 2 weeks. If you are the issue author and you still are running into this problem, please reactivate with additional information.
