### ISSUE TITLE
Add ability to tag cells in Jupyter notebook

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-jupyter#6650]
### Discussed in https://github.com/microsoft/vscode-python/discussions/16598

<div type='discussions-op-text'>

<sup>Originally posted by **scottsmith1474** July  1, 2021</sup>
Love the new jupyter notebook interface, would love to be able to tag cells like you can in jupyter lab. Table of contents would seal the deal as well.

Thanks!</div>

**Comment by claudiaregio** [comment]
Hi @scottsmith1474, you can find the table of contents in the File Explorer side bar in the Outline tab

![image](https://user-images.githubusercontent.com/19276747/125526894-b62db13e-d44a-4167-868e-036bdfd58a18.png)
![image](https://user-images.githubusercontent.com/19276747/125526979-0ada41a9-3d8b-4105-9216-73d98c325e26.png)

**Comment by claudiaregio** [comment]
@scotthsmith1474 If you'd like to show support for the other request you have raised, I believe it is this one here: https://github.com/microsoft/vscode/issues/103519
