### ISSUE TITLE
Tmux kind of process in interactive window

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-jupyter#6651]
### Discussed in https://github.com/microsoft/vscode-python/discussions/16618

<div type='discussions-op-text'>

<sup>Originally posted by **sergei3000** July  5, 2021</sup>
I often use the Python extension in a remote SSH window which I open using an SSH tunnel. Whenever the tunnel (or just a regular SSH session) breaks all my environment and its variables are lost. And among those variables there's often a connection to a remote cluster's session which cannot be serialized.
So it would be great if the Python interactive window, that is started by running cells marked by "# %%", could be optionally opened with a kind of tmux process. Just so I could reconnect to it after breaking that ssh connection.</div>

**Comment by DonJayamanne** [comment]
Dup of https://github.com/microsoft/vscode-jupyter/issues/3998
