### ISSUE TITLE
Jupyter window dose not look like the vs code introduction page.

### ISSUE THREAD

**Issue by OMGLee** [microsoft/vscode-jupyter#6662]
## Environment data

-   VS Code version: 1.58.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1013163132
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: macOS 11.4
-   Python and/or Anaconda version: Python 3.8.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

After updating the Jupyter extension, the introduction page shows a different view of Jupyter working window

<img width="988" alt="new look-07-14_18-54-55" src="https://user-images.githubusercontent.com/11349103/125611461-f1a84702-6094-4ff2-92fa-8a1afef7bb83.png">

## Actual behaviour

<img width="1229" alt="old look_2021-07-14_18-55-20" src="https://user-images.githubusercontent.com/11349103/125611541-1e749227-0a88-4130-b2cd-c780e3ee68a2.png">

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

Preference Json.

``` Json
{
    "security.workspace.trust.untrustedFiles": "open",
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter.notebook.ipynb"
    },
    "python.pythonPath": "/usr/local/bin/python3",
    "python.defaultInterpreterPath": "/usr/local/bin/python3",
    "jupyter.jupyterServerType": "local",
    "workbench.colorTheme": "Default Light+",
    "window.autoDetectColorScheme": true

}

```

1. pip3 install

- jupyter
- jupyter lab
- 

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by Aperture77** [comment]
Isn't the new notebook interface only availiable in VSCode Insiders ? Works fine on VSCode Insiders 1.59

**Comment by rchiodo** [comment]
@OMGLee the introduction page is ahead of the release bits. We're about to switch the UI for all users over to the new UI but the docs are already there.
