### ISSUE TITLE
The Interactive kernel does not same to the python interperter which I selected for the python file.

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/vscode-jupyter#6667]
## Environment data

-   VS Code version: 1.58.1
-   Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS and version: Win20
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9;3.7;3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): both
-   Relevant/affected Python packages and their versions: 
-   Relevant/affected Python-related VS Code extensions and their versions: 
-   Value of the `python.languageServer` setting: Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

When I run: _Jupyter: Create Interactive Window_ command. The kernel follows the python interpreter I selected for the python file.

## Actual behaviour

When I run: _Jupyter: Create Interactive Window_ command. The kernel does not follow the python interpreter I selected for the python file for some time.

After I deleted some cache of the VSCode, it works well.

I deleted all the files and folders under this location:
C:\Users\${UserName}\AppData\Roaming\Code\User\globalStorage

**Comment by rchiodo** [comment]
Thanks for the bug. This should be resolved in our next release. See this bug here: https://github.com/microsoft/vscode-jupyter/issues/6409
