### ISSUE TITLE
Investigate ZMQ issues in current Stable build

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#6669]
@rebornix @DonJayamanne and I were debugging a separate issue with kernels and discovered that ZMQ doesn't work so users are being prompted to fallback to `notebook`, possibly due to us lagging VS Code in Node version

**Comment by DonJayamanne** [comment]
Not a problem, it never worked for me as I'm on a macm1.
Please feel free to re-open if it doesn't work for you (@joyceerhl ) in stable
