### ISSUE TITLE
[Notebook] Missing Restart Kernel Button

### ISSUE THREAD

**Issue by rogueanx9** [microsoft/vscode-jupyter#6670]
## Environment data

-   VS Code version: 1.59.0 - Insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1025925145
-   Python Extension version (available under the Extensions sidebar): v2021.7.1012204448-dev
-   OS (Windows | Mac | Linux distro) and version: Windows 10 21H1
-   Python and/or Anaconda version: Miniconda 3 [Python 3.7.6]
-   Type of virtual environment used : conda
-   Jupyter server running: Local

## Expected behaviour

Restart Kernel button available.
![image](https://user-images.githubusercontent.com/59089013/125705926-21f44206-51bf-4ca7-b4ad-168a6aacedb3.png)

## Actual behaviour

There is no restart kernel button.
![image](https://user-images.githubusercontent.com/59089013/125705897-71fad63d-86e0-4d88-9a74-13c2acf5b17f.png)

## Steps to reproduce:

1. Just open notebook

**Comment by joyceerhl** [comment]
This is due to a bug in VS Code Insiders--should be fixed in the next VS Code Insiders build.
