### ISSUE TITLE
Creating interactive window scans for all kernel specs

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#6672]
Issue Type: <b>Bug</b>

* Open a python file
* Run code from code lens
* Check the output log, it scans for all kernel specs

Extension version: 2021.8.1025925145
VS Code version: Code - Insiders 1.59.0-insider (9520f0a515e7e24802c92f885a0efb242fca3831, 2021-07-14T07:15:41.024Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by joyceerhl** [comment]
@rebornix This is expected behavior, no? Otherwise the kernel picker will not be populated with kernels.

**Comment by rebornix** [comment]
It's an expected behavior, but the scanning starts too early and slows down the requested code execution. It can affect the speed of daemon and the kernel creation (by using more cpu cycles) and also main thread of extension host. Curious about how much we can gain for postponing everything not needed for the first cell execution (including the second kernel process for faster restart purpose). Any ideas?

**Comment by DonJayamanne** [comment]
> Any ideas?

Previously the second kernel process used to start immidiately, I moved the code to when we we run some code against the first kernel process. This resulted in a big improvement (hence the reason for changing that). I'm certain that removing it entirely will have benefits. Lets discuss offline today.

**Comment by amunger** [comment]
improvements have been made, wont fix for now
