### ISSUE TITLE
Jupyter Continues on Error even if "jupyter.stopOnError": true in the new native Window

### ISSUE THREAD

**Issue by 1vecera** [microsoft/vscode-jupyter#6673]
****
## Environment data
**New native window turned on**
-   VS Code version1.5.81
-   Jupyter Extension version (available under the Extensions sidebar): 2021.8.103..
-   Python Extension version (available under the Extensions sidebar): 2021.6.944..
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.8.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Jupyter server running: Local 

Setting
"jupyter.stopOnError": true

## Expected behaviour

After an error occurs, no further cells are executed.

## Actual behaviour

Jupyter continues running after errors are encountered.

## Steps to reproduce:

Code

```
#%%
assert 0 =1
#%%
print("im running")
```
Run all Cells

**Comment by DonJayamanne** [comment]
Thanks for filing this issue. I've tested this at my end and it seems to work as expected.
We're currently overhauling our interactive window experience, its possible you're using the new UI.
Please could you take a screenshot of the interactive window.

@joyceerhl I tested this and it works as expected in webview based interactive, but not in the new UI.

**Comment by 1vecera** [comment]
@DonJayamanne Yes, it's in the new native interactive window. I've adjusted my issue.

**Comment by joyceerhl** [comment]
@1vecera This should be fixed in the latest Jupyter insiders build. Please let us know if it's working for you 😊

**Comment by 1vecera** [comment]
Works like a charm, thanks @joyceerhl!
