### ISSUE TITLE
Cell `three dot` button not working

### ISSUE THREAD

**Issue by appledora** [microsoft/vscode-jupyter#6680]
## Environment data

-   VS Code version: c3f12631
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1013163132
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Pop!_OS 20.04 LTS x86_64
-   Python and/or Anaconda version: Python 3.8.5

-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour
![image](https://user-images.githubusercontent.com/27975232/125863135-69b4695c-7100-454c-968f-0a6924166d30.png)
Would expect to be able to right-click on the `three dot` button.
XXX

## Actual behaviour
deletes the cell
XXX

## Steps to reproduce:
Just trying to use the notebook in an usual manner, after the new UX update.

**Comment by appledora** [comment]
Fixed it by tinkering my `setting.json` :
```json
{
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Tinacious Design",
    "editor.minimap.enabled": false,
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
    },
    "ponicode.token": "91920adf-24aa-4b70-9f87-c263c0c30e84",
    "workbench.startupEditor": "none",
    "notebook.cellToolbarLocation": {
        "default": "right",
        "jupyter-notebook": "left"
    },
    "editor.inlineSuggest.enabled": true,
    "notebook.lineNumbers": "on",
    "jupyter.experiments.optOutFrom": [
    
    ],
    "notebook.cellFocusIndicator": "border",
    "notebook.cellToolbarVisibility": "hover",
    "notebook.consolidatedRunButton": true,
    "jupyter.addGotoCodeLenses": false,
    "jupyter.enableNativeInteractiveWindow": true,
    "jupyter.themeMatplotlibPlots": true,
    "jupyter.useDefaultConfigForJupyter": false,
    "jupyter.exportWithOutputEnabled": true,
    "notebook.compactView": false,
    "notebook.insertToolbarLocation": "notebookToolbar",
    "notebook.outline.showCodeCells": true,
    "notebook.showFoldingControls": "always"
}
```
Not exactly sure, what fixed the issue. However, the `run cells above` and the `run cells below` buttons are gone and compacted within the `execute cell` button as a drop-down. 
![image](https://user-images.githubusercontent.com/27975232/125948587-6f1fea4b-639c-462a-8140-864577986b1b.png)

**Comment by joyceerhl** [comment]
@appledora The setting that controls whether run above/below appears in the dropdown or cell toolbar is `notebook.consolidatedRunButton`. To put those buttons back into the toolbar, you'll want to change that setting to `false`.

**Comment by appledora** [comment]
> @appledora The setting that controls whether run above/below appears in the dropdown or cell toolbar is `notebook.consolidatedRunButton`. To put those buttons back into the toolbar, you'll want to change that setting to `false`.

Thanks @joyceerhl . I had totally missed that option!
