### ISSUE TITLE
Can't run single cells using keyboard

### ISSUE THREAD

**Issue by appledora** [microsoft/vscode-jupyter#6681]
## Environment data

 - VS Code version: c3f12631

 - Jupyter Extension version (available under the Extensions sidebar): v2021.8.1013163132

 - Python Extension version (available under the Extensions sidebar): v2021.6.944021595

 - OS (Windows | Mac | Linux distro) and version: Pop!_OS 20.04 LTS x86_64

 - Python and/or Anaconda version: Python 3.8.5

 - Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

 - Jupyter server running: Local

## Expected behaviour
![image](https://user-images.githubusercontent.com/27975232/125863513-2fe18f48-6549-4f31-bda2-bf3f0aadeb11.png)

Would expect cell to run on pressing `windows + enter` or `ctrl + enter`

## Actual behaviour
Nothing happens. Have to manually run each cell.

**Comment by appledora** [comment]
In case, you want to see the keybinding for cell run: 
![image](https://user-images.githubusercontent.com/27975232/125946367-d26308a0-5c1f-4ade-ba10-d3c291b2a6dd.png)

**Comment by appledora** [comment]
I think I fixed this by tinkering with my settings.json :
```json
{
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Tinacious Design",
    "editor.minimap.enabled": false,
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
    },
    "ponicode.token": "91920adf-24aa-4b70-9f87-c263c0c30e84",
    "workbench.startupEditor": "none",
    "notebook.cellToolbarLocation": {
        "default": "right",
        "jupyter-notebook": "left"
    },
    "editor.inlineSuggest.enabled": true,
    "notebook.lineNumbers": "on",
    "jupyter.experiments.optOutFrom": [
    
    ],
    "notebook.cellFocusIndicator": "border",
    "notebook.cellToolbarVisibility": "hover",
    "notebook.consolidatedRunButton": true,
    "jupyter.addGotoCodeLenses": false,
    "jupyter.enableNativeInteractiveWindow": true,
    "jupyter.themeMatplotlibPlots": true,
    "jupyter.useDefaultConfigForJupyter": false,
    "jupyter.exportWithOutputEnabled": true,
    "notebook.compactView": false,
    "notebook.insertToolbarLocation": "notebookToolbar",
    "notebook.outline.showCodeCells": true,
    "notebook.showFoldingControls": "always"
}
```

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, I think we might have a problem at our end, will check this out, thanks.
& sorry for any inconvenience.
