### ISSUE TITLE
Is it possible to add 'Enter interpreter path...' function like the Python extension provided to add the interpreter path?

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/vscode-jupyter#6684]
The Python interpreter selection list in Python extension:

![Capture](https://user-images.githubusercontent.com/21306413/125898400-abd5647f-941b-4d3f-be77-cb9d89cd492d.PNG)

In the Jupyter notebook, it has no method to add the new interpreter path:
![Screenshot (11)](https://user-images.githubusercontent.com/21306413/125898511-69c01d3e-19c0-44a0-9710-62ddb21d1a0e.png)

**Comment by DonJayamanne** [comment]
Thanks for filing this issue. 
Out of curiousity why do you need that.
Today if you add an interpreter into the Python Intpreter list, the Jupyter extension will pick that up.

I.e. if you want the Jupyter extension to show your custom interpreter in the list of kernels, then all you need to do is add that to the list of Python interpreters the way you have already suggested.

Closing this issue as we have no plans to add ability to register custom interpreters with Jupyter, as this falls into the Python extension.
Please feel free to let us know if that solution doesn't work, & we'll re-open thi sissue or please feel free to create a new issue.
