### ISSUE TITLE
Interactive Jupyter Can't Find Kernals In Virtual Environments

### ISSUE THREAD

**Issue by ivanthewebber** [microsoft/vscode-jupyter#6687]
Issue Type: <b>Bug</b>

Starting about a week ago I haven't been able to use virtual environments for my Jupyter Kernals. This is a problem because I need to install different libraries for different datasets.

I just tried reverting to an older version of the Jupyter extension and I can now use virtual environments for the kernel. Please find and modify the breaking change.

Extension version: 2021.8.1013163132
VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (16.20GB free)|
|Process Argv|C:\\Users\\ivwebber\\Data\\TR\\RecallDataset --crash-reporter-id 05385942-5ae3-499d-9b9e-5378f18fdccb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30321513
vshan820:30294714
vscus158:30321503
vscod805cf:30301675
bridge0708:30335490

```

</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, please could you:
* Repro the issue with the latest version of the extension & upload the contents of the `Jupyter` output panel
* Please provide the name of the kernel/virtual environment that isn't being listed (so i know what to look for).

**Comment by joyceerhl** [comment]
@ivanthewebber Sorry for the inconvenience. We found an issue with picking kernels for the interactive window and the fix is available in Insiders. Fix will be released in the Stable update that goes out either tomorrow or Thursday. Please let us know if it's not working for you!
