### ISSUE TITLE
Perf improvements for starting kernels (perf resulting from checking packages & dependencies)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#6694]
Starting kernels, Startingn debugger, checking dependencies
All slows down running & debugging.

Just cache.
Cache the file path of the module. E.g. ipykernel.__file__ along with the version.
If the file/directory last modified date , then version can be asumed to be the same.
Disc IO is much cheaper than spawning multiple processes. And optionally we can cache per lifetime of VS Code session as well, i.e. in same session don't check file either (just return from cache)
& if restart vs code, then check file.

**Comment by rchiodo** [comment]
Or we could just not ask on each run too. Need to see why we added the check in the first place.

**Comment by DonJayamanne** [comment]
Completed
