### ISSUE TITLE
Jupyter notebook cell not running

### ISSUE THREAD

**Issue by pedroangelini** [microsoft/vscode-jupyter#6695]
Issue Type: <b>Bug</b>

1. create a new pipenv environment in a folder
2. open the folder with  vscode, create an empty notebook by creating a new file, and calling it bug_test.ipynb
3. test file with a simple print("hi") cell --> ok
4. save file and exit vscode
5. pipenv install pandas
6. pipenv install matplotlib
7. re-open vscode. Try to run the first cell (print("hi")).
=> the cell status icon changes to the "executing" icon, and does not change. No other cell will run, and the only way to run anything on the notebook is to exit and open a different folder / different pipenv environment.

In my personal machine, these steps do not end in the frozen cell execution. It's only in my work machine.
I have uninstalled / re-installed python, cleared caches, uninstalled/re-installed vs code, ran it with minimum extenstions (Python + Jupyter only). Nothing seems to work. 
If I try to run the notebook after step 5, it still works. Matplotlib installation seems to be the trigger.
I have the Microsoft store version of Python (3.9) installed in this machine (as opposed to the website version in my personal machine).
I have uploaded the Jupyter terminal output, and screenshot of the locked cell.

VS Code version: Code - Insiders 1.59.0-insider (50b3811fdc5b5c80ca516a2edfffedcbd464b033, 2021-07-15T05:13:58.348Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (5.21GB free)|
|Process Argv|--crash-reporter-id 8a95f724-3ff1-46de-bfc4-eb59821704b0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.6.1
vscode-sql-beautify|cla|0.2.0
xml|Dot|2.5.1
json-tools|eri|1.0.2
file-icons|fil|1.0.29
gc-excelviewer|Gra|3.0.42
vscode-JS-CSS-HTML-formatter|lon|0.2.3
powerplatform-vscode|mic|0.2.10
fluent-icons|mig|0.0.12
prettify-json|moh|0.0.3
python|ms-|2021.7.1012204448-dev
vscode-pylance|ms-|2021.7.4-pre.1
jupyter|ms-|2021.8.1033311975
vscode-json-editor|nic|0.3.0
autodocstring|njp|0.5.4
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.8.0
vscode-powerquery|Pow|0.1.20
vscode-commons|red|0.0.6
ayu|tea|0.20.1
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.5.0
json|Zai|2.0.2

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwt:30312692
bridge0708:30335490

```

</details>

![Screenshot 2021-07-15 114006](https://user-images.githubusercontent.com/72536471/125827550-a8805e5f-ba6c-4d31-a0b9-a66b0440989c.png)
[Jupyter Output.log](https://github.com/microsoft/vscode/files/6824942/Jupyter.Output.log)

**Comment by DonJayamanne** [comment]
Thanks for filing this issue & I'm sorry ur running into a problem.
Looking at the logs, there doesn't seem to be any problems, however I can see that the logs don't spit anything out  once execution has commenced (i.e. nothing happens as you have indicated).
Please could you try running the exact same thing in Jupyter
* Install Jupyter into that same environment
* Run Jupyter `python -m jupyter notebook`, then run the cell.

**Comment by pedroangelini** [comment]
Hi! Thanks for the quick reply. Initially if I run the notebook directly on Jupyter, i get the following

Terminal

C:\Users\XXXXX>cd "C:\Users\xxxxxxxx\Notebooks\bug_test\"

C:\Users\XXXXXXXXXXXX\bug_test>pipenv shell
Launching subshell in virtual environment...
Microsoft Windows [Version 10.0.18363.1646]
(c) 2019 Microsoft Corporation. All rights reserved.

(bug_test-KBxYu-BE) C:\Users\XXXXXXXXXX\bug_test>python -m jupyter notebook bug_test.ipynb
[I 16:05:55.462 NotebookApp] Writing notebook server cookie secret to C:\Users\XXXXX\AppData\Roaming\jupyter\runtime\notebook_cookie_secret
[I 16:05:56.386 NotebookApp] Serving notebooks from local directory: C:\Users\XXxxxxx\Notebooks\bug_test
[I 16:05:56.386 NotebookApp] Jupyter Notebook 6.4.0 is running at:
[I 16:05:56.387 NotebookApp] http://localhost:8888/?token=f872ad02181edeab6eb852fa370098f1edbd795e9c3e0fb0
[I 16:05:56.387 NotebookApp]  or http://127.0.0.1:8888/?token=f872ad02181edeab6eb852fa370098f1edbd795e9c3e0fb0
[I 16:05:56.387 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:05:56.446 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/xxxxx/AppData/Roaming/jupyter/runtime/nbserver-18616-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=f872ad02181edeab6eb852fa370098f1edbd795e9c3e0fb0
     or http://127.0.0.1:8888/?token=f872ad02181edeab6eb852fa370098f1edbd795e9c3e0fb0
[I 16:06:02.136 NotebookApp] Writing notebook-signing key to C:\Users\xxxxx\AppData\Roaming\jupyter\notebook_secret
[W 16:06:02.138 NotebookApp] Notebook bug_test.ipynb is not trusted
[I 16:06:02.683 NotebookApp] Kernel started: fce6bb51-6855-40f5-ba02-c105fd805a31, name: python3
[W 16:06:02.763 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20210716160555 (::1) 76.790000ms referer=http://localhost:8888/notebooks/bug_test.ipynb
[IPKernelApp] WARNING | Eventloop or matplotlib integration failed. Is matplotlib installed?


The notebook is able to run the first cell, but as expected, if I try to run an import, it fails (since the notebook is not running with the pipenv kernel)
[cid:e25f1dc6-3327-4090-b7f3-0eb978493a12]


I have then installed the virtual environment Kernel in Jupyter, and tried to run the notebook using the command you mentioned, from the venv. I get a similar issue then with VS Code, so I'm guessing it's a Jupyter issue, not a VS Code issue.

(bug_test-KBxYu-BE) C:\Users\xxxxx\Notebooks\bug_test>python -m jupyter notebook bug_test.ipynb
[I 16:30:27.125 NotebookApp] Serving notebooks from local directory: C:\Users\xxxxx\Notebooks\bug_test
[I 16:30:27.125 NotebookApp] Jupyter Notebook 6.4.0 is running at:
[I 16:30:27.125 NotebookApp] http://localhost:8888/?token=3b50b748886894910ba15ee82bcf3a4d96fee8e94bbdb232
[I 16:30:27.125 NotebookApp]  or http://127.0.0.1:8888/?token=3b50b748886894910ba15ee82bcf3a4d96fee8e94bbdb232
[I 16:30:27.125 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:30:27.161 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/xxxxx/AppData/Roaming/jupyter/runtime/nbserver-1068-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=3b50b748886894910ba15ee82bcf3a4d96fee8e94bbdb232
     or http://127.0.0.1:8888/?token=3b50b748886894910ba15ee82bcf3a4d96fee8e94bbdb232
[I 16:30:32.165 NotebookApp] Kernel started: c390486c-2b36-457a-bf59-009b193f0208, name: bug_test-kbxyu-be
[W 16:30:38.024 NotebookApp] Nudge: attempt 10 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:30:43.059 NotebookApp] Nudge: attempt 20 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:30:48.089 NotebookApp] Nudge: attempt 30 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:30:53.117 NotebookApp] Nudge: attempt 40 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:30:58.143 NotebookApp] Nudge: attempt 50 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:31:03.147 NotebookApp] Nudge: attempt 60 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:31:08.156 NotebookApp] Nudge: attempt 70 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:31:13.186 NotebookApp] Nudge: attempt 80 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:31:18.214 NotebookApp] Nudge: attempt 90 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:31:23.242 NotebookApp] Nudge: attempt 100 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:31:28.277 NotebookApp] Nudge: attempt 110 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:31:33.292 NotebookApp] Nudge: attempt 120 on kernel c390486c-2b36-457a-bf59-009b193f0208
[E 16:31:33.499 NotebookApp] Uncaught exception GET /api/kernels/c390486c-2b36-457a-bf59-009b193f0208/channels?session_id=516745668e4741d1be1716d0a806e659 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/c390486c-2b36-457a-bf59-009b193f0208/channels?session_id=516745668e4741d1be1716d0a806e659', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "c:\users\xxxxx\.virtualenvs\bug_test-kbxyu-be\lib\site-packages\tornado\websocket.py", line 956, in _accept_connection
        await open_result
    tornado.util.TimeoutError: Timeout
[W 16:31:34.508 NotebookApp] Replacing stale connection: c390486c-2b36-457a-bf59-009b193f0208:516745668e4741d1be1716d0a806e659
[I 16:32:32.089 NotebookApp] Saving file at /bug_test.ipynb


The cell has the same issue of not being "idle", and from the output in the terminal I'm assuming there's some issue with the kernel not responding.

[cid:842fcff7-647c-4121-a7ef-d8e3ed8e316b]

I think that means we can close this issue, since it's not VS Code related?

**Comment by pedroangelini** [comment]
Hi! Thanks for the quick reply. Initially if I run the notebook directly on Jupyter, i get the following

Terminal

```C:\Users\XXXXX>cd "C:\Users\xxxxxxxx\Notebooks\bug_test\"

C:\Users\XXXXXXXXXXXX\bug_test>pipenv shell
Launching subshell in virtual environment...
Microsoft Windows [Version 10.0.18363.1646]
(c) 2019 Microsoft Corporation. All rights reserved.

(bug_test-KBxYu-BE) C:\Users\XXXXXXXXXX\bug_test>python -m jupyter notebook bug_test.ipynb
[I 16:05:55.462 NotebookApp] Writing notebook server cookie secret to C:\Users\XXXXX\AppData\Roaming\jupyter\runtime\notebook_cookie_secret
[I 16:05:56.386 NotebookApp] Serving notebooks from local directory: C:\Users\XXxxxxx\Notebooks\bug_test
[I 16:05:56.386 NotebookApp] Jupyter Notebook 6.4.0 is running at:
[I 16:05:56.387 NotebookApp] http://localhost:8888/?token=f872ad02181edeab6eb852fa370098f1edbd795e9c3e0fb0
[I 16:05:56.387 NotebookApp]  or http://127.0.0.1:8888/?token=f872ad02181edeab6eb852fa370098f1edbd795e9c3e0fb0
[I 16:05:56.387 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:05:56.446 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/xxxxx/AppData/Roaming/jupyter/runtime/nbserver-18616-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=f872ad02181edeab6eb852fa370098f1edbd795e9c3e0fb0
     or http://127.0.0.1:8888/?token=f872ad02181edeab6eb852fa370098f1edbd795e9c3e0fb0
[I 16:06:02.136 NotebookApp] Writing notebook-signing key to C:\Users\xxxxx\AppData\Roaming\jupyter\notebook_secret
[W 16:06:02.138 NotebookApp] Notebook bug_test.ipynb is not trusted
[I 16:06:02.683 NotebookApp] Kernel started: fce6bb51-6855-40f5-ba02-c105fd805a31, name: python3
[W 16:06:02.763 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20210716160555 (::1) 76.790000ms referer=http://localhost:8888/notebooks/bug_test.ipynb
[IPKernelApp] WARNING | Eventloop or matplotlib integration failed. Is matplotlib installed?
```

The notebook is able to run the first cell, but as expected, if I try to run an import, it fails (since the notebook is not running with the pipenv kernel)


![screenshot1](https://user-images.githubusercontent.com/72536471/126082982-3c2834ac-a162-4baf-9b59-3b606c7b93e0.png)



I have then installed the virtual environment Kernel in Jupyter, and tried to run the notebook using the command you mentioned, from the venv. I get a similar issue then with VS Code, so I'm guessing it's a Jupyter issue, not a VS Code issue.

Terminal:
```
(bug_test-KBxYu-BE) C:\Users\xxxxx\Notebooks\bug_test>python -m jupyter notebook bug_test.ipynb
[I 16:30:27.125 NotebookApp] Serving notebooks from local directory: C:\Users\xxxxx\Notebooks\bug_test
[I 16:30:27.125 NotebookApp] Jupyter Notebook 6.4.0 is running at:
[I 16:30:27.125 NotebookApp] http://localhost:8888/?token=3b50b748886894910ba15ee82bcf3a4d96fee8e94bbdb232
[I 16:30:27.125 NotebookApp]  or http://127.0.0.1:8888/?token=3b50b748886894910ba15ee82bcf3a4d96fee8e94bbdb232
[I 16:30:27.125 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:30:27.161 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/xxxxx/AppData/Roaming/jupyter/runtime/nbserver-1068-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=3b50b748886894910ba15ee82bcf3a4d96fee8e94bbdb232
     or http://127.0.0.1:8888/?token=3b50b748886894910ba15ee82bcf3a4d96fee8e94bbdb232
[I 16:30:32.165 NotebookApp] Kernel started: c390486c-2b36-457a-bf59-009b193f0208, name: bug_test-kbxyu-be
[W 16:30:38.024 NotebookApp] Nudge: attempt 10 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:30:43.059 NotebookApp] Nudge: attempt 20 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:30:48.089 NotebookApp] Nudge: attempt 30 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:30:53.117 NotebookApp] Nudge: attempt 40 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:30:58.143 NotebookApp] Nudge: attempt 50 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:31:03.147 NotebookApp] Nudge: attempt 60 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:31:08.156 NotebookApp] Nudge: attempt 70 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:31:13.186 NotebookApp] Nudge: attempt 80 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:31:18.214 NotebookApp] Nudge: attempt 90 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:31:23.242 NotebookApp] Nudge: attempt 100 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:31:28.277 NotebookApp] Nudge: attempt 110 on kernel c390486c-2b36-457a-bf59-009b193f0208
[W 16:31:33.292 NotebookApp] Nudge: attempt 120 on kernel c390486c-2b36-457a-bf59-009b193f0208
[E 16:31:33.499 NotebookApp] Uncaught exception GET /api/kernels/c390486c-2b36-457a-bf59-009b193f0208/channels?session_id=516745668e4741d1be1716d0a806e659 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/c390486c-2b36-457a-bf59-009b193f0208/channels?session_id=516745668e4741d1be1716d0a806e659', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "c:\users\xxxxx\.virtualenvs\bug_test-kbxyu-be\lib\site-packages\tornado\websocket.py", line 956, in _accept_connection
        await open_result
    tornado.util.TimeoutError: Timeout
[W 16:31:34.508 NotebookApp] Replacing stale connection: c390486c-2b36-457a-bf59-009b193f0208:516745668e4741d1be1716d0a806e659
[I 16:32:32.089 NotebookApp] Saving file at /bug_test.ipynb
```

The cell has the same issue of not being "idle", and from the output in the terminal I'm assuming there's some issue with the kernel not responding.

![screenshot2](https://user-images.githubusercontent.com/72536471/126082996-08360b9b-2764-469a-bf64-43c51c5fa1ff.png)


I think that means we can close this issue, since it's not VS Code related?

**Comment by DonJayamanne** [comment]
> I think that means we can close this issue, since it's not VS Code related?

Yes, agreed. Thanks for the confirmation.

Can you try this in a virtual environment, instead of pipenv. does that make a difference.
If that doesn't work, I'd probably file an issue on the matplot lib repo.

Once again, thanks for confirming the fact that this isn't an issue in VS Code.
