### ISSUE TITLE
Inconsistent mouse scroll speed in VSCode Jupyter

### ISSUE THREAD

**Issue by alceballosa** [microsoft/vscode-jupyter#6698]
Hi,

I've been using VSCode Insiders with Jupyter and my experience has been generally great but many times when scrolling through Markdown -text or images- the mouse scroll speed becomes inconsistent.

My mouse settings:

    "editor.mouseWheelScrollSensitivity": 1,
    "terminal.integrated.mouseWheelScrollSensitivity": 0.1,
    "editor.smoothScrolling": true,

## Environment data

-   VS Code version: 1.59 insiders
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1036914918
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows through WSL/Windows 10.
-   Python and/or Anaconda version: 3
-   Type of virtual environment used: conda
-   Jupyter server running: WSL/Windows.

## Expected behaviour

Scrolling speed for all kinds of content in a Jupyter notebook should be consistent, as in jupyter notebook and jupyter lab.

https://imgur.com/a/1C6OMmr

## Actual behaviour
When scrolling code, I scroll two lines at a time in a very smooth fashion. However, after clicking a markdown cell the scroll speed goes up and it gets "yanked", so even slightly moving my mouse wheel results in moving almost by a full screen.  This happens either on Windows or Windows+WSL.

Thanks in advance for your time!

**Comment by claudiaregio** [comment]
Hi @alceballosa, could you please provide a screenshot of your entire vs code window? The gif is a bit limited and we need to determine if you are using Native Notebooks or our old implementation first

**Comment by alceballosa** [comment]
Hi @claudiaregio , you're right, sorry! 

https://gifyu.com/image/BYpa

Here is a more detailed gif. In the first part of the video, I scroll through a code cell and the behavior is very consistent. As soon as I click (sometimes also when I hover) on a markdown cell the scrolling speed goes up dramatically and reading long markdown cells such as those in the displayed notebook becomes very difficult.

Let me know if you need me to provide any additional information.

Kindly,

Alberto

**Comment by claudiaregio** [comment]
Thanks for providing the rest of the view :) I'm actually going to close this since we are actually tracking the scrolling issue here: https://github.com/microsoft/vscode/issues/126880 

There are a few instructions on that issue to follow to see if it improves the scrolling. Let us know if it works for you!
