### ISSUE TITLE
Run Selected Text Code under a Cell in a Notebook (`ctrl+enter` execute highlighted/selected code like RStudio's notebooks)

### ISSUE THREAD

**Issue by rleyvasal** [microsoft/vscode-jupyter#6704]
It would be great to be able to run selected code under a cell. 

For example, selecting `mtcars` and pressing `ctrl+enter`  could run the code under the cell without having to copy `mtcars` to another cell to run it.  That functionality is currently available in RStudio notebooks. 

<img width="805" alt="run_selected_code" src="https://user-images.githubusercontent.com/61335136/126021197-4430a9bb-d174-4469-8706-8bb08cb98f9b.PNG">

**Comment by DavidKutu** [comment]
Thank you for the request! I'll bring it up in an upcoming meeting.

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time.
