### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Naimuddinsiddiqui** [microsoft/vscode-jupyter#6706]
- Issue Type: `Performance`
- Extension Name: `jupyter`
- Extension Version: `2021.8.1013163132`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.58.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\hp\AppData\Local\Temp\ms-toolsai.jupyter-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by claudiaregio** [comment]
HI @Naimuddinsiddiqui, could you attach the file mentioned above for us to help troubleshoot?

**Comment by Naimuddinsiddiqui** [comment]
I am very thankful for your immediate response. But as of now I am not
getting that error. In future if any error occur then I will share
screenshot.
