### ISSUE TITLE
Vscode  sometimes cursor flickers and freezes in jupyter 

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/vscode-jupyter#6708]
## Environment data

version: 1.58.2 (user setup)
comit: c3f126316369cd610563c75b1b1725e0679adfb3
date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.18363

## Expected behaviour
The mouse does not freeze
## Actual behaviour
Vscode  sometimes cursor flickers and freezes in jupyter 
Exactly the same problem https://github.com/microsoft/vscode/issues/128658
                                         https://github.com/microsoft/vscode/issues/128895

**Comment by claudiaregio** [comment]
If it's the same problem as https://github.com/microsoft/vscode/issues/128658, let's close in favor of that as to not fork the discussions
