### ISSUE TITLE
Wrong kernel when running a Jupyter Notebook!

### ISSUE THREAD

**Issue by sadjadanzabizadeh** [microsoft/vscode-jupyter#6709]
Issue Type: <b>Bug</b>

I have a virtual environment, and my workspace (containing multiple folders) is set to run in that environment (first image).
However, when I open a Jupyter notebook, although it shows that kernel initially (second image), when I run a cell, it switches to another kernel and demands installing `ipykernel` (third image). If I attempt to change the kernel, my intended kernel is not in the list (last image)! Sometimes, opening a new notebook and running something in it fixes the issue with this specific file, sometimes not.

![image](https://user-images.githubusercontent.com/32469424/126038526-37fcf83a-c9f5-4b32-ac00-9a1aca86c0c8.png)
![image](https://user-images.githubusercontent.com/32469424/126038537-187f0432-1528-45bb-a8e1-72ffb2ac5671.png)
![image](https://user-images.githubusercontent.com/32469424/126038542-e79c6e05-6f38-4fd5-996d-cc630c36aeed.png)
![image](https://user-images.githubusercontent.com/32469424/126038548-e185665f-64bb-498b-ac64-75c2554a3e0c.png)

Extension version: 2021.8.1013163132
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by sadjadanzabizadeh** [comment]
This is the output for `Jupyter` when I open the file:

Info 2021-07-17 08:42:40: Loading web panel for file:///c%3A/Users/user/codebase/W-D/read_results.ipynb
Info 2021-07-17 08:42:40: Loading webview. View is notset
Info 2021-07-17 08:42:40: Attempting to start a server because of preload conditions ...
Info 2021-07-17 08:42:40: Loading web view...
Info 2021-07-17 08:42:40: Webview panel created.
Info 2021-07-17 08:42:40: initialize CommonMessageCoordinator
Info 2021-07-17 08:42:40: IPyWidgetMessageDispatcher.initialize
Info 2021-07-17 08:42:40: Created and initailized CommonMessageCoordinator
Info 2021-07-17 08:42:40: Creating raw notebook for file:///c%3A/Users/user/codebase/W-D/read_results.ipynb
Info 2021-07-17 08:42:40: Getting preferred kernel for file:///c%3A/Users/user/codebase/W-D/read_results.ipynb
Info 2021-07-17 08:42:40: Find preferred kernel for file:///c%3A/Users/user/codebase/W-D/read_results.ipynb with metadata {"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.10"},"orig_nbformat":2,"kernelspec":{"name":"python3","display_name":"Python 3.8.10 64-bit ('.reil38': venv)"},"metadata":{"interpreter":{"hash":"e04279c8b8433d6bb4ad601b2105c69be664ea37f15dda9270e309e901031365"}},"interpreter":{"hash":"c3416ed0848a595f05e9086dffe759fd59e2a6671fda1539db684c903a99c9d9"}} & preferred interpreter {"sysPrefix":"c:\\Users\\user\\.reil38","envType":"Venv","envName":".reil38","envPath":"c:\\Users\\user\\.reil38","path":"c:\\Users\\user\\.reil38\\Scripts\\python.exe","architecture":3,"sysVersion":"3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]","version":{"raw":"3.8.10","major":3,"minor":8,"patch":10,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.8.10 64-bit ('.reil38': venv)"}
Info 2021-07-17 08:42:40: findPreferredKernel score for Python3, Python 3.8.10 64-bit (windows store) is 4
Info 2021-07-17 08:42:40: findPreferredKernel score for Python 3.8.10 64-bit (windows store) is 4
Info 2021-07-17 08:42:40: findKernel found Python 3.8.10 64-bit (windows store)
Info 2021-07-17 08:42:40: Find kernel spec, Class name = w, completed in 3ms, has a truthy return value, Arg 1: <Uri:c:\Users\user\codebase\W-D\read_results.ipynb>, Arg 2: {"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.10"},"orig_nbformat":2,"kernelspec":{"name":"python3","display_name":"Python 3.8.10 64-bit ('.reil38': venv)"},"metadata":{"interpreter":{"hash":"e04279c8b8433d6bb4ad601b2105c69be664ea37f15dda9270e309e901031365"}},"interpreter":{"hash":"c3416ed0848a595f05e9086dffe759fd59e2a6671fda1539db684c903a99c9d9"}}, Arg 3: undefined, Return Value: {"kind":"startUsingPythonInterpreter","kernelSpec":{"specFile":"C:\\Users\\user\\AppData\\Roaming\\jupyter\\kernels\\python3810jvsc74a57bd0c781b2277432b50a1e8eec5cb3e0f73bf5c2f898200d2c4b939b2a58c155c1ef\\kernel.json","interpreterPath":"C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\python3.8.exe","name":"python3810jvsc74a57bd0c781b2277432b50a1e8eec5cb3e0f73bf5c2f898200d2c4b939b2a58c155c1ef","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"python","display_name":"Python 3.8.10 64-bit (windows store)","metadata":{"interpreter":{"sysPrefix":"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0","envType":"WindowsStore","envName":"","envPath":"","path":"C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\python3.8.exe","architecture":3,"sysVersion":"3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]","version":{"raw":"3.8.10","major":3,"minor":8,"patch":10,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Microsoft","displayName":"Python 3.8.10 64-bit (windows store)"}},"env":{}},"interpreter":{"sysPrefix":"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0","envType":"WindowsStore","envName":"","envPath":"","path":"C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\python3.8.exe","architecture":3,"sysVersion":"3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]","version":{"raw":"3.8.10","major":3,"minor":8,"patch":10,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Microsoft","displayName":"Python 3.8.10 64-bit (windows store)"},"id":".jvsc74a57bd0c781b2277432b50a1e8eec5cb3e0f73bf5c2f898200d2c4b939b2a58c155c1ef.C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\python3.8.exe.C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\python3.8.exe"}
Info 2021-07-17 08:42:40: Computing working directory file:///c%3A/Users/user/codebase/W-D/read_results.ipynb
Info 2021-07-17 08:42:40: Connecting to raw session for file:///c%3A/Users/user/codebase/W-D/read_results.ipynb with connection {"kind":"startUsingPythonInterpreter","kernelSpec":{"specFile":"C:\\Users\\user\\AppData\\Roaming\\jupyter\\kernels\\python3810jvsc74a57bd0c781b2277432b50a1e8eec5cb3e0f73bf5c2f898200d2c4b939b2a58c155c1ef\\kernel.json","interpreterPath":"C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\python3.8.exe","name":"python3810jvsc74a57bd0c781b2277432b50a1e8eec5cb3e0f73bf5c2f898200d2c4b939b2a58c155c1ef","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"python","display_name":"Python 3.8.10 64-bit (windows store)","metadata":{"interpreter":{"sysPrefix":"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0","envType":"WindowsStore","envName":"","envPath":"","path":"C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\python3.8.exe","architecture":3,"sysVersion":"3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]","version":{"raw":"3.8.10","major":3,"minor":8,"patch":10,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Microsoft","displayName":"Python 3.8.10 64-bit (windows store)"}},"env":{}},"interpreter":{"sysPrefix":"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0","envType":"WindowsStore","envName":"","envPath":"","path":"C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\python3.8.exe","architecture":3,"sysVersion":"3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]","version":{"raw":"3.8.10","major":3,"minor":8,"patch":10,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Microsoft","displayName":"Python 3.8.10 64-bit (windows store)"},"id":".jvsc74a57bd0c781b2277432b50a1e8eec5cb3e0f73bf5c2f898200d2c4b939b2a58c155c1ef.C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\python3.8.exe.C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\python3.8.exe"}
Info 2021-07-17 08:42:40: Starting raw kernel Python 3.8.10 64-bit (windows store)
Info 2021-07-17 08:42:40: installMissingDependencies C:\Users\user\AppData\Local\Microsoft\WindowsApps\python3.8.exe
Info 2021-07-17 08:42:40: Cached data exists getEnvironmentVariables, <No Resource>
Info 2021-07-17 08:42:40: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.8.exe -c "import ipykernel"
> ~\AppData\Local\Microsoft\WindowsApps\python3.8.exe -c "import ipykernel"
Info 2021-07-17 08:42:40: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.8.exe -c "import ipykernel"
> ~\AppData\Local\Microsoft\WindowsApps\python3.8.exe -c "import ipykernel"
Error 2021-07-17 08:42:40: Install Missing Dependencies, Class name = w, completed in 428ms, has a falsy return value, Return Value: undefined [a [Error]: IPyKernel not installed into interpreter Python 3.8.10 64-bit (windows store):C:\Users\user\AppData\Local\Microsoft\WindowsApps\python3.8.exe
	at w.handleKernelDependencyResponse (c:\Users\user\.vscode\extensions\ms-toolsai.jupyter-2021.8.1013163132\out\client\extension.js:90:246461)
	at w.installMissingDependencies (c:\Users\user\.vscode\extensions\ms-toolsai.jupyter-2021.8.1013163132\out\client\extension.js:90:245644)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 1
}
Error 2021-07-17 08:42:40: Raw session failed to start because dependencies not installed
Info 2021-07-17 08:42:40: Shutdown session -- complete
Error 2021-07-17 08:42:40: Failed to determine if a notebook is active for the current editor [a [Error]: IPyKernel not installed into interpreter Python 3.8.10 64-bit (windows store):C:\Users\user\AppData\Local\Microsoft\WindowsApps\python3.8.exe
	at w.handleKernelDependencyResponse (c:\Users\user\.vscode\extensions\ms-toolsai.jupyter-2021.8.1013163132\out\client\extension.js:90:246461)
	at w.installMissingDependencies (c:\Users\user\.vscode\extensions\ms-toolsai.jupyter-2021.8.1013163132\out\client\extension.js:90:245644)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 1
}
Info 2021-07-17 08:42:41: Web view react rendered
Info 2021-07-17 08:42:41: Request for onigasm file at c:\Users\user\.vscode\extensions\ms-toolsai.jupyter-2021.8.1013163132\out\client\node_modules\onigasm\lib\onigasm.wasm
Info 2021-07-17 08:42:41: Request for tmlanguage file.
Info 2021-07-17 08:42:41: Searching for token colors ...
Info 2021-07-17 08:42:41: Attempting search for colors ...
Info 2021-07-17 08:42:41: Searching for token colors ...
Info 2021-07-17 08:42:41: Attempting search for colors ...
Info 2021-07-17 08:42:41: Loading colors from c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-07-17 08:42:41: Loading colors from c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-07-17 08:42:41: IPyWidgetMessageDispatcher.initialize
Info 2021-07-17 08:42:41: Searching for token colors ...
Info 2021-07-17 08:42:41: Attempting search for colors ...
Info 2021-07-17 08:42:41: Searching for token colors ...
Info 2021-07-17 08:42:41: Attempting search for colors ...
Info 2021-07-17 08:42:41: Searching for token colors ...
Info 2021-07-17 08:42:41: Attempting search for colors ...
Info 2021-07-17 08:42:41: Searching for token colors ...
Info 2021-07-17 08:42:41: Attempting search for colors ...
Info 2021-07-17 08:42:41: Loading colors from c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-07-17 08:42:41: Searching for token colors ...
Info 2021-07-17 08:42:41: Attempting search for colors ...
Info 2021-07-17 08:42:41: Loading colors from c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-07-17 08:42:41: Searching for token colors ...
Info 2021-07-17 08:42:41: Attempting search for colors ...
Info 2021-07-17 08:42:41: Loading colors from c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-07-17 08:42:41: Loading colors from c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-07-17 08:42:41: Loading colors from c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-07-17 08:42:41: Loading colors from c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-07-17 08:42:41: Attempting search for colors ...
Info 2021-07-17 08:42:41: Attempting search for colors ...
Info 2021-07-17 08:42:41: Loading base colors from c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-07-17 08:42:41: Loading base colors from c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-07-17 08:42:41: Attempting search for colors ...
Info 2021-07-17 08:42:41: Attempting search for colors ...
Info 2021-07-17 08:42:41: Attempting search for colors ...
Info 2021-07-17 08:42:41: Attempting search for colors ...
Info 2021-07-17 08:42:41: Attempting search for colors ...
Info 2021-07-17 08:42:41: Attempting search for colors ...
Info 2021-07-17 08:42:41: Loading base colors from c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-07-17 08:42:41: Loading base colors from c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-07-17 08:42:41: Loading base colors from c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-07-17 08:42:41: Loading base colors from c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-07-17 08:42:41: Loading base colors from c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-07-17 08:42:41: Loading base colors from c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-07-17 08:42:41: Using colors to generate CSS ...
Info 2021-07-17 08:42:41: Using colors to generate CSS ...
Info 2021-07-17 08:42:41: Using colors to generate CSS ...
Info 2021-07-17 08:42:41: Using colors to generate CSS ...
Info 2021-07-17 08:42:41: Using colors to generate CSS ...
Info 2021-07-17 08:42:41: Using colors to generate CSS ...
Info 2021-07-17 08:42:41: Using colors to generate CSS ...
Info 2021-07-17 08:42:41: Using colors to generate CSS ...

**Comment by sadjadanzabizadeh** [comment]
I compared Jupyter's log when it opens a blank notebook and my own notebook, and removed all metadata that were different. Still, `findPreferredKernel` for blank notebook can find my environment's `Python`, and it cannot find it for the saved notebook.

**Log for the saved file:**

Info 2021-07-17 09:22:17: Find preferred kernel for file:///c%3A/Users/user/codebase/W-D/read_results_2%20-%20Copy.ipynb with metadata {"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":3},"orig_nbformat":4} & preferred interpreter {"sysPrefix":"c:\\Users\\user\\.reil38","envType":"Venv","envName":".reil38","envPath":"c:\\Users\\user\\.reil38","path":"c:\\Users\\user\\.reil38\\Scripts\\python.exe","architecture":3,"sysVersion":"3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]","version":{"raw":"3.8.10","major":3,"minor":8,"patch":10,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.8.10 64-bit ('.reil38': venv)"}
Info 2021-07-17 09:22:17: findPreferredKernel score for Python3, Python 3.8.10 64-bit (windows store) is 4
Info 2021-07-17 09:22:17: findPreferredKernel score for Python 3.8.10 64-bit (windows store) is 4
Info 2021-07-17 09:22:17: findKernel found Python 3.8.10 64-bit (windows store)

**Log for the blank notebook:**

Info 2021-07-17 09:22:24: Find preferred kernel for untitled:/c%3A/Users/user/codebase/Untitled-7.ipynb with metadata {"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":3},"orig_nbformat":4} & preferred interpreter {"sysPrefix":"c:\\Users\\user\\.reil38","envType":"Venv","envName":".reil38","envPath":"c:\\Users\\user\\.reil38","path":"c:\\Users\\user\\.reil38\\Scripts\\python.exe","architecture":3,"sysVersion":"3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]","version":{"raw":"3.8.10","major":3,"minor":8,"patch":10,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.8.10 64-bit ('.reil38': venv)"}
Info 2021-07-17 09:22:24: findPreferredKernel score for Python3, Python 3.8.10 64-bit ('.reil38': venv) is 14
Info 2021-07-17 09:22:24: findPreferredKernel score for Python 3.8.10 64-bit ('.reil38': venv) is 24 
Info 2021-07-17 09:22:24: findPreferredKernel score for Python3, Python 3.8.10 64-bit (windows store) is 4
Info 2021-07-17 09:22:24: findPreferredKernel score for Python 3.8.10 64-bit (windows store) is 4
Info 2021-07-17 09:22:24: findKernel found Python 3.8.10 64-bit ('.reil38': venv)

**Comment by DonJayamanne** [comment]
Thanks for filling this issue. I believe it may be fixed in the insiders version. Please could you install vscode insiders, and let us know if it fixes your issue.

**Comment by sadjadanzabizadeh** [comment]
I reinstalled `Jupyter` extension and it fixed the issue. I can no longer replicate the conditions of the issue to check the insider version.
