### ISSUE TITLE
Output from Kqlmagic to launch token page doesn't work

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#6710]
Use kql magic, when we get the output to launch the token auth, nothing happened

**Comment by mbnshtck** [comment]
Kqlmagic detection that it runs within vscode is not perfect, it uses heuristic logic. If it fails, the workaround is to set the environmental variable KQLMAGIC_NOTEBOOK_APP=VisualStudioCode. If this does not solve the problem. please report the issue in Kqlmagic Github.
