### ISSUE TITLE
Add Find and Replace to Jupyter Notebooks 

### ISSUE THREAD

**Issue by rleyvasal** [microsoft/vscode-jupyter#6711]
Currently the option to Find and Replace is available for Python scripts after pressing `CTRL+F`   and clicking the right arrow in the Find dialog window.; however when working with Jupyter notebooks the right arrow on the Find dialog is not there and Find and Replace is not available. 

It would be great to have the option to Find and Replace text code in Jupyter notebooks they same way that it works for Python scripts - this functionality is currently available in Jupyter Lab.

<img width="777" alt="vscode_find" src="https://user-images.githubusercontent.com/61335136/126045720-b487a856-bfa2-4abb-a6cf-942f191e36fc.PNG">

<img width="914" alt="jupyterlab_find_replace" src="https://user-images.githubusercontent.com/61335136/126045781-28d50955-f2c2-4ff2-b27b-f8f656abd0c6.PNG">

**Comment by claudiaregio** [comment]
Hi @rleyvasal, this functionality is available today with our new notebooks implementation. To try it out follow the instructions located here: https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code
