### ISSUE TITLE
Cannot Delete Default Key Bindings

### ISSUE THREAD

**Issue by namespace-Pt** [microsoft/vscode-jupyter#6715]
## Environment data

-   VS Code version: 1.58.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1013163132
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.19043
-   Python and/or Anaconda version: conda 4.10.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

I want to delete the default key binding ( _ctrl+alt+enter_ ) for **execute cell** command

## Actual behaviour

I cannot delete this key binding. I tried to delete several other default key bindings (created by Jupyter Extension), none of them worked. 

## Steps to reproduce:

1. ctrl+shift+p, open keyboard shotcut
2. search for _ctrl+alt+enter_
3. find the **execute cell** command which is labeled **default** at the end of the line
4. right click and delete

## Logs

no logs recorded in any window.

**Comment by claudiaregio** [comment]
Hi @namespace-Pt, could you help me understand why you'd like to delete the default keyboard shortcut?

**Comment by namespace-Pt** [comment]
Because it contradicts with my own setting, I set _ctrl+alt+enter_ to **start a new line** in the cell, however now it is rendered as **execute cell**.

**Comment by claudiaregio** [comment]
@namespace-Pt Got it, user settings should override any that are set by default or extensions. It sounds like potentially the custom setting you have for that keyboard shortcut might be missing a clause that makes sure this occurs in a notebook file as well...

Could you paste the when condition for your custom shortcut? We can have someone take a look

**Comment by namespace-Pt** [comment]
@claudiaregio  Okay this is my when clause set for the command **insertLineAfter**: `editorTextFocus && !editorReadonly`;

By the way, I always don't know how to properly configure all those when clauses, is there any documentation?

**Comment by claudiaregio** [comment]
Here is a link that may help provide some getting started info: https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by namespace-Pt** [comment]
Thank you @claudiaregio

**Comment by greazer** [comment]
@namespace-Pt, I'm guessing that you may have been unblocked here? If not, please reopen.
