### ISSUE TITLE
jupyter notebook often frozen and consume much memory

### ISSUE THREAD

**Issue by GHpku** [microsoft/vscode-jupyter#6717]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

Things after startup are fine. This often happens after executing cells a few times. It seems to become worse and worse with more runs.

Extension version: 2021.8.1036914918
VS Code version: Code - Insiders 1.59.0-insider (599f5d2c67571f84a045a59eb3423bc254ee87d9, 2021-07-16T09:56:48.454Z)
OS version: Linux x64 5.8.0-59-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 4150)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 0|
|Memory (System)|15.35GB (1.91GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id ad4bf5a4-f6f2-4fa7-b8bc-a6aaa3b2b1b4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   141	180693	code-insiders main
    0	     0	180695	   zygote
    0	   157	180732	     gpu-process
    0	     0	180696	   zygote
    0	   959	185559	     window (undefined)
    0	    63	189968	     window (undefined)
    0	    79	239379	     window (Issue Reporter)
    0	    16	180741	   utility
    0	    79	181187	   shared-process
    0	    31	181208	     ptyHost
    0	     0	239400	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	239401	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   503	185519	   window (scarlet.ipynb - Visual Studio Code - Insiders)
    0	  1242	185545	     extensionHost
    0	   487	185634	       electron_node bundle.js 
    0	    31	189777	       /home/hua/anaconda3/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
    0	    31	189779	       /home/hua/anaconda3/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
    0	   110	189781	       /home/hua/anaconda3/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
    0	    31	189799	         electron_node c.js 
    0	  2861	189817	         /home/hua/anaconda3/bin/python -m ipykernel_launcher -f /home/hua/.local/share/jupyter/runtime/kernel-fb951a08-c178-4f1b-af48-9a893b212526.json
    0	    31	189834	         electron_node a.js 
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythonvspyt639:30291487
pythontb:30258533
vsc_aacf:30263846
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
3f5j7703:30294757
vscod805cf:30301675
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwtct:30312693
bridge0708:30335490

```

</details>

**Comment by DavidKutu** [comment]
Thanks for the issue @GHpku. Please upload your `cpuprofile.txt` file, follow these steps to obtain it:
https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by GHpku** [comment]
> Thanks for the issue @GHpku. Please upload your `cpuprofile.txt` file, follow these steps to obtain it:
> https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

Please find the attached file. Thanks!
[CPU-20210719T222553.119Z.cpuprofile.txt](https://github.com/microsoft/vscode-jupyter/files/6844222/CPU-20210719T222553.119Z.cpuprofile.txt)

**Comment by CatNofishing** [comment]
@DavidKutu  @GHpku  Similiar peoblem， it annoys me，Please refer to the following information，I am sure this is a bug after the update, not just caused by cpu usage, although I don’t know the specific reason.
https://github.com/microsoft/vscode/issues/128658
https://github.com/microsoft/vscode/issues/128895
https://github.com/microsoft/vscode-jupyter/issues/6708

This problem will appear suddenly, and the frequency is very high, your mouse will suddenly be unable to edit jupyter,Multiple cursors flash together at the same time.
![动画](https://user-images.githubusercontent.com/33288114/126093255-0a0db709-d78b-4798-8b8c-9a2c6ee7ff77.gif)

**Comment by claudiaregio** [comment]
Hi @CatNofishing, we are rolling out a new native notebooks experience. Are you able to follow the instructions here (https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code) to opt-in and see if you experience the same issue? We will eventually be retiring the old notebook experience so if you could help us obtain another cpuprofile.txt file to work off of that would be great

**Comment by DavidKutu** [comment]
@GHpku sorry for the late response!

I can't open your .cpuprofile on my browser :/
This is what happens:
![image](https://user-images.githubusercontent.com/20347396/127579142-5cf72a8e-54dc-4c87-ad4a-e9f978442cb2.png)
(This usually shows a bunch of functions and how long they take)

Could you please generate a new one?
Or, could you check if the info is displayed when you open the one you already shared?

**Comment by greazer** [comment]
@GHpku, please reopen if VS Code v1.59 doesn't address the problem.
