### ISSUE TITLE
Displaying a high number of widgets causes significant performance impact

### ISSUE THREAD

**Issue by sbland** [microsoft/vscode-jupyter#6718]
Using a high number of Ipywidgets (300+) causes long cell load times and lag when using button widgets. This is not the case for the same notebook when ran from the terminal and viewed in a web browser.

## Environment data

-   VS Code version: 1.58.0
-   Jupyter Extension version (available under the Extensions sidebar): 2021.8.1013163132
-   Python Extension version (available under the Extensions sidebar): 2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version:  Windows_NT x64 10.0.18363 WSL2 Ubuntu 20
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

Should be able to display many widgets (300+) without significant performance issues(as in web view)

## Actual behaviour

Slow load times for widgets

## Steps to reproduce:

``` python
w = widgets.Box([widgets.Text() for _ in range(600)])
display(w)
```

**Comment by DavidKutu** [comment]
Thanks for the issue @sbland. Please upload your cpuprofile.txt file, follow these steps to obtain it:
https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

That'll help us try to get it to perform better.

**Comment by claudiaregio** [comment]
@DavidKutu I tried reproducing, let me know if this file has the correct info

[CPU-20210724T225856.zip](https://github.com/microsoft/vscode-jupyter/files/6873449/CPU-20210724T225856.zip)

**Comment by DavidKutu** [comment]
That helps!

**Comment by DonJayamanne** [comment]
@sbland 
I've tested this out and seems to work well without any perf degradations.
@DavidKutu Not sure if you found any issues from the CPU logs or not.
I'm closing this a I cannot repro any issues (new release with a lot of perf improvements will be avaialbel today)
