### ISSUE TITLE
Bug in markdown render with single quotation marks 

### ISSUE THREAD

**Issue by lyc0930** [microsoft/vscode-jupyter#6719]
## Environment data

-   VS Code version: 1.58.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1013163132
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows21H1
-   Python and/or Anaconda version: 3.9.2
-   Type of virtual environment used : N/A
-   Jupyter server running: Local

## Expected behaviour

when there are code like these in a cell:
```md
<a href="https://github.com/">github</a>
<p> Don't work fine </p>
```
expected result in display:
```
[github](https://github.com/)

Don't work fine
```

## Actual behaviour

when there are code like these in a cell:
```md
<a href="https://github.com/">github</a>
<p> Don't work fine </p>
```
actual result in display:
```
github(github

Don)

Don')

Don't work fine
```
where both *github*  in line 1 are hyperlinked

However, after remove the single quotation marks in *Don't*, it works just fine:
```md
<a href="https://github.com/">github</a>
<p> Dont work fine </p>
```
actual result in display:
```
[github](https://github.com/)

Dont work fine
```
## Steps to reproduce:

1. open a new jupyter notebook
2. create a new cell and click the button "Change to markdown"
3. write down these code
```md
<a href="https://github.com/">github</a>
<p> Don't work fine </p>
```
4. Shift + Enter

**Comment by DavidKutu** [comment]
Thanks for the issue @lyc0930. That issue will be solved with native notebooks.
You can try it now by following these steps:
https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code

**Comment by lyc0930** [comment]
> Thanks for the issue @lyc0930. That issue will be solved with native notebooks.
> You can try it now by following these steps:
> https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code

**Comment by lyc0930** [comment]
Thanks, It seems to work just fine. It's great to see a brand new notebook in VSCode.
