### ISSUE TITLE
Interactive window toolbar scales in a not-user friendly way

### ISSUE THREAD

**Issue by jobevers** [microsoft/vscode-jupyter#6720]
## Environment data

-   VS Code version: 1.58.2
-   Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS and version: OSX 11.4
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pipenv
-   Value of the `python.languageServer` setting: Pylance language server 2021.7.4 (pyright 209f9621)

## Expected behavior

Be able to resize the interactive terminal and not have the top toolbar scale funny

## Actual behavior

Start like this:
![image](https://user-images.githubusercontent.com/2380127/125998302-32832de6-f942-4c06-9338-548038934b2b.png)

and resizing the interactive window does this:
![image](https://user-images.githubusercontent.com/2380127/125998451-ece5ea30-7e6d-40f8-9770-b0fae78ef08c.png)
(Its not obvious from the screenshots: I reduced the width of the window and the icons started running into the "Jupyter Server" label. The icons then stack vertically)

This leaves me with some tiny amount of actual screen real estate to interact with

## Steps to reproduce:

Start interactive window, resize.

**Comment by DavidKutu** [comment]
Thanks for the issue @jobevers. That issue will be solved with native notebooks and native interactive window.
You can try it by following these steps:
https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code

And after that, to use the new native interactive window, set this setting:
`"jupyter.enableNativeInteractiveWindow": true`

**Comment by jobevers** [comment]
Before:
![image](https://user-images.githubusercontent.com/2380127/126231271-0e1cb1d8-c1d5-41a5-912d-7ced8766114a.png)

After
![image](https://user-images.githubusercontent.com/2380127/126231447-3684ba4e-70db-46bb-9748-b33712e242a4.png)

Much improved!  Thanks.

Is it possible to get rid of the text associated with the buttons and just have the icons?

For anybody else reading this, I had the add the line `"jupyter.enableNativeInteractiveWindow": true` to `~/.vscode-server/data/Machine/settings.json` on the remote machine that I develop on (using the ssh remote extension)

**Comment by DavidKutu** [comment]
Glad it works!

Not right now, but please file an issue [here](https://github.com/microsoft/vscode) so we can make it happen.

**Comment by joyceerhl** [comment]
FWIW, I think the toolbar ask is tracked by https://github.com/microsoft/vscode/issues/125551 Please feel free to upvote that issue :)
