### ISSUE TITLE
Indent guidelines not available.

### ISSUE THREAD

**Issue by ItsJnz** [microsoft/vscode-jupyter#6721]
![image](https://user-images.githubusercontent.com/65062727/126113440-a2351fdc-3ea1-4bca-b89e-c01c774c0429.png)
there is no indent guidelines for python code on jupyter extension.

**Comment by claudiaregio** [comment]
Hi @ItsJnz, indent guidelines are available in native notebooks! 
To try it out, follow the instructions located here: https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code

![image](https://user-images.githubusercontent.com/19276747/126193280-2620b583-aa52-482f-9d46-fd7026ac0daf.png)

**Comment by ItsJnz** [comment]
Hey, thanks man, it was very annoying then. I got it all set now. 🙌
