### ISSUE TITLE
Cannot create New Blank Notebook

### ISSUE THREAD

**Issue by zxc40402** [microsoft/vscode-jupyter#6728]
## Environment data

-   VS Code version: 1.58.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1046824664
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: MacOS M1 11.0.1 (20B29)
-   Python and/or Anaconda version: conda 4.10.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

I want to create New Blank Notebook

## Actual behaviour

Error
`Command 'Jupyter: Create New Blank Notebook' resulted in an error (Running the contributed command: 'jupyter.createnewnotebook' failed.)`

## Steps to reproduce:

1. command + shift + P
2. click Jupyter: Create New Blank Notebook

## Logs
there is a problem
`settings.json - End of file expected`

Here is my settings.json
```
{
    "python.defaultInterpreterPath": "/Users/allen/miniforge3/envs/tf24/bin/python"
}nb": "jupyter.notebook.ipynb"
    },
    "workbench.startupEditor": "newUntitledFile",
    "python.pythonPath": "/Users/allen/miniforge3/envs/tf24/bin/python",
    "python.formatting.provider": "none",
    "terminal.integrated.inheritEnv": false,
    "jupyter.jupyterServerType": "local",
    "python.defaultInterpreterPath": "/Users/allen/miniforge3/envs/tf24/bin/python"
}

```

**Comment by claudiaregio** [comment]
Hi @zxc40402, I am not able to reproduce this issue however I am working with MacOS 11.2.3 . Does updating to that fix your issue?

**Comment by joyceerhl** [comment]
@zxc40402 This happens when your settings.json file contains invalid JSON. If you open your settings.json, there should be a squiggle flagging the part of the file that contains invalid data. Please remove the invalid lines, reload VS Code, and let us know if that fixes the problem.

**Comment by zxc40402** [comment]
@joyceerhl It's working. Thank you. I appreciate it
