### ISSUE TITLE
Feedback about data science survey

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#6730]
Tracking feedback from this morning's notebook sync:

- No action / clicking 'x' to dismiss a prompt should be equivalent to clicking on the 'No' button in terms of delay applied
- Opening native interactive window should not put up the survey
- Ensure no survey displayed in Codespaces (follow up with Kai)

**Comment by claudiaregio** [comment]
We can also revert back to the conditions we used for the webview feedback since we are rolling out

**Comment by TylerLeonhardt** [comment]
What would be the best way to verify this?

**Comment by joyceerhl** [comment]
1. Delete the extension global storage on your machine (or start Insiders with a random extensions dir) 
2. Install the Jupyter extension 
3. Open an interactive window using the `Create Interactive Window` command palette command. You should not see a popup in the bottom right
4. Open a native notebook
5. You should see a popup in the bottom right
6. Click on the X
7. Reload VS Code
8. The popup shouldn't appear anymore (previously it would appear)

**Comment by rzhao271** [comment]
I don't see the popup for step 5. For step 1, I used a random extensions dir.
I'm wondering where the extension global storage is, in case I need to delete that?

**Comment by joyceerhl** [comment]
@rzhao271 on Windows it's C:\Users\<your username>\AppData\Roaming\Code - Insiders\User\globalStorage

**Comment by rzhao271** [comment]
I've tried that and I've also tried using a fresh user data dir. I'm still not seeing the popup.
Jupyter extension `v2021.8.1081660962`

**Comment by joyceerhl** [comment]
🤦‍♀️ sorry, the trigger to show the survey is opening 6 notebooks (you can close and reopen the same one). Really sorry, totally forgot about that in the verification steps.
