### ISSUE TITLE
Ctrl+P fails to load Jupyter Notebook (ipynb) files

### ISSUE THREAD

**Issue by Astlaan** [microsoft/vscode-jupyter#6735]
Issue Type: <b>Bug</b>

After the latest Jupyter update (which included the latest aesthetic/layout changes), using the Ctrl+P shortcut to open an ipynb file appears not to work. When I do this, a new tab opens, but   stays blank, with the loading animation (the "travelling line" below the tab list) playing indefinitely.

There seems to be no problem in opening ipynb files with VS Code when done directly from the Windows Explorer.

Extension version: 2021.8.1046824664
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (3.42GB free)|
|Process Argv|G:\\Code\\workspace.code-workspace --crash-reporter-id c4587ea1-65de-4590-a2c4-cb48d86b4f8b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by szz65** [comment]
I just meet a similar problem. When I chose to open a file with jupyter notebook(custom), it just stays blank and with the loading animation (the "travelling line" below the tab list) playing indefinitely too.

**Comment by rchiodo** [comment]
Jupyter notebook (custom) should not be an option anymore (see this issue: #6741).

However CTRL+P should work. This might be a problem if the file was recently opened with the custom editor. I can open non recently opened ipynb files that way but I can't open files that were opened with the custom editor last. 

This might be a VS code core problem with custom editors.

**Comment by rchiodo** [comment]
Yeah if I force it to use the new editor, then CTRL+P works for a particular file:

![image](https://user-images.githubusercontent.com/19672699/126522289-c46f79cc-7c79-4128-b463-73bda83dffc3.png)

Pick the Jupyter notebook (preview) for the file that's having the problem.

**Comment by rchiodo** [comment]
Double clicking on the file in the file explorer seems to fix the problem too.

**Comment by Abhishek2271** [comment]
For me it gives this error while opening and then opens the ipynb file in a text editor.

![image](https://user-images.githubusercontent.com/33551684/126525877-51f8dc44-1d8c-4491-99b8-da77e48337ca.png)

**Comment by jfm-data** [comment]
Notebooks are not loading after the new update. Tried down grading to earlier versions and they will still not load.

**Comment by rchiodo** [comment]
@jfm-data if you run this command 

![image](https://user-images.githubusercontent.com/19672699/126540181-5aef5bbf-3d39-4bb9-9236-190454c2d930.png)

(using the latest bits)

Do you get a UI?

**Comment by Abhishek2271** [comment]
I fixed this issue by uninstalling the Notebook and reinstalling it.
Try opening an individual notebook rather than a folder.

**Comment by rchiodo** [comment]
This should be fixed now.
