### ISSUE TITLE
%%timeit cell magic not working

### ISSUE THREAD

**Issue by msm1089** [microsoft/vscode-jupyter#6736]
I searched for issues with timeit, but only one issue was found and not related to this.

## Environment data

-   VS Code version: 1.58.2 (commit c3f126316369cd610563c75b1b1725e0679adfb3)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1046824664
-   Python Extension version (available under the Extensions sidebar): v2021.7.1050252941
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.19043
-   Python and/or Anaconda version: 3.7.6
-   Type of virtual environment used - conda: 4.10.3
-   Jupyter server running: Local

## Expected behaviour

```
%%timeit

sum([i for i in range(10 ** 3)])
```
Above code should run, with timeit results displayed in cell output.

## Actual behaviour

Cell output displays "` not found."

## Steps to reproduce:

Run the short code above.

NOTE: For some reason, when I opened VS Code today, I got a new look for Jupyter. Cell magics (or at least timeit) were working yesterday. So it is almost certainly an issue with the latest update. Annoyingly, after following the instructions in https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code, I still have the new look. So I cannot go back to the old look and see if that works.

**Comment by rchiodo** [comment]
Can you show the output? It seems to work for me:

![image](https://user-images.githubusercontent.com/19672699/126522507-b53251df-f605-44df-a1f1-c4ae41112ef5.png)


If you get different output, can you include the output from the 'Jupyter' output tab?

**Comment by msm1089** [comment]
Here is a screenshot showing the result.
![image](https://user-images.githubusercontent.com/30074920/126565224-7c939648-e532-49c5-987d-8560e2147674.png)

What is the Jupyter output tab? I see a tab called Output in the console area, but this is blank.

**Comment by rchiodo** [comment]
This tab here
![image](https://user-images.githubusercontent.com/19672699/126565689-0ba9f6cc-3077-4d67-8456-e9c587904537.png)

You have top pick 'Jupyter' in the dropdown on the right side.

**Comment by msm1089** [comment]
@rchiodo - Thanks, but for some reason the view has went back to what it was previously! In order to try and replicate the issue, I have tried to get the new style back, again using the directions in https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code. But this is not working, it is coming up with an error as below. I tried saving these settings anyway and running but still had the old look.

Happy for you to close this, since I cannot now replicate. But it is confusing and annoying that the behaviour of the jupyter extension is inconsistent :/

![image](https://user-images.githubusercontent.com/30074920/126607441-296b12fe-7c52-4164-80c8-5df22a67d997.png)

**Comment by msm1089** [comment]
Just adding a comment to close this. I will create a new issue re. the optin to native editor not working.

**Comment by msm1089** [comment]
Well it is working now! Seems like it just took some time to update something somewhere, as I now have the new look back. Even better, timeit cell magic is now working :)

**Comment by msm1089** [comment]
Aggh! It worked when I first opened a notebook to test. But now it is not working any longer. The output after running the cell with %%timeit is below. Any idea what it could be? I could not find anything suspicious in the output except 4 lines which begin

`Info 2021-07-22 10:16:53: Cell Index:9, state:3, exec: undefined...`

```
Info 2021-07-22 10:16:53: Execute Cells request 1 9
Info 2021-07-22 10:16:53: Execute Cell 9 file:///c%3A/PythonProjects/interactive-coding-challenges/online_judges/merge_ranges/merge_ranges_challenge.ipynb
Info 2021-07-22 10:16:53: Cell Index:9, state:1, exec: 55. User queued cell for execution
Info 2021-07-22 10:16:53: Cell Index:9, state:1, exec: 55. Ready to execute
Info 2021-07-22 10:16:53: Cell Index:9, state:1, exec: 55. Before Execute individual cell
Info 2021-07-22 10:16:53: Cell Index:9, state:1, exec: 55. Start execution
Info 2021-07-22 10:16:53: Cell Index:9, state:3, exec: undefined. Send code for execution
Info 2021-07-22 10:16:53: Cell Index:9, state:3, exec: undefined. Wait for jupyter execution
Info 2021-07-22 10:16:53: [32mWidget Coordinator sent IPyWidgets_mirror_execute
Info 2021-07-22 10:16:53: [32mPosting message to Notebook UI 
Info 2021-07-22 10:16:53: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-22 10:16:53: [32mPosting message to Notebook UI 
Info 2021-07-22 10:16:53: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-22 10:16:53: [32mPosting message to Notebook UI 
Info 2021-07-22 10:16:53: Cell Index:9, state:3, exec: undefined. Kernel switching to busy
Info 2021-07-22 10:16:53: Notebook Session status file:///c%3A/PythonProjects/interactive-coding-challenges/online_judges/merge_ranges/merge_ranges_challenge.ipynb # Busy
Info 2021-07-22 10:16:53: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-22 10:16:53: [32mPosting message to Notebook UI 
Info 2021-07-22 10:16:53: Cell Index:9, state:3, exec: undefined. Update streamed output
Info 2021-07-22 10:16:53: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-22 10:16:53: [32mPosting message to Notebook UI 
Info 2021-07-22 10:16:53: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-22 10:16:53: [32mPosting message to Notebook UI 
Info 2021-07-22 10:16:53: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-22 10:16:53: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-22 10:16:53: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-22 10:16:53: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-22 10:16:53: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-22 10:16:53: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-22 10:16:53: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-22 10:16:53: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-22 10:16:53: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-22 10:16:53: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-22 10:16:53: Cell Index:9, state:3, exec: 57. Kernel switching to idle
Info 2021-07-22 10:16:53: Cell Index:9, state:3, exec: 57. Jupyter execution completed
Info 2021-07-22 10:16:53: Cell Index:9, state:3, exec: 57. Completed successfully
Info 2021-07-22 10:16:53: Cell Index:9, state:3, exec: 57. Completed successfully & resolving
Info 2021-07-22 10:16:53: Notebook Session status file:///c%3A/PythonProjects/interactive-coding-challenges/online_judges/merge_ranges/merge_ranges_challenge.ipynb # Idle
Info 2021-07-22 10:16:53: Cell Index:9, state:3, exec: 57. After Execute individual cell 3
Info 2021-07-22 10:16:53: Cell Index:9, state:3, exec: 57. Executed successfully in executeCell
Info 2021-07-22 10:16:53: Cell Index:9, state:3, exec: 57. Execution disposed
```

**Comment by msm1089** [comment]
Reopening...

**Comment by rchiodo** [comment]
What does the cell look like when it doesn't work? This might be an issue with the output you're generating or your version of ipython. We don't do anything special with %%timeit or any other cell magics. We just pass them onto ipython.

I can run this code 100s of times and it works each time:

```
%%timeit -n 2

sum(i for i in range(10 ** 3))
```

**Comment by msm1089** [comment]
I posted a screenshot earlier, nothing looks wrong, other than the result (or lack of...).
![image](https://user-images.githubusercontent.com/30074920/126680977-a0785903-a075-482e-bd1d-c948c2cef10f.png)

I have checked in a standard Jupyter notebook, %%timeout works fine everytime. I have never had problems with it until using the new style notebook editor in VS Code. So Occam's razor suggests VS Code is somehow causing the problem, although I appreciate that Occam's razor sometimes slips!

To try and help get to the bottom of this, I will opt out of NativeNotebookEditor again, if I can. Once I have the old style back, will update whether the problem persists.

Thanks for looking into this so far @rchiodo. Would you mind casting your eye over my settings.json above? I posted it as a screenshot to show the error it is flagging, even tho I have added the lines to opt in straight from the official guide. Does this look as it should for everything to be working for the new style? I am thinking maybe the error in here is causing it...

**Comment by rchiodo** [comment]
>  I am thinking maybe the error in here is causing it...

The error in the settings is a red herring. It's because we originally didn't want people signing up for the experiment on purpose (we control whether people are in an experiment with an automated system so we can run experiments without skewing numbers with optin situations).

To get back to the old style, you can just use 'Open With ...'

![image](https://user-images.githubusercontent.com/19672699/126686324-b3b5565b-b595-46e4-982c-e3ade366466e.png)

And then pick 'Jupyter Notebook (Custom)'

![image](https://user-images.githubusercontent.com/19672699/126686387-007efc3a-92a5-4886-a983-8515074eaef1.png)

on the popup. 

At least as of this morning. You might have to update your jupyter extension to do this as we just made this possible last night.

**Comment by msm1089** [comment]
Thanks for the info @rchiodo

I used the option to 'Open with...', then selected 'Jupyter Notebook (custom)'. As you said, it opened it in the old style :)
I can run %%timeout fine in this view. One thing I noticed, in the new style, the first '%' character is highlighted as an error (by Pylance, see below). In the old style it is not. Maybe a clue?

![image](https://user-images.githubusercontent.com/30074920/126693421-95129e6f-8604-41ac-9fec-0555b17bd912.png)

Another thing is that *sometimes* it works when I have just started a kernel (e.g. by opening a notebook and running a cell, so that I get asked which python to use). But at some point after this, it stops working. I have tried different things out but have not been able to get a 100% replicable example.

Last possible 'clue'...during testing, after noting that it had stopped working, I tried running %%timeout with some code that should throw an error (it relied on defs not already run). The result was  the same as in the screenshot I posted, i.e. ' not found printed to cell output. No sign of any exception as would normally happen. So whatever is going wrong, it is before the actual code (after the cell magic) in the cell is run.

**Comment by rchiodo** [comment]
It might be the cell from the new editor is sending extra linefeeds (over what the old editor did). That might be caused by some difference in our settings.json.

Mine looks like this:

```
{
    "workbench.colorTheme": "Default Light+",
    "window.zoomLevel": -1,
    "git.enableSmartCommit": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "notebook.cellToolbarLocation": {
        "default": "right",
        "jupyter-notebook": "right"
    },
    "jupyter.interactiveWindowMode": "perFile",
    "python.languageServer": "Pylance",
    "jupyter.experiments.optInto": [
        "__NativeNotebookEditor__"
    ],
    "[jsonc]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
    },
    "notebook.outline.showCodeCells": true
}
```

**Comment by msm1089** [comment]
Thanks for providing your settings. I copy-pasted them over my own settings, even installed a couple extensions so everything was recognised (except the `optInto` for `__NativeNotebookEditor__`). It didn't make any difference tho :/

**Comment by rchiodo** [comment]
Can you try the same thing with all extensions except for python and jupyter disabled? It might also be another extension that's adding extra code to the cell.

The new UI allows extensions to interact with the cell editor, the old one didn't.

**Comment by msm1089** [comment]
No joy after disabling all extensions other than the 2 required to run the notebooks.

**Comment by rchiodo** [comment]
I can't seem to repro this still. If you can still repro, can you include your notebook that's causing the problem? And maybe what your environment list is (pip list)
