### ISSUE TITLE
Python kernel doesn't update after downgrading python version in conda env

### ISSUE THREAD

**Issue by geoffery00** [microsoft/vscode-jupyter#6746]
Issue Type: <b>Bug</b>

1. Start a jupyter notebook in vscode
2. Select a higher version of python i.e. 3.9 kernel in conda env
3. Remove the conda env and create another conda env with the same name and downgrade with python=3.7
4. go back to vscode. The jupyter interface still shows python 3.9 conda env kernel. However, if I run !python --version the output shows the lower version of python (3.7)

![image](https://user-images.githubusercontent.com/7441182/126554084-3997872f-fbc3-490f-9338-0b3127fcb3fe.png)

Extension version: 2021.8.1046824664
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.22419
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (44.20GB free)|
|Process Argv|--crash-reporter-id f3adedc0-6cce-44a3-ad27-5471077a85ef|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vspre833:30321513
vsdfh931cf:30280410
vshan820:30294714
vscus158:30321503
vscod805:30301674
bridge0708:30335490

```

</details>

**Comment by rchiodo** [comment]
Thanks for the bug. 

This seems unlikely we'd update the name. It should refresh after reloading VS code (we get the name from the python extension actually).

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on addressing this issue at this time. The name should get update on next VS Code load. And the right environment is being used.
