### ISSUE TITLE
Local undo/redo for each cell

### ISSUE THREAD

**Issue by Abdelgha-4** [microsoft/vscode-jupyter#6755]
When performing undo/redo actions in jupyter notebook, only the active cell is affected so none of changes made in other cells are affected, however in Vscode it seems that the undo stack is global over the whole file (like a normal file), can this behavior be changed to the same as jupyter notebook, or even better detecting the appropriate one automatically based on if a cell is active or not.

**Product and Version** VSCode
**OS Version** Windows
**Jupyter Extension Version:** latest

**Steps to Reproduce / Scenario:**

1. Make changes in cell A
2. Make changes in cell B
3. Activate cell A and press Undo
4. Changes in cell B are undone

**Comment by joyceerhl** [comment]
You can add the following setting to your settings.json to achieve local undo/redo:

```
    "notebook.undoRedoPerCell": true,

```

**Comment by DonJayamanne** [comment]
Please feel free to report back if the above doesn't address the issue.
