### ISSUE TITLE
cursor disappear in Cell occasionally when you press Alt+Tab once or twice in Windows

### ISSUE THREAD

**Issue by kkonghao** [microsoft/vscode-jupyter#6763]
## Environment data

-   VS Code version: 1.58.2
-   Jupyter Extension version (available under the Extensions sidebar): 2021.8.2
-   Python Extension version (available under the Extensions sidebar): 2021.7.1
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: 3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A     Local

## Expected behaviour

cursor stay in same place rather than disappear

## Actual behaviour

cursor disappear when you Alt+Tab to other than back to vscode

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. cursor in a cell
2. press alt+tab and  alt+tab back

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by CatNofishing** [comment]
Exactly same problem after upadte latest vscode version，https://github.com/microsoft/vscode/issues/128658

**Comment by DonJayamanne** [comment]
@kkonghao thanks for filing this issue. We've updated the Notebook interface recently and there are significant differences between the two (if anything, the latest Notebook Interface addresses a number of issues we had in the past).

Please could you upload a screenshot of the notebook interface so we know which one you're using.
If its the new interface, then this is an issue in VS Code & we'll need to transfer this issue.

@CatNofishing , please could you also provide the above screenshot. Thanks

**Comment by CatNofishing** [comment]
@kkonghao   This problem will appear suddenly, and the frequency is very high, your mouse will suddenly be unable to edit jupyter cell, Multiple cursors flash together at the same time.
![动画](https://user-images.githubusercontent.com/33288114/126093255-0a0db709-d78b-4798-8b8c-9a2c6ee7ff77.gif)

**Comment by DonJayamanne** [comment]
@CatNofishing we've shipped a new Notebook Editor, and you should get the latest UI. Please could you ensure you are using the latest version of VS Code & the Jupyter extesnion (& ensure you're connected to the internet, having a network connection is a requirement of the experiment framework). 
Please note, the new notebook interface should fix this issue.

**Comment by CatNofishing** [comment]
@DonJayamanne Do you mean to use jupyter in the vscode insider version?

**Comment by petruccigp** [comment]
@CatNofishing : thanks for tagging me in this issue. I've installed VS Code Insiders with the latest Python and Jupyter extensions, and now I fail to reproduce issue #6770 and this one. The link to install VS Code Insiders: https://code.visualstudio.com/insiders/

The interface for Jupyter has changed quite a bit (for better imo), removing many of the quality of life complains that I had. Thanks @DonJayamanne and team for the great work!

**Comment by CatNofishing** [comment]
@petruccigp  Yes, but the insider version has many functions that need to be improved and it is not stable. I don't want to migrate to that version now. I prefer the stable version now.😂

**Comment by DonJayamanne** [comment]
> but the insider version has many functions that need to be improved and it is not stable. I don't want to migrate to that version now. I prefer the stable 

Sorry to hear about that, please could you file bugs for each with information so we can replicate at our end and help you get unblocked

**Comment by greazer** [comment]
Please reopen if VS Code v1.59 hasn't resolved this issue.
