### ISSUE TITLE
Ability to open figure in a new window and zoom in and out

### ISSUE THREAD

**Issue by xiaosihao** [microsoft/vscode-jupyter#6764]
After the latest update, I cannot open the figures in the notebook in a new window and zoom in. It is a very crucial feature to have for a data scientist. Could anyone let me know if my settings are wrong or did they just removed this feature? Many thanks.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue & I'm sorry this wasn't added earlier to the new Notebook interface, we've addressed this issue in the latest insider build and we'll be releasing this in the next version.

If you'd like you can try this out today in the latest Insider Build (install VS Code Insiders and you'll get the feature you are looking for).

Closing as this has been resolved, if you are still experiencing issues in the insiders version, please feel free to report back here or file a new issue.
