### ISSUE TITLE
Full editor crash in Jupyter notebook after checking image output

### ISSUE THREAD

**Issue by petruccigp** [microsoft/vscode-jupyter#6770]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
- OS Version: Windows 10 Pro 10.0.19043

Steps to Reproduce:

1. Create a simple Jupyter notebook with one cell and the following code (guess any other plotting library with the same underlying mechanism might work)

```python
import matplotlib.pyplot as plt

plt.grid()
plt.show()
``` 

2. Run the cell. Click on the Expand Image at the upper left corner of the image:

![image](https://user-images.githubusercontent.com/658179/126084768-a966946c-5c6b-4a4f-bcc9-30e917c8fea0.png)

3. In the new tab with the image expanded, click and move the image.

4. Close the tab, going back to the original Jupyter tab. Click and drag the image, and VSCode crashes.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (20.41GB free)|
|Process Argv|--crash-reporter-id e0672b45-8b31-4560-b801-4fa7bfcbceaa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.2.0
vscode-markdownlint|Dav|0.42.1
gitlens|eam|11.6.0
vscode-dashboard|kru|2.3.2
vscode-docker|ms-|1.14.0
vscode-postgresql|ms-|0.3.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1013163132
remote-containers|ms-|0.187.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.5.1
cpptools-extension-pack|ms-|1.0.0
vscode-yaml|red|0.21.1
unique-window-colors|stu|1.0.51
vscode-icons|vsc|11.5.0
vim|vsc|1.21.5
markdown-all-in-one|yzh|3.4.0

(2 theme extensions excluded)

</details>

**Comment by CatNofishing** [comment]
I think I also encountered the same problem,https://github.com/microsoft/vscode-jupyter/issues/6763

**Comment by petruccigp** [comment]
@joyceerhl I've installed VS Code Insiders with the latest Python and Jupyter extensions, and now I fail to reproduce this issue (also refer to #6763).
