### ISSUE TITLE
changes in local python modules are ignored

### ISSUE THREAD

**Issue by kl0n** [microsoft/vscode-jupyter#6772]
<b>Bug</b>

After upgrading to vscode 1.58:
- I write some functions in some_function.py  file
- In order to use the functions from Jupyter nb, I either import functions from some_function.py or use %run magic at the begining of the cell
- After first run of the nb, any changes made in some_function.py are ignored in consequent runs of the nb.
- Issuing both import and %run magic does not change this aberrant behaviour. 
- Clearing the outputs and restarting the kernel randomly cures the problem.

Extension version: 2021.8.1054968649
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.8.0-63-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1659)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.34GB (7.97GB free)|
|Process Argv|--unity-launch --crash-reporter-id 0132ff39-72b1-4eb6-af76-81a6b781180d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30341831
bridge0708:30335490

```

</details>

**Comment by DonJayamanne** [comment]
Thanks for reporting this issue. I don't see how this would have worked in the past.
You must restart the kernel to see changes in the affected module (this is also how it works in classic Jupyter & Jupyter Lab).
You might be interested in https://github.com/microsoft/vscode-jupyter/issues/4555
