### ISSUE TITLE
Comment shortcut not working inside notebook cell

### ISSUE THREAD

**Issue by onnoeberhard** [microsoft/vscode-jupyter#678]
# Bug: Notebook Editor, Interactive Window, Editor cells

This is one of the most important features for code editing, especially in a jupyter notebook, where it is really easy to run a cell quickly multiple times, changing little things each time. Of course it is easy to write/delete the `#` manually each time, but nobody really wants to do that.

## Steps to cause the bug to occur

1. Pressing the "Toggle Line Comment" shortcut keys

## Actual behavior
Nothing happens

## Expected behavior
Line comment toggle

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** v2020.7.96456
-   **VS Code version:** 1.47.3
-   **Setting python.languageServer:** Microsoft
-   **Python and/or Anaconda version:** Python 3.8.3
-   **OS:** Mac
-   **Virtual environment:** conda

**Comment by vedal** [comment]
@greazer This still doesn't work for me even though checkmarked in https://github.com/microsoft/notebook-extension-samples/tree/main/jupyter-keymap

**Comment by joyceerhl** [comment]
@vedal this is supported in the preview notebook editor, which we are hoping to roll out to more users later this year. Please see https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/#how-to-try-out-native-notebooks for instructions on how to use the native notebooks interface.

**Comment by vedal** [comment]
@joyceerhl thanks for the answer! that looks very exciting :)
