### ISSUE TITLE
Run cell from python file always selects wrong kernel

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#6790]
Issue Type: <b>Bug</b>

When clicking on Run Cell command from a py file, it always picks python 3.9.1 kernel. If I switch to another one, close the editor, open again, it picks the right kernel. However once I reload the window, the selected kernel is 3.9.1 again.

Extension version: 2021.8.1055544705
VS Code version: Code - Insiders 1.59.0-insider (04485223ebc6a075f39966bf9b3e261359ac7818, 2021-07-23T19:21:12.120Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No
Remote OS version: Linux x64 4.19.128-microsoft-standard

**Comment by joyceerhl** [comment]
@rebornix It should be using your active Python interpreter--which interpreter do you have selected?

**Comment by rebornix** [comment]
@joyceerhl sorry, I forgot that it always picks up my active interpreter :(
