### ISSUE TITLE
Switching kernel shows two "Connecting to kernel" status

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#6791]
Issue Type: <b>Bug</b>

Switching kernel now renders two "Connecting to kernel" sys info.

Extension version: 2021.8.1055544705
VS Code version: Code - Insiders 1.59.0-insider (04485223ebc6a075f39966bf9b3e261359ac7818, 2021-07-23T19:21:12.120Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No
Remote OS version: Linux x64 4.19.128-microsoft-standard

**Comment by rebornix** [comment]
This only happens when users switching a kernel before the first kernel is fully connected. Thus moving out of July release.

**Comment by DonJayamanne** [comment]
Duplicate of #5896
