### ISSUE TITLE
"No variables defined" after running any file in "Variables" tab.

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [microsoft/vscode-jupyter#6794]
## Environment data

-   VS Code version: 1.58.2
-   Jupyter Extension version (available under the Extensions sidebar): Version: 2021.8.1054968649
-   Python Extension version (available under the Extensions sidebar): Version: 2021.7.1060902895
-   OS (Windows | Mac | Linux distro) and version: Linux openSUSE
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

Click on "Variables" and it shows variables data

## Actual behaviour

It shows "**No variables defined**" in any jupyter file tried after running many cells in them.

## Steps to reproduce:

1. open a jupyter file.
2. run some cells with variables in them.
3. click on "Variables"
4. It shows "No variables defined" in its tab.

**Comment by claudiaregio** [comment]
Hi @GreatBigWhiteWorld, could you possibly attach a screen recording of what you are seeing? 
I experienced a similar issue but it only happens when hitting "Run All" for the first time in a notebook, basically not giving the kernel enough time to actually load the variables. Is this the scenario you are running into too or is it happening after already having run some cells?

**Comment by GreatBigWhiteWorld** [comment]
> Hi @GreatBigWhiteWorld, could you possibly attach a screen recording of what you are seeing?
> I experienced a similar issue but it only happens when hitting "Run All" for the first time in a notebook, basically not giving the kernel enough time to actually load the variables. Is this the scenario you are running into too or is it happening after already having run some cells?

There is really nothing to add  here. There's not an exception that the "Variables" tab would work in my case.
Just open any jupyter file and run a few cells that contain variables, the "Variables" tab shows "No variables defined".

About a month ago when the jupyter extention in vscode UI looked quite different from now, it worked without problem.

**Comment by claudiaregio** [comment]
@GreatBigWhiteWorld Would you be able to share the notebook you are seeing reproduceable issues with? That way we can do some testing with it. I'm no longer able to reproduce this behavior unless I immediately try to open the variable explorer after hitting run all.

**Comment by GreatBigWhiteWorld** [comment]
@claudiaregio I found what's causing this issue.

If my first cell contains the following code:
```
import globals
globals.initialize()
```
then I'm having the issue of "No variables defined" described above, meaning defining any variables in the following cells won't change the blank variables tab.

In my "globals" .py file, it contains the code like the following:
```
def initialize():
    global CUSTOM_ENV
    CUSTOM_ENV = 'personal running environment stuff'
```
Hope this helps. Note that I didn't have this issue before until the recent updates.

**Comment by joyceerhl** [comment]
I can repro this issue, seems like even importing any user-defined Python module breaks the variable explorer 

![image](https://user-images.githubusercontent.com/30305945/127025143-c5c11968-b655-4690-8ce3-9b572055a2a8.png)

**Comment by greazer** [comment]
We should spend a bit of time trying to figure out if this is a regression from webview or not.

**Comment by joyceerhl** [comment]
Aha. It looks like `globals` is the name of the Python global dictionary of names 
![image](https://user-images.githubusercontent.com/30305945/127407228-8aed30ed-3c8c-4307-894c-b5e266714928.png)

For example, I cannot repro this when I have a user-defined module 
![image](https://user-images.githubusercontent.com/30305945/127407244-6e08f505-c2cb-45b3-9542-090ae2a1d3cb.png)

@GreatBigWhiteWorld If you rename your globals.py file to something else, does the variable explorer start working?

**Comment by GreatBigWhiteWorld** [comment]
@joyceerhl Renaming my globlals.py file to something else does fix this issue. Thank you !
That said I didn't seem to have this problem or maybe I didn't notice?
Moral of the story may be "don't name things too ordinary".

**Comment by JacksonKearl** [comment]
Are we accepting this `as-designed`? @joyceerhl

**Comment by joyceerhl** [comment]
@JacksonKearl the user has verified this so no further verification is needed. Thank you for checking!

**Comment by JacksonKearl** [comment]
The bug would seem to be that aliasing `globals` in user scripts breaks the variables view. If that's by design it might be nice to have some sort of warning render in the variables view rather than just breaking.
