### ISSUE TITLE
Under the same color theme, the code highlighting of the ipynb file and the py file are inconsistent, and the code highlighting of the py file is more complete

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/vscode-jupyter#6799]
## Environment data

版本: 1.59.0-insider (user setup)
提交: 04485223ebc6a075f39966bf9b3e261359ac7818
日期: 2021-07-23T19:21:12.120Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.18363

## Expected behaviour

The code highlighting of the ipynb file and the py file are consistent

## Actual behaviour
![image](https://user-images.githubusercontent.com/33288114/126894678-4db7ed74-8e1b-444d-87a9-98b9b51a007a.png)

**Comment by joyceerhl** [comment]
Are you getting any intellisense in your Jupyter notebook at all? 

Note for triage, this is likely an issue with the notebook concat document code in the Python extension.

**Comment by CatNofishing** [comment]
@joyceerhl  Do you mean I need to submit this issue to vscode-python?😁

**Comment by mtsitzer** [comment]
I am also experiencing both issues mentioned in this item.

As for the inconsistent code highlighting colors, the ipynb/notebook colors seem muted (very hard to tell from the CodeSnap screenshots --- but definitely noticeable to my eyes when working with these files) compared to the py file colors, not to mention the different highlighting behavior:

**.py**
![code_py](https://user-images.githubusercontent.com/28517224/129234954-e60bf205-e9a5-4b9b-888d-98d1e4cd9e75.png)
**.ipynb**
![code_ipynb](https://user-images.githubusercontent.com/28517224/129234963-0fa1c6e7-14e2-42a5-8864-da8544b3d1e3.png)

As for the missing intellisense in the Notebook, I've noticed that this problem largely goes away when opening the Notebook in a workspace --- i.e. an instance of VSCode that has been opened from "Open Folder."

**Comment by keg247** [comment]
I'm having the same highlighting issue.  I'm using Pylance and the Dark+ theme.  Unlike the py file, there is no semantic token information in the notebook - the only thing that shows is the textmates scope.  If I turn off semantic highlighting and use a theme with textmates scopes, the highlighting appears to be consistent between a py file and notebook (although I did not scrutinize all of the possibilities for consistency).

Intellisense works fine.

Environment data:
Version: 1.59.1 (system setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:56:07.791Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT ia32 10.0.19043

If helpful, I can capture and upload the Jupyter output, Pylance output, and developer console.
