### ISSUE TITLE
spacing preference after pasting code in cell is lost

### ISSUE THREAD

**Issue by robbiemu** [microsoft/vscode-jupyter#6801]
<img width="1132" alt="Screen Shot 2021-07-24 at 10 40 25 AM" src="https://user-images.githubusercontent.com/248927/126872014-272e9047-03ad-4e75-9372-7c9f84702667.png">
Issue Type: <b>Bug</b>

I like tabsize of 2, and this is set in my vsc settings. by default, my ipynb files are opened respecting this setting. but if I paste into a cell, all the lines indented with 2 spaces get a brown tint to the leading space. this does not go away resetting the language server, and does not go away by removing all indentation are reindenting, nor after undoing the paste operation.

Extension version: 2021.7.1050252941
VS Code version: Code - Insiders 1.59.0-insider (d624242076d166bb8ce8b314e8d44b8af6100a3d, 2021-07-19T05:14:11.338Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (9.75GB free)|
|Process Argv|--crash-reporter-id 8d04f1ce-a644-4737-b163-1f71625d3443|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
3f5j7703:30294757
vscod805:30301674
pythonvspyt200:30323110
vscextlang:30310088
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490

```

</details>

**Comment by joyceerhl** [comment]
Hi @robbiemu, apologies but I am unable to replicate this behavior in VS Code Insiders. Could you please confirm whether this behavior persists after disabling all other extensions? Thank you!

**Comment by robbiemu** [comment]
so, if I turn off all the extensions except this one, NO syntax highlighting is occurring for indentation
<img width="1104" alt="Screen Shot 2021-07-27 at 5 00 16 PM" src="https://user-images.githubusercontent.com/248927/127226767-046137d1-f0f0-4026-ad8d-80c8b9a7507b.png">
I'll take this over to pylance I guess
