### ISSUE TITLE
unwanted - key dev PC VSC 1.58.2 has flipped into Insiders mode

### ISSUE THREAD

**Issue by TickboxPhil** [microsoft/vscode-jupyter#6811]
Issue Type: <b>Bug</b>

My key dev VSC 1.58.2 has flipped into Insiders mode, as the Jupyter notebook Markdown Theme is solid grey (not very workable) and suddenly has the new cell timers. But big problem is this is buggy - the Variables (in both Jupyter and normal .py) don't show in window (Problems and Terminal etc aok), which is critical.

Oddly, my other laptop also has exact latest 1.58.2 and does maintain the Jupyter Markdown Theme without the timers, so is normal. So, why has my core dev machine switched to what looks like Insiders release? Am trying to recommend VSC but I need a stable IDE to get my work done.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (16.72GB free)|
|Process Argv|--crash-reporter-id d2176d00-8911-4b68-94f8-b8a8636608a0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.5
jupyter|ms-|2021.8.1054968649
synthwave-vscode|Rob|0.1.8

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306cf:30341832
bridge0708:30335490

```

</details>

**Comment by joyceerhl** [comment]
@TickboxPhil We recently enabled the preview notebook interface for 100% of customers in VS Code Stable who have not opted out of experiments. Your other laptop likely has a setting like `"jupyter.experiments.enabled": false` or `"jupyter.experiments.optOutFrom": ["NativeNotebookEditor"]` in the settings.json. We are currently planning to remove the ability to opt out in the upcoming release, so thank you for letting us know about these issues--we are working to fix them ASAP:

- You can disable the timers and the cell status bar by selecting 'hidden' instead of 'visible' for notebook.showCellStatusBar
![image](https://user-images.githubusercontent.com/30305945/127020722-5b43a0a5-67e7-41b9-baef-31806dc25287.png)
- We're aware of an issue with variable explorer sometimes not working https://github.com/microsoft/vscode-jupyter/issues/6794 Is this what you are seeing? 
- Re: Jupyter notebook Markdown theme, just to clarify, is the issue that you dislike the way that markdown cells currently render, or something else?

Thank you and apologies for the inconvenience.

**Comment by TickboxPhil** [comment]
Thanks for understanding and adding clarity @joyceerhl . 

There's a ton of settings.json scattered throughout Settings, but I found "Enable Experiments" under User -> Workbench, and have unticked it on dev PC. Unfortunately, even after restart of VSC that is not reflected and I still have the horrible markdown - it's flat grey on everything (code, comments and output) other than charts, so difficult to distinguish cells. I'm not fussed about disabling the timers - they're great in fact, I just don't want the unclear markdown, a massive backwards step. Also concerning you guys removing that "Enable Experiments" toggle and forcing it (as no "opt out" implies), as some of us have our own job to do, not QA of IDE! Am happy to use Insiders for that.

Difference between laptop and PC is the latter is user-install based, wheras laptop usually "for all users" - small chance that is why they're different ("Enable Experiments" is ticked on both, so not that).

The Variable Explorer not working (will test further against that other Issue) is another major setback forcing me to run to the other hell of PyCharm instead, was just getting used to VSC. Hope I can come back (am sure I will!). Thanks for your attention.

**Comment by joyceerhl** [comment]
@TickboxPhil we are shipping changes to improve distinguishing cells in the upcoming stable release, it will soon look like this: https://github.com/microsoft/vscode/issues/128885#issuecomment-882897697 You can also customize notebook color tokens in your settings.json.

Just to clarify, the reason that the enable experiments toggle is being removed is that the new notebook UI is being rolled out in full to replace the old UI, i.e. it is not intended to be an experimental feature any longer.

Sorry about the variable explorer not working. Would you mind sharing more info on how it's not working?

**Comment by TickboxPhil** [comment]
@joyceerhl am looking forward to seeing those proper cells again (but better and less contrast eye strain)! Even better when we can collapse/expand all code cells so we can review output easily (or use 2 panes like PyCharm) - I requested at https://github.com/microsoft/vscode/issues/128519 but there's a lot going on for folks.

Fair enough on non experimental UI. Hope we don't have to endure too much experimentation in production in future (happy to provide feedback on new stuff or changes but not on major obvious backsteps)!

Variable explorer became intermittant at same time as "new look" notebook UI, but it's working currently - will add to or create new Issue if it blanks out again.

Many thanks for keeping on it. Could really do with a way to get back to the old notebook UI but will suffer until the new one.

**Comment by joyceerhl** [comment]
Re: https://github.com/microsoft/vscode/issues/128519, does this command do what you want? 

![image](https://user-images.githubusercontent.com/30305945/127065220-6689a6c1-727b-42d6-91f4-10b7b6d6b375.png)

**Comment by TickboxPhil** [comment]
Ah - excellent, they do collapse now! Some gain with pain then, thanks for bringing this back to attention @joyceerhl.

Fantastic - big productivity gain with long notebooks (was a hassle having to split them and use %store -r dataframe to retrieve pickles even in same workspace).

Currently only works from the cell menu - the shortcut (on Windows) Crtrl + K Ctrl + C (umm, both or either?!) doesn't work - they mark the line as comment.

What would be killer is to **project this to a "Collapse/Expand All Code Cells" in the top bar**, to apply across the board. Massive production gain when poring through the outputs. That way, VSC much better than PyCharm which depends on split screen Code + Preview, wasting huge horizontal space (although sometimes good to have code and outputs separate).

Collapse/Expand All Code would seriously rock!

**Comment by joyceerhl** [comment]
The shortcut works when the cell is in edit mode. When editing a cell, press esc to put it into command mode. I'm on Windows and it definitely works for me (and verified Cmd+K Cmd+C also works on Mac). 

VS Code notebooks support multiselecting notebook cells, but unfortunately it looks like Collapse Cell Input doesn't handle all of them. I don't believe we support collapsing all cell inputs today, so I've gone ahead and opened https://github.com/microsoft/vscode/issues/129488

Out of curiosity, is collapsing/expanding all code cells something that you frequently have to do? What is the use case for this gesture, and why would you want it surfaced in the top-level toolbar (versus, say, just in the command palette)?

**Comment by TickboxPhil** [comment]
Ctrl K Ctrl C not working on my Windows PC - looking deeper, the first stroke does, as the status bar shows it's waiting for the second, but that Ctrl C instead just comments out the line with a prefix #. See screenshot:

![VSC Ctrl K Ctrl C not working](https://user-images.githubusercontent.com/16966543/127107109-cf889d48-7a57-434a-84e8-278de10fc86d.png)

Thanks for the Collapse/Expand All Request Issue, hope it gets some love! 

I understand need not to clutter the toolbar - and I think it's clearer with the text rather than tiny icons like before, so great. Maybe the +Code / + Markdown there is overkill unless the hover-overs between cells are not clear, but not a big problem. I didn't like losing the Save icon, but learn to keyboard shortcut it! 

I'd use the Collapse All on almost every notebook, as my usual focus is EDA, Regression, ML etc, where many outputs and charts need to be compared - and having code and functions clogging up the screen forcing constant scrolling does slow down progress and increase chance of visual mistakes. I personally would prefer it on the toolbar, but anywhere else inc command pallette is fine!

**Comment by joyceerhl** [comment]
From the screenshot above, it looks like you have your cursor inside the cell, which means the cell is in edit mode:

![image](https://user-images.githubusercontent.com/30305945/127109513-4a754a9b-82ca-41df-a0b9-f53b669f0242.png)

For Ctrl+K Ctrl+C to work, you'll want to put the cell in command mode (no cursor and no blue border around the cell editor area):

![image](https://user-images.githubusercontent.com/30305945/127109595-7843a3ea-2dd3-45b1-831d-dc3e5da1035f.png)

Hopefully that works for you 🤞

**Comment by TickboxPhil** [comment]
Ah yes indeed - that works when exiting editing mode, thanks @joyceerhl. It's a bit counter-intuitive, because I can't be the only one who selects a cell by putting cursor in it, and the cell toolbar then tells me I can use that shortcut (which is wrong). Wise to make it work in edit mode too!
