### ISSUE TITLE
Remote empty space in Interactive window cells

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#6816]
# Today (webview based)
<img width="582" alt="Screen Shot 2021-07-11 at 16 57 01" src="https://user-images.githubusercontent.com/1948812/125216139-1320d500-e272-11eb-85b9-7481d7e762a1.png">

# Current (too many spaces in info message & trailing spaces in code)
<img width="644" alt="Screen Shot 2021-07-11 at 16 58 19" src="https://user-images.githubusercontent.com/1948812/125216141-14520200-e272-11eb-817d-23184b64ba83.png">

# After the fix
<img width="1137" alt="Screen Shot 2021-07-11 at 18 02 37" src="https://user-images.githubusercontent.com/1948812/125216197-43687380-e272-11eb-97fa-03b93e52edda.png">

**Comment by DavidKutu** [comment]
validated
