### ISSUE TITLE
Testing Interactive Window Debugging with IPyKernel 6.0

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#6818]
Refs: https://github.com/microsoft/vscode-jupyter/issues/6534

- [x] anyOS @roblourens
- [x] dev container @stuartleeks

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%236818%0A%0A&assignees=DonJayamanne)

---

Debugging in Interactive Window was broken when using IPyKernel 6.
* It would either open a new editor with the code the user ran & stop there (debugger stops)
	* This could be replicated only on Desktops
* Or would open interactiveshell.py and stop there  (debugger stops)
 	* This could be replicated only on `dev Containers`

Changes were made to ensure both were fixed. First issue was a fix in Jupyter extension & second issue was fixed in the debugger package.

**How to test:**
# Desktop Setup

* Install VS Code Insiders
* Install latest version of Python extension
* Install Python 3.9 on Desktop
	* Use of non-conda is preferred as thats easier to setup and use.
* Test 1: Test with old version of IPyKernel (validate the fact that we didn't break debugging with previous version)
	* Uninstall currently installed packages & install the older versions
		* `python -m pip uninstall ipykernel ipython debugpy`
		* `python -m pip install ipython==7.15.0 ipykernel==5.5.5`
	* Start interactive window
		* Create a Python file named `sample.py`
		* Add the following code
		    ```python
		    # %%
		    message = "Hello World"
		    print(message)
		    ```
		* Click the code lens `Debug Cell`
		* The interactive window will appear on the right & debugger will start
		* Verify debugger stops at the first line `message = "Hello World"`
* Test 2: Test with latest version of IPyKernel (6.0)
	* Uninstall currently installed packages & install the older versions
    	* `python -m pip uninstall ipykernel ipython debugpy`
		* `python -m pip install ipython`
	* Start interactive window
		* Create a Python file named `sample.py`
		* Add the following code
		    ```python
		    # %%
		    message = "Hello World"
		    print(message)
		    ```
		* Click the code lens `Debug Cell`
		* The interactive window will appear on the right & debugger will start
		* Verify debugger stops at the first line `message = "Hello World"`

# Dev Container setup

* Ensure you have docker up n running
* Clone the repo https://github.com/DonJayamanne/testDebugPyInContainer
* Open above folder in VS Code container
	* I.e. open folder in VS Code
	* Then when prompted to open in `Container` click yes
	* Ensure you select `Python 3.9` as your workspace interpreter in python 
		* Open a Python file, then wait for Python extension to actiavte.
		* You'll see the Python interpreter information on the bottom left statusbar)
		* Click that to change it to Python 3.9
* Test 3: Test with latest version of IPyKernel (6.0)
	* Uninstall currently installed packages & install the older versions
    	* `<fully qualified path to python 3.9> -m pip uninstall ipykernel ipython debugpy`
		* `<fully qualified path to python 3.9> -m pip install ipython`
		* The `fully qualified path to python 3.9` should be `/usr/local/bin/python`, 
			* You can validate this by using the Interpreter picker (path is displayed
![Screen Shot 2021-07-26 at 12 59 21](https://user-images.githubusercontent.com/1948812/127051081-542f0e66-ce30-4480-9e0d-6243a788fe0b.png)

	* Start interactive window
		* Create a Python file named `sample.py`
		* Add the following code
		    ```python
		    # %%
		    message = "Hello World"
		    print(message)
		    ```
		* Click the code lens `Debug Cell`
		* The interactive window will appear on the right & debugger will start
		* Verify debugger stops at the first line `message = "Hello World"`

**Comment by stuartleeks** [comment]
The instructions above say to run the following:

```
<fully qualified path to python 3.9> -m pip uninstall ipykernel ipython debugpy
<fully qualified path to python 3.9> -m pip install ipython
```

When I do this and attempt to debug `sample.py`, I get this error:

![image](https://user-images.githubusercontent.com/1824461/127151438-bbc60730-f2ae-4d36-829a-eab23dea4771.png)

Clicking "Install" doesn't seem to resolve the issue. If I manually run `python -m pip install ipykernel` then I am able to debug again.

While debugging works after doing this, I get an extra file with a random filename that I didn't get with the 5.5.5 version of ipykernel.

![image](https://user-images.githubusercontent.com/1824461/127152653-8da732eb-ac2c-4b54-8cde-8616f53e3d1c.png)

**Comment by stuartleeks** [comment]
Debugging in devcontainer worked with additional steps (#6836)

**Comment by rzhao271** [comment]
Closing based on https://github.com/microsoft/vscode-jupyter/issues/6818#issuecomment-887483033
