### ISSUE TITLE
Display place holder kernel for `Python` when Python extension Or Python runtime isn't installed

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#6821]
Refs: https://github.com/microsoft/vscode-jupyter/issues/5864

- [x] anyOS @kieferrm
- [x] anyOS @alexr00

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%236821%0A%0A&assignees=DonJayamanne)

---

If users do not have Python extension installed, and they open a Jupyter notebook, they do not know what they need to do to be able to run a Notebook with Python.
Solution:
* If users do not have Python extension installed, we list a kernel named `Python` and when this kernel is used to run a notebook cell, they'll be prompted to install the Python extension.
* If users have the Python Extension installed but do not have any Python runtime (environment) on their machine, we list a kernel named `Python` and when this kernel is used to run a notebook cell, they'll be prompted to install the Python runtime.

**Testing**
# Test 1 (with Python runtime)

* Ensure you do not have Python extension installed
* Ensure you have Python installed.
* Install VS Code Insiders
* Open a Jupyter Notebook
* Verify you do not have any Python kernels
	* Next select the kernel `Python`
	* Now attempt to run a cell.
	* Verify you are prompted to install Python extension
	* Once installed, verify the list of Python interpreters are now displayed in the kernel picker (without having to re-load VS Code)

# Test 2 (without Python runtime)

* Ensure you do not have Python extension installed
* Ensure you do not have Python installed.
* Install VS Code Insiders
* Open a Jupyter Notebook
* Verify you do not have any Python kernels
	* Next select the kernel `Python`
	* Now attempt to run a cell.
	* Verify you are prompted to install Python extension
* Re-load VS Code, & open the same notebook.
* Verify you do not have any Python kernels
	* Next select the kernel `Python`
	* Now attempt to run a cell.
	* Verify you are prompted to install Python runtime

**Comment by alexr00** [comment]
Tested on Windows.
