### ISSUE TITLE
Enable plot viewer for Notebooks and Native Interactive Window

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#6823]
Refs: https://github.com/microsoft/vscode-jupyter/issues/6692

- [x] anyOS @rzhao271 
- [x] anyOS @rchiodo

Complexity: 3

---

Plot outputs should have an icon allowing users the ability to:
* Save the plot (image)
* Open the plot in the Plot viewer

**How to test**
* Install VS Code Insiders
* Install Jupyter Extension
* Install Python
* Create a notebook 
	* Add the following code in the cells:
		```python
		import matplotlib.pyplot as plt
		plt.plot()
		```
	* Run the above cell
	* Install missing dependencies:
		* You might be prompted to install IpyKernel, click ok.
		* You might get errors about matplot lib not existing.
		* If you are using `conda`, please please create a cell and run this cell
			* Cell with code to install matplotlib
			* ```%conda install -c conda-forge matplotlib```
		* If you are not using please please create a cell and run this cell
			* Cell with code to install matplotlib
			* ```%pip install matplotlib```
* Run the cell with the code 	```		plt.plot()```
* Verify you have an output with a plot
* Hover over the plot & verify you have two icons for `save` and `open`.
	* Clicking on the save icon should allow you to save the plot as svg or pdf.
	* Clicking on the show plot viewer icon should allow you to open the plot in the plot viewer

**Icons on plots (top right, click to save or show plot viewer)**
![Screen Shot 2021-07-26 at 13 46 40](https://user-images.githubusercontent.com/1948812/127056869-d28b7641-7ded-43f6-8328-3c86efb79342.png)

**Plot viewer**
![Screen Shot 2021-07-26 at 13 46 54](https://user-images.githubusercontent.com/1948812/127056901-effb428b-e254-4b7a-bd17-03814892ee37.png)

**Comment by rzhao271** [comment]
I encountered https://github.com/microsoft/vscode-jupyter/issues/6851 while testing.
