### ISSUE TITLE
The venv kernels are not shown in the kernel list with the default server in jupyter notebook need to use existing one.

### ISSUE THREAD

**Issue by gwynbleidd415** [microsoft/vscode-jupyter#6832]
## Environment data

-   VS Code version: 1.58.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1054968649
-   Python Extension version (available under the Extensions sidebar): v2021.7.1060902895
-   OS (Windows | Mac | Linux distro) and version: Manjaro 21.0 with linux kernel 5.13.4
-   Python and/or Anaconda version: python 3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

On starting the ipynb files the kernels i have set in the kernelspec list should appear.

## Actual behaviour

On starting the ipynb files the kernels i have set in the kernelspec list doesn't appear. But when i start a jupyter notebook connection via terminal and then copy the localhost address it gets hosted on and then choose existing server option and use that server created on the terminal then the kernels get listed. The default kernel doesn't list them.

## Steps to reproduce:

1. Open a .ipynb file.
2. In the select kernel the venv kernel is not present but the python kernel is there.
3. Then on starting a jupyter server via terminal then using that as the existing server then the kernels are listed.

**Comment by rchiodo** [comment]
Thanks for the bug.

Can you do a ```jupyter kernelspec list --json``` on the command line and copy the contents here?

If you start jupyter and use a 'remote' connection to it, it gives us the list of kernels, so they should match. When we don't use jupyter we should be using the same list as ```jupyter kernelspec list```. Those two should be the same though.

Additionally if you could attach the output from the 'Jupyter' output tab, that would be helpful too.

Thanks.

**Comment by gwynbleidd415** [comment]
Sorry for the late reply, this is the json data

{
  "kernelspecs": {
    "webenv": {
      "resource_dir": "/home/gwynbleidd/.local/share/jupyter/kernels/webenv",
      "spec": {
        "argv": [
          "/mnt/myParts/sda2/Programs/Python/WebWorks/webvenv/bin/python",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "webenv",
        "language": "python",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    },
    "pyenv": {
      "resource_dir": "/home/gwynbleidd/.local/share/jupyter/kernels/pyenv",
      "spec": {
        "argv": [
          "/mnt/myParts/sda2/CollegeWork/Python/pyenv/pyenv/bin/python",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "pyenv",
        "language": "python",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    },
    "python3": {
      "resource_dir": "/home/gwynbleidd/.local/share/jupyter/kernels/python3",
      "spec": {
        "argv": [
          "python",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    }
  }
}

**Comment by rchiodo** [comment]
Can you include the contents of the 'Jupyter' output panel? My guess is that we're ignoring those other kernelspecs because their venv is not located under the currently open workspace.

**Comment by gwynbleidd415** [comment]
The output part in the vs code is empty. Also when i run jupyter notebook from the terminal and then change the server from local to the one that is started in the terminal then I am able to see all the kernelspecs that I have created.

**Comment by greazer** [comment]
Thanks for your feedback. This issue should be fixed in the latest VS Code Insiders build. If it's not, please reopen. Thanks again!
