### ISSUE TITLE
Python kernel placeholder confusion

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-jupyter#6834]
Testing https://github.com/microsoft/vscode-jupyter/issues/6821

In Test 1:
> Next select the kernel Python

I don't have an option to choose Python. Not sure if this is just a jupyter noob issue though, as this is literally my first time using jupyter notebooks.

![recording (60)](https://user-images.githubusercontent.com/38270282/127124380-f891acc3-ad65-4e1e-90b9-aeb72b68b8c4.gif)

I installed the Jupyter extension and tried to Select a kernel again, but it didn't show up in the picker. After closing and opening my notebook again(1), I found that the Python 3 kernel had already been selected for me and I couldn't unselect it to run through the test properly. 

When I attempted to run a cell I got this modal telling me to install python and I was able to complete test 1✔
![image](https://user-images.githubusercontent.com/38270282/127124946-d3d86082-92da-4c76-a9b8-9775185c9909.png)

(1) I did get prompted to install python at this point, but I didn't since that wasn't part of test plan item.

**Comment by alexr00** [comment]
Same deal with Test 2. After Jupyter was installed, the Python 3 kernel was automatically selected (I made sure there was no python installed).

**Comment by DonJayamanne** [comment]
The extension was updated yesterday with a fix, please could you retest this  with the latest version of the jupyter extension.

**Comment by greazer** [comment]
@alexr00, please reopen if this isn't fixed now.
