### ISSUE TITLE
Debugging requires manual ipkernel install (and creates additional file)

### ISSUE THREAD

**Issue by stuartleeks** [microsoft/vscode-jupyter#6836]
Testing #6818

The instructions for #6818 say to run the following:

```
<fully qualified path to python 3.9> -m pip uninstall ipykernel ipython debugpy
<fully qualified path to python 3.9> -m pip install ipython
```

When I do this and attempt to debug `sample.py`, I get this error:

![image](https://user-images.githubusercontent.com/1824461/127151438-bbc60730-f2ae-4d36-829a-eab23dea4771.png)

Clicking "Install" doesn't seem to resolve the issue. If I manually run `python -m pip install ipykernel` then I am able to debug again.

While debugging works after doing this, I get an extra file with a random filename that I didn't get with the 5.5.5 version of ipykernel.

![image](https://user-images.githubusercontent.com/1824461/127152653-8da732eb-ac2c-4b54-8cde-8616f53e3d1c.png)

**Comment by DonJayamanne** [comment]
> debugging works after doing this, I get an extra file

Please could you provide the following information:
* Os
* Dev container, or ssh or wsl or other
* Jupyter and python extension versions

**Comment by stuartleeks** [comment]
Version: 1.59.0-insider (user setup)
Commit: 0f22f2d343e33b03e8033d1083513072f58ece21
Date: 2021-07-29T05:13:10.735Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

Running in the dev container from https://github.com/DonJayamanne/testDebugPyInContainer

Jupyter extension: v2021.8.1077987658
Python extension: v2021.7.1060902895

**Comment by DonJayamanne** [comment]
Moving to verification

**Comment by rchiodo** [comment]
The install works, but I get this error when debugging a cell:
https://github.com/microsoft/vscode-jupyter/issues/7141
