### ISSUE TITLE
Disable vim ==only== in notebook editors

### ISSUE THREAD

**Issue by rosspleban** [microsoft/vscode-jupyter#6837]
Can support be added to turn off vim support ==only== in notebook editors?

The combination of notebook hotkeys and vim bindings creates a lot of unintentional behavior.  I find it much easier to edit notebooks with non-vim bindings.  

Global disable of vim is an option, but is a pain when working with multiple types of files (notebook, c++, and python).

**Comment by rchiodo** [comment]
I believe this would be up to the VIM extension and not the jupyter extension.

**Comment by rchiodo** [comment]
They would have to detect when they're being loaded into a document that was inside of a notebook.
