### ISSUE TITLE
"Run Python in Terminal" button in the Python extension should run cells in a #%% Python script.

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-jupyter#6839]
Testing microsoft/vscode#129288

With the python extension installed you have the run icon in the top right. With an interactive window opened I expected the interactive cells to get executed there. I'm not sure what the best UI would be though as I understand it can be a mixed file

**Comment by amunger** [comment]
The button now says `run python file in terminal` to disambiguate
