### ISSUE TITLE
Debugging an untitled file causes the file to close and re-open

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-jupyter#6841]
Testing microsoft/vscode#129288

1. Create an untitled Python file with some cells
2. Debug a cell
3. A save dialog comes up. Save the file
4. The file seems to close and then re-open in debug view, which I find confusing. For a second or two, I wonder whether I have to manually re-open the file.

**Comment by joyceerhl** [comment]
This behavior repros in the webview interactive window, hence moving to August milestone.

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on addressing this functionality at this time. Yes, it's strange, but I don't think it's serious enough to address right now.
