### ISSUE TITLE
Move export button into notebook toolbar overflow menu

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#6845]
Based on discussion at notebook sync this morning. The thought here is that this is not frequently used, so making it two clicks to access instead of one will not hurt users, and will also make the toolbar less crowded.

**Comment by joyceerhl** [comment]
@claudiaregio In the long run we want this command to live in the file > export menu, but right now extensions do not have the ability to contribute to the file menu.

**Comment by rebornix** [comment]
Fixed in main.

**Comment by TylerLeonhardt** [comment]
Looks right :) 
![image](https://user-images.githubusercontent.com/2644648/127573893-173a61af-8e7c-495c-94d3-c58723f45d76.png)
