### ISSUE TITLE
Editing with custom editor and reopening doesn't show dirty icon until clicking on tab

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6848]
Testing #6813

Start with this:

![image](https://user-images.githubusercontent.com/19672699/127223637-7f2d63cd-0432-4bd9-b7d6-00eeac7132f0.png)

bugbash.ipynb is a custom editor.

Reload VS code

Tab for background file is not marked as dirty

![image](https://user-images.githubusercontent.com/19672699/127223716-9a4a4a04-e531-4e67-969a-77290fe1fb5a.png)

**Comment by joyceerhl** [comment]
No repro, for me it's marked modified after reload: 
![image](https://user-images.githubusercontent.com/30305945/127228109-79ea1235-6d84-415d-9597-0a7676bf2005.png)

**Comment by rchiodo** [comment]
Doesn't look modified to me? THe background tab is the one with the problem.

**Comment by rchiodo** [comment]
How did you repro the double reload problem then? It doesn't repro if the background tab shows up as modified.

**Comment by joyceerhl** [comment]
> How did you repro the double reload problem then

I reloaded twice in quick succession without activating the backgrounded tab

**Comment by rchiodo** [comment]
So for this problem your background tabs auto activate?

**Comment by joyceerhl** [comment]
Weird, earlier I didn't need to set focus to the editor for it to show as modified, but now it doesn't show the dirty icon until clicking on the tab (i.e. now I'm reproing the behavior you described in this issue)

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/commit/e437d424c5e6de97632f5513229c7ebc2cf27a32
