### ISSUE TITLE
Modal dialog for restart kernel confirmation

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#6850]
Not sure if we have to show this dialog at all since but since we do, I think it is more accessible if we use a modal dialog other than a notification. On a 27 inch monitor, with 200% scale, I still find myself often miss the notification when I am looking at the top toolbar

![image](https://user-images.githubusercontent.com/876920/127230247-a11b9d80-9ec0-4cd2-9b92-ad5f7174d4c7.png)

**Comment by DonJayamanne** [comment]
This has been done & verified
