### ISSUE TITLE
Misleading diagnostics for !pip

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#6851]
![image](https://user-images.githubusercontent.com/876920/127230502-6c782b74-7a4a-4e69-8330-ad69599b696e.png)

Pylance keeps showing errors for `!pip`.

**Comment by rzhao271** [comment]
I get pip is not defined, install is not defined, and pandas is not defined.

The errors seem to be from Pylance.

Here's another example screenshot:
![Screenshot showing pip command runs, even though Pylance says it contains errors](https://user-images.githubusercontent.com/7199958/127239222-2f60d575-51ff-4832-acf7-90d9b7081fba.PNG)

**Comment by DonJayamanne** [comment]
Dup of https://github.com/microsoft/vscode-jupyter/issues/1497
