### ISSUE TITLE
Interactive Panes for every file

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#6853]
Issue Type: <b>Bug</b>

I used to be able to run python code in the Interactive Pane from any python file I chose.  Now I get a new Interactive pane for every single file.  

How do I restore the old behavior?

Extension version: 2021.8.1054968649
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (1.40GB free)|
|Process Argv|--crash-reporter-id 1e88d7ed-dfc2-42ed-b5d3-970568cb872e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306cf:30341832
bridge0708:30335490

```

</details>

**Comment by clayms** [comment]
I can create a ***generic*** Jupyter Interactive Window with <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>P</kbd> and selecting `Jupyter: Create Interactive Window`.  However, I cannot find a command like `Jupyter: Run Selection/Line in Interactive Window` (or equivalently `command: jupyter.execSelectionInteractive`) that will run a selected line in the ***generic*** Interactive Window.  Those commands always open a new Interactive Window.

Are there any buried commands that I can use to run a selection/line in a ***generic*** Interactive Window that is not tied to any file?

**Comment by joyceerhl** [comment]
What is the value of the `"jupyter.interactiveWindowMode"` setting in your settings.json? It sounds like you want it to be "single".

![image](https://user-images.githubusercontent.com/30305945/127248273-7238dd8c-f3dc-4471-88a0-51555a68dc74.png)

**Comment by clayms** [comment]
@joyceerhl  'multiple' works for me as I can create multiple Interactive Windows if I like but still runs any code from any file in the active Interactive Window.  It is marked as default, but somehow a recent update changed it.  I definitely would not have chosen 'per file.'
