### ISSUE TITLE
Support running Python as a post save hook 

### ISSUE THREAD

**Issue by janrito** [microsoft/vscode-jupyter#6854]
## Environment data

-   VS Code version:  1.59.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1070546638
-   Python Extension version (available under the Extensions sidebar): v2021.8.1046297456-dev
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: mini-forge python 3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote (I've ran this using `juptyer lab` and `jupyter server` with the same results

## Expected behaviour

I'm trying to setup a post save hook to export the notebook as a script, like the one described here: https://jupyter-server.readthedocs.io/en/latest/developers/savehooks.html#examples

The post save hook works fine when the notebook is saved from the lab web application, the hook receives 

```python

{'name': 'trial1.ipynb', 'path': 'trial1.ipynb', 'last_modified': datetime.datetime(2021, 7, 27, 22, 11, 0, 819643, tzinfo=<jupyter_server._tz.tzUTC object at 0x10291ca90>), 'created': datetime.datetime(2021, 7, 27, 22, 11, 0, 819643, tzinfo=<jupyter_server._tz.tzUTC object at 0x10291ca90>), 'content': None, 'format': None, 'mimetype': None, 'size': 276459, 'writable': True, 'type': 'notebook'}
```

 When I run it through the vscode notebook interface though, the metadata is empty:
```python
{'name': 'Untitled.ipynb', 'path': 'Untitled.ipynb', 'last_modified': datetime.datetime(2021, 7, 27, 22, 19, 56, 604318, tzinfo=<jupyter_server._tz.tzUTC object at 0x1041a3ee0>), 'created': datetime.datetime(2021, 7, 27, 22, 19, 56, 604318, tzinfo=<jupyter_server._tz.tzUTC object at 0x1041a3ee0>), 'content': None, 'format': None, 'mimetype': None, 'size': 72, 'writable': True, 'type': 'notebook'}
```

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue. the post save hooks do not work in VS Code, as the post save hooks are very specific to the Jupyter application.
Classified as an enhancement.

We'll discuss this in our triage meeting

**Comment by janrito** [comment]
great! I mean, some information is in fact being passed to the hook - so it runs, but it has unexpected behaviour.

**Comment by DonJayamanne** [comment]
Thanks for this feature request, however there haven't been enough upvotes or comments on this from others in the past year.
Hence closing this issue for now
