### ISSUE TITLE
Server is already being debugged

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-jupyter#6863]
Testing microsoft/vscode#129288

Repro steps:
1. Open a file A, set a breakpoint, and debug a cell in that file. Press the red button to stop debugging.
2. Open a file B, set a breakpoint, and debug another cell in that file. Press the red button to stop debugging. It might take setting two breakpoints in two cells and alternating between debugging the cells to get the next step to show up:
3. 🐛 The debug viewlet sometimes doesn't show properly. Press the refresh button
4. The error "Server[pid=some number] is already being debugged." shows up

**Comment by joyceerhl** [comment]
Have we ever supported debugging two files in the interactive window at once? @rchiodo

**Comment by rchiodo** [comment]
The bug doesn't sound like exactly at the same time to me. @rzhao271 it sounds like you're hitting stop in between each debug cell?

**Comment by rzhao271** [comment]
Yep, I'm hitting stop in between each debug attempt.

![Screencap demo](https://user-images.githubusercontent.com/7199958/127579913-a655a54a-6c5c-42b0-b488-20b817e9ad42.gif)

**Comment by martbern** [comment]
I get the samme issue if using an import statement. 

Would love to use the interactive debugger, let me know if I can help further!

**Comment by roblourens** [comment]
Messed around with this for awhile, can't repro it. There have been changes (and more coming)
