### ISSUE TITLE
Data viewer filter does not allow negative values

### ISSUE THREAD

**Issue by JulianCologne** [microsoft/vscode-jupyter#6869]
### Problem

Filter of the data viewer does not work when using negativ values in the filter.
Examples to enter in the filter: `<-2`, `>-13`, `=-4`.
The result is always an empty table.

### Environment data

- VS Code version: 1.58.2
- Jupyter Extension: v2021.8.1054968649

### Steps to reproduce

```python
import pandas as pd
data = {'values': [-7, 3, 8]}
df = pd.DataFrame(data)
```

Open `df` in the data viewer
Enter the filter for the `values` column: "`>-3`"

### Expected behaviour

Table gets filtered based on numbers of the `values` column that are greater than negative 3.

### Actual behaviour

Empty table.

**Comment by rchiodo** [comment]
Thanks for the bug. Should be easy to fix.

**Comment by rchiodo** [comment]
This should be fixed now.

**Comment by JulianCologne** [comment]
@rchiodo 
Cannot comfirm this.
I am on the latest releases and the given example is NOT working for me.

- VS Code Version: 1.59.1
- Jupiter Extension: v2021.8.1236758218

![DataViewer_NegativeNums_NotWorking](https://user-images.githubusercontent.com/25177421/131641586-54400552-df96-4e67-8805-2cd1afc274cb.png)

**Comment by rchiodo** [comment]
Sorry but the latest version hasn't shipped to stable yet. When we close bugs we're referring to the insiders version.

This is it working in insiders:
![image](https://user-images.githubusercontent.com/19672699/131706755-ebd1f6d0-e141-4b56-bfc6-2406f4a401b9.png)
