### ISSUE TITLE
So simple, but it takes so long?

### ISSUE THREAD

**Issue by A-Pai** [microsoft/vscode-jupyter#6873]
So simple, but it takes so long in vscode1.58?

![image](https://user-images.githubusercontent.com/5112397/127284044-03701bf1-5338-4255-8653-c8d410534dd2.png)

it is much quicker in jupyter lab， Both are first runs
![image](https://user-images.githubusercontent.com/5112397/127285216-36547850-fbe4-438f-822b-77c2cbe2a6a9.png)

**Comment by DonJayamanne** [comment]
@A-Pai Thanks for filing this issue, I'm sorry you are experiencing these delays.
Part of the delay is in starting the kernel.
In Jupyter, Python is already running & activated & when you open a notebook Jupyter starts the kernel , hence running a cell pretty fast (Python is already active & kernel is running).
Also note, launching Jupyter takes a few seconds from the command line (hence you don't notice that delay in VS Code).

Where as in VS Code, we need to start the python executable from scratch.

That being said I think we can look at further improvements.
* Please could you send the following information:
	* Output from the `Jupyter` output panel in VS Code
	* OS, Python versions
	* Are you using conda or other?

**Comment by A-Pai** [comment]
I am using anaconda，set "python.terminal.activateEnvironment": false，problem was solved

**Comment by DonJayamanne** [comment]
Thanks for getting back to us with the confirmation it has been fixed.
