### ISSUE TITLE
Migration to new editor doesn't work with `workbench.editorAssociations` set

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#6878]
Testing #6813

Maybe this is expected behavior? Filing just in case.

1. Have the following in your user settings.json
```
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter.notebook.ipynb"
    },
```
2. Open a notebook with custom editor
3. Make some changes with autosave disabled
4. Reload
5. 🐛 Dirty changes are lost, still using custom editor

**Comment by rchiodo** [comment]
It worked for me? I still had the custom editor open with the file changes there and it was dirty.

**Comment by joyceerhl** [comment]
Oh, I guess this is expected behavior https://github.com/microsoft/vscode/commit/baed4398a72bde585574b4c6cf3f241438bd3f39

**Comment by rebornix** [comment]
This is as expected, as long as users have this setting, we will not recover. Next month we will remove this setting check first.
