### ISSUE TITLE
User is never prompted to install `nbconvert`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#6879]
AFAIK we are never actually attempting to install `nbconvert` anywhere in our product code.

This line here only actually tries to install `jupyter` or `notebook`, i.e. first-run export users are inevitably broken

https://github.com/microsoft/vscode-jupyter/blob/abdb271b466f22397726e3a7963fcc87d035cb04/src/client/datascience/export/exportInterpreterFinder.ts#L41-L42

**Comment by greazer** [comment]
Dupe of #5726
