### ISSUE TITLE
Wall of notifications

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#6886]
Testing #6821

1) dev container without python
2) create untitled notebook with a python code cell
3) install python extension 

![image](https://user-images.githubusercontent.com/4674940/127410418-e5fbdd13-b0df-437c-aaa9-b1075c603960.png)

If Python is not installed, none of them really make sense.

**Comment by kieferrm** [comment]
With the welcome editor it become even more celebratory:

![image](https://user-images.githubusercontent.com/4674940/127412501-ef2edd6d-7c55-4ff3-b518-5aee16dd323e.png)

**Comment by IanMatthewHuff** [comment]
This was more of a meta issue that has been resolved by recent getting started v-team work. The welcome page has been cut out in both the scenario where you install Jupyter + Python from the marketplace (@lramos15 's work) as well as when you install Python via the kernel picker command (via me and Jupyter extension). The warning from Jupyter that you might need to restart I've also removed unless you have an active kernel running at the time of the install.

The other notifications are from the Python team. The "Python is not installed" warning I believe is removed from this scenario (@karrtikr for info) I believe that the "Do you want to use insiders" is still there though. I'm considering closing this from the Jupyter end, but if we still have the two Python messages I could transfer it as well. @karrtikr opinion on that?

**Comment by karrtikr** [comment]
Python extension no longer has any of these prompts, so feel free to close.
