### ISSUE TITLE
Loss of cell language types when uninstalling extensions

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#6888]
Testing #6821

1) have the jupyter and python extensions installed
2) create a new untitled notebook
3) add code cells with Python as the language type
-> don't save the notebook
4) uninstall python extension  (also see https://github.com/microsoft/vscode-jupyter/issues/6887)
5) reload window
-> code cells now have the language type "plain text"; we should not lose the language type

**Comment by kieferrm** [comment]
It doesn't seem you need step 4).

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on addressing this functionality at this time.
