### ISSUE TITLE
Losing selected kernel when installing python extension

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#6891]
Testing #6821

1) jupyter extension, no python extension
2) create new untiled notebook with python code cells
-> Python3 shows as selected kernel
3) run cell
4) install Python extension as requested
-> no kernel selected

![image](https://user-images.githubusercontent.com/4674940/127412716-85a96a89-c3f0-4daf-b7ab-41ef57cd63b8.png)

**Comment by DonJayamanne** [comment]
This should get fixed with the new kernel picker.

**Comment by DonJayamanne** [comment]
Closing as verification required with the new kernel picker.
