### ISSUE TITLE
Option to change kernel sends me down a rabbit hole

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#6892]
Testing #6821

1) no ipykernel installed
2) see screenshot
3) select change kernel; try to run again; same dialog
-> Not sure how change kernel can help if all potential kernels are python and all of them need ipykernel

![image](https://user-images.githubusercontent.com/4674940/127412990-5d6d3b09-271d-4b7f-b499-ff4aea960831.png)

**Comment by DonJayamanne** [comment]
I believe the issue here is with the ui flow. Will discuss in ux meeting with Miguel and ready, on how we can improve this. This particular experience was arrived at after a lot of internal discussion , looks like it can still be improved.

**Comment by DonJayamanne** [comment]
Given that 
* we now have Python Envs and Jupyter kernels separated 
* and the new Kernel Quick Picks has been around for a while now, 
* and we haven't had any issues, 
I think we can close this
