### ISSUE TITLE
Extension dependency issues when building python dev containers

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#6894]
Testing #6821

1) create a repo off https://github.com/microsoft/vscode-remote-try-python
2) clone repo locally
3) open repo in vscode
4) reopen repo in dev container

![image](https://user-images.githubusercontent.com/4674940/127414334-33030365-3447-4ac4-a137-9a7a851df179.png)

**Comment by DonJayamanne** [comment]
No longer reproducible.
