### ISSUE TITLE
Large overhead compared to browser Jupyter when running cells in Interactive

### ISSUE THREAD

**Issue by corneliusroemer** [microsoft/vscode-jupyter#6901]
Issue Type: <b>Bug/Performance</b>

# Behaviour
I have noticed that executing code through the integrated Jupyter notebook extension is several times slower than running the same code in an ordinary Jupyter notebook

There seems to be a lot of overhead when executing cells, for a reason I don't understand.

To investigate, I set up a remote Jupyter notebook server with SSH port forwarding. When I execute the same code in normal Jupyter in the browser, my local CPU remains idle. When I execute the same code through VS Code Jupyter being connected to the same remote server, my local CPU goes very busy.  Several 100% on htop are caused by vs code. This is absolutely not what I would expect. Something must be wrong.

## Steps to reproduce:

This is the code I ran this time, but I have noticed this in the past.

I'm on Ubuntu 21.04.

This is what htop looks like when I run the code through VS code:
![image](https://user-images.githubusercontent.com/25161793/127477958-c2e6c7e2-7eaf-45bb-8850-1119b690b340.png)

And this is what it looks like when I run the same code in native Jupyter:
![image](https://user-images.githubusercontent.com/25161793/127478126-b2fc7cdb-4617-44db-9f99-8d0c17b732cf.png)

```
#%%
import pymc3 as pm
import numpy as np
import matplotlib.pyplot as plt
from pymc3 import *
import arviz as az
import matplotlib
#%%
observed = [
    979363,
    919765,
    866090,
    817375,
    767528,
    728825,
    709147,
    681369,
    659343,
    627602,
]

t = np.arange(len(observed))
#%%
with pm.Model() as model:
    """Exponential decay with unknown parameters using PyMC3"""
    intercept = pm.Normal('intercept', mu=2, sd=0.3)
    lamb = pm.Exponential('lambda', lam=0.2)
    sigma = pm.Exponential('sigma', lam=0.1)
    const = pm.Uniform('const', lower=0, upper=0.6)
    pred = pm.Deterministic("pred", intercept * np.exp(-lamb * t) +const)
    likelihood = pm.Normal("likelihood", mu = pred, sigma=pred*sigma,observed=np.array(observed)/1e6)

#%%

with model:
    trace = pm.sample(draws=1000, tune=500, chains=4,cores=4,target_accept=0.95)
```

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.5
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): virt-conda
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>"Python" channel in the OUTPUT panel</summary>

<p>

```
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotificationcf'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
User belongs to experiment group 'pythonSortEnvs'
Python interpreter path: ~/miniconda3/envs/general/bin/python
Starting Pylance language server.
> ~/miniconda3/envs/general/bin/python --version

```

</p>
</details>

Extension version: 2021.8.1054968649
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.11.0-25-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|15.51GB (3.87GB free)|
|Process Argv|--unity-launch --crash-reporter-id 56d17e75-4070-4535-8292-5cdd09c86224|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by DonJayamanne** [comment]
Thanks for filling this issue and providing the screenshots and the sample code, I'll take a look.

**Comment by joyceerhl** [comment]
Yesterday @rebornix and I found that executing code cells in either webview or native notebooks are also much slower than notebooks in the browser, i.e. it's likely something with our kernel comm

**Comment by DonJayamanne** [comment]
@corneliusroemer we believe we have resolved most of the perf issues related to rendering & execution.
If this issue persists after tomorrows release please could you test & re-open this issue.
Or please feel free to create a new issue for this.
