### ISSUE TITLE
Stopping run by line causes whole cell to execute

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-jupyter#6904]
Testing https://github.com/microsoft/vscode/issues/129467

![recording (61)](https://user-images.githubusercontent.com/38270282/127486750-6f113462-9bad-4262-96b0-7987944a9aac.gif)

**Comment by roblourens** [comment]
Discussed this earlier, the stop button should do an interrupt instead of detaching and continuing

**Comment by roblourens** [comment]
Assuming that this is gone now
