### ISSUE TITLE
"No active notebook document to debug." when run by line in a different notebook

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-jupyter#6906]
Testing https://github.com/microsoft/vscode/issues/129467

I started run by line in notebook a.
Then I opened notebook b and tried to start run by line in a cell there.
It didn't start, and I got the error "No active notebook document to debug."

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/129715

**Comment by alexr00** [comment]
@roblourens the issue you mentioned as a dupe is also closed as a dupe. Was this issue accidentally closed?

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-jupyter/issues/6868 is the real open issue
