### ISSUE TITLE
Focusing out of VS Code during run by line causes stop button to change color

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-jupyter#6907]
Testing https://github.com/microsoft/vscode/issues/129467

![recording (63)](https://user-images.githubusercontent.com/38270282/127489304-044401cb-34e9-4f7b-9764-be50019eaaac.gif)

**Comment by roblourens** [comment]
@misolori this is actually another instance of that issue with codicon colors. But the second stop button is going to go away, so it's not worth fixing.
