### ISSUE TITLE
SVG Plot viewer perf fix

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#6913]
* Stop generating SVG
* Display plot viewer with PNGs
* Ensure exporting notebooks to PDF works even without SVG

**Comment by IanMatthewHuff** [comment]
One question here to examine is what do customers want from the plot viewer. We have feedback that they want it, but do they really care about zoom, pan, ect? Does just a basic image list work for 90% of users? Also are we worried enough about the perf issues here that we implement 1 - 3 quickly while we work on a bigger solution.

**Comment by IanMatthewHuff** [comment]
Yeah, that sounds like a useful side feature. We can support images or SVGs. But we could still have an opt-in feature to generate SVGs alongside plot images automatically. I don't think that any of the solutions here would preclude that, and it's a good idea.
