### ISSUE TITLE
Enhancement: Expose a global IKernelConnection to output renderers

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6918]
Right now we generate a global [WidgetManager ](https://github.com/microsoft/vscode-jupyter/blob/7c9d7e1f9d8979697e65f1f26bbb4f7be1f3eaa8/src/ipywidgets/src/manager.ts#L22) and a [proxy kernel ](https://github.com/microsoft/vscode-jupyter/blob/7c9d7e1f9d8979697e65f1f26bbb4f7be1f3eaa8/src/datascience-ui/ipywidgets/common/kernel.ts#L25) for ipywidgets to work.

For customers that don't want to write ipywidgets but still need kernel communication (one such one is Synapse) they really only need the [IKernelConnection](https://jupyterlab.readthedocs.io/en/stable/api/interfaces/services.kernel.ikernelconnection-1.html).

We should expose this as a global in our preloads for when a kernel runs. 

Additionally, we should check what Jupyter classic did to expose this before. It would be nice to follow the same API pattern (exactly if possible) with the intent to make it easier to port jupyter extensions to VS code/AZNB

**Comment by rchiodo** [comment]
An add on to this would be to expose this same IKernelConnection on the extension host side with an api like:

```
getKernel(uri: Document): Promise<IKernelConnection | undefined>
```

**Comment by duburcqa** [comment]
Is there any plan to implement this at some point ?

**Comment by rchiodo** [comment]
It's not in our near future plans (no milestone set) but it's needed by a partner team so it's likely it will get implemented at some point.

**Comment by DonJayamanne** [comment]
@duburcqa
What's your user case for this feature?

**Comment by duburcqa** [comment]
@DonJayamanne I'm developing a robotic simulator using a webgl viewer based on treejs. In ipython i can instantiate a iframe, that is opening a connection with the kernel in javascript so that the viewer and the main python thread can communicate back and forth. Currently, I can create the iframe in VSCode and used python to communication with the viewer, but not the other way around. I really need it to handle basic events such as waiting for the meshes to load before capturing the frame programmatically.

**Comment by DonJayamanne** [comment]
@duburcqa We've created some API that exposes the Kernels and their API to external extensions.
This is still a work in progress and we don't have any samples for for communicating with the kernel from webviews and using widgets (it will require quite a bit of work).
Please feel free to have a look at the API exposed by the extension.

**Comment by duburcqa** [comment]
@DonJayamanne Interesting ! Is there any documentation somewhere ?  I'm relying on one javascript method in particular:
```
window.parent.Jupyter.notebook.kernel.comm_manager.new_comm
```

**Comment by DonJayamanne** [comment]
> window.parent.Jupyter.notebook.kernel.comm_manager.new_comm

We do not expose this anywhere. Currently there are no plans to expose this, as this could pose a security risk (allowing any extension to access the kernel and execute code - an issue when dealing with remote jupyter kernels)

**Comment by duburcqa** [comment]
Ok i see. I was expecting this. No problem. Thank you anyway !

**Comment by DonJayamanne** [comment]
I'll see what can be done, I think we can use the same model we have today (exposing 3rd party API) to expose these kernels in output renderers.

**Comment by DonJayamanne** [comment]
@duburcqa Do you have a VS Code extension that ships the code running in the renderers?

**Comment by duburcqa** [comment]
@DonJayamanne No, it is a python package to install via pip:
```
pip install jiminy_py
```

Then, a basic jupyter noteboox example can be found [here](https://github.com/duburcqa/jiminy/blob/master/examples/python/tutorial.ipynb). Running it will embedded the renderer in a cell using a HTML iframe, and the latter while try to open a connection with the kernel through javascript in order to send simple information such as acknowledgements. [Here](https://github.com/duburcqa/jiminy/blob/master/python/jiminy_py/src/jiminy_py/viewer/meshcat/index.html) is the embedded HTML code I'm referring to. Note that this approach is not working for jupyterlab for a similar security concern. I'm open to developing a proper extension module but I have zero knowledge on this and I don't know where to start.

Thank you for paying attention to my problem!

**Comment by duburcqa** [comment]
After digging a little bit in other issues, I'm facing the issue than here: https://github.com/microsoft/vscode-jupyter/issues/1477

**Comment by DonJayamanne** [comment]
> I'm facing the issue than here: #1477

Not following you, is iminy_py also opening up sockets and communicating with the kernel via its own sockets?
It not, then its not the same as #1477

**Comment by duburcqa** [comment]
It is partially the same. I'm not communicating with the kernel via my own sockets, but they are relying on `IPython.notebook.kernel.comm_manager` just like me.

**Comment by DonJayamanne** [comment]
From what I can tell, Jupyter lab renderers cannot access the kernel unless the renderers are Jupyter Lab specific renderers.
Such as the following https://github.com/jupyterlab/jupyterlab/tree/master/packages/vdom

I.e. the widget gets the Kernel as a ctor argument.

**Comment by duburcqa** [comment]
hum. I tried to look a bit but my knowledge in javascript and jupyter is too limited to build something similar.

**Comment by duburcqa** [comment]
I want it to be compatible with cloud notebook providers such as colab, kaggle or deepnote. So developping a widget is not an option.

**Comment by DonJayamanne** [comment]
> So developping a widget is not an option

We try to support compatibility with Jupyter lab and classic Jupyter notebook. 
From what you're saying you aren't willing to create a Jupyter notebook/lab widget.
I'd recommend you consider that as it's already an industry standard, and as mentioned earlier, exposing kennels another way could lose security issues, basically any J's code from other extensions could execute code on local and remote machines.



Then again theres the whole security issue.

**Comment by duburcqa** [comment]
I see your point. I will think about it. Yet, for you to know, recently I managed to get it to work in VSCose and Jupyter by connecting to the kernel websocket manually. So the current implementation of VSCose notebooks is not preventing this at all.

**Comment by DonJayamanne** [comment]
Closing this issue as we expose an API for users to access the kernel connection. If users which to access the kernel, they could, send messages back to the extension host from the webview .

**Comment by Conchylicultor** [comment]
@duburcqa I'm having the same issue. Do you have an example of how to connect to the kernel without creating a custom widget ?

My use-case is to run `IPython.notebook.kernel.execute` for bidirectional Python communication.
