### ISSUE TITLE
cannot use itkwidgets to show images

### ISSUE THREAD

**Issue by ashapeng** [microsoft/vscode-jupyter#6921]
## Environment data

-   VS Code version: 1.58.2
-   Jupyter Extension version (available under the Extensions sidebar): ms-toolsai.jupyter
-   Python Extension version (available under the Extensions sidebar): ms-python.python
-   OS (Windows | Mac | Linux distro) and version: windows 10 64X
-   Python and/or Anaconda version: 3.9.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote |local

## Expected behaviour
try to visualize images with view(), but nothing comes out, and without any error

**Comment by DonJayamanne** [comment]
I'm very sorry I never got to this issue, some how slipped through the cracks. 
Please could you let me know if you are still running into this.

**Comment by greazer** [comment]
Issues labeled with "Info needed" are closed if we do not receive more information from the issue author in 2 weeks. If you are the issue author and you still are running into this problem, please reactivate with additional information.
