### ISSUE TITLE
Julia error messages not displayed in output because our renderer only takes Stack Trace into account

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#6929]
Originally filed here https://github.com/julia-vscode/julia-vscode/issues/2326

We might want to re-visit this renderer, it has the potential to break in a number of other situations.

I think we might want to consider the renderer architecture or have a custom error mime type so that we can render this in a special way for Interactive window (e.g. instead of using VSCodes error type, use a custom mime, this way it will work in Notebooks for Python, Julia, .NET, etc)

Right now its not useful for Julia notebooks as error message is not displayed.

**Comment by DonJayamanne** [comment]
@rebornix /cc

**Comment by rebornix** [comment]
> E.g thers no handling of ASCII in the custom renderer but VS Codes built in renderer has it.

we used `import ansiToHtml from 'ansi-to-html';` to convert ASCII, which is how we did in webview impl interactive window. Do we know what we are missing. cc @rchiodo @joyceerhl

**Comment by rchiodo** [comment]
@DonJayamanne can you show an example of what's going wrong? I'm not 100% sure I understand the problem.

**Comment by DonJayamanne** [comment]
> ng wrong? I'm not 100% sure I understand the problem.

We're not displayin the error message anymore.
Errors have error message, name & stack.
With our custom renderer we only display the stack trace & not the error message & name.

**Comment by DonJayamanne** [comment]
>  convert ASCII, which is how we did in webview impl int

Sorry, I missed that bit. Updated the message

**Comment by rchiodo** [comment]
So would the fix be to display the error message, name, and stack?

I agree it would be ideal if this only happened in the interactive window, but seems easier to just add the two extra items.

**Comment by rebornix** [comment]
> We're not displayin the error message anymore.
Errors have error message, name & stack.
With our custom renderer we only display the stack trace & not the error message & name.


Thanks for the details. We should do the same as the core, it's an oversight. PR: https://github.com/microsoft/vscode-jupyter/pull/6931

**Comment by DonJayamanne** [comment]
Related to https://github.com/microsoft/vscode/issues/125876
