### ISSUE TITLE
IPyKernel not installed into interpreter Python 3.8.5 32-bit

### ISSUE THREAD

**Issue by tylerol74** [microsoft/vscode-jupyter#693]
Issue Type: <b>Bug</b>

1.Open VS Code
2. Start Jupyter Notebook
3. VScode will attempt to connect to Ipython Kernels
4. Then prompt to download "Data Science library ipykernel is not installed. Install?" appears. I selected Yes
5. VS Code is unable to download ipykernel. 

Extension version: 2020.8.106424
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7410 APU with AMD Radeon R5 Graphics     (4 x 2196)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.91GB (2.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Meesaan** [comment]
This happened to me when I forgot to activate my virtual environment in anaconda. 
Hopes this helps.

**Comment by ArthurZ** [comment]
What solved my issue using an upgraded packaged in Anaconda is:
`conda uninstall pyzmq` then
`conda install pyzmq`

**Comment by uvsq22002522** [comment]
hello i have a similar problem... when i wanna run my code i have this : IPyKernel not installed into interpreter Python 3.8.5 64-bit ('base': conda):/Users/Icy/opt/miniconda3/bin/python
and also this : Could not install ipykernel. If pip is not available, please use the package manager of your choice to manually install this library into your Python environment.
what can i do about it ? thanl u

**Comment by reflexiveprophecy** [comment]
I am using python 3.7.4. Had the same error message. Fixed the issue with the following commands. It seems like it was the new version of pyzmq that caused the problem. The jupyter-client package didn't cause the problem on my end. 

`pip uninstall pyzmq
pip install pyzmq==19.0.2
`

**Comment by Sztuk** [comment]
For python 3.6.7 32-bit the reason is pyzmq also. Reinstall it and choose version 19.0.2 via pip (reflexiveprophecy solution)

**Comment by rajpatel1997** [comment]
> 
> 
> Issue Type: Bug
> 
> 1.Open VS Code
> 2. Start Jupyter Notebook
> 3. VScode will attempt to connect to Ipython Kernels
> 4. Then prompt to download "Data Science library ipykernel is not installed. Install?" appears. I selected Yes
> 5. VS Code is unable to download ipykernel.
> 
> Extension version: 2020.8.106424
> VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
> OS version: Windows_NT x64 10.0.19041
> System Info

Running VSCode as administrator and when you see to install click on that to install. It worked for me!

**Comment by roboroaster** [comment]
i have a problem that might be similar .
i have already  been working on jupyter notebooks on vscode for a long time and then suddenly a notification pops up that ipykernel is not installed even when it meets the requirements when i try to install it. i tried to force reinstall it, also reinstall all the plugins in vsc and still nothing got better what should I do?
![image](https://user-images.githubusercontent.com/75543479/116896969-6105d500-ac52-11eb-85d9-04ccfc6218ef.png)
