### ISSUE TITLE
Cannot set property 'PYTHONPATH' of undefined

### ISSUE THREAD

**Issue by isbada** [microsoft/vscode-jupyter#6934]
## Environment data

版本: 1.58.2
提交: c3f126316369cd610563c75b1b1725e0679adfb3
日期: 2021-07-14T22:09:06.581Z (2 周前)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 18.7.0

## Expected behaviour

![image](https://user-images.githubusercontent.com/23022062/127760106-4ad7a9d9-98e2-4bce-aa74-f5e28b95dd50.png)

click this, debugger function should started normally

## Actual behaviour

![image](https://user-images.githubusercontent.com/23022062/127760042-b8154b2a-90bb-4b06-b845-c442a9f368d9.png)

![image](https://user-images.githubusercontent.com/23022062/127760072-3cbc879a-6d2b-41a2-9870-b06bb5a6c2ed.png)

## Possible Reason.

![image](https://user-images.githubusercontent.com/23022062/127760181-49ee46f7-4ba6-4aa0-a0ed-33db5c36eb3c.png)

**Comment by DavidKutu** [comment]
Thanks for the issue @isbada. Could you please run this:
```
import sys;
print(sys.path)
```
on the interactive window and share the result with me?

**Comment by DavidKutu** [comment]
Also, @isbada, could you share the logs from the `output` panel? Select `Jupyter` on the dropdown and share that.

Thanks!

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
