### ISSUE TITLE
Runing a raw cell breaks execution of other cells

### ISSUE THREAD

**Issue by per11235813** [microsoft/vscode-jupyter#6954]
Issue Type: <b>Bug</b>

Make a blank notebook add three cells
1. A python cell, eg `a=1`
2. A cell with some text, change the type to "raw"
3. Another python cell eg `b=2`

Now select "Run all". Cell 1 is run, but after trying to run cell 2 of type "raw" all cell execution stalls. 

If you now try to run a code cell, it gets the pending state (left corner, clock with an arrow around)

Recovery by restarting the kernel. 

Same behavior is observed in the stable release.

Extension version: 2021.8.1081660962
VS Code version: Code - Insiders 1.59.0-insider (ba0df885e9d6b0f0ccf2cc714c3fa31423572205, 2021-07-31T00:41:55.692Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (13.75GB free)|
|Process Argv|--crash-reporter-id 9cb47b31-118f-4a63-91f9-b13170eb2d06|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
dockerwalkthru:30344901

```

</details>

**Comment by greazer** [comment]
Thanks for the report, we have fixed this.
