### ISSUE TITLE
Extension issue: Jupyter on Visual Studio Code Unresponsive (Run Very Slow)

### ISSUE THREAD

**Issue by imaginali** [microsoft/vscode-jupyter#6961]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.8.1054968649`
- OS Version: `Windows_NT x64 6.3.9600`
- VS Code version: `1.58.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DonJayamanne** [comment]
Thanks for filing this issue. Unfortuately we cannot do much without the CPU profile informaiton.
Looks liie you missed the message about requiring to paste the data `e have written the needed data into your clipboard. Please paste`

Please feel free to re-open this with the cpu profile or create a new issue.
