### ISSUE TITLE
Autocomplete / Autocompletion lacks parity with a standard Jupyter server

### ISSUE THREAD

**Issue by astrowonk** [microsoft/vscode-jupyter#6979]
## Environment data

Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:11:51.081Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin arm64 20.6.0

Jupyter Version: 2021.8.1195043623
Python Ext Version: 2021.8.1105858891
Name: Pylance Version: 2021.8.0

While I see a handful of issues on autocomplete (for example I commented on #1419), I'm not sure any capture the general lack of parity with a standard jupyter server in a browser.

A standard jupyter server can autocomplete not just available methods and packages inside a module but __strings__ both for subscriptable objects like a dictionary or a custom object. Notebooks on 1.59.0 lack much of this autocomplete ability.

Scenarios where autocomplete is missing:

- Lists of files in the current directory. e.g. `pd.read_csv`
 ![Screen Shot 2021-08-05 at 4 58 22 PM](https://user-images.githubusercontent.com/13702392/128420578-ba3509d0-3ca7-4bf5-b6c8-991a869e23d8.png)
- Dictionaries and other subscriptables
![Screen Shot 2021-08-05 at 5 01 53 PM](https://user-images.githubusercontent.com/13702392/128420733-2c79f1b1-06c4-45a6-80ef-609ac8d15e0f.png)

Until hitting tab produces the same autocomplete behavior as a standard juptyer notebook /server, it's really hard to see myself using it instead of the browser. I rely on autocomplete constantly, to the point I have created custom subscriptable classes that set `_ipython_key_completions` just so I can use autocomplete more.

Bringing full autocomplete parity to notebooks in VS Code is a vital feature I hope can come soon!

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, we'll discuss this issue in our next triage meeting.

**Comment by DonJayamanne** [comment]
**Notes for Internal use:**  
We disabled Jedi auto completion for Native Notebooks, see here https://github.com/microsoft/vscode-jupyter/issues/892 (associated PR https://github.com/microsoft/vscode-python/pull/13294)

**Comment by DonJayamanne** [comment]
@astrowonk 
Currently this is working for me.
Please could you provide a screenshot of this not working at your end.
Also please could you fill in the issue template (we need the information requested to be be able to help you, e.g. VS Code, Extension version & logs)

**Comment by astrowonk** [comment]
Updated the initial post with as many version numbers as I could find.

Pandas finds some random . directories but not any files.
<img width="845" alt="Screen Shot 2021-08-09 at 9 08 20 PM" src="https://user-images.githubusercontent.com/13702392/128793157-652312a0-c0db-4348-8192-e70d50a670cc.png">

dict behavior sortof worked briefly (it showed the keys after I typed the first [ but I can't seem to reproduce that initial success. It never worked on tab. I tried to make a short video:


https://user-images.githubusercontent.com/13702392/128793750-a7f9f2b3-1971-4dc8-87c0-2025d1c07883.mov

**Comment by DonJayamanne** [comment]
Thanks for the screen recording & details, I was able to repro with those steps.

> also note the docstring type tooltip floatover gets in the way of the autocomplete suggestions, even on your screenshot.)


Please could you file a bug against this. I'd like to keep this issue focused on the auto complete from jupyter.

**Comment by DonJayamanne** [comment]
Test:
* The characters ' or " should display the completion items
* The items should be sorted correctly.
E.g. with the following code:
```Python
# cell 1
dict = {"Apple": 1, "Banana": 2}
``
``python
# cell 2
dict[' <- At this point we should get completions & Apple should be on the top (at least top 5, previously it was a few 100 items down).
```
