### ISSUE TITLE
Running cells in quick succession doesn't behave as expected

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#6982]
Version: 1.60.0-insider (user setup)
Commit: a4eb4d688477fb9f2176bb2ed932b0b1726caed3
Date: 2021-08-05T21:34:13.867Z (2 hrs ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.22000

1. Take a script that looks like this:

```python
#%%
a = 1

#%%
b = a + 1

#%%
a = a + 1
```
2. Click Run Below 3 times in quick succession
3. Inspect the value of a. 

Actual
![image](https://user-images.githubusercontent.com/11685408/128437023-9a9f18b0-bbe4-416e-887b-5be4318eca95.png)

Expected
'a' should be 2, right?

The reason this is the case can be seen in the execution history of the Interactive window:
![image](https://user-images.githubusercontent.com/11685408/128437141-8c018823-a257-421e-b303-0528667510dc.png)

I would have expected the history to show 3 consecutive copies of the 3 cells in the script running. Rather than each cell being run 3 times in a row.

This may seem contrived, but I ran into it by accident and I suspect that real situations could arise where things get goofed up and the user doesn't realize it.

**Comment by DonJayamanne** [comment]
Moving to triage, as i think this is a `important` and `golden` scenario issue. (basically pretty serious bug)

**Comment by greazer** [comment]
Try to repro. May be fixed

**Comment by rchiodo** [comment]
Still repros but only on first open. If the window is already open, then it behaves as expected.

**Comment by rchiodo** [comment]
Also you have to click the link 3 times. If you click it once it works fine.

**Comment by greazer** [comment]
I can repro all the time.

**Comment by IanMatthewHuff** [comment]
Verification is pretty easy here. Just create a .py file with a few cell markers defined. In each cell just do a small timing loop to burn a second or two of time. Then trigger something like Run Below from the top code lens twice. In the old code you would get Cell A, Cell A, Cell B, Cell B, Cell C, Cell C. Now we get each command handled in order, so Cell A, Cell B, Cell C, Cell A, Cell B, Cell C.
