### ISSUE TITLE
Kernel died with exit code 1.

### ISSUE THREAD

**Issue by roboserg** [microsoft/vscode-jupyter#6986]
Running cells within VSCode gives me an error:

`C:\Users\shebo\AppData\Roaming\Python\Python39\site-packages\traitlets\traitlets.py:2196: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use 'hmac-sha256' instead of '"hmac-sha256"' – or use CUnicode. warn( C:\Users\shebo\AppData\Roaming\Python\Python39\site-packages\traitlets\traitlets.py:2151: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '20e6f2d8-5191-45d6-8208-db97e47902eb' instead of 'b"20e6f2d8-5191-45d6-8208-db97e47902eb"'. warn( Traceback (most recent call last): File "C:\Users\shebo\miniconda3\envs\torch\lib\runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Users\shebo\miniconda3\envs\torch\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\Users\shebo\AppData\Roaming\Python\Python39\site-packages\ipykernel_launcher.py", line 16, in <module> app.launch_new_instance() F...`

## Environment data

-   VS Code version: 1.59.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1195043623
-   Python Extension version (available under the Extensions sidebar): v2021.8.1102490946
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Ver 21H1
-   Python and/or Anaconda version: Python 3.9.6 + latest miniconda
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

**Comment by greazer** [comment]
Thanks for the feedback! We need more information though. Please copy the output of the 'Jupyter' output tab into this issue.

**Comment by roboserg** [comment]
Sorry, can't reproduce the issue anymore. Everything working fine now.
