### ISSUE TITLE
Intellisense doesn't support types and var provided from a call to "%run <notebook.ipynb>" (was makes mistakes every 2-3 lines of my code in Jupyter Notebook

### ISSUE THREAD

**Issue by sindzicat** [microsoft/vscode-jupyter#6987]
## Environment data

-   VS Code version: 1.59.0 (system setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1195043623
-   Python Extension version (available under the Extensions sidebar): v2021.8.1102490946
-   Pylance Extension version (available under the Extensions sidebar): v2021.8.0
-   OS (Windows | Mac | Linux distro) and version: Windows 7
-   Python and/or Anaconda version: Python 3.8.9 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Correct code is detected as corrected one by Pylance

## Actual behaviour

Let's look this cell in Notebook:

![image](https://user-images.githubusercontent.com/33900895/128481058-2df77663-680b-44fd-81e0-e5c576195f8d.png)

Code in this cell is correct. I'm sure about this, because I run it, and it worked as expected. But Pylance disagree with me:

![image](https://user-images.githubusercontent.com/33900895/128481178-d05c5061-8535-464a-9dd6-8dd474c06f0e.png)

`"PrettyTable" is not defined`, but it's defined...

![image](https://user-images.githubusercontent.com/33900895/128481274-87abb4b1-54a0-4576-b7f9-ee5ec36ae6ed.png)

`"table" is not defined`, but it's defined in current code cell...

![image](https://user-images.githubusercontent.com/33900895/128481369-d6ec0a5f-3c02-4eff-88b9-5f518584415a.png)

`"apdtable" is not defined`, but I even didn't typed such word. Anyway, there is no such word in my code.

![image](https://user-images.githubusercontent.com/33900895/128481516-3a4b02f0-1006-496b-aba5-9392ca1c5bcd.png)

`"dot_align" is not defined`, but it's defined...

And this is only ONE code cell! It's very annoying and makes impossible and very hard to works with notebooks.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by sindzicat** [comment]
I need to add, that I use
```
%run mynotebook.ipynb
```
in the first code cell. So, `PrettyTable`, `numpy as np` and some other variables are defined in extra notebook.

**Comment by sindzicat** [comment]
I &laquo;fixed&raquo; my problem, using this comment at the top of notebook:
```
#type: ignore
```

It seems for me, that using `%run notebook.ipynb` is the main source of Pylance problems. I splitted my big notebook into several small parts and load previous part via `%run`. So, Python knows about variables from other Notebooks, but Pylance not.

**Comment by StevenLi-DS** [comment]
I'm having this issue: 
![CS-9PcmOrQE](https://user-images.githubusercontent.com/33796896/201810979-d97cd0e6-bcc9-477a-a52f-bbe8dcda8b58.png)
Does it relate to this issue as well?

**Comment by DonJayamanne** [comment]
@StevenLi-DS @sindzicat 
This should now work with the latest release bits.

Please could you install the latest version of VS Code 1.74  and the latest versions of Jupyter, Python and Pylance extensions and let me know whether this has been resoved.

**Comment by StevenLi-DS** [comment]
@DonJayamanne Indeed, the problem is solved with the latest versions, thanks!

**Comment by sindzicat** [comment]
@DonJayamanne, yes it's fixed! Many thanks! 👍

**Comment by rogerlga** [comment]
I still can reproduce the error reported by @StevenLi-DS https://github.com/microsoft/vscode-jupyter/issues/6987#issuecomment-1314671688:

![image](https://user-images.githubusercontent.com/9919528/222928990-ab93c4a7-c7f5-4ca2-9a24-5033ed675fd7.png)

Imported modules are not recognized as well:

![image](https://user-images.githubusercontent.com/9919528/222929109-f5c9ab24-e891-49b4-bc41-98e639253c14.png)

All my related extensions are updated at the time I'm writing this:

![image](https://user-images.githubusercontent.com/9919528/222929158-d3383a7b-825f-4070-923f-9e3efe3da661.png)

Please check if you can also reproduce it to reopen this issue or if it's just with me.

**Comment by StevenLi-DS** [comment]
@rogerlga Might be a Pylance issue here https://github.com/microsoft/pylance-release/issues/3941
