### ISSUE TITLE
in native interactive window, need evaluation indicator for collapsed input cell

### ISSUE THREAD

**Issue by ltmsyvag** [microsoft/vscode-jupyter#6990]
Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 19.6.0

I used the previous (python) interactive window a lot, and I am embracing the change to native interactive window. 

I notice one thing that is missing compared to before: an evaluation indicator during evaluation. Previously, during time consuming evaluation, in interactive window there was a green spinning asterisk (in VS dark theme) to let you know the evaluation is on-going. In the new native interactive window, the evaluation indicator is now a moving blue border (in VS dark theme) at the top of an input cell. However afaik this blue border is only visible when input cell is not collapsed. But if one evaluates large chunks of code from from a .py file, the input cell in interactive window will always be collapsed. If you routinely run large chunks of no-output code, this would often leave you wondering whether the evaluation is finished or not, unless you move your mouse to click-expand the current input cell in native interactive window. If you don't do the click-expand, it seems you have no visual way to tell if a collapsed input cell has finished evaluation in native interactive window.

If the VS code team can make the moving blue border visible even when the input cell is collapsed, that would be very welcome, and this would be consistent with the always-visible spinning green asterisk in previous interactive window.

**Comment by krishnaraj-sr** [comment]
Is there a temporary workaround for this issue?

**Comment by janosh** [comment]
Thanks for pushing ahead with the new VS Code native notebook API. Excited to see where this goes. A pending calculation indicator is _urgently_ needed though, especially for people like me dealing with lots of long running cells.

**Comment by joyceerhl** [comment]
We are working on adding a progress indicator for the upcoming iteration. In the meantime you can opt back into the old experience by setting `"jupyter.enableNativeInteractiveWindow": false` in your user-level settings.json.

**Comment by greazer** [comment]
This has been addressed in the last release of VS Code Insiders and will appear in the August release of VS Code Stable. Further improvements as to how cell execution status is displayed are coming...
