### ISSUE TITLE
Variables explorer not updating when running the interactive session from the editor

### ISSUE THREAD

**Issue by kylebradbury** [microsoft/vscode-jupyter#6993]
## Environment data

-   VS Code version: 1.59.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1195043623
-   Python Extension version (available under the Extensions sidebar): v2021.8.1105858891
-   OS (Windows | Mac | Linux distro) and version: Mac Big Sur 11.4 (20F71) (M1 processor, 2020)
-   Python and/or Anaconda version: Python 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

When a code segment is run from the editor in the interactive window, the variable list in the variables explorer would reflect those changes that occur in the interactive window.

## Actual behaviour

The variable list in variables explorer does not update after running code in the interactive window from the editor. It updates after clicking on the interactive window; the variable values may reflect previous states of those variables in the meantime.

## Steps to reproduce:

Demo reproducing the issue:

![vscode-jupyter-issue](https://user-images.githubusercontent.com/4689093/128585051-c7f7f649-6af4-4ec3-b1e8-7da10ecaf1f5.gif)

## Logs

No output

**Comment by jon9885** [comment]
I Have the same problem.
The temporary fix is to return to the old interface using "jupyter.enableNativeInteractiveWindow": false

**Comment by joyceerhl** [comment]
Thanks for filing a bug and sorry for the trouble. This is an oversight and is due to the fact that our variable explorer is populated based on an active notebook editor (and the interactive window contains an embedded notebook editor). The desired behavior is for the variable explorer for the interactive window to be populated based on a visible but not active interactive window, and to remain populated when focus is placed in a #%% file.

**Comment by joyceerhl** [comment]
On restart the variable explorer doesn't get cleared for the interactive window either; it should.

**Comment by thor4** [comment]
> I Have the same problem.
> The temporary fix is to return to the old interface using "jupyter.enableNativeInteractiveWindow": false

I've tried checking and unchecking that box. Neither action results in correct variable explorer behavior. I have to click into the interactive window to trigger an update.

Separately, there are times when the variable explorer disappears entirely for me. I have to close the interactive window and re-open it, starting over, for it to function again. I have not been able to pinpoint the steps to reproduce this error, but if I do, I will post them here.

Finally, I really dislike this new layout for the variable explorer. Are we stuck with having it tied to the bottom panel with "problems, output, etc.."? Before, it fit neatly in the top of the interactive window layout (see attached screenshot).
![prev_interactive_window_layout](https://user-images.githubusercontent.com/6412103/128940223-10258c2c-7d1a-4248-b835-ef289b50bdd6.png)

**Comment by joyceerhl** [comment]
@thor4 If you reload VS Code after toggling that setting to 'false', you should get back the old interactive window behavior. That will be a temporary fix.

The current plan is to have the variable explorer in the bottom panel, and this is also how the variable explorer for native notebooks works. An alternative would be have VS Code provide a grid view and render that as part of the interactive composite editor. Please consider filing a feature request on https://github.com/microsoft/vscode (fyi @rebornix)

**Comment by mosierbryon** [comment]
Can I just say that I love the "old" style and desperately want it to always be an option.

**Comment by thor4** [comment]
Thanks, I will look at the feature request option when I get some time. If someone is able to do it before me, please link here so I and others can provide support. Otherwise I will link here when I am able to do it.

In the meantime, I was able to reproduce the issue of all variables disappearing completely. If you right click on the bottom panel and move it to the right of the screen, all variables disappear, including the table styling and everything. Trying to move it back to the bottom of the screen does nothing. You have to completely close out of the interactive window and restart it. Please let me know if you need further information.

**Comment by joyceerhl** [comment]
> I was able to reproduce the issue of all variables disappearing completely

@thor4 Thanks for the clear repro steps, looks like it actually impacts regular Jupyter notebooks too, I've created #7065 to track that bug.

**Comment by joyceerhl** [comment]
@mosierbryon Thanks for the feedback--it would help us to understand why the old style is better. Are you referring to the old interactive window all up, or the old variable explorer (embedded in the interactive window) specifically? What about it do you prefer?

**Comment by JoschD** [comment]
Related: On my machine the whole new interactive window and variable explorer is very buggy. I also have to click on the interactive window (especially into the "type code here" box) and even then the variables often don't update. And I have to click on the interactive window first, before opening the variables in the `data viewer`, as soon as I clicked on my code tab in between (without running anything between looking at different variables).

And I can't seem to get the old style back in my WSL VSCode. The setting you describe above isn't there at all (I guess the Jupyter extension is only installed in the local VSCode?). And setting it in the local VSCode has no effect on the WSL. It's always the view with the variables at the bottom.

**Comment by mosierbryon** [comment]
> @mosierbryon Thanks for the feedback--it would help us to understand why the old style is better. Are you referring to the old interactive window all up, or the old variable explorer (embedded in the interactive window) specifically? What about it do you prefer?

Hi @joyceerhl, I'm referring to the variable explorer embedded in the interactive window.  For me it's the must efficient use of space.  The script has the left 2/3 of the screen and the interactive window has the other 1/3.

**Comment by alandema** [comment]
Also, opening a big variable in the Data Viewer is super slow. I work a lot with big np arrays (~100000:~10:~100), and I can't use the Variable Explorer from VSCode properly because some don't even open and others takes forever.

**Comment by joyceerhl** [comment]
@JoschD You will also need to reload VS Code after that setting update. Additionally that setting is a user-level setting, so please ensure that you are adding it to your user settings and not your machine settings. Please let us know if that doesn't work!
