### ISSUE TITLE
%matplotlib widget  does not work  in notebok

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/vscode-jupyter#6994]
## Environment data
version: 1.59.0 (user setup)
commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
date: 2021-08-04T23:13:31.568Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT ia32 10.0.18363
## Expected behaviour
%matplotlib widget  work in notebook

## Actual behaviour
nothing to output
![image](https://user-images.githubusercontent.com/33288114/128590131-a00e7765-9774-4fe4-82be-0fb8ff06ab06.png)

## Steps to reproduce:
%matplotlib widget
import matplotlib.pyplot as plt
plt.plot([1,2,3])
plt.show()

**Comment by jackthepanisher** [comment]
This works for me in VS Code 1.59.0 as expected. Do you have the Python package _ipympl_ installed? Maybe you need to update some packages including _ipympl_. Also, does `%matplotlib inline` work?

**Comment by CatNofishing** [comment]
Okay ，after update it ，it works， thanks
