### ISSUE TITLE
If the type of variable is 'POSIXct' 'POSIXt', it would not be shown in jupyter 

### ISSUE THREAD

**Issue by hackeye** [microsoft/vscode-jupyter#7011]
# In microsoft/vscode-jupyter
![image](https://user-images.githubusercontent.com/25793057/128697903-0aa966bc-64ef-459c-a058-d19e8f242884.png)

# In jupyter lab
![image](https://user-images.githubusercontent.com/25793057/128698062-3871b2c6-9075-4276-bd9c-b0629e3819ab.png)

# code
```
one_pm <- ymd_hms(
    "2016-03-12 13:00:00",
    tz = "America/New_York"
)
one_pm
class(one_pm)
```

**Comment by joyceerhl** [comment]
@hackeye, I assume this is an R notebook with an R kernel. Would you mind confirming that? Could you also please run the 'Developer: Toggle Developer Tools' command from the command palette? The developer log may have more information. Thank you and apologies for the inconvenience!

**Comment by hackeye** [comment]
@joyceerhl 
Thank you very much.
Now it is working fine, I do not know the reasons.
