### ISSUE TITLE
Link for new notebook editor not working.

### ISSUE THREAD

**Issue by PedroMVM** [microsoft/vscode-jupyter#7012]
Link found in `DataScience.customEditorBanner` option (https://aka.ms/vscodeNotebookEditorBanner) is not working, it redirects to Microsoft page.

## Environment data

-   VS Code version: 1.59.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1195043623
-   Python Extension version (available under the Extensions sidebar): v2021.8.1105858891
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Python 3.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

It should open a page which explains what users should do after this new version.

## Actual behaviour

Open Microsoft page

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Just open VSCode and then a .ipynb file after the new update.

## Logs

No log available.

**Comment by rchiodo** [comment]
Whoops, it should redirect to here now:
https://code.visualstudio.com/blogs/2021/08/05/notebooks
