### ISSUE TITLE
Jupyter won't select specified virtual environment on first start

### ISSUE THREAD

**Issue by darim1** [microsoft/vscode-jupyter#7013]
I have a workspace containing several folders with projects. One contains a subfolder ".venv" with an environment for that specific project. I employ scripts, that I'd like to run interactively with that particular environment:

**Folder structure:**

/workspace
/workspace/project1/...
/workspace/project2/.venv/Scripts/python.exe
/workspace/project2/.vscode/settings.json
/workspace/project2/blabla/my_script.py

But whenever I open the interactive console, it will start with some system python. Then I have to manually select the proper environment. This is annoying!

This is the content of **settings.json**:

{
    "python.pythonPath": ".venv\\Scripts\\python.exe"
}

In addition I observed, that the same setup has worked before my recent update to vscode v1.59. 

Can someone please give me advice about how to setup my workspace properly or how to configure vscode?

Thanks,
Daniel

**Comment by joyceerhl** [comment]
@darim1  `"python.pythonPath"` has been deprecated in favor of `"python.defaultInterpreterPath"`. Could you please try the following:

1. Configure your settings like so and try again
```json
{
"python.defaultInterpreterPath": ".venv\Scripts\python.exe"
}
```
2. If that doesn't fix the problem, please try executing the Python: Select Interpreter command from the command palette. The interactive window should always use the active Python interpreter (you can always check this in the bottom left status bar)
3. Roll back to an earlier version of the Jupyter extension or Python extension and let us know which version this stops being a problem in

**Comment by darim1** [comment]
@joyceerhl, thanks for the quick reply (and apologies for the messy description)!

If changed the variable name to "defaultInterpreterPath", but it gets greyed out. It also does not improve the situation, therefore I think it's not supported, yet. 

My current setup is:

Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042

Jupyter: v2021.8.1195043623

-----
I also rolled back to the previous version: v2021.8.1081660962

This is the same situation: The new parameter is not supported.

-----
Then I downgraded to some 2 month old version, but this time the extension does not start. In the light of the many combinations regarding vscode versions and extension builds, it is pretty hard to track this down by try-and-error.

Is there no straightforward way in order to check configuration/ behavior?

Thanks,
Daniel

**Comment by joyceerhl** [comment]
@darim1 I am unable to reproduce this issue in a single root workspace. I recreated the setup you described in your issue and was able to set the venv as my active Python interpreter, as shown in the bottom left of this screenshot:

![image](https://user-images.githubusercontent.com/30305945/128897011-97ed1a8d-f6a0-4d89-abc0-638f9e681f7a.png)


Here is the content of my .code-workspace file:

```
{
	"folders": [
		{
			"path": "project1",
		},
		{
			"path": "project2",
		}
	],
	"settings": {
		"python.defaultInterpreterPath": "C:\\path\\to\\workspace\\project2\\tutorial-env\\Scripts\\python.exe"
	}
}
```

Would you mind sharing how you have configured your workspace?

As for the `defaultInterpreterPath` setting not being picked up, are you opted out of Python experiments in your user settings.json (`"python.experiments.optOutFrom": ["All"]`, `"python.experiments.enabled": false`, `"python.experiments.optOutFrom": ["pythonDeprecatePythonPath"] ` or similar)? The Python extension's support for `python.defaultInterpreterPath` is being rolled out as an experiment AFAIK.

**Comment by joyceerhl** [comment]
@darim1, we fixed a problem with the interactive window kernel selection that went out in today's Stable release. Does this problem still repro if you update to VS Code 1.60?

**Comment by joyceerhl** [comment]
@darim1, please leave a comment on here if the latest update did not resolve this bug. Thank you!

**Comment by darim1** [comment]
We've activated the interactive console and everything appears to work as expected. 

Sorry for the late reply and thanks!

Am 7. September 2021 18:39:40 MESZ schrieb Joyce Er ***@***.***>:
***@***.***, please leave a comment on here if the latest update did not resolve this bug. Thank you!
