### ISSUE TITLE
I get an error while running a jupyter notebok file in vs code.

### ISSUE THREAD

**Issue by Defcon404** [microsoft/vscode-jupyter#7021]
Whenever I run my Jupiter notebook files ,i get an error "**This editor is deprecated and we'll remove it after 1.59 of VS Code. Learn more about our new notebook editor**."  Please Help.
Link to the screenshot (error):
https://ibb.co/KbJLZqt

My vs code info Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
Python 3.9.6.

**Comment by greazer** [comment]
@Defcon404, this is by design. This old notebook experience will be removed in a version shipping after v1.59.

**Comment by loslch** [comment]
@greazer So, can I ignore this message? This message doesn't means that no longer support of 'vscode-jupyter', right?

**Comment by wenguai** [comment]
![image](https://user-images.githubusercontent.com/32946346/129196549-31726029-bb0d-46b3-9eeb-6a1d73a08143.png)
but this header is extremely ugly, is there any way to remove it before a further release of vscode?

**Comment by lpodl** [comment]
Is there anything one can do to get the "new" experience without waiting for the next release? Reading the linked post it seems like the transition was already made. Apparently, this is not the case for users who get this warning. 
The release notes for july state "This month, we moved the code that handles reading *.ipynb files from the Jupyter Notebook extension into a new built-in extension."
Are there currently two notebook editors around, depending on whether or not one has the Jupyter Notebook extension installed?

**Comment by thusithaC** [comment]
The ugly banner is a bit misleading. Why warn if there is no alternative available right now?

**Comment by mj2266** [comment]
I agree @thusithaC . Why is there a banner when I am using latest version, I can't even close the banner

**Comment by shah-xad** [comment]
If I create a new notebook it shows me the new UI. But, when I open the notebook by double click it just switches to the old ugly UI.

**Comment by hamedf62** [comment]
> If I create a new notebook it shows me the new UI. But, when I open the notebook by double click it just switches to the old ugly UI.

same problem here

**Comment by jgriffitts** [comment]
I have the same issue on one computer but another computer seems to run the new editor by default, and does everything described above including working differently when creating a new file.

Both computers are Windows 10 64-bit, release versions of VS Code and jupyter plugin. I can't find any significant differences in settings. There are no output messages that I can find. I'm out of ideas as to what to try next.

**Comment by GitProfAn** [comment]
> > If I create a new notebook it shows me the new UI. But, when I open the notebook by double click it just switches to the old ugly UI.
> 
> same problem here

The same issue.

**Comment by wenguai** [comment]
For all who have the same issue, I found a solution to get rid of this warning temporarily by using the new notebook editor. You may right click on the notebook file and select "Open in Notebook Editor", and the notebook will be launched in the new notebook UI.
![image](https://user-images.githubusercontent.com/32946346/129504572-752ae1cf-bc13-4b5d-a157-6da08d8d73f2.png)

**Comment by shah-xad** [comment]
Well, I found an easy way to get rid of this. In VSCode, right click on `your_notebook.ipynb` then click open with, after that you'll have like this:

![Screenshot from 2021-08-16 15-43-51](https://user-images.githubusercontent.com/32363363/129551849-f79e77ab-87fe-4ea9-a1dc-c71af62b2887.png)

Now click on the last option `Configure default editor for '*ipynb'`, the last one and then select `Jupyter Notebook (Built-in)` the second option from the drop down.
Now you'll have the new UI by default, no need to change again and again.

**Comment by rubkboy7** [comment]
![image](https://user-images.githubusercontent.com/76488414/129573955-e6563bf1-a8e9-4623-a647-367b317fe9a1.png)
I don't have the "built-in" option there. Does anyone know how to fix it?

> Well, I found an easy way to get rid of this. In VSCode, right click on `your_notebook.ipynb` then click open with, after that you'll have like this:
> 
> ![Screenshot from 2021-08-16 15-43-51](https://user-images.githubusercontent.com/32363363/129551849-f79e77ab-87fe-4ea9-a1dc-c71af62b2887.png)
> 
> Now click on the last option `Configure default editor for '*ipynb'`, the last one and then select `Jupyter Notebook (Built-in)` the second option from the drop down.
> Now you'll have the new UI by default, no need to change again and again.

**Comment by jgriffitts** [comment]
Thank you,  shah-xad, this seems to be a correct solution! This is the configuration option that I spent some time looking for, but I never found it.

**Comment by R3dW1ne** [comment]
> ![image](https://user-images.githubusercontent.com/76488414/129573955-e6563bf1-a8e9-4623-a647-367b317fe9a1.png)
> I don't have the "built-in" option there. Does anyone know how to fix it?
> 
> > Well, I found an easy way to get rid of this. In VSCode, right click on `your_notebook.ipynb` then click open with, after that you'll have like this:
> > ![Screenshot from 2021-08-16 15-43-51](https://user-images.githubusercontent.com/32363363/129551849-f79e77ab-87fe-4ea9-a1dc-c71af62b2887.png)
> > Now click on the last option `Configure default editor for '*ipynb'`, the last one and then select `Jupyter Notebook (Built-in)` the second option from the drop down.
> > Now you'll have the new UI by default, no need to change again and again.

I have the same problem. There is no "built in" option on one of my computers. seems to be a bug.

**Comment by shah-xad** [comment]
@R3dW1ne @rubkboy7, I am not sure but check if you're using Vscode `version 1.59.0`, if it's not, try to update it.

**Comment by R3dW1ne** [comment]
> @R3dW1ne @rubkboy7, I am not sure but check if you're using Vscode `version 1.59.0`, if it's not, try to update it.

Thanks @shah-xad, but I've already tried a lot.  Control of the VS Code version, reinstallation of vscode, reinstallation of all extensions, change and reinstallation of the python interpreter .. Funnily enough, it only affects one of three windows 10 devices on which I have installed vscode.

**Comment by azatgx** [comment]
> > @R3dW1ne @rubkboy7, I am not sure but check if you're using Vscode `version 1.59.0`, if it's not, try to update it.
> 
> Thanks @shah-xad, but I've already tried a lot. Control of the VS Code version, reinstallation of vscode, reinstallation of all extensions, change and reinstallation of the python interpreter .. Funnily enough, it only affects one of three windows 10 devices on which I have installed vscode.

If you still have the problem with "Built-in Notebook", try going into the Settings ––> Commonly Used ––> Files: Associations ––> Reset / remove .ipynb
It worked for me, hope it will for you.

**Comment by HishamKhdair** [comment]
> Well, I found an easy way to get rid of this. In VSCode, right-click on `your_notebook.ipynb` then click open with, after that you'll have like this:
> 
> ![Screenshot from 2021-08-16 15-43-51](https://user-images.githubusercontent.com/32363363/129551849-f79e77ab-87fe-4ea9-a1dc-c71af62b2887.png)
> 
> Now click on the last option `Configure default editor for '*ipynb'` and then select `Jupyter Notebook (Built-in)` the second option from the drop-down.
> Now you'll have the new UI by default, no need to change again and again.

Thank you so much, that helped a lot. Now I have the new editor opening by default
