### ISSUE TITLE
JavaScript code cell running errors in Notebooks

### ISSUE THREAD

**Issue by ProCode-Software** [microsoft/vscode-jupyter#7023]
Issue Type: <b>Bug</b>

In Jupyter notebooks, I switched the code cell language to JavaScript and when I run it by clicking ▶️, It shows a syntax error because it still thinks the language is Python. I reproduced it by adding a `const` and it still showed the error. Sample
```javascript
const name = 'John Doe'
```
```
SyntaxError: invalid syntax (Temp/ipykernel_668/3132045494.py, line 1)
  File "%LOCALAPPDATA%\Temp/ipykernel_668/3132045494.py", line 1
    const name = "John Doe"
          ^
SyntaxError: invalid syntax
```
It even showed by a line comment. by using `//`. This is getting annoying, and I have no JavaScript syntax errors.

Screenshot:
![JavaScriptNbbug](https://user-images.githubusercontent.com/68168458/128580089-2c4f0ea6-02c1-4459-ba6d-ff68f660e928.jpg)

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.21390
Restricted Mode: No

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by joyceerhl** [comment]
@ProCode-Software I believe you may need to use the %%javascript magic to tell the kernel that this code is JS? https://ipython.readthedocs.io/en/stable/interactive/magics.html#cellmagic-javascript

**Comment by rchiodo** [comment]
No this is execution. The syntax error is coming from the kernel, not from pylance. The fix is what Joyce suggests.
