### ISSUE TITLE
Re-enable Web View Tests we have been skipping

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7028]
* [ ] Notebook Tests
	* [ ] Remote Self Certificate
	* [ ] Remote No auth (Connect to a server that doesn't have a token or password, customers use this and we regressed it once)
	* [ ] Remote Deny insecure (For a connection to a remote machine that is not secure deny the connection and we should not connect)
	* [ ] Remote Password
	* [x] Export/Import
	* [ ] Non default config fails (should not be able to connect to notebook server with bad config)
	* [x] Custom command line (@donjayamanne)
	* [x] Invalid kernelspec works (@donjayamanne) - no longer applicable after refactoring
	* [ ] Kernelspec generates an env section for a conda env: https://github.com/microsoft/vscode-jupyter/issues/7186  (@donjayamanne)
	* [ ] Server cache working (@donjayamanne)
	* [ ] Execution logging (we only need tests for pre-execute, post execute should be removed & we should use native VS Code API)
	* [ ] Notebook launch failure
	* [ ] Startup commands (@donjayamanne)
	* [ ] Current directory (@donjayamanne)
* [ ] Native Editor functional tests @rchiodo
	* [ ] Export with no python
	* [ ] Invalid session still runs
	* [ ] Invalid kernel still runs
	* [ ] Invalid kernel can be switched
	* [ ] Select Jupyter Server
	* [ ] Server already loaded
	* [ ] Server load skipped
	* [ ] Convert to python
	* [ ] Toggle visibility of output (tests for custom commands), e.g. 
	* [ ] Stop on Error Off (with setting off, I think this is required for Interactive Window)
* [ ] Jupyter Provider Registration
	* [x] #8573
* [ ] Interactive Window
	* [x] Export
	* [x] ~Restart with session failure (I don't think we should do this, when using Native Notebook controller code, this will be unnecessary. Else we'll have to write test for everything we have in Native notebooks, & that seems wrong)~
	* [ ] Copy back to source
* [ ] :runner: Intellisense Functional tests @rchiodo
	* [ ] :runner: Filtered Jupyter autocomplete, verify magic commands appear
	* [ ] :runner: Filtered Jupyter autocomplete, verify magic commands are filtered
	* [ ] :runner: Hover on interactive
* [x] Raw kernel (not required, as we have sufficient native notebook tests that cover this)
* [x] Variable Explorer tests
* [x] Plot Viewer tests
* [ ] IPyWidget tests 
* [x] Run-By-Line tests

**Comment by kieferrm** [comment]
Needs to be split and resulting issue be assigned to owners.
