### ISSUE TITLE
Create a github issue template for bug and feature entries...

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7035]
See https://youtube.com/shorts/PilNDZsko3Y?feature=share for a quick intro.

**Comment by greazer** [comment]
Created an initial version: https://github.com/microsoft/vscode-jupyter/issues/new?assignees=octocat&labels=bug%2Cneeds-triage&template=3_bug_form.yml

**Comment by IanMatthewHuff** [comment]
Verified
