### ISSUE TITLE
Renderer log flooding dev tools when running a simple print loop

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#7040]
Issue Type: <b>Bug</b>

```py
for i in range(0,1000000):
    print(i)
```

Running this cell will generate thousands of logs in Dev Tools. This might have impact on the overall performance.

Extension version: 2021.8.2022228455
VS Code version: Code - Insiders 1.60.0-insider (1ee61f368ee0570feeb220605578a8768d99e762, 2021-08-09T06:11:00.971Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (10.64GB free)|
|Process Argv|--enable-proposed-api joyceerhl.vscode-pyolite --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api donjayamanne.kusto --crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by greazer** [comment]
I'm not seeing logs generated in the Jupyter Output Window panel or the Developer Tools Console. Perhaps Don fixed this already?
