### ISSUE TITLE
Cannot stop editing markdown cell by using hot key

### ISSUE THREAD

**Issue by christina-0725** [microsoft/vscode-jupyter#7042]
Issue Type: <b>Feature Request</b>

# Description
I have changed run cell (ID: "notebook.cell.execute") hot key to `ctrl`+`enter`, which is same as stop editing cell (ID: "notebook.cell.quitEdit"). After changing,  when I press `ctrl`+`enter`. I cannot stop editing and preview markdown cell. 

# Suggestion
I hope I can  stop editing and preview markdown cell when I press `ctrl`+`enter` even if these two hot keys are the same. Thank you!

# Other
The ui of new version jupyter is so cool, I love it.
But when I preview the markdown cell, the font size is so small that I cannot see the words clearly, how can I change the font size of markdown cell preview text.

Extension version: 2021.8.1195043623
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

**Comment by IanMatthewHuff** [comment]
Hmm, I'm not fully sure if we can resolve that hotkey issue. If both actions are mapping to the same hotkey one of them is going to win out and be applied over the other, not both. One thing to try if you want to apply notebook.cell.execute only to non-markdown cells you could add a `notebookCellType != 'markup'` clause to the new keybinding you added for ctrl+enter. That should apply that only to non-markup cells, leaving markup cells to fall back to the old quitEdit command. Does that help at all?

Also regarding the font size, we have an issue open here for that, feel free to upvote (that would bump it up the priority list):
https://github.com/microsoft/vscode/issues/126294

**Comment by christina-0725** [comment]
Thank you for your answer, it really helps me a lot.

And I upvoted at the issue, the preview image is as follows, the font size of markdown preview text is too small.
![preview](https://github.com/christina-0725/VScode-Juypter-extension-bug/blob/main/vscode%20jupyter%20preview.png)

**Comment by greazer** [comment]
@christina-0725, looks like all of the problems you've suggested are resolved for now. Please reopen if there's anything still remaining.
