### ISSUE TITLE
Long loop exection stops emitting outputs

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#7048]
Probably related to https://github.com/microsoft/vscode-jupyter/issues/7038

```py
for i in range(0,1000000):
    print(i)
```

the output stops updating from `125654` and the core no longer gets edits from the extension

**Comment by IanMatthewHuff** [comment]
Reproed. Yeah, that's an odd one. It looks like everything is still running (widget messages coming in) but no UI updates.

**Comment by DonJayamanne** [comment]
This has been fixed
