### ISSUE TITLE
Kernel test when kernel dies during execution

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7052]
Kernel might run out of memory or have a crash.

Test should verify:
- Cell finishes executing
- We can execute another cell afterwards (kernel auto restarted)

**Comment by DonJayamanne** [comment]
> We can execute another cell afterwards (kernel auto restarted)

What? We don't auto start kernels today, i don't think we ever did that.
Thats a feature request.

**Comment by DonJayamanne** [comment]
Here's the original feature request https://github.com/microsoft/vscode-jupyter/issues/5487
@rchiodo  I'm closing this issue in favor of the duplicate
