### ISSUE TITLE
Consider refactoring `NotebookWatcher`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#7055]
It seems like some of the events emitted by the `NotebookWatcher` are also provided by first class VS Code APIs. E.g.

https://github.com/microsoft/vscode-jupyter/blob/5c922c364f40f2399a4c4bbbc1c94348b54f10f9/src/client/datascience/variablesView/variableView.ts#L78-L79

can be replaced with

- `vscode.notebooks.onDidChangeNotebookCellExecutionState`
- `vscode.window.onDidChangeActiveNotebookEditor`

**Comment by rchiodo** [comment]
IF not stubbed for a test, we can just eliminate this.

**Comment by DonJayamanne** [comment]
This class is only used by the Variable viewer, assigning to Rob as he owns that area

**Comment by roblourens** [comment]
I actually don't really like using `onDidChangeNotebookCellExecutionState` when the notebook already knows what was executed, we may not want to finalize that event. I'll just leave this alone
