### ISSUE TITLE
Remove old debugging code

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-jupyter#7057]
src\client\common\application\debugService.ts
src\client\datascience\jupyterDebugService.ts
src\client\datascience\multiplexingDebugService.ts

This one is still used by interactive window so not sure we can remove it.
src\client\datascience\jupyter\jupyterDebugger.ts

**Comment by DonJayamanne** [comment]
This will not be done as it was decided (after a team wide discussion) that we'd not change the code as that would require existing users to upgrade ipykernel for debugging of IW after an update.
