### ISSUE TITLE
Format cell on run like the nb_black extension does.

### ISSUE THREAD

**Issue by nickeubank** [microsoft/vscode-jupyter#7058]
One of my favorite features of vscode (and other good editors) is format on save. Obviously that's not feasible for notebooks because they aren't linear and so a formatter would struggle if it tried to parse everything every time the notebook was saved. But there is a solution that's *like* format on save for notebooks: format on run. 

Now that notebook cells can be formatted, would it be possible to create a setting where each cell is formatted when it's run? It's already available in regular jupyter notebooks thanks to [nb_black](https://github.com/dnanhkhoa/nb_black), and I'd love to see it in VS code notebooks.

**Comment by rchiodo** [comment]
Thanks for the suggestion. We'll look at it in our weekly triage. It will probably need a bunch of upvotes before it's considered.

**Comment by nickeubank** [comment]
Thanks! Since black catches syntax errors, it's kinda related to this too, no? https://github.com/microsoft/vscode-jupyter/issues/1482

**Comment by dwSun** [comment]
+1 code format inside cell is the last reason I still keep jupyter-lab on my system.

**Comment by MarcoGorelli** [comment]
Just FYI, [black now supports Jupyter Notebooks and even has a `black.format_cell` function](https://github.com/psf/black/pull/2357), so that could help here

**Comment by alonme** [comment]
Any news regarding this?

I would personally prefer to have the formatting done on save, and not when running a cell.

**Comment by rchiodo** [comment]
Sorry but it's not planned at the moment.

**Comment by movy** [comment]
Spent 1/2 hour trying to figure out why it's not working... some hint in the config section would be nice.

**Comment by smoochy** [comment]
Could you please reconsider this again?

Cheers.

**Comment by sa2812** [comment]
You can add the `"notebook.formatOnSave.enabled": true` setting as found [here](https://stackoverflow.com/a/75918440/2386054).

**Comment by Yoyokrazy** [comment]
This feature will be in the next insiders build, and can be enabled by adding the following into your settings json:
`"notebook.formatOnCellExecution": true`

**Comment by jucor** [comment]
Awesome, thanks!
