### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by CodeAinz** [microsoft/vscode-jupyter#7062]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.8.1054968649`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.58.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rchiodo** [comment]
Sorry but this isn't enough information to do anything about the problem. What issue are you seeing? Do you have any output in your 'jupyter' output tab?

**Comment by rchiodo** [comment]
Your version of VS code is also out of date. The latest is 1.59.
