### ISSUE TITLE
Jupyter extension %matplotlib inline plot background issue

### ISSUE THREAD

**Issue by mcdonoughj** [microsoft/vscode-jupyter#7066]
Issue: matplotlib plots rendered poorly when using "%matplotlib inline"

Does this issue occur when all extensions are disabled?: Yes (have to enable python and Jupiter only in order to run), everything else disabled, same issue

- VS Code Version: 1.59
- OS Version: Windows 10

Steps to Reproduce:

1. %matplotlib inline, plot background is full width (although saving the image to pdf is the correct size), the issue appears to be the way it is rendered in the notebook
2. Remove %matplotlib inline and call plt.show() to fix

Using %matplotlib inline
![%matplotlib inline](https://user-images.githubusercontent.com/83503346/129051637-d23d87a1-e0db-42a4-991e-39ef59b6937f.png)

Using plt.show()
![plt show()](https://user-images.githubusercontent.com/83503346/129051653-0fb7720b-88dc-4255-a3a4-9dfed301e05b.png)

**Comment by rchiodo** [comment]
Thanks for the bug. 

Likely a CSS problem that we're not handling when matplotlib inline is used.

**Comment by Igorgro** [comment]
Also, maybe the plot should be centered like it is done in jupyterlab?
![изображение](https://user-images.githubusercontent.com/22894169/130279213-ef4ba98e-ef93-4523-a405-22047cb60489.png)

**Comment by AMIT110409** [comment]
do you guys have an idea in vscode what we use instead of this  %matplotlib inline . because in jupiter it is correct .

**Comment by DonJayamanne** [comment]
I've tested this against the latest pre-release version and the output seems to be as per Jupyter Lab
Here are the screenshots
![Screenshot 2022-12-30 at 14 32 57](https://user-images.githubusercontent.com/1948812/210031768-f0d7a9f4-2f31-4ae4-9bdb-e571241adca2.png)
![Screenshot 2022-12-30 at 14 33 02](https://user-images.githubusercontent.com/1948812/210031771-9f8dc4df-28de-4bb6-99f3-2c29c3e5e54a.png)
