### ISSUE TITLE
Change INotebookExecutionLogger to be an event (if possible) on the IKernelProvider

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7072]
INotebookExecutionLogger can go away. We need something to work with new native notebooks instead.

- If Pre/Post events can replace the concept (there's no need to modify the execution source) then we can use events
- If Pre/Post events need to replace source (cellhashprovider) then we can have some sort of hook system. Maybe like [addSendHook ](https://github.com/microsoft/vscode-jupyter/blob/bd63750c91e6e23dacdfb99c24d88086e0d1acd4/src/client/datascience/raw-kernel/rawSocket.ts#L118) method?

**Comment by DonJayamanne** [comment]
Closing as this has been fixed, INotebookExecutionLogger is no longer around
