### ISSUE TITLE
Notebook initialize code (startup commands, custom directory) is not applied on native notebook restart

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#7086]
On restart of native notebooks the restartKernel function of the notebook is not being applied. This means that things like custom working directories and custom startup commands are not applied on restart as expected.

**Comment by joyceerhl** [comment]
This was on purpose to fix https://github.com/microsoft/vscode-jupyter/issues/5996, because the old restartKernel method would wait for pending execution to complete instead of cancelling them all the way that kernel interrupt did /cc @rchiodo

**Comment by jaymegordo** [comment]
@IanMatthewHuff would jupyter startup commands eg:
```
    "jupyter.runStartupCommands": [
        "%alias_magic t timeit",
        "%load_ext autoreload",
        "%autoreload 2"
    ],
```

Fall under what you're talking about? I'm just noticing these don't work now in the native interactive window (I'm gonna use NIW from now on haha). Just wondering if you guys are aware or I should open a separate issue.

Not having `autoreload` makes the NIW pretty hard to use tbh so hopefully @joyceerhl 's PR resolves it?

**Comment by jaymegordo** [comment]
Ahh yes, the startup commands do work on first open of IW, but fail after a "restart". Thats why I was only noticing it sometimes.

**Comment by IanMatthewHuff** [comment]
@joyceerhl Yeah, I was looking at it a bit. In the old restart the cell cancellations are mixed in with the initialization steps. We'd want to separate out just the init code so that we can run the re-initialization without mixing up the old and new methods of cell cancellation. The init function could probably just take any old JupyterNotebook as an input.

**Comment by rchiodo** [comment]
Remove restart and just replace with kernel start.

**Comment by rchiodo** [comment]
questions about whether we wait for full refactor or not.

**Comment by joyceerhl** [comment]
This has been fixed https://github.com/microsoft/vscode-jupyter/blob/2e1c221cdc3ec1128d55886711677f77d699e552/src/client/datascience/jupyter/kernels/kernel.ts#L359-L377
