### ISSUE TITLE
Jupyter: Create Interactive Window - IW opens in 3rd tab group

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode-jupyter#7095]
## Environment data
- Version: 1.60.0-insider
- Commit: 7c25c174726ab969db3f99058cdf24bcfae1cfbe
- Date: 2021-08-11T05:13:17.497Z
- Jupyter Extension version (available under the Extensions sidebar): v2021.8.2025984474
- Python Extension version (available under the Extensions sidebar): v2021.9.1117361286-dev
- OS (Windows | Mac | Linux distro) and version: Darwin x64 20.6.0
- Python and/or Anaconda version: 3.9.2
- Type of virtual environment used: poetry
- Jupyter server running: Local

This is admittedly minor, but with webview IW, `jupyter: create interactive window` would create the IW in a second tab group if only one existed, or append to the second tab group if two already existed.

## Actual Behavior
- `jupyter: create interactive window` creates the new IW in "focused tab group + 1" no matter what (eg if tab group 1 is focused, it will be created in the second. If tag group 2 focused, it will be created in a third, but I never want more than two tab groups).
<img width="2248" alt="Screen Shot 2021-08-12 at 9 31 11 AM" src="https://user-images.githubusercontent.com/29611875/129233786-951fd58e-296d-49d4-93de-a1ae5b49503c.png">

## Expected Behavior
- `jupyter: create interactive window` always creates IW in second tab group, as per original webview behavior.

**Comment by greazer** [comment]
@jaymegordo, thanks for the feedback! This is a tough call to make. Can you take a couple minutes to describe why you prefer this behavior?

**Comment by jaymegordo** [comment]
@greazer well I think the first reason is that it's the behavior of the old webview IW so it's what I'm used to.

For my personal workflow at least, I'm always using the IW with a bunch `.py` or other files, and two is just the pefect number of tab groups haha. The IW always works best with at least one other file open beside, but I could never focus on MORE than 2 tab groups at a time.

**Comment by amunger** [comment]
added setting `jupyter.interactiveWindowViewColumn` to adjust where an interactive window will be opened when the `Jupyter: Create Interactive Window` command is called. 

Default is the second tab group as suggested in this issue.

**Comment by IanMatthewHuff** [comment]
Tried it will all three settings, looks good.
