### ISSUE TITLE
Output truncated with no way to view all output in the notebook itself

### ISSUE THREAD

**Issue by KRiedmiller** [microsoft/vscode-jupyter#7096]
Issue Type: <b>Bug</b>

Since the 1.59 update the output of cells in an interactive python window is truncated if it is longer than 30 lines. The setting 'jupyter.textOutputLimit' is not respected, and I couldn't find another way to change this behaviour.
This is extremly annoying as the 'show more' option only brings up the output unformatted, which isn't usable for long outputs.
I think previously this was solved with a scroll bar which worked perfectly.

Extension version: 2021.8.1105858891
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.4.0-80-generic
Restricted Mode: No
Remote OS version: Linux x64 5.11.22-100.fc32.x86_64
Remote OS version: Linux x64 5.11.22-100.fc32.x86_64

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30351386
vstre464cf:30350173

```

</details>

**Comment by greazer** [comment]
@KRiedmiller thanks for the feedback! While it's being discussed on our end, in the meantime you can work around this a bit by adjusting this setting:

```json
"notebook.output.textLineLimit": 30
```
Setting to 0 will cause the truncation to be disabled all together. 

Also the raw json format of data that is shown in a separate file when clicking on the "show more" link will be fixed in the next release of VS Code. 

We understand that your desire is to support just showing more in the same cell output.

**Comment by maflAT** [comment]
The same bug also applies to standard notebooks, not only the interactive window.

**Comment by turbonate** [comment]
Just to add a bit here, this truncation causes issues when using `help(object)` as the help file for almost every major python library is more than 30 lines.  It makes the kernel unusable for debugging without the workarounds mentioned in this thread.  

Specific commonly used object examples:  `help(pd.DataFrame)` `help(sm.OLS)`

Thanks!

**Comment by greazer** [comment]
Highly related issue: https://github.com/microsoft/vscode-jupyter/issues/1543. Closing that one as the resolution for this one should address it.

**Comment by fschiffers** [comment]
I just wanted to add that  setting textLineLimit to as
"notebook.output.textLineLimit": 0
doesn't have the expected effect.

I also tried really high numbers (e.g. 5000), but there still seems to be an internal limit. 

I'm using the pytorch lightning advancer profile which spits out a lot of information and I cannot see the information I'd like to see since it truncates at some point.

**Comment by rebornix** [comment]
@greazer and I discussed offline about the common scenarios/workflows, two of which can be improved:

* [x] Streaming output, e.g., for loops. We currently render a warning message "output reaches limit, show more" which opens the raw output in a text editor. 
  * [x] Once the output data is opened in the text editor, it should be synced when the output data is still updating until the streaming ends
  * [x] We may want to show the "show more" link at the beginning of the rendered output other than the middle/bottom.
* [ ] Large single text output, e.g. `help dataframe`. When we use `help` to check the definition of a class/function, the output is usually a single output item which contains several thousands lines of text (each line is relatively short though). it would be cumbersome if we have to open the output in a separate editor.

**Comment by amunger** [comment]
We have added an experimental setting to enable scrolling on notebook outputs. Turn it on with 
`"notebook.experimental.outputScrolling": true`

**Comment by amunger** [comment]
It's just an experiment at this point, so it won't appear in the settings UI, it must be manually set in the json.

**Comment by underwoodnoble** [comment]
It doesn't work.
![1669984095529](https://user-images.githubusercontent.com/55843000/205293088-3bda683f-3d64-47df-b186-38d2031af0c4.jpg)

**Comment by gjsjohnmurray** [comment]
@underwoodnoble the "Unknown Configuration Setting" message is just a warning. You can still save it. Does it have the desired effect? If not I suggest you try again after a VS Code reload/restart.

**Comment by OyLingji** [comment]
The scrollbar seems not work for the error messages. (v2023.2.1000481019)
