### ISSUE TITLE
Native Interactive Window - Pylance errors with variables imported in jupyter startup script

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode-jupyter#7098]
## Environment data
- Version: 1.60.0-insider
- Commit: 7c25c174726ab969db3f99058cdf24bcfae1cfbe
- Date: 2021-08-11T05:13:17.497Z
- Jupyter Extension version: v2021.8.2025984474
- Python Extension version: v2021.9.1117361286-dev
- OS: Darwin x64 20.6.0
- Python and/or Anaconda version: 3.9.2
- Type of virtual environment used: poetry
- Jupyter server running: Local

One main part of my workflow is to have certain variables/modules imported at jupter startup, defined in a `startup.py` file at:
- `~/.ipython/profile_default/startup/startup.py`

Expalained fully [here](https://towardsdatascience.com/how-to-automatically-import-your-favorite-libraries-into-ipython-or-a-jupyter-notebook-9c69d89aa343)

## Expected behaviour

- Jupyter/native interactive window/pylance recognizes variables imported through a startup script.

## Actual behaviour

For example I'd have
```py
#! startup.py
import pandas as pd
```

The module is imported, and `pd` is valid in the `globals()`, but pylance doesn't seem to recognize it. I'll also import lots of custom objects from the current project I'm working on, so you can imagine it's kinda hard to work when almost every variable is "undefined" (and also doesn't have intellisense).

In screenshots:
<img width="607" alt="Screen Shot 2021-08-12 at 9 48 59 AM" src="https://user-images.githubusercontent.com/29611875/129238104-862f6175-f9fc-4f11-9252-a7e536a980e8.png">

Not sure what's actually going on here, but just expanding the code from the previous image (before executing anything) made pylance/problems go crazy:
<img width="643" alt="Screen Shot 2021-08-12 at 9 50 00 AM" src="https://user-images.githubusercontent.com/29611875/129238119-e15fc32b-21d5-4f5b-b942-209fc081224f.png">

`pd` is recognized after explicitely importing in the current session:
<img width="530" alt="Screen Shot 2021-08-12 at 9 52 06 AM" src="https://user-images.githubusercontent.com/29611875/129238134-cfd6eba3-7aee-4243-b5aa-59781fc4b55d.png">

**Comment by greazer** [comment]
@jaymegordo Thanks for the feedback!

**Comment by rchiodo** [comment]
Sorry but this isn't currently supported. This is basically the same bug as this one:
#6987

**Comment by jaymegordo** [comment]
@rchiodo thanks for letting me know. Do you know if there will be any plans to support this in the future? Do you know of any other workarounds to have certain modules importd to the IW automatically which would support intellisense?

**Comment by rchiodo** [comment]
@jaymegordo you can track #6987 to see if we end up supporting dynamic modules in pylance or not. My guess is it won't be supported for a long time as pylance doesn't run any python code. It's all static analysis based. We might be able to fudge it by concating the code for a run startup commands onto the top of the notebook, but we haven't tried yet.
