### ISSUE TITLE
Export as pdf masks errors when it fails

### ISSUE THREAD

**Issue by djbhalodiya** [microsoft/vscode-jupyter#710]
Issue Type: <b>Bug</b>

PDF exported but with 0(zero) file size

Extension version: 2020.7.96456
VS Code version: Code - Insiders 1.48.0-insider (15ada625f20086007e2c4aa0d760234360cd648f, 2020-07-30T14:43:12.691Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.98GB free)|
|Process Argv|C:\Users\Dharmesh\Downloads\Mini-Project\BDPV - Mini Project\Mini Project.ipynb --crash-reporter-id 4086b05a-5e70-42e1-b21c-dd41020609e7|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by WenukaB** [comment]
> I have same issue here. Even though HTML format works well, the pdf format failed

I'm facing the same problem

**Comment by rchiodo** [comment]
@WenukaB your jupyter output tab should show you what the failure is. Generally for export to PDF you have to install extra software.

See this:
https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex
