### ISSUE TITLE
Change shortcuts for merge/join 

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7105]
Split from #7076. Change the shortcuts for merge to match those more used in the Jupyter Notebooks community. Specifically, use Control + Shift + M to merge with previous cell and Shift + M to merge with next cell. This is to replace the current shortcuts of Shift + Alt + Windows + J to merge with previous cell and Alt + Windows + J to merge with next cell.

**Comment by xhlulu** [comment]
Good to see this issue (after https://github.com/microsoft/vscode-jupyter/issues/1227 was closed)! 

At the moment it's possible to customize the keyboard shortcuts to use `Ctrl Shift M` or `Shift M`: 
![image](https://user-images.githubusercontent.com/21180505/147126644-91f92e31-feee-4aa5-96b2-f835ca4c807b.png)


However, in regular jupyter notebooks you can press `Shift M` when you have selected multiple cells and merge them all at the same time; I find this functionality to be very useful:

https://user-images.githubusercontent.com/21180505/147127034-eec011d4-935e-4eb9-99e5-5b4cea65b76d.mp4

Is there plans on implementing this?

**Comment by seeM** [comment]
See https://github.com/microsoft/vscode-jupyter-keymap/pull/10#issuecomment-1521454081.

The Jupyter-like behaviour seems possible with:

```json
  {
    "key": "shift+m",
    "command": "notebook.cell.joinBelow",
    "when": "notebookEditorFocused && !inputFocus"
  },
  {
    "key": "shift+m",
    "command": "notebook.cell.joinSelected",
    "when": "notebookEditorFocused && !inputFocus && listMultiSelection"
  },
```
