### ISSUE TITLE
No command history via ArrowUp in Python interactive window

### ISSUE THREAD

**Issue by dahilzen** [microsoft/vscode-jupyter#711]
# Bug in Interactive Window

I tried different versions of python from both venv and anaconda and different versions of the python-extension. There seems to be no command history in the interactive window.

Arrow up works when I type something in the interactive window and open ipython in the integrated terminal. Then there are even the previous commands I executed in the interactive window.

My current workaround:
"python.dataScience.sendSelectionToInteractiveWindow": false,
"python.terminal.launchArgs": ["-c", "\"import subprocess; subprocess.call(['ipython', '--no-autoindent'])\""],

## Steps to cause the bug to occur

1. Install Python extension
2. Create Python script
3. Send selection to interative window
4. Type some code in interactive window
5. try arrow-up

## Actual behavior
nothing happens, no previous commands 

## Expected behavior
previous commands should show up

## Jupyter and/or Python environment

-   **Jupyter server running:** Local
-   **Extension version:** v2020.7.96456
-   **VS Code version:** 1.47.3
-   **Setting python.jediEnabled:** false
-   **Setting python.languageServer:** Microsoft
-   **Python and/or Anaconda version:** 3.7.5 (I tried several)
-   **OS:** Ubuntu 18.04.4 LTS
-   **Virtual environment:** venv (but it doesn't matter which I choose)

## Developer Tools Console Output

/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:266 [Extension Host] (node:10507) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

t.log @ /snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:266
/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:266 [Extension Host] (node:10507) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

t.log @ /snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:266

/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:266 [Extension Host] Starting WebSocket: ws://localhost:8889/api/kernels/421c14f4-0a22-435c-9f13-0b1d8476290b

/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:266 [Extension Host] Kernel: connected (421c14f4-0a22-435c-9f13-0b1d8476290b)

/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:266 [Extension Host] Starting WebSocket: ws://localhost:8889/api/kernels/0b338f83-c258-4acf-bbc4-beabbabf0df7

/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:266 [Extension Host] Kernel: connected (0b338f83-c258-4acf-bbc4-beabbabf0df7)

/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3864 [Embedded Page] Starting WebSocket: BOGUS_PVSC/api/kernels/421c14f4-0a22-435c-9f13-0b1d8476290b

/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3864 [Embedded Page] Kernel: connected (421c14f4-0a22-435c-9f13-0b1d8476290b)

/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3864 [Embedded Page] Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/Microsoft/monaco-editor#faq

/snap/code/39/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3864 [Embedded Page] Failed to construct 'Worker': Script at 'vscode-webview-resource://e5b14fd1-bb51-42c4-8a49-4d1e53a310e7/file///home/administrator/projekte/test/editor.worker.js' cannot be accessed from origin 'vscode-webview://e5b14fd1-bb51-42c4-8a49-4d1e53a310e7'.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by infornite** [comment]
Confirming that I have the same issue on an Ubuntu 20.04 VM installed via Hyper-V

**Comment by darim1** [comment]
Hey, I encounter the same annoying problem. Is there a workaround?
Thanks,
Daniel

**Comment by joyceerhl** [comment]
Pulling this back to triage for discussion.

**Comment by rchiodo** [comment]
I'm not sure what's being asked for here. Arrow up definitely works in the interactive window. But it doesn't let you arrow through all the cells sent. Just the stuff you typed in. 

It sounds like this bug is about being able to arrow up through every cell executed (which has never worked).

**Comment by darim1** [comment]
@rchiodo thanks for the quick reply! 

Please let me specify: 

1. I open an interactive window
2. I type e.g. a=1 => ret
3. Then I push arrow-up and would expect proposal of a=1
4. alternatively I'd like to type a => arrow-up => proposal of a = 1

One additional remark: This works perfectly fine on Windows. I ancounter problems on Ubuntu 18.04.3LTS. It seems broken.

**Comment by rchiodo** [comment]
> I encounter problems on Ubuntu 18.04.3LTS. It seems broken.

What version of the jupyter extension are you using on the Ubuntu machine? The code is identical for both so if it works on Windows it should work on Ubuntu.

**Comment by rchiodo** [comment]
Can you send the output of your 'jupyter' tab?

**Comment by darim1** [comment]
Which output?

**Comment by rchiodo** [comment]
The whole panel. It should have a whole bunch of text in it.

**Comment by darim1** [comment]
Sorry, can't find this tab. How can I start this?

jupyter --version outputs:

bdrimmel@ubuntu1804-vm:/media/bdrimmel/data/git/backend$ jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.3.0
qtconsole        : not installed
ipython          : 7.16.1
ipykernel        : 5.5.3
jupyter client   : 6.1.12
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : not installed
nbformat         : 5.1.3
traitlets        : 4.3.3

**Comment by rchiodo** [comment]
If you click 'View | Output' in the main menu, the output tab will open.

![image](https://user-images.githubusercontent.com/19672699/114922660-c9def780-9de0-11eb-8ee5-611dd5d0a233.png)

That output tab has a dropdown on the right hand side. That drop down lets you see the output from different things that are running. Jupyter should be in that list. That's our debug output.

**Comment by darim1** [comment]
Info 2021-04-15 21:00:16: restartKernel - finishing cells that are outstanding
Info 2021-04-15 21:00:16: restartKernel - restarting kernel
Info 2021-04-15 21:00:16: Restarting 0716b001-5596-40a1-a9f4-dc42ca81f109
Info 2021-04-15 21:00:16: Got new session f003d4fb-daf7-45ce-a1fd-408922e1777e
Info 2021-04-15 21:00:16: Started new restart session
Info 2021-04-15 21:00:16: shutdownSession 0716b001-5596-40a1-a9f4-dc42ca81f109, .python369jvsc74a57bd0069fa2f23f34bb9a5fa3ab14bfd727866d8110d27556f8ce115569f6d74efb0e./xxx/.venv/bin/python.Python 3.6.9 64-bit ('.venv') - start
Info 2021-04-15 21:00:16: Session can be shutdown .python369jvsc74a57bd0069fa2f23f34bb9a5fa3ab14bfd727866d8110d27556f8ce115569f6d74efb0e./xxx/.venv/bin/python.Python 3.6.9 64-bit ('.venv')
Info 2021-04-15 21:00:16: restartKernel - initialSetup
Info 2021-04-15 21:00:16: Initial setup for history://62a49cfa-b4f5-4e8e-b730-678ddbdbf911 starting ...
Info 2021-04-15 21:00:16: UpdateWorkingDirectoryAndPath
Info 2021-04-15 21:00:16: Python Daemon (pid: 3170): write to stderr: [I 21:00:16.945 NotebookApp] Creating new notebook in /
[I 21:00:16.945 NotebookApp] Creating new notebook in /Info 2021-04-15 21:00:16: Python Daemon (pid: 3170): write to stderr: 


Info 2021-04-15 21:00:16: Python Daemon (pid: 3170): write to stderr: [I 21:00:16.983 NotebookApp] Kernel shutdown: 0716b001-5596-40a1-a9f4-dc42ca81f109
[I 21:00:16.983 NotebookApp] Kernel shutdown: 0716b001-5596-40a1-a9f4-dc42ca81f109Info 2021-04-15 21:00:16: Python Daemon (pid: 3170): write to stderr: 


Info 2021-04-15 21:00:17: shutdownSession 0716b001-5596-40a1-a9f4-dc42ca81f109, .python369jvsc74a57bd0069fa2f23f34bb9a5fa3ab14bfd727866d8110d27556f8ce115569f6d74efb0e./xxx/.venv/bin/python.Python 3.6.9 64-bit ('.venv') - shutdown complete
Warn 2021-04-15 21:00:17: [Error: Canceled
	at t.KernelShellFutureHandler.dispose (/home/xxx/.vscode/extensions/ms-toolsai.jupyter-2021.5.745244803/out/client/node_modules/@jupyterlab/services.js:3:498700)
	at /home/xxx/.vscode/extensions/ms-toolsai.jupyter-2021.5.745244803/out/client/node_modules/@jupyterlab/services.js:3:489165
	at Map.forEach (<anonymous>)
	at f._clearState (/home/xxx/.vscode/extensions/ms-toolsai.jupyter-2021.5.745244803/out/client/node_modules/@jupyterlab/services.js:3:489108)
	at f.dispose (/home/xxx/.vscode/extensions/ms-toolsai.jupyter-2021.5.745244803/out/client/node_modules/@jupyterlab/services.js:3:482826)
	at c.dispose (/home/xxx/.vscode/extensions/ms-toolsai.jupyter-2021.5.745244803/out/client/node_modules/@jupyterlab/services.js:3:540943)
	at /home/xxx/.vscode/extensions/ms-toolsai.jupyter-2021.5.745244803/out/client/node_modules/@jupyterlab/services.js:3:544740
	at Object.t.each (/home/xxx/.vscode/extensions/ms-toolsai.jupyter-2021.5.745244803/out/client/node_modules/@jupyterlab/services.js:1:63056)
	at /home/xxx/.vscode/extensions/ms-toolsai.jupyter-2021.5.745244803/out/client/node_modules/@jupyterlab/services.js:3:544709
	at /home/xxx/.vscode/extensions/ms-toolsai.jupyter-2021.5.745244803/out/client/node_modules/@jupyterlab/services.js:3:544752
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
Info 2021-04-15 21:00:17: Kernel switching to busy
Info 2021-04-15 21:00:17: installMissingDependencies /xxx/.venv/bin/python
Info 2021-04-15 21:00:17: Process Execution: > /xxx/.venv/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.5.745244803/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /xxx/.venv/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.5.745244803/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Info 2021-04-15 21:00:17: Kernel switching to idle
Info 2021-04-15 21:00:17: Kernel switching to busy
Info 2021-04-15 21:00:17: Kernel switching to idle
Info 2021-04-15 21:00:17: Initial setup complete for history://62a49cfa-b4f5-4e8e-b730-678ddbdbf911
Info 2021-04-15 21:00:17: restartKernel - initialSetup completed
Info 2021-04-15 21:00:17: Time to restart kernel is 0.472s
Info 2021-04-15 21:00:17: Registering commtarget jupyter.widget
Info 2021-04-15 21:00:17: Adding sys info for b010c6de-75cd-4467-8423-79fa5b8e6fcc 1
Info 2021-04-15 21:00:17: Sys info for b010c6de-75cd-4467-8423-79fa5b8e6fcc 1 complete
Info 2021-04-15 21:00:18: Install Missing Dependencies, Class name = v, completed in 1391ms, has a falsy return value, Return Value: undefined
Info 2021-04-15 21:00:18: Spec argv[0] updated from '/xxx/.venv/bin/python' to '/xxx/.venv/bin/python'
Info 2021-04-15 21:00:18: Check if a kernel is usable, Class name = b, completed in 1461ms, has a falsy return value, Arg 1: {"kind":"startUsingPythonInterpreter","kernelSpec":{"specFile":"/home/xxx/.local/share/jupyter/kernels/python369jvsc74a57bd0069fa2f23f34bb9a5fa3ab14bfd727866d8110d27556f8ce115569f6d74efb0e/kernel.json","name":"python369jvsc74a57bd0069fa2f23f34bb9a5fa3ab14bfd727866d8110d27556f8ce115569f6d74efb0e","argv":["/xxx/.venv/bin/python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"/xxx/.venv/bin/python","display_name":"Python 3.6.9 64-bit ('.venv')","metadata":{"interpreter":{"architecture":3,"path":"/xxx/.venv/bin/python","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.6.9-final","major":3,"minor":6,"patch":9,"prerelease":["final"],"build":[],"version":"3.6.9-final"},"sysVersion":"3.6.9 (default, Jan 26 2021, 15:33:00) \n[GCC 8.4.0]","sysPrefix":"/xxx/.venv","fileHash":"8457d16a8155bfde0d8aca7e390b457473ef006e66821529c174ca0cc584c05daf9e1ddfa6504b7f5de66a392baff5790ce10e48bf8c2908430de1661bcfe1a2","envName":".venv","type":"Venv","displayName":"Python 3.6.9 64-bit ('.venv')"}},"env":{"CLUTTER_IM_MODULE":"xim","VSCODE_NODE_CACHED_DATA_DIR":"/home/xxx/.config/Code/CachedData/3c4e3df9e89829dce27b7b5c24508306b151f30d","PYTHONUNBUFFERED":"1","NVM_DIR":"/home/xxx/.nvm","LS_COLORS":"","VSCODE_NLS_CONFIG":"{\"locale\":\"de\",\"availableLanguages\":{},\"_languagePackSupport\":true}","LESSCLOSE":"/bin/lesspipe %s %s","XDG_MENU_PREFIX":"gnome-","SNAP_USER_DATA":"/home/bdrimmel/snap/code/62","LANG":"de_DE.UTF-8","DISPLAY":":10.0","VSCODE_CRASH_REPORTER_START_OPTIONS":"{\"companyName\":\"Microsoft\",\"productName\":\"VSCode\",\"submitURL\":\"appcenter://code?aid=fba07a4d-84bd-4fc8-a125-9640fc8ce171&uid=a43464b4-e5ab-4da2-b6ab-f10b4eae589a&iid=a43464b4-e5ab-4da2-b6ab-f10b4eae589a&sid=a43464b4-e5ab-4da2-b6ab-f10b4eae589a\",\"uploadToServer\":true}","ORIGINAL_XDG_CURRENT_DESKTOP":"ubuntu:GNOME","VSCODE_LOG_STACK":"false","GNOME_SHELL_SESSION_MODE":"ubuntu","SNAP_REVISION":"62","VSCODE_IPC_HOOK_EXTHOST":"/run/user/1000/vscode-ipc-bdb59d59-c6a1-4d4e-8807-8a0b28b4a258.sock","DISABLE_WAYLAND":"1","SNAP_ARCH":"amd64","SNAP_INSTANCE_KEY":"","NVM_CD_FLAGS":"","CHROME_DESKTOP":"code-url-handler.desktop","GIO_LAUNCHED_DESKTOP_FILE_PID":"1978","PYTHONIOENCODING":"utf-8","SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","VIRTUAL_ENV":"/xxx/.venv","SNAP_REAL_HOME":"/home/bdrimmel","APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL":"true","XDG_SESSION_ID":"c3","XRDP_SOCKET_PATH":"/var/run/xrdp/sockdir","SNAP_USER_COMMON":"/home/xxx/snap/code/common","USER":"bdrimmel","QT4_IM_MODULE":"xim","TEXTDOMAINDIR":"/usr/share/locale/","PULSE_SCRIPT":"/etc/xrdp/pulse/default.pa","PWD":"/home/xxx","HOME":"/home/xxx","UID":"1000","TEXTDOMAIN":"im-config","SNAP":"/snap/code/62","SSH_AGENT_PID":"1607","QT_ACCESSIBILITY":"1","VSCODE_VERBOSE_LOGGING":"true","SNAP_COMMON":"/var/snap/code/common","DATABASE_PORT":"5432","VSCODE_LOG_NATIVE":"false","SNAP_NAME":"code","XDG_DATA_DIRS":"/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop","VSCODE_CWD":"/home/xxx","SNAP_INSTANCE_NAME":"code","VSCODE_AMD_ENTRYPOINT":"vs/workbench/services/extensions/node/extensionHostProcess","SNAP_DATA":"/var/snap/code/62","GSETTINGS_SCHEMA_DIR":"/snap/code/62/usr/share/glib-2.0/schemas","GJS_DEBUG_OUTPUT":"stderr","GDK_PIXBUF_MODULE_FILE":"/home/xxx/snap/code/common/.cache/gdk-pixbuf-loaders.cache","ELECTRON_NO_ATTACH_CONSOLE":"1","VSCODE_CLI":"1","GTK_MODULES":"gail:atk-bridge","SNAP_COOKIE":"iLmYhveDhEgcWACByncrBRgGXxnaufHFo3sjjBt3XWc7h32JQ1Pl","VSCODE_PID":"2041","NVM_RC_VERSION":"","SHELL":"/bin/bash","QT_IM_MODULE":"ibus","VSCODE_HANDLES_UNCAUGHT_ERRORS":"true","XMODIFIERS":"@im=ibus","IM_CONFIG_PHASE":"2","XDG_CURRENT_DESKTOP":"Unity","GPG_AGENT_INFO":"/run/user/1000/gnupg/S.gpg-agent:0:1","BAMF_DESKTOP_FILE_HINT":"/var/lib/snapd/desktop/applications/code_code.desktop","SNAP_REEXEC":"","DATABASE_USER":"admin","VSCODE_PIPE_LOGGING":"true","GIO_LAUNCHED_DESKTOP_FILE":"/var/lib/snapd/desktop/applications/code_code.desktop","ELECTRON_RUN_AS_NODE":"1","SHLVL":"2","GDK_PIXBUF_MODULEDIR":"/snap/code/62/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders","GNOME_DESKTOP_SESSION_ID":"this-is-deprecated","LOGNAME":"bdrimmel","DBUS_SESSION_BUS_ADDRESS":"unix:path=/run/user/1000/bus","XDG_RUNTIME_DIR":"/run/user/1000","SNAP_CONTEXT":"iLmYhveDhEgcWACByncrBRgGXxnaufHFo3sjjBt3XWc7h32JQ1Pl","PATH":"/xxx/.venv/bin:/home/xxx/.local/bin:/sbin:/bin:/usr/bin:/usr/local/bin:/snap/bin","DATABASE_HOST":"localhost","PS1":"(.venv) ","VSCODE_IPC_HOOK":"/run/user/1000/vscode-3cd9406c-1.55.2-main.sock","SNAP_VERSION":"3c4e3df9","GJS_DEBUG_TOPICS":"JS ERROR;JS LOG","SNAP_LIBRARY_PATH":"/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void","SESSION_MANAGER":"local/ubuntu1804-vm:@/tmp/.ICE-unix/1508,unix/ubuntu1804-vm:/tmp/.ICE-unix/1508","XRDP_SESSION":"1","DATABASE_PASSWORD":"admin","BREAKPAD_DUMP_LOCATION":"/home/xxx/.config/Code/exthost Crash Reports","LESSOPEN":"| /bin/lesspipe %s","GTK_IM_MODULE":"ibus","_":"/xxx/.venv/bin/python"}},"interpreter":{"architecture":3,"path":"/xxx/.venv/bin/python","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.6.9-final","major":3,"minor":6,"patch":9,"prerelease":["final"],"build":[],"version":"3.6.9-final"},"sysVersion":"3.6.9 (default, Jan 26 2021, 15:33:00) \n[GCC 8.4.0]","sysPrefix":"/xxx/.venv","fileHash":"8457d16a8155bfde0d8aca7e390b457473ef006e66821529c174ca0cc584c05daf9e1ddfa6504b7f5de66a392baff5790ce10e48bf8c2908430de1661bcfe1a2","envName":".venv","type":"Venv","displayName":"Python 3.6.9 64-bit ('.venv')"},"id":".python369jvsc74a57bd0069fa2f23f34bb9a5fa3ab14bfd727866d8110d27556f8ce115569f6d74efb0e./xxx/.venv/bin/python./xxx/.venv/bin/python.Python 3.6.9 64-bit ('.venv')"}, Arg 2: undefined, Arg 3: true, Return Value: undefined
Info 2021-04-15 21:00:18: Starting a new session for kernel id = .python369jvsc74a57bd0069fa2f23f34bb9a5fa3ab14bfd727866d8110d27556f8ce115569f6d74efb0e./xxx/.venv/bin/python./xxx/.venv/bin/python.Python 3.6.9 64-bit ('.venv'), name = python369jvsc74a57bd0069fa2f23f34bb9a5fa3ab14bfd727866d8110d27556f8ce115569f6d74efb0e
Info 2021-04-15 21:00:18: Python Daemon (pid: 3170): write to stderr: [I 21:00:18.845 NotebookApp] Kernel started: a35d02fe-126e-4367-80f8-952695a7d7a7, name: python369jvsc74a57bd0069fa2f23f34bb9a5fa3ab14bfd727866d8110d27556f8ce115569f6d74efb0e
Info 2021-04-15 21:00:18: Waiting for idle on (kernel): a35d02fe-126e-4367-80f8-952695a7d7a7 -> unknown
[I 21:00:18.845 NotebookApp] Kernel started: a35d02fe-126e-4367-80f8-952695a7d7a7, name: python369jvsc74a57bd0069fa2f23f34bb9a5fa3ab14bfd727866d8110d27556f8ce115569f6d74efb0eInfo 2021-04-15 21:00:18: Python Daemon (pid: 3170): write to stderr: 


Info 2021-04-15 21:00:18: Python Daemon (pid: 3170): write to stderr: [W 21:00:18.899 NotebookApp] delete /mock-controller-0a43a72c-63c9-457e-8732-f5948c54d438.ipynb
[W 21:00:18.899 NotebookApp] delete /mock-controller-0a43a72c-63c9-457e-8732-f5948c54d438.ipynbInfo 2021-04-15 21:00:18: Python Daemon (pid: 3170): write to stderr: 


Info 2021-04-15 21:00:20: Finished waiting for idle on (kernel): a35d02fe-126e-4367-80f8-952695a7d7a7 -> idle
Info 2021-04-15 21:00:26: Submitting code for b010c6de-75cd-4467-8423-79fa5b8e6fcc
Info 2021-04-15 21:00:26: Kernel switching to busy
Info 2021-04-15 21:00:26: Kernel switching to idle
Info 2021-04-15 21:00:26: Finished execution for f0e33c05-9f21-4c2f-9f85-4f1c356ee8c2

**Comment by rchiodo** [comment]
Hmm, that's not showing anything going wrong, so not sure what the problem is. We'll have to try with Ubuntu 18 to see if we can repro.

**Comment by darim1** [comment]
Hey, thanks for this instant reaction! Please let me know if I can assist!!

**Comment by darim1** [comment]
@rchiodo  : I think the integration of code cells, debugger and shell generally works nicely out of the box. Loosing the history, however, is tedious.  Is there any workaround workflow which brings back the command history? Do you suggest temporal integration of  ipython instead?

**Comment by rchiodo** [comment]
There's no workaround, it's a bug that needs to be investigated. It works fine on other OS's so not sure at the moment what the problem is.
