### ISSUE TITLE
Bad / Slow Linter Highlighting

### ISSUE THREAD

**Issue by basedrhys** [microsoft/vscode-jupyter#7117]
Issue Type: <b>Bug</b>

The linter doesn't update or takes a long time to update. This results in warning/error lines all throughout my code, even though the code is correct (and I can run the code cell).

![image](https://user-images.githubusercontent.com/21359576/129364931-5c907f8c-0e20-45fc-8444-f4b8800d11b9.png)

![image](https://user-images.githubusercontent.com/21359576/129365188-f70ef336-d825-43f0-abd6-5e7a34088e1b.png)

Steps to Reproduce:
1. Work in notebook for ~10 minutes. Doesn't get triggered by anything in particular apart from the usual editing one would do in a python notebook.

Extension version: 2021.8.1195043623
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id b1d2db05-53c6-43ee-954b-b20bd793fe8b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723cf:30351748

```

</details>

**Comment by greazer** [comment]
Thanks for the feedback, @basedrhys! We'll take a look.

**Comment by rchiodo** [comment]
I believe this should be fixed now. There were problems with notebooks with cells other than code in them.
