### ISSUE TITLE
The collapse jupyter doesn't show run time status.

### ISSUE THREAD

**Issue by DaiZack** [microsoft/vscode-jupyter#7120]
![image](https://user-images.githubusercontent.com/45176371/129406954-d26d3f98-da84-48ad-8810-09343bf2134f.png)

The collapsed cell doesn't show whether the code is finished, which is very bad. I have to expand the cell to check every time.

Also, when I change the setting to cancel the collapse, it doesn't work. The cells still collapse by default, even after restarted. 
![image](https://user-images.githubusercontent.com/45176371/129407126-e29b2a82-e3da-43eb-b9d0-0cc6b1e6c3f0.png)

**Comment by greazer** [comment]
Thanks for the feedback, @DaiZack. The latest insiders build shows a progress indicator for collapsed executing cells now. There's also this bug: https://github.com/microsoft/vscode/issues/130811

Therefore, closing as a dupe.
