### ISSUE TITLE
Running all cells should clear the output as well as executino count when running the whole notebook

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7123]
Open an existing notebook:
* RUn all cells
* Watch how execution order of all is cleared, but output is not cleared

In Jupyter all outputs of all cells are cleared when we start running all cells in a notebook

**Comment by DonJayamanne** [comment]
Closing this issue as no one has brought this up

**Comment by tabacof** [comment]
I think this is a relevant issue, also bothers me. I have a lot of experience with Jupyter and Databricks notebooks and the VSCode experience is a bit confusing to me.
