### ISSUE TITLE
I misread the modal dialog about installing ipykernel 6. I thought it was telling me to install with pip.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7125]
Guessing many people may misread this message that appears when you click run-by-line and ipykernel 6 isn't installed in the current kernel environment. I think we should more clearly indicate whether the user should run "pip" or "conda" to install manually.

[Window Title]
Visual Studio Code - Insiders

[Content]
Ipykernel 6 is needed for debugging, click Install to continue. Or you can run 'pip install ipykernel==6.0.3/conda install ipykernel=6'

[Install] [Cancel]

**Comment by greazer** [comment]
Also, I'm thinking we shouldn't be specifying a specific build of ipykernel. What if there's a security problem found in ipykernel 6.0.3?

**Comment by roblourens** [comment]
Hopefully more and more people have ipykernel 6+
