### ISSUE TITLE
I installed ipykernel 6 to try run-by-line, but I don't want to have to restart the kernel.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7127]
I used run-by-line and allowed VS Code to install ipykernel 6. I saw it install successfully in the terminal. However, I still can't use run-by-line. Says I still have to install ipykernel 6.

This is obviously because I need to restart the kernel. Which sucks, but many users may not understand this. If anything, we might want to show a non-modal notification after the install that indicates that the kernel must be restarted. Either that, or the initial modal dialog box should tell the user that this will have to happen. Otherwise, they go through all this waiting to get ipykernel installed, only to find out that they still can't use it.

**Comment by roblourens** [comment]
Would be ideal if we had the same experience here for running vs debugging. I understand how it's different for debugging because of the ipykernel issue.

**Comment by roblourens** [comment]
Hopefully less relevant as more people have ipykernel 6 already
