### ISSUE TITLE
VS Code does not show correct environment/interpreter in bottom left

### ISSUE THREAD

**Issue by gmnenad** [microsoft/vscode-jupyter#713]
I have this problem while using ipynb notebook, so I opened this issue under 'notebook editor', but this is probably general Python extension issue.

Initial problem that I had was "no module named pandas" error when I knew pandas was installed in selected environment ( selected either by Ctrl+Shift+P Python: Select Interpreter, or by clicking bottom left and doing same ).

Actual problem appears to be that VS Code did **not use** environment that I selected and that is shown in bottom left.  I found similar issue at microsoft/vscode-python#8085 , with suggestion that VS Code decided to use another environment  because selected one did not support jupyter notebook. That is also questionable here (since I tried to select several different environments , all with installed notebook ) and I tried suggestion to manually rename ipykernel with "python -m ipykernel install --user --name <myenv>" in order for it to show under "jupyter kernelspec list", but it didn't help. Eventually I used  sys.path ( since sys.version was same for multiple environments ) to determine that VS Code is using different environment from one displayed - and when I installed pandas in that environment, it worked.

But issue I'm opening here is not about why VS Code decided not to use environment that I selected, nor it is about jupyter notebook.  It is about  : 
1) VS Code can use **different Python environment**  than one displayed in bottom left - if, from any reason, VS Code decided not to use that environment, **it should change what is displayed in bottom left**.
2) VS Code can **silently** decide to use different Python environment  - if, from any reason, VS Code decide to use different environment than one selected by user, **it should at least display some warning**.

Above would avoid lot of misunderstandings and allow easier error cause detection.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by GitProfAn** [comment]
Hello, finally - how to set the desired python interpreter in VS code to work inside Jupyter Notebook?

![python_right_interpreter](https://user-images.githubusercontent.com/48450635/109417314-25d9f200-79d4-11eb-8a6f-64d98828de30.png)

**Comment by joyceerhl** [comment]
@GitProfAn are you hoping to use Python 3.8.8 as your kernel and selected interpreter? If so you can click on either of those to choose 3.8.8 as the default.

**Comment by GitProfAn** [comment]
@joyceerhl No, I would like to know how to set python 3.9.2 inside Jupyter Notebook to VS code (if you have more than one installed python interpreter - in my case 3.8.8 and 3.9.2). As we can see the bottom left and upper right settings do not provide python 3.9.2 inside Jupyter Notebook.

**Comment by GitProfAn** [comment]
No changes in the latest VS Code release.

Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 6.3.9600

**Comment by joyceerhl** [comment]
@GitProfAn I think you are asking about why `!python -V` outputs 'Python 3.8.8' while the kernel indicator says 'Python 3.9.2'. I believe !python -V tells you which Python executable is first on your PATH, and not the Python interpreter that we are using for the Jupyter notebook. If you run the following code in a Jupyter notebook cell, it should tell you which Python interpreter we are using for the Jupyter notebook:

```
import sys
print(sys.executable)
```

If the output of the code above does not match what is displayed on the kernel selector please let us know.

**Comment by GitProfAn** [comment]
@joyceerhl thanks for explanation. That's really it. Yes, I actually have Python 3.9.2

**Comment by joyceerhl** [comment]
Great. Thanks for confirming :)

**Comment by CooperData** [comment]
I know this is closed, but I am facing the same problem and I am not sure what to do to make sure the python on the notebook is the one I need. As you can see from the image, the python version on the notebook is 3.7.3, and the sys executable is my base environment. I have changed to another env using the left bottom prompt to my desired environment att-rest, and I have also changed it on the top right. After clicking on the top right, there is a quick message saying something like "switching to Python 3". I have restarted the vscode multiple times, and I cannot get it to load the correct interpreter. This is a remote connection.

![image](https://user-images.githubusercontent.com/1518908/113058521-3c629d00-917c-11eb-918c-1986429dc645.png)

**Comment by rchiodo** [comment]
@CooperData can you log a new issue?

**Comment by CooperData** [comment]
Sure thing @rchiodo
