### ISSUE TITLE
No indication that kernel is starting when it's starting...

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7134]
Version: 1.60.0-insider (user setup)
Commit: 58454f7bec838f79fe2422ab5914419147d82e40
Date: 2021-08-13T05:15:29.421Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

v2021.8.2027072902

1. Open a notebook
2. Select a kernel other than whatever it defaulted to, using the kernel selection button at the top right.
3. Run the first cell

I'm seeing no notification anywhere that a kernel is starting. It does start eventually and work though. Looks like step 2 is most important to be done. At least I DO see the kernel starting message if the notebook didn't have a good default kernel to start and I just run the first cell and choose the kernel from that initial popup.

**Comment by DonJayamanne** [comment]
Should be fixed now, closing so this gets validated

**Comment by IanMatthewHuff** [comment]
We get this message now right from the start of execution. Verified.
![image](https://user-images.githubusercontent.com/812783/151628010-6d313440-c54b-4883-90ad-6af381e459d7.png)
