### ISSUE TITLE
Auto completion is suggesting completely invalid suggestions.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7136]
Version: 1.60.0-insider (user setup)
Commit: 58454f7bec838f79fe2422ab5914419147d82e40
Date: 2021-08-13T05:15:29.421Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Jupyter: v2021.8.2027072902
Pylance: v2021.8.2-pre.1

1. Create a new ipynb that has nothing to do with another that exists in the same workspace.
2. In the new notebook type 
```python 
import pandas as pd
```

Notice that ```pd``` gets offered to be autocompleted as one of the files in the workspace. This is totally invalid. This doesn't happen in a py file in the same workspace following the same procedure. 

I'm also not sure whether this bug is a Jupyter or  PyLance problem, though I'm guessing Jupyter at this point.

![recording (6)](https://user-images.githubusercontent.com/11685408/129452889-4ced427e-3ef6-4a94-89c3-dd97a54b74c7.gif)

**Comment by greazer** [comment]
The autocomplete is coming from the Jupyter Kernel. Would be great to find a way to make this a more reasonable experience. 

Perhaps only accept jupyter kernel autocomplete when specific characters are typed... like '.' or "'", etc.

**Comment by rchiodo** [comment]
Autocomplete from jupyter outside of a string that returns file paths seems useless. That would alleviate this problem.

We could filter based on if inside a string or not.
