### ISSUE TITLE
Always get "This editor is deprecated" banner on one computer

### ISSUE THREAD

**Issue by jgriffitts** [microsoft/vscode-jupyter#7139]
This is a revisit of issue #7021 which has been closed as "working as designed", but I don't think that the person who closed it has fully understood the problem. The discussion thread on that issue describes exatly what I'm seeing.

Since the most recent 1.59.0 update, one of my computers insists on running the old Jupyter editor, with a message at the top of the screen: "This editor is deprecated and we'll remove it after 1.59 of VS Code."

My other computer seems to be using the new editor properly. I've done some poking around with settings and perused the release notes, but I haven't found any hint as to why this computer defaults to the deprecated editor. Both computers have the Jupyter extension enabled and not "Jupyter (deprecated)". Both are running Windows 10 64-bit.

BTW, the deprecation message is black on dark gray, and illegible unless I use the mouse to select the text.

## Environment data

-   VS Code version: 1.59.0
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS Windows 10 64-bit version 10.0.19042
-   Python version 3.7.11, miniconda 4.10.3
-   Type of virtual environment used: conda 
-   Jupyter server running: Local 

## Expected behaviour
I should see the new Jupyter editor when I open a .ipynb file.

## Actual behaviour

When I open a .ipynb file I get the old editor and the deprecation banner with no indication of how to get the new editor. If I create a new .ipynb notebook I get the new editor until I close the file and reopen it.

## Steps to reproduce:

The content of the notebook file doesn't seem to be significant, nor does it matter whether we are in a workspace environment. Opening any notebook seems to give the same result. The problem is evident without any action after opening the file.

## Logs

[log2.txt](https://github.com/microsoft/vscode-jupyter/files/6987139/log2.txt)
[log_whenWorking.txt](https://github.com/microsoft/vscode-jupyter/files/6987141/log_whenWorking.txt)

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel 
Log file from Output/Jupyter is attached. For comparison, the log from the computer that works properly is also attached as log_whenWorking.txt. They are substantially different. I observe that the *working* version seems to be making use of a legacy 32-bit Python 2.7 environment (Py27_32). when it executes: <code>
C:\ProgramData\Miniconda3\envs\Py27_32\python.exe -m pip list
</code>

</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by jgriffitts** [comment]
A good solution to this was posted [here in issue 7021](https://github.com/microsoft/vscode-jupyter/issues/7021#issuecomment-899413080). It appears that this is a configuration option that was somehow corrupt on one of my computers. I spent considerable time searching for such an option but never found it -- perhaps this needs a mention in the release documentation.

To summarize: 
1. right-click on the .ipynb file in the explorer window (in the directory file list, not under "Open Editors").
2. pick "Open With"
3. pick "configure default editor" at the bottom of the list
4. pick "Jupyter Notebook"

**Comment by greazer** [comment]
@jgriffitts, thanks for the feedback. You should be able to adjust this via changing your editor association in the settings.json.

Please find...
```json
"workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook-ipynb"
    },
```
and change it to...

```json
"workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
    },
```

**Comment by DavidKutu** [comment]
@jgriffitts, please let me know if greazer's comment fixes your issue.

**Comment by jgriffitts** [comment]
I had already fixed it per [my comment earlier](https://github.com/microsoft/vscode-jupyter/issues/7139#issuecomment-899689218)

I did observe that the "configure default editor" action changed workbench.editorAssociations to jupyter-notebook as you describe. I don't know what the old value might have been. If it's important I could try to dig up a backup.

**Comment by DavidKutu** [comment]
@jgriffitts, don't worry about it. On our next release the custom editor should be gone and the setting fixed.

**Comment by innovationmech** [comment]
> @jgriffitts, thanks for the feedback. You should be able to adjust this via changing your editor association in the settings.json.
> 
> Please find...
> 
> ```json
> "workbench.editorAssociations": {
>         "*.ipynb": "jupyter-notebook-ipynb"
>     },
> ```
> 
> and change it to...
> 
> ```json
> "workbench.editorAssociations": {
>         "*.ipynb": "jupyter-notebook"
>     },
> ```

it works ,thanks for your help 👍

**Comment by yousaf1951** [comment]
Thanks  for your help @jgriffitts .

I am relieved from that annoying banner!!
![image](https://user-images.githubusercontent.com/49249448/130326187-e551eb9f-74c9-4518-80d6-ec873590ca94.png)
