### ISSUE TITLE
Run Above, Run Below

### ISSUE THREAD

**Issue by gdianto** [microsoft/vscode-jupyter#7146]
Issue Type: <b>Feature Request</b>

I would like to see both "Run Below" and "Run Above" options on each cell (#%%)

Extension version: 2021.8.1105858891
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.4.0-72-generic snap
Restricted Mode: No

**Comment by DavidKutu** [comment]
Thanks for the issue @gdianto.

You can do that with the setting `jupyter.codeLenses`. 
Just set it to: `jupyter.runcell,  jupyter.runallcellsabove, jupyter.runcellandallbelow, jupyter.debugcell`

With that, the code lenses will appear on every cell. Let me know if that helps.

**Comment by greazer** [comment]
Closing. See @DavidKutu's comments above.
