### ISSUE TITLE
Codespace/safari: zoom in doesn't work in plot view

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#7147]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): 2021.8.2027072902
-   OS (Windows | Mac | Linux distro) and version: Mac 
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

* Click on Expand Image to open a plot in Plot View custom editor
* Zoom In/Out buttons don't work
* No log in console

**Comment by greazer** [comment]
This is by design. Confusing, but not worth addressing right now.
