### ISSUE TITLE
Codespace: Pylance diagnostics out of date

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#7148]
## Environment data

-   VS Code version: 1.60-Insiders
-   Jupyter Extension version (available under the Extensions sidebar): 2021.8.2027072902
-   OS (Windows | Mac | Linux distro) and version: Mac 
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

<img width="542" alt="image" src="https://user-images.githubusercontent.com/876920/129493317-dbfe6890-8b29-40eb-bcbb-cf4b2d5d0223.png">

**Comment by rchiodo** [comment]
This should be fixed with the latest build of the python extension.
