### ISSUE TITLE
Interactive Window: Variable Explorer issues

### ISSUE THREAD

**Issue by hunterdanielsmith** [microsoft/vscode-jupyter#7153]
Using #%% in .py files, I've had issues with the interactive window variable explorer.

Since the new update: the variables do not load consistently. I often see "no variables defined" after running my code. 

Also, I dislike that the variable explorer tab now opens in the bottom panel. And it seems I can only view one variable at a time now.

**Comment by greazer** [comment]
Thanks! This is a dupe of #6993
