### ISSUE TITLE
`Esc` and `Ctrl+U` no longer clear the contents of the interactive window input box 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#7157]
Originally reported by @greazer 

Webview interactive window had `esc` or `ctrl+u` to clear the input box contents. Now that the interactive window supports VS Code- and extension-contributed keymaps, this will cause keybinding conflicts. We have at least two options:

1. Similar to https://github.com/VSCodeVim/Vim/pull/6980, add code to Vim extension to route to the VS Code clear command 
2. Introduce an `interactive.input.clear` command that is by default not bound to any keymaps, and let users configure it themselves
3. Introduce the command and prompt the user somehow

**Comment by greazer** [comment]
Also consider adding a clear box on the interactive window input box so users can clear with a mouse.

**Comment by andycraig** [comment]
Hi, I like the sound of an `interactive.input.clear` command as it would allow me to bind to <kbd>Ctrl-C</kbd>, which is the command I use the most often for clearing the input across various REPLs.

**Comment by joyceerhl** [comment]
@andycraig We've implemented this command for the native interactive window, should be available in tomorrow's Insiders and the upcoming August Stable release. You can then add a keybinding like so:

```
{
  "key": "ctrl+c",
  "command": "interactive.input.clear",
  "when": "resourceScheme == 'vscode-interactive'"
}
```

**Comment by andycraig** [comment]
@joyceerhl Great, thank you very much!
