### ISSUE TITLE
ipywidget value not updated properly in VS Code

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-jupyter#7163]
## Environment data

-   VS Code version: 1.60.0-insider (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2027072902
-   Python Extension version (available under the Extensions sidebar): v2021.8.1105858891
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.22000
-   Python and/or Anaconda version: python 3.9.5 conda 4.10.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Widget values are updated and observable from other cells

## Actual behaviour

Widget values are not updated 

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

**Cell 1**
```python
siteTextBox = widgets.Dropdown(
    options=['site1', 'site2'],
    value='site1',
    description='Site:',
    disabled=False,
)
```

**Cell 2**
```python
print(siteTextBox.value)
```

:bug: => after running both cells, modifying the dropdown in the output to `site2`, re-running cell 2 results in printing `site1`

This works as expected when running in jupyter natively

**Comment by DavidKutu** [comment]
Thanks for the issue @sbatten. I was unable to repro, just to be sure, this is what you tried right?
![7163](https://user-images.githubusercontent.com/20347396/129652257-313681e7-dff7-4920-bf3f-15e529393e70.gif)

**Comment by sbatten** [comment]
Yep, and it does not reproduce on today's insiders, perhaps core was at fault? Not sure.

**Comment by greazer** [comment]
Closing due to not having a repro. Please reopen if you can find one.
