### ISSUE TITLE
If you could manully switch to window with Interactive python in vs-code when "Run Cell" is pressed...

### ISSUE THREAD

**Issue by TheGrowingPlant443** [microsoft/vscode-jupyter#7165]
If you run a python script and have the interaktive window in a seperate window and you press ```Run Cell``` it will automaticly switch over to the interactive window. My feature request is that this is made so you can choose manully to switch to see the output. Why do I request this it is because with live share in vs-code you can share your own file with yourself and then have the interactive window and code on two seperate screens except that when you press ```Run Cell``` your code view is automaticly switched to the interaktive window. 

Here is a video of it:  <https://youtu.be/rs0S41mnpZg>

**Comment by IanMatthewHuff** [comment]
@TheGrowingPlant443 Thanks for the suggestion (and the video to make things clear). Just to check would you see this as something that you would do from time to time, or would you want this as an "all the time" on setting?

**Comment by TheGrowingPlant443** [comment]
Hi @IanMatthewHuff,

Thanks for the quick response. I would use this as an "all the time" on the setting, because I rarely have less than 2 screens in front of me. If I only have 1 screen, then I would have the interactive window in a split screen with the code instead of a separated window from the code. This is what can be seen in the picture. In the case of 1 screen, it would make no differens whether it was set to automatically or manually switch. 

![1 screen](https://user-images.githubusercontent.com/57142309/129846923-ad504b2c-c681-405b-a6ea-2d7315842354.PNG)

**Comment by greazer** [comment]
Thanks for your feedback. This issue should be fixed in the latest build of VS Code. Version 1.59 or later.
