### ISSUE TITLE
Kernel session cannot generate requests after Kernel restart from cell (IPython.Application.instance().kernel.do_shutdown(True))

### ISSUE THREAD

**Issue by leiterenato** [microsoft/vscode-jupyter#7167]
## Environment data

-   VS Code version: Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z (1 wk ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.6.0

-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1195043623
-   Python Extension version (available under the Extensions sidebar): v2021.8.1105858891
-   OS (Windows | Mac | Linux distro) and version: MacOS 11.5.1
-   Python and/or Anaconda version: Python 3.9.5 (also tested with 3.9.6, 3.8.10 and 3.7 - same issue)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): tested with conda and venv
-   Jupyter server running: The problem happens both locally and in a remote setup (remote VM)

## Expected behaviour

I need to restart my kernel after a `pip install`.
I need to execute the following code and restart my kernel, without loosing connectivity to it.

```
import IPython  
app = IPython.Application.instance()  
app.kernel.do_shutdown(True) 
```

## Actual behaviour

After executing the `app.kernel.do_shutdown(True)` I receive the following message:

```
Error: Session cannot generate requests
Error: Session cannot generate requests
at w.executeCodeCell (/Users/renatoleite/.vscode/extensions/ms-toolsai.jupyter-2021.8.1195043623/out/client/extension.js:90:325139)
at w.execute (/Users/renatoleite/.vscode/extensions/ms-toolsai.jupyter-2021.8.1195043623/out/client/extension.js:90:324460)
at w.start (/Users/renatoleite/.vscode/extensions/ms-toolsai.jupyter-2021.8.1195043623/out/client/extension.js:90:320276)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async t.CellExecutionQueue.executeQueuedCells (/Users/renatoleite/.vscode/extensions/ms-toolsai.jupyter-2021.8.1195043623/out/client/extension.js:90:334803)
at async t.CellExecutionQueue.start (/Users/renatoleite/.vscode/extensions/ms-toolsai.jupyter-2021.8.1195043623/out/client/extension.js:90:334343)
```

If I restart the kernel using the "Restart" button from the UI interface, I still receive the same message.
I can only get my environment running again if I select another kernel and then select the original kernel again.

## Steps to reproduce:

1. Create an empty notebook and open in VScode (with the extension enabled).
2. Enable the kernel
3. On the first cell type a `print('Hello World')` to make sure it is working
4. On the second cell execute the following code:

```
import IPython  
app = IPython.Application.instance()  
app.kernel.do_shutdown(True) 
```
5. Include a new cell with a `print('Hello world')` to see the error message.

## Logs

Please see the attached files.
[kernel_restart_OK.txt](https://github.com/microsoft/vscode-jupyter/files/7000233/kernel_restart_OK.txt)
[cell_exec_FAIL.txt](https://github.com/microsoft/vscode-jupyter/files/7000234/cell_exec_FAIL.txt)
[requirements.txt](https://github.com/microsoft/vscode-jupyter/files/7000235/requirements.txt)

**Comment by leiterenato** [comment]
Follows a quick video to demonstrate this behavior.
https://user-images.githubusercontent.com/277946/129734512-1d72332a-c926-4e21-b79c-ddf3468af401.mov

**Comment by DonJayamanne** [comment]
Thanks for filling this issue, I'm and to relocate this at my end.

**Comment by leiterenato** [comment]
Thank you. Let me know if you need more information.

**Comment by DonJayamanne** [comment]
As a temporary work around, you can close the notebook and re-open it, that will work.
I'll have a fix before the end of this week for you in VS Code Insiders (hope you can use VS Code insiders until this goes into stable)?

**Comment by leiterenato** [comment]
That's great! Thank you very much,
Cheers

**Comment by momt99** [comment]
I'm not sure this is the same problem or not. I get this error when some error happens in my code and instead of reporting the stack trace, the cell finishes successfully. But I'm not able to run any cell afterward and get the message included above.

**Comment by DonJayamanne** [comment]
@momt99

Please could you file a separate issue. looks like you have some code in the cell that's causing the kernel to crash/die.

**Comment by DonJayamanne** [comment]
Closing this issue as this has been fixed, and the fix is now avaialble in the insiders version of the extension (install VS Code insiders to get the insider version of the extesnion).

**Comment by IvanPalm** [comment]
@DonJayamanne 
I had stumbled across the error reported here, so I got the latest version to overcome it.
I'm now using `code-insiders 1.61.0-insiders` with Jupyter `v2021.9.1001208778` on Ubuntu 20.04, and the error `Kernel is dead` occurs.   
Any suggestion on the version to use?

Thank you for the great work!

![Screenshot from 2021-09-08 09-18-26](https://user-images.githubusercontent.com/46936982/132464630-da2d3165-5ef2-410a-9fbb-b2fc4500eb96.png)

**Comment by DonJayamanne** [comment]
@IvanPalm
Play could you file a new issues with sample code that causes the kernel to crash. This issue addresses restarting the kernel after it has died.

**Comment by IvanPalm** [comment]
I just got back to the matter to file the issue but I could not replicate the error. 
I tested on Code Insiders `1.61.0-insiders` with Jupyter `v2021.9.1001216636`, `v2021.9.1001208778` as well as on Code `1.60.0` with Jupyter `v2021.8.2041215044`. The outcome is the same I got when I landed to this conversation: `Error: Session cannot generate requests`. I will file a new issue if/when the error occurs on other codes.

**Comment by Wang-Chbo** [comment]
I have the same issue.
If I run the code with `Jupyter v2021.8.2041215044`,when I run this demo(https://tensorflow.google.cn/text/tutorials/transformer?hl=zh_cn),`Error: Session cannot generate requests` will rise.
So I use an old version `Jupyter`, and this issue will disappear

**Comment by DonJayamanne** [comment]
@wang-chbo
Part could you file a separate issue, with the os, python version & other information including  the sample code you have mentioned. Oh yes, please do included the logs as well.

**Comment by greazer** [comment]
I was able to restart a kernel after it had died. Both from the original repro as well as from a separate one that killed the kernel externally.
