### ISSUE TITLE
Can the "data viewer" in VS Code interpret URL?

### ISSUE THREAD

**Issue by jhmlam** [microsoft/vscode-jupyter#7170]
Say, you have a column of bonafide URLs, 
is it possible to allow the "Follow Link" function as mouse hover to the link as like when a URL shows up in part of the code?
Thanks.

**Comment by IanMatthewHuff** [comment]
@jhmlam Thanks for the suggestion. Makes sense to me as well as something that we can consider.

**Comment by DonJayamanne** [comment]
Thanks for the suggestion, however there haven't been any upvotes on this issue
hence closing this for now
