### ISSUE TITLE
How to make the color of the coordinate axis consistent with the background color of the picture instead of the background color of the cell

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/vscode-jupyter#7181]
# version
版本: 1.59.0 (user setup)
提交: 379476f0e13988d90fab105c5c19e7abc8b1dea8
日期: 2021-08-04T23:13:31.568Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT ia32 10.0.18363

![image](https://user-images.githubusercontent.com/33288114/129821274-8a3e48d2-9fd4-43d6-915e-e835b57e330b.png)
The color of the axis should not be the same as the background color of the cell，this really affects the visual experience.

**Comment by rchiodo** [comment]
Thanks for the bug. 

The colors there are provided by matplotlib and can be controlled by changing the style of the plot. However we should be putting a white background behind all plots - like so:

![image](https://user-images.githubusercontent.com/19672699/129933891-6ebb3c2f-3cf2-4754-baf1-c6c6b739378a.png)

However I believe this requires a certain version of matplotlib (it will indicate to us in the output whether the plot is 'dark' or 'light'). 

What version of matplotlib are you using?

Or can you share your notebook?

**Comment by CatNofishing** [comment]
@ My jupyter is the newest version， but when you choose  other mime type like  image/svg   ，there will be this problem.
![image](https://user-images.githubusercontent.com/33288114/130018450-504cc0e8-65df-4cc0-a16a-98c2177bb9cc.png)

**Comment by rchiodo** [comment]
This works fine for svg if you pick the 'jupyter' renderer. Otherwise, yes VS code doesn't know about the matplotlib theme type. I don't think VS code will be making special changes for matplotlib. You should use the jupyter renderer.

**Comment by CatNofishing** [comment]
😥
