### ISSUE TITLE
Jupyter Interactive | Delete Cells without expanding it (July update issue) | Asking for roll back

### ISSUE THREAD

**Issue by abd-shouman** [microsoft/vscode-jupyter#7188]
One of the most convinet features that Jupyter on VS Code had was the ability to delete cells easily. 
It helps keeping the interactive section clean (deleteing cells that produces error, etc).

However, after July's update this has become a cumbersome/inconvient process. 
Now you have to first expand the cell then delete it

To reproduce the issue following these steps

1. Add a line of code in a .py file (e.g.)
```
# %%
from statsmodels.graphics.tsaplots import plot_acf
```
2. Run the cell 
3. Expand the cell (new july update)
4. Delete the cell

The attached image show how it looks before and after expansion
The option to delete the cell can only be viewed after expansion

** 
![before and after cell expansion](https://user-images.githubusercontent.com/4815689/129869336-1e2c9c66-fa10-4177-8267-22dd597f34af.png)

I am not sure why this was changed in the latest update.
I hope the ability for deleting a cell can be rolled back

**Comment by vzhangCM** [comment]
Same issue for me. I downgrade the jupyter extension to get the feature back. It will be great if the new version can make the delete button easily accessible or add a shortcut for it.

**Comment by abd-shouman** [comment]
@vzhangCM  I had to dowgrade as well. In general the new update for jupyter felt too cluttered and confusing. (The dataviewer is now buggy as well but I will open a new isue for that one)

**Comment by joyceerhl** [comment]
@rebornix Would it be possible to expose a third notebook.cellToolbarVisibility option "always" or "show", or introduce a separate setting for the interactive window?

![image](https://user-images.githubusercontent.com/30305945/129935517-0e2bd908-94dc-4353-a8b4-1bac28487deb.png)

@abd-shouman Sorry to hear that the update is cluttered and confusing. Would you mind sharing what aspects of it are frustrating for you so we can improve it? We have also just fixed a bug with the variable explorer in the recovery build that we published yesterday https://github.com/microsoft/vscode-jupyter/issues/6993 Please let us know if you encountered a different problem and we can get that fixed as well.

**Comment by joyceerhl** [comment]
We now render the cell toolbar when a cell is collapsed in Insiders, and this change will ship out in the upcoming Stable release:
![image](https://user-images.githubusercontent.com/30305945/129984969-fecd985b-03dd-4a71-8246-97140d47afd2.png)

In addition, you can change `"notebook.cellToolbarVisibility": "hover"` so that you don't need to set focus to the target cell to delete it.

**Comment by abd-shouman** [comment]
@joyceerhl #6993 is the issue that I wanted to report. Glad to see it fixed.

Regarding why the update felt cluttering and confusing, I would like to raise two points

1. I prefered having a seperate variable explorer for each interactive window, as it felt more organized. I am also not sure if the #6993 fix will also fix the issue having two variable with the same name in two different interactive windows where the explorer stops refereshing.
2. Not needing to focus on the cell to delete might be a good step forward (but I still have to collapse the cell). I do believe that having the mini-tool bar was a great convient (check attached image). 
For example, let's say I am using the interactive code to test something and it does not work, I have instant access to the delete button where I can just remove it. This for me was a clear winner over traditional Jupyter Notebooks. It allows me to test and delete cells instantly so I focus only on things that actually work. However, having to focus (or even hover) feels like an added step, and givne that I delete cells quite often this can be quite frustrating.

![VS Code cells easy access](https://user-images.githubusercontent.com/4815689/130033343-114bc805-1269-476d-9bd8-ba65d5b5b650.png)

**Comment by joyceerhl** [comment]
@abd-shouman Thank you for providing feedback, we really appreciate you taking the time to help us improve this tool.

> The arrow on the left (as show below) felt more intuitve to me. When I saw it, I was able to tell that this a cell that can be expand, unlike the new used logo.

This is good feedback. We are tracking that same concern in https://github.com/microsoft/vscode/issues/130622. /cc @greazer @rebornix

**Comment by abd-shouman** [comment]
@joyceerhl great, hope to see that fixed. And I just would like to highlight that I see the ability to quickly delete a cell as a crucial point as well

**Comment by joyceerhl** [comment]
@abd-shouman By any chance were you able to give the hover workaround a try, and does it work for you? Other users have found that it is sufficient https://github.com/microsoft/vscode-jupyter/issues/7250#issuecomment-906746971 and we would like to make sure we aren't making unnecessary changes.

**Comment by abd-shouman** [comment]
@joyceerhl thanks for getting back to me. I started using it today. Will give it a try and update this comment later

**Comment by joyceerhl** [comment]
With https://github.com/microsoft/vscode/pull/132834, the interactive window will always display the cell toolbar on hover, so you won't need to change the setting yourself, and you won't have to click on a cell to delete it. Hovering will bring it up instead. You can also use the `notebook.cellToolbarLocation` setting (values are 'left' and 'right') to change whether the toolbar appears on the left or right.

**Comment by abd-shouman** [comment]
@joyceerhl 
I tested the latest update and it seems that the following was fixed/enhanced

1. Cell view is more intuitive. Weird icon on the left was removed and no need to double click to see the cell content or the cells toolbar
2. Interrupt was fixed and now works as expected
3. Changing toolbar visibility to hovering as mentioned in your comment (https://github.com/microsoft/vscode-jupyter/issues/7250#issuecomment-906739023) imporves the experince, I also changed the tool bar location to left (https://github.com/microsoft/vscode-jupyter/issues/7250#issuecomment-904900826) which helps even more. 

However, I would argue that it's still a bit inconvienent and it would be better if there is an option for toolbar visibility to be always on. _**Would this be an acceptable feature request?**_

I faced some other issues but there are currently open issues for it (https://github.com/microsoft/vscode-jupyter/issues/7366) and (https://github.com/microsoft/vscode-jupyter/issues/7468)

**Comment by joyceerhl** [comment]
> Would this be an acceptable feature request?

Yes absolutely, please feel free to file it on https://github.com/microsoft/vscode as that's where the UI for the IW is implemented. 

> Trying to change the interactive window to be more like a native notebook seems like a weird strategy for me as someone who switched from notebooks to VS Code interactive window because it is nothing like native notebooks.

The IW currently inherits many aspects of the native notebooks experience because it's built on the VS Code notebooks ecosystem. Appreciate your continued feedback as we continue to fine tune the native interactive window experience. We're aware of usability issues with the new variable explorer experience, particularly as it relates to the interactive window. We're currently collecting that feedback in https://github.com/microsoft/vscode-jupyter/issues/7287 and I've included a reference to the feedback you've provided in this thread. FWIW, VS Code has also considered exposing a VS Code Table API that the Jupyter extension might then be able to adopt for the variable explorer, so the long term experience for the variable explorer may continue to evolve.

**Comment by abd-shouman** [comment]
Thanks for the response, I opened a new feature request as suggested (https://github.com/microsoft/vscode/issues/133067) and hopefully it gets considered. The way I see it though, is that this is more of a request for an old behaviour that just worked fine. Thanks again.
