### ISSUE TITLE
Cython code outcome is not displayed

### ISSUE THREAD

**Issue by scsleal** [microsoft/vscode-jupyter#7192]
## Steps to reproduce:
try to run the following code lines in cells:
```
%load_ext Cython
```
```
%%cython

cdef int a = 0
for i in range(10):
    a += i
print(a)
```

## Environment data
-   VS Code version: 1.60.0-insider
-   Commit: 0214d59846f265d9e50f53b61e2267407d81cbfb
-   Jupyter Extension version: 2021.8.1055544705
-   Python Extension version: 2021.7.1060902895
-   OS and version: Windows_NT x64 10.0.19041
-   Python version: 3.7.10 64-bit
-   Type of virtual environment used: conda
-   Jupyter server running: Local
-   Electron: 13.1.8
-   Chrome: 91.0.4472.164
-   Node.js: 14.16.0
-   V8: 9.1.269.39-electron.0

## References
https://cython.readthedocs.io/en/latest/src/quickstart/build.html

**Comment by rchiodo** [comment]
Thanks for the bug.

My guess is that the kernel is returning an output stream for Cython that we don't currently understand.

**Comment by rchiodo** [comment]
VS code behaves the same for me as jupyter does.

The first time I run a cell, I get this:

![image](https://user-images.githubusercontent.com/19672699/130302456-0c517b7d-2110-42ee-ab40-9e338b0f0bcc.png)

If I run the cell a second time, it doesn't return any output:

![image](https://user-images.githubusercontent.com/19672699/130302468-b32f900b-35e1-4378-a31e-e1d387e0a8f1.png)

Jupyter classic behaves the same way.

Annotate works for me as well:

![image](https://user-images.githubusercontent.com/19672699/130302533-bbc679b9-348a-497d-907b-33f458072dcf.png)

On the second run it's much faster but also doesn't print the output.

I believe this would be a bug/known design of Cython then.
