### ISSUE TITLE
Native interactive window always show dataframe shape

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-jupyter#7195]
When printing out a dataframe, the new native interactive window does not show the shape unless the dataframe is too large to display in its entirety. I assume this behavior is intentional but I can't see the rationale behind it and would like to suggest always showing dataframe shapes.

Minimal example:

```py
# %%
import numpy as np
import pandas as pd

# %%
pd.DataFrame(np.arange(100).reshape(10, -1))


# %%
pd.DataFrame(np.arange(10000).reshape(10, -1))
```

![Screen Shot 2021-08-18 at 15 27 44](https://user-images.githubusercontent.com/30958850/129916550-301d6122-56b3-4c7e-a41a-ff2700711264.png)

**Comment by rchiodo** [comment]
I don't think we're doing anything special here with dataframes. It should behave the same as the old interactive window.

@janosh  when you say show the shape, you mean the `10 rows x 1000 columns` on the bottom?

**Comment by rchiodo** [comment]
Oh yeah, old IW behaves the same way. 

![image](https://user-images.githubusercontent.com/19672699/129939527-2fb700dd-abda-44ab-a0ee-7e8b77c1cbf0.png)

So I think this is up to IPython (or maybe pandas) to decide what it wants to output.

**Comment by janosh** [comment]
I see. Oh well, both iPython and Pandas would be unlikely to want to change their current behavior, I assume.
