### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Tusharjungli** [microsoft/vscode-jupyter#7216]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.8.1236758218`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.59.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rchiodo** [comment]
Sorry but this isn't enough information to understand what the problem is. Can you respond with a more descriptive error?
