### ISSUE TITLE
Cell Output Width

### ISSUE THREAD

**Issue by Teslassian** [microsoft/vscode-jupyter#7221]
Suggestion to allow the user to set cell output width - especially on large monitors, a lot of space is wasted by having printed output wrap to the next line after a mere 70-something characters. This would especially be of value when printing Dataframes with a bunch of columns, and other similar data structures.

![image](https://user-images.githubusercontent.com/64134453/130318431-ba902be7-d562-44d3-af3c-afb171a54780.png)

**Comment by joyceerhl** [comment]
It sounds like you want to ensure that tables with a large number of columns don't get broken onto a new row? Does configuring either `pd.options.display.max_columns` achieve what you want?  
![image](https://user-images.githubusercontent.com/30305945/130476839-8bf2d6fd-385e-4b74-a2d1-40a22050268c.png)

**Comment by Teslassian** [comment]
Brilliant, thank you very much. Apologies for the silly question.
