### ISSUE TITLE
Old jupyter notebook editor opened

### ISSUE THREAD

**Issue by avoutsas67** [microsoft/vscode-jupyter#7222]
Issue Type: <b>Bug</b>

When opening a Jupyter notebook the old jupyter notebook appears and not the new one. 

Thanks

Achilleas

Extension version: 2021.8.1236758218
VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 16, 14|
|Memory (System)|8.00GB (0.50GB free)|
|Process Argv|--crash-reporter-id 2d73546a-783e-40a5-81d0-d764c18c9510|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30353136
vsdyn321cf:30354108

```

</details>

**Comment by joyceerhl** [comment]
From the file explorer, right click on the file and select 'Open With':

![image](https://user-images.githubusercontent.com/30305945/130341390-87e66c17-5838-4548-8348-cea0453aefe8.png)


Then pick the 'configure default editor' in the quickpick that shows up:

![image](https://user-images.githubusercontent.com/30305945/130341367-c455eb5c-f5ec-48c1-ac3f-5600d01920bc.png)


Thereafter notebooks should open with the new interface.

**Comment by greazer** [comment]
Closing as Joyce's instructions should be adequate.
