### ISSUE TITLE
Plot doesnt render unless in specific order

### ISSUE THREAD

**Issue by onionhammer** [microsoft/vscode-jupyter#7223]
## Environment data

VS Code Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
Jupyter extension version: v2021.8.1236758218
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.6.0

-   Python version: 3.9.6
-   Jupyter server running: Local

## Expected behaviour

A plot should be rendered regardless of order of imports

## Actual behaviour

Plot is only rendered for 'bt' library if a plot has already been rendered previously

## Steps to reproduce:

A notebook with the following cells produces no plots:

```py
### Cell 1
import bt

# download data
data = bt.get('aapl', start='2020-01-01')
sma = data.rolling(50).mean()
plot = bt.merge(data, sma).plot(figsize=(15, 5))
```

A notebook with the following cells produces two plots:

```py
### Cell 1
import matplotlib.pylab as plt
import numpy as np

x = np.linspace(0, 20, 100)
plt.plot(x, np.sin(x))
plt.show()

### Cell 2

import bt

# download data
data = bt.get('aapl', start='2020-01-01')
sma = data.rolling(50).mean()
plot = bt.merge(data, sma).plot(figsize=(15, 5))
```

**Comment by joyceerhl** [comment]
I see the same behavior in browser Jupyter notebooks. Additionally if I run the bt cell first, then the matplotlib cell, I see the following 

![image](https://user-images.githubusercontent.com/30305945/130341569-68e1f391-520b-4c3e-aea4-66e7fcc0fdaa.png)

It seems like the bt module configures matplotlib to not show plots somehow, so I believe you'd want to file this on the bt module's bug tracker instead if this is unexpected behavior for you.

**Comment by onionhammer** [comment]
@joyceerhl Interesting, but rendering another plot previously just 'unlocks' that functionality? Should a library be able to "lock" the plotting?

**Comment by onionhammer** [comment]
# Workaround:

Add line:
%matplotlib inline

**Comment by greazer** [comment]
Sounds like this has been resolved externally. Closing.
