### ISSUE TITLE
improve kernel selecting for notebook.

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode-jupyter#7229]
show default interpreter and sort the list for kernel selecting like this:
![image](https://user-images.githubusercontent.com/26390254/130270945-e302590c-667b-4684-9bbc-9c2aa61dae5a.png)

**Comment by joyceerhl** [comment]
We should probably apply whatever sort logic the Python extension applies to its interpreter list.

**Comment by DonJayamanne** [comment]
Closing this issue in favor of the new UI for grouping and sorting based on environments.
If the new UI  (please try the latest release) isn't sufficient, please feel free to re-open this issue or create a new one.
