### ISSUE TITLE
Identify kernels that have ipykernel installed to kernels picker.

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode-jupyter#7230]
![image](https://user-images.githubusercontent.com/26390254/130274259-3033faf1-e96b-4666-b656-eacc0957ef9d.png)

**Comment by joyceerhl** [comment]
Thanks for the suggestion. Out of curiosity why would you want this feature?

**Comment by byehack** [comment]
prevent from these notifications:

![image](https://user-images.githubusercontent.com/26390254/130525092-c066ae9a-a5d7-4878-9c0c-ff7b09af3a58.png)

**Comment by DonJayamanne** [comment]
Thanks for this suggestion, unfortunately there haven't been enough upvotes on this suggestion,
