### ISSUE TITLE
Reduce trace log levels to just `off|error|info|verbose`

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7232]
We have all of these log levels = 'off' | 'error' | 'warn' | 'info' | 'debug' | 'verbose';

Do we need `warn|info|debug`, why not just have `verbose`.

@roblourens @rchiodo @DavidKutu @IanMatthewHuff @joyceerhl /cc

**Questions:**
* Can we have just one instead of `info|debug|verbse`
* Do we even need `off`, why would we never display errors?

**Comment by roblourens** [comment]
A couple messages are very noisy, like `Notebook Session status ...`, it would be nice to have a level where I can see the DA traffic but not other super verbose messages that don't seem that useful.

**Comment by IanMatthewHuff** [comment]
Yeah, the levels feel funny to me. I feel like I could see maybe like three levels at maximum? Like a minimum error level, a pretty much everything level, then a level that adds in a few ultra verbose areas.

**Comment by DonJayamanne** [comment]
> ve a level where I can see the DA traffic but not other super verbose messages that don't seem that useful.

But then if someone else wants to just see kernel messages and not DA, then we still end up in the same place (i.e. DA messages are noisy).

As we use log4js, we can achieve this by creating loggers for each area. This way we can turn on/off logging for each area.

I kind of like that, but we'd need to change the loggers from a function to a factory (just like log4js).


E.g. 
```javascript
const logger = createLogger('debugAdapter');
logger.verbose('Helo');
```

I believe this is possibel, after all we're using log4js and its a simple factory function.

**Summary:**
* Keep just `off, error, info, verbose`
	* In release mode this defaults to `info` (messages only logged in output channel)
	* In debug/development mode, this defaults to verbose (we can configure this to what we want. I prefer verbose)
* Create a factory function to return a logger for individual categories (debug adapter, widgets etc)
	* In release & debug mode, all these categories are on by default.
	* If we only want to see `debug adapter` messages, then we go into the settings and only include `debug adapter` category.
* To make this possible, we'd need to change some existing code to slowly move each message into a category, e.g. kernel messages should probably go into `kernel` or the like.
* Finally add a setting `logging.categories:  ['all', 'debug adapter', 'kernel', ...]`
	* This will not be defined in package.json (i don't want users to be able to see this, its only for our use). If we end up using this often enough, we can optionally add it into package.json and this way we get the necessary auto completion we need.
	* This will default to `all`

How doe this sound?

**Comment by roblourens** [comment]
😁 
![image](https://user-images.githubusercontent.com/323878/130522185-d9059277-e450-4b90-87cf-3e1094a489f7.png)

**Comment by DonJayamanne** [comment]
Closing this for now, wouldlike to fix this, but not sure its worth the effort yet
