### ISSUE TITLE
Is the setting `stopOnFirstLineWhileDebugging` respected in the new run by line

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7263]
Not sure this setting is used anymore in notebook run by line.
If it doesn't apply we should probably update the description in the settings to indicate it applies just to interactive window.

@DavidKutu @roblourens

**Comment by roblourens** [comment]
Didn't know we had that setting. I think it's n/a for RBL but I could use it for full debugging? I think we discussed such a setting at some point

**Comment by greazer** [comment]
Definitely doesn't apply to run-by-line. Quite sure this was added for Interactive window debugging. However, it could certainly apply to notebook debugging as well.

**Comment by DonJayamanne** [comment]
Closing this as stale
