### ISSUE TITLE
Bogus paths displayed in interactive window errors messages

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7267]
Run a cell in the interactive window and ensure you have some errors in the code.
The stack trace will display some werid python file, instead of displaying the original python file.

This would apply to any error message display in interactive window (run time errors, or even when interrupting - actually they are one and the same).

Used to work in webview interactive window.

## Webview
![Screen Shot 2021-08-24 at 11 36 00](https://user-images.githubusercontent.com/1948812/130671360-6f5bd3d1-521e-46ef-98cf-287158a5afe4.png)

## Native

![Screen Shot 2021-08-24 at 11 36 08](https://user-images.githubusercontent.com/1948812/130671365-a496a1cf-a679-4c27-9520-bb1672fd45bb.png)

**Comment by joyceerhl** [comment]
I believe the fix for this would be in the custom error renderer we added.
