### ISSUE TITLE
Interrupt button is enabled even when there's no code running in interactive window

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7269]
**In notebooks,** 
* the interrupt icon is only enabled when we have some code running.
* Similarly variable icon is only enabled when variable view is not visible

In interactive window:
* The interrupt is always enabled even when no code is running.
* Ideally it should be disabled (like in notebooks)..

**Comment by joyceerhl** [comment]
FWIW I've personally never found the disable-when-not-running behavior compelling. I invariably wonder why the button is disabled. Same goes for the variable explorer being disabled when it's already open--clicking should be a noop but the button being disabled is distracting for me personally.

**Comment by DonJayamanne** [comment]
> personally never found the disable-when-not-running behavior compelling. I invariably wonder why the button is disabled

I think vs code does the same thing (disable the commands, via enablement & when clauses), 
Else one would end up clicking on this and it does absolutely nothing (thats what i did, i thought it was the restart button, then realized oh it was interrupt).

As for variable viewer, i think it could be argued that it should be enabled, as that launches the UI (sets focus to the UI element, or at least that's what i think).

**Comment by burkeholland** [comment]
Related: Interrupt button also seems to not be enabled when doing "Run all above". It works if you click it, but it doesn't show as enabled.

**Comment by joyceerhl** [comment]
@burkeholland are you seeing this in notebooks or the interactive window?

**Comment by burkeholland** [comment]
Interactive window....

https://user-images.githubusercontent.com/686963/132589326-29adae5e-9994-4a39-ba47-7b5bea3e5d3e.mp4
