### ISSUE TITLE
Outputs from background threads not displayed

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7270]
# Current main

![Screen Shot 2021-08-24 at 11 57 02](https://user-images.githubusercontent.com/1948812/130674057-928a92d3-1c29-436b-a862-547caa670f07.png)

# Previous stable release (stable vs code & stable extension)
![Screen Shot 2021-08-24 at 11 57 27](https://user-images.githubusercontent.com/1948812/130674059-e478a0d2-a016-438f-9207-41d76a810735.png)

**Comment by DonJayamanne** [comment]
Looks like weird bug
here's the output you get when you run it a few times
![Screen Shot 2021-08-24 at 11 59 22](https://user-images.githubusercontent.com/1948812/130674321-1fb84217-9b94-4eee-a2a9-49fd7308e339.png)


Looks like we're getting the outputs, but we're not sending it correctly to VS Code or something wrong in vs code.

**Comment by roblourens** [comment]
Works 100% reliably for me

**Comment by DonJayamanne** [comment]
Absolutely no idea, but this was not working earlier. No changes since then.

**Comment by roblourens** [comment]
So it works for you now? If you still repro an issue we can try to debug on your machine
