### ISSUE TITLE
Open in editor button after saving interactive window to ipynb does nothing if the notebook editor is visible but not active

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#7276]
1. Create interactive window
2. Run some code in it
3. Export to Jupyter notebook 
4. Open in editor. Leave the notebook open
5. Open interactive window on top of notebook
6. Export to Jupyter notebook again
7. Open in editor again
8. 🐛 Notebook isn't foregrounded

**Comment by amunger** [comment]
does not seem to repro, possibly fixed at some point
