### ISSUE TITLE
On restart kernel, reconsider having the "Yes, and don't ask again" option...

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7278]
Testing microsoft/vscode#131209

I'm not sure why we added the "Yes and don't ask again" choice when I restart a kernel. This seems like generally a bad idea, since restarting kernels can be a lossy proposition. 

I think it's fine if we keep the setting, but I don't think we should advertise it.

**Comment by joyceerhl** [comment]
The button should navigate the user to the settings UI page but not actually flip the setting value.

**Comment by DonJayamanne** [comment]
Closing as there haven't been any upvotes on this issue

**Comment by DonJayamanne** [comment]
Suggestion: 
Due to https://github.com/microsoft/vscode/issues/163729  we might want to always ask the user & be consistent with Jupyter as well (i.e. remote the option `do not show again`)

**Comment by DonJayamanne** [comment]
Closing this issue, hasnt received any upvotes
