### ISSUE TITLE
Unable to start session for kernel Python 3.8.5 32-bit

### ISSUE THREAD

**Issue by leonarduschen** [microsoft/vscode-jupyter#728]
# Bug: Notebook Editor, Interactive Window, Editor cells

Unable to start session for kernel Python 3.8.5 32-bit ('venv': venv). Select another kernel to launch with.

## Steps to cause the bug to occur
There is really nothing special here
1. Clone repo and start VSCode
2. Run `python -m venv venv`
3. Switch interpreter to venv and restart terminal
3. Create main.ipynb
4. Install data-science package when automatically prompted
5. Unable to start-session.

## Actual behavior
Unable to start session for kernel Python 3.8.5 32-bit ('venv': venv). Select another kernel to launch with.
## Expected behavior
Notebook runs!

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** v2020.8.105369
-   **VS Code version:** 1.48.2
-   **Setting python.jediEnabled:** I don't have this in my settings JSON file so default settings?
-   **Setting python.languageServer:** Microsoft
-   **Python and/or Anaconda version:** 3.8.5 32-bit
-   **OS:** Windows 10 Home 64-bit
-   **Virtual environment:** venv  ...

## Python Output

The notebook can't run so there is nothing to copy here. However, here is the installed package in the environment if it helps at all:

Package            Version
------------------ -------
argon2-cffi        20.1.0 
attrs              20.1.0 
backcall           0.2.0  
bleach             3.1.5  
cffi               1.14.2 
colorama           0.4.3  
decorator          4.4.2  
defusedxml         0.6.0  
entrypoints        0.3    
flake8             3.8.3  
ipykernel          5.3.4  
ipython            7.18.1 
ipython-genutils   0.2.0  
ipywidgets         7.5.1  
jedi               0.17.2
Jinja2             2.11.2
jsonschema         3.2.0
jupyter            1.0.0
jupyter-client     6.1.7
jupyter-console    6.2.0
jupyter-core       4.6.3
MarkupSafe         1.1.1
mccabe             0.6.1
mistune            0.8.4
nbconvert          5.6.1
nbformat           5.0.7
notebook           6.1.3
packaging          20.4
pandocfilters      1.4.2
parso              0.7.1
pickleshare        0.7.5
pip                20.1.1
prometheus-client  0.8.0
prompt-toolkit     3.0.7
pycodestyle        2.6.0
pycparser          2.20
pyflakes           2.2.0
Pygments           2.6.1
pyparsing          2.4.7
pyrsistent         0.16.0
python-dateutil    2.8.1
pywin32            228
pywinpty           0.5.7
pyzmq              19.0.2
qtconsole          4.7.6
QtPy               1.9.0
Send2Trash         1.5.0
setuptools         47.1.0
six                1.15.0
terminado          0.8.3
testpath           0.4.4
tornado            6.0.4
traitlets          5.0.0
wcwidth            0.2.5
webencodings       0.5.1
widgetsnbextension 3.5.1

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by weirdyang** [comment]
Solved the issue by recreating venv

**Comment by Amundeep-Dhaliwal** [comment]
Still experiencing the issue after

**Comment by neonbeast** [comment]
> Hey folks. In my local testing I believe that it was this update here to 5.0.0, which is picked up as part of our ipykernel install:
> https://pypi.org/project/traitlets/#history
> 
> In an activated environment that is not working try the following to drop it back to the older version:
> ` python -m pip install 'traitlets==4.3.3' --force-reinstall`
> Make sure to have VS Code closed (as we sometimes are starting a kernel in the background, this will make sure that you pick up the install fresh the next time that you start).

For windows it is showing this; 

C:\Users\pc>python -m pip install 'traitlets==4.3.3' --force-reinstall
ERROR: Invalid requirement: "'traitlets==4.3.3'"
WHAT TO DO ? PLS HELP!! AND FOR ME I INSTALLED EVEN JUPITER USING pip install jupyter, I INSTALLED IPYTHON TOO AND IPYKERNEL TOO BUT IN VS CODE IT SHOWS ERROR , PLS HELP , I URGENTLY NEED IT DUE TO MY SCHOOL EXAMS!!

**Comment by IanMatthewHuff** [comment]
@neonbeast This specific issue should not be hit anymore as the problematic 5.0.0 version of traitlets has already been fixed. If you are installing a new pip install of jupyter you should get a working version of traitlets. I'd suspect that you are hitting a different issue with getting things running. Please open up a new issue in the repo here.

When you open up a new issue the following info is very helpful to us in debugging.

1. Turn the VS Code setting Jupyter->Logging->Level to 'debug'
2. Copy out the contents of the Output: Jupyter window when you see the error
3. Save off the contents to a file and attach that file to the issue that you file.
