### ISSUE TITLE
Changing the kernel doesn't work for Interactive

### ISSUE THREAD

**Issue by wwydmanski** [microsoft/vscode-jupyter#7288]
## Environment data

-   VS Code version: 1.59.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1236758218
-   Python Extension version (available under the Extensions sidebar): v2021.8.1159798656
-   OS (Windows | Mac | Linux distro) and version: Darwin x64 20.5.0
-   Python and/or Anaconda version: Python 3.8.8
-   Type of virtual environment used: conda
-   Jupyter server running: Local 

## Expected behaviour

After switching the kernel (from 3.8.5 to 3.8.8), the button "Run cell" should execute the code in the 'Interactive' window using the newly selected Python.

## Actual behaviour

The editor proceeds to next cell, but the 'Interactive' window tries to execute it using the original kernel. 

Running the code directly from the `Type code here and press Enter (...)` works as expected.

## Steps to reproduce:

Make two Python installations available to the jupyter - a default one without ipykernel installed, and another one with an ipykernel. Change the kernel in the 'Interactive' window.

Everything works well if the default python has the IPyKernel installed.

## Logs

<details>

<summary>
IPyKernel error
</summary>

<p>

```
Error 2021-08-25 12:38:03: DataScience Error [a [Error]: IPyKernel not installed into interpreter Python 3.8.5 64-bit:/usr/bin/python3
	at E.handleKernelDependencyResponse (/home/MCB/wwydmanski/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218/out/client/extension.js:90:247249)
	at E.installMissingDependencies (/home/MCB/wwydmanski/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218/out/client/extension.js:90:246271)] {
  category: 'noipykernel',
  reason: 1
}
```

</p>
</details>

**Comment by joyceerhl** [comment]
This is caused by the promise chaining we do. Pending promises aren't cleared when the kernel is changed, which causes all cells submitted from the Run Cell codelens to wait forever on this line: 

https://github.com/microsoft/vscode-jupyter/blob/7f1c9d0bda398d5ae5cf175932ad808f85c7fa63/src/client/datascience/interactive-window/interactiveWindow.ts#L404
