### ISSUE TITLE
Jupyter interactive: run current cell throws IndentationError: unexpected indent

### ISSUE THREAD

**Issue by Jakoviz** [microsoft/vscode-jupyter#7303]
## Environment data

-   VS Code version: 1.60.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2031165864
-   Python Extension version (available under the Extensions sidebar): v2021.9.1144093763
-   OS (Windows | Mac | Linux distro) and version: Windows (local), Amazon Linux 2 (remote)
-   Python and/or Anaconda version: Python 3.7.6, IPython 7.21.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Jupyter server running: Remote

## Expected behaviour

When running a cell marked with # %% in a .py file, the indentation level of the cell is the "base level" for all lines in the cell when sent to the interactive window.

## Actual behaviour

![kuva](https://user-images.githubusercontent.com/7263106/130946048-dd4694f3-ced0-4e30-a871-06f8b8152acb.png)
"run current cell" results in
![kuva](https://user-images.githubusercontent.com/7263106/130945910-4ef88aad-ff54-4531-9154-d2e0eadd867c.png)
The first line is treated correctly:
![kuva](https://user-images.githubusercontent.com/7263106/130947132-1662765d-bcf2-438f-b209-3263a352e0b0.png)
results in
![kuva](https://user-images.githubusercontent.com/7263106/130946286-c5c3e594-dd1e-4931-b37e-117882d2d73c.png)
The indentation of # %% makes no difference:
![kuva](https://user-images.githubusercontent.com/7263106/130946814-75aa9d0a-bc0d-4b40-a3cc-abeb43a94e58.png)
results in
![kuva](https://user-images.githubusercontent.com/7263106/130946868-cfc65aaf-9790-484e-b49c-d8cad6891a60.png)

**Comment by minhducpsc** [comment]
Hello, 
What should I do to fix this issue?

Thank you,
Best,
duc

**Comment by joyceerhl** [comment]
Fixed via https://github.com/microsoft/vscode-jupyter/pull/7483. Fix should be available in next Jupyter Insiders build, and next Stable release at the start of October.

**Comment by minhducpsc** [comment]
Hello, could you please show me how to install the Jupyter Insiders build? Thank you

**Comment by joyceerhl** [comment]
You'll need to install the Insiders build of VS Code: https://code.visualstudio.com/insiders then install the Jupyter extension in the Insiders edition. The latest Jupyter Insiders build will be installed automatically.
