### ISSUE TITLE
Broken diagnostics after editing / reordering cells in polyglot notebooks

### ISSUE THREAD

**Issue by SGP57** [microsoft/vscode-jupyter#7308]
<h3> Environment data </h3>

-   Language Server version: 2021.6.3
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

Correct analysis!

<h3> Actual behaviour </h3>

Many false positives.

I am seeing many error reports, mostly this one but others too. It's reporting this error in comments at the start of the file as well.

Python language is selected.

I have <N> for a new file, selected python and pasted in my 39 lines of program and errors are not reported. I put an test-error into the new file and that was reported successfully, and removed when I removed my test-error .

So, it's not the actual syntax etc. I'm relatively new at this. What assumptions are you making that I wouldn't have predicted? I guess there's all sorts of things about my setup that I could discover and add but this seems a bit fundamental so I'd appreciate suggestions / guidance.

python --version
Python 3.8.10

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

```python
XXX
```

**Comment by jakebailey** [comment]
Is this fixed or was it closed mistakenly? I haven't seen a code change that would have fixed this in the concat document or elsewhere...

**Comment by rchiodo** [comment]
Hopefully this is a dupe of https://github.com/microsoft/vscode-jupyter/issues/6608. We closed awaiting verification.
