### ISSUE TITLE
Run Selection/Line in Interactive Window broken

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#7322]
Issue Type: <b>Bug</b>

Recent update broke `Jupyter: Run Selection/Line in Interactive Window` randomly in some workspaces but not others.  What should I check in the workspace file or elsewhere to fix this?  

All of the following do absolutely nothing:
1. Pressing <kbd>Shift</kbd>+<kbd>Enter</kbd>, 
2. Right clicking and selecting `Run Selection/Line in Interactive Window` 
3. Pressing <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>P</kbd> then selecting `Jupyter: Run Selection/Line in Interactive Window`

However, in some other workspaces, everything works as expected.  All settings and keyboard shortcuts have been checked and are the same in workspaces that work and workspaces that don't work. 

Strangely, in the workspaces where `Run Selection/Line in Interactive Window` doesn't work, the following commands still do work and open up an Interactive Window:
1. `Run Current File in Interactive Window`
2. `Run From Line in Interactive Window`
3. `Run To Line in Interactive Window`

However, even after the Interactive Window is open, `Run Selection/Line in Interactive Window`  by any method still does not work.

Extension version: 2021.8.1236758218
VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (1.00GB free)|
|Process Argv|--crash-reporter-id 1e88d7ed-dfc2-42ed-b5d3-970568cb872e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn478:30356813
vscus224cf:30358040
vssid140:30358036

```

</details>

**Comment by claudiaregio** [comment]
Hi @clayms I am not able to reproduce your issue with the same versions of VS Code and Jupyter extension. Are any logs produced when you attempt to run in the interactive window? If so could you please upload them here? 

Terminal -> New Terminal -> Output -> Jupyter

**Comment by clayms** [comment]
@claudiaregio 

In the examples below, both VS Code workspaces are on the same computer and connected to the same Python interpreter.

Why does the workspace that ***is not*** working only have `python` where the one that ***is*** working has `~\Miniconda3\python.exe` in the `Process Execution: >` line ?

In the VS Code workspace that ***does not*** work after pressing <kbd>Shift</kbd>+<kbd>Enter</kbd>, this is what the logs show:
```bash
Info 2021-08-28 07:40:09: Cached data exists getEnvironmentVariables, <No Resource>
Info 2021-08-28 07:40:09: Process Execution: > python d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.1236758218\pythonFiles\normalizeSelection.py
> python d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.1236758218\pythonFiles\normalizeSelection.py
```

In the VS Code workspace that ***does*** work after pressing <kbd>Shift</kbd>+<kbd>Enter</kbd>, this is what the logs show:
```bash
Info 2021-08-28 07:45:46: Cached data exists getEnvironmentVariables, <No Resource>
Info 2021-08-28 07:45:46: Process Execution: > ~\Miniconda3\python.exe d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.1236758218\pythonFiles\normalizeSelection.py
> ~\Miniconda3\python.exe d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.1236758218\pythonFiles\normalizeSelection.py
Info 2021-08-28 07:45:46: UpdateWorkingDirectoryAndPath
Info 2021-08-28 07:45:46: Adding hash for 2 = 3764aeefb081 with 2 lines
Info 2021-08-28 07:45:46: [32mWidget Coordinator sent IPyWidgets_mirror_execute
Info 2021-08-28 07:45:46: [32mPosting message to Notebook UI 
Info 2021-08-28 07:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-08-28 07:45:46: [32mPosting message to Notebook UI 
Info 2021-08-28 07:45:46: Kernel switching to busy
Info 2021-08-28 07:45:46: Notebook Session status vscode-interactive:Interactive-1.interactive # Busy
Info 2021-08-28 07:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-08-28 07:45:46: [32mPosting message to Notebook UI 
Info 2021-08-28 07:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-08-28 07:45:46: [32mPosting message to Notebook UI 
Info 2021-08-28 07:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-08-28 07:45:46: [32mPosting message to Notebook UI 
Info 2021-08-28 07:45:46: Kernel switching to idle
Info 2021-08-28 07:45:46: Finished execution for 7697adab-22ac-4936-a492-e5b0070fb02d
Info 2021-08-28 07:45:46: Notebook Session status vscode-interactive:Interactive-1.interactive # Idle
Info 2021-08-28 07:45:47: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-08-28 07:45:47: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-08-28 07:45:47: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-08-28 07:45:47: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-08-28 07:45:47: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-08-28 07:45:47: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-08-28 07:45:47: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-08-28 07:45:47: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
```

**Comment by clayms** [comment]
Likely a related issue: https://github.com/microsoft/vscode-jupyter/issues/7329

**Comment by greazer** [comment]
@clayms, please let us know if this still repros after the release of 1.60. Or you can try it in VS Code insiders today. We have been unable to reproduce the problem.
