### ISSUE TITLE
Very slow data viewer

### ISSUE THREAD

**Issue by alandema** [microsoft/vscode-jupyter#7331]
## Environment data

-   VS Code version: 1.59.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1236758218
-   Python Extension version (available under the Extensions sidebar): v2021.8.1159798656
-   OS (Windows | Mac | Linux distro) and version: W10 21H1
-   Python and/or Anaconda version: 3.9.6 minconda
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | N/A : Local

## Expected behaviour

Open the variables in data viewer fast

## Actual behaviour

It takes a good minute or two to open a quite large variable, like np array [~10000,~100,~10] or lists of ints [~100000]. I should expect these examples to be fast because they are almost instant in Spdyer.

## Steps to reproduce:

1. import numpy as np
2. a=np.random.random([10000,100,10])

More than a minute to open the np array
![3darr](https://user-images.githubusercontent.com/68517641/131235017-791a1a77-7180-411b-963d-dc1a33fc36b8.gif)

A larger array in spyder
![spyder](https://user-images.githubusercontent.com/68517641/131235031-873712cc-31f0-438e-85e3-13a3d7c4c8cf.gif)

**Comment by DavidKutu** [comment]
Thanks for filing @alandema.
We'll discuss this in our next triage meeting.

**Comment by IanMatthewHuff** [comment]
We have a number of reports on this. I'm going to close some as duplicates against the original issue #1139 .
