### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by yunho-94** [microsoft/vscode-jupyter#7333]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.8.1236758218`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.59.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DavidKutu** [comment]
Hi @yunho-94 , sorry to hear you're having trouble. We'd really like to help you. To do so, please fill the bug template.
