### ISSUE TITLE
Open interactive windows in locked editor groups by default

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7337]
The drive to add locked editor groups was driven by terminals being supported in editor windows. Users were frustrated that terminals were easily overlapped by newly opened files. Same arguments could be made for interactive window sessions.

**Comment by greazer** [comment]
Adding to September if relatively easy and straightforward to pull off.

**Comment by joyceerhl** [comment]
Locked editor groups are an editor-agnostic concept, so you can already lock an editor group that contains an interactive window editor:

![image](https://user-images.githubusercontent.com/30305945/131373709-2b21a0d9-c599-425b-abc8-ec86deb03664.png)

I just tested this out in the latest Insiders with the interactive window and it seems to work as expected.

**Comment by greazer** [comment]
We should follow suit with the terminal window version of this. If they lock the group by default, we should too. If not we can just close this bug.

**Comment by joyceerhl** [comment]
We might be able to do this by adding 'interactive' to this list:  https://github.com/microsoft/vscode/blob/4858eac2d2977b8c7f912c4eae2ab48b305ee7ef/src/vs/workbench/browser/workbench.contribution.ts#L197

**Comment by greazer** [comment]
Yep, just verified that terminals are in locked groups by default.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
