### ISSUE TITLE
Indentation issue mentioned in closed issue #4425

### ISSUE THREAD

**Issue by EternalLines** [microsoft/vscode-jupyter#7350]
## Environment data

-   VS Code version: 1.59.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1236758218
-   Python Extension version (available under the Extensions sidebar): v2021.8.1159798656
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Home
-   Python and/or Anaconda version: 3.8.10 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

As described in #4425

## Actual behaviour

As described in #4425

## Steps to reproduce:

As described in #4425.
Still having the same issue at my end, not sure if that already been fixed?
The indentation works if arguments are placed immediately in the new line, but it does not if the arguments are placed in the same line as the opening bracket.
![JupyterNB_Indentation_Issue](https://user-images.githubusercontent.com/69616195/131440804-046a72a7-2a41-4cf3-b640-4affe8c06080.png)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by EternalLines** [comment]
I realized this could be solved by installing an extension called "Python Indent". Just in case anyone faces the same issue in the future.

The link is attached:
https://marketplace.visualstudio.com/items?itemName=KevinRose.vsc-python-indent

But I am still very curious whether this issue has been solved, since the last issue was already closed.

**Comment by greazer** [comment]
@EternalLines, please reopen if you find this problem only repros in ipynb files. Thanks!

**Comment by EternalLines** [comment]
> @EternalLines is this an issue that you see with both .py files and in .ipynb notebooks? We've recently moved over to a new UI in which all notebook cells are fully fledged VS Code editor instances. As such something like indentation would be controlled by the currently installed Python formatting extension. If it's an issue with both .py and .ipynb I'd refer this issue to the python extension. That's probably why the previous issue was closed. But if it is an issue that only happens in .ipynb I can help to investigate.

Hi Thanks for replying. Yes, I have tried and the indentation issue happened in both .py and .ipynb files. I am not sure what you meant by "currently installed Python formatting extension"? Were you referring to the official Python extension (https://marketplace.visualstudio.com/items?itemName=ms-python.python)? Or were you referring to the "Python Indent" extension that I mentioned in previous post?
