### ISSUE TITLE
Jupyter notebook stuck loading, not showing content, in VSCode

### ISSUE THREAD

**Issue by Dervis-vL** [microsoft/vscode-jupyter#7352]
## Environment data

-   VS Code version: 1.59.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1236758218
-   Python Extension version (available under the Extensions sidebar): v2021.8.1159798656
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.18363
-   Python and/or Anaconda version: Python
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A and venv (both tried)
-   Jupyter server running: Local 

## Expected behaviour

Open new file and show a cell (window for input), or open existing file and show content of existing notebook(s).

## Actual behaviour

Not showing content. I can not (visually) edit anything. When I press 'Restart' nothing happens. 
The loading bar always shows as if it is loading something, but cannot. It shows a ribbon where I can select '+ Code' or '+ Markdown'. But does not actually do anything.

## Steps to reproduce:

A printscreen of the situation:
![image](https://user-images.githubusercontent.com/65704977/131457454-629296c0-a647-411f-a33c-9cd4f19045a7.png)

## Logs

No logs or errors are given.

**Comment by IanMatthewHuff** [comment]
@Dervis-vL Sorry about the issue. There are a couple of logs that could help with investigating this.

1. In VS Code after opening a file and getting into this situation go to Help->Toggle Develeoper Tools, then in that developer tools window go to the Console tab, right click in the log and use Save As to save that log.
2. Then in the Output: Jupyter window also copy out the contents there into a file.

Those file can then be attached to a comment here. The situation that you are showing here doesn't look familiar to me, and I can repro it myself, so I think that I'd need those logs to investigate more.

**Comment by DavidKutu** [comment]
#6132 seems to be related
@DavidKutu

**Comment by DavidKutu** [comment]
I can't repro anymore on 1.59.1 nor on insiders

**Comment by Dervis-vL** [comment]
@DavidKutu Yes, this could be the same issue. 

I can't see how this issue is resolved since the conversation seems to be blocked.

**Comment by IanMatthewHuff** [comment]
@Dervis-vL This issue is something that is being resolve in the code VS Code, it's not actually Jupyter specific. If you want to track an issue you can look at these two in the VS Code repro:
https://github.com/microsoft/vscode/issues/124383
https://github.com/microsoft/vscode/issues/122951
