### ISSUE TITLE
Markdown render issues

### ISSUE THREAD

**Issue by Claimh** [microsoft/vscode-jupyter#7355]
## Environment data

-   VS Code version: 1.59.1
-   Jupyter Extension version: v2021.8.1236758218
-   Python Extension version: v2021.8.1159798656
-   OS and version: Windows 10 Enterprise 2016 LTSB
-   Python and/or Anaconda version: Python 3.8.2 64-bit
-   Type of virtual environment used: venv
-   Jupyter server running: Local 

## Expected behaviour

Proper rendering of basic markdown.

## Actual behaviour

This only started happened after a recent automatic update for VSCode. This file's markdown has rendered correctly in the past and has remained unchanged for quite a while.

Markdown rendering works for .md files. It just appears not to work through Jupyter.

In render:

1. New lines inserted with a single new line in markdown

> ```
> # %% [markdown]
> #
> # This
> # should be on the same line
> ```

The rendered text is on two lines.

2. Tables do not render using the classic syntax

> ```
> # %% [markdown]
> # | A | B |
> # |----|----|
> # | 1 | 2 |
> ```

This just renders as the actual provided text instead of a table.

3. LaTex not working, just showing the provided text.

## Steps to reproduce:

1. Write markdown in any python file.

![image](https://user-images.githubusercontent.com/10032324/131550152-cc75e209-e057-4499-a12a-4a433bbd6c66.png)

![image](https://user-images.githubusercontent.com/10032324/131549656-58070081-c211-43a9-b310-8f9eabfeb60f.png)

```py
# Re-worded
#
# `A` is Pre Nov 9
#
# `B` is Indet/Term
#
# `C` is Non other code
#
# `I` is Include
#
# | A     | B      | C      | I      |
# | :---: | :----: | :----: | :----: |
# | T     | T      | T      | T      |
# | T     | T      | F      | T      |
# | T     | F      | T      | T      |
# | T     | F      | F      | T      |
# | F     | T      | T      | T      |
# | F     | T      | F      | F      |
# | F     | F      | T      | F      |
# | F     | F      | F      | F      |
#
# This basically resolves to:
#
# $\begin{aligned}
#     I &\iff A \lor (B \land C) \\
#     \lnot I &\iff \lnot A \land (\lnot B \lor \lnot C)
# \end{aligned}
# $
```

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by IanMatthewHuff** [comment]
@Claimh Can you give a bit more info about what you used to see with this repro? Or what you were expecting to see? I tried your bottom repro example in VS Code Notebooks, VS Code interactive window, as a .Markdown file in VS Code, and just inserted into a Jupyter cell. In all examples I'm seeing it displayed approximately the same.

Jupyter:
![image](https://user-images.githubusercontent.com/812783/131728508-41ab53da-b2a1-496f-a8dd-34e5c3dc6e8d.png)

VS Code Markdown File:
![image](https://user-images.githubusercontent.com/812783/131728587-6b1e451f-3171-41a9-a66e-7a1374534ae3.png)

Notebook in VS Code:
![image](https://user-images.githubusercontent.com/812783/131742702-6b7195cf-f526-4c14-9c17-eda1c41ba83a.png)

**Comment by IanMatthewHuff** [comment]
@Claimh My mistake, sorry about the above. I was pasting in the entire commented block, which should be just for the markdown block inside .py code files. I do see the issue here. The examples look ok in the notebook editor, but don't get picked up in the interactive window when tagging with the [markdown] block.

![image](https://user-images.githubusercontent.com/812783/131915973-113cdce0-f04f-4d73-81a0-f44c380ba93b.png)

**Comment by IanMatthewHuff** [comment]
Interesting, some tagged markdown cells render fine:
![image](https://user-images.githubusercontent.com/812783/131920266-d603c47d-4d42-4146-be44-f048b6f73092.png)

And this table format is correct in the notebook:
![image](https://user-images.githubusercontent.com/812783/131920781-632ea8e4-1d15-4983-88fb-60f8463cbb00.png)

**Comment by IanMatthewHuff** [comment]
Got a fix, PR incoming.
![image](https://user-images.githubusercontent.com/812783/131924910-8af57c49-3624-4941-88fc-d15689258767.png)

**Comment by IanMatthewHuff** [comment]
Closed, should be in the next insiders release.
