### ISSUE TITLE
Improve scrolling

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7360]
We have had many user complaints on surveys or other feedback channels about scrolling problems. Here's a bunch of issues related to it:

```
microsoft/vscode -> is:issue is:open in:title scroll label:notebook,notebook-layout,interactive-window,notebook-output
microsoft/vscode-jupyter -> is:issue is:open in:title scroll
```
Here are some papercuts that @claudiaregio identfied as possibly being related to the feedback she's seen

- [x] https://github.com/microsoft/vscode/issues/126880
- [ ] https://github.com/microsoft/vscode/issues/130942 (user refers to current scrolling as "clunky, especially with large cells"
- [x] https://github.com/microsoft/vscode/issues/129713
- [ ] https://github.com/microsoft/vscode-jupyter/issues/5186
- [x] https://github.com/microsoft/vscode/issues/123828

**Comment by thomasaarholt** [comment]
Currently (insider 1.61), notebook does not support the smooth scroll preference that is used with the mouse scroll wheel.
In JSON, this setting is `"editor.smoothScrolling": true,`.

**Comment by dynamicwebpaige** [comment]
+1 for improved scrolling in cell outputs. This is especially troublesome for pandas DataFrames (a couple of examples attached below, including truncated values):

![image](https://user-images.githubusercontent.com/3712347/140655799-878863ae-5048-493a-8a89-aba8ed0148f8.png)

![image](https://user-images.githubusercontent.com/3712347/140655834-82a2c6bd-4aa0-4fa2-b2aa-b9256948ce23.png)

Pandas has a couple of commands to change the number of output rows and columns within Jupyter and JupyterLab, e.g.:

* [`pandas.set_option('display.max_rows', 1000)`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.set_option.html#pandas.set_option)
* [`pandas.set_option('display.max_columns', 100)`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.set_option.html#pandas.set_option)

...but these configurations are not honored within VS Code. Is there a way that we could notify the user that they would need to change `"notebook.output.textLineLimit": n`, if they attempt to use `pandas.set_options`; or just take care of the change for them behind the scenes?

**Related issues**:
* https://github.com/microsoft/vscode-jupyter/issues/7096
* https://github.com/microsoft/vscode-jupyter/issues/4406

**Comment by xuJ14** [comment]
Was this feature solved? Because I still have the same issue, may I ask how to fix that? I have the latest version.
