### ISSUE TITLE
Debugging cells in the interactive window will show the 'temp hashed file' if you restart the kernel

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7366]
Latest stable

Repro steps:
1. Open py file with a bunch of cell delimiters
2. Send a cell to the interactive window
3. Restart the kernel
4. Debug a cell 

This will come up:

![image](https://user-images.githubusercontent.com/19672699/131585068-017fea1a-39d0-4ba8-b1f2-a73c948b9000.png)

**Comment by joyceerhl** [comment]
@rchiodo I can't repro this in Insiders now, can you?

**Comment by rchiodo** [comment]
Yeah still repros for me.

**Comment by rchiodo** [comment]
Steps I followed:

1. Run a cell with ipykernel 5 or so
2. Debug same cell
3. Debug same cell again
4. Restart kernel
5. Debug same cell 

Error happens

**Comment by joyceerhl** [comment]
Thanks that worked. Problem was I had ipykernel 6.

**Comment by joyceerhl** [comment]
Problem AFAIK is the `onKernelRestarted` method wasn't hooked up.
