### ISSUE TITLE
Notebook saved from the interactive window does not support the plot viewer

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7367]
1. Run some cells with a plot in the interactive window
2. See that the plot viewer works
3. Save as a notebook
Expected:
plot can still be open

Actual:
plot doesn't open

**Comment by DonJayamanne** [comment]
Isn't this an nb golden scenario issue, what's the point of export if users cannot view it in notebooks.
isn't this a regression?

**Comment by amunger** [comment]
This seems to work fine for me with the `Export Interactive Window as Notebook` command, is that what you were using?
@rchiodo

**Comment by rchiodo** [comment]
No I was just saving the interactive window as a notebook.

**Comment by rchiodo** [comment]
This was a long time ago though. Let me try it again.

**Comment by rchiodo** [comment]
Yeah same error still repros

![image](https://user-images.githubusercontent.com/19672699/161605693-9c4aba5b-46d8-4e94-b1d7-0dbee3a266dc.png)

Image does not support having a plot viewer icon.

**Comment by amunger** [comment]
> Image does not support having a plot viewer icon

OK, yeah that also repros with export
