### ISSUE TITLE
Execution count wrong after restarting kernel

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#7368]
Execution count is not reset to 1 after restarting kernel:

![image](https://user-images.githubusercontent.com/30305945/131594896-e81afeee-ad45-4eb4-b161-e7bde7a24cc4.png)

Testing with 1.60 and latest VSIX from release branch.

**Comment by DonJayamanne** [comment]
Looks like restart is not working at all

**Comment by DonJayamanne** [comment]
Isn't this a regression?

**Comment by joyceerhl** [comment]
Yes it is

**Comment by joyceerhl** [comment]
Weird, I can't repro this anymore.

**Comment by DonJayamanne** [comment]
Neither could i
