### ISSUE TITLE
Consider making settings for notebooks different from interactive window - in many cases they should be different

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7371]
1. Hide global toolbar
2. We should see the icons in the editor toolbar for interactive window
See images of Notebook vs interactive

No icons for interactive window (restart, variables, etc)
Basically changing the notebook layout is broken for interactive window (i.e. users cannot change their layout as we only display icons in one view).

![Screen Shot 2021-09-01 at 09 02 50](https://user-images.githubusercontent.com/1948812/131705777-f0b5e8b8-4149-49b7-980d-501d976b98db.png)

**Comment by joyceerhl** [comment]
We should probably review whether it makes sense for notebook settings to impact the interactive window. Cell toolbar visibility and undo redo behavior are two other areas where the default value for notebooks is not ideal for the interactive window.
