### ISSUE TITLE
Need telemetry to check if anybody is using two notebooks with different kernels at the same time

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7376]
In order to simplify our kernel picking, we're thinking about removing the ability to pick different python kernels in a notebook.

Instead we'll have a single 'python' kernel that maps to the active python interpreter.

A workaround would be to generate a kernelspec for a specific interpreter (we could even add a command for that)..

Before we do this, we want to check how many people need to have more than one interpreter at the same time.

**Comment by greazer** [comment]
Related to #7373

**Comment by greazer** [comment]
I don't think this is necessary for now. We can revisit in the future if necessary. Marking as debt in case we have some extra time. yeah right.

**Comment by DonJayamanne** [comment]
This telemetry is available today.
Its a matter of going through and figuring this out now.
Closing as as we're planning on re-visiting the kernel picker UI
