### ISSUE TITLE
Provide keyboard shortcut to clear the interactive window for Python

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-jupyter#7379]
### Discussed in https://github.com/microsoft/vscode-python/discussions/16004

<div type='discussions-op-text'>

<sup>Originally posted by **GitHunter0** April 20, 2021</sup>
Provide keyboard shortcut to clear the interactive window for Python. 
It is quite annoying to have to do that all the time via mouse click on the `x` (see picture below) 
![image](https://user-images.githubusercontent.com/26294221/115478419-7aebf480-a21c-11eb-9d53-2777ae63a7ad.png)
Thank you</div>

**Comment by rchiodo** [comment]
This already exists:

![image](https://user-images.githubusercontent.com/19672699/131734845-2d88973b-2ad6-48ae-9923-c4e20ac72258.png)
