### ISSUE TITLE
New Dataframe styling for Insider's build is not as nice the old one.

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-jupyter#7382]
### Discussed in https://github.com/microsoft/vscode-python/discussions/16095

<div type='discussions-op-text'>

<sup>Originally posted by **pbower** April 29, 2021</sup>
The Insider's Jupyter Notebooks are just awesome.

But the new dataframe styling for the Insider's build seems a tad off (the grey colour). 

Can we add the option of changing it back or instead make the colours user-configurable? Perhaps, if it is already configurable via Pandas dataframe styling, we could get a palette added to VS Code so we can style them to our preference?

Great work guys.

Thanks!!

New:
![Screenshot from 2021-04-30 07-24-09](https://user-images.githubusercontent.com/37089506/116620391-1bf94e80-a985-11eb-8dd9-15146a3875df.png)

Original:
![Screenshot from 2021-04-30 07-25-41](https://user-images.githubusercontent.com/37089506/116620562-5531be80-a985-11eb-874b-39c97b9f8e5a.png)
</div>

**Comment by rchiodo** [comment]
@pbower not sure how you got the original. Using dark theme I get this now:

![image](https://user-images.githubusercontent.com/19672699/131741622-bcca4160-13ab-49a0-b01c-87020ca0b815.png)


The old window looked the same:

![image](https://user-images.githubusercontent.com/19672699/131741646-b32d4d13-de4b-49dc-b4bb-7c1f9b35a2b5.png)

Font was different but colors came out the same.

We should be displaying the html returned by pandas itself without any css changes.

Are you asking for a predefined style for pandas to be applied?

**Comment by greazer** [comment]
Please reopen if this is not resolved in the current official release.
