### ISSUE TITLE
When connecting to remote connection, if the default kernel doesn't start, then remote will never work in vscode

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7384]
Basically we dont event dipslay the kernel picker that would allow users to connect toa different server.
The problem is we're starting a whole new session unnecessarily when all we want is a list of kernels.

I.e. even when we're getting list of kernels, we're starting unnecessary kernels.

Took me 2 hours to figure out that my default kernel wouldn't start.
I'm using Jupyter & jupyter labs & don't run into this issue, but vscode wouldn't allow me to connect to a local remote at all.

**Comment by greazer** [comment]
We shouldn't need to start a kernel to get the list of kernels in the remote scenario.

**Comment by DonJayamanne** [comment]
This has been fixed in the Nov milestome.

**Comment by DonJayamanne** [comment]
This has been fixed and validated in a previous release
