### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by lcampos777** [microsoft/vscode-jupyter#7388]
- Issue Type: `Performance`
- Extension Name: `jupyter`
- Extension Version: `2021.8.1236758218`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.59.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\lccc7\AppData\Local\Temp\ms-toolsai.jupyter-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, however you've failed to upload the cpuprofile.txt file.
Pkease upload that file
