### ISSUE TITLE
Recent Update - Lost ctrl+f Find function in Interactive Window

### ISSUE THREAD

**Issue by zalberts** [microsoft/vscode-jupyter#7390]
## Environment data

-   VS Code version: 1.59.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1236758218
-   Python Extension version (available under the Extensions sidebar): v2021.8.1159798656
-   OS (Windows | Mac | Linux distro) and version: Windows 10 21H1 build 19043.1165
-   Python and/or Anaconda version: Anaconda3 Python 3.8.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

Before most recent update, could search inside of an interactive window with ctrl+f - similar to all other windows with in vscode. 

## Actual behaviour

Now, i get an error pop-up in the bottom right that says "Cannot read property ;show; of null" with a yellow exclamation inside of a triangle when i hit ctrl+f.

## Steps to reproduce:

1. Open a new Interactive Window (from a python file with #%% or with F1 > Jupyter: Create Interactive Window.
2. Click inside of it, and hit your shortcut for Find or Replace (ctrl+f or ctrl+h
3. For thoroughness - also click EDIT in top tab, then click Find (while the Interactive window is selected) and the same error shows up. 

## Logs

None can be provided

**Comment by joyceerhl** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/131996

**Comment by zalberts** [comment]
@joyceerhl Is this a "vscode" or a "interactive window/jupyter" issue then? Will close if pure-duplication.

**Comment by joyceerhl** [comment]
This is a VS Code issue, because the interactive window UI is now fully provided by and implemented in VS Code (previously it was provided by the Jupyter extension).

**Comment by zalberts** [comment]
Closing as duplicate/Wrong ownership - vscode main thread issue, not vscode-python/jupyter issue.
