### ISSUE TITLE
Images render too large

### ISSUE THREAD

**Issue by david-cortes** [microsoft/vscode-jupyter#7397]
When rendering images in a jupyter notebook (from matplotlib for example), these images look much bigger in vscode than in nbviewer or github’s jupyter viewer.

Example (see the image at the end):
https://nbviewer.jupyter.org/github/david-cortes/contextualbandits/blob/master/example/online_contextual_bandits.ipynb
https://github.com/david-cortes/contextualbandits/blob/master/example/online_contextual_bandits.ipynb

VSCode version: 1.60.0
Jupyter extension version: v2021.8.2031190714
OS: linux (debian)

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
I've tested this, and nbviewer has a max width, hence no matter what kind of a monitor you have the width of the notebook is restricted.
Same applies to the GitHub notebook viewer.

The notebooks in VS Code dont have a width restriction,a s VS Code provides editing of notebooks (nbviewer & github viewer are readonly and built purely for vewing of notebooks - i.e. a readonnly experience).

You can however try the centered layout, `View: Toggle Centered Layout`.

**Comment by DonJayamanne** [comment]
Please do let me know if those options work.
