### ISSUE TITLE
Prompt the user to restart the kernel when running a cell against a dead kernel

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7399]
Run some code, and assume the kernl dies.
Next the user attempts to run a cell again
This is what you get (when kernel is dead)

Looks horrible, I think we should detect this and just inform the user the kernel is dead and ask them to restart the kernle (yes/no).

Else we just leave the user to figure out whats wrong & what they need to do.

![Screen Shot 2021-09-02 at 16 02 25](https://user-images.githubusercontent.com/1948812/131926911-a422e3b8-b5b0-408a-9c23-b3392b5278a6.png)

**Comment by DonJayamanne** [comment]
Done
Testing:
* Create a notebook
* Run a cell with the code 
```python
import os
os.getpid()
```
* Kill the kernel prcoess (pid printed above)
* Try to run the same or anotehr cell in the same notebook, user should be prompted to restart the kernel (notify them the kernel is dead)

**Comment by rchiodo** [comment]
/verified

![image](https://user-images.githubusercontent.com/19672699/144527050-ce810e04-1dfc-446c-9ad3-dcc82b126c62.png)
