### ISSUE TITLE
mode matplotlib notebook not work

### ISSUE THREAD

**Issue by smallp** [microsoft/vscode-jupyter#7408]
## Environment data

-   VS Code version: 1.59.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1236758218
-   Python Extension version (available under the Extensions sidebar): v2021.9.1191016588
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: 3.8.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Show animate.

## Actual behaviour

Error.
Here is vscode error info in console.
```
Exception opening new comm
VM16:4 Error: Object 'matplotlib' not found in registry
Uncaught ReferenceError: IPython is not defined
```
It works if it is `%matplotlib inline`, but the output is not gif but png.
Saving gif works fine.

## Steps to reproduce:
```
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# %matplotlib inline
%matplotlib notebook
print(matplotlib.pyplot.get_backend())
def update_points(num):
    point_ani.set_data(x[num], y[num])
    return point_ani,
 
x = np.linspace(0, 2*np.pi, 100)
y = np.sin(x)
 
fig = plt.figure(tight_layout=True)
plt.plot(x,y)
point_ani, = plt.plot(x[0], y[0], "ro")
plt.grid(ls="--")
ani = animation.FuncAnimation(fig, update_points, np.arange(0, 100), interval=100, blit=True)
 
# ani.save('sin_test2.gif', writer='Pillow', fps=10)
plt.show()

```

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>
Info 2021-09-03 16:45:46: Execute Cells request 1 0
Info 2021-09-03 16:45:46: Cell Index:0, state:1, exec: 9. User queued cell for execution
Info 2021-09-03 16:45:46: Cell Index:0, state:1, exec: 9. Ready to execute
Info 2021-09-03 16:45:46: Cell Index:0, state:1, exec: 9. Before Execute individual cell
Info 2021-09-03 16:45:46: Cell Index:0, state:1, exec: 9. Start execution
Info 2021-09-03 16:45:46: Cell Index:0, state:3, exec: undefined. Send code for execution
Info 2021-09-03 16:45:46: Cell Index:0, state:3, exec: undefined. Wait for jupyter execution
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_mirror_execute
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: Cell Index:0, state:3, exec: undefined. Kernel switching to busy
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: Cell Index:0, state:3, exec: undefined. Update streamed output
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-09-03 16:45:46: Cell Index:0, state:3, exec: 10. Update output
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-09-03 16:45:46: Cell Index:0, state:3, exec: 10. Update output
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-09-03 16:45:46: Cell Index:0, state:3, exec: 10. Kernel switching to idle
Info 2021-09-03 16:45:46: Cell Index:0, state:3, exec: 10. Jupyter execution completed
Info 2021-09-03 16:45:46: Cell Index:0, state:3, exec: 10. Completed successfully
Info 2021-09-03 16:45:46: Cell Index:0, state:3, exec: 10. Completed successfully & resolving
Info 2021-09-03 16:45:46: Cell Index:0, state:3, exec: 10. After Execute individual cell 3
Info 2021-09-03 16:45:46: Cell Index:0, state:3, exec: 10. Executed successfully in executeCell
Info 2021-09-03 16:45:46: Cell Index:0, state:3, exec: 10. Execution disposed
Info 2021-09-03 16:45:46: KernelProcess output: Content-Length: 178
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc": "2.0", "method": "log", "params": {"level": "INFO", "msg": "write to stderr: [IPKernelApp] WARNING | No such comm: a550bee5fada4a25a6959d18a7e2e18d\n", "pid": 22325}}Content-Length: 153
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc": "2.0", "method": "output", "params": {"source": "stderr", "out": "[IPKernelApp] WARNING | No such comm: a550bee5fada4a25a6959d18a7e2e18d\n"}}
Info 2021-09-03 16:45:46: Python Daemon (pid: 22325): write to stderr: [IPKernelApp] WARNING | No such comm: a550bee5fada4a25a6959d18a7e2e18d

Warn 2021-09-03 16:45:46: Kernel 22325 as possibly died, StdErr from Kernel Process [IPKernelApp] WARNING | No such comm: a550bee5fada4a25a6959d18a7e2e18d

Warn 2021-09-03 16:45:46: StdErr from Kernel Process [IPKernelApp] WARNING | No such comm: a550bee5fada4a25a6959d18a7e2e18d

Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: Notebook Session status file:///Users/xiaoping/Documents/python/l/test.ipynb # Busy
Info 2021-09-03 16:45:46: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-09-03 16:45:46: [32mPosting message to Notebook UI 
Info 2021-09-03 16:45:46: Notebook Session status file:///Users/xiaoping/Documents/python/l/test.ipynb # Idle
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-09-03 16:45:46: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
</p>
</details>

**Comment by DonJayamanne** [comment]
@IanMatthewHuff I think this might have to do with the fact that we force the format to be PNG.
I think we should not set a file format at all.
That way what ever the image format is, we should display that in the plot viewer. I.e. remove all code related to initializing matplotlib with our defaults.

**Comment by IanMatthewHuff** [comment]
Yeah, you’re totally right. Our code has always initialized something, it used to be SVG/PNG and PNG with enablePlotViewer turned off. After my change it’s now PNG default with SVG/PNG with generateSVGPlots set to true.
Plot viewer should support all image formats, but even in the super immediate short term it should just be:
1. If generateSVGPlots is off, do nothing
2. If generateSVGPlots is on, add SVG to the existing figure formats, instead of setting to PNG / SVG

**Comment by DonJayamanne** [comment]
Suggestion:
We might want to display a warning or the like when we detect `%matplotlib notebook` with more informaiton

**Comment by DonJayamanne** [comment]
Closing this for now as no one else has run into this nor have there been any upvotes on this issue
