### ISSUE TITLE
Unable to create or open notebooks with remote connection

### ISSUE THREAD

**Issue by rhoadesScholar** [microsoft/vscode-jupyter#7417]
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2021.8.2031190714`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.60.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 374,
		"activateCallTime": 12,
		"activateResolvedTime": 1295,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-toolsai.jupyter",
				"_lower": "ms-toolsai.jupyter"
			},
			"activationEvent": "onLanguage:jupyter"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 3
}
```

Unable to start notebook editor. Just opens raw notebook code (i.e. json).
Trying to create a new notebook gets this error: 
![image](https://user-images.githubusercontent.com/37990507/132067854-1775ceeb-de6d-4ec1-8e46-50e522b2ce02.png)

**Comment by claudiaregio** [comment]
@rhoadesScholar Are you having two issues? One is you attempt to open a notebook and you just see the JSON? The other is you cannot create a new notebook either? 

Could you use the command palette and select "Developer: Toggle Developer Tools" when the error occurs and paste the content here?

**Comment by rhoadesScholar** [comment]
> @rhoadesScholar Are you having two issues? One is you attempt to open a notebook and you just see the JSON? The other is you cannot create a new notebook either?
> 
> Could you use the command palette and select "Developer: Toggle Developer Tools" when the error occurs and paste the content here?

I figured the two issues were likely connected. My main goal is to open an existing notebook.

"Developer: Toggle Developer Tools"  output:
workbench.desktop.main.js:sourcemap:71 [Extension Host] (node:12344) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code --trace-deprecation ...` to show where the warning was created)
v @ workbench.desktop.main.js:sourcemap:71
workbench.desktop.main.js:sourcemap:2872 [GitHub.vscode-pull-request-github]: `remoteHub/pullRequest` is not a valid menu identifier
_logMessageInConsole @ workbench.desktop.main.js:sourcemap:2872
workbench.desktop.main.js:sourcemap:71 [Extension Host] (node:21702) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `node --trace-deprecation ...` to show where the warning was created)
v @ workbench.desktop.main.js:sourcemap:71
workbench.desktop.main.js:sourcemap:602   ERR read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
workbench.desktop.main.js:sourcemap:2877 Extension Host
workbench.desktop.main.js:sourcemap:2877 Debugger attached.

**Comment by claudiaregio** [comment]
@rhoadesScholar Are you working remotely?

**Comment by rhoadesScholar** [comment]
Yes.

**Comment by camelator** [comment]
Same issue here, working remotely but on Linux

**Comment by claudiaregio** [comment]
Could be related to https://github.com/microsoft/vscode-jupyter/issues/7384?

**Comment by rhoadesScholar** [comment]
> Same issue here, working remotely but on Linux

It may or may not be relevant, but I'm working locally on Windows 10, and connecting to a remote Linux server (Ubuntu 18.04).

**Comment by rhoadesScholar** [comment]
If I install the Jupyter Extension version v2021.8.1013163132 and reload the window I can open the notebook in the normal editor view, but trying to run a cell fails. It asks for the kernel (which should be already specified) and displays the following errors: 
![image](https://user-images.githubusercontent.com/37990507/132390851-6da0d35a-ddd5-4b0d-bc47-58963777a220.png)

**Comment by greazer** [comment]
Hey @rhoadesScholar, we believe that this has been fixed in the latest Python extension. Please update and reopen if it's still happening.

**Comment by rhoadesScholar** [comment]
No status change on my end, including after checking for updates, uninstalling and reinstalling Jupyter and Python extensions, reloading multiple times, and closing VS Code altogether, logging on to the server in a terminal and killing any running VS Code processes, then reopening Code and logging in again. So I guess I will open a new issue and reference this one since I don't think I have permission to reopen this issue. Thanks.

**Comment by rhoadesScholar** [comment]
Is v2021.9.1191016588 the Python version I should be expecting?

**Comment by DonJayamanne** [comment]
@rhoadesScholar @camelator are you still running into this issue?

**Comment by rhoadesScholar** [comment]
Yup. The issue is still very much present. I've attached an image of the current state of things. You'll notice the raw javascript showing for an "open" notebook, the minimal Jupyter Output, and the notification that running jupyter.createnewnotebook fails.
![image](https://user-images.githubusercontent.com/37990507/134577140-f13ad0a3-b89e-46fe-858e-c95ea575b095.png)

**Comment by DonJayamanne** [comment]
@rhoadesScholar 
Sorry, you're running into this.

* Oh yes, when you say remote Connection, are you referring to remote SSH or the like?
* 
* Please could you provide the logs from the console window, select the command `Toggle Developer Tools` and look for errors in there.

* Please could you disable the `Jupyter` extension and try to open an existing ipynb file.
Right click on an ipynb file, use `Open With` and select the option `Jupyter notebook`. 
Let me know if that works for you.

**Comment by rhoadesScholar** [comment]
> @rhoadesScholar
> Sorry, you're running into this.
> 
> * Oh yes, when you say remote Connection, are you referring to remote SSH or the like?
> * Please could you provide the logs from the console window, select the command `Toggle Developer Tools` and look for errors in there.
> * Please could you disable the `Jupyter` extension and try to open an existing ipynb file.
>   Right click on an ipynb file, use `Open With` and select the option `Jupyter notebook`.
>   Let me know if that works for you.

I included errors from the Developer Tools panel above. BUT: **Disabling the Jupyter extension worked!** Thank you! Definitely never would have thought to try that. (Of small note, the option in the Right-click menu was "Open in Notebook Editor", no mention of Jupyter.)

Thanks @DonJayamanne

**Comment by DonJayamanne** [comment]
Ok that's very weird, do things break again when enabling the Jupyter extension?
Yes I saw the logs, but they don't provided any information about the error your get.
