### ISSUE TITLE
in Ubuntu 20.10 after restarting the kernel, connection will not be established

### ISSUE THREAD

**Issue by moghadas76** [microsoft/vscode-jupyter#7418]

**Comment by claudiaregio** [comment]
@moghadas76 Can you please provide the Jupyter output logs when this occurs?

**Comment by moghadas76** [comment]
Where(in which path) can I find detailed logs?

**Comment by claudiaregio** [comment]
Terminal -> New Terminal -> Output -> Select Jupyter in the drop down list to the right. 
Please do not forget the vs code versions and extension versions as well

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
