### ISSUE TITLE
Notebook kernel can be lost when viewing cell's long stdout output, if ipynb is marked as preview (italicized file tab)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7419]
* Open a notebook that contains a cell that prints a long list of whatever... ala
```
for i in range(0,100000):
    print(i)
```
* Make sure the filename in the tab is italicized (I don't know what term we use for this state).
* Click on the "show more (open the raw output data..." link.
* Your notebook closes and is replaced by the opened text file. Basically you've lost your kernel state at this point.

**Comment by greazer** [comment]
Try to find a consistent repro for this.

**Comment by greazer** [comment]
Haven't been able to find a repro.
