### ISSUE TITLE
Kernel Died with Exit Code 1073741845

### ISSUE THREAD

**Issue by ranningw** [microsoft/vscode-jupyter#7423]
**Kernel Died with Exit Code 1073741845**
Can anyone help me? I tried to solve this issue, but many attempts are failed.
I am using VS code to run jupyter notebook, which returns this error.

**Detailed：**
Kernel died with exit code 1073741845. C:\anaconda\envs\env_test\lib\site-packages\traitlets\traitlets.py:2196: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use 'hmac-sha256' instead of '"hmac-sha256"' – or use CUnicode.
  warn(
C:\anaconda\envs\env_test\lib\site-packages\traitlets\traitlets.py:2151: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '26f89216-b950-4b0b-b069-b296e7078914' instead of 'b"26f89216-b950-4b0b-b069-b296e7078914"'.
  warn(
Bad file descriptor (bundled\zeromq\src\epoll.cpp:100)

**Comment by joyceerhl** [comment]
@ranningw Please could you provide the full Jupyter log? This appears to be a snippet. Additionally, have you ever been able to start a kernel in the Jupyter VS Code extension, or did this only start happening after a recent upgrade? What version of VS Code and the Jupyter extension are you on?

**Comment by ranningw** [comment]
Jupyter log: [jupyter_log.txt](https://github.com/microsoft/vscode-jupyter/files/7118565/jupyter_log.txt)
Jupyter version : v2021.8.2031190714
vs code version: 1.60.0 (user setup)
have you ever been able to start a kernel in the Jupyter VS Code extension:  No, I haven't. I installed jupyter that have't been worked.

**Comment by ranningw** [comment]
**Issue:**

**Kernel died with exit code 1073741845.**

1. c:\anaconda\envs\my_env\lib\site-packages\traitlets\ traitlets.py :2196: FutureWarning: **Supporting extra quotes around Unicode is deprecated in traitlets 5.0**. Use 'hmac-sha256' instead of '"hmac-sha256"' – or use CUnicode.

2. warn( c:\anaconda\envs\my_env\lib\site-packages\traitlets\traitlets.py:2151: FutureWarning: **Supporting extra quotes around Bytes is deprecated in traitlets 5.0.** Use '7aa5b615-129a-4e47-b483-0954be3b7001' instead of 'b"7aa5b615-129a-4e47-b483-0954be3b7001"'.

3. warn( **Bad file descriptor (bundled\zeromq\src\epoll.cpp:100)**

**Solution**:

To solve 1. & 2. using the following commend in vscode python terminal:

**python -m pip install traitlets==4.3.3 --force-reinstall** (maybe need run 2 times and shows successfully install)

just reinstall the traitlets to the lower version.

To solve 3. using the following commend in vscode python terminal:

**python -m pip install pyzmq==19.0.2 --force-reinstall** (maybe need run 2 times and shows successfully install)

just reinstall the pyzmq to the lower version.

**Comment by ranningw** [comment]
**I solve the issue, please see above solutions!**
