### ISSUE TITLE
Rounded floats are not shown correctly in the data viewer

### ISSUE THREAD

**Issue by salmanea** [microsoft/vscode-jupyter#7426]
## Environment data

-   VS Code version: 1.60.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2031190714
-   Python Extension version (available under the Extensions sidebar): v2021.9.1191016588
-   OS: Windows 10 Enterprise  Build: 19042.1165 
-   Python and/or Anaconda version: 3.9.1
-   Type of virtual environment used: conda
-   Jupyter server running: Local 

## Expected behaviour

Float32 values that are rounded to two decimal places should be shown in the data viewer with two decimal places (see the screenshot of the values printed out):

![image](https://user-images.githubusercontent.com/7900672/132218371-0d6aadb6-5616-49b9-a60d-e53971ce54d0.png)

## Actual behaviour

Float32 values are shown with many leading zeros and in some cases with other values (see the screenshot below):

![Screenshot 2021-09-06 142403](https://user-images.githubusercontent.com/7900672/132217081-79bbfdad-bf89-4085-beea-53e3f60b3c5d.jpg)

**Comment by joyceerhl** [comment]
Thanks for the bug. The loss of precision is likely a side effect of the JSON parsing process when we're passing info about a Python variable to TypeScript code.

**Comment by amunger** [comment]
closing as the jupyter variable viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486
