### ISSUE TITLE
Connecting to existing remote server. Can't find Python Kernel

### ISSUE THREAD

**Issue by isaacdchan** [microsoft/vscode-jupyter#7430]
## Environment data

-   VS Code version: 1.60.0
-   Jupyter Extension version: v2021.8.2031190714
-   Python Extension version: v2021.9.1191016588
-   OS: Catalina 10.15.7
-   Python and/or Anaconda version: 3.9.6
-   Type of virtual environment used: venv
-   Jupyter server running: Remote

## Expected behaviour
Find and attach to kernel

## Actual behaviour
Prompts me to Select kernel for 'test.ipynb'

## Steps to reproduce:
1. Run `jupyter-lab --no-browser`
2. CTRL+SHIFT+P
3. "Jupyter: Specify local or remote Jupyter Server for connections" 
![image](https://user-images.githubusercontent.com/33741008/131928724-162e1a42-f74f-433b-97a7-ddcaf2ce8b52.png)
4. Click "Existing"
5. Paste localhost URL
![image](https://user-images.githubusercontent.com/33741008/131928712-dd149111-cbbd-4c01-9f1e-cfc516e78aac.png)
6. Try running cell

## Logs
jupyter-lab --no-browser
[I 2021-09-06 16:53:36.870 ServerApp] jupyterlab | extension was successfully linked.
[I 2021-09-06 16:53:37.082 ServerApp] nbclassic | extension was successfully linked.
[I 2021-09-06 16:53:37.136 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-09-06 16:53:37.138 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.9/site-packages/jupyterlab
[I 2021-09-06 16:53:37.138 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 2021-09-06 16:53:37.143 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-09-06 16:53:37.144 ServerApp] Serving notebooks from local directory: /Users/ischan/workspace/lb-requests
[I 2021-09-06 16:53:37.144 ServerApp] Jupyter Server 1.9.0 is running at:
[I 2021-09-06 16:53:37.144 ServerApp] http://localhost:8888/lab?token=4d0134d6bd27db80a8b41e48148e4f7f0492153ca1a2b93b
[I 2021-09-06 16:53:37.144 ServerApp]  or http://127.0.0.1:8888/lab?token=4d0134d6bd27db80a8b41e48148e4f7f0492153ca1a2b93b
[I 2021-09-06 16:53:37.144 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-09-06 16:53:37.150 ServerApp]

    To access the server, open this file in a browser:
        file:///Users/ischan/Library/Jupyter/runtime/jpserver-1687-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=4d0134d6bd27db80a8b41e48148e4f7f0492153ca1a2b93b
     or http://127.0.0.1:8888/lab?token=4d0134d6bd27db80a8b41e48148e4f7f0492153ca1a2b93b
[I 2021-09-06 16:53:53.664 ServerApp] Creating new notebook in /
[I 2021-09-06 16:53:53.719 ServerApp] Kernel started: f572c4b6-c7c6-43a7-ad1a-71edc479596d
[W 2021-09-06 16:53:53.756 ServerApp] delete /default-01fa697e-ca16-4281-a1b0-88af3ed71d9b.ipynb
[I 2021-09-06 16:53:54.361 ServerApp] Kernel shutdown: f572c4b6-c7c6-43a7-ad1a-71edc479596d

**Comment by IanMatthewHuff** [comment]
@isaacdchan Sorry could I just ask a clarification question here? What Kernel are you expecting to attach to? When you connect to the remote connection the Select Kernel list should have a list that includes any sessions currently running on that server. Are you looking for a Kernel that is already running and not seeing it in the connection list?

**Comment by IvanAntipov** [comment]
I have the same problem. In my case, the list of available kernels is completely empty. I can't connect to an existing kernel, nor create a new one. I tested on different Jupyter servers, so the problem is on VS Code side. Problem several weeks ago everything worked well.

**Comment by IvanAntipov** [comment]
I found a workaround for this situation:

Create a new notebook. Probably, it can help someone.

My initial notebook was created with local Jupyter server. And I can't run cell from It on remote server. But, when I create a new notebook when remote server is configured, I can run cells from my notebook

**Comment by isaacdchan** [comment]
@IanMatthewHuff as @IvanAntipov stated the list of kernels is completely empty.

Just validated your results @IvanAntipov. Re-confirmed my above behavior (empty kernel list). Created a new notebook, was able to run cells. Then went back to my old notebook, and now it can run cells.

**Comment by IanMatthewHuff** [comment]
@isaacdchan Is the situation now where you don't have the repro anymore since creating a new notebook? I'm having trouble replicating this situation myself. I'm working with a saved .ipynb with a local kernel connection. Then changing my connection to remote. With the file I still see all the expected remote kernels listed.

**Comment by isaacdchan** [comment]
Yes now it doesn't prompt. me to select a kernel the code cell just runs. I'll close the issue and reopen if it resurfaces.
