### ISSUE TITLE
No stdout from jupyter.runStartupCommands

### ISSUE THREAD

**Issue by lfriedri** [microsoft/vscode-jupyter#7434]
## Environment data

-   VS Code version: 1.60.0
-   Jupyter Extension version: v2021.8.2031190714
-   Python Extension version: v2021.9.1191016588
-   OS: Windows 10
-   Python and/or Anaconda version: python 3.6.6 64-bit
-   Type of virtual environment used: Winpython
-   Jupyter server running: N/A

## Expected behaviour (usecase 1)

put "print('startup')" into the jupyter.runStartupCommands section of settings.json
-> 'startup' should appear in the interactive window on generation of interactive window or on kernel restart.

## Actual behaviour (usecase 1)

no output visible

## Expected behaviour (usecase 2)

run the following script via jupyter.runStartupCommands in settings.json:
```
import asyncio

loop = asyncio.get_event_loop()

async def myTask():
    for i in range(10):
        print(f'{i} hello')
        await asyncio.sleep(1)

loop.create_task(myTask())
```

Should print to the interactive window every second, as it happens if the script is manually executed.

## Actual behaviour (usecase 2)

No output visible at first. After the first input to the interactive window is executed, output appears. So I assume that some initialization of the stdout needs to take place.

## Notes
Might be related to #5379

**Comment by IanMatthewHuff** [comment]
@lfriedri This was actually intentional on our side. The startup commands were intended to run silent at the start for any pre-configuration that was needed. However this might be work re-discussing. We'll take about this at triage. Thanks for filing the issue.

**Comment by lfriedri** [comment]
@IanMatthewHuff Ok, I understand that silencing the startup commands can make sense. However, in my usecase 2, I am driving at automatically reporting something to the interactive window. Is there any workaround that I can use to make this work (i. e. activate stdout to print to the interactive window)?

**Comment by IanMatthewHuff** [comment]
Yeah I do get where you are coming from, I don't think this is something that we currently support, but maybe it's something that we could. Also in your Usecase 2 it just feels like a bug on our end. If we are executing silently then the output just should not show up, instead it's getting appended onto the output of an unrelated cell.
![image](https://user-images.githubusercontent.com/812783/132545418-f5254cff-f6a1-4b80-abef-b407467d0200.png)

**Comment by lfriedri** [comment]
I agree, that randomly writing text to the IW does not make sense. However, in my application, I would like to print something to the IW on some event in the UserInterface (let's assume it's a button: the user presses the button and it should print to the IW). After the fix of #5379, this is working now in principle. However, it only works after the first line was written manually into the IW. If I just start the IW and my UserInterface is created by the startup code, printing does not work.

So I tried to track this down and finally arrived at the question why startup code in general does not print.

If this is intended, I would say it is fine.

For me, however, the question remains how I can make my UserInterface (which is setup by startup code) can print to the IW directly after startup (without needing the workaround of entering something manually to the IW).

**Comment by lfriedri** [comment]
What remains from the "issue" point of view is: Why is there a difference in the behaviour of the startupcode BEFORE and AFTER the first cell is manually entered to the IW...

**Comment by IanMatthewHuff** [comment]
Since your code is running async the output is just coming in on stdout from the python kernel. It only shows up when a cell exists in the UI to put the output into, which is why you see the behavior that you do. It's a bit funky but I don't think that it's behavior that we will be changing now.
