### ISSUE TITLE
get_ipython.run_cell integration to interactive window

### ISSUE THREAD

**Issue by lfriedri** [microsoft/vscode-jupyter#7436]
## Environment data
- VS Code version: 1.60.0
- Jupyter Extension version: v2021.8.2031190714
- Python Extension version: v2021.9.1191016588
- OS: Windows 10
- Python and/or Anaconda version: python 3.6.6 64-bit
- Type of virtual environment used: Winpython
- Jupyter server running: N/A

## Expected behaviour

`get_ipython.run_cell('b=5')` in an interactive window should do the following (from my point of view):

- run the code (new variable 'b' becomes available)
- create a visual representation of the code that was run (as if it was typed into the interactive window)
- new variable 'b' should behave as if 'b=5' was entered manually into the console

## Actual behaviour

- new variable 'b' becomes available (correct behaviour)
- no visual representation of the code is generated
- new variable 'b' does not show autocompletion on entering `b.`

**Comment by IanMatthewHuff** [comment]
@lfriedri Just to check, what were you expecting for visual representation? This is what I see with current bits:
![image](https://user-images.githubusercontent.com/812783/132426898-ac7a43a0-f0da-4abf-93b9-38b67ee6d77f.png)
I do see the auto completion issue even though the variable is defined.

**Comment by lfriedri** [comment]
Thank you @IanMatthewHuff for following up on this. The output looks the same on my side. I would expect the interactive window to create a new cell [4] with input 'b=5' like so:
![image](https://user-images.githubusercontent.com/27409887/132470627-6a38cc73-e075-4e1f-9664-52c25c575d63.png)

The reason is, that I would use the run_cell command in some GUI handler to send commands to the interactive window. In the current implementation, there is no visible feedback that something was sent to the interactive window in this case.

**Comment by IanMatthewHuff** [comment]
So with our interactive window or notebooks the code being input is going to be passed more or less directly into Jupyter / IPython from our UI. That entire 'get_ipython()..." string is passed to Jupyter and we print back the result just as if you were to input it. Our results in the IW are going to look the same as if you ran this in Jupyter classic notebooks:
![image](https://user-images.githubusercontent.com/812783/132547121-cf1bace8-c5b9-4952-a678-01a054fb5f9e.png)
Our code doesn't have awareness of if you are trying to create a new cell here that would be displayed in the UI. And to do so would have to parse the input code and take some specific UI actions, which I don't believe we would want to do.

**Comment by lfriedri** [comment]
Ok, I understand. So what I would actually need is some kind of API of the IW, that would allow me to modify the cells that are displayed etc.
What I am basically doing is extending the VS-Code-interactive-window experience with my own UserInterface. However, this UserInterface is running INSIDE the IW. Maybe this is the wrong approach and I should rather try to put it to a VS-code-extension.
In this case, are there commands for the IW that I could use to generate new cells by VS-code-command?

**Comment by IanMatthewHuff** [comment]
@lfriedri Yeah, what you are describing (Cell modification API) would be driven by a VS Code extension better, not by code. The API guild here is a good place to get started here:
https://code.visualstudio.com/api/extension-guides/notebook#:~:text=The%20Notebook%20API%20allows%20Visual%20Studio%20Code%20extensions,allows%20for%20similar%20experiences%20inside%20Visual%20Studio%20Code.
I will say that this might be specific to notebooks (versus the interactive window) so using this API on the interactive window might take a request on the core vscode repo.
