### ISSUE TITLE
center align the plots in output cells

### ISSUE THREAD

**Issue by cenkt** [microsoft/vscode-jupyter#7449]
Can we have the option to center align the plots in output cells in notebooks?

**Comment by cenkt** [comment]
In jupyterlab I am able to do this by adding
 
`.p-Widget.jp-RenderedImage.jp-mod-trusted.jp-OutputArea-output {
  /*display: table-cell;*/
  text-align: center;
  /*vertical-align: middle;*/
}`

to the css files of the lab themes.

**Comment by DonJayamanne** [comment]
This issue has been open for a while and hasn't seen any interest in the past year, hence closing this
