### ISSUE TITLE
VS Code referencing multiple python interpreters (local and remote)

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#7450]
Issue Type: <b>Bug</b>

VS Code referencing multiple python interpreters (local and remote)

Possibly another cause of the issues listed below:

https://github.com/microsoft/vscode-jupyter/issues/7448
https://github.com/microsoft/vscode-jupyter/issues/7446
https://github.com/microsoft/vscode-jupyter/issues/7445
https://github.com/microsoft/vscode-jupyter/issues/7444
https://github.com/microsoft/vscode-jupyter/issues/7329
https://github.com/microsoft/vscode-jupyter/issues/7322

For some reason, the VS Code Jupyter Extension gets confused and starts an Interactive Window with the ***local*** Python interpreter even ***after*** I used <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> and selected `Jupyter: Specify local or remote Jupyter server for connections`, and specified my remote server url+token, reloaded, then used <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> and select `Jupyter: Create Interactive Window`.

Sometimes it takes several attempts to get the Interactive Window to start at all, but once it does I can click on the kernel icon in the upper right of the Interactive Window and change it to the remote kernel.

Why is the local kernel still have to be selected in the lower Status Bar?  I believe in previous versions the Status Bar would also show the remote kernel.

Extension version: 2021.8.2031190714
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (1.05GB free)|
|Process Argv|--crash-reporter-id 1e88d7ed-dfc2-42ed-b5d3-970568cb872e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn478:30356813
pythonvspyt187:30362782
pydsgst2:30361792
vscus224cf:30358040
vssid140:30362080

```

</details>

**Comment by IanMatthewHuff** [comment]
Tracking resolution in #7448
