### ISSUE TITLE
Ensure we display IW before creating the Notebook controller

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7458]
Today we wait until the controller has been created before displaying the IW
With remote this will be much slower, as we now need to connect to the server & fetch kernels (looking at the code today, thats a lot of remote API calls, at least 4) & that's slow.

This results in the following experience (which has been brought up in the past):
* We display a progress message
* IW is slow to load

In the past, the IW would load immediately and we wait (display progress).

I think we should do this.

Will also make it easier to support multiple languages in IW

**Comment by joyceerhl** [comment]
How slow is it right now?

**Comment by DonJayamanne** [comment]
Its a visual issue. 
Are you now suggesting we not do this?

**Comment by DonJayamanne** [comment]
Please feel free to close this, I thought you agreed this was a better way to do things.

**Comment by joyceerhl** [comment]
I'm just asking for clarification 😊 I still think we should do this. The severity of the delay impacts the prioritization of this work

**Comment by amunger** [comment]
@DonJayamanne - is this still something to be done? It looks like we get connection info to create a controller object, before opening the IW, but it opens before we start actually connecting.
With a local kernel it feels instant, but is there still a slow remote workflow?

**Comment by DonJayamanne** [comment]
Lets close this now.
