### ISSUE TITLE
Implement Live Share for native interactive window

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#7460]
Some people are still trying to use this https://github.com/MicrosoftDocs/live-share/issues/4032#issuecomment-914737341

**Comment by TamirShklaz** [comment]
+1 would really like this feature :)

**Comment by janyas188** [comment]
hi,

I was just wondering if this feature is likely to be bought back soon? I was hoping to use an interactive window in my current project and would also be useful in other future projects?

**Comment by rchiodo** [comment]
@janyas188 I recommend commenting on the liveshare issue. We (the jupyter team) would likely not be implementing this.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
