### ISSUE TITLE
Re-work restart kernel to just kill IKernel & start a new IKernel

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7463]
Remove all of the code around restarting kernel & just treat it as:
* Stop kernel
* Start a new kernel

Very similar to user switching to a new kernel.

@joyceerhl not sure if this is a dup issue, but this is something you indicated you'd work on last sprint, I'm assuming you'd still want to tackle this during the next debt week.

I'd like to see this done sooner as we have a few issues with kernel restarts (flaky tests) & feel it would be resolved if we just nixed the kernel process completely.

**Comment by joyceerhl** [comment]
Note, make sure to propagate restart to CellHashProviders. Presumably IKernelProvider will emit the restart event instead. Maybe we can fix up the CellHashProvider to handle the IKernelProvider restart event and hookup the relevant listener there?

**Comment by DonJayamanne** [comment]
>  handle the IKernelProvider restart 

If kernel restart is just a kill kernel & start a new kernel, will we need the event `restart` at all?
Else it gets confusing,

**Comment by DonJayamanne** [comment]
closing as i don't think we need this anymore.
lot of the extension is getting refactored
