### ISSUE TITLE
Ability to configure run key in interactive window

### ISSUE THREAD

**Issue by philnagel** [microsoft/vscode-jupyter#7464]
Hello!

I've been really enjoying the interactive window feature. One small item that has been difficult for me is that from all other Python IDEs I'm used to, the shortcut to execute code within the REPL (not the editor) is usually just ENTER, not SHIFT+ENTER.

I understand the necessity of using SHIFT+ENTER within the editor to send code to the interactive window. However, is it possible to allow configuration of  the shortcut just in the interactive window itself to make ENTER run the code, not start a new line?

To be very clear, I'm just asking about doing this within the interactive window (the area where it says "Type code here and press shift-enter to run", not within the editor window of VS Code.

**Comment by rchiodo** [comment]
Good news, this is already supported. You can create your own custom keybinding for the command 'interactive.execute' like so:

```json
// Place your key bindings in this file to override the defaults
[
    {
        "command": "interactive.execute",
        "key": "enter"
    }
]
```

**Comment by philnagel** [comment]
Thank you, once I made sure all of my extensions were at the latest version, this worked great, I did have to add one minor tweak with the below `when` condition, otherwise, the `enter` key stopped working for newlines across the entire application:

```
// Place your key bindings in this file to override the defaultsauto[]
[
    {
        "key": "enter",
        "command": "interactive.execute",
        "when": "resourceScheme == 'vscode-interactive'"
    }
]
```

**Comment by philnagel** [comment]
And actually one more tweak was needed, as it was not possible to select IntelliSense suggestions either:

```
// Place your key bindings in this file to override the defaultsauto[]
[
    {
        "key": "enter",
        "command": "interactive.execute",
        "when": "resourceScheme == 'vscode-interactive' && !suggestWidgetVisible"
    }
]
```
