### ISSUE TITLE
Variable explorer doesn't update correctly

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7468]
Variable list seems to behave inconsistently:

- Open IW
- Click back on python file
- Variables still work
- Open HTML file
- Variables still there but you can't click on anything
- Click on DF viewer
- Variables still there but you can't click on anything
- Click on IW
- Variables there
- Click back on DF viewer
- Variables disappear?

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/165445
