### ISSUE TITLE
White background fills entire output cell for Matplotlib plots

### ISSUE THREAD

**Issue by ianholst** [microsoft/vscode-jupyter#7470]
When I make a simple matplotlib plot, there is a white background covering the entire output cell area, which is pretty jarring in dark themes. I would expect it to only be white in the area immediately behind the figure. Also, I'm not sure why there is a small dark cutout in the lower right corner of the white background.

![vscodejupyter](https://user-images.githubusercontent.com/2507974/132594559-4067104f-2304-4c2e-aecc-533a11e4a68f.png)

I'm guessing that it's built this way because by default, the figure background is transparent. However, even if the plot image was partially transparent, I would not expect that to affect any parts of the screen beside the image itself, so this might be undesirable behavior.

## Steps to reproduce:

1. Create new blank notebook
2. Enter code in cell:
```python
import matplotlib.pyplot as plt
plt.figure()
plt.plot([1,2], [1,2])
plt.show()
```
3. Run cell

## Environment data

-   VS Code version: 1.61.0-insider
-   Jupyter Extension version: v2021.9.1001208778
-   Python Extension version: v2021.10.1210725981-dev
-   OS: Windows 10
-   Python 3.9.7
-   Type of virtual environment used: none
-   Jupyter server running: Local
-   No other extensions running besides Python + Jupyter

**Comment by DonJayamanne** [comment]
THanks for filing this issue.
I think we need to fix this, have had similar reports in the past as well https://github.com/microsoft/vscode-jupyter/issues/7066

**Comment by greazer** [comment]
The problem here is that to fix this we would likely need to parse the matplotlib html to tweak what the output looks like. Then on top of that we have VS Code themes to worry about. We're not likely going to make a change here in the near future.

**Comment by ianholst** [comment]
Perhaps an option to turn it off then, with it on by default?

**Comment by DonJayamanne** [comment]
Re-opening to discuss this:
We can apply the background to the image element instead of the container DIV, that would solve the issue

**Comment by ianholst** [comment]
I think that would be an ideal solution. Thank you!

**Comment by IanMatthewHuff** [comment]
Verified, but buttons are floating off on the right now, I'll open a new issue for that seems a bit off to me:
![image](https://user-images.githubusercontent.com/812783/135359738-440f0604-dd4d-4269-9f56-6eeff53de951.png)

**Comment by charlieh108** [comment]
Hi, 
I'm sorry if this isn't the right place, but I seem to have almost the exact opposite error! 

My preference would be to have the figure of the plot all in white so the axis labels can be seen against a white background, like in IanMatthew's display. 

I've tried all variants of the settings but I can't stop the overall figure from being transparent - am I missing something ? 




<img width="658" alt="Screenshot 2022-01-21 at 11 25 20" src="https://user-images.githubusercontent.com/26016072/150519181-0220fc38-8e50-4a83-b70b-43130b063ac8.png">

**Comment by IanMatthewHuff** [comment]
@charlieh108 Can you post what you see in the </> button next to the chart? Looks like you might not be using the correct renderer here.

**Comment by charlieh108** [comment]
Hi @IanMatthewHuff  - thanks for responding ! 

I get the issue with both the svg+xml and png renderer, as so
![Screenshot 2022-01-26 at 18 57 04 (2)](https://user-images.githubusercontent.com/26016072/151228422-b81a58c6-6811-4d9b-92d0-2d843ba6e44b.png)
!
<img width="1680" alt="Screenshot 2022-01-26 at 18 57 04" src="https://user-images.githubusercontent.com/26016072/151228404-23a67b8d-94dd-455b-bf44-846e80f8bf02.png">

In this photo I am using the atom colour theme, but I've had this problem using the vscode default, so I'm certain this is not the cause of the problem. 

Thanks for the help !

**Comment by IanMatthewHuff** [comment]
@charlieh108 Looks like you might be missing the Jupyter renderers extension. VS Code separates execution from display so different extensions can provide different output renderings. The Jupyter renderers extension is supposed to install with the main Jupyter extension, but it looks like you are missing it. Try installing that, it should provide the right views:
![image](https://user-images.githubusercontent.com/812783/151244455-c78f822c-44e0-4342-a18d-74cdc1840aa0.png)
![image](https://user-images.githubusercontent.com/812783/151244659-823e14f4-0141-49d4-bc26-deeb26908ebf.png)

You can see in my second image that it's using the renderer from that extension.

**Comment by charlieh108** [comment]
It was exactly that - thanks so much !

**Comment by hanwencat** [comment]
run the magic command before plotting your figure:

`%matplotlib inline`

You might need to run your plot code twice to see the effect of the above magic command.

**Comment by songololo** [comment]
I don't know what exactly it does, but there is a `vscode` setting which may or may not help in this instance:
```json
 "jupyter.themeMatplotlibPlots": true,
```
