### ISSUE TITLE
Retina display option for Matplotlib does not work as intended

### ISSUE THREAD

**Issue by ianholst** [microsoft/vscode-jupyter#7471]
## Expected behavior

Using the command `%config InlineBackend.figure_format = "retina"` in a Jupyter notebook allows matplotlib plots to match the true resolution of a high DPI display, as shown here in the browser version of Jupyter:

![browser_retina](https://user-images.githubusercontent.com/2507974/132598687-ff5356cb-8fb1-4e38-8d9d-0543513738d3.png)

## Actual behavior

I am using a system with 200% display scaling, and when I enable the retina format in a notebook in VS Code, it makes the plot image twice as big. The image output has the right number of pixels, but because it is scaled at the same level as the non-retina output, it is still blurry and is now too large to be practical.

![retina](https://user-images.githubusercontent.com/2507974/132598285-960fb63f-997e-4d89-96ea-20b04911fd1d.png)

## Steps to reproduce:
1. Create new blank notebook
2. Enter code in cell:
```python
import matplotlib.pyplot as plt
%config InlineBackend.figure_format = "retina"
plt.figure()
plt.plot([1,2], [1,2])
plt.show()
```
3. Run cell

## Environment data

- VS Code version: 1.61.0-insider
- Jupyter Extension version: v2021.9.1001208778
- Python Extension version: v2021.10.1210725981-dev
- OS: Windows 10
- Python 3.9.7
- Type of virtual environment used: none
- Jupyter server running: Local
- No other extensions running besides Python + Jupyter

**Comment by DonJayamanne** [comment]
Thanks I can replicate this issue and will get this fix soon.

**Comment by doublezz10** [comment]
Hi! Is this issue related to how matplotlib outputs in the interactive window don't respond to changing figsize?

Figures will render correctly if I manually change the mimetype from png to svg -- but I haven't been able to find the setting to make this behavior permanent/default.

**Comment by DonJayamanne** [comment]
No, its just a bug at our end (in the extension).
