### ISSUE TITLE
If I open an ipynb and then select a kernel for it, opening a Python terminal should activate the same environment

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7478]
1. Open a folder with an ipynb file in it.
2. Choose an existing kernel you know works.
3. Open a Python Terminal via the command

I would think that the Python terminal that's opened would match the environment selected for the notebook kernel. Instead you get the environment set for the Python extension, which isn't visible in the status bar.

**Comment by SiddhanthUnnithan** [comment]
How do you reconcile which extension gets precedence for the environment? As a user I can select a kernel in my notebook that is different from an interpreter that I select through the python extension.

How do we know that when the user opens the terminal they intend to use the environment as per the kernel selection and not the one they had set through Python?

**Comment by SiddhanthUnnithan** [comment]
Are you proposing that when the notebook file is in view then the terminal should reflect the kernel selected, and when a Python file is opened (thus showing the interpreter in the status bar) the terminal should use the interpreter?

Does the VS Code terminal have the ability to use file context to execute commands? I was under the impression that the Python extension is the one that contributes the environment activation on all "terminalCreate" events?

**Comment by greazer** [comment]
Yes, I'm proposing that when a Python notebook file has focus, if the user *creates a Python terminal* that terminal is created using the interpreter and environment associated with the selected kernel of the notebook. You could argue that the currently selected interpreter for Python is literally changed every time a notebook gets focus so as to match. If the user switches back to a Python file, then whatever was selected by the user for Python alone would be selected. Here's a more detailed walkthrough of the problem I ran into.

1. I opened an ipynb file and chose a specific kernel in which to run. 
2. I knew that there were packages I needed to install into that environment, so I launched a Python terminal erroneously thinking it would be the same environment used for my kernel.
3. I unknowingly installed the needed package into the wrong environment.
4. I ran the first cell and ... I was told the package couldn't be found.
5. I realized my mistake and entered this bug.

An alternative here is to implement the scratchpad or interactive window for notebooks idea. That way the user can stay in "notebook mindset" when doing these types of operations.

**Comment by DonJayamanne** [comment]
Why are you using a terminal?
Notebooks have the ability to run shell scripts.
I would like to find out how many users use the terminal while using notebooks. I feel a notebook is sufficient to run shell scripts (pip install etc)

**Comment by SiddhanthUnnithan** [comment]
@greazer, your workflow makes sense to me. The terminal environment should reflect the currently selected kernel or interpreter. As mentioned earlier, I think the Python extension **always** tries to activate the conda environment in a new terminal. This means that any other extension that writes to the terminal can, in theory, override the environment set by the Python extension. The work here would involve the Python extension modifying its current approach and only activating the environment when the user was previously in a non-Notebook view (i.e., don't have a notebook open). I'm assuming they have the ability to do that given they're able to hide the current interpreter.

I also strongly +1 Don's question about terminal usage with notebooks. From conversations with users we've learnt the following:
1. Writing shell commands in a notebook is good for auditability and reproducibility. A shared notebook will include all state changes made to a base environment (usually captured in an env.yml or requirements.txt file).
2. When "operationalizing" a notebook, users often clean it and remove shell commands, most likely moving them to their original env artifact.

My hypothesis is that notebook users are more inclined to writing shell commands in the notebook itself for the sake of auditability and reproducibility. I'd guess that we're less likely to see context-switches from a notebook to a terminal. VS Code is different in that users can view their current notebook and terminal in the same window context. If we use Jupyter classic as an example, we can see that users have to leave their current notebook, navigate back to the server landing page, create a terminal, and then execute commands. All subsequent terminal operations require going back and forth between the notebook and terminal tabs.

**Comment by DonJayamanne** [comment]
I think this should be labeled communit though.

**Comment by greazer** [comment]
Perhaps we should have Python disable their terminal command when a notebook is active. We could provide a replacement that does something more reasonable.

**Comment by SeaDude** [comment]
I experience the same problem. 
1. Using the VS Code Terminal, create a new directory. Example `oop`
2. Create a new virtual environment in `oop` using `python -m venv .venv`
3. Activate the .venv using `.\.venv\Scripts\activate`
4. Create a new Jupyter Notebook file. Example `oop.ipynb`
5. Using the Jupyter Notebook, select the kernel to use. 
    - ISSUE 1: It doesn't always work to select the `.venv` kernel
    - ![image](https://user-images.githubusercontent.com/8636973/196009962-aa4a5343-2135-4663-bf6e-0293e3149d72.png)
6. Back to the VS Code Terminal, install libraries. Example: `pip install requests`
7. Back to the Jupyter Notebook, run `import requests`
    - ISSUE 2: This doesn't always work. Sometimes I receive the error "Can't find requests", etc. 

It would be nice to have a more solid connection between the VS Code Terminal environment and the selected Jupyter Notebook kernel.

I could be hallucinating but to find someone with such a similar issue... there may be some meat to it.

**Comment by DonJayamanne** [comment]
This issue has been open for a while and we haven't had any upvotes on this issue since, hence closing this for now
