### ISSUE TITLE
zh-tw translation suggestion

### ISSUE THREAD

**Issue by ted1030** [microsoft/vscode-jupyter#7479]
VS Code 1.60
Windows 10 20H2
Python extension 2021.9.1191016588
Jupyter extension 2021.9.1001205359

![image](https://user-images.githubusercontent.com/37107237/132031393-5ed3dfce-40dc-4ed0-9a89-b9141d29019e.png)
Restart: 重新啟動
Restart Kernel: 重新啟動核心
Interrupt: 中斷
Interrupt Kernel: 中斷核心
Variables: 變數
Open Variables View: 開啟變數面板
Export: 匯出
Export As: 匯出為

When clicking "Export"
![image](https://user-images.githubusercontent.com/37107237/132033279-3989caae-f432-4568-9745-5b9408db181c.png)
Export As: 匯出為

When clicking "Restart"
![image](https://user-images.githubusercontent.com/37107237/132042805-924d0ac9-f40a-4868-b2bf-d73c356025f8.png)
Restarting Jupyter Kernel: 重新啟動 Jupyter 核心中

![image](https://user-images.githubusercontent.com/37107237/132032939-ded38eb1-34af-423a-83b2-93e012a6ecd5.png)
Run by Line (F10): 逐行執行 (F10)
Continue (F10): 繼續 (F10)
Debug Cell: 偵錯儲存格
![image](https://user-images.githubusercontent.com/37107237/132030358-13d820ce-26d3-498c-9192-2e9899168912.png)
Show Cell Line Numbers: 顯示儲存格行號
![image](https://user-images.githubusercontent.com/37107237/132034342-44ddc107-c8dc-4af9-8bbb-72b53e50f325.png)
Convert a Notebook to Python Script: 轉換筆記本至 Python Script
Open in Notebook Editor: 在筆記本編輯器中開啟
Run by Line: 逐行執行
Show Cell Line Numbers: 顯示儲存格行號
![image](https://user-images.githubusercontent.com/37107237/132248836-3e90202c-e927-4bd2-8ee9-119dfafdc359.png)
"JUPYTER: VARIABLES": "JUPYTER: 變數"
Name: 名稱
Type: 類型
Size: 大小
Value: 值
No variables defined: 尚未宣告變數

![image](https://user-images.githubusercontent.com/37107237/132044892-4c0db920-2225-49f9-bf8d-312934ebbd51.png)
Debug python file in terminal: 在終端機中偵錯 Python 檔案
Run current file in interactive window: 在互動式視窗中執行目前檔案
Run from line in interactive window: 在互動式視窗中從此行執行
Run Selection/Line in Interactive Window: 在互動式視窗中執行選定內容/行
Run from line in interactive window: 在互動式視窗中執行到此行

**Comment by greazer** [comment]
@ted1030, can you please make the suggested modifications within a PR? We'll take a look and integrate assuming it looks good. 

Here's the file: https://github.com/microsoft/vscode-jupyter/blob/main/package.nls.zh-tw.json
