### ISSUE TITLE
Undo cell delete not working

### ISSUE THREAD

**Issue by anthony169dollarsign** [microsoft/vscode-jupyter#7486]
## Environment data

-   VS Code version: Version: 
> 1.60.0 (user setup)
> Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
> Date: 2021-09-01T10:41:52.311Z
> Electron: 13.1.8
> Chrome: 91.0.4472.164
> Node.js: 14.16.0
> V8: 9.1.269.39-electron.0
> OS: Windows_NT x64 10.0.19042

-   Jupyter Extension version (available under the Extensions sidebar): 
> v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): 
> v2021.9.1218897484
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 
> 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): NA
-   Jupyter server running: Local 

## Expected behaviour
- Pressed 'Z' to undo cell delete
- Cell is restored 

## Actual behaviour
- Nothing happens

## Steps to reproduce:

- Created code chunk
- Deleted code chunk
- Pressed 'Z' to undo cell delete
- Nothing happens 😢

**Comment by DavidKutu** [comment]
Thanks for filing @anthony169dollarsign!

I can repro your issue on our latest extension and I'll make sure we talk about it during our next meeting.

**Comment by DavidKutu** [comment]
FOR TRIAGE: probably transfer this to vscode.
