### ISSUE TITLE
With two notebooks side by side, enabling restart and interrupt buttons in one notebook also enables them in the other

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#7487]
1. Open two notebooks side by side. Restart and interrupt buttons should be initially disabled in both
2. Run code in one notebook
3. 🐛 Restart and interrupt buttons are enabled in both. They should only be enabled in the one that is actually running

![image](https://user-images.githubusercontent.com/30305945/133009428-2b4de884-29af-42e0-bc38-17852300f285.png)

**Comment by greazer** [comment]
it's possible this could cause buttons to be disabled when they need to be enabled.

**Comment by DonJayamanne** [comment]
Note: We might be able to get this working with the new when clauses added by @roblourens to vscode core.

**Comment by roblourens** [comment]
Definitely. You can follow the same pattern from debug/run-by-line

**Comment by DonJayamanne** [comment]
This should be fixed, no idea when it wasx fixed, but its working now as expected
