### ISSUE TITLE
Connecting to Python environment on first run of Notebook takes super long

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-jupyter#7489]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001228862
-   Python Extension version (available under the Extensions sidebar): v2021.9.1218897484
-   Python and/or Anaconda version: 3.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

Version: 1.61.0-insider (Universal)
Commit: ec40cbe164c59f3d13b6eff5fc7b0231ec0ab7aa
Date: 2021-09-13T05:13:59.036Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

## Problem

I opened a notebook for the first time on my machine that I had cloned from: https://github.com/claudiaregio/data-science

I created a conda environment with the YAML file in the repo. I activated that environment with Python 3.7.

After I selected the kernel it took 45 seconds to connect to the environment. At minute 3:15 of this [video](https://msit.microsoftstream.com/video/71920840-98dc-ae72-3a43-f1ec149ab77a)

**Comment by DonJayamanne** [comment]
@tanhakabir 
Please could you repeat this and capture the logs from the `Jupyter Output` panel & paste that here

**Comment by tanhakabir** [comment]
I deleted my repo, freshly cloned, and  tried picking my activated env again without screensharing on and I can't seem to repro this issue. Not sure if it's fixed or I'm in a better state now. Going to close this issue for now until I see it again
