### ISSUE TITLE
Continue running the rest of the cell during RBL

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#7494]
We should have a way to allow ending the RBL session and running the rest of the cell. Right now pressing F5 will do this by triggering the debug "continue" command.

Ideally this would be a button in the cell toolbar but we don't want to shift the position of the RBL button when you click it to start a session, this is annoying.

**Comment by DavidKutu** [comment]
This is possible with ctrl+enter. But I agree, a cell button would be more visible.

We could go back to what we had. The interrupt button on the left stops run by line and interrupts execution, and another button on the cell toolbar stops RBL but continues executing.
