### ISSUE TITLE
Debug Cells / Run Cells are selecting wrong cell / wrong lines after 2nd Debug Cell.  Freezes after 3rd Debug Cell.

### ISSUE THREAD

**Issue by ThisntWorking** [microsoft/vscode-jupyter#7496]
## Environment data

-   VS Code version: 1.60.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): 3.7/2.7/3.9 (all)
-   OS (Windows | Mac | Linux distro) and version: Mac 11 & Ubuntu 20
-   Python and/or Anaconda version: 3.7/2.7/3.9 (all)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv & no environment affected
-   Jupyter server running: Issue on Local & Remote

## Expected behaviour

This is a 100% clean install. Problem is on Mac OS and Ubuntu.

I have a plain .py file and use "# %%" Cell Marker (jupyter.defaultCellMarker).  When I click "Debug Cell", it debugs the cell properly. When I click on any random cell, it debugs that cell properly line-by-line.  When I interrupt the kernel, it stops, but allows me to debug cells.

## Actual behaviour

When I click "Debug Cell", it will only allow me to debug that cell and ONLY that cell.  This prevents me from debugging any other cell. If I try to debug another cell, it will still highlight the first cell that was debugged.  However, the output will be from the selected cell.

Issue exists on mac and ubuntu with clean installs of VSCode + Extensions.  

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create a .py file
2. Add the following code to the file:
```
# %%
print(1)
print(2)
print(3)
# %%
print(4)
print(5)
print(6)
# %%
print(7)
print(8)
print(9)
```
3. In VS Code, select the second cell's "Debug Cell" command.
4. Iterate through print lines 4, 5, 6. 
5. In VS Code, select the third cell's "Debug Cell" command.
6. It will select cell with print statements for 4, 5, 6, instead of 7, 8, 9.  When iterating, the output will be 7, 8, 9.  Which doesn't match the selected cell.
7. Select the first cell.
8. Extension will freeze. There will be no ability to iterate / debug the cell.  Interrupting the kernel does not work.  Only kernel restart works.
9. 
![vscode_problem](https://user-images.githubusercontent.com/89668626/133147034-8634bcca-f8ea-4cd5-af0f-080d18e2cdff.gif)

Any ideas about a workaround or a fix for this?

</details>

**Comment by DavidKutu** [comment]
Thanks for filing @ThisntWorking.

We'll discuss in our next triage meeting.

**Comment by ThisntWorking** [comment]
@DavidKutu Is this a known problem or a new one?  It's been happening for at least two months now.  I'd love to know even a workaround for this bug. Thx

**Comment by greazer** [comment]
This may be related to the version of ipykernel you have installed in your environment. What is it? If it's version 6, it's a known issue #7141

**Comment by ThisntWorking** [comment]
@greazer  Jim, I'm using IPython 7.27.0.

I can try another one if it helps for testing.  Just let me know which one to try.

**Comment by DavidKutu** [comment]
Thanks for getting back to us @ThisntWorking.

We meant the ipykernel version. For instance, if you're using pip run `pip show ipykernel` and that should show the version.

**Comment by ThisntWorking** [comment]
@DavidKutu @greazer Apologies.  I have  ipykernel Version: 6.2.0. Is there an alternative version that I should try?

**Comment by DavidKutu** [comment]
This is the same as #7141 then. Glad you found a workaround.
This should be fixed in our next release anyway.

**Comment by shaperilio** [comment]
I'm seeing the same thing; I put a note in #7141 as well. Mine doesn't "freeze" with necessarily on the third debug attempt, and the only way to get things working again is to close the interactive window (restarting the kernel does not do it).

Here's what I see which closely replicates what @ThisntWorking saw:
Debug cell 3. Stops on the right line of code.
Debug cell 4. Stops on the same line of cell 3, because cell 3 is the top-most cell that has been executed (see my comment on #7141).
Debug cell 2. Debugger is stuck. Disconnecting from it, and any attempt to do anything after that, results in these empty "Canceled" popups until I close the interactive window.

![efc199c6-d7dc-431f-bd9b-16d6e741f023](https://user-images.githubusercontent.com/26465923/133344925-a25f2179-6aa2-4f02-9ca5-1ccb25d75b75.gif)

If you've run any cells before, then the debugger will get stuck on the _second_ time, not the third.
