### ISSUE TITLE
Update kernel preloads  to use JS modules

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#7519]
VS Code would like to switch kernel preload scripts to use JS modules instead of being global scripts: https://github.com/microsoft/vscode/pull/132088

This better aligns kernel preloads with renderer script and lets us define a much cleaner and clearer API for extension authors. 

The kernel preload api is still proposed but Jupyter is using it to load several scripts. We'd like to get Jupyter migrated over so that we can remove our support for global scripts and also test out this updated proposal

If you need to preload a global script that was not written with module support in mind (such as requirejs), try either:

- Have the preload module inject a script tag for the global script into the notebook webview
- Manually export any globals you need onto the `window` object

**Comment by rchiodo** [comment]
We believe we need this done before we can implement this.
https://github.com/microsoft/vscode/issues/132557

**Comment by mjbvz** [comment]
You should be able to migrate over today using one of the approaches I suggested. Let me know if they don't work though 

microsoft/vscode#132557 is related but is about a bug that also exists today with the old, non-module based controller preloads

**Comment by DonJayamanne** [comment]
This has been completed
