### ISSUE TITLE
Use VS Codes markdown renderer to render text/latex

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7525]
The latex rendered by nteract is not right
Since we now support latex in VS Code core, we should utilize that & drop nteract (that will reduce the size of the renderers as well)

# Desired output in Jupyter (this is jupyter Lab)
<img width="508" alt="Screen Shot 2021-09-14 at 15 30 30" src="https://user-images.githubusercontent.com/1948812/133342382-da364b85-1e25-4b2e-9a67-f97824ea4936.png">
# Desired output in Jupyter (this is jupyter notebook)
looks like latex in markdown has been fixed in jupyter lab (& broken in notebooks)
<img width="575" alt="Screen Shot 2021-09-14 at 15 30 38" src="https://user-images.githubusercontent.com/1948812/133342384-ec366395-f709-4a29-a4ce-7c79e5211e78.png">

# This is today in VS Code (first cell is rendered by nteract, second cell using VS Codes markdown renderer)
Note how the second cell works (I'm using VS Code to render the output markdown, and latex also works).

**Solution: Get VS Code core to support text/latex as a supported mime type for markdown-it**

<img width="853" alt="Screen Shot 2021-09-14 at 15 27 31" src="https://user-images.githubusercontent.com/1948812/133342546-66711e40-cf40-4587-8249-4117e363adec.png">

# Benefits:
* No need to ship nteract to render text/latex
* Rendering of latex in markdown cells & outputs will be identical (as we're relying on built in renderers from VS Code core)
* Things work out of the box on github.dev (no need of custom renderers)

**Comment by DonJayamanne** [comment]
**Related** 
https://github.com/microsoft/vscode-jupyter/issues/5790
https://github.com/microsoft/vscode/issues/123144

**Comment by rchiodo** [comment]
This should be working now. Don updated our renderer to not be used anymore.

/verified:

![image](https://user-images.githubusercontent.com/19672699/150887660-f8e6bd60-feb4-432d-a020-f7842e308a07.png)
