### ISSUE TITLE
With ipykernel<6, breakpoints in cells are ignored if "jupyter.stopOnFirstLineWhileDebugging" is false

### ISSUE THREAD

**Issue by shaperilio** [microsoft/vscode-jupyter#7528]
## Environment data

Version: 1.60.1 (user setup)
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:07:10.714Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
Jupyter Extension: 2021.8.2041215044
ipykernel: 5.5.5

## Expected behaviour

```
# %%
print(3)
print(5) # <-- set breakpoint here
```

If I I hit the "debug cell" code lens button, it should stop at `print(5)`

## Actual behaviour

It does not stop and will simply run the whole cell in the debugger. It _will_ stop if:
1. You were to put a breakpoint in the `print` function somewhere.
2. You have the "jupyter.stopOnFirstLineWhileDebugging" setting set to True; this will start the debugger paused on the first line of the cell, and continuing from there will stop at the breakpoint.

**Comment by rchiodo** [comment]
Thanks for the bug. Easy to repro too. I'm guessing we're not sending the breakpoints early enough when there's no initial breakpoint, or we send them but the source isn't matching.

**Comment by rchiodo** [comment]
Note for anybody investigating. Set these to see what messages are getting sent to debugpy:

```
PYDEVD_DEBUG=True
DEBUGPY_LOG_DIR=<dir that already exists>
PYDEVD_DEBUG_FILE=<dir that exists, but new file allowed>
```

**Comment by roblourens** [comment]
Going to close this as it works fine with ipykernel 6, with the old debugging mode
