### ISSUE TITLE
Restarting the debugger in the interactive window leaves it in a stuck state

### ISSUE THREAD

**Issue by shaperilio** [microsoft/vscode-jupyter#7529]
## Environment data

Version: 1.60.1 (user setup)
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:07:10.714Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
Jupyter Extension: 2021.8.2041215044
ipykernel: 5.5.5

## Expected behaviour

```
# %%
print(3)
print(5) # <-- set breakpoint here
```

Click on the "debug cell" code lens button; it should either stop on the first line if you have that option set, or at the breakpoint (see #7528). Now click restart (Ctrl+Shift+F5). Debugger should restart and stop at the same place.

## Actual behaviour

Debugger restarts (the yellow highlight disappears) but is then left in a stuck state similar to #7496; pause, restart, and disconnect are the only things enabled and pause does nothing. My call stack shows this:
![image](https://user-images.githubusercontent.com/26465923/133350252-1f6b48fc-6306-4e51-8f4a-a7f7c34b3d51.png)

When the debugger is working and stopped at `print(3)`, the call stack looks like this:
![image](https://user-images.githubusercontent.com/26465923/133350323-e1bb9804-72c9-4fe5-b6a9-2d6d25c5653d.png)

Kind of seems like on restart the debugger gets stuck where it was?

**Comment by rchiodo** [comment]
Thanks for the bug. Not sure we've ever really even tried restart before.

**Comment by greazer** [comment]
If anything we need to just disable the restart debugger capability, since we can't support this due to the way we implement debugging (attach)

**Comment by roblourens** [comment]
Decided that it's not really possible to implement this correctly for the IW
