### ISSUE TITLE
Show source for changed or deleted cells

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#7532]
- Open a notebook with two cells. The first defines a function, the second calls it
- Execute the first cell, then delete it
- Set a breakpoint in the second cell
- Step in to the function defined in the deleted cell

You get an error message saying that a tmp path isn't available. You should get an editor with the source of the deleted cell

**Comment by greazer** [comment]
Jupyter Lab actually displays the code that's being debugged. We should consider doing something similar.

**Comment by roblourens** [comment]
It's hard to fix this, with the way debugging works with the "run and debug" command. We would need to dump a cell every time a cell is executed, just in case you will start debugging soon.

**Comment by DonJayamanne** [comment]
Closing this issue as not planned, users haven't reported issues similar to this nor have there been any upvotes
