### ISSUE TITLE
Debugger jumping out of the cell in Python Interactive

### ISSUE THREAD

**Issue by nonname313** [microsoft/vscode-jupyter#7537]
## Environment data

-   VS Code version: 1.60.1
-   OS and version: 10 20H2
-   Python version (& distribution if applicable, e.g. Anaconda): v2021.9.1230869389
-   Value of the `python.languageServer` setting: 'Default'

## Expected behaviour
Debugging the selected cell line by line

## Actual behaviour
Jumping to any line outside the cell, to a line which is not containing code. If you try to debug a second time after canceling vs-code raises "Canceled" and debugging is not working anymore at all.

## Steps to reproduce:

See vid.

https://user-images.githubusercontent.com/90767155/133424799-f19f9b96-5876-4617-8d9a-436894026114.mp4

**Comment by rchiodo** [comment]
Thanks for the bug. I believe this is because ipykernel 6 isn't currently working for interactive debugging. I see that you're using IPython 7.27 (which should indicate ipykernel 6 is in use).

See this bug here:
https://github.com/microsoft/vscode-jupyter/issues/7141

**Comment by rchiodo** [comment]
The workaround would be to go back to an earlier version of ipython.

**Comment by nonname313** [comment]
I have now installed iPython 7.3.0 with ipykernel 5.5.5 and for now it is working again thanks a lot! 
Which version would you recommend for interactive debugging for now and will there be an update?

**Comment by rchiodo** [comment]
Anything earlier than ipykernel 6.0 should work with interactive debugging in the short term. 

Once bug #7141 is fixed, ipykernel 6.0 should work as well.
