### ISSUE TITLE
Warn users when files override built in packages that could have caused the kernel to fail

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7538]
We still have a large number of users running into issues resulting from creating files such as `string.py`, `email.py`, `os.py`, `sys.py` etc
I think in the past 3 weeks we had 3 users running into this issue.

This causes a lot of issues, kernel don't start or when packages get imported dynamically kernels behave weirdly.

Solution:
* Keep a hardcoded list of reserved file names (use `help('modules')` to get a list of all built in modules)
This should also help Python extension, but not sure it matters as much for Python extension.

**Comment by greazer** [comment]
We've seen many users run into problems due to this issue. It affects us more than plain Python files.
