### ISSUE TITLE
When using Run Above / Run Cell, it causes Debug Cell and stepping to open new temporary file

### ISSUE THREAD

**Issue by ThisntWorking** [microsoft/vscode-jupyter#7544]
## Environment data

-   VS Code version: 1.60.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): 3.7/2.7/3.9 (all)
-   OS (Windows | Mac | Linux distro) and version: Mac 11
-   Python and/or Anaconda version: 3.7/2.7/3.9 (all)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local & Remote & "blank"

## Expected behaviour

When stepping through a function, the line-by-line should be shown in the source and not a temporary file.

## Actual behaviour

When stepping through a function, if the function is in a different cell, vscode opens the cell as a new temp file.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create a python file with the following code:
```
# %%

print(1)


def test():
    print('test()')

# %%


def test2():
    print('test2()')


test2()  # steps properly
test()  # creates a temp file

# %%
```
2. Click "Run Cell" for cell 1.
3. Click "Debug Cell" for cell 2.
4. Step through.
5. For the test2(), the file is properly stepped into.
6. For test(), vscode opens a temp file.

It appears to jump to the correct position in the source file if Debug Cell is used for cell 1.

I tried this with server type being "Remote" "Local" and blank. All have similar behavior.

![ss2](https://user-images.githubusercontent.com/89668626/133511994-c1eff194-d155-414b-a460-b71b6425765f.gif)

**Comment by rchiodo** [comment]
Thanks for the bug. I can repro locally. My guess is that we're not providing the hash correctly for already run cells. 

This repros for me with ipykernel 5.

**Comment by greazer** [comment]
This can also be reproduced by running a ```\#%% [markdown]``` cell before trying to debug.

**Comment by joyceerhl** [comment]
Not a regression, repros in webview interactive window from 1.58 too

![image](https://user-images.githubusercontent.com/30305945/134085734-6d0afa9c-b943-4e7e-b80f-214dbc44f6f9.png)

**Comment by roblourens** [comment]
Works fine now with ipykernel 6 at least
