### ISSUE TITLE
Hide breakpoints when in a RBL session

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7563]
* Use run by line
* Add 2 break points
* Hit the `Continue` button, and it will run to completion without stopping at the break points

Identified when @DavidKutu was demoing the `Continue` feature.

**Comment by DavidKutu** [comment]
This is intended, the button is meant to exit RBL mode and execute the cell normally.

**Comment by greazer** [comment]
We need to finalize the UI coordination between RBL and notebook debugging.

**Comment by DavidKutu** [comment]
We decided on hiding the breakpoints while using RBL. Not removing them, as they need to persist. Just hide them.

**Comment by roblourens** [comment]
We could switch them to look like this

![image](https://user-images.githubusercontent.com/323878/136642997-65142138-f090-44cc-86ce-e0ab5973d599.png)

I suspect that they are actually being bound but then manually skipped over by RBL

**Comment by roblourens** [comment]
I think this is ok, haven't heard about confused users
