### ISSUE TITLE
Can't check for ipykernel 6 on remote kernel 

### ISSUE THREAD

**Issue by Syndorik** [microsoft/vscode-jupyter#7576]
## Environment data

-   VS Code version: 1.61.0-insider a0af58197e4a1d3e82fbe3048e0549e622d19f4f  x64  
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001244851
-   Python Extension version (available under the Extensions sidebar): v2021.9.1230869389
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 18.04
-   Python and/or Anaconda version: Python 3.9.7 64-bit, conda 4.10.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote 

## Actual behaviour

I have Ipykernel version 6.4.1 installed, but the line by line debugger cannot seem to work. It always redirect me to the setup link telling me ton install ipykernel 6.2.0. I've downgrade ipykernel to this version, but still can't seem to work. 

Is it becasue I'm working on a remote instance?

**Comment by claudiaregio** [comment]
@Syndorik Can you please provide the jupyter output logs when this occurs

**Comment by Syndorik** [comment]
Well there are no output from jupyter logs even though I've set `"jupyter.logging.level": "verbose"`

The only thing I'm getting is the following
![image](https://user-images.githubusercontent.com/28219244/134140676-953004cb-d18e-49fc-ba9a-200e12876fb3.png)

I've also looked at python logs and there is nothing

**Comment by DavidKutu** [comment]
Thanks for filing @Syndorik, like you guessed, it is because of being remote. We're looking into it.

**Comment by Syndorik** [comment]
Ok thanks for the information!

**Comment by DonJayamanne** [comment]
@david what about the `startDebugging` method in `JupyterDebugger.ts` that still uses the old way to check the version of ipykernel.
You'd need to fix that one as well.

**Comment by DavidKutu** [comment]
@Syndorik, this will work on our release next week, and its available on our insiders build right now.
This was half the issue tho, this is the other half (https://github.com/microsoft/vscode-jupyter/issues/7690). We'll probably get to that one on out next iteration.

For now, this should work if you run a cell before debugging, otherwise, reloading VS Code will also fix it.

Thanks again for filing!

**Comment by Syndorik** [comment]
It works! Thanks a lot!
