### ISSUE TITLE
Empty Cells trigger Error when running multiple cells 

### ISSUE THREAD

**Issue by 1vecera** [microsoft/vscode-jupyter#7581]
Running multiple cells using any of Run All Cells, Run above, Run Below commands results in error if any of the cells is empty (does not have any code or comments).

## Environment data
![image](https://user-images.githubusercontent.com/32644386/133755273-ee528a6d-ba77-4216-8a53-a3008b2e4a42.png)

-   Extension version (available under the Extensions sidebar): v2021.10.1239554536-dev
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

## Expected behaviour

All cells will run.

## Actual behaviour

Runtime stops after empty cells get executed.

## Steps to reproduce:
Use run all cells, run current and below or run above on the following code.
```
#%%

#%%


#%%
print(5+5)

```

Whereas this will already run:

```
#%%
#
#%%
#

#%%
print(5+5)
```

**Comment by claudiaregio** [comment]
@1vecera I am not able to reproduce this issue. Can you provide a screen recording of this happening
