### ISSUE TITLE
Breaking RBL by clicking quickly

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#7584]
Do RBL on this cell:

![image](https://user-images.githubusercontent.com/323878/133866223-77f23a57-1649-47a2-9903-e82655aa51ba.png)

Click through it quickly, and get this error
![image](https://user-images.githubusercontent.com/323878/133866197-374491ee-b22f-4303-b563-9ee3666f5038.png)

Get some errors:

![image](https://user-images.githubusercontent.com/323878/133866249-8eac3ca6-35e6-4c88-88de-b14e51a85450.png)
![image](https://user-images.githubusercontent.com/323878/133866257-29fbc6da-f4ef-41aa-ac87-e71f3e6dfebe.png)

**Comment by roblourens** [comment]
I still get this error:

![image](https://user-images.githubusercontent.com/323878/134602385-e7676373-d991-4017-bc43-4464598b67b2.png)

I don't see any real user impact, but we should check it out to make sure it's not a sign of something going wrong

**Comment by DonJayamanne** [comment]
Unable to repro anymore.
