### ISSUE TITLE
Auto scrolling not working in the interactive window. 

### ISSUE THREAD

**Issue by vpn12out** [microsoft/vscode-jupyter#7587]
While running python file in Interactive window, I encountered the following bugs/issues

1.  I set `"notebook.insertToolbarLocation": "betweenCells"` in settings.json in `Jupyter: Jupyter Command Line Arguments` option, changes take place in jupyter notebook only, nothing happens in Interactive window, it still uses the default jupyter config in Interactive window.
2. Pressing Esc does not interrupt kernel when `while True:` loop is running.  The default `notebook.insertToolbarLocation` is `notebookToolbar` in which whenever I run `while True:` loop (never ending loop)  `notebookToolbar` hides the interrupt kernel option and Esc button is also not working due to which I cannot stop operation.
3.  Interactive window should auto scroll new outputs when the user is inputting inputs, because every time I have to scroll down to see new output in Interactive window.
4. There is a Text Output Limit in Interactive window. I cannot see my new outputs after showing some outputs. I have to input values after seeing the new outputs which I cannot do. Even after `Jupyter: Text Output Limit` to `0`, nothing happens in Interactive window.
5. Finally, I want to say that changes in jupyter settings should also affect the interactive window, also these should be must have feature in Interactive window. The full potential of Interactive window cannot be used. Also, any people prefer to run their python file in Interactive window instead in terminal.

Pls fix these bugs as soon as possible, also let me know once it is fixed.

Regards

## Environment data

-   VS Code version: Version: 1.60.1 (user setup)
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:07:10.714Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): v2021.9.1230869389
-   OS (Windows) and version: Edition	Windows 10 Home Single Language
Version	20H2
Installed on	‎08-‎08-‎2021
OS build	19042.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0

-   Python and/or Anaconda version: Python 3.9.6 64bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A 
-   Jupyter server running: Local

**Comment by joyceerhl** [comment]
1. `"notebook.insertToolbarLocation"` is not designed to work in the interactive window, since the interactive window reflects code execution from a Python file or the input box. Out of curiosity, would you find it helpful to be able to use the insert toolbar to add empty cells to the interactive window and execute them directly there, and why would you like to be able to do this in the interactive window as opposed to in a notebook?

2. `Jupyter Command Line Arguments` is only applied when `jupyter` is used instead of our raw kernel support via ZMQ:
https://github.com/microsoft/vscode-jupyter/blob/2d22f42bbfd407c36baff8bc1aee8870f693c916/src/client/datascience/interactive-common/notebookProvider.ts#L131-L140

If you set `"jupyter.disableZMQSupport": true` in your settings.json and configure your command line arguments, do you see your settings applied? E.g. this is what I get:

![image](https://user-images.githubusercontent.com/30305945/133941334-6c5c641e-4bc7-4735-bb84-f63002fce754.png)


3. You can invoke the `Jupyter: Interrupt Kernel` command from the command palette, or configure a custom keybinding for `esc` to run `Jupyter: Interrupt Kernel` in your keyboard shortcuts like so:

```
    {
        "key": "escape",
        "command": "jupyter.interruptkernel",
        "when": "jupyter.interactive.canInterruptNotebookKernel"
    },
```

4. Have you configured `"jupyter.alwaysScrollOnNewCell": true` in your settings to auto scroll to new outputs?

5. `"jupyter.textOutputLimit"` has been deprecated in favor of `"notebook.output.textLineLimit"`.

6. Which Jupyter settings do you find are not supported in the interactive window?

Please let us know if the suggestions above do not work for you.

**Comment by vpn12out** [comment]
> 1. `"notebook.insertToolbarLocation"` is not designed to work in the interactive window, since the interactive window reflects code execution from a Python file or the input box. Out of curiosity, would you find it helpful to be able to use the insert toolbar to add empty cells to the interactive window and execute them directly there, and why would you like to be able to do this in the interactive window as opposed to in a notebook?
> 2. `Jupyter Command Line Arguments` is only applied when `jupyter` is used instead of our raw kernel support via ZMQ:
>    https://github.com/microsoft/vscode-jupyter/blob/2d22f42bbfd407c36baff8bc1aee8870f693c916/src/client/datascience/interactive-common/notebookProvider.ts#L131-L140
> 
> If you set `"jupyter.disableZMQSupport": true` in your settings.json and configure your command line arguments, do you see your settings applied? E.g. this is what I get:
> 
> ![image](https://user-images.githubusercontent.com/30305945/133941334-6c5c641e-4bc7-4735-bb84-f63002fce754.png)
> 
> 1. You can invoke the `Jupyter: Interrupt Kernel` command from the command palette, or configure a custom keybinding for `esc` to run `Jupyter: Interrupt Kernel` in your keyboard shortcuts like so:
> 
> ```
>     {
>         "key": "escape",
>         "command": "jupyter.interruptkernel",
>         "when": "jupyter.interactive.canInterruptNotebookKernel"
>     },
> ```
> 
> 1. Have you configured `"jupyter.alwaysScrollOnNewCell": true` in your settings to auto scroll to new outputs?
> 2. `"jupyter.textOutputLimit"` has been deprecated in favor of `"notebook.output.textLineLimit"`.
> 3. Which Jupyter settings do you find are not supported in the interactive window?
> 
> Please let us know if the suggestions above do not work for you.

Hi, thanks for your reply
1. I understood about `"notebook.insertToolbarLocation"`
2. Sorry, but I was not asking for `Jupyter Command Line Arguments`
3.  I had already configured key binding, but found that holding `Esc` button for a bit longer can interrupt the `while True:` loop.
4. `"jupyter.alwaysScrollOnNewCell": true` is not working in interactive window
5. `"jupyter.textOutputLimit"` is also working in interactive window
6. 
![image](https://user-images.githubusercontent.com/88290750/134186823-2de0ae67-74a7-4a05-bf18-b6c1202f8d62.png)
As you can after showing this 👉` show more (open the raw output data in a text editor) ...` , no new outputs are shown
7. In simple words, pls tell how to get rid of this output limit and get auto-output scroll in interactive window. Also sending you the settings.json
![image](https://user-images.githubusercontent.com/88290750/134188363-807d1e3b-06e2-4678-b229-1b5e79c688dd.png)

Regards,

**Comment by joyceerhl** [comment]
Please try setting `"notebook.output.textLineLimit": 100000` instead of using `"jupyter.textOutputLimit"`.

Could you share a screen recording of `"jupyter.alwaysScrollOnNewCell"` not working please?

**Comment by vpn12out** [comment]
> Please try setting `"notebook.output.textLineLimit": 100000` instead of using `"jupyter.textOutputLimit"`.
> 
> Could you share a screen recording of `"jupyter.alwaysScrollOnNewCell"` not working please?

Hi, `"notebook.output.textLineLimit": 100000` is working, now there is no output txt limit. But, new outputs are not auto-scroll even after adding `"jupyter.alwaysScrollOnNewCell"`. Sending you a screen recording as requested

https://user-images.githubusercontent.com/88290750/134284865-3530162d-93b6-472a-9e57-0372a53f150f.mp4

As you can see in the video new outputs are not auto scroll I have to manually scroll the window to see new outputs.

Regards,

**Comment by vpn12out** [comment]
![image](https://user-images.githubusercontent.com/88290750/134578967-fda7dd42-a308-4af6-a977-b7c311e0092c.png)
Maybe because of this auto-scroll is not working ?

**Comment by rchiodo** [comment]
@vpn12out is this still reproing for you? Auto scrolling should be fixed now.
