### ISSUE TITLE
Output from .NET Interactive rendered as `[object Object]` after opening .ipynb

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode-jupyter#7594]
Related issue: dotnet/interactive#1592

Execute the following with the latest VS Code Insiders build with the latest Jupyter extension (ms-toolsai.jupyter) and the latest .NET Interactive extension (ms-dotnettools.dotnet-interactive-vscode):

1. Ctrl+Shift+P -> ".NET Interactive: Create new blank notebook" -> "Create as '.ipynb'" -> "C#".
2. Set the cell contents to `1+1` and execute.  The output of `2` is shown.
3. Ctrl+S to save the notebook somewhere.  This appears to cause the notebook to be closed and immediately re-opened.

RESULT:
After a few seconds the output of the cell changes from `2` to `[object Object]`, which seems to indicate that the save operation done in step 3 above serialized the cell differently.

The cell shape in the backing file looks like this:

``` json
{
 "cell_type": "code",
 "execution_count": null,
 "source": [
  "1+1"
 ],
 "outputs": [
  {
   "output_type": "display_data",
   "data": {
    "text/html": [
     "<div class=\"dni-plaintext\">2</div>"
    ]
   },
   "metadata": {}
  }
 ],
 "metadata": {
  "dotnet_interactive": {
   "language": "csharp"
  }
 }
}
```

But when the equivalent Python notebook is created/run/saved, the cell shape looks like this:

``` json
{
 "cell_type": "code",
 "execution_count": 1,
 "source": [
  "1+1"
 ],
 "outputs": [
  {
   "output_type": "execute_result",
   "data": {
    "text/plain": [
     "2"
    ]
   },
   "metadata": {},
   "execution_count": 1
  }
 ],
 "metadata": {}
 }
}
```

The immediately obvious differences are:

``` diff
 ...
- "execution_count": null,
+ "execution_count": 1,
 ...
-   "output_type": "display_data",
+   "output_type": "execute_result",
```

The cell output from .NET Interactive is created [here](https://github.com/dotnet/interactive/blob/30ee67015e4ee85a26992dc49f35f79e8756c1a5/src/dotnet-interactive-vscode/common/interactiveClient.ts#L436), but I couldn't see anything obvious regarding `"output_type"` or `"execution_count"`.

**Comment by jhoneill** [comment]
This appears to have changed between VS Code 1.59.1 and 1.60 
If I downgrade the .NET interactive extension it does not fix the problem, but if downgrade VS Code and downgrade the the Jupyter and .NET interactive extensions (other wise they don't load) correct functionality is restored. 
So my working config is  Code 1.59.1, Jupyter v2021.8.1195043623  instead of .1236758218  and dot net interactive 1.0.2404030 instead of 2409020

**Comment by brettfo** [comment]
@jhoneill Would it be helpful to test VS Code 1.59 with the latest .NET Interactive extension?  I can do a quick build of our latest bits, but drop the vscode engine version.

**Comment by jhoneill** [comment]
@brettfo  I just bumped the .NET interactive extension up to v1.0.2409020 and that's still OK.  
When I downgraded VS code it grey'd out .NET Interactive and Jupyter so I thought they might be be checking for specific version. I've taken Jupyter to v2021.8.1236758218  and still OK. 
So I'm fairly confident it is VS code itself not the extensions, even if that is something wrong in the extensions didn't show as a problem in 1.59.1 and do in 1.60.

**Comment by DonJayamanne** [comment]
@brettfo @jhoneill 
Please could you try the following:
* Run the notebook in .NET extension, confirm the output is displayed
* Disable the .NET extension & open the notebook
* Things work as expected

To me it feels like the .NEt extension is doing something and corrupting the notebook outputs.
@brettfo I've created a PR that might address this, see here https://github.com/dotnet/interactive/pull/1606
I haven't dug into this yet, but found that disabling the .NET extension does fix this (meaning there's going on in there)

**Comment by jhoneill** [comment]
@DonJayamanne  

If I disable the .NET interactive extension 
![image](https://user-images.githubusercontent.com/16209593/134399795-db86fe7b-a0ed-4427-9395-eb9bd2362521.png)
It falls back to python 3 and the content in the ipynb file is rendered correctly. 
If I re-enable the extension nothing happens until I switch Kernel and then it's [object Object] again.
![image](https://user-images.githubusercontent.com/16209593/134400596-50f42d30-fb9c-4803-abe0-2c58e8da7d30.png)
There is a moment as the ipynb opens when it is deciding which kernel it should use and ."Net Interactive" hasn't appeared at the top - for that moment the rendering is fine, then the .Net interactive kernel is selected and [object Object] appears . But only with V 1.60   If I go back to 1.59:  
![image](https://user-images.githubusercontent.com/16209593/134402792-6e0ccf60-e269-499d-8026-514aff305688.png)

It's something about the interaction of the extension and 1.60 which has changed compared with 1.59.

**Comment by DonJayamanne** [comment]
Looks like the upstream PR resolves this issue, https://github.com/dotnet/interactive/pull/1606#issuecomment-925305201
Closing for now, please feel free to re-open or create a new issue if that doesn't fix it.

**Comment by jhoneill** [comment]
@DonJayamanne  is there likely to be a 160.3 with that PR in it, or would you expect it it come in 161 or later ?
