### ISSUE TITLE
Native Notebooks - Kernel Information + Management 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#7598]
### Today's Experience: 
1. When a user first connects to a kernel, they're shown a notification in the bottom right corner. 

![image](https://user-images.githubusercontent.com/19276747/134089974-9125ad35-4663-4660-a7b7-44413ec8d181.png)

2. When a kernel is executing a cell, there is an 'In Progress' bar that goes across the top of cell that is running. There is also an 'In Progress' spinner when the cell status bar is not hidden. When the running cell goes off the screen, there is no "In Progress" indicator for the notebook. One thing users can use today as a proxy is the state of the "Interrupt Kernel" item in the global toolbar -- activated or grayed out. 

![notebook running](https://user-images.githubusercontent.com/19276747/134092256-5a4fbb91-472e-4cb4-ac72-7a1d2f82f501.gif)

3. When restarting a kernel, there is both a notification in the bottom right corner and an item in the global status bar. 

![image](https://user-images.githubusercontent.com/19276747/134093465-038d582a-46b2-455d-ab4a-163786b00da6.png)

4. When interrupting a kernel, there is an item only in the global status bar. 

![image](https://user-images.githubusercontent.com/19276747/134107200-04ac47fa-bb9b-4190-b59a-e1345948139e.png)

### Summary + Additional Thoughts: 
- There are 4 different locations today that surface different types of kernel related information for users. 
- Past user studies have shown us the global status bar items are tricky to find, so the interrupt kernel command that doesn't come with a notification can be easy to miss for users. 
- While there is a proxy for notebook running (interrupt kernel icon) it is static which could also lead users to believe the notebook kernel is frozen unless they scroll down to try and follow the notebook execution to validate. 
- Adding a global running indicator would be beneficial in the case when a user is working with one notebook, but when working with multiple, this would require they set focus on each one to understand state. 
- Creating an area that consolidates kernel status/information would reduce the number of places a user needs to look to and could allow us to surface additional information or actions for users such as RAM usage or shut down all kernels.

### Related Issues: 
- https://github.com/microsoft/vscode-jupyter/issues/5654
- https://github.com/microsoft/vscode/issues/130811
- https://github.com/microsoft/vscode-jupyter/issues/4731
- https://github.com/microsoft/vscode/issues/105040
- https://github.com/microsoft/vscode/issues/130611
- https://github.com/microsoft/vscode-jupyter/issues/7713
- https://github.com/microsoft/vscode-jupyter/issues/7864
- https://github.com/jupyterlab/jupyterlab/issues/4012

### Potential Idea: 

We have floated the idea around of a Notebook Panel for quite some time, this could be a good opportunity to surface notebook specific information related to kernel status (busy, idle, disconnected, etc), management (restart, kill, switch), RAM usage, etc. in one location for users. 
Very rough mockup of a potential idea below

![image](https://user-images.githubusercontent.com/19276747/134089526-a62032d5-9db1-46b9-9604-642fc2dbe97a.png)

**Comment by claudiaregio** [comment]
@davidanthoff /cc 
Wanted to get your thoughts on this -- based on what happens with the variable explorer the kernel management may need to live somewhere else

**Comment by IanMatthewHuff** [comment]
This is an older meta-issue that is capture in other individual issues. Closing as part of issue debt cleanup.
