### ISSUE TITLE
The view jumps around when a cell terminates

### ISSUE THREAD

**Issue by fschlz** [microsoft/vscode-jupyter#7602]
Issue Type: <b>Bug</b>

Just run any cell for a couple of seconds, go to somewhere else to code there, once the first cell terminates the view will jump back to that cell.
And it won't even be obvious where you are now.
It's pretty annoying, I'd prefer not to have this behavior.

Extension version: 2021.8.1054968649
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|--crash-reporter-id 178eeb0c-2c32-4365-b5f2-1acb97567330|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30353136
vsdyn478:30354110

```

</details>

**Comment by IanMatthewHuff** [comment]
@fschlz The notebook UI is currently moving pretty fast each VS Code release. I can't repro this issue on our current stable VS Code build of 1.60.0 and it looks like you are on an older version of Code (1.58.2). Do you repro the issue if you update to the most recent stable VS Code build?
