### ISSUE TITLE
Why is 'export to python' so slow? (investigate)

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7606]
## Environment data

-   VS Code version: 1.61-insiders
-   Jupyter Extension version (available under the Extensions sidebar): 2021.9.100xxxx

Sometimes this operation seems really slow. At least inconsistent.

**Comment by greazer** [comment]
Do we have to rely on nbconvert to convert from ipynb to py?

**Comment by IanMatthewHuff** [comment]
Closing old issue based on the new quick text convert option.
