### ISSUE TITLE
Notebooks do not support showing variable values in datatips (tooltips). IW does.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7609]
When executing code via the Interactive Window a user can see the values of variables that have been initialized in the kernel. 

![image](https://user-images.githubusercontent.com/11685408/134254118-407fc8b6-3401-4564-ac16-6dbf8b271de1.png)

Notebooks should be able to support the same behavior.

**Comment by IanMatthewHuff** [comment]
Dupe #1495
