### ISSUE TITLE
i cant import data science library with my python 3.9.6 on vs1.6.0

### ISSUE THREAD

**Issue by TBAFoundation** [microsoft/vscode-jupyter#7613]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>
import pandas as pd
import numpy as np
from dateutil.parser import parse
import matplotlib as mpl
import matplotlib.pyplot as plt
```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the bug. Can you share the message you get or the logs from the Jupyter 'output' tab? It's likely the kernel you're using is not the one you expect.

**Comment by TBAFoundation** [comment]
ModuleNotFoundError: No module named 'pandas'
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_1780/3960935202.py in <module>
----> 1 import pandas as pd
      2 import numpy as np
      3 from dateutil.parser import parse
      4 import matplotlib as mpl
      5 import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'pandas'

**Comment by rchiodo** [comment]
That would be expected if the python interpreter you're running the kernel with has no pandas installed. 

See this for more information:
https://pandas.pydata.org/docs/getting_started/install.html

How many pythons do you have on your machine? Which one did you install pandas into before? That would be the one you'd pick from this drop down:

![image](https://user-images.githubusercontent.com/19672699/134378156-681d167a-f54b-4ca6-bd24-7755d92abd69.png)
