### ISSUE TITLE
Multi-thread tests are failing randomly.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7620]
These two tests seem to fail randomly. Disabling for now
`More messages from background threads`
`Messages from background threads can come in other cell output`

**Comment by DonJayamanne** [comment]
Note: Re-enabling the tests, if this fails, we have sufficient logging to figure this out.
I'd prefer to keep the failing tests to get the logs.
Or if disabling the tests, please please point to the CI job so we can extract the logs and see what's wrong.

**Comment by rchiodo** [comment]
Did you want to submit the test changes here? I was going to move to February otherwise.

**Comment by DonJayamanne** [comment]
Moved to feb

**Comment by amunger** [comment]
[TestResultNotebook-remote-nonConda-3.9-desktop-ubuntu-latest.zip](https://github.com/microsoft/vscode-jupyter/files/9185232/TestResultNotebook-remote-nonConda-3.9-desktop-ubuntu-latest.zip)
still failing for remote scenario

**Comment by DonJayamanne** [comment]
Should now be fixed

**Comment by amunger** [comment]
and test case works when checked manually
