### ISSUE TITLE
Can't start Run by line when the cell toolbar is hidden

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode-jupyter#7630]
VS Code 1.61.0-insider + Jupyter extension v2021.9.1001261101

1. open an ipynb file. 
2. turn off the cell toolbar by toggling the following setting to "jupyter-notebook": "hidden"

    "notebook.cellToolbarLocation": {
        "default": "right",
        "jupyter-notebook": "hidden"
    },

3. No entry point for the "run by line" feature at this point (no command or other UI piece for run by line).

**Comment by DavidKutu** [comment]
This will be fixed by #1166
