### ISSUE TITLE
Run by line "Continue" icon color change unexpectedly

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode-jupyter#7633]
VS Code 1.61.0-insider + Jupyter extension v2021.9.1001261101

1. open an ipynb file
2. start "run by line" on a cell
3. notice the "continue" button on the cell toolbar is blue
4. click into the cell

expected: no change to the "continue" button
actual: the button changed to grey. it might be a small thing but it was confusing. for a second, i though maybe it was disabled but it's not.

please refer to this video 17'43'' - 18'31'': https://msit.microsoftstream.com/video/12e10840-98dc-ae71-db7b-f1ec19e01ea4?list=studio

**Comment by greazer** [comment]
Please dupe against VS Code's version of this bug (bolded icon, not blue). Make sure nb-golden label is set on that bug.

**Comment by DavidKutu** [comment]
It going blue was fixed in VS Code by Rob.
It going bold can be tracked here: https://github.com/microsoft/vscode/issues/133293
