### ISSUE TITLE
Consider adding a blessed basic environment to install with the Jupyter extension

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#7642]
As an alternative to ironing out all of the environment selection issues we could consider shipping some type of blessed basic environment with python + ipkernel + basic data science packages (numpy, pandas, matplotlib). This could be the default environment to use in general and then only advanced users would need to wade into the kernelspec / interpreter selection stuff. This might suit the usage of plenty of customers and help our initial run success rates.

**Comment by greazer** [comment]
We should discuss with Python, as they were considering doing something along these lines to help users out.

**Comment by DonJayamanne** [comment]
Closing for now as we have the option to create a new virtual environment and the plan is to drive users to use that option
