### ISSUE TITLE
Notebook debugging should offer a "Stop on first line of cell when debugging"

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7647]
The interactive window debugging experience has a "Stop on first line of cell when debugging" setting. This allows the user to start debugging a cell without having to set a breakpoint.

Notebook debugging should offer an equivalent setting OR honor the same setting.

**Comment by DonJayamanne** [comment]
VS Code offers such a setting in launch.json today, its called `stopOnEntry`.
Most languages support this today (Python, node, go), basically stops on the first line of code.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-jupyter/issues/7263
