### ISSUE TITLE
Missing renderers output shown for regular code cell

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-jupyter#7654]
Repro Steps:
1. Open a repo with a notebook in a codespace.
2. Run a regular cell (e.g. "import numpy as np")
3. View the preload error output.

![image](https://user-images.githubusercontent.com/6413608/134597231-6d0c2206-7ba4-463b-946f-7c9822ff0c77.png)

**Comment by SiddhanthUnnithan** [comment]
This is being seen with the renderers extension installed. When I switch the mimetype to the built-in renderer, the error is displayed correctly.

![image](https://user-images.githubusercontent.com/6413608/134597423-83bb6016-465d-44a5-8cf8-8516c1a233f0.png)

**Comment by rchiodo** [comment]
@DonJayamanne this should be working now, right?
