### ISSUE TITLE
parameters details of a function

### ISSUE THREAD

**Issue by Alisher4512** [microsoft/vscode-jupyter#7655]
Issue Type: <b>Feature Request</b>

why its not showing the detail of parameters of any function in jupyter notebook whenever i open in this IDE ,although on other IDE parameters detail is shown  why.I also tried help function to know the detail but in vain.plz add the functionality to this IDE about the detail of parameters of any function  of python libraires in jupyter ,i use jupyter in this ide

Extension version: 2021.8.2041215044
VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 6.3.9600
Restricted Mode: No

**Comment by claudiaregio** [comment]
@Alisher4512 I am not able to reproduce your issue. Could you provide a screenshot/screen recording of what you are doing? Does hovering over the function or within the parentheses not show anything?
