### ISSUE TITLE
SyntaxError by sending a function with triple-quoted string/docsting to Interactive Window

### ISSUE THREAD

**Issue by firegate22** [microsoft/vscode-jupyter#7658]
## Environment data

-   VS Code version: 1.61.0
-   Jupyter Extension version (available under the Extensions sidebar):  2021.9.1001269173
-   Python Extension version (available under the Extensions sidebar): 2021.9.1246542782
-   OS (Windows | Mac | Linux distro) and version: windows/mac + linux remote
-   Python and/or Anaconda version: 3.7 or 3.9
-   Type of virtual environment used pyenv virtualenv and/or conda 
-   Jupyter server running: Remote

## Expected behaviour

```
def test(input: str = "test"):
    """
    test function
    """
    print("hallo")
```

get's executed correctly

## Actual behaviour

```
def test(input: str = "test"):
    test function
    print("hallo")

test()
```

is the code send to the interactive window, resulting in an error. 

It basically removes """ without anything else in the line I guess. 
e.g. 
"""test
"""
results in
"""test

other example:
```
def test1():
    """TEST
    
    TEST"""

def test2():
    """TEST
    TEST
    TEST"""
```

results in:

```
def test1():
    """TEST
    TEST"""

def test2():
    TEST
    TEST"""
```

## Steps to reproduce:

```
def test(input: str = "test"):
    """
    test function
    """
    print("hallo")
```

in .py file

mark the code, press shift enter (send to interactive console)

this works:
```
def test(input: str = "test"):
    """test function"""
    print("hallo")

test()
```

</p>
</details>

**Comment by rchiodo** [comment]
Should be fixed in next insiders bits.

**Comment by firegate22** [comment]
Thanks, yes - it's fixed!
