### ISSUE TITLE
Remove Interrupt buttons and commands from Jupyter

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#7661]
- "Run all" on a long notebook eg Titanic.ipynb
- The interrupt button blinks on and off
- This is actually contributed by Jupyter, and it looks like the when clause changed recently @joyceerhl 

Filing this because @kieferrm mentioned it, we could leave the when clause alone (if that is causing the issue), but next month we have this button in vscode itself. See https://github.com/microsoft/vscode/issues/133776 also

**Comment by DonJayamanne** [comment]
Even if we fixed this, i don't see a point, as we're planning on moving this into core in the same iteration!
To be discussed whether we want to fix this in Jupyter or not.

**Suggestion**
* VS Code enables the icon only when cells are queued/running
* Remove interrupt from Jupyter 
	* Currently the interrupt only appears in global toolbar & not in editor toolbar (moving to core will fix this - hopefully)

**Comment by DonJayamanne** [comment]
The changes will be made in VS Code core.
Leaving this issue open so we remove the custom toolbar icons & commands.

**Comment by rchiodo** [comment]
This requires core changes so it's blocked.

**Comment by DonJayamanne** [comment]
@roblourens any update on when or even if the interrupt button will be added into core.
I coudln't find any issue that tracks that work in vscode repo. Probably there is and I couldn't find it.

**Comment by roblourens** [comment]
That's https://github.com/microsoft/vscode/issues/133776 - from what I remember, the button is there but does not appear.

**Comment by roblourens** [comment]
It looks like currently the Jupyter command is still used for the Interactive Window, and the builtin command is used for notebook editors, is there a reason for the @rebornix? Can the builtin command also be used for the IW?

**Comment by rebornix** [comment]
@roblourens when removing the interrupt button for notebooks, I found that we have a different set of interrupt commands for IW, and their impl is slightly different, thus I leave them there. We should take some efforts to remove it.

**Comment by amunger** [comment]
easier repro to verify:
1. create an Interactive window
2. ensure there is no interrupt button in the toolbar while nothing is running
3. run some interruptable code

```
import time
for i in range(20):
    time.sleep(.5)
    print(i)
```

4. ensure interrupt button appears in the toolbar and can be used to interrupt execution
