### ISSUE TITLE
Cell magic %%timeit is not behaving properly

### ISSUE THREAD

**Issue by lucaguarro** [microsoft/vscode-jupyter#7668]
The %%timeit cell magic does not seem to work in vscode whereas it works fine on a web-hosted jupyer notebook. Interestingly "%timeit"for timing single lines of code works just fine. It is only when doing the cell timing with "%%timeit"that I get trouble.

## Environment data

-   VS Code version: 1.60.2
-   Jupyter Extension version (available under the Extensions sidebar): 2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): 2021.9.1246542782
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.6.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

For %%timeit to tell me the time of execution.

## Actual behaviour

Simply prints "` not found."

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

Simply:
```
%%timeit
a = 1 + 1
```
is enough

![image](https://user-images.githubusercontent.com/22605313/134786702-206b909c-5230-4e33-a419-78385c92fc60.png)

**Comment by DavidKutu** [comment]
Thanks for the issue @lucaguarro. I'm not very familiar with `%%timeit`, but it does something for me. Is this what you would expect?
![image](https://user-images.githubusercontent.com/20347396/134968141-532eaad9-49cf-4a4c-bbff-103d1b6e9c16.png)

If so, please share the `Jupyter` logs from the `Output` panel.

**Comment by DavidKutu** [comment]
@lucaguarro, does it work if you add an empty line above `%%timeit`?

**Comment by lucaguarro** [comment]
@DavidKutu 
1. Yes the screenshot you posted is what I would expect. 
2. I tried adding an empty line and I still have the same problem.
3. Here is the output of the jupyter logs after executing just that cell:
![image](https://user-images.githubusercontent.com/22605313/134986746-fbae4835-53df-4c47-a6cb-cf5899ca35fd.png)

**Comment by DavidKutu** [comment]
Thanks for your response @lucaguarro. Sorry to bother you again, but could you send all the logs in a text file?

Also, if you can, could you try to repro this in VS Code insiders? The issue might be resolved there.

**Comment by lucaguarro** [comment]
Hi @DavidKutu sorry for the slow reply. Attached are the logs from the moment i restart the kernel to execution of just that cell.

[vscodetimeitbugjupyterlog.txt](https://github.com/microsoft/vscode-jupyter/files/7281721/vscodetimeitbugjupyterlog.txt)

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
