### ISSUE TITLE
Can't "restart" notebook debug session

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#7670]
- Start debugging a cell
- Click "restart"
- Get an error about a missing debug adapter descriptor

Need to handle debugging being started this way too, not just through the command

**Comment by DavidKutu** [comment]
![image](https://user-images.githubusercontent.com/20347396/134966895-ea65644b-2535-48b6-a447-3d6b256b2cb6.png)
Is this it? this is the only error I get

**Comment by roblourens** [comment]
That's not it - it will fail to start because it calls our debug adapter descriptor factory without doing the setup that we do when the command is run.

**Comment by roblourens** [comment]
Why wouldn't it be supported?

**Comment by DonJayamanne** [comment]
Its not supported today in Interactive window, hence I'm assuming its the same reason its not supported in run by line as well.
Either we fix it (which we haven't for over 2 years the bug has been around) or we notify users via a message.

I'm up for fixing it, thats better than some hacky warning about not supporting something (when it works in traditional Python).
