### ISSUE TITLE
Broken Argparse

### ISSUE THREAD

**Issue by Brandon-H-Campbell** [microsoft/vscode-jupyter#7672]
Issue Type: <b>Bug</b>

Working with the new Sept 10 release of VS Code I experienced an error with argparse. The code was functioning previously and it works perfectly fine when using Jupyter running on localhost or when running in AML Notebooks/Jupyter Lab. Without changing any code, at the terminal I type jupyter notebook to launch a jupyter instance using my browser the code completes without any issues. The following is the output:
usage: split [-h]
             [--partition_column_names [PARTITION_COLUMN_NAMES [PARTITION_COLUMN_NAMES ...]]]
             [--target_column_name TARGET_COLUMN_NAME]
             [--time_column_name TIME_COLUMN_NAME]
             [--train_run_id TRAIN_RUN_ID]
             [--forecast_quantiles [FORECAST_QUANTILES [FORECAST_QUANTILES ...]]]
split: error: argument --forecast_quantiles: invalid float value: '/tmp/tmp-325t2pwDkF7H7GI.json'
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/home/brandon/miniconda3/envs/azureml/lib/python3.7/argparse.py", line 2409, in _get_value
    result = type_func(arg_string)
ValueError: could not convert string to float: '/tmp/tmp-325t2pwDkF7H7GI.json'

Extension version: 2021.8.2041215044
VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.38GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/brandon/projects/aml/mm --remote=wsl+Ubuntu-20.04 --crash-reporter-id 383fcac6-162d-466d-b577-5555438f4db8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2111)|
|Memory (System)|12.42GB (9.73GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136

```

</details>

**Comment by DavidKutu** [comment]
Thanks for filing @azure-walker. Could you please share code and instructions on how to repro your issue?

**Comment by rchiodo** [comment]
This sounds like your argument you're passing is not a string:

```
ValueError: could not convert string to float: '/tmp/tmp-325t2pwDkF7H7GI.json'
```

Perhaps this is an environment variable? 

Is this the expected interpreter that you're using?
```
/home/brandon/miniconda3/envs/azureml/
```

**Comment by azure-walker** [comment]
David,

I have been building a solution for the Many Models Accelerator that can be used within Az DevOps.
I had successfully run the code in VS Code prior to the Sept 10 update. The code can be found at the repo https://github.com/coding-forge , it is the many models mlops public repo.

I was only able to run this code after Sept 10 using Jupyter notebook in a browser.
In the terminal you can type Jupyter notebook and run the code in a local browser.

Regards,

-Brandon

**Comment by DavidKutu** [comment]
Hey @azure-walker, how are you using argparse on a notebook? It looks like that's made for regular python files.

If you could share some simple code that showcases what you're doing, that'll be very helpful.

**Comment by azure-walker** [comment]
David,

I am not sure what you mean by how am I using argparse. I believe this is in a script but I will see if I can track it down. @Yuan ***@***.***> is on the Many Models team and may also be able to help with this.

Regards,

-Brandon

**Comment by yuanzhuangyuanzhuang** [comment]
We have fixed in the next sdk release which will be in public 10/11.

**Comment by greazer** [comment]
Sounds like this is addressed in the Azure ML sdk. Closing.
