### ISSUE TITLE
Able to run multi-line R cells in windows

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7676]
Refs: https://github.com/microsoft/vscode-jupyter/issues/4576

- [x] windows @rchiodo

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%234576%0A%0A&assignees=DonJayamanne)

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%237676%0A%0A&assignees=DonJayamanne)

---

Running `R` multi-line cells in Notebooks will not work in windows.
Solution:
* Remove carriage returns from CRLF in lines from cells

**Testing**
* Install `R` (https://www.r-project.org/)
* Install R `Kernel` (see here https://irkernel.github.io/installation/)
* Install Jupyter extension
* Create an ipynb notebook 
* Create a `R` cell with the following code
```r
a <- "Hello World"
print(a)
```
* Run the cell & select the `R` kernel
* Verify the cell runs & output contains the text `Hello World`

**Comment by dbaeumer** [comment]
@DonJayamanne I install R (which was successful) but installing the R Kernel failed on my machine. 

```
Error in IRkernel::installspec() : 
  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127.
In addition: Warning message:
In system2("jupyter", c("kernelspec", "--version"), FALSE, FALSE) :
  '"jupyter"' not found
> 
```
Can you please find someone who has already the correct environment or let me know what I need to do to get this working.

**Comment by DonJayamanne** [comment]
@dbaeumer sure thing, please try the following:
* Install python
* Install jupyter using the following CLI
	* `python -m pip install jupyter notebook`
* Now try to re-install IRKernel (the above steps will ensure Jupyter is in the current path)

@DavidKutu @rchiodo @joyceerhl Please could one of  you try this as well. Thanks
* Optionally you can use a docker container with R in it & connect to that remotely (this container supports R kernels `jupyter/datascience-notebook`)
	* `docker run -p 8888:8888 jupyter/datascience-notebook`
	* Look for URL & connect to that remotely.

**Comment by dbaeumer** [comment]
@DonJayamanne thanks for the steps and @rchiodo thanks for taking the test plan item.

**Comment by rchiodo** [comment]
@DonJayamanne we remove our assignment after we're done testing.

**Comment by DonJayamanne** [comment]
You need to add `verfied` label if you have tested this & the last person on the list of testers.

**Comment by DonJayamanne** [comment]
Ok, I think i'm mistaken here, i don't think we need `verified` label for test plan items.
