### ISSUE TITLE
Test: Support retina outputs in Matplotlib 

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7677]
Refs: https://github.com/microsoft/vscode-jupyter/issues/7471

- [x] macOS @JacksonKearl

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%237471%0A%0A&assignees=DonJayamanne)

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%237677%0A%0A&assignees=DonJayamanne)

---

Retina display option for Matplotlib does not work as intended

**Testing**
* Install Python
* Install Python & Jupyter extension
* Install Matplotlib 
	* Open an ipynb file
	* Create a Python cell with the following code & run it
	```
	%pip install -U matplotlib
	```
	* Or use the following documentation (https://matplotlib.org/stable/users/installing.html) 
* Create a Python cell with the following code & run it
```python
import matplotlib.pyplot as plt
plt.figure()
plt.plot([1,2], [1,2])
plt.show()
```
* Create a Python cell with the following code & run it
```python
%config InlineBackend.figure_format = "retina"
import matplotlib.pyplot as plt
plt.figure()
plt.plot([1,2], [1,2])
plt.show()
```
* The outputs of both cells should be similar in size (but the quality of the second plot should be significantly better - its a retina quality)

Here'a sample of what is expected:
![Screen Shot 2021-09-27 at 11 15 50](https://user-images.githubusercontent.com/1948812/134963769-fc47cb98-046b-4068-ab5b-d192039b97ad.png)

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/135133084-5b06983f-ea0e-4d71-8495-e44bcf4399e1.png)

Works well. Note that this doesn't need to be a test plan item, we usually reserve those for feature requests. Bugs get verified as part of their own query

**Comment by DonJayamanne** [comment]
>  we usually reserve those for feature requests. Bugs get verified as part of their own query

Thanks, will do.
