### ISSUE TITLE
Ensure white background is applied to just the plot and not the entire output area for matplot lib plots

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7678]
Refs: https://github.com/microsoft/vscode-jupyter/issues/7470

- [x] anyOS @misolori

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%237470%0A%0A&assignees=DonJayamanne)

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%237678%0A%0A&assignees=DonJayamanne)

---

Retina display option for Matplotlib does not work as intended

**Testing**
* Install Python
* Install Python & Jupyter extension
* Change theme to dark (anything other than light/white)
* Install Matplotlib 
	* Open an ipynb file
	* Create a Python cell with the following code & run it
	```
	%pip install -U matplotlib
	```
	* Or use the following documentation (https://matplotlib.org/stable/users/installing.html) 
* Create a Python cell with the following code & run it
```python
import matplotlib.pyplot as plt
plt.figure()
plt.plot([1,2], [1,2])
plt.show()
```
* The background of the entire output area should not be white (only the plot should be white)

**Heres a sample of how it used to render (bug):**
![Screen Shot 2021-09-27 at 11 24 34](https://user-images.githubusercontent.com/1948812/134964905-5f17888b-057a-43e7-9ad5-a1e491ca3367.png)

**Heres a sample of how it should render (after the fix):**
![Screen Shot 2021-09-27 at 11 27 15](https://user-images.githubusercontent.com/1948812/134964959-e86d69e7-a0a9-47fd-b69f-17d655edbfa7.png)

**Comment by misolori** [comment]
Verified that this works as described:

<img width="914" alt="CleanShot 2021-09-28 at 09 42 34@2x" src="https://user-images.githubusercontent.com/35271042/135129905-67eab65d-a179-4230-ad9e-118ad6007e28.png">

And also with multiple outputs in the same cell:

<img width="743" alt="CleanShot 2021-09-28 at 09 44 41@2x" src="https://user-images.githubusercontent.com/35271042/135130204-a2e92a18-1e3f-4bf9-b684-d26bddc6a860.png">
