### ISSUE TITLE
Local kernels should not be displayed when connecting to a remote Jupyter server

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7679]
Refs: https://github.com/microsoft/vscode-jupyter/issues/6247

- [ ] anyOS @rzhao271

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%236247%0A%0A&assignees=DonJayamanne)

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%237679%0A%0A&assignees=DonJayamanne)

---

**Testing**
* Install Python
* Install docker
* Install Python & Jupyter extension
* Open VS Code Insiders
* Select a kernel from the kernel picker
* You should see a list of python environments & possible some jupyter kernles on your machine
	* If you have multiple python installations you should see most of them in the list
	* You should see fully qualified paths for the interpreters & kernels in the list
Here's a sample screenshot
![Screen Shot 2021-09-27 at 11 44 04](https://user-images.githubusercontent.com/1948812/134966981-17dfbce7-366a-4ba8-ad15-d96af83a194d.png)
* Next start jupyter on a remote machine (in this case docker container as follows)
	`docker run -p 8888:8888 jupyter/datascience-notebook`
	* Look for text such as the following & copy the full URL

```
[I 11:30:36.916 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:30:36.920 NotebookApp] 
    
To access the notebook, open this file in a browser:
    file:///Users/donjayamanne/Library/Jupyter/runtime/nbserver-10638-open.html
Or copy and paste one of these URLs:
    http://localhost:8888/?token=dd35bcade11e8d2589941e006949ec3f050f9044666f9af8
 or http://127.0.0.1:8888/?token=dd35bcade11e8d2589941e006949ec3f050f9044666f9af8
```

* Copy the URL `http://127.0.0.1:8888/?token=<token>`
* Go into VS Code & select the command `Jupyter: Specify local or remote Jupyter server for connections`
* From the quick pick select `Existing`
	* The URL copied would have been pasted into the intput box, if not paste it & hit `[Enter]`
* When prompted, reload VS Code
* Open an ipynb file again & select a kernel
	* It could take a few seconds (as the extesnion needs to communicate with Jupyter server over the HTTP endpoints)
* Confirm the list of kernels is different and you do not see all of the same kernels you saw earlier
	Ideally you should just see 3 kernels (julia, r & python)

![Screen Shot 2021-09-27 at 11 54 41](https://user-images.githubusercontent.com/1948812/134968201-a4166ce9-b3cc-4ba6-b268-bcd9d0484017.png)

**Comment by rzhao271** [comment]
I got confused at first because I tried switching the interpreter rather than the kernel. LGTM.
