### ISSUE TITLE
Test: Kernel improvements in Jupyter Extension

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7680]
Refs: https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+label%3Akernel-issues+milestone%3A%22September+2021%22+is%3Aclosed

- [x] anyOS @paulacamargo25 
- [x] dev container @mjbvz 
- [x] wsl @alexr00

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%236813%0A%0A&assignees=rchiodo)

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%237680%0A%0A&assignees=rchiodo)

---
There's been a bunch of work to get kernels to load correctly. 

**Steps**
1. Install latest jupyter extension into VS code
2. Install python extension into VS code
3. Go to settings and pick 'daily' for ```python.insidersChannel```
4. Wait for python insiders to download
5. Close VS code
7. Start a terminal window
8. Create a new folder
8. Create a python virtual environment in the same folder : ```python -m venv mytestEnv```
9. Open the new folder in VS code
9. Go to 'New File..' and pick Jupyter Notebook
10. Add the following to a cell 
```python
import sys
print(sys.executable)
```
12. Run the cell
13. You should be prompted to pick a kernel. Pick the 'myTestEnv' you just made
![image](https://user-images.githubusercontent.com/19672699/134976484-77e8373e-aeee-4354-9aef-a822af1531b0.png)
14. You should then be prompted to install ipykernel. Install it. This might take a while.
13. Cell should then run 

Verify you get a path that prints out that matches the mytestEnv.

**Comment by alexr00** [comment]
> 4. Wait for python insiders to download

Just FYI for other testers: you need to do something to cause the python extension to activate for this to happen.
