### ISSUE TITLE
Able to restart kernel after it dies

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7681]
Refs: https://github.com/microsoft/vscode-jupyter/issues/7167

- [x] anyOS @IanMatthewHuff

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%23 7167%0A%0A&assignees=DonJayamanne)

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%237681%0A%0A&assignees=DonJayamanne)

---

**Testing**
* Install Python
* Install Python & Jupyter extension
* Open VS Code Insiders
* Create a python cell with the following code and run it
```python
print("Hello World")
```
* Confirm cell runs (output should be displayed)
* Create another cell with the following cell & run it (this will kill the kernel)
```python
import IPython  
app = IPython.Application.instance()  
app.kernel.do_shutdown(True) 
```
* Go back to the first cell & try to run that.
	* Confirm it fails with errors
* Restart the kernel using the toolbar or the command `Notebook: Restart Kernel` command
* Go back to the first cell & try to run that.
	* Confirm it runs successfully & output is displayed

**Comment by IanMatthewHuff** [comment]
Yup, scenario looks good.
