### ISSUE TITLE
Opening ipynb notebooks created using nbformat 4.5 will not lose cell id 

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7682]
Refs: https://github.com/microsoft/vscode-jupyter/issues/7167

- [x] anyOS @IanMatthewHuff

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%23 7167%0A%0A&assignees=DonJayamanne)

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%237682%0A%0A&assignees=DonJayamanne)

---

**Testing**
* Install Python
* Install latest version of Jupyter notebooks or jupyter lab (install jupyter notebook as follows)
	* `python -m pip install jupyter notebook`
* Start Jupyter notebook
	* `python -m jupyter notebook`
* Create a new ipynb file, add a few cells and save it
* Open the above ipynb file in VS Code as plain text
	* 	Confirm the cells have an `id` property see below
```jsonc
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9b9e4656", <- Confirm cell id is present
   "metadata": {},
   "outputs": [],
   "source": [
    "1234"
   ]
  }
 ],
 "metadata": {
	....
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```
* Open the above ipynb file in VS Code as a notebook
* Edit the cell & save it, confirm the id still exists & is unchanged
* Run the cell & save it, confirm the id still exists & is unchanged

**Comment by IanMatthewHuff** [comment]
Looks good. ID shows up and is unchanged after edits and runs.
