### ISSUE TITLE
Remove 200ms delay used to reveal cells

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7686]
File `interactiveWindow.ts`
```
}, 200); // Rendering output is async so the output is not guaranteed to immediately exist
```

Surely there must be a better way to do this, trying to Code spaces things will get slower & 200ms might not be enough, basically we could end up with flaky issues, why 200ms & why not 2s?

**Comment by amunger** [comment]
likely needs to be implemented in VS Code since we cannot tell when the output is written

**Comment by DonJayamanne** [comment]
> we cannot tell when the output is written

Not sure what the API does, however we can monitor output by hooking into the VS Code Notebook cell output change events.
I.e. it is possible to tell when output is written/updated to a notebook.

**Comment by rebornix** [comment]
We should revist this since Rich added the auto scrolling in core.
