### ISSUE TITLE
Unable to use Run By Line first time when connecting to remote jupyter server

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-jupyter#7690]
## Environment data

- Version: 1.61.0-insider (user setup)
- Commit: 5991e3c4b97eca5568069bf3e0910ab693ad3549
- Date: 2021-09-27T05:16:11.989Z
- Electron: 13.4.0
- Chrome: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- OS: Windows_NT x64 10.0.19043
- Jupyter ver: build from main
- Python ver: v2021.9.1246542782

## Expected behaviour

Calling `getSelectedNotebookController()` returns the controller.

## Actual behaviour

It returns undefined.

## Steps to reproduce:

1. Open a notebook with a local kernel
2. Start a kernel outside of VS Code (`python -m notebook`)
3. Run the command to connect to a remote kernel
4. Paste your server link
5. Reload VS Code as usual
6. **notebook affinity is not updated, and if we need the controller it returns undefined**
7. Reload VS Code again
8. Now it works

**Comment by DonJayamanne** [comment]
Note: `getSelectedNotebookController` will only get updated after all controller have loaded and user has executed a cell.
Would be good to know at what point you are calling this API (i.e. where in the extnesion are we using this & what point in time).

> notebook affinity is not updated, and if we need the controller it returns undefined

This will take time, as we need to wait for list of kernels to be fetched from remote server.
Would be good to know where & when you are calling this API.
E.g. if you call this API after 2-3 minutes, it should be ok

**But again, it will always return `undefined` unless you run a cell.**

**Comment by DavidKutu** [comment]
gotcha, this is happening just after reloading and opening a notebook, before running.

Maybe I'll disable debugging until a controller is found

**Comment by roblourens** [comment]
Seems ok at the moment
