### ISSUE TITLE
Prompted to install ipykernel when ipykernel is already installed

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#7692]
@rebornix ran into this

- Open a notebook
- Have an interpreter selected that doesn't have ipykernel installed (or, have not selected an interpreter explicitly but the default does not have ipykernel installed)
- Try to use RBL
- Get an error that ipykernel is not installed, even though it is installed in the notebook kernel

We apparently check the current interpreter for this, but need to be checking using the kernel: https://github.com/microsoft/vscode-jupyter/blob/8b8f450932b4a04453c9a9e959d2a1282bc1926a/src/client/debugger/jupyter/debuggingManager.ts#L435

**Comment by DonJayamanne** [comment]
@DavidKutu has a PR that will make this go away https://github.com/microsoft/vscode-jupyter/pull/7689, but that only makes this bug go away and not fix the underlying issue (not using the right interpreter associated with the kernel)

**Comment by DonJayamanne** [comment]
Closing as @roblourens can no longer replicate this issue.

**Comment by DonJayamanne** [comment]
@rebornix can replicate

**Comment by DonJayamanne** [comment]
Closing, not an issue
