### ISSUE TITLE
Review usages of this.pythonInstaller.isProductVersionCompatible and remove this public API in Python extension

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7693]
We created an API `this.pythonInstaller.isProductVersionCompatible(` in python extension
This isn't being used anymore, 
TODO:
* Remove from python extension if no one is using this.

**Comment by joyceerhl** [comment]
That function is internally used in the Python extension for checking the TensorBoard module version fyi
