### ISSUE TITLE
Double Interrupt output while in RBL

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#7696]
- Start Run By Line
- Click the stop button
- Get two outputs

The stack is different, I think that's ok, but I don't know why there are two outputs

![image](https://user-images.githubusercontent.com/323878/135002214-1bb83bab-4c7b-40bc-af54-0ff8cfccf6b1.png)

**Comment by DavidKutu** [comment]
will be fixed by #7764
