### ISSUE TITLE
Notebooks - Variables disappear if trying to run by line while notebook cells are running

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#7698]
## Environment data

-   VS Code version: 1.61.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001277548

## Steps to reproduce:

1. Open notebook
2. Run all cells 
3. Open variable explorer
4. Pick a cell and run all below (enough to do another action before it finishes)
5. Hit run by line on another cell (one that has already run, not been queued up to run)

## Actual Behavior 

Variables disappear and 'No Variables Defined' pops up in the variable explorer

## Expected Behavior 

I don't think I would even expect to be able to click run by line on a cell if I hit run all/run all above/run all below. I was actually expecting to see some error telling me I couldn't run by line until queued cells were finished. Since I did not expect to be able to click it or try to use it, I didn't think anything would happen to the variables view

**Comment by greazer** [comment]
This is a moot point once we decide to not allow run-by-line if the kernel is busy running other cells.
