### ISSUE TITLE
Kernel picker not displayed when attempting to start debugging without a selected kernel 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#7700]
Testing https://github.com/microsoft/vscode/issues/133905

1. Create a blank notebook
2. Save it (no kernel selected at this point)
3. Add a cell with some breakpoints
4. Click Debug Cell
5. 🐛 prompted to setup ipykernel. This made me think I needed to change my ipykernel version, but it's really because no kernel was selected. I would expect the kernel picker to be displayed in this scenario 

![image](https://user-images.githubusercontent.com/30305945/135037698-74f919b8-0924-4060-926c-4b90eed482fa.png)

**Comment by DonJayamanne** [comment]
Yes, i think this is a blocker for the release, related issue is https://github.com/microsoft/vscode-jupyter/issues/7691

**Comment by DonJayamanne** [comment]
This has now introduced a new bug, I get the prompt `Install, Change Kernel, Cancel`
When selecting `Change Kernel/Cancel` I still get the message `ipykernel setup required for this feature` (now I need to click cancel `twice`)

**Comment by DonJayamanne** [comment]
![install](https://user-images.githubusercontent.com/1948812/135659876-ae667424-064c-4747-ae6c-5c9407cc5a65.gif)
