### ISSUE TITLE
Unable to interrupt kernel while debugging a notebook cell

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#7701]
Testing https://github.com/microsoft/vscode/issues/133905

The test plan item suggests it's possible to interrupt the kernel while debugging a cell, but the interrupt kernel button is disabled while debugging:

![image](https://user-images.githubusercontent.com/30305945/135038173-f298c6e0-de28-4730-a8d0-73539317bcb8.png)

**Comment by roblourens** [comment]
You can click the stop button on the cell, but I'm not sure why the notebook-level one is disabled. It is contributed by the jupyter extension and the kernel is probably not busy at this moment, so this is probably related to https://github.com/microsoft/vscode-jupyter/issues/7661
