### ISSUE TITLE
Can't detect created kernel while notebook was already opened

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-jupyter#7707]
Testing https://github.com/microsoft/vscode/issues/133905

I opened up a folder with notebooks. I followed the instructions to create an environment in terminal. My newly created env isn't available to pick from in my already opened notebook. I believe this is to do with an API change from the Python extension to detect new envs?

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/5319

@tanhakabir Please could you test this again after re-loading VS Code (the issue with not listing the venv is a seprate problem all together).

**Comment by tanhakabir** [comment]
@DonJayamanne it didn't work still, I created an issue
