### ISSUE TITLE
No visual cue something is happening when debugging long running task

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-jupyter#7708]
Testing https://github.com/microsoft/vscode/issues/133905

When a function is expensive and I'm in debug mode, there's no visual cue that the notebook is still running and working. The spinner doesn't spin and nothing animates on the notebook UI. The yellow highlight disappears too.

![image](https://user-images.githubusercontent.com/12758612/135132929-302f47b0-8a28-4e2d-8e41-f791301da995.png)

**Comment by roblourens** [comment]
I guess if the cell is running but you haven't been paused for awhile, we could show the animations?

**Comment by tanhakabir** [comment]
what does this mean?
> but you haven't been paused for awhile

**Comment by DavidKutu** [comment]
It means the cell is taking long to run, and nothing is meant to happen while debugging until we hit a breakpoint and pause there.

**Comment by tanhakabir** [comment]
ah I see, yeah I think some animation while paused would be nice!
