### ISSUE TITLE
Better indication that a remote kernel is connected

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode-jupyter#7713]
Testing https://github.com/microsoft/vscode/issues/133905

When connected to a remote kernel, the server in the status bar mentions you are on a remote but the kernel doesn't mention anything:

<img width="936" alt="CleanShot 2021-09-28 at 12 00 09@2x" src="https://user-images.githubusercontent.com/35271042/135149294-e6cdccf5-6b80-4cb1-9fbc-2d909026c51d.png">

Same thing in the kernel picker, I assume that when I am "connected" to a remote kernel that there is some indicator that helps identify it:

<img width="655" alt="CleanShot 2021-09-28 at 11 58 01@2x" src="https://user-images.githubusercontent.com/35271042/135149100-0fad133b-8a1f-4709-a20c-444dee707eb7.png">

I think having either some icon or a text label in the kernel picker that says "Remote" would help in this situation

**Comment by misolori** [comment]
Also related, when reloading a couple of times and trying different files I noticed the kernel picker getting polluted (not sure if this should be a separate issue):

![CleanShot 2021-09-28 at 13 40 33@2x](https://user-images.githubusercontent.com/35271042/135162385-8a7042fd-06cf-4a9c-b469-24d32e521ce2.png)

**Comment by greazer** [comment]
Related to #7598

**Comment by zpincus** [comment]
This little UI doodad in the status bar used to change to indicate whether a kernel was connected or not... now it just always shows the "unplugged" state. Not sure if that was by intent, but the old indicator was useful.

<img width="165" alt="image" src="https://user-images.githubusercontent.com/174217/140276030-93041037-e6f8-467e-be94-6c4f427bff0f.png">

**Comment by DonJayamanne** [comment]
This will be fixed with the new kernel picker
