### ISSUE TITLE
Run by line: Continue on the line we left off after fixing an error, instead of at the top

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-jupyter#7716]
Testing https://github.com/microsoft/vscode/issues/133903

- RBL through a cell
- Error in cell, i.e. `ModuleNotFoundError: No module named 'pydotplus'`
- RBL stops and line is no longer highlighted
- Once I fix the error (i.e. install missing module), if I start RBL in cell again, have to restart from top
- Could it make sense to:
     - Keep error line highlighted? At first when I ran into errors (i.e. some imports missing early on in a cell), I thought perhaps RBL stopped when it encountered `from` statements
     - Keep user's place? So that when I install the package and RBL again, I can pick up where I left off?

I'm not sure if this makes sense or would be feasible since an error stops the cell from running, but wanted to share my initial thoughts as I ran into errors while running by line.

**Comment by DavidKutu** [comment]
Cool idea, Thanks

**Comment by roblourens** [comment]
This is essentially https://github.com/microsoft/vscode-jupyter/issues/5621, not straightforward
