### ISSUE TITLE
Run by line: Run All should stop RBL session

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-jupyter#7718]
Testing https://github.com/microsoft/vscode/issues/133903

- Start RBL in first cell, get several lines in
- Click "Run All" at top of notebook while RBL still in progress in first cell
- :bug: First cell seems to still be stuck in RBL, while all other cells in the notebook are also trying to run (have the option to stop them)
     - Once I stopped an arbitrary cell in the middle of the notebook, all the cells stopped executing, and RBL stopped in the first cell
     - The output below first cell says "Keyboard Interrupt"
     - I would've expected RBL to stop in first cell (similar to "Continue Execution") and then all other cells to run
     - I've attached the Jupyter output channel logs [JupyterRBL9-28.txt](https://github.com/microsoft/vscode-jupyter/files/7246846/JupyterRBL9-28.txt)

**Comment by DavidKutu** [comment]
What happened was expected. The cells weren't running, they were queued to run after you were done using RBL. The error saying keyboard interrupt is also normal.

Although you make a good point. It would feel more responsive if clicking run all ends the RBL session and starts running immediately.

**Comment by roblourens** [comment]
I don't know about that. Why would it be different from the case where a cell is running normally and you click "run all"?

**Comment by DavidKutu** [comment]
My answer to that is because this is not only running, its also debugging. But I don't know what would be best.

**Comment by DonJayamanne** [comment]
I think we should look into what's expected, when user is in rbl can they run cells and vice versa and what the expected behavior.

to me Rbl and running cell are the same, we're still executing code.
It's similar to debugging regular code in vscode and then clicking the debug button again will really in vscode warning the user that a session is already in progress.

**Comment by greazer** [comment]
Let's do the same thing that we're doing if the user has currently running cells and they try to do run-by-line. We show a messagebox explaining the mode they're in.

**Comment by greazer** [comment]
Moving out of October since the workaround is fairly discoverable. Just interrupt executing any of the queued cells. RBL will then be stopped.
