### ISSUE TITLE
Jupyter Commands must be hidden unless user has selected a Jupyter kernel

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7726]
We have a lot of commands that are not valid.
E.g. `Jupyter: Run by line`, `Jupyter: Debug`, `Jupyter: Convert notebook to python script`, etc
If i have a .NET or Julia kernel selected, none of these commands are useful, we have a lot of these.

**Comment by roblourens** [comment]
I just fixed this for the debug/rbl commands
