### ISSUE TITLE
Jupyter Debug Current Cell command is available when no file are opened

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7728]
This is visible when we have a python file opened as well. 
Confusing as we have `Jupyter: Debug Current Cell` which works for python files using IW

**Comment by greazer** [comment]
We only need one Debug Cell. Should work in IW or notebooks.

**Comment by rzhao271** [comment]
`jupyter.runAndDebugCell` shows up in Notebooks.
`jupyter.debugcurrentcell.palette` shows up when I'm focused on a cell in a Python file that can be made to run in an IW.
When focusing on a cell in the IW, I opened the command palette and searched for debug, but didn't get any results from Jupyter.
I'm wondering what the expected results are?
