### ISSUE TITLE
Auto-install missing dependencies when running cells

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-jupyter#7731]
Related to https://github.com/microsoft/vscode-python/issues/17230

One of the common issues I encounter with Jupyter notebooks is creating new environments and forgetting to install the correct dependencies. This leads to a lot of searching for the correct package (not all packages map to their respective names), re-installing, restarting the kernel, etc. 

<img width="763" alt="CleanShot 2021-09-28 at 13 56 30@2x" src="https://user-images.githubusercontent.com/35271042/135164647-4793eb82-61a3-492d-adb1-b823ca6202d7.png">

I'd also imagine we could map the most popular packages to their respective install commands. Even just analyzing the top ~50 packages, this would be a big delighter for a user.

**Comment by DonJayamanne** [comment]
Dup of https://github.com/microsoft/vscode-jupyter/issues/1566
