### ISSUE TITLE
Editor configuration prompt shows up entering Run by Line

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-jupyter#7732]
Testing https://github.com/microsoft/vscode/issues/134038

- Run by line on a notebook
- This notification shows up:

<img width="472" alt="image" src="https://user-images.githubusercontent.com/2230985/135171225-8d8cb857-797a-42f7-9b4f-bdcc82e722e9.png">

**Comment by DavidKutu** [comment]
That notification comes from VS Code

**Comment by connor4312** [comment]
cc @lramos15 

When I hit "configure default" there were only two entries for the Jupyter notebook, and the text editor. This was in a fresh Ubuntu install since Hyper-V got uppity again...

**Comment by lramos15** [comment]
Funny enough I saw this too recently. I don't think it has anything to do with run by line and more to do with the way we specially handle cell URIs for notebooks.

To verify:
1. Have a fresh data dir
2. Open a jupyter notebook
3. Create a problem
4. Click on the problem in the problem panel

Ensure you never see this prompt.
