### ISSUE TITLE
Run by line: Ctrl + Enter to Continue Execution requires click to focus

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-jupyter#7734]
Testing https://github.com/microsoft/vscode/issues/133903

- Wanted to test `Try using it only with the key bindings (each button shows how to do it)`
- `F10` to RBL
- Use `F10` successfully several times
- Try `Ctrl`+`Enter` to continue execution
- Requires me to click inside the cell for `Ctrl`+`Enter` to work 
     - Feels like needing to click defeats the purpose of using keybindings - am I missing another way to focus back into the cell? Is there a way to get `Ctrl`+`Enter` to automatically pick up which cell is focused based on which has a line highlighted by RBL, and to continue its execution?

**Comment by DavidKutu** [comment]
good catch

**Comment by roblourens** [comment]
Variables view is not automatically revealed by default anymore. And it will become built-in to vscode anyway
