### ISSUE TITLE
Running line by line button loses focus when starting

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-jupyter#7735]
Testing https://github.com/microsoft/vscode/issues/133903

This is because the variable explorer is opened and the focus stays there. I'd expect for the focus to stay where I had it.

https://user-images.githubusercontent.com/35271042/135173395-873ec9b7-4f30-4d96-acf5-557693008181.mp4

**Comment by DavidKutu** [comment]
good catch

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-jupyter/issues/7734
