### ISSUE TITLE
Install pip when not detected when attempting to install ipykernel

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7739]
In this bug here, https://github.com/microsoft/vscode-jupyter/issues/7737 @mjbvz  was having trouble installing ipykernel (well because /usr/bin/python didn't have pip)

Why can't we just run ```python -m ensurepip --upgrade```? (as indicated here: https://pip.pypa.io/en/stable/installation/#supported-methods)

**Comment by DonJayamanne** [comment]
Python extension didn't want this done when I was planning on submitting a PR for their extension.
We are awaiting on telemetry for this.

**Comment by DonJayamanne** [comment]
I totally agree, we should do this, even Kai ran into this, i think Sid and a number of others have run into this very often.

**Comment by greazer** [comment]
What is the telemetry going to tell us? What percentage of people failed to install one of our dependencies because they didn't have pip installed? And if that number is high, we use it to convince Python to enable this? :) Or are there other reasons that Python doesn't think this is a good idea?
