### ISSUE TITLE
Notebooks - Export to PDF never completes

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#7745]
## Environment data

-   VS Code version: 1.61.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001277548

## Expected behavior

Export to PDF to work or to give me some error that the request timed out and to try again

## Actual behavior

I see the prompt below basically forever 

![image](https://user-images.githubusercontent.com/19276747/135314297-66c93902-dcda-4693-8244-d4b4a9da4dd6.png)

**Comment by rchiodo** [comment]
Do you have the jupyter output log? nbconvert might be stuck

**Comment by rchiodo** [comment]
This might be a 3.7 problem. However export to pdf has always been flakey and hardly anybody uses it. Taking off the golden path for now.

**Comment by dleve123** [comment]
> However export to pdf has always been flakey and hardly anybody uses it.

Just want to disagree with hardly anyone uses it! I often use VScode for Jupyter notebook development and the ability to quickly convert to PDF instead of printing a browser window is very helpful.

**Comment by greazer** [comment]
I think this has been fixed.
