### ISSUE TITLE
Continue execution should use F5 keybinding

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-jupyter#7746]
Testing microsoft/vscode#133903

Continue execution uses the `Ctrl + Enter` keybinding. Why not `F5` to be aligned with what we do for regular debugging?

![Screenshot 2021-09-29 at 17 41 48](https://user-images.githubusercontent.com/1926584/135302788-20fac950-9cf2-420b-9e21-d7f53ccaa15b.png)

**Comment by roblourens** [comment]
I think it could go either way, but F5 makes sense to me.

**Comment by greazer** [comment]
Ctrl+Enter, Shift+Enter and F5 should all continue to end of cell.

**Comment by roblourens** [comment]
F5 does do continue. I think it's fine that ctrl+enter is the main default shortcut
