### ISSUE TITLE
Run by line: no way to stop execution

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-jupyter#7747]
Testing microsoft/vscode#133903

Should we have a stop button to stop execution?
Also continue execution does not respect breakpoints? Is this expected?

Bonus idea: the other actions in the toolbar do not make much sense while you are running, do they? Should we customise the toolbar a bit more while the user is running?

![Screenshot 2021-09-29 at 17 44 38](https://user-images.githubusercontent.com/1926584/135303244-5fef46b9-e9cc-422d-8f5e-3de4e772fc37.png)

**Comment by isidorn** [comment]
Ok, thanks for letting me know.
Feel free to close this then, however some feedback on the interrupt button:
* Does not really look like a button or clickable
* Due to square shape looks like a rendering glitch

Could we use some other icon here? Something more rich?

**Comment by DavidKutu** [comment]
Notebook users are used to the run/stop button.

I'll be down to reopen this with a title like `Interrupt button does not look clickable`, add the community feedback label and see if people agree.
