### ISSUE TITLE
Run by line should continue in next cell

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-jupyter#7748]
Testing microsoft/vscode#133903

Run by line currently stops when the end of the cell is reached.
I think a much better flow would be if it would just continue to the next cell. Why else would the user continue clicking "Run By Line" at the last line.

**Comment by roblourens** [comment]
I think to debug cell2, you should have to click the RBL button on cell 2. This might be nice but then the RBL button should be global, which I don't think we should do.

**Comment by isidorn** [comment]
I think the button should be able to "pass focus" to the next cell. Once you are in the next cell the first button should no longer work (should be disabled). That might work nicely.

**Comment by roblourens** [comment]
We can think about it more as we see how people use RBL, but this doesn't really match my mental model of how it would work
