### ISSUE TITLE
VS Codes built-in renderer for text/markdown doesn't support all latex formats

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7759]
See here for the issue https://github.com/microsoft/vscode-jupyter/issues/7754
Basically in that issue we have text/latex thats not supported by core VS Code.
Also reported here by Paige https://github.com/microsoft/vscode/issues/133390

Users also have the same latex in plain mark down cells or python cells using `%%markdown` magics

E.g. as follows
```python 
%%markdown
\begin{equation}
y^{\prime}+2 y=2-\mathbf{e}^{-4 t} \quad y(0)=1
\end{equation}
```

This will not get rendered by the built-in renderer.

Solution: Fix this in core or submit a renderer for text/markdown in the Jupyter renderers extension.

**Comment by greazer** [comment]
Submit a PR to fix this in the VS Code repo.

**Comment by DonJayamanne** [comment]
This now works as expected
