### ISSUE TITLE
Focus issue in Interactive window

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#7760]
```
Version: 1.60.2 (user setup)
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:00:31.514Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
Extension: v2021.8.2041215044
```

I'm having an issue with shortcuts, and they sometimes stop working in the bottom code entering field in the Interactive Window. I believe it happened before, but I couldn't find the issue that logged it. It might have something to do with "focus".

I can't find a consistent way to reproduce it now, and it has been here for a while. But when it happens, enter+shift will no longer execute the code I entered, and I must click somewhere in the Editor and then click the code entering field to get it back to work again.

**Comment by DonJayamanne** [comment]
I believe we've address this in the the insider version. Please could you install VS Code insiders and test this out.

**Comment by rchiodo** [comment]
@StevenLi-DS please reopen if insiders doesn't work for you. Thanks.

**Comment by StevenLi-DS** [comment]
I'm not able to use it in insiders since the extension won't load for some reason.
![image](https://user-images.githubusercontent.com/33796896/135930657-948636de-6e0c-499a-9f1d-07e6f42ebcde.png)

**Comment by StevenLi-DS** [comment]
@DonJayamanne @rchiodo Sorry for the late reply. After trying it out for a very short period of time, I'm not having this issue in Insiders now.
