### ISSUE TITLE
Unclear why "Ipykernel setup required for this feature" is showing up for new setups and trying to run-by-line

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-jupyter#7761]
Testing https://github.com/microsoft/vscode/issues/133903

Both Brigit and I hit this when testing via the test plan item steps.

For Brigit, things just started working, perhaps after updating the ipykernal version.

For me, things started working after I did a Run All and accepted the prompt to install ipykernal.

Might be an issue with the test plan steps but it is also confusing that the "Ipykernel setup required for this feature" message has a "Setup" button that takes you to documentation, while the "Run All" message allows you to install the missing components.

**Comment by roblourens** [comment]
This would only affect older environments, not going to address it
