### ISSUE TITLE
Make error output collapsed by default (Was: Ugly output when clicking `Stop Cell Execution`)

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-jupyter#7764]
Testing https://github.com/microsoft/vscode/issues/133905

1. Put a breakpoint
2. Start debugging
3. Click the stop button `Stop Cell Execution`

The cell output will contain a pretty large scary KeyboardInterrupt message.

![image](https://user-images.githubusercontent.com/22350/135430534-730bdb01-b54d-45e1-b1fa-40d3861cf2fe.png)

**Comment by greazer** [comment]
Let's consider making the callstack collapsed by default. Some users may find the stack interesting, some may not. This would be true for ANY error that has a callstack.

**Comment by roblourens** [comment]
Meaning just collapse the output container? @DavidKutu I don't see how that fixes #7696

**Comment by DavidKutu** [comment]
It will help, but I guess its different enough

**Comment by roblourens** [comment]
@rebornix can we do anything here with the custom error renderer? Or would we want to detect this messy error and rewrite it in the jupyter extension?

**Comment by roblourens** [comment]
Like I think that just using a shorter line limit for this particular error so the library frames get truncated off the end, but not sure where that logic would happen.

**Comment by amunger** [comment]
closing in favor of https://github.com/microsoft/vscode/issues/200253
