### ISSUE TITLE
NbFormat cell id is missing when adding new cells in VS cdoe

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7765]
Technically in order to support 4.4 and above the 'id' is required:

https://github.com/jupyter/enhancement-proposals/blob/master/62-cell-id/cell-id.md#required-field

_Originally posted by @rchiodo in https://github.com/microsoft/vscode-jupyter/issues/5933#issuecomment-931483116_

**Comment by DonJayamanne** [comment]
I've already got a PR reaady to go into VS Code for this, want to get that in debt week

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/7749
