### ISSUE TITLE
State what version of VSCode is supported in the change log to ease offline VSIX install

### ISSUE THREAD

**Issue by dennisl68-castra** [microsoft/vscode-jupyter#7771]
When I try to install the ms-toolsai.jupyter VSIX on VS Code on an offline system I must only use a stable version of VSIX and the correct version of VS Code.
However, the setup only tells me that my version of VS Code isn't supported if there is a mismatch, not what version that is actually needed.

So trying to install the currently latest available stable version, ms-toolsai.jupyter-2021.9.1001277548.vsix on the latest currently stable version of VS Code, 1.60.2 will fail.

![image](https://user-images.githubusercontent.com/49750419/135589528-3c8d129c-436b-4879-89f2-21c3106090f6.png)

Please, provide information in the [ms-toolsai.jupyter change log](https://marketplace.visualstudio.com/items/ms-toolsai.jupyter/changelog) about what version of VS Code that the stable VSIX release is locked-stepped with.

**Comment by LuisPeregrina** [comment]
I can't locate the bug but it's been fixed, try VSCode insiders (has daily update). I remember seeing that it wasnt a jupyter bug but a VSCode bug.

**Comment by LuisPeregrina** [comment]
See [Unable to install stable version of extension in WSL](https://github.com/microsoft/vscode/issues/133777)

**Comment by dennisl68-castra** [comment]
Guess I have to wait for the next stable release of VS Code, then. 
(Can't use unstable releases on production systems.)

But the option to use an older stable version of ms-toolsai.jupyter with an older stable version of Vs Code is not a simple work around since there is no public information about the lock-stepped of VS Code available for ms-toolsai.jupyter stable releases.

**Comment by claudiaregio** [comment]
Hi @dennisl68-castra, I think we could do something like this in the meantime, will bring it up during our next sync meeting to chat about other solutions. 

There is a related feature request in the marketplace (https://github.com/microsoft/vsmarketplace/issues/43) if you'd like to take a look at that/leave your thoughts there too

**Comment by rchiodo** [comment]
Should be able to add the entry in the package.json to the changelog.
