### ISSUE TITLE
Jupyter extension marks a file as dirty every time it's opened

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7776]
Open the included file. 

[t2.ipynb.txt](https://github.com/microsoft/vscode-jupyter/files/7268595/t2.ipynb.txt)
If jupyter extension is enabled it will be marked dirty on open
If jupyter extension is disabled it won't be marked dirty on open

**Comment by rchiodo** [comment]
Kinda of a regression? Well since two months ago I'd say.

**Comment by DonJayamanne** [comment]
I cannot replicate this in the latest version of VSCode and latest jupyter extension.
Please ensure you have updated to the latest.

**Comment by jackthepanisher** [comment]
It will not reproduce unless a kernel is selected. So just loading the attached file above will not trigger the issue unless the same Python/kernel environment is available. To reproduce, select a kernel, save file and re-open it. BTW, the procedure given in [Opening an existing notebook marks it dirty unnecessarily](https://github.com/microsoft/vscode/issues/132306) should be still valid.

**Comment by rchiodo** [comment]
Dupe of #6637
