### ISSUE TITLE
Once raw notebook kernel is in broken state there's no way to recover unless you restart VS COde

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#778]
**VSC Native Notebooks + Raw Kernels**
* Somehow ended up in a situation where kernel was broken ```Error: Direct kernel connection broken```
* Restarting kernel doesn't fix this (it should as we're starting the kernel process again)

However re-loading VSC Fixes this.

**Comment by MJimitater** [comment]
Same error here, even a VSCode restart doesn't help

**Comment by davircarvalho** [comment]
Same issue, restaring VSC doesn't fix it

**Comment by nthomsencph** [comment]
This occurred for me after calling "os._exit(0)" in a function. Stay away from that one. Seemed to exit the kernel entirely. Restarting VSC solved it.
