### ISSUE TITLE
its better to fold the output

### ISSUE THREAD

**Issue by konpoe** [microsoft/vscode-jupyter#7782]
as title,sometimes,outputs is verbose i want to fold it but not clear

**Comment by claudiaregio** [comment]
Hi @konpoe, you can collapse output by double-clicking in the area to the left of a cell (in red below). 

![image](https://user-images.githubusercontent.com/19276747/135677477-61c6be4a-9c6f-42ee-b42e-c9d251ed67f3.png)

You can also collapse output by clicking the '...' in the cell menu and then selecting collapse cell output (in red below).

![image](https://user-images.githubusercontent.com/19276747/135679085-45a3fa68-1446-4c0b-afd9-3b696273c378.png)

**Comment by konpoe** [comment]
ty
