### ISSUE TITLE
Jupyter Startup Commands problem message

### ISSUE THREAD

**Issue by ngquocanh1197** [microsoft/vscode-jupyter#7785]
## Environment data

-   VS Code version: 1.60.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): v2021.9.1246542782
-   OS (Windows | Mac | Linux distro) and version: Windows 21H1 (Build 19043.1237)
-   Python and/or Anaconda version: Python 3.8.11
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

The `settings.json` file shows no warning when I use string startup commands:

`
"jupyer.runStartupCommands": "%load_ext_autoreload\n%autoreload 2",
`

## Actual behaviour

![image](https://user-images.githubusercontent.com/21218188/135685206-278d9471-3f3d-41eb-9eec-ed1adad876b4.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Add `"jupyer.runStartupCommands": "%load_ext_autoreload\n%autoreload 2",` to `settings.json` file as run startup commands using string

**Comment by rchiodo** [comment]
Your setting is using the older way to specify 'runStartupCommands'. We switched it to an array of commands but it still supports the old way. You can ignore the warning or fix your startup commands to look like so:

```json
    "jupyter.runStartupCommands": [
    "%load_ext_autoreload",
    "%autoreload 2"
   ]
```
