### ISSUE TITLE
Language Server Quick Fix Enhancement (if no kernel selected)

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#7788]
Filing this issue here for now...

I created a new notebook and started working in the cells. I immediately got diagnostics for the packages I wanted to grab since I had not yet selected a kernel. Pylance shows there are no quick fixes available, but it would be nice if the quick fixes could detect a kernel had not yet been selected for the notebook and asked me to select one, especially if the diagnostics are coming from import lines. 

![image](https://user-images.githubusercontent.com/19276747/135772865-fa3e908e-ade8-4667-a933-531b933c3d1b.png)

**Comment by rchiodo** [comment]
#6333 should alleviate this somewhat

**Comment by DonJayamanne** [comment]
Closing this issue so it gets validated in the august

**Comment by DonJayamanne** [comment]
Marking as verified as we always end up selecting a kernel no matter what, and user can change this if we get erroneous error messages
