### ISSUE TITLE
Notebook toggles in and out of a dirty state while running

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-jupyter#7790]
**Note: I am unsure of whether or not this behavior is intended to show that the Notebook is running, or if this is an actual issue.**

## Environment data

-   VS Code version: 1.61.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001294413
-   Python Extension version (available under the Extensions sidebar): v2021.9.1246542782
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: conda 4.10.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

Notebook should not be marked dirty in the tab indicator if no changes have been made.

## Actual behaviour

Notebook toggles in and out of a dirty state as it is running.

## Steps to reproduce:

1. Run a notebook with multiple code cells
2. Notice that the x on the tab turns to the dirty indicator (dot) and back to x as the Notebook runs cells

https://user-images.githubusercontent.com/686963/135780495-b4feff65-742d-485f-b947-0468ba64493a.mp4

**Comment by DavidKutu** [comment]
This might be happening because the output is changing.

**Comment by rchiodo** [comment]
If you have auto save turned on, this is by design. As you execute outputs are changing (making the file dirty) and then an auto save happens marking the file as not dirty.
