### ISSUE TITLE
Generate a telemetry CSV for querying telemetry generation data

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7798]
This PR: https://github.com/microsoft/vscode-jupyter/pull/7797 adds a TELEMETRY.md file to the root.

This is nice for documentation purposes, but it would be nice to be able to query the data used to generate this MD file.

This issue proposes to generate a CSV file (that can be pulled into a notebook for example) that contains things such as:

- Event name
- Event description
- Property names
- Potential property values (for string enums)
- Event category - still TBD on how to figure this out.

**Comment by DonJayamanne** [comment]
Closing for now, as this will be reviweed when automating GDPR tooling
