### ISSUE TITLE
Notebooks - Language not updating with kernel change 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#7807]
## Environment data

-   VS Code version: 1.61.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001294413

## Steps to reproduce

1. Have Python and Julia extension installed
2. Create new Jupyter notebook -> Choose julia extension provided kernel 
3. Change kernel to a Python kernel 

## Actual Behavior 

Language picker remains Julia
*Note, this only occurs the first time after creating a new notebook

## Expected Behavior 

Language picker updated to Python

**Comment by DonJayamanne** [comment]
Closing this as there haven't been any other complaints about this, nor any upvotes,
