### ISSUE TITLE
Confusing block of text printed at top of new interactive window

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#7815]
Issue Type: <b>Bug</b>

**Repro**
1. Start a new interactive window

**Bug**
A block of unformated text is printed at the top:

<img width="810" alt="Screen Shot 2021-10-05 at 10 09 16 AM" src="https://user-images.githubusercontent.com/12821956/136070755-79610b88-de3c-401b-b029-578153589302.png">

I don't know what I'm supposed to do with this text and the lack of formatting makes it difficult to read. Could be a good point to provide some hints to the user, similar to VS Code new untitled file experience

Extension version: 2021.9.1001294413
VS Code version: Code - Insiders 1.61.0-insider (Universal) (71ca6e8e74591ae5c577d52a2aa1bd0c3df5ac32, 2021-10-05T01:23:40.704Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|32.00GB (6.48GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsqsis300:30374797
vsaa593cf:30376535

```

</details>

**Comment by IanMatthewHuff** [comment]
Yeah, not only is the formatting off (though that feels like a general markdown block issue that we need to resolve, not just specific to this area) but I don't think this block is really actionable or informative to the user. 99% of the useful info in this block is covered just by seeing the selected Controller.
![image](https://user-images.githubusercontent.com/812783/136144648-e5134e7d-2062-41bd-844a-537cfb9713fc.png)
I don't think that we care about a user typing 'credits' or the Python date. There might be some value in seeing in the history where you changed the controller or restarted it, but it wouldn't need this entire block to convey that, and I'm dubious of that being a big use case just in general.

With regards to the formatting was it just the text formatting of the markdown block the issue? I see that, but even if the text was formatted it feels a bit like the blocks of text are just drifting in a bit of empty space here (example with info text block, then code + output, then markdown block).

![image](https://user-images.githubusercontent.com/812783/136145460-607b3816-0f3b-46c9-959e-27955a6716d5.png)
