### ISSUE TITLE
IntelliSense for data files does not work on subfolders

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-jupyter#7816]
When trying to read data files via `df = pd.read_csv()`, it appears that intellisense does not show subfolders and I have to explicitly trigger intellisense again after there are no matches. It would be nice if I didn't have to explicitly trigger this and it just worked automatically.

https://user-images.githubusercontent.com/35271042/136071529-1149082d-fd54-4e4b-b9ce-58ea65373b09.mp4

**Comment by rchiodo** [comment]
This PR will partially resolve this:
https://github.com/microsoft/vscode-jupyter/pull/8247 
if you add ```'``` or ```"``` to your trigger list. 

However after you hit tab on say ```"./data/```, you have to use ctrl+space again (or delete the last /) to get the completions to come up again. Not sure how to get VS code to do autocompletions again when just typing? Maybe delete the final ```/``` on the end when inserting the text so the user has to hit ```/``` again? (```/``` becomes a trigger character automatically when strings cause completions)

**Comment by rchiodo** [comment]
![stringCompletion](https://user-images.githubusercontent.com/19672699/141383766-4ae1c39a-189a-4a3d-9031-26630d52de35.gif)

@rebornix @misolori do you have any suggestions on how to get the secondary directories to work?

**Comment by misolori** [comment]
We use intellisense for paths in HTML where the suggest widget doesn't go away, which look like files as opposed to intellisense suggestions (notice the file icons vs symbol icons in your gif)

https://user-images.githubusercontent.com/35271042/141827268-856beebe-a7a3-496d-877d-e966ea3c4af4.mp4

y

**Comment by rchiodo** [comment]
Thanks. I can look at how the html extension does it. Might be the 'tab' key is a trigger character too.
