### ISSUE TITLE
Selected Kernel and kernel connection is lost when saving an untitled Jupyter Notebook

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#7820]
1. Start with the "New Jupyter Notebook" command
2. Select a kernel and work with the file for a bit
3. Save the file with a filename

Expected: After saving the file I have the same kernel selected and can continue working
Actual: On saving I lose my associated kernel and have to select it again and connect to it again to continue working

![image](https://user-images.githubusercontent.com/812783/136083540-895f19fc-764d-49c5-bbd2-75905726a9b6.png)
![image](https://user-images.githubusercontent.com/812783/136083559-5bb00724-205e-4eb5-a827-0fe3bc59727f.png)

**Comment by greazer** [comment]
As part of the investigation for this bug, see if you can find a repro where a kernel has to be selected for a notebook you previously had open in VS Code and had already selected a kernel. Might have something to do with a new version of VS Code generating a new list of kernels.

**Comment by DonJayamanne** [comment]
Unable to repro, closing this issue

**Comment by rchiodo** [comment]
This is not working for me.

Create enough notebooks that it doesn't have the selected kernel in them.
Select a kernel on the untitled notebook
Save as
Kernel is 'Select Kernel' on reopen

**Comment by rchiodo** [comment]
![image](https://user-images.githubusercontent.com/19672699/144328825-7f228aa5-9ab1-4a35-8316-9fd8a5c65697.png)

**Comment by rchiodo** [comment]
Isn't this a core issue? As in we should transfer?

**Comment by DonJayamanne** [comment]
@rchiodo 
 
We discussed this and all that was required was as mentioned by Jim here https://github.com/microsoft/vscode-jupyter/issues/7820#issuecomment-940435734

& I verified that, hence closed this as a verification, i.e. VS Code remembers the kernels for existing notebooks. 
We weren't concerned about untitled notebooks).
We were only concerned about existing notebooks saved to disc.
