### ISSUE TITLE
Garbled pylance info in Jupyter notebook

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#7821]
The repro here was just creating the following basic notebook. After adding in the second cell everything was garbled. Pylance seems to have some odd code that's not what is actually in the cells. Trying to suss out the total repro here. Basically I added and executed the first cell. Then added and executed the second cell. Then the problems showed up in the problems pane. Python interpreter is set to the same interpreter as my running kernel.

![image](https://user-images.githubusercontent.com/812783/136084647-21ffe245-3dfd-4c4e-acf7-466c1f467d49.png)

![image](https://user-images.githubusercontent.com/812783/136084382-b4a6596e-6f2f-4493-9fa8-8900d5f20a31.png)

Closing and reopening the file (this was a new file that had been saved from untitled) seems to have cleared the issues.

**Comment by rchiodo** [comment]
Looks like the change events for the cells didn't work correctly.
