### ISSUE TITLE
Improve setup instructions for setting up ipykernel for debugging Jupyter Notebooks

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-jupyter#7822]
I was trying out the new debugging feature for notebooks (which is so awesome btw 🤩), and I got that modal notification saying I needed to set up ipykernel to debug cells.

1. When I clicked "setup" I was expecting something to happen automatically. I did not notice it opened the instructions on the browser. If it's a temporary solution feel free to completely disregard this comment, otherwise it might be worth adding a "Learn more" or something like that to the button instead of "setup" to set up expectations 
2. When looking at the page on the [wiki](https://github.com/microsoft/vscode-jupyter/wiki/Setting-Up-Run-by-Line-and-Debugging-for-Notebooks), I was thinking it might be worth be more descriptive on the troubleshooting section. For example ,to how verify the version of ipykernel that is installed, and how to verify the extensions and VS Code versions too. For users who are not as familiar with the ecosystem it might not be obvious how to verify it all. It might also be worth adding the command to upgrade ipykernel in case it's installed.

**Comment by greazer** [comment]
Made some changes based on what you suggested, @luabud. https://github.com/microsoft/vscode-jupyter/wiki/Setting-Up-Run-by-Line-and-Debugging-for-Notebooks

**Comment by luabud** [comment]
It looks great, thanks a lot! 🤩
