### ISSUE TITLE
Variable explorer has two invalid 'loading' rows

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7825]
![image](https://user-images.githubusercontent.com/19672699/136101478-50ee43d9-5cce-4111-8eb4-180c9d274708.png)

This is the code I'm running

Download from here:
https://github.com/pluralsight-projects/python-collections-budget

Add this code to the FrequentExpenses.py

```python
#%%
import collections
import Expense
import os

dir = os.path.dirname(__file__)
expenses = Expense.Expenses()
expenses.read_expenses(f"{dir}/../data/spending_data.csv")

# %%
spending_categories = []

for expense in expenses.list:
    spending_categories.append(expense.category)

# %%
spending_counter = collections.Counter(spending_categories)

# %%
```

**Comment by amunger** [comment]
not seeing this from the repro steps
