### ISSUE TITLE
Upgrade to webpack 5

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7827]
We have lots of outdated dependencies and hacks/work arounds

**Comment by IanMatthewHuff** [comment]
@DonJayamanne I actually had this mostly done at one point (same time I converted the renderers) the one thing that was really difficult to work around was the old version of the Monaco editor that we were using in the webviews. To get Webpack 5 we had to use a newer version of Monaco-editor-webpack-plugin but that plugin required that we move to a newer version of Monaco which caused all sort of issues. Now that webviews are gone this could be pretty easy, I still have a OneNote with the other changes that I had to make.
