### ISSUE TITLE
Start using esbuild 

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7828]
No idea where the original issue went, i remember discussing this with the team as well.
Suggestion:
* Use esbuild for the webview stuff (will be faster)

**Comment by rchiodo** [comment]
Going to try out esbuild. Start with ipywidgets.

**Comment by rchiodo** [comment]
Gave up on this idea. There's a lot of stuff that esbuild doesn't support.

**Comment by rchiodo** [comment]
Biggest problem - dynamic requires. Jupyterlab does this in a bunch of spots.

**Comment by rchiodo** [comment]
https://github.com/evanw/esbuild/issues/1921

**Comment by DonJayamanne** [comment]
All we now need is esbuild for the main bundle,
All of the following are done
* IPyWidgets,
* Renderers
* Variable viewer
* Plot viewer
* DF viewer

**Comment by DonJayamanne** [comment]
Closing this for now, as we have implemented this in all places except for the main bundles.
