### ISSUE TITLE
Cell delimiters on indented code require a space

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7829]
Have code like this:

```python
#%%
def main():
  #%%
  print('do stuff')
```

There should be two cells there. There's only one

![image](https://user-images.githubusercontent.com/19672699/136112704-4b671416-8db5-49d7-90ef-dc5dfd58aaa2.png)

If I add a space it works:
```python
# %%
def main():
  # %%
  print('do stuff')
```

![image](https://user-images.githubusercontent.com/19672699/136112753-1ec1d6a9-841d-4285-bfce-ea0b0dd453fb.png)

**Comment by Andrewnt219** [comment]
Hi @rchiodo, I want to help with this issue. Can you tell me which file(s) should I start looking at?
