### ISSUE TITLE
Unnecessary requests to get Variables

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7831]
* When opening variable viewer we fetch variables twice
* When using RBL and hitting continue (run to completion), we fetch variables 4 times

Feels like a problem in the code flow, i would have expected:
* One fetch when displaying variable viewer
* Zero fetches when running to completion

this feels like things are not really working as we expect them to (i.e. somethign is wrong & we don't know)

**Comment by rchiodo** [comment]
We had some thoughts about redesigning the way variables are requested. The variable view class should be responsible for deciding when to refresh. It has the necessary information to know when it doesn't need to.

**Comment by DonJayamanne** [comment]
I don't see this anymore, closing this issue
