### ISSUE TITLE
Plot buttons stand out in dark themes

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#7833]
Issue Type: <b>Bug</b>

**repro**
1. Using the default Dark+ theme
1. In the interactive window
1. Create a chart with:

```py
import matplotlib.pyplot as plt
import numpy as np

# Data for plotting
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, ax = plt.subplots()
ax.plot(t, s)

ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()

fig.savefig("test.png")
plt.show()
```

3. Hover over the chart

**Bug**
The controls for viewing the interactive window are white:

![Screen Shot 2021-10-05 at 5 24 56 PM](https://user-images.githubusercontent.com/12821956/136121852-c2dc7e87-16ef-46ca-9ab9-8a551a78dc1b.png)

These stand out compared to the other controls in the interactive window (see the set of controls above for example)

I think these controls  should try to align with the theming, styling, and icons used by VS Code (or we should figure out a way for these controls to be contributed so that VS Code can render them instead of having them inside the webview)

Extension version: 2021.9.1001294413
VS Code version: Code - Insiders 1.61.0-insider (Universal) (71ca6e8e74591ae5c577d52a2aa1bd0c3df5ac32, 2021-10-05T01:23:40.704Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30377800
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsqsis300:30374797
vsaa593cf:30376535

```

</details>

**Comment by rchiodo** [comment]
Thanks for the bug. We should be able to theme them using the VS code colors

CSS for the plot button is here;
https://github.com/microsoft/vscode-notebook-renderers/blob/main/src/client/index.css

They used to be on top of a white background all the time, so the colors were hard coded. We had talked about moving the plot buttons on top of the graph itself (so then the colors would likely stay this way) but if they stay on the right, we should theme them.

**Comment by DonJayamanne** [comment]
Closing as not planned for now.
