### ISSUE TITLE
Restarting a kernel breaks error linking in interactive window

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7836]
Run code like so for the interactive window
```python
# %%
raise Exception("Error thrown")
```
Notice stack links working
Restart kernel
Run code again

Stack links are not there.

**Comment by IanMatthewHuff** [comment]
![image](https://user-images.githubusercontent.com/812783/143297926-a7f47ef6-61de-4c0d-96bf-24335445d1f3.png)
I'm not reproing this. After a restart I get a valid link back to the error line.
