### ISSUE TITLE
Notebooks - Kernels Not Enumerated

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#7844]
Themes: 

- Venv not showing up in kernel quick pick, users attempting to input path in input box to work around it. Likely doing this because of how the "Select Python Interpreter" command works. 
- Users potentially not realizing that finding new kernels requires a reload

![image](https://user-images.githubusercontent.com/19276747/136303787-749c7a94-4b6f-4e87-be04-232df784c5e2.png)

![image](https://user-images.githubusercontent.com/19276747/136303801-04349db3-8740-47e2-b15d-bca28fe824aa.png)

![image](https://user-images.githubusercontent.com/19276747/136303864-ded8ad41-a007-4252-8c1b-9856f2f80b5e.png)

**Comment by greazer** [comment]
Accounted for via #7901 and #7583
