### ISSUE TITLE
Notebooks - General Kernel Start Failure

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#7845]
![image](https://user-images.githubusercontent.com/19276747/136304994-e879f2bd-cd6c-4276-afa8-2a881071df52.png)

![image](https://user-images.githubusercontent.com/19276747/136305029-1243285a-6d63-4ec1-b257-dec5dd43e8d0.png)

**Comment by DonJayamanne** [comment]
Closing this issue as this doesn't provide any information apart from the fact that we know there are some issues.
We've since addressed a large number of issues and feel this doesn't add any value.
