### ISSUE TITLE
Better handling of kernel crashes (dead kernels)

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#7846]
![image](https://user-images.githubusercontent.com/19276747/136305639-e4bae032-ac58-48ee-a03b-393c5bf04e95.png)

**Comment by DonJayamanne** [comment]
I think we've fixed these issues in interactive window

**Comment by DonJayamanne** [comment]
# Current state
* Today we just bomb out and log errors in cell output (session cannot be created)
* Error message is very confusing to the user (no indication that kernel is dead)
	* Users are used to seeing errors from kernels in output (not extension), hence they might be under the impression these are errors from kernel & attempt to re-execute cells
* User needs to manually restart the kernel

# Proposed Solution
* Notify user when kernel dies (like jupyter)
* Allow user to restart kernel (like jupyter)
* Include error message from kernel (so users know what went wrong)
	* E.g. if kernel fails due to some package, or the like, then they know what caused it
	* Else all they know is kernel died and could end up just blaming vscode extension
	* I.e. we need to provide the user with tools necessary to resolve the issue themselves

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/microsoft/vscode-jupyter/issues/7901
