### ISSUE TITLE
Notebooks - Venv Integration 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#7847]
![image](https://user-images.githubusercontent.com/19276747/136305916-d545e14a-876d-46f5-a776-c539d8510908.png)

![image](https://user-images.githubusercontent.com/19276747/136305946-af7fb44f-6ef2-4745-9b3c-3ca6100a8642.png)

**Comment by greazer** [comment]
Yeah, this one's set of comments seems to be covered by other ones we have. Closing.
