### ISSUE TITLE
Slow Kernel startup/restart

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#7849]
![image](https://user-images.githubusercontent.com/19276747/136306361-ed4ac6cf-3236-4bda-aa18-d6e0c2cb2074.png)

**Comment by greazer** [comment]
This is one of those issues that can be a killer for retention. It falls in line with a theme of improving our kernel startup story in October.

**Comment by DonJayamanne** [comment]
See here https://github.com/microsoft/vscode-jupyter/issues/6702 & https://github.com/microsoft/vscode-jupyter/issues/7855
I've already started looking into this and found plenty of places that can be improved.

**Comment by rchiodo** [comment]
Not really verifiable. Going to have to wait for user feedback.

**Comment by de-loots1994** [comment]
Still an issue, the largest issue that the behaviour is unpredictable. In our dev team for some people it takes seconds others it doesn't start up at all and keeps saying:
![image](https://user-images.githubusercontent.com/115618999/204757906-e16ef0b5-b46b-489e-b6a1-4e94ae99a69d.png)

**Comment by DonJayamanne** [comment]
> Still an issue, the largest issue that the behaviour is unpredictable. In our dev team for some people it takes seconds others it doesn't start up at all and keeps saying:

I'm sorry about this, please could you file an issue with the details requested in the issue template (i.e. provide the logs)

**Comment by de-loots1994** [comment]
@DonJayamanne our issue seems to be resolved it appears that it has to do with the ipykernel not being active, and with pip install it goes wrong but when getting the pop up from vs code e.g:
![image](https://user-images.githubusercontent.com/115618999/204808733-cbf55a84-204f-4963-8ed1-83f611e8e388.png)

It works...
