### ISSUE TITLE
Support search options in dataviewer filters

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7857]
After discussing at standup, we probably need something that makes data viewer filtering work like other search inside of VS code. So an explicit button for
- Case match
- Whole world
- Regex or not

_Originally posted by @rchiodo in https://github.com/microsoft/vscode-jupyter/issues/7628#issuecomment-938017146_

**Comment by rchiodo** [comment]
Potential idea:
- As a dropdown menu on the filter icon?
- As buttons in the left most column header (under the filter icon). The 'clear filters' button might support them next to it

**Comment by misolori** [comment]
In the problems view we use the filter icon to show a dropdown w/ filter options:

<img width="240" alt="CleanShot 2021-10-07 at 15 51 33@2x" src="https://user-images.githubusercontent.com/35271042/136472938-88f91b2c-8dec-47b6-bcce-386caa39263d.png">

that seems like the next best place given the density of each input?

**Comment by rchiodo** [comment]
Should be able to use this for it:
https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/dropdown/README.md

**Comment by DonJayamanne** [comment]
Closing this feature requiest has there haven't been any upvotes on this for over a year
