### ISSUE TITLE
Interactive Window - Cell delimiter lines different widths

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#7871]
## Environment data

-   VS Code version: 1.62.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001312534

Just a little strange the lines aren't the same width

![image](https://user-images.githubusercontent.com/19276747/136631026-aabce0b8-475c-4ae9-a82e-f1bb796e22a9.png)

**Comment by greazer** [comment]
This is so you can tell if you're looking at the top of a cell or the bottom.
