### ISSUE TITLE
Make and/or plan significant Intellisense Improvements for Python and general notebook LS infrastructure

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7877]
Use [this query](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22November+2021%22+label%3Anotebook-intellisense) to see the issues we plan on investigating or fixing during the November iteration.

The Python and Jupyter teams will meet and come up with a robust, long-term approach for improving the way that notebooks and Pylance communicate (not a band aid fix but one we are all happy with and that we can continue to build on going forward). It is expected that this Jupyter/Pylance collaboration will drive the model for other language services.

All Pylance (or other language services) functionality should operate in the same way in .py and .ipynb files. As right now the experience is broken in several ways. Stretch goal here would be to start executing on this plan; if time does not permit, this will be the primary focus for upcoming sprints/iterations.

**Comment by jaymegordo** [comment]
Would like to suggest adding #7098 (have pylance recognize variables imported with a "startup" script) to this conversation pls and thx!

And thanks everyone for all the work, vscode + jupyter is an amazing product, I use it all day every day, can't thank you all enough ❤️!
