### ISSUE TITLE
Kernel interrupt does not work for raw kernels

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#788]
This no longer works in standard notebooks.
This used to work, now on Mac it always times out with an option to restart the kernel.

**Comment by marius311** [comment]
Not sure if I should file a new issue or not, but I'm unable to interrupt a Julia 1.5.0 kernel with 2020.11.358541065 and 1.52.0-insider. To reproduce, just run a cell `sleep(100)` and click the "stop" button or run "Jupyter: interrupt Jupyter kernel" and nothing happens.
