### ISSUE TITLE
Jupyter notebook autocomplete suggestion "%%!"

### ISSUE THREAD

**Issue by jamesoflol** [microsoft/vscode-jupyter#7880]
Issue Type: <b>Bug</b>

Starting docstring (''') or a function definition causes autocomplete to suggest "%%!". It means I need to ESC away from it constantly, or it chucks "%%!" in my code.

Someone else reported this issue here: https://stackoverflow.com/questions/69134016/vscode-jupyter-strange-autocomplete

Extension version: 2021.9.1001312534
VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 4229)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (25.78GB free)|
|Process Argv|--crash-reporter-id 7693d6ac-337e-4f4a-a5f3-9b5534313163|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis200:30374795
vsaa593cf:30376535
vssld246:30379911

```

</details>

**Comment by Greco1899** [comment]
I'm facing the same issue.

Jupyter Extension
Version: 2021.9.1101343141

VS Code
Version: 1.61.0 (user setup)
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:13:09.652Z
OS: Windows_NT x64 10.0.19042

**Comment by FelipeCoimbra** [comment]
Same here, quite annoying.

This seems to have been introduced at v2021.8.2031187289.

Rolling mine back to v2021.8.1236758218 solved it for now.

**Comment by kvanderwijst** [comment]
Indeed, it really breaks up your typing workflow, having to Escape everytime you enter a new line in a notebook.

Can't there be a filter for "%%!"? I can't imagine it every being useful.

**Comment by shin-t-o** [comment]
I also downgraded to v2021.8.2031187289 to avoid this problem for now, but I hope you'll do something about it.
