### ISSUE TITLE
Intellisense issue categorization

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7912]
Categories:
- Could be fixed in a couple of days but might be throwaway- :rabbit2:
- Could be fixed without pylance but make take a while - :rooster: 
- Pylance would be better to handle - :turtle:
- Requires pylance to know about kernels - :skull:

Current open intellisense issues:

## Possible throwaway quick work:
- [x] :rabbit2: #6333 
- [x] :rabbit2: #867 
- [x] :rabbit2: #7821 
- [x] :rabbit2: #6799 
- [ ] :rabbit2: #6556 
- [x] :rabbit2: #5932 

## No pylance changes needed: 
- [ ] :rooster: #7816 
- [x] :rooster:#7772 
- [ ] :rooster:#7500 
- [x] :rooster: #7406 
- [x] :rooster: #7136 
- [ ] :rooster: #6253 
- [ ] :rooster: #7039 

## Pylance should handle:
- [ ] :turtle: #7286 
- [ ] :turtle: #5800 
- [ ] :turtle: #5705 
- [x] :turtle: #5123
- [ ] :turtle: #4307 
- [x] :turtle: #1686 
- [x] :turtle: #7492 
- [ ] :turtle: #7788 

## Requires Pylance understand kernels:
- [ ] :skull: #6987 
- [x] :skull: #6261

**Comment by IanMatthewHuff** [comment]
Closing meta issue.
