### ISSUE TITLE
Python version inconsistency 

### ISSUE THREAD

**Issue by zohimchandani** [microsoft/vscode-jupyter#7916]
## Environment data

-   VS Code version: 1.61.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001312534
-   Python Extension version (available under the Extensions sidebar): v2021.10.1317843341
-   OS (Windows | Mac | Linux distro) and version: MacOS BigSur 11.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local 

## Expected behaviour

The notebook should run with the version of python selected in the kernel. 

## Actual behaviour

As you can see in the image below, the top right shows a Python 3.9.6 kernel being selected with a virtual environment whereas when the code cell is run, `!python --version` yields `Python 2.7.16` version. 

<img width="1853" alt="Screenshot 2021-10-13 at 12 53 00" src="https://user-images.githubusercontent.com/60148725/137127491-d050420b-cdb1-4a14-992c-a3cf07c02287.png">

**Comment by DonJayamanne** [comment]
Reopening as this is a bug, something we did support.
I'll text this on my Mac.

@zohimchandani
Please could you provide the following:
* Output from Jupyter panel
* Run the following cell and provide the output
```python
import os
import sys
print(os.environ("Path"))
print(sys.executable)
```

import

**Comment by rchiodo** [comment]
> Reopening as this is a bug, something we did support.
I'll text this on my Mac.

Sorry not following. Use the ```!``` operator runs the python on the path. 

The question is whether or not the wrong python is still being used or not. Are you reproing that Don?

**Comment by zohimchandani** [comment]
<img width="955" alt="Screenshot 2021-10-20 at 18 35 17" src="https://user-images.githubusercontent.com/60148725/138142991-9c2d6a1e-170a-4fad-9153-a2779487ce1a.png">


<img width="932" alt="Screenshot 2021-10-20 at 18 35 31" src="https://user-images.githubusercontent.com/60148725/138143033-e7dc23a6-2975-475e-9c01-6e5fa301d244.png">
>

**Comment by DonJayamanne** [comment]
@zohimchandani 
* Apologies the python code was incorrect, please run `print(os.getenv("PATH")`
* You missed the output from the `Jupyter` output panel, please could you provide that as well.
You need to go into the otuput panel and select everything, copy it and paste it here.
![image](https://user-images.githubusercontent.com/1948812/138369282-fbb7748b-e7e8-4b5f-b435-b74113fedc04.png)

**Comment by DonJayamanne** [comment]
@zohimchandani 
I believe this issue has been resolved, please could you try this in VS Code insiders.
* Install VSCode insiders from here https://code.visualstudio.com/insiders/
* Install Jupyter extesnsion (in VS Code Insiders you'll automatically get the latest dev version of Jupyter extension built daily from our main branch)

**Comment by DonJayamanne** [comment]
Closing this issue for now.
