### ISSUE TITLE
Jupyter in vscode can't execute syntax highlighting

### ISSUE THREAD

**Issue by SupritYoung** [microsoft/vscode-jupyter#7917]
## Environment data

-   VS Code version: 1.61.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001312534
-   Python Extension version (available under the Extensions sidebar): v2021.10.1317843341
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: 3.8.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

syntax highlighting

## Actual behaviour

can't execute syntax highlighting

![image](https://user-images.githubusercontent.com/30597946/137140639-56e7df61-3728-454a-b5cb-b2329a41c5b4.png)

## Steps to reproduce:

I try to change the python kernel in vscode
![image](https://user-images.githubusercontent.com/30597946/137140664-d8f5fb5b-5b44-4aa8-a161-a4c1d27b08ff.png)

**Comment by CatNofishing** [comment]
@rchiodo  I have already mentioned this question, please refer to the following information https://github.com/microsoft/vscode-jupyter/issues/6799

**Comment by ssm951** [comment]
I have the same issue too, and just recently. For my cells in the lower right, it shows `CVE` instead of Python. When I click on it though, the command palette says that it was linting Python. What could have caused the issue?

![image](https://user-images.githubusercontent.com/42690337/137243995-082d2166-f0a7-4d20-944c-7a8a623c5f73.png)

**Comment by SupritYoung** [comment]
It's useful, Thank u so much !

**Comment by hbing-l** [comment]
Thank u so much!

**Comment by JohanesKristiadi** [comment]
thanks
