### ISSUE TITLE
Enable to disable the intellisense of string

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/vscode-jupyter#7925]
It's a little annoying when I hit a quote key (either ' or "), its pop-up a list of suggestions, like this:
![Screenshot (58)](https://user-images.githubusercontent.com/21306413/137244846-7a210f16-c5e4-45af-8949-0bb94232785d.png)

It does not exist in the python file, and I could not find a configuration to disable it. 

```
  "editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": false
  },
```
does not work. 

When I change the `other` to `false` it works in both python files and jupyter notebook, but `string` does not work  in either, the python file always has no intellisense while jupyter notebook always has.

**Comment by Micro-sheep** [comment]
> Thanks for the suggestion. Those are the completions that we get directly from Jupyter (we use both language server and Jupyter for suggestions). Seems like those might be ignoring the settings for editor suggestions.

It there any way to disable completions from jupyter and just enable completions from pylance like coding in `.py` file?

In previous version, it work well without completions from jupyter.

**Comment by rchiodo** [comment]
> It there any way to disable completions from jupyter and just enable completions from pylance like coding in .py file?
In previous version, it work well without completions from jupyter.

The only way to disable jupyter completions is to not run any code (they come from the active kernel).

Although there might be a hacky way. Set this environment variable to something like '1':

```
VSC_JUPYTER_IntellisenseTimeout
```
It's used to determine how long we wait for jupyter to give us back completions (jupyter can be slow if the kernel is busy).

See the code here:
https://github.com/microsoft/vscode-jupyter/blob/ef6ed387e28d8a1803301b1ec344939aaee4ee8a/src/client/datascience/notebook/intellisense/jupyterCompletionProvider.ts#L66

**Comment by Micro-sheep** [comment]
> > It there any way to disable completions from jupyter and just enable completions from pylance like coding in .py file?
> > In previous version, it work well without completions from jupyter.
> 
> The only way to disable jupyter completions is to not run any code (they come from the active kernel).
> 
> Although there might be a hacky way. Set this environment variable to something like '1':
> 
> ```
> VSC_JUPYTER_IntellisenseTimeout
> ```
> 
> It's used to determine how long we wait for jupyter to give us back completions (jupyter can be slow if the kernel is busy).
> 
> See the code here:
> 
> https://github.com/microsoft/vscode-jupyter/blob/ef6ed387e28d8a1803301b1ec344939aaee4ee8a/src/client/datascience/notebook/intellisense/jupyterCompletionProvider.ts#L66

It works well! Thanks!
