### ISSUE TITLE
Keep track of executed cell after restart

### ISSUE THREAD

**Issue by alandema** [microsoft/vscode-jupyter#7927]
I was expecting the VSCode Jupyter to have a similar feature to the Google Colab: When restart the kernel, the cells to lose their number and the ran check mark. By this you know what cell ran in the CURRENT kernel and what cell ran in the previous one.

![image](https://user-images.githubusercontent.com/68517641/137352396-803913d9-4fa8-409c-b343-3e54012ec5f7.png)
After restarting the kernel, it is difficult to keep track of what cell I need to run now.

**Comment by IanMatthewHuff** [comment]
This would be different from juypter functionality, but honestly it makes sense to me, seems like we should discuss.
