### ISSUE TITLE
Multi-workspace active interpreter is not used in the interactive window

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7928]
Open a multiple folder workspace
In folder A, set active interpreter to interpreter A
In folder B, set active interpreter to interpreter B

Open py file in folder B
Run IW

It should use interpreter B.

It uses interpreter A.

**Comment by DonJayamanne** [comment]
Found another duplicate today https://github.com/microsoft/vscode-jupyter/issues/7856 is alow a
