### ISSUE TITLE
Matplot lib Widget does not work

### ISSUE THREAD

**Issue by mpoehlmann** [microsoft/vscode-jupyter#7944]
Issue Type: <b>Bug</b>

Jupyter noteobok widgets aren't displayed and when trying to create, the cell runs indefinitely and I have to quit VSCode to get Jupyter to stop

Extension version: 2021.11.1313923388-dev
VS Code version: Code - Insiders 1.62.0-insider (Universal) (cad4c193d85f0891204da41c0508de39e7aa38c6, 2021-10-14T05:15:07.179Z)
OS version: Darwin arm64 20.4.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-81-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|16.00GB (0.70GB free)|
|Process Argv|--crash-reporter-id 5fb29690-0fca-46a0-aa90-19896736f2fe|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ucddark|
|OS|Linux x64 5.4.0-81-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz (32 x 1872)|
|Memory (System)|125.80GB (39.51GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30382699
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsqsis300:30381676
vsaa593cf:30376535

```

</details>

**Comment by claudiaregio** [comment]
@DonJayamanne 

VS Code: 1.62.0-insider
Python Ext: v2021.11.1313923388-dev
Jupyter Ext: v2021.10.1001345285
Env: Local, Conda, Python 3.7.10

[Matplotlib Widget Jupyter Output Logs.txt](https://github.com/microsoft/vscode-jupyter/files/7368658/Matplotlib.Widget.Jupyter.Output.Logs.txt
[Matplotlib Widget Developer Tools Output.zip](https://github.com/microsoft/vscode-jupyter/files/7368667/Matplotlib.Widget.Developer.Tools.Output.zip)
)

**Comment by Keeptg** [comment]
Same issue for me.

OS: Ubuntu 16.4
Environment: Local, Conda, Python 3.7.6
VS Code: 1.62.0
Python extension: v2021.11.1422169775
Jupyter extension: v2021.10.1001414422

**Comment by DonJayamanne** [comment]
@Keeptg 
Please could you be more specific, what do you mean by same issue?
Please could you provide the logs from the Jupyter output panel & the `Developer Tool` console output

**Comment by hsandmeyer** [comment]
Same problem for me. `ipywidgets.js` does exist

OS: Ubuntu 20.04
VS Code: 1.62.3
Jupyter extension: v2021.10.1101450599
Python extension: v2021.11.1422169775
Python 3.8.10 64-bit from system

The following code snipped does not show a graph

```
%matplotlib widget
import ipywidgets as widgets
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(figsize=(6, 4))
ax.set_ylim([-4, 4])
ax.grid(True)
 
x = np.linspace(0, 2 * np.pi, 100)
 
def my_sine(x, w, amp, phi):
    return amp*np.sin(w * (x-phi))
 
@widgets.interact(w=(0, 10, 1), amp=(0, 4, .1), phi=(0, 2*np.pi+0.01, 0.01))
def update(w = 1.0, amp=1, phi=0):
    [l.remove() for l in ax.lines]
    ax.plot(x, my_sine(x, w, amp, phi), color='C0')
```
![tmp](https://user-images.githubusercontent.com/26244423/142642225-94421989-483b-4782-9757-9d75393eb245.png)

No specific output from the python console.
I attached the developer tool console log.
[vscode-app-1637332672684.log](https://github.com/microsoft/vscode-jupyter/files/7570982/vscode-app-1637332672684.log)

**Comment by DonJayamanne** [comment]
@hsandmeyer please could you see a separate issue. Three issues this area running into is different.

**Comment by hsandmeyer** [comment]
@DonJayamanne Sorry, I should have been more specific. I am pretty sure, that this is the same issue as in the initial post as the code in https://github.com/microsoft/vscode-jupyter/issues/7944#issuecomment-944628954 does not work for me as well. Removing the first line helps and the graph appears. However, without the first line in my code example, the widget slider do not have any effect.

**Comment by DonJayamanne** [comment]
@hsandmeyer Oh, thanks for the confirmation, let me look into this.
* Are you using WSL?
* Where did you install Python from?
* Please could you provide the output from `python -m pip list` for the above python environment?

**Comment by hsandmeyer** [comment]
@DonJayamanne `%matplotlib ipympl` does not work as well and behaves the same way as `%matplitlib widget`. `%matplotlib notebook` does not work and does not show a graph. I think this is expected according to #1948 and #4056. One more note: `%matplotlib widget` used to work before. It was one of the more recent updates that broke it. Not sure which one though, as I did not use the jupyter plugin for a few weeks. Using `%matplotlib notebook` never worked before

**Comment by DonJayamanne** [comment]
I'm sorry, yes, you need to use `%matplotlib widget`
I'll check this out.

**Comment by hsandmeyer** [comment]
Small update:
Appears to be fixed for me since updating the jupyter extension to version v2021.11.1001550889 and vscode to version 1.63.0

**Comment by Keeptg** [comment]
> Small update: Appears to be fixed for me since updating the jupyter extension to version v2021.11.1001550889 and vscode to version 1.63.0

It also works to me!

**Comment by DonJayamanne** [comment]
Thanks everyone for the confirmation, closing this issue.
