### ISSUE TITLE
Command `jupyter.exportoutputasnotebook` is no longer supported in Interactive window

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7947]
We're throwing an error `no supported`.

**Comment by rzhao271** [comment]
I'm unable to run that command from the command palette, still.
What are some steps to verify this issue?

**Comment by rchiodo** [comment]
Sorry, repro steps are:
1. Create a python file with a cell in it ```#%%\nprint(1)``` should work
2. Click on the 'Run Cell' code lens
3. Wait for cell to run
3. Open command palette
3. Export interactive window as notebook

**Comment by rchiodo** [comment]
Should look like this:
![image](https://user-images.githubusercontent.com/19672699/144681073-e51d960f-8a34-449b-82eb-1899bd81bc65.png)

**Comment by rzhao271** [comment]
Verified, but I noticed that if I reloaded, just created an interactive window, and tried to run the command, it would not show up.

**Comment by rchiodo** [comment]
> if I reloaded, just created an interactive window, and tried to run the command, it would not show up.

I didn't think we had this check but theoretically it should only activate if there are actual cells in the window (as the exported notebook would be empty)
