### ISSUE TITLE
Expanding column length in Data Viewer

### ISSUE THREAD

**Issue by alandema** [microsoft/vscode-jupyter#7950]
## Environment data

- VS Code version: 1.61.1
- Jupyter Extension version (available under the Extensions sidebar): v2021.9.1101343141
- Python Extension version (available under the Extensions sidebar): v2021.10.1336267007
- OS (Windows | Mac | Linux distro) and version: W10 H1
- Python and/or Anaconda version: 3.9.5
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Jupyter server running: Local

## Expected behaviour

When expanding the size of the last column (or some other column) in data viewer  to more than the maximum panel size, to be able to expand the columns as much as the user wants to.

## Actual behaviour

When you try to expand the column to outside the Data Viewer panel, the cursor get stuck clicked in the the column and it will not let go until a new click inside Data Viewer panel.

## Steps to reproduce:

Try to expand the last column, to see the whole name.

![vscode](https://user-images.githubusercontent.com/68517641/137557271-71f62c79-c4f2-410a-8bf4-bb136cca37b7.gif)

Even if you close the terminal panel, the outcome is not optimal. You need to keep scrolling to the side to expand the column little by little.

![vscode2](https://user-images.githubusercontent.com/68517641/137557543-adfc3eb0-147c-4600-84cd-5aaf5653257c.gif)

**Comment by claudiaregio** [comment]
Thanks @alandema for the GIF and info! I am able to reproduce this behavior and we will look into this as soon as we can.

**Comment by rchiodo** [comment]
Double clicking would be a nice way to do this instead (we don't support it yet though).

**Comment by ShafinKhadem** [comment]
How about adding a dummy column with screen width as rightmost column?
