### ISSUE TITLE
vscode-jupyter changes cells that were not modified: removes \n at the end of every "image/png" field

### ISSUE THREAD

**Issue by ageron** [microsoft/vscode-jupyter#7957]
## Environment data

-   VS Code version: Version: 1.61.1, commit c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1101343141
-   Python Extension version (available under the Extensions sidebar): v2021.10.1336267007
-   OS (Windows | Mac | Linux distro) and version: OS: Darwin x64 19.6.0
-   Python and/or Anaconda version: 3.8.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

When opening in VSCode a Jupyter notebook created using Jupyter Notebook or Jupyter Lab and making a tiny change to one cell, then saving the notebook, the other cells in the notebook should not be modified.

## Actual behaviour

Every cell that outputs an image (e.g., using Matplotlib) is modified. Specifically, the `\n` at the end of every `"image/png"` field is removed. This makes switching between VSCode and Jupyter Notebook/Lab very painful, especially when working with git, as even minor changes lead to large diffs.

## Steps to reproduce:

1. Create a notebook with Jupyter Notebook or Jupyter Lab, and run the following code:

```python
import matplotlib.pyplot as plt

plt.plot([1,2,3], [3, 1, 2])
plt.show()
```
2. Save the notebook. You can verify that the `"image/png"` field has a `\n` at the end.
3. Open the notebook in VScode, make a tiny modification without running the notebook or modifying the existing cells (e.g., add a markdown cell).
4. Save the notebook. You can verify that the `"image/png"` field no longer has a `\n` at the end. It was modified even though we didn't touch it.

**Comment by DonJayamanne** [comment]
Closing this issue as no one else has reported this nor have there been any upvotes on this issue
