### ISSUE TITLE
Display warning when user selects outdated versions of Python

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7960]
Python 2.7, 3.5, (soon 3.6), etc
We have users constantly running into issues with these.
Just a simple modal dialog warning `Are you sure, yes, cancel, do not show again`

I hate dialogs, but we want to avoid instances when novice users running into issues with python + jupyter (data science)

**Comment by greazer** [comment]
Yeah, let's do this.

**Comment by DonJayamanne** [comment]
This has been done, closing for verification.
