### ISSUE TITLE
Summary of Commands/Toolbar issues (not hiding/disabling or invalid items)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7968]
* https://github.com/microsoft/vscode-jupyter/issues/7242
* https://github.com/microsoft/vscode-jupyter/issues/7604
* https://github.com/microsoft/vscode-jupyter/issues/7726
* https://github.com/microsoft/vscode-jupyter/issues/6996
* https://github.com/microsoft/vscode-jupyter/issues/6543
* https://github.com/microsoft/vscode-jupyter/issues/7568
* https://github.com/microsoft/vscode-jupyter/issues/6626
* https://github.com/microsoft/vscode-jupyter/issues/7947

**Comment by roblourens** [comment]
Seems like all these issues have owners now, can we close this one?
