### ISSUE TITLE
Variable Explorer: Some variables are stuck in the loading state

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode-jupyter#7970]
VS Code Version: 1.62.0-insider (user setup)
Commit: 34eeebdd66033633ac22efd5fab928ae37916168
Date: 2021-10-15T05:16:57.817Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
Jupyter extension: v2021.10.1001358390

Steps to repro:
1. open this notebook file https://github.com/claudiaregio/data-science/blob/main/Titanic.ipynb
2. Run all cells. When completed, open the Variable Explorer.
3. Scroll to the top of the Variable explorer.
4. Jump to the "Neural Network" section in the file, "Run all above cells" on the first cell in the section.
5. When run finishes, scroll to the bottom of Variable Explorer

Expected: all variables are shown
![image](https://user-images.githubusercontent.com/26419852/137988819-5f6a01dc-2b50-49c8-912a-bf93d93d2467.png)

Actual: the bottom variables are stuck in the loading state
![image](https://user-images.githubusercontent.com/26419852/137988505-052d5236-6c26-4fcd-a19a-27d304bafdc1.png)

**Comment by amunger** [comment]
I've been able to repro something similar just by creating a few hundred variables and expanding the variable explorer and the ones stuck in loading are actually on the initial page of the explorer. It's pretty tough to get it to repro like this though, and closing and re-opening the explorer makes the issue go away (not sure about the original repro steps)

**Comment by IanMatthewHuff** [comment]
I have a consistent repro on this (well on at least one aspect). Working on the fix, but to make sure that I note it here:

1. Create a notebook that has a bunch of variables (to make sure that we have pages)
2. Run the notebook, scroll down the variable list (all should be ok)
3. Restart the kernel
4. Run the notebook again
5. Scroll down the variable list (all is not well, things show up as loading... off the first page.)

**Comment by minsa110** [comment]
Thanks for fixing this issue! :) I have one minor suggestion to add here. When I open the variable viewer, it says "No variables defined" while it's searching for / loading the variables. Could we replace that string with something like "Loading" / "Working on it..." / somewhere along those lines? And then afterwards when we actually don't have anything to show, replace that message with "No variables defined"?

Expected:
![image](https://user-images.githubusercontent.com/10833267/149392175-ab1a0190-03b3-46a7-82a2-4f2e93efb246.png)

Actual:
![image](https://user-images.githubusercontent.com/10833267/149391908-4d231f24-270e-4ae1-bf1a-86f20a57bfe1.png)

https://user-images.githubusercontent.com/10833267/149391956-773a457c-0ed8-4317-b6b2-09b936415f7f.mp4
