### ISSUE TITLE
.ipynb NameError: name 'x' is not defined

### ISSUE THREAD

**Issue by SMAshhar** [microsoft/vscode-jupyter#7971]
Issue Type: <b>Bug</b>

CELL 1:
import tensorflow.keras as tf
import numpy as np

path = tf.utils.get_file(
    'nietzche.txt',
    origin='https://s3.amazonaws.com/text-datasets/nietzsche.txt'
    )

Text = open(path).read().lower()

print('corpus length: ', len(Text))
max_len = 60

step = 3

sentences = []
next_word = []

for i in range(0, len(Text)-60, step):
    sentences.append(Text[i: i+ max_len])
    next_word.append(Text[i+max_len])
print("Number of sequences: ", len(sentences))
chars = sorted(list(set(Text)))
print("Number of unique characters", len(chars))
char_dict = dict((char, chars.index(char)) for char in chars)
print("Vectorizing.....")
x = np.zeros((len(sentences), max_len, len(chars)))
y = np.zeros((len(sentences), len(chars)))

for i, sentence in enumerate(sentences):
    for j, char in enumerate(sentence):
        x[i, j, char_dict[char]] = 1
    y[i, char_dict[next_word[i]]] = 1

Result:
corpus length:  600893
Number of sequences:  200278
Number of unique characters 57
Vectorizing.....

CELL 2:
x

Result
NameError: name 'x' is not defined

VS Code version: Code 1.61.1 (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63, 2021-10-14T01:15:35.620Z)
OS version: Linux x64 5.11.0-37-generic snap
Restricted Mode: No

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.6.1
vscode-graphql|Gra|0.3.18
vscode-docker|ms-|1.17.0
python|ms-|2021.10.1336267007
vscode-pylance|ms-|2021.10.1
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.202.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis200:30381674
vsaa593cf:30376535
vssld246:30379911

```

</details>

**Comment by rchiodo** [comment]
Thanks for the bug.

Unfortunately I'm not reproing. I get this:

![image](https://user-images.githubusercontent.com/19672699/137999115-894b87cb-794e-439a-a2d2-59a17bd053db.png)

Did it perhaps crash during vectorization?

**Comment by rchiodo** [comment]
@SMAshhar is this still reproing? Do you have a smaller repro perhaps? Please reopen if you have any more information.

**Comment by SMAshhar** [comment]
The problem still persists brother. 😥

**Comment by rchiodo** [comment]
You might try with a smaller set of sentences (smaller root file) to see if perhaps it's crashing somewhere. Or try using 'Run by line' to step through it.
