### ISSUE TITLE
listen EFAULT: bad addressin system call argument

### ISSUE THREAD

**Issue by sangkim22** [microsoft/vscode-jupyter#7974]
## Environment data

-   VS Code version: 1.61.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1101343141
-   Python Extension version (available under the Extensions sidebar): v2021.10.1336267007
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: Python 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local 

## Expected behaviour

If I run a cell, it should run a code.

## Actual behaviour

It says 
"listen EFAULT: bad address in system call argument 172.20.16.:9000
sometimes the address starts with 127

Also, sometimes jupyter notebook works fine. 
After using several minutes, jupyter notebook does not work and send this message.
How should I deal with this?
Can you explain why this is happening?

![Capture](https://user-images.githubusercontent.com/64191698/138046069-9ac969cc-74de-47f9-afb0-ed737ad722f4.PNG)

**Comment by sangkim22** [comment]
![image](https://user-images.githubusercontent.com/64191698/138199249-4a5de4ab-ba7a-4066-8c12-820c7e711d8b.png)

Hi thank you for the reply

this is what I have!

**Comment by rchiodo** [comment]
Sorry but can you copy the entire contents of that pane? If you save it to a text file, you can just drag it into this issue.

**Comment by sangkim22** [comment]
Ok
This is all I got!


Info 2021-10-22 12:31:13: Experimentation service retrieved: [object Object]
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 2021-10-22 12:31:13: ZMQ install verified.
Info 2021-10-22 12:31:57: No controller, hence notebook communications cannot be initialized for editor file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:31:57: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 2021-10-22 12:31:57: Find preferred kernel for file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"python"}} & preferred interpreter {"sysPrefix":"C:\\ProgramData\\Anaconda3","envType":"Conda","envName":"base","envPath":"C:\\ProgramData\\Anaconda3","path":"C:\\ProgramData\\Anaconda3\\python.exe","architecture":3,"sysVersion":"3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]","version":{"raw":"3.8.8","major":3,"minor":8,"patch":8,"build":[],"prerelease":["final","0"]},"companyDisplayName":"ContinuumAnalytics","displayName":"Python 3.8.8 64-bit ('base': conda)"}
Info 2021-10-22 12:31:57: findKernel found Python 3.8.8 64-bit ('base': conda)
Info 2021-10-22 12:31:57: Find kernel spec, Class name = x, completed in 24ms, has a truthy return value, Arg 1: <Uri:c:\Users\Sang\Documents\GitHub\Paper_Lazy_Pricce\.ipynb>, Arg 2: {"orig_nbformat":4,"language_info":{"name":"python"}}, Arg 3: {"_isCancelled":false,"_emitter":{"_disposed":false,"_listeners":{"_first":{"next":{},"prev":{}},"_last":{"next":{},"prev":{}},"_size":1}}}, Return Value: {"kind":"startUsingPythonInterpreter","kernelSpec":{"specFile":"C:\\ProgramData\\Anaconda3\\share\\jupyter\\kernels\\python3\\kernel.json","interpreterPath":"C:\\ProgramData\\Anaconda3\\python.exe","name":"python388jvsc74a57bd0b3ba2566441a7c06988d0923437866b63cedc61552a5af99d1f4fb67d367b25f","argv":["C:/ProgramData/Anaconda3\\python.exe","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"C:/ProgramData/Anaconda3\\python.exe","display_name":"Python 3.8.8 64-bit ('base': conda)"},"interpreter":{"sysPrefix":"C:\\ProgramData\\Anaconda3","envType":"Conda","envName":"base","envPath":"C:\\ProgramData\\Anaconda3","path":"C:\\ProgramData\\Anaconda3\\python.exe","architecture":3,"sysVersion":"3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]","version":{"raw":"3.8.8","major":3,"minor":8,"patch":8,"build":[],"prerelease":["final","0"]},"companyDisplayName":"ContinuumAnalytics","displayName":"Python 3.8.8 64-bit ('base': conda)"},"id":".jvsc74a57bd0b3ba2566441a7c06988d0923437866b63cedc61552a5af99d1f4fb67d367b25f.C:\\ProgramData\\Anaconda3\\python.exe.C:\\ProgramData\\Anaconda3\\python.exe.-m#ipykernel_launcher"}
Info 2021-10-22 12:31:57: PreferredConnection: .jvsc74a57bd0b3ba2566441a7c06988d0923437866b63cedc61552a5af99d1f4fb67d367b25f.C:\ProgramData\Anaconda3\python.exe.C:\ProgramData\Anaconda3\python.exe.-m#ipykernel_launcher found for NotebookDocument: file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:31:57: Loading kernelspec from C:\ProgramData\Anaconda3\share\jupyter\kernels\python3\kernel.json for C:\ProgramData\Anaconda3\python.exe
Info 2021-10-22 12:31:57: TargetController found ID: .jvsc74a57bd0b3ba2566441a7c06988d0923437866b63cedc61552a5af99d1f4fb67d367b25f.C:\ProgramData\Anaconda3\python.exe.C:\ProgramData\Anaconda3\python.exe.-m#ipykernel_launcher for document file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:31:57: Setting controller affinity for file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb .jvsc74a57bd0b3ba2566441a7c06988d0923437866b63cedc61552a5af99d1f4fb67d367b25f.C:\ProgramData\Anaconda3\python.exe.C:\ProgramData\Anaconda3\python.exe.-m#ipykernel_launcher
Info 2021-10-22 12:31:57: Kernel python388jvsc74a57bd0b3ba2566441a7c06988d0923437866b63cedc61552a5af99d1f4fb67d367b25f matches Python 3.8.8 64-bit ('base': conda) based on path in argv.
Info 2021-10-22 12:31:57: Kernel python388jvsc74a57bd0b3ba2566441a7c06988d0923437866b63cedc61552a5af99d1f4fb67d367b25f matches Python 3.8.8 64-bit ('base': conda) based on path in argv.
Error 2021-10-22 12:31:59: Live Notebook not available for file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:31:59: Process Execution: > C:\ProgramData\Anaconda3\python.exe -c "import jupyter"
> C:\ProgramData\Anaconda3\python.exe -c "import jupyter"
Info 2021-10-22 12:31:59: Process Execution: > C:\ProgramData\Anaconda3\python.exe -c "import notebook"
> C:\ProgramData\Anaconda3\python.exe -c "import notebook"
Error 2021-10-22 12:31:59: Live Notebook not available for file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:31:59: Process Execution: > C:\ProgramData\Anaconda3\python.exe -m jupyter kernelspec --version
> C:\ProgramData\Anaconda3\python.exe -m jupyter kernelspec --version
Info 2021-10-22 12:32:00: Creating daemon pool for C:\ProgramData\Anaconda3\python.exe with env variables count 74
Info 2021-10-22 12:32:00: Process Execution: > C:\ProgramData\Anaconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> C:\ProgramData\Anaconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
Info 2021-10-22 12:32:00: Process Execution: > C:\ProgramData\Anaconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> C:\ProgramData\Anaconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
Info 2021-10-22 12:32:00: Process Execution: > C:\ProgramData\Anaconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> C:\ProgramData\Anaconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
Error 2021-10-22 12:32:00: Live Notebook not available for file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Error 2021-10-22 12:32:01: Live Notebook not available for file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Error 2021-10-22 12:32:02: Live Notebook not available for file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Error 2021-10-22 12:32:02: Live Notebook not available for file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:32:05: Setting setActiveController for file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:32:05: Intiailize notebook communications for editor file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:32:05: Resolving notebook UI Comms (resolve) for file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:32:05: initialize CommonMessageCoordinator
Info 2021-10-22 12:32:05: Execute Cells request 1 0
Info 2021-10-22 12:32:05: Execute Cell 0 file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:32:05: Starting Notebook in kernel.ts id = .jvsc74a57bd0b3ba2566441a7c06988d0923437866b63cedc61552a5af99d1f4fb67d367b25f.C:\ProgramData\Anaconda3\python.exe.C:\ProgramData\Anaconda3\python.exe.-m#ipykernel_launcher
Info 2021-10-22 12:32:05: Creating raw notebook for file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:32:05: Getting preferred kernel for file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:32:05: Computing working directory file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:32:05: Process Execution: > C:\ProgramData\Anaconda3\python.exe -m pip list
> C:\ProgramData\Anaconda3\python.exe -m pip list
Info 2021-10-22 12:32:05: Connecting to raw session for file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb with connection {"kind":"startUsingPythonInterpreter","kernelSpec":{"interpreterPath":"C:\\ProgramData\\Anaconda3\\python.exe","name":"python388jvsc74a57bd0b3ba2566441a7c06988d0923437866b63cedc61552a5af99d1f4fb67d367b25f","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"python","display_name":"Python 3.8.8 64-bit ('base': conda)","metadata":{"interpreter":{"sysPrefix":"C:\\ProgramData\\Anaconda3","envType":"Conda","envName":"base","envPath":"C:\\ProgramData\\Anaconda3","path":"C:\\ProgramData\\Anaconda3\\python.exe","architecture":3,"sysVersion":"3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]","version":{"raw":"3.8.8","major":3,"minor":8,"patch":8,"build":[],"prerelease":["final","0"]},"companyDisplayName":"ContinuumAnalytics","displayName":"Python 3.8.8 64-bit ('base': conda)"}},"env":{}},"interpreter":{"sysPrefix":"C:\\ProgramData\\Anaconda3","envType":"Conda","envName":"base","envPath":"C:\\ProgramData\\Anaconda3","path":"C:\\ProgramData\\Anaconda3\\python.exe","architecture":3,"sysVersion":"3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]","version":{"raw":"3.8.8","major":3,"minor":8,"patch":8,"build":[],"prerelease":["final","0"]},"companyDisplayName":"ContinuumAnalytics","displayName":"Python 3.8.8 64-bit ('base': conda)"},"id":".jvsc74a57bd0b3ba2566441a7c06988d0923437866b63cedc61552a5af99d1f4fb67d367b25f.C:\\ProgramData\\Anaconda3\\python.exe.C:\\ProgramData\\Anaconda3\\python.exe.-m#ipykernel_launcher"}
Info 2021-10-22 12:32:05: Starting raw kernel Python 3.8.8 64-bit ('base': conda)
Info 2021-10-22 12:32:05: installMissingDependencies C:\ProgramData\Anaconda3\python.exe
Info 2021-10-22 12:32:05: Process Execution: > C:\ProgramData\Anaconda3\python.exe -c "import ipykernel"
> C:\ProgramData\Anaconda3\python.exe -c "import ipykernel"
Info 2021-10-22 12:32:05: KernelProvider switched kernel to id = .jvsc74a57bd0b3ba2566441a7c06988d0923437866b63cedc61552a5af99d1f4fb67d367b25f.C:\ProgramData\Anaconda3\python.exe.C:\ProgramData\Anaconda3\python.exe.-m#ipykernel_launcher
Info 2021-10-22 12:32:07: Install Missing Dependencies, Class name = S, completed in 1674ms, has a falsy return value, Return Value: undefined
Error 2021-10-22 12:32:07: Failed to connect raw kernel session: Error: listen EFAULT: bad address in system call argument :::9000
Info 2021-10-22 12:32:07: Shutdown session -- complete
Error 2021-10-22 12:32:07: failed to create INotebook in kernel, UI Disabled = undefined [Error: listen EFAULT: bad address in system call argument :::9000
	at Server.setupListenHandle [as _listen2] (net.js:1318:16)
	at listenInCluster (net.js:1366:12)
	at Server.listen (net.js:1452:7)
	at Object.testPort (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:755312)
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:756090
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:773185
	at l (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763794)
	at c (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763698)
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763492
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:756336
	at Server.r (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:754754)
	at Object.onceWrapper (events.js:421:28)
	at Server.emit (events.js:315:20)
	at emitListeningNT (net.js:1352:10)
	at processTicksAndRejections (internal/process/task_queues.js:79:21)] {
  code: 'EFAULT',
  errno: -4074,
  syscall: 'listen',
  address: '::',
  port: 9000
}
Error 2021-10-22 12:32:07: DataScience Error [Error: listen EFAULT: bad address in system call argument :::9000
	at Server.setupListenHandle [as _listen2] (net.js:1318:16)
	at listenInCluster (net.js:1366:12)
	at Server.listen (net.js:1452:7)
	at Object.testPort (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:755312)
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:756090
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:773185
	at l (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763794)
	at c (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763698)
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763492
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:756336
	at Server.r (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:754754)
	at Object.onceWrapper (events.js:421:28)
	at Server.emit (events.js:315:20)
	at emitListeningNT (net.js:1352:10)
	at processTicksAndRejections (internal/process/task_queues.js:79:21)] {
  code: 'EFAULT',
  errno: -4074,
  syscall: 'listen',
  address: '::',
  port: 9000
}
Error 2021-10-22 12:32:07: failed to start INotebook in kernel, UI Disabled = undefined [Error: listen EFAULT: bad address in system call argument :::9000
	at Server.setupListenHandle [as _listen2] (net.js:1318:16)
	at listenInCluster (net.js:1366:12)
	at Server.listen (net.js:1452:7)
	at Object.testPort (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:755312)
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:756090
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:773185
	at l (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763794)
	at c (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763698)
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763492
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:756336
	at Server.r (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:754754)
	at Object.onceWrapper (events.js:421:28)
	at Server.emit (events.js:315:20)
	at emitListeningNT (net.js:1352:10)
	at processTicksAndRejections (internal/process/task_queues.js:79:21)] {
  code: 'EFAULT',
  errno: -4074,
  syscall: 'listen',
  address: '::',
  port: 9000
}
Error 2021-10-22 12:32:07: Failed to execute cells in CellExecutionQueue [Error: listen EFAULT: bad address in system call argument :::9000
	at Server.setupListenHandle [as _listen2] (net.js:1318:16)
	at listenInCluster (net.js:1366:12)
	at Server.listen (net.js:1452:7)
	at Object.testPort (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:755312)
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:756090
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:773185
	at l (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763794)
	at c (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763698)
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763492
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:756336
	at Server.r (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:754754)
	at Object.onceWrapper (events.js:421:28)
	at Server.emit (events.js:315:20)
	at emitListeningNT (net.js:1352:10)
	at processTicksAndRejections (internal/process/task_queues.js:79:21)] {
  code: 'EFAULT',
  errno: -4074,
  syscall: 'listen',
  address: '::',
  port: 9000
}
Info 2021-10-22 12:32:07: Cancel pending cells
Info 2021-10-22 12:32:36: Execute Cells request 1 0
Info 2021-10-22 12:32:36: Execute Cell 0 file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:32:36: Starting Notebook in kernel.ts id = .jvsc74a57bd0b3ba2566441a7c06988d0923437866b63cedc61552a5af99d1f4fb67d367b25f.C:\ProgramData\Anaconda3\python.exe.C:\ProgramData\Anaconda3\python.exe.-m#ipykernel_launcher
Info 2021-10-22 12:32:36: Creating raw notebook for file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:32:36: Getting preferred kernel for file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:32:36: Computing working directory file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb
Info 2021-10-22 12:32:36: Connecting to raw session for file:///c%3A/Users/Sang/Documents/GitHub/Paper_Lazy_Pricce/.ipynb with connection {"kind":"startUsingPythonInterpreter","kernelSpec":{"interpreterPath":"C:\\ProgramData\\Anaconda3\\python.exe","name":"python388jvsc74a57bd0b3ba2566441a7c06988d0923437866b63cedc61552a5af99d1f4fb67d367b25f","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"python","display_name":"Python 3.8.8 64-bit ('base': conda)","metadata":{"interpreter":{"sysPrefix":"C:\\ProgramData\\Anaconda3","envType":"Conda","envName":"base","envPath":"C:\\ProgramData\\Anaconda3","path":"C:\\ProgramData\\Anaconda3\\python.exe","architecture":3,"sysVersion":"3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]","version":{"raw":"3.8.8","major":3,"minor":8,"patch":8,"build":[],"prerelease":["final","0"]},"companyDisplayName":"ContinuumAnalytics","displayName":"Python 3.8.8 64-bit ('base': conda)"}},"env":{}},"interpreter":{"sysPrefix":"C:\\ProgramData\\Anaconda3","envType":"Conda","envName":"base","envPath":"C:\\ProgramData\\Anaconda3","path":"C:\\ProgramData\\Anaconda3\\python.exe","architecture":3,"sysVersion":"3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]","version":{"raw":"3.8.8","major":3,"minor":8,"patch":8,"build":[],"prerelease":["final","0"]},"companyDisplayName":"ContinuumAnalytics","displayName":"Python 3.8.8 64-bit ('base': conda)"},"id":".jvsc74a57bd0b3ba2566441a7c06988d0923437866b63cedc61552a5af99d1f4fb67d367b25f.C:\\ProgramData\\Anaconda3\\python.exe.C:\\ProgramData\\Anaconda3\\python.exe.-m#ipykernel_launcher"}
Info 2021-10-22 12:32:36: Starting raw kernel Python 3.8.8 64-bit ('base': conda)
Info 2021-10-22 12:32:36: installMissingDependencies C:\ProgramData\Anaconda3\python.exe
Info 2021-10-22 12:32:36: Process Execution: > C:\ProgramData\Anaconda3\python.exe -c "import ipykernel"
> C:\ProgramData\Anaconda3\python.exe -c "import ipykernel"
Info 2021-10-22 12:32:37: Install Missing Dependencies, Class name = S, completed in 705ms, has a falsy return value, Return Value: undefined
Error 2021-10-22 12:32:37: Failed to connect raw kernel session: Error: listen EFAULT: bad address in system call argument :::9000
Info 2021-10-22 12:32:37: Shutdown session -- complete
Error 2021-10-22 12:32:37: failed to create INotebook in kernel, UI Disabled = undefined [Error: listen EFAULT: bad address in system call argument :::9000
	at Server.setupListenHandle [as _listen2] (net.js:1318:16)
	at listenInCluster (net.js:1366:12)
	at Server.listen (net.js:1452:7)
	at Object.testPort (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:755312)
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:756090
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:773185
	at l (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763794)
	at c (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763698)
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763492
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:756336
	at Server.r (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:754754)
	at Object.onceWrapper (events.js:421:28)
	at Server.emit (events.js:315:20)
	at emitListeningNT (net.js:1352:10)
	at processTicksAndRejections (internal/process/task_queues.js:79:21)] {
  code: 'EFAULT',
  errno: -4074,
  syscall: 'listen',
  address: '::',
  port: 9000
}
Error 2021-10-22 12:32:37: DataScience Error [Error: listen EFAULT: bad address in system call argument :::9000
	at Server.setupListenHandle [as _listen2] (net.js:1318:16)
	at listenInCluster (net.js:1366:12)
	at Server.listen (net.js:1452:7)
	at Object.testPort (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:755312)
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:756090
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:773185
	at l (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763794)
	at c (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763698)
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763492
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:756336
	at Server.r (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:754754)
	at Object.onceWrapper (events.js:421:28)
	at Server.emit (events.js:315:20)
	at emitListeningNT (net.js:1352:10)
	at processTicksAndRejections (internal/process/task_queues.js:79:21)] {
  code: 'EFAULT',
  errno: -4074,
  syscall: 'listen',
  address: '::',
  port: 9000
}
Error 2021-10-22 12:32:37: failed to start INotebook in kernel, UI Disabled = undefined [Error: listen EFAULT: bad address in system call argument :::9000
	at Server.setupListenHandle [as _listen2] (net.js:1318:16)
	at listenInCluster (net.js:1366:12)
	at Server.listen (net.js:1452:7)
	at Object.testPort (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:755312)
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:756090
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:773185
	at l (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763794)
	at c (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763698)
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763492
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:756336
	at Server.r (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:754754)
	at Object.onceWrapper (events.js:421:28)
	at Server.emit (events.js:315:20)
	at emitListeningNT (net.js:1352:10)
	at processTicksAndRejections (internal/process/task_queues.js:79:21)] {
  code: 'EFAULT',
  errno: -4074,
  syscall: 'listen',
  address: '::',
  port: 9000
}
Error 2021-10-22 12:32:37: Failed to execute cells in CellExecutionQueue [Error: listen EFAULT: bad address in system call argument :::9000
	at Server.setupListenHandle [as _listen2] (net.js:1318:16)
	at listenInCluster (net.js:1366:12)
	at Server.listen (net.js:1452:7)
	at Object.testPort (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:755312)
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:756090
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:773185
	at l (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763794)
	at c (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763698)
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:763492
	at c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:756336
	at Server.r (c:\Users\Sang\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:754754)
	at Object.onceWrapper (events.js:421:28)
	at Server.emit (events.js:315:20)
	at emitListeningNT (net.js:1352:10)
	at processTicksAndRejections (internal/process/task_queues.js:79:21)] {
  code: 'EFAULT',
  errno: -4074,
  syscall: 'listen',
  address: '::',
  port: 9000
}

Thanks!

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
