### ISSUE TITLE
code navigation doesn't work when choose kernel in remote jupyter mode 

### ISSUE THREAD

**Issue by Qiuzhuang** [microsoft/vscode-jupyter#7990]

**Comment by IanMatthewHuff** [comment]
@Qiuzhuang Just to check, do you mean features like "go to definition" for code navigation?

**Comment by greazer** [comment]
Currently, features like goto definition do not work well with remote kernels. We may revisit in the future.

**Comment by DonJayamanne** [comment]
Closing this issue as there haven't been any upvotes or comments for this issue.
