### ISSUE TITLE
Jupyter Variable Explorer layout

### ISSUE THREAD

**Issue by LeonM23** [microsoft/vscode-jupyter#7992]
Issue Type: <b>Feature Request</b>

I'm addicted to layout of Spyder. And I found that for a earlier version of Python Extension ( v 2020.10), the variable explorer for Interactive Window lies at the upper right, as the same as the Spyder layout. However, for the latest version of Python Extension(v 2021.10), it is, called Jupyter : Variables,  placed in panel area, and can not be dragged into editor area. Is it possible to rearrange the Jupyter: Variables?

Extension version: 2020.10.332292344
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/165445
