### ISSUE TITLE
Add ability to provide code completions for modules imported in startup commands

### ISSUE THREAD

**Issue by JordanLongstaff** [microsoft/vscode-jupyter#7993]
At my workplace, we have a specific code file written to provide useful helper functions whenever we choose to run IPython in a terminal:

```
ipython -i -m server.scripts.interactive
```

I want to have an option to run that file by default every time I create a new Jupyter Interactive Window. I've tried running it manually using Jupyter's `Run File in Interactive Window` feature, but it results in the working directory being shifted to the directory containing the file that is run, which is wrong. The working directory needs to be the workspace root or else the script will fail along with everything else I try to do. Plus, it would simply be nice to not have to navigate to that file just to run it every time I want to use an Interactive Window.

**Comment by rchiodo** [comment]
This definitely wasn't working. I think we may have misunderstood what the bug was about.

**Comment by IanMatthewHuff** [comment]
Looks good to me. Tried it with a basic local module in startup commands and I got completions for it.

![image](https://user-images.githubusercontent.com/812783/144328528-3de08b3d-7acc-4643-8e45-3b6860089a2e.png)
