### ISSUE TITLE
Jupyter: Export Current Python File and Output as Jupyter Notebook doesn't use the active virtual environment

### ISSUE THREAD

**Issue by alexkyllo** [microsoft/vscode-jupyter#7999]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I have a .py file with Jupyter code cells open and a virtual environment (created by Pipenv) active

![image](https://user-images.githubusercontent.com/2609312/138350538-5262bb23-dc58-4b52-a5c3-e66eaf133446.png)

When I run the "Jupyter: Export Current Python File and Output as Jupyter Notebook" command, I would expect it to use the active virtual environment, but it tries to use a different Python interpreter instead, and fails:

![image](https://user-images.githubusercontent.com/2609312/138350569-6b69ee88-4124-4b8a-85b8-df485e331a51.png)

This is in a VSCode Remote WSL session on my local machine.

### VS Code Version

Version: 1.61.2 (user setup) Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643 Date: 2021-10-19T14:57:20.575Z Electron: 13.5.1 Chrome: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.22000

### Jupyter Extension Version

v2021.9.1101343141

### Jupyter logs

```shell
N/A
```

### Coding Language and Runtime Version

CPython 3.9.5

### Language Extension Version (if applicable)

v2021.10.1365161279

### Anaconda Version (if applicable)

n/a

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
@alexkyllo are you still running into this issue?

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
