### ISSUE TITLE
split line highlight border and cell region lines #99425

### ISSUE THREAD

**Issue by jeromerg** [microsoft/vscode-jupyter#8005]
Would it be possible to re-open the issue microsoft/vscode#99425: It would be a great added-value to be able to better distinguish the cells in the python files. But currently the color used to delimit the cell is `editor.lineHighlightBorder` which highlights the line where the cursor is located in ...

**Comment by rebornix** [comment]
Please check the original issue https://github.com/microsoft/vscode/issues/99425
