### ISSUE TITLE
Creating a citable bibliography for VSCode Jupyter or make this repo citable

### ISSUE THREAD

**Issue by scaomath** [microsoft/vscode-jupyter#8007]
**Describe the feature you'd like.**
This is not really a feature. I have benefited a lot from VSCode Jupyter in my research and wanted to add the citation in the acknowledgement. However, I could not find a bibliography entry for VSCode Jupyter extension to put in acknowledgement and bibliography.

**Possible solutions**
Would you please consider make this repo citable? [https://guides.github.com/activities/citable-code/](https://guides.github.com/activities/citable-code/)

or even better a comprehensive bibtex entry like:

```bibtex
@Article{harris2020array,
 title         = {Array programming with {NumPy}},
 author        = {Charles R. Harris and K. Jarrod Millman and St{\'{e}}fan J.
                 van der Walt and Ralf Gommers and Pauli Virtanen and David
                 Cournapeau and Eric Wieser and Julian Taylor and Sebastian
                 Berg and Nathaniel J. Smith and Robert Kern and Matti Picus
                 and Stephan Hoyer and Marten H. van Kerkwijk and Matthew
                 Brett and Allan Haldane and Jaime Fern{\'{a}}ndez del
                 R{\'{i}}o and Mark Wiebe and Pearu Peterson and Pierre
                 G{\'{e}}rard-Marchant and Kevin Sheppard and Tyler Reddy and
                 Warren Weckesser and Hameer Abbasi and Christoph Gohlke and
                 Travis E. Oliphant},
 year          = {2020},
 month         = sep,
 journal       = {Nature},
 volume        = {585},
 number        = {7825},
 pages         = {357--362},
 doi           = {10.1038/s41586-020-2649-2},
 publisher     = {Springer Science and Business Media {LLC}},
 url           = {https://doi.org/10.1038/s41586-020-2649-2}
}
```

**AlternativeS**
Or a simple bib entry like
> T. A. Driscoll, N. Hale, and L. N. Trefethen, editors, Chebfun Guide, Pafnuty Publications, Oxford, 2014.

**Comment by kieferrm** [comment]
Since this is a public repo, you can reference the repo by URL.
