### ISSUE TITLE
iJavaScript Exception in cell will cause timeout

### ISSUE THREAD

**Issue by franz101** [microsoft/vscode-jupyter#8014]
## Environment data

-   VS Code version: 1.61.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1101343141
-   Python Extension version (available under the Extensions sidebar): v2021.10.1365161279
-   OS (Windows | Mac | Linux distro) and version: 11.6 (20G165) M1
-   Python and/or Anaconda version: mini-forge arm 3.9.6
-   Jupyter server running: Local

## Expected behaviour

Running [iJavaScript ](https://www.npmjs.com/package/ijavascript) with jupyter lab works without errors... When I create a duplicate variable it will run the next cell if let it run.

## Actual behaviour

<img width="1129" alt="Screenshot 2021-10-23 at 02 27 52" src="https://user-images.githubusercontent.com/18228395/138535312-165606e9-b818-4551-b938-5c7a15792d15.png">

## Steps to reproduce:

1. Install iJavaScript
2. Create an ipynb file
3. Choose iJavaScript Kernel
4. write invalid js and everything will crash

**Comment by franz101** [comment]
You are a champ, will check out the extension you mentioned. Often the problem was that the some notebooks weren't using the local tsconfig

**Comment by DonJayamanne** [comment]
I've tested this with our latest dev version of the extension and it works as expected.
I'm closing this issue as resolved. We're planning on releasing a new version this week.

Closing so as to get this validated.
