### ISSUE TITLE
Unable to render Altair plot using boxplot on repeat with mimetype

### ISSUE THREAD

**Issue by SonQBChau** [microsoft/vscode-jupyter#8016]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

#### Issue description
Jupyter in VSCode is unable to render the Altair plot. This happens when using boxplot on repeat and set the renderer to `mimetype`

#### Steps to reproduce the issue

```python
import altair as alt
from vega_datasets import data

# Show an image where the interactive plot is not supported
alt.renderers.enable('mimetype')

source = data.cars()

alt.Chart(source).mark_boxplot().encode(
    x='Origin',
    y=alt.Y(alt.repeat('column'), type='quantitative'),
).repeat(column=['Horsepower', 'Weight_in_lbs'])
```

#### What's the actual result?

```
TypeError: e.map is not a function
```

#### Additional details / screenshot

<img width="581" alt="Screen Shot 2021-10-23 at 8 23 55 PM" src="https://user-images.githubusercontent.com/12553570/138579138-3583a7f5-18c8-40e8-ba31-2d3e6246f16b.png">

### Altair Package Version

4.1.0

### VS Code Version

Version: 1.61.2 Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643 Date: 2021-10-19T15:03:09.437Z Electron: 13.5.1 Chrome: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Darwin arm64 20.6.0

### Jupyter Extension Version

v2021.9.1101343141

### Jupyter logs

```shell
TypeError: e.map is not a function
```

### Coding Language and Runtime Version

Python v3.9.7 64-bit

### Running Jupyter locally or remotely?

Local

**Comment by joelostblom** [comment]
@DonJayamanne  The docs have not been built in a while but you can see the full list in the repo:

- https://github.com/altair-viz/altair/blob/master/doc/user_guide/custom_renderers.rst
- https://github.com/altair-viz/altair/blob/master/doc/user_guide/display_frontends.rst

**Comment by DonJayamanne** [comment]
Thanks, will see what needs to be done at our end.
Hopefully just an update of the altair/vega or simiarl packages (used by us) should suffice.

**Comment by DonJayamanne** [comment]
Fixed,

**Testing instructions:**
* Install latest VS Code Insiders, Jupyter pre-release and Notebook renderers extension
* Install the following python packages
```pip install altair, vega, vega-datasets```
* Run a cell in a notebook
```python
import altair as alt
from vega_datasets import data

# Show an image where the interactive plot is not supported
alt.renderers.enable('mimetype')

source = data.cars()

alt.Chart(source).mark_boxplot().encode(
    x='Origin',
    y=alt.Y(alt.repeat('column'), type='quantitative'),
).repeat(column=['Horsepower', 'Weight_in_lbs'])
```
* Plot should appear
