### ISSUE TITLE
Fonts in variable viewer are too big

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode-jupyter#8020]
## Environment data

-   VS Code version: 1.61.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1101343141
-   Python Extension version (available under the Extensions sidebar): v2021.10.1365161279
-   OS (Windows | Mac | Linux distro) and version: macOS Big Sur 11.6
-   Python and/or Anaconda version: 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

Font family and size of the variable viewer are consistent with the overall look of VSCode.

## Actual behaviour

It has always looked out of place, big and bold, even the content of the table is larger than the panel tab titles, no to say the table headers.

![image](https://user-images.githubusercontent.com/2845433/138644987-3f34b4c4-60b3-4a7c-a5e0-e4d5e8ebb2d4.png)

## Steps to reproduce:

1. Open a notebook
2. Open the Variables view

**Comment by amunger** [comment]
font size is set to the editor default of 14px, but does not adjust with the font setting, which it probably should

**Comment by roblourens** [comment]
The variable viewer will be built-in core vscode UI https://github.com/microsoft/vscode/issues/165445
