### ISSUE TITLE
Diagnostics for input not refreshed in python interactive window when input is cleared

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#8021]
Testing microsoft/vscode#127378

1. Open native jupyter interactive window
2. Start typing a variable name that doesn't exist such as `abc`
3. Delete or execute to clear the input

**bug**
The diagnostics for the missing variable remains.

https://user-images.githubusercontent.com/12821956/124171723-c7924e00-da5d-11eb-93d6-8187d55b633e.mov

Similar issue I sometimes see: 

1. Type `abc`
2. Delete all
3. Type `def`
4. 🐛  You get an reported for `abcdef` not being defined.

**Comment by rchiodo** [comment]
This should no longer be an issue as IW diagnostics are completely ignored now.
