### ISSUE TITLE
Jupyter Notebook Tutorial

### ISSUE THREAD

**Issue by AGoh2019** [microsoft/vscode-jupyter#8029]
Issue Type: <b>Feature Request</b>

Can you provide a tutorial and video on how to use Jupyter Notebook in VS Code.  Especially when it comes to installing and configuring Anaconda 3 and the Conda library. And I would also like to know how to use chmod to give myself unrestricted privileges when using Git Bash in Windows 11.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by IanMatthewHuff** [comment]
I don't think that we should leave this open as a code issue. The best resources for this would be the tutorial videos put out by the outreach team:
https://www.youtube.com/watch?v=DA6ZAHBPF1U
https://www.youtube.com/watch?v=h1sAzPojKMg
