### ISSUE TITLE
Make the background of the jupyter variables tab respect the theme of VS Code

### ISSUE THREAD

**Issue by xiaoxi-david** [microsoft/vscode-jupyter#8030]
Currently, the background of the jupyter variables tab keeps white and doesn't respect any of the themes of VS Code.

**Comment by greazer** [comment]
Thanks for the feedback! This issue fell through the cracks for us, but as it stands we still aren't seeing the problem as originally described. Please reopen with specifics if the problem is still happening for you.

**Comment by ndgayan** [comment]
Still, I can see this.

![image](https://user-images.githubusercontent.com/1891059/166556288-ea2c3585-d2aa-4e16-a064-4ec6d9cd34e6.png)
