### ISSUE TITLE
Double `notebook` install prompt

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-jupyter#8041]
Testing #8024

When using this setting, I get the following double `notebook` installation prompt, as soon as I try to run a cell:

```
    "jupyter.disableZMQSupport": true
```

![recording (12)](https://user-images.githubusercontent.com/22350/138880175-78fd4027-b3cc-46f1-b946-6a5508b6e38b.gif)

**Comment by DonJayamanne** [comment]
Should be fixed, can no longer be reproduced
