### ISSUE TITLE
Dead remote Jupyter server detection takes too long

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-jupyter#8043]
Testing #8024

1. Follow the remote Jupyter server steps
2. Open a notebook
3. Kill `jupyter notebook`
4. Run a cell

🐛 Code should detect the Jupyter server has died... but instead the cell is left to run forever:

![recording (14)](https://user-images.githubusercontent.com/22350/138883157-593d2d43-7c9d-42f5-b830-a56f2d7ca36a.gif)

**Comment by DonJayamanne** [comment]
Should be fixed, closing for verification.
