### ISSUE TITLE
Kernel selection dialog: Provide action to open the filter list

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-jupyter#8045]
Testing #7373

Just a UI suggestion. Feel free to close if this was already discussed.

Following #8032, I installed some environments and opened a Jupyter notebook.
Clicking on the environments brings the 'Kernel change dialog'. It shows kernels to choose from.

As the kernel list can be configured by the user, it would be great to have an action right in the selection dialog that brings you there.
An additional item `Configure...` invoke the  `Filter Kernels` command.
- would make the user aware of the filter feature.
- the command `Filter Kernels` alone is hard to discover.

**Comment by DonJayamanne** [comment]
@rebornix we should remove this when adding support for the new kernel picker. basically the new ui makes the filter unnecessary, and this feature adds more work to maintain it.

**Comment by DonJayamanne** [comment]
I'm closing this issue, as the plan is to remove the kernel filter UI with the new kernel picker UI.
