### ISSUE TITLE
Can't export using nbconvert: `Export failed. Please check the 'Jupyter' output panel for further details`

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-jupyter#8050]
## Environment data

-   VS Code version:
Version: 1.62.0-insider (user setup)
Commit: dc1a6699060423b8c4d2ced736ad70195378fddf
Date: 2021-10-26T08:49:04.076Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22483
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1001384888
-   Python Extension version (available under the Extensions sidebar): v2021.10.1365161279
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: Python 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Testing https://github.com/microsoft/vscode/issues/135666

- Switch to `nbconvert` export setting (already successfully used other 2 export settings)
- ... -> Export -> Python Script
- Screenshot 3 in test plan item

## Actual behaviour

:bug: `Export failed. Please check the 'Jupyter' output panel for further details.`

![image](https://user-images.githubusercontent.com/25310137/138925018-dcac5727-2252-454a-8dff-719b69b5be48.png)

## Jupyter output panel

Logs here: [Jupyter output.txt](https://github.com/microsoft/vscode-jupyter/files/7419991/Jupyter.output.txt).

## Additional info

- I started my testing with the same exact cells pictured in the test plan item screenshots
- I tried other notebooks, and they fail with the same message
- When I try exporting with `nbconvert` setting again, it still fails each time

**Comment by IanMatthewHuff** [comment]
Validation notes:

1. You need to be in the state where you have no global jupyter interpreter set, so wipe out storage (or use a fresh VM) to repro
2. When you export with nbconvert you will still get a prompt to pick a global jupyter interpreter then the prompt to install dependencies. Maybe not ideal, but works for now to support a less important scenario.

**Comment by DonJayamanne** [comment]
Verified, but subsequent exports will never get the prompt (if i don't select an interpreter the first time).
Created separate issue for that.
