### ISSUE TITLE
nbconvert option results in duplicate IPython imports

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-jupyter#8057]
Testing #8034

With the nbconvert option:

1. Create a notebook with magics
2. Export the notebook to a Python script. The Python script starts off by importing IPython
3. Run all the cells in the Python script in order, which ends up running them in the IW
4. Export the IW contents to a new Python script
5. :bug: IPython gets imported twice

This behaviour could be by design, though.

**Comment by DonJayamanne** [comment]
Closing as will not be done, not a major issue and no one else has reported this, been 2 years, no point leaving this open
