### ISSUE TITLE
Tab Complete Greek Letters using Tex Syntax

### ISSUE THREAD

**Issue by bkaplowitz** [microsoft/vscode-jupyter#806]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description
A big QOL feature that could be added for math/science/engineering users would be to be able to tab-complete greek letters via Intellisense as found in Jupyter Labs and Julia. I imagine this wouldn't be a large technical challenge, so this would be a great feature to add.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by HenriqueCSJ** [comment]
No plans to add the feature yet? For scientists this is a great plus,
