### ISSUE TITLE
Is the kernel error being reported correct (i.e. the most useful?)

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#8060]
See the following image. The kernel (interpreter) I selected apparently is missing access to win32api.dll somehow. Yet the error reported is a much more nebulous and late-to-the-party type message: "Cannot execute code, session has been exposed". 

I think we have code to try and display to the user a better error message when a kernel can't be started, but are we getting the right one? 

![image](https://user-images.githubusercontent.com/11685408/138959031-bfb05142-f3c9-43a8-8faa-c7dd2ea3d20d.png)

**Comment by DonJayamanne** [comment]
**Testing:**

* Create a notebook with at least 3 cells (1 & 3 containing print statements)
	* Second cell should have the following code
```python
import IPython
app = IPython.Application.instance()
app.kernel.do_shutdown(True)
``` 
	* An error message should also be displayed indicating the kernel died (bottom right)
	* Try to run another cell or the same cell in the notebook
	* You should be presented with a modal message indicating the kernel is dead with the option to restart the kernel

* Create a notebook with the following code:
```python
import os
os.getpid()
``` 
	* Using this PID kill this process from the task manager or terminal
	* An error message should also be displayed indicating the kernel died (bottom right)
	* Try to run another cell or the same cell in the notebook
	* You should be presented with a modal message indicating the kernel is dead with the option to restart the kernel
