### ISSUE TITLE
Conflicting error report for identical lines.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#8062]
The !pip install line is flagged as an error if indented. Otherwise it's ignored. 

![image](https://user-images.githubusercontent.com/11685408/138963555-eacfc6c4-9894-4538-9731-03e388244bdc.png)

**Comment by DonJayamanne** [comment]
Been a while since this was reported and no one else seems to have run into this in the mean time
, closing this issue for now (as this was reported internally)
