### ISSUE TITLE
Make sure 'nbconvert' export options correctly install nb convert

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#8071]
Follow up to https://github.com/microsoft/vscode-jupyter/issues/5222.

The fix for #5222 ended up being adding a new way to export to python script without using nbconvert at all. However there is still an option for 'nbconvert' that customers can select for script export. And in that case we still don't have the right install prompt here. Most customers should be ok now as the export path doesn't require nbconvert, but we should still fix the underlying nbconvert install prompt issue.

**Comment by DonJayamanne** [comment]
Works for the first time. Created a seprate issue to track subsequent attempts
