### ISSUE TITLE
Test to validate telemetry is coming out as expected

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8078]
First idea:
- Generate log of telemetry for set of events
- Save log to repo
- Write test that runs same code. Compare telemetry output

**Comment by rchiodo** [comment]
After some discussion with the telemetry V-team, the thought was that teams should have telemetry tests for major user actions. Like opening a notebook, running a cell, interrupting a cell etc. And that the telemetry events for those big actions (at least non DS_INTERNAL events) should never change.

This test should validate those scenarios.

**Comment by greazer** [comment]
Not sure why I asssigned this to myself. Unassigning. :)

**Comment by DonJayamanne** [comment]
Closing for now. If telemetry isn't coming out and not seen, then either telemetry isn't used, hence makes one wonder why telemetry was added in the first place.
