### ISSUE TITLE
Pip module Unable to parse debugpy output

### ISSUE THREAD

**Issue by sambathraj** [microsoft/vscode-jupyter#8079]
## Environment data

-   VS Code version: Version: 1.61.2 (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): 2021.9.1101343141
-   Python Extension version (available under the Extensions sidebar): v2021.10.1365161279
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: 3.8.9
-   Type of virtual environment used : venv 
-   Jupyter server running: Local

## Expected behavior
Should be able to debug the cell. 

## Actual behavior
Pip module Unable to parse debugpy output, please log an issue with https://github.com/microsoft/vscode-jupyter is required for debugging cells. You will need to install it to debug cells.

## Steps to reproduce:
1) Follow the instructions at https://docs.microsoft.com/en-us/azure/synapse-analytics/spark/vscode-tool-synapse to install the support for Azure Synapse. 
2) Copy paste below code
`
#%%
import sys
from operator import add
from pyspark.sql import SparkSession, Row
spark = SparkSession.builder.appName("PythonWordCount").getOrCreate()
3) Click on Debug cell
4) Change the Kernebl to Synapse Pyspark. 
5) Wait for connection to be established. 
6) Click on debug cell. 
![Screenshot 2021-10-27 165223](https://user-images.githubusercontent.com/6494636/139163574-e2e8fbd3-c6ff-4159-ab4f-402bfda89bbd.png)`
`

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Comment by aayushagrawal135** [comment]
[debugpy_output.log](https://github.com/microsoft/vscode-jupyter/files/10169650/debugpy_output.log)

I am facing the same issue. Please find the requested output logs here.

**Comment by austinzh** [comment]
I downgrade debugpy==1.5.0(not sure other version will work or not) but 1.6.7 does not work for me

**Comment by collinmccarthy** [comment]
Same issue, my solution was to `pip uninstall typing` from [this SO post](https://stackoverflow.com/questions/74740776/debugging-jupyter-cells-fails-with-pip-module-unable-to-parse-debugpy-output/74740836#74740836)
