### ISSUE TITLE
Notebooks - Intellisense not helpful if using . to select pandas df column

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#8080]
If i use the . to select a column in a pandas dataframe and then use . again to apply some function to it, the intellisense pop up is not helpful as it does not show the function in full 

![image](https://user-images.githubusercontent.com/19276747/139167741-b264108a-e9f8-4626-9e3b-d8aa28ca8dff.png)

Compared to using the [ ] to select a column 
![image](https://user-images.githubusercontent.com/19276747/139168085-9bb2beb2-a97e-4359-83ec-330adc3dd828.png)

**Comment by rchiodo** [comment]
This is the label from Jupyter being super long. Going to change this anyway to not be so long. That change will fix this bug.

**Comment by rchiodo** [comment]
Repro steps:
- Clone https://github.com/claudiaregio/data-science.git
- Create conda environment using the 'golden_scenario_env.yml'
- Open in VS code
- Open titanic.ipynb
- Switch to the golden_scenario kernel
- Run the first two cells
- Create a new cell
- type in ```titanic_df.``` and wait a bit (jupyter provides column names so might have to wait a bit)
- if you get ```Embarked``` in the autocomplete, hit tab and then ```.``` again
- verify the auto complete is only the next word, and doesn't have ```titanic.Embarked.``` embedded in it.

**Comment by rchiodo** [comment]
Should look something like so:

![image](https://user-images.githubusercontent.com/19672699/144643446-788e75e3-1610-4486-b913-365d0c16a613.png)

**Comment by IanMatthewHuff** [comment]
Looks good.
![image](https://user-images.githubusercontent.com/812783/144680974-3de964d8-42a6-436e-8c15-d8021a6fc53d.png)
