### ISSUE TITLE
FileUpload ipywidget returns empty dict

### ISSUE THREAD

**Issue by vidsaat** [microsoft/vscode-jupyter#8084]
## Environment data

-   VS Code version: 1.61.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1101343141
-   Python Extension version (available under the Extensions sidebar): v2021.10.1365161279
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04.3 LTS
-   Python and/or Anaconda version: Python 3.8.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Jupyter server running: Local 

## Expected behaviour

After choosing a file to upload the next ran cell should return the uploaded file.

## Actual behaviour

The upload widget still returns an empty dict after the upload.

## Steps to reproduce:

1. 
```
import ipywidgets as widgets
uploader = widgets.FileUpload()
```

2. 
```
uploader.value.values()
```
returns: dict_values([])

3. 
```
display(uploader)
```
returns: visual uploader button
action: choose file and upload

4.
```
uploader.value.values()
```
returns: dict_values([])
expected return: dict_values([{'metadata': {'name': '.........}}])

**Comment by matifrancois** [comment]
Having the same problem here, it doesn't work in vscode but it works in Jupyter notebook classic.

**Comment by dd-rrc-ps** [comment]
Same problem here. It should be greate if VScode support this function

**Comment by JosephAntony1** [comment]
Any luck on this?

**Comment by DonJayamanne** [comment]
@matifrancois @dd-rrc-ps @JosephAntony1 
I've tested this at my end and it seems to work as expected. Please could you test this again and let me know if it works or not.

**Comment by JosephAntony1** [comment]
It worked for me once I started changing the jupyrer config kernel size from 10mb to something more like 1gb

**Comment by DonJayamanne** [comment]
> config kernel size from 10mb to something more like 1gb

Please could you let me know what that setting is.
Thanks

**Comment by JosephAntony1** [comment]
https://github.com/jupyter-widgets/ipywidgets/issues/2522#issuecomment-516434947

This is where I got the information from

**Comment by DonJayamanne** [comment]
Thanks, going to close this issue as fixed.

**Comment by datalifenyc** [comment]
> Thanks, going to close this issue as fixed.
> # Solution
> 
> ensure to increase the max message size as mentioned here [jupyter-widgets/ipywidgets#2522 (comment)](https://github.com/jupyter-widgets/ipywidgets/issues/2522#issuecomment-516434947)
> 
> ```
> c.NotebookApp.tornado_settings = {"websocket_max_message_size": 100 * 1024 * 1024}
> ```

How do we point Visual Studio Code to the created jupyter_notebook_config.py?

**Comment by datalifenyc** [comment]
In VS Code, there is one additional line to include:

```python
import ipywidgets as widgets
uploader = widgets.FileUpload()
display(uploader)
```
Then click on the `Upload(0)` button. The __Open__ dialog window will appear.

**Comment by datalifenyc** [comment]
> Thanks, going to close this issue as fixed.
> # Solution
> 
> ensure to increase the max message size as mentioned here [jupyter-widgets/ipywidgets#2522 (comment)](https://github.com/jupyter-widgets/ipywidgets/issues/2522#issuecomment-516434947)
> 
> ```
> c.NotebookApp.tornado_settings = {"websocket_max_message_size": 100 * 1024 * 1024}
> ```

How do you point Visual Studio Code to the `jupyter_notebook_config.py` or `jupyter_notebook_config.json` file?

**Comment by ubalklen** [comment]
@datalifenyc have you figured out? I have the same question.
Also summoning master wizard @JosephAntony1 to check if he can help us :-)

**Comment by epicwhale** [comment]
Has anyone figured how do you change that websocket_max_message_size for the VS Code Python kernel I am using here? I am confused how to link up the jupyter notebook config with VS code too...

**Comment by wrogner** [comment]
Wow, 555 days since this issue was reported.

Cudos to MS for taking so much time and effort to produce a working and stable product (stable it is).
