### ISSUE TITLE
Can't hover over error in interactive window

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#8089]
Issue Type: <b>Bug</b>

1. Open Jupyter interactive window
1. Type `noSuchSymbol`
1. See a yellow squiggly
2. Try hovering over this squiggly to see the error

**Bug**
Nothing happens

I can view this error in the problems view, but it is frustrating that I can't view it with hover while writing code

VS Code version: Code - Insiders 1.61.0-insider (Universal) (71ca6e8e74591ae5c577d52a2aa1bd0c3df5ac32, 2021-10-05T01:23:40.704Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (4.83GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsqsis300:30374797
vsaa593cf:30376535

```

</details>

**Comment by rchiodo** [comment]
This should be resolved now. 

Diagnostics are turned off in the interactive window for now. Navigating to them didn't work and it seemed silly to have them because the code would have run. If the code runs, why would there be a diagnostic?

**Comment by rchiodo** [comment]
Should have been addressed with this commit
https://github.com/microsoft/vscode-jupyter/commit/ff8acb2067eb8cb2b04cb0a895274b2ba2214a63

**Comment by IanMatthewHuff** [comment]
Verified. At least per the last comment that diagnostics are now turned off in the interactive window input box. 

@rchiodo is that the solution we want here? You can type longer stuff in the input box. If I'm doing "import X" and X isn't in the environment I think I would expect and appreciate a squiggle here in general.

**Comment by rchiodo** [comment]
Longer term I think we'd want diagnostics in just the input box. That was more work so I left it for later.

**Comment by rchiodo** [comment]
Added this issue:
https://github.com/microsoft/vscode-jupyter/issues/8448
