### ISSUE TITLE
Unable to interrupt non-python kernels

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8107]

**Comment by DonJayamanne** [comment]
**Testing**

* Julia (on linux/mac)
	* Create a julia notebook and select the Julia Jupyter kernel
``` julia
function estimate_pi(n)
    s = 1.0
    for i in 1:n
		sleep(1)
        s += (isodd(i) ? -1 : 1) / (2i + 1)
    end
    4s
end

p = estimate_pi(100_000_000)
println("π ≈ $p")
println("Error is $(p - π)")
``` 
	* Run this cell and try to interrupt
	* Be patient sometimes it takes a few tries (i think because Julia process is busy or the like)
	* The same flaky ness can be experienced in Jupyter as well.

**Comment by rchiodo** [comment]
/verified? Doesn't work for me but I see it sending the interrupt requests.
