### ISSUE TITLE
Can't show multiple prints on the same line in Python

### ISSUE THREAD

**Issue by chuongmep** [microsoft/vscode-jupyter#8112]
## Environment data

-   VS Code version: 1.61.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1101343141
-   Python Extension version (available under the Extensions sidebar): v2021.10.1365161279
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv 
-   Jupyter server running: Local 

## Expected behaviour

![image](https://user-images.githubusercontent.com/31106432/139571545-c7c9de47-a1ed-4f36-969f-3aa40540a589.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/31106432/139571523-950292bd-ac01-4c72-bd66-7e0103ab9da5.png)

Code Sample : 
``` py
import time 
for i in range(10):
    s = str(i) + "%"
    print("{0}\r".format(s),end="")
    time.sleep(0.2)
```

**Comment by DonJayamanne** [comment]
* Please could you provide the Jupyter and Outlook extension versions * please could you provide the output from the Jupyter output panel

**Comment by IanMatthewHuff** [comment]
Verified, looks good now.
![image](https://user-images.githubusercontent.com/812783/144321290-3e6e3b31-f19b-4316-b049-ba7c53cd7ce2.png)

**Comment by chuongmep** [comment]
I checked in version v2021.10.1101450599
It was still not working, it is a mistake or need waiting for update ? 
![image](https://user-images.githubusercontent.com/31106432/144338991-7c8e267e-c58f-409f-bdaa-da423f1404ab.png)

**Comment by DonJayamanne** [comment]
Please try vscode insiders. You'll get 2021.11.xxxx

**Comment by chuongmep** [comment]
How to install insider ? 
![image](https://user-images.githubusercontent.com/31106432/144339411-4f5db745-ece9-4d36-9179-e2918f55a1f6.png)

**Comment by chuongmep** [comment]
Thank you, it's working now.
![Uploading image.png…]()
