### ISSUE TITLE
Python interactive and VS Code window reload

### ISSUE THREAD

**Issue by svintuss** [microsoft/vscode-jupyter#8116]
Hello. 

I'm using VS Code with SSH conection to remote server and mostly use .py files and Python Interactive window. 
However, sometimes VS Code can't re-establish SSH connection and I have no option but to press "Reload VS Code window". After that Python Interactive is gone with all the work in it and I have to start from scratch. 

Is there a way to revive Python Interactive window after reloading VS Code Window?

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
Currently this isn't possible, however there's an issue that would make this possible https://github.com/microsoft/vscode-jupyter/issues/1516
Please do upvote that.
