### ISSUE TITLE
Add a plots tab on interactive mode

### ISSUE THREAD

**Issue by enajx** [microsoft/vscode-jupyter#8117]
Similarly to the 'variables' tab, it's be useful to have a 'plots' tab where the generated plots from each interactive notebook session could easily be accessed. This feature is implemented in Spyder and Pycharm scientific view mode. This feature, along with a better designed for the variable explorer, would make VScode much better suited for data analysis workflows.

[Example of how plots tab looks on Spyder IDE](https://docs.spyder-ide.org/5/panes/plots.html)
[Example of how plots tab looks on Pycharm IDE](https://www.jetbrains.com/help/pycharm/matplotlib-support.html#data)

**Comment by DonJayamanne** [comment]
Thanks for this suggestion, 
Today you can open plots in the plot viewer. Just hover over the image and you'll get a toolbar that'll allow you to either save or open the plot in a plotviewer.

**Comment by enajx** [comment]
A solution similar to that but compatible with interactive plots (%matplotlib widget) and where only the actual figures are shown -in the current implementation, using your suggestion, figures are plotted on a big blank space- would be fantastic.

**Comment by DonJayamanne** [comment]
What your area looking for is in here https://github.com/microsoft/vscode-jupyter/issues/5532

Please up vote that issue, the issue adds super for widgets (interactive plots) to be displayed outside a notebook.
Closing as a duplicate

**Comment by enajx** [comment]
Not quite, as indicated on the original post, the suggestion is to have a tab -similar to variables- where plots for the interactive notebook session plots are displayed.
