### ISSUE TITLE
Failure to activate conda env results in failure to detect if ipykernel is installed

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8119]
Initially reported by Rong.
Basically activation of conda environments fails, hence we cannot launch conda properly.

**Comment by DonJayamanne** [comment]
Jim too is running into this.
**Summary:**
* The process to get env variables seems to be timing out, and the process is terminated hence the SIGTERM error
* When using `conda run` we run into the exact same issue

**Comment by DonJayamanne** [comment]
Possible solutions here https://github.com/microsoft/vscode-jupyter/issues/6694

**Comment by DonJayamanne** [comment]
Timeout increased in Python extesnion

**Comment by rchiodo** [comment]
@greazer can you verify this works?
