### ISSUE TITLE
Track import and possibly other 'errors' as kernel crashes

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8122]
Customers hit import problems and blame VS code for them (seen this from customer feedback).

I believe we don't have telemetry that tracks user errors over time (or the type). I believe we only track failures that cause a kernel to actually crash.

**Comment by DonJayamanne** [comment]
> seen this from customer feedback

Which one

**Comment by rchiodo** [comment]
Multiple anecdotes in standup this morning from customers. Paige and Jim pointing out feedback from Data scientists.

**Comment by DonJayamanne** [comment]
Closing this for now as this will be a little difficult to implement and I believe we have improved our handling or kernel failures.
