### ISSUE TITLE
Hope the Interactive window can jump to the cell automatically

### ISSUE THREAD

**Issue by Vincent0706** [microsoft/vscode-jupyter#8124]
I hope the Interactive window can jump to the corresponding unit automatically when I run a code cell.
Always when I run a code cell, the Interactive window don't jump to the corresponding unit. And it always stay on the unit that I just watch.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
Today when you run a cell against the interactive window, the output is scrolled automatically.
Please could you provide the following information:
* Version of Python
* Version of Jupyter extnsion
* Version of VS COde
* OS

Please could you take a screen recording of the issue and share the screen recording, you can use [gifcap.dev](http://gifcap.dev/) (won't need to install anything)

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
