### ISSUE TITLE
Interactive Window to jupyter notebook file leads to wrong indentation

### ISSUE THREAD

**Issue by MaxiTrien** [microsoft/vscode-jupyter#8138]
- VS Code Version: 1.61.2
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Load a jupyter notebook 
2. Convert it into python script for debugging
3. After changes running the cells in the interactive window safe everything in another notebook

Changes run in the interactive window:

![image](https://user-images.githubusercontent.com/51158324/139587713-860a1b93-36d0-42b8-ad32-50858719826b.png)

Collaped tabs 
![image](https://user-images.githubusercontent.com/51158324/139587787-77b5b058-4e80-4b46-99b0-44bf4c8abe3c.png)

Thanks for you help!

**Comment by rchiodo** [comment]
Thanks for the bug. Export to notebook seems to be erasing tabs.

**Comment by IanMatthewHuff** [comment]
@MaxiTrien I've been playing with this now and currently I'm unable to repro this. Just to confirm the scenario is as follows?

1. Open up an ipynb file with indentation in some cells (indentation looks correct)
2. Use the Export to Python to convert that notebook to a .py file with cell markers
3. Run that file in the interactive window (indentation looks correct)
4. Use the "save" button in the interactive window to convert back to a .ipynb file
5. In the ipynb file the indentation has been lost

Following the scenario above I'm still seeing the correct indentation. 
![image](https://user-images.githubusercontent.com/812783/141004483-08391acc-8b86-48ed-83ad-9b49f17e1d8d.png)
In the example above I went (Left to Right) from ipynb => python script => interactive window => save interactive window as notebook.

Are you still seeing this issue (we did just push a new stable release recently) if you are, do you perhaps have any specific settings around indentation? I tried with both tabs and spaces and wasn't seeing an issue either way.

**Comment by MaxiTrien** [comment]
@IanMatthewHuff  Thanks for the follow up! The current update seems to fix it.
