### ISSUE TITLE
matplotlib.animation.FuncAnimation does not work in Notebook

### ISSUE THREAD

**Issue by vict0rsch** [microsoft/vscode-jupyter#8149]
Issue Type: <b>Bug</b>

# Behaviour

with `%matplotlib notebook` animations (`matplotlib.animation.FuncAnimation`) don't show up. Actually, not even the first `show`. With `%matplotlib inline`, as expected, the first `show` is displayed but not the subsequent animation

## Expected vs. Actual Behaviour

The code ([matplotlib example](https://matplotlib.org/stable/gallery/animation/simple_anim.html)) works on a regular web-based notebook but fails in VSCode's notebooks

## Steps to reproduce:

Cell 1:

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

%matplotlib notebook
```

Cell 2:

```python
fig, ax = plt.subplots()

x = np.arange(0, 2*np.pi, 0.01)
line, = ax.plot(x, np.sin(x))


def animate(i):
    line.set_ydata(np.sin(x + i / 50))  # update the data.
    return line,


ani = animation.FuncAnimation(
    fig, animate, interval=20, blit=True, save_count=50)

# To save the animation, use e.g.
#
# ani.save("movie.mp4")
#
# or
#
# writer = animation.FFMpegWriter(
#     fps=15, metadata=dict(artist='Me'), bitrate=1800)
# ani.save("movie.mp4", writer=writer)

plt.show()
```

![2021-11-02 18 17 05](https://user-images.githubusercontent.com/9283470/139959496-939f11fc-cba2-4dce-b97f-2f5bdcb59e2e.gif)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.2
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): virt-conda
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: true
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

analysis
• completeFunctionParens: false
• autoImportCompletions: true
• autoSearchPaths: "<placeholder>"
• stubPath: "<placeholder>"
• diagnosticMode: "openFilesOnly"
• extraPaths: "<placeholder>"
• useLibraryCodeForTypes: true
• typeCheckingMode: "off"
• errors: []
• warnings: []
• information: []
• disabled: []
• typeshedPaths: "<placeholder>"
• cacheFolderPath: "<placeholder>"
• memory: {"keepLibraryAst":true,"keepLibraryLocalVariables":true}
• logLevel: "Trace"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "black"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

autoComplete
• addBrackets: false
• extraPaths: "<placeholder>"
• showAdvancedMembers: true
• typeshedPaths: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: false
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

insidersChannel: "off"

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2021.10.1365161279
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No
Remote OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.71GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: cn-c010.server.mila.quebec|
|OS|Linux x64 4.15.0-45-generic|
|CPUs|AMD EPYC 7502 32-Core Processor (128 x 3343)|
|Memory (System)|377.75GB (298.39GB free)|
|VM|0%|
</details>

**Comment by rchiodo** [comment]
Thanks for the bug.

```
%matplotlib notebook
```
Actually only works in jupyter notebook.

The more generic

```
%matplotlib widget
```
works in VS code.
![matplotlibwidget](https://user-images.githubusercontent.com/19672699/140096078-1f3150b2-c967-417a-a5d4-474da116b5b2.gif)
