### ISSUE TITLE
moving jupyter variables panel to right makes it empty

### ISSUE THREAD

**Issue by SnippetsTeam** [microsoft/vscode-jupyter#8150]
## Environment data

-   VS Code version: 1.61.2
-   Jupyter Extension version: v2021.9.110134314
-   Python Extension version: v2021.10.1365161279
-   OS: Windows 10
-   Python and/or Anaconda version: python 3.9.7 / conda 4.10.3 / anaconda Command line client (version 1.7.2)
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Expected behaviour

Moving jupyter variables panel to right does not affect the content

## Actual behaviour
Moving variables panel to right makes all variables to disappear and the only way to get them back is close and open VScode again.

## Steps to reproduce:

1. Open a New empty jupyter notebook
2. load any CSV using pandas
3. Click on "variables" and see all variables in a panel.
4. Move panel to right
5. Variables panel get empty and reverting back to bottom does not solve it. Restarting kernel does not solve it either.
![bug](https://user-images.githubusercontent.com/87364140/140076968-d3e78548-6572-4930-8018-96da117a1c69.gif)

**Comment by rchiodo** [comment]
Thanks for the bug. I believe this is a VS code issue which should be solved in the next release. If you use [VS code insiders](https://code.visualstudio.com/insiders/), it should not repro there.
