### ISSUE TITLE
can't reconnect to remote jupyter server without UI reload

### ISSUE THREAD

**Issue by zpincus** [microsoft/vscode-jupyter#8159]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. Start up a jupyter server with some fixed token or password URL, e.g. run `jupyter notebook --no-browser --NotebookApp.token='12345'`
2. Configure a workspace to connect to that remote server (e.g. `http://localhost:8888/?token=12345`) and open or create some notebook files.
3. Close the workspace.
2. Cause something to happen such that the remote server is not accessible (e.g. kill it, or disconnect from the network if the server is truly on a remote machine).
3. Reopen the workspace. (Or just force a UI reload to simulate the close/reopen.)
4. Note that none of the "run" buttons are available in the notebook UI because (obviously) the jupyter server is not available.
5. Restart the jupyter server, as one would do in such a case.
6. "Run" buttons remain greyed-out in the notebook UI.
7. Try to force a reconnect to the now-running server by bringing up the "pick how to connect to jupyter" palette and either selecting the current URL from the "recents" list, or selecting "existing" and re-entering the current URL.
8. Nothing happens! (I assume vscode doesn't do anything because it assumes selecting a server URL that it is "already" connected to should be a no-op, without noting that there is actually no active connection.) *Expected outcome*: this would cause vscode to try to reconnect to the now-restored jupyter server.
9. The only way to reconnect to the jupyter server is to reload the UI or close and reopen the workspace.

### VS Code Version

Version: 1.61.2 (Universal) Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643 Date: 2021-10-19T15:49:28.381Z (2 wks ago) Electron: 13.5.1 Chrome: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Darwin x64 20.6.0

### Jupyter Extension Version

v2021.9.1101343141

### Coding Language and Runtime Version

Python, though I don't imagine it matters?

### Running Jupyter locally or remotely?

Remote

**Comment by zpincus** [comment]
Related to #7796.

**Comment by IanMatthewHuff** [comment]
@zpincus Thanks for the detailed report here. You are correct that we are not detecting the remote server being back up.

**Comment by zpincus** [comment]
Thanks!

FWIW, while it would be great if vscode automatically detects when a previously-disconnected remote server is back up, the least to address this issue would just be for vscode to allow a manual reconnect without reloading the whole UI.

Right now, it seems like trying to re-connect to the same server is a no-op (which makes sense in the general case); perhaps that could not be a no-op in the case where vscode also knows the server was unresponsive previously (and is thus e.g. not showing the "run cell" buttons)...

**Comment by DonJayamanne** [comment]
@zpincus 
Please could you test the latest version of the Jupyter extension and let us know if this works as expected.

**Comment by zpincus** [comment]
Yeah, it's much better-behaved now! Very helpful errors and everything.
