### ISSUE TITLE
Remote Jupyter development using VSCode: notebook shuts down when ssh connection is closed

### ISSUE THREAD

**Issue by mjbeyeler** [microsoft/vscode-jupyter#8176]
## Environment data

-   VS Code version: latest
-   Jupyter Extension version (available under the Extensions sidebar): latest
-   Python Extension version (available under the Extensions sidebar): latest
-   OS (Windows | Mac | Linux distro) and version: Ubuntu18 and macOS 11
-   Python and/or Anaconda version: 3.6.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Remote

## Expected behaviour

One of the key advantages of Jupyter servers is that I can keep them running, without having to run the entire notebook every day as I start working. It would be nice if that extends to remote (SSH) Jupyter development.

## Actual behaviour

Unfortunately, shutting down the SSH connection also shuts down the Jupyter server embedded within VSCode.

Is there an easy way to prevent this from happening, hence to comfortably continue where one left off as one opens a new SSH session?

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Start a notebook, and define some variables. Display the variables in cell 2.
2. Close SSH connection, and restart a new one.
3. Try running cell 2 without cell2.
4. This will display the error that there are no defined variables...

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by mjbeyeler** [comment]
Maybe this should be rather a feature request rather than a bug report as this is expected behavior when working with ssh. There should be a feature to disown all the processes that are spawned on the server by VSCode when it connects to the server. via SSH.

**Comment by rchiodo** [comment]
There's actually a feature request to allow the user to control kernel lifetimes: https://github.com/microsoft/vscode-jupyter/issues/1378. That should handle your request I think.
