### ISSUE TITLE
IPyWidgets do not work when connecting to existing remote Jupyter Kernels

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8179]
Reported by https://github.com/zpincus
https://github.com/microsoft/vscode-jupyter/issues/8085#issuecomment-961711194

Unfortunately, even with the new changes in Jupyter extension version 2021.10.100, this bug in fact does still affect reconnecting to existing sessions on a remote server.

That is, connecting to a *new* kernel (and creating a session on the remote server) now no longer breaks ipywidgets, but when re-connecting to an existing session, widgets are still broken.

The easiest steps to reproduce this are:
1. Switch to remote jupyter.
2. Make two cells like so:
```
import ipywidgets
```
```
ipywidgets.IntSlider()
```
3. Run all cells; note that the slider appears.
4. Close notebook and reopen, or just reload the UI via the "reload" command.
5. Due to #7610 you are actually now in a new session (you can verify by trying to run cell 2 and getting an `NameError`).
6. Click on the "select kernel" button in the vscode UI, and select the existing session (which is the one created in step 3).
7. Run just the second cell again. No `NameError`, but no slider either.

If you then go to the kernel picker and create a kernel session, you can run both cells and the slider reappears. But again connecting back to the existing session, the slider will not appear and ipywidgets remains broken.

@IanMatthewHuff would you prefer I create a new issue for this part of the bug, or just keep it all in this issue?

**Comment by zpincus** [comment]
Also per #8085,  I can confirm that on v2021.10.1001414422 of the Jupyter extension `ipywidgets` continue to work when changing kernels on a local server (which starts a new kernel every time). Moreover, things also work on remote servers when starting up new kernels. The _only_ breakage I note now is when connecting to an existing kernel on remote servers.

**Comment by DonJayamanne** [comment]
@zpincus I've tested ipywidgets when connecting to remote kernels in the past 2 releases & I coulnd't get it to work.
I.e. its never worked, looking at the code, we've never supported this functionality.

However I've managed to fix this fairly easily (PR submitted).

**Comment by zpincus** [comment]
Thanks a ton! This is a big improvement.

FWIW, as far as I recall `ipywidgets` have worked on remote, but only in the context of a new session that vscode just started up on the remote server. I agree that widgets have definitely never worked in my recollection after reconnecting to an existing session; thanks for adding that.

**Comment by DonJayamanne** [comment]
Fixed and it will be in the next insiders, we'll (team) discuss next week during our triage meeting whether to ship this as part of the recovery release or not (since its not a regression, its unlikely to ship as part of the recovery release).

Closing as this issue has been resolved,

**Comment by DonJayamanne** [comment]
Testing steps:
* Start jupyter server outside VS Code
* Create a jupyter notebook and run a python cell such as `print(1234)`
* Copy the URL
* Start VS Code and connect to the above jupyter URl (as though we were connecting to a remote server)
* Create a new notebook document in VS Code
* Select the existing kernel (pointing to the document created in Jupyter) 
* Add the following cell & confirm widgets work
```python
import ipywidgets
ipywidgets.IntSlider()
```
