### ISSUE TITLE
Remove obsolete welcome message on opening ipynb

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#8189]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

This notification had it's reasons for existing at one point, but now at minimum needs to be updated. But on reviewing and thinking about what to say, I felt that it wasn't necessary to keep at all. The information it provides is already part of the Jupyter extension marketplace readme. I'm not aware of other extensions that advertise themselves with a notification after they are installed. :)

### VS Code Version

1.63.0-insiders

### Jupyter Extension Version

xxx

**Comment by tanhakabir** [comment]
Verification steps?
