### ISSUE TITLE
Kernel/Interpreter discovery unit tests fail when run on windows

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8197]
We have some crucial tests related to interpreter/kernel discovery and these tests fail on windows.

**Comment by rchiodo** [comment]
Perhaps you need to run npm run clean?

They work for me:

![image](https://user-images.githubusercontent.com/19672699/140589571-461fbbbe-ea2a-4f7c-9d53-f51d6290c355.png)
