### ISSUE TITLE
Collapse Cell Input Code By Default - Not working (regression)

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode-jupyter#8199]
## Environment data

-   VS Code version: 1.63.0-insider
-   Jupyter Extension version: v2021.10.1001414422
-   Python Extension version: v2021.12.1422279751-dev
-   OS (Windows | Mac | Linux distro) and version: OSX 12.0
-   Python and/or Anaconda version: 3.9.7
-   Type of virtual environment used: poetry
-   Jupyter server running: Local

## Expected behaviour

- Native Interactive Window cell input collapsed by default as per setting `Jupyter: Collapse Cell Input Code By Default`

IW gets unusable very quickly when working in py files where you need to run a lot of long cells repeatedly.

## Actual behaviour
- Cell input is no longer collapsed when run from a .py file (recent regression, ~last week or so)
- Cell input is not collapsed when run from IW code entry cell (hasn't been since move to native interactive, but would be very nice to have!)

## Steps to reproduce:
1. run code from .py file
2. cell input not collapsed

**Comment by jaymegordo** [comment]
Oh I also mentioned part 2 of this (about the IW only) in [Microsoft/vscode#130713](https://github.com/microsoft/vscode/issues/130713)

**Comment by jaymegordo** [comment]
Also the commands `Jupyter: Collapse All Interactive Cells` and `Jupyter: Expand All Interactive Cells` don't seem to be working currently, when run by either the command palette, or the buttons in the IW.

<img width="726" alt="jupyter_collapse_cells" src="https://user-images.githubusercontent.com/29611875/140799632-bc7aba7d-c398-4f10-bf3e-d8a9dbfd1384.png">

**Comment by greazer** [comment]
Duping against https://github.com/microsoft/vscode-jupyter/issues/8203 as there is traction there already. There was a recent general update surrounding saving and restoring collapse state in notebooks altogether. More than likely this change may have had unexpected consequences.
