### ISSUE TITLE
Interactive Window not collapsing cells by default

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#8203]
### Applies To

- [ ] Notebooks (.ipynb files)
- [x] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When I execute a cell in the interactive window it should be collapsed by default. It isn't.

![image](https://user-images.githubusercontent.com/11685408/140782102-ab835f62-3a1d-41f7-8135-d65229a10f36.png)

### VS Code Version

Version: 1.63.0-insider (user setup) Commit: a7104f13ff61bcd9f4c827d8fe3c0d27bb479fd8 Date: 2021-11-08T05:14:49.440Z Electron: 13.5.1 Chrome: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.22494

### Jupyter Extension Version

v2021.10.1001414422

**Comment by rebornix** [comment]
@roblourens what's the recommended way to update the collapse state now?

**Comment by roblourens** [comment]
Set `isInputCollapsed` on the viewmodel. Where does the interactive window try to do this?

**Comment by jaymegordo** [comment]
@greazer not being able to collapse cells is KILLING me haha, hoping u guys have time to get this woking again shortly!

Thanks for everything though, the interactive window is unreal and I'm so appreciative of everything you all do xoxoxo 🙏🏻🙏🏻🙏🏻❤️❤️❤️

**Comment by roblourens** [comment]
I implemented this using a command after the cell is added, but then there is a flicker where the cell is initially rendered expanded, then we run the command to collapse it by index.

It seems like we just need some way to set the collapse state at the same time as the cell is created.

We could have some extra properties outside of `metadata` for this. Or we could just keep something in metadata like `inputInitallyCollapsed` which is read once and not updated. Do you have any other ideas @rebornix?

**Comment by roblourens** [comment]
I guess I would propose adding something like this to `NotebookCellData`

```
initialViewProperties?: {
	inputCollapsed?: boolean;
	outputCollapsed?: boolean;
};
```

**Comment by moritzwilksch** [comment]
Hey everyone, 
I just update to 1.63.0 and now I'm facing the same issue on mac. It only started right after the VSCode update, the previous version was working fine for me.

**Comment by michaelschwier** [comment]
Can you advice which version to use that does not have this bug? Being able to separate code cells and their output in different windows was the key feature I was using and this makes it extremely cumbersome to work now. I went to v2021.8.2041215044 which has the bug already.

**Comment by keithyipkw** [comment]
1.62.3 works for me. I downgraded my VS Code using the steps below

1. Changed the update mode to manual. See https://stackoverflow.com/a/49347158 for the details.
1. Installed the 1.62.3 from https://code.visualstudio.com/updates/v1_62
1. Opened VS Code.
1. Juypter became broken.
1. Opened Help -> Toggle Developer Tools
1. In the console, there was an error message "extension is not compatible" but the names of the extensions were not mentioned.
1. Reinstalled the extension Python. "Install Another Version..." did not work as it gave infinite GET 404.
1. Used "Install Another Version..." to downgrade the extension Juypter to v2021.10.1101450599.

**Comment by rebornix** [comment]
As we discussed offline, another option is keeping this still as a view state but introduce a setting for the Interactive Window in specific to archive the same experience: expand cell input if the request is from the input box, collapse for all other cases (requested by extensions).

**Comment by fang6100146** [comment]
I have encountered the same bugs when the VSCode and Jupyter are updated to the latest version. “Collapse cell input code by default” is enabled, but it still expanded the cell inputs when I click "run current file in the IW" automatically.

**Comment by roblourens** [comment]
This will be fixed in the next VS Code Insiders build

**Comment by StevenLi-DS** [comment]
@greazer Why the status texts became so huge as well as markdown texts... is it a bug or by design?
