### ISSUE TITLE
Creating blank ipynb pops up Extension error dialog requesting the presence of python even when targeting .NET Interactive notebooks

### ISSUE THREAD

**Issue by colombod** [microsoft/vscode-jupyter#8204]
## Environment data

-   VS Code version: 1.62.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1001414422
-   Python Extension version (available under the Extensions sidebar):  N/A
-   OS (Windows | Mac | Linux distro) and version: Windows11
-   Python and/or Anaconda version: N/A
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...):  N/A
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

With Jupyter and .NET Interactive extension installed use the command palette to create an empty ipynb notebook, the notebook open without problems

## Actual behaviour

Creatign emtpy notebooks or opening exteing ones bring up the following dialg:
![image](https://user-images.githubusercontent.com/375556/140783396-22f2569f-8b11-448b-9e92-9317e5ef77fb.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Ensure python extension is not installed
2. Install latest  Juptyer extenstion
3. Install latest .NET Interactive extension
4. open command palette
5. select .NET Interactive : Create new blank notebook
6. select ipynb
7. select any language

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by colombod** [comment]
@brettfo

**Comment by colombod** [comment]
on codespaces i get same behaviour even when opening a dib notebook from the file explorer
![image](https://user-images.githubusercontent.com/375556/140795810-8e90af36-aa16-4a42-a6a5-2abbbdfc333d.png)

**Comment by DonJayamanne** [comment]
Found the issue, will address this in our recovery release
