### ISSUE TITLE
Unchecking setting "Jupyter: New Cell on Run Last" doesn't work.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#8208]
### Applies To

- [ ] Notebooks (.ipynb files)
- [x] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I unchecked the "Jupyter: New Cell on Run Last", but I'm still getting new "# %%" cells on pressing shift+enter.

### VS Code Version

1.63.0-insiders

### Jupyter Extension Version

latest

**Comment by amunger** [comment]
I cannot get this to repro

**Comment by rchiodo** [comment]
Not reproing for me either. Should be fixed now. I believe @janosh fixed this problem about a month ago.

**Comment by IanMatthewHuff** [comment]
Verified. Setting looks good to me (plus I like this on, even with Ctrl+Enter as an option).
