### ISSUE TITLE
Notebooks - Kernel not maintained after save

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#8215]
- VS Code Version: 1.61.0-insider
- OS Version: WIndows

### Steps to Reproduce: 

1. Create notebook 
2. Select Kernel
3. Save 

### Actual Behavior

Kernel selection disappears/resets

![image](https://user-images.githubusercontent.com/19276747/136298503-8d8b0d41-abd6-46d8-b04a-dd0b2eb1c76b.png)

### Expected Behavior

Kernel selection to remain

**Comment by DonJayamanne** [comment]
@claudiaregio this isn't the same repro step as you demoed today.
Today the steps were:
* Create notebook
* Run a cell
* Save notebook

In your steps, you aren't running a cell.

**Comment by greazer** [comment]
If the user takes an explicit action to change the notebook kernel, then this should write the kernel to the file. For default kernels on notebooks, since the user didn't explicitly set the kernel, then opening a new notebook with the default kernel should not result in writing the kernel to metadata until the notebook is run.

**Comment by IanMatthewHuff** [comment]
Info from #11010 

@roblourens @rebornix do you think we can have some kind of event that would help Jupyter extension determine whether the user renamed a notebook from x.ipynb to y.ipynb, once we have that we can try to keep the same instance of the kernel for the user.

@[DonJayamanne](https://github.com/DonJayamanne) DonJayamanne added the [info-needed](https://github.com/microsoft/vscode-jupyter/labels/info-needed) Further information is requestedlabel [8 days ago](https://github.com/microsoft/vscode-jupyter/issues/11010#event-7228341643)
@roblourens
Member
[roblourens](https://github.com/roblourens) commented [7 days ago](https://github.com/microsoft/vscode-jupyter/issues/11010#issuecomment-1222764769)
Can you use vscode.workspace.onDidRenameFiles for this?

**Comment by DonJayamanne** [comment]
This should now be fixed with the new kernle picker
