### ISSUE TITLE
Tensorboard is always loading 

### ISSUE THREAD

**Issue by yonimedhub** [microsoft/vscode-jupyter#8223]
## Environment data

-   VS Code version: 1.57.1
-   Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS and version: linux ubuntu 20.04 on remote docker
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: tensorboard
-   Relevant/affected Python-related VS Code extensions and their versions: tensorboard
-   Value of the `python.languageServer` setting: pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

Tensorboard opens up in the dedicated window

## Actual behaviour

tansorboard in vscode is always loading and no data appears

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. run some train
2. open tensorboard via vscode
3. wait

**Comment by rchiodo** [comment]
Thanks. We might add detection logic to figure this out automatically.

**Comment by DonJayamanne** [comment]
Closing this issue as its been a while since this was reported, and we havent had others with similar issues.
Also looks like thiss is a problem outside VS Code as well,
