### ISSUE TITLE
Unable to load tensorboard logs in the remote server using remote ssh extension

### ISSUE THREAD

**Issue by harishkool** [microsoft/vscode-jupyter#8224]
Unable to load tensorboard logs for the training sessions conducted in the remote AWS server. Extension used is remotessh, tried with both vscode and vscode insiders.

VS code version: 1.57.1
VS insiders version: 1.58.0-insider

![vs_code_tensorboard_issue](https://user-images.githubusercontent.com/8947992/125814570-e4207b02-3aac-448f-b81d-d848305a5a98.png)

![vscode_tensorboard_1](https://user-images.githubusercontent.com/8947992/125814591-eff41186-6cc3-4d50-88c0-45817c14a36d.png)

**Comment by rchiodo** [comment]
Closing with assumption my workaround worked.
