### ISSUE TITLE
Allow setting tensorboard location as a workspace-specific setting?

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode-jupyter#8225]
Issue Type: <b>Bug</b>

Hi, for some reason I am unable to set the tensorboard log directory as a workspace (or Remote, for that matter) setting: 
![image](https://user-images.githubusercontent.com/8631181/129478403-e08f303f-9a4d-4f87-9157-53092f9bae22.png)

Same search in workspace settings:

![image](https://user-images.githubusercontent.com/8631181/129478423-3e0d4909-00d7-496b-ad02-cb3afe9aa41e.png)

This would make sense to have as a workspace-specific setting, as separate projects would likely use separate tensorboard log directories.

Extension version: 2021.8.1105858891
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.10.54-1-lts
Restricted Mode: No
Remote OS version: Linux x64 5.11.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 4121)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.36GB (1.90GB free)|
|Process Argv|--crash-reporter-id 66ea3ec9-05eb-4edd-8d35-34bbe6c1aba1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma-i3|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE-i3|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: medrel|
|OS|Linux x64 5.11.0-25-generic|
|CPUs|Intel(R) Xeon(R) CPU E3-1220 v5 @ 3.00GHz (4 x 3000)|
|Memory (System)|15.56GB (5.99GB free)|
|VM|0%|
</details>

**Comment by rchiodo** [comment]
Thanks for the suggestion.

**Comment by DonJayamanne** [comment]
Thanks for the suggestion, however its been over a year and no one else has up-voted this issue.
We prioritize our issues based on number of upvotes and impact of the issue, e.g. if its a bug or the like.
Closing this issue for now, however if other up-vote or create similar issues, I'll be happy to re-open this issue or make mention about the fact that its been requested here as well.

**Comment by vedal** [comment]
Seems this is possible now
![image](https://user-images.githubusercontent.com/22004000/211153755-83504213-7670-41b4-a7bc-0f41fa3b2469.png)

**Comment by sylph520** [comment]
IMO, this feature request is valuable. You usually does not want to mess the tensorboard logs of all projects together, you may wan t to set a custom tensorboard log directory for each project, thus a separate setting of default tesnsorboard log directory is fairly reasonable to me. Please reconsider this feature. (There seems  no such settings in windows vscode 1.77.3 🤣 @vedal )
