### ISSUE TITLE
Tensorboard has to reload everytime user changes to another tab

### ISSUE THREAD

**Issue by thomasbbrunner** [microsoft/vscode-jupyter#8227]
I am currently running latest VS Code with this Python extension.

## What currently happens:
Open Tensorboard on a VS Code tab and use it (eg. look at data, zoom in). If you switch to a different tab (eg. look at code) and switch back to Tensorboard, it will reload and go to the start page.

![Screencast from 30 08 2021 14_46_30 (2)](https://user-images.githubusercontent.com/23102971/131382999-5575d514-6700-4634-97c5-6b233f344273.gif)

This does not happen if Tensorboard is running in the browser.

## What should happen:
Open Tensorboard on a VS Code tab and use it. If you change tabs and go back, it should still be in the same state. 

This is specially important when using the Trace View in the Profiler, as it takes a very long time to open for long trace recordings.

**Comment by rchiodo** [comment]
Thanks for the bug. Not sure if we can address this. Might be a webview problem with VS code.

**Comment by huyfam** [comment]
I confirm this wired behavior. It was annoying.

**Comment by DonJayamanne** [comment]
This can be fixed, we just need to initialize the flag `retainContextWhenHidden` when creating the webview, for some reason this hasn't been set.
In the case of tensorboards, I think its useful to set this up, at least 2 users have complained about this.

**Comment by DonJayamanne** [comment]
Moving back to Python extension as this is an issue with the code in the Python extension

**Comment by DonJayamanne** [comment]
Fixed https://github.com/microsoft/vscode-python/pull/18592
Closing for verification
