### ISSUE TITLE
Persistent TensorBoard process

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-jupyter#8228]
### Discussed in https://github.com/microsoft/vscode-python/discussions/15658

<div type='discussions-op-text'>

<sup>Originally posted by **joyceerhl** March 12, 2021</sup>
_Originally requested in https://github.com/microsoft/vscode-python/issues/15476_

Integrated TensorBoard sessions in VS Code are terminated when the panel in VS Code is closed, with the intent of providing convenient lifecycle management.

That being said, we've gotten a request to provide a way to reuse the underlying TensorBoard process between VS Code session restarts. Is this something that users would find helpful?</div>

**Comment by DonJayamanne** [comment]
This issue has been open for over a year and we haven't received sufficient upvotes on this issue,
hence closing this
