### ISSUE TITLE
jupyter in vs-code giving Type error "'str' object is not callable" with matplotlib in plotting bargraph

### ISSUE THREAD

**Issue by arpan02122004** [microsoft/vscode-jupyter#8242]
## Environment data

-   VS Code version: 1.62.1
-   Jupyter Extension version (available under the Extensions sidebar): 2021.10.1001
-   Python Extension version (available under the Extensions sidebar): 2021.11.1422
-   OS (Windows | Mac | Linux distro) and version: windows 10 build 19042
-   Python and/or Anaconda version: python v3.9.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...):  N/A
-   Jupyter server running: Local | Remote |    : Local 

## Expected behaviour

jupyter notebook - it should plot the bargraph with xlabel and ylabel but it is giving type eroor " 'str' object is not callable " but normal interpretor is just doing it fine and plotiing the bargraph fine ...

## Actual behaviour

giving TypeError - "'str' object is not callable" on xlabel 

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. import matplotlib.pyplot as pp 
overs =[1,2,3,4]
runs=[6,18,10,5]
pp.bar(overs, runs, color='m')
pp.xlabel('Overs')
pp.ylabel('Runs')
pp.title('Score')
pp.legend(['Runs'])
pp.show()

## Logs

<details>
log of the jupyter notebook
'''Info 2021-11-12 02:13:22: Execute Cells request 1 7
Info 2021-11-12 02:13:22: Execute Cell 7 file:///c%3A/Users/arpan/OneDrive/Desktop/Testing/TestingJupyterNotebook.ipynb
Info 2021-11-12 02:13:23: Cancel all remaining cells true || 4
Info 2021-11-12 02:13:23: Cancel pending cells'''

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel <code > Info 2021-11-12 02:13:22: Execute Cells request 1 7
Info 2021-11-12 02:13:22: Execute Cell 7 file:///c%3A/Users/arpan/OneDrive/Desktop/Testing/TestingJupyterNotebook.ipynb
Info 2021-11-12 02:13:23: Cancel all remaining cells true || 4
Info 2021-11-12 02:13:23: Cancel pending cells</code > to <code>Jupyter</code>)
</summary>

<p>

```
Arpan kumar mandal 
```

</p>
email:- arpankumar1119@gmail.com
note:- reply and explain why this is happening i am curious why this is happpening ... the code is working fine in the normal interpretor but not in the jupyter notebook .....
</details>

**Comment by DonJayamanne** [comment]
Works fine for me,
![image](https://user-images.githubusercontent.com/1948812/141369086-40bac8c8-20df-4dc5-a161-09915b10135d.png)


Possible you are not using the interpreter in the kernel picker (please ensure you're using the same interpreter from the kernel picker on the top right of the notebook, or use the command `Notebook: Select Notebook Kernel`.

If that doesn't work, please provide the output from the jupuyter output panel (please provide all of the output).
The logs you provided don't contain the error messages you have mentioned.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
