### ISSUE TITLE
[Feature] Fast Navigations for Running Cells | Jump to Running Cell | Follow Running Cell

### ISSUE THREAD

**Issue by rrmistry** [microsoft/vscode-jupyter#8244]
Would be good to have fast navigation to running cells.

For example:
![image](https://user-images.githubusercontent.com/25514145/140769694-2409ee30-590a-4eb5-b3df-91f47d21f23d.png)

**Comment by greazer** [comment]
Thanks for the feedback @rrmistry. I believe your request is covered by this issue https://github.com/microsoft/vscode/issues/130611, so closing this one. Feel free to further comment on the other issue.

**Comment by rrmistry** [comment]
Sounds reasonable. Thanks @greazer !
