### ISSUE TITLE
VegaLite rendering in notebook is very slow

### ISSUE THREAD

**Issue by pablosanjose** [microsoft/vscode-jupyter#8246]
The following Julia code renders a 1000-point VegaLite scatter plot in 5+ seconds, or ~50 seconds for 10000-points. The Julia runtime is instantaneous, it is the render part which is slow. This slow render makes it very cumbersome to use VegaLite for visualization in notebooks

```julia
using VegaLite

npoints = 10000
[(; x = rand(), y = rand(), z = rand()) for _ in 1:npoints] |>
@vlplot(
    :point,
     x=:x,
     y=:y
)
```
<img width="972" alt="Screen Shot 2021-11-02 at 16 18 05" src="https://user-images.githubusercontent.com/4310809/139875960-b3c1f8a4-6f9c-4f26-b13c-afcd8031dd5a.png">

In comparison, rendering the same 10000-point plot in a recent Chromium browser takes less than 2 seconds.

**Comment by DonJayamanne** [comment]
I'm sorry for not getting back to you on this, I'll be looking into this today.

**Comment by DonJayamanne** [comment]
I've tested this at my end & it was instantaneous (tried this a few times).

**Please could you provide the following information:**
* VS Code version
* OS Version
* Jupyter extension version
* Notebook renderer version
* Output from the Jupter output panel (go into the command `Jupyter: View Output`)
* Output from the `console window` (go into the command `Toggle Developer Tools` to get there & then select `console` tab)
* From what I understand sometimes its 5s and other times 50s (ie between 5-50s).
	* Please could you confirm this
*  Are you using the `Julia` extension?
* Are you using this locally or remotely on SSH or the like.
* Finally, once you save this notebook and reload VS Code, do you experience the same perf issues when opening the saved notebook (i.e. can you see the vega output when opening the notebook, & without having to re-run it)

**Comment by pablosanjose** [comment]
When collecting this required info, I tried running the sample code in the latest Windows version of VS Code, and it runs 10 times faster than in my main macos machine. So that's a major clue. 
In any case, the data for the machine with the issue follows:

- Code version: 
```
Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z (3 days ago)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```
- OS version: macos Big Sur 11.6.1
- Jypyter extension version: v2021.10.1101450599
- Notebook renderer version: not sure how to check that, but the mimetype for the output figure is svg+xml

**Comment by DonJayamanne** [comment]
Do you see similar perf issues when using regular Jupyter notebooks (i.e. outside VSCode).

**Comment by pablosanjose** [comment]
Thanks for following up on this! 

Very interesting question, I should have checked: the delay is also present in a jupyter notebook in the browser (both Vivaldi and Firefox). Same timings in macos, much slower than simply displaying the plot in the browser (i.e. running the command in the OP from a Julia REPL).

So this means the problem is not in the vscode jupyter integration. Feel free to close this then.

**Comment by DonJayamanne** [comment]
THanks for confirming that
