### ISSUE TITLE
Neither of the debug modes working properly

### ISSUE THREAD

**Issue by r-moret** [microsoft/vscode-jupyter#8250]
## Environment data

-   VS Code version: 1.62.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Enterprise 21H1
-   Python and/or Anaconda version: Python 3.8.0    Anaconda 2021.05
-   Type of virtual environment used: conda
-   Jupyter server running: N/A

## Expected behaviour

When hitting the Run by Line button on one cell execute the cell line by line stopping automatically on every line.

When activating the Debug Cell mode debug the cell stopping on every breakpoint marked by me in the actual tab.

## Actual behaviour

When hitting the Run by Line button the cell is executed as if I just pressed the normal Run button (Ctrl + Enter) and all the cell is executed at once. The button to Continue Execution is shown but the actual line is not marked with any different color.

When activating the Debug Cell mode VS opens a new tab with the code of the cell in a new temporary `.py` file that is removed when I finish the execution. The debug is executed well in this tab because I can stop on every breakpoint but it gives some errors caused by using functions that comes from a library that is not imported on that precisely cell.

## Steps to reproduce:

1. Open a Jupyter Notebook on VS Code

2. Click on "Run by Line" button on one cell.

![Run_by_Line](https://user-images.githubusercontent.com/48282844/141386619-24fcb65f-e0bc-4615-a6c1-2bcfad787817.gif)

====== OR ======

2.  Click on "Debug Cell" in the menu next to the Run button of one cell.

![Debug_Cell](https://user-images.githubusercontent.com/48282844/141386638-d8c5210c-6c15-4b5c-a0d6-080fbd813bd4.gif)

## Logs

There are no logs for this issue.

**Comment by molly-w** [comment]
Same question and i want to know another thing that when I use standard debug mode, it will operate in a temporary file which has the same code in my `.ipynb`. Can i get the reason or if there's any setting to make it debug in original notebook?

**Comment by claudiaregio** [comment]
@r-moret, could you please separate these into two issues

**Comment by r-moret** [comment]
Yes, no problem, I will create two new issues to separate it into them. Maybe you want to delete this one then, @claudiaregio 
Thanks

**Comment by claudiaregio** [comment]
Great thank you :)
