### ISSUE TITLE
Unable to connect to remote or local jupyter server.

### ISSUE THREAD

**Issue by sanzgiri** [microsoft/vscode-jupyter#8257]
## Environment data

-   VS Code version: 1.63.0-insider (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001452373
-   Python Extension version (available under the Extensions sidebar): v2021.12.1441722766-dev
-   OS (Windows | Mac | Linux distro) and version: MacOS 10.15.7
-   Python and/or Anaconda version: Conda 4.10.3, Python 3.7.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local & Remote

## Expected behaviour

I should be able to connect to a remote (or local) jupyter server if I provide the correct URL + token. 

## Actual behaviour

I get a popup window that says "Please reload VS Code when changing the Jupyter Server connection."  However, even after reloading the connection is never established.

This happens with a jupyter server running on my local MacOS laptop or on a remote Ubuntu Linux machine.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Cmd-Shift-P, Jupyter Specify local or remote jupyter server
2. Choose Existing
3. Provide URL + Token
4. Click Enter
5. Get popup shown below
![Screen Shot 2021-11-12 at 12 09 55 PM](https://user-images.githubusercontent.com/291370/141528590-9c79d984-465d-41be-a56f-0cf0e8e0111c.png)

6. Selecting Reload restarts VSCode but does not connect to Jupyter server

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Please could you provide the output from the Jupyter logs

**Comment by sanzgiri** [comment]
Hi Don, I am not seeing any output / logs. No errors either. I am back to where I left in VSCode after the reload. No connection to the local/remote jupyter is established.

**Comment by DonJayamanne** [comment]
> . I am back to where I left in VSCode after the reload. No connection to the local/remote jupyter is established.

Have you opened an ipynb file. You need to open an ipynb file. We connect to the server only when we need it, opening VS Code will not trigger any connection to the server.

**Comment by sanzgiri** [comment]
Ok, thanks. Looks like I have to connect to the remote host via ssh and open an ipynb file. I was expecting that VSCode would automatically connect to the specified server. I will close this ticket.
