### ISSUE TITLE
Run by Line debug cell mode just executes the whole cell

### ISSUE THREAD

**Issue by r-moret** [microsoft/vscode-jupyter#8258]
## Environment data

-   VS Code version: 1.62.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Enterprise 21H1
-   Python and/or Anaconda version: Python 3.8.0    Anaconda 2021.05
-   Type of virtual environment used: conda
-   Jupyter server running: N/A

## Expected behaviour

When hitting the Run by Line button on one cell it should execute the cell line by line stopping automatically on every line, indicating the current executed line with a different color and a sign.

## Actual behaviour

When hitting the Run by Line button the cell is executed as if I just pressed the normal Run button (Ctrl + Enter) and the whole cell is executed at once. The button to Continue Execution is shown but the actual line is not marked in any way.

## Steps to reproduce:

1. Open a Jupyter Notebook on VS Code

2. Click on "Run by Line" button on one cell.

![Run_by_Line](https://user-images.githubusercontent.com/48282844/141386619-24fcb65f-e0bc-4615-a6c1-2bcfad787817.gif)

## Logs

There are no logs for this issue.

**Comment by greazer** [comment]
Hey @r-moret, thanks for the feedback. Can you ensure that you have ipykernel version 6.0 or greater installed into your ```test``` kernel environment?

To check if you have an appropriate version installed run...
```python
import ipykernel
ipykernel.__version__
```

**Comment by r-moret** [comment]
Hi @greazer, thanks to you for the answer! I've checked the version of `ipykernel` on my `test` environment through your indications and I can confirm that my version is `6.5.0`

**Comment by TheWillyM4AK** [comment]
I'm having exactly the same problem. I've been trying to set up everything correctly the last couple of days with no succes.  I have the `6.5.0` version of `ipykernel` too.

**Comment by TheWillyM4AK** [comment]
> When hitting the Run by Line button the cell is executed as if I just pressed the normal Run button (Ctrl + Enter) and the whole cell is executed at once. 
> 
I think I can add something. The whole cell is not executed like when you press the normal Run. It is executed like in a slow mode. I have some cell that prints tens of lines of output. In normal mode they are printed all at once. In run by line they are printed one by one.

In normal run execution time is 0.2s, in run by line it is increased to 59.6s.

**Comment by roblourens** [comment]
Sorry for the trouble, could you set `"jupyter.logging.level": "verbose"`, try this again, and share the log from the "Jupyter" output channel?

**Comment by r-moret** [comment]
Hi, thanks for the reply. I've set the setting parameter to `verbose` but how could I access the Jupyter output channel to get the log?

**Comment by roblourens** [comment]
It's here:

![image](https://user-images.githubusercontent.com/323878/142035209-862f9258-8bc4-41aa-a6cd-690730a28a4c.png)

**Comment by TheWillyM4AK** [comment]
@roblourens I did it myself. There are 2 logs. One is printed when vscode starts and opens a notebook. I've seen some errors. The other one is the log produced when I press F10 on a cell.
[Log_start.txt](https://github.com/microsoft/vscode-jupyter/files/7549033/Log_start.txt)
[Log_f10.txt](https://github.com/microsoft/vscode-jupyter/files/7549034/Log_f10.txt)

**Comment by r-moret** [comment]
Thanks for the info @roblourens, I've executed the cell and this is the log I've obtained: https://gist.github.com/r-moret/6bdd65f70155ba5c439849e5ee485e12

**Comment by roblourens** [comment]
Thanks for the logs. Both of these are caused by Jupyter using the windows "short name" formatting for the user dir: `C:\\Users\\RAFAEL~1\\AppData\\Local\\Temp` which we compare to the long name. Interesting

**Comment by TheWillyM4AK** [comment]
Thanks! You nailed it. I created a new user in windows with a name shorter than 8 characters and it worked. It was driving me mad.

**Comment by r-moret** [comment]
@roblourens and do you think is there any other solution or workaround than creating a whole new user on the system, like @TheWillyM4AK did? Because in my  case, in a first instance it is not possible to do that...

**Comment by melfar87** [comment]
@r-moret  one workaround is to change `TMP` and `TEMP` environment variables in Windows from `%USERPROFILE%\AppData\Local\Temp` to a folder that does not have a short name (e.g., `C:\localtmp`), then restart the kernel to reflect the changes.

**Comment by AyhamSaffar** [comment]
@DonJayamanne i have also encountered this bug despite having the latest ipykernal installed. Would be amazing not to have to create a new user on windows / start messing with enviroment variables. Could you help?

**Comment by garrofederico** [comment]
Is there any update on this? if not, has anybody found a workaround that works on macos that doesn't involve creating a new user just to use the debugger?

**Comment by elcoxo** [comment]
@r-moret I had similar issue when "Debug Cell" button exetuted the whole cell. First I tried to delete VS Code cache like [here](https://stackoverflow.com/questions/53204589/how-to-completely-purge-visual-studio-code-on-ubuntu) and reinstall Jupyter with `conda install jupyter notebook` and `pip install jupyter`. But these steps actually didn't help me...

The only thing that **worked** for me was downgraging Jupyter extension in VS Code:
![jupyter_downgrade](https://user-images.githubusercontent.com/38883294/235891473-9e5decca-3858-4b04-94d4-b7b2deec18fa.png)

hope this tip will help someone :)
