### ISSUE TITLE
[vscode.dev] add support for creating Jupyter notebooks

### ISSUE THREAD

**Issue by COWI-MI** [microsoft/vscode-jupyter#8266]
It would be nice if vscode.dev could create Jupyter notebooks via the command palette "Jupyter: Create Blank New Jupyter Notebook"

Existing notebooks can be opened and run interactively in vscode.dev with the extension [pyolite](https://github.com/joyceerhl/vscode-pyolite), but I can't find a way to create them.

**Comment by DonJayamanne** [comment]
Thanks, you should be able to do this today using the command `Create: New File ...` and then selecting `Jupyter Notebook`
See below:
![image](https://user-images.githubusercontent.com/1948812/141833743-d22d9054-1769-47a9-b969-3f4bee17ef5f.png)
![image](https://user-images.githubusercontent.com/1948812/141833830-4c4396fb-805c-4d7e-aefd-3cf351149f91.png)

**Comment by COWI-MI** [comment]
Thanks for the reply!

When i selects "Create: New File..." I see this instead of the option seen in your second screenshot:
[cid:540f7f7f-12e2-4675-8dc6-8e80ae1f2dc4]

Selecting a language gives me no "Jupyter Notebook":
[cid:f33682b5-316c-410f-ad61-28548907421c]

The language "Jupyter" does not make it a Python Jupyter Notebook. And saving the file ony saves it as a text file.

[cid:d080ec60-aeb8-44b4-94fb-c6f6d770ff44]

[cid:1ebe1d12-ac9a-495f-b17e-379aafade355]



________________________________
Fra: Don Jayamanne ***@***.***>
Sendt: 15. november 2021 19:19
Til: microsoft/vscode-jupyter ***@***.***>
Cc: Magnus-Matias Isbrand Høirup ***@***.***>; Author ***@***.***>
Emne: Re: [microsoft/vscode-jupyter] [vscode.dev] add support for creating Jupyter notebooks (Issue #8266)


Thanks, you should be able to do this today using the command Create: New File ... and then selecting Jupyter Notebook
See below:
[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1948812%2F141833743-d22d9054-1769-47a9-b969-3f4bee17ef5f.png&data=04%7C01%7Cmi%40cowi.com%7C1fa4493dd1e14227bebd08d9a86482f2%7C11be153879d8493982b8b767805d825b%7C0%7C0%7C637725971919681500%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5ZoLxvD5EUoru%2BBzA%2Bs66Sle8eBAhMcpp58xNwOQrL4%3D&reserved=0>
[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1948812%2F141833830-4c4396fb-805c-4d7e-aefd-3cf351149f91.png&data=04%7C01%7Cmi%40cowi.com%7C1fa4493dd1e14227bebd08d9a86482f2%7C11be153879d8493982b8b767805d825b%7C0%7C0%7C637725971919681500%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vyF38o2m1E5daG0C4S43JOw7%2BNhWdnc7HaH5gr9GvGs%3D&reserved=0>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode-jupyter%2Fissues%2F8266%23issuecomment-969188703&data=04%7C01%7Cmi%40cowi.com%7C1fa4493dd1e14227bebd08d9a86482f2%7C11be153879d8493982b8b767805d825b%7C0%7C0%7C637725971919691456%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KF1%2B10tz21RgvvpQeZcapt4iEfFnKR%2Bi5jNHQPgd%2BOU%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVO6VFC3PIJICASFEPWBIADUMFFMJANCNFSM5ICJUT4A&data=04%7C01%7Cmi%40cowi.com%7C1fa4493dd1e14227bebd08d9a86482f2%7C11be153879d8493982b8b767805d825b%7C0%7C0%7C637725971919691456%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Fd8YPhz%2FSBnlT1wmCGpVXpcpwHHWEYWHWUcI4DDYPVQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmi%40cowi.com%7C1fa4493dd1e14227bebd08d9a86482f2%7C11be153879d8493982b8b767805d825b%7C0%7C0%7C637725971919701408%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PEcDLpT3wgYdxWXfdl7CCpINOvrjlwNgyoTbRxESXzU%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmi%40cowi.com%7C1fa4493dd1e14227bebd08d9a86482f2%7C11be153879d8493982b8b767805d825b%7C0%7C0%7C637725971919701408%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=56%2BwP0qdMTcvu5iV427PWACJpHSkGtbJmSR3K%2FaOzMI%3D&reserved=0>.

COWI handles personal data as stated in our Privacy Notice<https://www.cowi.com/privacy>.

**Comment by COWI-MI** [comment]
When I selects "Create: New File..." I see this instead of the option seen in your second screenshot:
![1](https://user-images.githubusercontent.com/90040980/141855200-2926f163-90a9-429f-9f12-a9416e2f7c3b.png)

Selecting a language gives me no "Jupyter Notebook":
![2](https://user-images.githubusercontent.com/90040980/141855287-9d8a91d3-4aaf-4745-96ad-69882244d645.png)

The language "Jupyter" does not make it a Python Jupyter Notebook. And saving the file ony saves it as a text file.
![3](https://user-images.githubusercontent.com/90040980/141855310-1d63b79b-6df8-4f35-96d0-8876ac5e0839.png)

**Comment by tbelaire** [comment]
Yeah, if you do select language it doesn't actually start up the kernel interface in the same way as "Jupyter: Create Blank New Jupyter Notebook" does.
