### ISSUE TITLE
No error shown for not connecting to the IPyKernel if the same python version is re-selected

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#8267]
Issue Type: <b>Bug</b>

1. Open a notebook or the Interactive Window
2. Uninstall the IPyKernel from the current Python environment
3. Try to run a cell -> shows an error that IPyKernel needs to be installed
4. Select "Change Kernel" in the pop-up and select the same Python version

Actual Result:
No error shown, just stuck on the "connecting to kernel step"

Expected:
Same error pop-up since kernel still isn't installed

Extension version: 2021.10.1101450599
VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.00GB free)|
|Process Argv|--crash-reporter-id 310505c2-5030-4a12-9cd3-d8846072dfe0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by IanMatthewHuff** [comment]
Gets this error now for the scenario:
![image](https://user-images.githubusercontent.com/812783/151266938-cc52ef55-4ea4-4ed6-84a4-45359ca8ab8d.png)
