### ISSUE TITLE
Jupyter likely not activated

### ISSUE THREAD

**Issue by ch98road** [microsoft/vscode-jupyter#8269]
## Environment data

-   VS Code version:  1.63.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001461390
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: Both Mac and Win
-   Python and/or Anaconda version: conda 4.10.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Jupyter server running: Local | Remote | N/A:i have tried both Remote and Local

## Actual behaviour

seems like jupyter do not activated, so that I cannot find the runner button
![78BAC35D58422DE0965BE2CC721A7EAC](https://user-images.githubusercontent.com/49389600/141921962-2766ff99-240b-4c2c-9ca8-dbd4e4cf3bcd.png)
![15A046D4CA740D72A33CA9BA7DEB2049](https://user-images.githubusercontent.com/49389600/141921937-45823901-dba6-45f4-b0cd-65b05e54690d.png)

and if I use the command like :Jupyter:Create netw Jupyter Notebook，it returns:Command not found
![image](https://user-images.githubusercontent.com/49389600/141922239-f2147222-766b-4f89-a15f-935877d04e3b.png)

**Comment by rchiodo** [comment]
Thanks for the bug. Can you go to the Help menu and click on Toggle Developer Tools. There should be a console panel on that tab. It should contain any errors that might have come up with activating the jupyter extension.

**Comment by rchiodo** [comment]
Closing for now. If you can provide the asked for information, please reopen.
