### ISSUE TITLE
Jupyternotebook plot view does not generate vector plot

### ISSUE THREAD

**Issue by flyforward2016** [microsoft/vscode-jupyter#8272]
When I use VCcode (1.63.0 - insider) python Jupiter notebook to generate plot in the "plot view", the resolution of the plot is very poor not like the "vector" plot before. Hope this can be fixed. Thank you very much.

**Comment by rchiodo** [comment]
This was actually done on purpose because vector plots are really really big and can make your notebook grow way too much.

There's a setting to go back to the old way though:

![image](https://user-images.githubusercontent.com/19672699/142031813-e6e32d91-c415-4f0e-83db-7fbfd5ff82c4.png)
