### ISSUE TITLE
Automate GDPR tooling

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8280]
Looking here:
https://github.com/microsoft/vscode-telemetry-extractor/blob/main/documentation/typescript-code-annotations.md

And here (example from python)
https://github.com/microsoft/vscode-python/commit/a7acabb8e361469e7b8f5086398400d6d20a05ba

We could use the GDPR tooling from VS code to automate GDPR checking

**Comment by rchiodo** [comment]
We can either do it the comment way or the interface way.

**Comment by rchiodo** [comment]
Did some research on this. 

First attempt is here:
https://github.com/microsoft/vscode-jupyter/tree/rchiodo/adopt_vs_code_telemetry

Thoughts:
- publicLog2 is the way to go.
- publicLog2 does not support the way we infer properties from a keyof entry. 
- Changing the vscode-telemetry-extractor code to make it support that would be too specific to our repro
- We should instead change our logging to match how VS code does it. Example:
```
                sendTelemetryEvent(Telemetry.ExportNotebookAsCommand, { format: exportMethod });
```
becomes:

```
interface IExportProperties {
   format: ExportMethod
}
interface IExportPropertiesClassification {
   format: { classification: "SystemMetadata", purpose: "PerformanceAndHealth"}
}

       publicLog2<IExportProperties, IExportPropertiesClassification>(Telemetry.ExportNotebookAsCommand, {format: exportMethod});
```
- This is likely to take a lot of changes. The decorator will have to be removed/changed to support this too.
- We then update vscode-telemetry-extractor to follow the enum for 'Telemetery.ExportNotebookAsCommand' (right now it would output the constant name)
- Finally we add another option to vscode-telemetry-extractor that generates the telemetry.md file like our https://github.com/microsoft/vscode-jupyter/blob/397a5b38023a4fdb0b339339a86d8b540335aba0/src/platform/tools/telemetryGenerator.node.ts#L385

**Comment by rchiodo** [comment]
Not doing this now, might be a good first issue.

**Comment by DonJayamanne** [comment]
@rchiodo  Do we know what Python team did to get this working, it looks like they've gone down a different path.
Meaning there's another possible solution to this

**Comment by rchiodo** [comment]
They commented everything (see the linked PR above). The problem with the comments is there's no way to generate the telemetry.md from them as there is no use of the comments.

**Comment by DonJayamanne** [comment]
Closing this as done.
