### ISSUE TITLE
Request: option to shut down kernel

### ISSUE THREAD

**Issue by david-cortes** [microsoft/vscode-jupyter#8287]
In the interactive python environment which opens at the right side of the screen when running code from a python file interactively, there is no option to shutdown the ipython kernel, only to restart it. Would be nice to add the option for shutting it down and have it reactivate automatically once new code is run on that interactive environment.

**Comment by rchiodo** [comment]
Thanks for the suggestion. 

What's your reason for wanting to shut it down early? 

Right now it shuts down when closing the interactive window.

**Comment by david-cortes** [comment]
Good to know, didn't realize closing it shuts down the process. The reason was basically to free resource usage after it's no longer needed in order to run something else in a different application while continuing writing in the editor, but closing it is good enough for that.
