### ISSUE TITLE
Simplify PDF export by using webPDF

### ISSUE THREAD

**Issue by Cube707** [microsoft/vscode-jupyter#8288]
## Problem:

exporting a notebook to PDF is rather complicated and requires a Tex installation (and Pandoc I belive?).

I believe exporting to PDF is an important feature and should be easy to not scare of beginners.

## Solution:

The `nbconvert` module now includes a second PDF exporter called `webPDF` which exports the notebook first to HTML and uses `pyppeteer` headless chrome to print it to PDF. As this is the currently recommended Workflow, implementing it into a single button press makes a lot of sense to me.

The Exporter also has the option to export A4 pages (default) or a single, continues page. 

In my opinion, `webPDF` with one continues page should become the default behaviour for the PDF export. But at least a second Option should be implemented.

### Example:

Here is and example call to `nbconvert`:

```bash
jupyter nbconvert --to webpdf --WebPDFExporter.paginate=False example.ipynb
```

**Comment by Cube707** [comment]
related: #7745 would probably be solved by this

**Comment by rchiodo** [comment]
Thanks for the suggestion. I thought we already had this issue (we've been discussing switching to webPDF ourselves).

The problem right now is that webPDF has some issues with installation too.

**Comment by Cube707** [comment]
I am sorry if I missed another existing issue.

Thats great to hear. Installing the headless chrome might also pose some dificulties, but I from my point of view this is probably simpler than having to install a Tex distro and Pandoc. It would also stay inside the Python ecosystem and avoid people that don't want/need Tex some headaces.
Also nbconvert tries to autodwonload pyppeteer if its missing (which might be a resent feature)

Let me know if wou need people to run some teste/comparisons :)

**Comment by DonJayamanne** [comment]
Unfortunately this issue has not recieve enough upvotes nor interest over the past 2 years.
Hence closing this issue.
