### ISSUE TITLE
Jupyter extension starts an expensive workspace search on activation

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [microsoft/vscode-jupyter#8293]
>I raised this issue in remote-ssh, but turns out the evidence indicates it is an issue in Jupyter Notebook.
>
>Please see: https://github.com/microsoft/vscode-remote-release/issues/5904

In brief...

Jupyter search is following circular symlinks.  This tells me it is ignoring my setting for `"search.exclude"`. I am now going to be trying `"search.followSymlinks": false`.  Does Jupyter honor that setting?

If not, how can I tell Jupyter to exclude search directories or not to follow symlinks?

FWIW, this is also an issue in Pylance (https://github.com/microsoft/pylance-release/issues/1939), where I had to create a `pyrightconfig.json` file and duplicate my `"search.exclude"` setting.

It would be far better if all extensions honored some global setting, otherwise I'll be chasing this type of issue forever.

## Environment data

-   VS Code version: 1.62.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Python3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: N/A

## Expected behaviour

XXX

## Actual behaviour

Jupyter search consumes 100% CPU as it get stuck in circular symlinks.

## Steps to reproduce:

Please see: https://github.com/microsoft/vscode-remote-release/issues/5904

## Logs

Please see: https://github.com/microsoft/vscode-remote-release/issues/5904

**Comment by roblourens** [comment]
I didn't realize that the jupyter extension was starting a search through the entire workspace: https://github.com/microsoft/vscode-jupyter/blob/fa8bb5d5433bde220b6c5ed4b4781118d46b5e9e/src/client/datascience/interactive-common/notebookUsageTracker.ts#L31

Please don't do this unless absolutely necessary, searches can be very expensive

**Comment by rchiodo** [comment]
@roblourens we use this to gather telemetry on the number of notebooks in a workspace. Is there an alternative?

**Comment by roblourens** [comment]
Do you absolutely have to have that info? If so, maybe you could limit the search to run for 5s. 

If I open my home folder, and activate the jupyter extension, the search runs for minutes and my machine looks like this:

![image](https://user-images.githubusercontent.com/323878/142291488-d5eddd9f-b67d-4152-ac0d-abebefb8877d.png)

![image](https://user-images.githubusercontent.com/323878/142291605-07cf94fd-7da1-47c9-8711-2ae93f549ab8.png)


extensions running searches is one of the top things that leads to people saying that vscode is "slow" or "bloated" so we really want to avoid this. I just noticed that the python extension is doing this too.

**Comment by rchiodo** [comment]
Does VS code have this in its own telemetry (extension counts for workspaces?)

@ronglums @claudiaregio do we still use notebook count telemetry in a workspace for anything?

**Comment by roblourens** [comment]
We do something to collect file counts, but it doesn't use ripgrep, has some low max count, and is careful to avoid too much system impact

**Comment by rchiodo** [comment]
Sounds like we can drop this then. You have an equivalent.

**Comment by roblourens** [comment]
I mean we don't report the number of notebooks, just total number of files

**Comment by rchiodo** [comment]
Could that be modified to indicate extension?

**Comment by roblourens** [comment]
Probably wouldn't count on it

**Comment by ronglums** [comment]
I'll let @claudiaregio comment on whether this data point is still in use.
