### ISSUE TITLE
jupyter variables windows bug: doesn't show and too slow

### ISSUE THREAD

**Issue by yanyu2015** [microsoft/vscode-jupyter#8302]
when I generate a big DataFrame（about 360000 lines） in jupyter,it doesn't show in the  jupyter variables windows while it works well in spyder.
and if I use xx.head() to view the DataFrame,it speeds too much time to print the result.
the code is as fellow:

```python

# 计算离职人数指标
dict1 = dict()
i = 1
for name,group in wdata.groupby(['MCode']):
    group['LE'] = group.FM_num - group.FM_num.shift(1)
    dict1[i] = group
    i = i + 1
M = pd.concat(dict1)
M.head()
```

**Comment by IanMatthewHuff** [comment]
@yanyu2015 Sorry could you please clarify your report a bit? In the Jupyter variables window do you mean that the variable doesn't show up at all in this window here?
![image](https://user-images.githubusercontent.com/812783/142486916-48cbf318-96ce-4400-84e7-8ffbe00b184a.png)

Or do you mean that it doesn't load if you view it in the data viewer like this?
![image](https://user-images.githubusercontent.com/812783/142487057-70289147-c9c0-40ff-a082-9bf4ff97282c.png)

**Comment by yanyu2015** [comment]
> @yanyu2015 Sorry could you please clarify your report a bit? In the Jupyter variables window do you mean that the variable doesn't show up at all in this window here? ![image](https://user-images.githubusercontent.com/812783/142486916-48cbf318-96ce-4400-84e7-8ffbe00b184a.png)
> 
> Or do you mean that it doesn't load if you view it in the data viewer like this? ![image](https://user-images.githubusercontent.com/812783/142487057-70289147-c9c0-40ff-a082-9bf4ff97282c.png)
I mean the variable doesn't show up at all in this window here(the first image).
and I need to remind you that if I use `M.head()` in cell, it doesn't show the result while it should be print downside in normal case.

**Comment by IanMatthewHuff** [comment]
Is this a specific data file or notebook that you could share out? I tried creating some very large dataframes (1000000 rows) and they showed quickly in the variable view, in the data frame viewer and df.head() printed quickly. Is does the dataframe have a ton of columns as well (the examples I was testing with didn't).

Also could you look at the logging in Output->Jupyter and save that to a file and attach the file to a comment here. Might be something in that logging that I can see going wrong.

**Comment by yanyu2015** [comment]
Can you leave a email? I don‘t want to upload my data in public. I have check my data,it do has this problem. Is there some other reason may arise this problem?

**Comment by IanMatthewHuff** [comment]
@yanyu2015 Very sorry that this issue got dropped. I just ran into it while checking my old issues. Are you still running into this issue?

**Comment by rchiodo** [comment]
Closing as needs more info. If you can repro still please feel free to reopen.
