### ISSUE TITLE
Incomplete output of Command "Jupyter: Run Current File In Interactive Window".

### ISSUE THREAD

**Issue by ttSpace** [microsoft/vscode-jupyter#8312]
## Environment data

Build of Visual Studio Code - Insiders: 1.63.0-insider (user setup)
Build of python-insider: v2021.12.1478695168-dev
Build of jupyter-insider: v2021.11.1001475629
Build of pylance-insider: v2021.11.2
Build of jupyter Keymap-insider: v1.0.0
Build of jupyter Notebook Renderers-insider: v1.0.3

## Expected behaviour

Show all output.

## Actual behaviour

The markdown and Altair don't show.
BTW, after changing the position of ```Altair```, Altair was displayed.

![image](https://user-images.githubusercontent.com/82852072/142586264-bce4b921-9bde-41c7-b166-6742ba6c7be3.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Make sure Anaconda installed in local.
2. Open the file src/test/datascience/manualTestFiles/manualTestFile.py in VSCode.
3. At the top of the file it will list the things that you need installed in your Python environment.
  a. Please note, when installing PyTorch please visit pytorch.org to determine how to install torch for your environment. Do not run pip install torch as that will not suffice.
4. Ctrl + shift + P to open command palette.
5. Select the ```"Jupyter: Run Current File In Interactive Window"```.

**Comment by rchiodo** [comment]
Thanks for the bug.

For me this is crashing on the latex stuff. It looks like it's ingesting the entire file as one cell instead of as separate cells. I thought we used to do separate cells.

**Comment by rchiodo** [comment]
Separate cells would make it work because the latex cell magic would be appropriate.

**Comment by IanMatthewHuff** [comment]
Looks good now running the whole file:
![image](https://user-images.githubusercontent.com/812783/151237859-bce114a0-be01-4ba5-840f-1e86a59661be.png)
