### ISSUE TITLE
Test: set_next_input intermittent failure

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8315]
![image](https://user-images.githubusercontent.com/19672699/142667160-908492ba-529f-46f2-b7ee-d46cc60adf1c.png)

Looks like it's not actually rewriting the input.
[13.txt](https://github.com/microsoft/vscode-jupyter/files/7571998/13.txt)

**Comment by DonJayamanne** [comment]
I think the output might be getting set a little after the cell execution state completed.
I'd three might be a slight delay in outputs being setby vscode.
We might want to add a slight delay.
That would explain the flakiness, I don't think the flakyness is in our code

**Comment by DonJayamanne** [comment]
This should be fixed now
