### ISSUE TITLE
Cannot change basic keybinds

### ISSUE THREAD

**Issue by peekxc** [microsoft/vscode-jupyter#8321]
## Environment data

Version: 1.63.0-insider
Commit: bedf867b5b02c1c800fbaf4d6ce09cefbafa1592
Date: 2021-11-18T05:17:00.890Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0

## Expected behaviour

I can send things to the interactive terminal

## Actual behaviour

I cannot send things to the interactive terminal

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Download VSCode Insiders 
2. Open keyboard shortcuts 
3. Change the jupyter.execSelectionInteractive keybind to anything (cmd+enter, or even something unique like shift+v)
4. Inspect that keybind from (3) indeed has highest precedence for its given setting
5. Observe that pressing said keybind on any line in *.py file does not send the selection to the interactive window

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
Seems to have been broken for a while.

**Comment by DonJayamanne** [comment]
@peekxc 
You'll need to turn on the setting `jupyter.sendSelectionToInteractiveWindow`
Once thats done, it will work.

Closing as that works as expected
If that doesnt work, please feel free to reopen this or create a new issue.
