### ISSUE TITLE
Display error message with instructions to install ipykernel in cell output

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8327]
If installation of ipykernel fails or the like, then display an error in cell output with instructions on how the user can install ipykernel

![image](https://user-images.githubusercontent.com/1948812/142923166-91e19f6e-ff81-4c3f-9165-f968cc430460.png)

**Comment by rchiodo** [comment]
This is going to be tough to verify? How do I get ipykernel to NOT install?
