### ISSUE TITLE
Rainbow syntax highlighting in interactive window cell

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#8353]
![image](https://user-images.githubusercontent.com/812783/143298521-02b2ef75-67ad-49b9-9488-0d7d762b228e.png)

@rchiodo I believe that you fixed this in notebook cells but I currently repro the iffy highlighting in interactive window cells. At least for this specific scenario.

**Comment by rchiodo** [comment]
That might have been caused by my concat document changes. So would be a new bug.

**Comment by rchiodo** [comment]
Hmm, I can't repro this. 

I get this:
![image](https://user-images.githubusercontent.com/19672699/143953162-d8a84a00-3a61-4be0-9719-973260993a6e.png)

**Comment by rchiodo** [comment]
Can repro now.
