### ISSUE TITLE
Display error message with instructions to install ipykernel in cell output

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8358]
Refs: https://github.com/microsoft/vscode-jupyter/issues/8327

- [x] anyOS @paulacamargo25
- [x] anyOS @luabud

Complexity: 3

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%238358%0A%0A&assignees=DonJayamanne)

---

* Install Python
* Install Python & Jupyter Extension
* Open a workspace folder & create a Virtual Python environment as follows `python -m venv .venv` (where `.venv` is the name of the virtual enviornment) (more info on virtual envs here https://docs.python.org/3/library/venv.html)
* Reload VS Code
* Ensure the configured shell is Command Prompt or Powershell.
* Create a new Jupyter notebook (file extension `.ipynb`)
	* Select the `.venv` kernel from the top right of the Notebook UI (optionally use the command `Notebook: Select Notebook Kernel`)
* Add a cell with the code `print("hello")` and hit run (**Do not install ipykernel**)
	* [ ] Verify you are prompted to install IPyKernel
* Click `Cancel` in the prompt to install ipykernel
	* [ ] Verify the error message with details on how to install IPYKernel is displayed in the cell output

**Comment by cshjin** [comment]
A solution I knocked was to upgrade the ipykernel from ver 5.3.4 to 6.4.1 with python3.7. 
`conda update ipykernel`

**Comment by paulacamargo25** [comment]
Works, nice!
<img width="1277" alt="Screen Shot 2021-11-30 at 12 11 30 PM" src="https://user-images.githubusercontent.com/17892325/144120771-3ede286b-4ab3-43eb-b562-dfbeed049672.png">
