### ISSUE TITLE
Pip Install Packages in Jupyter extension when using unsupported shells on windows

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8359]
Refs: https://github.com/microsoft/vscode-jupyter/issues/8325

- [x] windows @joaomoreno
- [x] windows @rzhao271

Complexity: 3

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%238359%0A%0A&assignees=DonJayamanne)

---

* Install Python
* Install Python & Jupyter Extension
* Ensure you have a shell other than Command Prompt & Powershell (e.g. WSL or GitBash)
* Locate Python executable
	* Ensure you are using a globally installed version of Python.
	* Do not use Conda, Virtual env, Pyenv or Poetry or the like (if you don't know what that is, then you're doing the right thing)
*  Ensure ipykernel is not installed in the above Python environment
	* Open a `command prompt` and run the following command:
	* `python -m pip uninstall ipykernel -y`
* Go into VSCode
* Change the shell to WSL or Gitbash
* Create a new Jupyter notebook (file extension `.ipynb`)
* Ensure you select the Global Python enviornment identified earlier
	* 	Use the kernel picker (top right of the Notebook UI, or the command `Notebook: Select Notebook Kernel`) to pick the right python environment.
* Add a cell with the code `print("hello")` and hit run
	* [ ] Verify you are prompted to install IPyKernel
* Click `Install` in the prompt to install ipykernel
	* [ ] Verify you get a progress message indicating the fact that ipykernel is being installed
* [ ] Verify you can run cells & get output (i.e. verify ipykernel was installed successfully)

**Comment by joaomoreno** [comment]
Fantastic test plan item, everything was perfectly detailed! 👏

Works as expected.
