### ISSUE TITLE
Required to udpate IPyKernel to 6 from 5...

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8362]
> A solution I knocked was to upgrade the ipykernel from ver 5.3.4 to 6.4.1 with python3.7. 
`conda update ipykernel`

Orignally mentioned here https://github.com/microsoft/vscode-jupyter/issues/8358#issuecomment-978198619

@cshjin Please could you provide more informatoin on this. 
I.e. what was the problem & error messages you got.

**Comment by cshjin** [comment]
It happened after upgrading to vscode ver 1.62.3 with extension `jupyter` v2021.10.1101450599.
The problem happened when I tried to `debug cell` (alt+ctrl+shift+enter on linux) in the notebook. 
A window popped up saying `ipykernel setup required for this feature`.

Upgrading the `ipykernel` solves the problem.

**Comment by DonJayamanne** [comment]
Thanks, I thought you ran into some bug.
Closing as we did provide the right information and you managed to address it.
