### ISSUE TITLE
Document how to use Matplot lib widgets 

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8365]
Recommend usage of `%matplotlib widget` over others.
Update Wiki
Create a diagnostic message as we do for `!pip install`, users are regularly running into this.

**Comment by rchiodo** [comment]
I'm going to do the same thing you did for ```!pip install``` and document it on the wiki

**Comment by DonJayamanne** [comment]
I think we should offer a code actions to change this to `%matplotlib widget` or `%matplotlib inline` and then offer the existing `More information` as well.
This way the user can change it to one of the the two.

**As a user:**
* I would see the problem and the message indicates i should use either `widget` or `inline` to get things working
* I'd then expect a code action to change it to one of the two & have a 3rd code action for more information (as is the case).

**Comment by DonJayamanne** [comment]
Is this a bug? or enhancement, documenting this feature should ideally be a enhancement or just a regular debt item.
Feel free to change this

**Comment by rchiodo** [comment]
It behaves the same as !pip install. Do something extra should be a new issue.
