### ISSUE TITLE
Option to display a line for every cell in .py files with percent markup

### ISSUE THREAD

**Issue by smojef** [microsoft/vscode-jupyter#8368]
The editor currently only shows cell separation lines for the current cell.  However I need to see every cell separation permanently.  Can we add lines for missing red arrows please?
![img1](https://user-images.githubusercontent.com/43252951/143490751-8ebd3563-56aa-40c4-ae7b-09cee6fe3d5a.png)
Implementation suggestions:
- Add a boolean option to display all separators (true) or only current cell (false)
- Add a color styling option for themes

It is very difficult to move from Spyder to VS Code without this feature.  Here is the same screenshot in Spyder:
![spyder](https://user-images.githubusercontent.com/43252951/143496026-0c171a1b-a833-4748-9172-c09a907794be.png)

Thanks

**Comment by rchiodo** [comment]
Thanks for the suggestion. We had this at one point but thought it too noisy. Should be easy to add an option to support this.

**Comment by smojef** [comment]
Thanks @rchiodo, I finally understand why I have seen such screenshots in the past!  Is there a way I can hack this feature back quickly (it is really a deal breaker for me)?  It is also funny you mention about noise, because I find the "Run Cell | Run Above | Debug Cell" to be too noisy.   I have some UX design background.  If you look at the Spyder screenshot, the separator line along with the #%% comment form a separation block of uniform color.  The eye gets quickly trained to read the comment under every separator line to find the appropriate cell (when scrolling through code).  However, in the current VS Code implementation, the "Run Cell | Run Above | Debug Cell" repeated everywhere at the left actually distracts the eye that is searching for a cell title.  Improved variations could include:
- To display these commands only for the current cell (but leave an empty space above other cells).
- To display these commands only on mouse hover (but leave en empty space when not displayed).
- To display these commands as a right-aligned overlay on the same line as the #%% comment on mouse hover only, to minimize visual impact, while keeping discoverability.
Thanks

**Comment by rchiodo** [comment]
We use vscode's text decorations to put those lines in a python file: https://code.visualstudio.com/api/references/vscode-api#TextEditorDecorationType. You could look in our source where we create those decorations and add an option to add them for every cell. 

However there's no current way to limit the code cells to the current cell. We'd have to update code lenses on cursor move for that to work and it'd be way too expensive. An alternative to having the code lenses visible, is to just disable them altogether. 

That's this setting here:

![image](https://user-images.githubusercontent.com/19672699/143962307-6bac6c18-47cb-4896-8cd7-b5d8f06aa0d8.png)

**Comment by ma-sadeghi** [comment]
Could you please add the horizontal lines back for all the cells? It'd make long scripts broken up into cells much more organized/readable. Thanks! At least as a compromise, make it part of settings so it can be optionally turned on. Would really appreciate it :)

**Comment by RazorBaze** [comment]
> We use vscode's text decorations to put those lines in a python file: https://code.visualstudio.com/api/references/vscode-api#TextEditorDecorationType. You could look in our source where we create those decorations and add an option to add them for every cell.

@rchiodo, could you be a little more precise? Where is the 'source', what exact file there do you mean, and whether we can still hope to see this option implemented directly in VSCode?

**Comment by amunger** [comment]
@RazorBaze - cell decorators are added here https://github.com/microsoft/vscode-jupyter/blob/main/src/interactive-window/editor-integration/decorator.ts#L117

I don't know what's going on in that screenshot - it doesn't look like it's implementing what was requested in this issue

**Comment by RazorBaze** [comment]
@amunger oh yeah? Well, at least it did a better job than you for a whole year this thread had waited for a better clue
- assuming reading through your link doesn't require to be a part of developer team, or whatever.

**Comment by lbartell** [comment]
Coming here looking for this feature as well so commenting to say it would be extremely useful.  In the meantime, I'm using the hack @RazorBaze suggested (thanks!), i.e. just adding a bunch of extra/meaningless code lenses to visually distinguish the cells.

**Comment by ma-sadeghi** [comment]
> Thanks for the suggestion. We had this at one point but thought it too noisy. Should be easy to add an option to support this.

An argument for adding the borders back: If the border dividers make the script too noisy, then the user should not have really used the cell-based approach (`# %%`) in the first place. When writing a Python script with cell diviers, the user implicitly wants to chunk it up for readability, or at least that's how I see the cell-based approach. 

Anyway, would greatly appreciate it if you could add an option that adds border to all the cells. Also, would be useful for further readability to add another option to add background color to active cell. Thanks!

**Comment by DeepFlood** [comment]
I am looking for this feature as well, which is why I am commenting. It makes navigating through the code a breeze and helps to focus on the cell content as it is much easier to see the cell boundaries without having to search for them. I used the cell based approach in spyder all the time and  I am missing the structure the lines gave to the code.

**Comment by smojef** [comment]
Thanks @amunger for your contribution!  I can't wait to try this after all this time. 
 
And for those looking to reproduce the clean Spyder editor look, we can remove the inserted texts `Run Cell | Run Below | Debug Cell`.  In VS Code, go to `Preferences: Open User Settings`, then search for `jupyter code lens` and replace the **Commands** with a space.
![Visual Studio Code Screenshot](https://user-images.githubusercontent.com/43252951/229302543-4adfbdca-74f6-431e-b03c-b2c6493cc876.png)

There is a similar setting for debug mode, but it appears there is a typo (missing `n` in `Lens`):
![Visual Studio Code Screenshot2](https://user-images.githubusercontent.com/43252951/229303130-06fe14c7-330f-4328-ace4-364794beae82.png)

**Comment by ma-sadeghi** [comment]
@amunger Thanks so much for implementing this! You can't even imagine how much I appreciate it :)

**Comment by MSfinnet** [comment]
First things first: Thanks!

~~Mostlikely~~ Maybe it's just me but, I am still not getting those lines for all cells.

-Jupyter v2023.3.1000892223
-I added the empty space as suggested by @smojef 

Hoping not to look stupid here ... 🙈 
Any suggestions .. ? 

![image](https://user-images.githubusercontent.com/113613622/229436035-17f2fe93-312b-4ae9-b23b-0eb6f8ebcb58.png)

**Comment by ma-sadeghi** [comment]
> First things first: Thanks!
> 
> ~Mostlikely~ Maybe it's just me, but I am still not getting those lines for all cells.
> 
> -Jupyter v2023.3.1000892223 -I added the empty space as suggested by @smojef
> 
> Hoping not to look stupid here. 🙈 Any suggestions?
> 
> ![image](https://user-images.githubusercontent.com/113613622/229436035-17f2fe93-312b-4ae9-b23b-0eb6f8ebcb58.png)

I think you need to manually turn it on in user settings json:

"jupyter.interactiveWindow.cellMarker.decorateAllCells": true

Or something to this effect (I haven't yet tried myself).

**Comment by MSfinnet** [comment]
Ha! Thanks a lot my friend! 

I managed to track the problem down a bit, but I wasn't aware that I need to use _VS Code Insiders_ to use the pre-released version. So that helped a ton. Thanks @ma-sadeghi

**Comment by amunger** [comment]
Sorry, one more change going in that will alter the setting again https://github.com/microsoft/vscode-jupyter/pull/13252, which will go out with the next insiders update.
`"jupyter.interactiveWindow.cellMarker.decorateCells": "allCells"` instead of two different settings to control this.

@ma-sadeghi - it's based on a color theme `interactive.inactiveCodeBorder`, so it can be changed, though not through a simple setting. The [SO answer](https://stackoverflow.com/questions/61863572/how-to-replace-one-color-in-my-theme-vscode) here might help, but let me know if you have a better suggestion for what color it should be.

**Comment by amunger** [comment]
@smojef - If I understand what you're trying to do, there's also a setting just to turn off those injected code lenses: `"jupyter.interactiveWindow.codeLens.enable": false`

**Comment by smojef** [comment]
Thanks!  I was afraid it would disable the lines ;-)

**Comment by ma-sadeghi** [comment]
> @ma-sadeghi - it's based on a color theme `interactive.inactiveCodeBorder`, so it can be changed, though not through a simple setting. The [SO answer](https://stackoverflow.com/questions/61863572/how-to-replace-one-color-in-my-theme-vscode) here might help, but let me know if you have a better suggestion for what color it should be.

Thanks, I was able to change it using:

```json
	"workbench.colorCustomizations": {
	    "interactive.activeCodeBorder": "#00bc00",
		"interactive.inactiveCodeBorder": "#a5a5a5"
	}
```

Quick question: is there a reason you use a thinner border for the bottom of the cell? On a relevant note, I was wondering why don't we only add the border to the beginning of the cell?

**Comment by amunger** [comment]
That was just to differentiate the top of the cell from the bottom, but with all cells decorated, perhaps it would look fine to only decorate the top.

**Comment by ma-sadeghi** [comment]
> That was just to differentiate the top of the cell from the bottom, but with all cells decorated, perhaps it would look fine to only decorate the top.

Yeah, I think with all cells decorated, it'd even look nicer

**Comment by DeepFlood** [comment]
Thank you so much for the implementation! 

I think removing the bottom border would make it harder to identify the current cell which is indicated well at the moment. 
Instead of removing a border, maybe it would look nice if all borders were thin and only the current cell would be highlighted with thicker borders, a different colour or possibly a slightly different background.

But I think it depends on the preferences of each individual user, so it would be great if it were possible to self-adjust the thickness of the borders.

**Comment by ma-sadeghi** [comment]
@DeepFlood I like the idea of adjustable border thickness. 

Regarding the bottom border, if you use a different color for active/inactive borders (like dark blue vs. light blue), this problem goes away. Likewise, if optionally we're allowed to choose a background color for the active cell (like in Spyder), we no longer need the bottom border.

**Comment by ma-sadeghi** [comment]
@amunger Did you decide about only decorating the top of the cells? Thanks!

**Comment by amunger** [comment]
yes, I'll get that in while it's still in preview

**Comment by ma-sadeghi** [comment]
@amunger Thank you so much for hearing the users feedback! Would you also consider @DeepFlood's suggestion about optionally adding the ability to change the background color of the active cell? I've seen it in Spyder and it's great for even more visibility (of course it can be turned off)

Sorry, I don't mean to come across as demanding, just suggustions. Thanks again for your efforts!

**Comment by Diogo-Rossi** [comment]
Thanks @amunger , this feature is great.

I'd also like to give a feedback regarding the bottom border of the current cell:

> That was just to differentiate the top of the cell from the bottom, but with all cells decorated, perhaps it would look fine to only decorate the top.

I saw you made this modification in https://github.com/microsoft/vscode-jupyter/pull/13343#issue-1671945163

But, personally, I agree with @DeepFlood, and would like the option to keep the highlight of the bottom border,  

> I think removing the bottom border would make it harder to identify the current cell which is indicated well at the moment.

Displaying lines in every cell adds useful information, but keeping the previous information (the default `currentCell`, left screenshot) would also be good and maybe produce the same effect requested by @ma-sadeghi .

![image](https://github.com/microsoft/vscode-jupyter/assets/57204023/de9df6d8-b889-4a7a-aaec-dd98f78c232d)
