### ISSUE TITLE
VTK seems to break interactive window

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-jupyter#8371]
This example requires `pip install pymatgen vtk`. [VTK](https://pypi.org/project/vtk) is the Visualization Toolkit which offers [1st party Python bindings](https://kitware.github.io/vtk-examples/site/Python).

```py
# %%
from pymatgen.core import Structure
from pymatgen.vis.structure_vtk import StructureVis


# %%
struct = Structure(
    [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
    ["O", "H", "H"],
    [[0, 0, 0], [0.5, 0.5, 0], [0.5, 0, 0.5]],
)

# %%
struct_vis = StructureVis()
struct_vis.set_structure(struct)
struct_vis.show()


# %%
print("hello")
```

Two odd things here:
1. The interactive crystal structure created by `struct_vis.show()` opens in a new Python window, i.e. is not captured by VS Code Jupyter and inlined into the notebook. Screenshot below. ![Screen Shot 2021-11-26 at 12 52 14](https://user-images.githubusercontent.com/30958850/143585088-5247d37c-89e7-44b9-beb3-8ce99ca97307.png)
2. When closing the Python window, I get a beach ball spinning endlessly until I force close Python.app and from then on, my interactive window is broken. Running any cell (e.g. `print("hello")`) now throws

    ```
    Error: Session cannot generate requests
    at S.executeCodeCell (/Users/janosh/.vscode/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:66:301742)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at S.execute (/Users/janosh/.vscode/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:66:300721)
    ```

**Comment by rchiodo** [comment]
Thanks for the bug. This could be a number of things, but is similar to this issue here: #8273 The VTK package might be doing jupyter specific stuff.

**Comment by DonJayamanne** [comment]
@janosh 
I tried this in stable and insiders and seems to work as expected.
Tried in Jupyter too and the widget is displayed outside VS Code (not inlined), hence I'm getting the expected behaviour (i.e. exact same behavior i get in Jupyter)

![image](https://user-images.githubusercontent.com/1948812/143925400-7a7737c6-28ca-435e-8a2e-f78516a0d355.png)

**Comment by janosh** [comment]
Just tried again. Still same crash when I try to close interactive plot window.

Do you mean insiders of the extension or VS Code or both?

**Comment by DonJayamanne** [comment]
> Do you mean insiders of the extension or VS 

When you install vscode insiders, you'll automatically get the insiders version of the extension

**Comment by janosh** [comment]
@DonJayamanne Same problem in Insiders. I still get a beach ball when trying to close the Python plot window.

The error message when trying to run a cell after is a bit more helpful. Force closing the plot window seems to kill the whole Python kernel. If so, it's obvious why no more cells can be run.

![Screen Shot 2021-11-30 at 10 12 35](https://user-images.githubusercontent.com/30958850/144028165-1d3ec3b7-8b87-4fc0-8507-967db1dbbb58.png)

**Comment by DonJayamanne** [comment]
> Same problem in Insiders. I still get a beach ball when trying to close the Python plot window.

PLease could you provide the logs from the `Jupyter` output panel.
Looks like the kernel is dying. Also can you try this in Jupyter Notebook (outside vscode) and confirm the kernel doesn't die there either.

Basically I don't think this is a problem with VS Code, we don't kill the kernel, here it looks like the kernel died for some external reason.

**Comment by janosh** [comment]
@DonJayamanne You're right, same thing happening in Jupyter. Closing as unrelated to VS Code.
