### ISSUE TITLE
Show sent selection code cell input expanded

### ISSUE THREAD

**Issue by meandmymind** [microsoft/vscode-jupyter#8372]
Hello!

I'm using "Send selection to interactive jupyter window" feature.

Currently sent cell input is shown shrinked [1] [2]

I want a feature to allow showing it expanded by default as in [3]. Currently I have to toggle some small dots in cell, it's inconvenient for me.

### [1]

<img width="384" alt="image" src="https://user-images.githubusercontent.com/24773652/143584792-11de3944-9d3f-453d-a9fe-d588a721f531.png">

### [2]
<img width="316" alt="image" src="https://user-images.githubusercontent.com/24773652/143584879-0b84efb6-5b3e-4262-b5c3-b3c97916a72d.png">

### [3]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/24773652/143585753-9a8aaaed-450a-4b14-b397-19ef3906cde0.png">

**Comment by rchiodo** [comment]
Thanks for the bug. There's a setting I believe for what you're asking for:

![image](https://user-images.githubusercontent.com/19672699/143917575-f229e5b1-0b0a-4c49-8d7c-14c95431ca10.png)

If you uncheck that, it should always be expanded.

**Comment by meandmymind** [comment]
@rchiodo thank you it worked as I wanted!
