### ISSUE TITLE
Doesn't seem to recognize ipynb | Missing run cell, kernel selection

### ISSUE THREAD

**Issue by StaticKling** [microsoft/vscode-jupyter#8375]
## Environment data

-   Version: 1.62.3 (user setup)
-   Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
-   Date: 2021-11-17T08:11:14.551Z
-   Electron: 13.5.2
-   Chrome: 91.0.4472.164
-   Node.js: 14.16.0
-   V8: 9.1.269.39-electron.0
-   OS: Windows_NT x64 10.0.22000

-   Jupyter Extension version: v2021.10.1101450599
-   Python Extension version: v2021.11.1422169775
-   OS: Windows 11
-   Python and/or Anaconda version: 3.7
-   Type of virtual environment used: Conda
-   Jupyter server running: Local | Remote | Local

## Expected behaviour

Used to give me the option to run cells but the triangle is missing from the little menu.  

![image](https://user-images.githubusercontent.com/44011554/143772269-a62b1414-9434-442d-9d7c-b6c4a45f8742.png)

The lower right jupyter kernel is missing so I can't even select a jupyter notebook kernel.

![image](https://user-images.githubusercontent.com/44011554/143772227-c03c0a6e-fd77-4280-b423-a6f233b4f0b3.png)

## Actual behaviour

There is nothing on the UI that helps run the notebook or helps set up the Jupyter Notebook server to run the notebook.  There used to be a menu in the lower right that let me select which running kernel to connect to, but that is gone and I cannot figure out how to get it back.

![image](https://user-images.githubusercontent.com/44011554/143772242-c31d135e-78ec-4c72-99e6-4e1fa9deb06e.png)

## Steps to reproduce:

1. Open any ipynb using any method and there are no menus or buttons to run the notebook.  Followed the installation and setup steps and still nothing.

**Comment by StaticKling** [comment]
Reverting to v2021.10.1001414422  brings the menus back.
![image](https://user-images.githubusercontent.com/44011554/143773400-e8c487b9-1059-47ac-9de0-c0702b0768d4.png)
![image](https://user-images.githubusercontent.com/44011554/143773407-5db6e56e-0b17-42f3-b28c-3b6f732e68f7.png)
![image](https://user-images.githubusercontent.com/44011554/143773416-1757c5f8-e843-408c-bbb0-9e3bacc24686.png)

**Comment by DonJayamanne** [comment]
Please could you install the latest version and provide the output from the Jupyter output panel and a screenshot of the unsupported message.

**Comment by StaticKling** [comment]
Hi Don, 

Sorry for the delay-  I am not sure where that UNSUPPORTED banner came from and could have been some crossing of Visual Studio code that was from Anaconda install messing with the local VS Code install. I haven't been able to get it to show again.  

Reverting the extension to v2021.10.1001414422 and then upgrading from there to v2021.10.1101450599 worked for solving my issue though so I can close this ticket.
