### ISSUE TITLE
Code color and syntax check display error in jupyter

### ISSUE THREAD

**Issue by brynn-code** [microsoft/vscode-jupyter#8377]
## Environment data

-   VS Code version: 1.62.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: windows
-   Python and/or Anaconda version: 3.7.11
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local 

## Expected behaviour

right color and syntax check

## Actual behaviour

wrong color and syntax check display, but can run as usual.

![647be49c391e128005b9d0dbf940f61](https://user-images.githubusercontent.com/24237253/143852637-3b95f655-a419-46a0-84e8-2084a8b5a500.png)
![8a3a6e2c7ad85534425ec81a31b3936](https://user-images.githubusercontent.com/24237253/143852664-5d7495c9-a22a-4c51-8cb6-c7e03eaecea2.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. open the node book
2. open notebook source in vim(bash)
3. modify the kernel name  or something else
4. :wq close and save
5. return to vs code

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
@brynn-code Looks like the repro steps requires editing the ipynb from source.
Please could you let me know if you can repro this when eidting this file manully in VS Code using the notebook editor.

* Please could you provide the original IPYNB file
* & also the updated IPYNB file, this way I can try to edit this my self manually.

**Comment by rchiodo** [comment]
Sorry read this wrong in triage. If this only repros with an external edit, it's not the issue I thought it was.

**Comment by brynn-code** [comment]
Yes, I did modified the source, I change the 'name' in 'kernelspec' and python 'version' in metadata.

And when I follow the same step try again today, the bug can't be repro.
I think this may be a transient issue, you may close the bug since I didn't find a stable way to repro it.
I'll open a new issue if necessary (if there is a way to repro the bug)

**Comment by rchiodo** [comment]
Thanks for trying.

**Comment by BlueHawk77** [comment]
I have this exact bug right now. Is it solved ?

**Comment by BlueHawk77** [comment]
I have a similar problem now. Has this issue been solved ?
