### ISSUE TITLE
Test Plan : Notebook editing and intellisense

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8379]
Refs: #1510

- [x] anyOS @rzhao271
- [x] anyOS @brettcannon

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%238379%0A%0A&assignees=rchiodo)

---

Intellisense in notebooks is handled by concatenating all of the cells in a notebook into a single virtual python file. This code was entirely rewritten for this release so we'd like to test all sorts of notebooks to make sure intellisense works.

Before testing, set these two settings:

```json
    "notebook-intellisense.logLevel": "Trace",
    "notebook-intellisense.trace.server.verbosity": "Verbose",
```

These settings will generate a  lot of output to trace what might go wrong. Output should end up in an output tab like so:

![image](https://user-images.githubusercontent.com/19672699/143918519-7cdadc7b-ebc2-41d0-94de-4754ca62be2e.png)

Where the name of the output tab is related to the 'kernel' you're using for your notebook.

Test steps:

1. Open random notebooks. Verify semantic colorization of the code in the notebook looks correct
2. Add errors to notebooks by editing them or by moving cells around (for example declare a variable in first cell, use in second cell, then switch cells around, variable should show an error when used before defined)
3. Delete cells, delete code, and make sure edits are having the appropriate effects.

If you get any errors, please:
- Try to reproduce a second time
- As soon as you reproduce capture the contents of the custom output and include it in the bug you file.

**Comment by lszomoru** [comment]
@rchiodo, could you please confirm that this is a valid `testplan-item`? I am asking as in the past I remember that there were some items that got incorrectly assigned. Reading the description of this test plan item, it feel that this should probably have a higher complexity:

>  Intellisense in notebooks is handled by concatenating all of the cells in a notebook into a single virtual python file. This code was entirely rewritten for this release so we'd like to test all sorts of notebooks to make sure intellisense works.

> Open random notebooks. Verify semantic colorization of the code in the notebook looks correct

**Comment by rchiodo** [comment]
@lszomoru yes it's valid. Not sure why it wouldn't be? To test you simply need to open a jupyter notebook and edit some cells. No running necessary.

Maybe setting up python is the complex part (if you've never done that before)?

**Comment by rchiodo** [comment]
There's a fix coming for this issue in the next half hour or so. If you can hold off testing till it goes through that would be nice (we found some issues over the weekend)

I'll update the issue when I push the new drop of the Jupyter extension.

**Comment by rchiodo** [comment]
New build is done. Should be this version here:

Name: Jupyter
Id: ms-toolsai.jupyter
Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.
Version: 2021.11.1001522160
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

**Comment by brettcannon** [comment]
Thanks to this I found some dead imports in one of my notebooks! 😊
