### ISSUE TITLE
Changing kernel in notebook during running a cell doesn't run the cell

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8381]
1. Create new notebook
2. Pick kernel that doesn't have IPykernel installed
3. Run a cell
4. Pick 'change kernel' on dialog that comes up

Expected:
Cell runs

Actual:
Kernel changes but nothing else happens.

**Comment by DonJayamanne** [comment]
We'll need to keep track of all the queued cells and re-run then.
I agree, the current behavior is not the best.

**Comment by DonJayamanne** [comment]
Taking this as part of kernel refactoring, etc.
We'll need somethign similar for when selcting Jupyter Interpreter as well.

**Comment by rchiodo** [comment]
I don't believe this is working yet as this is the thing I'm currently fixing. Closing as dupe of #8817

**Comment by DonJayamanne** [comment]
this issue only focused on notebook.

**Comment by DonJayamanne** [comment]
i knew iw was not done
