### ISSUE TITLE
Remove `Connecting to xxxx` from IW when changing kernels

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8384]
* Run a cell
* When you get a promtp to select another kernel, select one with ipykernel
* Cell runs

However you still end up with the message `Connecting to xyz`, which is confusing.
Why are we still trying to connect to `xyz` when I've changed the kernel?

**Comment by rebornix** [comment]
> Why are we still trying to connect to xyz when I've changed the kernel?

Isn't this the same as initial startup of the iw? The IW is opened, kernel is auto selected, but it will still say it's connecting to `xyz`. The message indicates that the extension is launching the underling kernel and fetching specs/help info of the kernel.

**Comment by DonJayamanne** [comment]
* Run a cell for kernel `xyz`
* When you get a prompt to select another kernel `abc`, select one with ipykernel
* Cell runs

However you still end up with the message `Connecting to xyz`, which is confusing.
I think with the refactoring in Dec this may have been fixed.
Let me test this again.

**Comment by DonJayamanne** [comment]
Ideally we should remove `Connecting to Python 3.8.12` and replace that with `Connecting to golden_scenario...` the new kernel.
Also looks like there's a bug now, we don't run the cell at all. THe connecting message comes up after the cell, which is wrong.
Will file a separate issue for that.
