### ISSUE TITLE
Interactive pane broken

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#8385]
Issue Type: <b>Bug</b>

With `"jupyter.interactiveWindowMode": "single"` multiple interactive panes insist on opening up. Also, when inputting code in the directly in the interactive pane, the window will jump to another separate interactive pane and the number of the original interactive pane that the code was executed from shown in the interactive pane tab name will auto increment by one.  Do the same thing again, and the same number in the tab name will decrease by one.  keep doing this over and over, and it will just cycle between the two number.  

Something is severely broken. 

Also, repeated pop ups saying `Failed to request creation of interactive window from VS Code.`  Not for all Interactive panes though, only approximately half of the Interactive panes.

None of the Interactive panes work.  I just get bounced around to different Interactive panes that pop up and change their number every time I execute code from a file or directly from an Interactive pane. 

I have tried with localhost python instance, and also from remote Jupyter servers.  Python on the localhost computer and Jupyter labs or notebooks on the remote server run without issue.  It is only VS Code that is having the problems.

Extension version: 2021.10.1101450599
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.07GB free)|
|Process Argv|--crash-reporter-id f652528b-5678-4b12-9ca0-3de6b1e1135f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593:30376534
vssld246cf:30401891
vscexrecpromptc:30404946
vscop804cf:30404767
vscop940:30404999

```

</details>

**Comment by clayms** [comment]
Not sure what happened during the last VS Code update, but it broke a lot.  

Uninstalled all MS Python and Jupyter extensions, then re-installed.  Seems to have fixed the issue ¯\_(ツ)_/¯

**Comment by rchiodo** [comment]
Thanks for retrying. Maybe the update only partially updated. We have seen cases where it doesn't download fully for some reason.
