### ISSUE TITLE
Notebook intellisense shows squiggles when end of cell lines up with next

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8388]
See the picture:

![image](https://user-images.githubusercontent.com/19672699/143971592-4af8ef2d-96a2-4701-96fa-8965109fdb3a.png)

The red squiggle on the second 'def' shouldn't happen as this is not really a concat document.

We can fix this by injecting a hidden '\n' in between cells in the custom concat document.

**Comment by rchiodo** [comment]
Might be able to insert a dummy line between cells.

**Comment by IanMatthewHuff** [comment]
Looks good now with current bits:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/812783/200043142-9754c8f5-37dc-4c6a-a115-a17852e9bfdd.png">
