### ISSUE TITLE
AttributeError listed with double punctuation

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-jupyter#8392]
Testing #8357

The attribute error is correctly listed as "Kaboom" but has both a comma and period at the end, in both the toast and after the cell:

![image](https://user-images.githubusercontent.com/25310137/144102416-0b09ca2b-5f26-45dd-979a-c1207a8a7d25.png)

![image](https://user-images.githubusercontent.com/25310137/144102436-0fc9c2b5-5e30-43d7-a656-93949d0e9148.png)

I would've expected `AttributeError: Kaboom.` (or some variation with one or no punctuation) rather than `AttributeError: Kaboom,.`

**Comment by DonJayamanne** [comment]
**Testing**

* To verify this follow the steps in #8357

**Comment by bamurtaugh** [comment]
LGTM:

![image](https://user-images.githubusercontent.com/25310137/144306695-c67e3b85-f4c2-4156-86b3-d87d95a7d5bd.png)

![image](https://user-images.githubusercontent.com/25310137/144306765-4f1507a2-8a45-4c93-b159-ba7973d5d5a4.png)
