### ISSUE TITLE
Last cell doesn't seem to be highlighted properly

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-jupyter#8397]
Testing #8379

1. Open the notebook from [notebook.zip](https://github.com/microsoft/vscode-jupyter/files/7628553/notebook.zip)
2. Scroll down
3. :bug: Even after the other cells colour in, such as the cell with `import time`, the last cell doesn't seem to be highlighted properly

**Comment by rchiodo** [comment]
Thanks. I can repro.

Looks fine in a normal python file. Not sure why it's messed up here.

Normal python:

![image](https://user-images.githubusercontent.com/19672699/144121496-2eccc06f-1bd7-465f-ab65-c90826381f1a.png)

Notebook:

![image](https://user-images.githubusercontent.com/19672699/144121531-099513f3-192a-4aa8-afab-8d4d4e2ee093.png)

**Comment by rchiodo** [comment]
Range request is wrong. It sends a request for line 9. That cell should be line 28!

**Comment by rzhao271** [comment]
Interesting case. I also confirmed that if I swap the last two cells, scroll up, and then scroll back down, it's the last few lines starting with `e` that aren't highlighted properly.

**Comment by rchiodo** [comment]
It was an off by one error. 🐛 . Should be fixed once this goes through: https://github.com/microsoft/vscode-jupyter-lsp-middleware/pull/28

**Comment by rchiodo** [comment]
This should have been fixed in https://github.com/microsoft/vscode-jupyter/commit/f72607f7a791355e2d70de7e10df6d4080e30f92
