### ISSUE TITLE
IPyKernel not installed into interpreter Python 1.62.3

### ISSUE THREAD

**Issue by DeklynHunt** [microsoft/vscode-jupyter#8404]
had a small problem, manually installed by hitting the install button...
![image](https://user-images.githubusercontent.com/93553350/144157814-9d1de932-06b0-4f8a-9f21-6447b674ae6c.png)

![image](https://user-images.githubusercontent.com/93553350/144157681-d5ea8bea-9d0a-4257-9485-2dc5927cc256.png)

![image](https://user-images.githubusercontent.com/93553350/144158157-d85ee37d-3df1-4a68-99b9-0c7fd311a68f.png)

![image](https://user-images.githubusercontent.com/93553350/144158693-5aa6ea18-a957-47ed-aa13-3cc61637330d.png)

Edition	Windows 10 Pro
Version	21H1
Installed on	‎3/‎12/‎2021
OS build	19043.1348
Experience	Windows Feature Experience Pack 120.2212.3920.0

far as i know it will be fine till i find another problem, sorry to be a bother :/ (im new and getting situated...)
if you need any other information than my vague input...well...you know

## Environment data

-   VS Code version: Python 1.62.3
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: python 3.10.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the bug. Can you include the contents of the 'jupyter' output tab? It should show what's causing the error.

**Comment by rchiodo** [comment]
Actually I'm not sure there's even an error? It looks like the install worked. Were you able to run a cell?

**Comment by DeklynHunt** [comment]
> Actually I'm not sure there's even an error? It looks like the install worked. Were you able to run a cell?

yeah, it seems like the install works just fine, thank you for your time and reply

**Comment by rchiodo** [comment]
Thanks for replying.

**Comment by DonJayamanne** [comment]
@rchiodo I'm gong to re-open this, so we don't log the messages as errors. Basically these are handled, hence logging them into console as errors only adds to the confusion.
Changing this to debt

**TODO:** 
* Stop logging ipykernel not found as errors, instead log them as warnings or info.
