### ISSUE TITLE
Display(Sheet)..?

### ISSUE THREAD

**Issue by khatriharsh** [microsoft/vscode-jupyter#8405]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the bug. We need some more information to understand what your issue is.

Can you provide:
1. A description of the problem
2. A sample of code that repros the problem
3. The contents of your 'jupyter' output tab.

**Comment by rchiodo** [comment]
Closing as no info provided. Please reopen if you can provide the necessary information.
