### ISSUE TITLE
Error message not displayed in the output

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-jupyter#8406]
Testing #8357

The error was not shown in the cell's output when using an untitled notebook:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/9205389/144213892-a09a7fc2-e15d-4a0a-be7a-d6f168480441.png">

It was shown after I saved the notebook and ran it again.

**Comment by chrmarti** [comment]
I was using the Python 3 dev container (using the Python 3 definition in Remote-Containers). I cannot reproduce it anymore.

**Comment by DonJayamanne** [comment]
Let's close this for now.
