### ISSUE TITLE
Syntax colorization for Python is incorrect in Notebookcells when no folder or active interpreter

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8409]
* Latest Insiders
* Pylance 2021.11.2

**See below (latest insiders):** (this used to work in Insiders, see screenshots here https://github.com/microsoft/vscode-jupyter/issues/8374) 

![image](https://user-images.githubusercontent.com/1948812/144287434-666c0d50-baa6-4c0d-b9d7-2ae79876c412.png)

**Here's a screenshot from the stable version (hence a regression):**
![image](https://user-images.githubusercontent.com/1948812/144287741-216ca4fa-369c-4b18-aea7-49ce8952d328.png)

**Comment by rchiodo** [comment]
This works fine for me. 

![image](https://user-images.githubusercontent.com/19672699/144294891-534f4609-aea0-4b43-81d4-389a6f835a65.png)


Can you set this?

```json
    "notebook-intellisense.trace.server.verbosity": "Verbose",
    "notebook-intellisense.logLevel": "Trace",
```

And then copy the output of the pylance logging for the matching kernel?

**Comment by DonJayamanne** [comment]
Closing as per discussion

**Comment by rchiodo** [comment]
I can repro this if there's no folder open (or no active interpreter set)
