### ISSUE TITLE
Notebook editor changes metadata on save

### ISSUE THREAD

**Issue by lemccarthy** [microsoft/vscode-jupyter#8412]
When working with a project that has source-controlled ipynb files, I can't currently use vscode, because it keeps making these unnanounced, automatic changes to the metadata every time I save.

## Environment data

-   VS Code version: 1.53.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.2.603412351
-   Python Extension version (available under the Extensions sidebar): v2021.2.633441544
-   OS (Windows | Mac | Linux distro) and version: OSX 11.6
-   Python and/or Anaconda version: 3.6.13
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Jupyter server running: Local

## Expected behaviour

When saving a .ipynb file, the metadata are not altered.

## Actual behaviour

The key "display_name" automatically writes the name of the VENV used while editing the notebook e.g.
```
"display_name": "Python 3.5.13 64-bit ('my-venv-name-here': virtualenv)",
```

a new key is added called `metadata` with a child key `interpreter` with a child key `hash`
```
"metadata":  {
  "interpreter": {
    "hash" : "hashvalue"
  }
}
```

and the key "language" is deleted from the metadata.

## Steps to reproduce:

1. Create an .ipynb file with a metadata section including the keys "display_name" and "language".
2. Save the file.

**Comment by rchiodo** [comment]
Thanks for the bug. 

This should no longer be a problem. You're using a older version of VS code that this has since been fixed in.
