### ISSUE TITLE
JustMyCode = False does not work when debugging a Jupyter Notebook Cell

### ISSUE THREAD

**Issue by flyforward2016** [microsoft/vscode-jupyter#8413]
Issue Type: <b>Bug</b>

Following the great feature for VSCode to debug a cell in the Jupyte notebook (https://code.visualstudio.com/docs/datascience/jupyter-notebooks), I was able to run it to step through my code. However, it does not step into XGboost library even though I set the JustMyCode to False as below. The debug Concole was outputint " Frame skipped from debugging during step-in.
Note: may have been skipped because of "justMyCode" option (default == true). Try setting "justMyCode": false in the debug configuration (e.g., launch.json).
"
This is a follow up question of this https://github.com/microsoft/debugpy/issues/795, which has been succesfully resolved by configure the setting properly. Please let me know if additional configuration is required. Thanks in advance. 

 "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false
        },
        {
            "name": "Python: Debug Test",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "purpose": ["debug-test"],
            "console": "integratedTerminal",
            "justMyCode": false
        }
    ]

Extension version: 2021.10.1101450599
VS Code version: Code 1.62.3 (Universal) (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 20.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 19e43964-94c8-45bf-826d-09ace1e20d72|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by karthiknadig** [comment]
Have you tried disabling this setting:
![image](https://user-images.githubusercontent.com/3840081/144308183-a4b78a77-b6d4-4889-8ced-f6b77bcc71d8.png)

**Comment by rchiodo** [comment]
That setting isn't actually applied during cell debugging. That's from interactive window debugging. 

We don't currently support just my code on notebook cells. See this issue here:
https://github.com/microsoft/vscode-jupyter/issues/8146

**Comment by flyforward2016** [comment]
Hi Karthik,

Thanks for your response. I have tried this (uncheck this) but it didn't
work to debug into the Xgboost library.

Best,

Bin

**Comment by tnielens** [comment]
Same here, I expected the vscode jupyter "Debug Just My Code" setting to apply to cell debugging.

**Comment by matangover** [comment]
> That setting isn't actually applied during cell debugging. That's from interactive window debugging.

Could you please rename that setting? The name is misleading

**Comment by 6Roy** [comment]
> 您是否尝试过禁用此设置： ![图像](https://user-images.githubusercontent.com/3840081/144308183-a4b78a77-b6d4-4889-8ced-f6b77bcc71d8.png)

请问这个在哪啊

**Comment by xingener** [comment]
> > 您是否尝试过禁用此设置： ![图像](https://user-images.githubusercontent.com/3840081/144308183-a4b78a77-b6d4-4889-8ced-f6b77bcc71d8.png)
> 
> 请问这个在哪啊

@6Roy 在设置里，搜索 debug jupyter 可以很容易看到
