### ISSUE TITLE
When failing to restart kernel display error message in first available cell

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8418]
Today we display error mesage (messagebox), but not in cell output.
Question: Do we display message in cell output.

**Suggestions**
* Identify cell in view (based on selection, if not available, first cell)

* Q. Insert output at the top of existing output
* Q. Or replace output

**Comment by rchiodo** [comment]
Global message.

If cell runs it will put up a message anyway.

**Comment by DonJayamanne** [comment]
There haven't been any upvotes nor complaints about the UX related to restart failures, hence closing this issue
