### ISSUE TITLE
With non-raw kernels we don't prompt users to select an interpreter with Jupyter, instead we just display a quick pick

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8421]
In non-raw cases, when attempting to run a cell, we just display a quick pick.
The problem is, as a user I have absolutely no idea why I'm presented with a quick pick.
There's no error message nothing, just a quick pick.

This is very confusing specially when we have already selected a kernel

Suggestion: DIsplay message & have a button `Select Interpreter` or `Install Jupyter into xxx interpreter`.

**Comment by DonJayamanne** [comment]
This seems to be fixed now, we have a modal dialog with a good error message.
Closing for verification

**Comment by rchiodo** [comment]
/verified?

It displays this if the there is no kernel selected, but this is what we wanted. 

![image](https://user-images.githubusercontent.com/19672699/155772358-8830847b-2bb1-4ae1-bf41-6294f92ba561.png)

However if the kernel selected doesn't have ipykernel, we ask for it.
