### ISSUE TITLE
Running a cell in IW does nothing if no active Python interpreter & using non-raw (without a Jupyter interpreter selected)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8422]
* Ensure you are using non-raw (Jupyter)
* Ensure Jupyter interpreter is not selected (clean slate - new user)
* Ensure you do not have an active interpreter selected
* Run a cell , we open an empty IW but thats it, cells do not run, no prompts to select interpreter, no prompts to install ipykernel, no messages
No messages about any progress indicators either.

**Comment by DonJayamanne** [comment]
I ran into this today as well, and spent a few minutes trying to figure out what i did wrong.

**Comment by amunger** [comment]
we now provide an info message in this case
