### ISSUE TITLE
Not prompted to install Pandas when viewing variables from Debugger variable viewer (IW)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8423]
When testing #7295

* Debug a cell in IW
* Right click on a variable to view in Dataframe viewer
* I get an ugly error message about missing Pandas package

Should be prompted to install pandas

![image](https://user-images.githubusercontent.com/1948812/144329887-379bba20-4e81-484d-8c35-5ffc79410c25.png)

**Comment by IanMatthewHuff** [comment]
Verify steps:

Create a python environment without pandas
Debug a .py file with a simple list `x = [1, 2, 3]`
Right click x variable in the variables list
Click "Show in Data Viewer"
You should get prompted to install pandas in the env

**Comment by joyceerhl** [comment]
Only the 'Show Variable in Data Viewer' flow from the variable explorer is guarded, but if I right click on the variable in the debug variables panel and select 'View Value in Data Viewer', I am not prompted to install pandas:
![image](https://user-images.githubusercontent.com/30305945/155748593-60edfc95-2cfa-40e1-a60f-36ebaa591938.png)

![image](https://user-images.githubusercontent.com/30305945/155748331-a46aa20d-2f22-482f-bee0-63039a83bf9e.png)

**Comment by IanMatthewHuff** [comment]
@joyceerhl Can you snag the log quick? Something must be up between our configurations:

I trigger the same way:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/812783/155764074-56eb3cae-fc03-467f-b62f-ea3f4f3bda0f.png">

And get this prompt:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/812783/155764120-6c75d986-a617-400a-b168-ddf7d7884966.png">

**Comment by IanMatthewHuff** [comment]
@joyceerhl Ahh, nevermind I think that I found it. I guarded this from the non-Jupyter / non-IW python file debugging scenario. I wasn't using IW debug cell. I think that's the issue.

**Comment by joyceerhl** [comment]
I do get prompted now: 
![image](https://user-images.githubusercontent.com/30305945/156056110-366974ba-09f3-4ff7-a8f5-20f53f954421.png)
