### ISSUE TITLE
Interactive Window has wrong suggested kernel listed.

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#8424]
I might need to look into this myself if it's specific to my kernel setup.

But I'm running the interactive window with .debugEnv as my python interpreter. .debugEnv is correctly listed as my active controller. But when I click on the controller selector a different (unrelated) venv is the suggested kernel.

![image](https://user-images.githubusercontent.com/812783/144330753-ab062871-03e5-457d-9d85-b3ece91f9fa7.png)

The actual selected kernel is not suggested and is down at the bottom of the list:
![image](https://user-images.githubusercontent.com/812783/144330959-490a62ea-b981-445e-8c6b-205311cddfaf.png)

Tricky to pin down a repro on this. I see the same issue in stable VS Code so I don't believe that it's a recent regression.

**Comment by namespace-Pt** [comment]
@rchiodo Came across the same problem when used with RemoteSSH. The drop-down list only displays kernels on my local machine instead of those on the remote server. Even worse, I cannot find a way to manually designate a kernel location.

**Comment by rchiodo** [comment]
> @rchiodo Came across the same problem when used with RemoteSSH. The drop-down list only displays kernels on my local machine instead of those on the remote server. Even worse, I cannot find a way to manually designate a kernel location.

Thanks for the bug, I opened a new issue: #8483

**Comment by IanMatthewHuff** [comment]
Still repros for me, and seems important, so taking a look quick for January milestone.

**Comment by roblourens** [comment]
In my case, the C# kernel is always suggested, even though I am using a python venv

![image](https://user-images.githubusercontent.com/323878/151850835-1de107a1-790e-4f6d-8299-163afad0f758.png)

Are there some other steps?

**Comment by IanMatthewHuff** [comment]
@roblourens Your verification looks correct to me. I currently see the python env that I started the IW with always being the selected env. Sounds like it's not the same for you. If you are still seeing this could you attach the Jupyter output log and reopen? I can investigate.
