### ISSUE TITLE
Could we provide a setting to change the location of the `working` status of python interactivate?

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/vscode-jupyter#8428]
In the recent release, the location of the `working` status of python interactive has been moved.

![z1Bao](https://user-images.githubusercontent.com/21306413/144391172-b23bfad0-7421-4165-8a03-f726e2342744.png)

Sometimes it's frustrating because if the Python code is long, you have to navigate to the top of the section to see that the script working status. So, could we provide a configuration for it? Thanks.

**Comment by IanMatthewHuff** [comment]
Thanks for the suggestion.

**Comment by rchiodo** [comment]
Status of cells should be more visible now.
