### ISSUE TITLE
VS very slow with Jupyter extension and refuse to save

### ISSUE THREAD

**Issue by athy9193** [microsoft/vscode-jupyter#8429]
Issue Type: <b>Bug</b>

When I use Jupyter Extension on a remote server, every single code cells takes much longer to finish and the screen frozen after while, I cannot save the work I have made. Really frustrated.

Extension version: 2021.10.1101450599
VS Code version: Code 1.62.3 (Universal) (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 4.14.243-185.433.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (21.10GB free)|
|Process Argv|--crash-reporter-id 1b61dbf4-b0fb-43c9-8681-c713b6a06d58|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev.nettwerk.com|
|OS|Linux x64 4.14.243-185.433.amzn2.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (2 x 2399)|
|Memory (System)|3.85GB (0.10GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
vscexrecpromptc:30404946
vscop804:30404766
vscop453:30404998
vsrem710cf:30405999

```

</details>

**Comment by IanMatthewHuff** [comment]
Thanks for the report on this. To clarify something, are you using VS Code's Remote extensions to connect to the remote machine? Or are you using the "Jupyter: Specify local or remote Jupyter server for connections" to connect to a Jupyter instance already running on a remote machine? 

Also if you can repro this scenario could you save out the logs from the "Output: Jupyter" window and paste them in a comment here? That has extra diagnostic information that would be helpful when looking at this.

**Comment by IanMatthewHuff** [comment]
Closing on no reply.
