### ISSUE TITLE
semantic highlight in notebook is disordered

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-jupyter#8430]
版本: 1.63.0-insider (system setup)
提交: 0cc0904c565399781defa830facf43141db8b6f3
日期: 2021-12-01T05:14:47.986Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22504

名称: Jupyter
ID: ms-toolsai.jupyter
说明: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.
版本: 2021.11.1001524965
发布者: Microsoft
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/1876302/144333182-ce64675a-28d7-4cb8-b095-8cbd6c261f54.png)

**Comment by sdfordham** [comment]
## Environment data

  VS Code version: 1.62.3
  Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
  Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
  OS (Windows | Mac | Linux distro) and version: Microsoft Windows 10 Pro
  Python and/or Anaconda version: 3.9.6
  Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
  Jupyter server running: Local

![github-issue](https://user-images.githubusercontent.com/17852477/144884191-27beb0b8-5a81-4a83-90f5-1d787d48354b.jpg)

- Notebook is fine when first opened then after time this starts to happen.
- Opening and closing the notebook doesn't fix it.
- Opening and closing VSCode _does_ fix this.

**Comment by rchiodo** [comment]
This should be fixed if you have the latest of everything:
- VS code - VS code insiders Version: 1.63.0-insider (user setup) Commit: d09289a2b6dd0e56b2a264a8e9380685498e10d6
- Jupyter Extension - 2021.11.1001532801
- Python Extension - 2021.12.1522449417-dev
- Pylance Extension - 2021.12.0

![image](https://user-images.githubusercontent.com/19672699/144890426-211c0159-e47e-4579-9097-9c6b572bd7fe.png)

**Comment by rchiodo** [comment]
With Pylance and Jupyter being the parts that need to be the latest.

**Comment by sdfordham** [comment]
They are both latest for me according to Extensions tab in vscode, Pylance is v2021.12.0 and Jupyter v2021.10.1101450599.

The version you've listed does not seem to be available, how to get it?

![image](https://user-images.githubusercontent.com/17852477/145024792-c60f654b-b7c3-44e9-8728-46527b4d0641.png)

**Comment by rchiodo** [comment]
The latest version of Jupyter only installs on VS code insiders.
