### ISSUE TITLE
First cell in a notebook has invalid colorization

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8437]
![image](https://user-images.githubusercontent.com/19672699/144504937-ebb6e811-88a3-40be-8562-f734b32b53b1.png)

Caused by not filtering out the hidden lines during edits.

**Comment by meganrogge** [comment]
was this always happening @rchiodo ? how do I check that it's been fixed?

**Comment by rchiodo** [comment]
Sorry repro steps:

1. Add something to your ```jupyter.runStartupCommands```. Something like ```x = 11111```. This will get 'prepended' to the behind the scenes concatenated file we use for intellisense.
2. Open a notebook
3. Type something in the first cell
4. Verify colorization is correct.

**Comment by rchiodo** [comment]
And this doesn't repro in stable. Bug caused in this release.
