### ISSUE TITLE
some error debugConfirguration when I try to debug and about launch.json

### ISSUE THREAD

**Issue by nyck33** [microsoft/vscode-jupyter#8453]
it locked my Ubuntu so had to alt prtscreen REISUB, could not even log out.

is this a known error?

**Comment by amunger** [comment]
Did this only happen once or does it occur regularly?
Can you provide some clear repro steps? I'm not sure what you mean by "debug and about".
Do you have the error message that you received?
Can you provide the Jupyter logs from the output window if this occurs again?

**Comment by amunger** [comment]
we need more information to investigate, closing for now
