### ISSUE TITLE
Expose export interactive as notebook command in untitled IWs

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-jupyter#8455]
Based off of https://github.com/microsoft/vscode-jupyter/issues/7947

1. Close all open editors and reload the window within a trusted workspace
2. Create an IW
3. Type in and run some cells
4. Open the command prompt, and try to find the jupyter export command to export the content as a notebook
5. :bug: The command isn't there

**Comment by amunger** [comment]
It looks like the command only shows up after giving focus to the interactive window. Once the IW has had focus at some point, it will consistently show.

**Comment by rchiodo** [comment]
The IW needs focus otherwise the command is ambiguous.

**Comment by rzhao271** [comment]
Clarified the repro steps. I'm still seeing the issue:

![Demo](https://user-images.githubusercontent.com/7199958/144929569-60bc5b61-7b75-4715-b3a8-3f2b722f554b.gif)

**Comment by rchiodo** [comment]
Hmm, not reproing for me. Weird. Some sort of 'when' clause problem?

**Comment by rchiodo** [comment]
Repros for me if you create the interactive window with a command instead of with a code lens. Export may be checking the started file to get the interpreter to use.
