### ISSUE TITLE
Move installation of all DS packages into Jupyter Extension

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8457]
* We're already install ipykernel for windows PCs when users have shells other than Powershell/Command Prompt
* We've extended this to now install ipykernel ourselves always when on Windows PC (global & virtual environments)

**Suggestion**
* Install ipykernel for conda enviroments ourselves
	* We can actiavte the env and run `conda install ipykernel` ourselves (we have the location for conda, etc)
* Instlal ipyernel for other environmetns (pipenv, poetry, etc) ourselves
	* We can activate the env using Python extension, and run the pip installer

This should fix a number of ipykernel installation issues as well.

**Benefits**
* More users will be unblocked 
* We have a better idea/understanding of when things go wrong
	* Today when things go wrong, we have absolutely no idea in Python ext, because we run the command in the terminal and we don't know what goes on in the terminal
	* (also there's no need to run these in a terminal)
* Simpler
* Lower reliance on Python ext (we can just rely on getting the type of env)

**Comment by rchiodo** [comment]
The downside I see is any changes we need because conda changes, we'll be duplicating what Python is doing. Unless they stop doing this altogether, seems like we should make an npm module for this?

**Comment by IanMatthewHuff** [comment]
Not that this should influence our choice totally. But does the python extension want to own this type of thing (package installing) for the VS Code python extension ecosystem? If they do then it might be worth trying to solve problems there in the python extension. If they don't (and this was more exposed just for our team) then sure why not do this ourselves?

**Comment by DonJayamanne** [comment]
> doing this altogether, seems like we should make an npm module for this?

Python will be removing all code related to installation, hence there won't be much duplication.
Also the only code that we duplicate is `conda install ` (that's the command that is duplicated).
E.g. with teh current code we're running `python -m pip install`, thats already technically a duplication (but that's a single line of code).
Hence I'm not sure this is a duplicatoin.

I agree, we can create an npm module, as part of this. shoudl be super easy & i propose we create that npm in this same repo.

**Comment by DonJayamanne** [comment]
> But does the python extension want to own this type of thing (package installing)

I thought they don't want to own this.
& us waiting will not get us anywhere, we've been waiting for this to happey while users break and stop using.
I think we can go ahead with our npm, and when things get traction in python extnsion, we can consider merging.

Again, the only duplication is literally a few lines of code.
& the Python extnesion doesn't really have the smarts today, it just dumpts the commands into a terminal (& that will go away as they don't want to do any of this in the future), our code will be slighly different.

**Comment by DonJayamanne** [comment]
Again, I don't think there's any code duplication, but totally fine with the npm module.
Should be super easy.
