### ISSUE TITLE
Pre-release version of Jupyter Extension

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8463]
Going to tackle this in debt.
*   We don't need to go with odd/even, as our pre-release (insider) versions are already a MINOR number ahead of the stable (its for next month). 
	* E.g. stable is 2021.10.xxxx and insiders (pre-release) is 2021.11.xxxxx
* Just update build process

**Question for team (discuss in triage/standup):**
* Do we want users in stable to try out the pre-release version?
	* My suggestion = Yes (often we fix issues and ask users to try vs code insiders, now they can try this in stable)
	* However what if we end up using proposed API that's only available in latest insiders?
		* We now need to ensure we gate these API calls, else the extension could crash in stable.
	* If not, then we cannot adopt this new pre-release
*

**Comment by isidorn** [comment]
@DonJayamanne let me know if we can help somehow.
Also if you want the `pre-release` version to be only available in stable you can use the `engine` property for the `pre-release` version and put vscode-insiders version number as a requirement and then users will not be able to install it in VS Code stable.

Docs that might help: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions

Refs: https://github.com/microsoft/vscode/issues/15756

**Comment by DonJayamanne** [comment]
Thanks @isidorn , we're planning on shipping the pre-release only to VS Code Insiders (at least for now).
One of the reasons is to avoid having issues with the use of proposed API that might not yet be available in stable & the like.

**Comment by DonJayamanne** [comment]
Closing as done

**Comment by isidorn** [comment]
@DonJayamanne awesome, thanks a lot 👏
