### ISSUE TITLE
Allow to retrieve the jupyter filename programmatically [fix support for ClearML]

### ISSUE THREAD

**Issue by bmartinn** [microsoft/vscode-jupyter#8475]
Hi, I'm Martin one of the maintainers of [clearml](https://github.com/allegroai/clearml) (open-source solution for: MLOps + experiment management => CI/CD for ML)

One of the things ClearML does, it analyzes the code in runtime (i.e. when working on jupyter notebook, or running any  python code), picking up the git repo, versioning the jupyter notebook, storing the results on the `clearml-server` etc.

Specifically with jupyter notebooks, it periodically stores the jupyter notebook on the back-end server, creating transparent versioning, as well as allowing users to later run the jupyter as python code on remote machines (it also auto detects dependencies via code analysis, and support remote containers).

With the recent changes in `VSCode` and `VSCode-jupyter`, it seems that jupyter server is no longer executed, and the plugin actually communicates directly with ipykernel.
Is that correct ?

The way `ClearML` does all the magic on the jupyter notebook, is its ability to actually access the file itself, without the jupyter-server we currently cannot find a way to retrieve the active jupyter file name.
To add a bit more details, imagine a function running inside one of the jupyter notebook cells, trying to get the file name of the jupyter notebook. This is basically our current challenge.
 
I played a bit trying to run JavaScript from the cell itself, then picking up the filename from the frontend, but ran into problems communicating back to python code, also I did not find a way to retrieve the value on client end (JavaScript) in the first place...

Any help will be appreciated 😄

**Comment by rchiodo** [comment]
What specifically do you look for in your backend? Is it an environment variable? A global object? (I'm assuming you have your code injected into the kernel somehow).

**Comment by bmartinn** [comment]
Thanks @rchiodo for the quick response !

> What specifically do you look for in your backend? Is it an environment variable? A global object? (I'm assuming you have your code injected into the kernel somehow).

Basically I will take anything you offer, think python code running inside the jupyter notebook cell.
For example, assuming the following code works, it will solve our problem:
```python
import os
print('Jupyter notebook filename: {}'.format(os.environ['VSCODE_JUPYTER_FILENAME']))

>>> Jupyter notebook filename: /tmp/my-jupyter.ipynb
```
global object will also work, and even hidden property somewhere, I'm flexible :)

**Comment by rchiodo** [comment]
We already do this for the [interactive window](https://code.visualstudio.com/docs/python/jupyter-support-py). We set the ```__file__``` variable in every cell before we run them.

I assume that would work for you? Shouldn't be very hard to implement.

**Comment by bmartinn** [comment]
That would be perfect! 🎊 
If needed, I will gladly help in pushing it.

**Comment by rchiodo** [comment]
If you wanted to submit a PR, I think this would be a likely spot to put the logic:

https://github.com/microsoft/vscode-jupyter/blob/bf97452c99e70eac11e0c99edd8f4b2c7fda7efb/src/client/datascience/jupyter/kernels/kernel.ts#L617

You'd use the 'notebookDocument.uri' as the file to set. 

The code would pretty much be the same as this code here:
https://github.com/microsoft/vscode-jupyter/blob/f3f77cfccdcfc641284f37328e330eda872819b1/src/client/datascience/interactive-window/interactiveWindow.ts#L510

Meaning ```kernel.executeHidden(`__file__ = '${file.replace(/\\/g, '\\\\')}'`.

I think you could probably do this for all notebooks, but just to be safe, you could skip this on the interactive window (where the ```.scheme``` on the ```notebookDocument.uri``` would be ```vscode-interactive-notebook```)

I'm moving this item to triage to see if the rest of the team thinks this is okay.

**Comment by rchiodo** [comment]
We'd probably have to test that this didn't interfere with other cells running (run by line might be impacted).

**Comment by bmartinn** [comment]
> We'd probably have to test that this didn't interfere with other cells running (run by line might be impacted).

wouldn't it be enough to execute once in the kernel? I mean the state doesn't actually change between two cells running, no?

**Comment by rchiodo** [comment]
Yes that code I linked to runs once on startup of a kernel. I'm worried that things might be affected by ```__file__``` but it's probably fine. We've had it that way in the interactive window and it has no issues with it.

**Comment by bmartinn** [comment]
So basically [here](https://github.com/microsoft/vscode-jupyter/blob/bf97452c99e70eac11e0c99edd8f4b2c7fda7efb/src/client/datascience/jupyter/kernels/kernel.ts#L615), we could do ?
```js
await this.updateWorkingDirectoryAndPath(this.resourceUri?.fsPath);
file = this.resourceUri?.fsPath
await kernel.executeHidden(`__file__ = '${file.replace(/\\/g, '\\\\')}'`);
traceInfoIfCI('After updating working directory');
```

**Comment by DonJayamanne** [comment]
I don't think we'd should use `__file__`, Jupyter doesnt do this, if we started doing this we'd be introducing unexpected inconsistencies as it goes against the expected behavior.

I would suggest creating a assister global variable such as `__ipynb_file__` or the like.

**Comment by rchiodo** [comment]
> I don't think we'd should use __file__, Jupyter doesnt do this, if we started doing this we'd be introducing unexpected inconsistencies as it goes against the expected behavior.

I'd agree except we've been doing this for two years in the interactive window and nobody has complained about any failure related to it. And there are plenty of things that use ```__file__``` which this might get working for notebooks.

**Comment by rchiodo** [comment]
> So basically [here](https://github.com/microsoft/vscode-jupyter/blob/bf97452c99e70eac11e0c99edd8f4b2c7fda7efb/src/client/datascience/jupyter/kernels/kernel.ts#L615), we could do ?
> 
> ```js
> await this.updateWorkingDirectoryAndPath(this.resourceUri?.fsPath);
> const file = this.resourceUri?.fsPath
> await kernel.executeHidden(`__file__ = '${file.replace(/\\/g, '\\\\')}'`);
> traceInfoIfCI('After updating working directory & __file__');
> ```

Yeah that seems about right. I'd check that resource isn't undefined before executing though.

**Comment by bmartinn** [comment]
> I'd check that resource isn't undefined before executing though.

Do you mean if `__file__` already defined ? i.e. 
```js
await kernel.executeHidden(`__file__ = __file__ if '__file__' in globals() else '${file.replace(/\\/g, '\\\\')}'`);
```

**Comment by rchiodo** [comment]
No I meant this value here:

```typescript
this.resourceUri?.fsPath
```

That could be undefined.

The code is only running once per kernel startup, so we don't need to check if it exists or not yet.

**Comment by bmartinn** [comment]
Hmm I now see what you mean, I thought that since `updateWorkingDirectoryAndPath` is always called, it is defined...

So I'm assuming this would make sense
```js
await this.updateWorkingDirectoryAndPath(this.resourceUri?.fsPath);
const file = this.resourceUri?.fsPath;
if (file) {
    await this.executeHidden(`__file__ = '${file.replace(/\\/g, '\\\\')}'`);
}
traceInfoIfCI('After updating working directory & __file__');
```

**Comment by DonJayamanne** [comment]
Discussed with @rchiodo 
Please can we change this from `__file__` to `__vsc_ipynb_file__ `

**Comment by rchiodo** [comment]
We're worried python packages might be using ```__file__``` to detect if they're not running in jupyter. In the interactive window we actually have a python file so it's fine there. Here we don't.

**Comment by bmartinn** [comment]
Should I just PR it as is?

**Comment by rchiodo** [comment]
Yeah I think so. We probably need a test to verify it's set. Something like the test here:
https://github.com/microsoft/vscode-jupyter/blob/7d1f1706335a5916d7c039fbc357d9de1f1d9245/src/test/datascience/notebook/executionService.vscode.test.ts#L124

Except it would print the value of ```__vsc_ipynb_file__``` and verify it was set to the notebook.

**Comment by bmartinn** [comment]
Hmm what's the contest of the test? Is it running after a notebook was initialized and has an actual name (e.g. what happens if we just created a new notebook, and it is "untitled"?)

Come to think about it, is renaming supported (i.e. renaming the notebook while it is running) ?

**Comment by rchiodo** [comment]
Content of the test would be almost identical to the one I linked to.

You cannot rename a file while it's running (well you can, but it will not be connected to the same kernel).

**Comment by bmartinn** [comment]
Thank you @rchiodo for the guidance, and for the quick merge, you guys are awesome 😍
