### ISSUE TITLE
Remote SSH does not list remote kernels

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8483]
@rchiodo Came across the same problem when used with RemoteSSH. The drop-down list only displays kernels on my local machine instead of those on the remote server. Even worse, I cannot find a way to manually designate a kernel location.

_Originally posted by @namespace-Pt in https://github.com/microsoft/vscode-jupyter/issues/8424#issuecomment-988803857_

**Comment by rchiodo** [comment]
@namespace-Pt can you include the output logs for your situation? Remote-SSH should be impossible for it to list your local kernels as the extension is actually running on the remote machine (it has no access to the local file system).

**Comment by namespace-Pt** [comment]
@rchiodo This bug happens once in a while, and maybe it disappears itself one day later. Here is a figure:
![image](https://user-images.githubusercontent.com/61188463/145370548-bf5cc483-b5c1-494a-93ea-4dcbe0f74c17.png)

As you can see, local kernels and remote kernels are both present in the suggested list. **None of them are correct.**

**Comment by namespace-Pt** [comment]
How can I get the log?

**Comment by rchiodo** [comment]
If you open the output tab, there should be a 'jupyter' output tab:

![image](https://user-images.githubusercontent.com/19672699/145443083-85b6cb7b-3395-45ea-8ab5-a3019ba427f8.png)

**Comment by namespace-Pt** [comment]
Today everything's fine... I will feedback the log when it happens again.

**Comment by rchiodo** [comment]
Okay please reopen when it happens again.
