### ISSUE TITLE
Test for collapse expand is failing

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8492]
Code here:
https://github.com/microsoft/vscode-jupyter/blob/792872e14ae1711ed343f5d7feba22ac84f45d22/src/test/datascience/interactiveWindow.vscode.test.ts#L215

I believe @roblourens commit here changed how we track this. We need some other way to do so.

I'm disabling the test for now.

**Comment by StevenLi-DS** [comment]
Cells in the interactive windows are no longer collapsed. Is this a known issue @rchiodo

**Comment by rchiodo** [comment]
Yes. This one: https://github.com/microsoft/vscode-jupyter/issues/8203

**Comment by roblourens** [comment]
Sorry. You can't actually test this now...
