### ISSUE TITLE
Progress stack doesn't seem to be working

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8511]
I got this:

![image](https://user-images.githubusercontent.com/19672699/145493866-ba4c26db-71aa-41b6-968d-345b2c6ee244.png)

After:
- Connect to remote server
- Open a notebook
- Run a cell
- Close vs code
- Kill remote server
- Open VS code
- Pick cancel on 'connection is dead' dialog
- Pick a local kernel
- Start it

**Comment by DonJayamanne** [comment]
> Pick a local kerne

What was the local server you selected? Was it `condaEnvTest`.
I couldn't replicate this.

Are you using `raw` or `local Jupyter`

**Comment by rchiodo** [comment]
Using raw. You may have fixed this with your recent changes.

**Comment by DonJayamanne** [comment]
Aaah yes, thanks
Closing for now.
