### ISSUE TITLE
remote jupyter - IntelliSense not working

### ISSUE THREAD

**Issue by ccbiozhaw** [microsoft/vscode-jupyter#8517]
## Environment data

-   VS Code version: 1.63.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote 

## Expected behaviour

IntelliSense working in jupyter 

## Actual behaviour

IntelliSense does not work

## Steps to reproduce:

I have a new install of VsCode. I then download the Python Plugin and the Jupyter Plugin. I then connect to an already running server on the network. IntelliSense does not work. Hovering also does not work. I think that something is not beeing recognized. 

edit: working locally everything works as expected. if i connect to remote it doesnt

**Comment by amunger** [comment]
yes, this is a known issue: https://github.com/microsoft/vscode-jupyter/issues/8285
There is more info in that link and we are hoping to fix it in the January release.
