### ISSUE TITLE
VS Code Debug console not working with Jupyter Notebook

### ISSUE THREAD

**Issue by philffm** [microsoft/vscode-jupyter#8519]
## Environment data

-   VS Code version: Version: 1.64.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2022.1.1001562662
-   Python Extension version (available under the Extensions sidebar): v2022.0.1547637430-dev
-   OS (Windows | Mac | Linux distro) and version: MacOS 12.1 Beta (21C5045a)
-   Python and/or Anaconda version: conda 4.10.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): **N/A**
-   Jupyter server running: **Local** 

## Expected behaviour

Debug console lets examine e.g. variables / experiment with python code on the fly, just like in Python (or when using Jupyter Notebooks in Google Colab)

## Actual behaviour

Variables not accessible in Debug console
![image](https://user-images.githubusercontent.com/6079545/145580806-26ae03e5-1eae-4087-b96f-d6cf853caa10.png)
In debug mode:
![image](https://user-images.githubusercontent.com/6079545/145581113-ec18e15a-1c17-4d5f-a7d1-fd946362c8f4.png)

I was wondering, whether this is supposed to work at all or whether there is some workaround for that? Because usually I always use the debug console before I write code into stone ;) 

Best, Phil

**Comment by amunger** [comment]
yes, that's expected, that terminal is only available when the debugger is running.
The Jupyter: Variables window can be used to view current variables in scope, and you can just create cells temporarily to run extra code and delete them when you're done.
If you really don't want to add additional cells to your notebook, another option would be to connect to a remote Jupyter server (outside of VS code) and connect to the same kernel with an Interactive Window. The behavior is different from a terminal, but you'd have the same set of variables to act on.

**Comment by greazer** [comment]
Hey @philffm, thanks for the feedback. Take a look at #6484. We think it may be similar or identical to what you're looking for. Closing for now.
