### ISSUE TITLE
Variable viewer does not work with Python 3.10

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8523]
Run this code 
```
import numpy as np
import pandas as pd
mynpArray = np.array([1.0, 2.0, 3.0])
myDataframe = pd.DataFrame(mynpArray)
mySeries = myDataframe[0]
class MyClass:
    x = 5
myClass = MyClass()
```

No variables.
Run another cell with the code
```
a = 1234
```

Still no variables.

**Comment by DonJayamanne** [comment]
The following test has been disabled for Python 3.10
`src/test/datascience/variableView/variableView.vscode.test.ts`

**Comment by IanMatthewHuff** [comment]
IPython 8.0 has just been released. I tested and the fix for this issue is in there:
![image](https://user-images.githubusercontent.com/812783/149201883-666d69e3-edce-40ba-8357-efefc257dc48.png)
