### ISSUE TITLE
Use Python 3.10 or 3.9 in PRs

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8525]
* Should we switch over to 3.10 in the CI
* Should we use both 3.9 and 3.10

I personally think 3.9 is stable enough and we should just switch to 3.10 without using 3.9 (uses fewer resources as well).

**Comment by greazer** [comment]
Use 3.10 for local raw kernel tests

**Comment by greazer** [comment]
After discussion we decided to switch to 3.10 now for all scenarios that support it.

**Comment by rchiodo** [comment]
It looks to me like we're already doing this.
