### ISSUE TITLE
Inconsistent intellisense suggestions

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode-jupyter#8535]
## Environment data

-   VS Code version: 1.64.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2022.1.1001572077
-   Python Extension version (available under the Extensions sidebar): v2022.0.1573923366-dev
-   OS (Windows | Mac | Linux distro) and version: macOS 12.0.1 (21A559)
-   Python and/or Anaconda version: Python 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

I also have Pylance disabled

## Expected behaviour

For suggestions to be the same

## Actual behaviour

Suggestions are different if I am not typing the `.` in sequential order

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. create data frame
2. create new cell
3. type `df.` and see suggestions
4. go to another cell
5. return to previous cell and type any data property (head, drop, etc.) 
6. :bug: suggestions are different

At the 16s marker is where I notice the inconsistency. The suggestions only appear when I am already typing the `.` and proceed with the parameter.

https://user-images.githubusercontent.com/35271042/145862860-b8b074bb-81c2-486f-9288-7a008d6b6eef.mp4

**Comment by rchiodo** [comment]
It looks like the connection to the language server is lost. Not sure how that would happen. I can repro this myself too.

**Comment by IanMatthewHuff** [comment]
I don't see this anymore with current jupyter / pylance, so resolving.
