### ISSUE TITLE
display() helper marked as error

### ISSUE THREAD

**Issue by shamrin** [microsoft/vscode-jupyter#8539]
## Environment data

-   VS Code version: 1.62.3
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: 10.15.6
-   Python and/or Anaconda version: 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): poetry
-   Jupyter server running: Local

## Expected behaviour

I expect Jupyter extension to know about [`display()` built-in](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.display
).

It would also be nice for VSCode Jupyter documentation to tell about `display()` function.

`display()` is a useful print-like helper from IPython/Jupyter. Here's the example usage:

![image](https://user-images.githubusercontent.com/510678/145906058-5a6ed77c-6b41-4873-8f08-c16264f50752.png)

## Actual behaviour

Even though the code works, the `display()` call is underlined with curly as erroneous.

![image](https://user-images.githubusercontent.com/510678/145905891-bc9b8954-0054-423a-b28a-39fab3736031.png)

## Steps to reproduce:

```python
from PIL import Image
from random import randrange

def create_image():
    for _ in range(3):
        p = [randrange(256), randrange(256), randrange(256)]
        im = Image.frombuffer('RGB', (16,16), bytes(p*(16*16)))
        display(im) # rich print-like function from ipython
    return im

create_image()
```

## Related

https://github.com/microsoft/pylance-release/issues/1598

**Comment by rchiodo** [comment]
Thanks for the bug. 

This is happening because we don't shortcut 'display'. (We need to add this to our list of hidden imports)

If you write this instead, it should work:

```python
from PIL import Image
from random import randrange

def create_image():
    for _ in range(3):
        p = [randrange(256), randrange(256), randrange(256)]
        im = Image.frombuffer('RGB', (16,16), bytes(p*(16*16)))
        IPython.display(im) # rich print-like function from ipython
    return im

create_image()
```

**Comment by shamrin** [comment]
@rchiodo I've tried it. Using `IPython.display` does not work at all, while bare `display` works (but marked as error by Pylance):

```
NameError: name 'IPython' is not defined
```

Adding `from IPython.display import display` to the top helps, but feels extra.

**Comment by rchiodo** [comment]
Sorry, ```IPython.display``` isn't runnable. It just fixes the pylance problem, so that was a bad suggestion.

**Comment by IanMatthewHuff** [comment]
Looks good with newest bits now:
<img width="704" alt="image" src="https://user-images.githubusercontent.com/812783/200040153-9d164b1f-4919-474d-be85-77c7a80a3b79.png">
