### ISSUE TITLE
markdown cells not being split for code

### ISSUE THREAD

**Issue by RipPennell** [microsoft/vscode-jupyter#8543]
## Environment data

-   VS Code version: 1.63.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: 3.7.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. copy paste the following cell:

```
#%% [markdown]
# ## Some Markdown Text
print("hi")
```

The output in IPython 7.30.1 will only be the markdown text, with no code running.

Removing the "[markdown]" from the cell lets the markdown text be treated as a comment and the code executes, since it's not just a code cell. All of my python files have cells that start with markdown and go into code. Do I have to manually separate every cell?

Same problem is here [microsoft/vscode-jupyter#3501](https://github.com/microsoft/vscode-jupyter/issues/3501)

The automatic splitting appears to be a feature according to [microsoft/vscode-jupyter#2285](https://github.com/microsoft/vscode-jupyter/issues/2285)
Seems this is indeed a bug then

**Comment by RipPennell** [comment]
Downgrading to an earlier version of the Jupyter Extension fixes this issue, so the issue is in the Jupyter Extension specifically

**Comment by rchiodo** [comment]
Thanks for the issue. This is indeed a regression.
