### ISSUE TITLE
VSC-Insiders still required for Jupyter extension? Update info page if not.

### ISSUE THREAD

**Issue by oscarrutt** [microsoft/vscode-jupyter#8548]
Is VSC-Insiders still required for Julia users of the Jupyter extension? The info page says:

Working with other Languages
The Jupyter Extension supports other languages in addition to Python such as Julia, R, and C# in VS Code Insiders with our latest Native VS Code Notebooks Experience!
Quick Start
Step 1. Install VS Code Insiders
   etc. ...

I inquired about this at StackOverflow
https://stackoverflow.com/questions/70347617/is-visual-studio-code-insiders-still-required-for-julia-users-of-the-jupyter-ext
and got the answer that Insiders version is not required for VSC version ≥ 1.60.1. If this is true, could the info page be updated?

**Comment by rchiodo** [comment]
Thanks for the suggestion. We'll update if this is no longer necessary.
