### ISSUE TITLE
Add support for ipywidgets 8

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8552]
Packages such as `tqdm` will not work with the latest version of IPyWidgets 8
* [ ] [Explore supporting IPyWidgets 8](https://github.com/microsoft/vscode-jupyter/issues/11217)

# Work around - Please install ipywidgets==7.7.2

**Comment by JP-Ellis** [comment]
Is this a difficult issue to resolve?  Do we know what causes the widgets to not display at all?

**Comment by DonJayamanne** [comment]
> know what causes the widgets to not display at all?

we need to update the npm packages used and tweak a few places accordingly

**Comment by JP-Ellis** [comment]
Is there a temporary workaround which might allow this to work while a permanent fix is being worked on?

**Comment by DonJayamanne** [comment]
> temporary workaround which might 

unfortunately no. you can use the older version. i don't think 8 had been released yet.

**Comment by JP-Ellis** [comment]
All good!  While version 8 is not yet marked as stable, it has been available on pypi as a pre-release since February 2020, and the first beta (?) appeared in November 2021.  There's a few things I'm looking forward to use once it works well within VS Code :smile:

**Comment by JP-Ellis** [comment]
Just as a friendly FYI: The first release candidate for 8.0.0 was released on 12 March.

**Comment by DonJayamanne** [comment]
@JP-Ellis please test the latest pre-release version of the extension, it should work as long as you are not using any of the latest IPyWidget 8.0 widgets/features. I.e. older widgets like slider/textboxes, etc and othe 3rd party widgets will still work.

**Comment by JP-Ellis** [comment]
Unfortunately it didn't seem to work for me.  I tested the `HTML` and `Dropdown` widgets from ipywidgets `v8.0.0rc0` and against `v2022.4.1000912146` of the extension and nothing showed up.

**Comment by DonJayamanne** [comment]
Will test, I tried this with the 8b1, not the rc version.

**Comment by DonJayamanne** [comment]
@JP-Ellis 
I've just tried this again against the latest pre-release and the `v8.0.0rc0` and it seems to work for me
Here's the version of Jupyter extension installed `v2022.4.1000971004`, please could you let me know if this works?

**Comment by DonJayamanne** [comment]
Found that `slider` widget works and not the textbox. Will need to dig deeper into this.

**Comment by tongda** [comment]
Under the pre-release version of Jupyter plugin (v2022.8.1002431052), running code:

```
import ipywidgets as ipw
ipw.Text(value="test")
```

nothing presented.

Log of Jupyter plugin:

```
info 13:53:43.683: Execute Cell 0 /workspace/notebook/test.ipynb
info 13:53:43.758: Cell 0 executed with state Success
info 13:53:43.867: Widget Message: WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:2.0.0
info 13:53:43.868: Widget Message: WidgetManager: Loading class TextStyleModel:@jupyter-widgets/controls:2.0.0
info 13:53:43.868: Widget Message: WidgetManager: failed, Loading class TextStyleModel:@jupyter-widgets/controls:2.0.0
info 13:53:43.868: Widget Message: WidgetManager: failed, Loading class TextStyleModel:@jupyter-widgets/controls:2.0.0
error 13:53:43.868: Widget load failure {} {
  className: 'TextStyleModel',
  moduleName: '@jupyter-widgets/controls',
  moduleVersion: '2.0.0',
  cdnsUsed: false,
  isOnline: true,
  timedout: false,
  error: '{}'
}
info 13:53:43.870: Widget Message: WidgetManager: Loading class TextModel:@jupyter-widgets/controls:2.0.0
info 13:53:43.918: Widget Message: Received display data message 15e77492c9014d8987f2bc2b950e7ed8
info 13:53:43.929: Widget Message: Waiting for model to be available before rendering it 15e77492c9014d8987f2bc2b950e7ed8
info 13:53:43.929: Widget Message: Error: Failed to render widget 15e77492c9014d8987f2bc2b950e7ed8, Error: Module @jupyter-widgets/controls, semver range ^2.0.0 is not registered as a widget module
```

**Comment by FlorinAndrei** [comment]
I had to pin ipywidgets to the previous generation in my install scripts, or else VSCode would fail. This is annoying.

```
ipywidgets==7.*
```

**Comment by DonJayamanne** [comment]
Required work
* Support running kernel startup code prior to synchronizing kernel messages with webview kernel
    * Buffer kernel messages, see work done in lazy creation of controllers (switching controller from remote kernel spec to live kernel spec)
* Support lazy loading of IPyWidget script instead of statitcally contributing this in controller
* Support querying version of ipywidgets

**Comment by alex180500** [comment]
any update on this?

**Comment by giswqs** [comment]
I just ran into the same. It took me a while to debug and just found out the ipywidgets 8 does not support VS Code.
![image](https://user-images.githubusercontent.com/5016453/213613147-4498b5f3-3140-4a19-9c7b-509bdf6a9dd8.png)

**Comment by matifali** [comment]
Nice, so that it will work out of the box now?

**Comment by DonJayamanne** [comment]
Please wait till early next week and it will work in a prerelease version

**Comment by DonJayamanne** [comment]
@matifali  you should be able to test this within an hour
Please install the pre-release version of the Jupyter extension and the latest version of the notebook renderer application in vscode insiders

**Comment by pcmoritz** [comment]
@DonJayamanne Do you know when we can expect the fix to this being available in a released version of this extension? That would be very much appreciated! Thanks for fixing this :)

**Comment by DonJayamanne** [comment]
This issue is closed because it is now supported in the latest version, the support was added a few released ago

**Comment by pcmoritz** [comment]
Got it, thanks a lot! I think I got confused with the old version that was released on https://github.com/microsoft/vscode-jupyter/releases/tag/2022.09.120 -- it seems on the marketplace a newer version is available. Thanks for your help and sorry for the confusion :)

**Comment by pcmoritz** [comment]
It looks like this bug was tricky to fix, kudos for getting it solved!
