### ISSUE TITLE
Packages are not imported from the selected Python environment

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8553]
- Create new conda environment
- Install jupyter into it
- set ```"jupyter.disableZMQSupport": "true"```
- Try running interactive window with this environment

Kernel never starts.

**Comment by rchiodo** [comment]
Root cause is this when starting the kernel:

```
  File "C:\Users\aku91\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_core\paths.py", line 387, in win32_restrict_file_to_user
    import win32api
```

It looks like it's half using the global jupyter (which is probably my global jupyter interpreter) and the jupyter installed in the conda environment.

**Comment by DonJayamanne** [comment]
Works for me, on windows.

**Comment by rchiodo** [comment]
Yes I can. Everything works fine if I start jupyter from that environment. But if I start jupyter in another environment, it doesn't.

**Comment by rchiodo** [comment]
Figured out the problem. Sys path is wrong.

When working it's this:
```
['', 'C:\\Users\\Aku91\\Source\\Repos\\PythonApplication1', 'C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5\\python39.zip', 'C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5\\DLLs', 'C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5\\lib', 'C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5', 'C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5\\lib\\site-packages', 'C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5\\lib\\site-packages\\win32', 'C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5\\lib\\site-packages\\win32\\lib', 'C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5\\lib\\site-packages\\Pythonwin']
```
When not working, the global sys path is injected first:

```
['', 'C:\\Users\\Aku91\\Source\\Repos\\PythonApplication1', 'C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5\\python39.zip', 'C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5\\DLLs', 'C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5\\lib', 'C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5', 'C:\\Users\\aku91\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages', 'C:\\Users\\aku91\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\win32', 'C:\\Users\\aku91\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\win32\\lib', 'C:\\Users\\aku91\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\Pythonwin', 'C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5\\lib\\site-packages', 'C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5\\lib\\site-packages\\win32', 'C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5\\lib\\site-packages\\win32\\lib', 'C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5\\lib\\site-packages\\Pythonwin']
```

**Comment by rchiodo** [comment]
I wonder if we can generate a PYTHONPATH that fixes it.

**Comment by rchiodo** [comment]
Yep that fixes it. @DonJayamanne I fixed it by updating how we print out variables.

I changed this:

```python
import os
import builtins
import json

builtins.print("e976ee50-99ed-4aba-9b6b-9dcd5634d07d")
builtins.print(json.dumps(dict(os.environ)))
```

to this

```python
import os
import builtins
import json
import sys

builtins.print("e976ee50-99ed-4aba-9b6b-9dcd5634d07d")

# Special case PYTHONPATH to include sys.path
formatted_sys_path = os.pathsep.join(sys.path)
os.environ["PYTHONPATH"] = f"{os.getenv('PYTHONPATH')};{formatted_sys_path}"

# Dump results
builtins.print(json.dumps(dict(os.environ)))
```

Thoughts? I think this should be okay. We're not removing anything from the PYTHONPATH, and we're ensuring it includes the original sys path for the interpreter.

**Comment by DonJayamanne** [comment]
Ideally this shouldn't be necessary, also most of the time PYTHONPATH is empty.
I'm concerned we'd be setting that env variables unnecessarily.
Let me have  look, ie get a better understanding

**Comment by rchiodo** [comment]
> I'm concerned we'd be setting that env variables unnecessarily.

I believe this should be harmless. PYTHONPATH would be redundant in most cases with what it figures out is sys.path. Although if we got it wrong it would certainly mess up the sys.path.

**Comment by rchiodo** [comment]
> Please can you check sys path for other python envs (virtual env) and other conda environments.

Not sure what this means? You mean when printing? Only do this if you're on a virtual environment?

**Comment by DonJayamanne** [comment]
1. How did you manage to get the value for sys path (that you've mentioned earlier).
I'm suggesting we get the same values for another conda env and another virtual env.
2. Concern with PYTHONPATH is, users tend to udpate this in their .env files as well, and we've had issues there too.
I'm not saying its the wrong approach, just not comfortable without actually figuring out why the path variables are wrong.

**Comment by rchiodo** [comment]
> I'm not saying its the wrong approach, just not comfortable without actually figuring out why the path variables are wrong.

I believe the path variables are wrong because jupyter is injecting its sys.path into the kernel on startup. I got those sys.path variables by changing the kernel launch command.

I switched it from this:

```
  "argv": [
    "C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5\\python.exe",
    "-m",
    "ipykernel_launcher",
    "-f",
    "{connection_file}"
  ],
```
to this
```
  "argv": [
    "C:\\Users\\aku91\\miniconda3\\envs\\condaTestQT5\\python.exe",
    "-c",
    "import sys;sys.path",
    "-f",
    "{connection_file}"
  ],
```

It would still crash, but then I could see the sys path.

**Comment by rchiodo** [comment]
> I'm suggesting we get the same values for another conda env and another virtual env.

Not sure what you mean by this? What are they on my machine? Sys.path is what you expect. It includes the site-packages for the venv (or conda env). Conda envs seem to put their own paths first.

**Comment by DonJayamanne** [comment]
I'm running into similar issues on Windows, I don't think this is specific to Mac M1

**Comment by DonJayamanne** [comment]
I've submitted the PR and added tests for this, should be fine now.
https://github.com/microsoft/vscode-jupyter/pull/8576

**Comment by DonJayamanne** [comment]
# Notes
* Re-opening for the team to see this in triage meeting (as the changes were merged without a review)
* Issue was fixed by reverting the previous changes & submitting a new fix
* Please close this issue

**Comment by rchiodo** [comment]
I verified Don's latest change. It works for me too.

**Comment by Dr-Dum** [comment]
@DonJayamanne I saw that #8576 as merged and closed, but I'm not sure if it's still working or if something else needs to be changed on my end before the solution works.

I had an issue where I updated plotly in Conda, but it's still showing an old version because it's using the global site packages. Screenshotted below is the output from sys.path and as you can see the conda site packages are prioritized below the global site packages.

Is there something else I need to do? Currently running Python 3.9.12 and VS Code version 1.72.2.

![image](https://user-images.githubusercontent.com/101877538/198679705-db5c63d0-b85f-4cf4-8dcd-86bc785637ad.png)
