### ISSUE TITLE
Refresh Data Viewer should not reset column widths

### ISSUE THREAD

**Issue by dr1ver1** [microsoft/vscode-jupyter#8555]
### VS Code version

1.63.1

### Extension version

2021.12.1559732655

### OS type

Windows

### OS version

10

### Python distribution

python.org

### Python version

3.9.9

### Language server

Default

### Expected behaviour

Data Viewer columns should keep the same width on Refresh. 

### Actual behaviour

Clicking Refresh resets the width of the Data Viewer columns . This issue happens for all columns, but is particularly an issue for datetime where the important information is often not visible because of the column width. It is annoying and time consuming when debugging, particularly with multiple dataframes that are all being updated.

Originally raised at https://github.com/microsoft/vscode/issues/139185

### Steps to reproduce

1. Debug a python script containing a dataframe, with a DateTime column
2. View the dataframe in the Data Viewer
3. Change the column width of the DateTime column so that the date and time can be viewed
4. Refresh the Data Viewer, and the column width resets

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rchiodo** [comment]
Thanks for the bug. Seems like a good idea to me.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, however given the fact that this has recieved very few upvotes and the fact that this issue has been around for over 2 years, I'm closing this issue
