### ISSUE TITLE
Jupyter Variable very slow to update/buggy

### ISSUE THREAD

**Issue by AmrSol** [microsoft/vscode-jupyter#8563]
Issue Type: <b>Performance Issue</b>

When working with VSC's inbuilt npython notebook, the Jupyter: Varaible tab next to the terminal can be either very slow in updating or buggy. Please fix =)

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by DonJayamanne** [comment]
Thanks for filling this issue.
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Comment by yanyu2015** [comment]
I have the same problem. the jupyter variable windows is too slow and it may cause my code run slowly. How can it load as fast as spyder‘s variable window？
