### ISSUE TITLE
Interactive window not showing stack trace

### ISSUE THREAD

**Issue by thierry-bm** [microsoft/vscode-jupyter#8568]
## Environment data

-   VS Code version: 1.63.1
-   Jupyter Extension version (available under the Extensions sidebar): 2021.11
-   Python Extension version (available under the Extensions sidebar): 2021.12
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

Upon a crash, the interactive window should show which line from my code is responsible for the crash. 

## Actual behaviour

![image](https://user-images.githubusercontent.com/1646225/146384113-2f70ba14-786c-4648-a2d8-b92e1421eaf0.png)

The information does not show the line where the exception was raised. Howver it does show the stack trace if it's raised from a package. But it does not display the line of my code which prompted the exception.

![image](https://user-images.githubusercontent.com/1646225/146385084-cdeda574-118e-4a9f-8576-ba1d835d3019.png)
![image](https://user-images.githubusercontent.com/1646225/146385122-fb94e587-1d94-4bf5-8176-afbe141f6d63.png)

**Comment by rchiodo** [comment]
Thanks for the bug. I had some questions about the issue.

Where are you defining and running ```f``` from?

For me, if I define ```f``` and run ```f``` from a python file, this all works fine.
If I define ```f``` from the input box at the bottom of the interactive window it doesn't (this is expected as there's no module)

**Comment by rchiodo** [comment]
I think there's a problem with our stack parsing though.

This is coming out if I run ```f``` from a separate cell:

![image](https://user-images.githubusercontent.com/19672699/146447451-94c8e3dc-578e-4021-8fed-b88de23d431b.png)

**Comment by thierry-bm** [comment]
If I define and evaluate `f` within the same cell then the correct behaviour occurs. It's only when `f` is defined from a previously evaluated "cell" that the bug happens.

**Comment by rchiodo** [comment]
We should update manualTestFile.py to also include this scenario. Our normal just 'raise Exception' isn't sufficient.

**Comment by jaymegordo** [comment]
[#139545](https://github.com/microsoft/vscode/issues/139545) Is same issue

**Comment by rchiodo** [comment]
> [#139545](https://github.com/microsoft/vscode/issues/139545) Is same issue

@jaymegordo Actually that issue is related to this change here: https://github.com/microsoft/vscode/pull/140351. 

The stack trace not showing (this issue here) still repros even when the errorRenderer.js file loads.

**Comment by IanMatthewHuff** [comment]
Sorry for the back and forth on the tags. Didn't have the correct extension version:
![image](https://user-images.githubusercontent.com/812783/151428364-b8808689-b625-4230-9ecd-7af8a433e57a.png)
Looks good now and links work.

**Comment by Joshuaclymer** [comment]
I'm still having this issue
