### ISSUE TITLE
Giving option to create slides

### ISSUE THREAD

**Issue by Bipul-Harsh** [microsoft/vscode-jupyter#8571]
Just like the original jupyter notebook where you can create presentation slides through additional option of defining cell with different options like:

- <b>Slides</b> : are full slides that you move through left to right.
- <b>Sub-slides</b> : show up in the slideshow by pressing up or down.
- <b>Fragments</b> : are hidden at first, then appear with a button press.
- <b>Skip</b> : You can skip cells in the slideshow.
- <b>Notes</b> : leaves the cell as speaker notes.

Can you please provide it in your jupyter notebook also?

**Comment by amunger** [comment]
Thanks for the suggestion

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1121
