### ISSUE TITLE
Activation and execution of cells is slower when using Conda Run

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8580]
Conda run seems to be very slow
* Possibly because `conda run` is slow
* Or we have python extension running `conda run` for all conda environments and we're running as well
* Or other

@rchiodo @IanMatthewHuff You might recall, that running `conda activate` on CI can cause issues specially when run in parallel.
And we have code that retries the activation (basically conda isn't designed to activate multiple environments at the same time, due to some file locking issue).

Hence I believe using conda run in parallel (in python extension & then also running in jupyter) could be causing issues.

This is all hypothetical.

**Comment by rchiodo** [comment]
Conda is definitely slower for me (on first run). Takes almost 10 seconds to start up.

**Comment by rchiodo** [comment]
Note to self. this command was super useful for debugging this stuff:

![image](https://user-images.githubusercontent.com/19672699/149030304-b2d41207-58b0-42ad-915f-5d5ec838a877.png)

**Comment by rchiodo** [comment]
Conda activation itself takes 10 seconds on my machine for a specific environment.

- Calling 'C:/Users/aku91/miniconda3/Scripts/activate && conda activate golden_scenario_env && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && conda info -s' took 10 seconds
- Calling 'C:/Users/aku91/miniconda3/conda run -n golden_scenario_env python printVariables.py' took 9 seconds

There's no way around this, although it should be cached. Sometimes it seems like it isn't.

**Comment by rchiodo** [comment]
Slowdown isn't entirely getting variables though. Takes 15 seconds to get the activated environment variables in total.

**Comment by rchiodo** [comment]
Getting activated environment variables requires the following:

- Get conda location (searches the registry) = Takes 9.5 seconds
- Get conda version (runs conda to get info) = Takes 10ms
- Get conda environment (runs conda run with python process) = Takes 8.5 seconds

None of these can go any faster than that (for the machine I'm on). So minimum is 18 seconds.

We do cache it however.

**Comment by rchiodo** [comment]
Yeah on rerun it takes 14ms to get all the same information.

**Comment by rchiodo** [comment]
Looking at the kernel execution now.

**Comment by rchiodo** [comment]
Kernel execution (if environment variable activation is cached) takes 5 seconds to start the process. 2 seconds to run all of the startup code for a total of 7 seconds to get to the code actually executing.

The 5 seconds for launching can be broken down into:
- 2 seconds to check dependencies and start daemon
- 3 seconds for kernel to be ready (kernel startup time)

The 2 seconds to run all the startup code might be shortened if we combined all of the startup code into one cell.
The 2 seconds for the starting of daemon might be shortened if we auto started daemons in the background, but that seems like people might be pissed to have all of these python processes running.

**Comment by IanMatthewHuff** [comment]
Thanks for the breakdown. Those unavoidable items are slow :(. Kinda a bummer that our best case scenario would still have to take that hit.

**Comment by rchiodo** [comment]
I did find a typo that may be causing the caching to be skipped for somethings (this line [here ](https://github.com/microsoft/vscode-jupyter/blob/8b309169fdc69fb177bd67ded7a8c633f992264a/src/client/common/process/condaService.ts#L41) should read ```await Promise.race([cacheInfo.promise, latestInfo])```). 

Effectively that race always returns immediately but then the cacheInfo isn't completed so we always wait for the latestInfo promise. That should be cached on the python side though, so not sure it makes much of a difference.

I'm going to try moving all of the kernel warmup code into a single execution to see if I can speed that up a little.
