### ISSUE TITLE
Disable commiting changes to perf_results.json in every PR

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8585]
Every single PR updates this file, hence anyone submitting a PR will always have their PR out of date,
as a result, the CI will never run.

Assume i have 1 PR (even worse when you have 2-3)
* All will be blocked
* Then i updated all 5 to run
* Now merge 1
* Now others will be out of date and CI will block..

I think this should get updated ONLY in the main branch, not in PRs.

Also this results in the local PR branch being out of date, as there are changes on the server (that is not expected)

Hence to me this is more of a hindrance to my workflow.

**Summary of problems**
* Cannot submit PRs as it get blocked & CI jobs never run
* After fixing this and then submitting more changes to the PR to fix tests, then you find out its out of date all over again
* The server branch is updated with changes and my local branch is out of sync (when I own the branch)

**Suggestion**
* Commit only in main branch
* Upload this into azure blob store

**Comment by DonJayamanne** [comment]
For now I'm disabling the commits in PRs

**Comment by rchiodo** [comment]
Do you know if azure blob storage maintains a history? The goal was to have something tied to a commit that contains the perf results of the commit. So CI could run the test only on main but then update the perf results output with the commit id. But we'd still want to know the history of the perf results.

**Comment by rchiodo** [comment]
Need to setup a meeting to discuss once Don is back.

**Comment by rchiodo** [comment]
Another idea, submit perf results with every PR to vscode-jupyter-internal so it doesn't interfere with the PR in question.

**Comment by DonJayamanne** [comment]
Even with that we're still uploading files to a separate repository, wouldn't be the same as uploading individual files to azure blob store with each file name having the commit id

**Comment by rchiodo** [comment]
I just want a history of the results. Azure blob doesn't support it by default and it seems silly to use azure for source control.

**Comment by rchiodo** [comment]
@amunger is actively working on solving this with telemetry.
