### ISSUE TITLE
Test code used to check if a kernel is selected is incorrect (used to be correct)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8588]
We have the following in helpers.ts
```typescript
let waitForKernelPendingPromise: Promise<void> | undefined;

export async function waitForKernelToChange(
    criteria: { labelOrId: string } | { interpreterPath: string },
    timeout = defaultNotebookTestTimeout
) {
    // Wait for the previous kernel change to finish.
    if (waitForKernelPendingPromise != undefined) {
        await waitForKernelPendingPromise;
    }
    waitForKernelPendingPromise = waitForKernelToChangeImpl(criteria, timeout);
    return waitForKernelPendingPromise;
}
```

If we open a new notebook and expect the julia kernel to be selected, the this will return true.
Next if we open a new notebook and expect rust to be selected, this will return the same value returned previously.

Note: We're caching `waitForKernelPendingPromise`
& this is incorrect, tests don't expect this.

I think our tests are passing by chance in all the places where this function is being called.
I'd consider this to be a major issue, as all tests are passing incorrectly.

**Comment by greazer** [comment]
"Next if we open a new notebook and expect rust to be selected, this will return the same value returned previously."

We don't believe this is true. We'll have to discuss.
