### ISSUE TITLE
Multiple dataframe viewers opened when viewing the exact same DF variable

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8591]
Each time you click on a DF to view the DF, we open a new one.
This feels like a very poor UX, its like clicking on an ipynb and opening a new notebook everytime.

(when opening a large DF the memory usage doubles, after all we're cloning the JSON in memory for each webview).

We know the variable, hence it should be easy to check if it has already been displayed, also we have a refresh icon.

**Comment by greazer** [comment]
Now that we have refresh, this behavior does seem off.

**Comment by DonJayamanne** [comment]
Not reported by anyone, else closing this issue
