### ISSUE TITLE
Cannot read property 'then' of undefined (in tests)

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#8593]
We are receiving following errors from telemetry

```
TypeError: Cannot read property 'then' of undefined 
at DataScienceErrorHandler.showMessageWithMoreInfo (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/errors/errorHandler.js:8860:70) 
at /home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/errors/errorHandler.js:8715:24 
at DataScienceErrorHandler.handleErrorImplementation (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/errors/errorHandler.js:9022:25) 
at DataScienceErrorHandler.handleKernelError (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/errors/errorHandler.js:8652:16) 
at /home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/kernels/kernel.js:11670:38 
at runMicrotasks (<anonymous>) 
at processTicksAndRejections (internal/process/task_queues.js:93:5) 
```

**Comment by DonJayamanne** [comment]
These look like errors on ci when we run the tests (path is typical of what's on GitHub ci actions)

Can you ignore these when not running in production. 
I thought we had disabled telemetry when running tests 

There could be more errors similar to this in tests, as a result of stubs/mocks that's are poorly crafted, and we'd don't care about them.

Closing as this isn't supposed to be tracked and it's not production code

**Comment by rebornix** [comment]
@DonJayamanne  The error telemetry logs errors/exceptions thrown in all VS Code processes so I guess it doesn't know if the extension is in test/debug mode or not. 

By looking at the code, I'm not sure if this is absolutely a test error. `applicationShell.showErrorMessage` doesn't return a thenable object, it's likely that the extension host already shutdowns but the `showMessageWithMoreInfo` still gets executed

https://github.com/microsoft/vscode-jupyter/blob/7b21137398cd160d4d77d09b562fffea23a63a17/src/client/datascience/errors/errorHandler.ts#L266

IMO it means that we didn't dispose/stop all running requests on extension shutdown (extension host deactivate extensions first). It's probably not worthy to tackle this particular error but it can be something to take into consideration while improving the code structure.

**Comment by DonJayamanne** [comment]
> tackle this particular error but it can be something to take into consideration while improving the code structure.

As mentioned these are a result of the mocks. Possible we've arrived it with something that doesn't return a promise.

I'll update the code to ensure we handle this better to prevent bogus error being sent to vscode.

Can we not exclude since if these via telemetry, surely three just be a way, some property such as machine or seeding id or the like could tell us where its test or not 
Where we could need incorrectly counting a lot of events incorrectly on telemetry when we have ci running on a large number of machines for 1000s for jobs.

**Comment by DonJayamanne** [comment]
Reopening to clean up the test code to ensure we don't get these errors in telemetry

**Comment by DonJayamanne** [comment]
Hopefully we won't see these error anymore in our tests.
Difficult to tell as we don't know what test is causing this.
