### ISSUE TITLE
Support for Quarto qmd

### ISSUE THREAD

**Issue by trinhdhk** [microsoft/vscode-jupyter#8594]
[Quarto](quarto.org) has gradually become a thing and is pushed by RStudio. It is a variant of the famous Rmarkdown commonly used in R World to generate scientific reports/papers/books using markdown syntax and code embedded. Quarto is, however, independent from from R. It has its own binary compiler which supports multiple languages (but mainly focusing on Python, as opposed to Rmd on R). It hence, albeit new, can be a light-weighted alternative to Jupyter, with wider range of extensions and aesthetically pretty outputs thanks to Pandoc. The best thing is Quarto can compile both Jupyter Notebook ipynb file and qmd file, so it is great for VSCode to adopt it somehow.

**Comment by DonJayamanne** [comment]
Thanks for three suggestion.

**Comment by danieltomasz** [comment]
Quarto has it own extension now https://github.com/quarto-dev/quarto-vscode

**Comment by DonJayamanne** [comment]
Closing this issue in favor of [quarto-dev/quarto-vscode](https://github.com/quarto-dev/quarto-vscode) extension
