### ISSUE TITLE
Tests are broken as Python extension will always using virtual envs as active interpreter

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8609]
In our tests we expect Interpreter A to be the active interpreter,
We create some virtual envs in the workspace folder and Python extension now uses that as the active interpreter.

This breaks our tests.

**TODO:**
* Force python to use the specific interpreter as active interpreter

We're already forcing Python extension to use a specific interepter by iniitalizing the pythonPath and `defaultInterpreterPath`
Find out how to force the interpreter (I thought we already do that by initializing the defaultInterpreterPath)

**Comment by greazer** [comment]
Fixed, we think.
