### ISSUE TITLE
%load %hist should load cells from history to the active cell

### ISSUE THREAD

**Issue by bdrum** [microsoft/vscode-jupyter#8623]
Hi! Thanks for your work guys! This really nice and allow us to be more productive. All of you are amazing! 

I have a feature request that touched interactive jupyter notebook. It's not important, but perhaps it no so complex to make it.

Please, let me show.
In ipython user has an opportunity to upload any executed cells to the active cell via:

~~~python
%load %hist 1-5
~~~

You can see it in action
![image](https://user-images.githubusercontent.com/16210997/147486408-482d40a4-6753-4be4-86ed-7b763c181a05.png)

It very useful when you test something and then you want to save part of your experience. (Sure you can use save session and then edit file, but you see first way much easier).

The problem doesn't exist in jupyter notebook because it allows user to edit any cells.

In case of I miss something and you know other solution please inform me about that. I will be really appreciate.

Good luck!

**Comment by greazer** [comment]
@bdrum Thanks for the suggestion!

**Comment by DonJayamanne** [comment]
This should be working now,
Closing this as fixed,  (I just tested thsi)
