### ISSUE TITLE
Plotly not rendering at all in latest insiders build.

### ISSUE THREAD

**Issue by gampx** [microsoft/vscode-jupyter#8624]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Issue Type: <b>Bug</b>

Open remote vs code with jupyter extension. Create cell with plotly FigureWidget, execute it.

Expected result:
Figure widget is displayed (as in jupter lab)

Actual result:
Error message is displayed: Failed to fetch dynamically imported module: https://vscode-remote+ssh <...> .vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.1.1001614873/out/datascience-ui/ipywidgetsRenderer/ipywidgetsRenderer.js

Meanwhile, it works sometimes, especially when I roll back to older version of jupyter extension. My guess is that it takes too much time to load dynamically jupyterlab-plotly module.

Extension version: 2022.1.1001614873
VS Code version: Code - Insiders 1.64.0-insider (Universal) (7b9e5c32a053669d4e72f998e4fa217090c32f59, 2021-12-22T05:14:43.841Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 4.15.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|64.00GB (4.85GB free)|
|Process Argv|--crash-reporter-id ef9547d4-00e5-45ab-b7d0-0dc61911ea29|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev-docker|
|OS|Linux x64 4.15.0-48-generic|
|CPUs|Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz (56 x 1000)|
|Memory (System)|503.56GB (101.44GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
vscop804:30404766
vscop453:30404998
vsclayoutctrc:30405799
py55gd98:30408621
vscexrecpromp3c:30407757
azactmsalcf:30409288

```

</details>

### VS Code Version

Version: 1.64.0-insider (Universal) Commit: 7b9e5c32a053669d4e72f998e4fa217090c32f59 Date: 2021-12-22T05:14:43.841Z (5 days ago) Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Darwin x64 20.6.0

### Jupyter Extension Version

v2022.1.1001614873

### Jupyter logs

```shell
Error loading preloads:
Failed to fetch dynamically imported module: https://vscode-remote+ssh-002dremote-002dev-002ddocker.vscode-resource.vscode-webview.net/root/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.1.1001614873/out/datascience-ui/ipywidgetsRenderer/ipywidgetsRenderer.js
```

### Coding Language and Runtime Version

Python 3.8.8

### Language Extension Version (if applicable)

Python Extension

### Anaconda Version (if applicable)

-

### Running Jupyter locally or remotely?

Remote

**Comment by greazer** [comment]
@gampx, there's something fishy going on here. I am unable to get plotly to work at all. So I changed the title. :) We'll be taking a look real soon.

**Comment by greazer** [comment]
Seems highly related to https://github.com/microsoft/vscode/issues/139609

**Comment by rchiodo** [comment]
This is a vscode issue. The one mentioned. We don't load the prerenderers ourself.
