### ISSUE TITLE
Widget not loading and no error message to say why

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#8626]
Issue Type: <b>Bug</b>

<img width="437" alt="image" src="https://user-images.githubusercontent.com/876920/147704497-715b732f-a041-40bb-8095-2009b57f6029.png">

After clicking enable downloads, we still can't see the widget being rendered properly and there is no hint what we should do next.

Extension version: 2022.1.1001614873
VS Code version: Code - Insiders 1.64.0-insider (Universal) (7b9e5c32a053669d4e72f998e4fa217090c32f59, 2021-12-22T05:14:43.841Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|32.00GB (0.05GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --enable-proposed-api donjayamanne.jupyterpowertools --enable-proposed-api rebornix.better-jupyter-errors --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rchiodo** [comment]
Do you have an example notebook? Qgrid may not work. Looks like qgrid 1.1.1 is the only one on the CDN.

https://www.jsdelivr.com/package/npm/qgrid

**Comment by roblourens** [comment]
How do I get a widget that fails to load?

**Comment by rchiodo** [comment]
Install qgrid I think? At least the example that @rebornix mentioned was using qgrid but with a version too new.
