### ISSUE TITLE
Offline import of Jupyter (ms-toolsai.jupyter, v2021.11.1001550889) fails

### ISSUE THREAD

**Issue by jnjus** [microsoft/vscode-jupyter#8627]
## Environment data

-   VS Code version: 1.63.2
-   Jupyter Extension version v2021.11.1001550889
-   OS: Windows 10 20H2

## Expected behaviour

Expected successful install as the following python exentions had no issues:
ms-python.python-2021.12.1559732655.vsix
ms-python.vscode-pylance-2021.12.2.vsix

## Actual behaviour
Install fails: "Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.63.2'."

![image](https://user-images.githubusercontent.com/76278125/147704812-662d611b-a774-44f1-9ae9-7fc95d549d59.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Download extension from https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

![image](https://user-images.githubusercontent.com/76278125/147704872-36505376-e138-4819-9457-8405006e8cc7.png)

2. "Import from VSIX" on airgapped VSCode instance
3. Failure

FWIW - Installing to an online instance of VSCode through the extension marketplace works - same version.

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment]
This is a known problem. The marketplace lists ALL versions of the extension but doesn't distinguish between insiders or stable versions of VS code.

Please upvote this issue here:

https://github.com/microsoft/vsmarketplace/issues/43
