### ISSUE TITLE
Intellisense Not Working for Notebook in Remote-SSH, Jupyter-Server Remote

### ISSUE THREAD

**Issue by mp83782** [microsoft/vscode-jupyter#8628]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

- Open Remote-SSH Window
- Open Jupyter Notebook (.ipynb)
- import code from external module
- No ability to click-through, get 'No definition found...' when exec 'Go To Definition'

### VS Code Version

Version: 1.63.2 Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3 Date: 2021-12-15T09:39:46.686Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Linux x64 5.11.0-43-generic snap

### Jupyter Extension Version

v2021.11.1001550889

### Coding Language and Runtime Version

Python 3.8.10

### Language Extension Version (if applicable)

v2021.12.1559732655

### Running Jupyter locally or remotely?

Remote

**Comment by mp83782** [comment]
This doesn't appear to be related to Remote-SSH as I also see the issue on a local window. 'Go To Definition' works if 'Jupyter Server' is local and does not work if 'Jupyter Server' is Remote.

**Comment by amunger** [comment]
Does the external module that you're trying to navigate to exist in the remote server?

**Comment by mp83782** [comment]
Yes, and this happens with builtins as well (e.g. map). Right now, I am using 'Remote-SSH' and then using a local Jupyter Server (which is still remote on the machine that I am ssh'ed into) and definition navigation works.

**Comment by greazer** [comment]
@mp83782, Thanks for the feedback. Intellisense on remote is currently supported in the latest VS Code Insiders build. This will be released in the next Stable build. 

Going to definition for a function defined on a remote machine isn't supported by the PyLance language service.
