### ISSUE TITLE
Rainbow syntax highlighting 

### ISSUE THREAD

**Issue by kuelumbus** [microsoft/vscode-jupyter#8640]
## Environment data

Version: 1.64.0-insider
Commit: 990ad4044032b05c0ebf0f67f800c5845baad4c7
Date: 2022-01-04T05:16:47.911Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.157-17182-g2325f50676ee

-   Jupyter Extension version (available under the Extensions sidebar): 2022.1.1001614873
-   Python Extension version (available under the Extensions sidebar): 2022.0.1612153341-dev
-   OS (Windows | Mac | Linux distro) and version: Ubuntu
-   Python and/or Anaconda version: Python 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): poetry
-   Jupyter server running: Remote 

## Actual behaviour

![image](https://user-images.githubusercontent.com/44866753/148134624-fa8cd848-da2a-4057-b27b-debe276ddfa2.png)
![image](https://user-images.githubusercontent.com/44866753/148134834-d8f16863-c569-4ded-a86c-291e41e35af3.png)
![image](https://user-images.githubusercontent.com/44866753/148134884-905252f6-5d6b-439c-ac19-b68205ff99ab.png)

## Steps to reproduce:

I don't see rainbow syntax highlighting in a freshly opened notebook. It gets triggered by something. I have recently started using Github Copilot, not sure if this is related. Autocompletion is broken when I see the rainbow.

**Comment by rchiodo** [comment]
Thanks for the bug. What version of pylance are you using? It also needs to be the latest. 

Do you have any more repro steps? In the background we generate a concatenated python file of all of the python cells in the notebook. This rainbow effect can happen if we somehow don't update the concatenated file correctly. Magics might cause the problem, but without a repro it's hard to tell what went wrong.

Can you try setting these two values and reproing the issue?

```json
    "notebook-intellisense.trace.server.verbosity": "Verbose",
    "notebook-intellisense.logLevel": "Trace",
```

That should generate extra output for the pylance server. In an output tab that looks like your kernel name. 

![image](https://user-images.githubusercontent.com/19672699/148137812-1cc394aa-efed-4e48-abee-d0a5baae5760.png)

**Comment by kuelumbus** [comment]
Pylance is at 2021.12.3-pre.1. I have set the two values and post the output if I see it again.

**Comment by kuelumbus** [comment]
I am not seeing this anymore. Will reopen in case I see it again. Thanks for the help!
