### ISSUE TITLE
Marketplace's Extension Icon Update

### ISSUE THREAD

**Issue by SinaMobasheri** [microsoft/vscode-jupyter#8641]
it's no big deal but marketplace's extension icon is not clean icon (look sharp edges) <br/>
![image](https://user-images.githubusercontent.com/60809106/148268378-8931dbf7-2230-4a72-8da2-22fce7a28345.png) <br/>
compare to this one <br/>
![image](https://user-images.githubusercontent.com/60809106/148268433-acdada55-a3e3-40a7-8b2d-da88cf5a7055.png)

I'm curious why is that... ? isn't the second one is nicer to look at 🤔

**Comment by rchiodo** [comment]
I believe the icon we use was the allowed icon from the jupyter group. The other one was created by the author of that extension and is not the official jupyter icon.
