### ISSUE TITLE
Azure docs for using remote jupyter should be more descriptive

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8643]
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-set-up-vs-code-remote?tabs=studio

Customers aren't sure why remote doesn't sync files automatically (basically this issue here: https://github.com/microsoft/vscode-jupyter/issues/1601)

**Comment by rchiodo** [comment]
We could indicate the files aren't on the remote machine (with a diagram explaining how the server is different from where VS code is running) and then offer some suggestions on how to get them there?

**Comment by greazer** [comment]
Probably makes sense to consolidate the docs on setting this stuff up in one place. Whether we do something to automatically copy workspace files to a remote machine is something we need to discuss. That's the topic of https://github.com/microsoft/vscode-jupyter/issues/1601

**Comment by DonJayamanne** [comment]
@sevillal Perhaps you might want to take a look into this.
Closing as this isn't related to Jupyter extension.
