### ISSUE TITLE
ModuleNotFound errors on remote could indicate that files are not copied to the remote machine

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8644]
There's some confusion on this issue here:
https://github.com/microsoft/vscode-jupyter/issues/1601

People don't expect a remote jupyter server to not have the files from their workspace. I'm hypothesizing the most likely time they hit this error is when they either:

```FileNotFound``` when reading in a .csv file
```ModuleNotFound``` when importing a python file.

We could detect these two issues and add extra text about remote file syncing.

**Comment by DonJayamanne** [comment]
Closing thisx issue as there haven't been any upvotes nor further complaints about this issue,
