### ISSUE TITLE
Deleting a cell before it executes gives an error in the Interactive Window

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8646]
![image](https://user-images.githubusercontent.com/19672699/148300853-7e633978-f72b-4972-9d2e-73b27cc129fc.png)

**Comment by amunger** [comment]
My guess is that it errors when trying to update the `goto cell` code lense since it still runs the expected cell correctly if it's edited before then. Should be a pretty easy fix if so - just harden that update logic.
