### ISSUE TITLE
Informative coloring of jupyter outline headers

### ISSUE THREAD

**Issue by Ozziko** [microsoft/vscode-jupyter#8652]
Issue Type: <b>Feature Request</b>

In the spirit of jupyter-contrib-nbextensions, I suggest informative coloring of outline headers for jupyter notebooks:
* Headers of cells that are currently running - in orange
* The header or a cell that issued an error - in red
* The header of the current cell that is selected / being edited - in green

Extension version: 2021.11.1001550889
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by amunger** [comment]
Thanks for the suggestion.

**Comment by DonJayamanne** [comment]
Thanks for the feature suggestion unfortunately there haven't been enough upvotes or comments on this for a while.
Closing this issue for now
If you still believe this is requried please feel free to ping here and we'll reopen this issue or please feel free to create a new issue
