### ISSUE TITLE
Automated activation of conda environment for a selected remote kernel

### ISSUE THREAD

**Issue by RGBYCP** [microsoft/vscode-jupyter#8659]
## Environment data

-   VS Code version: Version: 1.63.2 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: conda 4.10.3, Python 3.6.7 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | remote

## Expected behaviour

Automated selection of the corresponding conda environment for a selected remote kernel.

## Actual behaviour

Kernel is selected, but environment remains the base environment. Previously, when the kernel was selected, the conda environment changed automatically to the conda environment based on which the kernel was created.

## Steps to reproduce:

I open the remote ssh connection. I try to select the kernel, but the conda environment remains the base environment. 
I have to request the corresponding conda environment with `conda activate environment-name` in the terminal.

**Comment by greazer** [comment]
Hi @RGBYCP, we have been making changes in this area. So, if you could try using the latest Insiders build of VS Code and the extension, that would be good. If it still repro's there, please reopen this bug. Thanks!

**Comment by RGBYCP** [comment]
@greazer  Can I still ask questions here, please? What is the latest Insiders build of VS Code and the extension? 
My version are not new enough? I thought, they were. Sorry. Thanks for pointing me in the right direction.
