### ISSUE TITLE
Automatically jump to a running cell that requires an interactive action 

### ISSUE THREAD

**Issue by Ozziko** [microsoft/vscode-jupyter#8662]
Issue Type: <b>Feature Request</b>

When running (all or multiple) cells in a jupyter notebook, please automatically jump to a cell that requires an interactive action (e.g. with an input prompt) - to save the time of manual searching for the relevant cell...

Extension version: 2021.11.1001550889
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by greazer** [comment]
Thanks for the suggestion! We'll consider it in a future release.

**Comment by DonJayamanne** [comment]
This issue has been open for over a year and we haven't received any upvotes on this.
Hence closing this issue.
