### ISSUE TITLE
Enable Jupyter Extension for web-based hosts (github.dev, vscode.dev)

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#8664]
We need to:
- Define the behavior we want to work.
- Investigate and cost 
- Implement

Lots of work here.

**Comment by DonJayamanne** [comment]
Suggestion - I would like to see support for remote Jupyter kernels

**Comment by rsha256** [comment]
Has there been any progress on this since?

**Comment by DonJayamanne** [comment]
Closing this issue as most (if not all) of the work has been done and this hasn't been added to any milestone since March
