### ISSUE TITLE
button near dataFrame preview that opens data viewer direcly 

### ISSUE THREAD

**Issue by maliknajjar** [microsoft/vscode-jupyter#8668]
### something like this
![Capture](https://user-images.githubusercontent.com/59079190/148869203-d52fffa6-5afe-49b8-bb1d-848d7950015f.PNG)

**Comment by rchiodo** [comment]
Thanks for the suggestion. Sounds like a good idea to me.

**Comment by maliknajjar** [comment]
yes, indeed

**Comment by matangover** [comment]
Adding sub-request to this feature -- it should work even when the result is not stored in a named variable. This can be done by taking the output value from IPython's `Out` object.

**Comment by roblourens** [comment]
Merging into https://github.com/microsoft/vscode-jupyter/issues/5229
