### ISSUE TITLE
Some Keyboard Shortcuts do not work.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#8672]
## Environment data

Build of Visual Studio Code - Insiders: 1.64.0-insider (user setup)  
Build of python-insider: v2022.0.1684931726-dev
Build of Pylance-insider: v2022.1.0
Build of Jupyter-insider: v2022.1.1001614873

## Steps to reproduce:
1. Select a notebook cell by clicking on it
**2. Move selection up and down with `j`, `k` and arrow keys.**
3. Focus a cell by double clicking on it or hitting the enter key when selected
4. Move selection through the code with the arrow keys.
5. Verify selection travels between focused cells
6. Hit escape when a cell has focus and verify it becomes selected instead of focused
7. Hit `y` on a markdown cell when not focused and see that it becomes a code cell
8. Hit `m` on a code cell when not focused and see that it becomes a markdown cell
**9. Hit `l` on a code cell and verify line numbers appear**
**10. Hit `o` on a code cell with output and verify that outputs disappear**
**11. Hit `d` + `d` and verify a cell is deleted.**
**12. Hit `z` and verify a deleted cell reappears**
**13. Hit `a` and verify the selected cell moves up**
**14. Hit `b` and verify the selected cell moves down**
15. Hit `shift+enter` and verify a cell runs and selection moves to the next cell
16. Hit `alt+enter` and verify a cell runs and a new cell is added below
**17. Hit `ctrl+enter` and verify a cell runs and selection does not change**

## Actual behaviour
All boldfaces steps do not work.  When enter this shortcut in the keyboard, no response in the Notebook.
And when hit `ctrl+enter`, the cell runs but also add a new cell is added below.

**Comment by rchiodo** [comment]
@linette-zyy did you have this extension enabled?

![image](https://user-images.githubusercontent.com/19672699/149190025-3f462e51-a0c3-407d-98b2-465d84ee5b27.png)

It provides these shortcuts. They all worked for me except for 'd+d' behaving weird.

**Comment by rchiodo** [comment]
'd+d' seems to delete the cell below and then the undo stack gets totally messed up.

**Comment by linette-zyy** [comment]
@rchiodo Thank you! 
I have installed the Junpyter Keymap extension and these Keyboard Shortcut work well.  And I found after hit d + d, the cell is deleted.  It works well. So I closed this issue.
