### ISSUE TITLE
Pylance errors in notebook after editing for over an hour.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8678]
@rchiodo I don't know why my Pylance give me a lots of errors, but the cell and whole notebook I can run without any issue (no errors). Here is list of founded errors: 
  * Unindent not expected
  * Unexpected indentation
  * Expected expression
  * "(" was not closed
  * and so on ...
 

Thanks.

_Originally posted by @markub3327 in https://github.com/microsoft/vscode-jupyter/issues/4307#issuecomment-1011474765_

**Comment by rchiodo** [comment]
@markub3327, I opened this based on your comment on #4307.

Can you provide:
- VS code version
- Python Extension version
- Pylance Extension version
- Jupyter Extension version

And a screenshot of the errors?

Thanks.

**Comment by markub3327** [comment]
Hi,
 
 * OS: Darwin arm64 21.2.0 
 * VS code version 1.63.2 (Universal)
 * Python Extension v2021.12.1559732655
 * Pylance Extension v2022.1.0
 * Jupyter Extension v2021.11.1001550889

Sorry, after the restart of VSCode all errors were out. I tried to provide you screenshot as fast as possible. I think the errors are shown for a long time opened VSCode, because I don't close it for a few days and don't restart my macOS too.

**Comment by markub3327** [comment]
Now I get a warnings about variable that not existed and variable that is correctly defined. Both are marked as undefined variable.

Here is the screenshot
<img width="1109" alt="Snímka obrazovky 2022-01-13 o 12 58 41" src="https://user-images.githubusercontent.com/74611856/149326768-8c7bf958-dafb-4d2d-8713-a6ab20b6362e.png">
:

**Comment by markub3327** [comment]
@rchiodo Now, I get what we are talking about. There are three errors, but my notebook can be run successfully (can see check mark under the cell and the output too). This issue appeared after the approximately 1 hour.

Here is the screenshot:
<img width="1115" alt="Snímka obrazovky 2022-01-13 o 13 05 09" src="https://user-images.githubusercontent.com/74611856/149327613-a985ec54-3bfa-4349-be3c-ebbc913e1a8c.png">

**Comment by rchiodo** [comment]
Thanks that helps.

Can you include your entire notebook here so I can try on my machine?

Do the errors appear only after editing a cell?

Does it require you edit as soon as the notebook opens? There might be a timing related problem with the changes.

**Comment by markub3327** [comment]
Yes errors appear after coding in cell (editing cell, writing new code to existing cell or after copying code by CTRL+CV) after approximately 1 hour since VSCode is started.

I edit cell as the notebook opens, because I working on it. If I only run cell after the VSCode is opened there is nothing error/warning.

I can provide a smaller version of it with part where was issue:
[Issue.zip](https://github.com/microsoft/vscode-jupyter/files/7866482/Issue.zip)

**Comment by rchiodo** [comment]
> I edit cell as the notebook opens, because I working on it. If I only run cell after the VSCode is opened there is nothing error/warning.

Does this mean the problem only occurs if you edit really quickly? That if you run a cell first before editing (or wait say 20 seconds), you can't repro the problem?

The reason I ask is because there's a delay internally before the server that generates these errors is ready. It might be that only part of your edit is getting to the server, and is therefore making only half of your edit (and generating the strange problems).

I can't repro any problems with your notebook myself, but I may not be editing it fast enough.

**Comment by rchiodo** [comment]
There's also some extra settings that might show us what the problem is (or at least give me enough information to repro it).

If you set these two settings your settings.json:

```json
    "notebook-intellisense.logLevel": "Trace",
    "notebook-intellisense.trace.server.verbosity": "Verbose",
```

This should generate an extra output tab like so:

![image](https://user-images.githubusercontent.com/19672699/149426158-f495791b-7b11-482b-80b8-f19913456bb3.png)

The contents of that tab (if you can repro on your example notebook) should allow me to try and recreate your edits to see if I can repro locally.

**Comment by markub3327** [comment]
No the problem only occurs if editing the cell many time for a long time (after 1hour of working on them). The issue cannot be saw if working a short time with notebook, but after a long time. Now, I tried copy code from the website and work with them and I get errors but cell can be run.

Screenshot:
<img width="1109" alt="Snímka obrazovky 2022-01-14 o 1 42 23" src="https://user-images.githubusercontent.com/74611856/149432137-2e0cc2e8-17ac-44c6-b241-fab0f45cd71c.png">

[Debug.zip](https://github.com/microsoft/vscode-jupyter/files/7866855/Debug.zip)

**Comment by rchiodo** [comment]
Notes for triage: Debug.zip should have enough info for us to repro

**Comment by rchiodo** [comment]
After implementing something to replay the log, I believe this was fixed with recent updates.

The root cause was the cell with ```%matplotlib inline``` in it. There was a bug handling this in intellisense before.

You don't really need ```%matplotlib inline``` as this is the default.

**Comment by markub3327** [comment]
@rchiodo 

I saw `%matplotlib inline` in some example of using Matplotlib in Jupyter notebook. If I'll see the same issue in future, I'll write here.

Thanks a lot.
Have a nice day.

**Comment by rchiodo** [comment]
Sorry I should have said it's fixed in the insiders build (and prerelease bits) of VS code and Jupyter. They should ship to stable next week.

**Comment by bapungiri** [comment]
Thanks @rchiodo for fixing/debugging the issue. Wondering if the fix also takes care of `%matplotlib widget` cells, as I also saw some of these random pylance errors popping up in notebooks.

**Comment by rchiodo** [comment]
@bapungiri I hope so. However if you do hit a problem, please turn these settings on:

```
    "notebook-intellisense.logLevel": "Trace",
    "notebook-intellisense.trace.server.verbosity": "Verbose",
```
And collect the trace from the output window for the intellisense for your kernel. That should let me repro whatever issue you find.

Thanks.

**Comment by bapungiri** [comment]
Sure, will do if I continue to see these errors after next week's stable release. Thanks.

**Comment by rchiodo** [comment]
No comments since the last release so assuming this is all good.
