### ISSUE TITLE
Ability to browser anndata objects like Pandas dataframes

### ISSUE THREAD

**Issue by rangan2510** [microsoft/vscode-jupyter#8691]
[anndata](https://anndata.readthedocs.io/en/latest/) objects are extensively used across single cell data analysis and the ability to go through them (sort and filter them) would be immensely helpful.

**Comment by IanMatthewHuff** [comment]
Just to check you'd like the ability to open the anndata object in this view here from the Jupyter variables window?
![image](https://user-images.githubusercontent.com/812783/149411456-52281877-fe17-4ac6-8824-aa3493833e8b.png)

**Comment by rangan2510** [comment]
Yes, something like this. Since Anndata objects are nested objects, we would need to see the tables present inside the dictionaries.

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1138
