### ISSUE TITLE
Ability to re-run last commands in IPython Interactive Windows by pressing "up" arrow key.

### ISSUE THREAD

**Issue by rangan2510** [microsoft/vscode-jupyter#8692]
Would like the ability to scroll through the last run commands in the python interactive window. This would be very helpful when I am running a cell (marked with %##) in a script and then I want to have a quick look into the variables in the ipython window.

**Comment by greazer** [comment]
Perhaps a setting would make most sense here, since many people may not want to have their typed IW history cluttered with cells run via codelenses.

**Comment by greazer** [comment]
Alternatively, perhaps we just record every execution regardless of how it happens. Provide a visible and accessible toggle in the IW itself to control whether non-typed executions are included when arrowing up. 

Additionally or alternatively, consider allowing a shift/ctrl/alt/cmd modifier to control which executions are included when pressing up arrow.

**Comment by amunger** [comment]
closing for https://github.com/microsoft/vscode/issues/129081 since this would be done in core
