### ISSUE TITLE
Copy function for Jupyter notebook plot viewer

### ISSUE THREAD

**Issue by kjohnsen** [microsoft/vscode-jupyter#8699]
When creating a plot in a Jupyter notebook, it'd be nice to be able to right click and copy an image, either straight from the notebook or from the viewer tab that pops up when you click the little graph icon.

**Comment by amunger** [comment]
thanks for the suggestion

**Comment by amunger** [comment]
Looks like there is already an issue in core for this, which is where it would need to be implemented: https://github.com/microsoft/vscode/issues/129880
