### ISSUE TITLE
Ginormous fonts on Linux with HiDPI

### ISSUE THREAD

**Issue by dimitry-ishenko** [microsoft/vscode-jupyter#8715]
Issue Type: <b>Bug</b>

Cells rendered by Jupyter have ginormous fonts on Linux with HiDPI. This only affects Jupyter. Other documents look fine.

Here is an example. Notice how normal text is much larger than the text in the EXPLORER pane. Text in a code block is also larger than the one in the edited cell. And the dataframe output is so big, you can hardly see any data.

![Screenshot from 2022-01-17 10-08-38](https://user-images.githubusercontent.com/2858291/149795205-930385e8-37c9-44dc-b3e0-babdcd0a198a.png)

Steps to reproduce:

1. Create new Jupyter notebook.
2. Enter anything in a cell
3. Press Ctrl + Enter to render the cell.

Extension version: 2022.1.1001614873
VS Code version: Code - Insiders 1.64.0-insider (6612ae0f8b5d9c0d86518ebbd153c724a7cbcf73, 2022-01-17T05:16:08.768Z)
OS version: Linux x64 5.13.0-25-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.22GB (0.21GB free)|
|Process Argv|--unity-launch --crash-reporter-id 2273c5d1-5f55-44d1-afd8-13c81c1bf0ca|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by dimitry-ishenko** [comment]
For comparison, here is a Markdown document with preview.

Notice, how the normal text matches the text in the menu and is only slightly larger than the EXPLORER pane text.

![Screenshot from 2022-01-17 10-08-30](https://user-images.githubusercontent.com/2858291/149796817-f1d098cb-bf3c-4721-ac2a-097c80a889cf.png)

Original text being edited:
![Screenshot from 2022-01-17 10-08-25](https://user-images.githubusercontent.com/2858291/149796764-36fadb23-be48-4d0c-8fc1-a69c92bde69f.png)

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, this is by design.
We've increased the font size of markdown output to improve readability (based on user feedback).
See here for details https://github.com/microsoft/vscode/issues/126294

Settings to control this can be found here https://github.com/microsoft/vscode/issues/126294#issuecomment-964601412

**Comment by dimitry-ishenko** [comment]
That fixed it to a degree. If I match the font size of the editor, normal text and code blocks look fine. But the headers in Jupyter are still ginormous and so is the line spacing.

Markdown:
![Screenshot from 2022-01-17 18-40-34](https://user-images.githubusercontent.com/2858291/149848226-582f93f1-63f0-4807-a9ee-33c1311989c6.png)

Jupyter:
![Screenshot from 2022-01-17 18-40-44](https://user-images.githubusercontent.com/2858291/149848236-1a11eae6-5517-4dcc-a9d4-77296bd068ae.png)

Please reopen.

**Comment by dimitry-ishenko** [comment]
Also, if you look at [@greazer 's comment](https://github.com/microsoft/vscode/issues/126294#issuecomment-906837889) in that issue, Heading 4 is rendered around the same size as normal text.

**Comment by dimitry-ishenko** [comment]
Even the text here on github:

#### Heading 4

**Comment by dimitry-ishenko** [comment]
@DonJayamanne any other suggestions? That didn't fully handle the problem for me
