### ISSUE TITLE
I wish the Interactive Window wouldn't steal editor group while a script is running.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#8720]
1. Open a python script with cells that will take a while to run.
2. Start the script with "Run Below" on the first cell.
3. Open an MD file and then open the preview. The preview should open on top of the Interactive Window.

As the IW gets updated, it will pop to the top of the editor group that it shares with the MD preview window.

Note that this doesn't seem to happen with stdout output. But it does happen with Plotly. Not sure about other plotting packages.

**Comment by rchiodo** [comment]
We use a vscode API to 'scroll' to the latest cell on output. So this would require changes to the VS code API to support not 'stealing' the focus.

**Comment by rchiodo** [comment]
When we implement this, we need to make sure 'goto cell' does still set the focus. We can probably do this with another command though.
