### ISSUE TITLE
Being prompted to switch to Jupyter pre-release. I'm already on pre-release.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#8724]
On my vscode insiders I'm seeing this:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/11685408/150021315-46a5a992-748d-4365-922e-f4af10098dc3.png">

Yet my extension is this:
<img width="619" alt="image" src="https://user-images.githubusercontent.com/11685408/150021357-6d1edee3-c41e-4d1b-bfa9-d0aae24ce1cf.png">

**Comment by greazer** [comment]
I'm continuously getting prompted to install pre-release, even though I have it already installed. On VS Code reload it pops up again and again.

**Comment by rchiodo** [comment]
Yes because it doesn't detect you're in prerelease version for some reason. It reads the package.json on disk (at least I thought it did). Works fine if this same metadata is added to the package.json when debugging so not sure why the ```__metadata.preRelease``` isn't readable at runtime.

**Comment by rchiodo** [comment]
Oh never mind, it's because it's been webpacked. The package.json was read during build time, and embedded in the webpack.
