### ISSUE TITLE
Kernel-related issues after connecting to Azure ML compute instances.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-jupyter#8725]
Note: These are issues from Azure ML wherein the users did not provide contact information nor details about their extension version (we can assume latest as that is what we install for them when initiating the remote connection). If there are recommendations for how we should be handling these incoming issues and/or what additional information we need from the user, please let me know.

Issue 1:
1. User initiates remote connection through Azure ML extension.
2. User opens Notebook and attempts to connect to a kernel.
3. The kernel is in a continuous **queueing** state.
4. User has to "restart" the kernel to get past the queueing state. (Unsure what restart means in this context).

Issue 2:
1. User initiates remote connection and opens Notebook.
2. User selects a kernel and Jupyter extension initiates the connection to that kernel.
3. The overall remote connection hangs for a long time when trying to connect to the kernel.

I'm curious why kernel connections would take a long time to the point where the overall connection begins to hang? I'm also curious how kernel connection can affect the overall connection?

Issue 3:
1. User is originally working on a Notebook in the Azure ML studio. User clicks out to VS Code.
2. The same notebook context is retained and the notebook is opened. The kernel information is not persisted. The user describes it as "the kernel is not attached".
3. The user tries to change the kernel through the "Pick a Jupyter server" option in the status bar. None of the presented options were found "helpful" (verbatim).

I understand that Jupyter server selection and kernel selection are two different things. This is less of an issue with kernel reliability/perf and more around how we can make it more clear to users what the difference is between the server and kernel selector. 

Re: the lack of persisted kernel context -- is there a way for us to add metadata to the notebook for the Jupyter extension to use and default to a server / kernel?

**Comment by rchiodo** [comment]
It would be better if you entered these 3 issues separately, but I can comment on them here.

Issue 1: - What does queueing mean? There's no 'queue' for kernels. Do you mean it just shows busy forever? 
Issue 2: - Sorry but I have no data on why the remote kernel would take a long time. We'd need logs (and probably extra logging) to investigate. We are just making websocket connections to the remote server.
Issue 3: - Kernel information is used to pick the 'suggested' kernel. This data should already exist in the notebook metadata. However VS code doesn't use this to pick the kernel, it just puts it at the top when they pick the kernel. Sounds like the user doesn't realize they pick it from the top right though. They were trying to pick the server instead.

All 3 of these require jupyter logs and aren't really actionable at this point. Unless you can get the contents of the 'jupyter' output tab from these users.

**Comment by rchiodo** [comment]
There is a way to 'force' a notebook to pick a specific kernel though. We use this in the remote situation when reopening a notebook.

There's a command 'notebook.selectkernel' that can be sent to force the UI to pick a kernel.

We could special case Azure ML to do this on transferring a notebook to VS code.
