### ISSUE TITLE
Code collapses by default when sending to interactive window

### ISSUE THREAD

**Issue by parasurama** [microsoft/vscode-jupyter#8730]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Code block collapses by default when sending code from editor to the interactive window with `Shift`+`Enter`

I have the collapse setting turned off
"jupyter.collapseCellInputCodeByDefault": false

Extension version: 2021.12.1559732655
VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1062.1.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id ff063a8f-916a-4966-bb68-317ca9914445|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: prasannac7|
|OS|Linux x64 3.10.0-1062.1.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (8 x 2100)|
|Memory (System)|31.26GB (19.19GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30424896
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614

```

</details>

**Comment by rchiodo** [comment]
This setting is actually obsolete now. There is a new setting in VS code core (it handles the interactive window now).

See this issue here:
https://github.com/microsoft/vscode/issues/140126
