### ISSUE TITLE
The kernel failed to start as a dll could not be loaded. View Jupyter log for further details.

### ISSUE THREAD

**Issue by z11y23h58** [microsoft/vscode-jupyter#8734]
for any code:

- jupyter notebook & vscode + vscode-jupyter Remote:
-- no bug

- vscode + vscode-jupyter LOCAL
--  The kernel failed to start as a dll could not be loaded. 
--   View Jupyter log for further details.

## Environment data

-   VS Code version: 1.63.2
-   Jupyter Extension version (available under the Extensions sidebar):  v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar):  v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version:  windows 11
-   Python and/or Anaconda version: Miniconda3-py37_4.10.3-Windows-x86_64.exe
-   Type of virtual environment used : conda base
-   Jupyter server running: Local 

## Expected behaviour

1. uninstsall conda
2. reinstall Miniconda3-py37_4.10.3-Windows-x86_64.exe
3. conda install pyzmq==19.0.2 (pyzmq>=20.0.0 another bug)
4. conda install jupyter ipykernel
5. jupyter notebook & vscode + vscode-jupyter Remote: no BUG
6.  vscode + vscode-jupyter LOCAL. a DLL could not be loaded

## Actual behaviour
maybe cos os is WIN11

**Comment by rchiodo** [comment]
Thanks for the bug. This should be fixed in our latest version. Can you try VS code insiders and the prerelease version of the Jupyter Extension?

**Comment by nirzaa** [comment]
Hi, I have the same bug too but with pip and not conda. A bit strange since there wasn't a bug till now. Would you suggest waiting several days or maybe try the VS code insiders or the prerelease of the Jupyter Extension?
Do you have a link for both of them?

Thanks!

**Comment by nirzaa** [comment]
> Thanks for the bug. This should be fixed in our latest version. Can you try VS code insiders and the prerelease version of the Jupyter Extension?

Hi, I have the same bug too but with pip and not conda. A bit strange since there wasn't a bug till now. Would you suggest waiting several days or maybe try the VS code insiders or the prerelease of the Jupyter Extension?
Do you have a link for both of them?

Thanks!

**Comment by YDX-2147483647** [comment]
For those who are using conda, try `code ./your/workspace/folder` in Anaconda Prompt (or Anaconda PowerShell Prompt) may help.

(My friend meets the same issue today. I guess the `ENV` is broken.)

**Comment by 600212** [comment]
一直使用的VS Code, 突然出现内核启动失败，无法加载dll。因为电脑和英语不是太懂，请直接告诉我怎么处理好吗？

**Comment by z11y23h58** [comment]
> 

下载以前的版本，新版本有bug
