### ISSUE TITLE
Python kernel in Jupyter Notebook is not loading modules from python path

### ISSUE THREAD

**Issue by xiaosihao** [microsoft/vscode-jupyter#8739]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.63.2(universal)
- OS Version:macos 12.1

Steps to Reproduce:

1.Python loaded in the jupyter notebook in VScode cannot load modules put in the python path. It is working fine in the terminal. Check the screenshot.
2.
![image](https://user-images.githubusercontent.com/51140032/149626673-1807efa5-e366-434f-ba28-ee1d70a03e6a.png)

**Comment by rchiodo** [comment]
Thanks for the bug.

Can you run this code in the terminal and in the notebook to see what the difference is?

```
import sys
print(sys.path)
```

**Comment by rchiodo** [comment]
Is ```machine_learning``` your own module? If so that would be the problem. It's not starting the kernel at the same location you're starting your python repl in the terminal. Jupyter kernels start at the same location as the notebook file itself (by default).

You can control this setting with the ```jupyter.notebookFileRoot``` setting.

**Comment by rchiodo** [comment]
Closing for lack of response.
