### ISSUE TITLE
Assertion

### ISSUE THREAD

**Issue by mrx23dot** [microsoft/vscode-jupyter#8743]
Issue Type: <b>Bug</b>

Can't start python debugging, getting the following assertion.
I updated to latest python+jupyther available in VS code-
Win7 x64, I have VC++ redists.
I would expect some more specific prechecks if it doesnt like something in the environment.

![f1](https://user-images.githubusercontent.com/4163396/150221811-01bd49f7-8ba7-4017-93f6-73340f82ccc0.jpg)
![f2](https://user-images.githubusercontent.com/4163396/150221816-b9db3aeb-38de-4b11-884a-544157c68e08.jpg)

Extension version: 2021.10.1101450599
VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.41GB (3.80GB free)|
|Process Argv|--crash-reporter-id d068a291-e2ce-4726-851f-8253022ad348|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30424895
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsrem710:30416614
vsbas813:30425875

```

</details>

**Comment by rchiodo** [comment]
Thanks for the bug.

Ah this likely doesn't work on Windows 7. Not sure why it would assert (should be only debug bits assert). We don't create these assertions, they're from a 3rd party library. 

We do check that zeromq works, but the check is likely causing the assertion.

I believe Windows 7 is no longer supported:
https://www.microsoft.com/en-us/windows/windows-7-end-of-life-support-information

**Comment by rchiodo** [comment]
There is a workaround that might work.

Set this hidden setting:

```json
"jupyter.disableZMQSupport": true
```

**Comment by mrx23dot** [comment]
Seems to have solved the problem, thanks.

Shouldn't the plugin check for max supported os version?
Isn't there a built in VS code matrix?
We all love updates, until it stops working :)

Why is jupyther mandatory for the Python plugin?

**Comment by rchiodo** [comment]
> Shouldn't the plugin check for max supported os version? Doesn't VS code help with that?

The official policy is not to support Win7 - meaning even checking for it. Although this is the fist time somebody has logged a win7 specific issue. I guess if a lot of people have this problem, we might just flip that flag automatically on Win7.

> Why is jupyther mandatory for the Python plugin?

It's not mandatory. You can remove it if you don't want it. It just installs it as a suggestion.
