### ISSUE TITLE
Sinekhaya Brian Ntuli 

### ISSUE THREAD

**Issue by sinekhayantuli** [microsoft/vscode-jupyter#8750]
https://github.com/cmdotcom

**Comment by sinekhayantuli** [comment]
See value on  it

**Comment by IanMatthewHuff** [comment]
@sinekhayantuli  I'm sorry, but this issue doesn't have enough information about your scenario for us to investigate. I'm going to close this down, but if you reply back with information about your scenario as well as expected and actual behavior I can help investigate.
