### ISSUE TITLE
error rendering jupyter notebook 

### ISSUE THREAD

**Issue by lots-o** [microsoft/vscode-jupyter#8755]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2 Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
- OS Version: mac OS Monterey12.1 Apple M1 

Steps to Reproduce:

1.brew install --cask visual-studio-code
2.install jupyter extension 
3. Raise error 
![image](https://user-images.githubusercontent.com/39071632/150146667-f52c2f99-4fbc-4360-b7a5-c4e3911f1c96.png)
![image](https://user-images.githubusercontent.com/39071632/150146794-3aefaa42-5610-44c8-ad05-89eee3b9cd5b.png)

[Modified]
Result after running "extension bisect"
![image](https://user-images.githubusercontent.com/39071632/150188342-b812004a-5490-40de-b0b2-747c96e91de6.png)

- [ ]

**Comment by greazer** [comment]
This is fixed in the latest pre-release build of the Jupyter extension.

**Comment by lots-o** [comment]
@greazer  I appreciate your support !! it works out! (c.f  Jupyter version `v2021.11.1001550889` -> pre-release `v2022.1.1001722501`)
