### ISSUE TITLE
After I do a change in a .py code or Python virtual environment package that the notebook uses, they are not reflected in the notebook and need to close the VSCode and open it again to have them reflected

### ISSUE THREAD

**Issue by monajalal** [microsoft/vscode-jupyter#8767]
So, whenever I change my ViT.py code or install a new package in my Python Virtual Environment, those changes are not picked up by the Jupyter notebook that I am running inside the VSCode. The only way that I am currently able to get them reflected is to close VSCode and open it again which is quite a lot of overhead given I am using SSH to connect to local machine. Is there a way to make these changes seamless ideally?

![Screen Shot 2022-01-21 at 7 00 55 PM](https://user-images.githubusercontent.com/1892917/150615170-c504a2aa-c62a-4327-adf7-797a32f408f6.png)
For example, in the image above, you see even after installing the Python package that is requested, it is still not recognized.

## Environment data

-   VS Code version: XXX
![Screen Shot 2022-01-21 at 7 05 03 PM](https://user-images.githubusercontent.com/1892917/150615254-a4ce113a-345b-4c27-a914-38ce3586ff7a.png)

-   Jupyter Extension version (available under the Extensions sidebar): XXX
![Screen Shot 2022-01-21 at 7 05 46 PM](https://user-images.githubusercontent.com/1892917/150615298-873781f7-d50d-4f6e-94f7-7e073eb7b2e1.png)

-   Python Extension version (available under the Extensions sidebar): XXX
![Screen Shot 2022-01-21 at 7 06 22 PM](https://user-images.githubusercontent.com/1892917/150615335-6cc17470-4710-4fee-a60e-8064ff3cf79e.png)

-   OS (Windows | Mac | Linux distro) and version: XXX
Local:
![Screen Shot 2022-01-21 at 7 06 50 PM](https://user-images.githubusercontent.com/1892917/150615364-586ffc8e-13fe-4d60-a8b0-cc95a2592fd1.png)
remote:
```
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```
-   Python and/or Anaconda version: XXX
```
[19:07:23] (dpcc) jalal@echo:~$ python
Python 3.8.10 (default, Nov 26 2021, 20:14:08)
[GCC 9.3.0] on linux
```
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
Native Python virtual environment on remote machine (name of virt env: dpcc)
-   Jupyter server running: Local | Remote | N/A
Remote

## Expected behaviour

After I closed and opened the VScode (and reconnect to remote host), this is what the expected behavior should be (progress bar for training):

![Screen Shot 2022-01-21 at 7 11 50 PM](https://user-images.githubusercontent.com/1892917/150615792-d6c649f5-720f-4fc8-ba9d-ad6fca1b85f7.png)

This is regarding cell #25 here https://github.com/lucidrains/vit-pytorch/blob/main/examples/cats_and_dogs.ipynb 

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment]
This issue here is related: https://github.com/microsoft/vscode-jupyter/issues/4555

**Comment by rchiodo** [comment]
But for a module install (and if you're not using auto_reload), you have to restart the kernel. You shouldn't have to restart VS code.

**Comment by monajalal** [comment]
Could you please give me a hint how to use auto_reload in jupyter notebook within VSCode? @rchiodo

**Comment by rchiodo** [comment]
The directions here should work (haven't tried it myself in some time)
https://ipython.org/ipython-doc/3/config/extensions/autoreload.html
