### ISSUE TITLE
Display local and remote kernels in together in the kernel picker

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8778]
Refs: #8489

- [x] anyOS @kimadeline 
- [x] anyOS @joyceerhl

Complexity: 4

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%238778%0A%0A&assignees=DonJayamanne)

---

We now allow users to connect to local and remote jupyter servers within the same VS Code session.

## Setup steps:
1. Install some version of python
2. Make sure you have Jupyter installed
	For non-conda environments use the command `python -m pip install jupyter notebook`, and for conda use the commands `conda install -c conda-forge notebook`
2. Install pre-release version of Jupyter & Python extension from marketplace (it has insiders only versions)
3. Start jupyter as follows `python -m jupyter notebook`
4. Copy the url printed in the terminal output (of the form `http://localhost:8888/?token=aae7097a0f2e63`)

## Test steps: (repeat multiple times)
1. Create a jupyter notebook and run a Python cell against a local kernel
2. Open the command palette and select the command `Jupyter; Specify local or remote..`
	* Select the option `Existing` & enter the URl copied earlier
3. Go back into the notebook and select a remote kernel (the remote kernels will be categorized as `(Remote) Jupyter Kernel`)
4. Attempt to run a cell against this Jupyter kernel & verify it works

**Comment by joyceerhl** [comment]
> Install pre-release version of Jupyter & Python extension from marketplace

I see a pre-release option for the Jupyter extension, but not the Python extension. To test this with the Python extension are we supposed to just install the daily channel? 
![image](https://user-images.githubusercontent.com/30305945/151013140-db1e43ad-e3c3-4afd-9afc-cebc013c616c.png)

**Comment by joyceerhl** [comment]
FYI, there were two Create Issue links in this TPI header. I removed the one that pointed to https://github.com/microsoft/vscode-jupyter/issues/8489 so that all the mentions show up linked to this TPI.

**Comment by DonJayamanne** [comment]
> . To test this with the Python extension are we supposed to just install the daily channel?

Yes
