### ISSUE TITLE
Rename the first item in the quick pick for `local or remote jupyter server`

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8780]
This first item doesn't make sense anymore as we always support local & remote now.
Hence the two options are no longer mutually exclusive.

I suggest we just rename it to `None - Do not connect to a remote jupyter server` or the like.

![image](https://user-images.githubusercontent.com/1948812/150701495-133e304b-ac34-4d91-be79-687e8f3011ed.png)

**Comment by rchiodo** [comment]
/verified
![image](https://user-images.githubusercontent.com/19672699/155628593-959fcb84-e3d1-471a-9893-bdfc50d8ac8a.png)
