### ISSUE TITLE
Add SVGs for getting started walkthrough

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#8782]
Add svgs for walkthrough items that don't need a gif per https://github.com/microsoft/vscode-jupyter/pull/8733, e.g.:
- https://github.com/microsoft/vscode-python/blob/main/resources/walkthrough/create-notebook.svg
- https://github.com/microsoft/vscode-python/blob/main/resources/walkthrough/data-science.svg

**Comment by lychung7** [comment]
Here are the SVG illustrations for the walkthrough!
[jupyterwalkthrough.zip](https://github.com/microsoft/vscode-jupyter/files/8159224/jupyterwalkthrough.zip)
