### ISSUE TITLE
Jupyter Notebook output cell display object contents

### ISSUE THREAD

**Issue by brew-guy** [microsoft/vscode-jupyter#8790]
When printing an object in a Jupyter Notebook code cell there should be an option to switch to more detailed output of objects.
Example:
```
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer()
print(count_vector)
```
Outputting the parameter values of the object will be helpful to determine what is set at that point or set by default.
VSCode implementation outputs the class name `CountVectorizer()` without the parameters, whereas online Jupyter instances often include the parameters in the output.

**Comment by DonJayamanne** [comment]
> whereas online Jupyter instances often include the parameters in the output.

Please could you provide a screenshot of the expected output (i.e. the output you see in Jupyter).

**Comment by brew-guy** [comment]
Hi Don,
Thanks for looking into this. Here's an example of a printed class instance
where I immediately see the parameters...
I hope it helps. Otherwise feel free to get back to me.

[image: image.png]

**Comment by DonJayamanne** [comment]
@brew-guy Please could you re-upload the image, looks like it didn't get uploaded

**Comment by brew-guy** [comment]
Hi,
Try this...
  image.png
<https://drive.google.com/file/d/1VfsTVyMIlRTFDByYoiSm7UnU5o2dU7J8/view?usp=drivesdk>

**Comment by brew-guy** [comment]
Hi @DonJayamanne, no worries. I hope it works this time.
![image](https://user-images.githubusercontent.com/11842974/154840468-fb0ea15e-0d76-4e86-ad0c-e793f84c0424.png)

**Comment by DonJayamanne** [comment]
thanks.
please could you provide a screenshot of what it looks like in vscode,

**Comment by brew-guy** [comment]
Oh ofcourse! Here it is. VSCode does not output anything but the name of the instance:
![Screenshot 2022-02-20 135811](https://user-images.githubusercontent.com/11842974/154843792-6a21e6e6-d635-44a3-acf1-773b58f0b359.jpg)

**Comment by DonJayamanne** [comment]
Thanks, unfortunately this isn't something we control.
The output we get for `print(count_vector)` is returned by the Python kernel, and should be the same, it its not then its likely you're using a different kernel or there's something else different in your setup.

Here's a screenshot of the exact same code for me in Jupyter (which is inline with VS Code, i.e. its the same)
![image](https://user-images.githubusercontent.com/1948812/155020490-78caf348-062e-4482-b9f4-bf4b0d905596.png)

Closing this as the output is not controlled by the VS Code extension, but controlled by the Python kernel itself.
