### ISSUE TITLE
The Data Viewer can't sort the data correctly

### ISSUE THREAD

**Issue by Vincent0706** [microsoft/vscode-jupyter#8794]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

![image](https://user-images.githubusercontent.com/82581024/150960178-164ba67b-58b8-4b27-bb28-e34bd641a24a.png)

I sort the data in the Data Viewer, but it didn't sort with its real value.

### VS Code Version

版本: 1.63.2 (user setup) 提交: 899d46d82c4c95423fb7e10e68eba52050e30ba3 日期: 2021-12-15T09:40:02.816Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.19043

### Jupyter Extension Version

v2021.11.1001550889

**Comment by amunger** [comment]
closing as the jupyter data viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486
