### ISSUE TITLE
Kernel selector should be auto displayed after specifying local or remote Jupyter server for connections

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#8795]
Testing #8778

I found the flow to add a remote kernel somewhat unintuitive. The user has to do the following:
1. Execute the 'Specify local or remote Jupyter server for connections' command and paste in the server url. At this point they are still connected to the local kernel in the kernel selector
2. Go back into the kernel selector and pick which kernel from the remote connection they want to use

After step 1 I was surprised that no kernel was autoselected and my previous, local kernel connection remained the same, and I needed to go into a different UI entrypoint to select the kernel. I suppose we can't autoselect a kernel from the remote connection because there could be multiple kernels running on the remote server? If that's the case, could we nudge users to pick the kernel by immediately invoking `notebook.selectKernel` with no arguments to put up the kernel selector?

**Comment by DonJayamanne** [comment]
If i don't have a notebook open I cannot display kernel picker (what do we do with the selection), possible the user wants to use IW and not notebooks.
I don't think we can display a kernel picker at all as we do'nt know whether they want to change kernels for existing NB or not.
Its possible this extra prompt would be annoying to users.

* To discuss in standup, 
* perhaps leave this open to see if users report similar issues (confusion about not getting prompted or the like).
* The kernel picker UX that Miguel designed with remote servers would address this workflow (the kernel picker has the ability to define the servers & the like)

**Comment by greazer** [comment]
Consider moving to suggested kernel picker that Miguel had spec'd out some time ago. This will address this problem in a smoother way.

**Comment by DonJayamanne** [comment]
this will be fixed with the new kernel picker ui

**Comment by rzhao271** [comment]
After specifying to use the remote server, the kernel picker is not auto-displayed.
However, I do immediately see the remote option when opening the kernel picker afterwards. Is this enough for verification?
