### ISSUE TITLE
Number of active connections for remote Jupyter session is not accurate in interactive windows

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#8798]
Testing #8778

1. Open a notebook and connect it to a remote kernel
2. Open an interactive window and connect it to the same remote _session_
3. Open the kernel selector for the notebook. It says there are 2 active connections for that session
    ![image](https://user-images.githubusercontent.com/30305945/151016594-be69c3e0-e619-4a04-8cdd-93ed2086612f.png)
4. 🐛 Open the kernel selector for the interactive window. It says there is only 1 active connection for that session
    ![image](https://user-images.githubusercontent.com/30305945/151016741-7198f51d-161f-4755-8966-e5b1efc2bcb4.png)
5. 🐛 Make another interactive window and connect it to the same remote session. It still says there is only 1 active connection for that session

**Comment by DonJayamanne** [comment]
Should be fixed
