### ISSUE TITLE
No images render in Jupyter walkthrough

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#8799]
Testing #8793

I have the pre-release Jupyter extension, latest VS Code Insiders on Windows 11, and am seeing the following:

![image](https://user-images.githubusercontent.com/30305945/151020298-06e5cae4-f363-4309-b97e-901b19c3ae61.png)

![image](https://user-images.githubusercontent.com/30305945/151020107-b54f583e-2e24-42ad-87da-94e976924922.png)

**Comment by minsa110** [comment]
Fixed per #8823

**Comment by roblourens** [comment]
@minsa110  Remember to assign yourself to issues when you fix them, thanks

**Comment by roblourens** [comment]
These gifs are pretty small on my screen. If we have to redo them at some point it might be helpful to zoom in a little.
