### ISSUE TITLE
Breakpoint ignored when debugging a cell

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode-jupyter#8803]
Testing [#141223](https://github.com/microsoft/vscode/issues/141223), followed the steps in https://github.com/microsoft/vscode/issues/131469 to set up Jupyter debugging

Environment: macOS 11.6.2, Python 3.10.1, ipykernel==6.7.0
Jupyter extension version 2022.1.1001744497, VS Code 1.64.0-insider commit f93c696

Tried setting a breakpoint in a cell, and the cell would just get executed normally, the breakpoint was ignored.

The cell:

```py
d = "no"
print(f"What is the value of d? {d}")
d = "yes"
print(f"What is the value of d now? {d}")
```

Content of the `Jupyter` output channel after I click on the `Debug Cell` button:

```
Info 11:52:11: Executing (status idle) silently Code = import ipykernel\nprint(ipykernel.__version__)
Info 11:52:11: Executing silently Code (completed) = import ipykernel\nprint(ipykernel.__version__)
Info 11:52:12: Executing (status idle) silently Code = import debugpy\ndebugpy.debug_this_thread()
Info 11:52:12: Executing silently Code (completed) = import debugpy\ndebugpy.debug_this_thread()
Info 11:52:12: Execute Cells request 3
Info 11:52:12: Execute Cell 3 ~/Documents/Sandbox/notebooks/notebook.ipynb
Info 11:52:12: Cell 3 executed with state Success
Warn 11:52:12: StdErr from Kernel Process [IPKernelApp] ERROR | Exception in control handler:

Warn 11:52:12: StdErr from Kernel Process Traceback (most recent call last):

Warn 11:52:12: StdErr from Kernel Process   File "/Users/kimiguel/Documents/Sandbox/notebooks/.othervenv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 281, in process_control

Warn 11:52:12: StdErr from Kernel Process     else:

Warn 11:52:12: StdErr from Kernel Process   File "/Users/kimiguel/Documents/Sandbox/notebooks/.othervenv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 856, in debug_request

Warn 11:52:12: StdErr from Kernel Process     async def debug_request(self, stream, ident, parent):

Warn 11:52:12: StdErr from Kernel Process   File "/Users/kimiguel/Documents/Sandbox/notebooks/.othervenv/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 426, in do_debug_request

Warn 11:52:12: StdErr from Kernel Process     return await self.debugger.process_request(msg)

Warn 11:52:12: StdErr from Kernel Process   File "/Users/kimiguel/Documents/Sandbox/notebooks/.othervenv/lib/python3.10/site-packages/ipykernel/debugger.py", line 606, in process_request

Warn 11:52:12: StdErr from Kernel Process     elif self.is_started:

Warn 11:52:12: StdErr from Kernel Process   File "/Users/kimiguel/Documents/Sandbox/notebooks/.othervenv/lib/python3.10/site-packages/ipykernel/debugger.py", line 348, in stop

Warn 11:52:12: StdErr from Kernel Process     cleanup_transforms = get_ipython().input_transformer_manager.cleanup_transforms

Warn 11:52:12: StdErr from Kernel Process   File "/Users/kimiguel/Documents/Sandbox/notebooks/.othervenv/lib/python3.10/site-packages/ipykernel/debugger.py", line 232, in disconnect_tcp_socket

Warn 11:52:12: StdErr from Kernel Process     def disconnect_tcp_socket(self):

Warn 11:52:12: StdErr from Kernel Process   File "zmq/backend/cython/socket.pyx", line 640, in zmq.backend.cython.socket.Socket.disconnect

Warn 11:52:12: StdErr from Kernel Process zmq.error.ZMQError: No such file or directory
```

![image](https://user-images.githubusercontent.com/51720070/151049478-c03de147-c85b-450a-85ad-40e7cf395397.png)

**Comment by rchiodo** [comment]
I get this too with the latest IPython bits.

Works fine with older IPython.

**Comment by rchiodo** [comment]
Note run by line seems to work fine. It's only Debug Cell that fails.

**Comment by greazer** [comment]
I have an environment with IPython 8 and debugging (hitting bps) is working just fine.

**Comment by rchiodo** [comment]
For me, I had to start debugging twice. Second run and the breakpoints fail to work (ZMQ throws error)

**Comment by r3m0t** [comment]
I just tried ipykernel's main branch and it works fine.
Looks to be this- https://github.com/ipython/ipykernel/pull/855 as that's the only change since 6.8.0

**Comment by danieltomasz** [comment]
For me even after installing the latest ipykernel the result is the same  as before - the breakpoint isn't  even hit when  trying to debug cell

When I try "Run and debug" from left sidebar I am getting "NameError: name 'null' is not defined" but this might be other or problem with my configuration

**Comment by danieltomasz** [comment]
when switching to Python 3.9.10 breakpoints work

**Comment by danieltomasz** [comment]
this might be related https://youtrack.jetbrains.com/issue/PY-47999
`After manual Cython speedups compilation on macOS for Python 3.10 breakpoint are ignored`

**Comment by danieltomasz** [comment]
With the new `ipykernel 6.9.0` release, everything seems to work.

**Comment by anmolsjoshi** [comment]
Experiencing this as well

python 3.9.5
ipykernel == 6.4.1  
ipython == 7.29.0 
VScode Version: 1.64.1 Commit: d6ee99e4c
Jupyter Extension: v2022.1.1001821375

**Comment by Zoxjib** [comment]
Experiencing this as well, both in VSCode and also in Jupyter's web UI when attempting to debug .ipynb files. 
No issues when debugging .py files.

python 3.10.2
ipykernel == tested on 6.8.0 and 6.9.0
ipython == 8.0.1
VSCode version 1.64.1 Commit: d6ee99e4c
Jupyter Extension: v2022.1.1001821375

I've seen the exact error as reported by the OP, but I've also encountered the following error:

```
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\username\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\username\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\username\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "e:\Programming\Github\python\MIT 6.0001\Ses3.ipynb", line 16, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
```

**Comment by danieltomasz** [comment]
When creating new environment  using code below, debugging  works with `VERSION=3.9.10` but not with  `VERSION=3.10.2`.
I am on macOS 12.3, 
Visual Studio 1.64.2, 
Jupyter Extension v2022.2.100182281

 ```
pyenv install 3.10.2
pyenv install 3.9.10
make install VERSION=3.9.10
make install VERSION=3.10.2
```

Content of the makefile:

```makefile
.ONESHELL:

.PHONY: install

PROJECT=debug
VERSION?=3.10.2
VENV=${PROJECT}-${VERSION}
VENV_DIR=$(shell pyenv root)/versions/${VENV}
PYTHON=${VENV_DIR}/bin/python

install:
	@echo "Installing $(VENV)"
	pyenv virtualenv ${VERSION} ${VENV}
	pyenv local ${VENV}
	$(PYTHON) -m pip cache purge 
	$(PYTHON) -m pip  install -U pip
	$(PYTHON) -m pip install wheel
	$(PYTHON) -m pip install ipykernel
	$(PYTHON) -m ipykernel install --user --name ${VENV}
```

**Comment by rchiodo** [comment]
I think this is debugpy/pydevd's fault. At least it is sent the breakpoints but it doesn't fire them.

**Comment by rchiodo** [comment]
Logging an issue on debugpy:
https://github.com/microsoft/debugpy/issues/844

**Comment by fabioz** [comment]
Hi all, this was a change of behavior in Python 3.10 itself (see: https://mail.python.org/archives/list/python-dev@python.org/thread/VXW3TVHVYOMXDQIQBJNZ4BTLXFT4EPQZ/).

I provided a pull request to IPython: https://github.com/ipython/ipython/pull/13535 (still pending).

If anyone wants to try it and is comfortable patching the installed version, you can run in the notebook:

```
from IPython.core import interactiveshell
print(interactiveshell.__file__)
```

And then open the file printed and apply the patch from https://github.com/ipython/ipython/pull/13535 (don't forget to restart the notebook afterwards).

p.s.: Given that this issue is an interaction between Python 3.10/ipython/debugpy, I think we can close the issue on vscode-jupyter...

**Comment by rchiodo** [comment]
Thanks @fabioz

**Comment by greazer** [comment]
Closing per @fabioz's suggestion.

**Comment by fabioz** [comment]
As a note, it seems there's another use-case where this happens (with hypothesis: https://github.com/microsoft/debugpy/issues/837), so, I'll provide a bugfix in debugpy itself which will fix both.

**Comment by fabioz** [comment]
As a note, it seems there's another use-case where this happens (with hypothesis: https://github.com/microsoft/debugpy/issues/837), so, I'll provide a bugfix in debugpy itself which will fix both.

**Comment by roblourens** [comment]
Anything to verify here?

**Comment by rchiodo** [comment]
I think we have to wait for the fix in ipykernel, so probably no?

**Comment by fabioz** [comment]
I ended up doing a fix in the debugger itself too (see comments in the PR: https://github.com/microsoft/debugpy/pull/851).

So, this does need a new debugger release...

**Comment by johnfkraus** [comment]
Can't help but observe a seeming hair trigger for closing issues.
