### ISSUE TITLE
Failed to get remote kernel connections, reason: unable to verify the first certificate

### ISSUE THREAD

**Issue by dracodoc** [microsoft/vscode-jupyter#8811]
## Environment data

-   VS Code version: 1.63.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.1.1001744497
-   Python Extension version (available under the Extensions sidebar): v2022.0.1744153312-dev
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.19042
-   Python and/or Anaconda version: 3.7.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

`Allow Unauthorized Remote Connection` in Jupyter is enabled. Http: Proxy Strict SSL and Http: System Certificates can be enabled or disabled, both with same error.

The same setup used to work with earlier version of VS code (a version slightly higher than 1.55). I upgraded VS code and found the error. I tried to downgrade jupyter extension till 2021.6 but still same error. With 2021.4 and earlier the extension cannot be activated.

## Expected behaviour

Connect to remote jupyter server and select kernel from list

## Actual behaviour

Cannot select kernel and cannot run cell with remote jupyter server.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open a jupyter notebook, set remote jupyter server with token, run cell. There will be error notification

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>Error 20:20:07: Failed to get remote kernel connections [FetchError: request to https://abc.abc.com:8443/user/abc/api/kernels?123 failed, reason: unable to verify the first certificate
	at ClientRequest.<anonymous> (c:\Users\abc\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001744497\out\client\extension.js:16:357760)
	at ClientRequest.emit (events.js:327:22)
	at TLSSocket.socketErrorListener (_http_client.js:469:9)
	at TLSSocket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)]
Error 20:20:07: SessionManager cannot enumerate kernelspecs. Returning default {}.</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by cmosguy** [comment]
@dracodoc  where do you set this `use proxy support for extensions` in VS code?  I am having a similar issue when trying to connect vs code to a remote jupyterhub using the `token`

**Comment by dracodoc** [comment]
You can just search `proxy` in settings. I have it under `http: proxy support`. I'm using 1.64.1

**Comment by GenDemo** [comment]
Hi - I am having this same issue trying to connect to a JupyterLab server.
I have tried setting the , however I am still getting the same error: 
![VS Code error when connecting to Jupyter lab obf](https://user-images.githubusercontent.com/58798533/211673193-3e6c7399-5c82-4e04-9394-2257df4f4d6e.png)


@cmosguy where is the `remote` tab you are referring to?

**Comment by RGBYCP** [comment]
I have the same issue. I run


Version: 1.80.2 (Universal)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T21:05:41.366Z (4 days ago)
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0

and

Jupyter
v2023.7.1001901100

It also did not work with the released version. 

I switched off `use the proxy support for extensions`, I unhooked/hooked `controls whether the proxy sever certificate should be verified against the list of supplied CAs`. 
Nothing works. 
Does anybody have advice how to fix this, please? Many thanks.
