### ISSUE TITLE
Interactive window cell not executed after selecting a kernel with IPykernel in it

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8817]
Tested in latest pre-release version of Jupyter ext

* Open a Python file
* Create a cell with `print("Hello World")`
* Ensure active python interpreter doesn't have ipykernel installed
* Run a cell
* Ensure you get a prompt to install ipykernel
* Select a kernel that has ipykernel isntalled

Problems
* Cell is printed before the progress message for the startup of the kernel (ideally the kernel startup info should be before the cell is printed in IW)
* The cell is not executed at all

**Comment by rebornix** [comment]
@rchiodo what should I expect after switching to a kernel with ipykernel installed? Should it rerun the cell?

**Comment by rchiodo** [comment]
It should run the cell (it's never been run yet).

Basically:
1. Create empty venv ```python -m venv testEnv```
2. Create another empty venv ```python -m venv testEnvWithKernel```
3. Install ipykernel into the second venv ```testEnvWithKernel\scripts\activate && python -m pip install ipykernel```
4. Open VS code
5. Open/Create python file with a cell in it ```#%%\nprint(1)```
6. Select the testEnv with the python extension's 'Select interpreter' command
7. Click on the Run Cell code lens
8. IW should open and show the 'print(1)' with no output
9. Dialog should popup saying install kernel
10. Switch the kernel to the ```testEnvWithKernel``` 
11. Kernel should eventually connect and 1 would should be printed.
