### ISSUE TITLE
.ipynb does not open when resolving merge conflict

### ISSUE THREAD

**Issue by gro1m** [microsoft/vscode-jupyter#8826]
## Environment data

-   VS Code version: 1.63.2
-   Jupyter Extension version (available under the Extensions sidebar): 2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): 2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Enterprise
-   Python and/or Anaconda version: 3.8.12 / 4.10.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | N/A: No Jupyter server running

## Expected behaviour

Able to open _3_train.ipynb to resolve merge conflict

## Actual behaviour

Unable to open '_3_train.ipynb': Unexpected token < in JSON at position 5178.

## Steps to reproduce:

1. Create a Jupyter Notebook with a merge conflict and try to open it

## Logs

see Actual result section.

**Comment by gro1m** [comment]
Related: https://github.com/microsoft/vscode-jupyter/issues/1734
Unfortunately still appearing 😒

**Comment by IanMatthewHuff** [comment]
@gro1m There currently is a known issue in vscode core tracking this. I'm going to close this issue down, and you can track the following issue for the resolution here:

https://github.com/microsoft/vscode/issues/136133

**Comment by gro1m** [comment]
> @gro1m There currently is a known issue in vscode core tracking this. I'm going to close this issue down, and you can track the following issue for the resolution here:
> 
> [microsoft/vscode#136133](https://github.com/microsoft/vscode/issues/136133)

Thanks for the link, this was unfortunately not clear from reading through #1734, this is why I opened it up here.
