### ISSUE TITLE
Render and Drag plots as PDFs from IW

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-jupyter#8828]
Sometimes I need to quickly send people a plot over Slack I just created in the interactive window. A cool feature is that you can just drag and drop figures out of the IW. What you get is always a PNG. Is there a way to get a PDF instead without needing to think of a file name and call `plt.savefig("my_plot.pdf")`, then find the file in Finder? PDFs are usually smaller in file size and vector graphics too, so can be scaled zoomed and searched for text.

**Comment by IanMatthewHuff** [comment]
Thats an interesting suggestion. I do know that for optional plotviewer support we currently have an option to generate SVGs alongside PNGs for plot output. The figure_format does allow for a pdf option so there may be something we can do there.

**Comment by DonJayamanne** [comment]
I would generate a PDF file on demand, I think thats simpler and better than always generating PDFs using the built in capabalities of matplotlib, else we run into issues with bloating notebooks.

I think we already ship & we could use that [pdfkit](https://www.npmjs.com/package/pdfkit)

**Comment by DonJayamanne** [comment]
> just drag and drop figures out of the IW. What you get is always a PNG

Optionally users could configure the default file export formats via the startup commands, to be pdf if matplot lib supports this

**Comment by janosh** [comment]
@DonJayamanne Interesting suggestion. [There is](https://matplotlib.org/2.1.0/api/_as_gen/matplotlib.pyplot.savefig.html)

```py
import matplotlib


matplotlib.rcParams["savefig.format"] = "pdf"
```

but since we never call `plt.savefig()` to get a plot in IW, it wouldn't have any effect. Couldn't find another `rcParam` that might have bearing here.

I remember the IW switched from rendering SVGs to PNGs for performance reasons at some point so I assumed the file type is determined internally and perhaps not even user overridable?

**Comment by IanMatthewHuff** [comment]
@janosh This is actually what I was thinking of (it's how we changed from SVG to PNG):
https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.set_matplotlib_formats

**Comment by DonJayamanne** [comment]
Can you not have both `%config inlinebackend...formats = ['svg', 'pdf']` ?

**Comment by janosh** [comment]
@DonJayamanne Yes, but then the file I get from dragging is PNG.

**Comment by IanMatthewHuff** [comment]
I need to try it myself, I think that would generate both, but the drag and drop wouldn't get the pdf it would get the rendered png.

**Comment by DonJayamanne** [comment]
Adding support for drag and drop will need to be done in VS Code core.
Also that would require quite a lot of changes (changing the native drag drop, to allow dragging png and drop the pdf).

Unless we always rendered PDF and had a PDF renderer for outputs.

**Comment by janosh** [comment]
Rendering PDFs would be cool in certain cases if there are no general performance concerns. Though there are certain plots that are huge as PDFs like scatter plots with 1000s of points where it would definitely become a problem.

**Comment by DonJayamanne** [comment]
Thank you for this feature request, however given the fact that this hasn't received any upvotes nor addtional comments, I'm closing this issue.
