### ISSUE TITLE
Putting a magic in the middle of a cell messes up intellisense

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8830]
Create some cells with at least one like so:

```python
import numpy as np
%matplotlib inline
import ipywidgets as widgets
import matplotlib.pyplot as plt
```

Close and open a notebook

Edit the 'inline' to be 'widget' or vice versa

Notebook colorization will be screwed up

![image](https://user-images.githubusercontent.com/19672699/151417282-78e68cd1-aa0d-4e09-8fea-4f4d23ea4ba0.png)

**Comment by IanMatthewHuff** [comment]
@rchiodo Just happened to run into this today:
![image](https://user-images.githubusercontent.com/812783/151423874-f26f60bc-1f8a-46d9-a5c4-7e23f77268ac.png)
Related? I can open a few issue for this as well. 

numpy has never been input into this window, it's part of a .py file that I ran the initial cell from. The magic was input from the input box.

**Comment by rchiodo** [comment]
Probably the same root cause. If you have an even simpler repro that'd be great.

**Comment by IanMatthewHuff** [comment]
Yeah so I had the manual .py test file that I added one small variable assignment to at the top cell (for testing another issue)
![image](https://user-images.githubusercontent.com/812783/151424647-e335e619-bb57-4c09-bda3-e7cb048bbdf9.png)
Steps were just:
1. Run the first cell via the code lens
2. Input `%connect_info` in the IW input box

I'm on daily python and pylance if that matters.

**Comment by IanMatthewHuff** [comment]
@rchiodo Bleh, ignore my previous comments (I deleted them) didn't have the right extension version. My scenario looks ok now.

**Comment by rchiodo** [comment]
Damn it wasn't supposed to close yet. I need to integrate this into the middleware and then into the jupyter extension and pylance.
