### ISSUE TITLE
Change problem to indicate qt5 is supported (or one of the recommended options)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8831]
Now that we have fixed support for `%matplotlib qt5` here https://github.com/microsoft/vscode-jupyter/issues/8322
I feel the warning about `%matplotlib` working best with `inline` or `widget` is misleading if not wrong.

E.g. users who have this working for `%matplotlib qt5` would not get a problem unnecessarily & could prove annoying.

![image](https://user-images.githubusercontent.com/1948812/151435882-f0d76799-0a67-40e3-a871-0b814613dc7c.png)

**Comment by rchiodo** [comment]
Yeah we should fix it, but we could update the wiki to say QT5 is supported. The more information link jumps to the wiki

**Comment by rchiodo** [comment]
Although the wiki is pretty ambiguous about it. It's like try it at your own risk. I think that's fine:

![image](https://user-images.githubusercontent.com/19672699/151436522-1d4f3f39-44f2-4e0f-841a-7a2311eed20d.png)

**Comment by DonJayamanne** [comment]
There haven't been any further issues nor upvotes related to this, hence clolsing this issue
