### ISSUE TITLE
VegasFusion doesn't work 

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8834]
This prevents the python package the user has in the kernel from actually working correctly. 

Recent example:
https://medium.com/@jonmmease/announcing-vegafusion-570f62207ba7

This doesn't work in our notebooks (likely because we ship our own version of vegas).

The python installed js file should work and if it needs something specific to jupyter, we could always polyfill it.

**Comment by DonJayamanne** [comment]
Looks like a different issue. 
I can see that the right files including the WASM files are all loaded from unpng (see below)

![image](https://user-images.githubusercontent.com/1948812/151742638-a1d84be9-5a1d-4262-ad3d-d8132237b0c0.png)

Other similar issues (loading scripts form `nbextensions` folder and this folder changes for jupyter lab):
* https://github.com/microsoft/vscode-jupyter/issues/6054
* https://github.com/microsoft/vscode-jupyter/issues/8241#issuecomment-966620799
* https://github.com/microsoft/vscode-jupyter/issues/1477#issuecomment-850724283

**Comment by DonJayamanne** [comment]
Fixed

**Comment by rchiodo** [comment]
Okay I think I attempted something that might be what this was trying to fix. It didn't work.

Here's the notebook I ran:

```
# %%
%pip install "vegafusion-jupyter[embed]" vega-datasets

# %%
import vegafusion as vf
vf.jupyter.enable()

# %%
import altair as alt
import pandas as pd

# %%
df = pd.read_json('./ipyvega/notebooks/cars.json')

alt.Chart(df).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
)
```
(works fine without the vf.jupyte.enable() cell because it just uses altair)

I get nothing in the output.

I have this in the developer tools (which sounds like the original error):

![image](https://user-images.githubusercontent.com/19672699/176976960-6b3087e8-44e7-4b32-8f6a-44eded531b36.png)

**Comment by DonJayamanne** [comment]
**Notes:**

This does not work with the latest version of vega-fusion 0.6.0, please test with and older version such as 0.4.0
Caused by an upstream issue https://github.com/vegafusion/vegafusion/issues/134 (i.e. latest version doesn't have the right files uploaded to the CDN).

Alternative, disable CDN and this will work
