### ISSUE TITLE
Duplicate suggestion on typing a keyword

### ISSUE THREAD

**Issue by soumesh2002** [microsoft/vscode-jupyter#8835]
## Environment data

-   VS Code version: Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
-   Jupyter Extension version (available under the Extensions sidebar): 2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: Python 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): None
-   Jupyter server running: Local

## Expected behaviour
Suggestion should be unique
XXX

## Actual behaviour
Duplicate Suggestion being produced while typing a keyword such as error: there will be several suggestion for 'error' word rather than relevant suggestion such as KeyError
XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>
```
XXX
```
<img width="502" alt="image" src="https://user-images.githubusercontent.com/53593544/151599098-c6cce2c2-d2b5-425c-85ac-975972f1c75d.png">

</p>
</details>

**Comment by amunger** [comment]
Can you provide some sample code that shows this behavior? A screenshot would also be helpful to see what's happening.
