### ISSUE TITLE
Intellisense breaks after changing cell language

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8836]
1. Create a notebook with multiple cells
2. With one of the cells in the middle, change it to be an HTML cell

Results:

![image](https://user-images.githubusercontent.com/19672699/151608155-99e04ffd-610e-449b-970c-ed56de8f167b.png)

**Comment by rchiodo** [comment]
Looking at the pylance logs, the cell change is not passed to pylance so it doesn't remove it from the concat document. It should have caused a close event.

**Comment by rchiodo** [comment]
Likely we need to wire up this specific for a notebook. Dirk's changes should fix/include this scenario so might just adopt those instead of doing more custom work.

**Comment by DonJayamanne** [comment]
Closing this issue as no one else has reported this until now/
