### ISSUE TITLE
Picking a non ipykernel kernel in the interactive window does not allow cancel

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8837]
1. Create venv
2. Dont set it as your interpreter
3. Launch IW
4. Pick the venv
5. THis dialog should appear:

![image](https://user-images.githubusercontent.com/19672699/151609325-fc295e64-74e0-45fb-9ff1-4224e5c361f7.png)

6. Say cancel

IW is no longer usable and still shows the venv kernel

**Comment by greazer** [comment]
This looks by design. If you try running the cell, you'll be reprompted to install ipykernel.

**Comment by rchiodo** [comment]
I would say cancel should force me to pick a new kernel then. It's not usable after hitting cancel:

![image](https://user-images.githubusercontent.com/19672699/152017296-3bd89946-15bd-495f-a3be-14a51d56614d.png)

**Comment by rchiodo** [comment]
This is actually being worked on for next month. Closing as dupe of #8817
