### ISSUE TITLE
 Execute cell and get completions that require jupyter test is failing

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8842]
Pylance changed their completion behavior/parsing.

Failure looks like so:
![image](https://user-images.githubusercontent.com/19672699/151622917-cc7e12f1-c861-4dc4-8a09-2f589badfdac.png)

This is caused by pylance not returning DataFrame completions. See upstream issue here:
https://github.com/microsoft/pylance-release/issues/2302

**Comment by DonJayamanne** [comment]
No such test anymore
