### ISSUE TITLE
User input prompts are not visible when running .ipynb in VS Code. 

### ISSUE THREAD

**Issue by effeappbw** [microsoft/vscode-jupyter#8846]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

There are at least two closed issues re: this topic (https://github.com/microsoft/vscode-jupyter/issues/2380), which suggest a solution of passing a string, but that solution doesn't work.

Inputs are possible--just not visible.

### VS Code Version

1.63.2

### Jupyter Extension Version

2022.1.1001760686

### Jupyter logs

```shell
Info 13:39:00: Execute Cells request 1
Info 13:39:00: Execute Cell 1 ~/ACP_exercises/M_exercises.ipynb
Info 13:39:02: Cell 1 executed with state Success
```

### Language Extension Version (if applicable)

Python 3.10.1

### Anaconda Version (if applicable)

NA

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
I'm not able to repro this, the input prompt pops up for both stable and insiders:
![image](https://user-images.githubusercontent.com/2019016/151847924-f37c0cb7-aef8-46f4-8bc4-4de116ec1dc8.png)

Can you provide a code snippet that causes the issue?
What OS are you on?

**Comment by greazer** [comment]
@effeappbw, can you verify that perhaps you're just not seeing the prompt at the top of the VS Code window? We are suspecting this may be a common oversight that we may try to address.

**Comment by effeappbw** [comment]
Hi--thanks for the quick response & feedback. 
I'm running macOS 12.1.

Arg. My bad--I was completely missing the command palette prompts for some reason. Total oversight on my end. I was fixating on the terminal where one might typically expect to see user input/prompts.

FWIW, the command palette gives me fits. I can't figure out how to pin the damn thing in place. 

Thanks again, gents. Apologies.
