### ISSUE TITLE
Want a full size image for a plot which got expanded in new tab by clicking expand image button

### ISSUE THREAD

**Issue by vikassnwl** [microsoft/vscode-jupyter#8872]
![feature_req](https://user-images.githubusercontent.com/54145523/151704483-298b1abb-f61c-4dc9-bf7c-1326a6189f1f.png)
I want a button to collapse the highlighted area in the attached image, so that the image can occupy the full space.

**Comment by greazer** [comment]
Thanks for the feedback! We'll consider for a future release.

**Comment by dynamicwebpaige** [comment]
+1 - this would be a great add, and potentially could be included first in @DonJayamanne's [Render extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter-renderers).

**Comment by mastevb** [comment]
Can I work on this?

**Comment by DonJayamanne** [comment]
Thanks for the suggestion, however given the fact that this has not received enough upvotes nor any additional interest for the past year, I'm closing this issue.
