### ISSUE TITLE
Remote Jupyter Server Ignoring jupyter.notebookFileRoot VS Code Setting

### ISSUE THREAD

**Issue by okwilkins** [microsoft/vscode-jupyter#8885]
## Environment data

-   VS Code version: 1.63.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): v2022.1.5
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 18.04.6 LTS
-   Python and/or Anaconda version: conda 4.11.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | Remove

## Expected behaviour

Using Azure ML, I create to a new compute instance. I then connect to the compute instance via VS Code.
I set `jupyter.notebookFileRoot` = `${fileDirname}` in all contexts: User, Remote and Workspace.
I expect that when I run `!pwd` in a cell in a Jupyter notebook for it to return the current directory that the notebook is running in.

> /mnt/batch/tasks/shared/LS_root/mounts/clusters/my-compute/code/Users/OWilkins/azure-ml-project/notebooks/

## Actual behaviour

Running `!pwd` instead prints this directory:

> /mnt/batch/tasks/shared/LS_root/mounts/clusters/my-compute/code

## Steps to reproduce:

1. Using Azure ML, create a new compute instance.
2. Connect to the compute instance via VS Code.
3. Inside the Settings UI set the `jupyter.notebookFileRoot` setting to `${fileDirname}` for User, Remote and Workspace.
3. Create a directory inside your user folder called: `azure-ml-project`. Your file structure will most likely look something like this:

```
code
  Users
    your-username
      azure-ml-project
```

4. Create a notebook inside `azure-ml-project`.
5. Inside that notebook, run: `!pwd`.

I understand that this may be something specific to Azure ML and may be outside the remit of this repository but I am at a loss! Any help would be greatly appreciated!

**Comment by DonJayamanne** [comment]
We setup the working directory only if the Jupyter URI is localhost or if we start a local kernel.
Based on what I know with AML its a jupyter server on the remote machine and we're connecting to it via the AML proxy server.

We might have to put in some special casing code just for the AML scenario as we cannot rely on localhost or the like to determine whether its a locally running Jupyter Uri or not.

**Suggestion:**
* If is AML
* If running remote VS Code
* Then set CWD

**Comment by DonJayamanne** [comment]
> I expect that when I run !pwd in a cell in a Jupyter notebook for it to return the current directory that the notebook is running in.

@okwilkins
Currently this works as expected without `jupyter.notebookFileRoot = ${fileDirname}`. 
i.e. please remove the setting and it should work.
If not, please:
* Provide the output from the `Jupyter` output panel
* Please provide the output for the cell `!pwd`

**Comment by okwilkins** [comment]
Thanks for coming back to me!

> Currently this works as expected without jupyter.notebookFileRoot = ${fileDirname}.

Forgive my ignorance if I am missing something here, but isn't ${fileDirname} the default value for jupyter.notebookFileRoot?
It's also my understanding that `${fileDirname}` should return the directory that the notebook resides in.
This is what I am wanting to happen.
![image](https://user-images.githubusercontent.com/5969778/152514882-ff00c234-e3db-4759-918b-4166a6fcf0dd.png)

> i.e. please remove the setting and it should work.

Removing the setting does not change the behaviour, unfortunately!

---

I investigated this a bit further and the problem only occurs when I connect to Jupyter via: _Azure ML compute instance_.
It works fine when connecting to _localhost_ (the first option).

![image](https://user-images.githubusercontent.com/5969778/152514802-b79e48d8-972b-4519-81b8-0221c5fcceac.png)

_Note_: When it says start a server on localhost, this is all happening on the compute:

![image](https://user-images.githubusercontent.com/5969778/152517080-4f679f1a-3525-42ee-b209-d117c17c3099.png)

This is what this cell outputs when I connect via _Azure ML compute instance_:

![image](https://user-images.githubusercontent.com/5969778/152518528-8ef2f32c-f622-4dab-a990-9e0a6c83a133.png)

**Comment by SiddhanthUnnithan** [comment]
Thanks for bringing this to our attention @okwilkins -- I can elaborate on the problem a bit.

I'm assuming you're connecting to the compute instance from the Azure ML Studio? The bottom-left of the screenshots you sent show "Azure ML: owilkins-low-cost" as the resource indicator meaning that you're connected to your compute instance through a remote VS Code window.

Within this window, all components (terminal, Jupyter server, debugger, extensions) are in the "remote" context. This means that when you connect to the "Default" Jupyter server, you're connecting to a Jupyter server running on the compute instance. The Jupyter extension behaves as expected and understands the Notebook as it is on the compute -- this is why when you _!pwd_ you're seeing the right path (cloudfiles/code/Users/<username>/azure-ml-project/notebooks).

The "Azure ML Compute Instance" option in the Jupyter server selector was meant to allow users to connect to their compute instances from their **local** Notebooks. Only the notebook, not the VS Code window, is connected to the remote compute. When the Jupyter extension creates the remote connection, they create a temporary Notebook at the root of the Jupyter server (cloudfiles/code/). This placeholder Notebook is then used to relay the commands of the local Notebook however all execution context is per the placeholder notebook. This is why when you run _!pwd_ after choosing the "Azure ML Compute Instance" option you're seeing the path as cloudfiles/code/ where cloudfiles == /mnt/batch/tasks/shared/LS_root/mounts/clusters/<my-compute>.

I think what is confusing in this experience is that once you're connected to the remote compute (through the full window), we still surface "Azure ML Compute Instance" as an option. This doesn't make sense as you're already connected to the compute, so the default localhost option is connecting you to the right server. I think the right approach here is for us to hide the "Azure ML Compute Instance" option when you're in the remote window. Keeping the option in the local window makes sense, as users that wish to only connect their local Notebooks to a remote compute can still do so in a streamlined way.

**Comment by SiddhanthUnnithan** [comment]
@sevillal @shsuman @tbombach I think it makes sense to move this issue to the Azure ML extension repository. We should also consider removing the "Azure ML Compute Instance" option from the list of Jupyter servers when the user is already connected to their remote instance. We contribute that option, so it makes sense for our extension to check the window context and hide the "Azure ML Compute Instance" option.

**Comment by okwilkins** [comment]
Thank you very much for the explanation @SiddhanthUnnithan! This perfectly explains the confusion I was having! I can now relay this information to my team, as we all found this confusing within the context of AML computes.

**Comment by SiddhanthUnnithan** [comment]
Happy to help! Really sorry about the confusion here. We'll evaluate getting rid of that option :)

**Comment by shsuman** [comment]
I think transferring this issue to our repository makes sense. Although, I think we should close this issue and open a new issue regarding removing the Compute instance option in the remote window. As far as I understand, everything explained in this issue is our current expected behavior and their is no underlying bug.

**Comment by roblourens** [comment]
Is there anything to verify here?

**Comment by rchiodo** [comment]
No the issue was essentially transferred.
