### ISSUE TITLE
misaligned intellisense for async functions across cells with syntax error

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#8886]
Issue Type: <b>Bug</b>

1. create a new .ipynb file
2. first cell:
```
async def hello(name="World"):
    return f'Hello {name}!'
```
second cell: 
```
await hello('Bob')
```
3. Add a usage of an undefined variable in the second cell:
```
print(greeting)
```

Extension version: 2022.1.1001760686
VS Code version: Code - Insiders 1.64.0-insider (a853936292178200eb58c2a9904d7a7dcf98cce8, 2022-01-30T20:09:01.122Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (11.98GB free)|
|Process Argv|--folder-uri file:///c%3A/src/test --crash-reporter-id 1202dc88-403d-4ebc-8393-af3551a8bd5b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstartedc:30421358
vscop804:30404766
vs360cf:30404996
vsclayoutctrc:30405799
azactmsalcf:30409288
pythonvspyt640:30426300
vscscmwlcmt:30428973

```

</details>

**Comment by amunger** [comment]
![image](https://user-images.githubusercontent.com/2019016/151837882-19ecd25e-0f86-4c46-b691-11269c08a8ba.png)

**Comment by rchiodo** [comment]
Not sure how this is nb-golden. ```await``` on a function is not a common thing to do.

The await is the root cause of the problem. Concat document is out of sync.

**Comment by greazer** [comment]
Pylance is working on changes that will fix this (or allow us to fix) this problem.

**Comment by IanMatthewHuff** [comment]
Looks good now to me with current pylance + jupyter bits.
