### ISSUE TITLE
Can't get out of remote kernel state

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#8887]
I am in a bad state, and I think these are the steps I took

- Connect notebook to Jupyter Remote kernel
- Close the notebook
- Kill the remote server
- At some point, I clicked the "Jupyter Server: Remote" button and clicked the trash can on the remote connection to disconnect
- Reopen the notebook

I get this error message

![image](https://user-images.githubusercontent.com/323878/151861571-19f453db-2cbe-4a14-9572-dbed7b462303.png)

The status bar says I'm connected to a remote
![image](https://user-images.githubusercontent.com/323878/151861706-769f0673-3f73-422a-b94f-3c5be8060055.png)

but when I click it, there is no remote connection
![image](https://user-images.githubusercontent.com/323878/151861663-6bf3f7ac-6f3f-4950-978b-1e990f84fac5.png)

Even if I reload the window and close/reopen the notebook again, I am stuck in this state

**Comment by roblourens** [comment]
Oh sorry, I am supposed to click "Default" I guess. Shouldn't it do that automatically when there is no remote server?

**Comment by DonJayamanne** [comment]
> Shouldn't it do that automatically when there is no remote server?

Yes, I'll check that.

**Comment by DonJayamanne** [comment]
Looks like an existing issue, I'm running into this as well.

**Comment by roblourens** [comment]
It seems to not fit my mental model that the statusbar item still says "Jupyter Server: Remote" when it doesn't feel like I am currently connected to any remote. But I don't see any errors and don't get stuck.

**Comment by DonJayamanne** [comment]
agreed, let's fix that, let's discuss today in standup
