### ISSUE TITLE
no autocomplete suggestions for dataframe columns

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#8888]
## Environment data

-   VS Code version: 1.63.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: 3.9.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behavior

Column names to be suggested when typing . after a dataframe when assigning to a variable

## Actual behavior

Suggestions for column names are no longer popping up when assigning to a variable 

![image](https://user-images.githubusercontent.com/19276747/151648281-46e62c97-1e6d-44c3-9673-7352d4fcfb51.png)

![image](https://user-images.githubusercontent.com/19276747/151867308-aa140236-fc33-4475-87d4-77d047c63202.png)

**Comment by DonJayamanne** [comment]
Works for me, please could you provide the sample code used to replicate this issue.

**Comment by DonJayamanne** [comment]
Got a confirmation of the issue:
* Getting completions when using `dfc.`
* But when you have assignments like `test = dfc.`

**Comment by greazer** [comment]
I see. Yeah we need to fix this. Is this a regression to?

**Comment by rchiodo** [comment]
Probably a bug in the filtering code for jupyter completions. It would be a regression.
