### ISSUE TITLE
Ability to Access Jupyter Server

### ISSUE THREAD

**Issue by rmorshea** [microsoft/vscode-jupyter#8889]
There are some widgets that require [Jupyter Server Extensions](https://jupyter-server.readthedocs.io/en/latest/developers/extensions.html). The client then needs to know the base URL where the Jupyter server can be found so that it can reach any assets which may have been added to the server via an extension. In normal notebooks, the base URL of the server can be discovered in a couple different ways which are described by the following function:

```javascript
const jupyterServerBaseUrl = (() => {
  const jupyterConfig = document.getElementById("jupyter-config-data");
  if (jupyterConfig) {
    return JSON.parse(jupyterConfig.text)["baseUrl"];
  }
  return document.getElementsByTagName("body")[0].getAttribute("data-base-url");
})();
```

Is there a similar way to discover the Jupyter server's base URL in VSCode?

**Comment by rmorshea** [comment]
This may be related to https://github.com/microsoft/vscode-jupyter/issues/1695, but it's a bit unclear.

**Comment by DonJayamanne** [comment]
@rmorshea We can add support for this (providing the Url).
However this would only work when connecting to remote jupyter servers, hence I don't see much point in adding support fort this.

I.e. if you start a kernel locally, then this will not work. I.e. jupyter server extensions will not work as we don't start a Jupyter server (on very rare cases we do, however thats an exception).

We dont support Jupyter server extensions, as we don't start Jupyter when connecting to kernels.
If the widgets require some communications to the backend, then IPyWidgets supports this functionality (via kernel comms).

**Comment by rmorshea** [comment]
The widget in question already uses comms where relevant. It additionally needs to know the URL of the Jupyter Server being used (if any) so, if the vscode-jupyter extension is configured to connect to a remote Jupyter Server, it would be useful for the widget to know what that URL is so it can load any static resources it requires (i.e. JS/CSS).

**Comment by rmorshea** [comment]
Also, given the aforementioned limitation, is there a recommended way to automatically start up a Jupyter Server locally in the background and connect to it via the remote protocol instead of using the local kernel implemented by vscode-jupyter? This, in combination with the presence of a `jupyter-config-data` element indicated the server baseURL (if the remote protocol is being used), would resolve my issue.

**Comment by DonJayamanne** [comment]
> , is there a recommended way to automatically start up a Jupyter Server locally in the background and connect to it via the remote protocol instead 

Right now there isn't one.
The user would have to start jupyter and connect to it as though it were a remote jupyter server.

> This would allow us to set up .vscode/settings.json with the relevant options for our users and display a helpful error message i

Out of curiosity, please could you be specicfic about what yo u mean by `our users`. Is this for a organization setup or class room or the like?
This would help us better understand the needs (based on how its used & where).

thanks

**Comment by rmorshea** [comment]
> I'm sorry, but right now there isn't one.

Are there any plans to implement this?

> Is this for an organization setup or class room or the like?

This is for an organization setup. I'm a software developer working at [AWS CQC](https://aws.amazon.com/blogs/quantum-computing/announcing-the-opening-of-the-aws-center-for-quantum-computing/) to support a team of researchers. We don't have an internal JupyterHub yet so researchers would need to repeatedly and manually stand up a local Jupyter Server to use the widget in question.

**Comment by DonJayamanne** [comment]
> Are there any plans to implement this?

unfortunately not at this stage.

**Comment by rmorshea** [comment]
Is there any way for the kernel or the widget to know if it is running VSCode? If so, I could stand up a simple static file server and rely on that to serve the resources.

**Comment by rchiodo** [comment]
> Is there any way for code running in the kernel or the widget to know if it is running inside VSCode? If so, I could use that knowledge to stand up a simple static file server instead of relying on the Jupyter server extension.

Do you mean in the python code? Yes there is a way. There's an environment variable (```VSCODE_PID```) you can check (the kernel should have this set if we start the kernel - non remote case).

**Comment by rmorshea** [comment]
That might be sufficient. Closing for now. Will re-open if that doesn't work.

**Comment by rmorshea** [comment]
I managed to get things working. The [way I'm doing it](https://github.com/idom-team/idom-jupyter/blob/9b43e63085b32a0f2d33d048fad2bc88e94184d2/idom_jupyter/import_resources.py#L18) feels quite hacky, but basically I use `notebook.notebookapp.list_running_server` to see if there are any running notebook servers. If there are, I ping the route where I expect my resources to be. If the ping fails, then I know I need to stand up my own static file server and use that instead.
