### ISSUE TITLE
Unable to start OCAML kernel in WSL, Mac, Linux

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8897]
## Environment data

-   VS Code version: 1.64
-   Jupyter Extension version (available under the Extensions sidebar): Latest
-   Python Extension version (available under the Extensions sidebar): Latest
-   OS (Windows | Mac | Linux distro) and version: WSL (Ubuntu)
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Venv
-   Jupyter server running: Local

## Expected behaviour

Able to run ocaml kernel

## Actual behaviour

Does not run

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Install ocaml as per instructions here https://akabe.github.io/ocaml-jupyter/
2. Run Jupyter in terminal and ocaml will work
3. Run OCAML kernel in VS Code and it will not work.

**Comment by DonJayamanne** [comment]
It doesn't seem to work as `opam` hasn't been initialized. When launched from the shell we have shell initialization scripts, hence opam is initialized. However in VS Code inside WSL there's no such thing, hence env variables are not as expected.

**Comment by DonJayamanne** [comment]
# TODO
* Does this work on Windows?
* Does this work on linux/mac desktop?

**Comment by IanMatthewHuff** [comment]
Reporting back on Mac.

Also doesn't work here, and I see the same basic symptom (I believe) as Don regarding shell initialization. Same kernel worked ok for me launching from shell with `jupyter notebook`.

```
Info 11:34:05: Process Execution: > /bin/sh -c "eval $(opam env --switch=default --shell=sh) && /Users/ianhuff/.opam/default/bin/ocaml-jupyter-kernel "$@"" ocaml-jupyter-kernel -init ~/.ocamlinit --merlin ~/.opam/default/bin/ocamlmerlin --verbosity app --connection-file /var/folders/q7/cn8fg6s94fgdcl0h7rbxldf00000gn/T/tmp-9387031XBpCbVv4Yg.json
> /bin/sh -c "eval $(opam env --switch=default --shell=sh) && /Users/ianhuff/.opam/default/bin/ocaml-jupyter-kernel "$@"" ocaml-jupyter-kernel -init ~/.ocamlinit --merlin ~/.opam/default/bin/ocamlmerlin --verbosity app --connection-file /var/folders/q7/cn8fg6s94fgdcl0h7rbxldf00000gn/T/tmp-9387031XBpCbVv4Yg.json
Info 11:34:05: Process Execution: cwd: ~/Documents/DataScience/Languages/OCAML
cwd: ~/Documents/DataScience/Languages/OCAML
Verbose 11:34:05: Launching kernel in kernelProcess.ts, Class name = x, completed in 3ms, has a truthy return value, Arg 1: "~/Documents/DataScience/Languages/OCAML", Arg 2: ""
Verbose 11:34:05: KernelProcess error: ocaml-jupyter-kernel: eval OPAM_SWITCH_PREFIX='/Users/ianhuff/.opam/default'; export OPAM_SWITCH_PREFIX;
CAML_LD_LIBRARY_PATH='/Users/ianhuff/.opam/default/lib/stublibs:/Users/ianhuff/.opam/default/lib/ocaml/stublibs:/Users/ianhuff/.opam/default/lib/ocaml'; export CAML_LD_LIBRARY_PATH;
OCAML_TOPLEVEL_PATH='/Users/ianhuff/.opam/default/lib/toplevel'; export OCAML_TOPLEVEL_PATH;
PKG_CONFIG_PATH='/Users/ianhuff/.opam/default/lib/pkgconfig'; export PKG_CONFIG_PATH;
PATH='/Users/ianhuff/.opam/default/bin:/Users/ianhuff/Documents/DataScience/Languages/OCAML/.venv/bin:/Users/ianhuff/.nvm/versions/node/v14.17.1/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/texlive/2020:/Users/ianhuff/opt/miniconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:~/.dotnet/tools'; export PATH; && /Users/ianhuff/.opam/default/bin/ocaml-jupyter-kernel -init: No such file or directory
```

**Comment by TimMcGilly** [comment]
I can also reproduce this on windows

**Comment by DonJayamanne** [comment]
@TimMcGilly out of curiosity, how do you install the ocaml kernel on windows. also does it work in classic jupyter notebook or jupyter lab?

**Comment by TimMcGilly** [comment]
@DonJayamanne I've got Ocaml installed in Ubuntu WSL. Then installed juypter ocaml following this https://akabe.github.io/ocaml-jupyter/

`jupyter notebook --no-browser` works well. I can copy link and have no errors.

However when I run `code .` and then try to create a juypter in vscode and run get "Failed to start kernel" error 
![image](https://user-images.githubusercontent.com/11339148/170491512-97c80527-93ee-4b28-91b1-3597f2b65748.png)

**Comment by DonJayamanne** [comment]
@TimMcGilly thanks for the confirmation, basically its installed in WSL, not windows. Thanks, 
I believe I have a fix for this, once I have something ready for testing, i'll ping you.

**Comment by IanMatthewHuff** [comment]
LGTM on Mac
<img width="852" alt="image" src="https://user-images.githubusercontent.com/812783/175129805-8fa4ea96-1a8d-4f87-852d-7de281e5bf72.png">
