### ISSUE TITLE
Flakey test `Update variables during stepping:1 | Cannot read property 'arguments' of undefined`

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8905]
Update variables during stepping:1 | Cannot read property 'arguments' of undefined
https://github.com/microsoft/vscode-jupyter/runs/5027692681?check_suite_focus=true

**Comment by rchiodo** [comment]
That's likely this code here:

```
  // Try debugging the cell
        assert.ok(codeLenses, `No code lenses found`);
        assert.equal(codeLenses.length, 3, `Wrong number of code lenses found`);
        let args = codeLenses[2].command!.arguments || []; <-- Right here
        void vscode.commands.executeCommand(codeLenses[2].command!.command, ...args);
```

I wonder if code lenses might require waiting.

**Comment by rchiodo** [comment]
They seem to be there though
![image](https://user-images.githubusercontent.com/19672699/152067314-e896bfa6-1b17-4232-a2dd-ad7c83cbeba9.png)
