### ISSUE TITLE
Pylance can be slow in returning intellisense

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8906]
I'm seeing this on a project with a single Notebook. @rchiodo mentioned opening an issue here and this one looks relevant.

**Environment**
OS: Windows 11 22000.466
VS Code: 1.64.0-Insiders
Jupyter: v2022.1.1001755318
Pylance: 0.18.1

**Logs**
https://gist.github.com/burkeholland/6f7deb0730456cc239db58c1eac8a59f

**Video**
https://user-images.githubusercontent.com/686963/151440515-cb083cb5-b08e-48ba-83b9-c4c1d523c206.mp4

**Project to reproduce**
https://github.com/claudiaregio/data-science

_Originally posted by @burkeholland in https://github.com/microsoft/pylance-release/issues/1338#issuecomment-1023623014_

**Comment by rchiodo** [comment]
We should handle this case and timeout the pylance results.

**Comment by rchiodo** [comment]
Going to timeout the pylance results.

**Comment by greazer** [comment]
Possibly related to:
https://github.com/microsoft/pylance-release/issues/1338
https://github.com/microsoft/pylance-release/issues/2313
https://github.com/microsoft/pylance-release/issues/2347

**Comment by rchiodo** [comment]
Verification steps:

1. Install Jupyter, Python, and Pylance extensions
2. Create jupyter notebook
3. Add code that loads a csv file or creates a pandas dataframe (like so:)
```python
import pandas as pd
df = pd.DataFrame([[0, 1, 2], [1, 2, 3], [2, 3, 4]], columns=['A', 'B', 'C'])
```
4. Create new cell and try to bring up intellisense for ```df.C```

It should take at most 2 seconds (max timeout)
