### ISSUE TITLE
Wrong nbextension version loaded via script

### ISSUE THREAD

**Issue by rmorshea** [microsoft/vscode-jupyter#8909]
## Environment data

-   VS Code version: 1.63)
-   Jupyter Extension version (available under the Extensions sidebar): 2021.11.100
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Poetry
-   Jupyter server running: Local

## Expected behaviour

Load the latest version of the nbextension distrbuted with a Python package as per [this template repo](https://github.com/jupyter-widgets/widget-cookiecutter)

## Actual behaviour

An old version of the nbextension is loaded every time even if I manually reach into the extension and delete the scripts folder.

## Steps to reproduce:

```bash
pip install idom_jupyter==0.6.5
```

Then in a notebook cell run:

```python
import idom_jupyter
from idom import component, html

@component
def Demo():
    return html.h1("Hello")

Demo()
```

This should display something like 

![image](https://user-images.githubusercontent.com/4041990/152079947-5faf6321-72ec-402b-8a43-48b7c33057bf.png)

Then, inside the scripts folder there should be the following file:

```
6d1d3934e795883f824531b16d0687f5a5124b176639403c4da6c0bbe0dbd3fd/index.js
```

I assume the `6d1d3934...` is some sort of hash so that should be a way of verifying the contents. If not though, doing a search for `"0.4.0"` inside `index.js` should yield a result indicating the version of the extension being used. The [latest version of the nbextension](https://www.npmjs.com/package/idom-client-jupyter) is actually 0.6.5 though.

While the example above displays correctly, there are other features of this `idom` widget that do not work on account of this older version of the extension being loaded (it's hard to explain how to demonstrate the failure of these features due to [other issues](https://github.com/microsoft/vscode-jupyter/issues/8889)).

I'd be happy to hop on a call to talk through this since I'm not really sure what other information might be relevant to solving this.

**Comment by rmorshea** [comment]
I think this might be because I forgot to run `jupyter nbextension install --py --sys-prefix idom_jupyter`. Closing for now.

**Comment by rmorshea** [comment]
Never mind. That hasn't fixed it.

**Comment by rchiodo** [comment]
It looks to me like the python code (inside of idom_jupyter) is passing along the wrong version. It always asks for 4.0.

https://github.com/idom-team/idom-jupyter/blob/e3a9fc0ecffd9b01a0e4be7e678ac99d10e56213/idom_jupyter/widget.py#L59

You should probably ask idom_jupyter to upgrade their widget request.

**Comment by rchiodo** [comment]
The reason this works fine in jupyter is because jupyter supports loading nbextensions. Nbextensions don't work in VS code because they make a lot of assumptions about the DOM currently in use. 

We load widgets from a CDN instead (not the nbextensions folder). When widgets are packaged for a CDN, they generally include everything they need to run independently of jupyter.

The failure in this case is that the python code is asking for the wrong version.
