### ISSUE TITLE
Move cell up/down not working

### ISSUE THREAD

**Issue by kjohnsen** [microsoft/vscode-jupyter#891]
Issue Type: <b>Bug</b>

The keyboard shortcut (alt up/down) for moving a cell up or down in a Jupyter notebook simply isn't working. I click on the cell (not the input), so the cell is highlighted in blue, which I understand is necessary for the shortcut to work.

Extension version: 2020.6.91350
VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by carlschmidt26** [comment]
Are there any news about how one can move cells using this extension?

I am a little puzzled as there seem to be two commands for this task `notebook.cell.moveDown` and `jupyter.moveCellsDown` 
As I don't know which one is the right one here, I simply mapped all related commands (both appear with and without a minus in front in the `keybindings.json`) to the same (so far unused) letter `T`.
```json
    {
        "key": "t",
        "command": "-jupyter.moveCellsUp",
        "when": "editorTextFocus && jupyter.hascodecells && !notebookEditorFocused"
    },
    {
        "key": "t",
        "command": "jupyter.moveCellsUp",
        "when": "editorTextFocus && jupyter.hascodecells && !notebookEditorFocused"
    },
    {
        "key": "t",
        "command": "-notebook.cell.moveUp",
        "when": "notebookEditorFocused && !inputFocus"
    },
    {
        "key": "t",
        "command": "notebook.cell.moveUp",
        "when": "notebookEditorFocused && !inputFocus"
    },
``` 

Unfortunately nothing happens when pressing `T`. 

I'd highly appreciate any answers if there is anything I can do here.

Extension version: 2020.12.414227025

**Comment by joyceerhl** [comment]
@kjohnsen, are you on VSCode stable (blue icon) or insiders (green icon)? If the latter, and you are using the new native notebooks interface, then the "notebook.cell.moveUp" command should be working. (If it doesn't work, that's a bug.) If the former, there is no keyboard shortcut to move cells unfortunately.

**Comment by kjohnsen** [comment]
I’m on stable. I’m looking forward to the new native interface though.

Joyce Er <notifications@github.com>于2021年1月5日 周二下午9:55写道：

**Comment by stpn** [comment]
Doesn't work for me as well and I am on stable. 
Other shortcuts work however, which is puzzling.
