### ISSUE TITLE
Variables window stops refreshing after running %reset

### ISSUE THREAD

**Issue by frank-yifei-wang** [microsoft/vscode-jupyter#8921]
## Environment data

-   VS Code version: 1.63.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.18363
-   Python and/or Anaconda version: 3.9.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda 4.11.0
-   Jupyter server running: Local

## Expected behaviour

Variables window refreshes to show blank after running IPython magic commands to clear variables.

## Actual behaviour

Variables window only refreshes if run `%reset_selective` (or `del var1, var2...`, or `%reset_selective -f .*`, or restart the kernel), but not `%reset` or `%reset -f`.

*Note: I read other similar issue reports and they have all been resolved as I tested (e.g. show/hide variables window before/after restarting the kernel, etc), but this one seems to have fallen through the cracks... or it could just be my environment setup*.

## Steps to reproduce:

See screenshot below

![image](https://user-images.githubusercontent.com/42301547/152438905-781d4a44-b0b6-4a62-abe5-f34c35c1072d.png)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
NameError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_40456/2054514353.py in <module>
      1 _rwho_ls = get_ipython().run_line_magic('who_ls', '')
----> 2 print(_VSCODE_getVariableTypes(_rwho_ls))

NameError: name '_VSCODE_getVariableTypes' is not defined
```

</p>
</details>

**Comment by IanMatthewHuff** [comment]
@frank-yifei-wang Thanks for the report. I repro the same thing. The reset magic command is not something that we are currently handling. We'll have to look into handling it correctly.

**Comment by frank-yifei-wang** [comment]
@IanMatthewHuff  Thanks for response. `%reset -f` and `%reset_selective -f .*` are both IPython magic commands that clear all variables, but currently only the second one triggers the variables explorer to refresh, so I'm sticking to it for now. Hopefully there will be a solution.

I also attached test code snippet below for anyone interested in trying:

> `test = "test"; test  # run this cell and should get output 'test'`

> `%reset_selective -f .*  # run this cell and should see the variables explorer clears`

> `%reset -f  # repeat the process but skip the cell above and run this one instead, and this time the variables explorer doesn't clear (though the variable is indeed gone)`

**Comment by amunger** [comment]
looks like this has been fixed
