### ISSUE TITLE
VSCode Error on reloading workspace set to a JupyterUriProvider

### ISSUE THREAD

**Issue by C-SELLERS** [microsoft/vscode-jupyter#8930]
## Environment data

    VS Code version: 1.63.2
    Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
    Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
    OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04
    Python and/or Anaconda version: 3.6.8
    Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
    Jupyter server running: Local | Remote | N/A; Remote

## Expected behaviour

Not entirely sure, its not that its 100% a Jupyter bug, but does seem like a flaw in design 🤔 I'm wondering what kind of solutions would exist.

I have tried using `vscode.workspace.onDidOpenNotebookDocument` to register an event that would await a promise for the selector to be added, but it still throws. 

Maybe there exists a pre-intialize type setup for VScode where I can ensure its ready first. 

## Actual behaviour

Using a custom JupyterUriProvider I am able to set up a remote server selector just fine. But if I close a workspace with this selector as my specified jupyter server and a notebook open, and then reopen vscode, there is a race condition occuring where VSCode attempts to use my RemoteServerSelector before its been registered via the public Jupyter extension api:

`jupyter.exports.registerRemoteServerProvider(new RemoteJupyterServerSelector());`

When this happens I get an error message:
![image](https://user-images.githubusercontent.com/41277998/152603169-b3461326-f2ea-4d0b-83f9-7ab0091b3f98.png)

Within a second or so later though, the remote selector is added and it works fine again. 

Its just very sensitive on start if I already have the notebook open in the workspace.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1.  Create remote server selector (see [this](https://github.com/microsoft/vscode-jupyter/blob/bd63750c91e6e23dacdfb99c24d88086e0d1acd4/src/test/datascience/extensionapi/exampleextension/ms-ai-tools-test/src/extension.ts))

2. Open a notebook using that server selector
3. Close VSCode (Leave the notebook tab open)
4. Reopen; when vscode goes to reopen the notebook the error will pop up.

## Logs

```
Info 13:06:47: ZMQ install verified.
Info 13:06:47: Checking for server existence.
Info 13:06:47: Checking for server usability.
Info 13:06:47: Starting notebook server.
Info 13:06:47: Connecting to server
Error 13:06:47: Failed to get remote kernel connections [Error: Server URI cannot be used. Did you uninstall an extension that provided a Jupyter server connection?
	at l.getJupyterServerUri (c:\Users\Colton\Desktop\Programs\VSCode\data\extensions\ms-toolsai.jupyter-2022.1.100\out\client\extension.js:66:1282762)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async v.updateServerUri (c:\Users\Colton\Desktop\Programs\VSCode\data\extensions\ms-toolsai.jupyter-2022.1.100\out\client\extension.js:113:290879)
	at async v.startOrConnect (c:\Users\Colton\Desktop\Programs\VSCode\data\extensions\ms-toolsai.jupyter-2022.1.100\out\client\extension.js:113:289718)
	at async c:\Users\Colton\Desktop\Programs\VSCode\data\extensions\ms-toolsai.jupyter-2022.1.100\out\client\extension.js:113:288413]
```

**Comment by rchiodo** [comment]
Did you include this in your contributes section?

```
	"contributes": {
		"pythonRemoteServerProvider": [
			{
				"id": "<your server uri provider id>"
			}
		],
```

That is supposed to allow us to reload your extension before we try and get the jupyter server URI.

**Comment by C-SELLERS** [comment]
Ah no I did not! Thank you, will try on Monday and confirm.

**Comment by greazer** [comment]
Sounds like a resolution is at hand. Closing for now. Thanks for the feedback and PR. :)

**Comment by C-SELLERS** [comment]
Ayo just an update on this guy, adding in the `contributes` section for the `pythonRemoteServerProvider`, it still throws and posts the error. 

```
Error 16:28:46: Failed to get remote kernel connections [Error: Server URI cannot be used. Did you uninstall an extension that provided a Jupyter server connection?
```

We ended up just working around the issue by not using a remote selector since we didn't need it. But still thought it was worth testing for the sake of awareness.
