### ISSUE TITLE
variable viewer search

### ISSUE THREAD

**Issue by mfieraci** [microsoft/vscode-jupyter#8934]
Hello,

Would you be able to add a search feature to the Variable Viewer Tab?
I know it currently has the option to filter alphabetically or by type, but being able to search by name or type would make this feature a lot easier to use

best,

**Comment by amunger** [comment]
thanks for the suggestion, lack of search was also mentioned in the much broader request for variable explorer improvements: https://github.com/microsoft/vscode-jupyter/issues/1148

**Comment by roblourens** [comment]
When the variables viewer becomes built-in, it will likely get this feature automatically: https://github.com/microsoft/vscode/issues/165445
