### ISSUE TITLE
jupyter causes inconsistent results comparing to the terminal

### ISSUE THREAD

**Issue by seyeeet** [microsoft/vscode-jupyter#8941]
## Environment data

-   VS Code version: 1.64.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.1.1001775990
-   Python Extension version (available under the Extensions sidebar): v2022.0.1786462952

-   OS (Windows | Mac | Linux distro) and version: Windows 
-   Python and/or Anaconda version: 4.9.2, and  python 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv conda
-   Jupyter server running: Remote 

I recently updated my jupyter in vscode and rerun some of my experiments in the vscode jupyter, I notice some results that did not match previous runs and by digging more into the problem I notice that when I use the jupyter for running the scripts it does not run the code correctly and the results is different from the case that I run the code directly from terminal, I am not sure how it happens or why, but this so annoying and can make people confused.
This definitely should not happen.
The expected behavior is when I run the scripts from jupyter notebook and terminal for the same seed it generates exactly same results as they are the same, but for some reason it does not happens and the results are different.
My last version which was 2 months ago was working okay btw

**Comment by seyeeet** [comment]
I changed back to version v2021.11.1001550889 for jupyter and python v2022.0.1786462952
 and it seems to work okay and normal again

**Comment by DonJayamanne** [comment]
@seyeeet Thanks for filing this issue
Unfortunately without more information its difficult to address the issue.

* Please could you let us know what is working and what is not
	* Please could you provide some sample code?
 * Please could you provide the output from the `Jupyter` output panel as well.
* What do you mean by inconsistent result?
	* Do you mean to say the code runs, but the output is different?

**Comment by seyeeet** [comment]
Do you mean to say the code runs, but the output is different?
yes
I will, provide more information regarding the questions that you asked later for sure, I switched to an older version for now so I wont have time to do it again :(
I will close this issue to not annoy you with it and later will reopen it when I can go the version that was problematic and provide the answers for your questions :)
thank you for your support
