### ISSUE TITLE
ipynb files no longer run

### ISSUE THREAD

**Issue by Abhishek2271** [microsoft/vscode-jupyter#8947]
Does this issue occur when all extensions are disabled?: The issue is with Jupyter extension after the update. Reinstalling the said extension does not help.

Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. The code gets stuck on "Connecting to Kernel". 
![image](https://user-images.githubusercontent.com/33551684/152702049-7eaaa986-b337-4fb8-903d-b96382588703.png)

This happened after the last update. Before this code was running fine. Also, where can I disable the updates. Is it necessary that  the updates are automatic?

**Comment by Abhishek2271** [comment]
Hi,

Thank you for the reply. Here are the details:

> Version of Python (and type of the environment, is it anaconda, virtual environment)
The Python version is 3.6.5. It is locally installed.

> the output from the Jupyter output panel
I think vs instance is not able to create a Jupyter session as the loading bar appears at the bottom-right of the screen. It says "waiting for the Jupyter session to be idle" and keeps on waiting. Below is a screenshot with the full message. 

It is a bit weird because I have had the same issue when I updated vs code a few months before as well but at the time the issue was fixed by just closing all .ipynb sessions and restarting the vs but this that did not work.

![image](https://user-images.githubusercontent.com/33551684/152889770-0efafcf3-dc30-42ce-8bee-8b07e04c8e93.png)

**Comment by DonJayamanne** [comment]
Please could you provide the output from the `Jupyter` output panel

**Comment by Abhishek2271** [comment]
I am not sure what you mean by the output panel.

**Comment by YARARMAN** [comment]
Step One: Extensions > Settings (Top Right 3 Dots Icon) > Auto Update Extensions > None

Step Two: Extensions > Jupyter > Down Arrow to Tight of Uninstall > Install Another Version... > v2022.1.1001614873 from List

**Comment by DonJayamanne** [comment]
> I am not sure what you mean by the output panel.

![outputpanel](https://user-images.githubusercontent.com/1948812/152953509-322334f8-c51f-4b2b-87ab-71254bb748fe.png)

**Comment by Abhishek2271** [comment]
> Step One: Extensions > Settings (Top Right 3 Dots Icon) > Auto Update Extensions > None
> 
> Step Two: Extensions > Jupyter > Down Arrow to Tight of Uninstall > Install Another Version... > v2022.1.1001614873 from List

This worked thank you. The extension was updated some days ago it seems.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, please could you try re-installing ipykernel & ipython as follows:
`/usr/local/bin/python3 -m pip install ipykernel ipython -U --fore-reinstall`

Looks like some of the dependencies are incompatible (more information here https://stackoverflow.com/questions/65843310/completion-in-ipython-jupyter-does-now-work-unexpected-keyword-argument-colu).
