### ISSUE TITLE
Jupyter Notebook startup not running when current folder has a ' in it

### ISSUE THREAD

**Issue by etiennecelery** [microsoft/vscode-jupyter#8957]
## Environment data

-   VS Code version: 1.64.0
-   Jupyter Extension version: v2022.1.1001775990
-   Python Extension version: v2022.0.1786462952
-   OS: Windows 10
-   Python and/or Anaconda version: 3.8.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Previous to the latest update to VS Code, the Jupyter Notebook File Root could be set to the File Directory or to the Workspace Folder,  so you can open files as the python terminal would.

## Actual behaviour

Now it seems the notebook File Root is stuck using the File Directory, no matter how many times I reset VS Code and set it to Workspace.
I can confirm that downgrading to Jupyter v2022.1.1001614873 fixes the bug, so it was indeed the new update.

<p>

</p>
</details>

**Comment by rchiodo** [comment]
Oh no wait, I have to close the notebook and start over when switching the setting. That seems strange. 

Should be a workaround though.

**Comment by rchiodo** [comment]
No sorry, it just needs a second for it to update on restart. I can change the setting with the notebook open. As long as I restart the kernel is does change the working directory.

**Comment by rchiodo** [comment]
Can you also include the contents of the Output | Jupyter tab? Thanks

![image](https://user-images.githubusercontent.com/19672699/153052445-1002cc11-e83b-413b-8807-55498955ed1b.png)

**Comment by etiennecelery** [comment]
Hi, 
Thanks for your follow up.

Here are screenshots of 3 trials:

1) `workspaceFolder`
![workspace](https://user-images.githubusercontent.com/22829290/153063277-988de2aa-f592-4772-aa8c-376ae575cb57.PNG)

2) `fileDirname`
![filedirname](https://user-images.githubusercontent.com/22829290/153063544-7fa3a52f-41b6-411a-939e-7b34b4a8b0b7.PNG)

3) `workspaceRoot`
![root](https://user-images.githubusercontent.com/22829290/153063827-4eae488c-6eac-4b60-b61f-fc1842d692d3.PNG)

As you can see, they end with the same results.

**Comment by rchiodo** [comment]
What's the directory your file is in?

**Comment by rchiodo** [comment]
I'm trying to narrow down the repro steps. It's unlikely we can fix the issue if we can't repro the problem. 

Does it work if you try a different directory structure? Like say something like ```C:\Users\ecp\workspace\data\jpm\file.py```?

Maybe it has something to do with onedrive. One drive redirects directories AFAIK.

**Comment by rchiodo** [comment]
Additionally the Jupyter output log would be helpful. I can see why we're not setting the directory correctly.

**Comment by etiennecelery** [comment]
I don't see any output from the Jupyter output log. 
However you were right! It appears something is up with OneDrive.
I created a folder in c:// and shows a different output. However, in the previous Jupyter version this doesn't happen, as I can use the folder inside my OneDrive.

![success](https://user-images.githubusercontent.com/22829290/153068211-c1b9a259-e2bb-45af-85a5-b64c1d978d18.PNG)

**Comment by rchiodo** [comment]
Jupyter output tab should be here:

https://user-images.githubusercontent.com/19672699/153052445-1002cc11-e83b-413b-8807-55498955ed1b.png

Not sure how the older version would work with OneDrive and the newer one wouldn't. Are you also using an older VS code (and not just an older jupyter extension)? 

We ask VS code for file paths, it might be something changed in VS code itself with respect to OneDrive.

**Comment by rchiodo** [comment]
I finally repro'd the problem. I recreated your entire directory structure from the original example and it repros. 

I suspect it might be the extra characters in the directory somehow. Not sure how this would have changed since last release though.

**Comment by rchiodo** [comment]
Problem is the ```'``` in the path. We have code that's executing that is using a ```'``` and the path is getting messed up.

**Comment by rchiodo** [comment]
The reason this used to work is the specific piece of code to be executed was run independently before. This last release we run all of the startup code in one chunk (so all of it fails, including the code to change the working directory).

**Comment by greazer** [comment]
This has been fixed.
