### ISSUE TITLE
Windows vscode.tests have multiple failures:

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8958]
![image](https://user-images.githubusercontent.com/19672699/153509545-91454414-3c8b-485e-9157-8dce10302039.png)

Captured from here:
https://github.com/microsoft/vscode-jupyter/runs/5148028223?check_suite_focus=true

**Comment by DonJayamanne** [comment]
I'm looking into `Python kernel returned if no matching kernel found...`

**Comment by rchiodo** [comment]
> I'm looking into `Python kernel returned if no matching kernel found...`

Entered a separate issue for that one:
https://github.com/microsoft/vscode-jupyter/issues/8959

**Comment by rchiodo** [comment]
Reopened. Tests are actually running now and not working. Only 34 tests run in windows.

**Comment by rchiodo** [comment]
Verification steps;
- Make sure windows tests are passing
