### ISSUE TITLE
Test failure with selecting kernel

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8959]
Recent failure:
![image](https://user-images.githubusercontent.com/19672699/153055948-e6e11aed-d0c5-4ca2-9d97-1b23d3de4210.png)

Copied from here:
https://github.com/microsoft/vscode-jupyter/runs/5112911623?check_suite_focus=true

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/8953 (fails even on Linux)
