### ISSUE TITLE
Typo in "Failure to start Kernel due to Modules not installed" wiki

### ISSUE THREAD

**Issue by owalid** [microsoft/vscode-jupyter#8965]
In wiki "[Failure to start Kernel due to Modules not installed](https://github.com/microsoft/vscode-jupyter/wiki/Failure-to-start-Kernel-due-to-Modules-not-installed)" there is a typo on the command with python.  It is written **fore-reinstall** instead of **force-reinstall**.

The command: 
`python -m pip install <xyz> -U --fore-reinstall` should be `python -m pip install <xyz> -U --force-reinstall`

**Comment by rchiodo** [comment]
Thanks for noticing. I fixed it.
