### ISSUE TITLE
Refactor test code to go under a single 'test' folder

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8975]
As discussed in our architecture review, this task is to move 'test' related code into a 'test' folder (or whatever you decided to name it).

The main reason for this is to ensure we never reference test related code inside of production code. One way to achieve this is to have a completely separate 'test' folder at the root (instead of under src).

This would include stuff like:
- standardTest.ts
- index.ts
- all *.vscode.test.ts files
- test helper code

It would NOT include:
- all unit tests. These would reside next to the code they're testing

**Comment by DonJayamanne** [comment]
> One way to achieve this is to have a completely separate 'test' folder at the root (instead of under src).

Not moving all of the tests, no need we can use linters to achieve the same requirement.

**Comment by rchiodo** [comment]
> Not moving all of the tests, no need we can use linters to achieve the same requirement.

Yeah I tried this and it was a huge pain having two root dirs in the tsconfig. Changed relative paths everywhere.

**Comment by DonJayamanne** [comment]
Done as per discussion
