### ISSUE TITLE
Refactor high level folders

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8976]
This is a rollup issue of the following issues:

- [x] #8970
- [x] #8971
- [x] #8972
- [ ] #8973
- [ ] #8974
- [x] #8975
- [x] #8981
- [ ] #9324?
- [x] #9337

Once all of those issues are complete we should have:
- src and test at the root
- src should have:
   - Kernels
   - Notebooks
   - InteractiveWindow
   - LanguageServices
   - Webviews
   - Test

**Comment by amunger** [comment]
I would suggest an Extension top level folder as well: https://github.com/microsoft/vscode-jupyter/issues/8981

**Comment by amunger** [comment]
Yeah I think a single extension.ts starting point would be great to have since it follows the convention used in the extension documentation
