### ISSUE TITLE
Live PDF/HTML Preview

### ISSUE THREAD

**Issue by bronze7** [microsoft/vscode-jupyter#8978]
Side by side Preview of the Notebook in PDF or HTML format. So that user can see the changes made to customize the notebook.
<br>
Thanks

**Comment by IanMatthewHuff** [comment]
@bronze7 . Thanks for the feature request here. Just to make sure that I'm fully understanding the request, you are looking for something like the current "Export To HTML" feature, but one that is displayed Side by Side with the notebook and continually updates as the code or outputs of the notebook change?

**Comment by DonJayamanne** [comment]
Thanks for this suggestoin, however there haven't been any upvotes on this feature request
Hence closing this for now
