### ISSUE TITLE
`IPKernelApp.launch_instance` `user_ns` Variables Not Detected

### ISSUE THREAD

**Issue by AaronBeaudoin** [microsoft/vscode-jupyter#8987]
## Environment data

-   VS Code version: 1.64.1
-   Jupyter Extension version: v2022.1.1001821375
-   Python Extension version: v2022.0.1814523869
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: Python 3.7.3
-   Type of virtual environment used: N/A
-   Jupyter server running: Remote

## Expected behaviour

`user_ns` variables are detected and I get no `"<variable_name>" is not defined (reportUndefinedVariable)` Pylance errors.

## Actual behaviour

`user_ns` variables are not detected and I get `"<variable_name>" is not defined (reportUndefinedVariable)` Pylance errors.

## Steps to reproduce:

1. Connect to a remote Jupyter server on which you've created a custom kernel which adds data to `user_ns`. Here is a minimal example kernel:

```python
from ipykernel.ipkernel import IPythonKernel
from ipykernel.kernelapp import IPKernelApp

IPKernelApp.launch_instance(kernel_class=IPythonKernel, user_ns={"a": 1, "b": 2})
```

2. Try using the `a` or `b` variables in a cell. You get a Pylance error.

**Comment by AaronBeaudoin** [comment]
Also, here is `kernel.json`:

```python
{
  "argv": ["/usr/bin/python3", "-m", "my_kernel", "-f", "{connection_file}"],
  "display_name": "Odoo",
  "language": "python"
}
```

...where `my_kernel` had been added to `PYTHONPATH`.

**Comment by IanMatthewHuff** [comment]
Your comment here is actually correct. 

> Pylance isn't correctly using the Python environment from the remote Jupyter kernel

Right now our pylance support won't be using the python on the remote machine. If you were seeing this work before it was possible that it was trying to work with your local python interpreter and able to match up some pylance results from that.

**Comment by IanMatthewHuff** [comment]
It's interesting though. I believe that even in the local case we would miss these variables as we look at code executed in the file, and these are defined in the kernel. I'm going to leave this bug open for discussion at triage.

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time.
