### ISSUE TITLE
Try Except all startup code 

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8988]
I think the simplest fix here is to just fix the bug where we're using ```'``` to wrap a path in the startup code. However @amunger had another idea. We could wrap each individual statement in a ```try:except:``` block to prevent one part of startup breaking other pieces.

_Originally posted by @rchiodo in https://github.com/microsoft/vscode-jupyter/issues/8957#issuecomment-1035247483_

**Comment by IanMatthewHuff** [comment]
https://github.com/microsoft/vscode-jupyter/pull/9197 resolved here.

Change was not to fully try except everything. Just parts that we expect might fail. However now we log and send telemetry for failures in our startup code, user specified startup code, variable fetching code, and IW debug configuration code.

**Comment by rchiodo** [comment]
/verified

I get this now (if I make an error) but startup still works:
```
Error 13:42:42: Error executing user defined startup code print(x) NameError: name 'x' is not defined 
     [1;31m---------------------------------------------------------------------------[0m
    [1;31mNameError[0m                                 Traceback (most recent call last)
    Input [1;32mIn [1][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m [38;5;28mprint[39m(x)
```
    [1;31mNameError[0m: name 'x' is not defined
