### ISSUE TITLE
Python 3.9 environments not showing up in Kernel list but are in Interpreter list

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8993]
I have this for a kernel list:

![image](https://user-images.githubusercontent.com/19672699/153516845-a1a9b7f3-4da8-4c90-8072-a1c8cbd8f9f8.png)

But this for an interpreter list:

![image](https://user-images.githubusercontent.com/19672699/153516867-7615904c-bd55-42a6-b0cd-5d9889b305e2.png)

I would have expected the 3.9 interpreter to show up too.

**Comment by rchiodo** [comment]
[jupyter.log](https://github.com/microsoft/vscode-jupyter/files/8045083/jupyter.log)

**Comment by rchiodo** [comment]
And no I didn't filter them. Checked that first

**Comment by greazer** [comment]
Not reproing.
