### ISSUE TITLE
Getting list of running notebooks

### ISSUE THREAD

**Issue by SergeyTsimfer** [microsoft/vscode-jupyter#8996]
It would be great to have an analog of `jupyter_server.serverapp.list_running_servers` to get the information about notebooks, created by `VSCode-jupyter`.

As of now, by parsing `tmp/tmp-*.json` files and matching their `key` field to processes in `proc/PID/`, we can get *some* idea about which notebooks are currently running, but it is impossible to get some of the useful fields like notebook names/cwd/path.

**Comment by amunger** [comment]
Thanks for the suggestion. I believe we are working on something for this already (assuming you mean running kernels), though I'm unable to find any related issue for it.

**Comment by amunger** [comment]
@SergeyTsimfer - are you looking for something in the UI that lists the kernels, or are you trying to use the list in your own extension?

**Comment by SergeyTsimfer** [comment]
I've developed a Python [library](https://github.com/analysiscenter/nbtools) that shows all of the running Python processes, their names, and resources they are using (CPU, RSS, NVIDIA devices, etc). 

It works well with Jupyter Notebooks started in JupyterLab, regular Jupyter, and a few other ways to create a running kernel. In doing so, it relies on, for example, `jupyter_server.serverapp` API to match the `kernel_id` of a given process to the name/path of an actual notebook it executes.

Unfortunately, VSCode does not expose such API. While I can still get the `kernel_id` (actually, `key`, that is returned by the `ipykernel_launcher` at kernel launch) of a process and get all of the resource statistics, I can't match it to the name/path of this notebook in a reasonable and non-hacky way.

**Comment by amunger** [comment]
OK, it sounds like you would be able to achieve that if we fixed #8827.
I'll close this issue in favor of that, and you can vote on that other issue if that works for you.
