### ISSUE TITLE
selecting LaTeX as language for a markdown cell changes it to a code cell

### ISSUE THREAD

**Issue by openSourcerer9000** [microsoft/vscode-jupyter#8998]
When changing the cell type to LATeX it tries running it as python, see these issues for more details. Remember to LaTeX up and always practice safe threads.

https://github.com/microsoft/vscode-jupyter/issues/3986
https://github.com/microsoft/vscode-jupyter/issues/1216

**Comment by amunger** [comment]
You need to put latex in a markdown cell for it to render.

Running a code cell will attempt to run against the selected kernel, no matter what language you have selected for the cell

**Comment by openSourcerer9000** [comment]
OK, clicking the [+ Markdown] button to add a new cell. Change the language of the cell from markdown to latex. Paste in `\[E=mc^2\]` and run the cell:

```
File "C:\Users\AppData\Local\Temp/ipykernel_2184/1172784145.py", line 1
    \[E=mc^2\]
             ^
SyntaxError: unexpected character after line continuation character
```
It's still hitting the python interpreter.

**Comment by openSourcerer9000** [comment]
Expected behavior would be if you change a cell to LaTeX it will render LaTeX, not run in python.

**Comment by amunger** [comment]
You have to leave it as markdown and use $$ to use the Katex renderer.
```
$$
[E=mc^2]
$$
```

But that is pretty confusing behavior, I updated the title to try and reflect the problem better

**Comment by openSourcerer9000** [comment]
Great, thanks, this method does work for me

**Comment by DonJayamanne** [comment]
Or you could the following
```python
%%latex
$$
[E=mc^2]
$$
```

**Comment by DonJayamanne** [comment]
Closing as resolved

**Comment by amunger** [comment]
related discussion in core https://github.com/microsoft/vscode/issues/120587
