### ISSUE TITLE
How to verify fixes when customer's machine is broken

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9002]
This issue here:
https://github.com/microsoft/vscode-jupyter/issues/8995

Was caused by bug in the daemon startup code. However the fallback works fine on test machines (and anybody that tries it in house). 

Can we catch these corner cases in testing?

**Comment by greazer** [comment]
Need some tests to validate daemon actually starts when we expect it to.

**Comment by DonJayamanne** [comment]
We have the necessary tests to ensure the daemon works. Hence clsoing this issue
