### ISSUE TITLE
Don't prompt for prerelease in a dev container

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#9005]
1) start up vscode insiders with the remote containers extension installed
2) open https://github.com/Chuxel/notebooks-test in a dev container
3) Open the notebook file 

-> I get prompted with the following notification:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/4674940/153663316-a9b01be8-955b-4898-b653-80cc46f8f475.png">

We should not prompt in a dev container. Also, the usage of "recommended" seems to suggest that if I don't follow the recommendation that I might not have as great of an experience as if I don't follow the recommendation. This is not the case though. Whether or not I use the prerelease version of an extension is a personal choice.

**Comment by greazer** [comment]
@kieferrm, why do you think that we should not prompt in this case?

**Comment by kieferrm** [comment]
Yes, I propose to not prompt. My reasoning: 
1) I assume that when you open a dev container with Insiders, you are not a new Insiders users. I believe this is a safe assumption since most people either user Insiders or Stable and usually stick with their choice. 
2) If you use Jupyter notebooks regularly and because of 1) you have seen the prompt before.
3) Because of 1) and 2) if you see the prompt, it's either because you either installed the extension while being in the dev container or the dev container spec said the extension should be installed.
4) If you installed the extension while being in the dev container, you made your choice at the moment of installation that you don't want to use the prerelease version.
5) If the devcontainer spec says you need the extension and because of 2) you are new to the Jupyter extension you are not the right audience for the prerelease version of the extension.

**Comment by IanMatthewHuff** [comment]
Resolving as a duplicate based on my fix for #11477 (which was totally removing the pre-release notification).
