### ISSUE TITLE
Couldn't start kernel that definitely works

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#9011]
@ronglums machine while debugging a different problem with her experienced a situation where right after updating the Jupyter extension to a later build and reloading, she wasn't able to start the kernel again, the first time she tried. Second time it worked. I've attached the logs.
[ronglums.log](https://github.com/microsoft/vscode-jupyter/files/8052515/ronglums.log)

**Comment by DonJayamanne** [comment]
@greazer @ronglums 
* Is this still not working?
* its difficult to figure out why things didn't work, for some reason we weren't able to load some packages.

@ronglums 
Please could you add the following setting into your user config:
* `jupyter.development: true`
* Reload VS Code
* Open a notebook and select the command `Jupyter (dev): Clear Cache`
* Wait for a few seconds, reload VS Code and try this once again

**Comment by DonJayamanne** [comment]
Is this still an issue, should we close this?

**Comment by greazer** [comment]
Closing per Rong stating that she is no longer reproing.
