### ISSUE TITLE
Contributions to `interactive/toolbar` menu lack adequate `when` clauses

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-jupyter#9037]
Issue Type: <b>Bug</b>

With Jupyter extension installed, install another extension that implements an `interactive` type `NotebookController` and provides a command to execute `interactive.open` that uses this controller.

Observe that the Jupyter toolbar buttons appear at the top of the interactive window despite it being correctly set to use a non-Jupyter controller (i.e. kernel).

![image](https://user-images.githubusercontent.com/6726799/154064008-cfb8119f-9c20-4b8e-aa28-8c9580c8865f.png)

Extension version: 2022.1.1201831736
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by rchiodo** [comment]
Thanks for the issue. Do you know what when clause would fix the problem? I'm not sure there's a context that indicates a 'jupyter' based interactive window.

**Comment by gjsjohnmurray** [comment]
Does `editorLangId` work as a way to narrow down to the languages you handle?

**Comment by rchiodo** [comment]
Is ```editorLangId``` set for the interactive window?. Doesn't really make sense.

**Comment by rchiodo** [comment]
We might be able to use whether or not one of our kernels is being used.

**Comment by rchiodo** [comment]
.NET team is asking for this for regular notebooks too.

**Comment by gjsjohnmurray** [comment]
> Is `editorLangId` set for the interactive window?. Doesn't really make sense.

What do you set your controller's `supportedLanguages` to? And which language gets used for colouring etc?

**Comment by rchiodo** [comment]
This is the list of languages supported by a python kernel:
https://github.com/microsoft/vscode-jupyter/blob/c26705632e8ca7f0f1cda6c0861cc2bb79c7f51a/src/datascience-ui/common/constants.ts#L18

Other kernels (from kernelspecs on disk) generally just list one.

Colorization is not done by us. It's done by VS code based on the language of a cell.

**Comment by gjsjohnmurray** [comment]
In the interactive case, how does the user change the language of a cell?

What language does VS Code colorize the interactive input text as the user types it?

Based on my brief experiments with an extension I'm prototyping, if the controller's `supportedLanguages` array contains at least one languageId then the (editable) input text and the (read-only) cell text is colorized for the first one. And if the array is empty it's not colorized at all.

**Comment by rchiodo** [comment]
> In the interactive case, how does the user change the language of a cell?

They don't. It's set by running code from somewhere else.

> What language does VS Code colorize the interactive input text as the user types it?

Python I believe. I think the interactive window creates the editor with that language. I don't believe it uses the controller at all, but I'd have to look in VS code's source.

**Comment by gjsjohnmurray** [comment]
My PR https://github.com/microsoft/vscode/pull/143163 was merged (thanks @rebornix)

**Comment by gjsjohnmurray** [comment]
Today's Insiders was built from the commit immediately before that, so we'll have to wait until tomorrow for this to turn up.

**Comment by rchiodo** [comment]
It will probably be a while before we get to this @gjsjohnmurray, so if you have the need for this sooner, PRs are welcome.
