### ISSUE TITLE
Does anyone work for vscode-web especially jupyter-notebook?

### ISSUE THREAD

**Issue by dahatake** [microsoft/vscode-jupyter#9046]
Goal:
- Run jupyternotebook extentions in VS Code for web

Issue:
- Somebody can't install VScode and extensions to his/her PC/Mac. To support these user, this support is highly helpful.

**Comment by rchiodo** [comment]
Jupyter notebooks don't currently run in the web, but they should work in VS code desktop.

What errors are you getting when trying to install on the user's machine?

**Comment by dahatake** [comment]
Some users can't install any software due to their company security policy, unfortunately.
I understand this is not issue for jupyter extensions, jupyter-notebook itself.

**Comment by DonJayamanne** [comment]
@dahatake you might want to take a look at github codespaces and/or using vscode inside of docker (assuming docker is installed or allowed to be installed).
