### ISSUE TITLE
Typo in "Failure to start Kernel due to Modules not installed" wiki page.

### ISSUE THREAD

**Issue by a1eaiactaest** [microsoft/vscode-jupyter#9050]
Couldn't find a way to make a pull request to wiki, but there's typo in [Failure to start Kernel due to Modules not installed](https://github.com/microsoft/vscode-jupyter/wiki/Failure-to-start-Kernel-due-to-Modules-not-installed) wiki page. `pytprocess` should be `ptyprocess`. The typo can make a lot of people confused, like me while getting error of `pytprocess` can't be found by pip.

**Comment by rchiodo** [comment]
Thanks for noticing. Fixed the wiki page.
