### ISSUE TITLE
Create a 'blessed' environment that has known modules installed

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9055]
We could add this as a default kernel for most environments. 

We'd know that it has a bunch of packages that work.
- Ipykernel
- Nbconvert
- Pandas
- Debugpy
- IPython
- numpy
- matplotlib

**Comment by DonJayamanne** [comment]
I think we should have a yml file so users can create conda environments for these.

**Comment by DonJayamanne** [comment]
However the more i think about these, we should submit fixes to the dock container definitions & the like.
Else I'm concerned we just end up proliferating different blessed environments.

**Comment by rchiodo** [comment]
I think there's a lot of ways to do this. Docker container might be one (feels like nobody would use it though). 

I was thinking a venv that we support for say 3 versions of python or something.

**Comment by minsa110** [comment]
https://github.com/microsoft/vscode-python-internalbacklog/issues/420
