### ISSUE TITLE
jupyter extension does not understand "~" refer to home directory

### ISSUE THREAD

**Issue by henrysky** [microsoft/vscode-jupyter#9058]
I was referred to post the issue here from microsoft/vscode#143252

## Environment data

-   VS Code version: 1.64.2
-   Jupyter Extension version (available under the Extensions sidebar):  v2022.1.1301854968 
-   Python Extension version (available under the Extensions sidebar): v2022.0.1814523869 
-   OS (Windows | Mac | Linux distro) and version: Windows 10 21H2 x64
-   Python and/or Anaconda version: Python 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Jupyter server running: Local

## Expected behaviour

Open file without no issue by treating `~` as user directory

## Actual behaviour

Cannot open file because treating `~` literally as `~`

## Steps to reproduce:

1. Run some python codes that will raise error
2. Attempt to open one of the file in trace (e.g. click on the number `267` below to open `constant_op.py` ). Since VSCode seems to treat `~` literally `~`, it will fail to open the file. If select "create file", a folder `~` will literally be created under C drive.

![image](https://user-images.githubusercontent.com/28623434/154411647-fe7e3be5-36d2-4961-8e00-7a63a91d5d14.png)

**Comment by IanMatthewHuff** [comment]
@henrysky Thanks for the report. I know the spot we add in that file link in code so might just be a quick fix I can make. Oddly enough, there is something off on my builds with the tracebacks in general so I'll have to investigate that first before the ~ fix.
