### ISSUE TITLE
Allow extensions to pass their display names when registering themselves using the registerRemoteServerProvider()

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-jupyter#9059]
We could pass a display name variable in the JupyterUriProvider which is passed in the registerRemoteServerProvider() api of the Jupyter extension. This can then be shown in the description of the quick picks rather than something like "ms-toolsai.vscode-ai"

**Comment by IanMatthewHuff** [comment]
Seems reasonable. Should be an easy change.

**Comment by greazer** [comment]
Hey @shsuman, we're concerned that we don't want to just allow an extension to override. The extension id needs to continue to be displayed. Please feel free to provide a PR for this. :)

**Comment by shsuman** [comment]
The reason I was asking for this specifically because we got rid of Jupyter extension as a hard dependency and now we are seeing (From unknown extension) in the quickpick description. The way I am able to repro it is to activate the Azure ML extension first, then open a notebook and click the "Jupyter Server" on the status bar.

![image](https://user-images.githubusercontent.com/44413557/155289737-51d0524c-23d2-488a-9868-9666488c2a0f.png)

**Comment by DonJayamanne** [comment]
i think it's a bug in the extension, I'll take a look.
please could you provide the steps to repro this issue

**Comment by shsuman** [comment]
@DonJayamanne It is currently reproducible in an internal dev build. I will send you the VSIX and instructions separately :)
