### ISSUE TITLE
Support Jupyter completions being shown in .py files for Interactive Window scenario

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#9073]
Filed from this bug here: https://github.com/microsoft/vscode-jupyter/issues/8983

Given the following code in a .py file:
#%%
import pandas as pd
df = pd.DataFrame({'test': [1,2], 'test2': [2,3]})

#%%
df.

If the server is running and you do df. the autocompletions will see the data frame methods, but they will not see .test or .test2. If you are doing this in a running notebook cell or input box of the interactive window you do see column name autocompletions. These are provided by Jupyter. In the same way that we provide hover values in .py files when Jupyter is running we could add in Jupyter completions to this file.

**Comment by IanMatthewHuff** [comment]
@natwille1 Created this new issue for the .py column name completions.

**Comment by DonJayamanne** [comment]
Closing this issue as there haven't been any upvotes or comments on this issue for a while (not since it was created)
