### ISSUE TITLE
Fresh NB: Need to run cell twice to activate kernel

### ISSUE THREAD

**Issue by p-i-** [microsoft/vscode-jupyter#9083]
Issue Type: <b>Bug</b>

Create a fresh 'foo.ipynb' file in file-explorer.
Click it to open.
`print('foo')` in first cell.
CMD+ENTER to execute

Nothing happens

Click on that cell and CMD+ENTER a second time
Now the 'Select kernel' list pops up

Very minor glitch, but probably an easy fix.

Extension version: 2022.1.1301854968
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id 208511c2-dba0-4576-b4d0-606dd0e49428|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30438340
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrt:30437039
vsrem710:30416614
vscop841cf:30438916
vsbas813:30436447
vscscmwlcmc:30438804
helix:30438806
vscaac:30438847

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue. This should be fixed in the latest insiders build of VS code.
