### ISSUE TITLE
Shell commands such as !pip !python !where python do not point to the right executable

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9089]
This has been reported a few times and we've take the route of recommending users use `%pip` and the like, and didn't really fix the underlying issue.

Solution: Put the python executable directory in front of the PATH entries

**Comment by joyceerhl** [comment]
@DonJayamanne Do you have any specific verification steps?

**Comment by rzhao271** [comment]
I get a list of Pythons when I run `!where python` in the IW but I don't think it found the venv one:

![A list of Pythons in the IW](https://user-images.githubusercontent.com/7199958/156078597-ece171c6-2c9a-4303-ae92-1c72eddd803a.PNG)

**Comment by DonJayamanne** [comment]
@rzhao271 can you confirm you have the latest pre-release version of the Jupyter extension?

**Comment by rzhao271** [comment]
It works!
