### ISSUE TITLE
Support custom (non-local) log directories with built-in tensorboard

### ISSUE THREAD

**Issue by DavidMChan** [microsoft/vscode-jupyter#9093]
Tensorboard already supports S3 as a backend for a log directory, however VSCode's tensorboard extension forces the logdir selected to be local. It would be nice if the plugin also supported remote log directories, so I don't have to launch tensorboard from the command line, and can instead just use the builtin vscode launcher.

**Comment by rchiodo** [comment]
Thanks for the suggestion.

**Comment by greazer** [comment]
Thanks for the suggestion, @DavidMChan.

**Comment by DonJayamanne** [comment]
@DavidMChan 
Please could you provide more information on your current setup (with S3) and workflow on how you use S3 today and then view the logs.
Is this something for a remote Jupyter server running on AWS, and then you use VS Code to connect to that or the like.
Basically I"m trying to understand your setup and workflow today to get a better understanding on how and what needs to be changed to improve this experience.

**Comment by DavidMChan** [comment]
Hi @DonJayamanne - Thanks for looking into this!

I have an interesting situation where I'm writing code on a laptop using the VSCode remote plugin, but running that code on several machines that are connected to the internet, but not connected to each other (through something like NFS). This is actually pretty common at universities, where we have lots of personal desktops running ML experiments, but no formal cluster infrastructure.

*Honestly*, this is mostly just a nit - since you can always run tensorboard in a terminal, and use port-forwarding (if the sysadmin allows), since you can launch Tensorboard natively against an S3 directory with:
```
tensorboard --logdir s3://<your S3 bucket here>
```
But when you try to launch tensorboard this way using the VSCode integration, it gives you a "file not found" error, since it assumes that all paths that you pass in are local. It would be nice to not have to do the terminal/port forwarding - but it's not exactly a game changer.

What would be a game changer, however, is supporting glob-style stings in the launcher, so you don't have to sync the whole log directory (and instead, you can just sync the tensorboard logs) (But that's a lot more complicated than the mostly UI changes that would enable initial S3 support).

**Comment by DonJayamanne** [comment]
Excellent, thanks for explaining the workflow, i'll discuss this with the team.

**Comment by DonJayamanne** [comment]
I'm going to close this issue as there haven't been any upvotes on this feature rqeuiest.
