### ISSUE TITLE
Interrupting a cell execution times out and am forced to restart kernel

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#9111]
## Environment data
-   VS Code Version: 1.65.0-insider (user setup)
-   Commit: eeeab304b9ac777b4a8dddf55f66ffebd9e4e7f2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.2.1010561006
-   Python Extension version (available under the Extensions sidebar): v2022.1.1854775815-dev
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.22000
-   Python and/or Anaconda version: 4.11.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

1. Run a cell
2. While running, click the stop button on the left side of the cell
3. Cell execution stops

## Actual behaviour

The process times out and error message notifies me that I need to restart the kernel.

## Steps to reproduce:

On this notebook: https://github.com/minsa110/titanic/blob/main/titanic.ipynb

While running this cell at the bottom of the notebook (under "Compare Accuracy Scores"):
```
#All Accuracies
print('NB accuracy: {0:.2f}'.format(NB_all_accuracy))

print("Decision Tree:")
print('All attributes: {0:.2f}'.format(tree_all_accuracy))
print('High importance attributes: {0:.2f}'.format(tree_imp_accuracy))

print("Random Forest:")
print('All attributes: {0:.2f}'.format(RF_all_accuracy))
print('High importance attributes: {0:.2f}'.format(RF_imp_accuracy))

print("Neural Network: ")
print('All attributes: {0:.2f}'.format(nn_accuracy))
```

**Comment by greazer** [comment]
@minsa110, please see if this repro's on Jupyter notebook or lab.

**Comment by DonJayamanne** [comment]
I'm removing the `notebook-regression` until we can confirm this is a regression, else it looks as though we're not working on this item when its a high priority item.

**Comment by DonJayamanne** [comment]
@minsa110 pinging as a reminder.

**Comment by greazer** [comment]
@amunger hasn't really been noticing this anymore. Closing. @minsa110, if you still are experiencing, please reopen.

**Comment by rchiodo** [comment]
/verified. Interrupt works fine for me.
