### ISSUE TITLE
Default and/or suggest environment for new notebooks

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#9115]
# Suggestion 1 (previously selected kernel)

Pulled from issue #8530 

From @abatomunkuev

Hello!

I think it would be great to change it to the environment that was previously used by the user and mark it as suggested so that the user doesn't have to specify the environment again.

Maybe for the initial start (very first start), we can ask the user: "what environment would you like to choose". Once the user selects the environment, we can mark it as suggested. From there, every time user creates a new notebook, the environment will belong to the one that the user has chosen previously (marked as "suggested").

# Suggestion 2

If a conda environment is activated in the temrinal, and we launch VS Code from the terminal,
then pre-select the corresponding conda environment in new Notebooks.

## Questions

* Notebooks
	* These new rules could conflict with the active Python interpreter. Assume your active interpreter is PythonA, and based on Suggestion 1/2, the new kernel is CondaA. Would this confuse the user?
* Interactive Window
	* Assume your active interpreter is PythonA, and based on Suggestion 1/2, the new kernel is CondaA. 
	* Now user runs a cell against IW (via code cells in a *.py file), what would they expect?
	* I'd always expect the kernel to point to the active interpreter 

@DonJayamanne what do you think?

**Comment by DonJayamanne** [comment]
will have alook at the vsc api to see if we can do something with the existing stuff.

**Comment by DonJayamanne** [comment]
Closing this as we've decided not to have any sugegstions for new notebooks as the algorithm will never be accurate
Solution: If we're 100% certain about the kernel, then suggest something, else let the user pick one from the kernelpicker
