### ISSUE TITLE
Support presenting notebooks in presentation friendly format like RISE

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#9116]
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/9110

https://github.com/damianavila/RISE

Might be something that we transfer to VS Code core, but wanted to discuss here first. Feels like an interesting feature to have.

**Comment by DonJayamanne** [comment]
i had an extension that i built and demoed last year, something that worked for all notebooks (github issues, we tc).
