### ISSUE TITLE
Latest IPython breaks run by line stepping

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9130]
Install IPython 8.1.0 or greater
Run by line on a cell with more than one line
It won't step through the cell one line at a time. Instead it keeps jumping back to the first line.

**Comment by rchiodo** [comment]
Same thing happens for Debug cell.

**Comment by rchiodo** [comment]
See this issue here:
https://github.com/microsoft/debugpy/issues/854

**Comment by DonJayamanne** [comment]
Closing as fixed, needs to be verified

**Comment by connor4312** [comment]
Verified working in 8.2.0
