### ISSUE TITLE
When using Jupyter (instead of raw kernels) create Kernelspecs in a custom directory

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9141]
Today we create the kernelspec json files in the global known Jupyter kernels directory.
**This causes a few issues:**
* Write access https://github.com/microsoft/vscode-jupyter/issues/5494
* Users edit these kernelspecs (but its not meant for users)
* Maintenance issues
* Code is a little complex (as we need to identify what we created vs what we created as a mapping for custom kernels created by users)
* There have been others

**If we create kernelspecs in a custom directory that user isn't aware of:**
* We know that these are created by us 
* These need not EVER be displayed in the kernel picker
* We can blow these away anytime as we don't have to worry about users editing them

**Solution**
* Create these in a folder specific to the extension version (i.e. within the extension directory)

**Comment by rebornix** [comment]
@DonJayamanne can you please provide detailed steps of what to test?

**Comment by rchiodo** [comment]
I believe this is a dupe of another. I already verified the kernelspecs are created in the temp folder under the extension.

**Comment by rchiodo** [comment]
Duh the dupe is in this issue. THe one I verified earlier:
https://github.com/microsoft/vscode-jupyter/issues/5494
