### ISSUE TITLE
Reconsider how often survey prompt is shown

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-jupyter#9151]
Are surveys really needed. I suggest to reduce how often we prompt people, or what is the percentage of users that we do prompt.
Maybe I am just unlucky but I feel like I get Jupyter / Python prompts all the time.

Feel free to move this to a discussion

fyi @minsa110

**Comment by greazer** [comment]
@isidorn, are you clearing your cache periodically? We shouldn't be asking more than once a year or so.

**Comment by isidorn** [comment]
I do open with new `--user-data-dir` from time to time. So it might be that...
