### ISSUE TITLE
Setting the Default language for a new notebook does not work for most languages

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#9158]
Issue Type: <b>Bug</b>

DIscovered when re-enabling the "DataScience - VSCode Notebook - (Creation Integration)" suite.

The tests were trying to set the default language for cells to Julia or Java, but those don't even show up in the language selection list. Of the languages that are in that list, only javascript and powershell work as expected.

Extension version: 2022.2.1010601211
VS Code version: Code - Insiders 1.65.0-insider (b7730c807c1e0fdacdcc91a854bb963715b2a89b, 2022-02-28T14:37:48.095Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (14.73GB free)|
|Process Argv|--folder-uri file:///c%3A/src/vscode-jupyter --crash-reporter-id 1202dc88-403d-4ebc-8393-af3551a8bd5b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
wslgetstartedc:30421358
vsclayoutctrt:30405800
vscop841:30438915
dsvsc009:30440021
pythonvspyt640:30438691
vsbas813:30436447
vscscmwlcmt:30428973
azactmsalcf:30432849
vscgsvid2:30433758
cppdebug:30437091
dockersurvey3cf:30438169
vsnot107:30443614

```

</details>

**Comment by DonJayamanne** [comment]
Install .NET interactive extension and this functionality works, at least for me.

**Comment by amunger** [comment]
is that expected for our tests? because this also fails on the CI machines

**Comment by DonJayamanne** [comment]
> is that expected for our tests? because this also fails on the CI machines

To me the title isn't accurate, the functionality works (at least for me) and the tests don't work on CI.
You can install the .NET extension and confirm whether this works or not. If it does, then we know its a CI issue

**Comment by amunger** [comment]
The test seems to be using our production API "createBlankNotebook" with a default language that is ignored for most languages.

For me, as for creating a .NET interactive notebook, the cell is initially the expected language (C#), but saving the file causes it to revert to python.

**Comment by DonJayamanne** [comment]
> but saving the file causes it to revert to python.

we have an issue for that

**Comment by amunger** [comment]
The hook for this functionality and the related tests were removed in https://github.com/microsoft/vscode-jupyter/pull/9311, so this is no longer needed
