### ISSUE TITLE
Kernel Display Error when use virtual env

### ISSUE THREAD

**Issue by darouwan** [microsoft/vscode-jupyter#9164]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When I try to use the virtualenv without creating a new kernel, the vscode jupyter switch back to system kernel automatically. But the kernel name displayed in right top corner is still the new virtualenv name rather than old system kernel name. It may confuse users what kernel is being used currently. 

### VS Code Version

Version: 1.64.2 (user setup) Commit: f80445acd5a3dadef24aa209168452a3d97cc326 Date: 2022-02-09T22:02:28.252Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.19042

### Jupyter Extension Version

v2022.1.1301854968

### Jupyter logs

```shell
Info 14:58:11: Interrupt requested file:///c%3A/Users/good/jupyter_workspace/env_check.ipynb
Info 14:58:11: Interrupt requested & sent for c:\Users\good\jupyter_workspace\env_check.ipynb in notebookEditor.
Info 14:58:11: Setting setActiveController for c:\Users\good\jupyter_workspace\env_check.ipynb
Info 14:58:11: Disposing kernel http://127.0.0.1:8888/..python3.python..-m#ipykernel_launcher for notebook c:\Users\good\jupyter_workspace\env_check.ipynb due to selection of another kernel or closing of the notebook
Info 14:58:11: Dispose kernel file:///c%3A/Users/good/jupyter_workspace/env_check.ipynb
Info 14:58:11: KernelProvider switched kernel to id = .jvsc74a57bd0867ccf27c32669b08f7225a9c6486542e56b1278936eccde933e4b7f6991ab54.c:\Users\good\jupyter_workspace\python39_venv_roger\Scripts\python.exe.c:\Users\good\jupyter_workspace\python39_venv_roger\Scripts\python.exe.-m#ipykernel_launcher
Info 14:58:11: Starting Notebook in kernel.ts id = .jvsc74a57bd0867ccf27c32669b08f7225a9c6486542e56b1278936eccde933e4b7f6991ab54.c:\Users\good\jupyter_workspace\python39_venv_roger\Scripts\python.exe.c:\Users\good\jupyter_workspace\python39_venv_roger\Scripts\python.exe.-m#ipykernel_launcher
Info 14:58:11: Creating raw notebook for c:\Users\good\jupyter_workspace\env_check.ipynb
Info 14:58:11: Getting preferred kernel for c:\Users\good\jupyter_workspace\env_check.ipynb
Info 14:58:11: Computing working directory c:\Users\good\jupyter_workspace\env_check.ipynb
Info 14:58:11: Starting raw kernel python39_venv_roger (Python 3.9.10)
Info 14:58:11: installMissingDependencies c:\Users\good\jupyter_workspace\python39_venv_roger\Scripts\python.exe
Info 14:58:11: IPykernel found previously in this environment c:\Users\good\jupyter_workspace\python39_venv_roger\Scripts\python.exe
Info 14:58:11: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
Info 14:58:11: No custom variables for Kernel as interpreter is not conda, but is Venv
Info 14:58:11: Process Execution: > c:\Users\good\jupyter_workspace\python39_venv_roger\Scripts\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> c:\Users\good\jupyter_workspace\python39_venv_roger\Scripts\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 14:58:11: Creating daemon process for c:\Users\good\jupyter_workspace\python39_venv_roger\Scripts\python.exe with env variables count 69
Info 14:58:11: Process Execution: > c:\Users\good\jupyter_workspace\python39_venv_roger\Scripts\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 10364
> c:\Users\good\jupyter_workspace\python39_venv_roger\Scripts\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 10364
Info 14:58:11: get interrupthandle daemon
Info 14:58:11: Process Execution: > c:\Users\good\jupyter_workspace\python39_venv_roger\Scripts\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"e268882b-9091-40ae-a6b8-f18f1bda0185" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\good27~1\AppData\Local\Temp\tmp-10364kElcgDNd255L.json
> c:\Users\good\jupyter_workspace\python39_venv_roger\Scripts\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"e268882b-9091-40ae-a6b8-f18f1bda0185" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\good27~1\AppData\Local\Temp\tmp-10364kElcgDNd255L.json
Info 14:58:11: Process Execution: cwd: c:\Users\good\jupyter_workspace
cwd: c:\Users\good\jupyter_workspace
Info 14:58:11: ipykernel version 6.9.1 for c:\Users\good\jupyter_workspace\python39_venv_roger\Scripts\python.exe
Info 14:58:11: ipykernel location c:\Users\good\jupyter_workspace\python39_venv_roger\lib\site-packages\ipykernel\__init__.py for c:\Users\good\jupyter_workspace\python39_venv_roger\Scripts\python.exe
Warn 14:58:12: StdErr from Kernel Process c:\Users\good\jupyter_workspace\python39_venv_roger\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
c:\Users\good\jupyter_workspace\python39_venv_roger\lib\site-packages\traitlets\traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'e268882b-9091-40ae-a6b8-f18f1bda0185' instead of 'b"e268882b-9091-40ae-a6b8-f18f1bda0185"'.
  warn(

Info 14:58:12: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing C:\Users\good27~1\AppData\Local\Temp\tmp-10364kElcgDNd255L.json

Info 14:58:12: Raw session started and connected
Started kernel python39_venv_roger (Python 3.9.10)
Info 14:58:12: Finished connecting 28fc8326-6fa5-47b2-b0ce-9401fa3d1905
Info 14:58:12: Executing silently Code (idle) = import sys\nprint(sys.executable)
Info 14:58:12: Executing silently Code (completed) = import sys\nprint(sys.executable)
Info 14:58:12: UpdateWorkingDirectoryAndPath in Kernel
Info 14:58:12: Executing silently Code (idle) = import site\nsite.addsitedir(site.getusersitepackages())\nimport os\nimport sys\n%cd "c:\Users\good27620
Info 14:58:12: Executing silently Code (completed) = import site\nsite.addsitedir(site.getusersitepackages())\nimport os\nimport sys\n%cd "c:\Users\good27620
Info 14:58:12: Waiting for idle on (kernel): b6e468cf-126f-4f3b-8d88-49a2925ced06 -> idle
Info 14:58:12: Finished waiting for idle on (kernel): b6e468cf-126f-4f3b-8d88-49a2925ced06 -> idle
Info 14:58:13: Creating server with settings : {"baseUrl":"http://127.0.0.1:8888/","appUrl":"","wsUrl":"ws://127.0.0.1:8888/","token":"","init":{"cache":"no-store","credentials":"same-origin","headers":{"Cookie":"_xsrf=2|9d3b1411|033aeb1fa0c6945a63d9535d1cbbaf13|1646112619; username-127-0-0-1-8888=\"2|1:0|10:1646112619|23:username-127-0-0-1-8888|44:YTNiODEyMTg2N2Q1NDE2ZjhkMjgzMTNkOTFkMjAxZTE=|cd2fe41abc1e7e5d19581a4ca78dc909ccfaaf24a7b831c4e520e2a7eaadf3ff\"; expires=Thu, 31 Mar 2022 05:30:19 GMT; HttpOnly; Path=/","X-XSRFToken":"2|9d3b1411|033aeb1fa0c6945a63d9535d1cbbaf13|1646112619"}}}
Info 14:58:13: Disposing session manager
Info 14:58:13: SessionManager - dispose contents manager
Info 14:58:13: ShutdownSessionAndConnection - dispose session manager
Info 14:58:13: Finished disposing jupyter session manager
```

### Running Jupyter locally or remotely?

Remote

**Comment by rchiodo** [comment]
Thanks for the bug.

I'm not sure why you're saying this?

> When I try to use the virtualenv without creating a new kernel, the vscode jupyter switch back to system kernel automatically

From the look of your log it is running the virtual environment. It starts it with this line here:

```
c:\Users\good\jupyter_workspace\python39_venv_roger\Scripts\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"e268882b-9091-40ae-a6b8-f18f1bda0185" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\good27~1\AppData\Local\Temp\tmp-10364kElcgDNd255L.json
```

**Comment by darouwan** [comment]
The log I paste here is based on the virtualenv that is not clean. I will reproduce the error again and I will post it later.

**Comment by darouwan** [comment]
Here is how I reproduce the error:
1. I create a new virtualenv with `virtualenv python3_test`
2. Open the vscode, select the new kernel "python3_test"
3. Run the jupyter notebook cell
4. The vscode prompts to install the ipykernel, and click the install button. 
5. Re-run the  jupyter notebook cell

In the cell, I import tensorflow and pytorch successfully. But the "python3_test" should be a new environment, and neither tensorflow nor pytorch lib is installed. The right top corner shows I am using the "python3_test". 

The logs:
`Info 12:16:40: Restart requested file:///c%3A/Users/user1/jupyter_workspace/env_check.ipynb
Info 12:16:40: Restart kernel execution
Info 12:16:40: Cancel pending cells
Info 12:16:40: Starting raw kernel venv-python3-test (Python 3.9.10) for interpreter c:\Users\user1\jupyter_workspace\python3_test\Scripts\python.exe
Info 12:16:40: installMissingDependencies c:\Users\user1\jupyter_workspace\python3_test\Scripts\python.exe
Info 12:16:40: IPyKernel found previously in this environment c:\Users\user1\jupyter_workspace\python3_test\Scripts\python.exe
Info 12:16:40: Restarting 8be4ef7f-5509-4535-9f67-3beefc4365c7
Info 12:16:40: Kernel launching with ports 9010,9011,9012,9013,9014. Start port is 9000
Info 12:16:40: Process Execution: > c:\Users\user1\jupyter_workspace\python3_test\Scripts\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> c:\Users\user1\jupyter_workspace\python3_test\Scripts\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 12:16:40: Adding env Variable PYTHONNOUSERSITE to c:\Users\user1\jupyter_workspace\python3_test\Scripts\python.exe
Info 12:16:40: Creating daemon process for c:\Users\user1\jupyter_workspace\python3_test\Scripts\python.exe with env variables count 67
Info 12:16:40: Process Execution: > c:\Users\user1\jupyter_workspace\python3_test\Scripts\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 32568
> c:\Users\user1\jupyter_workspace\python3_test\Scripts\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 32568
Info 12:16:41: get interrupthandle daemon
Info 12:16:41: Process Execution: > c:\Users\user1\jupyter_workspace\python3_test\Scripts\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9013 --control=9011 --hb=9010 --Session.signature_scheme="hmac-sha256" --Session.key=b"9b7ec818-4b15-4c40-850c-c562a098ac4a" --shell=9012 --transport="tcp" --iopub=9014 --f=C:\Users\user127~1\AppData\Local\Temp\tmp-32568Czx5CIOTEU0J.json
> c:\Users\user1\jupyter_workspace\python3_test\Scripts\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9013 --control=9011 --hb=9010 --Session.signature_scheme="hmac-sha256" --Session.key=b"9b7ec818-4b15-4c40-850c-c562a098ac4a" --shell=9012 --transport="tcp" --iopub=9014 --f=C:\Users\user127~1\AppData\Local\Temp\tmp-32568Czx5CIOTEU0J.json
Info 12:16:41: Process Execution: cwd: c:\Users\user1\jupyter_workspace
cwd: c:\Users\user1\jupyter_workspace
Info 12:16:41: ipykernel version 6.9.1 for c:\Users\user1\jupyter_workspace\python3_test\Scripts\python.exe
Info 12:16:41: ipykernel location c:\Users\user1\jupyter_workspace\python3_test\lib\site-packages\ipykernel\__init__.py for c:\Users\user1\jupyter_workspace\python3_test\Scripts\python.exe
Warn 12:16:42: StdErr from Kernel Process c:\Users\user1\jupyter_workspace\python3_test\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
c:\Users\user1\jupyter_workspace\python3_test\lib\site-packages\traitlets\traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '9b7ec818-4b15-4c40-850c-c562a098ac4a' instead of 'b"9b7ec818-4b15-4c40-850c-c562a098ac4a"'.
  warn(

Info 12:16:42: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing C:\Users\user127~1\AppData\Local\Temp\tmp-32568Czx5CIOTEU0J.json

Info 12:16:42: Got new session d0a8718d-6228-4257-b098-da1f2da5c72a
Info 12:16:42: Started new restart session
Info 12:16:42: Dispose Kernel process
Info 12:16:42: kill daemon
Info 12:16:42: Executing silently Code (idle) = import sys\nprint(sys.executable)
Info 12:16:42: Executing silently Code (completed) = import sys\nprint(sys.executable)
Info 12:16:42: UpdateWorkingDirectoryAndPath in Kernel
Info 12:16:42: Executing silently Code (idle) = import site\nsite.addsitedir(site.getusersitepackages())\nimport os\nimport sys\n%cd "c:\Users\user127620
Info 12:16:42: Executing silently Code (completed) = import site\nsite.addsitedir(site.getusersitepackages())\nimport os\nimport sys\n%cd "c:\Users\user127620
Info 12:16:42: Waiting for idle on (kernel): d0a8718d-6228-4257-b098-da1f2da5c72a -> idle
Info 12:16:42: Finished waiting for idle on (kernel): d0a8718d-6228-4257-b098-da1f2da5c72a -> idle
Info 12:16:47: Execute Cells request 0
Info 12:16:47: Execute Cell 0 c:\Users\user1\jupyter_workspace\env_check.ipynb
Info 12:16:51: Cell 0 executed with state Success
`

**Comment by DonJayamanne** [comment]
@darouwan 
Please could you run the following code in the cell
```python
import tensorflow
print(tensorflow.__file__)
import pytorch
print(pytorch.__file__)
```

**Comment by rchiodo** [comment]
Closing as fixed for now.
