### ISSUE TITLE
Refactor ErrorHandler and connections

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9170]
There are some inconsistencies:

- Error handler shows UI but then doesn't stick errors into cells. That's handled by IW and Notebooks. This makes it seem like the error handler maybe shouldn't show UI? Instead it just translates errors into actions to take?
- The new 'connectToKernel' method could be put into a class, like 'KernelConnector' or something. 
- Other UI percolates through into other locations. Can we isolate this at a higher level? Do we want to?

**Comment by DonJayamanne** [comment]
I'm picking this as we have regressed in functionality and introduced a few other bugs.
I.e. this has to be done in March and is not a debt.

**Comment by DonJayamanne** [comment]
Side effects https://github.com/microsoft/vscode-jupyter/issues/9271, https://github.com/microsoft/vscode-jupyter/issues/9269

**Comment by DonJayamanne** [comment]
Right now, I'm thinking of focusing on fixing this regression and perhaps later focus on re-factoring.
i.e., somethings needs to be done to fix the underlying problems and re-factoring could be done later after we fix the issues,

**Comment by rchiodo** [comment]
> Going to get connectToKernel make use of errorHandler so that error handler is used everywhere and displays errors as well in cells & messageboxes.

I don't think we should do this. Handling of UI display is different between interactive and notebooks. I think it (UI display) should be handled by each view type. ErrorHandler or whatever we call the new class could certainly consolidate what the error is, but I don't think it should be displaying anything.

**Comment by DonJayamanne** [comment]
> I don't think we should do this. Handling of UI display is different between interactive and notebooks. 

Agreed, I haven't made that change.

I think we can close this issue, but lets discuss tomorrow and validate whether we're in agreement about the current approach.

**Comment by DonJayamanne** [comment]
Closing as done
