### ISSUE TITLE
Interactive cell input code always collapsed

### ISSUE THREAD

**Issue by romatt** [microsoft/vscode-jupyter#9183]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

After upgrading Jupyter from v2021.8. to v2021.11. cell input code is always collapsed when executing code interactively. It seems like the relevant setting is no longer respected:
`"jupyter.collapseCellInputCodeByDefault": false,`

![jupyter_code_collapse_old](https://user-images.githubusercontent.com/77632960/156365414-d119e39a-17ce-482d-ad45-db24e21b96ff.png)
![jupyter_code_collapse_new](https://user-images.githubusercontent.com/77632960/156365542-57129d8d-854e-489d-835f-1d5452742259.png)

I observed the same behavior on 3 different systems and I just reproduced it again simply be upgrading the Jupyter extension.

### VS Code Version

1.63.2

### Jupyter Extension Version

v2021.11.1001550889

### Coding Language and Runtime Version

Python v3.8.5

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment]
Sorry this setting has moved. Interactive window is now owned by VS code core and they have their own setting for this. However you'll have to update to the latest VS code to use it:

![image](https://user-images.githubusercontent.com/19672699/156413379-b164a2b1-3941-47b4-9d44-9c9456d20207.png)
