### ISSUE TITLE
Our plot settings should only append SVG if needed. Not mess with existing figure_formats settings

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#9191]
Our SVG configuration code should not replace user defaults. It should just append on SVG if requests.

**Comment by DonJayamanne** [comment]
I thought this was done, I do remember discussing this

**Comment by IanMatthewHuff** [comment]
@DonJayamanne I thought so as well. Was in my head for debt week, so I went to check and I still see the issue. getMatplotLibInitializeCode looks to directly set figure format to PNG or to PNG + SVG. Unless I'm really missing something.

**Comment by DonJayamanne** [comment]
yeah, perhaps it never got done because we didn't create an issues, ie fell through the cracks

**Comment by IanMatthewHuff** [comment]
Validation: 
https://jupyter-notebook.readthedocs.io/en/stable/config.html

Create a jupyter configuration file. Change c.InlineBackend.figure_formats to something like ['jpeg']. When you start up a notebook check that the figure_formats is still jpeg and not changed to png.
