### ISSUE TITLE
test "!python should point to the Environment" is failing

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#9193]
possibly need to clear the workspace interpreter setting

## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Taking this on, as I added this recently

**Comment by DonJayamanne** [comment]
Caused by upstream issue https://github.com/microsoft/vscode/issues/144338

**Comment by DonJayamanne** [comment]
Oh seems to be a different error, when I looked at the logs, the cell was not running to completion because VSCode had crashed during cell execution.
This seems to be different

**Comment by DonJayamanne** [comment]
Looks like Python code is crashing with the error `shell not found` when using `zmq` related code.
I think we can just dump this test.
We have another test that ensures the first item in sys.path points to the location where the executable is located.

**Comment by amunger** [comment]
The test is still failing, even on the PR that was intended to fix it

**Comment by DonJayamanne** [comment]
> even on the PR that was intended to fix it

please could you point to a ci run so i can have a look

**Comment by amunger** [comment]
https://github.com/microsoft/vscode-jupyter/runs/5489090369?check_suite_focus=true
