### ISSUE TITLE
Tolerance of ipython magics in source code cells

### ISSUE THREAD

**Issue by robince** [microsoft/vscode-jupyter#9202]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I would like to be able to use ipython line magics (`%matplotlob`, `%run`, `%connect_info` and others) and cell magics (`%%time`,`%%timeit`) in cell mode Python scripts without having errors noted in the interface (Pylance gives "Expected expression") error:
<img width="977" alt="Screenshot 2022-03-03 at 08 44 12" src="https://user-images.githubusercontent.com/63155/156528725-00e8fe2b-4519-48fd-8497-d11bad4152ee.png">
 
This is the same as issue  #1497 which is now closed. 
"Closing for now as the workaround described above should work."
The workaround proposed there is to comment the magics with `#!`.
This doesn't work for me. If I "Run Cell" on a cell with a `#!%` the line just goes through as a comment and the magic is not run (see screenshot). 
<img width="1413" alt="Screenshot 2022-03-03 at 08 31 22" src="https://user-images.githubusercontent.com/63155/156527981-157a2729-86b3-40a2-9594-3df0e58b1ae3.png">

My understanding from #1497 is that the shebang should be stripped from the magic when it is run in the interactive window, but this isn't happening for me. This would work for both line and cell magics. 

A workaround for line magics is to use the functional form:
```
from IPython import get_ipython
ip = get_ipython()
ip.run_line_magic('connect_info','')
```
But I'm not sure how to do this with a cell magic: `run_cell_magic` needs the cell content as the third argument. 

### VS Code Version

Version: 1.64.2 Commit: f80445acd5a3dadef24aa209168452a3d97cc326

### Jupyter Extension Version

v2022.1.1301854968

### Jupyter logs

```shell
#%%
#!%connect_info
```

### Language Extension Version (if applicable)

Python extension v2022.0.1814523869

### Running Jupyter locally or remotely?

N/A or Not sure

### Related Issues

[Pylance #575](https://github.com/microsoft/pylance-release/issues/575)
[VScode-python #17058](https://github.com/microsoft/vscode-python/issues/17058)
[VScode-python #17057](https://github.com/microsoft/vscode-python/issues/17057)
[VScode-jupyter #3263](https://github.com/microsoft/vscode-jupyter/issues/3263)

**Comment by IanMatthewHuff** [comment]
Question, do you have Jupyter: Magic Commands as Comments set? That's the setting that should allow you to use it as a comment and have the # stripped when it's sent to the interactive window.

**Comment by robince** [comment]
No, I didn't - I hadn't seen that option documented or mentioned in those tickets. With that enabled it works fine. Thanks very much.
