### ISSUE TITLE
Enable queries on test run history

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#9218]
I'd like to be able to easily check the run history of a test or general trends in test runs/pass rate.

Some cases I can think of:
- I can easily check if a "flaky test" issue is still relevant. There are plenty of old ones that could probably just be closed.
- If a test fails in CI, I can go check if that test has already been failing before I made my change.
- When troubleshooting a flaky test, I can get a better idea of when it started failing to track down relevant changes

Notes:
- The CI system doesn't send any telemetry, so we currently can't just emit our normal telemetry events
- The "publish test results" step in the github action sounds promising, but is currently failing for auth reasons

**Comment by DonJayamanne** [comment]
Even if we had fixed the auth issue, you won't be able to query the failures of older tests.
Github doesn't store such information, I think we'd need to use Azure Pipelines or the like.
We could try pushing the results to azure pipelines in some weird n funky way.

However I think we should just fix the flaky tests.

**Comment by amunger** [comment]
`vscode-jupyter\.vscode\notebooks\CITestResults.ipynb` is published and ready for usage.
Also relies on the Github action `Aggregate Test Results` which consolidates results into daily chunks
