### ISSUE TITLE
Run by Line not available when switching from .NET Interactive Nb 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#9222]
## Environment data

-   VS Code version: 1.65.0 
-   Jupyter Extension version (available under the Extensions sidebar): v2022.2.1010630101
-   Python Extension version (available under the Extensions sidebar): v2022.2.1924087327

## Steps to reproduce:

1. Create .NET Interactive notebook through command palette and save (either through jupyter command or .net command, doesn't matter) 
2. Create new notebook through Jupyter command palette (kernel should automatically be set to .NET interactive) 
3. Switch kernel to python kernel

I havent tried this out with other kernels but since the last kernel used is remembered, when creating the new notebook through the command palette, I believe this would happen from using any other notebook like the Julia kernel...

Edit: *Reloading does bring the run by line icon back

## Actual behaviour

Run by line not available

## Expected behavior 

Run by line to be available

**Comment by IanMatthewHuff** [comment]
Reproed. Suspicion is the context keys added to associate toolbar actions with controller types.

**Comment by roblourens** [comment]
Seems like `jupyter.ispythonnotebook` will not be updated on kernel changes
