### ISSUE TITLE
No option to "import Jupyter notebook" in file-explorer context menu

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#9252]
Pretty sure we used to have a context menu item when the user right clicked on an ipynb file in the VS Code file explorer to "import Jupyter Notebook as Python script". Seems to have gotten lost (or did we somehow decide to remove it?)

**Comment by greazer** [comment]
Should rename the menu item too to be more specific about what it's doing.

**Comment by IanMatthewHuff** [comment]
Verification. ipynb files in Explorer should have a Right Click option on them to import them as Scripts. This command had gone missing for a bit and is now restored.
