### ISSUE TITLE
Issues with activation of Conda environments

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9254]
Python extension seems to be running into quite a lot of issues with `conda run`,
We've adopted `conda run`, just as they have to get environment variables.
I think we'll need to try both `conda run` and the `traditional way of activating conda` to ensure things work.

Unlike Python extension we cannot wait nor rely on `conda run` fixes to get pushed to end users.
Failure to activate conda results in failure to run cells or failure to import packages, both of which are golden scenarios.

**This issue is a placeholder for debt week,** 
* Ensure we look at the issues related to `conda run`
* How does this impact Jupyter extension
* Can we try both the old and new apparoach in tandem to get the env variables?
	* Remember, conda activation crashes when multiple processes attempt to activate simultaneously
* Do we have telemetry to track if the existing code works today
	* Do we have telemetry to check if the new approach is worse than the old (if so, then we'd be regressing & users would be running into a lot of issues)
* This feels like a good candidate for kernel doctor
	* Users run into issues with conda

**Comment by greazer** [comment]
Would be good to do some investigation here prior to debt week.

**Comment by DonJayamanne** [comment]
Fixed in https://github.com/microsoft/vscode-jupyter/pull/9377
