### ISSUE TITLE
IW no longer snaps to bottom on running a cell

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-jupyter#9259]
Running this cell a few times shows that the IW needs manual scrolling to bottom to show latest output:

```py
# %%
for i in range(100):
    print(i)
```

Temporary workaround is to set

```json5
// Automatically scroll the interactive window to show the output of the last statement executed.
// If false, the interactive window will only automatically scroll if the bottom of the prior cell is visible.
"jupyter.alwaysScrollOnNewCell": true,
```

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, this could be a regression at our end.

**Comment by rchiodo** [comment]
We should be revealing the cell if it was at the bottom. Might be the change to allow scrolling past the bottom that broke this? Although I don't have that ability in the IW and I can repro.

**Comment by crsqq** [comment]
There is a (I think) related issue with the IW: the most recent output from commands entered through the interactive prompt is not shown if the windows is filled by previous output.

E.g. in this screencast: the output of `i`, `i*2`, `i/0` is not shown, manual scrolling is thus necessary.



https://user-images.githubusercontent.com/4514040/157456743-2bd74f44-8bf7-4473-b387-0d3b23b4f7c9.mp4



Also happens with the changes from #9299 applied and `jupyter.alwaysScrollOnNewCell` does not change the behavior

Steps to reproduce:
1) fill IW output with
```
# %%
for i in range(100):
    print(i)
```
2) type something in the interactive prompt

**Comment by rzhao271** [comment]
It seems to snap to the end of the cell rather than the end of the entire output.
![Screencap](https://user-images.githubusercontent.com/7199958/160012503-2060434a-b079-45da-bb58-c145f374b84e.gif)

**Comment by rchiodo** [comment]
The output not scrolling is actually a separate issue: #8426

**Comment by Vincent0706** [comment]
this bug seem happened again in v2022.4.1000912146
