### ISSUE TITLE
Executing notebook cell in the web leads to install kernels

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-jupyter#9263]
- Go to vscode.dev
- Open an `.ipynb` notebook
- Try to execute a code cell
- Prompted to `Install kernels from the marketplace`
- Select prompt, Extensions view populates with `@id:ms-toolsai.jupyter` and shows the Jupyter extension, which cannot be installed in the web
- User left wondering if/how they can install kernels right now

![image](https://user-images.githubusercontent.com/25310137/157111122-ef344a1e-434b-4a33-b063-f37449b814d9.png)

![image](https://user-images.githubusercontent.com/25310137/157111257-bdefd33e-9102-40be-aa2c-583923beb6e4.png)

Should we change/disable the `Install kernels from the marketplace` flow, as it leads to user confusion over what currently can be performed in vscode.dev?

Related to https://github.com/microsoft/vscode-jupyter/issues/8664

**Comment by greazer** [comment]
This workflow is being discussed in this iteration. So closing this here.

**Comment by EklavyaFCB** [comment]
I have this issue ! Why can't I just choose the environment and execute the cell ?
