### ISSUE TITLE
Installing ipykernel will come up twice if kernel is started quick enough

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9267]
Refactor of the error handling caused this. The auto start causes the problem.

**Comment by DonJayamanne** [comment]
Yikes.
I'll take a look.

**Comment by DonJayamanne** [comment]
@rchiodo in your case were you using with or without zmq?

**Comment by DonJayamanne** [comment]
Been unable to repro this and don't see how we can end up with multiple kernel startups or multiple popups.
@rchiodo please could you merge the latest stuff from main branch and test this out once again.
thanks

**Comment by rchiodo** [comment]
Repros for me constantly. Maybe I should fix this one if you can't repro it?

**Comment by rchiodo** [comment]
Steps to repro:
1. Create empty venv
2. Open python file with a cell
3. Set interpreter to empty venv
4. Restart VS code
5. Click Run Cell
6. Hit cancel on the 'Install IPyKernel' that comes up.

**Comment by DonJayamanne** [comment]
I've tried this in Windows and even WSL, and still unable to repro this issue.
I'm on the latest jupyter pre-release and trying this in VS Code insiders.

> Maybe I should fix this one if you can't repro it?

Yes, please do, or if you're busy or don't have the time, please point to the faulty code and I can take a look.

**Comment by DonJayamanne** [comment]
@rchiodo  Ok i'm sorry, I was continously testing with a Notebook and not IW.

**Comment by roblourens** [comment]
How do I repro the issue?

**Comment by rchiodo** [comment]
Steps to repro comment has it:
https://github.com/microsoft/vscode-jupyter/issues/9267#issuecomment-1067275177

Basically create an empty python environment, pick it as the active interpreter for a python file, run a cell from said file, and click cancel.

**Comment by roblourens** [comment]
Oh sorry missed that, how do I disable zmq though?

**Comment by rchiodo** [comment]
Top secret setting:
```
"jupyter.disableZMQSupport": true
```

This forces us to use jupyter to run kernels (instead of us doing it directly)
