### ISSUE TITLE
Restore error message when not installing IPYKernel or Jupyter Dependencies

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9269]
The error message displayed when users cancel the prompt to install ipykernel has changed (the new error is as per screenshot).

Previously we'd display a message indicating the fact that the cell could not be run as ipykernle is not installed.
Yes, the user hit cancel here, but they don't know what ipykernle prompt is, and we chose to display the detailed error message in the output as well (asking with instructions to unblock themselves)

I think we should bring back the old error message.

![image](https://user-images.githubusercontent.com/1948812/157150221-a4818ca3-36f0-4ce9-af96-cb4827bf13b7.png)

**Comment by DonJayamanne** [comment]
Same applies when Jupyter packages are missing (ie. we are no longer displaying messages on how to install jupyter notebook packages)

**Comment by rchiodo** [comment]
This should simply be a matter of not throwing an error when canceled. Instead just rethrow the original error.

**Comment by rchiodo** [comment]
Not sure if we need to show the user they canceled or not. I can see it both ways. Interactive window shows the state of the error after it's done. The ipykernel error is true, but they not remember they canceled the install.
