### ISSUE TITLE
Function decorators not included in code when running with shift+enter

### ISSUE THREAD

**Issue by tlebryk** [microsoft/vscode-jupyter#9291]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I am attempting to add a language component (i.e. a custom pipeline) for a Spacy model. These components utilize a specific decorator documented [here](https://spacy.io/api/language#component). 

If you try and run a decorated function in a cell, the cell does not recognize your decorator. You can work around it by expanding the selection to arbitrary code above the decorator or copy and pasting the function into the code cell and running the entire cell and not just the selection.

However, ideally you would be able to select a function and execute it along with the decorator. 

See the below picture for what happens when you try to execute a selected decorated function and how the decorator is simply ignored. 
<img width="216" alt="image" src="https://user-images.githubusercontent.com/43556997/157299827-965957f9-7d43-48d2-819e-455fa497302a.png">

### VS Code Version

Version: 1.64.2 (user setup) Commit: f80445acd5a3dadef24aa209168452a3d97cc326 Date: 2022-02-09T22:02:28.252Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.22000

### Jupyter Extension Version

v2022.1.1301854968

### Coding Language and Runtime Version

Python 3.9.2

### Language Extension Version (if applicable)

v2022.2.192408732

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment]
Thanks for the bug. I'm not sure I understand what the failure is.

I did this as an example:

```python
# %%
import spacy
from spacy.language import Language
from spacy.lang.en import English

#%%
@Language.component("info_component")
def my_component(doc):
    print(f"After tokenization, this doc has {len(doc)} tokens.")
    print("The part-of-speech tags are:", [token.pos_ for token in doc])
    if len(doc) < 10:
        print("This is a pretty short document.")
    return doc

#%%
nlp = English()

#%%
nlp.add_pipe("info_component", name="print_info", last=True)
print(nlp.pipe_names)  # ['tagger', 'parser', 'ner', 'print_info']
doc = nlp("This is a sentence.")
# %%
```

And the decorator was applied correctly. My output was like so:

![image](https://user-images.githubusercontent.com/19672699/157310706-069d0489-577a-4d71-81c7-75e8481aaa92.png)

What happens if you do the same thing?

**Comment by tlebryk** [comment]
When I do what you say, it works perfectly. It's running using selection which causes an issue: try selecting just:
```
@Language.component("info_component")
def my_component(doc):
    print(f"After tokenization, this doc has {len(doc)} tokens.")
    print("The part-of-speech tags are:", [token.pos_ for token in doc])
    if len(doc) < 10:
        print("This is a pretty short document.")
    return doc
```
and "run selection in interactive window" (usually shift+enter). The generated interactive cell should be missing the decorator. If I run from the start like using run with selection I get the following: 
![image](https://user-images.githubusercontent.com/43556997/157352290-3217b8f8-c325-4759-99d2-f8750c4c50d1.png)

Again, not a huge bug because there are workarounds, but it seems confusing that the selection tool wouldn't accommodate decorators.

**Comment by rchiodo** [comment]
Ah thanks. That makes more sense. Yeah that's a bug. The selection should include the decorator.

**Comment by orcahmlee** [comment]
I got a similar situation. Here is my enviroment.

---

## VS Code Version
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:20.994Z (3 days ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 21.3.0

## Jupyter Extension Version
v2022.3.1000901801

## Jupyter logs
None

## Coding Language and Runtime Version
Python 3.8.13

## Language Extension Version (if applicable)
Python v2022.4.1
Pylance v2022.4.1

## Anaconda Version (if applicable)
conda 4.10.1

## Running Jupyter locally or remotely?
Local

**Comment by GaryLiuTelus** [comment]
Ditto, same error here

**Comment by amunger** [comment]
tracking in https://github.com/microsoft/vscode-jupyter/issues/13027
