### ISSUE TITLE
IPyaladin widget does not work in VSCode

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9292]
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/9290

<div type='discussions-op-text'>

<sup>Originally posted by **JosephKarpinski** March  8, 2022</sup>
Hi, 

I’m lost on this.
This jupyter notebook works fine in Jupyter but not in Visual Studio.
Nothing is displayed. Attaching error message.

<img width="526" alt="D1985D1C-B788-4F0D-862B-4CC70347281D" src="https://user-images.githubusercontent.com/37123616/157284667-2251356a-10af-4f91-82f0-f764ca382fca.png">
<img width="918" alt="55C0516D-26D4-4594-B4D9-DE69CB479B6D" src="https://user-images.githubusercontent.com/37123616/157284669-0420abbd-e542-482e-b733-93e37cd56de2.png">
<img width="526" alt="21E98D11-AF81-4277-92AA-AC6078FF55ED" src="https://user-images.githubusercontent.com/37123616/157284671-fadf5af2-977a-44ab-ac5f-ec25a1cc5f25.png">
<img width="253" alt="3ABC4FB5-B3D4-41F0-A18D-222B20161A3D" src="https://user-images.githubusercontent.com/37123616/157284672-8e9ebea1-2b01-4289-8cda-e779c52eb723.png">
<img width="1091" alt="6EA74317-BC6A-45DC-A4F9-BC831910A28A" src="https://user-images.githubusercontent.com/37123616/157284674-0c9058da-312f-4051-ad8b-02fe58b98bc1.png">
</div>

**Comment by rchiodo** [comment]
Not sure what we can do about this. This error here says it all:

![image](https://user-images.githubusercontent.com/19672699/157345791-a8396c79-198a-405e-8eea-bfdb4f22f4bd.png)

This means the ipyaladin widget does not ship the necessary javascript for us to support it.

Checking on jsdelivr.com, there is no version supported:

![image](https://user-images.githubusercontent.com/19672699/157345894-43a1ee6c-a49c-4152-9f21-f12e0ebe8b9a.png)

**Comment by rchiodo** [comment]
> Hmm, not sure why Jupyter has no issues running the widget.

Jupyter loads the js file from the python environment. We can't do that because the JS file in the environment almost always relies on jupyter parts already being loaded (which are not part of VS code). So instead we have to load it from a CDN where most widgets publish a non jupyter widget implementation.

> Looking in a different location for the associated Java script?

Yes jupyter loads from the nb_extensions folder. Which most of the time doesn't work for us.

> Other widgets like pyESASky generate a similar error message but work.
We attempt to load them from the nb_extensions folder. Sometimes they don't use jupyter specific libraries.

> Jupyter was replaced in Visual Studio with an extension.
Not sure what you mean by this?

> I wonder if the widget would run fine in an older version of Visual Studio.
It should have the same loading code. We haven't changed this since we implemented support for IPywidgets.

**Comment by JosephKarpinski** [comment]
Well, I sort of understand where Visual Studio is looking:

https://github-wiki-see.page/m/microsoft/vscode-jupyter/wiki/IPyWidget-Support-in-VS-Code-Python

![11BA2942-0B83-4F4C-A2D3-BAADCE0E3842](https://user-images.githubusercontent.com/37123616/157506930-ddf5505b-210c-4a6a-8133-b4444a0e7a38.jpeg)

**Comment by JosephKarpinski** [comment]
My guess is that Jupyter looks in a different location that what Visual Studio uses.

Regarding “ Jupyter was replaced in Visual Studio with an extension.”
Something like a year ago, Visual Studio started generating warning messages that Jupyter was 
not going to be supported natively. We had to select a Visual Studio extension to run Jupyter notebooks in Visual Studio. I think it was something like PyLance?

**Comment by rchiodo** [comment]
You may be referring to when we moved the notebook UI implementation into the VS code core. Happened about a year ago. The IPywidget implementation was the same.

**Comment by JosephKarpinski** [comment]
So maybe PyLance is using

[jsDelivr](https://jsdelivr.com/)
[UNPKG](https://unpkg/)

and Jupyter uses a different set of locations?

**Comment by JosephKarpinski** [comment]
What I really want is to run all my Jupyter Notebooks in Visual Studio.
Not some in Visual Studio and some in Jupyter.
Still looking for how Jupyter resolves this widget correctly….

**Comment by rchiodo** [comment]
Pylance is not involved at all here. Pylance is for python intellisense. It doesn't handle Jupyter execution.

Jupyter looks in the nb_extensions folder for the python environment.

We use the CDN locations 

That wiki you pointed is the link in this error here: 
![image](https://user-images.githubusercontent.com/19672699/157509532-b6a1847d-593d-4137-929c-525508879651.png)

Your best resolution to get ipyaladin to work in VS code would be to contact ipyaladin and have them publish their js files on npm. When they do that, they should follow the directions jupyter created here:
https://github.com/jupyter-widgets/widget-cookiecutter

**Comment by JosephKarpinski** [comment]
Ok, I did open an issue on GitHub ipyaladin quite a while ago (months).
They haven’t responded at all.

I guess for now we should close this problem record.
I’ll run ipyaladin notebooks in Jupyter.

Thanks for looking into this.

Best Regards…

**Comment by JosephKarpinski** [comment]
![4AD8966E-7D13-4A5C-B5FE-2C962FD404E0](https://user-images.githubusercontent.com/37123616/157514055-f17649c9-4e8a-4955-b3da-d4f8cbf6bf02.jpeg)

**Comment by DonJayamanne** [comment]
I have this working, 

![image](https://user-images.githubusercontent.com/1948812/157618593-6d1b9053-67d0-4e74-be93-e44f75cc987d.png)
