### ISSUE TITLE
Interactive window does not scroll down automatically when commands are sent from the editor

### ISSUE THREAD

**Issue by Iqigai** [microsoft/vscode-jupyter#9308]
Version: 1.65.1 (system setup)
Commit: 8908a9ca0f221f36507231afb39d2d8d1e182702
Date: 2022-03-08T02:06:27.846Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

When sending commands from the editor to the interactive window for instance with `right click  / Run Selection/Line in Interactive Window`, this latter does not always scroll down to show the most recent output, especially when there's an error. As we can see in the second screen shot we need to move the focus (i.e. click) in the interactive window and then manually pull the scrolling bars down to see what is at the the bottom. This move back and forth from the editor to the IW defeats the purpose of notebook like IDE.
![scrolling2](https://user-images.githubusercontent.com/80190909/157479639-14fa5555-2516-43ea-a503-48cc4f296fd9.png)
![scrolling1](https://user-images.githubusercontent.com/80190909/157479647-ad8c8f91-1aa7-4a10-9525-a60c84ff88eb.png)

**Comment by rchiodo** [comment]
Thanks for the issue. It's already been fixed in our insiders build.

An older version of this was logged here: https://github.com/microsoft/vscode-jupyter/issues/9259

**Comment by rchiodo** [comment]
There's also a workaround, set this to true and it will always scroll:

```
"jupyter.alwaysScrollOnNewCell": true
```
```

**Comment by Iqigai** [comment]
Till the insiders build is released I'll be using the work around. Thanks for the tip!

**Comment by jacobva88** [comment]
> There's also a workaround, set this to true and it will always scroll:
> 
> ```
> "jupyter.alwaysScrollOnNewCell": true
> ```

Could you tell me where I have to type this command please?

**Comment by jacobva88** [comment]
Ok thanks for this. I have turned this setting on but it hasn't really helped. The terminal will scroll down somewhat, but not to the bottom of the window so I can see the output without manually scrolling.  This will be a bit of a pain to sue now. Do you know when the insiders build will be released please?

**Comment by rchiodo** [comment]
Output is actually a separate issue: #9305 

That one is not going to be fixed anytime soon because we need changes in VS code core to get it to work.
