### ISSUE TITLE
Attempting To Run Jupyter Notebook In Virtual Environment Produces "Command Failed" Error

### ISSUE THREAD

**Issue by Salazar-99** [microsoft/vscode-jupyter#931]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Open up a .ipynb file, try to select venv (via bottom left shortcut), and attempt to run a cell

## Actual behavior
Selecting venv doesn't change the kernel (remains Python 3.8.2 instead of switching to venv)
Trying to run a cell results in "Starting Jupyter Notebook" message followed by "Command failed" error pasted below.

## Expected behavior
Able to successfully select venv, Jupyter notebook kernel starts, cells run successfully

### Your Jupyter and/or Python environment

-   **Jupyter server running:** Local 
-   **Extension version:** 2020.6.90262
-   **VS Code version:** 1.46
-   **Setting python.jediEnabled:** true | false (not sure how to find this)
-   **Setting python.languageServer:** Jedi
-   **Python and/or Anaconda version:** Python 3.8.2
-   **OS:**  Linux (Ubuntu 20.04):
-   **Virtual environment:** venv 

## Developer Tools Console Output

Command failed: . /home/gerardo/Desktop/Projects/Bayesian/bayesian-venv/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/gerardo/.vscode/extensions/ms-python.python-2020.6.90262/pythonFiles/pyvsc-run-isolated.py /home/gerardo/.vscode/extensions/ms-python.python-2020.6.90262/pythonFiles/printEnvVariables.py bash: python: command not found

**Comment by jacksongoode** [comment]
I am currently having this issue as well.

**Comment by Salazar-99** [comment]
I ended up going back to JupyterLab for notebooks for a while, then one day I tried again on VS Code and it just worked. Wish I had better advice but it seems like it just fixed itself after a certain number of times opening and closing vscode and restarting my computer.

**Comment by jacksongoode** [comment]
I also just solved it today be deleting the virtual environment folder, recreating and reinstalling the pip packages. VSCode then asked me to install pylinter and ipython (I believe) for that interpreter. I then had to manually configure the venv interpreter within the kernel.json for jupyter notebook to run as well. However, I think this is still an unresolved bug.
