### ISSUE TITLE
debug cell in jupyter notebook never executes or reaches breakpoint

### ISSUE THREAD

**Issue by ybagdasa** [microsoft/vscode-jupyter#9316]
Issue Type: <b>Bug</b>

The debug cell feature has stopped working in jupyter notebooks, while still working in python scripts. I've observed this with different breakpoints in different source files.

For jupyter cells, the execution just hangs with the options to step over, step into... etc grayed out. Only options to pause, reset, and disconnect debugger are available. Upon disconnecting, nothing is output from the cell.
![Screenshot from 2022-03-02 11-43-42](https://user-images.githubusercontent.com/5349813/156439634-89a36b41-4adb-4d83-b9b7-5b3be6f3ccd9.png)

Additionally I've noticed that sometimes when the notebook is first opened there is no option to debug the cell. After executing the cell, the option appears.
![Screenshot from 2022-03-02 12-15-34](https://user-images.githubusercontent.com/5349813/156442748-5b100d01-e241-47ff-8536-151348f49f2d.png)

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.13.0-30-generic snap
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-97-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2000)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (5.42GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 09889aea-dff4-45a4-8c0b-7ecc3bf3592e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Container 10.0.0.95:5000/ybagdasa/pytorch1.10.0-cuda11.1-cudnn8-devel:detectron2 (ybdetectron2) @ ssh://10.158.62.106|
|OS|Linux x64 5.4.0-97-generic|
|CPUs|AMD EPYC 7302 16-Core Processor (32 x 1463)|
|Memory (System)|188.77GB (97.93GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
preview-tiff|ana|1.0.1
gitkraken-authentication|git|1.0.3
kite|kit|0.147.0
vscode-docker|ms-|1.20.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.4
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
autodocstring|njp|0.6.1
vscode-commons|red|0.0.6
vscode-yaml|red|1.4.0
pdf|tom|1.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343
vscaac:30438847
vsnot107:30443614

```

</details>

**Comment by dmho418** [comment]
Same issue.
When I click "Debug cell" the left panel switches "Run and Debug" but nothing happens.
On the top it shows the wrong target configuration ("No configuration" in my case), the debug tool bar shows up (so the debugger did attach to something?), the "run by line" button gets grayed out, very similar to ybagdasa's screenshot. 
![image](https://user-images.githubusercontent.com/10499909/157809308-7ec74ceb-e031-4ea6-8767-a7c32e5cdd18.png)

I running on Windows with WSL, could be a bug in the remote.

VS Code: 1.65.2
OS: Windows_NT x64 10.0.19044
WSL Ubuntu 20.04 LTS
python 3.8.10
ipykernel 6.8.0
jupyter-client 7.1.2
jupyter-core 4.9.1

**Comment by Don-Felice** [comment]
Had the same problem:
![grafik](https://user-images.githubusercontent.com/69037707/159136103-58f481f5-17f1-4332-83ea-541b6dc5fdf0.png)

VS Code: 1.65.2
Windows 10 Pro 10.0.19044
Python 3.8.10
ipykernel 6.8.0

Updating ipykernel to version 6.9.2 fixed it for me.

**Comment by IanMatthewHuff** [comment]
@ybagdasa and @dmho418 We've had some issues recently with the version of ipykernel / debugpy in use. Can you try updating those and see if that helps? Looks like that update helped @Don-Felice .

https://github.com/ipython/ipykernel/issues/841
https://github.com/microsoft/vscode-jupyter/issues/9130

If you are still reproing I'd love the versions of ipykernel and debugpy that are in use.

**Comment by dmho418** [comment]
@IanMatthewHuff upgraded to ipykernel 6.11.0, the debugger working now. Thanks!

**Comment by IanMatthewHuff** [comment]
@ybagdasa Given that this update helped both @dmho418 and @Don-Felice I'm going to close down this issue. If you are still seeing the problem with an updated ipykernel just message back here and I can reopen the issue.

**Comment by ybagdasa** [comment]
@IanMatthewHuff Confirming, that was indeed the issue. Working now with upgraded ipykernel.
