### ISSUE TITLE
ERROR: Input redirection is not supported, exiting the process immediately.

### ISSUE THREAD

**Issue by 0-2-1** [microsoft/vscode-jupyter#9322]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Code:
```
!timeout 2
```

Output:
```ERROR: Input redirection is not supported, exiting the process immediately.```

### VS Code Version

1.65

### Jupyter Extension Version

v2022.2.1020642448

### Running Jupyter locally or remotely?

Local

**Comment by IanMatthewHuff** [comment]
@0-2-1 Thanks for filing. Could you do a couple of things quick for me? First, could you pull the logs from the "Jupyter" tab of the output window. That has our full debugging / diagnostics output and is pretty essential for debugging most issues. Also to check, you are trying to shell out to the windows timeout command? Does this work in a classic jupyter notebook running outside of VS Code? I'm not exactly sure how the Jupyter kernel runs the shell commands, but it seems like if it runs in the background we might not be able to support this (since VS Code is simply layering on top of the Jupyter kernel for execution).

https://www.ibm.com/support/pages/timeout-command-run-batch-job-exits-immediately-and-returns-error-input-redirection-not-supported-exiting-process-immediately

**Comment by 0-2-1** [comment]
> First, could you pull the logs from the "Jupyter" tab of the output window.

I think it's easy to reproduce, btw here is the logs:
<details>
<summary>Jupyter Output</summary>
<br>
Visual Studio Code (1.65.0, undefined, desktop)
Jupyter Extension Version: 2022.2.1020642448.
Python Extension Version: 2022.2.1924087327.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 00:16:46: ZMQ install verified.
Info 00:16:47: Preferred kernel connection found in cache .jvsc74a57bd0614e742bb8362d79323b02687c36b39178a2206e6ff94d540ebda8729a59cc40.C:\Python37x86\python.exe.C:\Python37x86\python.exe.-m#ipykernel_launcher
Info 00:16:47: PreferredConnection: .jvsc74a57bd0614e742bb8362d79323b02687c36b39178a2206e6ff94d540ebda8729a59cc40.C:\Python37x86\python.exe.C:\Python37x86\python.exe.-m#ipykernel_launcher found for NotebookDocument: untitled:Untitled-1.ipynb?jupyter-notebook
Info 00:16:47: Early registration of controller for Kernel connection .jvsc74a57bd0614e742bb8362d79323b02687c36b39178a2206e6ff94d540ebda8729a59cc40.C:\Python37x86\python.exe.C:\Python37x86\python.exe.-m#ipykernel_launcher
Info 00:16:47: TargetController found ID: .jvsc74a57bd0614e742bb8362d79323b02687c36b39178a2206e6ff94d540ebda8729a59cc40.C:\Python37x86\python.exe.C:\Python37x86\python.exe.-m#ipykernel_launcher for document untitled:Untitled-1.ipynb?jupyter-notebook
Info 00:16:47: Setting controller affinity for untitled:Untitled-1.ipynb?jupyter-notebook .jvsc74a57bd0614e742bb8362d79323b02687c36b39178a2206e6ff94d540ebda8729a59cc40.C:\Python37x86\python.exe.C:\Python37x86\python.exe.-m#ipykernel_launcher
Info 00:16:47: Experiment status for python is {"enabled":true,"optInto":["pythonInterpreterInfoUnpinned"],"optOutFrom":[]}
Info 00:16:47: Creating controller for jupyter-notebook with interpreter C:\Python37x86\python.exe
Info 00:16:47: Getting activation commands for C:\Python37x86\python.exe are not cached. May take a while.
Info 00:16:47: Interrupt requested & no kernel.
Info 00:16:47: Setting setActiveController for untitled:Untitled-1.ipynb?jupyter-notebook
Info 00:16:47: Getting activation commands for C:\Python37\python.exe are not cached. May take a while.
Info 00:16:47: KernelProvider switched kernel to id = .jvsc74a57bd004635d289a519a1410467dd0afb0db42f9184808881ca68b2eb5a687a20a5a94.C:\Python37\python.exe.C:\Python37\python.exe.-m#ipykernel_launcher
Info 00:16:47: Starting Notebook in kernel.ts id = .jvsc74a57bd004635d289a519a1410467dd0afb0db42f9184808881ca68b2eb5a687a20a5a94.C:\Python37\python.exe.C:\Python37\python.exe.-m#ipykernel_launcher
Info 00:16:47: Creating raw notebook for untitled:Untitled-1.ipynb?jupyter-notebook
Info 00:16:47: Getting preferred kernel for untitled:Untitled-1.ipynb?jupyter-notebook
Info 00:16:47: Computing working directory untitled:Untitled-1.ipynb?jupyter-notebook
Info 00:16:47: Starting raw kernel Python 3.7.7 64-bit
Info 00:16:47: installMissingDependencies C:\Python37\python.exe
Info 00:16:47: IPykernel found previously in this environment C:\Python37\python.exe
Info 00:16:48: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
Info 00:16:49: Registering dummy command feature
Info 00:16:50: Process Execution: > C:\Python37x86\python.exe -m pip list
> C:\Python37x86\python.exe -m pip list
Info 00:16:50: Process Execution: > C:\Python37\python.exe -m pip list
> C:\Python37\python.exe -m pip list
Info 00:16:50: Process Execution: > C:\Python37\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> C:\Python37\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 00:16:50: Creating daemon process for C:\Python37\python.exe with env variables count 56
Info 00:16:50: Process Execution: > C:\Python37\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 14152
> C:\Python37\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 14152
Info 00:16:54: get interrupthandle daemon
Info 00:16:54: Process Execution: > C:\Python37\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"2fb08b22-4841-4c82-b1f2-f4afbe713bf7" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\USER\AppData\Local\Temp\tmp-14152x4h1DUvDJqbI.json
> C:\Python37\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"2fb08b22-4841-4c82-b1f2-f4afbe713bf7" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\USER\AppData\Local\Temp\tmp-14152x4h1DUvDJqbI.json
Info 00:16:54: Process Execution: cwd: d:\pyprojects\tolidor
cwd: d:\pyprojects\tolidor
Info 00:16:58: ipykernel version 6.9.1 for C:\Python37\python.exe
Info 00:16:58: ipykernel location C:\Python37\lib\site-packages\ipykernel\__init__.py for C:\Python37\python.exe
Warn 00:17:01: StdErr from Kernel Process C:\Python37\lib\site-packages\traitlets\traitlets.py:2205: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  FutureWarning)

Warn 00:17:01: StdErr from Kernel Process C:\Python37\lib\site-packages\traitlets\traitlets.py:2160: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '2fb08b22-4841-4c82-b1f2-f4afbe713bf7' instead of 'b"2fb08b22-4841-4c82-b1f2-f4afbe713bf7"'.
  FutureWarning)

Info 00:17:01: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing C:\Users\USER\AppData\Local\Temp\tmp-14152x4h1DUvDJqbI.json

Info 00:17:02: Raw session started and connected
Started kernel Python 3.7.7 64-bit
Info 00:17:02: Finished connecting 82ad4644-c541-4a1d-84ba-a09d78df8bc6
Info 00:17:02: Executing silently Code (idle) = import sys\nprint(sys.executable)
Info 00:17:06: Executing silently Code (completed) = import sys\nprint(sys.executable)
Info 00:17:06: Executing silently Code (idle) = import site\nsite.addsitedir(site.getusersitepackages())\n__vsc_ipynb_file__ = "Untitled-1.ipynb"\n%con
Info 00:17:06: Executing silently Code (completed) = import site\nsite.addsitedir(site.getusersitepackages())\n__vsc_ipynb_file__ = "Untitled-1.ipynb"\n%con
Info 00:17:06: Waiting for idle on (kernel): 75b2f0e9-5a0b-48c5-add8-322cb7632e2c -> idle
Info 00:17:06: Finished waiting for idle on (kernel): 75b2f0e9-5a0b-48c5-add8-322cb7632e2c -> idle
Info 00:17:08: Registering dummy command feature
Info 00:18:44: Execute Cells request 0
Info 00:18:44: Execute Cell 0 untitled:Untitled-1.ipynb?jupyter-notebook
Info 00:18:44: Cell 0 executed with state Success

</details>



> Also to check, you are trying to shell out to the windows timeout command?

Yes.



> Does this work in a classic jupyter notebook running outside of VS Code?

I don't have any notebook out of vscode.



> I'm not exactly sure how the Jupyter kernel runs the shell commands, but it seems like if it runs in the background we might not be able to support this (since VS Code is simply layering on top of the Jupyter kernel for execution).

should i report this in python extension repo?

**Comment by IanMatthewHuff** [comment]
@0-2-1 thanks for the logs. I can't reproduce this myself as `timeout` is only on windows, and I'm currently on Mac only. But I can get someone else on the team to take a look on windows. My suspicion (per my comment on notebooks outside of vscode) is that we might not be able to support this, but we can investigate more on that.

**Comment by rchiodo** [comment]
Thanks for the issue but ```!timeout``` isn't supported in windows.

**Comment by DonJayamanne** [comment]
Trying this in windows, and doesn't work for me too, this is the error I'm getting `A required privilege is not held by the client.`

**Comment by 0-2-1** [comment]
> https://www.ibm.com/support/pages/timeout-command-run-batch-job-exits-immediately-and-returns-error-input-redirection-not-supported-exiting-process-immediately

can notebook support interactive output like terminal?

![image](https://user-images.githubusercontent.com/26469066/157759628-0012a6d5-46f5-4743-a195-24670da94a37.png)

**Comment by IanMatthewHuff** [comment]
@0-2-1 In general yes. But the ! command to call out to the shell is a bit of a special case. Jupyter doesn't actually control the shell so there are some limitations with how it can be interacted with.

**Comment by 0-2-1** [comment]
@IanMatthewHuff it would be great to support send `!shell commands` in one integrated terminal into vscode, instead of background execute.
or create an `notebook output renderer` for interactive shell input & output.
