### ISSUE TITLE
Node version should move to 16 to follow VS code

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9325]

**Comment by DonJayamanne** [comment]
Looking at VS Code insiders and stable, node 14 is what's still shipped. 
Also the CI builds use v14.
where do you see v16?

**Comment by rchiodo** [comment]
VS just upgraded to v16 this morning.

**Comment by rchiodo** [comment]
Have to wait for the build pipeline to switch to this too. Might not happen

**Comment by mjbvz** [comment]
Switching from `bug` to `engineering` based on description. Let me know if there's something to verify here

**Comment by rchiodo** [comment]
No, nothing to verify except that the extension loads.
