### ISSUE TITLE
Debug cell not working/stuck on first line

### ISSUE THREAD

**Issue by moonj94** [microsoft/vscode-jupyter#9333]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I am trying to debug the current cell, and the process keeps getting stuck on the first line. Initially, there was some sort of pydev error where it couldn't recognize ipykernel or something, but I can't seem to replicate that anymore. I tried changing my ipykernel version and nothing changed. 

I should mention that I am very new to vs code in general, so verbose explanations on how to do/check things would be greatly appreciated.

### VS Code Version

Version: 1.65.2 (user setup) Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1 Date: 2022-03-10T14:33:55.248Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.19043

### Jupyter Extension Version

v2022.2.1030672458

### Jupyter logs

```shell
KeyboardInterrupt                         Traceback (most recent call last)
c:\Users\jaemoon.LARKGROUP\OneDrive - Lark Group\Desktop\python\forward_problem\test.py in <module>
      2 breakpoint()
----> 3 import scipy
      4 import numpy as np
      5 import sklearn
      6 import os, sys

c:\Users\jaemoon.LARKGROUP\OneDrive - Lark Group\Desktop\python\forward_problem\test.py in <module>
      2 breakpoint()
----> 3 import scipy
      4 import numpy as np
      5 import sklearn
      6 import os, sys

_pydevd_bundle/pydevd_cython.pyx in _pydevd_bundle.pydevd_cython.SafeCallWrapper.__call__()

_pydevd_bundle/pydevd_cython.pyx in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch()

_pydevd_bundle/pydevd_cython.pyx in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch()

_pydevd_bundle/pydevd_cython.pyx in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch()

_pydevd_bundle/pydevd_cython.pyx in _pydevd_bundle.pydevd_cython.PyDBFrame.do_wait_suspend()

~\Anaconda3\envs\htc\lib\site-packages\debugpy\_vendored\pydevd\pydevd.py in do_wait_suspend(self, thread, frame, event, arg, exception_type)
   1974 
   1975             with self._threads_suspended_single_notification.notify_thread_suspended(thread_id, stop_reason):
-> 1976                 keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
   1977 
   1978         frames_list = None

~\Anaconda3\envs\htc\lib\site-packages\debugpy\_vendored\pydevd\pydevd.py in _do_wait_suspend(self, thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
   2009 
   2010             self.process_internal_commands()
-> 2011             time.sleep(0.01)
   2012 
   2013         self.cancel_async_evaluation(get_current_thread_id(thread), str(id(frame)))

KeyboardInterrupt:
```

### Coding Language and Runtime Version

Python 3.9.7

### Language Extension Version (if applicable)

 v2022.2.1924087327

### Anaconda Version (if applicable)

conda 4.11.0

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
Does running a cell (without debugging it) work?
What about debugging a very simple cell like
```
a=1
print(a)
```

**Comment by moonj94** [comment]
running the cell by itself works, but debugging the cell does not.

**Comment by amunger** [comment]
Can you post the jupyter extension logs after reproducing the issue - They are in the output tab and select Jupyter in the dropdown:
![image](https://user-images.githubusercontent.com/2019016/157974907-39280a91-1311-482b-86fe-4eccb89db214.png)
