### ISSUE TITLE
Making it easy to get started with the Jupyter extension

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#9336]
This issue represents a place to discuss ideas about how the Jupyter extension can make it as easy as possible to get started using Jupyter notebooks in VS Code. This work will span a combination of smaller ideas that can be tracked separately. To get started:

* #5936
* #1127
* #5864
* #9076
* [vscode-python#17305](https://github.com/microsoft/vscode-python/issues/17305)
* [#278](https://github.com/microsoft/vscode-jupyter-internal/issues/278)

**Comment by IanMatthewHuff** [comment]
This is tracked by other getting started aggregate issues. Closing.
