### ISSUE TITLE
No syntax highlight and code completion in python code cell

### ISSUE THREAD

**Issue by qiuhuiming** [microsoft/vscode-jupyter#9361]
## Environment data

-   VS Code version: 1.65.2
-   Jupyter Extension version (available under the Extensions sidebar): 2022.3.1000751005
-   Python Extension version (available under the Extensions sidebar): 2022.2.1924087327
-   OS (Windows | Mac | Linux distro) and version: MacOS Monterey 12.0.1
-   Python and/or Anaconda version: 3.9.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A: Local

## Expected behaviour

Support python syntax highlight and code completion in code cell as like in .py files.

## Actual behaviour

No python syntax highlight and code completion, thought the kernal works well.

<img width="975" alt="image" src="https://user-images.githubusercontent.com/47179776/158335335-c7e5c0ad-82f5-46ad-b604-3235cc5a51ea.png">

I'm confused about the "CVE" in the bottom right corner. In markdown cell, it is "Markdown" instead. I have no idea if it failed to detact the language.

<img width="930" alt="image" src="https://user-images.githubusercontent.com/47179776/158335814-2d489fee-d801-4f8a-a0a9-305b6e6c5a0b.png">

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]
I have tried to reset all  vscode settings and only installed Python and Jupyter extension but the problem is still existing. I don't known if it is related to the os according to the log output.

## Logs

<details>

Visual Studio Code (1.65.2, undefined, desktop)
Jupyter Extension Version: 2022.3.1000751005.
Python Extension Version: 2022.2.1924087327.
用户属于实验组 'jupyterTest'
用户属于实验组 'jupyterEnhancedDataViewer'
Error 15:59:38: Exception while attempting zmq : Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=89 uv=1 armv=8 libc=glibc node=14.16.0 electron=13.5.2
    loaded from: /Users/qiuhuiming/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/out/client/node_modules/zeromq

    at Function.load.path (/Users/qiuhuiming/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/out/client/node_modules/node-gyp-build/index.js:1:2741)
    at load (/Users/qiuhuiming/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/out/client/node_modules/node-gyp-build/index.js:1:625)
    at Object.<anonymous> (/Users/qiuhuiming/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/out/client/node_modules/zeromq/lib/native.js:1:198)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:32148)
    at Function._._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:28737)
    at Function.g._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:60372)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
    at Object.<anonymous> (/Users/qiuhuiming/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/out/client/node_modules/zeromq/lib/index.js:1:144)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:32148)
    at Function._._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:28737)
    at Function.g._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:60372)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
    at Object.92747 (/Users/qiuhuiming/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/out/client/extension.js:2:3942568)
    at __webpack_require__ (/Users/qiuhuiming/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/out/client/extension.js:2:4610281)
    at u.zmqSupported (/Users/qiuhuiming/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/out/client/extension.js:2:1136507)
    at u.isSupportedForLocalLaunch (/Users/qiuhuiming/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/out/client/extension.js:2:1136250)
    at u.get isSupported [as isSupported] (/Users/qiuhuiming/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/out/client/extension.js:2:1136160)
    at t.registerTypes (/Users/qiuhuiming/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/out/client/extension.js:2:594602)
    at /Users/qiuhuiming/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/out/client/extension.js:2:680925
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /Users/qiuhuiming/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/out/client/extension.js:2:4611856
    at e.activate (/Users/qiuhuiming/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/out/client/extension.js:2:4611533)
    at async Promise.all (index 0)
Info 15:59:38: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 15:59:38: Creating controller for jupyter-notebook with interpreter /opt/homebrew/bin/python3
Info 15:59:38: Getting activation commands for /opt/homebrew/bin/python3 are not cached. May take a while.
Info 15:59:38: Interrupt requested & no kernel.
Info 15:59:38: Setting setActiveController for ~/source/tmp/demo.ipynb
Info 15:59:38: KernelProvider switched kernel to id = .jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e./opt/homebrew/bin/python3./opt/homebrew/bin/python3.-m#ipykernel_launcher
Info 15:59:38: Starting Notebook in kernel.ts id = .jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e./opt/homebrew/bin/python3./opt/homebrew/bin/python3.-m#ipykernel_launcher
Info 15:59:38: Checking for server existence.
Info 15:59:38: Checking for server usability.
Info 15:59:38: Old KernelSpec '/Users/qiuhuiming/Library/Jupyter/kernels/python399jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e/kernel.json' deleted and backup stored in /Users/qiuhuiming/Library/Jupyter/kernels/__old_vscode_kernelspecs
Info 15:59:38: Process Execution: > /opt/homebrew/bin/python3 -m pip list
> /opt/homebrew/bin/python3 -m pip list
Info 15:59:38: Process Execution: > /opt/homebrew/bin/python3 -c "import jupyter"
> /opt/homebrew/bin/python3 -c "import jupyter"
Info 15:59:38: Process Execution: > /opt/homebrew/bin/python3 -c "import notebook"
> /opt/homebrew/bin/python3 -c "import notebook"
Info 15:59:38: Find preferred kernel for ~/source/tmp/demo.ipynb with metadata {"interpreter":{"hash":"b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e"},"kernelspec":{"display_name":"Python 3.9.9 64-bit","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.9"},"orig_nbformat":4} & preferred interpreter /opt/homebrew/bin/python3
Info 15:59:38: findKernel found Python 3.9.9 64-bit
Info 15:59:38: PreferredConnection: .jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e./opt/homebrew/bin/python3./opt/homebrew/bin/python3.-m#ipykernel_launcher found for NotebookDocument: ~/source/tmp/demo.ipynb
Info 15:59:38: TargetController found ID: .jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e./opt/homebrew/bin/python3./opt/homebrew/bin/python3.-m#ipykernel_launcher for document ~/source/tmp/demo.ipynb
Info 15:59:38: Setting controller affinity for ~/source/tmp/demo.ipynb .jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e./opt/homebrew/bin/python3./opt/homebrew/bin/python3.-m#ipykernel_launcher
Info 15:59:39: Process Execution: > /opt/homebrew/bin/python3 -m jupyter kernelspec --version
> /opt/homebrew/bin/python3 -m jupyter kernelspec --version
Info 15:59:39: Registering dummy command feature
Info 15:59:39: Starting notebook server.
Info 15:59:39: Connecting to server
Info 15:59:39: Launching server
Info 15:59:39: Starting Notebook
Info 15:59:39: Generating custom default config at /var/folders/j4/yv38ffjj6f584gq_71yxrpdm0000gn/T/23255d29-ad93-4303-8200-3e01bb9f45e6/jupyter_notebook_config.py
Info 15:59:39: Starting Jupyter Notebook
用命令行 --no-browser --notebook-dir="/Users/qiuhuiming/source/tmp" --KernelManager.autorestart=False --config=/var/folders/j4/yv38ffjj6f584gq_71yxrpdm0000gn/T/23255d29-ad93-4303-8200-3e01bb9f45e6/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0 从 /opt/homebrew/bin/python3 启动 Jupyter
Info 15:59:39: Creating daemon pool for /opt/homebrew/bin/python3 with env variables count 56
Info 15:59:39: Process Execution: > /opt/homebrew/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 2862
> /opt/homebrew/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 2862
Info 15:59:39: Process Execution: > /opt/homebrew/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 2862
> /opt/homebrew/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 2862
Info 15:59:39: Process Execution: > /opt/homebrew/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 2862
> /opt/homebrew/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 2862
Info 15:59:39: Process Execution: > /opt/homebrew/bin/python3 (daemon) -m jupyter notebook --no-browser --notebook-dir="/Users/qiuhuiming/source/tmp" --KernelManager.autorestart=False --config=/var/folders/j4/yv38ffjj6f584gq_71yxrpdm0000gn/T/23255d29-ad93-4303-8200-3e01bb9f45e6/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> /opt/homebrew/bin/python3 (daemon) -m jupyter notebook --no-browser --notebook-dir="/Users/qiuhuiming/source/tmp" --KernelManager.autorestart=False --config=/var/folders/j4/yv38ffjj6f584gq_71yxrpdm0000gn/T/23255d29-ad93-4303-8200-3e01bb9f45e6/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
Info 15:59:39: Waiting for Jupyter Notebook
/opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/qiuhuiming/source/tmp' instead of '"/Users/qiuhuiming/source/tmp"' if you require traitlets >=5.
  warn(
Info 15:59:39: /opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/qiuhuiming/source/tmp' instead of '"/Users/qiuhuiming/source/tmp"' if you require traitlets >=5.
  warn(

[I 15:59:40.020 NotebookApp] Serving notebooks from local directory: /Users/qiuhuiming/source/tmp
Info 15:59:40: /opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/qiuhuiming/source/tmp' instead of '"/Users/qiuhuiming/source/tmp"' if you require traitlets >=5.
  warn(
[I 15:59:40.020 NotebookApp] Serving notebooks from local directory: /Users/qiuhuiming/source/tmp

[I 15:59:40.021 NotebookApp] Jupyter Notebook 6.4.6 is running at:
Info 15:59:40: /opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/qiuhuiming/source/tmp' instead of '"/Users/qiuhuiming/source/tmp"' if you require traitlets >=5.
  warn(
[I 15:59:40.020 NotebookApp] Serving notebooks from local directory: /Users/qiuhuiming/source/tmp
[I 15:59:40.021 NotebookApp] Jupyter Notebook 6.4.6 is running at:

[I 15:59:40.021 NotebookApp] http://localhost:8888/?token=bb092a7176611e81e2a4d940e785478940dc6c0ecd479b63
Info 15:59:40: /opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/qiuhuiming/source/tmp' instead of '"/Users/qiuhuiming/source/tmp"' if you require traitlets >=5.
  warn(
[I 15:59:40.020 NotebookApp] Serving notebooks from local directory: /Users/qiuhuiming/source/tmp
[I 15:59:40.021 NotebookApp] Jupyter Notebook 6.4.6 is running at:
[I 15:59:40.021 NotebookApp] http://localhost:8888/?token=bb092a7176611e81e2a4d940e785478940dc6c0ecd479b63

Info 15:59:40: Process Execution: > /opt/homebrew/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /opt/homebrew/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[I 15:59:40.021 NotebookApp]  or http://127.0.0.1:8888/?token=bb092a7176611e81e2a4d940e785478940dc6c0ecd479b63
Info 15:59:40: /opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/qiuhuiming/source/tmp' instead of '"/Users/qiuhuiming/source/tmp"' if you require traitlets >=5.
  warn(
[I 15:59:40.020 NotebookApp] Serving notebooks from local directory: /Users/qiuhuiming/source/tmp
[I 15:59:40.021 NotebookApp] Jupyter Notebook 6.4.6 is running at:
[I 15:59:40.021 NotebookApp] http://localhost:8888/?token=bb092a7176611e81e2a4d940e785478940dc6c0ecd479b63
[I 15:59:40.021 NotebookApp]  or http://127.0.0.1:8888/?token=bb092a7176611e81e2a4d940e785478940dc6c0ecd479b63

Info 15:59:40: Process Execution: > /opt/homebrew/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /opt/homebrew/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[I 15:59:40.021 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Info 15:59:40: /opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/qiuhuiming/source/tmp' instead of '"/Users/qiuhuiming/source/tmp"' if you require traitlets >=5.
  warn(
[I 15:59:40.020 NotebookApp] Serving notebooks from local directory: /Users/qiuhuiming/source/tmp
[I 15:59:40.021 NotebookApp] Jupyter Notebook 6.4.6 is running at:
[I 15:59:40.021 NotebookApp] http://localhost:8888/?token=bb092a7176611e81e2a4d940e785478940dc6c0ecd479b63
[I 15:59:40.021 NotebookApp]  or http://127.0.0.1:8888/?token=bb092a7176611e81e2a4d940e785478940dc6c0ecd479b63
[I 15:59:40.021 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

[C 15:59:40.024 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/qiuhuiming/Library/Jupyter/runtime/nbserver-3326-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=bb092a7176611e81e2a4d940e785478940dc6c0ecd479b63
     or http://127.0.0.1:8888/?token=bb092a7176611e81e2a4d940e785478940dc6c0ecd479b63
Info 15:59:40: /opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/qiuhuiming/source/tmp' instead of '"/Users/qiuhuiming/source/tmp"' if you require traitlets >=5.
  warn(
[I 15:59:40.020 NotebookApp] Serving notebooks from local directory: /Users/qiuhuiming/source/tmp
[I 15:59:40.021 NotebookApp] Jupyter Notebook 6.4.6 is running at:
[I 15:59:40.021 NotebookApp] http://localhost:8888/?token=bb092a7176611e81e2a4d940e785478940dc6c0ecd479b63
[I 15:59:40.021 NotebookApp]  or http://127.0.0.1:8888/?token=bb092a7176611e81e2a4d940e785478940dc6c0ecd479b63
[I 15:59:40.021 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:59:40.024 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/qiuhuiming/Library/Jupyter/runtime/nbserver-3326-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=bb092a7176611e81e2a4d940e785478940dc6c0ecd479b63
     or http://127.0.0.1:8888/?token=bb092a7176611e81e2a4d940e785478940dc6c0ecd479b63

Info 15:59:40: Connecting to process server
Info 15:59:40: Connecting server kernel http://localhost:8888/
Info 15:59:40: Creating server with settings : {"baseUrl":"http://localhost:8888/","appUrl":"","wsUrl":"ws://localhost:8888/","token":"bb092a7176611e81e2a4d940e785478940dc6c0ecd479b63","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 15:59:40: Connection complete server
Info 15:59:40: Server started.
Info 15:59:40: Process Execution: > /opt/homebrew/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /opt/homebrew/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/pythonFiles/vscode_datascience_helpers/getServerInfo.py
Info 15:59:40: Process Execution: > /opt/homebrew/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /opt/homebrew/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[I 15:59:40.319 NotebookApp] Creating new notebook in 
Info 15:59:40: installMissingDependencies /opt/homebrew/bin/python3
Info 15:59:40: Process Execution: > /opt/homebrew/bin/python3 -c "import ipykernel"
> /opt/homebrew/bin/python3 -c "import ipykernel"
Info 15:59:40: RegisterKernel for .jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e./opt/homebrew/bin/python3./opt/homebrew/bin/python3.-m#ipykernel_launcher into ~/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000751005/temp/jupyter/kernels/python399jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e/kernel.json
Info 15:59:40: Spec argv[0] updated from 'python' to '/opt/homebrew/bin/python3'
Info 15:59:40: Starting a new session for kernel id = .jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e./opt/homebrew/bin/python3./opt/homebrew/bin/python3.-m#ipykernel_launcher, name = python399jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e
[I 15:59:40.550 NotebookApp] Kernel started: 61e31800-ee88-4140-b555-328472787853, name: python399jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e
Info 15:59:40: Waiting for idle on (kernel): 61e31800-ee88-4140-b555-328472787853 -> unknown
[W 15:59:40.562 NotebookApp] delete /demo-jvsc-4c2fec3c-42dc-4f70-bad8-229e71e540d1.ipynb
Info 15:59:41: Finished waiting for idle on (kernel): 61e31800-ee88-4140-b555-328472787853 -> idle
Info 15:59:41: Started session for kernel .jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e./opt/homebrew/bin/python3./opt/homebrew/bin/python3.-m#ipykernel_launcher
Info 15:59:41: Finished connecting kernel .jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e./opt/homebrew/bin/python3./opt/homebrew/bin/python3.-m#ipykernel_launcher
Info 15:59:41: UpdateWorkingDirectoryAndPath in Kernel
Info 15:59:41: Executing silently Code (idle) = import site\nsite.addsitedir(site.getusersitepackages())\nimport os\nimport sys\n%cd "/Users/qiuhuiming/
Info 15:59:41: Executing silently Code (completed) = import site\nsite.addsitedir(site.getusersitepackages())\nimport os\nimport sys\n%cd "/Users/qiuhuiming/
Info 15:59:41: Waiting for idle on (kernel): 61e31800-ee88-4140-b555-328472787853 -> idle
Info 15:59:41: Finished waiting for idle on (kernel): 61e31800-ee88-4140-b555-328472787853 -> idle
Info 15:59:49: Execute Cells request 0
Info 15:59:49: Execute Cell 0 ~/source/tmp/demo.ipynb
Info 15:59:49: Cell 0 executed with state Success
Info 16:19:11: Execute Cells request 0
Info 16:19:11: Execute Cell 0 ~/source/tmp/demo.ipynb
Info 16:19:11: Cell 0 executed with state Success

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the issue. 

This caused by another extension. You can tell because it says 'CVE' for the language for the cell in the lower right. 

See this issue here:
https://github.com/microsoft/vscode-jupyter/issues/7917
