### ISSUE TITLE
Typing greek letters (conveniently)

### ISSUE THREAD

**Issue by mapio** [microsoft/vscode-jupyter#9363]
As discussed in #806, #3315, and #3677 it would be great to be able to type greek letters in notebooks.

Since all such bug reports have been closed without solving the issue, I'd like to suggest to other users looking for help in the issues I'd like to point out the hint in #9362.

**Comment by rchiodo** [comment]
> I do understand that you don't want to bloat the Jupyter package, but I think it's confusing that in a Python file and in a Jupyter notebook (in vscode) the completion works so differently.

That would be a bug. They should be the same for python code. Or are you referring to Jupyter specific tasks, like LaTeX?

**Comment by mapio** [comment]
> That would be a bug. They should be the same for python code. Or are you referring to Jupyter specific tasks, like LaTeX?

Not sure to get what you mean.

If you open a Python file (with vscode), type `\alpha` and press TAB, the editor substitutes `\alpha` with , but the same does not happen if you open a Jupyter notebook (with vscode) and type in a code cell.

What I did not realize is that the completion works in a Python file thanks to yellpika.latex-input extension that seems not to work in Jupyter notebook code cells thoug.

On the other hand, the web interface of Jupyter notebooks supports LaTeX completion.

**Comment by rchiodo** [comment]
It's likely yellpika.latex-input extension doesn't support jupyter notebooks. 

It is strange that the web jupyter supports LaTeX and we don't though. We use the same underlying service to get completions in notebooks. 

Unless you have some extra extensions installed in jupyter too. Oh maybe this one? (https://github.com/latex-lsp/texlab). That wouldn't work in VS code.

**Comment by rchiodo** [comment]
Looking at the source for yellpika (https://github.com/YellPika/vscode-latex-input) you might be able to get it to work in a jupyter notebook. The scheme for the selector is wrong is all. It might work if you changed/added the 'scheme' value to 'vscode-notebook-cell'

**Comment by mapio** [comment]
> It is strange that the web jupyter supports LaTeX and we don't though. We use the same underlying service to get completions in notebooks.

Tested now, in a freshly minted virtual environment with just `pip install jupyter`. If you enter `\alpha` and TAB in a code cell it is replaced by the unicode letter; that strangely does not happen for markdown cells!

**Comment by mapio** [comment]
> It might work if you changed/added the 'scheme' value to 'vscode-notebook-cell'

It works! That's a very good hint, thank you. I read the extension doc, but was unable to figure out the scheme myself.

**Comment by mapio** [comment]
Watch out that the order seems to be relevant. This
    
      "latex-input.selector": [  
        {
          "scheme": "vscode-notebook-cell"
        },
        {
          "scheme": "file"
        }
      ]

works, but swapping the two "scheme" dicts does not.

**Comment by p-i-** [comment]
waitwat..?
> Tested now, in a freshly minted virtual environment with just pip install jupyter. If you enter \alpha and TAB in a code cell it is replaced by the unicode letter; that strangely does not happen for markdown cells!

I just tried creating a `x.ipynb` in VSCode FileExplorer, opening it, running a cell (which force-installs `ipykernel`) and `\alpha<TAB>` 100% does NOT autocomplete.

This is something I sorely miss. It's super-useful to be able to use greek variables when transcribing from ArXiv ML papers.

Please can team VSCode consider getting this working? Really it's a biggie.

**Comment by mapio** [comment]
If you read carefully the thread, you see that it works (both in code and Markdown cells) if you just install https://github.com/YellPika/vscode-latex-input and then add https://github.com/microsoft/vscode-jupyter/issues/9363#issuecomment-1272241667 in your `settings.json`.

Hope this helps.

**Comment by Atcold** [comment]
Does this work also for, say `y\tilde` + `<Tab>`?
Jupyter Notebook and Lab both replace `y` with `ỹ`.

**Comment by Yugal0** [comment]
> Thanks for the issue. What more would you want besides what the [Greek Alphabet Snippets](https://marketplace.visualstudio.com/items?itemName=lucas-rezende.greek-alphabet-snippets) provides?
> 
> I doubt we'd be implementing specific support for the greek alphabet in the jupyter extension, but maybe this request is about more than typing.
> 
> Is this more about LaTeX auto complete?

I installed [Greek Alphabet Snippets](https://marketplace.visualstudio.com/items?itemName=lucas-rezende.greek-alphabet-snippets). But don't know how to use it, I am a newbie, Any help please.
