### ISSUE TITLE
Cannot see defaultInterpreterPath kernel when selecting kernel ("Python is not installed.").

### ISSUE THREAD

**Issue by hasush** [microsoft/vscode-jupyter#9365]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When running an .ipynb file, not all kernels are shown to be selected. In particular, the kernel in the settings.json corresponding to key "python.defaultInterpreterPath" is not available. When executing a cell with the kernel that is available, a prompt pops up and states that python must be installed.

### VS Code Version

Version: 1.65.2 (Universal) Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1 Date: 2022-03-10T14:33:49.188Z (5 days ago) Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Darwin x64 20.6.0

### Jupyter Extension Version

v2022.2.1030672458

### Jupyter logs

```shell
Not sure how to do this step.
```

### Running Jupyter locally or remotely?

Remote

**Comment by rchiodo** [comment]
Closing as needs more info. Please reopen if you can provide the logs and the problem still reproduces.
