### ISSUE TITLE
Please update the readme file in Notebook Renderers extension

### ISSUE THREAD

**Issue by kasajian** [microsoft/vscode-jupyter#9370]
Please update the readme file and put something, anything, that shows how this extension can be used.

Perhaps you can point to a very simply jupiter network file on the web that one can open to show how this works.

Something that will work with "Visual Studio Code on Web" as used in github

**Comment by DonJayamanne** [comment]
**Things to update readme with**
* List mime types
* Document what this extension does (selecting outputs types, etc)
* Why do users need this extension
* Create sample notebook & provide a link to this on readme/wiki or the like so users can open this in vs code web

**Comment by DonJayamanne** [comment]
Done
