### ISSUE TITLE
Scala kernel autocomplete does not suggest anything

### ISSUE THREAD

**Issue by Jeronimo-GL** [microsoft/vscode-jupyter#9380]
When using the scala kernel in Jupyter the autocomplete only suggests words already typed but it does not suggest any of the methods of the variable for example. It seems it is not connecting with metals.

## Environment data

-   VS Code version: 1.65.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.2.1030672458
-   Python Extension version (available under the Extensions sidebar): v2022.2.1924087327
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 21.10
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used virtualenv
-   Jupyter server running: Local |
## Expected behaviour

In Python when I type and object and I want to call any of the methods the autocomplete function suggests the methods available. I'd like the same behaviour in Scala.

## Actual behaviour

In scala it does not suggest any of the methods of the object.

## Steps to reproduce:

I am not completely sure about this, as i don't know how the scala kernel works with jupyter in vscode. But it is great for example working with Spark. My setup in terms of Scala:

openjdk 11.0.14 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.14+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing

Scala code runner version 2.13.6 -- Copyright 2002-2021, LAMP/EPFL and Lightbend, In

metals 0.10.9

I have installed the scala (metals) plugin: v1.13.0. But other than that I don't remember any other configuration.

If you create a new notebook and choose the "Scala kernel" it works almost perfectly, I can write scala code and execute it, but the autocomplete does not work beyond suggesting any of the words I typed before. it seems it is not connecting with metals. This is a guess, I know how the scala plugin works and connects with metals. But from the jupyter kernel perspective it's magic to me.

![Captura de pantalla de 2022-03-16 10-11-12](https://user-images.githubusercontent.com/14802225/158555992-59036ff3-79f0-4b6d-a307-fee632592166.png)

**Comment by rchiodo** [comment]
Thanks for the issue. We only support calling the completion in the kernel from python kernels at the moment. This is because we have to parse the results (they don't follow the same patterns as VS code completions and must be fixed up). 

If you're so inclined, support for scala could probably be added through a PR. The python version of this is implemented here:
https://github.com/microsoft/vscode-jupyter/blob/6294201490592aeb5258a0e5117783ad2779944a/src/intellisense/pythonKernelCompletionProvider.ts#L41

**Comment by DonJayamanne** [comment]
Closing this issue as there haven't been enough upvotes on this and others haven't brought this up.
