### ISSUE TITLE
Jupyter/Python extension integration tests in VS code core

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9384]
There have been two failures in the last week related to core changes (caught by integration tests on Jupyter). 

Maybe we should add some tests in VS code core that run with jupyter/python? Is this outside the scope of VS code core testing? (It would require python being installed)

**Comment by DonJayamanne** [comment]
I don't think this is necessary, as the API stabilizes we might find the need for such a test, less & less useful.
Closing for now.
