### ISSUE TITLE
Running all cells marks every cell as running

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-jupyter#9405]
![image](https://user-images.githubusercontent.com/35271042/158850277-d044458d-de75-49e1-807e-3b55b39f6192.png)

Expectation is that only a single cell would show as running while others are in the "pending/queued" state.

Jupyter Extension: v2022.3.1000781005
Version: 1.66.0-insider (Universal)
Commit: db0525ff4ba814780e901a5b9e399aaf596b9b20
Date: 2022-03-17T05:18:05.656Z
Electron: 17.1.1
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.0

**Comment by IanMatthewHuff** [comment]
Thanks for the report. Just to log the info from the offline thread, this is on the jupyter extension to make sure that we don't set the status to started when cells are queued to run, just keep the pending state.
