### ISSUE TITLE
Consider using micromamba when installing packages on enduser machines

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9406]

**Comment by greazer** [comment]
Not sure what your intent here was Don, but I think part of this isn't just about using micromamba to install packages, but rather to consider using it to allow users to easily create environments on their machine that can work independently or in conjunction with other environments (if they're already using Anaconda) they may have on their machine.

**Comment by DonJayamanne** [comment]
@greazer  this is a suggestion RIch made.
His suggestion was that we use micromamba when installing packages such as IPykernel or the like for conda environments.
Today when users need to use various parts of the extension might have to install IPyKernel, jupyter, nbformat, etc, and when using conda enviornments we use the conda executable we can find on the system. The suggestion here is that we don't ever look for these conda executables , instead just use micromamba.

We haven't decided to do this, we had a brief discussion and felt we can sit on this for a while and re-visit this again (hence the `needs-triage` label).
Personally I'm not sold on this approach, at least not yet, we haven't even tried micromamba and the idea of using this always to install user packages feels way too early to force this on users and not use their conda installations.

**Comment by DonJayamanne** [comment]
Closing for in favor of using micromamba for blessed environment
