### ISSUE TITLE
 Jupyter connection closes after inactivity

### ISSUE THREAD

**Issue by kjcho-msft** [microsoft/vscode-jupyter#9411]
For a VS Code Data extension we are working on, we need a non-culling kernel connection. For our extension, leaving kernel idle for a long time (10 mins) is common but in that case, the kernel connection can be closed unexpectedly. So it’d be helpful if we have a persistent connection or at least it can be self-reconnected. 

## Environment data

-   VS Code version: 1.66.0-insider (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2022.3.1000781005
-   Python Extension version (available under the Extensions sidebar): v2022.2.1924087327
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: Python310
-   Jupyter server running: Local

## Expected behaviour

Need a way to keep the kernel connection alive 

## Actual behaviour

Kernel connection closes after inactivity

**Comment by DonJayamanne** [comment]
You can keep the connection alive by sending some shell (or other) message to the kernel.
Closing as this can be resolved externally.
