### ISSUE TITLE
Should not be prompted to install Python when trying to run a Jupyter notebook on Azure ML compute instance

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-jupyter#9415]
I cloned a repository, opened a notebook, and hit "Run All". Despite being on the compute instance, I'm prompted to install Python.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/6413608/159054710-908c3fe2-088d-4e8a-990a-e6c87f55a01e.png">

I should not have to install Python. I should be able to select a Python interpreter and kernel that is already available on the compute instance. When I try and change the kernel using the selector I'm only shown "Python 3" with no information about installation path or where it is being pulled from:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/6413608/159054824-c49f49a8-ff28-4168-88e3-76d67f45f27a.png">

If I open a Python file I can select an interpreter (e.g., Azure ML Py3.8) and successfully run my Python file. It is not clear to me how to make the same selection from within a Notebook view.

This is blocking the golden scenario run for Azure ML.

**Comment by rchiodo** [comment]
This means we're not getting any interpreters from the python extension. @SiddhanthUnnithan can  you include the output log for jupyter?

**Comment by SiddhanthUnnithan** [comment]
> This means we're not getting any interpreters from the python extension. @SiddhanthUnnithan can you include the output log for jupyter?

[jupyter_log_nb_open_issue.txt](https://github.com/microsoft/vscode-jupyter/files/8306876/jupyter_log_nb_open_issue.txt)

**Comment by SiddhanthUnnithan** [comment]
@rchiodo let me know if there's anything else you need
