### ISSUE TITLE
builtin Jupyter notebooks are slow and unreliable with Julia lang

### ISSUE THREAD

**Issue by lewisl** [microsoft/vscode-jupyter#9417]
I am sorry to report this in a way that is hard to reproduce or diagnose. That is sort of the nature of the beast with deep dependencies.

I use Julia.  The Julia kernel is provided by the 1) IJulia Julia package OR by the 2) Julia VS Code plugin.
No. 1 is essentially unusable: very slow, results from previous cells simply are forgotten during even a short session. Cells cannot be stopped. They appear as stopped, but in fact the kernel has probably hung. The kernel cannot be restarted.  Only resort is quitting VS Code and starting over.  Sometimes, but rarely this works.
No. 2 using the Julia plugin and language server is much better. It more or less works but is very slow. I'll go back and try out stopping a cell and restarting the kernel to see if these work.

If I can provide some diagnostics I will.  Otherwise all I can say is create a notebook that runs non-trivial code loaded from the files of a module or package (two kinds of containers for Julia code). Now load the Python implemented Jupyter (notebook or lab) and run code from the same package or module. No problems.  Much faster works as expected.

I want to like the Jupyter support in VS Code especially because editing the notebook itself uses all the capabilities of VS Code. But, running is just too slow and unreliable.

**Comment by IanMatthewHuff** [comment]
@lewisl Sorry I wasn't quite sure from your initial comment. In both scenarios do you have the Julia vscode extension installed? If that's the case then it would be best to open up an issue on the Julia extension repo regarding this. If you are seeing issues with just the Jupyter extension installed but using a Julia kernel (you can disable the Julia extension to make sure you are in this state) then I can hopefully help investigate this.

**Comment by rchiodo** [comment]
Closing as needs more info. If you can reproduce the issue with just the jupyter extension, please reopen.
