### ISSUE TITLE
Using shell commands to install packages shows false positive installation in Azur ML compute

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-jupyter#9421]
Missing packages while running the golden scenario. Installed the packages via "!pip install ..." showing success in the output, but when importing the package I'm receiving a missing package error:

<img width="898" alt="image" src="https://user-images.githubusercontent.com/6413608/159068330-b409f420-fd79-4c74-bae8-b6a63d9a2f0a.png">

**Comment by rchiodo** [comment]
You shouldn't be using '!'. That's why it shows an error there. `%pip install` is the correct command. You likely just installed pydotplus into your global python.

**Comment by DonJayamanne** [comment]
Also, please could you provide the version number of the Jupyter extension.

**Comment by SiddhanthUnnithan** [comment]
@rchiodo you were right. I was doing the global install earlier. Thanks!

This has me thinking -- is there a way we can teach users about the right way to install in the environment they're currently connected to. My default was assuming that any notebook shell commands are ran within my connected Anaconda environment.

**Comment by rchiodo** [comment]
The red squiggle is what we do now. It should show this:

![image](https://user-images.githubusercontent.com/19672699/162025946-5dff71b8-67c3-4ca9-9266-a980ade04a6e.png)

**Comment by SiddhanthUnnithan** [comment]
Awesome, I didn't catch that the first time. I'll close this.
