### ISSUE TITLE
Slow to load and missing completion options for dataframes in notebooks

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-jupyter#9422]
<img width="290" alt="image" src="https://user-images.githubusercontent.com/6413608/159070075-70bd754e-1e39-43a2-a19f-a32d8f70a732.png">

Running the above tests:
1. I expected typing "tita" would show completions in sub 1 second. It takes around 2 - 3 seconds.
2. I'm expecting completions for column names of the dataframe when typing ["...". Currently, referencing columns doesn't show anything.
3. Completions for methods like "value_counts" and "sort_values" are slow to load and I end up typing the entire method name.

**Comment by rchiodo** [comment]
The slowness wouldn't be us (pylance issue) but the 'Columns' in quotes is actually a bug in our completion provider. We skip everything except files when inside quotes with the assumption the user is listing a file name. We need more context to determine this might be a column instead. Feels like something pylance would have to handle too, or we're going to be rewriting pylance inside the jupyter extension.

**Comment by DonJayamanne** [comment]
We could try the following:
* Change algorithm to show everything from jupyter when inside quotes
* Parse the code and determine context of the code (cursor pos)

**Comment by greazer** [comment]
The columns problem is tracked elsewhere. The rest of this is fixed.
