### ISSUE TITLE
No intellisense in Notebook.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/vscode-jupyter#9428]
## Environment data

Build of Visual Studio Code - Insiders: 1.66.0-insider (user setup)   
Build of python-insider: v2022.3.1931132634-dev 
Build of jupyter-insider: v2022.2.1030672458 
Build of pylance-insider: v2022.3.2 
Build of jupyter Notebook Renderers: v1.0.6 
Build of jupyter Keymap: v1.0.0 

![image](https://user-images.githubusercontent.com/82852072/159234305-4ccbf4d4-5a7e-45f7-ab08-3f8ca7519c5b.png)

## Expected behaviour

Move the cell around and verify intellisense hover still works on the `import sys`.

## Actual behaviour

No intellisense.

![image](https://user-images.githubusercontent.com/82852072/159234407-0b1b02ac-3850-4e2b-acf7-6b2b6e4508fb.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open the src/test/datascience/manualTestFiles/manualTestFile.py in VSCode.
2. Run all of the cells in the file.
3. Interactive Window should open
4.  Export the cells in the interactive window and open the notebook editor
5. Hover over each cell in the notebook editor and verify you get hover intellisense
6. Add a new cell in between cells
7.  Add `import sys` and `sys.executable` to the cell
8. Move the cell around and verify intellisense hover still works on the `import sys`

**Comment by rchiodo** [comment]
Thanks for the issue. Your insiders build of Juptyer is out of date. It should be updated to the latest:

Name: Jupyter
Id: ms-toolsai.jupyter
Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.
Version: 2022.3.1000821004
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
