### ISSUE TITLE
Test installing modules

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9434]
Refs: https://github.com/microsoft/vscode-jupyter/issues/9376
https://github.com/microsoft/vscode-jupyter/issues/8457

- [x] anyOS: @IanMatthewHuff 
- [x] anyOS: @kimadeline 

Complexity: 4

Picking folks that have experience with this sort of thing. Feel free to reassign if you have too many items.

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%239434%0A%0A&assignees=rchiodo)

---

### Requirements

- Install a global python that is not the windows store version (poetry won't work with windows store)
- Install Conda
- Install Poetry (https://python-poetry.org/docs/). Make sure poetry is on the global path
- Install Python/Jupyter Extension
- Set the ```python.poetryPath``` setting in VS code to point to where your poetry executable is.

### Test Conda

1. Create a conda environment with say python 3.9. Like so:
```
conda create -c conda-forge -n Test python=3.9
```
2. Create a blank notebook
3. Pick this environment as your kernel
4. Make sure you're prompted to install ipykernel when running a cell
5. Install it and verify it works
6. Repeat (with new env) and pick cancel.
7. Verify it cancels
8. Repeat (with the new env from step 6) and pick switch (instead of install or cancel)
9. Verify it switches and runs the cell
10. Create a blank python file and add a cell
```python
# %%
print(1)
```
11. Pick the 'selected interpreter' to match your empty environment and repeat the steps you took for the notebook but with the interactive window. (Click Run Cell above the '#%%)

### Test Pip

1. Create venv like so:
```
python -m venv TestPip
```
2. Repeat steps taken for a conda environment

### Test Poetry
1. Create poetry folder like so:
```
poetry new poetry-demo
```
2. Open VS code in that `poetry-demo` folder
3. Repeat steps taken for the the conda environment.

Special note: Poetry is finicky. Make sure the python extension recognizes the poetry environment before proceeding with testing the install parts. For example I have a poetry environment setup in my TestPoetry2 folder that looks like so:

![image](https://user-images.githubusercontent.com/19672699/159312399-335463cb-b328-4b58-be8b-e7eb3eb9986a.png)

The key being it says 'poetry' in the name for the interpreter.

**Comment by IanMatthewHuff** [comment]
- [ ] Notebook conda install
- [ ] Notebook conda cancel
- [ ] Notebook conda switch
- [ ] IW conda install
- [ ] IW conda cancel
- [ ] IW conda switch
- [ ] Repeat for pip
- [ ] Repeat for poetry

**Comment by IanMatthewHuff** [comment]
That was not a fun poetry install process, blech.
