### ISSUE TITLE
Ensure we are prompted to install IPyKernel and it gets installed into the right Environment

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9435]
Refs: https://github.com/microsoft/vscode-jupyter/pull/9358

- [x] anyOS: @IanMatthewHuff  
- [x] anyOS: @rchiodo

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%239435%0A%0A&assignees=DonJayamanne)

---

### Requirements

- Use pre release build of the Jupyter extension.

### Test 1
* Run the following cell in Interactive window against a kernel that doesn't have IPyKernel
```python
import sys
print(sys.executable)
```
* Verify we get the prompt to install IPyKernel
* Click ok and verify the output points to the right environment

### Test 2
* Run the following cell in Interactive window against a kernel that doesn't have IPyKernel
```python
import sys
print(sys.executable)
```
* Verify we get the prompt to install IPyKernel
* Select another kernel that has IPyKernel and verify the kernel changes

### Test 3
* Run the following cell in Interactive window against a kernel that doesn't have IPyKernel
```python
import sys
print(sys.executable)
```
* Verify we get the prompt to install IPyKernel
* Select another kernel that does not have IPyKernel and verify you get a pompt to intall IPyKernel into this new environment.
* Click OK to install IPyKernel and verify the cell is executed against this new kernel and IPyKernel was installed

### Test 4
Same as Test1 with IPynb file

### Test 5
Same as Test2 with IPynb file

### Test 6
Same as Test3 with IPynb file

**Comment by IanMatthewHuff** [comment]
- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
