### ISSUE TITLE
Variables don't refresh when clicking the toolbar button on the interactive window

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9437]
Seems like a recent regression

1. Open notebook
2. Create variable 
3. View it in the variables window
4. Open terminal
5. Open python file with cell
6. Run cell that would create a new variable
7. Click on variables
8. No variables shown

9. Give focus to IW input box
10. Variables start working again

**Comment by IanMatthewHuff** [comment]
Side note, need to click off of the variables window between steps 3 and 4. If the variables window is still up and visible I don't repro the issue, but I do repro if you click to something like output or terminal after step 3.

**Comment by IanMatthewHuff** [comment]
Kinda think this is more a variable view issue versus IW, so assigning myself.

**Comment by amunger** [comment]
not reproducing for me with latest
