### ISSUE TITLE
Creating IW with a bad kernel and hitting cancel on the the ipykernel install allows for execution still

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9444]
Testing #9435

If you cancel the ipykernel install the IW comes up correctly like so:

![image](https://user-images.githubusercontent.com/19672699/159544245-1a67fc21-80ed-4351-ba9f-1e173f16bbea.png)

However you can still send code to it. 

It would be nice if it either
- Prevented sending anymore code
- Brought up the dialog again if you sent it again.

**Comment by DonJayamanne** [comment]
Also see https://github.com/microsoft/vscode-jupyter/issues/9450
