### ISSUE TITLE
The screen flickers when using matplotlib to draw a continuous picture

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9446]
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/9427

<div type='discussions-op-text'>
 Posted by @ZionDoki
<sup>Originally posted by **ZionDoki** March 20, 2022</sup>
I took a reinforcement learning practice course in jupyter in VSCode. 
The code tries to display the pygame screen in jupyter, but the screen flickers in VSCode, and the original Jupyter does not .

![2022-03-21-10-20-52](https://user-images.githubusercontent.com/16078801/159197593-4b79f3c9-d3d9-4250-a586-b6daea92d6df.gif)

``` Python
plt.figure(figsize=(4, 3))
display.clear_output(wait=True)

obs = env.reset()
print("run")
for t in range(TIME_LIMIT):
    plt.gca().clear()
    action = policy(obs, t)  # Call your policy
    # print(action)?
    obs, reward, done, _ = env.step(action)  # Pass the action chosen by the policy to the environment
    # print(reward)
    # We don't do anything with reward here because MountainCar is a very simple environment,
    # and reward is a constant -1. Therefore, your goal is to end the episode as quickly as possible.

    # Draw game image on display.
    plt.imshow(env.render('rgb_array'))
    
    display.clear_output(wait=True)
    display.display(plt.gcf())

    if  done:
        print("Well done!")
        break
else:
    print("Time limit exceeded. Try again.")

display.clear_output(wait=True)
```

Is there any way to fix this?
Thanks!
</div>

**Comment by rchiodo** [comment]
Need to discuss with @rebornix

**Comment by DonJayamanne** [comment]
@ZionDoki Not sure whether we can do anything about this.
The following line is forcing the UI to clear the output (i.e. forcing the output to be empty and we're adding the flag `wait=True` which causes an additional delay of waiting for the UI to get updated to be clear)
`display.clear_output(wait=True)`

As a result of the above wait, the UI will flicker.

**Comment by josiahls** [comment]
Having the same issue, is the solution to compile the video and use a full on object like the ipython video object? My only issue with that is I cant watch the env "live/streaming"
