### ISSUE TITLE
When editing markdown in Jupiter, you cannot insert pictures.

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9447]
Originally posted here by @MuRongKanKan https://github.com/microsoft/vscode-jupyter/discussions/9426

**Comment by rchiodo** [comment]
Needs an upstream issue. VS code has an issue around this.

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/5321
