### ISSUE TITLE
Cancel install for IW now looks a bit odd

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#9450]
Testing #9434

If you cancel ipykernel install for an IW launch it now looks funny compared to the notebook message.

IW:
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/812783/159586672-b9389b4b-7f11-44e3-912e-7622f974912a.png">

Notebook message is much better:
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/812783/159586754-d2e058a8-cefd-4ee8-9d6f-c59a0f08a512.png">

**Comment by DonJayamanne** [comment]
Closing as a dup of https://github.com/microsoft/vscode-jupyter/issues/9444

**Comment by rchiodo** [comment]
/verified

![image](https://user-images.githubusercontent.com/19672699/166500834-d401684a-cc2b-4471-8874-d92f9448e788.png)
