### ISSUE TITLE
Conda install output in the notification is a bit noisy

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#9451]
Testing #9434

Just my opinion here. But there is lots of random info that now pops up in the notification toast when installing.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/812783/159587083-fdfa5437-7113-40e5-91a3-e9d15b77a8cd.png">

On one hand, it's a long process, so the message changing lets you know that progress is being made. But on the other hand, it has some unhelpful messages like above. I think I'd personally rather just have an installing message.

**Comment by IanMatthewHuff** [comment]
If we want to keep it, might be helpful to trim to a set smaller size. It flashes up and down on screen as all the output message have different sizes that size up and down the message box.

**Comment by DonJayamanne** [comment]
Agree, we could just display the first 100 characters.

**Comment by DonJayamanne** [comment]
Weird, these issues are being assigned to Rich, i thought issues created by us (internally) don't get assigned to anyone.

**Comment by IanMatthewHuff** [comment]
@DonJayamanne When I file issues on Test plans there is a link to create an issue linked to the test plan. That link auto assigns the person who created the test plan.

**Comment by IanMatthewHuff** [comment]
One more note on this. I think on the message I'd also like to see the target. Like:

"Installing ipykernel into {myEnvName}: <message"

**Comment by DonJayamanne** [comment]
Suggestion:
* Change title to `"Installing ipykernel into {myEnvName}: "
* Message should be first 50 and last 50 characters (<first 50>..... <trailing 50>`
