### ISSUE TITLE
Clicking on "Run cell" in a Python file appends an empty cell

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode-jupyter#9452]
Testing #9434

- Create an empty Python file in a folder with a virtual environment with ipykernel installed (any type: pip, conda or poetry)
- Add a cell with a `print` statement
- Click on `Run Cell`

Observe that a new empty cell is added at the bottom of the file

https://user-images.githubusercontent.com/51720070/159591945-2a601e94-e4f8-4114-9f95-988d605ac711.mp4

**Comment by rchiodo** [comment]
This is actually by design.

There's a setting to disable this behavior:

![image](https://user-images.githubusercontent.com/19672699/159598258-8e0abffd-16cc-45bf-96e4-1395cb124008.png)

**Comment by rchiodo** [comment]
Seems odd we'd keep adding them though.
