### ISSUE TITLE
Interactive window still says connecting to old kernel even after a switch

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode-jupyter#9454]
Testing #9434

- Create a blank Python file in a folder with 2 environments, one with ipykernel, and one without (any type: pip, conda, poetry)
- Add a cell with a `print` statement
- Select the environment without ipykernel as your initial kernel
- Click on `Run Cell`, select `Change kernel` on the prompt, and pick the environment with ipykernel
- Observe that the text at the top of the interactive window still says `Connecting to <old env name>`

https://user-images.githubusercontent.com/51720070/159592726-a18e2c2f-e46b-453f-9483-6882b1e6d07c.mp4

**Comment by rchiodo** [comment]
Thanks.

I believe this is an issue in the core. The markdown doesn't seem to update. Need to double check.

**Comment by DonJayamanne** [comment]
I'll check, related PR is #9445

**Comment by rchiodo** [comment]
/verified 

It shows the new environment after you switch
