### ISSUE TITLE
Poetry doesn't have a group name in controller selection

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#9456]
Testing #9434

Controller list:
<img width="677" alt="image" src="https://user-images.githubusercontent.com/812783/159594345-628ef791-44cc-4c64-b79a-cf3cfe46f829.png">

Interpreter list:
<img width="653" alt="image" src="https://user-images.githubusercontent.com/812783/159594517-908d48f0-ee6d-4c43-a054-b0375d0c4995.png">

**Comment by DonJayamanne** [comment]
There haven't been any upvotes on this issue, hence closing this for now
