### ISSUE TITLE
How to get jupyter shell to auto scroll to new output?

### ISSUE THREAD

**Issue by moonj94** [microsoft/vscode-jupyter#9469]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I am running some code which outputs a lot of stuff, including figures. However, I have to continually scroll to keep up with the output. I saw some previous threads where this was an issue, but I was unable to find a good solution. Can anyone help?

### VS Code Version

Version: 1.65.2 (user setup) Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1 Date: 2022-03-10T14:33:55.248Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.19043

### Jupyter Extension Version

v2022.2.1030672458

### Coding Language and Runtime Version

3.7.7

### Anaconda Version (if applicable)

conda 4.11.0

### Running Jupyter locally or remotely?

Local

**Comment by IanMatthewHuff** [comment]
@moonj94 quick question here. Do you have the setting Jupyter: Always Scroll On New Cell turned on? That might be what you are looking for here. I wasn't quite sure if you were looking at autoscrolling to new cells, or if you were looking at scrolling within a single cell output. 

If you are looking at scrolling just in single cell output that's an issue that we are looking at resolving, https://github.com/microsoft/vscode-jupyter/issues/8426.

**Comment by moonj94** [comment]
@IanMatthewHuff I do have that setting turned on. I guess I am looking for something that auto-scrolls just in a single cell's output.

**Comment by IanMatthewHuff** [comment]
@moonj94 I'm going to close down this issue in favor of just tracking #8426. Just follow that issue to see progress with fixing this.
