### ISSUE TITLE
Codelens for interactive window show in notebook

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#9474]
## Environment data
- VS Code: Codespace
- Jupyter Extension version (available under the Extensions sidebar): v2022.3.1000851004

<img width="571" alt="image" src="https://user-images.githubusercontent.com/876920/160019920-f358b0bf-00db-40d3-810a-39cb04f4922c.png">

**Comment by DonJayamanne** [comment]
Seems to be caused by changes in VS Code, we can no longer use a Document Filter to exclude notebook document cells.
Seems that all notebook document cells are automatically included

**Comment by IanMatthewHuff** [comment]
Yeah, that was the change I was wondering about. Rich had to update intellisense for that change. I guess we just missed this filter.

**Comment by rchiodo** [comment]
This should be fixed.

**Comment by DonJayamanne** [comment]
Fixed and code has been mereged

**Comment by IanMatthewHuff** [comment]
Verified. Looks good now.
