### ISSUE TITLE
Bokeh output not working only from Interactive Window

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#9479]
![image](https://user-images.githubusercontent.com/812783/160021979-353b1f66-f1bb-4c53-bd67-33cbec8fd121.png)

The bokeh control never loads from the Interactive Window (this is using the bokeh code from manualTestFile.py).

**Comment by DonJayamanne** [comment]
Fixed and needs to be validated

**Comment by IanMatthewHuff** [comment]
![image](https://user-images.githubusercontent.com/812783/165645837-a65e76ed-3175-493a-a930-480524827b12.png)
