### ISSUE TITLE
Very bad experience

### ISSUE THREAD

**Issue by soickm** [microsoft/vscode-jupyter#9489]
While I understand that this is all free and that there are paid alternatives, the latest release of the Jupyter extension has a ton of bugs. I am on v2022.2.1030672458, which appears to be the latest and often VS Code crashes while building some very basic notebooks. I had to fix the JSON by hand after some errant changes were added to it by the extension. 

How do I go about proving a log file or something else that shows the problem so you can address it?

**Comment by amunger** [comment]
You can get the logs from the extension in the output panel, and selecting jupyter from the dropdown, and you can post those here. Although, if VS Code is crashing entirely, you probably won't be able to use that method.
![image](https://user-images.githubusercontent.com/2019016/160158494-ee8007fc-7f82-4eb1-8ba1-42849e0a98d2.png)

If you have a sample notebook that reproduces the issue, that would also be a great help in troubleshooting the issue.

**Comment by amunger** [comment]
> I had to fix the JSON by hand after some errant changes were added to it by the extension.

Do you have the repro steps for how this happened? Or the errant JSON that was added?

**Comment by amunger** [comment]
closing for now as we don't have enough information to troubleshoot this.
