### ISSUE TITLE
Feature request: force notebook to always serialize with an indent.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9491]
@rchiodo , Can open and display it correctly.
Just when looking at the RAW file (Using text editors) it is one liner.

I wonder abut 2 things:
1. How did it happen? Why did VS Code saved it like that?
2. Is there a way to make it save again with all lines separated?

_Originally posted by @RoyiAvital in https://github.com/microsoft/vscode-jupyter/issues/4576#issuecomment-1078680631_

**Comment by RoyiAvital** [comment]
Is there a way to share the file with you in private? If that helps.

**Comment by rchiodo** [comment]
@royiavital, what other extensions do you have installed?

What steps did you take to repro the problem?

For me I did this:

1. File | New File ...
2. Picked 'Jupyter notebook'
3. Added some code to a cell
4. Saved the file
5. Opened with a text editor. I get this;

```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(1)"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

Tried the same thing with 'Create Jupyter Notebook' command from the command palette. Same results.

**Comment by rchiodo** [comment]
Does it repro for you with a new notebook?

**Comment by RoyiAvital** [comment]
I have many files which are fine and doesn't show this issue.
I only have 2 files where it happened. I only saw it on the GIT when pushing.

I only have the Python extension by MS and Spell Right:

![image](https://user-images.githubusercontent.com/7347975/160185964-63edba3a-2694-4dfb-a5dd-473aa0da8530.png)

**Comment by rchiodo** [comment]
Can you try editing one of the two files where it doesn't work and then send me the contents of the 'Help | Toggle Developer Tools' console tab?

It looks like this:

![image](https://user-images.githubusercontent.com/19672699/160192033-5b08eb28-1a0e-43ae-9cbc-5f9632aa6dfa.png)

**Comment by RoyiAvital** [comment]
Wouldn't it be easier if I just send you the files?
If you have an email or something.

If you don't want to put it here, could you send me something to RoyiAvital at yahoo.com? I will send them to you.

**Comment by RoyiAvital** [comment]
I have sent you the files. Let me know you got them.

**Comment by rchiodo** [comment]
Yes. I can repro with your files. Thanks.

**Comment by rchiodo** [comment]
I believe this is by design. It maintains the indent of the original file. If the original file has no indentation, it won't create a new one. 

Was the original file all on one line? If not can you e-mail me the original file? 

If I reformat the ipynb file as a json file with VS code (so it has an indentation on each line of 4 spaces), reopen it as an ipynb, then save it again, it maintains the 4 spacing indentation and multiple lines.

**Comment by RoyiAvital** [comment]
It was 1 liner since I used Git and VS Code on it.
Any way to restore the indention as you described?

Maybe add an option to auto do it on save? As this 1 line mode make it Git unfriendly.

**Comment by rchiodo** [comment]
Reopen the file as a text file, right click and 'Format document'.

![image](https://user-images.githubusercontent.com/19672699/160207881-ff99f4a3-94e3-42f0-b7cd-02e88c66a5a2.png)

The 1 line mode should not have been caused by us. That's the part I'm trying to verify. Do you have the file in git history to see if at some point it wasn't a single line?

**Comment by rchiodo** [comment]
> By the way, it would be also great to have "Save without Output on HD" mode (Git friendly save mode).

I swear we've had this request already, but I can't seem to find it.

**Comment by RoyiAvital** [comment]
@rchiodo , That's not what I meant.
I meant something like [JupyText](https://github.com/mwouts/jupytext).

Namely on the HD I can save automatically a file with the output cleared yet, while I'm on the session, VS Code keeps the output visible (So it has a temp paired file for the output).

The motivation is having a GIT friendly file on the working folder while in VS Code temp cache the output is kept for the current session.

**Comment by DonJayamanne** [comment]
This feature request hasn't received any upvotes since it was created.
We prioritize issues based on populariry (interest, guaged by number of upvotes), 
Closing for now, if anyone feels this is useful, please upvote & comment on this and i'll be happy to re-open this issue or create a new issue.
