### ISSUE TITLE
External Kernel API shouldn't require a notebookDocument to create a kernel

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9495]
Right now our API requires a NotebookDocument to be passed in to create a kernel:

https://github.com/microsoft/vscode-jupyter/blob/e6d86dabc25d9e63b850251b7e5e576dfb86aaea/src/platform/api/extension.d.ts#L281

This is rather limiting and forces callers to create dummy notebook documents. 

We really only need a unique key to make sure we don't create the same kernel more than once.

**Comment by DonJayamanne** [comment]
perhaps we can create a notebook document internally .
i don't want to change our code just to accommodate 3rd parties just yet (feels too early).
using a notebook document is easy so that we can manage the lifetime and the like.

 i totally agree it's not ideal and it is limiting, however if we have more users if the api then i think we should change, else prefer the simplicity it offers.

**Comment by rchiodo** [comment]
The problem right now is that the notebook document (unless it's shown) seems to auto dispose itself. Which in turn kills the kernel.

**Comment by rchiodo** [comment]
Maybe internally we can create a dummy notebook that is just the same interface but not actually backed by anything. In fact I bet @pwang347 could try that.

**Comment by DonJayamanne** [comment]
> backed by anything. In fact I bet @pwang347 could try that.

that's exactly the code sample i provided (provided that some time ago with a sample to use this api). you can create an ipynb notebook easily today.

**Comment by rchiodo** [comment]
Is the sample still available? Maybe we should link to it in the doc for the api?

**Comment by pwang347** [comment]
@rchiodo @DonJayamanne I can confirm that a dummy class implementing the interface works
![image](https://user-images.githubusercontent.com/8560030/160214879-4e02a360-4ac9-42c2-869a-0327750aea1a.png)

**Comment by rchiodo** [comment]
Power tools extension verifies this is true.

/verified
