### ISSUE TITLE
Autocomplete lacks parity with standard jupyter server

### ISSUE THREAD

**Issue by astrowonk** [microsoft/vscode-jupyter#9496]
Issue Type: <b>Bug</b>

I opened this in #6979 which was closed, but autocomplete still doesn't work as well as in a standard jupyter notebook in a browser. Tab-complete should work with file names inside say, opening a csv:

```pd.read_csv(" ```

but this does nothing for me at the moment. Hiting tab after opening the quote just produces whitespace.

Similarly subscriptable objects with strings don't properly autocomplete. A dataframe:

```df[" ```

Should expose its columns on tab in that situation. It is not doing that for me now. Custom classes can define `_ipython_key_completions` which I use extensively too. Even dictionaries, the tab key is producing white space. 

EDITED with video:

https://user-images.githubusercontent.com/13702392/160241187-bac0977e-84d7-41b6-84ba-ac9ee856b161.mov

Extension version: 2022.2.1030672458
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:42:05.236Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id 68686b81-af00-4876-bfbb-a517c41c7bb9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvid1:30447480
pynewfile477:30450038

```

</details>

**Comment by amunger** [comment]
It looks like https://github.com/microsoft/vscode-jupyter/issues/8983 covers the same issue. There's a lot of chatter there, but https://github.com/microsoft/vscode-jupyter/issues/8983#issuecomment-1045050402 summarizes it well
