### ISSUE TITLE
Output messages sent from widgets not displayed in cell output

### ISSUE THREAD

**Issue by AoifeHughes** [microsoft/vscode-jupyter#9503]
Hi, 

My system:

``` bash
Version: 1.65.2 (Universal)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```

``` bash
 ➜  ~ python --version
Python 3.10.0
 ➜  ~ jupyter --version
Selected Jupyter core packages...
IPython          : 8.0.1
ipykernel        : 6.9.0
ipywidgets       : 7.7.0
jupyter_client   : 7.1.2
jupyter_core     : 4.9.1
jupyter_server   : not installed
jupyterlab       : not installed
nbclient         : 0.5.13
nbconvert        : 6.4.4
nbformat         : 5.2.0
notebook         : 6.4.10
qtconsole        : 5.2.2
traitlets        : 5.1.1
```

Similar issues: 
- https://github.com/microsoft/vscode-jupyter/issues/3767
- https://github.com/jupyter-widgets/ipywidgets/issues/2512

Code used: 

``` python
from IPython.display import display
from ipywidgets import widgets, interactive
button = widgets.Button(description="Run!")
def on_button_clicked(b):
    print('Clicked')
display(button)
button.on_click(on_button_clicked)
```

In Jupyter Web interface this works perfectly. In VScode it does nothing. 

However, the example give here https://github.com/microsoft/vscode-jupyter/issues/3767#issuecomment-625555606 works just fine. So it seems that they only work with decorators? 

I tested this using:

``` python
from IPython.display import display
from ipywidgets import widgets, interactive, interact
button = widgets.Button(description="Run!")
@interact(b=[0,1])
def on_button_clicked(b):
    if b ==1:
        print('Clicked')
``` 

This seemed to work fine. A bit of a hacky workaround, particularly as decorators don't seem to have a method for buttons...

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, I can replicate this at my end, Will try to dig into the issue and see whats causing this.

**Comment by DonJayamanne** [comment]
Took a while to figure out the issue, its a bug at our end.
Difficult to explain but we'll need to:
* Track the comm id associated with the widget displayed
* When messages of type `stream` come back and found to be associated with the previous commid, we'll need to append these output to the corresponding cell output.
