### ISSUE TITLE
Notebooks - Kernel Not Saved

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#9512]
- VS Code Version: 1.63.2
- OS Version: Windows 11 

Steps to Reproduce:

1. Create notebook
2. Select kernel and write code/run cells
3. Save notebook
4. Kernel selection disappears

I started working on an analysis and when I got to a checkpoint I was happy with I saved the notebook. After saving I tried to keep working and started getting errors in my notebook and it took me a few minutes to realize the kernel was not saved so I had to select it again and rerun everything to get back to where I was, a pretty annoying papercut

**Comment by DonJayamanne** [comment]
As discussed, labelling as upstream vscode, as the kernel selection is maintained in vscode core and the selected kernel needs to be transitioned upon saving as another file.

**Comment by DonJayamanne** [comment]
This should be fixed now, closing this for verification
