### ISSUE TITLE
Can't enter the url of a local jupyter server

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#952]
@LeonardoGentile commented on [Sun Nov 01 2020](https://github.com/microsoft/vscode-python/issues/14590)

## Environment data

-   VS Code version: 1.50.1
-   Extension version (available under the Extensions sidebar): v2020.10.332292344
-   OS and version: OSX 10.14.6 
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda (python 3.7.4)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: Microsoft

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour
In a jupyter notebook the extension asks me to enter the url of an already running server.
The input box should accept the pasted value

## Actual behaviour
I can paste this value but nothing happens on Enter.
The input box remains open, the pasted url still there and nothing happens. 
My only option is to hit Esc and close the input.

![image](https://user-images.githubusercontent.com/412061/97823058-1a8de880-1cb8-11eb-9aff-384b5c926134.png)

---

@LeonardoGentile commented on [Mon Nov 02 2020](https://github.com/microsoft/vscode-python/issues/14590#issuecomment-720618099)

i would add the the standard `cmd-v`command to paste text doesn't work in this input box. Right click and select 'paste' does work. Still Enter does not work so there is no way to confirm this choice

---

@DavidKutu commented on [Tue Nov 03 2020](https://github.com/microsoft/vscode-python/issues/14590#issuecomment-721303122)

Thanks for reporting the issue @LeonardoGentile. I was unable to reproduce this on Windows, both ctrl+v worked and the extension asked me to reload after pressing enter, and then successfully connected to the server.

@DonJayamanne, @IanMatthewHuff, could you help me by trying to repro this on a mac?

---

@DonJayamanne commented on [Wed Nov 04 2020](https://github.com/microsoft/vscode-python/issues/14590#issuecomment-722016895)

Hitting `Enter` does work for me & I can hit `cmd+v` as well.

---

@LeonardoGentile commented on [Wed Nov 04 2020](https://github.com/microsoft/vscode-python/issues/14590#issuecomment-722030909)

I've tried to restart multiple times and I can still reproduce it.
I'm also unable to paste the url using standard `cmd-v`, I have to right click and select paste.

---

@greazer commented on [Thu Nov 05 2020](https://github.com/microsoft/vscode-python/issues/14590#issuecomment-722720328)

@LeonardoGentile, can you try pasting something inside Cmd-shift-p, and see if you can paste a string in that? We're suspecting a problem out of the control of the Python extension. 

---

@LeonardoGentile commented on [Thu Nov 05 2020](https://github.com/microsoft/vscode-python/issues/14590#issuecomment-722746540)

@greazer I'm normally able to paste inside the command input.

Not sure if related but this also happens when editing a notebook. 
1) I bring on the command input or the goto input 
2) I close the input
3) I can't edit / interact with the notebook using the keyboard unless I click on something on the notebook

The same happen the other way, that is, when I close the command input I **can't** reopen it anymore with keyboard shortcut unless I first click on something on the notebook.
This behavior never happened with other kind of files.

So probably something similar is happening related to my initial problem, that is, when running a notebook, somehow the focus is stolen by something inside the notebook

---

@LeonardoGentile commented on [Mon Nov 09 2020](https://github.com/microsoft/vscode-python/issues/14590#issuecomment-724390433)

Is there anything else I can do to deubg this?

---

@DavidKutu commented on [Tue Nov 10 2020](https://github.com/microsoft/vscode-python/issues/14590#issuecomment-725090197)

Hey @LeonardoGentile, we think the `cmd+v` is either a vscode issue or its somehow related to your computer. To make sure I'd try  to test that on vscode insiders, or try reinstalling vscode.

As for the url not entering, I just noticed that what you're showing on your image is our default url. Could you share the url you're trying to input? (you can omit part of the token if you want)

**Comment by LeonardoGentile** [comment]
@DavidKutu I've tried vscode insider, it works there but the interface and extension look quite different.

This is my external url
![image](https://user-images.githubusercontent.com/412061/98879461-e4095800-2485-11eb-87cd-f0cd898bcdff.png)

**Comment by DavidKutu** [comment]
@LeonardoGentile that means your issue got fixed. We just had a release today, so if you update the python extension (and download the jupyter extension) back on VS code stable, you should get the fix.

That interface you see is in preview only for insiders, its a native notebook and its way faster. We'll eventually make it the default, but feel free to try it out in insiders.

Let me know if the issue persists on stable.

**Comment by LeonardoGentile** [comment]
@DavidKutu I've updated to 1.51.1 but problem persists in unpredictable way, sometimes the `cmd-v` works, sometimes not, as well the `return`. 
I can't say it's fixed on this version

**Comment by DavidKutu** [comment]
@LeonardoGentile did you update your python and jupyter extensions?
What versions are you using now?

They should both be 2020.11.xxxxx

**Comment by LeonardoGentile** [comment]
I've set automatic updates so yes:
- Python v2020.11.358366026
- Jupyter v2020.11.358541065

**Comment by DavidKutu** [comment]
That's weird that it works on insiders but not on stable, and your versions are fine.
So far what we can recommend you do is either of these:

- Continue your work on insiders, when we have another release, those changes will be on stable, your issue should be solved and you should be able to go back to stable.
- That first option should've already happened. That leads me to think that maybe something is wrong with your installation of vscode (maybe electron). To check this I'd like to ask you to install those specific versions you shared in insiders. If the issue is gone, then we should try to uninstall and reinstall vscode stable. And if the issue persists, we know those versions have your issue and it should be fixed next release, and in the mean time you can use the most recent version in insiders.

Please let me know if this helps.

**Comment by DavidKutu** [comment]
@LeonardoGentile please follow vscode's issue 110528.
