### ISSUE TITLE
about vscode jupyter notebook

### ISSUE THREAD

**Issue by GuiQuQu** [microsoft/vscode-jupyter#9520]
I want stop one cell running in jupyter notebook in vscode and not stop the all jupyter kernel , but I do not find a button to do this.and I get  double-i can stop the running cell ,but in vscode it`s useless.

**Comment by rchiodo** [comment]
Thanks for the issue. There are multiple ways to stop a cell:

The stop button on a cell:

![image](https://user-images.githubusercontent.com/19672699/160666593-86ca9339-6bdb-4eaa-942c-49a6f1764cc9.png)

The interrupt button on the top toolbar:

![image](https://user-images.githubusercontent.com/19672699/160666663-780a8d30-f749-48fb-8765-62696ec95859.png)

Are you saying these don't work? Kernels aren't always guaranteed to allow an interrupt. It all depends upon what your code is doing.

**Comment by GuiQuQu** [comment]
Thank your answer, I just don't find the button of stopping a cell&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode-jupyter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月30日(星期三) 凌晨1:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode-jupyter] about vscode jupyter notebook (Issue #9520)





 
Thanks for the issue. There are multiple ways to stop a cell:
 
The stop button on a cell:
 

 
The interrupt button on the top toolbar:
 

 
Are you saying these don't work? Kernels aren't always guaranteed to allow an interrupt. It all depends upon what your code is doing.
