### ISSUE TITLE
Update package-lock.json

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#9522]
Something is off with it since the node update. Fix it up but make sure build VSIX step is working.

**Comment by IanMatthewHuff** [comment]
When I fully cleared out node_modules and deleted package-lock.json I'm having lots of issues installing. Seems to be peer dependencies, mostly around react 16 / 17. NPM install actually fails here.

**Comment by IanMatthewHuff** [comment]
Forgot to link the pull. Updated with this: https://github.com/microsoft/vscode-jupyter/pull/9535

**Comment by connor4312** [comment]
Verified I could install with `npm ci` and then `npm run compile` without errors
