### ISSUE TITLE
Can't enter the url of a local jupyter server

### ISSUE THREAD

**Issue by LeonardoGentile** [microsoft/vscode-jupyter#953]
## Environment data

-   VS Code version: 1.50.1
-   Extension version (available under the Extensions sidebar): v2020.10.332292344
-   OS and version: OSX 10.14.6 
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda (python 3.7.4)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: Microsoft

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour
In a jupyter notebook the extension asks me to enter the url of an already running server.
The input box should accept the pasted value

## Actual behaviour
I can paste this value but nothing happens on Enter.
The input box remains open, the pasted url still there and nothing happens. 
My only option is to hit Esc and close the input.

![image](https://user-images.githubusercontent.com/412061/97823058-1a8de880-1cb8-11eb-9aff-384b5c926134.png)

**Comment by DavidKutu** [comment]
Issue moved to [microsoft/vscode #110528](https://github.com/microsoft/vscode/issues/110528) via [**ZenHub**](https://www.zenhub.com/)

**Comment by DavidKutu** [comment]
Hey @LeonardoGentile, if you're still seeing this issue, please let us know on [microsoft/vscode #110528](https://github.com/microsoft/vscode/issues/110528)
