### ISSUE TITLE
Running java cell using Ganymede kernel does not complete

### ISSUE THREAD

**Issue by taisbak** [microsoft/vscode-jupyter#9530]
## Environment data

-   VS Code version: 
          Version: 1.66.0-insider (user setup)
          Commit: 521a3d858570ebc9ce9d5602802f4525a02e045c
          Date: 2022-03-29T07:31:54.286Z
          Electron: 17.2.0
          Chromium: 98.0.4758.109
          Node.js: 16.13.0
          V8: 9.8.177.11-electron.0
          OS: Windows_NT x64 10.0.19042

-   Jupyter Extension version (available under the Extensions sidebar): v2022.4.100090100
-   Python Extension version (available under the Extensions sidebar): v2022.5.10881003
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.19042
-   Python and/or Anaconda version: Python 3.10,0. Anaconda 4.12.0
-   Type of virtual environment used:  N/A
-   Jupyter server running: Local
-   Java version
          openjdk version "17.0.2" 2022-01-18
          OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
          OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

## Expected behaviour

Run notebook cell and display output

## Actual behaviour

Starts running, but never completes

## Steps to reproduce:

Download and install Ganymede kernel from [https://github.com/allen-ball/ganymede](url).
(The Ganymede kernel works with JupyterLab.)

In VSCode:
- create new Jupyter notebook
- choose Java as cell language
- choose Ganymede as kernel
- write simple Java statement: System.out.println("hi");
- run cell
-> it keeps running forever...

Output indicates that the kernel gets started by VSCode and is ready for work - but apparently never receives any.

BTW, other Java kernels work well with VSCode, e.g., IJava [https://github.com/SpencerPark/IJava](url) 

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>
Output attached as a file because it's too large for inline:

[JupyterOutput.txt](https://github.com/microsoft/vscode-jupyter/files/8378138/JupyterOutput.txt)

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the issue.

I haven't tried it yet but my initial guess is this:

```
erbose 08:40:00: Did not get a response for requestKernelInfo
Warn 08:40:00: Didn't get response for requestKernelInfo after 3003ms.
```

This likely means the ganymede kernel isn't handling the [request kernel info](https://jupyter-client.readthedocs.io/en/stable/messaging.html#kernel-info) message (or it's requiring something in the parameters that we're not passing)

**Comment by rchiodo** [comment]
Ah the root cause is that the ganymede kernel never returns session status. Jupyter works fine in this scenario but we currently require it. 
https://github.com/microsoft/vscode-jupyter/blob/308bce616d06bacf5f2df4312453cc457c36815d/src/kernels/common/baseJupyterSession.node.ts#L304

The connectionStatus says 'connected' so maybe we can just use that instead of the kernel status (like we do for remote kernels)

**Comment by taisbak** [comment]
Brilliant - the change solved the problem.
Thank you for the quick response.
