### ISSUE TITLE
If IW cell ends in assignment, print value

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9536]
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/9533

<div type='discussions-op-text'>

<sup>Originally posted by **janosh** March 30, 2022</sup>
Would be a nice feature to have the IW print variables if the last line in a cell was an assignment. Essentially replicate the behavior of

```py
# %%
(x := 5)
>>> 5
```

without needing to use the walrus operator.

In dataframe manipulation it's often helpful to verify results before proceeding. Currently this requires code like this:

```py
# %%
import pandas as pd


df = pd._testing.makeMixedDataFrame()
df

>>>  | A | B | C | D
-- | -- | -- | -- | --
0.0 | 0.0 | foo1 | 2009-01-01
1.0 | 1.0 | foo2 | 2009-01-02
2.0 | 0.0 | foo3 | 2009-01-05
3.0 | 1.0 | foo4 | 2009-01-06
4.0 | 0.0 | foo5 | 2009-01-07

# %%
df_sum = df[["A", "B"]].sum()
df_sum

A    10.0
B     2.0
dtype: float64
```

Writing just this but getting the same output would be much better.

```py
# %%
import pandas as pd


df = pd._testing.makeMixedDataFrame()

# %%
df_sum = df[["A", "B"]].sum()
```</div>

**Comment by DonJayamanne** [comment]
I don' think we should add this, as this is functionality that should exist in IPYthon kernel, and not a custom implemetattion, e.g. if you run the code `value = 1234` in a jupyter notebook cell, then the value of `value` is not printed out, hence we why would one expect anything different in IW, 

Besides no one has asked for this, 

Note: This falls into execution of code against the kernel, hence not specific to IW or the like. & even if it was to be specific to IW, we'd have to write code in the kernel layer.

Closing as there haven't been any upvotes on this feature.
