### ISSUE TITLE
Editor becomes unresponsive and slow after few minutes

### ISSUE THREAD

**Issue by mapio** [microsoft/vscode-jupyter#9542]
Issue Type: <b>Performance Issue</b>

Open a Jupyter Notebook, after few minutes the editor slow down eating all the cpu (and filling the log files).

Extension version: 2022.2.1030672458
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.13.0-39-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|31.15GB (12.10GB free)|
|Process Argv|--verbose . --enable-proposed-api genuitecllc.codetogether --crash-reporter-id b7a8e658-5841-410c-b238-68977988cc60|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	   191	 16059	code main
    0	    32	 16062	   zygote
    0	   128	 16094	     gpu-process
    0	    32	 16063	   zygote
    0	     0	 16065	     zygote
    0	   128	 16235	       window (undefined)
    0	    64	 25399	       issue-reporter
    0	    32	 16106	   utility-network-service
   15	  1021	 16122	   window (● MergeExperiments.ipynb - mass-match - Visual Studio Code)
    2	   447	 16145	   extensionHost
    0	    96	 16285	     /usr/share/code/code --ms-enable-electron-run-as-node /home/santini/.vscode/extensions/ms-python.vscode-pylance-2022.3.4/dist/server.bundle.js --cancellationReceive=file:9b222e972ace3452a5129ace741c69fcfa5ccf0ac5 --node-ipc --clientProcessId=16145
    0	   255	 16296	     /usr/share/code/code --ms-enable-electron-run-as-node /home/santini/.vscode/extensions/ms-python.vscode-pylance-2022.3.4/dist/server.bundle.js --cancellationReceive=file:17ab41539c71b44ad99ada987417066175193234c0 --node-ipc --clientProcessId=16145
    0	   415	 16497	     electron_node cChUxTSLrinx.js 
    7	   191	 16531	     /usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=16145
    5	   287	 16631	     /usr/share/code/code --ms-enable-electron-run-as-node /home/santini/.vscode/extensions/ms-python.vscode-pylance-2022.3.4/dist/server.bundle.js --cancellationReceive=file:64c6d7356ab68093ada685e91cd688af4fba9110d2 --node-ipc --clientProcessId=16145
    0	   159	 16190	   shared-process
    0	    64	 16207	     ptyHost
    0	    64	 16256	     fileWatcher
    0	     0	 25418	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 25419	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● MergeExperiments.ipynb - mass-match - Visual Studio Code)
|    Folder (mass-match): 5 files
|      File types: ipynb(3) txt(1) py(1)
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvidc:30447482
pynewfile477:30463512

```

</details>

**Comment by mapio** [comment]
Here is a screenshot of the `top` command (only one VS Code window open).

![image](https://user-images.githubusercontent.com/612826/161086335-37b5ae1f-9f10-42dd-9006-aaa7fa7f27cd.png)

**Comment by IanMatthewHuff** [comment]
@mapio Thanks for filing the issue. Could you check something quick? Could you disable the Jupyter extension, reload the window and try the same thing? Just trying to isolate the issue a bit better.

**Comment by IanMatthewHuff** [comment]
As a quick note, there was just a recent stable vscode release that had a leak fix in it for notebooks. Might be good to check for an update and seeing if the issue still repros.

**Comment by mapio** [comment]
Sorry for the delay (we are in so different time zones). I've tried but it's very hard to tell since deactivating the extension makes it impossible to work with the notebook. Just opening the window and leaving it open for a while seems not to trigger the problem. Usually the CPU spikes after a while I actually edit the file…

**Comment by mapio** [comment]
> Could you disable the Jupyter extension, reload the window and try the same thing?

Sorry for the delay (we are in so different time zones). I've tried but it's very hard to tell since deactivating the extension makes it impossible to work with the notebook. Just opening the window and leaving it open for a while seems not to trigger the problem. Usually the CPU spikes after a while I actually edit the file…

**Comment by mapio** [comment]
> Might be good to check for an update and seeing if the issue still repros.

Unfortunately the problem persists even with version 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5/x64).

**Comment by mapio** [comment]
I'm not sure where this comes from. Here is the situation

![image](https://user-images.githubusercontent.com/612826/161490724-4d3e64e6-c56e-4144-a2bc-dc24b6c5cc2e.png)

the bug is making the editor unusable. I like vscode so much that I'm promoting it with all the students and colleagues I meet; this time though, I'm about to abandon it unless until the bug is fixed.

I'm more than willing to provide any info (dump, logs…). Tell me what is needed and I'll try to comply.

It's very hard, on the other hand, to provide a minimum viable reproducibility test case, due to the fact that the problem arises, albeit regularly, after few tens of minutes of work on large files.

I've reported some other information here https://github.com/microsoft/pylance-release/issues/2530

**Comment by IanMatthewHuff** [comment]
@mapio Per this comment here: https://github.com/microsoft/pylance-release/issues/2530#issuecomment-1088395470

I'm going to close this bug as it looks best addressed by the pylance team. If it's not a pylance specific issue just comment back here and I can reactivate.
