### ISSUE TITLE
built-in module override message has bad path on Windows

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#9560]
The unit test `Unable to import <name> from user overriding module in workspace folder (windows)` is currently failing after re-enabling it and confirmed the message in insiders:
![image](https://user-images.githubusercontent.com/2019016/161350174-ff240ed5-f9d0-4357-bc84-8b4df5c0fd5d.png)

**Comment by DonJayamanne** [comment]
Caused by path-browserify, [we shouldn't be using that directlry in code.](https://github.com/microsoft/vscode-jupyter/issues/new?assignees=&labels=bug&template=1_bug_report.md)

**Comment by DonJayamanne** [comment]
Test is not failing anymore.
