### ISSUE TITLE
Calling Buffer constructor directly is deprecated

### ISSUE THREAD

**Issue by caphosra** [microsoft/vscode-jupyter#9562]
It seems that this project uses Buffer constructor on these two lines:

https://github.com/microsoft/vscode-jupyter/blob/e07a7673f29076d7f5424b7e753308ec1ce161a4/src/platform/debugger/extension/helpers/protocolParser.node.ts#L31

https://github.com/microsoft/vscode-jupyter/blob/e07a7673f29076d7f5424b7e753308ec1ce161a4/src/webviews/extension-side/plotting/plotViewer.node.ts#L145-L148

According to [the nodejs document](https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/), we should use `Buffer.from()` or `Buffer.alloc()` instead of `new Buffer(...)`.
I think it would be better if we replace it.
> The Buffer() and new Buffer() constructors are not recommended for use due to security and usability concerns. Please use the new Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() construction methods instead.

## Screenshot

<img width="553" alt="Screen Shot 2022-04-02 at 20 19 32" src="https://user-images.githubusercontent.com/28725713/161380800-f6f4792f-0fad-4b3b-b30f-47e5517bff4c.png">

**Comment by amunger** [comment]
Thanks for creating this - it would be great to cut down on the errors we see in the console.
