### ISSUE TITLE
Add setting (other than .env) to append PYTHONPATH to kernel process

### ISSUE THREAD

**Issue by YoniChechik** [microsoft/vscode-jupyter#9564]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

 Altough launch config exists, the PYTHONPATH is not added.
``` 
"launch": {
    "configurations": [
      {
        ...
        "cwd": "${fileDirname}",
        "windows": {
          "env": {
            "PYTHONPATH": "${fileWorkspaceFolder};${env:PYTHONPATH}"
          }
```

I know of the solution for .env files but this does not scale for multiple projects and is a specific file only to use jupyter-vscode which is not a great thing to add to a github repo with multiple users... I wish there was a way to add it to the configurations diractly. something like:
```
"jupyter.PYTHONPATH": "${fileWorkspaceFolder};${env:PYTHONPATH}"
```

Thanks for the great work :)

### VS Code Version

latest

### Jupyter Extension Version

latest

**Comment by DonJayamanne** [comment]
thanks for filling this issue, however i don't quite understand the feature. request here.

* are saying that the PYTHONPATH in launch. json config is not used in jupyter?
* if so, is this issue specific to interactive window or notebook or both
* does the issue relate to debugging or regular execution of cells?

**Comment by YoniChechik** [comment]
> - are saying that the PYTHONPATH in launch. json config is not used in jupyter?

Yes.

> - if so, is this issue specific to interactive window or notebook or both

Both

> - does the issue relate to debugging or regular execution of cells?

Both

> please note, when adding PYTHONPATH in . env files you can also use relative paths. would that address your requirements?

I wish to avoid the use of .env alltogether. Specifically your solution is only valid for vscode so this can be problematic to add to projects.

> don't quite understand this. today the current working directory is already in the current path.

The example I've added was just a dummy example. for a more complex project where you wish to add other directories to the PYTHONPATH (e.g.: ${fileWorkspaceFolder}/src) this will have a problem.

**Comment by DonJayamanne** [comment]
Unfortunately we haven't had enough upvotes to warrant adding such a change (feature) into the extension, hence closing this issue

**Comment by DonJayamanne** [comment]
> sorry if this is the wrong place to ask.

Please could you for a new issue with details of the issue

**Comment by ndricca** [comment]
I have no issue. I come from PyCharm where I can simply right-click on a folder and mark a directory as source root (i.e. add that folder to `PYTHONPATH`).
I have already solved editing my user `settings.json` but it looks more like a workaround. Any plans for a new feature to simplify this?

```
{
...
    "jupyter.runStartupCommands": [
        "%load_ext autoreload",
        "%autoreload 2",
        "import os, sys; sys.path.append('./src')  if os.path.isdir('./src') else ''"
        ]  
}
```

**Comment by DonJayamanne** [comment]
> rkaround. Any plans for a new feature to simplify this?

As mentioned, please file an issue, and if there are sufficient upvotes for such feature requestes, then we'll consider adding it.
