### ISSUE TITLE
How to export ipynb to html with R kernel?

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9571]
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/9565

<div type='discussions-op-text'>

<sup>Originally posted by **amssljc** April  3, 2022</sup>
I can export my ipynb as .py .pdf. .html document with python kernel. But when I try to use R kernel, there is no this option "export"? I want to know what I can do? Or is it a bug??</div>

**Comment by amssljc** [comment]
@DonJayamanne  Thank you for your reply! Another question, when I use R kernel, there is no  variables defined in "jupyter" terminal. But when I use python, there are. Maybe you haven't been implement this feature? It will be awesome if I can see check variables in "jupyter" terminal. Expect its update! Appreciate!

**Comment by DonJayamanne** [comment]
We should display the command for all of the Jupyter extension kernels

**Comment by mertgoksel** [comment]
This issue is closed but i still cannot export with R kernel. This is the sole reason im still using jupyter lab.
