### ISSUE TITLE
Support remote Jupyter server URI connections in a web enabled Jupyter extension

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9574]
Add support for remote kernels into a web enabled jupyter extension.

Here's the tasks involved:
- [x] #9599
- [x] #9662
- [x] #9689
- [x] #9663
- [x] #9754
- [x] #9717
- [x] #9664
- [ ] #9665
- [x] #9765
- [x] #9973 
- [x] #9974
- [ ] #9976 
- [x] #9977
- [x] #9984
- [x] #9996

**Comment by rchiodo** [comment]
Here's the tasks involved:
- URI conversion for all paths
- NotebookController working in web
- Remote juptyer kernels working in web
- Variable Explorer working in web
- Data Frame viewer working in web

**Comment by IanMatthewHuff** [comment]
Debug tasks:
#9973 
#9974

**Comment by rchiodo** [comment]
I'm not sure we can do #9974. Not without redesigning how we do interactive debugging? It would have to change to work like notebook debugging.

**Comment by IanMatthewHuff** [comment]
@rchiodo Jim asked that I still do an issue to document and track it. But yeah, I'm assuming that I'm only working on 9973.

**Comment by DonJayamanne** [comment]
Closing this as completed, as ther'es only one issue remaining and we have that assigned to Ian
