### ISSUE TITLE
When I use shift + enter to open an interactive window, I automatically select the tab of the interactive window

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode-jupyter#9576]
As the title says, I want to be able to use the shortcut key to open the interactive window and automatically jump to the tab of the interactive window instead of staying on the code file.

Actual use：
![image](https://user-images.githubusercontent.com/100815370/161220839-96aa52e8-adc7-432a-8afc-092c1efadd65.png)

Expect :
![image](https://user-images.githubusercontent.com/100815370/161220962-baa25d4a-651e-4888-8763-a53a17cd8868.png)

**Comment by DonJayamanne** [comment]
This is by design
