### ISSUE TITLE
`Select Interpreter to start Jupyter Server` always prompts for required packages

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#9582]
running the command will always either prompt to install pip/notebook packages, or hit an error that pip does not exist in the environment, even if that interpreter is perfectly capable of running cells in jupyter.

**Comment by DonJayamanne** [comment]
@amunger do you know what's wrong, I.e. why do we prompt the user to install pip and the like?

**Comment by DonJayamanne** [comment]
**TODO:**
Remove this command from the command palette.

**Comment by amunger** [comment]
I had some confusion about Jupyter servers vs kernels - the interpreter that I had selected for a kernel was able to run cells, but the interpreter where Jupyter is installed is independent of that, and the one I was trying to use just didn't have pip installed.

We will also likely keep the command for now since it can be useful for non-raw kernel scenarios.
