### ISSUE TITLE
Port kernel extension API to web

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9585]
Web extensions will likely need support for the kernel API too

**Comment by rchiodo** [comment]
Here's the current api:
https://github.com/microsoft/vscode-jupyter/blob/dfdfd123bf901d986650bc943f879b3091413153/src/platform/api/extension.d.ts#L247

**Comment by DonJayamanne** [comment]
> Web extensions will likely need support for the kernel API too

Yup, that's how I've built the powertoys extension. I.e. with the plan we will web-enable that extension as well.

**Comment by lostintangent** [comment]
Would this API enable an extension to provision a remote Jupyter kernel (e.g. within a GitHub Codespace), and then provide the server URL, so that the Jupyter extension could handle the communication between VS Code and Jupyter?

**Comment by DonJayamanne** [comment]
>  extension to provision a remote Jupyter kernel

No, at this stage there's no such plan for this extension to provision Jupyter. 
This API merely provides a 3rd party extension to communicate with existing kernels.

I believe something similar is being addressed in the VS Code iteration plan here [Explore support for proxy controllers](https://github.com/microsoft/vscode/issues/146672)

**Comment by rchiodo** [comment]
No actually that would be something different.  @lostintangent it sounds like you want something like so?

```typescript
export interface IJupyterExtension {
   provideServerUri(uri: URI);
}
```

That would be the same as the user picking a remote server in the jupyter extension today? Maybe we could handle that with the current command we already have. In fact a user added that extensibility already:

https://github.com/microsoft/vscode-jupyter/commit/f9329d60f3bd07b350e64c53538c4648063da01b

Essentially another extension just executes a command to set a jupyter server URI.

**Comment by lostintangent** [comment]
Yep, something like what you mentioned should work well! That way, we could register the kernel controllers with VS Code, and when selected, provision the Codespace compute, start up Jupyter on it, and then automate connecting the Jupyter client to it.
