### ISSUE TITLE
For avoidable kernel crashes (such as Tenserflow misconfiguration) add user guidance to the kernel crash output

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9588]
* Add message in output indicating the fact that incorrectly installed package (tensorflow or similar package) could be the cause for the failure
* Add a link to a wiki with more info 
* Wiki to contain instructions to circumvent this issue (properly install tensorflow)

**Comment by DonJayamanne** [comment]
Fixed with https://github.com/microsoft/vscode-jupyter/pull/9587

**Comment by rchiodo** [comment]
@DonJayamanne do you have any verification steps for this issue? How do I setup tensorflow to not run?

**Comment by DonJayamanne** [comment]
Run a cell with the following code (cause the kernel to crash)
```python
import IPython
app = IPython.Application.instance()
app.kernel.do_shutdown(True)
```

Output should contrain a link to wiki as follows:
![Uploading Screen Shot 2022-05-04 at 06.02.31.png…]()
