### ISSUE TITLE
Do not include events into package.json

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9596]
Came across this while working on the PR https://github.com/microsoft/vscode-jupyter/pull/9592
(had to port the changes to package.json itno another branch).

Found that `events` has been added into package.json, to my knowledge this isn't necessary & webpack already has events and pulls that by itself. Can confirm that to be the case, i.e. based on the docs we don't need this https://www.npmjs.com/package/events

/cc @rchiodo

**Comment by rchiodo** [comment]
Building it after my webpack change should see if it's necessary or not. I thought I had to add it because webpack build failed.

**Comment by DonJayamanne** [comment]
No worries, as mentioned I noticed that when manually merging the package.json changes in a PR.
