### ISSUE TITLE
Consider removing extensions to prototypes of base types in favor of custom functions

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode-jupyter#9607]
See https://github.com/microsoft/vscode-python/issues/18871.

We can either convert them to functions, or the rename the names so they're unique enough: https://github.com/microsoft/vscode-python/pull/18870

**Comment by DonJayamanne** [comment]
I'm totally in favor of removing such magic.

**Comment by DonJayamanne** [comment]
This has been completed
