### ISSUE TITLE
Review Kernel Crash WIKI

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9609]
https://github.com/microsoft/vscode-jupyter/wiki/Kernel-crashes

**Comment by rchiodo** [comment]
For all of the links, I'm not sure which one to pick? It would stink to have to look at each link to determine what to do. 

Perhaps we can add a clause after each link saying what indicates you have a specific problem.

**Comment by DonJayamanne** [comment]
Closing this for now, as the wiki has been out for a while
