### ISSUE TITLE
Unable to start Kernel due to connection timeout

### ISSUE THREAD

**Issue by SeiteBroken** [microsoft/vscode-jupyter#9621]
## Environment data

-   VS Code version: 1.66
-   Jupyter Extension version (available under the Extensions sidebar): v2022.3.1000901801
-   Python Extension version (available under the Extensions sidebar): v2022.4.0
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: Python 3.10.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

Should start the Kernel

## Actual behaviour

Does not

## Logs
Warn 07:48:43: Kernel Error [s [Error]: Unable to start Kernel 'test (Python 3.10.2)' due to connection timeout. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at c:\Users\benni\.vscode\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:513299
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async x.launch (c:\Users\benni\.vscode\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:513370)] {
  category: 'timeout',
  kernelConnectionMetadata: {
    kind: 'startUsingLocalKernelSpec',
    kernelSpec: {
      specFile: 'C:\\Users\\benni\\AppData\\Roaming\\jupyter\\kernels\\test\\kernel.json',
      name: 'test',
      argv: [Array],
      language: 'python',
      path: 'C:\\DHiiP_Scripte\\test\\.venv\\Scripts\\python.exe',
      display_name: 'test',
      metadata: [Object]
    },
    interpreter: {
      id: 'C:\\DHIIP_SCRIPTE\\TEST\\.VENV\\SCRIPTS\\PYTHON.EXE',
      sysPrefix: 'c:\\DHiiP_Scripte\\test\\.venv',
      envType: 'Venv',
      envName: '.venv',
      envPath: 'c:\\DHiiP_Scripte\\test\\.venv',
      path: 'c:\\DHiiP_Scripte\\test\\.venv\\Scripts\\python.exe',
      architecture: 3,
      sysVersion: '3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]',
      version: [Object],
      displayName: "Python 3.10.2 ('.venv': venv)",
      detailedDisplayName: "Python 3.10.2 ('.venv': venv)"
    },
    id: '.test.C:\\DHiiP_Scripte\\test\\.venv\\Scripts\\python.exe.c:\\DHiiP_Scripte\\test\\.venv\\Scripts\\python.exe.-m#ipykernel_launcher'
  }
}
Info 07:48:43: Process Execution: > c:\DHiiP_Scripte\test\.venv\Scripts\python.exe -c "import ipykernel"
> c:\DHiiP_Scripte\test\.venv\Scripts\python.exe -c "import ipykernel"
Info 07:48:44: Dispose kernel file:///c%3A/DHiiP_Scripte/test/Untitled-1.ipynb

**Comment by jatq** [comment]
maybe this issue has something to do with vpn

**Comment by A164523** [comment]
Hi There, i am getting the same issue, please find error log attached for details. Thanks!
[ErrorLog.txt](https://github.com/microsoft/vscode-jupyter/files/10141828/ErrorLog.txt)

**Comment by sanskaromar** [comment]
Did anyone find the solution to this? I have observed that this issue occurs only when I'm behind the proxy. Otherwise it works fine.
