### ISSUE TITLE
Raw type cell evaluated inifinitely 

### ISSUE THREAD

**Issue by danieltomasz** [microsoft/vscode-jupyter#9633]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

After creating a raw type code cell (empty or with content) and running it or just running all cell , the cell seems as is evaluated infinitively (the time counter is running all the time). 
![image](https://user-images.githubusercontent.com/7980381/162337492-f0493f53-b755-4551-8627-b645d85741d6.png)

Restart notebook doesn't change this, but I can execute other cells. 
I needed a raw cell to run Jupiter notebook with Quatro extension (it stores its YAML metadata as raw)  but this is happening also after deactivating it.

Raw as cell type support was  merged  not that long ago https://github.com/microsoft/vscode-jupyter/issues/1611 https://github.com/microsoft/vscode-jupyter/pull/6958 https://github.com/microsoft/vscode-jupyter/issues/1466
### VS Code Version

Version: 1.66.1 (Universal)

### Jupyter Extension Version

v2022.4.1000912146

### Coding Language and Runtime Version

Python 3.10.3

### Language Extension Version (if applicable)

Python extension 

### Running Jupyter locally or remotely?

Local

**Comment by danieltomasz** [comment]
Support for raw is still fresh in VSCode https://github.com/microsoft/vscode-jupyter/issues/1611

**Comment by DonJayamanne** [comment]
I think its a minor regression with some of the recent work.
