### ISSUE TITLE
Step in only works during the first run when debugging through interactive 

### ISSUE THREAD

**Issue by avm19** [microsoft/vscode-jupyter#9635]
### Applies To

- [ ] Notebooks (.ipynb files)
- [x] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The contents of `test.py`:
```
# %%
import numpy

print(numpy.__version__)
```
Also:
- I set up a breakpoint at `import numpy` in `test.py` above.
- I have `"jupyter.debugJustMyCode": false` in the settings.
- I run VS Code under Windows. I connect to a remote, which has Ubuntu. (Local Extension: Remote - SSH v0.80.0)

First run:
1. I click "Debug Cell". The debugger pauses in a finally-clause in `interactiveshell.py` (probably an uncaught exception)
2. I press F5 (Continue) to step out of `interactiveshell.py`. The debugger points at `import numpy`.
3. I press F11 (Step in) to step into the import statement. **As expected**, the editor opens `__init__.py` of the module, and I can trace the execution.
4. I stop the debugger

Subsequent runs:
1. [as above]
2. [as above]
3. I press F11 (Step in) to step into the import statement. **The unexpected** happens: instead of stepping into `__init__.py`, I find the debugger at `interactiveshell.py:3457`:
    ```exec(code_obj, self.user_global_ns, self.user_ns)```

After I click "Restart" in the interactive window, the expected behaviour restores for the following run, after which the bug comes back.

If _when stepped in `__init.py__`_ I set a breakpoint there, then this breakpoint works in first runs, but is ignored in subsequent runs.

### VS Code Version

Version: 1.67.0-insider (system setup) Commit: a3d53f76790d8c88f835afe85225ff6442703409 Date: 2022-04-07T05:15:43.863Z Electron: 17.3.1 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Windows_NT x64 10.0.19042

### Jupyter Extension Version

v1.0.6 

### Jupyter logs

```shell
https://gist.github.com/avm19/201a983fb65ebbf543a2641b0030776d
```

### Coding Language and Runtime Version

Python 3.7.7

### Language Extension Version (if applicable)

v2022.5.10971003

### Anaconda Version (if applicable)

conda 4.11.0

**Comment by rchiodo** [comment]
This is the expected behavior with "justMyCode" turned off. There are some fine tuning settings you can apply but they're not exposed as a setting.

See this issue for more information:
https://github.com/microsoft/vscode-jupyter/issues/8146#issuecomment-970926977

**Comment by avm19** [comment]
@rchiodo Thanks for the reference.

It is hard to believe that this is intended behaviour, because it works differently during the first run and during the subsequent runs. If one behaviour is expected then the other must be not.

**Comment by rchiodo** [comment]
Subsequent runs may be entering code differently. Depends upon the implementation of the kernel and whether or not it caches things.

**Comment by rchiodo** [comment]
The not stepping into `__init__.py` sounds more like the design of how packages work. Once a package is loaded into a python process it doesn't run `__init__.py` again. 

This has some more information:
https://docs.python.org/3/tutorial/modules.html#tut-packages

So in this case if you debug a normal python file, you're starting a python process every time. You'd expect to be able to debug `__init__.py` each time.

If you debug from a kernel, it should only step into that file once, the first time the package is loaded into the kernel.

**Comment by avm19** [comment]
My bad, thanks for explaining!
