### ISSUE TITLE
No progress indicator when starting kernels for IW

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9644]
Create a blank interactive window
There's no progress indicator on the bottom right about the kernel starting.

On Windows with Python having complex packages, this startup takes a while and there's no progress indicator in this case.
Another easy way to replicate this issue is to simply select a `Julia` kernel from the kernel picker and you'll notice there's no progress indicator.

Note: This isn't specific to Julia, even in Python kernel for Windows this can be repro'ed today.

**Comment by rebornix** [comment]
While testing #10733 I found that I usually got connecting to kernel notification for the first session but then no progress notification anymore for new sessions.

**Comment by DonJayamanne** [comment]
This should be stanadrd block of code, agnostic of IW & Notebooks.

**Comment by DonJayamanne** [comment]
Fixed

**Comment by DonJayamanne** [comment]
Fixed
