### ISSUE TITLE
Jupyter Notebook editor not opening

### ISSUE THREAD

**Issue by constant5** [microsoft/vscode-jupyter#965]
Issue Type: <b>Bug</b>

Not sure what changed but after using Jupyter Notebook for some time in VS code the notebook editor stopped opening. I'm not sure how to reproduce this issue but now I can't use notebooks in VS Code.  

I confirmed it is is not working locally or on a remote session. 

Extension version: 2020.6.89148
VS Code version: Code - Insiders 1.47.0-insider (0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69, 2020-06-23T09:03:35.861Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 3.10.0-327.3.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (9.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: talon3|
|OS|Linux x64 3.10.0-327.3.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (28 x 2399)|
|Memory (System)|62.81GB (6.81GB free)|
|VM|0%|
</details>

**Comment by willjohnson** [comment]
I cannot open a Jupyter notebook in the November 2020 release so reinstalled October 2002 and everything ran fine.
