### ISSUE TITLE
Log can be difficult to read or interpret 

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#9650]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When the extension encounters a problem, it will sometimes suggest to the user to take a look at the Jupyter log to see what may have gone wrong. Unfortunately, this log can be extremely difficult to read and understand if you're not an engineer working on it. :)

Here's a few suggestions to consider as to how to better handle this:
* Default the ```Jupyter  > Logging: Level``` setting to something less wordy than "debug". One that is likely to more likely to contain just enough information for our customers to help solve common problems.
* Create two separate logging panels for Jupyter. One called "Jupyter" and the other called "Jupyter Detailed Log" or something like that. They would contain identical information, but the latter would contain many more details that may only be useful when entering a new issue. 
* Continue to make changes to the extension that can reduce or avoid simple "please consult the log" notifications and instead direct the user to how to fix any detected problems. 
* Provide a "one-click" method of entering an issue that automatically provides detailed logs in the issue itself.

### VS Code Version

Version: 1.67.0-insider (user setup) Commit: 6ea335e334b90a9aca753d558dec1d14741eff1e Date: 2022-04-08T07:13:56.078Z Electron: 17.4.0 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Windows_NT x64 10.0.22593

### Jupyter Extension Version

v2022.4.1001001004

**Comment by DonJayamanne** [comment]
> Default the Jupyter > Logging: Level setting to something less wordy than "debug". One that is likely to more likely to contain just enough information for our customers to help solve common problems.

I think we still log a lot of unnecessary stuff. Should reduce the logging of some of the stuff.

**Comment by DonJayamanne** [comment]
Found that the telemetry logging happened recently and that's what makes the logging more noisy. 
We should review the logs after telemetry logging is enabled only for verbose logging.
