### ISSUE TITLE
It's too easy to accidentally open an interactive window session with shift-enter when you didn't mean to.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#9652]
From a marketplace review (From: Not Specified on 3/18/2022)

Here's the relevant comment:

"One of the reasons this is so poorly reviewed is it's used outside of its intended use case. This gets enabled in all python files as well as Jupyter notebooks. So if you ever hit shift-enter on accident it's going to start a local jupyter server and send whatever happens to be under your cursor at the time.

It's bad enough to get interrupted because you were just trying to insert a line feed like in every other text editor that is not specifically a jupyter notebook. You have to close a menu that is asking you if you wanted to do this in the first place, and then close down the interactive editor that doesn't care if you did."

**Comment by greazer** [comment]
For sure, we need to make sure that when the user gets the notification that they can use the interactive window on shift-enter that the interactive window is not invoked even if the user chooses to not use it. 

Also consider reversing the notification to assume that a new user does NOT want to use the interactive window and make it easy for them to turn it on.

**Comment by amunger** [comment]
It looks like the only time we send code to the IW is when a `# %%` cell is in the file or when `jupyter.sendSelectionToInteractiveWindow` is enabled (it's off by default). Tested on a fresh install in an ubuntu vm and there were no pop-ups, so I think it's a lot less aggressive than it used to be.
closing this and the related issues as stale.
