### ISSUE TITLE
If I choose to not start an interactive window session on first prompt, I have to close the blank interactive window anyway.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#9654]
From a marketplace review (From: Not Specified on 3/18/2022). Here's the relevant comment:

"It's bad enough to get interrupted because you were just trying to insert a line feed like in every other text editor that is not specifically a jupyter notebook. You have to close a menu that is asking you if you wanted to do this in the first place, and then close down the interactive editor that doesn't care if you did."

Related to https://github.com/microsoft/vscode-jupyter/issues/9652

**Comment by amunger** [comment]
closing https://github.com/microsoft/vscode-jupyter/issues/9652#issuecomment-1338136635
