### ISSUE TITLE
Consider having a more discoverable/convenient way of opting into or out of the interactive window experience.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#9655]
From a marketplace review (From: Not Specified on 3/18/2022). Here's the relevant comment:

"Speaking of that interactive editor/terminal, it is the worst feature I have encountered in VS Code. First off, they just took the UI from jupyter labs. If you like that UI, then you might not give this one star. I'm so used to a terminal UI that it makes me skin crawl to use that web interface.

So that's a matter of opinion and doesn't necessarily justify one staring something. After all, in theory, if I don't like it I just disable the code that pipes things into notebooks when I hit shift -enter, back to four of five stars."

Related to: https://github.com/microsoft/vscode-jupyter/issues/9654

**Comment by amunger** [comment]
closing https://github.com/microsoft/vscode-jupyter/issues/9652#issuecomment-1338136635
