### ISSUE TITLE
Finding where and how to change remote server connections is not intuitive

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#9660]
From a marketplace review (From Abhay Prakash Tiwari on 3/31/2022). Here's the relevant comment:
"2. not documented well to modify server url"

While the ```Jupyter: Specify Jupyter server for connections``` allows me to specify a different server, remembering and finding this command could be made more intuitive. Perhaps provide a choice in the kernel picker to change your remote server?

This may dovetail into the work we're doing here: https://github.com/microsoft/vscode/issues/146942

**Comment by DonJayamanne** [comment]
Blocked on lazy controllers.

**Comment by DonJayamanne** [comment]
Fixed with the new kernel picker
