### ISSUE TITLE
Language requests not sent to R language server when editing R cell

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode-jupyter#9673]
Related https://github.com/REditorSupport/vscode-R/issues/1074.

## Environment data

-   VS Code version: 1.66.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.4.1000912146
-   Python Extension version (available under the Extensions sidebar): v2022.5.11021002
-   OS (Windows | Mac | Linux distro) and version: macOS 12.3.1
-   Python and/or Anaconda version: 3.9.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): NA
-   Jupyter server running: Local

## Expected behaviour

When I create a notebook and choose the language of the cell to be `R`, then the [vscode-R](https://github.com/REditorSupport/vscode-R) extension is activated and the [R language server](https://github.com/REditorSupport/languageserver) is started.

The editing experience should be the same as editing an R file with proper completion, hover, signature help, etc. provided by the R language server.

## Actual behaviour

Most language requests (e.g. completion, hover, signature help) are never sent to the R language server, as I can see in the log of the R language server channel when `r.lsp.debug` is on.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Install vscode-R extension in VS Code and languageserver package in R. Enable `r.lsp.debug` in vscode settings.
2. Create a ipynb notebook and a R cell. The R language server should be started.
3. Type R expressions in the cell and none of the language providers such as completion and hover work. From the log in the "R Langauge Server" output channel, it only receives document open/save/change requests. No language provider requests (completion, hover, signature help, etc.) are received from the language client.
4. Hover cursor on a function name (e.g. `read.csv`), the hover providers registered by vscode-R is properly shown.
5. Create an R file. A new instance of R languge server is started.
6. Type `read.csv` in the R file and the language server works properly with completion and hover.
7. Type and hover in the cell again, and it looks like the first language server suddenly could receive the requests but none works properly.

https://user-images.githubusercontent.com/4662568/163028694-5c5244ab-212d-4806-a252-93a435ef784c.mp4

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

(No output seen)

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the issue. 

The jupyter extension doesn't handle language server requests for languages other than Python. 

My guess is that the R extension is not registering itself for notebooks. You should open an issue on the R extension.

**Comment by rchiodo** [comment]
If it used to work, my guess would be this change in VS code core that requires more information when registering language servers so they work in notebooks:
https://github.com/microsoft/vscode/commit/b58c215a0bfa60729fbdd5c125c57b91d02ca723

**Comment by renkun-ken** [comment]
Thanks for pointing to the upstream change.

It is confirmed in https://github.com/REditorSupport/vscode-R/issues/1074#issuecomment-1097498054 that is worked before. Looks like I have to change something to adapt to the latest vscode notebooks api?
