### ISSUE TITLE
Localize using vscode-loc

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9676]
Looks like the Python extension is finally adopting the vscode-loc package to localize strings in the exension.
We might want to look into this.

**Comment by rchiodo** [comment]
See the directions that Tyler has:
https://gist.github.com/TylerLeonhardt/83abd380686ac1321b01552a5b236bad

**Comment by DonJayamanne** [comment]
We'd need to see how this would work with webviews.
@TylerLeonhardt do you have any idea whether this is possible today? or of any work arounds?

**Comment by TylerLeonhardt** [comment]
Webviews aren't supported today because you need a file system for localization at this time.

The best you can do today is have your strings on the extension host side and then send them to the webview.

This will get better over time
