### ISSUE TITLE
Kernel issues related to login shells

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9682]
* Python package ibm_db requires some env variables to be setup, if not kernel crashes
	* https://github.com/microsoft/vscode-jupyter/issues/9347
	* https://github.com/microsoft/vscode-jupyter/issues/9681
* ocaml kernel requires env variables to be setup, if not kernel will not start
	* https://github.com/microsoft/vscode-jupyter/issues/8897 
* Users have complained about env variables defined in login shells that are not detected by VS Code (plenty on remote SSH)
	* Need to find these issues (reported in VS Code as well as Jupyter repo) 
* ~Path variables are not the same when launched from terminal vs vscode ~
	* ~No known issues, just the fact that the values are different.~
	* ~https://github.com/microsoft/vscode-jupyter/issues/5041~ 	
* ~https://github.com/microsoft/vscode-jupyter/issues/5041~
* ~https://github.com/microsoft/vscode-jupyter/issues/9917~
* ~https://github.com/microsoft/vscode-jupyter/issues/10392~

**Comment by DonJayamanne** [comment]
# Suggestion

If kernels crash or the like, should we somehow offer (or try) to create a hidden terminal scrape the env variables from there and try running the kernel. This would work for OCaml & ibm_db (which crash the kernel) & would go a long way to improving overall usability of the extesnion.
Today anyone attempting to use ocaml or ibm_db could just stop using VS Code.

**Comment by DonJayamanne** [comment]
Closing this issue as there's nothing to be done here, creating a new issue to track login shell issues on SSH
https://github.com/microsoft/vscode-jupyter/issues/10707

**Comment by connor4312** [comment]
Marking verified since this seems to be a general tracking issue
