### ISSUE TITLE
jupyter.jupyterServerType config value not respected in user or remote config files.

### ISSUE THREAD

**Issue by apockoffork** [microsoft/vscode-jupyter#9686]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I added `"jupyter.jupyterServerType": "remote",` to my user and/or my remote config file (I'm using a remote ssh setup). When I then start a jupyter notebook I need to still configure it to use a remote kernel. When I do configure it to a remote kernel it updates the workspace config file to contain `"jupyter.jupyterServerType": "remote",`.

I believe the correct behavior is to use the server type config in the user or remote configuration file first or to not add the config to the workspace file if the configuration value is present in the user/remote config files. 

### VS Code Version

Version: 1.66.2 (Universal) Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977 Date: 2022-04-11T07:49:20.994Z (3 days ago) Electron: 17.2.0 Chromium: 98.0.4758.109 Node.js: 16.13.0 V8: 9.8.177.11-electron.0 OS: Darwin x64 21.4.0

### Jupyter Extension Version

v2022.3.1000901801

### Running Jupyter locally or remotely?

Remote

**Comment by IanMatthewHuff** [comment]
@apockoffork Thanks for the report here. You are correct that setting is being handled a bit different from other vscode settings. Currently when set to `remote` it is tied to an encrypted storage for the actual URI. This creates some funny expectations regarding what happens if the setting is manually set to `remote` or settings sync.

**Comment by greazer** [comment]
This particular setting is confusing and probably isn't needed to be user-settable. Changes down the line in our remote story will also likely obviate the need. #9684.

**Comment by DonJayamanne** [comment]
Closing this issue as such a setting no longer exists in the extension
