### ISSUE TITLE
python.envFile is not respected by Python code executed in Notebook and IW

### ISSUE THREAD

**Issue by dmartin** [microsoft/vscode-jupyter#9691]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Environment variables defined in an `.env` file in the workspace root are available in notebooks, but it is surprising that only root `.env` files are supported, rather than using the [`python.envFile` setting](https://code.visualstudio.com/docs/python/environments#_environment-variable-definitions-file) like other VSCode Python functionality.

The `.env` file path appears to be hardcoded [here](https://github.com/microsoft/vscode-jupyter/blob/5a91b9cdd946903a92610cb630221e78d3744038/src/platform/common/variables/environmentVariablesProvider.node.ts#L70).

### VS Code Version

1.66.2

### Jupyter Extension Version

v2022.3.1000901801

**Comment by amunger** [comment]
Thanks for the issue. I'm not sure if we should be using another extension's setting directly like that. Perhaps we can introduce our own env file setting that would default to Python's? We will discuss

**Comment by rchiodo** [comment]
We could use ```python.envFile``` for just python kernels.

**Comment by micimize** [comment]
This seems to also apply to `*.py` scripts. I'm still a bit unsure if it was ignoring my env entirely or just setting it relative to the script location, but I came up with a `runStartupCommands` solution that seems to work regardless:
```python
def _reparent_env_parts():
    import os, sys
    def _pluck_prefixed(file_pattern: str, prefix: str) -> str:
        file_path = file_pattern.replace("${workspaceFolder}", WORKSPACE_FOLDER)
        with open(file_path, 'r') as f:
            for l in f.readlines():
                line = l.strip()
                if line.startswith(prefix):
                    return line[len(prefix):]
    WORKSPACE_FOLDER = os.path.dirname(os.environ['VIRTUAL_ENV'])
    env_pattern = _pluck_prefixed('${workspaceFolder}/.vscode/settings.json', '"python.envFile": ')
    env_pattern = env_pattern.strip()
    env_pattern = env_pattern[1:len(env_pattern) - 2]
    pypath = _pluck_prefixed(env_pattern, 'PYTHONPATH=')
    python_path = [
        os.path.join(WORKSPACE_FOLDER, p)
        for p in pypath.split(':')
    ]
    os.environ['PYTHONPATH'] = ':'.join(python_path)
    sys.path[1:1] = python_path
_reparent_env_parts()
del _reparent_env_parts
```
```json5
// User settings.json
"jupyter.runStartupCommands": [
  "def _reparent_env_parts():",
  "    import os, sys",
  "    def _pluck_prefixed(file_pattern: str, prefix: str) -> str:",
  "        file_path = file_pattern.replace('$' + '{workspaceFolder}', WORKSPACE_FOLDER)",
  "        with open(file_path, 'r') as f:",
  "            for l in f.readlines():",
  "                line = l.strip()",
  "                if line.startswith(prefix):",
  "                    return line[len(prefix):]",
  "    WORKSPACE_FOLDER = os.path.dirname(os.environ['VIRTUAL_ENV'])",
  "    env_pattern = _pluck_prefixed('${workspaceFolder}/.vscode/settings.json', '\"python.envFile\": ')",
  "    env_pattern = env_pattern.strip()",
  "    env_pattern = env_pattern[1:len(env_pattern) - 2]",
  "    pypath = _pluck_prefixed(env_pattern, 'PYTHONPATH=')",
  "    python_path = [",
  "        os.path.join(WORKSPACE_FOLDER, p)",
  "        for p in pypath.split(':')",
  "    ]",
  "    os.environ['PYTHONPATH'] = ':'.join(python_path)",
  "    sys.path[1:1] = python_path",
  "_reparent_env_parts()",
  "del _reparent_env_parts()",
],
```

**Comment by DonJayamanne** [comment]
I beleive the solution was to respsect the .env file setting form Python when dealing with Python kernels & not others.

**Comment by DonJayamanne** [comment]
# Solution
* Respsect the .env file setting form Python only when dealing with Python kernels
* When running regular python code, such as launching Jupyter, etc, we'll not load from the pyhton.env file setting.

**Comment by liubenyuan** [comment]
If jupyter and python only respect .env file, could we make the PYTHONPATH in `.env` compatible (os.pathsep) for both linux and windows operating systems? 
```bash
# .env
if windows:
    PYTHONPATH = "D:/path1;D:/path2;D:/path3"
elif linux:
    PYTHONPATH = "~/lib/path1:~/lib/path2:~/lib/path3"
```
