### ISSUE TITLE
Built-in renderer does not render <moviepy.video.io.html_tools.HTML2 object> correctly

### ISSUE THREAD

**Issue by yilun-wu** [microsoft/vscode-jupyter#9695]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Executing the following code from a demo of moviepy:

```
import matplotlib.pyplot as plt
import numpy as np
from moviepy.editor import VideoClip
from moviepy.video.io.bindings import mplfig_to_npimage

x = np.linspace(-2, 2, 200)

duration = 2

fig, ax = plt.subplots()
def make_frame(t):
    ax.clear()
    ax.plot(x, np.sinc(x**2) + np.sin(x + 2*np.pi/duration * t), lw=3)
    ax.set_ylim(-1.5, 2.5)
    return mplfig_to_npimage(fig)

animation = VideoClip(make_frame, duration=duration)
animation.ipython_display(fps=20, loop=True, autoplay=True)
```
On macos at least, this would render a non-functional playing widget (i.e. not able to click the play button, and the video does not start to play automatically)

<img width="334" alt="image" src="https://user-images.githubusercontent.com/10345786/163682878-4b83c1b4-3bce-435c-8eb4-0ba6f6fcbf74.png">

On a standard web browser (e.g. Chrome), this block gets rendered correctly as expected.

### VS Code Version

1.66.2

### Jupyter Extension Version

v2022.3.1000901801

**Comment by amunger** [comment]
thanks for the bug, I was able to repro

**Comment by rchiodo** [comment]
Unfortunately VS code doesn't ship the necessary codecs to support audio/video playback. See this issue here:
https://github.com/microsoft/vscode/issues/118275

**Comment by yilun-wu** [comment]
> Unfortunately VS code doesn't ship the necessary codecs to support audio/video playback. See this issue here:
> [microsoft/vscode#118275](https://github.com/microsoft/vscode/issues/118275)

Note playing a video file with Python is possible and works in VSCode like the following:
```
from IPython.display import Video
Video("__temp__.mp4")
```
So not sure a missing codec is the problem here

**Comment by rchiodo** [comment]
I think it has something to do with the src element for the video. For a local file maybe it's using the codecs on your machine. However if the src element is a byte stream it's not. 

It's up to electron whether or not it's enabled.
