### ISSUE TITLE
Interactive window doesn't stick to bottom when printing lines

### ISSUE THREAD

**Issue by PKeener01** [microsoft/vscode-jupyter#9696]
Similar to issue #2256 which was resolved in 2021, this bug appears to have been reintroduced in latest patch.

## Environment data

-   VS Code version: 1.66.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.3.1000901801
-   Python Extension version (available under the Extensions sidebar): v2022.4.1
-   OS (Windows | Mac | Linux distro) and version: 
              Edition	Windows 10 Home
              Version	21H2
              Installed on	‎09-‎Mar-‎21
              OS build	19044.1645
              Experience	Windows Feature Experience Pack 120.2212.4170.0
-   Python and/or Anaconda version: 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A:  N/A

## Expected behaviour

When interactive window is all the way at the bottom and code is executed, the window should scroll with the output.   

## Actual behaviour

The window appears to advance 1 line then stop, even if there are multiple additional lines (GIF below)

## Steps to reproduce:

In interactive window:

print(f'not scrolling\n'*15)

1. XXX

![VSC_Immediate_bug](https://user-images.githubusercontent.com/92237036/163684067-dd4a588f-8da2-4fff-adc8-de407e041951.gif)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by amunger** [comment]
This needs to be fixed in core, and there is an existing [issue](https://github.com/microsoft/vscode/issues/145353) for it. 
I checked in 1.65.2, and it behaves the same as far as I can see, so I don't think it has regressed any worse, but still something that needs to be fixed.
