### ISSUE TITLE
Add API to allow opening Data Wrangler from Variable Explorer

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-jupyter#9699]
Users want the ability to open Data Wrangler from any existing DataFrame loaded into their notebook rather than having to save it as a CSV first. We would like to add an API entrypoint into the Variable explorer in the Jupyter Extension to allow any DataFrames loaded in the kernel to be passed to Data Wrangler to be rendered.

**Comment by rchiodo** [comment]
@jmew I'd think they'd want to replace our data viewer with the data wrangler? So the same button just opens it in the Data Wrangler?

**Comment by rchiodo** [comment]
First thoughts from the team - an entry point in the package.json that describes a command we'd execute.

```
"contributes":
    "jupyter-data-viewer:" 
    { 
       "types": ["DataFrame", "List"]
       "command": "data-wrangler.opendataframe"
    }
```

**Comment by jmew** [comment]
@rchiodo Currently, the Data Wrangler doesnt support all of the features of the Data Viewer (e.g. expression slicing), and it is also not a hard dependency of the Jupyter extension yet. So I think initially we would want to experiment with replacing the Data Viewer with Data Wrangler. Having the API would make it easy to run this as an experiment.

**Comment by amunger** [comment]
It doesn't look like there has much movement here for a while. @jmew - is this still something your team needs?
