### ISSUE TITLE
Users shouldn't be expected to read the Jupyter log

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#9701]
We have several error conditions in the product that point people to looking at the Jupyter log. Our log (in the default debug mode) is pretty difficult to parse. Therefore, we should change our messaging to indicate that there may be information in the Jupyter log that could be useful and that the user should create an issue, rather than telling them to refer to the Jupyter Log.

**Comment by greazer** [comment]
Here's a proposal:

"DataScience.sessionStartFailedWithKernel": "Failed to start the Kernel '{0}'. \nFor help, please copy the contents of the Jupyter [log](command:jupyter.viewOutput) into a new [GitHub issue](https://aka.ms/new_jupyterext_bug)",

Note that the new_jupyterext_bug alias *does* exist.

**Comment by greazer** [comment]
Potentially better is to just point the users at our bug form. It contains links to our wiki, discussions, and has a prompt for entering Jupyter output.

Example:
```"DataScience.kernelDied": "The kernel died. Error: {0}...\nFor help, please consider entering a a new [GitHub issue](https://aka.ms/vscodeNewJupyterExtBug)"```

**Comment by rchiodo** [comment]
For some of these the error is in the log. It should be easy to just have that output somewhere. I'd rather people solved their own problems if they can.

**Comment by greazer** [comment]
Let's review all the places we suggest users to look at the log and determine whether there's a better way to expose the information required to fix and use pointers to the log as a last resort.

**Comment by rebornix** [comment]
> For some of these the error is in the log. It should be easy to just have that output somewhere. I'd rather people solved their own problems if they can.

The logs can be helpful and guide users to self-troubleshoot, the catch here IMHO is the logs are way to verbose. It come with tons of `info` messages, which most of the time might be irrelevant to the issues users are running into. The logs often container errors which are not directly related to the problem users ran into, making it challenging to understand which went wrong. If we are asking users to reach to the logs, I would rather show the error logs to users first.

**Comment by DonJayamanne** [comment]
Closing this issue for now. as I do'nt think there's anything that needs to be done here
