### ISSUE TITLE
"outside root contents directory" error when run cell.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#9709]
## Environment data
Build of Visual Studio Code - Insiders: 1.67.0-insider(user setup)
Build of python-insider: v2022.5.11051003
Build of jupyter-insider:v2022.4.1001071005
Build of pylance-insider: v2022.4.1
Build of jupyter Notebook Renderers: v1.0.6
Build of jupyter Keymap: v1.0.0

## Steps to reproduce:
1. Make sure Anaconda installed in local
2. Open the file src/test/datascience/manualTestFiles/manualTestFile.py in VS Code
3. At the top of the file it will list the things that you need installed in your Python environment
4. On the first cell click Run Below

## Expected behaviour
Interactive Window should open, show connection information, and execute cells

## Actual behaviour
"outside root contents directory" error pops up.
![image](https://user-images.githubusercontent.com/59192491/163943127-c2030f5c-5881-436a-8e40-f2a3957c523a.png)

Create a new Jupyter Notebook and input some code to run. This issue also occurred.
![image](https://user-images.githubusercontent.com/59192491/163942968-c39db82b-b15f-4a07-9ab0-0717c4c15992.png)

## Logs
`[DEBUG 2022-3-19 6:50:33.915]: Getting activation commands for file:///c%3A/ProgramData/Anaconda3/python.exe
[DEBUG 2022-3-19 6:50:33.915]: Getting activation commands for file:///c%3A/ProgramData/Anaconda3/python.exe are cached.
[DEBUG 2022-3-19 6:50:33.916]: Got env vars with python c:\ProgramData\Anaconda3\python.exe in 1914ms
[DEBUG 2022-3-19 6:50:36.250]: Telemetry Event : HASHED_PACKAGE_PERF Measures: {"duration":0} Props: {"isInsiderExtension":"true","ds_notebookeditor":"native","localOrRemoteConnection":"local","isPythonExtensionInstalled":"true","rawKernelSupported":"false","installSource":"marketPlace","VSCode.ABExp.Features":"invitationLink;installRecovery;livesharecontinuousaacf;reusableLinks;RemoveKernelToolbarInInteractiveWindow;portForwardingServiceEnabled-development;portForwardingServiceEnabled-staging;portForwardingServiceEnabled-production;jupyterTest;pylanceIndexingEnabled;pythonSurveyNotificationcf;jupyterEnhancedDataViewer;pythonDeprecatePythonPath;mindaroBinariesVersion-1.0.20210702;mindaroBinariesVersion-1.0.20210723;account-aa;pythonInterpreterInfoPinned;config.python.createNewFileEnabled","abexp.assignmentcontext":"vsliv695:30137379;vsins829:30139715;vsliv368cf:30146710;vsreu685:30147344;python383:30185418;vspor879:30202332;vspor708:30202333;vspor363:30204092;vsjup275:30257432;pythonvspyl392:30422396;pythonvspyt551cf:30291413;pythondataviewer:30285072;pythonvspyt200:30323110;bridge0708:30335490;bridge0723:30353136;vsaa593:30376534;pythonvsnew555:30438690;pynewfile477:30451556;","isamlcompute":"false","userExecutedCell":"true"} 
[DEBUG 2022-3-19 6:50:37.677]: Telemetry Event : DS_INTERNAL.HASHED_OUTPUT_MIME_TYPE_PERF Measures: {"duration":1} Props: {"isInsiderExtension":"true","ds_notebookeditor":"native","localOrRemoteConnection":"local","isPythonExtensionInstalled":"true","rawKernelSupported":"false","installSource":"marketPlace","VSCode.ABExp.Features":"invitationLink;installRecovery;livesharecontinuousaacf;reusableLinks;RemoveKernelToolbarInInteractiveWindow;portForwardingServiceEnabled-development;portForwardingServiceEnabled-staging;portForwardingServiceEnabled-production;jupyterTest;pylanceIndexingEnabled;pythonSurveyNotificationcf;jupyterEnhancedDataViewer;pythonDeprecatePythonPath;mindaroBinariesVersion-1.0.20210702;mindaroBinariesVersion-1.0.20210723;account-aa;pythonInterpreterInfoPinned;config.python.createNewFileEnabled","abexp.assignmentcontext":"vsliv695:30137379;vsins829:30139715;vsliv368cf:30146710;vsreu685:30147344;python383:30185418;vspor879:30202332;vspor708:30202333;vspor363:30204092;vsjup275:30257432;pythonvspyl392:30422396;pythonvspyt551cf:30291413;pythondataviewer:30285072;pythonvspyt200:30323110;bridge0708:30335490;bridge0723:30353136;vsaa593:30376534;pythonvsnew555:30438690;pynewfile477:30451556;","isamlcompute":"false","userExecutedCell":"true"} 
[DEBUG 2022-3-19 6:51:37.732]: Telemetry Event : DS_INTERNAL.COMMAND_EXECUTED Measures: undefined Props: {"command":"jupyter.viewOutput","isInsiderExtension":"true","ds_notebookeditor":"native","localOrRemoteConnection":"local","isPythonExtensionInstalled":"true","rawKernelSupported":"false","installSource":"marketPlace","VSCode.ABExp.Features":"invitationLink;installRecovery;livesharecontinuousaacf;reusableLinks;RemoveKernelToolbarInInteractiveWindow;portForwardingServiceEnabled-development;portForwardingServiceEnabled-staging;portForwardingServiceEnabled-production;jupyterTest;pylanceIndexingEnabled;pythonSurveyNotificationcf;jupyterEnhancedDataViewer;pythonDeprecatePythonPath;mindaroBinariesVersion-1.0.20210702;mindaroBinariesVersion-1.0.20210723;account-aa;pythonInterpreterInfoPinned;config.python.createNewFileEnabled","abexp.assignmentcontext":"vsliv695:30137379;vsins829:30139715;vsliv368cf:30146710;vsreu685:30147344;python383:30185418;vspor879:30202332;vspor708:30202333;vspor363:30204092;vsjup275:30257432;pythonvspyl392:30422396;pythonvspyt551cf:30291413;pythondataviewer:30285072;pythonvspyt200:30323110;bridge0708:30335490;bridge0723:30353136;vsaa593:30376534;pythonvsnew555:30438690;pynewfile477:30451556;","isamlcompute":"false","userExecutedCell":"true"} `

**Comment by rchiodo** [comment]
I'm getting this too:
![image](https://user-images.githubusercontent.com/19672699/164053552-deb4801e-616a-4fc4-b33d-9add7031d00f.png)


Just disable zmq support. 

I believe this is related to this change here:
https://github.com/microsoft/vscode-jupyter/commit/a27632502a0c6027384055dec659a57821a4581f
