### ISSUE TITLE
Active Interpreter is no longer selected as the preferred kernel

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9718]
Upstream issue https://github.com/microsoft/vscode-python/issues/18955

**Comment by rchiodo** [comment]
Are you sure? It seems to be working for me:

![image](https://user-images.githubusercontent.com/19672699/164118774-62d20839-3a7b-4ebd-98cc-d2e4ba708505.png)

This is what I get as suggested (which is my active interpreter) for any new notebook I create.

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode-python/issues/18955
This is to do with the Python extension API
