### ISSUE TITLE
Kernel metadata in file is not getting updated when executing with a new kernel

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#9727]
I started out with executing a ipynb with the local python env .debugEnv. After execution and save this is the metadata:

```
 "metadata": {
  "interpreter": {
   "hash": "2e5fd6c28aced2b333922ede1ea4949b12041d4fbe9c4e40c9e7ce883e7249f4"
  },
  "kernelspec": {
   "display_name": "Python 3.7.7 ('.debugEnv': venv)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
```

I then selected the global Conda env functionalTestEnv and executed. I made sure to check sys.executable to make sure that I executed with the new kernel. After execution and save the meta data looked the exact same. Sill with a display name of .debugEnv, it was not updated to the new env.

**Comment by IanMatthewHuff** [comment]
Note: Also issues with display_name in the metadata setting code.

**Comment by IanMatthewHuff** [comment]
Repro steps:

Create two python envs with the same python version number (say 3.7.7)
Run with env number 1
Save and look at metadata
Run with env number 2
Save and look at metadata (display name and interpreter hash is the same as after the first execution)

In my particular situation I switched between a local .venv which was on python 3.7.7 and a global conda env also on 3.7.7.

**Comment by rchiodo** [comment]
/verified

In stable the same python version will prevent the metadata from getting updated.
In prerelease the metadata gets updated.
