### ISSUE TITLE
BUG:Always need to 'install tensorboard'

### ISSUE THREAD

**Issue by Pascal-bucketbreaker** [microsoft/vscode-jupyter#9740]
When I try to start the tensorboard, the VScode just tell me the tensorboard need to be installed. Then I click 'Yes',and VScode indicates me it has been installed. But the tensorboard can not be opened anyway.
Howewer,when I using Google Chrome to open the tensorboard,it can be opened and working successfully.

**Comment by IanMatthewHuff** [comment]
@Pascal-bucketbreaker Thanks for reporting. Can you give me a bit more information about your scenario? In particular the logs from the "Python" section of the output window would be helpful. Also what exactly do you mean by 'the tensorboard can not be opened' does it fail with some type of error message?

**Comment by Pascal-bucketbreaker** [comment]
![image](https://user-images.githubusercontent.com/46492746/180241148-db9824ed-0128-41c2-8278-ac37b4c792bf.png)
There are no error messages. But each time after installation finishes, I still can't open the tensorboard and the message above shows again, though all of the packages are installed.
Plus, I can use the tensorboard by command line.

**Comment by rchiodo** [comment]
There is an output log here:

![image](https://user-images.githubusercontent.com/19672699/180480832-256dfbcc-2395-4825-8720-2587d512251d.png)

That's the log @IanMatthewHuff is asking for.

**Comment by Pascal-bucketbreaker** [comment]
![image](https://user-images.githubusercontent.com/46492746/180590834-fc506be6-a012-4862-b9f2-a162f0969d16.png)
Is this what you need?

**Comment by IanMatthewHuff** [comment]
Thanks for the info. I'm going to keep this closed as it looks like a duplicate of the issue in #9678. We're not activating the conda environment correctly in the tensorboard case, so the install isn't doing the right thing. That bug is already being considered for next iteration.
