### ISSUE TITLE
Test web extension from a development environment

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9767]
Testing the web extension development environment

Refs: #9745 

- [x] windows @amunger 
- [x] mac @IanMatthewHuff 

Complexity: 4

Authors: @rchiodo

Picking folks that have experience with this sort of thing. Feel free to reassign if you have too many items.

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%239767%0A%0A&assignees=rchiodo)

---

### Requirements

- Setup your dev environment (install the 'Typescript + Webpack Problem Matcher extension)
- Have jupyter running locally with '--NotebookApp.allow_origin=*'

### Test Debugging

1. Start a jupyter notebook serer with the '--NotebookApp.allow_origin=*' set
2. Checkout and build the jupyter extension.
3. Pick 'Extension (web)' under debug
4. Specify a remote server to find kernels from
5. Run notebooks

Note: I don't expect https to work so don't start your jupyter server with a certificate. Just use http.

### Test Browser

1. Start a notebook server
2. Build jupyter source
3. Run the 'npm run openInBrowser'
4. Specify a remote server to find kernels from
5. Run notebooks

**Comment by IanMatthewHuff** [comment]
@rchiodo Any particular "known not working" stuff? InteractiveWindow I think is out, right?

**Comment by rchiodo** [comment]
Yes interactive window is out. Only remote works. There should be a very limited set of commands available. 

Variable viewer, Data Viewer, and Plot Viewer should not be working.

**Comment by rchiodo** [comment]
Oh and widgets probably don't work yet either. CDN download isn't possible they way we have it working right now. Not sure yet how to get that working.
