### ISSUE TITLE
Origin for web extension is too hard to specify

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9773]
In the remote server situation (from the web), the user must start Jupyter like so:

```jupyter notebook --NotebookApp.allow_origin=<base url>```

Ideally, they'd set it like so:

```jupyter notebook --NotebookApp.allow_origin=https://vscode-dev```

However this doesn't work. 

That's because the webworker has something like so set as the origin:

```https://v--0q1i8c2u150mcq90o85f64ukgjbssr515pashf0hfb9o28bfkbqo.vscode-cdn.net//```

And we get a CORS error when connecting.

**Comment by rchiodo** [comment]
It was suggested to try this instead:

```jupyter notebook --NotebookApp.allow_origin=https://*.vscode-cdn.net```

That doesn't work either because jupyter itself doesn't parse the *.

See the code here:
https://github.com/jupyter-server/jupyter_server/blob/25ec3ed0dad617a4388db865e9c1a585e54c0b7c/jupyter_server/base/handlers.py

**Comment by rchiodo** [comment]
There's another setting that might work:

```
--NotebookApp.allow_origin_pat=<Unicode>
    Use a regular expression for the Access-Control-Allow-Origin header
            Requests from an origin matching the expression will get replies
    with:
                Access-Control-Allow-Origin: origin
            where `origin` is the origin of the request.
            Ignored if allow_origin is set.
    Default: ''
```

**Comment by rchiodo** [comment]
Yes that does work, but still leaves the server open to url spoofing from other locations. Maybe it's good enough though.

**Comment by greazer** [comment]
We think the allow_origin_pat will be sufficient for now. Isn't really a security issue.
