### ISSUE TITLE
Matplotlib Slider stops working after some time

### ISSUE THREAD

**Issue by oliverw96** [microsoft/vscode-jupyter#9780]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I've created a plot with sliders `matplotlib.widgets.Slider`. When I run the code cell the plot is created correctly and I can also move the sliders to modify the plot. But this works only for a few seconds, then the sliders freeze. I can no longer change the values of the sliders. But the interactive features like 'Zoom to rectangle' still work.

The Slider demo file from https://matplotlib.org/stable/gallery/widgets/slider_demo.html works without a problem and I've simply wrapped the code of the demo in a function.

### VS Code Version

Version: 1.66.2 (system setup) Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977 Datum: 2022-04-11T07:46:01.075Z Electron: 17.2.0 Chromium: 98.0.4758.109 Node.js: 16.13.0 V8: 9.8.177.11-electron.0 Betriebssystem: Windows_NT x64 10.0.19043

### Jupyter Extension Version

v2022.3.1000901801

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment]
Thanks for the issue. Unfortunately, this works fine for me. It doesn't freeze.

What steps did you take to get it to repro other than it stops working after a few seconds? Are you using remote SSH by any chance?

It does seem to run smoother for me on insiders too (with preview bits of the Jupyter extension). The sliders may just be passing so much information that VS code can't keep up. There's been some improvements in communication speed in the last month, so you might try the [insiders version](https://code.visualstudio.com/insiders/) of VS code instead.

**Comment by rchiodo** [comment]
Oh and just to be clear. Here's the code I ran:

```
# Cell 1
%matplotlib widget
```
```
# Cell 2
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider, Button


# The parametrized function to be plotted
def f(t, amplitude, frequency):
    return amplitude * np.sin(2 * np.pi * frequency * t)

t = np.linspace(0, 1, 1000)

# Define initial parameters
init_amplitude = 5
init_frequency = 3

# Create the figure and the line that we will manipulate
fig, ax = plt.subplots()
line, = plt.plot(t, f(t, init_amplitude, init_frequency), lw=2)
ax.set_xlabel('Time [s]')

# adjust the main plot to make room for the sliders
plt.subplots_adjust(left=0.25, bottom=0.25)

# Make a horizontal slider to control the frequency.
axfreq = plt.axes([0.25, 0.1, 0.65, 0.03])
freq_slider = Slider(
    ax=axfreq,
    label='Frequency [Hz]',
    valmin=0.1,
    valmax=30,
    valinit=init_frequency,
)

# Make a vertically oriented slider to control the amplitude
axamp = plt.axes([0.1, 0.25, 0.0225, 0.63])
amp_slider = Slider(
    ax=axamp,
    label="Amplitude",
    valmin=0,
    valmax=10,
    valinit=init_amplitude,
    orientation="vertical"
)


# The function to be called anytime a slider's value changes
def update(val):
    line.set_ydata(f(t, amp_slider.val, freq_slider.val))
    fig.canvas.draw_idle()


# register the update function with each slider
freq_slider.on_changed(update)
amp_slider.on_changed(update)

# Create a `matplotlib.widgets.Button` to reset the sliders to initial values.
resetax = plt.axes([0.8, 0.025, 0.1, 0.04])
button = Button(resetax, 'Reset', hovercolor='0.975')


def reset(event):
    freq_slider.reset()
    amp_slider.reset()
button.on_clicked(reset)

plt.show()
```

**Comment by oliverw96** [comment]
Hi, I am not using SSH. Oh and I should have been a little bit clearer about how I use the demo code. I've put the code inside a function and then I run the function, see here:

```
# Cell 1
%matplotlib widget
```

```
# Cell 2
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider, Button

def dummy_plot():

    # The parametrized function to be plotted
    def f(t, amplitude, frequency):
        return amplitude * np.sin(2 * np.pi * frequency * t)

    t = np.linspace(0, 1, 1000)

    # Define initial parameters
    init_amplitude = 5
    init_frequency = 3

    # Create the figure and the line that we will manipulate
    fig, ax = plt.subplots()
    line, = plt.plot(t, f(t, init_amplitude, init_frequency), lw=2)
    ax.set_xlabel('Time [s]')

    # adjust the main plot to make room for the sliders
    plt.subplots_adjust(left=0.25, bottom=0.25)

    # Make a horizontal slider to control the frequency.
    axfreq = plt.axes([0.25, 0.1, 0.65, 0.03])
    freq_slider = Slider(
        ax=axfreq,
        label='Frequency [Hz]',
        valmin=0.1,
        valmax=30,
        valinit=init_frequency,
    )

    # Make a vertically oriented slider to control the amplitude
    axamp = plt.axes([0.1, 0.25, 0.0225, 0.63])
    amp_slider = Slider(
        ax=axamp,
        label="Amplitude",
        valmin=0,
        valmax=10,
        valinit=init_amplitude,
        orientation="vertical"
    )


    # The function to be called anytime a slider's value changes
    def update(val):
        line.set_ydata(f(t, amp_slider.val, freq_slider.val))
        fig.canvas.draw_idle()


    # register the update function with each slider
    freq_slider.on_changed(update)
    amp_slider.on_changed(update)

    # Create a `matplotlib.widgets.Button` to reset the sliders to initial values.
    resetax = plt.axes([0.8, 0.025, 0.1, 0.04])
    button = Button(resetax, 'Reset', hovercolor='0.975')


    def reset(event):
        freq_slider.reset()
        amp_slider.reset()
    button.on_clicked(reset)

    plt.show()
```

```
# Cell 3
dummy_plot()
```

Freezing occured every time I tested. Sometimes when moving just one slider, sometimes moving first one then the other. 

Will also try out the insiders version.

**Comment by oliverw96** [comment]
Unfortunately the same issue on the insiders version.

**Comment by rchiodo** [comment]
Can you check the CPU usage? Is something pegging the CPU?

It would be useful to know if it's vscode or a python process.

**Comment by rchiodo** [comment]
Oh I just repro'd it. Looks like a bug in matplotlib. I can repro the same thing in a jupyter notebook

![image](https://user-images.githubusercontent.com/19672699/165392856-d870fbd0-5854-44de-94cd-420c811da824.png)

You might try logging an issue here:
https://github.com/matplotlib/matplotlib/issues

**Comment by oliverw96** [comment]
Ok, thank you very much for your help.
