### ISSUE TITLE
errors not rendering while debugging web

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#9782]
while testing https://github.com/microsoft/vscode-jupyter/issues/9767

run the "Extension (web)" from source
Connect to an remote jupyter server
Run a cell with an error

result:
```
Error loading preloads:
Failed to fetch dynamically imported module: https://file+.vscode-resource.vscode-cdn.net/c%3A/src/vscode-jupyter/out/webviews/webview-side/errorRenderer/errorRenderer.js
```

![image](https://user-images.githubusercontent.com/2019016/165354257-9c856437-6c19-483a-a362-be34ac2c4235.png)

**Comment by rchiodo** [comment]
Did you build the webviews? As in does that path exist?

**Comment by amunger** [comment]
ah, nope. someday I'll remember to do that after running git clean
