### ISSUE TITLE
Odd (undefined) in front of file name when running extension in browser

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#9788]
Testing #9767

Note the 'undefined' at the start of the file name. It's not part of the file name. Happens to all files open in browser. Probably a core issue?

<img width="398" alt="image" src="https://user-images.githubusercontent.com/812783/165362257-7433d9fb-220c-4c73-9cb3-e2308b2d9d29.png">

**Comment by rchiodo** [comment]
I think this is a vscode-test-web problem. Doesn't happen in insiders.vscode.dev:

![image](https://user-images.githubusercontent.com/19672699/165387501-4a947af5-577a-4a30-a1c3-91a7e632ff2f.png)

**Comment by greazer** [comment]
Only a problem in testing. Closing.
