### ISSUE TITLE
vscode.dev constantly pings the remote jupyter server with forbidden requests

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#9801]
1. start a jupyter server in cmd
2. install the jupyter extension on https://insiders.vscode.dev/ and connect to that remote server
3. run a cell
4. end the jupyter server and start a new one

result:
The jupyter server command line gets quickly filled with 403 errors as vscode is trying to connect with the old token, making it hard to copy the address/token for the new server.
Even after connecting to the new server, the 403s keep coming until vscode is closed

**Comment by greazer** [comment]
Looks like this is occurring due to a potential issue in @jupyterlab/services

**Comment by DonJayamanne** [comment]
Found the bug in our code

**Comment by rebornix** [comment]
I'm still seeing the pings.

**Comment by DonJayamanne** [comment]
@rebornix please could you provide some steps to repro this issue.

**Comment by amunger** [comment]
the original repro steps still cause 403s for me

**Comment by DonJayamanne** [comment]
No one else has reported this issue and this doesn't really cause any problems, but logs messages in some rare cases (which I've been unable to repro)
