### ISSUE TITLE
Test rerunning the same notebook failed the first time

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode-jupyter#9809]
Testing #9769

When I reopen the notebook the first time, and try to run `print("c")` i get this error.

<img width="846" alt="Screen Shot 2022-04-27 at 1 43 05 PM" src="https://user-images.githubusercontent.com/17892325/165630273-c97a9aaf-594f-4f30-a4cc-ccd9980a7db4.png">

But when i run again the cell with `c=5`, close and reopen the notebook then it works.

<img width="595" alt="Screen Shot 2022-04-27 at 1 43 31 PM" src="https://user-images.githubusercontent.com/17892325/165630511-cd29c160-5ee8-4b76-b7a4-ac2c0a8fbe5d.png">

**Comment by rchiodo** [comment]
Thanks.

Just to be sure, the first time you created the notebook, you ran c=5? Did you rename it/save it after that point? That would likely explain the issue.

**Comment by rchiodo** [comment]
Oh actually I'm reproing this. This is a regression.

**Comment by rchiodo** [comment]
Might be related to the name of the notebook. It doesn't match.

**Comment by rchiodo** [comment]
Or maybe it requires @IanMatthewHuff's change for finding a specific notebook. Not sure why we wouldn't pick the existing kernel anymore.

**Comment by DonJayamanne** [comment]
> sure why we wouldn't pick the existing kernel anymore

i don't think ians chances are in yet.

**Comment by rchiodo** [comment]
No I didn't mean Ian's change caused it, a change in VS code core (Peng's change) might have caused it. 

Debugging it now, it looks more like the kernel refactor I did for the notebook controller manager. It was no longer firing the 'remoteRefreshed' event.

**Comment by IanMatthewHuff** [comment]
@rchiodo I don't believe my change would fix this. The existing kernel should be the top ranked connection in the previous implementation and should also be top ranked kernel (and flagged as an exact match) in my implementation. However it is a good scenario for me to check to make sure that my changes don't regress.

**Comment by rchiodo** [comment]
This brings up another point, @IanMatthewHuff I think your change could eliminate this class:
https://github.com/microsoft/vscode-jupyter/blob/261afd99b9880e31de1fc1e27aa49c836253fcb0/src/notebooks/controllers/liveKernelSwitcher.ts#L54

This class was responsible for picking the preferred interpreter for remote. Shouldn't be necessary anymore.

**Comment by DonJayamanne** [comment]
> was no longer firing the 'remoteRefreshed' event.

rather than bringing ians change at the last minute I'd rather restore the old functionality

**Comment by rchiodo** [comment]
Yeah I have a fix for it already. I restored the event.

**Comment by DonJayamanne** [comment]
also don't we'd have s test for this? 
i thought we had a test for this exact case. possible the test is busted

**Comment by rchiodo** [comment]
Yeah we do have a test, not sure how it's working

**Comment by rchiodo** [comment]
I think the test is passing because it's forcefully selecting the correct kernel. waitForKernelToGetSelected doesn't distinguish between us selecting and it selecting.

**Comment by DonJayamanne** [comment]
> waitForKernelToGetSelected

should be split into two functions, one to wait and the other to forcefully select. else the tests are wrong, as the author don't know the difference in functionality

**Comment by rchiodo** [comment]
> > waitForKernelToGetSelected
> 
> should be split into two functions, one to wait and the other to forcefully select. else the tests are wrong, as the author don't know the difference in functionality

Well I didn't split it, just added another parameter. This test is the only spot we'd need to not do the selection.

**Comment by rchiodo** [comment]
Verification steps (from test plan):

# Test Connecting to a kernel
1. Go to a command prompt where you've installed jupyter into a python environment
1. Switch to a folder you're using for testing
1. Run jupyter with the following command jupyter notebook --no-browser
1. It should print a URL, copy this to the clipboard
1. Start VS code
1. Pick the same folder you ran jupyter from in step 2
1. Run the 'Jupyter: Specify jupyter server for connections' command
1. Pick 'Existing'
1. Paste the URL from the jupyter notebook server you started in step 3
1. Create a new notebook
1. Add something like 'print("hello world")' into a code cell
1. Run the cell
1. There should be a 'Python 3' remote kernel in the drop down list at the top right:
1. Pick that kernel
1. Cell should run
#  Test rerunning the same notebook
1. Run steps 1-10 from the previous test
1. Add code like so in the first cell: a = 4
1. Run the first cell
1. Close the notebook
1. Reopen the notebook
1. Add another cell: print(a)
1. Run JUST this new cell
1. It should print 4
