### ISSUE TITLE
Test connecting to an https jupyter server

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode-jupyter#9810]
Testing #9769

I'm not sure this is what should happen.

When i try to pick the remote server i get this error.

<img width="477" alt="Screen Shot 2022-04-27 at 1 58 26 PM" src="https://user-images.githubusercontent.com/17892325/165631031-dae3ddb1-64f2-4b6b-94a4-7c70581ac606.png">

**Comment by rchiodo** [comment]
That's the intended behavior. Sorry I should have mentioned that in the test plan.

**Comment by rchiodo** [comment]
Connecting to a server with an invalid certificate is a security risk, well because it can't be verified that it is who it says it is, so we ask the user.

**Comment by rchiodo** [comment]
Actually no that isn't the intended behavior if you set this property:

```
"jupyter.allowUnauthorizedRemoteConnection": true
```

Did you set that before hand?

**Comment by paulacamargo25** [comment]
Oh no, i have the value set to false, `"jupyter.allowUnauthorizedRemoteConnection": false`. If i change the value to true, i can select the kernel and run the cell.

**Comment by rchiodo** [comment]
Ah okay. So it's behaving as expected. If that value is false the dialog should show up. Thanks.
