### ISSUE TITLE
Filter buttons should move with scrolling of data viewer

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9813]
Ahhh! I should have looked there!

I do still think it would be beneficial to move the buttons, because the screen is much more discoverable than the keyboard shortcut menu. But I would also love to see the tool tips show the keyboard shortcuts (where available) too.

_Originally posted by @charris-msft in https://github.com/microsoft/vscode-jupyter/discussions/9761#discussioncomment-2650690_

**Comment by DonJayamanne** [comment]
Closing this issue as there haven't been any upvotes for this issue
