### ISSUE TITLE
Restarting in IW creates two 'restarting' messages

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9827]
![image](https://user-images.githubusercontent.com/19672699/165856107-51fd1306-0106-4105-bcec-781e7f7c5ede.png)

**Comment by DonJayamanne** [comment]
Weird, I don't see this.

**Comment by amunger** [comment]
I am also unable to repro this

**Comment by rchiodo** [comment]
Happens every time for me. Must be a timing thing.

**Comment by rchiodo** [comment]
![image](https://user-images.githubusercontent.com/19672699/166322915-7b33d4f7-4d7a-45ac-a59a-208295e0f556.png)

**Comment by amunger** [comment]
@rchiodo - are you still repro'ing this? I still haven't seen this occur

**Comment by rchiodo** [comment]
It happened once yesterday when we were testing. I was on web.
