### ISSUE TITLE
Cells interminable after server closed

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-jupyter#9828]
Testing #9768

After closing the server in my local terminal, I tried running a cell on the browser. It started to run and did not stop, or respond to the stop button:
<img width="915" alt="image" src="https://user-images.githubusercontent.com/8586769/165856983-a0cf0abe-b5c6-413a-8f0a-c775c501a3c1.png">

**Comment by rchiodo** [comment]
Thanks for the issue.

Seems like the remote kernel should fail? Might depend upon what the active connection does in this situation. It might sit there forever.

**Comment by DonJayamanne** [comment]
This issue applies to local as well, not specific to web. I.e. its an existing issue, but will be more common in web as web will only support remote (at least for now).

**Comment by DonJayamanne** [comment]
This might be fixed now.

**Comment by rchiodo** [comment]
Sorry still repros for me.

**Comment by rzhao271** [comment]
1. Pressing the stop button still does nothing. I have to wait for around a minute to see the message that the server isn't available.
2. One of the messages is in monospace and the link isn't rendered properly:
![Screenshot showing badly formatted message](https://user-images.githubusercontent.com/7199958/186779156-34210724-370f-41e9-9a07-b9b8689831bc.png)
