### ISSUE TITLE
Active live session not picked as preferred on reopen

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#9829]
Ran into this while testing my exact match changes. But looks like it existed previously in stable v2022.3.1000901801 as well.

Repro:
start `jupyter notebook` from the command line
start up a notebook session with a new notebook in the jupyter browser
open VS Code in the same folder
open the file, in the kernel picker select the active session
run a cell in the file
close the file
reopen the file
The correct active session is the controller and is selected
But looking at the kernel list some random kernel is suggested, not the active session

**Comment by IanMatthewHuff** [comment]
It generally works since vscode persists the selection, but the suggestion is still wrong.

**Comment by IanMatthewHuff** [comment]
Logging looks to be doing the right thing?
Info 15:57:09: Preferred Remote kernel for ~/Documents/DataScience/Endgame/bugbash/FromJupyter.ipynb is a76e62dd-f0e3-4757-8e20-5b046b45aad0
Info 15:57:09: PreferredConnection: a76e62dd-f0e3-4757-8e20-5b046b45aad0 found for NotebookDocument: ~/Documents/DataScience/Endgame/bugbash/FromJupyter.ipynb
Info 15:57:09: TargetController found ID: a76e62dd-f0e3-4757-8e20-5b046b45aad0 for document ~/Documents/DataScience/Endgame/bugbash/FromJupyter.ipynb
Info 15:57:09: Setting controller affinity for ~/Documents/DataScience/Endgame/bugbash/FromJupyter.ipynb a76e62dd-f0e3-4757-8e20-5b046b45aad0

**Comment by greazer** [comment]
@rchiodo isn't able to repro with more recent changes.
