### ISSUE TITLE
VS Code extension host crashes when running a single cell in a large notebook

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9830]
* Connect to WSL from VS Code
* Create a notebook with around 200 cells each with a simple print such as `1`.
* Run the first cell
* Extension host crashes

**Comment by greazer** [comment]
We need to better understand what's happening here.

**Comment by greazer** [comment]
I was able to get the extension host to crash once in trying to repro this. However, I can't consistently repeat it so far. 

The repro involved a copy paste into a new notebook. 

I did notice that trying to copy/paste >n cells into a new notebook doesn't always work. I can repro if I try to copy/paste 200 cells. But it can paste less than n. I'm not sure what n is at this point.

**Comment by DonJayamanne** [comment]
Tried 12 times, no luck, cannot repro anymore.
@amunger @greazer @rchiodo Can one of you repro this again.

**Comment by rchiodo** [comment]
Works for me. No crash. Tried it with 360 prints.
