### ISSUE TITLE
Copy from interactive window doesn't work in new versions

### ISSUE THREAD

**Issue by michaelmiscanuk** [microsoft/vscode-jupyter#9843]
## Environment data

-   VS Code version: 1.69
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): v2022.4.1
-   OS (Windows | Mac | Linux distro) and version: W10
-   Python and/or Anaconda version: 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local 

## Expected behaviour

I expect text from Interactive window to be copied normally, by CTRL+C.

## Actual behaviour

In new versions I cannot copy anything - normal output and error messages. 
Downloaded today the November version from 2021. And I works better as I was used to for month, like this. I can copy outputs normally - by dragging over it - ctrl+c - ctrl+v to the code or elsewhere and it will paste normally. 
![image](https://user-images.githubusercontent.com/37830487/165992937-e542dcf0-66bf-4092-b115-f05d9083b285.png)

For error messages it doesn't work so preferably - I need to click ... button in upper right corner, choose "Change Presentation" and then built in - Now it will be possible to copy error messages. And again in new version (1.69) I am not able to change to this build in. 
![image](https://user-images.githubusercontent.com/37830487/165993544-27a5d720-0e78-46df-bd19-b72c7dbc4e8a.png)

**Comment by amunger** [comment]
The current stable version for vscode is 1.66.2 and insiders is 1.67, where are you seeing the version is 1.69?

I wasn't able to repro this in either stable or insiders - both error renderers are copyable for me.

**Comment by michaelmiscanuk** [comment]
> 

Yes, sorry. I wasn't sure about the latest version, since I was writing it with reinstalled old version. 
So you are saying that copying of the Output AND Error messages works normally for you? Can it be something on my side then?? 
Thanks

**Comment by amunger** [comment]
yes, copy pasting works as expected for plain text output and error output. Also, both Jupyter and the built-in error renderer are available for me. Were you saying that the built-in error renderer is no longer an option?

![image](https://user-images.githubusercontent.com/2019016/166268584-0807c12b-d6ba-47e1-bfbb-6bb72b23638b.png)

Is it only the error output that does not copy? Is the text still selectable?
