### ISSUE TITLE
Jupyter Powertoys not completely working on candidate April Release of VS Code

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#9868]
- Install candidate release of vscode from https://builds.code.visualstudio.com/builds/stable
- Install candidate release of jupyter extension from https://dev.azure.com/monacotools/Monaco/_build/results?buildId=169234&view=artifacts&pathAsName=false&type=publishedArtifacts.
- Install the Powertoys extension from the Marketplace

Neither the contextual help nor the kernal management feature will work. Execution groups do work though.

**Comment by rchiodo** [comment]
Root cause - we only allow our API to be used in insiders. Whoops.

**Comment by roblourens** [comment]
Is there a fixed build yet?

**Comment by rchiodo** [comment]
Yes published it a couple of hours ago.
