### ISSUE TITLE
Ctrl+C doesn't break out of an infinite loop while a cell is running.

### ISSUE THREAD

**Issue by shangong** [microsoft/vscode-jupyter#9874]
## Environment data

- VS Code version: 1.53.0 insider
- Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
- Python Extension version (available under the Extensions sidebar): v2021.1.431416030-dev
- OS (Windows | Mac | Linux distro) and version: Mac
- Python and/or Anaconda version: python 3.8.9
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Jupyter server running: Local

## Expected behaviour

Ctrl+C should break out of an infinite loop while a cell is running.

## Actual behaviour

Nothing happens with Ctrl+C. To restart, I have been resorting to restart the entire kernel instead.

## Steps to reproduce:

Run an infinite loop in one of the notebook's cell, and try Ctrl+C. The cell will continue running and timeout after awhile.

**Comment by rchiodo** [comment]
Thanks for the bug.

What do you have 'CTRL+C' mapped to? 'CTRL+C' by default is mapped to copy so it wouldn't interrupt a cell.

Additionally what code are you running? Not all code is interruptable. Depends upon what the implementation of the code is.

**Comment by Ishaanjangid** [comment]
So what should we do when there is infinite loop executed by mistake in VS code

**Comment by rchiodo** [comment]
You would hit the interrupt button. Or map a keystroke to the interrupt button (this command here):

![image](https://user-images.githubusercontent.com/19672699/233706969-bc5edee1-590f-46ed-bff3-eea3f3639ae3.png)

**Comment by gbromley** [comment]
For me, the interrupt button does not stop an infinite loop and still resorts to restarting the kernel.

**Comment by rchiodo** [comment]
> For me, the interrupt button does not stop an infinite loop and still resorts to restarting the kernel.

That can happen if the kernel is running native code. In that case there may not be something listening to the messages for the interrupt. It can also depend upon what code you're running.

See this issue here:
https://github.com/ipython/ipython/issues/3400
