### ISSUE TITLE
remote kernels aren't listed until reload

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#9877]
Issue Type: <b>Bug</b>

1. execute the "specify juptyer server for connections" command and select none
2. close vscode
3. start an external juptyer server
4. open vscode and specify that server for connections
5. try to select a kernel

remote kernels are not listed

5. reload vscode and select kernel

remote kernels are listed

Extension version: 2022.5.1001251004
VS Code version: Code - Insiders 1.67.0-insider (7295846887c3a4bf911ba2bd1e64971321cbbb07, 2022-05-03T12:38:20.213Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (15.33GB free)|
|Process Argv|--crash-reporter-id 1202dc88-403d-4ebc-8393-af3551a8bd5b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvspyt640:30438691
vscscmwlcmt:30465136
cppdebug:30475216
vsclangdc:30480125

```

</details>

**Comment by rchiodo** [comment]
This should be a dupe of #9750

**Comment by rchiodo** [comment]
It just takes a minute

**Comment by amunger** [comment]
added steps to the repro, I think you need to specify none for the server first

**Comment by DonJayamanne** [comment]
@amunger Please could you re-test this, it works for me.

**Comment by amunger** [comment]
not repro'ing anymore
