### ISSUE TITLE
Link detection not working with latest ipykernel/ipython

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9879]
<img width="398" alt="Screen Shot 2022-05-04 at 05 58 07" src="https://user-images.githubusercontent.com/1948812/166555985-3a6278ae-a287-4fda-88d7-b88f2ac8736f.png">

**Comment by rebornix** [comment]
@amunger may I ask what's the guidance for upgrading the kernels to a state where I can get cell error links for notebooks?

**Comment by amunger** [comment]
I get links in the error renderer with:
ipykernel: 6.13.0 
IPython: 8.3.0
