### ISSUE TITLE
ESLint rules to enforce layering

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9891]
Was thinking the following
- platform can use nothing else
- kernels can only use platform, telemetry
- notebooks can only use platform and kernels and telemetry
- interactive can only use platform, notebook, and kernels and telemetry
- webviews can only use platform and telemetry
- intellisense can only use platform and telemetry
- test can use anything
- telemetry can only use platform
- [ ] linter should prevent *.vscode.web.test files from importing node modules @amunger

**Comment by greazer** [comment]
Iteration candidate, probably not for May.

**Comment by DonJayamanne** [comment]
@rebornix is anything else required here?

**Comment by DonJayamanne** [comment]
Closing as completed.
