### ISSUE TITLE
Jupyter doesn't update env values on restart when .env file gets updated

### ISSUE THREAD

**Issue by vladpy8** [microsoft/vscode-jupyter#9893]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Hello

It seems that VSCode and Juputer extension don't update environment variable values, when value is changed in .env file.

.env file is located in VSCode/Juyter/project root directory

Action, which, I believe, will reproduce issue:

1. Set some variable value in .env: 

`MY_CUSTOM_VAR=value_1`

2. (Re)Start .ipynb and check value has been set:

`os.getenv('MY_CUSTOM_VAR')`
> 'value_1'

3. Change value of the very same variable in .env:

`MY_CUSTOM_VAR=value_2`

4. Reload and restart VSCode and kernels as many times as you believe necessary, but at least once
5. Observe that variable's value doesn't change:

`os.getenv('MY_CUSTOM_VAR')`
> 'value_1'

Is that intended behaviour?

I use conda environment packaged with python, ipykernel and jupyter:
```

name: test
channels:
  - conda-forge
  - defaults
  - microsoft
dependencies:
  - tqdm
  - jupyter
  - lxml
  - python=3.9
  - matplotlib
  - pandas[version='>=1.4']
  - ipykernel
  - openpyxl
  - gspread
  - aiohttp[version='>=3.8']
  - pylint
  - dataframe_image

```
(some packages have been removed for security reasons, but should work)

### VS Code Version

1.66.2

### Jupyter Extension Version

v2022.3.1000901801

### Coding Language and Runtime Version

3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59) [GCC 10.3.0]

### Anaconda Version (if applicable)

4.12.0

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment]
Thanks for the issue. This is a known issue: #9774.
