### ISSUE TITLE
IPySheets test seems to fail consistently on raw non conda 3.9

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9901]
Get this error.

```
Render IPySheets:1 | Widget did not render or Hello, World, 42.000 not in html = <div class="cell-output-ipywidget-background"><div class="cell-output cell-output"></div></div>
```

Haven't looked further. Maybe ipysheets doesn't work without jupyter on 3.9.

**Comment by DonJayamanne** [comment]
Hmm, haven't seen this failing in my PRs. I'd say its flaky, but not consitent, don't see this failing here https://github.com/microsoft/vscode-jupyter/runs/6296118628?check_suite_focus=true

**Comment by DonJayamanne** [comment]
@rchiodo please could you point to the failing PR, i'd like to see the logs.

**Comment by rchiodo** [comment]
https://github.com/microsoft/vscode-jupyter/runs/6297915635?check_suite_focus=true
