### ISSUE TITLE
Do not start multiple kernels when running a single cell in a notebook

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9909]
Curious why the descrepancy.
It would be a lot cleaner and simpler to just have jupyter to restart local (non-raw) kernels as well instead of us shutting it down and restarting a kernel.

Behind the scenes jupyter does the same thing, they kill the kernel process and start a whole new process.

I feel this will greatly simplify our code, by removing a lot of the code related to restarting

### User bug
See issue #9700
Note: Marked as bug as we end up starting multiple R kernels that chew up resources on end user machines, i.e. starting multiple processes is not cheap.

**Comment by greazer** [comment]
@rchiodo recalls that restart was slower than killing and restarting it.

**Comment by DonJayamanne** [comment]
> restart was slower than killing and restarting it.

yes, but that wasn't true anymore and that's why we removed the restart session.
ie we realized it wasn't slow never removed the restart session we created.

let's add some telemetry around this. i don't think we need this anymore. 
else why not do the same for remote as well.

**Comment by DonJayamanne** [comment]
TODO:
* Investigate starting just one process (no restart process)
* Investigate having a single interrupt process
