### ISSUE TITLE
Python interactive window delete last cell output shortcut/button

### ISSUE THREAD

**Issue by MbBrainz** [microsoft/vscode-jupyter#9914]
When you run a python cell using the interactive window, you encounter the common situation where there is an error. The error messaging of python can be really long and if you're trying to run different approaches of your code, this may lead to multiple super long cell outputs in your interactive window. To clean this up without removing your previous good outputs, it requires quite some scrolling and clicking. 

This could be mitigated by either adding a shortcut which deletes the last cell or by adding the option to a output cell to delete the cell above.

a very cheap drawing of what i mean:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/35366788/163560434-97236f27-f0c5-44e8-b7e2-b5cfa9ebd380.png">

**Comment by greazer** [comment]
The Jupyter extension could add this.

**Comment by amunger** [comment]
you can now select an IW history cell in insiders and use `DD` or `delete` to remove the cell, which should improve this workflow

**Comment by amunger** [comment]
yes, both input and output of the cell are removed (the action can also be undone if focus is in the history view)

**Comment by zatkins2** [comment]
Was this removed after the most recent release? After updating my VSCode install just now I seem to not be able to delete cells:
![image](https://user-images.githubusercontent.com/46325652/206493628-8be70d24-a227-4b13-8c49-66000e085de7.png)

Install versions:
![image](https://user-images.githubusercontent.com/46325652/206491131-13376d0c-7cc6-48ed-9af7-14accbb7e90a.png)
![image](https://user-images.githubusercontent.com/46325652/206491397-1983f414-ef86-45ad-9574-e90baa465e00.png)
![image](https://user-images.githubusercontent.com/46325652/206491523-890b84d1-1e6f-48d4-83df-33e6ed8d5979.png)
![image](https://user-images.githubusercontent.com/46325652/206491723-b0176475-392f-4512-b042-d24461be9a73.png)

**Comment by zatkins2** [comment]
Thanks. Unfortunately the delete-key trick doesn't work for me (also unfortunately I didn't know that trick in the past, so I can't say if that behavior is also a regression)

**Comment by amunger** [comment]
> Unfortunately the delete-key trick doesn't work for me

That's strange - can you check your keyboard shortcuts for `Notebook: Delete Cell`? There should be an entry from both core and the Extension. Also make sure you don't have focus in the cell input.

![image](https://user-images.githubusercontent.com/2019016/206548365-9ed75efa-ee02-4e32-b871-3915829dd5b3.png)

**Comment by zatkins2** [comment]
Ah sorry! The focus on the cell input was the issue, it works :)

**Comment by amunger** [comment]
I feel like there are a couple quick ways to do this now:

either click to focus the cell container and press delete/DD to delete the cell.
or with the keyboard with focus in the IW input: ctrl+up -> delete -> ctrl+down

Let me know if additional/different functionality would be better though.
