### ISSUE TITLE
command not found when I try execute shell script in jupyter cell

### ISSUE THREAD

**Issue by ztlevi** [microsoft/vscode-jupyter#9917]
## Environment data

-   VS Code version: 1.67.0
-   Jupyter Extension version (available under the Extensions sidebar): 2022.4.1001271738
-   Python Extension version (available under the Extensions sidebar): 2022.6.0
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: python3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): poetry
-   Jupyter server running: Local

## Expected behaviour

<img width="225" alt="image" src="https://user-images.githubusercontent.com/16655096/167047591-e19181d7-ea2b-4371-90b4-3c1d30ba6c0b.png">

## Actual behaviour

<img width="506" alt="image" src="https://user-images.githubusercontent.com/16655096/167047581-151e1433-f03e-4415-a189-fc0159b16143.png">

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

This is due to my personal setup in zsh https://github.com/ztlevi/dotty-config/blob/652cff7fae4abadaa8016847933c71c235250b2d/env#L81

- To reproduce, you'll probably need to set zsh as default terminal in macOS. Newer macOS already use zsh by default.
- Add the following code to your zshrc
```
function _load_all() {
  mkdir -p $HOME/Downloads
  local topics=($(ls $HOME/Downloads))
}
_load_all
```

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
info 17:27:20.562: Execute Cell 5 xxx.ipynb
info 17:27:21.148: Cell 5 executed with state Success
```

</p>
</details>

**Comment by amunger** [comment]
thanks for the bug, not sure why that would be happening.

**Comment by greazer** [comment]
Seems to possibly be related to #9682, @DonJayamanne, please check.

**Comment by ztlevi** [comment]
@DonJayamanne Compare side by side, left is the PATH print from vscode notebook, right is PATH print from jupyter notebook.

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/16655096/167950832-101eee28-3e8f-44c6-bce3-5dd7d2e0e908.png">

Left doesn't have `/bin` in the PATH where mkdir and ls located there. Furthermore, there are other bin paths missing. How is the PATH loaded in vscode notebook? Shouldnt' it use default $SHELL's PATH?

**Comment by DonJayamanne** [comment]
@ztlevi thanks for getting back with the information.
The path variables are inherited from the VS Code process. As you haven't launched vscode from a shell process, the environment variables are completely different.
Basically the vscode application (& other desktop applications) don't initialize any shell scripts and use any of the initialization shell scripts. Jupyter application on the other hand is launched from a terminal, hence the difference in the bahaviour and values of the `path` variable.

As a temporary work around you could:
* Open your user settings.json file and add the following contents
```json
  "jupyter.runStartupCommands": [
    "import sys",
    "sys.path.append('/bin')"
  ]
```

Please note, this is only a work around and we'll be looking into a more permanent fix as part of #9682

**Comment by ztlevi** [comment]
Thanks. This one doesn't work for me. I have to tweak a little bit.
```
  "jupyter.runStartupCommands": ["import os", "os.environ['PATH'] += os.pathsep+'/bin'"],
```

**Comment by DonJayamanne** [comment]
@ztlevi 
Please could you try the following:
* Revert the changes to the `runStartupCommands`
* Exit VS Code completely 
* Start VS Code & test this again to confirm whether it works or not.

Also, please could you provide the output from the `Jupyter` output panel (go into the command palette and select `Jupyter: Show Output`

**Comment by ztlevi** [comment]
Nice. it works!

**Comment by ztlevi** [comment]
Reopening the ticket as this issue happen in latests Jupyter v2023.1.2010391206. VSCode version is 1.75.0

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
