### ISSUE TITLE
Selecting remote prevents local kernels from showing up

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9924]
Not sure what happened, but I'm getting this now if I have a remote connection in desktop vscode:

![image](https://user-images.githubusercontent.com/19672699/167180182-56f274e7-b38f-48e1-8b1e-4866d34caeb7.png)

**Comment by rchiodo** [comment]
No local kernels at all

**Comment by rchiodo** [comment]
Oh maybe this was the bug Don just fixed. Merging main and rebuilding seems to have made it go away.

**Comment by DonJayamanne** [comment]
@rchiodo yes, i submitted a pr and added a comment indicating that id force merge as it was preventing local dev (though did also assign u and others to it for review)
