### ISSUE TITLE
View variable in data viewer does not have a test

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9926]
Test is a little hard to write.

1. Have to run debugger with a breakpoint from python (command should work)
2. Have to wait for breakpoint to hit
3. Have to figure out way to view variable in data viewer (command might work, not sure what the context is)
4. After that would be verification of the dataviewer opening, which we should already have.

**Comment by IanMatthewHuff** [comment]
@rchiodo @sadasant I actually wrote this as part of my data viewer fixing. Didn't realize there was a bug already. Closing.

**Comment by sadasant** [comment]
@IanMatthewHuff thank you!
