### ISSUE TITLE
Request: Add ability for partner extensions to create a new cell

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode-jupyter#9927]
## Overview
We would like to be able to insert a cell into an existing notebook from a different extension, and without using proposed notebook editor APIs.

A potential interface on the extension exports might look something like this:
```
addCell(notebook: NotebookDocument, kind: NotebookCellKind, value: string, options: { reveal?: boolean, select?: boolean, insertIndex?: number // defaults to end of notebook? });
```
Please let me know if more information is needed. Thanks!

**Comment by pwang347** [comment]
CC @rchiodo

**Comment by DonJayamanne** [comment]
> without using proposed notebook editor APIs.

our of curiosity, why don't you want to user the proposed api?
surely that should be possible as you're is a msft extension as well.

else we could end up wrapping a number of vscode api which would be obsolete when the vscode api is stable.

**Comment by DonJayamanne** [comment]
discussed offline, won't be required
