### ISSUE TITLE
Toggle input to appear in notebook output

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#9946]
Feedback from PyCon 2022

"The input box (from the Python's input() function) normally shows up on the notebook output space in classic Jupyter, but the input box is showing up on the top by the command palette. Is there a way for me to change it?"

### In Jupyter
![image](https://user-images.githubusercontent.com/10833267/167353829-53801ac1-d54e-4096-b605-8e2848c27b95.png)
After entering name:
![image](https://user-images.githubusercontent.com/10833267/167353837-6ba761e9-ffa8-4181-b2b8-64d20352fe11.png)

### In VS Code
![image](https://user-images.githubusercontent.com/10833267/167353035-fa67e4ff-c6c9-4b3c-b4c5-d58fedc1781c.png)
After entering name:
![image](https://user-images.githubusercontent.com/10833267/167353746-20244d8d-dc4c-4c7d-b386-1b5d843f393a.png)

**Comment by greazer** [comment]
@minsa110, we've had this feedback before. We're not planning on changing this.
