### ISSUE TITLE
Active kernel session shared between notebook and interactive window

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#9948]
Feedback from PyCon 2022

"Would love to have the Interactive Window kernel to be automatically synced to the active kernel in my notebook. For example, I want to pd.read_csv in my NOTEBOOK, and then play around with that data frame in the IW."

**Comment by DonJayamanne** [comment]
duplicate of https://github.com/microsoft/vscode-jupyter/issues/9517

**Comment by greazer** [comment]
Seems like a possible dupe of #6484. Closing
