### ISSUE TITLE
Add keybindings for next and previous cell are that are supported in notebooks "insert" mode

### ISSUE THREAD

**Issue by joelostblom** [microsoft/vscode-jupyter#9971]
The default keybindings for going the to the next and previous  cell are not working for me (`ctrl` + `alt` + `]/[`). I can still use `j/k` in command mode, but I would like to be able to use these keybinding when in a notebooks "insert mode". I tried rebinding them but that doesn't work either. Are these known to be broken or is there anything I can do to troubleshoot my install? I tried disabling other extensions I use related to keybinding (neovim) and the behavior was the same.

## Environment data

-   VS Code version: 1.67
-   Jupyter Extension version (available under the Extensions sidebar): v2022.4.1011282140
-   Python Extension version (available under the Extensions sidebar): v2022.6.0
-   OS (Windows | Mac | Linux distro) and version: PopOS 21.10
-   Python and/or Anaconda version: 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | local

## Expected behaviour

Keyboard shortcut works

## Actual behaviour

It doesn't work, nothing happens.

## Steps to reproduce:

Being in a jupyter notebook cell in insert mode and pressing the shortcut

## Logs

The output pane is empty

**Comment by rchiodo** [comment]
Thanks for the issue. I see the confusion. Those commands are not enabled in a notebook. They're for the [interactive window](https://code.visualstudio.com/docs/python/jupyter-support-py)

We should probably name them something different so they don't look like they work in a notebook. 

Notebooks require you to leave 'insert' mode (hit ESC key) to move to the next cell. Otherwise the commands enabled are related to a python file.

**Comment by joelostblom** [comment]
Ah thanks for the explanation. It would be great if it was possible define a keybinding for moving between cells without entering command mode in notebooks, e.g. `ctrl` + `j/k` from insert mode. Is there "when" context I could define manually for this, or is it something that would need to be added in an update?

**Comment by rchiodo** [comment]
It would have to be added in an update. The commands you referenced move within a text document and wouldn't apply to a notebook.

**Comment by joelostblom** [comment]
Thanks, I updated the title to indicate that this is a feature request for adding that behavior.

**Comment by rchiodo** [comment]
I know it's not the same thing, but if you're in insert mode and you arrow down through the code, it will go to the next cell. Hitting page down will jump to the end of a cell and arrow down moves to the next cell

**Comment by joelostblom** [comment]
Thanks! I did notice that, but would like a binding for moving between cells directly from insert mode (I currently use this in JupyterLab via the vim addon and find it effective for quick navigation).

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
