### ISSUE TITLE
Support Interactive Window debugging in the Jupyter web extension

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#9974]
Note: Adding item for tracking. But I believe this will not be supported as the old debugging method that IW uses is not usable for remote connections.

**Comment by DonJayamanne** [comment]
Part of this will depend on [Support debugging of Interactive Window using the Jupyter debugger protocol](https://github.com/microsoft/vscode-jupyter/issues/10037)

**Comment by DonJayamanne** [comment]
@IanMatthewHuff I've completed enabling the IW debugger using the Jupyter debugger protocol (works for local and remote Jupyter servers). I have one last PR that adds tests for using the new debugger with remote jupyter server connections.

**Comment by greazer** [comment]
Don thinks that this is complete at this point.

**Comment by IanMatthewHuff** [comment]
Looks good to me. @greazer should I add validation steps? Or did this get tested during endgame?
