### ISSUE TITLE
File synchronization ideas for remote jupyter server

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9975]
Solves this: https://github.com/microsoft/vscode-jupyter/issues/1601

3 options I can think of

When connecting, ask user if they want to 

### Sync
Sync workspace to remote machine. This might use a zip or just the jupyter api to do one file at a time. Might be really slow.

### Roll their own
Do their own syncing/Provide a root on the remote machine to run their kernels from. User provides a file path and we use that as the starting directory for a kernel.

### List files in a separate panel
We add a separate entry in the file panel (like Don did with his extension before) that just shows the files on the remote box. User can open them and interact with them just like normal files. 

This has the added benefit of you don't need to open a folder or anything in vscode.dev.

#### All 3?
We could ask any or all three of these. Or add them one at a time. 

Might also be other options I'm not thinking of.

**Comment by DonJayamanne** [comment]
Closing this issue for now, as we alraedy have a few issues tracking file sync and also issue for UI.

**Comment by DonJayamanne** [comment]
Closing as a dup of [#1366](https://github.com/microsoft/vscode-jupyter/issues/1366)
