### ISSUE TITLE
Better intellisense in the web version of jupyter extension

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9976]
We have this situation here:

![image](https://user-images.githubusercontent.com/19672699/167730383-c1e42413-230d-4431-9f4d-7ce771c962e0.png)

Pylance in the web is basically nerfed. This issue is to figure out a way to use the remote jupyter compute to generate better intellisense.

**Comment by rchiodo** [comment]
Ideas for implementing:

## Proxy idea
- Adding middleware to Python extension that drops all requests when in the web on a notebook (like we had before)
- Jupyter extension then install node and runs pylance on remote machine
- Jupyter extension proxies LSP requests through jupyter to this remote pylance

## Web client idea
- Use languageclient web interface 
- Start an LSP server on the remote jupyter box that serves up the web server?
- Not sure if this is a thing or not.

## File API idea
- Add a file api to LSP where the server can ask the client for the contents of a file
- Jupyter tells python about the API and it's used by the web pylance to read files from the remote jupyter machine
- Would require implementing this first: https://github.com/microsoft/vscode/issues/148967

**Comment by heejaechang** [comment]
let me tag Barry who is working on azure notebook for similar structure @barryt2

**Comment by Igonato** [comment]
When working with Rust notebooks using [evcxr_jupyter](https://github.com/google/evcxr/blob/main/evcxr_jupyter/README.md) extension, code completion in the extension is subpar to the one in the web version (`jupyter notebook`). Is this *the* relevant issue, or should a new one be opened?

**Comment by DonJayamanne** [comment]
>  Is this the relevant issue, or should a new one be opened?

@Igonato please create a separate issue.

**Comment by DonJayamanne** [comment]
Closing this issue as there hasn't been any activity nor upvotes on this issue.
