### ISSUE TITLE
Illegal state: service accessor is only valid during the invocation of its target method

### ISSUE THREAD

**Issue by ChaoXu1997** [microsoft/vscode-jupyter#9981]
## Environment data

-   VS Code version: 1.68.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2022.4.1011282140
-   Python Extension version (available under the Extensions sidebar): v2022.6.1
-   OS (Windows | Mac | Linux distro) and version: win10
-   Python and/or Anaconda version: 3.10.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...) conda
-   Jupyter server running: Local 

I run the python code cell  using *ctrl + enter*, but I get this error message "Illegal state: service accessor is only valid during the invocation of its target method"

![image](https://user-images.githubusercontent.com/72029457/167850891-3717090b-fd33-4e85-b1cc-e12b69891014.png)

**Comment by scherp14** [comment]
+1 for this Issue.
<details>
    <summary>Environment Data</summary>

    -   VS Code version: 1.68.0-insider (8c88267)
    -   Jupyter Extension version: 2022.5.1001331008
    -   Python Extension version: 2022.7.11311004
    -   OS : Windows_NT x64 10.0.19044
    -   Python version: 3.10.4
    -   Type of virtual environment used: venv
    -   Jupyter server running: Local

</details>
<details>
    <summary>Logs</summary>

    Visual Studio Code - Insiders (1.68.0-insider, undefined, desktop)
    Jupyter Extension Version: 2022.5.1001331008.
    Python Extension Version: 2022.7.11311004.
    Workspace folder ${workspaceFolder}
    info 10:0:54.283: ZMQ install verified.
    info 10:0:54.575: Experiment status for python is {"enabled":false,"optInto":[],"optOutFrom":[]}
    info 10:0:54.693: Storing Preferred remote kernel for ${workspaceFolder}\.idea\scratch.ipynb is undefined
    info 10:0:54.693: Starting Jupyter Session id = .jvsc74a57bd00d26cf50effcdb57c75f622c6b7e9474c3daaa66548e3cf03ba59da4565bcaef.${workspaceFolder}\.venv\Scripts\python.exe.${workspaceFolder}\.venv\Scripts\python.exe.-m#ipykernel_launcher for ${workspaceFolder}\.idea\scratch.ipynb (disableUI=true)
    info 10:0:54.695: Creating raw notebook for ${workspaceFolder}\.idea\scratch.ipynb
    info 10:0:54.695: Computing working directory ${workspaceFolder}\.idea\scratch.ipynb
    info 10:0:54.770: Starting raw kernel .venv (Python 3.10.4) for interpreter ${workspaceFolder}\.venv\Scripts\python.exe
    info 10:0:54.813: Kernel launching with ports 9005,9006,9007,9008,9009. Start port is 9000
    info 10:0:55.130: Preferred Remote kernel for ${workspaceFolder}\.idea\scratch.ipynb is undefined
    info 10:0:55.130: Find preferred kernel for ${workspaceFolder}\.idea\scratch.ipynb with metadata {"interpreter":{"hash":"0d26cf50effcdb57c75f622c6b7e9474c3daaa66548e3cf03ba59da4565bcaef"},"kernelspec":{"display_name":"Python 3.10.4 ('.venv': venv)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.4"},"orig_nbformat":4} & preferred interpreter ${workspaceFolder}\.venv\Scripts\python.exe
    info 10:0:55.132: Preferred Remote kernel for ${workspaceFolder}\.idea\scratch.ipynb is undefined
    info 10:0:55.132: Preferred kernel .jvsc74a57bd00d26cf50effcdb57c75f622c6b7e9474c3daaa66548e3cf03ba59da4565bcaef.${workspaceFolder}\.venv\Scripts\python.exe.${workspaceFolder}\.venv\Scripts\python.exe.-m#ipykernel_launcher is exact match
    info 10:0:55.133: PreferredConnection: .jvsc74a57bd00d26cf50effcdb57c75f622c6b7e9474c3daaa66548e3cf03ba59da4565bcaef.${workspaceFolder}\.venv\Scripts\python.exe.${workspaceFolder}\.venv\Scripts\python.exe.-m#ipykernel_launcher found for NotebookDocument: ${workspaceFolder}\.idea\scratch.ipynb
    info 10:0:55.133: TargetController found ID: .jvsc74a57bd00d26cf50effcdb57c75f622c6b7e9474c3daaa66548e3cf03ba59da4565bcaef.${workspaceFolder}\.venv\Scripts\python.exe.${workspaceFolder}\.venv\Scripts\python.exe.-m#ipykernel_launcher for document ${workspaceFolder}\.idea\scratch.ipynb
    info 10:0:55.157: Process Execution: > ~\source\repos\repo\.venv\Scripts\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
    > ~\source\repos\repo\.venv\Scripts\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
    info 10:0:55.163: Process Execution: > ~\source\repos\repo\.venv\Scripts\python.exe -m pip list
    > ~\source\repos\repo\.venv\Scripts\python.exe -m pip list
    info 10:0:55.559: Adding env Variable PYTHONNOUSERSITE to ${workspaceFolder}\.venv\Scripts\python.exe
    info 10:0:55.659: Creating daemon process for ${workspaceFolder}\.venv\Scripts\python.exe with env variables count 76
    info 10:0:55.664: Process Execution: > ~\source\repos\repo\.venv\Scripts\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 2396
    > ~\source\repos\repo\.venv\Scripts\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 2396
    info 10:0:55.716: ipykernel version 6.13.0 for ${workspaceFolder}\.venv\Scripts\python.exe
    info 10:0:55.716: ipykernel location ~\source\repos\repo\.venv\lib\site-packages\ipykernel\__init__.py for ${workspaceFolder}\.venv\Scripts\python.exe
    info 10:0:55.767: Registering dummy command feature
    info 10:0:55.878: Preferred Remote kernel for ${workspaceFolder}\.idea\scratch.ipynb is undefined
    info 10:0:55.878: Find preferred kernel for ${workspaceFolder}\.idea\scratch.ipynb with metadata {"interpreter":{"hash":"0d26cf50effcdb57c75f622c6b7e9474c3daaa66548e3cf03ba59da4565bcaef"},"kernelspec":{"display_name":"Python 3.10.4 ('.venv': venv)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.4"},"orig_nbformat":4} & preferred interpreter ${workspaceFolder}\.venv\Scripts\python.exe
    info 10:0:55.879: Preferred Remote kernel for ${workspaceFolder}\.idea\scratch.ipynb is undefined
    info 10:0:55.879: Preferred kernel .jvsc74a57bd00d26cf50effcdb57c75f622c6b7e9474c3daaa66548e3cf03ba59da4565bcaef.${workspaceFolder}\.venv\Scripts\python.exe.${workspaceFolder}\.venv\Scripts\python.exe.-m#ipykernel_launcher is exact match
    info 10:0:55.880: Preferred Remote kernel for ${workspaceFolder}\.idea\scratch.ipynb is undefined
    info 10:0:56.11: get interrupthandle daemon
    info 10:0:56.16: Process Execution: > ~\source\repos\repo\.venv\Scripts\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"05916a34-de71-47a2-9fb8-c4bffd4a16df" --shell=9007 --transport="tcp" --iopub=9009 --f=%HOMEPATH%\AppData\Roaming\jupyter\runtime\kernel-2396vQuNgDIJPcOV.json
    > ~\source\repos\repo\.venv\Scripts\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"05916a34-de71-47a2-9fb8-c4bffd4a16df" --shell=9007 --transport="tcp" --iopub=9009 --f=%HOMEPATH%\AppData\Roaming\jupyter\runtime\kernel-2396vQuNgDIJPcOV.json
    info 10:0:56.16: Process Execution: cwd: ~\source\repos\repo\.idea
    cwd: ~\source\repos\repo\.idea
    warn 10:0:57.632: StdErr from Kernel Process ${workspaceFolder}\.venv\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
    warn(
    ${workspaceFolder}\.venv\lib\site-packages\traitlets\traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '05916a34-de71-47a2-9fb8-c4bffd4a16df' instead of 'b"05916a34-de71-47a2-9fb8-c4bffd4a16df"'.
    warn(

    info 10:0:57.632: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

    To exit, you will have to explicitly quit this process, by either sending
    "quit" from a client, or using Ctrl-\ in UNIX-like environments.

    To read more about this, see https://github.com/ipython/ipython/issues/2049


    To connect another client to this kernel, use:
        --existing %HOMEPATH%\AppData\Roaming\jupyter\runtime\kernel-2396vQuNgDIJPcOV.json

    info 10:0:57.691: Started kernel .venv (Python 3.10.4), (Raw session started and connected)
    info 10:0:57.691: Finished connecting 04a00a57-a078-41aa-ad52-f97608a0d98d
    info 10:0:57.730: UpdateWorkingDirectoryAndPath in Kernel
    info 10:0:57.730: Initialize matplotlib for ${workspaceFolder}\.idea\scratch.ipynb
    info 10:0:57.730: Executing silently Code (idle) = import os\nimport sys\n%cd "${workspaceFolder}\.idea"\nif os.getcwd() not
    info 10:0:57.773: Executing silently Code (completed) = import os\nimport sys\n%cd "${workspaceFolder}\.idea"\nif os.getcwd() not
    info 10:0:57.773: Waiting for idle on (kernel): 1b936b4d-3459-40a8-8dbf-9130590b10ba -> idle
    info 10:0:57.773: Finished waiting for idle on (kernel): 1b936b4d-3459-40a8-8dbf-9130590b10ba -> idle

</details>

**Comment by Saran33** [comment]
Also experiencing this issue. Unable to run Jupyter in VS Code Insiders latest build on Mac, with any python path

**Comment by meg261995** [comment]
Same issue here with me. Updated VS code insiders yesterday and not able to run notebooks

**Comment by pshvechikov** [comment]
Same for me. Also have update VS code insiders, not able to run notebooks.

**Comment by fschiffers** [comment]
is there any quick fix? I tried using older Python/Jupyter version, but it isn't working. It's highly disrupting my workflow

**Comment by rchiodo** [comment]
It's not a bug in the extension, it's a vscode core issue. See the two issues mentioned above.

You have to go backwards on VS code itself. VS code should be fixing this today though.

**Comment by fschiffers** [comment]
@rchiodo Could you hint me how to go backwards with VS code? I've installed an old version from an old download, but it seemed VS code updated itself to the newest version.

**Comment by rchiodo** [comment]
You have to turn off auto updates and do that again:
![image](https://user-images.githubusercontent.com/19672699/168127008-9276a90c-fafd-459b-8403-ecfb60a9da29.png)
