### ISSUE TITLE
Cannot resolve starting jupyter if active interpreter doesn't support jupyter

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9992]
I have an active interpreter that doesn't support jupyter. 

I open a notebook and pick an interpreter that does have jupyter.

I try to run (with ZMQ disabled).

I get this:

![image](https://user-images.githubusercontent.com/19672699/167963456-925bc1dd-d4e3-4717-9dad-74d797b1348a.png)

In the picture you can see that I have 'condaEnvTest' selected but then it's saying the 'EmptyVenv' doesn't have jupyter installed. Why is it using 'EmptyVenv', well because it's the active interpreter.

This is because the code here: 
https://github.com/microsoft/vscode-jupyter/blob/efc80e4ead49e04dfd4da60b559432820cb0ec79/src/kernels/jupyter/launcher/jupyterExecution.ts#L85

Doesn't allow passing of any kernel information. It should be able to use the currently selected interpreter.

**Comment by greazer** [comment]
Pulling from iteration-candidate and milestone, due to Ian's review yesterday.

**Comment by DonJayamanne** [comment]
> Doesn't allow passing of any kernel information. It should be able to use the currently selected interpreter.

i think this should,
* check interpreter in currently select led kernel

**Comment by DonJayamanne** [comment]
Closing this as we have very few users on non-zmq and no one has run into this issue.
