### ISSUE TITLE
pre release版的jupyter插件会导致vscode前端卡死

### ISSUE THREAD

**Issue by xtay** [microsoft/vscode-jupyter#9999]
Issue Type: <b>Bug</b>

环境：
- vscode或者vscode-insider
- jupyter插件
- python插件

实际表现：
在code cell中输入一些python代码，在自动补全完成后，在高亮生效前，vscode前端会卡死。
例如我想输入"import sys"，在敲完最后一个"s"后，就卡死了，过一会儿会弹出The window is not responding。

期望结果：
当然是不卡死。。。

Extension version: 2022.4.1011282140
VS Code version: Code - Insiders 1.68.0-insider (Universal) (624bbc4fb966bfa34e9486e320a64a138ac337fd, 2022-05-12T05:20:14.804Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|17, 15, 13|
|Memory (System)|16.00GB (1.10GB free)|
|Process Argv|--crash-reporter-id e2acee66-b6ca-4efb-8d64-1e42da35b989|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IanMatthewHuff** [comment]
@xtay Trying my best at a translation here. But does this sound like the same issue?
https://github.com/microsoft/vscode-jupyter/issues/9936

If you have the Pylance extension installed could you try disabling the Pylance extension and trying the scenario again?

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
